### ISSUE TITLE
bounce rate 100 % with exit rate < 100 %

### ISSUE THREAD

**Issue by bruthe57** [piwik/piwik#10004]
How could we have a page with a bounce rate to 100% and an exit rate not equal to 100% ?
Bounce rate should be the percentage of visits that only had a single pageview. This means, that the visitor left the website directly from the entrance page. 
In this case if bounce rate is 100%, exit rate should be to 100% too !

example page "/16415" on demo : http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-04-04#/?module=Actions&action=menuGetPageUrls&idSite=7&period=day&date=2016-04-04 

Cheers

**Comment by sgiehl** [comment]
Exit rate can be lower than bounce rate as a visitor might visit other pages before and afterwards.

For example: 

If a visitor visits pageX and then leaves the page again, it will be counted as entry, bounce and exit for pageY.

If a vissitor visits pageY, then pageX, then pageZ and then leaves the page, pageY will be counted as entry and pageZ as exit.

If we take both visits together we have pageX with 100% bounce (all direct entries left again) and an exit rate of 50% (only the first visit left on that page)
PageY would have 0% bounce and 0% exit rate. PageZ 0% bounce and 100% exit rate.
