### ISSUE TITLE
Welcome page is not coming after piwik installation

### ISSUE THREAD

**Issue by avijitmohanty** [piwik/piwik#10006]
in Apache htdocs i have installed piwik but i cant see the welcome screen .
After hitting the URL i am getting the below page in this format . I am not using any DB currently

Index of /analytics

    Parent Directory
    How to install Piwik.html
    piwik/

I am not getting the Php/html page do i need to do some configuration changes.In Access log of Apache i am not getting any error and error log is not generated

Regard
Avijit

**Comment by tsteur** [comment]
@avijitmohanty I'm not quite sure what you mean when you say you have installed Piwik but you are not using a DB currently? It's not possible to install Piwik without a database. Maybe append `/piwik/index.php` to the URL you are trying to access?

**Comment by avijitmohanty** [comment]
without connecting to database will the piwik welcome page come up ? Do we need to do some php installation also?

**Comment by tsteur** [comment]
You need to install PHP, MySQL, etc. see http://piwik.org/faq/how-to-install/ for more information.

Then you need to open Piwik in the browser and install Piwik. If you don't want to install and host Piwik yourself there are also cloud services that do this for you like https://cloud.piwik.pro/
