### ISSUE TITLE
Show website's favicon in website selector + on other places with website-name

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10016]
Showing website's favicon in website selector would give selecting website better usability and a more individual "here I'm home"(-> I see my websites favicon) look.
Show
- for selected website
- in dropdown

please see attachment

Maybe this could be simply fetched and stored during site setup
on Administration/Websites/Manage websites when clicking save button
(plus always refetch the latest version on every click of this button)

![2016-04-06_20h26_09](https://cloud.githubusercontent.com/assets/5681880/14328272/44164000-fc36-11e5-90f2-b225d2491db3.png)

**Comment by hpvd** [comment]
of course this favicon could also be used/shown on all places were website name is mentioned...

**Comment by hpvd** [comment]
if one would make it even more universal, one could provide on
Administration/Websites/Manage websites
2 Buttons/function:
- fetch favicon
- upload individual icon 
(instead of coupeling with save-button as proposed above)

**Comment by hpvd** [comment]
just noticed this one is related to https://github.com/piwik/piwik/issues/3366
(no simple dublicate but give some more details)

**Comment by tsteur** [comment]
@hpvd I will close this issue as a duplicate for now as they are very similar. I hope that is okay. It would be a really nice feature :+1:
