### ISSUE TITLE
Installing stable release requires beta package, thus conflicting minimum stability requirements

### ISSUE THREAD

**Issue by fschwaiger** [piwik/piwik#10025]
<pre> ...$ composer require piwik/piwik
 Using version ^2.16 for piwik/piwik
 ./composer.json has been updated
 Loading composer repositories with package information
 Updating dependencies
 Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for piwik/piwik ^2.16 -> satisfiable by piwik/piwik[2.16.0].
    - piwik/piwik 2.16.0 requires php-di/php-di 5.0.0-beta1 -> satisfiable by php-di/php-di[5.0.0-beta1] but these conflict with your requirements or minimum-stability

 Installation failed, reverting ./composer.json to its original content.</pre>

**Comment by tsteur** [comment]
I can reproduce this. It works fine when performing a git checkout and then install via composer but not when installing directly via composer. Presume we need to set `minimum-stability` or so in `composer.json`.

BTW: For QA & production systems we recommend to only install builds that are downloaded from http://piwik.org see http://piwik.org/faq/how-to-install/faq_18271/ . Installs via git or composer should be only done for development on local systems.

Feel free to issue a pull request.

**Comment by sgiehl** [comment]
Problem is, that we require a beta of php-di/php-di. But we currently can't require the stable of 5.0.0 as it requires a higher php version than the beta. I think this issue won't be a problem for 3.0 anymore as we will increase required php version aswell.

**Comment by mattab** [comment]
as per @sgiehl comment: it is fixed in Piwik 3 (https://github.com/piwik/piwik/blob/3.x-dev/composer.json#L50) and we cannot fix it in LTS, closing.
