### ISSUE TITLE
2.16.1 debian package

### ISSUE THREAD

**Issue by gebi** [piwik/piwik#10037]
Hi,

Just a friendly reminder, 2.16.1 got released and is again marked _critical_.

Would it be possible to have the debian package mirror be updated at the same schedule as the official piwik release?
As most debian admins have notifications for security releases in repositories but do not actively monitor random websites, especially about software which is installed through a debian repository.

**Comment by tsteur** [comment]
Hi @gebi . Thanks for the reminder. Do you mind creating such an issue in https://github.com/piwik/piwik-package/issues as this is where the debian package maintainer will probably rather see it?

**Comment by gebi** [comment]
thx, will do, in the future.
2.16.1 is already on the servers ;), thx!
