### ISSUE TITLE
mysql driver is not installed - troubleshooting guide is not enough to fix this

### ISSUE THREAD

**Issue by bakku** [piwik/piwik#10035]
Hello !
Yesterday I installed piwik and everything worked well.
Today when I opened it again I got the error:

"The mysql driver is not currently installed"

I googled a bit and found two steps on the FAQ troubleshooting page on piwik.org (http://piwik.org/faq/troubleshooting/#faq_21163). But both steps are not enough to fix the problem. I looked at config.ini.php but everything is set correctly here and also I was able to connect manually to the piwik database.

The Apache log has of course many of these lines:

    [Mon Apr 11 11:48:57.149481 2016] [:error] [pid 47022] [client XXX.XXX.XX.XX:58629] Error in Piwik: Cannot connect to the database:  The mysql driver is not currently installed  This may be a temporary issue, try refreshing the page. If the problem persists please contact your Piwik administrator.

But before these error outputs there are a few lines like these:

    [Mon Apr 11 11:42:49.986962 2016] [:error] [pid 47024] [client 193.174.83.97:51650] PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /var/www/html/piwik/core/Tracker/Db/Pdo/Mysql.php on line 81, referer: http://secret-domain.com/

My php version is 5.5.9.

Does anybody know how to fix this?

Thanks a lot.

**Comment by tsteur** [comment]
Can you ask this question in the Piwik forum? https://forum.piwik.org/ In this issue tracker we only handle feature requests and bugs but don't provide support for server setup. 

Maybe mention whether you actually have PDO installed or maybe Mysqli . Also it might help to google for the error `Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' `

Hope it'll work soon

**Comment by arambadk** [comment]
I ran piwik on Ubuntu, had the same problem. Also had php 5.5.9.

Running `apt-get install php5-mysql` solved my problem.

**Comment by mattab** [comment]
Thanks @arambadk, added `php5-mysql` to the command in the Requirements user guide: http://piwik.org/docs/requirements/
