### ISSUE TITLE
 hasVisits - timezone problem - some sites not archived - no new tracking data for website id XY (between 2016-04-01 22:00:00 and 2015-04-02 01:36:19)

### ISSUE THREAD

**Issue by skleiber** [piwik/piwik#10031]
Since 2015-11 or around Piwik 2.15 i noticed, that some sites were not archived for days, sometimes for weeks. In the archiving reports i get my email, i can see the information from the hasVisits-check in core/CronArchive.php that sites have been skipped ... for example:

**"no new tracking data for website id XY (between 2016-04-01 22:00:00 and 2015-04-02 01:36:19) - Skipped website id XY as archiving is not needed"**

**core/CronArchive.php**
```
if ($hasVisits) {
        $this->logger->info("- tracking data found for website id $idSite (between $from and $to)");
    } else {
        $this->logger->info("- no new tracking data for website id $idSite (between $from and $to)");
    }
```

The hasVisits-check should test, if there were new visits for a specific site the day before; if yes do archiving, if not skip this site. Therefore it **should check**: 
**day before (2016-04-01) in the period from 00:00 to 23.59.**

So the message aboves shows, that the actually used test period 
2016-04-01 **22:00:00** to 2015-04-02 01:36:19  (cronjob starts 01.30)
differs from the expected period, which would be
2016-04-01 **00:00:00** to 2015-04-02 01:36:19 (cronjob starts 01.30)

This is on a server with Europe/Berlin timezone settings, so i have UTC+1h in winter and UTC+2h in summer, see here: http://www.timeanddate.com/time/zone/germany/berlin

With low traffic sites this goes on unitil the first visitor arrives someday between 22:00 and 23:59.
This made this behaviour quite erratic.

Possible solutions:
- change my timezone settings in Piwik backend (per site, global) to London ... but this would change the tracking data
- change core/CronArchive.php ... but this would be overwritten with every update

This behaviour could probably occur in any piwik instance with low traffic sites with deviant timezone settings.

Any hints how to fix this are welcome.

Best regards
Stephan

**Comment by mattab** [comment]
Hi Stephan, thank you for the report! 

This looks like a major bug indeed.  Maybe an upgade to 2.16.1 helps this issue? We recently fixed such issue in Piwik (in #9468 #10022 - see https://github.com/piwik/piwik/issues/8436#issuecomment-208217262 )

if you still experience after 2.16.1 let us know, we shall investigate further.

**Comment by skleiber** [comment]
Last night all data has been archived, no site has been skipped.
It seem that the update to 2.16.1 has fixed this issue.
Thanks for your great support!

**Comment by mattab** [comment]
Great to hear :+1:
