### ISSUE TITLE
When a dimension implements a `goalConversion` method, automatically set `Report::hasGoalMetrics`

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10039]
Our platform goal is to make it as easy as possible for developers to use features like Goals. So far, in a report, a developer needs to set `$this->hasGoalMetrics=true` when the dimension defines goal metrics. However, we could likely detect this automatically if the associated dimension implements eg `onAnyGoalConversion`. See https://github.com/piwik/piwik/pull/10026/files#r59276336

**Comment by tsteur** [comment]
I had a look into this and while I could detect this automatically it would not 100% work since the report would still need to archive a report for goals but only because we are writing a value into `log_conversion` doesn't mean the report generates this report.
Otherwise could have done:
```php
    public function hasGoalMetrics()
    {
        if ($this->hasGoalMetrics) {
            return true;
        }

        if (!empty($this->dimension) && $this->dimension->hasImplementedEvent('onAnyConversion')) {
            return true;
        }

        return false;
    }
```

**Comment by tsteur** [comment]
Maybe we close the issue? Or postpone it to Piwik 4? I think we could just close it

**Comment by mattab** [comment]
Closing for now :+1:
