### ISSUE TITLE
Unlimited paging in lists when selecting all

### ISSUE THREAD

**Issue by dczajkacc** [piwik/piwik#10044]
Steps to reproduce:
1. Find a widget with pagination, e.g. custom vars report - http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=CustomVariables&action=menuGetCustomVariables&idSite=7&period=day&date=yesterday
2. select "all" from dropdown where you can select how many items you want to see
3. click next few times

result: you can navigate through unlimited number of pages
![screen shot 2016-04-12 at 11 40 28](https://cloud.githubusercontent.com/assets/11975672/14456088/6e173a32-00a3-11e6-816b-9f1386215ee1.png)

see "-4 -- 6 of 1"

**Comment by tsteur** [comment]
We could maybe set `$viewConfig->show_pagination_control = false` when `filter_limit=-1` but that wouldn't be 100% safe I presume. There might be visualization / API methods that don't use `filter_limit`.
