### ISSUE TITLE
Visitors -> Overview indicator has not the same values as its widget

### ISSUE THREAD

**Issue by jamais203** [piwik/piwik#10042]
Hi there,

I've some trouble using Piwik 2.16.
I installed Piwik on my server for tracking my websites. Everything's fine, except that the overview indicator has not the same values as its widget. Indeed, the widget has less values than the indicator itself. (see the screenshoot, i hid the name server but trust me it is the same on both =))
I refreshed both several times. 
I was astonished when i discovered that because i thought both get values from the same table.

![refpiwik](https://cloud.githubusercontent.com/assets/14738488/14453723/be233632-0096-11e6-90ed-ecc4d1a8f91b.png)

**Comment by RMastop** [comment]
Hi @jamais203,

You are looking at two different reports here.

`Frequency Overview` shows data for returning visitors only, hence the lower values.
The report you are looking for is `Visits Overview`, below the difference between the both of them:
![image](https://cloud.githubusercontent.com/assets/7987117/14454774/558139c0-009c-11e6-8ff6-603b5dc45f76.png)

**Comment by jamais203** [comment]
@RMastop aha my bad! I get confused with those names. Thank you very much =)
(I close this one then)
