### ISSUE TITLE
Allow goal tracking JS to be used anywhere in page (outside of Piwik script in footer)

### ISSUE THREAD

**Issue by samtuke** [piwik/piwik#10060]
Often goals need to be triggered in the page body in content that is dynamic when the site footer and header are the same. Currently it appears that trackGoal() only works when included in boilerplate Piwik JS code, usually in the page footer. Please generate tracking JS which can be used anywhere in the page, separate to any other piwik tracking code. This will also be necessary for sites with heavy use of dynamic JS content.

**Comment by sgiehl** [comment]
You can always call that method whenever you want. As long as `var _paq = _paq || [];` was already defined (which can also be done in before and outside the tracking code)

For detailed information about the JavaScript Tracking Client see http://developer.piwik.org/guides/tracking-javascript-guide
