### ISSUE TITLE
Provide fallback image-based tracking for manual goal conversion when JS not supported

### ISSUE THREAD

**Issue by samtuke** [piwik/piwik#10061]
Please provide image-based tracking of goal conversion inside <noscript> tags for manual tracking of goals, as a fallback option for when JS is not supported in the browser. Currently it appears that only JS-based goal tracking is supported.

**Comment by sgiehl** [comment]
You can generate a Image Tracking URL for that within Piwik:

![image](https://cloud.githubusercontent.com/assets/1579355/14589529/c0259bb2-04e4-11e6-98a8-1fa9ed6d90be.png)

**Comment by samtuke** [comment]
Thanks for the screenshot. Please can you provide a link to that page? Is it a page within Piwik or part of the general documentation? Searching within Piwik for "image" returns no results.

**Comment by sgiehl** [comment]
It's within Piwik. Go to `Personal Settings` > `Tacking Code`
