### ISSUE TITLE
Make tasks (cron) not only triggerd by visits of website with first (lowest) ID

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10065]
At this time tasks (cron) seem to be trigged only by visits of first website
(lowest ID in manage websites)
If you run a multi-website piwik including some test environments, this may become not suitable.

An example:
you have one of your testing environment as the first website-ID (because one often starts with testing...)
and you does not use it frequently because you moved to an other testing site, you are on holiday..
=> no tasks are triggered (Please see attachment)

=> Maybe it would be possible to to trigger Tasks (cron) by a visit of ANY website...

![2016-04-18_07h17_34](https://cloud.githubusercontent.com/assets/5681880/14594463/2c78cf4e-0537-11e6-9ddc-3547d48a87da.png)

![2016-04-18_07h17_55](https://cloud.githubusercontent.com/assets/5681880/14594464/2f8b9e46-0537-11e6-9466-97e41adf2b8b.png)

**Comment by tsteur** [comment]
I presume you mean trigger the tasks during a tracking request?

I had a look at the code and this should not be bound to any specific website.

**Comment by hpvd** [comment]
thanks for looking at the code.
Just discoverd this time it could not be solved simply visiting our old dev (first ID in list (ID=2)
I'm pretty sure last time this problem of tasks being shown/running only in the past (- X days) could be solved this way.

hmm so there must be another solution - any idea on restarting it?
There were no changes on server etc for 4-5 month so there must be a reason why they stopped working...

**Comment by hpvd** [comment]
hmmm - is this fine on demo?

**Comment by tsteur** [comment]
On demo we have a regular cron job that starts the tasks. 

It should trigger the scheduled tasks during a regular HTTP tracking request (no bulk tracking request). The following conditions need to be met though:
* Config `record_statistics = 1` check `config.ini.php` if it's set
* Piwik is installed which means there is a `config/config.ini.php`, 
* There is a `database[username]` configured in this config
* The config does not contain `installation_in_progress=1`
* No exception / error occurred during the tracking request (if you see data in Piwik for recent days the tracking should be fine)
* Browser archiving is enabled (check in admin, if you see report data in Piwik for recent days this should be fine)

Apart from this maybe check if there is a custom value set for `scheduled_tasks_min_interval` in the config? There could be some more conditions but so far these are the basics
