### ISSUE TITLE
Manage websites: Links to website

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10066]
Would be really handy to have in "Manage websites" links to websites
especially in multi site tracking setups
e.g. to verivy
- which site it is
- is it up and running
- is it broken
- ... 
![2016-04-18_07h31_58](https://cloud.githubusercontent.com/assets/5681880/14594582/3dbcfe32-0538-11e6-87e7-5a1bf8643abf.png)

**Comment by tsteur** [comment]
Good idea 👍

**Comment by hpvd** [comment]
:-)
maybe this is an "easy pick"?

**Comment by tsteur** [comment]
yes, indeed :)
