### ISSUE TITLE
Work-around for #6834 (Numeric value out of range: 1264 Out of range value for column 'visit_total_actions')

### ISSUE THREAD

**Issue by rysiekpl** [piwik/piwik#10064]
Since comments seem to be disabled on the [original issue](https://github.com/piwik/piwik/issues/6834), submitting a new issue to signal the need for a work-around. From the original issue comment thread:

> I think best solution would be to change the type of the field to UNSIGNED MEDIUMINT

Is performing this change manually on our Piwik 2.16.1 install safe? Obviously it should not break anything for the time being, but will it be compatible with future schema changes? Will the schema upgrade script work in a situation where one of the changes has already been done?

Or is there any other workaround?

**Comment by sgiehl** [comment]
will be fixed by #9565 in Piwik 3.0

Doing manual changes to the log_visit table might cause problems, as changes to this table are done automatically based on the definitions in the column files. See https://github.com/piwik/piwik/blob/master/plugins/Actions/Columns/VisitTotalActions.php#L21

**Comment by rysiekpl** [comment]
Great. Still, we are hitting this error in our Piwik instance and it stops us from loading logs -- which we depend on very much. Is there a possible work-around?

We have a testing environment that mirrors production, so we can test stuff without danger, if that helps.

**Comment by tsteur** [comment]
Actually a manual schema change should do the trick as we do not verify which check is actually set (as different SQL versions could report it differently etc). If you update at some point to Piwik 3 it might perform another schema change for that column but this change will just fix it as well.

In Piwik 3 we fixed it here https://github.com/piwik/piwik/pull/10002 by setting the column type to `INT(11) UNSIGNED NOT NULL`. I suggest you do the same see https://github.com/piwik/piwik/issues/9565
