### ISSUE TITLE
PageViews missing one date in Report when using date range starting 4/4/16 or prior

### ISSUE THREAD

**Issue by dianep66** [piwik/piwik#10062]
Data for this page started being collected on 2016-04-06. Note that pulling Page views for range of 4/05 – 4/14 shows page views of 1690:

![image](https://cloud.githubusercontent.com/assets/17013164/14566429/6d3465e8-02e4-11e6-88bc-eade2daa2a2a.png)

As soon as you back up the range by one day (2016-04-04) and any dates prior to this date, the Page Views drops out the numbers for 4/08 which had 655 views.
What is interesting is that you can hover over the Row Evolution feature and it does show the 655 views for 4/08, they are just not included in the PAGEVIEWS number in the UI.

![image](https://cloud.githubusercontent.com/assets/17013164/14566436/76f2da06-02e4-11e6-8ec9-081767dd04b0.png)

We are observing this same behavior for all pages within this one Tracking ID pages however we are not observing it for any other tracking sites (ID’s) within Piwik.

Reviewing all error log files and MySQL database files, there are no indications of any issues for the dates of 4/04 or 4/08 and there were no updates to the server on these dates.

Since date of 4/04 appears to be the cutoff date for seeing the issue and is a Sunday, is there an archiving job that is switching to another table to report the views that perhaps didn’t include date of 4/08? Could this repair itself the following week when another archive is created?

Archiving Settings are set to YES for Archive reports when viewed from the browser.

Piwik 2.15.0
Apache/2.4.4 (Win32) 
mysqlnd 5.0.10
PHP/5.4.16

**Comment by tsteur** [comment]
It's hard to tell what is happening here. Is it maybe possible to get access to your Piwik instance and to your database maybe?

**Comment by dianep66** [comment]
I don't think that will be possible since the install is within our Internal Network. Basically for one Site ID when I pull a date range of anything of 4/04 or prior to current date, the resulting report drops the data for one date (4/08). For example if I put in date range of 4/01 - 4/17 the results do not include 4/08. If I put in date range of 4/05 -4/17, results do include data for 4/08.

This also happens if I use selection of "month" April or "year" 2016, the results to do not include data for 4/08. However, the data is in the database when I direct query such as this:

```
SELECT    idaction_name as id, 
          COUNT(idlink_va) as views,
          COUNT(DISTINCT idvisitor) as visits,
          COUNT(IF(idaction_url_ref=0, 1, null)) as entry,
          piwik_log_action.name as page
          FROM piwik_log_link_visit_action, piwik_log_action
          WHERE piwik_log_link_visit_action.idsite= 2
          AND piwik_log_link_visit_action.idaction_name = piwik_log_action.idaction
          AND server_time >= '2016-04-07'
		  AND server_time <= '2016-04-10'
          GROUP BY idaction_name
		  ORDER BY piwik_log_action.name
```

**Comment by dianep66** [comment]
Question: is there some kind of reporting process that we can rerun to update the data?

**Comment by tsteur** [comment]
Yes, this should help I presume: http://piwik.org/faq/how-to/faq_155/

**Comment by dianep66** [comment]
To be clear, marking the date as invalid will not remove data for that date from the database? The way it reads it will "reprocess" the reporting for that date...

**Comment by tsteur** [comment]
It will not delete any logs. It will only invalidate existing report archives. So it is possible to regenerate the archives afterwards

**Comment by dianep66** [comment]
Following the examples in the article, I ran this command in the Console. Does using "Dry Run" mean it didn't actually run or is just showing me the accompanying SQL queries and it did in fact invalidate the dates?

**php ./console core:invalidate-report-data --dates=2016-04-04,2
016-04-08 --sites=2 --dry-run
**
```
``d:\wamp\www\piwik>php ./console core:invalidate-report-data --dates=2016-04-04,2
016-04-08 --sites=2 --dry-run

Invalidating day periods in 2016-04-04,2016-04-08 [segment = ]...
[Dry-run] invalidating archives for site = [ 2 ], dates = [ 2016-04-04, 2016-04-
05, 2016-04-06, 2016-04-07, 2016-04-08 ], period = [ day ], segment = [  ], casc
ade = [ 0 ]
Invalidating week periods in 2016-04-04,2016-04-08 [segment = ]...
[Dry-run] invalidating archives for site = [ 2 ], dates = [ 2016-04-04 ], period
= [ week ], segment = [  ], cascade = [ 0 ]
Invalidating month periods in 2016-04-04,2016-04-08 [segment = ]...
[Dry-run] invalidating archives for site = [ 2 ], dates = [ 2016-04-01 ], period
= [ month ], segment = [  ], cascade = [ 0 ]
Invalidating year periods in 2016-04-04,2016-04-08 [segment = ]...
[Dry-run] invalidating archives for site = [ 2 ], dates = [ 2016-01-01 ], period
= [ year ], segment = [  ], cascade = [ 0 ]

`````

**Comment by tsteur** [comment]
dry run does not actually execute the queries

**Comment by dianep66** [comment]
Thank you for your advice to invalidate the problem dates and regenerate the reports, it appears to have worked and fixed the reported issue.

**Comment by tsteur** [comment]
Awesome, thx for letting us know.
