### ISSUE TITLE
Outlink tracking not working with JS tracker in FF and IE

### ISSUE THREAD

**Issue by sigurros** [piwik/piwik#10088]
Hi,

it seems that the tracking of outlinks does not work, when using the JS tracker in Firefox and Internet Explorer. The tracking of outlinks works fine in Chrome though. Tracking works also fine, when using the JS code provided by the piwik backend. The problem is somehow old and present also in older versions, but the current piwik version I am using is 2.16.0. I have already checked the faq http://piwik.org/faq/troubleshooting/faq_96/ and have played with the tips given there. As the problem does not occur in Chrome I think it is a bug. 

Here is the code I am using for tracking:

```
$j(window).load(function () {
    var pkBaseURL = (("https:" == document.location.protocol) ? "https://foo.bar.de/stats/" : "http://foo.bar.de/stats/");
    $j.getScript(pkBaseURL+'piwik.js', function(){
        // script is now loaded and executed
        var piwik = Piwik.getTracker(pkBaseURL+"piwik.php", "1");
        piwik.enableLinkTracking();
        piwik.trackPageView();
    });
});
```

**Comment by sgiehl** [comment]
Does the outlink tracking work in FF or IE if you open such a link in a new tab/window?

**Comment by sigurros** [comment]
No, have tried this already :-(

**Comment by tsteur** [comment]
If you can send us a link to a page that includes this code we can have a quick look. Feel free to send an email to hello at piwik.org . Afterwards comment here in case the mail goes into spam. 

Actually: Please update to Piwik 2.16.1. This was very likely fixed just recently https://github.com/piwik/piwik/pull/9925

**Comment by sigurros** [comment]
Thanx for the quick response. We will update, check again and I will report the result. Sorry for duplicating bug reports, haven`t found the exisiting one.

**Comment by sigurros** [comment]
After the update, my code is working correct now. Thanks for fixing this!
