### ISSUE TITLE
Photo on the profile of the person entering the web

### ISSUE THREAD

**Issue by octaviz** [piwik/piwik#10089]
In the real-time map when I click on the yellow dot visitor, the picture is not displayed in the profile of the person entering the web, it would be possible to get out the picture?

**Comment by sgiehl** [comment]
could you please explain that a bit more. I don't really understand what exactly you try to describe. Maybe you could add a screenshot to point that out.

**Comment by tsteur** [comment]
We cannot show a picture of the user by default as we do not have this kind of data. However, there are plugins that do something like this eg http://plugins.piwik.org/VisitorAvatar and http://plugins.piwik.org/GrabGravatar . In case you are using one of these plugins already and need to have it also working on the real time map maybe contact the plugin developers directly.
