### ISSUE TITLE
Update Scheduled Reports with Multiple recipients on 2.16.1

### ISSUE THREAD

**Issue by MackieeE** [piwik/piwik#10096]
I'm getting a direct 500 error when attempting to update a report with multiple recipients. At the following POST URL: 

> `analytics.websitename.com/index.php?date=2016-04-26&period=day&hour=19&idSite=1`

With the following *POST* parameters (Taken literally from Chrome Dev tools):

```
module:API
method:ScheduledReports.updateReport
format:json
idReport:1
description:Daily Stats
idSegment:
reportType:email
reportFormat:html
reports[]:VisitsSummary_get
reports[]:VisitTime_getVisitInformationPerLocalTime
reports[]:Goals_get_idGoal--ecommerceOrder
reports[]:DevicesDetection_getType
reports[]:DevicesDetection_getBrowserVersions
parameters[displayFormat]:2
parameters[emailMe]:true
parameters[evolutionGraph]:false
parameters[additionalEmails][]:mackieee@gmail.com
token_auth:5bafcbd0838f3ab93f866a90b71d7e47
```

So when updating a report and adding a recipient 'one per line' at the ***Send report to*** field group. Just add one or two then press 'Update Report' then the exception is immediately thrown and it's stuck on "please wait" on the report update. 

```
{
"result":  "error",
"message": 
  "Uncaught TypeError: Argument 1 passed to Piwik\\API\\ResponseBuilder::getResponseException() must be an instance of Exception, instance of Error given, 
  called in \/home\/websitename\/public_html\/001_subdomains\/analytics\/core\/ExceptionHandler.php on line 90 and defined in \/home\/websitename\/public_html\/001_subdomains\/analytics\/core\/API\/ResponseBuilder.php:130 
  Stack trace:#0 \/home\/websitename\/public_html\/001_subdomains\/analytics\/core\/ExceptionHandler.php(90): Piwik\\API\\ResponseBuilder-&gt;getResponseException(Object(Error))
  #1 \/home\/websitename\/public_html\/001_subdomains\/analytics\/core\/ExceptionHandler.php(70): Piwik\\ExceptionHandler::getErrorResponse(Object(Error))
  #2 \/home\/websitename\/public_html\/001_subdomains\/analytics\/core\/ExceptionHandler.php(36): Piwik\\ExceptionHandler::dieWithHtmlErrorPage(Object(Error))
  #3 [internal function]: Piwik\\ExceptionHandler::handleException(Object(Error))#4 {main}  thrown"
}
```

I'm using the latest version of **Piwik 2.16.1**. I've tested this on:

- Chrome (On Windows 7 & 10 )
- Safari 8.0.8 (Mac)

This Piwik is self-hosted and is running on a subdomain. 

If you need anything at all to help debug the issue or please point me in the direction if this has already been answered :)

**Comment by tsteur** [comment]
I presume you are using PHP 7? Can you change `Exception $e` to just `$e` here https://github.com/piwik/piwik/blob/2.16.1/core/API/ResponseBuilder.php#L130 and see if you get a different error message?

**Comment by MackieeE** [comment]
First and foremost @tsteur my apologies for missing out on providing you vital and key information such as PHP Version! Yes indeed, this is running PHP 7.0.5.

Secondly, removing the `Exception` did start a small trail of removing other methods that also dependant on having `Exception` type hinted (Such as `decorateExceptionWithDebugTrace()` and around 4 others) which eventually came down to `Piwik\\Plugins\\API\\Renderer\\Json::renderException() `. After removing this last typehint, it provided this message gracefully: 

![image](https://cloud.githubusercontent.com/assets/883702/14868898/16c92ade-0cc8-11e6-9729-adc9ee941df3.png)

Which I already immediately knew, I had seen an error message once before on the **System check** which had warned me of the missing `iconv` module. I hadn't rushed to have this fixed as the site is on a Shared VDS host - lazily! 

Hence obviously it's not a bug, configuration error - sorry!

**Comment by MackieeE** [comment]
@tsteur I had iconv installed today by the shared host and no problem whatsoever since. My only suggestion is having the error more gracefully shown - regardless thank you for your time in commenting & helping.

Thank you for the awesome application too Piwik team! :)

**Comment by tsteur** [comment]
Thanks for letting us know. I've created a follow up issue https://github.com/piwik/piwik/issues/10115 to tackle the error message problem.
