### ISSUE TITLE
Bulk request and imageGraph => not well supported

### ISSUE THREAD

**Issue by SimonDmz** [piwik/piwik#10097]
Trying to do multiple imageGraph API requests within a Bulk request, I only get the first graph.

The output screen only show 1 graph, as there is only one '< image >' in the page code where its _src_ value is the complete bulk request.

It would be great if it created a page with one <image> for each sub-request.

**Comment by tsteur** [comment]
This is a bug. It won't be trivial to fix though I think. Using bulk requests for https://github.com/piwik/piwik/pull/7660 would have been probably also a better solution.

**Comment by SimonDmz** [comment]
In fact it's easier to write a PHP page wich make multiple calls and take in charge the page layout

**Comment by tsteur** [comment]
OK, thanks for letting us know. We need to solve this some day either way but won't be soon I reckon
