### ISSUE TITLE
Improve plugins settings structure

### ISSUE THREAD

**Issue by quba** [piwik/piwik#10098]
It would be nice to not have all settings in one `plugins settings` section. Instead of that, I'd suggest to create a new category called `Plugin Settings` and create a separate section for each plugin with defined settings.

**Comment by hpvd** [comment]
good idea - goes into same direction like this one:
https://github.com/piwik/piwik/issues/9998
-> "findability"/ease of acess of settings

**Comment by tsteur** [comment]
I have done this already in Piwik 3 but it's not merged yet as I will be still working on it for a while

**Comment by tsteur** [comment]
it was merged recently
