### ISSUE TITLE
Yesterday's report  data is  empty ? what's happend?

### ISSUE THREAD

**Issue by fxjs** [piwik/piwik#10102]
![bug](https://cloud.githubusercontent.com/assets/3682415/14876635/2170d5aa-0d49-11e6-8fef-853d99dc5602.png)
Yesterday's report of bug data is displayed as 0，
How to fix this bug?

**Comment by tsteur** [comment]
Please update to latest Piwik 2.16.1 if this is not the case yet and then try to invalidate the report so they get re-generated see http://piwik.org/faq/how-to/faq_155/

Just to be sure, does the visitor log show visits for this day?

**Comment by eramirezprotec** [comment]
@tsteur I'm having a similar issue. I don't know what can be happening. I opened a ticket:

https://github.com/matomo-org/matomo/issues/12251

Let me know if there is some possible solution. I have been invalidating the last "done" archiving of the day in the database, that way Matomo regenerates everything and it shows the day as it shoulds. 

Thank you very much.
