### ISSUE TITLE
Not able to enable Tracker

### ISSUE THREAD

**Issue by plegault3397** [piwik/piwik#10107]
- I try to enable a plugin and Piwiki stops reporting data from my websites 
- I enable Tracking and logging and I do not receive any information.
- I disable the plugin and tracking then I start recieving the data again
- I enable tracking alone Piwiki stops reporting data from my websites.

I look at the system check and everything looks fine.
PHP version 	 5.6.5 
Piwik 2.16.2-b1

**Comment by tsteur** [comment]
Which plugin did you enable or which plugin are you trying to enable?

**Comment by plegault3397** [comment]
Well I'm trying to enable IntranetGeoIP 
I enable it and I stop receiving data from my websites, I was asked to enable tracking and I do not receive any tracking information at all.

I only have core plugins enabled at this point and not sure I can enable any others

**Comment by plegault3397** [comment]
I was able to enable the extension and still receive data
Now I need to figure out what the data is no showing up on the real-time map

I installed the ECL GeoIP extension

**Comment by tsteur** [comment]
I suggest you create an issue here https://github.com/ThaDafinser/Piwik-IntranetGeoIP/issues as we are not really familiar with the plugin. The plugin developer may be able to help you.
