### ISSUE TITLE
Error YYYY-MM-DD,YYYY-MM-DD

### ISSUE THREAD

**Issue by ONDABOX** [piwik/piwik#10106]
Just upgraded to version 2.16.1 from 2.8. Looks like all my data is gone. But upon further review an ugly error has resurfaced from 2012:
(
    [result] => error
    [message] => The date '2016-04-27%2C2016-04-30' is not a correct date range. It should have the following format:  'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'.
)
If you urldecode %2C it will produce the comma it's looking for. Not sure how to fix though. Spent 8 hours trying to do it myself. No luck.

**Comment by tsteur** [comment]
What's the URL you are trying to access? Feel free to anonymize the domain name and please remove the `token_auth` in case there is one in the URL.
