### ISSUE TITLE
reporting api token_auth="" access 

### ISSUE THREAD

**Issue by type0lang** [piwik/piwik#10103]
The user anonymous has the "no access" flag set on.
if i do 
```
curl -i -X POST -d '{"requests":["?idsite=1&url=http://example.org&action_name=Test bulk log Pageview&rec=1","?idsite=1&url=http://example.net/test.htm&action_name=Another bulk page view&rec=1"],"token_auth": ""}' http://localhost/piwik/piwik.php
HTTP/1.1 200 OK
Date: Thu, 28 Apr 2016 10:43:10 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Length: 44
Content-Type: application/json

{"status":"success","tracked":2,"invalid":0}

```
I've got 200, and the requests are tracked.

**Comment by type0lang** [comment]
notice the `token_auth=""`

**Comment by tsteur** [comment]
Hi @type0lang there is no token needed for tracking API, even bulk tracking. If you want to force an authentication try setting the config https://github.com/piwik/piwik/blob/2.16.1/config/global.ini.php#L677-L678

refs https://github.com/piwik/piwik/issues/5030
