### ISSUE TITLE
Fresh installation - no icons and half of the webinterface doesnt work

### ISSUE THREAD

**Issue by Levitas** [piwik/piwik#10108]
Hello, after i installed the fresh version with the apt-get repository it doesnt work for some reason.

The page stays blank with the navigation bar on the top of the size.
Also Fonts like font-awesome arent loaded.

It seems taht jquery is not loaded correctly: http://prntscr.com/ayqq04
also in the source code there is no reference to "jquery"

Any suggestion? 

(PS: I got the same problem when i installed piwik manually some days ago on another server)

**Comment by Levitas** [comment]
Edit:
Its only in Firefox, not in Chrome...

**Comment by sgiehl** [comment]
Maybe your Adblocker blocks some files?

**Comment by Levitas** [comment]
c'mon... youre right... the adblocker....
