### ISSUE TITLE
Data not consistent between API and queried to database directly.

### ISSUE THREAD

**Issue by Dharin-shah** [piwik/piwik#10111]
I want abandoned carts information from the table directly. The api to get abandoned carts information is through Goals module. I cant seem to figure out how exactly Goals provides the abandoned carts data since I have explored all the tables in the database. I am not getting consistent data from the database.

**Comment by tsteur** [comment]
@Dharin-shah can you please ask this question in the forum in our Platform category https://forum.piwik.org/c/plugins-platform unless there is actually a bug?

Please provide more information there. Which API you are calling, how you are fetching the DataTable (example code), what exactly the difference between them is (an example of the different data), which Piwik version you are using etc.

In general the API and DataTable should hold more or less same data but there are some filters applied when the API method is called.

**Comment by Dharin-shah** [comment]
@tsteur ,thank you for your response. I will post this in the forum.
