### ISSUE TITLE
piwik submit

### ISSUE THREAD

**Issue by wuyuxiu** [piwik/piwik#10113]
I don't know when users click the piwik's submit botton what document piwik will jump to? thanks

**Comment by sgiehl** [comment]
Sorry, it's not clear to me what you are trying to ask. Could you please explain that a bit deeper?

**Comment by wuyuxiu** [comment]
I  don't know when users click the piwik's submit bottom  what document piwik will jump to?

**Comment by wuyuxiu** [comment]
when we click the "sign in", what page will jump to?what is the document name for the page?

**Comment by sgiehl** [comment]
You mean the target the login form posts to?
I don't think this is an issue or bug. So I'll close if. If you have further questions please use our forums.  https://forum.piwik.org
