### ISSUE TITLE
Error: Invalid dimension 'null'.

### ISSUE THREAD

**Issue by Cruiser13** [piwik/piwik#10117]
I'm using the latest Piwik 2.16.1. If I try to export website statistics (referrers) with expanded data, the following error appears:
Error: Invalid dimension 'null'.

My URL looks like this:
https://domain.com/piwik/index.php?module=API&method=Referrers.getWebsites&format=TSV&idSite=9&period=range&date=2016-04-01,2016-04-30&pivotBy=null&expanded=1&translateColumnNames=1&language=de
URL shortened for privacy.

**Removing pivotBy=null from the URL manually fixes this problem.** I'm not sure why it should be inside the URL, must be generated by the widget.

**Comment by tsteur** [comment]
@Cruiser13 Did you get this URL via the Referrers / Websites report and then clicking on Export => TSV in the footer? I tried to reproduce this on demo.piwik.org but it worked there and did not add `pivotBy=null`. Nonetheless I can imagine there is a bug somewhere and we possibly need to check in the export URL whether pivotBy = `null` and remove it when needed.

**Comment by Cruiser13** [comment]
Hello @tsteur I can reproduce this on demo.piwik.org with the following steps:
Go to the referrers -> Websites & social Media report
Choose the extended version of the websites report so that unique visitors, visitors and actions are displayed.
Try to export. It'll add to TSV as well as to XML the pivotby=null which will cause errors in both export formats.

**Comment by Cruiser13** [comment]
Using Firefox 45.0.2 and 46.0.1 as well as Internet Explorer Edge 25.10586 do show this behaviour - just in case it's a browser related JS issue.

**Comment by tsteur** [comment]
Thanks! I can reproduce it as well now. In case someone else tries to reproduce it "extended" means the "All columns visualization" and it should be caused by this: https://github.com/piwik/piwik/blob/2.16.1/plugins/CoreVisualizations/Visualizations/HtmlTable/AllColumns.php#L70

**Comment by tsteur** [comment]
I hope we can tackle this for the next release

**Comment by mattab** [comment]
Hi @Cruiser13 
do you mind confirming the fix in https://github.com/piwik/piwik/commit/0323adabf29f1eff8b308596881e90496675b861 also fixes the issue for you?

**Comment by Cruiser13** [comment]
Hi @mattab the fix does indeed fix the issue for me. Thanks!
