### ISSUE TITLE
PHP Fatal error:  Call to a member function setLocale() on a non-object 

### ISSUE THREAD

**Issue by Viswan-piwki** [piwik/piwik#10124]
Hi team,
Executing the archive.sh ends up with error PHP Fatal error: Call to a member function setLocale() on a non-object  in /apps/bweb/servers/apache-2.2.20/htdocs/piwik/plugins/PDFReports/API.php on line 416
Any ideas?

**Comment by Viswan-piwki** [comment]
I have disabled the PDF Reports and I see no errors but trying to understand the reason of the error. The piwik version is 1.12

**Comment by tsteur** [comment]
I had a quick look at the code but couldn't find anything obvious. As we do not support Piwik 1.12 anymore I recommend to update Piwik to latest 2.16.X if possible and likely the bug is fixed.
