### ISSUE TITLE
External search engine with same domain as website causes Referrer detection to fail

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#10121]
If we have website tracked with domain of example.com, and using ReferrersManager we define an external search engine to be tracked as referrer, with address containing website domain (search.example.com), then it won't be detected as external search engine but internal website referrer.

Can this be improved so we can fulfill such a usecase?

**Comment by sgiehl** [comment]
Problem is the referrer type detection in https://github.com/piwik/piwik/blob/master/plugins/Referrers/Columns/Base.php#L98-L119
Switching the order of direct entry and search engine detection would solve that for your case, but might have an impact on other cases (e.g. a search engine itself wouldn't be able to track with piwik, as each request would be detected as external request).
Guess we should invest some deeper thoughts on that to avoid problems with other edge cases.
