### ISSUE TITLE
New Config for Log-Import: Filter by Site-ID while --replay-tracking

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#10122]
An option to filter by a Site-ID while importing (with replay-tracking) would be a handy feature. In most cases, Webserverlogfiles contain many Site-IDs. At the moment, it's not possible to import just one or multiple specific IDs, but instead, every Site-ID is imported which was found in the logfile.

To select just one or multiple specific Site-IDs which should be imported could be great in the following cases:
- Migrating a single/multiple specific Site-ID into another instance (at least the lookback window to not have a peak in "New Visitors" metric)
- When you have a mixed setup, some Site-IDs use Javascript tracking, others App-Tracking, others logimport with replay-tracking, you only want the ladder to be imported by the logimporter
- You can store standardized testdata in just one file and just import the datasets you need at the moment
- When the serverside tracking fails (for reasons...) and you use the logimporter (replay-tracking) to catch up to the most recent data state, you want to import the most important Site-IDs first and then the rest (or just specific Site-IDs at all).

**Comment by quba** [comment]
I think that's a better place to add such a feature request: https://github.com/piwik/piwik-log-analytics
I agree that it can be useful but it is also possible to achieve the same with a small bash script (just a few lines).

**Comment by peterbo** [comment]
Oh heck, you're right. Missed that the Logimporter got its own Repo by now. Closing the issue here and reopening there.
To solve the issue with a workaround is not a problem at all. But why working around an issue which could be integrated into core and then be used by everybody?
