### ISSUE TITLE
Display ad blocker message at the top of the screen instead of at the bottom

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10137]
Recently [in the forums](https://forum.piwik.org/t/cannot-add-new-websites/19068/10) an issue was caused by the ad blocker AdBlockPlus blocking assets from loading. The reason that user did not notice the problem is because our useful ad blocker message (introduced in #8949 #5094) is displayed at the bottom of the page and not at the top. It takes user to scroll down to view the message.

Would it be possible to display the message at the top instead?

![monday may 9 2016 - web analytics reports - 2016-05-10 14-19-01](https://cloud.githubusercontent.com/assets/466765/15133771/2b9f8484-16ba-11e6-976f-a9f44c77e090.png)

**Comment by tsteur** [comment]
One of the reasons it is shown at the bottom of the screen is that we cannot detect ad blockers 100% correct and there could be other reasons for it such as problems with internet etc. 

Are you sure what the user posted is related to ad blocker and related to this screen? It doesn't look like it

**Comment by mattab** [comment]
It was not related to ad blocker actually and since it's not possible to display at the top easily as you explain, i'm closing as "wont fix".

**Comment by sandeepjain2015** [comment]
thanks from bottom of heart  @mattab  after remove **adblock**  it is working

**Comment by Findus23** [comment]
will be fixed by #12493
