### ISSUE TITLE
7 days in Evolution over the period when Period is Day

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#10130]
Right now choosing day we got those values : 30, 60,90,180,365,500.

Would be great to add "7" as in a week,

I tried manually changing https://github.com/piwik/piwik/blob/7119a07d7e5bc6416c2f8eeb0823bbea5f840d18/plugins/CoreHome/javascripts/dataTable.js#L476 but it didn't show up even after deleting /tmp/.

Is there a hidden FAQ or setting where I would be able to add such number ?

**Comment by gaumondp** [comment]
Oh well it looks like I forgot to use CTR-F5 before loading the page, it works just editing plugins/CoreHome/javascripts/dataTable.js .

**Comment by tsteur** [comment]
Awesome 👍  Tested it as well and works. Issued a PR here: https://github.com/piwik/piwik/pull/10141

**Comment by gaumondp** [comment]
Thanks @tsteur , it just make sense ! :)

**Comment by gaumondp** [comment]
@tsteur , I'm wondering if 8 days wouldn't make more sense.

Consider this graphic : 
![image](https://cloud.githubusercontent.com/assets/5972510/15822139/0d766a64-2bc2-11e6-980f-cd18f00564e3.png)

Maybe people would expect to see Monday thru Monday?

That's where there's a difference between cold maths and human beings. ;)

**Comment by tsteur** [comment]
Does it maybe make sense to directly make it 10?

**Comment by gaumondp** [comment]
I think 10 days means "nothing", but with 8, you see Saturday-to-Saturday, hence a "real" wee.

I would love to read other's opinion !

**Comment by tsteur** [comment]
OK thx for the feedback 👍 . I've issued a PR and will merge when tests are green https://github.com/piwik/piwik/pull/10228
