### ISSUE TITLE
Are anchor links tracked by default without page reload?

### ISSUE THREAD

**Issue by samtuke** [piwik/piwik#10139]
Specifically regarding goals and funnels, it's unclear to me whether a link to an anchor using an element ID will be tracked by Piwik if no page reload takes place. E.g. if a funnel has three steps, each of which is a different section of a page or different dynamically loaded content, will those steps be recognisable with page URLs or regexes which refer to the ID linked to or not?

https://example.com/signup#step-1
https://example.com/signup#step-2
https://example.com/signup#step-3

With no page reloads, will each of the above be detected as a distinctive step in a funnel?

**Comment by tsteur** [comment]
If there was no actual page reload: no. You will need to trigger a `trackPageview` manually in such a case
