### ISSUE TITLE
.htaccess file ownership in 2.16.1

### ISSUE THREAD

**Issue by Privacywonk** [piwik/piwik#10143]
Upgrading from 2.16.0 to 2.16.1 via UI and command line for database (performed using sudo). Upgrade was successful but upon reloading piwik, I was given a blank page with no plugins or content running.

Investigation found that all `.htaccess` files were owned by **`root:root`** after the upgrade. Looking at previous installations I had archived, these files had all previously been owned by the web server user/group (**`apache:apache`** in my case). No other files that were updated had their ownership changed.

Requests:

1. Detect console commands being run as root to provide a notification to users to check file ownership after upgrade or to discourage people to run the update via sudo / root.
2. Investigate the update for [2.16.1-b3.php](https://github.com/piwik/piwik/blob/master/core/Updates/2.16.1-b3.php) that hard deletes previous .htaccess files and recreating them vs. overwriting.

**Comment by tsteur** [comment]
Thx for creating the issue. We need to find a solution for this. ping @mattab

**Comment by mattab** [comment]
> Upgrading from 2.16.0 to 2.16.1 via UI and command line for database (performed using sudo). 

AFAIK there is no valid use case for running a piwik console command as root. Maybe we should at least catch the use case `console command is being run as sudo / root` and fail the command in this case?

**Comment by mattab** [comment]
> Maybe it is as easy as just updating the file instead of deleting / creating.

Good idea. 

Also another idea: we could detect the web server user/group by looking at files in `tmp/` folder, and when `core:update` runs, if the user is different than the webserver one, issue a warning that this may create permission problems etc.

**Comment by Privacywonk** [comment]
> The problem is not only related to sudo / root. It's a problem when username or group is different to the one of the webserver."

This is my use case for using sudo The apache user on my box is set to nologin so the account is unavailable to su to even as root.

**Comment by mattab** [comment]
>      This is my use case for using sudo The apache user on my box is set to nologin so the account is unavailable to su to even as root.

@Privacywonk  I'm wondering in your case, how this issue could be fixed. What would be the correct way to create files that are writable/readable  by the webserver user? should the files be added to a given group or so?

**Comment by Privacywonk** [comment]
Following the Keep It Simple methodology, a warning before the CLI tool exits would be fantastic.

"Remember to check file ownership in $installdir" 

or if you wanted to provide a bit more context to the admin

"It appears your piwik installation runs under username:group. If you ran this update as any other user, please execute:
chown -R username:group $installdir"

**Comment by blueelvis** [comment]
This can be done by simply checking the owner and group (Or even permissions? ) of the files using `fileowner()` & `filegroup()` functions within PHP. If both are not same before and after the installation, just print a warning just before the CLI tool exits like @Privacywonk said.

Can I work on this?

**Comment by tsteur** [comment]
Sure. It would be good to test first though if it changes anything if we overwrote the content of the file instead of deleting and creating the file (eg `file_put_contents`). Maybe then there would be no problem at all but maybe not :)

**Comment by mattab** [comment]
Thanks for the suggestion. Here is the Pull request that will display a message at the end of core:update command when the user:group of the command process is different from the user:group that own piwik `index.php` file.  https://github.com/piwik/piwik/pull/10424

**Comment by Privacywonk** [comment]
Thank you everyone!
