### ISSUE TITLE
400 (Bad Request)

### ISSUE THREAD

**Issue by kira510** [piwik/piwik#10142]
I recently developed a plugin using dimensions which exports data to another source. I mainly used visit , action dimensions and settings(to set the host name to which piwik data must be exported).  The data export happens successfully but i see 400 error on all the piwik tracked websites. 
The error i get is 
_piwik.php:1 GET http://nce45.net/piwik.php?action_name=Dashboard%20Emb…7x971&_cvar=%7B%221%22%3A%5B%22Access%22%2C%22anonymous%22%5D%7D&gt_ms=126 400 (Bad Request)_

I get this when i click on the issue 
_Piwik is a free/libre web analytics that lets you keep control of your data._ 

Is this because of my plugin? I checked in the forum and did not find any proper solution as such. But many have faced this.

**Comment by tsteur** [comment]
This can have all sorts of reasons. Do you have access to your error logs? Can you see more information there? 

Otherwise you can enable debugging for the tracker as described here http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker and you might also want to enable logging to files here: http://piwik.org/faq/troubleshooting/faq_115/

**Comment by kira510** [comment]
Can we manually add plugins that use dimensions into the plugin directory of Piwik? Using dimensions alters the Database but it should not create any problems?

**Comment by kira510** [comment]
Hello @tsteur,
After investigating, i found the error occurs because of action dimension. Visit dimension works fine but i was using action dimension to track the actions of each visitor.  
This is my code
public function onNewAction(Request $request, Visitor $visitor,Action $action)
    {
            
        

	    // for every action, add one to total number of actions
        $settings = new \Piwik\Plugins\PiwikStatsD\Settings();
		$key1 = $settings->keyName->getValue();
		$actions = $settings->no_of_actions->getValue();
		$idsite = $request->getIdSite();
		$name = Site::getNameFor($idsite);
		$key = $key1."."."$name".".".$actions;
		
        // get port and host from settings then connect to stats		
		$port = $settings->portName->getValue();
        $host = $settings->hostName->getValue();
		$stats = new StatsD( $host, $port);
        $stats ->counting($key,1,1);
		
	return $action->getActionName();
    }

**Comment by tsteur** [comment]
Thx for letting us know what caused the issue. Certainly we have to improve on this part to make it easier to track custom dimensions and to get reports out of it. Especially on the documentation but also the API.

**Comment by kira510** [comment]
Hello @tsteur ,
The issue was with my code and now with piwik. A mismatch of datatype btween the database and the code caused this issue.
