### ISSUE TITLE
trackLink does not invoke callback if request is done via GET ?

### ISSUE THREAD

**Issue by er314** [piwik/piwik#10153]
Trying to understand why it was working with POST, but could not get it to work with GET, 
so I looked at the js code, function getImage, 
whatever I try, image.src fails onerror.
Then tried playing with request parameters, saw "send_image" was set to 0 
-> I set it to 1
-> now it works...
can you reproduce ?
 
my js tracking code :
```
  var tracking_callback = function() { console.log('hello callback'); };
  var _paq = _paq || [];
 //_paq.push(['setRequestMethod', 'POST']);
 _paq.push(['trackLink', 'http://127.0.0.1:81/tools/contact/', 'link', null, tracking_callback]);
 (function() {
    var u='//127.0.0.1:81/analytics/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
	_paq.push(['setLinkTrackingTimer', 300]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
 })();

```

**Comment by tsteur** [comment]
Good point, that's a bug. Makes sense to request an image  👍 

@mattab I move it into 2.16.2 as it's easy to fix but feel free to move it out.

**Comment by mattab** [comment]
@er314 Could you maybe create your PR in the piwik repository, rather than in your fork? Then it makes it possible for us to merge the PR.

Quick review: I think a good way to fix this issue would be to edit `getImage` method, and replace `send_image=0`  (if found) by `send_image=1`.

**Comment by er314** [comment]
Hi,
I did create some PR for some other bugs which I found, and for which I was rather certain about my proposed fix.
Here however, I have zero confidence about the fix, hence no dubious PR proposal... :-)

I have reviewed again the code (piwik.js + core/Tracker/Response.php) , and I think you're right : 
getImage() is used exclusively in case of GET, so if we perform the replacement here, then
- current standard behaviour with default POST requests will be unchanged
- this does allow GET requests to load the 1x1 image, and to call the callback, thus fixing the issue
-> I'm doing the PR :-)

**Comment by tsteur** [comment]
👍

**Comment by mattab** [comment]
Kuddos @er314 for the bug report, and the PR!
