### ISSUE TITLE
Overlay bubbles are not displayed if custom port in http://hostname:port/

### ISSUE THREAD

**Issue by er314** [piwik/piwik#10169]
There's no overlay bubbles displayed whatsoever, on site like http://127.0.0.1:81/
This is due to urlnormalizer.js, which removes the port. Then all comparisons with followingpages do fail. 

-> smallest fix ever : replace "document.location.hostname" by "document.location.host" , in plugins/Overlay/client/urlnormalizer.js : 

         initialize: function () {
              this.setCurrentDomain(document.location.hostname);

**Comment by tsteur** [comment]
Thx for reporting the bug and the solution 👍  Seems like an easy fix so adding it to 2.16.2. @mattab feel free to remove it to another milestone if / when needed.
