### ISSUE TITLE
Tracking downloads

### ISSUE THREAD

**Issue by y-ueyama** [piwik/piwik#10166]
when importing logs for tracking, is there a way to track 206 downloads as separate from other downloads? Currently, this causes a separate download to be tracked for each 206 download, so if someone were to use a download manager which creates 20 or so different sockets, 20 different downloads will be tracked for Piwik.

**Comment by tsteur** [comment]
Do you have an example for such a log file? It's probably not possible to differentiate them but maybe there could be some "smart" way to group multiple downloads from same ip for same resource within a few seconds together. Do you mind creating an issue for this here: https://github.com/piwik/piwik-log-analytics/issues ? That would be great. Ideally also attach an example of a log file containing such a case, that will make it easier to work on it.
