### ISSUE TITLE
Custom Variable data does not allow Page Size change

### ISSUE THREAD

**Issue by bcumberledge** [piwik/piwik#10168]
There is currently no way to change the page size for Custom Variable data.    This affects the UI display of the data and the export of the data when row count is greater than default page size.

Thanks.

https://forum.piwik.org/t/custom-variables-paging-page-size-export/19270

**Comment by tsteur** [comment]
I can't really reproduce this one. In the UI under Visitors => Custom Variables I can change the page size and use paging. Which Piwik version are you using?

**Comment by bcumberledge** [comment]
Are you paging the Custom Variables or the data within each Custom
Variable. I'm referring to 100s of rows within each Custom Variable. Thanks

**Comment by tsteur** [comment]
I was paging the custom variables, but in the data within custom variables the paging works as well. However, there is no limit selector shown. Got it :) 

I think we don't show a limit selector so far in any subtable but not 100% sure so it might be a bit more work then just enabling a flag to show it.

**Comment by bcumberledge** [comment]
Correct. Yes due to that I can't export more than the default page size.
Thanks for verifying.

**Comment by tsteur** [comment]
Try appending eg `&fiter_limit=300` or `&filter_limit=-1` to the URL this might help

**Comment by mattab** [comment]
As we will deprecate custom variables in #11524, closing this issue as Won't fix.

We now recommend to use [Custom Dimensions](https://piwik.org/docs/custom-dimensions/) instead.

**Comment by bcumberledge** [comment]
Thanks.  After years the fix is to not use them.
