### ISSUE TITLE
In Installation > Database setup step, indicate that PDO_Mysql is the recommended driver to use

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10164]
From user feedback:

> i missed informations about the difference of mysql and mysqli or a suggestion which one i should take

Maybe we could simply write `(recommended)` or `(default)` next to PDO_MYSQL in the Select field?

**Comment by blueelvis** [comment]
Can I work on this one? ^_^

**Comment by mattab** [comment]
Hi @blueelvis  - definitely! it is a good issue to get started  :+1:

**Comment by mattab** [comment]
This was done in 2.16.2 cheers @blueelvis
