### ISSUE TITLE
Piwik UI - Display Metrics issue (appearance)

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#10178]
Hi,

Piwik 2.16.1: Under Software reports if we select expanded report for first widget (e.g. Display a table with Visitor engagement metrics) the generated table will be behind other widgets "impossible" to read, unless we:

1) have a enough wide display
2) or we artificially shrink browser's area to activate responsive triggers
3) or less likely, go to source code and delete/hide other widgets temporarily

P.S. I am using 2-column grid layout, this could be solved if I switch to a single column, but that is generally a waste of space. I do not use this report often, so it is not urgent.

Thanks

(screenshot provided with highlighted area in question:)
![piwik ui issue - display metrics](https://cloud.githubusercontent.com/assets/5383059/15465323/4168a2cc-20d4-11e6-8ed6-afe0881faa71.png)

**Comment by tsteur** [comment]
This is a duplicate but I can't find the actual issue for it. @mattab do you maybe?

**Comment by mattab** [comment]
Duplicates https://github.com/piwik/piwik/issues/6159 https://github.com/piwik/piwik/issues/6121
