### ISSUE TITLE
JavaScript SDK: Calling an undefined JS API method should trigger a useful error message to help users locate the issue quickly

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10175]
Example to reproduce:
 * Call in the browser console `    _paq.push(['hello', '//demo3.piwik.org/piwik.php', 1]);`
 * Got: JavaScript error in the browser console: `TypeError: z[Y][ab] is undefined https://demo.piwik.org/piwik.js Line 22`
 * Expected: a useful error message in browser console such as `The method 'hello' does not exist in Piwik Tracker. See the list of methods at: http://developer.piwik.org/api-reference/tracking-javascript

**Comment by tsteur** [comment]
It should still be an error and the same exception. The exception message can be maybe enriched or something but it should still trigger an error. This is important for developers for debugging etc.
