### ISSUE TITLE
Less compiler changes css value of calc

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10173]
Eg when we load a library that defines eg a height as follows:

```
height: calc(100% - 56px);
```
It results in `height: 44%` because of less. This happens even when the input file is CSS. It works when specifying `height: ~"calc(100% - 56px)"`. The problem is we don't want to change any third library CSS files.

I think so far we concatenate simple all files and put them through the Less parser. However, this should not happen for CSS files. We need to find a solution for this. We could find via regex such occurrences of `calc` and escape them but that would be slow and we would likely still have other issues. Ideally, we do not send such files to the less parser and instead put them into the right position after parsing the less. This might make the less parser even faster as it does not have to parse jquery and other css files.

**Comment by tsteur** [comment]
I implemented it with preserving the position by replacing the content with "@import: url(....css)" and later replacing this part with the actual content. It *should* work. It results in less compiling time and the css file size is 30kb smaller as jquery and other libs stay actually minimized

**Comment by mattab** [comment]
> It should work. It results in less compiling time and the css file size is 30kb smaller as jquery and other libs stay actually minimized 

Sounds like the ideal solution!
