### ISSUE TITLE
Document new way to easily send tracking requests to multiple Piwik servers and/or multiple websites ID

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10174]
Let's update [this documentation](http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers) with our new, better way of using multiple trackers.

This was implemented in #10085 #9525

**Comment by mattab** [comment]
@tsteur does this look good? https://github.com/piwik/developer-documentation/pull/132/files?short_path=60f3612#diff-60f3612107814f4dba4f161a21efa02e

**Comment by tsteur** [comment]
left a few comments

**Comment by mattab** [comment]
done, new documentation is available at: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers
