### ISSUE TITLE
Need clarification on the table INFORMATION_SCHEMA.GLOBAL_STATUS  in PIWIK Data Base

### ISSUE THREAD

**Issue by samratng07** [piwik/piwik#10184]
when I use the below query:
SELECT * FROM INFORMATION_SCHEMA.GLOBAL_STATUS WHERE VARIABLE_NAME = 'SLOW_QUERIES';

I get a result:

 VARIABLE_NAME     VARIABLE_VALUE
'SLOW_QUERIES'             '1393'

I need to know what the value 1393 indicates.Is it the number of slow queries currently running on my web application?

Please do help.

**Comment by tsteur** [comment]
This is a MySQL feature and not related to Piwik AFAIK. Please google for it or ask in the forums http://forum.piwik.org/ if you have a question. Thank you 👍
