### ISSUE TITLE
Javascript tracking API, GET method firing multiple times

### ISSUE THREAD

**Issue by Daeno** [piwik/piwik#10182]
I was playing with the Content Tracking API through Google devtool console, and get this weird behavior that the browser fired multiple request in a single tracking event. Code like this: 
```
_paq.push(['trackContentImpression', "test123", 'special character', "http://123.12.12.123"]);
```
will trigger multiple GET request to the piwik server and caused the content impression count increase 2 or more. After googling, this is a browser optimization implemented by chrome. Switching to POST method can solve this problem, but no doc has mentioned this problem. Maybe we can add docs describing this issue and make the default method be "POST".

**Comment by tsteur** [comment]
Are you on the latest Google Chrome version? There used to be a bug in Chrome in one of the recent versions that fired a request multiple times

**Comment by mattab** [comment]
Hi @Daeno, could confirm and try with latest chrome?

**Comment by Daeno** [comment]
I used Chrome **50.0.2661.102 m** on Windows 7 when I reported, still the same on the latest Chrome, version **51.0.2704.63 m**
![image](https://cloud.githubusercontent.com/assets/5570190/15648855/be2e6f00-269f-11e6-9a13-71ba1fe53647.png)

**Comment by mattab** [comment]
Could you post a screenshot showing the problem, and how do you reproduce it?
