### ISSUE TITLE
URLs filter ignored

### ISSUE THREAD

**Issue by soheyb** [piwik/piwik#10183]
Hello,
I recently experienced a problem with a Piwik based system.
Someone scraped the HTML/JS of my website without permission, which is currently tracked by my local Piwik system.
So now, on my visitor's log report, I have some reports from the the other website of the people who scraped my website.
I added my website's URL under Administration -> Websites, which should normally allow only requests coming from my website.
But the External reports are still here.
Any solutions?

**Comment by tsteur** [comment]
Yes, you can configure Piwik to only accept tracking requests for your domain see http://piwik.org/faq/how-to/faq_21077/
