### ISSUE TITLE
Issues with visit over time and blank reports

### ISSUE THREAD

**Issue by samratng07** [piwik/piwik#10198]
We have 5 sites configured in PIWIK.

last week we were getting blank reports for one of the site and no data was shown in the dash board for visit over time although visitors in real time shows non zero values..later it was working fine after some changes from our side via the UI.

But now for another site we are facing the same issue again and the earlier changes wont solve it this time.

in the visit over time field we can see that the number of visits are 0 from past 2days although visitors in real time shows non zero values.

PFA the screen shot ,so all the reports are blank since last 2 days and PIWIK has no data for it.but for last 30 mins and last 24hours we can see data under visitors in real time.for all the other sites everything works fine

Please help.

![image](https://cloud.githubusercontent.com/assets/19566446/15673202/befe6bf2-2752-11e6-85f3-ae6f446be5ca.png)

**Comment by sgiehl** [comment]
Is your data archived using a cron, or is browser archiving enabled in configuration?

**Comment by samratng07** [comment]
no we have not enabled any mode of archving.we have disabled archiving in the settings.

**Comment by samratng07** [comment]
hi this issue still causes inconsistency and makes PIWIK unstable please do advice.we are using 2.16.0 version of PIWIK

**Comment by samratng07** [comment]
Hi we received blank reports again for the weekly reports,although PIWIK UI shows data for these sites.Please help.Why PIWIK is so inconsistent please help.

**Comment by mattab** [comment]
Hi @samratng07 please don't create several tickets for the same problem. thanks.
