### ISSUE TITLE
Getting Issue to loading all website Report Data on the Dashboard Page

### ISSUE THREAD

**Issue by RobinHossain** [piwik/piwik#10195]
I am getting this issue/warning/notice after login on the dashboard page.

"Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance. "
http://www.awesomescreenshot.com/image/1287389/f1d8e9423d17075c0754e800e75287c1

Using PHP Version : 5.6
Can you please let me know what have to do in current situation.
Thanks !

**Comment by tsteur** [comment]
Have a look at http://piwik.org/docs/setup-auto-archiving/ it should help. Please reopen or comment here if not. Cheers.

**Comment by irishabh** [comment]
I did the same. No changes yet. :(

**Comment by tsteur** [comment]
Please have a look in the server logs. There might be some error messages. Maybe the server has not enough memory or something.

**Comment by irishabh** [comment]
Issue resolved. I just need to disable my PageSpeed in cPanel.

Strange but true.

On Tue, 21 Jun 2016 at 00:20, Thomas Steur <notifications@github.com> wrote:

> Please have a look in the server logs. There might be some error messages.
> Maybe the server has not enough memory or something.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/piwik/piwik/issues/10195#issuecomment-227233772>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB17UU1rf5JwDAeDLUvPkCHSmUn8Iyt6ks5qNuDmgaJpZM4IpxmP>
> .
>
-- 
- rishabh
iNFOTYKE
www.infotyke.com
+91-9953-5858-69
+1 (831) 731-5869
+91-9953-5858-79
+91-9953-5858-01
+91-9953-5858-02
