### ISSUE TITLE
run command 'git submodule update --init' error

### ISSUE THREAD

**Issue by liuliuliu666** [piwik/piwik#10197]
When I run 'git submodule update --init' ,it has an error like:fatal: reference is not a tree: fae38dcff43420ee12459aa6f3a89d2a0fca750f
Unable to checkout 'fae38dcff43420ee12459aa6f3a89d2a0fca750f' in submodule path 'tests/travis'.
Then how should I do?

**Comment by sgiehl** [comment]
there was an invalid commit for this submodule. That was fixed already. Simply pull the master and it should work again.
