### ISSUE TITLE
Fix error err_cache_miss on mobile browser when back button

### ISSUE THREAD

**Issue by thanhdlk33** [piwik/piwik#10203]
I 'm having problems with the site running on mobile phones . when I pressed the button on the website if I returned it err error -cache -miss . it only happen on chrome browser.

Who can help me solve this problem ?? Thanks. help.

**Comment by tsteur** [comment]
Can you reproduce this with demo.piwik.org? Which chrome version are you using on which OS?

**Comment by mattab** [comment]
Hi @thanhdlk33 do you have a chance to replicate on the demo.piwik.org and let us know the browser version?

**Comment by mattab** [comment]
As we have not heard from you, closing the issue. Feel free to comment and re-open if you still experience the issue and have more info.
