### ISSUE TITLE
Minimize "summary report"

### ISSUE THREAD

**Issue by JLuc** [piwik/piwik#10218]
The "evolution over period" graph comes along with a "summary report" that show 10 mini-graphs.

These 10 minigraphs are fine but they take lot of room and it'd be nice to minimize that subpane
when using more than 1 "evolution over period" widget because there is no use for more than 1 "summary report".

**Comment by tsteur** [comment]
Have you seen the "Visits over time" widget? Maybe you can add this widget instead? This should show only the graph.

**Comment by JLuc** [comment]
The "evolution over period" features "Visits over time" graph but also 16 other graphs !

I need more than 1 "evolution over period" graphs because of scales. Some sets of data have very different scales. When max for a set is 10 and max for another set is 2000, then the 10 line will look flat when on same scale.

**Comment by JLuc** [comment]
I realize that what you've called "visits over time" actually enables to select which set of data is shown, amongst the 17 same possible sets as "evolution over period". So you're right, no need to have multiple "evolution over period"
