### ISSUE TITLE
Problem creating Goal with exact URL

### ISSUE THREAD

**Issue by RonGalore** [piwik/piwik#10212]
I cannot create a Goal which is triggered by a given url and where the url is exact. When I try to save the goal, it just shows "Loading data..." running over and over. I'm using Chrome and latest version of Piwik.

If I change the option so that the URL contains a portion of the exact url then I am able to create the goal ... but I would like to use the exact url option.

**Comment by tsteur** [comment]
I cannot reproduce this. Are you creating a goal in the Dashboard area under "Goals => Manage Goals" or under "Personal => Goals"? Can you paste an example URL? 

Do you have any extensions installed that maybe cause an error?

**Comment by mattab** [comment]
Hello, please check your server error logs for more information. if you have found a message or so, please create a new issue and paste the error message there.
