### ISSUE TITLE
data mismatches in the UI and the reports.

### ISSUE THREAD

**Issue by samratng07** [piwik/piwik#10215]
we have 5 sites configured in PIWIK but randomly we notice that the data within the daily reports does not match with the data in the PIWIK for that particular day ,the UI shows the correct data.

we run a cron job to generate reports daily and weekly ,but we notice discrepancies in both the reports,sometimes the weekly report is empty too.

If we manually generate a report for that day we get the correct data in the report.

please help.

**Comment by tsteur** [comment]
Are you using the latest Piwik version? Do you mean "Scheduled Reports" vs UI? Do the schedule reports show less data? Is maybe a segment selected in the scheduled report?

**Comment by samratng07** [comment]
we are using PIWIK version 2.16.0 and yes the Scheduled reports show sometimes less data not always,no we have not selected a segment.sometimes the data in reports is as per the UI but sometimes less or nothing at all please help.as we are finding it tough to use PIWIK because of this issue

**Comment by samratng07** [comment]
Hi we received blank reports again for the weekly reports,although PIWIK UI shows data for the past week 13th-19th June for these sites.Please help.Why PIWIK is so inconsistent please help.Only for one site out of 5 the correct report was generated.Please help

**Comment by mattab** [comment]
Hello, please update to latest Piwik version. if you still have a problem, crete a new issue and attach the broken reports PDF file, and exactly the steps you took to reproduce the issue.
