### ISSUE TITLE
Isn't it possible to track the source from WAS server?

### ISSUE THREAD

**Issue by changhoonKim** [piwik/piwik#10229]
We have IIS web server and Weblogic Was Server and they’re separated.
and there is all of source in the Was server.
We installed Piwik in the IIS web server. and we’re tracking by adding java script in the source.

Actually we would like to tracking the source in the Was server. 
We could tracking the source in the web server, 
but we failed to tracking the source in the was server

So could you give us some recommendation?

Thanks,

**Comment by tsteur** [comment]
I'm not quite sure what you mean but maybe this helps ? http://piwik.org/log-analytics/
