### ISSUE TITLE
Start and end date variable repeated in JSON api output? 

### ISSUE THREAD

**Issue by ReessKennedy** [piwik/piwik#10237]
I am seeing two date vars in the URL to output data via the API in JSON. 

&date=2016-05-18,2016-06-16&rows=Direct%20Entry%2CTotal&date=2016-05-18%2C2016-06-16

Doesn't impact output and I may have missed something but wanted to contribute if this has been overlooked. Thanks for all the great work by the community with this awesome project.

**Comment by tsteur** [comment]
How did you get this URL? Was this a link from the UI eg via an "export" link? Can you reproduce this?

**Comment by mattab** [comment]
Hi @ReessKennedy - how do you reproduce this issue, on demo.piwik.org ? (what steps do you take). Thanks

**Comment by mattab** [comment]
As we have not heard from you, closing the issue. Feel free to comment and re-open if you still experience the issue and have more info.
