### ISSUE TITLE
Bad Request #400 if rec=1 [v1.16.1]

### ISSUE THREAD

**Issue by SimonKraus** [piwik/piwik#10238]
Since our piwik got auto-updated it stopped working and tracking.
Reason for that is that all tracking-requests return #400 (Bad Request).

I tried to debug what causes this, as many other issues were opened concerning #400 in past versions, and got to the point that it breaks if rec-param is 1.

I even tested it with Image-Tracker. 
`<img src="http://host.xy/piwik.php?idsite=2amp;rec=1" style="border:0" alt="" />`
returns #400 while 
`<img src="http://host.xy/piwik.php?idsite=2amp" style="border:0" alt="" />`
returns #200.

I tested a blank installation of PIWIK 1.16.1 (using the same DB) with no success.

i appreciate any help

**Comment by tsteur** [comment]
I recommend having a look here: http://piwik.org/faq/troubleshooting/faq_58/ and especially here: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker  Please try to enable logging for the tracker and likely you will see  an error message. Please keep us updated

**Comment by mattab** [comment]
As indicated, debbuging the tracker will show you the problem directly. if you need more help please create a new issue.
