### ISSUE TITLE
Some Ad blockers block anything containing piwik

### ISSUE THREAD

**Issue by forgetso** [piwik/piwik#10232]
This results in the tracking being lost.

**Comment by sgiehl** [comment]
There is nothing we can do about that. Every other tracking tool has the same problem.
As a workaround you could try to use https://github.com/piwik/tracker-proxy and rename the piwik.php to something else or simply create an alias in your webserver so the url does not contain piwik anymore.

**Comment by mattab** [comment]
see also https://github.com/piwik/piwik/issues/7364
