### ISSUE TITLE
Weekly report gets generated with only one days data

### ISSUE THREAD

**Issue by samratng07** [piwik/piwik#10249]
We are generating weekly reports for 3 of our sites.

But when we try to generate the report from UI manually on Email Reports tab,for the weekly report just one days data is seen and the current days date appears instead of the week range.

this behavior is seen from yesterday 23rd June,previous to this everything was working fine.

for the last week for 2 of our sites the reports were blank.there were no changes made from our site.

Thus we are now completely unable to generate the weekly reports as before ,manually as well as scheduled.

Please help

**Comment by mattab** [comment]
> But when we try to generate the report from UI manually on Email Reports tab,for the weekly report just one days data is seen and the current days date appears instead of the week range.

could you please attach a sample report showing the problem? 

what was the 'URL' used to generate this report?

**Comment by mattab** [comment]
As we have not heard from you, closing the issue. Feel free to comment and re-open if you still experience the issue and have more info.
