### ISSUE TITLE
All graphs range from begining of time whatever time range is selected

### ISSUE THREAD

**Issue by JLuc** [piwik/piwik#10243]
When selecting a time range, the shown numbers do take that range into account, but all graphs start at the begining of times.

That's when using a predefined range as "week" or "day" or "month"
BUT there is no such issue when defining the range using the more precise "FROM such day TO such day" option.

![time range incoherents](https://cloud.githubusercontent.com/assets/443278/16176489/dd756edc-3611-11e6-9b05-5e3f1de61e96.jpg)

**Comment by JLuc** [comment]
That's when using a predefined range as "week" or "day" or "month"
BUT there is no such issue when defining the range using "FROM such day TO such day" option.

**Comment by JLuc** [comment]
I do reproduce the same on demo.piwik.org
Let me try to explain again in french. Better now ?

Quand je choisis une durée "semaine" ou "mois" ou "jour", ET que je sélectionne une date précise pour cette semaine, ce mois ou ce jour, les chiffres présentés sont corrects, mais le graphe ne les prend pas en compte et présente tout l'historique, pas seulement la période choisie.

Voici une copie d'écran de ce que ça donne sur demo.piwik :
- On voit bien que la période choisie est restreinte à une semaine (du 27/06 au 03/07) 
- MAIS le graphe commence au 4 janvier

![capture demo piwik](https://cloud.githubusercontent.com/assets/443278/16680172/1850f9ec-44ed-11e6-8b15-0b9391af5124.png)

**Comment by mattab** [comment]
Merci pour le rapport! Je comprends bien, et ce bug est effectivement souvent reporté par nos utilisateurs. Voici le ticket: https://github.com/piwik/piwik/issues/955
