### ISSUE TITLE
Multisites API-call for users with view permission requires an unnecessary idSite parameter

### ISSUE THREAD

**Issue by mwarmoeskerken** [piwik/piwik#10244]
I'm using Excel to extract data from Piwik using the API. Currently I'm working on a dashboard for which I need to get the data for all websites that the end-user has access to. These end-users have view-permissions, and strangely - the API call for the MultiSites.getAll is requesting an idSite parameter when calling the API-command with view-only credentials. An error message is returned stating that the idSite parameter is missing. However, it shouldn't be necessary because a list of sites is queried, and not the parameters for a specfic site. Users with superadmin rights are not affected.

Could the API be updated where the idSite for the view-credential-users is not neccessary?

**Comment by tsteur** [comment]
I can't reproduce this with latest Piwik 2.16.1. I'm only getting an error if there is no valid token_auth provided, or if the user of the token_auth does actually not have permission to any site.

**Comment by mwarmoeskerken** [comment]
Hi tsteur, thanks for your quick research into this issue. We run 2.16.0, so I'll wait and check again when we upgraded to 2.16.1.
