### ISSUE TITLE
Should VisitorProfile popup display segmented data?

### ISSUE THREAD

**Issue by wronan** [piwik/piwik#10245]
I wonder, because I stumbled on such problem:
- I've created visitCount>=2 segment
- such segment works OK (meaning: it filters visits at least in Visitor Log as expected)
- problems start when I would like to view Visitor Profile Popup

On Visitor Profile Popup same segment is applied (https://github.com/piwik/piwik/blob/master/plugins/Live/API.php#L204), so when app looks for previous visits to be counted and listed below the current one, I get one less visit then I should (this is for for visitCount>=2 segment, for for visitCount>=3 there probably would be 2 missing, for for visitCount>=4 there would be 3 missing, etc... haven't check that behavior but it seems as a logical consequence).

This is misguiding, since most of such visits have visitCount=2, when I open respective visitor's profile, it looks like there are no additional visits.

At this I wonder whether data on Visitor's Profile Popup should be segmented at all. Since it just should show logs for specified visitor ID (https://github.com/piwik/piwik/blob/master/plugins/Live/API.php#L218) anything else shouldn't be filtered out. Ie. when I put segment for visits with more actions then 5, I expect Visitor Log to present such visits, but when I view the specific Visitor's Profile from such list, I expect it to show me full profile. Or at least it should be stated in some explicit manner, that segment was applied while generating that profile so the profile is not "full". What's your opinion guys? Personally I would vote for option 1.

Visitor's Profile Popup is disabled on Demo, but a links to start looking at that issue would be:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Live&action=indexVisitorLog&idSite=7&period=day&date=yesterday
and
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/?module=Live&action=indexVisitorLog&idSite=7&period=day&date=yesterday&segment=visitCount%3E%3D2

**Comment by dczajkacc** [comment]
I agree with @wronan. This behavior is misleading for a user. At least there should be information on VisitorProfile like "segment is enabled, not all data is visible".

Ideally I would say there should be a separated filtering for VisitorProfile.

**Comment by wronan** [comment]
@mattab || @tsteur , could you give me some opinion on the subject? I'll prepare the PR, just want to know how to proceed. Thx in advance :)

**Comment by hpvd** [comment]
+1 for
- showing information
- separate filter
- or even no filtering in visitor profile

should be made more clear no matter how...

**Comment by mattab** [comment]
Hi @wronan 
please check this issue where I already reported the bug: https://github.com/piwik/piwik/issues/9893

**Comment by wronan** [comment]
Ahh... I stumbled upon that problem for the first time and didn't bother to check maybe it's already reported. Sorry for that.

**Comment by mattab** [comment]
@wronan No worries at all, and thanks for the report!
