### ISSUE TITLE
Custom dimensions show null entry as `Value not defined`.

### ISSUE THREAD

**Issue by sebastianpiskorski** [piwik/piwik#10246]
There is no way to tell CustomDimension to omit NULL values in reports. All entries with NULL values are reported as `Value not defined` in report table.

Scenario when I want to have only specific visits reported in in CustomDimension report is not possible.

**Comment by sebastianpiskorski** [comment]
Moved to CustomDimensions repository: https://github.com/piwik/plugin-CustomDimensions/issues/32

This should be closed.

**Comment by EugenVau** [comment]
Since the CustomDimensions repository linked above has vanished and the new one does not have any issues, what's the answer to the original issue? Behaviour is still as described there...

**Comment by tsteur** [comment]
@EugenVau it maybe referred to https://github.com/matomo-org/matomo/issues/16149 

There isn't any workaround so far AFAIK
