### ISSUE TITLE
tiny: visitor log: overlapping element

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10253]
visitor log: overlapping element when reducing window wide

![2016-06-24_12h58_00](https://cloud.githubusercontent.com/assets/5681880/16336189/ec441c94-3a0b-11e6-808a-675477447e2c.png)

![2016-06-24_13h00_36](https://cloud.githubusercontent.com/assets/5681880/16336190/ee3be004-3a0b-11e6-958e-481d42bdce16.png)

**Comment by tsteur** [comment]
Thanks for reporting it 👍  It might be actually not easy to solve but we'll see

**Comment by sogen** [comment]
What's the correct way to work on this? I mean how to test with Jekyll/Hugo/etc running on development before sending a PR

**Comment by sgiehl** [comment]
You can use our VisitorGenerator Plugin to generate fake visits. That way you have some test data in Piwik to be able to have a look at the reports.

**Comment by sogen** [comment]
Hi,
thanks for the plugin,
Plus, I found this:
https://piwik.org/blog/2014/08/create-custom-theme-piwik-introducing-piwik-platform/
which completes what I was looking for, thanks!

**Comment by sgiehl** [comment]
visitor log was refactored a bit meanwhile and those overlappings shouldn't occur anymore. But for sure there might be other improvements we could do for smaller resolutions.
