### ISSUE TITLE
Maximum execution time of 0 seconds exceeded

### ISSUE THREAD

**Issue by janakbaps** [piwik/piwik#10254]
it syas PHP Fatal error:  Uncaught exception 'Exception' with message 'Maximum execution time of 0 seconds exceeded' in

**Comment by tsteur** [comment]
Try setting `max_input_time = -1` in php.ini.

See eg http://stackoverflow.com/questions/4869611/fatal-error-maximum-execution-time-of-0-seconds-exceeded 

or http://www.sparrowtail.com/php-fatal-error-maximum-execution-time-0-seconds-exceeded

or google https://www.google.com/search?q=Maximum+execution+time+of+0+seconds+exceeded&oq=Maximum+execution+time+of+0+seconds+exceeded

**Comment by dignizant** [comment]
I have face same issue.
try to max_execution time set to -1 also but this is also not working If i used -1 then it gives Maximum execution time of -1 seconds exceeded
