### ISSUE TITLE
Remove AdvancedOnlineMarketing from Piwik marketplace

### ISSUE THREAD

**Issue by andre-hh** [piwik/piwik#10256]
I have added a plugin named "AdvancedOnlineMarketing" to the marketplace. As this version had namespace issues, I renamed it to "AOM". Now there are two versions out there, "AdvancedOnlineMarketing" and "AOM".

Is there any way to remove "AdvancedOnlineMarketing" from the marketplace?

**Comment by tsteur** [comment]
Thanks for letting us know. I will do this now. Nice plugin btw!

**Comment by tsteur** [comment]
done
