### ISSUE TITLE
Resolution unknown from tracking by Image Tracking Link

### ISSUE THREAD

**Issue by joubertredrat** [piwik/piwik#10250]
Hi guys,

Probably have a bug on a tracking by image, when I use image tracking link, always don't get resolution, then display as unknown, if I change to JavaScript Tracking Code, works fine.

I don't know if this is a bug or limitation on image tracking link, then, I open this issue.

Thanks.

**Comment by sgiehl** [comment]
Image tracking can't provide any metrics that can only be collected using javascript. This contains resolution, browser plugins, etc.

**Comment by joubertredrat** [comment]
Hi guys,

@sgiehl then I think that is good and important do add on https://developer.piwik.org/api-reference/tracking-api or on a trackingCodeGenerator action information about this limitation, isn't?

**Comment by mattab** [comment]
Hi @joubertredrat 

this is documented in: https://piwik.org/docs/tracking-api/#image-tracker-code

> Note: the code doesn’t use Javascript so Piwik will not be able to track some user information such as search keywords, referrers, screen resolutions, browser plugins and page titles. The image tracker code also does not create first party tracking cookies which results in some information being lost.

Also just added this in [ the FAQ  How do I enable tracking for visitors that have disabled Javascript?](https://piwik.org/faq/how-to/faq_176/)
