### ISSUE TITLE
Visits are count differently between segmentation and visits - devices

### ISSUE THREAD

**Issue by chronozzz** [piwik/piwik#10261]
We are tracking with Piwik on this website: http://www.herz-der-wirtschaft.de/ 

If I look up the visits, especially the devices, we have 6.878 Visits with a smartphone during the month May. 

If I add a segmentation - device type - smartphone the visits go down to 1970 for May. 

I do not understand why this is the case?

Can you help me out?

Cheers 

Christoph

![2016-06-28 09_14_51-herz der wirtschaft - mai 2016 - webanalytik berichte - piwik](https://cloud.githubusercontent.com/assets/9573013/16406844/e3db2018-3d10-11e6-9357-a1593c843edd.png)

![2016-06-28 09_15_09-herz der wirtschaft - mai 2016 - webanalytik berichte - piwik](https://cloud.githubusercontent.com/assets/9573013/16406865/f6f9882e-3d10-11e6-9ecb-7a4c322c260d.png)

**Comment by hpvd** [comment]
wow that would be intersting..

Just checked in our Piwik - everything is fine there (latest Piwik beta 2.16.2b2)

Which version are you using?
Could please show a screen shot of your setup of smartphone segment filter?

**Comment by chronozzz** [comment]
Hi, 

we are using 2.16.1 with PHP 5.6.5

Here is a screenshot of the segment filter. It is in german but it means: device type is smartphone

![2016-06-28 13_42_27-herz der wirtschaft - mai 2016 - webanalytik berichte - piwik](https://cloud.githubusercontent.com/assets/9573013/16414177/8c9c4d9c-3d36-11e6-9542-85bf314f12cf.png)

**Comment by hpvd** [comment]
hmm -segment filter looks the same...
just checked again with other period setting: always working..

Does period setting has any influnce in your installation or is there always a difference?

**Comment by chronozzz** [comment]
Yes. I just discovered when I change the month into weekly oder daily setting the numbers are correct (the same with or without the segmentation). 

Is there a difference in monthly visits because we delete old visit-logs?

![2016-06-29 16_01_19-privatsphareeinstellungen - administration - piwik](https://cloud.githubusercontent.com/assets/9573013/16454887/bf716824-3e12-11e6-81db-379ad5623789.png)

**Comment by sgiehl** [comment]
Segments are build on the log data if they are not preprocessed. So it might be possible that you try to view a segment for a period, where not all logs are available anymore.

**Comment by chronozzz** [comment]
How can we preprocess the data? We use a cronjob every hour to archive: 

console core:archive --url=http://xyz.domain.de/ --force-all-websites > /files/piwik-archive-errors.log
is this incomplete? 

Or is it just not possible to gain this data if we delete old visit-logs?

**Comment by sgiehl** [comment]
You can choose to preprocess segments when editing/creating them instead of having it processed live.

**Comment by mattab** [comment]
> Segments are build on the log data if they are not preprocessed. So it might be possible that you try to view a segment for a period, where not all logs are available anymore.

Good find @sgiehl - I created this issue to offer a solution:  #10280 

* When a report was processed using incomplete log data, display a notification/warning that report data may be incomplete 

Closing the issue as @chronozzz confirmed that Log Data delete was enabled causing the issue here.
