### ISSUE TITLE
Transitions do not work

### ISSUE THREAD

**Issue by iamklaus** [piwik/piwik#10269]
I am running Piwik on PHP 7.0.7. Everything works fine, but not the transitions module. It is loading forever. Chrome Inspector tells me that the there is Server Error 500. Here is the exception from the log:

[Sun Jul 03 18:40:58.230981 2016] [proxy_fcgi:error] [pid 4131] [client 130.0.20.121:59985] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Piwik\\API\\ResponseBuilder::getResponseException() must be an instance of Exception, instance of Error given, called in /var/www/piwik/core/ExceptionHandler.php on line 90 and defined in /var/www/piwik/core/API/ResponseBuilder.php:130\nStack trace:\n#0 /var/www/piwik/core/ExceptionHandler.php(90): Piwik\\API\\ResponseBuilder->getResponseException(Object(Error))\n#1 /var/www/piwik/core/ExceptionHandler.php(70): Piwik\\ExceptionHandler::getErrorResponse(Object(Error))\n#2 /var/www/piwik/core/ExceptionHandler.php(36): Piwik\\ExceptionHandler::dieWithHtmlErrorPage(Object(Error))\n#3 [internal function]: Piwik\\ExceptionHandler::handleException(Object(Error))\n#4 {main}\n  thrown in /var/www/piwik/core/API/ResponseBuilder.php on line 130\n', referer: http://piwik.rehau.org/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last7&showaddsite=false

What is the problem?

**Comment by mattab** [comment]
Could you try upgrade to our latest beta version? this bug should be fixed already: http://piwik.org/faq/how-to-update/faq_159/

if it is not fixed, please leave a comment to make sure we will know and have a chance to fix it! thanks.

**Comment by iamklaus** [comment]
Nope, just updated to Beta 2. Same error occures!

**Comment by mattab** [comment]
refs #8689

**Comment by mattab** [comment]
Thank you for the report. This duplicates https://github.com/piwik/piwik/issues/10115 - we will try to fix it for the next release.

**Comment by mattab** [comment]
@iamklaus Could you confirm the following patch fixes your issue? https://github.com/piwik/piwik/commit/60ae66a89b8e4cdca5d7e71bbefb47fd15534eb1
