### ISSUE TITLE
Archiving output showing always "0" visits for period = day summary

### ISSUE THREAD

**Issue by tomasztomik** [piwik/piwik#10276]
Hi,

Archiving output used to show information as below in previous versions:

`INFO CoreConsole[2016-07-05 13:11:40] [024d9] Archived website id = 1, period = day, 211 visits in last last1 days, 211 visits today, Time elapsed: 14.827s`

Unfortunately, Piwik 2.16.1 (maybe earlier versions too - haven't checked it) is always showing " 0 visits in last 1 days, 0 visits today", apart from the fact that there are processed visits.

`NFO [2016-07-05 13:21:09] Archived website id = 1, period = day, 3 segments, 0 visits in last 1 days, 0 visits today, Time elapsed: 4.090s`

Can you check it?

Thanks in advance and regards,
Tomasz

**Comment by mattab** [comment]
Thanks for the report!
