### ISSUE TITLE
Sections on the website open on different tabs

### ISSUE THREAD

**Issue by blueelvis** [piwik/piwik#10287]
Hi,

I found that on many pages of the documentation of Piwik, the ``href`` has been set to a relative URL (in some cases, a complete URL) rather than simply #section which causes it to open the link in a new tab even though the content is right there.

For example - https://piwik.org/docs/requirements/

If one clicks on any of the first 4 links, it opens a new tab with the link. The ``target="_blank"`` also needs to be removed on most pages in my opinion.

Just a suggestion :)

**Comment by mattab** [comment]
Thanks for the report @blueelvis - this should be now fixed!
