### ISSUE TITLE
comparison of data of "unfinished periods" with "complete periods" does not make big sense e.g. in widget

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10282]
When comparing data e.g. number of visits, entry pages etc
with data of day before there is a problem:
when checking earlier than 23:59 
there is always a difference because
the period taken into account is shorter 
than the complete day before
and with this not all "things" of this day has already happened.

An example:
Looking at data at 9:00 in the morning:
actual data is taken from 0:00 to 9:00 = 9h
the data for comparison form 0:00 to 0:00 = 24h

the result looks like this:

![2016-07-08_08h15_42](https://cloud.githubusercontent.com/assets/5681880/16681643/430f472a-44f6-11e6-902a-7d09187a397f.png)

**=> there are two ways to solve this:**
- compare data always the last 24h 9:00-9:00 to the 24h before 9:00-9:00
- compare last full day 0:00-0:00 to the last full day before 0:00-0:00

**Comment by hpvd** [comment]
for same reason for graphs I would vote for not connecting the data point of today to the others before the end of day (0:00)
![2016-07-08_10h38_37](https://cloud.githubusercontent.com/assets/5681880/16682091/d8c62fac-44f8-11e6-804e-4a9d6b157719.png)

what do you think of this?

**Comment by hpvd** [comment]
of course this is not only relevant for comparing the actual day with the day before but to all comparisons of data of unfinished periods with complete periods before
=> changed issue's title

**Comment by mattab** [comment]
Hi @hpvd 

For your first feedback regarding Insights, please check this issue which discusses it as well: https://github.com/piwik/piwik/issues/6600

For your second  suggestion on the graph, it is a nice idea IMHO, do you mind creating a new separate issue just for this?

**Comment by hpvd** [comment]
done, see:
make a difference in graphs for data of "unfinished periods" and "complete periods" #10291
