### ISSUE TITLE
Deprecated getMock()  methods used in tests

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10295]
See https://travis-ci.org/piwik/piwik/jobs/144259287 

eg 
```
22) Piwik\Plugins\Test\Columns\UpdaterTest::test_getMigrationQueries_ReturnsCorrectQueries_IfDimensionIsNotInTable
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
```

we should probably update this soon

**Comment by sgiehl** [comment]
I don't think we should fix that in LTS.  `getMock` was deprecated in PHPUnit 5.4.0. That version of PHPUnit already requires PHP >= 5.6
As the LTS should still support PHP 5.3 we can't use one of the latest PHPUnit versions using composer

**Comment by tsteur** [comment]
👍  moving it to 3.x

**Comment by tsteur** [comment]
I have updated them in a Piwik 3 branch but not the ones yet in submodules

**Comment by mattab** [comment]
just realised that Travis does not use the PHPUnit version that we set in our composer.json but it uses the latest PHPUnit. The integration tests are failing now, (see https://travis-ci.org/piwik/piwik/jobs/154281157) -  PHPUnit must have broken BC for `getMock`... 

Can think of two ways to solve issue:
* we backport the tests fixes in LTS as well, 
* or we could set Travis to use our composer.locked PHPUnit version

**Comment by tsteur** [comment]
> or we could set Travis to use our composer.locked PHPUnit version

sounds better

**Comment by mattab** [comment]
@tsteur sounds good, done in master
