### ISSUE TITLE
search_recursive

### ISSUE THREAD

**Issue by phoob** [piwik/piwik#10292]
Hello!

I have created a report with subtables, which are loaded by a separate report (**not** `$this->actionToLoadSubTables = $this->action;`). I want to be able to search the datatable recursively (by setting `$view->config->search_recursive = true`; in configureview), but when I do this, and search for something in a subtable, the wrong subtable is loaded when I try to expand it. 

I have noticed that other reports (such as those generated by the Events plugin and the Keyword report in the Referrer plugin) do not search recursively. Is this not possible? It would be useful if it was. The steps to reproduce, when using my plugin, are:

1. Create a record and a report with a datatable with subtables 
2. Open the report and search for something that you know is in a subtable
3. Observe that only the rows in the main data table that have the relevant subtables are shown
4. Click on the +-sign to load the subtable
5. Observe that a different subtable is loaded – not the one that is stored as the subtable for that row

The thing is I am not sure if this is a bug or if I am doing something wrong. Looking forward to any kind of response :) 

I would gladly supply some code, but the plugin depends on specific event actions in the database, so I'm afraid that won't do any good.

**Comment by mattab** [comment]
Hello @phoob 

Good to hear you are experimenting with the Piwik platform!

> but when I do this, and search for something in a subtable, the wrong subtable is loaded when I try to expand it. 

Does it happen for all dates? if it happens for "today" only, this may be this known issue: https://github.com/piwik/piwik/issues/1024#issuecomment-48296981

**Comment by phoob** [comment]
Thank you for your response, @mattab . It happens for all dates. I actually found a way to reproduce this with a core plugin (Referrers). See the screencast of the test here:

https://youtu.be/9XGXj_HjQc0

**Comment by mattab** [comment]
Thanks for the screencast @phoob that's really helpful. The bug might be fixed with: https://github.com/piwik/piwik/pull/10303/files - could you test the patch and confirm?

**Comment by phoob** [comment]
Awesome, @mattab , it works! This is perfect :)
