### ISSUE TITLE
`piwik_ignore` Cookie ignores `setCookieDomain` settings.

### ISSUE THREAD

**Issue by atrioom** [piwik/piwik#10301]
When setting the cookie domain in the JavaScript Tracker with `_paq.push(['setCookieDomain', '*.example.com']);` piwik changes only some of the cookies it sets to this new value. The `piwik_ignore` cookie still uses the default page (which is the domain that is set in the iframe src I guess).  
Is this intended behaviour, or should `piwik_ignore` also be changed by the setting?

**Comment by mattab** [comment]
Hi @atrioom - this is intended behavior, as the `piwik_ignore` cookie is set globally for all websites tracked in the Piwik. It excludes the user from all websites at once. The cookie is a third party cookie. As it was not so clear before, i've just clarified this in the FAQ: https://piwik.org/faq/how-to/faq_126/ - cheers
