### ISSUE TITLE
alignment broken in movers and shakers widget

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10308]
alignment broken in movers and shakers widget
- numbers are not aligned to the right
- column heads are also aligned some how wrong

=> best to see if uses high res screen (HD+) and browser using full wide
or simply zoom out.

Visible at least in FF and Opera...

![2016-07-13_10h28_271](https://cloud.githubusercontent.com/assets/5681880/16865038/25977994-4a62-11e6-8a9c-b2785a1c5474.png)

![2016-07-13_10h31_141](https://cloud.githubusercontent.com/assets/5681880/16865040/2904e378-4a62-11e6-9a06-de2d0aade812.png)

**Comment by tsteur** [comment]
I'm pretty sure  this has been fixed in Piwik 3 but I'll need to have a look.

**Comment by tsteur** [comment]
this is fixed in piwik 3 indeed
