### ISSUE TITLE
customDimensionIdsAlreadyHandled is a array,has no indexOf() in line 3932

### ISSUE THREAD

**Issue by dingxiangyang** [piwik/piwik#10310]
The array function indexOf() was added to the ECMA-262 standard in the 5th edition; as such it may not be present in all browsers,eg. IE8.
In getRequest() ,customDimensionIdsAlreadyHandled is a array

**Comment by sgiehl** [comment]
we already have a polyfill function `indexOfArray` included, so guess we just need to use it everywhere...

**Comment by dingxiangyang** [comment]
that's great,but you don't use it in customDimensionIdsAlreadyHandled
