### ISSUE TITLE
Password type input with auto-complete enabled

### ISSUE THREAD

**Issue by Showian** [piwik/piwik#10319]
Vulnerability description
When a new name and password is entered in a form and the form is submitted, the browser asks if the password should be saved. Thereafter when the form is displayed, the name and password are filled in automatically or are completed as the name is entered. An attacker with local access could obtain the cleartext password from the browser cache.
Please add AUTOCOMPLETE="off" parameter to the login page to fix this issue

**Comment by mattab** [comment]
Please see https://github.com/piwik/piwik/issues/6347
