### ISSUE TITLE
segment editor: not enough line height for p,y,...

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10313]
segment editor: not enough line height for p,y,q...

seen in FF

![2016-07-15_16h42_04](https://cloud.githubusercontent.com/assets/5681880/16878061/59037550-4aab-11e6-8c0f-9c236d8da0e5.png)

**Comment by hpvd** [comment]
same also here:
![2016-07-15_16h57_14](https://cloud.githubusercontent.com/assets/5681880/16878536/362f7b26-4aad-11e6-9cc1-3f4ffcd026f5.png)

**Comment by tsteur** [comment]
Thanks for creating the issue 👍

**Comment by tsteur** [comment]
I just realize this was actually a problem in Piwik 2, in Piwik 3 this is mainly fixed only the select needs to be a bit higher
