### ISSUE TITLE
widget/entry pages: what's "NB_Visits"?

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10315]
widget/entry pages: what's "NB_Visits"?
![2016-07-15_17h08_05](https://cloud.githubusercontent.com/assets/5681880/16878992/e825aaf2-4aae-11e6-8ec2-ea857d84a9aa.png)

**Comment by sgiehl** [comment]
That happens only for the evolution view.

**Comment by hpvd** [comment]
it's also visible in hover (probably it's the same var)
![2016-07-18_23h23_35](https://cloud.githubusercontent.com/assets/5681880/16930969/dabb0f5a-4d3e-11e6-83ff-217bb06790e4.png)

**Comment by tsteur** [comment]
I will close this as a duplicate of https://github.com/piwik/piwik/issues/9283
