### ISSUE TITLE
Password field submitted using GET method

### ISSUE THREAD

**Issue by Showian** [piwik/piwik#10320]
## Vulnerability description
This form submits user data using the GET method, therefore the contents of the password field will appear in the URL. Sensitive information should not be passed via the URL. URLs could be logged or leaked via the Referer header.

**Comment by sgiehl** [comment]
which form do you mean exactly? Login form, user data form,... ?

**Comment by Showian** [comment]
Login form

**Comment by sgiehl** [comment]
that's not correct, Looking at the rendered HTML of http://demo.piwik.org/index.php?module=Login there is a `method="post"`:

```html
<form name="login_form" id="login_form" method="post" ng-non-bindable="">
````

**Comment by Showian** [comment]
form name: "<unnamed>"
form action: ""
password input: "form_password"

**Comment by blueelvis** [comment]
@Showian - I just checked the form and like Stefan said, the form sends data over POST. Below is the source code I get in my browser -

`<form name="login_form" id="login_form" method="post" ng-non-bindable="">
                <h1>Sign in</h1>
                <fieldset class="inputs">
                    <input type="text" name="form_login" id="login_form_login" class="input" value="" size="20" tabindex="10" placeholder="Username" autofocus="autofocus">
                    <input type="password" name="form_password" id="login_form_password" class="input" value="" size="20" tabindex="20" placeholder="Password">
                    <input type="hidden" name="form_nonce" id="login_form_nonce" value="adb987b63bab346d6f936c36419e3f94">
                </fieldset>

                <fieldset class="actions">
                    <input name="form_rememberme" type="checkbox" id="login_form_rememberme" value="1" tabindex="90">
                    <label for="login_form_rememberme">Remember Me</label>
                    <input class="submit" id="login_form_submit" type="submit" value="Sign in" tabindex="100">
                </fieldset>
            </form>`


Maybe a false positive from Acunetix?
