### ISSUE TITLE
Error in latest Beta 3

### ISSUE THREAD

**Issue by iamklaus** [piwik/piwik#10326]
Still my transitions do not show up. Updating to the latest beta, I receive now this error:

[Mon Jul 18 12:12:24 2016] [error] [client 10.130.52.246] PHP Fatal error:  Call to undefined function Piwik\\Plugins\\Referrers\\getReferrerTypeFromShortName() in /srv/www/vhosts/piwik/plugins/Transitions/API.php on line 538, referer: http://piwikdev.rehau.org/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last7

**Comment by sgiehl** [comment]
which version of PHP are you using? that methods exists since a long time, so it shouldn't be missing

**Comment by iamklaus** [comment]
Totally reinstalled piwik, now the error is gone. Sorry! Somehow my system seemed to be screwed up.
