### ISSUE TITLE
Wrong map of Tibet

### ISSUE THREAD

**Issue by yfiua** [piwik/piwik#10343]
Tibet is part of China. 
see https://en.wikipedia.org/wiki/Tibet_Autonomous_Region

**Comment by ZihanShen90** [comment]
No doubts, Tibet's part of China. I visited Tibet 2 years ago. The local Tibetans live even better than Hans, the Tibetans own true free housing, medicines and education, not like their ancestors lived under serfdom  60 years ago.

**Comment by sgiehl** [comment]
dublicates #6006

**Comment by HaoLovesCoding** [comment]
Tibet should be part of China #11152
