### ISSUE TITLE
Correct wording: Donation widget only displayed to superusers

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10357]
![image](https://cloud.githubusercontent.com/assets/273120/17312020/b9ea935c-58a3-11e6-9ffa-9d2ba2adc62b.png)

It says:
> This widget is only displayed to users having Super User access.

Instead it should maybe rather say:

> This widget is displayed in the default dashboard only to users having Super User access.

Because a regular user would still be able to select it from the dashboard widgets and add it to the dashboard. In this case also non-superusers would see this widget

**Comment by johnrackles** [comment]
I think I can fix that, may I try?

**Comment by johnrackles** [comment]
I hope I did it right. I changed the german string, too, because I happen to speak the language. Or should this rather be done in a separate PR?
