### ISSUE TITLE
How to Display Visitors country name with Flag in Magento

### ISSUE THREAD

**Issue by gowthaman10** [piwik/piwik#10359]
Hi Guys ,

I am new to magento, actually i want to display the visitors country with the flag , I tried many API but couldn't get the right one .

**Comment by tsteur** [comment]
Can you give us a bit more details? Are you developing a magento plugin that integrates Piwik? How are you requesting data from Piwik?

**Comment by mattab** [comment]
@gowthaman10 - you're probably looking for the Metadata API of the UserCountry plugin called `getCountry`: http://developer.piwik.org/api-reference/reporting-api#UserCountry and see: http://developer.piwik.org/api-reference/reporting-api-metadata 

But maybe it's easier to simply embed the report in your app with an iframe: http://piwik.org/docs/embed-piwik-report/
