### ISSUE TITLE
Visitor Log - memory or script execution time error for a specific user only ....

### ISSUE THREAD

**Issue by comp-lsa** [piwik/piwik#10350]
Hello,
We have a piwik user that when executing the visitor log, there is an error : _Oops... there was a problem during this request. Maybe the server had a temporary issue ..._ 
When checking the apache error logs, we have seen, first a memory problem, so we changed the memory_limit setting in php.ini file and restarted. After there is no more memory problem but there is an error for the maximum execution time, and same error message is displayed for the user. Before changing this setting also, we have made another test. We have created a new account with same rights as the one with the problem, and there the execution gives **no errors at all**.
With administrator account we have not the issue neither ...
Do you know how could we solve the problem for the problematic account ?
For your info, the apache errors when executing the visitor log with the problematic account:
For the memory:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 80 bytes) in /var/www/html/piwik/libs/Zend/Db/Statement/Mysqli.php on line 235, 
For the max time execution:
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/piwik/core/Date.php on line 301,
Thanks.

**Comment by gaumondp** [comment]
30 seconds for max_execution_time is very little once you use Segments or Date range. My server is set to 600 seconds (10 minutes) but I have around 100 millions rows in my DB. My memory limit is at 512MB.

**Comment by tomasztomik** [comment]
@comp-lsa Please try to reset the visualisations settings stored for a specific user, as described in http://piwik.org/faq/troubleshooting/#faq_21433. It used to help me with issue as you've described.
