### ISSUE TITLE
Cannot Generate Tests using Piwik Console

### ISSUE THREAD

**Issue by blueelvis** [piwik/piwik#10368]
As per the documentation on this page - http://developer.piwik.org/guides/tests-php#writing-unit-tests, I am not able to execute the below command to generate test of any kind -

`$ ./console generate:test --testtype unit`

Running the command gives me the following error -

> $ ./console generate:test --testtype unit

>  [InvalidArgumentException]
  Command "generate:test" is not defined.
  Did you mean this?
      generate:travis-yml

**Operating System** - Windows 10 Pro
**Command Line** - Using Git MINGW64 shell.
**Piwik Version** - 2.16.2

**Comment by tsteur** [comment]
You likely first need to enable development mode via `./console development:enable`. I will update the guide. It's explained in the initial setup guide but not in here. Please comment if this doesn't help

**Comment by blueelvis** [comment]
Yes. That worked like a charm. Thanks a lot Thomas :)

**Comment by tsteur** [comment]
You're welcome :) let us know if you run into more issues. Happy to improve docs and to help :)
