### ISSUE TITLE
Plugins: Generating a new visualisation via  'generate:visualizationplugin' fails with InvalidArgumentException

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10374]
As reported in this forum post: https://forum.piwik.org/t/critical-bug-in-console-generate-visualizationplugin/20399

```
./console generate:visualizationplugin

[InvalidArgumentException]
The "overwrite" option does not exist.
```

**Comment by tsteur** [comment]
Bug was introduced here: https://github.com/piwik/piwik/commit/903dec2ee0d1a59534aa09bfa31f961dc37d5f4f and because visualizationplugin extends this command it failed.
