### ISSUE TITLE
Lost detailed visitor informations for jan 2016

### ISSUE THREAD

**Issue by ryrun** [piwik/piwik#10375]
I've lost all detail informations for the visits on jan 2016 for all websites. Its just show me the raw visits, but no search keywords, browsers for the visitors and so on. It seems that only jan 2016 is incomplete. Everything before and after this month is fine.
I get the message, that these data was removed, because its older than 3 months.

My current database cleanup settings was set to:
```
not remove old visit-logs
remove old-archived reports older than 3 months (+ all recommended settings are enabled)
```

I thought, when i try to access an non generated reports, piwik will regenerate them. 

I tried to regenerate the reports manually with following command:
```bash
php console core:archive --url=http://xxx/ --force-idsites=2 --force-date-range=2016-01-01,2016-01-31
```

But it doesn't help. There is no error message.

I've checked the tables, but it looks fine for me:
`archive_numeric_2016_01`
`archive_blob_2016_01`

Not sure, if this is a bug of the backend. Could be possible, that i've lost the data, but i'm not sure why.
I currently increased the "remove old-archived reports older than" to 12 months.
Is there a way to check, that the nessesary data is avaible in the big log_visit table so it can be "repaired"?

**Comment by tsteur** [comment]
I'd recommend to invalidate report data for those days and then try to archive the reports again see http://piwik.org/faq/how-to/faq_155/ 

You will need to call something like `...piwikurl...?module=API&method=CoreAdminHome.invalidateArchivedReports&idSites=YOUR_IDSITE&dates=2016-01-02&period=month&cascadeDown1&token_auth=YOURTOKEN`

Re the raw visits if you are familiar with SQL try to execute a query like 
```sql
SELECT * from piwik_log_visit where visit_last_action_time >= '2016-01-01 00:00:00 and visit_last_action_time <= '2016-01-31 23:59:59'
```

**Comment by mattab** [comment]
Hi @ryrun 
Please feel free to re-open this issue, if you still think there is a bug in Piwik.

**Comment by ryrun** [comment]
@mattab Thank you, i finally got some time to test it. It works. Is it possible or planned to add a "-invalidateoldreports" flag to the core:archive function? So i could use date-range, which is missing in "core:invalidate-report-data" and use as just one commandline to repair and re-archive missing days/months

**Comment by mattab** [comment]
> So i could use date-range, which is missing in "core:invalidate-report-data" and use as just one commandline to repair and re-archive missing days/months


@ryrun we don't plan to add a flag to the core:archive script however it would make sense to add date range invalidation support to core:invalidate-report-data command! Maybe you'd like to create an issue for this request?
