### ISSUE TITLE
Update documentation how to install Piwik from git on Windows

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10370]
See https://github.com/piwik/piwik/issues/6493#issuecomment-237335322

It is required to specify `--no-script` on Windows, because the install XHProf scripts are for OSX but do not work on Windows. As XHProf is not needed anyway we can just skip this part.

@mattab I have updated http://developer.piwik.org/guides/getting-started-part-1 do we need to update other pages as well? maybe on piwik.org?

**Comment by blueelvis** [comment]
Any chance the website could be open sourced? Atleast the documentation? That would surely help in reporting and fixing issues more quickly ;)

**Comment by tsteur** [comment]
I'm not sure if there are any plans for the website and how easy it is to do etc but we are discussing putting the docs on the website etc as open source so anyone can help changing it. If it is coming it will take a while though unfortunately as it needs to be developed.

**Comment by mattab** [comment]
I'm wondering whether we should update the FAQ in: https://piwik.org/faq/how-to-install/faq_18271/ which documents setting up composer in "Production" environment (where `--no-dev` is used). @blueelvis on Windows, could you tell me if it works if you run `php composer.phar install --no-dev` without the `--no-script` ? If it works, we don't need to update this fa

**Comment by blueelvis** [comment]
@mattab - `--no-dev` is supposed to remove packages/dependencies as per this [SO answer](http://stackoverflow.com/a/13744836/2758198)

When I tried the `--no-dev` option, it removed all of the dependencies. When I tried again, I did not see any of the downloads for the dependencies but instead got the following -

>$ php composer.phar install --no-dev
> Piwik\Composer\ScriptHandler::cleanXhprof
> Loading composer repositories with package information
> Installing dependencies from lock file
> Nothing to install or update
> Generating autoload files
> > Piwik\Composer\ScriptHandler::buildXhprof

If I use the simple `php composer.phar install` , I get the error at the XHProf stage (Downloads some dependencies before that).

**Comment by mattab** [comment]
The FAQ looks good and should work on windows, so we don't need to edit further content
