### ISSUE TITLE
bad referer 

### ISSUE THREAD

**Issue by bruthe57** [piwik/piwik#10377]
Hello,

I have an issue related to how piwik.js send the event. 
from my access log, a user did this request: 
X.X.X.X - - [05/Aug/2016:07:26:16 +0200] "GET /de/lokales/ueberschwemmungen-vorhersagen-hydrologie-die-wissenschaft-des-wassers-57a38f37ac730ff4e7f6488c HTTP/1.1" 200 17721 "http://www.wort.lu/de" "Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0"

as you can see, user access to this page from "http://www.wort.lu/de"

but the event send by piwik.js contain _rcn attribute set to "dailyNewsletter". In this case, piwik seems to consider this event as a new visit with referer type campaign dailyNewsletter

X.X.X.X - - [05/Aug/2016:07:26:17 +0200] "GET /piwik.php?action_name=%C3%9Cberschwemmungen%20vorhersagen%3A%20Hydrologie%20-%20Die%20Wissenschaft%20des%20Wassers%20&idsite=2&rec=1&r=258906&h=7&m=26&s=35&url=http%3A%2F%2Fwww.wort.lu%2Fde%2Flokales%2Fueberschwemmungen-vorhersagen-hydrologie-die-wissenschaft-des-wassers-57a38f37ac730ff4e7f6488c&urlref=http%3A%2F%2Fwww.wort.lu%2Fde&uid=54ea31271200002052157095&_id=8e19500a67ad7725&_idts=1457536791&_idvc=331&_idn=0&_rcn=dailyNewsletter&_refts=1468993735&_viewts=1470374776&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=1&fla=1&java=1&gears=0&ag=0&cookie=1&res=1920x1200&gt_ms=372 HTTP/1.1" 204 0 "http://www.wort.lu/de/lokales/ueberschwemmungen-vorhersagen-hydrologie-die-wissenschaft-des-wassers-57a38f37ac730ff4e7f6488c" "Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0"

I don't understand why the _rcn is sent because the user come from http://www.wort.lu/de
the result is many visit with only 1 page view, visit duration 0, time on page 0, etc ...
Can you help me to resolv this issue?

Cheers
Dam

**Comment by tsteur** [comment]
How do you embed the Piwik JS tracker? Are you calling any special methods eg via `_paq.push` beside the default methods such as `setSiteId`?

**Comment by mattab** [comment]
Hi @bruthe57 Which Piwik version are you using? do you still experience the issue?

**Comment by mattab** [comment]
Another question: did you maybe configure the config setting as explained in this FAQ: https://piwik.org/faq/how-to/faq_19616/ ?
