### ISSUE TITLE
Show version of piwik at install

### ISSUE THREAD

**Issue by auchri** [piwik/piwik#10371]
It would be very helpful if the version of Piwik would be somewhere shown during the install.

Use case: I just updated my docker container and wasn't entirely sure if the update worked, since no version is shown during the install process.

**Comment by blueelvis** [comment]
Do you mean that you updated **Piwik** in your **Docker Container** ? That would clear whether you want the Piwik version shown during **Piwik's** installation procedure :)

**Comment by tsteur** [comment]
We could show it in the browser title 👍 

FYI: Here are screenshots of start https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/Installation_start.png and finish https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/Installation_congrats.png but I think it would be just best to show it in title instead of adjusting any text there

**Comment by blueelvis** [comment]
@tsteur - If by Browser Title, you mean `Page Title` , then I wonder what would happen if there are lots of tabs open? I am sure many people open quite a lot of tabs leading to non-visibility of the Browser Title.

What do you think?

**Comment by tsteur** [comment]
Yes, I meant page title. It would get a bit lost when having a couple of tabs open for sure. I think it would also get lost when it's only visible on one page so the only other solution would be to put it on all pages and not sure where it could be done as it is maybe also not too important of an information. Do you have a suggestion where it could be shown?

**Comment by auchri** [comment]
I think if someone is interested in the version of piwik, he could still hover the tab to find it out.

**Comment by tsteur** [comment]
Users won't know that they can get this information there on the other side I think it would be a good compromise unless there's a better solution. If someone is "desperate" to find it and has many tabs open, a user might find it.
