### ISSUE TITLE
Page Overlay problems

### ISSUE THREAD

**Issue by babielau** [piwik/piwik#10388]
Hi!

I read about the page overlay problems on the forum and within different reported issues. But even your demo page overlay is not working: http://demo.piwik.org/index.php?module=Overlay&period=month&date=today&idSite=7#?l=http$3A$2F$2Fforum.piwik.org$2Fc$2Fsupport-bugs

That is a little odd. Could you please comment on that?

Thanks
Andreas

**Comment by tsteur** [comment]
It's true it doesn't work there as well. It cannot work in this case as the forum does not allow to embed this page in another page via iframe. The forum sends the header: `'X-Frame-Options' to 'SAMEORIGIN'.` so the browser won't load it. I think we have an issue for that eg https://github.com/piwik/piwik/issues/3530  https://github.com/piwik/piwik/issues/9807 https://github.com/piwik/piwik/issues/7067 etc. 

If you have any suggestions on how to improve this besides the existing issues please let us know. Would be highly appreciated. Ideally all the features would work on demo.piwik.org but unfortunately this is not trivial to fix for us right now
