### ISSUE TITLE
Piwik 3 requires PHP 5.5

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10380]
Steps to take to effectively increase PHP requirements in Piwik:

* [x] increase requirements in source code: https://github.com/piwik/piwik/blob/master/core/testMinimumPhpVersion.php
* [x] update requirements user guide: https://piwik.org/docs/requirements
* [x]  update PHP requirement in composer.json -> config -> platform -> php 
* [x] re-generate the composer.lock with this required PHP version as new packages may be available

Follows up: #8156

**Comment by tsteur** [comment]
>  increase requirements in source code: https://github.com/piwik/piwik/blob/master/core/testMinimumPhpVersion.php 

is done. We need to decide if we require at least 5.5.0 or maybe a little higher version such as 5.5.9 . Not sure if there are some weird problems etc in 5.5.0 or 5.5.1 ...

**Comment by tsteur** [comment]
Drupal 8  (https://www.drupal.org/docs/7/system-requirements/overview and https://www.drupal.org/node/2508231 ) and Symfony  (http://symfony.com/doc/current/reference/requirements.html ) require PHP 5.5.9 so it might be a good idea to directly require 5.5.9 as well. Gives us the possibility to use some Symfony components eventually etc

**Comment by tsteur** [comment]
ping @mattab @sgiehl any thoughts?

**Comment by sgiehl** [comment]
Other projects used PHP 5.5.9 for new requirement, as well. So guess that should be fine.
Examples:
* https://laravel.com/docs/5.3/releases#laravel-5.1
* https://getgrav.org/blog/changing-php-requirements-to-5.5

**Comment by tsteur** [comment]
Awesome. Seeing  Guzzle and the AWS SDK require 5.5.9 as well. Guzzle might be interesting for us to use eventually.
@matt can you quickly confirm re 5.5.9?

**Comment by mattab** [comment]
5.5.9 :+1:
