### ISSUE TITLE
Tracking Events with Custom Dimension

### ISSUE THREAD

**Issue by rsirres** [piwik/piwik#10389]
The [JS Tracking API](https://developer.piwik.org/guides/tracking-javascript-guide#tracking-a-custom-dimension-for-one-specific-action-only) states the following: "To define a dimension value pass an object defining one or multiple properties as the **last** parameter".

However, when I try to track:
`_paq.push(["trackEvent", "category", "action", "name", {dimension1: "fr"}]);`
it considers the last parameter as "trackevent value" instead as "customData".

The problem is in the following method:
https://github.com/piwik/piwik/blob/023d80496bf3cc02a7f6141243e55e3fb262c647/js/piwik.js#L4615

We probably need to check the last parameter whether it is of type Object or simply a string/integer.

**Comment by tsteur** [comment]
Please call it like this:

`_paq.push(["trackEvent", "category", "action", "name", null, {dimension1: "fr"}]);`

It is not meant as in we automatically use the last parameter sent to the method. It's meant as in the last parameter when all parameters are set. I will update the docs.

**Comment by tsteur** [comment]
fixed in https://github.com/piwik/developer-documentation/commit/ce07883b65a6263b16c6f65d67f2ad6d74881a3b
