### ISSUE TITLE
Not able to log data in Search Keyword with no results 

### ISSUE THREAD

**Issue by P-Ajay-Surya** [piwik/piwik#10405]
Hi 
I want to log data in search keyword with no results field of site Search.
Below is my code

var searchKey = false;
if($('#backHaulEstCost').val().trim().length>0){
searchKey = true;
_paq.push(['trackSiteSearch',$('#backHaulEstCost').val().trim(),'Back Haul Est Cost']);
}
if(!searchKey){ 
//_paq.push([ 'trackSiteSearch', keywords + '', 0 ]);
var searchCount = 0; // set this value when rendering the search result page
paq.push(['setCustomUrl', document.URL + '&searchcount=' + searchCount]);
_paq.push(['trackPageView']);
}
Please tell me how i can log data into Search Keywords with no Result widget

**Comment by mattab** [comment]
> Please tell me how i can log data into Search Keywords with no Result widget

you can use this method `trackSiteSearch(keyword, [category], [resultsCount])` and pass the last parameter resultsCount as 0, ie. ` _paq.push(['trackSiteSearch',$('#backHaulEstCost').val().trim(),'Back Haul Est Cost', 0]);`
