### ISSUE TITLE
"Only track visits and actions when the action URL starts with one of the above URLs" does not get saved

### ISSUE THREAD

**Issue by philipptrenz** [piwik/piwik#10412]
Hi there,

I try to track two different domains, which both use the same Joomla. I pasted both tracking codes to joomla and now want to track only the special domain for the website in Piwik.
But when I tick "Only track visits and actions when the action URL starts with one of the above URLs", save and reopen the website configuration the tick is gone. Also users get shown in both Piwik Pages, regardless of what domain (the different domains gets displayed correctly).

Using:
Piwik v2.16.2 (stable)
PHP v7.0.8 

Thanks for help!

**Comment by mattab** [comment]
Hi there, I cannot reproduce this issue, the checkbox is working for me. Can you reproduce this for all your websites? Do other website settings work well, only this checkbox does not?

**Comment by philipptrenz** [comment]
Hey, thanks for looking over it.
I have just the one installation running, there are the two domains mentioned above and a third. I didn't got through the php, but at the database the value "exclude_unknown_urls" in "piwik_site" gets set as it should.
I now compared the user logs of the two sites and it seems that I was wrong and the function is working properly. Maybe I just had the wrong value set and couldn't see it.

So concluding the issue is displaying the value "exclude_unknown_urls" at the frontend.

**Comment by mattab** [comment]
what browser do you use? Could you try to clear browser cache, then can you still reproduce today in your 2.16.2 on a different website?

**Comment by philipptrenz** [comment]
I tried in Chrome 50.0 and Firefox 48.0, also emptied the cache, no changes. Will try to install 2.16.2 locally and try again.

**Comment by mattab** [comment]
@philipptrenz can you please please try with  Piwik 3.0.0-beta if possible? http://piwik.org/faq/how-to-update/faq_159/ 

 as we've redesigned the UI it may actually work better. if you still have the problem please re-open this issue.

**Comment by philipptrenz** [comment]
Hi, I'll not make to test the beta, but as soon as 3.x stable is available I will check if the issue is gone.

**Comment by mpaolo** [comment]
same problem here, with 2.17.1 Firefox 50.0. 
Issue is not just UI since once set the flag, you cannot unset from UI, you have to do it on DB

**Comment by mpaolo** [comment]
ok tried update latest 3.x beta:
that flag now seems to work(for me too)

But flag "use_default_site_search_params" here now has same issue:
edit, tick it, save, re-edit: it's un-ticked
no idea where to check in the DB, I see only changes for the swicth (no)search while the search params fields are always empty

**Comment by mattab** [comment]
@mpaolo thanks for the report, created separate issue #10971
