### ISSUE TITLE
Give plugins using isExcludedVisit hook more information

### ISSUE THREAD

**Issue by e-dschungel** [piwik/piwik#10415]
It would be nice if the hook isExcludedVisit would give more information the the plugins using it.
For example the Plugin BotTracker has no possibility to get the useragent when the log-import script with the --enable-bots options is used. So the Bottracker tables stay empty. Other plugins could use the additional information to make a better choice if the visit should be excluded or not.

The suggestion is to extend the hook with idSite or request and userAgent like this: 

`Piwik::postEvent('Tracker.isExcludedVisit', array(&$excluded, $this->idSite, $this->userAgent));`
`Piwik::postEvent('Tracker.isExcludedVisit', array(&$excluded, $this->request, $this->userAgent));`

see the discussion at https://github.com/Thomas--F/BotTracker/issues/38 (in german)

**Comment by tillsteinbach** [comment]
I strongly support this change! As the parameters are past as array this should not break any existing code. This is really important as the plugins using the hook cannot reliably access any information related to the request.

**Comment by Thomas--F** [comment]
The first suggestion is sufficient for my needs but the second one gives far more information to the plugin.
If I use this parameters instead of $_REQUEST and $_SERVER it doesn't matter if the plugin is called live or from the log-import.

**Comment by mattab** [comment]
Hi @e-dschungel - @tillsteinbach @Thomas--F 

It sounds good to add a new parameter to the event. I propose to add `$this->request` after `$excluded` this way you have access to everything. User agent for example is $this->request->getUserAgent()

Could you maybe submit a pull request for this improvement?

**Comment by mattab** [comment]
Note: If you'd like this change in the next Piwik version 2.16.3 please submit the PR this week!

**Comment by Thomas--F** [comment]
It's not enough, just to add `$this->request`. During the log-import, the user agent an the ip-address is passed directly to the constructor and not in the $request-object.
So I prefer 
`Piwik::postEvent('Tracker.isExcludedVisit', array(&$excluded, $this->request, $this->userAgent));`

To pass all the given information, you can also add the parameter `$this->ip`, but I don't actually need it.

I've made a PR with all informations but there is a syntax error with one of the brackets behind `&$excluded`. How can I repair this in a pull request?

**Comment by sgiehl** [comment]
@Thomas--F  simply add a new commit to the branch the PR comes from. the PR will be automatically updated.

**Comment by Thomas--F** [comment]
OK, the second PR ist correct now.

**Comment by tillsteinbach** [comment]
Sorry, I must be blind, but I cannot find the PR. What is the current state of this feature?

**Comment by Thomas--F** [comment]
Sorry, something went wrong. Now there ist finally a PR:
https://github.com/piwik/piwik/pull/10564
