### ISSUE TITLE
issue tracker: remove the LTS milestone on Github 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10425]
### Given that:

* we won't make many more changes in LTS, 
* the Piwik core team does not have available resource to work on these issues,
* there are too few contributions from other people and companies to solve these LTS issues,

-> we would like to remove the [2.16.x LTS](https://github.com/piwik/piwik/milestone/90) milestone on Github.

# List of 56 issues in 2.16.x LTS milestone

Currently this LTS milestone includes many issues that should ideally be fixed in Piwik: especially several small and medium bugs.

Here is the  list of issues in this milestone as of today:

On ecommerce/Product category the Table sorting doesnot work properly Bug
#10110 opened on 1 May by faridnasiri

On email reports the conversion rate is zero always Bug
#10109 opened on 1 May by faridnasiri

Give plugins using isExcludedVisit hook more information Enhancement
#10415 opened 5 days ago by e-dschungel

Tag to identify messages belonging to the same archiving run Enhancement Regression
#10390 opened 13 days ago by tomasztomik

Excluding IPs doesn't work on php7 Bug
#10373 opened 19 days ago by andrzejewsky

Piwik archivization breaks on missing website. Bug
#10365 opened 20 days ago by sebastianpiskorski

Referrers / Campaigns report: wrong unique visitors count for Campaing Names Bug
#10360 opened 21 days ago by adaqus

Excluding URL query parameters doesn't work on Download Report Bug
#10387 opened 13 days ago by letailli

Actions/Pages: Unique pageviews shouldn't be summed up in hierarchical view Bug
#10127 opened on 7 May by adaqus

Visitors overview is slow when requesting a big date range c: Performance
#9532 opened on 16 Jan by quba

Report data does not display or process for a Segment set to "Real time" and when Browser archiving is disabled and enforced via browser_archiving_disabled_enforce=1 Bug
#10307 opened on 15 Jul by mattab

Custom date range shouldn't trigger archiving for today's day Bug c: Accessibility c: Performance
#10225 opened on 10 Jun by quba

when --force-idsegments is specified, Piwik will archive "all visits" for the day period before archiving the segment(s), but is it necessary? c: Performance Enhancement
#10234 opened on 15 Jun by quba

tiny: visitor log: overlapping element Bug c: Design / UI
#10253 opened on 24 Jun by hpvd

Visitor profile - better visibility c: Usability
#10272 opened on 6 Jul by tomasztomik

--concurrent-requests-per-website works differently for day and other periods Bug c: Performance
#10281 opened on 8 Jul by quba

Optional add link to ip to view data c: Platform
#10286 opened on 12 Jul by joubertredrat

show information geoip database is up to date as expected Enhancement
#10293 opened on 13 Jul by hpvd

'today' and 'yesterday' return different results than using todays date and yesterdays date Bug
#10099 opened on 28 Apr by gleasj

Buttons should have vertical spacing Bug c: Design / UI Easy pick
#10131 opened on 9 May by sirtet

Strange behavior during import apache logs Bug Regression
#10134 opened on 10 May by type0lang

columns order should not vary in exported API requests in TSV format Bug
#10186 opened on 26 May by mattab

Delete data with specific hours Easy pick Enhancement
#10008 opened on 6 Apr by Velborg

"console core:delete-logs-data" does not consider the time difference from GMT. Bug
#9982 opened on 30 Mar by cmt-all

Piwik triggering SQL warnings Bug
#9971 opened on 29 Mar by johannes

New system check to warn that Piwik is not compatible with mod_security c: Usability Task
#3371 opened on 8 Sep 2012 by mattab

Pages - Bounce Rate 100% , Transitions show traffic to subsite instead of exit Bug
#6225 opened on 16 Sep 2014 by MichalTomczak

Pivotting a report w/ all columns or goals view is broken Bug c: Usability
#7506 opened on 23 Mar 2015 by diosmosis

When a report was processed using incomplete log data, display a notification/warning that report data cannot be processed as some raw log data is missing Bug Major
#10280 opened on 8 Jul by mattab

Iframe buster not implemented in reports Bug c: Security
#10185 opened on 26 May by mgonera

X-Frame-Options header set to empty value Bug Easy pick
#10167 opened on 21 May by powerriegel

Disabling period "range" in enabled_periods_API causes segment value suggestions to fail Bug Easy pick
#10159 opened on 18 May by mgonera

Segmented visitor log faulted for specific urls Bug
#10126 opened on 6 May by wronan

Allow disable and configure the 'cdt' ignore mechanisme Easy pick Enhancement
#10116 opened on 4 May by moroine

Widget not found (goals) Bug
#9969 opened on 29 Mar by piwikbugs

Allow to customize mysql settings when running core:archive console command Enhancement
#9959 opened on 24 Mar by jaceklubzinski

Two hours missing from stats on 13th March 2016, daylight savings day Bug
#9949 opened on 19 Mar by jlazic

Get rid of unique visitors metric where it's not really available Bug c: Usability
#9902 opened on 10 Mar by mgonera

When opening the visitor profile, the Segment is applied, which can cause the Visitor Profile to be incomplete Bug
#9893 opened on 8 Mar by mattab

Custom Variables - percentage values in subtable should be based on parent table Bug
#9890 opened on 8 Mar by tsteur

More goal conversions than visits, even when set only one goal conversion per visit. c: Usability
#9843 opened on 25 Feb by RMastop

Visit by days since last visit seems wrong Bug Waiting for user feedback / Cannot reproduce yet
#9839 opened on 24 Feb by milexjaro

Create a warning for user anonymizing IP for GeoIP purposes c: Usability
#9819 opened on 22 Feb by MichalTomczak

Inform users about possible issues with Page Overlay report c: Usability
#9807 opened on 19 Feb by quba

Inform users why there is no data in some actions report when action/event segment is applied c: Usability Enhancement
#9796 opened on 18 Feb by adaqus

Add URL to all websites dashboard scheduled CSV report
#9790 opened on 17 Feb by mgonera

Piwik Logo in Mail Header not shown Bug
#9788 opened on 17 Feb by modsfabio

Lots of piwik_option inserts while archiving when there are thousands of sites c: Performance
#9753 opened on 11 Feb by quba

search result count is always 0 in visitor log Bug
#9733 opened on 9 Feb by hpvd

segment filter with action type "sitesearches" not working Bug
#9710 opened on 5 Feb by hpvd

No data in evolution graph on secondary event dimension Bug
#9634 opened on 26 Jan by dhiridjee

Piwik Sequence table does not auto-update after changing DB prefix Bug Major
#9533 opened on 16 Jan by quba

Top level event visitors / unique visitors are not calculated correctly Bug Major
#9512 opened on 13 Jan by tsteur

When clicking "Next" on Visitor log with an Action Segment applied, the next page may return no data Bug c: Performance
#9200 opened on 12 Nov 2015 by uedatakeshi

Users not receiving Email Reports Bug
#8996 opened on 14 Oct 2015 by autodeskpiwik

Move to the new Travis infrastructure (containers, sudo false) c: Tests & QA
#8535 opened on 11 Aug 2015 by mnapoli

**Comment by mattab** [comment]
I'm planning to move all LTS issues into `Mid term` milestone: https://github.com/piwik/piwik/milestones/Mid%20term - please leave a comment if you have any suggestion.

we'll make this change tomorrow otherwise!

**Comment by sgiehl** [comment]
We should imho check if some of the issues might already be fixed in 3.x branch. If so we should maybe let them remain in LTS milestone. Moving all other issues to mid term is fine for me, as we should try to backport important bug fixes to LTS.

**Comment by mattab** [comment]
@sgiehl AFAIK none of the above will be fixed in Piwik 3.0.0

**Comment by mattab** [comment]
LTS milestone was closed and issues moved to Mid term :+1:
