### ISSUE TITLE
Create a stable branch that is updated after every tagged stable release

### ISSUE THREAD

**Issue by srynot4sale** [piwik/piwik#10436]
I'm trying to automate a deployment of piwik, but unless I specify a tag my only other option for what to deploy is master.

I don't want to download a zip, I want to be able to go a git pull! :-)

**Comment by mattab** [comment]
Hello @srynot4sale 
Please use our Git tags for this purpose, as they are always up to date.

**Comment by mattab** [comment]
Note: you can fetch the latest available Piwik version (ie. git tag) at: https://api.piwik.org/1.0/getLatestVersion/

**Comment by srynot4sale** [comment]
Thank you for the quick response.

I'll write a script around fetching the lastest version but I do think that having a stable branch is a good idea and matches user's expectations. It should be trivial to add to your release process also.
