### ISSUE TITLE
CoreHome Integration tests error

### ISSUE THREAD

**Issue by wronan** [piwik/piwik#10432]
This:
https://github.com/piwik/piwik/blob/master/plugins/CoreHome/tests/Integration/Tracker/VisitRequestProcessorTest.php#L113
should rather be
`$dim = $this->getMock('Piwik\\Plugin\\Dimension\\VisitDimension', array('shouldForceNewVisit', 'getColumnName'));`

**Comment by mattab** [comment]
Should be fixed in Piwik 3 already, and build is green on master as we now use an older phpunit as specified in the composer.json
