### ISSUE TITLE
Make it easier to analyze overlay reports.

### ISSUE THREAD

**Issue by phoob** [piwik/piwik#10447]
Hello! Please see attached code – I have implemented this in my Piwik to make the Overlay reports more useful, but not sure if they meet Piwik coding standards...

(it is a replacement for /plugins/Overlay/client/followingpages.js)

[followingpages.js.txt](https://github.com/piwik/piwik/files/439268/followingpages.js.txt)

What it does is basically adding some css to the number bubbles based on which links are the most clicked. The link that is clicked the most often gets opacity:1 and zoom:2, while the least clicked link gets opacity:0.5 and zoom:1. The position of the bubble is also adjusted according to the zoom factor.

**Comment by phoob** [comment]
screen shot of result:

![skjermbilde 2016-08-26 kl 14 38 45](https://cloud.githubusercontent.com/assets/1475800/18005539/e23f84ca-6b9a-11e6-998d-195a4c094381.png)

**Comment by hpvd** [comment]
looks interesting!

**Comment by phoob** [comment]
I'd like to bump this issue.. Is there anything I can do to speed this up?

**Comment by sgiehl** [comment]
Feel free to create a pull request so someone can have a look at it and test it.

In general: If you are interested in speeding things up and/or sponsoring a feature you may get in touch with our support in order to get a quote how much it would cost. See https://piwik.org/development/

**Comment by phoob** [comment]
Well, I don't have a piwik development setup with Git, so therefore I supplied the full replacement js file – it is just a drop in replacement for /plugins/Overlay/client/followingpages.js . Is it not possible for you to test that? (I have never sent in a pull request before, so to me it seems overly difficult for this kind of issue).

**Comment by mattab** [comment]
Hi @phoob 
Thanks for your suggestion. Created pull request here: https://github.com/piwik/piwik/pull/10580
we'll review it for 3.0.0-beta2

**Comment by mattab** [comment]
Thanks @phoob, your nice improvement was merged!
