### ISSUE TITLE
Change font to System Default or Something which match with Piwik Branding

### ISSUE THREAD

**Issue by TanvirIsraq** [piwik/piwik#10446]
It seems that Piwik using "Verdana,​ sans-serif" as base Font Family. But its better to use Syetem default font for "-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif" for optimal rendering.

Or we can use any other font which matched with Piwik branding like as the font used in "Piwik" logo.

**Comment by tsteur** [comment]
refs https://github.com/piwik/piwik/pull/10397

We have just done this recently and I merged the PR yesterday in #10397 . It will be included in Piwik 3. I will write a blog post about UI updates soon.

**Comment by mattab** [comment]
Check out the blog post: https://piwik.org/blog/2016/09/piwik-3-development-update-1-new-ui-design-api-changes-release-date/

**Comment by TanvirIsraq** [comment]
As Piwik 3 following Material design concept, I think Piwik should use Roboto font family which is recommended for Material design.

**Comment by tsteur** [comment]
We first used Roboto but then decided to remove it since it saves loading additional font and still looks alright with system font fer several reasons mentioned eg in the blog post
