### ISSUE TITLE
Piwik 3 Blog post about some important changes

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10454]
I'd like to write one blog post about some changes that are a bit more "important" or have the potential to break some systems. Here's a summary that should be included in the blog post:

* [x] https://github.com/piwik/piwik/pull/10009 Apply default filter_limit to all API calls 
* [x] https://github.com/piwik/piwik/pull/10404 Extract the first IP from HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP and HTTP_CF_CONNECTING_IP and HTTP_X_FORWARDED_HOST when there is more than one IP
* [x] we had to drop support for IE 9, https://github.com/piwik/piwik/pull/10397#event-770138101
* big db schema changes

**Comment by mattab** [comment]
Also let's make sure each of those important changes are noted in the developer changelog as well ( #10404 is not currently but should be)

**Comment by mattab** [comment]
Updated [Piwik requirements](https://piwik.org/docs/requirements/) page already, as well as the [other FAQ](https://piwik.org/faq/troubleshooting/faq_17045/) mentioning the PHP version.

**Comment by mattab** [comment]
Blog post published! [Piwik 3 Development Update #4 – Important notes and breaking changes](http://piwik.org/blog/2016/10/piwik-3-development-update-4-important-notes-breaking-changes/)
