### ISSUE TITLE
[tested] PHP7.0.* not yet supported on Stable version 2.16.2

### ISSUE THREAD

**Issue by alexonbalangue** [piwik/piwik#10451]
I tested for install on server with PHP7 not works when i installed.

When is support.

Regards thanks

**Comment by sgiehl** [comment]
What error do you get?

**Comment by alexonbalangue** [comment]
impossible finalise the installer until ends. (i not yet take debug it)

**Comment by sgiehl** [comment]
If you could have a look at the error log, that would be great. Piwik already should be compatible with PHP 7. If there is still an issue, we will try to fix it.

**Comment by alexonbalangue** [comment]
ok, i debug, no error found and install later days now works with 7.0.10 thnks
