### ISSUE TITLE
token_auth is not working properly

### ISSUE THREAD

**Issue by jitumandal** [piwik/piwik#10450]
Hi,
I have been using piwik for so long. Lately, piwik got automatically updated from 2.16.0 to 2.16.2. Earlier, I could easly access custom dashboard by sending token_auth=xyx with idDashboard=xyz with url without login. But now after piwik updation it got stopped. It is only opning the defaul dashboard. But, when I hit url after login it is opening correct dashboard.
  Do anyone has any idia about this problem. Please help.

**Comment by mattab** [comment]
Hi @jitumandal 

Can you check that you use the correct `token_auth` for your user? maybe the token_auth has changed. please confirm
