### ISSUE TITLE
Deprecated - Non-static method Piwik\Db\Adapter::isRecommendedAdapter() should not be called statically,

### ISSUE THREAD

**Issue by bkbeckman** [piwik/piwik#10463]
During the database setup portion of the installation process, I see an error message.

`.../Installation/FormDatabaseSetup.php(44): Deprecated - Non-static method Piwik\Db\Adapter::isRecommendedAdapter() should not be called statically, assuming $this from incompatible context - Piwik 2.16.3-b2 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)`

**Comment by tsteur** [comment]
Thanks for reporting it 👍  I will fix it now
