### ISSUE TITLE
Disabled UserCountry plugin fails on some MySQL versions

### ISSUE THREAD

**Issue by tmuic** [piwik/piwik#10472]
It fails due to MySQL "feature" of silently defaulting CHAR(X) not null values to '' (empty string)

So on Distrib 5.5.35, it worked and inserted empty strings silently
and started failing on  Distrib 5.7.13 with:
`Error query: SQLSTATE[HY000]: General error: 1364 Field 'location_country' doesn't have a default value 
`
All other location_X fields are nullable so propably this one could be nullable as well (or with sane default) in order to avoid such errors.

NOTE: I think this is also possible with strict settings on older MySQL versions

**Comment by tmuic** [comment]
Seems that this is to strict mode enabled by default in 5.7;

> SQL mode changes.  Strict SQL mode for transactional storage engines (STRICT_TRANS_TABLES) is now enabled by default.

https://dev.mysql.com/doc/refman/5.7/en/mysql-nutshell.html

**Comment by mattab** [comment]
What Piwik version are you using?

See https://github.com/piwik/piwik/issues/9920  https://github.com/piwik/piwik/pull/8930 https://github.com/piwik/piwik/issues/5178 https://github.com/piwik/piwik/issues/8853 

and should be fixed hopefully in the next Piwik 3 beta1 https://github.com/piwik/piwik/issues/9231
