### ISSUE TITLE
inifinite nested ui [3.x-dev]

### ISSUE THREAD

**Issue by nahueldotme** [piwik/piwik#10470]
Hi,
I just upgraded (a test env) from piwik 2 to 3.x-dev branch, and the migration said everything went find, but when I login, I get this infinite nested ui (which crash my browser). I tried to find other users with the same issue, but no luck (I'm kind of new to github issue tracker). Any idea on how to debug is welcome!!!

![nested ui screenshot](https://www.dropbox.com/s/01zglncob89jtyf/piwik-nested.png)

ps: how I'm supposed to atttach screenshots here?

**Comment by nahueldotme** [comment]
I managed to make a local copy run successfully so, I'm pretty sure has something to do with the read only file system of that environment...I'm not sure how I'm gonna debug it (I need to see what files is piwik is writing outside /tmp and /config), but that my next move.

**Comment by tsteur** [comment]
Are you still having this problem @nahueldotme ? Which files / directories are not writable? Did you see any specific error message?

You can attach screenshots by dragging them into this text field. However, they only support a few formats like png and jpg

**Comment by nahueldotme** [comment]
Ohhh, I'm sorry I forgot to post the solution:I happened because my webserver was blocking access to .json files at piwik directory.

BTW: This tutorial was key to debug it (I order to run js without crashing my browser): http://www.html5rocks.com/en/tutorials/developertools/async-call-stack/

I'm setting this issue as close ;)

**Comment by tsteur** [comment]
Thx for letting us know. Do you remember which .json file(s) was/were blocked?

**Comment by nahueldotme** [comment]
All (was my fault on webserver settings), but the fist to make it crash, was manifest.json
