### ISSUE TITLE
Error: Class Piwik\PiwikPro\Advertising does not exist

### ISSUE THREAD

**Issue by dankeller** [piwik/piwik#10477]
After updating to 2.16.2, every site dashboard displays the following error:
Class Piwik\PiwikPro\Advertising does not exist

![image](https://cloud.githubusercontent.com/assets/1724950/18320957/a49ae3c0-74f1-11e6-9d96-fe4c99445939.png)

From the error_log:
`Error in Piwik: Class Piwik\\PiwikPro\\Advertising does not exist, referer: https://piwik.************/index.php?module=CoreHome&action=index&date=previous30&period=range&idSite=1`

Running Apache 2.4, PHP7, Ubuntu 16.04

**Comment by mattab** [comment]
Hello, please delete the folder `plugins/PiwikPro`
