### ISSUE TITLE
Add explicit warning to docs about event registering logic

### ISSUE THREAD

**Issue by tmuic** [piwik/piwik#10475]
There are two very similar functions listed in this document
https://developer.piwik.org/api-reference/Piwik/Plugin#getlisthooksregistered

`registerEvents()`

`getListHooksRegistered()`

If you by mistake implement both in same plugin the latter one will override the former one and events registered in first one will be lost.

Error can happen easily if basing work on different plugins which use either one of this variants.

Also seems that events and hooks terminology is used interchangelably and should be explicitely stated that those two mean the same thing.

It can be very confusin

**Comment by mattab** [comment]
Thanks for suggestion. Hopefully it will be fixed after adding `@ignore` the method should be removed from the auto-generated documentation. Will check again in 10min as it runs every 10min

**Comment by mattab** [comment]
@tsteur the developer doc was not updated although we added @ignore - any idea maybe?

**Comment by tsteur** [comment]
fixed in https://github.com/piwik/developer-documentation/commit/1107e497f4e90e68ed85f00e47b8fc9b4e17d43a must be a bug in Sami docs parser or so
