### ISSUE TITLE
Piwik using CLoudflare IPs instead of real user IPs

### ISSUE THREAD

**Issue by MikeHergaarden** [piwik/piwik#10476]
When hosting Piwik behind cloudflare the IP reporting is off. This is correct behaviour, but it would be preferred to make use of the cloudflare header that's reporting the real IP for clients.

This could be an easy fix or option:

if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
  $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
}

**Comment by MikeHergaarden** [comment]
I guess apache mod_cloudflare is a better fix

**Comment by mattab** [comment]
The solution should be already documented here: http://piwik.org/faq/how-to-install/faq_98/
