### ISSUE TITLE
Issues installing Piwki (Blank Screen)

### ISSUE THREAD

**Issue by clarm060** [piwik/piwik#10485]
I have tried to Install Piwki on a Cpanel Server with follows all Requirements (Php5.5 PDO extensions installed)

![blank](https://cloud.githubusercontent.com/assets/13317639/18419441/c29d963a-7828-11e6-90ce-067d6e1b4815.png)

Any thoughts?

**Comment by sgiehl** [comment]
Any errors in PHP error log or in browser console?

**Comment by alexonbalangue** [comment]
But the http://php.net/ not supported anymore, why continus?

**Comment by clarm060** [comment]
I look there are no PHP errors or Console errors

**Comment by mattab** [comment]
What is the full HTML output of the page? maybe there is an error in there that can help us.
otherwise also check our FAQ: https://piwik.org/faq/troubleshooting/faq_19489/

**Comment by clarm060** [comment]
sorry it took me so long to respond to this, it looks like once i replaced the code with the 3.0 it works now. Not sure if Godaddy did something with the settings on my shared server, but re-uploading the files seemed to do the trick,
