### ISSUE TITLE
Stop Piwik from setting any cookies for visitors

### ISSUE THREAD

**Issue by paya-cz** [piwik/piwik#10484]
So I want to make sure none of my visitors ever get any cookies at all. I use the following code:

```html
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['disableCookies']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//<?php echo $_SERVER['HTTP_HOST']; ?>/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//<?php echo $_SERVER['HTTP_HOST']; ?>/piwik/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
```

However, the Piwik PHP code seems to be setting an expired `_pk_uid=deleted` for all visitors (using a request to `piwik.php?action_name=XXX&idsite=XXX&rec=XXX&r=XXX&h=XXX....` which returns 43-byte long 1x1 empty `image/gif`). Chrome then reports as if my website set a real cookie:

![chrome](https://cloud.githubusercontent.com/assets/10402560/18417106/4b5f1d2e-7827-11e6-89c6-73535519cd1c.jpg)

Firefox recognizes the cookie in response, but does not set it for the website:

![ff1](https://cloud.githubusercontent.com/assets/10402560/18417114/6228ab74-7827-11e6-996a-b638d5787e12.jpg)
![ff2](https://cloud.githubusercontent.com/assets/10402560/18417115/62434830-7827-11e6-8f53-b8150b49fc2d.jpg)

Internet Explorer completely ignores the cookie and does not even notice it in the response headers:

![ie](https://cloud.githubusercontent.com/assets/10402560/18417122/749023c8-7827-11e6-8451-53a595844125.jpg)

I get it why Piwik does this - to delete the `_pk_uid` cookie in case it was already set before. But in my case, this will never be required since I do not plan to use cookies at all from the site's very inception. How can I stop Piwik from issuing even the expired cookie? I do not want Chrome users to be confused and think I am actually setting a cookie. Maybe the `piwik.php` can be tuned to set the expired cookie only in case the `_pk_uid` was actually set before?

**Comment by mattab** [comment]
Hello @paya-cz 

* Are you using ["third party cookie"](https://piwik.org/faq/how-to/faq_118/) (ie. did you set this config setting in your config file) ?

* If not, have you maybe clicked in the Admin > Exclude my visits using cookie link?

**Comment by mattab** [comment]
Could you try this patch: https://github.com/piwik/piwik/pull/10579/files

I haven't tested it but hopefully it fixes the issue

**Comment by mattab** [comment]
@paya-cz please can you confirm whether the patch above, fixes the issue you reported?

**Comment by paya-cz** [comment]
@mattab Hi, sorry for the late reply, I was busy with other things.

- I am not using third party cookie. The only change I made to the deployed Piwik was just adding the `_paq.push(['disableCookies']);` line.
- I have not clicked the `Exclude my visits using cookie` link
- I am not using `Do not track` and I have disabled all addons before testing, particularly AdBlock and Ghostery

Anyway, I am no longer able to reproduce the issue in Chrome 53.0.2785.143 m 64-bit. I was using previous stable release when I reported the issue. To my experience, the previous Chrome release was kinda buggy, I had other problems mainly related to visual glitches / rendering issues. They all seem to be fixed in this version, including the cookie thing. But as you can see from the screenshots, I was not making this up. I will let you know if the issue ever shows up again. Thanks for your assistance.
