### ISSUE TITLE
number_format() expects parameter 1 to be double, array given

### ISSUE THREAD

**Issue by thefraj** [piwik/piwik#10495]
ErrorException (E_WARNING)
HELP
number_format() expects parameter 1 to be double, array given

(line 180 of app/src/Analytics/Controller/WebAnalyticsController.php) which contains):

	$visits = number_format($visits, 0, trans('i18n.dec_point'), trans('i18n.thousands_sep'));

If it helps, for reference, $visits variable created on line 174 of this same file (WebAnalyticsController.php) on the line:

$visits = \App\Core\Piwik::getVisits($app->piwik_site_id, $date_start, $date_end);

**Comment by mattab** [comment]
Hello @thefraj 

This is not a bug in Piwik but in this library you are using: \App\Core\Piwik::getVisits /// WebAnalyticsController
