### ISSUE TITLE
Piwik Visitors in Real-Time displays nothing

### ISSUE THREAD

**Issue by khalilst** [piwik/piwik#10504]
Hello
I'm new to latest version Piwik 2.6.12 and installed in ubuntu 14.04 server with nginx and PHP7.
But I feel Piwik is not track all visits. Visit stats is very lower than our tests and visitors.
Also Visitors in Real-time displays zero visit, but it's not!
I've checked the error log and there's no error in error log.
What's wrong here? Could you please help me to find out.

**Comment by mattab** [comment]
Hello @khalilst 
please check: https://piwik.org/faq/troubleshooting/faq_58/

Thanks
