### ISSUE TITLE
path disclosure in http://developer.piwik.org/js/ and http://developer.piwik.org/css/

### ISSUE THREAD

**Issue by karthickumar42** [piwik/piwik#10507]
go to http://developer.piwik.org/js and http://developer.piwik.org/css/ in google chrome browser

path disclosure is displayed in browser

**Comment by mattab** [comment]
Thanks for report. The source code of this website is publicly available at: https://github.com/piwik/developer-documentation/

fixed in https://github.com/piwik/developer-documentation/commit/fa246a89c9f53c50e1557a0eb15bedf4e77550a9
