### ISSUE TITLE
Evolution and visit by time disappear when coming back to tab

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#10508]
Piwik 2.16.1, Chrome 51 under Windows 8.1. 
PHP 5.5.x , Apache 2.4.x

After letting a tab open over a period of time > 20 minutes, some red graphics disappear when switching to Piwik's tab like in this screenshot:
![image](https://cloud.githubusercontent.com/assets/5972510/18556454/56235116-7b39-11e6-8321-ff5abf8be52e.png)

Just switching to another tab and then coming back to Piwik "solves" the problem. uBlocl origin is set to "off" on my Piwik site.

This is not critical but I was curious if I was alone with this behavior...

**Comment by gaumondp** [comment]
I updated my Chrome to 53 and didn't get the misbehavior in the last 5 hours... I'll close the ticket tomorrow if it doesn't happen again.

**Comment by mattab** [comment]
Thanks for letting us know @gaumondp
