### ISSUE TITLE
Undefined index General_Mobile during translations

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#10529]
Hello there,
 writing plugins you suggest to avoid adding strings then reusing already present strings.
I wrote a backporting MobileVsDestop plugin and I'm using: 

- General_Mobile
- General_Desktop
- General_Unknown

to refer to a translated string of device types.

The problem is I get a warning while visiting old stats. Any help is appreciated :) 

![screenshot6](https://cloud.githubusercontent.com/assets/92727/18664332/79492ca0-7f22-11e6-8db4-0c14974ea116.png)

**Comment by sgiehl** [comment]
Without knowing what exactly is in `RerMobVsDesk.php` line 51, it's hard to say what is going wrong. The translation key should still exist.

**Comment by tassoman** [comment]
Foreach Device Family I found, I sum _nb_visits_ by type. My reference is the old _functions.php_ I've found in MobileVsDesktop plugin < 2.10.x

To fill types I'm using an array as matrix with the General_* string as key so I bet I'm trying to sum something not yet existent. Nevermind.
