### ISSUE TITLE
help required to upgardePIWIK from version 2.16.0 to 2.16.2 without losing already present data

### ISSUE THREAD

**Issue by samratng07** [piwik/piwik#10538]
Hi All,

I need to upgrade PIWIK to version 2.16.2 from 2.16.0 without losing the data that I have collected in the last 6 months can you please guide me on this

**Comment by RMastop** [comment]
Hi @samratng07,

Did you check the following page?
http://piwik.org/docs/update/
It describes two methods of upgrading Piwik.

**Comment by mattab** [comment]
Updating from any version to any version works without losing data
