### ISSUE TITLE
count visits but no visitors or other things

### ISSUE THREAD

**Issue by wklueter** [piwik/piwik#10540]
dear all
I'm using version 2.16.2 and use also new Tracking-code. I will attached tracking-code ( all my sides use same code ) and a report Sep.2016. 
on Report you see only visitis nothing else.
Many Thx for your support
Best regards 
Willi 
[Report_piwik_sep_2016.txt](https://github.com/piwik/piwik/files/487403/Report_piwik_sep_2016.txt)

[piwik_track_neu_0916.txt](https://github.com/piwik/piwik/files/487417/piwik_track_neu_0916.txt)

**Comment by mattab** [comment]
Hello, please ask in the forums: http://forum.piwik.org/
