### ISSUE TITLE
Allow for underscores (and perhaps other characters) in plugin names.

### ISSUE THREAD

**Issue by bkbeckman** [piwik/piwik#10541]
Currently, Piwik restricts the naming of plugins using the following regular expression: `'/^[a-zA-Z]([a-zA-Z0-9]*)$/D'`.  I propose that any valid PHP class name be a valid plugin name.  According to the PHP documentation, a valid class name is defined as,

> The class name can be any valid label, provided it is not a PHP reserved word. A valid class name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: ^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$. 

Barring this expansion.  I propose that underscore character included as a valid character for plugin names.

**Comment by mattab** [comment]
There is a theme with an `_` here: http://themes.piwik.org/Proteus_Bold
Did we maybe change the naming rules after this theme was published?

**Comment by mattab** [comment]
This will be fixed with https://github.com/piwik/piwik/pull/10737

**Comment by mattab** [comment]
This should be fixed in 2.17.0-b2 released in a few minutes
