### ISSUE TITLE
Bad regexp in DbHelper.php

### ISSUE THREAD

**Issue by wronan** [piwik/piwik#10547]
Here https://github.com/piwik/piwik/blob/master/core/DbHelper.php#L201 instead of 

```
return (0 !== preg_match('/(^[a-zA-Z0-9]+([a-zA-Z_0-9.-\+]*))$/D', $dbname));
```

should be 

```
return (0 !== preg_match('/(^[a-zA-Z0-9]+([a-zA-Z_0-9.\-\+]*))$/D', $dbname));
```

('-' was not escaped).

**Comment by tsteur** [comment]
Can you maybe issue a PR for this?

**Comment by wronan** [comment]
Sure :+1:  Just wanted to know if you are interested in fixing that first.
Will do that later today after work.

**Comment by mattab** [comment]
@wronan We are definitely interested in pull requests fixing bugs! :-) even better when they include a test of course, but already great to have without a test..

**Comment by kylekatarnls** [comment]
Mini-trick: the `+` does not need to be escaped in a class and neither the `-` if it ends the class:
So ```[a-zA-Z_0-9.+-]``` works fine in this order.

**Comment by wronan** [comment]
Thx. Trick is good but when some sign is escaped then it is more explicit (in my opinion).

**Comment by kylekatarnls** [comment]
I understand, in this case, you should also escape the dot I think.

**Comment by wronan** [comment]
Hey guys, I PRed the changes ^
Please review.
