### ISSUE TITLE
Real-time Map difficult to use / unusable with higher traffic

### ISSUE THREAD

**Issue by Xionax** [piwik/piwik#10549]
Its is impossible to use the real-time map (zoom step 2). To zoom in it requires the user to click on the country. However if the country is small (like the netherlands) the yellow circles will completely cover it. Resulting in the fact that you cant zoom in any further. 

<img width="374" alt="screen shot 2016-09-23 at 15 56 37" src="https://cloud.githubusercontent.com/assets/14850391/18788218/55855272-81a6-11e6-804d-37d9a0f8cd4e.png">

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=UserCountryMap&action=realtimeWorldMap&idSite=7&period=day&date=yesterday

Using: Latest version

**Comment by lipis** [comment]
Give the option to see the live map by highlighting the countries when showing the globe, but when selecting a specific country then show these bubbles :)

**Comment by mattab** [comment]
Yes this is much needed. Already requested in https://github.com/piwik/piwik/issues/5917 and https://github.com/piwik/piwik/issues/4301

Anyone keen to submit a pull request?

**Comment by lipis** [comment]
No but we are about to start paying for *Piwik PRO Cloud* if that can help somehow :)

**Comment by sgiehl** [comment]
@lipis I doubt it. See https://piwik.org/faq/new-to-piwik/faq_21984/

**Comment by lipis** [comment]
Then all I can say is thank you!

P.S. maybe you should start charging the Piwik PRO more.. ;)

**Comment by mattab** [comment]
Hi @lipis get in touch maybe we can find a way: https://piwik.org/contact/
