### ISSUE TITLE
All websites dashboard: the metrics selector's text is partially hidden  

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10559]
Reproducible in FF and Chrome

![evolution visits not visible](https://cloud.githubusercontent.com/assets/466765/18822381/b7af706a-840b-11e6-8194-ac235eac7c08.png)

* `Visits` is not fully visible 
* the selector appears not to use the material design

**Comment by tsteur** [comment]
just fyi: this works on Chrome under Mac but fails on firefox on mac
