### ISSUE TITLE
in General Settings dashboard, getting "Invalid PHP version" 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10560]
Reproduce URL is: `index.php?module=CoreAdminHome&action=home&showaddsite=1&period=day&date=yesterday&idSite=1`

Marketplace request URL is `http://plugins.piwik.org/api/2.0/plugins?keywords=&php=7.0.9-1%2Bdeb.sury.org%7Etrusty%2B1&piwik=3.0.0-b1&prefer_stable=1&query=&sort=newest`

My PHP version is `PHP 7.0.9-1+deb.sury.org~trusty+1`

Response from marketplace was: `Invalid PHP Version`

Screenshot:

![invalid php version](https://cloud.githubusercontent.com/assets/466765/18822488/e37e8996-840c-11e6-8e00-8a51ca8f0def.png)

**Comment by tsteur** [comment]
what is the output of `PHP_VERSION` vs `phpversion()`

**Comment by mattab** [comment]
same output:
```
$ php -r 'echo PHP_VERSION . "\n" . phpversion() . "\n"; '
7.0.9-1+deb.sury.org~trusty+1
7.0.9-1+deb.sury.org~trusty+1
```

**Comment by tsteur** [comment]
issued PR in https://github.com/piwik/piwik/pull/10573

Can you test output of `php -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION;"`

if it works I will fix it for Piwik 2 as well

**Comment by mattab** [comment]
```
$ php -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION;"
7.0.9
```
