### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by lukshap** [piwik/piwik#10582]
Hi!
While I try to access to piwik I got "The directory "/var/www/piwik/tmp/cache/tracker/" does not exist and could not be created." error, but I even grant 777 rught either to piwik/tmp and piwik/config directories.

**Comment by lukshap** [comment]
![error](https://cloud.githubusercontent.com/assets/22010985/18876664/33262cb2-84d3-11e6-835c-3c411194c243.png)
![permissions](https://cloud.githubusercontent.com/assets/22010985/18876665/332c94d0-84d3-11e6-98e2-7bc986bd0e52.png)

**Comment by lukshap** [comment]
UPD:Selinux is disabled.

**Comment by mattab** [comment]
Hello @lukshap 
can you please try with Piwik 3.0.0 beta, do you get the same issue or a different message? http://piwik.org/faq/how-to-update/faq_159/
