### ISSUE TITLE
Tracking HTTP API: Server IP is tracked instead of user IP 

### ISSUE THREAD

**Issue by SDPrio** [piwik/piwik#10581]
Hi,

I have integrated the [Tracking HTTP API](http://developer.piwik.org/api-reference/tracking-api) using the [PHP Client](http://developer.piwik.org/api-reference/PHP-Piwik-Tracker) into my Symfony 2.7 WebApp.

To track a page view I simply call clients `doTrackPageView($documentTitle)` method from within the page controllers. This works fine with one problem: **All page views are tracked with the IP of the WepApp server instead of the users IP.**

 I added a `echo` statement to output the URL that is used by the Clients `sendRequestsendRequest(...)` method:

    URL3: https://piwik.example.com/piwik.php?idsite=1&rec=1&apiv=1&r=177493&cip=56.71.16.47&_idts=...

This is the same, no matter if call use `$this->tracker->setIP($_SERVER['REMOTE_ADDR'])` or not. The URL transfers the correct IP (56.71.16.47) but piwik tracks the server IP instead.

**Comment by mattab** [comment]
Hello @SDPrio 
you need to call `setTokenAuth` to set your token as setting a custom IP address requires a token auth, as documented in http://developer.piwik.org/api-reference/tracking-api
