### ISSUE TITLE
NumberFormatting problems, avg. page generation time is displayed with two decimal points in German language

### ISSUE THREAD

**Issue by OliverIost** [piwik/piwik#10596]
After moving to a new server (from Debian 7 with standard mysql and php5.6 via dotdeb to Debian 8 with mariadb and php7.0 via dotdeb) some problems occur.
With language set to german seconds are shown like 0..15 s and 0.2 s (where 0,15 s and 0,2 s would be correct).

To resolve the problem for me, I changed line 224 in NumberFormatter.php to:

if (!is_numeric($value) || is_float($value)) {

**Comment by mattab** [comment]
Hi @OliverIost 
Where in the reports do you see this displayed? I cannot reproduce on PHP 7.0.9 using German language, seconds are shown correctly for me.

I'm using the 2.16.3 RC which you can download from our "Beta" channel: http://piwik.org/faq/how-to-update/faq_159/

**Comment by mattab** [comment]
Ok this bug was also reported here: https://github.com/piwik/piwik/issues/10594 by 
@sesom42

> "Action -> Page titles" shows the avg. page generation time. With language set to english the numbers are displayed correctly. With language german numbers are displayed with two decimal points.

![piwik localization bug](https://cloud.githubusercontent.com/assets/8649051/18944737/6685dad0-8627-11e6-93f8-f7b1fb1b83ef.png)

> Piwik 2.16.2, PHP 5.6.24

@sgiehl could you maybe take a look at this one?

**Comment by mattab** [comment]
As @sesom42 is not using PHP7, this is not a PHP7 bug, so it must be caused by another configuration setting or so. Not yet able to reproduce it.

**Comment by mattab** [comment]
Can anyone else reproducing it? do you know how we could reproduce this issue? 

Can you reproduce it on demo.piwik.org ?

**Comment by sgiehl** [comment]
For me it's displayed as expected like `1,3s`. On my local install it's the same using PHP 5.6 or PHP 7.
@OliverIost  which server locale have you set?

**Comment by OliverIost** [comment]
I updated to 2.16.4 and the problem is back (cause my „patch“ is now missing).

locale shows the following:

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

Please remember: There shows up „0..37 s“ but „0.2 s“

**Comment by sesom42** [comment]
I have tracked it a little bit down. Tooltips in the page also shows the problem.
![piwik pagetitles de numberformat](https://cloud.githubusercontent.com/assets/8649051/19089528/ee23273e-8a7a-11e6-948d-e31ff2957bbf.png)
The numbers in the tooltip are formatted with method `getPrettyTimeFromSeconds`. If I append the unformated numbers to the tooltip (in plugins/Actions/Reports/Base.php) they are displayed correctly.

The problem only occurs with the German language setting. Other language settings show the numbers correctly (according to the respective country format).

Debian 8.6, Nginx 1.6.2, php-fpm 5.6.24 + php5-mysqlnd, MariaDB 10.0.27 (other server), system locale on webserver: `LANG="de_DE.UTF-8"`, charset of db connection:
` show variables like '%char%';
 +--------------------------+----------------------------+
 | Variable_name            | Value                      |
 +--------------------------+----------------------------+
 | character_set_client     | utf8                       |
 | character_set_connection | utf8                       |
 | character_set_database   | utf8                       |
 | character_set_filesystem | binary                     |
 | character_set_results    | utf8                       |
 | character_set_server     | utf8                       |
 | character_set_system     | utf8                       |
 | character_sets_dir       | /usr/share/mysql/charsets/ |
 +--------------------------+----------------------------+
 8 rows in set (0.00 sec)
`

**Comment by mattab** [comment]
@sgiehl did you have a chance to reproduce this issue? maybe it could be due to PHP locate configuration...

If anyone else has an idea let us know

**Comment by mattab** [comment]
we haven't been able to reproduce so far so please send more info or help us reproduce. for now moving out of 2.17.0 / LTS

**Comment by OliverIost** [comment]
Hmm, what about my „patch“: if it doesn't crash something in your installations – why not use it? For me with it everything is okay. Or what does happen in your installations then?

**Comment by mattab** [comment]
@OliverIost I think your patch basically disables the formatter in some cases. feel free to create a pull request with the patch as it will run the whole thousands of automated tests and we can see what breaks

**Comment by OliverIost** [comment]
That's right, it disables the formatter. It must be a kind of type problem which only occurs in some cases we all do not really understand. As long as I understand it, the formatter is only needed for numbers >=1000 (=> to format it like 1,000 or 1.000 - english / german) which are integers and for display numbers with %. But the %-numbers seem always to be rounded to integers before the formatter is called (otherwise my patch would make other problems). If these are the only cases where the formatter is needed, my patch should not make any problems.

As long as I do not oversee this – I do not want to make new problems ;)

**Comment by peterbo** [comment]
@sesom42 @OliverIost do you have the php5-intl extension installed? Perhaps I have an idea, what's happening here.

**Comment by sesom42** [comment]
@peterbo php5-intl was installed. After uninstalling php5-intl the problem remains unfortunately.

**Comment by OliverIost** [comment]
@peterbo php5-intl was installed. After upgrading to php7.0 (with php7.0-intl) the problem remains.

**Comment by peterbo** [comment]
@sesom42 @OliverIost what is the output of "locale -a" on your server?

**Comment by OliverIost** [comment]
C
C.UTF-8
de_DE
de_DE@euro
de_DE.iso88591
de_DE.iso885915@euro
de_DE.utf8
deutsch
german
POSIX

**Comment by peterbo** [comment]
I think there is the problem. We try to set `setlocale(LC_NUMERIC, array('en_US.UTF-8', 'en-US'));` for juggling with unified types of float values. In this case, setlocale fails, because "en_US.UTF-8" is not installed on the server. PHP casts back the float values to be comma separated on every operation and so, the format logic fails.

Can we check if this is the case? 
Console: `cat /usr/share/i18n/SUPPORTED` - if this list contains "en_US.UTF-8", please try to install it if possible: `sudo locale-gen en_US.UTF-8`

When we know that this was the reason, we can think of a possible fix.

**Comment by OliverIost** [comment]
I had to use „dpkg-reconfigure locales“ to add en_US.utf8  ( sudo locale-gen en_US.UTF-8 generates the locales as they were – but did not add the new one)

After adding as described „locale -a“ shows

C
C.UTF-8
de_DE
de_DE@euro
de_DE.iso88591
de_DE.iso885915@euro
de_DE.utf8
deutsch
en_US.utf8
german
POSIX

And now – after restarting apache – it works! Thank you @peterbo !

**Comment by peterbo** [comment]
@OliverIost thanks for testing, then I probably know how to fix this.

**Comment by OliverIost** [comment]
👍

**Comment by sesom42** [comment]
Works here to! Thank you @peterbo

**Comment by peterbo** [comment]
Sorry... pull request went to my own fork at first.
