### ISSUE TITLE
Piwik is slowing down website

### ISSUE THREAD

**Issue by saqib16** [piwik/piwik#10595]
Hi ,

Is there any modification done regarding piwik snippet as mentioned here :
 
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    window.addEventListener('load', function() {
      var u="//mysite/piwik/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', 1]);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    });

https://forum.piwik.org/t/piwik-is-slowing-down-my-website-load-speed-but-why/15257/9

Kind Regards,
Saqib

**Comment by tsteur** [comment]
Have a look here: https://github.com/piwik/piwik/issues/9077

**Comment by mattab** [comment]
See also: [ Will the Matomo Analytics JS Tracker slow down my site?](https://matomo.org/faq/general/will-the-matomo-analytics-js-tracker-slow-down-my-site/)
