### ISSUE TITLE
Error in the display of localized numbers

### ISSUE THREAD

**Issue by sesom42** [piwik/piwik#10594]
"Action -> Page titles" shows the avg. page generation time. With language set to english the numbers are displayed correctly. With language german numbers are displayed with two decimal points.

![piwik localization bug](https://cloud.githubusercontent.com/assets/8649051/18944737/6685dad0-8627-11e6-93f8-f7b1fb1b83ef.png)

Piwik 2.16.2, PHP 5.6.24

**Comment by mattab** [comment]
Thanks for the report @sesom42 , let's continue discussion in this issue: #10596
