### ISSUE TITLE
Sometimes the datatable footer controls can be hidden

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10605]
I don't manage to reproduce this one consistently or even easily, but for sure sometimes the control, are being partially hidden, as if the overflow was hidden.

It ends up looking like this, making the datatable controls unusable / un-reachable:

![custom var goal metrics controls hidden](https://cloud.githubusercontent.com/assets/466765/18979522/3e22a9a4-8728-11e6-9c03-b03a8a3f0409.png)

**Comment by mattab** [comment]
Here is how to reproduce consistently:
* Open the browser with a small width eg. like a mobile phone
* Open the page Visitors > Devices
* The controls are hidden:

![hidden controls](https://cloud.githubusercontent.com/assets/466765/18980097/4f8221fc-872d-11e6-9cdf-f51c308f00f1.png)



Maybe this article talks about this issue, but not sure: https://css-tricks.com/popping-hidden-overflow/ - if that's the same issue, it seems maybe we'd need to position the element in javascript manually.

**Comment by mattab** [comment]
Looks like a limitation of HTML/CSS as per http://stackoverflow.com/a/6112856

Solution could be to extract the DOM node for the footer list, and move it out of the container..  likely we don't do it (non trivial?)

**Comment by tsteur** [comment]
very non trivial

**Comment by mattab** [comment]
Moving back to 3.0.0 (ie. we don't need to do it before release, maybe during 3.X dev cycle...)
