### ISSUE TITLE
Find a new loading icon with a transparent background

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10604]
As Piwik 3 now has a grey background, it would be good to use a Loading icon that has a transparent background, so the "White background" is not visible while the page is loading. Since the page loading is a critical part of the user experience (as it is always visible and users will see loading constantly while using the app), this would make a big impact. 

Maybe also the loading icon could be slightly bigger.

![loading white background](https://cloud.githubusercontent.com/assets/466765/18979431/4770fa2a-8727-11e6-9d57-927b1bf79643.png)

**Comment by tsteur** [comment]
maybe a duplicate of https://github.com/piwik/piwik/issues/8987 ?

**Comment by mattab** [comment]
Yes, moving this other one to beta2
