### ISSUE TITLE
Piwik Ecommerce- how to track my best seller

### ISSUE THREAD

**Issue by siddharth3977** [piwik/piwik#10616]
I want to track who my best seller is, I can pass an extra parameter seller id in order tracking api.

**Comment by mattab** [comment]
Hello @siddharth3977 
maybe you can use "Custom Dimensions" for this? https://piwik.org/docs/custom-dimensions/ 

or what do you mean exactly?

**Comment by siddharth3977** [comment]
What I mean is,  with each order which I pass in the piwik order api to track my orders, I also want to pass a seller id (who is the seller of the product ).
Like I track which my best sold products  , I also want to know which seller generated the most revenue by selling its product.

**Comment by mattab** [comment]
Hello,
For this please to set Custom Variables or Custom dimensions before sending your order. Then you can see sales and other metrics, for each custom value seller id. Hope it helps
