### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by standus** [piwik/piwik#10617]
I installer new version of piwik, but when script sent request, web server log error:
Unknown column 'location_ip_protocol' in 'field list' In query: INSERT INTO piwik_log_visit

**Comment by mattab** [comment]
@standus have you maybe installed some plugins from the Marketplace? If so, please report this bug to the plugin directly

**Comment by standus** [comment]
Yes it is possible. You dont test any plugins to compatibility and guaranty for Piwik quality???

**Comment by mattab** [comment]
We only guarantee the quality and compatibility of our own plugins, published by the Piwik team. Obviously we don't test other plugins as it is up to each developer. You can be useful by reporting the message to the plugin developer directly on their github issue tracker

**Comment by standus** [comment]
But how can I know , which plugin is it? 
Its not good info, that you dont test it.

**Comment by mattab** [comment]
@standus maybe you want to help test all marketplace plugins, and report any issue to us? we would love to get your help, as you think it should be tested, I agree it would be a great idea...

**Comment by mattab** [comment]
>  You are like WordPress = unsecured Plugins = potential security risc = very bad !!!

If you are concerned with this, which I fully understand, then ONLY use plugins created by the Piwik team. We guarantee those. Piwik is  an open platform and our marketplace is open, which is great but obviously has pros/ cons, which you need to deal with according to your needs and situation.

**Comment by standus** [comment]
OK, thank you.
