### ISSUE TITLE
A long goal name will overflow the submenu, maybe instead it could be truncated with an ellipsis and a tooltip showing full-truncated name

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10614]
Reproduce
- Create goal with long name eg `longgoalnamewithoutspacessssss`
- Got: The submenu overflows into the reporting dashboard
- Expected: maybe the long name could be truncated with an ellipsis eg. `longgoalnamewithoutsp...` and show a Tooltip on hover with the full name `longgoalnamewithoutspacessssss`

Screenshot

![goal name](https://cloud.githubusercontent.com/assets/466765/18980425/abd4289e-8730-11e6-961b-f07d37917fad.png)

**Comment by tsteur** [comment]
FYI: This is firefox only

**Comment by tsteur** [comment]
and it is not a regression, so moving out for now
