### ISSUE TITLE
Login dialog warning

### ISSUE THREAD

**Issue by standus** [piwik/piwik#10619]
Why is on login dialog warning message?
Please specify a value for 'idSite'.

**Comment by mattab** [comment]
Which URL do you use?

**Comment by standus** [comment]
Normal website root:
https://mysubdomain.mydomain.com/

**Comment by hpvd** [comment]
same here. Always before login it looks like this:
![2016-10-01_15h09_56](https://cloud.githubusercontent.com/assets/5681880/19014268/2d6ed148-87e9-11e6-9008-157ac86df923.png)

**Comment by hpvd** [comment]
even directly after log out via button, there is a warning (a slightly other one):

![2016-10-01_15h14_23](https://cloud.githubusercontent.com/assets/5681880/19014292/e08368de-87e9-11e6-80fa-ddd33a167f2e.png)

**Comment by mattab** [comment]
I've never seen this one before, maybe it us caused by a plugin from
marketplace. Which third party plugins  do you use? If you temporarily
disable all third party plugins do you still reproduce the issue?

**Comment by hpvd** [comment]
@mattab good guess :-)
it's https://plugins.piwik.org/Chat

after deactivation everything is fine.
Should affect many users since this plugin has 7k+ downloads...

**Comment by mattab** [comment]
@hpvd Does this plugin work btw? we were wondering this recently, and whether it was providing good value. Would love to hear from you!

**Comment by hpvd** [comment]
sorry couldn't give any information on this: after install we decided to use another chat tool (before it was really implemented). And we forgot to deactivate it so it was still there...

**Comment by hpvd** [comment]
was in-between already reported by @standus at plugin site: https://github.com/VincentLahaye/piwik-chat/issues/23

**Comment by hpvd** [comment]
could be closed here

**Comment by mattab** [comment]
Vincent asked us to remove the `Chat` plugin from the Marketplace. so we will remove it... unless someone confirms very soon whether it's working for them

**Comment by standus** [comment]
What it means? It means that Chat is discontinued? Closed development or what?

**Comment by sgiehl** [comment]
this is unrelated to that plugin. Try removing all parameters from your current url and click through to the plugin admin and try it again
