### ISSUE TITLE
Segments created in Piwik 3, appear with creator 'undefined' instead of the username

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10626]
As a result, segments mistakenly appear in the list `Visible to you because you have Super User access:` 

 ![created by undefined](https://cloud.githubusercontent.com/assets/466765/19017225/d595424e-888e-11e6-987f-0819e66c9e4c.png)

Feature was implemented in #9621 #9307

**Comment by sgiehl** [comment]
This works for me.
