### ISSUE TITLE
Consolidate "Mid term" and "Long term" milestone into a new "Backlog / Help needed" milestone

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10632]
I don't really understand anymore why we have two milestones for stuff we won't work on any time soon: Mid term and Long term. Therefore I'd like to suggest to consolidate these two into one new milestone that is more clear that we could maybe call something like `Backlog / Help needed`.

It would be useful because:
- Mid term / Long term distinction is very arbitrary and not real
- We won't work on the Mid term issues in the mid term (whatever it means?). At best we will work on 10-20% of them over the next two years.
- the industry term for issues that are not being worked on now is `Backlog`
- we will need serious external / business help in order to make progress on these issues, so it would make sense to me to call out and add `Help needed` in the milestone title.

If nobody disagrees I'll go ahead and make the change in few days...
- I'll add a label to the issues currently in `Long term` (for example `Long term`...) so that we can still have the distinction that these issues are less important than those without the label, in case we'd like to handle them differently in the future.

As always, any feedback is very welcome! :+1:

**Comment by mattab** [comment]
* [Mid term](https://github.com/piwik/piwik/milestone/20) currently has 316 issues.
* [Long term](https://github.com/piwik/piwik/milestone/40) currently has 754 issues.

**Comment by hpvd** [comment]
good idea :-) With this maybe one can apply a 3-step priority label
- High priority (should be done as fast as possible, but no release version applied yet)
- mid priority
- low priority (should be done sometime)
Would give even more overview/control what should be thought of next...

**Comment by hpvd** [comment]
Some of the "High priority" ones has of course already "major"-label...
Working with" x-priority" wording one easily could identity every label belonging to this group ("priority") of labels.
.

**Comment by mattab** [comment]
Done, new milestone: https://github.com/piwik/piwik/milestone/20 listing 1,099 issues
and a new label for lower priority issues: https://github.com/piwik/piwik/labels/Lower%20priority (used to be "Long term" issues)
