### ISSUE TITLE
On mobile, when a datatable report row is in focus, display the row action icons 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10645]
On mobile, when a datatable report row is in focus, display the row action icons mobile users can enjoy full feature set of piwik

Currently row icons are not displayed when the row is in focus, preventing access on mobile to powerful features like row evolution, overlay, segmented visitor log, etc

![tmp_9265-screenshot_2016-10-03-22-07-52-1151930795](https://cloud.githubusercontent.com/assets/466765/19032498/92b2bc80-89b6-11e6-9fd4-e355b6b4308a.png)

**Comment by tsteur** [comment]
Is this working on Piwik 2?

**Comment by tsteur** [comment]
I checked and it does not work in Piwik 2. I won't be working on this one

**Comment by mattab** [comment]
This was fixed in 3.0.4 :+1:
