### ISSUE TITLE
On mobile, in website selector, display the arrow to the right

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10641]
Currently it's displayed in the right of the selector

![tmp_9265-screenshot_2016-10-03-21-02-56-922162220](https://cloud.githubusercontent.com/assets/466765/19030912/586785fa-89ad-11e6-923c-2812a1f62393.png)

**Comment by mattab** [comment]
Also it would be great for consistency, and usability, to make the whole selector clickable (currently only.the left part till the arrow icon is clickable)

**Comment by tsteur** [comment]
moving this out of b1
