### ISSUE TITLE
SiteSearch reports empty when Action-Segment applied (unexpected behaviour)

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#10674]
The SiteSearch reports do not display values for the keyword / keywords with no results / search category reports when e.g. an actionUrl or pageUrl Segment is applied:

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&segment=pageUrl!@sdvgsdfgdafg#?module=Actions&action=indexSiteSearch&idSite=7&period=day&date=yesterday&segment=pageUrl!@sdvgsdfgdafg

In this example, we segment the reports for "pageURL" does not contain "sdvgsdfgdafg" which should display all reports correctly (with all values shown in the mentioned reports). The same happens, when we segment for the actionUrl.

**Comment by mattab** [comment]
Thanks for the report @peterbo - it's a limitation of how segmentation on actions currently work. it's clear that many users are confused about this, and it should ideally be changed. See discussion in #9796 and many other issues that are kinda duplicate of this.

**Comment by peterbo** [comment]
Thanks @mattab for clarification!
