### ISSUE TITLE
Git workflow for Piwik 3.X and beyond

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10678]
We would like to go back to releasing Piwik versions every month, as it is by far the best release workflow for everyone (release early, release often). In order to make frequent release as painless as possible, we're proposing slight changes from the git workflow we've been using in Piwik 2.X cycle.
### Context

At Piwik we like to:
- release early and often
- write automated tests for most changes 
- keep our builds green (although in practise it has proven difficult)
- keep operational / release overhead as small as possible
### Git workflow in Piwik 3

In order to help with these few points, it would be helpful if:
- we keep our day to day work for Piwik 3.X in the `3.x-dev` branch
- `master` branch is always "Stable" and able to be released at any time
- `master` branch is always green: our thousands of automated tests are all passing
### What needs to be done
- We feel the only way to ensure `master` is always green is to merge `3.x-dev` to `master` only when the develop branch (3.x-dev) is green. Covered in #10677
- We will start releasing Piwik 3.X releases every month on a schedule and will try to stick to it. So if all goes to plan, we will see a monthly release of Piwik 3 independently of how many issues or features were added.

Any feedback / suggestions welcome!

**Comment by tsteur** [comment]
👍

**Comment by mattab** [comment]
We've put this new process into place :+1:
