### ISSUE TITLE
Datebase upgrade from 2.16.2 to 2.16.4 throws notices

### ISSUE THREAD

**Issue by florisluiten** [piwik/piwik#10671]
When upgrading from 2.16.2 to 2.16.4 I get the following notices when upgrading the database by running "core:update".

    WARNING [2016-10-04 07:35:32] (snip)/piwik/core/Updates/2.16.3-b3.php(37): Notice - Undefined variable: timezone - Piwik 2.16.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
    WARNING [2016-10-04 07:35:32] (snip)/piwik/core/Date.php(275): Notice - date_default_timezone_set(): Timezone ID '' is invalid - Piwik 2.16.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
    WARNING [2016-10-04 07:35:32] (snip)/piwik/libs/Zend/Db/Statement/Pdo.php(228): Notice - Array to string conversion - Piwik 2.16.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
    WARNING [2016-10-04 07:35:32] (snip)/piwik/libs/Zend/Db/Statement/Pdo.php(228): Notice - Array to string conversion - Piwik 2.16.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

The upgrade succeeds, I haven't encountered any other issues.

**Comment by florisluiten** [comment]
Sorry, I found out it was already mentioned here https://forum.piwik.org/t/errors-in-update-2-16-4/21196

**Comment by mattab** [comment]
We keep track of bugs here, not in the forum, so it's better to leave it opened.

**Comment by florisluiten** [comment]
Okay Mat, will open this issue again. Thanks!

**Comment by sgiehl** [comment]
Too late, already fixed it :trollface:

**Comment by mattab** [comment]
[Piwik 2.16.5](http://piwik.org/changelog/piwik-2-16-5/) has been released and fixes this issue. In case your [Scheduled reports](https://piwik.org/docs/email-reports/) are not working anymore you may have to re-create them manually, or you can also restore the table `piwik_report` (containing your Scheduled reports definition) from a backup if you have one. We are sorry for any inconvenience caused.

**Comment by florisluiten** [comment]
Thank you @mattab and @sgiehl for your quick response!
