### ISSUE TITLE
/htdocs/analytics/plugins/ScheduledReports/API.php(658): Warning - Invalid argument supplied for foreach() - Piwik 2.16.4

### ISSUE THREAD

**Issue by llsnndlldkm** [piwik/piwik#10679]
I am reporting this error as the nice script requested. I had entered the command:
/htdocs/analytics/console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='https://www.example.com/analytics

**Comment by zero-24** [comment]
can you try: https://github.com/piwik/piwik/compare/master...zero-24:patch-1 it should make sure that this is an array.

The other way arround could be:
https://github.com/piwik/piwik/compare/master...zero-24:patch-2

**Comment by mattab** [comment]
Should be fixed in https://github.com/piwik/piwik/pull/10680

**Comment by mattab** [comment]
Unfortunately you may have to restore the table `piwik_report` from the backup in case your scheduled reports were overwritten wrongly.

**Comment by mattab** [comment]
[Piwik 2.16.5](http://piwik.org/changelog/piwik-2-16-5/) has been released and fixes this issue. In case your [Scheduled reports](https://piwik.org/docs/email-reports/) are not working anymore you may have to re-create them manually, or you can also restore the table `piwik_report` (containing your Scheduled reports definition) from a backup if you have one. We are sorry for any inconvenience caused.
