### ISSUE TITLE
Monthly scheduled reports

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#10689]
Scheduled report fetches data using &period=range&date=last30 instead of fetching data from previous month. Can this be configured somehow or maybe desired behavior would be to "intelligently" choose previous actual month or week?

**Comment by tsteur** [comment]
I don't think it can be configured

**Comment by tsteur** [comment]
Adding label bug to this, haven't checked in the code but sounds buggy

**Comment by mattab** [comment]
If that's the case it's definitely a bug, as the report should include last month report, not last 30 days. @mgonera how did you investigate this issue and found it was using last30 ?

**Comment by mgonera** [comment]
Customer reached out with question on why there is no unique visitors number in monthly report.

After trying to recreate report definition and few other steps, I just checked what is the API request behind "Download" link of the report. It turned out that **period=range&date=last30**.

Obviously when I took the request that returns HTML report and changed period to month and date to specific date within desired month, all of the metrics, along with Unique Visitors number, were returned in the report.

**Comment by mgonera** [comment]
I actually noticed that what is in the Report Download link, will rely on previously chosen UI context. And in this case range/last30 came from the fact, that these were default dashboard settings for particular user. Still I think this is bug, that report with "monthly" parameter can be downloaded for not-month period. Would you say we can expect improvement in this feature? I wonder what is actually being processed into the reports that are automatically sent by archiving process running for example on 1st day of the month. Could you maybe answer on that please?

**Comment by tsteur** [comment]
I had a quick look in the code and there it should actually use the week, month, ... when sending the report. As for the UI the behaviour is expected but could be more clear. That's why there is a date selector above. @mattab I think we can close this one as it seems to work fine?

**Comment by mgonera** [comment]
@tsteur ok, we can investigate it further on our side.
