### ISSUE TITLE
Piwik sends email from localhost instead of fqdn

### ISSUE THREAD

**Issue by SebBoffen** [piwik/piwik#10684]
Piwik sends email from localhost instead of fqdn

Hope someone can help as I do not know what triggers this:
Link in the email:

https://localhost/index.php?module=CoreUpdater&action=newVersionAvailable

formerly this was:

https://fqdn/index.php?module=CoreUpdater&action=newVersionAvailable

I've checked Piwik and the Ubuntu Server installation but I am not finding the reason for this issue, run Piwik for more than a year (with about the same configuration, and a new installation) The rest of the server is running fine apart from this issue. Email dns ftp websites etc. I've tried mail settings in Piwik they did not result in a solution. Network name settings en php settings are the same as the former installation.

**Comment by mattab** [comment]
thanks @SebBoffen for the report. Could you let me know if any of your crontab tasks for Piwik refer to "localhost" at all? What are your "trusted hosts domains" set to, in General Settings of Piwik?

**Comment by SebBoffen** [comment]
Hi I do not have any piwik cronstasks, it seems for one or another reaon piwik prefers localhost over fqdn and I’m not seeing te reason. As there is no host to set nor have I got other issue’s with this server.

 

Met vriendelijke groet / With kind regards,

 

Sebastian Boffen

 

Boffen Systeembeheer
Wijkeroogstraat 156
1951AE Velsen-Noord
Tel. +31 6 42 44 72 12
Email:  <mailto:info@boffensysteembeheer.nl> info@boffensysteembeheer.nl
www:  <http://www.boffensysteembeheer.nl/> www.boffensysteembeheer.nl

 

---------
Disclaimer

 

Dit bericht is alleen bestemd voor de geadresseerden. Aan dit bericht kunnen geen rechten worden ontleend.

 

---------

Disclaimer

 

This transmission is confidential and must not be used or disclosed by anyone other than the intended recipient. Boffen Systeembeheer cannot accept any responsibility for any use or misuse of the transmission by anyone.

 

Van: Matthieu Aubry [mailto:notifications@github.com] 
Verzonden: zaterdag 12 november 2016 11:27
Aan: piwik/piwik
CC: SebBoffen; Mention
Onderwerp: Re: [piwik/piwik] Piwik sends email from localhost instead of fqdn (#10684)

 

thanks @SebBoffen <https://github.com/SebBoffen>  for the report. Could you let me know if any of your crontab tasks for Piwik refer to "localhost" at all? What are your "trusted hosts domains" set to, in General Settings of Piwik?

**Comment by SebBoffen** [comment]
An upgrade to version 3.0 resolved the issue.
