### ISSUE TITLE
Error in database migration from 2.16.3-b2 to  2.16.4.

### ISSUE THREAD

**Issue by k-nut** [piwik/piwik#10699]
When trying to upgrade to the 2.16.4 version from 2.16.3-b2 the following error happens during the migration:

```
Critical Error during the update process:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hour' in 'field list'
```

Rerunning the migration does not mitigate the problem and the page seems to be stuck in the update state now. 

The PHP verison used is 5.4.45
The mysql version is 5.5.52

Let me know if there is any more information that I should provide.

**Comment by hebbet** [comment]
try using 2.16.5

**Comment by k-nut** [comment]
How would I do that? I don't see a way to do it from the GUI as it is stuck in this half updated state now. Should I replace the piwik files on disk?

**Comment by RMastop** [comment]
@k-nut use the Manual Three-Step Update, described here:
http://piwik.org/docs/update/#the-manual-three-step-update

**Comment by k-nut** [comment]
I tried this but still get the same error.
This is what the updater says it will do:
```
Piwik database will be upgraded from version 2.16.3-rc2 to the new version 2.16.5.

The following dimensions will be updated: log_visit.visit_entry_idaction_url.
```

**Comment by k-nut** [comment]
Any suggestions for what else to try/how to get more debug information?

**Comment by mattab** [comment]
@k-nut most likely what is happening is that your mysql server is not finishing to run the SQL query. can you check your mysql error logs for more info? then you can search in our FAQ for a solution to the actual error.

**Comment by mattab** [comment]
@k-nut to fix your issue please create a new column `hour` in the table mentioned in the message. The column has a type of "integer". this should fix your update path hopefully :+1:

**Comment by k-nut** [comment]
@mattab sorry for the many questions but this would be the `log_visit` table then?

**Comment by k-nut** [comment]
Nevermind. I figured out that it is the `reports` table that needs this new column. Thank you for your help @mattab, @hebbet and @RMastop 💐
