### ISSUE TITLE
Installing a plugin from the marketplace does not always activate the plugin and may display "This plugin has not been loaded"

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10695]
Reproduce:
* On Piwik 3.0.0-b1,
* Install the latest ApiGetWithSitesInfo plugin from marketplace
* Got: 
  * red notification `This plugin has not been loaded`
  * the plugin is not activated
* Expected instead:
  * the plugin is downloaded in the background and the page then loads a message with a link or button to activate the plugin

**Comment by tsteur** [comment]
This is actually in Piwik 2 as well

**Comment by mattab** [comment]
Works in 2.17.0-b2, will check again in 3.0.0-b2

**Comment by tsteur** [comment]
This will be fixed in Piwik 3 once we update the Marketplace there. It was broken in 2.x and I fixed it there in the other Marketplace PR
