### ISSUE TITLE
Remove many languages from language selector

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#10709]
It would be nice to have a configuration option to remove unused language from the language selector of the administration interface.

We rarely have to choose from more than 3-4 languages so I suggest something like : 

[General]
show_lang_selector = fr, en, de

And then only show those 3 languages in the menu instead of a cluttered menu with 50 others we never use.

**Comment by mattab** [comment]
Thanks for the suggestion. This could be done easily with a custom plugin :+1:

**Comment by sgiehl** [comment]
Just released a small plugin able to do that. Currently only available for new Piwik 3. Will publish a BC version for Piwik 2 later.

http://plugins.piwik.org/RestrictLanguageSelection?piwikversion=3

**Comment by gaumondp** [comment]
I am speechless @sgiehl  !

Thanks a bunch !

**Comment by tsteur** [comment]
That's great @sgiehl Always good to see when features are built on top of Piwik in plugins 👍 

Can we close the issue?

**Comment by sgiehl** [comment]
Already closed it ;)

**Comment by mattab** [comment]
nicely done :+1:
