### ISSUE TITLE
Don't see any events being tracked when I'm using the API 

### ISSUE THREAD

**Issue by lipis** [piwik/piwik#10707]
So according to the [API docs](http://developer.piwik.org/api-reference/tracking-api) for tracking events I'm doing the following in my Python backend (using [Flask](http://flask.pocoo.org/) and [Requests](http://docs.python-requests.org/en/master/)):

```python
def track_event_to_piwik(category, action, name, value):
  return requests.post('https://%s/piwik.php' % PIWIK_HOSTNAME, data={
    'idsite': PIWIK_ID,
    'req': 1,
    'url': flask.request.url,
    'rand': random.random(),
    'apiv': 1,
    'e_c': category,
    'e_a': action,
    'e_n': name,
    'e_v': value,
  }).status_code
```

But I don't see anything in my dashboards.. only the events that are being tracked using [JavaScript](http://piwik.org/docs/event-tracking/#javascript-trackevent)..

Is there anything that I'm doing wrong?! Yes I'm getting the `200 OK` from the above request..

**Comment by tsteur** [comment]
Can you try to rename `req` => `rec` ?

**Comment by lipis** [comment]
There is always this one thing!! :D I'll close it for now until _further_ investigation..

**Comment by tsteur** [comment]
Sweet. Feel free to reopen in case it doesn't help
