### ISSUE TITLE
captcha on piwik.org not displayed

### ISSUE THREAD

**Issue by clor09** [piwik/piwik#10729]
Not about coding , but the 'Contact the team' way on the website does not work, there is really no "Captcha" thing... The world map used in the "Real-time Map" is wrong, you may correct it~

**Comment by mattab** [comment]
Hi @clor09 
Could you please post a screenshot showing the missing captcha on the website? it seems to be working for us, but maybe there is some issue if you use an adblocker or so.

**Comment by clor09** [comment]
here it is:
![screenshot_20161012_204825](https://cloud.githubusercontent.com/assets/20962135/19310675/dc8082f8-90bd-11e6-912b-2cf3b6f2176a.png)
So, what about the second question, world map~

**Comment by clouseau** [comment]
The captcha seems to require Javascript.

**Comment by clor09** [comment]
@clouseau Yes, it may need. But i didnt disable my js engine, so maybe it's another issue ^_^, ( the sidebar left also need js to show some effect ^_^ )

**Comment by p-blomberg** [comment]
The captcha works fine for me, on Firefox 49 with Adblock Plus active and NoScript installed but allowing all domains. The page includes scripts from google.com and gstatic.com.

@clor09: I suggest you open a new issue for the world map problem. "other mistakes" is not a good issue name. If you open separate issues with good names and descriptions, it is more likely that they will get resolved.

**Comment by clor09** [comment]
@p-blomberg  I have loaded all scripts,  so strange.. And thanks for your suggestion, i will open a new issue for the world map problem

**Comment by mattab** [comment]
@clor09 what browser did you use when not seeing captch? we'll try to reproduce

**Comment by clor09** [comment]
@mattab Firefox,  with the newest version.

**Comment by clor09** [comment]
@mattab  After a completely reinstall, things comes to be fine. The issue may be caused by my broken system.
