### ISSUE TITLE
Dose piwik re-process on statistics must be set --force-all-periods parameters?

### ISSUE THREAD

**Issue by fengzhibin** [piwik/piwik#10726]
I look at piwik's FAQ on the reconstruction statistics. 
This is the URL address [http://piwik.org/faq/how-to/#faq_59](url)

My piwik statistics in September 2016, there have been problems, lost the monthly statistics. 
Now time is October 12, 2016, I am ready to rebuild the September statistics.

I have deleted the data table piwik_archive_numeric_2016_09 and piwik_archive_blob_2016_09.And then 
execute the following command in the piwik project.
**php console core:archive --force-all-websites --force-all-periods=3715200 --force-date-range=2016-09-01,2016-09-30 --php-cli-options="-d memory_limit=6G"**

I find that when I do not enter the --force-all-periods parameter, the command will be skipped.Only if I fill in the parameter --force-all-periods can I start to re-process the statistics in September.

The following command makes me wonder about the definition of the parameter --force-all-periods
**php console help core:archive**

Now even if it has been re-process statistics in September, but I am to the accuracy of the data to doubt.I fear that the October data will also statistics in September.

**Comment by mattab** [comment]
Hi @fengzhibin 
yes the parameter is necessary for now. the accuracy of the data should be valid independantly of the values of the parameters (as long as you don't see "no data")
