### ISSUE TITLE
Is there a way to create a goal programmatically?

### ISSUE THREAD

**Issue by beatelite** [piwik/piwik#10724]
I saw that you have Dimension.addDimensions to be able to create dimensions but what about goals?

I have sites that all need the same dimensions and goals set up. It's a pain to copy and paste. Is there a way (via hook) to do this programmatically?

**Comment by sgiehl** [comment]
You could use the Goals API. See http://developer.piwik.org/api-reference/reporting-api#Goals

**Comment by beatelite** [comment]
@sgiehl Excellent. Not sure how missed that! Thank you!
