### ISSUE TITLE
keep choosen period ond segment when going to settings and back

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10723]
Selecting in dashboard a period e.g. "year 2016" going to settings
go back to dashboard: chosen period is changed to day 11/10/2016 (today).

This may produce
- some extra work (one hast to change it back..)
- some extra load on server
  ...

Same happens for chosen segment: after going to settings this is reset to "all visits"

Seen in 3.0b1

**Comment by mattab** [comment]
Thanks for the report, but it works like this by design: when going back to Reporting UI we default to the user preference date, selected in Personal settings.
