### ISSUE TITLE
Update from 2.x to 3.0.0-b1 failed: ".form-description is undefined"

### ISSUE THREAD

**Issue by jangrewe** [piwik/piwik#10738]
I just enabled the beta release channel on my instance and during/after the update i'm receiving this error:

```
An exception has been thrown during the rendering of a template (".form-description is undefined: failed at `.form-description;` line: 6182") in "@CoreUpdater/runUpdaterAndExit_welcome.twig" at line 8.
```
Can't do much now, that error is always shown.

**Comment by jangrewe** [comment]
Okay, it was incompatible plugins. Must have been one of:

Bandwidth
InterSites
LiveTab
PerformanceMonitor
ReferrersManager
TreemapVisualization

**Comment by Findus23** [comment]
It seems like it was *InterSites* for me.

**Comment by mattab** [comment]
Created issue on the InterSites repo to let the devs know https://github.com/PiwikPRO/plugin-InterSites/issues/24

**Comment by mattab** [comment]
### Solution to this problem is to delete the files in `piwik/plugins/InterSites/*`
