### ISSUE TITLE
WARNING: Sparklines.php(62) - Piwik 3.0.0-b1

### ISSUE THREAD

**Issue by acs-ferreira** [piwik/piwik#10731]
`WARNING: /plugins/CoreVisualizations/Visualizations/Sparklines.php(62): Warning - array_merge(): Argument #1 is not an array - Piwik 3.0.0-b1`

PHP 7.0.11

**Comment by sgiehl** [comment]
would you mind provding the url where that occurs? Or is it within a specific dashboard widget?

**Comment by acs-ferreira** [comment]
Main dashboard
`index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1`

**Comment by Firesphere** [comment]
Having the same issue. Any dashboard page gives this warning once or twice.

**Comment by mattab** [comment]
Hi guys, we have tried to fix the issue in https://github.com/piwik/piwik/commit/d2517c03375edcedc9948bf7cbdf64b14502f185 - could you please try this patch or directly 3.0.0-b2 which will be released in a few minutes? If the bug is not fixed, let us know

**Comment by Firesphere** [comment]
Late to the party. I can confirm it's not showing anymore as well.
