### ISSUE TITLE
Add header X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by nico3333fr** [piwik/piwik#10734]
Hi there,

first of all, thanks for your work, it is the first time I self-host a Piwik for a website, it works very well. 👍 

I've tested this website with Dareboost service and I got this message: https://www.dareboost.com/en/report/57ff4d3e0cf296dad130c6db

On this page, you should configure the following resource, that risks being misinterpreted:
van11y.net/piwik/piwik.php?action_name=Van11y%3A[...]1&res=1920x3000>_ms=90

I was able to fix it easily by adding a :
```
header('X-Content-Type-Options: nosniff');
```
at the top of piwik.php. Might not be perfect, but does the job.

Each time Piwik updates itself, this modification is removed. Could it be possible to fix it definitively by this method or another?

Kind regards,
Nicolas

**Comment by p-blomberg** [comment]
You can add the header in your web server configuration instead of doing it in piwik. 
If you are using apache, check out [the Header directive](http://httpd.apache.org/docs/current/mod/mod_headers.html#header).

**Comment by nico3333fr** [comment]
Sorry, I though it was parametrable in Piwik.
