### ISSUE TITLE
action/pages: unit of "average time on page" => minutes

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#10748]
Since "average time" on page should hardly be more than several minutes, maybe on should think of turning the unit of this column from "hh:mm:ss" to "minutes" - would be far better to read/compare.

This probably the same reason why one do not show "generation time" in hh:mm:ss...

this is how it looks like at the moment:
![2016-10-17_12h13_34](https://cloud.githubusercontent.com/assets/5681880/19434168/4b4f4968-9464-11e6-8153-f406028feef8.png)

**Comment by mattab** [comment]
Thanks for suggestion, in this case we display in hh:mm:ss format on purpose as it makes comparing value easier while scanning. (All values have the same width with this format as opposed to other format)
