### ISSUE TITLE
 The world map used in "Real-time Map" is wrong

### ISSUE THREAD

**Issue by clor09** [piwik/piwik#10741]
In the piwik web application, the "Real-time Map" part, the world map is wrong at the china part. You may correct it, please.

**Comment by mattab** [comment]
Duplicates https://github.com/piwik/piwik/issues/6006

**Comment by clor09** [comment]
@mattab  I dont think this issue duplicates to the the one that you point out, that is about tibet, and this one is about 'xizang' which my fault that i didnt descript my issue clearly, and more detail ,  i wont say that you have prejudice against china, but i think if somebody who want to talk about something in a very public place which may impress many people should do a research on the reality. And yes , i agree with you that internet is internet, it's not a country, the network unifies us and the most important 'freedom', but this is not the point.

Hope you could come and see and find more about the reality and the history. 

About the 'oppression': i dont know where you find about the thousands of death and the infomation about Dalai, but do you really think that "a cat with dog's clothes on is a dog?", not all the articles on newspapers or the papers that the government give out are the truth, like the reason of the war happening in Iraq, and the 'reason' things seems to be everywhere... I think what we could hold is justice but should based on truth including the differences between our culture.

Again, hope you could come and see and you will be very welcome~

**Comment by mattab** [comment]
Hi @clor09  - can you create a new issue for the "xiZang" region issue? it's important we have separate issues for each suggestion / request

**Comment by clor09** [comment]
Hi @mattab .
I dont think history can be rewritten, truth just be there and could never be changed. And why the 'few tibetans' are right but china not? People can have their own opinion freely, BUT :
The 'few tibetans' could be india and this situation has its own reason including the ‘territorial dispute’ and other conflict of interest between India and China, and more( arguments between America/Europe/Russia/China/The Middle East/etc..   The east and the west, The culture differences.), we cant just listen what they told, but why they told so and why is the why.  It can be really hard to find out all of them, but,  if m right, we cant just deside something simply. and If it's still a question, leave it with a "'not clear' tag" is more appropriate i think.
The truth never comes late.
I will open another issue for the new suggestion.

**Comment by mattab** [comment]
> I dont think history can be rewritten, truth just be there and could never be changed. 

I hope you are not serious. If you are, i'm afraid you have a lot to learn still about the power of governments and how EASY it is to rewrite history and to deceive un-informed humans. It was so easy to be un-informed before the global information age and how the information is now more easily available to everyone via books and more. A beautiful and very famous book (of english litterature) very well explains, how rewriting history can be done, in a most "extreme" way. It's called 1984, learn more here: https://www.amazon.com/1984-Signet-Classics-George-Orwell/dp/0451524934/ - I recommend you check out this book and learn about other cases where history has been rewritten very favorably in favor of the oppressors. Think for example "Columbus" who "discovered america" which is very similar case as China "helping Tibet get into the modern age". so many cases of this over the last millenia. 

But as it's an issue tracker for an open source analytics project, I do not wish to discuss this further here. Thanks

**Comment by clor09** [comment]
you may misunderstand my post, i just mean things that happened just happened there, nobody could change it no matter how the (history) book was written.
thanks for your recommandation of the book.
