### ISSUE TITLE
Upgrading to 2.16.5 is breaking the ScheduledReports

### ISSUE THREAD

**Issue by provirus** [piwik/piwik#10754]
Hi,

after the update, in the table "piwik_report", both "reports" and "parameters" are changed to "Array", which is invalid, so I am no more receiving email reports.

After resaving a report, I can see an actual array of values for both columns

**Comment by mattab** [comment]
Hi @provirus - maybe you updated to 2.16.3 or 2.16.4? These versions had a bug which broke the scheduled reports, which we fixed after 24 hours. See: #10682
