### ISSUE TITLE
Let's not use Gender (for example "his") in the product User Interface

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10753]
It would be very valuable for a good user experience, not to use Gender terms in the Piwik User Interface. In particular, not use "his" or "her" or other similar not-gender-neutral terms. The sentences can often be rewritten so we don't need to use such term. 

If someone wants to help with this project we would greatly appreciate!

**Comment by x3ro** [comment]
I'd like to help with this. Is there anything I should be aware of before starting?

**Comment by mattab** [comment]
Hi @x3ro Great to hear.  feel free to get started and submit PR and we can go from there :+1:

**Comment by mattab** [comment]
Some work was done in #10982 - wondering if there are more strings left of if this ticket can be closed?

**Comment by mattab** [comment]
Did another search and could only find these few remaining ones  #11216
