### ISSUE TITLE
Can piwik.js be hosted on a server different than the piwik installation?

### ISSUE THREAD

**Issue by michael4john** [piwik/piwik#10760]
Hi there,

We're interested in whether or not piwik.js can be hosted on a server (actually this is the one hosting the websites we are tracking with Piwik) that is different than the one where the piwik was installed, and that is not so responsive sometimes when the piwik.js needs to be loaded on a client.

For your information, the website we are tracking with Piwik has moderate traffic. And the version of piwik we are using now is 2.16.5.

I did do searches on lots of place, but did not get a definite answer. Among the pages I looked at is: http://piwik.org/faq/troubleshooting/faq_58/. The information provided in the 'Local copy of piwik.js outdated' list item does indicate that a local copy is doable, but is not recommended.

Anyone here has already tried that?

Thanks!

**Comment by mattab** [comment]
Hello

>  The information provided in the 'Local copy of piwik.js outdated' list item does indicate that a local copy is doable, but is not recommended.

This is the current state of our recommendations: you can do it, but we highly recommend against it (because you will forget to update the piwik.js when upgrading piwik and this will cause bugs).
