### ISSUE TITLE
LanguagesManagerTest::testGetTranslationsForLanguages test sometimes fail with " Exception: unable to save empty or invalid translations"

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10774]
this translation file https://github.com/piwik/piwik/commit/da063f9ae60bbd9c729083cf970d69e2b628610d (before it was deleted) 

caused this build job to fail: https://travis-ci.org/piwik/piwik/jobs/169435535

with error
```
1) Piwik\Plugins\LanguagesManager\Test\Integration\LanguagesManagerTest::testGetTranslationsForLanguages with data set #1288 ('hr', 'CorePluginsAdmin')

Exception: unable to save empty or invalid translations

/home/travis/build/piwik/piwik/plugins/LanguagesManager/TranslationWriter/Writer.php:268

/home/travis/build/piwik/piwik/plugins/LanguagesManager/Test/Integration/LanguagesManagerTest.php:99


```

Thoughts?

**Comment by sgiehl** [comment]
Without having a closer look: maybe the current translation file only
contains some strings that have been removed from the english one. The test
tries to clean the file and thus gets an emptry translation list.

Will have a closer look when I'm back home

**Comment by sgiehl** [comment]
Had a look right now. Seems to be exactly what I supposed. The file would have been empty after clearing it. We could catch that exception in the tests and output a message that the file might need to be removed?

**Comment by sgiehl** [comment]
In the future those tests will now also be skipped and a proper message will be given
