### ISSUE TITLE
Translate not working for plugins in 3.x

### ISSUE THREAD

**Issue by joubertredrat** [piwik/piwik#10776]
Hi guys,
I'm updating my plugin for 3.x version but translate isn't working. Flag counter have same issue, because translate not working, their settings doesn't appear.

https://github.com/sgiehl/piwik-plugin-FlagCounter/blob/3.x-dev/SystemSettings.php#L38

**Comment by sgiehl** [comment]
Maybe you are looking at the wrong place within Piwik. If you convert your Settings to SystemSettings, the options will appear under the general settings within Piwik. The "settings" link within the plugin list should link to there.
