### ISSUE TITLE
 Script not found or unable to stat: /usr/local/cpanel/cgi-sys/plugins & index.php error

### ISSUE THREAD

**Issue by ashiquen** [piwik/piwik#10770]
Hi,

i'm installed piwik and 300+ websites added piwik. But piwik not start tracking. All sites 0 stats.

Cpanel error log :
script not found or unable to stat: /usr/local/cpanel/cgi-sys/plugins, referer: http://sitename.com/index.php?module=MultiSites&action=index&idSite=1&period=day&date=today

script not found or unable to stat: /usr/local/cpanel/cgi-sys/index.php, referer: http://sitename.com/index.php?module=MultiSites&action=index&idSite=1&period=day&date=today

help me pls.
Thanks

**Comment by mattab** [comment]
Hello @ashiquen 
please check: https://piwik.org/faq/troubleshooting/faq_58/
