### ISSUE TITLE
Create 20 new websites from command line, and get tracking codes

### ISSUE THREAD

**Issue by josephernest** [piwik/piwik#10780]
I'd like to add 20 new websites to Piwik, from command line (instead of GUI, that would be too long), and get automatically the JS tracking codes (or even PHP tracking code if PHP is possible with Piwik?) as a list exported to a file.

How is this possible ?

**Comment by sgiehl** [comment]
You can use the SitesManager API: https://developer.piwik.org/api-reference/reporting-api#SitesManager
It has methods for adding new sites and for getting the JS tracking code.
