### ISSUE TITLE
No entry or class found for 'marketplacePiwikVersion'

### ISSUE THREAD

**Issue by dessant** [piwik/piwik#10781]
After updating from 2.16.2 to 2.16.5 I get this error when attempting to access the marketplace.

**Comment by tsteur** [comment]
It looks like this file was not written during the update: https://github.com/piwik/piwik/blob/2.16.5/plugins/CorePluginsAdmin/config/config.php 

To solve this create a file `plugins/CorePluginsAdmin/config/config.php` using content of https://raw.githubusercontent.com/piwik/piwik/2.16.5/plugins/CorePluginsAdmin/config/config.php

**Comment by dessant** [comment]
The module is there, with the same content.

**Comment by tsteur** [comment]
Does it still not work? I will reopen the issue. 

What's your PHP version and operating system?

I'd recommend to execute the update again, but this time manually see http://piwik.org/docs/update/#the-manual-three-step-update . Important: backup your `config/config.ini.php` before doing so

**Comment by dessant** [comment]
I'm using the docker image from https://github.com/piwik/docker-piwik.

The update consisted of changing the image version in my Dockerfile and recreating the container, the database is in a separate data volume.
On first visit after the update there was a message about existing tables and I opted to use the existing ones. These steps worked without issues for the last couple of updates.

I  have called `console core:update`, it says everything is already up to date.

I'll try reproducing with a new container *and* database, is `marketplacePiwikVersion` supposed to be present somewhere as a db entry, or only in the php code?

**Comment by tsteur** [comment]
It is supposed to be only in the PHP code

**Comment by dessant** [comment]
It turns out CustomDimensions was listed in config without really being activated, after sorting out the config and activating the plugin, the issue disappeared.

**Comment by tsteur** [comment]
Awesome, glad to hear this
