### ISSUE TITLE
ScheduledReports not removing/unlinking reports

### ISSUE THREAD

**Issue by MikeN123** [piwik/piwik#10788]
For some reason, ScheduledReports is not removing the generated reports from disk after sending them. On a relatively low-volume server this already gives us a `tmp/assets` dir of more than 1 GB, with 2500 reports.

Any specific reason for this?

The unlink should be here: https://github.com/piwik/piwik/blob/3.x-dev/plugins/ScheduledReports/API.php#L615
But that was removed here, without clear commit message: https://github.com/piwik/piwik/commit/740316a0563a285fbca2eccbab4f137e3fd3c88f#diff-e909e6365fce91bbdff80062f4b5fbc7L560

**Comment by tsteur** [comment]
@mattab do you remember why this was removed? Looks like a bug to me

**Comment by mattab** [comment]
It is a bug, the reports should be deleted after they were sent.
