### ISSUE TITLE
Visitor log very slow and crashes (Piwik 2.16.5)

### ISSUE THREAD

**Issue by dejwsz** [piwik/piwik#10784]
In version 2.16.5 of Piwik I try to get 'Visitor log' through web interface and I'm getting: "Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance. ". 
Looks like the processing of quite a large data needs time - isn't it paged or something? I have live reporting turned off and cron based auto-archival enabled.

**Comment by mattab** [comment]
Can you try this: http://piwik.org/faq/troubleshooting/faq_21433/

**Comment by dejwsz** [comment]
Thanks, it works now after I applied this. So the problem and the cause is known. Will it be fixed in next releases?

**Comment by gaumondp** [comment]
AFAIK @dejwsz it's not an issue in itself but having to use an under the hood solution (SQL queries) is an interface issue...

So I created  #10795 (Add buttons to reset user's visualisation for Admins and users) with 3 options.

Hope it helps.

**Comment by dejwsz** [comment]
OK thanks
