### ISSUE TITLE
Track the vidoe websites

### ISSUE THREAD

**Issue by gkannan21** [piwik/piwik#10786]
Hi,
iam new to piwik, we have video sharing site like youtube, i need to track those videos from piwik.
How to do that,any plugins available, orelse how to do that.
my requirements is ,
1.need to track each and every videos.
2.who played that videos
3.track the play,pause,skip click also
4.how many times and minutes watch the video

Please help me to solve this issue.
Thanks
KannanG

**Comment by fvdm** [comment]
> 3.track the play,pause,skip click also
> 4.how many times and minutes watch the video

You can send events to Piwik for YouTube player events.

https://developers.google.com/youtube/iframe_api_reference#Getting_Started
https://piwik.org/docs/event-tracking/

Something like this:

```js
var player;

function videoStateChange (event) {
  var state;
  var videoId = player.getVideoData()['video_id'];
  var seconds = Math.round (player.getCurrentTime());

  switch (event.data) {
    case -1: state = 'Unstarted'; break;
    case 0: state = 'Ended'; break;
    case 1: state = 'Playing'; break;
    case 2: state = 'Paused'; break;
    case 3: state = 'Buffering'; break;
    case 4: state = 'Cued'; break;
  }

  // Replace `console.log` with `_paq.push` to actually send to Piwik
  if (state === 'Paused') {      
    console.log (['trackEvent', 'Video', state, videoId, seconds]);
  } else {
    console.log (['trackEvent', 'Video', state, videoId]);
  }
}

function onYouTubeIframeAPIReady() {
  player = new YT.Player ('player', {
    height: '390',
    width: '640',
    videoId: 'M7lc1UVf-VE',
    events: {
      'onStateChange': videoStateChange
    }
  });
}
```

**Comment by tsteur** [comment]
@gkannan21 have a look at http://www.media-analytics.net/ . It is very feature rich and gives lots of insights into video (and audio) analytics. A full list of features is mentioned on our Marketplace https://plugins.piwik.org/MediaAnalytics . The points you mentioned will be fulfilled by that plugin.
