### ISSUE TITLE
2.16.5 -> 2.17.0 auto-upgrade issue

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#10798]
Never had issues with auto-upgrades so far, but this was generated this time:

> PHP message: PHP Fatal error:  Class 'Composer\\Semver\\VersionParser' not found in /.../piwik/core/Plugin/Dependency.php on line 77, referer: http://.../piwik/index.php?module=CoreUpdater&action=newVersionAvailable

It is (was) vanilla 2.16.5 version, no custom modifications etc.

Otherwise, seems to be working fine:

**v 2.16.5** (before upgrade) status:

> Diagnostic > System Check = Huzzah!

**v 2.17.0** (after auto-upgrade) status:

> Diagnostic > System Check = Huzzah!

**Comment by dev-101** [comment]
Noticed that GitHub's formatted quotes have removed double slashes \\ in the path

`Composer\\Semver\\VersionParser`

Maybe that's the problem.

**Comment by dev-101** [comment]
Just upgraded another independent installation on the same server, went all fine. Not really sure what has happened here.

**Comment by mattab** [comment]
I suppose you are [deploying Piwik from Git](http://piwik.org/faq/how-to-install/faq_18271/) in which case please follow instructions in the FAQ post-update: ` Upgrade the libraries in case there is any to be upgraded`

**Comment by dev-101** [comment]
Hi Mat,
as far as I can remember, it wasn't installed via git, but from .zip archive at official download page.

As posted above, system check before and after was fine.

**Comment by neralex** [comment]
Exactly the same issue here with the same version as pointed above.
