### ISSUE TITLE
Autoarchiving error

### ISSUE THREAD

**Issue by milexjaro** [piwik/piwik#10790]
Hi, recently, after I migrated Piwik database, and calling an API, I got this following error: 

![abeae3d2-ae92-461f-8020-150576d0df7d](https://cloud.githubusercontent.com/assets/11173209/19715903/b2c5c5f2-9b82-11e6-9a4d-b48d5ec42351.jpg)

but if the parameter "trigger=archivephp" is removed, the API works fine, how do I deal with this issue? Is there any corruptions happened during auto-archiving? Thanks

**Comment by tsteur** [comment]
Do you have any 3rd party plugins installed? Or is it maybe possible that the "Events" plugin is disabled? You can check in "Administration => Plugins"

**Comment by milexjaro** [comment]
"Events" plugin is activated, and yup, I have 3rd party plugins: bottracker, advancecampaignreporting, and referrersmanager

**Comment by tsteur** [comment]
Do you maybe see any errors in the webserver (apache / nginx )log if you have access to these? Maybe try to disable the other plugins and try to re-run it. Maybe it works then? Afterwards you can enable it again. Just to make sure it's not related to any of these plugins

**Comment by milexjaro** [comment]
No errors were found in the log, And I have disabled the plugin, re-ran the archives, and still have the same error. So it's not related to any of these plugins I think.

**Comment by tsteur** [comment]
Can you maybe try to update the file `plugins/Actions/Archiver.php` like this: 

https://github.com/piwik/piwik/compare/2.x-dev...10790?quick_pull=1

It may help

**Comment by milexjaro** [comment]
Thanks, I have done your suggestion but unfortunately, it didn't help

**Comment by milexjaro** [comment]
So, I did the migration on 25th October 2016, and the archiving has gone wrong, if I requested the API.get method with archivephp trigger between 26th October 2016 till now, the log_link_visit_action.idaction_event_category is not detected even though it has occurred in the database

![pasted image at 2016_10_31 02_21 pm](https://cloud.githubusercontent.com/assets/11173209/19848122/ee6de842-9f7d-11e6-8512-81acddb9092f.png)

![pasted image at 2016_10_31 03_21 pm](https://cloud.githubusercontent.com/assets/11173209/19848132/fc5cdce2-9f7d-11e6-9301-8c1f191aab58.png)

and when I requested between 25th October 2016 until now, it gave a different error like this

![pasted image at 2016_10_31 02_19 pm](https://cloud.githubusercontent.com/assets/11173209/19848158/2a413eb4-9f7e-11e6-9c7c-97b8ef5637f2.png)

**Comment by tsteur** [comment]
@milexjaro can you undo the change again? The query was wrong and falsely reported the column is missing. 

I'm not really sure what the error could be and it's hard to guess. Is it maybe possible to get access to your server including database?

**Comment by mattab** [comment]
@milexjaro is the plugin `Events` activated in your piwik?

**Comment by tsteur** [comment]
I asked this already in first comment ;)

**Comment by milexjaro** [comment]
Apparently I've tried to undo the change again, and an API call from 26th October now gives the same error like from 25th October.

Sure, I will make an identical sandbox, and will notify you if the sandbox is ready, thanks

**Comment by milexjaro** [comment]
Update: after I've tried to undo the change again, the archiving went well for 'day' period, other than that (week, month, year) didn't work at all, still have error action '11' not found.

**Comment by tsteur** [comment]
In this case you might need to invalidate the reports for the days you experience this error and then maybe try again http://piwik.org/faq/how-to/faq_155/  The FAQ might help to invalidate reports. Otherwise a sandbox to test would be great

**Comment by mattab** [comment]
see https://github.com/piwik/piwik/issues/11623
