### ISSUE TITLE
Piwik Update 2.17.0 has const VERSION = '2.16.5'

### ISSUE THREAD

**Issue by l0wskilled** [piwik/piwik#10793]
Piwik Update 2.17.0 has `const VERSION = '2.16.5'` in core/Version.php

**Comment by larshaendler** [comment]
I have the same issue. When I update to 2.17 every look as if it was successful but it clearly is not. But upon checking the administration menu it says that I have to upgrade PHP to 5.5.9 and therefore updates are not available.

**Comment by l0wskilled** [comment]
@larshaendler That youre using an unsupported php version is another problem.

Oh sorry, the problem is that the piwik update leads to "https://builds.piwik.org/piwik.zip?cb=2.17.0" which gives the 2.16.5 version not the 2.17.0.

**Comment by mattab** [comment]
Thanks for the report. There was a little misconfiguration in the build script which was fixed a few hours after the release, so now everyone should see 2.17.0 (fix commit: https://github.com/piwik/piwik-package/commit/5f4681d9f971b43f20a46474098e59c99d8e1203 )
