### ISSUE TITLE
All test/UI screenshots are in the git repository

### ISSUE THREAD

**Issue by jurgenhaas** [piwik/piwik#10802]
Looks like that happened by mistake and cloning the repository now takes ages. Reading the guidelines I thought the screenshots shot be stored at a different place.

**Comment by sgiehl** [comment]
We used to store the screenshots in a seprate repo. But the screenshots are now stored within this repo using Git LFS

**Comment by tsteur** [comment]
@jurgenhaas which guidelines are you referring to? We should definitely update the guide. 

@sgiehl is there maybe a way to fetch / clone the repository and ignoring all images in git lfs? Maybe we could document this as well. May be useful eg here: http://piwik.org/faq/how-to-install/faq_18271/

**Comment by sgiehl** [comment]
See https://github.com/github/git-lfs/issues/720
Haven't tried that, but might be an option

**Comment by tsteur** [comment]
Here is an interesting performance comparison: https://github.com/github/git-lfs/issues/931#issuecomment-172608754 I will give them a try and meanwhile reopen the issue

**Comment by tsteur** [comment]
They all took about the same time for me and I think we could recommend any of them.

@jurgenhaas can you try if `git clone --config filter.lfs.smudge=true https://github.com/piwik/piwik.git`  is faster for you? Or alternatively `GIT_LFS_SKIP_SMUDGE=1 git clone  https://github.com/piwik/piwik.git` ?

**Comment by jurgenhaas** [comment]
@tsteur I've found the mention about screenshot storage at https://github.com/piwik/piwik/tree/3.x-dev/tests#screenshot-tests-build-artifacts

I will test the various clone options right now and will report back shortly.

**Comment by jurgenhaas** [comment]
@tsteur The filter config option is working well, it brings back the previous performance and the good thing is that this config is persistent because it is written to `.git/config`. All the screenshots are zero-length files and the only small downside is that the git status is dirty.

If someone uses this as a deployment strategy, the command should look like this:

```
git clone -b 2.17.0 --recurse-submodules --config filter.lfs.smudge=true https://github.com/piwik/piwik.git
```

**Comment by tsteur** [comment]
@jurgenhaas the link you mentioned references actually generated screenshots during the test runs but not expected screenshots that are already in the repository. 

Thank you for your test and feedback 👍  I have updated https://piwik.org/faq/how-to-install/faq_18271/
