### ISSUE TITLE
Would like a report with "visits" per local time (hour) per day of week.

### ISSUE THREAD

**Issue by sggcouronne** [piwik/piwik#10803]
Hi,

I'm using Piwik 2.16.3. 

I would like to know when there is the least visit in my website tracker during the week, during a period of time.

I setted the period to year (I don't have a lot of data, less than 50 visits/day). 
When I go to Visitors > Times, I can see two reports :
- visits / local time (hour)
- visits / day of week

With those reports, I determined that Monday is with the least visits, and 1pm visits. However, I would like to be sure that Monday at 1 pm is with the least visits (Monday could be the least, but at 8 am, not 1 pm). 

I would like to get an report  for :
-  visits / hour / day of week

For this, creating a custom report is the best solution, based on dayOfWeekFromDate and InformationPerLocalTime or not ? Is there an official/third-party plugin solution ?

Here some tickets related :
https://github.com/piwik/piwik/issues/7498

Thank you for your support.

**Comment by mattab** [comment]
Hello, correct one can create a custom report and for now it is the best way to solve it. The doc we have can be found on developer.piwik.org for example : http://developer.piwik.org/guides/custom-reports

 In the future hopefully we will have true Custom Reports (using drag and drop interface).
