### ISSUE TITLE
CRON Reports PHP Fatal Error Tasks.php on line 17

### ISSUE THREAD

**Issue by trec-r** [piwik/piwik#10805]
After updating to 2.17 I get the following on every cron run.

`PHP Fatal error:  Call to undefined method Piwik\Plugins\CorePluginsAdmin\CorePluginsAdmin::isMarketplaceEnabled() in /home/account/public_html/piwik/plugins/CorePluginsAdmin/Tasks.php on line 17`

**Comment by tsteur** [comment]
@trec-r the file `/home/account/public_html/piwik/plugins/CorePluginsAdmin/Tasks.php` should have been deleted during the update. From which Piwik version did you update? 

You can fix the issue by removing the file, eg on Linux via `rm /home/account/public_html/piwik/plugins/CorePluginsAdmin/Tasks.php`. It may be good to also clear your caches afterwards eg on linux via 

```bash
rm -rf /home/account/public_html/piwik/tmp/cache/*
```

**Comment by trec-r** [comment]
The fix seems to have worked. Upgraded from 2.16.5.
