### ISSUE TITLE
In all emails, show links to Piwik as HTTPS when using force_ssl=1 

### ISSUE THREAD

**Issue by blu-IT** [piwik/piwik#10814]
Hello,

I would appreciate very much, when the automatic e-mail notification for piwik (or plugin) updates would countain the links starting with https:// for secure connections to the host.

My notification looks like this
`http://my.piwik.install/index.php?module=CoreUpdater&action=newVersionAvailable `

I wolud like to get it like this:
`https://my.piwik.install/index.php?module=CoreUpdater&action=newVersionAvailable `

Is it possible?

Thanks!

Regards,
Ivan

**Comment by 22h** [comment]
I have search for wrong protocol using in mails, but all of them are correct.
Only a handful links to piwik.org are with http, but i think this is ok, because piwik.org have an redirect to https.

**Comment by 22h** [comment]
Sorry guys, but as I mentioned before, the ticket can be closed because the problem has already been fixed.
