### ISSUE TITLE
Piwik month statistics requires a lot of memory?

### ISSUE THREAD

**Issue by fengzhibin** [piwik/piwik#10820]
![qq 20161101174726](https://cloud.githubusercontent.com/assets/12097229/19885765/4edc95b0-a05b-11e6-8f26-eb01e0badae2.png)

I saw a very slow SQL through show processlist mysql. Seems to be piwik's monthly statistics sql. The execution of more than 19 hours. And our MySQL server only 1G memory.

**Comment by mattab** [comment]
This particular query is caused by the Unique Visitors and Unique Users metrics. you can disable it for your  Piwik (for all periods) as documented in: http://piwik.org/faq/how-to/faq_113/
