### ISSUE TITLE
Pin repositories on your organization

### ISSUE THREAD

**Issue by lipis** [piwik/piwik#10839]
Sometimes the top repositories are lost in the huge list of other things.. now you can pin the repos that you want: https://github.com/piwik

Here is an example: https://github.com/wireapp 🗡

**Comment by sgiehl** [comment]
Hard to decide which should be pinned or not. For now I've pinned piwik and device detector as both have the most "stars"

**Comment by lipis** [comment]
This page can help you decide..

**Comment by tsteur** [comment]
That's a really nice summary @lipis 

I think we could star the top 5 from that list:

* piwik	
* device-detector	
* referrer-spam-blacklist	
* piwik-sdk-ios
* piwik-sdk-android

+ either `docker-piwik` (pos 6) or maybe `piwik-log-analytics` (pos 9) 

Any other thoughts?

**Comment by tsteur** [comment]
Actually, I see those 6 were pinned 👍
