### ISSUE TITLE
[2.17.0] Can't uninstall SecurityInfo and VisitorGenerator Plugin

### ISSUE THREAD

**Issue by zero-24** [piwik/piwik#10832]
i have just tryed to unistall the plugins `SecurityInfo and VisitorGenerator` but i can't unistall them i got an error:

![uninstall](https://cloud.githubusercontent.com/assets/2596554/19962107/6a49cbc2-a1b6-11e6-8c37-e44b0f47873f.JPG)

It is the same error as this here: https://github.com/piwik/piwik/issues/4801

**Comment by tsteur** [comment]
This looks like a very old version of the VisitorGenerator.

I think there might be 2 ways to fix this: 
1) Update VisitorGenerator to the latest version and then uninstall it
2) Remove it manually by reming the directory `plugins/VisitorGenerator` and then in `config/config.ini.php` you may want to remove the line `Plugins[] = "VisitorGenerator"` and `PluginsInstalled[] = "VisitorGenerator"`. The lines might not exist, in this case you can simply ignore it.

Same procedure for SecurityInfo.

**Comment by tsteur** [comment]
Let me know if it worked

**Comment by zero-24** [comment]
Thanks :+1:
