### ISSUE TITLE
Revert removing Request.getRenamedModuleAndAction listeners

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10831]
from https://github.com/piwik/piwik/pull/10815

Reasoning behind requesting a partial revert:

* cannot remember why we marked we would remove those calls
* Removing them would cause some errors in the way users may embed these reports in their app, forcing them to change apps or products or apps, which is time consuming for them
*  there is no advantage for the platform to remove this code: this is very little code with no complexity and most is tested...

**Comment by sgiehl** [comment]
Imho there is not much value in keeping that forever and it would be accaptable if some user may need to change the emedded urls. The plugin was deprecated in 2.10.0 over a year ago.
If we remove them, we should do it with a major release and I wouldn't wait for 4.0.

**Comment by mattab** [comment]
@sgiehl +1 to remove them but then could we note again in the developer changelog the methods removed and the new methods to use instead.

**Comment by sgiehl** [comment]
I'd add something like:

> Widgets using the already removed `UserSettings` plugin won't work any longer. Please recreate your widget urls using `DevicesDetection`, `Resolution` or `DevicePlugins` plugin instead.

But should we really list all methods that had been removed a long time ago?

**Comment by mattab** [comment]
> But should we really list all methods that had been removed a long time ago?

Yes let's list them all, as the Widget URL embed API was effectively broken it's important I feel to lay out changes we made. Ideally we'd just have to "Copy paste" the previous changelog entries where we would announce the 'url rewrites', but seems we didn't document it so far, so it will be the first time we document.
