### ISSUE TITLE
Tracking is not working when page title contains apostrophe

### ISSUE THREAD

**Issue by fred-the-coder** [piwik/piwik#10838]
Hi,

I was not understanding why tracking for one of my website was not working...I used bugzilla to check what was happening on network side and discover a 403 error on GET <my piwik server URL>/piwik.php.

I tryed to play with the URL. I saw that parameter "action_name" has page title as value. I found that if I remove the apostrophe in page title it was working fine!
My web site name contains an apostrophe (character = ' ) and site name is used in all website pages title...

Not sure it is a bug, maybe it's "working as expected"...if not a bug, I would like to know if there is a workaround...?

Right now I replace the apostrophe with a space...

Thank you for your reply.

**Comment by tsteur** [comment]
I have tried to reproduce this but couldn't. I think we pretty much do not even send a 403 when tracking. Likely you have some kind of security mod active which prevents forwarding the call to Piwik and directly blocks it. I'd recommend to ask your sys-admin / hoster or have a look at your server configuration.

**Comment by fred-the-coder** [comment]
OK,
Thank you for your answer!
Remind that tracking is working when I remove the apostrophe in page title. Page title which is part of the URL sent for tracking....

**Comment by tsteur** [comment]
Yes, that's what the security mod is likely blocking, the apostrophe. Please check with your hoster / sys admin it's likely a security mod or security plugin.

**Comment by ADKlineDesign** [comment]
Hi - I had the same type of problem. The occurrence of the word "and" in the "action_name" parameter resulted in a 403 error on GET /piwik.php.

For those who cannot resolve this via their hosting provider, the solution is to filter the page title before providing it to Matomo.

Replace the following lines in the Matomo Tracking Code:

`var _paq = _paq || [];
_paq.push(['trackPageView']);`

With:

`var filtered_page_title = document.title.replace('to_be_filtered ',''),
    _paq = _paq || [];
    _paq.push(['setDocumentTitle', filtered_page_title ]);
    _paq.push(['trackPageView']);`

This will remove the offending item ("to_be_filtered") from the page title before providing that title to Matomo (in my case this was the word "and").
