### ISSUE TITLE
Add WebGL support statistics

### ISSUE THREAD

**Issue by johsin18** [piwik/piwik#10841]
Would be great if Piwik would report statistics on WebGL support, maybe as one more entry in the list of "Plugins" in the Visitors/Software page.
It's not literally a plugin, but "Cookie" is neither, and WebGL is often used as a replacement for some of the listed plugins, e.g. Flash.

**Comment by sgiehl** [comment]
I'd vote to implement that in Piwik 3.
Shouldn't be difficult to detect. Sample JS to do it proper:

```javascript
var canvas = document.createElement('canvas');
var webglContextParams = ['webgl', 'experimental-webgl', 'webkit-3d', 'moz-webgl'];
var webglContext = null;
for (var index = 0; index < webglContextParams.length; index++) {
	try {
		webglContext = canvas.getContext(webglContextParams[index]);
		if(webglContext) {
			break;
		}
	} catch (e) {}
}
if(webglContext === null) {
	console.log('WebGL is not supported');
} else {
	console.log('WebGL is supported');
}
```

Note: Not sure if we should make that detection by default. Creating WebGL objects might force the browser switching from Hardware- to Software-Rendering. At least IE makes that afaik.

**Comment by tsteur** [comment]
When we're unsure about certain features it is always good to add the feature as opt-in 👍  and once we have more experience with it and feedback make it default eg in Piwik 4

**Comment by tsteur** [comment]
Especially for tracker...

**Comment by sgiehl** [comment]
release in a new plugin: https://plugins.piwik.org/DeviceFeatureWebGL
Will work from the next release on
