### ISSUE TITLE
Missing icon for Samsung Browser

### ISSUE THREAD

**Issue by jsmad** [piwik/piwik#10848]
There is no icon for the Samsung Browser on Android phones.

Here it is:
https://lh3.googleusercontent.com/TAcIrBPu2YVSqrG3KclrwU7RxYmy7ab-9XTkC6ALmR9BNRQdKieV-5-VYqQK8A3c1oc=w300

**Comment by sgiehl** [comment]
added the new icon to 2.x-dev and 3.x-dev branch so it will be included in both releases.
