### ISSUE TITLE
Goals Overview always shows 0% conversation rate

### ISSUE THREAD

**Issue by johsin18** [piwik/piwik#10851]
When showing the respective graph, it amounts to 14.75% conversation rate in the shown example.

![0conversions](https://cloud.githubusercontent.com/assets/3518185/20187509/d4befcb6-a774-11e6-9b8a-9933d5660271.png)

I'm using Piwik 2.17.0.

**Comment by mattab** [comment]
Hi @johsin18 - thanks for the report. Would you mind testing in Piwik 3.0.0 beta if you experience this issue? I think we have fixed it but it would be good to hear your confirmation? http://piwik.org/faq/how-to-update/faq_159/

**Comment by johsin18** [comment]
I confirm that this is fixed in 3.0.0.

**Comment by tsteur** [comment]
Thank you for letting us know 👍
