### ISSUE TITLE
Two referer for same url

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#10857]
Hello,

On my dashboard, for website referer widget, Piwik 2.16.1 show two rows for the same url:
- plugins/apijs => http://...
- plugins/apijs => https://...

![referer](https://cloud.githubusercontent.com/assets/18172876/20246360/a52c6aae-a9b5-11e6-97c1-672c2000f0be.png)

It's a bug or a stupid feature or a good feature?

**Comment by mattab** [comment]
Hi there, as can be seen in this PR: https://github.com/piwik/piwik/pull/10970

Piwik will indeed track both website referrers URLs as HTTP and HTTPS separately, if they were both used. This could be changed in the future, but for now that's how it's done.
