### ISSUE TITLE
Page urls appearing "flat" in hierachical view

### ISSUE THREAD

**Issue by phoob** [piwik/piwik#10858]
Using Piwik 2.17.0 (PHP 7.0.8-0ubuntu0.16.04.3), I get some odd behavior for the Actions reports where the tables are based on page urls. Some urls are displayed twice: once in hierarchies and once flat. They have different counts for page views etc. See attached screen shot. I have no idea where to start explaining this.. but I can't seem to find any similar issue here. 

![screenshot](https://cloud.githubusercontent.com/assets/1475800/20248854/e5a80458-a9ec-11e6-9954-17a54bc5b38e.png)

**Comment by mattab** [comment]
Thanks for the report @phoob - it does look like a bug and we haven't heard about this otherwise.

Does anyone else experience this issue?

**Comment by phoob** [comment]
Seems it might be related to the fact that I used jQuery Waypoints to track events (when user scrolled to 50%, 75% and 100% of pages). The symptoms came and went away at about (but not exactly) the same time I tried that... this was the code that I used:

```
	$(document).ready(function() {
		window.trackScrolling();
	});

	window.trackScrolling = function(){
		var waypoints = [0.75,1];
		waypoints.forEach(function(wp,i){
			var dh = $(document).height();
			var wh = $(window).height();
			var currentUrl = window.location.href.split('?')[0].replace(/\/?$/, '/');
			waypoints[i] = new Waypoint({
				element: document.body,
				handler: function(dir){
					_paq.push(['trackEvent', 'Scroll', wp*100 + '%', currentUrl ]);
					this.destroy();
				},
				offset: '-' + ((dh*wp)-wh)
			});
		});
	};
```

**Comment by tsteur** [comment]
Maybe some URLs are sent URL encoded and some not. Try `_paq.push(['trackEvent', 'Scroll', wp*100 + '%', decodeURIComponent(currentUrl) ]);`

**Comment by mattab** [comment]
Btw there's also this tool for tracking scrolls down the page in piwik http://rodi.sk/misc/piwik-scroll-depth/

**Comment by mattab** [comment]
Cannot reproduce yet
