### ISSUE TITLE
Forward-port all 2.71.1 fixes and improvements to Piwik 3

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10861]
Let's go through and forward-port all the 2.71.1 desired code changes to 3.x-dev branch (most are already merged but not quite all)

**Comment by mattab** [comment]
Checked through commits https://github.com/piwik/piwik/compare/2.17.0...2.x-dev and seems they're all here now. 

@tsteur only one still not as a PR is: https://github.com/piwik/piwik/commit/1a2a91e968ea6ad82adf8cebe38d0baf8c3d776a

**Comment by tsteur** [comment]
was included in a different PR
