### ISSUE TITLE
UI test Overlay_page_new_links regressed

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10869]
See discussion in: https://github.com/piwik/piwik/pull/10842

The UI test Overlay_page_new_links / `page_new_links` does not work about since this PR was merged #10580

See for example at: http://builds-artifacts.piwik.org/piwik/piwik/new_submoduels/20945/Overlay_page_new_links.png

![diff](https://cloud.githubusercontent.com/assets/466765/20298748/8695c018-ab7c-11e6-89a8-ddf7f86bbc66.png)

**Comment by sgiehl** [comment]
Seems this one is already fixed somehow... latest process screenshot looks correct http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/21730/processed/Overlay_page_new_links.png

**Comment by mattab** [comment]
But the expected one doesn't: https://github.com/piwik/piwik/blob/recursive_columns_api/tests/UI/expected-screenshots/Overlay_page_new_links.png

do you know why tests are passing anyway?

**Comment by sgiehl** [comment]
Test was changed to check for "similar" image. I'll remove that...
