### ISSUE TITLE
2006 MySQL server has gone away

### ISSUE THREAD

**Issue by Trance-Man** [piwik/piwik#10865]
Have an issue, please someone tell me exactly what I can do to solve this and do the update.

Got this message this morning to update Piwik [below]
**Piwik 2.17.1 is available. - Please update now! (see changes). - You are currently using Piwik 2.17.0.** 

==== When trying to update, error below ======
**Update error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away**

**Comment by tsteur** [comment]
Can you have a look at http://piwik.org/faq/troubleshooting/faq_183/ ?

**Comment by Trance-Man** [comment]
I saw that thread thank you, but I am not sure where to find that file [Server timed out and closed the connection. To fix, check that “wait_timeout” mysql variable in your my.cnf configuration file is large enough.], inside Piwik install/main folder on my server or is that a server type file, please if someone can help me figure it out. Thank you.

**Comment by mattab** [comment]
Hi @Trance-Man please contact your webhost, or for professional support see: http://piwik.org/support/
