### ISSUE TITLE
Scheduled reports columns are missing average price, conversion rate

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10875]
for some reasons after passing flat=1 to the scheduled reports,

some of the data (average price, conversion rate) became "zero"

regression visible in https://github.com/piwik/piwik/pull/10870/files#diff-c4467c545cc9ea3a94cc2b8be30809e0L417

regressed in https://github.com/piwik/piwik/pull/10870/files

**Comment by sgiehl** [comment]
guess thats related to #10916
