### ISSUE TITLE
I can't translate some fields

### ISSUE THREAD

**Issue by ademaro** [piwik/piwik#10877]
I get Error: The expression '% d' is not present in the translation.
![img](https://3.downloader.disk.yandex.ru/preview/d00d644af1410528169a83a144542829411fa99d4333b76ee47d43e4ab1085ae/inf/xbtgyAQi0rDaqNpt_hEu1pF0tnpky_hPKweAPiXP97PMPJZuiHSQT1SuXQIBfeP5ClUjNauLHo_UMtlARSJUaA%3D%3D?uid=0&filename=2016-11-16_07-48-01.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

**Comment by sgiehl** [comment]
Need to do some tests if we could change it to %% or if Piwik isn't able to handle that correctly.

**Comment by ademaro** [comment]
all works! tnx! 👍
