### ISSUE TITLE
JS Tracking: Improve documentation for multiple Piwik server tracking

### ISSUE THREAD

**Issue by gkannan21** [piwik/piwik#10883]
Hi ,
I need to know more for the following,

1.how to track the website data to multiple piwik server in version 2.17.0 , can anyone show me the sample tracking code for tracking my website data in to multiple piwik server and also for multiple website date into single website id in same piwik server.

i need for 2.17.0 version java tracking code not earlier  code.

2.difference between domain,subdomains and sub directories,multiple piwik tracker.

Actually, my website video site xxx.com with many users page like "xxx.com/username1""xxx.com/username2" like its going
i need to track in piwik for each and every username created separately in piwik server.
Also i need to track all user page in single piwik site id in another piwik server or same piwik server.

Please advice any idea.
if you have any confusion please reply.

Thanks
KannanG

**Comment by tsteur** [comment]
Have a look here: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers

**Comment by gkannan21** [comment]
Hi ,

I already seen that document , but its not clear where to add and how to add this code in my website.for version 2.17.0
for my 3 question which one i have to use multiple tracker or subdirectories
Thanks for your reply

**Comment by gkannan21** [comment]
any one please advice

**Comment by mattab** [comment]
> I already seen that document , but its not clear where to add and how to add this code in my website.for version 2.17.0

@gkannan21 what is not clear in the developer guide? maybe we can improve it there

**Comment by tsteur** [comment]
The guide pretty much doesn't cover this topic at all currently, unless you kind of want to track same data into different servers. A standalone page for this would be great eventually

**Comment by gkannan21** [comment]
Above document clear for  2.16.0 before version,but not clear for recent versions 3.0.
it just given code like this
<script type="text/javascript">
    window.piwikAsyncInit = function () {
        try {
            var piwikTracker = Piwik.getTracker("http://URL_1/piwik.php", 1);
            piwikTracker.trackPageView();
            var piwik2 = Piwik.getTracker("http://URL_2/piwik.php", 4);
            piwik2.trackPageView();
        } catch( err ) {}
    };
</script>

But i dnt know where i have to include this code,if i add this code below piwik java code its not working .
iam ecpecting full code sample code for version 3.0 like below.
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);

  (function() {
    var u="//piwik.example.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);

    // Add this code below within the Piwik JavaScript tracker code
    var secondaryTracker = 'https://analytics.example.com';
    var secondaryWebsiteId = 77;
    // Also send all of the tracking data to this other Piwik server, in website ID 77
    _paq.push(['addTracker', secondaryTracker, secondaryWebsiteId]);
    // That's it!

    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by gkannan21** [comment]
Hi All
Actually this is my java tracing code.
my website is xxx.com/login-form  and website id is 81 in piwik website list.
-----------------------------------------------------------------

<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDomains", ["*.xxx.com/login-form"]]);
  _paq.push(['trackPageView']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
 _paq.push(['enableHeartBeatTimer']);
(function() {
    var u="//xxx.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '81']);
 var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//xxx.com/piwik/piwik.php?idsite=81" style="border:0;" alt="" /></p></noscript>
<a href='#'  onclick="javascript:_paq.push(['trackEvent', 'MediaVideo','Like','comedy']);">Like</a>
<a href='#'  onclick="javascript:_paq.push(['trackEvent', 'MediaVideo','UnLike','comedy']);">UnLike</a>
<a href='#'  onclick="javascript:_paq.push(['trackEvent', 'MediaVideo','Share','comedy']);">Share</a>

---------------------------------------------------------------------

I need to track same website data in another website id  in same piwik server 

for example website id in 59.same piwik server.

iam using 3.0 piwik version.

Also i need to know track same website data in to another piwik server someother website id 

for example piwil server name yyy.com/piwik and website id is 2.

Please give me the exact java script code (like code available between 2 lines.for above my requirement.

Please dont refer this link for me "https://github.com/piwik/developer-documentation/pull/132/files?short_path=60f3612#diff-60f3612107814f4dba4f161a21efa02e"

Already i followed the link.i need exact code for the piwik version 3.0.

Thanks
KannanG

**Comment by tsteur** [comment]
I think this can be closed now https://piwik.org/blog/2017/02/complete-guide-tracking-websites-web-apps-multiple-piwiks-easily-efficiently/
