### ISSUE TITLE
Visitors -> Users: "There is no data for this report."

### ISSUE THREAD

**Issue by Danchello** [piwik/piwik#10895]
Hi there,

I think the title is self-explanatory, there is no data when I check Users tab (same result for different websites and time periods). I haven't checked users tab for while, but the issue is probably connected to the fact that i just updated piwik to the latest release (2.17.1-rc1).

All the other features like visitor log, actions and goals work just fine. The diagnostics only show problem with "LOAD DATA INFILE", but as far as I know this shouldn't cause the issue.

**Comment by tsteur** [comment]
Are you tracking users? http://piwik.org/docs/user-id/

**Comment by suvedhaGanapathy** [comment]
Hi ,
please provide some steps on adding user-id other than  'http://piwik.org/docs/user-id/'(which explains only for php) , I don't use php in my project, I use angularjs and django rest api for my project, how can I use them in my project.

**Comment by shravya123456** [comment]
sir,
 I am getting visitors-->users as "no data for this report".
.I am running the command as python 
C:/xampp/htdocs/analytics/piwik/misc/log-analytics/import_logs.py --url=http://localhost:8089/analytics/piwik --log-format-name=w3c_extended --w3c-time-taken-millisecs --idsite=1 --recorders=4 --enable-http-errors --enable-http-redirects --enable-bots C:/inetpub/logs/LogFiles/7july2017/u_ex170725.log

to get the log report in piwik..I am unable to track the record of userid in piwik section.Please guide me

**Comment by shravya123456** [comment]
Already i read 'http://piwik.org/docs/user-id but didnt find any solution to retrieve the userid from python
