### ISSUE TITLE
XFRAME options issue

### ISSUE THREAD

**Issue by gkannan21** [piwik/piwik#10891]
Hi 

We facing xframe options domain error.using iframe widgets diaplaying dashboard in my own website,while open piwik dashboard using iframe code getting xframe error.

where to remove the xframe options or where to allow my website URL to resolve issue.In my webserver or PIWIK server where and what do i change to resolve this issue.

**Comment by mattab** [comment]
Hi @gkannan21 please see this FAQ about embedding reports in iframe: http://piwik.org/faq/troubleshooting/faq_147/
