### ISSUE TITLE
I can not log in.

### ISSUE THREAD

**Issue by vlamant** [piwik/piwik#10907]
Hello. Help me please. I can not log in.

`Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Piwik to accept the proxy header that forwards the Host header.`

Everything worked, and stopped after the upgrade.

**Comment by pebosi** [comment]
Have you done what the message explaine? Host-Header, cookies, etc.?

**Comment by vlamant** [comment]
I found the cause. This problem is related to the PHP 7.0. In PHP 5.5 it works.

**Comment by vlamant** [comment]
I found the cause. This problem is related to the PHP 7.0. In PHP 5.5 it works.

**Comment by vlamant** [comment]
I found the cause. This problem is related to the PHP 7.0. In PHP 5.5 it works.
