### ISSUE TITLE
(3.0.0b) appearance suggestion

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#10906]
Hi, as all went material in new version, the left dashboard sidebar could be converted into a stand-alone section by reducing the width and adding small margin, this way it will align with top search bar.

This change does not affect mobile view.
See example:

now:
![2016-11-24_155822](https://cloud.githubusercontent.com/assets/5383059/20602978/c9b0780e-b25f-11e6-812f-c8678f86a38a.png)

after:
![2016-11-24_155529](https://cloud.githubusercontent.com/assets/5383059/20603004/d4b69210-b25f-11e6-8714-63d39bc19a6b.png)

**Comment by mattab** [comment]
Hi @dev-101 thanks for suggestion, but the current left menu design is this way on purpose.
