### ISSUE TITLE
Dashboard column layout reset to 3 after upgrading from 2.17.1 to 3.0.0-b3

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#10905]
Hi, column layout was reset from 2 (equal width) to 3 (equal width) after auto-upgrading to 3.0.0-b3.

Btw, nice work :)
Thanks

**Comment by tsteur** [comment]
@sgiehl we are using `Dashboard\Model::replaceDashboardWidgets` to update the widgets. Do you know if we had such issues before?

**Comment by sgiehl** [comment]
No, don't know of any issues like that.
But I can have a look at it later.

**Comment by sgiehl** [comment]
Wasn't able to reproduce that and can't see any obvious mistake in the methods, but I don't have much time to dig deeper into that right now.

**Comment by tsteur** [comment]
No worries, I had a look as well and couldn't find an obvious problem. @dev-101  from which version did you update? Where all the widgets still visible? Do you have one dashboard or several dashboards?

**Comment by dev-101** [comment]
Hi tseur and shiehl,

this is definitely not a serious issue, but only noticed it on desktop, as I have performed upgrade from mobile...

Anyway, as already stated in the issue title above, I was upgrading from latest stable version 2.17.1 to 3.0.0-b3.

I have only 2 widgets active on the landing dashboard page (visits over time; real time;)

Soon I will perform other Piwik instances on the same server, so will report here if the problem reappears, as they have similar layout setup, but are completely separated installations.

Thanks

**Comment by tsteur** [comment]
Sweet. Please let us know how it went there 👍

**Comment by mattab** [comment]
feel free to reopen if issue is confirmed
