### ISSUE TITLE
Count and track custom data

### ISSUE THREAD

**Issue by pebosi** [piwik/piwik#10919]
Hi, 
what is the right way to track custom data for a site?
I would like to import data from search console, to have timeseries of keyword positions.

Regards

**Comment by RMastop** [comment]
Hi @pebosi,

One method would be to add Site Search using the Javascript trackSiteSearch() function, as it is explained in the user guide: 
http://piwik.org/docs/site-search/#track-site-search-using-the-javascript-tracksitesearch-function
or in developer guides:
http://developer.piwik.org/guides/tracking-javascript-guide#internal-search-tracking

This way of tagging will improve the site search report, like knowing what category do visitors search in and what keywords returned no results.

Is this what you are looking for?

**Comment by pebosi** [comment]
Hi, no SiteSearch is not what i meant. i would like to track custom data form Google Search Console, Ranking Stuff, etc.

**Comment by mattab** [comment]
Hi @pebosi 
We are working on the premium product to import data from Google/Bing/etc. search consoles. Please stay tuned about this and check upcoming announcements and marketplace release. 

To answer your question: to track custom data for a site, best way is to use custom dimensions: https://piwik.org/docs/custom-dimensions/ or to write a custom plugin using our platform: http://developer.piwik.org/
