### ISSUE TITLE
(3.0.0-b3) (UI) (mobile) Action > Pages - Please restore page zoom in/out for tables

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#10912]
It is no longer possible to use a "single finger" gesture to zoom in/out page in Chrome Mobile browser app, something that is possible in 2.x. I need to easily zoom in/out tables to fit at least first column and quickly examine the data, instead of scrolling through overflow content, that I can only partially see.

Also, a suggestion to reduce left and right margins to bare minimum; on narrow mobile screens would be another major plus, it wastes 10-15% of the screen for fancy appearance, instead of usability.

Thanks

**Comment by dev-101** [comment]
Well, after some investigation, it seems that Chrome mobile browser app now sees the page as 'responsive and mobile friendly', so it disables single-finger zooms (in/out) by itself, because the table is overflowed, where in the older versions was not.

I assume you will not go over the new design because of this, but it really has lower mobile usability, to say at least.

**Comment by mattab** [comment]
Hi @dev-101 thanks for the feedback. Would you mind posting a screenshot showing when it is unusable in Piwik 3?

**Comment by dev-101** [comment]
Hi Matthieu,
the screenshot is not gonna tell you much :)

![2016-12-06_114052](https://cloud.githubusercontent.com/assets/5383059/20922581/f777bfac-bba8-11e6-9f42-2bdaac129581.png)

![2016-12-06_114136](https://cloud.githubusercontent.com/assets/5383059/20922588/fdf472e4-bba8-11e6-8bd7-95a67245fc92.png)

Simply reduce your browser's width to 300-400 pixels, go to Actions > Pages (select any meaningful range to produce table with results) and this table is now made horizontally scrollable with `overflow-y: scroll`:

`<div class="card-content" style="overflow-y: scroll;">`

In mobile, Chrome browser app will not allow you to zoom-out the table/page (with single or both fingers, does not matter) (as was possible in Piwik 2.x, because the page was not responsive) and make the table smaller to fit fit more columns (e.g. with with title + next table column = pageviews).

This is how it is... so I'll have to get used to it.
