### ISSUE TITLE
(3.0.0-b3) old piwik 2.x bookmarks no longer working

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#10913]
I keep some bookmarks to quickly access certain sections, for example action > pages > last day pageviews table, last 30 day pageviews table and so on.

They are no longer working in Piwik 3.x, instead I am "returned" to main dashboard with widgets.

**Comment by sgiehl** [comment]
The URLs for the pages have simply been changed. You may need to recreate your shortcuts.

**Comment by dev-101** [comment]
Thanks Stefan, already did it.
I've opened the issue just to be documented.
