### ISSUE TITLE
Have the LDAP Plugin support login via API

### ISSUE THREAD

**Issue by lucaboesch** [piwik/piwik#10936]
Taken from [http://piwik.org/faq/mobile-app/#faq_16332]
Do you use the LDAP plugin? Unfortunately, the LDAP plugin does currently not support to log in via API
Supporting the LDAP plugin would give a lot more user access by using the app.

**Comment by cybernet** [comment]
i still don't get it :(

**Comment by lucaboesch** [comment]
You don't get the issue's matter?
It states in the subject: Have the LDAP Plugin support login via API
The description then is just a quotation taken from the FAQ.

**Comment by mattab** [comment]
Hello @lucaboesch - please can you report the suggestion about LDAP in the Ldap tracker here: https://github.com/piwik/plugin-LoginLdap/issues
