### ISSUE TITLE
Feature request: provide a archive generation package

### ISSUE THREAD

**Issue by SR-mkuhn** [piwik/piwik#10932]
Is it possible to provide a package, that can run on a dedicated databaseserver without all assets, just for report generation?

Greetings

**Comment by mattab** [comment]
Hello @SR-mkuhn 
You can use Piwik on any server and if you disable the webserver then you can use Piwik from the command line. https://developer.piwik.org/guides/piwik-on-the-command-line

**Comment by SR-mkuhn** [comment]
Hi @mattab 
I know, and we are already doing this, but my request was about stripping down this package to save space and get rid of everything not necessary to report generation.
