### ISSUE TITLE
Using use_third_party_id_cookie=1, Idvisitor same in database but JS getVisitorId() return different

### ISSUE THREAD

**Issue by hrhthegreat** [piwik/piwik#10934]
Hello,
I am using the third party cookie to track users cross different sites with different site ids. I have set use_third_party_id_cookie=1 and the idvisitor column in the database are the same for all sites but when I try to get idvisitor through Javascript getVisitorId(), the Ids are different. Is this a normal behavior?
How should I take with same Id for different visits with Javascript?

**Comment by mattab** [comment]
Hello @hrhthegreat 

Yes it is a normal behavior as the third party cookie can't be read from JS. Marking as "wontfix"
