### ISSUE TITLE
Update FAQ: How do I change the Super User’s password when password recovery emails are not sent?

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10941]
Our FAQ: [How do I change the Super User’s password when password recovery emails are not sent?](http://piwik.org/faq/how-to/faq_191/) needs to be updated with a new procedure for Piwik 3, since we do not use hashed md5 anymore.

Follows up #10740 #10926 #5728

**Comment by mattab** [comment]
@mneudert  maybe you have some idea how we could update the FAQ to work with Piwik 3+ ?

**Comment by mneudert** [comment]
The most simple advise would probably a oneliner:

```shell
php -r 'echo password_hash(md5("changeMe"), PASSWORD_DEFAULT);'
```

But if one has access to the database he might also be able to copy the reset password over from the "[username]_reset_password_info" option. If that key got written it should be valid and ready for use.

**Comment by mattab** [comment]
Thank you very much @mneudert - the FAQ has been updated: https://piwik.org/faq/how-to/faq_191/ :+1:
