### ISSUE TITLE
Piwik on Cloud Foundry

### ISSUE THREAD

**Issue by mastertinner** [piwik/piwik#10950]
I have written a tutorial about how to deploy Piwik to [Cloud Foundry](https://www.cloudfoundry.org/): https://berndsgn.ch/run-piwik-on-cloud-foundry/

However, I am not too happy about how I have to edit the files which are part of Piwik additionally to the `bootstrap.php` file. Also, if I add a `config/config.ini.php` file, the app doesn't start on Cloud Foundry so I had to edit the `global.ini.php` directly which is far from optimal. Could you guys give me some inisghts on how to improve the blog post and how I could avoid having to change the files mentioned above? The whole goal is to have a database configuration which is dynamically read from the environment variables on start up of the app.

**Comment by tsteur** [comment]
I'd recommend to have a look at https://github.com/piwik/piwik/issues/10257 and https://github.com/piwik/piwik/issues/10914

**Comment by bbodenmiller** [comment]
@mastertinner great tutorial. Have you published the code on GitHub anywhere or know of any Matomo on Cloud Foundry GitHub projects?

**Comment by mastertinner** [comment]
@bbodenmiller, all the code that deviates from Matomo should be part of the tutorial. I don't know if the tutorial still works with Matomo though because the tutorial was written quite a while ago.

**Comment by berndgoetz** [comment]
It can be now found at https://blog.bespinian.io/posts/run-piwik-on-cloud-foundry/ - nice work, thanks for the post, although some time ago. Maybe somebody has a refresh for it. I'll definitely give it a spin. It's definitely an valuable option between VM based and going SaaS.
