### ISSUE TITLE
comparison tool for different PIWIK reports of a same project

### ISSUE THREAD

**Issue by arbaldryan** [piwik/piwik#10964]
Hi there! I would like to know if you have a new alternative to the PIWIlk comparison dashboard tool. I have been trying to find out a solution for making a comparison of PIWIK reports of a same site within different time periods. Do you perhaps have an answer to this question?

Thanks, 
Arus

**Comment by mattab** [comment]
Hello @arbaldryan 
See these issues: #5711 #7716
