### ISSUE TITLE
core/Updater/Migration/Db/BoundSql.php(40): Warning - addcslashes() expects parameter 1 to be string, array given - 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10975]
Not sure if this is  bug but worth investigating:

> WARNING: /home/lafoytr1/public_html/piwik/piwik/core/Updater/Migration/Db/BoundSql.php(40): Warning - addcslashes() expects parameter 1 to be string, array given - Piwik 3.0.0-b3 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

Reported in https://forum.piwik.org/t/upgrade-to-piwik-3-0-0-b3-warnings/21842

**Comment by tsteur** [comment]
The last two updates defined in core don't pass arrays. Maybe it is from a plugin?

**Comment by mattab** [comment]
Thanks for checking
