### ISSUE TITLE
different hints where to put tracking code on website

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11007]
different hints where to put tracking code on website:
in setup <->"no data yet" message

please see attachments

![2016-12-14_15h41_42](https://cloud.githubusercontent.com/assets/5681880/21186246/2942c97a-c214-11e6-87ff-8e7c7f53f92e.png)

![2016-12-14_15h40_15](https://cloud.githubusercontent.com/assets/5681880/21186255/335b5c38-c214-11e6-92d1-e7ee277b3e00.png)

**Comment by tsteur** [comment]
Thx 👍  Issued PR https://github.com/piwik/piwik/pull/11011
