### ISSUE TITLE
widget name and behaviour does not match

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11008]
widget name and behaviour does not match

please see attachment
![2016-12-14_15h25_17](https://cloud.githubusercontent.com/assets/5681880/21186511/325be7f2-c215-11e6-8a42-94a01b943c55.png)

**Comment by tsteur** [comment]
Maybe we should rename it to "previous" (in German "vorherige")

**Comment by mattab** [comment]
I guess it's not confusing in English so feel free to edit the german translation directly on Transifex, if it's deemed appropriate @hpvd https://www.transifex.com/projects/p/piwik/
