### ISSUE TITLE
Unable to change password after upgrade to 3.0.0-RC3

### ISSUE THREAD

**Issue by slinkymanbyday** [piwik/piwik#11018]
Occurs after update to 3.0.0-RC3 from RC2.

In personal-> settings, attempting to change password results in a passwords do not match message even when the passwords do match.

**Comment by tsteur** [comment]
Can you maybe execute a MySQL query and let us know the output?

```sql
show fields from piwik_user where Field = 'password'
```

**Comment by tsteur** [comment]
Actually, I can reproduce this

**Comment by slinkymanbyday** [comment]
No problem. Thanks for responding so quickly.

Just in case, output from MySQL: 
`'password', 'varchar(255)', 'NO', '', NULL, ''`

**Comment by tsteur** [comment]
Cheers, I have issued a PR to fix it 👍  Thanks again
