### ISSUE TITLE
Downloading some HTML reports shows a "Success:ok" after the HTML

### ISSUE THREAD

**Issue by SimonWaters** [piwik/piwik#11014]
During testing 3.0.0-rc3

When you view some HTML reports the string "Success:ok" is displayed in the browser (Firefox 55) using Debian Jessie and default PHP5 and Mysql.

Inserting this message seems to be normal behaviour of the ResponseBuilder for the API, so I assume it is being called in the wrong context.

My request

http://192.168.56.103/index.php?module=API&action=index&idSite=1&period=day&date=yesterday&activated=&mode=admin&type=&show=&updated=2&token_auth=303a5339083d704fcf3448dd7fe31530&method=ScheduledReports.generateReport&idReport=2&outputType=3&language=en&format=html

HTML response ends:

</html>
Success:ok

![screen shot 2016-12-14 at 22 53 10](https://cloud.githubusercontent.com/assets/5347414/21204623/28bb0440-c250-11e6-8c29-ada155edd60f.png)

**Comment by mattab** [comment]
Thanks for the report - fixed in the latest version
