### ISSUE TITLE
setup piwik via API: new website, new goals, new segments etc

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11010]
setup piwik via API would be really awesome when wanting connecting Piwik with different external tools.
- new website (e.g. push name, url etc., return ID given by piwik)
- new goals,
- new segments
- etc

are there already any possibilities in this field?
are there plans?

**Comment by tsteur** [comment]
Piwik already comes with an API (see http://developer.piwik.org/api-reference/reporting-api ) to do this, or do you mean one API where you can pass all segments, all goals in just one API call?

**Comment by mattab** [comment]
Yes it should already be possible with our many APIs. Everything that Piwik can do can be done with the APIs, since all the user interfaces in Piwik use APIs. :+1:
