### ISSUE TITLE
GeoIP2 installation ignored, piwik falls to DEFAULT provider

### ISSUE THREAD

**Issue by Glisse1** [piwik/piwik#11034]
Hello.

I have installed the new GEOIP2 provider, with LITE database, activated the plugin and selected it with no problem. But for some reason also I select this provider, on the front-end (i mean, in stats, live plugin, etc) piwik falls back and gives me just the useless DEFAULT provider. Dont know if it`s plugin`s fault, but i`ve been waiting for 3 years to get access to the highly enhanced geoip2 which is 3 times bigger than the old geoip1, so this is a blow for me :(

Screenshots with my own IP case. 

![snip1](https://cloud.githubusercontent.com/assets/8209518/21294342/1d0ab028-c543-11e6-8a36-502cc6166efc.PNG)
![snip2](https://cloud.githubusercontent.com/assets/8209518/21294343/1ef26afc-c543-11e6-81a9-680f5abfce84.PNG)

**Comment by tsteur** [comment]
Did you install http://plugins.piwik.org/GeoIP2 ?

**Comment by Glisse1** [comment]
Yes, of course, that`s the one.. i looked forward to 3.0 rc because this plugin was not for 2.17x

**Comment by tsteur** [comment]
@Glisse1 do you mind creating the issue on https://github.com/diabl0/piwik-geoip2 ? We can't provide support for third party plugins.

**Comment by s1awa** [comment]
@tsteur This plugin uses GeoLite2-City.mmdb file format.

When trying to use "Setup automatic updates of GeoIP databases" with this type of database (http://dev.maxmind.com/geoip/geoip2/geolite2/)
The updater fails with an error because of the .mmdb file ending. Can it be added to the autoupdater or does the plugin author needs to write his own update function?

To reproduce upload GeoLite2-City.mmdb to misc folder and use the url (http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz) to autoupdate.

**Comment by Glisse1** [comment]
@s1awa i did not manage to make it work, that is make geolite2-city be the one used instead of the default provider as you can see in the posted screenshots, let alone auto-update. Is this working for you?

**Comment by tsteur** [comment]
I will reopen the issue for now as it sounds like it might be an issue in Piwik @s1awa ?

**Comment by s1awa** [comment]
@tsteur I think this ticket is about a different issue. So I made a new ticket: https://github.com/piwik/piwik/issues/11049

**Comment by s1awa** [comment]
Another example with IP in Germany. It definitely is not using the plugin for geoip but the browser language of the "Default Location Provider"
![geoip2](https://cloud.githubusercontent.com/assets/20663500/21335448/f7e37886-c699-11e6-8e36-cdf9e18ea3f8.png)
![visitors](https://cloud.githubusercontent.com/assets/20663500/21335452/fdea8f94-c699-11e6-8f56-43766f467c29.png)

**Comment by diabl0** [comment]
@Glisse1 
Unfortunately i'm on christmas vacation and cannot investigate this in details, but diabl0/piwik-geoip2 it's very simple - it gets IP address from Piwik (https://github.com/diabl0/piwik-geoip2/blob/master/LocationProvider/GeoIP2.php#L141), runs it thru maxmind-db/reader library () and rewrites results to Piwik expected format. There is no checks for browser accepted language and any other logic (except rewriting region/country codes from ISO 3166-2 Code to FIPS 10.2).

@s1awa currently diabl0/piwik-geoip2 doesn't support autoupdating.

In jan/feb i will probably get back to our piwik integration project and will have more time for more extended testing, and then i'm also planing to implement autoupdate.

**Comment by Glisse1** [comment]
So, in february we`ll know if it`s piwik`s fault or plugin`s.

Looking forward to it, thx

**Comment by mattab** [comment]
@Glisse1 did you maybe find out if it was a bug in Piwik core or in the plugin itself? Thanks!
