### ISSUE TITLE
Safe mode: Display plugin versions next to plugin names

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11043]
Make Error Message
```
A fatal error occurred
The following error just broke Piwik (v3.0.0)
```
even more helpful

by showing version number of plugins installed -in addition to their names

=> with this one could more easy search (google) for a possible solution ...

learned from:
https://github.com/piwik/piwik/issues/11041

![2016-12-19_10h51_13](https://cloud.githubusercontent.com/assets/5681880/21308679/4e69e6c8-c5db-11e6-866b-88f26c55df0a.png)

**Comment by mattab** [comment]
Plugin version added in safe mode in https://github.com/piwik/piwik/pull/11082/files

**Comment by mattab** [comment]
Done in https://github.com/piwik/piwik/pull/11082
