### ISSUE TITLE
Auto-Update also deactivated plugins 

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11044]
Auto-Update also deactivated plugins 
because of 3 reason:
1. I'm note sure, if this time, there is an easy way to make a deactivated plugin active again when Piwik version got incompatible (because of Piwik update) during plugin was deactivated?
(see what happens in this case https://github.com/piwik/piwik/issues/11041)
2.  reduce number of problems when trying to activate a plugin (e.g. compatibility, bugs):
when having always the latest one installed, this should be the best available one.
3. maybe even deactivated plugins may influence security in some cases

**Comment by mattab** [comment]
@hpvd do you know if we currently check for new updates for deactivated plugins? we definitely should, I guess.

**Comment by hpvd** [comment]
I think Piwik doesn't check and doesn't update deactivated plugins -that's why I opened this issues...
(but as always I didn't check the code if it shouldn't do)
btw: merry x-mas!

**Comment by hpvd** [comment]
imho this is pretty important and one should not push this to the far future... (see the 3 reasons above)
What do you think?

**Comment by tsteur** [comment]
AFAIK and I had a rough look in the code we do check for all plugins here: https://github.com/piwik/piwik/blob/3.0.0/plugins/Marketplace/Plugins.php#L167-L169 This should include deactivated ones.

**Comment by hpvd** [comment]
Many thanks for looking in the code!

I just had a deeper look too:
You are right! It's no general problem.
Most are updated but not all.

e.g. in my installation AOM plugin is installed, but deactivated and it's not updated.
Noticed that there are several new versions by looking at it's github page.

Looking in Piwik's integrated Marketplace, I couldn't even find it anymore.
("huu... was it banned for some reason?")
Looking for it on https://plugins.piwik.org directly I managed to find it.
("hmm, why is there a difference to internal view?")

When looking into it's details I realized that it has requirements Piwik <3.0.0b1

So there is simply no compatibility version for Piwik 3.

**=> With this we need a better handling not for deactivated,
but for deactivated and not compatible anymore plugins.**

some ideas:
- should one update them even if latest version is not compatible to current piwik version (e.g. for security reason)?
- do not show "activate"-Link in list of installed plugins if not compatible to current version
- show a hint instead "not compatible to current piwik version" 
- do not make them disappear in internal marketplace view, make it transparent and show "not compatible for your piwik version"
- add a filter for plugin search "not compatible"/"other piwik versions" (so one can ask the author for an update...)

**Comment by mattab** [comment]
So it should already more or less work. AOM wasn't updated because there was no 3.0 compatible release at the time. Closing this issue @hpvd but feel free to open separate requests for your suggestions / the ones you think are most important.
