### ISSUE TITLE
plug in

### ISSUE THREAD

**Issue by cibler95** [piwik/piwik#11048]
Beaucoup de plug  in ne fonctionnent plus
le plug generator visitor, n'existe plus.... ?

**Comment by RMastop** [comment]
Hi @cibler95, please find the visitor generator here: https://plugins.piwik.org/VisitorGenerator

**Comment by cibler95** [comment]
hello

J'ai mis dans piwik/plugins/VisitorGenerator/data
un fichier *.log avec
 ./console visitorgenerator:generate-users --limit 100
./console visitorgenerator:generate-visits --idsite 1 --custom-piwik-url=http://jumelagedomont.fr

est-ce que c'es ok ?

Best regards

**Comment by RMastop** [comment]
Hi @cibler95,

The value that you would add to --custom-piwik-url, defines an alternate Piwik URL, e.g. if Piwik is installed behind a Load-Balancer.
Please run the script without the --custom-piwik-url option in it.

**Comment by cibler95** [comment]
Hi

don't function

visitorGenerator isn't run

./console visitorgenerator:generate-users --limit 100
./console visitorgenerator:generate-visits --idsite 1

Best regards
