### ISSUE TITLE
wrong message after deactivating plugin using link in fatal error message

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11045]
When seeing "Fatal error" message
and deactivating a plugin using a link within this message
seeing Piwik again, there is a positive message instead a negative one:

![2016-12-19_10h51_13](https://cloud.githubusercontent.com/assets/5681880/21309167/7150f6fc-c5dd-11e6-828b-89b7d3caaa17.png)

**Comment by mattab** [comment]
Couldn't reproduce this one. Maybe the message was queued from an earlier action
