### ISSUE TITLE
Fatal error: Cannot redeclare class after upgrade or installation of 3.0.0

### ISSUE THREAD

**Issue by zubfatal** [piwik/piwik#11054]
Initially I installed Piwik 3.0.0, worked fine although some widgets failed to render, throwing "Fatal error: Cannot redeclare class" errors.

I tried installing 2.17.1 and everything just worked, from within Piwik I attempted to upgrade to 3.0.0, which also worked, but again the same problems occurred.

From the dashboard of the tracked website:

**Visits over time**
`Fatal error: Cannot redeclare class Piwik\Plugins\CoreVisualizations\Visualizations\Graph in /var/www/clients/client1/web8/web/piwik2/plugins/CoreVisualizations/Visualizations/Graph.php on line 26`

**Visits overview**
`Fatal error: Cannot redeclare class Piwik\Plugins\CoreVisualizations\Visualizations\HtmlTable in /var/www/clients/client1/web8/web/piwik2/plugins/CoreVisualizations/Visualizations/HtmlTable.php on line 23`

**Referer types**
`Fatal error: Cannot redeclare class Piwik\Plugins\CoreVisualizations\Visualizations\HtmlTable in /var/www/clients/client1/web8/web/piwik2/plugins/CoreVisualizations/Visualizations/HtmlTable.php on line 23`

* Debian 8.6
* PHP 5.6.29 (php-fpm)
* MySQL 5.5.53
* nginx 1.6.2

**Comment by zubfatal** [comment]
Not sure what may have caused it, but I moved everything from the /piwik2 subfolder to the website root (/web) and everything seems to be working at the moment, so this issue is probably not applicable anymore?

**Comment by zubfatal** [comment]
Moved the contents of the subfolder (/web/piwik2) to web root (/web) and it worked fine for 2-3 hours but it seems the errors have begun to popup again.

**Comment by tsteur** [comment]
Maybe have a look at https://github.com/piwik/piwik/issues/10378

Is maybe opcache and xcache enabled?

**Comment by mattab** [comment]
As @tsteur pointed out, this sounds like a PHP cache issue. #10378

**Comment by zubfatal** [comment]
@tsteur @mattab you're both right - now I haven't been looking at this setup daily, just every now and then, and since i added the PHP setting `opcache.enable off` for the site, I haven't experienced these errors.

**Comment by orrumar** [comment]
Che significa? come posso risolvere??
Fatal error: Cannot redeclare class Requests in /home2/masterwe/Public_html/marketerstart.com/wp-content/plugins/Aliplugin/libs/Requests/Requests.php on line 21

**Comment by orrumar** [comment]
come posso risolvere errore Aliplugin/libs/Requests/Requests.php on line 21
