### ISSUE TITLE
Notice undefined index category warnings after upgrading to piwik 3

### ISSUE THREAD

**Issue by michelesbw** [piwik/piwik#11053]
Hello everybody here,
when switching to Personal settings I have 3 warnings as follows, I'm reporting as suggested (upgraded from very previous to latest 3.0.0):

    List item /plugins/ScheduledReports/Controller.php(64): Notice - Undefined index: category - Piwik 3.0.0
    /plugins/ScheduledReports/ScheduledReports.php(198): Notice - Undefined index: category - Piwik 3.0.0
    /plugins/ScheduledReports/ScheduledReports.php(197): Notice - Undefined index: category - Piwik 3.0.0

Also, email reports do not work neither automatically or manually (download or send now both not working)

Cheers

**Comment by MackieeE** [comment]
FYI @matthieu You asked here on the [forums](https://forum.piwik.org/t/notice-undefined-index-category-warnings-after-upgrading-to-piwik-3/22184) if they disappear after removing the notifications. Unfortunately they don't (See reload gif) 

![catagoryerror](https://cloud.githubusercontent.com/assets/883702/21347103/25404f52-c69f-11e6-95ef-7de758f0608b.gif)

**Comment by tsteur** [comment]
It looks like there is a plugin installed that is not compatible with Piwik 3. You may wanna go to "Administration => Plugins" and filter there for "Third-party" and disable one plugin after another until you found the incompatible plugins.

We automatically disable incompatible plugins but some plugins did not mark with which plugins they are compatible

**Comment by michelesbw** [comment]
Here's 1st finding: TasksTimetable (v3.0.1) disabled, reports work again (second problem highlighted above)

**Comment by michelesbw** [comment]
Nope, sorry, not true..I need more time for testing, sorry. The problem seems to be some of the items selected in reports: if I activate all of the report's fields I get: "Piwik encoutered an error: Call to a member function getMetadata() on boolean (which lead to: Call to a member function getMetadata() on boolean)"

**Comment by MackieeE** [comment]
@tsteur Well luckily for me it was quite straightforward as I had only one Third-party plugin ;) 

Disabled ***IP2Location Plugin*** and no-more error messages. I suppose this isn't a bug for Piwik per-say?

Cheers,
Rob.

**Comment by michelesbw** [comment]
I can confirm it was IP2Location Plugin v2.3.0 now updated to 2.3.2. Closing this issue, thanks everybody!
