### ISSUE TITLE
Piwik stopped tracking after update to 3.0.0

### ISSUE THREAD

**Issue by ModemMisuser** [piwik/piwik#11059]
As title says, my Piwik installation simply stopped tracking after update to 3.0.0.  I've been running for 5+ years...never had this problem with an update before.

**Comment by tirami5u** [comment]
I had the same issue but saw, that no the whole tracking stopped but the graph of daily visitors, visitor summary and so on. I only get a flat line. The User log still works and shows new visitors. So I hope not all data gets lost and a bugfix release can restore the lost information in the mean time.
![piwik-flatline](https://cloud.githubusercontent.com/assets/24698536/21391160/b44ff88c-c78a-11e6-9d36-38a99a012c7e.png)

**Comment by ModemMisuser** [comment]
Not on my installation.  Everything is dead.  No tracking at all.

**Comment by tirami5u** [comment]
I have to correct myself - I checked it again and do not see any user activity any more.

**Comment by RMastop** [comment]
anyting mentioned in logfiles, that might help debugging these cases?

**Comment by ModemMisuser** [comment]
I am on commercial hosting and therefore don't have access to logs.

**Comment by RMastop** [comment]
please request the logfiles for your site. it might help you and others.

**Comment by RMastop** [comment]
together with the logfiles provide environment details, php version, OS version, MySQL version, etc.

**Comment by ModemMisuser** [comment]
I can try but the chances are between "not going to happen" and "never f'ing going to happen, now go away" that I'll be able to get access.

**Comment by ModemMisuser** [comment]
Piwik version: 3.0.0
MySQL version: 5.6.31
PHP version: 5.6.27 

OS: 
FreeBSD xxxxx.pair.com 8.2-STABLE FreeBSD 8.2-STABLE #0: Tue May 31 14:36:14 EDT 2016     xxxxx@xxxxx.pair.com:/usr/obj/usr/src/sys/82PAIRx-AMD64  amd64

**Comment by tirami5u** [comment]
I have some logs, find them as attached - but this is all I got from 2016! Piwik worked without any problem until 3.0.0.

System Check has only one warning:

>  	LOAD DATA INFILE
Die Benutzung von LOAD DATA INFILE erhöht die Geschwindigkeit des Piwik Archivierungsprozesses erheblich. Um dies für Piwik verfügbar zu machen setzen Sie bitte eine neuere PHP & MySQL Software ein und stellen Sie sicher, dass der gewählte Datenbankbenutzer das FILE Recht besitzt.
Falls Ihr Piwik Server Websites mit erhöhtem Verkehrsaufkommen (z.B.: > 100.000 Seiten pro Monat) verarbeiten muss empfehlen wir dieses Problem zu beheben. 
> 

System:
CentOS 6.8 (Final)‬
PHP 7.0.14 (checked 5.6.x aswell, same result)
MySQL 5.1.73
Using HTTPS

[logs.txt](https://github.com/piwik/piwik/files/666518/logs.txt)

**Comment by RMastop** [comment]
What about the piwik/tmp/logs/ logfiles?  
do you have access to these?

Did you try to clean up the cache files after the upgrade (piwik/tmp/cache)?

**Comment by ModemMisuser** [comment]
piwik/tmp/logs/ is empty. (Just index.htm and php).

I cannot clean up the cache files, as they are owned by the webserver process (nobody/users on FreeBSD), so I can't perform any operations on them via an SSH session.  (I hate this, but it's how webservers run nowadays, for security.)

**Comment by tirami5u** [comment]
This log directory is empty. Cache is cleaned. No change.

![tmp-logs](https://cloud.githubusercontent.com/assets/24698536/21393308/24424ba0-c794-11e6-8370-27a130936741.png)

**Comment by ModemMisuser** [comment]
Also - it's likely all 3 of the issues I've reported are related.  Could you take a look at the other two?  (They should be listed right near this one, as there isn't much activity here.)

**Comment by tsteur** [comment]
Can maybe someone have a look at the console in the browser developer tools? Is there maybe an error? From which version did you all update?

**Comment by ModemMisuser** [comment]
I can't recall what version I updated from.  I was behind probably one minor release.   So probably I was on 2.17.0.

What "browser developer tools?"

**Comment by mattab** [comment]
Are you using any "Third party plugins" not created by "piwik? ? if so try to disable them.

If that does not work for sure you can find the problem by debugging the tracker as documented here: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker

**Comment by ModemMisuser** [comment]
No, I'm not using any 3rd party plugins.

I'll have a look at that guide, but if you also see my other open issues, I think you'll see I have a much larger problem. :/

**Comment by tsteur** [comment]
Maybe send us a link to your website to hello at piwik.org and we can have a look at the console to see if there is a JavaScript error

**Comment by ModemMisuser** [comment]
I will do that right now.

I'll also mention that if you'd like, I can give you the info to login to my piwik admin.  This problem is maddening.  :)

**Comment by ModemMisuser** [comment]
Note that if you check now you'll find nothing as I just removed the tracking code.  Since I can't fix this, I suppose piwik will have to go.

**Comment by tsteur** [comment]
Could you maybe temporarily add it again? I'd have a look quickly

**Comment by tsteur** [comment]
Noticed it is still there. Tracking integration looks good to me and it did send a tracking request, so it must be something on the server side. We'd need access to the Piwik server and the logs to investigate what happened there.

**Comment by necalex** [comment]
Same problem, but only if you use filters.

**Comment by mattab** [comment]
Can you please "Troubleshoot the piwik tracker" as explained here: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker 

What error message do you see in the output?

**Comment by Presskopp** [comment]
I have the same issue. I got it working again, and then it stopped again. Because I have many plugins/customizations, I'm unable to recall all the steps I did, but there is no error showing up at all, not in console (Debugging the Tracker), not in logs, everything seems fine, connection to piwik works, but it just stopped showing results. After trying for days now on my own, I'm posting here. If there is anything more I can do, let me know.
![piwik_issue](https://cloud.githubusercontent.com/assets/18373563/21548365/38492322-cdec-11e6-828c-ea8cbf651a34.jpg)

**Comment by mattab** [comment]
@Presskopp Are you seeing data in the visitor log? if so, data is tracked correctly. Then are you seeing any error in the `core:archive` cron output ?

**Comment by mattab** [comment]
see https://github.com/piwik/piwik/issues/11059#issuecomment-269161861

**Comment by tirami5u** [comment]
Even with Degubbing is on as described, the issue can not be found on my side. 
I deactivated all Plugins that did not come with PIWIK Core > No change
I reinstalled PIWIK 3.0.0 > No change
It is really confusing, that tracking seems to work but some reports are all 0 and the visitors line is flat - even if the visitor log on the left seems to record all visitors correctly (see screenshots).

Any further suggestions? Can I rollback to PIWIK 2.x ?

![piwiktracking](https://cloud.githubusercontent.com/assets/24698536/21613008/c41bd418-d1d3-11e6-8239-68614a1339c3.png)

![piwiktracking2](https://cloud.githubusercontent.com/assets/24698536/21613009/c41e9b62-d1d3-11e6-8b24-f873b9cb92df.png)

**Comment by mattab** [comment]
Since you have visitors in your visitor log, your data is being tracked. Likely the problem occurs with the archiving. Please setup auto archiving as per: http://piwik.org/docs/setup-auto-archiving/ and then check any error message that the archiver outputs?

**Comment by Presskopp** [comment]
I have no visitors (while there sure are some!) and therefore no peaks to see. Tracking code is to find in sourcecode like original, I can do whatever, I can produce no errors. Could be my fault in some way, I just can't detect the cause :( FYI: All is over https.

I ran https://your-server.org/path/to/piwik/misc/cron/archive.php?token_auth=XYZ and it gave my some output, excerpt:

```
 START
 Starting Piwik reports archiving...
 - no new tracking data for website id 1 since 2017-01-03 20:45:31 UTC (since the last successful archiving)
 Skipped website id 1 as archiving is not needed
 Done archiving!
 ---------------------------
 SUMMARY
 Total visits for today across archived websites: 0
 Archived today's reports for 0 websites
 Archived week/month/year for 0 websites
 Skipped 1 websites
 - 1 skipped because no new visit since the last script execution
```

**Comment by tirami5u** [comment]
YES! It was simply the wrong PHP version I used to run the cronjob. Seemed it worked prior to PIWIK 3.x but not after updating to 3.x - THANKS
