### ISSUE TITLE
Keywords garbled problem

### ISSUE THREAD

**Issue by fanyoujian** [piwik/piwik#11056]
How to solve the problem of garbled keywords?

**Comment by sgiehl** [comment]
what exactly do you mean with garbled keywords? Is the encoding of the keywords broken? Maybe you could post a screenshot to make clear what exactly your problem is

**Comment by mattab** [comment]
Hello @fanyoujian 
As we haven't heard more information from you i'm closing this issue. feel fre to post more info and re-open
