### ISSUE TITLE
Widgetized Dashboard accessed with token is no longer working after updating to 3.0

### ISSUE THREAD

**Issue by aguarsk** [piwik/piwik#11055]
Hi!

I just updated to version 3.0 but I had a widgetized Dashboard accessed with the token as a parameter in the link, like this: http://www.webpage.com/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=5&period=week&date=yesterday&token_auth=TOKEN

Dashboard opens, but all the widgets in it says that you can access it, that it is required a view access to the internet site. And tells me to log in.

This was working perfectly before the update, the user (with the token) has the view privileges to the site.

Any help will be appreciated, thanks!

**Comment by aguarsk** [comment]
UPDATE:

In the 3.0 Piwik changelog says:

    ### New APIs

    * The JavaScript AjaxHelper has a new method `ajaxHelper.withTokenInUrl()` to easily send a token along a XHR. Within the Controller the existence of this token can be checked via `$this->checkTokenInUrl();` to prevent CSRF attacks.

Also, in the core controller's principal class (core/Plugin/Controller.php), the new API function says:

    /**
     * Checks that the token_auth in the URL matches the currently logged-in user's token_auth.
     *
     * This is a protection against CSRF and should be used in all controller
     * methods that modify Piwik or any user settings.
     *
     * If called from JavaScript by using the `ajaxHelper` you have to call `ajaxHelper.withTokenInUrl();` before
     * `ajaxHandler.send();` to send the token along with the request.
     *
     * **The token_auth should never appear in the browser's address bar.**
     *
     * @throws \Piwik\NoAccessException If the token doesn't match.
     * @api
     */
    protected function checkTokenInUrl()

But, there are are ajax petitions (ajaxRequest.send) in the Dashboard plugin javascript (plugins/Dashboard/javascripts/widgetMenu.js) that do not invoke the token.
If I add what the new API suggests, it works, the problem is know in which other plugins have the same problem.

**Comment by mattab** [comment]
Thanks for the report @aguarsk - maybe you could submit a pull request to solve (or partially solve) this issue ?

**Comment by mattab** [comment]
This will be fixed in the next release 3.0.1-b3

**Comment by aguarsk** [comment]
Thanks, guys.
