### ISSUE TITLE
 PIwik 3.0.0 Core Plugin “UserCountry” Error

### ISSUE THREAD

**Issue by Chriz1083** [piwik/piwik#11057]
Hi,

I use:
Piwik Version: 3.0.0
MySQL Version: 5.5.53
PHP-Version: 5.6.29-0+deb8u1 

After I upgrade Piwik to v3.0.0, I get some errors.

I have to disable the Core Plugin "UserCountry" because, if i activate this Plugin, Piwik stops the tracking.

When the Plugin is activated, in the php Error Log I get the Error:

`PHP Fatal error: Cannot redeclare class Piwik\Plugins\UserCountry\LocationProvider\DefaultProvider in [...]/piwik/plugins/UserCountry/LocationProvider/Default.php on line 0`

So, I have to deactivate the Plugin. With that, Piwik is tracking the website user. Without that, if the plugin is active, Piwik determines the tracking of the website User.

Also, if the UserCountry Plugin is activated, I can't access the following pages in Piwik:
- Administration > Geolocation
- Administration > Systemcheck

I only got a blank page.

FYI:
since the Update, I also get this PHP Error Message sometimes:

`PHP Fatal error:  Call to undefined method Piwik\Plugins\CorePluginsAdmin\CorePluginsAdmin::isMarketplaceEnabled() in [...]/piwik/plugins/CorePluginsAdmin/Tasks.php on line 1`

PS:
Piwik 3.0.0 works only, when I uncomment in all .htaccess Files the last line:
`#Options -Indexes`
Without that, I can't see anything at the pages.

**Comment by mathomp4** [comment]
I am also seeing this same error on my newly update Piwik 3.0.0 instance and can confirm I can see the System Check again with UserCountry (and UserCountryMap) plugins disabled. 

As I'm not really a power user of Piwik, all I can really add is: I miss the map. :)

**Comment by tsteur** [comment]
For the IsMarketplaceEnabled problem please delete the file `piwik/plugins/CorePluginsAdmin/Tasks.php`. It should not be there anymore.

For redeclare class maybe have a look at https://github.com/piwik/piwik/issues/10378 . Does this help?

**Comment by mathomp4** [comment]
@tsteur, as I've said, I'm not a web guru or anything (mainly a Fortran programmer), but I took a look at #10378 and as near as I can tell, my php instance has OPcache enabled, but xcache is not. So I'm not hitting that. (Well, as far as I can decode Dreamhost and my phpinfo page.)

I guess the next question is how do I know if there is another cacher on? I see in my global.ini.php file that there is a [Cache] section, and backend is set to "chained". Should I fiddle with that? Or with RedisCache? (I looked in config.ini.php and I saw no cache in that file at all.)

**Comment by Chriz1083** [comment]
@tsteur 
Thank you! Deleting the file
`piwik/plugins/CorePluginsAdmin/Tasks.php` 
solves the "IsMarketplaceEnabled" Problem.

No, the #10378 doesn't fix my UserCountry Problem. I only use opcache.

But I have had a look at the piwik files at github and I saw that here at github is no file like 
`/piwik/plugins/UserCountry/LocationProvider/Default.php`

So, I delete this file also and my problems are fixed now.

Thank you very very much for your help!
Greetz

**Comment by mathomp4** [comment]
Ah. Yup. That gets rid of the error for me too. I'm wondering if the upgrade to 3.0.0 also should require a find command to remove files that are old and no longer part of Piwik?

Also, my Country Map doesn't seem to be working at the moment (stuck at loading map) but it might be one of those "Wait 24 hours" things?

**Comment by tsteur** [comment]
Piwik automatically deletes no longer needed files usually but there may be problems when there are no write permissions for Piwik to delete the files. In this case we would need to ideally show a list of commands after installation so users can copy paste and delete it. 

Re the map and  the redeclare class feature it is hard to tell without being able to debug on the server. Maybe you can give us access to your server and to Piwik?

**Comment by Chriz1083** [comment]
@tsteur 
In my case, I update Piwik manually. I can't update it automatically because I have many Website in Piwik and it's better for me to update manually to avoid Errors.

When I do the update, I download the latest piwik.zip and unzip it directly on the Server. But If I only unzip the new files, the old wouldn't deleted. I don't know If Piwik would delete the old files, when I make the update over the Piwik Backend automatically, but this is no way for me.

But now, I knew that there can be problems after update Piwik manually, if there are old files in the Piwik directories and that I have to check it after every update. And if there are problems, I have to compare the files on my server with the files at github.

@mathomp4 
Wait a little bit. But I think that you can already see some data at the County Map now.

**Comment by mattab** [comment]
At some point we'll make the System check display all files that are there but should be deleted: https://github.com/piwik/piwik/issues/11087

**Comment by mathomp4** [comment]
@Chriz1083 Well, I eventually got the maps working. I'm not sure how, but I guess just clicking buttons and turning things on and off works. *shrug*

@mattab That sounds great, especially as I upgrade with the unzip method on your site. I'm guessing it's not quite as robust during big updates like 2->3. My install is pretty boring so I'm guessing I could do a diff between piwik.zip expanded and my current install and figure out what is old and unneeded...but an automatic tool would be great!

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/cannot-declare-class-piwik-plugins/49153/3
