### ISSUE TITLE
Error in middle box on admin main page

### ISSUE THREAD

**Issue by ModemMisuser** [piwik/piwik#11060]
After update to 3.0.0, in the middle box of the main admin page, between "System Summary" and "Need Help?," there is a box with "Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance." - I don't know what's supposed to be in that box, but I doubt it's that error. :)

**Comment by tsteur** [comment]
There is supposed to be shown a summary of the system check. Can you go to "Administration => System Check" and see if everything is alright there?

**Comment by ModemMisuser** [comment]
Oh dear.

That renders a totally blank page.  (And view source is empty as well.)

**Comment by ModemMisuser** [comment]
Interestingly, in the other open Issue regarding UserCountry (opened by another person) it was mentioned about System Check not working.  I tried disabling UserCountry and... that makes System Check work for me, too.

**Comment by tsteur** [comment]
Can you maybe also have a look at https://github.com/piwik/piwik/issues/10378 to see if there is opcache and xcache enabled maybe? Maybe your hoster lets you view a "php info" or  something

**Comment by ModemMisuser** [comment]
As near as I can tell, from running phpinfo(), no.

**Comment by mattab** [comment]
When you have UserCountry enabled, and open system check, do you see anything in the HTML source code of the blank page? 

Or in your web server error logs?
