### ISSUE TITLE
Numerous errors in admin after update to 3.0.0

### ISSUE THREAD

**Issue by ModemMisuser** [piwik/piwik#11061]
After update to 3.0.0, on the top of the main admin page, I have numerous errors of the form:

"WARNING: /usr/www/users/pazuzu/piwik/plugins/Goals/Reports/BaseEcommerce.php(56): Notice - Undefined index: idSites - Piwik 3.0.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)"

I did search, and have not found this reported yet.

**Comment by tsteur** [comment]
I think that file should not exist and was deleted > 2 years ago. It should be fine to just delete that file.

**Comment by ModemMisuser** [comment]
... seriously?  Ok.  Heh.  BaseEcommerceItem.php and BaseGoal.php too, then, I ass-u-me?

**Comment by tsteur** [comment]
Yep :)

**Comment by ModemMisuser** [comment]
Actually, doing that makes piwik lock after displaying...

"Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance. "

**Comment by tsteur** [comment]
Sorry, forgot to mention you likely need to empty the "tmp/cache" folder in piwik.

**Comment by gaumondp** [comment]
I'm pointing finger @tsteur (but in a friendly way) by mentioning this:

https://github.com/piwik/piwik/issues/6402#issuecomment-61534217

IMHO, clearing cache should happen at Piwik's update, upgrade and every time you add or remove a plugin...

**Comment by tsteur** [comment]
I know, in this case the file was removed manually from the file system

**Comment by ModemMisuser** [comment]
Which of course is impossible, since this is running on normal commercial hosting, thus the files are all owned by the webserver process (in this case, nobody/users).  This is just how commercial hosting works, for security.

**Comment by tsteur** [comment]
Sometimes there are "tools" where you can enter a path to delete a directory or it lets you browse the files? Is there no way to remove the files from a directory for you? You may want to ping that hoster to add such functionality.

**Comment by bluikko** [comment]
I had this problem as well, and additionally QueuedTracking is not working with error:

**Comment by Findus23** [comment]
@tsteur, There are more people having the same issue:
https://forum.piwik.org/t/warning-after-update/24748
https://forum.piwik.org/t/undefined-index-idsites-piwik-3-0-2/23571

It seems like all of them are updating from a 2.x version that isn't 2.17. Is it possible there is an bug in the updater?

**Comment by tsteur** [comment]
It is not really a bug. The feature to also update plugins with the core was only added in 2.17. or so. Updating from an earlier version won't update the plugins automatically and may cause trouble.

**Comment by Findus23** [comment]
Maybe it would be helpful in the future if updating to piwik 4 was only possible from the latest 3.x and the updater would only do it in two steps. 
I feel like most of the "the-update-broke-piwik"-issues happen to people who update from older 2.x versions.

**Comment by tsteur** [comment]
yeah be good probably. We'd need to see how to implement that when refactoring the updater in https://github.com/piwik/piwik/issues/5985 as there are a couple of "problems" with the updater
