### ISSUE TITLE
Downloads are not displayed hierarchically

### ISSUE THREAD

**Issue by tfrdidi** [piwik/piwik#11069]
I use Piwik 3.0.0, and had some of the previous versions, too. I use it without JS tracking, just by importing server logs. Now I need information about which file is downloaded the most. The problem with the downloads overview is, that "hierarcical" view only groups the url of the site, not the path of the file.

This it what is grouped hierarchically:

```
my.site.com/
direcotry/asdfasdf/jklö/download1.pdf
direcotry/asdfasdf/jklö/download2.pdf
direcotry/asdfasdf/jklö/download3.pdf
```

This is what I would expect (same as for the visited sites):

```
my.site.com/
  + directory/
     + asdfasdf/
         + jklö/
             download1.pdf
             download2.pdf
             download3.pdf
```

**Comment by mattab** [comment]
Hi @tfrdidi - this works like this by design.

**Comment by tfrdidi** [comment]
What is the reason to have different behaviours for those similar reports? I have a site with very long download paths. Hence there is no possibility except exporting it to a file, to see which file is listed because I can only see the first part of the URL. Maybe I missed some setting to fix this, but this does not feel like the right behavior for me.

**Comment by mattab** [comment]
Do you mind opening a new issue @tfrdidi about the problem that you cannot see the full URL/path names? we can probably solve it separately but likely we will keep the structure as it currently is.

**Comment by tfrdidi** [comment]
Would you mind explaining why you want to keep the structure as it is? For me there is technically no difference between downloads and page visits, but you handle it differently.
