### ISSUE TITLE
Visitor log says " Mysqli prepare error: Unknown column 'log_link_visit_action.interaction_position' in 'field list' "

### ISSUE THREAD

**Issue by billtzim** [piwik/piwik#11073]
When clicking on the Visitor Log menu the following error is displayed and nothing else
 Mysqli prepare error: Unknown column 'log_link_visit_action.interaction_position' in 'field list' 

Searching through the code i see that piwik 2.17.1 and 3.0 have a difference in the file plugin/Live/Model.php in line 56 where the 'log_link_visit_action.interaction_position' does not exist based on the database schema (looked in /core/Db/Schema/Mysql.php)

**Comment by mattab** [comment]
Duplicate https://github.com/piwik/piwik/issues/11074
