### ISSUE TITLE
Dropdown menu becomes hidden inside the widget

### ISSUE THREAD

**Issue by KaanErturk** [piwik/piwik#11070]
The UI element referenced as a `card widget` (DIV classes), one that has the **Change visualisation** option, has a bug.

When you select **Insights** from the dropdown menu, the next time you open it it becomes hidden (or contained perhaps) inside the widget area. You need to scroll down (inside the widget) to see it. Other options do not cause this, regardless of in what order you select them. You need to change it back to one of the other options and then refresh the page (or go to another one and then back) to fix it. If you keep the **Insights** option selected, the dropdown menu is always hidden inside the widget, even after a page refresh.

Here it works as expected.

<img width="435" alt="screen shot 2016-12-22 at 19 07 18" src="https://cloud.githubusercontent.com/assets/77985/21437181/5476a898-c87a-11e6-9d51-5c058275ee20.png">

It is again working as expected after you select an option other than **Insights**.

<img width="388" alt="screen shot 2016-12-22 at 19 07 44" src="https://cloud.githubusercontent.com/assets/77985/21437207/6ff663a6-c87a-11e6-9ec2-e4a7241a77b7.png">

This is what you see after you select **Insights**.

<img width="379" alt="screen shot 2016-12-22 at 19 08 01" src="https://cloud.githubusercontent.com/assets/77985/21437239/9d321590-c87a-11e6-899b-b9d692e8e018.png">

And you have to scroll down inside the widget to see the full dropdown.

<img width="375" alt="screen shot 2016-12-22 at 19 08 20" src="https://cloud.githubusercontent.com/assets/77985/21437243/a6f1307a-c87a-11e6-90c7-05195e7d5ab4.png">

Piwik version is 3.0.0.

**Comment by mattab** [comment]
Thanks for the report @KaanErturk 

If you can, a pull request would be very appreciated :+1:

**Comment by KaanErturk** [comment]
I'll see what I can do.

**Comment by mattab** [comment]
Duplicates https://github.com/piwik/piwik/issues/10605
