### ISSUE TITLE
Visitors Log Does Not Show Any Data

### ISSUE THREAD

**Issue by oschino** [piwik/piwik#11072]
When accessing Visitors->Users, no matter the time-frame selected "There is no data for this report." 
This occurred after upgrading to 3.0.0

**Comment by KaanErturk** [comment]
Happening on my fresh install of Piwik 3.0.0 too.

**Comment by necalex** [comment]
Same problem, but only if you use filters. (Piwik 3.0.0)

**Comment by mattab** [comment]
Can you please "Troubleshoot the piwik tracker" as explained here: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker 

What error message do you see in the output?

**Comment by mattab** [comment]
let's continue discussion in: https://github.com/piwik/piwik/issues/11059#issuecomment-268993378
