### ISSUE TITLE
Unique visitors are displayed/processed wrongly when amount is bigger than 1000

### ISSUE THREAD

**Issue by phip1611** [piwik/piwik#11090]
**Problem**
Unique visitors are displayed/processed wrongly when amount is bigger than 1000

**Since / Version**
I noticed this bug first yesterday, I think it's since the upgrade to **Piwik 3**.

**What works**
View unique visitors for a timespan where unique visitors amount is **smaller than** 1000.

**What doesn't work**
View unique visitors for a timespan where unique visitors amount is **bigger than** 1000.
For example piwik displays "4" instead of something like "4xxx" as unique visitors count. I first thought this is a problem by custom timespanes but now I'm sure the bug occurs when the amount is bigger than 1000. **It crops the last three digits.**

<img width="987" alt="bildschirmfoto 2016-12-26 um 12 51 56" src="https://cloud.githubusercontent.com/assets/5737016/21481773/e5be4a24-cb6b-11e6-885a-206cc564bb41.png">

**Comment by mattab** [comment]
Thanks for the report @phip1611 

Below the graph, when you export the data eg. as XML, do you see the correct nb_uniq_visitors metric data in the export?

**Comment by phip1611** [comment]
I didn't even know that export is a feature at that place. Neat, thanks!

No I can't reproduce it there because the export-feature works on a statistics per day base but I don't have a single day with >999 unique visitors.

**Comment by mattab** [comment]
@phip1611 you can replace `period=day` by `period=month` in the export url to see monthly data etc

**Comment by phip1611** [comment]
1. there are two "period"-parameters in the url (the last one overrides the first one)
2. it seems to work there! Data is displayed properly

**Comment by mattab** [comment]
I can reproduce this bug on the demo when setting language to German here: https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&updated=1#?idSite=7&period=month&date=2016-12-26&category=General_Visitors&subcategory=General_Overview
