### ISSUE TITLE
Wrong data in stats after trackEcommerceOrder 

### ISSUE THREAD

**Issue by netslovdlyasnov** [piwik/piwik#11092]
Hello.
Here is the process:
_paq.push(['addEcommerceItem',	'1', 'item1', false, 100, 20]);
_paq.push(['addEcommerceItem',	'2', 'item2', false, 200, 30]);
till now everything looks ok in stats. ( views, price and everything else, including items and quantity of items in abandoned cart)
after
_paq.push(['trackEcommerceOrder', '1111', 8000]);
Order is created, revenue is ok, but quantity of items is zero, and product purchases are not updated.
Purchases of products are zero.
I am using latest piwik 3.0.0, clean install.

**Comment by mattab** [comment]
Hi @netslovdlyasnov 

Before you call `trackEcommerceOrder` , you must again call `addEcommerceItem` for each item in the cart. This is how the ecommerce tracking works, see https://piwik.org/docs/ecommerce-analytics/#tracking-ecommerce-orders-items-purchased-required
