### ISSUE TITLE
dashboard: define a standard pattern for heights of widgets

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11105]
dashboard: define a standard pattern for heights of widgets and make it obligatory.
=> with this dashboard would look more beautiful/professional

At this time there are many different heights of widgets used
please see attachments (each color is a different height)

![2016-12-27_15h58_38](https://cloud.githubusercontent.com/assets/5681880/21502309/30332186-cc4f-11e6-85e8-da7b186410aa.png)

![2016-12-27_16h00_35](https://cloud.githubusercontent.com/assets/5681880/21502315/37256c2e-cc4f-11e6-99ab-8c792f2bbe8c.png)

**Comment by mattab** [comment]
Thanks for suggestion. It won't be possible since we have so many different styles of widgets and reports and it wouldn't look good or be possible to make them same height

**Comment by hpvd** [comment]
@mattab 
sorry I was not clear enough.
Of course this was not about making everything the same height.
It was meant to purpose to define a pattern of different standard heights e.g. 125px, 250px, 375px, 500px
With this every widget developer can choose the next best matching height.
The results:
instead of making a widget 237px it would be build with a height of 250px.
And instead of 127px one may easily find a way to make it work with 125px.

=> what do you think of this?

**Comment by mattab** [comment]
the widgets would always have many different height depending for example on how many rows are in the table, or how many metrics are defined as sparklines by a given plugin etc.
