### ISSUE TITLE
feature request: the mapping from two letter country code to the country

### ISSUE THREAD

**Issue by d2two** [piwik/piwik#11109]
Hi here,
    for now, the mapping from two letter country code to the country in HTTP Tracking API is not available, which means, given a country, I cannot figure out the corresponding two letter country code. Hope there is a list or standard to show the mapping. thanks a lot : )

**Comment by mattab** [comment]
Thanks for the suggestion. We'll try to work on this one in the future :+1:

**Comment by mattab** [comment]
@d2two Could you please let us know all use cases where you need this mapping / where you use country codes?
