### ISSUE TITLE
After Update to 3.0 piwik does not work

### ISSUE THREAD

**Issue by snowysandro** [piwik/piwik#11118]
After Updating to Piwik 3.0 the interface of piwik is not working any more,
I have also tried to reinstall piwik (deleted also all mysql tables)

The Pictures don't load any more :/
Webhosting: World4you
PHP Version 5.6.29
![piwik](https://cloud.githubusercontent.com/assets/11328935/21566434/440cbaea-cea3-11e6-9a58-6891628d0c4f.png)

**Comment by mattab** [comment]
Please try upgrade to 3.0.1-b2: http://piwik.org/faq/how-to-update/faq_159/

If not working, check your error logs for an error message?

Closing now but please reopen if you still have the issue in beta2

**Comment by snowysandro** [comment]
it is not possible to upgrade through the interface because it doesn't load the interface correctly 
![piwik](https://cloud.githubusercontent.com/assets/11328935/21607929/9ce2dd66-d1b9-11e6-9cf3-017c4dce8f0f.png)

**Comment by mattab** [comment]
@snowysandro can you check your web server error file? there is likely an error there. If you are on IIS please upgrade to 3.0.1-b2 where we fixed an issue: http://piwik.org/faq/how-to-update/faq_159/
