### ISSUE TITLE
Exported exit pages are not complete

### ISSUE THREAD

**Issue by responseinformationsdesign** [piwik/piwik#11137]
Using Piwik 3.0.0
Actions -> Exit pages
If there are more entries than 98, the exported TSV (Excel) is not complete. There are always just 98 entries. 
Same by exporting as CSV.

**Comment by mattab** [comment]
You need firstly to select "All" in the bottom right corner. 

Or alternatively edit the URL and set `filter_limit=-1`

**Comment by responseinformationsdesign** [comment]
I tested _both_ possibilities. Nothing works. I can still not export more than 98 entries.

**Comment by RMastop** [comment]
Hi @responseinformationsdesign,

Please add the following to the export URL:
`&filter_limit=-1&flat=1`
By default only the top level results are exported, by adding flat=1 it will drill down the result set and include all available results from the report.
Please be careful when using filter_limit=-1, it might be better to use filter_limit and filter_offset if the dataset is too large.
