### ISSUE TITLE
Language changes not respected within login screen

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11133]
We set Piwik to German language long time ago.
These days we set it back to English since this makes bugreports etc much easier.
-> everything is in English now :-)
=> login screen keeps German :-(

(different browsers, browser cache is set to disabled)

**Comment by Findus23** [comment]
After some testing it seems like the anonymous user's language is set by the language setting of the browser.
If the anonymous user is allowed to view the site (like on https://demo.piwik.org/), there is a language selector, which sets a cookie to override this detection similar to this:
```
piwik_lang=language%3DczoyOiJlbiI7%3A_%3D7da9ca0e02170d0e0d5412a70a3f64690822c55e
```

**Comment by mattab** [comment]
Yes that's expected that login form is displayed in the user's language as detected from browser :+1:
