### ISSUE TITLE
UsersManager API calls lead to incorrect error messages

### ISSUE THREAD

**Issue by c-prompt** [piwik/piwik#11138]
On both Piwik versions 2.17.1 and 3.0.0, the following API call leads to an error message "Please specify a value for 'email'."

`index.php?module=API&method=UsersManager.addUser&userLogin=testme&password=!@#Testme123&email=testme@gmail.com&alias=testme&format=PHP&token_auth=token_goes_here
`

Moving the `&password=!@#Testme123` to the end of the API call leads to an error message "The password length must be greater than 6 characters."

**Comment by mattab** [comment]
You need to URL encode each parameter, including the `password` parameter.

**Comment by c-prompt** [comment]
My mistake - thanks for catching that @mattab.
