### ISSUE TITLE
multiple idvisitors per single idvisit

### ISSUE THREAD

**Issue by heekyungyoon** [piwik/piwik#11141]
I thought there should be only one idvisitor matched for single idvisit.

However, there are more than 10 cases where multiple idvisitors exist for single idvisit in log_link_visit_action table.

Idvisitor changed as soon as user signed up, so I checked if the idvisitor occured right after signed up existed before the event. But, it wasnt'. The idvisitor occued for the first time there.

Is it possible?

**Comment by mattab** [comment]
Yes it's possible, when for example visitors delete cookies but the fingerprint will still match the same visit - and Piwik will keep the last idvisitor updated in the visit. Works as expected. Btw recently I wrote this FAQ to explain in more details how tracking works: http://piwik.org/faq/general/faq_21418/
