### ISSUE TITLE
Plugin Filter "third party" shows several plugins with author "piwik"

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11145]
Plugin Filter "third party" shows several plugins with author "piwik"
that's somehow irritating....
(piwikPro should be fine)
please see attachment

![2017-01-04_13h17_34](https://cloud.githubusercontent.com/assets/5681880/21642161/c55954ec-d280-11e6-96a8-14ec243651ec.png)

**Comment by sgiehl** [comment]
Those plugins are listed there as they are not bundled with core. Not sure if would make sense to have an extra category "official plugins" or something like that to sort them in there.

**Comment by hpvd** [comment]
..thought something like this was the reason.
Stumbled across this because if you doesn't know the background it looks messed up / broken
("Piwik" is not third party for average user)

**Comment by tsteur** [comment]
That's a good point actually. Either we should rename it to "Non-Core" or add a "Non-Core" on top. Then for "Non-Core" it would work as it does currently for "Third-party" and "Third-Party" would not show any Piwik or InnoCraft plugins.

**Comment by hpvd** [comment]
what do think of:
All | Core | Piwik Special | All 3rd-party | All Premium

where "Piwik special" is "additional Plugins from Piwik" (but this ist to long)
- I'm not perfectly happy with "non core", because imho even 3rd-Party Plugins are "non core"...

**Comment by hpvd** [comment]
having also "Premium" filter here even when there are no premium plugins installed, may help further to give theme more visibility...
if there is no Premium plugin installed one could show a link to them...

**Comment by mattab** [comment]
Thanks @hpvd for this suggestion :+1:
