### ISSUE TITLE
can not add new website

### ISSUE THREAD

**Issue by skasberger** [piwik/piwik#11140]
i can not add a new website to my website. the website management page trys to load all 22 websites, but then stops and non website gets enlisted. have changed php version from 5.5 to 5.6 and 7.0. my piwik instance is installed on a hosted server, so i have no root access.
![screen](https://cloud.githubusercontent.com/assets/1374253/21625295/469d9c14-d20b-11e6-9cd8-44a3a5ac7676.jpg)

**Comment by skasberger** [comment]
here also a screen from the system check page: 
![screen-2](https://cloud.githubusercontent.com/assets/1374253/21625419/de44837a-d20b-11e6-9906-026e07af26a9.jpg)

**Comment by skasberger** [comment]
have fixed the issue on my server with changing the folder rights of all folders+files in the plugins folder to 755 recursevily.

**Comment by mattab** [comment]
Thanks for the report and solution @skasberger - I think it was also explained in FAQ: https://piwik.org/faq/troubleshooting/faq_19489/

**Comment by mattab** [comment]
Actually I meant this FAQ: https://piwik.org/faq/troubleshooting/faq_135/
