### ISSUE TITLE
No link to "backend-start-page" in "backend-menu"

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11143]
since start page of admin backend gives a good and interesting overview, shows news etc. (and also advertise Premium plugins and possibility for donation...)
it should **be accessible** and with this also **be visible** directly via link site menu.
And not only via link in right head...

please attachment

![2017-01-04_12h58_16](https://cloud.githubusercontent.com/assets/5681880/21641737/16bcd0dc-d27e-11e6-9797-957f72913427.png)

**Comment by hpvd** [comment]
in "frontend" site menu there is a link to Dashboard
In backend the startpage is something like a dashboard too...

**Comment by mattab** [comment]
Thanks for the suggestion @hpvd 

I know we did this on purpose. The "admin dashboard/backend start page" can be accessed via the "Administration" cog icon in the top bar. Any thought on this one @tsteur whether we should add another link in the left menu?

**Comment by tsteur** [comment]
In some ways I think it would be good to have it, in some others thinking maybe not needed to add another link there. No clear opinion

**Comment by mattab** [comment]
As it isn't clear at this moment, I'll simply close the issue as won't fix. But we may find clarity in the future and decide on a particular way. Thanks @hpvd for the feedback as always :+1:
