### ISSUE TITLE
Location Provider: GeoIP (Php) missing after update to 3.0.0

### ISSUE THREAD

**Issue by s1awa** [piwik/piwik#11157]
I have one instance of Piwik where the Location Provider: GeoIP (Php) is not showing up after updating to 3.0.0. It was active and in use before the update.

![no](https://cloud.githubusercontent.com/assets/20663500/21761102/bde50b2a-d68b-11e6-9eea-99bb8f24628e.png)
 

Here is how a fresh install looks like
![yes](https://cloud.githubusercontent.com/assets/20663500/21761111/ce3bdf62-d68b-11e6-8f57-e607f7d2000a.png)

Edit: GeoIP2 Plugin was installed afterwards because all other location provider options are not available at this server.

Edit 2: Have this problem actually on 2 separate servers.

**Comment by alorence** [comment]
I had the exact same problem. After disabling Geo IP 2 plugin, I was able to see (and enable) CeoIP (PHP) provider for location lookup. I suspect an incompatibility between Geo IP 2 and Piwik 3

**Comment by s1awa** [comment]
@alorence Thanks, I will try to remove the plugin tomorrow.

**Comment by s1awa** [comment]
@alorence Deactivating GeoIP2 (v0.1.2) solved the problem.

So this is another problem with the GeoIP2 Plugin.

**Comment by s1awa** [comment]
@mattab FYI Plugin has fixed https://github.com/ahaenggli/piwik-geoip2/commit/320d4faa6c1ec611f645ca11558b058092ad09fb

It was missing the order key
`'order' => 20`

May be Piwik needs to check if a plugin doesn't have some required keys defined and let them use some other default value instead of letting it overwrite a built in location provider.
