### ISSUE TITLE
Improve icons and images in piwik

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#11155]
Follow-up to #10587 and similar to #9292

There are still many low resolution icons left in piwik:
- Flags:
     - Personally I don't like the "glossy" look of the current flags. (e.g ![fr](https://cloud.githubusercontent.com/assets/6266037/21581830/ccbf8440-d041-11e6-9468-df3bcee04be8.png))
     - There are many libraries providing official flags as svg (mostly from wikipedia | e.g [lipis/flag-icon-css](https://github.com/lipis/flag-icon-css))
     - After some tries I realized that converting the svg to 16px png images isn't enough.
While some simple flags look better (in my opinion, like ![at](https://cloud.githubusercontent.com/assets/6266037/21581851/7870c0ec-d042-11e6-9bae-2f37c8135171.png), ![fr](https://cloud.githubusercontent.com/assets/6266037/21581856/8544fc5c-d042-11e6-8f17-cf81ceb47ac1.png) or ![ch](https://cloud.githubusercontent.com/assets/6266037/21581860/c89639d0-d042-11e6-9535-7ef50b042b3b.png)) ~others get ugly as too much detail is lost. (![pk](https://cloud.githubusercontent.com/assets/6266037/21581864/eb720aec-d042-11e6-8cc3-427fa976d0b1.png), ![us](https://cloud.githubusercontent.com/assets/6266037/21581863/d5f532f2-d042-11e6-9d75-d79426211a20.png), ![sz](https://cloud.githubusercontent.com/assets/6266037/21581872/220c86ea-d043-11e6-9fde-f61cd42fdace.png), ![ba](https://cloud.githubusercontent.com/assets/6266037/21581875/3bb27a78-d043-11e6-99e3-7273beb64424.png))~
     - ~I'm not sure what to do as it is pretty hard to show many details in 192 Pixel total (16x12)~
    This got better by increasing the icon size to 64x48px: <img src="https://cloud.githubusercontent.com/assets/6266037/21742168/7fc0611c-d4e9-11e6-9323-5e665d62ba5e.png" height="16px">,<img src="https://cloud.githubusercontent.com/assets/6266037/21742185/b8875230-d4e9-11e6-932a-eaf1164b06f2.png" height="16px">,<img src="https://cloud.githubusercontent.com/assets/6266037/21742198/d5ee632c-d4e9-11e6-9004-4831ddd210bc.png" height="16px">,<img src="https://cloud.githubusercontent.com/assets/6266037/21742200/e223119c-d4e9-11e6-85ff-1c78ab8ce6d4.png" height="16px">
     - I would suggest keeping the height at 16px (48px) even if this means being a bit wider than the other icons, as they would fit better in line. 
     - [old](https://cloud.githubusercontent.com/assets/6266037/21582108/58952c50-d04b-11e6-8f24-495952351f06.png) vs. [new](https://cloud.githubusercontent.com/assets/6266037/21742341/dc4b105a-d4ec-11e6-9221-e9ba481fbffd.png)
- DevicesDetection/images/screens
    - In my opinion it's quite important to replace these (11) icons, as they are extremely pixelated next to the new icons 
![6083834a-d13a-11e6-9ffb-38dd847ed4ad](https://cloud.githubusercontent.com/assets/6266037/21742358/5d8fd894-d4ed-11e6-914f-648c2d1cba6a.PNG)
     - Anybody got an idea what icons to use. I [haven't found](https://commons.wikimedia.org/wiki/Category:Computer_monitor_icons) pretty ones.

- DevicesDetection/images/brand
    - I'd suggest creating a list of most common brands and only replace the icons for them. (https://github.com/piwik/piwik/issues/10587#issuecomment-269909494)

But there are still many single icons left (either in Morpheus or in the `images` folders of the core plugins). Best would be to recreate them a vector image and maybe even embed them as svg.

**Comment by Findus23** [comment]
Some ideas for images/screens:
- [ ] desktop:
  - https://commons.wikimedia.org/wiki/Category:Computer_monitor_icons
  - ???
- [ ] smartphone:
  - similar to ![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Smartphone_icon_-_Noun_Project_283536.svg/24px-Smartphone_icon_-_Noun_Project_283536.svg.png)
- [ ] tablets:
  - more square than smartphone
  - ![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/PICOL_icon_Tablet.svg/32px-PICOL_icon_Tablet.svg.png)
- [ ] phablet:
  - somewhere in between smartphone and tablets
- [ ] Portable media player:
  - mostly iPad Touch and similar devices
  - difference to smartphone?
- [x] camera:
  - as current icon: ![](https://demo.piwik.org/plugins/DevicesDetection/images/screens/camera.png)
- [x] carbrowser:
  - as current icon: ![](https://demo.piwik.org/plugins/DevicesDetection/images/screens/carbrowser.png)
  - https://commons.wikimedia.org/wiki/File:Car_with_Driver-Silhouette.svg (without driver?)
- [ ] console:
  - i would suggest a simple game controller (similar to https://commons.wikimedia.org/wiki/Category:Game_controller_icons)
  - e.g ![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Video_game_controller_icon_designed_by_Maico_Amorim.svg/20px-Video_game_controller_icon_designed_by_Maico_Amorim.svg.png)
- [ ] TV
  - Wikimedia is again not really helpful: https://commons.wikimedia.org/wiki/Category:Television_set_icons?uselang=de
- [ ] Smart display
  - Never heard of them, but seem to be all-in-one-displays like [this one](https://images-na.ssl-images-amazon.com/images/I/51OJFZLYw2L.jpg).

**Comment by Findus23** [comment]
For most of them there are fitting material icons: https://material.io/icons/
Now I'm just missing "phablet", "portable media player" and "smart display".
Any ideas how to visualize them?

**Comment by mattab** [comment]
* Smart display: could we reuse the TV icon?
* phablet: could we reuse tablet icon?
* portable media player: maybe reuse smartphone?

@sgiehl do you think these three device categories still make sense? or would we consider removing them in the future...?

**Comment by sgiehl** [comment]
good question. They will stay in device detector for now. But we might combine the numbers in Piwik reports. Not sure how useful it is for users to see those device types.

**Comment by mattab** [comment]
> we might combine the numbers in Piwik reports.

:+1:

**Comment by mattab** [comment]
Hi @Findus23 what's the status on this issue? (maybe we could create smaller separate issues for any remaining icons to be improved)

**Comment by Findus23** [comment]
Flags: 11272
screens: If the current pull requests are merged and everything is working, I'll start working on it (which should be pretty fast)
Brand Icons: I am still missing an easy solution and the time to manually collect the icons. 
If anyone wants to create a pull request to the piwik-icon repo with source images, I'd do the rest.

**Comment by Studio384** [comment]
There is also some need to take a second look at the Internet Explorer icons, both for desktop and Mobile. The desktop icon isn't the official one and the IE for Windows Phone icon is out of context. The white-on-colored-background icon isn't supposed to be used in the context Piwik uses it. Just go with the flat blue-on-white icon there.

This is the correct Internet Explorer icon: https://github.com/alrra/browser-logos/blob/master/src/archive/internet-explorer_9-11/internet-explorer_9-11.png. Notice how it is lighter.
This is the correct Internet Explorer Mobile icon: https://upload.wikimedia.org/wikipedia/commons/2/2f/Internet_Explorer_10_logo.svg. Notice that it doesn't have a background.

**Comment by Findus23** [comment]
@Studio384 We have now created a repository for the icons: https://github.com/piwik/piwik-icons
You can report all issues there.

About Deskop IE: Are you sure? When in doubt I tend to trust Wikipedia more. But maybe its a good idea to replace it with the latest Logo:
https://commons.wikimedia.org/wiki/File:Internet_Explorer_10_logo.svg
This one is used in https://en.wikipedia.org/wiki/Internet_Explorer

About Windows Phone: You are right that the tile is looking a bit odd. But if we use the "normal" logo you can't distinguish it with the desktop one.

**Comment by Studio384** [comment]
No, the logo you're linking is only used in the "About" page, anywhere else throughout Windows and Internet Explorer the normal full colored logo is used. The logo that is being used in Piwik right now is however not that logo but instead a darker altered version.

The version Wikipedia uses should represent IE Mobile in Piwik, and with that we also have a clear distinction between desktop and Mobile.

**Comment by Findus23** [comment]
@Studio384 BTW, with https://github.com/piwik/piwik-icons/pull/7 I am using the lighter IE-logo. While I am still not sure if it's correct, I am trusting you and alrra to know it better than me. (I'm not using windows)

**Comment by Studio384** [comment]
Well, have a look then at the logo Windows uses:
![capture](https://cloud.githubusercontent.com/assets/1693592/24607823/e806d828-1873-11e7-9e69-4287e3777047.PNG)
