### ISSUE TITLE
Error php

### ISSUE THREAD

**Issue by MWisotzki** [piwik/piwik#11151]
After update to Piwik 3.0.1-b2 I have 2 error:

WARNING: /homepages/15/d655099974/htdocs/analytics/plugins/SecurityInfo/PhpSecInfo/PhpSecInfo.php(95): Deprecated - Methods with the same name as their class will not be constructors in a future version of PHP; PhpSecInfo has a deprecated constructor - Piwik 3.0.1-b2 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

WARNING: /homepages/15/d655099974/htdocs/analytics/plugins/SecurityInfo/PhpSecInfo/Test/Test.php(35): Deprecated - Methods with the same name as their class will not be constructors in a future version of PHP; PhpSecInfo_Test has a deprecated constructor - Piwik 3.0.1-b2 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by MWisotzki** [comment]
WARNING: /homepages/15/d655099974/htdocs/analytics/vendor/piwik/decompress/libs/PclZip/pclzip.lib.php(1797): Notice - A non well formed numeric value encountered - Piwik 3.0.1-b2 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by MWisotzki** [comment]
After Update to 3.0.1:


WARNING: /homepages/15/d655099974/htdocs/analytics/plugins/CorePluginsAdmin/Controller.php(272): Notice - ob_clean(): failed to delete buffer. No buffer to delete - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by mattab** [comment]
Thanks for the report.
Theseissues are already reported in separate tickets:
https://github.com/piwik/piwik/issues/11320
https://github.com/piwik/component-decompress/pull/9
https://github.com/piwik/plugin-SecurityInfo/issues/13
