### ISSUE TITLE
UX builder fail when PIWIK plugin activated

### ISSUE THREAD

**Issue by faroe2k9** [piwik/piwik#11160]
As per 9th of january 2017 i'm using latest version of Wordpress, Flatsome Theme, latest version of Piwik plugin. PHP 5.6.29 - Debian. Mysql 5.0.11-dev

When the plugin is activated and I try to edit a page using the UX-builder, I get this error:

This page contains the following errors:
error on line 2 at column 55: Specification mandate value for attribute ng-strict-di
Below is a rendering of the page up to the first error.
----
What can I do to overcome this? The PIWIK is selfhosted - and works perfectly - but it interferes with the UX builder in the Flatsome Theme.

With regards
Thomas

**Comment by mattab** [comment]
Hi @faroe2k9 
I don't really understand this issue. Are you sure it's related to Piwik? If so please post more information, screenshot etc.
