### ISSUE TITLE
"File integrity" modal is unusable as content is displayed as HTML entities

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#11167]
Hi!
After morning upgrade I see long modal with list of the files which I should to delete.... No more words, see screenshot.
![3 0 1](https://cloud.githubusercontent.com/assets/740757/21797863/971f47f2-d722-11e6-9a30-2b5c5d42c61e.png)

**Comment by Findus23** [comment]
Seems like this, #11171 and #11172 are the same issue.

**Comment by mattab** [comment]
Thanks for the report. We'll fix this soon

**Comment by s1awa** [comment]
got following after 3.0.2 update

Files were found in your Piwik but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: libs/jquery/jquery.smartbanner.js
File to delete: libs/jquery/MIT-LICENSE-smartbanner.txt
File to delete: libs/jquery/stylesheets/jquery.smartbanner.css
