### ISSUE TITLE
Updating from 3.0.0 to 3.0.1 needs manual file deletions

### ISSUE THREAD

**Issue by kkretsch** [piwik/piwik#11166]
I didn't have this problem before and updated nearly every step of the version 2 path.

It finds several problems in the file integrity after updating and gives some commands to delete folders and files (I'm realy glad for these btw).

Shouldn't the update itself already clean up unused files?

Example:
rm "/var/www/stat/libs/Zend/Auth.php" "/var/www/stat/libs/Zend/Feed.php" "/var/www/stat/libs/Zend/Loader.php" "/var/www/stat/libs/Zend/Log.php" "/var/www/stat/libs/Zend/OpenId.php"

**Comment by Globulopolis** [comment]
I can say more. I can't do this on server on Windows platform.

**Comment by mattab** [comment]
Thanks for the report. Duplicates: https://github.com/piwik/piwik/issues/11132
