### ISSUE TITLE
Uploading plugin in 3.0.1 causes error

### ISSUE THREAD

**Issue by jloh** [piwik/piwik#11176]
Trying to upload the PerformanceInfo plugin via the GUI since for some reason I can't find it via search (another issue I guess?) and I get the following error from the interface:

```
You did not specify a ZIP file.
```

Checking error logs shows the same:

```
FastCGI sent in stderr: "PHP message: Error in Piwik: You did not specify a ZIP file" while reading response header from upstream
```

I'm running PIwik 3.0.1 and PHP 7.0.8. Piwik also has write access to its dirs.

Installing a plugin through the Marketplace without manually uploading the ZIP works fine.

**Comment by jloh** [comment]
Turns out the performance plugin isn't compatible with 3.0.x, is that the issue maybe?

**Comment by mattab** [comment]
are you able to reproduce this issue with other plugins or just this one?

**Comment by sgiehl** [comment]
@jloh  if you can reproduce that error with a plugin compatible with you piwik version, please open a new issue
