### ISSUE TITLE
Update emails link to localhost

### ISSUE THREAD

**Issue by jloh** [piwik/piwik#11174]
Apologies if this has been opened before/reported somewhere else, I did some searching and couldn't find anything.

I originally thought this was an issue with Piwik 2.X.X and waited until 3.0 to update and test but I'm still getting it.

I just got the "Update to 3.0.1" email and the `from` address is correct because I set `noreply_email_address` manually in `config.ini.php` however the link links me to localhost:

```
Hello,

There is a new version of Piwik available for update

You can update to version 3.0.1 automatically or download the package and install it manually:
https://127.0.0.1/index.php?module=CoreUpdater&action=newVersionAvailable

View the changelog for this version:
http://piwik.org/changelog/piwik-3-0-1/

Feel free to share your ideas and suggestions with the Piwik Team here:
http://piwik.org/contact/
```

Any idea whats causing this? I have valid and correct hostnames set in `trusted_hosts` however the last "person/thing" to access the system would've been the console archiving command which was run from localhost.

Currently on Piwik 3.0.0 on Ubuntu 16.04 with PHP 7.0.8

Let me know if there is any other info I can give!

**Comment by mattab** [comment]
Thanks for the report! I think this might be a duplicate of https://github.com/piwik/piwik/issues/11029

**Comment by jloh** [comment]
Ahh yep, thats a duplicate. Thanks for that!
