### ISSUE TITLE
Garbled error message related to File Integrity when upgrading to 3.0.1

### ISSUE THREAD

**Issue by Amenel** [piwik/piwik#11171]
At the Database Upgrade Required step, the update process reports an error and invites to revisit the page until no errors are reported. After clicking the Details link, I get this:

![image 137](https://cloud.githubusercontent.com/assets/7868710/21810018/6e30184e-d74a-11e6-9678-9da22d8326b6.png)

I don't think the intention was to get that display. I imagine it was meant to be some rich formatting with line breaks, bold text, code sections, etc. The comment markers around *Please delete these directories to prevent errors.* might be the culprit. I'm saying that because I have ssh'ed into the server and have checked all permissions as well as ownership of the directories and files, which are as they've always been for years now.

EDIT: And of course, I can no longer view the dashboard, as I'm brought back to that very page with the very same Details link. I was using the habitual automatic update.

**Comment by mattab** [comment]
Duplicates #11167
