### ISSUE TITLE
Build in cli Installer

### ISSUE THREAD

**Issue by pc-magas** [piwik/piwik#11184]
Sometimes an automated process for installation eg. for a hosting service provider or even people who run the piwik via docker container. 

So to be able to run a command such as:
```
php console install
```

By default the `install` option would look for a `config.ini.php`  and will:

* Generate the database
* Install basic Modules (the ones that not installed). If no plugin is defined it will auto setups the basic plugins needed except a `--no-plugin` option is provided.

Also I suggest this frature to have theese options too:

* Database only Setup:
```
php console install:database
```

* Plugin Only Setup:
```
php console install:plugin
```

Also I suggest to have options in order to specifying database connection crendentials and plugins.

**Comment by mattab** [comment]
Hi @pc-magas 

Thanks for the suggestion. This is covered in: https://github.com/piwik/piwik/issues/10257 

Please note we have this automation available but it's one of the rare things we haven't published as Open source. If you want to access this please contact InnoCraft here: https://www.innocraft.com/#contact
