### ISSUE TITLE
Numeric value out of rang 'visit_total_interactions'

### ISSUE THREAD

**Issue by obi12341** [piwik/piwik#11181]
Hello,
we are using Log Analytics with a very huge nginx access log and are running into this error after ~ 5.000.000 lines:

"NOTICE: PHP message: Error in Piwik (tracker): Error query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'visit_total_interactions' at row 1 In query: UPDATE piwik_log_visit SET idvisitor = ?, visit_last_action_time = ?, visit_exit_idaction_url = ?,  visit_total_actions = visit_total_actions + 1 ,  visit_total_interactions = visit_total_interactions + 1 , visit_total_time = ? WHERE idsite = ? AND idvisit = ? Parameters: array (   0 => 'u�����',   1 => '2017-01-09 13:35:58',   2 => 35211,   3 => 52493,   4 => 1,   5 => 61694, )"

Piwik Version 3.0.0 (official piwik docker)

Seems like the field visit_total_interactions is too small.
Any way to solve this problem?

Best regards,

obi12341

**Comment by obi12341** [comment]
changing the column from smallint to int(11) fixed the problem.

**Comment by mattab** [comment]
Thanks for report. will be fixed in Piwik 4 in https://github.com/piwik/piwik/pull/11086
