### ISSUE TITLE
3.0.x - No more Action showed since upgrade

### ISSUE THREAD

**Issue by coredumb** [piwik/piwik#11187]
Since the upgrade to 3.0 I've lost all actions - Automatic update.
It still shows the ones processed before the upgrade if I get back in time, but none are processed anymore since the upgrade.
Under "Actions menu", only "Downloads" still shows something while all other sub-menus shows only:

`There is no data for this report.`

In the database I see the log_action table populated though...

**Comment by TobeBenn** [comment]
same behaviour here ... update 2.17.1 => 3.0.1

only old actions are shown; no error in logs; db check ok

**Comment by mattab** [comment]
Do you see new actions tracked in Visitors > Visitor Log ? If so it means that the data is still being tracked correctly, and that there would be an issue with Archiver or so.

Do you see any problem with another report or only reports under "Actions" menu?

**Comment by coredumb** [comment]
When going on Visitors > Visitor Log I get this error:

Mysqli prepare error: Unknown column 'log_link_visit_action.interaction_position' in 'field list'

**Comment by mattab** [comment]
Please create this `interaction_position` column in your mysql table log_link_visit_action (field type is INT)

**Comment by coredumb** [comment]
Forgot to answer that it indeed fixed the problem.

Thanks.
