### ISSUE TITLE
Error 500 when trying to install 3.0.1

### ISSUE THREAD

**Issue by thueske** [piwik/piwik#11183]
Hey,

installing Piwik 3.0.0 works fine (no errors in system check), but when I try to install version 3.0.1 I get an Error 500 at system check page. Php-Error Log is empty and Apache Log only displays "premature end of script headers".

I am using PHP 7.0.x with FPM and apache 2.

Any ideas?

**Comment by Hermsi1337** [comment]
Hey m8,

do the following via CLI:

piwik/console core:update

<3

Hermsi

**Comment by thueske** [comment]
Error occurs when https://github.com/piwik/piwik/blob/3.x-dev/core/FileIntegrity.php#L415-#L424 is executed. CGI PHP works, FPM not. @mattab - you integrated the check, any ideas?

**Comment by mattab** [comment]
Sorry @thueske - no idea so far. These lines shouldn't trigger an error. can you paste the full error message?

**Comment by ins0** [comment]
Looks like ``use Piwik\Filesystem`` is missing?!

**Comment by sgiehl** [comment]
@ins0 That shouldn't be needed as the class is within the same directory & namespace

**Comment by thueske** [comment]
Problem still exists... Happens when setlocale(LC_ALL, $newLocale) is something other than "en-US"... Any ideas or workaround?

**Comment by thueske** [comment]
de_DE.UTF-8 fails, de_DE works...

**Comment by wdj-ac** [comment]
@mattab I can confirm! 
`/index.php?module=Installation&action=systemCheckPage`
Fails with Internal Server Error 500. When I switch from PHP-FPM to PHP-CGI everything is fine.

**Comment by simonschaufi** [comment]
Can this be documented somewhere? I just found this issue as I'm also using PHP FPM and realized, Piwik isn't working properly. PHP-CGI works fine.
