### ISSUE TITLE
In Visitors > Software > Browser Plugins, Cookie shows 100% but it likely shouldn't

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11199]
In Visitors > Software > Browser Plugins, Cookie shows 100% but it likely shouldn't, as we would expect some people maybe disable cookie tracking (first party).

To investigate further we could try to disable cookie in our browser, and then check whether Piwik detects correctly that cookies are disabled.

![cookie detection shows 100 percent](https://cloud.githubusercontent.com/assets/466765/21998554/62c99bba-dc9a-11e6-99a1-8945fc881711.png)

**Comment by Findus23** [comment]
It seems to be working. I disabled cookies in Firefox and got the following http request:
```http
GET /piwik.php?action_name=Weingut%20Gattinger&idsite=2&rec=1&r=498338&h=12&m=35&s=8&url=https%3A%2F%2Fwww.gattinger-wachau.at%2Fen%2F&_id=&_idts=1484998509&_idvc=1&_idn=1&_refts=0&_viewts=1484998509&send_image=1&pdf=0&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=0&res=1920x1080&gt_ms=32&pv_id=wDGsOp HTTP/1.1
Host: piwik.gattinger-wachau.at
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://www.gattinger-wachau.at/en/
Connection: keep-alive
```

It seems like cookies aren't mentioned in the Visitor log/Visitor profile so I don't now if the server side detection is working, but the percentage went down from 100%
![bildschirmfoto vom 2017-01-21 12-42-22](https://cloud.githubusercontent.com/assets/6266037/22174159/6bcd9834-dfd7-11e6-8188-99c081672621.png)

**Comment by mattab** [comment]
Thanks @Findus23 for confirming! :+1:
