### ISSUE TITLE
v3.0.1 SEO-Bewertungen <- Image Size

### ISSUE THREAD

**Issue by github-hbr** [piwik/piwik#11192]
v3.0.1
in "SEO-Bewertungen" the image size seems to be different?

![img_033](https://cloud.githubusercontent.com/assets/24852088/21955467/f1a9e12c-da6b-11e6-8394-08eb6ffad1c9.jpg)

**Comment by sgiehl** [comment]
Thanks for the report. @Findus23 would you mind having a look?

**Comment by Findus23** [comment]
@sgiehl of course. I just have never heard of a SEO-plugin. 
Where can I find it?

**Comment by sgiehl** [comment]
It can be added as widget on the dashboard.

**Comment by Findus23** [comment]
Ah thanks I found it. Have never seen it before.

**Comment by Findus23** [comment]
@github-hbr If you have more ideas for icon improvement, just mention them.
