### ISSUE TITLE
 Allowed memory size exhausted in FileIntegrity.getDirectoriesFoundInManifest()

### ISSUE THREAD

**Issue by ptr1120** [piwik/piwik#11197]
After upgrading Piwik from 2.17.1 to the new version 3.0.1 (using official debian package) I get a fatal error due to missing allowed memory size when I execute the system checks in admin area. 
`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /mydir/piwik/core/FileIntegrity.php on line 259`
My php memory limit is 512Mb, increasing the memory limit did not help. When I manually remove the code from FileIntegrity.getDirectoriesFoundInManifest() the system checks run fine.
I do not understand why `getDirectoriesFoundInManifest()` in FileIntegrity.php consumes as much memory?

Any ideas?

**Comment by gamanet** [comment]
Same problem after update to 3.0.1...

ii  php5                           5.6.29+dfsg-0+deb8u1 
ii  php5-cli                       5.6.29+dfsg-0+deb8u1 
ii  php5-common                    5.6.29+dfsg-0+deb8u1 
ii  php5-curl                      5.6.29+dfsg-0+deb8u1 
ii  php5-dev                       5.6.29+dfsg-0+deb8u1 
ii  php5-gd                        5.6.29+dfsg-0+deb8u1 
ii  php5-geoip                     1.1.0-2              
ii  php5-json                      1.3.6-1              
rc  php5-mysql                     5.6.26+dfsg-0+deb8u1 
ii  php5-mysqlnd                   5.6.29+dfsg-0+deb8u1 
ii  php5-readline                  5.6.29+dfsg-0+deb8u1 
ii  pkg-php-tools                  1.28                 

ii  apache2                        2.4.10-10+deb8u7      
ii  apache2-bin                    2.4.10-10+deb8u7      
ii  apache2-data                   2.4.10-10+deb8u7      
ii  apache2-utils                  2.4.10-10+deb8u7      
ii  libapache2-mod-geoip           1.2.8-2               
ii  libapache2-mod-php5            5.6.29+dfsg-0+deb8u1  

ii  mysql-client                   5.5.53-0+deb8u1        
ii  mysql-client-5.5               5.5.53-0+deb8u1        
ii  mysql-common                   5.5.53-0+deb8u1        
ii  mysql-server                   5.5.53-0+deb8u1        
ii  mysql-server-5.5               5.5.53-0+deb8u1        
ii  mysql-server-core-5.5          5.5.53-0+deb8u1        
rc  php5-mysql                     5.6.26+dfsg-0+deb8u1   
ii  php5-mysqlnd                   5.6.29+dfsg-0+deb8u1   

What i found in syslog:

 apache2: PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 72 bytes) in /usr/share/piwik/core/FileIntegrity.php on line 259

I´ve raised memory_size from 1024M to finally 8000M - without any changes, the error still occours...

thx in advance for your help!

**Comment by mattab** [comment]
what PHP version do you each use?

Can you try upgrade php?

**Comment by ptr1120** [comment]
I am using the default debian 8 php version:
```
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
Upgrade is not allowed here.

**Comment by triforce** [comment]
I am experiencing exactly the same problem and upgrading PHP is not an option for me either. I am using nginx with php5-fpm on Debian 8.1. I also upgraded from Piwik 2.17.1 to 3.0.1.

**Comment by gamanet** [comment]
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

I don´t know what i should upgrade... the problem (Allowed memory size exhausted in FileIntegrity.getDirectoriesFoundInManifest) arose AFTER updating to 3.0.1.

thats the repo i used to install and update our piwik-installation:

deb https://debian.piwik.org/ piwik main
deb-src https://debian.piwik.org/ piwik main

**Comment by triforce** [comment]
This looks like a bug in the code that needs fixing (I've submitted a pull request).

**Comment by mattab** [comment]
Do you know if your PHP has some special configuration like safe mode, or open base dir restriction?

**Comment by gamanet** [comment]
allow_url_fopen	On	On
allow_url_include	Off	Off
always_populate_raw_post_data	On	Off
arg_separator.input	&	&
arg_separator.output	&	&
asp_tags	Off	Off
auto_append_file	no value	no value
auto_globals_jit	On	On
auto_prepend_file	no value	no value
browscap	no value	no value
default_charset	UTF-8	UTF-8
default_mimetype	text/html	text/html
disable_classes	no value	no value
disable_functions	pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,	pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
display_errors	Off	Off
display_startup_errors	Off	Off
doc_root	no value	no value
docref_ext	no value	no value
docref_root	no value	no value
enable_dl	Off	Off
enable_post_data_reading	On	On
error_append_string	no value	no value
error_log	no value	no value
error_prepend_string	no value	no value
error_reporting	22527	22527
exit_on_timeout	Off	Off
expose_php	On	On
extension_dir	/usr/lib/php5/20121212	/usr/lib/php5/20121212
file_uploads	On	On
highlight.comment	#FF8000	#FF8000
highlight.default	#0000BB	#0000BB
highlight.html	#000000	#000000
highlight.keyword	#007700	#007700
highlight.string	#DD0000	#DD0000
html_errors	On	On
ignore_repeated_errors	Off	Off
ignore_repeated_source	Off	Off
ignore_user_abort	Off	Off
implicit_flush	Off	Off
include_path	.:/usr/share/php:/usr/share/pear	.:/usr/share/php:/usr/share/pear
log_errors	On	On
log_errors_max_len	1024	1024
mail.add_x_header	On	On
mail.force_extra_parameters	no value	no value
mail.log	no value	no value
max_execution_time	30	30
max_file_uploads	20	20
max_input_nesting_level	64	64
max_input_time	300	300
max_input_vars	1000	1000
memory_limit	512M	128M
open_basedir	no value	no value
output_buffering	0	4096
output_handler	no value	no value
post_max_size	513M	5120M
precision	14	14
realpath_cache_size	16K	16K
realpath_cache_ttl	120	120
register_argc_argv	Off	Off
report_memleaks	On	On
report_zend_debug	On	On
request_order	GP	GP
sendmail_from	no value	no value
sendmail_path	/usr/sbin/sendmail -t -i 	/usr/sbin/sendmail -t -i 
serialize_precision	17	17
short_open_tag	Off	Off
SMTP	localhost	localhost
smtp_port	25	25
sql.safe_mode	Off	Off
sys_temp_dir	no value	no value
track_errors	Off	Off
unserialize_callback_func	no value	no value
upload_max_filesize	513M	5120M
upload_tmp_dir	no value	no value
user_dir	no value	no value
user_ini.cache_ttl	300	300
user_ini.filename	.user.ini	.user.ini
variables_order	GPCS	GPCS
xmlrpc_error_number	0	0
xmlrpc_errors	Off	Off
zend.detect_unicode	On	On
zend.enable_gc	On	On
zend.multibyte	Off	Off
zend.script_encoding	no value
