### ISSUE TITLE
Error Update 2.17.1 to 3.0.1.

### ISSUE THREAD

**Issue by twixi** [piwik/piwik#11198]
/home/www/stats.site.com/core/Updates/3.0.0-b1.php: Error trying to execute the migration 'ALTER TABLE `piwik_plugin_setting` ADD INDEX index_plugin_name_user_login (`plugin_name`, `user_login`);'. The error was: SQLSTATE[42000]: Syntax error or access violation: 1142 ALTER command denied to user 'DB'@'127.0.0.1' for table 'piwik_plugin_setting'

**Comment by sgiehl** [comment]
Seems to be insufficient database access rights not related to Piwik.
