### ISSUE TITLE
Doc function signatures not right

### ISSUE THREAD

**Issue by ysangkok** [piwik/piwik#11207]
https://developer.piwik.org/guides/tracking-javascript-guide claims getAsyncTracker takes arguments. http://developer.piwik.org/api-reference/tracking-javascript claims it takes some.

Also, on http://developer.piwik.org/api-reference/tracking-javascript , Scroll is misspelt as Sroll.

**Comment by tsteur** [comment]
Thank you 👍 fixed by @CheweyZ in https://github.com/piwik/developer-documentation/pull/167 and https://github.com/piwik/developer-documentation/pull/166

**Comment by CheweyZ** [comment]
in future if you notice these issue feel free to make a pull request on them via the bottom left corner of the doc page there is a edit on GitHub button
