### ISSUE TITLE
Not able to detect inbuild browsers like Facebook app

### ISSUE THREAD

**Issue by fdellwing** [piwik/piwik#11208]
So, today I saw a lot of not detectable browser in a newly tracked site. So I looked into it and it looks like these are clicks from browser build in facebook app.

```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C92 [FBAN/FBIOS;FBAV/75.0.0.48.61;FBBV/45926345;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/10.2;FBSS/2;FBCR/o2-de;FBID/phone;FBLC/de_DE;FBOP/5]
```
```
Mozilla/5.0 (Linux; Android 6.0; LG-D855 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/106.0.0.26.68;]
```
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C92 [FBAN/FBIOS;FBAV/75.0.0.48.61;FBBV/45926345;FBRV/0;FBDV/iPhone8,4;FBMD/iPhone;FBSN/iOS;FBSV/10.2;FBSS/2;FBCR/o2-de;FBID/phone;FBLC/de_DE;FBOP/5]
```
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C92 [FBAN/FBIOS;FBAV/75.0.0.48.61;FBBV/45926345;FBRV/0;FBDV/iPhone7,1;FBMD/iPhone;FBSN/iOS;FBSV/10.2;FBSS/3;FBCR/o2-de;FBID/phone;FBLC/de_DE;FBOP/5]
```
```
Mozilla/5.0 (Linux; Android 5.0; SM-N9005 Build/LRX21V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/106.0.0.26.68;]
```
```
Mozilla/5.0 (Linux; Android 4.4.4; XT1021 Build/KXC21.5-40) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/91.0.0.17.68;]
```

Would be nice to detect them.

**Comment by Findus23** [comment]
For me all of your User Agents are detected as "facebook"
![bildschirmfoto vom 2017-01-21 12-24-49](https://cloud.githubusercontent.com/assets/6266037/22174048/af705d5e-dfd4-11e6-89f1-f7178ca31d31.png)

@sgiehl Why is Facebook detected as a browser, but is not in the list of browsers (https://github.com/piwik/device-detector/blob/master/Parser/Client/Browser.php#L29) and therefore has no icon.
And why is Apple using the unknown-icon even though it has an own icon. (Visible in `Show all`)

**Comment by sgiehl** [comment]
@Findus23 the apple logo wasn't displayed caused by a bug. Just fixed that one.

Regarding the facebook detection. Actually device detector doesn't detect it as browser. It's detected as mobile app. Piwik itself only handles browsers atm. All other client types are reported as unknown. The device detection displays the client name (even if it is not detected as browser). Piwik should be able to handle clients other than browser in the future. This will be handled in #5413
