### ISSUE TITLE
SMS Provider: new integration for ASP SMS

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11213]
Goal of this issue is to integrate a new SMS API Provider in Piwik. Currently Clockwork SMS provider is available but we'd like to introduce a new Swiss-based provider: ASP SMS. https://www.aspsms.com/

### How to call the API to send SMS

* we could simply use this super simple API: https://www.aspsms.com/en/http/
* or maybe we could use this existing PHP library which connects to the API? https://github.com/nadar/aspsms 

### How to get counted as affiliate when users send SMS

* Set "AffiliateID" parameter to "227830" when calling operations that send text messages. 
*  use this link when linking to ASPSMS create account for our users:
http://www.aspsms.com/en/?REF=227830

#### What are ASPSMS Credits and how do I buy some?

For sending an SMS, you need so-called ASPSMS credits,
which are purchased in advance. The ASPSMS credits do
not expire. Payment by bank transfer, various credit
cards such as Eurocard/Mastercard, Visa, American
Express or Diners Club, PayPal or Swiss Postcard.
https://www.aspsms.com/instruction/payment.asp

**Comment by mattab** [comment]
Challenge: 

* Currently our SMS Provider expects one API Key. This ASP SMS API has a password and an API key. So we need SMS Provider (in `SMSProvider` abstract class) to be able to define which fields they need (eg. password + api key) and the UI to display these fields.

**Comment by sgiehl** [comment]
Are you going to handle this one @mattab ?

**Comment by mattab** [comment]
Stefan I was going to ask for your help for this project 🙌 maybe after
your current project.
I'll on you my username and password with loads of free credits
