### ISSUE TITLE
File integrity check failed dramatically

### ISSUE THREAD

**Issue by daniel-barrows** [piwik/piwik#11226]
I am trying to upgrade from Piwik 3.0.0 to 3.0.1 using Softaculous in cPanel on Namecheap servers. I have upgraded Piwik a number of times in the past without incident.
This time, however, upgraded on Softaculous, then clicked the button to the Piwik page that says "Database Upgrade Required". On this page, I see "File integrity check failed and reported some errors." When I click details, I see the this long list of errors: https://gist.github.com/daniel-barrows/5b8c0d51f71754cf4d074f085b8916b6
I have two problems:
1) My problem: How do I upgrade? It says "You should fix this issue and then refresh this page until it shows no error." I don't know how to fix it.
2) Your problem: I suspect it's a bug that I am seeing &lt;br/&gt; tags instead of actual line breaks. The html source of the error page is at https://gist.github.com/daniel-barrows/1a1e17ec9ea46a82f923e484ff4586e4

This issue seems similar to https://github.com/piwik/piwik/issues/11129 and https://github.com/piwik/piwik/issues/9233

**Comment by daniel-barrows** [comment]
@mattab I read the similar issues more carefully, and see that I can safely remove the files via ssh. However, I would encourage you to read Problem (2) more carefully, as I am not aware that it has been reported elsewhere.

**Comment by mattab** [comment]
@daniel-barrows You're right. Since then a separate issue was created here: #11167
