### ISSUE TITLE
Core Provider plugin Column class has no $columnType property and prevents location_provider field from being created in piwik_log_visit table

### ISSUE THREAD

**Issue by petejohnson84** [piwik/piwik#11225]
I ran into an issue installing the core Provider plugin by adding it to the [Plugins] and [PluginsInstalled] sections in config.ini.php. The plugin seems to be installed but the table piwik_log_visit is missing the column location_provider. Even deactivating and activating the Provider plugin will not create the column. I even tried running the core:update script via command line which said database was up-to-date. I noticed that other core plugins that have Provider class extending VisitDimension class have $columnType property. After adding $columnType property and running the core:update the column was created. Note that a fresh install without Provider in config.ini.php, activating through UI will create column correctly. The bug can be reproduced only by installing via config.ini.php. I think code should be changed to include $columnType property in the Provider plugin Provider class.

**Comment by mattab** [comment]
> I ran into an issue installing the core Provider plugin by adding it to the [Plugins] and [PluginsInstalled] sections in config.ini.php. 

This is not the correct way to install plugins. You need to click "activate" in the Administration > Plugins, or install it via the console command `./console plugin:activate`
