### ISSUE TITLE
since 3.0.1 scheduled reports are no longer sent

### ISSUE THREAD

**Issue by mameier** [piwik/piwik#11224]
I have scheduled reports that are (have been) sent daily.
After installing 3.0.1 the reports are no longer sent.

The report is sent via mail when I klick the "send report now" link in the report list.
The cron job is running every hour.
No report is sent by the cron job.

**Comment by sgiehl** [comment]
Do you have logs of the cron job output? Maybe an error occurs...

**Comment by mameier** [comment]
There were no errors in cron log.
After 5 days, piwik started to generate reports again.
Without any change of the configuration.
Strange, now it's working and I can't reproduce the reported behaviour.
