### ISSUE TITLE
 Call to undefined function Piwik\fnmatch() 

### ISSUE THREAD

**Issue by bluesailor45** [piwik/piwik#11237]
after upgrade to PIWIK 3.0.1 in Joomla, following error appears:
fatal error in PIWIK 3.0.1
Call to undefined function Piwik\fnmatch() in /share/MD0_DATA/.qpkg/Piwik/Piwik/core/FileIntegrity.php 312 using PHP 5.5.26

thereafter it is not possible to logon to PIWIK:
------------------------------
a fatal error occurred:
Please contact the system administrator, or login to Piwik to learn more.

If you are Super User, but cannot login because of this error, you can still troubleshoot further. Follow these steps: 
1) open the config/config.ini.php file and look for the salt value under [General]. 
2) edit this current URL you are viewing and add the following text (replacing salt_value_from_config by the salt value from the config file): 
index.php?i_am_super_user=salt_value_from_config&....
-----------------------------
However this 2) message is not useful for me.

**Comment by CheweyZ** [comment]
What OS are you running this on?

**Comment by bluesailor45** [comment]
Hi CheweyZ
I am running Linux-Firmware Version 4.2.1  in QNap TS-219P. In Joomla I am using Joomla 3.6.5 with PHP 5.5.26. I was upgrading PIWIK from Version 2.6.1 which was installed as a QNAP Application.
Thanks for your help.

**Comment by bluesailor45** [comment]
No solution to that 😳???

**Comment by CheweyZ** [comment]
So not 100% sure but it appears your system is none POSIX compliant which means that fnmatch is not able to run on your machine. To find out more see or confirm you machine-distro is a POSIX supported system as then php call only works on that.

Sorry for the little help.

**Comment by bluesailor45** [comment]
Thank you very much for your hint. Any tip is welcome😉. I will check in this direction.

**Comment by tsteur** [comment]
@bluesailor45  can you try to copy something like this in your "libs/upgradephp/upgrade.php"

```php
if(!function_exists('fnmatch')) {

    function fnmatch($pattern, $string) {
        return preg_match("#^".strtr(preg_quote($pattern, '#'), array('\*' => '.*', '\?' => '.'))."$#i", $string);
    } // end

} // end if
```

I haven't tested it and only copied it from http://php.net/manual/en/function.fnmatch.php

We would need to define this method then in the future if it is not defined

**Comment by bluesailor45** [comment]
@tsteur thank you very much for your help.
I added your suggested code add the end of upgrade.php and it did work!

Unfortunately I got an additional error while the upgrade is trying to upgrade the Mysql database:
Mysqli prepare error: Table 'Piwik_analytics.piwik_plugin_setting' doesn't exist

I checked the Piwik_analytics.piwik database and the mentioned table really does not exist. Please provide me with the correct create table command.
Thank you very much.

**Comment by bluesailor45** [comment]
Thank you Thomas
 
I have added this code to the end of upgrade.php and the update process did work until the database upgrade - which ended with the error message:

Mysqli prepare error: Table 'Piwik_analytics.piwik_plugin_setting' doesn't exist

How do I have to create this table? Can you give me the correct Mysql create table command

Thank you very much.

Very kind regards

Kurt

**Comment by RMastop** [comment]
Please use this to create the table

```
CREATE TABLE `piwik_plugin_setting` (
  `plugin_name` varchar(60) NOT NULL,
  `setting_name` varchar(255) NOT NULL,
  `setting_value` longtext NOT NULL,
  `user_login` varchar(100) NOT NULL DEFAULT '',
  KEY `index_plugin_name_user_login` (`plugin_name`,`user_login`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by bluesailor45** [comment]
Hi Thomas
thank you very much for your fast response. After I have created the table and rerun the update, obviously the table „Piwik_analytics.piwik_site_setting“ is also missing.
Please send also the required create table sql.

Thank you very much.

Very kind regards
Kurt

**Comment by RMastop** [comment]
Hi,

The requested info:
`CREATE TABLE `piwik_site_setting` (
  `idsite` int(10) unsigned NOT NULL,
  `plugin_name` varchar(60) NOT NULL,
  `setting_name` varchar(255) NOT NULL,
  `setting_value` longtext NOT NULL,
  KEY `idsite` (`idsite`,`plugin_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`

**Comment by bluesailor45** [comment]
Hi
I created requested table and rerun, but there is obviously some severe errors with my install (see below). I will try to uninstall from Qnap, and install the Qnap supported version and the upgrade. Keep fingers crossed ;-)
-------------------------------------
File integrity check failed and reported some errors. You should fix this issue and then refresh this page until it shows no error.
Directories were found in your Piwik but we didn't expect them.<br/>--> Please delete these directories to prevent errors. <--<br/><br/>Directory to delete: libs/pChart2.1.3<br/>Directory to delete: libs/tcpdf<br/><br/><br/>To delete all these directories at once, you can run this command:<br/>rm -Rf /share/MD0_DATA/.qpkg/Piwik/Piwik/libs/pChart2.1.3 /share/MD0_DATA/.qpkg/Piwik/Piwik/libs/tcpdf<br/><br/>
Files were found in your Piwik but we didn't expect them.<br/>--> Please delete these files to prevent errors. <--<br/><br/>File to delete: config/global.ini.auto-backup-before-update.php<br/>File to delete: libs/PEAR.php<br/>File to delete: libs/PEAR5.php<br/>File to delete: libs/Archive_Tar/Tar.php<br/>File to delete: libs/PEAR/Exception.php<br/>File to delete: libs/PEAR/FixPHP5PEARWarnings.php<br/>File to delete: libs/PEAR/LICENSE<br/>File to delete: libs/PclZip/lgpl-2.1.txt<br/>File to delete: libs/PclZip/pclzip.lib.php<br/>File to delete: libs/PiwikTracker/LICENSE.txt<br/>File to delete: libs/UserAgentParser/README.md<br/>File to delete: libs/UserAgentParser/UserAgentParser.php<br/>File to delete: libs/UserAgentParser/UserAgentParser.test.php<br/>File to delete: libs/angularjs/LICENSE<br/>File to delete: libs/angularjs/angular-animate.js<br/>File to delete: libs/angularjs/angular-animate.min.js<br/>File to delete: libs/angularjs/angular-cookies.js<br/>File to delete: libs/angularjs/angular-cookies.min.js<br/>File to delete: libs/angularjs/angular-csp.css<br/>File to delete: libs/angularjs/angular-loader.js<br/>File to delete: libs/angularjs/angular-loader.min.js<br/>File to delete: libs/angularjs/angular-mocks.js<br/>File to delete: libs/angularjs/angular-resource.js<br/>File to delete: libs/angularjs/angular-resource.min.js<br/>File to delete: libs/angularjs/angular-route.js<br/>File to delete: libs/angularjs/angular-route.min.js<br/>File to delete: libs/angularjs/angular-sanitize.js<br/>File to delete: libs/angularjs/angular-sanitize.min.js<br/>File to delete: libs/angularjs/angular-scenario.js<br/>File to delete: libs/angularjs/angular-touch.js<br/>File to delete: libs/angularjs/angular-touch.min.js<br/>File to delete: libs/angularjs/angular.js<br/>File to delete: libs/angularjs/angular.min.js<br/>File to delete: libs/angularjs/errors.json<br/>File to delete: libs/angularjs/version.json<br/>File to delete: libs/angularjs/version.txt<br/>File to delete: libs/html5shiv/html5shiv.js<br/>File to delete: libs/javascript/sprintf.js<br/>File to delete: libs/jquery/MIT-LICENSE-jquery.txt<br/>File to delete: libs/jquery/MIT-LICENSE-jqueryui.txt<br/>File to delete: libs/jquery/MIT-LICENSE-placeholder.txt<br/>File to delete: libs/jquery/MIT-LICENSE-scrollto.txt<br/>File to delete: libs/jquery/jquery-ui.js<br/>File to delete: libs/jquery/jquery.history.js<br/>File to delete: libs/jquery/jquery.js<br/>File to delete: libs/jquery/jquery.jscrollpane.js<br/>File to delete: libs/jquery/jquery.mousewheel.js<br/>File to delete: libs/jquery/jquery.placeholder.js<br/>File to delete: libs/jquery/jquery.scrollTo.js<br/>File to delete: libs/jquery/themes/base/jquery-ui.css<br/>File to delete: libs/mousetrap/README.md<br/>File to delete: libs/mousetrap/mousetrap.min.js<br/>File to delete: libs/upgradephp/old-upgrade.php<br/>File to delete: misc/others/cli-script-bootstrap.php<br/>File to delete: misc/others/iframeWidget.htm<br/>File to delete: misc/others/phpstorm-codestyles/Piwik_codestyle.xml<br/>File to delete: misc/others/phpstorm-codestyles/README.md<br/>File to delete: misc/proxy-hide-piwik-url/piwik.php<br/>File to delete: vendor/piwik/device-detector/phpunit.xml.dist<br/>File to delete: vendor/piwik/device-detector/test.php<br/>File to delete: vendor/piwik/device-detector/Cache/CacheFile.php<br/>File to delete: vendor/piwik/device-detector/Cache/CacheInterface.php<br/>File to delete: vendor/piwik/device-detector/Cache/CacheMemcache.php<br/>File to delete: vendor/piwik/device-detector/Cache/CacheStatic.php<br/>File to delete: vendor/twig/twig/ext/twig/LICENSE<br/>File to delete: vendor/twig/twig/lib/Twig/Node/SandboxedModule.php<br/>File to delete: vendor/twig/twig/.editorconfig<br/><br/><br/>To delete all these files at once, you can run this command:<br/>rm "/share/MD0_DATA/.qpkg/Piwik/Piwik/config/global.ini.auto-backup-before-update.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PEAR.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PEAR5.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/Archive_Tar/Tar.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PEAR/Exception.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PEAR/FixPHP5PEARWarnings.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PEAR/LICENSE" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PclZip/lgpl-2.1.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PclZip/pclzip.lib.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/PiwikTracker/LICENSE.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/UserAgentParser/README.md" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/UserAgentParser/UserAgentParser.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/UserAgentParser/UserAgentParser.test.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/LICENSE" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-animate.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-animate.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-cookies.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-cookies.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-csp.css" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-loader.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-loader.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-mocks.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-resource.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-resource.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-route.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-route.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-sanitize.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-sanitize.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-scenario.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-touch.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular-touch.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/angular.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/errors.json" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/version.json" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/angularjs/version.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/html5shiv/html5shiv.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/javascript/sprintf.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/MIT-LICENSE-jquery.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/MIT-LICENSE-jqueryui.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/MIT-LICENSE-placeholder.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/MIT-LICENSE-scrollto.txt" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery-ui.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery.history.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery.jscrollpane.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery.mousewheel.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery.placeholder.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/jquery.scrollTo.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/jquery/themes/base/jquery-ui.css" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/mousetrap/README.md" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/mousetrap/mousetrap.min.js" "/share/MD0_DATA/.qpkg/Piwik/Piwik/libs/upgradephp/old-upgrade.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/misc/others/cli-script-bootstrap.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/misc/others/iframeWidget.htm" "/share/MD0_DATA/.qpkg/Piwik/Piwik/misc/others/phpstorm-codestyles/Piwik_codestyle.xml" "/share/MD0_DATA/.qpkg/Piwik/Piwik/misc/others/phpstorm-codestyles/README.md" "/share/MD0_DATA/.qpkg/Piwik/Piwik/misc/proxy-hide-piwik-url/piwik.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/piwik/device-detector/phpunit.xml.dist" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/piwik/device-detector/test.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/piwik/device-detector/Cache/CacheFile.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/piwik/device-detector/Cache/CacheInterface.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/piwik/device-detector/Cache/CacheMemcache.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/piwik/device-detector/Cache/CacheStatic.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/twig/twig/ext/twig/LICENSE" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/twig/twig/lib/Twig/Node/SandboxedModule.php" "/share/MD0_DATA/.qpkg/Piwik/Piwik/vendor/twig/twig/.editorconfig"<br/><br/>
Errors below may be due to a partial or failed upload of Piwik files.
--> Try to reupload all the Piwik files in BINARY mode. <--<br/>
Unterschiedliche Dateigröße: /share/MD0_DATA/.qpkg/Piwik/Piwik/libs/upgradephp/upgrade.php (erwartete Größe: 16965, gefunden: 17282)


Very kind regards
Kurt

**Comment by RMastop** [comment]
Hi @bluesailor45, 

It might actually be correct to remove those files and directories. Do you have a way to remove the directories and files from the device? Piwik 3.0.1 has a check on unexpected files / directories.

In the past some files were kept in the install package, Piwik now identifies those unneeded items.

**Comment by bluesailor45** [comment]
I tried to reinstall Piwik 2.6.1 (which is supported in Knapp App store), apply the mentioned fix to the module and rerun the upgrade process. However I got much too many error while upgrade. I will wait with the install/update until 3.xx is available in the Qnap app store.
