### ISSUE TITLE
Icons in scheduled reports are big

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#11238]
![image](https://cloud.githubusercontent.com/assets/273120/22128454/816125bc-df05-11e6-86d1-e039b3871bdf.png)

**Comment by Findus23** [comment]
@tsteur I can understand the reasoning, but it makes it really confusing if icons from completely different plugins (DevicePlugins in this case) are used in unrelated places in Piwik.

**Comment by tsteur** [comment]
very true 👍  maybe we can define a max-width in the scheduled reports management at some point
