### ISSUE TITLE
region in visitorlog - character set problem?

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11258]
With Piwik 3.0.2b1 city and region is shown in visitor log (solved https://github.com/piwik/piwik/issues/9705)
That's awesome!

While German umlauts works great for city, for region there seem to be a problem
(e.g. u shown instead of ü)

In maxminds demo this particular case looks fine.
Is there a problem with character set or similar for region?

Example:
city "Düsseldorf" is fine in piwik and in maxmind's demo
region "Württemberg" is shown fine in maxmind's demo, but piwik shows "Wurttemberg" (u instead of ü)

Please see attachments

![2017-01-22_23h05_07](https://cloud.githubusercontent.com/assets/5681880/22186644/4af39852-e0f9-11e6-95f1-14daea17bfec.png)

![2017-01-22_23h07_44](https://cloud.githubusercontent.com/assets/5681880/22186647/53435150-e0f9-11e6-9793-91c05b8405ec.png)

**Comment by sgiehl** [comment]
We use geoip library from maxmind. And they have that incorrect in their list. See http://www.maxmind.com/download/geoip/misc/region_codes.csv

**Comment by hpvd** [comment]
thankyou for investigating. closing...
