### ISSUE TITLE
Add the need to regenerate old reports to FAQ#113

### ISSUE THREAD

**Issue by caistleitner** [piwik/piwik#11265]
[Faq#113](http://piwik.org/faq/how-to/faq_113/) explains how to turn on `Unique Vistor` for future reports.

But it fails highlight that old reports are not fixed up.
This confuses people, as can be seen for example [here](https://github.com/piwik/piwik/issues/11179#issuecomment-274366280).

Please add a remark to [Faq#113](http://piwik.org/faq/how-to/faq_113/) similar to the one from [`config/global.ini`](https://github.com/piwik/piwik/blob/ae8a94575735b4ef0e0249cebe0087462f429715/config/global.ini.php#L139):
 
```
; if you set it to 1 and want the Unique Visitors to be re-processed for reports in the past,
  drop all piwik_archive_* tables
```

That would help to see why Unique Visitors may work for the current year, but fails for previous years. And it would explain how to fix the issue.

(Is there a repo for the faqs? I tried [searching](https://github.com/search?utf8=%E2%9C%93&q=org%3Apiwik+%22metric+for+Yearly%22&type=Code&ref=searchresults) [for](https://github.com/search?utf8=%E2%9C%93&q=org%3Apiwik+%22By+default+Piwik+will+not+process%22&type=Code&ref=searchresults) [it](https://github.com/search?utf8=%E2%9C%93&q=org%3Apiwik+%22query+to+process+the+number+of+unique%22&type=Code&ref=searchresults), but could not find it. Hence, I could not upload a pull request)

**Comment by halfnibble** [comment]
Just curious. dropping `piwik_archive_*` is going to drop a lot of tables going back a long ways. Is this data stored somewhere else? How is it *regenerated*?  I don't want to be the cause of years worth of data loss.

**Comment by caistleitner** [comment]
> Is this data stored somewhere else? How is it regenerated?

Since that discussion is coming over from #11179, the relevant part from the [comment there](https://github.com/piwik/piwik/issues/11179#issuecomment-274492493) is

> [...] (if you've still got the raw input data for them!) [...]

The raw data is stored it the `log_*` tables.

If you've _not_ pruned them in the past and if you've _not_ set them to get pruned automatically, then the reports get regenerated upon need.

If you've pruned them in the past or if you've set them to get pruned automatically, you pruned the raw input data away. Not sure there is an easy way to get unique visitors if you no longer have the raw input data. Maybe your backups allow to reclaim the data.

But regardless and obviously: Do make backups before dropping tables :-)

**Comment by mattab** [comment]
Thanks for the note! we've updated the FAQ: https://piwik.org/faq/how-to/faq_113/
