### ISSUE TITLE
UI: Default value for select not selected when it's zet to 0

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#11268]
I'm trying to understand why it's always select item with ? value.
Example:
```
<div piwik-field uicontrol="select" name="siteid"
	 title="{{ 'Params_site'|translate }}"
	 value="0"
	 inline-help="{{ 'Params_sites'|translate }}"
	 options='{{ data.item.sites|json_encode }}'>
</div>
```

And expected that the item with value 0 will be selected but other value selected. If I change value to en empty string when it's working as expected.

Any suggestion?

**Comment by mattab** [comment]
@Globulopolis do you experience this issue in a custom plugin you are developing, or in an existing core UI or marketplace plugin?

Maybe @tsteur has some idea?

**Comment by tsteur** [comment]
You need to make sure the variable type is the same. Likely there are integers in options vs string passed via value.
