### ISSUE TITLE
issue on piwik installation

### ISSUE THREAD

**Issue by jayapratha** [piwik/piwik#11286]
Hi,

I have installed piwik in my server, it has installed successfully. But i can't view anything in my dashboard, piwik logo's on left hand side and etc. Settings menu only i can view on left hand side, if i click any menu's in settings its not working. 

How to resolve this problem?

**Comment by Findus23** [comment]
Are there any errors in the Console? Are you by change using an ad-blocker which is blocking all js files called "piwik"?

**Comment by jayapratha** [comment]
i did't find any errors in that and not using any ad-blocker..

**Comment by mattab** [comment]
Hello @jayapratha please check our FAQ here: https://piwik.org/faq/troubleshooting/faq_135/
