### ISSUE TITLE
FAQ improvement for faq_98 / Using Apache Module RPAF

### ISSUE THREAD

**Issue by bohnelang** [piwik/piwik#11281]
https://piwik.org/faq/how-to-install/#faq_98

How do I configure Piwik when the server is installed behind a proxy?

Second way:

Running piwik on an Apache web server behind a reverse-proxy one can use the RPAF Apache module to replace remote address by HTTP_X_FORWARDED_FOR  address.

```
On Debian/Ubuntu:
apt-get install libapache2-mod-rpaf
edit the /etc/apache2/mods-enabled/rpaf.conf

<IfModule rpaf_module>
        RPAFenable                On
        RPAFsethostname      On
        RPAFproxy_ips           IP-OF-YOUR-PROXY-SERVER
        RPAFheader                X-Forwarded-For
</IfModule>

apachectl restart
```
More information about RPAF: https://github.com/gnif/mod_rpaf
---

Apache 2.4 and 2.5:
https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html

**Comment by mattab** [comment]
Hi @bohnelang 

thanks for the note. Added to the FAQ `an alternative solution on Apache 2.4 and Apache 2.5 is to use mod_remoteip to override the client IP with the IP as provided by a proxy or load balancer. Then you won’t need to specify these Piwik config settings.`
