### ISSUE TITLE
Missing visitors Piwik 3.0.2

### ISSUE THREAD

**Issue by MWisotzki** [piwik/piwik#11289]
Again, sorry for my bad english....

My problem:

In the moment I use Piwik 3.0.2-b2

At the same time, I use the tool tawk.to. If I can see a visitor in tawk.to, in about 50% I don't see the visitor in Piwik.

This is my tracking code:

<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//xxx.xxx/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

I use also the picture script with noscript  -  I dont can copy it in here, because I will not shown...

What can I do? Thanks for reply!!!

**Comment by Findus23** [comment]
Is it possible that tawk.io doesn't exclude users who have Do-not-track enabled? Could it be that this explains the difference.

**Comment by MWisotzki** [comment]
Hello an thanks for reply!

I disabled all do-not-track options, so normaly I get the same visitor in Piwik and tawk.to

**Comment by sgiehl** [comment]
See http://piwik.org/faq/troubleshooting/faq_50/ for possible reasons...

**Comment by MWisotzki** [comment]
The best way...just closing

**Comment by sgiehl** [comment]
I can't determine any problem within Piwik based on your descriptions. Also I've provided a link that should point out why the numbers could differ. If there would be any problem in tracking, guess we would get more reports.
