### ISSUE TITLE
Tracking code is wrong for piwik server behind a proxy

### ISSUE THREAD

**Issue by bohnelang** [piwik/piwik#11282]
We use piwik behind a reverse proxy and as generating the tracking code the server shows the _intranet view_ like this: //piwik.mydomain.de/piwik/

```
  (function() {
    var u="//piwik.mydomain.de/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
```
 
The _internet view_ instead is: //www.mydomain.de/piwik/

Thus it would be nice if I could set a u-variable on the page where the tracking code is generated and that value overrides the system generated value u. 

A variable in config/config.ini.php would good a well. Adding this pice of information at FAQ: "Using piwik behind a proxy" would be nice.

Same as tracking image...

**Comment by mattab** [comment]
Thanks for the report @bohnelang 
I think this duplicates: https://github.com/piwik/piwik/issues/6644

**Comment by MESWEB** [comment]
For my reason. Issue was:
disabled mod_security
