### ISSUE TITLE
System Check widget disappeared from admin homepage in 3.0.1-b3

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11299]
Probably regressed /buggy change in https://github.com/piwik/piwik/pull/11288

regression visible in UI tests

**Comment by sgiehl** [comment]
Yes it is: See https://github.com/piwik/piwik/pull/11288/commits/d38c8042d79afcfb6b6704d9aa44e9641c9458dd#diff-ba052faba7db018ae5ee1f72ffdbc950
The second parameter of `$widgetsList->isDefined` needs to be the action, not the name
