### ISSUE TITLE
how to update piwik 3.0.0? hidden link

### ISSUE THREAD

**Issue by cmdtstof** [piwik/piwik#11303]
hi
since v3.0.0 the "new update piwik 3.0.1" button expands when hover, but when trying to move to the expanded area, the expanding will be hidden again.
update is only working with getting the link out from source code!
is not working with firefox, chromium, opera.

i suggest to add an update link in the administration section for a fallback solution.

thanks
stof

**Comment by Findus23** [comment]
See #11111 for more information.

**Comment by CheweyZ** [comment]
This has been patched already

**Comment by cmdtstof** [comment]
thanks
