### ISSUE TITLE
How to prepend logged url without setting the whole url?

### ISSUE THREAD

**Issue by mronnlun** [piwik/piwik#11300]
We have a government site http://www.someagency.eu that is public and requires no login. There is also a subsite with electronic services requiring login, e.g. https://eservices.someagency.eu. All start pages for the e-services are on the public site. In some cases the url's for the sites can be the same, e.g. there can be both http://www.someagency.eu/somepage and https://eservices.someagency.eu/somepage.

When tracking that site we would like to log the used url as normal but prepend it with the site name, e.g. logged url would be /public/somepage and /eservices/somepage.

Can I prepend the logged url somehow or do I have to use setCustomUrl and set it like '/public/' + location.href?

**Comment by tsteur** [comment]
It should be still a URL that starts with http:// so I would rather do something like `http://public.$yourdomain` and make it a subdomain or you can prepend it to the your path like `http://$yourdomain/public/$yourpath`. `'/public/' + location.href` would result in `/public/http://$yourdomain`. If you need help with JavaScript you could for example ask in our forums: https://forum.piwik.org
