### ISSUE TITLE
Seeing issue with GD > 2.x + Freetype (graphics) in Piwik 3.0

### ISSUE THREAD

**Issue by ksachdeva11** [piwik/piwik#11304]
<img width="1148" alt="screen shot 2017-01-31 at 3 06 08 pm" src="https://cloud.githubusercontent.com/assets/24254124/22459499/d33d18cc-e7c6-11e6-86fe-99bd2c1d4372.png">

I have installed GD with freeType but still seeing this error on installation. Not able to proceed further without this. Please help

**Comment by cybernet** [comment]
it required a version above 2+. are you sure you meet this requirement ?

**Comment by mattab** [comment]
It should work. if still not working for you please post here your phpinfo so we can check you have it enabled

**Comment by tsteur** [comment]
I think the problem why so many mention this is probably because gd and freetype is grouped into one check
