### ISSUE TITLE
Outdated custom howto

### ISSUE THREAD

**Issue by schwindelbub** [piwik/piwik#11309]
Hi,

the howto "http://piwik.org/blog/2014/08/create-custom-theme-piwik-introducing-piwik-platform/" is with Version 3 outdated. 

And even this too: http://developer.piwik.org/guides/theming
The Command `./console generate:theme` doens't exists anymore.

Or is there a new howto?

Best Regards,
Christian

**Comment by mattab** [comment]
Hi there,

The command `./console generate:theme` still exists, but first you need to enable developer mode via `./console development:enable`
