### ISSUE TITLE
bug with "and" key word

### ISSUE THREAD

**Issue by beemoon** [piwik/piwik#11313]
Hello,
if you have word "and" in action like that

piwik.php?action_name=test%20and%20foobar

"test and foobar" is title of your web page in html title tag

you will get a acces denied to piwik.php file and no track for your page or website !!!!

(debug with console browser in firefox)

**Comment by sgiehl** [comment]
> `piwik.php?action_name=test%20and%20foobar` 

this request can't work as tracking requires `idsite` param
