### ISSUE TITLE
bug with "and" key word (#11313)

### ISSUE THREAD

**Issue by beemoon** [piwik/piwik#11314]
of course piwik.php?action_name=test%20and%20foobar is just a part of complet url
I ommit  idsite and others!!! but the bug is here!!! So please check before to close

**Comment by sgiehl** [comment]
I had tested that on my local machine and on our demo. Tracking works fine with an `and` within the action name. Do you maybe have some security software running on your server that causes that problem? maybe something like mod_security or similar?

**Comment by beemoon** [comment]
Hello,

no security.

I check all conf apache, php, firewall, htaccess during 2 days !!!!

I discovered if i just change title without "and" all it ok

see screenshoot

**Comment by sgiehl** [comment]
Which version of Piwik are you using? and do you have any third party plugins installed?

**Comment by beemoon** [comment]
the last version and none plugins

**Comment by beemoon** [comment]
New test with word "or" in title

same issu as "and"

**Comment by mattab** [comment]
Please open a new issue and send us steps to reproduce, or exact piwik.php request you used. We cannot reproduce this
