### ISSUE TITLE
Possible issue with install "Guzzle Abandoned"

### ISSUE THREAD

**Issue by CheweyZ** [piwik/piwik#11318]
![image](https://cloud.githubusercontent.com/assets/19643053/22613239/8ac07f72-eadb-11e6-8578-efdb662f86f3.png)

this is seen on a fresh install of Piwik dev I'm not sure if it is going to cause any issues but src file should be updated for its new address

**Comment by mattab** [comment]
Thanks for the report. This is a requirement from the `aws/aws-sdk-php` library which is only used in dev.  so nothing really important and likely will be fixed in aws/aws-sdk-php
