### ISSUE TITLE
Scheduled PDF Reports: Report Referrer Type shows only keywords but not detailed titles

### ISSUE THREAD

**Issue by mihadd** [piwik/piwik#11323]
The referrer type report shows only keywords like search engines, websites, ... for the entries. It should show detailed titles.
![grafik](https://cloud.githubusercontent.com/assets/25606657/22684952/bfae930a-ed1e-11e6-8e7c-fccc961daf6a.png)

**Comment by sgiehl** [comment]
This is a general bug that occurs when showing the report "flat"

**Comment by sgiehl** [comment]
Thinking a bit about this actually points out, that flattening this report doesn't really make sense, as it would show the same as the report displaying all referrers. I'll try to disable flattening for this report.

**Comment by sgiehl** [comment]
That won't be as easy as I thought. We currently set the `flat` parameter for all reports rendered for scheduled reports. This triggers the flattener to flatten the report, even if the report isn't able to handle that in any way.

I guess we need to find a way to define if a report can/should be shown flat in scheduled reports, but I'm not sure right now how to solve this best.

@mattab @tsteur any suggestions?

**Comment by tsteur** [comment]
The only way I can think of is to change the API method and remove flatten parameter or to keep API always set it to `false` in the API method if possible?

Problem is that scheduled reports doesn't consult viewDataTable about which features are enabled etc

**Comment by sgiehl** [comment]
@tsteur  The API method doesn't have any flat param. 
The DataTablePostProcessor handles this using the request parameter: https://github.com/piwik/piwik/blob/3.x-dev/core/API/DataTablePostProcessor.php#L172
And I didn't find a way to manipulate the request from within the API.

**Comment by tsteur** [comment]
I just had a look and it is tricky indeed.

I did make it work with this logic:

```php
        if (Common::getRequestVar('flat', 0, 'int') && $idSubtable === false) {
            $dataTable->queueFilter('GroupBy', array('label'));
        }
```

but not sure about any side effects. To boost performance it would also need to set `expanded=1` when flat is loaded.

Another workaround, and probably better and faster solution is to add a new method to report class like `function supportsFlatten() {return true}`. I think in the post processor we have the report already anyway and could call this method. Ideally, we would then also in `ViewDataTable` configure the config property `$view->config->show_flatten_table` automatically but not sure if that would work or if we'd break something as we would maybe suddenly enable flatten table somewhere where it was disabled before (I don't think so since it is configured after config creation in ViewDataTable).

**Comment by tsteur** [comment]
I haven't tested it but there should be an easier solution like 

```php
     if (Common::getRequestVar('flat', 0, 'int') && $idSubtable === false) {
            $dataTable->disableFilter('Flatten');
        }
```

and then we only need to make sure to put logic of postprocessor into a filter like this:

```php
            $flattener = new Flattener($this->apiModule, $this->apiMethod, $this->request);
            if ($this->includeAggregateRows) {
                $flattener->includeAggregateRows();
            }

            $recursiveLabelSeparator = ' - ';
            if ($this->report) {
                $recursiveLabelSeparator = $this->report->getRecursiveLabelSeparator();
            }

            $dataTable = $flattener->flatten($dataTable, $recursiveLabelSeparator);
```

We are also doing this for other things where we need to disable sort etc and I think this may be the best solution, if we can decide in the API method itself when to disable filter "flatten"

**Comment by sgiehl** [comment]
sounds good. Will give it a try.

**Comment by sgiehl** [comment]
It's not as easy as it seemed to be. The filter method of a DataTable filter gets the datatable as parameter, so it can be used to manipulate it using the objects methods. But it can't be easily replace. But that's what the flattener currently does: creating an empty clone and creating a new table. So we might need to manipulate it in another way. Will check that next week

**Comment by mattab** [comment]
Referrer type is now not flattened:

![referrer type](https://cloud.githubusercontent.com/assets/466765/24445199/6339e2ce-1469-11e7-8af9-d53d621157ee.png)
