### ISSUE TITLE
segment not valid-errors when filtering for operating system

### ISSUE THREAD

**Issue by phip1611** [piwik/piwik#11321]
When I try to create a segment with a filter for a specific operating system piwik throws a bunch of errors. This happens when creating a segment that is only filtering for a operating system as well as combining other filters with the operating system. Other filters like provider or site url work fine, also in AND/OR-combinations.

`ERROR: Failed to get data from API: The segment 'deviceType%3D%3DDesktop%3BoperatingSystemCode%3D%3DWIN%2CoperatingSystemCode%3D%3DMAC' is not valid. #0 /piwik/core/Segment.php(155): Piwik\Segment\SegmentExpression-&gt;parseSubExpressions() #1 /piwik/core/Segment.php(106): Piwik\Segment-&gt;initializeSegment('deviceType%253D...', Array) #2 /piwik/core/Archive.php(225): Piwik\Segment-&gt;__construct('deviceType%253D...', Array) #3 /piwik/plugins/VisitsSummary/API.php(29): Piwik\Archive::build('1', 'day', '2017-01-07,2017...', 'deviceType%253D...') #4 [internal function]: Piwik\Plugins\VisitsSummary\API-&gt;get('1', 'day', '2017-01-07,2017...', 'deviceType%253D...', 'nb_uniq_visitor...') #5 /piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array) #6 /piwik/plugins/API/API.php(388): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #7 [internal function]: Piwik\Plugins\API\API-&gt;get('1', 'day', '2017-01-07,2017...', 'deviceType%253D...', Array) #8 /piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array) #9 /piwik/core/Plugin/Visualization.php(264): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #10 /piwik/core/Plugin/Visualization.php(181): Piwik\Plugin\Visualization-&gt;loadDataTableFromAPI() #11 /piwik/core/Plugin/Controller.php(249): Piwik\Plugin\Visualization-&gt;render() #12 /piwik/plugins/VisitsSummary/Controller.php(121): Piwik\Plugin\Controller-&gt;renderView(Object(Piwik\Plugins\CoreVisualizations\Visualizations\JqplotGraph\Evolution)) #13 [internal function]: Piwik\Plugins\VisitsSummary\Controller-&gt;getEvolutionGraph() #14 /piwik/core/FrontController.php(542): call_user_func_array(Array, Array) #15 /piwik/core/FrontController.php(137): Piwik\FrontController-&gt;doDispatch('VisitsSummary', 'getEvolutionGra...', Array) #16 /piwik/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #17 /piwik/index.php(27): require_once('/www/htdocs/w01...') #18 {main}`

**Comment by phip1611** [comment]
**Update**
The problem occurs when filtering for Windows or Mac but not when filtering for Android

**Comment by tsteur** [comment]
Same problem here when using eg this segment: 
![image](https://cloud.githubusercontent.com/assets/273120/22809659/c0c2a55c-ef98-11e6-9895-ba03df50156e.png)

It seems to first work but when then selecting the segment from the list of segments it does no longer work and fails like this:

![image](https://cloud.githubusercontent.com/assets/273120/22809674/d4640d62-ef98-11e6-800f-eab74286b8b7.png)
