### ISSUE TITLE
Manage Goals broken in 3.0.1

### ISSUE THREAD

**Issue by tipmaster** [piwik/piwik#11327]
Getting the following error:

The following error just broke Piwik (v3.0.1):

Key "description" for array with keys "idsite, idgoal, name, match_attribute, pattern, pattern_type, case_sensitive, allow_multiple, revenue, deleted" does not exist in "@Goals/_listGoalEdit.twig" at line 51
in
/mgmt/piwik/3_0/piwik/vendor/twig/twig/lib/Twig/Template.php line 501

Any help?

**Comment by JimmyKuruvilla** [comment]
Getting the same thing after an upgrade to 3.01:

![image](https://cloud.githubusercontent.com/assets/7905473/22833263/e40449fc-ef76-11e6-94c4-ba512ddaf8a2.png)

**Comment by tipmaster** [comment]
I got this response from support which fixed the issue for me:

To answer your question: We haven't seen this error in Piwik 3 before. It sounds like there is a column "description" in the "piwik_goal" MySQL table missing. Can you or your system administrator execute this MySQL query and check if it works afterwards:

ALTER TABLE piwik_goal ADD `description` VARCHAR(255) NOT NULL DEFAULT '';

**Comment by JimmyKuruvilla** [comment]
@tipmaster thanks, that was definitely the problem. I guess the db upgrade missed a step (or maybe skipping a version skipped a db migration).

**Comment by pgerstbach** [comment]
I had the same issue, now it works after altering the table, thanks @tipmaster !

**Comment by DevDaveo** [comment]
+1
Having the same fatal error message too!

**Comment by sbuchali** [comment]
We had the same error.

Piwik just told the administrator: 
> oops, an error occured ... contact your administrator

Nothing more. Only a 500 error in the access.log, but no more specific error message.

The solution posted by @tipmaster did also solve the problem for us. It seems that goals that were created in Piwik 2.x did not have the "description" column yet, which causes the error in 3.x
