### ISSUE TITLE
WARNING: /plugins/CorePluginsAdmin/Controller.php(272) ob_clean(): failed to delete buffer. No buffer to delete

### ISSUE THREAD

**Issue by phip1611** [piwik/piwik#11320]
Hello there,
I deleted a segment and got this warning. 

_WARNING: ...piwik/plugins/CorePluginsAdmin/Controller.php(272): Notice - ob_clean(): failed to delete buffer. No buffer to delete - Piwik 3.0.1_

PS: Keep going, Piwik is a great product!

**Comment by tsteur** [comment]
Thanks for the feedback. Did it show a safemode page (a page with white background and black text only)? Which Piwik version are you using?

It should not show the safemode page when deleting a segment but we should also make sure to check if a buffer is open before deleting it.

**Comment by phip1611** [comment]
> Thanks for the feedback. Did it show a safemode page (a page with white background and black text only)? Which Piwik version are you using?

No.

> Which Piwik version are you using?

3.0.1
