### ISSUE TITLE
Goal plugin is falsely reported to be deactivated on API request 

### ISSUE THREAD

**Issue by jvolker** [piwik/piwik#11326]
I'm trying to access the API with `/?module=API&method=Goal.addGoals&idSite=2&name=my%20goal&matchAttribute=url&patternType=contains&pattern=example%20pattern&format=JSON&token_auth=[tokenAuth]` from Node.js

I'm getting back the following error even though the goal plugin has been activated:
`{ result: 'error',
  message: 'The plugin Goal is not enabled. You can activate the plugin on Settings &gt; Plugins page in Piwik.' }`

I'm using Piwik 3.0.1
Please let me know, if this is not enough information and what else I should provide!

Thanks.

**Comment by tsteur** [comment]
It should be `Goals.addGoal` not `Goal.addGoals`
