### ISSUE TITLE
No entry or class found for 'Piwik\Plugins\*\Menu' after upgrading to 3.0.1

### ISSUE THREAD

**Issue by hansfn** [piwik/piwik#11349]
Hi!

After upgrading I got an error page saying first `No entry or class found for 'Piwik\Plugins\Actions\Menu'` and then `No entry or class found for 'Piwik\Plugins\UserCountryMap\Menu'`. I tracked it down to tmp/cache/tracker/eagercache-301-ui.php that contained

    [...]
    'PluginActionsMenuPiwik\\Plugin\\Menu' => 'Piwik\\Plugins\\Actions\\Menu',
    [...]
    'PluginUserCountryMapMenuPiwik\\Plugin\\Menu' => 'Piwik\\Plugins\\UserCountryMap\\Menu',

I know you can work-around the problem, by setting `enabled = 1` in the `[Development]` section of config/global.ini.php

Anyway, I realized what is going on. Before upgrading I forgot to delete all files from my earlier Piwik 2 installation. That is a user error, but please don't close this as a "won't fix". I think a lot of users can do this mistake, and it's hard to find the work-around - and all you get is the error page.

Could Piwik use config/manifest.inc.php when generating eagercache-301-ui.php to avoid this problem? I don't know. When you finally get to the filesystem integrity check (which isn't displayed if use the work-around above) you see the files that are leftover form 2.x and should be removed. Easy. I removed eagercache-301-ui.php so the system check page displayed.

**Comment by tsteur** [comment]
We have recently fixed this and we now show a list of files that should be deleted based on manifest etc. :)
