### ISSUE TITLE
piwik has dropped support for the most used enterprise linux distribution

### ISSUE THREAD

**Issue by roweryan** [piwik/piwik#11345]
Seriously guys? Red Hat 7 and CentOS 7 are no longer supported?

**Comment by tsteur** [comment]
Hi, we still support Piwik 2.X in case you are on an older PHP version.

**Comment by tsteur** [comment]
See https://piwik.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/

**Comment by sgiehl** [comment]
Maybe that's not visible enough. We could add a second download button for LTS version or at least a small note with a link

**Comment by roweryan** [comment]
Phew :+1: 

I have an update script that uses the latest.zip file. Maybe the web gui could link to the LTS release page? (and the faq entry too)
