### ISSUE TITLE
It's me again! question about the "others" data.

### ISSUE THREAD

**Issue by ChrisR1993** [piwik/piwik#11348]
Hi everyone,

I have a question about the "others", first please refer this page which said after the top 500 or top 1000 rows, Piwik automatically groups pages.(https://piwik.org/faq/how-to/faq_54/1) 
but in my case, the row dosn't reach 500 or 1000 at all,

what's the difinition of the number(row or visite number)? which number reached 500 or 1000, Piwik automatically groups pages to others?
And if the number (rows or visitor number) reached 500, the "others" will be gone? 

I will appreciate your kindly help.
Cheers

**Comment by tsteur** [comment]
It's rows. Eg when you have more than 500 different referrers, all others >= 501 will be grouped into an others row.

**Comment by ChrisR1993** [comment]
@tsteur 
Thanks tsteur, appreciate your answer.
The picture below is my understanding of your answer, is this right?
![github](https://cloud.githubusercontent.com/assets/25838575/23239429/87c1190c-f9aa-11e6-8163-74bea2567c88.png)

Regards,

**Comment by tsteur** [comment]
Yep 👍

**Comment by ChrisR1993** [comment]
@tsteur 
Hi tsteur, sorry to bother you again 'cause I had another question.
Eg the number of  a PDF link unic download is "57", and I searched the link with customer segment function, then the result showed that the same link's unic download number turned to "127". (I think some of it gruoped into the "others", so the number is different)

is this by the same reason? if it is, on what condition did the number changed? because by searching in customer segment function, some links' number didn't change but some links did.

thanks very much as always.
Chirs

**Comment by tsteur** [comment]
When you apply a segment to a report, the value for a uniq download should stay the same or decrease but usually not increase (unless some of the download urls were stored url encoded and some url decoded).

**Comment by ChrisR1993** [comment]
@tsteur 
thank you for the repaly.
![question](https://cloud.githubusercontent.com/assets/25838575/23288100/bd24bbc8-fa84-11e6-83a1-e21bcd24c440.png)
Eg Z's value is 59 displayed by Piwik, I apply a segment by searching Z and the result is 164.
so the value (164-59) is included into "others"?

**Comment by ChrisR1993** [comment]
@mattab 
![version](https://cloud.githubusercontent.com/assets/25838575/23296006/8b195634-fab6-11e6-9dc8-4fc0a712af12.PNG)
mattab, is this(answer form tsteur) also same with the old version? 'cause for now my Piwik version is
2.15.0

Regards,
