### ISSUE TITLE
I only see real time visitors after I installed Piwik. 

### ISSUE THREAD

**Issue by bobbypiwik** [piwik/piwik#11353]
I only see real time visitors after I installed Piwik. I am tracking all the real time visitors correctly. However, the traking for other systems doesn't work. like total visitors to geograph. In fact, nothing on my dashboard works besides real time visitors. What should be the issue? isn't this plug and play software?

**Comment by RMastop** [comment]
Hi @bobbypiwik ,
Please check the following page:
https://piwik.org/docs/setup-auto-archiving/
It makes sure report data is generated using a cron job.

**Comment by bobbypiwik** [comment]
Should that fix the issue? I am working on it right now. Will I see the results directly? or should I wait

**Comment by bobbypiwik** [comment]
Is there anything else I should do? Or should the Cron configuration fix all my problems

**Comment by RMastop** [comment]
It should fix the issue after the first run has finishen.

**Comment by bobbypiwik** [comment]
Well It's installed but isn't working well yet. How lond does it take for the first run to finish

**Comment by RMastop** [comment]
It should be real quick, depending on the amount of data. Any errors show up in browser console, when accessing the dashboard?

**Comment by bobbypiwik** [comment]
No none of the errors show. Just, I only see the real time visitors reports show no data at all. That's the error

**Comment by bobbypiwik** [comment]
What should be our next step?

**Comment by RMastop** [comment]
Are you sure data is tracked and added to the database?  Have you added the tracking tag tournament the website?

**Comment by bobbypiwik** [comment]
Yes I'm sure the data is tracked well. When i activate the open graphs in my dashboard it steadily shows me the graph. In addition, I see every real time visitor coming in. And, when I log in myself. I see the notification. So the system is accurate it just doesn't communicate toward the graphs and reports

**Comment by bobbypiwik** [comment]
With dashboard, I am talking about the dashboard in wordpress

**Comment by bobbypiwik** [comment]
Your my only help, could you respond quiker. I need to fix this. I appreciate the support!

**Comment by RMastop** [comment]
I'm Sorry, can't help you with that one. I never used the dashboard in Wordpress. This is the support forum Piwik. You should try the Wordpress plugin community or file a bug in the wp-piwik issue tracker.

**Comment by bobbypiwik** [comment]
Oke, I manually posted my code to the website. What can be the problem now? Btw the only thing this plugin does is put the tracking code on the right location. So it's nothing new, and you can help me out. I would appreciate it if you do

**Comment by RMastop** [comment]
Please have a look at the plugin if you need to have reports within Wordpress. It does more than just adding the tracking code. The plugin explains how to use it. Since it is not an issue in Piwik, this issue can be closed.

**Comment by bobbypiwik** [comment]
I am not talking about the fact I want to see statistics in wordpress. I want my statistics to pop op in reports and show in graphs in the regular dashboard of the official Piwik login, I re-installed Piwik with softuculous this time, It created the Cron automatic. Again, it's tracking the real time visitors. And, again its not showing me the reports and other side information in the graphs. I just want the data, to be imported to the statistics. Moreover, I checked wheter the chrons are working correctly, and they are gathering the data succesfully. So it's not that the data is not gathered. it just isn't communicated to the reports. Where should this issue be resolved?

**Comment by mattab** [comment]
Check that you're looking at the right date maybe. Data should be displayed after it's been processed via cron or via the browser trigger archiving (which is On by default in Settings)
