### ISSUE TITLE
transparent icons are hard to recognize on dark backgrounds

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#11352]
Follow-up to discussion in #11271

![bildschirmfoto von 2017-01-24 09-36-38](https://cloud.githubusercontent.com/assets/6266037/22239923/d2a76d62-e218-11e6-9238-e865a20ef8f9.png)

I have now modified the script so that instead of replacing white with transparency it floodfills all white parts with transparency beginning from all four corners. That way white parts of icons (e.g. Quicktime, Windows Media) will stay white and the icons look great on light grey backgrounds.
While it improves many icons there are still some left, that are impossible to recognize on dark backgrounds (mostly because they are only made of dark lines) 
![bb](https://cloud.githubusercontent.com/assets/6266037/23093618/8ab10bba-f5e8-11e6-94a9-b41c8d82394a.png)
![java](https://cloud.githubusercontent.com/assets/6266037/23093620/a2599bec-f5e8-11e6-871b-d37f8fbaf0ad.png)
Because of that I would recommend adding a white background with CSS in these cases (mostly the black popup)

**Comment by mattab** [comment]
> I have now modified the script so that instead of replacing white with transparency it floodfills all white parts with transparency beginning from all four corners. That way white parts of icons (e.g. Quicktime, Windows Media) will stay white and the icons look great on light grey backgrounds.


This sounds ideal! Glad you could make this work.

> Because of that I would recommend adding a white background with CSS in these cases (mostly the black popup)

:+1:

**Comment by Findus23** [comment]
I have now added a new release on https://github.com/Findus23/device-icons. Should I create a new pull request or wait until we have found a solution for `Findus23/device-icons`? (e.g. use as a composer package similar to `piwik/searchengine-and-social-list`)

**Comment by mattab** [comment]
@Findus23 shall we create new issue regarding finding a solution to package icons in Piwik core via composer or submodule etc. ?

If we can find a solution quickly then maybe it's worth waiting to push the new icons to KISS

**Comment by Findus23** [comment]
> @Findus23 shall we create new issue regarding finding a solution to package icons in Piwik core via composer or submodule etc. ?

see #11370

**Comment by Findus23** [comment]
This should have greatly improved with https://github.com/piwik/piwik-icons/commit/1161949e5ca23de8dbd1c261de03772fcc627436

![screenshot_20170407_132426](https://cloud.githubusercontent.com/assets/6266037/24798307/89d8941a-1b95-11e7-8116-7179b9ac4db4.png)
