### ISSUE TITLE
Security Check warning

### ISSUE THREAD

**Issue by MWisotzki** [piwik/piwik#11361]
I use Piwik 3.0.2-b4

I get some warnings...
![piwik fehler sicherheitsprufung](https://cloud.githubusercontent.com/assets/24963870/23102306/27887ec8-f6a7-11e6-9fb9-eea2c6669508.jpg)

![piwik fehler sicherheitsprufung core](https://cloud.githubusercontent.com/assets/24963870/23102308/2dda7f92-f6a7-11e6-836e-fe5d90986cfa.jpg)

**Comment by sgiehl** [comment]
which php version are you using?

**Comment by sgiehl** [comment]
This one seems to duplicate https://github.com/piwik/plugin-SecurityInfo/issues/13

**Comment by MWisotzki** [comment]
I use php 7.1.1
