### ISSUE TITLE
No JavaScript-Tracking-Code

### ISSUE THREAD

**Issue by cleicht** [piwik/piwik#11364]
In the actual Piwik 3.0.2-b4 no JavaScript-Tracking-Code will be shown in Administration Website Tracking Code. The Image altenative is ok.

**Comment by mattab** [comment]
Hi @cleicht 
Thanks for the report!


Do you see any error in the browser console?
Could you post a screenshot?

**Comment by cleicht** [comment]
Sorry there are no deep informations about the Problem in Chrome
Only the Fiel with Code is empty

Christian

*Von:* Matthieu Aubry
*Gesendet:* Montag, 20.Februar 2017 9:26AM
*An:* piwik@noreply.github.com <mailto:piwik@noreply.github.com>
*Cc:* Christian Leicht, Mention *
Titel:* Re: [piwik/piwik] No JavaScript-Tracking-Code (#11364) 	 
Christian Leicht
Asternstr. 54
85368 Moosburg

**Comment by mattab** [comment]
Can you try to delete your browser cache and try again?

**Comment by cleicht** [comment]
It doesent change anything. The same on Firefox an Chrome. Also on a 
older Win7 PC.

*Von:* Matthieu Aubry
*Gesendet:* Montag, 20.Februar 2017 4:46PM
*An:* piwik@noreply.github.com <mailto:piwik@noreply.github.com>
*Cc:* Christian Leicht, Mention *
Titel:* Re: [piwik/piwik] No JavaScript-Tracking-Code (#11364) 	 
Christian Leicht
Asternstr. 54
85368 Moosburg

**Comment by mattab** [comment]
Could you please email us Piwik URL and some user with admin access to http://piwik.org/contact/ with a link to this ticket? we will investigate and try to fix this issue. thanks

**Comment by cleicht** [comment]
i have send it with the Contact Form

**Comment by mattab** [comment]
Hi @cleicht 

Getting error: "Class 'Piwik\Plugin\Settings' not found" in the HTTP response for the JS tracker code. I think this error is caused by some third party plugin you use. So we suggest to disable your third party plugins (any plugin not made by "Piwik" or "InnoCraft") until you find which plugin caused this issue. Then you can re-enable any plugin that were not problematic
