### ISSUE TITLE
I need your kindly help....

### ISSUE THREAD

**Issue by ChrisR1993** [piwik/piwik#11365]
Could everyont take a little time to look my question by the link?

https://forum.piwik.org/t/why-the-number-is-different/23206
https://forum.piwik.org/t/why-it-has-difference-between-page-and-download-display/23202
I'll be very appreciate your help!

thank you!

**Comment by mattab** [comment]
Hi @ChrisR1993 

please open a new issue with description etc. rather than linking to forums. thanks
