### ISSUE TITLE
Piwik 3.0.2-b4 Dashboard 

### ISSUE THREAD

**Issue by MWisotzki** [piwik/piwik#11371]
I use Piwik 3.0.2-b4 with php 7.1.1

After update to 3.0.2-b4 all Dashboards are extremly slow.

**Comment by mattab** [comment]
Nothing should have changed regarding performance. please check you setup: https://staging.piwik.org/docs/setup-auto-archiving/

**Comment by Findus23** [comment]
I guess you mean https://piwik.org/docs/setup-auto-archiving/

**Comment by mattab** [comment]
Thanks @Findus23 !

**Comment by MWisotzki** [comment]
Thanks for reply, but I think its not the problem. I do the archiving manual - no better result. I install Piwik new - no result. I talk to my provider - everything works fine.

When I select the year 2017 in the dashboard, I get an error like this:

![piwik-error](https://cloud.githubusercontent.com/assets/24963870/23177049/c12d4f44-f865-11e6-87d4-a7dfbe19036c.jpg)

...and sorry for my bad english :-)

**Comment by mattab** [comment]
@MWisotzki see https://piwik.org/faq/troubleshooting/faq_19489/
