### ISSUE TITLE
cyrillic not work

### ISSUE THREAD

**Issue by andruwa13** [piwik/piwik#11373]
help me please
![bankoved - 19 2017 - - piwik 2017-02-20 15-00-10](https://cloud.githubusercontent.com/assets/5846351/23130297/93a78a08-f78e-11e6-8c3f-cd9781947125.png)

Docker container (MariaDB, Piwik, Nginx-Alpine)
![- - piwik 2017-02-20 17-05-08](https://cloud.githubusercontent.com/assets/5846351/23130376/e27e0706-f78e-11e6-8917-06995d30b85b.png)

**Comment by mattab** [comment]
Hi @andruwa13 

Could you please send us at http://piwik.org/contact/
 some access to your Piwik and steps to reproduce this issue?

**Comment by andruwa13** [comment]
@mattab 
![bankoved - 19 2017 - - piwik 2017-02-20 17-48-03](https://cloud.githubusercontent.com/assets/5846351/23132049/00a14ddc-f795-11e6-9503-cd2ffc1566a1.png)

russian lang - not work
![bankoved - 19 2017 - - piwik 2017-02-20 17-50-44](https://cloud.githubusercontent.com/assets/5846351/23132115/35acd7da-f795-11e6-9bb6-c17da7f4cb99.png)
english lang - work (80%)
![bankoved - sunday february 19 2017 - web analytics reports - piwik 2017-02-20 17-53-42](https://cloud.githubusercontent.com/assets/5846351/23132263/b0d966bc-f795-11e6-8c02-bdbd6a1524b1.png)

**Comment by mattab** [comment]
Can you reproduce this issue on http://demo.piwik.org/

**Comment by andruwa13** [comment]
@mattab on your demo site do not have user-profile
demo:
![virtual-drums com - 20 2017 - - piwik 2017-02-21 11-01-03](https://cloud.githubusercontent.com/assets/5846351/23157769/28c8da10-f825-11e6-86dd-b52b942f5986.png)
prod:
![bezprovodoff - 20 2017 - - piwik 2017-02-21 11-02-22](https://cloud.githubusercontent.com/assets/5846351/23157871/807f5928-f825-11e6-99dc-083a5a7da032.png)

**Comment by mattab** [comment]
Correct the visitor profile is not active on demo for privacy reasons

But I tested and it's working fine see: 
![works](https://cloud.githubusercontent.com/assets/466765/23179822/833f9aac-f86f-11e6-9087-564ecef1a6ea.png)


## please upgrade to PIwik 3.0.2-b5 http://piwik.org/faq/how-to-update/faq_159/

**Comment by andruwa13** [comment]
Thanks for the fix. Please add new tag to [docker container](https://hub.docker.com/r/library/piwik/tags/)

**Comment by andruwa13** [comment]
not work :( 
![bezprovodoff - 20 2017 - - piwik 2017-02-21 21-12-23](https://cloud.githubusercontent.com/assets/5846351/23180625/b189d890-f87a-11e6-84b5-91635bedf192.png)

  
![- - piwik 2017-02-21 21-13-15](https://cloud.githubusercontent.com/assets/5846351/23180633/b99bc502-f87a-11e6-89e6-55c604dce11c.png)

**Comment by andruwa13** [comment]
After rebooting the system started to work 
![bezprovodoff - 21 2017 - - piwik 2017-02-21 21-23-57](https://cloud.githubusercontent.com/assets/5846351/23181052/24c26362-f87c-11e6-94a2-83f9b5d6db36.png)
