### ISSUE TITLE
Feature Request: Add pagination to visitor log

### ISSUE THREAD

**Issue by tfrdidi** [piwik/piwik#11388]
Even for mid size piwik instances the **visitor log**, which loads all the visitor data at once, often exceeds the timeout. Adding some kind of pagination to that view to show only 10 - 20 visitors on one page, 

- improves the loading performance, 
- prevents browser lags when scrolling a 1 mile long page, and 
- reduces the db load.

**Comment by mattab** [comment]
> Even for mid size piwik instances the visitor log, which loads all the visitor data at once, often exceeds the timeout. 

Visitor Log already has pagination, in the bottom right of the report. Maybe you have selected `all` which loads all data but by default it loads 50
