### ISSUE TITLE
Click on defined segment generates "no data for this report"

### ISSUE THREAD

**Issue by JunkeAl** [piwik/piwik#11382]
We predefined some segments in Piwik, but if we click on one we get always "No data for this report"; but if we open the segment an click "Save & Apply" we get the needed data - looking forward to getting help. :)

**Comment by mattab** [comment]
Please try again in piwik-3.0.2-b5 

if you still have the issue please re-open

**Comment by mattab** [comment]
Beta instructions here: http://piwik.org/faq/how-to-update/faq_159/

**Comment by JunkeAl** [comment]
Dear mattab,

Thanks for help - I followed the instructions and the Beta 3.02. -B5 is shown, but if I click on update button nothing happens - and the layer with link "Please update now!" disappears always if I move the cursor down. Is there a trick?

**Comment by mattab** [comment]
this bug has been fixed since. But for now you should be able to move VERY fast the mouse and go to the bottom panel to click update?

**Comment by JunkeAl** [comment]
ah, clever! Works! Thanks :)
