### ISSUE TITLE
bug with "and" key word in title

### ISSUE THREAD

**Issue by beemoon** [piwik/piwik#11396]
version: Piwik 3.0.1 
standard install (on ovh server or localy apache2, php5.6 or 5.5)
in web page to track: just add in title html tag with word "and" or "or" (i.e: "beemoon and co")
put piwik code to track

check in debug browser console

web page not track in piwik

**Comment by Findus23** [comment]
I can't reproduce it. I have a page with 
```html
 <title>„Nacht­wan­de­rung“</title>
```
and it tracks without problems (nothing in js console, visit appears in piwik)
```http
GET https://piwik.example.org/piwik.php?action_name=„Nacht­wan­de­rung“&idsite=5&rec=1&r=288596&h=13&m=24&s=44&url=https://www.example.org/projekte/nachtwanderung/&_id=&_idts=1487766284&_idvc=1&_idn=1&_refts=0&_viewts=1487766284&send_image=1&pdf=0&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=0&res=1920x1080&gt_ms=114&pv_id=pW1LLj
Host: piwik.example.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: image/png,image/*;q=0.8,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://www.example.org/projekte/nachtwanderung/
Connection: keep-alive
```

> check in debug browser console

What is the error you get?

**Comment by beemoon** [comment]
try

<title>„Nacht­w an­d e­rung“</title>

space before and after "and",
the issue is with the word "and" not a word contening syllable "and"
It is the same with "or".

**Comment by mattab** [comment]
We cannot reproduce this issue
