### ISSUE TITLE
The parameter 'module' isn't set in the Request

### ISSUE THREAD

**Issue by nukuaes** [piwik/piwik#11398]
Hi, im use last beta version of piwik3, when i install the last update the page login show this.
The parameter 'module' isn't set in the Request, and a default value wasn't provided.
Regards

**Comment by Findus23** [comment]
As mentioned in #11395 this has already been fixed and should be included in beta 6.

Workaround is visiting https://piwik.mydomain.example/index.php?module=CoreHome for login.

**Comment by mattab** [comment]
fixed in beta6

**Comment by Kukitom** [comment]
I cant open the dashboard to make an update with the fix. and now? what cam i do?

**Comment by Findus23** [comment]
@Kukitom As mentioned above you can visit [YOUR-PIWIK-URL]/index.php?module=CoreHome

**Comment by Kukitom** [comment]
THX @Findus23 sorry my english and understanding not so god
