### ISSUE TITLE
The parameter 'module' isn't set in the Request, and a default value wasn't provided.

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#11395]
Since I have applied the patch of pull request #11358 I am experiencing a new bug. 

If I visit https://piwik.mydomain.example/ I get the following error:
> The parameter 'module' isn't set in the Request, and a default value wasn't provided.

![screenshot_20170222_101924](https://cloud.githubusercontent.com/assets/6266037/23204915/7db550bc-f8e8-11e6-885c-4b1bc993a8fe.png)

https://piwik.mydomain.example/index.php?module=CoreHome is working (shows the login form)

If I revert the patch, the bug vanishes, so it must have to do with the pull request (I assume this line: https://github.com/piwik/piwik/pull/11358/files#diff-719a15b635df457515639ff08ee921b3R711)

It's also visible in the UI tests of https://github.com/piwik/piwik/pull/11383#issuecomment-281379363

http://builds-artifacts.piwik.org/piwik/piwik/3.x-dev/22428/Login_login_form.png

**Comment by TheCodePianist** [comment]
I can confirm this bug after upgrading from Beta 4 to Beta 5. It happens when:

- One is logged out
- One tries to access the base-dir (piwik.domain.com).

I can also confirm the workaround of `?module=CoreHome`

**Comment by mattab** [comment]
Thanks. it's already fixed in git and will be published in the next beta
