### ISSUE TITLE
no more 'token_auth' column in user management, seems after upgrade to 3.0.2-b4

### ISSUE THREAD

**Issue by mpaolo** [piwik/piwik#11390]
Hi

I'm using API methods that require auth (to override IP). Suddenly that tracking disappeared, seems coincident with upgrade to 3.0.2-b4. 
A cue could be that, in 'user management' / 'create user', I don't see the token_auth column anymore (logged in as superuser of course) as shown in the docs, although I get the token in 'personal settings'.
Should I downgrade to e.g. 3.0.2-b3 as temp fix? how, in case

thx

**Comment by tsteur** [comment]
Hi,

we removed this column for security reasons. Only the user can see the token and nobody else.

**Comment by mpaolo** [comment]
ah ok ... 
then for the muting of the tracking might be due to just me, resetting the 'admin' flag for that user

BTW note that that 'changes' in the updates notice pointed to 3.0.1 changelog instead of 3.0.2 changelog. 

thank you!
