### ISSUE TITLE
Visitor map (showing cities) Error: visitorId is expected to be a 16 hex char string

### ISSUE THREAD

**Issue by pardvm** [piwik/piwik#11403]
**Description:**
When trying to open the visitor log (clicking on a circle corresponding to a given city from the visitor map panel) the error "Error: visitorId is expected to be a 16 hex char string" is shown

**Steps to reproduce:**

1. Access a visitor map panel from a site containing pages with no ASCII characters in their title
2. Zoom in the map as far as you can switch the view to "Cities":
![image](https://cloud.githubusercontent.com/assets/25912392/23261012/c597fd70-f9d4-11e6-96c2-27aaa9cfc5f1.png)
3. Click on a circle to open the visitor log

**Gotten result:**
![image](https://cloud.githubusercontent.com/assets/25912392/23260877/34ffee9e-f9d4-11e6-8ff3-35cd73fb47cb.png)

**Expected result:**
The visitor log opens as usually it does.

**Additional info:**
The visitor log opens correctly if accessed from the "Real time map" panel instead.

This can not be reproduced in other sites I have except those where page titles have non ASCII characters (like french ones: ^, ', ´, `,...) so I guess this could be related somehow with [Custom dashboards and visitor segments: The segment %s is not valid](https://github.com/piwik/piwik/issues/8323)

---

**Comment by mattab** [comment]
Thanks for the report, but we cannot reproduce it. It may not be caused by the non ascii characters. Could you maybe send us URL to reproduce this issue and login/password to your Piwik (temporary) by email at: http://piwik.org/support/ ? We would like to see this error and try understand what is the cause

**Comment by pardvm** [comment]
I cannot reproduce this issue anymore, so...
