### ISSUE TITLE
Error SSL certificate problem, verify that the CA cert is OK SSL3_GET_SERVER_CERTIFICATE: certificate verify failed

### ISSUE THREAD

**Issue by vopjie** [piwik/piwik#11402]
when i click the button to install theme or plugin, An error occurred!

![image](https://cloud.githubusercontent.com/assets/9351855/23253187/913d590c-f9ee-11e6-9e6a-dadb74b5758e.png)

**Comment by Findus23** [comment]
As mentioned in https://github.com/piwik/piwik/issues/7598#issuecomment-93247970 this is because the CA-Certificates of curl are outdated on your server.

**Comment by vopjie** [comment]
@Findus23 what can i do?

**Comment by Findus23** [comment]
Download http://curl.haxx.se/ca/cacert.pem and point to it in your php.ini:

```ini
[cURL]
curl.cainfo = "path_to\cacert.pem"
```

**Comment by mattab** [comment]
Thanks @Findus23 for posting the solution :
