### ISSUE TITLE
There is no region, city info in visitors log.

### ISSUE THREAD

**Issue by sitte** [piwik/piwik#11404]
There is no region, city info in visitors log.
I installed MaxMind Lite database, I choosed new database and in GeoIP, I can see there that my ip is in databas (there is info about my City on the right) but there is no info in visitors log. Should I set something on?
I have PIWIK 3.0.1 version.

**Comment by mattab** [comment]
It should work, but will only work for future visits. For past visits you can set geolocation data as well see: https://piwik.org/faq/how-to/faq_167/
