### ISSUE TITLE
Profile window are not closed completely - Piwik 3.0.2-b6

### ISSUE THREAD

**Issue by MWisotzki** [piwik/piwik#11413]
If I close a visitor's profile, the closing badges are not closed

![piwik-design-ii](https://cloud.githubusercontent.com/assets/24963870/23323634/b85ce574-fae9-11e6-9bce-bc4e1c35b7b0.jpg)

![piwik-design-fehler](https://cloud.githubusercontent.com/assets/24963870/23323617/9a73030e-fae9-11e6-82fa-01bfd9e7937a.jpg)

**Comment by sgiehl** [comment]
Thanks for the report. Seems almost to be the same as #11302
