### ISSUE TITLE
Custom logo with white text and transparency is not visible on error pages

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#11419]
eg 
![image](https://cloud.githubusercontent.com/assets/273120/23348318/bc64b25c-fd0d-11e6-8a80-b057e3db1a37.png)

Because in Piwik the top header has dark background many people might choose a logo with transparent background and white text. 

A solution could be to repeat the background from the regular layout:

![image](https://cloud.githubusercontent.com/assets/273120/23348358/22bc4f38-fd0e-11e6-84bb-935147afc88e.png)

**Comment by mattab** [comment]
> A solution could be to repeat the background from the regular layout:

:+1:
