### ISSUE TITLE
Unable to choose website time zone in 3.0.1

### ISSUE THREAD

**Issue by granticusmaximus** [piwik/piwik#11416]
In the newest version of Piwik 3.0.1, I am unable to pick the website time zone, there are no option available to do so. And this is creating a road block for me to be able to set this up completely and use that tracking capabilities. Is there any way around this to fix?
Thanks

**Comment by Findus23** [comment]
Is it possible you are referring to #11310?
Could you try another browser?

**Comment by sgiehl** [comment]
@granticusmaximus  if this doesn't duplicate #11310, please reopen!
