### ISSUE TITLE
I really don't get the principles of the "others" 

### ISSUE THREAD

**Issue by ChrisR1993** [piwik/piwik#11420]
Hi, @tsteur 
me again.
I modify my config.ini.php like the picture below.
![php](https://cloud.githubusercontent.com/assets/25838575/23349639/5671c968-fcf8-11e6-8a29-3729796fbe8f.PNG)
the "others" showed up after 100 rows before, so I set it to 500 this time.
Then I restart the mariadb and archived logs to import.

But, the Piwik page doesn't change anything. the "others" still showed up after 100 rows.
could you please tell me the reason of this....again....?

Appreciate your help.
Regards,
Chirs

**Comment by tsteur** [comment]
Did you force to re-archive the reports? eg have a look at https://piwik.org/faq/how-to/faq_155/ or https://piwik.org/faq/how-to/faq_59/ 

In general please ask questions in our forum https://forum.piwik.org as we only keep track of bugs and feature requests here.
