### ISSUE TITLE
Kafka Push plugin

### ISSUE THREAD

**Issue by ksachdeva11** [piwik/piwik#11424]
How can I setup KafkaPush plugin ? Im not able to figure out where to find the attached screenshot window.

![kafkapush-screenshot-001](https://cloud.githubusercontent.com/assets/24254124/23395091/d039eeb4-fdb2-11e6-9f41-4264142c60ca.png)

**Comment by mattab** [comment]
Hi @ksachdeva11 

This plugin is not created by Piwik nor InnoCraft therefore we don't support it. Please contact developer directly
