### ISSUE TITLE
[Request] Need to set different "Others" mode in one Piwik

### ISSUE THREAD

**Issue by Viviansweaty** [piwik/piwik#11437]
Hey there,
I need to set different "Others" display for different web site.
![screenshot](https://cloud.githubusercontent.com/assets/26127899/23493378/b4898970-ff4e-11e6-9bdf-41500dd8f3f7.PNG)
I konw this which you guys want us to know, but I want to set this for different web site analysis.
eg. siteA: 1000
      siteB: 500
is this possible? if it does could you tell how to deal with?
Thank you!

**Comment by Viviansweaty** [comment]
Please! any comment is appreciated !!

**Comment by mattab** [comment]
It's not possible to set different limits for different websites @Viviansweaty
