### ISSUE TITLE
After update to 3.0.2 - Integrety Check - Plugins Menu.php

### ISSUE THREAD

**Issue by DavidLiedke** [piwik/piwik#11439]
After the update to 3.0.2:

![firefox_2017-03-02_09-56-52](https://cloud.githubusercontent.com/assets/25581728/23500033/cbb12024-ff2e-11e6-9077-7cc9ed9a1695.png)

The first list was a lot of longer. I deleted a lot of other files with no problems. But if i delete one of these Menu.php files i get the following message:

![firefox_2017-03-02_09-57-54](https://cloud.githubusercontent.com/assets/25581728/23500050/da53d7c0-ff2e-11e6-9258-bd66be6731ad.png)

**Comment by tsteur** [comment]
It should mention to clear the cache afterwards. Running `./console cache:clear` should help.

**Comment by gaumondp** [comment]
How many support emails Piwik Team wouldn't be writing just by adding an automatic clear-cache and clear-tmp at every Piwik update or after plugin activation...

**Comment by tsteur** [comment]
This is already there. Problem is when files are deleted manually on the server

**Comment by tsteur** [comment]
Actually, when an error contains a message like this we could also call `Filesystem::deleteAllCacheOnUpdate();` similar to what we do when safemode gets activated

**Comment by DavidLiedke** [comment]
Same issue after running `./console cache:clear` .

What can i do ?

**Comment by tsteur** [comment]
Can you clear the tmp folder manually like `rm -rf $piwik/tmp/cache/*` Sounds like either the VisitTime\Menu.php was not deleted or there seems to be some permission problems to delete the cache files.

**Comment by DavidLiedke** [comment]
Now i deleted the cache folder manually. The folder was definitely clear.

The issue is the same. In the past i had no problems after a Piwik Update.

**Comment by DavidLiedke** [comment]
I had a second installation (different server) with exact the same issue.  The rest of the system check is "green".

**Comment by mattab** [comment]
Sorry we cannot reproduce this issue. Maybe you could send us acces to your Piwik server for us to debug further? https://piwik.org/contact/

**Comment by mattab** [comment]
@DavidLiedke 
Thanks for sending info by email

* I deleted all files as per system check recommendations
* THEN I deleted tmp/cache/*

and it works :+1: 

(I reckon you deleted cache before deleting the files which may not work)
