### ISSUE TITLE
Visitor log: Extra line break at the top of each visit

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11442]
There's an extra space/line at the top of each visit in the visitor log, which should be removed:

![extra line break top](https://cloud.githubusercontent.com/assets/466765/23509627/b573008e-ff56-11e6-8a4c-7a4c39d4684c.png)

**Comment by sgiehl** [comment]
Not able to reproduce that locally. Are there any extra plugins enabled on demo? That extra lines seem to be inserted by the Event `Live.visitorLogViewBeforeActionsInfo`

**Comment by tsteur** [comment]
Yes, this is caused by an extra plugin.
