### ISSUE TITLE
Same IP (server host ip) for all visitors when using tracker-proxy

### ISSUE THREAD

**Issue by EdgarPE** [piwik/piwik#11447]
For some websites I am using piwik tracker proxy (https://github.com/piwik/tracker-proxy), but in Visitors in Real Time widget every user has the same IP address, the address of the web server IP. There are no other proxy-s involved.

The tracker proxy does a request to real piwik tracker like this one:
`91.X.Y.Z - - [02/Mar/2017:16:55:57 +0100] "GET /piwik.php?cip=212.A.B.C&token_auth=9c43c...`

91.X.Y.Z is the server IP, 212.A.B.C is clients real IP address.

So the tracker proxy sets the cip query parameter right, the correct IP is there. Still, the real piwik server do not obey to this, but uses the server host IP address.

If you need any more info let me know.

**Comment by EdgarPE** [comment]
Some more info: Piwik version: 3.0.2 (upgraded from 2.x)

There are sites on different web servers with tracker proxy involved. All the stats of these sites shows the actual web server IP of that site as client IP. There is one site, which do not use tracker proxy, it uses the embeddable JS connecting directly to piwik server. The client IP-s are correct on that site.

**Comment by tsteur** [comment]
Can you check that the configured token auth is correct?

**Comment by EdgarPE** [comment]
Oh, the AUTH_TOKEN was not matching. The 2.x -> 3.x upgrade must have changed it. Thanks! And also thank you for this awesome piece of software!

**Comment by tsteur** [comment]
You're welcome. Glad it works 👍
