### ISSUE TITLE
XHR widget requests

### ISSUE THREAD

**Issue by ctomczyk** [piwik/piwik#11440]
Currently all widgets are sending **XMLHttpRequests** independently. I think this sometimes impacting on server performance, especially on shared hosting.

What I'd suggest is to use **Promise** (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) and queue all widget requests. I think there is no need to "_attack_" server with multiple requests at the same time. Just send one and wait until it finishes then send another one.

Possibly, this could be even configured in Piwik options to send widget XHR requests asynchronously or synchronously.

**Comment by mattab** [comment]
Thanks for the suggestion, but we won't queue XmlHttpRequests as it would be too slow from a user perspective.
