### ISSUE TITLE
Overlay showing bubbles in wrong location

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11441]
on the demo the Overlay reports are not working well anymore. The bubbles are displayed in the wrong location. Can be seen in https://demo.piwik.org/index.php?module=Overlay&period=month&date=today&idSite=1#?%3Fl=https$3A$2F$2Fpiwik.org$2F and many others like https://demo.piwik.org/index.php?module=Overlay&period=month&date=today&idSite=35#?%3Fl=https$3A$2F$2Fplugins.piwik.org$2Fpremium

The bubbles are shown too high compared to the block:

![bubbles](https://cloud.githubusercontent.com/assets/466765/23509209/503375ba-ff55-11e6-8234-5e9242ad1e04.png)

(here the 21% bubble is highlighted but the rectangle is shown well below the bubble...)

**Comment by sgiehl** [comment]
Did you test with firefox? or other browsers as well?

**Comment by mattab** [comment]
Fixed in #11485
