### ISSUE TITLE
Chrome browser outlinks request is cancel

### ISSUE THREAD

**Issue by pkptzx** [piwik/piwik#11453]
Chrome browser outlinks request is cancel , can't track outlinks 
IE is ok.

![image](https://cloud.githubusercontent.com/assets/4339676/23546833/566a0c68-003c-11e7-8c72-9a3f4f564c6d.png)

**Comment by mattab** [comment]
Are they all cancelled or just sometimes? are they cancelled after 500 ms? you can increase timeout as documented here: https://developer.piwik.org/guides/tracking-javascript-guide#changing-the-pause-timer
