### ISSUE TITLE
Piwik does not indicate the correct period

### ISSUE THREAD

**Issue by MWisotzki** [piwik/piwik#11457]
I would like to evaluate the topical day, however, the expired day is still indicated.
![piwik-datum](https://cloud.githubusercontent.com/assets/24963870/23586962/aea05642-01a1-11e7-8b65-06423bde4571.jpg)

**Comment by MWisotzki** [comment]
I use Piwik 3.0.2

**Comment by tsteur** [comment]
This is a duplicate of https://github.com/piwik/piwik/issues/9053 

It currently shows also visits from the day before because of https://github.com/piwik/piwik/pull/11425
