### ISSUE TITLE
Users always get Error: Wrong Username and password combination.

### ISSUE THREAD

**Issue by FaliseDotCom** [piwik/piwik#11458]
Whenever a user tries to log in, they always get Error: Wrong Username and password combination. Updating the password works (I get the e-mail and after clicking the link, the password hash is changed in the DB) but I still get the same error.

I've been experimenting a bit and when I return a forced TRUE in Auth::hasSuperUserAccess() and Auth::wasAuthenticationSuccessful() (core/auth.php) I can login but then I get another error:
You can't access this resource as it requires an view access for at least one website.

So maybe user rights are screwed up? As a superuser, I shouldn't be bothered with individuals site view rights.

I've removed all files (except for the config folder) and uploaded the latest version twice, this doesn't fix the issue.

Any tips or things I can try?

**Comment by FaliseDotCom** [comment]
Next step; disabling all plugins. No change. 
Enable ERROR / WARN logging to both file and screen; nothing comes up.

Any help would be greatly appreciated.

**Comment by tsteur** [comment]
Did this start after updating to 3.X? Where there any problems during the update and do you know if all DB updates were executed? If you have access to DB, can you check in "piwik_user" table whether there are 32 or about 60 characters in the password column?

**Comment by L-A** [comment]
Chiming in to say the same thing happened here.

With an up-to-date installation, sessions that expire can't seem to be able to log in again. All steps for a forgotten password work.

**Comment by L-A** [comment]
@tsteur I got to connect and verify: there are 32 characters stored in the password column.

**Comment by tsteur** [comment]
Can you confirm you are on Piwik 3.x?

**Comment by L-A** [comment]
Yes,`3.0.2`

I'm not certain if this is the first 3.x update I applied (provided that `3.0.0` or `3.0.1` were public releases).

**Comment by L-A** [comment]
Confirming that the `password` column was a `char(32)` (if that was your suspicion).

I'm not sure what the new type is exactly, but expanding it to `char(64)` and performing a password reset allows it to be stored properly.

**Comment by tsteur** [comment]
It sounds like some database updates weren't executed. Do you know if you used the "One-click update in the UI" or whether database updates were executed manually?

**Comment by L-A** [comment]
Our installation has a history of receiving wrong permissions on certain files – which made the one-click update fail at times. We always attempt it first, so my working hypothesis is this:

- One-click update was attempted, failed
- The installation was then manually uploaded & unzipped (preserving `config.ini.php`)
- `core:update` was _not_ run afterwards
- The next web visit triggered the "Finish updating Piwik" UI.

Then Piwik was in a functional state but the database was missing parts or the entirety of a necessary migration.

**Comment by FaliseDotCom** [comment]
Same here; one click updates usually causes errors so I do the upload manually (deleting everything but config.ini.php first). After updating this way I click the Finish updating Piwik button and I'm good to go, except this time. My previous update was december 2016 so that was version 3.0.0. Current update was to version 3.0.2.

**Comment by FaliseDotCom** [comment]
Counting password characters; 32 for all users

**Comment by tsteur** [comment]
I recommend to change the database column as well to allow more characters and then it should work to reset password like: 

`ALTER TABLE piwik_user CHANGE `password` `password` VARCHAR(255)` (untested)

**Comment by FaliseDotCom** [comment]
Updated the table and I can now login. Unfortunately I could login only once, subsequent times the page just keeps on loading and gives a 500 error after a while. Even on the first successful login, I could not see any site details, the also just kept on loading. An easy for another thread maybe?

**Comment by mattab** [comment]
@FaliseDotCom when you get error 500 please check this: https://piwik.org/faq/troubleshooting/faq_19489/ and let us know the message

**Comment by FaliseDotCom** [comment]
I get this: 

[Thu Mar 16 11:29:41.034269 2017] [fastcgi:error] [pid 5666] [client ***] FastCGI: comm with server "/var/www/clients/client6/web83/cgi-bin/php5-fcgi-*-80-networkcultures.org" aborted: idle timeout (300 sec), referer: ***/web-analytics/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last7
[Thu Mar 16 11:29:41.034338 2017] [fastcgi:error] [pid 5666] [client ***] FastCGI: incomplete headers (0 bytes) received from server "/var/www/clients/client6/web83/cgi-bin/php5-fcgi-*-80-networkcultures.org", referer: ***/web-analytics/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last7

So timeouts and zero bytes. Maybe it takes too long to access the DB? Some other update script that has not run?

**Comment by FaliseDotCom** [comment]
Update; I did a system check and saw a few files having wrong file lengths. I updated these manually, and after a while the dashboard started to show all website results again. A long while, but still some progress.

System check suggest enabling LOAD DATA INFILE, so I'll try that next. 

Thanks for your help so far.

**Comment by FaliseDotCom** [comment]
According to the the server guy,  LOAD DATA INFILE is not a good idea because we don't get enough visitors :'(

Enabling DEBUG level I now get the following error;

**Comment by FaliseDotCom** [comment]
WARNING: /var/www/clients/client6/web83/web/web-analytics/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(37): Warning - realpath(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/clients/client6/web83/web:/var/www/clients/client6/web83/private:/var/www/clients/client6/web83/tmp:/var/www/networkcultures.org/web:/srv/www/networkcultures.org/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin) - Piwik 3.0.2

So why is Twig trying to get to the root of the server, it shouldn't look there I think. Is there some config I can change for this?

I wrapped the code in a try catch and now I get this error a few times instead of just once. A bit further but still the data loading times out.

Any ideas?

**Comment by FaliseDotCom** [comment]
Hi guys,

Haven't heard back in a while. Any clue why Twig would be looking in the root of the server? This is the only lead I have why Piwik might be slow. What does Twig do? Maybe it's a config thing?
