### ISSUE TITLE
Scheduled PDF Reports: Wrong time saved

### ISSUE THREAD

**Issue by mdawart** [piwik/piwik#11459]
When saving the settings for email report the time is saved + 2 hours, e.g. wanted to have the report  7, 

![bildschirmfoto 2017-03-06 um 16 05 07](https://cloud.githubusercontent.com/assets/420582/23615465/cd06e7aa-0286-11e7-930a-e67a7f3d43b4.png)
it is set to 9 when I reopen it
![bildschirmfoto 2017-03-06 um 16 05 23](https://cloud.githubusercontent.com/assets/420582/23615464/cd06a51a-0286-11e7-84c8-563da44c3f28.png)

is there maybe a problem with the time conversation or may I have set up sth wrong with the time zone? This worked correctly in the very past when I installed it, just found this issue as I wanted to update a setting for one report

**Comment by sgiehl** [comment]
Can confirm this issue. Will investigate it...
