### ISSUE TITLE
Clarify that emails about new versions are sent to Super Users

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11450]
Recently we got a few emails like this:

> for some reason I'm regularly getting mails whenever a new Piwik version is being released. Since there's no unsubscribe option in these mails I'd highly appreaciate if you'd remove me from the mailing list.

To make it more clear I would suggest that in our emails about new versions, we add a note such as "You receive this email because you are a Super User on the Piwik at piwik.example.org" - any better suggestion welcome!

**Comment by tsteur** [comment]
👍

**Comment by fbrzozowski** [comment]
[https://github.com/piwik/piwik/pull/11542](url)
