### ISSUE TITLE
File integrity checker creates too long command lines.

### ISSUE THREAD

**Issue by mathomp4** [piwik/piwik#11468]
From the addition of the file integrity checker in #11096:

My only other suggestion for this would be, perhaps, breaking up the "run this command" command. A few times I've had a lot of files reported as unexpected. When I copy and paste the command, it's longer than some buffer on my box. It seems to be at 8189 characters, which must be a buffer in X? Gnome? Not sure who handles the middle button copy.

Would it be possible to limit the size of commands provided and give two or three commands to copy-and-paste?

**Comment by mattab** [comment]
Thanks for the suggestion. Yes we should split the verrry long commands into smaller ones.
