### ISSUE TITLE
Curl_exec: SSL: invalid CA certificate #1 (offset 0) in bundle 

### ISSUE THREAD

**Issue by gfive** [piwik/piwik#11460]
It's basically a mac os x or unix problem.

`$ php -i | grep "SSL Version"`

I suspect you'll see this:
`SSL Version => SecureTransport`

And that's the problem. OS X is using SecureTransport and NOT OpenSSL.
Simple solution: http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error2

So or follow these steps (not complicated If you do a bit more with your osx) or Piwik has to add SecureTransport.

**Comment by mattab** [comment]
Thanks for the report. duplicates #11451
