### ISSUE TITLE
[ERROR] 2.15.0 version bug?

### ISSUE THREAD

**Issue by ChrisR1993** [piwik/piwik#11462]
![error](https://cloud.githubusercontent.com/assets/25838575/23648620/cd51a366-035e-11e7-8d38-6395b53bcaf4.PNG)

Hey,
I got the error message like the picture.
1).My Piwik version is 2.15.0.
2).Why did this happened?
3).How should I do ?

Thank you!

**Comment by mattab** [comment]
Please always upgrade to latest Piwik as we fix dozens of bugs in each version. Please upgrade to piwik 3.0.2 and if you still have this issue, let us know :+1:

**Comment by ChrisR1993** [comment]
@mattab thank you mattab,
I know I know I need to upgrade which I always do, but still want to know the reason, and the solution of this bug.
appreciate it.

**Comment by mattab** [comment]
First upgrade and then if you still have the bug, we will help
