### ISSUE TITLE
"Export as Image" for widget images

### ISSUE THREAD

**Issue by cardinalacres** [piwik/piwik#11464]
For widgets that display data as an image, when I use the "Export as Image" function the image produced is incorrectly scaled (only the upper left-hand corner of the image is visible). This appears to be a bug that was introduced with Piwik 3.0.0 (used to work in my install previously).

Attached is a screenshot showing the issue:

![piwik_image_bug](https://cloud.githubusercontent.com/assets/19563265/23686026/373c57b0-0375-11e7-8103-e70033d39d49.png)

**Comment by mattab** [comment]
Thanks for the report.

Which browser and Operating system do you use?

**Comment by cardinalacres** [comment]
I see the same behavior on both Safari (v10.0.2) and Firefox (v52.0.1). This is on Mac OS X (or, I guess, MacOS these days) 10.12.2.

**Comment by Findus23** [comment]
This issue reminds me of https://github.com/piwik/piwik/issues/9292#issuecomment-159989768 and https://github.com/piwik/piwik/issues/4594

**Comment by mattab** [comment]
Maybe this is easily fixable @sgiehl ?

**Comment by sgiehl** [comment]
Can confirm that happens on displays > 2k only. Need to investigate

**Comment by sgiehl** [comment]
I've created a pull request. Can anyone having a screen with a pixel ratio > 1 (like a retina display) approve this changes fix the problem?

**Comment by tsteur** [comment]
looks good to me

![image](https://cloud.githubusercontent.com/assets/273120/24470518/a446cfe0-151b-11e7-8732-9b2cc37979e6.png)

**Comment by tsteur** [comment]
and just to confirm this is with 3.x-dev branch

![image](https://cloud.githubusercontent.com/assets/273120/24470602/0152e67e-151c-11e7-848d-9f5d8492eb24.png)
