### ISSUE TITLE
File integrity check failed and reported some errors.

### ISSUE THREAD

**Issue by aasano** [piwik/piwik#11461]
I downloaded latest Piwik 3.0.2. and installed it with Yummy FTP Pro via FTPS protocol and binary (Raw data) transfer to my web hosting server. I re-installed it several times, but every time came with same result as below. Everything else was checked green in Piwik Installation System Check, except this. What can I do to fix this?

![piwik](https://cloud.githubusercontent.com/assets/26228746/23620172/a977be00-029e-11e7-9ba5-ca9c0db61ae4.jpg)

**Comment by DavidLiedke** [comment]
You have to upload the files in the "Binary mode".

For example with WinSCP:
Select the files --> right click --> Upload --> Transfer settings --> Transfer Mode "Binary" --> Ok --> Ok --> Done.

**Comment by aasano** [comment]
But I have used Binary (Raw data) transfer!

**Comment by aasano** [comment]
How can I go more binary with transfer?
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/26228746/23661138/6c58ef92-0354-11e7-9916-a9d2549cd80c.png)

**Comment by aasano** [comment]
Well. I enabled "Include invisible items in transfers" in my FTP software and the installation went through. Is this strange.

**Comment by Findus23** [comment]
> Well. I enabled "Include invisible items in transfers" in my FTP software and the installation went through. Is this strange.

It isn't really. All files starting with a dot are considered hidden in Linux file systems. Appearently your ftp Client doesn't upload them by default and as a result Piwik is complaining that they are missing (as in your first screenshot).

Maybe the error message should make it more clear that the files don't have to be corrupted, but also can be completely missing.

**Comment by aasano** [comment]
That makes sense very well. Thank you Findus23. Yes, the default setting on my FTP client disabled invisible items. It would help if the error message could suggest that possibility also.
