### ISSUE TITLE
Cannot search https://developer.piwik.org

### ISSUE THREAD

**Issue by tkapler** [piwik/piwik#11466]
This is not a bug of piwik itselft, but more of the usability for piwik developer - it is not possible to do fulltext search on https://developer.piwik.org - there is a search filed in the top right corner, but actually it only allow us to select something from the suggest box (and in 99 % of my needs the word i was searching was not a tag in suggest box, althought it exist on web, so it did nothing).

**Comment by mattab** [comment]
Thanks for the suggestion @tkapler - fully agree! See this duplicate report in the dev docs tracker: https://github.com/piwik/developer-documentation/issues/23

A pull request would be super welcome :+1:
