### ISSUE TITLE
Excluded IPs still show up in Piwik when using IP anonymization

### ISSUE THREAD

**Issue by brortao** [piwik/piwik#11467]
I have a few spam IPs that regular show up in my Piwik analytics. I have added them to the "Global list of excluded IPs" in "Global website settings" - one address per line with no wildcards. However, their visits still keep showing up. I've enabled debug logs now, and I'll update this issue if they shed light on the issue.

I'm using Piwik 3.0.2. Has anyone else had a similar problem?

**Comment by tsteur** [comment]
FYI: I just browsed through the code, and debugged it while trying to reproduce it but it works.

Are you using the regular JavaScript tracker?

**Comment by brortao** [comment]
I found the problem - it was my mistake.
I've set Piwik to anonymize the last part of visitor's IP addresses, so they all end in `.0`. Of course, this isn't the actual visitor's IP, so I'll have to use the wildcard in the list of excluded IPs.

Sorry for the false alarm - closing this issue.

**Comment by tsteur** [comment]
Actually, I'm thinking this might be a bug as the exclusion should maybe still work on the original IP. I will reopen for now but feel free to close if I'm wrong @mattab

**Comment by sgiehl** [comment]
Looking at the code, the IP exclusion should be handled before the IP get anonymized. So excluding the original IP should work.

**Comment by BalooBearUSA** [comment]
I have also have my setting set to anonymize YES, but my Global List of Excluded IPs still appear in my visitor logs.
