### ISSUE TITLE
ajax loading reinit download tracking

### ISSUE THREAD

**Issue by DomsaNN** [piwik/piwik#11479]
Hi I am running a ajax based website and we need to reinit the event on download links. It works like a charm on the initial page load, but after reloadind ajax content I need somehow to reinitiate that scanning for downloadlinks and initiate event thing from piwik.

I couldnt find anything about that topic. Any solutions for that?

**Comment by tsteur** [comment]
Check out https://piwik.org/blog/2017/02/how-to-track-single-page-websites-using-piwik-analytics/ 

Since Piwik 3.0.2 you can call `_paq.push(['enableLinkTracking']);` to do this when content changes

**Comment by DomsaNN** [comment]
tot bad I cant go above 2.17 due to php version... thanks anyway
