### ISSUE TITLE
Unable to send mail.

### ISSUE THREAD

**Issue by vopjie** [piwik/piwik#11470]
An error occurred while sending 'HTML Email Report - 1.2017-03-08.1.zh-cn.html' to jiezhiyong.mail@qq.com. Error was 'Unable to send mail. '

**Comment by cybernet** [comment]
piwik version ?

**Comment by vopjie** [comment]
@cybernet

Piwik version: 3.0.2
MySQL version: 5.1.48
PHP version: 5.5.30

error：
An error occurred while sending 'HTML Email Report - 1.2017-03-19.1.zh-cn.html' to jiezhiyong.mail@qq.com. Error was 'No connection has been established to smtp.gmail.com'

**Comment by mattab** [comment]
Looks like your server cannot talk to smtp.gmail.com - maybe you're behind great firewall or so?
