### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by MESWEB** [piwik/piwik#11477]
Mixed Content: The page at 'https://domain.com/index.php?' was loaded over HTTPS, but requested an insecure image 'http://piwik.domain.com/'. This content should also be served over HTTPS.

**Comment by sgiehl** [comment]
please update your javascript tracking code. The code generator should already give you a code where javascript will be included without protocol. It should look like this:

```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//piwik.domain.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    
  })();
</script>
<script type='text/javascript' src="//piwik.domain.com/piwik.js"></script>
<!-- End Piwik Code -->
```

**Comment by MESWEB** [comment]
Yes I do that but nothing work.
