### ISSUE TITLE
Error with mover and shaker widget after updating to Marketing Campaigns Reporting

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11493]
Error with mover and shaker widget after
- deleting old advanced campaign reporting and
- installing new (renamed) Marketing Campaigns Reporting
https://plugins.piwik.org/MarketingCampaignsReporting/changelog

 ![grafik](https://cloud.githubusercontent.com/assets/5681880/23997211/b45459c8-0a50-11e7-8dd8-8a24c52bee1d.png)

**Comment by sgiehl** [comment]
Thanks. Guess I know the reason. Will try to fix that soon

**Comment by sgiehl** [comment]
Fixed that in the plugin. Will release a new version soon.
