### ISSUE TITLE
WARNING: Error while getting SEO stats (domain age): curl_exec: Connection timed out after 10001 milliseconds.

### ISSUE THREAD

**Issue by howdytom** [piwik/piwik#11495]
Since I have upgraded to Piwik 3 the following warning shows up most of the time:

> WARNING: Error while getting SEO stats (domain age): curl_exec: Connection timed out after 10001 milliseconds. Hostname requested was: www.whois.com

How can I debug this? No server errors with php 7.0.16, Piwik 3.0.2

**Comment by sgiehl** [comment]
Do you have ssh access on the server Piwik is running on? Maybe try to run an curl on the shell to check whether a connection to whois.com can be established or not.

**Comment by howdytom** [comment]
yeah. Good point. Indeed it says 

`curl: (7) Failed to connect to www.whois.com port 80: Connection timed out`

I am able to establish a connection to various other domains, except whois.com, though. Any ideas?

**Comment by sgiehl** [comment]
Is it listed in your hosts file? Don't have any other idea why it shouldn't be reachable otherwise right now...

**Comment by howdytom** [comment]
thank you for your quick reply. Which hosts file are you referring to? It's not listed in /etc/hosts file

**Comment by mattab** [comment]
It looks like some network/connection errors to whois.com which works for us

**Comment by benhartwich** [comment]
Hi,

I´ve the same problem - is there any solution?

**Comment by howdytom** [comment]
Check your firewall port settings for outgoing httpd connections.

**Comment by benhartwich** [comment]
No, other websites works.

**Comment by howdytom** [comment]
mephivio shared a solution in the [Piwik Forum](https://forum.piwik.org/t/piwik-3-0-1-warning-error-while-getting-seo-stats-domain-age/23136/2)

To solve it :
`
1/ edit the file /plugins/SEO/Metric/DomainAge.php
2/ modify lines 77, 97, 117
3) replace http with https

like this
$data = $this->getUrl('https://wayback.archive.org/web/*/' . urlencode($domain));
$data = $this->getUrl('https://www.who.is/whois/' . urlencode($domain));
$data = $this->getUrl('https://www.whois.com/whois/' . urlencode($domain));`

**Comment by benhartwich** [comment]
Solved!

**Comment by sgiehl** [comment]
Ah that's interesting. So it works with https for you but not with http?
Guess we could implement a fallback, so it tries https if http doesn't work

**Comment by RMastop** [comment]
I'd say try HTTPS, if it fails, use http as the fallback.

**Comment by mattab** [comment]
this was fixed earlier in https://github.com/piwik/piwik/pull/11672
