### ISSUE TITLE
Custom dimension with regex not working ?

### ISSUE THREAD

**Issue by davidvenin** [piwik/piwik#11492]
Hi, 

I'm using the latest version of piwik and experiencing some issues with custom dimension.
I added a custom dimension  (actions dimension) with this regex : 

`\/ios\/(\d*)\/` 

tested with regex101 in case of ... only to trigger an id. 
I tracked the dimension Page URL but in actions/myCustomDimension, `Value is not defined`... Don't understand why, maybe I'm doing it the wrong way. Do you have any idea ?

**Comment by davidvenin** [comment]
Ok fixed, no need to escape `/` that's why.

**Comment by tsteur** [comment]
👍
