### ISSUE TITLE
MediaAnalytics plugin causes much higher memory use

### ISSUE THREAD

**Issue by toebu** [piwik/piwik#11490]
I'm not sure if this really warrants an issue, but I wanted to let you know of our experience with the MediaAnalytics plugin: after installing it in Piwik 2.17.1, reports would not load any more when selecting date ranges longer than a couple of months (custom date range). The site we tested this with has about 1 mio page views a month, but no media analytics events tracked yet.

PHP memory_limit was set to 128MB and was exhausted. When disabling the plugin, everything worked fine again. Increasing the limit to 512MB also solved the issue. So this isn't really a problem, but I was just astonished that just enabling a plugin that doesn't really have any data to be processed would increase the memory usage by that much.

**Comment by tsteur** [comment]
Hi @toebu 

128MB for Piwik is pretty low and you were likely already quite close to the memory limit. I'm actually impressed it worked in the past with 128MB, we usually recommend a minimum of about 768MB for selecting date ranges (and archiving), unrelated to the traffic. Selecting date ranges often uses similar amount of MB and doesn't so much depend on the traffic or the number of enabled plugins but rather the number of different page URLs and titles, number of different referrers etc.

The plugin itself doesn't really do anything when selecting date ranges as everything is done by Piwik core and if no data had been tracked yet, it might be even unrelated to Media Analytics. It likely was using quite close to 128MB before and it could be eg related to what date ranges you combine, how many different referrers there were etc. Increasing the limit to 512MB sounds good for this 👍
