### ISSUE TITLE
Piwik Marketplace (upload Plugin) not possible without internet

### ISSUE THREAD

**Issue by FireFart** [piwik/piwik#11494]
Currently the Marketplace GUI to upload new plugins can only be accessed, if the server has correct internet access. If the installation is based behind a corporate proxy the marketplace request fails with an curl_exec error like
```
curl_exec: Could not resolve host: plugins.piwik.org. Hostname requested was: plugins.piwik.org
```
So it is not possible to access the upload plugin form without internet. I think the missing internet exceptions should be handled gracefully so the superadmin is still able to upload plugins via the web gui (without having shell access)

**Comment by tsteur** [comment]
I see, the problem is that the upload plugin feature is on the Marketplace page but it may not be possible to view that page when there is no internet connection? Is that right? 

We would need to move the upload to the plugins page or so

**Comment by FireFart** [comment]
@tsteur exactly that's the problem :)

**Comment by mattab** [comment]
> We would need to move the upload to the plugins page or so

would suggest to put the "upload plugin" feature on both pages "Plugins" and "Marketplace" if possible. 

Proposed:

* on Plugins page: change `Extend Piwik by <a>installing a new plugin</a>. ` to `Extend Piwik by <a>installing Plugins from the Marketplace</a> or <a>upload a Plugin in .zip format</a>. `
* Leave Marketplace as it is
