### ISSUE TITLE
Duplicate entry in Visitors Entry Real-Time

### ISSUE THREAD

**Issue by MESWEB** [piwik/piwik#11496]
Duplicate entry in Visitors Entry Real-life. I have https website wit redirecting by .htaccess

**Comment by sgiehl** [comment]
Could you please explain that a bit more?
Are all visitors tracked twice, or what exactly is your problem?

**Comment by MESWEB** [comment]
One IP have two Entry in Log Visitors Entry. Example if I enter page from link then I see in log like this:
Date - 1.1.2011 12:23:11
IP XXX.XXX.XXX.XXX Visitor back
From - domain.com

Date - 1.1.2011 12:23:11
IP This same number as previous 
Direct entry

**Comment by Findus23** [comment]
I haven't tested it again but I have mentioned in https://github.com/piwik/piwik/issues/11478#issuecomment-285975812 that you are using the JavaScript and the non-JavaScript tracker at the same time. 

You should wrap the 
```html
<img src="//piwik.auctio.uk/piwik.php?idsite=1&rec=1" style="border:0" alt="" />
```
in a `<noscript>`, so that it is only used of JavaScript is disabled.

**Comment by MESWEB** [comment]
Yeah seems work. I will test more this solution then I close this issue.
Thank You @Findus23
