### ISSUE TITLE
Pressing ALT+d keyboard combination should not open calendar

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11498]
Recently we added some keyboard shortcuts https://github.com/piwik/piwik/issues/5230#issuecomment-274304407

- `z` for Zen mode 
- `s` to open Segment selector
- `w` to open Website selector
- `d` to open calendar (`d` stands for Date)
- `f` to open the search (`f` stands for Find)

Those shortcuts are  sometimes triggered when a combination of keys is pressed including one of them. For example ALT+D triggers the Calendar shortcut. 

The goal of this ticket is to make sure that those shortcuts are not triggered when ALT+key is pressed. Because for example ALT+D is supposed to go in the address bar in most browsers, and Piwik would break usability of the browser.

**Comment by sgiehl** [comment]
This seems to be a firefox only problem and was [reported in the Mousetraps issue tracker](https://github.com/ccampbell/mousetrap/issues/211) years ago.
We might need to patch this library if we would like to fix the behavior I guess

**Comment by CheweyZ** [comment]
As an idea how about we change the key bind to C as this way it would also imply C for calendar

**Comment by sgiehl** [comment]
that won't solve the problem. It's not only ALT+D. there are other letters in firefox as well, that wouldn't work anymore. ALT+S for example would normally be "Save"

**Comment by sgiehl** [comment]
I'll try to find a workaround to prevent our event from being fired if the ALT key is pressed
