### ISSUE TITLE
curl_exec: Could not resolve host: plugins.piwik.org on IPv6

### ISSUE THREAD

**Issue by ser** [piwik/piwik#11508]
Piwik 3.0.2

On a host with IPv6 bound to the interface, but without IPv6 routing to Internet, marketplace does not show up with an error:

```curl_exec: Could not resolve host: plugins.piwik.org```

A workaround is to patch ```core/Http.php``` adding:

```curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );```

**Comment by mattab** [comment]
Thanks for the report. The suggestion sounds reasonnable. Maybe @sgiehl can confirm

**Comment by j100002ben** [comment]
This issue occur on me too, and I add `curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );` to `core/Http.php` at line 525 and solve the problem.
It's seems like I have IPv6 setting in interface but the host have no IPv6 routing.

**Comment by mattab** [comment]
@ser  @j100002ben could you 
* Remove the line you added to http.php
* try again if this works now?

we've enabled ipv6 on the Marketplace and probably this should fix this issue. Please let us know

**Comment by mattab** [comment]
Please re-open if you still experience this issue.
