### ISSUE TITLE
Piwik Custom Dimensions does not work in combination Javascript-PHP on Moodle 3

### ISSUE THREAD

**Issue by sthopd** [piwik/piwik#11518]
Custom Dimensions does not work in combination Javascript-PHP on Moodle v.3, because Piwik's tutorial and FAQ's are very confusing and do not show the same code. 
Which code line is correct? :
a) `_paq.push(['setCustomDimension', 'customDimensionId = 1', 'customDimensionValue = ".$userData."']);`
  
b) `_paq.push(['setCustomDimension', 'customDimensionId:1', 'customDimensionValue:".$userData."']);`
  
c) `_paq.push(['setCustomDimension', 1, '".$userData."']);`

NB: ".$userData." is filled in correctly by Moodle v3 plugin. But the Custom Dimension is not accepted by Piwik, so which one is correct: a, b, or c or ...?

What should be the **exact line of code** to paste into an analytics / statistics block of a web page for processing by Piwik?

Thanking you in advance for your answer,
sthopd@hotmail.com

Piwik 3.0.1
URLs: 
Moodle: http://www.cper.org?br=gh
Piwik: http://www.sthop.org?br=gh

**Comment by tsteur** [comment]
c) is correct. 

> because Piwik's tutorial and FAQ's are very confusing and do not show the same code.

can you send us links where we show different code?

**Comment by mattab** [comment]
Please re-open if you still experience the issue, and see our comment above.
