### ISSUE TITLE
Feature Request: How can I manually add my information to any Visitor-profile within Piwik?

### ISSUE THREAD

**Issue by sthopd** [piwik/piwik#11519]
Hello,
How can I (as admin) manually write a note (or PostIt or sticky comment) within Piwik Visitor-Profile about anything I want to be remembered about this external/anonymous visitor, in order to get this information stored together with this Visitor in the Piwik statistics-database concerned? 
Later on, I want to retrieve/read my notes about this particular UserID in the Piwik database about my website.
Is it possible that a Piwik programmer can develop such a nice feature?
Friendly regards,
sthopd@hotmail.com

**Comment by mattab** [comment]
Not possible yet but will soon be possible. Check #6111
