### ISSUE TITLE
Premium Plugin Installer shows false error message after install

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#11512]
I wanted to install a Premium Plugin (Search Engine Keywords Performance)

After adding the key to piwik, I got the suggestion to `INSTALL PURCHASED PLUGINS`, which opened a modal:
![screenshot_20170322_133315](https://cloud.githubusercontent.com/assets/6266037/24197978/2d3f8c7e-0f04-11e7-97ee-4a4ecae9dbdb.png)

After clicking install I get the following errors (in production and local testing):
![screenshot_20170322_080606](https://cloud.githubusercontent.com/assets/6266037/24198009/50dda936-0f04-11e7-9195-cb864b5e4d91.png)

```
Plugin 'FormAnalytics' cannot be found in the filesystem in plugins/ directory.
Plugin 'RollUpReporting' cannot be found in the filesystem in plugins/ directory.
Plugin 'UsersFlow' cannot be found in the filesystem in plugins/ directory.
Plugin 'WhiteLabel' cannot be found in the filesystem in plugins/ directory.
Plugin 'Funnels' cannot be found in the filesystem in plugins/ directory.
Plugin 'AbTesting' cannot be found in the filesystem in plugins/ directory.
Plugin 'MediaAnalytics' cannot be found in the filesystem in plugins/ directory.
Plugin 'ActivityLog' cannot be found in the filesystem in plugins/ directory.
Some paid plugins were not installed successfully.
```
Everything works afterwards, but it seems a check in the installer is assuming one wants to install all premium plugins.

**Comment by tsteur** [comment]
Cheers, I heard of an error like this before and couldn't reproduce initially but seeing it again in the code it's quite obvious. Will issue a PR
