### ISSUE TITLE
API: UsersManager.getUser -> Result without token_auth

### ISSUE THREAD

**Issue by sweting** [piwik/piwik#11513]
In one of the last updates you have deleted the token_auth - result of the GetUserInfo. I use this Information from the API in my software. Can you please revert these change.

## Deleted since 3.0.0
Since version 3.0.0 is token auth not visible anymore in the superusermode. Not in the piwik interface and not in the API. 
That's not good beacuse I wrote software that uses these Informations. 

If there are any security reasons to delete the token_auth in the API then make a psoibility to configure these option.

**Comment by tsteur** [comment]
Unfortunately, we cannot revert this change for security reasons. You could develop a plugin though that does return it again.
