### ISSUE TITLE
After upgrading to 3.0.2, users with view/admin permissions cannot view widgets posted externally

### ISSUE THREAD

**Issue by bondjimbond** [piwik/piwik#11527]
After upgrade, users with View or Admin permissions on some sites (in my case, site ID 16) cannot view report widgets that have been posted on sites outside Piwik.

For example, I have given a user Admin permission for site ID 16, and anonymous users View permission. When they go to view reports (e.g. http://kora.kpu.ca/admin/reports/islandora_piwik_reports) they are redirected to a Piwik login screen - even when the Admin user is already logged in.

However, on another site (site ID 3) with same permission setting, both anonymous and admin users are fine - e.g. http://arcabc.ca/about/usage

Since discovering this problem, I've altered the permissions of both the admin user and anonymous user, in case permissions had been lost, but they are still unable to view widgets.

The admin user reports that she can view the dashboard, etc. just fine if she goes straight to my Piwik site.

**Comment by Findus23** [comment]
On http://kora.kpu.ca/admin/reports/islandora_piwik_reports you are using 
```html
<h3>Islandora object pages</h3>
<div id="widgetIframe"><iframe width="100%" height="350" src="http://analytics.bceln.ca/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=16&period=day&date=today&disableLink=1&widget=1&token_auth=9d571fe32e33608bbefe169b0d7b" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
```
while on http://arcabc.ca/about/usage you are using
```html
<h4>Pageviews</h4>
<div id="widgetIframe"><iframe width="100%" height="350" src="http://analytics.bceln.ca/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=3&period=day&date=yesterday&disableLink=1&widget=1" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
```

The difference (except for idSite and date) is that on the site that isn't working you are adding a token_auth. If I remove the token, it is working:
```
http://analytics.bceln.ca/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=16&period=day&date=today&disableLink=1&widget=1
```

**Comment by bondjimbond** [comment]
Hmm, thanks. I will test this answer. Will also flag for the creator of islandora_piwik to let him know this is a concern.

**Comment by bondjimbond** [comment]
Sigh - apologies; it looks like the user made a mistake copying her API key. Never mind.
