### ISSUE TITLE
Feature Request: Please display Device Type/Model in Visitor Profile pop-up

### ISSUE THREAD

**Issue by sthopd** [piwik/piwik#11520]
Hello,
Is it possible to add some statistics data about the apparatus that the visitor uses to approach a website that has Piwik code built-in?
Please display Device Type/Model in Visitor Profile pop-up.
Thanks,
Sthopd@hotmail.com

**Comment by mattab** [comment]
Thanks for the suggestion! A pull request will be welcome for this feature :+1:

**Comment by sgiehl** [comment]
I'm already about to fix that with the changes to visitor log and profile.
