### ISSUE TITLE
Piwik not tracking events for all android visitors

### ISSUE THREAD

**Issue by i1jordan** [piwik/piwik#11522]
I have this issue while sending events , Piwik dashboard show some visits and don't reflect some. I'm facing this issue over my android app whereas my ios app reflects all visits. 
And yes I'm sending separate userId for different users. Please help me.

**Comment by sgiehl** [comment]
How are you doing the tracking? Are you using the andoid sdk?

**Comment by mattab** [comment]
If you still experience the issue, please re-open the issue and see our comment above.
