### ISSUE TITLE
After upgrade to 3.0.2 deleting a user throws  Integrity constraint violation: 1451 

### ISSUE THREAD

**Issue by bmartinGithub** [piwik/piwik#11523]
After we upgraded to 3.0.2 I tried to delete a user account but I'm getting the following error:

> SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`db_piwik`.`piwik_user_dashboard`, CONSTRAINT `FK_login_IN_piwik_user_dashboard` FOREIGN KEY (`login`) REFERENCES `piwik_user` (`login`))

I tried a second account thinking maybe it was just that one that somehow became corrupt but I get this error when I try to delete any account.

**Comment by mattab** [comment]
We don't use foreign keys in Piwik so it should be something added by someone on your end?
