### ISSUE TITLE
Website selector: always set the focus in the search field when the selector is clicked

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11525]
In various places we show our website selector. For example in Administration > Users (where users can choose which websites a user has access to), or when creating [Roll-Ups websites](http://plugins.piwik.org/RollUpReporting). 

When the website selector is clicked, we should set the focus on the search field at the top which lets people directly type a search string, to find a matching website. This will make the user flow  faster and more usable.

**Comment by sgiehl** [comment]
Haven't had a closer look, but that might already be handled by https://github.com/piwik/piwik/blob/3.x-dev/plugins/CoreHome/angularjs/siteselector/siteselector.directive.html#L32
Not sure why it doesn't work. Will have a look later

**Comment by sgiehl** [comment]
I'm not able to reproduce. Works for me on Chrome and Firefox.
@mattab In which browser did you spot that issue?

**Comment by mattab** [comment]
strange, also can't reproduce! closing
