### ISSUE TITLE
no more movers and shakers with 3.03b1

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11538]
after update to 3.03b1:
no more movers and shakers shown in dashboard widget if date is today

- directly before the update there were some shown
- for days not today there are some shown

"No rows match the criteria "
![2017-03-27_17h43_15](https://cloud.githubusercontent.com/assets/5681880/24365041/e89ca9ca-1314-11e7-9534-1b7bc23c4453.png)

**Comment by hpvd** [comment]
hmm after some time now there is something shown again but only one item.

**Comment by hpvd** [comment]
now its again "No rows match the criteria"

**Comment by tsteur** [comment]
Are you viewing today? Maybe the value is just slightly over the threshold and sometimes not? Like something will be only shown if there is significant more traffic. Eg like 50% more than usual. Maybe it's just like 49.9% and sometimes 50.1% which causes it to appear and disappear?

**Comment by hpvd** [comment]
Same today (28.03.17) Maybe it's only a strange contingency... but before update i never saw "No rows match the criteria" in movers and shakers. Now I see it >90% of the time...
Were there any changes ore corrections in algorithm?

**Comment by mattab** [comment]
>  Were there any changes ore corrections in algorithm?

No there shouldn't be any change in the algorithm. Are you still experience the issue regularly?

**Comment by hpvd** [comment]
hmm just today it's there again:
![2017-05-08_22h17_28](https://cloud.githubusercontent.com/assets/5681880/25823357/2cea5daa-343c-11e7-85f1-6ed704b15ed9.png)

btw: heartbeat timer is in use...

**Comment by hpvd** [comment]
seems to be fine now. closing.
