### ISSUE TITLE
opt-out opens popup and closes it

### ISSUE THREAD

**Issue by StiftungAusNachlass** [piwik/piwik#11531]
Hi, 
the newest Piwik-Release shows some strange behaviour.
If a user clicks the checkbox in the Opt-Out-Iframe, a new Popup appears and within a millisecond it disappears again. After that the content of the iframe changes as expected, but that takes 1 or 2 seconds.
Our Piwik-Users reported that as a bug, because in some Browser (and maybe Plugin)-Constellation (EDGE-Browser), the Popup doesnt close automatically and the checkbox has no effect and doesnt save the status.
In our opinion, the Popup itself is a bug, because the flickering of the Popup (and the new opened and closed Browsertab) irritates the users. The Problem appears at least in Chrome, Safari & Edge.
Any ideas?
Thanks, Tobias

**Comment by mattab** [comment]
Hi Tobias,

Yes, the popup is expected and needed for the opt out to work.

in Chrome it seems to work fine in: https://piwik.org/privacy-policy/

Can you confirm having a problem in Chrome as well as Edge? (except the popup)

**Comment by StiftungAusNachlass** [comment]
Hi Matthieu,
we asked our clients again. Seems like the problem is not appearing any more.
Thanks for making clear, that the popup itself is not a bug.
Best, Tobias
