### ISSUE TITLE
[Bug] Downlaod display abnormality of year period

### ISSUE THREAD

**Issue by Viviansweaty** [piwik/piwik#11543]
Hi, @mattab  hope you doing well.

I have an issue of my Japanese version Piwik, you can refer the screenshot below.
when I check the number of download which by "Year" period of 2017,  the number was 0.
I think this is abnormal, so could please kindly tell me why this happened and how to deal with?

![issue](https://cloud.githubusercontent.com/assets/26127899/24385085/f482f008-13a2-11e7-9f94-1c7fb74051b1.png)

But the data of monthly displayed normally like the screenshot below.
![issue](https://cloud.githubusercontent.com/assets/26127899/24442645/f7b93758-1499-11e7-93d3-1142841d96a5.PNG)

I appreciate your kindly help as always.
Regards,

**Comment by mattab** [comment]
This issue should be fixed in the latest Piwik version, please upgrade

**Comment by Viviansweaty** [comment]
@mattab 
Thanks mattab, I will upgrade the Piwik version.
But I also will be very appreciate if you can tell me why this error happened, wrong procedure? old version bug? or something else?

Regards,
