### ISSUE TITLE
v3 Upgrade Code needs to prohibit specific upgrades

### ISSUE THREAD

**Issue by claytondaley** [piwik/piwik#11552]
As I documented in #11067, the upgrade code for numerous 2.x versions make calls to core plugins like plugin manager.  When these upgrades are run against the 3.x codebase, they don't work right.

I believe the simplest option is to modify the 3.x upgrade code to prohibit users from upgrading an "old" 2.x branch (i.e. except the latest, 2.16.5).  Other versions may work, but I don't see any advantage to figuring out which.  If a pre-2.16.5 version is found, tell the user that they need to update to 2.16.5 first.

Obviously, it would be even better if the 3.x upgrade code could automatically "downgrade" the install to 2.16.5 (i.e. download and unzip-over).

**Comment by mattab** [comment]
Thanks for the report. We haven't been able to reproduce an issue, upgrading from old Piwik version work as expected. If you can identify and reproduce an error please let us know the protocol to reproduce?
