### ISSUE TITLE
Preset/Saved Custom Date Ranges 

### ISSUE THREAD

**Issue by MackieeE** [piwik/piwik#11554]
I often found myself logging into Piwik Dashboard and wanting to quickly see info from a certain date. Resorting to changing the Date range from the Default to a custom "*Date Range*" for different points in time - for example:

- Since the day of Launch
- Since the day when our Advert was released.
- Since the day of the Hardware Upgrade

As often enough, Month/Week/Day will often include the days prior that had no relevant data - much prefer to report from the beginning of something - not necessarily something to compare against.

In that respect, having a dropdown list from inside the "Date Range" of a key "Milestone" start date - until Present.

You may all probably tell me something else is already in place at a more advanced level (Reporting, Segments). However I do feel that a quick summary change on the Dashboard would be beneficial.

See below for a very quick mock-up!

![custdate](https://cloud.githubusercontent.com/assets/883702/24449674/fdebc19c-146f-11e7-8f80-b8788bca3d36.jpg)

(As re-posted from [**Piwik forums**](https://forum.piwik.org/t/preset-saved-custom-date-ranges/23573))

**Comment by tsteur** [comment]
This is similar to https://github.com/piwik/piwik/issues/9094 and marking it as a duplicate. I will leave a comment in the other issue. It would be really great to have 👍
