### ISSUE TITLE
Some Overlay UI tests are failing

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11550]
Following UI tests have regressed recently and are now failing:

* Overlay_page_new_links.png
* ~~Overlay_row_evolution.png~~
* ~~Overlay_transitions.png~~

Example: http://builds-artifacts.piwik.org/piwik/piwik/Findus23-icons-as-a-submodule/22704/

We've seens this particular regression in the Overlay UI tests several times over the last few months/years. It should be very interesting to find out what is the cause this time.

**Comment by sgiehl** [comment]
I've fixed two tests, but the first one is still failing. Tried a lot, but couldn't get it fixed. Will give it another try when I'm done with some other issues
