### ISSUE TITLE
Old data not available after upgrade to version 3

### ISSUE THREAD

**Issue by wadecaldwell** [piwik/piwik#11564]
I am not sure where the bug is because so much had to be done in order to upgrade my server to version 3, which required a newer version of PHP. 
Here are the steps I had to do:

1. Perform a full server drive duplication
2. Upgrade Mac OS to 10.12 in order to upgrade to Server 5.2 in order to get a newer version of PHP
3. PHP version built into Server was only slightly above minimum for Piwik, so I upgrade to current stable 7.1
4. installed Piwik version 3 and made adjustments and permissions to get it up and running.
5. Up and running since March 5, but lost all of my sites, goals, users, etc. (I must have done something wrong there)
6. Added back all sites, goals and users
7. Needed to pull end of month reports this week, so I started to working to pull in old data
8. Old access log files are on the duplicated drive, so I found the instructions on the Piwik site to process those logs and picked a smallish one to test on, used python import_logs and console core:archive, after a few tries, i got them both to execute, but saw no change in data in that site.
9. Have clients waiting on reports, but since we use ?src= referrer strings, Google analytics doesn't show anything. 

Please let me know what I can do to help move this forward. 
Thanks, Wade

**Comment by mattab** [comment]
Hi there,

> Up and running since March 5, but lost all of my sites, goals, users, etc. (I must have done something wrong there)

We didn't hear before that this was an issue, so indeed something must have gone wrong.

Would recommend to restore your data from backup and try again the upgrade. If you are seeing all your data in Visitors > Visitor log, then you should be able to fix the problem with: https://piwik.org/faq/troubleshooting/faq_42/
