### ISSUE TITLE
Undefined index warning in archive log (plugin: DevicesDetection)

### ISSUE THREAD

**Issue by phoob** [piwik/piwik#11567]
As reported here: https://forum.piwik.org/t/undefined-index-in-devicesdetection/22445/5 , it seems I am not alone in getting this warning in piwik logs when archiving:

```
WARNING DevicesDetection[2017-03-30 18:35:06] 
/var/www/piwik/public_html/plugins/DevicesDetection/Archiver.php(91): 
Notice - Undefined index: CONCAT(log_conversion.config_device_brand, ';',
log_conversion.config_device_model) - Piwik 3.0.2 - Please report this message
in the Piwik forums: http://forum.piwik.org (please do a search first as it might 
have been reported already)
```

I don't really know what other information could be relevant.. I am running Piwik 3.0.2 on Apache 2.4, PHP 7.0.15. Please let me know if I can contribute any other information.

**Comment by sgiehl** [comment]
thanks for the report. Will have a look

**Comment by phoob** [comment]
(thumbsup)
