### ISSUE TITLE
Request for events in Live plugin

### ISSUE THREAD

**Issue by hrhthegreat** [piwik/piwik#11560]
Hello,

I develop my own plugin and I created custom columns for my plugin as VisitDimension and ActionDimention. Now I want to include my variables in the Live API report. I don't want to touch the Live Plugin code in order to have the updates of Piwik.
Is it possible to request for events in functions like Live/Model (queryActionsForVisit) so I can add my columns to the query? 
I know I can get all the data as Datatable and add my columns but it requires running new query. By having a few more postEvent, It's more efficient and easy to implement it.

Thank you

**Comment by mattab** [comment]
Hi @hrhthegreat 

Please check our ongoing work to allow you to hook into the Live API report in: https://github.com/piwik/piwik/pull/11579 and feel free to leave your comments there
