### ISSUE TITLE
Custom dimensions on events

### ISSUE THREAD

**Issue by interworks-morr** [piwik/piwik#11565]
I need to track multiple additional dimensions when a user interacts with a page.

For instance, filtering data that is shown on a page should be able to track the content type that is being filtered (article, image, etc), which field is being filtered (year, region, etc.), the actual filter value (2017, Northwest, etc.), groups, subgroups, and N-level predefined sub-subgroups for categorizing the data (sales->annual sales, etc.).  Other actions/events that also need to be tracked could include sorting, tagging, etc. with a similar levels of detail needed.

I attempted to use the custom dimensions plugin, but it does not appear to work in this way.

**Comment by mattab** [comment]
Custom Dimensions plugin should work and let you track dimensions for pages.
