### ISSUE TITLE
Result got truncated when call month/week API

### ISSUE THREAD

**Issue by xiaotaozi1127** [piwik/piwik#11576]
Hello,

I fund that the data result will be truncated when i call **Live.getLastVisitsDetails** API with month/week as period. 

For example:
$monthData = \Piwik\API\Request::processRequest('Live.getLastVisitsDetails', array(
            'idSite' => $idSite,
            'period' => 'month',
            'date' => '2017-03-01',
            'segment' => false
        ));

I expect the data can include the whole March data about user visits details. However, when i debug the result, i found it only contains Mar 31, Mar 30 and Mar 29 **three days data**. Where is the data before Mar 29? Is it possible that the result is too large that being truncated?

Because if i visit the API in browser
https://rpc1999.com/index.php?module=API&method=Live.getLastVisitsDetails&idSite=1&period=month&date=2017-03-01&format=xml&token_auth=a1eaed46a3a773635c84699570df3a56
i can see more result which is end at Mar 17. How to explain it?

Similar problem when i call Week data.
$weekData = \Piwik\API\Request::processRequest('Live.getLastVisitsDetails', array(
            'idSite' => $idSite,
            'period' => 'week',
            'date' => '2017-02-27',
            'segment' => $segment
        ));

I expect the result can contain data from 2017-02-27 to 2017-03-03.
However, i can only see data Mar 3 and Mar 2. The data between Mar 1 and Feb 27 is missing.

If i look this in browser,
https://rpc1999.com/index.php?module=API&method=Live.getLastVisitsDetails&idSite=1&period=week&date=2017-02-27&format=xml&token_auth=a1eaed46a3a773635c84699570df3a56
I found the result is more accurate. From Mar 3 to Feb 27, the data is more convincible. 

Did you receive any similar issue?
I really appreciate that you can help me.

**Comment by RMastop** [comment]
Hi @xiaotaozi1127 ,
By default a max of 100 items will be returned by the API. Use filter_limt and filter_offset to get all data.
Check the following page for details:
https://developer.piwik.org/api-reference/reporting-api

Cheers,
Richard

**Comment by tsteur** [comment]
See comment from @RMastop . `filter_limit` and `filter_offset` will be your friend :)

**Comment by xiaotaozi1127** [comment]
Thank you very much. Great, It helps.
