### ISSUE TITLE
In the Campaigns report, add a note about our Marketing Campaigns Reporting plugin

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11570]
It would be great to advertise our [Marketing Campaigns Reporting](https://plugins.piwik.org/MarketingCampaignsReporting) in the Referrers > Campaigns report.

**Comment by mattab** [comment]
@sgiehl let's do this one before RC

**Comment by sgiehl** [comment]
Would be easy to implement, but I wonder why we should advertise our own open source plugins. If we want to ensure people use our plugins we can simply add them to core. 
If we want to advertise those plugins, maybe we could show them as recommended in marketplace, but I would try not to flood more reports with advertisements for other plugins.
