### ISSUE TITLE
call same API by different way got different result

### ISSUE THREAD

**Issue by Shengzhi-Wang** [piwik/piwik#11575]
hello, 

i found an issue which is same API call got different result when called by different ways.

one way:
$data =  \Piwik\API\Request::processRequest('Live.getLastVisitsDetails', array(
            'idSite' => $idSite,
            'period' => $period,
            'date' => $date,
            'segment' => $segment
        ));

another way:
$data2= \Piwik\Plugins\Live\API::getInstance()->getLastVisitsDetails($idSite, $period, $date, $segment);

$data2 has 75 rows, but $data1 has 52 rows.
Right now I just find it in Live.getLastVisitsDetails API.
It seems that I use the same API. why $data is different with $data2?

Thanks,

**Comment by tsteur** [comment]
Which URL do you use to call the first way? Any URL parameter will be also used in the API call and could change the result.

**Comment by xiaotaozi1127** [comment]
i am in the same team with shengzhi.
@tsteur, what do you mean for URL parameter? we only pass idSite, period, date and segment parameters.

**Comment by tsteur** [comment]
The PHP script that calls ` \Piwik\API\Request::processRequest(...)` do you call that? On command line? Or via HTTP? If via HTTP, with with URL parameters in the URL?
