### ISSUE TITLE
Month data is not equals to sum daily data

### ISSUE THREAD

**Issue by Shengzhi-Wang** [piwik/piwik#11574]
Hi,
I find an issue month result is not equals to sum of daily data.
For example:
When I call Live.getLastVisitsDetails API by month like March 2017

I get the data from http request like :
index.php?module=API&method=Live.getLastVisitsDetails&idSite=1&period=month&date=2017-03-01&format=xml
I can get 14 rows.

But when I sum the daily data :
index.php?module=API&method=Live.getLastVisitsDetails&idSite=1&period=day&date=2017-03-01&format=xml
index.php?module=API&method=Live.getLastVisitsDetails&idSite=1&period=day&date=2017-03-02&format=xml
.....
index.php?module=API&method=Live.getLastVisitsDetails&idSite=1&period=day&date=2017-03-31&format=xml
It's more than 14 rows.

Can you check this for me?
Thanks,

**Comment by xiaotaozi1127** [comment]
i know this issue is not a real issue. when call month API, we forgot add filter_limit parameter, so it only return default items.  you can close this issue.

Thanks,

**Comment by tsteur** [comment]
Thanks for letting us know
