### ISSUE TITLE
row evolution: which year(s) are shown?

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11583]
Doing some long term investigations using row evolution, there is a small problem:
looking at the graph there is no information about the years shown.

please see attachment.

![2017-04-04_11h18_49](https://cloud.githubusercontent.com/assets/5681880/24649966/0b86f4da-1929-11e7-9940-09a408c6a7f0.png)

**Comment by hpvd** [comment]
other example:
![2017-04-04_11h28_01](https://cloud.githubusercontent.com/assets/5681880/24650242/e6416786-1929-11e7-913b-27834c626e23.png)

**Comment by mattab** [comment]
Thanks for the report @hpvd, see duplicate issue also created recently: https://github.com/piwik/piwik/issues/11452
