### ISSUE TITLE
text displayed on top of each other on visitor profile window

### ISSUE THREAD

**Issue by forreggbor** [piwik/piwik#11589]
The texts are displayed on top of each other when viewing Visitor profile window.
Tested on Ubuntu 16.10 with latest Chrome and Firefox.

![kijeloles_046](https://cloud.githubusercontent.com/assets/23742538/24693692/10ceba48-19df-11e7-917e-81961ca79b07.png)

**Comment by sgiehl** [comment]
will be solved with my visitor profile refactoring
