### ISSUE TITLE
Can we delete some fonts from the CpChart library to make Piwik release smaller?

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11581]
Follows up #11559 

### Can we delete some fonts from the CpChart library to make Piwik release smaller?

* Our current way of documenting Chart support for "unicode" languages is done via our unifont.ttf font as per these instructions: https://piwik.org/faq/how-to-install/faq_142/
* But seems CpChart embeds some fonts as well:

![fonts](https://cloud.githubusercontent.com/assets/466765/24633335/4dd90d7a-18c8-11e7-9427-5d17bdc46845.png)

As our previous pChart library didn't have those fonts we're wondering:
* Are these fonts used sometimes, in some graphs or for specific charsets / languages? 
  * if so, when are these fonts used?
* or can we delete them?

**Comment by sgiehl** [comment]
Most fonts shouldn't be required as we aren't using them. CpChart uses `GeosansLight.ttf` as default, but should use our fonts as we explicitly set them.
So imho it should be safe to remove all fonts execpt of `GeosansLight.ttf`

**Comment by aureq** [comment]
@sgiehl Thanks for the PR.

I'm wondering what's the best way to approach this.

To remove the fonts, a custom code is required. But if later a removed font is used, some code in the packaging script will have to be amended again.
As opposed to just keeping the fonts and not changing the packaging script which would allow any developer/contributor to make use of these fonts.

Thoughts?

**Comment by sgiehl** [comment]
I wouldn't include them by default. If someone would like to use another font, than those already included in Piwik, he can provide the font within his plugin. And if we decide to use a new font, I wouldn't rely on a font included in a third party package, as that might change from version to version

**Comment by mattab** [comment]
> As opposed to just keeping the fonts and not changing the packaging script which would allow any developer/contributor to make use of these fonts.

@aureq our goal with removing extra files is to keep the release ZIP/Tar.gz packages as small as possible and only include files which are needed to run Piwik. Our release package is already quite big (ZIP approximately 17M or 18M) , but as far as I can see all of the files are needed to run Piwik
