### ISSUE TITLE
[2.16.4] dbname value under database_tests section overridden in tests/javascript/piwik.php

### ISSUE THREAD

**Issue by yarimadam** [piwik/piwik#11587]
hi there,

i'm trying to perform unit tests for piwik.js trough http://example.tld/tests/javascript/.

however, some part of the tests were failing due to getting 500 error from XHR made to /tests/javascript/piwik.php.

after spending some time i found that the file tests/javascript/piwik.php overrides value of the dbname (database_tests section) to **tracker_tests** which doesn't exists.

i can confirm that i am able to perform all unit tests after i created tracker_tests database.

any suggestions? is it a potential bug or i'm i missing something?

**Comment by mattab** [comment]
Hi @yarimadam 
Thanks for the report. the `tracker_tests` mysql DB should be automatically created when executing the tests. in some cases it does not work. What would be useful is that when we load the page `/tests/javascript/` we could display a warning in case the `tracker_tests` mysql DB cannot be created for some reason.

**Comment by mattab** [comment]
Feel free to create a PR if you can for this improvement. For now we'll close the issue
