### ISSUE TITLE
Grey border around flags in Datatable also affects other icons

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#11586]
Unfortunately I'm a few hours late for 3.0.3, but I just noticed it after updating my public piwik instance.
The grey border in the country overview also affects the other icons in the row:

![screenshot_20170404_173505](https://cloud.githubusercontent.com/assets/6266037/24665286/3e4c84f0-195d-11e7-9000-3fd95bf4402a.png)

It seems like the css selector introduced in https://github.com/piwik/piwik/pull/11553/commits/22f4a9f06986aac3d17572fa925babb0a7899a74 is a bit too broad as not only the span around the flag and text has the class `label` but also the whole `tr`.

Replacing it with `.dataTable .label .label img {` is ugly, but works.

**Comment by Findus23** [comment]
@mattab, do you have a idea how to solve this? I am missing the time to look into it at the moment, but I think this should be solved until the release of 3.0.4.

**Comment by mattab** [comment]
Hi @Findus23 we'll investigate this for 3.0.4

**Comment by sgiehl** [comment]
I'll change it to use `dataTable .label > img` instead. Should solve the issue, as well
