### ISSUE TITLE
API: Actions.getOutLinks doesn't work with Segmentation

### ISSUE THREAD

**Issue by iadj** [piwik/piwik#11594]
I have a page tracked by Piwik with the URL `http://localhost/somelink`. There's an outlink on the page i.e. `http://google.com`.

If I create a GET request to the API with `&method=Actions.getOutlinks&segment=pageUrl==http://localhost/somelink` nothing shows up.
If I remove the segment from the request it shows the outlink (including all other outlinks).

**Comment by iadj** [comment]
You can also try this with the demo:
```
https://demo.piwik.org/?module=API&method=Actions.getOutlinks&idSite=7&period=day&date=today&format=xml&token_auth=anonymous&segment=pageUrl=@piwik
```

This doesn't return anything, while removing the segment tag will display all results.

**Comment by mattab** [comment]
You need to use `actionUrl` segment instead of `pageUrl` so it matches pages + download + outlink, or use `outlinkUrl`
