### ISSUE TITLE
[Request] Need to combine the mumber of same page counting

### ISSUE THREAD

**Issue by ChrisR1993** [piwik/piwik#11599]
@tsteur 
Hi, hope you doing well.
I had an issue about the same page counting.
for instance, 

pageA.com/A/
pageA.com/A/index.html

these two address are totally  identical page, but counted separately like the result of 

pageA
 /index.html 40,000
 /index          900

So I and my customers have to do the math every single time to caculate the sum total and it 
takes very long time.

I want to combine these into one analysis result and get the sum automatically.
Can you help me with this.

Appreciate your help every time.
Regards,

Chris

**Comment by Findus23** [comment]
While this isn't a direct solution to your problem, it's always helpful to have only one url for one page (and setup a redirect)  as it can create many other problems (e.g. duplicate results in search engines)

**Comment by tsteur** [comment]
As @Findus23 suggested redirects might be a good idea. Also in the JavaScript tracker you could set the URL always to the same URL manually. I think the method for this is `setCustomUrl`.

If you are familiar with PHP there may be a solution to group those results with a Piwik Plugin using the `GroupBy` filter. Setting custom URL manually may be the easiest solution. Eg in pseudo code:

```
if (url = /) {
  _paq.push(['setCustomUrl', '/index.html'])
}
```

**Comment by ChrisR1993** [comment]
@Findus23 @tsteur 

Thank you, appreciate your answers, so as my understanding there's no way to set the log import file to 
solve this issue, right?
