### ISSUE TITLE
setUserID:  Users are being counted 3 times Visitor Id is taking precedence over User Id

### ISSUE THREAD

**Issue by bflanagan78** [piwik/piwik#11593]
Hi,

We recently migrated to AWS and in both of our instances of Piwik 2.16.5 production and 3.0.2 staging we are now seeing User Ids being counted as 3 unique visitors.  We are running PHP 7.x and MySQL 5.7

setUserId is being used, however the Visitor Id is still taking precedence over the User Id.  A single user (one unique User Id) is being counted three separate times because the visitor id has changed three times.  Every time the visitor id changes, that user is being counted as a new user.  A segment for a particular User Id will return a single user, but will be counted as three unique visitors.

any thoughts, Thanks

**Comment by bflanagan78** [comment]
Clarification, we are tracking over 100+ sites and each site Piwik assigns a different Visitor ID for the same User ID.  We did not see this issue with Piwik 2.11.  Is there a user table per site and/or overall global table?  Will we need to wait for the resolution of #11411 or should we try tracking multiple domain names as discussed in the thread below?  

Tracking multiple domain names in the same website documentation    https://github.com/piwik/developer-documentation/commit/70a72f3f66a9385bcaf416e4454cfa0a812c2cd3

Thanks.

**Comment by mattab** [comment]
Hi @bflanagan78 
Could you please create a new issue and paste there a small HTML code that can be used to reproduce a problem, as well as "We got XYZ but expected ABC". Thanks
