### ISSUE TITLE
Css not loaded

### ISSUE THREAD

**Issue by FinnFrotscher** [piwik/piwik#11608]
I installed piwik on a LAMP stack. I can load the installer interface but the css is not loaded.

![screen shot 2017-04-10 at 23 08 20](https://cloud.githubusercontent.com/assets/11148454/24882810/ac76f1ba-1e42-11e7-9cc3-b6275aba44ff.png)

**Comment by Findus23** [comment]
What is the error in the console? Is it possible you are using an adblocker (with too broad rules)?

**Comment by FinnFrotscher** [comment]
`uBlockOrigin` killed the css...
