### ISSUE TITLE
getCoreJs extremly slow

### ISSUE THREAD

**Issue by simonmilz** [piwik/piwik#11606]
Hi guys,

I just installed Piwik on a fresh Ubuntu 14.04 VM. Installation works fine, everything was easy peasy. But the UI is extremly slow. As you can see in the image `getCoreJs` call takes over 1 minute.

![getcorejs](https://cloud.githubusercontent.com/assets/5016123/24857847/ff60cbd4-1de9-11e7-9e64-3359a3241089.PNG)

OS: Ubuntu 14.04
Piwik: 3.0.3
PHP: 7.1 (tested everything also with 5.x)
Sessions: dbtable

Anyone have an idea what this is?

**Comment by Globulopolis** [comment]
It's server error. See you apache or nginx logs for errors

**Comment by mattab** [comment]
Do you still experience this issue? Any error in your server log?

**Comment by lnicola** [comment]
I'm seeing the same thing. Looks like it's hitting some quadratic or exponential behavior in `getCoreJs`:

![image](https://user-images.githubusercontent.com/308347/108484242-4e5f3f00-72a4-11eb-8495-3c9eac4c5421.png)

```
Maximum execution time of 300 seconds exceeded in /srv/http/REDACTED/vendor/matomo-org/jshrink/src/JShrink/Minifier.php
```

**Comment by lnicola** [comment]
As a quick workaround, you can comment out the `$jshrink->minifyDirectToOutput($js, $options);` call in `Minifier.php`.

This might be no longer needed in Matomo 4.
