### ISSUE TITLE
Piwik installation

### ISSUE THREAD

**Issue by FinnFrotscher** [piwik/piwik#11607]
I am trying to install piwik on an empty fresh `Ubuntu 16.04` distribution. 
The installation guide for piwik states that i just have to unzip and visit my servers url.
That does not work. no welcome screen.

obviously there are implicit dependencies that the guide omits.  what is missing?

**Comment by FinnFrotscher** [comment]
-- Update --
I worked it out. The LAMP stack needs to be preloaded.
it would be nice to put that in the instructions.

**Comment by Findus23** [comment]
What do you mean by "preloading" a LAMP stack?

**Comment by FinnFrotscher** [comment]
Just that LAMP needs to be installed and setup prior to starting the piwik installation.
