### ISSUE TITLE
Unexpected website exception thrown while getting report with Request::processRequest(args)

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#11600]
I'm writing a new plugin using this short snippet of code querying VisitsSummary.get API method, but unluckly.

```php
    public static function getVisitsSummary()
    {
        Access::getInstance()->setSuperUserAccess();

        $report = Request::processRequest(self::$method, [
            'idSite' => self::$idSite,
            'date'   => self::$date,
            'period' => self::$period,
        ]);

        return $report;
    }
```
My unit test is throwing an exception: 
> Exception: An unexpected website was found in the request: website id was set to '1' .
I've tried passing `idSite` also as array but with no luck.

I've also tried calling the API directly (but isn't a good practice as shown in docs):
```php
        $report = \Piwik\Plugins\VisitsSummary\API::getInstance()->get(
            self::$idSite,
            self::$date,
            self::$period
        );
```
In this case I got a more detailed backtrace:
> Piwik\Exception\UnexpectedWebsiteFoundException: An unexpected website was found in the request: website id was set to '1' .
>
> /home/dev/piwik/core/Site.php:128
> /home/dev/piwik/plugins/SitesManager/API.php:195
> /home/dev/piwik/core/Site.php:432
> /home/dev/piwik/core/Site.php:494
> /home/dev/piwik/core/Archive.php:215
> /home/dev/piwik/plugins/VisitsSummary/API.php:28
> /home/dev/piwik/plugins/RerVerify2/RerVerify2.php:45
> /home/dev/piwik/plugins/RerVerify2/tests/Unit/RerVerifyTest.php:78

Reading the code looks like idSite argument get lost (empty) in its road to Site.php:128 but I can't really say where, because at UnexpectedWebsiteFoundException idSite stills `1`.

Any help is appreciated, ciao!

**Comment by tassoman** [comment]
This exception was talked about in: #8534 #8396 #7698

**Comment by tsteur** [comment]
You would need to create an integration test (instead of unit test) and make sure to create a site for example in the setUp method of the test.

**Comment by tassoman** [comment]
Ciao @tsteur I've switched the test to an Integration Test (using console generator) then I've added fixtures to `setUp()` but _with no luck_, the exception still there.

```php
    public function setUp()
    {
        Fixture::createSuperUser();
        Fixture::createWebsite('2017-01-01 00:00:00');

        parent::setUp();
    }
```

**Comment by tsteur** [comment]
Try to call the parent setUp first and then it should work I presume
