### ISSUE TITLE
PHP7 error: Notice - A non well formed numeric value encountered

### ISSUE THREAD

**Issue by canajun2eh** [piwik/piwik#11603]
See this forum topic:
[(https://forum.piwik.org/t/non-well-formed-numeric-value-encountered-upon-upgrading-to-3-0-2/23314)]

When using PHP7, the above error is posted.  The incorrect code exists even in Piwik 2.14.3 .

The fix, which works for all versions of PHP, is to add the following line
`$v_memory_limit = substr($v_memory_limit, 0, -1); // drop G, M, or K suffix`

In Piwik 2.14.3, the above line should be added following line 1838 of vendor/piwik/decompress/libs/PclZip/pclzip.lib.php

In Piwik 2.17.1 and later versions, the above line should be added following line 1789 of vendor/piwik/decompress/libs/PclZip/pclzip.lib.php

I can't tell you where the line should be added in Piwik versions between 2.14.3 and 2.17.1

**Comment by sgiehl** [comment]
We recommend to update to Piwik 3. This error should be fixed there.

**Comment by Findus23** [comment]
It was fixed in https://github.com/piwik/component-decompress/pull/9 and was also mentioned in https://github.com/piwik/piwik/issues/11335

**Comment by sgiehl** [comment]
@canajun2eh feel free to create a PR for `2.x-dev` so it would be fixed in a new release of 2.x LTS.
