### ISSUE TITLE
what should I do to record two (or more) different campaigns successively in very short time

### ISSUE THREAD

**Issue by JamesJungmoonLim** [piwik/piwik#11604]
I had the test that if piwik could record two different campaigns A and B when I visit the site through campaign A then B successively in very short interval. (about 10 seconds,  I know it is much more less than 30 minutes, the session time)
(with url parameter; pk_campaign=A&pk_keyword=a
                                pk_campaign=B&pk_keyword=b)

Piwik recorded my two visits but did not capture campaign B, the second campaign.
Only campaign A is recorded. However I want to track every campaign although there was very short term between the visits.

So I had some googling,
then, I changed the variable **"create_new_visit_when_campaign_changes" to 1** in config.ini.php

but It doesn't work.

How can I figure it out? Please help!

**Comment by sgiehl** [comment]
duplicates #11605
