### ISSUE TITLE
Trying to resurrect Piwik / out-of-memory condition

### ISSUE THREAD

**Issue by buzz** [piwik/piwik#11609]
Hey,

I'm reading issues for the last hour and couldn't find something helpful.

Trying to resurrect a Piwik instance that is tracking 5 websites. Four of them just have a couple of views per day. One has about 300 to 500 views per day. I've been using Piwik for many years. Database is close to 2G in size.

Piwik was offline for about 40 days due to a server failure. I installed Piwik on a fresh nginx/mariadb/php7 stack and imported the old database. Upgrade to newest Piwik was not a problem. (Before i was running PHP5.)

I think I'm suffering from the infamous out-of-memory problem during archival.

While browsing the issues I see people using ridiculous values like `memory_limit=6G` (#10726). My server just has 1G installed which has been sufficient so far.

I can't even log-in. Piwik gives:

    Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/core/FrontController.php on line 416

Also I tried running on the command line using `console core:archive`. Same result.

I put `browser_archiving_disabled_enforce = 1` in the config file to prevent Piwik to archive on-the-fly, hoping to be able to login at least. It doesn't seem to have any effect. `index.php` is still running out of memory after a couple of minutes.

Is there anything left I could do?
I figured to ask for someone pointing me to the right direction.

I was thinking on 2 possible next steps:

1. Archiving incrementally: Something like running `core:archive` subsequently for every day in the last 40 or so days.
1. Temporarily installing Piwik on my desktop machine (8GB RAM) to do the archive job and copy back the database to the server.

Any help highly appreciated!

**Comment by tsteur** [comment]
Both next steps sound good and I'd recommend to try step 1).

When you disable browser archiving and you enforce it, it should not run into memory issues. Make sure to set option name "enableBrowserTriggerArchiving" to `0` in "piwik_option" table.

Please ask questions in the future in the forum: https://forum.piwik.org/ as we don't answer questions like these here usually.
