### ISSUE TITLE
No country/device icons with release 3.0.3

### ISSUE THREAD

**Issue by nebulade** [piwik/piwik#11617]
Hi, just installed 3.0.3 and it seems that none of the new icons are part of the release tarball. 
Specifically the folder `/piwik-3.0.3/plugins/Morpheus/icons/` is empty, but it looks like it should contain all those icons from the new piwik-icons repo. 

Is there some build/install step I am missing?

Thanks

**Comment by sgiehl** [comment]
Did you download Piwik from github or the official release package from piwik.org?

**Comment by Findus23** [comment]
What file do you mean by `release tarball`. If you mean the ones from github (https://github.com/piwik/piwik/releases), those are just for development, 

Instead I recommend you to use the following:
- Latest stable production release can be found at https://piwik.org/download/ (learn more) (recommended)
- Beta and Release Candidates releases can be found at https://builds.piwik.org/ (learn more)

**Comment by nebulade** [comment]
Ah ok, that explains, so the exact link for me was https://codeload.github.com/piwik/piwik/tar.gz/3.0.3
Didn't know there was a difference between those tarballs, because I used them fine previously. So I guess there were some hidden issue all along then.

Will close it then. Thanks!
