### ISSUE TITLE
Segments to filter URLs are not reflected in Dashboard widgets

### ISSUE THREAD

**Issue by gbrener** [piwik/piwik#11618]
Hi Piwik team,
My goal is to create segments of users based on the URLs that they visit (or don't). However when I add a segment to do this (either by Action URL, Clicked URL, or Page URL) with a "Does not contain" matcher and a small substring, the Dashboard widgets still show URLs that contain the substring.

Steps to reproduce:
1. Add Visitor Log widget to the default Dashboard
2. Add a new Segment with "Action URL" + "Does not contain" + "<part of a URL that is already in the log"
3. View the Visitor Log widget (it still contains the matching URLs)

If there's a simpler way to do what I'm describing, please let me know.

**Comment by mattab** [comment]
Hi @gbrener 
this is expected behavior. Segments apply to Visits, not Actions. The URLs segment, do not filter out URLs from the visits, but they filter out Visits and will remove visits that do not contain the URL part.
