### ISSUE TITLE
Create and Schedule a report: "Send report to" "Send to me" gets selected while editing

### ISSUE THREAD

**Issue by andristeiner** [piwik/piwik#11622]
While saving any email report, the checkbox "send to me" gets always selected, even if the selection was changed or not there before.

# Versions

* Piwik 3.0.3
* PHP 5.6

# Steps to reproduce

* Open Personal > Email Reporst
* Create and Schedule a report, or edit an existing one
* Uncheck the "Send to me" checkbox and add another email address in the "Also send the report to these emails (one email per line):" field
* Create report
* Send to me is not active and recipient is the other email address (expected behaviour)
* Edit report
* "Send to me" checkbox is still not checked
* Change other values, or don't change anything at all
* select "Update report"
* **Report is sent to the other email address and my own as well (even te "Send to me" checkbox was not touched)**
* Edit report
* "Send to me" checkbox is checked
* Uncheck "Send to me"
* Update report
* Send to me is not active and recipient is the other email address (expected behaviour)

**Comment by mattab** [comment]
Thanks for the report, I could reproduce the issue using the steps. Seems the box becomes checked when we add an email address in "Also send the report to these emails (one email per line):"
