### ISSUE TITLE
Segment settings lost while updating segment

### ISSUE THREAD

**Issue by andristeiner** [piwik/piwik#11624]
After editing a segment, all settings ("This segment is visible to", "and processed for" and "processing") are lost.

# Versions

* Piwik 3.0.3
* PHP 5.6

# Steps to reproduce

* edit a segment with a custom setting in one of "This segment is visible to", "and processed for" or "processing"
* change some value
* save segment
* segment settings are set back to the default settings (This segment is visible to: me and processed for this website only and reports are processed in real time)

**Comment by mattab** [comment]
and thanks for the report @andristeiner :+1:
