### ISSUE TITLE
Improve Brand icons

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#11626]
Now that most of piwiks icons are improved there is just one large collection from #11155 left: The brand icons

I am missing an idea how to automatically collect them, but in my opinion even if we just replace some of them (the most common ones) it's still an improvement. (See https://github.com/piwik/piwik/issues/10587#issuecomment-269909494)

So if anyone has an idea or wants to help me, I am open to suggestions.

**Comment by sgiehl** [comment]
Could we maybe use the existing ones as basis and additionally maintain a list of sources to be able to update some of them automatically?

**Comment by Findus23** [comment]
If I have some spare time, I'll copy the status quo to the Piwik-icons repo, so it's easier to update them.

**Comment by sgiehl** [comment]
Is any work left on this issue, or did you already improve the icons?

**Comment by Findus23** [comment]
Everything that's left (even more/better brand icons) can be done on the piwik-icons repo.
