### ISSUE TITLE
API Goals.addGoal Error!!

### ISSUE THREAD

**Issue by druidajes** [piwik/piwik#11636]
With version 3.3 of piwik, when I try to add a target through the api, it returns the following error:

Mysqli prepare error: Unknown column 'description' in 'field list

I have looked in the piwik_goal table and indeed there is no such column (in fact no version exists, but in the new update when making the insert if you take it into account)

I've added this directly and it works:

ALTER TABLE lead_on_site.piwik_goal ADD description VARCHAR (255) after name;

A greeting!!

**Comment by sgiehl** [comment]
This should have been automatically done with updating to 3.0.0.
Maybe the [update script](https://github.com/piwik/piwik/blob/3.x-dev/plugins/Goals/Updates/3.0.0-b1.php) failed on your side somehow.
