### ISSUE TITLE
Create segments including a whitespace in the definition at demo.piwik.org

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#11637]
Hi,

would it be possible to insert some dummy data (urls including a whitespace) into current Piwik demo and create segments including a whitespace to make #10973 reproducable?

Best regards,
Markus

**Comment by mattab** [comment]
Hi Markus,

Sure it is possible. For example you can visit pages URL with a space in them and even if they are 404 they will be tracked. Then you should see the data in the demo.

**Comment by iMarkus** [comment]
Hi mattab,

but I am not allowed to create a segment in demo.piwik.org

You must be logged in to create and edit custom visitor segments. 
Best regards,
Markus

**Comment by mattab** [comment]
ok, which segment would you like me to create?

**Comment by iMarkus** [comment]
Hi Mattab,

thanks for your support. I created a Forum entry to test it. You see now the following was tracked:

![grafik](https://cloud.githubusercontent.com/assets/12813354/25839490/2ed93b16-3498-11e7-9b35-6b9ad4fc9dbc.png)

Please create a segment where PageURL contains

create segments including a whitespace

![grafik](https://cloud.githubusercontent.com/assets/12813354/25839639/ca53e73a-3498-11e7-9c8e-d3fe80aa46de.png)

Thanks,
Markus

**Comment by mattab** [comment]
The segment has been created: https://demo.piwik.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=7&segment=pageUrl%3D%40create%2520segments%2520including%2520a%2520whitespace%2520in%2520the%2520definition%2520at%2520demo%2520piwik%2520org&updated=1#?idSite=7&period=week&date=today&category=Dashboard_Dashboard&subcategory=1&segment=pageUrl%3D@create%2520segments%2520including%2520a%2520whitespace%2520in%2520the%2520definition%2520at%2520demo%2520piwik%2520org

There should be data displayed in a few hours after the next archiving run.

**Comment by iMarkus** [comment]
Hi,
thanks. Seems to work. Could you please also create the following segment:

_PageURL contains forum.piwik.org/t/create segments including a whitespace_

Regards,
Markus

**Comment by mattab** [comment]
done

**Comment by iMarkus** [comment]
Hi Mattab,

both are working fine. Thanks a lot!

Best regards,
Markus

**Comment by mattab** [comment]
So, can you reproduce this issue @iMarkus or is everything working?

**Comment by iMarkus** [comment]
Hi,

everything is working.
