### ISSUE TITLE
Custom plugin migration/update not recognized

### ISSUE THREAD

**Issue by alfonso-romero** [piwik/piwik#11648]
Hi

I'm trying to do an update on an existing custom plugin. Following the steps from https://developer.piwik.org/guides/extending-database

I ran the command `./console generate:update` and got the Updates directory with the 1.0.php file inside of it generated. I want to create a custom table on database, and I put the code accordingly inside the getMigrations() method.

But when I want to execute the update, command `./console core:update` always displays everything is up to date, but it never shows the pending update nor any sql queries to be executed, and table is never created on database.

I'm using the latest Piwik version 3.0.3 up until today, but can't get Piwik to recognize this update

Am i missing some additional setting somewhere else, or missing some step to be able to get this update done?

Thanks in advance, any help will be appreciated

**Comment by tsteur** [comment]
I presume the database has maybe already recorded that this version is installed. I would recommend to try changing the update class and filename from eg `1_0_0` to `1_0_1` and then also the plugin version from eg 1.0.0 to 1.0.1 in `plugin.json`.

Please ask such questions in the form in the future as we handle only bugs and feature requests here. https://forum.piwik.org/c/plugins-platform
