### ISSUE TITLE
Detect custom browser user-agent

### ISSUE THREAD

**Issue by kelson42** [piwik/piwik#11641]
Use case:
1 - Track web service usage used through custom built browser
2 - Custom build browser is identified with a custom user-agent string
3 - Web service is tracked using Piwik

Problem:
1 - Browser appears as "unknown"
2 - Stats (for "unknown" browser) are not meaningful as all unknown browsers are "mixed".
3 - No way to setup a new custom browser in the admin UI

Proposal of solution:
1 - Implement a way to add a custom user agent (browser name, etc... ) to the list of supported browsers (which can be display in admin UI "device detection" > "browser" > "show all")

**Comment by sgiehl** [comment]
You may do this by implementing a plugin for this.

**Comment by mattab** [comment]
As Stefan suggested we recommend  to create a new plugin for this.
