### ISSUE TITLE
Typo on German info page

### ISSUE THREAD

**Issue by maba4891** [piwik/piwik#11656]
If I click on the "info" icon in my German Piwik backend (/index.php?module=Feedback&action=index), there is a typo in the heading "Profesionelle Hilfe". It should read "Professionelle Hilfe" (with two s) 

Otherwise it doesn't look very professional ;)

**Comment by sgiehl** [comment]
Thanks for reporting this issue. Our translations are fully community contributed. I'll change the typo.
If you would like to contribute more to our translations, feel free to sign up for our project on Transifex: https://www.transifex.com/piwik/piwik/
