### ISSUE TITLE
Plugin Bandwidth no compatible with 3.0.3

### ISSUE THREAD

**Issue by sysC0D** [piwik/piwik#11666]
Hi,

After migrate Piwik 3.0.2 to 3.0.3 (Docker 3.0.3-php-fpm), i had Bandwidth plugin no compatible with this version.
For not uninstall plugin and lose previous data, go to Docker (exec /bin/bash): 
```
apt-get update; apt-get install -y git
cd /var/www/html/plugins; git clone https://github.com/piwik/plugin-Bandwidth.git
mv plugin-Bandwidth Bandwidth; chown -R www-data:1000 Bandwidth
```
No reload plugin page and plugin is now active :-)

**Comment by mattab** [comment]
Hi @sysC0D 
Bandwidth seems to work for us. If anyone else experiences the problem let us know
