### ISSUE TITLE
Piwik A/B Plugin causes error in archive cron

### ISSUE THREAD

**Issue by walter-ma** [piwik/piwik#11664]
Hi,

my company bought the Piwik premium plugin “A/B Testing”. 
Since the installation and the implementation of the code on our websites we have a problem to archive our data.

The archive cronjob throws following errors:
ERROR [2017-05-05 08:16:34] Got invalid response from API request: ?module=API&method=API.get&idSite=40&period=day&date=last52&format=php&segment=visitConvertedGoalId%3D%3D39&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:91:"Mysqli prepare error: Not unique table/alias: 'log_conversion' - caused by plugin AbTesting";}'
ERROR [2017-05-05 08:17:16] Got invalid response from API request: ?module=API&method=API.get&idSite=40&period=week&date=last2&format=php&segment=visitConvertedGoalId%3D%3D39&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:91:"Mysqli prepare error: Not unique table/alias: 'log_conversion' - caused by plugin AbTesting";}'
ERROR [2017-05-05 08:17:52] Got invalid response from API request: ?module=API&method=API.get&idSite=40&period=month&date=last2&format=php&segment=visitConvertedGoalId%3D%3D39&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:91:"Mysqli prepare error: Not unique table/alias: 'log_conversion' - caused by plugin AbTesting";}'
ERROR [2017-05-05 08:18:42] Got invalid response from API request: ?module=API&method=API.get&idSite=40&period=year&date=last2&format=php&segment=visitConvertedGoalId%3D%3D39&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:91:"Mysqli prepare error: Not unique table/alias: 'log_conversion' - caused by plugin AbTesting";}'

Has someone recongized this before and knows how to fix this?
I need a solution for this ASAP.

Thanks for any advices.
Best regards,
Mario

**Comment by sgiehl** [comment]
Our support team will investigate and get back to you.
For future issues please create a [support ticket](https://shop.piwik.org/tickets/) within your shop account or get in touch with our support team by mail.
