### ISSUE TITLE
How do I tell Piwik a user is using the app ?

### ISSUE THREAD

**Issue by FrankenSteinxD** [piwik/piwik#11692]
Hello.
What I need to do is to put some script in index.html, so that every time a user opens the app, piwik will know that, I am not using javascript tracker.
So, I want to send an ajax request to my backend, then my backend will talk to piwik.
But what request should I tell my backend to send to piwik for this action ?
I have only piwik actions on userRegister and userLogin, so if a user logged in a while ago and he didn't logout, how can piwik know that user is using the app so that I can get Monthly Active Users.

**Comment by sgiehl** [comment]
What kind of application are you trying to track? If it's a web app you should be able to include the javascript tracking code. For mobile apps based on iOS or Android you could use our Mobile SDKs (https://github.com/piwik/piwik-sdk-android / https://github.com/piwik/piwik-sdk-ios). There are also other SDKs you can use for other kind of applications.
