### ISSUE TITLE
AllTests CI job: a test is failing but the build job is green

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11695]
### Example #1

https://travis-ci.org/piwik/piwik/jobs/231488610

we see there was a failure in the system tests:
```
There was 1 failure:

1) Piwik\Tests\System\CsvExportTest::testApi with data set #3 ('Live.getLastVisitsDetails', array(1, '2010-01-03 11:22:33', 'csv', array('serverDate,actionDetails,serv...Action')))

Piwik\Tests\System\CsvExportTest: Differences with expected in '/home/travis/build/piwik/piwik/tests/PHPUnit/Framework/TestCase/../../System/processed/test_csvExport__Live.getLastVisitsDetails_day.csv'
```

#### Expected

When a test fails in the `AllTests` job, the job should fail

#### Got instead

The build is green, maybe because the UnitTests are passing?

### Example #2 

in https://travis-ci.org/piwik/piwik/jobs/231488611 one of the integration test failed: 
```
1) Piwik\Tests\Integration\ArchiveTest::testExistingArchivesAreReplaced

Failed asserting that 1 matches expected 2.`
```
The PluginTests are passing.

#### Got
 the job was green

#### Expected

 the job to be red/failing as one test failed

**Comment by sgiehl** [comment]
fixed in https://github.com/piwik/travis-scripts/pull/34
