### ISSUE TITLE
Debian Package for Piwki 3.0.3 still missing

### ISSUE THREAD

**Issue by gebi** [piwik/piwik#11705]
Hi,

Just a note, it's already 6 weeks since you released a new version which is marked critial for security and your mirrors still only have 3.0.2 as the lastest version as debian package.

It would be nice to have timely debian packages in the future, especially for security critical releases.

**Comment by mattab** [comment]
Thanks for the feedback. We're releasing piwik 3.0.4 today and will try to publish this new version quickly in the debian package. Maybe we could make our tools better so we can easier release new debian packages. And/or maybe we could get some help from new community member to help us maintain the debian package. We'll see what we can do!

**Comment by aureq** [comment]
Hi @gebi and @mattab 

Apologies for the delay. Version 3.0.3 is in the Debian repository now. Version 3.4 should follow shortly after its publication.

@gebi we are in the process of automating the Debian package build, but it takes a bit of time to get things right. When this is done, the Debian package should become available soon after a new release is published (a few minutes lag only in most cases).

**Comment by mattab** [comment]
@aureq Great news about the Automation of the Debian release! This will be awesome to have. Closing ticket as you mentioned you will release 3.0.4 debian package shortly. Thanks!

**Comment by gebi** [comment]
many thx for the quick update :)!
