### ISSUE TITLE
Piwik: Visitor Log and browser language

### ISSUE THREAD

**Issue by Fantomas777** [piwik/piwik#11707]
I suggest to enrich the existing visitor Log with the browser language.

**Comment by sgiehl** [comment]
Actually I'm currently refactoring / improving the visitor log and profile in #11579
I will take it in consideration to also display the browser language somewhere.

**Comment by sgiehl** [comment]
Will be displayed in the location tooltip after #11579 was merged.

**Comment by mattab** [comment]
Done in #11579
