### ISSUE TITLE
Document how to view our UI demo page in developer guides

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11710]
The UI demo is availabe in Piwik > Administration > Development > UI demo.

-> we should document our UI demo page in the developer guide in relevant places.

this will also fix https://github.com/piwik/piwik/issues/7652

Here is what the demo page looks like: 
![morpheus_load](https://cloud.githubusercontent.com/assets/466765/26126344/5a9428e6-3ad9-11e7-9a23-6b0887df0f24.png)

**Comment by spacenate** [comment]
I added a new section for this to the Views guide, linked to from other relevant guides 👍

**Comment by tsteur** [comment]
Thanks @spacenate  it is merged and deployed 👍 

In description it was mentioned that this issue will fix #7652 but this is not really the case as we ideally still have this page eventually embedded on developer.piwik.org
