### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.piwik_log_link_visit_action' doesn't exist

### ISSUE THREAD

**Issue by glatzenarsch** [piwik/piwik#11723]
Hi!

After upgrading piwik from 2.17.1 to 3.0.4 i cant get to my dashboard and have error message:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.piwik_log_link_visit_action' doesn't exist

What to do? My production is not working.

can i recreate that table and how?

ty

**Comment by mattab** [comment]
We recommend to import your table from a recent backup or so. Or if you don't have backups, re-install Piwik fresh in a new folder and import the the empty table in your old piwik
