### ISSUE TITLE
PIWIK Error

### ISSUE THREAD

**Issue by BCTH** [piwik/piwik#11730]
After sign-on, receive this error message: SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT,UPDATE command denied to user 'uwgSr3L5KD55l'@'69088336-fda7-40aa-a864-eea193bb9667.cell.default.w3ibm-cio-' for table 'piwik_option'

**Comment by Findus23** [comment]
`command denied to user` means that the MySQL user you are using doesn't have the permission to write to the database. 

Make sure you are using the right user.

**Comment by mattab** [comment]
When installing Piwik, you will need to specify a MySQL username and password. The MySQL user must have permission to create and alter tables in the database.

The MySQL USER should have the permission to SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES.

[Click here for detailed instructions on how to create a new database and MySQL user. ](https://piwik.org/faq/how-to-install/faq_23484/)
