### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by tflo** [piwik/piwik#11739]
As I saw this shiny thing I did what I always do with shiny things, I clicked it:

![screenshot 2017-05-25 at 18 56 31-pty-fs8](https://cloud.githubusercontent.com/assets/1410282/26461108/3388980a-417c-11e7-9b81-09a59b5ac25c.png)

But it only leads to a 404.

The broken link is : `https://piwik.org/recommends/heatmap-session-recording-learn-more/`

– Tom

**Comment by sgiehl** [comment]
Thanks for the report. That link should work now.
