### ISSUE TITLE
Add siteID to dashboard markup

### ISSUE THREAD

**Issue by DevDaveo** [piwik/piwik#11734]
This would be a very easy enhancement to add some sort of unique website identifier (e.g. data-id="23") inside the dashboard listing HTML code of all websites. So I could write a few lines of a [Userscript](https://tampermonkey.net/) to remove it from the overview as there is no way to archive or hide a site with Piwik itself without deleting it.

**Comment by mattab** [comment]
Hi @DevDaveo 

please submit a pull request for this, as we won't implement it otherwise. Thanks
