### ISSUE TITLE
File integrity check failed

### ISSUE THREAD

**Issue by Legion2** [piwik/piwik#11732]
After Update 3.0.4
```
Directories were found in your Piwik but we didn't expect them.
--> Please delete these directories to prevent errors. <--

Directory to delete: plugins/Morpheus/icons/submodules
```

**Comment by Findus23** [comment]
That's really odd. That directory should have never been there. You can safely delete it. Did you by change use the package from git(hub)?

**Comment by Legion2** [comment]
I used [https://builds.piwik.org/piwik-3.0.4.zip](https://builds.piwik.org/piwik-3.0.4.zip) to install piwik.

**Comment by sgiehl** [comment]
Hm. That directory does exist in the zip file. Guess we need to delete it in [the build script](https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh#L147)

**Comment by Findus23** [comment]
Ah, I created a new folder to make the repo more organized and didn't notice you changed the build-script in https://github.com/piwik/piwik-package/commit/e26d2ab6ccc088de72087d429056b1f0b84c537e to only delete the list of existing files.

**Comment by sgiehl** [comment]
Proposed a PR to fix it
