### ISSUE TITLE
action_title_category_delimiter not respected for transitions view

### ISSUE THREAD

**Issue by cgrottolo** [piwik/piwik#11754]
In Piwik 3.0.2, transitions view cannot be opened from Page Titles Report if action_title_category_delimiter had been set to a different value than '/' (in our case to '::').

**URL as generated by Piwik 3.02**
https://piwik.mydomain.com/index.php?date=2017-05-23&actionType=title&actionName=Shop%2FCheckout&expanded=1&format=JSON&module=API&method=Transitions.getTransitionsForAction&filter_limit=-1&idSite=22&period=day

Error message is: There's no data for Shop/​Checkout

**Working URL (constructed manually)**
https://piwik.mydomain.com/index.php?date=2017-05-23&actionType=title&actionName=Shop::Checkout&expanded=1&format=JSON&module=API&method=Transitions.getTransitionsForAction&filter_limit=-1&idSite=22&period=day

Transitions are shown correctly.

The bug only concerns transitions view. Row evolution view is working correctly.

**Comment by sgiehl** [comment]
Thanks for the report. I was able to reproduce and will have a look if it can be fixed easily.
