### ISSUE TITLE
Chrome privacy error

### ISSUE THREAD

**Issue by iyko** [piwik/piwik#11751]
Using Chrome Version 58.0.3029.110. When I try to access my Piwik site I get a privacy error stating that the site sent back unusual and incorrect credentials. I was able to get to my dashboard from IE11.
![screenshot](https://cloud.githubusercontent.com/assets/14927681/26587525/3f6d3302-4518-11e7-8ba7-a09e3f61e629.png)

**Comment by sgiehl** [comment]
I'm able to visit that url without a ssl warning. It shouldn't be anything Piwik is responsible for.
