### ISSUE TITLE
Report export (CSV) row limit does not match the page row limit

### ISSUE THREAD

**Issue by pouyana** [piwik/piwik#11759]
### Version:
Piwik 3.0.4
PHP 7.0.7
### To Reproduce:
* Go to a site statistic
* Actions -> Pages -> Choose at the bottom `rows to display = all` and choose export as `CSV`.
The generated URL is something like this:

https://piwik.org/index.php?module=API&method=Actions.getPageUrls&format=CSV&idSite=3&period=year&date=2017-05-09&flat=1&translateColumnNames=1&language=en&token_auth=anonymous&filter_limit=100

which returns the first hundred not all the records.

`filter_limit=100` should not be here.

**Comment by sgiehl** [comment]
Thanks for the report. This was already fixed with https://github.com/piwik/piwik/pull/11729 and will be included in the next version
