### ISSUE TITLE
log file import not correctly 

### ISSUE THREAD

**Issue by godkillok** [piwik/piwik#11795]
the log format as follow:

192.168.0.250 - - [16/Jun/2017:19:23:49 +0800] "GET /b.gif?action_name=Minutes&idsite=1&rec=1&r=524079&h=19&m=23&s=49&url=http%3A%2F%2F192.168.0.211%2Fstatscv%2Ftmline_mins&id=4ee175f20102e5e8&idts=1497407716&idvc=2&idn=0&refts=1497439385&viewts=1497439385&ref=http%3A%2F%2Fmng.colorv.cn%2Fmng%2F&sendimage=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1600x900&gt_ms=33&pv_id=gvgYkQ HTTP/1.1" 200 35 "http://192.168.0.211/statscv/tmline_mins" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"

I use imort_logs to import it and the result as follow which is not correct
http://192.168.0.211/b.gif?action_name=Minutes&idsite=1&rec=1&r=524079&h=19&m=23&s=49&url=http%3A%2F%2F192.168.0.211%2Fstatscv%2Ftmline_mins&_id=4ee175f20102e5e8&_idts=1497407716&_idvc=2&_idn=0&_refts=1497439385&_viewts=1497439385&_ref=http%3A%2F%2Fmng.colorv.cn%2Fmng%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1600x900&gt_ms=33&pv_id=gvgYkQ

**Comment by mattab** [comment]
what import_logs command did you use? @godkillok

**Comment by sgiehl** [comment]
@godkillok  Do you still have that problem? If so please answer mattab's question. We gonna close this issue soon otherwise
