### ISSUE TITLE
[Bug?] Data at "date range" page 

### ISSUE THREAD

**Issue by ChrisR1993** [piwik/piwik#11798]
@tsteur 
Hi, tsteur, hope you doing well.
I have a question about the "date range".
![piwk](https://user-images.githubusercontent.com/25838575/27214883-a5877712-52a9-11e7-85ec-71801df4c2dc.PNG)
The data report at "date range" shows nothing, though it worked well at period "month" page.
Can you tell me how do fix this?

Thanks

**Comment by mattab** [comment]
please dont create several tickets, this is not useful.

to fix this issue upgrade to Piwik 3

**Comment by ChrisR1993** [comment]
@mattab 
is this a bug?

**Comment by mattab** [comment]
yes
