### ISSUE TITLE
[Question] About archive option

### ISSUE THREAD

**Issue by Viviansweaty** [piwik/piwik#11791]
@mattab 
Hi, mattab. I had a question about the option of archive.
![option pic](https://user-images.githubusercontent.com/26127899/27110890-661d5d30-50e7-11e7-9da8-5d8b97082456.PNG)

so, for now the archiving settings is "No" which means when I check the data in period of "Date range"(e.g.5/1~5/31), there's no data presented at overview page ( but the data will be presented when I goes to period of "Month" May).

My question is if I select the Archiving settings to "Yes", the data period of "Date range" will show up automatically? or something else?

I appreciate your kindly help as always.
Regards,

**Comment by mattab** [comment]
The period "date range" should always be processed even when you select "No" above. Unless you have set in the config.ini.php the following setting to 0:

```

; By default, Piwik will force archiving of range periods from browser requests, even if enable_browser_archiving_triggering
; is set to 0. This can sometimes create too much of a demand on system resources. Setting this option to 0 and
; disabling browser trigger archiving will make sure ranges are not archived on browser request. Since the cron
; archiver does not archive any custom date ranges, you must either disable range (using enabled_periods_API and enabled_periods_UI)
; or make sure the date ranges users' want to see will be processed somehow.
archiving_range_force_on_browser_request = 1
```

**Comment by Viviansweaty** [comment]
@mattab 
I tested 1 and 0 but the result didn't change. 
I just want to make "date range" archive one time at the first time I select it, and second time third time it will show the data automatically. I don't want to archive it every time.
