### ISSUE TITLE
Update from 2.x to 3.x

### ISSUE THREAD

**Issue by AndiLeni** [piwik/piwik#11821]
Hello,

since there is no guide which deals with this topic here is my question:
Is there a built in way to update from 2.x o 3.x without data lost, or do I have to reinstall piwik completely?

Could someone create a guide for this and put it in the "help" section of the website?

**Comment by sgiehl** [comment]
which version of 2.x are you using? Updating from 2.16 or higher to 3.x should work with automatic updater (you may need to adjust the release channel). If you are on an older version of 2.x I would recommend to update to latest 2.x before updating to 3.x.
It should work without any data loss or reinstallation.
