### ISSUE TITLE
Tibet and Taiwan is part of China

### ISSUE THREAD

**Issue by tonsonmiao** [piwik/piwik#11822]
what prevent us to use piwik is that tibet and taiwan is seperate from china in the map,please fix it.

**Comment by sgiehl** [comment]
We are currently not able to change this. Feel free to create a PR for that.

duplicates #10757 / #6006  (#6994 #8557 #11152 #6749 and maybe others)

**Comment by Richard-D** [comment]
Tibet is part of China! NOT an independent country!

**Comment by HaoLovesCoding** [comment]
Tibet is part of China! NOT an independent country!

**Comment by justjavac** [comment]
Tibet is part of China! NOT an independent country!

**Comment by jeenlee** [comment]
Tibet is part of China! NOT an independent country!

**Comment by phodal** [comment]
Tibet is part of China! NOT an independent country!
--

**Comment by huruji** [comment]
Tibet is part of China! NOT an independent country!
