### ISSUE TITLE
Piwik is not sending Email Reports anymore in 2.17.1

### ISSUE THREAD

**Issue by Sobhika2** [piwik/piwik#11835]
Hello,

The email reports we have scheduled inside PIWIK are not sending any emails to the recipients from June 1st 2017. We are currently on version 2.17.1 and there was no recent upgrade or major changes that could have affected the functionality.  The 'Send Report Now' option is not working as well. But, we are allowed to download the report using the Download option.

Is this a big inside piwik? Can anyone please help me on this issue ASAP.

Regards,
Sobhika

**Comment by sgiehl** [comment]
As nothing was change on Piwik side, maybe your server was updated in any way? Or are you using the SMTP settings to send emails? If so maybe your password changed?
For more help, please ask your questions in our forum.

**Comment by Sobhika2** [comment]
Hi,

I can confirm that the server was not updated by any chance. We are not using the SMTP settings as well, And this is not a password issue as we are using Single sign on and the issue exists in our test instance as well.

Regards,
Sobhika

**Comment by Sobhika2** [comment]
By the way, could you please tell me why the issue is closed.

**Comment by sgiehl** [comment]
Maybe the mail server is now blocking those emails. Try to check if the server itself is triggered to send any mails, or try using the SMTP settings, to prove that it really doesn't work.
But as you wrote, that it was working till June, Piwik itself was able to send mail and also did it, right? As the software didn't change, I can't see a reason why it should be a bug in Piwik. Piwik 2.17. is available for a long time now, and we didn't receive any other bug reports regarding unsent mails and it was working on all our instances. 
As Piwik 2.x is almost EOL, we highly recommend to update to Piwik 3.

**Comment by Sobhika2** [comment]
Hi ,

There was one change which was happened just one day before this happened. We had set up a cronjob for auto archiving on May 31st.

Not to defend, but I see similar kind of issues here : 
https://github.com/piwik/piwik/issues/11534
https://github.com/piwik/piwik/issues/8996

Regards

**Comment by sgiehl** [comment]
which command are you executing for the cronjob? `core:archive` normally executes the scheduled tasks. Maybe that isn't done in your case. Do you have the output of a cron?

**Comment by Sobhika2** [comment]
@sgiehl ,

I could fix this issue in our test instance by setting up a secure mail relay through SMTP. We are using port as 25 and method as 'TLS'. But, unfortunately with the same settings,  the email reports are throwing an error ' Unable to connect via TLS' in PIWIK production instance.

Could you please help me find out what is the issue here.

![tls error](https://user-images.githubusercontent.com/26790315/29916020-288d6ada-8e5b-11e7-84be-b1918486ecf1.png)

**Comment by sgiehl** [comment]
Sorry, I'm not very familiar with setting up SMTP. Did you try to connect to the SMTP using TLS with any other tool?
