### ISSUE TITLE
Can piwik speed up the GET request and response

### ISSUE THREAD

**Issue by triffic-tang** [piwik/piwik#11832]
As picture below shows:

![piwik](https://user-images.githubusercontent.com/2368001/27723996-45029742-5da2-11e7-8283-f89751642d61.png)

It takes `176ms` to send get request and get response, can piwik speed up the request?

**Comment by sgiehl** [comment]
This request stores the given data in the database, so it simply takes some time to do so. But as it is no blocking request it shouldn't be important.
Nevertheless there is a possibility to speed up this request a lot. But this requires redis and https://plugins.piwik.org/QueuedTracking
