### ISSUE TITLE
System check mod_pagespeed explain what breaks when it's enabled

### ISSUE THREAD

**Issue by MackieeE** [piwik/piwik#11845]
Good afternoon!

I have searched a little into this - couldn't find any similar issue page for the same terminology I attempted to find with. I'm sure it has been reported before somewhere, please reference the duplicated page if there is. 

When I open the "**Pages**" Subcategory under "**Actions**" and Open a Breakdown of the Sub-pages of visitor behaviour, I am presented with an littered text display of:

![image](https://user-images.githubusercontent.com/883702/27863565-9d3f743c-6182-11e7-8d33-e1a54456263b.png)

Things I've checked:

- No Missing/404 Resources or CSS File referenced in Developer Tools
- Attempted to open this in various Browsers; all displayed the same formatting.

My Setup:

- Google Chrome v60.0 (Beta Branch)
- Windows 7
- *Proudly!* Piwik Version 3.0.4

**Comment by mattab** [comment]
Hi @MackieeE 
Thanks for the report. It definitely looks like a bug we need to address. 

1) Can you reproduce this issue on the https://demo.piwik.org ?
2) could you send us via http://piwik.org/contact/ your PIwik URL and temporary Username/pasword so we can see this issue?

**Comment by MackieeE** [comment]
1. It's not re-producible on the Demo-site. I can see that it does continue breakdown to the next level via another collapsible tooltip. 

2. Sent Email! :)

**Comment by mattab** [comment]
@sgiehl Would be great if you could take a look at this one

**Comment by sgiehl** [comment]
Issue was caused by mod_pagespeed . 

@mattab  We should maybe add a FAQ item that Piwik might not work correctly if mod_pagespeed is activated or even add a system check for that. thoughts?

**Comment by mattab** [comment]
@sgiehl 
we already have this system check https://github.com/piwik/piwik/blob/3.x-dev/plugins/Diagnostics/Diagnostic/PageSpeedCheck.php#L25-24

Is this diagnostic correctly triggering a warning?

**Comment by MackieeE** [comment]
The system check _does_ warn of the PageSpeed module being enabled, which I admittedly didn't check. So user error :)

![pagespeeddisabled](https://user-images.githubusercontent.com/883702/28059583-9821d6e0-661c-11e7-8d57-6c4f49c62f0f.jpg)

I would suggest on expanding on the various(?) front-end issues that `mod_pagespeed` has on the Admin pages of Piwik. Anything to add for future google searches! But understandably it doesn't sound like this has happended very often so I open this ticket will be suffice.

Thanks to you both for your awesome support & product :)

MackieeE

**Comment by mattab** [comment]
Good idea, we'll improve the label and make it more clear what problems it causes.

Btw, did you notice any other problems besides that one reported here?

**Comment by mattab** [comment]
from email:
```

However, with the help of the query string tests that ModPageSpeed offer:

https://modpagespeed.com/doc/experiment#ModPagespeed

By appending &PageSpeed=off to the URL, it worked perfectly with Page-speed disabled:
```

So maybe one solution could also be to automatically append this parameter to index.php requests, when we detect mod_pagespeed is enabled?

**Comment by MackieeE** [comment]
I have noticed one more action, however I'm not sure it's PageSpeed related, as even turning it off via the Query string has no effect (Maybe because it's a seperate web request). See below for example:

When clicking the "Open Row Evolution" under Browsers, for Chrome specifically:

![image](https://user-images.githubusercontent.com/883702/28260005-05773fc4-6ad1-11e7-8b76-04b731d55ffa.png)

The resulting modal spills out:

![seeexample](https://user-images.githubusercontent.com/883702/28260094-647bebbe-6ad1-11e7-888b-bdcad2323949.jpg)
,

**Comment by sgiehl** [comment]
Yes, that seems to be mod page_speed as well. We should keep on suggesting to turn it off.

@mattab Should anything be done here?

**Comment by mattab** [comment]
@sgiehl Yes let's just add a message that makes the failed system check more prominent. For example "[...] cause several issues in Piwik such as: broken Pages reports, broken Row Evolution, and other issues hard to troubleshoot. Please disable mod_pagespeed on this server."
