### ISSUE TITLE
Tibet is part of China! NOT an independent country!

### ISSUE THREAD

**Issue by kchanlee** [piwik/piwik#11840]
Here is a screenshot of dashboard from our self-hosted Piwik:
![snipaste_20170705_120421](https://user-images.githubusercontent.com/2238607/27848754-3747574c-617a-11e7-9f2f-c9d406376147.png)

**Comment by sgiehl** [comment]
Next time please do a search before opening an issue!
duplicates #10757 / #6006 (#6994 #8557 #11152 #6749 #11822 and maybe others)
