### ISSUE TITLE
Error in Piwik: Metric has two different documentations

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11847]
Got this error in demo2 several times and it would be good to understand where it comes from and fix:

`mod_fcgid: stderr: Error in Piwik: Metric T\xe1\xbb\xb7 l\xe1\xbb\x87 tho\xc3\xa1t (H\xc3\xa0nh vi) has two different documentations: (1) T\xe1\xbb\xb7 l\xe1\xbb\x87 truy c\xe1\xba\xadp m\xc3\xa0 \xc4\x91\xc3\xa3 b\xe1\xba\xaft \xc4\x91\xe1\xba\xa7u tr\xc3\xaan trang n\xc3\xa0y v\xc3\xa0 r\xe1\xbb\x9di kh\xe1\xbb\x8fi trang web ngay l\xe1\xba\xadp t\xe1\xbb\xa9c. (2) T\xe1\xbb\xb7 l\xe1\xbb\x87 truy c\xe1\xba\xadp \xc4\x91\xc3\xa3 r\xe1\xbb\x9di kh\xe1\xbb\x8fi trang web sau khi xem trang n\xc3\xa0y.`

**Comment by sgiehl** [comment]
Guess it helps to have that decoded
`mod_fcgid: stderr: Error in Piwik: Metric Tỷ lệ thoát (Hành vi) has two different documentations: (1) Tỷ lệ truy cập mà đã bắt đầu trên trang này và rời khỏi trang web ngay lập tức. (2) Tỷ lệ truy cập đã rời khỏi trang web sau khi xem trang này.`

**Comment by sgiehl** [comment]
The reason are incorrect translations. The translation `Tỷ lệ thoát` is used for `General_ColumnBounceRate` and for `General_ColumnExitRate`. I'll remove one of them on transifex, so it should be fixed in the next version.

Note: (1) is `General_ColumnPageBounceRateDocumentation`, (2) is `General_ColumnExitRateDocumentation`

**Comment by mattab** [comment]
Would it be possible to add a test case to Pro actively detect this, or
some automatic cleanup of language file?

**Comment by sgiehl** [comment]
We could maybe extend the import script to filter duplicate ColumnNames

**Comment by mattab** [comment]
@sgiehl OK: would be good to prevent this error in the future automatically
