### ISSUE TITLE
In Tracking code page, clarify that at least two domains need to be set in the Websites before one can enable "Enable cross domain tracking" feature

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11866]
from feedback:

> In site setup, I originally only entered one domain.
> Because of this, the "enable cross domain tracking" was grey/disabled. I could not enable it.
> Well, it turns out that its disabled until I enter a 2nd domain to track. It should have told me that instead of just being disabled.

We could show a little text next to the checkbox to clarify this, eg. `To use Cross Domain tracking, you must specify at least two domain names in your Website.` or better

**Comment by spacenate** [comment]
I love helpful messaging 👍 PR submitted
