### ISSUE TITLE
Add gitignore file

### ISSUE THREAD

**Issue by gemal** [piwik/piwik#11860]
I just installed piwik and it seems that there are not any .gitignore file so a lot of files shows up as modified

I think you should add a few files to gitignore like
config/config.ini.php

perhaps also the plugins folder?

**Comment by Findus23** [comment]
Hi, how did you install piwik?
Have you installed it from this repository? Then there should be [one](https://github.com/piwik/piwik/blob/3.x-dev/.gitignore). But I wouldn't recommend you to use it as you would need to also get the submodules and [other components](https://piwik.org/faq/how-to-install/faq_18271/).

If you have installed the zip from [piwik.org/download/](https://piwik.org/download/) you shouldn't need a .gitignore file. But if you have an exceptional setup (all webapps in an git repository) you can use [this .gitignore](https://github.com/piwik/piwik/blob/3.x-dev/.gitignore) file.

**Comment by sgiehl** [comment]
As @Findus23 mentioned. There are `.gitignore` files. But those are [removed for git archives](https://github.com/piwik/piwik/blob/3.x-dev/.gitattributes#L52).
