### ISSUE TITLE
3.0.2 top_controls not displaying for regular users

### ISSUE THREAD

**Issue by Xeevis** [piwik/piwik#11872]
I've installed recently updated Piwik 3.0.2 from Synology package center. Everything works great except for top controls where search/dashboard etc are located. They simply don't get revealed for regular users, if I promote user to super user they do start showing.

I've tried Edge, Chromium, Firefox, different machine, nothing helped, also no errors in console beside jQuery warning on Synchronous XMLHttpRequest.

For super users I can see div being styled

    <div class="top_controls" style="visibility: visible; opacity: 1;">

Regular users are left out

    <div class="top_controls">

Restoring styles manually on this div restores controls which appear to be otherwise fully functional.

![Issue](https://i.imgur.com/eUiKR7n.png)

Test server
======
```
Server: https://piwik.jadex.eu/piwik
Username: test
Password: Test123!
```

**Comment by sgiehl** [comment]
I could find why it's not shown, but I don't know the reason. 
The problem is, that none of [those lines](https://github.com/piwik/piwik/blob/3.x-dev/plugins/CoreHome/templates/_headerMessage.twig#L19-L32) are rendered. That should be possible to happen. Maybe check if the file has the same content on your installation or try clearing the tmp directory of Piwik.

**Comment by Xeevis** [comment]
@sgiehl Nailed it, that file was quite different, probably modified by Synology to prevent users from running updater and they inadvertently killed controls for users while doing so. I've restored the file and updated to latest 3.0.4, all good! 👍

**Comment by mattab** [comment]
Synology should not be allowed to do this. Do you know how we could contact them about this? @Xeevis

**Comment by Xeevis** [comment]
[Here is a diff](https://www.diffchecker.com/W69YkoMm) of the two files  🤦‍♂️ 

Corporations like this require you to go through super forms I'm afraid https://www.synology.com/en-us/company/contact_us

Attachment: [_headerMessage.zip](https://github.com/piwik/piwik/files/1168968/_headerMessage.zip)
