### ISSUE TITLE
How long can a new user develop a login plugin with openid?

### ISSUE THREAD

**Issue by wei1215583760** [piwik/piwik#11880]
Hey, i am new using piwik, and i am amazed with the application. In addtion, I want integrate it with openid to login, do you know how much time it will cost to develop a new plugin? And can you give some advice?
thank you so much !

**Comment by sgiehl** [comment]
Hey @wei1215583760 Please have a look at our forum (https://forum.piwik.org/) and ask for help there. 
Additionally you may have a look at our developer guide (https://developer.piwik.org/develop).
