### ISSUE TITLE
File integrity check on vanilla install telling me to delete plugins/Morpheus/icons/submodules

### ISSUE THREAD

**Issue by suprko** [piwik/piwik#11935]
Downloaded Piwik direct from the website and installed, didn't change anything, and the file integrity check is giving me this error!

> Directories were found in your Piwik but we didn't expect them.
> --> Please delete these directories to prevent errors. <--
> 
> Directory to delete: plugins/Morpheus/icons/submodules
> 
> 
> To delete all these directories at once, you can run this command:
> rm -Rf /var/www/html/piwik/plugins/Morpheus/icons/submodules

It's just a warning, rather than an error, so I just contiued with installation...? But a brand-new install shouldn't be throwing warnings like this, no?

**Comment by Findus23** [comment]
Hi, 

You can ignore this message. I made mistake in the build process, which was already fixed and will be included in the next piwik release 

 piwik/piwik#11383
