### ISSUE TITLE
New Metric: Time between Visits

### ISSUE THREAD

**Issue by mstenz** [piwik/piwik#11944]
Hi, 
it would be good to have not only "Duration of a Visit" but also the "Time between visits of a Returning Visitor". 
This also make the way free for reports like "Average time between Visits".

**Comment by mattab** [comment]
To get "Time between visits of returning visitors", create a segment "Returning visitors" then look at Visitors > Engagement, where you'll find the "Days since last visits" report segmented to view only returning visitors.
