### ISSUE TITLE
Freedom has bottom line , Please do not put personal opinions into formal products

### ISSUE THREAD

**Issue by WG-Com** [piwik/piwik#11940]
please use the UN world map , tibet is your Serious fault : 

http://www.un.org/Depts/Cartographic/map/profile/world.pdf

**Don't complain about Chinese people， not our fault , you are **

**Comment by sgiehl** [comment]
@WG-Com if #11930 isn't enough for you, feel free to raise your hands as volunteer for #11929 
And next time please use the search first and comment existing issues before creating a new one.

**Comment by WG-Com** [comment]
so  you have fault many years , now blame me ?

**Comment by WG-Com** [comment]
so this is your attitude when this happen, boring until today

**Comment by WG-Com** [comment]
that is why i am here everyday , because of you , you know ?

**Comment by WG-Com** [comment]
that map still there , why don't block that map component first ?

**Comment by phodal** [comment]
@WG-Com please clam down, everything was in progress.

**Comment by WG-Com** [comment]
@phodal 你知道我们中国企业在出事后的态度，到今天了 地图可能确实不好立刻处理，但是可以先把 地图组件屏蔽吗？ 这是态度问题，从一开始他们就不耐烦

**Comment by WG-Com** [comment]
根本就没有基本的尊重

**Comment by YouYue123** [comment]
@WG-Com Calm down first. They are already working on this or you can also create a pull request for this
