### ISSUE TITLE
Unable to use Session Recording Feature

### ISSUE THREAD

**Issue by poksay** [piwik/piwik#11956]
Looking for assistance getting the session recording up and running. 

Note: our ssl cert is signed by CA, not self-signed

GOing to the url manually gives us:
Piwik.HeatmapSessionRecording.configuration.assign({"heatmaps":[],"sessions":[{"id":2,"sample_rate":"100.0","min_time":0,"activity":true,"keystrokes":true}],"idsite":1,"trackerid":"5lX6EM"});

Message from system check below:
--- 
Requesting 'https://xxxxxxxxxxx.com/analytics/plugins/HeatmapSessionRecording/configs.php?idsite=1&trackerid=5lX6EM&url=http%3A%2F%2Ftest.test%2F' resulted in an SSL error. Maybe you are using a self signed certificate? Please open the URL manually in a browser to see if the response contains 'Piwik.HeatmapSessionRecording'. If not, you might need to modify your server configuration as this file needs to be accessible via a browser from the Internet or Intranet.

**Comment by tsteur** [comment]
The system check can be ignored in this case, the response looks all good. It looks like Piwik was not able to ping your website. Maybe openssl is missing or too old or so. 

If it still doesn't work for you feel free to get in touch via contact@innocraft.com
