### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by netsmartzrahul** [piwik/piwik#11955]
Hi,

I really don't find it useful and piwik is been charging for me from a long time. Can anyone tell me how to discontinue my account with piwik.

Thanks

**Comment by Findus23** [comment]
I doubt that you are being charged by the Open Source Project.
Either you have bought an premium plugin in the marketplace: https://plugins.piwik.org/premium
Or you are using the innoCraft Cloud. Then you'll need to contact [them directly](https://www.innocraft.cloud/#contact).

Or you are customer of [Piwik Pro](https://piwik.pro/), then you should look at [this FAQ entry](https://piwik.org/faq/new-to-piwik/faq_21984/) as this company is completly independent of the piwik project.
