### ISSUE TITLE
Piwik is breaking title if #-symbol is used

### ISSUE THREAD

**Issue by hossmannitconsulting** [piwik/piwik#11951]
Piwik do not track the Page Title in Outgoing References correctly if iam using a #-symbol in the page title. The url encoding in the piwik request is correctly. But piwik proceed the encoded %23 (#) incorrect. iam Using a old piwik version 1.11.1. How can i fix this issue? For me, at the moment it is not possible to change to a another piwik version.

piwik.php?link=http%3A%2F%2F_mediathek%2FStartseite%2FNews%20Center%2FBranchen%20News%2F %23Video%20zuerst%2FVideo%20in%20einer%20Nerws&idsite=...

**Comment by mattab** [comment]
please upgrade to latest version of Piwik 3 where this error is fixed
