### ISSUE TITLE
Hidden img src on external links is beeing copied

### ISSUE THREAD

**Issue by stibay** [piwik/piwik#11950]
Piwik 3.0.4
I have a link on my page with a link to an external site.

```
<a ng-href="http://someSite/?ref={{i[x.someField]}}" target="_blank">{{i[x.someField]}}</a>
```

The problem is I am getting lots of extra stuff when I copy this link by either dragging from the start or the end of the text.

`<p><img src="//myPiwikSite/piwik.php?idsite=1&rec=1" style="border:0;" alt="" /></p>  `
ActualLinkTextHere

Is there a way to prevent this?

**Comment by mattab** [comment]
Hi @stibay 

> when I copy this link by either dragging from the start or the end of the text.

Sorry I don't understand this issue. Could you again explain what you get VS what you expect to get?

**Comment by stibay** [comment]
I am not managing this installation anymore, but the expected result would be just copying the text, not the piwik markup that seems to be hidden around the link.

**Comment by mattab** [comment]
Probably this is caused by the <noscript> tag which we have removed a while ago, so this shouldn't be an issue with the new tag
