### ISSUE TITLE
Unable to track JS error

### ISSUE THREAD

**Issue by wei1215583760** [piwik/piwik#11957]
I have added _paq.push(['enableJSErrorTracking']) in my tracking code, and i add some js error in my website as well. However, i cannot receive any error's information in my piwik action=>event module. Do you know where the problem might it be?

Other modules work well,  and i can receive new visitors' information except js errors.

**Comment by sgiehl** [comment]
Did you try to manually create a JS error in order to check if they aren't tracked?
Please note, that only errors will be tracked after Piwik is initialized and `_paq.push(['enableJSErrorTracking'])` was called.
