### ISSUE TITLE
How to make the following effect？

### ISSUE THREAD

**Issue by wei1215583760** [piwik/piwik#11964]
![a538aef5fa81434c8bbdca3ac92a8f33](https://user-images.githubusercontent.com/11715783/29404115-d102e14e-836c-11e7-8f53-ba971d0ac826.png)
![62ef00dd8728ff4aa78e198939c19733](https://user-images.githubusercontent.com/11715783/29404165-f3f5b2c6-836c-11e7-9331-565fadc8056f.png)

I want to add my report with the effect that we can control when to expand the url. How can I make it? Thanks a lot if you can help me

**Comment by sgiehl** [comment]
This "effect" is available for action tables. Have a look at the Actions plugin and the reports generated there.
