### ISSUE TITLE
Notice; core/DataTable/Renderer/Html.php(121): Notice - Array to string conversion

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11963]
Got this notice on demo.piwik.org after upgrading to 3.0.5-b2 ([this URL](https://demo.piwik.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=34#?idSite=34&period=week&date=2017-08-10&category=General_Visitors&subcategory=Live_VisitorLog&popover=)):
`WARNING: /www/demo.piwik.org/core/DataTable/Renderer/Html.php(121): Notice - Array to string conversion - Piwik 3.0.5-b2 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)`

**Comment by sgiehl** [comment]
Similar problem as with the Console Renderer #11884 
The Metadata contains an array of processed metrics, which can't be converted to string
