### ISSUE TITLE
Yandex, SearchLock, Ecosia URLs without keyword not recognized as SE

### ISSUE THREAD

**Issue by endrepalinkas** [piwik/piwik#11975]
https://yandex.ru/ and https://www.yandex.ru/ as the referrer - without any keyword in URL - not recognized as Yandex SE traffic by Piwik

https://results.searchlock.com/ -  without any keyword in URL - not recognized as SearchLock SE traffic by Piwik

https://www.ecosia.org/ -  without any keyword in URL - not recognized as Ecosia SE traffic by Piwik

**Comment by sgiehl** [comment]
Thanks for the report. Will fix those now.

Btw: would be more correct to report it in https://github.com/piwik/searchengine-and-social-list

**Comment by endrepalinkas** [comment]
Thank you. Will keep it in mind in the future!
