### ISSUE TITLE
Undefined index: always_load_commands_from_plugin

### ISSUE THREAD

**Issue by gfernandez83** [piwik/piwik#11987]
root@app1:/srv/http/piwik/piwik# ./console plugin:list
WARNING [2017-08-30 03:51:53] /srv/http/piwik/piwik/core/Console.php(222): Notice - Undefined index: always_load_commands_from_plugin - Piwik 3.0.4 - Please report this message in the Piwik forums: http://forum.piwik.org

**Comment by sgiehl** [comment]
could you please check if your version of `config/global.ini.php` contains [this lines](https://github.com/piwik/piwik/blob/master/config/global.ini.php#L567-L568)?
If not, please update the file from the latest release...

**Comment by gfernandez83** [comment]
there's none. I copied from the old version. thanks.
