### ISSUE TITLE
When are the stats updated?

### ISSUE THREAD

**Issue by Bryze** [piwik/piwik#11984]
I am not able to find an answer to this question. The `Visitors in Real Time` are updated instantly, but the rest of the logs and stats took me almost 2-3 hours to update. 

Few questions
Can anyone explain what could be the reason? 
Or is there any specific time when the update requests are sent?
If there is a specific time, is it configurable from our end?

**Comment by sgiehl** [comment]
This depends on your settings. I've you have set up a cron job to archive the data, the reports will update after the job ran. If you use browser archiving, the archiving process should be triggered when you view the reports (but only every 2,5h, if you didn't change the config value for `time_before_today_archive_considered_outdated`)
