### ISSUE TITLE
I cannot track the downloads inside a segment (Piwik 3.0.4)

### ISSUE THREAD

**Issue by mpocceschi** [piwik/piwik#11992]
Hi everyone,
I have created a segment on Piwik to analyze a subset of pages in a site.
Here's the condition I set:
_**"URL page"**_ + _**"Contains"**_ + << _**URL**_ (Partial)>>
Now, when the segment is active, Piwik does not return the number of downloads made (the rest of the values seem correct).
If I run the analysis for _**"All visit (default)"**_, the values of the downloads reappear.
I also tried to force the click logging using the css _**'piwik_download'**_ class, but without result.
This problem occurs both for dashboards and for reports.
I hope to have been useful and to have explained to you correctly.
Thank you

**Comment by GitFr33** [comment]
This sounds like it might be related to #11900 [comment-327014778](https://github.com/piwik/piwik/issues/11900#issuecomment-327014778)

Do your downloads show up in the visitor log and real-time visitor log when a segment is used?

Do you have other events tracked that are, or are not, showing up when a segment is used?

**Comment by mpocceschi** [comment]
Hi GitFr33,
I've done more tests and I can tell you that downloads are shown both when I view the visitor logs and when I see the real-time visitor log (with the segment active or not). 
It's just the download widget that is left blank.
I turned your Cron Job question to the colleague who installed Piwik and this was his answer:
"Yes, we use them and in particular: 
_\* / 30 * * * * root / opt / piwik / php / bin / php / opt / piwik / apps / piwik / htdocs / console core: archive --url = http: / ... "_
I hope this answer will be helpful to you.
Thank you

**Comment by mattab** [comment]
Marking as duplicate of https://github.com/piwik/piwik/issues/11900#issuecomment-330796179

@mpocceschi @GitFr33 feel free to comment in that other issue

**Comment by mattab** [comment]
This should be fixed in Matomo 3.12.0 which will be released tomorrow - if you still experience this issue then, let us know.
