### ISSUE TITLE
Site Migration Issue

### ISSUE THREAD

**Issue by Sobhika2** [piwik/piwik#12006]
Hi,

We are trying to migrate sites from one Piwik instance to another( source db from windows server and target db in linux environment ) using the Site Migration plugin. We could find some mismatch in the data after migration. Please find the details below:

DB name : sourcedb and targetdb  in mysql 
we are using : site migration plugin 
we have activated the site migration plugin in windows and ran the below command for site migration : 

 php ./console migration:site 1 --db-prefix piwik_ --db-username arun  --db-password  xxxxxxx  --db-name target
destination database host : localhost 
start tranasaction
migrating site config
loading existing actions
migrating log data -visits
migrating log data - link visit action
migrating log data - conversions and conversion items
migrating archive data
commit transaction .

the above command was migrated the from source db site id  : 1  to  siteid : 50 to our target db. In end of the  migration we are getting commit transaction line.
(ending without any error ) .

But only piwik_site and piwik_archive_x and numeric table data were get populated into tragetdb from sourcedb..  

DAta are not populated in the below tables .. 

piwik_log_visit
piwik_log_action
Piwik_log_link_visit_action

Can anyone please let me know what is the issue here.

Regards

**Comment by mattab** [comment]
Hi @Sobhika2 

Surprising, the last times we used the plugin it was correctly migrating the log_* tables data. Please create the issue in the project repo here: https://github.com/PiwikPRO/plugin-SiteMigration/issues/

**Comment by mattab** [comment]
FYI we have released a new plugin which lets you migrate one website from one Matomo instance to another. Get it for free at http://plugins.matomo.org/Migration

**Comment by shubhangi1995** [comment]
hi @mattab 
is there a way we can migrate visitor logs and reports from one instance to another instance of piwik.

**Comment by tsteur** [comment]
See previous comment.
