### ISSUE TITLE
3.1.0 RC1: problems with some characters

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#12000]
![2017-09-05_09h37_07](https://user-images.githubusercontent.com/5681880/30050368-84ef8684-921e-11e7-8d02-33b1c50c1b69.png)

**Comment by mattab** [comment]
Thanks for the report @hpvd we will investigate

**Comment by sgiehl** [comment]
@hpvd  I'm not able to reproduce that locally. Are those umlauts only broken for new visits after the update, or are they shown incorrect for old visits as well?

**Comment by hpvd** [comment]
@sgiehl thanks for your work on this.

Some more details:
It's not only german umlauts: just have a look at the left red mark in the screenshot above (from visitor profile) the character right after "Generated a Life Time Revenue of" maybe it's the "Euro" sign?

German umlauts are fine in visitorlog, but broken in visitor profile.

It's also broken for older entries in visitor profile (before update).

Happens at least in events but also in url titles...

**Comment by sgiehl** [comment]
I'm not able to reproduce that here nor on piwik demo. 
Did you try to clean tmp directory of Piwik? How did you perform the update - auto update or manually upload?
Do you maybe have another system locale than English on the server running Piwik?

**Comment by hpvd** [comment]
I used auto update. cleaning doesn't help.

Switched user language from english to german and the problem is even more visible - but only in visitor profile...

![2017-09-07_23h09_10](https://user-images.githubusercontent.com/5681880/30185608-75e2ef90-9422-11e7-937a-1d24c3328e0a.png)

**Comment by hpvd** [comment]
just found system check brings up: "File integrity check failed and reported some errors. You should fix this issue and then refresh this page until it shows no error."

will clean this tomorrow.

**Comment by hpvd** [comment]
hmm cleaning these files doesn't help.

**Comment by sgiehl** [comment]
I'm not able to reproduce that even with german language. 
Are the encoding problems the same when you add the visitor profile as dashboard widget?

**Comment by hpvd** [comment]
@sgiehl 
yes it's the same in dashboard.
But giving this a try I managed to find place were its fine in visitor profile (standard and in dashboard)
please see attachment. Hopes this gives a good hint..

![2017-09-10_23h17_40](https://user-images.githubusercontent.com/5681880/30253097-aa8a199a-967e-11e7-95fb-23003e16837e.png)

**Comment by hpvd** [comment]
just to complete information: still there with 3.1.0 final

**Comment by sgiehl** [comment]
@hpvd could you give some detailed information on the server running Piwik? like OS, php version, mysql version, system local,... also do you have any third party plugins installed?

**Comment by hpvd** [comment]
![2017-09-13_19h08_06](https://user-images.githubusercontent.com/5681880/30390656-22ef0898-98b7-11e7-8abd-c8af1f646b5b.png)

**Comment by hpvd** [comment]
uuuh. you were right. when deactivating all 3rd party plugins the problem has gone.
Sorry couldn't imagine that a third party plugin could do this.
Will figure out now which one was responsible...

**Comment by hpvd** [comment]
aarrr, it's aom, the one also advertised in piwiks blog today...

**Comment by hpvd** [comment]
sorry once again.

**Comment by sgiehl** [comment]
Guess it's the way they manipulate the visitor profile

**Comment by hpvd** [comment]
would there be a better way with the possibilities introduced in https://github.com/piwik/piwik/issues/6111 ?

**Comment by sgiehl** [comment]
not sure if exactly that is possible, as I didn't have a closer look. If not we could consider to make the profile even more extendable

**Comment by hpvd** [comment]
thankyou.

**Comment by mattab** [comment]
fyi: I've contacted AOM author and they should check the plugin for compatibility over the next days and release a new version. Feel free to create an issue in their repository as well

**Comment by hpvd** [comment]
thankyou! I already did that... maybe you missed the reference shown above.
(but there was no response yet, so thanks again!)
