### ISSUE TITLE
Widgetized dashboards

### ISSUE THREAD

**Issue by vincent3569** [piwik/piwik#12014]
hi all
as told on piwik forum, I have 2 issues on my piwik installation (https://forum.piwik.org/t/widgetized-dashboards/25405):

on my piwik server I have 2 different dashboards (full and simple).
I tried to widgetize simple dashboard on my website.

First issue : I am unable to widgetize only one of my dashboard and I can only see full dashboard and 2 links to full and simple dashboards.
The link is as following: https://piwik.my_domain_name.fr/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=2&period=week&date=yesterday

Second issue : the links I can see with the widgetized  dashboards are wrong (or ineffiscient).
there is a javascript link (as following):
```javascript:$(’#dashboardWidgetsArea’).dashboard(‘loadDashboard’, 3);```
but I can’t access to the dashboard with this id=3 (my simple dashboard).

**Comment by mattab** [comment]
Hi @vincent3569 

> First issue : I am unable to widgetize only one of my dashboard and I can only see full dashboard and 2 links to full and simple dashboards.

Could you send more details, is there any error, or what makes you unable to widgetise the dashboard?

**Comment by vincent3569** [comment]
hi @mattab 
I have 2 dashboards, and i want to widgetize only one (or access to the dashboard that I want first), but I can't.
maybe it's not an issue but for me it is not working as i wish.

and with the 2nd issue, I can't really not access to my 2nd dashboard that i want to widgetize (more simple that the 1st one).

**Comment by mattab** [comment]
It's not possible to widgetise only one, all dashboard will be visible.

A solution: you can create a new user in Piwik who has only one dashboard, and use this new user's `token_auth`

**Comment by vincent3569** [comment]
OK, I did that and it works fine. thanks.
