### ISSUE TITLE
Error code : Failed to get data from API: Merci de sp&eacute;cifier une valeur pour idSite

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#12027]
When I try to view my stats, I have this message : 
ERROR: Failed to get data from API: Merci de sp&eacute;cifier une valeur pour idSite #0 /var/www/piwik/core/API/Proxy.php(162): Piwik\API\Proxy-&gt;getRequestParametersArray(Array, Array) #1 /var/www/piwik/core/Plugin/Visualization.php(264): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #2 /var/www/piwik/core/Plugin/Visualization.php(181): Piwik\Plugin\Visualization-&gt;loadDataTableFromAPI() #3 /var/www/piwik/core/Plugin/Controller.php(249): Piwik\Plugin\Visualization-&gt;render() #4 /var/www/piwik/plugins/MultiSites/Controller.php(118): Piwik\Plugin\Controller-&gt;renderView(Object(Piwik\Plugins\CoreVisualizations\Visualizations\JqplotGraph\Evolution)) #5 [internal function]: Piwik\Plugins\MultiSites\Controller-&gt;getEvolutionGraph() #6 /var/www/piwik/core/FrontController.php(544): call_user_func_array(Array, Array) #7 /var/www/piwik/core/FrontController.php(137): Piwik\FrontController-&gt;doDispatch('MultiSites', 'getEvolutionGra...', Array) #8 /var/www/piwik/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #9 /var/www/piwik/index.php(27): require_once('/var/www/piwik/...') #10 {main}

And Piwik don't want to get new visitors who came in my website

**Comment by Findus23** [comment]
What URL are you using?
The error message seems to translate to `Please specify a value for "idSite"`
So can you make sure you are specifying the `idSite` GET parameter?

**Comment by lanargeek** [comment]
Panel of piwik, of all websites
Yes, I make it and it doesn't work

(sorry for my poor english, I'm french)

**Comment by sgiehl** [comment]
Can you copy/paste the full querystring of the url where the error occurs for you?

**Comment by sgiehl** [comment]
@lanargeek can you provide the full url? Otherwise we won't be able to help or reproduce and likely close this issue.

**Comment by sgiehl** [comment]
As the user isn't on github anymore we likely won't get any feedback. Closing now
