### ISSUE TITLE
3.1.0 - Error 500 when getVisitorProfilePopup

### ISSUE THREAD

**Issue by GuillaumeG22** [piwik/piwik#12028]
Hi,

When I open the popup for get visitor profile, I get an error 500 and  : 

> The following error just broke Piwik (v3.1.0):
> 
> Key "totalGoalConversions" for array with keys "visitorId, totalVisits, totalVisitDuration, totalActions, totalOutlinks, totalDownloads, totalSearches, totalPageViews, totalUniquePageViews, totalRevisitedPages, totalPageViewsWithTiming, searches, totalEvents, hasLatLong, lastVisits, nextVisitorId, previousVisitorId, totalVisitDurationPretty, userId, firstVisit, lastVisit, visitsAggregated, visitedPages, averagePageGenerationTime, devices, continents, countries" does not exist.
> in
> /.../www/plugins/Live/templates/_profileSummary.twig line 19

I have already restart my webserver (Apache & PHP7 FPM).

**Comment by sgiehl** [comment]
Do you have the goals plugin disabled?

**Comment by GuillaumeG22** [comment]
No, it's disabled;

When I activate it, it works.

**Comment by sgiehl** [comment]
Thanks for letting me know. Will add a fix for this

**Comment by sschueller** [comment]
Is it possible this error is back? I am getting this in my current version (Matomo-Version: 5.0.2) with Goals disabled and opening "getVisitorProfilePopup".

```
Error in Matomo: The plugin Goals is not enabled. You can activate the plugin on Settings &gt; Plugins page in Matomo., referer: https://xxxxxxxxx/index.php?module=CoreHome&action=index&idSite=122&period=day&date=yesterday
"POST /index.php?date=yesterday&module=Live&action=getVisitorProfilePopup&visitorId=0e49e31d0fa4ef4b&idSite=122&period=day HTTP/1.0" 500 645 "https://xxxxxxxxxx/index.php?module=CoreHome&action=index&idSite=122&period=day&date=yesterday" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0"
```

**Comment by michalkleiner** [comment]
Hi @sschueller, if you think there might be a regression with the same error, please open a new bug report linking this issue to it rather than commenting here as we don't usually action on closed issues. Thank you.
