### ISSUE TITLE
Cannot login to Piwik no matter what I do. Password reset not working either

### ISSUE THREAD

**Issue by nicktrout** [piwik/piwik#12026]
I have been unable to login to my piwik for several days. Tried the password reset link several times but it still says invalid username/password. I can see the login and hashed pw in DB via phpmyadmin. I have tried to manually reset the pw there using:
php -r 'echo password_hash(md5("changeMe"), PASSWORD_DEFAULT) . "\n";'
then updating the relevant record in the users table. 
I am at my wits end with this. I haven't upgraded or updated anything. One minute it was working and now it refuses to let me in. What can I do?

**Comment by jsargent7089** [comment]
You could try removing it and do a reinstall of piwik

**Comment by nicktrout** [comment]
Got it figured out--thanks! I (re)installed to 3.1.0. Now I can log in.
