### ISSUE TITLE
The visit counter displays incorrect values after more than 100 visits

### ISSUE THREAD

**Issue by sesom42** [piwik/piwik#12034]
Visitors with more than 100 visits will only be shown with 100 visits. Scrolling further down you can see that the visit counter becomes negative.

![screenshot-piwik-2017-09-12-11-13-35](https://user-images.githubusercontent.com/8649051/30318340-224c7a48-97ad-11e7-9b24-520b4ce12394.png)

Piwik 3.1.0

**Comment by sgiehl** [comment]
Actually it shouldn't be possible to view more than 100 visits in the profile. Gonna fix that...

**Comment by sesom42** [comment]
Thank you. The Quickfix only fixes that no more than 101 entries are displayed. Nevertheless, the counters of visits are wrong. When opening the details, the top visit is always marked with # 100 although it can be much higher. At the end of the list, # 1 is always displayed twice, as shown in the above screenshot.

**Comment by sgiehl** [comment]
you shouldn't be able to load more visits after Visit 1 is displayed. so for a visitor with more than 100 visits it should display from 100 to 1. 
All the details in the profile only summarizes the last 100 visits, even if there were more. Opened #12045 to make that configurable
