### ISSUE TITLE
Fatal on real time widget, icon not defined

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#12037]
We are getting this error on demo.piwik.org on an ecommerce website (Marketplace)

A fatal error occurred

The following error just broke Piwik (v3.1.0-rc1):

Key "icon" for array with keys "type, url, pageTitle, pageIdAction, idpageview, serverTimePretty, timeSpentRef, pageId, contentName, contentPiece, contentTarget, contentInteraction, interactionPosition, timestamp" does not exist.
in
/storage/piwik-demo/www/demo.piwik.org/plugins/Live/templates/getLastVisitsStart.twig line 148

![image](https://user-images.githubusercontent.com/273120/30343591-22c5b138-9852-11e7-84fe-df06e1642422.png)

**Comment by OldGrumpy-de** [comment]
Is there a workaround for this error? I upgraded a dozen installs to 3.1.0 today and just one of them shows this error... Just wondering what triggers it.

**Comment by sgiehl** [comment]
@OldGrumpy-de you could try to apply this manually on the instance where it's not working:
https://github.com/piwik/piwik/pull/12038/files

**Comment by OldGrumpy-de** [comment]
Thanks a lot, worked like a charm. :)

**Comment by dihihive** [comment]
The fix works well for "Visitors Real time" widget but it brakes All websites list: http://take.ms/JbS0K
which would normally look like so: http://take.ms/TZO2Y

**Comment by fluctuate** [comment]
@sgiehl 
I applied the patch https://github.com/piwik/piwik/pull/12038/files 
and it seems to work fine. (until now)

**Comment by mattab** [comment]
We've released 3.1.1-b1 which fixes the issue, please report if you still have the problem (to use the beta channel see: http://piwik.org/faq/how-to-update/faq_159/ )

**Comment by fluctuate** [comment]
I've just updated to 3.1.1 and it seems everything it's alright!
Thank you

**Comment by ragboy** [comment]
I am getting this error, after upgrade to 3.2.0.
