### ISSUE TITLE
500 error after update 3.0 to 3.1

### ISSUE THREAD

**Issue by Power2All** [piwik/piwik#12032]
Hi,

I applied update to my Piwik setup, but now after login, it gives immediatly a 500 error.
Added a screenshot of the data returned.
Could someone explain me why update 3.0 to 3.1 broke my setup ?

Cheers.
<img width="533" alt="2017-09-12 10_32_49-error loading website - opera" src="https://user-images.githubusercontent.com/2010549/30315988-f76d48f4-97a5-11e7-9813-7e7fdb13a67f.png">

**Comment by sgiehl** [comment]
Can you have a look at your error log? As it returns a 500, there should be an error in the logs...

**Comment by Power2All** [comment]
Problem solved.
Seems the permissions on the cache folder (tmp) was incorrect after update.
Thanks for responding @sgiehl
