### ISSUE TITLE
Error "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_action_event_category.type' in 'field list'"

### ISSUE THREAD

**Issue by arnowelzel** [piwik/piwik#12036]
Recently I updated from Piwik 3.0.4 to 3.1.0.

Now I have the following error in the visitors log page:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_action_event_category.type' in 'field list'`

The visitors live view also does not work any more.

**Comment by JonTheWong** [comment]
Same issue as posted on forum.
https://forum.piwik.org/t/nach-update-auf-3-1-0-keine-besucher-mehr/25519
(German forum)

I'm having the same issue; disabled all 3rd party adding; cleared all cache/tmp files.

Here are some of the logs;

ERROR: Failed to get data from API: SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘log_action_event_category.type’ in ‘field list’ #0 /home2/USER/public_html/analytics.domain.tld/libs/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array) #1 /home2/USER/public_html/analytics.domain.tld/libs/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array) #2 /home2/USER/public_html/analytics.domain.tld/libs/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(’\n\t\t\t\tSELECT\n\t\t\t…’, Array) #3 /home2/USER/public_html/analytics.domain.tld/core/Db/Adapter/Pdo/Mysql.php(256): Zend_Db_Adapter_Pdo_Abstract->query(’\n\t\t\t\tSELECT\n\t\t\t…’, Array) #4 /home2/USER/public_html/analytics.domain.tld/libs/Zend/Db/Adapter/Abstract.php(736): Piwik\Db\Adapter\Pdo\Mysql->query(’\n\t\t\t\tSELECT\n\t\t\t…’, Array) #5 /home2/USER/public_html/analytics.domain.tld/core/Db.php(217): Zend_Db_Adapter_Abstract->fetchAll(’\n\t\t\t\tSELECT\n\t\t\t…’, Array) #6 /home2/USER/public_html/analytics.domain.tld/plugins/Actions/VisitorDetails.php(239): Piwik\Db::fetchAll(’\n\t\t\t\tSELECT\n\t\t\t…’) #7 /home2/USER/public_html/analytics.domain.tld/plugins/Actions/VisitorDetails.php(36): Piwik\Plugins\Actions\VisitorDetails->queryActionsForVisits(Array) #8 /home2/USER/public_html/analytics.domain.tld/plugins/Live/API.php(332): Piwik\Plugins\Actions\VisitorDetails->provideActionsForVisitIds(Array, Array) #9 [internal function]: Piwik\Plugins\Live\API->Piwik\Plugins\Live{closure}(Object(Piwik\DataTable)) #10 /home2/USER/public_html/analytics.domain.tld/core/DataTable.php(475): call_user_func_array(Object(Closure), Array) #11 /home2/USER/public_html/analytics.domain.tld/core/DataTable.php(581): Piwik\DataTable->filter(Object(Closure), Array) #12 /home2/USER/public_html/analytics.domain.tld/core/API/DataTablePostProcessor.php(283): Piwik\DataTable->applyQueuedFilters() #13 /home2/USER/public_html/analytics.domain.tld/core/API/DataTablePostProcessor.php(129): Piwik\API\DataTablePostProcessor->applyQueuedFilters(Object(Piwik\DataTable)) #14 /home2/USER/public_html/analytics.domain.tld/core/Plugin/Visualization.php(449): Piwik\API\DataTablePostProcessor->process(Object(Piwik\DataTable)) #15 /home2/USER/public_html/analytics.domain.tld/core/Plugin/Visualization.php(186): Piwik\Plugin\Visualization->applyFilters() #16 /home2/USER/public_html/analytics.domain.tld/core/Plugin/Report.php(317): Piwik\Plugin\Visualization->render() #17 /home2/USER/public_html/analytics.domain.tld/plugins/CoreHome/Controller.php(58): Piwik\Plugin\Report->render() #18 [internal function]: Piwik\Plugins\CoreHome\Controller->renderReportWidget(Object(Piwik\Plugins\Live\Reports\GetLastVisitsDetails)) #19 /home2/USER/public_html/analytics.domain.tld/core/FrontController.php(544): call_user_func_array(Array, Array) #20 /home2/USER/public_html/analytics.domain.tld/core/FrontController.php(137): Piwik\FrontController->doDispatch(‘Live’, ‘getLastVisitsDe…’, Array) #21 /home2/USER/public_html/analytics.domain.tld/core/dispatch.php(34): Piwik\FrontController->dispatch() #22 /home2/USER/public_html/analytics.domain.tld/index.php(27): require_once(’/home2/USER/pub…’) #23 {main}

[Mon Sep 11 20:04:56.704154 2017] [cgid:error] [pid 31641:tid 140158690981632] [client 123.456.789.1011:60109] End of script output before headers: nk.pl.png, referer: domain/index.php?module=ReferrersManager&actio
n=index&date=last30&period=range&idSite=1&activated=
[Mon Sep 11 20:04:57.388635 2017] [cgid:error] [pid 31641:tid 140158816872192] [client 123.456.789.1011:60109] End of script output before headers: www.google.interia.pl.png, referer: domain/index.php?module=Referr
ersManager&action=index&date=last30&period=range&idSite=1&activated=
[Mon Sep 11 20:04:57.537184 2017] [cgid:error] [pid 31641:tid 140158942762752] [client 123.456.789.1011:60109] End of script output before headers: szukaj.onet.pl.png, referer: domain/index.php?module=ReferrersMana
ger&action=index&date=last30&period=range&idSite=1&activated=
[Mon Sep 11 20:04:59.490973 2017] [cgid:error] [pid 31641:tid 140158867228416] [client 123.456.789.1011:60109] End of script output before headers: szukaj.wp.pl.png, referer: domain/index.php?module=ReferrersManage
r&action=index&date=last30&period=range&idSite=1&activated=
[Mon Sep 11 20:10:21.420480 2017] [cgid:error] [pid 31946:tid 140158884013824] [client 123.456.789.1011:60163] End of script output before headers: nk.pl.png, referer: domain/index.php?module=ReferrersManager&actio
n=index&widget=undefined&idSite=1&period=range&date=last30&showtitle=1&random=4693&activated=
[Mon Sep 11 20:10:21.872320 2017] [cgid:error] [pid 31946:tid 140158884013824] [client 123.456.789.1011:60163] End of script output before headers: www.google.interia.pl.png, referer: domain/index.php?module=Referr
ersManager&action=index&widget=undefined&idSite=1&period=range&date=last30&showtitle=1&random=4693&activated=
[Mon Sep 11 20:10:21.947679 2017] [cgid:error] [pid 31946:tid 140158884013824] [client 123.456.789.1011:60163] End of script output before headers: szukaj.onet.pl.png, referer: domain/index.php?module=ReferrersMana
ger&action=index&widget=undefined&idSite=1&period=range&date=last30&showtitle=1&random=4693&activated=
[Mon Sep 11 20:10:22.094529 2017] [cgid:error] [pid 31946:tid 140158884013824] [client 123.456.789.1011:60163] End of script output before headers: szukaj.wp.pl.png, referer: domain/index.php?module=ReferrersManage
r&action=index&widget=undefined&idSite=1&period=range&date=last30&showtitle=1&random=4693&activated=

**Comment by JonTheWong** [comment]
I was able to resolve the issue by enabling "Events (Core)" in the plugin section.

Can you see if this solves it for you @arnowelzel ?

**Comment by sgiehl** [comment]
Yes. Activating the Events plugin should solve this issue. Will work on a fix, to get it working without activated Events plugin

**Comment by arnowelzel** [comment]
Yes - activating this plugin solved the problem for me as well.

But it was not only the plugin itself - the activation also triggered a database update. So I assume that the update process from 3.0.4 to 3.1.0 was missing some database changes due to the inactive plugin.

**Comment by sgiehl** [comment]
I already found the problem. Will issue a PR for that later

**Comment by mattab** [comment]
We've released 3.1.1-b1 which fixes the issue, please report if you still have the problem (to use the beta channel see: http://piwik.org/faq/how-to-update/faq_159/ )
