### ISSUE TITLE
Multilevel event tracking

### ISSUE THREAD

**Issue by Bryze** [piwik/piwik#12044]
**Given:**
Three Events:
1. Users arriving from `facebook`
2. Users arriving from a website `X`
3. Users placing an order.

**Problem Statement**
1.  Tracking number of users that arrived from `facebook` to website `X` and placed an order.
2.  Tracking number of users that arrived from website `X` and placed an order.
3.  Tracking the users who made this journey, eg- `User A` took journey from `facebook` to `placing an order`.

How do i track this via piwik? According to my current understanding, I am only able to track one level of hierarchy, but I am confused when it comes to multilevel hierarchy and tracking it.

**P.S:** This need not be a 3 level case. Thus, writing the problem statement in the most general way,
1. How do I track the number of users that navigated through `event A` to `event Z` via `n` number of events in between.
 2. How do I track the user's full event traversal activity?

**Comment by mattab** [comment]
1) Facebook and website referrers are automatically tracked by Piwik
2) To track ecommerce interactions, implement Ecommerce tracking: https://piwik.org/docs/ecommerce-analytics/

Then, you'll be able to see all 1/2/3 reports in Piwik, using a mix of https://piwik.org/docs/ecommerce-analytics/#sales-by-marketing-channel and https://piwik.org/docs/segmentation/ when needed

You may also be interested in this plugin that lets you visualise the Users flow: http://plugins.piwik.org/UsersFlow
