### ISSUE TITLE
Crash manually created EventAction with 3.1.0 update

### ISSUE THREAD

**Issue by Yiivgeny** [piwik/piwik#12041]
https://github.com/piwik/piwik/commit/1d5bbb55a4ffdfa9c40ba68a8680a7208e26adb4#commitcomment-24263189

My class ovverride `EventAction` class and `getEventCategory` method for internal recording additional events for some page views. But commit #1d5bbb5 crash my logic as not use suitable method and read data from raw request data (which does not exist for manually created `EventAction`).

**Comment by sgiehl** [comment]
Thanks for the note. I'll prepare a PR to change that in next version
