### ISSUE TITLE
After upgrade to 3.1.0 getting "Oops… there was a problem during the request." in  Visitors real time widget

### ISSUE THREAD

**Issue by dihihive** [piwik/piwik#12051]
After upgrade to 3.1.0 getting "Oops… there was a problem during the request." in  Visitors real time widget

This only happens when there are currently or recently were some visitors online.
Screenshot: http://take.ms/cKY7e

If there were no recent visitors to the site the widget works fine. Screenshot: http://take.ms/NlGNX

===
`A fatal error occurred

The following error just broke Piwik (v3.1.0):

Key "icon" for array with keys "type, url, pageTitle, pageIdAction, idpageview, serverTimePretty, timeSpentRef, pageId, contentName, contentPiece, contentTarget, contentInteraction, interactionPosition, timestamp" does not exist.
in
/var/www/vhosts/website.com/httpdocs/plugins/Live/templates/getLastVisitsStart.twig line 148`

**Comment by sgiehl** [comment]
Thanks for the report. This was already reported and fixed in #12037

**Comment by dihihive** [comment]
The #12037 fix works well for "Visitors Real time" widget but it brakes All websites list: http://take.ms/JbS0K
which would normally look like so: http://take.ms/TZO2Y

**Comment by sgiehl** [comment]
Could you check if adding a second `\` before the constant names solves your problem. eg `constant('\\Piwik::...`

**Comment by dihihive** [comment]
@sgiehl 
Adding the second \ helped. Thank you
