### ISSUE TITLE
get "Allowed memory size exhausted" error after upgrading to version 3.10

### ISSUE THREAD

**Issue by pengshuai2010** [piwik/piwik#12052]
After upgrading to version 3.10, the "Visitors in Real Time" component on the dashboard shows an error message "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4104 bytes) in /var/www/html/core/NumberFormatter.php on line 305".  Not sure if this is related to #8169.

Is there any workaround for this? e.g. can I change the memory limit of php to mitigate this issue? If so, where can I find the php.ini file? Thank you!

**Comment by pengshuai2010** [comment]
I tried to increase PHP's memory limit by editing the php.ini file. I first ran `php -i | grep php.ini`, I got 
`Configuration File (php.ini) Path => /usr/local/etc/php
Loaded Configuration File => /usr/local/etc/php/php.ini
`
I added a line `memory_limit = -1`, then run `php -i | grep memory_limit`, I got 
`memory_limit => -1 => -1`.
But I still get the same error.

**Comment by mattab** [comment]
Hi @pengshuai2010 you need to edit the php.ini for your webserver, not for CLI. Check in phpinfo() where is your php.ini
