### ISSUE TITLE
Visitors Real Time fails after upgrade 3.1.0 

### ISSUE THREAD

**Issue by fluctuate** [piwik/piwik#12056]
The update worked fine, only the widget "visitors in real time" fails, i've already:
- deactivated the plugin and re-activated it again 
- cleared all tmp files. 

No change.

![piwik_error_visitor_real_time](https://user-images.githubusercontent.com/1607696/30427044-8bb1f5c4-994e-11e7-9b73-098da2913048.png)

**Comment by alanjross** [comment]
Same problem-"visitors in real time" fails since 3.10 upgrade.

**Comment by fluctuate** [comment]
I was thinking i was the only to have this problem.

**Comment by sgiehl** [comment]
see #12037
