### ISSUE TITLE
Updating from Piwik 3.0.4 to 3.1.0 causes file integrity warnings

### ISSUE THREAD

**Issue by arnowelzel** [piwik/piwik#12050]
After updating from Piwik 3.0.4 to 3.1.0 with the "automatic" update, I got the following warning in the diagnostics:

```
Directories were found in your Piwik but we didn't expect them.
--> Please delete these directories to prevent errors. <--

Directory to delete: vendor/szymach/c-pchart/app


To delete all these directories at once, you can run this command:
rm -Rf /var/www/clients/client1/web3/web/vendor/szymach/c-pchart/app
```

Probably nothing serious - but it's irritating.

**Comment by mattab** [comment]
Thanks for the report @arnowelzel 

Could you send us the list of all files and directories within this, ie. the output of this command (if you can run commands): `ls -laR vendor/szymach/c-pchart/app/`  ?

**Comment by arnowelzel** [comment]
Sorry, I already cleaned up the path as suggested by the diagnostics (and Piwik works fine so far). I'll try to reproduce the problem with a backup from the point before I applied the update.

**Comment by Findus23** [comment]
See also https://github.com/piwik/piwik/issues/11978 which is the same issue:
```
