### ISSUE TITLE
mailto link should contain semicolon separated email addresses

### ISSUE THREAD

**Issue by egarjans** [piwik/piwik#12057]
https://github.com/piwik/piwik/blob/a54f62f55e500644372fa342738483a6fd3dfaa3/core/Plugin/Controller.php#L882

**Comment by sgiehl** [comment]
Why should that be the case? RFC https://tools.ietf.org/html/rfc6068#section-2 says comma is correct. But might be possible that IE and Outlook only accepts semicolon.

**Comment by egarjans** [comment]
Ok, i see. You are right, we had problem only with Microsoft Outlook. 
It was one of clients who discovered it and for who tried "check names" with comma separated recipients and it didn't work, but after some digging i see there is possibility to enable comma separated email recipients in Microsoft outlook.
