### ISSUE TITLE
After Upgrading to Piwik version: 3.1.0 tracking stopped working for all the sites.

### ISSUE THREAD

**Issue by satya876** [piwik/piwik#12063]
Hi,
Kindly suggest, after I upgraded my Piwik to version: 3.1.0 tracking to all the sites stopped. None of the site is now been tracked. I am not getting any error while I am accessing the Piwik dashboard. It only stopped all the tracking. Kindly help. Before upgrade everything was working fine.

Piwik version: 3.1.0
MySQL version: 5.5.56
PHP version: 7.0.23

**Comment by michaeltarleton** [comment]
+1 Same here

- Piwik: 3.1.0
- MySQL: 14.14 Distrib 5.7.19
- PHP: 7.0.18
- Ubuntu: 16.04.1 (x86_64)
- Apache:
  - version: Apache/2.4.18 (Ubuntu)
  - built:   2017-07-27T14:34:01

Downgrade is not possible because of the database migration

**Comment by mattab** [comment]
@satya876 @michaeltarleton can you please follow instructions here: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker
and let us know what error message you're seeing in the piwik.php debug output?

**Comment by satya876** [comment]
[piwik.zip](https://github.com/piwik/piwik/files/1309631/piwik.zip)
Hi Matt,
I did as instructed. kindly find attached log file.

Thank You !!

**Comment by mattab** [comment]
@satya876 Thanks, but in your tests you have the "Ignore Cookie" created, so your visits are not tracked and there is no error. Could you try again in "private browsing" window or a browser without the Piwik exclude cookie?

**Comment by satya876** [comment]
Hi Matt,

I removed the option to ignore cookie and have tested in "private browsing" as well as from another browser. Still not showing any data in Real Time as well as in Visitor Log. Kindly find the attached updated logs.
[piwik.zip](https://github.com/piwik/piwik/files/1309661/piwik.zip)

**Comment by mattab** [comment]
Now your IP address is excluded so can you remove this IP exclude: 

> DEBUG CoreHome[2017-09-18 03:43:49 UTC] [0b22e] Visitor IP 127.0.0.1 is excluded from being tracked

**Comment by satya876** [comment]
I excluded 127.0.0.1 IP, however now in the visitor log all the IP is shown as 127.0.0.1, it is not tracking the public IP. Kindly refer the attachments with screen shots.
I am not accessing the application from local host. I am using it from the static IP: 107.182.225.47
[ss_visitor_log.zip](https://github.com/piwik/piwik/files/1309745/ss_visitor_log.zip)

**Comment by satya876** [comment]
All the time it is showing "Your current IP address is 127.0.0.1" this is not correct and in the Visitor Log the same IP is showing for all the visit. I believe this application is not reliable for production, this is the 3rd time I find the application have issues.

**Comment by mattab** [comment]
I guess you're using Piwik behind a proxy, see: http://piwik.org/faq/how-to-install/faq_98/

**Comment by satya876** [comment]
Hi Matt,

I use to deploy on Apache and reverse proxy with NGINX before version upgrade everything was working fine. But after version upgrade there are issues coming up. Anyways Thanks for replying.

**Comment by mattab** [comment]
Something changed in your server configuration, because nothing's changed in Piwik in that area

**Comment by satya876** [comment]
Thanks for your response, I will check on my server.

**Comment by satya876** [comment]
I am using the below configuration:

proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"
trusted_hosts[] = "analytics.bluella.in"

Apache is listining on 127.0.0.1:81

NGINX as: proxy_pass  http://127.0.0.1:81;

From long time I was using the same configuration and everything was working fine. But after update, the Visitor IP is simply showing 127.0.0.1 for all the website.

Kindly suggest.

**Comment by mattab** [comment]
which version did you upgrade from?

**Comment by satya876** [comment]
From version 3.0.4

**Comment by satya876** [comment]
Hi Matt,

I am running the Piwik on Apache server without using any reverse proxy. The issue still not rectified. Experiencing the same issue. Only Server local IP is shown in the visitor log.

Kindly suggest.

**Comment by mattab** [comment]
can you post a link to your phpinfo or so?

**Comment by satya876** [comment]
[php.zip](https://github.com/piwik/piwik/files/1328219/php.zip)
Hello Matt,

You can access phpinfo from the below link:
https://analytics.bluella.in/analytics/info.php

Thank You !!

**Comment by mattab** [comment]
the IP address of the user is not visible in the phpinfo, so there is a problem in the configuration of your server somehow. please ask your host how you can get the original IP address

**Comment by satya876** [comment]
Okay, I will and will get back to you with the update. Thank You !!

**Comment by satya876** [comment]
I changed the NGINX configuration as below, now it is working fine. 

proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

Thank You for the help provided.
