### ISSUE TITLE
PHP7.2 no longer supports 'object' as a class name in Sparkline

### ISSUE THREAD

**Issue by Magentaize** [piwik/piwik#12065]
In `piwik/libs/sparkline/lib/Object.php`, the class 'Object' should be renamed.

**Comment by Findus23** [comment]
Hi, thanks for the info.

Maybe we should replace the library with one that isn't 14 years old and can be installed with composer.

e.g. https://github.com/davaxi/Sparkline
(even though it doesn't seem to support FeaturePoints (Minimum/Maximum))

**Comment by mattab** [comment]
fixed  in #12099 duplicates  #12086

**Comment by Findus23** [comment]
@mattab, to be precise #12086 is a duplicate of this issue as it appeared later.
