### ISSUE TITLE
FAQ doesn't work to reset admin password

### ISSUE THREAD

**Issue by Dennis1993** [piwik/piwik#12069]
Hello,

I want to program a password change function as a bridge. If I change my password on the website, the password should be updated in piwik too. I tested this but the login is not possible. Is that changed in piwik 3.1.0?
How I can create a hash to set the new password?

wrong FAQ: https://piwik.org/faq/how-to/faq_191/

Systeminformation:
PHP 7.1.6
Piwik 3.1.0
Ubuntu with Apache 2.4

**Comment by Findus23** [comment]
Hi,

Can you exactly describe what you were doing and what didn’t work?

The hash in the database is the result of the password_hash() php function of the md5 hash of the users password.

**Comment by Dennis1993** [comment]
I've created a hash how explained in the documentation. The login is after that not possible.
Then I have looked in the code. There is used another code: https://github.com/piwik/piwik/blob/a9038318a94cc32f0f15add5272322ff6afe71f5/core/Auth/Password.php#L25

What I'm doing wrong? It is working in your system? Maybe I make it wrong

**Comment by sgiehl** [comment]
for me it works without any problem if I follow the steps in FAQ.

**Comment by Findus23** [comment]
Only thing I can think of is checking again if the username is correct. See also:
https://forum.piwik.org/t/cannot-log-into-installation/25676

**Comment by Dennis1993** [comment]
Now it works, I don‘t know what I‘ve do wrong. Thanks for your help! 👍🏿
