### ISSUE TITLE
Event value storage machanism

### ISSUE THREAD

**Issue by Bryze** [piwik/piwik#12079]
Forgive me, if it sounds trivial.
But, I have a doubt on how event value is stored and tracked.

For example, assume there are two commands
`_paq.push(['trackEvent', 'Documentary', 'Rating', 'Thrive', 9.5]);` and
`_paq.push(['trackEvent', 'Documentary', 'Rating', 'Thrive', 9.0]);`.

Will the above codes give me a segregated user count based on how many users gave rating 9.5 and rating 9.0?
If no, could you please highlight how is event value used? 
And which table, column in database stores the `event value`, couldn't find it here ->
 [https://developer.piwik.org/guides/persistence-and-the-mysql-backend#action-types](url)

**Comment by mattab** [comment]
> Will the above codes give me a segregated user count based on how many users gave rating 9.5 and rating 9.0?

Yes

> And which table, column in database stores the event value, couldn't find it here ->
https://developer.piwik.org/guides/persistence-and-the-mysql-backend#action-types

in the `log_link_visit_action.custom_float` column
