### ISSUE TITLE
Different custom dimension entries for same value?

### ISSUE THREAD

**Issue by Bryze** [piwik/piwik#12083]
I have this use case,

For example -> I put forward two custom dimensions with same name but different values.

Will the entries of different values be stored differently?
Or will the values be overridden because the custom dimension name is same?

**Comment by mattab** [comment]
Hi @Bryze 
Please ask questions in the forums: http://forum.piwik.org/
as here is only for bug reports and feature requests.

The answer is that, if you use a Custom Dimension of Visit scope, the last value will be kept.
If you use "Action" scope, then all values will be recorded as they are recorded in each action/pageview.
