### ISSUE TITLE
PHP Fatal Error with PHP 7.x

### ISSUE THREAD

**Issue by umpire274** [piwik/piwik#12086]
Hi all.

I've installed Piwik 3.0.4 on RHEL 7 with Apache 2.4 e PHP 7.2 successfully.
When I've finished the installation in the main dashboard I'll see an error in a widget in the middle of the page, and in apache log I've this error:

[Wed Sep 20 12:41:05.322847 2017] [php7:error] [pid 26822] [client 10.8.161.114:57411] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/html/piwik/libs/sparkline/lib/Object.php on line 72, referer: ...

I know that is a problem with PHP 7.x: "PHP 7 will soft reserve object as a possible typehint for a 7.x release (or may never use it at all)."

Is it correct? There's a solution?

Alex.

**Comment by Findus23** [comment]
Hi, this is an issue in a third party library used by piwik.
See also https://github.com/piwik/piwik/issues/12065

I have proposed a solution, but there is some wok left until it is fixed.

**Comment by umpire274** [comment]
For completato the reference in error are in:

piwik/libs/sparkline/lib/Object.php (riga 72):
`class Object {`

piwik/libs/sparkline/lib/Sparkline.php (riga 27):
`class Sparkline extends Object {`

**Comment by umpire274** [comment]
@Findus23 thanks a lot.
