### ISSUE TITLE
lang/cs.json malformed

### ISSUE THREAD

**Issue by navstevnost** [piwik/piwik#12088]
After update to 3.1.1 Piwik in Czech lang not work. File plugins/UserCountry/lang/cs.json is malformed, one curly bracket is missing.

**Comment by mattab** [comment]
Thanks for the report @navstevnost 

We need to:

* Add integration tests checking all *json files are valid in lang/ folders
* Fix this issue and any other issue in other languages

**Comment by sgiehl** [comment]
fixed with #12094
