### ISSUE TITLE
Chinese map missing taiwan Province and Tibet

### ISSUE THREAD

**Issue by lihaoHuawei** [piwik/piwik#12082]
![20170920-144233 espace](https://user-images.githubusercontent.com/24602093/30630186-ffcf2bc6-9e11-11e7-94e0-e09b897f6145.png)

**Comment by sgiehl** [comment]
This duplicates #10757, #6994, #11822 
Note: Tibet should already be part of China with Piwik 3.1.1
We hope to create some completely new maps with 4.0.0

**Comment by forging2012** [comment]
强烈抗议！
