### ISSUE TITLE
BUG: Schedule old data deletion

### ISSUE THREAD

**Issue by eramirezprotec** [piwik/piwik#12097]
The problem was when I tried to change the frequency Piwik uses to delete old data in database. I could not change the frequency value (day, week, etc). So, making the following change did the trick:

Piwik version: **3.0.4**
Plugin: **Privacy Manager**
File: angularjs/schedule-report-deletion/**schedule-report-deletion.controller.js**
Error: _Cannot read property ‘savePurageDataSettings’ of undefined_
Problem: _**reportDeletionModel**.model.savePurageDataSettings(this..._
Solution: _**self**.model.savePurageDataSettings(this..._

**Comment by Findus23** [comment]
from https://forum.piwik.org/t/how-to-force-piwik-to-merge-files-in-production-environment/25479
