### ISSUE TITLE
API: prevent the API returning not well-formed XML

### ISSUE THREAD

**Issue by ghimf** [piwik/piwik#12090]
Since 3.1.0, the result/visitedPages/row elements, when the visited url contains the '=' character, instead of the expected:
`<visitedPages><row key="http://example.org/homepage?param1=value1&param2=value2">1</row></visitedPages>`
it returns:
`<visitedPages><row http://example.org/homepage?param1="value1&param2=value2">1</row></visitedPages>`

**Comment by mattab** [comment]
Hi @ghimf 

Thanks for the report. Can you please send the URL used to generate this API output?

Looking forward to fixing this issue

**Comment by ghimf** [comment]
`http://demo.piwik.org/?module=API&method=Live.getVisitorProfile&idSite=7&visitorId=VID&format=xml&token_auth=TAU`
with valid `VID` and `TAU` values

**Comment by mattab** [comment]
@sgiehl re-opening because:

* our automated tests do not show this actual bug. We need to have at least one test which shows the XML problem
* to prevent the issue of invalid XML returned by API, we also need to add some test that ensures that all XML files are valid XML

**Comment by ghimf** [comment]
Hello,

With the same URL as above
`http://demo.piwik.org/?module=API&method=Live.getVisitorProfile&idSite=7&visitorId=VID&format=xml&token_auth=TAU`
when the `VID` visitor used a "Portable media player" device, the result/devices element contains a not well-formed element named `<Portable media player></Portable media player>`.

Regards.

**Comment by mattab** [comment]
thanks for letting us know @ghimf

**Comment by sgiehl** [comment]
Good point. I'll change that.

**Comment by mattab** [comment]
Last remaining task AFAIK before closing issue:


* to prevent the issue of invalid XML returned by API, we also need to add some test that ensures that all XML files are valid XML
