### ISSUE TITLE
Call to undefined function Piwik\Plugins\ScheduledReports\mb_strtoupper() in plugins/ScheduledReports/Controller.php 39

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#12101]
error message reported by email: 

> Call to undefined function Piwik\Plugins\ScheduledReports\mb_strtoupper() in /home/adad1041/public_html/adept_piwik/plugins/ScheduledReports/Controller.php 39 using PHP 7.0.23

we should call nb_strtotupper only when the function is available (when `mbstring` extension is enabled), otherwise we should just leave the text as-is (to avoid calling strtotupper on unicode which would not work).

**Comment by sgiehl** [comment]
`mbstring` extension is required for Piwik. At least we have a system check for it. Also the `testMinimumPhpVersion.php` should prove that `func_overload` is disabled. So this method should always be available.

**Comment by mattab** [comment]
> So this method should always be available. 

interesting, didn't remember we required the extension. it can become sometimes un-available later if server changes configuration.

**Comment by sgiehl** [comment]
It's in the list of required extensions in https://github.com/piwik/piwik/blob/3.x-dev/plugins/Diagnostics/Diagnostic/PhpExtensionsCheck.php#L65
