### ISSUE TITLE
Minor JavaScript Memory Leak: `piwikApiService` `allRequests` array

### ISSUE THREAD

**Issue by jvilk** [piwik/piwik#12105]
## Problem

The `piwikApiService` class contains an array called [`allRequests`](https://github.com/piwik/piwik/blob/193a9bb8b13bfdce69731181d3dad102f7e14f6b/plugins/CoreHome/angularjs/common/services/piwik-api.js#L22) that it [appends to whenever the frontend makes an API request](https://github.com/piwik/piwik/blob/193a9bb8b13bfdce69731181d3dad102f7e14f6b/plugins/CoreHome/angularjs/common/services/piwik-api.js#L170). However, it only clears this array if [`abortAll`](https://github.com/piwik/piwik/blob/193a9bb8b13bfdce69731181d3dad102f7e14f6b/plugins/CoreHome/angularjs/common/services/piwik-api.js#L240) is called. Over a session with the Piwik dashboard, the array continues to grow as the frontend makes API requests.

## Solution

`allRequests` should only contain active requests that have not yet completed, as it is only used by `abortAll`.

A simple solution is to remove requests when they complete. To do this, change [line 170](https://github.com/piwik/piwik/blob/193a9bb8b13bfdce69731181d3dad102f7e14f6b/plugins/CoreHome/angularjs/common/services/piwik-api.js#L170) to the following:

```javascript
allRequests.push(request);
promise.finally(function() {
  var index = allRequests.indexOf(request);
  if (index !== -1) {
    allRequests.splice(index, 1);
  }
});
```

**Comment by tsteur** [comment]
Great suggestion. Do you mind issuing a pull request for this?

**Comment by jvilk** [comment]
PR issued and awaiting review!
