### ISSUE TITLE
Issue with SVG

### ISSUE THREAD

**Issue by savkevip** [piwik/piwik#12115]
Does Piwik show SVG and canvas elements on recordings?

**Comment by Findus23** [comment]
About which recordings are you talking?
Do you maybe mean the Heatmap and Session Recording premium plugin?
If yes, you'll need to open a ticket on the marketplace as this is the issue tracker of the open source software.

**Comment by savkevip** [comment]
Yes, I think on premium plugin... Thanks, dude! :)

**Comment by Findus23** [comment]
If you think others will have the same question, you can ask on the forum:

https://forum.piwik.org/c/premium-plugins
