### ISSUE TITLE
issue with Widgetized dashboards

### ISSUE THREAD

**Issue by vincent3569** [piwik/piwik#12113]
hi

this issue is linked with https://github.com/piwik/piwik/issues/12014 (the second issue listed in is not fixed).

when I use widgetized dashboards, there is a link to my dashbord.
this link is following: `javascript:$('#dashboardWidgetsArea').dashboard('loadDashboard',%201);`
When I follow this link, there is an issue and I have only `[object Object]` displayed.

**Comment by mattab** [comment]
Which version of Piwik are you using?

**Comment by vincent3569** [comment]
I use the latest one (3.1.1)

**Comment by mattab** [comment]
Can be reproduced here: https://demo.piwik.org/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=3&period=week&date=today&token_auth=anonymous&updated=5&segment=deviceType%3D%3DSmartphone%2CdeviceType%3D%3DTablet

Thanks for the report @vincent3569 

* We need to fix this issue,
* and add a UI test to prevent it occuring again
