### ISSUE TITLE
detecting java plugin on edge browser?

### ISSUE THREAD

**Issue by pavarnos** [piwik/piwik#12117]
Hi. Piwik appears to detect Java and PDF plugins for MS Edge, but Edge does not allow plugins?

<img width="643" alt="screen_shot_2017-09-26_at_12_09_34_pm" src="https://user-images.githubusercontent.com/589595/30835229-c32877f8-a2b3-11e7-9205-975bc3263f7f.png">

**Comment by Findus23** [comment]
Hi, can you enter navigator.mimetypes into the JavaScript console and paste the result here?
Piwik is checking for application/x-java-vm and application/pdf

See also here: https://github.com/piwik/piwik/blob/3.x-dev/js/piwik.js#L5423

**Comment by sgiehl** [comment]
Had a short look at an Edge browser. It seems to have an built in PDF viewer, and maybe it automatically uses JAVA if installed.
 Maybe at some point we shouldn't name it "Plugins" anymore, as it more or less represents supported "technologies" and not real plugins anymore...

**Comment by Findus23** [comment]
> Maybe at some point we shouldn't name it "Plugins" anymore, as it more or less represents supported "technologies" and not real plugins anymore...

I agree. See also: https://forum.piwik.org/t/cookie-browser-plugin/25711

**Comment by pavarnos** [comment]
sorry for the delay: my user is in a time zone 13 hours different to mine. Takes a while to arrange a meeting... his navigator.mimetypes below. I just checked a more recent login and it is still showing the same as the original image above. Perhaps piwik is aggregating / collating across many different sessions (from different devices) instead of showing the plugins just from the current (most recent) session / device? 
<img width="863" alt="edge_navigator_mimetypes" src="https://user-images.githubusercontent.com/589595/30934597-93598cc4-a42a-11e7-9b2f-8e6e21e74888.png">

**Comment by mattab** [comment]
> Perhaps piwik is aggregating / collating across many different sessions (from different devices) 

That would be the case only if you use User ID https://piwik.org/docs/user-id/ and if user connected from different devices with the same user id

**Comment by pavarnos** [comment]
Yes, we are using a consistent UserId across all devices

**Comment by pavarnos** [comment]
Looking at the source code, there is separate java detection https://github.com/piwik/piwik/blob/3.x-dev/js/piwik.js#L5459. So i asked him to type `navigator.javaEnabled()` in his browser. Result is `true`.

**Comment by pavarnos** [comment]
https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator-javaenabled 
```
The navigator.javaEnabled() method must return true if the user agent supports a plugin that supports the MIME type "application/x-java-vm"; otherwise it must return false.
```

**Comment by pavarnos** [comment]
How does piwik aggregate browser plugins cross different visitor sessions (with UserId enabled)? Is it the last N sessions? All detected plugins for all time?
Are there any configuration settings to change this?

I'm using Piwik to understand what browser plugins our users have installed. Then I can go visit each user and say "hey, you should really disable Flash". But I need to know what the user had enabled on their last visit (or 2), not for all time... Is this possible?

**Comment by mattab** [comment]
> How does piwik aggregate browser plugins cross different visitor sessions (with UserId enabled)? Is it the last N sessions? All detected plugins for all time? Are there any configuration settings to change this?

The plugin detection is done once per [visit](https://piwik.org/faq/general/faq_36/). so each "Session" (ie. visit) will have their own set of plugins.

**Comment by pavarnos** [comment]
@mattab thanks for the quick reply. The visitor profile shows the plugin info only at the top of the page. Is this for the most recent visit? Or is it some aggregation of all the visits?

I'm trying to figure out why an Edge user is shown as having a Java plugin enabled when Java has been removed from his computer (in the last few weeks) and Edge does not support plugins (eg Java).

**Comment by mattab** [comment]
Are you using latest Piwik version? in the latest version you can see plugins for each individual visit by clicking on the visit row itself

**Comment by pavarnos** [comment]
Piwik version 3.2.0.
Thanks: I did not know that about plugins for each visit. Very handy to have the extra detail.

So here is a visit from the same user 10 days ago, using Edge, which shows the Java plugin. See the screenshots above which show Java is not installed. So why is it showing Java?
<img width="1112" alt="screen_shot_2017-10-17_at_8_50_32_pm" src="https://user-images.githubusercontent.com/589595/31652892-3567e540-b37d-11e7-87fd-88207b34ec7a.png">

**Comment by mattab** [comment]
> using Edge, which shows the Java plugin. See the screenshots above which show Java is not installed. So why is it showing Java?

No idea about that

**Comment by sgiehl** [comment]
It's right that Edge dropped support for any plugin. But there could be another reason for this "incorrect" data. The browser plugins are detected using javascript, whereas the browser itself is detected by parsing the user agent. Actually someone could use firefox with an extension to change the useragent. That way Piwik would detect the plugins the firefox has, but would be reported as another browser according to the useragent.

**Comment by sgiehl** [comment]
@pavarnos On my Edge `navigator.javaEnabled()` returns `true` as well, which imho it shouldn't. so maybe we shouldn't check that on Edge. Will prepare a PR for that.

**Comment by pavarnos** [comment]
Crazy! Thanks for the PR
