### ISSUE TITLE
Row evolution of custom report

### ISSUE THREAD

**Issue by eramirezprotec** [piwik/piwik#12132]
Hi! I developed a new report. It is associated with a dimension and it's all working "fine". The problem is when I click on the "Open row evolution", It takes TOO LONG to show the evolution graph. How can I make this run faster? 

I don't know if (somehow) I have to archive each row of the report. 

**This is the aggregateDayReport method of the Archiver.php:**

    $archiveProcessor = $this->getProcessor();
    $dataTable = new DataTable();
    $dataTable->addRowsFromSimpleArray($visitsData); //$visitsData is a well formed array.
    $serializedDataTable = $dataTable->getSerialized();
    $archiveProcessor->insertBlobRecord(self::XXX_RECORD_NAME, $serializedDataTable);

**aggregateMultipleReports method:**

```
$archiveProcessor = $this->getProcessor();
$archiveProcessor->aggregateDataTableRecords(self::READINGSMAS_RECORD_NAME);
```

**And this is my API.php:**

    $archive   = Archive::build($idSite, $period, $date, $segment);
    $dataTable = $archive->getDataTable(Archiver::XXX_RECORD_NAME);
    return $dataTable;

**Comment by sgiehl** [comment]
Row evolution loads a big bunch or archives to compare the data within. As long as all archives are built, there is nothing you can do about the performance of row evolution in your plugin. 
Improvements therefor would be needed to be done in core.

**Comment by eramirezprotec** [comment]
Thank you very much for taking the time to answer this issue, @sgiehl.

**Comment by eramirezprotec** [comment]
@sgiehl, I don't understand why the row evolution graph of the reports built by me are taking too long to be shown. Normal reports' row evolution graph like campaigns, referrers, etc., load really fast. Is there something I am missing that I should add to my Report? Or at the moment of archiving? 

A normal Matomo report row evolution graph loads in less than 4 seconds; the row evolution graph of my reports takes more than 30 seconds (I'm getting a timeout, and I know I can increase that time, but I'm not interested, my goal is to load my reports evolution row as fast as Matomo's reports).

**Comment by tsteur** [comment]
I suggest to ask this in the forums as we usually don't answer such questions here. https://forum.matomo.org/c/plugins-platform

I would check if viewing the evolution report is still slow when you don't include today in the row evolution.

**Comment by eramirezprotec** [comment]
@tsteur, I understand. I'm sorry.

It is still slow when I don’t include today in the row evolution. This is a big problem for me…

I asked on the forums: https://forum.matomo.org/t/row-evolution-takes-too-long-to-show-up/27203
