### ISSUE TITLE
Warnings all over the page in every page (Warning - htmlentities(): charset 'Windows-1255' not supported)

### ISSUE THREAD

**Issue by Bosaa** [piwik/piwik#12134]
Hi,
I reported this 1 year ago.
You get errors in every page 
When did it start ? V3
V2 was all good but after update to V3 its start.
I tried to delete and reinstall … nothing
Piwik version: 3.1.2-b2
MySQL version: 5.6.36
PHP version: 5.6.31
Error : 

`WARNING: /home/piwik/domains/domain.com/private_html/core/API/DataTablePostProcessor.php(400): Warning - htmlentities(): charset 'Windows-1255' not supported, assuming utf-8 - Piwik 3.1.2-b2 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)`

PrintScreen : https://forum.piwik.org/uploads/db1181/original/2X/8/8cf5c91e9dc3936a742001780c3f095d644c8ca1.png

**Comment by sgiehl** [comment]
Could you have a look at the output of phpinfo() and check what your `default_charset` is?

**Comment by Bosaa** [comment]
default_charset
Local Value : Windows-1255
Master Value : Windows-1255

**Comment by Findus23** [comment]
@Bosaa 
Have you tried setting default_charset to "utf-8"?
Why are you using Windows-1255?

**Comment by Bosaa** [comment]
i tried to set it utf-8 it not working .. and i have to use Windows-1255 due to my websites on my server (they are in Hebrew)
and piwik not support Hebrew

**Comment by sgiehl** [comment]
Ok. so the problem is that you use a charset that is [not compatible](http://php.net/manual/de/function.htmlentities.php) with `htmlentities`. I'll check if we can change that in Piwik, so *invalid* charset aren't a problem here

**Comment by Bosaa** [comment]
thanks !!!

**Comment by mattab** [comment]
Thanks for the report @Bosaa and @sgiehl for the solution :+1:
