### ISSUE TITLE
Possible to modify a goal's revenue after it's been added?

### ISSUE THREAD

**Issue by olleharstedt** [piwik/piwik#12155]
We have a web page with subscriptions. Therefore, it's not possible to know beforehand how much revenue a certain goal conversion will make since the subscription can be cancelled in two months, or two year, or whenever. Basically, we need to update the revenue of a specific goal conversion at every payment until the subscription ends. Is it possible to fetch one goal conversion using the Piwik API and update its revenue?

**Comment by olleharstedt** [comment]
As an example, consider a user making two orders one year apart. One order lasts for 2 months, the other one 4 months. So what we need is to bind one visit to a revenue of 2 months, and the other visit to a revenue of 4 months. If we just add a total of 6 goal conversions, it would not be possible to know which visit led to the most revenue.

**Comment by mattab** [comment]
>  Is it possible to fetch one goal conversion using the Piwik API and update its revenue?

you can use `Goals.updateGoal` HTTP API, but it will only affect future converted goals

> We have a web page with subscriptions. Therefore, it's not possible to know beforehand how much revenue a certain goal conversion will make since the subscription can be cancelled in two months, or two year, or whenever. Basically, we need to update the revenue of a specific goal conversion at every payment until the subscription ends.

For this you should use Ecommerce analytics: https://piwik.org/docs/ecommerce-analytics/

**Comment by olleharstedt** [comment]
@mattab Thanks for your answer!
