### ISSUE TITLE
Plugin: Dashboard as Widget/Iframe, SegmentSelection do not affect

### ISSUE THREAD

**Issue by TomTheRock** [piwik/piwik#12166]
Hi There,

i use the newest Piwik 3.1.1.

If you use the Dashboard over the Widget implementation (iframe) you can select/create the Segmentations you created. But they do not affect/data stastics do not filter always fall back to default "All Visits". If you direct login into piwik Backoffice it worked.

My Widget call example:
https://www.xxxxxxxxx.com/_statistics/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=xxxxx&period=week&date=today&token_auth=xxxxxxxxxxxxx

Best Regards
Tom

**Comment by tsteur** [comment]
This can be reproduced on https://demo.piwik.org/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=3&period=week&date=today&token_auth=anonymous

**Comment by tsteur** [comment]
Thanks for the report @TomTheRock

**Comment by tsteur** [comment]
FYI: I  quickly debugged and noticed this regressed in #11790  https://github.com/piwik/piwik/pull/11790/files#diff-4e4c0250d8a0ec9660276e396757f6efL1317
