### ISSUE TITLE
Please use same padding for all widget content

### ISSUE THREAD

**Issue by fdellwing** [piwik/piwik#12175]
As you can see on the screenshot, this card (.widget .widgetContent .card) has no padding to the widget border, looking really awfull.

.widget .dataTableVizEvolution has 10px left and right.
.widget .sparkline has 5px margin left

So we have 3 different styles in one widget. Thats not looking clean at all.

![piwik](https://user-images.githubusercontent.com/22813377/31499889-4e0d0c3a-af66-11e7-96de-3fbe322b2bd7.png)

**Comment by mattab** [comment]
Thanks for the report @fdellwing 
Yes, we need to have the same consistent padding everywhere. 
Would be great if you can submit a pull request addressing this change :+1:

**Comment by fdellwing** [comment]
Well, giving the card class padding is not as hard. But I'm pretty sure I should not give the sparkline 10px, I think a container (maybe a card) around the sparklines should be usefull?

**Comment by mattab** [comment]
we wouldn't want a container around sparklines

**Comment by fdellwing** [comment]
As long as I know, a card has no visible border.

**Comment by mattab** [comment]
@fdellwing I propose you create a Pull request, which will trigger our UI tests and take all screenshots, so we can easily see whether something changed and how :+1:

**Comment by mattab** [comment]
Fixed in #12220
