### ISSUE TITLE
HTTPS-green PAD lock not showing after adding the tracking code.

### ISSUE THREAD

**Issue by infomazeteam** [piwik/piwik#12187]
Hi,
1. My PIWIK is running on https and i have even Force HTTPS plugin activated.
2. My site where i am using the tracking code is on https as well.

But as soon as add the code the green pad lock is not visible, it basically consider it as insecure.

When i checked the chrome network requests then i found that it first call piwik.js, after that piwik.php and then it try to send the request to piwik login page.
Please check the attached screen shot to know what i mean.
![2017-10-13 13_30_39-https___secure propertycampaign com_piwik php](https://user-images.githubusercontent.com/24824800/31536787-7ee11b32-b01d-11e7-8c78-b7c6b603c634.png)
When i checked the same thing on piwik.org there it is not going to index page. did any one else faced this problem please? is there any setting or solution please this please?

**Comment by Findus23** [comment]
Hi,
Can you check the third request. Something on your webserver is redirecting the request instead of letting it through to Piwik.
Maybe check your .htaccess for old rules.

**Comment by infomazeteam** [comment]
Hi,

Thanks, secure.propertycampaign.com is my site URL. 

Also https://analytics.propertycampaign.com is in a seperate root directory and does not have any .htaccess file.

Kindly note: User logs are getting recorded correctly, it is just this redirect issue.

Thanks

**Comment by mattab** [comment]
Looks like your piwik.php or something else issues a 302 redirect to the homepage of your subdomain. 

I recommend you check your JS code contains a line like this:

`var u="//analytics.domain.org/";`

If not, copy-paste the JS code that Piwik latest version gives you, into your website
