### ISSUE TITLE
Can't install piwik with composer and php 7.1

### ISSUE THREAD

**Issue by netwarp** [piwik/piwik#12198]
Hi,
I try to install piwik with composer: `composer require piwik/piwik` and I have this error message: 

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for piwik/piwik ^3.2 -> satisfiable by piwik/piwik[3.2.0].
    - Conclusion: remove symfony/console v3.3.10
    - Conclusion: don't install symfony/console v3.3.10
    - piwik/piwik 3.2.0 requires symfony/console ~2.6.0 -> satisfiable by symfony/console[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - Can only install one of: symfony/console[v2.6.0, v3.3.10].
    - Can only install one of: symfony/console[v2.6.1, v3.3.10].
    - Can only install one of: symfony/console[v2.6.10, v3.3.10].
    - Can only install one of: symfony/console[v2.6.11, v3.3.10].
    - Can only install one of: symfony/console[v2.6.12, v3.3.10].
    - Can only install one of: symfony/console[v2.6.13, v3.3.10].
    - Can only install one of: symfony/console[v2.6.2, v3.3.10].
    - Can only install one of: symfony/console[v2.6.3, v3.3.10].
    - Can only install one of: symfony/console[v2.6.4, v3.3.10].
    - Can only install one of: symfony/console[v2.6.5, v3.3.10].
    - Can only install one of: symfony/console[v2.6.6, v3.3.10].
    - Can only install one of: symfony/console[v2.6.7, v3.3.10].
    - Can only install one of: symfony/console[v2.6.8, v3.3.10].
    - Can only install one of: symfony/console[v2.6.9, v3.3.10].
    - Installation request for symfony/console (locked at v3.3.10) -> satisfiable by symfony/console[v3.3.10].

Installation failed, reverting ./composer.json to its original content.`

I use php 7.1
Do someone knows what's wrong ?

**Comment by pavarnos** [comment]
is there anything other than piwik in your composer.json? looks like a version clash with another tool?

**Comment by mattab** [comment]
Hi @netwarp 
As @pavarnos suggests, "looks like a version clash with another tool" ie. ` - Conclusion: remove symfony/console v3.3.10`

We probably need to update our symfony/console version to solve this problem, feel free to create a PR for this
