### ISSUE TITLE
Piwiki 3.20 Flowplayer 7.1.2 in splash mode.

### ISSUE THREAD

**Issue by ctaity** [piwik/piwik#12209]
In splash mode, with piwiki 3.2.0 and flowplayer 7.1.2 in splash mode, the plugin dont count plays, the media pluguin.

**Comment by tsteur** [comment]
Flowplayer with splash mode can be tracked. You may need to add a code to your website like this for older Media Analytics versions, but latest version (3.0.12) detects this automatically and works out of the box. 

```js
flowplayer().on('load', function () {
    Piwik.MediaAnalytics.scanForMedia();
 });
```

**Comment by ctaity** [comment]
Thanx, i will test

**Comment by tsteur** [comment]
If you have any questions or problems otherwise, feel free to simply email contact@innocraft.com
