### ISSUE TITLE
Piwik 3.1.1. Upgrade issue

### ISSUE THREAD

**Issue by anidayta** [piwik/piwik#12229]
After upgrading to 3.1.1, Piwik data from before the upgrade is lost.
Was there something missed that the old data is not currently available?  What needs to happen to make sure that old data pre-upgrade is available when we log into Piwik?

**Comment by sgiehl** [comment]
There shouldn't be any data loss when updating Piwik. What exactly have you done? Did you use the auto update within Piwik or did you perform a manual update (uploading):

**Comment by anidayta** [comment]
manual update

**Comment by sgiehl** [comment]
how exactly did you perform it? Did you remove and reupload all files, or simply uploaded and overwrite? Did you reuse the same config as before? Did you perform the (database) update on console?

**Comment by anidayta** [comment]
no its totally different server..we have built complete PHP and MySQL server and  then downloaded latest piwik.. and installed it in the server with latest version..

**Comment by sgiehl** [comment]
then why are you talking about an upgrade issue? You could have reused old data be importing the database before. if you already started tracking in the new database, there is no simple way to reimport the old data.
