### ISSUE TITLE
Visitor statistics error

### ISSUE THREAD

**Issue by kentTanL** [piwik/piwik#12261]
HI, I hava a error, like this:
![qq](https://user-images.githubusercontent.com/15412193/32541302-4254219a-c4aa-11e7-8c2e-928fe87066a2.png)

the number of visitors can't be counted,  I was Piwik started using on 2017.02.14, So what's wrong this one? thanks

**Comment by Findus23** [comment]
Hi,

Can you please explain more detailed what you expected to happen and what happened instead.
According to the graph there is only data in 2017 which is obviously if you started collecting data in 2017.

**Comment by kentTanL** [comment]
Yes , I mean is , in fact, I have the  number of visitors, but it shown above is 0

**Comment by mattab** [comment]
Can you switch to english and take again the screenshot?

If the blue line refers to "Unique Visitors" you will need to activate a setting to enable unique visitors metrics for years: https://piwik.org/faq/how-to/faq_113/

**Comment by kentTanL** [comment]
Yes, the blue line refers to "Unique Visitors", and you are right, I set up `enable_processing_unique_visitors_year = 1` ,  solved. thanks
