### ISSUE TITLE
Add possibility to ignore certain files in File integrity check

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#12268]
I mean the check that suggests to delete certain files that are no longer needed.

```
File integrity: WARNING File integrity check failed and reported some errors. You should fix this issue and then refresh this page until it shows no error.

Files were found in your Piwik but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: config/config.myuser.php
File to delete: config/config.mytest.php
```

It would be great to be able to specify files (directories not needed for now) that should be ignored and not suggested to be deleted. Configuration should be either via DI, or via config file.

**Comment by verybigelephants** [comment]
so how do i actually configure the global.php file? because it's also part of matomo file integrity and i see no such settings for configuration in `config.ini.php`

**Comment by sgiehl** [comment]
You can simply create a `config.php` file in the config directory.
