### ISSUE TITLE
Usort Warning ReportsProvider.php line 166

### ISSUE THREAD

**Issue by mstroeve** [piwik/piwik#12281]
OS : Ubuntu 14.0.4.5 LTS
PHP Version: PHP 5.5.9-1ubuntu4.22 

Original warning message:

WARNING: /piwik/core/Plugin/ReportsProvider.php(166): Warning - usort(): Array was modified by the user comparison function - Piwik 3.2.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

reported here first: https://forum.piwik.org/t/usort-warning-reportsprovider-php-166/26341

**Comment by mattab** [comment]
We had this problem and it seems that upgrading PHP to latest version has fixed it. Latest of 7.0 or 7.1

could you try upgrading to latest PHP 5.5 or 5.6 or 7.0 and see if this error occurs again in the future?

**Comment by mstroeve** [comment]
I cant seem to reproduce it anymore after:
1. update piwik with recent update.
2. double checking plugins and removing 2 old plugins
3. running latetst 14.04 LTS sec. updates (no php packages where there).

So one of these seemed to fix it.  This issue can be closed

**Comment by mattab** [comment]
We will try to fix this issue as it seems quite a few people experience it

**Comment by olivierlambert** [comment]
Hi there! Got it since last Piwik update (`3.2.1`) on Debian 9 (with PHP `5.6.30`)
