### ISSUE TITLE
Period selector doesn't work - it shows "{{ periodselector.getcurrentviewingtext() }}"

### ISSUE THREAD

**Issue by vradmilovic** [piwik/piwik#12306]
Period selector shows _**{{ periodselector.getcurrentviewingtext() }}**_ and doesn't respond when clicked. This started happening since **3.2.1-b1**, but as it's the same in b2, I figured it's not something everybody see, so decided to report it here.

I have checked with two different browsers (Firefox with bunch of addons and vanilla Chromium). Piwik is in English and no additional plugins installed.

**Comment by sgiehl** [comment]
could you check the browsers developer tools if any error occurs?

**Comment by vradmilovic** [comment]
Sorry, I should have mentioned it right away. Only "Synchronous XMLHttpRequest on the main thread is deprecated" warning, which I believe is around for a while.

**Comment by Presskopp** [comment]
{{ periodSelector.getCurrentlyViewingText() }} +1 
FF57.0x64, no console errors

**Comment by diosmosis** [comment]
@vradmilovic @Presskopp Does this continue to happen after a cache clear or in an incognito window? Does it happen for every page/site? And does it also happen regardless of whether you're viewing a segment?

**Comment by vradmilovic** [comment]
For all questions the answer is "Yes".

**Comment by diosmosis** [comment]
I can reproduce the issue now, has to do w/ the `previous7` query parameter value. Will post a fix soon or failing that, tomorrow.
