### ISSUE TITLE
Page URL segment counts more than All visits segment

### ISSUE THREAD

**Issue by mibto** [piwik/piwik#12313]
Hi :)
I have the same issue than: 
https://forum.piwik.org/t/page-url-segment-counts-more-than-all-visits-segment/16621

![bildschirmfoto zu 2017-11-30 17-04-35](https://user-images.githubusercontent.com/5446003/33440952-b1076de2-d5f1-11e7-925e-f31ce7283678.png)
![bildschirmfoto zu 2017-11-30 17-04-12](https://user-images.githubusercontent.com/5446003/33440953-b11f3206-d5f1-11e7-9bd7-1bb515601d96.png)

Piwik version: 3.2.0
MySQL version: 5.5.5
PHP version: 5.6.30-0+deb8u1 

Many thanks in advance!

**Comment by mibto** [comment]
any updates?

**Comment by tsteur** [comment]
This is not quite the same issue here and Piwik currently has some limitations when it comes to segmenting actions on non-core plugins. We'll have a look at it. I will close this issue for now and recommend you get in touch via contact at innocraft.com (someone is having a look though already)

**Comment by tsteur** [comment]
FYI: You can expect an update soon :)
