### ISSUE TITLE
[privacy] stop piwik tracking local pc file path when saving html page

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#12318]
Hi,

For increased privacy reasons I wish to stop Piwik recording entire file path when someone saves the web page (e.g. in html format).

Please look at the provided screenshot, I can see sensitive information like visitor's PC User name, and some private folders as well.

I don't want my Piwik track all that! It's ok that I know if some webpage was downloaded (cool! that means it wasn't written for nothing), but I don't really need entire private info from their freaking computer.

![piwik-tracking-local-pc-file-path](https://user-images.githubusercontent.com/5383059/33519741-8032ad04-d7ad-11e7-811c-db9fd82c5c30.png)

Thanks :)

**Comment by RMastop** [comment]
Hi Dev-101,

In site settings, there is a checkbox that would correct this. It only tracks visits when the URL is one of the known URLs you have set as known URLs

Cheers,
Richard

**Comment by dev-101** [comment]
Hi Richard,

I know about this option (and thought it was checked), but I didn't know it was related with file path tracking as well.

Thanks!
