### ISSUE TITLE
API: Actions.getDownload always returns empty result

### ISSUE THREAD

**Issue by renefreund** [piwik/piwik#12317]
Hello,

Piwik-Version: 3.2.0
MySQL-Version: 5.7.20
PHP-Version: 7.0.22-0ubuntu0.16.04.1
Only Standardplugins activated.

It seems the API-Method Actions.getDownload is broken and always return an empty result. I haven't found any related issue so i open this one.

Example URL:
https://piwik.domain-tld/piwik/?module=API&method=Actions.getDownload&idSite=1&downloadUrl=https%3A%2F%2Fwww.domain.tld%2Fdownload.pdf&period=year&date=2017&format=xml&token_auth=VALID_TOKEN

Better read:

```
https://piwik.domain-tld/piwik/
?module=API
&method=Actions.getDownload
&idSite=1
&downloadUrl=https%3A%2F%2Fwww.domain.tld%2Fdownload.pdf
&period=year
&date=2017
&format=xml
&token_auth=VALID_TOKEN
```

The Response is:
`<result/>`

idSite & token_auth are correct in my case. The download URL is an encoded URL of a file that is downloaded several times the last days and also appears in our archived reports for last weeks/months etc. The URL is in table piwik_log_action

apache-error.log don't show anything.

Additional Question:
Even if the API work: Would i get the exact count of downloads for (in this example) Year 2017 or do i only get the counts that any archived reports would show for this downloadurl? Like, the downloadurl is in the "other" count it would not count in my API call?

Greetings,

René

**Comment by sgiehl** [comment]
That should work. See for example https://demo.piwik.org/index.php?module=API&method=Actions.getDownload&downloadUrl=http%3A%2F%2Fgeolite.maxmind.com%2Fdownload%2Fgeoip%2Fdatabase%2FGeoLiteCity.dat.gz&idSite=7&period=year&date=yesterday&format=JSON&token_auth=anonymous

**Comment by renefreund** [comment]
After some Testing i got why now result show up. If the Download-Url isnt in the archieved report for the requested time/time-period (in my case year/2017) it won't show up.

It seems i need to rebuild my reports like https://piwik.org/faq/how-to/faq_54/ suggest.

Greetings,

René
