### ISSUE TITLE
Map Border Error

### ISSUE THREAD

**Issue by superwg1984** [piwik/piwik#12315]
![image](https://user-images.githubusercontent.com/9349029/33465958-cd88582a-d685-11e7-8259-7714ecc001d0.png)

It is recommended to use http://www.openstreetmap.org/
Avoid regional disputes
like https://grafana.com/

**Comment by fdellwing** [comment]
I don't quite see what the problem is?

**Comment by sgiehl** [comment]
This is an outdated screenshot of Piwik. We did not yet have time to update all screenshots on piwik.org. This will be done in #7269 and #7106
