### ISSUE TITLE
Update to 3.2.1 not found

### ISSUE THREAD

**Issue by buzanits** [piwik/piwik#12335]
I have two installations of piwik. One is correctly updating to 3.2.1. The other is showing an error: Your version 3.2.0 is up to date. Previous updates worked well with both installations.
![piwik](https://user-images.githubusercontent.com/9774538/33654241-ce959cb2-da6f-11e7-96c5-7de59213df5d.png)

**Comment by sgiehl** [comment]
Does that error show up when you click the update button? Or where did you get that screen?

**Comment by buzanits** [comment]
I pasted the URL from the working installation into the other installation (the part after the server name).

**Comment by sgiehl** [comment]
the latest release version might be cached, so try checking for an update in Piwik admin directly.

**Comment by buzanits** [comment]
Yes, that worked! Odd, that both installations have different cache times. They were installed and upgraded at the same time... Thanks for the help!

**Comment by buzanits** [comment]
Yes, that worked! Odd, that both installations have different cache times. They were installed and upgraded at the same time... Thanks for the help!

**Comment by Findus23** [comment]
Does Piwik check for an update when you manually visit `/index.php?module=CoreUpdater&action=newVersionAvailable`?

**Comment by buzanits** [comment]
Then the same message appears. But now I already updated to 3.2.1...
