### ISSUE TITLE
;jsessionid is not removed from url

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#1670]
Piwik uses parse_url to split the url, then the excluded parameters are removed from the query-Result.

The problem is, that the ;jsessionid=... is still in the path-Result because it is separated by ; instead of ?
Example url: http://www.example.com/some/site.jsp;jsessionid=1234?param1=value&param2=value

What's the best way to resolve this problem? Just replace/extend the parse_url function?

**Comment by sgiehl** [comment]
This was fixed in 2.16.1. See https://github.com/piwik/piwik/blob/3.x-dev/CHANGELOG.md#new-features-4
