### ISSUE TITLE
Send mail uses password-reset as user instead of assigned user in config

### ISSUE THREAD

**Issue by igm-jl** [piwik/piwik#16825]
I have set all my credentials and mail user to the no-reply@<companyname>.<tld> but in the logs it keeps wanting to use password-reset@<companyname>.<tld> (after enabling mailer debug and reading the issues returned).

Office365 (or at least my configuration of) blocks you from sending emails from a different user account so because Matomo is trying to force sending it as password-reset instead of the actual user I put into the config, the authentication fails.

I was able to get the mailer to work by adding $phpMailer->setFrom() to the actual email address that needed to be authenticated against in /core/Mail/Transport.php' prior to return $phpMailer->send().

It might make sense to either only use the actual authentication email address (as one would expect the default behaviour would be) OR to provide an option to override this in the settings page.

**Comment by sgiehl** [comment]
@igm-jl you can set this config values to adjust the email address password requests are sent from:

https://github.com/matomo-org/matomo/blob/375dd9f6933dcf7eeb37df9d2d9f44d16f35a277/config/global.ini.php#L415-L425
