### ISSUE TITLE
Unknown column 'log_visit.config_director' in 'field list' - in plugin DevicePlugins

### ISSUE THREAD

**Issue by C0rn3j** [piwik/piwik#16827]
After upgrading from 3.14.1 to 4.0.1, I run into this error in the web app's 'Visits Over Time' and 'Channel Types' tabs.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_visit.config_director' in 'field list' - in plugin DevicePlugins.
```
```
nginx-mainline 1.19.3
php 7.4.13
mariadb 10.5.8
```
This looks like the same issue as https://forum.matomo.org/t/database-issues-after-auto-upgrade-to-matomo-4-0-0/39509/4 but I did update via CLI, with the catch that I ran into #16824 first.

**Comment by sgiehl** [comment]
That column has been dropped on purpose. Might it be possible that some files were not updated correctly?
Maybe try downloading the release and replacing the files

**Comment by C0rn3j** [comment]
Actually unsure what happened here.

I reinstalled the package, now supposedly taking 10MB less space, rebooted the server and issue is gone.
