### ISSUE TITLE
matomo 3.14.1 Widgetize function in iframe Unable to log in automatically

### ISSUE THREAD

**Issue by JueMeiAlg** [piwik/piwik#16833]
https://domain.com/index.php?module=Widgetize&action=iframe&moduleToWidgetize=HeatmapSessionRecording&actionToWidgetize=showHeatmap&idSiteHsr=1&useDateUrl=0&idSite=3&period=day&date=yesterday&token_auth=XXX

this my Access url format 
![image](https://user-images.githubusercontent.com/34858740/100541699-78dec480-3280-11eb-9fab-9324fa76645d.png)

enable_framed_pages = 1
enable_framed_logins = 1
enable_framed_settings = 1

this my setting

What else can I do to solve this problem

**Comment by JueMeiAlg** [comment]
If this address is not opened in iframe, it can be accessed successfully by individual access

**Comment by tsteur** [comment]
Hi @JueMeiAlg as this question is related to a premium feature could you contact our support instead at shop@innocraft.com? We only handle issues for the free core part of Matomo in this issue tracker unfortunately. When you email the support, it would be great to also provide information what browser you are using. Thanks for this
