### ISSUE TITLE
The parameter ‘confirmPassword’ isn’t set in the Request

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#16847]
reported in https://forum.matomo.org/t/warning-message-on-new-installation/39557/3 (futher down)

> I do however have an issue trying to install the google analytics plugin as i get this server error either trying to access the marketplace or import a zip file. Any ideas on that one? From what I read in the other article, it seems the issues may have been related?
>
> ( 500 - Internal server error. ### There is a problem with the resource you are looking for, and it cannot be displayed.)

`ERROR Piwik\ExceptionHandler[2020-12-01 11:04:09 UTC] [ffda2] Uncaught exception: C:\inetpub\wwwroot\matomo\core\Common.php(535): The parameter ‘confirmPassword’ isn’t set in the Request, and a default value wasn’t provided.`
`ERROR Piwik\ExceptionHandler[2020-12-01 11:04:09 UTC] [ffda2] The parameter ‘confirmPassword’ isn’t set in the Request, and a default value wasn’t provided.`

https://github.com/matomo-org/matomo/blob/f4dd5624a1f56602ea449668a40e00b70f0e28f4/core/Common.php#L535
This is most likely called from 
https://github.com/matomo-org/matomo/blob/7585967cbd80d7869f57a9adc69c02e8d14cbc33/plugins/CorePluginsAdmin/Controller.php#L120

**Comment by sgiehl** [comment]
I'm able to reproduce that locally. Seems the form data is actually not send with the request. Will look into it.

**Comment by sgiehl** [comment]
Guess that might be an issue of `post_max_size` php ini setting being too low. The plugin has 12 MB, but the default setting has 8M. Will create a simple PR that shows an error when someone wants to upload a file that is bigger than post_max_size.
But guess that's nothing we need for 4.0.3, so moving out of the milestone for now

**Comment by tsteur** [comment]
Could we in general simply check if that parameter is missing and if so, indicate that likely they need to increase `post_max_size` or install plugin through the marketplace instead of adjusting a plugin?

**Comment by tsteur** [comment]
I see there's already a PR now
