### ISSUE TITLE
Mysqli prepare error after upgrade to v4.0.3 (Unknown column 'log_conversion.config_browser_name')

### ISSUE THREAD

**Issue by bittner** [piwik/piwik#16868]
I have just upgraded from v3.14.1 to v4.0.3 over Matomo's web interface (after being notified by email).

After automatically downloading and installing the new version Matomo reported a few "unrecognized files" and prompted me to delete them on the target system: (indentation mine)

```console
rm -Rf \
   ~/www/analytics/home/libs/bower_components \
   ~/www/analytics/home/vendor/container-interop \
   ~/www/analytics/home/vendor/piwik \
   ~/www/analytics/home/vendor/twig/twig/ext
rm ~/www/analytics/home/misc/others/ExamplePiwikTracker.php
```

The subsequent update of the database schema (I assume) took a little bit longer than in all the upgrades before (I started with < v2.4.9 in 2014).

## Broken dashboard widgets

Afterwards I could log in just as normal, but I notice a red warning banner for a fraction of a second after the login, and now some widgets are broken:

![image](https://user-images.githubusercontent.com/665072/100916114-9d7faa00-34d5-11eb-8f3b-2e9ceba91590.png)

![image](https://user-images.githubusercontent.com/665072/100916184-b25c3d80-34d5-11eb-8927-ac52ef12cb0b.png)

![image](https://user-images.githubusercontent.com/665072/100916234-c607a400-34d5-11eb-8cd4-de46938d0217.png)

## Incompatible ExampleXxx plugins

The System Check complains about a "ExampleLogTables" plugin that could not be loaded due to incompatibility:

> Das Plugin ExampleLogTables konnte nicht geladen werden, da folgende Abhängigkeiten fehlen: ExampleLogTables benötigt Piwik <4.0.0-b1 Bitte kontaktieren Sie Ihren Matomo Administrator.

Note that I have 3 websites that I track with one Matomo instance. Interestingly, the widgets of the first website are **not** affected, but the other two are. And the dashboard for "All websites" reports serious problems:

![image](https://user-images.githubusercontent.com/665072/100916865-a4f38300-34d6-11eb-89e5-23bf152d72bd.png)

## Uninstall links missing

Can I uninstall all the old "ExampleXxx" plugins and install compatible ones to fix this? The _Adminstration_ ➜ _System_ ➜ _Plugins_ page doesn't show an "Uninstall" link for most of them. :worried:

**Comment by Findus23** [comment]
Hi,

You can delete the Example* plugins, they are no longer shipped with Matomo 4.

**Comment by tsteur** [comment]
To fix the browser column issue could you run the following SQL statement and check if it works afterwards @bittner ?

`ALTER TABLE log_conversion ADD COLUMN config_browser_name VARCHAR(40) NULL;`

If you have DB prefix configured then you might need to replace `log_conversion` with eg `piwik_log_conversion`. This should add the column and hopefully no other columns are missing. Let me know if you get a different error afterwards.

A long upgrade time is expected unfortunately in this major Matomo upgrade since we made changes to the database tables that store the raw data.

Any plugin in `plugins` directory that start with `Example` can be deleted. The next Matomo 4.0.4 update will do this also automatically. The 4.0.4 update should be due likely tomorrow.

Hope this helps. Let me know if not and we'll reopen the issue.

**Comment by bittner** [comment]
Thank you, @tsteur, adding the table column fixed the issue. :1st_place_medal: 

I also deleted the `Example` plugins on the file system. For now, my Matomo instance seems to work fine again.

Thanks again! :bow: :trophy:

**Comment by tsteur** [comment]
Great, glad this worked @bittner 👍

**Comment by datango** [comment]
I still have the problem that the column config_browser_name is not added by console core:update. I had to add it manualy. Otherwise console core:archive produces errors. (Matomo 4.1.1)

**Comment by phaser32** [comment]
> To fix the browser column issue could you run the following SQL statement and check if it works afterwards @bittner ?
> 
> `ALTER TABLE log_conversion ADD COLUMN config_browser_name VARCHAR(40) NULL;`
> 
> If you have DB prefix configured then you might need to replace `log_conversion` with eg `piwik_log_conversion`. This should add the column and hopefully no other columns are missing. Let me know if you get a different error afterwards.
> 
> A long upgrade time is expected unfortunately in this major Matomo upgrade since we made changes to the database tables that store the raw data.
> 
> Any plugin in `plugins` directory that start with `Example` can be deleted. The next Matomo 4.0.4 update will do this also automatically. The 4.0.4 update should be due likely tomorrow.
> 
> Hope this helps. Let me know if not and we'll reopen the issue.

THANK YOU SO MUCH !!! This solve the issue!!
