### ISSUE TITLE
Error on Auro Archive

### ISSUE THREAD

**Issue by JE4GLE** [piwik/piwik#16862]
Hello,

after updating to version 4.0.3, I receive the following error when calling my cron archive URL:

> ERROR Piwik\FrontController[2020-12-02 10:38:41 UTC] [92c61] Uncaught exception: Error: Call to a member function isSkipSegmentsForToday() on null in /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/CronArchive.php:518
  Stack trace:
  #0 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/CronArchive.php(400): Piwik\CronArchive->generateUrlToArchiveFromArchiveInfo(Array)
  #1 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/CronArchive.php(373): Piwik\CronArchive->launchArchivingFor(Array, Object(Piwik\CronArchive\QueueConsumer))
  #2 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/CronArchive.php(260): Piwik\CronArchive->run()
  #3 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/Access.php(664): Piwik\CronArchive->Piwik\{closure}()
  #4 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/CronArchive.php(266): Piwik\Access::doAsSuperUser(Object(Closure))
  #5 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/plugins/CoreAdminHome/API.php(194): Piwik\CronArchive->main()
  #6 [internal function]: Piwik\Plugins\CoreAdminHome\API->runCronArchiving()
  #7 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/API/Proxy.php(244): call_user_func_array(Array, Array)
  #8 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
  #9 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/API/Proxy.php(335): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
  #10 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/API/Request.php(266): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'runCronArchivin...', Array)
  #11 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/plugins/API/Controller.php(46): Piwik\API\Request->process()
  #12 [internal function]: Piwik\Plugins\API\Controller->index()
  #13 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/FrontController.php(605): call_user_func_array(Array, Array)
  #14 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/FrontController.php(166): Piwik\FrontController->doDispatch('API', false, Array)
  #15 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/core/dispatch.php(32): Piwik\FrontController->dispatch()
  #16 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/index.php(25): require_once('/var/www/vhosts...')
  #17 /var/www/vhosts/h149549.web219.dogado.net/httpdocs/matomo/misc/cron/archive.php(67): require_once('/var/www/vhosts...')
  #18 {main}
Error: Call to a member function isSkipSegmentsForToday() on null

Does anyone have a solution, or do I have to wait for a fix?
Thanks!

**Comment by sgiehl** [comment]
Hi @JE4GLE Thanks for creating the issue. This might be something we need to fix in the code.

@diosmosis could you check if an additional check is needed. Seems the archiveFilter is not set in all cases maybe? Or is that maybe already included in one of the pending archiving PRs?
