### ISSUE TITLE
Call to undefined method MaxMind\Db\Reader::getWithPrefixLen()

### ISSUE THREAD

**Issue by bst2002git** [piwik/piwik#16877]
I'v updated to matomo 4.0.3 from 3.14.1.
The error is 
Call to undefined method MaxMind\Db\Reader::getWithPrefixLen() in vendor/geoip2/geoip2/src/Database/Reader.php line 232    

i think some missing dependencies or something got wrong on update, but i do not know where to look for
ore something is wrong in the autoload.php...

i don't know if this is related, but when i try in the web root of matomo

 composer -vv show geoip2/geoip2 --all

  [UnexpectedValueException]
  Unknown package has no name defined

**Comment by sgiehl** [comment]
How did you do the update? Maybe reuploading the files (or at least the vendor directory) might help.

**Comment by bst2002git** [comment]
Hello @sgiehl 
i updated via the Web-Interface and then via the cli: console core:update
no errors occurred

**Comment by sgiehl** [comment]
Please try reuploading the vendor directory from the build package.
Or do you maybe have a php cache running? Maybe an old version of that file was still cached.

**Comment by bst2002git** [comment]
Hello,

i think this is the problem

php72-php-maxminddb-1.4.1-1.el6.remi.x86_64:
This optional PHP C Extension is a drop-in replacement for
MaxMind\Db\Reader.

**Comment by bst2002git** [comment]
updated to php72-php-maxminddb-1.8.0-2.el6.remi.x86_64
and works!
