### ISSUE TITLE
Hide Comparison feature on All Websites dashboard 

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#16879]
At the moment it looks as though the Comparison feature does not work on the All Websites dashboard.

1. When going to the All Websites dashboard through the top menu it does not show an option to do a comparison when viewing the All Websites dashboard from here.
![image](https://user-images.githubusercontent.com/20905821/101080252-6ad8cd00-360d-11eb-8ed5-c332d0ae63ba.png)

2. When going to the All Websites dashboard through the Site Selector the option to compare shows, but when selecting a period to compare to there is no comparison data shown in the report.
![image](https://user-images.githubusercontent.com/20905821/101080300-7e843380-360d-11eb-917c-fc2dc1686263.png)
![image](https://user-images.githubusercontent.com/20905821/101080337-8cd24f80-360d-11eb-8c6d-fec114660bb9.png)
(Screenshots were taken from demo.matomo.cloud)

We can either remove this option from showing on the All Websites dashboard when navigating to it from the Site Selector, or we can implement the feature to work on the All Websites dashboard.

**Comment by tsteur** [comment]
It should not show up in the date picker in all websites 👍  not sure if it's the case in other places too
