### ISSUE TITLE
Error during DB Update from 3.14.1 to 4.0.3 

### ISSUE THREAD

**Issue by ordilibre** [piwik/piwik#16874]
Hi,

Because of web UI update is failling, I try to update by CLI
> php /home/myaccount/websites/matomo/console core:update

After a good Dry Run, the effective job is stopped with this error :

> Executing ALTER TABLE 'stats_log_visit' ADD COLUMN 'visitor_seconds_since_first' INT(11) UNSIGNED NULL, ADD COLUMN 'visitor_seconds_since_order' INT(11) UNSIGNED NULL, ADD COLUMN 'visitor_seconds_since_last' INT(11) UNSIGNED NULL, ADD COLUMN 'profilable' TINYINT(1) NULL;... 
>  [X] Critical Error during the update process:
> 
> /home/aquinetic334/websites/matomo/core/Updates/4.0.0-b1.php:
> Error trying to execute the migration 'ALTER TABLE 'stats_log_visit' ADD COLUMN 'visitor_seconds_since_first' INT(11) UNSIGNED NULL, ADD COLUMN 'visitor_seconds_since_order' INT(11) UNSIGNED NULL, ADD COLUMN 'visitor_seconds_since_last' INT(11) UNSIGNED NULL, ADD COLUMN 'profilable' TINYINT(1) NULL;'.
> The error was: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large
. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

full trace is [MatomoUpdateError.txt](https://github.com/matomo-org/matomo/files/5635028/MatomoUpdateError.txt)

I have re-run the update 3 times with always the same result.

- Is the "1118 Row size too large" message the important information ?
- Is it normal for Matomo to try to increase the row size of this table to more than 8192 ?
- How can I increase this limit in the database, outside of Matomo ?

thank you for any help

**Comment by sgiehl** [comment]
See #16810 or our FAQ: https://matomo.org/faq/troubleshooting/how-do-i-fix-the-error-1118-row-size-too-large-the-maximum-row-size-for-the-used-table-type-not-counting-blobs-is-8126/

**Comment by ordilibre** [comment]
Many thanks **sgiehl**, my problem is now resolved.
Sorry for not having found the answer directly.
