### ISSUE TITLE
SQLSTATE[42S22]: Column not found

### ISSUE THREAD

**Issue by kantel** [piwik/piwik#16888]
I just updated to Matomo 4.0.4 and now I got the error message: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_visit.config_director' in 'field list' - in plugin DevicePlugins.` on nearly all widgets. Only the visitors log works fine.

![Bildschirmfoto 2020-12-05 um 14 53 43](https://user-images.githubusercontent.com/1219909/101245011-3434ac80-370a-11eb-8da7-a516be84b318.png)

Need urgent help.

**Comment by Findus23** [comment]
Hi,

This sounds like https://github.com/matomo-org/matomo/issues/16827

**Comment by kantel** [comment]
I tried a manual reinstall but the error isn't gone.

**Comment by sgiehl** [comment]
@kantel could you check if this file exists for you:  `plugins/DevicePlugins/Columns/PluginDirector.php`

**Comment by kantel** [comment]
Solved! Matomo 4.0.4 is working again. See [here](http://blog.schockwellenreiter.de/2020/12/2020120502.html).
