### ISSUE TITLE
Page generation time not being tracked after 4.x upgrade

### ISSUE THREAD

**Issue by HatBeardZero** [piwik/piwik#16884]
I updated my instance from 3.14.0 to 4.0.4 and now page generation time is not being tracked.

Any thoughts on what could cause this?

**Comment by tsteur** [comment]
Hi @HatBeardZero we have removed this feature in Matomo 4 and replaced it with the new page performance reports see https://matomo.org/faq/how-to/how-do-i-see-page-performance-reports/ So this is expected and we're now tracking more detailed insights.

**Comment by HatBeardZero** [comment]
it still shows up on the report pages though under visits overview on the dashboard, and visits->overview

**Comment by tsteur** [comment]
@HatBeardZero it still shows it so you can still view previously tracked data.

@sgiehl do we remove the column for dates after the upgrade to Matomo 4 (not too important but could avoid confusion)

**Comment by fvdm** [comment]
@tsteur I love the new performance stats, but also like to keep the old metrics for comparison over time. Can't the old data be merged with 'Avg. page load time' ?

**Comment by sgiehl** [comment]
@tsteur the metric should actually be removed automatically if the sum of page generation times is 0. See https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/Actions/Columns/Metrics/AveragePageGenerationTime.php#L71-L103   Not sure if that actually work correctly.

@fvdm  Guess we could merge them. But actually they are not that good comparable in most cases. Guess most people tracked the time the server needed to generate the response. The new page performace metrics are also including timtings for network and browser rendering, which likely were not included before...

**Comment by peterbo** [comment]
It's probably still included in the graph selectors or will the list of selectable metrics also get filtered then? In general (sorry for hijacking this issue), it'd be great to have the avg. page load time also as a graph plottable metric as a successor of the avg. page generation time.

**Comment by mattab** [comment]
> It's probably still included in the graph selectors or will the list of selectable metrics also get filtered then? In general (sorry for hijacking this issue), it'd be great to have the avg. page load time also as a graph plottable metric as a successor of the avg. page generation time.

@peterbo thanks for the suggestion! created follow-up issue https://github.com/matomo-org/matomo/issues/17010
