### ISSUE TITLE
Error 500 after new Update

### ISSUE THREAD

**Issue by manuelw99** [piwik/piwik#16891]
Hi,

after updating my matomo I got an error 500.

In my PHP-Logs, i get this message: (i clicked on the button update matomo on the page "Database Upgrade Required"

Access level to Piwik\Plugins\ExampleTracker\Columns\ExampleActionDimension::configureSegments() must be public (as in class Piwik\Columns\Dimension)
matomo/plugins/ExampleTracker/Columns/ExampleActionDimension.php Row 57

**Comment by Findus23** [comment]
Hi,

Can you please try deleting the ExampleTracker plugin (plugins/ExampleTracker). It is no longer included in Matomo 4 and it seems like the old files are breaking the remaining new code.
