### ISSUE TITLE
MultiSites as matomo homepage

### ISSUE THREAD

**Issue by 1000i100** [piwik/piwik#16914]
I'm hosting somes website on my server and i've added a matomo to track activity on them ( parsing server log with https://github.com/matomo-org/matomo-log-analytics ).

When i log-in matomo, i would like to go to the Multi Sites dashboard rather than the first i've added in matomo webui.
And the same when i clic on the top left logo to go back to home, i would like to go to the Multi Sites dashboard.

Is-it possible ?

**Comment by tsteur** [comment]
@1000i100 you can change this in personal settings:

![image](https://user-images.githubusercontent.com/273120/101538141-88d57180-3a01-11eb-90da-97e64cf91245.png)
 It also works re the logo.

**Comment by 1000i100** [comment]
Thank-you !!!
