### ISSUE TITLE
Call to a member function setColumn() on boolean in plugins/Referrers/API.php

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#16919]
Error on Cloud:

 Error: {"message":"Call to a member function setColumn() on boolean","file":"\/var\/www\/html\/plugins\/Referrers\/API.php","line":765,"request_id":"5d68e","backtrace":" on \/var\/www\/html\/plugins\/Referrers\/API.php(765)\n#0 \/var\/www\/html\/plugins\/Referrers\/API.php(770): Piwik\\Plugins\\Referrers\\API->mergeNumericArchives(Object(Piwik\\DataTable), Object(Piwik\\DataTable\\Simple))\n#1 \/var\/www\/html\/plugins\/Referrers\/API.php(51): Piwik\\Plugins\\Referrers\\API->mergeNumericArchives(Object(Piwik\\DataTable\\Map), Object(Piwik\\DataTable\\Map))\n#2 [internal function]: Piwik\\Plugins\\Referrers\\API->get('3', 'day', '2019-04-21,2020...', false, 'Referrers_visit...')\n#3 \/var\/www\/html\/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#5 \/var\/www\/html\/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#6 \/var\/www\/html\/plugins\/API\/API.php(374): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'get', Array)\n#7 [internal function]: Piwik\\Plugins\\API\\API->get('3', 'day', '2019-04-21,2020...', false, Array)\n#8 \/var\/www\/html\/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#9 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#10 \/var\/www\/html\/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#11 \/var\/www\/html\/core\/Plugin\/Visualization.php(341): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'get', Array)\n#12 \/var\/www\/html\/core\/Plugin\/Visualization.php(188): Piwik\\Plugin\\Visualization->loadDataTableFromAPI()\n#13 \/var\/www\/html\/core\/Plugin\/Controller.php(247): Piwik\\Plugin\\Visualization->render()\n#14 \/var\/www\/html\/plugins\/VisitsSummary\/Controller.php(128): Piwik\\Plugin\\Controller->renderView(Object(Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution))\n#15 [internal function]: Piwik\\Plugins\\VisitsSummary\\Controller->getEvolutionGraph()\n#16 \/var\/www\/html\/core\/FrontController.php(605): call_user_func_array(Array, Array)\n#17 \/var\/www\/html\/core\/FrontController.php(166): Piwik\\FrontController->doDispatch('VisitsSummary', 'getEvolutionGra...', Array)\n#18 \/var\/www\/html\/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#19 \/var\/www\/html\/index.php(25): require_once('\/var\/www\/html\/c...')\n#20 {main}"}

URL: https://x.matomo.cloud/index.php?date=2020-09-01&forceView=1&viewDataTable=graphEvolution&module=VisitsSummary&action=getEvolutionGraph&disableLink=0&widget=1&evolution_day_last_n=500&idSite=3&period=day

**Comment by sgiehl** [comment]
Not able to reproduce locally, but guess that only happens under certain circumstances. Found a potential fix.
