### ISSUE TITLE
Call to a member function getDateStart() on boolean DataTable/Renderer/Rss.php

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#16918]
Error seen on Cloud:

 Error: {"message":"Call to a member function getDateStart() on boolean","file":"\/var\/www\/html\/core\/DataTable\/Renderer\/Rss.php","line":62,"request_id":"1e86d","backtrace":" on \/var\/www\/html\/core\/DataTable\/Renderer\/Rss.php(62)\n#0 \/var\/www\/html\/core\/DataTable\/Renderer\/Rss.php(34): Piwik\\DataTable\\Renderer\\Rss->renderTable(Object(Piwik\\DataTable\\Map))\n#1 \/var\/www\/html\/plugins\/API\/Renderer\/Rss.php(40): Piwik\\DataTable\\Renderer\\Rss->render()\n#2 \/var\/www\/html\/core\/API\/ResponseBuilder.php(193): Piwik\\Plugins\\API\\Renderer\\Rss->renderDataTable(Object(Piwik\\DataTable\\Map))\n#3 \/var\/www\/html\/core\/API\/ResponseBuilder.php(104): Piwik\\API\\ResponseBuilder->handleDataTable(Object(Piwik\\DataTable\\Map))\n#4 \/var\/www\/html\/core\/API\/Request.php(272): Piwik\\API\\ResponseBuilder->getResponse(Object(Piwik\\DataTable\\Map), 'Actions', 'getPageUrl')\n#5 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Request->Piwik\\API\\{closure}()\n#6 \/var\/www\/html\/core\/API\/Request.php(273): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#7 \/var\/www\/html\/plugins\/API\/Controller.php(46): Piwik\\API\\Request->process()\n#8 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#9 \/var\/www\/html\/core\/FrontController.php(605): call_user_func_array(Array, Array)\n#10 \/var\/www\/html\/core\/FrontController.php(166): Piwik\\FrontController->doDispatch('API', false, Array)\n#11 \/var\/www\/html\/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#12 \/var\/www\/html\/index.php(25): require_once('\/var\/www\/html\/c...')\n#13 {main}"}

URL: https://xyz.matomo.cloud//?module=API&format=rss&pageUrl=%xxxxxxxxxxxxxxxx&idSite=1&period=day&date=last7&token_auth=XYZANONYMIZED&method=Actions.getPageUrl

Referrer:

GET: {"module":"API","format":"rss","pageUrl":"\xxxxxxxxxxxx","idSite":"1","period":"day","date":"last7","token_auth":"XYZANONYMIZED","method":"Actions.getPageUrl","filter_limit":100}

Time: 2020-12-09 09:09:38

**Comment by sgiehl** [comment]
Seems that error occurs when filtering for a `pageUrl` that does not occur in one of the returned periods. Will check if it's easy to fix
