### ISSUE TITLE
core:convert-to-utf8mb4 disables tracking

### ISSUE THREAD

**Issue by nkfilis** [piwik/piwik#16928]
As per the documentation https://matomo.org/docs/update/#the-manual-three-step-update, it's possible to update matomo and run the database migrations without disabling tracking. 
However, running `core:convert-to-utf8mb4` disables tracking completely, runs the utf8mb4 migrations and enables tracking again.
Maybe there could be a switch for those who want to continue tracking thru the Queued Tracking Plugin, since running those utf8mb4 migrations takes quite some time, which makes people lose quite some data.

**Comment by sgiehl** [comment]
@nkfilis the command should have an option `--keep-tracking` to achieve that.
