### ISSUE TITLE
import_logs.py instructs to use --force-all-periods but core:archive says that switch DNE

### ISSUE THREAD

**Issue by psec** [piwik/piwik#16931]
Output from import_logs.py:

<pre>Processing your log data
------------------------

    In order for your logs to be processed by Matomo, you may need to run the following command:
     ./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='URL'</pre>

Corresponding console output:

<pre>ERROR [2020-12-10 03:09:40] 5554  Uncaught exception: /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php(213): The "--force-all-periods" option does not exist.
The "--force-all-periods" option does not exist.

                                                    
  [RuntimeException]                                
  The "--force-all-periods" option does not exist. 
</pre>

**Comment by sgiehl** [comment]
Thanks for creating the issue. Seems we need to adjust the command that is suggested to run

**Comment by mattab** [comment]
btw it would be great to check across the whole codebase, as well as on the website (i've tried removing it from a few places on the site already but maybe more are left)
