### ISSUE TITLE
Other installation options?

### ISSUE THREAD

**Issue by Flaburgan** [piwik/piwik#16948]
Hello, I'd like to install Matomo on my server but I am surprised to see only a tutorial asking me to install Php, Mysql etc by hand as in the past. Isn't there any snap package, or flatpack, or docker image, or anything?

**Comment by sgiehl** [comment]
There's an official docker image (https://github.com/matomo-org/docker) and some third parties are offering some other stuff as well.

**Comment by mattab** [comment]
See also https://matomo.org/faq/how-to-install/faq_108/
