### ISSUE TITLE
Non-English characters are not able to display in the report

### ISSUE THREAD

**Issue by Kkwong-wisdomir** [piwik/piwik#16945]
Hi @Richard Stark 

Some text sections are not displayed properly in the reports. Especially, the non-English characters are not able to display in the report. Kindly advise how to solve it.
We are currently using Matomo 3.5.1.

[431_20201214.pdf](https://github.com/matomo-org/matomo/files/5686233/431_20201214.pdf)
![ESR matomo](https://user-images.githubusercontent.com/75768179/102036073-e5b79a00-3dfc-11eb-882a-616c9e727a09.jpg)

Thanks,
Kiko Kwong

**Comment by tsteur** [comment]
Hi @Kkwong-wisdomir 

Have a look at https://matomo.org/faq/how-to-install/faq_142/ which should fix this problem.

If this doesn't fix the issue, you might need to upgrade to Matomo 4 and migrating your database to UTF8MB4 see https://matomo.org/faq/how-to-update/how-to-convert-the-database-to-utf8mb4-charset/

Hope this helps @Kkwong-wisdomir
