### ISSUE TITLE
Database upgrade row size error  on table piwik_log_visit

### ISSUE THREAD

**Issue by hahayidu** [piwik/piwik#16959]
Hi,

When upgrade to > Matomo database will be upgraded from version 3.14.1 to the new version 4.0.5.

I've seen an error in error log [mariadb]

> 2020-12-15  2:31:19 344 [ERROR] InnoDB: Cannot add field `custom_var_k4` in table `piwik`.`piwik_log_visit` because after adding it, the row size is 8671 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.

It is look like no problem with any visit record or reporting. core:update also successfully finished.

I'am not database expert but also I run following command for check db

>mariadb-check piwik -c

It's show all table OK

```
MariaDB [(none)]> SELECT VERSION();
+---------------------------+
| VERSION()                 |
+---------------------------+
| 10.3.27-MariaDB-0+deb10u1 |
+---------------------------+
```
My version is not affected following bug.

https://jira.mariadb.org/browse/MDEV-19292

I wanted to avoid problems in the future and to share information if anyone is affected.

This my test environment I can share more information for future analysis.

Thanks in advance for your support.

**Comment by tsteur** [comment]
Hi @hahayidu https://matomo.org/faq/troubleshooting/how-do-i-fix-the-error-1118-row-size-too-large-the-maximum-row-size-for-the-used-table-type-not-counting-blobs-is-8126/ should help 👍  Let us know if that's not the case and we'll be happy to reopen.
