### ISSUE TITLE
No data has been recorded yet, get set up below in Matomo Dashboard for Sharepoint 2013 site   

### ISSUE THREAD

**Issue by Pthakur17** [piwik/piwik#16961]
I implemented the Matomo to my Sharepoint 2013 site using the 3rd option given in the link []( https://matomo.org/faq/how-to-install/faq_19424/  ) But I don't see any data in Matomo Dashboard for mysite. 
Following the below step :
a) Get the tracking code for your website
log in to Matomo (Piwik) with your admin or Super User account
click on your username in the top-right menu, and click Settings to access the administration area
click on Tracking Code in the left menu
Copy the Tracking code

b) Add this Tracking code to SharePoint master page.
Edit your master page in ‘Advanced mode’ with SharePoint designer 2013
and paste/insert the Matomo Tracking code just before </head> tag.
Save-Check-in-publish/Approve the master page.

c) Check your Visitors data in Matomo
Under Visitors > Visits Log, select “Today” in the calendar, you can now see your visitors and interactions tracked in real-time.

**Comment by tsteur** [comment]
Hi @Pthakur17 do you mind asking this question in our forum https://forum.matomo.org/ ? Or if you are a support plan customer asking our support about this (see https://matomo.org/support-plans/ )? 

We generally don't answer questions or troubleshooting requests here but only handle bug reports and feature requests.

I suppose generally you refer to this guide? https://matomo.org/faq/how-to-install/faq_19424/

Any chance that you are familiar with browser developer tools? If so, you could check if the tracking code is actually embedded into the site. I could check this for you but I suppose we wouldn't be able to access your site. 

I suppose in the guide the first 2 options don't apply to you?
