### ISSUE TITLE
Update wikimedia/less.php dependency to v3.1.0 or above

### ISSUE THREAD

**Issue by MichaIng** [piwik/piwik#16981]
The following warning is logged when running the web UI updater:

WARNING | CoreUpdater | 2020-12-19 17:05:44 UTC | e415b | /var/www/matomo/vendor/wikimedia/less.php/lib/Less/Tree/Directive.php(20): Deprecated - Required parameter $rules follows optional parameter $value - Matomo 4.1.0-b2
-- | -- | -- | -- | --

This is likely a PHP8.0 related deprecation. I see now it is from an external dependency, where it has been fixed recently: https://github.com/wikimedia/less.php/commit/7b04e9236e29d13cfd574443a77ab09444b06122

So take this as a request to update the less.php dependency to v3.1.0 or above.

**Comment by sgiehl** [comment]
see #16976
