### ISSUE TITLE
core:archive reports "0 out of 4 archivers running currently" when --matomo-domain parameter is at the start of the command

### ISSUE THREAD

**Issue by fealXX** [piwik/piwik#16984]
I noticed our Cronlogs always said "0 out of 4 archivers running currently" - regardless of the actual number of running archivers.

This was, because our cron for the core:archive job had the matomo-domain parameter in front of the core:archive command:
`console --matomo-domain=my.matomodomain.com -vvv core:archive >> cron_daily.log`
but CronArchive.php checks for `strpos($process, 'console core:archive') !== false` in hasReachedMaxConcurrentArchivers().

Changing the check to `strpos($process, 'core:archive') !== false` reports the correct number of running archivers.

**Comment by tsteur** [comment]
Thanks for reporting this @fealXX
