### ISSUE TITLE
4.1.0 Data from "Channel Types" and others are showing Yesterday's data while some other part are showing today's data

### ISSUE THREAD

**Issue by esolix** [piwik/piwik#16999]
Matomo 4.1.0 (Upgraded from 4.0.5)

It was showing yesterday's analytics data rather than selected day (always showing data from a day before) on some part of the dashboard. Screenshot attached.

<img width="1250" alt="Screen Shot 2020-12-22 at 23 14 48" src="https://user-images.githubusercontent.com/24265629/102898748-4c981b80-44ad-11eb-803a-83cc93cf84b3.png">

Downgraded back to 4.0.5 and it is fixed again.

Thanks

**Comment by mox575** [comment]
I am seeing the same thing after the update. Right away I noticed on the Dashboard that the Visits for today were from yesterday's data. Visits over time is correct, but the visits overview is yesterdays total.

**Comment by sgiehl** [comment]
I'm not able to reproduce that locally

@esolix @mox575 Could you maybe give some more information:
* Does that only happen on the dashboard or is it happening on other report pages as well?
* When opening the page the browser sends separate requests for each report, could you check the network tab of the browser console if the requests for the reports are containing the correct date parameter
* Are you using the archiving cron to archive the reports or is that triggered by the browser?

**Comment by esolix** [comment]
1. It is happening to dashboard only
2. I have restored our instance (Let me clone it and retry to reproduce it from 4.05 to 4.1.0 upgrade in a moment.
3. Using cron

Will update this in a moment

**Comment by esolix** [comment]
> I'm not able to reproduce that locally
> 
> @esolix @mox575 Could you maybe give some more information:
> 
> * Does that only happen on the dashboard or is it happening on other report pages as well?
> * When opening the page the browser sends separate requests for each report, could you check the network tab of the browser console if the requests for the reports are containing the correct date parameter
> * Are you using the archiving cron to archive the reports or is that triggered by the browser?

Attached is the output, i tried to match it with the production server with 4.0.5 - Output is the same.

![Screen-Shot-2020-12-23-at-20 27 02](https://user-images.githubusercontent.com/24265629/102992097-eddeaa80-455d-11eb-9550-bf96edc12930.jpg)

Let me know if you need me to run some more test i will leave the dev instance on.

**Comment by sgiehl** [comment]
@esolix that's weird. Even the sparkline in the summary seems to have the correct values 🤔 
Have you looked through all requests if the date is the same? Does that only happen when viewing todays stats or are any reports showing the wrong date in other cases as well?
btw. which timezone is your matomo site configured for?

**Comment by esolix** [comment]
> @esolix that's weird. Even the sparkline in the summary seems to have the correct values 🤔
> Have you looked through all requests if the date is the same? Does that only happen when viewing todays stats or are any reports showing the wrong date in other cases as well?
> btw. which timezone is your matomo site configured for?

Yes I have, all the request seems to line up with the older version. It happens when viewing stats from any other day, so if I select 20th, it will show the 19th data. So it is wrong as well.

Timezone is setup for CST time (Central) and I am in Tokyo time.

**Comment by sgiehl** [comment]
@esolix Ok. Thanks. That seems to be a timezone issue. I was able to reproduce that by setting up a site in CST timezone and generating some fake visits.
Will have a quick look if I'm able to figure out the reason.

**Comment by esolix** [comment]
> @esolix Ok. Thanks. That seems to be a timezone issue. I was able to reproduce that by setting up a site in CST timezone and generating some fake visits.
> Will have a quick look if I'm able to figure out the reason.

Thank you!

**Comment by sgiehl** [comment]
Seems to be a regression from this change:
https://github.com/matomo-org/matomo/pull/16830/files#diff-3f15e6e8235bb796794c812a3c85b929cb82ae02f1dfbcd6e74e105d1fb31a6bL170-R170

**Comment by Pipwizard** [comment]
I just took the files from the 4.0.5 core/Period folder and overwrote the files in 4.1.0 core/Period folder and it now works.

So it's definitely a problem in core/Period

**Comment by mox575** [comment]
Just FYI, I am in California, Pacific Standard Time

**Comment by mox575** [comment]
I noticed on my Goals, the same issue. 
![Screenshot (12)](https://user-images.githubusercontent.com/55412642/103022119-2c457c80-4500-11eb-887e-91715838a2ea.png)

**Comment by esolix** [comment]
> Seems to be a regression from this change:
> https://github.com/matomo-org/matomo/pull/16830/files#diff-3f15e6e8235bb796794c812a3c85b929cb82ae02f1dfbcd6e74e105d1fb31a6bL170-R170

The fix works with 

index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=2020-12-23&segment=&category=Dashboard_Dashboard&subcategory=1

but default still show yesterday's data

index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=today&segment=&category=Dashboard_Dashboard&subcategory=1

Thanks for the quick patch!

**Comment by BasketballBuzz** [comment]
I'm also having this same issue. How do I fix this?

**Comment by Findus23** [comment]
Hi @BasketballBuzz,

Have you tried applying the changes from #17008 (you can ignore the ones from ` tests/PHPUnit/Integration/Period/FactoryTest.php`)?

**Comment by esolix** [comment]
The fix does work for URL string that contains date, but "Today" query string (which is default dashboard URL) still show the same issue

**Not working**
index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=today&segment=&category=Dashboard_Dashboard&subcategory=1

**Working by specifying today's date**
index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=2021-01-15&segment=&category=Dashboard_Dashboard&subcategory=1

Thanks
