### ISSUE TITLE
When showing the Export URL, clarify that users must use their app token (instead of displaying a token_auth that only works in their session)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#16990]
After Matomo 4 upgrade, we got many reports that the "Export URL" feature is now confusing and people can't figure it out. 
What's happening is that people expect to be able to copy paste the “Export URL”, and send it to others, but it doesn’t work anymore to use this URL. (since Matomo 4, the token_auth only works for that particular user session).

To improve the situation, here is an idea that we came up with after a short discussion: 

When clicking the “Show export URL”, it indicates that the user wants to get the URL and use it. So when people click on it, we could instead

1.  automatically remove the token_auth and replace it by eg. `&token_auth=ENTER_YOUR_TOKEN_AUTH_HERE`

2. show the information in the  tooltip as a visible warning instead (and tweak the message a bit such as below, or better):

> Note: To use the generated export URL, you will need to specify an app token auth. You can configure these tokens in [Admin -> Security -> Auths Tokens.](open the link in a new tab?). Replace `ENTER_YOUR_TOKEN_AUTH_HERE` in the Export URL by your Auth token.

This would help people achieve their goals of sharing the URL, and reduce confusion.

**Comment by tsteur** [comment]
> Note: To use the generated export URL, you will need to specify an app token auth. You can configure these tokens in [Admin -> Security -> Auths Tokens.](open the link in a new tab?). Replace ENTER_YOUR_TOKEN_AUTH_HERE in the Export URL by your Auth token.

It should also say to never ever share this URL with the replaced token with anyone else.

**Comment by sgiehl** [comment]
should have been fixed with #17227
