### ISSUE TITLE
Matomo App Version 1.002 on a Sharepoint Online Site will not load

### ISSUE THREAD

**Issue by Porti3** [piwik/piwik#17000]
hello all, 

I need your help. We set up a new Matomo server at the beginning of the year. We have deployed the app in the AppCatalog (online and onPrem). The pages where we have installed the Matomo app are still being tracked without any problems. In Sharepoint Online we now have problems with newly rolled out pages. The app can be installed smoothly, but it does not load. If you look in the developer tools of the browser, you can see that Matomo does not appear in the sources of the new pages. On the pages from the beginning of the year you can see the Matomo entry under the sources. In the Onprem world, everything is also running fine. What could be the reason for this? Does MS have new security and no longer allow it on new pages? I have already tried so many things. I have even updated version 1.00.2, but it won't load either. 

I would be very grateful for an answer

**Comment by tsteur** [comment]
Hi @Porti3  thanks for creating this issue. I recommend you ask this question in our forum https://forum.matomo.org/ as we can't provide Sharepoint support in our issue tracker. We're only managing bug reports and feature requests in this issue tracker for Matomo core. Maybe there's another sharepoint user in the forum that can help you.

**Comment by tsteur** [comment]
You have probably seen it but mentioning it just in case you haven't. Maybe https://matomo.org/faq/how-to-install/faq_19424/ helps
