### ISSUE TITLE
When embedding a widget with the "Multisites" report (All websites), the links are not working

### ISSUE THREAD

**Issue by almare** [piwik/piwik#17001]
I embed the Multisite Widget into an Ifram on my page. The iframe is showing nicely all websites with a view permission. So far so good. The problem begins if I click on a website link. I get redirected and have to login. It  would be much better if the auth_token is added to the dashboard deeplinks. This will make it possible to get on overview of all websites and switch between them.

I added the auth_token directly to the website dashboard deeplink and it worked aout of the box.

**Comment by tsteur** [comment]
Thanks for reporting this issue @almare and glad you found a workaround until this is fixed
