### ISSUE TITLE
JS tracker should not track anything when the protocol is file:// to avoid tracking personal data by accident

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17017]
Use case:

Someone downloads a page from your website and stores it locally. Then the user opens it and the user will be tracked and the URL might look like

```
file:///C:/Users/myname/AppData/Local/...
```

This way we actually track personal data potentially by accident without knowing.

* We would always exclude page urls with this protocol by default
* There should be a method to opt out of this feature so you can track these requests if needed. 
* We create an FAQ to document this behaviour / feature.

As this could be seen as a BC break we need to maybe wait for Matomo 5 for this and/or clearly announce this and warn users of this change.

**Comment by tsteur** [comment]
see https://developer.matomo.org/guides/jstracker-core this would need to be changed in `js/piwik.js` see how to embed tracking code https://developer.matomo.org/guides/tracking-javascript-guide

**Comment by tsteur** [comment]
This would be a great new privacy feature which be quick to implement 👍

**Comment by jane-twizel** [comment]
Will be quick work and supports privacy.

**Comment by peterhashair** [comment]
@tsteur just found we have something similar, but not the same. Do we consider removing that one?
https://github.com/matomo-org/matomo/blob/6be3e32e29ef8c70e13ace7ef02efcacb64154b5/js/piwik.js#L6524-L6528

**Comment by tsteur** [comment]
@peterhashair we would keep it to not break the API as some people might use this

**Comment by peterhashair** [comment]
Add documents here. https://matomo.org/?post_type=faq&p=59435&preview=true

**Comment by sgiehl** [comment]
@peterhashair the new method should also be added here: https://developer.matomo.org/api-reference/tracking-javascript
But as this will be included in Matomo 5 only, we maybe should first start the documentation for 5.x. See https://github.com/matomo-org/developer-documentation/issues/675

**Comment by peterhashair** [comment]
@sgiehl should I wait for the `5.x` documentation created? Or should I created PR follow those steps https://github.com/matomo-org/developer-documentation/#how-to-add-docs-for-a-new-matomo-version

**Comment by sgiehl** [comment]
Let's wait till https://github.com/matomo-org/developer-documentation/issues/675 is done

**Comment by justinvelluppillai** [comment]
Looks like this is ready now @peterhashair @sgiehl - 5.x-dev documentation is now live.

**Comment by peterhashair** [comment]
@justinvelluppillai  added updates.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/strange-item-in-analytics/53432/2

**Comment by manufitoussiwit** [comment]
And what about tracking in Electron based application ? UI is often served with file:// protocol. It the case of my application.

The solution explained here https://fr.matomo.org/faq/how-to/enable-file-protocol-tracking/ is not really a good solution. 
It requires to build a new version of my application to reactivate tracking. 
In other words, update matomo in v5 leads to loose tracking of my current clients untill they update their app.

Is there another solution?

**Comment by sgiehl** [comment]
@manufitoussiwit Guess that depends a bit how you have integrated Matomo into that application. If you use the TagManager it would be easy to add an additional call like this. Otherwise I think there might only be the possibility to adjust the tracker file yourself to enable file tracking.
