### ISSUE TITLE
Plugin cannot update even though 4.x-dev branch/code exists

### ISSUE THREAD

**Issue by DevDavido** [piwik/piwik#17018]
Hello there 👋 

My Matomo 4.1.0 (running on PHP 7.2.18) installation says "PerformanceAudit requires Piwik <4.0.0-b1." which prevents me from updating the plugin even though the plugin is available and released for Matomo 4.x as also seen in its [plugin.json](https://github.com/DevDavido/performance-audit-plugin/blob/4.x-dev/plugin.json) and [marketplace page](https://plugins.matomo.org/PerformanceAudit?matomoversion=4). 

Is there some hick up on Matomos side or on the plugins side?

**Comment by Findus23** [comment]
Hi,

What happens when you go to the marketplace and update (or uninstall and install the latest version) the plugin?

**Comment by DevDavido** [comment]
Under Settings ⮁ Platform ⮁ Marketplace the PerformanceAudit plugin doesn't show up in Matomo 4.1. And the marketplace page already shows the latest, updated version. Is that what you were referring to?

Is there any special treatment of plugins by Matomo if they are in beta?

**Comment by tsteur** [comment]
Hi @DevDavido you would likely need to enable receiving beta versions in Admin => General Settings => Release Channels. Then you would be able to update to it maybe. It be best to create an issue in the plugin's repo to release a stable version in https://github.com/DevDavido/performance-audit-plugin Let me know if this doesn't work and I'll be happy to reopen. The plugin developer would need to release a non-beta version though.

**Comment by DevDavido** [comment]
Thanks @tsteur, the release of a non-beta version of the plugin made the update possible.
