### ISSUE TITLE
When "average generation time" is zero, hide the sparkline and "Avg generation time" graphs metric from picker 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#17010]
As a user, when i'm viewing a period where the  "average generation time" is zero, for example under "Visitors > Overview", it would be helpful if:

1. the sparkline "0 average generation time" is hidden
2. and "Avg generation time" metric is removed from graphs metric picker 

Context: currently this metric is shown for Matomo instances that used to track this metric (before Matomo 4). Which is helpful, but in this issue we just want to remove any confusion and hide the feature when it's definitely zero for the selected period.

![Screenshot from 2020-12-24 09-23-04](https://user-images.githubusercontent.com/466765/103034402-a5f56d00-45c9-11eb-836a-e73f0e0f733e.png)

**Comment by mattab** [comment]
Otherwise if it's a bit too complex, instead of implementing the "smart" remove, we could just remove this metric completely, once we have implemented the new metric in #17013 - this would be good enough as people will be able to use the new metric now. (and would still be able to access the old metric in API)

**Comment by tsteur** [comment]
@mattab was just going to say the same we could just remove it which would make it a lot easier independent of whether #17013 is implemented or not.

**Comment by fvdm** [comment]
Do I understand it correctly that the old metric will then not be available for comparison in the UI anymore? Our non-dev users have to pull the raw data from the API? 👀

**Comment by mattab** [comment]
> was just going to say the same we could just remove it which would make it a lot easier independent of whether #17013 is implemented or not.

:+1: it would be great and ideally we can do it in 4.3.0 already then?

**Comment by basos9** [comment]
Hello,
Maybe this could be defered after #17013 is implemented for comparizon purposes

After upgrading to 4.3 (from 3.) we have this picture

![image](https://user-images.githubusercontent.com/1616441/118990309-6de13300-b98b-11eb-9ae6-bf9fc04b72b0.png)

which could be complemente by just overlapping the new metrics "avg. page load time"

**Comment by tsteur** [comment]
As part of this issue we remove (not replace) the metric average generation time

**Comment by fvdm** [comment]
You are going to delete the historic page generation data?
