### ISSUE TITLE
Explain how to track Ecommerce Orders in Shopify store (using image pixel tracking)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#17024]
an FAQ explains how to add shopify ecommerce store page tracking with Matomo in https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-shopify-store/

and the FAQ says:

> Currently Matomo does not have an eCommerce integration with Shopify, so Ecommerce tracking is not available. That’s because Shopify plans don’t allow 3rd party javascript on their checkout pages, so Matomo cannot track these ecommerce checkout pages. 

as Shopify is very popular among ecommerce, it would be valuable to also be able to track shopify ecommerce sales in the Matomo analytics dashboard. Looking at their docs online at https://help.shopify.com/en/manual/orders/status-tracking/customize-order-status/add-conversion-tracking there seems to be a feature to do conversion tracking using an image beacon such as:

`<img src="https://www.tracking.com/pixel.gif?amount={{ total_price | money_without_currency }}&amp;order-id={{ order_number }}&amp;currency={{ currency }}" height="1" width="1" />`

Limitation: It looks like we won't be able to track the products, but tracking the sale and amount is already extremely valuable.

Suggested steps: 

1. double check whether it works to record the ecommerce sale in Matomo using pixel beacon,
2. update our [Shopify FAQ](https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-shopify-store/) to include instructions on how to add this image beacon

FYI customer who uses shopify messaged:

> see the recordings of the user journey from the moment they arrived on our site until they left either without placing an order or with placing an order?

**Comment by EladGeek** [comment]
why not use the script pixel?
you have to load the base tag in advance (to capture the pageview also), and then fire the conversion event

a similar solution is used by the [Bing tag in Shopify](https://polkadotdata.com/shopify/how-to-install-the-bing-uet-tag-on-a-shopify-site/)

**Comment by Starker3** [comment]
The Shopify themes allow for quite a lot of flexibility in how they can be setup.
So what we could do is create some basic shopify style functions to trigger certain types of tracking requests. The easiest will probably be tracking product views, since this can easily fire on every product page by adding the tracking code in the correct theme file.

**Comment by tsteur** [comment]
fyi @mattab @Starker3 this might be more an internal KB or SUP issue?

**Comment by mattab** [comment]
Closing here and re-created internally as SUP-372

**Comment by mattab** [comment]
how to track Ecommerce Analytics for Shopify covered (including product, categories, product views & add to carts, etc.) in https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-shopify-store/

**Comment by uschtwill** [comment]
Shouldn't the docs change to make use of this feature now? https://help.shopify.com/en/manual/promoting-marketing/pixels/overview
