### ISSUE TITLE
No way to send batch events after a configured time

### ISSUE THREAD

**Issue by Sayeeda12** [piwik/piwik#17027]
Hi there,

I'd a question w.r.t batch tracking in Matomo. I've been using Matomo from quite a long time and now I'm implementing batch tracking for my website but I'm unable to add a configurable delay to send the queued requests. It's by default 1.75 seconds and there's no way for me to change it. Please let me know if it's possible because 1.75 seconds is too less and is not of much help in my use case. If it's not available currently, could you please add it as part of your next release.

Regards,
Sayeeda

**Comment by tsteur** [comment]
Hi @Sayeeda12 you can use `_paq.push(['setRequestQueueInterval', intervalInMs])`.
