### ISSUE TITLE
Password recovery SMTP email configuration

### ISSUE THREAD

**Issue by wlabarron** [piwik/piwik#17026]
I'm setting up SMTP email using the web interface (System > General settings > Email server settings) and it provides the option to set an SMTP From Address.

It seems like this field sets the config option `noreply_email_address` ([global.ini.php#L474](https://github.com/matomo-org/matomo/blob/9790d90f876ae74b5770f23b1958384b01d2028c/config/global.ini.php#L474)), but not `login_password_recovery_email_address` ([global.ini.php#L421](https://github.com/matomo-org/matomo/blob/9790d90f876ae74b5770f23b1958384b01d2028c/config/global.ini.php#L421)).

This means that my SMTP server rejects any password recovery emails, since Matomo tries to send it using the default password recovery email address, which the SMTP user isn't authorised to send as.

Perhaps a fix for this would be to change the SMTP From address option in the web interface to update both emails in the config? Or perhaps to add another form field in the web interface to set the two addresses separately?

**Comment by tsteur** [comment]
@mattab why do we have a `login_password_recovery_email_address`? I suppose both users would need to have the same password for this to work.

**Comment by wlabarron** [comment]
The current Matomo settings interface has fields for SMTP Username ([global.ini.php#L985](https://github.com/matomo-org/matomo/blob/9790d90f876ae74b5770f23b1958384b01d2028c/config/global.ini.php#L985)), SMTP password ([global.ini.php#L986](https://github.com/matomo-org/matomo/blob/9790d90f876ae74b5770f23b1958384b01d2028c/config/global.ini.php#L986)), and SMTP From address (`noreply_email_address`). This setup means one SMTP username and password needs to be able to send as `noreply_email_address` and `login_password_recovery_email_address`.

**Comment by tsteur** [comment]
fyi was made configurable in https://github.com/matomo-org/matomo/issues/527 in 2009.

It was added in https://github.com/matomo-org/matomo/commit/68eb786396c3313f74515363b04b9ca2309a0035#diff-801809c140d123b729100c6dd8097fd6954dff224a290112ed910bb8e33c577c in  2008. 

I suppose there is no particular reason for this and we could simply remove it and use the regular from.

**Comment by mattab** [comment]
Sounds good to use the regular from :+1:
