### ISSUE TITLE
File integrity: remove vendor/bin/lessc

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17031]
I am doing right now a fresh installation of Matomo v4.1.0

![grafik](https://user-images.githubusercontent.com/1645099/103351125-78fdfa00-4aa2-11eb-9973-ad0aa5f7cdde.png)

and I got the information that I should delete vendor/bin/lessc
![grafik](https://user-images.githubusercontent.com/1645099/103351189-b06ca680-4aa2-11eb-8a11-51d46898a87f.png)

In my opinion a fresh installation should not contain any not needed files

**Comment by tsteur** [comment]
Thanks for creating this issue @mathContao 

We've already prepared a fix for this in https://github.com/matomo-org/matomo-package/pull/124 and will close this issue as a duplicate see https://github.com/matomo-org/matomo/issues/16938

This should be fixed in one of the next 1-2 releases.
