### ISSUE TITLE
Unable to start matomo on Windows 10

### ISSUE THREAD

**Issue by pvk2410** [piwik/piwik#17032]
Hi There,

I'm trying to set up Matomo on windows 10 having NGINX 1.19.6  as the webserver , the Matomo files were downloaded on this server and unzipped to <webserver>/analytics/matomo location (C:\NGNIX2\nginx-1.19.6\analytics\matomo).

When i hit the URL - http://localhost:82/analytics/matomo , but some how i cannot access the Matomo's starting page. I get a 404 not found error.

Can someone please let me know if any specific configurations needs to be done?

**Comment by tsteur** [comment]
Hi @pvk2410 

Matomo should run nicely on Windows 10. I suggest you ask the same question in our forum as some users might be able to help you there: https://forum.matomo.org/ 

Here in this issue tracker we don't answer questions but only handle specific bug reports and feature requests. There seems to be something not quite right with your webserver setup or so.

Thanks for your understanding.
