### ISSUE TITLE
SQL fieldsize in log_visit for location_region to small

### ISSUE THREAD

**Issue by grzchr15** [piwik/piwik#17042]
Currently there are various functions getRegionNames() which work for MaxMind/Wikipedia regions and get cropped to 3 chars at SQL schema.
If Intranet Regions are longer this field must be increased in size.
For example office regions are  up to 20 chars in my use case.

A patched version of GeoIp2 with adding https://github.com/grzchr15/IntranetGeoIP can so track both Intranet and Internet regions.

https://gist.github.com/grzchr15/dfc8e975482ad99e94b620b033da1da5

**Comment by sgiehl** [comment]
The location_region column was designed to store ISO region codes. Using it for something else might work though, but I would suggest using a new column if you want to store something else in there
