### ISSUE TITLE
File integrity check failed for wikimedia lessc

### ISSUE THREAD

**Issue by haraldhaas** [piwik/piwik#17048]
Hi All,

I am running Matomo v4.1.0 and the file integrity check in the system check is alerting about a file that is part of the original source code.

```bash
Files were found in your Matomo, but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/bin/lessc


To delete all these files at once, you can run this command:
rm "/var/www/html/vendor/wikimedia/less.php/bin/lessc"
```

The exact same files are in the source code for tag v4.1.0 here in git. Any idea?

Thanks,
Harry

**Comment by Findus23** [comment]
Hi,

This has been fixed in https://github.com/matomo-org/matomo-package/pull/124 and will therefore be fine in the next release. (I'm not sure if you might have to delete the file once after the update)

**Comment by haraldhaas** [comment]
Hi @Findus23,

thanks for the swift response. Seems despite searching for it, I have missed the other bug reports to the same issue. I'll close this issues now.

Thanks,
Harry
