### ISSUE TITLE
Segment graph wrong since Matomo 4.0.3

### ISSUE THREAD

**Issue by robles-design** [piwik/piwik#17044]
I noticed that the segment graph for Checkout Success Suche intern (blue) is wrong since November 01, 2020. The comparison for "Checkout Success Suche intern" and "Checkout Success" (all checkouts) must be different like in October. Any idea?

![matomo-segments-compare](https://user-images.githubusercontent.com/25033650/103599773-386d0900-4f06-11eb-8d20-b754aa7ccbea.png)

**Comment by sgiehl** [comment]
would you mind sharing both segment definitions?

**Comment by robles-design** [comment]
Checkout Success
Visitors who reached a goal id --> matches --> 1

Checkout Success Search intern
Visitors who reached a goal id --> matches --> 1
AND
Search term (internal search) --> does not contain --> testomat

With "Checkout Success Search intern" I get all visitors who bought something and did an internal search, because no one searches for testomat and all other search terms are counted. That worked since 2016.

**Comment by sgiehl** [comment]
I guess an empty search term might meanwhile match the `does not contain testomat`. Did you try it with a segment like `searches>0` ?

**Comment by robles-design** [comment]
How do I define this?

**Comment by sgiehl** [comment]
Should be something like `Number of searches` in the UI

**Comment by robles-design** [comment]
Thanks, found it. Test button works. I'll give you feedback if it works after archiving.

**Comment by robles-design** [comment]
I'll get the following error in the UI admin panel when I want to reset historical reports: The segment condition 'searches&gt' is not valid.

**Comment by sgiehl** [comment]
Are you using the Invalidate Reports plugin?

**Comment by robles-design** [comment]
Yes

**Comment by mattab** [comment]
Thanks for your patience with this issue. We believe this has been resolved in the recent updates of Matomo. To ensure you have the fix, please [update](https://matomo.org/docs/update/) to the latest version of Matomo.  If the issue persists after the update, don't hesitate to reopen this issue and let us know. Cheers!
