### ISSUE TITLE
Dimensions: previousPages & followingPages within custom reports

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17056]
Hi everyone,
So far, one need to access the API to get a table for the transition report.
So to say, one cannot get the data regarding the previous pages and following pages within Matomo.
-> Is there any possibilities for you to add them as dimension within the custom report premium features?

Thank you,

**Comment by tsteur** [comment]
Hi @Chardonneaur could you get in touch with our support here as well as this is a premium feature? Cheers :)
