### ISSUE TITLE
Upgrade to 4 fatal error upgrade script fails

### ISSUE THREAD

**Issue by oz-olson** [piwik/piwik#17051]
Fatal error: Access level to Piwik\Plugins\VisitTime\Columns\ServerTime::configureSegments() must be public (as in class Piwik\Columns\Dimension) in C:\inetpub\wwwroot\piwik\plugins\VisitTime\Columns\ServerTime.php on line 33

The upgrade script fails with this error. 

Thanks

**Comment by Findus23** [comment]
Hi,

I am not aware of a `plugins\VisitTime\Columns\ServerTime.php` file.

https://github.com/matomo-org/matomo/tree/4.x-dev/plugins/VisitTime/Columns

Maybe this is something like https://github.com/matomo-org/matomo/issues/16927

Could you try (after making a backup) deleting this file? If it is important the integrity checker should complain afterwards and you could restore it from the latest matomo.zip download.

**Comment by oz-olson** [comment]
We removed ServerTime.php and the upgrade was successful. 

Thanks

**Comment by oz-olson** [comment]
We removed ServerTime.php and the upgrade was successful.

Thanks

**Comment by sgiehl** [comment]
@oz-olson Just out of curiosity. Which version did you upgrade from? The ServerTime.php has been removed with Matomo 3.2 already...
