### ISSUE TITLE
Anonymise IP when sending feedback through Matomo UI

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17052]
Currently when submitting feedback through the Matomo UI, the full user IP address is being sent when providing feedback.

We should preferably change this to anonymise the IP when sending feedback in this manner.

![image](https://user-images.githubusercontent.com/20905821/103715562-d0154900-5025-11eb-8806-ef48fcc1db6a.png)

![image](https://user-images.githubusercontent.com/20905821/103715361-4796a880-5025-11eb-9c57-d39f64e004ba.png)

**Comment by sgiehl** [comment]
I don't think the IP is needed to be sent with the request at all. Having it anonymized doesn't have any benefit. Will issue a PR to simply remove it.
