### ISSUE TITLE
Integrity Check Fails on New Docker Install

### ISSUE THREAD

**Issue by DaAwesomeP** [piwik/piwik#17066]
This is a brand new install (Docker), so the manifest must not be accurate to the files fetched?
![image](https://user-images.githubusercontent.com/4472083/104074407-11505900-51de-11eb-9a97-9fdce2e35c9c.png)

**Comment by Findus23** [comment]
Hi,

This has already been fixed and will be shipped in the next release (you might have to manually delete this file once afterwards)

See also https://github.com/matomo-org/matomo-package/pull/124, https://github.com/matomo-org/matomo/issues/17031 and https://github.com/bitnami/bitnami-docker-matomo/issues/68
