### ISSUE TITLE
Text error in German translation -> "oderr"

### ISSUE THREAD

**Issue by dirkeinecke** [piwik/piwik#17067]
"Sie können Domänen oder Subdomänen wie http://example.com oderr http://stats.example.com definieren. Oder fügen Sie einfach * hinzu, um cross domain requests für alle Domänen zu erlauben"

The word "oderr" must be "oder". In this context, you can also add a period to the end of the sentence.

**Comment by sgiehl** [comment]
Hi @dirkeinecke 
Thanks for mentioning this one. I've adjusted it in our translation tool.
If you want to help us improving the translations further, feel free to sign up at 

https://www.transifex.com/matomo/matomo/
