### ISSUE TITLE
Publish new Cloudflare App for Matomo

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17068]
As suggested by https://forum.matomo.org/t/update-cloudflare-app/40159

https://www.cloudflare.com/apps/piwik currently uses Piwik branding and Screenshots which probably should be replaced with Matomo. Also the tracking code should be updated to the latest one using matomo.php

I am not sure how cloudflare apps work, but if possible it could be open sourced so that other people could contribute additional features.

**Comment by tsteur** [comment]
code is in https://github.com/innocraft/cloudflare-app-manual (needs to be made public)

**Comment by tsteur** [comment]
Made it public for now but it still has the piwik and innocraft branding/license/ ... https://github.com/matomo-org/cloudflare-app-manual

**Comment by tsteur** [comment]
@Findus23 closing this one for now as I think it might be done but feel free to reopen if needed.
