### ISSUE TITLE
Login issue with LoginLdap

### ISSUE THREAD

**Issue by nrenault** [piwik/piwik#17071]
Hello,

One user get the following error message:

"_You are currently not allowed to log in because you had too many failed logins, try again later_"

https://matomo.org/faq/troubleshooting/faq_32758/

According to this FAQ, the error seems to come from Login plugin who is disabled because I use LoginLdap plugin.

I removed manually brute force logs from DB, I cleared cache, the user can login but after few seconds of navigation on Matomo, he have the same error again.

Version used: Matomo 4.1.0

**Comment by sgiehl** [comment]
@nrenault  are you using any third party plugins?

**Comment by nrenault** [comment]
@sgiehl: I use ExtraTools, LoginLdap and QueuedTracking.

**Comment by nrenault** [comment]
To give you more informations: Matomo is installed on 3 servers. This one only have LoginLdap activated on it, but ExtraTools and QueuedTracking are used on other servers (same database).

I have no entries in bruteforce table on DB, and the error is still here for all users loggued from LDAP.

I enabled development mode and logging, but I have nothing interesting.

Is it possible to desactivate the bruteforce check from config file or DB ?

**Comment by nrenault** [comment]
I close the issue, the problem is users, not Matomo....

Sorry for this lost of time...
