### ISSUE TITLE
Editing Users screen is partially broken

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17079]
Matomo 4.1.0

settings -> system -> user

![grafik](https://user-images.githubusercontent.com/1645099/104379845-59e37b80-552a-11eb-9187-1c186e13b527.png)

1. cannot read the select list "Massenaktion" (= batch action?) + user search input + filter select list. Grey on grey.
2. column "role": select list (that includes: no access and read access) looks strange and is difficult to use + the select below shines through (see grey "Hauptadmin" text label)
3. 2FA column: strange letters

**Comment by tsteur** [comment]
Thanks for creating this issue @mathContao I experienced the same issue before regarding 2) 
![image](https://user-images.githubusercontent.com/273120/104390465-a7033400-55a2-11eb-9f6a-969e5a543d8f.png)

1) might be on purpose maybe if you haven't selected anything yet? To be seen.
