### ISSUE TITLE
Anonymous user settings not working after v4 upgrade

### ISSUE THREAD

**Issue by alexymik** [piwik/piwik#17077]
After upgrading a Matomo site from 3.14.1 to 4.1.0, Anonymous users are no longer able to access the dashboard or sites directly.

in v4, accessing Matomo results in a login page despite allowing view access to sites and setting a default anonymous dashboard in Anonymous user settings.

**Comment by tsteur** [comment]
Thanks for creating this issue @alexymik 

I think I can reproduce this here actually as I just gave anonymous user view access and then I wouldn't be able to see the dashboard. Interestingly it works on https://demo.matomo.cloud/

**Comment by alexymik** [comment]
Thanks :+1:
