### ISSUE TITLE
--skip-idsites argument to core:archive works like --force-idsites in 4.x

### ISSUE THREAD

**Issue by Callidior** [piwik/piwik#17074]
When specifying `--skip-idsites` in a CLI call to `core:archive`, it will actually process only these sites instead of skipping them.

The current [implementation](https://github.com/matomo-org/matomo/blob/4.x-dev/core/CronArchive.php#L744) looks like this:

```PHP
if (!empty($this->shouldSkipSpecifiedSites)) {
    $websiteIds = array_intersect($websiteIds, $this->shouldSkipSpecifiedSites);
}
```

I guess it should use `array_diff` instead of `array_intersect`.

**Comment by tsteur** [comment]
Thanks for finding this regression @Callidior  👍  Very appreciated
