### ISSUE TITLE
"Keep basic metrics (visits, page views, bounce rate, goal conversions, ecommerce conversions, etc.)"

### ISSUE THREAD

**Issue by candaj** [piwik/piwik#17089]
Hello,

In order to keep our data in order and compliante I would like to know what are the complete list of "basic metrics" that are keep from the deletion with the option checked. Is there a list somewhere ? 

edit: if I keep reports, do I keep personnal data too or do I have to delete it ?

Regards,

**Comment by tsteur** [comment]
@candaj AFAIK these metrics are kept:

> 'nb_uniq_visitors', 'nb_visits', 'nb_users', 'nb_actions', 'max_actions',                     'sum_visit_length', 'bounce_count', 'nb_visits_converted', 'nb_conversions',                     'revenue', 'quantity', 'price', 'orders'

If goals are configured, a few additional metrics may be kept. I don't have a list for this but I think it's like the number of conversions, the number of orders and the number of cart abandoned.
