### ISSUE TITLE
Translation missed on "Create a new user"

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17086]
The (German) translation is missed in the screen of "Create a new user"
![grafik](https://user-images.githubusercontent.com/1645099/104502746-c325c600-55e0-11eb-9fa1-24e8f66ae83e.png)

Username = Benutzername
Password = Passwort
Email = E-Mail

See the wording in the table before
![grafik](https://user-images.githubusercontent.com/1645099/104503167-05e79e00-55e1-11eb-9358-1d8542d70721.png)

**Comment by Findus23** [comment]
This does indeed seem to be hardcoded:
https://github.com/matomo-org/matomo/blob/8c792dcf02424fce9b5a88c571c8f5c76295b710/plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.html#L39-L86
