### ISSUE TITLE
Matomo showing incorrect Month data when selecting first day of the month for specific time zones

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17087]
This may be related to: #17080 

When selecting the period "Month" for a website that has its time zone set for example as United States - New York and selecting the first day of the month, Matomo is showing the previous months data.

Screenshot comparison between the same month selected but using the 1st vs the 2nd:
![Thursday-14-01-2021 08-57-55](https://user-images.githubusercontent.com/20905821/104503986-ae7c1900-5646-11eb-8bdc-e2f84b484428.png)
URL parameters: index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=month&date=2020-12-02&segment=&category=General_Visitors&subcategory=General_Overview
![Thursday-14-01-2021 08-58-20](https://user-images.githubusercontent.com/20905821/104503982-ad4aec00-5646-11eb-8714-d8b0825d3062.png)
index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=month&date=2020-12-01&segment=&category=General_Visitors&subcategory=General_Overview

This causes the comparison feature to show the incorrect month data (I.e. showing October data for November when comparing December with November)

![image](https://user-images.githubusercontent.com/20905821/104504351-3104d880-5647-11eb-8942-f83808f1a0e2.png)

Manually changing the date in the URL shows the correct comparison data 

![image](https://user-images.githubusercontent.com/20905821/104504433-4d087a00-5647-11eb-91e6-881a4091952b.png)

This same behaviour occurs when using the "Week" period and may also be occurring in the "Day" time period as well (But it may be quite difficult to confirm that one)

The Matomo server is located in a different timezone (EU) to the website timezone (US - NY).

**Comment by tsteur** [comment]
it be great to test this and the other issue once the next Matomo update has been released and deployed. It might be fixed already.

**Comment by tsteur** [comment]
@Starker3 can you check if this one is fixed now? eg on demo

**Comment by Starker3** [comment]
It looks like this one is fixed for the websites that had the error. When comparing the same as in the examples above the reports are showing the correct numbers even when selecting the 1st day of the month (As expected)
