### ISSUE TITLE
How does UniApp integrate Matomo

### ISSUE THREAD

**Issue by huangzhong0406** [piwik/piwik#17090]
Hello friend ~
How does UniApp integrate Matomo? I want to integrate Matomo with UniApp,I want you to help me！
Thank you very much

**Comment by Findus23** [comment]
Hi,

I don't know UniApp, but as long as you can modify the page template and add the JS tracking code, you can use Matomo on every page.
And on how to do it in UniApp, I'd rather recommend you to ask their support team.
