### ISSUE TITLE
Real-Time Map description switches to "There is no data for this report."

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17099]
reported in https://forum.matomo.org/t/frage-zur-besucherkarte-in-echtzeit/40267

The header of the real-time map seems to switch to an error message after a few seconds even though the map loads fine.

https://user-images.githubusercontent.com/6266037/104736232-f1bbb200-5742-11eb-8421-d3e4c3d3d913.mp4

Interestingly I can't reproduce this issue on demo.matomo.org

There is no error in the JS console

**Comment by sgiehl** [comment]
Seems that the case when the ajax request, that is sent periodically to fetch new visitors, does not have any results

**Comment by Findus23** [comment]
Okay, I found a bit more details. Indeed the initial request returns data, but the ones afterwards don't.
The first one sends `&minTimestamp=0` and the ones afterwards send `&minTimestamp=1610714405` and I guess if there were no new visits since the text is incorrectly updated.
