### ISSUE TITLE
fatal error: Modulo by zero: method=imageGraph while widht = 0

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17092]
I called the API by this:
/index.php?module=API&method=ImageGraph.get&idSite=1&token_auth=xxxxxxxxxxxxx&period=month&date=previous24&apiModule=VisitsSummary&apiAction=get&graphType=evolution&width=0&height=2

and got this fatal error message

![grafik](https://user-images.githubusercontent.com/1645099/104643219-6099fc00-56ac-11eb-9ccc-9d7f9148c656.png)

width = 0 AND height != 0

width = 0 and height = 0 => it works fine.

**Comment by tsteur** [comment]
Thanks for creating this issue @mathContao I can reproduce it using the same parameters 👍
