### ISSUE TITLE
Widget is showing wrong data from yesterday instead of today

### ISSUE THREAD

**Issue by esolix** [piwik/piwik#17095]
In ref to #16999 

The fix for 4.11 works on URL string with date specified, however with "date=today" it still has the issue of showing yesterday's stats for some dashboard widget if you are in other timezone

**Not working**
index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=today&segment=&category=Dashboard_Dashboard&subcategory=1

**Working - By selecting today's date URL string -> &date=2021-01-15**
index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=2021-01-15&segment=&category=Dashboard_Dashboard&subcategory=1

**Comment by ghost** [comment]
Same problem here.  I think #16999 was prematurely closed.

**Comment by BasketballBuzz** [comment]
Still facing the same issue after updating to 4.11.

**Comment by tsteur** [comment]
fyi @sgiehl
