### ISSUE TITLE
Updatecheck does not find Updates in Matomo 4.*

### ISSUE THREAD

**Issue by narfk** [piwik/piwik#17098]
My Version is 4.1.0
Release Channel ist latest stable. Even when i'm switching to latest Beta the Updatechecker return 'You are using the latest version of Matomo!'

Is there any way to figure out what is going wrong?
I made the Updates from 3 to 4 (and from 4.0.0 to 4.1.0) with the ZIP download.

**Comment by Findus23** [comment]
The update check returns the latest version correctly: 

https://api.matomo.org/1.0/getLatestVersion/?piwik_version=4.0.0&php_version=7.2.5&mysql_version=5.7.0&trigger=CoreHome&timezone=UTC

The only way I can think of to check here would be to output `$url` (e.g. with `var_dump($url);`) here:
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/CoreUpdater/ReleaseChannel.php#L34-L39

**Comment by tsteur** [comment]
@narfk are you basically missing the 4.1.1 update? Does it maybe show up by now? You could also try clicking the "check for updates" button in the Admin area of Matomo

**Comment by narfk** [comment]
@tsteur after the manual update to version 4.0.0 with the zip archive. matomo didn't find any 4.0.* updates.
for sure i was also trying to check for new updates. in the devtools (network) i can see the it results with a http code 200 (successfull). but noting happens.

**Comment by tsteur** [comment]
@narfk any chance you can send us the output of the system report which you find in Administration -> System Report? There is a button to copy/paste the text and the data should be anonymised.

**Comment by narfk** [comment]
Here we go:

# Mandatory checks

## PHP version >= 7.2.5: ✔ 7.4.13


## PDO extension: ✔ 


## PDO\MYSQL extension: ✔ 


## MYSQLI extension: ✔ 


## Other required extensions: ✔ zlib ✔ SPL ✔ iconv ✔ json ✔ mbstring ✔ Reflection


## Required functions: ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack


## Required PHP configuration (php.ini): ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR >= 30


## Directories with write access: ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c



# Optional checks

## File integrity: ✔ 


## Tracker status: ✔ 


## Memory limit: ✔ 1024M


## Time zone: ✔ 


## Open URL: ✔ curl


## PageSpeed disabled: ✔ 


## GD > 2.x + Freetype (graphics): ✔ 


## Other extensions: ✔ json ✔ libxml ✔ dom ✔ SimpleXML


## Other functions: ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file


## Filesystem: ✔ 


## Setup Cron - Managing processes via CLI: ✔ Ok


## Last Successful Archiving Completion: ✔ The archiving process completed successfully 07:13:57 ago.


## Database abilities: ✔ UTF8mb4 charset ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level


## Max Packet Size: ✔ 


## Forced SSL Connection: ✔ 


## Geolocation: ✔ 



# Informational results

## Matomo Version: 4.1.0


## Matomo Update History: 4.0.3,4.0.0,3.14.1,


## Matomo Install Version: Unknown - pre 3.8.


## PHP_OS: Linux


## PHP SAPI: apache2handler


## Timezone Version: 0.system


## PHP Timezone: UTC


## PHP Time: 1611044046


## PHP Datetime: 2021-01-19 08:14:06


## PHP Disabled functions: pcntl_alarm, pcntl_fork, pcntl_waitpid, pcntl_wait, pcntl_wifexited, pcntl_wifstopped, pcntl_wifsignaled, pcntl_wifcontinued, pcntl_wexitstatus, pcntl_wtermsig, pcntl_wstopsig, pcntl_signal, pcntl_signal_dispatch, pcntl_get_last_error, pcntl_strerror, pcntl_sigprocmask, pcntl_sigwaitinfo, pcntl_sigtimedwait, pcntl_exec, pcntl_getpriority, pcntl_setpriority, 


## PHP INI max_execution_time: 180


## PHP INI post_max_size: 32M


## PHP INI max_input_vars: 6000


## PHP INI zlib.output_compression: 


## Curl Version: 7.68.0, OpenSSL/1.1.1f


## Suhosin Installed: 0


## DB Prefix: piwik_


## DB Charset: utf8mb4


## DB Adapter: PDO\MYSQL


## MySQL Version: 5.7.30-0ubuntu0.16.04.1-log


## Num Tables: 330


## Browser Segment Archiving Enabled: 0


## Development Mode Enabled: 0


## Internet Enabled: 1


## Multi Server Environment: 1


## Custom User Path: 0


## Custom Include Path: 0


## Plugins Activated: API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CustomDimensions, CustomJsTracker, CustomVariables, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, GeoIp2, Goals, Heartbeat, ImageGraph, Insights, Installation, Intl, InvalidateReports 4.0.1, LanguagesManager, Live, Login, LoginTokenAuth 4.0.0, Marketplace, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Provider, Proxy, Referrers, Resolution, SEO, ScheduledReports, SegmentEditor, SitesManager, Transitions, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable


## Plugins Deactivated: Feedback, IntranetMeasurable, MobileAppMeasurable, MobileMessaging, ProfessionalServices, RssWidget, TagManager, Tour, TwoFactorAuth, Widgetize


## Plugins Invalid: 


## Server Info: Apache


## Had visits in last 1 day: 1


## Had visits in last 3 days: 1


## Had visits in last 5 days: 1


## Archive Time Last Started: 1611018002


## Archive Time Last Finished: 1611018009


## Num invalidations: 0 queued, 0 in progress


## User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0


## Browser Language: de-ch,de,en-us,en,fr-ch,fr


## Anonymize Referrer: 


## Do Not Track enabled: 0

**Comment by tsteur** [comment]
@narfk any chance you set the "Multi Server Environment: 1" setting in the config recently? That might explain this.

**Comment by narfk** [comment]
This was the output from my servers on a load balancing environment - so this setting seems ok for me.
On my Testserver the Setting is Multi Server Environment: 0 - the problem is the same.

**Comment by tsteur** [comment]
Could you also post the system check output from your test server @narfk

**Comment by 65Q2M89mBVP53sCK** [comment]
Output from Testserver

# Mandatory checks
## PHP version >= 7.2.5: ✔ 7.4.14

## PDO extension: ✔ 

## PDO\MYSQL extension: ✔ 

## MYSQLI extension: ✔ 

## Other required extensions: ✔ zlib ✔ SPL ✔ iconv ✔ json ✔ mbstring ✔ Reflection

## Required functions: ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

## Required PHP configuration (php.ini): ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR >= 30

## Directories with write access: ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c



# Optional checks
## File integrity: ✔ 

## Tracker status: ✔ 

## Memory limit: ✔ 1024M

## Time zone: ✔ 

## Open URL: ✔ curl

## PageSpeed disabled: ✔ 

## GD > 2.x + Freetype (graphics): ✔ 

## Other extensions: ✔ json ✔ libxml ✔ dom ✔ SimpleXML

## Other functions: ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

## Filesystem: ✔ 

## Setup Cron - Managing processes via CLI: ✔ Ok

## Last Successful Archiving Completion: ✔ The archiving process completed successfully 04:37:25 ago.

## Database abilities: ✔ UTF8mb4 charset ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level

## Max Packet Size: ✔ 

## Forced SSL Connection: ⚠ Warning: We recommend using Matomo over secure SSL connections only. To prevent insecure access over http, add <code>force_ssl = 1</code> to the <code>General</code> section in your Matomo config/config.ini.php file.<br /><br />Attention: Doing this without having set up a SSL certificate for using HTTPS will break Matomo.

## Geolocation: ✔ 



# Informational results
## Matomo Version: 4.1.1

## Matomo Update History: 3.14.1,

## Matomo Install Version: Unknown - pre 3.8.

## PHP_OS: Linux

## PHP SAPI: apache2handler

## Timezone Version: 0.system

## PHP Timezone: UTC

## PHP Time: 1611207461

## PHP Datetime: 2021-01-21 05:37:41

## PHP Disabled functions: pcntl_alarm, pcntl_fork, pcntl_waitpid, pcntl_wait, pcntl_wifexited, pcntl_wifstopped, pcntl_wifsignaled, pcntl_wifcontinued, pcntl_wexitstatus, pcntl_wtermsig, pcntl_wstopsig, pcntl_signal, pcntl_signal_dispatch, pcntl_get_last_error, pcntl_strerror, pcntl_sigprocmask, pcntl_sigwaitinfo, pcntl_sigtimedwait, pcntl_exec, pcntl_getpriority, pcntl_setpriority, 

## PHP INI max_execution_time: 180

## PHP INI post_max_size: 32M

## PHP INI max_input_vars: 6000

## PHP INI zlib.output_compression: 

## Curl Version: 7.68.0, OpenSSL/1.1.1f

## Suhosin Installed: 0

## DB Prefix: piwik_

## DB Charset: utf8mb4

## DB Adapter: PDO\MYSQL

## MySQL Version: 8.0.23

## Num Tables: 254

## Browser Segment Archiving Enabled: 1

## Development Mode Enabled: 0

## Internet Enabled: 1

## Multi Server Environment: 0

## Custom User Path: 0

## Custom Include Path: 0

## Plugins Activated: API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CustomDimensions, CustomJsTracker, CustomVariables, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, GeoIp2, Goals, Heartbeat, ImageGraph, Insights, Installation, Intl, InvalidateReports 4.0.1, LanguagesManager, Live, Login, LoginTokenAuth 4.0.0, Marketplace, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Provider, Proxy, Referrers, Resolution, SEO, ScheduledReports, SegmentEditor, SitesManager, Transitions, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable

## Plugins Deactivated: Feedback, IntranetMeasurable, MobileAppMeasurable, MobileMessaging, ProfessionalServices, RssWidget, TagManager, Tour, TwoFactorAuth, Widgetize

## Plugins Invalid: 

## Server Info: Apache

## Had visits in last 1 day: 0

## Had visits in last 3 days: 1

## Had visits in last 5 days: 1

## Archive Time Last Started: 1611190805

## Archive Time Last Finished: 1611190816

## Num invalidations: 0 queued, 0 in progress

## User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0

## Browser Language: de-ch,de,en-us,en,fr-ch,fr

## Anonymize Referrer: 

## Do Not Track enabled: 0

**Comment by tsteur** [comment]
The API itself would return the correct result in this case @narfk  https://api.matomo.org/1.0/getLatestVersion/?piwik_version=4.1.1&php_version=7.4.14&release_channel=latest_stable&mysql_version=8.0.23&trigger=CoreHome&timezone=UTC

Any chance you are familiar with a bit of PHP? I could suggest maybe one or two files to tweak to see if the request maybe somehow fails for you or so.

Any chance in your config/config.ini.php there is maybe a setting `enable_auto_update = 0`?

**Comment by narfk** [comment]
I'm familiar- so this is not a big thing.

I made a new attempt for an update from 3 to 4.1.1. Maybe something went wrong in my first try?
I see that the navigation in the backend is different. In the first attempt I see all points - now the subpoints are hidden and are only displayed when clicking on the main point. Maybe a hint?

Anyway. Yes in my settings i have enable_auto_update = 0 because i don't want a automatich update on my production servers.  Is this wrong?

**Comment by Findus23** [comment]
>  I see that the navigation in the backend is different. In the first attempt I see all points - now the subpoints are hidden and are only displayed when clicking on the main point. Maybe a hint?

This is an intentional new feature
https://github.com/matomo-org/matomo/issues/16793

> Anyway. Yes in my settings i have enable_auto_update = 0 because i don't want a automatich update on my production servers. Is this wrong?

Ah, I think this is where the misunderstanding comes from. Matomo will never update itself automatically (without you initializing, like Wordpress now does with patch releases), but I think this setting just disables the update check.

**Comment by narfk** [comment]
I will try enable_auto_update for the next update and I will report the result here

**Comment by tsteur** [comment]
`enable_auto_update=0` would explain this @narfk I'm quite confident it will work once you set the setting to `1`. If it doesn't work feel free to comment any time and we'll reopen the issue. Thanks
