### ISSUE TITLE
Error Message notification is not hidden when navigating to a new page

### ISSUE THREAD

**Issue by eric215** [piwik/piwik#17104]
When a server error results in the message below being displayed, transitioning to another page via the menu does not remove it, it continues to be displayed at the top of each page until a hard refresh is done.

Ver 4.1.1

`Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance.`

**Comment by tsteur** [comment]
@eric215 any chance you know the steps to reproduce this? So far I haven't seen this before AFAIK except for maybe https://github.com/matomo-org/matomo/issues/15575 which has a different error message.

**Comment by eric215** [comment]
If you have access to an Apache webserver, use this code in the .htaccess file to force a 406 ("Not Acceptable") error on the "Behaviours --> Transition page".  

This will cause the error message I noted to be displayed every time without seriously affecting the other functionality

```
RewriteCond %{QUERY_STRING} actionName
RewriteRule ^.* - [R=406,L]

```

**Comment by tsteur** [comment]
Thanks @eric215 I can reproduce it this way Basically, when someone changes the reporting page, then the error messages should be cleared.

**Comment by Findus23** [comment]
It would be great if there could be one fix that fixes this issue, #15575, #15498, #12934 and more related issues at once as it seems like the notification session is simply never cleared unless you log out and login again.

**Comment by tsteur** [comment]
@Findus23 they are a bit unrelated to this one unfortunately. We will eventually work on them though but I suppose these happen less and are much more complicated to solve so it's not as much of a priority right now

**Comment by flamisz** [comment]
I reproduced the bug a different way (maybe it's useful for someone):

I changed the return of the `plugins/Transitions/Controller.php` -> `renderPopover()` method:

```diff
+ Common::sendResponseCode(406);
- return $view->render();
```

This way I got the error message on the **Behaviour -> Transitions** page.
