### ISSUE TITLE
Content tracking isn't working properly

### ISSUE THREAD

**Issue by Maxel01** [piwik/piwik#17113]
I am new to Matomo, but I already know programming.
I tried to implement the content tracking feature using the Tag Manager.
It looks like the content impressions appear at random, sometimes they track the impression, sometimes it doesn't, sometimes it tracks only the interactions but not the impression.
I thought maybe it is the Tag Manager, so I tried it with the js tracking code. Same issue as before.
So I tried one last thing: trigger the content impression manually, which didn't work. So I added the trackEvent code just below.
What happened? The event was tracked, but the impression wasn't.
I can't find any solution for this.
If you need more information, send me a message.
Thank you a lot for the great project.

Matamo Version 4.1.1 (no updates available -> current stable version)
I cannot use SSL connection on my test domain because I do not have an other ssl certificate available

![Test-Log](https://user-images.githubusercontent.com/77640056/104957235-0bbcf500-59ce-11eb-8a86-cff9e77ceaaf.png)

[matomo.js.txt](https://github.com/matomo-org/matomo/files/5832100/matomo.js.txt)
-> my js tracker, isVisible() works fine and is not the problem.

Edit:
I made a quick test on my other website with SSL and it seems working fine.
Could it be a problem caused by an non SSL connection?

**Comment by tsteur** [comment]
@Maxel01 it should not be related to the SSL connection. Maybe it's a webserver configuration or PHP setting that is causing the issue (for example limited URL length etc). On your test site, when you look at the developer tools in the nextwork tab, do you maybe see some failed tracking requests? If so, maybe check out the HTTP response code.

I'll close this one for now as it kind of has to be a configuration issue but happy to reopen the issue any time and also happy to continue commenting. Let me know regarding the requests if they fail or succeed @Maxel01

**Comment by Maxel01** [comment]
Thank you for your fast answer.
It actually was a problem with the SSL connection. On my normal domain where the matomo server is located, i activated to force use SSL. I now tried it without and it works.
It the chart you can see the different HTTP codes:
Top: with SSL
Bottom: without SSL and redirecting to a GET request instead of POST

![Log](https://user-images.githubusercontent.com/77640056/105012934-02b83c00-5a3f-11eb-9c4d-5cd37a77c368.png)

It cost me about 3h in total to figure it out.
Still it does not answer why it works sometimes, and sometimes it doesn't. It looks like the request loses the arguments.
BTW that's the answer for the redirected request:

> "This resource is part of Matomo. Keep full control of your data with the leading free and open source web analytics & conversion optimisation platform.
> This file is the endpoint for the Matomo tracking API. If you want to access the Matomo UI or use the Reporting API, please use index.php instead"

Again, thank you! @tsteur
