### ISSUE TITLE
'console customdimensions:add-custom-dimension' does nothing

### ISSUE THREAD

**Issue by voxspox** [piwik/piwik#17126]
I want to have more than 5 custom dimension. Thus I call:

`php console customdimensions:add-custom-dimension --scope=visit -vvv`

Because I have no SSH access to the server I call this command via php [passthru](https://www.php.net/manual/en/function.passthru.php) over the webbrowser.

The output is:
```
Adding 1 Custom Dimension(s) in scope visit.
This causes schema changes in the database and may take a very long time.

return code: 0
```
The output and the return code is displayed instantly. Seems to be fast.

But on the configuration page for Custom Dimensions the button still says: "Configure a new dimension (0 of 5 dimensions left)"

Also, I'm wondering why there is no verbose output.

I know using passthru is a bit hacky, but maybe someone has a hint for me :)

using matomo: 4.1.1

**Comment by tsteur** [comment]
@voxspox you need to add `--no-interaction` as there would be usually a confirmation question.

**Comment by voxspox** [comment]
works!

**Comment by voxspox** [comment]
@tsteur I think the error code of the script should not be 0 then. 0 means success, but in this scenario the task "add dimensions" was not successful, it was aborted.

**Comment by tsteur** [comment]
@voxspox I'm not sure what common behaviour in such situations is. If you were to execute this on the console then you would have been asked whether you want to execute this action or not. If you select "no" it seems to me that maybe an exit code of 0 is correct as it correctly exited and did nothing as requested. But not sure if linux / command line behaviour is usually different.
