### ISSUE TITLE
Since updating Matomo  to 4.1.1. my Admin-area is "broken" (can't click on anything)

### ISSUE THREAD

**Issue by tauschn** [piwik/piwik#17124]
Hello,
since updating Matomo  to 4.1.1. my Admin-area is "broken" (can't click on anything) - means I can't handle the Admin-Area for excample create new user, can't click on System, develop, data-security, etc.
Please help!
Thank you!
NT

**Comment by sgiehl** [comment]
Can you see any error in the browser console?
As a workaround: Does maybe the mobile menu work for you? You could try resizing the windows to a smaller size, so the layout switches to mobile.

**Comment by tauschn** [comment]
Hello @sgiehl ,
genious! Idk why, but THIS works! thank you so so much for your help!
Best,
NT

**Comment by sgiehl** [comment]
@tauschn  The mobile menu is actually build in another way. Might still be good to find out why the normal menu doesn't behave like it should... 🤔
