### ISSUE TITLE
Ho to track UserId in vuejs  

### ISSUE THREAD

**Issue by kamran364** [piwik/piwik#17135]
I am trying to track userid in Vuejs through userId:"2", but didn't found any solution, and still getting NULL in DB

**Comment by tsteur** [comment]
Hi @kamran364 I recommend you ask your question in our forum https://forum.matomo.org/ or maybe you can search for it on the internet. I think there are a few search results when eg search for `vue.js userId matomo`. Here in this repository we only manage bug and feature reports unfortunately but don't answer general questions. Thanks for understanding.
