### ISSUE TITLE
Duplicate a Segement

### ISSUE THREAD

**Issue by mkarg67** [piwik/piwik#17140]
In addition to edit a segment a duplicate function would be nice. Often one creating a segment with a lot of conditions. In such cases it is likely that there have to be many of those segments with similar conditions. Duplication would make this process faster.

**Comment by tsteur** [comment]
Thanks for creating this issue @mkarg67 I'll close this for now as a duplicate of https://github.com/matomo-org/matomo/issues/7246

**Comment by tsteur** [comment]
Thanks for creating this issue @mkarg67 I'll close this for now as a duplicate of https://github.com/matomo-org/matomo/issues/7246
