### ISSUE TITLE
Call to undefined function Piwik\Plugins\DevicesDetection\getClientTypeMapping()

### ISSUE THREAD

**Issue by webmasterscd** [piwik/piwik#17141]
Good morning,
I got error 500 while upgrading v3 to v4 using the one-click upgrade option, so I backed up the server to the yesterday save and this error occurs...

Thanks for helping.

**Comment by Findus23** [comment]
Hi,

The only report of this issue I can find is https://forum.matomo.org/t/call-to-undefined-function-problem-lasst-sich-nicht-losen/39512

Can you make sure that all files are the ones they should be and when in doubt replace them with the proper ones from https://builds.matomo.org/

It would also be useful if you could look in your server log to find the error you got with Matomo 4.

**Comment by webmasterscd** [comment]
Problem solved, I uploaded the new version of matomo in my server and I updated via command line (actually, database is too big to update via browser so I was redirected to the "error 500" page...)  

Now version 4.1.1 is successfully running.

Thank you
