### ISSUE TITLE
Tag Manager Publish isn't pushing new Tags and Triggers

### ISSUE THREAD

**Issue by elrauk12** [piwik/piwik#17147]
Let me preface this by saying that I'm running 3.14.0. Yes, I know this is not the current version. We set everything up about 7 months ago and the Publish Tag Manager function worked fine. Now it doesn't, so this hardly feels like an update issue.

Now when we use publish, this is what happens:
- This "Updating data..." text displays for about 30 seconds, then just goes away with no confirmation message.
- I check the list of Versions and I can see the one I just published, but it doesn't say live.
- I download and check the version JSON, and it contains none of the new tags/triggers I've added.

<img width="656" alt="Screen Shot 2021-01-25 at 4 11 39 PM" src="https://user-images.githubusercontent.com/59264992/105782114-b8482b00-5f28-11eb-97df-99ed3432f6f4.png">

It seems like something is preventing the Publish action from actually doing anything, other than just creating a version. If this is specifically something that is known and was fixed by a Matomo update, then so be it.

**Comment by tsteur** [comment]
@elrauk12 sorry about that. Any chance that you could create an account for us on your Matomo so that we could get roughly an idea what is happening there? Or maybe you could export the container so we could try and reproduce it? If so, can you send us an email to hello at matomo.org ?

There's a small chance it'll be fixed in the next release already but it's hard to tell.

**Comment by rabbit28399** [comment]
Hello,

is this problem solved? I am having this problem on 4.6.1

Any advice would be appreciated.

**Comment by rabbit28399** [comment]
@elrauk12 do you have any solutions?

**Comment by elrauk12** [comment]
No, never found any solution. We ended up ditching Matomo. It's just not polished and consistent enough
