### ISSUE TITLE
Add Performance Metrics to Visits Over Time graph

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17145]
The main Visits Over Time graph can only display the pre Matomo 4 average generation time.

It would be great if the new performance metrics could also be shown there.

![grafik](https://user-images.githubusercontent.com/6266037/105745164-48449f80-5f3e-11eb-8d06-fe5cf3b440a0.png)

**Comment by tsteur** [comment]
refs https://github.com/matomo-org/matomo/issues/17013

**Comment by atom-box** [comment]
A user said the feature they would like to see is
_Question:
Answer:
events displayed on a graph like visits_

**Comment by mattab** [comment]
Appreciate your effort in raising this! As it aligns with Issue https://github.com/matomo-org/matomo/issues/17013 I will close this one.
