### ISSUE TITLE
Tracking requests might not be loaded because of CORB

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17159]
In the browser developer console I see a warning linking to https://www.chromestatus.com/feature/5629709824032768 anyone seen this before?
See https://www.chromium.org/Home/chromium-security/corb-for-developers for more information.

HTTP with 204 seems to work but 200 blocked. `send_image=0` is used so it should have sent an HTTP 204 header. Actually... this output happens because of bulk requests. The request with HTTP 200 was sent as a bulk request in this example.

![image](https://user-images.githubusercontent.com/273120/106067345-64755600-6163-11eb-88af-b99e08f601f6.png)

response headers:

![image](https://user-images.githubusercontent.com/273120/106067376-6fc88180-6163-11eb-9a50-5c648fb55b6b.png)

The console warning reads `Cross-Origin Read Blocking (CORB) blocked cross-origin response XYZ with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

For a URL where this can be reproduced feel free to ping me privately. I'm not sure if the tracking request will be executed or if just the response is not loaded. 

Goal of this issue is to make sure such requests are tracked and the warning is no longer shown.

**Comment by sgiehl** [comment]
@tsteur I'm not very deep into CORS/CORB, but based on the description CORB is only applied for this type of content: JSON, HTML, XML. According to your screenshot, the bulk request returns a json, with http 200. Maybe the response type is the problem in that case. BulkTracking currently has it's own response handler, which always uses json. See https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/BulkTracking/Tracker/Response.php
Not sure if there was an intention that bulktracking requests are returning json content, is the response used in some cases? 🤔

**Comment by tsteur** [comment]
I reckon to solve this issue be great if it also supported `send_image=0` I suppose and then returned an HTTP 204. There should be no reason for returning JSON in a JS tracker request. And we're not reading the response.

The `send_image` would need to be set along `{requests: [], token_auth: 'optional', send_image:0}`. Be great to add this 👍

**Comment by bitsagarob** [comment]
We are still having this issue even when using latest matomo.js script

**Comment by tsteur** [comment]
@segersrobbert are you using the latest version of Matomo? In case you are, is there any chance you can post a link to where we can reproduce this?

**Comment by dasuchin** [comment]
I'm having a similar issue with a self-hosted version of Matomo, using the latest version. I have Matomo up and running on `analytics.team.example.com` with my applications running on `name.application.example.com`. I'm getting the same CORB message on the requests. The requests to matomo.js and matomo.php are both returning a 200. Not seeing any results in the dashboard though.

**Comment by inkskull** [comment]
Hello,
Still got what seems to be the same issue : 
﻿﻿
matomo-tracking.min.…cc00d517f6177b.js:2 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://monserveurencarton.eu/yunohost/sso/?r=aHR0cHM6L...Lmpz with MIME type text/html. 

Tried it on Firefox : get the same answer

**Comment by FrozenBlueSky** [comment]
I have the same issue. Usind version 4.10.1

matomo.js:35 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://... with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
