### ISSUE TITLE
Scheduled task

### ISSUE THREAD

**Issue by ngothanhtam** [piwik/piwik#17150]
Scheduled Task seems working once though i setup $this->hourly (It has run once and has stopped)
Must i need to configurate more?

class Tasks extends \Piwik\Plugin\Tasks
{
    public function schedule()
    {

        $this->hourly('remindMeToLogIn');
    }

    public function remindMeToLogIn()
    {
        $mail = new \Piwik\Mail();
        $mail->setFrom('noreply@xxx.com');
        $mail->addTo('xxxx@gmail.com');
        $mail->setSubject('Check stats');
        $mail->setBodyText('Log into your Matomo instance and check your stats!');
        $mail->send();
    }
   }

**Comment by sgiehl** [comment]
Hi @ngothanhtam
Please use our forum for such questions. We usually don't answer questions here.
You can find some details on scheduled tasks here: https://developer.matomo.org/guides/scheduled-tasks
In general tasks are only executed when
* a archive:cron runs (which will execute the tasks afterwards if not disabled)
* when browser archiving is enabled: a random visit tracked or a visits to the stats might trigger archiving (which then would trigger the tasks)
