### ISSUE TITLE
Can't make Matomo work with Discourse forum

### ISSUE THREAD

**Issue by HECFM** [piwik/piwik#17157]
Hi the Matomo team and thanks for your great work !
Have been trying for 10 days now to link my self hosted Matomo instance fo my self hosted Discourse forum.

I followed the tutorial with the [theme component of Discourse dedicated to Matomo](https://meta.discourse.org/t/script-to-enable-matomo-analytics-on-discourse/33090).

On my Matomo home screen I've a message saying there is no date for the moment and that I have to put these configurations : 

- Matomo URL: (edit removed by author)
- ID of your site : 1

And the printscreen within the theme component of Discourse : 
(edit removed by author)

What did I do wrong ?

**Comment by tsteur** [comment]
@HECFM I checked your website and the configured CSP is preventing to load our tracker. You'll want to have a look at https://matomo.org/faq/general/faq_20904/ and check how this can be configured in your server environment.

**Comment by HECFM** [comment]
I already looked into the CSP aspect and here is what I already did in Discourse settings.
Do I need to add another thing ?
(edit removed by author)

**Comment by tsteur** [comment]
Hi @HECFM sorry I'm not so much familiar with how this works in discourse. I suggest you ask in the discourse forum how this can/needs to be configured.

**Comment by HECFM** [comment]
Hi @tsteur I went to the Discourse forum and [the support team told me there](https://meta.discourse.org/t/forgot-to-edit-csp-when-adding-tracking-code-via-custom-component/174811/8) that they see the Matomo tracker loading just fine and that it isn't a CSP issue.
They are suggesting it might be on the Matomo side.

What can I do to make Matomo work on Discourse ?

**Comment by Findus23** [comment]
@HECFM If you want to, we can continue this discussion on the Matomo forum: https://forum.matomo.org/
I can see on your site that the piwik.js is blocked by CSP as the firefox developer tools nicely show.

I'd recommend you to look into the `content security policy script src` discourse setting and add your Matomo domain there.
