### ISSUE TITLE
Graphical bug when viewing drop down menu for users permissions

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17161]
When changing a users permissions for a website, the dropdown menu shows the below users permissions above the dropdown menu.

![image](https://user-images.githubusercontent.com/20905821/106195830-9810b880-6215-11eb-8a76-ac33e33ea377.png)

![image](https://user-images.githubusercontent.com/20905821/106195874-a52da780-6215-11eb-863a-59e9e19264ca.png)

It does not however occur when the menu is above the role selector:
![image](https://user-images.githubusercontent.com/20905821/106196022-cee6ce80-6215-11eb-97bb-fb3bf25fbabf.png)

**Comment by Starker3** [comment]
Additional info: This prevents you from clicking on the role and selecting it for that user if it is above the role you wish to choose.
For example the "Write" role above cannot be clicked because it has the "No access" from the below user above it.

**Comment by sgiehl** [comment]
Guess that might already be fixed with https://github.com/matomo-org/matomo/pull/17082
