### ISSUE TITLE
Request for Hiding ipaddress without rewriting raw data from "Visitor ⇒ Visit Log" screen.

### ISSUE THREAD

**Issue by skingoh** [piwik/piwik#17165]
We use a Matomo in on-premises environment.

We are considering about suppressing to be displayed the accesor's IP address that can be confirmed by anyone on the "Visitor ⇒ Visit Log" screen, because of complying with the GDPR.

In advanse, We considered using the function "IP address anonymization" that already released, but we found the face it takes huge amount of times to rewrite all previews data and we thought that it is difficult to use this function immediately.
As a provisional measure, we need a function which hide IP address when being displayed without rewriting raw data.
We guess there are many users also bother the same problem and need to be cared.

We'd like to request the function in the roadmap for future version upgrades.

Best regards.

**Comment by tsteur** [comment]
Hi @skingoh is this a duplicate of https://github.com/matomo-org/matomo/issues/17164 ?

**Comment by skingoh** [comment]
Hi. @tsteur Thank you for reply.
I'm sorry to raise similar issue duplicately. I'll close here.

About the other issue #17164, we're refering for the comment you wrote and considering to determine our direction. 

regards.
