### ISSUE TITLE
Update Matomo to 3.13 to 4.1.0 leads to blank page

### ISSUE THREAD

**Issue by brijoyj** [piwik/piwik#17167]
After upgrade Matomo is not working as expected.
I see a blank page https://xxx.com/index.php?module=CoreUpdater&action=

Logs:
I manually did console core update and leads to the following error. Verified the DB tables are updated. 

ERROR [2021-01-30 04:49:23] 3387  Fatal error encountered: /var/www/html/libs/Zend/Db/Statement/Pdo.php(292): Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes)
Matomo encountered an error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) (which lead to: Piwik and/or some plugins have been upgraded to a new version.

Can you tell us what is the issue?

**Comment by brijoyj** [comment]
![image](https://user-images.githubusercontent.com/49916563/106347462-5a974400-6284-11eb-8654-b1990141a0d2.png)
Further i did all the plugins deactivate, still same issue

**Comment by tsteur** [comment]
Hi @brijoyj sounds like there's a memory issue. Is there any chance you can increase the memory limit to say 256MB and try again? The update itself usually doesn't use much memory. However, it's possible that some query requires a bit of memory if you have eg a lot of users, or heaps of data or so. Do you remember from which version of Matomo you upgraded?

> I manually did console core update and leads to the following error. Verified the DB tables are updated.

Be also great to let us know what exactly you mean by "manually" as there a few different ways like "manually executing each query in the database" or "executed the cli update command" etc. 

I suppose when you open the regular Matomo URL it redirects you to this URL? This would suggest there's still some update outdanding.

**Comment by brijoyj** [comment]
I have 2 GB Ram allocated in OpenShift. We are using Nginix Web server for Matomo. We tried upgrading from 3.4.1 to 4.1.0.

i meant to say manually using CLI commands (./console core:update) and it list all the sql queries. So i manually copied and pasted to my MySQL server and ran it. Hope it answers u r question

**Comment by tsteur** [comment]
Any chance you can execute `./console core:update` again on the command line and proceed? Maybe it runs through on the CLI to finish the update. If you could otherwise increase the memory for PHP that would likely fix the issue too.

**Comment by brijoyj** [comment]
I did core:update and the result is the same (memory issue). Not sure how to fix the PHP memory issue. For now i downgraded to 3.14.1 , and its working.

**Comment by dev-101** [comment]
It doesn't matter how much memory your server has. It **matters how much it can allocate to PHP** alone. Either edit your PHP ini file and increase 128M to something like 512M, 768M or 1024M or consult your hosting provider for help. Reload / Restart server after the change.

**Comment by michalkleiner** [comment]
Hello there! We will close this issue now as there's no response for several years now. If there's still a problem please open a new issue. We do recommend upgrading to Matomo 5.
