### ISSUE TITLE
Actions of events are not considered correctly

### ISSUE THREAD

**Issue by 4ev** [piwik/piwik#17177]
Does not correctly count the actions of events, in one year less than one day

16 events in one day, and 13 events in the whole year

What to do to recalculate the actions of events?

**Comment by sgiehl** [comment]
Hi @4ev.

Thanks for creating the issue. Based on the images you had added in an earlier version of the issue it seems you are referring to results of a search in a report. If this is the case, this can be explained quite easily.
When a report is built the dataset is limited to a configured amount of rows. Depending on the report type that might be for example 500 rows. So when a daily report is built all rows will be calculated, but only the first 500 rows are included in the report (normally sorted by count of visits). The other rows are truncated. When the reports for week, month and year are built, the already calculated reports for the next smaller period are used to sum them up. So for year all monthly reports are combined into one. For those combined reports the same limit applies. That means that if the report has more than 500 rows after the monthly reports were combined, some rows are truncated again. Therefor it can happen, that rows are included in daily reports, but not in weekly, monthly or yearly reports.

You can find more information on how to extend those row limits here: https://matomo.org/faq/how-to/faq_54/

Hope that answers your question.
