### ISSUE TITLE
_idvc is no longer available with Matomo 4

### ISSUE THREAD

**Issue by Sayeeda12** [piwik/piwik#17178]
We used idvc to manage visits but I don't see it being passed as part of the request anymore. Is this changed? How do we know which session the visitor is in? How can I get the visit count now? Please help

**Comment by Sayeeda12** [comment]
_idvc *

**Comment by diosmosis** [comment]
Hi @Sayeeda12, the _idvc parameter is no longer used after Matomo 4, the visit count is now determined server side via a running counter. Can you explain what you use the parameter for and how you use it? To get the information now you'd have to use the `Live.getLastVisitsDetails` API.

**Comment by Sayeeda12** [comment]
Hi,

   It's unfortunate that idvc is removed. We use it heavily to determine
visits and manage sessions in our JS analytics library. It is used as part
of our request and within customRequestProcessing, we do a lot of
operations based on this parameter.


You say that it's handled at server side now. But is it still dependent on
sessionCookieTimeout? Earlier when session timeout expired, visit count
incremented. Is it the same now? How? Please explain. Also I'm not sure how
to use Live.get.....() within our JS library. Please provide some
references if possible. Thanks in advance.

Kind regards,
Sayeeda

**Comment by diosmosis** [comment]
Hi @Sayeeda12, the visit count is incremented server side if the last visit time was further in the past than the visit length configured in matomo.

If you need it client side it would probably be easiest for you to simply keep track of it yourself. You can create a cookie value holding the last visit time and the current visit count. If the current time for a page view is `> the last visit time + visit length` increment the visit count. Update the last visit time on every page load.

For future requests for information on how to use or integrate matomo, please use the forums: https://forum.matomo.org/ as the issue tracker is only for feature requests and bug reports.
