### ISSUE TITLE
Issues on map naming

### ISSUE THREAD

**Issue by uhlhosting** [piwik/piwik#17171]
In swiss map the cantons are wrong displayed:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/6324047/106371783-ceab1800-6368-11eb-81b9-b90ef71125fe.png">

This should be Zürich ,not Zrich . Such canton does not exists.

**Comment by uhlhosting** [comment]
@Findus23 more cantons have wrong name, I see wherever a üöä were used. Make sure to double check them all.

**Comment by Findus23** [comment]
@uhlhosting 
As you are probably more familiar with Switzer cantons than me, can you help me list the incorrect ones?

I fixed Zürich and Graubünden which seems to be all of them (according to https://de.wikipedia.org/wiki/Kanton_(Schweiz)#Liste_der_Schweizer_Kantone_mit_ihren_Eckdaten)

**Comment by uhlhosting** [comment]
I will double check and give feedback.

**Comment by uhlhosting** [comment]
Genève is also wrong
