### ISSUE TITLE
Is it possible to filter matomo reports based on dynamic values for multiple custom dimensions while embedding the reports

### ISSUE THREAD

**Issue by Lakkanna** [piwik/piwik#17175]
Hi, i have multiple customDimensions based on the dynamic value is it possible to show matching records only in report?
i tried to use custom report plugin but there i need to create each report for one value, which is not easy to maintain.

customDimension1='first-value'
customDimension2='second-value'

`https://example.com/index.php?module=Widgetize&action=iframe&secondaryDimension=eventName&disableLink=0&widget=1&moduleToWidgetize=Events&actionToWidgetize=getAction&idSite=1&period=day&date=yesterday&disableLink=1&widget=1&customDimension1=somevalue&customDimension2=another-value`

i need to filter out the data based on some dynamic value for customDimensions and need to embed, please let me know how can i achieve this one

**Comment by tsteur** [comment]
@Lakkanna does maybe Segmentation work for you see https://matomo.org/docs/segmentation/ and https://developer.matomo.org/api-reference/reporting-api-segmentation ?

**Comment by Lakkanna** [comment]
i checked segmentation, i didn't find way to integrate with **Widgetize** module, filtered data can be used only through API's?

**Comment by Lakkanna** [comment]
i got the solution, i have suffixed **&segement=dimension1==value1;dimension2==value2** to the widgetize module url, it's seems working, thanks

**Comment by tsteur** [comment]
Great, glad this works @Lakkanna
