### ISSUE TITLE
No server-to-server tracking when "Only track visits and actions when the action URL starts with one of the above URLs." checked

### ISSUE THREAD

**Issue by traderjean** [piwik/piwik#17170]
Hey everyone, 
Using an ecommerce API to track conversions. Tracking is working fine in JS. But the user conversion is sent from another server and seems like matomo is blocking it when the options "Only track visits and actions when the action URL starts with one of the above URLs." is checked.

Anyone has an idea how I can fix that ? 
Thanks a lot.

**Comment by traderjean** [comment]
v

**Comment by tsteur** [comment]
hi @traderjean you will then need to set a page URL in the tracking request that matches a configured URL in Matomo.

If you're using the PHP tracker, that be for example `$tracker->setUrl()`. If you're using the Tracking API, you would need to use the `url` tracking parameter.
