### ISSUE TITLE
Actions of same user sometimes splitt to several visits

### ISSUE THREAD

**Issue by agmorpheus** [piwik/piwik#17191]
Hello,

after the update from Matomo version 3 to 4 I have noticed the problem, that sometimes actions of a user is splitt into several visits. Each action has its own visit. This is pretty strange. Sometimes all is good, sometimes it looks like this:

![image](https://user-images.githubusercontent.com/16916776/106922835-bbec6680-670d-11eb-9b1c-8b097ad7b98c.png)

**Comment by Findus23** [comment]
https://forum.matomo.org/t/besuch-wird-auf-mehrere-besuche-aufgeteilt/40527 contains more details about this

**Comment by diosmosis** [comment]
hi @agmorpheus, would you be able to post the visitorid for the visits you're displaying? Are they the same?

And do you have any interesting INI config set, for example, `[Tracker] enable_userid_overwrites_visitorid`?

**Comment by agmorpheus** [comment]
Hi @diosmosis, the visiter id is the same only without "User_". Even when I remove the visiter id, the problem is still there.
No, I have normal settings in the config file. 
Can I provide a log file where you can see why the actions are split between multiple visits?

**Comment by diosmosis** [comment]
Hi @agmorpheus, if you could send a log file that could be very helpful (you can email me at dizzy@innocraft.com). Can you also tell me how you are tracking visits? Are you using the JS tracker or are you importing logs?

**Comment by agmorpheus** [comment]
Hi @diosmosis, I am using the JS tracker. For a log file I have to [enable ](https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker)it, right? Or is there a log that is written by default?

**Comment by diosmosis** [comment]
@agmorpheus the only log that would help with this are webserver logs (you'll have to extract visits with the single visitor ID). If this isn't something you have, we'll have to try something else (if you can provide access to your matomo & the website you are tracking it might be possible to figure out why this is happening).

**Comment by agmorpheus** [comment]
@diosmosis I sent you an email

**Comment by diosmosis** [comment]
Closing as user reports this has been resolved
