### ISSUE TITLE
Video events are not captured (or very few)

### ISSUE THREAD

**Issue by geosigno** [piwik/piwik#17193]
It's been 2 weeks i'm using Matomo on a video stream app and I'm seeing a quite significant discrepancy between visit and play events. 

The only page with the Matomo tracker are the video pages. Right now, for 1000 visits, I got 10 plays, which I know is wrong. Even when clicking the play button a dozen times, I don't see any data in Matomo real time, or normal data after a while.

The video player used in the app is JWplayer. According to the doc, there is nothing special to do to enable the media analytic, only exception is to setup the video title on the JW player, which I already did.

Do I need to activate something to have all the media analytic available? Or should I use manual custom events play when user clicks on player, etc? But in that case i may have duplicata at some point with Matomo raw data right.

**Comment by tsteur** [comment]
Hi @geosigno  as far as I understand you're using our Media Analytics plugin? As we only manage issues for Matomo core in this issue tracker, could you contact our support at shop@innocraft.com about this? They will be happy to follow up. Thanks for this @geosigno
