### ISSUE TITLE
Obtenir de Matomo un tableau adequat

### ISSUE THREAD

**Issue by Patrick-devX** [piwik/piwik#17195]
Salut Matthieu, @mattab 

Je solliciterai bien ton aide pour pouvoir obtenir un tableau de la structure [suivante](https://github.com/Patrick-devX/ML-On-AWS/blob/main/DatenstrukturAusMatomo.pdf),

Merci d'avance et bonne journée
Patrick

**Comment by diosmosis** [comment]
Hi @Patrick-devX, unfortunately we don't answer questions in this issue tracker but only handle feature requests or bug reports. It would be great if you could ask this question in our forum: https://forum.matomo.org/. You may also want to take a look at the https://plugins.matomo.org/CustomReports premium feature, though I'm not 100% sure if it will provide what you want. Thanks for your understanding.
