### ISSUE TITLE
Scheduled Email report does not pick up custom report widgets

### ISSUE THREAD

**Issue by MISTAnalytics** [piwik/piwik#17190]
**What**
Matomo does not seem to pick up the custom reports in the scheduled email functionality. In the attached screenshots (part I, II, III) a full scheduled Matomo report is being displayed. However, the first four sections are being displayed which are basic Matomo widgets but the last four sections are not which are custom report widgets. The report stops after Video Titles but there are more sections expected.

**Why**
It helps to be able to schedule a full report instead of only parts of the scheduled report.

_The scheduled report_

![Matomo scheduled email report part I](https://user-images.githubusercontent.com/46724952/106922537-7465da80-670d-11eb-90fb-dfcec611f562.png)
![Matomo scheduled email report part II](https://user-images.githubusercontent.com/46724952/106922540-74fe7100-670d-11eb-979e-3d9f344422eb.png)
![Matomo scheduled email report part III](https://user-images.githubusercontent.com/46724952/106922538-74fe7100-670d-11eb-8dbb-b089464f9d74.png)

**Comment by diosmosis** [comment]
hi @MISTAnalytics, sorry you're experiencing this issue. Would you be able to post the definition of the email report? Would you also be able to post the response to the `API.getReportMetadata` API method (as an attachment as it should be quite large)?

(If any of these have information you wouldn't want to post here, you can also email them to me at dizzy@innocraft.com.)

**Comment by MISTAnalytics** [comment]
Hi @diosmosis, I just sent you all the requested input by mail.

Please let me know.
