### ISSUE TITLE
Users Flow-Plugin: Show Users Flow based on user interactions and custom events

### ISSUE THREAD

**Issue by straussCS** [piwik/piwik#17201]
Noways, especially when it comes to modern single page applications it would be very helpful for us to not only view Users Flow based on pageviews. 

Instead we (and our customers) need a solution, which allows them to be able to observe the vistors interaction on the page based on events.

Is it possible to choose "events" from event tracking as a source in the Users Flow Plugin?

**Comment by tsteur** [comment]
Hi @straussCS thanks for creating this issue. Unfortunately we only manage issues for Matomo core here. As the question is about a premium feature can you email our support at shop@innocraft.com about this? Sorry about the inconvenience @straussCS
