### ISSUE TITLE
Behaviour > Pages > PAGE URL table column - no longer bold font in 4.x ?

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#17204]
Sorry if it's a duplicate issue, couldn't find it with search.

I know it's purely cosmetic, but ever since upgrading to 4.x page links / groups are no longer in bold font, and this puts such unbelievable strain to my eyes. Am I the only one complaining about this minor issue or there are others as well?

Here's the demo link: (**PAGE URL** table column)
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=General_Actions&subcategory=General_Pages

**Comment by tsteur** [comment]
Thanks @dev-101 I believe that might be a regression indeed. Be great to comment if it was maybe changed on purpose.

**Comment by dev-101** [comment]
Well, I will close this issue for now. It doesn't seem to be 'popular', and I am already accepting the truth :)

**Comment by tsteur** [comment]
@dev-101 I hope you don't mind me reopening it. We're planning on fixing this (it's already in a milestone to be worked on).

**Comment by sgiehl** [comment]
@tsteur We actually don't have bold fonts for any other table. Why should only the page url reports have a bold font on the label column? Imho that's a bit inconsistent. Or shall we add a bold to all label columns?

**Comment by dev-101** [comment]
Of course, this is just an example page, change in all tables should be uniform. I don't have old version anywhere anymore, but I am sure it was bold in the first column. Here, this is from an old version where you can barely see the left edge font in bold: https://cloud.githubusercontent.com/assets/5383059/13856125/0f9f390c-ec74-11e5-95af-371d43e7dfa3.png

Anyway, I understand if this was on purpose... guess I have to get used to it. I think font was changed as well, and that's what is bothering me at the same time :)

**Comment by sgiehl** [comment]
@dev-101  having a bold label column would be fine. just wanted to point out that it should be consistent as the issue description only is about the action reports.

**Comment by tsteur** [comment]
@sgiehl thanks for this. Thought this was the case across all tables but now seeing in eg https://github.com/matomo-org/matomo/blob/3.14.1/tests/UI/expected-screenshots/UIIntegrationTest_referrers_allreferrers.png that this wasn't the case. Only in actions tables indeed by the looks https://github.com/matomo-org/matomo/blob/3.14.1/plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_initial.png . It wasn't even the case for content tracking etc https://github.com/matomo-org/matomo/blob/3.14.1/tests/UI/expected-screenshots/UIIntegrationTest_actions_content_piece.png so @dev-101 I will close this for now indeed as a wontfix as it seems it was changed on purpose.

**Comment by dev-101** [comment]
I *knew* it :)
Thanks for those screenshots, though... reminded me how great it was before.

**Comment by sgiehl** [comment]
@dev-101  I you liked it more the other way. Feel free in trying to create a new theme ;-)
