### ISSUE TITLE
segmentation: add numeric operators for custom dimensions

### ISSUE THREAD

**Issue by voxspox** [piwik/piwik#17219]
## Summary

In the segmentation editor the dropdown menu with operators shows only text operators like "contains" "starts with" for custom dimensions. 

I have numeric values in my custom dimensions. I want to see numeric operators for custom dimensions, like "less than", etc.

**Comment by tsteur** [comment]
Thanks for creating this issue @voxspox  be great to have this indeed. I will close as as it's a duplicate of https://github.com/matomo-org/matomo/issues/16267 and also refs https://github.com/matomo-org/matomo/issues/5372

**Comment by voxspox** [comment]
thx :) didn't find the other issues
