### ISSUE TITLE
Add system check: Real live check if the database is ok/has the right structure

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17211]
see https://github.com/matomo-org/matomo/issues/17181#issuecomment-777209894

It might not be easily doable though. Like we'd need to potentially create many tables with a different prefix or a new DB and install Matomo there and then compare the structure with the current structure. Maybe there could be a basic check if all expected columns exists. Checking the type and default values etc might be bit more complicated as they might be reported differently by different MySQL forks not sure.

**Comment by Findus23** [comment]
see also https://github.com/matomo-org/matomo/issues/11540

**Comment by tsteur** [comment]
closing as a duplicate of https://github.com/matomo-org/matomo/issues/11540
