### ISSUE TITLE
Create new Dashboard popup does not show radio button to select options (empty, default)

### ISSUE THREAD

**Issue by KrzysztofMadejski** [piwik/piwik#17223]
Version: 4.1.1

## Current Behavior

<img width="1583" alt="Screenshot 2021-02-16 at 15 02 33" src="https://user-images.githubusercontent.com/849975/108073498-664a7f00-7068-11eb-8cf2-2f10cb13e956.png">

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

Matomo version: 4.1.1
PHP version: 7.4.15
* Additionally installed plugins:

* Browser: Chrome 88.0.4324
* Operating System: Mac

**Comment by sgiehl** [comment]
Hi @KrzysztofMadejski 
Thanks for reporting this issue. I was able to reproduce it. Will have a quick look if it's easy to fix...

**Comment by Findus23** [comment]
It might be related to https://github.com/matomo-org/matomo/pull/16986 and https://github.com/matomo-org/matomo/issues/16983
