### ISSUE TITLE
Bulk sending events

### ISSUE THREAD

**Issue by corentinc-old** [piwik/piwik#17235]
Hello !

I would like to optimize the sending of my matomo events.
What would be the maximum events Matomo could handle in a unique http post request ?

Thanks :)

**Comment by sgiehl** [comment]
Excellent question. Our javascript tracking actually sends bulk requests in chunks of max 50 requests at once. But Matomo should be able to handle more. I guess that would depend on your server configuration and how much POST content the webserver actually would accept. Sending too man requests could also run into problems if you server has a max execution time for php scripts.

**Comment by corentinc-old** [comment]
Thank for your anwser.

I currently use matomo-java-tracker.
I will do some tests to determine the limit I should put.

Have a nice day !
