### ISSUE TITLE
just space characters are missing in German translation

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17245]
Matomo V 4.2.0

settings (module=CoreAdminHome&action=home)

German translation

system summary: segments: after the number(zeroI is a space to the next word missing

![grafik](https://user-images.githubusercontent.com/1645099/108771203-9f4c8d00-755b-11eb-8265-2f198d395df0.png)

**Comment by math-GH** [comment]
English is fine

![grafik](https://user-images.githubusercontent.com/1645099/108771848-7d9fd580-755c-11eb-96a0-bf5c54d1354a.png)

**Comment by Findus23** [comment]
Hi,

The mistake is in the translation:
https://github.com/matomo-org/matomo/blob/817b3ba57d89fe751be5160d0a183a4e562fb528/plugins/CoreHome/lang/de.json#L87

I'll fix it on Transifex.

**Comment by Findus23** [comment]
It turns out it was even me who introduced the error (those spaces are nearly invisible with the transifex UI:
![grafik](https://user-images.githubusercontent.com/6266037/108776451-b478ea00-7562-11eb-8b6a-6c9b88a13aff.png)
