### ISSUE TITLE
core:archive error: Segment 'visitorFirstVisitTime' is not a supported segment.

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#17257]
Started on Jan 24th

Got the following error (every hour) on demo2 when the archive runs via cron

> ERROR [2021-02-24 00:49:02] 1173217 Uncaught exception: /home/piwik-demo2/storage/www/demo2.piwik.org/core/Segment.php(210): Segment 'visitorFirstVisitTime' is not a supported segment.
Segment 'visitorFirstVisitTime' is not a supported segment.

>  [Exception]
> Segment 'visitorFirstVisitTime' is not a supported segment.

> core:archive [--url="..."] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--skip-segments-today] [--force-periods[="..."]] [--force-date-last-n="..."] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]] [--force-all-websites] [--force-report[="..."]]

**Comment by diosmosis** [comment]
@mattab this might be due to the recent change to code checkout when we released 4.2.1. The premium plugins no longer exist (they were untracked files, so they were probably removed).

**Comment by diosmosis** [comment]
@tsteur fyi, this is a configuration issue on demo2 so shouldn't be a blocker for a 4.2.1 release

**Comment by tsteur** [comment]
👍  do we need to do something or is it @mattab  or was it maybe only a one time issue?

**Comment by diosmosis** [comment]
there was a change made on demo2 to automatically remove untracked files so pulls would always work. unfortunately premium plugins are untracked files, so they got deleted too. So I guess we have to change the command back and reinstall the premium plugins? i'm not sure how premium plugins got on there to begin with (manually installed?)

**Comment by tsteur** [comment]
@mattab I have removed `git add -A .; git stash` and install the plugins again so assuming this is fixed. It might be overall not needed what you added there as it may be fine that when we're testing something we wouldn't want it to be overwritten every time and otherwise you could maybe add a git checkout or something.

**Comment by mattab** [comment]
Ok makes sense. I will close the issue for now.
