### ISSUE TITLE
trackPageView still sends page performance report after disablePerformanceTracking

### ISSUE THREAD

**Issue by ufoproger** [piwik/piwik#17267]
## Expected Behavior

Disable all performance tracking. This feature required for single page application (SPA).

## Current Behavior

**With disablePerformanceTracking** all page views contains old page performance.
**Without disablePerformanceTracking** first request contains not complete page performance (without DOM info), second request contains full page performance and other next requests does not contain page performance data.

## Possible Solution

Additionally check variable `configPerformanceTrackingEnabled` before calling `appendAvailablePerformanceMetrics(request)`.

## Steps to Reproduce (for Bugs)

1. Create single page application;
2. Push `disablePerformanceTracking`;
3. Track page view — page performance is sent;
4. Change `window.location`;
5. Track page view — old page performance is sent. 

## Context

SPA without page reload.

## Your Environment

* Matomo Version: 4.2.0
* PHP Version: PHP/7.4.15
Server Operating System: Docker image **matomo:4.2.0**
* Additionally installed plugins: none

**Comment by tsteur** [comment]
Hi @ufoproger thanks for reporting this bug and the suggestion for the solution 👍  very appreciated. I've created the PR in https://github.com/matomo-org/matomo/pull/17275 and the fix should be included in the 4.3.0 release (not the next 4.2.1 release)

**Comment by tsteur** [comment]
Sorry didn't notice you had already created a PR. closed mine again :)
