### ISSUE TITLE
Ecommerece: Cart stats by Campaign

### ISSUE THREAD

**Issue by dl-lim** [piwik/piwik#17284]
I'm using the API to call Campaign Names, sources, etc (Sales by Referrer), via the CSV, and in the documentation, it is said to add `&abandonedCarts=1` or `&idGoal=ecommerceAbandonedCart` to the URL, but these don't show the abandoned cart info in the pull. 

Alternatively, if there is a way to track just the number of Add to Cart or Checkouts, even without the abandoned cart info, is this currently built in to the Ecommerce module or would it have to be set up as a custom goal?

Most importantly, it needs to be tracked to the relevant campaign ID or other parameters

**Comment by diosmosis** [comment]
Hi @alderson59, unfortunately we don't answer questions in this issue tracker but only handle feature requests or bug reports. It'd be better to ask this question in our forum: https://forum.matomo.org/ . Thanks for your understanding.
