### ISSUE TITLE
this.setRequestQueueInterval() doesn't work as expected

### ISSUE THREAD

**Issue by Sayeeda12** [piwik/piwik#17291]
Hi colleagues,

       I've been using Matomo library for quite some time now and I recently implemented bulkTracking using the library. I wanted to set an interval for which duration the events will be queued and the bulk request will be sent after this interval.
I got to know that setRequestQueueInterval() can be used to set the queue interval. However, it doesn't work like an interval but rather inactivity time after which request is fired.

 **What I mean here is** - I set the timeout to be 15 seconds and if I start using the application at 4:00:00 pm and used it continuously for 1 minute, I expect that at the end of my 1 min activity, there should be 4 requests fired. However, there's no request fired at all. Rather, there's 1 request fired at 4:01:15 pm, i.e., after 15 seconds of inactivity from 4:01:00 pm. 

is this a bug? How do I achieve my requirement? Kindly let me know. Thank you.

**Comment by sgiehl** [comment]
Hi @Sayeeda12,
unfortunately we don't answer questions in this issue tracker but only handle feature requests or bug reports. It'd be better to ask this question in our forum: https://forum.matomo.org/ .

Btw. It seems you maybe misunderstood the purpose of bulktracking. Bulktracking is a technique to send multiple tracking requests at once. Those tracking requests still need to be fired using `trackPageView`, `trackEvent` or similar. See https://developer.matomo.org/api-reference/tracking-api#bulk-tracking
