### ISSUE TITLE
Private life configuration should be available per site

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#17309]
If my On Permise Matomo server is used to analyze Internet and Intranet sites (small organization), the private life configuration should be available per site instead of for all sites.

![image](https://user-images.githubusercontent.com/79993552/110142854-e433b780-7dd6-11eb-8455-7a8b301f25c9.png)

**Comment by Findus23** [comment]
Hi,
This sounds very similar to https://github.com/matomo-org/matomo/issues/6653

**Comment by heurteph-ei** [comment]
Oh, yes, you're right. When I searched on the backlog, the filter `is:issue` was checked by default and I did not see the #6653
