### ISSUE TITLE
Vivaldi browser

### ISSUE THREAD

**Issue by n-gram-hub** [piwik/piwik#17329]
It looks like Piwik considers Vivaldi browser a Chrome browser (there's no Vivaldi icon too)

**Comment by sgiehl** [comment]
That might depend on the Matomo version you are using. The detections are done using device detector.
Do you have a useragent of a browser that is not detected correctly?

**Comment by Findus23** [comment]
Hi,

This might be intentional by the Vivaldi team:

> For the next release of Vivaldi, we have decided to try something different. The problem with our current approach is that with the web being almost infinite, we can’t possibly discover all the websites who have blocks set against us. Thus maintaining a list of sites where we present a non-Vivaldi User Agent is difficult. Instead, we will try doing the reverse. For a handful of sites where we know the label Vivaldi (and our version number) is responsibly used, we will present our full User Agent. Those sites being our own and a handful of interesting alternative search engines: duckduckgo.com, ecosia.org, qwant.com, and startpage.com. Every other site will get a User Agent that appears to be identical to Chrome.
> https://vivaldi.com/blog/user-agent-changes/

**Comment by sgiehl** [comment]
Ah. Interesting. Guess in that case there is actually nothing we could do about.
