### ISSUE TITLE
Segment in a rollup with a does not condition do not work

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17346]
When I create a segment when the value does not equal something and apply it to a roll-up. It does not work. For example: creating a segment which does not contain such url within the visit...results in this filter to be ignored.

## Expected Behavior
If I apply a does not equal or does not contain to a segment, the result should end up in not having those visits within the segment results.

## Current Behavior
The segment does not include this negative condition.
event if within the URL i can clearly read the != operator

## Possible Solution
To double check the result as I have the feeling that a negative condition equals to not doing anything.

## Steps to Reproduce (for Bugs)
1. Create a segment with a does contain filter
2. Identify if this segment, once applied results in changes.

## Context
Such segment is really useful when using a rollup for a website you would like to exclude.

## Your Environment

* Matomo Version: 4.2.1

**Comment by tsteur** [comment]
Hi @Chardonneaur thanks for creating this issue. As it's about a premium feature do you mind reaching out to our support? We only manage issues for core here. Thanks for that.
