### ISSUE TITLE
Update usage of Transifex API

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#17341]
Our scripts to update the translations are currently using the Transifex API v2.
Today Transifex released the new API v3. This API has a changed authentication. See https://transifex.github.io/openapi/index.html#section/Authentication
Seems they've switched from authenticating with username/password to and authentication token. 

We can still use v2, but need to update our scripts before end of 2022, as v2 will become unavailable afterwards.

We may need to update our API implementation (https://github.com/matomo-org/matomo/blob/4.x-dev/core/Translation/Transifex/API.php) as well as all commands (https://github.com/matomo-org/matomo/tree/4.x-dev/plugins/LanguagesManager/Commands) and the GitHub action in all repos, which uses the commands.

**Comment by Findus23** [comment]
This is now no longer needed with #17907
