### ISSUE TITLE
About geolocation: give the possibility to the user to search for its IP geolocation

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17355]
Currently within the geolocation plugin, the plugin directly identifies our IP address and indicate the geolocation. It would be great to have the possibility to check it for any IP address.

## Summary
Add a search bar for the geolocation admin plugin screen.

* Matomo Version: 4.2.1

**Comment by sgiehl** [comment]
@Chardonneaur  It's not possible to do this using the UI, but you can use the API method `UserCountry.getLocationFromIP`. Is that enough for you?

**Comment by Chardonneaur** [comment]
This is awesome I didn't know it, thank you Stefan.
So, just using this url can give it to us: https://demo.matomo.cloud/index.php?module=API&method=UserCountry.getLocationFromIP&ip=194.57.91.215&format=xml&token_auth=anonymous
Not sure if that could be worth linking this method within the documentation. Thank you so much.
