### ISSUE TITLE
Can ton "configure websites" in "search engine keyword performance"

### ISSUE THREAD

**Issue by frescoshop** [piwik/piwik#17350]
Hi,
Using wordpress and woocommerce
I have set google and bink keyword imports (google and bing are connected and list "my website as available to import"), however i cant seem to "Configure Websites", both Google and Bing give same problem. 
I select website and account from the dropdown and click save... it reloads the same page, nothing is saved. Both Google and Bing do the same.

So i think something is wrong on Wordpess side

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Hi @frescoshop 
For questions about premium plugins please get in touch with our support. We actually only handle issues for Matomo core here.
Nevertheless, we have actually released a new version of that plugin a few hours ago, which should fix the problem.

**Comment by frescoshop** [comment]
Hi Stafan,

Thank you. I have downloaded new version but when trying to install WP
plugin installer says "destination folder already exists" and quits. Please
advise

**Comment by sgiehl** [comment]
Sorry, I'm not very familiar with the wordpress version. Maybe @tsteur can help on this.

**Comment by frescoshop** [comment]
I figured it out. Thanks for initial reply! I literally downloaded and installed old version minutes before it was updated...
