### ISSUE TITLE
Ensure performance timings are sent as integer values

### ISSUE THREAD

**Issue by MichaelRoosz** [piwik/piwik#17371]
I am currently testing Matomo 4.2.1.

The new Performance Report feature is not working at all:

- in matomo_log_link_visit_action the only field with non-NULL data is time_network and its always 0
- the other fields are always NULL
- -> Reports are empty

This is what the browsers are sending:

chrome
pf_net: 0
pf_srv: 1.150000000052387
pf_tfr: 1.2499999993451638

firefox
pf_net: 0
pf_srv: 2
pf_tfr: 1

- floats in chrome seem strange as the backend seems to expect integers
- the values 0/1/2 look like seconds but I guess we want milliseconds?

-> the performance feature seems completely broken at this time

**Comment by sgiehl** [comment]
@MichaelRoosz thanks for creating the issue. Actually both values should be in milliseconds.
I'll prepare a PR to round the values, so we use integer in all cases. 
Not sure if the float values might cause problems when storing them in database..

**Comment by diosmosis** [comment]
Might be related to https://github.com/matomo-org/matomo/issues/17259

**Comment by sgiehl** [comment]
There had been some fixed aroud the Performance Timing tracking. I assume this one should have been fixed as well.
@MichaelRoosz If you still have an issue with this, please let us know, so we can reopen the issue. Thanks.
