### ISSUE TITLE
On-Premise: Custom Reports

### ISSUE THREAD

**Issue by gpadbidri** [piwik/piwik#17373]
We have an On-Premise Setup of Matomo - We have a requirement that EVREY registered Website on Matomo Dashboard displays **graph with Pageviews by hour, total pageviews, and then top pages of the day and their pageviews at the bottom**. 
Is it possible to create a Report that splits the Total Page Views by the hour for the last 24 hours ?

My queries around the same : 

1. Is it possible by creating a Custom Plugin / Widget ?
2. If # 1 is not possible - is it possible to achieve the same using Custom reports Plugin ? 
3. I need a way where I do not want to invest in a Custom Reports plugin just to have a COUPLE of reports ? Can you suggest me  a workaround of how can the above mentioned REPORTS be achieved with a GRAPH.

**Comment by diosmosis** [comment]
Hi @gpadbidri, unfortunately we don't answer questions in this issue tracker but only handle feature requests or bug reports. We'd greatly appreciate it if you asked the question in our forum: https://forum.matomo.org/ . Thanks for your understanding. Note: if you also have inquiries into our premium features, like CustomReports, please email our support at shop@innocraft.com.

**Comment by gpadbidri** [comment]
Sure, Thanks !
