### ISSUE TITLE
Referrer full path missing for most websites

### ISSUE THREAD

**Issue by alimony** [piwik/piwik#17381]
In the Acquisition > Websites view, almost all referrers only show the "index" path. I know the rest is not being anonymised or anything, looking at settings, and the fact that a handful of the websites also show a full path. It looks like I've been on the front page on some _major_ websites, which I know not to be true. In some cases I've been able to track down the specific path from which I've been linked, but that path does not show up in Matomo.

## Expected Behavior

I expect to see the full path for all referrers.

## Current Behavior

I see only the index page for almost all referrers.

## Possible Solution

Not sure.

## Steps to Reproduce (for Bugs)

1. Go to Acquisition > Websites
2. Expand referrers to see full paths.

## Context

I want to know from what specific pages I've been linked, and the current data does not tell me that, making the feature not very useful at the moment.

## Your Environment

* Matomo Version: 4.2.1
* PHP Version: 7.4.3
* Server Operating System: Ubuntu 20.04.1 LTS
* Additionally installed plugins: GoogleAnalyticsImporter 4.1.2

**Comment by Findus23** [comment]
Hi,

Which Referrer the browser forwards to a website when the visitor clicks on a link to it, depends on the ReferrerPolicy. 
You can simply try it out by clicking on a link to your website, opening your browsers developer tools (<kbd>F12</kbd>) and entering `document.referrer` in the console.

Matomo can't record any data that doesn't exist and therefore only stores what the browser outputs with `document.referrer`.

If for example your website doesn't use HTTPS, but the linked website does then no browser allows sending the full URL as a referrer (as it would make the secure URL path visible unencrypted).

Also a few days ago Firefox updated their browser to set the default referrer policy (if the site doesn't set another one) to `strict-origin-when-cross-origin`  (https://blog.mozilla.org/security/2021/03/22/firefox-87-trims-http-referrers-by-default-to-protect-user-privacy/) which means that different origins (so domains) never get to see the full referrer, but just the domain.
Chrome also changed this recently and I'm sure other browsers will follow soon.

I hope this answers the topic. If anything is still unclear just reopen the issue.
