### ISSUE TITLE
On-Premise -> Custom Reports Visualization Issues 

### ISSUE THREAD

**Issue by gpadbidri** [piwik/piwik#17392]
I have an Matomo - On Premise setup and I have installed Custom report TRIAL Version to evaluate if it suffices our requirements.

I was able to create a TABLE Report for “Pageviews by hour for a given day” Screenshot for reference : https://www.screencast.com/t/WILnaWJb

However, there are 3 issues :

When I go to the the “Vertical Bar Graph” option using the Change Visualization option below the tabular report - it randomly picks some hours of the day and shows data - I was assuming it will show me a Bar diagram with 24 bars (1 for each hour)

The hours in X-axis are in random order.

Why can I not see ALL the Visualization options mentioned in the documentation like Sparkline - All I see now is Vertical Bar Diagram and Pie-Chart

Check the screenshot for #1 and #2 for your reference : https://www.screencast.com/t/M4NiokT3DfS

Am I missing on something ?

**Comment by sgiehl** [comment]
Hi @gpadbidri, unfortunately we don't handle inquiries for our premium features, like CustomReports, on our public issue tracker.
Please email our support at shop@innocraft.com
