### ISSUE TITLE
setting the cookie domain even when cookies are disabled for compatibility with "Require Cookie Consent" feature

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17417]
### Description of issue:
When using a cookie domain such as .example.com and requiring cookie consent causes cookies for both www.example.com and .example.com to be created when cookie consent is given when using MTM
However, when cookie consent is withdrawn only one set of cookies are deleted (.example.com).
The www.example.com cookies remain including the mtm_cookie_consent cookie which causes .example.com cookies to be recreated when refreshing the page.

### Steps to reproduce:
1. Setup MTM container using the following settings:
Enable Link Tracking
Enable Cross Domain Linking
Require Cookie Consent
Cookie domain set to .example.com
Bundle Tracker
Register As Default Tracker

2. Visit the page and execute `_paq.push(['rememberCookieConsentGiven']);`
3. Refresh the page and check cookies created (There should be cookies for both www.example.com and .example.com when reproducing - in my testing I am using a website with a different subdomain of static.example.com)
It is expected here that cookies should only be set to .example.com
![image](https://user-images.githubusercontent.com/20905821/113207699-68d9fe80-92cd-11eb-8fd7-f8cc9f338fae.png)

4. Execute `_paq.push(['forgetCookieConsentGiven']);` and refresh the page. Check cookies, there should be cookies that remained for www.example.com:
![image](https://user-images.githubusercontent.com/20905821/113207895-ab034000-92cd-11eb-96aa-2e4ac8abb7f6.png)

5. Refresh the page, it should have recreated the cookies for .example.com:
![image](https://user-images.githubusercontent.com/20905821/113208056-db4ade80-92cd-11eb-8f15-983a55aa0412.png)

### Expected behaviour:
When not using a cookie domain and having Require Cookie Consent enabled, the Cookie Consent works as expected. It only creates cookies for the subdomain that is being viewed and the cookies are deleted when withdrawing cookie consent.

**Comment by Starker3** [comment]
@tsteur I've been able to reproduce this with the standard tracking code with the following added:
`  _paq.push(['requireCookieConsent']);`
 ` _paq.push(["setCookieDomain", ".example.com"]);`
  `_paq.push(['enableCrossDomainLinking']);`

Would you like me to recreate this bug report in Core?

**Comment by tsteur** [comment]
@Starker3 I moved it.

**Comment by Starker3** [comment]
FYI - In some cases the cookies left behind are reversed (I.e. in the example above it was the subdomain cookie `www.example.com` that was not removed)
It seems that having some plugins active or not may cause the other cookies to remain when using `_paq.push(['forgetCookieConsentGiven']);` (I.e. `.example.com` instead of `www.example.com`)

**Comment by Starker3** [comment]
### Reproducing issue with the standard JS tracker:

The following is required in the tracking code in order to reproduce:
```
_paq.push(['requireCookieConsent']);
_paq.push(["setCookieDomain", ".example.com"]);
```

Step 1: Visit the web page from a subdomain (In this example `www.`)
Step 2: Execute `_paq.push(['rememberCookieConsentGiven']);` from the console
Step 3: Confirm that cookies were created for the correct subdomain (`www.` in this example):
![Friday-28-05-2021 12-02-48](https://user-images.githubusercontent.com/20905821/119911051-b791d500-bfac-11eb-84e7-5e25c6d30630.png)
Step 4: Refresh the page and confirm that cookies for the cookie domain specified is created (`.example.com`)
![Friday-28-05-2021 12-04-19](https://user-images.githubusercontent.com/20905821/119911220-f9228000-bfac-11eb-8c26-e521728e52cc.png)
Step 5: Execute `_paq.push(['forgetCookieConsentGiven']);` from the console
Only cookies for the cookie domain specified are removed: 
![Friday-28-05-2021 12-06-33](https://user-images.githubusercontent.com/20905821/119911308-325af000-bfad-11eb-952c-8603c63e0fc6.png)
Step 6: Refresh the page, all cookies that were removed are created again because of the presence of `mtm_cookie_consent`:
![Friday-28-05-2021 12-08-29](https://user-images.githubusercontent.com/20905821/119911514-836ae400-bfad-11eb-940d-b1f8e1a3f309.png)


This can be reproduced on any subdomain of a website as long as the top level domain is set as the cookie domain. The only required settings are a top level domain set as cookie domain and cookie consent required.

**Comment by tsteur** [comment]
@Starker3 thanks for this. moved it into 4.4
