### ISSUE TITLE
Service Crashes on initial Setup when using specific passwords

### ISSUE THREAD

**Issue by cinatic** [piwik/piwik#17415]
i had problems when using the following password for the initial user `11!test$Lc&gCu+_+gB2c5dQGzywtuS=5M+`, this should be error handled

**Comment by sgiehl** [comment]
Hi @cinatic. Thanks for creating the issue. What exactly is the problem with this password? Wasn't it accepted by Matomo as valid, or weren't you able to login with it after setting up the account?

**Comment by Findus23** [comment]
Hi,

I tested it and it worked perfectly fine (as one would expect).

Can you please provide more details? What exactly did you do? What exactly went wrong? Did you see any errors? Maybe in the browser console or the server log?

**Comment by cinatic** [comment]
huh turned out it was a problem with the reverse proxy sorry, i also tested it again with the same image on local docker works as expected
