### ISSUE TITLE
Internal Server Error while creating tables during installation

### ISSUE THREAD

**Issue by jonaskohl** [piwik/piwik#17411]
## Expected Behavior
Installation should function as intended without any errors

## Current Behavior
After filling in the database details and clicking continue, the script errors out after about two minutes with the following error page
<details><summary>More info</summary><blockquote>
<h1>Internal Server Error</h1>
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [REDACTED] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

</blockquote></details>

The only thing that appears in my error log is the following:

    End of script output before headers: index.php

## Steps to Reproduce (for Bugs)

1. Try to install Matomo

## Your Environment

* Matomo Version: 4.2.1
* PHP Version: 7.4.16
* Server Operating System: Linux (Shared hosting)
* Additionally installed plugins: None

* Browser: Edge 89
* Operating System: Windows 10 Home 20H2 64-Bit

**Comment by diosmosis** [comment]
Hi @jonaskohl, do you have your PHP `max_execution_time` (or some other timeout) set to something low? It looks like the step to setup the database is just taking too long and gets cut off. Or possibly there's some other error causing the database queries like `CREATE TABLE` to just hang...

**Comment by jonaskohl** [comment]
The tables (or at least some of them) do get created. I think it's a problem with `max_execution_time`. I've already contacted my hosting provider because changing the value inside a script or `php.ini` does not seem to have an effect. So the problem probably lies with my hosting provider, not with Matomo.

**Comment by diosmosis** [comment]
:+1: good to know, I'll close this for now. If you discover anything else that could point to a bug feel free to comment or reopen the issue.
