### ISSUE TITLE
After fresh installation of 4.2.1 some columns like "visit_first_action_time" are missing

### ISSUE THREAD

**Issue by mwalliczek** [piwik/piwik#17420]
I just installed matomo 4.2.1 at my server, connected to an empty database, added some sites to be analyzed - but when I try to import some data from the logfiles, I get an Error 500 from the server and the logfile says "PHP message: Error in Matomo (tracker): Error query: preparing query failed: Unknown column 'visit_first_action_time'"

## Expected Behavior
The data is imported correctly.

## Current Behavior
Command:
```
python /home/matomo/misc/log-analytics/import_logs.py --enable-reverse-dns --enable-http-errors --enable-http-redirects --enable-bots --url=https://example.com/matomo --idsite=1 /var/log/nginx/access.log-20210328
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Parsing log /var/log/nginx/access.log-20210328...
2021-04-03 10:07:02,054: [INFO] Error when connecting to Matomo: HTTP Error 500: Internal Server Error
```

logfile:
```
2021/04/03 09:53:57 [warn] 5709#0: *5422011 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client/0000000712, client: 1.2.3.4, server: example.com, request: "POST /matomo/piwik.php HTTP/1.1", host: "example.com"
2021/04/03 09:53:57 [error] 5709#0: *5422011 FastCGI sent in stderr: "PHP message: Error in Matomo (tracker): Error query: preparing query failed: Unknown column 'visit_first_action_time' in 'field list' : SELECT visit_last_action_time, visit_first_action_time, idvisitor, idvisit, user_id, visit_exit_idaction_url, visit_exit_idaction_name, visitor_returning, visitor_seconds_since_first, visitor_seconds_since_order, visitor_count_visits, visit_goal_buyer, location_country, location_region, location_city, location_latitude, location_longitude, referer_name, referer_keyword, referer_type, idsite, profilable, visit_entry_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, referer_url, config_browser_name, config_client_type, config_device_brand, config_device_model, config_device_type, visit_total_events, visit_total_time, location_ip, location_browser_lang, last_idlink_va  FROM matomo_log_visit WHERE visit_last_action_time >= ? AND visit_last_action_time <= ? AND idsite = ? AND config_id = ?                 ORDER BY visit_last_action_time" while reading response header from upstream, client: 1.2.3.4, server: example.com, request: "POST /matomo/piwik.php HTTP/1.1", upstream: "fastcgi://unix:/usr/lib64/php7.4/fpm/matomo/socket:", host: "example.com"
```
## Possible Solution
I tryed adding the column, but than I get an error about a different missing column (user_id).

## Your Environment

# Mandatory checks

## Verzeichnisse mit Schreibzugriff: ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c

# Optional checks

## Schreibbarer JavaScript-Tracker ("/matomo.js"): ✔ 

# Informational results

## Do Not Track enabled: 1

**Comment by diosmosis** [comment]
Hi @mwalliczek, sorry you're experiencing this issue, it seems like matomo or php isn't able to create columns itself. To try and recreate the columns yourself through matomo, you could run the following SQL:

```
delete from matomo_option where option_name like 'version\_log\_%';
```

Then visit Matomo and the auto updater will try to recreate the columns. If this doesn't work, then php or matomo isn't able to create columns for some reason (and errors are maybe silenced).

**Comment by mwalliczek** [comment]
Hi @diosmosis, thanks for your help. You are right: I forgot to add "Alter_priv" to the matomo mysql user. Unfortunately there was no error displayed or logged.
So I run this SQL script, Matomo started the auto update - but there is still an error when trying to import:
`2021/04/07 07:32:00 [error] 5709#0: *5578453 FastCGI sent in stderr: "PHP message: Error in Matomo (tracker): Error query: preparing query failed: Unknown column 'last_idlink_va' in 'field list' : SELECT visit_last_action_time, visit_first_action_time, idvisitor, idvisit, user_id, visit_exit_idaction_url, visit_exit_idaction_name, visitor_returning, visitor_seconds_since_first, visitor_seconds_since_order, visitor_count_visits, visit_goal_buyer, location_country, location_region, location_city, location_latitude, location_longitude, referer_name, referer_keyword, referer_type, idsite, profilable, visit_entry_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, referer_url, config_browser_name, config_client_type, config_device_brand, config_device_model, config_device_type, visit_total_events, visit_total_time, location_ip, location_browser_lang, last_idlink_va  FROM matomo_log_visit WHERE visit_last_action_time >= ? AND visit_last_action_time <= ? AND idsite = ? AND config_id = ?                 ORDER BY visit_last_action_time DESC"`

**Comment by diosmosis** [comment]
@mwalliczek that column comes from a plugin. It might be easier to just do a clean install of matomo w/ the mysql user that has the correct privileges. Otherwise something like `DELETE FROM matomo_option WHERE option_name LIKE 'version_' AND name <> 'version_core';` might do the trick.

**Comment by mwalliczek** [comment]
Ok, after clean installation everything is working fine. Thanks for your help.

**Comment by diosmosis** [comment]
Glad it's working for you, I'll close this.
