### ISSUE TITLE
Tracker JS Tests

### ISSUE THREAD

**Issue by ElManaa** [piwik/piwik#17423]
Hello Everyone!

It’s been months that I’ve been working on matomo and I found it very effective and flexible for our needs, we are actually trying to extend matomo and add new plugins, plugins that helps media and web magazines get more information about their articles!

Every plugin I create I made some system tests for it to make sure it’s working as it should be but, on the tracker JS side, haven’t found any way to make sure that the events submitted are real and precise could you suggest for me a methodology to test every event I track and make sure that it’s real? … I did work a little with selenium, but we require big numbers of tests (simulate hundreds of people on a website)

i hope you all have a good day
stay productive
Greetings

**Comment by Findus23** [comment]
Hi,

You might want to look into how the JS tests work for the Tag Manager plugin:
https://developer.matomo.org/guides/tagmanager/testing
https://github.com/matomo-org/tag-manager/tree/4.x-dev/tests/javascript

**Comment by ElManaa** [comment]
thank you i find this quite helpful

**Comment by Findus23** [comment]
These two pages might also help:
https://developer.matomo.org/guides/enrich-js-tracker
https://developer.matomo.org/guides/jstracker-core
