### ISSUE TITLE
Don't load review logos if they are not shown

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17422]
It seems like the images used by the review plugin (e.g. /plugins/Feedback/images/saasworthy.png) are loaded on every Matomo page view, even if the popup is not shown. 

Changing `<img src="">` to `<img ng-src="">` doesn't seem to change a thing.
This could be used to save five requests that could instead load images that are blocking the rendering of the page.

**Comment by sgiehl** [comment]
@Findus23 Did you try if a `loading="lazy"` attribute would do the trick?

**Comment by Findus23** [comment]
@sgiehl I didn't think of that and it does indeed seem to work. 
While this doesn't work in the [30% of browsers](https://caniuse.com/loading-lazy-attr) that don't support native lazy-loading yet, I guess this is a workaround unless someone knows an angular-related trick.
