### ISSUE TITLE
Site cannot be fetched

### ISSUE THREAD

**Issue by ljubacanoa** [piwik/piwik#17429]
I get already Matomo installed on GCP like official click to deploy and it worked well. Now I switched to Plesk and no chance to get it to work by following tutorial from docs (100% - firewall disabled and PageSpeed disabled). P.S. - Plesk is running on Litespeed Fast CGI.
Finally I started fresh instance of GCP (again) and I get 100% same situation. So, NOTHING TOUCHED (click to deploy), mean - running Matomo from IP, by adding first site, site is not recognized. So, here is nothing from above specific moments (firewall, LS,...).

## Expected Behavior

After adding tracking code of first site to WP site, by login on Matomo, I should to see dashboard with initial site tracking widgets, but I still see warning page that tracking code is not added.

## Possible Solution

I suspect that issue is OS - Ubuntu 20.04 (Plesk) or Debian (GCP click and deploy), as it looks how Matomo runs on CentOS 8 (CyberPanel).
I tried to mess with permissions on Plesk, but no results. However, that cannot be the case on GCP click and deploy.

## Steps to Reproduce (for Bugs)

On GCP is no steps. Install it, run it and see the issue.

1.
2.

## Your Environment

* Matomo Version:4.11 - 4.20 - 4.21 (Plesk installations) and 4.21 (GCP click and deploy)
* PHP Version: 7.4.16
* Server Operating System: Ubuntu 20.04 (Plesk) and Debian (GCP)
* Additionally installed plugins: none

* Browser: Chromium (cache) and Chrome (Incognito)
* Operating System: MacOS Big Sur

**Comment by Findus23** [comment]
For reference: https://forum.matomo.org/t/brand-new-plesk-installtion-not-working/41395/5

**Comment by diosmosis** [comment]
Hi @ljubacanoa, from reading the linked forum post, it seems the real issue is that visits from Opera with the free VPN enabled are not tracked by matomo, is that correct?

**Comment by sgiehl** [comment]
Closing this one as there hadn't been any feedback within over a year.
