### ISSUE TITLE
Email reports management: per group instead of per user

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#17450]
# Summary
Today, if I want to create (and share) an **Email & SMS Report**, I can do it, thanks to the [dedicated feature](https://matomo.org/docs/email-reports/):
![image](https://user-images.githubusercontent.com/79993552/114424211-2f9c6b00-9bb8-11eb-9267-5f60c8b69320.png)
(Note: I think it is strange to place this feature in **Administration > Personal** menu 🤨)

Then I add many colleagues in the list of report recipient. 👌 Great.

Suddenly, I become sick.
Who will then manage the report (eg. update the report contents, change frequency, add/remove recipients, etc.)?

I think it could be better to create a role (as the roles that manage the sites: **read**, **write**, **admin**, etc.) dedicated to manage the **Email & SMS Report** feature (or use an existing one, but which one?)

**Comment by tsteur** [comment]
Thanks for creating this issue @heurteph-ei it be valuable indeed. We have an issue for this already in https://github.com/matomo-org/matomo/issues/15164 and somewhat related too https://github.com/matomo-org/matomo/issues/7076 . I'll close this for now as a duplicate. Thanks for creating this issue it helps us prioritise often requested features 👍
