### ISSUE TITLE
Providers 100% Unknown When Using Webserver Logs, Works when Using Javascript Tracking?

### ISSUE THREAD

**Issue by mddvul22** [piwik/piwik#17486]
We are using the free Maxmind GeoLite2-City database with our Matomo install.  Our Matomo install is mainly using a nightly import of Apache logs for the majority of the websites being used with our Matomo.  For every one of these sites, when you click on Vistors->Locations, and scroll down to Providers, it states that 100% are "Unknown".

However, we have configured **_one_** of our websites in Matomo twice: one is using log analytics, and the other is using javascript tracking -- but they are the same URL.

We have found that for the version using javascript tracking, the Provider details work.  It is only on the sites using log analytics that Provider is 100% unknown.  Do the provider details require javascript tracking? Or is something wrong in our configuration?

## Expected Behavior
Since the visitor IP address should be available to Matomo through both methods, I would expect that Provider details wouldn't be dependent upon the javascript tracking.

## Current Behavior
It appears that it is dependent upon javascript tracking.

## Your Environment
* Matomo Version: 3.14.1
* PHP Version: 7.2.24
* Server Operating System: Centos 8.3
* Browser: Firefox
* Operating System: Linux

**Comment by diosmosis** [comment]
Hi @mddvul22, can you look for an IP that is both in your log file and in your Matomo database and see if the provider is geolocated successfully in the maxmind demo: https://www.maxmind.com/en/geoip-demo? Can you also make sure the IP isn't anonymized in any way in the log files?

**Comment by mddvul22** [comment]
Hi @diosmosis Here is an example: at approximately 23:19:41, last night, we had a visit from the IP address 67.225.10.219.
Here is how the javascript tracking shows the visit.  You can see the provider is listed:

![image](https://user-images.githubusercontent.com/6833993/115871092-b695e280-a405-11eb-8508-d5c40789a84c.png)

Here is how log analytics shows that visit, with no provider shown:

![image](https://user-images.githubusercontent.com/6833993/115871162-cc0b0c80-a405-11eb-9a8b-54d41cd19b2d.png)

Here is the geoip lookup results for that IP:

![image](https://user-images.githubusercontent.com/6833993/115871246-e93fdb00-a405-11eb-852c-e6891ece69c1.png)

And, for the purposes of our troubleshooting this issue, we have completely disabled IP anonymization, as you can see here:

![image](https://user-images.githubusercontent.com/6833993/115871350-0bd1f400-a406-11eb-9f32-651737a4a118.png)

Finally, here are screenshots of the Providers overviews, from the Locations tabs.  First is the website with javascript tracking:
![image](https://user-images.githubusercontent.com/6833993/115871667-75ea9900-a406-11eb-8051-fcfbeb0f365f.png)

And, for comparison, the same website with log analytics tracking:
![image](https://user-images.githubusercontent.com/6833993/115871738-8ef34a00-a406-11eb-9c44-cc811ff73c9e.png)

Thanks!

**Comment by sgiehl** [comment]
Hi @mddvul22  Looking up the provider is disabled by default when importing visits. This was initially implemented to prevent reverse dns lookups to identify the provider. You can disable that default by setting the `--enable-reverse-dns` for log importer.
Nevertheless I guess we actually could do the geoip lookup in any case, as it shouldn't take long to do it.

**Comment by mddvul22** [comment]
Thank you!  I've added --enable-reverse-dns to our import command and will run the import with that, tonight.  Thanks!

**Comment by mddvul22** [comment]
This worked.  Thanks!
