### ISSUE TITLE
Campaign parameters: if the keyword field is not filled it gets filled by the referrer domain name

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17482]
When you use the new version of the Matomo URL builder and use all fields except the one of the keywords, the one of the keyword get automatically field with the domain name of the referrer.

## Expected Behavior
If a parameter is not used, it shouldn't be filled automatically with a value.

## Current Behavior
If the keyword parameter is not used but others are: name, source, medium, content, campaign id... then the keyword field get filled.

## Possible Solution
It should stay empty.

## Steps to Reproduce (for Bugs)
Just use the url builder form with mtm parameters.

**Comment by diosmosis** [comment]
Hi @Chardonneaur, I tried to reproduce this on https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Referrers_Referrers&subcategory=Referrers_URLCampaignBuilder but couldn't (I also tried locally). `mtm_kwd` was never present if I left the keyword field blank. Can you provide a screenshot of the problem maybe?

**Comment by sgiehl** [comment]
@Chardonneaur Are you still able to reproduce that one, or can we close the issue?

**Comment by Chardonneaur** [comment]
@sgiehl hi, thanks for the follow up, I just tested it and it works fine.
