### ISSUE TITLE
Evolution graph of acquisition overview does not work

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17499]
When we click on the titles of each channel sources at the bottom of the overview graph, it works for the first two channels, then it goes to 0 for every period.

## Expected Behavior
When we click on direct traffic, it should plot the direct traffic, when we click on campaigns it should plot the campaign traffic...

## Current Behavior
It gets buggy after two clicks

## Possible Solution
Force the update.

**Comment by flamisz** [comment]
Hi @Chardonneaur, sorry about this. It's indeed a bug, as we can easily reproduce it on the demo site [here](https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Referrers_Referrers&subcategory=General_Overview). After the 3rd click we get only flat graphs.

I set this issue as bug so we can hopefully get things sorted soon.

**Comment by mkindred** [comment]
I think this is related to the issue I called attention to in the forums https://forum.matomo.org/t/acquisition-overview-multiple-bugs/41308 and possibly as far back as 2019 https://forum.matomo.org/t/3-13-bug-in-acquisition-overview/35248

But I noticed the bug when I opened the pulldown above the graph that allows you to select Records to Plot. Doing so eventually causes all the graph data to flatline to zero, and it also seems to result in URL-encoded characters in the 'records to plot' labels.

This is also reproducible in the demo site.

**Comment by mattab** [comment]
i could reproduce the issue, steps:

* Go to [demo](https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Referrers_Referrers&subcategory=General_Overview)
* Under evolution graph click on the sparkline eg. `1,620 from search engines, 56% of visits -16.5%`
* the graph loads correctly
* then click again
* got: the graph is now empty
* expected: the graph loads correctly

![Screenshot from 2021-09-28 14-22-33](https://user-images.githubusercontent.com/466765/135006819-6e876dee-518e-4f9c-b452-31813c35aeec.png)

(fyi: In some other cases I get a different issue, but i couldn't exactly reproduce it, where the graph label appears double encoded, see screenshot below. this issue might be automatically fixed when we fix the above)

![Screenshot from 2021-09-28 14-18-51](https://user-images.githubusercontent.com/466765/135006587-47095fb8-2115-4efa-bc9e-3357b055f218.png)

**Comment by sgiehl** [comment]
This could possibly be fixed with https://github.com/matomo-org/matomo/pull/18016

**Comment by mattab** [comment]
It is fixed :tada:
