### ISSUE TITLE
Error during installation (wrong dimension of file)

### ISSUE THREAD

**Issue by mpaglia0** [piwik/piwik#17501]
Hi all,
installed Matomo latest this morning.
During the installation I saw and error regarding the dimensions of file /node_modules/materialize-css/dist/css/materialize.min.css
The installation goes ahead without problems but - upon login - I cannot see any data...
Files have been transferred via FTP in binary mode as recommended.
![Senzanome](https://user-images.githubusercontent.com/21242068/116078135-89ac2e80-a696-11eb-98f1-2a4dad8321cd.jpg)

**Comment by sgiehl** [comment]
@mpaglia0 Thanks for creating this issue. I don't think this is a general problem of Matomo. Could you please check your browser console if all files could be loaded correctly? If you see some html files failing to load, you might need to adjust you server configuration to fix this.

**Comment by mpaglia0** [comment]
@sgiehl I think you are right... I will go and see my .htaccess. 
Thank you!
