### ISSUE TITLE
Matomo mysqldump import issues

### ISSUE THREAD

**Issue by Osomo3000** [piwik/piwik#17534]
I dumped a database from an old Matomo Server (v3.9.1). I want to import the dump into our new Matomo Server (v3.14.0). The old Database use _PIWIK as Prefix, and the new Database use _MATOMO as Prefix. If I try to import the old database to the new server, the old database doesn't merge with the new database. Is there any solution to integrate the old database into the new Matomo Database?

## Expected Behavior

Merging the old database with the new database. Display the old and the new database on Matomo Statistics.

## Current Behavior

It doesn't merge the databases. Piwik Tables and Matamomo Tables are displayed separated. I can't see the old Database on the Matomo Dashboard.

![piwik](https://user-images.githubusercontent.com/23298262/117533474-4da98f80-afed-11eb-9aa7-8868efa19700.PNG)

## Steps to Reproduce (for Bugs)

1. Exporting the dump from the old server: mysqldump -u username -p database_name > data-dump.sql
2. Importing the old database into the new server:  mysql -u username -p new_database < data-dump.sql
3. Restart the Server

## Your Environment

* Matomo Version:
Old server 3.9.1
New server: 3.14.0

* PHP Version:
Old server: 7.0.21
New server: 7.4.9

* Server Operating System: Microsoft Windows Server 2016 Standard
* Additionally installed plugins:

* Browser: Google Chrome
* Operating System: Microsoft Windows Server 2016 Standard

**Comment by diosmosis** [comment]
Hi @Osomo3000, unfortunately we don't answer questions in this issue tracker, we only handle feature requests or bug reports. We'd appreciate it if you asked this question in our forum: https://forum.matomo.org/. Thanks for your understanding.

**Comment by mattab** [comment]
FYI the correct mysqldump command to generate a dump that works well, is documented in https://matomo.org/faq/how-to/how-do-i-backup-and-restore-the-matomo-data/
