### ISSUE TITLE
Allow multiple dates or date range in core:purge-old-archive-data

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17556]
Refs #17555 

Currently if you need to purge specific date ranges using the `core:purge-old-archive-data` command, you need to run the command for each month that you would like to purge reports from the archive_blob

It would be great if we could support adding multiple dates to the command (Perhaps this is only possible if we add support for the `--dates=` parameter), for example:
`./console core:purge-old-archive-data --dates=2021-01-01,2021-01-02`

Or perhaps to purge a date range we could add support for `--date-range`, for example to purge all old reports between January and March we could run:
`./console core:purge-old-archive-data --date-range=2021-01-01,2021-03-01`

Or perhaps add it as a flag, for example:
`./console core:purge-old-archive-data --dates=2021-01-01,2021-03-01 --date-range`

**Comment by diosmosis** [comment]
Closing since this is available (though perhaps not obvious)
