### ISSUE TITLE
Internationalized domain names and ccTLDs

### ISSUE THREAD

**Issue by robocoder** [piwik/piwik#1755]
Make sure we support internationalized domain names and ccTLDs by adding more unit tests.  (Areas include provider, sitesmanager.addsite, and searchengine detection for {}.)

China (.cn):
- . / .xn--fiqs8S
- . / .xn--fiqz9S
  Egypt (.eg):
- . / .xn--wgbh1c
  Hong Kong (.hk):
- . / .xn--j6w193g
  India (.in):
- . / .xn--h2brj9c
- . / .xn--mgbbh1a71e
- . / .xn--fpcrj9c3d
- . / xn--gecrj9c
- . / .xn--s9brj9c
- . / .xn--xkc2dl3a5ee0h
- . / .xn--45brj9c
  Iran (.ir):
-  / .xn--mgba3a4f16a
-  / .xn--mgba3a4fra
  Jordan (.jo):
- . /.xn--mgbayh7gpa
  Korea (.kr):
- . /.xn--3e0b707e
  Palestine (.ps):
- . / .xn--ygbi2ammx
  Qatar (.qa):
- . / .xn--wgbl6a
  Russia (.ru):
- . / .xn--p1ai
  Saudi Arabia (.sa):
- . / .xn--mgberp4a5d4ar
- . / xn--mgberp4a5d4a87g
- . / .xn--mgbqly7c0a67fbc
- . / .xn--mgbqly7cvafr
  Singapore (.sg):
- . / .xn--yfro4i67o
- . / .xn--clchc0ea0b2g2a9gcd
  Sri Lanka (.lk):
- . / .xn--fzc2c9e2c
- . / .xn--xkc2al3hye2a
  Syria (.sy):
- . / .xn--ogbpf8fl
- . / .xn--mgbtf8fl
  Taiwan (.tw):
- . / .xn--kpry57d
- . / .xn--kprw13d
  Thailand (.th):
- . / .xn--o3cw4h
  Tunisia (.tn):
- . / .xn--pgbs0dh
  United Arab Emirates (.ae):
- . / .xn--mgbaam7a8h

Also, an opportunity to provide support or Punycode URLs was raised in #1073, but never implemented.

References:
- http://icann.org/en/topics/idn/fast-track/string-evaluation-completion-en.htm
- http://en.wikipedia.org/wiki/Punycode and RFC3492

**Comment by magiruuvelvet** [comment]
Not sure if I add those here, but before opening a new issue. I temporarily worked around the email address validation by returing always `true` in `core/Piwik.php`@`isValidEmailString`. I know this is nasty but I have a IDN domain and Piwik refused to accept my valid and working e-mail address. After applying this patch I finally got piwik to send reports and it worked great without problems.

Just want to let you guys know.

**Comment by mattab** [comment]
@magiruuvelvet a few months ago we tried to detect these issues. We added an automated tests which tests our email validation logic against the list of valid domain name extensions as per IANA in http://data.iana.org/TLD/tlds-alpha-by-domain.txt

This was done in https://github.com/piwik/piwik/pull/9674

so if you still experience an issue in PIwik 3, please create a new issue
