### ISSUE TITLE
CSS: "speak" property: "none" changed to "never"

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17565]
![grafik](https://user-images.githubusercontent.com/1645099/118404150-e4bbba80-b671-11eb-9dbf-4057059b718a.png)
link: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Dashboard_Dashboard&subcategory=1

## Expected Behavior
`speak: never`

## Current Behavior
`speak: none`

## Possible Solution
`speak: never`
see https://www.w3.org/TR/css-speech-1/
![grafik](https://user-images.githubusercontent.com/1645099/118404070-b342ef00-b671-11eb-837b-9c391171e7b4.png)

## Steps to Reproduce (for Bugs)
see above

## Your Environment
* Matomo Version: 4.2.1 (demo.matomo.cloud)
* Browser: Firefox
* Operating System: windows 10

**Comment by Findus23** [comment]
Hi @mathContao,

It seems like the best solution is to keep everything as-is (see https://github.com/matomo-org/matomo/pull/17566)

**Comment by math-GH** [comment]
thanks
