### ISSUE TITLE
Uploading logo kicks user out

### ISSUE THREAD

**Issue by julienbfabre** [piwik/piwik#17586]
Fresh installation of Matomo 4.3, i tried to upload a logo, got kicked out to the login page with an error saying ""Error: Token is not valid."

Trying to log back in while on this page keeps failing.
Note that the url is `index.php?module=CoreAdminHome&format=json&action=uploadCustomLogo`

## Expected Behavior
The logo should upload.

## Current Behavior
The user get's kicked out and can't get back in unless manually changing the url.

## Steps to Reproduce (for Bugs)
1. Fresh install
2. click on the "Upload your logo" link in the "Become a Motomo expert" box on the dashboard
3. Scroll down to the branding settings, select a logo.

## Your Environment
* Matomo Version: 4.3
* PHP Version: 8.0.5
* Server Operating System: Ubuntu 16.04.4
* Additionally installed plugins:
Nothing, brand new installation
* Browser: Chrome
* Operating System: Mac OS

**Comment by flamisz** [comment]
Hi @julienbfabre, thanks for reporting this issue. I'm able to reproduce that locally, it's indeed a bug.
