### ISSUE TITLE
Matomo shows disruptive banner on dashboard after upgrade

### ISSUE THREAD

**Issue by unikitty37** [piwik/piwik#17581]
## Summary

After upgrading to Matomo 4.3.0, the following banner appeared at the bottom of my dashboard.

![image](https://user-images.githubusercontent.com/139183/118639230-93294200-b7cf-11eb-9fb8-daaca14cbd2d.png)

It is not at all clear whether the "close" button simply dismisses the banner for a period of time, or prevents it from ever showing again.

Please could there be an **explicit** "never show this again" button, as well as an option in the user preferences to not keep trying to hustle me like this?

When I use Matomo, I want to see the analytics for my site. It's already annoying enough that every upgrade makes me click through a donation interstital, but now the dashboard is being polluted with nags as well.

What's next: continually hassling me to sign up for the mailing list? Adverts for the new Ford?

If anything, this makes it much *less* likely that I will recommend Matomo to anybody as, like me, they don't want to be hassled by their software. Matomo should be respectful of its users' time and not force them to keep dismissing nags. Please add an option to disable them *all*.

(From an accessibility design point of view — there is *way* too little space between those icons. A user with poor motor control could end up on LinkedIn when they just wanted to get rid of the banner — especially on a touch-based device.)

## Your Environment

* Matomo Version: 4.3.0
* PHP Version: (from Matomo Docker container)
* Server Operating System: (from Matomo Docker container)
* Additionally installed plugins: AjaxOptOut, BotTracker

**Comment by diosmosis** [comment]
Hi @unikitty37, someone else has already complained about this: https://github.com/matomo-org/matomo/issues/17571, so I'm going to close this as duplicate. We'll certainly take your comments into consideration as well.
