### ISSUE TITLE
System Check showing warning when max_execution_time is set to -1 in PHP.ini

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17585]
## Current Behavior

Some systems seem to not support setting `max_execution_time=0`, in these cases setting `max_execution_time=-1` seems to work to disable the max execution time

However, this causes a warning in the System Check:
![image](https://user-images.githubusercontent.com/20905821/118727735-5b7dd100-b887-11eb-87a3-c87621d0ac72.png)

## Possible Solution

Add check for `max_execution_time=-1`

## Your Environment

* Matomo Version: 4.2.1
* PHP Version: 7.4.18
* Server Operating System: Ubuntu
* Additionally installed plugins: NA

**Comment by tsteur** [comment]
I'll move it in a milestone simply because it's very quick to do. Setting it to 0 should always work though. When setting it to -1 seems you actually simply set a very high number see https://stackoverflow.com/a/9371428

**Comment by Starker3** [comment]
Setting it to 0 seems to work in >99% of the cases.
We did get two reports from two different users, one got the result:
`{"result": "error","message": "Maximum execution time of 0 seconds exceeded"}` 

Another one had a fatal PHP error with PHP 7.4.16:
`PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /srv/http/piwik`
