### ISSUE TITLE
HeatmapSessionRecording.addHeatmap failed

### ISSUE THREAD

**Issue by zkaitanx** [piwik/piwik#17580]
When I use api - HeatmapSessionRecording.addHeatmap (idSite, name, matchPageRules, sampleLimit = '1000', sampleRate = '5', excludedElements = '', screenshotUrl = '', breakpointMobile = '', breakpointTablet = '') like this:
https://xxxxxxx.com/?method=API.getBulkRequest&format=json&module=API&token_auth=mytoken&urls[0]=method%3DHeatmapSessionRecording.addHeatmap%26idSite%3D1%26name%3Dtest%26matchPageRules%3D%5B%7B%22attribute%22%3A%22url%22%2C%22type%22%3A%22equals_simple%22%2C%22value%22%3A%22https%3A%2F%2Fmysite.com%2F%22%7D%5D
But the api return I don't have this site permission, and I can this site's heatmap.
Is there any setting error

**Comment by diosmosis** [comment]
Hi @zkaitanx, thanks for the report. In this issue tracker we only manage issues around Matomo's core functionality. For bugs or help with premium features please email our dedicated support at shop@innocraft.com. Thanks again @zkaitanx and sorry for the inconvenience.
