### ISSUE TITLE
Visitor Map shows no visits for all regions of Greece (matomo 4.2.1/geoip2 lite)

### ISSUE THREAD

**Issue by basos9** [piwik/piwik#17590]
Hello 

The Visitor map does not show any Region (I think since the last upgrade from matomo 3 to 4.2)

REFS
This may be related https://github.com/matomo-org/matomo/issues/16714

![image](https://user-images.githubusercontent.com/1616441/118802704-23888500-b8ab-11eb-888e-146008365dee.png)

While regions are detected for most users
![image](https://user-images.githubusercontent.com/1616441/118802757-356a2800-b8ab-11eb-984e-0ef62c4329fe.png)

We are using the maxmind geoip2 (free) db

![image](https://user-images.githubusercontent.com/1616441/118802908-63e80300-b8ab-11eb-9e9c-334c15ecb2eb.png)

```
EditionIDs GeoLite2-ASN GeoLite2-City GeoLite2-Country
```

**Comment by sgiehl** [comment]
Hi @basos9.
Thanks for creating the issue. I just had a quick look and it seems the map leaks the iso attributes so the visitors can't be shown correctly. I'll try to prepare a PR that should fix this quickly.
