### ISSUE TITLE
Error message "The promise was rejected" after adding a new measurable

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17592]
![grafik](https://user-images.githubusercontent.com/1645099/118806879-e4a50000-b8a7-11eb-91f9-2bbfd82f0582.png)

error message "The promise was rejected with reason: Invoking the wait callback did not resolve the promise" after adding a new measurable

but it was added
(same screen without reloading the page)

<img width="1387" alt="grafik" src="https://user-images.githubusercontent.com/1645099/118807170-3d749880-b8a8-11eb-8b40-9a03d2660d6e.png">

## Expected Behavior
no error message

## Current Behavior
error message 

## Possible Solution
no idea

## Steps to Reproduce (for Bugs)
add a new measurable

## Context
see screen shots

## Your Environment
* Matomo Version: matomo.cloud

**Comment by sgiehl** [comment]
Hi @mathContao. Thanks for creating the issue. I tried to reproduce that locally and on my cloud instance, but wasn't able to.
Could you check if that happens every time you add a measurable? If so please get in touch with our support and send them some more details and your cloud instance name. Maybe we are possible to reproduce it there.
