### ISSUE TITLE
DE-Translation missed, when website was updated

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17591]
![grafik](https://user-images.githubusercontent.com/1645099/118805154-e5d52d80-b8a5-11eb-9d14-7d2a5f661821.png)

User interface language: German

What I did:
Changed some settings of a website

## Expected Behavior
OK-Message in German (f.e. "Website wurde aktualisiert")

## Current Behavior
OK message in English

## Possible Solution
translation added

## Steps to Reproduce (for Bugs)
1. Go to matomo.cloud/index.php?module=SitesManager&action=index&idSite=1&period=year&date=today
2. edit page seetings
3. save it

## Context
German user interface

## Your Environment
* Matomo Version: matomo.cloud

**Comment by Findus23** [comment]
Seems like this text is indeed not translatable yet:
https://github.com/matomo-org/matomo/blob/bf38fded460899f4b668aaee6c3cb58211921588/plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js#L141-L144

**Comment by sgiehl** [comment]
Thanks @mathContao for creating the issue.
Putting into current milestone as it should be fixable in a couple of minutes.

**Comment by Findus23** [comment]
This got fixed by #17673, right @justinvelluppillai?
