### ISSUE TITLE
docker-compose recipe?

### ISSUE THREAD

**Issue by vsoch** [piwik/piwik#17599]
Hi Matomo! I'm looking to get this running on an instance, and I'm wondering if anyone has set up a docker-compose recipe for it? I saw the docker-compose.yml in the .gitignore so I suspect that one used to exist, it exists locally for some developer. Any pointers to work started in this direction would be greatly appreciated! I'd definitely rather use containers than installing everything natively. If there is more development/help needed to create this recipe I could also offer. Thank you!

**Comment by tsteur** [comment]
Hi @vsoch there is https://github.com/matomo-org/docker if that helps? I'll close this issue for now but let me know if that's not helping and we can reopen the issue.

**Comment by vsoch** [comment]
Absolutely perfect (and good idea to have it separate). Thank you!
