### ISSUE TITLE
Fix 2-lines label overflows the input

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17602]
<img width="552" alt="Bildschirmfoto 2021-05-20 um 15 35 40" src="https://user-images.githubusercontent.com/1645099/118988272-556c1b00-b981-11eb-9f03-dfc66b1ed50e.png">
link: /index.php?module=CoreAdminHome&action=generalSettings&idSite=1&period=year&date=today

In English it is mostly quite ok, because the texts are short.
In German it happens often, because of longer texts.

## Expected Behavior
more whitespace between label and input

## Current Behavior
less whitespace 

## Possible Solution
CSS: less "line-height" (f.e. 1em)

better:
I do not understand why the label follows after the input in HTML.
<img width="796" alt="grafik" src="https://user-images.githubusercontent.com/1645099/118989408-4df94180-b982-11eb-80be-96f9a3033f9d.png">

Better would be: first the label, then the input.

The label could be display: block, so it would not overflow the input.

## Steps to Reproduce (for Bugs)
see screen shots

## Your Environment
* Matomo Version: matomo.cloud
* Browser: Firefox 88
* Operating System: MacOS

**Comment by diosmosis** [comment]
Thanks for the bug report @mathContao, there certainly could be more space in this situation!
