### ISSUE TITLE
widget: minimize and reload icon

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17626]
Dashboard: maximized Widget

When the mouse cursor hover over the head of table, than the icons to minimize and to reload the widget content appears on the left of close icon.
![grafik](https://user-images.githubusercontent.com/1645099/119710579-cbc7bc00-be5e-11eb-9038-6904f5f1f5be.png)

The red close icon gets cuted.
The appeared icons cannot used, because while the cursor leaves the head of table the icons disappear.

## Expected Behavior
icons do not appear

## Current Behavior
see description

## Your Environment
* Matomo Version: 3.4.1
* Browser: Firefox 88

**Comment by sgiehl** [comment]
Hi @mathContao. Thanks for creating this issue. I was able to reproduce that on our demo and it seems to happen in all browsers. Not sure when that got broken, but it seems to be regression as it used to work somewhen.
