### ISSUE TITLE
"Rows to display" cannot be changed if a row is expanded

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17628]
## Expected Behavior

We would expect that a reports maximum "Rows to display" can be changed when expanding/collapsing a row in the report.

## Current Behavior

Currently when a report contains rows that can be expanded (When a report is hierarchical), the option to change the maximum number of rows is removed. For example when no rows are expanded the option to change the number of rows is shown:
![Thursday-27-05-2021 14-53-42](https://user-images.githubusercontent.com/20905821/119759116-c4a2bb80-befb-11eb-9971-e363edca18a1.png)

However, when one of the rows has been expanded, the option is removed:

![Thursday-27-05-2021 14-54-02](https://user-images.githubusercontent.com/20905821/119759124-c8364280-befb-11eb-8e29-a99c16ffcb18.png)

The option does not show again, even after the row is collapsed and requires a page refresh to show the option again:
![Thursday-27-05-2021 14-54-20](https://user-images.githubusercontent.com/20905821/119759172-e4d27a80-befb-11eb-93eb-087e804c7761.png)

## Possible Solution

Allow the "Rows to display" to be changed when a row is expanded in a hierarchical report, or alternatively we can continue to show the number of "Rows to display" and perhaps disable the option to click on it and change it (Maybe by greying it out on the page or removing the dropdown arrow to show it cannot be changed)
This will at least show users what the current maximum number of rows is for the report they are viewing.

## Your Environment

* Matomo Version: 4.3.1

* Browser: Firefox
* Operating System: Ubuntu

**Comment by heurteph-ei** [comment]
Additional question in order to find the best solution: When roots are collapsed, does this _number of rows_ selector filter the number of root rows, or the number of all rows including leaves?
If this only apply on the roots, so the selector could be displayed and be active all time...

**Comment by Starker3** [comment]
@heurteph-ei It affects all row limits for the report including subtable rows.
So for example is we set the limit to 10, the root row including all subtable rows will each be limited to 10.

That means that technically you could see all the top rows if your limit was for example 10, but if you expanded one row and the subtable had more than 10 rows in it you wouldn't see more than the first 10 rows of the expanded root row (For each level as well).

**Comment by diosmosis** [comment]
@Starker3 noticed this as well and just created a bug report for it: https://github.com/matomo-org/matomo/issues/17634

**Comment by heurteph-ei** [comment]
So this bug seems easy to fix as the drop-box already works as expected, it has just to not be hidden...
But bug #17634 needs more work to be fixed...

**Comment by DontPlayTheGame** [comment]
I'm happy that the current behavior is now reported/labelled as bug.
Just my 2 cents to the issue (as some one as a CPUX) and with many feedback from our users, i can tell that the current behavior is not what a user is expecting during interactions with the UI.
The typical user interaction is: 

- select a date / date range, 
- check the numbers in the aggregated rows and 
- **then click on a row to expand it** to see further details

At this point the drop-down disappear and the user is wonder, why there are so few rows in the view (default is 10) and then i got a message "how can i/we see more data in the rows?" ;-)  )

**Comment by tsteur** [comment]
This seems to mostly impact action data tables where we show the subtable "embedded".

I see this was removed in https://github.com/matomo-org/matomo/commit/0b5e89c669df628427a8361298c9f99e0a3b9219#diff-f1627c29aeaa3c345fe9c1cadcd5080c98fc169131e2e37a7d590bc7aa929532R240  and partially related https://github.com/matomo-org/matomo/commit/681d4437d908218b26b79da7b84008d8b72d9431

@sgiehl @mattab do you maybe remember why this was the case? I suppose it was only meant to apply to the subtable itself but not the rootTable and is simply a bug.

**Comment by sgiehl** [comment]
@tsteur can't remember actually. Maybe it was a usability thing. As changing the limit with an open subtable would actually close the subtable again and not show more rows in the subtable.

**Comment by tsteur** [comment]
OK lets allow changing the value of rows to show even when there is a subtable open. If this becomes an issue then we can revert the change again later.
