### ISSUE TITLE
Sticky "Maximize" tooltip 

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17625]
Move the mouse cursor on the dashboard over the maximize icon.
Wait till the "Maximize" mouse title appears.
Than click on the icon.
=> The widget opens in a maximized mode
But the black "Maximize" mouse title sicks to the cursor and will not disappear.

<img width="574" alt="grafik" src="https://user-images.githubusercontent.com/1645099/119682405-27844c00-be43-11eb-9407-8580bab85537.png">

<img width="517" alt="grafik" src="https://user-images.githubusercontent.com/1645099/119682852-81851180-be43-11eb-9365-1ea5a09e09da.png">

## Expected Behavior
mouse title disappears after leaving the icon, also when the widget maximized

## Current Behavior
mouse title does NOT disappear

## Steps to Reproduce (for Bugs)
see above

## Your Environment
* Matomo Version: 4.3.1
* Browser: Firefox 88

**Comment by sgiehl** [comment]
Hi @mathContao. Thanks for creating this issue. I was able to reproduce that on our demo using Firefox. In Chrome it seems to work fine. Guess we need to force closing the tooltips when the maximize button is clicked.
