### ISSUE TITLE
Segment uses wrong archive to report visits

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#17631]
When a certain segment (archived server side) is selected, daily reports are correct, but range/monthly/year reports are completely off / wrong. It seems like the higher periods would use outdated / wrong archives to calculate data. The numbers are all wrong, but in the visits count, this is most obvious, because it shows 15 times more visits than pageviews, but in the graphs you can see, that pageviews are always higher than visits. It is possible that the segment was edited shortly after the setup, but the client can't tell for sure.

## Expected Behavior
Segment reporting should only use correct segment archives.

## Current Behavior
Since the segment reports is showing the wrong data, I suspect it to use the wrong archives.

## Possible Solution
Make sure to use the correct archive identifiers and don't use outdated archives, especially (but not only) after the segment definition was changed.

## Steps to Reproduce (for Bugs)
Not reproducible on demo. I suspect this to be a rare edge case, since I wasn't able to reproduce it in 3 different instances.

## Context
-

## Your Environment

* Matomo Version: 4.2.0
* PHP Version: 7.4
* Server Operating System: Debian
* Additionally installed plugins: Funnels, Custom Reports, Cohorts, Heatmaps, A/B Tests, MediaAnalytics, FormAnalytics

Segment definition:
![segment_settings](https://user-images.githubusercontent.com/1018973/119876048-bff3fc80-bf27-11eb-81c8-9552049ec256.JPG)

Reports:
![segment_report-other-range](https://user-images.githubusercontent.com/1018973/119876097-ce421880-bf27-11eb-9868-de62de578605.JPG)
![segment_report-period-month](https://user-images.githubusercontent.com/1018973/119876101-cedaaf00-bf27-11eb-936f-201b43230ff1.JPG)
![segment_report-range](https://user-images.githubusercontent.com/1018973/119876103-cf734580-bf27-11eb-998a-e45681b37a4f.JPG)
![segment_report-api](https://user-images.githubusercontent.com/1018973/119876105-d00bdc00-bf27-11eb-859d-b43b339e8776.JPG)

**Comment by diosmosis** [comment]
Hi @peterbo, there were a lot of bugs fixed around this in 4.3, would you be able to upgrade and check again? It might be required to invalidate the periods w/ inaccurate data.

**Comment by peterbo** [comment]
Hi @diosmosis thanks for the fast response! At the moment, we can't update yet, but I hope this will be possible soon, since it's also my recommendation. I'll report back, when the update was done, but it can take some time (because of client infrastrcture and compliance).

**Comment by ggr-mtm** [comment]
Hi 
We were facing to the same problem with 4.2.1 version. And now I confirm, all problem ar solved with 4.3. But you may need to truncate report tables before invalidate .

**Comment by Jaimeapo** [comment]
We are using 4.4.1 and have similar problems.
![image](https://user-images.githubusercontent.com/2892389/137182241-0240cca1-91aa-4f00-ad88-8282c9f1da59.png)

**Comment by tsteur** [comment]
@peterbo are you still experiencing this issue on a more recent Matomo version?

**Comment by peterbo** [comment]
@tsteur for the instances in question, this was fixed after updating to Matomo >4.3. This here looks more like an archiving problem, because the "All Visits" graph also jumps to 0% sometimes. So there might be a specific problem with @Jaimeapo instance (e.g. archiving, memory, timeout, etc.)

**Comment by tsteur** [comment]
Thanks for this @peterbo I'll close this issue for now. 

Indeed what @Jaimeapo mentioned sounds like a different issue. @Jaimeapo it may help to invalidate the dates where it shows 0 and then see if the reports come up see https://matomo.org/faq/how-to/faq_155/  . If this then continues to happen then it might be something that needs to be looked at.
