### ISSUE TITLE
The same access session produces two different visitorids

### ISSUE THREAD

**Issue by Amber-Wish** [piwik/piwik#17647]
hello, When I checked the data, I found the data in the following picture.
![image](https://user-images.githubusercontent.com/55867470/120839932-2918e700-c59c-11eb-9c1c-698296aa06ea.png)
Is this data normal? Why is this kind of data produced? I hope to get a reply. thank you.

Our Environment
Matomo version: 4.3.1
PHP version: 7.4.19

**Comment by diosmosis** [comment]
Hi @Amber-Wish, by default Matomo will look for an existing visit by visitor ID, and if none is found, try to look for one using the device fingerprint (within the last 30 mins), in case the visitor ID changes for some reason. If the `config_id` for the two visitor IDs is the same, this is what happened. If you don't want this to be done, you can disable this behavior: https://matomo.org/faq/how-to/faq_175/

Does this answer your question?

**Comment by Amber-Wish** [comment]
yes, thank you!
