### ISSUE TITLE
<wbr> can be displayed in tooltip in "Row Evolution"

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17679]
How to go there:
Behavior-> Page titles -> Open Row Evolution
<img width="1175" alt="grafik" src="https://user-images.githubusercontent.com/1645099/122233405-529b1200-cebc-11eb-8a4f-abf0f85c4334.png">

Move with the mouse cursor over the title and see the black mouse title text
<img width="958" alt="grafik" src="https://user-images.githubusercontent.com/1645099/122234295-12885f00-cebd-11eb-932a-abc1773152ea.png">

## Expected Behavior
no HTML tags shown

## Current Behavior
wbr HTML tag is shown in the mouse title

## Your Environment

* Matomo Version: matomo.cloud.com / 4.3.1

**Comment by sgiehl** [comment]
thanks @mathContao for creating the issue. I can confirm that the tooltip shows those tags. Will check if that can be changed easily.
