### ISSUE TITLE
dev/sda2        50G   43G  4.4G  91% /var

### ISSUE THREAD

**Issue by tipoa** [piwik/piwik#17699]
I am not a developer. Our website host is reporting a critical status:-
<img width="625" alt="PastedGraphic-2-37" src="https://user-images.githubusercontent.com/8222075/122886540-59a0a500-d340-11eb-8470-b79638932082.png">

I have today gone into the ADMIN of our Matomo account and requested to delete old raw data etc.. and reducing the amount of time data is retained in a log.

I am very much guessing this will solve this issue. Nothing has happened instantly, but perhaps this will take time?

How can I clear the log at dev/sda2 ? Can it be done from the ADMIN ?

regards
Beatriz

**Comment by sgiehl** [comment]
Hi @tipoa 
Log data deletion is normally done using background tasks. It might take a while till they are removed. But it can also be forced. See https://matomo.org/faq/troubleshooting/faq_42/

Note: This issue tracker is only used for bug reports and feature requests. For further support please refer to our forum at https://forum.matomo.org
