### ISSUE TITLE
disable plugins in config.ini.php

### ISSUE THREAD

**Issue by kevin-shelaga** [piwik/piwik#17708]
The following settings do not disable plugins as expected, is this currently possible?

```
[General]
enable_trusted_host_check = 0
salt = "xxxxxxxxxxxxxxxx"
enable_marketplace = 0
enable_goals = 0
enable_tour = 0
enable_feedback = 0
enable_mobilemessaging = 0
enable_ecommerce = 0
```

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Hi @kevin-shelaga.
It is possible to simple deactivate plugins in the UI. If that doesn't suite you, you can use the console command `./console plugin:deactivate pluginname` or remove the plugin from the plugins list in `config.ini.php`

**Comment by kevin-shelaga** [comment]
Thank you @sgiehl how would I disable them from the UI? I could not find instructions for that. I am on 4.3.1. 

When I removed the plugin from the config file, it would be automatically added back in a second later. It do you mean remove the plugin from the plugin directory?

**Comment by sgiehl** [comment]
In administration under System > Plugins. But some plugins can't be disabled as they are required.

**Comment by kevin-shelaga** [comment]
@sgiehl tyvm!
