### ISSUE TITLE
Invalidate Reports UI unable to invalidate segments with '>' or '<' in the segment, incorrectly encoding characters

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#17701]
## Expected Behavior

The Invalidate Reports UI tool should be able to invalidate segments with special characters, such as `>` or `<`

## Current Behavior

When invalidating a segment with either the character `>` or `<` currently results in the following error:
`The segment condition 'actions&gt' is not valid.`
![image](https://user-images.githubusercontent.com/20905821/123009988-dcddfb80-d411-11eb-880e-e07c22d70eed.png)

## Possible Solution

It seems as though the Invalidate Reports UI is not correctly encoding the segment when invalidating the reports, running the command with the correct URL encoding: `./console core:invalidate-report-data --segment='actions%3E1' --dates=XXX` works to invalidate the reports from an SSH session. 

## Steps to Reproduce (for Bugs)

1. Create a report with at least one condition as either greater than(>) or less than(<)
2. Invalidate that segment in the Invalidate reports plugin in the Administration > System menu

## Your Environment

* Matomo Version: 4.3.1

**Comment by tsteur** [comment]
@Starker3 do you mind closing this issue and recreating it in https://github.com/innocraft/plugin-InvalidateReports/issues ? Because it is a different organisation I cannot move it there. I could create it there myself but then you won't receive notifications for comments.

**Comment by Starker3** [comment]
Re-created here: https://github.com/innocraft/plugin-InvalidateReports/issues/16
