### ISSUE TITLE
Typo: Feautre

### ISSUE THREAD

**Issue by Ryuno-Ki** [piwik/piwik#17723]
## Expected Behavior

In a German setup, adding a new website shows a typo for the Visitor Profile checkbox.

## Current Behavior

https://github.com/matomo-org/matomo/blob/a627ca1711d9b7f49e05fe56dd474a08da4a4801/plugins/Live/lang/de.json#L35

has a character swap.

## Possible Solution

* Update the JSON (Feautre -> Feature).
* Run some spellcheck as GitHub Action? (stretch goal)

## Steps to Reproduce (for Bugs)

1. Log into Matomo (I'm self-hosting)
2. Switch to Settings
3. Use Quicklink to create a new tracking (general website, i.e. not internal)
4. Scroll down to Visitor Profile
5. Read explanation card

## Context

Typos are haunting me. (I'm fine, thanks).

## Your Environment

* Matomo Version: 4.3.1
* PHP Version: 7.4.20
* Server Operating System: CentOS (I believe - it's shared hosting)
* Additionally installed plugins:

* Browser: Firefox
* Operating System: Sabayon Linux

**Comment by Findus23** [comment]
Hi,

Thanks for the notice, I fixed the translation.
If you like fixing typos, you can join the translation team on transifex: https://www.transifex.com/matomo/matomo :)

**Comment by Ryuno-Ki** [comment]
Ah, there it is!
I was a bit confused by the outgoing link. (German seems to be fine with 99%).
