### ISSUE TITLE
Use multiple/different database for each domain to be tracked (On Premise)

### ISSUE THREAD

**Issue by aayush27894** [piwik/piwik#17739]
Hello,

I am currently tracking user metrics for 2 domain names/websites using a single "On-Premise" matomo instance. Each of them are being used by different clients. The issue is that all of the data is getting stored in the same database, that might be a security concern for both the clients as both their user data gets stored in the same database and tables. Even though matomo gives a way to isolate the domains at a UI level by creating users to control the access, that isn’t enough.

I was wondering if there is any way of storing the data for each domain that we are tracking to be stored in separate databases and if not separate databases, even separate schemas in the same database should be good enough.

**Comment by diosmosis** [comment]
Hi @aayush27894, the only way currently to separate users by database is to have a multi tenant setup. We have some documentation about it here: https://developer.matomo.org/guides/multi-tenants . If you have further questions about how to set this up, please ask on the forums (https://forum.matomo.org/).
