### ISSUE TITLE
New console command "core:version" outputs the Matomo version information

### ISSUE THREAD

**Issue by ziegenberg** [piwik/piwik#17755]
## Summary

The Symfony built-in commands for the console provides an `--version (-V)` option to "_Display this application version_". It, however, is not just the version information, but it is prefixed with the string `Matomo version`, which makes it harder to parse and compare, e.g. with what `https://builds.matomo.org/LATEST` returns.

I'd like to have a `core:version` command that outputs the bare version information without any additional strings. This comes in handy when automating things using the console for headless updates.

## Your Environment

* Matomo Version: 4.3.1
* PHP Version: 8.0.8
* Server Operating System: RHEL
* Additionally installed plugins:

**Comment by diosmosis** [comment]
Fixes by 17757

**Comment by diosmosis** [comment]
Fixed by #17757
