### ISSUE TITLE
Install issue: Matomo couldn't write to some directories

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17766]
I uploaded a fresh Matomo via FTP and wanted to start the install routine. But I get this error message

![grafik](https://user-images.githubusercontent.com/1645099/125523216-e0d93330-647b-488a-91c7-0a7c5421f292.png)

The problem: the `tmp` folder has no sub directories.

## Expected Behavior
no error, start of install routine

## Current Behavior
see screenshot

## Steps to Reproduce (for Bugs)
fresh install

## Your Environment
* Matomo Version: 3.4.1
* PHP Version: 7.4

**Comment by Findus23** [comment]
> The problem: the tmp folder has no sub directories.

That's exactly the problem. The user with which PHP is running doesn't have the right file permissions to create files and directories in tmp/. How to change this depends a lot on your webserver setup, but changing the owner to the PHP-user (often `www-data`) or changing the file permissions often helps.

**Comment by math-GH** [comment]
I see that the problem could be on my server. Just 777 works. And that could not be the solution. I am in contact with my hoster.

**Comment by math-GH** [comment]
I found the issue. Server-User and FTP-user had a miss match. After support from my web hoster it is solved now.
