### ISSUE TITLE
Receiving Error core:archive since latest update

### ISSUE THREAD

**Issue by maquejp** [piwik/piwik#17760]
## Expected Behavior
The Archive work successfully and do not send error email. 

## Current Behavior
I receive an error email every hour

## Steps to Reproduce (for Bugs)
No steps, after update of matomo, I started receiving the emails

## Context
Matomo has an erratic behavior. I suppose that this is linked.
index.php?module=Installation&action=systemCheckPage&idSite=2&period=day&date=yesterday <- fail 

## Your Environment
Matomo version: 4.3.1
MySQL version: 10.2.36-MariaDB-log
PHP version: 7.4.19
Shared Hosting (InmotionHosting.com)
OS: Linux

## Message received
`ERROR [2021-07-13 09:46:07] 3096330  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=week&date=2021-07-12&format=json&trigger=archivephp. Response was '{"result":"error","message":"Illegal length modifier specified 'f' in s[np]printf call"}'
ERROR [2021-07-13 09:46:10] 3096330  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=month&date=2021-07-01&format=json&trigger=archivephp. Response was '{"result":"error","message":"Illegal length modifier specified 'f' in s[np]printf call"}'
ERROR [2021-07-13 09:46:11] 3096330  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=3&period=year&date=2021-01-01&format=json&trigger=archivephp. Response was '{"result":"error","message":"Illegal length modifier specified 'f' in s[np]printf call"}'
ERROR [2021-07-13 09:46:14] 3096330  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=5&period=week&date=2021-07-12&format=json&trigger=archivephp. Response was '{"result":"error","message":"Illegal length modifier specified 'f' in s[np]printf call"}'
ERROR [2021-07-13 09:46:16] 3096330  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=5&period=month&date=2021-07-01&format=json&trigger=archivephp. Response was '{"result":"error","message":"Illegal length modifier specified 'f' in s[np]printf call"}'
ERROR [2021-07-13 09:46:17] 3096330  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=5&period=year&date=2021-01-01&format=json&trigger=archivephp. Response was '{"result":"error","message":"Illegal length modifier specified 'f' in s[np]printf call"}'
ERROR [2021-07-13 09:46:18] 3096330  6 total errors during this script execution, please investigate and try and fix these errors.
ERROR [2021-07-13 09:46:18] 3096330  Uncaught exception: /home/xxx/public_html/pwk/core/CronArchive.php(599): 6 total errors during this script execution, please investigate and try and fix these errors.
                                                                                                 
  [Exception]                                                                                    
  6 total errors during this script execution, please investigate and try and fix these errors.  

core:archive [--url="..."] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--skip-segments-today] [--force-periods[="..."]] [--force-date-last-n[="..."]] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]] [--force-all-websites] [--force-report[="..."]]`

## Other related error
index.php?module=Installation&action=systemCheckPage&idSite=2&period=day&date=yesterday&showtitle=1&random=4471

`A fatal error occurred
The following error just broke Matomo (v4.3.1):

Illegal length modifier specified 'f' in s[np]printf call
in /home/xxx/public_html/pwk/vendor/twig/twig/src/Cache/FilesystemCache.php line 61  `

**Comment by diosmosis** [comment]
Hi @maquejp, can you provide your php version, tell us how you are deploying matomo (are you using git? did you install the composer dependencies yourself?) and whether you are using any third party plugins that aren't distributed with matomo?

Can you also provide the contents of FilesystemCache.php that the error references?

**Comment by tsteur** [comment]
Hi @maquejp please have a look at this issue: https://github.com/matomo-org/matomo/issues/16613
