### ISSUE TITLE
Missing performance metrics for most dates

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#17761]
When viewing the performance metrics we are missing data for most dates

## Expected Behavior
When looking at performance metrics we expect to find data for all dates.

## Current Behavior
We have data for different dates.

![image](https://user-images.githubusercontent.com/712838/125457282-220b95bc-4083-442e-b567-476f0060521f.png)

We are using Matomo 4.3.1

Data is archived with cron archiver, no errors in the logs for missing dates for performance metrics.

**Comment by diosmosis** [comment]
@mikkeschiren for days that have missing metrics, can you check in the log_link_visit_action table if there are any positive values in the performance dimension columns, for example `time_dom_processing`, `time_dom_completion`, `time_network`, etc.?

**Comment by mikkeschiren** [comment]
@diosmosis - values were in fact NULL on the dates with no data that I tested, how could  this happen?

**Comment by sgiehl** [comment]
@mikkeschiren are you using the normal javascript tracking? Those values should actually be automatically tracked in this case (if the users browser provides them).

**Comment by mikkeschiren** [comment]
I will check with our analysts if they have done some changes on some dates, but with the results we are getting, that does not really make sense (couple of days per month that we have results, and then thousands of them, and next day none). But with that said - it could be an implementation problem.

**Comment by tsteur** [comment]
@sgiehl wouldn't it be expected in some cases when the tracking request is sent before the browser load event for example and there is no follow up load event?

**Comment by sgiehl** [comment]
Yes. indeed. If the page tracking event is sent before the performance metrics are available they will be sent with the next tracking request. If no further tracking request is sent, the performance metrics might not be tracked at all.
It might work to trigger a ping once the page was completely loaded

**Comment by mikkeschiren** [comment]
This could be a implementation issue, I think we can close this now.

**Comment by tsteur** [comment]
👍  thanks for letting us know @mikkeschiren
