### ISSUE TITLE
Provide filtering for headless browser

### ISSUE THREAD

**Issue by beankylla** [piwik/piwik#17763]
## Summary
Hello,

as [asked in the forum](https://forum.matomo.org/t/segment-visitors-whose-browser-is-headless/30869) (post without answer), we would need to be able to filter or exclude headless browsers
It is possible to see when a headless browser visit comes but there is no way of filtering /  excluding it. (unless this is already done when filtering out bots etc? (did not find anything on the subject)

 I think most headless browser are not humans so should not really be an issue.

Thanks for the consideration!

**Comment by tsteur** [comment]
Hi @beankylla The [tracking spam prevention plugin](https://plugins.matomo.org/TrackingSpamPrevention) does that.

**Comment by beankylla** [comment]
Thanks perfect!
