### ISSUE TITLE
Call to undefined method Piwik\\DataTable\\Map::getRowFromLabel() in plugins/UserCountry/API.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17776]
refs https://github.com/matomo-org/matomo/issues/13507

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Map::getRowFromLabel()","file":"plugins\/UserCountry\/API.php","line":46,"request_id":"41b0e","backtrace":" on plugins\/UserCountry\/API.php(46)\n#0 [internal function]: Piwik\\Plugins\\UserCountry\\API->getCountry('all', 'day', 'last14', false)\n#1 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#2 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#3 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#4 core\/API\/Request.php(266): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getCountry', Array)\n#5 plugins\/API\/Controller.php(46): Piwik\\API\\Request->process()\n#6 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#7 core\/FrontController.php(615): call_user_func_array(Array, Array)\n#8 core\/FrontController.php(167): Piwik\\FrontController->doDispatch('API', false, Array)\n#9 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#10 index.php(25): require_once('c...')\n#11 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(615): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(167): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(98): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(138): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(188): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> ?token_auth=XYZANONYMIZED&module=API&method=Referrers.getReferrerType&method=UserCountry.getCountry&idSite=all&period=day&date=last14&segment=&format=json&filter_limit=-1

No referrer

will comment  then this happens again.

**Comment by sgiehl** [comment]
Easy as well. The filter in the method currently can't handle a Map of Datatable Maps. Will provide a quick fix.
