### ISSUE TITLE
Javascript console error when clicking Install routine: Download System Check button

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17787]
Install routine
Page 2

Button "Download System Check"

Does not work. JavaScript error.
![grafik](https://user-images.githubusercontent.com/1645099/126038323-dcbde0eb-c665-4fe1-be5f-402f01872659.png)

## Expected Behavior
download works without an JavaScript error

## Current Behavior
download does not work

## Your Environment
* Matomo Version: 4.3.1
* Browser: Firefox 90

**Comment by Findus23** [comment]
I guess
https://github.com/matomo-org/matomo/blob/2b35b46a0988f8c3b6f848c59be8d7d918965a52/plugins/Morpheus/javascripts/piwikHelper.js#L32 

is not included in the installation page

**Comment by tsteur** [comment]
👍  and/or it needs to be `piwikHelper` instead of `piwik.helper`
