### ISSUE TITLE
Page Overlay Plugin trying display a page that blocks being embedded in an i-frame

### ISSUE THREAD

**Issue by RadekKosiada** [piwik/piwik#17781]
We use Page Overlay Plugin on the page that blocks being displayed in an i-frame within the Plugin and so the whole Plugin doesn't work. We can't see the page, and on the right side it says 'Loading..'.

We cannot adjust the settings of the page due to the policy again clickjacking. 
Can we still use the Plugin, if the page cannot be displayed in the i-frame?

**Comment by sgiehl** [comment]
Hi @RadekKosiada. I guess that depends how you prevent the page from being displayed in an iframe.
Maybe you can find a workaround here: https://matomo.org/docs/page-overlay/#1-it-doesnt-work-at-all
For further help please ask such questions on our forum (https://forum.matomo.org) as we only handle bug reports and feature requests here.
