### ISSUE TITLE
Install routine: language changer line height improvements

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17786]
![grafik](https://user-images.githubusercontent.com/1645099/126037769-f5eb0732-56ba-4085-8e59-7f3f7e10ad47.png)

## Expected Behavior
smaller gap between line 1 and 2

## Current Behavior
big gap (line-height: 30px)

![grafik](https://user-images.githubusercontent.com/1645099/126037811-a5f267fd-fa18-4296-9206-33be019befc9.png)

## Possible Solution
```
.menuDropdown .items .item {
  padding: 12px 25px 12px 6px !important;
  line-height: 16px;
}
```
![grafik](https://user-images.githubusercontent.com/1645099/126037908-2972c147-6ceb-41d0-8081-f90a3e424db6.png)

## Your Environment

* Matomo Version: 4.3.1
* Browser: Firefox 90

**Comment by sgiehl** [comment]
@mathContao  Thanks for your report. If you have tested your possible solution, feel free to simply create a Pull Request to fix it.
