### ISSUE TITLE
Install routine: "In case you are using an ad blocker, please ..."

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17784]
Install routine first page:

![grafik](https://user-images.githubusercontent.com/1645099/126033841-6c475782-4610-49e0-a8af-762aeb615264.png)

Step 2:
![grafik](https://user-images.githubusercontent.com/1645099/126034076-3f07aa0c-42b7-4733-b314-54bb83b9b3ea.png)

## Expected Behavior
a better UI. Show the message at the top with a modern UI.

## Current Behavior
looks a little bit outdated

## Your Environment

* Matomo Version: 4.3.1

**Comment by donovanglover** [comment]
For anyone that wants to fix this, the current code is located in [`plugins/CoreHome/templates/_adblockDetect.twig`](https://github.com/matomo-org/matomo/blob/2f80606b1db3caaeb4195ff7cd0bf949b2154968/plugins/CoreHome/templates/_adblockDetect.twig)

**Comment by tsteur** [comment]
I just got to see the ad blocker page and it wasn't really visible that the page is blocked by an ad blocker until I noticed after a while the top sentence in red. That's on an already installed in Matomo. Wasn't clearly visible
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/273120/194797284-101fd3fa-0a0d-4d12-9fdf-fd0b235de196.png">
