### ISSUE TITLE
Recent 4.3.1 Upgrade. Getting Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function

### ISSUE THREAD

**Issue by jbrule** [piwik/piwik#17796]
Upgraded from 3.13.6 -> 4.3.1

I recently upgraded to 4.3.1 and most things are working well. I am however getting the following error when querying monthly Time states for some sites. FYI. The the initial archive after upgrade is still running (via cron). Other sites works for this particular time frame. Any tips?

```
Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information):
```
I see some NULL ```visitor_localtime``` entries in my ```log_visit``` table but it is not consistent as those sites doesn't error out when retrieving the report

![Matomo-4 3 1 Error](https://user-images.githubusercontent.com/765798/126212513-20eb57d1-784f-4515-99f6-5f1ad870841e.png)
![Matomo Diagnostics](https://user-images.githubusercontent.com/765798/126212519-1b4bd38b-d34e-4430-afe7-faf9f23e1080.png)

**Comment by jbrule** [comment]
This is in the logs
```
ERROR CoreHome[2021-07-19 17:49:54 UTC] [591e0] Failed to get data from API: /apps/apache/www/production/matomo/core/Date.php(1126): Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information):
WARNING CoreHome[2021-07-19 18:56:16 UTC] [3b902] /apps/apache/www/production/matomo/plugins/VisitTime/functions.php(18): Warning - mktime() expects parameter 1 to be integer, string given - Matomo 4.3.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/plugins/VisitTime/functions.php(18),#3/core/DataTable/Filter/ColumnCallbackReplace.php(96),#4/core/DataTable.php(528),#5/core/DataTable.php(613),#6/core/API/DataTablePostProcessor.php(303),#7/core/API/DataTablePostProcessor.php(133),#8/core/Plugin/Visualization.php(536),#9/core/Plugin/Visualization.php(193)

```

**Comment by diosmosis** [comment]
Hi @jbrule can you apply this PR: https://github.com/matomo-org/matomo/compare/17796-debugging?expand=1 and trigger the error again? It will hopefully provide some more details.

**Comment by jbrule** [comment]
```
unable to parse date label:
```
![matomo-parse-label](https://user-images.githubusercontent.com/765798/126392191-2f145f35-16bc-4b98-aa28-d0ff47ff3e7d.png)

**Comment by diosmosis** [comment]
@jbrule I'm not sure why the label is empty there, they should be predefined... I've updated the branch: https://github.com/matomo-org/matomo/compare/17796-debugging?expand=1 . Can you apply the changes then post a screenshot of the report that is created (preferably in the table view)?

**Comment by jbrule** [comment]
![matomo-time-table](https://user-images.githubusercontent.com/765798/126394853-06586602-2fb8-4c32-a300-8a0340588c44.png)

**Comment by diosmosis** [comment]
@jbrule looks like you've got a visit with no local time data... can you check the log_visit table for a visit where `visitor_localtime IS NULL AND idsite = ? AND visit_last_action_time >= ? AND visit_last_action_time < ?` substituting the idSite and start and end time for the period you're looking at? For example:

```
SELECT * FROM log_visit WHERE visitor_localtime IS NULL AND idsite = 1 AND visit_last_action_time >= '2021-06-20 00:00:00' AND visit_last_action_time < '2021-06-21 00:00:00';
```

**Comment by jbrule** [comment]
```SELECT COUNT(*) FROM piwik_log_visit WHERE visitor_localtime IS NULL```
5886

**Comment by diosmosis** [comment]
@jbrule I've created a PR to handle the NULL values you're having: https://github.com/matomo-org/matomo/pull/17801 . But you may want to look into why there are NULL values there, as the PHP tracker code doesn't allow the column to be NULL.

**Comment by jbrule** [comment]
Looks like these happened around the time of upgrade. It's a pretty small number of the whole so I'm just going to purge them and invalidate the archive for the day.

**Comment by jbrule** [comment]
I neglected to disabled Redis Queue processing and some went through. I intended for everything to queue up in Redis until DB schema update was complete.

**Comment by tsteur** [comment]
@jbrule does this mean the issue is resolved now?

**Comment by jbrule** [comment]
> @jbrule does this mean the issue is resolved now?

Yes

**Comment by tsteur** [comment]
great, thanks for letting us know.
