### ISSUE TITLE
"All visits" sometimes shows no visits, but Segments do.

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#17804]
## Expected Behavior
When archiving data I would expect that "All visits" has data, when the segment for the same day has.

## Current Behavior
For some dates, we are getting 0 for All visits, but the segment for the same day has thousands of hits.

This started to happen recently, we have changed some settings in how the archiving works, and it worked for a couple of days, and suddenly, for some dates, we are getting nothing for "All visits". Could this has something to do with invalidated dates?

**Comment by diosmosis** [comment]
@mikkeschiren can you post your system report? And can you provide the periods/segments that this issue involves? If you invalidate and rearchive the all visits archive for the site and period, do you see data?

There was an issue like this about a month or two ago that had a similar effect: https://github.com/matomo-org/matomo/pull/17547 but it was a very specific issue. Some similar mechanism might be at play here.

**Comment by mikkeschiren** [comment]
This behavior has not hap again since I created this issue, maybe some things that were not in sync, I will close this for now, thanks for paying attention.
