### ISSUE TITLE
Reporting API - CSV malformed

### ISSUE THREAD

**Issue by richardstrong** [piwik/piwik#17821]
CSV export header row does not match data row. Data rows have 1 field more and some values clearly do not match the headings. E.g. percentage value for "Avg. Actions per New Visit" or minute & seconds value for "Returning Visits"

## Steps to Reproduce (for Bugs)
Example link: https://demo.matomo.cloud/index.php?date=previous12&expanded=1&filter_limit=100&format=CSV&format_metrics=1&idSite=1&language=en&method=API.get&module=API&period=week&segment=&translateColumnNames=1&convertToUnicode=0

Header fields: 93
Data fields: 94

## Context
Renders CSV export useless – fields are named wrongly, and the importing tool rejects the file

**Comment by sgiehl** [comment]
Hi @richardstrong. Thanks for creating this issue. This was already resolved with #17442 and should be included in the upcoming release
