### ISSUE TITLE
More warnings about missing shell_exec() since Matomo 4.4.0

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17838]
reported in 
https://forum.matomo.org/t/warning-shell-exec-has-been-disabled-for-security-reasons-matomo-4-4-0/42661 (two users)
and
https://forum.matomo.org/t/error-after-update-to-v4-4-0/42679

It seems like this is maybe caused by https://github.com/matomo-org/matomo/pull/17576

**Comment by tsteur** [comment]
It be good to add a `function_exists('shell_exec')` before these calls 👍  and also make sure warnings are suppressed using `@shell_exec` 👍
