### ISSUE TITLE
Overlay not loading since Matomo 4.4.0 upgrade: error setting cookie `_pk_id.1.2f7c`

### ISSUE THREAD

**Issue by maxbraeutigam** [piwik/piwik#17843]
## Expected Behavior
Overlay with analytics data should load and show number of clicks on links etc.

## Current Behavior
Left panel and external site show up, left panel only shows "loading…" indicator and no overlay is produced.

## Possible Reason
The only error visible on the console is 

`There was an error setting cookie `_pk_id.1.2f7c`. Please check domain and path. container_rUey5fiC.js:56:287`

## Steps to Reproduce (for Bugs)
Tried to reproduce on demo.matomo.cloud and indeed, the [overlay here](https://demo.matomo.cloud/index.php?module=Overlay&period=month&date=today&idSite=1#?l=https$3A$2F$2Fdivezone.net$2Fjobs$3F__prod_demo$3D1$26__enterprise_demo_idsite$3D1) is not loading, too.

1. Got to Behavior
2. Pages
3. click on any Overlay

## Context
It broke down after upgrading to 4.4.0, before it was working without any problems.

## Your Environment
* Matomo-Version: 4.4.0
* MySQL-Version: 10.5.11-MariaDB-1:10.5.11+maria~focal-log
* PHP-Version: 8.0.6 
* Server Operating System: Linux
* Additionally installed plugins: None
* Browser: Latest Firefox and Chrome
* Operating System: Arch Linux, Windows
* System check passes without errors

**Comment by sgiehl** [comment]
Hi @maxbraeutigam 
Thanks for creating this issue. The logged error should actually be unrelated to the overlay. Nevertheless it should be fixed with #17830 and will be included in the 4.4.1, which we plan to release early next week.
If it still doesn't work when that error is gone, we might need to investigate that further.

**Comment by justinvelluppillai** [comment]
#17830 will remove the console error setting the cookie but actually #17842 is the fix for the overlay issue, which will be part of the 4.4.1 release early next week.

**Comment by maxbraeutigam** [comment]
Hi @sgiehl, thanks for the quick answer. Yeah, let’s see. I will close the bug, if it’s solved.
Cheers, Max

**Comment by maxbraeutigam** [comment]
Resolved in 4.4.1

**Comment by tsteur** [comment]
Great to hear @maxbraeutigam  👍

**Comment by valentin-ed** [comment]
I'm facing this issue but i upgraded to 4.4.1 few days ago. 

I have this in my console : 
![image](https://user-images.githubusercontent.com/73354059/130195631-20f82525-bbb2-45db-9b30-1b528319054d.png)

I don't know where to look to try to resolve this issue.

Thanks !

**Comment by sgiehl** [comment]
@valentin-ed Where and when exactly are those errors shown? When someone is being tracked, after login or in the overlay feature only?

**Comment by valentin-ed** [comment]
@sgiehl  When someone is tracked, no errors in console. Only when i use the overlay feature.

**Comment by sgiehl** [comment]
@valentin-ed Is the overlay still working, or is it broken?

**Comment by valentin-ed** [comment]
What do you mean ? If the overlay is "drawned" on the screen? Yes it is. But.. look https://i.imgur.com/Zckb0Rg.png
The overlay Keep loading.

**Comment by sgiehl** [comment]
Can you see any other error on the console? Or maybe some resources that can't be loaded?

**Comment by valentin-ed** [comment]
There is nothing more on the console (except a favicon which is not relevant). 

And in the "Network" there is no error. I don't really know where i can find more information. I'm using the Tag manager. May the JS generated by the Tag manager can cause a issue while using the Overlay ?

**Comment by sgiehl** [comment]
Did you create a new container release in tag manager after you updated to Matomo 4.4.1?

**Comment by valentin-ed** [comment]
No, the Overlay wasn't working before. I upgraded because i thought it might solved the problem.

But i did not create a new tag after the upgrade.

**Comment by sgiehl** [comment]
Did you check the troubleshoot hints here: https://matomo.org/docs/page-overlay/#page-overlay-troubleshooting
Maybe that helps. Maybe also try to create a new container release and check if the cookie errors remain.

**Comment by valentin-ed** [comment]
After several tries i found nothing. Even with blocking all javascript except the container.js of my matomo.

The thing is tha the domain is never retrieved. I can find "undefined" in my console. I don't know if it should break but it does.

**Comment by tsteur** [comment]
@valentin-ed if there's the possibility for us to have a look at your Matomo that be great. If that's the case, please create a user in your Matomo with at least `view` access to the site where you have the problem. Please use the email `hello@matomo.org` . There is no need to send us the password as we will do a password reset. You would still need to send us an email with the URL to your Matomo instance. Please also comment here once you have created the user so we can check the spam folder just in case it went there.

**Comment by seyuf** [comment]
Hi @valentin-ed did you solve this issue? I'm having the same thing on matomo **v  4.5.0**.
