### ISSUE TITLE
Performance metrics reports incorrect times due to single exceptional high value

### ISSUE THREAD

**Issue by rr-it** [piwik/piwik#17847]
## Expected Behavior

Performance reports should use relevant time metrics only. Single outlier and exceptions should not be included in the statistics.

## Current Behavior

Single outliers counting like 4 hours instead of 0.01 seconds totally screw up the metrics.

---

![page-performance-metrics](https://user-images.githubusercontent.com/29690343/127863229-7ef17d7f-8099-49e8-bdfb-dac97555175c.png)

Might be one exceptional high value which is already smoothed by 16 normal values.
![page-performance-dom_completion](https://user-images.githubusercontent.com/29690343/127863400-dd231658-fadc-4fd7-add8-0fb79b046f69.png)

Might be one exceptional high value which is already smoothed by 189 normal values.
![page-performance-dom_procession](https://user-images.githubusercontent.com/29690343/127863259-f6b5e9e2-e624-4b50-95e4-99fd531176a8.png)

---

![page-performance-metrics2](https://user-images.githubusercontent.com/29690343/127863754-63d89a0e-5eaa-418e-8d66-f4db4a5522e1.png)

One exceptional high value which screws up the whole metrics.
![page-performance-download_time](https://user-images.githubusercontent.com/29690343/127863765-f114a539-fd8e-4170-a48f-efdbe43e37fe.png)

---

## Possible Solution

Only take the fastest/lowest 99th or 99.9th percentile of all values into account. Thereby ignoring the highest 1st or 0.1th percentile of values makes the metrics usable again.

Maybe use Google PageSpeed as orientation: 75th or 95th percentile
https://developers.google.com/speed/docs/insights/v5/about

## Your Environment

* Matomo Version: 4.3.0

## Related issues

Might be related to https://github.com/matomo-org/matomo/issues/17646

**Comment by tsteur** [comment]
Thanks for the suggestion 👍  Only looking at 99th or 99.5 or 99.9 percentile should be quite helpful there indeed

**Comment by heurteph-ei** [comment]
:+1:  But this kind of data cleaning should be enablable / disablable...

**Comment by rr-it** [comment]
It's not possible right now to do 'filtering by percentile' directly in the db engine as Matomo still supports database engine versions that do not have the needed [window functions](https://dev.mysql.com/doc/refman/8.0/en/window-functions.html).

This new approach just caps insane high values:
- Collected data is not capped. The capping is applied to the generated reports only.
- Default caps are at 100-fold an avg/high value. Thereby one wrong value in 10000 values results in a 1% deviation:
  `(1x 100N + 9999x N) / 10000 ~= 101% N`
- Caps can be adjusted or deactivated via `config.ini.php`

```
[PluginPagePerformance]
; The values used in reports 'sum/total' and 'average' are capped to reduce the impact of single failed performance measurements.
;
; Default caps are at 100-fold an avg/high value. Thereby one wrong value in 10000 values results in a 1% deviation:
; (1x 100N + 9999x N) / 10000 ~= 101% N
;
; To disable capping set cap to: 0
;
; Network: avg/high 100ms
time_network_cap_duration_ms = 10000
; Server: avg/high 500ms
time_server_cap_duration_ms = 50000
; Transfer: avg/high 250ms
time_transfer_cap_duration_ms = 25000
; DOM processing: avg/high 500ms
time_dom_processing_cap_duration_ms = 50000
; DOM completion: avg/high 1500ms
time_dom_completion_cap_duration_ms = 150000
; On load: avg/high 2500ms
time_on_load_cap_duration_ms = 250000
```

Without this PR:
![performance-old](https://github.com/matomo-org/matomo/assets/29690343/92aed68e-c2ac-45b5-9cbc-8f854b09267b)

With this PR:
![performance-new](https://github.com/matomo-org/matomo/assets/29690343/bfac3fde-d4ae-40a9-b386-8dc9bbee4abf)
