### ISSUE TITLE
500 error when loading js asset

### ISSUE THREAD

**Issue by nerdoc** [piwik/piwik#17844]
Using Matomo version 4.3.1

I wanted to update Matomo, but after the klick on te update link and login, the Dashboard stays empty.

## Expected Behavior
Matomo should load normally and load widgets - or update.

## Current Behavior
After login, Matomo shows an empty page:
![grafik](https://user-images.githubusercontent.com/2955584/127638845-20dcde1c-b006-4284-ad7a-a4b836f6d1f5.png)
In the browser console it says:
GET https://analytics.nerdocs.at/index.php?module=Proxy&action=getCoreJs&cb=556b45688935c0968089623b67ce77c5
![grafik](https://user-images.githubusercontent.com/2955584/127638949-0613a7ae-852a-474f-876d-7596155ca8f1.png)

on the CLI, a `console core:update` tells me that everything is up to date. `diagnostics:run` tells me that some files are missing, but only files like

```
Missing file: /var/www/virtual/nerdoc/analytics.nerdocs.at/core/Updates/0.2.10.php                                                                                                      
Missing file: /var/www/virtual/nerdoc/analytics.nerdocs.at/core/Updates/0.2.12.php                                                                                                      
Missing file: /var/www/virtual/nerdoc/analytics.nerdocs.at/core/Updates/0.2.13.php     
...
```

500 error page says: 

```The ui asset with 'href' = ...node_modules/angular-cookies/angular-cookies.min.js is not readable```

## Possible Solution
I went into `node_modules/angular-cookies` and did a

```
wget https://raw.githubusercontent.com/angular/bower-angular-cookies/master/angular-cookies.min.js
```
So I downloaded a current js file from that as workaround. And promptly, Matomo worked again.

But why was this directory empty? BTW, `node_modules/angular-mocks` is empty too. But that's probably ok.

## Context
Trying to make an upgrade to 4.4.0, as the link in the upgrade mail says.

* Matomo Version: 4.3.1
* PHP Version: PHP 7.3.29
* Server Operating System:  CentOS (Uberspace.de)
* Additionally installed plugins:
no I know of. 
* Browser: Firefox/Linux
* Operating System: Manjaro Linux

**Comment by nerdoc** [comment]
FYI: Upgrade went well after this workaround.

**Comment by tsteur** [comment]
`angular-mocks` should usually have a few files too but they might not be used. It sounds like during the last update something went wrong somehow or maybe someone deleted some files on the server by accident? Someone deleting files could be the case if it was working initially after the previous update and then now stopped working. 

Great that it worked after this update. I'll close this error for now but feel free to comment if this happens again and we'll reopen it.

**Comment by nerdoc** [comment]
No, noone changed anything besides me in this Server, and i wasn't logged in since last update. So must:be been an error during update. Can't give more info as it already is done... I'll reopen if after next update sth. similar happens.
