### ISSUE TITLE
When I Clicked 'From Internal Pages' link, I found an Error 'There's no data for http:​/​/​xxxxxxx'.

### ISSUE THREAD

**Issue by maIkeda** [piwik/piwik#17850]
I found an error when doing the following.
Is this a bug?

## Steps to Reproduce (for Bugs)
 1. Behaviour > Page titles
 2. Select 'PAGE TITLE' and Click 'Open Trasitions'
 3. Click 'From Internal Pages' link or 'To Internal Pages' link
 4. Error 'There's no data for http:​/​/​xxxxxxx'

## Your Environment
* Matomo Version: 4.3.1
* PHP Version: 7.4
* Server Operating System: CentOS7

**Comment by sgiehl** [comment]
Hi @maIkeda. I guess #17853 duplicates your report. But as the other issue has a more detailed description, I'll close this one
