### ISSUE TITLE
Error when archiving since update to 4.4.1

### ISSUE THREAD

**Issue by ThorbenOermann** [piwik/piwik#17858]
## Expected Behavior
The hourly archive process should finish without any error.

## Current Behavior
Since upgrading matomo from 4.3.1 to 4.4.1 the archive process throws exceptions every hour. Data does not get archived.
The error message is the following:
```
ERROR [2021-08-04 08:05:03] 5685  Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=4&period=day&date=2021-08-04&format=json&trigger=archivephp. Response was '{"result":"error","message":"Ihre Matomo Codebase läuft auf der alten Version 4.3.1 und wir haben erkannt, dass Ihre Matomo Datenbank bereits auf die neuere Version 4.4.1 aktualisiert wurde. Möglicherweise sind die Matomo Administratoren gerade daran, den Aktualisierungsprozess abzuschließen. Bitte versuchen Sie es in ein paar Minuten noch einmal. Falls dieses Problem weiterhin besteht, kontaktieren Sie bitte Ihren Matomo Administrator für Unterstützung.
```

## Context
I updated our matomo installation via the browser. The update finished successfully. Matomo is running and states that version 4.4.1 is installed. Everything seems to work fine exept archiving.
I manually updated matomo to 4.4.1 again this morning, trying to fix the error. Afterwards I manually started the archive process. It ran through without any error message. 
After another hour the automatic archive process started again and I am getting the same error every hour since.

## Your Environment
* Matomo-Version: 4.4.1
* MySQL-Version: 8.0.20
* PHP-Version: 7.4.21
* Server Operating System: Ubuntu20.04

**Comment by sgiehl** [comment]
Hi @ThorbenOermann 
The error messages says that the code base has not been updated, or at least the file `core/Version.php` still contains the old version. If that is not the case, maybe you have some kind of PHP cache running, that still contains the old content maybe.
Or are you running a multi server setup and maybe forgot to update the code base on one of the servers?

**Comment by ThorbenOermann** [comment]
Hi @sgiehl
Thank you for the quick reply. The file `core/Version.php` contains the correct version number and we are only running one server. But we migrated to another server not long ago and forgot to transfer the cronjob 🤦‍♂️ 
Therefore the archive process was still running on the old server (with matomo 4.3.1) installed.
