### ISSUE TITLE
Some goals not loading properly in AbTesting report when enforcing disable browser archiving

### ISSUE THREAD

**Issue by kelvinatph** [piwik/piwik#17897]
Hi,

This is an issue that occurs for our Matomo v4.4.1 setup when using Goals and AbTesting plugins; the guidelines mention that paid plugins should be directed to a specific email, but I thought I'd share the issue here as well since the problem seemed to be occurring in Goals rather than AbTesting.  If this isn't suitable, please close/delete.

We are using the AbTesting and Goals plugins and in one AbTesting report, we have six goals.  We are also using scheduled archiving and disabled browser archiving by setting `browser_archiving_disabled_enforce=1` in `/var/www/matomo/config/config.ini.php`.  When viewing the AbTesting report in the web interface, two of the goals load fine, but four specific goals do not ever complete loading.  

MySQL timeout is set to 8 hours; PHP script execution time limit is set to 1.5 hours.  After ~1.5h, a red box saying, "Oops, there was a problem during the request" appears.  When using the CLI to load those goals, they return 500 after 1+ hour.  The commands I tried were:

```
/usr/bin/php /var/www/matomo/console climulti:request  'forceView=1&viewDataTable=table&module=AbTesting&action=getMetricDetails&idExperiment=44&successMetric=nb_conversions_goal_88&idSite=1&period=day&date=yesterday&segment=&showtitle=1&token_auth=<REDACTED>'
```

and 

```
/usr/bin/php /var/www/matomo/console climulti:request 'module=API&method=AbTesting.getMetricDetails&idSite=1&format=JSON&idExperiment=44&successMetric=nb_conversions_goal_88&idSite=1&period=day&date=yesterday&segment=&token_auth=<REDACTED>'
```

## Expected Behavior

Expected all six goals to load in a similar amount of time, or at least eventually load before our configured 1.5 hour PHP timeout.

We have other AbTesting experiments set up w/ multiple goals, but they don't experience this problem (the AbTesting report loads within a minute or so for those ones, usually)

## Current Behavior

Four of the six goals fail to load.

I set the logs to DEBUG mode and in the logs, noticed it is trying to load all of the goals; after it's loaded the last one, it goes back to loading the first one and repeating the process over and over again (not sure why):

```
DEBUG Goals[2021-08-08 22:22:35 UTC] [6293] aggregating record Goal_1_visits_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:22:44 UTC] [6293] aggregating record Goal_1_days_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:22:53 UTC] [6293] aggregating record Goal_2_visits_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:23:02 UTC] [6293] aggregating record Goal_2_days_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:23:11 UTC] [6293] aggregating record Goal_3_visits_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:23:19 UTC] [6293] aggregating record Goal_3_days_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:23:28 UTC] [6293] aggregating record Goal_4_visits_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:23:37 UTC] [6293] aggregating record Goal_4_days_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
[...]
DEBUG Goals[2021-08-08 22:19:56 UTC] [6293] aggregating record Goal_110_days_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:20:04 UTC] [6293] aggregating record Goal_111_visits_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:20:13 UTC] [6293] aggregating record Goal_111_days_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
DEBUG Goals[2021-08-08 22:20:22 UTC] [6293] aggregating record Goal_0_visits_until_conv [archive = [idSite = 1, period = range 2021-06-22,2021-07-20, segment = visitorType==new, plugin = Goals, report = ]]
```

After each of those log lines, it also mentions:

```
DEBUG Goals[2021-08-08 22:23:02 UTC] [6293] Archiving is disabled because of config setting browser_archiving_disabled_enforce=1
```

Sorry I don't have the original log – I grepped those notable parts and saved it in a file.  

Because of the message, I tried switching setting `browser_archiving_disabled_enforce=0` in the config file.  I also invalidated the date range mentioned in the debug message and re-archived, using the CLI.  After that, loading the report in the web interface and the CLI was successful; however, it took a long time (~13 minutes) to load the four problematic goals.  

## Possible Solution

As a non-Matomo dev, I'm not sure where exactly the issue is, but the fact that turning off browser_archiving_disabled_enforce might be a hint.

Strangely, only four of the goals in the AbTesting report have the issue.  Our other AbTesting reports that use Goals don't seem to have this problem.  They also load much more quickly than ~13 minutes.  Maybe for some reason these four goals aren't archived by the manual archival process, but then when it attempts to archive via browsing, that also fails because it's disabled.

## Steps to Reproduce (for Bugs)

We have an AbTesting experiment with six goals that is experiencing this problem.  We also have other AbTesting experiments that don't have this problem, and I'm not sure what is different between them.  This issue also is also affected by the `browser_archiving_disabled_enforce` setting, so can't reproduce on the demo Matomo.

I have the PHP Slow Log trace for loading one of the problematic goals, if that's helpful: https://gist.github.com/kelvinatph/662be517bd65c298e69382159d383202

## Context

The issue was affecting us as we could not view the results of the AbTesting experiment around that goal.  After the workaround (disable browser_archiving_disabled_enforce), the main problem is resolved, but it is still inconvenient as the goals take a long time to load on the report.

## Your Environment

* Matomo version: 4.4.1
* PHP Version: PHP 7.2.24-0ubuntu0.18.04.8 (cli) (built: Jul  5 2021 17:41:32) ( NTS )
* Server Operating System: Ubuntu 18.04.4 LTS
* Additionally installed plugins: AbTesting (v4.1.5), HeatmapSessionRecording (v4.0.13)

**Comment by tsteur** [comment]
Hi @kelvinatph , thank you for creating this issue. In this issue tracker we only manage issues around Matomo core. For premium feature related enquiries could you please email our support at shop@innocraft.com 

Thanks again @kelvinatph  and sorry for the inconvenience.
