### ISSUE TITLE
Inconsistent parameter names for trackEcommerceOrder between js API and _normal_ docs

### ISSUE THREAD

**Issue by lennart** [piwik/piwik#17909]
Parameter names used in the [Example of Tracking the Ecommerce Order](https://matomo.org/docs/ecommerce-analytics/#example-of-tracking-the-ecommerce-order)

do not match the parameter names in the [JS Tracking Client documentation](https://developer.matomo.org/api-reference/tracking-javascript#ecommerce)

However, the example includes more detail than the API docs (E.g. expected types and default values).

It would be great if both were consistent.

I'll also file a new issue on the developer-documentation issue tracker (as the issue-template suggests)

**Comment by tsteur** [comment]
@lennart thanks for bringing this up. Do you refer to `revenue` vs `grandTotal`?

**Comment by lennart** [comment]
yes, also see Amsterdam/matomo-tracker#563 for more of the discussion.

**Comment by tsteur** [comment]
Thanks for this @lennart . I've updated the guide.
