### ISSUE TITLE
"Open Row Evolution" in Forms: Error: "Requested report FormAnalytics.getPageUrls"

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17912]
<img width="370" alt="grafik" src="https://user-images.githubusercontent.com/1645099/130426832-f3aba935-b705-40fa-afad-e428ce1f7e76.png">

<img width="1429" alt="grafik" src="https://user-images.githubusercontent.com/1645099/130426563-1ab13668-9015-4205-8c4d-3c9969f0093a.png">

<img width="844" alt="grafik" src="https://user-images.githubusercontent.com/1645099/130426662-be05f152-6f22-417c-a8c4-422b16234f24.png">

## Expected Behavior
No error message. I expect a better information where I should do what.

## Current Behavior
error message

## Steps to Reproduce (for Bugs)
see screenshots

## Your Environment

* Matomo Version: 4.4.1

**Comment by tsteur** [comment]
Hi @mathContao thanks for creating this issue. As it is about a premium feature could you please contact our support about this via shop@innocraft.com ? That would be great as we only manage issues for Matomo core in this repository. Thanks for understanding and sorry for the inconvenience.

**Comment by math-GH** [comment]
ok. Did not know that it is a premium feature.
