### ISSUE TITLE
In Acquisition > Overview report, the Row selector is missing

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#17965]
In the Acquisition > Overview report, the Row selector is missing below the evolution at the top.

Whereas you can still see the row selector under the  evolution graph in "Visitors > Overview" (other evolution graphs show it as well).

Expected the same behavior as in "Visitors > Overview", but in Acquisition > Overview it is missing.

it is problematic because often you need to see the evolution over multiple more than the default number of days or weeks or months, so it means users can't get more context/historical data.

Reproduced in Matomo Cloud  in https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Referrers_Referrers&subcategory=General_Overview and also in 4.5.0-b1

(this is a regression as it used to work)

**Comment by tsteur** [comment]
@mattab it's not clear what you are meaning. 

maybe you mean https://github.com/matomo-org/matomo/issues/17499 where it works until you select more than 2 records to plot?

**Comment by heurteph-ei** [comment]
@mattab @tsteur , maybe this:
![image](https://user-images.githubusercontent.com/79993552/132182280-a6361e1d-ff69-418a-ab50-bf8715957cd5.png)
![image](https://user-images.githubusercontent.com/79993552/132182407-0599f06c-0261-4d3b-bdf4-77382788f415.png)
(note: screenshots taken from version 4.3.1)

**Comment by mattab** [comment]
@heurteph-ei thanks for posting the screenshot :+1:

**Comment by sgiehl** [comment]
#17987 didn't solve that properly. See https://github.com/matomo-org/matomo/pull/17987#issuecomment-920095127
