### ISSUE TITLE
Remove Provider and CustomVariables plugin from our core release

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17973]
Follow up from https://github.com/matomo-org/matomo-package/pull/112

It's been a while since we released Matomo 4 meaning we can now remove Provider and CustomVariables plugin from the core release and only ship it only through the marketplace.

We no longer want to have in `matomo.zip` release zip the directories `plugins/Providers` and `plugins/CustomVariables`. Of course we also need to test that this won't cause any issues for people that are already on Matomo 4.

**Comment by tsteur** [comment]
Closed this issue too early. @peterhashair there is now a test `test_CustomVariablesAndProviderPluginCanBeUninstalledOnceNoLongerIncludedInPackage` failing. 
![image](https://user-images.githubusercontent.com/273120/137204324-fd3519de-d4b2-437a-a726-44b4774e6db6.png)

Seems we possibly also need to adjust the method `isPluginBundledWithCore` in the plugin manager.

**Comment by peterhashair** [comment]
@tsteur sorry about that, removed the test.

**Comment by mig5** [comment]
Whoops: on 4.6.2 somehow I hit a fatal error because Provider was still in my config.ini.php as an installed plugin, via this plugin:

```
user@example:~/piwik/piwik-4.6.2$ grep -r "Provider\Provider" *
plugins/UserCountry/Columns/Country.php:use Piwik\Plugins\Provider\Provider as ProviderProvider;
plugins/UserCountry/Columns/Country.php:        $hostnameExtension = ProviderProvider::getCleanHostname($hostname);
```

Had to remove 'Provider' from the installed plugins by hand from the config.ini.php.
