### ISSUE TITLE
Promote the new SEO web vitals feature 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17975]
Similar to various other premium features we will want to mention this new feature in relevant places similar to eg https://github.com/matomo-org/matomo/blob/4.5.0-b1/plugins/ProfessionalServices/ProfessionalServices.php#L24-L33

As usual we would only show it if the plugin is not installed already.

- [x] We could show it in the `Behaviour -> Performance` page maybe?

- [x]  And maybe also in the search engine report? 

![image](https://user-images.githubusercontent.com/273120/132419903-c42dd6c4-06fc-4bc2-b70b-516121aff166.png)

Link to use: https://matomo.org/recommends/seo-web-vitals/
Text:  Use [SEO Web Vitals](...) to improve your website performance, rank higher in search results and optimise your visitor experience with SEO Web Vitals.

- [x]  At the same time we should also add a new entry for Heatmaps and for Session Recordings to https://github.com/matomo-org/matomo/blob/4.5.0-b1/plugins/ProfessionalServices/Promo.php#L21 (not for SEO web vitals). This will then be visible in the promo widget. 

Link: https://matomo.org/recommends/heatmap-session-recording-learn-more/
Wording: Truly understand your visitors by seeing where they click, hover, type and scroll. Replay their actions in a video and ultimately increase conversions

**Comment by geekdenz** [comment]
I see that e.g.

https://github.com/matomo-org/matomo/blob/4.5.0-b1/plugins/ProfessionalServices/templates/promoSearchKeywords.twig

has the text in the template. I would make it translatable for the new strings only. Do you prefer to keep it simple and put it directly in the template like above for the new promotions?

EDIT: I see they're all 'hard-coded' for lack of a better term.
https://github.com/matomo-org/matomo/tree/4.5.0-b1/plugins/ProfessionalServices/templates

**Comment by justinvelluppillai** [comment]
@geekdenz probably good to do it the same as the others for now. We can separately refactor if we wish to translate all these as a separate issue (which you could create now if you want)
