### ISSUE TITLE
Dashboard Sharing / Copying with all users is not possible

### ISSUE THREAD

**Issue by janheig** [piwik/piwik#18004]
It seems that there is a limited number of users available in the selection for copying a dashboard to users.

in my case, there is a number of 8 registered users (admin / writing rights), but there are only 5 users available, with whom the dashboard can be copied to.

Thanks and best regards!

**Comment by heurteph-ei** [comment]
Is this related to: #17996 ?

**Comment by sgiehl** [comment]
@janheig For super users all users should be visible in the copy dashboard overlay. If an admin opens the overlay he will only see those users that have access to the same site. Maybe that's the case for you?

**Comment by janheig** [comment]
@sgiehl Vielen Dank für den Hinweis! Der betreffende User hatte bisher nur Rechte für die Live-Seite, jedoch nicht für den Staging-Bereich. Mit der Zuweisung der Rechte für das Staging, konnte nun das Dashboard mit dem User geteilt werden.
