### ISSUE TITLE
Uncaught TypeError: document.body is null 

### ISSUE THREAD

**Issue by geekdenz** [piwik/piwik#18003]
This happens on this page in the current 4.x-dev branch.

In developer tools' console:

`Uncaught TypeError: document.body is null` 

materialize.min.js:6:12646

## Expected Behavior

There should not be an error. Discovered this while reproducing https://github.com/matomo-org/matomo/issues/15892 .

## Current Behavior

<img width="957" alt="image" src="https://user-images.githubusercontent.com/479499/133376936-aaa3f3b3-d723-41f2-9e23-a9c19d3be549.png">

## Possible Solution

Not known at this point.

## Steps to Reproduce (for Bugs)

Navigate to page in Matomo instance.

## Context

No known impact, but something might be broken.

## Your Environment

* Matomo Version: commit 9585236c88c591b377758bad315564852c27ef43
* PHP Version: 8.0.10
* Server Operating System: Apple MacBook Pro M1 - macOS Big Sur Version 11.5.2
* Additionally installed plugins: Pure install without ECommerce nor other non-core plugins.
* Browser: Firefox latest
* Operating System: Apple MacBook Pro M1 - macOS Big Sur Version 11.5.2

**Comment by sgiehl** [comment]
I'm not able to reproduce that locally

**Comment by tsteur** [comment]
Can't reproduce it either. @geekdenz maybe check out the 4.x-dev branch and see if you can reproduce it there. And if not close the issue. If you can reproduce the issue be good to mention the exact steps to reproduce the issue and to paste the system report from Admin -> Diagnostics .

**Comment by geekdenz** [comment]
I had the then current `4.x-dev` branch checked out with a clean checkout. Had checked with `git status`. However, now, after a few merges I cannot reproduce this either. Thanks for checking.

**Comment by tsteur** [comment]
fyi replaced label `Potential bug` with `worksforme`
