### ISSUE TITLE
System check widget shows wrong database warning

### ISSUE THREAD

**Issue by BigBerny** [piwik/piwik#18006]
This is what the System check widget on the Admin overview shows a warning about UTF8mb4 when I hover (ignore the other warnings, they are all valid):
![image](https://user-images.githubusercontent.com/1528504/133400898-25d43a10-5eab-4e80-a4ff-7720c8dd613f.png)

This is what I see in the (full) System Check:
![image](https://user-images.githubusercontent.com/1528504/133400351-223e2a02-6109-4c2e-aecc-b16a2ea8765c.png)

* Matomo Version: 4.4.1
* PHP Version: 7.4.20

**Comment by sgiehl** [comment]
I guess the problem is, that the overview simply tries to place the results (you can see in the details) into the tooltip, which doesn't work properly in some cases. Maybe we should simply remove the tooltips to avoid irritations. 

Kind of related to #17627

**Comment by tsteur** [comment]
Maybe could also think about removing line breaks etc then it might work again (and/or strip html)? It could be quite useful to have these tooltips but if not easily doable we can remove the tooltips 👍

**Comment by mwithheld** [comment]
To reproduce the problem, run this in mysql as root:
```
SET GLOBAL local_infile = 'ON';
```

**Comment by mwithheld** [comment]
![18006](https://user-images.githubusercontent.com/796986/133855484-36dfe91e-6ca7-40d9-b14f-25a9c47bd4f8.png)

**Comment by mwithheld** [comment]
This kind of fixes Issue #17627 in that it strips tags, leaving the hyperlink text in place, e.g. 
`<a href="http://blah">Learn more</a>` becomes `Learn more`.

![18006-2](https://user-images.githubusercontent.com/796986/133856036-26233eb1-100b-489a-999f-e8592e7fece4.png)
