### ISSUE TITLE
Add warning about dropping support for IE11 in Matomo user interface

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18012]
We are using Angular.JS library which soon will be no longer receiving updates. This forces us to upgrade to either a newer version of Angular or an alternative library. We've chosen to migrate all our Angular.js components to Vue.js 3 starting in https://github.com/matomo-org/matomo/pull/17940

Unfortunately, Vue.js 3 is not supporting IE 11. This means we have no choice but to drop support for IE11 as well. This follows Microsoft who is [dropping support for IE11](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-support-end-dates) and [WordPress](https://wordpress.org/news/2021/05/dropping-support-for-internet-explorer-11/).

This only applies to the Matomo user interface but not to the Matomo JavaScript tracker which will still support this browser and older IE versions.

To make users aware of this upcoming change, we should show a notification in the reporting and the admin UI that support for this version will soon be dropped.  For the admin part we could do it similar to https://github.com/matomo-org/matomo/blob/4.5.0-b1/core/Plugin/ControllerAdmin.php#L247 . For the UI part we probably need to show that notification somewhere else. We would only show this if IE11 is used.

We should also write a blog post announcing this eg similar to how [WordPress](https://wordpress.org/news/2021/05/dropping-support-for-internet-explorer-11/) did and link to that blog from the notification.

It's not clear yet if some next versions of Matomo will still partially work with IE11 or whether it will not work anymore at all.

Created also a follow up issue to at the latest in Matomo 5.0 mark the browser as no longer supported: https://github.com/matomo-org/matomo/issues/18011

**Comment by tsteur** [comment]
@diosmosis published https://matomo.org/blog/2021/09/matomo-to-end-support-for-internet-explorer-11/ which we can link to. Will you add the notifications? To be a bit faster we could only do the browser detection for IE 11 if the user agent contains `Windows` and `11` maybe? see https://www.whatismybrowser.com/guides/the-latest-user-agent/internet-explorer the user agent would typically look somewhat like `Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko`. Or maybe we could reuse the result from https://github.com/matomo-org/matomo/blob/4.5.0-b2/core/SupportedBrowser.php#L51 somehow?

**Comment by diosmosis** [comment]
@tsteur working on it now. I was thinking of just checking and adding the notification via JavaScript. What do you think?

**Comment by tsteur** [comment]
Sounds good to me 👍  PR looks good to merge just waiting for @sgiehl to confirm in case he notices anything with user agent check
