### ISSUE TITLE
Remove not used DB adapters

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18039]
Meaning https://github.com/matomo-org/matomo/blob/4.5.0-b2/core/Db/Adapter/Pdo/Mssql.php and https://github.com/matomo-org/matomo/blob/4.5.0-b2/core/Db/Adapter/Pdo/Pgsql.php

Since these are not supported can we remove them? It requires us on occasion to add core to these classes when we add methods to the other adapters and it confuses new developers thinking we might support them and that they need to be tested.

@mattab @sgiehl or do you know any reason why they still exist in the code?

**Comment by sgiehl** [comment]
@tsteur can't think of any useful reason. Couldn't even find a reason in git history why they had been added...
