### ISSUE TITLE
If multi_server environment is set, disable Plugin management in GUI

### ISSUE THREAD

**Issue by iamfinky** [piwik/piwik#18048]
## Summary
When running Matomo in a cluster/multi-server environment, by design I cannot activate or deactivate plugins.
When I visit the plugins page in the UI (as a Super-Admin), I can still see options to activate or deactivate plugins.

Could we have a change so that, in this situation:

1. Plugin activation/deactivation controls are removed or disabled
2. A message is added at the top of the page stating "This server is deployed in a multi-server environment. Plugins cannot be managed here" (or something similar).

This would lead to less confusion and, in theory, could be easy to implement (happy to do a PR) given this setting is known and part of the config file.

## Your Environment

* Matomo Version: 4.4.1
* PHP Version: 7
* Server Operating System: Ubuntu
* Additionally installed plugins: FormAnalytics, CustomReports

**Comment by Starker3** [comment]
There is already a config setting to disable plugins install/enable/disable here: https://github.com/matomo-org/matomo/blob/b35a0c8feebb7fc804485cd606872465821cdce1/config/global.ini.php#L747

As well as an additional config setting which disables some other admin settings: https://github.com/matomo-org/matomo/blob/b35a0c8feebb7fc804485cd606872465821cdce1/config/global.ini.php#L775

What we could maybe do is add a warning to the diagnostic/system check if these settings are still enabled with multi server set to 1 in the config?

**Comment by iamfinky** [comment]
Oh, thanks! I had no idea. I'll close this ticket. Cheers! :)
