### ISSUE TITLE
Add system check for 32 bit PHP / OS

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18058]
refs https://github.com/matomo-org/matomo/issues/18019

Let's add a system check if a 32 bit PHP is used and mention we recommend upgrading to a 64 bit to prevent various issues that may come up in the future.

Not sure how many possible integer overflows there are so far in Matomo. We need to do a quick check as part of this issue to know if there might be already issues with 32 bit in PHP by looking through the code (like finding places where we do `time() + ...`

Does anyone know how common 32 bit installs are these days?

**Comment by Findus23** [comment]
> Does anyone know how common 32 bit installs are these days?

For reference: Of all Debian users who have popcon enabled (https://popcon.debian.org/), 190502 use amd64 while 14218 use 1386. But the number is decreasing quite rapidly.
