### ISSUE TITLE
Weblate component needed for Community Plugin RerIntranetSubnetwork

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#18069]
Hello there, I'm sorry to bug you but I have no privileges on the Weblate application, to create any component.
We can use as starting point the [en.json](https://github.com/RegioneER/RerIntranetSubnetwork/blob/4.x-dev/lang/en.json) file.

Please let me join translations, as we did for the [RerUserDates](https://github.com/RegioneER/RerUserDates/issues/17) plugin.

Ciao!

**Comment by sgiehl** [comment]
@Findus23 can you do that one?

**Comment by Findus23** [comment]
It has been created and set up at https://hosted.weblate.org/projects/matomo/communityplugin-rerintranetsubnetwork/ and is currently adding the new languages.
Again, please set up the (same) webhook for the repo.

**Comment by tassoman** [comment]
Webhook is already set! :heavy_check_mark: 
Thanks team :checkered_flag: :racing_car:

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/move-plugin-translations-to-weblate/48860/3
