### ISSUE TITLE
API methods `Actions.XXX` return empty with period set to range and date between first and last day of current month on matomo 3.X

### ISSUE THREAD

**Issue by benIT** [piwik/piwik#18068]
The issue occurs when the `period` parameter is set to `range` and the `date` parameter set to first and last day of current month:

This API call with `period=range` and `date=2021-09-01,2021-09-29` returns data:

 * https://analytics.company.com/?module=API&method=Actions.getDownloads&idSite=4&period=range&date=2021-09-01,2021-09-29&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1

whereas this one with `period=range` and `date=2021-09-01,2021-09-30` returns empty (http status code 200):

 * https://analytics.company.com/?module=API&method=Actions.getDownloads&idSite=4&period=range&date=2021-09-01,2021-09-30&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1 

The same issue happens with other Actions.XXX methods:

*  https://analytics.company.com/?module=API&method=Actions.getPageUrls&idSite=4&period=range&date=2021-09-01,2021-09-30&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1 

 * https://analytics.company.com/?module=API&method=Actions.getPageTitles&idSite=4&period=range&date=2021-09-01,2021-09-30&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1 

*  https://analytics.company.com/?module=API&method=Actions.getEntryPageUrls&idSite=4&period=range&date=2021-09-01,2021-09-30&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1 
...

but not with past months:

 * https://analytics.company.com/?module=API&method=Actions.getDownloads&idSite=4&period=range&date=2021-08-01,2021-08-30&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1 

 * https://analytics.company.com/?module=API&method=Actions.getDownloads&idSite=4&period=range&date=2021-07-01,2021-07-31&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1 

## Workaround with `period=month&` not working

According to [the doc](https://developer.matomo.org/api-reference/reporting-api), we tried to use `period=month`:

* https://analytics.company.com/?module=API&method=Actions.getDownloads&idSite=4&period=month&date=2021-09-30&format=JSON&token_auth=BRuebEp5YJOxn0B3oFRUdur4ReS3K99&flat=1&filter_limit=-1&expanded=1

The API call returns incomplete data, some entries are missing.

## Expected Behavior

API call should return a JSON response with data from the first day until the last day of this month.

## Current Behavior

API call return empty response.

## Steps to Reproduce (for Bugs)

API calls on demo.matomo.cloud demo site work fine:

*  https://demo.matomo.cloud/index.php?module=API&method=Actions.getOutlinks&idSite=1&format=JSON&token_auth=anonymous&period=range&date=2021-09-01,2021-09-30

The demo site is running matomo v4.4.1 whereas our instance is v3.14.1

## Environment

* matomo version: 3.14.1
* PHP version: 7.3.11
* MariaDB version: 10.3.18-MariaDB-0+deb10u1
* OS : debian 10
* Matomo error log: empty

Cheers,
ben

**Comment by sgiehl** [comment]
@benIT  We highly recommend updating to the latest Matomo version, as we likely won't spend much time on fixing issues for Matomo 3
