### ISSUE TITLE
_pk_id _pk_ses cookies are not secured

### ISSUE THREAD

**Issue by rupalikombade** [piwik/piwik#18118]
Is there way to make _pk_id _pk_ses cookies secured? I am using matomo recent version.

**Comment by Findus23** [comment]
Hi,

If you mean by that, that you would like to add the `secure` flag to all tracking cookies (so they are only sent with HTTPS requests), then this guide is the answer:
https://matomo.org/faq/general/faq_25936/

Please next time ask on the forum (https://forum.matomo.org/) as this issue tracker is only intended for bug reports and feature requests.
