### ISSUE TITLE
Incorrect asset URL if reverse proxy provides forwarded URI using headers fields other than HTTP_X_FORWARDED_URI 

### ISSUE THREAD

**Issue by andremartin** [piwik/piwik#18119]
## Expected Behavior

Correct URL generation (for assets) when running Matomo behind a reverse proxy on a sub path.
## Current Behavior

Incorrect URL generation since some reverse proxies such as traefik provide the URI using HTTP_X_FORWARDED_PREFIX rather than HTTP_X_FORWARDED_URI.

## Possible Solution

Extend the URL generation to also consider HTTP_X_FORWARDED_PREFIX if set in addition to HTTP_X_FORWARDED_URI as shown here:
https://github.com/andremartin/matomo/commit/e1322be0f3f3b73ad041733e17c99c312f3b3635

## Your Environment

* Matomo Version: 4.5.0
* PHP Version: 7.3
* Server Operating System: Ubuntu
* Additionally installed plugins:

* Browser: Chrome
* Operating System: Ubuntu

**Comment by tsteur** [comment]
Thanks for reporting this @andremartin . I wonder if we should maybe support also different flags like when `proxy_uri_header=1`(for backwards compatibility) still use `HTTP_X_FORWARDED_URI`.

Then we also allow configuring `HTTP_X_FORWARDED_PREFIX` as a value like 

```
proxy_uri_header="HTTP_X_FORWARDED_PREFIX"
proxy_uri_header="HTTP_X_FORWARDED_URI"
proxy_uri_header="..."
```

Basically, when it's non numeric then we assume a user configured the name of the header.

I'm just meaning this approach be slightly more secure in that the host header cannot be simply set by anyone. By only allowing a specific header eg the user could make sure to not allow this header to be overwritten etc.

**Comment by tsteur** [comment]
@andremartin btw feel free to create a PR for this and we'll review 👍

**Comment by andremartin** [comment]
Looks like this can be solved using e.g. traefik's headers middleware to expose the `HTTP_X_FORWARDED_URI`  field to Matomo. Hence closing as no extra action/functionality is needed anymore.
