### ISSUE TITLE
An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by liping521** [piwik/piwik#18129]
We upgraded Matomo to 4.5.0 and observed a bug.
An exception has been thrown during the rendering of a template ("Unable to write in the cache directory (/var/www/html/tmp/templates_c/f9).").
in /var/www/html/plugins/CoreHome/templates/getDefaultIndexView.twig line 1

**Comment by Findus23** [comment]
Hi,

Can you make sure the user running PHP (and therefore Matomo) does have write access to your `/var/www/html/tmp` directory?

**Comment by tsteur** [comment]
@liping521 I'll close this issue already as it's a server configuration issue. However, we're happy to keep the conversation going. I'm assuming during the upgrade (maybe a manual update of uploading server files or a command was run on the CLI using a different user?) changed some permissions for some directories like the `tmp` or `tmp/templates_c` directory.

**Comment by liping521** [comment]
Yes. After I modify the permission, it's OK.
