### ISSUE TITLE
All sites upload datas to matomo returning a 400, by https://xxx.xxx.com/matomo.php?action_name=xxx&idSite=.....

### ISSUE THREAD

**Issue by liping521** [piwik/piwik#18154]
Method: POST
Response：
![image](https://user-images.githubusercontent.com/92291622/137276004-9c025c46-ac0f-4931-8fd5-60bfe0ed8211.png)

Matomo 4.5.0

**Comment by tsteur** [comment]
@liping521 I see above in the title you are using `idSite`. Try using `idsite`. Also make sure there is a `rec=1` parameter. You can find more about this in https://developer.matomo.org/api-reference/tracking-api
