### ISSUE TITLE
All sites upload datas to matomo returning a 400

### ISSUE THREAD

**Issue by liping521** [piwik/piwik#18159]
Response:
This resource is part of Matomo. Keep full control of your data with the leading free and open source web analytics & conversion optimisation platform.
This file is the endpoint for the Matomo tracking API. If you want to access the Matomo UI or use the Reporting API, please use index.php instead.

Response Headers
access-control-allow-credentials: true
access-control-allow-origin: https://xxx.xxx.com
content-length: 410
content-type: text/html; charset=UTF-8
date: Fri, 15 Oct 2021 00:44:06 GMT
server: nginx
status: 400
x-powered-by: PHP/7.2.20

Request Headers
:authority: xxx.xxx.com
:method: POST
:path: /matomo.php?e_c=%E5%AE%A2%E6%88%B7%E7%AE%A1%E7%90%86&e_a=clicked&e_n=%E5%AE%A2%E6%88%B7%E7%AE%A1%E7%90%86%3E%E6%89%93%E5%BC%80%E5%AE%A2%E6%88%B7%E8%AF%A6%E6%83%85&ca=1&idsite=4&rec=1&r=341100&h=8&m=46&s=18&url=https%3A%2F%2Fxxx.xxx.com%2F&urlref=https%3A%2F%2Fxxx.xxx.com%2Faccounts&uid=test%40test.com&_id=92c78bb5ae2b22c9&_idn=0&_refts=0&send_image=0&pdf=1&qt=0&realp=0&wma=0&fla=1&java=0&ag=0&cookie=1&res=1366x768&dimension1=34pj27enfq34gvdgtlt0smz1gb8B4gsayA0kbTF8wMu&dimension2=test%40test.com&_cvar=%7B%221%22%3A%5B%22nickname%22%2C%22%E7%8E%8B%E4%B8%BD%E5%B9%B3123%22%5D%2C%222%22%3A%5B%22role%22%2C%22%E7%AE%A1%E7%90%86%E5%91%98%22%5D%2C%223%22%3A%5B%22organization%22%2C%22Zmtest-EN1%22%5D%7D&pv_id=uDSKsO
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
content-length: 0
content-type: application/x-www-form-urlencoded; charset=utf-8
origin: https://xxx.xxx.com
referer: https://xxx.xxx.com/accounts
sec-fetch-mode: no-cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by tsteur** [comment]
@liping521 can you share with us your system report see https://matomo.org/faq/troubleshooting/how-do-i-find-and-copy-the-system-check-in-matomo-on-premise/

You would generally get this error if nothing was recorded. For example the set idsite does not exist.

You can also go to `Matomo -> Administration -> Diagnostics -> Tracking failures` and see if anything comes up there.

**Comment by liping521** [comment]
![image](https://user-images.githubusercontent.com/92291622/137424700-8ec2273e-c7c8-4a56-8033-7a55f0f40d59.png)

![image](https://user-images.githubusercontent.com/92291622/137424965-bed50dd8-895b-411b-83c0-66946fc3d115.png)

**Comment by tsteur** [comment]
@liping521 can you copy/paste the entire system check? There's a copy button. We otherwise don't see the full output unfortunately.

Regarding the second screenshot. I don't know exactly what it says but it sounds like a wrong `idsite` URL parameter is used and that's why it's not working.

**Comment by liping521** [comment]
<details>
<summary>Click to view System Check</summary>

### Mandatory checks

#### PHP 版本 >= 7.2.5:
 ✔ 7.2.20

#### PDO 扩展:
 ✔ 

#### PDO\MYSQL 扩展:
 ✔ 

#### MYSQLI 扩展:
 ✔ 

#### 其他必须的扩展:
 ✔ zlib ✔ json ✔ filter ✔ hash ✔ session

#### 必需的功能:
 ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

#### 必要的 PHP 配置（php.ini）:
 ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR = -1 OR >= 30

#### 具有写入权限的文件夹:
 ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c

#### Directories with write access for Tag Manager:
 ✔ $DOC_ROOT/js


### Optional checks

#### Required Private Directories:
 ✔ All private directories are inaccessible from the internet.

#### Recommended Private Directories:
 ✔ All private directories are inaccessible from the internet.

#### 文件完整性:
 ✔ 

#### 追踪器状态:
 ✔ 

#### 内存限制:
 ✔ 512M

#### 时区:
 ✔ 

#### 打开网址:
 ✔ curl

#### PageSpeed 已停用:
 ✔ 

#### GD > 2.x + Freetype（图形功能）:
 ✔ 

#### 其它扩展:
 ✔ json ✔ libxml ✔ dom ✔ SimpleXML ✔ openssl

#### 其它功能:
 ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

#### 文件系统:
 ✔ 

#### 设定Cron - 通过 CLI 管理进程:
 ✔ OK

#### 上次成功完成归档:
 ✔ 归档过程已成功完成00:03:38之前。

#### 数据库能力:
 ✔ UTF8mb4 charset ✔ LOAD DATA INFILE ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level

#### 最大包大小:
 ✔ 

#### 强制 SSL 连接:
 ✔ 

#### 地理位置:
 ✔ geoip2php (continent_code, continent_name, country_code, country_name, region_code, region_name, city_name, postal_code, lat, long)

#### 通过 HTTPS 更新:
 ✔ 

#### 可写的JavaScript追踪器（"/matomo.js" & "/piwik.js"）:
 ✔ 


### Informational results

#### Matomo Version:
 4.5.0

#### Matomo Update History:
 4.5.0,4.4.1,3.13.5-rc1,3.13.4,

#### Matomo Install Version:
 Unknown - pre 3.8.

#### Latest Available Version:
 4.5.0

#### Is Git Deployment:
 0

#### PHP_OS:
 Linux

#### PHP SAPI:
 apache2handler

#### Timezone Version:
 0.system

#### PHP Timezone:
 UTC

#### PHP Time:
 1634267357

#### PHP Datetime:
 2021-10-15 03:09:17

#### PHP INI max_execution_time:
 30

#### PHP INI post_max_size:
 8M

#### PHP INI max_input_vars:
 1000

#### PHP INI zlib.output_compression:
 

#### Curl Version:
 7.29.0, NSS/3.36

#### Suhosin Installed:
 0

#### DB Prefix:
 matomo_

#### DB Charset:
 utf8mb4

#### DB Adapter:
 PDO\MYSQL

#### MySQL Version:
 8.0.13

#### Num Tables:
 411

#### Browser Segment Archiving Enabled:
 1

#### Development Mode Enabled:
 0

#### Internet Enabled:
 1

#### Multi Server Environment:
 0

#### Auto Update Enabled:
 1

#### Custom User Path:
 0

#### Custom Include Path:
 0

#### Release Channel:
 latest_stable

#### Plugins Activated:
 API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CustomDimensions, CustomJsTracker, CustomVariables, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, EventPointConfig 1.0.0, Events, Feedback, GeoIp2, Goals, Heartbeat, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, LanguagesManager, Live, Login, MarketingCampaignsReporting 4.0.4, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Proxy, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, TagManager, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize

#### Plugins Deactivated:
 DBStats, MobileAppMeasurable, ProfessionalServices, Provider

#### Plugins Invalid:
 

#### Server Info:
 Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.20 mod_perl/2.0.10 Perl/v5.16.3

#### Had visits in last 1 day:
 0

#### Had visits in last 3 days:
 0

#### Had visits in last 5 days:
 1

#### Archive Time Last Started:
 1634267102

#### Archive Time Last Finished:
 1634267139

#### User Agent:
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

#### Browser Language:
 en,zh-cn,zh

#### Total Invalidation Count:
 0

#### In Progress Invalidation Count:
 0

#### Scheduled Invalidation Count:
 0

#### Earliest invalidation ts_started:
 

#### Latest invalidation ts_started:
 

#### Earliest invalidation ts_invalidated:
 

#### Latest invalidation ts_invalidated:
 

#### Number of segment invalidations:
 0

#### Number of plugin invalidations:
 0

#### List of plugins being invalidated:
 

#### Anonymize Referrer:
 

#### Do Not Track enabled:
 0

</details>

**Comment by liping521** [comment]
The second screenshot is  unexist siteId, but the site id we are using is 4 and it is existed as following picture shows. We checked the error information analysis and found that the listed ids are unexisted indeed (we didn't use that).  However, we uploaded data into existed site id and it returned us with error code 400
![image](https://user-images.githubusercontent.com/92291622/137425976-cbc822be-bb38-4873-867d-5abbd8615d5f.png)

**Comment by tsteur** [comment]
Thanks for this. The system check looks good.

To troubleshoot this you will need to temporarily enable the tracker debug log.

You can find the needed information in https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker

Mostly needed is adding below lines to your `config/config.ini.php`:

```ini
[Tracker]
debug = 1
```

When you then issue the tracking request, it should print in the response eg in the browser what is going on. 

You will then want to disable those two lines again from the `config/config.ini.php`.

**Comment by liping521** [comment]
Error query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'campaign_content' in 'field list' In query

After add this field to matomo_log_visit, it's ok, Thank you

**Comment by tsteur** [comment]
Great, glad this works now @liping521
