### ISSUE TITLE
Close Tooltip when redirecting to another page

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#18162]
## Expected Behavior

When you open the side menu tooltips, then jump back to the dashboard, the tooltip should close? See Screen Capture

https://user-images.githubusercontent.com/3783072/137431645-b6139787-2339-4bae-8634-7d6bc03f51d6.mp4

## Current Behavior

When you open the side menu tooltips, then jump back to the dashboard, the tooltip remain on top.

## Possible Solution

It maybe carry by session or cookies

## Your Environment

* Matomo Version: 4.6.0

* Browser: Chrome
* Operating System: mac

**Comment by jonathannoel** [comment]
Hey ! I'm on it.
