### ISSUE TITLE
Fix initial export option values so checkbox shows correct value

### ISSUE THREAD

**Issue by AltamashShaikh** [piwik/piwik#18172]
When we try to import any datatable and try to export by unchecking "Expand subtables" option we can see expanded=1 is passed always

## Expected Behavior
Ideally expanded should not be passed in the URL or '0' should be passed

## Current Behavior
Setting expanded=1 always

## Steps to Reproduce (for Bugs)
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=General_Actions&subcategory=Actions_SubmenuSitesearch

Try to export Pages Following a Site Search and you can see even if you uncheck "Expand Subtable" expanded=1 is pass in the URL.

## Context
Was working on fixing issues for Funnels Plugin and observed this issue and was able to replicate the same on demo site.
Since expanded=1 is passed always the result shown on UI is with expanded=false due to which the output on export differs.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Hey @AltamashShaikh 
Thanks for creating this one. I can confirm that the checkbox doesn't work when clicking it the first time. Guess the initial value doesn't fit. Will have a quick look if it's easy to fix
