### ISSUE TITLE
Fix segment creation fails when enable_create_realtime_segments = 0

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18178]
Below config

```
[General]
enable_general_settings_admin = 0
process_new_segments_from = "editLast30"
rearchive_reports_in_past_last_n_months = "last1"
rearchive_reports_in_past_exclude_segments = 1
enable_browser_archiving_triggering = 0
browser_archiving_disabled_enforce = 1
enable_create_realtime_segments = 0
```

Getting this error 
![image](https://user-images.githubusercontent.com/273120/137855184-f02b3e46-621b-4849-8ed6-05092a0f90a0.png)
![image](https://user-images.githubusercontent.com/273120/137855395-b1f24a41-6b64-40ad-b5a0-ebfcc6372be9.png)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/after-upgrade-all-new-segments-pre-processed/45626/2
