### ISSUE TITLE
how can i Segment user by department

### ISSUE THREAD

**Issue by chiraggwalani** [piwik/piwik#18173]
We have multiple departments now how can we segment site visitors by the department?

For ex. 
Userid 1 dept 1
Userid 2 Dept 2
Userid 3 dept 1

then dept1 has 2 visitors

**Comment by sgiehl** [comment]
I guess the best solution would be a custom dimension to track the department for each visitor. See https://matomo.org/docs/custom-dimensions/ for more details about custom dimensions.
Otherwise you may need to create complex segments where you segment for each userid in a department using OR.
