### ISSUE TITLE
Fix possible problem with CSP in overlay feature

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18187]
See https://demo.matomo.cloud/index.php?module=Overlay&period=month&date=today&idSite=1#?l=https$3A$2F$2Fdivezone.net$2Fdiving$2Findonesia$3F__prod_demo$3D1$26__enterprise_demo_idsite$3D1

seeing this error 
![image](https://user-images.githubusercontent.com/273120/138014144-60909493-ce4c-4d9f-90f7-ae8713c6b6fa.png)

When we remove the report only mode in https://github.com/matomo-org/matomo/issues/17923 this could break the overlay feature.

Not really sure what the problem is there?

**Comment by justinvelluppillai** [comment]
That default-src CSP looks wrong, like it didn't apply the `allowEmbedPage` directives in `SecurityPolicy` class

**Comment by tsteur** [comment]
@justinvelluppillai doesn't look like this is called for the overlay feature maybe?
