### ISSUE TITLE
Use MaxScale for read-write separation

### ISSUE THREAD

**Issue by huye** [piwik/piwik#18207]
I use the MariaDB database and MaxScale 6.1.3 for read-write separation. However, matomo does not work properly, and SQL syntax errors will be reported. I don't know whether it's not supported or the maxscale setting problem. I hope to get help.

I have tried to use MariaDB directly without MaxScale.

Debian 11
Docker 20.10.5
MaxScale 6.1.3
MariaDB 10.5.10
PHP 8.0

**Comment by sgiehl** [comment]
Hi @huye 
Thanks for creating this issue. I'm not familiar with MaxScale, but maybe it limits the SQL syntax in any way so some of our queries don't work anymore.
Maybe you could provide some details about the syntax errors you recieves. Maybe that helps to identify the issue,

**Comment by tsteur** [comment]
@huye MaxScale (or similar) is not supported unfortunately. However, you can configure a reader in Matomo directly and then it should work. See https://matomo.org/faq/how-to-install/faq_35746/

**Comment by huye** [comment]
@tsteur I now bypass MaxScale (which is a gateway or middleware) and directly connect to MariaDB. This is not very friendly. MaxScale supports automatic switching of the primary server. Now, when the server fails, I can only switch manually. I guess it's probably because MaxScale doesn't support functions like load file, but I didn't track and debug Matomo.

**Comment by tsteur** [comment]
Maybe check if it can update the DNS automatically when it switches over then the problem would be solved. I don't know if it supports that.

**Comment by huye** [comment]
I encountered this problem when using matomo. If you want to know the situation, you can install and test this statistical program. If you don't want to deal with it, take it as if I didn't mention it. 

https://matomo.org/
