### ISSUE TITLE
Login SAML - Attribute Mapping Settings unable to work with attribute friendly name

### ISSUE THREAD

**Issue by Alice-Pa** [piwik/piwik#18209]
We have configured the SAML plugin to connect with a shibboleth IDP. 
It sends our matomo a "mail" attribute that we use for both Login (username) and email.
The issue is that SAML authentification doesn't work if configured with attribute friendly name "mail" but requires to specify the technical attribute OID "urn:oid:x.x.xxxx.xxxxxxxx.xxx.x.x"

**Comment by sgiehl** [comment]
Hi there, Thank you for creating the issue. To request support for a Premium Feature please contact shop(at)innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features

Looking forward to helping you there. Closing this issue now. Thanks.
