### ISSUE TITLE
Display friendly display name for authenticated user

### ISSUE THREAD

**Issue by Alice-Pa** [piwik/piwik#18210]
Once authenticated in Matomo, the web interface does not display the name of the authenticated user (usually available in the top right corner in most application). It would be nice to have it. 
We also authenticate against our corporate IDP with SAML Plugin, and it would be great to be able to retrieve the friendly display name from the SAML response attributes.

**Comment by Findus23** [comment]
As this is something only few people will probably need (but would be really nice for them) and this can be implemented in a few lines of code, this would be in my opinion the ideal concept for a new plugin.

**Comment by tsteur** [comment]
@Alice-Pa thanks for creating this issue. As our [SAML plugin](https://plugins.matomo.org/LoginSaml) is a premium feature it be great to contact our support about this at shop@innocraft.com  . Here we only manage issues about the free version of Matomo core. Sorry about this inconvenience. I'll close this issue for now.  @Findus23 I hope I didn't misunderstand this but it sounded SAML specific to me and it might needs to be implemented in the plugin directly.

Let me know if I misunderstood anything here and I'll be happy to reopen.
