### ISSUE TITLE
Fix annotations for "Behaviour > Performance" StackedBarEvolution charts

### ISSUE THREAD

**Issue by robles-design** [piwik/piwik#18231]
## Expected Behavior
Annotations should show up below Behaviour > Performance.

## Current Behavior
Annotations doesn't show up below Behaviour > Performance.

## Steps to Reproduce (for Bugs)
https://user-images.githubusercontent.com/25033650/139089875-6a513947-87d5-4c7a-ad69-c1d3c74caf64.mp4

## Context
I work with annotations to analyze websites changes to see if they have an impact or not.

## Your Environment
Matomo-Version: 4.5.0
MySQL-Version: 10.5.11-MariaDB-1:10.5.11+maria~focal-log
PHP-Version: 8.0.10

**Comment by bx80** [comment]
Hi @robles-design, thanks for raising this issue and taking the time to make a video, that's very helpful. I've managed to recreate the problem and it does seem to be a bug.

**Comment by sgiehl** [comment]
That's quite easy to explain. Annotations are currently hard coded only available for evolution charts, but the performance chart has another graph type. Should be quite simple to fix that. Will have a quick look...
