### ISSUE TITLE
Remove "refer us" feature

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18232]
In https://github.com/matomo-org/matomo/pull/17234 we added the "refer us" feature which shows a popup asking to share on twitter, facebook, linkedin.

We couldn't see too many shares so far now we would like to remove this feature again to have less popups.

**Comment by tsteur** [comment]
@peterhashair seems this one is maybe done and can be closed?

**Comment by peterhashair** [comment]
@tsteur yes can be closed.
