### ISSUE TITLE
unable to excute syncronous functions in matomo

### ISSUE THREAD

**Issue by mkassir95** [piwik/piwik#18248]
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by Findus23** [comment]
Hi,

I think you have to expand a lot more on what you mean by "synchronous functions".

https://github.com/matomo-org/developer-documentation/issues/575
