### ISSUE TITLE
Collect feedback about what features people are using?

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18251]
We are wanting to learn more about what features or services people are missing in Matomo so we can improve it further.

## How we ask for feedback

Therefore, we want to ask for feedback in the app like this:

![Screenshot 2021-10-27 at 7 56 01 PM](https://user-images.githubusercontent.com/273120/139606488-97f72d88-ea79-4100-b418-1a1eaf579df0.png)

* [x] Important to have the close button/icon visible clearly
* [x] It should basically look exactly like on our cloud (the above initial screen has too much of a padding-top/bottom for example):

![image](https://user-images.githubusercontent.com/273120/139606537-67e04690-2eb4-4ef2-aeb2-5b93cd297639.png)

## Questions to show

* [ ] The first question is selected randomly out of our pool of questions
* [x] We will rotate between below questions.  Meaning next time it shows again, we show a different question. 
* [x] Once all questions are shown, we start again with the first question.

### Questions

* What are your biggest problems or pain points with Matomo and why?
* What is the one thing you’d like to see improved in Matomo and why?
* What is the feature you are missing the most in Matomo and why?
* What is your main goal for using Matomo?
* What is your main concern about Matomo?

## When to show this

* [x] When the message is supposed to show, we show it again on every subsequent page view until they either clicked on close, or clicked on the button in the bar
  * [x] When someone closes it, we don’t show it for another 6 months. 
  * [ ] When someone clicks the feedback button, we don’t show it for another 6 months. 
     * (we could also change this to when user actually sent feedback in case they want to do it later)... or maybe if easy to do the popup could have a button "remind me later" and then we remind again in couple days -> let's maybe ignore it for now?
* [ ] We only show it on desktop, not on mobile/tablet because it might take too much space and close button might be hard to see/reach etc.
* [ ] We show it the first time 6 months after Matomo has been installed. This is important because we don't want to show it to all users at once to not get too much feedback at once, and because it means by then they have used Matomo for a while and know better what is possible and what is missing etc. 
  * [ ] Basically, on each day we show it to the people where it was installed 6 months ago. If someone installed it 7 months ago, then we don't want to show it. Otherwise if we rolled out this feature, then we would suddenly get feedback from all Matomo installations. Basically, we want to do something like `$daysSinceInstallation % 6 months == 0`. Problems: We don't have an install date I think, and what if they log in 6 months+3 days but not exactly 6 months ago to the day? We'd need to have some flexibility in there. Like we want to show it also to people that haven't logged in the last 1 week. If users only use it every few weeks that's fine then they might not see the popup. Likely they have little usage and requirements anyway. Maybe the next best thing is to check the first site creation date? (although when someone imports historical data then this may be changed). 
* [x] For now we only show it to super users, we might later expand to regular users depending on the amount of feedback we get

Also:
* [ ] We won't show this when WhiteLabel is installed (I believe this plugin might disable Feedback plugin anyway)
* [ ] To be defined: Maybe we also don't show it when there is any premium feature installed already?

## On button click to get actual feedback

We show our feedback popup 
![image](https://user-images.githubusercontent.com/273120/139607491-e3977b1d-e63f-4a97-8f93-cdb6bc8cf8b7.png)

* [x] The title of the popup is the same question we were showing in the UI initially
* [x] When it opens, the cursor should be already in the text field
* [x] We require at least 10 characters to be entered
* [x] We show a privacy policy with text eg `Your message and your email address will be sent to us by submitting this form. The information will be only used to improve our products and services. Your data will be processed by us, our hosting provider, and our support ticket provider. For more information have a look at Matomo's Privacy Policy.`  Link for privacy policy: https://matomo.org/privacy-policy/ 

## Confirmation message 

![image](https://user-images.githubusercontent.com/273120/139607590-cb6eec3c-f5b1-449e-8770-e1498d544423.png)

* [x] People might expect a response and send support questions. The idea was to show a message that we might reply if we need more information, to lower expectations of a reply. Note: Maybe at some point could also show a message that if they submitted a support question, to ask it in our forum instead and if they reported a bug, to create a github issue. We could set up a dedicated page for this and say something like `If your message was not feedback, please [read here]` (to be improved). 
* [x] The feedback is sent to us by email similar to the other feedback
* [x] The email includes the asked question, and the email of the user so we can follow up if needed

At a later stage we might ask a single select follow up question on the thank you confirmation message.

**Comment by peterhashair** [comment]
@tsteur just checking, should we use a cookie per browser, or database per user to reload the popup. I mean if someone finishes the feedback, should we record it into the browser cookie per browser or local database per user.

**Comment by tsteur** [comment]
@peterhashair we'll want to do this in the browser

**Comment by tsteur** [comment]
@peterhashair sorry I meant in the database. Similarly to how we've done this for review popup and refer popup.

**Comment by peterhashair** [comment]
@tsteur Just checking the logic here and prority. `Hide if the user answered question already.` >`Show if(currentUser) not seen last week` > `Hide if(currentUser>'six month old')`.

**Comment by heurteph-ei** [comment]
@tsteur , take also int account when Matomo cannot access the Internet (then the email could be sent though the email app of the user if any... Or else the feature desactivated...)
Also, how do you collect the sender email address? Indeed, the confirmation message says `We will be in touch in case...`

**Comment by tsteur** [comment]
@peterhashair I'm not quite understanding what you mean re that logic?

@heurteph-ei So far Internet vs email are two different things in Matomo. We're usually assuming that when internet is disabled, emails usually still work.

> Also, how do you collect the sender email address

We will include the email address of the currently logged in user (see the privacy notice below the textarea)

**Comment by tsteur** [comment]
@peterhashair did you mean to close this issue?

**Comment by peterhashair** [comment]
@tsteur definitely not.  Sorry, I click the wrong button. Just checking because it fires us an email, do we worry about spam. do we need to do a captcha

**Comment by sgiehl** [comment]
@peterhashair Some of the requirements are not yet fully met for the feature. Maybe you can create some additional pull requests for those:

- This feature is currently also shown for mobile. We should hide it for at least very small screens and maybe make the layout on smaller screens bit more responsive so it looks good. 
- The banner is also shown if WhiteLabel plugin is enabled. We used to use an event called `'Feedback.showReferBanner'` for that, but seems that have been removed in Matomo code. Maybe you could reuse that one, or introduce a new one and also create a PR in that plugin to ensure it's not displayed anymore.

The conditions when it should be displayed are actually not the same. Above it says:
> - [ ] We show it the first time 6 months after Matomo has been installed. This is important because we don't want to show it to all users at once to not get too much feedback at once, and because it means by then they have used Matomo for a while and know better what is possible and what is missing etc.
>   - [ ] Basically, on each day we show it to the people where it was installed 6 months ago. If someone installed it 7 months ago, then we don't want to show it. Otherwise if we rolled out this feature, then we would suddenly get feedback from all Matomo installations. Basically, we want to do something like $daysSinceInstallation % 6 months == 0. Problems: We don't have an install date I think, and what if they log in 6 months+3 days but not exactly 6 months ago to the day? We'd need to have some flexibility in there. Like we want to show it also to people that haven't logged in the last 1 week. If users only use it every few weeks that's fine then they might not see the popup. Likely they have little usage and requirements anyway. Maybe the next best thing is to check the first site creation date? (although when someone imports historical data then this may be changed).

But actually implemented we have:
The banner is shown if the current user has a creation date, that is more than six months in the past. 
If the creation date was in the last 6 months it will be shown 6 months after the creation date.
If there is not such an date we simply show it in 6 months.
Might be good enough, but it might still happen that a high number of users are seeing the banner directly after the update. Not sure if that should be changed/improved a bit further. ping @tsteur

**Comment by tsteur** [comment]
> Might be good enough, but it might still happen that a high number of users are seeing the banner directly after the update. Not sure if that should be changed/improved a bit further. ping @tsteur

We will definitely want to avoid that too many people see the banner at once. Maybe if we don't have a creation date or something then we simply pick a date from the last 6 months randomly or so? We need some solution that distributes this somewhat evenly so never too many people at once see it and submit the feedback.
