### ISSUE TITLE
Support for Global Privacy Control (GPC) and enabled by default

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#18264]
> Mozilla has become the latest browser to test the waters in incorporating the Global Privacy Control in Firefox this week, calling itself "the first major web browser" to do so. 
> The GPC -- required under the California Consumer Protection Act (CCPA) and Europe's Global Data Protection Regulation (GDPR) -- tells websites not to sell or share your personal data.  

from https://www.zdnet.com/article/mozilla-firefox-joins-browsers-implementing-global-privacy-control/

## Global Privacy Control (GPC) spec

The spec is available at https://globalprivacycontrol.github.io/gpc-spec/ and was proposed less than  a month ago.

Questions:

* Could we add support for Support for Global Privacy Control (GPC) in Matomo?
* And what would be the implications if we enabled it by default? (similarly to how DoNotTrack is enabled by default) For example how much of Firefox userbase would now be excluded?

We would want to update the guide at https://matomo.org/docs/privacy/, and add a new FAQ eg. `Does Matomo Analytics respect Global Privacy Control (GPC)?` .

**Comment by mattab** [comment]
The spec says:

> A do-not-sell-or-share interaction is an interaction with a website in which the user is requesting that their data not be sold to or shared with any party other than the one the user intends to interact with, except as permitted by law. 

So it looks like we don't want to "Not track" people when they only mean to indicate that their data is not be sold to or shared with any party other than the one the user intends to interact with.

So maybe this is a won'tfix?

**Comment by ronak-innocraft** [comment]
Thanks for creating this issue. As it has been almost 3 years since the last activity, and we believe it's likely not an issue anymore, we're closing it. If that's not the case, please feel free to either reopen this issue or open a new one.
