### ISSUE TITLE
Stray vendor files in File Integrity report

### ISSUE THREAD

**Issue by alimony** [piwik/piwik#18282]
I get stray files in the File Integrity report but that seems to have popped up as part of an upgrade or similar.

## Expected Behavior

No errors in integrity check, as I haven't modified any files.

## Current Behavior

I get three stray files.

## Possible Solution

Ignore these in the check, if they are now expected to pop up as part of other packages.

## Steps to Reproduce (for Bugs)

1. Upgrade to latest version of Matomo (4.5.0)

## Context

```
Files were found in your Matomo, but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/php-di/php-di/.gitstats.yml
File to delete: vendor/php-di/php-di/.phpstorm.meta.php
File to delete: vendor/twig/twig/.php_cs.dist
```

## Your Environment

* Matomo Version: 4.5.0
* PHP Version: 7.4.3
* Server Operating System: Ubuntu 20.04

**Comment by sgiehl** [comment]
Hi @alimony 
Thanks for your report. Those files were actually not part of the last release. It seems for some reason they might have been included in a former release and were not removed on update in your case.
We will improve our script to ensure they won't be included in future releases.
For your setup please simply remove the files manually. Those files won't be included in future releases.
