### ISSUE TITLE
[4.6.0-b2] Error: Call to undefined function Piwik\piwik_fix_lbrace() in DiagnosticResult.php

### ISSUE THREAD

**Issue by MichaIng** [piwik/piwik#18303]
## Expected Behavior
The diagnostic check when accessing admin settings does not fail.

## Current Behavior
The diagnostic check when accessing admin settings fails with this errro:
```
Uncaught exception: Error: Call to undefined function Piwik\piwik_fix_lbrace() in /var/www/matomo/plugins/Diagnostics/Diagnostic/DiagnosticResult.php:74
```
If you need the stack trace, I can add it.

## Possible Solution
- Related code: https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Diagnostics/Diagnostic/DiagnosticResult.php#L74
- Probably this function got removed or renamed with latest beta? Though it is here and namespace correct, also this script exists on my system: https://github.com/matomo-org/matomo/blob/4.x-dev/core/Twig.php#L43
- It got implemented here: #18171
- Not sure what's wrong with it. I cannot rule out that it is related our recent upgrade to PHP8.1.

## Steps to Reproduce (for Bugs)

1. Update to Matomo v4.6.0-b2
2. Access the admin settings

## Your Environment

* Matomo Version: 4.6.0-b2
* PHP Version: 8.1.0RC6
* Server Operating System: Debian Bookworm
* Additionally installed plugins:
```
API, Actions, Annotations, BulkTracking, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, DBStats, DarkTheme 1.1.7, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Goals, IPReports 4.1.1, ImageGraph, Insights, Installation, Intl, LanguagesManager, Live, LogViewer 4.0.1, Login, Marketplace, Monolog, Morpheus, PagePerformance, PrivacyManager, Proxy, Referrers, Resolution, SEO, SegmentEditor, SitesManager, TrackingSpamPrevention 4.1.0, Transitions, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable
```
* Browser: Opera 83
* Operating System: Windows 10

**Comment by sgiehl** [comment]
I'm actually not able to reproduce that with PHP 8.1-rc6. For me the diagnostics runs without problems 🤔

**Comment by MichaIng** [comment]
Hmm, I face regular segmentation faults of all php-fpm children after accessing that page now (the gear icon, initial page, segfauls temporarily solved by service restart) and an error loading the top right diagnostics, but indeed not the same error anymore. Not sure but there seems to be an issue on a different level which I need to identify first.

Btw, another minor one when accessing that page, from browser console:
```
[Report Only] Refused to load the image 'https://plugins.matomo.org/IP2Location/images/4.0.2/01_Settings.png?w=600' because it violates the following Content Security Policy directive: "img-src 'self' 'unsafe-inline' 'unsafe-eval' data:".
```
Since this does not match the webserver wide CSP we set, I guess it is set internally by Matomo and hence needs to have `https://plugins.matomo.org` added as image source?

**Comment by sgiehl** [comment]
@MichaIng thanks for the update. The CSP issue should already be fixed, but was not yet included in any beta I guess.

**Comment by MichaIng** [comment]
Great. Sorry for the spam, seems to be a system issue and not necessarily a bug in Matomo. I'll close this hence for now and try to further investigate first what causes this segfault loops. I observed it once already with PHP8.0, so maybe it's a specific PHP module (those get updates for both PHP versions) or another system library or so 🤔.

**Comment by bigahuna** [comment]
Hey all,

centos7, php 7.4.26, 10.0.38-MariaDB

I see the same Error after updating Matomo from 4.5.0 to 4.6.1. 

The Systemcheck in the Browser (/index.php?module=Installation&action=systemCheckPage) runs just fine and reports no errors. This error did not happen with Matomo 3 or 4.5, It startet after the Update to 4.6.1

If I run  `console diagnostics:run` I get the following Errors. Also This error shows up when accessing admin settings in the Browser.

`
ERROR [2021-12-06 11:14:01] 24912  Uncaught exception: Error: Call to undefined function Piwik\piwik_fix_lbrace() in /var/www/evim.de/typo3/public/analyse/plugins/Diagnostics/Diagnostic/DiagnosticResult.php:74
Stack trace:
#0 /var/www/evim.de/typo3/public/analyse/plugins/Diagnostics/Diagnostic/MatomoInformational.php(36): Piwik\Plugins\Diagnostics\Diagnostic\DiagnosticResult::informationalResult('Matomo Version', '4.6.1')
#1 /var/www/evim.de/typo3/public/analyse/plugins/Diagnostics/DiagnosticService.php(68): Piwik\Plugins\Diagnostics\Diagnostic\MatomoInformational->execute()
#2 /var/www/evim.de/typo3/public/analyse/plugins/Diagnostics/DiagnosticService.php(55): Piwik\Plugins\Diagnostics\DiagnosticService->run(Array)
#3 /var/www/evim.de/typo3/public/analyse/plugins/Diagnostics/Commands/Run.php(41): Piwik\Plugins\Diagnostics\DiagnosticService->runDiagnostics()
#4 /var/www/evim.de/typo3/public/analyse/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\Diagnostics\Commands\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/evim.de/typo3/public/analyse/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/evim.de/typo3/public/analyse/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\Diagnostics\Commands\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/evim.de/typo3/public/analyse/core/Console.php(130): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/evim.de/typo3/public/analyse/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#10 /var/www/evim.de/typo3/public/analyse/core/Console.php(131): Piwik\Access::doAsSuperUser(Object(Closure))
#11 /var/www/evim.de/typo3/public/analyse/core/Console.php(82): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/evim.de/typo3/public/analyse/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/evim.de/typo3/public/analyse/console(32): Symfony\Component\Console\Application->run()
#14 {main}
Uncaught exception in /var/www/evim.de/typo3/public/analyse/plugins/Diagnostics/Diagnostic/DiagnosticResult.php line 74:
Call to undefined function Piwik\piwik_fix_lbrace()
`
Regards
Michael
