### ISSUE TITLE
Fatal error Impossible to invoke a method (\"getRowsCount\") on a boolean variable

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18310]
Stacktrace:

> Error: {"message":"Impossible to invoke a method (\"getRowsCount\") on a boolean variable (\"\").","file":"\/plugins\/CoreVisualizations\/templates\/_dataTableViz_htmlTable.twig","line":15,"request_id":"2001f","backtrace":" on \/plugins\/CoreVisualizations\/templates\/_dataTableViz_htmlTable.twig(15)\n#0 \/tmp\/templates_c\/d0\/d013f74306a2a91dd5de5a93c762aadf1bccad0b7b40b2273259926c780a964d.php(63): twig_get_attribute(Object(Twig\\Environment), Object(Twig\\Source), false, 'getRowsCount', Array, 'method', false, false, false, 15)\n#1 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_462cb7f5bb23fb3aed8430e16a75c4a93ffff6bfe2250abcaa6ac46c2dce2c3c->doDisplay(Array, Array)\n#2 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#3 \/tmp\/templates_c\/d0\/d013f74306a2a91dd5de5a93c762aadf1bccad0b7b40b2273259926c780a964d.php(280): Twig\\Template->display(Array)\n#4 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_462cb7f5bb23fb3aed8430e16a75c4a93ffff6bfe2250abcaa6ac46c2dce2c3c->doDisplay(Array, Array)\n#5 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#6 \/tmp\/templates_c\/37\/3778e1f25244e9b13c79bb7f1f2ff8d782d90651202f396874512e174d3279b5.php(250): Twig\\Template->display(Array)\n#7 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_e135e321ed78391f54c5d30fa2ac2c94c51b0fe4a0efde66231a2aaf49de30e2->doDisplay(Array, Array)\n#8 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#9 \/vendor\/twig\/twig\/src\/Template.php(379): Twig\\Template->display(Array)\n#10 \/vendor\/twig\/twig\/src\/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)\n#11 \/vendor\/twig\/twig\/src\/Environment.php(277): Twig\\TemplateWrapper->render(Array)\n#12 \/core\/View.php(331): Twig\\Environment->render('@CoreHome\/_data...', Array)\n#13 \/core\/View.php(316): Piwik\\View->renderTwigTemplate()\n#14 \/core\/Plugin\/Visualization.php(269): Piwik\\View->render()\n#15 \/core\/Plugin\/Report.php(320): Piwik\\Plugin\\Visualization->render()\n#16 \/plugins\/CoreHome\/Controller.php(59): Piwik\\Plugin\\Report->render()\n#17 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\Actions\\Reports\\GetPageUrls))\n#18 \/core\/FrontController.php(619): call_user_func_array(Array, Array)\n#19 \/core\/FrontController.php(168): Piwik\\FrontController->doDispatch('Actions', 'getPageUrls', Array)\n#20 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#21 \/index.php(25): require_once('\/c...')\n#22 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(619): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(168): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(99): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(139): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(183): Piwik\\FrontController::(Object(Twig\\Error\\RuntimeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

Url:

> index.php?date=last30&viewDataTable=table&limit_increaser=0&limit_decreaser=5&keep_totals_row=0&module=Actions&action=getPageUrls&idSite=2&period=range&random=5556&search_recursive=1&min_growth_percent=1&order_by=absolute&compared_to_x_periods_ago=1&filter_sort_column=nb_visits&filter_sort_order=desc&enable_filter_excludelowpop=0&filter_column_recursive=label&filter_pattern_recursive=checkout&filter_offset=0&filter_limit=10&flat=0&totals=1

>  GET: {"date":"last30","viewDataTable":"table","limit_increaser":"0","limit_decreaser":"5","keep_totals_row":"0","module":"Actions","action":"getPageUrls","idSite":"2","period":"range","random":"5556","search_recursive":"1","min_growth_percent":"1","order_by":"absolute","compared_to_x_periods_ago":"1","filter_sort_column":"nb_visits","filter_sort_order":"desc","enable_filter_excludelowpop":"0","filter_column_recursive":"label","filter_pattern_recursive":"checkout","filter_offset":"0","filter_limit":"10","flat":"0","totals":"1"}

Referrer: index.php?module=CoreHome&action=index&idSite=2&period=range&date=last30&updated=3

**Comment by tsteur** [comment]
This is still happening on cloud, putting the logs below

> Error: {"message":"Impossible to invoke a method (\"getRowsCount\") on a boolean variable (\"\").","file":"\/plugins\/CoreVisualizations\/templates\/_dataTableViz_htmlTable.twig","line":15,"request_id":"4dd86","backtrace":" on \/plugins\/CoreVisualizations\/templates\/_dataTableViz_htmlTable.twig(15)\n#0 \/tmp\/templates_c\/6f\/6f241a490ac652d4b42bf92c97e90321d84fa233c1948dea81273435f9e9aa5c.php(63): twig_get_attribute(Object(Twig\\Environment), Object(Twig\\Source), false, 'getRowsCount', Array, 'method', false, false, false, 15)\n#1 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_4341b48c9271336301ba7706721407dc1f6549c82f1be03029779ceee27ab5c5->doDisplay(Array, Array)\n#2 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#3 \/tmp\/templates_c\/6f\/6f241a490ac652d4b42bf92c97e90321d84fa233c1948dea81273435f9e9aa5c.php(280): Twig\\Template->display(Array)\n#4 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_4341b48c9271336301ba7706721407dc1f6549c82f1be03029779ceee27ab5c5->doDisplay(Array, Array)\n#5 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#6 \/tmp\/templates_c\/13\/138cc304f243beb2b6432540ddad34b1b0a6a1d3aa55b403d336a01886a6da93.php(258): Twig\\Template->display(Array)\n#7 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_0607358a34c7247508d333ced45bca0f502c2ab4a463b439cf63f9640d1770a4->doDisplay(Array, Array)\n#8 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#9 \/vendor\/twig\/twig\/src\/Template.php(379): Twig\\Template->display(Array)\n#10 \/vendor\/twig\/twig\/src\/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)\n#11 \/vendor\/twig\/twig\/src\/Environment.php(277): Twig\\TemplateWrapper->render(Array)\n#12 \/core\/View.php(331): Twig\\Environment->render('@CoreHome\/_data...', Array)\n#13 \/core\/View.php(316): Piwik\\View->renderTwigTemplate()\n#14 \/core\/Plugin\/Visualization.php(270): Piwik\\View->render()\n#15 \/core\/Plugin\/Report.php(320): Piwik\\Plugin\\Visualization->render()\n#16 \/plugins\/CoreHome\/Controller.php(60): Piwik\\Plugin\\Report->render()\n#17 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\Actions\\Reports\\GetPageUrls))\n#18 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#19 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Actions', 'getPageUrls', Array)\n#20 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#21 \/index.php(25): require_once('\/c...')\n#22 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(184): Piwik\\FrontController::(Object(Twig\\Error\\RuntimeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: index.php?date=yesterday&viewDataTable=table&module=Actions&format=html&action=getPageUrls&idSite=3&period=day&random=2794&search_recursive=1&keep_totals_row=1&filter_sort_column=nb_hits&filter_sort_order=desc&enable_filter_excludelowpop=0&filter_column_recursive=label&filter_pattern_recursive=blog&filter_offset=0&filter_limit=25&flat=0&totals=1&include_aggregate_rows=0

> Referrer: /index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday

**Comment by sgiehl** [comment]
Had a quick look. Wasn't able to reproduce that locally. But think I found a simply improvement that should fix that.
