### ISSUE TITLE
BotTracker plugin page: user agent external website link is dead

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#18339]
## Documentation page to be updated:
https://plugins.matomo.org/BotTracker

## What's wrong
A link is dead
> ## How it works
> [...] You can add/delete/modify the keywords in the administration-menu. There are webpages that list the user-agents of known spiders and webcrawlers (e.g. ~~http://www.useragentstring.com/pages/Crawlerlist/~~). The most common bots are already in the default list of the plugin.

To be replaced by: http://www.useragentstring.com/pages/useragentstring.php

**Comment by sgiehl** [comment]
Hi @heurteph-ei 
This plugin is not developed by the Matomo team. Please try reporting the issue in the plugin repository:
https://github.com/Thomas--F/BotTracker/issues
