### ISSUE TITLE
WARNING Undefined index: host - Matomo 4.5.0 

### ISSUE THREAD

**Issue by lrrrs** [piwik/piwik#18338]
## Expected Behavior

I get no warning 😆

## Current Behavior

`WARNING [2021-11-16 07:30:20] 29776  ...core/Http.php(229): Notice - Undefined index: host - Matomo 4.5.0`

## Steps to Reproduce (for Bugs)

This warning only occures sometimes when running `console core:archive` directly after this log: `Will invalidate archived reports for yesterday in site ID = 1's timezone (2021-11-16 00:00:00).`

It seems like this only occurs, when the script is run via a crontab. When I run it in the terminal, I never noticed the issue. Maybe this could be a clue to identify the root cause. I'll try to dig deeper…

## Your Environment

* Matomo Version: 4.5.0
* PHP Version: 7.4
* Server Operating System: Debian
* Additionally installed plugins: -

**Comment by sgiehl** [comment]
Thanks for the report. I'll prepare a fix for that.

**Comment by lrrrs** [comment]
Many many thanks 🙏
