### ISSUE TITLE
"How do I track visits on my intranet?" How-to page: IntranetGeoIP plugin link is dead

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#18347]
## Documentation page to be updated:
https://matomo.org/faq/how-to/faq_19/#faq_19

## What's wrong
A link is dead

> ## How do I get accurate geolocation for people viewing my Intranet site?
> [...] When many people viewing your website share the same IP address (for example because they’re connecting via a VPN or from within your intranet network), then to still track geolocation for these we recommend using this third party plugin from the Marketplace ***IntranetGeoIP plugin*** (*https://plugins.matomo.org/IntranetGeoIP* - dead link).

Probably to be replaced by: https://plugins.matomo.org/CampusGeoIP

**Comment by sgiehl** [comment]
Hi @heurteph-ei. Thanks for pointing that out. Seems the plugin was only available for Matomo 3 and not updated for Matomo 4 compatibility. Will update the FAQ.
