### ISSUE TITLE
Call to a member function getPluginName() on bool 

### ISSUE THREAD

**Issue by zthomas1** [piwik/piwik#18370]
Theme.php line 39 

calls getThemeEnabled

If plugins are not loaded yet this will always return false.  

self::DEFAULT_THEME is never set.

This is occurring on a clean install where a superuser is being created via API methods in a php script.

**Comment by sgiehl** [comment]
@zthomas1 I wonder how this can happen. When executing an API methods, all plugins should always be loaded. Did you install Matomo the "normal" way, or are you using some custom script for that?

**Comment by zthomas1** [comment]
Thank you for the response, I am using a custom script, this is likely on my end at this point, I'll report back if not.

**Comment by Chrissitopher** [comment]
@zthomas1 : I am using [pikiwintegration](https://github.com/kaystrobach/TYPO3.piwikintegration) and I am seeing the same issue.

Have you been able to debug or even to solve this issue?
