### ISSUE TITLE
Bahrain Map

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#18459]
Hi team,

Bahrain (map) isn't showing up in Matomo maps:

![image](https://user-images.githubusercontent.com/89768140/144952867-4b927eb2-5fa7-4775-81eb-4276cc98da89.png)

**Comment by sgiehl** [comment]
There are several very small countries missing on our current map. See e.g. https://github.com/matomo-org/matomo/issues/321
This will hopefully be handled at some point with #11929

**Comment by sgiehl** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/11929
