### ISSUE TITLE
HOW DO I ADD MORE THAN THE DEFAULT 5 CUSTOM DIMENSIONS?

### ISSUE THREAD

**Issue by mkassir95** [piwik/piwik#18489]
I am applying this tutorial to add more than 5 custom dimensions
I am using matomo version 4.6.2
https://matomo.org/faq/how-to/faq_21121/

but I no thing is happening after executing the command

![image](https://user-images.githubusercontent.com/72728047/145641689-890f3442-2f39-41cc-805a-6ddd41c44659.png)

**Comment by bx80** [comment]
Hi @mkassir95, thanks for contacting us.

On Windows the console command needs to be run via the php interpreter.. You should be able to run the command to increase custom dimensions like this:

`php c:\wamp64\www\matomo\console customdimensions:add-custom-dimension --scope=action --count=5`

**Comment by mkassir95** [comment]
Thank you man! 
This works

**Comment by bx80** [comment]
You're welcome :smiley:
