### ISSUE TITLE
Time zone may not be correct

### ISSUE THREAD

**Issue by mkassir95** [piwik/piwik#18484]
I am using matomo latest version 4.6.2 .
I feel that that the time zone is not accurate , it is behind the real time zone by two hours (please look at my PC clock)
![image](https://user-images.githubusercontent.com/72728047/145565040-93e829f8-43ac-4a8f-962b-db99f3e75f78.png)

**Comment by sgiehl** [comment]
Hi @mkassir95. As the text says, the displayed time is UTC. So guess you are having a timezone with UTC+2?

**Comment by mkassir95** [comment]
yes lebanon  timezone is UTC+2 
![image](https://user-images.githubusercontent.com/72728047/145575584-a42ae0a8-607a-443c-815f-93f058cd0fbc.png)
How can I adjust this ?

**Comment by sgiehl** [comment]
You do not need to adjust anything. If you select your timezone in the drop down, this timezone will be used for newly created websites. The time displayed in the description is for informal purpose only and will always display the UTC time.

**Comment by mkassir95** [comment]
but the server time saved in the database is UTC and not the select zone time , in the dashboard the time is correct UTC+2 but in the database the time is UTC

**Comment by mkassir95** [comment]
![image](https://user-images.githubusercontent.com/72728047/145577323-58fd38c6-d608-440a-9f2c-9e6535974016.png)
![image](https://user-images.githubusercontent.com/72728047/145577499-13e13832-00df-4982-828b-21a6aba40246.png)

**Comment by mkassir95** [comment]
The database is  UTC while the dashboard is UTC+2

**Comment by sgiehl** [comment]
Yes. The database is always using UTC. The dashboard should use the timezone that is configured for the site.

**Comment by mkassir95** [comment]
Then , is there a solution for this in order to read the real time form the database without workaround?

**Comment by sgiehl** [comment]
I think I don't understand your problem. If you want your data being processed in UTC, simply select UTC as timezone for the website.

**Comment by mkassir95** [comment]
I need to generate custom reports and I do not want use the reports generated by the dashboard . So , I will fetch the data from the database to generate my custom reports and I will not use the dashboard . For this I will be facing a problem because the UTC is used as a timezone in the database even though I selected my local timezone

**Comment by sgiehl** [comment]
UTC is used in that database for a very good reason and this won't be changed. If you want to generate reports using database data directly, you need to adjust the returned datetime values on your own. All reports returned by the UI or the API should do that automatically for you.
