### ISSUE TITLE
No entry or class found for 'view.clearcompiledtemplates.enable'

### ISSUE THREAD

**Issue by liping521** [piwik/piwik#18485]
When I upgrade to 4.6.2 from 4.5.0
![image](https://user-images.githubusercontent.com/92291622/145571130-9d17709a-a604-440a-8f04-9a73a3ac7617.png)

**Comment by liping521** [comment]
After add config  to  /config/global.php  is resolved 
'path.tmp.templates' => DI\string('{path.tmp}/templates_c'),
 'view.clearcompiledtemplates.enable' => true,
![image](https://user-images.githubusercontent.com/92291622/145573969-1be03433-e587-4c45-8505-1b1036436209.png)

**Comment by sgiehl** [comment]
This should have happened automatically on update. Was the file `config/global.php` maybe write protected and thus couldn't be updated by the updater?

**Comment by mardy** [comment]
Happened today to me as well. Permissions on the `config/global.php` are the same as all other files installed with Matomo, and I never touched them.

I added the lines showed by @liping521 above, and they fixed the issue for me too.
