### ISSUE TITLE
difference between _id  and uid 

### ISSUE THREAD

**Issue by mkassir95** [piwik/piwik#18495]
In the API reference documentation there are two terms : _id  & uid .
What is the use case of each of them and what the difference between them

**Comment by sgiehl** [comment]
Hi @mkassir95. Would you mind linking the according documentation pages?

**Comment by mkassir95** [comment]
Hi , yes sure
https://developer.matomo.org/api-reference/tracking-api 

uid is in Optional User Info Section  and _id is in Recommended  paramters  Section

**Comment by sgiehl** [comment]
Setting the `uid` should normally overwrite the `_id`, based on your config setting of `enable_userid_overwrites_visitorid`. While the `_id` is hexadecimal the `uid` can be filled with more custom content (like a username or alias).
If you need more help with that, maybe try asking your questions on our forum (https://forum.matomo.org). We are actually only handling bug reports and feature requests here.
