### ISSUE TITLE
Unable to access Matomo Report due to permission issue

### ISSUE THREAD

**Issue by rhpdc** [piwik/piwik#18490]
Hello, 
I am an admin for www.biokineticshealthsystem.com , and now I cannot read the Matomo reports anymore.
When trying to click on REPORTING, the message reads:

**Forbidden
You don't have permission to access this resource.**

Thanks for letting me know what to do from here!
RP

[NSBK syst report .pdf](https://github.com/matomo-org/matomo/files/7696589/NSBK.syst.report.pdf)

**Comment by justinvelluppillai** [comment]
Hi @rhpdc could you please ask questions in our forums: https://forum.matomo.org/

Maybe there is also already this question solved there, eg https://forum.matomo.org/t/403-forbidden-error-general-query/33359/2. I will close this for now.
