### ISSUE TITLE
Field conditions eg in Measurable Settings API not working anymore

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18539]
Seems to work in 4.6.2 but not on 4.x-dev or on demo2.

eg go to https://demo2.matomo.org/index.php?module=SitesManager&action=index&idSite=13&period=day&date=yesterday and edit a site/measurable.

Then click on `Disable visits log & visitor profile`. When enabled, it should hide the second setting which it no longer does. 

![image](https://user-images.githubusercontent.com/273120/147301875-1cead1e4-dd22-4800-9b8d-9bde98a27d97.png)

Noticed this in some other plugin that it seems to no longer work. Maybe a regression in Vue ? 

ping @diosmosis 

putting it for now as a regression in 4.7 but happy can move it out if it's not a regression.

**Comment by diosmosis** [comment]
It's probably a regression, will look into it.
