### ISSUE TITLE
Field width 3356450096 is too long in core/DataTable.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18544]
Error: {"type":1,"message":"Field width 3356450096 is too long","file":"\/var\/www\/html\/core\/DataTable.php","line":1586,"request_id":"2b6ce","backtrace":" on \/var\/www\/html\/core\/DataTable.php(1586)\n","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\MyPlugin\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(619): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(168): Piwik\\FrontController->doDispatch('MyPlugin', 'safemode', Array)\n#3 \/core\/FrontController.php(99): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(274): Piwik\\FrontController::(Array)\n#5 [internal function]: Piwik\\FrontController::triggerSafeModeWhenError()\n#6 {main}"}

URL: https://example.matomo.org/index.php?date=previous24&period=month&expanded=1&filter_limit=-1&force_api_session=1&format=CSV&idSite=4&language=fr&method=API.getProcessedReport&apiModule=Referrers&apiAction=getReferrerType&module=API&period=month&segment=&translateColumnNames=1&convertToUnicode=0&token_auth=....

No referrer

GET: {"date":"previous24","period":"month","expanded":"1","filter_limit":"-1","force_api_session":"1","format":"CSV","idSite":"4","language":"fr","method":"API.getProcessedReport","apiModule":"Referrers","apiAction":"getReferrerType","module":"API","segment":"","translateColumnNames":"1","convertToUnicode":"0","token_auth":"....","format_metrics":"bc"}

POST: {"token_auth":"....","date":"previous24","period":"month","expanded":"1","filter_limit":"-1","force_api_session":"1","format":"CSV","idSite":"4","language":"fr","method":"API.getProcessedReport","apiModule":"Referrers","apiAction":"getReferrerType","module":"API","segment":"","translateColumnNames":"1","convertToUnicode":"0","format_metrics":"bc"}

**Comment by sgiehl** [comment]
@tsteur I think that error actually only occurs as `API.getProcessedReport` can't be exported as a CSV. Normally I guess this part should throw an exception as the data structure can't be converted:

https://github.com/matomo-org/matomo/blob/70b004c968a1850b65c71156b465d189f4692a49/core/DataTable.php#L1585

But it tries to add the full array content to the exception message. Locally that ends up for me in a memory exhausted error. Maybe the message above would occur if I would have a more memory available.

We maybe should change the error messages in that case, so it no longer tries to add the full data content.

**Comment by tsteur** [comment]
Truncating the exported array makes sense and could be a good quick fix 👍  We could limit it to the first 1M characters or so

**Comment by sgiehl** [comment]
Actually I'm not sure if it's worth to include it at all. The variable is an array, so doing a  var_export on it will double the amount of used memory for it. So we would need to truncate the array before dumping it, but hard to say how big the dump will be without looking through the array content and its structure.

**Comment by tsteur** [comment]
Not sure if I understand correctly. I thought in this case it's not a memory issue but maybe a limitation in `sprintf`? 
If there's a memory issue or so, we could otherwise always extract the first say 1K entries and then do the var_export?

**Comment by sgiehl** [comment]
I think the problem is, that the array is too big in some cases. But we can't know which part of the array is how big. So using the first 1000 entries in the array might still be too big, depending on the complexity of the array.

**Comment by tsteur** [comment]
We had the same problem again

> Error: {"type":1,"message":"Field width 2699393714 is too long","file":"\/core\/DataTable.php","line":1587,

Request:
> GET: {"expanded":"1","filter_limit":"100","format":"CSV","flat":"1","date":"2022-01-01,yesterday","format_metrics":"1","idGoal":"","idSite":"29","language":"fr","method":"API.getProcessedReport","apiModule":"Referrers","apiAction":"getReferrerType","module":"API","period":"day","segment":"","showAllGoalSpecificMetrics":"0","token_auth":"XYZANONYMIZED","translateColumnNames":"1","convertToUnicode":"0"}

> POST: {"token_auth":"XYZANONYMIZED","expanded":"1","filter_limit":"100","format":"CSV","flat":"1","date":"2022-01-01,yesterday","format_metrics":"1","idGoal":"","idSite":"29","language":"fr","method":"API.getProcessedReport","apiModule":"Referrers","apiAction":"getReferrerType","module":"API","period":"day","segment":"","showAllGoalSpecificMetrics":"0","translateColumnNames":"1","convertToUnicode":"0"}

**Comment by sgiehl** [comment]
I'll prepare a PR to adjust the exception messages. I guess there is no much value in printing the whole content in the exception anyway.
