### ISSUE TITLE
"Update automatically": No SSL connection possible

### ISSUE THREAD

**Issue by monkeyjunglejuice** [piwik/piwik#18546]
When trying to update, this error message appears:
"Downloading the latest Matomo version over secure HTTPS connection did not succeed, because of the following error:
curl_exec: SSL certificate problem: certificate has expired. Hostname requested was: builds.matomo.org"

There's only the chance to update via unencrypted HTTP.

## Expected Behavior
![screenshot](https://user-images.githubusercontent.com/64652122/147437169-2ec03da1-a213-4644-9f94-2b5241adaf9d.png)

Automatic update via HTTPS should work.

## Current Behavior
Error message appears, automatic update via HTTPS not possible

## Possible Solution
If the error message really points out the actual problem, then update the certificates of builds.matomo.org (but they seem valid).

## Steps to Reproduce (for Bugs)
1. https://matomoinstallation.domain/index.php?module=CoreUpdater&action=newVersionAvailable
2. Click button "UPDATE AUTOMATICALLY"
3. Update error

## Your Environment
* Matomo Version: 4.4.1
* Webserver: NGINX 
* PHP Version: 8.0 with OPCache
* Server Operating System: Debian
* Additionally installed plugins: None
* Browser: Firefox 95.0.1
* Operating System: GNU/Linux

**Comment by justinvelluppillai** [comment]
Thanks for the issue @monkeyjunglejuice - I think this was resolved in Matomo 4.5. I will close this for now. Please refer to #18089 for more info.

**Comment by digitalextremist** [comment]
Seeing this again at the update to `4.10.1` unfortunately @justinvelluppillai

**Comment by justinvelluppillai** [comment]
@digitalextremist what version did you upgrade from there?

edit: it looks like you came from 4.4.1, which means the error is expected but was resolved in `4.5` after which you shouldn't see this.

**Comment by digitalextremist** [comment]
@justinvelluppillai I was coming from the prior revision, `4.10.0` and had remained current up to there.

When I selected `Continue Automatically` using `HTTPS` another time or two, it finally did work.
