### ISSUE TITLE
Fix SQL syntax error due to incorrect parameter

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18550]
Maybe an empty array was passed to `deleteInvalidations` method in which case it would need to return directly again?

> Error: {"message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1","file":"libs\/Zend\/Db\/Statement\/Pdo.php","line":236,"backtrace":" on libs\/Zend\/Db\/Statement\/Pdo.php(236)\n#0 libs\/Zend\/Db\/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)\n#1 libs\/Zend\/Db\/Adapter\/Abstract.php(479): Zend_Db_Statement->execute(Array)\n#2 libs\/Zend\/Db\/Adapter\/Pdo\/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `ar...', Array)\n#3 core\/Db\/Adapter\/Pdo\/Mysql.php(310): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `ar...', Array)\n#4 core\/Db.php(280): Piwik\\Db\\Adapter\\Pdo\\Mysql->query('DELETE FROM `ar...', Array)\n#5 core\/DataAccess\/Model.php(801): Piwik\\Db::query('DELETE FROM `ar...')\n#6 core\/CronArchive\/QueueConsumer.php(260): Piwik\\DataAccess\\Model->deleteInvalidations(Array)\n#7 core\/CronArchive.php(375): Piwik\\CronArchive\\QueueConsumer->getNextArchivesToProcess()\n#8 core\/CronArchive.php(263): Piwik\\CronArchive->run()\n#9 core\/Access.php(661): Piwik\\CronArchive->Piwik\\{closure}()\n#10 core\/CronArchive.php(269): Piwik\\Access::doAsSuperUser(Object(Closure))\n#11 plugins\/CoreConsole\/Commands\/CoreArchiver.php(32): Piwik\\CronArchive->main()\n#12 vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\CoreConsole\\Commands\\CoreArchiver->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\CoreConsole\\Commands\\CoreArchiver), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 core\/Console.php(130): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 core\/Access.php(670): Piwik\\Console->Piwik\\{closure}()\n#18 core\/Console.php(131): Piwik\\Access::doAsSuperUser(Object(Closure))\n#19 core\/Console.php(82): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 console(32)

**Comment by sgiehl** [comment]
Just cam across this issue and had a quick look at the code. I guess the problem might be here:
https://github.com/matomo-org/matomo/blob/c11469e4199405628e97650914f0cdbdea94dac7/core/CronArchive/QueueConsumer.php#L267-L277

`$this->model->deleteInvalidations()` expects to receive the full array and not the ids only. Will set up a quick PR to fix that.
