### ISSUE TITLE
Latest version of Matomo not available on Installatron

### ISSUE THREAD

**Issue by CalumChilds** [piwik/piwik#18565]
The latest version of Matomo is not available through Installatron. The last version available on Installatron is 4.4.1.

## Expected Behavior

That the software should be automatically updated.
## Current Behavior

The software has not been updated for two major versions.
## Steps to Reproduce (for Bugs)

N/A

## Your Environment

* Matomo Version: 4.4.1
* PHP Version: 7.3
* Server Operating System: Linux
* Additionally installed plugins:

* Browser: N/A
* Operating System: N/A

**Comment by Findus23** [comment]
I don't think anyone apart from the Installatron team can change this fact as this integration is neither maintained nor supported by the Matomo team.

**Comment by tsteur** [comment]
@Wingo5315 have you reached out to Installatron already about this? If not, that be great to do

**Comment by Wingo5315** [comment]
Just submitted a ticket. https://installatron.com/tickets?ticket=15015336&email=mail@calumchilds.com

**Comment by Findus23** [comment]
@Wingo5315 I deleted your message as it seems like that link would allow anyone to send a message to support with your E-Mail address

**Comment by tsteur** [comment]
Thanks. I'll close this issue again as it's not really related to us. Feel free to comment again if there's any way we can help.
