### ISSUE TITLE
[VUE]Date selector doesn't change on report page.

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#18578]
## Expected Behavior

I guess there is a regression there. Under admin->Personal->Email Reports. if you change the date selector the UI doesn't change, but the param changes. 

## Current Behavior

![image](https://user-images.githubusercontent.com/3783072/148324153-a7f79ecb-dcdb-45f1-b694-8dab1bf4d4e3.png)
See the screenshot, the date selector is 2021-01-04, but the URL param is 2021-01-05

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
The problem actually seems to be, that the admin interface still works without a url hash, but changing the date in the selector appends/updates the date param in the url hash and not in the normal url parameters. 
I Matomo 4.5 the url parameter was updated instead. So this is a regression indeed.
