### ISSUE TITLE
User Opt Out not correct

### ISSUE THREAD

**Issue by marcelcz1** [piwik/piwik#18595]
Hi,
I wanted to implement the opt out button for matomo to our privacy page, but the text of the pre-built html code is not correct.
It marks that the visit is not tracked on matomo at the moment and by clicking on the checkbox it will activate the tracking. Normally the text should be the opposite (tracking is active, checkbox to opt out). 
How can I change this?

html code: 
<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="https://iternity.com/analytics/index.php?module=CoreAdminHome&action=optOut&language=de&backgroundColor=&fontColor=&fontSize=&fontFamily="
        ></iframe>

preview:
Deaktivierung durchgeführt! Ihre Besuche auf dieser Webseite werden von der Webanalyse nicht mehr erfasst. Bitte beachten Sie, dass auch der Matomo-Deaktivierungs-Cookie dieser Webseite gelöscht wird, wenn Sie die in Ihrem Browser abgelegten Cookies entfernen. Außerdem müssen Sie, wenn Sie einen anderen Computer oder einen anderen Webbrowser verwenden, die Deaktivierungsprozedur nochmals absolvieren.
 Ihr Besuch dieser Webseite wird aktuell von der Matomo Webanalyse nicht erfasst. Diese Checkbox aktivieren für Opt-In.

**Comment by bx80** [comment]
Hi @marcelcz1, thanks for contacting us. The opt out text will automatically change to opt in if Matomo detects that the user is not currently being tracked. Are you testing using a browser that is configured with the 'Do not track' preference? It's possible that this would cause tracking to be disabled and the opt in text would then be shown.

**Comment by marcelcz1** [comment]
Hi @bx80 , thank you for the explanation. I've implemented the code again and tested it with several people and it works fine, so it was the "do not track" preference that caused this problem.
