### ISSUE TITLE
Add URL campaign parameters to in-app search and help links

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18598]
We use these campaign parameters as we're partially using them already in other cases (we could change if it doesn't make sense)

```
mtm_campaign=App_Help&mtm_source=Matomo_App&mtm_medium=$DEPENDS_ON_CONTEXT
```

When someone searches for something in the quick search, or on the help page, and we then open "matomo.org" to view the search results, add campaign parameters so we know how many people used this feature.

Also add campaign parameters to the help links in report documentation (not sure there are any URLs)

![image](https://user-images.githubusercontent.com/273120/148838497-fb651ada-3e64-442d-8d01-f1696151e7d1.png)

and category help 
![image](https://user-images.githubusercontent.com/273120/148838328-7f33aad0-0eb1-489c-9057-c142470e16ca.png)

help links in the help page

![image](https://user-images.githubusercontent.com/273120/148838565-1cc8c63c-08aa-4a6e-aa57-d97bd02a15c2.png)

**Comment by peterhashair** [comment]
@tsteur Should I follow this rules. Or `mtm_campaign=App_Help&mtm_source=Matomo_App&mtm_medium=cpc|email 
` is enough.
![image](https://user-images.githubusercontent.com/3783072/148884117-460255c7-6f49-474d-98f7-52c5da3edbd0.png)

**Comment by tsteur** [comment]
@peterhashair I'm not sure what rules you mean?
