### ISSUE TITLE
Error 400  Bad Request

### ISSUE THREAD

**Issue by thomasbnt** [piwik/piwik#18650]
I have restored my database since I migrated everything. Everything is good, I have all my history on the dashboard. But it doesn't record new visitors. This marks a mistake for me **400 Bad Request**.

![](https://i.thomasbnt.dev/i/rw4wv.png)

## Expected Behavior
Push stats and get 200 OK. And get recent statistics.

## Current Behavior
- At the first time, GET the matomo.js file with status 200
- The second request in POST with the URL options like id, referals, got status 400. 

## Steps to Reproduce (for Bugs)

1. I test that to one of my website : https://mrrobot.app
2. Open F12 and go to network
3. Reload the page
4. See requests and errors from analytics.thomasbnt.dev

## Context

I would not like to have errors and statistics displayed and recorded in the database. 
## Your Environment

* Version de Matomo: 4.6.2
* Version de MySQL: 8.0.27
* Version de PHP: 7.4.25
* Server Operating System: Debian 11
* Additionally installed plugins:
* [PluginsInstalled]
PluginsInstalled[] = "Diagnostics"
PluginsInstalled[] = "Login"
PluginsInstalled[] = "CoreAdminHome"
PluginsInstalled[] = "UsersManager"
PluginsInstalled[] = "SitesManager"
PluginsInstalled[] = "Installation"
PluginsInstalled[] = "Monolog"
PluginsInstalled[] = "Intl"
PluginsInstalled[] = "CoreVue"
PluginsInstalled[] = "CorePluginsAdmin"
PluginsInstalled[] = "CoreHome"
PluginsInstalled[] = "WebsiteMeasurable"
PluginsInstalled[] = "IntranetMeasurable"
PluginsInstalled[] = "CoreVisualizations"
PluginsInstalled[] = "Proxy"
PluginsInstalled[] = "API"
PluginsInstalled[] = "Widgetize"
PluginsInstalled[] = "Transitions"
PluginsInstalled[] = "LanguagesManager"
PluginsInstalled[] = "Actions"
PluginsInstalled[] = "Dashboard"
PluginsInstalled[] = "MultiSites"
PluginsInstalled[] = "Referrers"
PluginsInstalled[] = "UserLanguage"
PluginsInstalled[] = "DevicesDetection"
PluginsInstalled[] = "Goals"
PluginsInstalled[] = "Ecommerce"
PluginsInstalled[] = "SEO"
PluginsInstalled[] = "Events"
PluginsInstalled[] = "UserCountry"
PluginsInstalled[] = "GeoIp2"
PluginsInstalled[] = "VisitsSummary"
PluginsInstalled[] = "VisitFrequency"
PluginsInstalled[] = "VisitTime"
PluginsInstalled[] = "VisitorInterest"
PluginsInstalled[] = "RssWidget"
PluginsInstalled[] = "Feedback"
PluginsInstalled[] = "TwoFactorAuth"
PluginsInstalled[] = "CoreUpdater"
PluginsInstalled[] = "CoreConsole"
PluginsInstalled[] = "ScheduledReports"
PluginsInstalled[] = "UserCountryMap"
PluginsInstalled[] = "Live"
PluginsInstalled[] = "PrivacyManager"
PluginsInstalled[] = "ImageGraph"
PluginsInstalled[] = "Annotations"
PluginsInstalled[] = "MobileMessaging"
PluginsInstalled[] = "Overlay"
PluginsInstalled[] = "SegmentEditor"
PluginsInstalled[] = "Insights"
PluginsInstalled[] = "Morpheus"
PluginsInstalled[] = "Contents"
PluginsInstalled[] = "BulkTracking"
PluginsInstalled[] = "Resolution"
PluginsInstalled[] = "DevicePlugins"
PluginsInstalled[] = "Heartbeat"
PluginsInstalled[] = "Marketplace"
PluginsInstalled[] = "ProfessionalServices"
PluginsInstalled[] = "UserId"
PluginsInstalled[] = "CustomJsTracker"
PluginsInstalled[] = "Tour"
PluginsInstalled[] = "PagePerformance"
PluginsInstalled[] = "CustomDimensions"

* Browser: Chrome v97
* Operating System: Windows 10.

**Comment by sgiehl** [comment]
Hi @thomasbnt. Thanks for creating the issue. Unfortunately it's hard to identify the root cause. 
Are you maybe able to see the failed tracking requests in Admin > Diagnostic > Tracking Failures? 
If not you maybe need to turn the debugging of tracking requests in order to see some more details what causes the request not to be recorded.

**Comment by thomasbnt** [comment]
Hello @sgiehl, thanks for your reply.

In Admin > Diagnostic > Tracking Failures, I've got no errors and no messages :(

How I can activate Debug mode and see log?

**Comment by tsteur** [comment]
@thomasbnt any chance you can enable the Tracker Debug mode see https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker ? This would tell you in the output of the request what is happening. You would only want to enable it for a short time as anyone sending a tracking request will see the response of the request.

**Comment by thomasbnt** [comment]
> @thomasbnt any chance you can enable the Tracker Debug mode see [developer.matomo.org/api-reference/tracking-api#debugging-the-tracker](https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker) ? This would tell you in the output of the request what is happening. You would only want to enable it for a short time as anyone sending a tracking request will see the response of the request.

Hello, no really more information. And I don't know if it's related, but I get a 500 error when I want to install a plugin. 

So I'm going to reinstall Matomo entirely, it will take me less time, it's annoying, but I can't see anything else. And change MySQL by MariaDB.

**Comment by thomasbnt** [comment]
Hmmmmmmmm okay, maybe I founded the "bug". I didn't why it happened.

I uninstalled **mysql-server** and taken **mariadb**, reconfigure user and database and use a new Matomo configuration. All works!

**Comment by arashatt** [comment]
I am also facing the same issue after migrating the website to another server!

<img width="1915" height="988" alt="Image" src="https://github.com/user-attachments/assets/c4bd80e2-947f-4cca-a4f1-f68a4347f9d9" />
