### ISSUE TITLE
Användare som försvann

### ISSUE THREAD

**Issue by helenala1** [piwik/piwik#18658]
Hej! Jag skapade nyss en användare som inte syns i systemet. Försöker jag lägga till denna på nytt får jag till svar att den redan finns. 

*translated with Google Translate:*
> Hey! I just created a user that is not visible in the system. If I try to add this again, I get the answer that it already exists.

**Comment by sgiehl** [comment]
Hi @helenala1 
Thanks for creating the issue. For future issues please write you messages in English. I have added a translation to your descriptions, so other don't need to do that.

Did you perform the actions with a super user account? If you used an account with lower permissions, it might be possible that you can't see the user if the new user doesn't have access to one of your sites.
See https://matomo.org/docs/manage-users/ for more details.
