### ISSUE TITLE
Admin home issues requests and then cancels them again

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18662]
This might be a regression in Matomo 4.7. At least I can't reproduce it on the cloud where an older version of Matomo runs. I noticed this because sometimes it would then show me an alert notification in the admin home page but not always.

![image](https://user-images.githubusercontent.com/273120/150264071-e6fd98d8-0aa0-4af6-919e-c0b09e924795.png)

Only managed to see this error when the developer tools are closed. It happens after clicking on the Admin cog icon 
![image](https://user-images.githubusercontent.com/273120/150264240-aa3303d1-7264-409e-b47e-2934728c0237.png)

Noticed this eg on https://demo.matomo.org/index.php?module=CoreAdminHome&action=home&idSite=1&period=day&date=yesterday

See network tab in browser developer tools:

![image](https://user-images.githubusercontent.com/273120/150263949-25abf767-4b21-4c7d-bc4b-57983a6bee4f.png)

**Comment by justinvelluppillai** [comment]
@diosmosis @sgiehl is this issue resolved or still needing to be looked at?

**Comment by diosmosis** [comment]
Should have been fixed by https://github.com/matomo-org/matomo/pull/18672
