### ISSUE TITLE
[Documentation] Default value of "recorder-max-payload-size" incorrect

### ISSUE THREAD

**Issue by DevDavido** [piwik/piwik#18678]
Actual value of parameter `--recorder-max-payload-size` for `import_logs.py` is [200](https://github.com/matomo-org/matomo-log-analytics/blob/4.x-dev/import_logs.py#L757) and not [300](https://matomo.org/docs/log-analytics-tool-how-to/#:~:text=speed.%20By%20default%2C-,300%20pageviews,-\(or%20log%20lines) as stated in the documentation.

**Comment by bx80** [comment]
Thanks for spotting thing @DevDavido :+1:, I've updated the documentation with the correct default parameter value.
