### ISSUE TITLE
PHP Deprecaded message after upgrade PHP to Version 8.1.2

### ISSUE THREAD

**Issue by emkcloud** [piwik/piwik#18694]
PHP Deprecaded message after upgrade PHP to Version 8.1.2

* Matomo Version: 4.6
* PHP Version: 8.1.2
* Browser: Chrome 97.0.4692.71
* Operating System: Ubuntu 20.04 LTS

![image](https://user-images.githubusercontent.com/5731295/151422193-5298fef9-7386-4029-a509-170e6e89a5e4.png)

**Comment by sgiehl** [comment]
This should be already fixed in Matomo 4.7.

**Comment by sgiehl** [comment]
was fixed in #18384
