### ISSUE TITLE
AH01630: client denied by server configuration: E:/Intranet/matomo/config/config.ini.php error after upgrading matomo from v3 to v4

### ISSUE THREAD

**Issue by suganja** [piwik/piwik#18693]
After upgrading to 4.6.2, when I am logged in in Matomo, there are some issues with loading. I think, it's related to this issue, but couldn't solve the problem: https://github.com/matomo-org/matomo/issues/17589

![grafik](https://user-images.githubusercontent.com/10153210/151360237-18b2dfad-414a-4408-80d5-d0098c13e5f2.png)

I checked the error.log in Apache:

[Thu Jan 27 12:11:45.153081 2022] [php7:notice] [pid 18868:tid 1824] [client 10.5.20.62:53506] Error in Matomo: Failed to write cache file &quot;E:\\Intranet\\matomo/tmp/templates_c/8c/8c69945382970ba9358b29855818d71a8eb8d53c39c9c89615548c1812552769.php&quot;., referer: http://statistik-intern/index.php?module=CoreHome&action=index&idSite=1&period=day&date=today
[Thu Jan 27 12:12:03.781484 2022] [authz_core:error] [pid 18868:tid 1844] [client ::1:54408] AH01630: client denied by server configuration: E:/Intranet/matomo/config/config.ini.php
[Thu Jan 27 12:12:03.785486 2022] [authz_core:error] [pid 18868:tid 1844] [client ::1:54409] AH01630: client denied by server configuration: E:/Intranet/matomo/tmp/cache/tracker/matomocache_general.php
[Thu Jan 27 12:12:03.788484 2022] [authz_core:error] [pid 18868:tid 1844] [client ::1:54410] AH01630: client denied by server configuration: E:/Intranet/matomo/tmp/
[Thu Jan 27 12:12:03.791485 2022] [authz_core:error] [pid 18868:tid 1844] [client ::1:54411] AH01630: client denied by server configuration: E:/Intranet/matomo/tmp/empty
[Thu Jan 27 12:12:03.794539 2022] [authz_core:error] [pid 18868:tid 1844] [client ::1:54412] AH01630: client denied by server configuration: E:/Intranet/matomo/lang/en.json
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.

* Matomo Version: 4.6.2
* PHP Version: 7.2
* Server Operating System: Apache24
* Additionally installed plugins:

* Browser: Firefox, Chrome
* Operating System: Windows

Hope to get a solution, thanks in Advance for replying.

**Comment by Findus23** [comment]
Hi,

>  [Thu Jan 27 12:12:03.781484 2022] [authz_core:error] [pid 18868:tid 1844] [client ::1:54408] AH01630: client denied by server configuration: E:/Intranet/matomo/config/config.ini.php

is not the issue, but showing that your server is set up as it should be (blocking these requests).

I'm assuming the actual issue is:
> Failed to write cache file "E:\Intranet\matomo/tmp/templates_c/8c/8c69945382970ba9358b29855818d71a8eb8d53c39c9c89615548c1812552769.php

This issue tracker is intended for bug reports about specific reproducable bugs. If you want general help with your Matomo setup please ask on the forum (forum.matomo.org) the next time.

**Comment by suganja** [comment]
Hi Findus23,
thank you for your reply. I am sorry, if this does no belong here, next time I will ask in the forum. 
>
> is not the issue, but showing that your server is set up as it should be (blocking these requests).
>

The directory for matomo in Apache is setup like this:

![grafik](https://user-images.githubusercontent.com/10153210/151501884-a1f6648b-0e5b-43f5-9935-b5f2742e6644.png)

So I am not sure, where the problem is. I will ask in the forum.
