### ISSUE TITLE
Label shortened when opening multiple subtables

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18699]
Not sure if we already have an issue.
* To reproduce, go to https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=2022-01-27&segment=&category=General_Actions&subcategory=Events_Events
* Click on `Event Names`
* First the table will look like this 
![image](https://user-images.githubusercontent.com/273120/151489480-374096ae-0cb8-48e9-b8ca-cbc50fa7e4c3.png)

* when clicking on a row with a little bit longer title like `added - Diving Boots` and then row `Diving the Ribbon Reefs on Australia's Great Barrier Reef`, then the rows gets truncated and barely any text is readable 
![image](https://user-images.githubusercontent.com/273120/151489654-9eb20792-4d77-48bb-8cb5-240c7627556e.png)
* The more subtables are open, the less space is available 
![image](https://user-images.githubusercontent.com/273120/151489691-39f4762c-063c-4811-9f16-291b0e103f57.png)

**Comment by peterhashair** [comment]
also got another interface bug here, I think 
![image](https://user-images.githubusercontent.com/3783072/152245426-65a8f737-4ffb-48f2-8a11-333b59615637.png)
