### ISSUE TITLE
Fixes problem where dashboards can't be copied to users in certain circumstances

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#18692]
Refs DEV-2411
Not sure exactly under what circumstances this bug occurs, but in some cases its not possible to copy a dashboard to a different user. 

For example we had a case where an `Admin` user was not able to copy a dashboard to a specific `View` user. They were able to copy to **some** View users and other Admin users, but several View users were not showing on the list when trying to copy.
Other Admin users were also not able to copy to that specific View users until that View user was made an Admin user.

Thomas mentioned that this might be something that only happens under certain circumstances depending on what users exist:
![image](https://user-images.githubusercontent.com/20905821/151284875-20f79c00-20b8-433f-aea0-91e84469e7fd.png)

**Comment by peterhashair** [comment]
Just trying to reproduce this one, the only case I found. When your site Selector is Site 2. And Permission as listed below, this will appear. @Starker3 @tsteur  is that sound about the right reproduction? 

Site 1: 
 - Admin:
   User A
 - No Access:
   User B


Site 2 
  - Admin: 
    User B 
 - View:
    User A

**Comment by Starker3** [comment]
@peterhashair That might be how to reproduce it, if you want I can test it and see if I get the same results with such a setup?

**Comment by peterhashair** [comment]
@Starker3 that would be great.

**Comment by justinvelluppillai** [comment]
Hey @Starker3 did you get a chance to have a look here?

**Comment by justinvelluppillai** [comment]
Also @peterhashair is this fixed in #18796 ?

**Comment by Starker3** [comment]
@justinvelluppillai @peterhashair The setup that Peter gave for reproduction doesn't work for me to reproduce this.
I had the users configured as follows:
Site 1:
    Admin: User A
    No Access: User B

Site 2
    Admin: User B
    View: User A

For Site 2 both User A and User B were able to see each other in the list when copying dashboards. The Super Users were not visible in that list, but I'm not sure if that is intentional or not?

**Comment by sgiehl** [comment]
@Starker3 Do you remember if the users that weren't shown might have had `write` access?
Looking at the code it seems we check if a user has `admin` or `view` access. But users with `write` access might be ignored.

**Comment by sgiehl** [comment]
@Starker3 Are you sure the user had view access? I was able to reproduce it with a user having write permission, which then wasn't visible for an admin. The PR would fix this.

**Comment by Starker3** [comment]
@sgiehl I don't remember the specifics for the permissions level of the users when I encountered this error.
I can test it again though and see if I can reproduce it. I'll get back to you once I've tried that.

**Comment by sgiehl** [comment]
@Starker3 if you are able to reproduce that with vier permission, please reopen the issue. For write permission this should be fixed with 4.11. then.
