### ISSUE TITLE
Update orange brand color less variable in morpheus theme

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18709]
If I see this right then [@color-orange-brand: #ff9600;](https://github.com/matomo-org/matomo/blob/4.7.0-rc2/plugins/Morpheus/stylesheets/base/colors.less#L32) isn't used anywhere.

Yet at the same time we're using `#f57c00` quite often for variables. In https://github.com/matomo-org/tag-manager/pull/416/files?short_path=2b826b2#diff-a3310714e534480dda01c12cc1fdd9062b60925c446ff3fad5e51b7bec4c9fa0R3 `orange` was used and I will be suggesting to use `#f57c00`.

Generally be great though to maybe define `@color-orange-brand: #f57c00;` so we can use `@color-orange-brand` maybe instead of `#f57c00`

**Comment by AltamashShaikh** [comment]
Also it will be great if we can add the same in Morpheus
