### ISSUE TITLE
Wrong rocket icon used in no data page

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18700]
Issue was created in https://github.com/matomo-org/matomo/issues/18458 to change the header and use the rocket icon 
![image](https://user-images.githubusercontent.com/273120/151490006-5faacf77-aabe-483b-b556-3d13c6b11a41.png)

But the rocket icon looks like this:

![image](https://user-images.githubusercontent.com/273120/151489943-99a54084-27cd-43d9-9359-9845a6ce71f7.png)

Is it possible to use the actual rocket emoji 🚀 maybe or is there an issue with this?

**Comment by sgiehl** [comment]
We are currently using an icon in the matomo font. Using an emoji should work as well, but it would be displayed differently on every operating system depending on the fonts. See e.g. https://emojipedia.org/rocket/

**Comment by tsteur** [comment]
That be fine if it's displayed slightly differently 👍
