### ISSUE TITLE
Fixed error when closing a notification

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18714]
Open Matomo,

Execute this code in browser console:

```js
 var UI = require('piwik/UI');
var       notification =  new UI.Notification();
        notification.show('wwe', {context: 'error', id: 'test'});
```

Then close the notification. You will see such an error
![image](https://user-images.githubusercontent.com/273120/151916169-92e1c361-a34a-4154-ab70-6098ceffa031.png)
![image](https://user-images.githubusercontent.com/273120/151916186-84c1ce40-5ae6-4b8e-8b13-2f5daebe3cdd.png)

**Comment by peterhashair** [comment]
It seems like the  `token` param is not posted with the request.
