### ISSUE TITLE
Big issue while updating Matomo to 4.7

### ISSUE THREAD

**Issue by matmicro** [piwik/piwik#18722]
I tried to upgrade Matomo online.
This broke my install.

Error :
`Erreur critique pendant le processus de mise à jour :
/matomo/core/Updates/4.7.0-b2.php: Error trying to execute the migration 'ALTER TABLE `matomo_changes` ADD UNIQUE KEY unique_plugin_version_title (`plugin_name`, `version`, `title`);'. The error was: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

How to recover from this now ?

**Comment by Globulopolis** [comment]
Upgrade to MySql 5.7+
Or roll back changes from backup.

**Comment by Findus23** [comment]
I think this is the same issue as https://github.com/matomo-org/matomo/issues/18721 so to avoid splitting the discussion to much, I will close this in favour of https://github.com/matomo-org/matomo/issues/18721.
