### ISSUE TITLE
Restrict plugin name to 60 characters

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18727]
Follow up from https://github.com/matomo-org/matomo/pull/18723/files#r797936437

We have been using 40 characters in some columns, in some others 60 for `plugin_name`.

We should adjust `isValidPluginName` method to check the length in the regex and if not valid, throw an exception? It may be painful for some people to rename the plugin but at least on Marketplace the length has been already enforced.

The Marketplace itself enforces a length of 40 characters. Happy to increase this to 60 characters if better. 

We want to make sure that

* Marketplace and Matomo itself validate plugin name
* All DB columns use same length

**Comment by jane-twizel** [comment]
Let's increase this to 60 everywhere so it is consistent and this also means we won't have to address any names that are 40+

**Comment by sgiehl** [comment]
Note: Once this has been changed, we also need to update the marketplace, as well as prepare a change for the documentation here: https://developer.matomo.org/guides/distributing-your-plugin#pluginjson-file

**Comment by sgiehl** [comment]
@tsteur could you adjust the marketplace to be able to handle plugins with a length of 60 chars? Seems I don't have access to the repo anymore.

**Comment by tsteur** [comment]
@sgiehl I'll check this and also check the access as you should have access

**Comment by tsteur** [comment]
@tsteur this is done. And you now also have access again

**Comment by sgiehl** [comment]
Awesome. Thanks. Then all parts of this issue should be solved 🎉
