### ISSUE TITLE
setCustomRequestProcessing does not get"Page Performance" parameters passed

### ISSUE THREAD

**Issue by McSodbrenner** [piwik/piwik#18736]
## Current Behavior
I rewrite the GET parameters of the tracking request via setCustomRequestProcessing(). However, I noticed that the page performance parameters (https://developer.matomo.org/api-reference/tracking-api#optional-page-performancehttpsmatomoorgfaqhow-tohow-do-i-see-page-performance-reports-info) are not included there. They are added to the parameter string at a later time.

## Expected Behavior
The description on https://developer.matomo.org/api-reference/tracking-javascript for setCustomRequestProcessing() I understand so that the function is called directly before sending the request. Therefore, I expect all parameters to be included in it.

## Your Environment
 * Matomo-Version: 4.7.1
 * PHP-Version: 7.2.23
 * Browser: Chrome 97

**Comment by sgiehl** [comment]
@McSodbrenner The method `configCustomRequestContentProcessing` is called last when generating the request. 
But the page performance parameters might not yet be available when the first tracking request is fired. If that is the case the parameters will automatically be included in the next request (on the same page). If you want to have all parameters in one request you might need to wait until the page load event is finished.
