### ISSUE TITLE
Marketplace Reviews no longer shown

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18740]
follow up from https://github.com/matomo-org/matomo/pull/18215/files

<img width="938" alt="image" src="https://user-images.githubusercontent.com/273120/152466506-b274613f-e369-4227-8940-19f2038eab76.png">

It's not allowing `shop.matomo.org` to be opened in an iframe.

To reproduce go to Marketplace, then click on a premium feature, then click on `Reviews` tab

**Comment by sgiehl** [comment]
@tsteur According to the browsers message the problem actually is, that `shop.matomo.org` only allows to be framed by `plugins.matomo.org` by sending the csp header: `frame-ancestors https://plugins.matomo.org;`. I guess we would actually need to allow any source, as it might be opened by any matomo instance.

In addition it might also be needed to add `frame-src: *.matomo.org` within Matomo, but we can check that once the issue above is solved.

**Comment by tsteur** [comment]
👍  thanks for this. created an internal issue
