### ISSUE TITLE
Map of Romania is missing a county (Tulcea)

### ISSUE THREAD

**Issue by petru** [piwik/piwik#18752]
## Expected Behavior
The Southeastern part of the country should have two counties: Constanța (which is present) and Tulcea, which is missing.
## Current Behavior
The entire Southeastern part of the country is occupied by Constanța county.

## Possible Solution
Map update

## Steps to Reproduce (for Bugs)
1. Check the map of Romania in the reports.

## Context
Inaccurate stats.

## Your Environment
* Matomo Version: 4.6.0
* PHP Version: 7.4
* Server Operating System: Ubuntu 20.04 LTS
* Browser: Firefox
* Operating System: Windows 10

**Comment by sgiehl** [comment]
Hi @petru. Our maps are unfortunately quite outdated. We will at some point work on new maps in #11929

**Comment by sgiehl** [comment]
Closing this one for now, as we will work on it as part of #11929
