### ISSUE TITLE
Show the selected conversion rate on Goals->Overview evolution graph

### ISSUE THREAD

**Issue by weixuezhang** [piwik/piwik#18766]
Goals->Overview, selecting any goal's conversion rate, on the top evolution graph always shows zero.

We can reproduce this issue on https://demo.matomo.cloud/.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by bx80** [comment]
Hi @weixuezhang, thanks for reporting this. It looks like the top evolution graph on the goals overview page doesn't load the goal conversion or conversion rate when clicking on a specific goal's details. Instead the overall period values are still shown (in my test these were not zero but still the wrong figures)

**Comment by peterhashair** [comment]
when I was reviewing this issue, I realize, that after you refresh the page, the conversion rate showing correctly, but when you untick and tick the conversion box, it won't work. I guess a simple approach is to refresh the page after tick, but that won't be the perfect solution, still diving deep to see which JS cause the problem.

**Comment by sgiehl** [comment]
@peterhashair Did you try to analyze the requests that are sent to render the chart. I would assume that they differ when switching the metric and loading the chart already containing the metric. Knowing the difference should help to find the place where the request isn't build correctly.
