### ISSUE TITLE
Spammers feature not up to date in Release 4.7.1

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#18768]
A user writes:
_It seems your matomo-org/referrer-spam-list is not updated in the latest Matomo version 4.7.1. I compared some latest additions (like #1289 and #1309) to this file with the file in our Matomo installation and these are missing.
I ran 'composer require matomo/referrer-spam-blacklist'. The content of file equals the content in our install, but this file has as date: 2020-08-10!_

**Comment by sgiehl** [comment]
The file should be automatically updated when running scheduled tasks. But we should maybe change our composer requirement to the main branch of the repo or regularly tag versions there
