### ISSUE TITLE
Check folder & permission before downloading a GeoIP database

### ISSUE THREAD

**Issue by abbradar** [piwik/piwik#18785]
When downloading free DBIP database this error is shown if `tmp/latest` subdirectory does not exist:

```
WARNING: /core/Http.php(962): Warning - fopen(/var/lib/matomo/tmp/latest/DBIP-City.mmdb.gz.download): Failed to open stream: No such file or directory - Matomo 4.7.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: GeoIp2, Action: downloadFreeDBIPLiteDB, In CLI mode: false)
```

## Expected Behavior

Directory is created and file is downloaded.

## Current Behavior

Error message is shown.

## Possible Solution

Add `mkdir` call.

## Steps to Reproduce (for Bugs)

1. `rm -rf ./tmp/latest`, `rm -rf ./misc/DBIP-City.mmdb`;
2. Go to `/index.php?module=UserCountry&action=adminIndex&idSite=1&period=day&date=yesterday`;
3. Press "Get started..." to download free DBIP database.

## Context

Stops user from downloading GeoIP database from the admin UI.

## Your Environment

* Matomo Version: 4.7.1
* PHP Version: 8.0.13
* Server Operating System: NixOS 21.09
* Additionally installed plugins: -

**Comment by sgiehl** [comment]
Hi @abbradar 
Thanks for creating that issue. I was able to reproduce and will check if I can quickly provide a fix for it.

**Comment by abbradar** [comment]
Thanks!
