### ISSUE TITLE
Fatal error: urldecode(): Argument #1 ($string) must be of type string, array given in Date.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18795]
Not sure if this was maybe fixed by https://github.com/matomo-org/matomo/issues/18639

Happens in PHP 8

> Error: {"message":"urldecode(): Argument #1 ($string) must be of type string, array given","file":"\/core\/Date.php","line":138,"request_id":"9f07b","backtrace":" on \/core\/Date.php(138)\n#0 \/core\/Date.php(138): urldecode(Array)\n#1 \/core\/Period.php(121): Piwik\\Date::factory(Array)\n#2 \/core\/Plugin\/Controller.php(644): Piwik\\Period::checkDateFormat(Array)\n#3 \/core\/Plugin\/Controller.php(616): Piwik\\Plugin\\Controller->setGeneralVariablesViewAs(Object(Piwik\\View), 'basic')\n#4 \/plugins\/CoreHome\/Controller.php(180): Piwik\\Plugin\\Controller->setGeneralVariablesView(Object(Piwik\\View))\n#5 \/plugins\/CoreHome\/Controller.php(214): Piwik\\Plugins\\CoreHome\\Controller->getDefaultIndexView()\n#6 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->index()\n#7 \/core\/FrontController.php(623):

URL: https://demo.matomo.cloud/index.php?action=index&date%5B0%5D=%3D2and+3+in+&date%5B1%5D=3%27%22%5C%28&idSite=1&module=CoreHome&period=day

GET: {"action":"index","date":["=2and 3 in ","3'\"\\("],"idSite":"1","module":"CoreHome","period":"day"}

**Comment by sgiehl** [comment]
This one now throws as `The parameter 'date' doesn't have a correct type, and a default value wasn't provided.` exception. So should already be fixed with https://github.com/matomo-org/matomo/issues/18639
