### ISSUE TITLE
Inline Help - show report generation date on "Overview" reports with Evolution Graphs

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#18806]
In #18689 It was reported that the "Report Freshness" was not showing correctly which was fixed with #18498 
However, I noticed that on the "Overview" reports (The ones that contain the evolution graphs) don't show this date at all:
![image](https://user-images.githubusercontent.com/20905821/154383426-d29b0d04-e0b5-45d7-8ba8-09fa808ff363.png)
![image](https://user-images.githubusercontent.com/20905821/154383512-8e946121-3ef9-4637-8eaa-7621ec58ab39.png)

Is it possible for this to be shown on these reports, or is this data not stored for the evolution graphs?

**Comment by peterhashair** [comment]
@Starker3 thanks for finding that, there is definitely a bug there.

**Comment by peterhashair** [comment]
Notes: Under here.  https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=General_Actions&subcategory=General_Pages


When the report is shown as `Report generated 3 hours 4 min ago`  It won't show. See screenshots. 

![image](https://user-images.githubusercontent.com/3783072/154586675-c60bcfce-c3a1-47fa-841d-8675c7072606.png)
