### ISSUE TITLE
options request will also be recorded

### ISSUE THREAD

**Issue by 5idu** [piwik/piwik#18812]
## Expected Behavior

`options request` should not recorded!

## Current Behavior

`options request` will also be recorded

## Possible Solution

The server should filter out the `options request` and not participate in the record.

## Steps to Reproduce (for Bugs)

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/26264096/154448428-95a0193d-38f1-45ce-97cc-9450ecbf77dd.png">

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/26264096/154448601-904d838d-efe6-4a2b-baa7-28469395a17d.png">

## Your Environment

* Matomo Version: 4.7.1
* MySQL version: 10.6.5-MariaDB-1:10.6.5+maria~focal
* PHP Version: 8.0.15
* Server Operating System: centos7
* Additionally installed plugins:

* Browser: chrome98
* Operating System: macos 12.1

**Comment by 5idu** [comment]
@tsteur Hi, are you sure this is a bug? and will be fixed in the next version?

**Comment by tsteur** [comment]
@5idu I haven't looked into this yet but put it for now into Matomo 5 to consider changing this there. This release could be 6-12  months away as we don't have specific plans for a Matomo 5 release yet. We probably wouldn't want to change anything there earlier just in case it would cause any kind of regressions where people rely on this working for some reason.

**Comment by 5idu** [comment]
@tsteur Thanks Reply. looking forward to your verification result.
Now my solution is to intercept the `options request` on `nginx`, and then the statistical results are normal.

**Comment by tsteur** [comment]
@5idu do you know what issues these OPTIONS requests in the first place?

**Comment by 5idu** [comment]
@tsteur since cross-domain, browser client send the `options request`, this is fine.
However, after the `options request` is sent to the `matomo server`, `matomo` will still process the data passed by the options request, resulting in repeated statistics.

**Comment by tsteur** [comment]
Thanks for this, that's really helpful. I will move this in the 4.9 milestone so we look into this earlier. If someone in the team could reproduce this that be great.

**Comment by peterhashair** [comment]
Haven't reproduced this locally, but this could be caused by CORS preflight, I guess we could filter those request types, stop them for the double record.
