### ISSUE TITLE
Load tracking site from Iframe

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#18815]
So when you have Matomo tracking set in `a.com`, then use `a.com` as an iframe in `b.com`, it causes js errors around cookie can't be set across the domain,  this case is rare. 

But I guess user could check if `a.com` is load as iframe, then disable matomo cookies maybe? 
```js
function checkIsInIframe () {
    try {
        return window.self !== window.top;
    } catch (e) {
     _paq.push(['disableCookies']);
    }
}

```

**Comment by tsteur** [comment]
@peterhashair I'm not really sure what you mean here? Does maybe https://matomo.org/faq/how-to/how-do-i-track-a-website-within-an-iframe/ help?

**Comment by peterhashair** [comment]
@tsteur eg: this site. https://www.worxogo.com/  has load a [iframe](https://www.cuspera.com/wyz?mode=leadQual&page=worxogo&gaCat=VerifyRightFit&gaLabel=worxogo&product=CFProdCode-16753&ryze_mode=true&showIntent=true&productName=worxogo&categoryName=Sales%20Coaching&categoryPermalink=sales-coaching&origin=https://www.worxogo.com/). 
iframe has the `matomo.js` tracking code. 

It returns js errors on  https://www.worxogo.com/.   JS console.

**Comment by tsteur** [comment]
@peterhashair did you check out the FAQ and whether the site is setting it?

**Comment by peterhashair** [comment]
@tsteur will do.
