### ISSUE TITLE
Fix cookies with session lifetime

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#18819]
The language change option for the anonymous user doesn't seem to be working at the moment (Tested in 4.6.1 and 4.7.1)

It shows the drop down menu and you can select a different language, but it just kicks it back to English every time.
![image](https://user-images.githubusercontent.com/20905821/154609241-e4892784-eee4-4edf-ac78-980550580f93.png)

This happens on any instance that has Anonymous user access enabled including demo.matomo.cloud and demo2.matomo.org

**Comment by sgiehl** [comment]
This one is a regression from #18179, as the session language cookie is always set with an expire of `01-Jan-1970 00:00:00 UTC`

**Comment by Findus23** [comment]
Guess I should have checked the issues first as I noticed that my plugin (https://plugins.matomo.org/LanguageToogle) was broken and I rediscovered that issue. (In the plugin I set the users language with `LanguagesManager::setLanguageForSession($lang);` for the session if they use the buttons to quickly change it)

And indeed with #18820 everything works again as it should, thanks for that.

**Comment by Findus23** [comment]
As this breaks the plugin complete and I assume it will be a while until 3.8.0 is released, I published a new version of the plugin which as a workaround sets the language in the DB (which also works as long as the language is not set in the session):
https://github.com/Findus23/plugin-LanguageToogle/compare/0.3.3...0.3.5
