### ISSUE TITLE
TSV and CSV report can not be send nor download on wordpress multisite

### ISSUE THREAD

**Issue by fmh31200** [piwik/piwik#18814]
MS Edge : whereas PDF or HTML reports can be downloaded, CSV and TSV start downloading, but an error message appears "Network error".
None of them are received when "sent by email"

Chrome : reports of all formats can be downloaded, but like Edge, none of them are received when "sent by email"

**Comment by peterhashair** [comment]
@fmh31200 I tested on MS Edge, it seems working fine for me, is there any change, a WIFI or network connection drop during the process?

**Comment by fmh31200** [comment]
Thx for your help. no connection problem during the process. 
Here's a screencast of downloads of PDF and CSV : https://watch.screencastify.com/v/v6kkOrrQEShxfgqE06rm

**Comment by peterhashair** [comment]
@fmh31200, thx for the screencast, will do more investgation, come back to you ASAP

**Comment by michalkleiner** [comment]
Hi @fmh31200, the video is no longer available. Can you please confirm this is still an issue for you on Matomo 4.15 or 4.16? Thank you.

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. If someone still experiences this problem feel free to create a new issue.
