### ISSUE TITLE
Fix possible dashboard warning

### ISSUE THREAD

**Issue by mkassir95** [piwik/piwik#18829]
Hello
I am using matomo 4.7.1 , it is working fine and tracking the events but I am getting this warning sometimes
This is the request I am sending through postman:
http://localhost/matomo/piwik.php?idsite=22&rec=1&e_c=inbox&e_a=archiveMessage&uid=961000&dimension1=1&dimension2=1&dimension3=1

![image](https://user-images.githubusercontent.com/72728047/154919134-17e43740-c0dd-48f4-9c67-c2dc707f3de9.png)

**Comment by sgiehl** [comment]
@mkassir95 I guess I found the issue. It might occur while archiving if you tracked a custom dimension for an action without an url. created a PR to fix that.

**Comment by mkassir95** [comment]
Thank you
