### ISSUE TITLE
Map about Taiwan in China

### ISSUE THREAD

**Issue by nickcdon** [piwik/piwik#18828]
Taiwan should be a part of China

**Comment by justinvelluppillai** [comment]
Thanks for the comment. We have an issue to update the map so I will close this as duplicate for now.

**Comment by RYUDEN** [comment]
> Taiwan should be a part of China

支持你，居然还有两个狗给你点down。
这个项目好多年了 还没把台湾认为是一个国家

**Comment by RYUDEN** [comment]
> Thanks for the comment. We have an issue to update the map so I will close this as duplicate for now.

立刻马上修改，台湾是中国的一部分！
