### ISSUE TITLE
Unable to update Matomo using the web UI (4.2.6 > 4.7.1)

### ISSUE THREAD

**Issue by rusty1281** [piwik/piwik#18826]
## Expected Behavior
To be able to update using the web UI

## Current Behavior
Up until version 4.2.6, the official docker image was working fine. I would get the update notifications just fine. Now, on version 4.2.6 I am unable to see new updates.

## Steps to Reproduce (for Bugs)
Going to settings > check for updates returns that I am on the last version (4.6.2). It doesn't detect new versions.

## Context
<img width="222" alt="Screenshot 2022-02-20 at 11 12 16" src="https://user-images.githubusercontent.com/5110408/154837874-285ec514-bd81-4a87-8cb8-efc8037da5a6.png">

<img width="355" alt="Screenshot 2022-02-20 at 11 13 08" src="https://user-images.githubusercontent.com/5110408/154837893-9bb2de41-a423-4d26-a55b-02a47fa84f3e.png">

## Your Environment
Running in a docker (20.10.x) for the past 3y
Matomo version: 4.6.2
MySQL version: 5.7.9
PHP version: 8.0.16

Any info on this problem would be much appreciated.

**Comment by Findus23** [comment]
Hi,
Can you check if your server (ideally inside the docker container) is able to reach https://api.matomo.org/1.0/getLatestVersion/ ?

**Comment by rusty1281** [comment]
Thank you @Findus23 for your fast response on the matter.


> Hi,
> Can you check if your server (ideally inside the docker container) is able to reach https://api.matomo.org/1.0/getLatestVersion/ ?


Yes indeed, I can, and it works just fine.
<img width="758" alt="Screenshot 2022-02-20 at 17 56 44" src="https://user-images.githubusercontent.com/5110408/154854324-6461d251-5059-43a5-9100-54bc514fc03c.png">

**Comment by sgiehl** [comment]
@rusty1281 I'll close this issue for now. We've already released couple of new versions meanwhile. If you still have problems with updating, feel free to comment here again or open a new issue.

**Comment by rusty1281** [comment]
Hello,

Problem is still present but I have done all the current updates using the manual method. Not sure why the pull is not working but it’s fine, acceptable workaround. 

Tnx again.
