### ISSUE TITLE
Update INTL CLDR translations

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18833]
We need to update the translations for languages, currencies, and countries according to our internal confluence process  "Update Intl CLDR Translations". We're doing this every 6 months-ish.

**Comment by sgiehl** [comment]
@tsteur would be quite quick to write a small github action that automatically creates a PR if updates are available. We could then run that once a month or so. This would reduce the amount of manual work that needs to be done in the future.

**Comment by tsteur** [comment]
How much work would that be?

**Comment by sgiehl** [comment]
As most of the stuff is already there in other actions I would say around 1 or 2 hours.

**Comment by tsteur** [comment]
👍  sounds good
