### ISSUE TITLE
Enhancement: Display statistics of returning visitors in additional ways, including percentages

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#18856]
Develop a statistic on the dashboard to show visitors who come back frequently
A first way:
Express the daily rate of return as a percentage
Second way:
Detail what is the return frequency rate per day .. on people returning to the site how many times have they already come before.
  
  
This request was translated based on the following user email:
**Question**: What is the feature you are missing the most in Matomo and why?
**Answer**:  Bonjour,
Le top serais de pouvoir développer les personnes qui revienne fréquemment
Un premier point
Exprimer en pourcentage le taux de retour journalier
Et un 2eme
Détailler quel est le taux de fréquence retour par jour ..sur les personnes retour sur le site combien de fois sont il déjà venus auparavant.

**Comment by sgiehl** [comment]
@atom-box Isn't that kind of included in the engagement reports:
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=General_Actions&subcategory=VisitorInterest_Engagement

**Comment by heurteph-ei** [comment]
@atom-box, @sgiehl Then I think this 3 months old enhancement can be closed, isn't it?
