### ISSUE TITLE
Auth token (for API) not displayed on creation

### ISSUE THREAD

**Issue by rafaelmaeuer** [piwik/piwik#18850]
## Expected Behavior

When generating an API auth token, the `auth_token` should be displayed.

## Current Behavior

When generating an API auth token, the requests loads (page loading spinner) until there is a timeout.
After refreshing the page one (or sometimes two similar) new entries appear under `tokens`.
As the one-time token isn't displayed, the created API-access cannot be used.

The same is happening when deleting a token (timeout -> entry is deleted after refresh).

## Possible Solution

?

## Steps to Reproduce (for Bugs)

Follow these steps in https://matomo.org/faq/general/faq_114/ for `Matomo 4 and newer`

## Context

Trying to connect [WP-Matomo Integration (WP-Piwik)](https://de.wordpress.org/plugins/wp-piwik/) with Matomo and therefor needing an `auth_token`.

## Your Environment

* Matomo Version: 4.7.1
* PHP Version: 8.0.14
* Server Operating System: Ubuntu 20.04.1
* Additionally installed plugins:

* Browser: Brave / Safari
* Operating System: macOS 12.1

**Comment by sgiehl** [comment]
Hi @rafaelmaeuer. Thanks for creating the issue.
For me that works without issues and after confirming the password it displays a page like
![image](https://user-images.githubusercontent.com/1579355/156013970-f6ab7378-6896-47dd-8eda-488354046e61.png)

Can you see any errors in the error log?

**Comment by rafaelmaeuer** [comment]
Hey @sgiehl thanks for confirming the issue is not related to matomo itself, I am using the docker-image from [crazy-max/docker-matomo](https://github.com/crazy-max/docker-matomo/) so the problem might lay there... No the logs aren't showing any hints toward the problem, I already enabled the debug-mode, but it didn't gave any further information about any cause...

**Comment by rafaelmaeuer** [comment]
Updating Ubuntu and restarting the Server solved the issue...
