### ISSUE TITLE
No data for the month

### ISSUE THREAD

**Issue by ShenandoahInfo** [piwik/piwik#18859]
I logged in to do my monthly report and there is no data for the month of Feb. I also looked at the all-time data and it is the same as last month which confirms no Feb data

**Comment by sgiehl** [comment]
Hi @ShenandoahInfo 
Thanks for creating the issue. We are sorry to hear you are having trouble with your Matomo.
As it's hard to find any reason without more details, please help us by answering the following questions:
* Are all reports empty for the month, or only certain ones?
* Are visitors shown in the visits log, or is it empty as well?
* Can you see data in the reports by switching to week or day reports within Feb?

**Comment by ShenandoahInfo** [comment]
I saw the days and month totals for January but nothing shows up on Feb under any of the types of day, month, custom period…

**Comment by sgiehl** [comment]
@ShenandoahInfo Ok. Are you able to see visitors when going to `Visitors > Visits Log`? If that one is empty as well, there were actually no visits tracked. If there are any it seems the archiving didn't run for some reason.

**Comment by ShenandoahInfo** [comment]
We have never had a month that we didn't have visitors. We have healthy traffic.

**Comment by ShenandoahInfo** [comment]
This morning I am seeing NO info for any month or year.  Everything is zero.  Again, we always have traffic on this website and none of my previous info is available.  Yesterday I was seeing totals through January and today I see nothing.

**Comment by sgiehl** [comment]
Hey @ShenandoahInfo. As we haven't received any other similar report, it seems to be a very specific one. 
You can try to invalidate the report data and re-archive the reports. See this FAQ for details: https://matomo.org/faq/how-to/faq_155/

If that doesn't help, please ask for help on our forum or if you are a customer of Matomo, reach out to our support.

**Comment by atom-box** [comment]
A few users have reported a similar issue this morning.

**Comment by atom-box** [comment]
At least one of the cases is actually not our product:
![image](https://user-images.githubusercontent.com/22874146/156471357-890f70d0-41c1-4576-ac09-2b7f0a422c29.png)
