### ISSUE TITLE
Remove subtable tooltip if rows are displayed expanded upon search

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#18873]
A user noticed and was confused by a misleading message in Pages.  

To reproduce:
1. Go to Dashboard > Behaviour > Pages 
2. Apply a filter term (anything)
3. **Good** See that the hierarchical listing is frozen: the tree does not expand or collapse
4. Unexpected:  The mouseover tooltip misleadingly says _Click this row to expand or contract the subtable_
5. Expected: The mouseover says " "    or else "Expansion / Contraction not allowed in filtered results"

Screenshot: 
![misleading-mouseover-matomo](https://user-images.githubusercontent.com/22874146/156450625-f439199b-c426-4589-bd76-a2e618c9e48a.png)

**Comment by sgiehl** [comment]
That's very easy to change. Will prepare a PR for it.
