### ISSUE TITLE
Data protection: Hide visitor id in visits log if profile is disabled

### ISSUE THREAD

**Issue by PeteTrombone** [piwik/piwik#18884]
We had to deactivate the visitor profile for data protection reasons.
However, the IP address and the visitor ID are still displayed in the visitor log as a mouseover effect.
![image](https://user-images.githubusercontent.com/57910876/156796735-3c8530f5-0c10-4ff5-b257-4317396b19b4.png)

This is not the case on the Matomo demo page.
![image](https://user-images.githubusercontent.com/57910876/156796810-cf17e786-4523-4c7c-a165-a43427e7bfc0.png)

Matomo-Version: 4.7.1
MySQL-Version: 10.4.21-MariaDB-log
PHP-Version: 7.4.26

**Comment by sgiehl** [comment]
Hi @PeteTrombone. Matomo doesn't display this private information for the anonymous user. If you would be logged in on the demo you would see it their as well

**Comment by tsteur** [comment]
@PeteTrombone Matomo can be configured to [optionally allow anyone to view the tracked analytics data](https://matomo.org/faq/how-to/faq_20130/). This is the case on the demo. When the data is available publicly then this information is hidden.

For the IP if you don't want to show it, then you can either [fully or partially anonymise the IP address](https://matomo.org/docs/privacy-how-to/#step-1-automatically-anonymize-visitor-ips).

The visitor ID would be always shown when you are logged in and AFAIK it isn't possible to hide it. Do you see an issue with this?

**Comment by PeteTrombone** [comment]
@tsteur yes, we have an issue. 
Due to privacy laws in Germany (Europe), we had to disable the visitor profiles so that the visitor ID is no longer visible. Unfortunately, the visitor id is still visible in the visitor log as described above. However, we do not want to disable the visits log, because then the ecommerce log, the segmented visits log, the realtime map or the realtime widgets will no longer work.

I also don't understand the function that you can only switch off the visitor profile if you can still see the personal data.

We already anonymize the IP address.

**Comment by tsteur** [comment]
Indeed @PeteTrombone . If the visitor profile is disabled, then the visitor ID should not be shown, and the visitorID segment should be disabled too. It seems like currently this is only happening when visits log and visitor profile is disabled.

**Comment by sgiehl** [comment]
@tsteur It seems the visitorID segment is correctly disabled if (only) the visitor profile is disabled globally. If it's only disabled for a specific site, then the segment remains active when viewing that site.

**Comment by tsteur** [comment]
@sgiehl not fully understanding why that would be the case? We could maybe still disable it even if visits profile is only disabled for a specific site (unless the site is a roll up maybe)? Not sure how trivial it is to implement though

**Comment by sgiehl** [comment]
@tsteur I guess the problem is that the segment list is cached globally and not site dependent. So if we want that segment being available per site we need to change the caching.

**Comment by tsteur** [comment]
@sgiehl I can't really imagine that as Goals, Dimensions, and other things are site dependent and it works fine. Also looking at the cache it may be siteAware?

**Comment by sgiehl** [comment]
@tsteur that was just a guess without looking at the code 🙈 But you're right, it's cached site dependent.
