### ISSUE TITLE
Need to update/replace your code enlistments on OpenHub

### ISSUE THREAD

**Issue by nekohayo** [piwik/piwik#18897]
Some years ago @mattab set up Piwik's profile on OpenHub; now that your repositories have all moved under matomo-org, they are out of date in https://www.openhub.net/p/matomo/enlistments ; as a result OpenHub is unable to pull the data, and if even _one_ repository fails to pull, it will not update its data. So I would recommend you delete all those code enlistments there and add the new ones for the core code that reflects Matomo's activity.

**Comment by mattab** [comment]
Thanks for the info @nekohayo! the project settings were updated, now waiting for the page to be refreshed within 1-2 days :+1:
