### ISSUE TITLE
Add more options for goal tracking based on events

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#18898]
## Summary

Currently, one can trigger a goal based solely on one characteristic of an event (category or name or . It could be great to give the possibility to do it with multiple event fields, like event category AND event name.
## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

**Comment by heurteph-ei** [comment]
Same as (newer but more complete) enhancement #19093

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/goal-events-not-really-usable/48524/3

**Comment by jwhWHU** [comment]
Yes, it would be much more useful if Event Category, Action, and Name could all be defined for a certain goal.

**Comment by larsskjoldiversen** [comment]
Yes, please.
I'm surprised this is not implemented and that we have to do workarounds to make this work.

**Comment by Chardonneaur** [comment]
@larsskjoldiversen  great comment, in fact, there is a potential work around when you use manual goal. You can use the tag manager in order to filter the trigger according to different variables. It is a bit more techie but it can work on some cases. If you need me to provide you with a specific use case, just let me know about the use case you have in mind. Cheers,

**Comment by goochj03** [comment]
Had a customer today asking how they could easily setup a goal with multiple event values - "Is it not possible to easily add several conditions for an event, ie a CATEGORY + label + action? That seems basics and I cant figure out"

**Comment by mattab** [comment]
Thanks for the reports and all the comments! it duplicates this one: https://github.com/matomo-org/matomo/issues/10791
