### ISSUE TITLE
Error on upgrade: Call to undefined method Piwik\Plugins\Overlay\Overlay::isOverlayRequest()

### ISSUE THREAD

**Issue by unhammer** [piwik/piwik#18906]
## Expected Behavior
Upgrading to 4.8.0 from the web ui. 

## Current Behavior

After it seems done, I got a 500, and on trying to log in I see `An Error occurred` and `Call to undefined method Piwik\Plugins\Overlay\Overlay::isOverlayRequest()` 

## Steps to Reproduce (for Bugs)

1. Be on some older version (my CHANGELOG file says 4.6)
2. Try to upgrade to 4.8.0 from web ui

## Your Environment

* Matomo Version: possibly 4.6 according to CHANGELOG
* PHP Version: 7.4.25
* Server Operating System: debian 10 buster
* Additionally installed plugins: none that I know of

I see nothing from https://forum.matomo.org/search?q=isOverlayRequest

**Comment by unhammer** [comment]
fixed by manually wget+unzipping over ssh, as described in
https://matomo.org/docs/update/#the-manual-three-step-update
Maybe it was just some glitch with the auto-unzipping on the server? I'll just close this, probably not a bug if it's just me :-)

**Comment by 756gzdz5** [comment]
@unhammer what did you unzip? I'm having the same issue.

**Comment by sgiehl** [comment]
@756gzdz5 It seems for some reason the file `plugins/Overlay/Overlay.php` hasn't been updated correctly. You can download the official release zip and overwrite the contents on your webserver to fix that.

**Comment by 756gzdz5** [comment]
@sgiehl Thank you, now I got it.

**Comment by unhammer** [comment]
@756gzdz5 edited my comment for future readers, I meant following https://matomo.org/docs/update/#the-manual-three-step-update instead of "one-click update" :) Interesting that you got the same error, maybe this is a real bug after all?

@sgiehl I think it's more than just that file that wasn't updated correctly (since my CHANGELOG still said 4.6), that's just the first file that lead to an error. Just in case someone thinks they can update just that one file, that's probably not going to work, need to unzip everything ;)
