### ISSUE TITLE
Set the _pk_id in the past when deleting cookie. 

### ISSUE THREAD

**Issue by jmumby** [piwik/piwik#18902]
When the _pk_id cookie is set to expire it sets the current date. When tools like cookiebot scans for cookies and have a timing anomaly potentially the cookie can still seem active. 

Can we have the cookie set to a time in the past to avoid this issue.

**Comment by aleksijohansson** [comment]
It seems that the cookies are set to expire in the past when deleted, but only 86400 milliseconds (~86 seconds). Since there can be 26 hours at most between timezones, maybe setting the cookies to expire a good 36 hours in the past would be a safe bet. PR incoming.
