### ISSUE TITLE
Matomo knowledgebase discoverability improvements

### ISSUE THREAD

**Issue by justinvelluppillai** [piwik/piwik#18934]
In order to assist with our goal of improving discoverability of relevant, timely information while onboarding and using Matomo we have the following improvements:

## Summary

- [ ] adding a Search placeholder so it’s more clear there is a search.

![image](https://user-images.githubusercontent.com/1127121/158078765-17ed0fa1-c986-4882-9104-3a1b01226db9.png)

- [ ] In the search box make the categories bold to highlight them better and people better noticing the “help resources”

![image (1)](https://user-images.githubusercontent.com/1127121/158078758-abcff229-4384-4998-84cd-1115d5926277.png)

- [ ] On the info page shows the h4 headers bigger to better see the different versions of help like Community help. And we could also mention a benefit around it like find what you are searching for quickly or discover new features by 
searching or what not. Would need to come up with something

![image (2)](https://user-images.githubusercontent.com/1127121/158078759-45927af8-371b-4e58-9027-4f761bc709ae.png)

- [ ] Add links to the relevant guides where possible, eg there is currently no link to the Goals guide.

![image (4)](https://user-images.githubusercontent.com/1127121/158078764-0dd4f33c-ddcf-4df5-afed-5fef06f1d2f1.png)

**Comment by justinvelluppillai** [comment]
#18944 provides the search box improvements, the info page changes and links to Knowledge base articles for Goals and several others.

Suggested: splitting the admin menu help links task to a separate issue and defer until after the admin menu is migrated to Vue.

Any preferences there @tsteur?

**Comment by tsteur** [comment]
@justinvelluppillai sounds good to split it and create a new issue and do it later 👍
