### ISSUE TITLE
UI Problem : Variable Types change simply writing a name

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [piwik/piwik#18933]
Hi, 

In Tag Manager, just create a new variable (all of types of variables are concerned) specify a name, then the type of the variable change also (https://ibb.co/xqyMRvQ).

This the variable cannot be used.
This is a big issue of the UI

here the config : 
* Matomo Version: 4.8.0
* PHP Version: Version de PHP: 7.4.28
* DB Version de MySQL: 10.4.14-MariaDB-1:10.4.14+maria~stretch-log
* Server Operating System: Debian 10.11
* Additionally installed plugins: None
* Browser: Chrome & Firefox
* Operating System: MacOS

Best

**Comment by Kixell-NicolasJardillier** [comment]
Re,
this is not only UI problem.
Export/Import JSON produce same error.

This is critical in the sens that it is not possible to change the name of the variable. Moreover, if you can create variables correctly by inspecting the source code to override the default JS behavior, the export/import JSON failed.
This is urgent problem.

**Comment by Kixell-NicolasJardillier** [comment]
To illustrate the UI (but export/import is also bugged)
![Mar-13-2022 08-42-48](https://user-images.githubusercontent.com/4049969/158050345-2e2c0183-b615-4d91-b83d-f88e1c22ab69.gif)

**Comment by sgiehl** [comment]
@diosmosis is this Vue related?

**Comment by diosmosis** [comment]
@sgiehl this was reported in https://github.com/matomo-org/tag-manager/issues/444 and fixed in https://github.com/matomo-org/tag-manager/pull/445

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/matomo-4-8-0-tag-manager-variable-editing-variable-name-changes-variable-type/45181/2
