### ISSUE TITLE
More beautiful reports with 100% width

### ISSUE THREAD

**Issue by anyworx** [piwik/piwik#18942]
Hello Developers,

thank you for this wonderful product - I love Matomo, but I feel there is one thing I should tell you as a developer:

Once a month, I send a Matomo report to my customers and I think these reports could look much better, with a simple change... when the graphs and tables are set to 100% width, it doesn't seem like patchwork.

To illustrate it, I have uploaded a screenshot to my cloud here:
https://sun.anyworx.cloud/index.php/s/ATRfFNT23LMgGiW

Best Regards,
Adrian

**Comment by atom-box** [comment]
A user request:

" _Question: What is your main concern about Matomo?
Answer: 
(customised reports in Matomo, truly customised, like on GDS.)_"

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue https://github.com/matomo-org/matomo/issues/18950, I'll close this one. It would be great to have your perspective there.

**Comment by tzi** [comment]
Should be fixed in #23919
