### ISSUE TITLE
Link to FAQ not working when segment archiving disabled for plugin

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18954]
Just enabled the feature for https://github.com/matomo-org/matomo/pull/18279

This links to https://matomo.org/faq/how-to-disable-archiving-the-segment-reports-for-specific-plugins

I clicked on the link and the link is not working.

Expected: I expect the FAQ to work and explain what is happening.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/273120/158703012-ff36ada0-2e1f-4093-a812-82dcf738cfdf.png">

**Comment by peterhashair** [comment]
@tsteur should work now, it seems like the article was not published.

**Comment by tsteur** [comment]
👍
