### ISSUE TITLE
Deleting recorded sessions via HTTP API doesn't remove them from Matomo Cloud quota

### ISSUE THREAD

**Issue by BobOtike** [piwik/piwik#18960]
## Expected Behavior
When I hit the quote of sessions I can record, all session recordings get set to "Ended". Ideally, I would then be able to remove some of the recorded sessions to go below the quota, and the recordings would continue until the quota is hit again. At the very least, I would be able to start a new session recording while I have an unused quota.

## Current Behavior
I have Matomo Cloud with a limit of 150 recorded sessions. This limit was recently hit. I then went ahead and deleted some of the sessions via the HTTP API endpoint `HeatmapSessionRecording.deleteRecordedSession`. Upon doing so, the existing session recordings stayed "Ended" and didn't continue. I also wasn't able to create a new recording, but instead was presented with the following message:

```
Limit of recorded sessions reached
The limit for the number of recorded sessions is reached as you have currently 152 recorded sessions but your plan allows only up to 150 recorded sessions.

To use this feature, please ask a billing owner to upgrade your plan.
```

I currently have 43 recorded sessions in my account, after removing most of the 152 with the HTTP API. As the quota isn't updated and I can't restart the existing session recordings either, the only way to start recording again would (presumably) be to remove one of my existing session recordings. I didn't try that so far, as I want to keep the recorded sessions.

I haven't tested whether the same problem arises when removing the recorded sessions via the GUI on the website. 

## Possible Solution
The quota should be kept in sync with the actual number of recorded sessions. If unused quota becomes available again, best case scenario would be that existing recordings continue until the quota is reached once more. A less optimal, but still viable, solution would be to at least be able to create a new recording when a portion of the quota is freed. 

## Steps to Reproduce (for Bugs)
1. Start a session recording on Matomo Cloud
2. Wait for your quota to be hit
3. Delete some sessions via the HTTP API
4. Try to create a new session recording

## Context
I am not always in a position to use a specific page that has a filtering capacity as an entry point for a recording. If I want to record all ecommerce interactions for visits that convert in a shop for example, starting on e.g. the cart page would be too late. So I have to start recording on the first page a user hits. That means I also get a lot of sessions which don't actually convert, and are therefore not interesting to me. 
To get to the sessions which interest me, I then use the HTTP API endpoint `HeatmapSessionRecording.getRecordedSessions` combined with the `segment` parameter to identify the unwanted sessions. I then delete those sessions via `HeatmapSessionRecording.deleteRecordedSession`. If those deleted sessions get subtracted from the quota properly, I can keep recording until I have 150 useful sessions before I need to start deleting those. 

## Your Environment
* Matomo Version: Matomo Cloud

**Comment by justinvelluppillai** [comment]
Hi @BobOtike have you contacted our Cloud support team about this issue? It is affecting your cloud account rather than Matomo and they will be able to help you there.
