### ISSUE TITLE
Argument #1 ($m) must be of type Piwik\Plugin\Metric, __PHP_Incomplete_Class given, in Visualizations\Graph

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18963]
Error: {"message":"Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Graph::Piwik\\Plugins\\CoreVisualizations\\Visualizations\\{closure}(): Argument #1 ($m) must be of type Piwik\\Plugin\\Metric, __PHP_Incomplete_Class given","file":"/plugins\/CoreVisualizations\/Visualizations\/Graph.php","line":243,"request_id":"3e7f2","backtrace":" on /plugins\/CoreVisualizations\/Visualizations\/Graph.php(243)\n#0 [internal function]: Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Graph->Piwik\\Plugins\\CoreVisualizations\\Visualizations\\{closure}(Object(__PHP_Incomplete_Class))\n#1 /plugins\/CoreVisualizations\/Visualizations\/Graph.php(243): array_map(Object(Closure), Array)\n#2 /plugins\/CoreVisualizations\/Visualizations\/JqplotGraph\/Evolution.php(244): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Graph->ensureValidColumnsToDisplay()\n#3 /plugins\/CoreVisualizations\/Visualizations\/Graph.php(151): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution->ensureValidColumnsToDisplay()\n#4 /plugins\/CoreVisualizations\/Visualizations\/JqplotGraph\/Evolution.php(96): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Graph->afterAllFiltersAreApplied()\n#5 /core\/Plugin\/Visualization.php(196): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution->afterAllFiltersAreApplied()\n#6 /core\/Plugin\/Controller.php(257): Piwik\\Plugin\\Visualization->render()\n#7 /plugins\/Goals\/Controller.php(223): Piwik\\Plugin\\Controller->renderView(Object(Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution))\n#8 [internal function]: Piwik\\Plugins\\Goals\\Controller->getEvolutionGraph()\n#9 /core\/FrontController.php(626): call_user_func_array(Array, Array)\n#10 /core\/FrontController.php(168): Piwik\\FrontController->doDispatch('Goals', 'getEvolutionGra...', Array)\n#11 /core\/dispatch.php(32): 

URL: https://example.matomo.org/index.php?date=2022-03-07&module=Goals&format=html&forceView=1&viewDataTable=graphEvolution&action=getEvolutionGraph&idSite=2&period=week&comparePeriods%5B%5D=week&compareDates%5B%5D=2022-02-28&segment=&widget=&showtitle=1&random=5722

Referrer: https://example.matomo.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=2

GET: {"date":"2022-03-07","module":"Goals","format":"html","forceView":"1","viewDataTable":"graphEvolution","action":"getEvolutionGraph","idSite":"2","period":"week","comparePeriods":["week"],"compareDates":["2022-02-28"],"segment":"","widget":"","showtitle":"1","random":"5722"}

**Comment by JasonMortonNZ** [comment]
This issue was encountered again a few days ago.

**Comment by tsteur** [comment]
This was likely due to an internal plugin. Will close for now
