### ISSUE TITLE
Add hits to all websites dashboard metrics

### ISSUE THREAD

**Issue by jmumby** [piwik/piwik#18978]
The All websites metrics does not currently list individual hits per site. 

## Summary
For Cloud customers that are agency's they would like to bill hits as Cloud does, but this is not possible to accurately measure as hits is not included in the all websites dashboards metric.

Can we have hits added to the All websites dashboard in total and per site?

**Comment by atom-box** [comment]
_Every two months, roughly, we get a request for this feature in Sales. Typical:_

> I have 40+ websites for the clients and would like to know if ... you provide a dashboard to see how much bandwidth is used for each site.

**Comment by atom-box** [comment]
Currently we tell customers to find "hits" in either Custom Reports or in their Cloud Billing.
Because a majority of Matomo users have neither of these things, it would be nice to have a way to see hits; this would be a good feature to add.

**Comment by Normandygirl** [comment]
Since hits are so important to Matomo (for Cloud pricing) is there a way to have them appear in our "All Websites" dashboard alongside the other metrics we have like "visits, pageviews, actions, revenue"?

**Comment by Chardonneaur** [comment]
Hi guys, i got exactly the same demand today, @atom-box it is important to note that it seems that only the account creator in the cloud can see the number of hits in billing, not the other super users.
This is a MAJOR NEED.
Solution suggested, could we please get a metric named Hits which is making the total amount of actions on the Visitors --> Overview report.

**Comment by atom-box** [comment]
A user requested this feature today:

> We **urgently** need the data for the actions of the individual websites in the table in the dashboard "all websites".
> What can I do to display this in the table?
>

**Comment by Chardonneaur** [comment]
@atom-box well, displaying the number of actions could do the job. Honestly, i didn't succeed in just sending a hit to matomo.

**Comment by rcontiuk** [comment]
A customer shared a valid point about hits report:

_"This would be an important development for your customers, as it's difficult for a customer investing several thousand euros to accept that this type of functionality isn't offered"_

**Comment by PeteTrombone** [comment]
Thank you for implementing this function.
I was the trigger for the last request from atom-box entered above.

But I still have a question. What is the difference between actions and hits? Is it the same or is there a difference?
I have different numbers in some cases.

If it is the same, why is it called something different?

**Comment by sgiehl** [comment]
@PeteTrombone Depending on what you are tracking it might be different. See https://matomo.org/faq/getting-started/what-is-the-difference-between-a-hit-and-an-action/
