### ISSUE TITLE
When setting time_before_*_archive_considered_outdated not respected for segments

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#18987]
When setting time_before_*_archive_considered_outdated (day, week etc.) it's respected for "All visits", but not for segments.

## Expected Behavior
If I set time_before_*_archive_considered_outdated, this should be valid both for "All visits" and segments.

## Current Behavior
When setting time_before_*_archive_considered_outdated "All visits" are scheduled for rearchiving respecting the time set, for segments, it's not. 

## Your Environment

* Matomo Version: 4.7.1
* PHP Version: 7.4.27 
* Server Operating System: Ubuntu

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/segments-always-get-invalidated/45247/2

**Comment by mikkeschiren** [comment]
Could be that this behaviour is gone for us in 4.8.0, will come back on the subject later today.

**Comment by mikkeschiren** [comment]
It seems that the issue we had in 4.7.1 is gone in 4.8.0. So closing this issue.
