### ISSUE TITLE
get_class(): Argument #1 ($object) must be of type object, bool given in MultiSites/API.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18992]
Seen below error a few times. This could be a regression maybe?

> Error: {"message":"get_class(): Argument #1 ($object) must be of type object, bool given","file":"plugins\/MultiSites\/API.php","line":344,"request_id":"e1f08","backtrace":" on plugins\/MultiSites\/API.php(344)\n#0 plugins\/MultiSites\/API.php(344): get_class(false)\n#1 plugins\/MultiSites\/API.php(352): Piwik\\Plugins\\MultiSites\\API->calculateEvolutionPercentages(Object(Piwik\\DataTable\\Simple), false, Array)\n#2 plugins\/MultiSites\/API.php(260): Piwik\\Plugins\\MultiSites\\API->calculateEvolutionPercentages(Object(Piwik\\DataTable\\Map), Object(Piwik\\DataTable\\Map), Array)\n#3 plugins\/MultiSites\/API.php(189): Piwik\\Plugins\\MultiSites\\API->buildDataTable(Array, 'day', '2022-03-01,toda...', false, false, false, false, Array)\n#4 [internal function]: Piwik\\Plugins\\MultiSites\\API->getOne('2', 'day', '2022-03-01,toda...', false, false, false)\n#5 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#6 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#7 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#8 core\/API\/Request.php(266): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getOne', Array)\n#9 plugins\/API\/Controller.php(46): Piwik\\API\\Request->process()\n#10 [internal function]

URL: https://example.matomo.org/?module=API&method=MultiSites.getOne&format=json&idSite=2&token_auth=XYZANONYMIZED&period=day&date=2022-03-01,today

Referrer: None

GET: {"module":"API","method":"MultiSites.getOne","format":"json","idSite":"2","token_auth":"XYZANONYMIZED","period":"day","date":"2022-03-01,today","filter_limit":100}

**Comment by sgiehl** [comment]
Turned out that actually was caused by a more fundamental timezone issue 🙈
