### ISSUE TITLE
Fix Sarawak and Terengganu on Visitors Interactive Map Widget

### ISSUE THREAD

**Issue by avimaymon** [piwik/piwik#19006]
## Expected Behavior
1. When clicking on Sarawak we should get the data for Sarawak, when clicking on Terengganu we should get the data for Terengganu.
2. The tooltip should be available also after going into a state and going back out.

## Current Behavior
1. Clicking on Sarawak shows data for Terengganu, clicking on Terengganu shows data for Sarawak.
2. Before going into a state we have the tooltip, after going inside of it and coming back out it's not available anymore
Both issues can be seen here
https://ibb.co/5LWJnGB

## Steps to Reproduce (for Bugs)
Can be seen in this GIF
https://ibb.co/5LWJnGB

## Your Environment

* Browser: Microsoft Edge
* Operating System: Windows 10

The other details will be added shortly
* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

**Comment by sgiehl** [comment]
Hi @avimaymon 
Thanks for the report. Seems the ISO codes on our map are flipped in that case. I'll prepare a PR to fix that.
