### ISSUE TITLE
The 4.8.0 tagged commit is outside of the repository.

### ISSUE THREAD

**Issue by djun-kim** [piwik/piwik#19055]
The following message is displayed when viewing the "4.8.0" tag (https://github.com/matomo-org/matomo/commit/f2f6c3d1e7fe00cceb86feaa184049737f3ba45e)

"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

This makes it impossible to update via git

**Comment by Findus23** [comment]
I think that's because the commit was made in the [next_release](https://github.com/matomo-org/matomo/tree/next_release) branch by https://github.com/matomo-org/matomo/pull/18893

**Comment by sgiehl** [comment]
@djun-kim What exactly is your issue with the tag? It should be possible to do a `git checkout 4.8.0`

**Comment by Findus23** [comment]
I just tested it and indeed it is possible to checkout the tag from a fresh clone even though it is not a commit on 4.x-dev.
So it should be fine.

**Comment by djun-kim** [comment]
If I attempt to list tags on an existing repo, I don't see the 4.8.0 tag.  Attempting to checkout the tag on an existing repo gives the following error: `error: pathspec '4.8.0' did not match any file(s) known to git.`.

Working with a fresh clone resolves the issue.

**Comment by sgiehl** [comment]
@djun-kim on an existing repo you might need to fetch the tags with `git fetch --tags` maybe.
