### ISSUE TITLE
Docs for disabling archiving segments for selected plugins - typo in config setting

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#19073]
The docs on https://matomo.org/faq/how-to-disable-archiving-the-segment-reports-for-specific-plugins mention the config parameter name as "disable_archiving_segment_for_plugin" (singular), but the actual config setting is "disable_archiving_segment_for_plugins".

**Comment by Starker3** [comment]
Thanks @peterbo 
I've updated the FAQ with the correct config setting name. You're welcome to close this issue then :+1:
