### ISSUE TITLE
Use HTTPS by default for connections to matomo.org (with working fallback to HTTP requiring super user edit the INI config)

### ISSUE THREAD

**Issue by justinvelluppillai** [piwik/piwik#19081]
# Remaining steps

- Make HTTPS the default 
- Make sure the error message links to this FAQ: https://matomo.org/faq/how-to/faq-how-to-disable-https-for-matomo-org-and-api-matomo-org-requests/ 
- Update the FAQ https://matomo.org/faq/how-to/faq-how-to-disable-https-for-matomo-org-and-api-matomo-org-requests/ to mention it was put in 5.0.0 instead of "We will soon switch this connection over to HTTPS"
- Test that an update from 5.0.0-bX to 5.0.0-bY still work when HTTPS doesn't work (ie. people see the message, and after changing the INI config as per the clear FAQ, then it works for people)

# Initial issue

This applies to all api.matomo.org and plugins.matomo.org calls.

1. DONE  First we add a new required system check showing to users if the connection over HTTPS works or not for these endpoints. If it doesn't work, then there should be an error shown explaining that we will soon switch to HTTPS by default. They should either make HTTPS work or disable HTTPS (see next item). We should mention the consequences of not fixing this issue (eventually won't receive any updates anymore big security issue for sure, and using HTTP is a minor security issue that someone could pretend there is no longer an update available)

2. We introduce a setting to force HTTP instead of HTTPS as some people won't be able to change their PHP either because the hoster doesn't allow it or because they aren't technical enough etc.

3. Create an FAQ about how to make HTTPS work or disable HTTPS and link to it in the system check error message in 1 above.

**Comment by justinvelluppillai** [comment]
@peterhashair did number 3 get done also regarding creating or updating the FAQs? Be good to link to that in this issue for completeness when done.

**Comment by peterhashair** [comment]
FAQ here: [https://matomo.org/faq/faq-how-to-disab…omo-org-requests/](https://matomo.org/?post_type=faq&p=55687&preview=true)

**Comment by peterhashair** [comment]
reopen this issue, as we discussed,  not to force users to use HTTPS at this stage, only a warning message. In the next stage we will force HTTPS connections. Ref Here: https://github.com/matomo-org/matomo-security/issues/195

**Comment by sgiehl** [comment]
removing from 4.11. milestone, as the remaining tasks will be solved in a later verion.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/plugins-matomo-org-over-https/52525/2
