### ISSUE TITLE
Cannot save setting "Also use the Anonymized IP addresses when enriching visits."

### ISSUE THREAD

**Issue by kaskaes** [piwik/piwik#19089]
## Expected Behavior

Under Administration -> Privacy -> Anonymize data -> "Also use the Anonymized IP addresses when enriching visits." the radio button ist set to "Yes". If I change it to "No" and press "save" Button, the value should be stored.

## Current Behavior

Under Administration -> Privacy -> Anonymize data -> "Also use the Anonymized IP addresses when enriching visits." the radio button ist set to "Yes". If I change it to "No" and press "save" Button, it looks like the new value is stored. But after reloading / refreshing the page, the value (radio button) is still "Yes"

## Steps to Reproduce (for Bugs)

1. Go to Administration Administration -> Privacy -> Anonymize data
2. Change the radio button under "Also use the Anonymized IP addresses when enriching visits." to "No"3. 
3. Press "Save" Button
4. Reload the Page
5. Value has not changed

#Context

## Your Environment

* Matomo Version: 4.9.0
* PHP Version: 8.1.3
* Server Operating System: Linux
* Additionally installed plugins:

* Browser: Safari 15.4
* Operating System: Mac OS 12.3.1

**Comment by sgiehl** [comment]
Hi @kaskaes. Thanks for your report. I was able to reproduce that.

@diosmosis that seems to be vue related. The request always contains `useAnonymizedIpForVisitEnrichment: 1`, even if the `no` option was selected. Could you have a quick look?

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/anonymize-tracking-data-issue-after-update-to-4-9/45565/4
