### ISSUE TITLE
Allow users to view report when an A / B test is archived

### ISSUE THREAD

**Issue by nicomegadrive** [piwik/piwik#19091]
## Summary
I would like to be able to see again the results of an A / B test after I archive a test, it's currently not possible.

## Your Environment
* Matomo Version: 4.9.0
* PHP Version: 7.2.34
* Server Operating System: Debian9
* Additionally installed plugins: Custom Reports, Heatmaps

**Comment by sgiehl** [comment]
Hi there, Thank you for creating the issue. To request features for a Premium Plugin please contact shop at innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features

Closing this issue now. Thanks.
