### ISSUE TITLE
Allows extra options when configuring a Goal

### ISSUE THREAD

**Issue by nicomegadrive** [piwik/piwik#19093]
## Summary

On Google Analytics, when you configure a goal if a visitor send an event, you can configure :
- The Category,
- The Action,
- The Label,
- The Value

I would like to be able to do the same on Matomo, as I want to create a goal when an event with the Category "documentation" has been sent, and also where the Label's name is "Test" for example.

At the current state, only allowing people to set only one parameter is too limited.

## Your Environment

* Matomo Version: 4.9.0
* PHP Version: 7.2.34
* Server Operating System: Debian9
* Additionally installed plugins: Custom Reports / Heatmaps

**Comment by bx80** [comment]
@nicoco59 Thanks for the suggestion, this would indeed be a useful capability. :+1: 
Issue #18898 already requested the same functionality so I'll close this issue so we can keep the discussion focused in one place.

**Comment by kravi4** [comment]
Any chance there is some documentation that allows use to add custom events to php code?

**Comment by bx80** [comment]
Hi @kravi4, there is some documentation on PHP events in Matomo here [https://developer.matomo.org/guides/events](https://developer.matomo.org/guides/events)
