### ISSUE TITLE
Facing issues in piwik pro that, we are not able to track the visiters on our Amp page.

### ISSUE THREAD

**Issue by Sdaud1950** [piwik/piwik#19114]
facing issues in Piwik pro that, we are not able to track the visitors on our Amp page.
We've followed the documentation of analytics Accelerated Mobile Pages integration, but we're getting errors in the console.

Ref: Below I have shared a URL link.
"https://analytics.lemontrend.com/ppms.php?action_name=Fashion%20Photographer%20Carlos%20Vaz&idsite=1a05c9c6-0a3f-46c0-aa56-b23e6fbc40c5&rec=1&r=857676&url=https%3A%2F%2Flemontrend.com%2Fphotographers%2Ffashion-photographer-carlos-vaz%2Famp%2F&_id=b11171c18e227161&apiv=1&urlref=&res=1366x768&lang=en-us&gt_ms=53&cs=UTF-8&pv_id=nymoCh "

The code which we've added is followed:
<amp-analytics type="ppasanalytics"> <script type="application/json">{"vars": {"host": "[analytics.lemontrend.com](http://analytics.lemontrend.com/)","website_id": "1a05c9c6-0a3f-46c0-aa56-b23e6fbc40c5","website_hash": "6b17"
}}</script> </amp-analytics>

**Comment by Findus23** [comment]
Hi,

Can you please explain in more detail how this issue is related to Matomo?

**Comment by heurteph-ei** [comment]
I think there is some confusion between Matomo (former piwik) and Piwik-pro (initially a fork of piwik)... :-S

**Comment by Sdaud1950** [comment]
Sorry for the inconvenience, there was a little bit of confusion between Piwik pro and Matomo (Piwik).
