### ISSUE TITLE
Fix display issue with z-index for widgets that use tables with embedded dashboards

### ISSUE THREAD

**Issue by scottf-tvw** [piwik/piwik#19125]
table <thead> in widgets that use tables embedded dashboards have a z-index of 10 causing overflow issues with other components in the view. 

## Expected Behavior
Table headers should not contain a z-index higher than other root components. Thus not blocking menu's and or other nearby reports when overflow is triggered on resizing

## Current Behavior
resizing a dashboard with other components may cause the <thead> of a widget using a table to overflow into the view over other widgets. Menus that are activated will be obscured by the <thead> portion of a widget.  

## Possible Solution
remove z-index = 10 from the <thead>

## Steps to Reproduce (for Bugs)
create a dashboard with table type views. load as an iframe and open a menu. 

## Context
it looks horrible and unprofessional for a white labeled system, lie we are paying for. Also not interested in adding css overrides for something like this. 

## Your Environment

* Matomo Version: 4.9
* PHP Version: 7.4.3
* Server Operating System: cluster of ubuntu 20 lts in AWS
* Additionally installed plugins:
Whitelabel, custom reports and media analytics
* Browser: ANY
* Operating System: ANY
![Screen Shot 2022-04-20 at 4 13 45 PM](https://user-images.githubusercontent.com/2366145/164341499-ab99b9f4-dfbe-44fa-978c-cd7937ea62dc.png)
![Screen Shot 2022-04-20 at 4 06 37 PM](https://user-images.githubusercontent.com/2366145/164341502-b253e0fb-3732-453c-8b27-7c804b86f04e.png)

**Comment by bx80** [comment]
Hi @scottf-tvw, thanks for reporting this. I've recreated the issue and can confirm that removing the z-index from the table header prevents the broken layout.
