### ISSUE TITLE
PHP8.1 compatibility fixes in referrers plugin

### ISSUE THREAD

**Issue by MichaelRoosz** [piwik/piwik#19127]
With Matomo 4.9.0, I see lots of these warnings:

**1.**
```
WARNING Referrers
plugins/Referrers/Columns/Base.php(525): 
Deprecated - mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
```

**2.**
```
WARNING Referrers
plugins/Referrers/Columns/Base.php(478): 
Deprecated - urldecode(): Passing null to parameter #1 ($string) of type string is deprecated
```

Problem 1 I solved temporarily by replacing
`$this->keywordReferrerAnalyzed = mb_strtolower($this->keywordReferrerAnalyzed);`
with
`$this->keywordReferrerAnalyzed = mb_strtolower($this->keywordReferrerAnalyzed ?? '');`

But I am not sure this is the best fix.

**Comment by justinvelluppillai** [comment]
Hi @MichaelRoosz - that fix looks fine to me, it'd be great if you could make a Pull Request for that. The other warning would be a similar fix to the same file.

**Comment by MichaelRoosz** [comment]
Hello @justinvelluppillai , here is a pr: https://github.com/matomo-org/matomo/pull/19135
