### ISSUE TITLE
Key words searched on the site 

### ISSUE THREAD

**Issue by Bira-navi** [piwik/piwik#19140]
Hello,

I would like to know how it is possible to have in front of the keywords searched on the site, the users who typed this keyword?

**Comment by sgiehl** [comment]
Hi @Bira-navi,

I'm not fully sure what exactly you want to achieve. If this is about the distinct number users that performed a search, I guess this is currently not possible. To see all users that performed a search query you can simply use the segmented log feature.

For further questions it might be good to use our forum instead. We usually don't answer questions here, as this should only be used for bug reports and feature requests.

**Comment by Bira-navi** [comment]
> Hi @Bira-navi,
> 
> I'm not fully sure what exactly you want to achieve. If this is about the distinct number users that performed a search, I guess this is currently not possible. To see all users that performed a search query you can simply use the segmented log feature.
> 
> For further questions it might be good to use our forum instead. We usually don't answer questions here, as this should only be used for bug reports and feature requests.

Thank you for your answer, I apologize for not asking my question in the right place.

I would like to know, in front of a keyword, WHICH users have typed it without having to do it one by one

**Comment by sgiehl** [comment]
That is currently not possible using the Matomo UI. Guess you would need to write something yourself to iterate over the results of the segmented visitors log and parse out the attribute you use to identify the user.

**Comment by Bira-navi** [comment]
> That is currently not possible using the Matomo UI. Guess you would need to write something yourself to iterate over the results of the segmented visitors log and parse out the attribute you use to identify the user.

When you say I should write something myself, you mean out of Matomo by coding something like that ?

**Comment by heurteph-ei** [comment]
@Bira-navi have a look at my answer to your post in the forum: https://forum.matomo.org/t/key-words-searched-on-the-site/45679/

**Comment by Bira-navi** [comment]
> @Bira-navi have a look at my answer to your post in the forum: https://forum.matomo.org/t/key-words-searched-on-the-site/45679/

Thank you very much !!!
