### ISSUE TITLE
User Permissions: View user is able create a segment

### ISSUE THREAD

**Issue by KarthikRaja1388** [piwik/piwik#19162]
A user with View permission is able to create a new segment.

## Expected Behavior
View user should only be able to view the reports

## Current Behavior
The user is able to create a new segment

## Steps to Reproduce (for Bugs)
1. Create a view user
2. try to create a new Segment

## Context
User management would not be efficient when the user who have view permission, be able to create a segment which they're not supposed to do

**Comment by peterhashair** [comment]
I think you are right, a view user shouldn't be able to create segments.

**Comment by sgiehl** [comment]
That is actually correct and by design. But it is possible to change the access required with the config flag `adding_segment_requires_access`.
