### ISSUE TITLE
Add superuser access to a user is not possible when SSO is used

### ISSUE THREAD

**Issue by mstenz** [piwik/piwik#19169]
## Expected Behavior
There is no input form for password received (because the user does not know/have a password)

## Current Behavior
A popup is showing that request the user got given his password, which he doesn't know.

## Possible Solution
see "Expected Behaviour"

## Steps to Reproduce (for Bugs)
1. got to the admin panel with a user that has logged in via SSO
2. go to System -> Users
3. choose a user that is not a superuser
4. enable superuser access (the popup appears)

## Your Environment

Matomo Version	 4.9.0
PHP version >= 7.2.5	 8.0.12
PHP_OS	 Linux

**Comment by sgiehl** [comment]
Hi @mstenz 
Which plugin are you using for SSO access? Are you using the SAML plugin or LoginLDAP plugin?

**Comment by mstenz** [comment]
@sgiehl Hi, I am using LoginOIDC, because it authenticates with Gitlab

**Comment by sgiehl** [comment]
Iirc we had similar issues with LoginLdap, but can't remember if there was a solution for that. Maybe @tsteur or @diosmosis know?

**Comment by tsteur** [comment]
@sgiehl had a quick search in the [LoginLdap Issues](https://github.com/matomo-org/plugin-LoginLdap/issues). There was this PR: https://github.com/matomo-org/plugin-LoginLdap/pull/185 maybe it's that? I couldn't find anything else

**Comment by miton18** [comment]
Same issue here with LoginOIDC plugin
https://github.com/matomo-org/matomo/issues/19235

**Comment by miton18** [comment]
Do you know when the prioritization will occur ?

**Comment by bat79a** [comment]
+1 ;p

**Comment by miton18** [comment]
up ;-)

**Comment by justinvelluppillai** [comment]
Adding to current milestone.

**Comment by sgiehl** [comment]
@mstenz @miton18 With #19525 we will most likely introduce a new event, which can then be used to disabled the password confirmation for certain users in UI and API. Login plugins will then need to implement this event.

**Comment by mstenz** [comment]
perfect, thank you
