### ISSUE TITLE
Remove discontinued Alexa from SEO metrics providers

### ISSUE THREAD

**Issue by justinvelluppillai** [piwik/piwik#19166]
Alexa has been discontinued and now our lookups fail. This also means our tests don't pass until we remove Alexa as an SEO rank provider.

We will need to remove Alexa as a provider from the SEO widget, supporting classes and tests also.

Also there may be some documentation updates needed, including https://matomo.org/faq/dashboards/seo-ranking-widget/

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/seo-tab-what-to-replace-alexa/45793/2
