### ISSUE TITLE
Search Engine Keywords Performance Bing report issue

### ISSUE THREAD

**Issue by agency-w52** [piwik/piwik#19178]
Currently we are having problems with the search engine keyword reports: 
Keywords show up in any report (week, month, year) but in a report with a day-based timeframe - here the keyword list is empty for Bing (Google works without problems). The problem occurs on several instances, each using the latest version of Matomo and the plugin - is there any way to fix this?

**Comment by sgiehl** [comment]
Hi @agency-w52.
This is actually not a bug. As it should be mentioned somewhere in the plugin, Bing only provides data on a weekly base. Therefor it is not possible to import or display data for days.

**Comment by agency-w52** [comment]
@sgiehl oh sorry, didn't see that - thanks for the clarification!
