### ISSUE TITLE
Single visit 

### ISSUE THREAD

**Issue by Eknerof** [piwik/piwik#19174]
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by Eknerof** [comment]
Do you think Matomo can be updated to include the function I am looking for where the visiting time of a single visit is displayed?

**Comment by sgiehl** [comment]
Hi @Eknerof. 
I guess you would need to explain that a bit more in detail in order to get an answer.
But for asking questions I would recommend using our forum (https://forum.matomo.org) instead of our issue tracker.
Thanks.

**Comment by Eknerof** [comment]
Hi StefanI have tried to get this message to your programmers for over a year now with no success. I give up nowThanksHans Rencke
      
        
        
          On maj 5 2022, at 11:13 am, Stefan Giehl ***@***.***> wrote:
          
        
        
          
Hi @Eknerof.
I guess you would need to explain that a bit more in detail in order to get an answer.
But for asking questions I would recommend using our forum (https://forum.matomo.org) instead of our issue tracker.
Thanks.

**Comment by sgiehl** [comment]
Where exactly did you try to reach out? Normally messages on the forum or to our support should be answered within a week at most.
We usually only handle bug reports or specific features requests on github, as we don't have enough resources to handle support requests here as well.
