### ISSUE TITLE
Uncaught exception: Error: Class "GuzzleHttp\Exception\RequestException" not found in .../CurlFactory.php:201

### ISSUE THREAD

**Issue by hyzteric** [piwik/piwik#19188]
We purchased and installed the SearchEngineKeywordsPerformance plugin.
Since then, we got the exception below every night.

We are running : 

- OS: Rocky Linux release 8.5
- Matomo: 4.9.1
- MySQL: 8.0.26
- PHP: 8.1.5

Keywords are updated, but something still fails : 

> ERROR [2022-05-04 00:21:46] 3369342  Uncaught exception: Error: Class "GuzzleHttp\Exception\RequestException" not found in /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201
> Stack trace:
> #0 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
> #1 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
> #2 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
> #3 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
> #4 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
> #5 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php(111): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
> #6 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): Google\Auth\Middleware\AuthTokenMiddleware->Google\Auth\Middleware\{closure}()
> #7 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
> #8 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
> #9 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke()
> #10 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
> #11 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\HandlerStack->__invoke()
> #12 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Client.php(112): GuzzleHttp\Client->transfer()
> #13 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->sendAsync()
> #14 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send()
> #15 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/apiclient/src/Http/REST.php(83): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke()
> #16 [internal function]: Google\Http\REST::doExecute()
> #17 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/apiclient/src/Task/Runner.php(182): call_user_func_array()
> #18 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/apiclient/src/Http/REST.php(66): Google\Task\Runner->run()
> #19 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/apiclient/src/Client.php(898): Google\Http\REST::execute()
> #20 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/apiclient/src/Service/Resource.php(238): Google\Client->execute()
> #21 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/vendor/google/apiclient-services/src/SearchConsole/Resource/Searchanalytics.php(51): Google\Service\Resource->call()
> #22 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/Client/Google.php(404): Google\Service\SearchConsole\Resource\Searchanalytics->query()
> #23 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/Importer/Google.php(304): Piwik\Plugins\SearchEngineKeywordsPerformance\Client\Google->getSearchAnalyticsData()
> #24 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/Importer/Google.php(215): Piwik\Plugins\SearchEngineKeywordsPerformance\Importer\Google->getKeywordsFromConsoleAsDataTable()
> #25 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/Importer/Google.php(150): Piwik\Plugins\SearchEngineKeywordsPerformance\Importer\Google->importKeywordsIfNecessary()
> #26 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/Importer/Google.php(136): Piwik\Plugins\SearchEngineKeywordsPerformance\Importer\Google->importKeywordsForListOfDates()
> #27 /var/web/matomo/plugins/SearchEngineKeywordsPerformance/Tasks.php(70): Piwik\Plugins\SearchEngineKeywordsPerformance\Importer\Google->importAllAvailableData()
> #28 [internal function]: Piwik\Plugins\SearchEngineKeywordsPerformance\Tasks->runImportsGoogle()
> #29 /var/web/matomo/core/Scheduler/Scheduler.php(309): call_user_func()
> #30 /var/web/matomo/core/Scheduler/Scheduler.php(154): Piwik\Scheduler\Scheduler->executeTask()
> #31 /var/web/matomo/plugins/CoreAdminHome/API.php(68): Piwik\Scheduler\Scheduler->run()
> #32 /var/web/matomo/core/CronArchive.php(653): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
> #33 /var/web/matomo/core/CronArchive.php(279): Piwik\CronArchive->runScheduledTasks()
> #34 /var/web/matomo/core/Access.php(661): Piwik\CronArchive->Piwik\{closure}()
> #35 /var/web/matomo/core/CronArchive.php(284): Piwik\Access::doAsSuperUser()
> #36 /var/web/matomo/plugins/CoreConsole/Commands/CoreArchiver.php(32): Piwik\CronArchive->main()
> #37 /var/web/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute()
> #38 /var/web/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
> #39 /var/web/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
> #40 [internal function]: Symfony\Component\Console\Application->doRun()
> #41 /var/web/matomo/core/Console.php(135): call_user_func()
> #42 /var/web/matomo/core/Access.php(670): Piwik\Console->Piwik\{closure}()
> #43 /var/web/matomo/core/Console.php(136): Piwik\Access::doAsSuperUser()
> #44 /var/web/matomo/core/Console.php(87): Piwik\Console->doRunImpl()
> #45 /var/web/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
> #46 /var/web/matomo/console(32): Symfony\Component\Console\Application->run()
> #47 {main}

**Comment by sgiehl** [comment]
Hi @hyzteric

Thank you for creating the issue. To request support for a Premium Feature please contact shop at innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features
We are only handling Matomo core issues here.

Closing this issue now. Thanks.
