### ISSUE TITLE
Unnecessary loop

### ISSUE THREAD

**Issue by ulcuber** [piwik/piwik#19181]
## Current Behavior

https://github.com/matomo-org/matomo/blob/0e41d7e28ae063ca6117cb00d73f1c6a2b1a8436/js/piwik.js#L266

## Possible Solution

`return false` immediate

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Hi @ulcuber 
Thanks for point that out. You are right, that can be improved. I'll try to set up a PR for that quickly.
