### ISSUE TITLE
Use a customized dashboard in a email report

### ISSUE THREAD

**Issue by niklasternstedt** [piwik/piwik#19198]
## Summary
I would be nice to be able to use a dashboard in a email report. The email report lacks some nice features like bar graphs or pie charts. It would be nice to use the same features in a dashboard as in a email report. For example use kpi widgets in a email report.

**Comment by mJ25-fr** [comment]
I fully agree with this request : a simple button to convert a full dashboard (all the tables/graphs in a dashboard)  into a similar PDF that could be send by mail.

**Comment by atom-box** [comment]
Redundant to 
[5101](https://github.com/matomo-org/matomo/issues/5101)
Post there instead.

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue https://github.com/matomo-org/matomo/issues/13820, I'll close this one. It would be great to have your perspective there.
