### ISSUE TITLE
Sparklines show correct data in all goals reports

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#19206]
in the Goals report the sparklines for each goal are all the same although they should be different. 

For example here: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today#?idSite=1&period=month&date=today&category=Goals_Goals&subcategory=General_Overview

## Expected Behavior

The sparklines should be different and show the real data.

## Current Behavior

Sparklines in Goals Overview are all the same but shouldn't be.

This seems to be buggy only in Goal overview report. (Other sparklines seem to work fine?)

## Proposed solution

Is there a UI test to catch this regression in the future?

## Your Environment
 
Reproduced in 4.9.1 and still present in latest RC

**Comment by sgiehl** [comment]
Guess that one regressed in #18493
