### ISSUE TITLE
UI error when deploying matomo 4.9.1 on wordpress

### ISSUE THREAD

**Issue by mattmary** [piwik/piwik#19207]
## Expected Behavior
Be able to open matomo 4.9.1 on wordpress

## Current Behavior
Only a part of the interface is displayed. there is a js error 
![Screenshot from 2022-04-20 11-14-49](https://user-images.githubusercontent.com/86216084/167750547-a7f6e6fa-a4e2-4ebc-bb41-264890108fbd.png)

## Possible Solution
removing the method getJsInclusionDirective in the plugins/WordPress/WpAssetManager.php file solves the issue.

**Comment by mattmary** [comment]
https://github.com/matomo-org/matomo-for-wordpress/issues/605

**Comment by peterhashair** [comment]
@mattmary @justinvelluppillai
 I fixed it by remove  `/plugins/WordPress/WpAssetManager.php`
 
 replace below with 
 ```php
use Piwik\AssetManager; 
...
$assetManager = new AssetManager(); 
 ```
  https://github.com/matomo-org/matomo-for-wordpress/blob/3665e6fad628d16fea27e3f2672f571e5a82b1c1/plugins/WordPress/WordPress.php#L139


PR here https://github.com/matomo-org/matomo-for-wordpress/pull/607

**Comment by mattmary** [comment]
the wordpress asset manager does not load the new js files.
to be able to do it, I need access to the assetManager::getPluginUmdChunks from the wpAssetManager. Can you switch its visibility to protected?

**Comment by justinvelluppillai** [comment]
Most of the changes needed here are in the WpAssetManager, but @peterhashair can you please change `AssetManager::getPluginUmdChunks` from `private` to `protected`? We can merge this change to 4.10.0 before release, on `next_release` branch.
