### ISSUE TITLE
Spark lines show correctly in KPI widget when using segments 

### ISSUE THREAD

**Issue by jmumby** [piwik/piwik#19209]
When you use KPI widgets in the dashboard and select for example `Visits` and then apply a segment the spark line flat lines.  

![image](https://user-images.githubusercontent.com/4339071/167752868-6c457e09-3357-4701-9fda-297c80b654bf.png)

## Expected Behavior

The spark line should appear the same way it does for all visits. 

![image](https://user-images.githubusercontent.com/4339071/167753039-b6377832-26f5-414b-9cd3-0aa98432cb0b.png)

## Current Behavior

The spark line is missing. 

## Steps to Reproduce (for Bugs)

1. Add the KPI widget to your dashboard
2. Select a metric like `Visits`
3. Apply a segment

## Your Environment

Matomo Cloud 11/MAY/22

**Comment by sgiehl** [comment]
This might possibly be a url encoding issue. If e.g. the segment might be encoded too often or less in the url, it might fail to load.
Not sure if there were any changes when migrating to vue maybe. Guess we should quickly check that (with browser archiving disabled).

**Comment by justinvelluppillai** [comment]
It'd be good to confirm whether this is a regression @sgiehl and if so we can prioritise it for the next patch release or 4.11.0

**Comment by sgiehl** [comment]
@justinvelluppillai This actually seems to be a vue regression. With Matomo 4.6. a segment like `deviceType==tablet` was included in the sparkline url with `deviceType%3D%3Dtablet`, with latest 4.x-dev it's included with `deviceType%253D%253Dtablet`. So it now seems encoded twice. ping @diosmosis

**Comment by heurteph-ei** [comment]
@justinvelluppillai it was working on 4.3.1:
![image](https://user-images.githubusercontent.com/79993552/169980306-5f9ab398-5131-45bd-985e-de696d6ab572.png)

**Comment by diosmosis** [comment]
@sgiehl I was not able to reproduce the original problem locally, but I was able to see the double encoded segment. The fix for that is here: https://github.com/matomo-org/matomo/pull/19260. Can you check if it solves the original problem?

**Comment by justinvelluppillai** [comment]
thanks @sgiehl and @diosmosis
