### ISSUE TITLE
Error in "Visits in Real-time" widget when visits log and profile is disabled

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19219]
I have the visits log & profile disabled in the site: 

<img width="389" alt="image" src="https://user-images.githubusercontent.com/273120/168500101-4bf2cdb0-51da-4315-a6ae-63a4946b4120.png">

In a dashboard I have the "Visits in Real-time" widget.

This shows below error

<img width="589" alt="image" src="https://user-images.githubusercontent.com/273120/168500116-eff3b604-3caf-49c4-be2c-d4c13bd0370e.png">

### Expected:

Show a nice error message saying this visitor is disabled and that an admin can enable it.

### Background

This is the request that fails 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/273120/168500147-2a06000c-36eb-46c8-9a65-0711820577f5.png">

The response includes the correct message. But Matomo doesn't show it and instead replaces it with a generic one 
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/273120/168500167-22504717-975d-43a7-9bba-73c116b4047c.png">

**Comment by sgiehl** [comment]
@tsteur Shouldn't we simply disable the widget if visits log & profile are disabled?

**Comment by tsteur** [comment]
@sgiehl disable the widget when the feature is disabled for a site would work too 👍

**Comment by sgiehl** [comment]
Actually it seems the widget should already be disabled if the visits log was disabled. Just tested that locally and the widget isn't shown anymore, even if it was added to the dashboard before. It for sure might fail if a dashboard is opened and you disable the visits log in another tab.

**Comment by tsteur** [comment]
👍  I'll close it again as I now can't reproduce it either. Maybe some caching or so. It's been disabled for days though and I had reloaded the page a few times and the error still showed up. I'll re-open if I see the error again.
