### ISSUE TITLE
Error message when upgrading CustomVariables plugin from 4.0.1 => 4.1.0

### ISSUE THREAD

**Issue by chriscroome** [piwik/piwik#19229]
With the latest version of Matomo:

```bash
php console core:version
4.10.0
```

There is a plugin upgrade available:

Plugin | Version | Description | Status | Action
-- | -- | -- | -- | --
| CustomVariables | 4.0.1 => 4.1.0 | Categorise your visitors and actions with custom  name-value pairs. Segment by these values and get more insights to draw  the right conclusions. | Active | Update

When the *Update* link is clicked I get:

> ## An error occurred
> Could not verify the security token on this form.

When the *Plugin* tick box is selected and then *Update Selected* is clicked I also get:

> ## An error occurred
> Could not verify the security token on this form.

If I reload the plugin page and then tick the box to select the plugin and click *Update Selected* I get an error page with:

> ## An error occurred
> The ui asset with 'href' = /home/stats/sites/default/plugins/CustomVariables/angularjs/manage-custom-vars/manage-custom-vars.directive.less is not readable

Note that the `/home/stats/sites/default/plugins/CustomVariables/angularjs` directory doesn't exist.

However when then reloading the plugins page there are no updates available and CustomVariables is listed as running version 4.1.0:

Plugin | Description | Status | Action
-- | -- | -- | --
CustomVariables                        (v4.1.0) | Custom Variables are (name, value) pairs  that you can assign using the Javascript API to visitors or any of their  action. Matomo will then report how many visits, pages, conversions for  each of these custom names and values. View the detailed Custom  Variables for each user and action in the Visitor Log. This plugin is  required to use Ecommerce Analytics feature!                                                                                                                                                                         GPL v3+                                                                                                                                          By                                     Matomo. | Active | Deactivate

So the upgrade for the plugin do appear to work but the errors are not ideal, I have had the exact same issue as described above with 4 Matomo sites, all running with the latest Debian Bullseye PHP:

```bash
phpquery -V
7.4
```

**Comment by bx80** [comment]
Hi @chriscroome, thanks for reporting this. 

That security token error message when updating plugins sounds very much like bug #15608 which we've had trouble recreating, the extra information here might be helpful.

The missing file error when rerunning the plugin update likely means that the first plugin update attempt correctly removed the file as part of the update, then when the second (page reload) update ran the file is unexpectedly reported missing as it. The angularjs files are no longer needed in newer versions of the plugin.

I'll close this issue in favor of #15608.
