### ISSUE TITLE
ConfirmPassword is not working with Login plugins

### ISSUE THREAD

**Issue by miton18** [piwik/piwik#19235]
Using https://github.com/dominik-th/matomo-plugin-LoginOIDC.
We cannot save settings on `General settings`.

## Expected Behavior
Be able to confirm password with OIDC plugin

## Current Behavior
Asking for a password we never set

## Steps to Reproduce (for Bugs)
1. Setup matomo v4.10.0
2. Add LoginOIDC plugin
3. Login
4. Try to edit settings

## Context
We use the LoginOIDC plugin to use CleverCloud (KeyCloak) Authentication system.

It seems [this event](https://github.com/dominik-th/matomo-plugin-LoginOIDC/blob/4.x-dev/LoginOIDC.php#L37) is never fired to OIDC plugin.

## Your Environment

* Matomo Version: v4.10.0
* PHP Version: PHP 8.1.6
* Server Operating System: Gentoo
* Additionally installed plugins:
  * TrackingQueue
* Browser: Firefox
* Operating System: Gentoo

**Comment by sgiehl** [comment]
Hi @miton18 
That seems to be a similar issue like #19169
The event you mentioned was actually added in #16337

**Comment by sgiehl** [comment]
Closing this one in favor of #19169
