### ISSUE TITLE
Config.ini.php Updation not getting reflected and Global.ini.php is observed

### ISSUE THREAD

**Issue by Prithivi-Rajan** [piwik/piwik#19230]
I'm running the Matomo as a docker file and I'm trying to update the config.ini.php file for rows

datatable_archiving_maximum_rows_actions = 10000
datatable_archiving_maximum_rows_referrers = 10000

where as I'm seeing the results to be 

datatable_archiving_maximum_rows_actions = 500
datatable_archiving_maximum_rows_referrers = 1000

## Expected Behavior

I should see below values in Matomo UI
datatable_archiving_maximum_rows_actions = 10000
datatable_archiving_maximum_rows_referrers = 10000

## Current Behavior

datatable_archiving_maximum_rows_actions = 500
datatable_archiving_maximum_rows_referrers = 1000

## Possible Solution

Looks like the global.config.ini is referred irrespective of the changes done in config.ini.php

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 3.13.4-debian
* PHP Version:
* Server Operating System: 
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
@Prithivi-Rajan Are you still using Matomo 3.13.4? In this case we highly recommend to update to Matomo 4.
But besides that there is no known Bug in Matomo 3 regarding the config. Please double check that you put the configuration into the correct section. They need to go into `[General]`

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/config-ini-php-updation-not-getting-reflected-and-global-ini-php-is-observed/45960/2
