### ISSUE TITLE
Links are not visible in tooltip

### ISSUE THREAD

**Issue by AltamashShaikh** [piwik/piwik#19249]
Links displayed with tooltip are not visible

<img width="1054" alt="169452698-befd7491-03d3-4bc5-8f44-061243dbb597" src="https://user-images.githubusercontent.com/14902277/169489784-b8238d8e-14c3-47a4-80e1-40eb9d6f8454.png">

## Expected Behavior
The links should be visible, might changing the link color to blue would help or make it dark.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Actually I guess it would make sense to remove all `<a>` tags from tooltips, as they can't be clicked anyway.

**Comment by Findus23** [comment]
I think this is the same as https://github.com/matomo-org/matomo/issues/17627
