### ISSUE TITLE
Ensure Safari browser shows the information notice

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#19244]
When hovering the mouse on a metric header column the information notice is not showing up when using Safari browser, in fact it is appearing behind the header.

**Comment by bx80** [comment]
Hi @Chardonneaur, thanks for reporting this. Are you using the latest Matomo 4.10 release?

This bug was recently fixed in issue https://github.com/matomo-org/matomo/issues/19125 which should be included in 4.10

**Comment by justinvelluppillai** [comment]
Actually this was fixed for the top controls by increasing their z-index, rather than decreasing the z-index on the table header. Possibly this is a related regression still in `4.10.0` - can you confirm @Chardonneaur ?

**Comment by Chardonneaur** [comment]
@justinvelluppillai thanks, it happens within a matomo.cloud account yesterday.
