### ISSUE TITLE
plugin management no longer working

### ISSUE THREAD

**Issue by BeckeBauer** [piwik/piwik#19243]
I have re-installed matomo on a new server and (after some struggle) managed to also transfer the database to the new server. It is running but I can no longer install / activate / deactivate plugins. 

When trying e.g. to activate the plugin Log Viewer, the following is shown in the logs:

`ERROR Piwik\ExceptionHandler[2022-05-19 10:30:21 UTC] [a0182] Uncaught exception: /matomo/plugins/Login/Controller.php(196): Not available [Query: ?module=Login&action=confirmPassword&pluginName=LogViewer&nonce=aa4aa728f2d0c9885390b68c1e5b120c&redirectTo=referrer, CLI mode: 0]`

Any help is appreciated

**Comment by bx80** [comment]
HI @BeckeBauer, thanks for reaching out. It's hard to know what is happening based on that error message, it's meant to be shown when the login session could not be verified. Could you describe in detail what happens when you try to activate a plugin? When you try to activate the plugin are you shown a 'confirm password' prompt? 

It could also be worth checking the diagnostics page to see if there are any warnings or errors with the new server configuration.

**Comment by BeckeBauer** [comment]
When I try to activate a deactivated plugin or vice versa, I get the white page with `An error occurred Not available Go back - Go to Matomo` without any "confirm password prompt"

When I run the diagnostics within matomo, the only error shown is `Unable to execute check for https://mydomain.local/tmp/: curl_exec: SSL certificate problem: unable to get local issuer certificate. Hostname requested was: mydomain.local `
(I use matomo to analyse the server logs and do not need it to be accessible from the internet so that I use a self-signed certificate)

When I try to run the diagnostics via console, I get the following error
`ERROR [2022-05-20 08:58:02] 3645  Uncaught exception: /matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(549): Command "generate:system-check" is not defined.`

**Comment by sgiehl** [comment]
@BeckeBauer The commands for running the system checks would be `diagnostics:run`

**Comment by BeckeBauer** [comment]
sorry, was not aware of the right command. I got the following result:

```
INFO [2022-05-20 19:13:25] 3111  Unable to test if mod_pagespeed is enabled: the request to http://unknown/console?module=Installation&action=getEmptyPageForSystemCheck failed
Required Private Directories:
	- WARNING Unable to execute check for https://tracking.tracking.mydomain.local/config/config.ini.php: curl_exec: Could not resolve host: matomo.mydomain.local. Hostname requested was: matomo.mydomain.local
	- WARNING Unable to execute check for https://tracking.tracking.mydomain.local/tmp/cache/tracker/matomocache_general.php: curl_exec: Could not resolve host: matomo.mydomain.local. Hostname requested was: matomo.mydomain.local
	- OK All private directories are inaccessible from the internet.
Recommended Private Directories:
	- WARNING Unable to execute check for https://tracking.tracking.mydomain.local/tmp/: curl_exec: Could not resolve host: matomo.mydomain.local. Hostname requested was: matomo.mydomain.local
	- WARNING Unable to execute check for https://tracking.mydomain.local/tmp/empty: curl_exec: Could not resolve host: matomo.mydomain.local. Hostname requested was: matomo.mydomain.local
	- WARNING Unable to execute check for https://tracking.mydomain.local/lang/en.json: curl_exec: Could not resolve host: matomo.mydomain.local. Hostname requested was: matomo.mydomain.local
	- OK All private directories are inaccessible from the internet.
Forced SSL Connection: WARNING We recommend using Matomo over secure SSL connections only. To prevent insecure access over http, add force_ssl = 1 to the General section in your Matomo config/config.ini.php file.

Attention: Doing this without having set up a SSL certificate for using HTTPS will break Matomo.
3 warnings detected
```

**Comment by sgiehl** [comment]
@BeckeBauer I don't think those warnings should cause your problems.
Does enabling the plugin on command line work? e.g. `./console plugin:activate LogViewer`

**Comment by BeckeBauer** [comment]
works flawless this way 
```
/web/matomo$console plugin:activate LogViewer
Activated plugin LogViewer
```
I noticed that actions requiring password confirmation seems not to work. For instance, when I try to change my password (which is not working), the error log shows:

`Uncaught exception: /web/matomo/core/Nonce.php(236): Security token could not be verified. [Query: ?module=UsersManager&action=recordPasswordChange&idSite=7&period=day&date=yesterday&embed=0&activated=, CLI mode: 0]`

**Comment by sgiehl** [comment]
@BeckeBauer Which version of Matomo are you using and are you maybe using any additional login plugins?

**Comment by BeckeBauer** [comment]
I`ve been using the official release channel, currently vers. 4.10.1 
But I gave up and installed a clean database (I assume that something went wrong when I transferred the database to the new server) - so I am closing the issue; thanks for your input
