### ISSUE TITLE
Fix adjacent elements to dashboard-dropdown-menu-modal overlapping on narrower screens

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19254]
## A user reported:

_We found an issue on the Matomo Page Stats Dashboard. When you click on the Dashboard button, the submenu is under lapping of the date bar and channel types bar._ 

![bug-modal-is overwritten](https://user-images.githubusercontent.com/22874146/169705478-fc139722-6a93-4642-a53f-22a4774715f4.png)

## I confirmed 

For a narrow screen, some of the divs escape from Visits in Real-time widget under these conditions:
* screen width 800 to 630 px roughly
* Firefox or Chromium browser, in Linux Ubuntu 
* The widget was "Visits in Real Time"
* my Matomo version was  4.10.0

![tatll-overflow div](https://user-images.githubusercontent.com/22874146/169705686-051d8975-7ac3-481a-abf0-057ca3fbd1a4.png)

**Comment by peterhashair** [comment]
Thanks for providing this bug, I can confirm this exists on the current Matomo Version, our product team will prioritize that task.
