### ISSUE TITLE
Email report delete all feature

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#19253]
It would be nice to have a feature in order to delete all the email report created. Currently this feature is not implemented within the API.

**Comment by bx80** [comment]
@Chardonneaur Thanks for the suggestion. Just to understand this a little more, would you see this as being per user feature or an super user option affecting all users?

**Comment by Chardonneaur** [comment]
@bx80 I think we should provide both options. For example, a regular user may want to clean his account and a super user may want to clean the full instance.

**Comment by mattab** [comment]
Thanks for creating the issue. If i understand correctly, this is a request for a button to delete all email reports at once? Because currently it's possible to delete email reports one by one, then i suppose this is an OK workaround. could you please comment & reopen if i misunderstood.

**Comment by Chardonneaur** [comment]
Positive, this is what this feature is about.
