### ISSUE TITLE
Goals conversion rate percentage not formatted properly in goals page

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#19263]
I noticed this in the Funnels UI tests:

![image](https://user-images.githubusercontent.com/125140/170135859-59005b47-6beb-4a83-812d-193e11f654ce.png)

The conversion rate is not converted into a percent. I couldn't find a combination of query parameters that would turn it into a percentage, and the URL seems to be the same as in 4.5.0, so I assume it's not related to Vue.

CC @sgiehl

**Comment by sgiehl** [comment]
That seems to be a regression from #19057
@bx80 could you have a quick look on that one, so we can fix it before rc release of Matomo 4.11
