### ISSUE TITLE
Can't install purchased plugins: Action 'installAllPaidPlugins' not found in the module 'CoreHome'

### ISSUE THREAD

**Issue by mattmary** [piwik/piwik#19278]
The form leads to an unknown action.

## Expected Behavior

When clicking on the button to install the purchased plugins, it installs the plugins.

## Current Behavior

When clicking on the button to install the purchased plugins, we have an error page.

## Steps to Reproduce (for Bugs)

1.Go to marketplace, browse.
2.Click on the button install purchased plugins
3.Click on the install and activate x purchased plugins

## Your Environment

* Matomo Version: 4.10.0
* PHP Version: 8.0.14
* Server Operating System: Apache
* Additionally installed plugins:

* Browser:Firefox 100
* Operating System:Ubuntu
![Screenshot from 2022-05-27 07-44-36](https://user-images.githubusercontent.com/86216084/170566312-28260e78-39e6-4245-953c-56688173335c.png)
![Screenshot from 2022-05-27 07-45-03](https://user-images.githubusercontent.com/86216084/170566574-7b03daa4-e02f-4924-8f14-e8486d7b64f8.png)
![Screenshot from 2022-05-27 07-45-24](https://user-images.githubusercontent.com/86216084/170566349-08d2fb19-04f2-49f8-9311-0f6bf7b8f41d.png)
-8949-c5e891474cc2.png)

**Comment by bx80** [comment]
Looks like the destination url from from confirmation modal might be defaulting to CoreHome instead of Marketplace? https://github.com/matomo-org/matomo/blob/c75dcf71b75d1112e3e00fda602fd0e7a17a54f7/plugins/Marketplace/vue/src/LicenseKey/LicenseKey.vue#L158-L160

**Comment by justinvelluppillai** [comment]
@bx80 @diosmosis is this a vue related regression?

**Comment by diosmosis** [comment]
@bx80 @mattmary does this change solve the issue: https://github.com/matomo-org/matomo/compare/vue-marketplace-action-url?expand=1 ?

**Comment by bx80** [comment]
@diosmosis That change solved the issue for me :+1:

**Comment by diosmosis** [comment]
Created https://github.com/matomo-org/matomo/pull/19288
