### ISSUE TITLE
UI/UX regressions in global website settings

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#19303]
While developing another feature I came across some regressions in the global website settings form.
Might be possible they also exists in the general settings form:

- When the API request to store the data returns an error (e.g. invalid excluded ip), the error is logged in the browser console and is displayed at the top of the form. But the loading bar above the save button remains and the save button stays disabled. That makes it impossible to simply fix the problem and save it again.

- All text input areas behave a bit strange when you try to type some characters somewhere in between. If there is already text in the box and you try to type something e.g. in the front, the cursor will automatically jump to the end. This makes it hard to change anything.

@diosmosis I assume both are vue regressions. Could you check and fix them?

**Comment by diosmosis** [comment]
@sgiehl I can't reproduce the second issue, can you provide a browser/os and possibly a video?

**Comment by sgiehl** [comment]
@diosmosis sorry for the delay, that one somehow slipped through 🙈 

I'm still able to reproduce the second one on locally on Windows using Chrome, Firefox or Edge but also on OSX / Chrome using BrowserStack.

https://user-images.githubusercontent.com/1579355/174819590-79ac7e38-3e42-4ebb-9baa-ed8a17441d42.mp4

**Comment by diosmosis** [comment]
:+1: I can reproduce now, and have a fix I'll put up soon.
