### ISSUE TITLE
Display recent visits NOT only chronologically

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19304]
Interface Enhancement Idea.

How it is now:  the pages visited in the last half hour, are arranged chronologically

How I wish it were:   
_"I would really like to have a synthetic overview of the pages visited in the last half hour, 
with a ranking by popularity of the page"._.. In GA they can do this.   _"The Google Analytics view allows me to see the instantaneous effect of a mention on social networks."_

From a user request sent to Contact Matomo.

**Comment by sgiehl** [comment]
I guess this will actually be included in #19134
