### ISSUE TITLE
Handle 429 HTTP response in the UI

### ISSUE THREAD

**Issue by JasonMortonNZ** [piwik/piwik#19317]
We need to adjust the UI to handle a 429 HTTP response happening. At present a generic error message will be displayed when someone encounters this issue. It would be good to implement a custom HTML error page for this response type.

This is required to complete the rate limiting feature (dev-2437) on cloud and will improve uptime, cloud performance and customer experience.

**Comment by sgiehl** [comment]
Looks like a duplicate of #19233
