### ISSUE TITLE
Show conversion attribution in visits log & profile

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#19328]
## Summary

With #19269 our `Live.getLastVisitsDetails` API now also contains details about which referrer was attributed to a conversion.
This information should also be shown in the visits log & visitor profile at least when hovering a conversion.

![image](https://user-images.githubusercontent.com/1579355/172865651-c11789d4-42e8-4b35-ae0a-7e56e35b9a84.png)

As the conversion attribution might differ from the visit attribution, we could maybe highlight the conversion attribution, if it differs from the visit.

**Comment by Chardonneaur** [comment]
@sgiehl thank you, i have a client who is asking exactly this feature.

**Comment by mattab** [comment]
Yes, this is causing some confusion indeed 👍 
as this would be a quick fix, it'd be valuable to include it soon. eg. Maybe in the tooltip we could show a clear text like `This [Ecommerce|Goal] conversion has been attributed to the Acquisition Channel: <strong>XXXXXXX</strong>` where XXXX might be `Search Engine - Google ($keyword_here)` or the list of all campaign parameters (like currently shown in the Visits Log where we see the parameter names & values)
