### ISSUE TITLE
Allow IP anonymisation to be set on a site by site basis

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19320]
A user asked:

"If I want to block for some sites two bytes and for other sites only one byte ... 
...I have to set up a second server and distribute the sites according to this setting" 

It would be great to allow differing privacy settings for each website, in this case, the IP Anonymization.

**Comment by Findus23** [comment]
I think this is the same as https://github.com/matomo-org/matomo/issues/6653 and the linked issues there.
