### ISSUE TITLE
Tracking Failures not working with invalid siteId

### ISSUE THREAD

**Issue by uxfrank** [piwik/piwik#19339]
We tried to validate the tracker failures feature by intentionally changing the siteId in our snippet to an invalid siteId (e.g. "-1", "2000", removing the siteId, etc). 

None of these changes seemed to trigger the Logfailure() in Visit.php . 

Is there a setup step that was missed? 

## Expected Behaviour
If a snippet has an invalid siteId, than a tracker failure should be logged in the admin diagnostics. 

## Current Behaviour
No tracking failures are logged.

## Steps to Reproduce (for Bugs)
Within the javascript tracking code change the valid setSiteId to something invalid
e.g. 
from
    _paq.push(['setSiteId', '1']);

to
    _paq.push(['setSiteId', '2000']);

browse to:
/index.php?module=CoreAdminHome&action=trackingFailures&idSite=1&period=day&date=today

## Context
We're planning on using the on-premise version of Matomo and would like to have some built in tracker status monitoring.

## Your Environment
On-premise, fully installed, no issues with the installation

* Matomo Version: 4.9.1
* PHP Version: 7.4.29

**Comment by bx80** [comment]
Hi @uxfrank, thanks making contact. 

Any `siteId` less than 1 will be ignored, so setting the `siteId` to -1 will not log any tracking errors. 
A `siteId` of 2000 should record a tracking failure (assuming you don't have a site with that id). I've tested this and a tracking failure was logged, so it doesn't seem to be a general bug.

If the visit is excluded for some reason (excluded IP, user agent, parameters,) then no tracking failure will be recorded, so it would be worth checking your site exclusions (Measurables > Manage) to see if there is anything that would cause your test visit to be excluded.
