### ISSUE TITLE
Goals cannot change back "Allow multiple conversions per visit" to "Default"

### ISSUE THREAD

**Issue by AltamashShaikh** [piwik/piwik#19331]
Created 1 new goal and saved it
Later changed the "Allow multiple conversions per visit" option to "Allow Goal to be converted more than once per visit" from "default"  and submit the form and after that try to edit the form and try resetting "Allow multiple conversions per visit" to "default" and  you cannot change the option

## Expected Behavior
Toggling of ""Allow Goal to be converted more than once per visit" option should work

## Current Behavior
Once you set the  "Allow multiple conversions per visit" to "Allow Goal to be converted more than once per visit" you cannot change back to "Default"

## Steps to Reproduce (for Bugs)
1. Create new Goal and save it
2. Change the Allow multiple conversions per visit" to "Allow Goal to be converted more than once per visit" and try to change back to "Default" and you won't be able to do so

No errors in console.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by tarasowski** [comment]
Hey folks!
I'm having the same issue. When do you think 4.11.0 gets released?

Thanks,
Dimi

**Comment by sgiehl** [comment]
@tarasowski we are planning to release it this or next week.

**Comment by tarasowski** [comment]
Thanks Stefan! It creates a lot of issues for goal tracking.
