### ISSUE TITLE
SMTP passwords with ampersand are saved as &amp;

### ISSUE THREAD

**Issue by fritzmg** [piwik/piwik#19340]
## Expected Behavior

When saving an SMTP passwords that contains an ampersand (`&`), it should be saved as such, otherwise authentication will not work.

## Current Behavior

Ampersands in SMTP passwords are saved as `&amp;`

## Steps to Reproduce (for Bugs)

1. Go to System - General settings - Email server settings.
2. Fill out the details, with a password containing the `&` character, like `foo&bar`.
3. Check the `config/config.ini.php` - it will say `password = "foo&amp;bar"`

## Your Environment

* Matomo Version: 4.10.1
* PHP Version: 7.4.28
* Server Operating System: Debian 10

**Comment by peterhashair** [comment]
@fritzmg thanks for reporting this, our product team will prioritize this bug

**Comment by AaronClifford** [comment]
I've looked into this, I believe this is correct behavior as it uses the **sanitizeInputValues** function on save as it's a user inputted value, then when it's used it's likely **unsanitizeInputValue** is used as it is with other user inputted values in other areas.

**Comment by AaronClifford** [comment]
Left as a draft as currently unable to test

**Comment by fritzmg** [comment]
> then when it's used it's likely unsanitizeInputValue is used as it is with other user inputted values in other areas.

That's currently not the case though - but I see you already created a PR to fix this 👍

**Comment by sgiehl** [comment]
@fritzmg Are you actually having any trouble with the `&` in your password?
Looking through the code it seems to be on purpose that a `&` is stored as `&amp;`, as config values are encoded when written and decoded when read (using htmlentities).

**Comment by fritzmg** [comment]
I did, yes. However in retrospect I am not sure anymore if the credentials were the actual problem. I will need to test again.

**Comment by peterhashair** [comment]
@fritzmg I believe this is invalid, close the issue for now. If the issue appears again, feel free to reopen this issue.
