### ISSUE TITLE
Fix FAQ links using # in the link no longer working

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#19346]
refs DEV-2838

With the recent KB system update any FAQ links that use a # anchor link no longer link to the correct FAQ. For example https://matomo.org/faq/general/#faq_125  just links to the general page, but https://matomo.org/faq/general/faq_125 works as expected.

There are several FAQ links in the codebase that are now effectively broken. 
Eg. there is this one: https://github.com/matomo-org/matomo/blob/2b35b46a0988f8c3b6f848c59be8d7d918965a52/plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig#L54
that is supposed to go to https://matomo.org/faq/how-to/faq_111/

But because of the # in the faq link it goes to the KB homepage: https://matomo.org/guides/#faq_111

**Comment by bx80** [comment]
Just to clarify, the task here is to update all FAQ links in core that use `#` in URL so they work again.
