### ISSUE TITLE
France regions 20% of unknown region

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#19359]
When using the Maxmind database, 20% of the cities are not matched with a region, for example: Dinan, France - Deauville, France

**Comment by peterhashair** [comment]
Thank you for reporting this, our team is looking for the latest address and IP updates

**Comment by Chardonneaur** [comment]
@peterhashair : thank you, that's also happening within matomo.cloud

**Comment by sgiehl** [comment]
@Chardonneaur Are you able to identify an IP where that not reported correctly? Or maybe lookup one of those visitors in the log_visit table, if the location_region field is empty or not?

**Comment by heurteph-ei** [comment]
Hi @Chardonneaur 
Is it the same problem as #19329?

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/problem-with-geography-cities-regions/47960/4

**Comment by sgiehl** [comment]
Closing this one in favor of https://github.com/matomo-org/matomo/issues/20527
