### ISSUE TITLE
Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in app/plugins/Diagnostics/Diagnostic/PhpVersionCheck.php on line 66

### ISSUE THREAD

**Issue by mattmary** [piwik/piwik#19352]
there is a deprecated warning on php8.1 for a variable is null and should be a string

## Expected Behavior

No warning displayed when displaying the system report page within the wordpress plugin.

## Current Behavior

![Screenshot from 2022-06-14 13-11-09](https://user-images.githubusercontent.com/86216084/173472521-47260095-e1dd-458b-9ae3-395f6d9a2456.png)
A warning is displayed when running with php8.1 the system report page

## Possible Solution

define the $piwik_minimumPHPVersion variable as global in the app/core/testMinimumPhpVersion.php solves this issue.

## Steps to Reproduce (for Bugs)

1.install the wordpress plugin 
2.switch to php8.1 version for your apache
3.open the wp-admin/admin.php?page=matomo-systemreport url 
4.views the warning
5.add global $piwik_minimumPHPVersion; in line 25 of the app/core/testMinimumPhpVersion.php
6. refresh the page
7. see the warning message has disappeared

## Your Environment

* Matomo Version: 4.10.0
* PHP Version: 8.1.7
* Server Operating System: Apache 2.4
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by mattmary** [comment]
another related warning

Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in app/core/CliMulti/CliPhp.php on line 76

**Comment by sgiehl** [comment]
@mattmary I'm not seeing this error when using Matomo the "normal" way on PHP 8.1.

**Comment by mattmary** [comment]
@sgiehl when you say the normal way is matomo on premise?

**Comment by mattmary** [comment]
refs https://github.com/matomo-org/matomo-for-wordpress/issues/614

**Comment by sgiehl** [comment]
Yes. On premise

**Comment by mattmary** [comment]
in php8.1 @sgiehl ?

**Comment by sgiehl** [comment]
tested it with 8.1.5

**Comment by mattmary** [comment]
hi @sgiehl 

I've tried different ways to fix this issue. the only one which work is to define as global the variable $piwik_minimumPHPVersion in this file. which impact would it have to do so?

**Comment by sgiehl** [comment]
That variable actually should be global. But maybe that isn't the case as WordPress includes Matomo 🤔

**Comment by justinvelluppillai** [comment]
@sgiehl yes it looks like due to the way wordpress is including matomo it needs a workaround here. Any advice on whether we can apply @mattmary 's fix to core would be appreciated, or alternative ways to work around so he doesn't have to make this change every release for wordpress.

**Comment by sgiehl** [comment]
@justinvelluppillai I don't have Matomo for Wordpress set up, so I'm not able to say if there would a smarter solution. But adding a global keyword should not produce any problems I guess.

**Comment by sgiehl** [comment]
@mattmary Is this something we still need to change in core, or is the fix for wordpress a suitable solution and we can close this one?

**Comment by mattmary** [comment]
@sgiehl Sure I can fix it, but I'll have to do it each time we publish a new release. It would be definitively better if you could update the core.

**Comment by sgiehl** [comment]
@mattmary Would you mind creating a pull request for core?

**Comment by mattmary** [comment]
Hum @sgiehl 

Now with the latest branch release, I've some fatal errors:
![Screenshot from 2022-11-18 13-50-38](https://user-images.githubusercontent.com/86216084/202591184-bbfe023e-217c-4ad3-908e-d620e1722cbc.png)
I guess I'll have to fix these updates first when we'll deploy the 4.13 release.

So I would suggest postponing this fix in the release after the 4.13.
