### ISSUE TITLE
Event Appearing as Custom Variable in Matomo Dashboard

### ISSUE THREAD

**Issue by aashishgoyal2000** [piwik/piwik#19365]
I am sending events using Piwik Tracker with the sendBulkRequestAsync method, and the event is appearing as Custom Variable in the dashboard. It should appear in the events list.

{
    "eventName":"Name: ",
    "eventAction":"Action",
    "eventCategory":"Category",
    "eventValue":null,
    "eventTime":1655388962709
}

Events are being raised from Spring Boot Java using Piwik Tracker.
Dependency Used:
        <dependency>
            <groupId>org.piwik.java.tracking</groupId>
            <artifactId>matomo-java-tracker</artifactId>
            <version>1.7</version>
        </dependency>

**Comment by peterhashair** [comment]
Link this issue to [here](https://github.com/matomo-org/matomo-java-tracker/issues/60) since is duplicated
