### ISSUE TITLE
Fix date range handling to prevent evolution graph display being confused when changing the period

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#19393]
When we change the period of a graph with the "green icon calendar" for example changing from Day to Week, and then when we are coming back to a Day period, the graph is getting confused and not coming back to its original state.
For example, if you choose June the 22th, then you click on the green icon calendar and select week and then select back the day period then instead of coming back to June the 22th it will be June the 26th... rather than June the 22th.
I checked this out on https://demo.matomo.cloud.

**Comment by sgiehl** [comment]
Hi @Chardonneaur 
Thanks for the report. I was able to reproduce that. It seems for some reason the `date` parameter in the request seems to be changed to the last day of the period in that case. 
I'll try to set up a quick fix for that.
