### ISSUE TITLE
Fixes reporting menu category doesn't close when clicking on it

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19419]
I believe this might be a regression. 

When I click on eg `Behaviour` then it doesn't close the menu 

<img width="332" alt="image" src="https://user-images.githubusercontent.com/273120/176106889-3e1979cc-77e6-409e-a9a0-3852a160fd9a.png">

This causes me having to scroll down to get to the other menus and can't switch easily anymore. The admin reporting menu still works.

**Comment by sgiehl** [comment]
Yes. That seems to be a regression from the vue migration. It seems currently always one menu item is visible, which is either the category currently selected or another category the user toggled through click. It's not possible to hide all categorie menus anymore.

ping @diosmosis could you have a look at that?
