### ISSUE TITLE
Incorrect usage data for Malaysian states on Visitors Map widget + clicking on Malaysia shows different states 

### ISSUE THREAD

**Issue by avimaymon** [piwik/piwik#19411]
## Expected Behavior
1. The states of Pulau Pinang and Perlis under Malaysia should show correct usage data
2. Clicking on Malaysia should show the state of Malaysia

## Current Behavior
1. No usage data for these two states while on the Cities view but on Regions view we can see that there is usage from cities of these two states
2. Clicking on Malaysia shows other states e.g. China and Russia, to see Malaysia the user needs to click on Australia

## Steps to Reproduce (for Bugs)
The bugs are clearly depicted here
https://www.screencast.com/t/LKiBvqIe2D

## Your Environment
* Matomo Version: 4.9.0
* Browser: Microsoft Edge
* Operating System: Windows 10

**Comment by peterhashair** [comment]
@avimaymon Thank you for reporting this, our team is looking for a map and IP updates, once that's updated should fix it.

**Comment by avimaymon** [comment]
@peterhashair Thanks for your reply, I have to ask if there is a rough estimate to when it will be fixed so I can inform my clients that are having a hard time with this issue? perhaps some workaround? thanks

**Comment by sgiehl** [comment]
@avimaymon I've created https://github.com/matomo-org/matomo/pull/19415, which should address the second issue. So clicking on Malaysia will no longer show the asia map, but the oceania one. Which is also displayed when clicking on australia.
This fix should be included in Matomo 4.12.

Regarding the incorrect region data: Which geo location database are you using?
Are those regions listed in the region report at all, or are they only not shown on the map?

**Comment by avimaymon** [comment]
@peterhashair Your help is much appreciated, thanks
Regarding the geo location database - we're using DBIP/GeoIP (Php) which was last update less than a week ago

**Comment by sgiehl** [comment]
@avimaymon Is it the free or the paid DBIP database? The free database make some problems with detecting the regions correctly. See #19329 for more details.

**Comment by avimaymon** [comment]
@sgiehl The second issue was fixed after updating to 4.12 but the first one remains, 
we do use the free DBIP database, but I'm not sure it's a DBIP issue because we do get that data on the Cities view

This is how it looks on the Cities view
![1](https://user-images.githubusercontent.com/29678658/195541049-e2038f3a-2791-4001-bc9f-6020929892d1.png)
![1](https://user-images.githubusercontent.com/29678658/195542823-403a9511-82af-4b85-b44b-968017dbd772.png)

and this is how it looks on the Regions view
![1](https://user-images.githubusercontent.com/29678658/195541936-3d6e29a4-fe98-4630-88d7-c5530d8a2a60.png)
![1](https://user-images.githubusercontent.com/29678658/195543009-d30b0578-599c-496b-bcfd-00899103ff01.png)

There are different names for the first area in the two different view modes but there are adjacent so I'm not sure it's an issue
![1](https://user-images.githubusercontent.com/29678658/195541684-7c0c0b8d-3f04-4b8f-a798-634a454ea994.png)

Could it be that really small counts do not appear in the regions view?

would love your help, thanks!

**Comment by sgiehl** [comment]
I would assume it's a similar issue like https://github.com/matomo-org/matomo/issues/19329
Or the iso region code of malaysia might have changed, and we can't map them correctly.
Should be something to have a look at when implementing #11929

**Comment by avimaymon** [comment]
@sgiehl Thanks for the quick reply, if possible, I would love getting an update regarding this issue because it really bothers some clients, thanks!

**Comment by sgiehl** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/20527
