### ISSUE TITLE
Add TikTok to socical networks

### ISSUE THREAD

**Issue by DJulienD** [piwik/piwik#19458]
Hello, I saw that no TIKTOK statistics is available on matomo.
When I go the social Network area (from acquisition) I can see, Youtube , FB, Instagram... and so on... but NO TIKTOK
Could you do someting for us ?

Many thanks
Best regards

**Comment by sgiehl** [comment]
@DJulienD I'm actually not using TikTok. Is it possible to link to other websites from within TikTok in any way?
If so, I guess TikTok would appear within the list of referring websites. Is that the case?

**Comment by DJulienD** [comment]
Hello,

Thank you for your reply.

The problem is that it's not in the list of referring websites neither.

**Comment by DJulienD** [comment]
I only find in here

[image: image.png]

**Comment by sgiehl** [comment]
@DJulienD Sorry, not sure if you tried to send an image, but the email replies aren't displayed properly on github...

**Comment by DJulienD** [comment]
Ok, i understand

I can only see TIKTOK statistics in Acquisition > Campagne

**Comment by sgiehl** [comment]
@DJulienD Are you using campaign link on tiktok only? If so, that might be the reason, as a campaign kind of overwrites the referrer.

**Comment by DJulienD** [comment]
Ok I understand, but If  I don't using a campaign link, do you think I will
have TIKTOK statistics ?

I mean if i put just : www.couteauxduchef.com without UTM

Let me know, thank you

**Comment by sgiehl** [comment]
As mentioned previously, I'm not using TikTok at all, nor do I know how referrer links from there might look like.
If we know that, we can add it to the detection here: https://github.com/matomo-org/searchengine-and-social-list

Is anyone else able to see any TikTok links in the referrering websites? Or is maybe using TikTok and is able to say if TikTok hides the referrer or not?

**Comment by DJulienD** [comment]
www.tiktok.com is not in the referring website.

So tell me if it will work if the link is www.couteauxduchef.com

instead of
https://www.couteauxduchef.com/?utm_source=tiktok&utm_medium=social&utm_campaign=homepage
with the link bit.ly/plusquedescouteaux.

Thank you
