### ISSUE TITLE
Can't create/edit goals with write access

### ISSUE THREAD

**Issue by mattmary** [piwik/piwik#19463]
Hi, I can't create or edit a goal with my account on our innocraft account. My account has the write permission.

## Expected Behavior

I should be able to edit or create a new goal.

## Current Behavior

Can't edit goals: I can just list them.

## Steps to Reproduce (for Bugs)

1. open /index.php?module=CoreHome&action=index&idSite=12&period=day&date=yesterday#?idSite=12&period=day&date=yesterday&category=Goals_Goals&subcategory=Goals_ManageGoals
2. view the goals list
3. Can't edit or create a new goal

## Your Environment

* Matomo Version: 4.10.1 (the version on web.innocraft.cloud)
* PHP Version: don't know
* Server Operating System: don't know
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by peterhashair** [comment]
@mattmary thank you for reporting this, can you check if the write user has the write access to site id = 12 in your case.

**Comment by mattmary** [comment]
Hi @peterhashair 

I have only view access on this site. I close this issue
