### ISSUE TITLE
Fixes occasional website chooser drodown not working

### ISSUE THREAD

**Issue by KarthikRaja1388** [piwik/piwik#19462]
When navigating through some reports and you would like to view the same report for another website, website chooser dropdown does not work anymore, you may need to reload the page to get the dropdown functionality

For example: viewing a Heatmap for website 1 and would like to view Heatmaps for website 2, it is not possible to choose it from dropdown, as the dropdown doesn't work

## Your Environment

* Matomo Version:
* PHP Version: 8.1.1
* Server Operating System: Ubuntu 20.04
* Additionally installed plugins:

* Browser: Firefox 101.0.1
* Operating System: Ubuntu 20.04

**Comment by sgiehl** [comment]
@diosmosis could you please check if that is vue related?

**Comment by diosmosis** [comment]
I'm not able to reproduce this. @KarthikRaja1388 can you provide screenshots or a way to reproduce on demo/demo2?

**Comment by sgiehl** [comment]
@diosmosis maybe unrelated to this one, but for me the website selector in the top controls, doesn't show the correct site as selected. When switching to another site, it loads the site, but the selector always shows the first site in the list as selected.

**Comment by diosmosis** [comment]
@sgiehl I can see this issue, created a fix here: https://github.com/matomo-org/matomo/pull/19483
