### ISSUE TITLE
Can't install TagManager plugin because table _tagmanager_container is missing

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#19474]
## Expected Behavior

I wanted to enable TagManager plugin by issuing console command:
`php console plugin:activate TagManager`
Activation didn't outputted any error message, logging didn't traced any error.

## Current Behavior

After activation, website frontend dies with error 500.
Also console command _tagmanager:regenerate-released-containers_ died:

```bash
bash-4.2$ php console tagmanager:regenerate-released-containers
ERROR [2022-07-06 11:06:07] 2290  There was an error while regenerating container releases: /var/www/html/matomo_4-9-1/libs/Zend/Db/Statement/Pdo.php(236): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.piwik_tagmanager_container' doesn't exist [Query: , CLI mode: 1]
Done
Error: error or warning logs detected, exit 1
```

Same error while browsing web ui. 

After installation, there isn't any table named `*_tagmanager_*`

## Steps to Reproduce (for Bugs)

Probably it's working on a fresh installation, but our installation was upgraded to 4.9.1 since Matomo was Piwik 2.x.x

## Context

https://forum.matomo.org/t/unhandled-exception-while-enabling-plugin-tagmanager/45981/

## Your Environment

* Matomo Version: 4.9.1
* PHP Version: 7.3
* Server Operating System: Centos7

**Comment by sgiehl** [comment]
@tassoman You can try the following steps to fix this:
- Deactivate TagManager plugin using:
  `./console plugin:deactivate TagManager`
- Then remove the plugin from the list of installed plugin in the config.ini.php file under the `[PluginsInstalled]` header and remove the line that contains:
  `PluginsInstalled[] = "TagManager"`
- Then run the `core:update` command:
  `./console core:update`
- Then reactivating the TagManager plugin:
  `./console plugin:activate TagManager`

**Comment by tassoman** [comment]
Flawless!
I managed to get it working! Such a cheat! 🤣

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/unhandled-exception-while-enabling-plugin-tagmanager/45981/8
