### ISSUE TITLE
matomo tracking noise (bots)

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#19484]
Hello,

matomo tracks bots massivelly and waste my database full with it.

I have write a question in the forum, but only a hint to a plugin is answered.

https://forum.matomo.org/t/field-report-matomo-tracking-noise-bots/46476

matomo had a massivelly problem with bot tracking. In my question, i have only mentioned my brandnew domains and not the list of all my older domains. And i write only for onepager. Also all infos are per one page (onepager). It is multiplicate for multi-page websites.

Please help!

**Comment by justinvelluppillai** [comment]
Hi @matomoto probably the Tracking Spam Prevention plugin is what you are looking for - https://plugins.matomo.org/TrackingSpamPrevention

I will close this issue here now, further discussion can be had in the forum.
