### ISSUE TITLE
Mobile device heat map shows wrong Above the fold area

### ISSUE THREAD

**Issue by ruredi** [piwik/piwik#19503]
https://drive.google.com/file/d/1zBODokZ9kz8gdAWIYwlaZ7ImTXKHBBgO/view?usp=sharing

**Comment by bx80** [comment]
@ruredi Thanks for reaching out, could you provide a bit more information about the issue?

I might be misunderstanding the screenshot you've provided, but the number 355 on the heat map header is the number of mobile devices sampled, the "above the fold" marker line is the average height of the fold on those sampled devices in pixels. So 355 mobile devices visited the page and they had an average fold height on 353px.

**Comment by sgiehl** [comment]
Closing this issue as no further information has been provided. Also the image is meanwhile unreachable, which makes it impossible to understand the reason.
