### ISSUE TITLE
User Keyword Search

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#19509]
When I am writing the FAQ, I found the keyword search under user manage is quite bugged. I guess maybe we need to add a debounce on the key-up events.

 

https://user-images.githubusercontent.com/3783072/178173781-6bd205c5-142f-436f-8fa1-e82ecc9df364.mp4

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.11
* PHP Version: 8.0
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
probably a vue regression. ping @diosmosis

**Comment by diosmosis** [comment]
A regression caused by https://github.com/matomo-org/matomo/pull/19375, the nextTick() is not enough to execute the code after the property emit finishes. Not sure yet what a fix would be.

**Comment by sgiehl** [comment]
@diosmosis would that be fixed with removing angular js? Or would that issue remain?

**Comment by diosmosis** [comment]
@sgiehl it will remain, it seems to be a Vue reactivity issue.

**Comment by sgiehl** [comment]
This one seems to be fixed meanwhile. At least it works for me on latest 4.x-dev.
@peterhashair Are you able to confirm that it works for you as well?

**Comment by peterhashair** [comment]
@sgiehl yes it works
