### ISSUE TITLE
Marketplace plugin not found, wrong notification message

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#19521]
When you go marketplace, and search for a plugin name not exist, it will return an error screen. See screen capture.

https://user-images.githubusercontent.com/3783072/178640773-5acb559f-80bd-496d-bcc1-2de66a20f0a6.mp4

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.11
* PHP Version: 7.4
* Server Operating System: Valet
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
@peterhashair I'm not able to reproduce that locally. Are you maybe able to give some more details on the request that is failing?
But while testing I found another regression, which will be fixed with https://github.com/matomo-org/matomo/pull/19529.

**Comment by peterhashair** [comment]
@sgiehl close the ticket, sorry I was on development `enabled=1`.
