### ISSUE TITLE
API Language depends on user language.

### ISSUE THREAD

**Issue by ClientCrash** [piwik/piwik#19520]
## Expected Behavior
API Language should never change. This breaks systems.

## Current Behavior
If the user has a different language, for example German, the language of API responses changes.

## Possible Solution

It should be completely removed of if some people depend on it it should be a toggle that is off by default. 

## Context
The API being dependent on users and their language settings created issues in our production environment.

## Your Environment

* Matomo Version: 3

**Comment by bx80** [comment]
Hi @ClientCrash, thanks for reaching out. Sorry to hear that this behavior caused an issue for you.

The API has an optional [language](https://developer.matomo.org/api-reference/reporting-api#optional-api-parameters) parameter, this can be set on API requests so the same language is always used to give consistent responses.

Changing the API to ignore users language by default could cause problems for existing API usage. We also can't assume that every user understands English, it seems reasonable that if a user has already indicated that they want to use Matomo in a specific language then API responses should by default be served in that language and not a different language that the user might not be able to comprehend. I hope that makes sense :slightly_smiling_face:
