### ISSUE TITLE
Space missing in invite users email

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#19534]
in the email with subject `????? sent you an invite to join Matomo Analytics for ?????.` 

Got this text in the email body: 
`Notes:If you were not expecting this invitation, you can ignore this email. If root is sending you too many emails, you can block them or report abuse. The invitation automatically expires in 7 days.`

Expected a space after `Notes:`:

`Notes: If you were not expecting this invitation, you can ignore this email. If root is sending you too many emails, you can block them or report abuse. The invitation automatically expires in 7 days.`

**Comment by peterhashair** [comment]
Hi, @mattab thank you for pointing that out, updated in PR https://github.com/matomo-org/matomo/pull/19535.

**Comment by sgiehl** [comment]
@peterhashair If you work on issues (and even create PRs) it would be helpful to assign the issue to you and add a milestone if possible.
