### ISSUE TITLE
Conflicting informations about Visit duration

### ISSUE THREAD

**Issue by utrautmann** [piwik/piwik#19533]
My question relates to visitors that have only visited one page and taken no further action and where no heartbeattimer is used.

Here https://matomo.org/faq/how-to/faq_21824/ is written:
**When your visitor views only one page in the website, the “Visit” duration will be set to a default of 10 seconds**

and here https://matomo.org/faq/how-to/faq_21158/
**when the visitor views only one page view, the “Time on Page” will be 0 seconds and the “Visit duration” will be 10 seconds.**

and here is written:
https://developer.matomo.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page
**when the visitor views only one page view, the "Visit duration" will be 0 second.**

It seems to me that the third statement is correct (0 second).
Otherwise it would not be possible for such low values to appear here.
![grafik](https://user-images.githubusercontent.com/25771066/179009997-945dfa60-8781-4fa8-89ee-8ead7304f904.png)
![grafik](https://user-images.githubusercontent.com/25771066/179010474-7e0a5cbc-0835-426d-a372-690027836c03.png)

**Comment by sgiehl** [comment]
I think we might actually have changed that behavior somewhen in the past. But can't remember when or why. Maybe with introducing the HeatBeat 🤔  @tsteur can you remember?
But I think when not using HeatBeat `0s` should be default.

**Comment by tsteur** [comment]
I don't remember but looking at the code I can see there is a config `default_time_one_page_visit` that is set to 0s by default. So as part of this issue we should correct the wrong documentation.

**Comment by sgiehl** [comment]
Seems that had been changed back in 2010. I have updated the mentioned pages above and also mentioned that changing `default_time_one_page_visit` can be used to set another default visit duration
