### ISSUE TITLE
Update vendor lib szymach/c-pchart to latest version

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#19546]
## Summary

The vendor lib `szymach/c-pchart` released a new update `3.0.14`.
Using this new version the images generated by ImageGraph plugin changed and are looking a bit misplaced. Some numbers are even placed partially outside the viewport. 

It fixes a couple of PHP 8.1 deprecation notices by casting a couple of variables to integer. Maybe this causes the numbers to be calculated a bit differently.

We need to investigate if we can provide a fix for the lib, so our graphs look better again, or if we need to adjust our graphs instead.

follow-up to #19537

**Comment by justinvelluppillai** [comment]
@sgiehl great if you can spend a couple hours at most looking into this and if it's an easy fix we can complete it in the `4.12` milestone.

**Comment by sgiehl** [comment]
created a PR upstream. Let's see if that will get merged... https://github.com/szymach/c-pchart/pull/81

**Comment by justinvelluppillai** [comment]
@sgiehl looks like it's merged already 👍🏽

**Comment by sgiehl** [comment]
Yep. Will create a PR to update the lib then.
