### ISSUE TITLE
Unable to enter plugin license key with Japanese language set

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#19551]
When a users language is set to Japanese, it's not possible to click on the input box to enter a license key for plugins.
For example:
![image](https://user-images.githubusercontent.com/20905821/180085718-b1f2cef0-121f-42a6-af3b-b044cdd18f98.png)
It seems to show that the cursor is over the link to upload a plugin, which when clicked results in this popup when plugin uploads are not enabled:
![image](https://user-images.githubusercontent.com/20905821/180085869-9acc3b67-99d5-4159-803e-f1da1a3281cc.png)
When plugin uploads are enabled, it shows the plugin upload overlay:
![image](https://user-images.githubusercontent.com/20905821/180085995-31a5c2d2-ea0c-465d-8f22-482148809026.png)

Clicking anywhere in the highlighted area brings the overlay to upload a plugin: 
![image](https://user-images.githubusercontent.com/20905821/180086195-27a533be-8099-430c-b025-7ac9d9f0cd27.png)

I've tested this on a few other languages (Arabic, Korean, Simplified/Traditional Chinese) and couldn't reproduce it there, so its possibly just the Japanese translation where this is happening.

**Comment by sgiehl** [comment]
Guess there might be a link tag not being closed correctly. Will check that quickly

**Comment by sgiehl** [comment]
This is an issue with the translation. The english source string might be a bit hard to understand, as there are some words placed within and a link. The order of placeholders for Japanese isn't correct, causing the open link tag being placed in the end.
I'll create a PR to split the source string, so no additional words are placed. Hopefully that makes it easier to translate the string.
