### ISSUE TITLE
Support Error report with in Angular framework

### ISSUE THREAD

**Issue by VincentCoucharriere** [piwik/piwik#19562]
I seems that Angular framework caches and handles "uncaught" JS error / exception : new Error('my error')
This prevents Matomo from catching & reporting these errors.
How to solve this ?
Can you please take care of this ?

## Your Environment

* Matomo Version: latest (cloud)
* Angular Version: 10+

**Comment by bx80** [comment]
Hi @VincentCoucharriere, thanks for your question. We're in the process of migrating Matomo from AngularJS to Vue.js which should resolve this issue.

Could you explain a bit about what you are trying to achieve by catching JavaScript errors? If you are experiencing a JavaScript error with Matomo cloud then I'd recommend contacting support. If you are developing a plugin or making code changes then it's possible to define an AngularJS exception handler to catch and log errors.

**Comment by heurteph-ei** [comment]
@bx80 @VincentCoucharriere, wouldn't it be about this option (in MTM):
![image](https://user-images.githubusercontent.com/79993552/183432422-29cc7531-1246-49bc-8432-8f0fcfb4f9d4.png)
?

(then this topic should be moved into the MTM project)

**Comment by sgiehl** [comment]
@heurteph-ei Guess it is a bit unclear what the issue actually was about. If it is about catching and tracking javascript errors on a website, then it might be correct here. Matomo currently appends an onError handler to track possible javascript errors.
If Angular or other frameworks might catch there errors themself and the error handler is not triggered, then Matomo currently can't track it.
But if Angular provides a possibility to hook into their error handling, one could even track the javascript error event manually.

**Comment by sgiehl** [comment]
Closing this one as there hadn't been any further activity.
We've meanwhile also released a new premium plugin for analyzing javascript errors, which might help in this manner: https://plugins.matomo.org/CrashAnalytics
