### ISSUE TITLE
Allow users on Matomo cloud to chose not to exclude the default query parameters

### ISSUE THREAD

**Issue by will-titan** [piwik/piwik#19603]
On matomo cloud, common query parameters such as utm source and others are stripped off url loggs by default, even when exporting raw data. We have the option to add more parameters to strip off but we do not have the option to show those parameters anywhere. As a user who is primarily using Matomo to collect pageview data to then analyze in a consolidated BI system, the current system forces us to rely on Matomo's attribution for each person and makes us blind to the multiple touch points an individual might have. It seems the only solution is to start making up new parameters to use instead of utm's that wont get stripped off by Matomo.

**Comment by sgiehl** [comment]
Hi @will-titan
Thanks for creating this issue. Unfortunately we are not able to help you here. Matomo itself already offers this possibility by overwriting the default parameters in config. 
Those default parameters are: https://github.com/matomo-org/matomo/blob/908ea17c764255239c4e6573189b65c637700b1f/config/global.ini.php#L941

In addition all parameters that are configured as campaign parameters will also be excluded, as they will be stored as campaign details instead.

If you really need to change the default parameters, please get in touch with our support. They might be able to change the config if needed.
