### ISSUE TITLE
Can't delete a user

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#19605]
## Expected Behavior
Should show popup and delete user.

## Current Behavior
When I try to delete a user, it seems like the confirm password modal didn't show up, leading to an error.

## Your Environment

* Matomo Version: 4.x
* PHP Version: 8.0
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
That works without problems for me. Also all UI tests covering removing a user are working correctly.

> leading to an error.

If you see an error, why don't you simply paste the error message or a screenshot here?

**Comment by peterhashair** [comment]
@sgiehl ops,sorry, it's VUE build error on mine, works on development enabled = 0
