### ISSUE TITLE
Fatal error in 4.11.0

### ISSUE THREAD

**Issue by mzch** [piwik/piwik#19602]
## Expected Behavior

Show System Check screen.

## Current Behavior

PHP Fatal error. Please see below:
https://d.pr/i/MOOMpX
https://d.pr/i/ufkG7M

## Steps to Reproduce (for Bugs)

1. Click `CHECK FOR UPDATE` for updaring to 4.11.0
2. Finish updating
3. Click `Administration` button.

## Context

Not shown System Check screen.

## Your Environment

* Matomo Version: 4.11.0
* PHP Version: 7.4.0
* Server Operating System: Debian 11.4
* Additionally installed plugins: only Cores

* Browser: Chrome 104.0.5112.79
* Operating System: macOS 12.5

**Comment by sgiehl** [comment]
Hi @mzch 
Did you maybe have the Provider plugin installed before? It seems the plugin is marked as installed, but actually not available.
Could you maybe check your config.ini.php if it contains the plugin `Provider` within the `PluginsInstalled` section?
If it does, but you don't have the plugin in the plugin directory, simply remove the line in the config.

**Comment by justinvelluppillai** [comment]
Also relevant: https://github.com/matomo-org/matomo/issues/18505

**Comment by justinvelluppillai** [comment]
Closing as answered, but please reopen and let us know if you think there is still an issue here.

**Comment by mzch** [comment]
Well, I deactivated `UserCountryMap` and `UserCountry` plugins to fix this issue...

**Comment by sgiehl** [comment]
Deactivating those plugin might not be the best approach, as it might also disable geolocation of your visitors. I'll prepare a small code change to make sure this problem can't occur in the future

**Comment by mzch** [comment]
Wow, I have a high expectation. Thanks!
