### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by miton18** [piwik/piwik#19609]
An orange message is shown on several pages, 

```
WARNING: /core/Http.php(1100): Notice - Undefined index: exclude - Matomo 4.11.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)
```

## Expected Behavior
no error message 

## Current Behavior
An error message

## Possible Solution
Comment the next line (quick fix)
https://github.com/matomo-org/matomo/blob/1ef548f5a28d08f741697fd012a3c988b3e5c8a0/core/Http.php#L1118

## Steps to Reproduce (for Bugs)
1. Use Matomo v4.11.0
2. 
## Your Environment

* Matomo Version: v4.11.0
* PHP Version: 7.4.30
* Server Operating System: Exherbo
* Additionally installed plugins:
  * LoginOIDC
* Browser: Firefox
* Operating System: Exherbo

**Comment by sgiehl** [comment]
Hi @miton18 
Could you check if your global.ini.php was correctly updated with the last update? The `exclude` option for proxy section should be defined there and thus shouldn't trigger a notice

See https://github.com/matomo-org/matomo/blob/908ea17c764255239c4e6573189b65c637700b1f/config/global.ini.php#L1109

**Comment by miton18** [comment]
in fact, I miss this one in my update process, sorry for the noise
