### ISSUE TITLE
Fix for page goals visualization showing hits instead of visits

### ISSUE THREAD

**Issue by utrautmann** [piwik/piwik#19615]
This issue is related to the new 4.11 feature described here: 
https://github.com/matomo-org/matomo/issues/2030#issuecomment-928878139

## Expected Behavior

The column "Unique pageviews" in the new report page urls in the goals section shows number of visits of this page.
Where? New report "Pages" under the "Goals by pages" category:

 

## Current Behavior
It seems the report shows simple pageviews.

Please compare the following screenshots:

The goal conversion report for page urls shows 10 unique pagevies (report Goals)
![grafik](https://user-images.githubusercontent.com/25771066/183912744-311c4641-4e97-4a49-990f-4405f6a02d9d.png)

Same result in the Goal metric table in the Behaviour-Category:
![grafik](https://user-images.githubusercontent.com/25771066/183913119-7b352069-9cb1-41b8-841c-4239774504ad.png)

The page url /anfahrt shows 6 unique pageviews (report Behaviour - pages)
![grafik](https://user-images.githubusercontent.com/25771066/183912087-7d88f4c4-4ba3-4af2-8dac-bbfd1524ef83.png)

**Comment by bx80** [comment]
@utrautmann Thanks for spotting this :+1: 

I can confirm the wrong metric is being used for the column. I've submitted a PR to correct this.
