### ISSUE TITLE
Matomo demo: Piwik reference in the Matomo ChangeLog widget

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19639]
## Expected Behavior
No more reference to Piwik...
(I tried to find another subject in the GitHub about removing all reference of Piwik, but did not found any...)

## Current Behavior
>See the latest changes in **Piwik**.

![image](https://user-images.githubusercontent.com/79993552/185159547-82e1c4c4-81cd-4ae3-b492-111b91a9c5ed.png)

## Possible Solution
Change Piwik into Matomo! 

## Steps to Reproduce (for Bugs)
1. Select a new widget in the Matomo dashboard of the demo.matomo.cloud/
1. Hover: **Add a widget **>** About Matomo **>** Matomo Changelog**
1. And See the preview

## Your Environment
https://demo.matomo.cloud/
French version

**Comment by justinvelluppillai** [comment]
We do have a relevant issue https://github.com/matomo-org/matomo/issues/12420. I will close this one in favour of that.
