### ISSUE TITLE
Invalidate report - Warning - Array to string conversion

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19638]
## Expected Behavior
No warning in report invalidation

## Current Behavior
> Hi all,
> I tried to run the invalidate report using a command line and I got this message:
> 
> `INFO [2022-08-16 13:23:08] 5512 Invalidating year periods in 2021-05-01,2021-05-31 [segment = ]…`
> `WARNING [2022-08-16 13:23:08] 5512 C:\Websites\matomo\vendor\monolog\monolog\src\Monolog\Logger.php(329): Warning - Array to string conversion - Matomo 4.10.1 - Please report this message in the Matomo forums: https://forum.matomo.org/ (please do a search first as it might have been reported already)`
> 
> Does any one know how to fix it?
> 
> Thank you
> Oswaldo

## Context
https://forum.matomo.org/t/invalidate-report-error-message/47006

## Your Environment
* Matomo Version: 4.10.1
* PHP Version: 8.0.16
* Server Operating System:
* Additionally installed plugins:

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/invalidate-report-error-message/47006/4

**Comment by sgiehl** [comment]
@heurteph-ei Do you know the exact command that was executed? Otherwise it might be hard to reproduce.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/invalidate-report-error-message/47006/5

**Comment by heurteph-ei** [comment]
```
> php /console -vvv core:invalidate-report-data --dates=2021-05-01,2021-05-31 --sites=4
```
