### ISSUE TITLE
Goal revenue cannot be set to $0

### ISSUE THREAD

**Issue by vadi2** [piwik/piwik#19642]
## Expected Behavior
Setting a goal's revenue to $0 should disable revenue tracking for it.

## Current Behavior
With the goal at $0, Matomo still counts revenue per download:

![image](https://user-images.githubusercontent.com/110988/185338330-3f8c01db-a771-4fa8-b7a6-152e99eacb74.png)

## Context
Running an open-source project where no income is made from downloads. I'd like to make the dashboard be completely public, but cannot right now as it would be misleading folk.

## Your Environment

* Matomo Version: 4.11.0

**Comment by sgiehl** [comment]
Hi @vadi2 
Thanks for creating this issue. The revenue value you are able to configure in the goal settings is actually only a default value. It is always possible to send a custom value when the goal is being tracked (in case that's done manually). So even if it's configured to `0`, there might always be other values tracked.
I guess you are looking for a possibility to disable revenue tracking & reporting completely for a certain goal, right? That's something Matomo can't provide at the moment.
I'll hand this issue over to our product team, so they can consider this improvement for a future release.

**Comment by vadi2** [comment]
Hey @sgiehl, I've set the goal revenue to $0 but Matomo is still counting $0.01 per download - that part seems like a bug to me.

**Comment by sgiehl** [comment]
But there seems to have been some revenues tracked. At least the revenue sum is not reported as `0`.

**Comment by vadi2** [comment]
Precisely the problem, why is that the case when the goal revenue is set to $0?

**Comment by sgiehl** [comment]
As mentioned before, When you track goals manually using the javascript method, you can send a custom revenue. Only if no revenue is sent, the configured default is used.

**Comment by heurteph-ei** [comment]
@sgiehl 
@vadi2 correct me if I'm wrong.
What I understood of Vadi explaination is: for `pkuxkx.net`, there was 42 conversions at $0, and the total sum of these 42x0 is displayed equal to... $0.42!

**Comment by vadi2** [comment]
Yeah, I don't know really. 

@sgiehl I was not the one who setup the JS tracking originally, so what you said at first did not resonate. My tracking code does not set any custom revenues:

```js
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
  _paq.push(["setCookieDomain", "*.mudlet.org"]);
  _paq.push(["setDomains", ["*.mudlet.org","*.forums.mudlet.org","*.make.mudlet.org","*.wiki.mudlet.org","*.forums.mudlet.org","*.make.mudlet.org","*.mudlet.org","*.wiki.mudlet.org"]]);
  _paq.push(["enableCrossDomainLinking"]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://stats.mudlet.org/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

So this still seems to be a Matomo bug, please correct me if I'm wrong.

**Comment by mattab** [comment]
@vadi2 thanks for the report!
can you confirm that if you select data say for this week, then the revenue columns show as zero?

I'm having a similar issue where, if a revenue is set to 0, or not set, for any Goal, and the goal is not Ecommerce related,  and if the values in the column are all zeros in that period (in case some goal are manually tracked with a revenue),  then the "Revenue" column and "Revenue per visit" column should be hidden. 

I was going to create another issue for it but maybe it could be included in the scope of this one?

**Comment by vadi2** [comment]
> can you confirm that if you select data say for this week, then the revenue columns show as zero?

Yep, I can confirm that. Sounds like it should be included!
