### ISSUE TITLE
Problème de mise a jour du nombre de visiteur

### ISSUE THREAD

**Issue by labearnaise** [piwik/piwik#19658]
Bonjour,
Le nombre de visiteur de la journée n'a pas été mis à jour ce lundi 22 août 2022 depuis environ 16h00

**Comment by sgiehl** [comment]
Hi @labearnaise 
If you are a user of our Matomo cloud, please get in touch with our support. Otherwise reach out to your administrator or try to get some help on our forum.
We are only handling specific bug reports or feature requests here on GitHub.
Thanks.
