### ISSUE TITLE
Remove sentence about Alexa in SEO ranking widget documentation

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19666]
Following  [#19166 Remove discontinued Alexa from SEO metrics providers](https://github.com/matomo-org/matomo/issues/19166), the following sentence must be removed:
> Additionally, it reports on your Alexa ranking, which is a ranking of the most popular sites on the web.

And the example picture, updated from documentation:
https://matomo.org/faq/dashboards/seo-ranking-widget/

**Comment by justinvelluppillai** [comment]
Good one, thanks 👍🏽

**Comment by justinvelluppillai** [comment]
I've updated the doc with the current state of affairs.
