### ISSUE TITLE
Import data from other installations

### ISSUE THREAD

**Issue by h3x4git** [piwik/piwik#19668]
I had to recreate a project on another server and start from scratch.

It consists of a set of domains that all pull data from the same database. All of them are tracked by the same local Matomo installation which allows performance comparison. However one of the domains was previously hosted elsewhere and already tracked by the back then's Matomo installation, which I still have a working copy of.

It would be great to merge statistics from that other installation with the current one in order to calculate metrics over the years for that original domain server without risking the current Matomo database to break in MySQL.

I wonder if there could one day exist a plugin to export and re-import sites data in another Matomo instance (for merging information)

**Comment by Findus23** [comment]
What feature are you looking for that https://plugins.matomo.org/Migration doesn't provide?

**Comment by h3x4git** [comment]
I was unaware of the existence of such plugin, I wasn't able to locate it in the Marketplace and couldn't find information on its usage via my search engine. I had looked up for "export" related expressions in the Marketplace but only "Conversion" would turn up. Maybe this could be an opportunity to inform you that Migrations plugin's hard to find for someone at the moment. Thank you

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/feature-request-matomo-to-matomo-import-plugin/55246/2
