### ISSUE TITLE
Design/UI: Prevent the use of (too much) scrollings...

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19676]
## Summary
When users uses Matomo reports, they complain about always having to scroll down then up...

## Step to reproduce
I want to see (on demo site) the Page Location and Page Type for different segments (or date)
1. Go to https://demo.matomo.cloud/
![image](https://user-images.githubusercontent.com/79993552/186672796-78264b13-5eb6-4ddd-828c-9674e570885a.png)
Great! 🎉
2. Open the **Behaviour** menu, scroll down to see **Page Location** then click on this link
![image](https://user-images.githubusercontent.com/79993552/186676023-de7204e3-3c1c-4751-b466-ba02b6034f39.png)
Argh, I don't see the first lines of the table... 😥
3. Now I want to change or check the dimension (or date), so I have to scroll up! (because I don't see the dedicated dropdowns) 😢
4. OK, now I want to see the **Page Type** sub menu of **Behaviour**... I have to scroll down again😢
![image](https://user-images.githubusercontent.com/79993552/186675905-db4dfd6b-9a03-418d-9553-21f3b551b61f.png)
And loose again top report lines and segmentation/date dropdowns... 😭

(Note: for top bar, the problem is the same when using the green bottom icons of the table reports (for data export, etc.) or when you scroll down the main Matomo dashboard to see the most bottom one...)

### Left menu
Provide an independent scrolling for the left menu
### Top menu/dropdowns
Use of sticky menu

## Your Environment
Steps to be done at: https://demo.matomo.cloud on device 1200x800 (Firefox)

**Comment by bx80** [comment]
Hi @heurteph-ei, 

Thanks for the feedback and detailed explanation, there certainly is a lot of scrolling involved when using device with limited vertical pixels. Sticky menus could definitely be a good way to address this but any change would need to also be considered in the context of the overall user experience. I've marked this issue for further prioritization and I'm sure it can inform our future UX improvements :+1:

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated 🙌
There were quite a few issues with the same theme: https://github.com/matomo-org/matomo/issues/6362 https://github.com/matomo-org/matomo/issues/15873 https://github.com/matomo-org/matomo/issues/19669 https://github.com/matomo-org/matomo/issues/21147 https://github.com/matomo-org/matomo/issues/19355
i'll mark this as closed in favor of this issue: https://github.com/matomo-org/matomo/issues/19669
