### ISSUE TITLE
When filtering a user's permissions, then it doesn't show capabilities correctly

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19679]
Eg when editing a user, then I can see all capabilities
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/273120/186792706-3e72b95d-8b79-42bb-86a7-f27f4ad30623.png">

Then select `Filter by access: View`.

Now it no longer shows these

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/273120/186792749-2205d2cd-7487-4b9f-8d0d-257c19a10783.png">

Is this a regression maybe?

**Comment by peterhashair** [comment]
@tsteur quickly did a PR and will add tests for that as well.

**Comment by sgiehl** [comment]
That did never work I guess. Already fixed a similar issue in https://github.com/matomo-org/matomo/pull/19388/files#r904786439
