### ISSUE TITLE
Exit Rate for Plug-in Custom Report

### ISSUE THREAD

**Issue by benwulfio** [piwik/piwik#19689]
The metric EXIT RATE for pages and SEARCH EXIT for site search can be used in custom reports.

There are other users looking for the same feature: https://forum.matomo.org/t/costum-reports-metrics/33245

**Comment by sgiehl** [comment]
Hi there, Thank you for creating the issue. We are only handling issues regarding Matomo itself here.
To request support or suggest features for a Premium Feature please contact shop at innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features
Thanks
