### ISSUE TITLE
Wrong cursor on delete icon

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19697]
When hovering the delete button, then no pointer cursor appears  but it does for the edit icon. Thus it's not fully clear it's clickable.
![image](https://user-images.githubusercontent.com/273120/187823637-70d434dc-8c2a-4263-a96e-11acbd63d87f.png)

This happens eg in "Manage users". But also in "Custom Alerts" manage screen.

**Comment by sgiehl** [comment]
Seems the css in usersmanager hadn't been updated after it was rebuilt. There are a lot rules that can't even be used. Will put up a quick PR to clean that up.
