### ISSUE TITLE
Measurables with long names have name cutoff in PDF reports

### ISSUE THREAD

**Issue by varunKothare** [piwik/piwik#19693]
The issue occurs when generating an email report for a long website title (as defined under Matomo >> All Website) 
example:  website name "A quite long name for a simple website which hopefully reproduces the issue" 

Now if we try to generate an email report for this website, the websites full name is cut from the PDF: 
![image](https://user-images.githubusercontent.com/100554311/187562548-2b60f169-030e-49ed-bceb-5dd6e1e70a79.png)
see attached img. 

Is there a way we can get the website title to wrap around similar way to the description which allows longer strings to be displayed.

Tested on Matomo version 4.2.1 (older version of tcpdf) and latest, occurs on both. 

Related Forum ticket showing the same issue: https://forum.matomo.org/t/missing-line-breaks-in-mail-reporting-pdf/46244

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/missing-line-breaks-in-mail-reporting-pdf/46244/7

**Comment by bx80** [comment]
This is a trivial fix, just need to change the TCPDF cell type for the report title. I've created a PR.

Also noticed long titles can cause the footer to overflow, so I've added some cropping there which seems better than having the page counter overflow off the page.

**Comment by PatrickHBerlin** [comment]
At the moment we try the “custom reports” plugin and there are some more problems with missing breaklines by using custom reports im mail reporting.


In this case we want to report the page Titel + page URL. The page URL is very long ;-)
Could you please check to wrap the given urls to show the whole report on one page? Maybe on landscape?

We use Matomo 4.12.0 at the moment.

Best,
Patrick
![Bildschirmfoto_2022-10-19_um_11_27_29](https://user-images.githubusercontent.com/116718960/197994407-0f216bae-e5ca-4476-91af-74ff8149c06c.jpg)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/missing-line-breaks-in-mail-reporting-pdf/46244/11
