### ISSUE TITLE
Typo in examples of CRON command and JavaScript 

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19704]
# CRON
## Page
https://matomo.org/faq/on-premise/how-to-configure-matomo-to-handle-unexpected-peak-in-traffic/
## Problem
The CRON command will be triggered every hour instead of every minute
>Then setup a cronjob that executes the command `./console queuedtracking:process` **every minute,** for example:
> `1 * * * * php /path/to/matomo/console `

# JavaScript
## Page
https://matomo.org/faq/tag-manager/data-layer-in-matomo-tag-manager/
## Problem
Use of `‘’` chars (opening and closing quotes) instead of `'` (simple quote):
> `<script>`
> `var  _mtm =  _mtm || [];`
> `_mtm.push({'weather': `**`‘`**`sunny`**`’`**`});`
> `</script>`

And also there:
> `<script>`
> `var  _mtm =  _mtm || [];`
> `_mtm.push({'weather': `**`‘`**`MY CODE HERE TO GET THE DATA FROM A WEATHER API`**`’`**`});`
> `</script>`

**Comment by sgiehl** [comment]
Hi @heurteph-ei 
Thanks for bringing that up. I've updated the pages.
