### ISSUE TITLE
core:archive command failed

### ISSUE THREAD

**Issue by luckycloud-GmbH** [piwik/piwik#19706]
Hello,
matomo suddenly does not create any statistics from one day to the next (we are using matomo v4.11.0).

I have tried to execute the archive command manually, but I get an error message
/var/www/matomo/console --matomo-domain=monitor.luckycloud.de core:archive

ERROR [2022-09-05 01:04:49] 2300  Uncaught exception: Error: Undefined constant "Piwik\Db\Adapter\MYSQLI_OPT_LOCAL_INFILE" in /var/www/matomo/core/Db/Adapter/Mysqli.php:35
Stack trace:
#0 /var/www/matomo/core/Db/Adapter.php(49): Piwik\Db\Adapter\Mysqli->__construct()
#1 /var/www/matomo/core/Db.php(157): Piwik\Db\Adapter::factory()
#2 /var/www/matomo/core/Db.php(56): Piwik\Db::createDatabaseObject()
#3 /var/www/matomo/core/Db.php(302): Piwik\Db::get()
#4 /var/www/matomo/core/Option.php(288): Piwik\Db::fetchAll()
#5 /var/www/matomo/core/Option.php(178): Piwik\Option->autoload()
#6 /var/www/matomo/core/Option.php(48): Piwik\Option->getValue()
#7 /var/www/matomo/plugins/UserCountry/LocationProvider.php(341): Piwik\Option::get()
#8 /var/www/matomo/plugins/UserCountry/LocationProvider.php(357): Piwik\Plugins\UserCountry\LocationProvider::getCurrentProviderId()
#9 /var/www/matomo/plugins/GeoIp2/Commands/ConvertRegionCodesToIso.php(34): Piwik\Plugins\UserCountry\LocationProvider::getCurrentProvider()
#10 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(388): Piwik\Plugins\GeoIp2\Commands\ConvertRegionCodesToIso->isEnabled()
#11 /var/www/matomo/core/Console.php(163): Symfony\Component\Console\Application->add()
#12 /var/www/matomo/core/Console.php(121): Piwik\Console->addCommandIfExists()
#13 /var/www/matomo/core/Console.php(87): Piwik\Console->doRunImpl()
#14 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#15 /var/www/matomo/console(32): Symfony\Component\Console\Application->run()
#16 {main}
Uncaught exception in /var/www/matomo/core/Db/Adapter/Mysqli.php line 35:
Undefined constant "Piwik\Db\Adapter\MYSQLI_OPT_LOCAL_INFILE"

**Comment by peterhashair** [comment]
Hi @luckycloud-GmbH, this may be caused `LOAD DATA INFILE` setting on the local server. To set it up you can follow this https://matomo.org/faq/troubleshooting/faq_194/. If that still shows the errors, feel free to leave comments.

**Comment by luckycloud-GmbH** [comment]
Hi,
thanks for the very fast answer.
I tried the troubleshooting steps, but its still not working.
I got still the same error

Also disabling with enable_load_data_infile=0 does not work (got the same error with the core:archive)

**Comment by sgiehl** [comment]
@luckycloud-GmbH Maybe ask your server admin if there had been any changes to your server. The error message indicates, that the MYSQLi extension for PHP might not be loaded correctly. The missing constant `MYSQLI_OPT_LOCAL_INFILE` should be defined by this extension.
For further help, I'd like to refer you to our forum at https://forum.matomo.org, as we usually don't do any troubleshooting on GitHub, due to our limited resources. Thanks!

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/undefined-constant-mysqli-opt-local-infile/49839/2
