### ISSUE TITLE
Invitation emails not arriving

### ISSUE THREAD

**Issue by caranorth** [piwik/piwik#19713]
I'm trying to invite users and the emails are not arriving.  They are not going to Spam or Promotions or Junk.  Is there any way that I as administrator can get around this?

Thanks,
Cara
cnorth@fsu.edu

**Comment by peterhashair** [comment]
Hey @caranorth, we create a new register method, you can copy the email link in the next release. Details can be found here https://github.com/matomo-org/matomo/issues/19625

**Comment by justinvelluppillai** [comment]
@caranorth you can create a user via the API if you can't wait for the next release: https://developer.matomo.org/api-reference/reporting-api#UsersManager

**Comment by caranorth** [comment]
When do we expect the next release?

**Comment by sgiehl** [comment]
> When do we expect the next release?

likely this month

**Comment by heurteph-ei** [comment]
@caranorth , is the mail service of your server enabled? Or if you use SMTP, is it well configured? What happens if you send email report?

**Comment by caranorth** [comment]
We took care of it. Thanks.
