### ISSUE TITLE
 Wrong number format for thousands in languages different by english 

### ISSUE THREAD

**Issue by jr-ewing** [piwik/piwik#19726]
In the evaluation of engagement, the format of the numbers is different in German than in English. It's probably because of the thousands separator. The problem probably existed earlier in other places, e.g. #15356.

## Expected Behavior
The representation of the number 9946 should read 9.946 and not be truncated

## Current Behavior
In German, the number is truncated to two decimal places if the number is greater than 1000.

## Steps to Reproduce (for Bugs)
First, in English, call up the engagement evaluation in the menu under Behavior. Here you should choose the period so that more than a thousand visitors are counted.
Then go to personal settings and change the language to German. In the Behavior -> Commitment menu, you can then see the changed thousands formatting.

## Your Environment
* Matomo Version: 4.11
* PHP Version: 7.4.30
* Server Operating System: Ubuntu
* Browser: Firefox
* Operating System: Linux
Webserver: Apache  

![Auswahl_4419](https://user-images.githubusercontent.com/192153/189883257-d6505e76-9787-4e13-a60b-82766723a9b7.png)
![Auswahl_4420](https://user-images.githubusercontent.com/192153/189883261-e2b3bc1e-877b-449e-806e-83de5f939323.png)

**Comment by sgiehl** [comment]
Hi Thomas,

Thanks for creating this issue. I was able to reproduce that one and will prepare a fix for the next release shortly.

Cheers,
