### ISSUE TITLE
Fatal error while opening notification menu

### ISSUE THREAD

**Issue by simone-gasparini** [piwik/piwik#19728]
## Expected Behavior

Open notification menu and see items

## Current Behavior

Fatal error page with stacktrace
```
Piwik\Changes\Model::doChangesExist(): Argument #1 ($newerThanId) must be of type ?int, string given, called in /var/www/vhosts/xxx.yyy/matomo.xxx.yyy/core/Changes/UserChanges.php on line 48
in /var/www/vhosts/xxx.yyy/matomo.xxx.yyy/core/Changes/Model.php line 139
```
Every page i go will redirect to this error page:
```
https://matomo.xxx.yyy/index.php?module=CoreHome&action=index&idSite=2&period=day&date=yesterday
```

## Steps to Reproduce (for Bugs)

1. New installation
2. Login
3. Create new site
4. Open notification menu
5. Matomo will show fatal error page with no way to get back to home

## Your Environment

* Matomo Version: 4.11.0
* PHP Version: 8.1.10
* Server Operating System: Ubuntu 20.04.5
* Additionally installed plugins: All plugin disabled

* Browser:
* Operating System:

**Comment by simone-gasparini** [comment]
Digging into the code...
[https://github.com/matomo-org/matomo/blob/4.x-dev/core/Changes/UserChanges.php#L48](https://github.com/matomo-org/matomo/blob/4.x-dev/core/Changes/UserChanges.php#L48)

```$idchangeLastViewed``` is ```string(19) "0000-00-00 00:00:00"``` but ?int is required by ```doChangesExist()```

Watching the DB table
<img width="310" alt="Schermata 2022-09-13 alle 15 52 18" src="https://user-images.githubusercontent.com/1280258/189919418-4653f15f-c2db-49fd-a05b-8592bf481700.png">

This issue happen only with entries in the matomo_changes table, this enable the notification icon in the header menu.

**Comment by sgiehl** [comment]
Hi @simone-gasparini 
Thanks for reporting this issue. Guess I found the problem. I'll prepare a fix for it...
