### ISSUE TITLE
Viewing what's new entry causes an error and doesn't let you use the UI anymore at all

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19739]
Seeing this after trying to view the "What's new" section on Cloud. GA Importer recently added the first entry

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/273120/190316817-c58210d4-f0f3-4bcb-9756-61b0574f89f9.png">

Currently, the feature is not usable and results in an error. I can't view any page anymore after clicking on "what's new". Even when I try to just open the analytics domain, nothing works anymore.

This is the error:

> Error: {"message":"Piwik\\Changes\\Model::doChangesExist(): Argument #1 ($newerThanId) must be of type ?int, string given, called in \/core\/Changes\/UserChanges.php on line 48","file":"\/core\/Changes\/Model.php","line":139,"request_id":"52c71","backtrace":" on \/core\/Changes\/Model.php(139)\n#0 \/core\/Changes\/UserChanges.php(48): Piwik\\Changes\\Model->doChangesExist('0000-00-00 00:0...')\n#1 \/plugins\/CoreAdminHome\/Menu.php(60): Piwik\\Changes\\UserChanges->getNewChangesStatus()\n#2 \/core\/Menu\/MenuTop.php(55): Piwik\\Plugins\\CoreAdminHome\\Menu->configureTopMenu(Object(Piwik\\Menu\\MenuTop))\n#3 \/core\/Plugin\/Controller.php(680): Piwik\\Menu\\MenuTop->getMenu()\n#4 \/core\/Plugin\/Controller.php(605): Piwik\\Plugin\\Controller->setGeneralVariablesViewAs(Object(Piwik\\View), 'basic')\n#5 \/plugins\/TagManager\/Controller.php(220): Piwik\\Plugin\\Controller->setGeneralVariablesView(Object(Piwik\\View))\n#6 \/plugins\/TagManager\/Controller.php(90): Piwik\\Plugins\\TagManager\\Controller->renderTemplate('@TagManager\/get...', Array)\n#7 [internal function]: Piwik\\Plugins\\TagManager\\Controller->gettingStarted()\n#8 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#9 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('TagManager', 'gettingStarted', Array)\n#10 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#11 \/index.php(25): require_once('\/c...')\n#12 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(190): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

this is stored in the DB
<img width="293" alt="image" src="https://user-images.githubusercontent.com/273120/190317952-9557e24f-2047-4602-a243-c7f51103d0d7.png">

**Comment by tsteur** [comment]
Problem seems to be maybe that new installs use `timestamp` and older ones an `integer`?

**Comment by peterhashair** [comment]
@tsteur I believe @sgiehl already fixed that one, should be in the next release.

**Comment by justinvelluppillai** [comment]
Refs #19728
