### ISSUE TITLE
When Visits log is disabled, then a red error notification is shown at the top of every report for today.

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#19734]
Matomo regularly wrongly shows a red error message for people who disabled Visits log & profiles (as part of CNIL compliance).

## Reproduce:

* Edit a website
* Configure website to turn off Visits log and profile for this website:
![Screenshot from 2022-09-15 10-31-35](https://user-images.githubusercontent.com/466765/190275024-2bfb719e-52fa-46c7-b6c3-d969a42a79c6.png)
* Then open any report 
* and select "Today" in the calendar

## Got:

A red error message at the top of each report. It can be closed, but then it constantly re-opens. 

![image](https://user-images.githubusercontent.com/466765/190275194-1fb6f0bc-039f-443f-95b8-affb11fc990f.png)

## Expected instead:

Data for today to show without an error message.

**Comment by tsteur** [comment]
This is a duplicate of https://github.com/matomo-org/matomo/issues/19291

**Comment by mattab** [comment]
Ok, issue is known since May 20th. see https://github.com/matomo-org/matomo/issues/19291
