### ISSUE TITLE
When Visits log is disabled, and looking at today's report, the notification explaining that reports are not yet processed is not displayed

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#19736]
As a user I want to be Notified that "Today's report" are showing zeros because it takes hours to generate reports and explain I need to wait. This works fine except when "Visits log & profile" feature is disabled

## Reproduce

* Disable the Visits log for the website https://matomo.org/faq/how-to/how-do-i-disable-the-visits-log-or-the-visitor-profile-feature/
* Open Today's report when there are no reports generated yet 

## Expected

So when looking at Today’s report (or this week, this month, or any date range including today), and the report shows Zeros, then we’d expect to see a notification explaining that data is tracked but reports take some hours to generate. 

Similar to this message below, but without the link to the Visits log (since it's disabled).

So it could say something like "it looks like reports for this period have not been processed yet, but they will be available in a few hours. You could choose a different date period until the reports are generated." or similar?

![image](https://user-images.githubusercontent.com/466765/190276801-9e4af8ac-3e6f-42e0-ac49-338d20229d45.png)

## Got instead

Zeros and no blue notification - Actually even getting an error, bug known since may 20th see: https://github.com/matomo-org/matomo/issues/19291

**Comment by sgiehl** [comment]
See https://github.com/matomo-org/matomo/issues/19291#issuecomment-1247679925 for a possible solution how to fix that quickly.
