### ISSUE TITLE
Login on local installation does not fully work

### ISSUE THREAD

**Issue by gheisz** [piwik/piwik#19742]
## Expected Behavior
When trying to log into our local server installation log in with username and password should be possible.

## Current Behavior
After entering username and password the URL changes to https://matomo.regnumchristi.eu/index.php?module=Login and shows an error message "Error: form security failed. Token doesn not match. Please reload the form and check whether cookies are activated." (my translation from German "Fehler: Formularsicherheit fehlgeschlagen, Token stimmt nicht überein. Bitte laden Sie das Formular neu und überprüfen Sie, ob Ihre Cookies aktiviert sind.")
In most cases login actually worked which can be seen when I simply remove /index.php?module=Login from the URL.
I am not sure whether there is a aconnection with checking "Stay logged in / Angemeldet bleiben" or leaving it unchecked.

## Possible Solution
No idea

## Your Environment

* Matomo Version: 4.11.0
* PHP Version: 7.4.30
* Server Operating System: Linux
* Additionally installed plugins: none

* Browser: MS Edge
* Operating System: Windows 11

**Comment by heurteph-ei** [comment]
Hello,
Can you try to go to `https://matomo.regnumchristi.eu/index.php` (without any additional parameter) in a private navigation window (in order to remove all any cookie)?

**Comment by gheisz** [comment]
That worked nicely.
GH

**Comment by heurteph-ei** [comment]
Hi @gheisz 
Then I think you can close your issue...

**Comment by gheisz** [comment]
I just deleted all cookies in my normal browser window and I still have the same problem.
I even deleted all other browser data. No change.
Yours,
Gerd

**Comment by heurteph-ei** [comment]
No idea...
@sgiehl maybe?

**Comment by sgiehl** [comment]
Sorry, guess that one slipped through. I'm actually not aware of any known login issues.
@gheisz Are you still having that login issue?
There are a lot of related post on our forum at https://forum.matomo.org. Maybe you are able to find a prober solution there.
If not we might need to investigate that further. But it might take a while till we have time to tackle it.

**Comment by gheisz** [comment]
Dear Stefan,
yes, these issues still exist for me and so far I found one other entry in the forum with the same problem but no solution.
I still have my workaround so it is not hurting too much, just annoying.
Yours,
Gerd

**Comment by sgiehl** [comment]
@gheisz So it works in an incognito tab but not in a normal browser session? My guess would be that maybe a browser plugin might be the problem. Do you maybe have any browser plugins installed? Maybe try disabling them too see if any of them is the problem.

**Comment by gheisz** [comment]
Thanks! This led me to the solution! I am using Keeper as a password manager and when I unchecked the setting that keeper should automatically submit the authentication data it worked!!
Thank you!
Gerd

**Comment by sgiehl** [comment]
Glad to hear it's working now. I'll close the issue. Cheers!
