### ISSUE TITLE
An error occurred : Matomo 4.10.1 and database in 4.11.0.

### ISSUE THREAD

**Issue by Guiraud** [piwik/piwik#19757]
No answers on the forum for [this](https://forum.matomo.org/t/warning-message-after-update/47150). 
## Expected Behavior
Going to the website and finding the login page

## Current Behavior
Prints an error message : 
>Votre installation de Matomo fonctionne sur l'ancienne version 4.10.1 et nous avons détecté que votre base de données a été mise à jour vers la version plus récente 4.11.0. Peut-être que les administrateurs de Matomo sont en train de terminer le processus de mise à jour en ce moment. Veuillez réessayer dans quelques minutes. Si vous rencontrez toujours ce problème, veuillez contacter votre administrateur Matomo pour obtenir de l'aide.

## Possible Solution
Maybe two installed versions are there

## Steps to Reproduce (for Bugs)
1.
2.

## Context
While updating with sudo apt update && sudo apt upgrade -y

## Your Environment

* Matomo Version:
Good question 
* PHP Version: 8.1.10
* Server Operating System:  Debian GNU/Linux 11 (bullseye)
* Additionally installed plugins:
* Browser: Firefox 91.13.0esr (64 bits)
* Operating System: Debian GNU/Linux 10 (buster)

**Comment by bx80** [comment]
Hi @Guiraud, thanks for reaching out.

It sounds like the update from Matomo 4.10 to 4.11 didn't complete successfully.

Are you able to run `./console core:update` from the Matomo installation directory?

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-message-after-update/47150/3

**Comment by Mela** [comment]
I had the same problem today and I can run ./console core:update without any problems. I get the message back that the update ran already successfully. 
 
My Matomo installation updated today to version:

Matomo-Version: 4.13.2
MySQL-Version: 10.5.18-MariaDB-1:10.5.18+maria~ubu2004-log
PHP-Version: 8.1.13

Regards,
Mela

**Comment by sgiehl** [comment]
Hi @Mela 
Do you still have that error displayed? In some cases it could be a matter of caching that this error is shown directly after the update maybe. If it persist, that would actually mean, that the database performed an update to the newer version, but the files in filesystem are still from an older version. This is something that should not happen, unless you manually copy over old files after performing an update.

**Comment by Guiraud** [comment]
Still having the issue. here's some details :
````TEXT

An error occurred
Votre installation de Matomo fonctionne sur l'ancienne version 4.11.0 et nous avons détecté que votre base de données a été mise à jour vers la version plus récente 4.13.3. Peut-être que les administrateurs de Matomo sont en train de terminer le processus de mise à jour en ce moment. Veuillez réessayer dans quelques minutes. Si vous rencontrez toujours ce problème, veuillez contacter votre administrateur Matomo pour obtenir de l'aide.
```
WHen I do the update with the matomo console : 
```
 ./console core:update
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/matomo/core/testMinimumPhpVersion.php on line 130
PHP Deprecated:  Function utf8_encode() is deprecated in /var/www/html/matomo/vendor/szymach/c-pchart/constants.php on line 50
WARNING [2023-05-31 19:29:13] 3766023  /var/www/html/matomo/plugins/PrivacyManager/DoNotTrackHeaderChecker.php(29): Deprecated - Creation of dynamic property Piwik\Plugins\PrivacyManager\DoNotTrackHeaderChecker::$config is deprecated - Matomo 4.11.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
WARNING [2023-05-31 19:29:13] 3766023  /var/www/html/matomo/core/Console.php(135): Deprecated - Callables of the form ["Piwik\Console", "Symfony\Component\Console\Application::doRun"] are deprecated - Matomo 4.11.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

Everything is already up to date.
Error: error or warning logs detected, exit 1
```

You might some more info : 
```
/var/www/html/matomo# php --version
PHP 8.2.6 (cli) (built: May 12 2023 07:47:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
```

**Comment by sgiehl** [comment]
Hey @Guiraud.
Did that happen when updating to 4.13.3?
Could you check which version is defined within the file `core/Version.php`?
Also does this error only occur on updating and afterwards everything works again, or does the error remain?

**Comment by sgiehl** [comment]
Closing as there hadn't been any further activity in the last months.
