### ISSUE TITLE
TwoFactorAuth: Deprecated - str_replace() on PHP 8.1.9

### ISSUE THREAD

**Issue by JE4GLE** [piwik/piwik#19753]
Hi!

> WARNING: /plugins/TwoFactorAuth/TwoFactorAuth.php(255): Deprecated - str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated - Matomo 4.11.0 - Please report this message in the Matomo forums: https://forum.matomo.org 1 (please do a search first as it might have been reported already) (Module: Proxy, Action: getNonCoreJs, In CLI mode: false)

I don‘t think, I have to add more. The error message is pretty self-explanatory 😅

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/twofactorauth-deprecated-str-replace-on-php-8-1-9/47451/3

**Comment by peterhashair** [comment]
@JE4GLE Thank you for reporting this, looks like we could use a null check there.
