### ISSUE TITLE
Rapport Courriel Personnalisé

### ISSUE THREAD

**Issue by Improov-marketing** [piwik/piwik#19761]
Bonjour, 
J'ai programmé un export personnalisé avec envoi quotidien mais les emails ne partent pas. 
Je n'ai pas de soucis avec les exports hebdo par contre. 
Pouvez-vous m'aider ? 

![image](https://user-images.githubusercontent.com/114217834/191915719-2f8f3b5c-ef50-4b8f-9ca4-595f75699582.png)

**Comment by heurteph-ei** [comment]
Bonjour,
Aucun email quotidien ne part-il, ou bien certain partent et d'autres non ?
Avez-vous des erreurs dans les fichiers de log de Matomo ?
Les données sont-elles-bien archivées quotidiennement (et l'archive prête avant l'envoi du mail) ?

**Comment by sgiehl** [comment]
Hi @Improov-marketing 
Maybe try getting some help on our french forum https://forum.matomo.org/c/support-en-francais/10

**Comment by Improov-marketing** [comment]
Yes,
Many thanks.
Regards.
Alexandra

De : Stefan Giehl ***@***.***>
Envoyé : mercredi 5 octobre 2022 16:52
À : matomo-org/matomo ***@***.***>
Cc : Alexandra Ripot ***@***.***>; Mention ***@***.***>
Objet : Re: [matomo-org/matomo] Rapport Courriel Personnalisé (Issue #19761)


Hi @Improov-marketing<https://github.com/Improov-marketing>
Maybe try getting some help on our french forum https://forum.matomo.org/c/support-en-francais/10
