### ISSUE TITLE
There was an error setting cookie `_pk_testcookie_domain`. Please check domain and path.

### ISSUE THREAD

**Issue by Nyaundi** [piwik/piwik#19767]
Hello, I am getting this error. I tried to upgrade matomo to the latest version but still the error is there.
![image](https://user-images.githubusercontent.com/67205640/192135908-4b98df75-ea3e-419f-96d9-e8870fbae408.png)

**Comment by justinvelluppillai** [comment]
This error is displayed on purpose to show you that you have tried to set a cookie on a domain that you can't write cookies to.

Perhaps this is something you could ask for help with in the [forum](https://forum.matomo.org/) as it's most likely not a bug report.

**Comment by Nyaundi** [comment]
Okay, understood. I apologize for that
