### ISSUE TITLE
Logged in but you don't have any permission should not HTTP 500

### ISSUE THREAD

**Issue by mwithheld** [piwik/piwik#19774]
If you login but don't have any permissions, the HTTP return code is 500.  It should be a 401.

```
[26/Sep/2022:09:47:20 -0900] Error in Matomo: You are logged in as 'blah@bloo.com' but it seems you don't have any permission set in Matomo.  Ask your Matomo administrator (click to email) to give you 'view' access to a website.&nbsp;&nbsp;&nbsp;&rsaquo; Sign out

[26/Sep/2022:09:47:20 -0900] "GET /index.php HTTP/1.1" 500 2064 "https://bloo.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0"
```

## Possible Solution
core/Plugin/Controller.php::redirectToIndex() should produce a 401 HTTP response here:

```
        if (!Piwik::isUserIsAnonymous()) {
            $currentLogin = Piwik::getCurrentUserLogin();
            $emails = implode(',', Piwik::getContactEmailAddresses());
            $errorMessage  = sprintf(Piwik::translate('CoreHome_NoPrivilegesAskPiwikAdmin'), $currentLogin, "<br/><a href='mailto:" . $emails . "?subject=Access to Matomo for user $currentL$
            $errorMessage .= "<br /><br />&nbsp;&nbsp;&nbsp;<b><a href='index.php?module=" . Piwik::getLoginPluginName() . "&amp;action=logout'>&rsaquo; " . Piwik::translate('General_Logout$

            $ex = new NoPrivilegesException($errorMessage);
            $ex->setIsHtmlMessage();

            throw $ex;
        }
```

## Steps to Reproduce (for Bugs)
1. Create a user profile but assign no site privileges
2. Login as that user
3. Check the HTTP response code

## Context
Our BigIP ASM blocks pages with 500 response codes from displaying, so the resulting page displayed to the user is unfriendly.

* Matomo Version: 4.11.0

**Comment by peterhashair** [comment]
hey @mwithheld, that makes sense, some of the API response code needs to update, I put this onto our priority queue.

**Comment by mwithheld** [comment]
This is still a problem in 4.3.1, and from the code it looks like it'll still be a problem with 5.0.0-rc3.
