### ISSUE TITLE
Segment auto suggest capitalization

### ISSUE THREAD

**Issue by mindbreaker** [piwik/piwik#19773]
When the value is typed in a segment, it appears in capital letters. As a value, however, it is then taken over in such a way that only the first letter is written in capital letters. 

Issue in forum: https://forum.matomo.org/t/segment-autosuggest-capitalization/47525

## Expected Behavior
The value should be displayed in the auto-completion as it should actually be taken over in the field. For example:
If you want to select the country "Austria" it is displayed as "AUSTRIA" in the Autosuggest. But the value is "Austria".

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/segment-autosuggest-capitalization/47525/2

**Comment by bx80** [comment]
Hi @mindbreaker, thanks for reporting this. The auto-completion list has a `text-transform: uppercase` style applied which shows all list items as uppercase even though the underlying value is first letter capital only. This seems unnecessary and it would be better if the displayed list value was consistent when chosen.

I've assigned this issue for prioritization.

**Comment by mindbreaker** [comment]
OK. I created a pull request:
#19777

**Comment by bx80** [comment]
Thanks for the pull request @mindbreaker, I've assigned it to the next release milestone :+1:

**Comment by mindbreaker** [comment]
Thx. @bx80 i see that the merge needs another approval.
