### ISSUE TITLE
Make title for E-Commerce overview desktop widget more descriptive

### ISSUE THREAD

**Issue by danielhug-cc** [piwik/piwik#19779]
## Summary
I am generating a little c-level dashboard, and I noticed that while the visits overview widget says “visits overview”, the e-commerce overview only says “overview”. That is confusing, and should be changed. It should say “E-Commerce Overview”:
![image](https://user-images.githubusercontent.com/104900372/192499631-95878166-0ad7-4d3f-a994-fc993bfef7d6.png)

## Your Environment
Matomo Cloud

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/title-for-ecommerce-widget-is-incomplete/47515/5

**Comment by peterhashair** [comment]
@danielhug-cc that sounds like a simple title change, I will put this into our priority queue. And also feel free to create a PR.
