### ISSUE TITLE
Styling bug: For Page Overlay, the left side panel div is partially covered in Firefox 

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19782]
To reproduce, go to Behavior > Pages > (then select from a single page row “Overlay” by pressing the overlay icon).    
It seemed to not be present in Chromium but not totally sure.

The bug is arrow 2 in the diagram below.

![image](https://user-images.githubusercontent.com/22874146/192778826-86472c12-d331-4c99-ba15-177849f0c05b.png)

**Comment by bx80** [comment]
Hi @atom-box, I can't recreate this either on Firefox 91 or 102.3.0esr. What version of Firefox and OS are you running?

**Comment by sgiehl** [comment]
Closing this one, as the problem should be related to the Overlay not working correctly on demo in general, as the tracker of demo isn't installed on that page at all.
