### ISSUE TITLE
Hundreds of API requests sent to API.getSuggestedValuesForSegment when trying to configure a segment

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19786]
I'm clicking on "Add new segment"

Then I select "Page URL".

Then it starts fetching data. As soon as I click around or type of for some reason it starts sending hundreds of requests to the API causing a massive load.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/273120/192893944-4300dfba-b7b0-434c-a885-6184b3aeb9c3.png">

Call stack:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/273120/192894012-da745acc-3ad5-435e-9e7b-8af3c84aeb18.png">
<img width="662" alt="image" src="https://user-images.githubusercontent.com/273120/192894042-b1e60f47-7bc7-4a84-9578-99e1667a051c.png">

**Expected**: 

Only request the data once

**Comment by justinvelluppillai** [comment]
@diosmosis is this a vue related regression?

**Comment by diosmosis** [comment]
@justinvelluppillai seems likely. I'll look into it.
