### ISSUE TITLE
Page Overlay doesn't work: never finishes loading

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19781]
Possible Regression

On my version 4.10.1 site, everything is fine, no bug.
On my cloud instance (v 4.11.0), and on the Matomo demo site, Page Overlay just spins and spins, never loads.

To reproduce the bug:

Go to
Behavior > Pages > go to a single page row, like Bali > Page Overlay
![image](https://user-images.githubusercontent.com/22874146/192777482-45296514-522d-47a2-aba5-21396e6688cf.png)

The page hangs (on the left edge it says "loading" forever).

 

Chromium:
![image](https://user-images.githubusercontent.com/22874146/192777536-8c3ba1b2-abb0-48bf-8316-5a204bc618e5.png)

The page hangs (on the left edge it says "loading" forever).

 

Firefox:
![image](https://user-images.githubusercontent.com/22874146/192777668-e735d7c6-8bda-43a1-87b7-77b6b4d90ddb.png)

Again, on my version 4.10.1 site, everything is fine, no bug.

(By the way, arrow 2 in this image points to a styling bug, reported separately as https://github.com/matomo-org/matomo/issues/19782

**Comment by bx80** [comment]
I can confirm this issue on demo.matomo.cloud. Seems like it might be CORS setup related?

![Screenshot_20220930_125316](https://user-images.githubusercontent.com/88810029/193161815-0ea8304e-e98d-4391-b22f-444fa4cabbd9.png)

**Comment by bx80** [comment]
Unable to recreate locally on 4.x-dev. Any thoughts @samjf?

**Comment by sgiehl** [comment]
I guess the problem is, that `divezone.net` actually tracks to `ananlytics.divezone.net`. I think our demo uses some generated test data for that domain. To get the page overlay working, I guess the website would need to load `piwik.js` from `demo.matomo.cloud`.
That isn't anything we can fix in Matomo I guess. Might be something for an internal issue...

**Comment by jphustman** [comment]
I'm having this issue on my website as well, the page loads in the frame, but the left sidebar never moves on from "Loading..."
Nothing appears to be being blocked, or any errors in the console, also I'm not getting any information on any of the links either.

**Comment by sgiehl** [comment]
@jphustman If it doesn't finish to load, that is in most cases a problem of mismatching domains or other issues that prevent loading the data from the API. But normally your browser console should report you, that a request wasn't loaded and why. If all requests are loaded correctly, maybe the request to load the data has other problems, in that case maybe the error log can give a hint. In any case I would suggest you to get some support on this on our forum at https://forum.matomo.org
