### ISSUE TITLE
DE: Segment translation for saveAndApply

### ISSUE THREAD

**Issue by mindbreaker** [piwik/piwik#19783]
Looks like the translation excapes the & in the button.
![image](https://user-images.githubusercontent.com/225204/192791792-b647b98e-ec13-4f55-bd14-175731f51599.png)

**Comment by bx80** [comment]
Thanks for reporting this @mindbreaker :+1:

**Comment by sgiehl** [comment]
This has already been fixed with https://github.com/matomo-org/matomo/pull/19190/files#diff-05e5730fc6d27386e71d02ec01af30266f96593438ba2e504a8e900dccd0e0b5

**Comment by mindbreaker** [comment]
Thx:

![image](https://user-images.githubusercontent.com/225204/199800075-f278fcda-84f6-42f9-acf7-9bef827c4f72.png)
