### ISSUE TITLE
Is there a way to filter a specific user ID on Visitors > User IDs?

### ISSUE THREAD

**Issue by jrca025** [piwik/piwik#19800]
For example I will search user_id = 1.

When I try to filter it, it seems like all user id with "1" will be shown.

![image](https://user-images.githubusercontent.com/89201548/193213678-45296e0a-aa70-48dc-bf47-249040597b85.png)

**Comment by peterhashair** [comment]
@jrca025 we normally don't ask support questions in Github, refer to our [forum](https://forum.matomo.org/). But to filter User ID, you can create a segment. See screenshots. 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/3783072/193474186-cf353d01-4a98-4246-8156-b007da22b300.png">

**Comment by peterhashair** [comment]
@jrca025 you are right, the system searches substring, and everything containing `1` will be shown, but I guess that's expected behavior. To filter a single number, maybe a user segment can be configed.

**Comment by sgiehl** [comment]
Note: The UI doesn't allow that, as the search box always searches by pattern. Using the API directly that is possible by using the `label` parameter.
