### ISSUE TITLE
Move public environment outside private directories

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#19801]
The security check feature called Required (and Recomended) private directories" is now [generating about 15 open issues on github](https://github.com/matomo-org/matomo/issues?q=is%3Aissue+private+directories) if we exlude closed issues.

For example, I've put this effective directive inside apache, but looks like not enough for the feature.

```
<LocationMatch "^/matomo/(config|core|tmp|lang|.git)">
    Require all denied
</LocationMatch>
```

In my opinion private directories shouldn't served by apache. So, for a next software's refactoring (v.5.x), I suggest to distribute public files and assets directories inside their own `/public` directory.

Suggesting to [bypass the security checks](https://github.com/matomo-org/matomo/issues/19719#issuecomment-1243415375), is a needed fast shortcut, but unreliable long term solution.

## Target Environment
* Matomo Version: 5.x

**Comment by Findus23** [comment]
I think that's the same discussion as https://github.com/matomo-org/matomo/issues/19505 
And I still agree that this is (at least as an optional installation method) a huge benefit for Matomo.

**Comment by tassoman** [comment]
We're on the same frequency, I close as duplicated
