### ISSUE TITLE
Ensure empty report tables also use max width

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19819]
Not sure if that was on purpose or a regression. Previously, they were limited to a certain width but now in 4.12 they utilise the full screen width. 

For example it looked like this in 4.11

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/273120/194150389-fbdda9fa-becd-4d94-9314-71be99b7310b.png">

But now in 4.12 they use the full width.

I couldn't find anything in the changelog and assume this is a regression

**Comment by peterhashair** [comment]
@tsteur It's a maybe on purpose. the max width used to 1200px injected by javascript. But I believe this only applies when there is data inside the table, if there is no data, it shows as full width.

https://github.com/matomo-org/matomo/blob/64e8473b3d6a1227c52fe9dc661806674efaab4e/plugins/CoreHome/javascripts/dataTable.js#L418

**Comment by sgiehl** [comment]
I'll set up a PR to fix that for empty tables...

@tsteur would you mind to confirm, if that only happens for empty tables, or also for some tables with data?

**Comment by tsteur** [comment]
@sgiehl it looks to me that this happens also for non-empty reports

**Comment by sgiehl** [comment]
@tsteur can you give some examples?

**Comment by tsteur** [comment]
@sgiehl clicking through a few reports I actually couldn't find any examples. There were quite a few reports that had full width but turns out this was already the case with Matomo 4.11. Not sure if this regressed for other reports earlier some time or if it's always been that way. For example https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Funnels_Funnels&subcategory=2 . Likely it's been always that way on purpose and that's not a regression. So there should be no issue 👍

**Comment by sgiehl** [comment]
Ok. Then this should be fixed with the referenced PR.
