### ISSUE TITLE
20 to 40% of visitors are not tracked, if using Kubernetes Cluster

### ISSUE THREAD

**Issue by LewisReyes** [piwik/piwik#19810]
Hello
I use Matomo in several projects. On VDS everything works fine, sometimes I even see more visitors compared to Google Analytics

But in the current project, the infrastructure is located in the Kubernetes Cluster. I see that the statistics are 20-40% lower, compared to Google Analytics. Despite the fact that the configuration is exactly the same as in other projects

To solve this issue, I did the following:
- Used standart Matomo configuration
- Disabled bot tracker plugin
- Reduced the number of Kubernetes Pods to one.
- Added up more resources to the server. Now the CPU is loaded no more than 7%.
- updated PHP version to 8.1.9
But none of these actions increased the number of tracked visits. I know that Google needs a few days to more accurately display the number of visitors, so I waited, but the situation has not changed.

Have you ever experienced underestimated statistics? Are there any solutions to this issue? What kind of logs do I need to pay attention to?
Thank you

**Comment by sgiehl** [comment]
Hi @LewisReyes 
I actually don't have any experience with Kubernetes. But based on your report this looks like a very specific issue, that does not have anything to do with Matomo it self.
We are actually unable to provide support for such specific use cases here on GitHub, as our time is quite limited.

Personally I would try to narrow down the issue a bit more. You could for example send a certain amount of tracking requests to the kubernetes pod and check if all are handled correctly within Matomo. If that is the case, the problem might be somewhere else...

Also you can try to find some help on our forum.

**Comment by LewisReyes** [comment]
Thanks for your reply
Yes, I think it makes sense to run another test site on another Kubernetes Cluster and check how Matomo handles it. I'd be grateful to get some expertise advice on the following matters:
- which test is best for traffic generation
- what type of logs to pay attention to in Matomo (how to find unrecorded visits)
