### ISSUE TITLE
Fix Referrers.getKeywordsFromSearchEngineId API for invalid subtable ids

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19817]
URL to reproduce: https://demo.matomo.cloud/?date=2010-04-22&filter_limit=25&format=JSON&idSite=1&idSubtable=34&method=Referers.getKeywordsFromSearchEngineId&module=API&period=month&token_auth=anonymous

GET: {"date":"2010-04-22","filter_limit":"25","format":"JSON","idSite":"1","idSubtable":"34","method":"Referers.getKeywordsFromSearchEngineId","module":"API","period":"month","token_auth":"anonymous"}

See stack trace

> Error: {"message":"Call to a member function getColumn() on bool","file":"plugins\/Referrers\/API.php","line":332,"request_id":"a01d2","backtrace":" on plugins\/Referrers\/API.php(332)\n#0 [internal function]: Piwik\\Plugins\\Referrers\\API->getKeywordsFromSearchEngineId('1', 'month', '2010-04-22', '34', false)\n#1 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#2 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#3 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#4 core\/API\/Request.php(266): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getKeywordsFrom...', Array)\n#5 plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#6 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#7 core\/FrontController.php(631): call_user_func_array(Array, Array)\n#8 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#9 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#10 index.php(25): require_once('c...')\n#11 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(190): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

**Comment by sgiehl** [comment]
Seems that occurs when a subtable is requested that doesn't exist. Will provide a simple fix for that.
