### ISSUE TITLE
4.12.0 file integrity fail

### ISSUE THREAD

**Issue by n2N8Z** [piwik/piwik#19826]
## Expected Behavior
When there was no file integrity issue before an upgrade, there should not be one afterward.

## Current Behavior
After 4.12.0 upgrade there are 3 files that are flagged as not expected.
```
Files were found in your Matomo, but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/matomo/matomo-php-tracker/run_tests.sh
File to delete: vendor/phpmailer/phpmailer/language/phpmailer.lang-ch.php
File to delete: vendor/geoip2/geoip2/.php-cs-fixer.php


To delete all these files at once, you can run this command:
rm "/var/www/matomo/vendor/matomo/matomo-php-tracker/run_tests.sh" "/var/www/matomo/vendor/phpmailer/phpmailer/language/phpmailer.lang-ch.php" "/var/www/matomo/vendor/geoip2/geoip2/.php-cs-fixer.php"
```

## Steps to Reproduce (for Bugs)
1. Have 4.11.0 installed.
2. Install 4.12.0 over the top.

## Your Environment
* Matomo Version: 4.12.0
* PHP Version: 8.1.10 
* Server Operating System: CentOS Linux release 7.9.2009 (Core)
* Additionally installed plugins:
```
#### Plugins Activated:
 API, Actions, Annotations, Bandwidth 4.0.2, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, Feedback, FlagCounter 4.0.0, GeoIp2, Goals, GroupPermissions 4.0.5, Heartbeat, IPReports 4.2.0, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, KPIWidgets 1.1.1, LanguagesManager, Live, LiveTab 4.0.1, LogViewer 4.1.1, Login, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, ProfessionalServices, Proxy, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, TasksTimetable 4.0.2, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize
```

**Comment by Findus23** [comment]
This might be related to https://github.com/matomo-org/matomo/issues/18435

**Comment by n2N8Z** [comment]
> This might be related to #18435

Yeah sounds the same.  Two of the files in this case seem useful though (run_tests.sh, phpmailer.lang-ch.php).

**Comment by sgiehl** [comment]
@n2N8Z I'll close this as duplicate for now.
The files you mentioned can be deleted safely.

**Comment by n2N8Z** [comment]
While I agree the cause is the same as #18435, but what is the resolution to the specific files that are flagged in 4.12.0, can they really be deleted without impacting any functionality ?

**Comment by sgiehl** [comment]
The files you have mentioned in the issue description can be removed safely.
