### ISSUE TITLE
Allow empty excludedReferrers on the global setting

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#19833]
reported in https://forum.matomo.org/t/the-address-is-not-a-valid-url/47725 and reproduced on 4.12.0

If e.g. the "Global list of excluded referrers" is empty, the form can't be saved:
![grafik](https://user-images.githubusercontent.com/6266037/194755276-41ddf823-5854-4edc-a482-3a4d72576a10.png)

related to #19302

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/the-address-is-not-a-valid-url/47725/3

**Comment by WM-Loose** [comment]
on all installations after update the same problem!

**Comment by peterhashair** [comment]
Quickly did a PR for this one, just wondering, once the global setting is successfully saved, should we show a success notification on the top?
