### ISSUE TITLE
Analyze Geo Location before anomynize IP address

### ISSUE THREAD

**Issue by plexmaniax** [piwik/piwik#19831]
Matomo should set the geo data (flags) before anonymize the ipaddress, to prevent mismatches.

## Expected Behavior

Matoma should analyze the geo data befor anomynize the ip address. It's important for reporting.

## Current Behavior

At the moment matomo anomynized the ipaddress and then it decides which country belongs to this ipaddress.
That is why there was the following error

217.150.XXX.XXX has sent a request to the webserver (this IP belongs to a swiss provider)
217.150.0.0 was shown in matomo with the russian flag

So even if we had no traffic from russia, we got a report in matomo.

**Comment by sgiehl** [comment]
Hi @plexmaniax 
It should actually be possible in the privacy settings to configure if Matomo should use the anonymized IP address for geolocation or not. So changing that should fix your problem for future visits.
