### ISSUE TITLE
Need better version detection for macOS

### ISSUE THREAD

**Issue by KingsLine** [piwik/piwik#19832]
I am using the latest version of Matomo (4.12.0) and have noticed for awhile now that every version of macOS since Catalina (10.15) is reported as 10.15. While, in fact, Big Sur (macOS 11.0 released in 2020) and Monterey (macOS 12.0 released in 2021) are subsequent releases to Catalina. 

![Matomo_stuck_10 15](https://user-images.githubusercontent.com/52168264/194671279-5518276a-3177-453c-96b9-4713f0d54262.png)

I have confirmed this via BrowserStack by testing in a clean browser environment using macOS 12.2.1. Matomo reports it as a visit from a macOS 10.15 device. 

Someone must have noticed this, right? Is this just my installation somehow?

**Comment by Findus23** [comment]
Hi,

Can you share the user agent your browser is sending to Matomo? (And which browser you are using)
(e.g. by visiting https://devicedetector.lw1.at/)

If that's what the user agent is telling Matomo (and if I remember Apple is intentionally freezing the UA), there is not much that can be done here.

**Comment by KingsLine** [comment]
Ah, I see now. 

Yes, here is the UA string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15.

So it appears it's an operating system limitation as this happens in both the latest versions of Safari and Chrome on macOS 12.6.

**Comment by KingsLine** [comment]
Update: it appears that Matomo can sniff the OS version from Chrome (due to JSON/headers) but not Safari on macOS. I confirmed this using BrowserStack. So, apparently, I have a bunch of visitors using Safari.

**Comment by sgiehl** [comment]
@KingsLine with Matomo 4.12 we have added support for client hints. In browsers using client hints like chrome, it might be possible to detect the correct OS version using such now. For Safari and other brothers not supporting client hints, there is actually not much we can do, as the useragent reports the incorrect version...
