### ISSUE TITLE
DeviceDetector Exception, $clientHints null, should be array

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#19849]
Exception with queued tracking - I suspect the queuedTracking Plugin to be the reason for the Exception: 

Uncaught exception in /home/users/xxx/www/stats/core/DeviceDetector/DeviceDetectorFactory.php line 28:
Piwik\DeviceDetector\DeviceDetectorFactory::makeInstance(): Argument #2 ($clientHints) must be of type array, null given, called in /home/users/xxx/www/stats/core/Tracker/VisitExcluded.php on line 193

When updated from an older version, requests of an "older format" may have been still present in the queue and could not be processed further.

## Expected Behavior

Piwik/Request getClientHints() should return an empty array, if no data was found, not null, because for DeviceDetectorFactory::makeInstance(), $clientHints has to be an array.

## Current Behavior

Exception is thrown, Queue handling stops.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.12 (updated from 4.5)
* PHP Version: 8
* Server Operating System: Debian
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by Findus23** [comment]
Could this be the same as https://github.com/matomo-org/plugin-QueuedTracking/issues/192 and the linked forum thread there?
