### ISSUE TITLE
Update Semver dependency

### ISSUE THREAD

**Issue by SOMERSOFTAndrewCrook** [piwik/piwik#19846]
In composer.json it has the line
```json
        "composer/semver": "~1.3.0",
```
and in composer.lock
```json
            "name": "composer/semver",
            "version": "1.3.0",
            "source": {
                "type": "git",
                "url": "https://github.com/composer/semver.git",
                "reference": "df4463baa9f44fe6cf0a6da4fde2934d4c0a2747"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/composer/semver/zipball/df4463baa9f44fe6cf0a6da4fde2934d4c0a2747",
                "reference": "df4463baa9f44fe6cf0a6da4fde2934d4c0a2747",
                "shasum": ""
            },
            "require": {
                "php": "^5.3.2 || ^7.0"
            },
```
This commit [Added support for php8 ](https://github.com/composer/semver/commit/df3d4b187b08b6bb06966afa3069bef3dad6f4e1) indicated it was introduced with verison3.3.2.

## Expected Behavior

Should be able to composer install when using using PHP 8.

## Current Behavior

semver is is flagged as incompatible.

## Possible Solution

Update composer.json
```json
        "composer/semver": ">=3.3.2",
```

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version: 8.1
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
We are actually only using the VersionParser, which seems to run on all versions. At least we don't have any issues when running tests on PHP 8.1.
I think this might be something we could consider doing as part of Matomo 5. ping @justinvelluppillai

**Comment by SOMERSOFTAndrewCrook** [comment]
@sgiehl Thank you for the reply, could it be a part of 4.12.1 release? It would interesting to find out how many sites use the composer install to build the application.

**Comment by sgiehl** [comment]
We most likely won't update vendor libs with patch releases. Also installing Matomo using composer is not the recommended way to use it, so I don't think many people are doing that. At least we did not yet get any similar report.

**Comment by konradmichalik** [comment]
We get the same problem here, want to try to install matomo via composer and run the application with php 8. 
Is it possible to fix this issue while allowing _composer/semver_ 1.7.2?
https://packagist.org/packages/composer/semver#1.7.2
