### ISSUE TITLE
in User IDs report: remove columns "Unique Visitors" and "Users"

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19850]
## Expected Behavior
Do not display values that don't mean anything

## Current Behavior
Go:
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=2022-10-10&idSite=1&category=General_Visitors&subcategory=UserId_UserReportTitle
Click on the **Change Visualization** icon then **Display a table with Visitor engagement metrics**
Then some nonsense data are displayed:
![image](https://user-images.githubusercontent.com/79993552/195150095-d7a55d93-d91e-4c2f-85ae-580dadb7c88a.png)

## Possible Solution
Remove unnecessary columns

## Context
https://forum.matomo.org/t/visitor-engagement-metrics-in-user-ids-table/47770/

## Your Environment
Matomo demo (4.12.0)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/visitor-engagement-metrics-in-user-ids-table/47770/4

**Comment by bx80** [comment]
Thanks for highlighting this @heurteph-ei, you're right - it doesn't make any sense to display those columns on the user IDs list.

**Comment by dzhibas** [comment]
in https://github.com/matomo-org/matomo/pull/21404 this should be fixed
![image](https://github.com/matomo-org/matomo/assets/400147/594df90b-4dd7-4240-83cc-b1a3a99d03cb)

**Comment by dzhibas** [comment]
PR to 5.x-dev https://github.com/matomo-org/matomo/pull/21405
