### ISSUE TITLE
Problème d'archivage 

### ISSUE THREAD

**Issue by IllonaRZ** [piwik/piwik#19854]
lorsque je souhaite consulter le rapport complet, seul le journal de visites contient des informations, le reste est à 0 depuis le 21 septembre alors que nous avons des visites sur le site comme peut le témoigner le journal de visites.

Aussi, à l'ouverture du rapport complets, deux messages apparaissent :

"L'archivage de votre rapport ne s'est pas exécuté correctement,"apprenez-en plus sur comment générer vos rapports."

"Il semble que les rapports pour cette période n'aient pas encore été traités. Voulez-vous voir ce qui se passe maintenant ? Consultez le journal Visits ou choisissez une autre période jusqu'à ce que les rapports soient générés"

Pouvez vous m'aider ?

**Comment by heurteph-ei** [comment]
Bonjour,

Pour ce genre de problème (qui n'est pas encore un bug), il est préférable d'utiliser le forum :
https://forum.matomo.org/

Comment avez-vous configuré l'archivage ?
Y a-t-il des erreurs dans le fichier de log des erreurs de Matomo pour l'archivage ?
Quel est votre environnement ? (Version de Matomo, plugins installés, version de PHP, Apache, Serveur, etc.)

**Comment by IllonaRZ** [comment]
Je viens de laisser le même message sur le forum.

Il s'agit du plugin Matomo sur WordPress. je n'ai rien configuré de spécial au niveau de l'archivage et lorsque je fais un archivage manuel une très longue liste d'erreurs apparaît

**Comment by sgiehl** [comment]
I'll close this one. As @heurteph-ei mentioned, it's better to first use the forum for such kind of requests.
If you are able to determine a bug in Matomo for wordpress, the correct place for reporting it would then be https://github.com/matomo-org/matomo-for-wordpress/issues
