### ISSUE TITLE
Fix array to string conversion warning in userOptOut

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#19852]
## Expected Behavior
No error, no warning

## Current Behavior
After 4.12 update:
```
WARNING: /tmp/templates_c/08/086087ec6b1f49536aca0dde3949a877ff4f4f1d35c2087ab45bea9f74ddf14d.php(48): Notice - Array to string conversion - Matomo 4.12.0 - Please report this message in the Matomo forums: https://forum.matomo.org/ (please do a search first as it might have been reported already) (Module: PrivacyManager, Action: usersOptOut, In CLI mode: false)
```

Also (in line 48) ?
```
echo \Piwik\piwik_escape_filter($this->env, (isset($context["language"]) || array_key_exists("language", $context) ? $context["language"] : (function () { throw new RuntimeError('Variable "language" does not exist.', 2, $this->source); })()), "html", null, true);
```

## Possible Solution
Fix the bug 🤣 

## Steps to Reproduce (for Bugs)
Module: PrivacyManager, Action: usersOptOut, In CLI mode: false?

## Context
https://forum.matomo.org/t/mise-a-jour-4-12-message-pour-info-pas-bloquant/47700

## Your Environment
* Matomo Version: 4.12.0 after update
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/mise-a-jour-4-12-message-pour-info-pas-bloquant/47700/3

**Comment by sgiehl** [comment]
this might related to #19848

**Comment by bx80** [comment]
Thanks for logging this @heurteph-ei  :+1: It's a quick fix, I've created a PR for 4.12.1

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/global-websites-settings-warning-libs-zend-db-statement-pdo-php-229-warning/47848/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/global-optout-is-not-working-this-isuseroptedout-always-return-false/47834/5

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/global-optout-is-not-working-this-isuseroptedout-always-return-false/47834/6
