### ISSUE TITLE
Matomo not starting in Azure WebApp/404

### ISSUE THREAD

**Issue by LeopoldLerch** [piwik/piwik#19868]
Hi,
we want to Host Matomo in an Azure Web App. So we set one up, using PHP 8.1, uploaded Matomo, but it does not start. We always get an 404-Page (not found) when we want to access it.

However, the files are uploaded in the correct folder, we can eg. access the robots.txt manually. Also, during Upload of the files we can access the website and get an Error-Page from Matomo stating that the composer-plugin is not there. However, as soon as the upload is finished, we get only an 404-Error-Page from nginx.

We tried various uploads (FTP, SSH, or publshing via Azure-Powershell). All ends up the same issue.

Does anybody have some Ideas?

thx

**Comment by sgiehl** [comment]
Hi @LeopoldLerch 
We unfortunately can't provide support for such specific use cases on GitHub. We are using this issue tracker for bugs and feature requests only.
You may try to get some help on our forum instead: https://forum.matomo.org/
Thanks,
