### ISSUE TITLE
Update autocomplete values

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#19872]
In Matomo 4.12.0 it looks as though some fields are being auto filled by browser or browser extensions with the username. 
For example in the Measurables admin area browser autofill now enters the username in the search field:
![image](https://user-images.githubusercontent.com/20905821/196292649-6ea2d736-c7d5-4589-9c7e-cfb7efacc346.png)

I tested this in 4.11.0 and the behaviour was not the same, but after updating to 4.12.0 my browser password manager extension could auto fill the search bar with a username. I've tested a few different places where a search bar or input field is present and it seems to only affect the search input in the measurables.

This would mainly be an issue where people have browsers or extensions configured to autofill without interaction.

**Comment by peterhashair** [comment]
Looks like there is a regression here `autocomplete="false"`, should be `autocomplete="off"`.
