### ISSUE TITLE
Fix for opt-out toggling on page load and incorrect default state

### ISSUE THREAD

**Issue by KiwiKilian** [piwik/piwik#19879]
## Expected Behavior
The opt-out checkbox should only change when clicked. The checkbox and text should display the actual current state of the users choosen settings.

- If the cookie `mtm_consent_removed` is set, the opt-out text should state, the user has opted-out. The checkbox should **not** be checked and say: "You are currently opted out. Check this box to opt-in."
- If there is **no** `mtm_consent_removed` cookie set, the checkbox should be checked and the text should say: "You are not opted out. Uncheck this box to opt-out."

## Current Behavior
Everytime the page with the opt-out is loaded, the state of the opt-out is toggled. So if there is no `mtm_consent_removed` cookie set, it will be set. Meanwhile the checkbox and text displays the opposite of the cookie state. It seems like the JS is just toggling the state everytime.

## Steps to Reproduce (for Bugs)
1. Create a page that only inlcudes the tracking snippet and the opt-out snippet
2. Simply reload the page multiple times

## Context
We are trying to implement the cookieless, opt-in method. Therefore the tracking code has set the following options:
```js
    _paq.push(["setDoNotTrack", true]);
    _paq.push(["disableCookies"]);
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
```
No other cookies are set for the domain. There are results beeing tracked by this example page.

(The different single and double quote styles are actually generated by Matomo UI).

## Your Environment
* Matomo Version: 4.12.1 (previously also occured on 4.12.0)
* PHP Version: 7.4.3
* Server Operating System: Linux
* Additionally installed plugins: CustomVariables
* Browser: Chrome, Firefox
* Operating System: macOS

**Comment by heurteph-ei** [comment]
Is it related to https://forum.matomo.org/t/global-optout-is-not-working-this-isuseroptedout-always-return-false/47834 ?

**Comment by justinvelluppillai** [comment]
@bx80 can you please take a look here and see if we need to promote this issue?

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/global-optout-is-not-working-this-isuseroptedout-always-return-false/47834/6

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/strange-opt-out-issues/48252/2

**Comment by KiwiKilian** [comment]
Thank you very much for the fix. Everything is working fine now with 4.13.0! 🚀

**Comment by bx80** [comment]
@KiwiKilian Appreciate your taking the time to confirm that the fix worked - always great to hear! :smiley:
