### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list'

### ISSUE THREAD

**Issue by micker** [piwik/piwik#19886]
after update to 4.12.1
i have this error when i try to create a new site 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list'
thanks for any help

**Comment by feralhawk** [comment]
Same issue here when trying to create a new variable in tag manager. Database reupdate did not solve the problem.

**Comment by heurteph-ei** [comment]
Seems to be linked to #19887 and/or https://github.com/matomo-org/tag-manager/issues/557

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/facebook-pixel-tag-manager-and-complianz/47927/2

**Comment by AltamashShaikh** [comment]
Hey everyone, Matomo 4.12.2 was released today and should fix the issue.
Closing the issue for now, please let us know here if you are still facing issues after upgrade

**Comment by thomasstr** [comment]
After update this issue still persists. Also when trying to create triggers in Tag Manager.

**Comment by AltamashShaikh** [comment]
@thomasstr Did you run `./console core:update` after the update ?

**Comment by thomasstr** [comment]
Yes, It ran it through the automatically updater. If I can supply with anything else, let me know.

**Comment by AltamashShaikh** [comment]
Do you have access to your Mysql and command line ?

**Comment by thomasstr** [comment]
> Do you have access to your Mysql and command line ?

Yes I do.

**Comment by AltamashShaikh** [comment]
> > Do you have access to your Mysql and command line ?
> 
> Yes I do.

Please check the version of plugin using this query `SELECT * FROM matomo_option where option_name='version_tagmanager'`
If the option_value is `4.12.2` update it to `4.11.0` chances are that the update didn't run properly
Next execute this command in your cli `./console core:update` and check if it fixes the issue or not

**Comment by thomasstr** [comment]
It added the columns now. Thanks for the help.

`
./console core:update

    *** Update ***

    Database Upgrade Required

    Your Matomo database is out-of-date, and must be upgraded before you can continue.

    The following plugins will be updated: TagManager.

    *** Note: this is a Dry Run ***

    ALTER TABLE `matomo_tagmanager_tag` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;
    ALTER TABLE `matomo_tagmanager_trigger` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;
    ALTER TABLE `matomo_tagmanager_variable` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;

    *** End of Dry Run ***

A database upgrade is required. Execute update? (y/N) y

Starting the database upgrade process now. This may take a while, so please be patient.

    *** Update ***

    Database Upgrade Required

    Your Matomo database is out-of-date, and must be upgraded before you can continue.

    The following plugins will be updated: TagManager.

    The database upgrade process may take a while, so please be patient.

  Executing ALTER TABLE `matomo_tagmanager_tag` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;... Done. [1 / 3]
  Executing ALTER TABLE `matomo_tagmanager_trigger` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;... Done. [2 / 3]
  Executing ALTER TABLE `matomo_tagmanager_variable` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;... Done. [3 / 3]

Matomo has been successfully updated!`

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/mysqli-prepare-error-unknown-column-description-in-field-list/47919/7

**Comment by develth** [comment]
> Please check the version of plugin using this query `SELECT * FROM matomo_option where option_name='version_tagmanager'` If the option_value is `4.12.2` update it to `4.11.0` chances are that the update didn't run properly Next execute this command in your cli `./console core:update` and check if it fixes the issue or not

That solved it for now. Thanks!

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/sql-unknown-column-description/54324/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/tag-manager-create-new-variable-sql-problem/54465/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/problems-updating-from-4-16-0-to-5-0-0/54602/2

**Comment by MoralCode** [comment]
> Please check the version of plugin using this query `SELECT * FROM matomo_option where option_name='version_tagmanager'` If the option_value is `4.12.2` update it to `4.11.0` chances are that the update didn't run properly Next execute this command in your cli `./console core:update` and check if it fixes the issue or not

This worked for me with only a minor change in the table name (my tables had it as `option` - i.e. without the `matomo_`prefix). In my case the value was stuck on 4.16.0. setting it back to 4.11.0 and running a core:update fixed this issue for me. Seems like i must have been affected by this earlier and it went undetected until now.

Thanks!
