### ISSUE TITLE
New Opt-out solution: checkbox is OFF per default even though I'm being tracked

### ISSUE THREAD

**Issue by utrautmann** [piwik/piwik#19888]
We are using Matomo 4.12.1 .

We integrated the new script to Opt-out without the previous iframe (#17452).
Since we track without cookies and do not use a consent tool, the behavior is incorrect.
In the default case, the checkbox is off and it means that I would not be tracked.

## Steps to Reproduce 

1. Integrate Tracking-script without consent tool
2. integrate Opt-out script with DIV-Container
3. The Opt-out dialog shows that I would not be tracked. But that is wrong. I'm being tracked.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/opt-out-using-the-matomo-javascript-tracker-code-is-triggert-by-page-reload/47768/5

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/global-optout-is-not-working-this-isuseroptedout-always-return-false/47834/6

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/strange-opt-out-issues/48252/2
