### ISSUE TITLE
Avoid escaping of characters other than "

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#19899]
When the MySQL password contains special characters (e.g. `'`) and a plugin is disabled (or presumably any other action is taken that modifies config.ini.php), some special characters get escaped with `\'` and Matomo breaks with a `Database access denied` as the password isn't correct anymore.

Matomo 4.12.1 

This might be a bug in https://github.com/matomo-org/component-ini instead of Matomo itself and might be related to https://github.com/matomo-org/plugin-LoginLdap/issues/308

**Comment by peterhashair** [comment]
@Findus23 thanks for reporting this, I can reproduce this one locally, I will put this into the current milestone.

Notes this maybe related to this PR https://github.com/matomo-org/component-ini/pull/17/files.
