### ISSUE TITLE
cannot download HTTP file

### ISSUE THREAD

**Issue by rockbenben** [piwik/piwik#19898]
When I click on the http type download link on the page with matomo, it returns nothing. I tried changing the link from http to https, so it can be downloaded properly.

Will we be able to make Matomo compatible with HTTP downloads? 

## Your Environment
* Matomo Version: 4.12.2
* PHP Version:7.4.30
* Server Operating System: CentOS 8.4.2105 x86_64(Py3.7.8)

* Browser: Chrome 106.0.5249.119
* Operating System: Windows 11

**Comment by bx80** [comment]
Hi @rockbenben, thanks for reaching out. 

Could you explain a bit more which page with Matomo has the http download link that does not work for you? Is this on www.matomo.org or an update page on your Matomo installation? If you could post the full link or a screenshot that would help us pinpoint the issue.

**Comment by rockbenben** [comment]
Here's the page code and demo. The bug occurs when downloading http files using the  Chrome browser's own download manager.
Demo Page: https://stackblitz.com/edit/web-platform-5muhj8?file=index.html
![image](https://user-images.githubusercontent.com/28252913/198160874-566ede96-3812-4dd6-9404-77324bb4849e.png)

**Comment by sgiehl** [comment]
@rockbenben If your demo page is on https, ir might be possible that chrome itself blocks clicks/downloads on http links/downloads due to an insecure context switch. For Matomo itself it should not be relevant if the link if http or https.

**Comment by rockbenben** [comment]
> @rockbenben If your demo page is on https, ir might be possible that chrome itself blocks clicks/downloads on http links/downloads due to an insecure context switch. For Matomo itself it should not be relevant if the link if http or https.

got it, Thanks.
