### ISSUE TITLE
Improve performance of segment queries when multiple action segment parts are used

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19897]
Given a segment like this: 

```
pageUrl!@https%253A%252F%252Ftest.matomo.org%252F;pageUrl!@https%253A%252F%252Fmatomo.org%252Fevent;pageUrl!@https%253A%252F%252Fmatomo.org%252Fsearch;pageUrl!@https%253A%252F%252Fmatomo.org%252Forga;pageUrl!@https%253A%252F%252Fmatomo.org%252Ffoo;pageUrl!@https%253A%252F%252Fmatomo.org%252Fbar;pageUrl!@https%253A%252F%252Fmatomo.org%252Ftesdlweke;pageUrl!@https%253A%252F%252Fmatomo.org%252Fhello-world;pageUrl!@https%253A%252F%252Fmatomo.org%252Fvideo;pageUrl!@https%253A%252F%252Fmatomo.org%252Fblog;pageUrl!@https%253A%252F%252Fmatomo.org%252F...;pageUrl!@https%253A%252F%252Fmatomo.org%252Fabout;pageUrl!@https%253A%252F%252Fmatomo.org%252Fcart
```

The resulting query takes many hours to execute even on a smaller data set (on Aurora). In this case there are around:

* 75K log_action entries
* 20K log_visit entries
* 1M log_link_visit_action entries

It's not too much data and wouldn't be expected that this query takes that long.

The resulting where clause looks roughly like this:

![archive](https://user-images.githubusercontent.com/273120/197084495-de6e6c62-f3a9-4a78-8833-0bf96621d96a.png)

See https://github.com/matomo-org/matomo/issues/19581 and https://github.com/matomo-org/matomo/issues/8850 and https://github.com/matomo-org/matomo/issues/8867 we know that action name queries are slow. However, we could see a big improvement for these kind of queries if we may be able to merge them into one queries instead of multiple full table scans.

Maybe we can do something like `where idaction_url in (select idaction from log_action where type = 1 and (name like '%...%' or name like '%...%' or name like '%...%'...))` or if the segment definition was different like `where idaction_url in (select idaction from log_action where type = 1 and (name not like '%...%' and name not like '%...%' and name not like '%...%'...))`.

The goal would be to minimise the amount of full table scans as much as possible and group the queries together as much as possible so that the query completes a lot faster.

Above is running slow on a custom report with a segment filter attached but the same should be happening if this was a regular segment. Let me know if there are any questions or if anything is unclear.

Note:
As part of this PR we could remove the segment subquery cache logic `enable_segments_subquery_cache` (NOT the segment cache `enable_segments_cache` which is still needed). Since we have `enable_segments_cache` I can't really think of any benefit of the `enable_segments_subquery_cache` logic.

Note 2:
It may be easier to rewrite this to use joins instead of subqueries see the attempted solution in https://github.com/matomo-org/matomo/compare/m19897

**Comment by bx80** [comment]
Hi @tsteur, thanks for the explanation, that makes sense. Would you see this approach as preferable to implementing a segment link table or some sort of persistent segment <-> action cache as discussed in #19581? Or as a short-medium term workaround?

**Comment by tsteur** [comment]
It depends on the effort. If we could improve this query fairly "easily", then I would implement this one first as it would prevent the worst case where we have not just one slow log_action.name contains but multiple

**Comment by tsteur** [comment]
Just FYI I had a look into this time boxed 90 minutes to see if this is something that can be solved quickly as it could bring some big performance gain in some cases. I hacked some code in https://github.com/matomo-org/matomo/compare/m19897 to see if few changes can make this work. After few minutes noticed it's likely quicker to solve this via joins rather than changing the subqueries. Was adding some quick code (which would need to be refactored and would need at least 1 performance improvement) and the tests were mostly passing except a very few. There's probably quite a few more edge cases to make this really happen. We also need to make sure that we keep "equals and not equals" as fast as it was before.

On the good side it could open few more possible segments that weren't possible before as it would be possible to join in more tables and this way eg segment by goal name, form name, etc if we wanted.
