### ISSUE TITLE
Native mail() function does not work

### ISSUE THREAD

**Issue by Kleppinger** [piwik/piwik#19900]
When using the `mail()` function instead of SMTP, he function returns true, but the mail does not get send. When calling the `mail() `function in the same environment, it works. The issue also occurs in the CLI application. Sendmail is working fine.

## Expected Behavior
When the mail() function returns true, the mail should be sent.

## Current Behavior
The function returns true, but no mail got sent.

## Steps to Reproduce (for Bugs)
1. Make an fresh installation.
2. Configure sendmail
3. Send an mail or use the CLI to send an test-mail. It will return true, but no mail will be sent

## Your Environment

* Matomo Version: 4.12.2
* PHP Version: Tested on 7.4 and 8.1
* Server Operating System: Debian 9
* Additionally installed plugins: None

**Comment by heurteph-ei** [comment]
Was it working on previous version?

**Comment by bx80** [comment]
Hi @Entenlias, thanks for reporting this. Could you please provide the sendmail logs from when Matomo attempts to connect and send the mail?

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. Locally using the native mal function works without problems, so I'd assume this to be a configuration issue on the server.
