### ISSUE TITLE
Prevent exception possibilities in retrieving columns from previous data row

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19903]
See below details

> Error: {"message":"Call to a member function getColumn() on bool","file":"/plugins\/Goals\/Reports\/Get.php","line":197,"request_id":"b9ee3","backtrace":" on /plugins\/Goals\/Reports\/Get.php(197)\n#0 /plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(316): Piwik\\Plugins\\Goals\\Reports\\Get->Piwik\\Plugins\\Goals\\Reports\\{closure}(Array, Array)\n#1 /plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(108): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->fetchConfiguredSparklines()\n#2 /core\/Plugin\/Report.php(320): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->render()\n#3 /plugins\/CoreHome\/Controller.php(60): Piwik\\Plugin\\Report->render()\n#4 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\Goals\\Reports\\Get))\n#5 /core\/FrontController.php(631): call_user_func_array(Array, Array)\n#6 /core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Goals', 'get', Array)\n#7 /core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#8 /index.php(25): require_once('/c...')\n#9 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(190): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: https://demo.matomo.cloud/index.php?forceView=1&viewDataTable=sparklines&module=Goals&action=get&idGoal=6&allow_multiple=0&only_summary=1&idSite=1&period=day&date=yesterday&segment=&showtitle=1&random=7404&isocode=1%3Cu%3Efuzz%3C/u%3Ez%22%20z&ispersis=2%3Cu%3Efuzz%3C/u%3Ez%22%20z&ispublic=3%3Cu%3Efuzz%3C/u%3Ez%22%20z&issue=4%3Cu%3Efuzz%3C/u%3Ez%22%20z&issues=5%3Cu%3Efuzz%3C/u%3Ez%22%20z&isverify=6%3Cu%3Efuzz%3C/u%3Ez%22%20z&it=7%3Cu%3Efuzz%3C/u%3Ez%22%20z&item=8%3Cu%3Efuzz%3C/u%3Ez%22%20z&itemcount=9%3Cu%3Efuzz%3C/u%3Ez%22%20z&itemid=10%3Cu%3Efuzz%3C/u%3Ez%22%20z&itemkey=11%3Cu%3Efuzz%3C/u%3Ez%22%20z&itemname=12%3Cu%3Efuzz%3C/u%3Ez%22%20z&items=13%3Cu%3Efuzz%3C/u%3Ez%22%20z&items_per_page=14%3Cu%3Efuzz%3C/u%3Ez%22%20z&iv=15%3Cu%3Efuzz%3C/u%3Ez%22%20z&j=16%3Cu%3Efuzz%3C/u%3Ez%22%20z&jabber=17%3Cu%3Efuzz%3C/u%3Ez%22%20z&jahr=18%3Cu%3Efuzz%3C/u%3Ez%22%20z&jax=19%3Cu%3Efuzz%3C/u%3Ez%22%20z&jaxl=20%3Cu%3Efuzz%3C/u%3Ez%22%20z&jenkins=21%3Cu%3Efuzz%3C/u%3Ez%22%20z&jform=22%3Cu%3Efuzz%3C/u%3Ez%22%20z&jid=23%3Cu%3Efuzz%3C/u%3Ez%22%20z&jj=24%3Cu%3Efuzz%3C/u%3Ez%22%20z&job=25%3Cu%3Efuzz%3C/u%3Ez%22%20z&join=26%3Cu%3Efuzz%3C/u%3Ez%22%20z&joindate=27%3Cu%3Efuzz%3C/u%3Ez%22%20z&joined=28%3Cu%3Efuzz%3C/u%3Ez%22%20z&joingroup=29%3Cu%3Efuzz%3C/u%3Ez%22%20z&jpeg=30%3Cu%3Efuzz%3C/u%3Ez%22%20z&js=31%3Cu%3Efuzz%3C/u%3Ez%22%20z&json=32%3Cu%3Efuzz%3C/u%3Ez%22%20z&jsonp=33%3Cu%3Efuzz%3C/u%3Ez%22%20z&jufinal=34%3Cu%3Efuzz%3C/u%3Ez%22%20z&jump=35%3Cu%3Efuzz%3C/u%3Ez%22%20z&jupart=36%3Cu%3Efuzz%3C/u%3Ez%22%20z&k=37%3Cu%3Efuzz%3C/u%3Ez%22%20z&karma=38%3Cu%3Efuzz%3C/u%3Ez%22%20z&katid=39%3Cu%3Efuzz%3C/u%3Ez%22%20z&kb=40%3Cu%3Efuzz%3C/u%3Ez%22%20z&keep=41%3Cu%3Efuzz%3C/u%3Ez%22%20z&keeppass=42%3Cu%3Efuzz%3C/u%3Ez%22%20z&key=43%3Cu%3Efuzz%3C/u%3Ez%22%20z&keydata=44%3Cu%3Efuzz%3C/u%3Ez%22%20z&keyid=45%3Cu%3Efuzz%3C/u%3Ez%22%20z&keylen=46%3Cu%3Efuzz%3C/u%3Ez%22%20z&keyname=47%3Cu%3Efuzz%3C/u%3Ez%22%20z&keys=48%3Cu%3Efuzz%3C/u%3Ez%22%20z&keystring=49%3Cu%3Efuzz%3C/u%3Ez%22%20z&keytype=50%3Cu%3Efuzz%3C/u%3Ez%22%20z&keyword=51%3Cu%3Efuzz%3C/u%3Ez%22%20z&keywords=52%3Cu%3Efuzz%3C/u%3Ez%22%20z&kick=53%3Cu%3Efuzz%3C/u%3Ez%22%20z&kid=54%3Cu%3Efuzz%3C/u%3Ez%22%20z&kil=55%3Cu%3Efuzz%3C/u%3Ez%22%20z&kill=56%3Cu%3Efuzz%3C/u%3Ez%22%20z&killfilter=57%3Cu%3Efuzz%3C/u%3Ez%22%20z&kim=58%3Cu%3Efuzz%3C/u%3Ez%22%20z&kime=59%3Cu%3Efuzz%3C/u%3Ez%22%20z&kind=60%3Cu%3Efuzz%3C/u%3Ez%22%20z&king=61%3Cu%3Efuzz%3C/u%3Ez%22%20z&kod=62%3Cu%3Efuzz%3C/u%3Ez%22%20z&kr=63%3Cu%3Efuzz%3C/u%3Ez%22%20z&kstart=64%3Cu%3Efuzz%3C/u%3Ez%22%20z&kw=65%3Cu%3Efuzz%3C/u%3Ez%22%20z&l=66%3Cu%3Efuzz%3C/u%3Ez%22%20z&labdef=67%3Cu%3Efuzz%3C/u%3Ez%22%20z&label=68%3Cu%3Efuzz%3C/u%3Ez%22%20z&labels=69%3Cu%3Efuzz%3C/u%3Ez%22%20z&laggif=70%3Cu%3Efuzz%3C/u%3Ez%22%20z&lan=71%3Cu%3Efuzz%3C/u%3Ez%22%20z&landscape=72%3Cu%3Efuzz%3C/u%3Ez%22%20z&lane=73%3Cu%3Efuzz%3C/u%3Ez%22%20z&lanes=74%3Cu%3Efuzz%3C/u%3Ez%22%20z&lang=75%3Cu%3Efuzz%3C/u%3Ez%22%20z&langname=76%3Cu%3Efuzz%3C/u%3Ez%22%20z&langs=77%3Cu%3Efuzz%3C/u%3Ez%22%20z&language=78%3Cu%3Efuzz%3C/u%3Ez%22%20z&languages=79%3Cu%3Efuzz%3C/u%3Ez%22%20z&last=80%3Cu%3Efuzz%3C/u%3Ez%22%20z

> Referrer: NONE

> GET: {"forceView":"1","viewDataTable":"sparklines","module":"Goals","action":"get","idGoal":"6","allow_multiple":"0","only_summary":"1","idSite":"1","period":"day","date":"yesterday","segment":"","showtitle":"1","random":"7404","isocode":"1<u>fuzz<\/u>z\" z","ispersis":"2<u>fuzz<\/u>z\" z","ispublic":"3<u>fuzz<\/u>z\" z","issue":"4<u>fuzz<\/u>z\" z","issues":"5<u>fuzz<\/u>z\" z","isverify":"6<u>fuzz<\/u>z\" z","it":"7<u>fuzz<\/u>z\" z","item":"8<u>fuzz<\/u>z\" z","itemcount":"9<u>fuzz<\/u>z\" z","itemid":"10<u>fuzz<\/u>z\" z","itemkey":"11<u>fuzz<\/u>z\" z","itemname":"12<u>fuzz<\/u>z\" z","items":"13<u>fuzz<\/u>z\" z","items_per_page":"14<u>fuzz<\/u>z\" z","iv":"15<u>fuzz<\/u>z\" z","j":"16<u>fuzz<\/u>z\" z","jabber":"17<u>fuzz<\/u>z\" z","jahr":"18<u>fuzz<\/u>z\" z","jax":"19<u>fuzz<\/u>z\" z","jaxl":"20<u>fuzz<\/u>z\" z","jenkins":"21<u>fuzz<\/u>z\" z","jform":"22<u>fuzz<\/u>z\" z","jid":"23<u>fuzz<\/u>z\" z","jj":"24<u>fuzz<\/u>z\" z","job":"25<u>fuzz<\/u>z\" z","join":"26<u>fuzz<\/u>z\" z","joindate":"27<u>fuzz<\/u>z\" z","joined":"28<u>fuzz<\/u>z\" z","joingroup":"29<u>fuzz<\/u>z\" z","jpeg":"30<u>fuzz<\/u>z\" z","js":"31<u>fuzz<\/u>z\" z","json":"32<u>fuzz<\/u>z\" z","jsonp":"33<u>fuzz<\/u>z\" z","jufinal":"34<u>fuzz<\/u>z\" z","jump":"35<u>fuzz<\/u>z\" z","jupart":"36<u>fuzz<\/u>z\" z","k":"37<u>fuzz<\/u>z\" z","karma":"38<u>fuzz<\/u>z\" z","katid":"39<u>fuzz<\/u>z\" z","kb":"40<u>fuzz<\/u>z\" z","keep":"41<u>fuzz<\/u>z\" z","keeppass":"42<u>fuzz<\/u>z\" z","key":"43<u>fuzz<\/u>z\" z","keydata":"44<u>fuzz<\/u>z\" z","keyid":"45<u>fuzz<\/u>z\" z","keylen":"46<u>fuzz<\/u>z\" z","keyname":"47<u>fuzz<\/u>z\" z","keys":"48<u>fuzz<\/u>z\" z","keystring":"49<u>fuzz<\/u>z\" z","keytype":"50<u>fuzz<\/u>z\" z","keyword":"51<u>fuzz<\/u>z\" z","keywords":"52<u>fuzz<\/u>z\" z","kick":"53<u>fuzz<\/u>z\" z","kid":"54<u>fuzz<\/u>z\" z","kil":"55<u>fuzz<\/u>z\" z","kill":"56<u>fuzz<\/u>z\" z","killfilter":"57<u>fuzz<\/u>z\" z","kim":"58<u>fuzz<\/u>z\" z","kime":"59<u>fuzz<\/u>z\" z","kind":"60<u>fuzz<\/u>z\" z","king":"61<u>fuzz<\/u>z\" z","kod":"62<u>fuzz<\/u>z\" z","kr":"63<u>fuzz<\/u>z\" z","kstart":"64<u>fuzz<\/u>z\" z","kw":"65<u>fuzz<\/u>z\" z","l":"66<u>fuzz<\/u>z\" z","labdef":"67<u>fuzz<\/u>z\" z","label":"68<u>fuzz<\/u>z\" z","labels":"69<u>fuzz<\/u>z\" z","laggif":"70<u>fuzz<\/u>z\" z","lan":"71<u>fuzz<\/u>z\" z","landscape":"72<u>fuzz<\/u>z\" z","lane":"73<u>fuzz<\/u>z\" z","lanes":"74<u>fuzz<\/u>z\" z","lang":"75<u>fuzz<\/u>z\" z","langname":"76<u>fuzz<\/u>z\" z","langs":"77<u>fuzz<\/u>z\" z","language":"78<u>fuzz<\/u>z\" z","languages":"79<u>fuzz<\/u>z\" z","last":"80<u>fuzz<\/u>z\" z"}

**Comment by heurteph-ei** [comment]
isn't is the same as: #19817 ?

**Comment by bx80** [comment]
Very similar @heurteph-ei, I think #19817 was related to referrers, this is the same method but a different location - it could be a similar cause.
