### ISSUE TITLE
Fix value of delete_logs_enable not displayed correctly in UI

### ISSUE THREAD

**Issue by sebastian-berlin-wmse** [piwik/piwik#19919]
The settings for "Regularly delete old raw data", under "Privacy" -> "Anonymize data", doesn't show the correct value. Saving changes doesn't change settings in config/config.ini.php.

# Steps to reproduce
1. Click "Administration" in the top bar.
2. Click "Privacy" in the menu on the left, then "Anonymize data".
3. Under "Regularly delete old raw data", check "Regularly delete old raw data from the database".
4. Click "Save".
5. Reload the page.

# Expected result
"Regularly delete old raw data from the database" is checked.

# Actual result
"Regularly delete old raw data from the database" isn't checked. There is a success message after clicking "Save".

# Additional information
The checkbox is still unchecked after having set the Deletelogs.delete_logs_enable to 1 with `console`, which does add the setting to config/config.ini.php.

This is on a fairly new installation of Matomo (4.12.3) that was migrated from another server. OS is Ubuntu 22.04.1.

**Comment by sgiehl** [comment]
Hi @sebastian-berlin-wmse 
This might be a bit confusing. But for those settings, the setting done in UI is actually stored as an option in the database.
So the setting from config is only used, if there is no setting in the database. If you want to configure such value in the config only, please set `enable_delete_old_data_settings_admin = 0`, which will disable the UI and force the config settings to be used.

**Comment by sebastian-berlin-wmse** [comment]
Thanks for clearing that up. I found the option in the database. It seems to be set as it should when I save, but the web interface doesn't reflect the setting. The checkbox is always unchecked, even when `option_value` for `matomo_option.delete_logs_enable` is 1.

**Comment by sgiehl** [comment]
I'm able to confirm that for `delete_logs_enable` the UI does not reflect the current setting correctly. I'll prepare a fix for that.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/enabling-delete-logs-enable/48129/2
