### ISSUE TITLE
Segment by "Page URL contains" does not work

### ISSUE THREAD

**Issue by bjornarhagen** [piwik/piwik#19911]
We are collecting data from multiple domains/subdomains (example.com, subdomain-1.example.com, subdomain-2.example.com) into a single website/property in Matomo (self hosted instance).

If I look at Behaviour -> Pages I can see all the different page URLs.
I want to create some segments for the different domains/subdomains.
I've created a couple:
* Segment 1: "Page URL" contains "subdomain-1.example.com"
* Segment 2: "Page URL" contains "subdomain-2.example.com"

## Expected Behavior

When I view Segment 1, I expect to only see page URLs that contain "subdomain-1.example.com", as that is how the segment is configured.

When I view Segment 2, I expect to only see page URLs that contain "subdomain-2.example.com", as that is how the segment is configured.

## Current Behavior

When I view Segment 1, I see page URLs with example.com, subdomain-1.example.com and subdomain-2.example.com.

When I view Segment 2, I see page URLs with example.com, subdomain-1.example.com and subdomain-2.example.com.

Thus it seems the segmentation based on page URLs doesn't work as it should.

## Steps to Reproduce (for Bugs)

1. Send data from multiple URLs into a website/property in Matomo
2. Create a custom segment and configure it so that it only includes page urls that contain 1 spesific url
3. Open the segment, it will now show page urls that are not supposed to be included as per the segment configuration.

## Your Environment

* Matomo Version: 4.10.1
* PHP Version: 8.0.20
* Server Operating System: Linux
* Additionally installed plugins: GoogleAnalyticsImporter

* Browser:
* Operating System:

**Comment by bx80** [comment]
Hi @bjornarhagen, thanks for reaching out. 

You might need to [include the subdomain name in the page title](https://developer.matomo.org/guides/tracking-javascript-guide#custom-page-title) for this to work. This [FAQ](https://matomo.org/faq/new-to-piwik/faq_104/) also has some more information about tracking multiple subdomains.
