### ISSUE TITLE
Fix Unknown format specifier in translation in Live plugin

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19928]
see https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Live/lang/id.json#L58 

it says `% 1$s Jika` when it should be `%1$s Jika` and there is a `% 2$s` which should be `%2$s`.

This happened when opening `/index.php?date=today&module=Live&format=html&forceView=1&viewDataTable=VisitorLog&action=getLastVisitsDetails&small=1&period=day&idSite=1&segment=&widget=&showtitle=1` resulting in this error:

> Error: {"message":"Unknown format specifier \"$\"","file":"\/var\/www\/html\/core\/Translation\/Translator.php","line":100,"request_id":"048c8","backtrace":" on \/var\/www\/html\/core\/Translation\/Translator.php(100)\n#0 \/var\/www\/html\/core\/Translation\/Translator.php(100): vsprintf('Tabel ini menun...', Array)\n#1 \/var\/www\/html\/core\/Piwik.php(916): Piwik\\Translation\\Translator->translate('Tabel ini menun...', Array, 'id')\n#2

I'll mark this as a regression as I believe this translation key changed only recently.

I would adjust the translation myself but I don't think I'm set up in Weblate to do it and we need to make sure to have the translation in the next patch release.

Can we maybe cover something like this in a test to detect it proactively?

**Comment by bx80** [comment]
I've assigned this to the next patch release as it's a regression (and should be trivial to fix)

**Comment by sgiehl** [comment]
I have fixed those on weblate so the next translation update should fix it. There actually should be tests to check that stuff, but I think they are currently marked as incomplete instead of failing. Need to check them...

**Comment by mattab** [comment]
This particular issue is fixed. Created follow up  #20181
