### ISSUE TITLE
Headless browser filter

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#19921]
I would like to have an option in matomo default where I can filter out tracking from headless browser. I think this is not too difficult to implement. Is the header empty → don't track.

I don't like tracking visits from headless browsers. They are like bots. However, I don't like plugins either. It would be nice if this feature could be offered as an option in matomo default - to turn on and off.

**Comment by sgiehl** [comment]
@matomoto You might want to have a look at our official plugin https://plugins.matomo.org/TrackingSpamPrevention
That allows blocking e.g. headless browsers.

**Comment by matomoto** [comment]
The internet is so boring... sorry, but i have say no Plugin. **P**lugin is always **P**roblem. Your linked superduper boring plugin calls 5 external server - the cloud server. Sorry, think you i am stupid and allowed my matomo installation to call this server? sorry sorry no sorry. Make a good work and add the Enhancement label. Add a headless browser filter into matomo default is really not a super performance. Here the code: https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/4.x-dev/BrowserDetection.php

**Comment by Findus23** [comment]
> Plugin is always Problem

If you check https://github.com/matomo-org/matomo/tree/4.x-dev/plugins, you can see that nearly all features in Matomo are implemented as plugins (that work exactly like plugins from the marketplace with the only difference of being included and enabled by default). So if a plugin is maintained by the Matomo team, then it won't cause more issues whether it is a core plugin or distributed on the Marketplace. But in the latter case it won't increase the (UI, UX, code, beginner-friendliness) complexity of Matomo for those who are not interested in that feature.

**Comment by matomoto** [comment]
Thank you for your reply Findus23. I have been using Piwik/Matomo for many years. In addition, I also monitor the matomo forum.m You are also in the matomo forum (under another nickname). In addition, I had(!) also once Analytics running and this observed. As well as much more.

The matomo users are either pure users who have no idea about the matter, or users who use very specific applications and are looking for a solution with matomo for that. Many let their matomo tracking (and their whole website) also managed by other people. Most of them will not know about the problem with cloud viewers and headless browser viewers. Rather, they are happy when matomo shows more viewers than analytics. The more, the better. So they will not do anything to reduce the viewers. But, these cloud viewers and headless browser viewers are like bots. They can be filtered. They litter the database. Keep your matomo database clean! So it would be even advisable to include these two functions as well as the bot/spider/crawler filter in the matomo core by default.

For me a plugin is out of question as long as I can solve it differently. The cloud IP ranges can be added to the default IP filter in the settings. The headless browsers I can filter myself with a PHP function on my websites. So for both I do not need such a plugin. For me remains only the request to integrate it into the matomo core. It then benefits especially those who do not know anything about the problem.
