### ISSUE TITLE
Cloud IP ranges filter

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#19920]
I have problems with many visits from cloud hoster. I don't need track visitis from cloud hoster. It's like bots. The cloud hoster provide their IP ranges via JSON / CSV. There is a Plugin, but this calls this JSON / CSV directly. I don't need calls to this servers via my matomo installation.

I have grab this IP ranges from 5 cloud hoster. There are a total of ~40,000 IP ranges. And yes, i will ignore all visitors from this IP ranges. In matomo default, i have the possibility to put it all in the settings area in the IP filter textarea. But ~40,000 lines are very much. OK, it works, but not fine.

Better was a new idea to ignore IP ranges from clouds. I always don't need Plugins. My piwik/matomo installation runs for many years with default and default settings. I track many of my websites. Default is good.

My suggestion would be that not a plugin is used for this, but that this is integrated into matomo default. As an offer to filter visits from clouds. For this, the IP range JSON / CSV should not be retrieved from matomo installation. Because they do not change that often. It would be enough if these lists are renewed at every update of matomo, but not by the matomo installation, but by the matomo programmers. Grab it and save it in a file. Update it by every matomo update. Similary to the bots/spider/crawler filter list.

The integration of this IP ranges list would be very simple. It only needs to be stored somewhere in the matomo installation and retrieved when the matomo user wants it. There should be a setting in the backend where the selection can be made whether to filter visitis from clouds or not.

Here are the 5 lists of cloud hosters that I know of:

amazon aws
https://ip-ranges.amazonaws.com/ip-ranges.json

microsoft azure
https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519

google digital ocean
https://www.digitalocean.com/geo/google.csv

google cloud
https://www.gstatic.com/ipranges/cloud.json

oracle cloud
https://docs.cloud.oracle.com/en-us/iaas/tools/public_ip_ranges.json

I had filtered this IP ranges for duplicates. That makes sense. Total are ~70,000 and filtered only ~40,000.

**Comment by sgiehl** [comment]
@matomoto Thanks for the suggestion. Filtering cloud IPs is part of our plugin https://plugins.matomo.org/TrackingSpamPrevention
We most likely won't include such features in core, as not all people might need it. If you have suggestions on improving the plugin. Feel free to create an issue here: https://github.com/matomo-org/plugin-TrackingSpamPrevention

**Comment by matomoto** [comment]
I have say no Plugin. **P**lugin is always **P**roblem. Your linked plugin calls 5 external server - the cloud server.
