### ISSUE TITLE
Goal overview page, when there is no goal setup, it seems like there unfinished load.

### ISSUE THREAD

**Issue by peterhashair** [piwik/piwik#19962]
## Expected Behavior

Should hide loading bar

## Current Behavior

see screenshots 
![image](https://user-images.githubusercontent.com/3783072/200221080-b7529a2e-c151-4941-8a3e-464bcdb06268.png)

## Steps to Reproduce (for Bugs)

1. Go to Goal overview, and make sure there are no goals setup.

## Your Environment

* Matomo Version:
* PHP Version: 8.0
* Server Operating System: 
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
@peterhashair that works for me without problems on `4.x-dev`. If you are still able to reproduce, maybe check for possibly failing requests or javascript errors that give a hint where the problem is.

**Comment by peterhashair** [comment]
@sgiehl random failed, close issue now.
