### ISSUE TITLE
Fix incomplete tool tip for best converting entry page in goals conversion overview

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19960]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/273120/200209265-2db34fd6-94c4-49a1-ba3f-a96aa8c296a3.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/273120/200209369-ce1bab20-a138-4523-8f20-6133a47ee6da.png">

see above screenshots. The conversion rate is not shown.

This can be reproduced in our own analytics via Matomo 4.12.3

**Comment by peterhashair** [comment]
This can reproduce locally, ping @mattab do we want to move this to the current milestone since it may have an impact on the usability

**Comment by mattab** [comment]
Yes, this must be fixed soon - i had reported it as well (and other bugs..) in https://github.com/matomo-org/matomo/issues/19512

**Comment by sgiehl** [comment]
@peterhashair are you already working on that one? I know where the problem is. I can set up a fix for that quite quickly...

**Comment by peterhashair** [comment]
@sgiehl nope feel free to grab it.

**Comment by peterhashair** [comment]
duplicate issue with https://github.com/matomo-org/matomo/issues/19512

**Comment by justinvelluppillai** [comment]
@peterhashair the reference to the other issue is incorrect - can you please update the link so we can see the duplicate?

**Comment by peterhashair** [comment]
@justinvelluppillai updated.
