### ISSUE TITLE
Fix flat lines in Sparklines when comparing segments

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19968]
see for example https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=week&date=2022-11-04&compareSegments%5B%5D=visitConvertedGoalId%3D%3D7&category=Goals_Goals&subcategory=General_Overview

and https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=week&date=2022-11-04&compareSegments%5B%5D=visitConvertedGoalId%3D%3D7&category=General_Visitors&subcategory=General_Overview

All sparklines don't show any data / only a flat line
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/273120/200442604-3d88c9bf-587d-4b9d-beb1-d5dbf5f6c2ae.png">

I would assume this used to work.

**Comment by peterhashair** [comment]
I believe this could be a similar issue with https://github.com/matomo-org/matomo/issues/19933
https://github.com/matomo-org/matomo/issues/19967

Hey, @mattab Do we want to move this to the current milestone since is a regression and has an impact on usability?

**Comment by sgiehl** [comment]
Had a quick look into that. Seems like the date used for the sparklines is provided as range instead of a single day. That causes the sparkline to use the provided range, instead if looking back for last30. Will provide a PR to fix that.
