### ISSUE TITLE
Missing translation keys for the anomyization backend part

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#19985]
Hi guys,
When it comes to anonymize past data within the privacy part of the Matomo backend, there is no possibility to translate the keys within weblate.

**Comment by sgiehl** [comment]
@Chardonneaur Do you mean the list of previous anonymizations? That one indeed seems to be hard coded.
Might be something we will fix with Matomo 5, as that part was meanwhile moved to vue here:
https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/PrivacyManager/vue/src/AnonymizeLogData/PreviousAnonymizations.vue

**Comment by Chardonneaur** [comment]
@sgiehl whaoo, does it mean that all plugins will need to be refactored for Matomo v5?

**Comment by sgiehl** [comment]
If a plugin uses angular js, then yes. It needs to be rewritten. But that can already happen, as the last releases of Matomo 4 already have Vue included
