### ISSUE TITLE
Site search in measurable settings has a blurry icon

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19981]
That's on a high resolution screen. See screenshot. 

<img width="282" alt="image" src="https://user-images.githubusercontent.com/273120/200915856-6601ef94-2035-4c29-9739-fb0752027a9a.png">

**Comment by sgiehl** [comment]
It seems we are using an image in this place and also for the search field in the menu drop down. I'll prepare a PR to change that to the font icon for Matomo 5.
