### ISSUE TITLE
Archive Cronjob Reports: WARNING Undefined array key "group"

### ISSUE THREAD

**Issue by mritzmann** [piwik/piwik#20006]
## Expected Behavior

* `./console core:archive` should run without WARNINGs
* `./console core:archive` should end with exit status `0`

## Current Behavior

* `./console core:archive` shows an WARNING in the logs
* `./console core:archive` is not terminated with exit status `0`

```
WARNING [2022-11-14 00:03:09] 641697 /home/matomo/www/core/Site.php(488): Warning - Undefined array key "group" - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
```

## Possible Solution

n/a

## Steps to Reproduce (for Bugs)

Cronjob was run with:

```shell
./console core:archive &>> "$LOG_FILE"
```

## Context

Similar issues have been reported in the past. Possibly relevant: https://github.com/matomo-org/matomo/issues?q=is%3Aissue+Undefined+array+key+is%3Aclosed+author%3Amattmary

## Your Environment

* Matomo Version: 4.12.3
* PHP Version: 8.0.25
* Server Operating System: Debian 10 (buster)
* Additionally installed plugins: According UI no "Third-party" plugin is installed

**Comment by sgiehl** [comment]
Hi @mritzmann 
Could you please check if your database table `matomo_site` has a column with the name `group`?

**Comment by mritzmann** [comment]
Hi @sgiehl, yes there is a column with the name `GROUP`.

```
MariaDB [matomo]> SHOW COLUMNS FROM piwik_site LIKE 'GROUP';
+-------+--------------+------+-----+---------+-------+
| Field | Type         | Null | Key | Default | Extra |
+-------+--------------+------+-----+---------+-------+
| GROUP | varchar(250) | NO   |     | NULL    |       |
+-------+--------------+------+-----+---------+-------+
1 row in set (0.001 sec)
```

**Comment by sgiehl** [comment]
@mritzmann Is the column name defined in uppercase? Or is that just the case in your output? It should have a lower case name though.

**Comment by mritzmann** [comment]
You are right, I have `GROUP` in upper case, although it [should be](https://github.com/matomo-org/matomo/blob/12ecd2662aee64327a6ea12462b662e3d07bb991/core/Db/Schema/Mysql.php#L114) `group`. It is not clear to me why this is not correct with this Matomo installation. I can only say that the installation has been around for a while, back when it was called Piwik.

Can you tell me if I can just rename this? If this goes beyond GitHub tickets, I can create a forum post.

**Comment by sgiehl** [comment]
Renaming it should solve your problem. Not sure how it ended up being upper case for you 🤷

**Comment by mritzmann** [comment]
Thanks for your help! I have renamed the column.

```mysql
ALTER TABLE piwik_site RENAME COLUMN `GROUP` TO `group`;
```
