### ISSUE TITLE
Deprecate Do-Not-Track Support

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#20011]
## Summary

Matomo currently supports the Do-Not-Track-Header that was introduced by some browser years ago. The option to exclude visitors sending this header is even enabled by default.

In 2019 W3C closed the group that was working on the DNT standard and though this is meanwhile deprecated.

Safari [removed the support for DNT](https://developer.apple.com/documentation/safari-release-notes/safari-12_1-release-notes#Security-and-Privacy) for privacy reasons shorty after that in version 12.1.

In matter of GDPR the DNT header does also not need to be respected.

We should there no longer enabled the DNT option by default in Matomo and add a useful information explaining why this feature now is deprecated and might be removed in an upcoming major release if more browsers drop the support.

**Comment by tsteur** [comment]
Do we already have an issue to remove the DNT feature in Matomo 6?

**Comment by Findus23** [comment]
@tsteur That's https://github.com/matomo-org/matomo/issues/20012, right?

**Comment by tsteur** [comment]
Awesome, sorry didn't notice it when I searched. I searched for everything but DNT :)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/discrepancy-between-backend-database-and-matomo-tracking/52038/17

**Comment by mpdude** [comment]
> In matter of GDPR the DNT header does also not need to be respected.

@sgiehl Could you please explain how you come to this conclusion? My data protection officer takes a different stance on this.

**Comment by sgiehl** [comment]
Actually I can't remember and I can't give any legal advice. But from a logically point of view it doesn't make sense to respect a technology that is abandoned.
Safari does not even support it anymore, and some browsers are always sending the DNT header without even giving the user the choice to disable it.

Anyway, at least in Germany there seem to be judgments that say something in terms of DNT: 
https://cybernews.com/tech/germany-court-bans-linkedin-from-ignoring-browser-do-not-track/

From my understanding I think this might depend on the data you are tracking and how you do it. If you are not tracking personal data at all you should be allowed to track anyone without consent (even when ignoring DNT). If you are tracking personal data you may need consent anyway, and if the user gives consent, DNT imho doesn't need to be respected anymore.
But I'm really not deep enough in GDPR to say something reliable.

Maybe @tsteur has more insights on that.

**Comment by tsteur** [comment]
I don't really have any insights on it but the recent court ruling suggests we still need to support this feature. I believe the majority of browsers also still has this feature. For example the most recent Chrome version still has this feature.
