### ISSUE TITLE
User opt-out checkbox toggles status (checked/unchecked) between browser refreshes (F5 or Ctrl+F5)

### ISSUE THREAD

**Issue by edisfera** [piwik/piwik#20023]
When implementing the "User opt-out" script in a page, it puts up a from with a checkbox showing the following label "Your are not opted out. Uncheck this box to opt-out" (ref. https://matomo.org/faq/general/faq_20000/). The checkbox is initially checked or unchecked according to the user's choice of being completely excluded from aggregated analitycs or not. Regardless the actual status of the checkbox (checked/unchecked), its status is not mainteined correctly between browser refreshes (F5 or Ctrl+F5). In fact, the status toggles from checked to unchecked and viceversa upon each refresh.

The checkbox should stay in the correct status between refreshes (that is, if checked, it should stay always checked regardless of the number or refreshes or unchecked in the opposite case).
This behavior can be seen on this page https://www.flaviamenopausa.it/Cookie-policy (the checkbox is located after the cookies table in the paragraph titled "Come disabilitare i cookie mediante configurazione del browser").

The mentioned site where the bug can be seen is powerd by matomo cloud.

This bug has been seen on Microsoft Edge, Firefox and Chrome.

**Comment by Findus23** [comment]
Hi,

I think this bug is the same as https://github.com/matomo-org/matomo/issues/19879 and related to https://github.com/matomo-org/matomo/issues/19888 and should be fixed with the next Matomo release
