### ISSUE TITLE
No data page (set up tracking page). Tag Manager section has an extra card

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20026]
see 
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/273120/202551813-51f5963b-35b3-498d-b42e-5865f6add392.png">

The tag manager section has a card wrapped around which other sections don't have.

**Comment by bx80** [comment]
The tag manager setup tab is being rendered by a vue component which is adding the card class via a `ContentBlock`. This `ContentBlock` could probably be removed which would get rid of the card wrapping.

**Comment by mattab** [comment]
Closing this as i assue this will be fixed in https://github.com/matomo-org/matomo/issues/20026

**Comment by heurteph-ei** [comment]
Hi @mattab 
Is it a duplicate of itself? ;-)
