### ISSUE TITLE
Add new website modal buttons are squashed together

### ISSUE THREAD

**Issue by justinvelluppillai** [piwik/piwik#20020]
When I click Add new website in Matomo I get buttons that are squashed together.

## Expected Behavior
Excellent UI (buttons not squashed)

## Current Behavior
Squashed together buttons:

<img width="759" alt="Screenshot 2022-11-16 at 3 39 40 PM" src="https://user-images.githubusercontent.com/1127121/202070492-34a547d7-f3d0-45b3-9362-9f543fb478e4.png">

## Possible Solution
Get UX/UI input and improve the spacing

## Steps to Reproduce (for Bugs)

1. Open Matomo UI in 4.13.0-rc1
2. Click Add New Website
3. Next page the modal pops up and looks as in the screenshot provided above

## Your Environment

* Matomo Version: 4.13.0-rc1
* PHP Version: 8.1
* Server Operating System: MacOS
* Additionally installed plugins:

* Browser: Firefox
* Operating System: MacOS

**Comment by sgiehl** [comment]
This should not happen for most users, as they don't have such many different type of measurables to create. As this is really easy to fix, I'll create a simple PR for Matomo 5.
