### ISSUE TITLE
Multiple errors displayed on the reporting page

### ISSUE THREAD

**Issue by vccs** [piwik/piwik#20039]
When accessing the reports page on v4.12.3 I am seeing the following errors;

WARNING: /plugins/ScheduledReports/ScheduledReports.php(239): Notice - Undefined index: category - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: ScheduledReports, Action: index, In CLI mode: false)
×
WARNING: /plugins/ScheduledReports/ScheduledReports.php(240): Notice - Undefined index: category - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: ScheduledReports, Action: index, In CLI mode: false)
×
WARNING: /plugins/ScheduledReports/Controller.php(74): Notice - Undefined index: category - Matomo 4.12.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: ScheduledReports, Action: index, In CLI mode: false)

Unfortunately no obvious config changes in reporting remove the errors.

**Comment by sgiehl** [comment]
Looks like some of the reports provided do not have a category set in their metadata.
Are you using any additional plugins?

**Comment by heurteph-ei** [comment]
Isn't it a migration problem? (migration that has not been played)

**Comment by sgiehl** [comment]
We have fixed a couple of warnings and similar problems in the meantime. Guess those problems should be fixed with Matomo 5. If not feel free to create a new issue.
