### ISSUE TITLE
Email report: page url which are too long are truncated in pdf format

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20035]
When we export the page url report as a pdf, if the urls are too long, they get truncated so impossible to use by the recepient.

What would be great is to have them moving to the next line when they are too long.

**Comment by sgiehl** [comment]
@Chardonneaur Might this one be included in the report in #18950 ?

**Comment by bx80** [comment]
Closing as a duplicate of #18950

**Comment by tzi** [comment]
Should be fixed in #23919
