### ISSUE TITLE
For users coming in from Google ads, each operation is created as a new session

### ISSUE THREAD

**Issue by HankMoody0603** [piwik/piwik#20036]
![image](https://user-images.githubusercontent.com/118788215/203213326-938ab183-c6f7-4694-b72f-33003a85ab5a.png)

As shown in the figure

For every customer who comes in through google ads, every behavior will be stored in the form of a new session

**Comment by HankMoody0603** [comment]
For each customer who uses the mobile terminal to enter through Google ads, each behavior will be stored in the form of a new session

**Comment by sgiehl** [comment]
Hi @HankMoody0603 
This is the default behaviour for Matomo. Whenever a user comes in with a new campaign a new visit will be started. If you do not want to have this you can change the config flag `create_new_visit_when_campaign_changes` to `0`.
But this will result in loosing all following campaign details, as only the first one will be stored.

**Comment by HankMoody0603** [comment]
The interval between these two actions is only a few seconds

**Comment by sgiehl** [comment]
That doesn't make a difference. See my comment above for a setting to change that in general.
