### ISSUE TITLE
 file:// protocol exclude option JS in tracker doesn't consider custom URL

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20049]
The feature https://github.com/matomo-org/matomo/issues/17017 was added in https://github.com/matomo-org/matomo/pull/19835/files

In this change we're using `location.protocol`. However, we would need to use the tracker method `getCurrentUrl()` and check whether the protocol is `file` for `configCustomUrl || locationHrefAlias`. That's because a user can overwrite the URL via `setCustomUrl()`. If the set custom URL isn't of protocol `file`, then we could still track it. Not sure if there would be any other side effects otherwise like the referrer may be still `file://`.

**Comment by justinvelluppillai** [comment]
Small point but we also have `function getProtocolScheme(url)` that would be useful to use
