### ISSUE TITLE
Add changelog and documentation for new JS tracker method file protocol exclusion

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20050]
This was added in https://github.com/matomo-org/matomo/pull/19835 as part of https://github.com/matomo-org/matomo/issues/17017

Not sure if we already have an issue for this. Feel free to close it if we do.

* We need to add the new method to the Developer changelog.
* We need to add the new method to the JS tracking client docs in https://developer.matomo.org/api-reference/tracking-javascript (5.x is now available there)
* Maybe we should also add a quick FAQ on matomo.org around `Why is no data tracked on my local file ...`?
* This FAQ we could then also link to in "Step 10) Optional Privacy Preferences" in https://matomo.org/faq/general/configure-privacy-settings-in-matomo/

**Comment by bx80** [comment]
Status update:
:heavy_check_mark: Add method to developer change log - done
:heavy_check_mark: JS api reference - PR 699 created, pending review.
:heavy_check_mark: FAQ - Pending review: https://matomo.org/?post_type=faq&p=61468&preview=true 
:o: Link to FAQ - to be done once FAQ is published

**Comment by sgiehl** [comment]
I have added the new FAQ to the privacy settings page. Now everything should be done here.
