### ISSUE TITLE
open_basedir IIS - Slow

### ISSUE THREAD

**Issue by romain25** [piwik/piwik#20052]
Thank you for this amazing alternative to Google Analytics.
I have a little issue on our installation. It's impossible to enable open_basedir with Matomo and IIS

## Steps to Reproduce (for Bugs)
1. I enable this on my php.ini - open_basedir = "D:\Datas\Inetpub\wwwroot\myanalytics.com" - Impossible to access to Matomo instance, everything is too slow
2. I disable open_basedir, Matomo is fast and quick. Car you give me path access matomo need, temp, other ? 

## Your Environment
Windows Server 2019
IIS 10
PHP 8.1.13
Mysql 8.0.13

Thank you

**Comment by peterhashair** [comment]
@romain25 you can probably find the info for IIS from here. https://matomo.org/faq/matomo-on-windows/how-do-i-install-and-configure-iis-on-windows-for-matomo/,  olpen_basedir will reduce performance, because it disables the realpath cache
