### ISSUE TITLE
Broken links on `Tips and considerations for updating a high traffic Matomo server` page

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20058]
## Page URL
**Tips and considerations for updating a high traffic Matomo server**
https://matomo.org/faq/on-premise/how-to-upgrade-matomo-to-the-latest-release/

#### Paragraph
> Note: before you start the upgrade, we recommend you make a fresh [Backup](https://matomo.org/faq/on-premise/how-to-upgrade-matomo-to-the-latest-release/#) of your MySQL database and codebase.

#### Problem
The `Backup` link leads to the page itself.

#### Paragraph
> When you put Matomo in maintenance, no data will be tracked during the maintenance window. There is a way to backfill the tracking requests and not lose any data during the migration: see the step below [Recover maintenance window’s missing tracking data](https://matomo.org/faq/on-premise/how-to-upgrade-matomo-to-the-latest-release/#)

#### Problem
The `Recover maintenance window’s missing tracking data` link leads to the page itself.

#### Paragraph
> View instructions in [Deploy Matomo to your servers](https://matomo.org/faq/on-premise/#how-to-deploy-matomo-to-your-servers) and [Deploy an upgrade](https://matomo.org/?post_type=faq&p=51764).

#### Problem
The `Deploy an upgrade` link leads to an HTTP 404 page.

#### Paragraph
> See: [How to recover missing data during maintenance?](https://matomo.org/faq/on-premise/how-to-upgrade-matomo-to-the-latest-release/#)

#### Problem
The `How to recover missing data during maintenance?` link leads to the page itself.

#### Paragraph
> You may go through each item in [Checklist: Post-deploy checks](https://matomo.org/faq/on-premise/how-to-upgrade-matomo-to-the-latest-release/#) to ensure the system is correctly deployed and working.

#### Problem
The `Checklist: Post-deploy checks` link leads to the page itself.

**Comment by sgiehl** [comment]
@justinvelluppillai is that one something the websites team could maybe handle?

**Comment by justinvelluppillai** [comment]
Yes, just a few links to change here so anyone can do it. I have updated them and will close this issue now.
