### ISSUE TITLE
Matamo tracker code automatically opts people out

### ISSUE THREAD

**Issue by andysh-uk** [piwik/piwik#20069]
I've rebuilt a website recently and replaced my Matamo privacy opt-out iframe with the new functionality introduced in 4.12 (I'm using 4.12.3.)

Whilst testing, I noticed that when the opt-out code is the much shorter version using the "Use the Matamo tracker code to set the opt out" option, when a user visits the page, the cookie "mtm_consent_removed" is **automatically set** without any interaction, even though the form says "to opt-out click the box."

When you check/uncheck the box, this cookie is added/removed.

If I use the "self-contained" code, no cookie is automatically set, and check/unchecking the box adds or removes different cookies - "mtm_consent" or "mtm_consent_removed".

I feel this behaviour with the cookie should be consistent whichever option is used, and certainly should not automatically opt users out without them interacting with the checkbox.

**Comment by sgiehl** [comment]
I think this should already be fixed with #19915
A new release should be pushed soon, which should include the fixed.
If it's urgent you can also consider using the latest release candidate: 4.13.0-rc2

**Comment by andysh-uk** [comment]
Ah, perfect, thanks.

I'll look out for the new release, not urgent, I've used the standalone code for now.
