### ISSUE TITLE
Bug with Ecommerce Overview when comparing with Previous year. 

### ISSUE THREAD

**Issue by varunKothare** [piwik/piwik#20075]
For **The Compare** to Function for **Ecommerce Overview**
 
![image](https://user-images.githubusercontent.com/100554311/205513100-af38b43e-e0e7-491e-b5f8-ad3567b84893.png)

if you select Compared to: Previous Year  - as follows
the graph reflects correctly, but if you hover over 'Ecommerce Orders' the text shows it as compared with the previous 2 weeks not the previous year as selected

![image](https://user-images.githubusercontent.com/100554311/205513124-8f8094f0-a318-4916-82d5-60f5e6e95bd6.png)

This can also be recreated and observed within the demo.matomo.cloud

**Comment by peterhashair** [comment]
Hey, @varunKothare thank you for reporting this, we notice this issue, duplicated with https://github.com/matomo-org/matomo/issues/15349.
