### ISSUE TITLE
Fatal error in tour when detecting consent manager

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20077]
The recently added tour challenge "detect consent manager" is triggering a fatal error:

> Error: {"message":"explode(): Argument #2 ($string) must be of type string, array given","file":"\/core\/Http.php","line":759,"request_id":"aceb4","backtrace":" on \/core\/Http.php(759)\n#0 \/core\/Http.php(759): explode('\\r\\n', Array)\n#1 \/core\/SiteContentDetector.php(294): Piwik\\Http::sendHttpRequestBy('curl', 'https:\/\/www....', 5, 'Mozilla\/5.0 (Wi...', NULL, NULL, 0, false, true)\n#2 \/core\/SiteContentDetector.php(130): Piwik\\SiteContentDetector->requestSiteData(1, 5)\n#3 \/plugins\/Tour\/API.php(84): Piwik\\SiteContentDetector->detectContent(Array)\n#4 [internal function]: Piwik\\Plugins\\Tour\\API->detectConsentManager('1', 60)\n#5 \/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#6 \/var

URL: /index.php?date=yesterday&module=API&format=json&method=Tour.detectConsentManager&idSite=1&filter_limit=-1&segment=&period=day

**Comment by bx80** [comment]
@tsteur From the backtrace it looks like the issue is in `core/Http::sendHttpRequestBy()` which is failing to parse the header returned by the configured site. This could be difficult to recreate without knowing the site response. Would it be possible to share the site URL in some way?

**Comment by justinvelluppillai** [comment]
Looks like it could actually be fixed already without knowing that by changing the default value of `$headers` to an empty array instead of empty string https://github.com/matomo-org/matomo/blob/4.x-dev/core/Http.php#L745

**Comment by bx80** [comment]
Thanks @justinvelluppillai :+1: I'd spotted that but was hoping to be able to recreate the issue to confirm there were no other downstream problems in this scenario, seems like this might be a rare code path since the offending code was added back in 2013! Since this is a trivial fix I've created a quick PR.
