### ISSUE TITLE
Possible to see numbers in a Heatmap

### ISSUE THREAD

**Issue by niklasternstedt** [piwik/piwik#20079]
## Summary
Would be able in a Heatmap see how many users have interacted with each element in the heatmap. If you hover over one elemnt in the heatmap you get the raw numbers of how many have clicked on that element.

I think hotjar have this functionality and Matomo have the data so it would be possible to merge the raw numbers with a heatmap.

**Comment by sgiehl** [comment]
Hi there, Thank you for creating the issue. Unfortunately we are only handling bugs & features requests for core here.
To request support or features for a Premium Feature please contact shop at innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features

**Comment by heurteph-ei** [comment]
@niklasternstedt maybe your need can be covered by the **Page overlay feature**: https://matomo.org/faq/reports/using-the-page-overlay-feature/
@sgiehl, this feature (page overlay) seems to not work anymore on the demo site + Firefox 102.4.0esr + Windows NT 10.0; Win64; x64 : https://demo.matomo.cloud/index.php?module=Overlay&period=month&date=today&idSite=1#?l=https$3A$2F$2Fdivezone.net$2Fdiving$2Fdjibouti$3F__prod_demo$3D1$26__enterprise_demo_idsite$3D1
> `There was an error setting cookie '_pk_ses.1.e555'. Please check domain and path. [piwik.js:12:282](https://analytics.divezone.net/piwik.js)`
> ...
> **`POST`**`https://analytics.divezone.net/piwik.php?e_c=abtesting&e_a=AffiliateLinkEffectiveness&e_n=original&ca=1&idsite=1&rec=1&r=895184&h=10&m=15&s=31&url=https://divezone.net/diving/djibouti?__prod_demo=1&__enterprise_demo_idsite=1&urlref=https://demo.matomo.cloud/&_id=dd04cf581bca2ef3&_idn=1&send_image=0&_refts=1670318131&_ref=https://demo.matomo.cloud/&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1920x1080&dimension1=anonymous&dimension2=Myryam&dimension3=-1924 days&dimension4=Djibouti&dimension5=diving&cvar={"1":["page-author","Myryam"],"2":["post-age","-1924 days"]}&_cvar={"1":["type","diving"],"2":["location","Djibouti"],"5":["diving-rating","5"]}&pv_id=BNGrMi`**`[HTTP/2 400 Bad Request 167ms]`**
>**`POST`**`https://analytics.divezone.net/piwik.php?e_c=abtesting&e_a=IDivedThereLinkMove&e_n=original&ca=1&idsite=1&rec=1&r=902089&h=10&m=15&s=31&url=https://divezone.net/diving/djibouti?__prod_demo=1&__enterprise_demo_idsite=1&urlref=https://demo.matomo.cloud/&_id=3d91688dc9cb00d6&_idn=1&send_image=0&_refts=1670318131&_ref=https://demo.matomo.cloud/&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1920x1080&dimension1=anonymous&dimension2=Myryam&dimension3=-1924 days&dimension4=Djibouti&dimension5=diving&cvar={"1":["page-author","Myryam"],"2":["post-age","-1924 days"]}&_cvar={"1":["type","diving"],"2":["location","Djibouti"],"5":["diving-rating","5"]}&pv_id=BNGrMi`**`[HTTP/2 400 Bad Request 178ms]`**

**Comment by sgiehl** [comment]
@heurteph-ei That's a known problem on the demo. The demo actually shows data dynamically generated from some fake logs, so no real visitor data would be shown publicly. The site it's referencing to does not contain the tracking code at all, causing the failure for the overlay. We already have an internal issue for that and it might get fixed at some point.
