### ISSUE TITLE
Update our github actions to not use set-output

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#20095]
Most of our actions are currently using `set-output`. As this one is deprecated, we need to update the actions.

```
Warning: The `set-output` command is deprecated 
and will be disabled soon. Please upgrade to using 
Environment Files. 
```
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

`set-output` will fail after June 1st 2023

We should already change that on 4.x-dev branch, to avoid the action to fail on that branch as long as it may still be LTS.

**Comment by peterhashair** [comment]
we maybe also need up checkout@v2 to v3, seems like Github Action only accept node 11 +
Consider maybe reopen this PR https://github.com/matomo-org/matomo/pull/19874/files
