### ISSUE TITLE
Visits over time" widget empty

### ISSUE THREAD

**Issue by dfranco** [piwik/piwik#20093]
## Expected Behavior
Visits over time widget in main Dashboard should contain web statistics (as Visits log)

## Current Behavior
Visits over time is empty since last upgrade

## Possible Solution
From system / check, there is a warning saying that one of our tracker has the issue below

> Request was not authenticated but authentication was required.

But I cannot find where/how to disable authentication requirement for this Matomo site. 

## Steps to Reproduce (for Bugs)
1. Log in on Matomo
2. Display the Dashboard for one of our site

## Context
We're only expecting to use the visits over time feature, nothing more

## Your Environment
* Matomo Version: 4.11.0
* PHP Version: 8.0
* Server Operating System: Debian 11
* Additionally installed plugins: none
* Browser: Brave 1.46.140
* Operating System: Mac OS Monterey 12.6.1

**Comment by dfranco** [comment]
Hello there,

Here's another hint that could help fixing this issue

In Tracking failures, the proposed solution is set or correct a "token_auth" (see screenshot)

![image](https://user-images.githubusercontent.com/482177/207008708-274de9ff-ce66-430b-a75b-47b8eeb3669a.png)

By the way, clicking on the **Learn more** link does not help as it doesn't open a new tab nor new windows in the web browser.

**Comment by sgiehl** [comment]
@dfranco A tracking request only requires authentication if it tries to track a visit/action for an older date or if it tries to overwrite the IP to be tracked using the `cip` parameter. This is usually only the case when doing log importing.

Is only the visits over time widget empty or do all other reports also not contain any data?

**Comment by dfranco** [comment]
Thanks for your feedback @sgiehl 

> @dfranco A tracking request only requires authentication if it tries to track a visit/action for an older date or if it tries to overwrite the IP to be tracked using the `cip` parameter. This is usually only the case when doing log importing.
> 
Good to know, thanks for the explanation.
Shall I delete the tracking failure then ?

> Is only the visits over time widget empty or do all other reports also not contain any data?

Actually, also Scan result, Conversions Overview and Visits Overview widgets are empty if I choose a specific period (from upgrade time to today).

What's weird is that the **Visits in Real-time** widget does shows statistics.

If I can provide further informations, please let me know.

**Comment by sgiehl** [comment]
> Shall I delete the tracking failure then ?

Feel free to do that. If that doesn't occur frequently, I guess that's nothing to worry about.

> Actually, also Scan result, Conversions Overview and Visits Overview widgets are empty if I choose a specific period (from upgrade time to today).
> What's weird is that the Visits in Real-time widget does shows statistics.

Sounds like the archiving might not run correctly. Can you see any errors in the log file?

**Comment by dfranco** [comment]
Hello @sgiehl ,

> > Shall I delete the tracking failure then ?
> 
> Feel free to do that. If that doesn't occur frequently, I guess that's nothing to worry about.
> 
> > Actually, also Scan result, Conversions Overview and Visits Overview widgets are empty if I choose a specific period (from upgrade time to today).
> > What's weird is that the Visits in Real-time widget does shows statistics.
> 
> Sounds like the archiving might not run correctly. Can you see any errors in the log file?

Indeed, the reports archiving was not running as expected.

Running the command manually fixed the widgets mentioned above.

I'm closing this one as it was more an issue on my side.

Thanks again for your quick support.
