### ISSUE TITLE
Various UI tests fail with TypeError: Cannot read property 'join' of undefined in page-renderer.js

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20103]
Noticed this eg in https://app.travis-ci.com/github/matomo-org/matomo/jobs/591094114

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/273120/207438505-4dfeadac-54e6-42f2-b9aa-1c4cca2d47ff.png">

Seems it doesn't impact the tests but it's confusing as it's not clear if the test failed or succeeded etc.

**Comment by peterhashair** [comment]
@tsteur quickly did a PR. Seems fixed it.
