### ISSUE TITLE
Add privacy & security features to only allow adding users with emails from specific domains

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20101]
By only allowing inviting users of specific email domains, eg your company domain, you can "prevent" to some extend that third party people may be added.

* This way it can prevent that for example admins give access to third party agencies without a super user's knowledge. Preventing data sharing.
* This way it can prevent some cases where a security issue could allow someone changing the email or inviting an email or adding a user with a third party email.

There should be a security setting where optionally a sysadmin can restrict the domains to one or multiple domains.

If any are defined, and then a user tries to invite|add|change a user email from a different domain, then an error would be shown that this is not allowed and to contact a super user.

To be defined:
* When adding or removing domains in the system setting but users with other domains exist. I suggest for simplicity we would show an error that this setting cannot be changed until all users match that criteria. Meaning a super user would need to first remove certain users and then change the setting again or allow additional domains.

**Comment by heurteph-ei** [comment]
This configuration could be even better if also being defined by site.
Eg. site A (with siteID=1) could restrict on A.com domain only.

**Comment by tsteur** [comment]
@mattab before the holidays I did an implementation of this to check this in https://github.com/matomo-org/matomo/compare/m20101?expand=1 but did not finalise the wording and testing. Figured that because only super user can add users there's not too much of a security benefit because an attacker who is able to add a user would also have the permissions to change the login domains. 

So mostly it would only help with:
* From a security & privacy perspective prevent users from changing their email to a private email address
* From  a privacy perspective prevent from adding third parties too easily, but the same user can workaround it easily.

Not sure if it's all that useful in the end @mattab ? 

Or does anyone see any other benefits of this?

**Comment by mattab** [comment]
@tsteur on https://matomo.org/faq/general/manage-users/ it says "As an Admin user, you can invite new users by clicking the Invite a New User button:" so also Admin users can invite users, and therefore this feature is indeed useful because Admins wouldn't be able to update the Authorised domains :+1:
