### ISSUE TITLE
Fatal error: Allowed memory size exhausted core/DataTable/Row.php on line 361

### ISSUE THREAD

**Issue by Daijobou** [piwik/piwik#20109]
## Expected Behavior
Show box for "Visits Overview"

## Current Behavior
"Visitors > overview" shows instead box "Visits Overview" this:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vhosts/example.com/core/DataTable/Row.php on line 361

## Possible Solution
Increase memory limit? ;)

## Steps to Reproduce (for Bugs)
https://example.com/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last30#?period=range&date=2022-01-01,2022-12-14&idSite=1&category=General_Visitors&subcategory=General_Overview
I want see data for this year. Last year working fine.

## Your Environment
* Matomo Version:  4.13
* PHP Version: 8.1.13
* Server Operating System: AlmaLinux  8.7

**Comment by sgiehl** [comment]
This is most likely a memory issue, as the chart when using a range will try to load the data for each day in the range.
I'll close this one as an improvement is already in progress with #20100.
Meanwhile there is nothing else you can do except of increasing the memory limit.

**Comment by Daijobou** [comment]
@sgiehl The "Overview" is not the "Chart". The chart is displayed correctly. It is the box below, the "overview". With the numerical values for visitors. 

here for 01.01. - **15**.12.**2022**
![image](https://user-images.githubusercontent.com/260343/207819047-5732992b-3817-4a88-a674-bc1b9f409a35.png)

here for 01.01. - **31**.12.**2021** (here are more days and working fine)
![image](https://user-images.githubusercontent.com/260343/207819445-4448e1ce-e008-4fe7-9a02-a40d8f84e8d9.png)

**Comment by sgiehl** [comment]
@Daijobou We are currently implementing some improvements around loading archives for date ranges.
But the difference for the data above is easy to explain:
The second one displays a full year, so the numbers displayed in the report can simply use the prepared year archive. If you request a range, that does not contain the full year, Matomo tries to sum up best matching archives. E.g. some month archives for jan. to nov. together with some day archives for dec. This might consume a lot more time and memory.
