### ISSUE TITLE
Conversion not registered

### ISSUE THREAD

**Issue by 7starsone** [piwik/piwik#20106]
Hello,
URL pattern contains something like
`/one/two/three`

users regularly visit that page but 0 conversions.
Please, why? On your documentation there's no specific example except for "contact" keyword.
Is the slash / an issue on the pattern or the problem somewhere else?
Thanks

**Comment by 7starsone** [comment]
eg. on access log
`IP ADDRESS - - [13/Dec/2022:10:46:09 +0100] "GET /myfolder/ii/mod/why/submit?key=5663b8d0fb91d0423aed4282fc49e2a4&id_mod=25&id_ca=64112&id_or=14413 HTTP/2.0" 200 10330 "https://domain.com/myfolder/ii/mod/why/confirm?get_confirmation=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0"`

**Comment by 7starsone** [comment]
In that example the pattern contains `/mod/why/submit`
so that's the goal but your software doesn't register the conversion at the moment.

**Comment by 7starsone** [comment]
Hello, is it possible that this issue is caused by the script on the footer instead of the head ? I will test in these days to understand if it works well keeping the script inline. Thanks

**Comment by heurteph-ei** [comment]
Hi,
For questions about configuration, please ask first on forums: https://forum.matomo.org/
Please precise:
 - Matomo version
 - Tracking method (JavaScript API, MTM, logs analysis, etc.) and maybe some used tracking code
 - The browser version
 - If there are some errors in the browser console
 - If there are some HTTP requests to the Matomo server in the browser console
 - If you see some hits on the visits log (or in the real-time report)
 - The conversion configuration

**Comment by 7starsone** [comment]
> Hi, For questions about configuration, please ask first on forums: https://forum.matomo.org/ Please precise:
> 
>     * Matomo version
> 
>     * Tracking method (JavaScript API, MTM, logs analysis, etc.) and maybe some used tracking code
> 
>     * The browser version
> 
>     * If there are some errors in the browser console
> 
>     * If there are some HTTP requests to the Matomo server in the browser console
> 
>     * If you see some hits on the visits log (or in the real-time report)
> 
>     * The conversion configuration

Matomo 4.13.0
Javascript (now in the head section)
Firefox 108 64bit
@heurteph-ei 
Maybe found, there was an error from fbpixel 'cause `fbq` wasn't defined. The strange thing was that Matomo retrieved in realtime the goal on the visitor profile but then the summary and the specific goal widget were never updated. 
Is it expected, just because  of an error on console from other scripts?
Thanks

**Comment by heurteph-ei** [comment]
> Matomo retrieved in realtime the goal on the visitor profile but then the summary and the specific goal widget were never updated

This is probably due to archiving settings. Either wait for 1 day, or: https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

**Comment by 7starsone** [comment]
@heurteph-ei it's not about archiving, when I disabled the fbpixel then I saw the recent goal/conversion updated.

**Comment by heurteph-ei** [comment]
Maybe @sgiehl has an idea?

**Comment by sgiehl** [comment]
If a goal is configured to be triggered when a certain URL is visited, the goal will be triggered internally as soon as a tracking request contains this URL. So I guess the regex for the url match that is configured for the goal does not match for some reason.
You may want to check again how exactly the gal is configured and what exact url is sent in the tracking request.
Regarding fbpixel: Maybe that pixel manipulates the URL in some way, so it doesn't match anymore in the end

**Comment by 7starsone** [comment]
@heurteph-ei @sgiehl well, the URL comes from a PayPal purchase confirmation. It's returned on access log with HTTP 200 code but probably it's a S2S call where javascript is not executed. So, If I directly visit that page is a matter while if the request is S2S the user only sees a template but it's not like a real visit. So, maybe because of this they write an article like https://support.google.com/grants/answer/9628112?hl=en anyway, I would need to better understand how this S2S call works and I will try to put the code directly into that page.

**Comment by sgiehl** [comment]
Hi @7starsone . If the page is called without javascript, it won't be tracked in Matomo and thus no goal tracking can be triggered.
It might be possible to solve that using the PHP tracker and send the tracking requests in PHP directly, but it might be hard to associate that with the correct visit then.
Another possibility would be to redirect the user to a certain page after a checkout, so that one can be used for goal tracking maybe.
As there is nothing in Matomo what we could change to improve that atm, I'll close this issue for now. You can try getting some more help on our forum or maybe our support.
