### ISSUE TITLE
When creating a segment, Ecommerce Order value dimension should be numeric

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20120]
## Expected Behavior

When creating a segment, Ecommerce Order value dimension should be numeric, and offer comparisons like "Less than, Less than or equal," etc.

## Current Behavior

Order value shows the "string" operators instead:
![Screenshot from 2022-12-19 08-12-40](https://user-images.githubusercontent.com/466765/208315112-0090c199-9ff1-4bf9-974f-cf76433a34af.png)

## Steps to Reproduce (for Bugs)

1. add a new segment to an Ecommerce enabled website
2. add the Order value dimension
3. Try to say "Less than or equal" to 0 but it's not possible

## Context

* Trying to create a segment where Ecommerce order value is zero, currently the segment doesn't work (Order value is 0.00), and hoping it's just because of this bug.

**Comment by sgiehl** [comment]
Hm. I actually don't even have a segment "Order Value". The dimension does have different segments configured. See
https://github.com/matomo-org/matomo/blob/e1eea7a08911da4d8718ad9316a19bd326cf02d7/plugins/Ecommerce/Columns/Revenue.php#L29-L61

**Comment by bx80** [comment]
@mattab Thanks for the screenshot and reproductions steps :+1: I've tried to recreate this issue, but I only have `Order Revenue` in the ecommerce segment dimensions, which is numeric as expected - is it possible that `Order Value` is a custom dimension or has been added by some other means? Do you also have an `Order Revenue` dimension in the list for this site?

![image](https://user-images.githubusercontent.com/88810029/210461874-78ce5fed-d040-484b-b7e8-54893a662e66.png)

**Comment by mattab** [comment]
Thanks for the feedback, it was indeed a custom dimension called "order value" and when using the correct "order revenue"  dimension, then it works as expected :+1:

**Comment by heurteph-ei** [comment]
Hello @mattab and happy new year!
Maybe this could good idea to take the opportunity (with your initial issue) to define the format of custom dimension (string, boolean, numeric, date, etc.). Then the segment definition could take this info in consideration and they could be build properly?

**Comment by mattab** [comment]
Absolutely @heurteph-ei and i believe this is already the case, for example for "strings" we have operators like "Contains" whereas for "numbers" we don't but then we have "less than" etc.
