### ISSUE TITLE
Zeroes ("0") in custom dimension values appear as hyphens ("-")

### ISSUE THREAD

**Issue by rberggreen** [piwik/piwik#20129]
## Expected Behavior
Custom dimension values should appear in the dashboard exactly as they were sent.

## Current Behavior
When "0" is used as the value for a custom dimension, it appears as "-" in the dashboard.

![Skärmavbild 2022-12-20 kl  15 10 26](https://user-images.githubusercontent.com/10262269/208717528-a5d37d2e-b6ea-40ca-a2de-9ddd48dc4cd2.png)

## Possible solution
Workaround: Represent boolean values in another way, e.g. "false"/"true". 

## Steps to Reproduce
1. Post an analytics event containing a custom dimension such as `dimension1=0`
2. Go to the Matomo dashboard > Visitors > [the custom dimension in question]

The bug does not happen when viewing the equivalent data in the Visitor profile view. 

## Context
We are using the custom dimensions feature to collect data about the user's environment such as whether a screen reader is active or whether an external keyboard is connected. Custom dimension values can only be strings and we have chosen to convert all of our bool values to "0"/"1". 

The bug makes the presented data harder to understand. It can also raise concerns about the data being correct in the first place, which it appears to be. 

## Your Environment
* Matomo Version: 4.12.3
* PHP Version: 7.4
* Browser: Google Chrome 108.0.5359.124
* Operating System: macOS Monterey 12.5.1

**Comment by sgiehl** [comment]
Hi @rberggreen 
Thanks for creating this report. The value `0` should indeed be shown in the label column. The hyphen should only be shown in other columns. I'll have a quick look if we can easily fix that.
