### ISSUE TITLE
Testcookie causes warning in browser console

### ISSUE THREAD

**Issue by ValenDigital** [piwik/piwik#20144]
Related to:  #17829

as reported in: reported in https://forum.matomo.org/t/javascript-error-trying-to-set-test-cookie-pk-testcookie-domain/42655
and in the closed issue: https://github.com/matomo-org/matomo/issues/17829

This is still an issue even after updating to the latest 4.13.0 self hosted version. Multiple sites that show this exact same issue on inconito and private browsers. Running the latest 4.13.0 self hosted version. How can we get this fixed?

**Comment by justinvelluppillai** [comment]
Thanks for the info @ValenDigital. Are you using setCookieDomain on your sites? This warning is intended to show that the cookie domain has not been set correctly, and therefore cookies cannot be written. If the setCookieDomain domain is wrong then it should be fixed and this console error won't show.

**Comment by ValenDigital** [comment]
@justinvelluppillai yes thats right. Got it. Thanks for the push in the right direction. Please close this then. We can solve from our end if thats the case :)
