### ISSUE TITLE
integrate https://db-ip.com/xxx.xxx.xxx.xxx IP info lookup when clicking on IP of a visit

### ISSUE THREAD

**Issue by fsennj** [piwik/piwik#20152]
Hello All, not an issue more more an enhancement. Would it be able to integrate a link to the above mentioned URL with the IP of a visit so to be able to lookup more info about the visitors IP.

thank you

**Comment by heurteph-ei** [comment]
Hi @fsennj 
Isn't the GeoIP location (https://matomo.org/faq/how-to/setting-up-accurate-visitors-geolocation/) or the [IP 2 Location plugin](https://plugins.matomo.org/IP2Location) sufficient for your needs?

**Comment by fsennj** [comment]
Hello,

no with the db-ip.com you can acutally see names to whom the IP belongs too.

for example our own business id
https://db-ip.com/80.93.44.30
80.93.44.30 - Austria - Stadtwerke Kufstein GmbH - IP address geolocation<https://db-ip.com/80.93.44.30>
80.93.44.30 is an IPv4 address owned by Stadtwerke Kufstein GmbH and located in Vienna, Austria (see map)
db-ip.com


[cid:16392ad2-611a-4d16-a392-8477e4ddc965]
________________________________
Von: heurteph-ei ***@***.***>
Gesendet: Mittwoch, 4. Januar 2023 10:56
An: matomo-org/matomo ***@***.***>
Cc: Franz Senn jun. ***@***.***>; Mention ***@***.***>
Betreff: Re: [matomo-org/matomo] integrate https://db-ip.com/xxx.xxx.xxx.xxx IP info lookup when clicking on IP of a visit (Issue #20152)


ACHTUNG diese Email stammt von einem Externen Absender. Bitte mit Vorsicht öffnen. Im Zweifel Administrator kontaktieren.


Hi @fsennj<https://github.com/fsennj>
Isn't the GeoIP location (https://matomo.org/faq/how-to/setting-up-accurate-visitors-geolocation/) or the IP 2 Location plugin<https://portalnospam.senn-beteiligung.at/link?id=BAgAAAA6zIvzk7yOunoAAACfKfPES0VxBskX_MlwVQ3ibTGOUP1tzFrCqwyh2AL1Tw5564I2dn-pvA0DUce1mXDwjoFuYOl_yK4WiuhvbfDxza8yEVsZyp1vuoVgBjF7YI7Q3psNjBVxV3HgO2NASlaUsBZygkUgidHtIHeQGdf66y9CwfqzqQD8KQ2> sufficient for your needs?

**Comment by Findus23** [comment]
Detecting the ASN should also already be supported by Matomo: https://github.com/matomo-org/matomo/issues/16499

**Comment by fsennj** [comment]
Yes but that case has never been completed. is there any plans to do so?
________________________________
Von: Lukas Winkler ***@***.***>
Gesendet: Mittwoch, 4. Januar 2023 11:28
An: matomo-org/matomo ***@***.***>
Cc: Franz Senn jun. ***@***.***>; Mention ***@***.***>
Betreff: Re: [matomo-org/matomo] integrate https://db-ip.com/xxx.xxx.xxx.xxx IP info lookup when clicking on IP of a visit (Issue #20152)


ACHTUNG diese Email stammt von einem Externen Absender. Bitte mit Vorsicht öffnen. Im Zweifel Administrator kontaktieren.


Detecting the ASN should also already be supported by Matomo: #16499<https://github.com/matomo-org/matomo/issues/16499>

**Comment by heurteph-ei** [comment]
@fsennj 
The ticket mentioned by Lukas (Findus) has been solved on Oct 1, 2020. Then why do you write:
>that case has never been completed

❓
