### ISSUE TITLE
Mention new consent guides in Matomo "Asking for consent" page

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20158]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/273120/210891377-b412fb7a-0c89-4faf-92f8-45c3d6768eb6.png">

See screenshot above. Our consent guides weren't mention on that page.

* Can we mention the new consent guides available there?  see https://matomo.org/subcategory/consent-managers-javascript-tracking/ for the available guides.
* Can we also update https://developer.matomo.org/guides/tracking-consent to cross link to the consent guides?

**Comment by Stan-vw** [comment]
Suggested new text for the asking for consent page:

**Asking for consent**
Consent means offering individuals choice and control about how their personal data is processed.

**When do I need to ask for user consent?**
The [GDPR privacy regulations](https://matomo.org/faq/new-to-piwik/what-is-gdpr/) require you to ask for your users' consent when processing personal data in some cases. To determine whether you need to ask for consent, you need to identify your lawful basis for processing personal data. This can be either "Consent" or "Legitimate interest", or you may be able to avoid collecting personal data altogether.

It's recommended to learn more about the lawful basis for processing personal data under GDPR. You can find more information on this topic on [our blog](https://matomo.org/blog/2018/04/lawful-basis-for-processing-personal-data-under-gdpr-with-matomo/).

Please note that if you require your users' consent, and you cannot prove that you obtained their "Consent" in the past, we recommend anonymizing your previously tracked users' raw data. Anonymizing your previously tracked users' raw data can be done through the Privacy Manager in Matomo [learn more](https://matomo.org/faq/how-to/faq_35661/).

**How do I ask users for consent?**
Matomo has guides available for setting up consent tracking with the following popular consent managers:
- [Osano Consent Manager](https://matomo.org/faq/how-to/using-osano-consent-manager-with-matomo/)
- [Cookiebot Consent Manager](https://matomo.org/faq/how-to/using-cookiebot-consent-manager-with-matomo/)
- [CookieYes Consent Manager](https://matomo.org/faq/how-to/using-cookieyes-consent-manager-with-matomo/)
- [Tarte au Citron Consent Manager](https://matomo.org/faq/how-to/using-tarte-au-citron-consent-manager-with-matomo/)
- [Klaro Consent Manager](https://matomo.org/faq/how-to/using-klaro-consent-manager-with-matomo/)
- [Complianz for WordPress Consent Manager](https://matomo.org/faq/how-to/using-complianz-for-wordpress-consent-manager-with-matomo/)

If you do not use one of the above consent managers, you can implement [tracking with consent using the Matomo JavaScript API](https://developer.matomo.org/guides/tracking-consent).

**Comment by sgiehl** [comment]
@Stan-vw The screen currently might also include some details and links to a certain consent manager if one is detected on the users site. This currently looks like this:
![PrivacyManager_ConsentManager_consent_default](https://user-images.githubusercontent.com/1579355/235962911-995aec2b-f4b6-4b8e-80c6-eae089f7576d.png)

Should that still be simply displayed below the new text or should we maybe hide some parts if a consent manager is detected, or move that up. To me it might look a bit strange to first suggest the user to have a look at various guides in oder to point him to the one that might be important for them afterwards...

**Comment by Stan-vw** [comment]
@sgiehl thanks for pointing this out, didn't know about this conditional section.
My suggestion is to bring the "we detected this specific consent manager on your site" card all the way to the top (since it's the most relevant). We can still adjust the other items as suggested above.
@Javi-Ormaechea fyi
