### ISSUE TITLE
Enable segmented visits log feature for product reports

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20153]
Matomo provides the following Ecommerce > Products reports:
*    Product Name
*    Product SKU
*    Product Category

In these reports, when hovering on a row, the Segmented Visits log icon is not displayed:
(only the row evolution icon displays):

![image](https://user-images.githubusercontent.com/466765/210470065-cced0e32-3fea-4107-9bef-219dae774284.png)

Instead, we expected that the Segmented Visits log icon displays.

The icon displays correctly in the "Sales" reports eg: 
![image](https://user-images.githubusercontent.com/466765/210470167-280fa9f0-cbb9-462c-a263-b8618e3ba10b.png)

Showing this icon in the "Products" reports will be very valuable to Ecommerce operators who can then easily view the visits where customers purchased the product that is being clicked.

**Comment by sgiehl** [comment]
Had a quick look, why that isn't already possible. Turned out it's easy to add by adding a couple of lines only.
Will create a PR so we can include that in Matomo 5.
