### ISSUE TITLE
Cron tab issue

### ISSUE THREAD

**Issue by altavia-belgium** [piwik/piwik#20156]
Hi Team,

The message set up cron persist while our dev team has created crob tabs for archiving purposes (see screen shot) [](url)
for https://matomo-slci.jetpulp.work/index.php

## Expected Behavior
disappearing of crob tab info message

## Current Behavior
appearing of cron tab info message

## Possible Solution
?
## Steps to Reproduce (for Bugs)
go diagnostic systemcheck to see cron tab message

## Your Environment
system check 
<details>
<summary>Click to view System Check</summary>

#### PHP version >= 7.2.5:
 ✔ 8.1.12

#### PDO extension:
 ✔ 

#### PDO\MYSQL extension:
 ✔ 

#### MYSQLI extension:
 ✔ 

#### Other required extensions:
 ✔ zlib ✔ json ✔ filter ✔ hash ✔ session

#### Required functions:
 ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

#### Required PHP configuration (php.ini):
 ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR = -1 OR >= 30

#### Directories with write access:
 ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c

#### Directories with write access for Tag Manager:
 ✔ $DOC_ROOT/js

#### Required Private Directories:
 ✔ All private directories are inaccessible from the internet.

#### Recommended Private Directories:
 ✔ All private directories are inaccessible from the internet.

#### File integrity:
 ✔ 

#### 64-bit PHP Binary:
 ✔ 

#### Tracker status:
 ✔ 

#### Memory limit:
 ✔ 128M

#### Time zone:
 ✔ 

#### Open URL:
 ✔ curl

#### PageSpeed is turned off:
 ✔ 

#### GD > 2.x + FreeType (graphics):
 ✔ 

#### Other extensions:
 ✔ json ✔ libxml ✔ dom ✔ SimpleXML ✔ openssl

#### Other functions:
 ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

#### Filesystem:
 ✔ 

#### Set up Cron (faster report-loading):
 ⚠ Warning: For optimal performance and a speedy Matomo, it is highly recommended to set up a crontab to automatically archive your reports, and to disable browser triggering in the Matomo settings. Learn more.

#### Browser and Auto-archiving enabled:
 ⚠ Warning: It looks like both browser and auto archiving are enabled. Auto archiving last started 4 hours 59 min ago. If auto archiving is enabled, you should disable browser archiving in "General Settings".

#### Set up Cron - Managing processes via CLI:
 ✔ Ok

#### Database abilities:
 ✔ UTF8mb4 charset ✔ LOAD DATA INFILE ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level

#### Max Packet Size:
 ✔ 

#### Forced SSL Connection:
 ✔ 

#### Geolocation:
 ✔ geoip2php (continent_code, continent_name, country_code, country_name, region_code, region_name, city_name, postal_code, lat, long)

#### Update over HTTPS:
 ✔ 

#### Writable JavaScript Tracker ("/matomo.js"):
 ✔ 

#### [GoogleAnalyticsImporter] Required PHP Functions:
 ✔ 

#### [GoogleAnalyticsImporter] Required Executables (php):
 ✔ 

#### [GoogleAnalyticsImporter] Required Executables (nohup):
 ✔ 

#### Matomo Version:
 4.13.0

#### Matomo Update History:
 4.13.0,4.12.3,

#### Matomo Install Version:
 4.12.3

#### Latest Available Version:
 4.13.0

#### Is Git Deployment:
 0

#### PHP_OS:
 Linux

#### PHP_BINARY:
 /usr/sbin/php-fpm8.1

#### PHP SAPI:
 fpm-fcgi

#### Timezone Version:
 0.system

#### PHP Timezone:
 UTC

#### PHP Time:
 1672921467

#### PHP Datetime:
 2023-01-05 12:24:27

#### PHP INI max_execution_time:
 30

#### PHP INI post_max_size:
 8M

#### PHP INI max_input_vars:
 1000

#### Curl Version:
 7.64.0, OpenSSL/1.1.1n

#### Suhosin Installed:
 0

#### DB Prefix:
 matomo_

#### DB Charset:
 utf8mb4

#### DB Adapter:
 PDO\MYSQL

#### MySQL Version:
 10.3.37-MariaDB-1:10.3.37+maria~deb10-log

#### Num Tables:
 284

#### Browser Segment Archiving Enabled:
 1

#### Development Mode Enabled:
 0

#### Internet Enabled:
 1

#### Multi Server Environment:
 0

#### Auto Update Enabled:
 1

#### Custom User Path:
 0

#### Custom Include Path:
 0

#### Release Channel:
 latest_stable

#### Plugins Activated:
 API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomAlerts 4.1.0, CustomDimensions, CustomJsTracker, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, Feedback, GeoIp2, Goals, GoogleAnalyticsImporter 4.4.5, Heartbeat, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, LanguagesManager, Live, Login, MarketingCampaignsReporting 4.1.3, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, ProfessionalServices, Proxy, Referrers, ReferrersManager 4.0.3, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, TagManager, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize

#### Plugins Deactivated:
 DBStats, MobileAppMeasurable

#### Server Info:
 nginx/1.22.1

#### Had visits in last 1 day:
 1

#### Had visits in last 3 days:
 1

#### Had visits in last 5 days:
 1

#### Archive Time Last Started:
 2023-01-05 07:24:33

#### Archive Time Last Finished:
 2023-01-05 07:24:34

#### User Agent:
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

#### Browser Language:
 en-gb,en-us,en,nl

#### Total Invalidation Count:
 1897

#### In Progress Invalidation Count:
 0

#### Scheduled Invalidation Count:
 1897

#### Earliest invalidation ts_invalidated:
 2022-11-30 14:45:53

#### Latest invalidation ts_invalidated:
 2023-01-05 08:48:41

#### Number of segment invalidations:
 116

#### Number of plugin invalidations:
 0

#### Do Not Track enabled:
 1

</details>

**Comment by bx80** [comment]
Hi @altavia-belgium, thanks for reaching out. 

From that diagnostic message it seems that the cron is running ('Auto archiving last started 4 hours 59 min ago') but that browser triggered archiving is still enabled, which is probably why the message is still being shown.

Can you check that the 'Archive reports when viewed from the browser' option is set to 'No' in Administration > System > General settings?

![image](https://user-images.githubusercontent.com/88810029/210895629-68d35d65-05b9-4a01-acad-73ddd355de15.png)

Alternatively this can also be disabled by adding `enable_browser_archiving_triggering = 0` to the `config.ini.php` file `[General]` section
