### ISSUE TITLE
Amount of rows in site search report not respecting the config limit

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#20166]
Hi,

The site search report shows a limited amount of rows, which is configured in the config with the setting: datatable_archiving_maximum_rows_site_search. But when I want to increase this value to 50000, the amount of rows still caps at 2.500
![image](https://user-images.githubusercontent.com/11771529/211152810-996a200f-4655-47a8-9ba1-9ca0c6b0c977.png)

I have noticed that the 2500 is my setting for the limit of actions. To test this I've increased this number to 5000, and indeed it now gives me 5.000 rows in the site search report.
![image](https://user-images.githubusercontent.com/11771529/211152917-a5de8f6b-3b73-4c93-9c96-09ed8ec1b627.png)

But not 50.000 like I specified:
datatable_archiving_maximum_rows_site_search = 50000
datatable_archiving_maximum_rows_actions = 2500

When I change the setting for action back to 2500, the report will also drop to 2500 rows. So it seems the maximum amount of rows for the site search report is not using the correct specified config value.

(I have invalidated the archived data before re-archiving to make sure of the config values)

Also, when I search for a specific keyword, the totals row is not updated to the subset. It will keep showing the full amount of results
![image](https://user-images.githubusercontent.com/11771529/211153161-8646bf05-ce3c-48bd-ad83-6d6c2c22fb4f.png)

**Comment by sgiehl** [comment]
Hi @conflate-nl 
Sorry for the long delay and thanks for your report!
I just had a look at the code, and it indeed seems to be the case, that for archiving reports for periods other than day the wrong limit is used for site search reports.
I'll prepare a fix for this one.

**Comment by ghost** [comment]
Great, thank you!
