### ISSUE TITLE
[Feature Request] More detailed transition report for "Others" entries

### ISSUE THREAD

**Issue by NicoHood** [piwik/piwik#20163]
Hi,
I originally wrote this to the email support, but they told me to flag a github issue. So here is my question:

Is it possible to get a more detailed transition report? Some of the  pages are summarized as "Other". And I really need more details about  those summarized pages. How can I get them?

Look at my attached screenshot. You can see there are 41% "Others" outgoing links. Is there any way to get those "Others" no summarized? I want to also have the information about the less often clicks.

![grafik](https://user-images.githubusercontent.com/6888294/210968702-aff9780a-7e53-4233-9238-b8cb268aef6c.png)

**Comment by sgiehl** [comment]
It's kind of possible using the API. There is already an older issue regarding this topic, so I will close this one in favor of #18607.
