### ISSUE TITLE
Goal name is truncated when ampersand is present

### ISSUE THREAD

**Issue by marcusosterberg** [piwik/piwik#20174]
## Expected Behavior
I guess goal names / titles should accept a & character

## Current Behavior
Everything after the "&" is scrapped when saving a goal.
My example: 
`2. Mikro: Klickar till etjänsten "Felanmälan&`
When I try:
`2. Mikro: Klickar till etjänsten "Felanmälan&syn"`

## Steps to Reproduce (for Bugs)
The demo environment do not allow me to enter goals.

## Context
I'm trying to have ampersands and other special characters in the name of a goal

## Your Environment
* Matomo Version: 4.13.0
* PHP Version: 7.4.32
* Server Operating System: Ubuntu LTS

* Browser: Brave (Chromium)
* Operating System: Macos 12.6.2

**Comment by sgiehl** [comment]
Hi @marcusosterberg,

The problem actually is not the ampersand. Goal names are limited to 50 chars. But special html chars like `"` or `&` are stored html encoded as `&quot;` or `&amp;`. 
So goal names that reaches that limit (after encoding the html chars) are truncated to 50 chars. This currently might also break those encoded characters as they might get cut off.

I guess in general we should store those names unencoded in that database and ensure the name is encoded whereever it is used. Might be related or solvable with #11786

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/goals-autocorrect-to-html-entities/49904/3

**Comment by heurteph-ei** [comment]
Hi @sgiehl 
Do you know if the fact the goal regular expression (in goal definition) could also be impacted by this bad bahaviour? (URL escaping of `&` char...). See https://forum.matomo.org/t/goals-autocorrect-to-html-entities/49904

**Comment by sgiehl** [comment]
@heurteph-ei Kind of a similar issue. The content is stored sanitized, but seems it's not unsanitized before being displayed again. 
I've created https://github.com/matomo-org/matomo/pull/20495 to fix this in Matomo 5.

**Comment by sgiehl** [comment]
This had been fixed with Matomo 5
