### ISSUE TITLE
Fix PHP8.2 Deprecation Warning on module install

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [piwik/piwik#20176]
## Expected Behavior

Plugin should download with no warnings

## Current Behavior

Plugin downloads but warning banner is displayed:
WARNING: /core/Url.php(599): Deprecated - Use of &quot;self&quot; in callables is deprecated - Matomo 4.13.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Marketplace, Action: installPlugin, In CLI mode: false)

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.13.0
* PHP Version: 8.2.1 (Litespeed version)
* Server Operating System: Fedora 37
* Additionally installed plugins:

* Browser: Librewolf (Security Paranoid Firefox)
* Operating System: Fedora 37

**Comment by sgiehl** [comment]
Hi @Entrepreneur-AJ 
Thanks for creating this issue. I'll prepare a PR to fix it.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/self-is-depreciated/53752/2
