### ISSUE TITLE
Add test builds for PHP 8.2

### ISSUE THREAD

**Issue by bx80** [piwik/piwik#20184]
## Summary

Currently test suites are run against PHP 7.2 and PHP 8.1.

With PHP 8.2 now entering mainstream usage, once we've migrated to github actions we should run all tests against PHP8.2.

This can probably replace the PHP 8.1 build, so we'd test against the lowest (7.2) and highest (8.2) supported PHP versions.

**Comment by sgiehl** [comment]
Let's try doing that one, once we migrated to GitHub actions

**Comment by michalkleiner** [comment]
We are running unit tests, integration and system tests on versions 7.2, 8.2 and 8.3, so I think this can be now marked as done.
