### ISSUE TITLE
Row evolution doesn't work in events when switching secondary dimension

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20180]
Steps to reproduce:

* Go to https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=General_Actions&subcategory=Events_Events
* Click on "Switch to Event Name" in footer
* Click on a category such as "Ecommerce"
* Click on row evolution row action in a row within the subtable. For example "Added - Basic Wetsuit"
* Row evolution will falsely not show any values
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/273120/211394336-81b16eba-4929-4f7b-b4bd-e30cf3d929c0.png">

However, it works for the original secondary dimension

Happens on latest Matomo version 4.13.0. Not sure if this is maybe a regression or not.

**Comment by bx80** [comment]
Thanks for the detailed recreation steps @tsteur :+1: 
I've provisionally flagged this as a regression as I guess it would have worked at some point,

**Comment by heurteph-ei** [comment]
FYI the same on Matomo 4.3.1

**Comment by sgiehl** [comment]
The problem is most likely that the row evolution request does not contain the secondaryDimension parameter. Thus it looks it up with the default dimensions, where nothing is found. I'll have a quick look if that is easy to fix.
