### ISSUE TITLE
When asking for password confirmation, and password confirmation feature is disabled (eg. in SAML or LDAP), then explain they can proceed without entering a password

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20186]
Currently, when using SAML (and soon with LDAP) users see this prompt:
![image](https://user-images.githubusercontent.com/466765/211459341-807d8913-ec1b-4311-b12c-dfbda2c674e0.png)

The password field is disabled, and users can click Yes to continue without a password and it will work

But there is no indication this is the case, so it would be great to, in this case (where the password confirmation is disabled).

How could we solve this issue?

- is it possible to automatically click the YES button or even hide the popover all together when password confirmation is disabled?
- otherwise if not possible, we can show a message within the popover below the title eg.

> Attention: The password confirmation feature is temporarily disabled. You can still proceed with this action by clicking 'YES' without entering a password.

**Comment by sgiehl** [comment]
Not showing the confirmation box at all is not an option in all cases. It's also used to confirm that the user really wants to proceed with the action, so removing the password confirmation would also remove the confirmation step.
We could though provide a different text if it's disabled and also hide the password input maybe.

**Comment by mattab** [comment]
## Proposal

When there is no password to confirm then maybe the modal title could change to:

> Please confirm this change. 

and then the password field could be replaced with a sentence:

> Are you sure you want to continue?

And replace the "YES" by "Proceed" 
and the NO by "Cancel"

**Comment by sgiehl** [comment]
That should be doable. But every password confirmation might use a custom text. So there is more then one text that might need to be adjusted/changed.

**Comment by AltamashShaikh** [comment]
Input from Support on this 
Treat this as a confirmation box and change the button text "yes" -> "proceed"

**Comment by atom-box** [comment]
_Some user feedback from today:_


> The UI is a bit confusing where it asks for a password but the field is blank. Perhaps, in a future release, you can just replace the password textbox with a simple message, like "Password not required" or something.

**Comment by pitbulk** [comment]
@mattab, @sgiehl with the LoginSaml plugin and "enable password confirmation" to false I have the following behavior:

1. Password confirmation sending user invitations shows the following popup:
![image](https://github.com/matomo-org/matomo/assets/600897/893f529d-a23c-44aa-9039-e4026402f0a3)

2. Removing a website 
![image](https://github.com/matomo-org/matomo/assets/600897/a5aac6c7-0e18-44e1-907a-23e0e8b9e564)

3. Save Trusted Matomo Hostname
![image](https://github.com/matomo-org/matomo/assets/600897/757c5920-f48d-4b60-897a-fde5ca5ce044)


the first is the one discussed here where UX should be improved, the second also applies.

But I see that there are other actions requesting password confirmation using another generic popup that is not affected at all by the password confirmation flag.
![image](https://github.com/matomo-org/matomo/assets/600897/cf11cb23-6f9e-43ff-bdc9-df572dc0ff0a)

List of actions:
- Create a new token
- Turn On 2FA

Can we fix the UX as well as support the "enable password confirmation" for the not supported scenarios?

**Comment by AltamashShaikh** [comment]
@pitbulk We fixed the 2FA for LDAP in the plugin as that function needs to be overridden by the plugin to skip password screen, see the code changes [here](https://github.com/matomo-org/plugin-LoginLdap/pull/349/files)

**Comment by pitbulk** [comment]
Cool, I will review the PR you have in PluginSaml and check how cover "Turn On 2FA" action
