### ISSUE TITLE
[PHP8.2] Deprecated dynamic properties

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [piwik/piwik#20197]
## Expected Behavior

All websites view loads without error no matter the immediate page prior

## Current Behavior

Warning messages, showing a deprecation warning on the All Websites Dashboard.

`WARNING: /plugins/BotTracker/Reports/GetBotTrackerAnzeige.php(31): Deprecated - Creation of dynamic property Piwik\Plugins\BotTracker\Reports\GetBotTrackerAnzeige::$subCategory is deprecated - Matomo 4.13.1-rc2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Referrers, Action: getReferrerType, In CLI mode: false)`

`WARNING: /plugins/BotTracker/Reports/GetTop10.php(30): Deprecated - Creation of dynamic property Piwik\Plugins\BotTracker\Reports\GetTop10::$subCategory is deprecated - Matomo 4.13.1-rc2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Referrers, Action: getReferrerType, In CLI mode: false)`

## Steps to Reproduce (for Bugs)

1. From the Dashboard view click on All Websites (Doesn't seem to show when stating from the Tag Manager tab)

## Your Environment

* Matomo Version: 4.13.1-rc2
* PHP Version: 8.2.1
* Server Operating System: Fedora 37
* Additionally installed plugins: `API, Actions, AdminNotification 4.0.0, Annotations, Bandwidth 4.0.3, BotTracker 2.07, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, Dashboard, DeviceDetectorCache 4.3.1, DeviceFeatureWebGL 4.0.1, DeviceNetworkInformation 4.0.1, DevicePixelRatio 2.0.0, DevicePlugins, DevicesDetection, Diagnostics, DiagnosticsExtended 0.1.9, DisableTracking 1.2.0, Ecommerce, Events, GeoIp2, Goals, Heartbeat, HidePasswordReset 4.3.3, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, JsTrackerForceAsync 4.0.0, LanguagesManager, Live, Login, MarketingCampaignsReporting 4.1.3, Marketplace, MobileAppMeasurable, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PasswordVerifier 0.2.3, PrivacyManager, ProtectTrackID 2.3.0, Proxy, QueuedTracking 4.0.6, QuickExcludeVisitorIP 0.1.1, Referrers, ReferrersManager 4.0.3, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, TagManager, Tour, TrackingSpamPrevention 4.1.3, Transitions, TreemapVisualization 4.0.2, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize `

* Browser: Librewolf (Security Paranoid Firefox)
* Operating System: Fedora 37 (KDE Desktop Environment)

**Comment by sgiehl** [comment]
Hi @Entrepreneur-AJ 
Thanks for creating that issue. It seems the problem occurs within the third party plugin BotTracker.
So there is actually nothing we can do here about that.
Fee free to create this issue in the repository of that specific plugin: https://github.com/Thomas--F/BotTracker/issues
Cheers,
