### ISSUE TITLE
AdvertisingConversionExport no ecommerce goals selectable

### ISSUE THREAD

**Issue by stbaum** [piwik/piwik#20200]
The AdvertisingConversionExport does not show up Ecommerce Goals!

Matomo Version 4.13.0
AdvertisingConversionExport 4.1.1

As shown in screenshots it should be possible to use existing ecommerce data as goals for advertising conversion exports, however this is not possible. If you need more informations, jus contact me.

![image](https://user-images.githubusercontent.com/35727948/211827260-342e5edb-1775-484f-b153-d710dde36ad5.png)

**Comment by AltamashShaikh** [comment]
@stbaum Does running `./console cache:clear` and trying again helps ?

**Comment by stbaum** [comment]
> @stbaum Does running `./console cache:clear` and trying again helps ?

tried, but does not help.

**Comment by AltamashShaikh** [comment]
@stbaum You should be able to see "Ecommerce orders" as shown below
![Screenshot from 2023-01-12 10-33-42](https://user-images.githubusercontent.com/14902277/211981737-536ecb12-a522-4adf-8c53-adf5ba36cbac.png)

Do you have any error in the console ?

As per the code if its `isEcommerceSite` you should be able to see atleast "Ecommerce Orders" in the dropdwon

**Comment by stbaum** [comment]
No I do not see it:

![image](https://user-images.githubusercontent.com/35727948/211982920-3b987164-8f21-4096-9a24-5407d449f409.png)

All I see is my manual setup goal

![image](https://user-images.githubusercontent.com/35727948/211983034-96df6126-3fd9-48a2-8e67-608878c72c96.png)

Site is ecommerce enabled, see 1st screenshot.

**Comment by stbaum** [comment]
> Do you have any error in the console ?

Which command to show error, currently everything seems fine:

root@ryz2 /var/www/matomo/tmp/logs # /var/www/matomo/console diagnostics:run
There are no problems with your Matomo setup. Give yourself a pat on the back.

**Comment by AltamashShaikh** [comment]
@stbaum Can you check if its showing up as "Ecommerce: yes" in the Measurables
![Screenshot from 2023-01-12 13-40-48](https://user-images.githubusercontent.com/14902277/212012838-c442e858-2292-45f4-973e-450627b4ee82.png)

Also check the idSite in the URL is correct, we cannot seem to find why the goal named "Ecommerce Orders" won't show up

**Comment by stbaum** [comment]
All websites are E-COMMERCE YES
I do not see any problems with the IDs as well

![image](https://user-images.githubusercontent.com/35727948/212042927-0069400e-99db-479f-b999-1f32957647a1.png)

**Comment by AltamashShaikh** [comment]
@stbaum On the below page
![image](https://user-images.githubusercontent.com/35727948/211827260-342e5edb-1775-484f-b153-d710dde36ad5.png)

Can you open the network tab, refresh the page and filter for `getSitesWithAtLeastViewAccess` and check the response for you siteID, does it have `ecommerce: "1"`
![Screenshot from 2023-01-13 08-49-23](https://user-images.githubusercontent.com/14902277/212229575-77bbe880-70d6-4efa-8ec7-b00644e81991.png)

**Comment by stbaum** [comment]
If you contact me by mail. I could give you full access to the instance, maybe this would speed up the fix.
you may contact me by sb[at]kmp360.de

![image](https://user-images.githubusercontent.com/35727948/212236045-f001ff83-6c4d-439b-b1e0-0b56c77c29d8.png)

**Comment by AltamashShaikh** [comment]
@stbaum I couldn't do that sorry, can you please open a support ticket for this issue, since its a premium feature issue such issues should be raised via support and we can connect and ask for better info on this

**Comment by stbaum** [comment]
Varun from the support team wrote to me, that I should continue here (some hours ago) ...

**Comment by sgiehl** [comment]
@AltamashShaikh I'll close the issue here. As far as I remember we had figured out the problem. So guess this is fixed meanwhile.

**Comment by AltamashShaikh** [comment]
@sgiehl We have a support ticket and we have shared an updated code with the customer and waiting for confirmation, good to close :+1:
