### ISSUE TITLE
Problem opening CSV files in Excel

### ISSUE THREAD

**Issue by samiii3103** [piwik/piwik#20211]
When exporting a CSV file from the report system, it cannot be opened in Excel correctly anymore. No matter what encoder is used, it will always only display the first column. All other columns are cut off. 
![ImportWindowExcel](https://user-images.githubusercontent.com/26456180/212294021-859d56f3-9de3-4cf5-8bb5-cc8093d82332.png)

The file is still using comma to seperate the data. Nevertheless, the data cannot be displayed correctly.
![EditorView](https://user-images.githubusercontent.com/26456180/212295128-e9cc2e43-0c32-4192-8f56-e828dfa64fba.png)

**Comment by heurteph-ei** [comment]
Since when doesn't it work anymore?
What are your Matomo and Excel versions?
Did you try to use the TSV format instead of the CSV format while exporting Matomo data into Excel file?

**Comment by sgiehl** [comment]
I'll close this one now, as there hadn't been an further feedback.
Excel often fails when using CSV files that use a comma as separator, as it expects a semicolon instead. In most cases it works fine when opening the file customly and define the separators manually.
