### ISSUE TITLE
Matomo issue for new mesurable element

### ISSUE THREAD

**Issue by ImPulsive76** [piwik/piwik#20219]
Hi,

I've an issue on my self-hosted Matomo, I use the 4.13.0 version. It's impossible to save a new mesurable element, so I can't add a new website on the plateform. Also, when i check for issues, a message appears : "Oops... There was a problem processing the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Try Again. If this error repeats please contact your Matomo administrator for assistance."

Can you help me for that please ? Thanks !

Have a great day,
Siegfried Lefez

**Comment by heurteph-ei** [comment]
Hi @ImPulsive76 
Can you have a look at errors in:
 - The browser console
 - The browser network log
 - The Matomo error log file

?

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback.
