### ISSUE TITLE
Creating a new segment that has some visits will show 2 notifications instead of 1

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20222]
After creating a new segment on Cloud, that matches some visits, then we see this:

![image](https://user-images.githubusercontent.com/466765/212809218-d4fe11d9-0b2e-47ef-a7af-751ace8861d0.png)

Instead, we would only expect the blue notification?

Is this maybe a regression? 
Can we confirm that we have a uI test for this and whether it shows this?

**Comment by sgiehl** [comment]
The second message should actually only be shown for segments that aren't stored in the database.
@mattab does the segment value contain any special chars maybe?

**Comment by mattab** [comment]
It doesn't contain special chars:

![image](https://user-images.githubusercontent.com/466765/212867102-6f9f3298-20ba-4d53-b612-4b7bb280a5f5.png)

**Comment by sgiehl** [comment]
Wondering if this might be related to https://github.com/matomo-org/matomo/issues/20060

**Comment by mattab** [comment]
as I can still reproduce this in our company account, I suppose this applies to all Cloud customers, which could have a big impact, so adding to 4.x to fix?
 reproduced here today: https://web.innocraft.cloud/index.php?module=CoreHome&action=index&idSite=12&period=month&date=today&updated=1#?period=month&date=today&category=Dashboard_Dashboard&subcategory=1&segment=countryName%3D%3DFrance

we would expect only the blue notification and not the red one

**Comment by sgiehl** [comment]
I was actually not able to reproduce that on our company account, but I was able to reproduce that red message locally.
It seems to be caused by the SingleMetricView widget. That one directly queries the API. And if the API doesn't find an usable archive it may throw that exception. I'll prepare a fix for that.
