### ISSUE TITLE
Keep selected site when returning to the dashboard from Tag Manager

### ISSUE THREAD

**Issue by mhh515** [piwik/piwik#20232]
Let's say the default website is "A" after logging on.
1. In the dashboard select site "B".
2. Go to Tag Manager and do Tag Manager stuff for site "B".
3. Return to the dashboard.
--> Site "A" is now selected in the dashboard.

When exiting tag manager it would be better if the same site that was selected in tag manager were selected when returning to the dashboard, not the default or any other site.

**Comment by AltamashShaikh** [comment]
@mhh515 This is due to Matomo core which considers default siteID for such cases, I am moving this issue to core as it will be easier to fix via core.

**Comment by sgiehl** [comment]
The menu entry is handled here: https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Dashboard/Menu.php#L23

@mattab do you think it makes sense to change the Dashboard link in the upper menu to use the idSite of the current url and fall back to the default one, only of there isn't any? Would be implemented in a couple of minutes though...

**Comment by mattab** [comment]
Thank you @mhh515 for your suggestion, this would be a nice UX improvement :+1: 

@sgiehl let's go ahead and change it so that after working in Tag manager on a specific website, then going back to the Dashboard should keep that website selected,

**Comment by mhh515** [comment]
Thanks! :)
