### ISSUE TITLE
Anchor link issue on the tracking code page of the admin when clicking on MTM

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20233]
Hi team,
If one access to the admin of Matomo within the tracking code part and click on the link MTM, then it goes at the bottom and then if you scroll up it will automatically scroll you down.

**Comment by heurteph-ei** [comment]
And the same if you:
 1. Click on any Tracking code link
 1. Hover the Tracking code block header: triggers an automatic scroll down to the Tracking code anchor...

**Comment by sgiehl** [comment]
This should be fixed with https://github.com/matomo-org/tag-manager/pull/592

@heurteph-ei I don't fully understand your report. When exactly is the scrolling triggered and where? If you clicked the broken tagmanager link before, that might be a reason...

**Comment by heurteph-ei** [comment]
@sgiehl:
Sorry, It was a bug on version 4.3.1, but no more on 4.10+
