### ISSUE TITLE
Real-time page interval reload button to top

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#20238]
Matomo Version: 4.13.1
Matomo Update History: 4.11.0,4.10.1,4.9.1,4.7.0,4.6.2,4.6.1
Matomo Install Version: Unknown - pre 3.8.
Latest Available Version: 4.13.1

Hello, i think it is better when in the Real-time page and widget the interval reload button for pause and start is on the to top of the page, or top _and_ bottom.

**Comment by sgiehl** [comment]
Hi @matomoto. I'll close this as duplicate of https://github.com/matomo-org/matomo/issues/19669, which already requests to move all control element of a report to the top.
