### ISSUE TITLE
Cant access marketplace, request was blocked by WAF.

### ISSUE THREAD

**Issue by carlgrundberg** [piwik/piwik#20259]
## Expected Behavior

It should be possible to show Matomo marketplace from within Matomo on a local installation.

## Current Behavior

I get an error when going to the markteplace and when I debug the problem it seems that the request to the plugins API is blocked by WAF. I get this response.

`<html><body><h1>Forbidden<br>Request was blocked by WAF.</h1><p></p><p>Request ID: c02cc3a8-4fecae25</p></body></html>`

I dont think the API request params matter but its something like this.
https://plugins.matomo.org/api/2.0/plugins?module=Marketplace&action=overview&idSite=1&period=day&date=yesterday&activated=&mode=admin&type=&show=

It works in our production environment and if I run the request locally in my browser, but not in my local environment.

## Your Environment

* Matomo Version:  4.12.3 4.13.0 4.13.1 
* PHP Version: 8.1.3

**Comment by sgiehl** [comment]
Hi @carlgrundberg 
Sorry to hear you are having problems with a WAF. Unfortunately there is not much we can do about that, without knowing which exact rule blocks the request and why.

**Comment by carlgrundberg** [comment]
Maybe i misunderstand your answer, but it's the request made from the Marketplace plugin to your plugin website (url above), so it's the WAF on your side and nothing I have any insight of.

I have used Matomo in development for a couple of years now and it never happened before.

**Comment by carlgrundberg** [comment]
The error originates from here:

https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Marketplace/Api/Client.php#L290

**Comment by sgiehl** [comment]
Ah. I thought it's a WAF on your side blocking the request. I'm not responsible for our WAF. maybe @tsteur can say something on that.

**Comment by tsteur** [comment]
@carlgrundberg do you mind checking again if it works now? We've made a change and it should work now

**Comment by carlgrundberg** [comment]
Yes it works now, thank you!

**Comment by tsteur** [comment]
Great. Sorry about that @carlgrundberg
