### ISSUE TITLE
PerformanceAudit - Functions deprecated

### ISSUE THREAD

**Issue by nicomegadrive** [piwik/piwik#20267]
Hi,

I'm currently using Matomo 4.13.1 and I'm having an issue while enabling the plugin "Performance Audit", it seems to prevent the cron tasks to work properly, here is the error when I navigate to the "Plugin check" section : 

WARNING: /plugins/PerformanceAudit/vendor/symfony/process/Process.php(612): Deprecated - Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice - Matomo 4.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: PerformanceAudit, Action: pluginCheck, In CLI mode: false)

Did someone run into this issue before ? How to solve it ?

Thanks.

**Comment by sgiehl** [comment]
Hi @nicoco59. This plugin is a third party plugin. We are unable to fix anything in it.
You can try to open this issue in the repository of the plugin here: https://github.com/DevDavido/performance-audit-plugin

Cheers,
