### ISSUE TITLE
Inconsistancy in Engagement values: bounced visits vs Visits with only one page

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20265]
## Expected Behavior
The **Frequency Overview** (in **Behavior > Engagement** report) should display the same number of bounced visits than displayed in **Visits per number of pages** (also in **Behavior > Engagement** report).

## Current Behavior
I cannot explain that the number bounced visits is really higher than the number of visits with only 1 page.
### On the [Matomo demo site](https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=week&date=2023-01-19&idSite=1&category=General_Actions&subcategory=VisitorInterest_Engagement)
![image](https://user-images.githubusercontent.com/79993552/214543190-d053db7f-d6e4-4f66-8a9b-99dc2974ce6e.png)
The same on a single day:
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=2023-01-16&idSite=1&category=General_Actions&subcategory=VisitorInterest_Engagement

### On my side (Matomo 4.3.1)

![image](https://user-images.githubusercontent.com/79993552/214532400-51ab9611-bc85-44d3-a76e-6e045a15688a.png)

## Possible Solution
Maybe this is not a bug, but just need some explanation...?

**Comment by sgiehl** [comment]
@heurteph-ei The Frequency report at the top actually show visits grouped by `returning visitors` and `new visitors`. The number of pages report below shows a metric that contains both. So they are not directly comparable.

**Comment by heurteph-ei** [comment]
Hi @sgiehl 
Thanks for your reply.
Ok, sorry, I read too fast the first graph.
