### ISSUE TITLE
Monthly email report : visits by day of week only for the day before

### ISSUE THREAD

**Issue by paysages** [piwik/piwik#20266]
I use a monthly email report selecting "Visits by day of week" but the report, for this category, shows only the data for the day before and not for all the previous month (it's ok for the others graphics).

**Comment by bx80** [comment]
Thanks for reaching out @paysages, unfortunately this report is only intended to show data for a single day.

For more information see this forum post: https://forum.matomo.org/t/report-visits-by-day-of-week-empty/13478
