### ISSUE TITLE
Uncaught exception: Error: Cannot access private property Piwik\DataAccess\ArchiveWriter::$idArchive 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20276]
We're getting this error with Matomo 4.13.2. This looks like a regression

Uncaught exception: Error: Cannot access private property Piwik\DataAccess\ArchiveWriter::$idArchive in plugins/SearchEngineKeywordsPerformance/Importer/Google.php:388
Stack trace:
#0 plugins/SearchEngineKeywordsPerformance/Importer/Google.php(177): Piwik\Plugins\SearchEngineKeywordsPerformance\Importer\Google->completeExistingArchiveIfAny(Object(Piwik\Period\Day))
#1 /plugins/SearchEngineKeywordsPerformance/Importer/Google.php(138): Piwik\Plugins\SearchEngineKeywordsPerformance\Importer\Google->completeExistingArchivesForListOfDates(Array)

**Comment by sgiehl** [comment]
That's a regression of #20235. Wasn't aware that property is directly used somewhere. I'll propose a fix soon.
@tsteur Might be good to directly fix that on cloud as well, as it might cause problems with the archiving of that plugin.

**Comment by tsteur** [comment]
Thanks @sgiehl applied a patch on cloud 👍  I assume this also affects On-Premise customers? In that case we would need to release a patch release fairly soon

**Comment by Juri-Salminen** [comment]
I'm an On-Premise user and this error affects me, so would really appreciate a patch fairly soon :)

**Comment by hyzteric** [comment]
> I'm an On-Premise user and this error affects me, so would really appreciate a patch fairly soon :)

Same here ;-)

**Comment by sgiehl** [comment]
We have released a new version yesterday that should have fixed the issue.

**Comment by hyzteric** [comment]
Fixed with last update indeed.
Thank you!
