### ISSUE TITLE
Update to version 4.13.2

### ISSUE THREAD

**Issue by xloouch** [piwik/piwik#20271]
Depricated Error Message after upgrading to 4.13.2

OS: Debian 11
Webserver: Apache 2.4.54
PHP: 8.2.1
Matomo: 4.13.2

Error Message: 
WARNING: /plugins/CoreVisualizations/Visualizations/HtmlTable.php(293): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizations\Visualizations\HtmlTable::$siteSummary is deprecated - Matomo 4.13.2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: DevicesDetection, Action: getBrowserVersions, In CLI mode: false)

Website-View
![grafik](https://user-images.githubusercontent.com/81850525/214791790-4835c00a-5a4e-4d3c-967e-8b0841acc276.png)

or in "all websites-view"

![grafik](https://user-images.githubusercontent.com/81850525/214791975-7d762540-f311-46f4-b8f2-ad9e76166d57.png)

**Comment by heurteph-ei** [comment]
Hi @xloouch 
Seems to be already reported in:
https://github.com/matomo-org/matomo/issues/20236 (point `#5`)

**Comment by xloouch** [comment]
thank you @heurteph-ei
