### ISSUE TITLE
Help! To fix missing content-interactions and interaction-rate in content tracking.

### ISSUE THREAD

**Issue by areeshaad** [piwik/piwik#20281]
Hi there,
We are implementing 'content tracking' by following developer-matomo guide. Here is the reference URL for that guide. https://developer.matomo.org/guides/content-tracking
Here is my website url,    https://vanlifemagazin.eu/
We have added "**data-content-target, data-track-content, data-content-name and data-content-piece**". When I visit on matomo dashboard to see the content tracking result I find blank content interaction and 0% interaction rate. Here are the screenshots for more clarity,
this is my content piece for interaction tracking,
![mako](https://user-images.githubusercontent.com/98154363/215082730-42cdc6de-a19f-4bb4-b1e4-06acfe785ec9.png)
Here are content tracking terms used in code.
<a href="https://makosport.at" data-content-target="https://makosport.at" data-track-content="" data-content-name="MAKO Ad" target="_blank" id="mako_ad_banner_a">
<img src="https://vanlifemagazin.eu/wp-content/uploads/Mako-klein.jpg" data-content-piece="MAKO Bannerimage" id="mako_ad_banner_img">
</a>
![mako code](https://user-images.githubusercontent.com/98154363/215083296-ad14d1d9-a26f-40f4-a5e6-d740101ab776.png)
Here is the interaction result,
![mako-dashboard](https://user-images.githubusercontent.com/98154363/215083540-10b71417-7455-4714-bdd0-86a6fbd16e1a.png)
So here the main issue is why these both "content-interaction and interation-rate" are blank. How can I track them? How can I get this percentage? What should I do to fix this issue and meet my requirements? Any help or suggestion from anybody would be highly appreciated. Thanks alot dear all.

**Comment by heurteph-ei** [comment]
Hi,

Did you have a look at this chapiter?
https://developer.matomo.org/guides/content-tracking#what-can-i-do-if-an-impression-is-tracked-automatically-but-not-an-interaction

**Comment by areeshaad** [comment]
Thank you @heurteph-ei for pointing the right way. :)

**Comment by heurteph-ei** [comment]
Did this solve your issue?

**Comment by areeshaad** [comment]
Yes. With a bit modifications it was solved. Thanks again @heurteph-ei
