### ISSUE TITLE
Customize Email Reports

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20294]
Customer has asked about the possibility of being able to adjust the text that is displayed in the **Email Reports**. Basically the ability to type a brief custom message, displayed in the email report, for the recipients of these emails.

"Is it possible to customize the text in the e-mail itself? So we can write a personal message to the receiver of the report"

**Comment by bx80** [comment]
Thanks for the feedback @goochj03, there isn't any option to set a custom message for the report emails at the moment. 

Seems like this could be a useful feature. I'll assign this issue for prioritisation :+1:

**Comment by ghost** [comment]
[]()

**Comment by mattab** [comment]
Note it is already possible to customise the email report. 

By setting a “Description” in the email report it’s already possible to customise one sentence in the email:  here in orange is the “email report description” that was set:
![Screenshot from 2023-03-12 11-02-19](https://user-images.githubusercontent.com/466765/224513438-86af054f-7af8-4ab7-96e0-970654a68faf.png)

This will then be displayed in the email message after the "Hello":

![image](https://user-images.githubusercontent.com/466765/224513492-096b86a8-491c-4d4b-ab5b-e466bb90ce29.png)


So maybe we could improve the inline help from:

> The report description will be displayed on the first page of the report.

to include also the email eg.

> The report description will be displayed in the email message, as well as on the first page of the report.

 maybe this would make it more clear to people it’s already possible?

**Comment by michalkleiner** [comment]
Adding some further scope from #20856:

> I have noticed that, currently, there is no option to customize the text and footer in report emails. This customization ability could give users the flexibility to tailor their reports according to their specific needs and the audience they are intended for.
>
> The addition of this feature would allow users to input personalized comments, notes, or conclusions in the body of the email message, allowing greater flexibility in the presentation of data. Additionally, customizing the footer could be used to include contact information, copyright notices, or any other information that an organization might want to include in their reports.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/change-the-text-of-the-message-and-the-footer-of-the-matomo-report-email/51662/3
