### ISSUE TITLE
In accept invitation screen show the email instead of the username

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20306]
Currently, when someone is invited, then we show their username in the `Username or email` field.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/273120/216178334-88a2ffc9-ce0c-4d4d-b961-e8e535316f76.png">

However, it makes people think they need to remember their username in order to log in when it's actually not needed as people can log in with their email. The username would have been defined by the person that invited someone or automatically by the system if they signed up for a trial. Meaning it is not a username that was defined by them.

IMO it be better to show the email address there so people don't have to remember anything extra.

This comes from CLOUD-1172 where as part of onboarding it was suggested to show email address there rather than username.

**Comment by sgiehl** [comment]
@tsteur that would be a very easy change. Let me know if this is something that should be included in the next patch release.

**Comment by tsteur** [comment]
If it's very easy change that be great to include 👍
