### ISSUE TITLE
2FA plugin: Depreciation in PHP 8.2

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20307]
Another ticket on PHP 8.2 depreciation (from https://forum.matomo.org/t/warning-plugins-usersmanager-repository-userrepository-php-252-deprecated/49554):
 - [ ] WARNING: /plugins/UsersManager/Repository/UserRepository.php(252): Deprecated - Creation of dynamic property Piwik\Plugins\UsersManager\Repository\UserRepository::$twoFaPluginActivated is deprecated - Matomo 4.13.3 (Module: API, Action: userSettings, Method: UsersManager.getUser, In CLI mode: false)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-plugins-usersmanager-repository-userrepository-php-252-deprecated/49554/2
