### ISSUE TITLE
Add subtable to DataTable

### ISSUE THREAD

**Issue by jorgeuos** [piwik/piwik#20316]
Hi,

I'm kinda stuck.

I followed the examples in: [Developers guide](https://developer.matomo.org/guides/datatable)

I'm trying to add a Subtable to a DataTable but when I try to open the Subtable I only get the same row over and over again.

What am I doing wrong here?

```php
        $table = new DataTable();
        $arrayOfThings = ['label' => 'thing1', 'nb_visits' => 1, 'nb_actions' => 1];
        $row = new Row([$arrayOfThings]);
        $subTable = new DataTable();
        $arrayOfThings2 = ['label' => 'thing2', 'nb_visits' => 2, 'nb_actions' => 2];
        $row2 = new Row([$arrayOfThings2]);
        $subTable->addRow($row2);
        $row->setSubtable($subTable);
        $table->addRow($row);
        return $table;
```
<img width="999" alt="Screen Shot 2023-02-03 at 09 59 55" src="https://user-images.githubusercontent.com/21176316/216557902-0dfdeb8e-66c0-4f88-bb01-1f114efb5db9.png">

Br, Jorge

**Comment by sgiehl** [comment]
Your API method most likely needs to support sending a `$idSubtable`, so it only returns a subtable when a `$idSubtable` is sent.

**Comment by jorgeuos** [comment]
I appreciate your quick response!! 🙏🏼

I'll give that a try! Thanks!
