### ISSUE TITLE
Get more people to see what's new in the product

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20313]
Currently, very few people click on "what's new". Partially, this may be because of https://github.com/matomo-org/matomo/issues/20312 . 

In many products I'm seeing that when there is something new, then a new popup/modal opens automatically showing the new entry right away. This way they ensure that every active user is aware of what is new.

This could be something we do as well maybe?

Meaning when a person accepts an invite, then we set the current "latest change number as seen". When there is the a new entry, we open the window with only the new entries since last time.

When clicking on the "What's new icon" we would show the usual last X entries (we should make sure to not show too old entries).

**Comment by atom-box** [comment]
+1

Here's a GA4 Modal example. They show a series of "what's new" modals that pop up in the lower left, the far right, the top, including Previous/Next button. In all it's a 6 panel tour to orient the new user: 

![image](https://github.com/matomo-org/matomo/assets/22874146/02b1bf15-cb99-4b5c-8d53-21097e7d151b)

This UI strategy seems a nice complement of a mouseover tooltip: a tooltip explains something you already noticed, these quick tour modals explain something you did not notice yet.

**Comment by sgiehl** [comment]
This was improved a lot with https://github.com/matomo-org/matomo/pull/21271 
Not sure if we can close this one or if we should keep it open to check if too old entries might still be shown...
