### ISSUE TITLE
Date comparison selector should stay when changing site

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20321]
## Expected Behavior
When I select a date comparison other than **Previous period**, then change the selected site, I would like the comparison selector stays at the one selected (and displayed).

## Current Behavior / Steps to Reproduce (for Bugs)
1. Go to your favorite Matomo instance: https://demo.matomo.cloud/index.php
2. Select a date comparison other than **Previous period** (eg. another day in the same month)
3. Change the site selector (from **Demo site** to **Example site** for example)
4. OK, the comparison is still taken into account... But when the comparison date needs to be changed, the date comparison selector has been reset to **Previous period**

## Possible Solution
Minor display bug. Just need to select the date comparison type  again...

## Your Environment
Visible in demo site, but was already buggy in 4.3.1

**Comment by sgiehl** [comment]
Thanks @heurteph-ei for reporting this one. 
I'm not sure if that is something that would be expected by everyone. We could though implement that for date comparison only, which would make it a bit inconsistent maybe, as a segment comparison couldn't be kept (as they might not exist).
I'll let the product team decide to consider this as a future improvement.

**Comment by heurteph-ei** [comment]
Hi @sgiehl 
This is not a new feature, it is just an UI bug.
When changing displayed site, the date comparison is kept for the reports calculations, but the date selector is reset to "Compare to previous period".

**Comment by sgiehl** [comment]
Ah ok, guess now I understood. So the selector isn't initialized with the correct values after loading a new site.

**Comment by michalkleiner** [comment]
The issue is not related to switching websites, a simple reload presents the issue as well.
The date range selector doesn't correctly pick up the query parameters and always displays 'Previous period'.
