### ISSUE TITLE
"count(): Argument #1 ($value) must be of type Countable|array, null given"..... I need help

### ISSUE THREAD

**Issue by McSherlock** [piwik/piwik#20320]
I am using this code in my project and I got an error saying 

"count(): Argument #1 ($value) must be of type Countable|array, null given" 

...... This is relating to the first line. 

for ( $product_id = 0; $product_id < count($request->product_id); $product_id++) {
                $order_details = new Order_Detail;
                $order_details->order_id = $order_id;
                $order_details->product_id = $request->product_id[$product_id];
                $order_details->quantity = $request->quantity[$product_id];
                $order_details->unitprice = $request->price[$product_id];
                $order_details->discount = $request->discount[$product_id];
                $order_details->amount = $request->total_amount[$product_id];
                $order_details->save();
            }

**Comment by sgiehl** [comment]
Hi @McSherlock 
If you are seeking for help on coding issues, maybe try to find that on our forum instead at https://forum.matomo.org
We are only handling bug reports or feature requests here.

Nevertheless in the example above it seems that `$request->product_id` is not an array or a class that implements the `Countable` interface. The reason for that can't be identified by the code snippet, as it does not include where the variable is defined.
