### ISSUE TITLE
Fatal error in referrer type subtable: Piwik\\DataTable\\Row::setSubtable(): Argument #1 ($subTable) must be of type Piwik\\DataTable, Piwik\\DataTable\\Map given, 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20339]
Happens with latest Matomo version.

> Error: {"message":"Piwik\\DataTable\\Row::setSubtable(): Argument #1 ($subTable) must be of type Piwik\\DataTable, Piwik\\DataTable\\Map given, called in plugins\/Referrers\/DataTable\/Filter\/SetGetReferrerTypeSubtables.php on line 86","file":"core\/DataTable\/Row.php","line":314,"request_id":"21ab3","backtrace":" on core\/DataTable\/Row.php(314)\n#0 plugins\/Referrers\/DataTable\/Filter\/SetGetReferrerTypeSubtables.php(86): Piwik\\DataTable\\Row->setSubtable(Object(Piwik\\DataTable\\Map))\n#1 core\/DataTable.php(532): Piwik\\Plugins\\Referrers\\DataTable\\Filter\\SetGetReferrerTypeSubtables->filter(Object(Piwik\\DataTable))\n#2 core\/DataTable\/Map.php(109): Piwik\\DataTable->filter('Piwik\\\\Plugins\\\\R...', Array)\n#3 plugins\/Referrers\/API.php(160): Piwik\\DataTable\\Map->filter('Piwik\\\\Plugins\\\\R...', Array)\n#4 [internal function]: Piwik\\Plugins\\Referrers\\API->getReferrerType('all', 'day', '2023-02-07', false, false, false, '1', '0')\n#5 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#6 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#7 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#8 core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getReferrerType', Array)\n#9 core\/API\/Request.php(560): Piwik\\API\\Request->process()\n#10 plugins\/Referrers\/API.php(208): Piwik\\API\\Request::processRequest('Referrers.getRe...', Array, Array)\n#11 [internal function]: Piwik\\Plugins\\Referrers\\API->getAll('all', 'day', '2023-02-07', false)\n#12 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#13 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#14 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#15 core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getAll', Array)\n#16 plugins\/API\/API.php(483): Piwik\\API\\Request->process()\n#17 [internal function]: Piwik\\Plugins\\API\\API->getBulkRequest(Array)\n#18 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#19 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#20 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#21 core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getBulkRequest', Array)\n#22 plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#23 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#24 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#25 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#26 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#27 index.php(25): require_once('c...')\n#28 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> POST: {"token_auth":"XYZANONYMIZED","module":"API","method":"API.getBulkRequest","urls":["method=Referrers.getAll"],"idSite":"all","date":"2023-02-07","format":"json","period":"day","filter_limit":"-1"}

**Comment by sgiehl** [comment]
That turns out to be an edge case. We have a check that should prevent that method from being called with multiple sites. But in case `all` only returns one site, that check fails.
