### ISSUE TITLE
Fatal error: Argument #1 ($value) must be of type Countable|array, null given in DataTable.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20333]
Getting below error on latest Matomo:

> Error: {"message":"count(): Argument #1 ($value) must be of type Countable|array, null given","file":"\/core\/DataTable.php","line":1036,"request_id":"b3807","backtrace":" on \/core\/DataTable.php(1036)\n#0 \/core\/DataTable.php(1036): count(NULL)\n#1 \/core\/DataTable\/Renderer\/Xml.php(166): Piwik\\DataTable->getRowsCount()\n#2 \/core\/DataTable\/Renderer\/Xml.php(101): Piwik\\DataTable\\Renderer\\Xml->renderArray(Array, '\\t')\n#3 \/core\/DataTable\/Renderer\/Xml.php(35): Piwik\\DataTable\\Renderer\\Xml->renderTable(Array)\n#4 \/core\/API\/ApiRenderer.php(77): Piwik\\DataTable\\Renderer\\Xml->render()\n#5 \/core\/API\/ResponseBuilder.php(236): Piwik\\API\\ApiRenderer->renderArray(Array)\n#6 \/core\/API\/ResponseBuilder.php(113): Piwik\\API\\ResponseBuilder->handleArray(Array)\n#7 \/core\/API\/Request.php(273): Piwik\\API\\ResponseBuilder->getResponse(Array, 'API', 'getProcessedRep...')\n#8 \/core\/Context.php(28): Piwik\\API\\Request->Piwik\\API\\{closure}()\n#9 \/core\/API\/Request.php(274): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#10 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#11 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#12 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#13 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#14 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#15 \/index.php(25): require_once('\/c...')\n#16 {main}"

> URL: /index.php?module=API&format=XML&idSite=2&period=range&date=2023-02-01,2023-02-07&method=API.getProcessedReport&apiModule=Actions&apiAction=getPageUrls&expanded=1&token_auth=XYZANONYMIZED&filter_limit=-1

> Referrer: None

> GET: {"module":"API","format":"XML","idSite":"2","period":"range","date":"2023-02-01,2023-02-07","method":"API.getProcessedReport","apiModule":"Actions","apiAction":"getPageUrls","expanded":"1","token_auth":"XYZANONYMIZED","filter_limit":"-1"}

**Comment by bx80** [comment]
I've created a PR to check for a non-array row property in this class before each attempting to count it.
