### ISSUE TITLE
Add ability to limit no of rows in FieldConfig::UI_CONTROL_MULTI_TUPLE

### ISSUE THREAD

**Issue by AltamashShaikh** [piwik/piwik#20352]
If we use FieldConfig::UI_CONTROL_MULTI_TUPLE to create a setting it creates `n` no of rows and there is no way to limit the rows allowed.

Example: Below UI will keep adding rows and it cannot be restricted via any FieldConfig setting

![Screenshot from 2023-02-13 18-20-26](https://user-images.githubusercontent.com/14902277/218472893-c8686e31-7ff5-4380-82ea-3a26ca47cfb1.png)

It will be good to have a way to limit the rows or have a min and max no of rows that can be added

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

**Comment by sgiehl** [comment]
Thanks @AltamashShaikh for the suggestions.
I'll have a quick look if can maybe implement that for Matomo 5.
Guess we could use the `rows` property maybe to limit the number of entries. That way it might be very quick to implement...
