### ISSUE TITLE
WooCommerce track 'On Hold' orders

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20363]
Is it possible to add tracking for the status of an order in the Matomo WooCommerce plugin if an order has a status of **On Hold**.

Currently this is not tracked, likely because no payment has been received for the order.

Customer Comment: "We would like to track all orders that are received in our Woocommerce shop. The system currently skips those orders that come in with the status "**on hold**"."

**Comment by sgiehl** [comment]
@goochj03 Could you please create an internal issue for the `WooCommerceAnalytics` plugin instead. We can't handle that in core.
