### ISSUE TITLE
top controls are sometimes not displayed when there are multiple site records in the wordpress plugin

### ISSUE THREAD

**Issue by mattmary** [piwik/piwik#20389]
refs https://github.com/matomo-org/matomo-for-wordpress/issues/727
To summarize, some of our users with one blog only haven't the top-controls displayed. 
In their case, they should have only one idsite in the matomo table. Unfortunately, we have a bug in our synchronization process between the WordPress data and the Matomo ones which lead to a situation that they have multiple sites in the Matomo site tables.
For some of them (see the related issues), they also have data for all sites in their matomo report tables.

In this configuration, they should have listed all the websites available in the Matomo site table in the top-controls. But instead, the top-controls are hidden.

## Expected Behavior

Display all available sites in the Matomo sites table and display the top-controls fields.

## Current Behavior

top-controls are sometimes hidden when there are more than one site in the Matomo sites table.

## Possible Solution

Workaround is for now to delete the unexpected records. But it does not explain why the site records are hidden and not displayed.

## Steps to Reproduce (for Bugs)

See related issue.

## Your Environment

* Matomo Version: 4.12 and 4.13
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
@mattmary Would you mind explaining how this issue is related to core? Matomo itself should always display all top menus. Isn't there some additional code in the wordpress plugin to hide the menu under certain circumstances maybe?

**Comment by mattmary** [comment]
Hello @sgiehl 

I've created this issue especially because we have no CSS nor config which concern this Matomo part.
Here's the config updates we use in the plugin:
https://github.com/matomo-org/matomo-for-wordpress/blob/develop/config/config.php

**Comment by sgiehl** [comment]
There is actually some code to show the controls once, they are rendered. See 
https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/CoreHome/javascripts/top_controls.js#L30-L51
Maybe that fails for any reason. But as this is not reproducible in core it's hard to find the reason.
Maybe it helps you to identify the problem?
