### ISSUE TITLE
Dashboard - Email report feature request

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#20387]
As of now, this feature is not available: Export a newly created Dashboard in Matomo as email reports so that it can be shared.

**Comment by Birkaransingh94** [comment]
More feedback and request:
 If we can choose a widget and then we can add that widget to a report (for email) that would be great. :)

**Comment by Starker3** [comment]
FYI this is a duplicate of https://github.com/matomo-org/matomo/issues/13820

**Comment by Stan-vw** [comment]
Thanks @Starker3. Closing this ticket as it's a duplicate.
Any further comments on this feature request can go into https://github.com/matomo-org/matomo/issues/13820
