### ISSUE TITLE
@$_SERVER['HTTP_ACCEPT_LANGUAGE'] cause error in php >8

### ISSUE THREAD

**Issue by hamburger123456** [piwik/piwik#20388]
in core/common.php the line: $browserLang = self::sanitizeInputValues(@$_SERVER['HTTP_ACCEPT_LANGUAGE']);   
cause the error <<Undefined array key "HTTP_ACCEPT_LANGUAGE">> with some bots.
The @ (silent-mode) do not work longer as expected in php8.

use: if ( is_null($browserLang) && array_key_exists('HTTP_ACCEPT_LANGUAGE', $_SERVER) ) {  ... insted

**Comment by sgiehl** [comment]
That type of error should actually still be hidden in PHP 8.
Nevertheless we should get rid of using the `@` operator at all.

**Comment by sgiehl** [comment]
I've added a fix for that in #20376
