### ISSUE TITLE
Check and fix missing tables and columns during upgrade

### ISSUE THREAD

**Issue by hey-tony** [piwik/piwik#20382]
After performing automatic upgrade I ran into an issue where I would get a database error trying to query an **"_access"** table that didn't seem to exist. 

The query:
```sql
SELECT access, t2.idsite FROM xxxx_access as t1 JOIN xxxx_site as t2 USING (idsite) WHERE login = ?SELECT access, t2.idsite FROM xxxx_access as t1 JOIN xxxx_site as t2 USING (idsite) WHERE login = ?
```

After poking around the schema I was able to manually create the SQL table referencing the following: https://github.com/matomo-org/matomo/blob/4.x-dev/core/Db/Schema/Mysql.php#L88

## Expected Behavior

When upgrading from an old version of 4.x Matomo, it is expected that the upgrade not result in an error.

## Current Behavior

Code is tested based on an assumed path / state. Since this is not a state machine and the user can upgrade from any previous version (any state), it is impossible to test all scenarios. So an assumed path is tested, i.e, 4.1 -> 4.2  or  3.x to 4.x etc. Somehow my upgrade broke. 

## Possible Solution

To prevent future errors, instead of failing and displaying a SQL error, can the code automatically check that all tables exist and create any missing tables from the schema. Essentially creating self-healing code.

## Steps to Reproduce (for Bugs)

1. Unfortunately I did not record my previous version. It was a 4.x version.
2. My Matomo doesn't appear to have many logs, therefore I was unable to go back and find my previous version.

## Context

Unable to log in or do anything once the error is shown.

## Your Environment

* Matomo Version: 4.13.3
* PHP Version: 7.4.33
* Server Operating System: Linux
* MySQL version: 10.6.11-MariaDB

**Comment by bx80** [comment]
Thanks for the feedback @hey-tony, a self-healing schema would certainly be a nice feature to have :+1:

The `access` table has been part of Matomo since before version 1.0., so for any 4.x upgrade it should definitely exist. It's also alphabetically the first table in the database so usually the most vulnerable to any errant commands or file issues. Glad you managed to get it sorted.

I'll assign this issue for prioritization as a suggestion to recreate missing tables / columns rather than throwing an error.

**Comment by mattab** [comment]
Thanks for the report. Because the tables is not supposed to go missing, and we haven't heard other reports about it, i'll close it for now, but if anyone experiences it, please open a new issue or comment here :ok_hand:
