### ISSUE TITLE
Incorrect visualization of page titles in visitor profile

### ISSUE THREAD

**Issue by annamaureder** [piwik/piwik#20391]
Our organization recently updated to Matomo 4.12.3 - before that we used an earlier version from a couple of years ago (Version < 4). Since the update, the tracking data of one of our applications does not seem to be visualized properly. In our application we directly call the Tracking API over HTTPS. We already checked all required and recommended parameters, but no change there.

### Expected Behavior
If we tooltip the actions in the section „Visits in real time“ different pages are shown (as expected, as the user here starts at the „Landing page“ and proceeds with the page „News“ in this case).

<img width="475" alt="Real Time Logs" src="https://user-images.githubusercontent.com/33025565/220861102-85a62bbf-e2ae-49b4-9960-2935ac0faaa3.png">
(I removed the name of our app from the pictures, just to comply with our organization policy)

### Current Behavior
However, if we take a look at the visitor profile the information for tracked page titles gets lost. Instead each page is called like the page the user visited first.

<img width="380" alt="Visitor Profile" src="https://user-images.githubusercontent.com/33025565/220861567-b69751d9-7bf2-46e6-aa0e-cbf67c438ca5.png">

### Steps to Reproduce (for Bugs)
Go to a visitor profile, all listed page titles are named as the first page visited

**Comment by sgiehl** [comment]
Hi @annamaureder 
Thanks for creating this report. I was able to reproduce that locally and will check if I can provide a fix for that.
If it's easy to fix, this will likely by fixed with the next release. Otherwise we might need to push it to our prioritization queue and see when we will find some time to work on it.
Cheers,
