### ISSUE TITLE
Fatal error: Unsupported operand types: null + array in API/RowEvolution.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20399]
On PHP 8 + latest Matomo.

> Error: {"message":"Unsupported operand types: null + array","file":"\/plugins\/API\/RowEvolution.php","line":440,"request_id":"801ef","backtrace":" on \/plugins\/API\/RowEvolution.php(440)\n#0 \/plugins\/API\/RowEvolution.php(61): Piwik\\Plugins\\API\\RowEvolution->getRowEvolutionMetaData(2, 'day', '2023-01-03,2023...', 'FormAnalytics', 'getFieldSize', false, Array)\n#1 \/plugins\/API\/API.php(443): Piwik\\Plugins\\API\\RowEvolution->getRowEvolution(2, 'day', '2023-01-03,2023...', 'FormAnalytics', 'getFieldSize', '@scq_descriptio...', false, false, false, Array, true, true, false, false)\n#2 [internal function]: Piwik\\Plugins\\API\\API->getRowEvolution(2, 'range', '2023-01-03,2023...', 'FormAnalytics', 'getFieldSize', '@scq_descriptio...', false, false, false, false, true, true, false, false, false)\n#3 \/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#4 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#5 \/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#6 \/core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getRowEvolution', Array)\n#7 \/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(216): Piwik\\API\\Request->process()\n#8 \/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(124): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->loadEvolutionReport()\n#9 \/plugins\/CoreHome\/Controller.php(260): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->__construct(2, NULL, NULL)\n#10 \/plugins\/CoreHome\/Controller.php(226): Piwik\\Plugins\\CoreHome\\Controller->makeRowEvolution(false)\n#11 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->getRowEvolutionPopover()\n#12 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#13 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('CoreHome', 'getRowEvolution...', Array)\n#14 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#15 \/index.php(25): require_once('\/c...')\n#16 {main}"

**Comment by tsteur** [comment]
Here is the related URL

URL: /index.php?date=2023-01-03,2023-02-24&apiMethod=FormAnalytics.getFieldSize&label=%40foo&disableLink=1&module=CoreHome&action=getRowEvolutionPopover&colors=%7B%22backgroundColor%22%3A%22%23ffffff%22%2C%22lineColor%22%3A%22%23162c4a%22%2C%22minPointColor%22%3A%22%23ff7f7f%22%2C%22maxPointColor%22%3A%22%2375bf7c%22%2C%22lastPointColor%22%3A%22%2355aaff%22%2C%22fillColor%22%3A%22%23ffffff%22%7D&idForm=65&idSite=2&period=range

Referrer: index.php?module=CoreHome&action=index&idSite=2&period=range&date=previous30

GET: {"date":"2023-01-03,2023-02-24","apiMethod":"FormAnalytics.getFieldSize","label":"@foo","disableLink":"1","module":"CoreHome","action":"getRowEvolutionPopover","colors":"{\"backgroundColor\":\"#ffffff\",\"lineColor\":\"#162c4a\",\"minPointColor\":\"#ff7f7f\",\"maxPointColor\":\"#75bf7c\",\"lastPointColor\":\"#55aaff\",\"fillColor\":\"#ffffff\"}","idForm":"65","idSite":"2","period":"range"}

**Comment by bx80** [comment]
Looks like a quick fix to make sure the metrics array isn't null, I've linked a PR.
