### ISSUE TITLE
PHP 8.2 deprecation warnings

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20402]
From https://github.com/matomo-org/matomo/issues/20236#issuecomment-1436067158
 - [ ] `WARNING: /plugins/DBStats/Reports/Base.php(43): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizationsWisualizations\HtmlTable \Config::Skeep_summary_row is deprecated - Matomo 4.13.3
WARNING: /plugins/CoreVisualizationsficiplotDataGenerator/Evolution.php(89): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizationsVqplotDataGenerator\Chart::SdataTable is deprecated - Matomo 4.13.3 (Module: DBStats, Action: index, In CLI mode: false)`

From https://forum.matomo.org/t/php-8-2-depreciated-features-on-ver-4-13-1/49221/5
- [ ] `WARNING: /plugins/Live/VisitorProfile.php(24): Deprecated - Creation of dynamic property Piwik\Plugins\Live\VisitorProfile::$idSite is deprecated - Matomo 4.13.1 (Module: API, Action: getVisitorProfilePopup, Method: Live.getVisitorProfile, In CLI mode: false)`
- [ ] `WARNING: /core/Tracker/TableLogAction/Cache.php(41): Deprecated - Creation of dynamic property Piwik\Tracker\TableLogAction\Cache::$limitActionIds is deprecated - Matomo 4.13.3
(Module: API, Action: getEvolutionGraph, Method: VisitsSummary.get, In CLI mode: false)`

From https://forum.matomo.org/t/logs-filled-with-deprecated-warnings-in-matomo-4-13-3-with-php-8-2-2/49799:
 - [ ] `Message: plugins/LogViewer/Log/Query.php(15): Deprecated - Creation of dynamic property Piwik\Plugins\LogViewer\Log\Query::$query is deprecated - Matomo 4.13.3`

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/php-8-2-depreciated-features-on-ver-4-13-1/49221/8

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/logs-filled-with-deprecated-warnings-in-matomo-4-13-3-with-php-8-2-2/49799/2
