### ISSUE TITLE
Add `referrerpolicy="no-referrer-when-downgrade"` to noscript tracking code

### ISSUE THREAD

**Issue by pbb72** [piwik/piwik#20409]
#16237 (Jul 23, 2020) added the `referrerpolicy="no-referrer-when-downgrade"` attribute to the Image Tracking code, but the JavaScript Tracking code for users with JavaScript disabled, which uses the exact same `<img>` tag, was forgotten. Please add the `referrerpolicy` attribute there also.

![image](https://user-images.githubusercontent.com/1436366/222144608-b38c3e29-1d25-4db6-a614-46ade81bc041.png)

**Comment by pbb72** [comment]
Actually, as an alternative it might be a better solution to altogether remove the "Track users with JavaScript disabled" option, and replace it with a clear note that Image Tracking can be used in addition to JavaScript tracking.

**Comment by bx80** [comment]
Thanks for highlighting this @pbb72, I've linked a PR which adds the referrer policy to the noscript image tag. 

Removing the "Track users with JavaScript disabled" in favor of a note about image tracking might be something we can look at when there is next a design refresh of this page :+1:
