### ISSUE TITLE
Dates returned by API for Report Invalidation is incomplete

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#20401]
When using the API endpoint to invalidate reports: `CoreAdminHome.invalidateArchived`
And invalidating for any period other than `range` returns incomplete dates for confirmation of invalidated periods.

For example, when using `period=week&dates=20223-01-01,2023-02-24` the following response is returned:
```
<result>
<row>
Success. The following dates were invalidated successfully: 2023-02-24
</row>
</result>
```

When using a `dates` value such as `lastN` or `previousN` returns no dates. For example when using `&dates=last2` the following response is returned:
```
<result>
<row>
Success. The following dates were invalidated successfully:
</row>
</result>
```

**Comment by bx80** [comment]
Invalid dates were not being shown in the output and lastN / previousN dates were failing validation. These issues should be fixed in the linked PR.
