### ISSUE TITLE
Error Call to undefined method Piwik\Piwik::doesUserRequirePasswordConfirmation() for task

### ISSUE THREAD

**Issue by WhilelM** [piwik/piwik#20405]
Got this error from cron execution.

> Subject: Cron <www-data@XXXXX> [ -e /usr/share/matomo/console ] && [ -x /usr/bin/php ] && nice /usr/bin/php /usr/share/matomo/console core:archive --url="https://XXXXX.info/analytics" >>/var/log/matomo/matomo-archive.log                                               
> 
> ERROR [2023-02-28 22:38:54] 3937061  Scheduler: Error Call to undefined method Piwik\Piwik::doesUserRequirePasswordConfirmation() for task 'Piwik\Plugins\ScheduledReports\API.sendReport_2'

Log extract:

> INFO [2023-02-28 22:38:35] 3937061  SCHEDULED TASKS
> INFO [2023-02-28 22:38:35] 3937061  Starting Scheduled tasks... 
> INFO [2023-02-28 22:38:35] 3937061  Scheduler: executing task Piwik\Plugins\CoreAdminHome\Tasks.invalidateOutdatedArchives...
> INFO [2023-02-28 22:38:35] 3937061  Browser triggered archiving disabled, archives will be invalidated during core:archive.
> INFO [2023-02-28 22:38:35] 3937061  Scheduler: finished. Time elapsed: 0.000s
> INFO [2023-02-28 22:38:35] 3937061  Scheduler: executing task Piwik\Plugins\CoreAdminHome\Tasks.deleteOldFingerprintSalts...
> INFO [2023-02-28 22:38:35] 3937061  Scheduler: finished. Time elapsed: 0.097s
> INFO [2023-02-28 22:38:35] 3937061  Scheduler: executing task Piwik\Plugins\CoreAdminHome\Tasks.purgeOutdatedArchives...
> INFO [2023-02-28 22:38:35] 3937061  Purging archives in 298 archive tables.
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 19.009s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\Login\Tasks.cleanupBruteForceLogs...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.019s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\TwoFactorAuth\Tasks.cleanupTwoFaCodesUsedRecently...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.001s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\UsersManager\Tasks.cleanupExpiredTokens...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.001s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\UsersManager\Tasks.setUserDefaultReportPreference...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.026s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\UsersManager\Tasks.cleanUpExpiredInvites...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.001s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\ScheduledReports\API.sendReport_2...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.422s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: 'Piwik\Plugins\ScheduledReports\API.sendReport_2' retry scheduled for 2023-02-28
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\CustomJsTracker\Tasks.updateTracker...
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: finished. Time elapsed: 0.002s
> INFO [2023-02-28 22:38:54] 3937061  Scheduler: executing task Piwik\Plugins\CoreAdminHome\Tasks.purgeInvalidatedArchives...
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: finished. Time elapsed: 1.422s
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: executing task Piwik\Plugins\CoreAdminHome\Tasks.purgeInvalidationsForDeletedSites...
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: finished. Time elapsed: 0.144s
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: executing task Piwik\Plugins\PrivacyManager\Tasks.deleteReportData...
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: finished. Time elapsed: 0.005s
> [...]
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: executing task Piwik\Plugins\Marketplace\Tasks.sendNotificationIfUpdatesAvailable...
> INFO [2023-02-28 22:38:56] 3937061  Scheduler: finished. Time elapsed: 0.192s
> INFO [2023-02-28 22:38:56] 3937061  done
> INFO [2023-02-28 22:38:56] 3937061  ---------------------------
> Error: error or warning logs detected, exit 1
> 

## Expected Behavior
Cron executed without error.

## Context
Just upgraded matomo debian package (Upgrade: matomo:amd64 (4.11.0-1, 4.13.3-1))

## Your Environment

* PHP Version: 7.4
* Server Operating System: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Comment by bx80** [comment]
Thanks for reporting this @WhilelM, the `doesUserRequirePasswordConfirmation()` method was added in Matomo 4.12. Are you seeing this error each time the cron executes or did it just happen once? This error could potentially happen if the cronjob executed during the upgrade and some of the 4.13 code was used with 4.11 classes.

**Comment by WhilelM** [comment]
You're right. it did just happen once and the cronjob was launched before the upgrade and ended after. Thanks for your reply. I assume it's ok so.

**Comment by sgiehl** [comment]
@WhilelM thanks for the feedback. I'll close the issue for now. If the problem occurs again, please report back to use, so we can reopen the issue and investigate this further if needed. Cheers
