### ISSUE TITLE
PHP8.2 Deprecated

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20426]
From https://forum.matomo.org/t/error-in-widgets-when-trying-to-create-reports-with-a-longer-time-range/49932
 - [x] `PHP Deprecated:  Creation of dynamic property Piwik\Plugins\Events\Actions\ActionEvent::$eventValue is deprecated in [webserver-www-file-location]/matomo/plugins/Events/Actions/ActionEvent.php on line 30` (Matomo 4.13.3, Nginx webserver, PHP 8.2, mysql DB)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-in-widgets-when-trying-to-create-reports-with-a-longer-time-range/49932/2

**Comment by waclaw66** [comment]
Still occurs in 4.14.2 running cron archive job...
```
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /mnt/data/www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /mnt/data/www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120
```

**Comment by sgiehl** [comment]
@waclaw66 this will be fixed with Matomo 5
