### ISSUE TITLE
Where does come from 90a5a511e1974bca37613b6daec137ba

### ISSUE THREAD

**Issue by valentin-ed** [piwik/piwik#20432]
# It's not a bug

Hi matomo team, i just wanted to understand better the Archive Process.

The things is that on matomo there is a "90a5a511e1974bca37613b6daec137ba" id/hash from the "archive_numeric*" table. I tried to lookup the hash from the segment table but none of them seems to come from this table.

Can you help me understand:

- What are those "hash" : `90a5a511e1974bca37613b6daec137ba` and `fea44bece172bc9696ae57c26888bf8a`
- What is the `donefea44bece172bc9696ae57c26888bf8a.VisitsSummary` from the archive_numeric* table.

Thank you !

**Comment by sgiehl** [comment]
Those might be a md5 over the segment definition. See https://github.com/matomo-org/matomo/blob/4.x-dev/core/Segment.php#L479 for details on how a segment is hashed.
