### ISSUE TITLE
invalidate report data for segment in development mode triggers a warning in some cases

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20440]
To reproduce have a segment with a definition: `pageUrl=@foo.com;pageUrl!@staging;pageUrl=@app;pageUrl!@cover`.

Then run `./console core:invalidate-report-data ...` to invalidate this segment.

This only happens when development mode is enabled.

Getting error:

> WARNING   [05:30:10] %extra.request_id%  Avoiding segment subquery due to missing start date and/or an end date. Please ensure a start date and/or end date is set when initializing a segment if it's used to build a query. Stacktrace:
> #0/core/Segment.php(435): Piwik\Segment->doesSegmentNeedSubquery('!@', 'pageUrl')
> #1 //core/Segment.php(275): Piwik\Segment->getCleanedExpression(Array)
> #2 /core/Segment.php(172): Piwik\Segment->initializeSegment('pageUrl=@foo.co...', Array)
> #3 /plugins/CoreAdminHome/Commands/InvalidateReportData.php(253): Piwik\Segment->__construct('pageUrl=@foo.co...', Array)
> > #4 plugins/CoreAdminHome/Commands/InvalidateReportData.php(84): Piwik\Plugins\CoreAdminHome\Commands\InvalidateReportData->getSegmentsToInvalidateFor(Object(Symfony\Component\Console\Input\ArgvInput), Array, Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by sgiehl** [comment]
Sure that the invalidation doesn't work nevertheless? Looking at the code this is "only" a warning that is logged in development mode.

**Comment by tsteur** [comment]
True 👍  Feel free to close it. After heaps of lines of warnings there's at the end actually a success message. It's a bit confusing/misleading but it works. 
<img width="344" alt="image" src="https://user-images.githubusercontent.com/273120/224112503-6f6e2995-017c-4939-bee5-f066740bbd4b.png">

**Comment by michalkleiner** [comment]
Closing the issue as this is an intentional behaviour when development mode is enabled.

Relevant previous issues/PRs: https://github.com/matomo-org/matomo/issues/16200 and https://github.com/matomo-org/matomo/pull/16512
