### ISSUE TITLE
Matomo strict transport security not enforced

### ISSUE THREAD

**Issue by sven47845** [piwik/piwik#20458]
According to headers the best practice to enable strict transport security is not enabled in the docker container.

## Context

sslstrip and other tools can be abused to attack Matomo

Strict-Transport-Security shall be enabled - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

Strict-Transport-Security shall be enabled - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

## Expected Behavior

Strict-Transport-Security shall be enabled by default - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

## Current Behavior

Strict-Transport-Security is not enabled.

## Possible Solution

Strict-Transport-Security shall be enabled - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

## Steps to Reproduce (for Bugs)

1. Inspect Response Headers from webserver
2.

## Your Environment

* Matomo Version: Matomo version 4.13.1
* PHP Version: PHP 8.1.14 (cli) (built: Jan 11 2023 07:53:46) (NTS)
* Server Operating System: RedHat 8
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by bx80** [comment]
Hi @sven47845, thanks for reporting this. Could you please recreate this issue in the [Matomo docker repository](https://github.com/matomo-org/docker/issues)? Issues here are limited to the core analytics platform only.
