### ISSUE TITLE
Matomo's config directory is publically accessible. How to deny access?

### ISSUE THREAD

**Issue by areeshaad** [piwik/piwik#20453]
Hi there, 
I am receiving the critical issue "Matomo's directory is publically accessible" under the system checks. I have searched a lot and implemented a few methods. But still not fixed. Here is the screenshot,

![image](https://user-images.githubusercontent.com/98154363/224466769-91b06af0-51aa-4b81-a584-033f9c688cd1.png)

I am using apache, and I have double checked everything. Everything seems to me okay but still system check fails. Have a look on my apache configuration file setup.
<VirtualHost *:80>
    ServerAdmin web@mydomain.com
    ServerName mydomain.com
    ServerAlias www.mydomain.com
    DocumentRoot /var/www/html/matomo
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    <IfModule !mod_php7.c>
        <IfModule proxy_fcgi_module>
        ProxyPass /config !
        <FilesMatch "^/(config|tmp|core|lang)$">
            Require all denied
        </FilesMatch>
        </IfModule>
    </IfModule>
<Directory /var/www/html/matomo>
        DirectoryIndex index.php
        Options FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
RewriteEngine on
RewriteCond %{SERVER_NAME} =www.my-domain.com [OR]
RewriteCond %{SERVER_NAME} =my-domain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

Directory path is correct , "AllowOverride All" is present in apache configuration and "Require all denied" is also implemented.
After reading similar-issues from matomo github and applying them didn't work for me. Please help me if I am still missing anything.
This issue needs to be fixed as quickly as possible. Thanks in Advance.

**Comment by bx80** [comment]
Hi @areeshaad, 

It looks like your VirtualHost config file is for *:80 / HTTP traffic and redirects to HTTPS, so the directory rules should be configured in the VirtualHost config for the HTTPS version of the site. Depending on the operating system you are using, this is often a separate file in the same directory, e.g. `/etc/apache2/sites-available/my-domain.conf` for HTTP and `/etc/apache2/sites-available/my-domain-ssl.conf` for HTTPS.

Hope that helps, if not you may be able to find more help on the [Matomo Forum](https://forum.matomo.org/)

**Comment by hafiz-naser** [comment]
> 

Thank you so much @bx80 , you were exactly right. I didn't think about that. However, It worked for me. Thanks!
