### ISSUE TITLE
Matomo allows clickjacking - missing X-Frame-Options header

### ISSUE THREAD

**Issue by sven47845** [piwik/piwik#20459]
The response of GET /matomo.php is frameable, which allows potential clickjacking.

## Context

Matomo does not add all best practice headers in responses. An attacker can be loaded by an attacker within an iframe, allowing overlay attacks.  This technique allows the attacker to circumvent defenses against cross-site request forgery, and may result in unauthorized actions.

https://portswigger.net/web-security/clickjacking

## Expected Behavior

Set the X-Frame-Options either to DENY or SAMEORIGIN.
## Current Behavior

The X-Frame-Options are not set.
## Possible Solution

Set the X-Frame-Options either to DENY or SAMEORIGIN.
## Steps to Reproduce (for Bugs)

1.GET /matomo.php HTTP/1.1
2. look at the headers returned

## Your Environment

* Matomo Version: Matomo version 4.13.1
* PHP Version: PHP 8.1.14 
* Server Operating System: RedHat 8
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by bx80** [comment]
Thanks for highlighting this issue @sven47845, we'll need to assess any potential impact this change may have on current usage. I've assigned this issue for prioritization. :+1:

**Comment by bx80** [comment]
Hi @sven47845 , after some discussion we've decided that this header cannot be sent by default as it will break image tracking functionality and our support for tracking within iframes. If a specific use case would benefit from adding the header then we'd recommend that the webserver be configured to send it. Thanks again for raising the issue, it's always good to re-examine options like this :+1:
