### ISSUE TITLE
Issue with Unique Visitors Quantity while Changing Report Period

### ISSUE THREAD

**Issue by ThorstenMichel** [piwik/piwik#20463]
We're using Matomo 4.14. Since last update there is an issue with unique visitors in email reports: in daily time range there are consistent values for unique visitors. If I change report period to weekly, monthly, yearly, or free range, the sum of unique visitors value is always zero.

## Context
We collect data of a few websites and want to use automatic email reports to inform the website owners about their visitors and visits. After being informed about https://matomo.org/faq/how-to/faq_113/ we added missing lines in our config.ini.php
Unique visitors data in other report periods as days still stay zero.

## Expected Behavior
All metrics shall provide their data in reports, according to config.ini.php

## Current Behavior
Sum of unique visitors is zero, if I select weekly, monthly, yearly, or free range as report period. 
If I select daily report period, the unique visitor values are correct.

Daily:
![image](https://user-images.githubusercontent.com/126069069/225040007-42d70277-bff8-4912-8b1c-d236b6255493.png)

Weekly:
![image](https://user-images.githubusercontent.com/126069069/225040273-1bb689c3-03e2-439f-a70f-e6bd00947aab.png)

## Steps to Reproduce (for Bugs)
- Adapt/add lines in config.ini.php
- Create custom report with metric "Unique visitor"
- Create email report that contains custom report, report period = month
- Collect data
- Download report

## Your Environment

* Matomo Version: 4.14.1
* PHP Version: 7.4.30
* Server Operating System: Debian 11
* Additionally installed plugins: Custom Reports

**Comment by bx80** [comment]
Hi @ThorstenMichel, thanks for reporting this. 

The 'unique visitors' metric requires additional configuration as described in [this guide](https://matomo.org/faq/how-to/faq_113/), can you check that these settings are correctly configured for periods other than 'day'?

On which previous Matomo version did this report work correctly for you?

**Comment by ThorstenMichel** [comment]
Thank you @bx80 , that was a good hint (unfortunately Matomo support didn't mentioned that but asked me to create a bug ticket).
I cannot verify if the lines containing "enable_processing_$range" were present  in our config in the past.
At least they were currently missing and we have now added them.
I will check if that solves our issue.

**Comment by ThorstenMichel** [comment]
@bx80 Sorry, but this approach is not working. 
The _unique_visitors_ still counts zero in all created custom reports except one reports based on evolution data. What's even worse: For testing purposes I changed in some email reports _unique_visitors_ to _visits_, but I'm just getting data of last day instead of chosen time period month.

It's disappointing because we're using the premium plugin Custom Reports to provide data to customer. But it is not possible to automatically provide the necessary data, although we know that they are contained in the database.

**Comment by ThorstenMichel** [comment]
FYI: Still no change in our reports though we adapted config.ini.php. I updated ticket.
Maybe it would be helpful to provide some trigger in Matomo administration board to enable time periods.

**Comment by bx80** [comment]
Apologies for for the delay in getting back to you @ThorstenMichel. Unfortunately it seems that the unique visitors metric is currently not supported in custom reports for periods other than a single day. There is a forum post discussing this [here](https://forum.matomo.org/t/no-sum-unique-users-in-custom-reports/37764). The documentation is not as clear as it should be on this limitation.

This repository is only for issues relating to the core open source Matomo application so it doesn't cover premium plugin enhancements, but we do have an internal ticket tracking this problem. I've added a link to this github issue and mentioned your understandable disappointment with the current functionality.

I'll close this issue here, sorry I couldn't be more of help.
