### ISSUE TITLE
Improved onboarding flow

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#20466]
Problem: When trying to set up Matomo for the first time, the majority of our users are not able to find or follow the right information and feel that it is not simple or easy to do so. This is a problem because these users find themselves lost without guidance and are not able to succeed with their Matomo journey.

Solution: We're looking at a large set of improvements. One of them is improving the onboarding flow, particularly to:
1. Design the onboarding experience in line with widely adopted modern software solutions
2. Enable us to track where users have trouble (so we can better target improvements in the future)
3. Enable us to understand who our users are (so we can better understand who has trouble at what stage)

Acceptance criteria:
Design:
1. New design implemented (screenshots attached, illustrations: TBD)
2. Slides with personal questions: not shown for on-premise product
3. None of the slides are shown in the Wordpress plugin (which immediately starts tracking and thus skips this stage)

Measuring:
1. Only measure on Cloud
2. Measure how many people landed on each slide
3. Measure how many of each option (role / goal) were saved
4. Measure how many people clicked on the Start Tracking Data button
5. Measure how many people clicked on the View Demo button (separately for Let’s Get Started screen and Start Tracking Data screen)

Screenshots: https://github.com/matomo-org/matomo/issues/20466#issuecomment-1571388372
(high resolution images and updated copy available internally in Jira)

**Comment by sgiehl** [comment]
@Stan-vw The setup process for on-premise is actually completely different to the one on cloud. To me it looks like the above screenshots are meant to improve the cloud process only. This needs to be fully implemented by the cloud team, as this is not part of the core.

**Comment by Javi-Ormaechea** [comment]
### Updated solution

**Screen 00 - Create Password**
Not to be shown in On-Premise and WordPress plugin

_Desktop_
![pre-onboarding-password](https://github.com/matomo-org/matomo/assets/109315616/5be65b52-6b44-4c7f-b512-6b1015a9fabd)

_Mobile_
![mobile-pre-onboarding-password](https://github.com/matomo-org/matomo/assets/109315616/865629c4-80d3-4fd4-9cb3-2c5e9aac1763)

**Screen 01 - Welcome to Matomo**
On-Premise and Cloud

_Desktop_
![onboarding-welcome](https://github.com/matomo-org/matomo/assets/109315616/0e6c11c7-bedc-4fb3-af06-8ffd131754e1)

_Mobile_
![mobile-onboarding-welcome](https://github.com/matomo-org/matomo/assets/109315616/da20b62b-fd02-41a8-9324-61be70eb68fd)

**Screen 02 - Role**
Not to be shown on On-Premise

_Desktop_
![onboarding-role](https://github.com/matomo-org/matomo/assets/109315616/38a7b427-be1d-4cb8-bd8c-0965dad4fa29)

_Mobile_
![mobile-onboarding-role](https://github.com/matomo-org/matomo/assets/109315616/8352f364-1905-4799-a2b8-67ece01e8a52)

**Screen 03 - Goal**
Not to be shown on On-Premise

_Desktop_
![onboarding-goal](https://github.com/matomo-org/matomo/assets/109315616/5d445c4c-e36e-4bdf-af9c-f62b5e22e9d0)

_Mobile_
![mobile-onboarding-goal](https://github.com/matomo-org/matomo/assets/109315616/7b49add3-e00e-44b5-b41e-4fe5ad5cdfe5)

**Screen 04 - Get Started**
No step tracker for On-Premise

_Desktop_
![onboarding-get-started](https://github.com/matomo-org/matomo/assets/109315616/43efdb98-d1d2-4ef2-ad5c-74ac5d9a7f07)

_Mobile_
![mobile-onboarding-get-started](https://github.com/matomo-org/matomo/assets/109315616/ae49ada5-eda3-49a0-82a0-58e4e98bf9e2)

**Comment by Stan-vw** [comment]
> **Screen 00 - Create Password**
> Not to be shown in On-Premise and WordPress plugin

Password update screen: actually is shown on on-premise, just not relevant for the first user (it is relevant for every invited user after that)

**Comment by Stan-vw** [comment]
Closing as this has been implemented.
