### ISSUE TITLE
segmented page-report contains pages which do not match the segment-criterias (regression for 4.12.2 compared to 3.9.1)

### ISSUE THREAD

**Issue by christophs78** [piwik/piwik#20461]
## Context
Each of our pages contains 4 custom matomo variables we use for segmentation. 
```
_paq.push(["setCustomVariable", 1, "Ebene1", 'Personalvertretung', "page"]);
_paq.push(["setCustomVariable", 2, "Ebene2 ", '\u00dcber uns', "page"]);
_paq.push(["setCustomVariable", 3, "Ebene3 ", 'Jugendausschuss', "page"]);
_paq.push(["setCustomVariable", 4, "Ebene4 ", 'Ausschussmitglieder', "page"]);
```
Segment-definition:
![image](https://user-images.githubusercontent.com/10461942/225002998-dd8630f1-e179-4c89-b0a6-c418be72270c.png)
(Side-note: It´s hard to tell the name of the variable afterwards. Especially regarding page or visit - scope of custom variables.)

Resulting data:
![image](https://user-images.githubusercontent.com/10461942/225008829-f6a07435-b0f1-400b-96e6-ea741b9b95bc.png)

## Expected Behavior
Only pages according to the segment-definition should be shown.
(We currently use 4.12.3, before we had 3.9.1 which did not had this issue. When we switch back to segmented data from january which had been calculated by the 3.9.1-release we don´t see this issue.)

## Current Behavior
Pages which are not part of the segment are shown  as resulting pages.

Free interpretation - maybe other page which are part of a vistit which contains pages of the segment are also counted as part of the segment.
Screenshot from clicking the test-button of the segment:
![image](https://user-images.githubusercontent.com/10461942/225011167-4125a539-9953-4562-a9df-263685348dc6.png)

## Your Environment

* Matomo Version: 4.12.3
* PHP Version: 8.1.14
* Server Operating System: CentOS

**Comment by sgiehl** [comment]
Hi @christophs78 
In Matomo 4 the way how segments on action dimension work has been fixed. 
Segments are meant to kind of filter for certain visits. So when using an segment for an action scope it will look for all visits that had a certain action. But it will no longer filter away all actions that don't match the segment.
So the new behavior is actually the correct one.

You can find more details (including a way how to preserve the old behavior) in https://github.com/matomo-org/matomo/issues/15438
