### ISSUE TITLE
Include new database table column needed in 5.X already in 4.X for easier upgrade

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20470]
see https://github.com/matomo-org/matomo/issues/20375#issuecomment-1437635363

## Context
In Matomo 5.0 we will be adding a new DB column to improve the performance of a query see https://github.com/matomo-org/matomo/issues/20375

## Possible Solution
We should already add this column for all new 4.X installs so that people who install On-Premise now or sign up on the Cloud won't need to have this DB upgrade executed. This will prevent many thousands of installs from not needing big DB migrations when upgrading to Matomo 5 and will save us a lot of effort on the Cloud and possible problems.

We would only need to have the new column in the schema so it's there for new installs. Nothing else would need to be done. We wouldn't actually need to track any data yet.

**Comment by sgiehl** [comment]
@bx80 could you maybe provide a simple PR for this one? It would be only adding the column to the schema for now here: https://github.com/matomo-org/matomo/blob/4.x-dev/core/Db/Schema/Mysql.php#L226
I'm not sure what exactly that column should hold, so guess it's easier for you to find a good name for it.
The new columns name should then be also added to https://github.com/matomo-org/matomo/issues/20375
