### ISSUE TITLE
Create & place a cloudflare installation guide

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#20477]
**Problem:** We have [a cloudflare app](https://matomo.org/blog/2017/11/piwik-now-integrated-within-cloudflare/) but we're currently not helping the users of the app to easily add data tracking to their Matomo instance

**Solution:** A few identified steps to solve the problem:
1. Create an Installation Guide / FAQ on how to start tracking data when you're using the cloudflare app
2. Check if we can detect if a website is using cloudflare
3. If a website is using cloudflare: the No Data Screen could be optimised for it (simple fix: add cloudflare to Installation Guides, perhaps later we can optimise further)
4. Add the link to cloudflare installation guide in the Tracking Code page (in the configuration settings)

**Comment by mattab** [comment]
Closing as this was implemented in https://github.com/matomo-org/matomo/pull/20566 in 4.x and also in 5.x :+1:
