### ISSUE TITLE
Fix inconsistencies across dropdown elements

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#20475]
Context: Through community feedback we've heard that the UI of Matomo has room for improvement. We are therefore looking at improvements (small and large) that can have an impact on making the platform easier to use, particularly for new users who are struggling the most.

Problem: Dropdown elements have visual inconsistencies, leading to an unnecessarily difficult UX 

Proposed solution:
- move icons on dropdowns to after the text
- make the icons consistent (e.g. the standard v icon pointing downwards when folded in, and pointing up when folding out)
- check that these controllers are consistent  in the whole codebase (core + plugins)

Current
![image](https://user-images.githubusercontent.com/52564377/225459921-fd8cfd34-51c4-4922-b79d-a32c59d5dcf8.png)

New proposal
![image](https://user-images.githubusercontent.com/52564377/225459952-5e0798ca-b1ec-4b14-946e-530395a649fa.png)

**Comment by sgiehl** [comment]
@Stan-vw We actually used to have the icons on the other side, but at some point decided to move them. I can't remember the reason. Maybe @tsteur or @mattab can...

**Comment by heurteph-ei** [comment]
The segments dropdown list also doesn't display the **v** icon, some beginner users could think this is not a dropdown list, but a button...

**Comment by tsteur** [comment]
@sgiehl that was originally moved to the left in https://github.com/matomo-org/matomo/issues/12301

**Comment by Stan-vw** [comment]
Thanks for linking https://github.com/matomo-org/matomo/issues/12301 @tsteur. That ticket actually talks about buttons albeit not explicitly named like that (all examples are buttons), and it's indeed more standard practice to have icons on the left of a button (e.g. "+ Add file", and "X Close"). 
However, in my experience the standard design for dropdowns is to have the "v" on the right.

**Comment by Stan-vw** [comment]
See the attached for an interesting example, the icon for the "button action" is on the left and icon for the the "dropdown action" is on the right, even though it's on the same element.
![Screen Shot 2023-03-17 at 9 43 20 AM](https://user-images.githubusercontent.com/52564377/225748129-f71f4b42-cf86-4814-a14a-85602ab300b7.png)

**Comment by Javi-Ormaechea** [comment]
Like @Stan-vw said, the dropdown icon is commonly found placed to the right of the label in a button. Also, placing it on the right would be consistent with the rest of the dropdowns we currently have on the dashboard.

![dropdown-icon](https://user-images.githubusercontent.com/109315616/225783876-3d1818c6-7773-4c0f-9288-d15b7bb6e8f3.png)
