### ISSUE TITLE
Segment does not filter urls properly

### ISSUE THREAD

**Issue by Greg-ecedi** [piwik/piwik#20486]
Hi 

I added a segment like this : Url of a page > that content > xxxxxxxx
Meanwhile some of the urls in the report are not containing the xxxxxxxx.
It is a big issue because i need to filter data for our clients.

Sincerely

**Comment by bx80** [comment]
Hi @Greg-ecedi, thanks for reaching out. Would it be possible to provide a screenshot of the segment definition?

**Comment by Greg-ecedi** [comment]
Dear @bx80, 
Sorry when we are on the filter all our screenshot addon do not manage to produce a screenshot as the segment box disapear. Well here is the exact filter : 

**On the menu :** Comportement > Pages 
**Segment :** URL de la page >Commence par > https://www.xxxx.fr/espace-prive/

On the report i have urls like https://www.xxxx.fr/structures ???

**Comment by sgiehl** [comment]
This is actually expected behaviour. Segments are not mean to work like filters for actions ()even though they worked like for older Matomo versions). If you e.g. create a segment for matching a certain page url, the segment will include all visits, that contain an action with that page url. But those visits will also include all their other actions they had. 
For more information please check this issue: https://github.com/matomo-org/matomo/issues/15438

**Comment by Greg-ecedi** [comment]
Ok so how should i do to get only data from urls with a certain pattern ?

**Comment by sgiehl** [comment]
Depends what you are trying to achieve. In the UI there should be the possibility to search in reports. This should allow you to show the pages report filtered for a certain URL. But it is currently not possible to filter other reports like the visits log for certain URLs.

**Comment by Greg-ecedi** [comment]
Great, meanwhile i like to create a segment in order to extract data that will be displayed. If the data is mixing urls there is not use. I have to display the top 5 visited folders (categories) of a site. It is impossible because i created a segment with all folder names and then asked to display the data with a "Le rapport est hiérarchique" in order to have only the different folder in the report and guess what i have plenty of urls... Very hard to work then the segment then.

**Comment by heurteph-ei** [comment]
@Greg-ecedi 
For top urls prefixes, the hierarchical view of pages allows the display of top 5:
From [demo **Pages** report](https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=General_Actions&subcategory=General_Pages)
![image](https://user-images.githubusercontent.com/79993552/225923926-4383a4de-1698-4678-abf9-5d4ce2677022.png)

Also for filters behavior, you can use CustomReports premium plugin:
https://plugins.matomo.org/CustomReports
When designing the report:
![image](https://user-images.githubusercontent.com/79993552/225924406-aef60aed-39e7-496c-bf17-78d199819116.png)

**Comment by Greg-ecedi** [comment]
Thank you but the top 5 is currupt with urls that should not appear.

Question, i downloa the customer data into a spredsheet in order to make a data studio. My customer likes to have monthly report. I do not want to pass on all script to change the date of the export URLs every month. Thus, do you have in your export url a parameter to export only last month data (like dynamic) : 
like periode:month&date=lastmonth ?


function myFunction() {        
  var csvUrl = "https://matomo.xxxxxxl.fr/index.php?module=API&format=CSV&idSite=1&period=month&date=LASTMONTH&method=Actions.getOutlinks&flat=1&translateColumnNames=1&language=fr&segment=pageUrl%3D%5Ehttps%25253A%25252F%25252Fwww.XXXXX.fr%25252Fespace-prive%25252F&token_auth=XXXXXXXX&convertToUnicode=0";
  var csvContent = UrlFetchApp.fetch(csvUrl).getContentText();
  var csvData = Utilities.parseCsv(csvContent);
  var sheet = SpreadsheetApp.getActiveSheet();
  sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
}

**Comment by heurteph-ei** [comment]
@Greg-ecedi 
The GitHub is for feature requests or bug reports. For another question please use the Matomo forum:
https://forum.matomo.org/

For your question, you may use, instead of `LASTMONTH` the value of:
`var lastmonth = (new Date((new Date()).setMonth((new Date()).getMonth()-1))).toISOString().substring(0,10);`
