### ISSUE TITLE
Enable segmented log feature for social network reports

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20482]
Hi team,

If we hover our mouse on the social network row of the channel type report, we get the log segmented feature.
Though, if we open the sub-table and would like to get it for Facebook, for example, then the log segmented feature is not appearing.
Can we make it possible?

**Comment by bx80** [comment]
Thanks for the suggestion @Chardonneaur , sounds like a useful addition :+1: 

It could also be good to have the log segmentation option when viewing the Acquisitions > Social Networks report as a table too.

**Comment by sgiehl** [comment]
Sounds like a quite valuable improvement. I'll set up a quick PR, as it's quite easy to change that.
