### ISSUE TITLE
Delete annotation feature is not translatable

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20484]
Hi team,
When we hover the mouse on the bin of an annotation written and that we are in a language other than English, it shows the word "Delete" as a bubble.
I guess this translation key is not within weblate yet.

**Comment by Findus23** [comment]
It seems like here 
https://github.com/matomo-org/matomo/blob/184f0160b5d92b1c1f5bc3028e3d6a42ba3ded2c/plugins/Annotations/templates/_annotation.twig#L54-L56
it should be `title="{{ 'Annotations_ClickToDelete'|translate }}"` instead

**Comment by bx80** [comment]
Thanks @Findus23 :+1: 

I've put that fix in a PR and it will be in Matomo 5
