### ISSUE TITLE
Include the pie chart, bar graph etc visualization within the email report

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20483]
Hi team,

Currently, the email report feature includes only the data table and the graph report.
It would be nice to have an option when picking up the report, to mention if we want to export the image from the report as a bar graph, pie chart etc

**Comment by bx80** [comment]
Hi @Chardonneaur, would the suggestion to use a customized dashboard for email report in issue #19198 cover this?

**Comment by Chardonneaur** [comment]
Hi, positive, my fault, yes, my ticket seems to be a duplicate. Sorry.
