### ISSUE TITLE
[bug] A fatal error occurred on database stats page after upgrade from 4.13.3 to 4.14.0

### ISSUE THREAD

**Issue by MikkCZ** [piwik/piwik#20496]
## Steps to Reproduce (for Bugs)
1. Open Matomo.
2. Click the gear icon to go to Administration.
3. Under diagnostics select database stats.

## Expected Behavior
The stats page should load without error.

## Current Behavior
The page displays an error saying:

> A fatal error occurred
>  The following error just broke Matomo (v4.14.0): 
> `Undefined constant Piwik\Columns\Dimension::TYPE_UNKNOWN`
> `in /var/www/[hostname]/plugins/CoreHome/Columns/Metrics/CallableProcessedMetric.php line 21            `

## Your Environment
* Matomo Version: 4.14.0
* PHP Version: 8.1
* Server Operating System: Debian 11
* Additionally installed plugins:  LogViewer, GoogleAnalyticsImporter (inactive), Modern, TrackingSpamPrevention (inactive)

**Comment by MikkCZ** [comment]
Seems like the `Dimension::TYPE_UNKNOWN` was only introduced into `CallableProcessedMetric.php` in https://github.com/matomo-org/matomo/commit/eeb6e3b84f1340d10421e714231f22bbe75fe986 / #20493 today.

/cc @diosmosis @sgiehl

**Comment by mrwhizzy** [comment]
Just upgraded and getting HTTP 500 errors for such requests:

```
index.php?date=yesterday&module=API&format=json&method=API.getReportMetadata&filter_limit=-1&idSite=1&segment=&period=day
```

and get the following response:
```
{result: "error", message: "Undefined class constant 'SEMANTIC_TYPE_NUMBER'"}
```

--------

Also, as @MikkCZ mentioned, when visiting `Administration` -> `Diagnostic` -> `Database usage`, at:
```
index.php?module=DBStats&action=index&idSite=1&period=day&date=yesterday
```

I also get the following HTTP 500 error:

```
A fatal error occurred
The following error just broke Matomo (v4.14.0):

Undefined class constant 'SEMANTIC_TYPE_NUMBER'
in /var/www/matomo/plugins/Bandwidth/Columns/Metrics/HitsWithBandwidth.php line 34            
```

> **Note:**
> Disabling the `Bandwidth (v4.0.4)` plugin suppresses the error

------
### System info:

Matomo Version: 4.14.0
PHP Version: 7.4
Server Operating System: Debian 10

**Comment by sgiehl** [comment]
@AltamashShaikh we need to release a new version of the bandwidth plugin

**Comment by AltamashShaikh** [comment]
@all Released [4.0.5](https://github.com/matomo-org/plugin-Bandwidth/releases/tag/4.0.5) version of the Bandwidth plugin

**Comment by MikkCZ** [comment]
In my case, as the error message suggests, the issue is not in the Bandwidth plugin (not even installed), but directly in  CoreHome.

Here

https://github.com/matomo-org/matomo/blob/0df69694d6cd13280cfddb618756a5110eb214cb/plugins/CoreHome/Columns/Metrics/CallableProcessedMetric.php#L21

`Dimension::TYPE_UNKNOWN` is used, but if you look at the class

https://github.com/matomo-org/matomo/blob/0df69694d6cd13280cfddb618756a5110eb214cb/core/Columns/Dimension.php#L27-L52

there is truly no `TYPE_UNKNOWN`. Seems like you wanted to use `null` (based on the commit message, how `Metric::SEMANTIC_TYPE_UNKNOWN` was replaced in `core/Plugin/Report.php` and most importantly based on

https://github.com/matomo-org/matomo/blob/eeb6e3b84f1340d10421e714231f22bbe75fe986/plugins/CoreHome/Columns/Metrics/CallableProcessedMetric.php#L51-L54

which returns nullable string.

So the patch would be either to change the method signature to use `null` as the default argument, or defined `TYPE_UNKNOWN` inside the `Dimension` class with value of `null`.

**Comment by MikkCZ** [comment]
^ here is a proposal for the pach

**Comment by MikkCZ** [comment]
Updated to 4.14.1 and I cannot see the error anymore. Thanks for the quick release.
