### ISSUE TITLE
Remove "ALL WEBSITES" from the website selection dropdown

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#20492]
**Context:**
Modern BI & Analytics products typically allow users to view data for multiple sources in one place. Matomo currently offers this feature through the RollUp plugin, which requires creating a "new website" that combines all configured websites. This can be confusing and time-consuming for users who just want to view data for all websites, and are not familiar with the RollUp plugin.

**Problem:**
The current behaviour of the "ALL WEBSITES" option in the "select website" dropdown is not in line with leading data analytics user experience. Clicking on it navigates to the All Websites Dashboard page instead of showing data for all websites combined on the current page. This can lead to frustration for users who expect to see aggregated data.

**Suggested solution:**
1. This ticket: Remove the "ALL WEBSITES" option from the "select website" dropdown on all pages. Note that the All Websites Dashboard page will still be accessible through the button on the top right of the product.

2. Separately: Consider how we can improve the UX of the RollUp plugin to make it easier for users to view data for multiple / all websites combined. This could include adding a new option in the "select website" dropdown that selects all websites, or otherwise more tightly integrating the RollUp functionality into the main Matomo experience.

With these changes, we can provide a better user experience for Matomo users and make it easier for them to view and analyze data from multiple sources.

![image](https://user-images.githubusercontent.com/52564377/226219352-2c03afbb-0bab-427a-b072-76abfb91bc67.png)

**Comment by sgiehl** [comment]
@Stan-vw For possible changes around that, please always keep in mind, that the RollUp plugin is a premium feature. Most on premise installs might not have installed it. And in theory it could also be disabled for some cloud accounts. In general in core we can only provide hooks to adjust something in the UI. The required change might then needed to be triggered by the plugin.

**Comment by Stan-vw** [comment]
@sgiehl yes, UX changes for the RollUp plugin would most likely land with the plugin itself. Making any changes to that plugin is probably still pretty far away since we've got a decent backlog of higher priority design tickets.

For the removal of "ALL WEBSITES" in the website select dropdown we wouldn't need to change anything in the plugin, correct?
