### ISSUE TITLE
DataTable report not showing zero values

### ISSUE THREAD

**Issue by areeshaad** [piwik/piwik#20494]
Hi everyone,

I’m having a problem with my DataTable report not showing rows with zero values, even though I’ve added the datatable_reports_show_zero_values = 1 setting to my config/config.ini.php file. I’ve tried troubleshooting the issue using the following steps:

Verified that the setting is being applied correctly by going to the Matomo Administration > System > Diagnostic page and checking the datatable_reports_show_zero_values setting.
Checked the report configuration to make sure that the “Exclude low population” option is disabled.
Checked the segment to make sure that it’s not excluding rows with zero values.
Cleared the Matomo cache using the “Clear Cache” button on the Matomo Administration > System > General Settings page.
However, none of these steps have resolved the issue. I’m still not seeing rows with zero values in my DataTable report. Does anyone have any suggestions for how to troubleshoot this issue further?

![image](https://user-images.githubusercontent.com/98154363/226266259-f7fd17fe-e2b1-4d0a-8f96-6720f01d2d5e.png)

Thanks in advance for your help.

**Comment by sgiehl** [comment]
There is no configuration like `datatable_reports_show_zero_values`, at least none I'm aware of.
Zero values might always be treated as no value, causing a dash to be rendered instead. See https://github.com/matomo-org/matomo/blob/3f8a46ad966dfa727d4888f68e4380e84d91c0c6/plugins/CoreHome/templates/_dataTableCell.twig#L33-L36

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/datatable-report-not-showing-zero-values/50322/2
