### ISSUE TITLE
System Summary MySQL version and PHP version are swapped

### ISSUE THREAD

**Issue by skylarmt** [piwik/piwik#20498]
The PHP version actually shows the MySQL version, and vice versa, as shown in this screenshot on the main settings page:

![Screenshot 2023-03-20 at 21-44-26 General settings - Administration - Matomo](https://user-images.githubusercontent.com/6668965/226512878-72c0d37f-36df-4b84-8ad5-e55cb5f77788.png)

**Comment by sgiehl** [comment]
Hi @skylarmt 
Thanks for reporting. Seems to be a regression from #18679
Will provide a fix and push that in the upcoming patch release.
