### ISSUE TITLE
HTTP 508 error (Resource Limit is Reached)

### ISSUE THREAD

**Issue by claudix** [piwik/piwik#20500]
## Summary
My website provider is limiting the concurrent HTTP requests of a single session to 5. This makes Matomo fail during widget loading, for example, in the dashboard. As far as I have checked, the reason is that Matomo spawns multiple concurrent requests (to load graphics for example), and I find no way to reduce the number of these requests.

It would be great Matomo had a parameter that limited the number of concurrent requests or there could be a way to pipeline requests instead of spawning them in parallel.

## Your Environment
* Matomo Version: 4.14.0
* PHP Version: 
* Server Operating System:
* Additionally installed plugins:

**Comment by sgiehl** [comment]
Hi @claudix 
A limit of 5 sound quite low to me. How should a website work correct that uses multiple javascript files and images on a page. Those might be loaded in parallel 🤔 

It's currently not possible to limit the number of concurrent requests. You browser might already limit this to a certain amount, but maybe that number is higher than your server allows. 
As a workaround: It might be possible to configure the max connection per domain limit in your browser.

Our product team will consider this for a future improvement. 
But to be honest I doubt we will be able to work on this soon. There might be more important stuff right now, as we are working on a new major release.

**Comment by claudix** [comment]
I understand, it was only a suggestion :)
I was just reusing a spare website service from my provider I had from an old domain in order to host Matomo. Indeed, 5 concurrent connections is very low but this is what I currently have and, so far, I have no plans to host Matomo in another provider. I already tried configuring the max connection per domain limit in my browser but it seems it is completely ignored. I was wondering whether Matomo had a mechanism to pipeline requests or reduce the concurrency, but if it's not possible, I understand there are other more important stuff to work on.

Thx for your time!
