### ISSUE TITLE
Error with php 8.2

### ISSUE THREAD

**Issue by killerpapy** [piwik/piwik#20514]
Hello, 

I use the last public version of Matomo :  4.14.1

I have errors with the cron task.
`'PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /data/www/matosco/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52 PHP Deprecated:  Using ${var} in strings is deprecated, use {$var}
...
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /data/www/matosco/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120`

In all case, you need to replace ${width} by  {$width}.

Thanks.

**Comment by sgiehl** [comment]
Hi @killerpapy 
I'm sorry, but we are not able to fix this error within Matomo 4. The problem actually is located within Symfony Console, a dependency we are using. 
We are currently preparing our next major release (Matomo 5), where we will also update such dependencies. This will fix your reported problem. But it will take some time till our major release is finished. Till then I guess you have to ignore the message.
Thanks anyway for creating this report. It's always valuable for us to get feedback ❤️

**Comment by killerpapy** [comment]
Hello,

Ok thanks but i have error in my cron job. 
```
INFO [2023-03-24 08:33:41] 101203  'PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120
{"idarchives":[4993],"nb_visits":35}'
ERROR [2023-03-24 08:33:41] 101203  Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=19&period=day&date=2023-03-24&format=json&trigger=archivephp: 'PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52 PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120 {"idarchives":[4993],"nb_visits":35}'
INFO [2023-03-24 08:33:43] 101203  'PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120
{"idarchives":[4998],"nb_visits":105}'
ERROR [2023-03-24 08:33:43] 101203  Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=19&period=week&date=2023-03-20&format=json&trigger=archivephp: 'PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matomo/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 52 PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /www/matosco/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php on line 120 {"idarchives":[4998],"nb_visits":105}'
```

Due to this error, my "Last Successful Archive Run" in diagnostic page is not good...

I have change PHP log level : error_reporting = E_ALL ^ ( E_DEPRECATED | E_STRICT).

I stell have the error...

Can you help me so that the error does not go up without changing the source code?

**Comment by heurteph-ei** [comment]
Hi @sgiehl 
Is there any workaround for @killerpapy issue in CRON job running?

**Comment by sgiehl** [comment]
Maybe changing the log level in the Matomo config might help.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecated-warning-in-archiver-for-php8-2/52852/2

**Comment by dsagal** [comment]
@killerpapy , here is a way to silence the deprecation error. Edit the file `./core/bootstrap.php` in the Matomo installation. Comment out the line `error_reporting(E_ALL);` and add instead:
```
error_reporting(E_ALL & ~E_DEPRECATED);
```

My file looks like this now:
```
// Disable deprecation warnings, to silence output like
// "PHP Deprecated:  Using ${var} in strings is deprecated".
// error_reporting(E_ALL);
error_reporting(E_ALL & ~E_DEPRECATED);
```

The errors are gone, including the ones about "Error unserializing the following response".
