### ISSUE TITLE
Regions might not be detected correctly when using free DBIP geolocation database

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#20527]
## Context

When geolocation is enabled in Matomo, Matomo tries to detect and store the location of the visitor based on his IP.

Depending on the use location database, this may contain country, region and city details.

Countries and Regions are internally stored as iso codes.

Unlike most other databases the free DBIP location database does not include any region codes. Instead it only serves region names.
To be able to store the region details in that case, we try to look up the region code by it's name using a [list of all regions](https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/GeoIp2/data/isoRegionNames.php).

This currently fails as in some cases our list is not up to date in other cases the database returns the name in e.g. another language or writing.

As the free DBIP geolocation database is the suggested default database, we should improve that detection/mapping.

This problem has already been reported in various other issues like: https://github.com/matomo-org/matomo/issues/19359, https://github.com/matomo-org/matomo/issues/19329, https://github.com/matomo-org/matomo/issues/19411, https://github.com/matomo-org/matomo/issues/16714

## Expected Behavior

Regions should be detected correctly when using free DBIP location database

## Current Behavior

Regions are only partially or not detected at all for certain countries.

## Possible Solution

The detection of regions should be done a bit more fuzzy. In addition the list should also contain old names of regions, regions that have been removed from iso and maybe also some other names that are used by DBIP database.

A proposed solution can be found in https://github.com/matomo-org/matomo/pull/20420

@mattab @Stan-vw Might be good to prioritize this one into Matomo 5 as it might impact a lot on premise customers.
The proposed solution is almost finished. Might need a couple more hours to look it through again and maybe add some more tests.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/geolocation-real-time-map/49564/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/some-french-regions-are-not-defined/50483/3

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/probleme-de-geolocalisation-et-statistiques-absentes/53255/2
