### ISSUE TITLE
[Enhancement] Add a page group feature to Matomo Core

### ISSUE THREAD

**Issue by SW-Vincent** [piwik/piwik#20528]
Adding the possibility to define page groups within the UI would make it possible for matomo user to get better insights of their data at different scales.

## Summary

It is currently possible to define page groups through custom dimensions, therefore it has several flaws : 
- they are not retroactive as they are collected during the visit (even when defined through url extraction)
- url extraction doesn't support conversion table (only 1 extraction expression, which makes it hard to group by anything else than same level repository)
- they cannot be used within the transition report

Defining custom page group would also reduce the "Others" row limitation impact on page data insights.

This feature would require core update and cost additionnal server ressources as page groups would require to be aggregated. This implies business plan limitations for Cloud users (ex : 15 custom page groups per website).

Note : this feature is a core feature of some other analytics tools like Content Square

## Your Environment

* Matomo Version: Matomo Cloud

**Comment by bx80** [comment]
Hi @SW-Vincent, 

Thanks for the excellent feedback. I think this would be a very useful feature. :+1:

There is already a long standing issue #4576 which appears covers this functionality. So I'll close this issue as a duplicate and link it to the other issue.
