### ISSUE TITLE
idorder hashed although anonymization is switched off (E-Commerce tracking)

### ISSUE THREAD

**Issue by gadam-avocadostore** [piwik/piwik#20523]
Hello,

we have a problem with e-commerce tracking.

On our website all orders are tracked with calls like this:

_paq.push(['trackEcommerceOrder', subscription.id, amount, anotherAmount]);

For subscription.id we use a UUID like “88eb5e45-199f-4240-bbe4-8367479cf462”.

Anonymization of the order id is switched off in our Matomo instance (but IP anonymization is switched on).

So we expected that we find the UUID in the Matomo database in table “log_conversion” in field “idorder”
But instead “idorder” shows hashed value like “f1e9d51179f2503815e5d114e4a5a685”.

How to store the original UUID in “log_conversion”?

## Your Environment
* Matomo Version: 4.14.1
* PHP Version: 8
* Server Operating System: Linux

**Comment by sgiehl** [comment]
Hi @gadam-avocadostore 
Thanks for taking the time to create the report. I've tried to reproduce that, but actually wasn't able to.
So anonymizing the order id is disabled in the settings for you?
Could you maybe double check that by looking up the option record for this setting in the database:
`SELECT * from matomo_option WHERE option_name = 'PrivacyManager.anonymizeOrderId'`
(matomo_option might need to be changed depending on your use database prefix.)

The option_value should be `0` if it's disabled.

**Comment by gadam-avocadostore** [comment]
Hello!

Our option table shows these values for PrivacyManager:

| option_name | option_value | autoload |
| ------------- | ------------- | --------- |
| PrivacyManager.anonymizeOrderId | 0 | 0 |
| PrivacyManager.anonymizeReferrer |  | 0 |
| PrivacyManager.anonymizeUserId | 0 | 0 |
| PrivacyManager.doNotTrackEnabled | 1 | 0 |
| PrivacyManager.forceCookielessTracking | 1 | 0 |
| PrivacyManager.ipAddressMaskLength | 2 | 0 |
| PrivacyManager.ipAnonymizerEnabled | 1 | 0 |
| PrivacyManager.useAnonymizedIpForVisitEnrichment | 1 | 0 |

Thanks for you help

**Comment by gadam-avocadostore** [comment]
Hello!

We checked our logs and found this example:

<img width="2059" alt="Screenshot_orderid" src="https://user-images.githubusercontent.com/88833676/236193956-8b4d7842-9c7b-4591-ab24-8ee7870a707f.png">

The order in the screenshot produced two log-entries:

```
8...7 - - [03/May/2023:21:58:24 +0000] "POST /mtm/js/?idgoal=0&ec_id=17....1a-7..1-4..3-8..0-d..........7&revenue=138.28&ec_st=8.4&ec_tx=-0.0&ec_sh=undefined&ec_dt=undefined&ec_items=...&idsite=1&rec=1&r=802535&h=23&m=58&s=23&url=... HTTP/2.0" 204 0 "https://..." "Mozilla/..." 957 0.017 [...] [] 1...:8080 0 0.017 204
8...7 - - [03/May/2023:21:58:24 +0000] "POST /mtm/js/?e_c=Enhanced%20eCommerce&e_a=Purchase&e_n=17....1a-7..1-4..3-8..0-d..........7&e_v=138.28&ca=1&idsite=1&rec=1&r=252184&h=23&m=58&s=23&url=... HTTP/2.0" 204 0 "https://..." "Mozilla/..." 460 0.019 [...] [] 1...:8080 0 0.019 204
```

The first log entry is the ecommerce call.
The second is our custom event "Purchase".

The custom event and the log entries for ecommerce call and custom event show the same UUID "17....1a-7..1-4..3-8..0-d..........7"
This UUID is a based on a hash value, we create for logging.

But the order id (idorder) stored in "log_commerce" is "22c2c......................d1c61".
This is the same id, that is shown as visitor profile id in the screenshot.

So it looks like the visitor profile id is stored as "idorder", not the content of the "ec_id" parameter.

Greetings

**Comment by gadam-avocadostore** [comment]
Found it:
Our server uses a proxy that overwrote the order id.
Sorry for the false alarm

**Comment by michalkleiner** [comment]
Hi @gadam-avocadostore, nice investigative work! Thanks for letting us know this is not an issue anymore.
