### ISSUE TITLE
Dashboard is accessible without login

### ISSUE THREAD

**Issue by frankWeiershausen** [piwik/piwik#20534]
Hello,

I created an e-mail report. There I find a link where I can access my dashboard even though I am not logged in.
URL is like:
[my matomo domain]/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

I just wonder, is this a security issue? Everybody can access my dashboard over this URL. Or am I'm wrong?

Thanks
Frank

**Comment by sgiehl** [comment]
Hi @frankWeiershausen 
This should not be the case by default. But Matomo provides the possibility to give the `Anonymous` user view access. If this is done, anyone will be able to access your statistics.
Maybe check in the user permission managment if anonymous access to a certain site was granted. If you don't want to allow that, simply revoke the access.
