### ISSUE TITLE
Test button in segment editor might throw an error

### ISSUE THREAD

**Issue by tdrzewosz** [piwik/piwik#20532]
Hello, 

I can't test a segment. If I click the test button, I get this error

`Error: Action 'getLastVisitsDetails' not found in the module 'CoreHome'`

Can you help me, please? Thanks

**Comment by sgiehl** [comment]
Hi @tdrzewosz.
Does that fail on any page, or does this maybe only not work when you are currently on a specific reporting page?
If so might be good to past the url/hash here, so we are easier able to reproduce and fix the issue.
Thanks.

**Comment by tdrzewosz** [comment]
Hi, it does fail on any page. I click the "Test" Button and I get the error.

For example... /index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=5#?idSite=5&period=day&date=yesterday&category=General_Visitors&subcategory=General_RealTime

<img width="1172" alt="Bildschirmfoto 2023-03-30 um 12 01 09" src="https://user-images.githubusercontent.com/82414827/228801563-44d52181-77ab-4dd2-87a2-1e191e38ddc4.png">

**Comment by sgiehl** [comment]
Are you maybe able to look up the url that is requested after you click the test button in the browser console? There might be a problem with the method that generates the test url.

**Comment by tdrzewosz** [comment]
<img width="1454" alt="Bildschirmfoto 2023-03-30 um 13 17 15" src="https://user-images.githubusercontent.com/82414827/228820007-dd754b95-f2f3-42ad-ba0b-f4b4fb2096a5.png">

**Comment by sgiehl** [comment]
The method for generating this url, looks a bit weird to me. I've created a change here: https://github.com/matomo-org/matomo/compare/m20532
As I'm not able to reproduce your problem yet, I'm unable to say if it will fix it. If you are able to do it you can try to apply the changes in your installation to test if it works. After updating the file, it might be needed to clear the cache of Matomo as well as your browser cache.

**Comment by tdrzewosz** [comment]
It's working now. Thanks

**Comment by sgiehl** [comment]
Thanks for the feedback. I'll create a PR so this gets fixed for everyone in Matomo 5.
