### ISSUE TITLE
PHP 8.2.4 WARNING: Deprecated - Creation of dynamic property

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20545]
From https://forum.matomo.org/t/warning-please-report-this-message-in-the-matomo-forums/49590/8

 - [x] WARNING: /plugins/PagePerformance/JqplotDataGenerator/StackedBarEvolution.php(64): Deprecated - Creation of dynamic property Piwik\Plugins\PagePerformance\JqplotDataGenerator\Chart::$dataTable is deprecated - Matomo 4.14.1 (Module: PagePerformance, Action: getEvolutionGraph, In CLI mode: false)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-please-report-this-message-in-the-matomo-forums/49590/9

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecated-warning-messages-matomo-4-15-1-php-8-3-0/52760/2
