### ISSUE TITLE
[Enhancement] Add a preview screen capture to Heatmaps plugin

### ISSUE THREAD

**Issue by SW-Vincent** [piwik/piwik#20544]
When using the "url validator", adding a "take a test snapshot" button would make possible for Matomo user to anticipate some common issues with Heatmaps.

## Summary

There are a lot of common issues with Matomo Heatmaps that could be anticipated with a test snapshot : 
 - lazy loading
 - scroll-based animations/CSS
 - screen-size based CSS 
 - real url is different from custom url

![image](https://user-images.githubusercontent.com/118832007/229120916-b85e46e7-92ce-405c-a006-81d0325b1bc2.png)

It is an important point as when debbugging Heatmaps after launching them consumes Heatmap pageviews from the (limited) business plan of Matomo Cloud users.

## Your Environment

* Matomo Version: Cloud

**Comment by AltamashShaikh** [comment]
@SW-Vincent Thanks for creating the issue, but this repository belongs to Matomo core and Heatmap belongs to premium features, can you please create a support ticket for the same as that is the best way to report a bug or to ask for a new feature for Matomo premium plugins
