### ISSUE TITLE
[Bug/Enhancement] Incorrect behaviour of Heatmap /Session recordings for %vh-based html elements within coreHome IFrame

### ISSUE THREAD

**Issue by SW-Vincent** [piwik/piwik#20551]
When a HTML element has a size based on x% of the screen size, the size of the element will be stretched to x% of the snapshot instead of x% of the screen size.

Important : The same snapshot seems to be working within the HeatmapSessionRecording module but not the coreHome module. The Core module is accessed directly within the UI, while the HeatmapSessionRecording module is imported as an IFrame

## Context

This issue has been observed on several accounts, often for Single Page Applications CMS.
The current workaround consist in inserting [custom CSS for Heatmaps/Session recordings](https://fr.matomo.org/faq/heatmap-session-recording/faq_24426/) that would force the size of the element to a size in pixels (often arbitrarily). 

## Expected Behavior

Matomo Heatmap and Session Recordings module should handle properly %vh-based height elements.

## Possible Solution

I assume it is related to the snapshot Iframe having a "100vh" CSS property.

## Steps to Reproduce (for Bugs)

1. Having (or creating) a page containing an HTML element with a 0-100vh height CSS attribute (the easiest way to see the issue is to set a 100vh height CSS attribute)
2. Defining a Heatmap on this page

## Your Environment

* Matomo Version: Matomo Cloud

**Comment by AltamashShaikh** [comment]
@SW-Vincent Thanks for creating the issue, but this repository belongs to Matomo core and Heatmap belongs to premium features, can you please create a support ticket for the same as that is the best way to report a bug or to ask for a new feature for Matomo premium plugins
