### ISSUE TITLE
Search Engine Keywords - Admin access

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20561]
Customer emailed support and tried to access the 'Search Engine Keywords Performance' section while as an Admin user.
They were confused and thought perhaps the feature was broken/not working. **Admin > System > Search Performance**

When accessed as an Admin user, all that shows is:
![image](https://user-images.githubusercontent.com/118518962/229979837-1e16c727-6f54-4e75-9fba-76e1322d73ac.png)

Customers response "In my defense, and I'm sure it's not the first time you hear this, it genuinely looked broken to me. I would have expected at the very least a warning message like "you can't do this because you don't have superuser rights". Not to mention the fact that I've already configured keyword import for Bing, and I didn't need to be a superuser for that".

Can we perhaps get a warning message to display they need to be a 'super user' when accessing this option.

**Comment by AltamashShaikh** [comment]
@goochj03 This is a premium feature request, please create a PG ticket on JIRA.
