### ISSUE TITLE
[PHP 8.2 compatibility] WARNING: Deprecated - Creation of dynamic property

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20562]
From https://forum.matomo.org/t/warnings-rowevolution-please-report-this/50407
 - [ ] WARNING: /plugins/CoreHome/DataTableRowAction/RowEvolution.php(266): Deprecated - Creation of dynamic property Piwik\ViewDataTable\Config::$show_series_picker is deprecated - Matomo 4.14.1 (Module: CoreHome, Action: getRowEvolutionPopover, In CLI mode: false)
 - [ ] WARNING: /plugins/CoreHome/DataTableRowAction/RowEvolution.php(273): Deprecated - Creation of dynamic property Piwik\ViewDataTable\Config::$external_series_toggle is deprecated - Matomo 4.14.1 (Module: CoreHome, Action: getRowEvolutionPopover, In CLI mode: false)
 - [ ] WARNING: /plugins/CoreHome/DataTableRowAction/RowEvolution.php(274): Deprecated - Creation of dynamic property Piwik\ViewDataTable\Config::$external_series_toggle_show_all is deprecated - Matomo 4.14.1 (Module: CoreHome, Action: getRowEvolutionPopover, In CLI mode: false)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warnings-rowevolution-please-report-this/50407/4

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-plugins-corehome-datatablerowaction-rowevolution-php/52451/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecated-warning-messages-matomo-4-15-1-php-8-3-0/52760/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/php-8-2-x-problems-with-matomo-4-15-1/52971/2
