### ISSUE TITLE
How to change the name of a key in api data

### ISSUE THREAD

**Issue by areeshaad** [piwik/piwik#20571]
Hi there, 
I wanna change the name of key/column in api data. For example, in getLastVisitsDetails api dimensions named as dimension1, dimension2, dimension3... I want to replace this predefined names with their original custom names as in custom dimensions. Is there any default method? How can I do this? Thanks in advance for the time.

**Comment by sgiehl** [comment]
Hi @areeshaad.
There is currently no possibility to do something like this. Also it might be hard to make something like this possible.
Custom dimensions might e.g. have names that contain special characters that might be invalid for being used as xml tags.
Using custom names might also make it unreliable to work with API responses, as the name of those fields might change as soon as a dimension would be renamed.
If you need that for any purpose, you might need to implement a simply script yourself, that renames them accordingly in responses.
