### ISSUE TITLE
"Year" as a date range is broken and shows less data

### ISSUE THREAD

**Issue by konopkja** [piwik/piwik#20572]
## Context
When I select "March 2023" I see more hits than when I select "the year 2023" which does not make any sense. When I use date range instead, it works properly...

## Expected Behavior
More or equal numbers

## Current Behavior
see above

## Steps to Reproduce (for Bugs)
1. go to custom reports
2. select date range "year" and choose 2023
3. see error

## Your Environment
You are currently using Matomo 4.12.3.

* Browser: Chrome
* Operating System:
![Screenshot 2023-04-10 at 20 35 07](https://user-images.githubusercontent.com/100724231/230935179-2dcc6c4c-a4e8-4fee-bd3f-df7b70e410a6.png)
![Screenshot 2023-04-10 at 20 35 12](https://user-images.githubusercontent.com/100724231/230935190-0cf867aa-e7f2-4053-89f5-ae3919a8f796.png)

**Comment by bx80** [comment]
Hi @konopkja, thanks for reporting this. 

This could happen if the archived data for the year is not up to date after creating a custom report. Date ranges are calculated directly from the logs and do not use archived data, so it makes sense that they are not affected.

This should be resolved by invalidating and reprocessing the historic archived reported data as described in [this guide](https://matomo.org/faq/how-to/faq_155/)

Please feel free to reopen this ticket if you have any further issues.

**Comment by konopkja** [comment]
Hello @bx80 , tried two different methods based on the article and it did not help.

**Comment by sgiehl** [comment]
@konopkja did you check any errors occur while archiving? May it runs out of memory when archiving years?

**Comment by konopkja** [comment]
@pauljickling

**Comment by pauljickling** [comment]
No warnings or errors when running the invalidation command.

`./console core:invalidate-report-data --dates=2022-04-17,2023-04-17 --sites=<side_ids>`

```
INFO [2023-04-17 17:51:54] 28572  Invalidating day periods in 2022-04-17,2023-04-17 [segment = ]...
INFO [2023-04-17 17:55:34] 28572  Invalidating week periods in 2022-04-17,2023-04-17 [segment = ]...
INFO [2023-04-17 17:55:53] 28572  Invalidating month periods in 2022-04-17,2023-04-17 [segment = ]...
INFO [2023-04-17 17:56:00] 28572  Invalidating year periods in 2022-04-17,2023-04-17 [segment = ]...
```
