### ISSUE TITLE
Referrer icon misplaced in visits in real time widget

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20576]
See screenshot below.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/273120/231632665-ab72238c-147d-4e46-8036-7c3de860308e.png">

The facebook icon is misaligned.

Seems to work for Google?
<img width="368" alt="image" src="https://user-images.githubusercontent.com/273120/231632831-2a459cbc-f2ae-4cbd-a83f-232c4215ce31.png">

**Comment by sgiehl** [comment]
@tsteur I don't think this is a core issue. For social networks there is currently no icon shown.
Maybe the icon is added through AdvertisingCoversionExport plugin. It should track facebook click ids and might add icons for visitors coming with clickids. Guess the tooltip when hovering the icon might give a hint.

**Comment by tsteur** [comment]
Thanks for that. I'll recreate it there
