### ISSUE TITLE
How to send this raw data (visitorId, Screen size, revisit or not  etc)  to kafka ?

### ISSUE THREAD

**Issue by prk2331** [piwik/piwik#20574]
Hi team, 
Team, can you please guide me on how I can send the Matomo collected raw data to another platform for further processing? I saw that Matomo is sending this collected data to /matomo.php.

i am using Matomo 4.14.1 version

Thanks.

**Comment by prk2331** [comment]
Team , 
   I saw this one 
   https://plugins.matomo.org/KafkaPush?matomoversion=2
   But this Extension is too old, I dont think so it is going to support current version of Matomo
   
   Any alternative ?

**Comment by sgiehl** [comment]
No. I'm not aware of any newer version of this plugin or an alternative.
Maybe try to get in touch with the author or you might need to consider forking this plugin and making it compatible with latest Matomo releases yourself.

For further general questions please also consider asking them on our forum at https://forum.matomo.org instead. We are using GitHub issues only for bug reports and feature requests.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/in-matomo-can-we-push-custom-js-events-add-to-cart-view-etc-on-their-specific-kafka-topics-or-hadoop/48940/7
