### ISSUE TITLE
Fatal error: htmlspecialchars_decode(): Argument #1 ($string) must be of type string, array given in Common.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20590]
## Context
See below error details

> Error: {"message":"htmlspecialchars_decode(): Argument #1 ($string) must be of type string, array given","file":"core\/Common.php","line":422,"request_id":"3bc2b","backtrace":" on core\/Common.php(422)\n#0 core\/Common.php(422): htmlspecialchars_decode(Array, 3)\n#1 plugins\/Transitions\/API.php(165): Piwik\\Common::unsanitizeInputValue(Array)\n#2 plugins\/Transitions\/API.php(79): Piwik\\Plugins\\Transitions\\API->deriveIdAction(Array, 'url')\n#3 [internal function]: Piwik\\Plugins\\Transitions\\API->getTransitionsForAction(Array, 'url', '1', 'day', 'yesterday', false, 0, 'all')\n#4 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#5 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#6 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#7 core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getTransitionsF...', Array)\n#8 plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#9 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#10 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#11 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#12 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#13 index.php(25): require_once('c...')\n#14 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637)

> URL: /index.php?module=API&method=Transitions.getTransitionsForAction&actionType=url&actionName[]=https%3A%2F%2Fwww.matomo.org%2Fde%2Fbar%2Ffoo%2F&idSite=1&period=day&date=yesterday&format=JSON&token_auth=XYZANONYMIZED&force_api_session=1

> Referrer: None

> GET: {"module":"API","method":"Transitions.getTransitionsForAction","actionType":"url","actionName":["https:\/\/www.matomo.org\/de\/bar\/foo\/"],"idSite":"1","period":"day","date":"yesterday","format":"JSON","token_auth":"XYZANONYMIZED","force_api_session":"1","filter_limit":100}

## Expected Behavior
No fatal error

## Current Behavior
Fatal error occurs

## Your Environment
Latest Matomo version

**Comment by bx80** [comment]
Seems to be caused by the actionName parameter being passed as an array. I've added a quick fix PR
