### ISSUE TITLE
Add single click copy button for code snippets

### ISSUE THREAD

**Issue by michalkleiner** [piwik/piwik#20607]
## Summary
At the moment the code snippets (tracking code or tag manager code) get highlighted for copying and then the user needs to either use the keyboard or mouse to actually copy the snippet into the clipboard before it can be used.

This enhancement would add a single click copy button which would automatically copy the snippet into the clipboard. The current highlight all behaviour would be retained.

Example of the button within GitHub code snippets:
![Screenshot 2023-04-20 at 2 30 01 PM](https://user-images.githubusercontent.com/233342/233244013-9789b6b5-2e3e-4f5d-913a-027aa7452f7b.png)

**Comment by theVJagrawal** [comment]
hey @michalkleiner I am interested to work on this issue so could you please describe it more like which page are you talking about

**Comment by michalkleiner** [comment]
Hi @theVJagrawal,
it would involve all places where a snippet of code is displayed. It's currently handled by the `SelectOnFocus` Vue directive from Core. There are some components using it, such as `JsTrackingCodeGenerator` and `ImageTrackingCodeGenerator`. Those components would need to be adjusted as well. Building this in a universal and reusable way will be important.
