### ISSUE TITLE
Archiving error

### ISSUE THREAD

**Issue by SophieElle** [piwik/piwik#20602]
Hi,

the plugin doesn´t work. I git this message from the plugin:

* Error Letzter erfolgreicher Abschluss der Archivierung: error  (Die Archivierung ist zuletzt am Donnerstag, 23. Februar 2023 06:43:57 erfolgreich gelaufen, also vor 54 Tage 03:44:12 )
* Error MySQLi support: missing (Your PHP cli does not load the MySQLi extension. You might have archiving problems in Matomo but also others problems in your WordPress cron tasks. You should enable this extension)

I use the PHP-Version 8.1.17

Hope you can help?

Best regards
Sophie

**Comment by sgiehl** [comment]
Hi @SophieElle 
Sorry to hear you are having trouble with the archiving. Based on the error message it sounds like a server configuration problem. The php configuration for PHP on command line (cli) does not load the mysqli extension.
If you are not able to check of fix that yourself you might need to ask your server administrator.

For further support please consider asking your questions on our forum at https://forum.matomo.org
We are actually only handling bug reports and feature requests here on GitHub.
Cheers,
