### ISSUE TITLE
Multipe 'oops there is a problem...' on the dashboard

### ISSUE THREAD

**Issue by tbswork1** [piwik/piwik#20617]
On entering or refreshing dashboard it shows multiple red error 'Oops… there was a problem during the request. ' in the sub sections.

## Expected Behavior
Too many of them. 

## Current Behavior
Always show that errors. If manually press the refresh button of the section, it can shows the correct contents. 
Particularly, in the 'Visitor Overview' section, some graphs are always missing.

## Steps to Reproduce (for Bugs)
1. Login 
2. Or refresh

## Your Environment

* Matomo Version:
* PHP Version: 7.4.33
* Server Operating System: Debian
* Additionally installed plugins:

* Browser: Chrome
* Operating System: Windows 10

**Comment by michalkleiner** [comment]
Hi @tbswork1,

thank you for taking the time to raise the issue. There could be several possible reasons the message might come up. The most common cause is browser-triggered archiving.

Could you try setting up cron-triggered archiving and disable the browser triggered one by following this guide? https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

If you know how to check your PHP error logs, could you also check if there are any errors there?

**Comment by tbswork1** [comment]
it is on a shared hosting server and matomo is installed with softaculous. Just found the cpanel already has a cron job set up for matomo:

```
/opt/cpanel/ea-php74/root/usr/bin/php /home/xxxx/public_html/matomo/console core:archive --url=https://mydomain.com/matomo/ > /dev/null
```

**Comment by michalkleiner** [comment]
Any visible issues in the error logs?

**Comment by tbswork1** [comment]
@michalkleiner 
No. Some contents it fails to fetch have nothing to do with 'archiving', like 'Motomo.org blogs'. Again, when I press the refresh button it will show up.

**Comment by michalkleiner** [comment]
Thanks for confirming that, @tbswork1.

Are you able to inspect any of the XHR requests through your browser's console/network tab and see if there are any errors there? Do they produce 500 error or some other HTTP error that you could see?

Is it all widgets or the blog only or what other widgets?

What version of Matomo are you running? Any specific server config worth mentioning, e.g. being on a shared hosting, behind a proxy etc.?

**Comment by sgiehl** [comment]
As there haven't been any feedback in a couple of weeks I'll close this issue.
But we have done some improvements around this error message in #21303. So maybe this will be improved with Matomo 5
