### ISSUE TITLE
More then 20 actions bleed over from widgets

### ISSUE THREAD

**Issue by michalkleiner** [piwik/piwik#20622]
## Context
On a fresh Matomo 5.x install, when generating testing visits, some come up with more than approximately 20 actions.

## Expected Behavior
The icons are contained within the widget container and 

## Current Behavior
The action icons bleed out from the widget container.

## Possible Solution
Apply `flex-wrap: wrap` to `#visitsLive .settings` or remove `display: flex` from the same element.

## Steps to Reproduce (for Bugs)
On a fresh 5.0.0-b1 install generate fake visits with more than 20 actions/pages.
Couldn't reproduce this on the demo.matomo.cloud instance and checking there the container doesn't have the `display: flex` declaration, so this could be a regression.

## Your Environment

* Matomo Version: 5.0.0-b1
* PHP Version: 8.1.18
* Server Operating System: MacOS Ventura 13.3.1 (22E261)
* Additionally installed plugins: Visitor Generator
* Browser: Chrome Version 112.0.5615.137 (Official Build) (arm64)
* Operating System: MacOS Ventura 13.3.1 (22E261)

**Comment by michalkleiner** [comment]
Seems to have been introduced by https://github.com/matomo-org/matomo/pull/19418

**Comment by sgiehl** [comment]
@michalkleiner when creating such issues it would be helpful to add some screenshot how it currently looks.

**Comment by michalkleiner** [comment]
I actually happened to take a screenshot!
![Screenshot 2023-04-24 at 9 19 19 PM](https://user-images.githubusercontent.com/233342/237026873-7ed116f4-6b87-46e5-84e3-80e39dcf9c51.png)

**Comment by sgiehl** [comment]
That seems to be a regression indeed. We should though fix it before releasing Matomo 5.
