### ISSUE TITLE
[PHP 8.1 compatibility] deprecation warning — Return type of RequiredPhpSetting::jsonSerialize

### ISSUE THREAD

**Issue by michalkleiner** [piwik/piwik#20627]
WARNING: /plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php(104): Deprecated - Return type of Piwik\Plugins\Diagnostics\Diagnostic\RequiredPhpSetting::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice - Matomo 5.0.0-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/php-8-1-warning-deprecated-missing-return-type-for-requiredphpsetting-jsonserialize/50891/2

**Comment by michalkleiner** [comment]
Fixed by #20628
