### ISSUE TITLE
[PHP 8.1 compatibility] Fix array access warning on float - /plugins/Goals/DataTable/Filter/CalculateConversionPageRate.php

### ISSUE THREAD

**Issue by michalkleiner** [piwik/piwik#20636]
## Context
Coming back to view the dashboard after a day without any new visits, I see two PHP warnings.

## Expected Behavior
No warning displayed.

## Current Behavior
Two instances of the warning appear when no data/goals for the movers/shakers widget, one for `getPageTitles` action and one for `getPageUrls` action.

![Screenshot 2023-04-26 at 9 01 35 PM](https://user-images.githubusercontent.com/233342/234525761-083ff7b2-4cd2-4bb0-9574-541f476ab47a.png)

> WARNING: /plugins/Goals/DataTable/Filter/CalculateConversionPageRate.php(112): Warning - Trying to access array offset on value of type float - Matomo 5.0.0-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: API, Action: getOverallMoversAndShakers, Method: Actions.**getPageUrls**, In CLI mode: false)

> WARNING: /plugins/Goals/DataTable/Filter/CalculateConversionPageRate.php(112): Warning - Trying to access array offset on value of type float - Matomo 5.0.0-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: API, Action: getOverallMoversAndShakers, Method: Actions.**getPageTitles**, In CLI mode: false)

## Steps to Reproduce (for Bugs)
1. Establish a fresh Matomo instance
2. Use the Visits Generator to generate some visits
3. Wait a day (I realise this is not a super-feasible/fast reproduction step, sorry)
4. Observe the error in a fresh session (as it disappears on page refresh)

## Your Environment
* Matomo Version: 5.0.0-b1
* PHP Version: 8.1.18
* Server Operating System: MacOS
* Additionally installed plugins:
* Browser: Brave
* Operating System: MacOS

**Comment by michalkleiner** [comment]
This seems to be a regression caused by https://github.com/matomo-org/matomo/pull/20438 where we always assume there's a list returned from `$sum = $archive->getNumeric($names);` which is not the case here.

@tsteur since you worked on the change previously — do you think a check whether `$sum` is an array and only iterate the `$names` array then or do we need to specifically cater for the case when `$sum` is a valid number for a single goal?

**Comment by tsteur** [comment]
@michalkleiner I guess previously there was an is_numeric check when it's not an array so we may need to replicate that 👍 https://github.com/matomo-org/matomo/pull/20438/files#diff-d5a66fad2b3bee3d87d60b1adf5d098b7c69b9cc3d2866c2c4ddf36afbcddce4L105-L106

**Comment by michalkleiner** [comment]
PR https://github.com/matomo-org/matomo/pull/20638
