### ISSUE TITLE
Chart under acquisition - channel selection is forgotten

### ISSUE THREAD

**Issue by jr-ewing** [piwik/piwik#20635]
I found an error under Acquisition -> Overview when displaying the evolution chart.
Unfortunately, the error cannot be reproduced on the Matomo demo.
But I take care of some customers where the error occurs.
There are also 2 customers who use the Matomo cloud.

Here is my environment:
Matomo version: 4.14.2
MySQL version: 10.6.12-MariaDB-0ubuntu0.22.04.1
PHP version: 8.1.18

The Direct and Total channels are selected by default.
Additional channels can be selected using the small icon next to the legend.
If you select search engines here, for example, everything will be displayed correctly.

![image](https://user-images.githubusercontent.com/192153/234510400-e6fedac5-2c3f-47d0-9c53-86a76e7ceba1.png)

If you now select another channel, this will also be displayed correctly for the time being.

![image](https://user-images.githubusercontent.com/192153/234510591-52a4c1a5-3519-47cb-8444-f1b73087e2d1.png)

But if you press F5 afterwards, no more numbers will be played for the new line.
When you go to the drop down menu he seems to have forgotten the channel too.
He is still in the legend.

![image](https://user-images.githubusercontent.com/192153/234510763-0043e910-9560-4287-ac0c-fd2c4ae46630.png)

The checkbox is not selected anymore. 

![image](https://user-images.githubusercontent.com/192153/234511155-bd1cccff-d312-4350-8749-a4aef188cb58.png)

If you now go to another statistic and come back, there are no values ​​either.
It remembers the settings, which is of course ideal.
The Matomo demo always jumps back to the initial standard - direct & total.
That's why you can't reproduce the error there.

**Comment by michalkleiner** [comment]
Hi @jr-ewing,
thank you for the bug report. This indeed looks like a potential bug, so I'll assign it to the product team for prioritisation.

**Comment by michalkleiner** [comment]
I can replicate this issue locally.
It seems to come down to escaping of the names of the metrics and records to plot, see the screenshot with the %20 instead of the space in the name.
<img width="600" alt="Acquisition graphing issue" src="https://user-images.githubusercontent.com/233342/235818350-c76d5ec0-1aca-494b-b90f-99197e9771c4.png">

**Comment by sgiehl** [comment]
duplicates https://github.com/matomo-org/matomo/issues/21051 and will be fixed with #21165
