### ISSUE TITLE
UX: Search bar javascript issue

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20640]
Hi team,
there is (I guess) a simple UX issue to fix within Matomo.
When using the search bar at the bottom of the report, if the user drag and drop by mistake the search icon then the word javascript appears.
![Screenshot from 2023-04-27 12-15-18](https://user-images.githubusercontent.com/28002238/234833285-85422cfb-4a31-4b70-b142-df4fbd077568.png)
This UX bug is here since a LONG time within Matomo, and honestly, that would be so great to fix it.

**Comment by michalkleiner** [comment]
Hi @Chardonneaur,
thanks for raising the issue. I can replicate it using the demo.matomo.cloud instance. It seems that you can drop any link with the `href` attribute to the field and it fills the search field with that text.
This might be a slight inconvenience however I don't see that as a major issue. I will still pass it onto the product team for prioritisation but it's likely this won't get any attention in the near future.

**Comment by heurteph-ei** [comment]
Hi @michalkleiner,
The bug described by Ronan leads also to another irritating behavior: it is impossible to select part of the text inside the search field. It is impossible to use the mouse to:
 - put the typing cursor somewhere in the field
 - select part of the text in the field

**Comment by Chardonneaur** [comment]
Thank you @heurteph-ei . Yes @michalkleiner . This is really an annoying UX thing. I mean when I am training participants about Matomo, you have no idea how many times the attendees want to throw the mouse of the window because of this bug, the number of times that they are saying that Matomo is not working etc
Just because the word javascript has been input by mistake.

**Comment by michalkleiner** [comment]
Right, I see. It's not only when drag&dropping the search icon, it's also on mouse selection within the text field. I can click around the text and select words by double-clicking on them just fine, but when trying to select some text within the field it drops the text there.
I'll reclassify this as a bug.
