### ISSUE TITLE
Windows 10 get recognized as Windows 11?

### ISSUE THREAD

**Issue by Tennyleaz** [piwik/piwik#20673]
## Context

I'm using Matomo HTTP API (using C# client) to track visitors. In visitor profile or visitor device, all windows 10 visits show windows 11.

## Expected Behavior

Windows 10 user agent shows correctly.

## Current Behavior

Windows 10 user agent shows windows 11.
If I set user agent string to `Mozilla/5.0 (Windows NT 10.0; x64)`, the profile shows as follow picture:
<img width="238"  src="https://user-images.githubusercontent.com/7089271/236417191-5caa2cd1-6775-4987-95ff-d4a257c3d617.png">

If I set user agent string to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Firefox/112.0`, the profile shows as follow picture:
<img width="243" src="https://user-images.githubusercontent.com/7089271/236417391-8ad1ed1e-e8fb-4193-befc-8b7779199488.png">

## Steps to Reproduce (for Bugs)

1. Using [piwik-dotnet-tracker](https://github.com/matomo-org/piwik-dotnet-tracker) in my project.
2. Set user agent string.
```C#
PiwikTracker piwikTracker = // ...
int osMajor = Environment.OSVersion.Version.Major;
int osMinor = Environment.OSVersion.Version.Minor;
string architecture = Environment.Is64BitOperatingSystem ? "; x64" : "; x86";
string userAgent = "Mozilla/5.0 (Windows NT " + osMajor + "." + osMinor + architecture + ")";
piwikTracker.SetUserAgent(userAgent)  // which is "Mozilla/5.0 (Windows NT 10.0; x64)"
```
3. Visit matomo and verify visit record, which is windows 11.

## Your Environment

* Matomo Version: 4.14.2
* PHP Version: 8.2
* Server Operating System: Ubuntu 20.04.6 LTS
* Additionally installed plugins:

* Browser: Firefox 112
* Operating System: Windows 10

**Comment by sgiehl** [comment]
Matomo is using device detector for detection. The mentioned useragents above are correctly detected as Windows 10.
Not sure why they are detected as Windows 10 for you. Can you extract the tracking requests that are sent to Matomo? Maybe they include something else causing this.

**Comment by Tennyleaz** [comment]
I tried to use wireshark to capture the packet.
A request is like:
```
GET /piwik.php?idsite=5&rec=1&apiv=1&r=316519&uid=Tennytest+1&_idts=1683279352&res=1707x960&_id=28574263493adfe9&url=http%3a%2f%2fWCR%2fWindows%2fv8.8.2%2fTest&urlref=http%3a%2f%2fWCR%2fWindows%2fv8.8.2%2fTest%3fpk_campaign%3dScan HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Firefox/112.0
Sec-CH-UA-Platform: Windows
Sec-CH-UA-Platform-Version: 13.0.0
Host: 10.10.15.65
```

**Comment by sgiehl** [comment]
Ok. In this case the client hints header are the cause.
```
Sec-CH-UA-Platform: Windows
Sec-CH-UA-Platform-Version: 13.0.0
```
You might need to suppress those if you don't want them to be respected.

**Comment by Tennyleaz** [comment]
OK.
Seems I need to remove these headers from `HttpWebRequest`.
