### ISSUE TITLE
Tracking Mastodon links in Matomo

### ISSUE THREAD

**Issue by prh22** [piwik/piwik#20688]
Bitte stellen Sie sicher, dass Sie "Mastodon" zu den SocialMedia-Referenzen hinzufügen! Bisher ist das alles bei "Twitter" zusammengefasst!
Vielen Dank.

Please make sure you add "Mastodon" to the SocialMedia references! So far it is all summarised at "Twitter"!
Thank you very much.

Peter

**Comment by sgiehl** [comment]
Hi @prh22 
I'm unfortunately not fully sure what you are trying to report here. Matomo uses a definition file for detecting social media referrers. The URLs we are using for detecting Mastodon are defined here: https://github.com/matomo-org/searchengine-and-social-list/blob/master/Socials.yml#L113-L135
If there might be one missing, feel free to report that in that repo or simply create a pull request for it.
Cheers,

**Comment by prh22** [comment]
Hallo, Stefan,

danke für die Antwort.

Ich hatte dies angefragt, weil auf meinen Seiten keine Referenzen von Mastodon (z.B. bildung.social) ausgewiesen werden.

In der von Dir genannten Datei „Socials.yml“ sind diese Referenzquellen jedoch vorhanden. Wo kann ich diese Datei lokal auf meinem Server finden? Oder liegt die dort gar nicht?

Mit anderen Worten: Was kann ich tun, damit diese Referenzen bei uns hier auch angezeigt werden?

Danke für Deine Bemühungen!

Mit freundlichem Gruß

 Peter R. Horak

**Comment by sgiehl** [comment]
Diese Datei sollte in Matomo enthalten sein. Darüber hinaus sollte Matomo diese auch automatisch aktualisieren insofern Verbindung zu Internet besteht.
Evtl kann dir dieses Plugin dabei helfen einzusehen was dein Matomo alles erkennt: https://plugins.matomo.org/ReferrersManager

**Comment by prh22** [comment]
Vielen Dank!

ich will sehen, ob mir das Tool weiterhilft…

😉

Gruß

Peter

**Comment by Findus23** [comment]
See also https://forum.matomo.org/t/let-matomo-recognise-traffic-from-mastodon-as-coming-from-mastodon-instead-of-direct-entry/46883/2?u=lukas as to why Mastodon traffic can't be recognized in Matomo. 
In summary:
- Mastodon can be hosted on any domain
- Mastodon hides the referrer for outgoing links

**Comment by prh22** [comment]
Danke für die Info!

Dennoch: ist sehr schade…

Peter
