### ISSUE TITLE
CoreAdminHome.invalidateArchivedReports date ranges not working

### ISSUE THREAD

**Issue by tladesignz** [piwik/piwik#20714]
Documentation says, you can provide something like this as query: `period=range&dates=2023-04-20,2023-05-04` but actually it fails in a really bad way:

The query returns with a **`200 OK`** containing an XML error:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<result>
    <error message="The date '2023-04-20' is not a correct date range. It should have the following format:  'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'." />
</result>
```

More details in the log:

```
Uncaught exception in API: /var/www/matomo/core/Period/Range.php(274): The date '2023-04-20' is not a correct date range. It should have the following format:  'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'. [Query: ?module=API&method=CoreAdminHome.invalidateArchivedReports&idSites=1&period=range&dates=2023-04-20,2023-05-04&token_auth=removed, CLI mode: 0]
```

## Context

We use this in the CIMP (Clean Insights Matomo Proxy) project:
https://gitlab.com/cleaninsights/clean-insights-matomo-proxy

I found another bug report, which is slightly related but quite old:
https://github.com/matomo-org/matomo/issues/9898

## Reason

`Period\Range::parseDateRange` expects the argument `$dateString` to be a range like '2023-04-20,2023-05-04'.
https://github.com/matomo-org/matomo/blob/5.x-dev/core/Period/Range.php#L293

BUT

`CoreAdminHome\API::getDatesToInvalidateFromString` (and earlier code, too!) deconstructs the date range into two values and tries to evaluate them separately.
https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreAdminHome/API.php#L318-L324

## Expected Behavior

- If a bug happens, don't return a `200 OK` but respective 400 or 500 error range status codes.
- Process date range correctly.

## Current Behavior

- Call is ignored, returns with error message BUT `200 OK` status code.

## Possible Solution

Rethink the concepts of periods either on the parsing side in `Period\Range` or on the calling side in `CoreAdminHome\API`.

## Steps to Reproduce (for Bugs)

1. Take query from log output.
2. Exchange the redacted token with a valid one.
3. Exchange `siteId` with a test project's ID.
4. Execute the HTTP query as documented in the log with a proper token with a tool like CURL, wget or the like.
5. See response and log.

## Your Environment

* Matomo-Version: 4.14.2
* MySQL-Version: 10.5.19-MariaDB-0+deb11u2
* PHP-Version: 7.4.33 
* Server Operating System: Debian Buster

Also:

* Matomo version: 4.14.2
* MySQL version: 8.0.33
* PHP version: 8.1.18
(See https://gitlab.com/cleaninsights/clean-insights-matomo-proxy/-/issues/3)

**Comment by tladesignz** [comment]
Interesting. While debugging this further to find a workaround, I understood, that the code I linked above (https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreAdminHome/API.php#L318-L324) actually doesn't split the date string. 
I obviously just glossed over it, when trying to understand what's going on.

However, a stack trace I dumped at the exception, brought me to the conclusion at first:
(The `object` key is removed, otherwise the output would have been unbearable.)

```
    [4] =&gt; Array
        (
            [file] =&gt; /var/www/matomo/plugins/CoreAdminHome/API.php
            [line] =&gt; 170
            [function] =&gt; getDatesToInvalidateFromString
            [class] =&gt; Piwik\Plugins\CoreAdminHome\API
            [type] =&gt; -&gt;
            [args] =&gt; Array
                (
                    [0] =&gt; Array
                        (
                            [0] =&gt; 2023-04-20
                            [1] =&gt; 2023-05-04
                        )

                    [1] =&gt; Piwik\Period\Range Object
                        (
                            [label:protected] =&gt; range
                            [today:protected] =&gt; Piwik\Date Object
                                (
                                    [timestamp:protected] =&gt; 1683889788
                                    [timezone:protected] =&gt; UTC
                                )

                            [defaultEndDate:protected] =&gt; 
                            [strPeriod:protected] =&gt; range
                            [strDate:protected] =&gt; 2023-04-20
                            [timezone:protected] =&gt; UTC
                            [endDate:protected] =&gt; 
                            [subperiods:protected] =&gt; Array
                                (
                                )
...

```

```
    [5] =&gt; Array
        (
            [function] =&gt; invalidateArchivedReports
            [class] =&gt; Piwik\Plugins\CoreAdminHome\API
            [type] =&gt; -&gt;
            [args] =&gt; Array
                (
                    [0] =&gt; Array
                        (
                            [0] =&gt; 1
                        )

                    [1] =&gt; 2023-04-20,2023-05-04
                    [2] =&gt; range
                    [3] =&gt; 
                    [4] =&gt; 
                    [5] =&gt; 
                )

        )
```

It seems, there's some automagic going on, which splits up the date string between function call and receive.

Anyway. It seems, I found a workaround by using `dates[]` instead of `dates` as the query parameter name.

**Comment by bx80** [comment]
Hi @tladesignz, thanks for reporting this.

I can recreate this issue on the 4.x-dev branch, but I've not been able to recreate it on the latest 5.x-dev branch. There was a [recent fix](https://github.com/matomo-org/matomo/pull/20413) committed to 5.x-dev which I think may have already fixed this issue.

Please reopen if you can recreate this issue on the latest 5.x-dev branch

**Comment by tladesignz** [comment]
Aaah! Sorry, I didn't find this bug. Seems pretty much the right fix. Thank you!
