### ISSUE TITLE
In the left menu under Goals/Forms/Custom reports are displayed incorrectly in Mobile

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20723]
Reproduced just now on Firefox on Android on mobile phone:
As you can see the Goal names in the left menus are not aligned properly.
![Screenshot_2023-04-26-20-52-28-10_3aea4af51f236e4932235fdada7d1643](https://github.com/matomo-org/matomo/assets/466765/caaa7b0f-31b9-4655-adab-1dedfe126536)

Expected instead a normal submenu list.

Note:

- We have the same bug in the Forms submenu as well
- And A/B Tests
- And Custom reports
so it's a global issue for left menu that have lists of things that can be created.

**Comment by sgiehl** [comment]
That seems to be a regression from the ~materialize css update~ vue migration. I'll propse a fix for that.
