### ISSUE TITLE
Applying filters in AB test reports hides 'variant' in all metric sections

### ISSUE THREAD

**Issue by angie-west-cgc** [piwik/piwik#20749]
When I apply a filter/segment which is filtering by IP to my AB test report, I see the data as expected in the top section (Evolution over the period) however all the metric sections only ever show the original variant. This means that when I am using filtering by IP address to verify that the test is behaving as I expect, I am only able to verify the original and not the variant. 

Attached are 2 tests to the original and variant of my AB test using different IPs. As you can see, both show the info I need re. visits in Evolution over the period, but I am only able to see metric info for the test with the original experience. 

![image](https://github.com/matomo-org/matomo/assets/133964570/acb56bdc-f0f1-4d11-85f3-3a1f3fde80d0)
![image](https://github.com/matomo-org/matomo/assets/133964570/c4290067-67bf-4139-b80c-e4fab35d9baf)

**Comment by sgiehl** [comment]
@AltamashShaikh @snake14 would you mind checking if that is a known bug in A/B tests plugin?

**Comment by snake14** [comment]
@sgiehl The closest thing I could find in the open issues was PG-357, but it doesn't seem to be the same issue. Can you find anything @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@angie-west-cgc Looks like there is no data for that segment

Example: Selected a segment which will not have variation data
![Screenshot from 2023-05-19 08-57-05](https://github.com/matomo-org/matomo/assets/14902277/ff028248-18e9-4bb1-aa4e-7710d70113c0)


Example: Selected a segment which will have variation data
![Screenshot from 2023-05-19 08-58-30](https://github.com/matomo-org/matomo/assets/14902277/3e27ba10-9799-45bf-89b7-4feee9331340)

**Comment by angie-west-cgc** [comment]
@AltamashShaikh I don't think that is what is happening here, when I apply my filter of AW Testing VPN there is 1 visit and that visit is in the variant of the AB test. On the AB test report, it shows a variant visit in the top graph yet no information in the other panels. 

Whereas when AW Testing VPN (2) is applied, again there is one visit but this is to the original of the AB test. On the AB test report again you see 1 visit in the top panel but also information in the others against 'original'

If a variant should not show when there is no data, when AW Testing VPN is applied then it should show variant 1 only but it looks to only ever be showing original in the reports regardless of the data collected. 

AW Testing VPN
<img width="1552" alt="Screenshot 2023-05-19 at 11 07 28" src="https://github.com/matomo-org/matomo/assets/133964570/b71c6335-9958-4f29-9e85-76c5221fb1e2">
<img width="1552" alt="Screenshot 2023-05-19 at 11 06 33" src="https://github.com/matomo-org/matomo/assets/133964570/8fcf18c1-f725-4a0b-8f74-5c3104931499">
<img width="1552" alt="Screenshot 2023-05-19 at 11 06 42" src="https://github.com/matomo-org/matomo/assets/133964570/78a5b5d2-2c8c-4458-ac22-0890ac63aa44">
![image](https://github.com/matomo-org/matomo/assets/133964570/24877917-b5c9-48fd-8f5f-72497ba5a54c)


AW Testing VPN (2)
<img width="1552" alt="image" src="https://github.com/matomo-org/matomo/assets/133964570/15a8769b-5ea3-4cba-918c-9aa0e26d7ace">
<img width="1552" alt="image" src="https://github.com/matomo-org/matomo/assets/133964570/e899f109-0bbb-46f6-b312-94ea19c76181">
<img width="1552" alt="Screenshot 2023-05-19 at 11 12 42" src="https://github.com/matomo-org/matomo/assets/133964570/b7849e47-a936-4250-bc54-e53afe29bbee">
![image](https://github.com/matomo-org/matomo/assets/133964570/3556bb47-0072-479b-bbaa-7d19cf797d17)

**Comment by AltamashShaikh** [comment]
@angie-west-cgc Thanks for the above info, will try to replicate and update you on this, and also it will be great if you could send such issues via Matomo support i.e by contacting them via email or from [here](https://matomo.org/support/). As this repository is used for Matomo core issues

**Comment by angie-west-cgc** [comment]
@AltamashShaikh apologies, I just used the form from the help docs. Is the issue OK here and I raise any new ones to Matomo support?

**Comment by AltamashShaikh** [comment]
would be great if you could do it for this issue and it looks like a bug to me,so would be easier to keep track of the bug for us.

**Comment by AltamashShaikh** [comment]
@angie-west-cgc I tried to debug this issue by creating 2 new segments, `ABTEST_GA4` and `ABTEST_UA` and can see following data and it filters data, this might be due to your settings configured in `config.ini.php`

![Screenshot from 2023-05-23 07-54-24](https://github.com/matomo-org/matomo/assets/14902277/b5383f38-3266-4f6d-949d-a03b9cf99d38)
![Screenshot from 2023-05-23 07-53-58](https://github.com/matomo-org/matomo/assets/14902277/0bd947ce-7389-4a75-ab27-7194ea687201)
![Screenshot from 2023-05-23 07-53-18](https://github.com/matomo-org/matomo/assets/14902277/22039465-2bdb-447e-87d5-81d04af50ab3)

**Comment by angie-west-cgc** [comment]
@sgiehl can you provide me the definitions of these segments please, so I can replicate?

**Comment by AltamashShaikh** [comment]
@angie-west-cgc 
![Screenshot from 2023-06-08 12-15-43](https://github.com/matomo-org/matomo/assets/14902277/a3529fd2-fd85-4c41-9a3e-edb3f9b82590)

![Screenshot from 2023-06-08 12-15-31](https://github.com/matomo-org/matomo/assets/14902277/6544e629-5a73-4da0-9623-d8dcd78c8c2a)

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. If you still experience problem around AB Testing, please directly reach out to our support. We only handle reports for Matomo itself in this repository.
