### ISSUE TITLE
SQLSTATE[42000] GET_LOCK support using Galera Cluster or MariaDB Galera Cluster

### ISSUE THREAD

**Issue by aresxc** [piwik/piwik#20752]
I’m using MariaDB Galera Cluster and everything works fine, but in some circumstances, like navigating through reports show errors like:

`QLSTATE[42000]: Syntax error or access violation: 1235 This version of MariaDB doesn't yet support 'GET_LOCK in cluster (WSREP_ON=ON)'`.

* Database server: MariaDB 10.11.3/mysql 15.1/Galera Cluster 26.4.14
* Matomo Version: 4.14.2
* PHP Version: 8.1.7
* Server Operating System: Ubuntu 22.04 LTS

MariaDB multi-master cluster setup. Matomo Archive works. Almost everything works fine, but it happens more on segments. 

This is weird because it's just about displaying the data, and not writing to the database.

**Comment by bx80** [comment]
HI @aresxc, thanks for reaching out. 

We don't support Matomo running on Galera Cluster at this time because currently the `GET_LOCK` function is required for archiving.

If your Matomo installation is using browser triggered archiving or if you are viewing data for date ranges then archiving can be happening the background which would explain why you are seeing an error message.

There is an ongoing [issue](https://github.com/matomo-org/matomo/issues/19643) to improve support for distributed databases and also a an [older experimental branch](https://github.com/matomo-org/matomo/tree/lockalt) which avoids using `GET_LOCK`. Unfortunately I can't give you any indication of when support might be added to a production release.

**Comment by jSML4ThWwBID69YC** [comment]
This is interesting. I've been running Matomo for over a  year on Galera without issues. It's only since the recent update to MariaDB 10.6.13 that the errors have shown up. 

The archiving itself does not seem to have any issues. I'm only seeing the sql errors displayed when navigating reports.

**Comment by manusfreedom** [comment]
> This is interesting. I've been running Matomo for over a year on Galera without issues. It's only since the recent update to MariaDB 10.6.13 that the errors have shown up.
> 
> The archiving itself does not seem to have any issues. I'm only seeing the sql errors displayed when navigating reports.

Same here.

**Comment by manusfreedom** [comment]
I think I found the source and it's not related to Matomo but MariaDB:
* In first line of https://mariadb.com/kb/en/mariadb-10-6-13-changelog/ you can see : `Includes all fixes from MariaDB 10.5.20`
* In https://mariadb.com/kb/en/mariadb-10-5-20-changelog/ you see:
```
[Revision #49ee18eb42](https://github.com/MariaDB/server/commit/49ee18eb42) 2023-01-27 10:40:07 +0200
[MDEV-30473](https://jira.mariadb.org/browse/MDEV-30473) : Do not allow GET_LOCK() / RELEASE_LOCK() in cluster
[Revision #696562ce55](https://github.com/MariaDB/server/commit/696562ce55) 2023-01-26 14:34:12 +0200
[MDEV-30473](https://jira.mariadb.org/browse/MDEV-30473) : Do not allow GET_LOCK() / RELEASE_LOCK() in cluster
```

We are not alone: https://jira.mariadb.org/browse/MDEV-31325

**Comment by jSML4ThWwBID69YC** [comment]
It's strange that Matomo has worked all this time even if GET_LOCK / RELEASE_LOCK technically did not.

**Comment by aresxc** [comment]
Has been reverted in MariaDB 10.11.4.

[MariaDB 10.11.4 Release Notes](https://mariadb.com/kb/en/mariadb-10-11-4-release-notes/):
> Revert "[MDEV-30473](https://jira.mariadb.org/browse/MDEV-30473) : Do not allow GET_LOCK() / RELEASE_LOCK() in cluster"

**Comment by manusfreedom** [comment]
> Has been reverted in MariaDB 10.11.4.
> 
> [MariaDB 10.11.4 Release Notes](https://mariadb.com/kb/en/mariadb-10-11-4-release-notes/):
> 
> > Revert "[MDEV-30473](https://jira.mariadb.org/browse/MDEV-30473) : Do not allow GET_LOCK() / RELEASE_LOCK() in cluster"

The main MariaDB versions have been reverted (10.6.14,...).
