### ISSUE TITLE
Fatal error: Call to undefined method Piwik\DataTable\Map::getMetadata() in MergeDataTables.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20768]
## Context

Got below error:

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Map::getMetadata()","file":"\/plugins\/API\/DataTable\/MergeDataTables.php","line":51,"request_id":"51562","backtrace":" on \/plugins\/API\/DataTable\/MergeDataTables.php(51)\n#0 \/plugins\/API\/API.php(381): Piwik\\Plugins\\API\\DataTable\\MergeDataTables->mergeDataTables(Object(Piwik\\DataTable\\Map), Object(Piwik\\DataTable\\Simple))\n#1 [internal function]: Piwik\\Plugins\\API\\API->get('1,3', 'range', '2023-04-17,2023...', false, Array)\n#2 \/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#3 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#4 \/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#5 \/core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'get', Array)\n#6 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#7 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#8 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#9 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#10 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n

URL: /?module=API&method=API.get&idSite=1,3&token_auth=XYZANONYMIZED&period=range&date=2023-04-17,2023-05-19&expanded=0&flat=1&segment=&format=JSON&format_metrics=0&filter_limit=-1&filter_pattern_recursive=

Referrer: None (meaning it's not coming from the UI)

GET: {"module":"API","method":"API.get","idSite":"1,3","token_auth":"XYZANONYMIZED","period":"range","date":"2023-04-17,2023-05-19","expanded":"0","flat":"1","segment":"","format":"JSON","format_metrics":"0","filter_limit":"-1","filter_pattern_recursive":""}

USER AGENT: Mozilla/5.0 (compatible; Google-Apps-Script; beanserver; https://script.google.com/; id: ....)

## Expected Behavior
No fatal error.

## Current Behavior
Fatal error

## Your Environment
Latest Matomo 4.X

**Comment by michalkleiner** [comment]
Looking at the code, this error can occur when one of the tables for the merge is empty/null. Based on the line number it's `$table1` in this case. We can investigate further or we can put a few extra safeguards in place.

**Comment by michalkleiner** [comment]
Replicated on demo2

**Comment by sgiehl** [comment]
This might actually be a problem of the `API.get` method. That one tries to merge all other available `get` reports of other plugins.
See https://github.com/matomo-org/matomo/blob/6d05d4952f7ee42257bb2f26d68f18b70fbef99a/plugins/API/API.php#L365-L382

For some reason this seems to result in merging a datatable map with a simple datatable. This shouldn't happen. So we need to investigate which API returns a simple datatable for a range request.

**Comment by tsteur** [comment]
This happened again

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Map::getMetadata()","file":"plugins\/API\/DataTable\/MergeDataTables.php","line":51,"request_id":"1bcf7","backtrace":" on plugins\/API\/DataTable\/MergeDataTables.php(51)\n#0 plugins\/API\/API.php(381): Piwik\\Plugins\\API\\DataTable\\MergeDataTables->mergeDataTables(Object(Piwik\\DataTable\\Map), Object(Piwik\\DataTable\\Simple))\n#1 [internal function]: Piwik\\Plugins\\API\\API->get('1,3,4,5,6,7,8,9', 'range', '2023-04-01,2023...', false, Array)\n#2 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#3 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#4 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#5 core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'get', Array)\n#6 plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()

for URL

> ?module=API&method=API.get&idSite=1,3,4,5,6,7,8,9&token_auth=XYZANONYMIZED&period=range&date=2023-04-01,2023-05-29&expanded=0&flat=1&segment=&format=JSON&format_metrics=0&filter_limit=-1&filter_pattern_recursive=

**Comment by tsteur** [comment]
This happened again a few times.

**Comment by tsteur** [comment]
This happened again.

**Comment by samjf** [comment]
Just a bit more info. I think this could possibly be related to some script. I looked back through the history and they all have the exact same user agent:
`USER AGENT: Mozilla/5.0 (compatible; Google-Apps-Script; beanserver; https://script.google.com/; id: UAEmdDd-xxxxxxxx)`
I munged the ID, but all of them have exactly the same ID so are likely the same Google app script.

**Comment by sgiehl** [comment]
Had another look at that one. The problem seems to be that `API.get` is called with multiple sites.
I was able to recreate that locally. The unexpected datatable seems to be returned by `VisitFrequency.get`, as it doesn't handle that type of request correctly.
I will create a PR to fix `VisitFrequency.get`, but the above request will end up in an API error nevertheless, as it will also try to call `Referrers.get`, which doesn't support multiple sites yet. But at least the PHP error should be gone afterwards.
