### ISSUE TITLE
URL overflows in goal conversions widget

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20772]
## Context

see screenshot below:
<img width="1194" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/3efae68e-1275-45d9-9107-1b0718425bc7">

## Steps to reproduce

* Add a goal widget to the dashboard where it has a long URL as best converting entry page.

## Your Environment
Latest Matomo 4.x

**Comment by michalkleiner** [comment]
Hi @tsteur, thanks for reporting this.
We have a similar issue for the actions (#20622), so will see if this can be addressed together.

**Comment by sgiehl** [comment]
@michalkleiner as this should be very simple and fast to fix, we can also move that directly in the sprint. Shouldn't be more than adding a `word-break: break-word;` to that element.
