### ISSUE TITLE
Sharing segments as an Admin user

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20778]
A customer has asked about sharing segments, when their user is only assigned the Admin role.

"My coworker cannot see the segments I have set up in our Matomo-account. I have attempted to find a way to share it, but can only find instructions that talk about a tool bar in the editor I cannot see."

Are we able to adjust the segments option to allow Admin users to share their segments with other users? (A segment created by an Admin user can only be viewed by that user and any super users currently)

As a super user there is the option to allow all users to see the segment:
![image](https://github.com/matomo-org/matomo/assets/118518962/73247187-dd0a-49eb-9674-f60a50e50d96)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/sharing-segments-between-users-as-a-normal-user/49317/3

**Comment by goochj03** [comment]
Another request from a customer for the ability to share segments from Admin users "Our company we have few people who use Matomo, the problem is that they can not share segments to entire company. Only Super Users (who also has administration access) can share segments. It creates extra work for us, because then only the person with Super User rights, can approve these segments and make them visible for everybody. Could you add possibility to the user rights to make segments visible for everybody, but still keep the user rights away from administration part?"

**Comment by goochj03** [comment]
"I've created a bunch of different segment views, but I can't share them with other people in the team, as I don't have "Super User" access." Another request to share segments from different user roles.

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue https://github.com/matomo-org/matomo/issues/6844, I'll close this one. It would be great to have your perspective there.
