### ISSUE TITLE
Mist analytics - Survey Plugin

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20780]
The customer is referring to the plugin by Mist analytics called Matomo Surveys - [https://www.youtube.com/watch?v=3Y5IsmqridA](https://www.youtube.com/watch?v=3Y5IsmqridA)

They seem to think this is a neat feature and having something similar implemented into cloud, could be beneficial for other customers.

Customer Response: "You have recently communicated about the availability of a plugin to realize survey online. I was sad to hear that this was only for the on premise version. This is a nice feature which can definitively increase the value proposition of Matomo by replacing both Google Analytics and Hotjar tools (sessions recording and heatmaps already available). Is there a chance that this functionality could be added to the pipeline of development? "

**Comment by sgiehl** [comment]
@goochj03 Might be possible to make that plugin available in cloud maybe. But that's out of control for us. Please create internal issues for requests that only affect cloud.
