### ISSUE TITLE
The colour highlight for the bounce trend in the Visit Summary should be reversed

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#20788]
A customer has noted that the colour highlight for the bounce trend in the Visit Summary should be green if trending downward and red if trending upward...

![image](https://github.com/matomo-org/matomo/assets/20234985/5a708302-3c0f-4ea4-a84a-1fb0c837c306)

**Comment by sgiehl** [comment]
Hi @9joshua 
Thanks for the report. We actually have methods in Matomo to determine whether a lower value is better or not. But it looks like that isn't used for the sparkline evolutions.
