### ISSUE TITLE
Column Sorting issue for Ecommerce -> Products -> Product Name table

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#20797]
_This behaviour is currently affecting a Cloud instance. See JIRA version of this ticket for instance URL._

In the report at Ecommerce -> Products -> Product Name, the 2nd 3rd and 4th column headers do not sort their corresponding columns, but instead sort the Visits column...

![image](https://github.com/matomo-org/matomo/assets/20234985/ad338feb-46d3-4880-8f27-02b2c9c5f340)

**Comment by michalkleiner** [comment]
Checked the [Demo Site - Web Analytics Reports - Matomo](https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=year&date=2023-03-08&idSite=1&category=Goals_Ecommerce&subcategory=Goals_Products) and it seems to work there, it could be that there is no data for some of the columns so it uses the number of visits as a secondary dimension to sort on?

**Comment by michalkleiner** [comment]
Needs further investigation.

**Comment by Team-Startup** [comment]
Hello,
I am the originator of this ticket. I still have this problem. Have you figured out what's causing it?

Have a nice day!

**Comment by sgiehl** [comment]
closing in favor of #21829
