### ISSUE TITLE
API throws "You must be logged in to access this functionality."

### ISSUE THREAD

**Issue by naivedeveloper95** [piwik/piwik#20792]
Matomo API throws this error "You must be logged in to access this functionality." even after passing the generated AUTH_TOKEN

## Context

I am trying to access a few User and Website Management functionality of Matomo through API into our platform. I tried this API **method=UsersManager.setUserAccess** but it throws this error "You must be logged in to access this functionality."

## Expected Behavior
I am able to access other APIs such as **method=UsersManager.inviteUser** and **method=SitesManager.addSite** and I was hoping to manage the Users and Websites functionality through the APIs provided by Matomo.

## Steps to Reproduce

I have added the snippet below for your reference:

`const axios = require('axios');
const FormData = require('form-data');
let data = new FormData();
data.append('module', 'API');
data.append('method', 'API.getBulkRequest');
data.append('urls[]', 'method=UsersManager.setUserAccess&userLogin=<username>&access=view&idSites=4');
data.append('format', 'json');
data.append('token_auth', 'MATOMO_GENERATED_TOKEN_AUTH');

let config = {
  method: 'post',
  maxBodyLength: Infinity,
  url: 'https://<on-prem-matomo-instance>/index.php',
  headers: {
    ...data.getHeaders()
  },
  data: data
};

axios.request(config)
  .then((response) => {
    console.log(JSON.stringify(response.data));
  })
  .catch((error) => {
    console.log(error);
  });`

**Response** : `[
    {
        "result": "error",
        "message": "You must be logged in to access this functionality."
    }
]`

## Your Environment
Matomo version: 4.13.3
MySQL version: 5.7.42-0ubuntu0.18.04.1
PHP version: 8.2.4

**Comment by naivedeveloper95** [comment]
Something similar happens for this **SitesManager.deleteSite** API too.

**Code Snippet**:

`const axios = require('axios');
const FormData = require('form-data');
let data = new FormData();
data.append('token_auth', 'MATOMO_GENERATED_TOKEN_AUTH');
data.append('passwordConfirmation', 'SU_PASSWORD');

let config = {
  method: 'get',
  maxBodyLength: Infinity,
  url: 'https://<on-prem-domain>/index.php?module=API&format=json&method=SitesManager.deleteSite&idSite=6',
  headers: { 
    ...data.getHeaders()
  },
  data : data
};

axios.request(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});
`

`{
    "result": "error",
    "message": "You can't access this resource as it requires a 'superuser' access."
}`

I am trying to integrate Matomo user and website management functionalities into our Platform using Matomo APIs.

**Comment by naivedeveloper95** [comment]
@sgiehl Can you please check If these functionalities are supported via API, and if yes how do I invoke them?

Kind Regards,
Satyam

**Comment by sgiehl** [comment]
All API methods should be callable. Some might require a token auth with higher privileges. See our API reference here: https://developer.matomo.org/api-reference/reporting-api

For further questions please try to seek for help on our forum. We use the issue tracker here only for bug reports and feature requests. Thanks.
