### ISSUE TITLE
Error in Matomo: Matomo requires the php-json extension 

### ISSUE THREAD

**Issue by agroundworld** [piwik/piwik#20794]
I currently run Matomo on a Prestashop site. The Matomo version is 4.14.2 On the website, I am attempting to upgrade to PHP 8 and am currently running 7.4. Whenever I upgrade to any version of 8 (8.0, 8.1, or 8.2) Matomo stops working and I get the following error message in the logs "matomo requires the php-json extension". I've checked the PHP version with phpinfo and it states that json is enabled.  I put a phpinfo file in the matomo folder for verification and it is using the php version that I have set for the website.  I’m attaching some of the screenshots of the log, the PHP setup screen, and the relevant phpinfo screenshots. The issue goes away when I downgrade to any php version less than 8. There seems to be an issue between Matomo and PHP 8.

Currently using the following:
Matomo version: 4.14.2
MySQL version: 5.7.42
PHP version: 8.1.18

![errorlog1](https://github.com/matomo-org/matomo/assets/75636570/41f3085e-55c4-4a11-b4df-f18035cf910d)
![errorlog2](https://github.com/matomo-org/matomo/assets/75636570/31a7fae2-0767-4da5-b815-6341ce89ef7b)
![errorlog3](https://github.com/matomo-org/matomo/assets/75636570/754e3568-841f-4cae-8bbb-926c8da385d7)
![PHP setup](https://github.com/matomo-org/matomo/assets/75636570/dee490cf-385f-45c5-91a6-5e3944f7369d)
![phpinfo1](https://github.com/matomo-org/matomo/assets/75636570/6c42d964-e390-4a67-b349-28bf5fcfb9e9)
![phpinfo2](https://github.com/matomo-org/matomo/assets/75636570/c97314a0-91d9-476c-a6e7-e9f7d97884ed)

**Comment by sgiehl** [comment]
Hm. That's very strange. The message is printed if a `function_exists('json_encode')` returns false.
That method should always be available if json support is enabled.
This actually can't be a general problem with PHP 8+ and Matomo. Our tests work smoothly there, most of our own instances and also Matomo Cloud are also already running on PHP 8+.
Maybe try to get some help on our forums. We can't give support for server related issues here.
