### ISSUE TITLE
SitesManager.updateSite is bug

### ISSUE THREAD

**Issue by 786659214** [piwik/piwik#20796]
When I was using Matomo's open API and using SitesManager.updateSite to call and modify the website interface, I found that the main_ When modifying my website link with the URL, I found that I couldn't update matomo_ The main of the site table_ The URL field, but if siteName is modified, the name field can be modified normally.
![9e350c00b1588cadf527ee4f76f172443c8a3085736811484eff8fee39d5717aQzpcVXNlcnNcNzg2NjVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQyODA1NjM3M192MlxJbWFnZUZpbGVzXDE2ODUzMjM1OTI3NTZfRjZDODFFNEItNDFGMi00MmJhLUI2RUYtNzNDNkM4RTlFODIxLnBuZw==](https://github.com/matomo-org/matomo/assets/49685173/b0ef3499-97c8-4d37-a8db-db261a3f6211)

**Comment by michalkleiner** [comment]
Hi @786659214, we already have the #20793 ticket for this from you, so I'll close this as a duplicate.
