### ISSUE TITLE
UI/integration tests seem to be order dependent

### ISSUE THREAD

**Issue by michalkleiner** [piwik/piwik#20805]
UI and integration tests need to be reliable and independent in order to be able to safely say we are not introducing regressions and/or testing scenarios that have hidden dependencies/assumptions.

## Context

When doing any UI related changes, we need reliable tests.

## Expected Behavior
Tests cases can be run in isolation and work independently and reliably.

## Current Behavior
Changing order of individual tests within the test suite can impact results.

## Steps to Reproduce (for Bugs)
E.g. in the `Login_spec.js` integration test change order of the tests or comment out first few of them.

**Comment by sgiehl** [comment]
It's actually kind of on purpose that some tests rely on each other. But that should only be the case within one test suite. Nevertheless there is some time for improvement and tests that rely on each other should maybe be marked in some way, so it's directly visible.

**Comment by michalkleiner** [comment]
I think we can close this for now, we had a discussion internally about the overall system and it's not a priority for now.
