### ISSUE TITLE
Events tracking - Categories & Actions names not shown (blank)

### ISSUE THREAD

**Issue by L3on1d** [piwik/piwik#20812]
Hi!

Our team working on Event tracking (configuration based on Matomo docs).

At the moment we unable to sort our "Categories" and "Actions" names due to missed name.

Please check my screenshots.

![image](https://github.com/matomo-org/matomo/assets/11537656/e30fb336-52d8-46c1-aa54-7226db07862e)

![image](https://github.com/matomo-org/matomo/assets/11537656/4257a290-0552-49aa-b162-2f82163cde91)

Events names works fine and listed correctly.

![image](https://github.com/matomo-org/matomo/assets/11537656/a57cbb42-24ff-46f5-9b74-dbb51bfc63aa)

Thank you.

System info:

OS: Ubuntu 18.04.6 LTS
Matomo: 4.14.2
PHP: 8.2.5

**Comment by sgiehl** [comment]
Hi @L3on1d 
Afaik a dash should be shown if no value had been tracked. If you look at the visitors log, are you able to see the event names correctly?

**Comment by L3on1d** [comment]
@sgiehl Hi!

In _Visitors - Visit Log_ I can't find such information.

**Comment by sgiehl** [comment]
They should be visible in visits log as actions for the visitors. If that isn't the case they might not have been tracked correctly.

**Comment by L3on1d** [comment]
Hmm, for example when I'm trying to find Event Name in visits log.

![image](https://github.com/matomo-org/matomo/assets/11537656/752ab555-9403-4eb4-933e-75d43b32e1a0)

Per my understanding, Events should be highlighted, for example like Goals.

![image](https://github.com/matomo-org/matomo/assets/11537656/83a02f3c-a343-40ad-beb3-629e73b2e1b6)

**Comment by sgiehl** [comment]
Yes. They should be displayed. See e.g. https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=month&date=2023-05-19&idSite=1&category=General_Actions&subcategory=Events_Events&popover=RowAction$3ASegmentVisitorLog$3AEvents.getActionFromCategoryId$3AeventAction$253D$253Dclick$3A$257B$2522date$2522$253A$25222023-05-19$2522$252C$2522period$2522$253A$2522month$2522$252C$2522idSubtable$2522$253A$25225$2522$257D

You could maybe have a look in the API response for `Live.getLastVisitsDetails` to see if events are included.

**Comment by L3on1d** [comment]
Should be Event Categories and Actions names visible in matomo log_link_visit_action table? I'm trying to find where this data should be stored on DB side.

![image](https://github.com/matomo-org/matomo/assets/11537656/1b2858c7-bc19-438b-896d-752a59cc2ffe)

Thank you!
