### ISSUE TITLE
Email report charts with only one value are not displayed correctly

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#20821]
It seems that when only one value is displayed in an email report chart, the chart's axes swap and the bar becomes a line...

![image](https://github.com/matomo-org/matomo/assets/20234985/fd81418b-7001-43a9-b67a-ac256d027065)

Example when more than one value is present in a chart...

![image](https://github.com/matomo-org/matomo/assets/20234985/812652b5-79bc-42b1-8d2e-665c474c0e3f)

**Comment by michalkleiner** [comment]
Hi @9joshua, would you have a link to an instance where this can be replicated or where you've seen it? Was it cloud or on-premise? Is it only when you receive the report via an email or could it be recreated when triggering the report via Matomo UI?

**Comment by 9joshua** [comment]
@michalkleiner This may have been a regression which has subsequently been fixed.
A Cloud customer reported this and I reproduced it in my Cloud account.
However I can no longer reproduce it and my email reports now look normal.

The issue was mainly with the visits summary chart. It looks the line showing the actual visits was not populating, but it is now...
![image](https://github.com/matomo-org/matomo/assets/20234985/d1b264ec-5d11-46c2-aec8-26e54e5f21e6)

**Comment by michalkleiner** [comment]
Ok, thanks for the confirmation @9joshua. I suggest we close this for now and if it reappears we can always reopen or create a new issue.
