### ISSUE TITLE
Install stack in Create SuperUser step, No redirect to the Step 6.

### ISSUE THREAD

**Issue by AkarinLiu** [piwik/piwik#20829]
## Context

I`am installing the matomo, but I have a Big Trouble, When I After Typing The Super User infomation, click next, and no Redirect to the Step 6.
## Expected Behavior

Click to the "Next" Button, will redirect to the Step 6.
## Current Behavior

Not redirect to the Step 6, Stack at Step 5.
## Possible Solution

Skip Step 5 When SuperUser is Created.
## Steps to Reproduce (for Bugs)

1.Config The Database.
2.Typing The Super User infomation.
3.Click "Next" button.

## Your Environment

* Matomo Version:4.14.2
* PHP Version:8.1.13
* Server Operating System:Debian GNU/Linux 11 (bullseye)
* Additionally installed plugins:

* Browser: Mozilla Firefox
* Operating System: Windows 11 Home

**Comment by sgiehl** [comment]
Hi @AkarinLiu 
Sorry to hear you are having trouble with the installation. Are you able to provide any additional information?
Were there maybe some error shown in the browser console or any failed requests. Does the PHP error log contain any errors that might be related?
Note: Our automatic tests for the installation are still working and they automatically click through the installation. So there aren't any known regressions on our side...

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. @AkarinLiu Hope you found a solution for your problem. Otherwise feel free to get in touch on or forum for further support.
