### ISSUE TITLE
The ignoreClearAllViewDataTableParameters query parameter doesn't work for UI tests testing evolution graphs

### ISSUE THREAD

**Issue by snake14** [piwik/piwik#20822]
While trying to write some new UI test cases, I noticed that the `ignoreClearAllViewDataTableParameters` query parameter was working for dataTable reports, but not evolution graph reports.

## Context
I'm unable to use an automated test to confirm that the report parameters are being stored and used correctly for visualisation reports. I was able to get it working for table reports, but not visualisation reports. For example, here is [a link to the test cases I added that did work](https://github.com/innocraft/plugin-CustomReports/pull/167/files#diff-bfe33e11d2e988c3fb0fc70edc3c008791ce120e8b5157ee3939bd59cbc3af26R213-R239). When I tried doing something similar for a visualisation report, it didn't work because there was an AJAX call for `?date=2022-11-21&module=Annotations&action=getEvolutionIcons&idSite=1&period=day&filter_limit=-1&lastN=30` which didn't include the `ignoreClearAllViewDataTableParameters` like the `getEvolutionGraph` or `saveViewDataTableParameters` AJAX calls did.

## Expected Behavior
The `ignoreClearAllViewDataTableParameters` query parameter should prevent the parameters from being cleared regardless of the type of report.

## Current Behavior
The `ignoreClearAllViewDataTableParameters` parameter only works for table reports and not visualisations.

## Possible Solution
Update the Annotations.getEvolutionIcons AJAX call to forward the `ignoreClearAllViewDataTableParameters` query parameter so that it doesn't cause stored report parameters to be cleared.

## Steps to Reproduce (for Bugs)
1. Add a new test case around saving the report parameters of a visualisation report. For example, I tried adding one for report 11 in `CustomReports/tests/UI/CustomReportsReport_spec.js`, using the `ignoreClearAllViewDataTableParameters` query parameter.
2. Note that despite including the `ignoreClearAllViewDataTableParameters` query parameter in the URL, the visualisation doesn't persist the report parameters.

## Your Environment
* Matomo Version: 4.14.3-b5
* PHP Version: 8.1.2-1ubuntu2.11
* Additionally installed plugins: CustomReports
* Browser: Brave (Chromium)
* Operating System: Ubuntu 22.04.2 LTS

**Comment by michalkleiner** [comment]
Thanks for the detailed report @snake14!

**Comment by sgiehl** [comment]
@snake14 I've created https://github.com/matomo-org/matomo/pull/20827 to convert that get parameter to a testing variable. That should allow to persist the value so it's used in all requests. Feel free to check if that would work for your tests...

**Comment by snake14** [comment]
Thank you @sgiehl . I tested your PR and confirmed that it fixes the issue I was running into while trying to create new UI test cases.
