### ISSUE TITLE
Allow wildcards to add website in URL patterns 

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#20839]
Under manage measurable > URL, URL patterns should be accepted so that multiple URLs can be setup & tracked. 

For e.g, if a user wants to track abc.example.com, xyz.example.com and 50 other URLs, we should be able to set it up as:

*.example.com

**Comment by michalkleiner** [comment]
Hi @Birkaransingh94, this is already possible when generating the JS tracking code, you can check the "Track visitors across all subdomains".

<img width="595" alt="track subdomains" src="https://github.com/matomo-org/matomo/assets/233342/b82a8fe1-3cdf-46b2-9323-d76b80750cd1">

**Comment by michalkleiner** [comment]
We also have open tickets for enhancements in the area — [19844](https://github.com/matomo-org/matomo/issues/19844) and [16484](https://github.com/matomo-org/matomo/issues/16484).

**Comment by michalkleiner** [comment]
Feel free to reopen and provide more details if allowing to track the subdomains in the JS tracking code area is not sufficient.

**Comment by Birkaransingh94** [comment]
@michalkleiner yes, I have seen this option. Thank you :)

Maybe we can add the same option under measurables > URL settings as well so that it is easy for user to set up tracking across all domains?
