### ISSUE TITLE
When adding a website, it adds it twice instead of once

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#20838]
Sometimes when adding a new website, the website is added twice. This seems to happen somewhat frequently, and I haven't found a common cause.

It's pretty easy to just delete one, but it's quite confusing when you're not familiar with the bug. 

## Expected Behavior

When adding a website, it adds it just once.

## Current Behavior

Sometimes it's added twice.

## Possible Solution

Workaround: people can delete the second one.
Actual fix: it shouldn't happen in the first place

## Steps to Reproduce (for Bugs)

Unsure

## Your Environment

Cloud
MacOs

**Comment by bx80** [comment]
Thanks for reporting this @Stan-vw, I wasn't able to easily reproduce this issue with some brief testing, so I'll assign it for prioritization where we can investigate in more depth.

**Comment by sgiehl** [comment]
@Stan-vw could that be some sort of double click issue? Maybe the create button isn't locked and it's possible to send the same request multiple times...

**Comment by Stan-vw** [comment]
@sgiehl I'm reasonably certain I didn't double click. Locking it after one click does sound logical to me, then again not a dev so I'm not sure what the best options are here.
@Javi-Ormaechea you've had this too iirc, any further details that you're aware of?

**Comment by sgiehl** [comment]
I just did a local test and the button seems no longer be disabled upon a click. This might be a regression of the vue migration. As least I think the button had been disabled before.
Anyway. Clicking the button 10 times creates 10 new sites. That should for sure be avoided by disabling the button. Should be an easy fix. Will have a quick look at it.

**Comment by Javi-Ormaechea** [comment]
@Stan-vw I haven't had this (as far as I can remember)
