### ISSUE TITLE
Ability to exclude team member visits

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#20833]
Exclusion by IP is useful for brick and mortar. For a modern, remote team, working from a wide variety of locations, including VPNs, it would be useful to be able to exclude team mamber trafffic.  

It would be helpful to exclude by one or more characteristics.  Possibilities:
- exclusions by email address
- excludions by User ID

**Comment by atom-box** [comment]
_One user wrote:_

> The biggest problems or pain points with Matomo?
> Answer:
> To be able to exclude visits from employees defined by their User ID from the consultation statistics.

**Comment by michalkleiner** [comment]
Hi @atom-box, thanks for the suggestion. I'm not sure how achievable this could be, so I'll put it to the product team to prioritise and have a discussion on the possible approach.

**Comment by heurteph-ei** [comment]
Hi @atom-box 
It is possible to exclude tracking thanks to a cookie, if I am right: 
![image](https://github.com/matomo-org/matomo/assets/79993552/76a3d8f1-0a4d-4b46-a4af-a2953dba0fa7)
https://matomo.org/faq/how-to/faq_126/

**Comment by sgiehl** [comment]
And in addition to that I had built a plugin to allow exclusion by dynamic hosts: https://plugins.matomo.org/ExcludeByDDNS
This is only available for on premise, though.

**Comment by Daijobou** [comment]
@atom-box Maybe I misunderstand your problem? Just don't include the matomo code in your page code if they are team members. That way they don't cause any traffic. So easily define exclude rules by your php code. 

You can also define/set up a special cookie for this people, so no need for logged in. Only check for this cookie, if exists don't insert matomo in your page.

**Comment by atom-box** [comment]
These are reasonable solutions.

Based on conversation with original requester, I think this issue can be closed.

**Comment by atom-box** [comment]
Closing.
