### ISSUE TITLE
Switch to Simplified Chinese version, the graphic generated by mail report shows garbled characters 

### ISSUE THREAD

**Issue by robbinhank** [piwik/piwik#20848]
[![20230607211300.png](https://i.postimg.cc/ZnP5DtDK/20230607211300.png)](https://postimg.cc/1VtSfTQL)

**Comment by sgiehl** [comment]
Hi @robbinhank 
Please try this steps to solve the problem: https://matomo.org/faq/how-to-install/faq_142/
If you still have issues afterwards, please let us know.

**Comment by robbinhank** [comment]
Thank you, perfectly resolved this issue.
