### ISSUE TITLE
[PHP 8.2 compatibility] WARNING: Deprecated - Creation of dynamic property

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20845]
From https://forum.matomo.org/t/deprecation-error-in-plugins-userid-reports-getusers-php/51551/3
 - [ ] WARNING: /plugins/UserId/Reports/GetUsers.php(58): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizations\Visualizations\HtmlTable\Config::$show_active_view_icon is deprecated - Matomo 4.14.2 - (Module: UserId, Action: getUsers, In CLI mode: false)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecation-error-in-plugins-userid-reports-getusers-php/51551/6

**Comment by sgiehl** [comment]
Looks like that property is outdated, and setting it can simply be removed.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecated-warning-messages-matomo-4-15-1-php-8-3-0/52760/2

**Comment by viceice** [comment]
Still seen this issue:
```
WARNING: /plugins/UserId/Reports/GetUsers.php(58): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizations\Visualizations\HtmlTable\Config::$show_active_view_icon is deprecated - Matomo 4.15.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UserId, Action: getUsers, In CLI mode: false)
```

**Comment by sgiehl** [comment]
@viceice This is at least fixed in Matomo 5.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-message/52377/2
