### ISSUE TITLE
Manage Session Cookie Expire time

### ISSUE THREAD

**Issue by ghnp5** [piwik/piwik#20866]
I'd like to have an option in the Settings to increase the Session Cookie time, if possible.

Currently, it seems to be 2 weeks, but I'd like to be able to manage that (increase or decrease).

## Environment
* Matomo Version: 4.14.2
* PHP Version: (using Docker)
* Server Operating System: (using Docker)
* Additionally installed plugins: TwoFactorAuth

**Comment by bx80** [comment]
Hi @ghnp5,

You should be able to use the `login_cookie_expire` config setting to achieve this:

```
; By default, the auth cookie is set only for the duration of session.
; if "Remember me" is checked, the auth cookie will be valid for 14 days by default
login_cookie_expire = 1209600
```

So if you add `login_cookie_expire = 2419200` to the `[General]` section of your `config/config.ini.php` file then the session cookie time would be set to four weeks, etc.
