### ISSUE TITLE
timeZone info always missing

### ISSUE THREAD

**Issue by itscvenk** [piwik/piwik#20886]
Using Matomo 4.x latest version with PHP 7.4

Using the javascript tracking

In dashboard, under visitors, timezone is always blank. And yes, I did try all date ranges. Looks like a bug

**Comment by sgiehl** [comment]
Hi @itscvenk 
I'm sorry, but I'm not able to follow you. Which report are you referring to? Would you mind adding a screenshot?
Thanks.

**Comment by itscvenk** [comment]
Hi @sgiehl 

It is in the dashboard

Image attached below. I accessed a page with the javascripting Tag as well as a separate one with the PHP tracking code

Nothing has shown up at all

![image](https://github.com/matomo-org/matomo/assets/117738376/86a27be5-2bbd-4ab2-89f0-1479d44b722d)

**Comment by sgiehl** [comment]
That actually looks like a custom report or a report provided by a certain plugin. I'm not aware of any timezone report that is shipped with matomo by default

**Comment by itscvenk** [comment]
My bad... it was not part of the default code
