### ISSUE TITLE
PHP tracking: userId is messed up

### ISSUE THREAD

**Issue by itscvenk** [piwik/piwik#20887]
Hi

latest version of Matomo 4.x plus PHP 7.4

Please consider the following code:

```
<?php 


try {
      $matomoSiteId = 3;                  // Site ID

      $matomoTracker = new MatomoTracker((int)$matomoSiteId, $matomoUrl);
      $matomoTracker->setTokenAuth($matomoToken);  
      $setVisitorIdResult = $matomoTracker->setVisitorId('a0aa6368fc475d97'); 
      echo "<hr>at line " . __LINE__ . " setVisitorIdResult is <pre>";  var_dump($setVisitorIdResult) ; echo  "</pre>";

        $matomoUserId = $matomoTracker->getUserId();
        echo "<hr>at line " . __LINE__ . " matomoUserId is <pre>";  var_dump($matomoUserId) ; echo  "</pre>";


        if (!$matomoUserId) {
          $matomoTracker->setUserId($cookieSetVal); //setting it to the cookie value for the main cookie
          echo "\r\n <h1>matomoUserId has been set to  $cookieSetVal for $theMatomoVisitorId  
          <br>  VisitorId:  $theMatomoVisitorId </h1>";

        } else {
          echo "\r\n <h1>matomoUserId = $matomoUserId for $theMatomoVisitorId  and unhexed is $theMatomoVisitorIdUnHexed \r\n</h1>
          <br>  VisitorId:  $theMatomoVisitorId </h1>";
        }

        $matomoTracker->doTrackPageView('hardcodedTitleForTest' . $_GET['version']);
        $matomoUserId = $matomoTracker->getUserId();
        echo "<hr>at line " . __LINE__ . " matomoUserId is <pre>";  var_dump($matomoUserId) ; echo  "</pre>";

        $theMatomoVisitorId = $matomoTracker->getVisitorId() ;
        echo "at line " . __LINE__ . " theMatomoVisitorId is $theMatomoVisitorId<hr>";
  

} catch (\Throwable $th) {
  //throw $th;
  echo "<h1>Caught exception .... " . $th->getMessage() . "</h1>";
}
```

The userId towards the bottom is reported as 4dee7e4ab4824b25, for example. 

Now look at these 2 screenshots from the dashboard. The userId magically changes and there is no mention of 4dee7e4ab4824b25 in the 2nd screenshot below (1st screenshot is from "visitor log" and the 2nd one is after clicking on the "view visitor profile")

How reliable is the php tracker? Will this mismatch impact reporting in any other way? I will be setting the userId manually like this using the php tracking

Thanks

![image](https://github.com/matomo-org/matomo/assets/117738376/1ee957cb-b771-4674-8692-6eb6b1ce5759)

![image](https://github.com/matomo-org/matomo/assets/117738376/e562ac8b-f30a-4e4f-8e0c-7b32222015d8)

**Comment by michalkleiner** [comment]
Hi @itscvenk. We appreciate your time opening the issues you come across while testing out Matomo and its tracking features. It would help us understand more about your use case and what you're trying to achieve if you could provide a step by step replication steps following the issue template.
Also if you provide a script like above it would help providing the full output it produces, the config of your instance that can be important as to how your local instance behaves in some of the tracking aspects etc. Can you clarify if you're raising a bug or is it more of a general question?

**Comment by itscvenk** [comment]
Using http api now so that i can do what i want with full flexibility

No time to retest above things, sorry. So closing it for now
