### ISSUE TITLE
Row labels disappear on double click in table report

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20894]
## Context

I have a custom report with a subtable. When I double click in the white space on a row, then all top level row labels disappear in Matomo 5.0 beta:

<img width="704" alt="Screenshot 2023-06-14 at 7 15 51 AM" src="https://github.com/matomo-org/matomo/assets/273120/a8ff8962-2ac0-4db0-825e-c2b00a5b0bc0">

In Matomo 4.0 the labels shorten:

<img width="323" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/de599127-8c93-450b-bd41-22c97ece4eba">

I couldn't reproduce it yet on a standard report I think.

## Expected Behavior

Labels stay fully visible

**Comment by sgiehl** [comment]
I was able to reproduce that locally by clicking a bit around on the events report. Not yet sure what it's caused by. But it's a regression that we should fix before the final release of Matomo 5.
