### ISSUE TITLE
Exported CSV not providing the full URL in Label

### ISSUE THREAD

**Issue by enual** [piwik/piwik#20891]
Customer tried to Export CSV but on the report, full page url is not showing under Label column. They want a feature that will display the full URL

![image](https://github.com/matomo-org/matomo/assets/132400623/a198ed51-c82e-4e45-9ecb-706c74e437e3)

**Comment by michalkleiner** [comment]
Hi @enual, thanks for opening the issue. Can you please provide more information about what report was exported, if there were any other selections/configuration made before the export was run and anything else that could help us evaluate/scope the issue? Thank you!

**Comment by enual** [comment]
Hi @michalkleiner base on the information customer provided, it's from Behavior > Pages tab. From their, they are not getting the full URL
![image](https://github.com/matomo-org/matomo/assets/132400623/e46f1639-02e0-486d-b641-f11fdcde1f40)

Please let me know if I need to get additional details from the customer.

**Comment by sgiehl** [comment]
@enual That should be possible by "flattening" the report. The export overlay should have an option like "flatten report". That will append a `&flat=1` to the export url.
