### ISSUE TITLE
HTTP Api on php7.4 token_auth is not taken into account at all! SECURITY HOLE

### ISSUE THREAD

**Issue by itscvenk** [piwik/piwik#20902]
PHP 7.4 & latest version of on premise Matomo 4.x

Token Auth is not needed!
Invalid token auth is also accepted!

And the visits show up in both above cases on the dashboard, under Dashboart/ visits log !!!

Is this intended? If so, then this is **flabbergasting**. Anyone can flood my dashboard! And the URL isn't hard to guess ....they simply have to look at the javascript requests and figure out what's the URL to matomo.php and flood my dashboard :-( 

I can provide logs on request

**Comment by sgiehl** [comment]
Hi @itscvenk 

The token_auth is only used to authenticate API requests.
Tracking requests by default do not need any authentication. This is only required when tracking requests with some special use cases, like a forced date in the past, force IP or location,..
Using the token_auth for javascript tracking wouldn't have any benefit actually, as it would still need to be sent with the request. And anyone could look it up and use it as well.

If you want to avoid having a public tracking endpoint, then you might need to consider using log importing or server side tracking using e.g. our php tracker instead.

**Comment by itscvenk** [comment]
Very strange. Will implement directory level protection and include access details in my http api :-(

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/token-auth-totally-ignored-with-the-http-api-calls-serious-issue/51805/2
