### ISSUE TITLE
UI breaks when trying to change a segment condition's operator

### ISSUE THREAD

**Issue by smokris** [piwik/piwik#20908]
## Context
I'd like to add a new segment with a condition whose operator is something other than "Equals".

## Expected Behavior
In the segment editor dialog, clicking the operator dropdown should allow changing the operator from "Equals" to another operator.

## Current Behavior
Clicking the operator dropdown causes the whole segment editor dialog to disappear.

Here's a screen recording demonstrating what happens:

https://github.com/matomo-org/matomo/assets/190164/ff9d5962-f752-43ff-bcfc-76f4154bf7aa

No errors are logged in the browser's console.

## Possible Solution
?

## Steps to Reproduce (for Bugs)
- "For UI bugs, please try to reproduce that on our demo (https://demo.matomo.cloud/)" — I can't do that since it requires signing in, but I haven't found a way to sign in to the demo instance.

1. Sign in to Matomo
2. Select a website
3. Click "All Visits"
4. Click "Add New Segment"
5. Click "Equals"
6. The "Add New Segment" form disappears, and the "All Visits" button no longer works

## Your Environment
* Matomo Version: 5.0.0-b3
* PHP Version: 8.2.6
* Server Operating System: CentOS Stream 9
* Additionally installed plugins:
   * LoginOIDC (5.0.0)
* Browser: reproduced bug in Firefox 114 and Safari 16
* Operating System: macOS 13

**Comment by sgiehl** [comment]
Hi @smokris 
Thanks for reporting this one. I was able to reproduce it. I will have a quick look if it's easy to fix.

**Comment by smokris** [comment]
Great, thanks.  I applied the patch to my site, and confirmed that it solves the problem for me, so I'm able to edit segment operators again.
