### ISSUE TITLE
_id not taken into account in http api

### ISSUE THREAD

**Issue by itscvenk** [piwik/piwik#20903]
php 7.4
Matomo latest version 4.x, on premise

Consider the following GET request to the HTTP API:
https://www.myDomain.com/matomoDirectory/matomo.php?url=https://www.myDomain.com/FORCE_ID_TO193386b8ec03528a&testVersion=1&idsite=3&rec=1&action_name=hardCodedRequest33333333333WithInfoLevel&_id=193386b8ec03528a&referenceCode=testVersion4

The attempt was to set _id to a valid 16 digit hexadecimal string.

This is ignored by Matomo (behavior is same in Javascript API as well as in PHP Api). One cannot force the visitorID

See attachments below. Personal data has been intentionally replaced

`DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] Debug enabled - Input parameters: array (
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] 'url' => 'https://www.myDomain.com/FORCE_ID_TO193386b8ec03528a',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] 'testVersion' => '1',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] 'idsite' => '3',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] 'rec' => '1',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] 'action_name' => 'hardCodedRequest33333333333WithInfoLevel',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] '_id' => '193386b8ec03528a',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] 'referenceCode' => 'testVersion4',
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] )
DEBUG Piwik\Tracker\Cache[2023-06-15 16:43:21 UTC] [f5a72] Website 3 tracker cache was re-created.
DEBUG Piwik\Tracker[2023-06-15 16:43:21 UTC] [f5a72] Current datetime: 2023-06-15 16:43:21
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\IntranetMeasurable\Tracker\RequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Actions\Tracker\ActionsRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Goals\Tracker\GoalsRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Ecommerce\Tracker\EcommerceRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\SitesManager\Tracker\SitesManagerRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PrivacyManager\Tracker\RequestProcessor::manipulateRequest()...
DEBUG PrivacyManager[2023-06-15 16:43:21 UTC] [f5a72] General tracker cache was re-created.
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Heartbeat\Tracker\PingRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PagePerformance\Tracker\PerformanceDataProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CustomDimensions\Tracker\CustomDimensionsRequestProcessor::manipulateRequest()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor::processRequestParams()...
DEBUG PrivacyManager[2023-06-15 16:43:21 UTC] [f5a72] DoNotTrack support is not enabled, skip check
DEBUG CoreHome[2023-06-15 16:43:21 UTC] [f5a72] Visitor doesn't have the piwik cookie...
DEBUG CoreHome[2023-06-15 16:43:21 UTC] [f5a72] The visitor was not matched with an existing visitor...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\IntranetMeasurable\Tracker\RequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Actions\Tracker\ActionsRequestProcessor::processRequestParams()...
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] (this is not a Site Search request)
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] Excluding parameters "ignore_referrer,ignore_referer,gclid,fbclid,msclkid,yclid,fb_xd_fragment,fb_comment_id,phpsessid,jsessionid,sessionid,aspsessionid,doing_wp_cron,sid,pk_vid,pk_cpn,pk_campaign,piwik_campaign,mtm_campaign,matomo_campaign,utm_campaign,utm_source,utm_medium,pk_kwd,pk_keyword,piwik_kwd,mtm_kwd,mtm_keyword,matomo_kwd,utm_term" from URL
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] Action is a PAGE_URL, Action name = hardCodedRequest33333333333WithInfoLevel, Action URL = https://www.myDomain.com/FORCE_ID_TO193386b8ec03528a
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Goals\Tracker\GoalsRequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Ecommerce\Tracker\EcommerceRequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\SitesManager\Tracker\SitesManagerRequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PrivacyManager\Tracker\RequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Heartbeat\Tracker\PingRequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PagePerformance\Tracker\PerformanceDataProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CustomDimensions\Tracker\CustomDimensionsRequestProcessor::processRequestParams()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor::afterRequestProcessed()...
DEBUG PrivacyManager[2023-06-15 16:43:21 UTC] [f5a72] Visitor IP (was: xxx.xxx.xxx.xxx) has been anonymized: xxx.xxx.xxx.xxx
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\IntranetMeasurable\Tracker\RequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Actions\Tracker\ActionsRequestProcessor::afterRequestProcessed()...
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] Recorded a new action (PAGE_URL) in the lookup table: myDomain.com/FORCE_ID_TO193386b8ec03528a (idaction = 388)
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Goals\Tracker\GoalsRequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Ecommerce\Tracker\EcommerceRequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\SitesManager\Tracker\SitesManagerRequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PrivacyManager\Tracker\RequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Heartbeat\Tracker\PingRequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PagePerformance\Tracker\PerformanceDataProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CustomDimensions\Tracker\CustomDimensionsRequestProcessor::afterRequestProcessed()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] New Visit (IP = xxx.xxx.xxx.xxx)
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Following dimensions have been collected from plugins: idsite, profilable, user_id, visit_first_action_time, visit_first_action_time, visit_goal_buyer, visit_goal_converted, idvisit, location_ip, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visit_last_action_time, visitor_seconds_since_first, visitor_seconds_since_order, config_id, idvisitor, visitor_returning, visitor_seconds_since_first, visitor_seconds_since_order, visitor_count_visits, visit_entry_idaction_name, visit_entry_idaction_url, visit_exit_idaction_name, visit_exit_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, , referer_keyword, referer_name, referer_type, referer_url, , location_browser_lang, config_browser_engine, config_browser_name, config_browser_version, config_client_type, config_device_brand, config_device_model, config_device_type, config_os, config_os_version, visit_total_events, visitor_localtime, visitor_localtime, visitor_seconds_since_last, visitor_seconds_since_last, config_resolution, config_cookie, config_flash, config_java, config_pdf, config_quicktime, config_realplayer, config_silverlight, config_windowsmedia, , visit_total_time, location_city, location_country, location_latitude, location_longitude, location_region
DEBUG Referrers[2023-06-15 16:43:21 UTC] [f5a72] Excluding parameters "ignore_referrer,ignore_referer,gclid,fbclid,msclkid,yclid,fb_xd_fragment,fb_comment_id,phpsessid,jsessionid,sessionid,aspsessionid,doing_wp_cron,sid,pk_vid,pk_cpn,pk_campaign,piwik_campaign,mtm_campaign,matomo_campaign,utm_campaign,utm_source,utm_medium,pk_kwd,pk_keyword,piwik_kwd,mtm_kwd,mtm_keyword,matomo_kwd,utm_term" from URL
DEBUG Referrers[2023-06-15 16:43:21 UTC] [f5a72] Excluding parameters "ignore_referrer,ignore_referer,gclid,fbclid,msclkid,yclid,fb_xd_fragment,fb_comment_id,phpsessid,jsessionid,sessionid,aspsessionid,doing_wp_cron,sid,pk_vid,pk_cpn,pk_campaign,piwik_campaign,mtm_campaign,matomo_campaign,utm_campaign,utm_source,utm_medium,pk_kwd,pk_keyword,piwik_kwd,mtm_kwd,mtm_keyword,matomo_kwd,utm_term" from URL
DEBUG Referrers[2023-06-15 16:43:21 UTC] [f5a72] Excluding parameters "ignore_referrer,ignore_referer,gclid,fbclid,msclkid,yclid,fb_xd_fragment,fb_comment_id,phpsessid,jsessionid,sessionid,aspsessionid,doing_wp_cron,sid,pk_vid,pk_cpn,pk_campaign,piwik_campaign,mtm_campaign,matomo_campaign,utm_campaign,utm_source,utm_medium,pk_kwd,pk_keyword,piwik_kwd,mtm_kwd,mtm_keyword,matomo_kwd,utm_term" from URL
DEBUG Referrers[2023-06-15 16:43:21 UTC] [f5a72] Excluding parameters "ignore_referrer,ignore_referer,gclid,fbclid,msclkid,yclid,fb_xd_fragment,fb_comment_id,phpsessid,jsessionid,sessionid,aspsessionid,doing_wp_cron,sid,pk_vid,pk_cpn,pk_campaign,piwik_campaign,mtm_campaign,matomo_campaign,utm_campaign,utm_source,utm_medium,pk_kwd,pk_keyword,piwik_kwd,mtm_kwd,mtm_keyword,matomo_kwd,utm_term" from URL
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] GEO: Found IP xxx.xxx.xxx.xxx location (provider 'geoip2php'): array (
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'continent_name' => 'xxxx',
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'continent_code' => 'xx',
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'country_code' => 'xx,
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'country_name' => 'xxxxxxxxx',
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'city_name' => 'xxxx',
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'lat' => 00,
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'long' => 00,
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'postal_code' => xxxx,
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'region_code' => 'xxxx',
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] 'region_name' => 'xxxxxx',
DEBUG UserCountry[2023-06-15 16:43:21 UTC] [f5a72] )
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] array (
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'idvisitor' => '4e22389cc311836e',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_id' => 'ebf60879db977b7e',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_ip' => 'xxx.xxx.xxx.xxx',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'idsite' => 3,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'profilable' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_first_action_time' => '2023-06-15 16:43:21',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_goal_buyer' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_goal_converted' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_last_action_time' => '2023-06-15 16:43:21',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visitor_returning' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visitor_seconds_since_first' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visitor_seconds_since_order' => NULL,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visitor_count_visits' => 1,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_entry_idaction_name' => 379,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_entry_idaction_url' => 388,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_exit_idaction_name' => 379,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_exit_idaction_url' => 388,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_total_actions' => 1,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_total_interactions' => 1,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_total_searches' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'referer_keyword' => NULL,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'referer_name' => NULL,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'referer_type' => 1,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'referer_url' => '',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_browser_lang' => 'en-us',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_browser_engine' => 'Presto',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_browser_name' => 'OI',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_browser_version' => '8.0',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_client_type' => 1,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_device_brand' => 'AP',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_device_model' => 'iPhone',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_device_type' => 1,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_os' => 'IOS',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_os_version' => '',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_total_events' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visitor_localtime' => '16:43:21',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visitor_seconds_since_last' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_resolution' => 'unknown',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_cookie' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_flash' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_java' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_pdf' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_quicktime' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_realplayer' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_silverlight' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'config_windowsmedia' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'visit_total_time' => 0,
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_city' => 'xxxxx',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_country' => 'xxx',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_latitude' => 'xxxxxx',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_longitude' => 'xxxxx',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] 'location_region' => 'xxxxx',
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] )
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\IntranetMeasurable\Tracker\RequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Actions\Tracker\ActionsRequestProcessor::recordLogs()...
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] Inserted new action: array (
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idvisit' => '256',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idsite' => 3,
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idvisitor' => '4e22389cc311836e',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idaction_url' => '388',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idaction_url_ref' => 0,
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idaction_name_ref' => 0,
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'server_time' => '2023-06-15 16:43:21',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idpageview' => '',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'pageview_position' => 1,
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'time_spent_ref_action' => 0,
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idaction_name' => '379',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] 'idlink_va' => '546',
DEBUG Actions[2023-06-15 16:43:21 UTC] [f5a72] )
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Goals\Tracker\GoalsRequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Ecommerce\Tracker\EcommerceRequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\SitesManager\Tracker\SitesManagerRequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PrivacyManager\Tracker\RequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\Heartbeat\Tracker\PingRequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\PagePerformance\Tracker\PerformanceDataProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] Executing Piwik\Plugins\CustomDimensions\Tracker\CustomDimensionsRequestProcessor::recordLogs()...
DEBUG Piwik\Common[2023-06-15 16:43:21 UTC] [f5a72] -> Scheduled Tasks: Starting...
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Starting Scheduled tasks...
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Scheduler: executing task Piwik\Plugins\CustomJsTracker\Tasks.updateTracker...
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Scheduler: finished. Time elapsed: 0.078s
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Scheduler: executing task Piwik\Plugins\PrivacyManager\Tasks.deleteLogData...
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Scheduler: finished. Time elapsed: 0.012s
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Scheduler: executing task Piwik\Plugins\PrivacyManager\Tasks.anonymizePastData...
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] Scheduler: finished. Time elapsed: 0.039s
INFO CoreAdminHome[2023-06-15 16:43:27 UTC] [804209] done
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] task,output
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] Piwik\Plugins\CustomJsTracker\Tasks.updateTracker,Time elapsed: 0.078s
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] Piwik\Plugins\PrivacyManager\Tasks.deleteLogData,Time elapsed: 0.012s
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] Piwik\Plugins\PrivacyManager\Tasks.anonymizePastData,Time elapsed: 0.039s
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] Finished Scheduled Tasks.
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] Next run will be from: 2023-06-15 13:23:36 UTC
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] Nothing to notice => default behaviour
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] End of the page.
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] array (
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72] )
DEBUG Piwik\Common[2023-06-15 16:43:27 UTC] [f5a72]
`

![image](https://github.com/matomo-org/matomo/assets/117738376/7f2109cb-baba-4270-afe0-b82f2b5ffcdd)

**Comment by michalkleiner** [comment]
Hi @itscvenk,
an initial check suggests there isn't an issue with the tracking itself. Please have a look at https://matomo.org/faq/general/faq_21418/ and https://developer.matomo.org/api-reference/tracking-api and consider using the `uid`/`cid` params and make sure the user ID is hexadecimal string (A-F, 0-9 characters only). We'll do some more testing to confirm or decline the issue.

**Comment by michalkleiner** [comment]
Hi @itscvenk, please try using the `cid` query param, and/or make sure you don't have cookie-less tracking enforced as that prevents _id being used. Check the logic in https://github.com/matomo-org/matomo/blob/4.x-dev/core/Tracker/Request.php#L737-L790.

**Comment by itscvenk** [comment]
i am now implementing http api so that I have full control on what goes into matomo and so am not impacted by this

with the javascript code, etc., any user can flood and corrupt my data. so, using the http api
