### ISSUE TITLE
Can't login using quic (http3)

### ISSUE THREAD

**Issue by kochtopf** [piwik/piwik#20916]
Sign-in form gets Error: The form security failed because of an invalid "Referer" header... error message.

## Context

No login possible

## Expected Behavior

Request URL:
https://domain/index.php?module=Login
Request Method:
POST
Status Code:
302
Remote Address:
192.168.x.x:443
Referrer Policy:
strict-origin-when-cross-origin

## Current Behavior

Request URL:
https://domain/index.php?module=Login
Request Method:
POST
Status Code:
403
Remote Address:
192.168.x.x:443
Referrer Policy:
strict-origin-when-cross-origin

## Steps to Reproduce (for Bugs)

1. add listen 192.168.x.x:443 quic;
2. add_header Alt-Svc 'h3=":443"; ma=86400';       # required for browsers to direct them to quic port

## Your Environment

* Matomo Version: 4.14.2
* PHP Version: 8.2.7
* Server Operating System: debian sid
* Browser: chromium and firefox same result
nginx version: nginx/1.25.1
built with OpenSSL 3.0.9+quic 30 May 2023

**Comment by Findus23** [comment]
This might be specific to nginx with quic.

https://matomo.lw1.at is reachable via HTTP/3 using Caddy and login is working normally for me.

**Comment by kochtopf** [comment]
thanks for the pointer. Yup looks like its nginx releated. I will look there.

**Comment by ddogfoodd** [comment]
@kochtopf did you find a solution by chance?

**Comment by harryqt** [comment]
Having the same issue, did you find any fix?

**Comment by kochtopf** [comment]
According my old quic notes...
1. moved from openssl to https://github.com/quictls/quictls (this gives you full quic API support incl. ssl_early_data)
2. port forward/open up iptables for UDP port 443
3. append 'fastcgi_param HTTP_HOST $host;' to your fastcgi.conf  <-- give this a try first. I remember it had something to do with quic.
