### ISSUE TITLE
Please update Readme for correct useable PHP version

### ISSUE THREAD

**Issue by Daijobou** [piwik/piwik#20925]
I mean this text in https://github.com/matomo-org/matomo/blob/5.x-dev/README.md?plain=1#L33 with

> PHP 7.2.5 or greater

You should specify which version of Matomo works with which version of PHP at all. Obviously there are some problems with PHP 8.2. The above information is a bit rudimentary. ;)

There are many open tickets https://github.com/matomo-org/matomo/issues?q=8.2

I wanted matomo set to PHP 8.2, because I wanted to uninstall 8.1 from the server and luckily I looked here and found the problems with it. :)

**Comment by michalkleiner** [comment]
Hi @Daijobou,
do you mean the [4 open issues](https://github.com/matomo-org/matomo/issues?q=8.2+is%3Aopen) where one is this one, two are enhancements and one is related to Azure and specific hosting setup?

Matomo should actually work on all version from the mentioned 7.2.5 up, the only issue with latest 8.2 is that there might be some deprecation warnings which if you encounter them, please report them.

Matomo have unit, system, integration and UI tests running on PHP 8.2 for the 5.0.0-beta3 version so the team is confident there aren't any major issues for the upcoming Matomo 5.0.0.

We'd appreciate more users testing the new beta release if you wanted to give that a go on PHP 8.2.

**Comment by michalkleiner** [comment]
As the information is correct at this time, I'll close the issue, but if you find any issues related to PHP 8.2, please report them individually. Thank you!
