### ISSUE TITLE
Characters not displaying in Chrome browser

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20937]
A customer has noticed an issue with missing characters on report graphs in their cloud instance. "Most of our views are missing some pixels in the views. For example, on my Channel Types vertical bar chart for "Search Engines" I see "Sear h -ngines" with the dash in my quote being part of an e."

Example:
![characters](https://github.com/matomo-org/matomo/assets/118518962/41d8720a-2d1d-4c8e-aea1-f67c0bce1e6d)

I have been able to replicate this issue when using Google Chrome on another account (it seems to happen randomly e.g. refresh the page with the graph a few times), the issue doesn't appear to occur in FireFox or Edge.

Example 2:
![characters2](https://github.com/matomo-org/matomo/assets/118518962/d71ed35d-b9c5-4773-ab58-54528f0016f9)

**Comment by michalkleiner** [comment]
Are you using zoom in or out by any chance to adjust font sizes in the UI, @goochj03?

**Comment by bx80** [comment]
That almost looks like there is some blank HTML element floating over the text. Are you able to right click precisely in the area of the missing characters, then choose inspect and see what element is shown in the DOM inspector?

**Comment by goochj03** [comment]
No not zooming in/out, simply loading the report and the text displayed with the graph appears that way.

Checking an example of the text with the issue via inspector, the code is:
<canvas width="52" height="11" class="jqplot-xaxis-tick" style="text-align: left; position: absolute; width: 52px; height: 11px; left: 237.75px;"></canvas>
![screengrab](https://github.com/matomo-org/matomo/assets/118518962/0f468501-5d5c-4c10-959a-0bed277e71d5)

**Comment by bx80** [comment]
What operating system and exact version of Chrome is being used?
Does disabling `Accelerated 2D canvas` in `chrome://flags/` help?

**Comment by michalkleiner** [comment]
I tried on several different devices with different version of Chrome and Brave and wasn't able to replicate this myself. Not really helpful, just for confirmation.

To me it also seems like there's a white rectangle over the text, so it might not be directly within the `div.jqplot-axis.jqplot-xaxis` element but somewhere in the graph markup.

**Comment by goochj03** [comment]
Using the latest version of Chrome "Version 114.0.5735.199 (Official Build) (64-bit)"
OS Windows 11 Pro

Disabling Accelerated 2D canvas in Chrome does seem to fix it. With this disabled, I can't replicate the problem anymore. If I re-enable this, I can get the issue to occur almost right away.

**Comment by bx80** [comment]
Thanks for confirming that disabling Accelerated 2D canvas in Chrome fixes the issue, that's a known Chrome bug on Windows. I'll close this issue since it's not some thing we can fix in Matomo.
