### ISSUE TITLE
Occasional Error message when Visitor Log is deactivate (regression)

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#20948]
When the visitor log is deactivated for a website an error message can be seen at times...
![image](https://github.com/matomo-org/matomo/assets/20234985/3e0ad127-e90a-406d-b0c4-caa4da5476e4)

In this particular case, the date range included the current date (related to live data?)

**Comment by michalkleiner** [comment]
Hi @9joshua, can you provide more details about when the error appears? Is it when viewing a particular report only, e.g. the Goal as in the picture, or it appears elsewhere too?

**Comment by 9joshua** [comment]
@michalkleiner The issue affected another user and they were not able to reproduce it, nor was I.

**Comment by sgiehl** [comment]
Without looking too much into details I would assume this can happen here:
https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CoreHome/vue/src/ReportingPage/ReportingPage.vue#L276

If there are not visits, we check for raw data to consider which notification to show. If visits log is disabled that API method might throw an error, that is then possibly displayed.

Guess we need to check if visits log is enabled (`piwik.visitorLogEnabled`) or not before before calling this API method.

**Comment by 9joshua** [comment]
This can be reproduced by:

- viewing a report that has no data
- for a site which has the visitor log disabled
- where the calendar period includes the current day (i.e. current month)

I think Matomo assumes that the disabling of the visit log produced the empty table, even if the reason is simply that no data exists for the requested table/period...
![image](https://github.com/matomo-org/matomo/assets/20234985/a7c4c33b-070e-4bcc-b4cf-8ec17e958f06)
