### ISSUE TITLE
Dependency jquery.dotdotdot has a non-commercial license

### ISSUE THREAD

**Issue by hg-diavlon** [piwik/piwik#20941]
Matomo is licensed under the GPL-3.0+, but our library-scanner detected a non-commercial license in the dependency jquery.dotdotdot (published under CC-BY-NC-4.0). 

## Context
The license CC-BY-NC-4.0 is a non-commercial-usage license as of https://creativecommons.org/licenses/by-nc/4.0/
This is not expected, since https://matomo.org/licences/ states a free use of matomo under GPL-3, which is contrary to the usage of a dependency with a non-commercial license.

## Expected Behavior
Usage of matomo without conflicting licenses in dependencies.

## Current Behavior
jquery.dotdotdot has a non-commercial license

## Possible Solution
As far as i understood, jquery.dotdotdot is only used for module-documentation for the matomo developers and is never be used in any context to end-users. Could it be simply removed in the release-process?

## Your Environment
* Matomo Version: 4.14.2-b146
* PHP Version:  8.0.28
* Server Operating System: SLES15 SP4

**Comment by bx80** [comment]
Hi @hg-diavlon, thanks for raising this issue. 

Removing this package from the release process might well be the solution here, I'll assign this to our product team for discussion and prioritization :+1:

**Comment by michalkleiner** [comment]
The package is actually used (at least) in the Marketplace plugin, so we will need to find a replacement for it or a different approach to how we clamp content there.
