### ISSUE TITLE
Pass URL parameters to variation in a/b testing

### ISSUE THREAD

**Issue by p1xel007** [piwik/piwik#20947]
Hello, how do I pass url parameters from the original variation to the secondary variation in a/b testing?

**Comment by bx80** [comment]
Hi @p1xel007, thanks for reaching out. This github repository is for development issues and improvements relating to the core Matomo application, so for support queries on the a/b testing premium plugin I'd recommend you contact the dedicated support team who will be happy to help :slightly_smiling_face:
