### ISSUE TITLE
[PHP 8.1 compatibility] Deprecated - trim(): Passing null to parameter #1 ($string) of type string

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#20959]
From: https://forum.matomo.org/t/probleme-de-recherche-de-mise-a-jour/51570/11
 - [ ] `/core/CliMulti/Process.php(259): Deprecated - trim(): Passing null to parameter #1 ($string) of type string is deprecated - Matomo 4.14.2 - Piwik\ErrorHandler::errorHandler(),#1/core/CliMulti/Process.php(259),#2/core/CliMulti/Process.php(244),#3/core/CliMulti/Process.php(200),#4/core/CliMulti.php(289),#5/core/CliMulti.php(85),#6/plugins/Diagnostics/Diagnostic/CronArchivingCheck.php(63),#7/plugins/Diagnostics/DiagnosticService.php(68),#8/plugins/Diagnostics/DiagnosticService.php(54),#9/plugins/Installation/Controller.php(525)`
 - [ ] `/core/CliMulti/Process.php(259): Deprecated - trim(): Passing null to parameter #1 ($string) of type string is deprecated - Matomo 4.14.2 - Piwik\ErrorHandler::errorHandler(),#1/core/CliMulti/Process.php(259),#2/core/CliMulti/Process.php(244),#3/plugins/Diagnostics/Diagnostic/CronArchivingCheck.php(68),#4/plugins/Diagnostics/DiagnosticService.php(68),#5/plugins/Diagnostics/DiagnosticService.php(54),#6/plugins/Installation/Controller.php(525),[internal function]: Piwik\Plugins\Installation\Controller->systemCheckPage(),#8/core/FrontController.php(637),#9/core/FrontController.php(169)`

I think this is not related to #20658

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/probleme-de-recherche-de-mise-a-jour/51570/14

**Comment by sgiehl** [comment]
Looks like this might fail if a `shell_exec` can't be executed correctly. A simply check if the variable isn't empty should solve this.
