### ISSUE TITLE
Wordpress Plug-in doesn't display Matomo pages correctly

### ISSUE THREAD

**Issue by SophieTamara** [piwik/piwik#20958]
## Context
I downloaded the Matomo Analytics Plug-in on a wordpress website hosted on Hostinger. But when I open the links in the Matomo menu (summary, settings, ...), they don't show up like they should. There are no lay out, just text and permalinks. 
Only when I click on Reporting and Tag Manager it opens a new window to the Matomo pages with the Dashboard. All the other links in the menu, which are supposed to open within the wordpress admin panel, are having issues. 

## FIx
I have no idea how to fix this. 

## Environment
* Matomo Version: Version 4.14.2
* PHP Version: No idea
* Server Operating System: No idea
* Additionally installed plugins: All in One Migration, Contact Form, Flamingo, Jetpack, MC4WP, Spectra, UpdraftPlus, Woo commerce (+Payment, + Shipping), WP Super Cache, Yoast SEO
* Browser: Brave
* Operating System: MacOs

**Comment by michalkleiner** [comment]
Hi @SophieTamara,

thank you for reaching out. This Github repository is for development issues and improvements relating to the core Matomo application and we don't provide user support this way.

We have a FAQ/a guide for enabling tracking within Wordpress CMS, perhaps you might give that a go? It's on https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-wordpress/. The main point is to search for "Connect Matomo" and use the "WP-Matomo Integration (WP-Piwik)" plugin.

If you need further help, the best place to ask is the [Matomo Forum](https://forum.matomo.org). It might be good to also include some screenshot of how the UI looks for you.

Thank you for understanding and best of luck enabling tracking for your WP site!

**Comment by SophieTamara** [comment]
The issue is not on WP-Matomo Plug-in, it's on Matomo Analytics – Ethical Stats plug-in. I think it could be an issue that other users might encounter. 
I wasn't trying to connect Matomo. It's already connected. Everything works fine with the tracking. The issue is just when we click on the menu links of the Matomo plug-in, it doesn't show pages with the right layout, it's just text and links.

![Capture d’écran, le 2023-07-03 à 14 52 13](https://github.com/matomo-org/matomo/assets/103660199/faff4ff2-c971-4c04-8c8d-9eba3bbe6c3f)

![Capture d’écran, le 2023-07-03 à 14 49 35](https://github.com/matomo-org/matomo/assets/103660199/11098734-e748-4ee2-9626-092a4f748526)

**Comment by heurteph-ei** [comment]
@SophieTamara 
Can you have a look at the network tab of the browser console to see the error cause of the missing CSS ?
I think this is a server misconfiguration, not a Matomo plugin problem.

**Comment by lance-matomo** [comment]
Hey @SophieTamara, If you are having issues with the Matomo for Wordpress plugin the best place to get help is in the forum:
https://wordpress.org/support/plugin/matomo/
