### ISSUE TITLE
Seeking Advice: Best Module for React App/Website Tracking?

### ISSUE THREAD

**Issue by areeshaad** [piwik/piwik#20954]
Hi there,
I'm here to seek your valuable expertise and recommendations regarding the tracking of React applications or websites.

Our team is currently working on a React-based project, and we are looking for the most suitable module or approach to integrate Matomo tracking into our app. We want to ensure accurate tracking and leverage the capabilities of Matomo effectively.

If any of you have experience with tracking React apps or websites using Matomo, we would greatly appreciate your insights. Could you please share your recommendations, best practices, or any modules that you have found useful in this context?

Thank you in advance for your time and assistance. We value your expertise and look forward to your valuable suggestions.

**Comment by michalkleiner** [comment]
Hi @areeshaad,

thank you for reaching out. This Github repository is for development issues and improvements relating to the core Matomo application and we don't provide user support this way.

Of course every application may require slightly different approach, but using Matomo Tag Manager seems to be the best/most common way.

We have a FAQ/a guide for tracking React apps on our website — https://matomo.org/faq/new-to-piwik/how-do-i-start-tracking-data-with-matomo-on-websites-that-use-react/.

There are also questions related to React with some suggestions and answers on Matomo Forum, for example https://forum.matomo.org/t/matomo-integration-in-react-app/41044.

Thank you for understanding and best of luck building your React app!
