### ISSUE TITLE
Too long city names might overlap in visitor profile

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#20963]
A too long city name can currently overlap the browser name, which makes both unreadable.

![image](https://github.com/matomo-org/matomo/assets/1579355/36ab7163-f496-48b3-a799-1163f3d37040)

We should either shorten the city name to a certain amount of chars and appending `...` or wrap the content into multiple lines.

Note: The full city name would always be visible when hovering it.

**Comment by mindbreaker** [comment]
Do you think we can fix this with this:

```
.visitorLogIconWithDetails {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}
```

**Comment by Stan-vw** [comment]
@Javi-Ormaechea do you have preference for any particular way to fix this?

**Comment by ARSHIL1804** [comment]
Can I contribute to this issue?

**Comment by Stan-vw** [comment]
> Can I contribute to this issue?

Yes, if you can make a PR that solves this (ideally with a test), that would be wonderful.

**Comment by ARSHIL1804** [comment]
my PR : https://github.com/matomo-org/matomo/pull/21145

**Comment by ARSHIL1804** [comment]
@sgiehl  why is it still open?

**Comment by sgiehl** [comment]
Seems the PR was not yet merged. I'll have a quick look at that.
