### ISSUE TITLE
In the Diagnostics plugin (core) add a helpful link to Packet Too Large for max_allowed_packet

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#20970]
A user has suggested we add a useful footnote in our comments:

> In Settings page ?page=matomo-systemreport maybe you could link max_allowed_packet pointing tohttps://dev.mysql.com/doc/refman/8.0/en/packet-too-large.html where one can find how to fix it.

**Comment by bx80** [comment]
This is a trivial change so I've added a quick PR [here](https://github.com/matomo-org/matomo/pull/20990)
