### ISSUE TITLE
Feature request: Quarterly reports

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#20981]
Feature request: It will be nice to have an option for quarterly reports.

**Comment by michalkleiner** [comment]
Thanks for the suggestion @Birkaransingh94. I'll move this to PO for prioritisation but if there's more info, more context etc, please feel to add it here or internally.

**Comment by Stan-vw** [comment]
This seems like a duplicate of https://github.com/matomo-org/matomo/issues/20418 so I'll close this ticket.
Feel free to reopen if it's a different request.
