### ISSUE TITLE
Module UserId.getUsers is not showing full data when used in API.

### ISSUE THREAD

**Issue by RohitG7-Hexaware** [piwik/piwik#20993]
This API - module=API&method=UserId.getUsers&idSite=1&period=year&date=last1&format=JSON isn't giving the full data which is showing in the Matomo dashboard, For Example:- There are 5 clients, And if we use segmentation to filter out on the basis of domain name, We see there are 40 users which are active for YTD (Year to Date). But in the above API when hit it gives us only count as 20.

**Comment by sgiehl** [comment]
@RohitG7-Hexaware Sorry to hear you are having trouble using the API.
Actually the Dashboard uses the API to display data, so the results can only differ if the API parameters are different to those used by the dashboard.
Which URL parameters are there when you are viewing the dashboard?

**Comment by RohitG7-Hexaware** [comment]
Matomo Dashboard Parameters - https://app-tensai-analytics-prod.azurewebsites.net/index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?period=year&date=2023-07-11&idSite=1&category=General_Visitors&subcategory=UserId_UserReportTitle

Matomo API - https://app-tensai-analytics-prod.azurewebsites.net/?module=API&method=UserId.getUsers&idSite=1&period=year&date=last1&sformat=JSON&token_auth=''

**Comment by RohitG7-Hexaware** [comment]
@sgiehl Can you please help us out here.

**Comment by sgiehl** [comment]
The only obvious difference in both calls I can see is the used date. On the dashboard you are using `2023-07-11`, while you use `last1` in the API call. Are the results still different when using the same date?

**Comment by RohitG7-Hexaware** [comment]
Yes, i'm not getting the same results as dashboard.

**Comment by sgiehl** [comment]
Technically the results will always be the same on dashboard and API, as the dashboard uses the API. If this isn't the case there might be certain settings in the UI report set, that differ from API. Hard to guess the real reason without looking into the instance.
I'll close this here, as we don't have the capacity to provide this type of support here.
@RohitG7-Hexaware If you still have this problem, maybe try to find some help on our forums...
