### ISSUE TITLE
Add console plugin:install

### ISSUE THREAD

**Issue by mwithheld** [piwik/piwik#21003]
Add a console command to install a plugin: 
`console plugin:install ...`

## Summary
The console can uninstall, activate and deactivate, but strangely, cannot install plugins.  The command `console plugin:install` would facilitate automated installs, and replace our current clumsy wget-unzip method.  The command should get the latest version of the plugin that is compatible with the currently-installed Matomo version, e.g. by parsing through https://plugins.matomo.org/api/2.0/plugins/:pluginname/info .  E.g. if you have Matomo 4.x and want the ExtraTools plugin (https://plugins.matomo.org/api/2.0/plugins/EXtraTools/info) you would get version "4.1.0-beta5" and not version "5.*".

## Your Environment
* Command line
* Matomo Version: any
* PHP Version: any
* Server Operating System: Linux

**Comment by michalkleiner** [comment]
Hi @mwithheld,
thank you for the suggestion.
Is it not possible for you to use the Marketplace plugin from within the Settings area?

**Comment by mwithheld** [comment]
Command-line automated install of plugins via the CLI console is what we're after.
Automating the UI install of plugins is possible, but much more complicated.
We currently wget https://plugins.matomo.org/api/2.0/plugins/$pluginname/download/latest but this fails when the latest version of the plugin is incompatible with the current (non-beta) version of Matomo.

**Comment by michalkleiner** [comment]
Ok, thanks for the extra info. I'll pass this to the product owner for prioritisation, but if you're keen to provide a PR we will be happy to look at it, as always.
