### ISSUE TITLE
FAQ of Email open tracking is not correct since Matomo 4.14 update

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#21006]
Description of email tracking with campaign parameters _rcn and _rck is not correct anymore, since the update to 4.14: https://matomo.org/faq/how-to/faq_25454/

These Campaign parameters will no longer attribute visits, but only conversions (https://github.com/matomo-org/matomo/blob/eed6ea95caa687d33b67b04dc7e05176bfd50895/CHANGELOG.md?plain=1#L79). This kind of changes should mostly be done in major updates, because a lot of users are probably using this technique, based on the FAQ.

https://matomo.org/faq/how-to/faq_25454/ - hydrate the URL parameter with mtm_* campaign parameters to track an email opening as a campaign. _rcn, _rck are not attributing visits anymore (visits are all reported as direct since the update).

**Comment by sgiehl** [comment]
Hey @peterbo 

Thanks for bringing this to our attention. I actually wasn't aware that we suggest to use those  parameters for attributing email referrers.
I agree that normally such a change should be done with a major release, but there were some bigger issues with attribution that made us decide not to wait for a major release with this fix.
We will update the FAQ so it will suggest using the normal campaign parameters instead.

**Comment by peterbo** [comment]
Thank you, @sgiehl!

**Comment by sgiehl** [comment]
I've just updated the FAQ so it advises to use `mtm_campaign` / `mtm_keyword` instead if the old `_rcn` / `_rck`
