### ISSUE TITLE
Getting this error message when we go ahead with custom segment creation

### ISSUE THREAD

**Issue by naivedeveloper95** [piwik/piwik#21027]
Here is the snapshot of the error message for a test site:

![image](https://github.com/matomo-org/matomo/assets/15083393/0047586e-5dbd-4e83-a1ce-3a4c788f198e)

How do I resolve this? 

Matomo Version: 4.15.0

**Comment by sgiehl** [comment]
Hi @naivedeveloper95 
Thanks for reporting this one. We have already provided a fix for it in https://github.com/matomo-org/matomo/pull/20549
It will be fixed with Matomo 5.
