### ISSUE TITLE
Add new user: password manager might change new users username

### ISSUE THREAD

**Issue by mvaneijgen** [piwik/piwik#21023]
## Context
When creating a new user it will prompt for your password, when you fill this in with the build in macOS password manager it will change the username of the new user to the current username.

I made a screen recording to better illustrate the issue. As you can see underneath the op up the username gets updated
[![PIeYkcFHdkw](https://img.youtube.com/vi/PIeYkcFHdkw/0.jpg)](https://www.youtube.com/watch?v=PIeYkcFHdkw)

## Expected Behavior
When I fill in my password is should keep the new users username

## Possible Solution
It seems like the fields are linked to each other. A password field usually has a username field, so either the fields should be better scooped. An extra username field should be above the password field, disabled and pre-filled in or the password prompt should be on a new page instead of a popup.

## Steps to Reproduce (for Bugs)

1. Create a new user
2. Click "invite user"
3. Have your password be filled in by a password manager. 

## Your Environment
Matomo 4.15.0
PHP 8.2
Safari Version 16.5.1 (18615.2.9.11.7)
macOS 13.4.1 (22F82)

**Comment by sgiehl** [comment]
The inputs currently don't have a `autocomplete="off"`. I'll prepare a PR to add that. But not sure how much that will help, as many browsers or password managers ignore that attribute.

**Comment by heurteph-ei** [comment]
Hi @sgiehl 
I saw also this: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password
