### ISSUE TITLE
Filtered / missing datas in reports

### ISSUE THREAD

**Issue by tisonv** [piwik/piwik#21035]
## Context
How has this issue affected you? Reports are wrong / missing
https://forum.matomo.org/t/archiving-ignores-filters-url-patterns/52218/1
https://forum.matomo.org/t/missing-data-in-behaviours-and-page-titles/52188/1

## Expected Behavior
The search in the 'Page' page should return all results
The 'Title' page should return all visits
The numbers should match

## Current Behavior
Only urls with certain patterns are taken into account.
No settings are to be found on the why.
No log explains the behaviors

## Possible Solution
Give an easy way to see / query the blob value in matomo_archive_blob_* ?
More logs in the archiving process ? The datas exist in matomo_log_link_visit_action and matomo_log_action

## Steps to Reproduce (for Bugs)
Both in our staging and production environments, 
* https://intranet.domain.fr/jcms/pr2_865552/se-proteger-des-piqures-et-morsures-d-insectes 
* https://intranet.domain.fr/jcms/pl1_861012/les-animations-de-l-ete-vous-attendent 
Both appear in the 'Title' page but the view numbers is wrong 
Both are missing in the 'Page' page and won't be found when pr2_865552 or pl1_861012 is searched.

* https://intranet.domainfr/jcms/pr1_855922/expo-photo-robert-doisneau
will appear in 'Page' and 'Title' but the numbers are off and do not match the ones in the database (but my query may be off though)
The total views displayed :
  * in Page : 447
  * in Title : 470
  * db : 479

## Your Environment
* Matomo Version: 4.15
* PHP Version: 8.2.1
* Server Operating System: Windows 2019
* Additionally installed plugins:
Actions (Core) 	
Annotations (Core) 	
CampusGeoIP (v4.1.4) 	
Contents (Core) 	
CustomDimensions (Core) 	
CustomJsTracker (Core) 	
DBStats (Core) 	
Dashboard (Core) 	
DevicePlugins (Core) 	
DevicesDetection (Core) 	
Provides extended information about user devices, such as Brand (manufacturer), Model (device version), device type (tv, consoles, smart phones, desktop, etc) and more.
Diagnostics (Core) 	
Performs diagnostics to check that Matomo is installed and runs correctly.
Ecommerce (Core) 	
Events (Core) 	
Goals (Core) 	
Heartbeat (Core) 	
IP2Location (v4.1.2) 	
ImageGraph (Core) 	
Insights (Core) 	
IntranetMeasurable (Core) 	
InvalidateReports (v4.1.1) 	
Live (Core)
LoginLdap (v4.7.3) 	
Marketplace (Core) 	
Monolog (Core) 	
MultiSites (Core) 	
Overlay (Core) 	
PagePerformance (Core) 	
PrivacyManager (Core)
Referrers (Core) 	
Resolution (Core) 	
SEO (Core) 	
ScheduledReports (Core) 	
SegmentEditor (Core) 	
Tour (Core) 	
Transitions (Core) 	
TwoFactorAuth (Core) 	
UserCountry (Core) 	
UserCountryMap (Core) 	
UserId (Core) 	
UserLanguage (Core) 	
VisitFrequency (Core) 	
VisitTime (Core) 	
VisitorInterest (Core) 	
Visitor interest: number of pages viewed, time spent on the website, days since last visit, and more.
VisitsSummary (Core) 	

* Browser: Chrome, Firefox, Edge
* Operating System: Windows 11, Windows 10

**Comment by sgiehl** [comment]
Hi @tisonv. Thanks for creating this issue.
The pages reports are "truncated" to a certain amount of data. By default this should be 500 for the first level and 100 for all levels below. So if you are tracking a lot of different urls it can happen that some urls with low amount of visits is aggregated into the "Others" row. This makes it impossible to find the record using the table search as well.

In general when comparing data in Matomo against data in the database, please be aware that all data in the database is stored in UTC time. So depending on the timezone you have configured you might need to adjust them selected timeframe accordingly.

**Comment by tisonv** [comment]
Hi @sgiehl ! 
Thank a lot for your reply

I do not think this apply to my problem.
I can query pages with 1 or 2 page views without any problem while some with 500+ are missing.
I would not mind a slight gap between the UI and the db but this is too much to be ignored.

I do not see the "Others" row you're talking about.

**Comment by sgiehl** [comment]
It's really hard to dig into such problems as they can be anywhere. I don't know what exactly you are tracking nor how the tracking is implemented. Without having an exact way how to reproduce that, we likely won't be able to investigate and maybe fix it.
We have a dozens auf automatic tests that check if the tracked data is correctly aggregated into reports and there is currently no known problem around this topic.

**Comment by tisonv** [comment]
I understand
There is nothing off the basic internal site setup. No filter nor anything
Datas end up in the `matomo_log_link_visit_action` but is missing in the reports.

Is there a way to get a highly verbose log while computing the reports to see what is being aggregated or not ?

**Comment by peterbo** [comment]
@tisonv try -vvv as a parameter for archiving. This is the most verbose mode. See the "help output" on https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

**Comment by tisonv** [comment]
@peterbo -vvv is unhelpful as it prints only the calls to the Matomo API, not the actual archiving work.

I tried deleting the faulty actions from the database to see if they would appear when new calls are made but to no avail. ( the actions are still logged in the database)

I plugged the website to a new Matomo site (same matomo instance but new site with new id). It _may_ seem to work but I'll know in a couple of days when more datas will be available.

**Comment by tisonv** [comment]
> Hi @tisonv. Thanks for creating this issue. The pages reports are "truncated" to a certain amount of data. By default this should be 500 for the first level and 100 for all levels below. So if you are tracking a lot of different urls it can happen that some urls with low amount of visits is aggregated into the "Others" row. This makes it impossible to find the record using the table search as well.
 
hi @sgiehl 
You were indeed right.  
I never found the 'Others' before today. After upping it to 5.000, I was able to find all my missing statistics.

I find it rather counter-intuitive when Matomo is used in internal websites as opposed to news websites.
Our intranet is 10.000+ pages big and the need for statistics remains the same on every page all the time whether the page was viewed 1 or 1000+ times or 5 years old

Maybe it should be worth mentioning on the ["Intranet Website"](https://matomo.org/faq/how-to/faq_19/) documentation.


Thanks for your help !

**Comment by sgiehl** [comment]
Thanks for the hint. Might indeed be worth mentioning it there. 
@Stan-vw Shall we create an internal issue to cross link https://matomo.org/faq/how-to/faq_54/#faq_54 on the intranet documentation?

**Comment by Stan-vw** [comment]
We can make an internal issue, that's all good @sgiehl 
It's not 100% clear to me what the relation is between the two though, can someone help me to better understand the issue?

**Comment by sgiehl** [comment]
It might not be directly related. Maybe its also a general thing that people might not expect. Maybe we could also display that somewhere in Matomo itself, so people are aware that reports might be "truncated" after a certain amount of records and all remaining ones are grouped to a `Others` row.

**Comment by Stan-vw** [comment]
I'm not sure how people are missing that the bottom row literally says "Other", it'd be good to understand this better if that's a real problem that people are having (it's also pretty common practice in analytics tools, since otherwise tables/charts become unwieldy and/or unreadable).

Having had another look at it, I think I understand why you suggested the crosslink. I've added a section at the bottom of https://matomo.org/faq/how-to/faq_19/ that crosslinks to https://matomo.org/faq/how-to/faq_54/#faq_54

**Comment by tisonv** [comment]
As a new user, I missed the 'Other' row because I never unfold the whole "Pages". 
I was expecting to see the list every pages ever viewed on the selected time range (which can be a lot) so I didn't bother.
I just go there and click on the magnifier to find the pages I need from their ids.

Even if they're grouped on "Other" for display, I would have expected them to be searchable or have a at least have message saying "it exists but it's insignificant. Go to faq_54 if you so desire them".

**Comment by Stan-vw** [comment]
Thanks for sharing that, I'll have to have another look at it at some point.
I've added it to our list of UX elements to look at, and will keep my eyes open to see if this is a common issue.
