### ISSUE TITLE
There are unnecessary extra spaces in the generated campaign builder URL

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#21039]
## Expected Behavior

The URL should have no unnecessary characters, so that we can copy & paste without problems.

## Current Behavior

For the campaign builder code it adds extra spaces. See screenshot:
![image](https://github.com/matomo-org/matomo/assets/52564377/feab03d6-b08e-447d-a4b4-982dd8d47c1a)

Not sure if it also adds it for other places.

## Possible Solution

tbd

## Steps to Reproduce (for Bugs)

1. Go to acquisition > campaign builder
2. Make a campaign
3. Check the generated campaign URL

## Your Environment

* Matomo Version: 4.15 on sandbox

* Browser: Chrome
* Operating System: Mac

**Comment by Stan-vw** [comment]
@bx80 just checking, could this be related to the copy code button? No other changes to text fields come to mind

**Comment by bx80** [comment]
@Stan-vw This wasn't caused by the copy button itself, but an adjustment made to template markup on that page when implementing the copy button.  I've created a PR to fix this.
