### ISSUE TITLE
Transition window: text overflow

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#21048]
## Context
The text of the transition window overflows the box
![grafik](https://github.com/matomo-org/matomo/assets/1645099/117c2485-e0ec-4206-a040-a154e1891219)

## Steps to Reproduce (for Bugs)
Came from "page title" dashboard widget and clicked the transition icon
![grafik](https://github.com/matomo-org/matomo/assets/1645099/3ef8fb12-cb59-4fe5-a4b1-393f3ac1ea09)

## Your Environment
current matomo.org instance (cannot find any information about the version)

**Comment by sgiehl** [comment]
Hi @math-GH Thanks for reporting this issue. I was able to reproduce that one. I'll try to provide a small PR to fix this.
