### ISSUE TITLE
Allow Campaign tagging of a phone number.  Make clicking a phone number a channel

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21049]
A user suggests this feature. They saw it on Google Analytics first and it leverages Google's phone number forwarding. 
Our user says:

> 
> "I see it as a key feature because otherwise its impossible to tell if new leads that call the business are coming from the Marketing campaigns or not."
> 
> "When somebody sees a phone number on their screen and decides to call it on their phone, its more difficult to track because its not a click on the website, its a call made on a separate device. "
> 
> "By dynamically updating the phone number on the website to a forwarding number when a user enters the website via a Google Ad, the call is now trackable because any calls through that forwarding number must have come from the Google Ads campaign. Using Google Tag Manager, a marketer can actually have the phone number on a client's website dynamically update to a different forwarding number when a potential customer clicks through from a Google Search Ad."

**Comment by sgiehl** [comment]
@atom-box I'm actually not sure what exactly the expectations would be on this use case. What should Matomo do differently?
I guess with our Tag Manager it should also be possible to update certain html elements (like a phone number), depending on where the use came from.

**Comment by atom-box** [comment]
The user did not give a complete explanation. Maybe Matomo can already detect a clicked phone number, I don't know. I am closing this.
