### ISSUE TITLE
Segment definitions cannot contain "+" character, but there is no warning to user

### ISSUE THREAD

**Issue by ajpgross** [piwik/piwik#21058]
## Context
Users can add segment definitions that contain "+" characters (like contoso.com/Some,+url). Those characters are encoded and saved in the database then decoded here: https://github.com/matomo-org/matomo/blob/5.x-dev/core/Segment/SegmentExpression.php#L104

On the following couple of lines, the match will end in a new exception being thrown because of the way the regex is written. The "+" character is a special character within the context of the regex.

## Expected Behavior
The "+" character should work in this context or be disallowed at the start, via the segment editor on the GUI. It also appears that this URL was encoded 3 or 4 times.

## Current Behavior
Since the + character is allowed, it ends up being processed in the archiver, and the archiver will fail. Throws a trace that begins with 

```
Error: Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=***&period=year&date=2023-01-01&format=json&segment=pageUrl%3D%3Dhttps%25253A%25252F%25252Fcontoso.com%25252FSome%2525252C%25252Burl. Response was '{"result":"error","message":"The segment condition ' url' is not valid. #0 \/Segment.php(235): Piwik\\Segment\\SegmentExpression-&gt;parseSubExpressions() #1 \/Segment.php(163): Piwik\\Segment-&gt;initializeSegment('pageUrl==https:...', Array)

...
```

## Steps to Reproduce (for Bugs)
1. Create a segment for a URL that contains a "+" character. Note that in the scenario, the exact characters are ",+". It is possible the comma makes a difference.
2. Force archiving for that segment with something like `./console core:archive --force-idsegments=n`
3. Trace will be thrown in archiver logs

## Your Environment
* Matomo Version: 4.2.1
* PHP Version: 7.4.33

**Comment by sgiehl** [comment]
Hi @ajpgross. Thanks for reporting this issue. Are you still on Matomo 4.2.1. Did you maybe check if this error still occurs after updating to latest 4.15.0?

**Comment by ajpgross** [comment]
I only have access up to 4.14.2 at the moment, though I've also been working with Matomo support, who replicated the issue. More specifically, the issue occurs when a user adds a segment with an encoded comma, followed by a "+." So if the user pastes something like https://contoso.com/Some%2C+url

**Comment by ajpgross** [comment]
More research has led me to believe that something changed between 4.2.1 and 4.14.2. This may no longer be an issue. Thank you.
