### ISSUE TITLE
Some advanced options in tracking code generator do no longer work

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21063]
The 'Enable cross domain linking' option in Administration -> Measurabels -> Tracking code is not clickable regardless of having multiple URLs defined for the site...

![image](https://github.com/matomo-org/matomo/assets/20234985/a2ec3d09-af2d-4fca-97b8-20dc9b84a56f)

![image](https://github.com/matomo-org/matomo/assets/20234985/0a8d004d-43c8-40e5-bb91-cf49e35a04b1)

This was first in a Cloud 4.15 instance. Was unable to reproduce in an on-premise 4.14 version until upgrading to 4.15

Also, the label of the option should read "Enable ..." not "Enables ..."

**Comment by sgiehl** [comment]
That one seems to be a regression of #20834. I will look into it.
