### ISSUE TITLE
United States Location Map Should Include Alaska and Hawaii

### ISSUE THREAD

**Issue by jcolag** [piwik/piwik#21060]
## Summary
Currently, the "Locations" map for the United States shows the forty-eight contiguous states.  While the data can be found with some digging, this leaves out Alaska and Hawaii.  It would improve the map if those states appeared as insets on the US part of the map.

(Arguably, this qualifies as a bug, but it would certainly not rate more than a low-priority bug.)

## Your Environment
* Matomo Version: 4.15.0
* PHP Version:  8.2.7
* Server Operating System: Ubuntu
* Additionally installed plugins: CustomVariables (v4.1.3), IP2Location (v4.1.2), Provider (v4.0.5), ReferrersManager (v4.0.4), SecurityInfo (v4.0.2)

**Comment by sgiehl** [comment]
Thanks for reporting this one. Our maps are already quite outdated. Unfortunately we can't update them anymore, as the tool we previously used for that doesn't work anymore. We plan to create some new maps at some point as part of #11929 
I'll close this one, but it will be referenced in the other issue, so we can have an eye on it when we create new maps.
