### ISSUE TITLE
Fatal error: count(): Argument #1 ($value) must be of type Countable|array, string given in TrackerCodeGenerator.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21076]
See below for details 

> Error: {"message":"count(): Argument #1 ($value) must be of type Countable|array, string given","file":"\/core\/Tracker\/TrackerCodeGenerator.php","line":117,"request_id":"8dd7d","backtrace":" on \/core\/Tracker\/TrackerCodeGenerator.php(117)\n#0 \/core\/Tracker\/TrackerCodeGenerator.php(117): count('TEST')\n#1 \/plugins\/SitesManager\/API.php(161): Piwik\\Tracker\\TrackerCodeGenerator->generate('1', 'foo.ba...', false, false, false, '', 'TEST', '', '', false, false, false, false, '', false)\n#2 [internal function]: Piwik\\Plugins\\SitesManager\\API->getJavascriptTag('1', 'https:\/\/foo.bar...', false, false, false, '', 'TEST', '', '', false, false, false, false, false, '', false)\n#3 \/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#4 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#5 \/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#6 \/core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getJavascriptTa...', Array)\n#7 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#8 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#9 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#10 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#11 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#12 \/index.php(25):

> URL: /?module=API&method=SitesManager.getJavascriptTag&idSite=1&piwikUrl=&format=JSON&token_auth=XYZANONYMIZED&pageCustomVariables=TEST

> Referrer: None

> GET: {"module":"API","method":"SitesManager.getJavascriptTag","idSite":"1","piwikUrl":"","format":"JSON","token_auth":"XYZANONYMIZED","pageCustomVariables":"TEST","filter_limit":100}

**Comment by sgiehl** [comment]
The parameter `pageCustomVariables` expects an array. I'll update the API definition, so it will only use parameters with correct type.
