### ISSUE TITLE
Visitors > Overview: Visits Overview should reverse the Green + Red color for bounce rate (lower is better)

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21086]
**Expected**:
High bounce rate is displayed as a red dot, low bounce rate is displayed as a green dot

**Actual**:
Opposite; vice-versa.

![image](https://github.com/matomo-org/matomo/assets/22874146/6143a5a2-f9a6-456d-955b-c3fd6846f151)

**Comment by michalkleiner** [comment]
It's strange as anything starting with `bounce` or `exit` should automatically get the "lower value is better" treatment. Will investigate further why this might not work properly.

**Comment by sgiehl** [comment]
@michalkleiner The sparklines didn't respect that. But that should be fixed with https://github.com/matomo-org/matomo/pull/20795 in Matomo 5.

**Comment by michalkleiner** [comment]
Rightio. @atom-box can you confirm what version did you encounter this in?
@sgiehl should we backport the fix to 4.x-dev?

**Comment by sgiehl** [comment]
> @sgiehl should we backport the fix to 4.x-dev?

we should only backport security related stuff, or things causing trouble

**Comment by michalkleiner** [comment]
Ok. I'll wait to get the confirmation of the version this was spotted in, and if it was 4.x then we can close this as duplicate.

**Comment by atom-box** [comment]
Yes, it was in the current Cloud, so 4.15.0 at that time.

**Comment by michalkleiner** [comment]
Ok, thanks for the confirmation @atom-box. Since this is not a security issue the fix for that won't be backported to 4.x branch. It will get fixed when cloud moves to Matomo 5 in a few months.
