### ISSUE TITLE
Matomo tracking beacon not recording mtm_campaign, mtm_keyword (and others)

### ISSUE THREAD

**Issue by omert37** [piwik/piwik#21091]
Hello,
The Matomo tracking beacon/pixel doesn't record "mtm_campaign" and "mtm_keyword", it also does not record the others (piwik_campaign... piwik_keyword... etc...).
It only records URL and ACTION_NAME parameters.
Even though the official documentation says that it's supposed to work: <a href="https://matomo.org/faq/how-to/faq_25454/" target="_blank">https://matomo.org/faq/how-to/faq_25454/</a>.
Could someone please FIX OR tell me if I'm doing something wrong?

## Steps to Reproduce (for Bugs)

1. <img src="http://[MY MATOMO DOMAIN]/matomo.php?idsite=3&rec=1&bots=1&url=https%3A%2F%2Fexample.com%2Femail-opened%2Fnewsletter_XYZ&action_name=Email%20opened&mtm_campaign=internal%20email%20name&mtm_keyword=newsletter_XYZ" style="border:0;” alt="" />
2.

## Your Environment

* Matomo Version: 4.15.0
* PHP Version: 8.0.28
* Server Operating System: Ubuntu 22.04.4
* Additionally installed plugins:

* Browser: Chrome, Firefox, Explorer
* Operating System: Windows 10

**Comment by sgiehl** [comment]
Hi @omert37. Thanks for reporting this issue. We had implemented some changes around that lately and seems the instructions actually can't work that way. The campaign parameters are currently not considered when directly send as tracking parameters.
Instead you may need to attach them to the `url` that is provided as query parameters. That would need to be encoded correctly though. Something like this should work:

```
<img src="http://[MY MATOMO DOMAIN]/matomo.php?idsite=3&rec=1&bots=1&url=https%3A%2F%2Fexample.com%2Femail-opened%2Fnewsletter_XYZ%3Fmtm_campaign%3Dinternal+email+name%26mtm_keyword%3Dnewsletter_XYZ&action_name=Email%20opened" style="border:0;” alt="" />
```

We will check for an improvement from code side to make that working in the next release again.
