### ISSUE TITLE
Campaing Tracker doesn't recognize campaign urls

### ISSUE THREAD

**Issue by kathrinhpm** [piwik/piwik#21096]
Hello!
The matamo campaing tracker does not recognize the url with the campaign and kwd values I added to to the urls. 
e.g. url/?mtm_campaign=newshop&mtm_kwd=mailtastic
The visits to the url/?mtm_campaign=newshop&mtm_kwd=mailtastic are tracked when I go to behaviour/pages and select the url, but the campaign is not added to the aquistion/campaign page. 

I cannot find a mistake in the syntax. Can you help?

**Comment by michalkleiner** [comment]
Hi @kathrinhpm, thank you for reporting the issue. We already have similar issue logged (#21091) and we will have a fix ready shortly, a PR #21093 is currently in review.
I'll close this as a duplicate so please follow the process on the other issue. Thank you!
