### ISSUE TITLE
Matomo encountered an error: Call to a member function getIdSubDataTable() on bool (which lead to: Zend_Session is currently marked as read-only.

### ISSUE THREAD

**Issue by McSwizzlestix** [piwik/piwik#21095]
I get error 
`Matomo encountered an error: Call to a member function getIdSubDataTable() on bool (which lead to: Zend_Session is currently marked as read-only.`

When attempting to Download or Email Reports

**Comment by sgiehl** [comment]
Hi @McSwizzlestix. Thanks for creating this report. Could you provide some further details, that would help us recreating the issue?
* Which Matomo version are you using?
* Do you have additional plugins installed?
* Which reports are selected for the scheduled report?
* Does it maybe contain a report, that wouldn't contain any data?

**Comment by McSwizzlestix** [comment]
Sorry for the delay, you can actually close this, it turns out, my SMTP settings were off. Reports seem to function properly right now.
