### ISSUE TITLE
Configure subdomains through the main domain, to make subdomains more organized, manageable

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21100]
_This feature request is from a user who is asking for Matomo to organize domains and subdomains.  (Like maybe a hierarchical tree?)_

"**Question**: What is the one thing you’d like to see improved in Matomo and why?

**Answer**:
Managing sub-domains in a single measurable element.
To measure sub-domains, I have to create as many elements as sub-domains.
I would have liked to be able to set parameters to manage sub-domains in the main domain.

I manage several websites with this subdomains question. Hope you find out the way to do it "
;)

**Comment by michalkleiner** [comment]
Hi @atom-box, I'm not 100% sure I understand the enhancement request. Do you know what they mean by a measurable element? Do they mean widgets on the dashboard? Do they mean websites? You can already assign multiple domains and/or use subdomains to capture data together, so I'm not really sure what this enhancement is asking for.
Could you maybe go back to the user to ask for more details? Perhaps provide screenshots from Matomo UI with some annotations on what doesn't work or what they would like improved?
Thanks!

**Comment by atom-box** [comment]
_Hi_ @michalkleiner 

_The user wrote back, with more details. See below._

===========================================================

My idea is to be able to configure subdomains in Matomo through the main domain.

I have https://example.com/ and severals subdomains: https://one.example.com/, https://two.example.com/, three, four, five...
I would like to set up all the subdomain in one configuration. i.e "the numbers" ID:5 (which is the name of the measurable element, in this case:EXAMPLE) with URLs (one.example, two.example) instead of having each subdomain as mesurable element.
![image](https://github.com/matomo-org/matomo/assets/22874146/2608c116-1911-488f-8b0f-3a6ea9c57d8d)


As I have, "exclude...." (cf. the pic below), I imagine having "Include the URLs or subdomains you want to follow through the mesurable element ID" or a tutorial showing me the way to code this into the js for each subdomain...

![image](https://github.com/matomo-org/matomo/assets/22874146/e9827434-9ac4-405a-8662-7c439278bfbb)

So far, I tried to put few subdomains URLs here (see the next pic), But when I set up the code for each subdomain into WordPress, it refers to the main domain (ternalis.com)... which sounds logical actually ;)

![image](https://github.com/matomo-org/matomo/assets/22874146/12648b2e-ca05-4e75-993f-7fc3eb78779a)

**Comment by atom-box** [comment]
_The user continues:_

to explain more precisely:

What if I can set up a measurable element only with group of subdomains?

Means:

ID5: example.com

ID:6:
one.example.com
two.example.com
three example.com
four.example.com
five.example.com
...

ID7:
blablabla.example.com
bliblibli.example.com
blobloblo.example.com
...
...

**Comment by michalkleiner** [comment]
I think this is already supported when you enable the "Only track visits and actions when the action URL starts with one of the above URLs." option when configuring a new/existing website property.

With that, you can specify exact domains of any level (e.g. example.com is 2nd level, subdomain.example.com is 3rd level). Various numbers of domains can be specified and the tracking will only trigger when the URL starts with the domain, so not just based on where the tracking code is installed.

<img width="1217" alt="only exact domains" src="https://github.com/matomo-org/matomo/assets/233342/d8fd48cf-7f70-40a3-bbaf-c28e38b74439">

**Comment by atom-box** [comment]
@michalkleiner Thank you - yes you are correct.

I am closing this.

**Comment by atom-box** [comment]
This feature already exists in Matomo.
