### ISSUE TITLE
Page evolution chart URLs incorrect when choosing "Display a table with Goal metrics"

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21117]
When an evolution chart is viewed after selecting the chart option "Display a table with Goal metrics", the chart displays a URL without including subdirectories. The chart also appears to display results for these non-existent URLs (no data)...
![image](https://github.com/matomo-org/matomo/assets/20234985/63bdf8ca-f0c4-476a-8c5b-a46354a24ade)

Reproduced with on-premise and Cloud, v 4.15

### Steps to reproduce:

1. Go to Behaviour -> Pages
2. Choose the table option "Display a table with Goal metrics"
![Screenshot from 2023-08-04 11-46-20](https://github.com/matomo-org/matomo/assets/20234985/5a1027a1-ab85-411d-9a93-be04bfa649fe)

3. View an evolution chart for a page that is located in a subdirectory of the site
 ![image](https://github.com/matomo-org/matomo/assets/20234985/69195cd7-bdc0-4794-aff6-10bb5780b775)

If the Pages table is set to 'Make it flat' this does not occur.

**Comment by livebernd** [comment]
@sgiehl this row level evolution chart does still not work for me as notified you also via email

**Comment by sgiehl** [comment]
Hey @boerndtz 
This fix was added to Matomo 5. Matomo 5 is still in beta and will be released within the next weeks.
