### ISSUE TITLE
4.15.1 Docker build amd64 broken

### ISSUE THREAD

**Issue by martinhaye** [piwik/piwik#21124]
Tried last night to upgrade from 4.15.0 to 4.15.1, and discovered that the official Matomo Docker image for 4.15.1 amd64/linux doesn't seem to exist. Looking at https://hub.docker.com/r/amd64/matomo/ I see "amd64/matomo build status" is "unstable".

I don't know enough about Docker to help with debugging the build.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/docker-images-for-4-15-1-are-incomplete-in-os-support/52641/2

**Comment by michalkleiner** [comment]
Thanks for reporting the issue @martinhaye. I'll transfer it to the correct repository, as it's unrelated to Matomo (the product) itself.

**Comment by michalkleiner** [comment]
Seems like I can't transfer it, @sgiehl can you help? Thanks.

**Comment by sgiehl** [comment]
I don't have permission to the docker repo as well. Guess @tsteur needs to handle it.

**Comment by iamspido** [comment]
I've already created an issue under https://github.com/matomo-org/docker/issues/330

**Comment by michalkleiner** [comment]
Closing as a duplicate.

**Comment by martinhaye** [comment]
Thanks @michalkleiner for pointing me to the correct repo for future reference.
