### ISSUE TITLE
Problem with archiving function

### ISSUE THREAD

**Issue by foxiyu** [piwik/piwik#21121]
## Context

The last successful run of the archive was on Tuesday, April 4, 2023 at 09:05:03, 121 days before 21:41:51.

## Current Behavior

I followed the prompts to execute /matomo/console -- matomo domain=[my domain] core: archive

The following error occurred：

/matomo/console --matomo-domain=[my domain] core:archive

PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0
INFO [2023-08-04 07:03:07] 19357 ---------------------------
INFO [2023-08-04 07:03:07] 19357 INIT
INFO [2023-08-04 07:03:07] 19357 Running Matomo 4.15.1 as Super User
INFO [2023-08-04 07:03:07] 19357 ---------------------------
INFO [2023-08-04 07:03:07] 19357 NOTES
INFO [2023-08-04 07:03:07] 19357 - Async process archiving supported, using CliMulti.
INFO [2023-08-04 07:03:07] 19357 - Reports for today will be processed at most every 900 seconds. You can change this value in Matomo UI > Settings > General Settings.
INFO [2023-08-04 07:03:07] 19357 - Archiving was last executed without error 121 days 21 hours ago.
INFO [2023-08-04 07:03:07] 19357 - Continuing ongoing archiving run by pulling from shared idSite queue.
INFO [2023-08-04 07:03:07] 19357 ---------------------------
INFO [2023-08-04 07:03:07] 19357 START
INFO [2023-08-04 07:03:07] 19357 Starting Matomo reports archiving...
INFO [2023-08-04 07:03:07] 19357 Start processing archives for site 4.
INFO [2023-08-04 07:03:09] 19357 'PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0
{"idarchives":[1061],"nb_visits":3}'
ERROR [2023-08-04 07:03:09] 19357 Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=4&period=day&date=2023-08-02&format=json&trigger=archivephp: 'PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0 {"idarchives":[1061],"nb_visits":3}'
INFO [2023-08-04 07:03:09] 19357 'PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0
{"idarchives":[441],"nb_visits":3}'
...........................
ERROR [2023-08-04 07:03:22] 19357 Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=4&period=year&date=2023-01-01&format=json&trigger=archivephp: 'PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0 {"idarchives":[73955],"nb_visits":60}'
INFO [2023-08-04 07:03:22] 19357 Finished archiving for site 4, 24 API requests, Time elapsed: 14.725s [1 / 1 done]
INFO [2023-08-04 07:03:22] 19357 Done archiving!
INFO [2023-08-04 07:03:22] 19357 ---------------------------
INFO [2023-08-04 07:03:22] 19357 SUMMARY
INFO [2023-08-04 07:03:22] 19357 Processed 0 archives.
INFO [2023-08-04 07:03:22] 19357 Total API requests: 24
INFO [2023-08-04 07:03:22] 19357 done: 24 req, 14790 ms, 24 errors.
INFO [2023-08-04 07:03:22] 19357 Time elapsed: 14.790s
INFO [2023-08-04 07:03:22] 19357 ---------------------------
INFO [2023-08-04 07:03:22] 19357 SCHEDULED TASKS
INFO [2023-08-04 07:03:22] 19357 Starting Scheduled tasks...
INFO [2023-08-04 07:03:22] 19357 Scheduler: executing task Piwik\Plugins\CustomJsTracker\Tasks.updateTracker...
INFO [2023-08-04 07:03:22] 19357 Scheduler: finished. Time elapsed: 0.011s
INFO [2023-08-04 07:03:22] 19357 Scheduler: executing task Piwik\Plugins\TagManager\Tasks.regenerateReleasedContainers...
INFO [2023-08-04 07:03:22] 19357 Scheduler: finished. Time elapsed: 0.015s
INFO [2023-08-04 07:03:22] 19357 Scheduler: executing task Piwik\Plugins\PrivacyManager\Tasks.deleteLogData...
INFO [2023-08-04 07:03:22] 19357 Scheduler: finished. Time elapsed: 0.008s
INFO [2023-08-04 07:03:22] 19357 Scheduler: executing task Piwik\Plugins\PrivacyManager\Tasks.anonymizePastData...
INFO [2023-08-04 07:03:22] 19357 Scheduler: finished. Time elapsed: 0.001s
INFO [2023-08-04 07:03:22] 19357 done
INFO [2023-08-04 07:03:22] 19357 ---------------------------
INFO [2023-08-04 07:03:22] 19357 ---------------------------
INFO [2023-08-04 07:03:22] 19357 SUMMARY OF ERRORS
INFO [2023-08-04 07:03:22] 19357 Error: Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=4&period=day&date=2023-08-02&format=json&trigger=archivephp: 'PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0 {"idarchives":[1061],"nb_visits":3}'
............................
INFO [2023-08-04 07:03:22] 19357 Error: Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=4&period=year&date=2023-01-01&format=json&trigger=archivephp: 'PHP Warning: Missing arginfo for bt_echo() in Unknown on line 0 {"idarchives":[73955],"nb_visits":60}'
ERROR [2023-08-04 07:03:22] 19357 24 total errors during this script execution, please investigate and try and fix these errors.
ERROR [2023-08-04 07:03:22] 19357 Uncaught exception: /matomo/core/CronArchive.php(631): 24 total errors during this script execution, please investigate and try and fix these errors. [Query: , CLI mode: 1]

[Exception]
24 total errors during this script execution, please investigate and try and fix these errors.

core:archive [--url="..."] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--skip-segments-today] [--force-periods[="..."]] [--force-date-last-n[="..."]] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--max-websites-to-process="..."] [--max-archives-to-process="..."] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]] [--force-all-websites] [--force-report[="..."]]

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:4.15.1
* PHP Version:8.1.17 (cli) (built: May 12 2023 09:21:55) (NTS)
* Server Operating System:CentOS Linux 7
* Additionally installed plugins:

* Browser:Egde
* Operating System:WIN10

**Comment by sgiehl** [comment]
Hi @foxiyu 
This error actually seems unrelated to Matomo. Matomo does not have any method called `bt_echo`.
I found similar error records for Flarum: https://www.google.com/search?q=%22Missing+arginfo+for+bt_echo%28%29%22
Are you maybe using that one?
In any case it might help to disable the screen writer for error logs in the matomo config, so the errors aren't printed to the document, but instead logged to a file. If that already is the case, you might have `display_errors` enabled in your php config maybe.
