### ISSUE TITLE
Custom reports apply to certain SiteIDs

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#21130]
Had an interesting feature request from a customer "When a custom report is made, I can not choose in one take to distribute the report into 3 out of 7 websites, for whom it's relevant for. Could be great if the "apply to" feature could handle a selection of entities".

Currently a custom report can be applied to an **individual** website or to **All Websites**.

This feature has also been mentioned on the Matomo forums and would be a useful addition.

"When creating a custom report you can choose to what website the report should apply to. You can choose between a specific website or all website. We would like to select multiple websites, but not all."

"I would really appreciate this feature: we use an installation with more than hundred site IDs. We need half a dozen custom reports for a group of round about 30 site IDs. Another group of site IDs can be seen by customer accounts, but I don’t want them to see the custom reports of the first group."

**Comment by sgiehl** [comment]
Hey @goochj03
please create internal issues for feature requests around custom reports.
