### ISSUE TITLE
I can't become a "Matomo expert" because it fails to detect my added website

### ISSUE THREAD

**Issue by Normandygirl** [piwik/piwik#21134]
In my "become a Matomo expert", it lists I should "create a website" and yet this is something I already did. 
![Screenshot 2023-08-08 at 15 56 48](https://github.com/matomo-org/matomo/assets/141650307/1c67b9bf-dfa1-4105-9f3d-d9773bfe2276)
![Screenshot 2023-08-08 at 15 57 06](https://github.com/matomo-org/matomo/assets/141650307/e3daf8b6-9599-46e0-ac8f-898c4913902f)

**Comment by bx80** [comment]
Hi @Normandygirl, thanks for reporting this.

 The [check for adding a website](https://github.com/matomo-org/matomo/blob/76429dce259ea03b751cd760ad1362b0562db1c0/plugins/Tour/Dao/DataFinder.php#L27) only returns true if there exists a website that doesn't have site id 1 and it was added by the currently logged in user. So the wording 'Add a website' is misleading here as it's really checking for an additional website other than the first one. It should perhaps read  'Add another website'. We'll look at improving this to make it less confusing!

**Comment by bx80** [comment]
@Stan-vw This technically isn't a regression as the check has worked this way since the plugin was original written in 2019.

**Comment by Stan-vw** [comment]
Ah right. Let's fix this then by rewording to "Add another website" or "Add a second website" (any preferences by anyone?)

**Comment by Normandygirl** [comment]
I vote "add another website".
Merci!
