### ISSUE TITLE
HTTP Error 500 when running import_logs.py

### ISSUE THREAD

**Issue by greneit** [piwik/piwik#21135]
## Context
I have a self hosted matomo installation stats.xyz.com on a VPS and I have another server running a website abc.com. I am copied import_logs.py from https://github.com/matomo-org/matomo-log-analytics/ to abc.com in the directory /mnt

Now when I run this command:
` python3 /mnt/import_logs.py --url='https://stats.abc.com' --token-auth=1234434343 --debug-tracker --enable-http-errors --enable-http-redirects --enable-static --enable-bots --idsite=1 /home/logs/log.log`

I get the 500 error

## Current Behavior
`Parsing log /home/logs/log.log...
2023-08-08 17:06:31,378: [INFO] Error when connecting to Matomo: HTTP Error 500: Internal Server Error
2023-08-08 17:06:31,378: [INFO] Retrying request, attempt number 2
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
2023-08-08 17:06:41,493: [INFO] Error when connecting to Matomo: HTTP Error 500: Internal Server Error
2023-08-08 17:06:41,493: [INFO] Retrying request, attempt number 3
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
26 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
2023-08-08 17:06:51,606: [INFO] Error when connecting to Matomo: HTTP Error 500: Internal Server Error
2023-08-08 17:06:51,606: [INFO] Max number of attempts reached, server is unreachable!
Fatal error: HTTP Error 500 Internal Server Error, response: 
You can restart the import of "/home/logs/log.log" from the point it failed by specifying --skip=24 on the command line.
`

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 4.15.1
* PHP Version: 8.0
* Server Operating System: Ubuntu 20.0
* Additionally installed plugins:

* Browser: firefox
* Operating System: ubuntu 22.04

**Comment by michalkleiner** [comment]
Hi @greneit,
we are sorry to hear that you are having trouble with the import.

Unfortunately there can be many reasons why this might not work for you. This problem is most likely unique to your particular configuration. You might be able to get some help with investigating your issue by searching and/or asking on our forums at https://forum.matomo.org/. 

The best place to start would be to look into the webserver logs for the Matomo instance to see what the stacktrace for the HTTP 500 error is and/or where it comes from.

I will close the issue for now but feel free to open a new one if you think there is a problem with Matomo itself and you can provide reliable replication steps.

Thank you for your understanding.
