### ISSUE TITLE
Transitions shows search engines providers as 'Unknown'

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21143]
When looking at the Transitions report in Behaviour -> Pages, the search engine providers are listed as 'Unknown'...
![image](https://github.com/matomo-org/matomo/assets/20234985/5fffb19f-0fb9-45b8-94a8-8454e5ce0a98)

I can reproduce this in Cloud and on-premise.

The actual search engine referrer appear in the segmented visitor's log in the Pages report for the same URL.

**Comment by michalkleiner** [comment]
Hi @9joshua, can you please provide the name of the search engine if it's not a sensitive information? Or does it happen with all search engines?

**Comment by 9joshua** [comment]
@michalkleiner In the example above the search engine was Google. this was also produced with a combination of Baidu and Google. Seems to happen will all search engines.

**Comment by sgiehl** [comment]
@9joshua Were you looking at a report from a recent day/period or was it for an older date? The Transition report uses log data, so if e.g. log data is anonymized after a certain amount of time, older dates might show unknown in that case.

**Comment by 9joshua** [comment]
@sgiehl I reproduced this using reports from the previous day and the current month.

**Comment by sgiehl** [comment]
Hey @9joshua. I just had a closer look again. The entries shown for search engines in the traansitions report are actually the keywords used for search and not the search engines itself. As most search engines do no longer provide the keywords it's kind of expected that it shows unknown.
But it could maybe make sense to show the list of search engines there instead, as the keywords are no longer useful.

**Comment by 9joshua** [comment]
Because keywords can be available if they are imported, maybe just clarifying that 'Unknown' refers to keywords would be sufficient.

**Comment by sgiehl** [comment]
@9joshua Imported keywords can't be displayed in that view, as they are not related to a certain page. So even with imported ones, it would state unknown there. Imho it would be more helpful to display the search engine names there.

**Comment by 9joshua** [comment]
@sgiehl Good point. I agree that the name of the search engine would provide better insight.

**Comment by mit2sumit** [comment]
Hi Guys, I also stumbled upon this issue now, after a recent migration from GA4 to on-premise setup of matomo. Being a developer, I was looking for the issue but found this on-going thread. Just raised my hands-up here to report it and have it fixed. Thanks.
![image](https://github.com/matomo-org/matomo/assets/5330405/2d50f104-026a-49a1-8339-6a504aa79deb)

**Comment by goochj03** [comment]
Have had another customer today asking about "Unknown" showing in the Transitions report. Search engine name would be good to show here.

**Comment by sgiehl** [comment]
@Stan-vw This would be a quite small change, but maybe with a lot more value. I've created a small draft PR in a couple of minutes, which would change that. Let me know if this change makes sense to you. I would then finish up the PR, so it can be merged into the next minor release.

**Comment by Stan-vw** [comment]
@sgiehl if you already have half the work done, then by all means 😅
