### ISSUE TITLE
Matomo 4.14.2: Page Overlay does not work, seems to be endless loading

### ISSUE THREAD

**Issue by gunnarsymbolic** [piwik/piwik#21140]
Dear Matomo support team,

We cannot make the Page Overlay function work. It always seems to be endless loading, but nothings happens at all. We already read and evaluated the troubleshooting hints, tried different browsers and even installed it on a subdomain without any cookie blocking, but nothing ever changes.

We are using Matomo 4.14.2 on a web server with the latest PHP version.
We would bei grateful for every further hint you could give us.

Environment:
* Matomo Version: 4.14.2
* PHP Version: 8.2
* Server Operating System: Linux
* Browser: Firefox, Chrome, Edge (each in latest versions)
* Operating System: Windows 10, Windows 11

Thank you in advance.

Kind regards,
Gunnar

**Comment by michalkleiner** [comment]
Hi @gunnarsymbolic, thanks for raising the issue. Can you check/confirm if there there are any errors in browser console perhaps or in the network tab, any failed requests?

**Comment by michalkleiner** [comment]
Alternatively we'd recommend trying on latest Matomo 4.15 and see if that changes anything.

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. @gunnarsymbolic If you still experience problems with the overlay feature this troubleshoot might help you solve the problems: https://matomo.org/faq/reports/troubleshoot-page-overlay-issues/
