### ISSUE TITLE
Search bar visibility when searching Pages

### ISSUE THREAD

**Issue by enual** [piwik/piwik#21147]
Customer notice that our Search bar under Behaviour > Pages can be improved by making it visible and moving it on the top part instead at the bottom, The search bar will only appear if you drag your mouse at bottom and click the magnifying icon.

Sample screenshot.
![image](https://github.com/matomo-org/matomo/assets/132400623/70e45020-9ae4-4a2d-a73b-b5582a239544)

**Comment by michalkleiner** [comment]
Thanks for creating the ticket @enual.
There's definitely a potential for making the UI more usable, having some elements visible at all times (not just on hover/click) etc.
It'd be up to the product team to decide on the priorities and/or whether this can be bunched with some other improvements — thank you for your understanding on this.

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
There were quite a few issues with the same theme: https://github.com/matomo-org/matomo/issues/6362 https://github.com/matomo-org/matomo/issues/15873 https://github.com/matomo-org/matomo/issues/19669 https://github.com/matomo-org/matomo/issues/21147 https://github.com/matomo-org/matomo/issues/19355
i'll mark this as closed in favor of this issue: https://github.com/matomo-org/matomo/issues/19669
