### ISSUE TITLE
[PHP 8.3 compatibility] WARNING: Deprecated - Calling get_class() without arguments

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#21141]
From https://forum.matomo.org/t/deprecated-warning-messages-matomo-4-15-1-php-8-3-0/52760
 - [ ] WARNING: /core/Plugin.php(163): Deprecated - Calling get_class() without arguments is deprecated - Matomo 4.15.1 - (Module: CoreHome, Action: index, In CLI mode: false)
 - [ ] WARNING: /core/Plugin.php(163): Deprecated - Calling get_class() without arguments is deprecated - Matomo 4.15.1 - (Module: Installation, Action: getSystemCheck, In CLI mode: false)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecated-warning-messages-matomo-4-15-1-php-8-3-0/52760/2

**Comment by sgiehl** [comment]
Hey @heurteph-ei 
Thanks for reporting this one. I'll prepare a fix for it.
