### ISSUE TITLE
Problem with hybrid approach to track 100% of the ecommerce conversion 

### ISSUE THREAD

**Issue by DelphineRD** [piwik/piwik#21153]
## Context
We followed the hybrid approach to track 100% of the ecommerce conversion.

We can see in our e-commerce platform that all the sales are sent to Matomo successfully. But we are missing sales in Matomo's ecommerce reports.

We are not sure if the cookies are causing the problem, but when we look at the segment of users who didn’t accept cookies, there are no e-commerce conversions recorded in Matomo reports. 
We carried out tests under authentic booking conditions, both with and without cookies, within the development environment, and the outcome was as expected. 
However, the concern arises exclusively when an order is executed in the production environment, resulting in some orders not being recorded and subsequently failing to appear in Matomo's report.

We have implemented the cookie consent functionality with Cookiebot and server-side tracking for ecommerce interactions in our self-hosted Matomo instance. We have followed the guidelines provided in Matomo's documentation. However, despite our efforts, we are still experiencing limitations in capturing all ecommerce interactions in Matomo's reports, apparently for users who have explicitly denied the use of analytics cookies.
https://matomo.org/faq/how-to/measure-100-of-ecommerce-interactions-using-server-side-tracking/

Our server-side implementation is working perfectly otherwise, we check that the information is sent to the Matomo server each time. We used [Matomo’s PHP SDK](https://fr.matomo.org/faq/how-to/measure-100-of-ecommerce-interactions-using-server-side-tracking/#:~:text=your%20secret%20token_auth-,When%20using%20our%20PHP%20SDK%2C%20the%20code%20will%20look%20like%20this%3A,-//%20it%20is%20assumed%20that%20%24order)

The goals, which are set up with JavaScript tracking, are recording as expected even when cookie consent has been denied, but the server-side tracking for Ecommerce conversions is not functioning when cookies consent has been denied. In this article, it is said despite the tracking being "cookie-less," the goals and conversions themselves are still recorded (the attribution process, however, is impacted)   https://matomo.org/faq/general/faq_156/

Are there settings we should change in Matomo to see 100% of the ecommerce interactions? 

## Environment

* Matomo Version: 4.15.1
* PHP Version: 8.2.8
* Server Operating System:Linux Ubuntu server 22.04

#### Matomo Version:
 4.15.1

#### Plugins Activated:
 API, AbTesting 4.2.6, Actions, ActivityLog 4.1.2, AdvertisingConversionExport 4.1.3, Annotations, AnonymousPiwikUsageMeasurement 4.1.0, Bandwidth 4.0.5, BulkTracking, Cohorts 4.0.8, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomAlerts 4.1.0, CustomDimensions, CustomJsTracker, CustomReports 4.1.7, CustomVariables 4.1.3, DBStats, Dashboard, DeviceDetectorCache 4.3.1, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, ExampleAPI, ExampleCommand, ExampleLogTables, ExamplePlugin, ExampleReport, ExampleSettingsPlugin, ExampleTracker, ExampleUI, ExampleVisualization, ExampleVue, Feedback, FormAnalytics 4.4.3, Funnels 4.1.6, GeoIp2, Goals, GoogleAnalyticsImporter 4.6.10, Heartbeat, HeatmapSessionRecording 4.5.10, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, InvalidateReports 4.1.1, LanguagesManager, Live, LogViewer 4.1.2, Login, LoginLdap 4.7.3, MarketingCampaignsReporting 4.1.3, Marketplace, MediaAnalytics 4.2.1, MobileAppMeasurable, MobileMessaging, Monolog, Morpheus, MultiChannelConversionAttribution 4.3.2, MultiSites, Overlay, PagePerformance, PrivacyManager, Provider 4.0.5, Proxy, QueuedTracking 4.0.7, Referrers, Resolution, RollUpReporting 4.1.3, RssWidget, SEO, SEOWebVitals 4.0.4, ScheduledReports, SearchEngineKeywordsPerformance 4.5.5, SecurityInfo 4.0.2, SegmentEditor, SitesManager, TagManager, TasksTimetable 4.0.2, TestRunner 0.1.0, Tour, TrackingSpamPrevention 4.1.7, Transitions, TreemapVisualization 4.0.2, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersFlow 4.1.1, UsersManager, VisitFrequency, VisitTime, VisitorGenerator 4.0.7, VisitorInterest, VisitsSummary, WebsiteMeasurable, WhiteLabel 4.0.8, Widgetize

**Comment by michalkleiner** [comment]
Hi @DelphineRD,
thank you for taking the time to create the issue with all the details.
Unfortunately we don't provide user support/answer configuration questions through the issue tracker.
We only accept feature requests or bug reports with clear replication steps.
We recommend asking the question in our forum at https://forum.matomo.org/.
Thank you for your understanding.

**Comment by DelphineRD** [comment]
This isn't about a configuration inquiry; rather, I'm seeking reassurance that there isn't a bug involving server-side ecommerce tracking and cookie consents within Matomo's system.
