### ISSUE TITLE
Goals by Pages reports show no conversions prior to 12 months back

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21150]
The _Goals by Pages_ reports appear to have no conversion data for historical periods prior to 12 months back.

This is seen in Cloud and on-premise.
For example at https://demo.matomo.cloud, selecting July 2022 in the calendar and then viewing **Goals -> Overview -> Goals by Pages -> Page titles** shows no conversions...
![image](https://github.com/matomo-org/matomo/assets/20234985/6bcd4f34-5867-434f-bb07-da4390c8839f)

The same report for August 2022...

![image](https://github.com/matomo-org/matomo/assets/20234985/b788730a-80d8-47ea-8d97-0e5390212838)

**Comment by sgiehl** [comment]
@9joshua This feature has been developed somewhen last year, so I guess we simply might not have re-processed older reports. 
@bx80 correct me if I'm wrong

**Comment by bx80** [comment]
Yes, that's correct, unless the `core:calculate-conversion-pages` update has been run for historic data and those older reports have been invalidated/reprocessed then there won't be any data prior to about the 4.12 / 4.13 / 4.14 release.

**Comment by sgiehl** [comment]
Closing this one. As it kind of expected behavior then.
