### ISSUE TITLE
When updating a scheduled report, page title says "Create a report"

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21188]
This is on Matomo 5.

To reproduce create a report, then click on "edit".

You will see the title is as following:

<img width="630" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/33a55599-25c8-4532-95ad-4f6801cfeb52">

It confused me that I'm creating a new report when I was updating the report.

**Comment by sgiehl** [comment]
Had a quick look. The button text of the save button is actually also incorrect. It says update when creating a report and create when updating one. Seems to be a regression from converting to vue. I'll prepare a PR to fix it.
