### ISSUE TITLE
Schedule reports UI shows wrong action button labels

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21187]
See below screenshot. 

When creating a report, it says "Update report". When updating a report, it says "Create report".
<img width="531" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/e1f90fa2-7e09-4784-9dae-34e6d169c6c3">

This is on Matomo 5. Not sure if it's also a bug on Matomo 4.

**Comment by sgiehl** [comment]
fixed with #21194
