### ISSUE TITLE
Detect bots by their provider

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#21183]
Detect the provider of the IP address and use that to mark AWS traffic as bots.

## Summary

Hello everyone!

Many bots do not state their name in the user agent string, they provide a fake agent to avoid detection. This causes problems for us who use the matomo API to directly count hits (and not the javascript code), because all these bots go undetected.

Here is an example of such a bot:
```
54.212.192.249 [13:11:20] "GET / 12912 "" "(X11; Linux x86_64) AppleWebKit/537.36 Chrome/83.0.4103.97 Safari/537.36"
```

It would be great if we could use the existing infrastructure for IP location, to detect the provider/data centre of the IP address and mark all AWS traffic (and other similar sources) as bots.

Thank you!

## Your Environment

* Matomo Version: 4.15.1
* PHP Version: 8.0.27
* Server Operating System: AlmaLinux 8.8
* Additionally installed plugins: none

**Comment by michalkleiner** [comment]
Hi @LauraTaylorUK,
thank you for the suggestion. I'm not sure it's as simple as it may sound. I don't think it's that easy to detect and block large cloud providers like AWS and Azure or GCP with their large ranges of IP addresses, you could as well limit legitimate visitors from the same IP range.
I would suggest engaging with the author of the [BotTracker plugin](https://plugins.matomo.org/BotTracker) through their GitHub issues tracker and seeing if this can be done there as an enhancement, or perhaps building a new plugin specifically for your use case.
Thank you for your understanding.

**Comment by sgiehl** [comment]
There is actually the plugin https://plugins.matomo.org/TrackingSpamPrevention, which should allows to block requests from cloud providers.
