### ISSUE TITLE
Export of weekly period should not use comma separated values

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#21193]
Hi team,

When we export a report on a weekly period, then the date period are exported in this format "date1,date2" for the first column resulting in postponing all the values of all the other columns.
So we need to always fix back the csv by hand.
Could you please use another separator than a comma to separate the dates of the week?

Thank you,

**Comment by bx80** [comment]
Hi @Chardonneaur, 
I didn't manage to recreate this when exporting CSV reports from the UI for a week or date range, would it be possible for you provide a bit more information about the export settings and period selection you are using for the export when this occurs? A copy of the export URL would be useful. Thanks!

**Comment by Chardonneaur** [comment]
Hi @bx80 
Sure:
https://demo.matomo.cloud/index.php?module=API&format=CSV&idSite=1&period=week&date=2023-03-06,2023-09-03&method=API.get&filter_limit=100&format_metrics=1&expanded=1&translateColumnNames=1&language=en&token_auth=anonymous
just try to get from this file an Excel file with corresponding columns.

**Comment by sgiehl** [comment]
@Chardonneaur This works without problems. You need to define `,` a separator and `"` as encapsulation char when loading the CSV in Excel. Any value in the CSV that contains a `,` is encapsulated with `"`, so this strictly follows the CSV definitions.
Directly opening a CSV file in Excel will never work though, as Excel by default looks for tab or `;` as far as I remember.

**Comment by Chardonneaur** [comment]
sorry i should be tired, it makes sense to export is a tsv instead, sorry for that.
