### ISSUE TITLE
* Error Dernière exécution d'archivage réussie: error

### ISSUE THREAD

**Issue by paulrouf** [piwik/piwik#21206]
No data showing since many month.
Here is the system report (only partial as too long to paste here)
Anyone can help ?
thanks!!

			  # Errors

* Error Dernière exécution d'archivage réussie: error  (L'archivage s'est exécuté avec succès le Jeudi 26 janvier 2023 02:22:12 soit il y a 216 jours 10:19:20 )

# Matomo

* Version de l’extension Matomo: 4.15.0
* Config existe et est accessible en écriture.: Oui ("$abs_path/wp-content/uploads/matomo/config/config.ini.php" )
* JS Tracker existe et est accessible en écriture.: Oui ("$abs_path/wp-content/uploads/matomo/matomo.js" )
* Répertoires de l’extension: Yes ([{"pluginsPathAbsolute":"$abs_path\/wp-content\/plugins\/matomo\/plugins","webrootDirRelativeToMatomo":"..\/"}])
* Répertoire temporaire accessible en écriture: Yes ($abs_path/wp-content/cache/matomo)
* Version de Matomo: 4.15.0
* idSite du site web Matomo: 1
* Version installée de Matomo: 4.13.0 (Install date: 2022-12-15 14:15:01)
* Upgrades outstanding: No
* Upgrade in progress: No

## Endpoints

* Matomo JavaScript Tracker URL:  ($site_url/wp-content/uploads/matomo/matomo.js)
* Matomo JavaScript Tracker - WP Rest API:  ($site_url/wp-json/matomo/v1/hit/)
* Matomo HTTP Tracking API:  ($site_url/wp-content/plugins/matomo/app/matomo.php)
* Matomo HTTP Tracking API - WP Rest API:  ($site_url/wp-json/matomo/v1/hit/)

## Crons

* Heure du serveur: 2023-08-30 12:41:33
* Heure du site web: 2023-08-30 14:41:33 (Les dates ci-dessous sont affichées dans le fuseau horaire du site web)
* Sync users & sites: Next run: 2023-08-30 15:20:26 (38 min 53s) ( Last started: 2023-08-29 15:27:44 (-23 heures 13 min). Last ended: 2023-08-29 15:27:44 (-23 heures 13 min). Interval: daily)
* Archive: Next run: 2023-08-30 15:15:05 (33 min 32s) ( Last started: 2023-08-30 14:21:16 (-20 min 17s). Last ended: 2023-08-30 14:25:24 (-16 min 9s). Interval: hourly)
* Update GeoIP DB: Next run: 2023-09-11 15:20:26 (12 jours 0 heures) ( Last started: 2023-08-12 15:22:31 (-17 jours 23 heures). Last ended: 2023-08-12 15:22:34 (-17 jours 23 heures). Interval: matomo_monthly)

## Contrôles obligatoires

* Version PHP >= 7.2.5: ok 
* PDO extension: ok 
* PDO\MYSQL extension: ok 
* MYSQLI extension: ok 
* Autres extensions requises: ok 
* Fonctions requises: ok 
* Configuration PHP requise (php.ini): ok 
* Répertoires avec les droits d'accès en écriture: ok 
* Répertoires avec accès en écriture pour Gestionnaire de balises: ok 

## Contrôles facultatifs

* Binaire PHP 64 bits: ok 
* État du traqueur: ok 
* Limite mémoire: ok 
* Fuseau horaire: ok 
* Ouvrir l'URL: ok 
* GD > 2.x + FreeType (graphics): ok 
* Autres extensions: ok 
* Autres fonctions: ok 
* Warning Système de fichiers: warning  (Votre serveur utilise un système de fichier NFS. Cela signifie que Matomo va être très lent lors de l'utilisation des sessions basées sur des fichiers. )
* Error Dernière exécution d'archivage réussie: error  (L'archivage s'est exécuté avec succès le Jeudi 26 janvier 2023 02:22:12 soit il y a 216 jours 10:19:20 )
* Capacités de la base de données: ok 
* Warning Taille maximale des paquets: warning  (Il est important de configurer une taille 'max_allowed_packet' dans votre base de données MySQL d'au moins 64MB. 32MB configuré en ce moment. )
* Géolocalisation: ok 
* Mettre à jour via HTTPS: ok 
* Supports Async Archiving: Yes
* Location provider ID: geoip2php
* Location provider available: Yes
* Location provider working: Yes
* Warning Proxy header: HTTP_X_FORWARDED_FOR (Un en-tête de proxy est défini, ce qui signifie que vous devrez peut-être configurer un en-tête de proxy dans les réglages avancés pour que les rapports de localisation fonctionnent. Si la localisation est détecté correctement dans vos rapports, vous pouvez ignorer cet avertissement. <a href="https://matomo.org/faq/wordpress/how-do-i-fix-the-proxy-header-warning-in-the-matomo-for-wordpress-system-report/" target="_blank">En savoir plus</a>)
* Had visit in last 5 days: Yes
* Matomo URL: Yes ($site_url/wp-content/plugins/matomo/app/)

## Matomo Settings

* Track mode: default
* Track codeposition: footer
* Track api endpoint: default
* Track js endpoint: default
* Version history: 4.15.0, 4.14.2, 4.13.0
* Core version: 4.15.0
* Last tracking settings update: 1693389005
* Last settings update: 1693389005
* Show get started page: 0
* Track ecommerce: No

## Logs

* Warning archive_main: 2023-08-30 12:19:54 (516 total errors during this script execution, please investigate and try and fix these errors. => CronArchive.php:631; CronArchive.php:624; CronArchive.php:278; Access.php:670; CronArchive.php:282; ScheduledTasks.php:332; class-wp-hook.php:308; class-wp-hook.php:334; plugin.php:565; wp-cron.php:191;)
* Warning archive_errors: 2023-08-30 12:19:54 ('Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=1&period=day&date=2023-08-30&format=json&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of \'memory_limit\' in your php.ini file.  For more information and the error message please check in your PHP CLI error log file. As this core:archive command triggers PHP processes over the CLI, you can find where PHP CLI logs are stored by running this command: php -i | grep error_log' 'Error unserializing the following response from ?module=API&method=CoreAdminHome.archiveReports&idSite=1&period=day&date=2023-08-30&format=json&trigger=archivephp: \'\'' 'Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=1&period=day&date=2023-08-29&format=json&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of \'memory_limit\' in your php.ini file.  For more information and the error message please check in your PHP CLI error log file. As this core:archive command triggers PHP processes over the CLI, you can find where PHP CLI logs are stored by running this command: php -i |
# WordPress

* Home URL: $site_url
* Site URL: $site_url
* WordPress Version: 6.3.1
* Number of blogs: 1
* Multisite Enabled: No
* Network Enabled: No
* WP_DEBUG: No
* WP_DEBUG_DISPLAY: Yes
* WP_DEBUG_LOG: No
* DISABLE_WP_CRON: -
* FORCE_SSL_ADMIN: Yes
* WP_CACHE: No
* CONCATENATE_SCRIPTS: -
* COMPRESS_SCRIPTS: -
* COMPRESS_CSS: -
* ENFORCE_GZIP: -
* WP_LOCAL_DEV: -
* WP_CONTENT_URL: $site_url/wp-content
* WP_CONTENT_DIR: $abs_path/wp-content
* UPLOADS: -
* BLOGUPLOADDIR: -
* DIEONDBERROR: -
* WPLANG: -
* ALTERNATE_WP_CRON: -
* WP_CRON_LOCK_TIMEOUT: 60
* WP_DISABLE_FATAL_ERROR_HANDLER: -
* MATOMO_SUPPORT_ASYNC_ARCHIVING: -
* MATOMO_TRIGGER_BROWSER_ARCHIVING: -
* MATOMO_ENABLE_TAG_MANAGER: -
* MATOMO_SUPPRESS_DB_ERRORS: -
* MATOMO_ENABLE_AUTO_UPGRADE: -
* MATOMO_DEBUG: -
* MATOMO_SAFE_MODE: -
* MATOMO_GLOBAL_UPLOAD_DIR: -
* MATOMO_LOGIN_REDIRECT: -
* Permalink Structure: /%category%/%postname%
* Possibly uses symlink: No
* Upload base url: $site_url/wp-content/uploads
* Upload base dir: $abs_path/wp-content/uploads
* Upload url: $site_url/wp-content/uploads/2023/08
* Custom upload_path: 
* Custom upload_url_path: 
* Compatible content directory: Yes

# WordPress Plugins

* 10Web Social Feed: 1.2.9
* Advanced TinyMCE Configuration: 1.6
* Branda: 3.4.11
* Classic Editor: 1.6.3
* Contact Form 7: 5.8
* Disable WP Notification: 3.1
* Imsanity: 2.8.2
* JSM's Non-Breaking Space (nbsp) for French Content: 1.13.0
* Matomo Analytics - Ethical Stats. Powerful Insights.: 4.15.0
* MC4WP: Mailchimp for WordPress: 4.9.7
* Permalink Manager Lite: 2.4.1.3
* Redirection: 5.3.10
* Regenerate Thumbnails: 3.1.6
* Reviews and Rating - Google My Business: 4.24
* Sassy Social Share: 3.3.53
* Templatera: 1.1.12
* Ultimate Addons for WPBakery Page Builder: 3.19.12
* Wordfence Security: 7.10.3 (Réseau activé)
* WP ACF-VC Bridge: 1.7.9
* WP Armour - Honeypot Anti Spam: 2.1.5
* WPBakery Page Builder: 6.9.0
* WP Popups Lite: 2.1.5.3
* Yoast SEO: 21.0
* Active Plugins: 23 (Ultimate_VC_Addons advanced-tinymce-configuration branda-white-labeling classic-editor contact-form-7 disable-wp-notification g-business-reviews-rating honeypot imsanity js_composer mailchimp-for-wp matomo nbsp-french permalink-manager redirection regenerate-thumbnails sassy-social-share templatera wd-facebook-feed wordfence wordpress-seo wp-acf-vc-bridge wp-popups-lite)
* Theme: castellanos2019 (castellanos2019)

# Server

* Server Info: Apache
* Apache AddHandler support: Pris en charge
* PHP OS: Linux
* PHP Version: 7.4.33
* PHP SAPI: fpm-fcgi
* PHP Binary Name: /images/stable64/usr/local/php7.4/sbin/php-fpm
* Extension PHP Maxmind DB: Non chargé
* PHP Error Reporting:  After bootstrap: 0
* PHP Found Binary: /usr/local/php7.4/bin/php -q
* Timezone: UTC
* WP timezone: Europe/Paris
* Locale: fr_FR
* User Locale: fr_FR
* Memory Limit: 512M (Au moins 128MB recommandé. En fonction de votre trafic, 256MB ou plus peuvent être nécessaires.)
* WP Memory Limit: 256M
* WP Max Memory Limit: 512M
* Timezone version: 2022.1
* Time: 1693399294
* Max Execution Time: 165
* Max Post Size: 130M
* Max Upload Size: 134217728
* Max Input Vars: 16000
* Disabled PHP functions: Yes (_dyuweyrj4,_dyuweyrj4r,dl)
* zlib.output_compression is off: Yes
* Curl Version: 7.64.0, OpenSSL/1.1.1n
* Suhosin installed: No

# PHP cli

* Version de PHP cli: 7.4.33
* Prise en charge de MySQLi: ok

# Database

* MySQL Version: 5.7.42
* Mysqli Connect: Yes
* Force MySQL over Mysqli: No
* DB Prefix: cast19_
* DB CHARSET: utf8mb4
* DB COLLATE: 
* SHOW ERRORS: No
* SUPPRESS ERRORS: No
* Uses Socket: No
* Uses IPv6: No
* Matomo tables found: 87
* DB tables exist: Yes
* Matomo users found: 1
* Matomo sites found: 1
* Permissions obligatoires: OK

# Browser

* Browser:  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0)
* Language: fr,fr-fr,en-us,en

**Comment by sgiehl** [comment]
@paulrouf Thanks for creating this report. Based on the error message it seems that your archiving isn't running for some reason.
You may need to check if you archiving cron is still running correctly. Maybe increasing the memory limit might help.
Otherwise there are a couple of FAQ in our knowledge base like https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/ that might help to check if it set up correctly.
If you aren't able to get it running, maybe try to get some help on our forums. We aren't able to provide this type of support on GitHub, as we are using this issue tracker for bug reports and feature requests only.
