### ISSUE TITLE
config.ini.php rules

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#21205]
Hello, i have used the possibility to change values of `global.ini.php`variables by adding it in the `config.ini.php`. I had it put on the end. First with own [Own Settings] category. Second without that. Both don't work.

There is no hint to find in the doc how and where to insert the variables in the `config.ini.php`.

I have now found out myself that the variables must be written in the same category as in the `global.ini.php`. So for example in `[General]`.

Please put a hint in the doc how and where to insert the variables in the `config.ini.php`.

Question: Is it allowed to use blank lines within a category (between two variables)?

**Comment by michalkleiner** [comment]
I guess we can add a note to the [INI configuration documentation](https://developer.matomo.org/guides/piwiks-ini-configuration).

Yes, it is allowed to use blank lines, empty rows are not significant within the configuration files.
