### ISSUE TITLE
Make Matomo compatible with PHP 8.3

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21209]
RC1 was released today: https://www.php.net/index.php#2023-08-31-1

I assume the final will be released in November?

We need to make sure Matomo works with PHP 8.3 without errors/warnings.

**Comment by sgiehl** [comment]
created https://github.com/matomo-org/matomo/pull/21212 to run our phpunit tests on PHP 8.3.
We should plan in some time the coming weeks to check if there are any failures or warnings in the logs that needs to be fixed.

**Comment by tsteur** [comment]
When we work on PHP 8.3 compatibility, if not already done by then, it could be great to also look at resolving PHP 8.1 errors in core and plugins as we created 2 or 3 issues there recently (I think so far 1 in core and 2 in plugins)

**Comment by sgiehl** [comment]
Not sure if we are already at the point were this issue should be closed. We "only" run tests on PHP 8.3 for now and they are passing. But there might still be a lot of deprecation warnings and similar stuff left over unfixed. If we decide to leave the issue closed, we should add the `not-in-changelog` label, as having `Make Matomo compatible with PHP 8.3` as changelog record might be missleading then.

**Comment by caddoo** [comment]
> Not sure if we are already at the point were this issue should be closed. We "only" run tests on PHP 8.3 for now and they are passing. But there might still be a lot of deprecation warnings and similar stuff left over unfixed. If we decide to leave the issue closed, we should add the `not-in-changelog` label, as having `Make Matomo compatible with PHP 8.3` as changelog record might be missleading then.

Fair point, I noticed we also have many deprecation notices from older versions as well (8.2), I'll create follow up tickets if they aren't already created to handle these deprecations, I already have a list.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/plans-to-support-php-8-2-and-php-8-3/54294/2
