### ISSUE TITLE
Error message while accessing tracking code when Tour plugin is disabled

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#21200]
## Context
I disabled the Tour plugin.
When I try to access ⚙️ > Measurables  > Tracking Code
I get following red error message: `The plugin Tour is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.`
In the log viewer, I see:
```
Uncaught exception in API: .../core/Plugin/Manager.php(303): The plugin Tour is not enabled. You can activate the plugin on Settings > Plugins page in Matomo. [Query: ?date=today&module=API&format=json&method=Tour.detectConsentManager&idSite=3&filter_limit=-1&segment=&period=day, CLI mode: 0]
```

## Expected Behavior
No error message when accessing the Tracking code section while Tour is disabled.

## Your Environment
* Matomo Version: 4.14.2
* PHP Version: 7.3.33
* Server Operating System: RedHat 7
* Additionally installed plugins:

## Plugins Activated:
 API, AbTesting 4.2.4, Actions, ActivityLog 4.1.2, AdminNotification 4.0.0, Annotations, AnonymousPiwikUsageMeasurement 4.1.0, BulkTracking, Cohorts 4.0.8, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, CustomReports 4.1.4, CustomTranslations 4.1.1, CustomiseTranslations 1.0.3, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, ForceSSL 4.0.1, FormAnalytics 4.4.1, Funnels 4.1.6, Goals, GroupPermissions 4.0.5, Heartbeat, HeatmapSessionRecording 4.5.9, HidePasswordReset 4.3.3, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, InvalidateReports 4.1.1, JsTrackerForceAsync 4.0.0, KPIWidgets 1.1.6, LanguagesManager, Live, LogViewer 4.1.1, LoginLdap 4.7.3, LoginSaml 4.3.0, MarketingCampaignsReporting 4.1.3, MediaAnalytics 4.2.1, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Proxy, QueuedTracking 4.0.7, Referrers, ReferrersManager 4.0.3, Resolution, RestrictLanguageSelection 4.0.2, RollUpReporting 4.1.3, ScheduledReports, SecurityInfo 4.0.2, SegmentEditor, SitesManager, TagManager, TasksTimetable 4.0.2, Transitions, TreemapVisualization 4.0.2, TwoFactorAuth, UserId, UserLanguage, UsersFlow 4.1.1, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, WhiteLabel 4.0.8, Widgetize

## Plugins Deactivated:
 DiagnosticsExtended 0.1.9, Feedback, GeoIp2, LanguageToogle 0.3.5, Login, Marketplace, MobileAppMeasurable, MobileMessaging, ProfessionalServices, RssWidget, SEO, Tour, UserCountry, UserCountryMap

**Comment by sgiehl** [comment]
hi @heurteph-ei 
Thanks for the report. This seems to be a bug. It will be fixed as part of #21029
