### ISSUE TITLE
Heatmaps for variation in AB test

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#21225]
Problem: A customer wanted to view the heatmaps for an AB test's variation. 
Note: The variation URL doesn't change in this AB test. 

I understand that to test a specific variation, you can append a URL parameter ?pk_ab_test=$variationName. This will make sure to activate the given variation even if the experiment should not trigger yet because of a defined filter. It will also not track any experiment activation to your Matomo so your data is kept clean.

However, the above method doesn't work when viewing heatmaps for a variation and screenshot doesn't show correct results.

**Comment by AltamashShaikh** [comment]
@Birkaransingh94 You should create or move this issue internally, since Heatmap is a premium feature
