### ISSUE TITLE
The form to sign in with a 2FA recovery code is unreachable 

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21231]
**Expected**:
I begin to sign in with two factor authorization. At the step for 2fa, clicking "Enter one of your recovery codes" presents a form where I can enter the 2fa code.

**Actual**:
I begin to sign in with two factor authorization. At the step for 2fa, clicking "Enter one of your recovery codes" just has a href link to our documentation. The form to enter a recovery code is unreachable (user never sees it, cannot see it).
![matomo-lack-of-recovery-codes-input-form](https://github.com/matomo-org/matomo/assets/22874146/5dd8d057-0015-4200-a9e7-b59e27955f82)

**Comment by sgiehl** [comment]
The 2FA recovery code can simply be used instead of the normal 2FA code. There is no other form for that. The linked FAQ should explain that.
