### ISSUE TITLE
Some UI test cases are providing false positives

### ISSUE THREAD

**Issue by snake14** [piwik/piwik#21244]
In at least 3 separate plugins (FormAnalytics, AbTesting, and Cloud), we have noticed that some of the UI test cases return false positives. The test cases are passing despite the processed and expected screenshots having significant differences. As this is affecting multiple plugins and it's happening in local and build environments, this seems more likely to be a core/library issue. If there's a change that we can make in the plugins, that would be great, but we haven't been able to find one yet.

## Context
We've had cases where the UI tests didn't alert us to a regression because the test cases continued to pass despite the screenshots not matching. The most recent issue was when I made a change to one of the AbTesting screens, but [the build](https://github.com/innocraft/plugin-AbTesting/actions/runs/6117817532/job/16605009973) still passed without me updating the screenshot. A couple weeks ago, the Cloud plugin had a couple screenshots passing despite the background color being different for the entire screen. Back in April (build 4685686384), I noticed that one of the FormAnalytics test cases was still passing despite the processed screenshot being practically empty. You can find some conversation about it in the development channel on 19 April.

## Expected Behavior
I expect the UI builds to pass when the screenshots match and fail when they don't.

## Current Behavior
The UI builds pass and fail as expected most of the time, but sometimes they pass even when there are significant differences between the screenshots.

## Possible Solution
Not sure. Change image comparison libraries?

## Steps to Reproduce (for Bugs)
1. Try changing something obvious in `AbTesting/vue/src/Experiments/Edit/Embed.vue`
2. Run the UI tests locally or commit and push to run them via Github Action
3. Note that the UI build still passes despite the screenshots no longer matching

## Your Environment

* Matomo Version: 4.15.1 or 5.0.0-rc2 currently, but it's been an issue for months
* PHP Version: 8.1, 8.2, probably others
* Server Operating System: Ubuntu and whatever the builds use
* Additionally installed plugins: Pretty much everything but the stock ones are disabled

**Comment by sgiehl** [comment]
This will need some further investigation. Could be caused by the way the tests are currently run (e.g. on a merge commit to the base branch, instead of on the branch it self) or on too big screenshots the threshold might not be hit for small changes.

**Comment by AltamashShaikh** [comment]
I had similar issue with other plugins where the UI tests didn't show any change even though there was significant change in height also.
Example: [https://builds-artifacts.matomo.org/matomo-org/plugin-GoogleAnalyticsImporter/PG-2631-stre[…]all-screenshots/GoogleAnalyticsImporterGA4_load_ga4.png](https://builds-artifacts.matomo.org/matomo-org/plugin-GoogleAnalyticsImporter/PG-2631-streamID-filter/6142889350/all-screenshots/GoogleAnalyticsImporterGA4_load_ga4.png)

Here we added new input field `streamID` and the UI test showed no change.

**Comment by sgiehl** [comment]
@AltamashShaikh @snake14 Were your branches up to date with the base branch and were they based on 4/5.x-dev or any other branch? All tests for a pull request are currently running on the merge commit that would be generated when merging back the branch to its base. In case of a merge conflict this can even cause the tests not to run at all.

**Comment by AltamashShaikh** [comment]
@sgiehl Its based from 5.x-dev and it was upto date
This is the [PR](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/452)

**Comment by snake14** [comment]
@sgiehl I tried the same test case after merging my changes into 5.x-dev. I changed the expected `AbTestingEdit_created_embedcode_view_after_update.png` screenshot and ran the UI test suite `./console tests:run-ui --plugin=AbTesting AbTestingEdit`, but the test case still passed. So, even when executing locally from the tip of 5.x-dev, the image comparison gives a false positive for some tests.

**Comment by snake14** [comment]
Closing becuase I'm pretty sure that this issue was fixed by #21523
