### ISSUE TITLE
Remove underlined websites in "All websites" dashboard as it's noisy to have underlines under 50 website names

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#21255]
In All Websites dashboard, when you have say 30+ websites, then in Matomo 5 RC, the All Websites dashboard becomes noisy and harder to read. Because the site names are underlined. 

To keep things simple and clean, let's remove the blue underlines under the websites names in the "All Websites" dashboard.

**Comment by Stan-vw** [comment]
For me, the use-cases of this page should dictate whether there are underscores:
- if it's mostly used to check some stats and then click to the website of interest: underscores make sense
- if it's mostly used to analyze stats (but not to click through to the websites) then underscores do not make sense.

The UX becomes worse when you add more websites, but I don't think the underscores are the issue. A table with limited sorting and aggregation is not a great way to look at a lot of data.

Some questions I have around this page:
- what are users currently doing with this screen
- what would users like to get out of this screen
- what other "all websites" related features are highly valuable for the user?

Some examples of what might be valuable:
- easier ways to analyse all websites, so making this more like the dashboard for single websites. However, this is already achieved in a roll-up with all websites, so it might not add value, and actually duplicate effort and features.
- easier ways to manage their websites? --> the admin settings are probably right for this, not the All Websites section (which currently has 1 table)

Some of these questions make me think that removing the underlines doesn't make the page "simple and clean", the page fundamentally struggles to have a clear use-case.

Keen to read how other people think about it, and how people are using this page

**Comment by Stan-vw** [comment]
As per internal conversation, if we take away the underscore we reduce accessibility.  

While figuring out a way to remove the underscore while keeping reasonable accessibility and the 2 functionalities (navigate to report, navigate to website) while using our existing design patterns, we suggest to move to:
![image](https://github.com/matomo-org/matomo/assets/52564377/6900bf89-ec35-4fcf-8bad-92f80398f3b1)

**Comment by ronak-innocraft** [comment]
Will be released as part of 5.3.0
