### ISSUE TITLE
PHP 8.1 incompatibility  - UsersManager API - getUsersPlusRole

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21253]
> plugins/UsersManager/API.php(355): Deprecated - Automatic conversion of false to array is deprecated

This is happening in Matomo 4.X.

**Comment by tsteur** [comment]
This happened again.

**Comment by sgiehl** [comment]
Seems to happen when the is no user in the access here: https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/UsersManager/API.php#L354-L356
Should be easy to add a simple check for that to avoid the error.
