### ISSUE TITLE
PHP 8.1 incompatibility in GridGraph

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21256]
Got below Deprecated message. This is in Matomo 4.x. Not sure if this was maybe already fixed in Matomo 5?

> vendor/szymach/c-pchart/src/Image.php(236): Deprecated - imagettfbbox(): Passing null to parameter #4 ($string) of type string is deprecated - Matomo 4.15.2-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Image.php(236),#2/vendor/szymach/c-pchart/src/Draw.php(2289),#3/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#4/plugins/ImageGraph/StaticGraph/Evolution.php(24),#5/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#7/core/API/Proxy.php(244),#8/core/Context.php(28),#9/core/API/Proxy.php(335) | /var/www/html/vendor/szymach/c-pchart/src/Image.php(236): Deprecated - imagettfbbox(): Passing null to parameter #4 ($string) of type string is deprecated - Matomo 4.15.2-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Image.php(236),#2/vendor/szymach/c-pchart/src/Draw.php(2289),#3/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#4/plugins/ImageGraph/StaticGraph/Evolution.php(24),#5/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#7/core/API/Proxy.php(244),#8/core/Context.php(28),#9/core/API/Proxy.php(335)
/var/www/html/vendor/szymach/c-pchart/src/Image.php(236): Deprecated - imagettfbbox(): Passing null to parameter #4 ($string) of type string is deprecated - Matomo 4.15.2-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Image.php(236),#2/vendor/szymach/c-pchart/src/Draw.php(2289),#3/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#4/plugins/ImageGraph/StaticGraph/Evolution.php(24),#5/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#7/core/API/Proxy.php(244),#8/core/Context.php(28),#9/core/API/Proxy.php(335)
 

<br class="Apple-interchange-newline">

**Comment by sgiehl** [comment]
Should be fixed with Matomo 5. See https://github.com/matomo-org/matomo/issues/20654 or https://github.com/matomo-org/matomo/pull/20806

**Comment by tsteur** [comment]
@sgiehl will these 2 Deprecated errors be fixed with that as well?

> vendor/szymach/c-pchart/src/Draw.php(2451): Deprecated - preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated - Matomo 4.15.2-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Draw.php(2451),#2/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#3/plugins/ImageGraph/StaticGraph/Evolution.php(24),#4/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#6/core/API/Proxy.php(244),#7/core/Context.php(28),#8/core/API/Proxy.php(335),#9/core/API/Request.php(267)
 

> vendor/szymach/c-pchart/src/Draw.php(2302): Deprecated - preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated - Matomo 4.15.2-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/vendor/szymach/c-pchart/src/Draw.php(2302),#2/plugins/ImageGraph/StaticGraph/GridGraph.php(312),#3/plugins/ImageGraph/StaticGraph/Evolution.php(24),#4/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#6/core/API/Proxy.php(244),#7/core/Context.php(28),#8/core/API/Proxy.php(335),#9/core/API/Request.php(267)

**Comment by sgiehl** [comment]
Yes. Those errors are all related to a missing series label and should be fixed.
