### ISSUE TITLE
Email report - period Month sends data of current month not last 30 days. Acts different when sent manually

### ISSUE THREAD

**Issue by m-milic** [piwik/piwik#21258]
## Context

I made an email report, with Weekly schedule, and Month selected as the Period.
I want to have a report sent every week (Monday), with data on the last 30 days, eg on June 7. data from May 7. - June 7.

## Expected Behavior

From description next to the field Period - report should have data of the 1 month period up to the date sent. Graph on the report should be display only one month.
Also report should be sent every Monday.

## Current Behavior

First the schedule - report is sent every second week(Monday) automatically, instead of Weekly as selected.
About the Period - when report is sent automatically - it displays the period of the current month in the tables - so if sent on June 15. - it will display data in the table for June 1. - June 15.
The graph of the report displays data for the last 2 years. 

Most confusing thing is that, if I send the email report manually by clicking 'Send report now', both graph and the tables display data for the last 30 days, as they are expected to.

## Your Environment

* Matomo Version: 4.14.2

**Comment by sgiehl** [comment]
Hi @m-milic. The UI around creating and sending scheduled reports currently seems to be a bit confusing. We already received similar reports like https://github.com/matomo-org/matomo/issues/21044 or https://github.com/matomo-org/matomo/issues/19674, so I'll close this one as duplicate.
