### ISSUE TITLE
Larger customisable field in the footer of each page for annotating Emailed reports 

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21250]
Currently, the emailed reports arrive at the stakeholder with only a single customizable sentence at the top: 
![image](https://github.com/matomo-org/matomo/assets/22874146/8deba768-0427-4add-92d0-bcca156b1772)

The need is much greater. The email is sent by a data specialist, and arrives contextless at the client, for example the owner of a shoe store, or a city council.  The question from the recipient is "how shall I interperet this data?" With no interpretation, the emailed report can only arrive fruitfully at the desk of a data specialist. And even for such a peer-recipient, added context and annotation would be helpful.

**Comment by atom-box** [comment]
_From a user:_

I make cheap WP websites (albeit with bespoke plugins and themes) for small family run businesses - guest houses, caravan sites, pubs, dog trainers, parish councils etc . My customers are (independent businesses owners, lone founders and entrepreneurs,) wondering if their website is worth the money it costs to host it. They need to see a very simple and clear report with lots of explanation.

I would like the option for a 'Dummies Guide' explanation of the report to appear below the data, either one you have written or the option for me to write them myself. Either way they would need to be global to all reports.

**Comment by atom-box** [comment]
This issue was upvoted three times this year by users who took the time to speak for those who want this feature. 

At that time it was noted that Matomo has a one sentence customizable field. I would ask the developers to still consider this feature as the users are telling us that the single sentence on page 1 is not what they are asking for.

See:
https://github.com/matomo-org/matomo/issues/20856
https://github.com/matomo-org/matomo/issues/20294

**Comment by michalkleiner** [comment]
Thanks for the suggestion @atom-box. Does this feature request have anything more to it than what would already be covered by #20856? I think 20856 would cover this one as well, so do you think we can close this as a duplicate? More issues for the same thing won't help get it done any faster.

**Comment by atom-box** [comment]
The other issue was closed at the time. I misunderstood how to make pressure to open it.
