### ISSUE TITLE
Show period selection in Evolution Chart when using "Compare to" in the calendar

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21261]
When selecting "Compare to" in the calendar, the period menu for evolution charts should still be available.

Not comparing dates:
![image](https://github.com/matomo-org/matomo/assets/20234985/478c457b-f7e8-45ce-a77b-b64bb674ed56)

Comparing dates:
![image](https://github.com/matomo-org/matomo/assets/20234985/d6f37983-1102-412a-8f9f-49f2281961d4)

**Comment by sgiehl** [comment]
This was actually removed on purpose. For more details see https://github.com/matomo-org/matomo/issues/19967#issuecomment-1740787322
I'll close this as duplicate, as the same topic is kind of handled in https://github.com/matomo-org/matomo/issues/17582 and https://github.com/matomo-org/matomo/issues/19967
