### ISSUE TITLE
Upload & install plugin ZIP fails with "Wrong username and/or password."

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#21274]
In Matomo 5 RC, trying to upload a plugin ZIP of a plugin:
![Screenshot from 2023-09-19 06-44-55](https://github.com/matomo-org/matomo/assets/466765/7ecddc0e-ecc4-4956-94f3-791aed30a6c2)

And entering the correct password, 

then it  fails with

> An error occurred
> Wrong username and/or password.

![image](https://github.com/matomo-org/matomo/assets/466765/9d1602c6-7571-4495-a861-0497eadd8ca4)

**Comment by sgiehl** [comment]
@mattab did you test that on Matomo 4 and does your password contain a char like `&` ?

**Comment by mattab** [comment]
@sgiehl reproduced on 5.0.0-rc2 so it's a regression I think?

**Comment by sgiehl** [comment]
Technically not a regression as the problem existed there before. The upload mechanism has it's own password check, which still uses `Common::getRequestVar` to receive the value. As it doesn't unsanitize the value, every char that might get escaped causes problems there. I'll prepare a PR to fix that, as it's easy to do.
