### ISSUE TITLE
Fatal error: "Call to a member function getColumn() on null" in DataTableRowAction/RowEvolution.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21282]
We got below error:

This fatal error happened on 4.15.2-b1

> Error: {"message":"Call to a member function getColumn() on null","file":"\/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php","line":416,"request_id":"ff53c","backtrace":" on \/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(416)\n#0 \/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(237): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->extractPrettyLabel(Array)\n#1 \/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(231): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->extractEvolutionReport(Array)\n#2 \/plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php(124): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->loadEvolutionReport()\n#3 \/plugins\/CoreHome\/Controller.php(260): Piwik\\Plugins\\CoreHome\\DataTableRowAction\\RowEvolution->__construct(6, Object(Piwik\\Date), 'graphEvolution')\n#4 \/plugins\/CoreHome\/Controller.php(246): Piwik\\Plugins\\CoreHome\\Controller->makeRowEvolution(false, 'graphEvolution')\n#5 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->getRowEvolutionGraph()\n#6 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#7 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('CoreHome', 'getRowEvolution...', Array)\n#8 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#9 \/index.php(25): require_once('\/c...')\n#10 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: /index.php?date=2023-09-30&evolution_day_last_n=8&evolution_month_last_n=3&evolution_week_last_n=4&viewDataTable=graphEvolution&dateUsedInGraph=2023-07-01%2C2023-09-30&columns=nb_clicks%2Cnb_impressions%2Cctr%2Cposition&apiMethod=SearchEngineKeywordsPerformance.getKeywordsBing&label=%40test%2520%25C3%25B8st&disableLink=1&module=CoreHome&action=getRowEvolutionGraph&colors=%7B%26quot%3BbackgroundColor%26quot%3B%3A%26quot%3B%23ffffff%26quot%3B%2C%26quot%3BlineColor%26quot%3B%3A%26quot%3B%23162c4a%26quot%3B%2C%26quot%3BminPointColor%26quot%3B%3A%26quot%3B%23ff7f7f%26quot%3B%2C%26quot%3BmaxPointColor%26quot%3B%3A%26quot%3B%2375bf7c%26quot%3B%2C%26quot%3BlastPointColor%26quot%3B%3A%26quot%3B%2355aaff%26quot%3B%2C%26quot%3BfillColor%26quot%3B%3A%26quot%3B%23ffffff%26quot%3B%7D&idSite=6&period=day&totals=0

> Referrer: /index.php?module=CoreHome&action=index&idSite=6&period=month&date=2023-09-15&updated=2

**Comment by sgiehl** [comment]
I'm not sure how to reproduce that, but looking at the code it seems clear what is causing the error. I'll put up a PR to prevent that error from happening. But not sure if there is actually another problem somewhere else, that leads to this error...
