### ISSUE TITLE
GDPR tools doesn't support Custom Dimensions

### ISSUE THREAD

**Issue by utrautmann** [piwik/piwik#21286]
In the GDPR tools I can't find any way to filter by custom dimensions, even though I selected a specific website and followed the note in this issue #14702.

This applies to both custom dimensions for visits and behavior.

Surprisingly, I can filter for the custom variables that are considered as deprecated.

* Matomo Version: 4.15.2

**Comment by sgiehl** [comment]
Hey @utrautmann 
Thanks for creating this report. I had a quick look and it seems it doesn't refresh the list of segments correctly when a site is select.
I'll check if that is easy to fix.
