### ISSUE TITLE
Rowevolution is showing the ID instead label

### ISSUE THREAD

**Issue by AltamashShaikh** [piwik/piwik#21283]
We recently observed that a UI test, that was failing for CrashAnalytics plugin and it seems that rowEvolution now displays the id instead of the label

![Screenshot from 2023-09-20 09-23-05](https://github.com/matomo-org/matomo/assets/14902277/060248b8-59af-418b-b077-3ee3ea2b5e39)

After checking out to Matomo `5.0.0-rc1` we can see the label correctly, looks like something changed post that
![Screenshot from 2023-09-20 09-22-11](https://github.com/matomo-org/matomo/assets/14902277/cd1784a3-35be-473b-9ede-30afe16612ea)

## Steps to Reproduce (for Bugs)
Check this demo2 [URL](https://demo2.matomo.org/index.php?module=CoreHome&action=index&idSite=82&period=day&date=yesterday#?period=day&date=yesterday&idSite=82&category=CrashAnalytics_Crashes&subcategory=CrashAnalytics_AllCrashes&popover=RowAction%243ARowEvolution%243ACrashAnalytics.getCrashMessages%243A%24257B%24257D%243A35)

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Was fixed with #21288
