### ISSUE TITLE
advertising conversion export: gclid, wbraid, gbraid

### ISSUE THREAD

**Issue by VirtualLaw** [piwik/piwik#21298]
According to the documentation the advertising conversion export plugin for google adwords only supports gclid. Please integrate the new parameters wbraid and gbraid.

https://support.google.com/analytics/answer/11367152?hl=de
https://developers.google.com/google-ads/api/docs/conversions/upload-clicks?hl=de

thx :)
Peter

**Comment by sgiehl** [comment]
Hi @VirtualLaw,

thank you for creating the issue. To request features / support for a Premium Feature please contact shop at innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features

We are only handling requests for Matomo itself here.

But regarding your requests we already have an internal issue around that topic.
As far as I remember it is not (yet) possible to use those ids in the offline conversion upload feature. They are currently only supporting when using the API.
Our team will revisit that topic from time to time and add that once it is supported.

Closing this issue now. Thanks.
