### ISSUE TITLE
Looking for a segment in the list of Segments is difficult because segment names are cut after just a few letters

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#21291]
Looking for a segment in the list of Segments is difficult because segment names are cut after just a few letters

Example of what i'm seeing:

![image](https://github.com/matomo-org/matomo/assets/466765/817a3acd-3c92-4f1b-96b2-4506f8e2aa08)

but here is no reason/benefit to make it so narrow.

So instead it would be great if the segment list was wider and showed maybe twice as many letters.

**Comment by sgiehl** [comment]
Should be quite easy to change the css a bit. Should we keep a fixed with of the dropdown, or maybe let it adjust automatically based on the segment names, while having a min and max width or similar?

**Comment by heurteph-ei** [comment]
I vote for the automatic width! ;-)

**Comment by Stan-vw** [comment]
Automatic width based on name while having a min and max sounds reasonable to me too 👍
