### ISSUE TITLE
Description of auth token is encoded

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21302]
I just created an auth token in my personal security settings. In the description I wrote `I'm using this for ...`.

Afterwards, the description appeared encoded as `I&#039;m...` in the email and in the UI see below 3 screenshots.

Email about deletion of token
<img width="605" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/def162b6-2a3d-4a8b-96ae-246844245b18">

Email about creation of token
<img width="461" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/d8550efd-0797-41fe-8bad-c6b77f74ab6f">

UI - the list of tokens
<img width="975" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/ee32209b-6ffb-4460-92ea-3133e7803694">

This is on latest Matomo 4.X

**Comment by sgiehl** [comment]
The might be a general problem with the vue migration. Translation might also include encoded entities in certain languages, but in most cases we use the translations as text-only in vue, so encoded entities aren't displayed correctly.

**Comment by tsteur** [comment]
@sgiehl so is it a regression likely? Could we add the regression label maybe?

**Comment by sgiehl** [comment]
Just tried reproducing that with Matomo 5. Seems that specific issue has already been fixed with https://github.com/matomo-org/matomo/commit/c4b71cd9418bdfad6a24e784cefa33e613ae13fa#diff-8ce9786c22fb57a4bc8b4122e413fbaf8613ccf8db305c7f27fa631d0e866b3cR386
