### ISSUE TITLE
Matomo 5 Upgrade script: Calculate conversion page command doesn't work with Last-N option

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21309]
I'm running `./console core:calculate-conversion-page --last-n=50000`.

Then I get below error:

> Preparing to calculate the pages before metric for the last 50000 conversions belonging to ALL websites for ALL goals.
ERROR     [01:36:36] 15727  Uncaught exception: Exception: Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): NULL in core/Date.php:1144

When I try to provide both `dates` and `last-n` option, then I get an error that both should not be supplied at the same time.

On Cloud we would like to limit the number of conversions that we'd like to calculate using the `last-n` option.

**Comment by michalkleiner** [comment]
@tsteur can you confirm there are no rows in the `log_conversion` table for that particular instance?
