### ISSUE TITLE
When disabling visitor profile feature, then also disable related segment to prevent archiving from failing

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21318]
## Context
You can currently disable the visitor profile (and visits log) feature. Then certain segments like UserID and visitorId disappear and are no longer valid.

However, segments may already exist that use one of these disabled dimensions..

## Expected Behavior
The segments are deleted so that archiving doesn't fail.

## Current Behavior
Archiving fails. In worst case our scheduled tasks no longer run which could have side effects such as scheduled reports and custom alerts to be no longer sent, billing being inaccurate, etc.

> Uncaught exception in API: Exception: Segment 'visitorId' is not a supported segment. in /core/Segment.php:228 Stack trace: #0 /core/Segment.php(276): Piwik\Segment->getSegmentByName('visitorId') #1 //core/Segment.php(254): Piwik\Segment->getExpressionsWithUnionsResolved(Array) #2 /core/Segment.php(168): Piwik\Segment->initializeSegment('visitorId==0124...', Array) #3 /plugins/CoreAdminHome/API.php(284)

## Possible Solution
Maybe delete those segments? Not sure what we're doing currently when we're deactivating a plugin whose dimensions are used in segments?

## Your Environment
Latest Matomo 4.x

**Comment by sgiehl** [comment]
@tsteur Had a rough look through the code, but it seems we currently only automatically remove segments if either a user or a site is removed. Disabling plugins seems not to trigger that. So this might be something that should be added as well.
