### ISSUE TITLE
Email report - Report with weekly schedule not sent every week

### ISSUE THREAD

**Issue by m-milic** [piwik/piwik#21315]
## Context
I made an email report, with Weekly schedule, and I want to have it sent every week (Monday), 

## Expected Behavior
It is sent every Monday to selected emails.

## Current Behavior
It is sent every 2-3 or sometimes even 4 weeks.

## Steps to Reproduce (for Bugs)
Create email report with following settings, and wait for a few weeks.
![image](https://github.com/matomo-org/matomo/assets/122835179/6d0a35cd-6b63-4e47-aa97-25fc55b8b8a4)

## Your Environment
Matomo Version: 4.14.2

**Comment by sgiehl** [comment]
Hi @m-milic. Sorry to hear you have problems with that.
Are you using a cron job for archiving or is this triggered through the UI?

**Comment by m-milic** [comment]
Hi,
Report is set up/scheduled through the UI.

**Comment by michalkleiner** [comment]
@m-milic I think sgiehl was asking how is your archiving triggered. The background being when the archiving is triggered by the UI, the report sending is actually linked to the archiving action when there's no cron setup which may mean irregular runs like you're mentioning when there's less things to archive/less traffic.

**Comment by m-milic** [comment]
Hi @sgiehl and @michalkleiner ,

Sorry for waiting this long for my answer.

Our archiving is triggered through the UI, so that might be the cause of the issue. We will set up a cronjob, and if there are any problems with that I'll let you know.

Thanks
