### ISSUE TITLE
German: Small typo

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#21329]
In the Frequency Overview widget, there is a mistranslation in German, which is causing confusion to clients.

The first value in the widget is "returning VISITS" but in German it is translated as "wiederkehrende Besucher". That means visitORS. For visits, it should be without the final r. Please correct this.

<img width="712" alt="Screenshot 2023-10-02 at 2 01 24 PM" src="https://github.com/matomo-org/matomo/assets/89768140/ec0b180f-b80f-4779-9d57-d7bfea6ad476">

**Comment by Birkaransingh94** [comment]
In English, it is displayed as:
<img width="411" alt="Screenshot 2023-10-02 at 2 02 45 PM" src="https://github.com/matomo-org/matomo/assets/89768140/2fc1c05e-10bb-4094-a4ea-195989ff1952">

**Comment by sgiehl** [comment]
We can't fix such stuff directly in the code. That needs to be changed on weblate directly. 
As @michalkleiner already did that, this should be changed with the next update.
