### ISSUE TITLE
Matomo 5 regression making archiving fail: Metrics::makeGoalColumnsRow Argument idGoal must be of type int in CustomDimension.php 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21345]
This fatal error happened on 5.0.0-rc4

> Error: {"message":"Piwik\\Metrics::makeGoalColumnsRow(): Argument #1 ($idGoal) must be of type int, string given, called in \/plugins\/CustomDimensions\/RecordBuilders\/CustomDimension.php on line 143","file":"\/core\/Metrics.php","line":613,"request_id":"dcc10","backtrace":" on \/core\/Metrics.php(613)\n#0 \/plugins\/CustomDimensions\/RecordBuilders\/CustomDimension.php(143): Piwik\\Metrics::makeGoalColumnsRow('__mtm_ranking_q...', Array)\n#1 \/plugins\/CustomDimensions\/RecordBuilders\/CustomDimension.php(75): Piwik\\Plugins\\CustomDimensions\\RecordBuilders\\CustomDimension->aggregateFromConversions(Object(Piwik\\DataTable), Object(Piwik\\DataAccess\\LogAggregator), 'custom_dimensio...', Array, ' log_conversion...')\n#2 \/core\/ArchiveProcessor\/RecordBuilder.php(94): Piwik\\Plugins\\CustomDimensions\\RecordBuilders\\CustomDimension->aggregate(Object(Piwik\\ArchiveProcessor))\n#3 \/core\/Plugin\/Archiver.php(205): Piwik\\ArchiveProcessor\\RecordBuilder->buildFromLogs(Object(Piwik\\ArchiveProcessor))\n#4 \/core\/ArchiveProcessor\/PluginsArchiver.php(181): Piwik\\Plugin\\Archiver->callAggregateDayReport()\n#5 \/core\/ArchiveProcessor\/Loader.php(310): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateAllPlugins(27143, '21037', false)\n#6 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(27143, '21037')\n#7 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(27090.0, 21002.0, false, NULL)\n#8 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary')\n#9 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#10 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#11 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary')\n#12 \/core\/Archive.php(918): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(2, Object(Piwik\\Period\\Day), '2023-10-02', '', 'VisitsSummary', '')\n#13 \/core\/Archive.php(699): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Day))\n#14 \/core\/Archive.php(638): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array)\n#15 \/core\/Archive.php(564): Piwik\\Archive->getArchiveIds(Array)\n#16 \/core\/Archive.php(361): Piwik\\Archive->get(Array, 'numeric')\n#17 \/core\/ArchiveProcessor.php(700): Piwik\\Archive->getDataTableFromNumeric(Array)\n#18 \/core\/ArchiveProcessor.php(282): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false)\n#19 \/core\/ArchiveProcessor\/PluginsArchiver.php(327): Piwik\\ArchiveProcessor->aggregateNumericMetrics(Array)\n#20 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics()\n#21 \/core\/ArchiveProcessor\/Loader.php(304): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics()\n#22 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(14674.0, 11317.0)\n#23 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(14674.0, 11317.0, false, NULL)\n#24 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary')\n#25 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#26 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#27 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary')\n#28 \/core\/Archive.php(918): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(2, Object(Piwik\\Period\\Week), '2023-10-02', '', 'VisitsSummary', '')\n#29 \/core\/Archive.php(699): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Week))\n#30 \/core\/Archive.php(638): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array)\n#31 \/core\/Archive.php(564): Piwik\\Archive->getArchiveIds(Array)\n#32 \/core\/Archive.php(361): Piwik\\Archive->get(Array, 'numeric')\n#33 \/core\/ArchiveProcessor.php(700): Piwik\\Archive->getDataTableFromNumeric(Array)\n#34 \/core\/ArchiveProcessor.php(282): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false)\n#35 \/core\/ArchiveProcessor\/PluginsArchiver.php(327): Piwik\\ArchiveProcessor->aggregateNumericMetrics(Array)\n#36 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics()\n#37 \/core\/ArchiveProcessor\/Loader.php(304): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics()\n#38 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(35120.0, 27017.0)\n#39 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(35120.0, 27017.0, false, NULL)\n#40 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary')\n#41 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#42 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#43 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary')\n#44 \/core\/Archive.php(918): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(2, Object(Piwik\\Period\\Month), '2023-10-01', '', 'VisitsSummary', '')\n#45 \/core\/Archive.php(699): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Month))\n#46 \/core\/Archive.php(638): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array)\n#47 \/core\/Archive.php(564): Piwik\\Archive->getArchiveIds(Array)\n#48 \/core\/Archive.php(361): Piwik\\Archive->get(Array, 'numeric')\n#49 \/core\/ArchiveProcessor.php(700): Piwik\\Archive->getDataTableFromNumeric(Array)\n#50 \/core\/ArchiveProcessor.php(282): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false)\n#51 \/core\/ArchiveProcessor\/PluginsArchiver.php(327): Piwik\\ArchiveProcessor->aggregateNumericMetrics(Array)\n#52 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics()\n#53 \/core\/ArchiveProcessor\/Loader.php(304): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics()\n#54 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(8092946.0, 5981698.0)\n#55 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(8092946.0, 5981698.0, false, NULL)\n#56 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl(false)\n#57 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#58 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#59 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive(false)\n#60 [internal function]: Piwik\\Plugins\\CoreAdminHome\\API->archiveReports('2', Object(Piwik\\Period\\Year), '2023-01-01', false, false, false)\n#61 \/core\/API\/Proxy.php(255): call_user_func_array(Array, Array)\n#62 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#63 \/core\/API\/Proxy.php(346): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#64 \/core\/API\/Request.php(272): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'archiveReports', Array)\n#65 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#66 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#67 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#68 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#69 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#70 \/index.php(25): require_once('\/c...')\n#71 \/core\/CliMulti\/RequestCommand.php(75): require_once('\/i...')\n#72 \/core\/Plugin\/ConsoleCommand.php(110): Piwik\\CliMulti\\RequestCommand->doExecute()\n#73 \/vendor\/symfony\/console\/Command\/Command.php(298): Piwik\\Plugin\\ConsoleCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#74 \/core\/Plugin\/ConsoleCommand.php(125): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#75 \/vendor\/symfony\/console\/Application.php(1040): Piwik\\Plugin\\ConsoleCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#76 \/vendor\/symfony\/console\/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\CliMulti\\RequestCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#77 \/core\/Console.php(106): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#78 [internal function]: Piwik\\Console->originDoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#79 \/core\/Console.php(145): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#80 \/core\/Access.php(670): Piwik\\Console->Piwik\\{closure}()\n#81 \/core\/Console.php(146): Piwik\\Access::doAsSuperUser(Object(Closure))\n#82 \/core\/Console.php(85): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#83 \/vendor\/symfony\/console\/Application.php(171): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#84 \/console(32): Symfony\\Component\\Console\\Application->run()\n#85 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 \/core\/CliMulti\/RequestCommand.php(75): require_once('\/i...')\n#9 \/core\/Plugin\/ConsoleCommand.php(110): Piwik\\CliMulti\\RequestCommand->doExecute()\n#10 \/vendor\/symfony\/console\/Command\/Command.php(298): Piwik\\Plugin\\ConsoleCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/core\/Plugin\/ConsoleCommand.php(125): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 \/vendor\/symfony\/console\/Application.php(1040): Piwik\\Plugin\\ConsoleCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/vendor\/symfony\/console\/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\CliMulti\\RequestCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/core\/Console.php(106): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 [internal function]: Piwik\\Console->originDoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/core\/Console.php(145): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/core\/Access.php(670): Piwik\\Console->Piwik\\{closure}()\n#18 \/core\/Console.php(146): Piwik\\Access::doAsSuperUser(Object(Closure))\n#19 \/core\/Console.php(85): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/vendor\/symfony\/console\/Application.php(171): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/console(32): Symfony\\Component\\Console\\Application->run()\n#22 {main}"}

> Executed on CLI

Originally reported in https://github.com/matomo-org/matomo/issues/21344

**Comment by sgiehl** [comment]
Reopening as the PR might not fully fix the problem. Looking through the stack trace it seems `__mtm_ranking_query_others__` is passed as goal id, which indicates an `others` row created by the ranking query. Need to investigate why that now is the case...

**Comment by sgiehl** [comment]
I've now investigated that in detail. So the problem in that case occurred while archiving custom dimensions. The custom dimensions archiving uses `LogAggregator::queryConversionsByDimension` in combination with a RankingQuery. This ends up in a query like
```sql
	SELECT
		
		CASE
			WHEN counter = 50001 THEN '__mtm_ranking_query_others__'
			ELSE `custom_dimension_1`
		END AS `custom_dimension_1`
	, 
		CASE
			WHEN counter = 50001 THEN '__mtm_ranking_query_others__'
			ELSE `idgoal`
		END AS `idgoal`
	
		, sum(`1`) AS `1`, sum(`3`) AS `3`, sum(`2`) AS `2`, sum(`4`) AS `4`, sum(`5`) AS `5`, sum(`6`) AS `6`, sum(`7`) AS `7`, sum(`8`) AS `8`
	FROM ( 
	SELECT
		`custom_dimension_1`, `idgoal`,
		
	CASE
		WHEN @counter = 50001 THEN 50001
		ELSE @counter:=@counter+1
	END
 AS counter
		, `1`, `3`, `2`, `4`, `5`, `6`, `7`, `8`
	FROM
		( SELECT @counter:=0 ) initCounter,
		( SELECT /* sites 1 */ /* 2023-10-10,2023-10-11 */ /* CustomDimensions CustomDimension */
		log_conversion.idgoal AS `idgoal`, 
	log_conversion.custom_dimension_1 AS `custom_dimension_1`, 
	count(*) AS `1`, 
	count(distinct log_conversion.idvisit) AS `3`, 
	ROUND(SUM(log_conversion.revenue),2) AS `2`, 
	ROUND(SUM(log_conversion.revenue_subtotal),2) AS `4`, 
	ROUND(SUM(log_conversion.revenue_tax),2) AS `5`, 
	ROUND(SUM(log_conversion.revenue_shipping),2) AS `6`, 
	ROUND(SUM(log_conversion.revenue_discount),2) AS `7`, 
	SUM(log_conversion.items) AS `8`
	FROM
		matomo_log_conversion AS log_conversion
	WHERE
		log_conversion.server_time >= ?
		AND log_conversion.server_time <= ?
		AND log_conversion.idsite IN (?) AND  log_conversion.custom_dimension_1 is not null
	GROUP BY
		log_conversion.idgoal, log_conversion.custom_dimension_1 ) actualQuery
 ) AS withCounter
	GROUP BY counter
```
So in case there are more combinations of custom dimension values and available goals, this might end up in records where the custom dimension value and the goal id is set to `__mtm_ranking_query_others__`.

Logically this seems sort of wrong, but I doubt that this was handled correctly any time before.
As `queryConversionsByDimension` is used to enrich the visit metrics fetched using `queryVisitsByDimension` with goal data, it would be correct to limit that query by the amount of custom dimensions only and fetch all goal data for those.
Otherwise this could end up in a mixed up data set, where `queryVisitsByDimension` returned another set of values than `queryConversionsByDimension`. So there could be records having only visit metrics and records only having goal metrics.

@tsteur I'm actually not fully sure how to proceed here. Fixing the ranking query so it fetches all goals for a limited set of custom dimensions might be the correct solution, but it might need a bit more effort to adjust that code.
A temporary solution could be to simply throw away returned records with `__mtm_ranking_query_others__` as goalid or increase the ranking query limit...

**Comment by tsteur** [comment]
@sgiehl I'm not fully understanding the problem between `queryVisitsByDimension` and `queryConversionsByDimension`. However, if that was not correctly handled before, does it make sense to create a new issue for this and simply allow the goalId to be a string or integer (or not specify a type)?

Overall, that's maybe how RankingQuery works but I believe the inner query should be having an "OrderBy" to make sure we include the records with the most visits/conversions/... (whatever the sort metric would be there)

**Comment by sgiehl** [comment]
`queryVisitsByDimension` fetches the metrics for all dimension value. for custom dimensions e.g.
| label | hits | visits |
| --- | --- | --- |
| val1 | 2 | 3 |
| ... | ... | ... |

`queryConversionsByDimension` would fetch the goal metrics. e.g.
| label | goal1_conversions | goal1_revenue | goal2_conversions | goal2_revenue |
| --- | --- | --- | --- | --- |
| val1 | 2 | 3.99 | 1 | 20.5
| ... | ... | ... | ... | ... |

both results will then be combined ending up in a table like
| label | hits | visits | goals
| --- | --- | --- | --- |
| val1 | 2 | 3 | {1: {conversions: 2, revenue: 3.99}, 2: {conversions: 1, revenue: 20.5}} |
| ... | ... | ... | ... |

So there might be a problem if `queryConversionsByDimension` returns a different result set of dimension values as `queryVisitsByDimension` or if the results are limitted by the rankingquery, as the data grouped in to the others row might be from different dimension value / goal combinations. Hope that makes it a bit clearer

**Comment by sgiehl** [comment]
This problem might actually be kind of an edge case for very big customers having a lot conversions.
When there are too many conversions for different goals and different custom dimension values, this might currently cause the goal metrics for custom dimensions to be inaccurate.

I've created https://github.com/matomo-org/matomo/pull/21398, which will circumvent the problem for now.
But might be good to think about creating a new issue for a proper fix.
