### ISSUE TITLE
Matomo 5: Error on login  around a translation

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21346]
We're seeing below error in Matomo 5 by the looks when logging in. Not sure what language it is, maybe Italian?

This fatal error happened on 5.0.0-rc4

> Error: {"message":"Unknown format specifier \"i\"","file":"\/core\/Translation\/Translator.php","line":103,"request_id":"cc322","backtrace":" on \/core\/Translation\/Translator.php(103)\n#0 \/core\/Translation\/Translator.php(103): vsprintf('Questo non \\xC3\\xA8 m...', Array)\n#1 \/core\/Piwik.php(916): Piwik\\Translation\\Translator->translate('Questo non \\xC3\\xA8 m...', Array, 'it')\n#2 \/plugins\/UserCountry\/LocationProvider\/DefaultProvider.php(181): Piwik\\Piwik::translate('UserCountry_Def...', Array)\n#3 \/plugins\/UserCountry\/LocationProvider.php(415): Piwik\\Plugins\\UserCountry\\LocationProvider\\DefaultProvider->getInfo()\n#4 \/plugins\/UserCountry\/LocationProvider.php(405): Piwik\\Plugins\\UserCountry\\LocationProvider->getId()\n#5 \/plugins\/UserCountry\/VisitorGeolocator.php(90): Piwik\\Plugins\\UserCountry\\LocationProvider::getProviderById('geoip2php')\n#6 \/plugins\/ActivityLog\/Activity\/Activity.php(159): Piwik\\Plugins\\UserCountry\\VisitorGeolocator->__construct()\n#7 [internal function]: Piwik\\Plugins\\ActivityLog\\Activity\\Activity::logEvent('test')\n#8 \/core\/EventDispatcher.php(147): call_user_func_array(Array, Array)\n#9 \/core\/Piwik.php(871): Piwik\\EventDispatcher->postEvent('Login.authentic...', Array, false, Array)\n#10 \/core\/Session\/SessionInitializer.php(36): Piwik\\Piwik::postEvent('Login.authentic...', Array)\n#11 \/plugins\/Login\/Controller.php(332): Piwik\\Session\\SessionInitializer->initSession(Object(Piwik\\Plugins\\Cloud\\Auth))\n#12 \/plugins\/Login\/Controller.php(160): Piwik\\Plugins\\Login\\Controller->authenticateAndRedirect('test', 'test')\n#13 \/plugins\/Login\/Controller.php(135): Piwik\\Plugins\\Login\\Controller->login()\n#14 [internal function]: Piwik\\Plugins\\Login\\Controller->index()\n#15 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#16 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Login', false, Array)\n#17 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#18 \/index.php(25): require_once('\/c...')\n#19 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(ValueError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: /?module=Login

**Comment by tsteur** [comment]
Maybe this is an issue with activity log?

**Comment by tsteur** [comment]
Seems the `UserCountry_DefaultLocationProviderDesc2` translation key for Italian has an incorrect `%1$` missing a following `s` if I had to guess

**Comment by michalkleiner** [comment]
String fixed in Weblate and translations update merged.
