### ISSUE TITLE
Matomo 5: Translation error in No Data page

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21349]
Seems to be happening on no data page. For language `sv` maybe?

> Error: {"message":"The arguments array must contain 3 items, 2 given","file":"\/core\/Translation\/Translator.php","line":103,"request_id":"998c8","backtrace":" on \/core\/Translation\/Translator.php(103)\n#0 \/core\/Translation\/Translator.php(103): vsprintf('Vi har ocks\\xC3\\xA5 u...', Array)\n#1 \/core\/Piwik.php(916): Piwik\\Translation\\Translator->translate('Vi har ocks\\xC3\\xA5 u...', Array, 'sv')\n#2 \/core\/Twig.php(500): Piwik\\Piwik::translate('SitesManager_Si...', Array)\n#3 \/tmp\/templates_c\/7f\/7fecf523531e7810cff8e98fdc2504f1.php(141): Piwik\\Twig->Piwik\\{closure}('SitesManager_Si...', '')\n#4 \/vendor\/twig\/twig\/src\/Template.php(394): __TwigTemplate_f34f13e025094714296c19efc8574a25->doDisplay(Array, Array)\n#5 \/vendor\/twig\/twig\/src\/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)\n#6 \/vendor\/twig\/twig\/src\/Template.php(379): Twig\\Template->display(Array)\n#7 \/vendor\/twig\/twig\/src\/TemplateWrapper.php(40): Twig\\Template->render(Array, Array)\n#8 \/vendor\/twig\/twig\/src\/Environment.php(280): Twig\\TemplateWrapper->render(Array)\n#9 \/core\/View.php(333): Twig\\Environment->render('@SitesManager\/_...', Array)\n#10 \/core\/View.php(318): Piwik\\View->renderTwigTemplate()\n#11 \/core\/Plugin\/Controller.php(331): Piwik\\View->render()\n#12 \/plugins\/SitesManager\/Controller.php(243): Piwik\\Plugin\\Controller->renderTemplateAs('@SitesManager\/_...', Array, 'basic')\n#

> URL: /index.php?date=yesterday&module=SitesManager&format=html&action=siteWithoutDataTabs&idSite=1&period=day&segment=&widget=&showtitle=1&random=2958

> Referrer: /index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday

**Comment by tsteur** [comment]
Same maybe also in `FR`?

> Error: {"message":"The arguments array must contain 3 items, 2 given","file":"\/var\/www\/html\/core\/Translation\/Translator.php","line":103,"request_id":"a3954","backtrace":" on \/var\/www\/html\/core\/Translation\/Translator.php(103)\n#0 \/var\/www\/html\/core\/Translation\/Translator.php(103): vsprintf('Nous avons \\xC3\\xA9ga...', Array)\n#1 \/var\/www\/html\/core\/Piwik.php(916): Piwik\\Translation\\Translator->translate('Nous avons \\xC3\\xA9ga...', Array, 'fr')\n#2 \/var\/www\/html\/core\/Twig.php(500): Piwik\\Piwik::translate('SitesManager_Si...', Array)\n#3

**Comment by michalkleiner** [comment]
Not sure what's going on here, the strings have correct placeholders in Weblate and in the code, looking at the key `SiteWithoutDataDetectedGtm` which is common to both errors based on the translated text.

**Comment by michalkleiner** [comment]
@sgiehl do you mind having a look?

**Comment by tsteur** [comment]
There are 3 parameters in the french translation, but only 2 are passed. The english version of the translation has only 2 placeholders. There's a mismatch in expected parameters that's causing things to break. 

I actually thought we had automated tests to prevent this but it seems we don't. There may be also other translations that have similar issues.

**Comment by sgiehl** [comment]
This one should be fixed with next RC. I saw that while working in the new layout. Someone had removed one of the placeholders in the string and it ended up only having `%2$s` and `%3$s`. I had updated the English version and all translations some days ago.
