### ISSUE TITLE
[Bug]: In the Visitor Map Piemonte, Italy inherits the visits of Liguria, Italy

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21358]
### What happened?

The visitor map displays the number of visits for Piemonte, Italy as the visits for Liguria, Italy...

![italy](https://github.com/matomo-org/matomo/assets/20234985/123b1f05-c036-443f-b7a6-c1211c878aa2)
![image](https://github.com/matomo-org/matomo/assets/20234985/098224c1-a70d-41e8-8348-4328465a6a05)

I can reproduce this in multiple instances of Matomo 4.15.
This may be related to https://github.com/matomo-org/matomo/issues/11929

### What should happen?

The map region for Piemonte, Italy should show the visits for that region.

### How can this be reproduced?

Visitors -> Location -> Visits Map

### Matomo Version

Matomo 3

### Matomo Patch or Minor Version

15

### PHP Version

NA

### Server Operating System

NA

### Computer Operating System

NA

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Thanks for reporting this one. Seems the map is using the wrong codes to determine the visits. I'll set up a PR to fix that.
