### ISSUE TITLE
Fatal error: Call to undefined method getDataTables in ComparisonRowGenerator.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21352]
Unsure if below is a Matomo 5 regression. I believe we haven't had this issue before but unclear if it's a regression or not.

This fatal error happened on 5.0.0-rc4

> Error: {"message":"Call to undefined method Piwik\\DataTable::getDataTables()","file":"\/plugins\/API\/Filter\/DataComparisonFilter\/ComparisonRowGenerator.php","line":48,"request_id":"f68aa","backtrace":" on \/plugins\/API\/Filter\/DataComparisonFilter\/ComparisonRowGenerator.php(48)\n#0 \/plugins\/API\/Filter\/DataComparisonFilter.php(222): Piwik\\Plugins\\API\\Filter\\DataComparisonFilter\\ComparisonRowGenerator->compareTables(Array, Object(Piwik\\DataTable\\Map), Object(Piwik\\DataTable))\n#1 \/core\/API\/DataTablePostProcessor.php(519): Piwik\\Plugins\\API\\Filter\\DataComparisonFilter->compare(Object(Piwik\\DataTable\\Map))\n#2 \/core\/API\/DataTablePostProcessor.php(124): Piwik\\API\\DataTablePostProcessor->applyComparison(Object(Piwik\\DataTable\\Map))\n#3 \/core\/Plugin\/Visualization.php(560): Piwik\\API\\DataTablePostProcessor->process(Object(Piwik\\DataTable\\Map))\n#4 \/core\/Plugin\/Visualization.php(193): Piwik\\Plugin\\Visualization->applyFilters()\n#5 \/core\/Plugin\/Controller.php(258): Piwik\\Plugin\\Visualization->render()\n#6 \/plugins\/VisitsSummary\/Controller.php(126): Piwik\\Plugin\\Controller->renderView(Object(Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution))\n#7 [internal function]: Piwik\\Plugins\\VisitsSummary\\Controller->getEvolutionGraph()\n#8 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#9 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('VisitsSummary', 'getEvolutionGra...', Array)\n#10 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#11 \/index.php(25): require_once('\/c...')\n#12 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): 

> URL: /index.php?date=2023-09-24,2023-10-01&forceView=1&viewDataTable=graphEvolution&module=VisitsSummary&action=getEvolutionGraph&disableLink=0&widget=1&columns%5B%5D=nb_uniq_visitors&columns_to_display%5B%5D=nb_uniq_visitors&evolution_day_last_n=90&comparePeriods%5B%5D=range&compareDates%5B%5D=2023-09-23%2C2023-09-24&idSite=1&period=range

> Referrer: /index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday

**Comment by sgiehl** [comment]
Looks like it tries comparing a Datatable map with a normal datatable for that specific request. The problem seems to be that the graph aims to display the metric `nb_uniq_visitors` for a range period, where that metric actually isn't available. I'll set up a PR to prevent that error.
