### ISSUE TITLE
Matomo 5 Archiving regression:  Column 'config_browser_name' in group statement is ambiguous

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21351]
Matomo 5.0.0RC 4.

See details below.

> piwik.ERROR: Uncaught exception in API: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'config_browser_name' in group statement is ambiguous in libs/Zend/Db/Statement/Pdo.php:233 Stack trace: #0 libs/Zend/Db/Statement/Pdo.php(233): PDOStatement->execute() #1 libs/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array) #2 libs/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array) #3 libs/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT  /*+ MAX...', Array) #4 core/Db/Adapter/Pdo/Mysql.php(325): Zend_Db_Adapter_Pdo_Abstract->query('SELECT  /*+ MAX...', Array) #5 [internal function]: Piwik\Db\Adapter\Pdo\Mysql->query('SELECT  /*+ MAX...', Array) #6 core/DataAccess/ArchivingDbAdapter.php(118): call_user_func_array(Array, Array) #7 core/DataAccess/ArchivingDbAdapter.php(60): Piwik\DataAccess\ArchivingDbAdapter->callFunction('query', 'SELECT  /*+ MAX...', Array) #8 core/DataAccess/LogAggregator.php(1095): Piwik\DataAccess\ArchivingDbAdapter->query('SELECT  /*+ MAX...', Array) #9 plugins/DevicesDetection/RecordBuilders/Base.php(81): Piwik\DataAccess\LogAggregator->queryConversionsByDimension(Array) #10 core/ArchiveProcessor/RecordBuilder.php(94): Piwik\Plugins\DevicesDetection\RecordBuilders\Base->aggregate(Object(Piwik\ArchiveProcessor)) #11 core/Plugin/Archiver.php(205): Piwik\ArchiveProcessor\RecordBuilder->buildFromLogs(Object(Piwik\ArchiveProcessor)) #12 core/ArchiveProcessor/PluginsArchiver.php(181): Piwik\Plugin\Archiver->callAggregateDayReport() #13 core/ArchiveProcessor/Loader.php(310): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateAllPlugins(4, '0', false) #14 core/ArchiveProcessor/Loader.php(185): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive(4, '0') #15 core/ArchiveProcessor/Loader.php(164): Piwik\ArchiveProcessor\Loader->insertArchiveData(false, false, false, NULL) #16 core/ArchiveProcessor/Loader.php(104): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl(false) #17 core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}() #18 core/ArchiveProcessor/Loader.php(108): Piwik\Context::changeIdSite(1, Object(Closure)) #19 plugins/CoreAdminHome/API.php(295): Piwik\ArchiveProcessor\Loader->prepareArchive(false) #20 [internal function]: Piwik\Plugins\CoreAdminHome\API->archiveReports('1', Object(Piwik\Period\Day), '2023-10-02', 'dimension1%3D%4...', false, false) #21 core/API/Proxy.php(255): call_user_func_array(Array, Array) #22 core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}() #23 core/API/Proxy.php(346): Piwik\Context::executeWithQueryParameters(Array, Object(Closure)) #24 core/API/Request.php(272): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'archiveReports', Array) #25 plugins/API/Controller.php(45): Piwik\API\Request->process() #26 [internal function]: Piwik\Plugins\API\Controller->index() #27 core/FrontController.php(637): call_user_func_array(Array, Array) #28 core/FrontController.php(169): Piwik\FrontController->doDispatch('API', false, Array) #29 core/dispatch.php(32): Piwik\FrontController->dispatch() #30 index.php(25): require_once('c...') #31 core/CliMulti/RequestCommand.php(75): require_once('i...') #32 core/Plugin/ConsoleCommand.php(110): Piwik\CliMulti\RequestCommand->doExecute() #33 vendor/symfony/console/Command/Command.php(298): Piwik\Plugin\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),

**Comment by sgiehl** [comment]
Looks like this happens due to using a segment on a visits dimension while querying conversion dimensions. I'll try to reproduce that locally to find a fix.

**Comment by sgiehl** [comment]
I wasn't able to reproduce that error yet. Tried a couple of different segments, but everything ran through correctly. 
@tsteur Are you maybe able to look up the full segment definition?
