### ISSUE TITLE
Composer missing...

### ISSUE THREAD

**Issue by Shine753** [piwik/piwik#21350]
Hello,

A few years ago I downloaded version 2.13.1 of Piwik. It was 13 Mb in size. Simply unpacking it in its destination directory, and running it, led to a multi-step installation procedure. And it worked.

Today, I re-downloaded this same version from Github, it's 23.5 Mb, I did the same thing to install it, and when I launched it I landed on an error message telling me that Composer was missing, and asking me to download and install it...

So I took the package I'd downloaded at the time, unpacked it, ran it: installation procedure, and it worked.

What's the problem? Why don't I get the same behavior from the version I downloaded and the one on Github?

**Comment by sgiehl** [comment]
Depends what exactly you downloaded. The assets attached to our releases on github should contain all needed files: See e.g. https://github.com/matomo-org/matomo/releases/tag/4.15.1
You only can't use the source code downloads.

**Comment by Shine753** [comment]
This is partially right and wrong.
See https://github.com/matomo-org/matomo/releases/tag/2.13.1
There is here only the source code.
Where, obviously, what I did download some years ago when the release was out was more complete.
And this seems to be the case up to the 4.7.1 version.

**Comment by sgiehl** [comment]
We have changed our release process last year. Before that releases were only pushed to our release server at https://builds.matomo.org/
