### ISSUE TITLE
Matomo 5: Matomo console always exits with status code 0

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21353]
I'm not sure if this is new in Matomo 5 or was the case previously. 

Because we have a `register_shutdown_function(array('\\Piwik\\FrontController', 'triggerSafeModeWhenError'));` defined, any console command seems to always exit with status code 0 no matter what exception you trigger or what code you return in the `doExecute()` method. Removing the shutdown handler makes the command exit with the expected code.

It looks like a regression to me as we use exit code checks for various things, but it could be equally a different behavior from a different PHP version or so.

This may be something to look into.

Locally using PHP 8.1 with Matomo 5 RC4

**Comment by sgiehl** [comment]
@tsteur can you provide an example which command used to return a different return code? When e.g. a parameter is missing or another exception is thrown the return code already seems to be `1`

**Comment by tsteur** [comment]
Weird, I checked the logs and I was reproducing it yesterday with `./console core:archive --no-ansi` but now I can no longer reproduce it. I always get the expected return code. I'll close it for now and will reopen should I be able to reproduce it again 👍  Thanks for checking
