### ISSUE TITLE
[Bug]: Translation strings missing in 5.0 for user feedback text

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21365]
### What happened?

When clicking the thumbs up/down feedback button at the top of table and charts, the feedback form shows missing translation strings. This appears to be a regression in Matomo 5.0 which was temporarily deployed to Cloud. This can be reproduced on demo2. This does not appear to affect `5.x-dev` so possibly it has been resolved. Per dev team: "there seems to be something wrong with the Feedback-Plugin and Permissions".

![image](https://github.com/matomo-org/matomo/assets/20234985/b69d9a8c-b324-40e0-8de5-fdba31f6e1d9)

### What should happen?

Translations shown

### How can this be reproduced?

Using the **demo2** instance go to Behaviour -> Software (for example) and click the thumbs up icon at the top of any chart or table.

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.0

### PHP Version

NA

### Server Operating System

NA

### What browsers are you seeing the problem on?

Chrome

### Computer Operating System

NA

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Re "permissions": I was able to reproduce it for a limited timeframe by deactivating the `Feedback` plugin. A logged in account was not able to experience the issue (rate icons immediately hidden), but switching to a guest account showed the rating icons but the translations were missing due to the deactivated plugin. So perhaps more "caching" than "permissions".

**Comment by sgiehl** [comment]
The RateFeature will automatically be used when the javascript for it is available:
https://github.com/matomo-org/matomo/blob/ff812d1faeab4d7f712289b53883b14a4e6910cb/plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue#L81

So if the browser has cached the JS or the Matomo cache isn't cleared after the plugin was deactivated, it might be shown, but the translations are no longer loaded.
We could maybe add a check somewhere in the javascript, that checks if the plugin is enabled or similar, to prevent it from being shown if deactivated.
