### ISSUE TITLE
PDF/HTML Reports: Expand Actions reports (and some others) by default

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#2137]
It would be sometimes useful to Expand (show recursively) the data for some reports since the expanded data is very important for these:
- Page Urls, Page Titles, Outlinks, downloads
- [Custom variables name /values](http://piwik.org/docs/custom-variables/)
- [Campaign names/keyword](http://piwik.org/docs/tracking-campaigns/)

When creating the Scheduled report, users could check a box "For Pages, Downloads, Outlinks report, Expand and show Top Pages in the hierarchy"
- if a category has 10 children categories and pages, I propose we display the 4 top ones in each sub category.
- The 5th listing will be the truncated row ("Others") or the 5th page/category if there were only 5.
  - countries/fr/paris/
  - countries/fr/marseille/
  - countries/fr/lyon/
  - countries/fr/bordeaux/
  - countries/fr/Others (this is the truncated row)

See  #2816 and #2742

This was reported in the forum [this post](http://forum.piwik.org/read.php?2,72844) and [here](http://forum.piwik.org/read.php?3,83855)

**Comment by OG2K** [comment]
Need very much to expand pathes of entry pages in report to justify behaviour of user. See more #6655 Thank you!

**Comment by OG2K** [comment]
Hi there,

Where itg is implemented?
Where to tick a box to get pathes expanded in the pdf reports?

/A

**Comment by mattab** [comment]
Hi @OG2K 

the issue is opened, so it's not implemented yet.

**Comment by OG2K** [comment]
ok, I wait. and it is nice to know that it will be implemented. /A

**Comment by mattab** [comment]
Now that flatten is very fast for Page URLs I reckon it would be really useful to flatten Page URL report by default in Scheduled reports

**Comment by RMastop** [comment]
+1 for the flatten Page URL scheduled report.

**Comment by johnnydevs** [comment]
+1 for this feature too

**Comment by OG2K** [comment]
+1 since, 10 months of ticket active

**Comment by WittTheRock** [comment]
+1 
currently I change global settings to get this feature (hardcoded), but that changes every table too.

**Comment by johnnydevs** [comment]
@WittTheRock how's that working out for you?

**Comment by WittTheRock** [comment]
not a good solution, but i set the get parameter "flat" always to 1

**Comment by PeterMakkes** [comment]
+1

**Comment by OG2K** [comment]
+1

**Comment by fberke** [comment]
Since Custom Variables are going to be dropped in favour of Custom Dimensions at some point, would those be expandable as well? Dimensions currently don't seem to selectable for e-mail reporting at all, event with the plugin installed.

Additionally, the presentation of Events in the e-mail reporting is not very satisfying. Event Categories, Actions, and Names are shown in separate tables, although the data makes more sense if displayed in hierarchical composition.

**Comment by mattab** [comment]
> Dimensions currently don't seem to selectable for e-mail reporting at all, event with the plugin installed.

@fberke  FYI Custom Dimensions are available in the Scheduled reports, under the category `Actions` for actions dimensions, and  under `Visits` for visit custom dimensions.

**Comment by gaumondp** [comment]
As of 2.16.1 adding "&flat=1" works in PDF at least for URL. Why not make a quick fix by adding the checkbox to the "create email reports" interface with "Expand URL" ?

You can't count on asking simple editors to modify urls by hand...

**Comment by Fensterbank** [comment]
I just wanted to ask what's the current state of this issue?
I checked a few pull requests but didn't find the answer. Is in the current state of development a flat view of custom variables already possible?
If not, how big is the chance, to get all this in 3.0.0?

We are using Scheduled Reports via Mail and track user selected UI languages. It's useless when product owners receive a PDF report but doesn't see which language has been selected in the non-flatten view.

**Comment by mattab** [comment]
@Fensterbank in Piwik 3, all scheduled reports will show Flattened reports, when they support it. Flatten is enabled for all reports and can't be disabled. Should be a big win for all readers of the email reports! :+1:

**Comment by TobeBenn** [comment]
Hey,
is this point really enabled in Piwik 3.0.1???

still got summarized URLs in pdf-mail-reports
![url](https://cloud.githubusercontent.com/assets/25386460/23205583/b5a3676e-f8ea-11e6-8341-0aacab2777a3.JPG)
