### ISSUE TITLE
[Bug]: anomaly in the Matomo Analytics tool

### ISSUE THREAD

**Issue by Vastruc** [piwik/piwik#21379]
### What happened?

While monitoring the group intranet indicators, we identified an anomaly in the Matomo Analytics tool. Indeed, the IP addresses of visitors to eramet|inside (intranet) are unexpectedly geolocated in Israel, as illustrated in the screenshots below. Could you assist us in comprehending this situation? It appears that this issue is related to the database utilized by Matomo to match IP addresses with locations, which seems to be outdated.
We are providing you with the complete list of IP addresses (IP Address column) used, along with their corresponding physical locations, to update in the Matomo tool :

https://config.zscaler.com/zscalerthree.net/cenr
![Unknown-1](https://github.com/matomo-org/matomo/assets/147185401/8e507e72-8ad3-4e8b-a8c7-9de934c19cdd)
![Unknown-2](https://github.com/matomo-org/matomo/assets/147185401/10f7001e-22cd-4f22-aeb3-c1ae3247ed65)
![Unknown-3](https://github.com/matomo-org/matomo/assets/147185401/3fa5ddd8-207e-4fd1-9e69-f6e9eeab26b1)
![Unknown](https://github.com/matomo-org/matomo/assets/147185401/0b8dc3aa-3cf6-4ae3-8a27-f61e8b90f9df)

### What should happen?

While monitoring the group intranet indicators, we identified an anomaly in the Matomo Analytics tool. Indeed, the IP addresses of visitors to eramet|inside (intranet) are unexpectedly geolocated in Israel, as illustrated in the screenshots below. Could you assist us in comprehending this situation? It appears that this issue is related to the database utilized by Matomo to match IP addresses with locations, which seems to be outdated.

### How can this be reproduced?

https://matomo.eramet.com/index.php?module=MultiSites&action=index&idSite=10&period=day&date=today

### Matomo Version

Matomo 3

### Matomo Patch or Minor Version

??

### PHP Version

??

### Server Operating System

??

### What browsers are you seeing the problem on?

Chrome

### Computer Operating System

laptop HP

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @Vastruc,

Matomo itself does not ship a GeoIP database with the product. Instead you can manually configure the database you want to use. The database can be from DBIP or Maxmind, but there are also third party plugins for other providers.
See e.g. https://matomo.org/faq/how-to/setting-up-accurate-visitors-geolocation/

Anyway. If you are still using Matomo 3, I would suggest to first update to Matomo 4, as it includes a couple of improvements around geolocation.

Cheers,
