### ISSUE TITLE
[Bug]: Broken link/redirect

### ISSUE THREAD

**Issue by tumd** [piwik/piwik#21389]
### What happened?

Not really a problem with Matomo per se, but rather your webpage having a faulty redirect. However linked to from Matomo.

I wanted to read up on your "[Web Analytics Privacy](https://matomo.org/docs/privacy/)" linked to from Matomo, but ended up with a screenshot of the 'Anonymize data'-page.

### What should happen?

I think the link was suppose to get me to https://matomo.org/privacy/, perhaps?

### How can this be reproduced?

1. Go to Admin -> Privacy -> Anonymise Data.
2. The highlighted link can be found in the text in the top of the page;
   > ... See also our official guide: [Web Analytics Privacy](https://matomo.org/docs/privacy/)

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.0.0-rc4

### PHP Version

8.2

### Server Operating System

Debian 12

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer Operating System

MacOS

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
I guess it's more likely meant to link to https://matomo.org/guide/manage-matomo/privacy/
@bx80 could you maybe update that link as part of the issue you are currently working on?

**Comment by bx80** [comment]
I've corrected the link as part of this PR commit https://github.com/matomo-org/matomo/pull/21375/commits/fd4e6a54d95dabd6e858b37e073b5ff463221b9c

**Comment by sgiehl** [comment]
Should meanwhile be fixed.
