### ISSUE TITLE
[Bug]: the color of the rebound percentages is incorrect

### ISSUE THREAD

**Issue by macintoshplus** [piwik/piwik#21381]
### What happened?

The color of the rebound (visitor out after one page) percentages is incorrect. 

If this value is negative, it's good news for the website. but, if the value is positive, it's bad news for the website.

![image](https://github.com/matomo-org/matomo/assets/814683/2052d97a-ec1a-46b6-8e50-d51e1e51e88b)

### What should happen?

Only for the rebound value (visitor leave after one page):

The color must be green with a green top arrow if the value is negative.

If the value is positive, the color must be red with a red down arrow.

### How can this be reproduced?

Add the widget "Visits summary" on the dashboard.

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

all

### PHP Version

All

### Server Operating System

All

### Computer Operating System

All

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @macintoshplus 
Thanks for creating this report.
I guess you are still on the lastest release of Matomo 4. In Matomo 5 this will be fixed (see https://github.com/matomo-org/matomo/issues/20788)

**Comment by macintoshplus** [comment]
Yes, I'm in the latest version of Matomo 4. Good job for Matomo 5.
