### ISSUE TITLE
PIWIK_DOCUMENT_ROOT instead of PIWIK_INCLUDE_PATH used

### ISSUE THREAD

**Issue by Flachdachs** [piwik/piwik#21382]
If these lines are needed `PIWIK_INCLUDE_PATH` should be used or it breaks Matomo when you use a different include path.
https://github.com/matomo-org/matomo/blob/8770cde10eafa3f9c22e3030b9ac33a26a175eff/plugins/TwoFactorAuth/Dao/TwoFaSecretRandomGenerator.php#L10
https://github.com/matomo-org/matomo/blob/8770cde10eafa3f9c22e3030b9ac33a26a175eff/plugins/TwoFactorAuth/TwoFactorAuthentication.php#L20

**Comment by Flachdachs** [comment]
Actually more things are broken when using the concept of PIWIK_INCLUDE_PATH. There are files at least in `plugins` and `libs` that the browser should read.

**Comment by sgiehl** [comment]
Currently the structure doesn't really allow a difference between root and include path.
I guess you intention might be similar to https://github.com/matomo-org/matomo/issues/19505, so I'll close this one.
