### ISSUE TITLE
[Bug]: 2fa setup - no OTP code

### ISSUE THREAD

**Issue by tumd** [piwik/piwik#21380]
### What happened?

I'm trying to set up 2fa on the initial admin-account, and can not use the barcode to install it in my OTP app.
Instead I try to retrieve the (numerical) code by clicking "Enter this code"-link. However this link only gives me an empty popup, without showing the code;

![2fa-code](https://github.com/matomo-org/matomo/assets/463066/ffabe4b3-8cee-4b1e-979d-da6bfb2337bc)

### What should happen?

In the "enter this code"-popup I expect to see a copyable number sequence to insert into my 2fa application.

### How can this be reproduced?

1. Logged in as admin, go to the settings page, and in the menu continue to Personal -> Security and click the button "Turn on two-factor authentication".
2. Complete Step 1.
3. Click the highlighted link in the text;
   > Next, open the app and scan the barcode below with the OTP app on your mobile device. **_Enter this code_** if you can't scan the barcode.
4. Behold the empty popup pictured above

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.0.0-rc4

### PHP Version

8.2

### Server Operating System

Debian 12

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer Operating System

MacOS 13.6

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @tumd 
Thanks for reporting this one. I was able to reproduce it and will work on a fix before our next release.
Cheers,
