### ISSUE TITLE
[Bug]: Ecommerce order showing incorrect price and quantity (possible string parsing issue)

### ISSUE THREAD

**Issue by jalavosus** [piwik/piwik#21392]
### What happened?

Client uses Shopify for their ecommerce setup, along with Matomo for tracking. 

Client had an order placed for 1 (one) $6,795 subtotal product, plus shipping. 

Matomo shows this order as quantity: 795, price: $6. 

Product itself has three packages plus two options which determine price: Package A, Package B, Package C, and each package can select Option X or Option Y, all of which affect the price of the item. 

### What should happen?

Matomo tracking should show the correct quantity and amount for the product: 1 x $6,795. Preferably, the correct options/packages would be reflected as well.

### How can this be reproduced?

Unsure, as this is related to making a purchase (possibly large). 

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15.2-b1

### PHP Version

Unavailable

### Server Operating System

Unsure

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer Operating System

macOS 12.6 ("Monterey")

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @jalavosus 
I guess the problem is, that the number was provided formatted. it should work correctly when the number does not contain thousands separators.
For further help on how to integrate Matomo with Shopify see https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-shopify-store/

**Comment by jalavosus** [comment]
@sgiehl That... really isn't an answer, in any which way. 

First, the Matomo FAQs for Shopify don't seem to provide any information on proper passing of data from Shopify to Matomo, other than "It'll pass the data and show up!". If further documentation exists, that would be great to have.
Second, this _is_ a bug in Matomo - sanitizing inputs should be on the data collection platform, not on the user who's just following directions.

**Comment by sgiehl** [comment]
The problem actually seems to happen on the website calling the tracking methods and not on Matomos end.
I assume the shopify integration uses some sort of variables that are passed to the ecommerce methods.
So there is something like 
`_paq.push(['addEcommerceItem', "{SKU}", "{Category}", {Price}, {Quantity})`
When the placeholders are replaced and the price is replaced with a formatted number this e.g. ends up in
`_paq.push(['addEcommerceItem', "sky", "category", 6,875.9, 1)`
So it actually sets `6` as price parameter, `875.9` as quantity and the actual quantity of `1`, would be thrown away.

Hope that helps you to understand the problem. I'm not familiar with Shopify, so can't you help with a solution on that site.

**Comment by jalavosus** [comment]
Now that is an answer. Thank you. I'll work with that.

**Comment by smerriman** [comment]
For reference, this _was_ a bug on Matomo's side - the documentation page [as is stood in July](http://web.archive.org/web/20230707041035/https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-shopify-store/) (where we copied it from) used the _money_without_currency_ filter, which output these incorrect commas.

It appears someone already fixed the bug in the documentation as the current version of the page works - we just hadn't known to update the code accordingly.
