### ISSUE TITLE
Append one more possibility to the error message given for InvalidNonceReferrer

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21391]
The error message is in the JSON table here [plugins/Login/lang/en.json](https://github.com/matomo-org/matomo/blob/dbeffa30f009c41974f85889c07a3bdc17aeeb22/plugins/Login/lang/en.json#L9)

Expected
"InvalidNonceReferrer": "The form security failed because of an invalid \"Referer\" header. If you are using a proxy server, you must %1$sconfigure Matomo to accept the proxy header%2$s that forwards the host header. Also, check that your \"Referer\" header is sent correctly. If you previously connected using HTTPS, please ensure you are connecting over a secure (SSL/TLS) connection and try again. **Also check that allowedReferrerHost is not NULL**"

Actual
        "InvalidNonceReferrer": "The form security failed because of an invalid \"Referer\" header. If you are using a proxy server, you must %1$sconfigure Matomo to accept the proxy header%2$s that forwards the host header. Also, check that your \"Referer\" header is sent correctly. If you previously connected using HTTPS, please ensure you are connecting over a secure (SSL/TLS) connection and try again."

**Comment by atom-box** [comment]
_This is in response to the following user email:_  

> (The error message for InvalidNonceReferrer) tells me the Referrer is not set correctly, but var_dump shows it set just perfectly. The real problem is that allowedReferrerHost is NULL and it's very unclear where allowedReferrerHost is supposed to be configured.
> 
> I traced this back to Nonce.php where it appears to be triggered by $allowedReferrerhost being NULL. $referrer is set correctly to "https://s.wanwire.com".
> 
> (I managed to get around it, but the error message is both incorrect and unhelpful.)

**Comment by sgiehl** [comment]
I don't think this addition will bring any benefit to the (end) users, as they wouldn't be able to change anything. The `allowedReferrerHost` is provided in the code and `null` is actually valid.
If there is a specific problem where that check fails we should look at that place.
