### ISSUE TITLE
[Bug]: Search icon not showing up on the device report

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#21406]
### What happened?

The search icon does not show up on the device report.

### What should happen?

Well, it should be displayed (the green icon)

### How can this be reproduced?

Just go on https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=week&date=2023-10-14&category=General_Visitors&subcategory=DevicesDetection_Devices then over your mouse at the footer of the report and you will see that it is not showing.

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15.2-b1

### PHP Version

8

### Server Operating System

??

### What browsers are you seeing the problem on?

Firefox

### Computer Operating System

Ubuntu

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
Thanks for reporting this @Chardonneaur.

Checking the [report code](https://github.com/matomo-org/matomo/blob/aecb3f414b3a9f24344719d84151defdecfdf57b/plugins/DevicesDetection/Reports/GetType.php#L30) it looks like the search function for this report has always been disabled. I can't see any good reason for that so I've created [a quick PR](https://github.com/matomo-org/matomo/pull/21412) to enable search on this report.

**Comment by sgiehl** [comment]
Just for completeness: The search was disabled on this report (on purpose), as it has a fixed number of records that is quite low. Matomo is capable to detect 14 different device types, so there can only be 14 rows at max. Having that searchable doesn't provide much benefit, but won't hurt either...
