### ISSUE TITLE
[Bug]: evolution over the period: metrics name is not URL decoded

### ISSUE THREAD

**Issue by macintoshplus** [piwik/piwik#21409]
### What happened?

The metric names contain `%20` instead of the space character.

![image](https://github.com/matomo-org/matomo/assets/814683/3d6868de-2a48-4d38-883e-213aa825675e)

### What should happen?

The name should be URL decoded to get the original metric name. When I select the metrics in the menu, the graph works fine.

### How can this be reproduced?

Use Matomo in french, and go to [Acquisition] > [Récapitulatif]

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15.1

### PHP Version

8.1.23

### Server Operating System

GNU/Linux Debian 11

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Computer Operating System

GNU/Linux Ubuntu 22.04

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
Thanks for reporting this @macintoshplus :+1: 

The bug has [previously been spotted](https://github.com/matomo-org/matomo/issues/21051) and has been fixed in Matomo 5.
