### ISSUE TITLE
Option to put a notes in visitors profiles

### ISSUE THREAD

**Issue by emernual** [piwik/piwik#21415]
Matomo user reached out to support requesting for a feature. 

To have an option to be able to put a notes in visitors profiles which improve tracking traceability.

**Comment by bx80** [comment]
Hi @emernual, thanks for reporting this, it sounds like a useful feature. There is already an [existing feature request ](https://github.com/matomo-org/matomo/issues/8161) that covers this exact functionality, so I'll close this issue in favour of it.
