### ISSUE TITLE
[Bug]: Can not enter my password when inviting a new user

### ISSUE THREAD

**Issue by Pilot001** [piwik/piwik#21423]
### What happened?

This happened after updating to v4.15.1 (previous 4.13.0).

When inviting a new user a password prompt opens up:
![image](https://github.com/matomo-org/matomo/assets/13788225/0737df70-3969-4a47-a249-cf92215cb42b)

But clicking on the password line does not make a text cursor to appear. It looks like there was no input line in that dialogue, so I can not enter my password.

I also think that I found a possible reason. Comparing the generated code between this and the previously used version, there is now an additional `disabled=""` inserted into the code. As soon as I manually remove this with the browser debugging tools, I can use the password prompt as expected.

Current:
![image](https://github.com/matomo-org/matomo/assets/13788225/2c64c61e-063c-4f42-965e-d46b1432229a)
Previous:
![image](https://github.com/matomo-org/matomo/assets/13788225/038ec03f-90f9-403d-b95d-4a87b530e0f9)

### What should happen?

I should be able to enter my password.

### How can this be reproduced?

Create a new user invitation, click on invite and try to enter your password.

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15.1

### PHP Version

8.0.30

### Server Operating System

SuSE Linux Enterprise Server 15 SP4

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other

### Computer Operating System

openSuSE Leap 15.4

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by AltamashShaikh** [comment]
@Pilot001 Are you using LoginSaml or LoginLdap plugin by any chance ?
If yes you need to enable `enable_password_confirmation` config setting, can be done via UI, you need to login as administrator and update the setting

![image](https://github.com/matomo-org/matomo/assets/14902277/c54f13d0-fa1e-46d2-b91b-ac204982498e)

**Comment by Pilot001** [comment]
Thank you for your repsonse.
I don't have the LDAP plugin installed. The SAML plugin is installed (for testing purposes), but currently not in use:
![grafik](https://github.com/matomo-org/matomo/assets/13788225/8d49c9c6-efec-4eec-9afa-28b6014fdc2b)
Nevertheless, this worked. Thank you!

But to be honest: Where is the logic behind that? Obviously Matomo requires to enter your password when creating/inviting a new user, but you are not able to enter it, if you do not enable this option? And this even the use of the plugin is disabled? I know this was working before so I consider this to be a bug.

**Comment by AltamashShaikh** [comment]
@Pilot001 If you have plugins like SAML in use this becomes redundant as you don’t add a password in Matomo, the authentication happens with the LDAP/SAML server.

If you still need it you can enable it via UI setting.

we have https://github.com/matomo-org/matomo/issues/20186 to make this behaviour more better, closing this as we already have #20186

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/inputfield-for-password-confirmation-on-deleting-a-user-is-disabled/53743/2
