### ISSUE TITLE
[Bug]: Websites -> Manage page not working

### ISSUE THREAD

**Issue by tumd** [piwik/piwik#21432]
### What happened?

Navigate to Settings -> Websites -> Manage (https://matomo.example.com/index.php?module=SitesManager&action=index)

Shows a blank page:

<img width="1006" alt="SCR-20231024-opav" src="https://github.com/matomo-org/matomo/assets/463066/c4f111d1-8cd8-4f2f-9673-b3ada11d27ae">

### What should happen?

Not blank page.

### How can this be reproduced?

Navigate to Settings -> Websites -> Manage

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.0.0-rc5

### PHP Version

8.2.7

### Server Operating System

Debian 12

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer Operating System

MacOS 13.6

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
Thanks for reporting this @tumd :+1:

Looks like this bug managed to sneak through RC testing. I've created a [PR](https://github.com/matomo-org/matomopull/21435) to fix the issue which will be in the next RC release.
