### ISSUE TITLE
Cannot isolate events happening on a specific page using segments

### ISSUE THREAD

**Issue by infor-pranav** [piwik/piwik#21438]
Hi Team,

I had a question regarding how segments work in tandem with event tracking. My team has set up events on various pages of our website. One of our goals is to view event categories, names and actions only for Events happening on a specific page. To do this, we created segments by filtering for each page title individually. However, when I apply this segment and land on the Events page under the Behavior tab, I am seeing more than the expected number of events. Is there a bug in this functionality? If not, can you please explain the expected behavior here?

Thanks,
Pranav Sood

**Comment by sgiehl** [comment]
Hi @infor-pranav 

This might currently not work with segments. Segments are designed to filter for certain visits only. So if you create a segment looking for a certain action url, the result will present you all data for visits that contained a certain action url.
Those data will also contain any other url and event those visits contain. What you might be looking for are something like filters, which are currently not supported. See https://github.com/matomo-org/matomo/issues/15438 for more details.

**Comment by heurteph-ei** [comment]
Hi @infor-pranav 
You can use https://plugins.matomo.org/CustomReports premium plugin to create reports filtered on page URLs...
