### ISSUE TITLE
[Bug]: Metrics are disappearing in the graph in custom reports

### ISSUE THREAD

**Issue by Chaprou** [piwik/piwik#21441]
### What happened?

In the custom reports, I have a problem with the custom metrics displayed the graphs.
When the graph is loaded, I have all the metrics that I asked for as it should be.

However, as soon as I want to unbox one of the metrics so that it won't be displayed in my graph anymore, several metrics are erased at the same time.

If I want to get my metrics back, I have to reload the page.

Example: What I have at the beginning
![Bug metrics rapport matomo](https://github.com/matomo-org/matomo/assets/143426708/c442542f-7fbd-419d-af7d-48e943f75c09)

When I unbox one of the metrics:
![Bug metrics rapport matomo 2](https://github.com/matomo-org/matomo/assets/143426708/371215be-4b68-494d-a40d-c29e25496db1)

### What should happen?

I should be able to unbox one metric and keep all the others in my graph.
Moreover, I should be able to unbox a metric, and then check it once again in the list if I want it back on my graph, without having to reload the page.

### How can this be reproduced?

Go to a cutom report with a multiple metrics graph in Matomo and try unboxing some metrics.
Check whether you have only one metric disappearing or not

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

4.15.1

### PHP Version

N/A

### Server Operating System

N/A

### Computer Operating System

Windows 10

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
Hi @Chaprou, thank you for creating this issue. In this issue tracker we only manage issues for Matomo core. For premium feature related inquiries please email our support at shop@innocraft.com. Thank you for you understanding and sorry for the inconvenience.
