### ISSUE TITLE
[Bug]: FAQ link is truncated in error message

### ISSUE THREAD

**Issue by bx80** [piwik/piwik#21453]
### What happened?

The error message "This user has at least some write access. Only tokens of users who have only view access can be used. Check [link] for more info." now has the external link campaign parameters appended to the [link] this is causing the link to be too long to show on the screen.

![image](https://github.com/matomo-org/matomo/assets/88810029/11521656-ee2f-4de5-85bf-9819d7229a7b)

### What should happen?

The link should be clickable and be displayed without the parameters. The campaign parameters should only be included in the link href.

### How can this be reproduced?

Appears in UI test screenshots for ActivityLog plugin.

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.x-dev

### PHP Version

8.2.11

### Server Operating System

Debian 12

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer Operating System

Windows 3.11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
How's your OS going? Still strong and reliable?
