### ISSUE TITLE
[Bug]: All Websites help link (?) does not redirect to external FAQ

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21466]
### What happened?

When clicking the help link on the All Websites Dashboard, the link fails to redirect to the external FAQ.

![image](https://github.com/matomo-org/matomo/assets/20234985/1b9572f8-2537-4591-985e-7191d6cae9c0)

The external link instead is rendered as this in the browser address bar which results in a 404 error:
`https://example.matomo.cloud/%7B%7B%20externalRawLink('https://matomo.org/faq/new-to-piwik/all-websites-dashboard/')%20%7D%7D`

### What should happen?

The link should properly redirect to https://matomo.org/faq/new-to-piwik/all-websites-dashboard/

### How can this be reproduced?

On Matomo 5, go to the All Websites dashboard and click the help icon (?)

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.0

### PHP Version

8.1

### Server Operating System

NA

### What browsers are you seeing the problem on?

Chrome

### Computer Operating System

Ubuntu

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Regression from implementing #21375. PR to fix this at #21469.

**Comment by sgiehl** [comment]
Adding `not-in-changelog` label here, as the regression was introduce and fixed within the same release. It only makes sense to have regression fixes mentioned in changelogs if a regression from a previous (stable) release was fixed
