### ISSUE TITLE
[Bug]: Deprecated - Creation of dynamic property - PHP 8.2

### ISSUE THREAD

**Issue by caddoo** [piwik/piwik#21471]
### What happened?

Since PHP 8.2 Creation of dynamic properties are deprecated and cause a deprecation notice when running UI tests

### What should happen?

There should be no deprecation notices due to this.

### How can this be reproduced?

Access different pages via the PHPunit proxy and you will see messages like:

<img width="759" alt="image" src="https://github.com/matomo-org/matomo/assets/1169490/261ef19c-1254-4ce2-b646-35075536cda2">

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

0

### PHP Version

8.2

### Server Operating System

MacOS

### Computer Operating System

MacOS

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@caddoo When creating new issue, please try to directly add correct labels.
