### ISSUE TITLE
Issue with Auto-Update Function in RC6

### ISSUE THREAD

**Issue by caddoo** [piwik/piwik#21488]
### Background

<img width="229" alt="image" src="https://github.com/matomo-org/matomo/assets/1169490/f3ec0408-9cc6-4559-ba90-183c55258487">

We've identified an issue with the auto-update function when transitioning from RC6 to RC7. Users may encounter difficulties during this process, [we have already resolved it](https://github.com/matomo-org/matomo/pull/21447). To ensure a smoother update experience, we recommend implementing the following workaround:

### Workaround

Manually go to the URL:

`https://{yourhost}/index.php?module=CoreUpdater&action=newVersionAvailable`

Where `{yourhost}` is the host of the Matomo instance, for example if your Matomo instance is hosted on `https://analytics.mysite.com` then you should visit:

`https://analytics.mysite.com/index.php?module=CoreUpdater&action=newVersionAvailable`

Once there simply click the green `Update automatically` button.

<img width="740" alt="image" src="https://github.com/matomo-org/matomo/assets/1169490/3042b98b-0491-401b-a6f1-de680cd3b9c1">

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/important-notice-for-rc6-users-auto-update-issue/53903/1

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/5-0-rc-7-upgrade-issue-tried-again-and-all-is-well/53935/3
