### ISSUE TITLE
[Bug]: Matomo sends out Custom Alerts on incomplete data

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21499]
### What happened?

We have various custom alerts configured on a "day" level. For example, notify us if traffic drops by 25%.

Matomo at times sends out custom alerts on incomplete data.

Example:
* Say we had 100K visits on Monday.
* It's Tuesday 7PM and Matomo generates reporting data to consider all visits from 0AM-7PM. Result: 70K visits
* It's now Tuesday midnight. Since 7PM we had 20K more visits making it 90K visits overall. Matomo has not yet updated the report that says "70k visits" as Matomo only updates reports every X hours (this is configurable).
* It's now Wednesday 1AM. 
* Matomo checks the Custom Alerts conditions. The last report Matomo has available says we had 70K visits.
* 70K visits is a 30% drop. As a result, Matomo sends an email that we had a drop of 30% traffic putting us into panic mode.
* However, we actually didn't have a 30% drop but a 10% drop only and we should not have been alerted.

We also know that some people have on-call teams hooked up against custom alerts and people may be falsely woken up at night because of false alerts.

*Note that the same thing may happen for [scheduled reports](https://matomo.org/faq/general/create-and-schedule-a-report/). This is something that would need to be checked.*

### What should happen?

Matomo should make sure before sending out an alert that the data is based on complete data, not just partial data of a day.

### How can this be reproduced?

For more information see DEV-17369

I assume you can reproduce it by:
* Disabling browser archiving
* Archiving reports on the command line
* Tracking more data for yesterday
* Run the custom alerts task
* The email will be sent based on inaccurate data

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

0

### PHP Version

.

### Server Operating System

.

### Computer Operating System

.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by tsteur** [comment]
fyi @mattab

**Comment by snake14** [comment]
As the related PR for CustomAlerts has been merged, I'm going to go ahead and close this issue. The next release of the CustomAlerts plugin should resolve the issue.
