### ISSUE TITLE
[Bug]: After Nov 2023 daylight saving, old time is still showing

### ISSUE THREAD

**Issue by aimran50** [piwik/piwik#21497]
### What happened?

All visits are recorded with time before daylight savings. Plus one hour. So if the current time is 1600, the visit log time will show 1700.

Tried setting the timezone in Settings > Websites > Settings, but it is not working.

### What should happen?

Correct time as per the set timezone should be displayed.

### How can this be reproduced?

Not sure. Maybe set up an instance with time before daylight, move the clock one hour back or change the timezone UTC minus one and see if the visits display the new time.

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

15.1

### PHP Version

php-7.4.27-Win32-vc15-x64

### Server Operating System

Windows server

### What browsers are you seeing the problem on?

Firefox

### Computer Operating System

Windows

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@aimran50 Matomo stores all data in UTC in the database. When data is being aggregated and displayed for a certain website, the data will be converted to the timezone of the selected website.

Changing the timezone in the website settings will always only have an effect on reports archived **after** the setting was changed, unless you invalidate all reports an archive them again.
Note: The visits log and profile are handled a bit different, as they are showing unaggregated data. That means changing the websites timezone might directly change the displayed values.

Based on your report it's a bit hard to easily identify the exact problem. Would you mind providing some more details?
Like which timezone is or was configured for your website in Matomo and which reports are affected by the problem. Is it only the visits log or also visible in the visitor profile...

**Comment by aimran50** [comment]
"Changing the timezone in the website settings will always only have an effect on reports archived after the setting was changed, unless you invalidate all reports an archive them again." **This is not working.** 

In the website settings, I tried setting to both UTC -6 and Chicago. But the hour is always showing the pre-daylight savings time. One hour ahead. Previously, I had PHP7. I tried upgrading to PHP 8.1, but that did not resolve it either. All the records are off. What else can be done? If you tell me specifically what more details to provide, I will be happy to.

**Comment by sgiehl** [comment]
As mentioned before: Matomo internally stores the time in UTC. So any timeshift in a local timezone won't have an effect on the time that is tracked.
The reports displayed in Matomo are built based on the websites timezone. So the times stored internally are sort of converted to the according timezone again.
If you change the timezone of a website, all reports that are built after the switch will respect the new timezone. Reports built before will still have the old. If you want to update old reports you need to invalidate and reprocess them.

If some data was tracked with incorrect time for any reason, there is unfortunately nothing we can do about that, as updating the time of old visits doesn't work easily.
