### ISSUE TITLE
Matomo evolution graphs could be confusing, making you believe data is accurate/complete when it might not be

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21498]
### What happened?

See below screenshot as an example. The same applies to all evolution graphs though:

<img width="1674" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/5999f39a-7f12-43ad-b687-d55dc4decd59">

Above screenshot showing 9717 visits for yesterday but we may have had actually 10K visits on the demo. It appears like we had 9717 visits when in fact this might not be the case.

#### More explanations

When viewing "today's data" then the last day is always shown with a "dotted line" so people are aware that the data for this day is not complete yet. This is a great feature.

However, it makes you believe that all the other days that have an unbroken line are complete/ finished and shows accurate data.

This might not be the case though.

That's because Matomo archives data only every 15minutes to 24 hours. On Cloud, we're processing data for example every 6 hours.

This means that for example on Cloud for up to 6 hours yesterday's data is incorrect as we haven't generated the full/complete/finished report. Yet the unbroken line lets you to believe that the data is accurate and "complete".

For example:
* Yesterday is 7. Nov 2023
* It is 10PM and reports gets generated. The report shows 50K visits.
* It is now midnight and yesterday we had 60K visits.
* You view the data at 4AM
* Matomo shows still the report data from yesterday 10PM showing 50K visits when there were in fact 60K visits. However, it looks like Matomo is showing the data for the full day which includes all visits up to midnight because there isn't a dotted line. Matomo shows an unbroken line in those cases.
* Only at like 6AM the full data for yesterday might be available.

This makes Matomo look buggy and not trustworthy.

You might think it's an edge case as not many people few the data before say 6 or 7 AM.

However, we need to take into consideration:
* that sites are at times in different timezones making this a much bigger issue. Think for example of the US with many different time zones. Or in our example we are in NZ but the site's timezone is in France. 
* Reports sometimes also get invalidated automatically and need to be re-processed, for example when importing data via logs. In those cases any day may show incomplete data at any time of the day.

### What should happen?

Whenever data is not fully processed yet, Matomo should show a dotted line so people can understand we have not generated the full report yet. This makes it clear for users that they are seeing incomplete data.

### How can this be reproduced?

* View our own analytics data at say 1PM NZ time for today (the site is configured in French timezone so it's 1AM in France and past midnight)
* You will see Matomo shows an unbroken line for yesterday
* Few hours later you will see that number for yesterday will change again and you weren't seeing the accurate number of visits for yesterday at 1PM

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

0

### PHP Version

.

### Server Operating System

.

### Computer Operating System

.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by Stan-vw** [comment]
just to check if I understand it correctly:
- the last dot in the graph is fine (because it's a dotted line showing that it's not finalised)
- the second to last dot in the graph is sometimes fine and sometimes not, due to time of archiving
- while the second to last dot in the graph is awaiting its last planned archiving process, you suggest we show it with a dotted line

Is that correct @tsteur ?

**Comment by tsteur** [comment]
Yes. However, this could be the case for any dot in the graph.
Ideally, we would check every for every dot in the graph if data is complete and present it accordingly.

For example, someone might track data for a day last week. Like someone now tracked data for Nov 16th. Then Matomo considers that report invalid/outdated and a dotted line would need to be shown until Matomo has regenerated that report.

**Comment by Stan-vw** [comment]
Does Matomo know when data is incomplete? In your example, how would Matomo know that data should still come in for Nov 16th?

**Comment by tsteur** [comment]
Yes Matomo would know that it's incomplete 👍 

When there is a tracking request for other days Matomo will remember this.
