### ISSUE TITLE
Understanding Revenue Metrics: Differences, Calculations, and Significance

### ISSUE THREAD

**Issue by Mendels0n** [piwik/piwik#21503]
Hello. Could you please tell me what is the difference between these metrics: revenue, revenue_attrib, and revenue_entry? How are they calculated, and why is revenue such a big numbers?  
I haven't found anything about it anywhere.

**Comment by michalkleiner** [comment]
Hi @Mendels0n, and thank you for opening the issue.
Unfortunately the issue tracker is dedicated to either reporting bugs in Matomo itself or raising enhancements and feature requests, we are not able to provide support through the issue tracker.
If you don't mind, I would direct you to the [forum](https://forum.matomo.org/) where you can ask the question. Alternatively, if you think there's a bug in Matomo itself, please open a new bug report describing the expected and unexpected behaviour and provide a set of replication steps.
Thank you for your understanding.
