### ISSUE TITLE
Behaviour when receiving both UTM and MTM parameters is not documented

### ISSUE THREAD

**Issue by danielhug-cc** [piwik/piwik#21516]
How does Matomo behave when user visits https://www.example.com?mtm_campaign=campy&utm_source=sourcy
(German forum discussion [here](https://forum.matomo.org/t/wie-ist-das-wenn-eine-url-utm-und-mtm-enthalt/53855).)

In the case of mixed MTM and UTM parameters, what is saved in raw data, and what is used for reports?

There are a few variations possible:
1. Overlapping parameters, such as both MTM and UTM campaign or source parameter
2. Mixed, but not overlapping, such as MTM campaign and UTM source, as in above example
3. Some overlapping, some not
4. Does the order play a role?

Documentation might require a new page or fit somewhere here:
https://matomo.org/faq/reports/common-campaign-tracking-use-cases-and-examples/

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/wie-ist-das-wenn-eine-url-utm-und-mtm-enthalt/53855/6

**Comment by michalkleiner** [comment]
Hi @danielhug-cc, having a quick look it seems the `mtm_` params take priority over `utm_` params, so if you use both `mtm_campaign` and `utm_campaign` with different values the `mtm_campaign` value will be used. If you mix campaign and source, one with `mtm_` and one with `utm_` prefix, that will work fine. The first one found in the URL for the given property (name, source, keyword, medium etc) is used.
I'll pass it for prioritisation on updating an FAQ or creating a new one on this topic.
