### ISSUE TITLE
[Bug]: Bing indexed pages in SEO Rankings not working anymore?

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21520]
### What happened?

The SEO Rankings widgets (eg in Dashboard) is showing an error for "Bing indexed pages".

<img width="490" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/b8c2b283-e6ed-4f83-a2bb-cee77586f3d7">

### What should happen?

No error

### How can this be reproduced?

* Add the widget to the dashboard (see SEO category)
* If no domain is there, enter one. Eg "matomo.org"

Can be reproduced for example in our own analytics

This sounds like a regression?

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

15

### PHP Version

.

### Server Operating System

.

### What browsers are you seeing the problem on?

Chrome

### Computer Operating System

.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@tsteur Locally with Matomo 5 that works without problems and as there hadn't been any changes to the SEO metrics lately I would assume it works with Matomo 4 as well.
Might it be possible that bing blocks requests coming from our cloud?

**Comment by tsteur** [comment]
@sgiehl I actually don't know if it blocks requests coming from our Cloud.

**Comment by AltamashShaikh** [comment]
@tsteur Can this and the #L3-584 be related ? Like our server IP being blocked ?

**Comment by tsteur** [comment]
Possible @AltamashShaikh We could potentially check the logs

**Comment by tsteur** [comment]
This is a regression as it used to work. ping @sgiehl @Stan-vw

**Comment by tsteur** [comment]
Could we add a regression label here @sgiehl @Stan-vw ?

**Comment by sgiehl** [comment]
@tsteur Sure. But it's hard to find a proper fix without trying things on cloud. Locally that works without problems.
You could maybe check if applying https://github.com/matomo-org/matomo/compare/proxyrequests on cloud would fix it.

**Comment by sgiehl** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/21712
