### ISSUE TITLE
[Bug] API BullkRequest with encoded parameters return errors or duplicate content

### ISSUE THREAD

**Issue by ronan-hello** [piwik/piwik#21553]
### What happened?

When you use the BulkRequest API to generate multiple requests, which individually require encoded parameters, the API cannot support these parameters.

For example, the `ScheduledReports.addReport` endpoint requires passing a `parameters` parameter as an encoded array using `EncodeURI`.

The problem is that each URL in a BulkRequest must also be encoded using `EncodeURI`, the `parameters` parameter then ends up encoded twice and Matomo is not able to decode it.

If the `parameters` parameter is not encoded, then all parameters `parameters` be identical for all BulkRequest requests, and the different values ​​will be ignored.

### What should happen?

When Matomo encounters a BulkRequest with encoded parameters, it should be able to decode them.
Today, it interprets request parameters directly without decoding URLs received in BulkRequest

### How can this be reproduced?

This URL sould generate 3 Scheduled reports with parameters `displayFormat` as 1, 2 or 3 (one each).

https://demo.matomo.cloud/?module=API&format=json&token_auth=XXXXXXXXXXXXXXXX&method=API.getBulkRequest&urls[0]=method%3DScheduledReports.addReport%26idSite%3D1%26description%3DYour%20weekly%20analytics%20report%26period%3Dweek%26hour%3D1%26reportType%3Demail%26reportFormat%3Dhtml%26reports%3DMultiSites_getAll%2CVisitsSummary_get%2CUserCountry_getCountry%2CActions_get%2CActions_getPageUrls%2CActions_getOutlinks%2CActions_getDownloads%2CReferrers_getAll%2CGoals_get%2CFormAnalytics_get%2CMediaAnalytics_get%26evolutionPeriodFor%3Dprev%26evolutionPeriodN%3D30%26periodParam%3Dweek%26reports%5B0%5D%3DMultiSites_getAll%26reports%5B1%5D%3DVisitsSummary_get%26reports%5B2%5D%3DUserCountry_getCountry%26reports%5B3%5D%3DActions_get%26reports%5B4%5D%3DActions_getPageUrls%26reports%5B5%5D%3DActions_getOutlinks%26reports%5B6%5D%3DActions_getDownloads%26reports%5B7%5D%3DReferrers_getAll%26reports%5B8%5D%3DGoals_get%26reports%5B9%5D%3DFormAnalytics_get%26reports%5B10%5D%3DMediaAnalytics_get%26parameters%5BemailMe%5D%3D1%26parameters%5BevolutionGraph%5D%3D0%26parameters%5BdisplayFormat%5D%3D1&urls[1]=method%3DScheduledReports.addReport%26idSite%3D1%26description%3DYour%20weekly%20analytics%20report%26period%3Dweek%26hour%3D1%26reportType%3Demail%26reportFormat%3Dhtml%26reports%3DMultiSites_getAll%2CVisitsSummary_get%2CUserCountry_getCountry%2CActions_get%2CActions_getPageUrls%2CActions_getOutlinks%2CActions_getDownloads%2CReferrers_getAll%2CGoals_get%2CFormAnalytics_get%2CMediaAnalytics_get%26evolutionPeriodFor%3Dprev%26evolutionPeriodN%3D30%26periodParam%3Dweek%26reports%5B0%5D%3DMultiSites_getAll%26reports%5B1%5D%3DVisitsSummary_get%26reports%5B2%5D%3DUserCountry_getCountry%26reports%5B3%5D%3DActions_get%26reports%5B4%5D%3DActions_getPageUrls%26reports%5B5%5D%3DActions_getOutlinks%26reports%5B6%5D%3DActions_getDownloads%26reports%5B7%5D%3DReferrers_getAll%26reports%5B8%5D%3DGoals_get%26reports%5B9%5D%3DFormAnalytics_get%26reports%5B10%5D%3DMediaAnalytics_get%26parameters%5BemailMe%5D%3D1%26parameters%5BevolutionGraph%5D%3D0%26parameters%5BdisplayFormat%5D%3D2&urls[2]=method%3DScheduledReports.addReport%26idSite%3D1%26description%3DYour%20weekly%20analytics%20report%26period%3Dweek%26hour%3D1%26reportType%3Demail%26reportFormat%3Dhtml%26reports%3DMultiSites_getAll%2CVisitsSummary_get%2CUserCountry_getCountry%2CActions_get%2CActions_getPageUrls%2CActions_getOutlinks%2CActions_getDownloads%2CReferrers_getAll%2CGoals_get%2CFormAnalytics_get%2CMediaAnalytics_get%26evolutionPeriodFor%3Dprev%26evolutionPeriodN%3D30%26periodParam%3Dweek%26reports%5B0%5D%3DMultiSites_getAll%26reports%5B1%5D%3DVisitsSummary_get%26reports%5B2%5D%3DUserCountry_getCountry%26reports%5B3%5D%3DActions_get%26reports%5B4%5D%3DActions_getPageUrls%26reports%5B5%5D%3DActions_getOutlinks%26reports%5B6%5D%3DActions_getDownloads%26reports%5B7%5D%3DReferrers_getAll%26reports%5B8%5D%3DGoals_get%26reports%5B9%5D%3DFormAnalytics_get%26reports%5B10%5D%3DMediaAnalytics_get%26parameters%5BemailMe%5D%3D1%26parameters%5BevolutionGraph%5D%3D0%26parameters%5BdisplayFormat%5D%3D3

### Matomo major version

Matomo 4

### Matomo minor or patch Version

4.15.1

### PHP version

8.1.0

### Server operating system

Debian 11

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @ronan-hello,

The request you are trying does indeed not work with Matomo 4 as the parser is only able to handle arrays without keys,
not the associative arrays that break your example request.

_You probably have already found that problem as you are trying to send both `reports=` and `reports%5Bxxx%5D` in your example. To pass a real array of reports it would be required to use `reports%5B%5D` (without a key) in the URL. Not passing it in the expected array format would create a report with a single (unknown) statistic instead of 10 individual statistics._

This problem with the bulk request API has already been fixed for Matomo 5.

But as the release of Matomo 5 is planned soon, there are currently no immediate plans to fix that for Matomo 4. Sorry for the inconvenience.

**Comment by ronan-hello** [comment]
Hello,

Thank your for your response.
I understand the situation and if this is fixed for Matomo v5, then it's OK for me !
I wish we can use Matomo v5 as a stable version soon

Regards,
Ronan
