### ISSUE TITLE
Activity Log search feature and "row to display"

### ISSUE THREAD

**Issue by rcontiuk** [piwik/piwik#21552]
It would be very handy to be able to search specific entries in the Activity Log, especially when there are tens of thousands log entries.

There is currently only a **Filter by User** drop down and it would be a great feature if we had something like this:

Filter Name | Filter Type
-- | --
Website | Dropdown
User | Dropdown
Action | Dropdown
Date | Date Selector
Keyword Search | Text

**Website**: List of all websites
**User**: List of all users
**Action**: Most common actions - Settings Changes, Tag Manager actions, User Management Changes, Goals, Heatmaps, etc.
**Date**: Date selector - Similar to the Dashboard: date, week, month and date range
**Keyword Search**: Search for a specific keyword. i.e. name of a tag or goal

Also, having a "Rows to Display" dropdown at the bottom would be helpful because having only 10 lines force users to keep pressing the "Next" or "Previous" buttons. It needs to be more user friendly.

**Comment by AltamashShaikh** [comment]
@rcontiuk Since Activity log is a premium feature can you make a PG ticket ?
