### ISSUE TITLE
Interaction to Next Paint for SEO Web Vitals plugin

### ISSUE THREAD

**Issue by enual** [piwik/piwik#21561]
Customer mentioned that Google is replacing the FID Metric with Interaction to next paint (INP) in March 2024, when will/can this metric be added to the Matomo Web Vitals plugin?

**Comment by AltamashShaikh** [comment]
@enual SEOWebVitals is a premium feature, please watch #PG-2805 in JIRA for further update

**Comment by enual** [comment]
Thank you @AltamashShaikh
