### ISSUE TITLE
AbTesting_Experiments always plots wrong zero metrics series when navigating from one test to another

### ISSUE THREAD

**Issue by leobardimpact** [piwik/piwik#21577]
Steps to reproduce:

1. go to [AbTest overview](matomo/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=AbTesting_Experiments&subcategory=General_Overview)
2. Open any test, ie. "Test1" by clicking "view report", i.e. /matomo/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=yesterday&idSite=1&category=AbTesting_Experiments&subcategory=3
3. In Test1, Evolution over the period, element id=jqplot-seriespicker ("Series to plot"), pick any variant of the test (i.e. "FS19817") 
4. See screenshots <br/>![first report graph](https://github.com/matomo-org/matomo/assets/12297805/bd3437ac-70be-4877-a5a3-b3bcdf9a1b3f) and <br/>
![first report selection](https://github.com/matomo-org/matomo/assets/12297805/0e9714f4-e6b0-49d8-9755-f1d5812e4e22)
5. Go back to the AbTest overview of step 1, click any other test. 
6. On the page of the other test, an empty "FS19817" variant series is plottet with Zero values (a useless flatline) inside the graph JqplotEvolutionGraphDataTable
7. See screenshots <br/>![second report graph](https://github.com/matomo-org/matomo/assets/12297805/f1df2c74-2b34-46de-b131-8acc309b772c) and <br/>
![second report selection](https://github.com/matomo-org/matomo/assets/12297805/79350d6a-fc1a-4ca8-92be-de153d1bc7c4) and 

That's confusing.

Matomo version: 4.15.1
AbTesting 4.2.6
Chrome Version 119.0.6045.159 , Windows

**Comment by sgiehl** [comment]
ping @AltamashShaikh @snake14

**Comment by snake14** [comment]
Hi @leobardimpact . Thank you for taking the time to create this issue. I was able to reproduce the issue in our Cloud staging environment. I am marking this bug to be reviewed and prioritised by our product team.

**Comment by snake14** [comment]
Thank you for the heads-up @sgiehl . I'm not seeing the AbTesting repo in the search to transfer this issue. Is it because it's a different organization? Are we able to transfer it?

**Comment by michalkleiner** [comment]
@snake14 the premium plugin repos don't have issue trackers, the issues there should be raised via support.

**Comment by snake14** [comment]
Thank you @michalkleiner . I had forgotten that we don't have issues for our premium plugins since they're private repositories. As the information is here and I was able to reproduce the issue, I'll create the issue in Jira.

**Comment by michalkleiner** [comment]
Thanks for raising the issue here @leobardimpact. For premium plugins, please raise an issue via support next time. Thank you for your understanding.

**Comment by snake14** [comment]
Hi @leobardimpact . Thank you again for creating this issue. As this is the wrong repository, I'm closing this issue. I created a Jira issue based on this one and referenced this issue so that we can inform you when the bug has been addressed. As Michal mentioned, for future issues with premium plugins, please post on https://forum.matomo.org/ and/or contact support.

**Comment by leobardimpact** [comment]
> Hi @leobardimpact . Thank you again for creating this issue. As this is the wrong repository, I'm closing this issue. I created a Jira issue based on this one and referenced this issue so that we can inform you when the bug has been addressed. As Michal mentioned, for future issues with premium plugins, please post on https://forum.matomo.org/ and/or contact support.

Thanks for the update where us premium users should post bugs/issues of premium plugins. The instruction here is surely in good intent. There are plenty of instructions within the app that boosted my confidence I write exactly where I should. What you write here must first and foremost be written there. Somewhere close to "**Premium Products**" and "**Do you have a bug to report or a feature request?**"

"How can we help?"
index.php?module=Feedback&action=index&idSite=1&period=day&date=yesterday
![contact support premium bug](https://github.com/matomo-org/matomo/assets/12297805/a7297932-9028-4db5-bd13-aa677c902c67)

**Comment by sgiehl** [comment]
@leobardimpact Thanks for the valuable feedback. 
@Stan-vw It might indeed be good to advise people directly in the product where to direct feedback for premium plugins to.

**Comment by Stan-vw** [comment]
Thanks for tagging, yes this would be a great change. I'll put it on the backlog 👍
