### ISSUE TITLE
consider enabling dependabot security updates in this repo

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#21582]
## Summary

While checking the Matomo for WordPress' repo settings, it was noticed that the dependabot security updates in core were disabled. This is likely because the runtime dependencies can't always change without breaking all sorts of dependent products/plugins, so some updates have to be done during major releases.

But for development dependencies, it would be pretty easy to update them. The only thing that would need to be checked is whether the updated dependency altered the built UMDs, and if that were expected or not.

For other dependencies that can't necessarily be updated safely, dependabot will not re-create a PR if one is closed.

Might be worth considering enabling this setting.

**Comment by sgiehl** [comment]
dependabot has meanwhile been configured for this repository. We though need to do major version updates manually
