### ISSUE TITLE
Clear guidance where to provide feedback on Premium Plugins

### ISSUE THREAD

**Issue by Stan-vw** [piwik/piwik#21583]
## Summary

We regularly see github tickets being created for feedback / bugs / feature requests related to Premium Plugins. These tickets are subsequently closed and internal jira tickets are created. This is both double work, and not a great experience for the person that's investing their time to help improve Matomo.

Some ideas:
- We could make a new GitHub Create Ticket option that is for Premium Plugins, that would feed into the Plugins team Jira project
- An easy alternative change is to document (on the page below) that people should contact support for feedback on premium plugins:
![image](https://github.com/matomo-org/matomo/assets/52564377/f7f0d37a-4161-40b9-a63a-696920363b7e)

## Your Environment

N/A

**Comment by Starker3** [comment]
We already have an option in the issue creation template that opens the Contact Support page for Premium plugins. (See screenshot).

Maybe if we had a drop down in the issue creation (Once they click Bug Report or Feature Request) that asks which plugin the question/issue is about and if they select a premium feature it disables the submit button with a link to contact support?
![image](https://github.com/matomo-org/matomo/assets/20905821/9f30c95e-02ea-457e-ad75-9a574310c06c)

**Comment by Stan-vw** [comment]
Good that you put a red box around it, I've literally never seen this 🤯 
(and clearly many others miss it too 😅 )

Having looked at it, when clicking on it I get the support page where we "welcome businesses and individuals alike to get in touch." That doesn't feel like the right place to report issues/ideas, so perhaps people think we linked the wrong page.

What's the reason:
1. Why it's so far down? Personally I think it fits better right above/below security vulnerabilities.
2. This should go through support rather than directly to the dev team, similar to core tickets?

**Comment by Starker3** [comment]
It might also be a case of our brains filtering it out because the button colour is so similar to the background colour (So it kind of looks like a disabled button?)

But perhaps the simplest solution would be that we can add a label that auto creates the original issue in the appropriate Jira board and closes the original GitHub issue? Unless it's clearly a support related question and not a bug then we ask them to contact support.

This might make more work for the plugins teams though as it would likely increase potential duplicates for already reported issues or requested features.

**Comment by atom-box** [comment]
100% agree on the Starker3's automation idea. If I understand correctly they are suggesting:
1) A visitor arrives with an idea for Funnels (_oops..._)
2) The visitor naively clicks Feature Request >> Get Started green button
3) At the next screen a pull down asks the visitor to choose a category (visitor chooses _Funnels_)
4) (a robot does something automatically)
