### ISSUE TITLE
Bar graph in Last visits widget

### ISSUE THREAD

**Issue by modnykrakow** [piwik/piwik#21586]
is there a way to change the evolution graph into bar graph in Last visits widget somehow? (which I prefer).

**Comment by michalkleiner** [comment]
Hi @modnykrakow, unfortunately we don't provide user support/answer questions through this issue tracker, it's mainly dedicated to reporting bugs or suggesting new features/enhancements.
We recommend to ask the question in our forum: https://forum.matomo.org/.
Thanks for your understanding.
