### ISSUE TITLE
[Bug] Form Analytics - table view to small to show values

### ISSUE THREAD

**Issue by gonerator** [piwik/piwik#21606]
### What happened?

Hi, I was just running Form Analytics and I was thinking that maybe somehow the names for my fields are not mapped, but it turns out the table is just too wide to fit in the html card element:

![CleanShot 2023-11-29 at 11 49 26](https://github.com/matomo-org/matomo/assets/16865753/585c6942-b57e-447b-8774-e97928354ecd)

That's actually it. Tested it on Matomo Cloud.

### What should happen?

The data should be entirely visible

### How can this be reproduced?

I reproduced this on multiple instances on current Matomo Cloud, also on Demo data

### Matomo major version

Matomo 5

### Matomo minor or patch Version

5.0.0-rc8

### PHP version

Matomo Cloud

### Server operating system

Matomo Cloud

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Mac

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by AltamashShaikh** [comment]
@gonerator This is already fixed and a new version is also released, it should be deployed on cloud too in a week.

Also this is to track issues with Matomo core, for issues with premium feature, please contact support directly
