### ISSUE TITLE
Demo site: provide user log

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#21602]
## Summary
In order to provide the maximum of Matomo capabilities, is it possible to activate the user and visitor logs?
(Sorry, I don't know exactly where to put this request...)

## Your Environment
Matomo demo site: https://demo.matomo.cloud/index.php

**Comment by michalkleiner** [comment]
Hi @heurteph-ei, thank you for opening the issue. I think the best channel for a query like this would be to use the standard [Contact us form on Matomo's website](https://matomo.org/contact/). We appreciate there might not be an ideal place where to raise a request like this, however this tracker is primarily used for reporting bugs and suggesting improvements and enhancements to Matomo itself. Thank you for your understanding!
