### ISSUE TITLE
Option to disable "set password" on mail invite (for SSO)

### ISSUE THREAD

**Issue by christophvw** [piwik/piwik#21604]
Invite mail requests a password for newly created users. We would like to use SSO only and do not want users to set a password at all.
The password could be set to a strong random value as default.

## Your Environment
* Matomo Version: 4.16
* PHP Version: 8.1.2-1ubuntu2.14
* Server Operating System: Ubuntu
* Additionally installed plugins: LoginOIDC

**Comment by AltamashShaikh** [comment]
@christophvw If you are using `LoginOIDC` and want to remove the resetPassword screen, you should create a issue at  LoginOIDC end and not at Matomo's end. We have done similar thing with LoginSaml plugin, where only a super user can reset password
