### ISSUE TITLE
[Bug] Ecommece Overview revenue chart broken with change from SEK -> KR

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21612]
### What happened?

It appears that Matomo 5 has changed the currency identifier for the Swedish Krona from **SEK** to **KR**
This breaks the Ecommerce -> Overview chart when revenue is shown...
![Screenshot from 2023-11-30 12-45-43](https://github.com/matomo-org/matomo/assets/20234985/6090ed73-bb6b-4056-a667-a6f392f36331)
This does happen when the currency is change to EUR or USD, etc...
![Screenshot from 2023-11-30 12-47-05](https://github.com/matomo-org/matomo/assets/20234985/0a0691d4-f2ff-43b6-b943-5f9aa74c76eb)

It looks like the chart does not scale properly to show KR values.

### What should happen?

The chart should be able to scale to the upper limit of KR currency values as it does for other currencies.

### How can this be reproduced?

Change the currency for any instance which has tracked ecommerce orders to KR

### Matomo major version

Matomo 5

### Matomo minor or patch Version

5.0.0-rc8

### PHP version

8.2

### Server operating system

NA

### Computer operating system

NA

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by phattrance** [comment]
Please note that this bug happens for Danish (DKK) and Norwegian (NOK) also, and not just Swedish SEK / KR :)

**Comment by mneudert** [comment]
Can confirm it broke for all currencies having two leading characters before the monetary amount, e.g. the already mentioned `kr` formattings.
