### ISSUE TITLE
[Bug] Goals/VisitorDetaisl::queryGoalConversionsForVisits() does not apply Live max execution time setting

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21624]
### What happened?

Seeing in the processlist in the database a query like

```
SELECT
						log_conversion.idvisit,
						'goal' as type,
						goal.name as goalName,
						goal.idgoal as goalId,
						log_link_visit_action.idpageview,
						log_conversion.revenue as revenue,
						log_conversion.idlink_va,
						log_conversion.idlink_va as goalPageId,
						log_conversion.server_time as serverTimePretty,
						log_conversion.url as url,
						log_conversion.referer_type as referrerType,
						log_conversion.referer_name as referrerName,
						log_conversion.referer_keyword as referrerKeyword
				FROM log_conversion AS log_conversion
				LEFT JOIN log_link_visit_action AS log_link_visit_action
				    ON log_link_visit_action.idlink_va = log_conversion.idlink_va
				LEFT JOIN goal AS goal
					ON (goal.idsite = log_conversion.idsite
						AND
						goal.idgoal = log_conversion.idgoal)
					AND goal.deleted = 0
				WHERE log_conversion.idvisit IN ('623238')
					AND log_conversion.idgoal > 0
                ORDER BY log_conversion.idvisit, log_conversion.server_time ASC
```

### What should happen?

The DB select query should have had a `max_execution_query` defined.

### How can this be reproduced?

* Configure `live_query_max_execution_time` in config.ini.php.
* Make sure you have a goal configured
* Make sure you have a visitor who triggered a goal
* Fetch the visits log or profile

The DB query doesn't have the max execution time query applied.

### Matomo major version

Matomo 5

### Matomo minor or patch Version

0

### PHP version

0

### Server operating system

.

### Computer operating system

.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Guess we missed that one when adding the max execution time statements. I'll prepare a simple PR to add it.
