### ISSUE TITLE
[Bug] Scheduling re-archiving of custom reports results in archives being deleted for unrelated reports

### ISSUE THREAD

**Issue by snake14** [piwik/piwik#21620]
### What happened?

When creating a new custom report, it schedules re-archiving so that the past n months (rearchive_reports_in_past_last_n_months) can be archived for the new report. Invalidation records are created for that specific report ID for the past n months. However, when archiving runs, it deletes the archives for other custom reports and doesn't archive the new report for those periods or re-archive the other reports.

### What should happen?

The archives of existing reports should be untouched and the new report should be archived for the past n months, based on the `rearchive_reports_in_past_last_n_months` config.

### How can this be reproduced?

First, I run the `customreports:archive` command to make sure that all of the archives have been created:
![image](https://github.com/matomo-org/matomo/assets/11394099/43a902d3-4fb6-43fd-ad58-c46d99511515)

After creating a new custom report, the blob records are unchanged, but the re-archiving is scheduled:
![image](https://github.com/matomo-org/matomo/assets/11394099/44fbbd2d-5a29-4e93-8ae6-c659576c0e60)
![image](https://github.com/matomo-org/matomo/assets/11394099/b8515740-608c-48b1-8c4c-fbde95f86a19)

When I run the archive process (`core:archive`) with a breakpoint [before the API calls to archive](https://github.com/matomo-org/matomo/blob/b90f53c6bbaadecd513c4d01b6ef5314ac772676/core/CronArchive.php#L492):
![image](https://github.com/matomo-org/matomo/assets/11394099/e5bf13e3-c36a-44fb-9542-261d1848a2e1)
![image](https://github.com/matomo-org/matomo/assets/11394099/0be65069-be70-46b2-89d7-97d77a9e01bf)
I confirmed that all of the invalidation records had the same report ID.

Once archiving is done running:
![image](https://github.com/matomo-org/matomo/assets/11394099/a037088d-f530-4348-8f91-8e8697fbb4e3)
![image](https://github.com/matomo-org/matomo/assets/11394099/839c09ec-c04c-4e71-a5a3-bd794aa8adf0)

More information is available in my notes on Jira tickets PG-2881 and PG-3173

### Matomo major version

Matomo 5

### Matomo minor or patch Version

5.0.0-rc8

### PHP version

8.1.26

### Server operating system

Ubuntu 22.04

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Ubuntu 22.04

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
There seems to be something wrong with detecting the RecordBuilder: https://github.com/matomo-org/matomo/blob/1474562882db86249f6fb1727ad087ca18243d3e/core/ArchiveProcessor/RecordBuilder.php#L328-L330

When running the archiving I received some values that obviously won't match:

```
$recordMetadata = {object[1]} 
 0 = {Piwik\ArchiveProcessor\Record} 
  type = "blob"
  name = "CustomReports_customreport_13_4"
  columnToSortByBeforeTruncation = "nb_visits"
  maxRowsInTable = null
  maxRowsInSubtable = null
  countOfRecordName = null
  countOfRecordNameIsRecursive = false
  columnToRenameAfterAggregation = null
  blobColumnAggregationOps = null
  multiplePeriodTransform = null
$requestedReports = {string[1]} ["13"]
 0 = "13"
```

If I do some hacky modifications to match that record the previously missing archive blobs appear as expected. Perhaps there is only a call to `Archiver::makeRecordName` to be patched into an override of `RecordBuilder::isBuilderForAtLeastOneOf`?

**Comment by michalkleiner** [comment]
Do you think it's an issue in CustomReports, @mneudert, after changing to use `RecordBuilder`?
