### ISSUE TITLE
[Bug] PHP Deprecated Creation of dynamic property

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#21637]
### What happened?

Seen at:
https://forum.matomo.org/t/deprecated-warning-messages-after-update-to-4-16-0-php-8-2/54193/

>On the Main Page I got those two errors, after a reload they are gone
 - [ ] `WARNING: /core/Plugin/Controller.php(807): Deprecated - Creation of dynamic property Piwik\View\OneClickDone::$isCustomLogo is deprecated - Matomo 4.15.1`
 - [ ] `WARNING: /core/Plugin/Controller.php(808): Deprecated - Creation of dynamic property Piwik\View\OneClickDone::$customFavicon is deprecated - Matomo 4.15.1`

### What should happen?

No error / warning.

### How can this be reproduced?

Navigate to main page.

### Matomo major version

Matomo 4

### Matomo minor or patch Version

4.15.1

### PHP version

Probably 8

### Server operating system

Probably linux

### Computer operating system

Doesn't matter

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/deprecated-warning-messages-after-update-to-4-16-0-php-8-2/54193/3

**Comment by wes-p** [comment]
As in the title of the forum post: it happened after the update from version 4.15.1 to version 4.16.0 (and only once, after a reload it was gone)

System specs:
MySQL-Version: 5.7.43-47-log
PHP-Version: 8.2.9-he.0
Server OS: Apache (not sure if thats the answer you were asking, but also no sure how to get more details)

and seen in Google Chrome Version 119.0.6045.199

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/mise-a-jour-de-matomo-4-16-0-vers-matomo-5-0-0/54596/2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-core-plugin-controller-php-807-deprecated-4-14-2-php-8-2-5/50804/6
