### ISSUE TITLE
[Bug] Undefined offset: 1 in [/data/website/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 1526

### ISSUE THREAD

**Issue by mawocego** [piwik/piwik#21638]
### What happened?

When we try try track an event using the MatomoTracker we get the following error:

Warning (2): Undefined offset: 1 in [/data/website/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 1526]
Trace: ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
AppError::handleError() - APP/Lib/Error/AppError.php, line 33
MatomoTracker::loadVisitorIdCookie() - ROOT/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 1526
MatomoTracker::getVisitorId() - ROOT/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 1471
MatomoTracker::getRequest() - ROOT/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 2052
MatomoTracker::getUrlTrackEvent() - ROOT/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 1162
MatomoTracker::doTrackEvent() - ROOT/vendor/matomo/matomo-php-tracker/MatomoTracker.php, line 731
MatomoTrackerClient::trackEvent() - APP/Vendor/Matomo/MatomoTrackerClient.php, line 91

We assume it's because the cookie is not set (correctly or in the wrong format).

### What should happen?

We are trying to track an event by using the tracker code, but we get an error since the cookie is not set correctly.

### How can this be reproduced?

Occurs when we try to track an event, but the cookie is set in an incorrect format.

### Matomo major version

Matomo 3

### Matomo minor or patch Version

3.2.0

### PHP version

7

### Server operating system

Linux

### What browsers are you seeing the problem on?

Chrome, Other

### Computer operating system

MacOS

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @mawocego,

from the stacktrace you have posted I assume you are using the [Matomo PHP Tracker](https://github.com/matomo-org/matomo-php-tracker/) in version `3.2.0` and not an older Matomo/Piwik version of 3.2.0, correct?

As you have already mentioned the cookie value seems to be in a wrong format (missing a dot after the 16 character visitor id), but seems to exist with at least the visitor id in it.

Do you know have any hints where those invalid cookies come from?

**Comment by sgiehl** [comment]
Closing for now, as there hadn't been any further feedback. 
@mawocego If you still have problems using our PHP Tracker, feel free to create a new issue around that here: https://github.com/matomo-org/matomo-php-tracker/issues
