### ISSUE TITLE
[Bug] Inconsistency in Menu styling between reporting and admin UI

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#21641]
### What happened?

Our menu on the left side has a different styling between reporting and admin UI. 
While the reporting menu does not show any box shadow, the admin UI currently does:

Admin UI:

![image](https://github.com/matomo-org/matomo/assets/1579355/9b0422e8-1d9f-492f-9797-0660dee36d88)

Reporting UI:

![image](https://github.com/matomo-org/matomo/assets/1579355/e255303f-cafc-426e-b594-74225e8427fa)

This might be a regression of the refactoring of the reporting menu a (long) while ago.

### What should happen?

The menu should look the same across different parts.

### How can this be reproduced?

Can be seen when viewing reporting and admin ui.

### Matomo major version

Matomo 5

### Matomo minor or patch Version

5.0.0-rc*

### PHP version

not relevant

### Server operating system

not relevant

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

not relevant

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@Javi-Ormaechea Would you have a quick look? I'm not aware of the long term plans for our UI, so I'm unable to say if it's better to remove the shadow in admin UI, or readd it in reporting UI.

**Comment by Javi-Ormaechea** [comment]
@sgiehl just had a look. I think Reporting should have a shadow too as that's part of the current UI.

The long term plan would be to move away from shadows and make the interface 'cleaner' but for now I haven't had the chance to work around this change and go through a couple of iterations before we change anything on the UI.

**Comment by sgiehl** [comment]
@Javi-Ormaechea Ok. fine. So adding back the shadow would be the correct approach for now, right? I could quickly set up a PR to do that.

**Comment by snake14** [comment]
@sgiehl Adding the shadow back means that we're going to have a bunch more test cases fail on top of the ones already failing due to the admin shadow (both 4.x and 5.x). Is there going to be a core level workaround or is the plan still to duplicate code across all the plugin repos?

**Comment by sgiehl** [comment]
@snake14 I'd aim a solution that would also solve all the ui test issues around it. We might adjust the CSS a bit more, but it should be possible to have the menu shadow "overlay" the content.

**Comment by sgiehl** [comment]
This had been fixed in #21689
