### ISSUE TITLE
[Bug] First/Last visit displayed date doesn't take website timezone into account.

### ISSUE THREAD

**Issue by rsichnyi** [piwik/piwik#21645]
### What happened?

In visitor details summary, the date of First,Last visit doesn't respect the website timezone, see the screenshot below:

![image](https://github.com/matomo-org/matomo/assets/745639/984a22a4-9d11-438b-8e5d-1c0424a8c940)

The website is configured with timezone="America/New_York". The timestamp of this visit (based on api response for the same data) is 1701734804. This is correctly converted to EST timezone in the visit details on the right (green underline), but is not converted to EST in visitor details on the left (red underline). I assume (based on the code, haven't tested) the same is true for Last Visit.

### What should happen?

Under the described conditions, First Visit date (red underline) should display "Monday, December 4, 2023".

### How can this be reproduced?

Set the website time zone to EST, visit the website for the first time between 19:00 EST and midnight EST.

### Matomo major version

Matomo 4

### Matomo minor or patch Version

4.15.1

### PHP version

8.2.11

### Server operating system

Linux

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Linux, Windows

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Thanks for reporting this issue.

Having one date using UTC and one using the site timezone is indeed odd and should be corrected.
