### ISSUE TITLE
[Bug] Heavy Performance problem in tracker

### ISSUE THREAD

**Issue by Jak2k** [piwik/piwik#21643]
### What happened?

The tracker script runs for 2 seconds in my lighthouse test. This bad performance is unacceptable by me.

### What should happen?

The script should be runned in under half a second.

### How can this be reproduced?

Run lighthouse on a matomo site.

### Matomo major version

Matomo 4

### Matomo minor or patch Version

16.0

### PHP version

8.3

### Server operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Linux

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @Jak2k, can you share how the tracking code is integrated and how the performance problems are reflected in the lighthouse report?

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. If you still experience problems around that feel free to reach out for help on our forum or create a new issue.
