### ISSUE TITLE
Regarding the issue of slow monthly data acquisition in OpenApi

### ISSUE THREAD

**Issue by 786659214** [piwik/piwik#21675]
hello

I am a Chinese and my English is not very good。

I would like to ask about the issue of using UserId. getUsers in OpenAPI to obtain independent visitor information. Due to its long periodicity, the query data is slow. I searched for relevant documentation but did not see any explanation of this part. Can you provide some helpful documentation.

The following is an example of my query:

![image](https://github.com/matomo-org/matomo/assets/49685173/3dfa4b9f-ec92-4277-8eea-b749352ac728)

Although I only selected one month, the large amount of data has caused slow query time. I would like to optimize this and hope to receive your help. Thank you

**Comment by sgiehl** [comment]
Hi @786659214 
It's hard to answer this one, as it depends on you exact setup. I would assume that in your case archiving might get triggered by the API call, causing it to take a bit longer.
You can try setting up an archive cron and disable browser archiving as described here: https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

For further help, please consider using our forum instead. We are only handling bug reports and feature requests on github.
Thanks for your understanding.
