### ISSUE TITLE
[Bug] mktime(): Argument #1 ($hour) must be of type int, string given in /mnt/efs/plugins/VisitTime/functions.php line 18

### ISSUE THREAD

**Issue by nodomain** [piwik/piwik#21677]
### What happened?

When opening the visitor time report for the current year, it breaks with this error message.

index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?period=year&date=2023-12-13&idSite=1&category=General_Visitors&subcategory=VisitTime_SubmenuTimes

mktime(): Argument #1 ($hour) must be of type int, string given in /mnt/efs/plugins/VisitTime/functions.php line 18

It works fine for day, week and monthly period for December but breaks in November.

I initialized my instance in November, so perhaps this is related.

### What should happen?

The report should work without issues.

### How can this be reproduced?

Go to Matomo -> click on visitors -> click on times and select the first month of your Matomo installation.

### Matomo version

4.16.0

### PHP version

8.1.26

### Server operating system

AWS ECS Docker php:8.1-apache

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Computer operating system

Mac

### Relevant log output

```shell
n/a
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @nodomain 
Thanks for creating this report. I actually don't have a idea how this can happen, but I found a solution that should fix that problem nevertheless. I'll prepare a PR to fix that.

**Comment by nodomain** [comment]
Thanks for the fast fix. You are awesome 😎
