### ISSUE TITLE
Limit the number of parallel connections when reports/widgets load in the console/interface

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21686]
A user asks:

> I have Matomo hosted on a limited hosting service, which limits simultaneous connections to 5. It'd be great that Matomo would not spawn multiple concurrent requests to load the widgets, since I can never see them fully loaded because of "resource limit reached" error issued by the server.

@Starker3 suggests: _"Maybe we could implement this feature by having Matomo detect the speed and automatically switch the number of parallel connections."_

**Comment by atom-box** [comment]
How many dashboard views would be improved by this?  Maybe the scenario is not totally rare...

The user above has always-slow connection on their server. But how many people have sometimes-slow connections on their client?
 
An unknown number of Matomo users may have normal internet infrastructure but at random times, can be slow or intermittently slow connection. On a train? Using their phone as a hotspot? Maybe this would give a smoother dashboard appearence during times of low connectivity? For On Premise we have no idea of the connectivity, but in Cloud this data exists right?  Should I make a story ticket like "measure connection speeds by quartile or average and with standard deviation"?

**Comment by claudix** [comment]
For your convenience, I'm attaching a screenshot with the widgets not loading because of 508 http error.

![capture](https://github.com/matomo-org/matomo/assets/5880835/05ca6bff-63c2-48d6-b856-a6a121ba3a67)

**Comment by bx80** [comment]
Although we could in theory add a configuration option for the server to limit the amount of parallel requests, this would mean that each area of the application would need additional client-side logic to monitor the state of requests and start new requests once the previous requests have finished. This would add a lot of complexity, involve a lot of work and isn't really a practical solution in this case.

I'd suggest either upgrading the hosting provider (many web applications will struggle with a 5 connection limit which really is quite low) or address this from the browser side by configuring the browser to limit the maximum number of connections to 5. This setting will vary depending on the browser being used, for example in FireFox the setting is `Network.http.max-persistent-connections-per-server` available via the `about:config` address.
