### ISSUE TITLE
Segment isn't working efficiently

### ISSUE THREAD

**Issue by guilletmarion** [piwik/piwik#21691]
J'ai récemment créé un segment dont le but était de tracker les utilisateurs accédant à notre service via une ancienne URL (labonnealternance.pole-emploi.fr au lieu de la nouvelle URL labonnealternance.apprentissage.beta.gouv.fr).

Ce segment fonctionnait correctement jusqu'au 05/10/23 et depuis cette date, seule une quantité infime d'utilisateurs sont trackés sur ce segment, sans que je n'ai rien changé à son paramétrage.

J'ai essayé de le modifier sans succès et ai demandé à de nombreux utilisateurs d'accéder à l'URL labonnealternance.pole-emploi.fr pour vérifier que la chute de tracking ne reflétait pas une réelle chute dans les accès.
Et finalement, l'ensemble de ces accès n'ont pas été trackés dans Matomo.

![image](https://github.com/matomo-org/matomo/assets/57708683/817a70d3-ebc0-46b2-acd5-59b35c63a906)
![image](https://github.com/matomo-org/matomo/assets/57708683/e1252115-0dd5-47a2-a6ba-086d816bc7fd)

**Comment by guilletmarion** [comment]
![image](https://github.com/matomo-org/matomo/assets/57708683/24dac660-e6c8-4b73-9ec7-39831404bd5a)
![image](https://github.com/matomo-org/matomo/assets/57708683/b874090c-070f-4a7d-9f91-b70c55d31ea7)

**Comment by sgiehl** [comment]
Hi @guilletmarion,

I would assume that you might have changed something on your website. Your old website URL is doing a 301 redirect to the new host, so Matomo can't track anything in between (unless you would be using log importing)

For further help or similar questions like this, please try to find some help on our forum please. We are using GitHub for bug reports and feature requests only.

PS: Please create your issues in english in the future. To make it easier for anyone to understand them without needing to use a translator first.
