### ISSUE TITLE
Segment selector scrollbar partially obscured edit segment buttons

### ISSUE THREAD

**Issue by bx80** [piwik/piwik#21706]
### What happened?

After twelve segments are added the segment selector adds a scrollbar on the right hand side. This scroll bar partially blocks the edit segment buttons making them hard to click.
![image](https://github.com/matomo-org/matomo/assets/88810029/4ceeebea-b4db-4019-a661-efb72ab1fe0e)

### What should happen?

The CSS layout should be tweaked to prevent the scrollbar overlaying the buttons.

### How can this be reproduced?

1) Add random segments until the scroll bar appears in the segment selector.
2) Hover over one of the edit buttons (slightly to the right of the icon)
3) The scrollbar appears and blocks the right side of the edit button.
4) Clicking will now scroll instead of editing.

### Matomo version

5.0.0-RC9

### PHP version

8.1

### Server operating system

Debian 12

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Linux

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Note: This seems to work correctly on latest Chrome and Firefox on Windows. Which version of Firefox are you running?

**Comment by bx80** [comment]
This was on Firefox 115.5.0esr (64-bit) on Linux (latest ESR, but latest standard build is 120.xxx)
I tested Chromium 120.0.6099.71 also on Linux which worked correctly.
Looks like this is probably Firefox bug that has been fixed in newer release so I'll close the issue and this ticket can be a reference for any other Firefox-ESR-on-Linux users seeing the same issue :slightly_smiling_face:
