### ISSUE TITLE
[Bug] Matomo could not be updated to version 5.0.0

### ISSUE THREAD

**Issue by evaso** [piwik/piwik#21725]
![matomo_error](https://github.com/matomo-org/matomo/assets/36920248/1f1a4d15-2d5a-4969-a6b9-1a8360467e3b)
### What happened?

 I received a message that a new Matomo version is available and I should install it.
 When I clicked "Update" a new message appeared: _Database Upgrade Required_
 _Your Matomo database is out-of-date, and must be upgraded before you can continue.
  Matomo database will be upgraded from version 5.0.0-rc2 to the new version 5.0.0._

Execute on Piwik-Database (mariadb) Server version: 11.0.2-MariaDB
  --- dru run---
   ALTER TABLE `matomo_user` ADD COLUMN `ts_changes_shown` TIMESTAMP NULL;
   **ERROR 1025 (HY000): Error on rename of './piwik/matomo_user' to './piwik/#sql-backup-73d0-109f9be' (errno: 168 "Unknown (generic) error from engine")**
   
   ALTER TABLE `matomo_log_conversion` MODIFY COLUMN `pageviews_before` SMALLINT UNSIGNED DEFAULT NULL;
   Query OK, 0 rows affected (0.004 sec)
   Records: 0  Duplicates: 0  Warnings: 0
--- End of dry run ---

  Final report:
 ERROR     [08:58:43] 25013  Uncaught exception: /var/www/matomo/plugins/CoreUpdater/Commands/Update.php(267): Matomo could not be updated! See above for more information. [Query: , CLI mode: 1]

### What should happen?

We use MariaDB as a database server (version: 11.0.2). On November 29th I was able to install the update to version 4.16.0 automatically without any problems.
The update to version 5.0.0 doesn't work and I can't even reset the whole thing. Access to the account is no longer possible. I always get the message "The database needs to be updated" on the website. What's next? If the update is not possible, how can I at least use the old Matomo version?

### How can this be reproduced?

Matomo is installed on our own Linux server.

### Matomo version

4.16.0

### PHP version

PHP 8.1.12

### Server operating system

Ubuntu Server 18.04 LTS

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @evaso 
Sorry to hear you have trouble updating Matomo.
SQL Error 168 can happen when the disc space is full. Would you mind checking if there is enough free space for the database?

**Comment by evaso** [comment]
Hi @sgiehl 

Unfortunately, this is not the case. There is enough hard drive space available.
df -h
`Filesystem                      Size   Used   Avail   Use%  Mounted on`
`/root                            491G  140G   331G  30%     /`

**Comment by sgiehl** [comment]
Would you try to execute that statement directly on the database? Wondering if that would work.

**Comment by evaso** [comment]
What I wrote above in the issue came directly from the Linux console. I entered the commands directly into the database.

**Comment by mneudert** [comment]
Hi @evaso, could you additionally check to make sure your DB server has not run out of inodes (`df -i`)?

As the 168 error code is quite generic the mysql error log may be of help. There should be a more helpful log message, something like `InnoDB: Operating system error...`, detailing if you are experiencing a space/permission/other issue.

_The log file location should be displayed ny `SELECT @@GLOBAL.log_error;` if you need to search for it._

**Comment by evaso** [comment]
I restarted the MariaDB server and tried to update Matomo again so that the messages are logged. Then I looked in the log files and didn't necessarily find anything directly related to the Matomo update. I have attached the log file here.
[mariadb_log.txt](https://github.com/matomo-org/matomo/files/13729450/mariadb_log.txt)
[mariadb_defaults.txt](https://github.com/matomo-org/matomo/files/13729491/mariadb_defaults.txt)
[df-i.txt](https://github.com/matomo-org/matomo/files/13729590/df-i.txt)

**Comment by mneudert** [comment]
The error lines for `innodb_table_stats` could be indirectly related:

- https://mariadb.com/kb/en/mariadb-server-109-mysql_upgrade-does-not-fix-column-last_update-in-table-m/
- https://www.drupal.org/project/drupal/issues/3253870

The drupal issue matches the problem: an `ALTER TABLE` statement resulting in `rename x to x/#backup` and Error 168. Comment number 5 solved the issue for someone, probably by running `mysql_upgrade` mentioned in the second link.

After creating a backup of your database (!), could you check if that also works for you?

**Comment by evaso** [comment]
I executed the command “mysql_upgrade” and every line was acknowledged with “OK”. The final result was also “OK”. However, this did not bring any changes to the Matomos update. The error message remains the same.

Can't I go back to Matomo version 4.16? That would be enough for me for now. Currently I can't do anything with matomo anymore.

**Comment by evaso** [comment]
The problem has now been solved. I installed the current update of Mariadb (11.0.3-MariaDB, previously version was 11.0.2) and then I successfully executed the Matomo update. 😅
Thanks for the support!
