### ISSUE TITLE
How to hide items added with version 5.0.0

### ISSUE THREAD

**Issue by EmilieCrx** [piwik/piwik#21726]
Hi, I would like to remove the following items from the reporting section: Funnels Forms, Media, A/B Tests, Heatmaps, Session Recordings, Custom Reports, Crashes.

These items were added with version 5.0.0 and are displayed even when the plugins are deactivated. I’d like them to be hidden from users (our interface is public).

Is there an easy way to do this?

**Comment by sgiehl** [comment]
On each of those pages there should be a small link to hide the section. Alternatively disabling the ProfessionalServices plugin should hide them as well.
