### ISSUE TITLE
[Bug] Critical Error during the update process - SQLSTATE[42S22]

### ISSUE THREAD

**Issue by cybeardjm** [piwik/piwik#21723]
### What happened?

Updating to 5.0, problem when updating the SQL Database

Critical Error during the update process:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list'

tried updating again, same error

Have 2 SQL queries waiting to be executed:
# These SQL queries will be executed: 
ALTER TABLE `matomo_tagmanager_container` ADD COLUMN `ignoreGtmDataLayer` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 AFTER `description`;
ALTER TABLE `matomo_log_conversion` MODIFY COLUMN `pageviews_before` SMALLINT UNSIGNED DEFAULT NULL;

### What should happen?

N/A

### How can this be reproduced?

N/A

### Matomo version

Latest before 5.0

### PHP version

8.1.16 (Supports 64bit values)

### Server operating system

Linux 4.9.124-paas-2270098 x86_64

### What browsers are you seeing the problem on?

Firefox

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by cybeardjm** [comment]
Could run the 2 changes manually from the SQL DB.
Still unable to finish update, as error persists...

**Comment by sgiehl** [comment]
Which version did you update from? Looks like an update script was not executed correctly for tag manager.

**Comment by cybeardjm** [comment]
4.16.0
Did a reset of the core_version, and it just comes back to this same error, although the changes were already made manually by running the SQL query... Can't move past this...
Annoying as hell... Did a lot of updates since August 2022, no problem ever. Worse is I don't use tag manager at all!!!!

**Comment by cybeardjm** [comment]
The script doesn't like the "AFTER `description`" part, as it doesn't find `description`...
I just copied/pasted the two queries and they ran like a charm...
Have the column right now in front of me...

**Comment by cybeardjm** [comment]
I was about to ditch analytics for all my sites altogether, and this might be the straw that'll break the camel's back...

**Comment by cybeardjm** [comment]
"re-run the updater" How many times should I do it then? 10, 20, 100 times, am running in circles here...
There's a script in a PHP file in the updates somewhere that I should be able to edit to stop this happening, no?

**Comment by sgiehl** [comment]
That update seems to have been part of 4.12.3 already. See https://github.com/matomo-org/tag-manager/blob/5.x-dev/Updates/4.12.3-b1.php
So either set back the core version before this and rerun the updates. Or add the description fields manually according to that update script.

**Comment by sgiehl** [comment]
@cybeardjm For further details please look at https://github.com/matomo-org/matomo/issues/19886
