### ISSUE TITLE
Handle OpenAI referrer

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21748]
OpenAI started sending below referrer:

> 'https://chat.openai.com/'

Unsure if this is happening when ChatGPT is doing research or if there's a link that can be clicked. 

If it's the first one, we may want to classify this as a bot if it's not done yet?
If it's the second case, we would need to classify it as a search engine?

It seems to me that it's the second case and we would need to classify it as a search engine as IPs and UserAgents are quite different for each visit.

**Comment by sgiehl** [comment]
Adding it as a search engine can be easily done by adding it to https://github.com/matomo-org/searchengine-and-social-list/blob/master/SearchEngines.yml
