### ISSUE TITLE
[Bug] Live Plugin action=getLastVisitsDetails 504 after 300 seconds

### ISSUE THREAD

**Issue by lippoliv** [piwik/piwik#21745]
### What happened?

I updated to Matomo 5.0.0 recently (including MySQL 8.2 and switching to official Matomo docker image).
Sanity checks did look good. After some hours I started to see 504 Gateway Timeout when users trying to use Matomo UI, I started bigger research.

The timeouts are exclusively towards the URL `https://matomo/index.php?date=today&module=Live&format=html&forceView=1&viewDataTable=VisitorLog&action=getLastVisitsDetails&small=1&idSite=...&period=day&segment=&widget=&showtitle=1&random=...`

I cannot guarantee that it started "hours after the update", may be it was already with the update but I haven't seen it until users reported it to me.

### What should happen?

The report should load, as it did in Matomo 4.x

### How can this be reproduced?

Prett sure it's not that easy (it would have been reported already) but for me it is:

1. Open `Some site > Visitors > Visitor log` (`https://matomo/index.php?module=CoreHome&action=index&date=today&period=day&idSite=...#?idSite=...&period=day&date=today&category=General_Visitors&subcategory=Live_VisitorLog`)

### Matomo version

5.0.0

### PHP version

8.2.13

### Server operating system

Docker (matomo:5.0.0-apache)

### Computer operating system

Tested on: MacOS, Android, Windows

### Relevant log output

```shell
No log output (not even DEBUG)

(Used `enable_sql_profiler = 1` and `log_level = DEBUG`.)
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by lippoliv** [comment]
Some more context:
On the database, if I run `show full processlist;` while the API request is pending, I see 

```sql
SELECT
                    idgoal,
                    COALESCE(SUM(ROUND(revenue,2)), 0) as lifeTimeRevenue,
                    COUNT(*) as lifeTimeConversions,
                    COALESCE(SUM(ROUND(items,2)), 0)  as lifeTimeEcommerceItems
                                        FROM  piwik_log_visit AS log_visit
                                            STRAIGHT_JOIN piwik_log_conversion AS log_conversion
                                            ON log_visit.idvisit = log_conversion.idvisit
                                        WHERE
                                                log_visit.idsite = '...'
                                            AND log_visit.idvisitor = '\'?\?V???'
                                                AND log_conversion.idgoal IN ( -1, 0 )
                    GROUP BY idgoal
```

If I run this query it takes 3,3 seconds, here's the mysql explenation

```
mysql> explain SELECT
    ->                     idgoal,
    ->                     COALESCE(SUM(ROUND(revenue,2)), 0) as lifeTimeRevenue,
    ->                     COUNT(*) as lifeTimeConversions,
    ->                     COALESCE(SUM(ROUND(items,2)), 0)  as lifeTimeEcommerceItems
    ->                                         FROM  piwik_log_visit AS log_visit
    ->                                             STRAIGHT_JOIN piwik_log_conversion AS log_conversion
    ->                                             ON log_visit.idvisit = log_conversion.idvisit
    ->                                         WHERE
    ->                                                 log_visit.idsite = '...'
    ->                                             AND log_visit.idvisitor = '\'?\?V???'
    ->                                                 AND log_conversion.idgoal IN ( -1, 0 )
    ->                     GROUP BY idgoal
    -> ;
+----+-------------+----------------+------------+------+------------------------------------------------------------+------------------------------+---------+-------------------------+--------+----------+------------------------------+
| id | select_type | table          | partitions | type | possible_keys                                              | key                          | key_len | ref                     | rows   | filtered | Extra                        |
+----+-------------+----------------+------------+------+------------------------------------------------------------+------------------------------+---------+-------------------------+--------+----------+------------------------------+
|  1 | SIMPLE      | log_visit      | NULL       | ref  | PRIMARY,index_idsite_config_datetime,index_idsite_datetime | index_idsite_config_datetime | 4       | const                   | 309308 |    10.00 | Using where; Using temporary |
|  1 | SIMPLE      | log_conversion | NULL       | ref  | PRIMARY                                                    | PRIMARY                      | 8       | piwik.log_visit.idvisit |    483 |    20.00 | Using index condition        |
+----+-------------+----------------+------------+------+------------------------------------------------------------+------------------------------+---------+-------------------------+--------+----------+------------------------------+
2 rows in set, 1 warning (0.00 sec)
```

**Comment by lippoliv** [comment]
I "worked around" the issue by putting `false` to this condition https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/Ecommerce/VisitorDetails.php#L34 (e.g. `if(false && Site::isEcommerceEnabledFor($visitor['idSite']))`)

But for sure this is just a temporary fix. If I can support a long-term fix somehow, please let me know.

**Comment by michalkleiner** [comment]
Hi @lippoliv, thanks for the report.
It seems like you've changed a lot of things at once and it might be difficult to identify the issue because of that. It's usually good to change one thing at a time on production systems.
The Matomo Docker image is not officially supported by Matomo (despite being under the Matomo Github org), it's a community project, so we can't provide and guarantees or troubleshooting there.
At this stage it's probably more likely it's something related to the infrastructure/hosting setup — would it be possible to see if it works fine with whatever hosting setup you had before to rule out the docker setup? There might be a default 300s timeout on web requests in the nginx setup inside the docker container, might be another thing to look for.
And another thing you can try is disabling running archiving through web requests and switching to using cron (if it's not done already).

**Comment by lippoliv** [comment]
@michalkleiner thanks for your feedback and sorry for the late reply.

Yes I should have known better, I changed to much. But not right away. Before I post Issues, I want to be sure that "I" am not the problem (at least as much as I can) :)

# Rough roadmap
Step 1
Update to Matomo 5 and MySQL 8

Step 2
Update to PHP 8

-some hours later I got informed about "the issue"-

Step 3 (triggered by the issues)
Switch to "official" images

-now I posted this issue-

# New information

All in all I think this Query I spotted is "slow", but not the cause of the issue.
I got back a stable Matomo by adding QueuedTracking and splitting my archivers. Now I run daily, weekly and "month + year" seperated with different timing.

Overall I still see peaks when there's a lot of "spam" in the wooCommerce Shop, so it looks like there's a link. Luckily now it's just that (at least today) 1000 events are queued and after an hour or so everything is back to normal.

# Answers to your questions
**would it be possible to see if it works fine with whatever hosting setup you had before to rule out the docker setup?**
I cannot roll back to Matomo 4.16.0.
I probably with some preperation could go back to my images, but that would only revert Step 3, when the issue was here already.

**There might be a default 300s timeout on web requests in the nginx setup inside the docker container, might be another thing to look for.**
This timeout definitely is from my reverse proxy (node proxy manager), I increased it to 300 from 90.
But to be honest, 300 (and 90 as well) are way to much for a "small" table to render, right?

**And another thing you can try is disabling running archiving through web requests and switching to using cron (if it's not done already).**
As you probably read already: It was cron already, now I even splitted up the different metrics.

**Comment by michalkleiner** [comment]
Thanks for the additional info, @lippoliv.
With the above, do you still think there is a reproducible bug in Matomo 5 or do you think it's specific to your local conditions, peak of traffic or similar?

**Comment by sgiehl** [comment]
As far as I know we didn't have any bigger problems with the mentioned query in the past. But this could be related to the setup. For instances with higher traffic we would recommend to use an additional database reader instance (see https://matomo.org/faq/how-to-install/faq_35746/). Maybe that would also help in your case, so write requests can't block reading requests at all.
