### ISSUE TITLE
[Bug] Critical Error during the update process (v5.0)

### ISSUE THREAD

**Issue by Babisx71** [piwik/piwik#21759]
### What happened?

During the automatic update from version 4.16.0 to 5.0 I get this error:
core/Updates/5.0.0-b1.php: Error trying to execute the migration './console core:calculate-conversion-pages --dates=yesterday,today'. The error was: plugins/Goals/Commands/CalculateConversionPages.php: Error trying to execute the migration ' UPDATE *_log_conversion c LEFT JOIN ( SELECT c.idvisit, c.idgoal, COUNT(a.idvisit) AS pagesbefore, c.idlink_va, c.server_time FROM *_log_conversion c LEFT JOIN ( SELECT va.idvisit, va.server_time FROM *_log_link_visit_action va INNER JOIN *_log_action a ON a.idaction = va.idaction_url WHERE a.type = 1 AND va.idsite = 1 AND va.server_time >= '2024-01-02 02:00:00' AND va.server_time

### What should happen?

I had never problems before during automatic upgrades

### How can this be reproduced?

not possible

### Matomo version

4.16.0

### PHP version

8.2

### Server operating system

apache 2.4.58, mysql 10.6.16-MariaDB-cll-lve

### What browsers are you seeing the problem on?

Firefox

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @Babisx71,

Sorry to hear you have trouble performing the update.
Can you provide some more details? Were there any further messages displayed or are there entries in the error log maybe?
Also did that error break Matomo or were you able to finish the update nevertheless?

**Comment by Babisx71** [comment]
Hi @sgiehl sgiehl, thank you for answering.
I am sorry, the only line that has not a 200 result in the error log is the following:
"POST /?module=CoreUpdater&action=oneClickUpdatePartTwo&nonce=fec79c245de3fb0016421871bd992093 HTTP/1.1" 404 2774 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
I was not able to deal with it, I reverted to last version by using server's backup from last night.

**Comment by Babisx71** [comment]
upgrade to 5.0.3 was successful.
