### ISSUE TITLE
[Bug] Failing "Matomo Test / UI (1)" - Date format must be: YYYY-MM-DD - given: `compareDates%5B%5D=2011-31-12`

### ISSUE THREAD

**Issue by rr-it** [piwik/piwik#21755]
### What happened?

New PR https://github.com/matomo-org/matomo/pull/20718 but "Matomo Test / UI (1)" failed in Github CI:

Failing query:
`date=2012-01-01&module=API&format=json&method=API.getProcessedReport&apiModule=VisitsSummary&apiAction=get&compare=1&comparePeriods%5B%5D=day&compareDates%5B%5D=2011-31-12&format_metrics=1&segment=&idSite=1&period=day`

### What should happen?

Date format must be: YYYY-MM-DD
So `compareDates%5B%5D=2011-31-12` is invalid and instead must be `compareDates%5B%5D=2011-12-31`

### How can this be reproduced?

Run "Matomo Test / UI (1)"

### Matomo version

5.x-dev

### Relevant log output

```shell
2024-01-03T15:35:15.6983443Z ERROR API[2024-01-03 15:26:46 UTC] [4339c] Uncaught exception in API: /home/runner/work/matomo/matomo/matomo/core/Date.php(1142): Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): false [Query: ?date=2012-01-01&module=API&format=json&method=API.getProcessedReport&apiModule=VisitsSummary&apiAction=get&compare=1&comparePeriods%5B%5D=day&compareDates%5B%5D=2011-31-12&format_metrics=1&segment=&idSite=1&period=day, CLI mode: 0]
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @rr-it 
I'm not sure which failing test your are referring to. At least I can't see one in that test suite.
Anyway. I search the code base and seems the invalid date is provided here:
https://github.com/matomo-org/matomo/blob/5.x-dev/tests/UI/specs/PeriodSelector_spec.js#L143
Not sure if this is done on purpose or was added by mistake.

**Comment by rr-it** [comment]
I found the ERROR API log-entry in the "raw logs":
![grafik](https://github.com/matomo-org/matomo/assets/29690343/c23cedff-9350-4ad5-9576-251d131f03d4)

----

This new test was introduced with https://github.com/matomo-org/matomo/pull/21242
And "Matomo Test / UI (1)" was also failing on this PR - but logs are no longer available.

https://github.com/matomo-org/matomo/blob/85948b63b2a2866b18a47e7d3628fe74cb0ecd46/tests/UI/specs/PeriodSelector_spec.js#L142C1-L147
```php
        it('should select "previous period" from URL', async function () {
          await page.goto(url + '&comparePeriods[]=day&comparePeriodType=previousPeriod&compareDates[]=2011-31-12');
          await page.waitForNetworkIdle();

          expect(await getSelectedPeriodType()).to.match(/Period/);
        });
```

@caddoo May we change this test to `compareDates[]=2011-12-31` instead of the current `compareDates[]=2011-31-12`?

**Comment by sgiehl** [comment]
@rr-it The test itself is passing. And the log entry actually is kind of expected in that case.
@mneudert Did you add that invalid date in the test on purpose?

**Comment by mneudert** [comment]
Nope, not intended to break this way. Created a small PR to change the date as already suggested.
