### ISSUE TITLE
Mauvaise version de Windows avec Firefox / Wrong version of Windows with Firefox

### ISSUE THREAD

**Issue by lorimode** [piwik/piwik#21757]
Bonjour
Je ne sait pas si c'est la bonne catégorie, mais je n'est pas trouvé mieux, alors :

J'ai remarqué qu'avec Firefox, et sur un PC Windows 11, étant à la base Windows 10 et mis à jour vers Windows 11, que Matomo affiche Windows 10, alors qu'avec d'autre navigateurs, Matomo affiche Windows 11, ce que le PC à actuellement...

Le problème se répète sur différent PC avec la même configuration : Ancien Windows 10 et mis à jour vers Windows 1, avec Firefox dernière version... 
Voila, cela vient il de Matomo ? Et sinon de quoi ?

Merci

---trad google---
Hello
I don't know if this is the right category, but I couldn't find anything better, so:

I noticed that with Firefox, and on a Windows 11 PC, being Windows 10 and updated to Windows 11, that Matomo displays Windows 10, while with other browsers, Matomo displays Windows 11, what the PC currently has...

The problem repeats itself on different PCs with the same configuration: Old Windows 10 and updated to Windows 1, with Firefox latest version...
Voila, does this come from Matomo? And if not what?

THANKS

**Comment by sgiehl** [comment]
Hi @lorimode,

Matomo is using [device detector](https://github.com/matomo-org/device-detector) to identify the device and it's settings using the useragent and client hints sent by the browser.
With Windows 11 the useragent fragment for the operating system was frozen, and the correct version can only be detected with client hints. More details can be found here: https://github.com/matomo-org/device-detector/issues/6928
You can check what you browser would be detected as using https://devicedetector.lw1.at/

**Comment by lorimode** [comment]
Mais cela vient de quoi ? de l'agent de détection Matomo ou de Firefox ? Car le problème est uniquement avec ce navigateur... 
Avec Opera, Edge, cela affiche Windows 11, donc pas de problème, mais c'est avec Firefox que sa marche pas bien...

---trad google--- 
But what does this come from? Matomo detection agent or Firefox? Because the problem is only with this browser...
With Opera, Edge, it displays Windows 11, so no problem, but it's with Firefox that it doesn't work well...
