### ISSUE TITLE
Arrondir les bords des widgets du tableau de bord / Round the edges of the dashboard widgets

### ISSUE THREAD

**Issue by lorimode** [piwik/piwik#21756]
Bonjour
Je pense que pour moderniser Matomo, vous devriez arrondir les bords des widgets du tableau de bord, cela ferait mieux...
Voila, merci...

---trad google---
Hello
I think to modernize Matomo you should round the edges of the dashboard widgets, it would look better...
There it is, thanks...

**Comment by sgiehl** [comment]
Hi @lorimode,

Thanks for the suggestion. We are working on modernizing the look and feel of Matomo step by step and may consider using rounded edges.
Anyway, if you would like to have Matomo looking a bit different you can consider [creating your own theme](https://developer.matomo.org/guides/theming).
Cheers,

**Comment by lorimode** [comment]
Merci...
---trad google---
Thanks...
