### ISSUE TITLE
Mauvaise version de Windows avec Firefox / Wrong version of Windows with Firefox

### ISSUE THREAD

**Issue by lorimode** [piwik/piwik#21768]
### What happened?

J'ai un PC avec Windows 11, qui était à la base Windows 10 et mis à jour vers Windows 11, Et avec le Navigateur Firefox, et avec uniquement Firefox, Il affiche que j'ai Windows 10, alors que j'ai Windows 11.
Avec d'autre navigateurs (Opera, Edge, Chrom, ETC...) Cela Affiche Windows 11 (se que j'ai)...
Donc, pourquoi avec Firefox, c'est Windows 10 qui est détecté et pas Windows 11 ?

---trad google---
I have a PC with Windows 11, which was originally Windows 10 and updated to Windows 11, And with the Firefox Browser, and with only Firefox, It shows that I have Windows 10, when I have Windows 11 .
With other browsers (Opera, Edge, Chrom, ETC...) It shows Windows 11 (which I have)...
So, why with Firefox, is Windows 10 detected and not Windows 11 ?

### What should happen?

Il devrait sa passer que Firefox détecte Windows 11, comme tous les autres navigateurs, alors que là, il détecte Windows 10...

---trad google---
It should happen that Firefox detects Windows 11, like all other browsers, whereas there, it detects Windows 10...

### How can this be reproduced?

Ordinateur Avec Windows 11, ancien Windows 10 et mis à jour vers 11, Navigateur Firefox dernière version, installation Matomo classique, avec plugin de détection des fournisseurs internets en plus...

---trad google---
Computer With Windows 11, old Windows 10 and updated to 11, Firefox browser latest version, classic Matomo installation, with internet provider detection plugin in addition...

### Matomo version

4.5 et 5.0

### PHP version

8.2

### Server operating system

?

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Windows 11

### Relevant log output

```shell
???
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
As mentioned on the other issue: Windows 11 reports Windows 10 in it's user agent. Windows 11 can only be detected through client hints. Client hits are currently not support by Firefox (and certain other browsers). See e.g. https://caniuse.com/?search=client-hints
There is unfortunately nothing we can do about that.

**Comment by lorimode** [comment]
Donc le problème vient bien de Firefox ? C'est cela ?
---trad google---
So the problem really comes from Firefox? That's it ?

**Comment by lorimode** [comment]
SVP, j’attends un réponse...
---trad google---
Please, I'm waiting for a response...

**Comment by sgiehl** [comment]
Yes.

**Comment by lorimode** [comment]
Merci 😊...
---trad google--- 
Thanks😊...
