### ISSUE TITLE
[Bug] Unable to close visitor profile by clicking 'x' button with one click.

### ISSUE THREAD

**Issue by enual** [piwik/piwik#21762]
### What happened?

From Matomo Dashboard, if you click the visitor profile, it's not possible to close it by clicking the 'x' button with one click.
![image](https://github.com/matomo-org/matomo/assets/132400623/07c8a959-edf8-4a2f-addc-0304d3fd74be)

### What should happen?

If they click the 'x' button it should close the pop up box for the visitors profile right away.

### How can this be reproduced?

Matomo Dashboard > Visit in real time widget > click visitor's profile > click 'x' to close it.

### Matomo version

5.0.0

### PHP version

8.2.10

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by atom-box** [comment]
I reproduced this problem in these browsers:
Firefox, Brave, Safari, Edge



![image](https://github.com/matomo-org/matomo/assets/22874146/8d4e5ba5-9751-4124-aa21-53b87bf4b3d5)

**Comment by lorimode** [comment]
Oui, j'ai le même problème depuis Matomo 5.0.0...
---trad google---
Yes, I have the same problem since Matomo 5.0.0...
