### ISSUE TITLE
[Bug] Unable to register license key

### ISSUE THREAD

**Issue by sashozahariev** [piwik/piwik#21771]
### What happened?

I am attempting to install a license key on Matomo. Specifically, the goal is to activate the Funnels plugin in a Docker container via command line. The expected outcome is to execute the command and register the key:
`./console marketplace:set-license-key --license-key=xxx`
where 'xxx' is the serial number for the marketplace. 
Unfortunately, it returns an error message "This license key is not valid.":

> root@59cbdce26754:/var/www/html# /var/www/html/console marketplace:set-license-key --license-key=xxx
> ERROR     [16:50:36] 150  Uncaught exception: /var/www/html/plugins/Marketplace/API.php(89): This license key is not valid. [Query: , CLI mode: 1]
> 
> In API.php line 89:
> 
>   This license key is not valid.

I have tried all possible syntax variations of the command that I could think of, namely:

bash
Copy code
```
./console marketplace:set-license-key --license-key=xxx
./console marketplace:set-license-key --license-key="xxx"
./console marketplace:set-license-key --license-key xxx
./console marketplace:set-license-key --license-key "xxx"
```

I've tried with both Matomo Docker versions 4.16.0 and 5.0.1. 

### What should happen?

The license key should be added successfully. 
The same key works as expected via the UI

### How can this be reproduced?

Run /path/to/console marketplace:set-license-key --license-key=xxx

where xxx is the actual license key.

### Matomo version

4.16.0, 5.0.1

### PHP version

8.2

### Server operating system

Ubuntu 20.04.6 LTS

### Computer operating system

Windows 10, WSL 2

### Relevant log output

```shell
root@59cbdce26754:/var/www/html# /var/www/html/console marketplace:set-license-key --license-key=xxx
ERROR     [16:50:36] 150  Uncaught exception: /var/www/html/plugins/Marketplace/API.php(89): This license key is not valid. [Query: , CLI mode: 1]

In API.php line 89:

  This license key is not valid.

marketplace:set-license-key [--license-key LICENSE-KEY]
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @sashozahariev. I've just tried myself, I signed up for a new account at https://shop.matomo.org/, then got the license key from https://shop.matomo.org/my-account/downloads/ and used that with the first variant of the console command, i.e. with the equal sign and without the quotes, and the key got set correctly.

At this stage I don't think it would be a code issue and I would recommend contacting the support team via shop@matomo.org email. It could be possible they might be able to provide you with a replacement license key for the same subscription.

Alternatively, if you don't have any purchases yet, try using a different email to sign up to the store, get a different licence key and try again to see if it helps. The UI and the CLI way uses the same endpoint to validate the license key so it's strange it wouldn't work in one of the places. Also make sure there are no invisible characters when you copy and paste the code, you could try typing it in manually in the CLI.

**Comment by sashozahariev** [comment]
Hi there, @michalkleiner .
Thank you for the prompt response!
Will try the suggestions.

**Comment by sgiehl** [comment]
As there hadn't been any further activity on this issue in the last months, we assume that it works as expected now.
If not, feel free to contact our support for issues around license keys. Thanks.
