### ISSUE TITLE
[Bug] cannot run ./console after update from 4.16.0 to 5.0

### ISSUE THREAD

**Issue by hafriz** [piwik/piwik#21775]
### What happened?

try to run ./console help and error come out 

ERROR     [04:47:41] 563594  Uncaught exception: TypeError: Symfony\Component\Console\Application::has(): Argument #1 ($name) must be of type string, null given, called in /www/analytics/core/Console.php on line 172 and defined in /www/analytics/vendor/symfony/console/Application.php:592
Stack trace:
#0 /www/analytics/core/Console.php(172): Symfony\Component\Console\Application->has()
#1 /www/analytics/core/Console.php(131): Piwik\Console->addCommandIfExists()
#2 /www/analytics/core/Console.php(85): Piwik\Console->doRunImpl()
#3 /www/analytics/vendor/symfony/console/Application.php(171): Piwik\Console->doRun()
#4 /www/analytics/console(32): Symfony\Component\Console\Application->run()
#5 {main}
Uncaught exception in /www/analytics/vendor/symfony/console/Application.php line 592:
Symfony\Component\Console\Application::has(): Argument #1 ($name) must be of type string, null given, called in /www/analytics/core/Console.php on line 172

### What should happen?

console help information list will shown 

### How can this be reproduced?

ssh to server, go to matomo path execute ./console or php /www/analytics/console core:archive --url=https://website.com

### Matomo version

5.0.1

### PHP version

8.1

### Server operating system

Ubuntu 20.04

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
ERROR     [04:47:41] 563594  Uncaught exception: TypeError: Symfony\Component\Console\Application::has(): Argument #1 ($name) must be of type string, null given, called in /www/analytics/core/Console.php on line 172 and defined in /www/analytics/vendor/symfony/console/Application.php:592
Stack trace:
#0 /www/analytics/core/Console.php(172): Symfony\Component\Console\Application->has()
#1 /www/analytics/core/Console.php(131): Piwik\Console->addCommandIfExists()
#2 /www/analytics/core/Console.php(85): Piwik\Console->doRunImpl()
#3 /www/analytics/vendor/symfony/console/Application.php(171): Piwik\Console->doRun()
#4 /www/analytics/console(32): Symfony\Component\Console\Application->run()
#5 {main}
Uncaught exception in /www/analytics/vendor/symfony/console/Application.php line 592:
Symfony\Component\Console\Application::has(): Argument #1 ($name) must be of type string, null given, called in /www/analytics/core/Console.php on line 172
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by hafriz** [comment]
The issue is close as the console cannot be run because of problem with compatibility of performanceAudit plugin

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-when-try-to-run-archive/54733/4
