### ISSUE TITLE
Matomo Screen Recording Stopped After 3 Sessions

### ISSUE THREAD

**Issue by chrisativonne** [piwik/piwik#21776]
We purchased the Screen Recording and Heatmap function. After setting it up I noticed it only recorded 3 sessions.

However the config confirms it is set to:
This session recording is active. Up to 1000 sessions will be recorded with a sample rate of 100.0%.

Where should I look?

Thank you in advance.

**Comment by michalkleiner** [comment]
Hi @chrisativonne, thank you for creating this issue. In this issue tracker we only manage issues for Matomo core. For premium feature related enquiries please email our support at shop@innocraft.com. Thank you for you understanding and sorry for the inconvenience.
