### ISSUE TITLE
[Bug] Envelope icon is missing in Manage Users (regression)

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21774]
### What happened?

In Admin >> Users >> Manage Users there used to be an envelope icon next to the 
_Edit_ and _Delete_ icons. It is now missing.

### What should happen?

- I expect to have an envelope icon that I can click if I want to copy a link for inviting a new User.
- I expect it to work as described in this documentation:  https://matomo.org/faq/invite-a-new-user-if-email-hasnt-worked/ 

### How can this be reproduced?

This is present in:
Brave: Matomo Cloud
Brave: Matomo On Premise
Firefox: Matomo Cloud
Firefox: Matomo On Premise

![image](https://github.com/matomo-org/matomo/assets/22874146/dfddde45-93c6-42e9-b058-f96c4aba5291)
![image](https://github.com/matomo-org/matomo/assets/22874146/75fc0b2e-7b56-404d-9b3d-02158b3fc4b4)

### Matomo version

5.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer operating system

Linux

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@atom-box The users on the screenshot are already active. So they already accepted an invite or were added directly. It's only possible to resend an invite to users that were invited before, but did not accept the invite yet.

**Comment by bx80** [comment]
I can't recreate this - for users with a pending invite the envelope option to allow resending is shown:

![image](https://github.com/matomo-org/matomo/assets/88810029/25482a59-43e8-4857-a9c2-029c82c908bd)

I'll close this issue for now, but if you see the resend option missing for a user with an pending invite then please reopen.
