### ISSUE TITLE
[Bug] Uploading logo throws token error

### ISSUE THREAD

**Issue by downhiller** [piwik/piwik#21770]
### What happened?

When I try to upload a custom logo to a clean new install of Matamo 5.0.0 (updated to 5.0.1) I get kicked to the login screen with the message 

```
Error: We're sorry, but the action you were trying to perform failed due to a security check. This is a standard measure to ensure the safety and security of your account. Please try again, and if the issue persists, please contact our support team for further assistance.
```

### What should happen?

It should have uploaded the logo

### How can this be reproduced?

Under "Become a Matomo expert" click "Upload your logo", scroll down to "Branding settings", tick "Use a custom logo", then click the "SELECT A LOGO TO UPLOAD" button.

### Matomo version

5.0.1

### PHP version

8.3.1

### Server operating system

CentOS 8 Stream

### What browsers are you seeing the problem on?

Microsoft Edge

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
I've just checked this locally, and it works without problem for me.
Does the problem persist and occur every time you try to upload it?

**Comment by downhiller** [comment]
I found the nginx matamo.conf file that you guys offer and replaced the one I'd made myself and that's fixed the issue.
