### ISSUE TITLE
Added the possibility of marking a visit and a visitor

### ISSUE THREAD

**Issue by lorimode** [piwik/piwik#21806]
Ajouté la possibilité de marqué une visite et un visiteur :

Il serait bien de pouvoir marqué un visiteur, ou même un visite, par exemple, pour la retrouvé plus facilement, parce que c'est une visite "modèle" et que je veux pouvoir la revoir et la gardé comme référence, ou bien parce que cette visite c'est mal passée, et que je veux garder le parcours de l'usager pour améliorer mon site...
Bref, plain de possibilité avec cette potentiel fonction, d’où l'idée de l'ajouter !

---trad google--- 
Added the possibility of marking a visit and a visitor :

It would be nice to be able to mark a visitor, or even a visit, for example, to find it more easily, because it is a "model" visit and I want to be able to see it again and keep it as a reference, or because this visit went badly, and I want to keep the user's journey to improve my site...
In short, lots of possibilities with this potential function, hence the idea of ​​adding it !

**Comment by sgiehl** [comment]
Sounds like a duplicate of https://github.com/matomo-org/matomo/issues/8161
