### ISSUE TITLE
Added ad blocker detection

### ISSUE THREAD

**Issue by lorimode** [piwik/piwik#21805]
Ajout de la détection de bloqueurs de publicités :

Je propose d'inclure la détections des bloqueurs de publicités dans Matomo, pour pouvoir voir quelle proportion des usagés des sites suivis utilise se genre de choses, quel pays, quel visiteurs, bref, ajouter cette possibilité dans Matomo.
Voila.

--trad google---
Added ad blocker detection :

I propose to include the detection of ad blockers in Matomo, to be able to see what proportion of users of the sites tracked use this type of thing, which country, which visitors, in short, add this possibility in Matomo.
So.

**Comment by sgiehl** [comment]
duplicate of https://github.com/matomo-org/matomo/issues/9165
