### ISSUE TITLE
[Bug] Console Archive Command ignores `–quiet` in v5.0.1

### ISSUE THREAD

**Issue by WBTMagnum** [piwik/piwik#21800]
### What happened?

Our archive cronjob started to generate output after upgrading to v5.0.1 even though the command is invoked with the parameter `--quiet`.

The generate output looks as follows:
```
INFO      [06:10:01] 47645  ---------------------------
INFO      [06:10:01] 47645  INIT
INFO      [06:10:01] 47645  Running Matomo 5.0.1 as Super User
INFO      [06:10:01] 47645  ---------------------------
INFO      [06:10:01] 47645  NOTES
INFO      [06:10:01] 47645  - Async process archiving supported, using CliMulti.
INFO      [06:10:01] 47645  - Reports for today will be processed at most every 900 seconds. You can change this value in Matomo UI > Settings > General Settings.
INFO      [06:10:01] 47645  - Archiving was last executed without error 59 min 56s ago.
INFO      [06:10:01] 47645  ---------------------------
INFO      [06:10:01] 47645  START
INFO      [06:10:01] 47645  Starting Matomo reports archiving...
INFO      [06:10:01] 47645  0 out of 3 archivers running currently
DEBUG     [06:10:01] 47645  Applying queued rearchiving...
```

It also seems that there `-verbose` parameter is ignored.

Note: This issue has also been reported on the forum: https://forum.matomo.org/t/console-quiet-no-longer-works-in-5-0-1/54761/1

### What should happen?

If there are no errors, the archiver should not generate any output.

### How can this be reproduced?

Case 1 (working): `./console core:archive --help --quiet` will not generate any output

Case 2 (not working): `./console core:archive --quiet --url=https://matomo.url/`

### Matomo version

5.0.1

### PHP version

8.1.27

### Server operating system

Debian GNU/Linux 11 (bullseye)

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
This might have happened due to updating symfony console. Maybe the handling of `--quiet` changed internally there.
I'll have a quick look if that can be fixed easily.

**Comment by WBTMagnum** [comment]
I cherry-picked the change in one project. Works as expected. Thanks for the swift fix.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/console-quiet-no-longer-works-in-5-0-1/54761/2
