### ISSUE TITLE
[Bug] Can't delete users as superuser

### ISSUE THREAD

**Issue by drakanor** [piwik/piwik#21817]
### What happened?

Logged in as superuser in a self-hosted Matomo instance, I can't delete other users. When clicking the delete user button in the user overview, I'm getting a popup requesting my superuser password. After entering it, I'm getting an error message "The current password you entered is not correct.".
The  password is correct, I'm taking it from a password manager and it works for all other superuser tasks.

### What should happen?

When clicking the delete user button in the user overview as a superuser, the user should be deleted. There shouldn't even be a superuser password check.

### How can this be reproduced?

"Administration" -> "System" -> "Users -> delete a user by clicking on the trash can on the far right side of it's entry

### Matomo version

4.16.0

### PHP version

8.1.27

### Server operating system

Debian Bookworm 12.4

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @drakanor. There is a known problem around the password confirmation if your password contains certain special characters.
This was fixed with Matomo 5. So please consider updating you instance. If the problem remains, feel free to create a new issue.
