### ISSUE TITLE
Documentation page that consider segment as filter: Segment a Custom Dimension by Action type

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/piwik#21823]
Wrong documentation page:
https://matomo.org/faq/reporting-tools/segment-a-custom-dimension-by-action-type/

In this documentation, segment is considered as filter. I think this should maybe mention filter configuration in custom reports (instead of segments).

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/distinguish-from-page-views-and-events-of-a-custom-dimension/54905/2

**Comment by gillnd** [comment]
Thanks for your patience with this issue. We believe it has been resolved in a recent documentation update for https://matomo.org/faq/reporting-tools/segment-a-custom-dimension-by-action-type/. If this did not fully address your concern, feel free to reopen this issue and let us know. We'll gladly take another look!
