### ISSUE TITLE
[Bug] Suggested values of segment list pulldown: headless chrome choice is missing

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21828]
### What happened?

The pulldown in `Segment >> Browser is >> _______`  is missing Headless Chrome as a choice. 
Maybe others are missing too?
The code file is 

`plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml`

### What should happen?

We should still see the choices that were available in Matomo 4.16 and 5.0.0

Screenshot of 4.16
![image](https://github.com/matomo-org/matomo/assets/22874146/599bcfca-d366-4766-adf6-ac074c83c3e4)

Screenshot of 5.0.1
![image](https://github.com/matomo-org/matomo/assets/22874146/ad51e3be-408f-4edd-ac13-d29e245761de)

### How can this be reproduced?

Make a segment, try to choose `Browser // is // Headless Chrome`

### Matomo version

5.0.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@atom-box this might be expected behavior. The drop down only shows a maximum of 30 records. The List of browser is a way longer, so it shows the top30 list, sorted by latest usage.

**Comment by atom-box** [comment]
I think you are correct, thank you. Therefore I am closing this.

When I start to type "CH" I get the expected "headless chrome".
![image](https://github.com/matomo-org/matomo/assets/22874146/12105810-5e0c-44cf-8e17-e805bc0a7097)

**Comment by atom-box** [comment]
Works as intended. See above.

**Comment by atom-box** [comment]
Works as intended. Am closing this. See above.
