### ISSUE TITLE
[Bug] Matomo Web UI doesn't recognize new Version

### ISSUE THREAD

**Issue by ErikFeise** [piwik/piwik#21827]
### What happened?

Hi y'all

Just a quick infomartion in advance, we use matomo with docker-compose. 
Since the Version 4.16 Matomo no longer displays new versions via the button for upgrading. 
I read that this may be a Problem with the FW. 

I've checked this with our IT-Sec team and the VM, on which our matomo instances are running, are allowed to go out on the Internet. 

After that I tried:
`wget builds.matomo.org` 
and
`curl "https://api.matomo.org/1.0/getLatestVersion/"` 
which where not working inside the docker container.
I then created my own docker image (with matomo 5), that loads all my company certificates into the container and does
`update-ca-certificates`

After that all the commands from above will get the expected results (executed in the docker container).
Still the matomo web UI doesnt recognize that there is a new version available and shows that I'm still using Version 4.16. 

### What should happen?

Matomo should recognize, that there is a new version available in the Web UI

### How can this be reproduced?

Hard to reproduce.

Maybe: Click on "check for updates" on Version 4.16, while running matomo via docker-compose

### Matomo version

4.16

### PHP version

8.2.14

### Server operating system

RHEL 8.9

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer operating system

Win10 

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
Hi @ErikFeise, this repository is for the core Matomo application so we can't provide help for the matomo docker image here. You can try https://github.com/matomo-org/docker where you're more likely to get a helpful response, thanks for your understanding :slightly_smiling_face:

**Comment by ErikFeise** [comment]
Hi @bx80,
Thanks for pointing that out!
And sorry for posting in the wrong repository
