### ISSUE TITLE
[Bug] Annotations get wrong date on timeline chart view

### ISSUE THREAD

**Issue by dominiklaube** [piwik/piwik#21837]
Matomo Version:  5.0.1

**Bug Scenario:**

1. Create an annotation with the date 01-20-2024
2. The annotation will wrongly get marked on the timeline chart view for the date 01-19-2024
3. click on the annotation icon next to the timeline - no annotation appears because annotations for 01-19-2024 get listet
4. check: click on the annotations icon which appears on hover for the full timeline. The annotation is in the list with the correct date 

Conclusion: Annotation icons that are displayed next to the timeline chart get the wrong date.

![matomo-annotations-4](https://github.com/matomo-org/matomo/assets/11940726/3faf7546-e7b4-4182-9c10-bc1048e1d203)

**Comment by mneudert** [comment]
Hi @dominiklaube,

I wasn't able to reproduce this issue. Could you, as it seems to be reproducible for you, provide some details what is happening here?

Using `01-20-2024` as an example, if you start adding an annotation to the graph, for a date that has no annotations yet, you should see roughly this:

![](https://github.com/matomo-org/matomo/assets/635801/0e50e251-a2e5-40c2-9176-00e3ae6632b6)

Both the italic-grey date and the bordered-blue-ish date should match.

If you open the network tab of your browser's developer tools, you should find a POST request to a URL containing `module=Annotations&action=addAnnotation` after saving the new annotatoin. The details should look like this:

![Screenshot from 2024-01-29 17-39-43](https://github.com/matomo-org/matomo/assets/635801/28a8d7de-f5cc-4c9d-9410-3f0fbc4be14f)

- `managerDate` should be the same as to the italic-grey date
- `date` should be the same as the bordered-blue-ish date

And the response should contain the created annotation with the same date as the other places:

![](https://github.com/matomo-org/matomo/assets/635801/de6dc401-3508-474d-baa7-419fbf92d00f)

Is the same single date value used everywhere, is it somewhere a date range (e.g. `01-19-2024,01-20-2024`), or does it change in some of the places?

**Comment by dominiklaube** [comment]
Hey @mneudert,

i made a video to demonstrate the behaviour. I think this schould help to make it reproduceable for you.

https://github.com/matomo-org/matomo/assets/11940726/a359dd98-a430-4d56-ae13-27fc3ce5153d

**Comment by mneudert** [comment]
Hi @dominiklaube,

thank you very much for the video. The period selector ("From ... To ...") was the actual hint needed.

I assume your user is set up to display "Last 30 days (including today)" by default for all reports. Matching that setting I was able to reproduce your issue. ("Previous 30 days (not including today)" should also show that problematic behaviour).

Could you confirm the annotations are getting placed properly if you switch to a regular range? (open the period selector and just hit apply, it should already match a custom 30 day date range in your case).

**Comment by dominiklaube** [comment]
@mneudert yes, I can confirm that when i reapply the period selector the annotations are getting placed properly.
