### ISSUE TITLE
Redirecting to the default site ID after OIDC authentication.

### ISSUE THREAD

**Issue by OrangeTech-Melissa** [piwik/piwik#21848]
### What happened?

When I navigate to: `https://<matomo_url>/index.php?module=CoreHome&action=index&idSite=X&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1`, I first pass through OIDC authentication. However, Matomo redirects me to the default site ID.

### What should happen?

The redirection should lead us to the site's dashboard with ID X, rather than the default site.

### How can this be reproduced?

Navigate to: `https://<matomo_url>/index.php?module=CoreHome&action=index&idSite=X&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1`

### Matomo version

4.12.3

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @Meli1Git, sorry to hear you're having issues with the redirection after logging in. Since OIDC login is provided by a community plugin, could you check if the same issue occurs when you try logging in using other means, e.g. the standard username and password?

**Comment by OrangeTech-Melissa** [comment]
Hi @michalkleiner, thanks for your quick response. Indeed, the issue doesn't occur with standard username and password authentication – it redirects to the correct site. It seems to be specific to OIDC authentication

**Comment by michalkleiner** [comment]
Thanks for the confirmation @Meli1Git. In that case I would ask you to raise the issue with the plugin developer at [their issue tracker](https://github.com/dominik-th/matomo-plugin-LoginOIDC) as there's nothing we can do in Matomo itself. Alternatively you can check the Matomo forum on https://forum.matomo.org to see if someone had a similar issue in past.

With that I will close this issue. Thank you for your understanding.
