### ISSUE TITLE
Delete user does not work.

### ISSUE THREAD

**Issue by STS-AG** [piwik/piwik#21840]
Hi there

Unfortunately I cannot delete any of my users in our account although I have admin access.

Can you please help!

Thanks and best regards
David

**Comment by michalkleiner** [comment]
Hi @STS-AG,
unfortunately we don't provide user support/answer questions through this issue tracker. We only accept feature requests or bug reports. We recommend asking the question in our forum at https://forum.matomo.org/.

Related to your question, you can check https://matomo.org/faq/general/manage-users/ that relates to user management. A quick skim through the document mentions only super admins can delete users. Admins can only invite new users and manage user roles for sites they manage. So you may need to contact your super admin.

With that I will close the issue. Thanks for your understanding.
