### ISSUE TITLE
'Log in' action from matomo.org website in mobile view hardly unusable

### ISSUE THREAD

**Issue by TartejBrothers** [piwik/piwik#21853]
- The login button is very small and pretty hidden, specially in the mobile view. 
![image](https://github.com/matomo-org/matomo/assets/112921727/1cbb60a3-0099-4eb3-99be-c65e4b01754d)
- it is inside the menu.
- On desktop view we can place it next to try it for free, there is a lot of space there. 
<img width="261" alt="image" src="https://github.com/matomo-org/matomo/assets/112921727/b2fcb40b-b584-44bc-b022-acc0802a19a9">

- It looks like an after thought

**Comment by michalkleiner** [comment]
Hi @TartejBrothers, thank you for reporting the issue with the website and the 'Log in' action in the mobile menu. I'd agree that the UX around that can be improved. Even though this is not directly related to Matomo (the product) which this issue tracker is for, I'm passing this to the product team to prioritise.

On top of the UX aspect, there is actually a bug where `#help_center_link { right: 10px; }` CSS declaration causes the Help link to overlay the Log in link and the Log in link can't be tapped on mobile devices.

**Comment by AltamashShaikh** [comment]
@michalkleiner @TartejBrothers  I have fixed the login_link click not working on mobile for now, we can improve the UI once we schedule this.

**Comment by Stan-vw** [comment]
Thanks @AltamashShaikh . Since it's fixed I'll close the ticket. 

Please feel free to reopen in case it's still not properly usable on some devices.
