### ISSUE TITLE
[Bug] Two-factor authentication title doesn't seem to be correctly encoded in the QR code

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#21856]
### What happened?

2FA apps (e.g. FreeOTP) do not recognize the name that was entered in the 2FA configuration (Two-factor authentication title). Some issue a warning (e.g. FreeOTP). Sometimes, the username is used as a token title.

### What should happen?

2FA Apps should recognize the configured "Two-factor authentication title" from the QR code and use that together with the username.

### How can this be reproduced?

Setup 2FA for an account and check the application name, which was recognized by the OTP app. 

### Matomo version

4.15.x - 5.0.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @peterbo 
I just tried that with google authenticator, and there it works without problems.
The URL is generated here:
https://github.com/matomo-org/matomo/blob/8bfe2c7465a25081d8e5a23fcfa9b2f888272d41/plugins/TwoFactorAuth/Controller.php#L336-L344

**Comment by peterbo** [comment]
Hey @sgiehl thank you for always referencing the code for an issue. That helps a lot in analyzing a potential problem. I think in this case, we're somehow correct with the current implementation, but Google recommends using the issuer as a prefix in addition to the &issuer parameter (but not all specifications encourage to do so... So I don't know, what's right). However, some TOTP applications don't seem to have incorporated the other standard yet.

So as per https://github.com/google/google-authenticator/wiki/Key-Uri-Format, the string format should be:
`otpauth://totp/<<ISSUER>>:<<ACCOUNT_NAME>>?secret=<<BASE32_KEY>>&issuer=<<ISSUER>>`
("We recommend using both an issuer label prefix and an issuer parameter, described below."). Also important for the validation "Neither issuer nor account name may themselves contain a colon".

**Comment by sgiehl** [comment]
@peterbo I've just tested that locally. If I add the issuer as prefix and as parameter the google authenticator actually displays it incorrectly 😩 
So not sure how to improve this

**Comment by peterbo** [comment]
@sgiehl thanks for testing! - In this case, I think we could leave it just like it is now. The FreeOTP app is by RedHat, but it has bad reviews and they don't seem to be interested in keeping it up to date. Thank you, @sgiehl !

**Comment by sgiehl** [comment]
@peterbo Shall we close the issue? I don't think there is anything we can do to improve it.
