### ISSUE TITLE
[Bug] Bad date formatting in email reports

### ISSUE THREAD

**Issue by bojana-z** [piwik/piwik#21867]
### What happened?

When selecting the date range 'week' in the calendar and sending an HTML or PDF email report, symbols appear below the evolution graph in the date field that should not be there.
![image](https://github.com/matomo-org/matomo/assets/146905988/621b6dc5-efb2-4c72-8a16-ce659d90a4fe)

### What should happen?

We should see the normal date range, without any strange symbols, below evolution graph in email report.

### How can this be reproduced?

Go to Email Reports, Select 'week' from calendar and send report.
![image](https://github.com/matomo-org/matomo/assets/146905988/e4e5e5fa-0446-4592-9cb7-72eff1a8f49e)

### Matomo version

5.0.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Thanks for the report @bojana-z.

There seems to be some unicode being mixed into the formatting and not getting rendered well. Will prepare a quick fix for that.
