### ISSUE TITLE
MATOMO_SESSID cookie set even with "Force tracking without cookies" option enabled

### ISSUE THREAD

**Issue by PixelbarEupen** [piwik/piwik#21860]
### What happened?

We have a matomo instance running with cookieless tracking via "Force tracking without cookies" option enabled.

Now we discovered that several of the sites that have our matomo tracking code inserted have a cookie set named MATOMO_SESSID.

The tracking code is the following:

```
<script>
var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(["disableCookies"]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
  var u="https://XXXXXX.XXXXXX.TLD/";
  _paq.push(['setTrackerUrl', u+'matomo.php']);
  _paq.push(['setSiteId', 'XXX']);
  var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
  g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
```

### What should happen?

When cookieless tracking is forced no cookie should be set.

### How can this be reproduced?

Enable "Force tracking without cookies" and check the websites that use the tracking code. Some will have set the cookie.

### Matomo version

5.0.1

### PHP version

8.2.13

### Server operating system

debian buster

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@PixelbarEupen Are you sure the cookies are set for the domains the tracking code is installed on? Afaik the `MATOMO_SESSID` is set when you visit the Matomo instance, as it's used as session cookie for it. So if you visited the Matomo instance before, that cookie might still exist and be visible in the browser console, as your page is requesting data from the Matomo instance.

**Comment by PixelbarEupen** [comment]
omg. You're right, thank you - never thought about this! In fact the behaviour is exactly how you describe it. Erased all cookies and it came back after logging in into my matomo instance. Never to late to learn something

Issue closed, thanks
