### ISSUE TITLE
[Bug] Tracking Code requires Overlay plugin to be enabled

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#21891]
### What happened?

With Overlay plugin deactivated, and you go to 

Measureables -> Tracking Code

You get a warning:

> The plugin Overlay is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.

It also makes the area to get the Tracking Code for JavaScript non working (empty).

### What should happen?

You should get the Tracking Code, and no warning.

### How can this be reproduced?

Deactivate Overlay plugin if it is enabled.

Then you go to:
Measureables -> Tracking Code

You get the warning and nothing for the Tracking Code.

### Matomo version

5.0.2

### Relevant log output

```shell
Uncaught exception in API: /var/www/html/core/Plugin/Manager.php(303): The plugin Overlay is not enabled. You can activate the plugin on Settings > Plugins page in Matomo. [Query: ?date=yesterday&module=API&format=json&method=Overlay.getExcludedQueryParameters&idSite=1&filter_limit=-1&segment=&period=day, CLI mode: 0]
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mikkeschiren** [comment]
Suggested solution would be to add `public function getExcludedQueryParameters($idSite)` to CoreAdminCore, that would cause code duplication, but it also makes core functionality work without the need of a none required plugin, and will not break anything. I can create a pull request for this.

**Comment by sgiehl** [comment]
Thanks for the report. This indeed shouldn't be that case. I'll prepare a fix for that.
