### ISSUE TITLE
[Bug] Matomo 5.0.2 update timeouts 

### ISSUE THREAD

**Issue by neubreed** [piwik/piwik#21890]
### What happened?

I've been trying to update Matomo to 5.0.2 (from 5.0.1) via the web from the link in the upgrade email. And it's repeatedly timing out, even when setting php with unlamented execution time.

After several attempts I decided to do it manually following these instructions https://matomo.org/faq/on-premise/update-matomo/#the-manual-three-step-update

First problem encountered https://builds.matomo.org/matomo.zip](https://builds.matomo.org/matomo.zip is not the latest, so I downloaded the [matomo-5.0.2.zip](https://builds.matomo.org/matomo-5.0.2.zip) file using wget.

Second problem is that the transfer speed from builds.matomo.org only ranges from 2KBkb/s and 50KB/s. Extremely slow for some reason and times out. Which is probably why the web update is timing out  

```shell
wget https://builds.matomo.org/matomo-5.0.2.zip
--2024-02-07 13:55:49--  https://builds.matomo.org/matomo-5.0.2.zip
Resolving builds.matomo.org (builds.matomo.org)... 185.31.40.177, 2a00:b6e0:1:200:177::1
Connecting to builds.matomo.org (builds.matomo.org)|185.31.40.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26066124 (25M) [application/zip]
Saving to: 'matomo-5.0.2.zip’

matomo-5.0.2.zip                                         94%[=====================================================================================================================>        ]  23.37M  40.2KB/s    in 7m 29s

2024-02-07 14:03:19 (53.3 KB/s) - Connection closed at byte 24509100. Retrying.

--2024-02-07 14:03:20--  (try: 2)  https://builds.matomo.org/matomo-5.0.2.zip
Connecting to builds.matomo.org (builds.matomo.org)|185.31.40.177|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 26066124 (25M), 1557024 (1.5M) remaining [application/zip]
Saving to: 'matomo-5.0.2.zip’

matomo-5.0.2.zip                                        100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=======>]  24.86M   443KB/s    in 3.4s

2024-02-07 14:03:25 (443 KB/s) - 'matomo-5.0.2.zip’ saved [26066124/26066124]
``` 

### What should happen?

Web update normally works, although last time it took a few tries

### How can this be reproduced?

Click the update link from the Matomo to 5.0.2 upgrade email. 

### Matomo version

5.0.1

### PHP version

7.4

### Server operating system

Ubuntu 18.04

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @neubreed! Thank you for opening the issue and sorry to hear you have troubles updating to latest Matomo 5.0.2. I've checked the download link and it correctly downloads Matomo 5.0.2 version in the zip for me.

Can I check a few things:
1. Is this the first time something like that occurred? Update to 5.0.1 worked ok?
2. Have you tried running the update e.g. a day after or during a different time of the day? It's possible the connection speed of your server to the builds server being slow may impact the web update.
3. Did you manage to update using the manual steps or are you still experiencing update issues?

**Comment by hhrensheng** [comment]
I have the same problem.
The update to 5.0.1 was successful.

**Comment by hhrensheng** [comment]
During the upgrade, sometimes it will prompt '很抱歉，由于安全检查，您尝试执行的操作失败。这是确保您帐户安全的标准措施。请重试，如果问题仍然存在，请联系我们的支持团队以获得进一步帮助。'
When you click "Update Automatically" again, it will time out.

**Comment by neubreed** [comment]
My update to 5.0.1 timed out. I increased php execution timeout, and it eventually worked. However, upgrading to 5.0.2 I set it to unlimited and still timed out so I had to do a manual update

**Comment by neubreed** [comment]
My 5.0.1 update timed out a few times. I increased the PHP execution time to 5 minutes and it worked. However, the 5.0.2 update didn't work even if PHP execution time was set to unlimited. 

I think the issue is that the server downloading the update package is slow from my geo, and it's dropping the connection before the download finishes.

**Comment by sgiehl** [comment]
The process to update Matomo can indeed take some time. To ensure it runs through correctly, it might not only be needed to increase the max execution time for PHP, but also the webserver configuration could cause the connection to be closed after a certain amount of time.
If you aren't able to autoupdate due to this reason, I guess the simplest solution is to do a manual update.
