### ISSUE TITLE
[Bug] Header background color affects Cohorts report 

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#21899]
### What happened?

Setting a custom color for the header background in the White Label section, also adjusts the text/columns of the Cohorts report.
**Administration(cog icon) > System > General Settings > White Label.**

If you have a white header background set, the text of that report is not viewable unless you highlight the text.

For example:

![image](https://github.com/matomo-org/matomo/assets/118518962/fec6c8f4-befe-4ea5-be57-4249c08ab3a6)
![image](https://github.com/matomo-org/matomo/assets/118518962/75e3b21a-b161-49cf-87d0-dd4dfa15edb2)

### What should happen?

Only the color of the theme/dashboard header should change.

### How can this be reproduced?

Try changing the color of the header in **Administration(cog icon) > System > General Settings > White Label** then check the Cohorts report. This could only be reproduced in Matomo cloud.

### Matomo version

5.0.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@goochj03 Does that only happen for Cohort reports or any other report as well? If it only affect Cohorts, please create an internal issue instead, as it only involves Premium plugins.

**Comment by Stan-vw** [comment]
Good catch @goochj03 , we'll have to look into this. Great edge case.
As Stefan asked, kindly confirm if it's only for Cohorts or whether this happens on other places as well. I'm aware we recently changed this for Cohorts so we'll adjust that, but I imagine there could be other reports that use theme based color coding as well.

**Comment by Stan-vw** [comment]
This is fixed in https://github.com/innocraft/plugin-Cohorts/pull/81
