### ISSUE TITLE
System Check: safelist zip of matomo.js.gz  during integrity/delete check

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21907]
Users who deliver matomo.js store the zip in matomo/ directory. 

System check recommends to delete the file.

Here is a prior whitelist story, in case that makes this quicker to do: https://github.com/matomo-org/matomo/issues/11454

**Comment by sgiehl** [comment]
It is already possible to manually ignore files using DI config. To add a file in your local `config.php` add a similar code block like it's included in `global.php` already:

https://github.com/matomo-org/matomo/blob/bd86fa86bc3ab66815e08336e6339c660c065b6b/config/global.php#L126-L134
