### ISSUE TITLE
Asking for consent page does not link to our consent manager guides

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21911]
## Summary
<img width="1017" alt="image" src="https://github.com/matomo-org/matomo/assets/273120/a038c930-f082-4df9-a8f0-1689d2318249">

See above screenshot. There is a link to https://developer.matomo.org/guides/tracking-consent to learn everything about consent. But this is very technical and not usable for most people.

Instead, I suggest the link goes to https://matomo.org/guide/tracking-data/consent-managers/ and on this page we're adding a link to the Developer FAQ.

This will make it easier for people to start tracking data.

**Comment by Stan-vw** [comment]
@tsteur can you check what Matomo version you've taken this screenshot on?

When I looked at 5.0.2 and 5.0.3 on onpremise, and on cloud (which I think runs 5.0.3) I saw the following:
<img width="1502" alt="Screen Shot 2024-03-11 at 6 48 55 PM" src="https://github.com/matomo-org/matomo/assets/52564377/8a28b5e2-7eed-4a8a-b10a-25ba48d3e4cd">

**Comment by tsteur** [comment]
Thanks @Stan-vw 💯 

I don't know what version that was but I can see it now 👍
