### ISSUE TITLE
[Bug] cron:archive CLI changed response format in Matomo 5 - instead of DateTime before every row, only time is displayed

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#21924]
### What happened?

cron:archive CLI changed response format - instead of DateTime before every row, only time is displayed:
- before Matomo 5: `INFO [2024-02-01 22:27:07] 8632  INIT`
- Matomo 5: `INFO      [08:03:33] 11096  INIT`

### What should happen?

The log/response format should still include date and time. Logging/analyzing/debugging the archiver output is very hard, if you just have the time and not the date. Also, monitoring scripts that search for errors in the output files do not work anymore and would have to be changed.

### How can this be reproduced?

Setup cron archiving and output into a logfile.

### Matomo version

5

### PHP version

all

### Server operating system

all

### Computer operating system

all

### Relevant log output

```shell
- before Matomo 5: `INFO [2024-02-01 22:27:07] 8632  INIT`
- Matomo 5: `INFO      [08:03:33] 11096  INIT`
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Likely caused by the update of `symfony/console` and how it configures its formatters.

**Comment by sgiehl** [comment]
Yes. I guess Symfony changed the default. I'll quickly check if that's easy to change.
