### ISSUE TITLE
[Bug] Visitors map doesn't show the visits by country any more

### ISSUE THREAD

**Issue by paolobenve** [piwik/piwik#21943]
### What happened?

I'm using last version

In the Visitor Graph map, before I saw the various visitor countries with different colors, according to the number of visits from them, and hovering the country showed the number.

### What should happen?

The various visitor countries should have different colors, according to the number of visits from them, and hovering the country should show the number.

### How can this be reproduced?

I'm having this problem since some version ago

### Matomo version

Matomo version: 5.0.2 - MySQL version: 10.11.6-MariaDB-0+deb12u1-log

### PHP version

8.2.7

### Server operating system

debian

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

ubuntu 22.04

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

![piwik](https://github.com/matomo-org/matomo/assets/1417508/49c2fcba-ebdd-4a7e-b11b-faae532092ec)

**Comment by michalkleiner** [comment]
Hi @paolobenve, thanks for the report. Sorry to hear you have troubles viewing the visits on the visitor map. I can see in your real time visits that the country flag is not displayed and rather displays a question mark, which indicates the country couldn't be determined for the visit and therefore won't be able to be visualised in the map. Have you recently changed any config around user anonymisation, perhaps tried to update the GeoIP database and it didn't update successfully or similar? Could you check you have geolocation enabled in Settings > System > Geolocation?

**Comment by paolobenve** [comment]
> Have you recently changed any config around user anonymisation, perhaps tried to update the GeoIP database and it didn't update successfully or similar? 

I have updated the geoIP db, substituting the old file with the new. Should I do anything after that?

**Comment by Stan-vw** [comment]
Just tried to recreate this on 5.0.2 since this would be quite a major regression, but it's working alright for me:
<img width="419" alt="Screen Shot 2024-03-11 at 6 29 56 PM" src="https://github.com/matomo-org/matomo/assets/52564377/3ac006de-295f-4aa0-bcd7-bbd901bd9808">

Can you check if there's data in your Realtime Map and Locations reports?

**Comment by Stan-vw** [comment]
I'll close this for now since we haven't heard back, but feel free to reopen if this problem still persists for you.
