### ISSUE TITLE
Hourly evolution data points in Visits sparkline

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#21956]
![image](https://github.com/matomo-org/matomo/assets/22874146/46470547-6833-4490-8c63-eef32b59bbdf)

Question: What is the one thing you’d like to see improved in Matomo and why?
Answer:
hourly graphs (stündliche Charts)

**Comment by mneudert** [comment]
I'll close this as a duplicate of #9956 and #4158.

We can always reopen if there are more details to it not already captured on those two issues.
