### ISSUE TITLE
[Bug] Upgrade from 4.0.1 to 5.0.1 - Error query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '50883579070' for key 'matomo_log_link_visit_action.PRIMARY'

### ISSUE THREAD

**Issue by nnhiep** [piwik/piwik#21960]
### What happened?

Hi,

I upgraded from Matomo 4.0.1 to Matomo 5.0.1

I got 500 status, and when I checked matomo.log, I got error as below:
ERROR Piwik\Tracker\Handler[2024-02-20 10:24:19 UTC] [4a4da] Exception: /xxx/matomo/core/Tracker/Db/Pdo/Mysql.php(237): Error query: Error query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '50883579071' for key 'matomo_log_link_visit_action.PRIMARY' In query: INSERT INTO matomo_log_link_visit_action (idvisit, idsite, idvisitor, idaction_url, idaction_url_ref, idaction_name_ref, server_time, idpageview, pageview_position, time_spent_ref_action, time_dom_processing, time_network, time_server, time_transfer, idaction_name) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) Parameters: array (

ERROR BulkTracking[2024-02-20 10:24:19 UTC] [97eeb] Exception: /xxx/matomo/core/Tracker/Db/Pdo/Mysql.php(237): Error query: Error query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '50883579072' for key 'matomo_log_link_visit_action.PRIMARY' In query: INSERT INTO matomo_log_link_visit_action (idvisit, idsite, idvisitor, idaction_url, idaction_url_ref, idaction_name_ref, server_time, idpageview, time_spent_ref_action, idaction_content_name, idaction_content_piece, idaction_content_target) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) Parameters: array (

### What should happen?

Please help me to fix it.

### How can this be reproduced?

Upgrade from 4.0.1 to 5.0.1

### Matomo version

5.0.1

### PHP version

7.3.33

### Server operating system

CentOS7

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @nnhiep, sorry to hear you encounter an issue during a Matomo upgrade. Can you please confirm whether the error only appeared once and the upgrade finished or are you still experiencing it and you couldn't finish the upgrade? The log message seems like it's related to bulk tracking rather than the upgrade, are you using bulk tracking by chance with some custom setup?

**Comment by nnhiep** [comment]
Hi @michalkleiner 

During the upgrade process, no errors occurred. However, when I routed 5% of the traffic to the new system, I got 500 status in the new system (the old system did not have this issue). Therefore, I stopped the rerouting and raised the issue here.

**Comment by michalkleiner** [comment]
Thanks for the extra info @nnhiep. How do you route the tracking traffic? Do you use bulk tracking or some other method like queued tracking via redis etc.?

**Comment by nnhiep** [comment]
Hi @michalkleiner 

I route traffic on Proxy. (add new server to upstream)

**Comment by michalkleiner** [comment]
@nnhiep can you answer the other questions as well, please?

**Comment by nnhiep** [comment]
Ok @michalkleiner

**Comment by michalkleiner** [comment]
@nnhiep just reiterating the question — Do you use bulk tracking or some other method like queued tracking via redis etc.?

**Comment by nnhiep** [comment]
I am still using Redis as before the upgrade.

**Comment by michalkleiner** [comment]
Ok, so there might be scenarios where you have the visit in the database and it tries to insert it again after the upgrade perhaps. Do you turn on the maintenance mode before the upgrade?
This might be quite hard to replicate to confirm whether this could be a bug in Matomo, the index/db constraints are in place for a reason (to prevent duplicate data). Is there anything in the upgrade procedure you can try to do differently to see if you can avoid the issue?

**Comment by nnhiep** [comment]
Thanks @michalkleiner, after I flush Redis data, the 500 error was resolved.
