### ISSUE TITLE
Get latest visit details for a unique visitor.

### ISSUE THREAD

**Issue by Shailendar** [piwik/piwik#21963]
Hi Team,

Is there any way to get latest visit related data instead of all visits for one visitor using Matomo reporting API.

Our requirment is when visitor visited our website for the first time we will ask them to provide feedback about their experience with our application. For this I am using **Live.getLastVisitsDetails** method and  **segment=visitCount<2**. If response is not empty we will ask feedback. Here my expectation is if user visited our website 5times, this condition should not satisified and method will return empty data so that we will not ask any feedback. But based on matomo it captures each visit. So that when we apply **segment=visitCount<2** it still return data because it is like SQL where condition it will fetch the values based on condition. So my request is to help me to achive this scenario to get latest visit(not 1,2,3,4 visits & get 5th visit) and find the visitCount.

**Comment by bx80** [comment]
Hi @Shailendar,

You could use `visitorType==new` for the segment definition which should only return visits which do not have any previous visits.
