### ISSUE TITLE
[Bug] Archive job not working

### ISSUE THREAD

**Issue by headyj** [piwik/piwik#21975]
### What happened?

I'm trying to conifgure the archive job using the Helm chart, which seems to be the same command as the [official one](https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/) but th job is returning an error with GeoIP2:

```
INFO [2024-02-27 10:19:58] 1  SCHEDULED TASKS
INFO [2024-02-27 10:19:59] 1  Starting Scheduled tasks... 
INFO [2024-02-27 10:19:59] 1  Scheduler: executing task Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater.update...
INFO [2024-02-27 10:19:59] 1  Downloading https://download.db-ip.com/key/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb to /bitnami/matomo/tmp/latest/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb.download.
INFO [2024-02-27 10:19:59] 1  GeoIP2AutoUpdater: successfully downloaded 'https://download.db-ip.com/key/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb'
ERROR [2024-02-27 10:19:59] 1  /bitnami/matomo/plugins/GeoIp2/GeoIP2AutoUpdater.php(190): GeoIP2AutoUpdater: failed to unzip '/bitnami/matomo/tmp/latest/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb.download' after downloading 'https://download.db-ip.com/key/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb': Unable to determine what type of database this is. [Query: , CLI mode: 1]
ERROR [2024-02-27 10:19:59] 1  Scheduler: Error GeoIP2AutoUpdater: failed to unzip '/bitnami/matomo/tmp/latest/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb.download' after downloading 'https://download.db-ip.com/key/152b6c2d1366a4a0a7dcc5d9eeceaab90045c663.mmdb': Unable to determine what type of database this is. for task 'Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater.update'
INFO [2024-02-27 10:19:59] 1  Scheduler: finished. Time elapsed: 0.492s
INFO [2024-02-27 10:19:59] 1  done
INFO [2024-02-27 10:19:59] 1  ---------------------------
Error: error or warning logs detected, exit 1
```

My guess is that it has nothing to do with the chart itself, reason why I'm posting the issue here

### What should happen?

Archive job should succeed

### How can this be reproduced?

- install matomo using the helm chart
- Install and configure GeoIP2 plugin
- launch the archive job following the official documentation: https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

### Matomo version

4.16.0

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @headyj,

the issue is most likely unrelated to the chart :thinking: 

From your output it seems you have a paid DB-IP database configured. The configuration in the geolocation system settings should look like this:

- `https://db-ip.com/account/$ACCOUNT_KEY/db/ip-to-location`
- `https://db-ip.com/account/$ACCOUNT_KEY/db/ip-to-location/mmdb/url`

The individual URLs to download (`https://download.db-ip.com/key/<some token>.mmdb`) change regularly (#15580). When configuring the direct download URL it should eventually respond with `error: invalid link` instead of a file.

Can you check your configuration and, if you have access to the storage, check if the current downloads have an error string in them (or something that could point to the actual problem)?

**Comment by sgiehl** [comment]
As there hadn't been any further feedback, we assume the answer solved your problems. If you still have trouble with anything feel free to reach our on our forums at https://forum.matomo.org or create a new issue here if you want to request a new feature or report a bug. Cheers.

**Comment by headyj** [comment]
Sorry for the late answer. Indeed it seems that it was due to the database being outdated
