### ISSUE TITLE
Despite HeatmapSessionRecording.disable(), tracker calls HeatmapSessionRecording plugin

### ISSUE THREAD

**Issue by utrenkner** [piwik/piwik#21976]
### What happened?

We need to track certain pages to two different Matomo instances. I use this code to add a secondary tracker and to set CustomDimension2 for this tracker to 12345:
```
window.matomoAsyncInit = function () {
  var secondaryTrackerUrl = 'https://<mydomain>/matomo.php';
  var secondaryWebsiteId = 1;
  _paq.push([\'addTracker\', secondaryTrackerUrl, secondaryWebsiteId]);
  var tracker = Matomo.getAsyncTracker(secondaryTrackerUrl, secondaryWebsiteId);
  tracker.HeatmapSessionRecording.disable();
  tracker.setCustomDimension(2, 12345);
  tracker.trackPageView();
  tracker.enableLinkTracking();
}
var _paq = window._paq = window._paq || [];
 _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
...
```
However, the Matomo script still sends a GET-request to ``https://<mydomain>/plugins/HeatmapSessionRecording/configs.php``, which does not exist (the plugin is not installed).

I tried detecting if HeatMapSessionRecording exists, as suggested in the [Heatmap & Session Recording JavaScript Tracker API Reference](https://developer.matomo.org/guides/heatmap-session-recording/reference):
```   
if (tracker.HeatmapSessionRecording) {
 tracker.HeatmapSessionRecording.disable();
}
```
But, as expected, this makes no difference as the plugin is not installed.

### What should happen?

The call to the non-existing ``https://<mydomain>/plugins/HeatmapSessionRecording/configs.php`` should be suppressed. No HeatMapSession should be recorded.``

### How can this be reproduced?

The key parts of my configuration are given above. With it, the problem should be reproducible.

### Matomo version

5.0.2

### PHP version

8.2.14

### Server operating system

FreeBSD 14.0-RELEASE-p4

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

FreeBSD 14.0-RELEASE-p4

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by AltamashShaikh** [comment]
@utrenkner To not record any session or heatmap activity on the current page, set an empty object like below after `var tracker = Matomo.getAsyncTracker(secondaryTrackerUrl, secondaryWebsiteId);` more info can be found [here](https://developer.matomo.org/guides/heatmap-session-recording/reference#addconfig)
```
tracker.HeatmapSessionRecording.addConfig({})
```

Also this repository is for Matomo core issues and HeatmapSessionRecording is a premium plugin, please contact Matomo support for assistance.

**Comment by utrenkner** [comment]
Thank you for your answer. But the problem really is an issue in Matomo core! 

We never had the premium plugin installed. Maybe it is a leftover of the former free plugin that was shipped with every Piwik installation? You still find references to this plugin hard-coded in core, e.g. here https://github.com/matomo-org/matomo/blob/1baa4ba569f9583719cd289dfa279aeebd084d2e/plugins/Installation/ServerFilesGenerator.php#L182

Because Heatmap plugin is NOT installed on our server, most suggestions to disable recording simply do not work, including your ``tracker.HeatmapSessionRecording.addConfig({})``.

The only thing that does work is ``_paq.push([\'HeatmapSessionRecording::disable\']);`` but this disables it for all trackers (which, fortunately, is OK in our case).

I am not sure if you read this answer. If I do not here back from you, I will file a new issue clearly stating that it is a bug in Matomo core, and that the provided answer does not solve it.

**Comment by AltamashShaikh** [comment]
@utrenkner I tried the above mentioned code and found the issue `var tracker = Matomo.getAsyncTracker(secondaryTrackerUrl, secondaryWebsiteId);` is returning the initial tracker, whereas it should return this new tracker, @matomo-org/core-team Good to check this if this is a regression or not, @utrenkner you can use the below code to disable HeatmapSessionRecording for this new tracker.

```
window.matomoAsyncInit = function () {
        var secondaryTrackerUrl = 'https://altamash.matomo.cloud/matomo.php';
        var secondaryWebsiteId = 1;
        _paq.push(['addTracker', secondaryTrackerUrl, secondaryWebsiteId]);
        var tracker = Matomo.getAsyncTracker(secondaryTrackerUrl, secondaryWebsiteId); //without this getAsyncTrackers was returning an empty []
        var trackers = Matomo.getAsyncTrackers();
        for (var i=0; i < trackers.length; i++) {
            var t = trackers[i];
            if (t.getTrackerUrl() === secondaryTrackerUrl && t.getSiteId() === secondaryWebsiteId) {
                t.HeatmapSessionRecording.disable();
                t.setCustomDimension(2, 12345);
            }
        }
    }
```

**Comment by AltamashShaikh** [comment]
@utrenkner I have shared an updated working code snippet, let me know if this works or not.

**Comment by utrenkner** [comment]
@AltamashShaikh Thank you, your code snippet does work for us!

**Comment by mneudert** [comment]
From what I can tell this is not a bug, but rather unintuitive behaviour.

The problem is the order of internal actions when using both `_paq.push` and `window.matomoAsyncInit()`.

When `matomo.js` is loaded, it will call `matomoAsyncInit` before the first tracker has been created. Calling `Matomo.getAsyncTracker()` will create that first tracker, and also execute all queued `_paq` requests. This results in a tracker being created with the secondary URL, but before returning it `_paq.push(['setTrackerUrl'])` is going into effect and overwrites that URL immediately.

This is also the reason why this code works:

```
window.matomoAsyncInit = function() {
    // this will not create a new tracker instance at this point, only queue it
    _paq.push(['addTracker', secondaryTrackerUrl, secondaryWebsiteId]);

    // This call will create the first tracker with the tracker URL
    // configure using `_paq.push(['setTrackerUrl'])` and return it.
    // It will also execute `_paq.push(['addTracker'])` internally,
    // providing the instance for later access.
    var tracker = Matomo.getAsyncTracker(secondaryTrackerUrl, secondaryWebsiteId);

    // now both trackers have been created
    var trackers = Matomo.getAsyncTrackers();

    // ... loop over trackers ...
}
```

This snippet should be equivalent:

```
window.matomoAsyncInit = function() {
    _paq.push(['addTracker', secondaryTrackerUrl, secondaryWebsiteId]);

    // Initialize primary tracker with `_paq` configuration values.
    // Using `getAsyncTracker()` should be identical here.
    Matomo.addTracker();

    // Fetch the secondary tracker.
    // Previous combination of `_paq.push(['addTracker'])`
    // and `addTracker()` has created it.
    var secondaryTracker = Matomo.getAsyncTracker(secondaryTrackerUrl, secondaryWebsiteId);

    secondaryTracker.HeatmapSessionRecording.disable();
}
```

The first call to `addTracker` (or `getAsyncTracker()`) should return the tracker instance, so you can also choose to disable HSR on the first tracker while having it enabled on the secondary.
