### ISSUE TITLE
[Bug] Inconsistent use of info/help icons

### ISSUE THREAD

**Issue by pbb72** [piwik/piwik#21974]
### What happened?

The usage of info/help icons is inconsistent throughout the Matomo interface, at places even within a single page.

Take this user pemissions table: 
![image](https://github.com/matomo-org/matomo/assets/1436366/f1978a2f-e5c0-4276-916e-eb528047f5e6)

The gray question-mark icons in the header need to be clicked to open an information message.

But the blue question-mark icons in the popup menu for Tag Manager should *not* be clicked. These show their information on hover, and if you click them then you activate the corresponding menu item instead.

And to top it off, when you hover over the expand/collapse arrow icon next to the line "Tag Manager", the mouse cursor shows a question-mark icon as if there is some information to be gotten here, but nothing will show and clicking will just expand/collapse the menu.

### What should happen?

There should be consistency throughout the user interface. Identical feature should have identical interaction. Where this is not technically possible, the required change in interaction should be clearly noted. (A different color or mouse cursor is *not* clear enough.)

### How can this be reproduced?

Hover over the info/help icons in the table header and wait for a popup message to appear. Move the mouse a few pixels around, just in case the message doesn't show up because the mouse is not perfectly centered over the icon.

Wait long enough to conclude this info message apparently doesn't show up on hover. Try clicking on the icon to learn you have to click to show the message.

Then open the pop-up menu in the Capabilities column. Notice that the mouse cursor shows a question-mark icon when hovering over the arrow behind "Tag Manager". Keep hovering a while and conclude no information is showing up. Then click the arrow in assumption this also needs to be clicked to show the help. Notice that clicking still doesn't show any help and instead opens the submenu. Conclude that there either is no help here and the mouse cursor must be a bug, or that you just don't understand how to open the help for this item.

Then notice the various blue info/help icons in the opened submenu. Having gotten used to the interface now, click the icons. Now instead of a help message, a window pops up asking for confirmation that you really want to assign these capabilities to the user.

Sigh in resignation. There is just no consistency, you will have to either remember how each icon works, or try and fail a few times every time.

### Matomo version

4.13.3

### What browsers are you seeing the problem on?

Chrome

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @pbb72. Thank you for taking the time to open the issue. We are aware that some parts of the UI are not fully consistent with others, mainly due to the growing nature of the product and how/when features and functionality were added over time. Our team is aware of these and long term we are planning to improve the UI, make it more consistent and easier to use.
With Matomo 5 we also updated the icons pack, so perhaps try to update to Matomo 5.0.2, you should see a small improvement already.

**Comment by randy-innocraft** [comment]
Hi @pbb72. Once again, thank you for taking the time to open this issue. We will be tackling this as part of design system work in the future and we will work to improve help text within the product as well. Closing this ticket now as it will be tracked in design system work.

**Comment by pbb72** [comment]
@randy-innocraft Does this mean I have to report this issue again if it isn't fixed (forgotten) in the future?

**Comment by ronak-innocraft** [comment]
We've decided to address it through our design system to ensure a comprehensive and consistent solution.

Rest assured, we are tracking this internally and will work diligently to implement the necessary changes. You do not need to report this issue again. However, if you notice that it hasn't been resolved in a future release or if you encounter any new related issues, please feel free to reach out. Your feedback is invaluable, and we appreciate your patience and understanding.
