### ISSUE TITLE
[Bug] Upgrade from 5.0.0~ynh2 to 5.0.2~ynh1 not working

### ISSUE THREAD

**Issue by thomas-jardinet** [piwik/piwik#21973]
### What happened?

When I try to upgrade, I have the upgrade box appearing, but nothing else happens. Issue on a URL? No DNS liar used by the way on my network.

### What should happen?

To be upgraded obviously :)

### How can this be reproduced?

System update > Upgrade button on Matomo (matomo) from 5.0.0~ynh2 to 5.0.2~ynh1

### Matomo version

5.0.0~ynh2

### PHP version

Last on 27/02/2024

### Server operating system

DEBIAN 11 Arm64

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Windows 10

### Relevant log output

```shell
N/A
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @thomas-jardinet. Sorry to hear you are experiencing upgrade issues. I'm not sure where you'd be getting the `~ynh2` part of the version, that's not a standard Matomo version format, are you perhaps using docker image to run Matomo or some other source of it? Are there any errors in the logs or in the browser console when trying to run the upgrade?

**Comment by thomas-jardinet** [comment]
At least in my memory I have installed from the Yunohost web ui.
Haven't found any log regarding the fact it does not upgrade.
Have found this yml file about the install <anonymised>: 
args:
  app: matomo
  force: false
  label: undefined
  no_remove_on_failure: false
ended_at: 2024-01-07 15:46:36.474365
env:
  YNH_APP_ACTION: install
  YNH_APP_ARG_ADMIN: <myadmin>
  YNH_APP_ARG_DOMAIN: <matomosubdomain>
  YNH_APP_ARG_INIT_MAIN_PERMISSION: all_users
  YNH_APP_ARG_PATH: /
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_x8bhiy4w
  YNH_APP_ID: matomo
  YNH_APP_INSTANCE_NAME: matomo
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 5.0.0~ynh2
  YNH_APP_PACKAGING_FORMAT: '2.0'
  YNH_ARCH: arm64
  YNH_DEBIAN_VERSION: bullseye
error: null
interface: api
operation: app_install
parent: null
related_to:
- - app
  - matomo
started_at: 2024-01-07 15:44:51.691106
success: true
yunohost_version: 11.2.9.1

I've retried, still have the same thing : "Waiting for the server's response..."

**Comment by michalkleiner** [comment]
Ok, right. I'm sorry but we can't really help much with custom installations like your one using Yunohost as we have no visibility into how they are providing the builds or if they are changed in some way etc., so your best bet might be to try and reach out to them. With that I will close the issue for now but if it turns out to be a problem with Matomo itself please do let us know.
