### ISSUE TITLE
[Bug] Call to a member function getSeriesCount() on null

### ISSUE THREAD

**Issue by JC5** [piwik/piwik#21972]
### What happened?

Several charts are broken. When I open the image directly, I see:

 The following error just broke Matomo (v5.0.2):

```
Call to a member function getSeriesCount() on null
in /var/www/analytics/core/Visualization/Sparkline.php line 224            
```

### What should happen?

I should see a small sparkline graph

### How can this be reproduced?

I see this in several dashboard modules, one is "Visits overview"

### Matomo version

5.0.2

### PHP version

8.3.3

### Server operating system

Linux

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

MacOS

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @JC5,

Given the error I assume your PHP installation is missing the `gd` extension. Could you look into your system check (Adminstration -> Diagnostic -> System Check) what it says in the `GD > 2.x + FreeType (graphics)` row?

**Comment by JC5** [comment]
Indeed, that was the issue.

I moved servers a few weeks ago. I never noticed. Thanks!
