### ISSUE TITLE
[Bug] 我尝试在堡塔面板安装matomo，但是进入网站后每次都卡在超级用户这一栏目，如果刷新就会提示该账户已存在，如果不管过一会自动就跳转502，请问这是什么情况？是我没有HTTPS的原因吗？

### ISSUE THREAD

**Issue by willow-god** [piwik/piwik#21986]
### What happened?

在安装过程中，没有成功安装，卡在超级用户一步骤

### What should happen?

无法实现安装

### How can this be reproduced?

随时复制

### Matomo version

latest

### PHP version

7.4.33

### Server operating system

Ubuntu 18.04

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

windows

### Relevant log output

```shell
502 Bad Gateway
nginx
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @willow-god, apologies, but we cannot accept issues in other languages than in English. For that reason I will close this issue, but feel free to open a new one in English if you have a replicable bug related to Matomo itself. Seeing the 502 code it looks like a webserver or proxy configuration issue at your end. Thank you for your understanding.
