### ISSUE TITLE
Location Matomo

### ISSUE THREAD

**Issue by Farahmb2** [piwik/piwik#21983]
Hello,
I have a Matomo account for my website. On this account, it is indicated that a large part of visitors come from the French region Ile de France. However, my Ads campaigns only target the Rhone-Alpes region. Can you tell me if the location of Matomo is correct? How do you locate visitors?
Thanking you
Have a good day
![Capture](https://github.com/matomo-org/matomo/assets/161807258/d640fc3e-2bbe-4a6b-afc4-e0eac3752200)

**Comment by sgiehl** [comment]
Visitors are located using geo ip databases/services like maxmind. For more details you can have a look at https://matomo.org/faq/new-to-piwik/faq_168/
If you are using our cloud service, this should already be set up correctly.
