### ISSUE TITLE
[Bug] Can't be deployed on the server, and each deployment gets stuck in the Create Superuser section

### ISSUE THREAD

**Issue by willow-god** [piwik/piwik#21987]
### What happened?

Dear developers, I'm sorry to bother you, I have a problem deploying the matomo page on my own server, I can't create a superuser, every time I click create, it keeps stuttering, as follows:
<img width="209" alt="image" src="https://github.com/matomo-org/matomo/assets/93815242/bdfd2765-5843-4ed1-a88b-86e370edad80">
If I wait, he'll be redirected to page 502:
<img width="634" alt="image" src="https://github.com/matomo-org/matomo/assets/93815242/17d82c52-8b41-4a9d-91e8-43e3d417ecf4">

And if I repeatedly click create or refresh when 502, he will say that it cannot be created successfully, because the account has already been duplicated, and then I try to change the username and email address to continue the registration, and he will also get stuck in the above situation
<img width="483" alt="image" src="https://github.com/matomo-org/matomo/assets/93815242/4e7327a3-737b-453b-a184-24f3f0f191ea">
I don't know how to deal with it, I think there are two warnings in the first step of the environment check, but I don't know how to fix it and I don't know if it's related to the problem
<img width="717" alt="image" src="https://github.com/matomo-org/matomo/assets/93815242/90123bc9-9a30-4797-a22c-240ee8ed0e85">
<img width="732" alt="image" src="https://github.com/matomo-org/matomo/assets/93815242/9cae507d-99b5-4043-811c-87c88749c970">

I hope the developers can solve my doubts and have a happy life!

### What should happen?

This issue prevented me from creating an account and not being able to use the features properly

### How can this be reproduced?

This issue occurs every time an account is created in My Server

### Matomo version

5.0.2

### PHP version

7.4.33

### Server operating system

Ubuntu 20.04

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer operating system

windows 11

### Relevant log output

```shell
<details>
<summary>Click to view System Check</summary>

### Mandatory checks

#### PHP 版本 >= 7.2.5:
 ✔ 7.4.33

#### PDO 扩展:
 ✔ 

#### PDO\MYSQL 扩展:
 ✔ 

#### MYSQLI 扩展:
 ✔ 

#### 其他必须的扩展:
 ✔ zlib ✔ json ✔ filter ✔ hash ✔ session

#### 必需的功能:
 ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

#### 必要的 PHP 配置（php.ini）:
 ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR = -1 OR >= 30

#### 具有写入权限的文件夹:
 ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c


### Optional checks

#### 文件完整性:
 ✔ 

#### 64 位 PHP 二进制文件:
 ✔ 

#### 追踪器状态:
 ✔ 

#### 内存限制:
 ✔ 128M

#### 时区:
 ✔ 

#### 打开网址:
 ✔ curl

#### PageSpeed 已关闭:
 ✔ 

#### GD > 2.x + Freetype（图形功能）:
 ✔ 

#### 其它扩展:
 ✔ json ✔ libxml ✔ dom ✔ SimpleXML ✔ openssl

#### 其它功能:
 ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

#### 文件系统:
 ✔ 

#### 设置 Cron - 通过 CLI 管理进程:
 ✔ OK

#### 通过 HTTPS 更新:
 ✔ 

#### 可写的JavaScript追踪器（"/matomo.js"）:
 ✔ 


### Informational results

#### Matomo Version:
 5.0.2

#### PHP_OS:
 Linux

#### PHP SAPI:
 ⚠ Warning: fpm-fcgi<br><br>PHP FPM will ignore .htaccess rules for .php files. To ensure that sensitive files cannot be accessed directly it is recommended to exclude certain directories from being handled by PHP FPM. For more information please see the  official nginx server configuration 

#### PHP Timezone:
 UTC

#### PHP Time:
 1709540750

#### PHP Datetime:
 2024-03-04 08:25:50

#### PHP Disabled functions:
 passthru, exec, system, putenv, chroot, chgrp, chown, popen, proc_open, pcntl_exec, ini_alter, ini_restore, dl, openlog, syslog, readlink, symlink, popepassthru, pcntl_alarm, pcntl_fork, pcntl_waitpid, pcntl_wait, pcntl_wifexited, pcntl_wifstopped, pcntl_wifsignaled, pcntl_wifcontinued, pcntl_wexitstatus, pcntl_wtermsig, pcntl_wstopsig, pcntl_signal, pcntl_signal_dispatch, pcntl_get_last_error, pcntl_strerror, pcntl_sigprocmask, pcntl_sigwaitinfo, pcntl_sigtimedwait, pcntl_exec, pcntl_getpriority, pcntl_setpriority, imap_open, apache_setenv

#### PHP INI max_execution_time:
 300

#### PHP INI post_max_size:
 50M

#### PHP INI max_input_vars:
 1000

#### PHP INI zlib.output_compression:
 

#### Curl Version:
 7.70.0, OpenSSL/1.0.2u

#### Suhosin Installed:
 0

#### Server Info:
 ⚠ Warning: nginx/1.24.0<br><br>To ensure that sensitive files cannot be accessed directly it is recommended to configure your web server to restrict access to certain directories. For more information please see the  official nginx server configuration 

#### User Agent:
 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

#### Browser Language:
 zh-cn,zh

</details>
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @willow-god, thank you for creating the issue in English.
As mentioned in the previous issue with the 502 gateway error, it's most likely a server configuration issue. I see you only have 128MB of PHP memory. It's likely the PHP server runs out of memory and that then surfaces as this gateway error. Please try increasing the available memory to 256 or better 512MB. There are other sizing guides on the https://matomo.org/faq/on-premise/matomo-requirements/ FAQ page. This doesn't seem like a Matomo code issue so with that I will close the issue and kindly ask you to seek help in the [Matomo forum](https://forum.matomo.org/) if your problem persists as we can't assist with custom server configuration issues through the issue tracker here. Thank you for your understanding.
