### ISSUE TITLE
[Bug] Incorrect display of set_time_limit in the system check

### ISSUE THREAD

**Issue by electricarts** [piwik/piwik#21990]
### What happened?

An incorrect set_time_limit value is indicated in the system check. The max_execution_time value should be increased. No matter what I enter for this value, the message remains. An entry of "360" for a Matomo installation of 6 "low performing" websites should be enough, right? Even a change to "1000" does not change anything. Calling up the server PHP info shows that the value is set correctly via php.ini. What else can I do?

<img width="1292" alt="Screenshot 2024-02-28 at 12 34 21" src="https://github.com/matomo-org/matomo/assets/625286/df25c78f-517f-4651-b1dd-f6950bfc806b">

<img width="1116" alt="Screenshot 2024-02-28 at 12 29 43" src="https://github.com/matomo-org/matomo/assets/625286/b8ca111f-bc79-4cec-bec5-a0a1c90a5227">

### What should happen?

Is this "just" a display error? Are there any interactions with other server or Matomo settings?

### How can this be reproduced?

Administration -> System Check

### Matomo version

5.0.2

### PHP version

8.1.27

### Server operating system

LightSpeed

### What browsers are you seeing the problem on?

Chrome, Safari, Other

### Computer operating system

macOS Sonoma 14.3.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @electricarts,

This is most likely a result of a system configuration disabling the `set_time_limit` function.

The warning tries to give you the hint that, if you experience timeouts while using Matomo, you could try to raise the `max_execution_time`. No check is done that this value is high enough, as that heavily depends on the individual environment (general server load, concurrent archiving processes, number of visits, ...).

If a warning is displayed you should find an entry in the `Core` section of your PHP info under `disable_functions`. Could you look there if `set_time_limit` is disabled?

**Comment by electricarts** [comment]
@mneudert Oh God. Sorry, I didn't check that myself! I had written to the server support about it, but they had no idea why the hint came. Enabled it (was disabled) and it works like a charm now. 

Thanks for the help!

**Comment by mneudert** [comment]
Nice to hear that :+1:
