### ISSUE TITLE
Loss of data history for a custom dimension

### ISSUE THREAD

**Issue by HabibEquzz** [piwik/piwik#21991]
While navigating the Matomo standard dashboard, I've encountered an issue with data extraction from my custom dimension third_party_name which is Custom dimension 4. Specifically, when I attempt to retrieve data spanning from January 1st, 2023 to March 31st, 2024, I notice a discrepancy. Many of the values I expect to find are absent compared to a previous extraction covering January 1st to December 31st, 2023. This inconsistency raises concerns about data integrity and completeness, hindering my ability to derive accurate insights. Seeking resolution to ensure the reliability of our analytics
FYI, here is the account : //analytics.heppner-group.com
Thanks.

**Comment by michalkleiner** [comment]
Hi @HabibEquzz, please contact the support team via https://matomo.org/support/ if you're a support plan customer or if you're using Matomo cloud. This issue tracker is used to report replicable bugs in Matomo or suggest enhancements and new features. Thank you for your understanding.
