### ISSUE TITLE
[Bug] Call to a member function getSeriesCount() on null

### ISSUE THREAD

**Issue by Boitso** [piwik/piwik#22001]
### What happened?

When I want to check the statistics of my website campaigns, I get this message :
![image](https://github.com/matomo-org/matomo/assets/90326673/812a588f-0dae-43d7-b728-9e6be74d836e)

### What should happen?

There should be a graph.

### How can this be reproduced?

In Acquisition, then Campaigns.

### Matomo version

5.0.2

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by mneudert** [comment]
Hi @Boitso,

the exception will get fixed, but you will probably still see broken images for the sparklines.

Could you look into your system check (Adminstration -> Diagnostic -> System Check) what it says in the GD > 2.x + FreeType (graphics) row? I expect the required `gd` extension to be missing.
