### ISSUE TITLE
[Bug] UsersManager: can't disallow example.org as email domain

### ISSUE THREAD

**Issue by janv8000** [piwik/piwik#22009]
### What happened?

Presence of the anonymous@example.org users forces the UsersManager to allow `example.org` as valid domain.

User anonymous can't be deleted:
![image](https://github.com/matomo-org/matomo/assets/1412705/85ae8172-b632-42f1-a9d6-4dc2eb558556)

Email domain `example.org` can't be deleted:
![d717cda291fb83bb0955e6e353f1212fec8a8eb0_2_1035x481](https://github.com/matomo-org/matomo/assets/1412705/675c8f24-f4f9-43c8-9962-2d7a8db6ec42)
![ae1faacef437f82a1ea55c0f383bc243ca5876f8_2_1035x133](https://github.com/matomo-org/matomo/assets/1412705/15d04bf5-a294-44dc-a7af-63cf21ee3d78)

* UsersManager feature introduced in #20101
* Discussed in https://forum.matomo.org/t/what-is-user-anonymous-example-org-after-install-can-be-deleted/48791/6

### What should happen?

Presence of anonymous users should not prevent deleting/excluding example.org as valid domain

### How can this be reproduced?

* Goto index.php?module=CoreAdminHome&action=generalSettings&idSite=1&period=range&date=last7
* scroll to UsersManager
* try to limit the list to not include example.org

### Matomo version

5.0

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/what-is-user-anonymous-example-org-after-install-can-be-deleted/48791/10

**Comment by bx80** [comment]
Thanks for reporting this @janv8000, it looks like the example.org domain should be ignored by that check (assuming there aren't any other non-anonymous users for example.org)
