### ISSUE TITLE
Segment-Creation with "Please specify a value for 'definition'." error

### ISSUE THREAD

**Issue by utrautmann** [piwik/piwik#22028]
### What happened?

When I want to create a segment and I try to save, an error window appears saying "Please specify a value for 'definition'."
Everything is set up correctly, but I can't save the segment.

![I9hsyAFl5X](https://github.com/matomo-org/matomo/assets/25771066/6cd12eb8-f48c-4ef7-b00d-f725758090a7)

### What should happen?

The segment definition should be saved

### How can this be reproduced?

It could be that the error always occurs if you first used the Test button before saving.

1. Add new segment
2. Choose any values
3. Press Test
4. Show Visit log and leave visit log with Escape
5. Press Save

### Matomo version

5.0.3

### PHP version

8.x

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @utrautmann, thanks for reporting the issue. Would it be possible for you to do a short screen recording of the whole process from when you start creating the segment up to when the issue occurs while having the UI in English? That way it would be easier for most of us to see what's going on. Appreciate that!

**Comment by utrautmann** [comment]
Hi @michalkleiner ,

here another screencast to reproduce:
![Animation](https://github.com/matomo-org/matomo/assets/25771066/2154b038-8fe2-4907-a335-84155c1a2b61)

**Comment by mneudert** [comment]
Hi @utrautmann, thank you for those great reproduction videos. I was able to reproduce it with 5.x.

It seems to only break if the close icon is used, or the escape key is pressed. A click on the grey backdrop outside the overlay seems to never break the segment editor. 4.x also seems not to be affected by this.
