### ISSUE TITLE
[Bug] Password field is set to auto-complete

### ISSUE THREAD

**Issue by fmaruna** [piwik/piwik#22020]
### What happened?

A network scan discovered that the login password field has autocomplete on. Probably not a huge deal with modern browsers, but it'd be nice if it was off. 

### What should happen?

Turn that off. 

### How can this be reproduced?

Check out your login form. 
Its not that way on your password reset form. 

### Matomo version

Latest.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
Hi @fmaruna, thanks for highlighting this. :+1:
I've created a quick PR to turn off autocomplete on this password field

**Comment by fmaruna** [comment]
outstanding, thanks so much for the prompt turn around. You're making our CISO's life easier!
