### ISSUE TITLE
[Bug] Download personal email report with date range

### ISSUE THREAD

**Issue by jk-swe** [piwik/piwik#22027]
### What happened?

Receiving an error message trying to download a personal email report with a date range:
Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): '2024-03-01,2024-03-18'

### What should happen?

The download should work like in version 4

### How can this be reproduced?

Create a personal email report
Select a date range
Try to download the report

### Matomo version

5.0.3

### PHP version

8.1.27

### Server operating system

Linux

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Windows

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @jk-swe, thanks for raising the issue.
Can I confirm one thing please — you checked the checkbox stating you checked there isn't already an issue for the same bug, could I ask what did you try to search for when checking this? There is https://github.com/matomo-org/matomo/issues/21945 so I was curious what keywords you used to search for, and whether we can put some more context/keywords into existing issues so they're easier to find before raising new ones? Thank you!

**Comment by jk-swe** [comment]
Sorry, I didn't search within Github. I searched only with google without findig information about this issue.
I will search within Github first in the future.
