### ISSUE TITLE
[Bug] Custom Report Preview 'show total rows'

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#22037]
### What happened?

When previewing a Custom Report, the option to 'show total rows' doesn't seem to work. 

This works fine for custom reports that are already created, the problem is only when previewing a custom report before saving.
![image](https://github.com/matomo-org/matomo/assets/118518962/1a27f719-3d3d-46ea-bb19-360e5dc60396)

Selecting the option shows 'Loading data...' but no totals are shown.
![image](https://github.com/matomo-org/matomo/assets/118518962/b0f0e2d6-d843-410a-a6da-17cf3d96210a)

### What should happen?

The total from the displayed rows should be shown when selected.

### How can this be reproduced?

Attempt to create Custom Report and view the report from the "Preview Report" button.
![image](https://github.com/matomo-org/matomo/assets/118518962/672fe356-3ad7-48d8-9b14-db341fa98802)

Custom Reports > Manage Reports > Create New Report > select any dimension/metric > Preview Report.

Tested on both Matomo Cloud and On-Premise.

### Matomo version

5.0.3

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @goochj03, thanks for the report. Is this related to a premium plugin feature or Matomo core?

**Comment by goochj03** [comment]
This would be in regards to the Custom Reports plugin.

**Comment by michalkleiner** [comment]
@goochj03 please raise any issues relating to premium plugins internally in the plugin's team Jira, thank you.
