### ISSUE TITLE
[Bug] Segment creation is taking the previous segment configuration

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22045]
### What happened?

When you create a new segment, it is taking the configuration of the previous segment created.

https://github.com/matomo-org/matomo/assets/28002238/45063995-1790-4397-b3c3-2e5d6705b299

### What should happen?

When you create a new segment, it shouldn't take the configuration of the previous one created.

### How can this be reproduced?

By creating two segments, one after the other.

### Matomo version

5 Cloud

### What browsers are you seeing the problem on?

Firefox

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @Chardonneaur,

I was able to reproduce that one and will check if it's easy to fix.
