### ISSUE TITLE
[Bug] Does not support SMTP without authentication

### ISSUE THREAD

**Issue by TonyBogdanov** [piwik/piwik#22063]
### What happened?

Trying to connect to an SMTP server that does not support authentication fails regardless of the settings.

### What should happen?

It should be possible to connect to an SMTP server, which has no authentication set up, when no username / password is configured.

### How can this be reproduced?

To reproduce simply configure an SMTP serrver, which doesn't support authentication, under System / General settings / Email server settings.

I suspect the issue comes from this line: https://github.com/matomo-org/matomo/blob/1765f5f6077535c38d6f7a5e1f11148c7944a16e/core/Mail/Transport.php#L135 which **forces** authentication regardless if one is needed or not.

### Matomo version

5.0.3

### PHP version

8.2.17

### Server operating system

Alpine Linux

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @TonyBogdanov,

What exactly have you configured as `type` in your config file? If it is empty, no authentication should be used.

**Comment by TonyBogdanov** [comment]
Hi @sgiehl, I don't know how I missed that, but you're absolutely right. Setting the type variable to an empty string disabled authentication attempts. Thanks!
