### ISSUE TITLE
Log Importer Status

### ISSUE THREAD

**Issue by slalabs** [piwik/piwik#22064]
Using the log importer, it should be straightforward to read the HTTP status, as the special Nginx log format also captures the status. One should be able to filter by this in Matomo.

'{"ip": "$remote_addr",'
'"host": "$host",'
'"path": "$request_uri",'
**'"status": "$status",'**

## Summary
With this data, it should be easy to create a segment for 404 and 301. Status contains 301 or 404. With that, it's easier to fix errors.

## Your Environment
* Matomo Version:5.0.3
* PHP Version:8.2
* Server Operating System:Debian 12
* Additionally installed plugins: Provider

**Comment by sgiehl** [comment]
This should already be possible / be the case.
By default the log importer might ignore such requests at all. There are parameters that will enable to e.g. log redirect requests.
Status codes may then be tracked in a custom variable with name `HTTP-code`.
