### ISSUE TITLE
Matomo 4.14.1 Request data prompt:Allowed memory size of 268435456 bytes exhausted (tried to allocate 266240 bytes)

### ISSUE THREAD

**Issue by 786659214** [piwik/piwik#22062]
hello，I encountered some issues while using Matomo deployed through Docker。
The problem is as follows:
{
    "result": "error",
    "message": "Allowed memory size of 268435456 bytes exhausted (tried to allocate 266240 bytes)"
}

I am trying to expand the memory size of PHP through Docker，But even if the configuration file is modified, it will still prompt this error。

May I ask how to solve such a problem，thanks！

**Comment by sgiehl** [comment]
Hi @786659214 
This is most likely a "server" configuration issue and is unrelated to Matomo itself.
You may need to extend the allowed memory size. Depending on how much data you are tracking more memory might be needed.
For further issues around server configuration please try to find help on our forums (at https://forum.matomo.org), as we cannot answer such requests in detail here.
