### ISSUE TITLE
Option to record device resolution onExistingVisit

### ISSUE THREAD

**Issue by seb303** [piwik/piwik#22079]
Currently the Resolution plugin records the device resolution (screen css pixel size) on the first page impression of a new visit, and then after this any subsequent values are ignored.

There are however situations where the first tracking event doesn't know the resolution. For example where there is a server-side tracking event sent before the first page is rendered client-side, or when tracking is done solely server side via the API (not using the Matomo Javascript). In this case the device resolution will never get set since the initial "unknown" value persists.

My suggestions is either:

(1) Have a user option for the Resolution plugin to update the value on subsequent page impressions of an existing visit.

or

(2) If the resolution happens to be "unknown" and then a specific value is set for a page impression, then the specific value should replace the "unknown" value.

We have simulated this behaviour by adding this function to `plugins/Resolution/Columns/Resolution.php`
```
    public function onExistingVisit(Request $request, Visitor $visitor, $action)
    {
        // Also update value for subsequent tracking events in visit
        return $this->onNewVisit($request, $visitor, $action);
    }
```
But for backwards compatibility it should be switchable by an option.

**Comment by sgiehl** [comment]
Hey seb303,

thanks for raising this issue. I think it would indeed make sense to at least update the resolution when previously a unknown value was stored. This should improve overall tracking accurancy.

I'll pass this on to our product management for priorisation. 
If you are in need of this soon, feel free to create a pull request yourself and we will try to review it as soon as possilbe.
To check for an unknown value something like this might work:
```php
if ($visitor->getVisitorColumn($this->columnName) === \Piwik\Tracker\Request::UNKNOWN_RESOLUTION) {
    return $this->onNewVisit($request, $visitor, $action);
}
```

**Comment by seb303** [comment]
Thanks @sgiehl for the pointer :)
I'd be keen to get it integrated with the core as soon as possible, as we use it via cPanel/Installatron and this will likely overwrite our manual changes on the next update.

Here's a PR (tested and working fine):
https://github.com/matomo-org/matomo/pull/22080
