### ISSUE TITLE
[Bug] Transmission failed unexpectedly.

### ISSUE THREAD

**Issue by dtruong21** [piwik/piwik#22094]
### What happened?

Matomo can't link our dashboard. 
Unable to resolve host "matomo.*******.com": No address associated with hostname
failed to connect to matomo.********.com/***.***.**.** (port 443) from /***.**.**.* (port 54634) after 5000ms

### What should happen?

The connection should be fine after integration.

### How can this be reproduced?

Just open my app with Matomo integrated can directly the issue

### Matomo version

4.1.4

### What browsers are you seeing the problem on?

Other

### Computer operating system

Android

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @dtruong21 
It looks like problems with DNS, network or similar. If you are a cloud customer, please contact our cloud support directly for help.
If you are using a self hosted version of Matomo please contact your system administrator.
