### ISSUE TITLE
[Bug] Data received from Matomo is outside the range of dates provided

### ISSUE THREAD

**Issue by YashRunwal** [piwik/piwik#22107]
### What happened?

The data retrieved from Matomo using requests library is outside the start_date and end_date provided. 

For example:

if  - 

start date is 2024-04-11 00:00:00
end date is datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

Then the data received if even beforethe start date. This is not desired. 

Why does it keep happening?

### What should happen?

I expect to receive the data between start_date and end_date and if there is no more data between dates, I should get an empty response. 

### How can this be reproduced?

```
import requests
import datetime
from requests import Response

    def construct_matomo_visit_details(website_id, matomo_api_token, start_date: str, end_date: str,
                                       filter_limit: int, filter_offset: int) -> Dict:
        visit_details_params = {
            'module': 'API',
            'method': 'Live.getLastVisitsDetails',
            'idSite': website_id,
            'format': 'json',
            'date': f'{start_date},{end_date}',
            'token_auth': matomo_api_token,
            'filter_limit': filter_limit,
            'filter_offset': filter_offset,
        }
        return visit_details_params
        
if __name__ == '__main__':
     filter_limit, filter_offset = 3000, 0
     start_date = '2024-04-11'
     end_date = datetime.datetime.now().strftime("%Y-%m-%d")
     while True:
          params = construct_matomo_visit_details(website_id, matomo_api_token, start_date, end_date, filter_limit, filter_offset)
         response = requests.get(matomo_api_url, params=params)
         filter_offset += filter_limit
         if not response.json():
            break        
```

### Matomo version

NA

### What browsers are you seeing the problem on?

Firefox, Chrome, Not applicable (e.g. an API call etc.)

### Computer operating system

Windows

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@YashRunwal This might be a timezone issue. The data stored in Matomo is converted to UTC. So if your website is configured for another timezone, the data returned might show you an UTC datetime, which would be within the provided dates within the websites timezone.

**Comment by YashRunwal** [comment]
@sgiehl My local time is just 2 hours ahead of UTC Timezone. The problem persists because I also get the data for '2024-04-09', '2024-04-08', and so on even though the start_date is '2024-04-11'. Even after taking the timezone into consideration, the data received from matomo still falls outside the range of dates.

**Comment by michalkleiner** [comment]
@YashRunwal is it working correctly when you access Matomo in browser or try to compose the API request e.g. using Postman? My guess would be that the request or the query params are not formatted properly and the date range condition is not applied at all. We can't really provide support for custom coding or using external queries, so please do let us know if the issue is also observable in browser. Alternatively please paste here the resulting API request that your script/application produces.

**Comment by YashRunwal** [comment]
@michalkleiner I fixed the error by using mintimestamp and completely omitting start and end date usage. Also to answer your question, I cannot test that personally. I am going to close the story here and if anyone wants help with it, feel free to tag me here.
