### ISSUE TITLE
piwik.js: Cross domain tracking

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#2211]
(ticket description updated by @mattab) 

The goal of this ticket is to be able to measure a unique user across several domain names, by having Piwik.js automatically forwarding the User ID for this user in the URL as a query parameter. 
### Details

First party cookie by design will be only created and available in this domain where they were created. To allow for accurate cross-domains reporting, we need a way to persist the UUID (unique identifier) in the first party cookie from one domain to another domain. 

The solution is to implement a mechanism that automatically decorates DOM elements within the page, which are links, and will add a GET Parameter to links, with the User ID.

Note: this feature has been available in Google universal analytics forever, and is well documented here: [Universal analytics cross domain tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain). (this is a must read!)

Maybe in Piwik we can support the following methods:
- 'Decorate Utility Method'
- 'Decorating HTML Links'
- 'Cross Domain Auto Linking'
- Linker parameters are only valid for 2 minutes after they are created. Avoids user being assigned to wrong user id when sharing URLs with others.
### Notes
- we probably should implement User ID #3490 first
- tracking unique users across websites will only accurately track users that clicked from one website to another. If user visits both websites independently, he will be assigned two different User IDs.
- Will not be done in MVP: 
  - Tracking Across iFrames
  - Decorating HTML Forms

**Comment by cemdev** [comment]
+100

**Comment by mattab** [comment]
PR: #11243

**Comment by mattab** [comment]
Cross domain tracking is available in Piwik 3.0.2-b1 release.

To use it configure it as follows in the Piwik Tracker code:

```js
_paq.push(['setDomains', ['domain-1.net', 'domain-2.net']]);
_paq.push(['enableCrossDomainLinking']);
_paq.push(['setSiteId', X]);

```

(when adding both these lines in domain-1.net and domain-2.net -> users clicking from either website to the other website, will be automatically recognised as the same visitor and tracked in the same visit in website id X)

**Comment by mattab** [comment]
Before closing the issue:

* Document cross domain feature in the [JavaScript tracking guide](http://developer.piwik.org/guides/tracking-javascript-guide)
* Add new FAQ
* Create a separate issue for `backend improvement: ensure that Visitor ID is the same across all visits of a given visitor and re-uses the last visitor id value set` or similar

**Comment by tsteur** [comment]
> when adding both these lines in domain-1.net and domain-2.net

We need to clearly mention it needs to be enabled on all domains / websites

> backend improvement: ensure that Visitor ID is the same across all visits of a given visitor and re-uses the last visitor id value set

We should do it actually as part of this issue, it is in most cases not working without it.

**Comment by mattab** [comment]
Note: Cross Domain feature is also useful when the data is tracked into different websites in Piwik. In that case, there won't be just "one visit" created, but "one visit per website". The advantage of using cross domains is that those two visits across website IDs will have the same Visitor ID. Could be super useful and we need to mention it in docs :+1:

**Comment by mattab** [comment]
Important:

* Need to add a new checkbox in JavaScript Tracker Code screen, to let users enable cross domain tracking which will 1) enable the `setDomains` existing checkbox automatically and 2) output in the code the `_paq.push(['enableCrossDomainLinking']);`

**Comment by mattab** [comment]
* Created new FAQ: [How do I accurately measure a same visitor across multiple domain names (cross domain linking)?](https://piwik.org/faq/how-to/faq_23654/)
* Added link into related faqs https://piwik.org/faq/new-to-piwik/faq_104/ and into [manage websites](https://piwik.org/docs/manage-websites/) user guide
* and developer guide https://github.com/piwik/developer-documentation/pull/175/files for [JS Tracker code guide](http://developer.piwik.org/guides/tracking-javascript-guide)
