### ISSUE TITLE
[Bug] Container Stops after some time with message "caught SIGWINCH, shutting down gracefully"

### ISSUE THREAD

**Issue by rajatraj733** [piwik/piwik#22112]
### What happened?

We have setup matomo using docker. The container is running fine until at some point we get the message: "caught SIGWINCH, shutting down gracefully"
This message is coming from apache. 
SIGWINCH is usually the signal sent by Terminal when the window resizes. 

### What should happen?

Ideally, The container should keep running. Not sure why apache is receiving singal SIGWINCH.

### How can this be reproduced?

It should be reproduced by simply running matomo container in deattached mode in docker.

### Matomo version

5.0.3

### Server operating system

ubuntu amd64

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @rajatraj733,

the issues seems unrelated to the Matomo software itself. We can't provide any system specific troubleshooting here on GitHub.
If you think that is an issue related to our docker container, try to create an issue here: https://github.com/matomo-org/docker
If you are using a custom docker image for that, maybe try to find some help on our forums at https://forum.matomo.org
Cheers,
