### ISSUE TITLE
Real time visit log updated when using HeartBeatTimer

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22127]
Hi team,

When the HeartBeatTimer feature is on, I guess, the expected behaviour should be to have a real time visit log which get updated at every push, it is currently not the case:
![Screenshot from 2024-04-15 16-23-14](https://github.com/matomo-org/matomo/assets/28002238/1b1e0aec-8f66-478b-a4aa-ccf9c2fa3910)

**Comment by sgiehl** [comment]
No, actually not really. The HeatBeatTimer feature might meanwhile have a bit of a misleading naming. It does no longer send periodic requests. It only sends a request when the user focus, blurs or leaves the tab/page. Also those ping requests will only update the visit end time, so the time displayed in brackets there might change then.
