### ISSUE TITLE
[Bug]  Discrepancy in Matomo Statistics for Confluence Pages

### ISSUE THREAD

**Issue by DnyanrajM** [piwik/piwik#22130]
### What happened?

Below is an observation regarding the Matomo statistics for our Confluence pages.

Upon reviewing the data, we have noticed that some pages are displaying a significantly high average load time in Matomo. However, when accessing these pages manually, it appears that the actual load time does not align with the figures reported in Matomo. The disparity between the average load time shown in Matomo and the actual time experienced is quite substantial.

### What should happen?

Average load time in matomo should match to actual load time 

### How can this be reproduced?

Click on application name -> Behaviour -> Performance -> Average load time

### Matomo version

4.14.1

### PHP version

7.4.21

### Server operating system

Linux

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@DnyanrajM Matomo is only tracking the values the browser provides.
One possible reason for this could be that some very high values were tracked, pushing the average up.
The next Matomo release will include a feature to cap such values. See https://github.com/matomo-org/matomo/issues/17847 for details around that.
