### ISSUE TITLE
[Bug] Segments: Filtering by country results in inconsistent data

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#22142]
### What happened?

We have a self-hosted instance of Matomo 5.0.3 running on our servers and are running into an issue when filtering Matomo statistics by user country. 

**We created a segment that should exclude data for visitors in Luxembourg:**
<img width="955" alt="Bildschirmfoto 2024-04-22 um 12 09 08" src="https://github.com/matomo-org/matomo/assets/118112813/c7176b21-0e41-458a-9d35-57e4a90bad78">

**Data from Luxembourg is also successfully excluded, however we also lose a bunch of data points from other countries.**
**This is the visitor location overview without any custom segments (all visits):**

<img width="1920" alt="Bildschirmfoto 2024-04-22 um 12 05 36 1" src="https://github.com/matomo-org/matomo/assets/118112813/dddc1daa-5ecb-4743-aa34-2576fc7dab32">

**This is the visitor location overview with the above segment enabled (Country is not Luxembourg):**

<img width="1920" alt="Bildschirmfoto 2024-04-22 um 12 08 13" src="https://github.com/matomo-org/matomo/assets/118112813/96491d82-d84f-4630-8beb-f4922e86e264">

You can see that visits drop dramatically for all countries, even though the segment should only touch data from Luxembourg.
Are we using it wrong? Is there any indication why this behaviour could happen?

### What should happen?

Excluding data from one country (e.g. Luxembourg) should not change data points from other countries, just remove the data points from the specified country.

### How can this be reproduced?

Click on Visitors > Click on Locations > Enable Country excluding Segment > Compare statistics

<img width="1920" alt="Bildschirmfoto 2024-04-22 um 12 41 32" src="https://github.com/matomo-org/matomo/assets/118112813/13cd6f20-ce6b-440e-9e5a-20e903faf2ac">

### Matomo version

5.0.3

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @itslewin 
Thanks for creating this issue. The number should indeed not differ in that case.
Did you maybe check if the numbers are also incorrect when looking through all months of that year?
Just wondering if that is a problem in general or if some data was maybe not correctly archived for this segment.

**Comment by ghost** [comment]
> Hi @itslewin Thanks for creating this issue. The number should indeed not differ in that case. Did you maybe check if the numbers are also incorrect when looking through all months of that year? Just wondering if that is a problem in general or if some data was maybe not correctly archived for this segment.

We indeed seem to have a problem in the months from May to September, where the segment filters all visitor data for some reason. April and October are only slightly incorrect. For the first and last few month the data is correct.

<img width="836" alt="Bildschirmfoto 2024-04-23 um 17 01 00" src="https://github.com/matomo-org/matomo/assets/118112813/fe0f81f6-7d01-44a5-9bee-4599c71ee10d">

**Comment by sgiehl** [comment]
I can imagine various reasons why that can be that case. 
- Are you maybe using the feature to automatically remove old raw data? 
- Was the segment maybe created recently and Matomo is configured to only process segments for certain time in the past (`process_new_segments_from` config flag)?

**Comment by ghost** [comment]
> I can imagine various reasons why that can be that case.
> 
> * Are you maybe using the feature to automatically remove old raw data?
> * Was the segment maybe created recently and Matomo is configured to only process segments for certain time in the past (`process_new_segments_from` config flag)?

Thank you, indeed our setup was the issue. Sorry to bother you!
