### ISSUE TITLE
how to track network status ? 

### ISSUE THREAD

**Issue by olivM** [piwik/piwik#22143]
the offline tracking works perfectly ( https://matomo.org/faq/how-to/how-do-i-set-up-matomo-offline-tracking/ )
but is there a way to differenciate online and offline navigation ?

thanks

**Comment by sgiehl** [comment]
Hi @olivM,
We unfortunately can't provide support within GitHub issues. We only handle bug reports and feature requests here.
If you have any questions around offline tracking, please ask your question on our forums or get in touch with our support.
If a specific feature turns our to be missing, feel free to create a new issue here and describe in detail what exactly you are looking for, so our product team can pick that up for future improvements.
Thanks for your understanding.
