### ISSUE TITLE
Automatically update ts_created & ts_last_edit when invalidating segment reports

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#22169]
When processing additional historical data into segments there are two steps:
1. Invalidate the Segment report
2. Edit the DB to set the segment creation date and last edit date to the beginning date of the invalidation date range

For example:
Invalidate the report...
`sudo -u apache -E bash -c "php /var/www/html/console core:invalidate-report-data --sites=IDSITE_HERE --segment='SEGMENT_NAME_DEFINITION_HERE' --dates=2023-01-01,2024-03-31 --matomo-domain=domain.matomo.cloud"`

Log into the DB and update the `segment` table...
`UPDATE segment SET ts_created = '2023-01-01 00:00:00', ts_last_edit = '2023-01-01 00:00:00' WHERE name LIKE 'SEGMENT_NAME';`

This process should be automatic. When the `core:invalidate-report-data` command is used in combination with `--segment`, the system should check if the invalidation start date precedes the current `ts_created` and `ts_last_edit` dates in the `segment` table for the requested segment name. If it does, these columns should be modified automatically to remove the need to perform step two above.

**Comment by sgiehl** [comment]
@9joshua This sound more like a workaround for processing segments beyond the configured time frame.

https://github.com/matomo-org/matomo/blob/826ab461e7bde71d7ab76e9cbecb1db976bde8c2/config/global.ini.php#L315-L323

If this is not set to "beginning of time", segments might not be processed for the past by default. Automatically updating the ts_created of a segment would bypass this setting. So we shouldn't do that.
