### ISSUE TITLE
Don't have any report data for two days of the last month

### ISSUE THREAD

**Issue by dabock** [piwik/piwik#22179]
Hi,

we use Matomo for Wordpress on one of our clients sites.
While reviewing the reports of April, we discovered that the reports don't show any data for two days - but the report is complete the days before and after.

![grafik](https://github.com/matomo-org/matomo/assets/66642723/58c97cf8-0227-4c53-9504-dcdcae959cef)

But I can see data in the visitor logs for those days
![grafik](https://github.com/matomo-org/matomo/assets/66642723/75d1ac97-df07-4b0b-aae8-d59fa596872b)

I already tried to re-generate the reports - same results.

Any idea what goes wrong?

Thanks & regards,
David

				  # Matomo

* Matomo Plugin Version: 5.0.6
* Config exists and is writable.: Yes ("$abs_path/wp-content/uploads/matomo/config/config.ini.php" )
* JS Tracker exists and is writable.: Yes ("$abs_path/wp-content/uploads/matomo/matomo.js" )
* Plugin directories: Yes ([{"pluginsPathAbsolute":"$abs_path\/wp-content\/plugins\/matomo\/plugins","webrootDirRelativeToMatomo":"..\/plugins"}])
* Tmp directory writable: Yes ($abs_path/wp-content/cache/matomo)
* Matomo Version: 5.0.2
* Matomo Blog idSite: 1
* Matomo Install Version: 4.15.3 (Install date: 2023-11-29 13:24:54)
* Upgrades outstanding: No
* Upgrade in progress: No

## Endpoints

* Matomo JavaScript Tracker URL:  ($site_url/wp-content/uploads/matomo/matomo.js)
* Matomo JavaScript Tracker - WP Rest API:  ($site_url/wp-json/matomo/v1/hit/)
* Matomo HTTP Tracking API:  ($site_url/wp-content/plugins/matomo/app/matomo.php)
* Matomo HTTP Tracking API - WP Rest API:  ($site_url/wp-json/matomo/v1/hit/)

## Crons

* Server time: 2024-05-02 11:35:46
* Blog time: 2024-05-02 13:35:46 (Below dates are shown in blog timezone)
* Sync users & sites: Next run: 2024-05-02 14:25:39 (49 min 53s) ( Last started: 2024-05-01 14:27:10 (-23 hours 8 min). Last ended: 2024-05-01 14:27:10 (-23 hours 8 min). Interval: daily)
* Archive: Next run: 2024-05-02 14:24:54 (49 min 8s) ( Last started: 2024-05-02 13:24:55 (-10 min 51s). Last ended: 2024-05-02 13:24:55 (-10 min 51s). Interval: hourly)
* Update GeoIP DB: Next run: 2024-05-27 14:25:36 (25 days 0 hours) ( Last started: 2024-04-27 14:25:46 (-4 days 23 hours). Last ended: 2024-04-27 14:25:47 (-4 days 23 hours). Interval: matomo_monthly)

## Mandatory checks

* PHP version >= 7.2.5: ok 
* PDO extension: ok 
* PDO\MYSQL extension: ok 
* MYSQLI extension: ok 
* Other required extensions: ok 
* Required functions: ok 
* Required PHP configuration (php.ini): ok 
* Directories with write access: ok 
* Directories with write access for Tag Manager: ok 

## Optional checks

* 64-bit PHP Binary: ok 
* Tracker status: ok 
* Memory limit: ok 
* Time zone: ok 
* Open URL: ok 
* GD > 2.x + FreeType (graphics): ok 
* Other extensions: ok 
* Other functions: ok 
* Filesystem: ok 
* Last Successful Archiving Completion: ok 
* Database abilities: ok 
* Warning Max Packet Size: warning  (It is recommended to configure a '<a href="https://dev.mysql.com/doc/refman/en/packet-too-large.html" rel="noreferrer noopener" target="_blank">max_allowed_packet</a>' size in your MySQL database of at least 64MB. Configured is currently 16MB. )
* Geolocation: ok 
* Update over HTTPS: ok 
* Mobile Messaging SMS Provider: ok 
* Supports Async Archiving: No
* Async Archiving Disabled in Setting: No
* Location provider ID: geoip2php
* Location provider available: Yes
* Location provider working: Yes
* Warning Proxy header: HTTP_X_REAL_IP (A proxy header is set which means you maybe need to configure a proxy header in the Advanced settings to make location reporting work. If the location in your reports is detected correctly, you can ignore this warning. <a href="https://matomo.org/faq/wordpress/how-do-i-fix-the-proxy-header-warning-in-the-matomo-for-wordpress-system-report/" target="_blank">Learn more</a>)
* Had visit in last 5 days: Yes
* Matomo URL: Yes ($site_url/wp-content/plugins/matomo/app/)

## Matomo Settings

* Track mode: default
* Track ecommerce: No
* Track codeposition: footer
* Track api endpoint: default
* Track js endpoint: default
* Version history: 5.0.6, 5.0.5, 5.0.4, 4.15.3
* Core version: 5.0.2
* Last tracking settings update: 1701260762
* Last settings update: 1701343052
* Track ecommerce: No
* Disable cookies: Yes
* Show get started page: 0
* Mail history: 2024-05-01 19:24:58, 2024-04-01 19:25:18, 2024-03-01 19:25:08

## Logs

* None: 

# WordPress

* Home URL: $site_url
* Site URL: $site_url
* WordPress Version: 6.5.2
* Number of blogs: 1
* Multisite Enabled: No
* Network Enabled: No
* WP_DEBUG: No
* WP_DEBUG_DISPLAY: No
* WP_DEBUG_LOG: No
* DISABLE_WP_CRON: -
* FORCE_SSL_ADMIN: Yes
* WP_CACHE: No
* CONCATENATE_SCRIPTS: No
* COMPRESS_SCRIPTS: -
* COMPRESS_CSS: -
* ENFORCE_GZIP: -
* WP_LOCAL_DEV: -
* WP_CONTENT_URL: $site_url/wp-content
* WP_CONTENT_DIR: $abs_path/wp-content
* UPLOADS: -
* BLOGUPLOADDIR: -
* DIEONDBERROR: -
* WPLANG: -
* ALTERNATE_WP_CRON: -
* WP_CRON_LOCK_TIMEOUT: 60
* WP_DISABLE_FATAL_ERROR_HANDLER: -
* MATOMO_SUPPORT_ASYNC_ARCHIVING: No
* MATOMO_ENABLE_TAG_MANAGER: -
* MATOMO_SUPPRESS_DB_ERRORS: -
* MATOMO_ENABLE_AUTO_UPGRADE: -
* MATOMO_DEBUG: -
* MATOMO_SAFE_MODE: -
* MATOMO_GLOBAL_UPLOAD_DIR: -
* MATOMO_LOGIN_REDIRECT: -
* Permalink Structure: /%postname%/
* Possibly uses symlink: No
* Upload base url: $site_url/wp-content/uploads
* Upload base dir: $abs_path/wp-content/uploads
* Upload url: $site_url/wp-content/uploads
* Custom upload_path: 
* Custom upload_url_path: 
* Compatible content directory: Yes
* WP_Filesystem Initialized: Yes

# WordPress Plugins

* Advanced Custom Fields: Extended: 0.9.0.2
* Advanced Custom Fields: Table Field: 1.3.22
* Advanced Custom Fields Multilingual: 2.0.5
* Advanced Custom Fields PRO: 6.2.9
* Better Search Replace: 1.4.6 (Network enabled)
* Contact Form 7: 5.9.3
* Contact Form 7 Multilingual: 1.2.2
* Duplicate Page: 4.5.3
* Enhanced Media Library: 2.8.14
* eRecht24 legal texts for WordPress: 3.3.11
* Flamingo: 2.5
* Honeypot for Contact Form 7: 2.1.1
* Link Juice Optimizer: 2.3.2
* Matomo Analytics - Ethical Stats. Powerful Insights.: 5.0.6
* Rank Math SEO PRO: 3.0.60
* Rank Math SEO with AI Best SEO Tools: 1.0.217
* Regenerate Thumbnails: 3.1.6
* Relevanssi: 4.22.2
* Safe SVG: 2.2.4
* WebP Express: 0.25.9 (Network enabled)
* Wordfence Security: 7.11.5 (Network enabled)
* WP All Export - ACF Export Add-On Pro: 1.0.5
* WP All Export Pro: 1.8.8
* WPML Media Translation: 2.7.4
* WPML Multilingual CMS: 4.6.10
* WPML String Translation: 3.2.11
* WP Super Cache: 1.12.0
* Active Plugins: 26 (sitepress-multilingual-cms:4.6.10 acf-extended:0.9.0.2 acfml:2.0.5 advanced-custom-fields-pro:6.2.9 advanced-custom-fields-table-field:1.3.22 better-search-replace:1.4.6 contact-form-7-honeypot:2.1.1 contact-form-7-multilingual:1.2.2 contact-form-7:5.9.3 duplicate-page:4.5.3 enhanced-media-library:2.8.14 erecht24:3.3.11 flamingo:2.5 link-juice-optimizer:2.3.2 matomo:5.0.6 regenerate-thumbnails:3.1.6 relevanssi:4.22.2 safe-svg:2.2.4 seo-by-rank-math-pro:3.0.60 seo-by-rank-math:1.0.217 webp-express:0.25.9 wordfence:7.11.5 wp-all-export-pro:1.8.8 wpae-acf-add-on:1.0.5 wpml-media-translation:2.7.4 wpml-string-translation:3.2.11)
* Theme: taniobis (taniobis)

# Server

* Server Info: Apache
* Apache AddHandler support: Supported
* PHP OS: Linux
* PHP Version: 8.0.30
* PHP SAPI: fpm-fcgi
* PHP Binary Name: /opt/plesk/php/8.0/sbin/php-fpm
* PHP Maxmind DB extension: Not loaded
* PHP Error Reporting: 4437 After bootstrap: 4437
* PHP Found Binary: /usr/bin/php -q
* Timezone: UTC
* WP timezone: Europe/Berlin
* Locale: en_US
* User Locale: en_US
* Memory Limit: 1024M (At least 128MB recommended. Depending on your traffic 256MB or more may be needed.)
* WP Memory Limit: 512M
* WP Max Memory Limit: 1024M
* Timezone version: 0.system
* Time: 1714649747
* Max Execution Time: 30
* Max Post Size: 128M
* Max Upload Size: 67108864
* Max Input Vars: 1000
* Disabled PHP functions: Yes (opcache_get_status)
* zlib.output_compression is off: Yes
* Curl Version: 7.81.0, OpenSSL/3.0.2
* Suhosin installed: No

# PHP cli

* PHP cli Version: 8.1.2-1ubuntu2.15
* MySQLi support: ok

# Database

* MySQL Version: 10.6.16
* Mysqli Connect: Yes
* Force MySQL over Mysqli: No
* DB Prefix: CrnDNCN_
* DB CHARSET: utf8
* DB COLLATE: 
* SHOW ERRORS: No
* SUPPRESS ERRORS: No
* Uses Socket: No
* Uses IPv6: No
* Matomo tables found: 121
* DB tables exist: Yes
* Matomo users found: 9
* Matomo sites found: 1
* Required permissions: OK

# Browser

* Browser:  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0)
* Language: de,en-us,en

**Comment by sgiehl** [comment]
@dabock Looks like for some reason the data wasn't processed correctly.
Invalidating the days with incorrect data and rearchiving those periods might fix the problem.
See https://matomo.org/faq/how-to/faq_155/ for further details on how to invalidate the reports.

**Comment by dabock** [comment]
@sgiehl thanks for the fast reply.
Is this plugin (https://plugins.matomo.org/InvalidateReports#description) also available for Wordpress?

**Comment by sgiehl** [comment]
It should. See https://plugins.matomo.org/?wp=1 for plugins available for Matomo for Wordpress

**Comment by dabock** [comment]
Found it, deleted and regenerated the reports and now the data is also visible in the reports.
So the problem is solved.

Thanks again for your quick help!
