### ISSUE TITLE
UX -Userfriendly backend

### ISSUE THREAD

**Issue by NickZ450** [piwik/piwik#22174]
The way matomo goes is not UX or user friendly.
Newest development is we have to invite a user in order to later limit the very user. 
Whoever came up with this should not have a role in development other than coding.
Why not used use a simple path: create a user, give the user access to view, edit his page or pages?

Similar is the new way to store passphrases, usernames, Is there a reason behind making things more complex?

**Comment by michalkleiner** [comment]
Thank you for your feedback, @NickZ450.
Our product and engineering teams are aware of some of the shortcomings of Matomo UI that were accumulated over more than 15 years of its development, and we are actively working on making Matomo better.
As this is not reporting a specific reproducible bug, and this issue tracker is primarily designated to reporting bug and proposing new features, I'd suggest opening the topic in one of the forum categories on https://forum.matomo.org/.
With that I will close the issue for now, appreciate the understanding.
If you think there is a replicable bug, feel free to provide more details including replication steps.
