### ISSUE TITLE
[Bug] Can't login Admin after upgrade to matomo 5.x 

### ISSUE THREAD

**Issue by nnhiep** [piwik/piwik#22172]
### What happened?

I encountered an issue when upgrading Matomo from version 4.x to 5.x. After the upgrade, should I choose the new global.ini.php file or continue using the old one? 
When I use the new file, there's a notification "File integrity check failed", but when I use the old file, I get this error "array_intersect(): Argument #2 must be of type array, null given"

<img width="698" alt="Screen Shot 2024-04-30 at 06 56 11" src="https://github.com/matomo-org/matomo/assets/17465696/63dc7cd9-35fa-4fa3-a683-a1f4cd7a837d">
<img width="697" alt="Screen Shot 2024-04-30 at 07 03 20" src="https://github.com/matomo-org/matomo/assets/17465696/69af2517-5543-40f8-bb23-497b0933980c">

### What should happen?

How can I fix it?

### How can this be reproduced?

Upgrade matomo from 4.0.3 to 5.0.1

### Matomo version

5.0.1

### PHP version

8.3.6

### Server operating system

CentOS7

### What browsers are you seeing the problem on?

Chrome

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@nnhiep Try using the `global.ini.php` from the release you are using rather than the latest one from GitHub. If you are using 5.0.1 download the according release and extract the file from there: https://builds.matomo.org/

**Comment by nnhiep** [comment]
Thanks @sgiehl

**Comment by nnhiep** [comment]
I use global.ini.php in version 5.0.1, I successfully logged in as admin, but I'm still encountering this error as below. Can you guide me on how to fix it?"

**Errors below may be due to a partial or failed upload of Matomo files.
--> Try to reupload all the Matomo files in BINARY mode. <--

File size mismatch: /var/www/html/matomo/config/global.ini.php (expected length: 64375, found: 64379)**
