### ISSUE TITLE
Poor integration with Google products

### ISSUE THREAD

**Issue by enual** [piwik/piwik#22196]
Customer reported a poor integration with Google products, especially Google Ads Remarketing. Google Analytics is needed if ad performance needs to be measured in a useful way.

**Comment by michalkleiner** [comment]
Hi @enual. I will close this issue as it is not actionable bug or enhancement request, there's no suggestion or reproduction steps. Perhaps this can just be raised internally with the product team. Thanks for your understanding.

**Comment by enual** [comment]
Thank you for letting me know @michalkleiner. Have a nice day.
