### ISSUE TITLE
Password field is disabled when saving settings [Bug] 

### ISSUE THREAD

**Issue by jorgeuos** [piwik/piwik#22203]
### What happened?

I've seen this a couple of times now, even with previous versions too.

The password field is disabled when trying to save General settings, which prompts for password.

Could be elsewhere too, e.g. the user setting page.

I believe it has to do with a Vue component setting isLoading or isUpdating to true and never sets it to false, I could be wrong.

### What should happen?

It should be possible to input your password when prompted.

### How can this be reproduced?

Go to the settings page, update a field, "Cross-Origin Resource Sharing (CORS) domains" for example, and hit save.

### Matomo version

5.0.3

### PHP version

8.2.18

### What browsers are you seeing the problem on?

Chrome

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@jorgeuos are you using LoginLdap or LoginSaml? When using those plugins the password field might be disabled on purpose.

**Comment by jorgeuos** [comment]
Ah, that could be it.
I believe SAML has recently been activated.
Thanks!

**Comment by sgiehl** [comment]
Note: With Matomo 5.1.0. the password field will no longer be shown when it is not required. See https://github.com/matomo-org/matomo/pull/21916
