### ISSUE TITLE
[Bug] File size mismatch hiddeninput.ext

### ISSUE THREAD

**Issue by 65Q2M89mBVP53sCK** [piwik/piwik#22211]
### What happened?

I have updated Matomo to version 5. Subsequently, I updated to the latest version via the backend update. After the updates, I see the message in the system check:

```
Errors below may be due to a partial or failed upload of Matomo files.
--> Try to reupload all the Matomo files in BINARY mode. <--

File size mismatch: /srv/www/DocRoot/piwik/vendor/symfony/console/Resources/bin/hiddeninput.exe (expected length: 9216, found: 9201)
```

Even a current version of GitHub (Symphony console) doesn’t change anything. All versions of hiddeninput.ext that I try seem to be incorrect. I’m also wondering what I should do with a *.exe file on a Linux system?

### What should happen?

No such notifications should occur.

### How can this be reproduced?

Got to Matomo Backend > Diagnostic - System Check

### Matomo version

5.0.3

### PHP version

8.3.6

### Server operating system

Ubuntu 16.04.7 LTS (Xenial Xerus)

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Macos Sonoma 14.4.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
You may need to use the version of the release you are using. You can download the full release at https://builds.matomo.org/.
Ensure to download exactly the version you are currently using and extract the incorrect file from it.

Note: The file is part of symfony console, a library we are using. As far as I know the mentioned exe file is used to hide password on windows cli.

**Comment by 65Q2M89mBVP53sCK** [comment]
"I took a look at composer.json:
[https://raw.githubusercontent.com/matomo-org/matomo/5.x-dev/composer.json](https://raw.githubusercontent.com/matomo-org/matomo/5.x-dev/composer.json)

```
composer.json contains the following line for the Symphony Console:
"symfony/console": "~5.4.0",
```

When I run composer install for testing, I see that symfony/console (v5.4.39) is being installed.
This version is 12 years old. The latest version of Symphony is 7.1. I am worried that Matomo is using 12-year-old components. Shouldn't it be updated to the latest version?

**Comment by sgiehl** [comment]
@65Q2M89mBVP53sCK Symfony console 5.4. is still actively maintained. The last release was done two weeks ago. See https://github.com/symfony/console/releases/tag/v5.4.39
And we can't update to 7.x yet, as we still support PHP 7.2, which Symfony console 7 doesn't.
