### ISSUE TITLE
Error Vue build in plugin

### ISSUE THREAD

**Issue by Red2011** [piwik/piwik#22212]
When running build for example Example Vue: php .\console vue:build ExampleVue
an error occurs:
Building CoreHome…
‘BROWSERSLIST_IGNORE_OLD_DATA’ is not recognized as an internal or external command,
operable program or batch file.
Failed:

The system cannot find the path specified.
Building ExampleVue…
‘BROWSERSLIST_IGNORE_OLD_DATA’ is not recognized as an internal or external command,
operable program or batch file.
Failed:

The system cannot find the path specified.

 **I need some help!**

**Comment by sgiehl** [comment]
Sorry for the late response on that one.
By the looks you tried to run the command using a windows environment. As mentioned on https://developer.matomo.org/guides/getting-started-part-1 this is currently not supported.
For building vue files on windows you might need to use a virtual machine or wsl, but it might also work using something like git bash.
