### ISSUE TITLE
Display unique visitors on custom dimensions when range is different than day

### ISSUE THREAD

**Issue by Ghislain-Italic** [piwik/piwik#22227]
Hello,

We want to have "unique visitors" metric on dimension other than daily (weekly, monthly, yearly and range).
We followed the documentation by modyfying the config.ini.php file and reprocessing our data without result :
https://matomo.org/faq/how-to/faq_113/
https://matomo.org/faq/how-to/faq_59/

We want this unique metric for our events but it is not available on dimension other than daily :  
Daily :       
![](https://files.italic.fr/chrome_YWBYCRuT09.png)

Custom range :        
![](https://files.italic.fr/chrome_c5jm4784V7.png)

Does any extra settings are required ?

Thank you !

**Comment by sgiehl** [comment]
Hi @Ghislain-Italic,

It is only possible to process the overall unique visitors metric by changing the configs you referenced above.
Processing this metric for other reports isn't possible at the moment.

Note: Only day reports are currently computed by querying the raw data. All other periods are built by summing up the daily numbers. This won't work for unique visitors, as summing them up would result in an incorrect number. But computing them by querying the raw data for bigger periods would fully kill the archiving performance even with smaller datasets.
