### ISSUE TITLE
[Bug] Charts for Conversions by Entry Pages & Page Titles Broken

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#22236]
### What happened?

The 'Visits' chart plot does not have a title and once another chart plot type is selected, the visits type cannot be reselcted.
![image](https://github.com/matomo-org/matomo/assets/20234985/bc653dd0-f3b4-4701-98eb-f1f5dbfb1270)

Entry Page conversion charts are partly broken for both:
- Conversions -> Overview (or specific Goal) -> Goals by Pages
- Ecommerce -> Sales -> Sales by Pages
![Ecommerce report - entry page ev chart](https://github.com/matomo-org/matomo/assets/20234985/07c88b8a-5fd5-40f4-9446-e1fa23ca8225)

```
WARNING: /plugins/API/RowEvolution.php(67): Warning - Undefined array key &quot;nb_visits&quot; - Matomo 5.1.0-b3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreHome, Action: getRowEvolutionPopover, Method: API.getRowEvolution, In CLI mode: false)
```

### What should happen?

The chart plot category 'Visits' should function properly. 

### How can this be reproduced?

View a evolution chart for Ecommerce -> Sales -> Sales by Pages -> Entry Pages -> Click the chart button for any page URL

### Matomo version

5.1.0-b3 (Cloud)

### PHP version

8.1

### Server operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Ubuntu

### Relevant log output

```
WARNING: /plugins/API/RowEvolution.php(67): Warning - Undefined array key &quot;nb_visits&quot; - Matomo 5.1.0-b3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreHome, Action: getRowEvolutionPopover, Method: API.getRowEvolution, In CLI mode: false)
```
Browser console error when clicking the 'Visits' chart plot type:
```
index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:774 Uncaught TypeError: Cannot read properties of undefined (reading 'tickOptions')
    at exports.JqplotEvolutionGraphDataTable.setYTicksForAxis (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:774:9)
    at exports.JqplotEvolutionGraphDataTable.setYTicks (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:768:655)
    at RowEvolutionSeriesToggle.replot (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:787:99)
    at RowEvolutionSeriesToggle.showSeries (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:782:588)
    at HTMLTableRowElement.<anonymous> (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:790:243)
    at HTMLTableRowElement.dispatch (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:4:43184)
    at y.handle (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:4:41168)
```
### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Thanks for the detailed report @9joshua 
I was able to reproduce that one, and directly found a proper fix for it. Will prepare a pull request, so that gets fixed in the next release.
