### ISSUE TITLE
MySQLv8 + cache_sha2_password

### ISSUE THREAD

**Issue by stalachristian** [piwik/piwik#22238]
Matomo does not support MySQLv8 in a proper way.

If I create a user with mysql_native_password i get a warning that this is deprecated on EVERY database access
> Plugin mysql_native_password reported: ‘‘mysql_native_password’ is deprecated and will be removed in a future release. Please use caching_sha2_password instead’

If I create a user with sha2_password i get an error:
> SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

Matomo-Forum:
https://forum.matomo.org/t/mysqlv8-cache-sha2-password/56083

Environment
* Matomo Version: 5.0.3
* PHP Version: 7.4.33
* Server Operating System: SLES12 SP5

**Comment by sgiehl** [comment]
Hey there,

There actually isn't anything we can do about that. We are providing the credentials to the PHP MySQL client, which then creates the connection.
If it doesn't work this might be an issue with either the configuration of MySQL or with the PHP MySQL extension.
