### ISSUE TITLE
Problem with Campagin Tracking since update to 5.0.3

### ISSUE THREAD

**Issue by markatus** [piwik/piwik#22263]
Since the update to Matomo version 5.0.3 we have the problem that the campaign tracking does not work 100% anymore. Since the update, visitors coming via Google Ads are no longer listed. Visitors from Meta still seem to be recognized. The day before the update the tracking still worked.

Previously, the tracking links were stored with ?mtm parameters.

Has there been an update regarding tracking links or something similar?

**Comment by sgiehl** [comment]
@markatus Which version did you update from?

**Comment by markatus** [comment]
@sgiehl 

Matomo Update History: 4.15.1, 4.13.0, 4.12.3, 4.11.0, 4.10.1, 4.9.1

**Comment by markatus** [comment]
Now i have seen that the Plugin _MarketingCampaignsReporting_ has not worked correctly. I have now updated this Plugin and will check if this fixes the problem.

**Comment by sgiehl** [comment]
Pretty sure that will fix the issue. If not feel free to create a new issue.
