### ISSUE TITLE
[Bug] The device type is incorrect

### ISSUE THREAD

**Issue by skyhhjmk** [piwik/piwik#22273]
### What happened?

The "honor"
At present, it no longer belongs to Huawei
![image](https://github.com/matomo-org/matomo/assets/78078552/d2d83550-8933-4b0f-9547-04ce0859ee0f)

### What should happen?

Its brand should be called: Honor

### How can this be reproduced?

Obviously, there is no point in reproducing this problem, and having this image is enough to prove that this problem exists
![image](https://github.com/matomo-org/matomo/assets/78078552/d2d83550-8933-4b0f-9547-04ce0859ee0f)

### Matomo version

5.1.0-b4

### PHP version

8.2.15

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
We had decided not to split that up in the past in order not to loose comparability. Splitting them would mean that you would not be able to e.g. view the row evolution for old dates anymore. See https://github.com/matomo-org/device-detector/issues/6836
