### ISSUE TITLE
No response at relocation request

### ISSUE THREAD

**Issue by tradium-team** [piwik/piwik#22275]
Hi there,

were trying to move our on-premise account to a cloud account. I filled out the contact form a few weeks ago but didnt receive any answer from Matomo yet. Can you please look up in your system if you got the message? Or is there any other probem? 

Cloud account is https://tradium.matomo.cloud/

Thanks a lot and have a nice day,
Oliver

**Comment by michalkleiner** [comment]
Hi @tradium-team, I will let the team know internally but please contact the support team via https://matomo.org/support/ or through the contact form from your cloud instance and I'm sure they will get back to you on the matter. The issue tracker is dedicated to reporting bugs or raising feature requests. Thank you for your understanding.
