### ISSUE TITLE
[Bug] Give this user access to All Websites does not work

### ISSUE THREAD

**Issue by brodenbrett** [piwik/piwik#22286]
### What happened?

When updating a user's permissions for all sites using the "Give this user access to All Websites" field, some sites retain their previous permission level.

### What should happen?

After Apply is clicked, the user should have the applied permission for all websites.

### How can this be reproduced?

Note that our Matomo account has 3058 sites included.

1. Create a new user.
3. Edit the user. Under "Permissions", select "View" in the "Give this user access to All Websites:" field, then click Apply.
4. In our case, filtering by "No access" reveals that there are 2060 sites that were not affected. Filtering by "View" reveals 998.

Click [here](https://github.com/matomo-org/matomo/assets/22228834/8941b5ce-6c54-40e6-9b25-67583ad8e186) for a video example

### Matomo version

4.15.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @brodenbrett. I've just checked that with our latest release and I wasn't able to reproduce it there.
I would therefor recommend to update your Matomo instance.
