### ISSUE TITLE
Date Comparison: require "Apply" button as the only way to close the modal

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#22308]
Improve the UI for date comparison by waiting for the user to click the green "Apply" button (in Date selector >> Compare to >> Custom).

As @michalkleiner said:

> The issue I can see here is that when you enable the comparison feature and then click a date in the calendar, it confirms the date selection and shows an error because there were no dates selected for the comparison (regardless if typed in or selected in some other way). The modal/date selection should not close when the comparison is enabled and a date in the calendar is clicked, it should only apply and close using the Apply button.

To reproduce:
1. From any report in Matomo, click the date selector tab
2. Select any time
3. Click Compare to >> Custom
4. Click the calendar

**Comment by michalkleiner** [comment]
Thanks for separating this issue out from #22042. After another round of consideration we'll fold it back in and address it together.

**Comment by atom-box** [comment]
Sounds good.
