### ISSUE TITLE
Enhance password generation on user invitations with autocomplete HTML parameter

### ISSUE THREAD

**Issue by ronan-hello** [piwik/piwik#22303]
Hello,

It could be a great enhancement to add HTML `autocomplete` parameter to allow web browser to generate password and password confirmation easily.

HTML documentation : https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/autocomplete

<img width="1728" alt="Capture d’écran 2024-06-10 à 21 37 44" src="https://github.com/matomo-org/matomo/assets/24936187/33e3e034-18df-4c84-a11c-962691542307">

Regards,
Ronan HELLO from [Openmost](https://openmost.io)

**Comment by sgiehl** [comment]
Hi @ronan-hello,
Thanks for creating this suggestions. I'll prepare a PR to change that.
