### ISSUE TITLE
Results problem in “Others

### ISSUE THREAD

**Issue by shynixxx** [piwik/piwik#22307]
Hello,

I'm having a problem searching for a url from the api by passing a range as a parameter but it doesn't find the results when I search because it goes into the “Other” category.
I've followed the matomo documentation https://matomo.org/faq/how-to/faq_54/ and made several different modifications, putting 5000 on each one, but it still displays “Others” and the API returns an empty table .... I've emptied the matomo cache after each modification and checked in /index.php?module=Diagnostics&action=configfile if it was applied correctly but still nothing.

I've run out of ideas, do you have a method for displaying all the stats for the various pages when the range is large? 

Thanks in advance

Translated with DeepL.com (free version)

**Comment by sgiehl** [comment]
After changing the config you may need to reprocess the archive data. Otherwise the reports for the past will stay the same and only new records will include more rows.
