### ISSUE TITLE
[Bug] When adding a user, the confirm button has an error message inside it

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#22313]
### What happened?

![image](https://github.com/matomo-org/matomo/assets/22874146/c76451ec-060f-43ab-ad9a-b8d6e263c103)

I upgraded to Matomo 5.1.0. When adding a user today, Matomo showed the above message (notice what the confirm button has inside it, instead of "OK".

When clicking the blue button (the strange message) I get a confirmation that an invitation was sent, so it doesn't seem to be a problem. But the message is obviously no good.

### What should happen?

The button is supposed to say "Okay" or similar. Instead it has a strange error message text inside it.

### How can this be reproduced?

1. Install 5.1.0.
2. Invite a user.
3. Notice the bug!

### Matomo version

5.1.0

### PHP version

_pending!_

### Server operating system

_Docker, Linux_

### What browsers are you seeing the problem on?

_answer pending!_

### Computer operating system

Linux

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
@atom-box is it reliably replicable? I just tried on a fresh install of 5.1.0 and I don't see the issue, the button reads Confirm. I would recommend checking all files from the 5.1.0 release are correctly installed and possibly reinstall again. It's either a missing language file or some language translation strings didn't load properly. Any errors in browser console?

**Comment by randy-innocraft** [comment]
Hi @atom-box. Thank you for creating the issue and bringing this to our attention, that's very appreciated. We have reviewed and triaged the problem internally, and we have confirmed it is an issue. Our team will prioritise this, and we will update you on the progress here when we have an update to share. If you have any further information or questions, please feel free to add them here.

**Comment by atom-box** [comment]
The user wrote back:
"I don't see any other similar problems, so not a big deal."

Number of other users reporting this problem in the last 45 days:
zero

I recommend to close this ticket!

**Comment by atom-box** [comment]
This was reported again today by a user. Not re-opening this until I reproduce it.

**Comment by sgiehl** [comment]
@atom-box Do you know if the user maybe had the 2FA plugin completely disabled on their instance?
