### ISSUE TITLE
[Bug]  Visitor Profile stucked at loading

### ISSUE THREAD

**Issue by jrca025** [piwik/piwik#22337]
### What happened?

When clicking a visitor profile. It is stucked at loading

![image](https://github.com/matomo-org/matomo/assets/89201548/f6faf1c7-b668-483a-b684-fb7cf3d0e5f2)

### What should happen?

Given with the large amounts of data for this particular site. What other ways for us to optimize this? I already have archive on this since from the start. Tried adjusting memory limits of PHP/NGINX.

### How can this be reproduced?

Click on Visits Log > Click visitor profile of a specific user

### Matomo version

5.1.0

### PHP version

8.1

### Server operating system

Ubuntu 22

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer operating system

Windows

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @jrca025,
Unfortunately this isn't anything we can help you with here on GitHub, as we are only using our issue tracker for feature requests and bug reports. You problem seems more related to server setup and configuration.

There are various things you can do to improve the performance: https://matomo.org/subcategory/improve-performance/

Please try to find further help on our forums or our support instead. Thanks.
