### ISSUE TITLE
White labelling of tracking APIs domain name

### ISSUE THREAD

**Issue by Shyamjitiwari12** [piwik/piwik#22359]
I am using white label plugin and want to white label tracking code
end-points. When I am using Wappalyzer chrome extension to know the
Analytics tool used on my website [digitup.in](http://digitup.in/), it's still shows Matomo
Analytics, we want it to show our brand name.

I am attaching the screen recording for your reference.

https://github.com/matomo-org/matomo/assets/88368625/1b371a1c-ec91-4d50-a75f-e12a90588a44

**Comment by michalkleiner** [comment]
Hi @Shyamjitiwari12, I don't think that is something easily possible by changing/configuring things within your Matomo instance. My guess is that Wappalyzer determines there's Matomo Analytics tracking by looking at the actual delivered JS tracker snippet. It would be unpredictable for the users of Wappalyzer if everyone could change how their tracking appears in their extension. It would create room for spam/scam or fraud. As there's no mention of Matomo in your page's HTML source we can be sure it's not from there. I hope that makes sense.
