### ISSUE TITLE
How can I create a segment to track if users are visiting 2 key pages in a single visit?

### ISSUE THREAD

**Issue by infor-pranav** [piwik/piwik#22352]
I have tried to create a segment with the following criteria: "Page Title" Is "Page 1" AND "Page Title" Is "Page 2". However, this returns no results. Is there a better way to create this segment? I would like to track if a user has visited both of these pages in a visit.

**Comment by sgiehl** [comment]
Hi @infor-pranav 
That won't work with the segment system, as it will always look for one action/visit that matches all criterias.
For more details see https://github.com/matomo-org/matomo/issues/22235

Depending on your needs that might be something you can achieve with the Funnels plugin.
