### ISSUE TITLE
Cloudflare without the matomo app

### ISSUE THREAD

**Issue by tsatilas** [piwik/piwik#22377]
Hi
i have bean using matomo for a good time now via cloudflare
but sins 04/07/2024 cloudflare have stop the support of third parties applications
and its not possible to get data anymore
Any solution to use the matomo self hosted on a domain via cloudflare without the application?

**Comment by masterwishx** [comment]
Also interested, it will end up in 31 August

**Comment by sgiehl** [comment]
Hey there. We've updated our FAQ on how to install the tracking code on cloudflare: https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-cloudflare-setup/
Hope that helps!

**Comment by masterwishx** [comment]
> Hey there. We've updated our FAQ on how to install the tracking code on cloudflare: https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-my-cloudflare-setup/ Hope that helps!

Thanks its working , should we use `All Tracks` or better add all triggers from matomo tags? 
Also zarah is limited for 1,000,000 events for free ...

**Comment by tsatilas** [comment]
Is not working for me 🙁
________________________________

**Comment by masterwishx** [comment]
Did you made as in faq?
Are you using js script or tag manager?

**Comment by tsatilas** [comment]
I did it exactly like the faq
Should have work
________________________________

**Comment by tsatilas** [comment]
It worked
It was permissions issues, you guide is ok
Thanks for your reply to tell me that you have updated =)
________________________________

**Comment by sgiehl** [comment]
Glad to hear this works for you both. I'll close this issue then.
