### ISSUE TITLE
Matomo iOS SDK Bundle name problem

### ISSUE THREAD

**Issue by stevespaw** [piwik/piwik#22387]
### What happened?

While we track events to Matomo, there is a problem that affects mainly iOS devices: the events are not logged for iOS devices only. We have discovered that the Matomo iOS SDK is sending user agents by utilizing the bundle name "Zeale" for our project, which is why no iOS events are being tracked. But, it does function if I replace the bundle name with another name, such as "Zeel". Therefore, would you kindly investigate why it prevents us from tracking events?

The user agent that is sent via Matomo iOS SDK:
Darwin/23.2.0 (iPhone16,2; iOS 17.4) MatomoTrackerSDK/7.3 Zeale/0.0.1

### What should happen?

Bundle name "Zeale" should work

### How can this be reproduced?

send user agents by utilizing the bundle name "Zeale"

### Matomo version

5.1.0

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @stevespaw 
It seems like `Zeale` matches a bot user agent pattern of device detector, causing tracking requests to be ignored by Matomo.
Feel free to create an issue here to get that changed if needed: https://github.com/matomo-org/device-detector/issues
