### ISSUE TITLE
[Bug] When applying a segment to the Referrers reports it is not getting applied 

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22401]
### What happened?

If I click on Acquisition --> All Channels --> Referrers and that I applied a segment. The information displayed are not getting filtered.

https://github.com/user-attachments/assets/9321483e-2ff0-4708-94e0-5ea2e3fd971d

### What should happen?

It should get filtered or at least display a blue information message saying that it is not getting filtered.

### How can this be reproduced?

Acquisition --> All Channels --> Referrers and then apply a filter.
Strangely, it is appearing in the cloud, but on the last on-premise version of Matomo that i have it is working fine.

### Matomo version

5

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@Chardonneaur That happens when using SearchEnginesKeywordsPerformance plugin. As the data provided by Google, Bing or Yandex can not be segmented, the reports, those data is included in, loose their ability for segmentation. There unfortunatelly isn't much we can do about that. If you think the message could possibly be improve to explain that better, that would need to be changed in the plugin.

**Comment by Chardonneaur** [comment]
@sgiehl but it is not only about keywords, it is also about visits to websites.

**Comment by sgiehl** [comment]
The referrer overview report merges together the reports around referring websites, social networks, search engines (including keywords) and campaigns. As the keyword data is not segmentable, the whole report doesn't support it, as there is no sense in mixing up segmented and unsegmented data.

**Comment by Chardonneaur** [comment]
@sgiehl ok but can we then have an information message explaining this?

**Comment by sgiehl** [comment]
It might be mentioned in our FAQs somewhere. The messages displayed in the reports can also be adjusted, but as they are coming from the plugin, they would also need to be adjusted in the plugin. So this would need an internal issue.
