### ISSUE TITLE
[Bug] Total revenue ecommerce metric is different from the total of the total product revenue

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22407]
### What happened?

The total revenue metric of ecommerce is different that the total of all product revenue in ecommerce whereas they should be the same.

https://github.com/user-attachments/assets/2fffc185-48f0-4411-abe3-b7615afb8607

### What should happen?

The two metrics should be the same.

### How can this be reproduced?

Go on https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Goals_Ecommerce&subcategory=General_Overview and look at the metric named Total revenue.
Go on https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Goals_Ecommerce&subcategory=Goals_Products and click on the cog wheel at the bottom of the report in order to display the show totals row.

### Matomo version

5

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by randy-innocraft** [comment]
Hi @Chardonneaur . Thank you for creating the issue and bringing this to our attention, that's very appreciated. We have reviewed and here are our findings.

Technically there is no link between product and overall ecommerce revenue. The reason for that is how ecommerce stuff is tracked.

You can add products to a cart, where each product may have quantity and price. Those data is displayed in the product views in Matomo. So the sum there is simply quantity * price for each converted cart item.

When something is sold Matomo allows to track a ecommerce conversion, providing the total revenue, taxes, shipping, discounts… Those are stored with the conversion. The overall ecommerce numbers are simply a sum of those conversion metrics.

BUT: The totals of all products previously added to a cart must not match the numbers tracked for the ecommerce conversion. 

So if those numbers don’t match it can be the case, that for some conversion  numbers simply don’t match the products added to it.

We will make a clear distinction between conversion (total revenue) and products in cart within our product and KB. We will track progress in the KB ticket. Therefore, this issue will be closed.

**Comment by Chardonneaur** [comment]
thank you @randy-innocraft for the explanation, mind blowing, in fact I discovered yesterday that it is kind of the same logic for the visitor metric across the different reports. Now, it is my role, to clearly explain it to the public about the mathematics behind. Thank you so much for your effort in explaining it to me.
