### ISSUE TITLE
Instead of percent rate, send numerical values through the API

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22405]
Hi Team,

Currently, if we export a data feed from the API where this a percent rate, for example: 7%, it will be intepreted as a text string from the data visualization software. Ideally, the data output should be 0.07 in order to have a clean datafeed for those platforms:

https://github.com/user-attachments/assets/74de2e5b-898b-42fe-ae22-039354466139

**Comment by michalkleiner** [comment]
https://github.com/matomo-org/matomo/issues/20701 might be relevant.

**Comment by sgiehl** [comment]
@Chardonneaur you should be able to achive that already by appending `&format_metrics=0` to the url. If the parameter is not provided the default will be to format percent metrics only.

**Comment by Chardonneaur** [comment]
@sgiehl ok, thank you, it is fixing the issue, so I guess, now it is just about enriching our internal documentation. I wrote the following ticket: https://github.com/matomo-org/developer-documentation/issues/795
