### ISSUE TITLE
[Bug] Differences between the number of visitors from API.get to Referrers.get

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22404]
### What happened?

If you look at https://demo.matomo.cloud/index.php?module=API&method=API.get&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous the number of visitors is 9794, if you look at https://demo.matomo.cloud/index.php?module=API&method=Referrers.get&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous the number of unique visitors is 10857 so, there is an issue in finding the right KPI.

### What should happen?

The number of visitors from both reports should be exactly the same.

### How can this be reproduced?

Look at https://demo.matomo.cloud/index.php?module=API&method=API.get&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous compare it to https://demo.matomo.cloud/index.php?module=API&method=Referrers.get&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous

### Matomo version

5

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by Chardonneaur** [comment]
https://github.com/user-attachments/assets/ddf6376a-844b-4a02-86d5-02e285113956

**Comment by michalkleiner** [comment]
I'm not sure how you're adding the numbers together, but as of now, I see 10142 visits in https://demo.matomo.cloud/index.php?module=API&method=API.get&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous and if I add up the referrers in https://demo.matomo.cloud/index.php?module=API&method=Referrers.get&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous I also get 10142.

**Comment by michalkleiner** [comment]
7165+1157+973+847+0=10142

![Screenshot 2024-07-18 at 3 35 57 PM](https://github.com/user-attachments/assets/87eb26bd-dbc9-4e8a-bede-0106f9742a4d)

![Screenshot 2024-07-18 at 3 35 49 PM](https://github.com/user-attachments/assets/eca3d7b4-9a60-4ddb-bf4e-ecbd24fa901e)

**Comment by Chardonneaur** [comment]
@michalkleiner but I didn't mention visits, I mentioned visitors.

**Comment by peterbo** [comment]
Without looking into details, but I think these two dimensions are not comparable 1:1, since one visitor can have multiple referrers (one per session). So I guess that a unique visitor can be attributed multiple times to different channels. But I cannot open visitor profiles on demo, so I can't check if that's the case.

**Comment by Chardonneaur** [comment]
Whaoooo, that's a very good point. Thank you @peterbo I was wrong.
