### ISSUE TITLE
[Bug] Warning - Array to string conversion -WARNING: /libs/Zend/Db/Statement/Pdo.php(229): - Matomo 5.2.0-alpha.20240628132246

### ISSUE THREAD

**Issue by WhitneyItron** [piwik/piwik#22410]
### What happened?

seeing this warning message when creating a new segment - WARNING: /libs/Zend/Db/Statement/Pdo.php(229): Warning - Array to string conversion - Matomo 5.2.0-alpha.20240628132246

### What should happen?

should be able to create a new segment without a warning message - 

### How can this be reproduced?

go to the dashboard overview -  edit segments

### Matomo version

cloud version

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

PC

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by randy-innocraft** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue #21410, I'll close this one to keep the discussion centralized. 
It would be great to have your perspective on the original issue.
