### ISSUE TITLE
Remove rel="noreferrer noopener" in Visits Log

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#22426]
Please remove `rel="noreferrer noopener"` in Visits Log visited page links.

My websites configuration needs the referrer, but matomo set a `rel="noreferrer noopener"` to the links of the visited page. I have tested to remove it with JavaScript `.removeAttribute("rel")`, and this removes it, but the referrer will always not be send.

**Comment by randy-innocraft** [comment]
Hi @matomoto,
Thank you for bringing this to our attention and for your valuable input. We recommend that you develop a plugin for it as the current behaviour is expected and a privacy/security measure. If you have any additional details or questions, please feel free to share them here.

**Comment by matomoto** [comment]
I have tested the Matomo Plugin CodeInjector, but with this it is not possible to change or remove the HTML Attribute.    
https://github.com/openmost/CodeInjector

I don't really understand the security risk by `noreferrer`. The internet adress of a matomo instance is always inside the Matomo Tracking Code in the webpages that are listed in the Matomo statistics. It's a circle.
