### ISSUE TITLE
Unique Visitor error

### ISSUE THREAD

**Issue by Travellersarchive** [piwik/piwik#22431]
### What happened?

When looking at the visitor overview, it shows that the number of visitors is exactly the same as the number of unique visitors. As this is not possible, what is the explanation for this? Is this an error, and if so, how can we fix it? 

### What should happen?

The number of total visitors has to be much bigger, of course, than the number of uniques.

### How can this be reproduced?

-

### Matomo version

5.0.2.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by peterbo** [comment]
This is normal for environments, where cookies are disabled. That's because without cookies (and no special settings for heuristic user recognition), Matomo is "not allowed" to recognize visitors cross session. After half an hour of inactivity, a visitor is recognized as a new unique visitor (same logic as new sessions. Therefore, both numbers are (near) identical).

**Comment by des-innocraft** [comment]
@Travellersarchive thank you for creating this ticket. Did you have a change to review @peterbo reply? Is the explanation answered this -->  number of visitors is exactly the same as the number of unique visitors ?

**Comment by Travellersarchive** [comment]
Hi there, 

actually, not really. What are the right settings to ensure that our figures are tracked correctly?

Thanks
Clemens

**Comment by sgiehl** [comment]
@Travellersarchive If unique visitors and visits numbers are always the same, this is most likely an issue with the tracking implementation or configuration. As mentioned not using cookies at all might cause this, but there could also be other reasons.
As we are not able to provide such type of support via github issues, I would suggest to try getting support on our forums at https://forum.matomo.org/
You should try to include as much information as possible in your request there. Like what exactly you are tracking, how the tracking is implemented,...
