### ISSUE TITLE
[Bug] Monolog/Logger not found

### ISSUE THREAD

**Issue by faizanjaved5** [piwik/piwik#22466]
### What happened?

cloned the project to my local machine and tried to run the app, but at first the application was unable to load Piwik/Url class stating class not found 

> Fatal error: Uncaught Error: Class "Url" not found in matomo\core\testMinimumPhpVersion.php:70 ...

Then i tried regenerating autoload files via composer dump-autoload command but now it is giving this error

> Fatal error: Uncaught Error: Class "Monolog\Logger" not found in core\Log\Logger.php:16 

### What should happen?

Installing a fresh copy of the application

### How can this be reproduced?

- git clone https://github.com/matomo-org/matomo.git
- running the application on the browser via xampp 

### Matomo version

latest

### PHP version

8.1.6

### Server operating system

xampp, Apache

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows 11

### Relevant log output

```shell
Fatal error: Uncaught Error: Class "Monolog\Logger" not found in C:\xampp2\htdocs\matomo\core\Log\Logger.php:16 Stack trace: #0 C:\xampp2\htdocs\matomo\vendor\composer\ClassLoader.php(576): include() #1 C:\xampp2\htdocs\matomo\vendor\composer\ClassLoader.php(427): Composer\Autoload\{closure}('C:\\xampp2\\htdoc...') #2 C:\xampp2\htdocs\matomo\core\Log.php(177): Composer\Autoload\ClassLoader->loadClass('Piwik\\Log\\Logge...') #3 C:\xampp2\htdocs\matomo\core\ExceptionHandler.php(143): Piwik\Log::debug(Object(Piwik\Container\ContainerDoesNotExistException)) #4 C:\xampp2\htdocs\matomo\core\ExceptionHandler.php(101): Piwik\ExceptionHandler::getErrorResponse(Object(Piwik\Container\ContainerDoesNotExistException)) #5 C:\xampp2\htdocs\matomo\core\ExceptionHandler.php(42): Piwik\ExceptionHandler::dieWithHtmlErrorPage(Object(Exception)) #6 [internal function]: Piwik\ExceptionHandler::handleException(Object(Exception)) #7 {main} thrown in C:\xampp2\htdocs\matomo\core\Log\Logger.php on line 16

Fatal error: Uncaught Piwik\Container\ContainerDoesNotExistException: The root container has not been created yet. in C:\xampp2\htdocs\matomo\core\Container\StaticContainer.php:44 Stack trace: #0 C:\xampp2\htdocs\matomo\core\Container\StaticContainer.php(85): Piwik\Container\StaticContainer::getContainer() #1 C:\xampp2\htdocs\matomo\core\FrontController.php(277): Piwik\Container\StaticContainer::get('Piwik\\Log\\Logge...') #2 [internal function]: Piwik\FrontController::triggerSafeModeWhenError() #3 {main} thrown in C:\xampp2\htdocs\matomo\core\Container\StaticContainer.php on line 44
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@faizanjaved5 did you run a `composer install` after cloning the repo?
You can find further information how to run Matomo from a git checkout here: https://matomo.org/faq/how-to-install/faq_18271/

**Comment by faizanjaved5** [comment]
> @faizanjaved5 did you run a `composer install` after cloning the repo? You can find further information how to run Matomo from a git checkout here: https://matomo.org/faq/how-to-install/faq_18271/

That worked thanks 👍
