### ISSUE TITLE
Ensure Matomo is functional with PHP 8.4

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#22471]
PHP 8.4 will be released on 21st Nov 2024 and we need to make sure that Matomo will work with this new version of PHP. That means a release needs to have happened by then.

It's still a few months away but figured to already create the issue now so we can schedule the issue in advance for around the time when the first RC releases come out.

**Comment by narfk** [comment]
Just a note:
Starting from PHP 8.4, the functions strtok() and md5() are marked as deprecated. Both functions appear frequently in the Matomo code. This won’t throw any errors but may be logged depending on the configuration.

**Comment by jostreff** [comment]
Fix PHP 8.4 deprecation: Implicitly marking parameter as nullable is deprecated, the explicit nullable type must be used instead - too many such cases in source.

**Comment by jostreff** [comment]
Also I have errors shown like this:

Deprecated: DI\Definition\Resolver\ObjectCreator::setPrivatePropertyValue(): Optional parameter $className declared before required parameter $propertyValue is implicitly treated as a required parameter in /usr/local/www/matomo/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php on line 212

Deprecated: Constant E_STRICT is deprecated in /usr/local/www/matomo/vendor/symfony/var-dumper/Caster/ExceptionCaster.php on line 44

Deprecated: Constant E_STRICT is deprecated in /usr/local/www/matomo/vendor/symfony/var-dumper/Caster/ExceptionCaster.php on line 44

Deprecated: Constant E_STRICT is deprecated in /usr/local/www/matomo/vendor/symfony/var-dumper/Caster/ExceptionCaster.php on line 44

**Comment by jostreff** [comment]
My checks are made with 
PHP 8.4.0RC2 (cli) (built: Oct 16 2024 18:32:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.0RC2, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.0RC2, Copyright (c), by Zend Technologies

**Comment by sgiehl** [comment]
For PHP 8.4 we need to disable the error reporting for deprecation notices. While we were able to update all the deprecation notices caused in our code, we are not able to solve those that happen in the vendor libraries we are using.

Unfortunately we can't update libraries like `php-di/php-di`, as newer versions require at least PHP 8. Same applies for a couple of other libraries. So we may keep deprecation notices disabled for PHP 8.4+ until we dropped support for PHP < 8

**Comment by sgiehl** [comment]
> Just a note:
> Starting from PHP 8.4, the functions strtok() and md5() are marked as deprecated. Both functions appear frequently in the Matomo code. This won’t throw any errors but may be logged depending on the configuration.

Neither `strtok()` nor `md5()` have been deprecated with PHP 8.4. The suggestions to deprecate those methods have been rejected. See https://wiki.php.net/rfc/deprecations_php_8_4

**Comment by jostreff** [comment]
how can I get proposed changes from GitHub?

**Comment by michalkleiner** [comment]
Not sure what you mean exactly @jostreff, can you elaborate?

**Comment by jostreff** [comment]
how to download version with patches for 8.4 compatibility from GitHub?

**Comment by sgiehl** [comment]
@jostreff You can simply checkout the github project. Or is you want to have a Matomo package you can download one of the latest beta releases from https://builds.matomo.org/

**Comment by jostreff** [comment]
Thanks, I have get https://builds.matomo.org/matomo-5.2.0-b5.tar.gz and extracted all files, overwriting my existing installation. The result is that matomo works, but it shows messages like this:

Deprecated: DI\Definition\Resolver\ObjectCreator::setPrivatePropertyValue(): Optional parameter $className declared before required parameter $propertyValue is implicitly treated as a required parameter in /usr/local/www/matomo/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php on line 212

Deprecated: Zend_Db_Statement_Mysqli::_execute(): Implicitly marking parameter $params as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/libs/Zend/Db/Statement/Mysqli.php on line 183

Deprecated: Zend_Db_Statement::execute(): Implicitly marking parameter $params as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/libs/Zend/Db/Statement.php on line 294

Deprecated: Piwik\Updater::__construct(): Implicitly marking parameter $columnsUpdater as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Updater.php on line 64

Deprecated: Piwik\Plugin\Dimension\VisitDimension::shouldForceNewVisit(): Implicitly marking parameter $action as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Plugin/Dimension/VisitDimension.php on line 243

Deprecated: Piwik\CacheId::siteAware(): Implicitly marking parameter $idSites as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/CacheId.php on line 32

Deprecated: Piwik\Plugins\CoreHome\Columns\Metrics\CallableProcessedMetric::__construct(): Implicitly marking parameter $semanticType as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/plugins/CoreHome/Columns/Metrics/CallableProcessedMetric.php on line 22

Deprecated: Piwik\Plugins\Referrers\Columns\Campaign::shouldForceNewVisit(): Implicitly marking parameter $action as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/plugins/Referrers/Columns/Campaign.php on line 37

Deprecated: Piwik\Plugins\Referrers\Columns\Website::shouldForceNewVisit(): Implicitly marking parameter $action as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/plugins/Referrers/Columns/Website.php on line 23

Deprecated: Piwik\Archive\ArchiveInvalidator::getRememberedArchivedReportsThatShouldBeInvalidated(): Implicitly marking parameter $idSite as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 159

Deprecated: Piwik\Archive\ArchiveInvalidator::markArchivesAsInvalidated(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 274

Deprecated: Piwik\Archive\ArchiveInvalidator::addParentPeriodsByYearMonth(): Implicitly marking parameter $originalDate as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 432

Deprecated: Piwik\Archive\ArchiveInvalidator::markArchivesOverlappingRangeAsInvalidated(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 458

Deprecated: Piwik\Archive\ArchiveInvalidator::reArchiveReport(): Implicitly marking parameter $plugin as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 501

Deprecated: Piwik\Archive\ArchiveInvalidator::reArchiveReport(): Implicitly marking parameter $report as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 501

Deprecated: Piwik\Archive\ArchiveInvalidator::reArchiveReport(): Implicitly marking parameter $startDate as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 501

Deprecated: Piwik\Archive\ArchiveInvalidator::reArchiveReport(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 501

Deprecated: Piwik\Archive\ArchiveInvalidator::scheduleReArchiving(): Implicitly marking parameter $pluginName as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 585

Deprecated: Piwik\Archive\ArchiveInvalidator::scheduleReArchiving(): Implicitly marking parameter $startDate as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 585

Deprecated: Piwik\Archive\ArchiveInvalidator::scheduleReArchiving(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 585

Deprecated: Piwik\Archive\ArchiveInvalidator::markArchivesInvalidated(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Archive/ArchiveInvalidator.php on line 722

Deprecated: Piwik\DataAccess\Model::__construct(): Implicitly marking parameter $logger as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/DataAccess/Model.php on line 38

Deprecated: Piwik\DataAccess\Model::updateArchiveAsInvalidated(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/DataAccess/Model.php on line 111

Deprecated: Piwik\DataAccess\Model::updateRangeArchiveAsInvalidated(): Implicitly marking parameter $segment as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/DataAccess/Model.php on line 314

Deprecated: Piwik\Session\SessionAuth::__construct(): Implicitly marking parameter $userModel as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Session/SessionAuth.php on line 49

Deprecated: Piwik\Plugin\Report::getMetricsForTable(): Implicitly marking parameter $report as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Plugin/Report.php on line 1075

Deprecated: Piwik\Plugin\Report::getProcessedMetricsForTable(): Implicitly marking parameter $report as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Plugin/Report.php on line 1107

Deprecated: Piwik\Metrics\Formatter::formatMetrics(): Implicitly marking parameter $report as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/core/Metrics/Formatter.php on line 177

Deprecated: Zend_Exception::__construct(): Implicitly marking parameter $previous as nullable is deprecated, the explicit nullable type must be used instead in /usr/local/www/matomo/libs/Zend/Exception.php on line 43

**Comment by jostreff** [comment]
I forgot to mention also this message:
WARNING: /libs/Zend/Session.php(272): Deprecated - session_set_save_handler(): Providing individual callbacks instead of an object implementing SessionHandlerInterface is deprecated - Matomo 5.1.2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)

**Comment by sgiehl** [comment]
Ah sorry, my fault. I thought we had released a beta after the fixed for PHP 8.4, but it had been released a couple of days before that. You may need to wait for the next beta or preview release, which might happen this or next week.

**Comment by jostreff** [comment]
https://www.php.net/ChangeLog-8.php#8.4.1

no new build published on builds.matomo.org still.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/warning-libs-zend-session-php-272-deprecated-session-set-save-handler/61413/2

**Comment by jostreff** [comment]
Anything? At least new beta version published?

**Comment by sgiehl** [comment]
@jostreff we plan to have a release candidate today/tomorrow and the final release in one or two weeks.

**Comment by jostreff** [comment]
@sgiehl First impressions with 5.2-RC1 under 8.4.1 - it works great!

**Comment by slhck** [comment]
I have run into problems after updating to PHP 8.4 with a system that had `php-imagick` installed. Since the PHP imagick package is not compatible with PHP 8.4 (and apparently not even 8.3), I got these diagnostics errors in the Matomo dashboard:

> 'Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=1&period=day&date=2025-01-09&format=json&trigger=archivephp. Response was \'PHP Warning: PHP Startup: Unable to load dynamic library \'imagick.so\' (tried: /usr/lib/php/20240924/imagick.so (/usr/lib/php/20240924/imagick.so: undefined symbol: php_strtolower), /usr/lib/php/20240924/imagick.so.so (/usr/lib/php/20240924/imagick.so.so: cannot open shared object file: No such file or directory)) …  ... /example.com/wp-content/plugins/matomo/app/vendor/prefixed/php-di/php-di/src/functions.php on line 34\'' '140 total errors during this script execution, please investigate and try and fix these errors.' => ScheduledTasks.php:392; class-wp-hook.php:322; class-wp-hook.php:348; plugin.php:565; wp-cron.php:191

I removed `php-imagick` from the server and restarted Apache/PHP-FPM and hope that it will make everything work again.
