### ISSUE TITLE
[Bug] Bug that different browsers on the same computer access different system versions

### ISSUE THREAD

**Issue by note4** [piwik/piwik#22496]
### What happened?

同一台电脑访问站点，在访客明细中显示的系统版本不一致。
When the same computer accesses the site, the system version displayed in the visitor details is inconsistent.
![recording](https://github.com/user-attachments/assets/55f183b1-9706-41ac-bb5d-9156eb9f46ea)

### What should happen?

如果我们需要用系统作为指标对站点进行优化时，这样的数据错误会误导我们。
If we need to use the system as an indicator to optimize the site, such data errors will mislead us.

### How can this be reproduced?

做了相关尝试，但是在访客明细找不到我的记录。
Made an attempt to do so, but can't find my record in the visitor details.

### Matomo version

5.1.0

### PHP version

7.4.3-4ubuntu2.23

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by note4** [comment]
![image](https://github.com/user-attachments/assets/e53df591-a33f-4d6f-83f1-041f8294598f)
使用第三方查看 UA 信息。
Use a third party to view UA information.

**Comment by sgiehl** [comment]
Hi @note4,

thanks for creating this issue. The detection actually is "correct" in that case, or at least it can't be done better.
Matomo tries to identify the operating system by parsing the user agent. In addition it also looks at the client hints (if they are available).

Windows 11 still sends the same user agent as Windows 10, so it is not possible to detect that correctly based on the user agent.
A browser supporting client hints (like Chrome), will send additional information that Windows 11 is used. So it's currently only possible to detect Windows 11 in browsers that support client hints.

If you want to check what your browser / os is detected as you can visits http://devicedetector.net
