### ISSUE TITLE
[Bug] IOS users on snapchat detected as direct entry

### ISSUE THREAD

**Issue by ohiomichael** [piwik/piwik#22506]
### What happened?

IOS users accessing website from snapchats web browser are reported as a direct entry.

### What should happen?

Users accessing the website from the snapchat browser should be tagged as "Social Network: Snapchat" for user aquisition anylitics. 

### How can this be reproduced?

Bug happens when any IOS user on snapchat clicks a link on a snapchat story.

### Matomo version

5.1.0

### PHP version

8.1.2

### Server operating system

Ubuntu Server 22.04.4 LTS | Apache 2.4.52 (Ubuntu)

### What browsers are you seeing the problem on?

Other

### Computer operating system

IOS

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@ohiomichael if this is the case I would guess that the app suppresses the referrer, hence Matomo can't detect it.
Or does Snapchat maybe provide additional url parameters when clicking a link, which would make it possible to detect it.

**Comment by ohiomichael** [comment]
@sgiehl Yea not quite sure i'm not familiar with matomo but if you got any questions about the bug i can give you answers, a lot of my website traffic comes from snapchat so ive got plenty of incorrect visit entries to share.

**Comment by sgiehl** [comment]
@ohiomichael Sorry, I won't be much of help here. I don't even know how or where you can place custom links on snapchat 🙈 
Maybe someone else, who is more familiar with snapchat can check if there is anything we could improve here.

**Comment by liviuconcioiu** [comment]
Snapchat is tricky when adding links. There's a link icon when you post a story, but depending on links authority it will show or not.

I modified a link with browser inspector on other stories, so I can check the referer, and is blank.

The only way to do this will be to match the `Snapchat` app from device-detector, to Snapchat as social network.

**Comment by sgiehl** [comment]
@liviuconcioiu But I guess if the link isn't opened within the SnapChat app and no referrer is provided, there isn't any possibility to detect that, right? If that is the case, I guess there is nothing we can do.
But it could be possible to append campaign parameters to custom links on snap chat, which would at least end up in campaign tracking. Can't see any other possibility...

**Comment by sgiehl** [comment]
@ohiomichael As outlined there is unfortunately nothing we can change about this, as it's not in our hand which information is passed through from other platforms or applications.
You can only try if campaign tracking works out for you in this case.
