### ISSUE TITLE
[Feature request] Tracking obfuscation so that tracking also works for visitors with AdBlocker

### ISSUE THREAD

**Issue by fbroen** [piwik/piwik#22526]
With well-known ad blockers such as AdBlock or uBlock, visitor trackers such as Matomo are automatically blocked. On the one hand, the blocking is based on checking URLs to see whether they are known URLs or whether parts of the URL contain certain words such as "matomo" or "tracking" etc.

In addition, ad blockers also know the names of the files that trigger tracking in the background and lead to background requests in the browser.

Even if you as an administrator have anonymized the address as best as possible, e.g. t.meine-domain.de, Matomo will still be blocked because the ad blockers also know matomo.js and matomo.php, which are needed for tracking.

It would therefore make sense if these file names could be changed to any name as easily as possible.

Specifically, I would like to have settings options for Matomo to easily change these names and, if necessary, other identification options.

**Comment by sgiehl** [comment]
Hey @fbroen,

Matomo aims to be a privacy friendly tracking solution. We therefor don't aim to (easily) bypass tools that allow users to not get tracked if they don't want to be tracked.

Anyway, there are certain ways to change that on your own if you want. There are some helpful comments in this issue https://github.com/matomo-org/matomo/issues/7364. In addition you should be able to find some more help on this in our forums.

**Comment by fbroen** [comment]
Hey @sgiehl,

I've readed the comments from your linked post but until now the problem is that from 100 visitors have over 80 some blockers enabled. Matomo is useless if it tracks only 20. So the hole statistic i completly wrong and useless.

Like in your linked post commented, there are some other factors like url paramaters what will prevent tracking if uBlock oder Adblock are enabled.

And for example, if I only want to know how much visitors have visited me today and which site, I can't answer that with this wrong statistic. And in my example I don't need any privacy data from the visitor.

I hope you understand my problem and I hope that this problem will be covered.
