### ISSUE TITLE
 UI on iOS needs improvement

### ISSUE THREAD

**Issue by enual** [piwik/piwik#22528]
A user provided a feedback about our Matomo Mobile app. They said that the app is useful but the UI would need some improvement.

**Comment by sgiehl** [comment]
Hey @enual,

Thanks for sharing the feedback. Unfortunately such generalized issues aren't much helpful.
Without some details on what exactly should be improved it's hard to guess that.
If you are able to provide some details, feel free to create an issue here instead: https://github.com/matomo-org/matomo-mobile-2

Thanks!
