### ISSUE TITLE
[Bug] Import of logs is successful but when archive is executed no visits are shown

### ISSUE THREAD

**Issue by fabianboerner** [piwik/piwik#22523]
### What happened?

Execute

/usr/bin/python3 ./import_logs.py --url=https://mywebsite --enable-http-errors --enable-bots --enable-http-redirects --token-auth=xxx--idsite=1 ./some.log 

"50 requests imported to 1 sites"

after "./console core:archive --force-all-websites --url='https://matomo.mysite..com'

nothing is shown in the dashboard.

If i do the same for idsite=2 all visits are shown after this process

### What should happen?

Import to site id 1 should also show all data.

### How can this be reproduced?

Not sure how to reproduce. Install matomo in kuberntes and run the commands against the setup

### Matomo version

5.10.0

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hi @fabianboerner,

In order to sort out possible problems:
Did you check if those imported visits were really tracked? Can you see them in the visits log?
If not they might have been dropped for other reasons. To identify them it could be helpful to activate the debug log for tracking.

**Comment by fabianboerner** [comment]
Im not able to check this, i solved this error by invalidating all logs. It seems Matomo has Problems if the order of the import data sets date is slightly mixed up.

**Comment by sgiehl** [comment]
Matomo should actually automatically invalidate dates in the past as soon as new data is tracked for them. On the day you imported the data, was it data for today, yesterday or older data?

**Comment by fabianboerner** [comment]
it was "today" at the time i tried to import it.

**Comment by sgiehl** [comment]
Interesting, as today should actually always be invalidate automatically. Might it be possible that archiving had run shortly before importing maybe? Archives for today a normally valid for like 15 minutes before they are reprocessed.

**Comment by fabianboerner** [comment]
exactly what i thought but i tried it multiple times with exactly that in mind. I waited and changed also the timing of my manual imports, it did not change anything.

I deleted the database entries. Then tried to reimport, archive until i just invalidated everything and ran archive again. Before the data only showed up in the second page, archive did not ran through the dates after importing for page 1 but for page 2 it did.

I gave the log rotate more time and changed the interval for the import and after that the problem did not occur anymore.

**Comment by des-innocraft** [comment]
@fabianboerner thank you for your reply. Can I confirm, after the reply exchanges with @sgiehl you don't experience the problem anymore?

**Comment by fabianboerner** [comment]
No the problem itself is still there we just didnt had the case anymore that we imported old dates again.

**Comment by sgiehl** [comment]
Thanks for letting us know @fabianboerner. I tried to reproduce that issue locally, but wasn't really able to. Therefor I will close this issue. We have implemented a couple of improvements around invalidation and archiving, which will be included in upcoming Matomo 5.2.0. So hopefully those also sorts our the problem you had.
If you ever come again to the point that you need to import old data, and you see that there is still a problem around the automatic archiving, please create a new issue for that, so we can have a look again.
Thanks!
