### ISSUE TITLE
[Bug] Warnings after update to 5.1.1

### ISSUE THREAD

**Issue by zenzen279** [piwik/piwik#22553]
### What happened?

Just after updating Matomo to 5.1.1 (was on previous one) using the automatic update,
Just after, I started to see new warnings and I don't know where they are from and how to get rid of them.

### What should happen?

No warning at all :)

### How can this be reproduced?

I suppose that the automatic update process was fully tested before deployment.
Below, I put the diagnostic log.

Also, I tried to disable some plugins but no change :(

## The warnings
![2024-09-04 10_58_18-New Issue · matomo-org_matomo — Mozilla Firefox](https://github.com/user-attachments/assets/52c4a74a-a028-451a-87bc-8df19675daca)

#### Version PHP >= 7.2.5:
 ✔ 8.3.10

#### PDO extension:
 ✔ 

#### PDO\MYSQL extension:
 ✔ 

#### MYSQLI extension:
 ✔ 

#### Autres extensions requises:
 ✔ zlib ✔ json ✔ filter ✔ hash ✔ session

#### Fonctions requises:
 ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

#### Configuration PHP requise (php.ini):
 ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR = -1 OR >= 30

#### Répertoires avec les droits d'accès en écriture:
 ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c

#### Répertoires privés requis:
 ✔ Tous les répertoires privés sont inaccessibles depuis Internet.

#### Répertoires privés recommandés:
 ✔ Tous les répertoires privés sont inaccessibles depuis Internet.

#### Binaire PHP 64 bits:
 ✔ 

#### État du traqueur:
 ✔ 

#### Limite mémoire:
 ✔ 2048M

#### Fuseau horaire:
 ✔ 

#### Ouvrir l'URL:
 ✔ curl

#### PageSpeed est désactivé:
 ✔ 

#### GD > 2.x + FreeType (graphics):
 ✔ 

#### Autres extensions:
 ✔ json ✔ libxml ✔ dom ✔ SimpleXML ✔ openssl

#### Autres fonctions:
 ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

#### Système de fichiers:
 ✔ 

#### Paramétrer une tâche Cron - Gestion des processus via la ligne de commande:
 ✔ Ok

#### Dernière exécution d'archivage réussie:
 ✔ Le processus d'archivage s'est terminé avec succès il y a 00:59:20.

#### Capacités de la base de données:
 ✔ UTF8mb4 charset ✔ LOAD DATA INFILE ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level

#### Taille maximale des paquets:
 ✔ 

#### Connexion SSL forcée:
 ✔ 

#### Géolocalisation:
 ✔ geoip2php (continent_code, continent_name, country_code, country_name, region_name, city_name, lat, long)

#### Mettre à jour via HTTPS:
 ✔ 

#### Mobile Messaging SMS Provider:
 not configured

#### Traceur JavaScript inscriptible ("/matomo.js"):
 ✔ 

#### [GoogleAnalyticsImporter] Fonctions PHP requises:
 ✔ 

#### [GoogleAnalyticsImporter] Exécutables requis (php):
 ✔ 

#### [GoogleAnalyticsImporter] Exécutables requis (nohup):
 ✔ 

#### Matomo Version:
 5.1.1

#### Matomo Update History:
 5.0.3,4.16.0,4.15.1,

#### Matomo Install Version:
 4.15.1

#### Latest Available Version:
 5.1.1

#### Is Git Deployment:
 0

#### PHP_OS:
 Linux

#### PHP_BINARY:
 /usr/local/bin/lsphp

#### PHP SAPI:
 litespeed

#### Timezone Version:
 2024.1

#### PHP Timezone:
 UTC

#### PHP Time:
 1725440366

#### PHP Datetime:
 2024-09-04 08:59:26

#### PHP INI max_execution_time:
 7200

#### PHP INI post_max_size:
 512M

#### PHP INI max_input_vars:
 250000

#### Curl Version:
 7.87.0, OpenSSL/1.1.1w

#### Suhosin Installed:
 0

#### DB Prefix:
 matomo_

#### DB Charset:
 utf8mb4

#### DB Adapter:
 PDO\MYSQL

#### MySQL Version:
 10.6.19-MariaDB

#### Num Tables:
 136

#### Browser Segment Archiving Enabled:
 1

#### Development Mode Enabled:
 0

#### Internet Enabled:
 1

#### Multi Server Environment:
 0

#### Auto Update Enabled:
 1

#### Custom User Path:
 0

#### Custom Include Path:
 0

#### Release Channel:
 latest_stable

#### Plugins Activated:
 API, Actions, AdminNotification 5.0.0, Annotations, Bandwidth 5.0.2, BotTracker 5.2.16, BulkTracking, CaptchaHub, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, Feedback, ForceSSL 5.0.1, GeoIp2, Goals, GoogleAnalyticsImporter 5.0.21, Heartbeat, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, JsTrackerInstallCheck, LanguagesManager, Live, Login, Marketplace, MobileAppMeasurable, MobileMessaging, Modern 5.0.4, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, ProfessionalServices, Provider 5.0.3, Proxy, QueuedTracking 5.0.7, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize

#### Plugins Deactivated:
 TagManager

#### Server Info:
 Apache

#### Had visits in last 1 day:
 0

#### Had visits in last 3 days:
 0

#### Had visits in last 5 days:
 0

#### Archive Time Last Started:
 2024-09-04 08:00:03

#### Archive Time Last Finished:
 2024-09-04 08:00:06

#### User Agent:
 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0

#### Browser Language:
 fr,fr-fr,en-us,en

#### Total Invalidation Count:
 0

#### In Progress Invalidation Count:
 0

#### Scheduled Invalidation Count:
 0

#### Number of segment invalidations:
 0

#### Number of plugin invalidations:
 0

#### Do Not Track enabled:
 1

### Matomo version

5.1.1

### PHP version

8.3.10

### Server operating system

Linux

### What browsers are you seeing the problem on?

Microsoft Edge

### Computer operating system

Windows 11

### Relevant log output

```shell
WARNINGS :

WARNING: /core/Plugin.php(316): Warning - Trying to access array offset on null - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CorePluginsAdmin, Action: plugins, In CLI mode: false)

WARNING: /core/Updater.php(433): Deprecated - version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CorePluginsAdmin, Action: plugins, In CLI mode: false)

WARNING: /core/Plugin.php(316): Warning - Trying to access array offset on null - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CorePluginsAdmin, Action: plugins, In CLI mode: false)

WARNING: /core/Plugin.php(316): Warning - Trying to access array offset on null - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreAdminHome, Action: home, In CLI mode: false)

WARNING: /core/Plugin.php(316): Warning - Trying to access array offset on null - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreHome, Action: quickLinks, In CLI mode: false)

WARNING: /core/Plugin.php(316): Warning - Trying to access array offset on null - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreHome, Action: getSystemSummary, In CLI mode: false)

WARNING: /core/Plugin.php(316): Warning - Trying to access array offset on null - Matomo 5.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: RssWidget, Action: rssPiwik, In CLI mode: false)
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@zenzen279 Do those warnings reappear if you close them?

**Comment by zenzen279** [comment]
> @zenzen279 Do those warnings reappear if you close them?

Yes 😣

**Comment by sgiehl** [comment]
Ok. So the line the warning points to gets the version of a certain plugin. Does your plugin admin maybe display any plugin as broken?

**Comment by zenzen279** [comment]
I checked again and I don't have anymore warnings... So the case seems closed.
The reason will stay a mistery but that's a good news.
Thank you for your help @sgiehl .

**Comment by sgiehl** [comment]
@zenzen279 Ok. I'll close this issue then. If those errors might pop up again, please let us know, so we can investigate that further.
