### ISSUE TITLE
Custom reports - Add "Visit ID" in the dimensions list

### ISSUE THREAD

**Issue by marcosciamanna** [piwik/piwik#22556]
## Summary
I didn't find a way to create a custom report that lists the visitors (Visitor IP or Visitor ID), then for each visitor lists the visits (Visit ID), and finally for each visit lists some data (i.e. datetime, action type, and the URL), as the excel attached file.

To create such report, matomo should include the Visit ID in the dimensions list to choose from.

Thanks in advance!

## Your Environment

* Matomo Version: 4.x
* PHP Version: don't know exactly - I'm not the admin/superuser
* Server Operating System:   don't know exactly - I'm not the admin/superuser
* Additionally installed plugins: Premium bundle plugins
[matomo-desired-custom-report.xlsx](https://github.com/user-attachments/files/16884675/matomo-desired-custom-report.xlsx)

**Comment by sgiehl** [comment]
ping @matomo-org/plugin-reviewers

**Comment by AltamashShaikh** [comment]
@marcosciamanna You can select only 3 dimensions in CustomReports, but we do have dimensions called "Visitor ID" and "Visitor IP" to solve your need

![Screenshot from 2024-09-05 12-36-30](https://github.com/user-attachments/assets/6a68d78d-be3f-4d06-b67c-d911ab6cabed)

**Comment by AltamashShaikh** [comment]
@marcosciamanna I am closing this issue, let us know if you still face any issue and since this is related to premium features it would be better you create a support ticket as this repository is for Matomo core issues.

**Comment by marcosciamanna** [comment]
Hi @AltamashShaikh, I'll create the support ticket where you suggested.

Apart from this, I think I didn't understand your previous answer. I need not only the Visitor IDs (or IPs); I need also the Visit IDs, because the aim is to collect data (datetime, action type, page URL, etc.) about every single visit that is generated from the Visitor ID (or IP).

**Comment by marcosciamanna** [comment]
> Hi @AltamashShaikh, I'll create the support ticket where you suggested.

By the way, how could I create the support ticket related to premium features?

**Comment by AltamashShaikh** [comment]
@marcosciamanna You can fill in this [contact form](https://matomo.org/support/) to contact support.
