### ISSUE TITLE
Matomo custom reports: More than 3 dimensions

### ISSUE THREAD

**Issue by klbrnd** [piwik/piwik#22550]
Hi! I would like to include more dimensions in the customised reports. Unfortunately, so far only three dimensions per report are possible.

It would be fantastic if more could be added there. Is that possible?

BR

**Comment by sgiehl** [comment]
@matomo-org/plugin-reviewers  Is one of you able to answer this one?

**Comment by snake14** [comment]
Hi @klbrnd . Thank you for taking the time to create this issue. Sadly, adding the option to use more than the 3 allowed dimensions to the CustomReports plugin likely won't happen any time soon. Doing so would require a fair amount of effort and would further decrease the efficiency of report archiving. I just commented on our internal ticket about adding a fourth dimension that another customer has requested it. If enough customers request it, our Product team will likely make it a higher priority.

**Comment by GreenReaper** [comment]
For others who end up here: [it looks like this might have been made possible recently](https://matomo.org/faq/on-premise/how-do-i-change-the-number-of-dimensions-shown-in-a-custom-report/), e.g.
```
[CustomReports]
custom_reports_max_dimensions = 4
```
