### ISSUE TITLE
[Bug] SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_general_ci,COERCIBLE) and (utf8mb4_uca1400_ai_ci,COERCIBLE) for operation '=' - in plugin Goals.

### ISSUE THREAD

**Issue by LaKanDoR** [piwik/piwik#22566]
### What happened?

1.) normaly i use the daily view, there was no error. 
2.) i switched to monthly view -> "SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_general_ci,COERCIBLE) and (utf8mb4_uca1400_ai_ci,COERCIBLE) for operation '=' - in plugin Goals." 
this message occurs.

### What should happen?

No Error Message.

### How can this be reproduced?

i had changed my website to use the gtranslate (free google translate widget, https://gtranslate.io/) this is causing this bug.
I used every language that is supported.

### Matomo version

5.1.1

### PHP version

8.3

### Server operating system

debian 12.7

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @thE-iNviNciblE, there is already an existing issue for this problem (https://github.com/matomo-org/matomo/issues/22536) so I'll close this one as a duplicate - please follow progress through #22536, there's a PR already linked that should make it to a patch release reasonably soon.
