### ISSUE TITLE
[Bug] Matomo wizard and SSL connections

### ISSUE THREAD

**Issue by perpective2410** [piwik/piwik#22570]
### What happened?

I am trying to setup Matomo on our AKS cluster. We are using [bitnami Chart ](https://github.com/bitnami/charts/tree/main/bitnami/matomo). Matomo is configured to target Azure MySQL Flexible server. MySQL server is configured with [require_secure_transport](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_require_secure_transport) parameter to ON.

We pass Matomo CA certificate as described in the Microsoft [documentation](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/how-to-connect-tls-ssl)

However, the wizard is failing with the following error:

`Could not connect to the database server: Connections using insecure transport are prohibited while --require_secure_transport=ON.`

I have opened an [issue ](https://github.com/bitnami/charts/issues/29287) with bitnami, but I feel like the issue is in this repository.
From what I see [here](https://github.com/matomo-org/matomo/blob/750fdced131a8d2fd3ed30ba06b19506651f4258/plugins/Installation/FormDatabaseSetup.php#L173C5-L173C37), the wizard is trying to call the database with **ssl_enable = false** statically set.

```
$dbInfos = array(
    'host'          => (is_null($host)) ? $host : trim($host),
    'username'      => $this->getSubmitValue('username'),
    'password'      => $password,
    'dbname'        => $dbname,
    'tables_prefix' => (is_null($tables_prefix)) ? $tables_prefix : trim($tables_prefix),
    'adapter'       => $adapter,
    'port'          => Db\Schema::getDefaultPortForSchema($schema),
    'schema'        => $schema,
    'type'          => $this->getSubmitValue('type'),
    'enable_ssl'    => false
);
```

From what I understand, the wizard is currently not supporting SSL connections. Could you please confirm?

### What should happen?

The wizard should work with SSL connections

### How can this be reproduced?

SImply setup Mysql server with SSL connection enabled.

### Matomo version

5.1.1

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @florentvaldelievre 
This is indeed not possible. By now you can only switch to SSL once Matomo was installed.
See https://github.com/matomo-org/matomo/issues/16404
