### ISSUE TITLE
[Bug] Campaign Tracking in Dashboard - Incorrect total yearly value for campaign names

### ISSUE THREAD

**Issue by pixelbrackets** [piwik/piwik#22591]
### What happened?

* I added the widget »acquisition campaigns - campain names« to the dashboard
* I checked the number of visits of campaigns for each month
  * A test campaign showed for january until september: 0, 0, 0, 7, 11, 7, 0, 0, 0 visitors
* Then switched to check the number of visits for the whole year
  * The test campaign shows a total value of 7 visitors - expected is 25

### What should happen?

* Calculate the correct number of visits for a campaign name for the selected year

### How can this be reproduced?

* Open Dashboard
* Add the widget »acquisition campaigns - campain names«
* Check the number of visits of a campaign for each month
* Change the selected timerange from month to year - widget calculates to low total values

However: I do not have the same problem in a different instance for another client with the same setup (Matomo version, PHP version, OS, …). So this bug has to be caused by a different reason, which is yet unknown.

### Matomo version

5.1.1 (Update history 5.0.3,4.16.1,4.15.0)

### PHP version

8.1.29

### Server operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Ubuntu Linux

### Relevant log output

```
./console diagnostics:run
There are no problems with your Matomo setup. Give yourself a pat on the back.
```

### Related information

It looks like a smiliar issue existed for the visitor count wiget a long time ago: https://github.com/matomo-org/matomo/issues/15170#issuecomment-562905289

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by randy-innocraft** [comment]
Hi @pixelbrackets,
Thanks for reporting this issue. Is the issue still occurring for you?
Unfortunately, we're unable to reproduce the problem. Is there any other info that you could provide that would help us reproduce the problem?

**Comment by pixelbrackets** [comment]
I'm afraid not. As stated above, I do not have the same problem in a different instance for another client with the same setup (same Matomo version, PHP version, OS version, …). I had hoped that this issue might be similar to #15170 and have an obvious cause. Unfortunately, this is probably not the case and requires a more comprehensive analysis to identify the cause. :( So its okay for me to abondon the issue for now since it's not reproducable.
