### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by enual** [piwik/piwik#22608]
### What happened?

A user has experienced a fatal error in Matomo after installing Bot tracker, and clicked the link in the error to get the message emailed to us.

Here is the error: 
syntax error, unexpected 'string' (T_STRING), expecting function
(T_FUNCTION) or const (T_CONST) in
/var/www/matomo/plugins/BotTracker/Controller.php 23 using PHP
7.2.26-1+ubuntu16.04.1+deb.sury.org+1

### What should happen?

na

### How can this be reproduced?

na

### Matomo version

 5.1.1

### PHP version

7.2.26

### Server operating system

Ubuntu 16.04.1

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @enual, it looks like there might be a bug in the Bot Tracker plugin itself. It would be best to report the issue in the plugin's issue tracker at https://github.com/Digitalist-Open-Cloud/Matomo-Plugin-BotTracker as this is not a Matomo plugin.
