### ISSUE TITLE
[Bug] Windows Server IIS new install 500 Internal Server Error

### ISSUE THREAD

**Issue by PercentageCorporation** [piwik/piwik#22628]
### What happened?

I have installed the latest Matomo download on two WIndows Servers (2016 and 2022) running IIS 10 and have the same problem on each one. I get a 500 Internal Server Error when I try to go to the site.
This was a standard download install (not for WP). WordPress is running on both servers and PHP works fine. I can run phpinfo from the Matomo sites. I cannot find any logs that would help identify the issue.

### What should happen?

new installations

### How can this be reproduced?

http://matomo.percentagecontrols.com

### Matomo version

5.1.2

### PHP version

7.1.19  and 8.2.7

### Server operating system

Windows server 2016 and 2022

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Computer operating system

Windows 10

### Relevant log output

```shell
Can't find any
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by PercentageCorporation** [comment]
I ran matomo.php and piwik.php on the sites.
On one site I still get the 500 error, on the other site (2012) I get the following:

As Matomo is not installed yet, the Tracking API cannot proceed and will exit without error.

**Comment by sgiehl** [comment]
Hey @PercentageCorporation,

Sorry to hear you are having trouble setting up Matomo. It most likely seems to be some sort of server configuration issue.
Unfortunately we are not able to provide support for this type of issues here on GitHub, as we use this issue tracker only for bug reports and feature requests.

Please try to find some help on our forum at https://forum.matomo.org or try reaching out to our support
