### ISSUE TITLE
Forcing collation to be utf8mb3_general_ci?

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#22634]
As of Matomo 5.1.2, collation is set to be utf8mb3_general_ci in config for the database. How is this impacting Matomo in general?

* Is the collation now forced to be set to utf8mb3_general_ci?
* What happens if the collation is forced in config and the console task core:convert-to-utf8mb4 has not been runned?

**Comment by sgiehl** [comment]
Hi @mikkeschiren,

Thanks for taking the time to create the report.
The collation needs to be written to the configuration as relying on the database default collation caused problems with the newest versions of MariaDb.
The collation can be, in theory, set to whatever you want, but it should match the collation of the tables in your database.
It's generally used when creating the database connection and when creating new database tables.

The command to convert the database wasn't adjusted yet, so it currently might actually break things, unless you update the config manually after running that command.
We will try to provide a fix for that asap.
