### ISSUE TITLE
[Bug] Session recording HTML strips out some classes

### ISSUE THREAD

**Issue by smerriman** [piwik/piwik#22651]
### What happened?

When viewing a session recording, some CSS is not being applied. When debugging by inspecting the iframe that Matomo has generated, I noticed the HTML has some of the class names stripped.

### What should happen?

The session recording HTML should use the same CSS classes as the actual website.

### How can this be reproduced?

I don't have specific steps to replicate, but here are two screenshots of the result:

- the first is inspecting the Matomo session recording:
![matomo](https://github.com/user-attachments/assets/db05dcec-5001-45cc-979a-e984c371ec70)

- the second is the source code of the [actual URL](https://store.titanabrasive.com/collections/portable-blast-machine-packages/products/titan-u300-portable-blast-machine) being recorded
![website](https://github.com/user-attachments/assets/9d3b3905-efeb-487b-8284-cc2db04a711a)

You can see the `rte product-single__description` and `hiddendescription` classes have been removed from the recording, which results in the preview being rendered incorrectly.

### Matomo version

Matomo Cloud

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by AltamashShaikh** [comment]
@smerriman Thanks for the report, I can confirm this bug and this is due to our XSS check which is matching `script` in `description` and removing that attribute, we need to improve this check.

Also this repository is for Matomo core and HeatmapandSessionRecording is a premium feature, will you please create a Matomo Support request for this, ?
You can reach out to them on [shop@matomo.org](mailto:shop@matomo.org)

**Comment by smerriman** [comment]
Thanks, will do so. I hunted for quite a while and couldn't find a support email address; the support form within Matomo didn't support images, had a very short character limit, and after I finally squeezed in a message, said an error occurred and deleted everything I wrote, so this seemed the most appropriate place.

Will forward this thread onto that email now that I know where to send it.

**Comment by AltamashShaikh** [comment]
Released v5.1.7 of the plugin with a fix
