### ISSUE TITLE
[Bug] Unable to use IPv6 database server

### ISSUE THREAD

**Issue by cwchristerw** [piwik/piwik#22677]
### What happened?

 I'm trying to install Matomo in Docker container with using MariaDB that has IPv6 address. I'll get following error message in Web UI. "Could not connect to the database server: SQLSTATE[HY000] [2002] Failed to parse IPv6 address "[fd80:3306"

Database Address:
`[fd80:deaf:1::95]`

### What should happen?

It should be possible to use IPv6 address in database address.

### How can this be reproduced?

1. Go to https://analytics.example.com/index.php?action=databaseSetup&clientProtocol=https
2. Add Database server settings with database address that is IPv6 address.

### Matomo version

5.1.2

### PHP version

8.2.24

### Server operating system

Debian

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Linux Mint

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by randy-innocraft** [comment]
Hi @cwchristerw. Thank you for creating the issue and bringing this to our attention, that's very appreciated. We have reviewed and triaged the problem internally, and we have confirmed it is an issue. Our team will prioritise this, and we will update you on the progress here when we have an update to share. If you have any further information or questions, please feel free to add them here.

**Comment by cwchristerw** [comment]
Thank you for your response, I'll be waiting. I'll use IPv4 temporarily until then. :smile:
