### ISSUE TITLE
Matomo can't see custom variable

### ISSUE THREAD

**Issue by analyticskislist** [piwik/piwik#22708]
Hi,
I am in the process of configuring analytics using Matomo Tag Manager, and my Debug View is not detecting custom events that look like this:

```javascript
window._mtm.push({'event': 'purchase', 'orderTotal': {{purchase.amountWhole}}});
``` 
Without this event being visible, I am unable to track order values, which is a key function needed for analyzing the results of our efforts. Please help.

**Comment by sgiehl** [comment]
@AltamashShaikh @snake14 Can you help here? This seems to be a tagmanager problem/question.

**Comment by snake14** [comment]
@analyticskislist Unless you have a Trigger configured to listed to that specific event, I don't think you'll see it in the Debug View, as mentioned in [the developer documenation](https://developer.matomo.org/guides/tagmanager/datalayer#triggering-an-event). Also, I'm not sure if `_mtm` supports `{{}}` variable notation. I see a syntax error in the JS console when I try to execute it. Do you have that purchase amount value stored in a JavaScript variable or dataLayer? If so, you should be able to use that when triggering the event.

**Comment by sgiehl** [comment]
@analyticskislist I hope your question has been answered.

For further questions/requests around this or similar topics, please try to find some help on our forum (https://forum.matomo.org) first or get in touch with our support.
We are using the issue trackers on GitHub only for feature requests and bug reports.
Cheers,
