### ISSUE TITLE
Matomo On-Premise download states 5.2.0 in Changelog

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#22760]
Link: <https://matomo.org/faq/on-premise/installing-matomo/>

## Problem
Download latest Matomo (5.1.2 in this case), unzip.
Changelog should reflect the version, while downloading 5.1.2, the Changelog says it is version 5.2.0.

## Solution

Changelog should reflect the version downloaded.

**Comment by randy-innocraft** [comment]
Hi @mikkeschiren . Thank you for creating the issue and bringing this to our attention, that's very appreciated. We have reviewed and triaged the problem internally, and we have confirmed it is an issue. Our team will prioritise this, and we will update you on the progress here when we have an update to share. If you have any further information or questions, please feel free to add them here.

**Comment by sgiehl** [comment]
Hey @mikkeschiren,

Thanks for letting us know. That change was initially planned to be part of Matomo 5.2.0, but was then already included in 5.1.0. Seems we forgot to adjust the changelog accordingly. I'll prepare a PR to fix that.
