### ISSUE TITLE
[Bug] Error recieved when trying to view a visitor profile

### ISSUE THREAD

**Issue by jonbellard** [piwik/piwik#22761]
### What happened?

When i'm trying to view a visitor profile i get an error stating the following:

"Error: An exception has been thrown during the rendering of a template ("Unable to write in the cache directory (/var/www/html/tmp/templates_c/f3).")."

### What should happen?

I should be able to view the visitor profile without error. 

### How can this be reproduced?

Click view visitor profile. 

### Matomo version

5.1.2

### PHP version

8.2.19

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by des-innocraft** [comment]
Hi @jonbellard thank you for raising this ticket and we are happy to help. 

We have an FAQ page that can help you with this issue --> https://matomo.org/faq/how-to/faq_35627/ . Can you try the steps on this page to update the permission within Matomo directory and see if it solves your issue?

**Comment by sgiehl** [comment]
@jonbellard I hope the above mentioned FAQ helped you solving your issue.
I will close this issue here, as this is not a general problem within Matomo, but more likely a server specific issue you need to solve yourself.
If you need further assistance, feel free to reach out on our forums at https://forum.matomo.org
