### ISSUE TITLE
[Bug] Wrong range shown in e-mail reports

### ISSUE THREAD

**Issue by JVC-MSF** [piwik/piwik#22790]
### What happened?

I have define a Personal e-mail report to be sent daily.

When I receive it in the morning, the range show the right  range.

But when I click in the "Send report now" link, I receive the report with the right data, but in the range it has only today date.

### What should happen?

I expect to have the right range shown in the report, even if I ask for having it sent manually.

### How can this be reproduced?

* When in the dashboard
* Click on _Administration_ (the wheel in the top right corner)
* Click on _Personal_ (in the left menu)
* Click on Email Reports
* Click in the _Send report now_ link in any report you have defined there
* Check the received e-mail, the range attribute will show today's date

### Matomo version

5.2.0

### PHP version

8.2.24

### Server operating system

Debian 12

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Debian 12

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @JVC-MSF,

This is expected behavior. The `Send report now` button will trigger to send the report for the date/period that is currently selected in the date picker. The report should also contain the data for that period.

**Comment by JVC-MSF** [comment]
Thanks for the feedback.

I find it counterintuitive, but if this is how it is, nothing to say.

**Comment by sgiehl** [comment]
I agree that it might not necessarily be what everyone expects and there already have been a couple of reports around this topic. Improving the UI so it's more clear what to expect from this feature will at some point be handled with https://github.com/matomo-org/matomo/issues/19674
