### ISSUE TITLE
[Bug] Categorize visits coming from Perplexity AI as 'Search Engine' instead of 'Website'

### ISSUE THREAD

**Issue by kslstn** [piwik/piwik#22807]
### What happened?

Visits via perplexity.ai are listed under Acquisition > Websites. 

### What should happen?

As Perplexity AI is described as a search engine (and is arguably even more so than ChatGPT, which already is considered a 'Search Engine' in Matomo), it would be easier to compare stats with other search engines, if Perplexity AI is listed among the other search engines under Acquisition > Search Engines & Keywords. 

### How can this be reproduced?

Go to Acquisition > Websites. 

### Matomo version

5.1.2

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@kslstn Makes sense to add that.
Can you provide the exact referrer url(s), Perplexity AI is using, that are listed in your reports?

**Comment by liviuconcioiu** [comment]
@sgiehl, `Perplexity` is already added in this PR https://github.com/matomo-org/searchengine-and-social-list/pull/104, but it needs to be merged.

**Comment by sgiehl** [comment]
This has been fixed with the merge of https://github.com/matomo-org/searchengine-and-social-list/pull/104
Note: Only new perplexity referrers will then be detected as search engines. Already existing visits won't be updated.
