### ISSUE TITLE
[Bug] PHP 8.4 Deprecated

### ISSUE THREAD

**Issue by patrickvandenhoek** [piwik/piwik#22829]
### What happened?

WARNING: /plugins/CoreUpdater/Controller.php(54): Deprecated - Piwik\Plugins\CoreUpdater\Controller::__construct(): Implicitly marking parameter $marketplacePlugins as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: newVersionAvailable, In CLI mode: false)
×
WARNING: /plugins/CoreUpdater/Controller.php(54): Deprecated - Piwik\Plugins\CoreUpdater\Controller::__construct(): Implicitly marking parameter $marketplacePlugins as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: newVersionAvailable, In CLI mode: false)
×
WARNING: /plugins/CoreUpdater/Controller.php(54): Deprecated - Piwik\Plugins\CoreUpdater\Controller::__construct(): Implicitly marking parameter $marketplacePlugins as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: getUpdaterCss, In CLI mode: false)
×
WARNING: /vendor/wikimedia/less.php/lib/Less/Functions.php(12): Deprecated - Less_Functions::__construct(): Implicitly marking parameter $currentFileInfo as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: getUpdaterCss, In CLI mode: false)
×
WARNING: /plugins/CoreUpdater/Controller.php(54): Deprecated - Piwik\Plugins\CoreUpdater\Controller::__construct(): Implicitly marking parameter $marketplacePlugins as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: oneClickUpdate, In CLI mode: false)
×
WARNING: /core/ArchiveProcessor/Rules.php(256): Deprecated - Piwik\ArchiveProcessor\Rules::isRequestAuthorizedToArchive(): Implicitly marking parameter $params as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: oneClickUpdate, In CLI mode: false)
×
WARNING: /core/ArchiveProcessor/Rules.php(335): Deprecated - Piwik\ArchiveProcessor\Rules::getSelectableDoneFlagValues(): Implicitly marking parameter $params as nullable is deprecated, the explicit nullable type must be used instead - Matomo 5.2.0-b5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: oneClickUpdate, In CLI mode: false)

### What should happen?

Fix compatibility for PHP 8.4...

### How can this be reproduced?

All over the place

### Matomo version

5.2.0-rc1

### PHP version

8.4

### Server operating system

Ubuntu

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@patrickvandenhoek Might it be possible that those error happened during update? I have checked the code and they seem to be fixed in 5.2.0-rc1.

**Comment by patrickvdhoek** [comment]
You are absolutely right @sgiehl ! I've refreshed all pages and now the deprecated messages are gone.
Sorry. How do I close this ticket?

**Comment by sgiehl** [comment]
Thx for letting us know. I've closed the issue

**Comment by williamdes** [comment]
> @patrickvandenhoek Might it be possible that those error happened during update? I have checked the code and they seem to be fixed in 5.2.0-rc1.

Not the less.php ones
Since for now it is locked below this version: https://github.com/wikimedia/less.php/blob/master/CHANGES.md#v512

PR done: https://github.com/matomo-org/matomo/pull/22858
