### ISSUE TITLE
Fatal error: Argument #1 ($string) must be of type string in ClientHints.php:285

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#22846]
PHP Fatal error: Uncaught TypeError: trim(): Argument matomo-org/device-detector#1 ($string) must be of type string, null given in matomo/device-detector/ClientHints.php:285

And second PHP fatal error: PHP Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, null given in /var/www/html/vendor/matomo/device-detector/ClientHints.php:297 Stack trace: #0 

This happens a few times per hour.

PHP: 8.2 

Backtrace:

> PHP Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, null given in /var/www/html/vendor/matomo/device-detector/ClientHints.php:285 Stack trace: #0 /var/www/html/vendor/matomo/device-detector/ClientHints.php(285): trim() #1 /var/www/html/core/DeviceDetector/DeviceDetectorFactory.php(46): DeviceDetector\ClientHints::factory() #2 /var/www/html/core/DeviceDetector/DeviceDetectorFactory.php(29): Piwik\DeviceDetector\DeviceDetectorFactory::getNormalizedUserAgent() #3 /var/www/html/core/Tracker/VisitExcluded.php(199): Piwik\DeviceDetector\DeviceDetectorFactory->makeInstance() #4 /var/www/html/core/Tracker/VisitExcluded.php(73): Piwik\Tracker\VisitExcluded->isNonHumanBot() #5 /var/www/html/plugins/CoreHome/Tracker/VisitRequestProcessor.php(104): Piwik\Tracker\VisitExcluded->isExcluded() #6 /var/www/html/core/Tracker/Visit.php(164): Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor->processRequestParams() #7 /var/www/html/core/Tracker.php(171): Piwik\Tracker\Visit->handle() #8 /var/www/html/core/Tracker/Handler.php(55): Piwik\Tracker->trackRequest() #9 /var/www/html/core/Tracker.php(151): Piwik\Tracker\Handler->process() #10 /var/www/html/core/Tracker.php(126): Piwik\Tracker->track() #11 /var/www/html/piwik.php(73): Piwik\Tracker->main() #12 /var/www/html/matomo.php(14): include('...') #13 {main} thrown in /var/www/html/vendor/matomo/device-detector/ClientHints.php on line 285

Second problem
> PHP Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, null given in /var/www/html/vendor/matomo/device-detector/ClientHints.php:297 Stack trace: #0 /var/www/html/vendor/matomo/device-detector/ClientHints.php(297): trim() #1 /var/www/html/core/DeviceDetector/DeviceDetectorFactory.php(46): DeviceDetector\ClientHints::factory() #2 /var/www/html/core/DeviceDetector/DeviceDetectorFactory.php(29): Piwik\DeviceDetector\DeviceDetectorFactory::getNormalizedUserAgent() #3 /var/www/html/core/Tracker/VisitExcluded.php(199): Piwik\DeviceDetector\DeviceDetectorFactory->makeInstance() #4 /var/www/html/core/Tracker/VisitExcluded.php(73): Piwik\Tracker\VisitExcluded->isNonHumanBot() #5 /var/www/html/plugins/CoreHome/Tracker/VisitRequestProcessor.php(104): Piwik\Tracker\VisitExcluded->isExcluded() #6 /var/www/html/core/Tracker/Visit.php(164): Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor->processRequestParams() #7 /var/www/html/core/Tracker.php(171): Piwik\Tracker\Visit->handle() #8 /var/www/html/core/Tracker/Handler.php(55): Piwik\Tracker->trackRequest() #9 /var/www/html/core/Tracker.php(151): Piwik\Tracker\Handler->process() #10 /var/www/html/core/Tracker.php(126): Piwik\Tracker->track() #11 /var/www/html/piwik.php(73): Piwik\Tracker->main() #12 /var/www/html/matomo.php(14): include('...') #13 {main} thrown in /var/www/html/vendor/matomo/device-detector/ClientHints.php on line 297

**Comment by liviuconcioiu** [comment]
It was also reported here https://github.com/matomo-org/device-detector/issues/7916.

There are bots/libraries that will send `NULL` for the user-agent and other client hints headers. I think it should be fixed in device-detector.
