### ISSUE TITLE
[Bug] Translator.php(202): Warning - Undefined array key 1

### ISSUE THREAD

**Issue by jorgeuos** [piwik/piwik#22853]
### What happened?

It's been reported to me from my client and I can verify that I see the same error across various installations and it's spamming our logs.

I saw that warning already before 5.2.0, but it's still there.

```
WARNING CoreHome[2024-12-13 12:02:09 UTC] [12316] /var/www/html/core/Translation/Translator.php(202): Warning - Undefined array key 1 - Matomo 5.2.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) #0/core/Translation/Translator.php(202),#1/core/AssetManager.php(147),#2/core/Twig.php(231),#3/tmp/templates_c/9b/9bcdbc324b7372161ba12b6ad9eb6285.php(43),#4/vendor/twig/twig/src/Template.php(360),#5/tmp/templates_c/b3/b35accd563c963c7f8a6fbee91f567bb.php(137),#6/vendor/twig/twig/src/Template.php(430),#7/vendor/twig/twig/src/Template.php(492),#8/tmp/templates_c/f9/f91be83f44d125f542a7d6c7c5b11fc0.php(68),#9/vendor/twig/twig/src/Template.php(430)
```

I haven't seen any issues reported on this, so I thought I'll create a new one.

Regards, Jorge

### What should happen?

This warning should not be present in the logs.

### How can this be reproduced?

See the logs for warnings.

### Matomo version

5.0.2

### PHP version

php 8.2-fpm

### Server operating system

Docker php:8.2-fpm-alpine

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Mac

### Relevant log output

```shell
WARNING CoreHome[2024-12-13 12:02:09 UTC] [12316] /var/www/html/core/Translation/Translator.php(202): Warning - Undefined array key 1 - Matomo 5.2.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) #0/core/Translation/Translator.php(202),#1/core/AssetManager.php(147),#2/core/Twig.php(231),#3/tmp/templates_c/9b/9bcdbc324b7372161ba12b6ad9eb6285.php(43),#4/vendor/twig/twig/src/Template.php(360),#5/tmp/templates_c/b3/b35accd563c963c7f8a6fbee91f567bb.php(137),#6/vendor/twig/twig/src/Template.php(430),#7/vendor/twig/twig/src/Template.php(492),#8/tmp/templates_c/f9/f91be83f44d125f542a7d6c7c5b11fc0.php(68),#9/vendor/twig/twig/src/Template.php(430)
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@jorgeuos Are they maybe using any custom plugins? The warning might be thrown when a translation key is added to client side translations that does NOT contain a `_`.
We can for sure add some code to discard such unexpected values, and log a warning instead, but it might nevertheless be good to check if we can find the origin.

**Comment by jorgeuos** [comment]
Ah, good point!

I'll check by disabling all plugins and re-activate them one by one.

Thanks for the swift reply!

**Comment by jorgeuos** [comment]
Ok, I figured out the issue.

A custom contrib plugin that I was using had a menu item like this:
```php
<?php
/**
 * Piwik - free/libre analytics platform
 *
 * @link https://matomo.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Piwik\Plugins\PluginName;

use Piwik\Menu\MenuAdmin;
use Piwik\Piwik;

class Menu extends \Piwik\Plugin\Menu
{

    public function configureAdminMenu(MenuAdmin $menu)
    {
        if (Piwik::hasUserSuperUserAccess()) {
            $menu->addItem('Menu name', "Do some magic", $this->urlForAction('performAction'));
        }
    }
}
```

Which for some reason runs a check, with the plugin "LanguagesManager".

I'm guessing they didn't want to use translations and thought they could pass a string into the `$menu->addItem($menuName)`.

From the `addItem` description, the `$menuName` can hold either a string or a translation token.

Resulting in this confusion.


```php
    /**
     * Adds a new entry to the menu.
     *
     * @param string $menuName The menu's category name. **Can be** a translation token.
     * @param string $subMenuName The menu item's name. Can be a translation token.
     * @param string|array $url The URL the admin menu entry should link to, or an array of query parameters
     *                          that can be used to build the URL.
     * @param int $order The order hint.
     * @param bool|string $tooltip An optional tooltip to display or false to display the tooltip.
     * @param bool|string $icon An icon classname, such as "icon-add". Only supported by admin menu
     * @param bool|string $onclick Will execute the on click handler instead of executing the link. Only supported by admin menu.
     * @param string $attribute Will add this string as a link attribute.
     * @param bool|string $help Will display a help icon that will pop a notification with help information.
     * @param int $badgeCount If non-zero then a badge will be overlaid on the icon showing the provided count
     * @since 2.7.0
     * @api
     */
    public function addItem(
        $menuName,
        $subMenuName,
        $url,
        $order = 50,
        $tooltip = false,
        $icon = false,
        $onclick = false,
        $attribute = false,
        $help = false,
        $badgeCount = 0
    )
```

The easy fix, use a translation key.

Long term solution: either force a translation key or allow strings.

**Comment by sgiehl** [comment]
@jorgeuos Thanks for posting the code. The PR I've already set up should prevent the error you were initially seeing.
As string should still be allowed for menu items, I'll prepare another PR to ensure that they are not automatically added to the client side translations.
