### ISSUE TITLE
Add Metric Definitions on Hover for eCommerce Report Table Metrics in Matomo Analytics

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#22864]
Hi Team,

I am not sure, but this should be an easy fix.

Steps to reproduce

- Open an eCommerce report table in Matomo Analytics. For example: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Goals_Ecommerce&subcategory=Goals_Products
- Hover over any metric in the table to check for a definition tooltip.

What I got:
- No definition is displayed when hovering over the metrics in the eCommerce report table.

What I expected instead:
Consistent behavior with other reports (like Behaviour or Acquisition), where hovering over a metric shows its definition in a tooltip, providing better clarity for users.

https://github.com/user-attachments/assets/f95080e4-f04a-4864-befc-4751acb0466a

**Comment by des-innocraft** [comment]
@Chardonneaur Thank you for bringing this enhancement request. We have an existing ticket about implementing tooltips to add metric definition to various analytics report including  eCommerce report table.  We'll close this issue and use the existing ticket for implementing metric definition to various analytics reports. https://github.com/matomo-org/matomo/issues/17230
