### ISSUE TITLE
Add 'tooltips' to Event report columns

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#22883]
When the _Behaviour > Event_ reports are set to '_Display a table with Visitor engagement metrics_' these include metrics for "Visits" and "Unique Visitors".
e.g.
![image](https://github.com/user-attachments/assets/aff40759-0af8-4129-9aa6-13e57355f7a8)

![image](https://github.com/user-attachments/assets/baddc286-e1b2-441a-9e05-03cce7344959)

These metrics are actually the sum of all visits. The table is summing each of the subtable rows into a total. 
This makes the visit numbers look inflated when compared to the visit numbers for that day.
![image](https://github.com/user-attachments/assets/aae5bc16-2f2b-4d94-a861-104f09ddbf14)
vs
![image](https://github.com/user-attachments/assets/df4fca1e-2fec-4773-831e-2f2cff0b2734)

This causes confusion when comparing the too.

There are no 'tool tips' or any indication of what the metrics in the Events report are based on. 
It would be good to have some information displayed for these metrics when hovering over the column headings that explains this, as seen in other reports.

For example,
![image](https://github.com/user-attachments/assets/4acf7592-e29e-4c60-802a-f34b53a25674)

**Comment by des-innocraft** [comment]
Hi @goochj03 , thank you for raising this enhancement ticket. Currently we have an existing enhancement ticket to update all tooltips on various reports to inform users about the data displayed specially the various metrics and computations. I'll close this issue for now and will just refer the existing ticket for the overall enhancement of tooltips.
