### ISSUE TITLE
[Bug] Error when creating a funnel in Matomo

### ISSUE THREAD

**Issue by Lordoftests** [piwik/piwik#22897]
### What happened?

When filling all the necessary fields this is the error I get
![image](https://github.com/user-attachments/assets/bc038e72-a792-47f7-9f6e-d8bb6c52e3ff)
**Mysqli prepare error: Unknown column 'name' in 'field list'**

### What should happen?

A funnel should be created

### How can this be reproduced?

Funnels -> "Add a new Funnel" -> Fill the fields -> Press "Add Funnel"

### Matomo version

5.1.0

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by Lordoftests** [comment]
Any help please ?

**Comment by AltamashShaikh** [comment]
@Lordoftests It seems you haven't ran the migration, which adds this new column in the table
running `./console core:update` should fix the issue, or you can alter the table manually by running this SQL query `ALTER TABLE matomo_funnel ADD name VARCHAR(50) NOT NULL AFTER revision;`.

Adjust the table name based on your setup.

**Comment by AltamashShaikh** [comment]
@Lordoftests I am closing this issue, since its a premium feature you should contact Matomo support as this repository is only for issues with Matomo core.
