### ISSUE TITLE
SEO Report average keyword position for google keywords

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#2466]
In a percentage of requests from google, google gives the ranking of the result on the search page. 

We currently parse this ranking and display it in the Live! or Visitor Log when we have it. (see function getKeywordPosition() in plugins/Live/Visitor.php) 

It could be interesting to, add a new field in log_visit to keep track of this ranking when it is passed, and add a new column in the keyword report "Average position" of keyword.

**Comment by sgiehl** [comment]
Guess we can close this issue, as keyword positions can now be imported using https://plugins.piwik.org/SearchEngineKeywordsPerformance

**Comment by mattab** [comment]
:+1: see: https://piwik.org/docs/search-engine-keywords-performance/#keywords-position-in-search-engine-over-time
