### ISSUE TITLE
Allow to plot custom variable values (or any rows) by searching & plotting - JS Graphs

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#2786]
At the custom variable section, when you select to show them as graphs, there is only one graph that shows the name of the variables used. 

What I suggest is to generate one graph for each custom variable, so the data shown will be from its values.
Keywords: custom variables, graphs

**Comment by mattab** [comment]
Feedback from @rugk in #8507

> The [custom variables] (https://developer.piwik.org/guides/tracking-javascript-guide#custom-variables) are all in one graph - no matter what you do. In the table view this may be okay, because you can unfold the name  of the variable and see the results.
But if you select a graph (e.g. a pie chart) at the bottom it at first displays the percentage of the variable names (so the 'category'). E.g. if you have two variable names gender and category (like it's shown on the dev page) both of them will be placed in the pie chart and you will e.g. get: 45% gender, 55% category. That's useless!

> However you can make the report 'flat' so you won't have these foldings. After this you can also see the category values, but it's still in one chart. In the example it would be: 30 % gender - male, 30 % gender - female, 15% Category - Europe, 25% Category - Sports.
It even does not matter in what slot/index the variable is saved. It's still all in one graph.

> This makes pie charts of specific variables practically useless.

> I cannot see a direct relation to these issues, but maybe they are related: https://github.com/piwik/piwik/issues/6762, https://github.com/piwik/piwik/issues/6031

**Comment by mattab** [comment]
note: with [custom dimensions](https://piwik.org/docs/custom-dimensions/)  available from the Marketplace https://plugins.piwik.org/CustomDimensions it is now possible to plot values of any custom dimensions as Pie chart or bar plot. Another benefit of using custom dimensions over custom variables.

**Comment by mattab** [comment]
As we will deprecate custom variables in #11524, closing this issue as Won't fix.

We now recommend to use [Custom Dimensions](https://piwik.org/docs/custom-dimensions/) instead.
