### ISSUE TITLE
Two factor authentication login

### ISSUE THREAD

**Issue by robocoder** [piwik/piwik#2846]
Proposing Yubico integration initially since I already have a Yubikey.

Can look into other vendors later.

**Comment by finchapps** [comment]
This should be back in the roadmap!

**Comment by MagicFab** [comment]
Other free open source implementations of this exist, this reminds me of this [2FA plugin for WordPress](https://wordpress.org/plugins/google-authenticator/), very nicely implemented.

**Comment by strobeltobias** [comment]
Two factor authentication for Piwik would be awesome! Especially the data of website visitors would be better protected against hackers.
Maybe a Yubikey integration would also be possible. I live great with this gadget!

**Comment by robocoder** [comment]
There are ways to approach this:
1) 2fa is enabled for everyone, so the pin is input on the same form as the user+password
2) 2fa is enabled per user, so requires an intermediate pin page

**Comment by sgiehl** [comment]
There is now a plugin for GoogleAuthenticator. See http://plugins.piwik.org/GoogleAuthenticator

**Comment by robocoder** [comment]
@sgiehl : how hard to allow API requests without the auth_code?

**Comment by sgiehl** [comment]
Guess we would need to add app specific passwords or something like that.
Otherwise a login would be possible using token_auth in the url only

**Comment by mattab** [comment]
@sgiehl  Well done, this looks epic. It is an excellent news for the Piwik community :rocket:

**Comment by MagicFab** [comment]
@sgiehl app-specific passwords: https://github.com/piwik/piwik/issues/6559

I believe we can now close this one?

**Comment by mattab** [comment]
I guess the issue can be closed and all further requests regarding two factor auth can go into the plugin github repository: https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator

@sgiehl I'll let you the pleasure the close it :tada:
