### ISSUE TITLE
Support BrowserID login authentication in Piwik

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#2970]
browserid is a new fantastic protocol that will provide authentication the way it should be done: protecting everyone privacy.

I believe we should add support to BrowserID in Piwik before 2.0.

There is an example php implementation at: https://github.com/mozilla/browserid-cookbook/blob/master/php/browserid.php

It looks simple to implement. Apparently, the way I understand it is that we would add a "browser id login" link on the login form, that would open a popup from browserid.org (until browsers implement it), which would authenticate using the email address.

**Comment by lioman** [comment]
@mattab: could be closed! Persona (BrowserID) is discontinued.
