### ISSUE TITLE
Archive.php should log in the system timezone.

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#3029]
All other logs are using the system timezone (syslog, nginx, php, etc...). Having piwik logging in its own timezone makes things difficult to debug.
Keywords: timezone archive

**Comment by gaydenko** [comment]
I"m the next voting the suggestion. Logs are something presented for people :) Logic and presentation are separate concerns, I guess...

**Comment by valmiRe** [comment]
Hi all, I was wondering if there is a problem with the archive process mixing UTC and local timezone.
My timezone is UTC+1, the process logs in UTC, but the last line below is confusing, it mixes UTC (13:18:38) and local timezone (14:30:02)

logs extract of 2 last core:archive runs :
```
[....]
INFO [2016-01-04 13:18:38] done
INFO [2016-01-04 13:18:38] ---------------------------
INFO [2016-01-04 13:30:01] ---------------------------
INFO [2016-01-04 13:30:01] INIT
INFO [2016-01-04 13:30:01] Running Piwik 2.15.0 as Super User
[....]
INFO [2016-01-04 13:30:02] START
INFO [2016-01-04 13:30:02] Starting Piwik reports archiving...
INFO [2016-01-04 13:30:02] - tracking data found for website id 1 (between 2016-01-04 13:18:38 and 2016-01-04 14:30:02)
```

**Comment by mattab** [comment]
HI @valmiRe could you please create a separate issue for this bug?

**Comment by valmiRe** [comment]
hi @mattab, it's done here #9653
