### ISSUE TITLE
custom regex works outside of Piwik but not in log_import.py

### ISSUE THREAD

**Issue by fogelfish** [piwik/piwik#311]
This is a hitch I encountered while working on a solution to ticket 5252 (I opened this a couple weeks ago at http://dev.piwik.org/trac/ticket/5252).  I have a custom regex that works **outside** of Piwik but it does not return a match when used in the import_logs.py script.

An example log line is:
```
92.224.96.192 - - [24/May/2014:23:59:51 -0700] "GET /path/to/resource/image.GIF HTTP/1.1" 200 6652 "http://subdomain.obscured.com/path/to/folder/" "Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17" i=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9; t=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9
```
The custom regex is:
```
(?P<host>[\w\-\.]*)(?::\d+)?[\s-]+\[(?P<date>.*?)[\s-]+(?P<timezone>.*?)\][\s]+"(?P<request>.*?)[\s]+(?P<path>.*?)[\s]+(?P<protocol>[\w\/\.]*)"[\s]+(?P<status>[\d]*)[\s]+(?P<bytes>[\d|-]*)[\s]+"(?P<url>.*?)"[\s]+"(?P<user_agent>.*?)"[\s]+(?:.*)i=(?:[\w]*)(?::[\w]*);[\s]+(?:.*t=(?!.*t=)(?P<sessionid>[\w]*))
```
I'm not sure what's going wrong... probably has to do with encoding/decoding.  The script changes the log line to unicode.  Here it is at the point where the match is tried at ```match = format.match(line)```
```
u'92.224.96.192 - - [24/May/2014:23:59:51 -0700] "GET /books/howmany/firefightingaddition/3small.GIF HTTP/1.1" 200 6652 "http://members.enchantedlearning.com/books/howmany/firefightingaddition/" "Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17" i=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9; t=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9
'
```
Which ```--encoding``` flag should I use to prevent this from happening?  My test log has been saved as ASCII (ISO-8859-1).

**Comment by mattab** [comment]
Hi @fogelfish thanks for the report. 

I'm closing it as we now keep track of log importer bugs in another issue tracker. Would you mind creating this issue in the Log importer tracker? https://github.com/piwik/piwik-log-analytics/issues 

Cheers
