### ISSUE TITLE
Provide a shorter parameter for campaign name/keyword tracking (_pkc _pkd ?)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#3111]
Then update URL builder, documentation, FAQs.

**Comment by sgiehl** [comment]
We now have `pk_cpn` and `pk_kwd` and everyone has the option to overwrite that config and add even shorter ones. Should we still add shorter ones or close this issue?

**Comment by mattab** [comment]
Looks good, nothing to do I reckon
