### ISSUE TITLE
Make Piwik opt-out feature work on safari and internet explorer

### ISSUE THREAD

**Issue by ryrun** [piwik/piwik#3135]
Iframe dont work with internet explorer and safari, when piwik is hosted on a different domain. Its not possible to uncheck the checkbox. Browser wont set the needed cookie.

Solution for IE:
Add following to your .htaccess(create one, when needed) in your piwik folder:
header append P3P "CP=\"CAO PSA OUR\""  (thx to MuX512 for this)

Maybe the iframe could send this via php:
header('P3P: CP="CAO PSA OUR"');

For Safari we need another method to set the cookie:
Safari block every cookie from pages, which wasn't "clicked"/opened from user.

German forum thread about this:
http://forum.piwik.org/read.php?5,71496

Tested some suggestions, the "_top" method dont work for safari ...

**Comment by alex-gulentz** [comment]
Hey Guys,

the most important features of Piwik are: Privacy protection and complaint with the privacy regulation of the European Union. The opt-out is a very important feature there, because the opt-out is requested i.e. by the German law!

I would like to ask you to increase the importance of this Issue and start solving this.

Can this be possible?

Br, Alex

**Comment by diosmosis** [comment]
After some testing, everything appears to work on IE7/8/9. I can confirm it's broken for Safari.

**Comment by alex-gulentz** [comment]
Is there any timeline when this Issue will be solved? It is very important! 
@mattab could you schedule this fix?

**Comment by diosmosis** [comment]
It is scheduled for 2.14.0 (as you can see in the Milestone section on the right). I've assigned myself to fix it.

**Comment by Cruiser13** [comment]
This issue does still exist for me with Piwik 2.14.3 and Internet Explorer 11 if third party cookies are disabled.

**Comment by mattab** [comment]
@Cruiser13 thanks for the report. Created an issue: https://github.com/piwik/piwik/issues/8578
