### ISSUE TITLE
Goals conversion : url encoding problem

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#3146]
Hello,
I have a goal tracking clics on an external link which downloads a file. The filenames can have special characters like "spaces".

The goal is set with the encoded URL copied directly from the site like "my%20file%20link.pdf". With this encoded filename, the goal is never converted. With the non-encoded filename like "my file link.pdf", it's converted.

Maybe Piwik should handle this use case and convert goals even with encoded URLs.

**Comment by mattab** [comment]
it's a 2.5 year old bug and this time decided to tackle it and it took 20min
