### ISSUE TITLE
Support for POST in Piwik_Http::sendHttpRequest

### ISSUE THREAD

**Issue by JulienMoumne** [piwik/piwik#3325]
Piwik_Http::sendHttpRequest does not currently support [the POST method](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5).

Required by #2708 to go around a Clockwork limitation.

**Comment by tsteur** [comment]
I'll need it for the Marketplace. Need to see if I can add it to all different handlers
