### ISSUE TITLE
List of Scheduled reports: add "View Reports Across All Websites" feature

### ISSUE THREAD

**Issue by JulienMoumne** [piwik/piwik#3336]
It would be useful for a user to see at once all the scheduled reports across all websites.

In the screen, the website selector moves from being displayed on the right, to being displayed in the content of the page.

The option "Filter reports to the website [ WEBSITE SELECTOR ]" is displayed.

By default, it show reports created for this website.

User can click on site selector and select "Show reports for all websites".

**Comment by mattab** [comment]
Duplicated in https://github.com/piwik/piwik/issues/7076
