### ISSUE TITLE
Static graphs: display Browser, OS, Plugin and Screen icons in legend

### ISSUE THREAD

**Issue by julienmoumne** [piwik/piwik#3395]
pChart2 does not currently support drawing GIF files in the legend.

Here are two options to circumvent this limitation:
- convert all GIF files to PNG
- patch pChart2

We have managed so far not to patch pChart2 source code. It seems converting icons to PNG is the best way to go.

**Comment by mattab** [comment]
I saw that this is now done, probably we added this months ago. see for example: https://raw.githubusercontent.com/piwik/piwik/3.x-dev/tests/PHPUnit/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
