### ISSUE TITLE
In archiving process, truncate datatables in-place everywhere this can result in speed gains

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#3484]
Most of Piwik when archiving will generate DataTables and then apply a sort and truncation filter before storing them as records. This is highly inefficient when dealing w/ DataTables w/ thousands of rows, since every one of those rows will have to be first allocated & constructed then sorted.

As done in the Actions plugin it is possible to apply ordering through the SQL and then use new DataTable functions to limit the number of rows in a DataTable w/o having to create and sort every possible one. This technique should be used everywhere possible.

**Comment by mattab** [comment]
This issue was fixed in 2.12.0!
