### ISSUE TITLE
New Report: the Top IP Addresses

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#3613]
This was requested a few times over the years by email and in the forums. 

We could process a new simple report: the top 100 (or 500) IP adresses with: number of actions, bounce rate, etc.

This would help find bots, automated requests, or discover bugs in the tracking or other things.

I propose a new report, available only to the Super User and Admin user, displayed in Visitors>Ip Adresses.

Thoughts?

**Comment by sgiehl** [comment]
Just released a small plugin providing such an report: https://plugins.piwik.org/IPReports
