### ISSUE TITLE
Segmenting fails if keyword is a URL

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#3639]
For example, if you click "Year" for "Date Range" and then choose to display "500" keywords on the Dashboard, the following keyword is displayed (which is actually a URL) about halfway down the list: 

http://forum.piwik.org/read.php?2,94978,94982#msg-94982

This is the demo URL which shows the filtering doesn't work: 

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=year&date=2012-12-20#module=Live&action=getVisitorLog&idSite=7&period=year&date=2012-12-20&segment=referrerKeyword==http%3A%2F%2Fforum.piwik.org%2Fread.php%3F2%2C94978%2C94982%23msg-94982

**Comment by mattab** [comment]
Works in modern piwik eg. http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=year&date=2012-12-20&segment=referrerKeyword%3D%3Dhttp%253A%252F%252Fforum.piwik.org%252Fread.php%253F2%252C95803#/module=Referrers&action=getSearchEnginesAndKeywords&idSite=7&period=year&date=2012-12-20&segment=referrerKeyword==http%253A%252F%252Fforum.piwik.org%252Fread.php%253F2%252C95803
