### ISSUE TITLE
import_logs.py needs upgrade to Python 3 or updated shebang line

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#3759]
Some distributions like Arch have `/usr/bin/python` point to `python3`, not Python 2.x. [Even more popular distributions are transitioning to do the same thing](https://wiki.ubuntu.com/Python/3). Currently, the `import-logs.py` script does not work under Python 3. As such, either it should be updated to support Python 3, either its shebang line should be changed to `#!/usr/bin/python2` instead of assuming that `/usr/bin/python` is Python 2.x.
Keywords: log-analytics, python

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
