### ISSUE TITLE
Defined goal could not be tracked with hash-sign (#)

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#3863]
If a target definition contains a "#" character (hash), this goal is no longer tracked.

works in 1.9.2
dont works in 1.11.1
Keywords: goal, hash, #

**Comment by mattab** [comment]
I tested and it works  to trigger a Goal conversion when page URL matches eg. `http://localhost/#test` - if it fails to track a goal on "Outlink click", maybe it's likely due to #6244
