### ISSUE TITLE
New segment 'language'

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#3950]
We should have a segment for "user language". Maybe this involves rewriting the data and storing only one language, instead of storing the whole string as we do now in location_browser_lang

**Comment by oussjarrouse** [comment]
:+1: 
I believe it is a very important feature to have and I hope it will be included in your next release

**Comment by fnagel** [comment]
+1

**Comment by mattab** [comment]
now that we store only one language in the DB field (#5365)  this can be done quite easily I think :+1: 
@sgiehl maybe you want to take a crack at it
