### ISSUE TITLE
Deprecate UserSettings plugin -> use DeviceDetection instead!

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#3962]
In Piwik 1.12 we added the DevicesDetection plugin to provide advanced user detection of mobile devices, tvs, consoles, brands, models, Operating systems versions, etc. The code is still beta and we know covers only 50-80% of all devices. 

Now that this plugin works well, we note redundancy between DevicesDetection algorithm and UserSettings. 

eg the Following reports are processed and displayed in both plugins:
* Browsers report (and browser versions)
* Operating System report (and OS versions)

**Tasks**
Here is how to solve the redundancy and make code unified.

general

API: 
* the Following UserSettings.* API will be redirected from UserSettings to their equivalent in DevicesDetection  (to keep backward compatibility)
  * getOS
  * getOSFamily
  * getMobileVsDesktop (now loads  DevicesDetection.getType )
  * getBrowserVersion
  * getBrowserType
  * getBrowser
* Remove code processing of these reports from UserSettings/Archiver

Core:
* Enable DevicesDetection by default (add new Update file to enable plugin). 
  * Officially out of beta!

Tests & Backward compatibility
* If users re-process reports from the "old logs" (when UserSettings alone was doing detection), do the reports processed by DevicesDetection using old data display OK ? 
* If users migrate to Piwik 2.0 and use DevicesDetection for the first time
  * We must ensure that old UserSettings blobs are renamed to DevicesDetection names ([example](https://github.com/piwik/piwik/blob/master/core/Updates/2.0-a13.php#L27)). So that the UserSettings blobs are read and used by DevicesDetection API.

Tracker: 
* remove the current UserAgentParser code to simplify Tracker (in getUserSettingsInformation())
  * If DevicesDetection plugin is disabled, there will not be any browsers or OS detected 
 
At the end of this ticket we will see:
* UserSettings plugin will be simpler
* DevicesDetection plugin becomes critical part of Piwik architecture (by providing browsers/os parsing exclusively)
* Simplification of Tracker in core  
* Consistent reports (browsers/OS only displayed once as expected) 
* Keep backward compatibility in terms of API and also DevicesDection can read old UserSettings blob data.
  * Better detection accuracy for most users (since they will now use DevicesDetection)

See also: Help improve DevicesDetection plugin: see piwik/device-detector#4215

**Comment by sgiehl** [comment]
All reports and API methods are moved now. Last remaining part is the page template showing the reports

**Comment by mattab** [comment]
Nice work @sgiehl - it would be nice to get it done in 2.11.0 and this would successfully conclude this project! :)

**Comment by sgiehl** [comment]
Hm. I'm not sure where to move the template displaying the various reports.
Should I move it to CoreHome and dynamically add  the reports using an event or something like that?

**Comment by mattab** [comment]
Not sure how this should be solved but it seems good use case for the platform, to let plugins enrich existing reports with their data.  ideally we would provide a nice API for plugins to compose report pages.

 * Maybe we could add events similar to http://developer.piwik.org/api-reference/events#controllermoduleaction but that would be for Twig templates, where other plugins could "append" string content to it? 
 * maybe better idea could be to  replace the current way of creating reports eg. in Usersettings `$view->dataTableResolution = $this->renderReport(new GetResolution());`.  Maybe we could introduce a new object for "Composite reports" (eg. a page in Piwik made of several reports). This object would let plugins add or modify reports to it, setting order, maybe right/left column, etc.?

Thoughts?

**Comment by sgiehl** [comment]
I'm not sure how to solve that best. Maybe we should reorganize the technical reports.

We currently have:
- Devices
  - Device type
  - Device brand
  - Device model
  - Browser (Versions)
  - OS (Versions)
  - Browser engine
- Visitor settings
  - Resolution
  - Configurations (OS / Browser / Resolution)
  - Browser plugins
  - Browser language

I don't think that this splitting makes much sense. Maybe something like that would fit more:
- Devices
  - Device type
  - Device brand
  - Device model
- Browser & Operating System
  - Browser (Versions)
  - OS (Versions)
  - Browser engine
  - Resolution
  - Browser plugins

I would maybe remove the Configurations completely or make it available as widget only. Not sure if that report is useful at all.
The browser language reports could be moved to location reports maybe, as it is more related there.

**Comment by mattab** [comment]
> Maybe something like that would fit more:

maybe we could also move "Resolution" into "Devices" ?

> Browser & Operating System 

we need to find shorter name so it fits in the sub-menu... do you maybe have an idea? 

> I would maybe remove the Configurations completely or make it available as widget only. Not sure if that report is useful at all.

it's a useful report, some users have mentioned using it before (in the forums and in the tracker). Although maybe we could move this feature into a plugin that would be on the Marketplace rather than in core?

>  The browser language reports could be moved to location reports maybe, as it is more related there.

:+1:

**Comment by mattab** [comment]
Hi @sgiehl the UserSettings plugin looks now quite "deprecated" and almost empty. maybe we close this issue and create smaller follow up issue?

**Comment by sgiehl** [comment]
Yes. Let's create follow ups.
