### ISSUE TITLE
Redirecting after login, to the original target

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#3963]
It would be very handy to have also in piwik the possibility to directly use a deeplink "through" the BE login page.

e.g.
for pointing colleagues or customers to a special statistic (page)

To that there should be a redirection path like this:
deeplink => Login Page => log in => restored deeplink

since it is implemented in several softwares e.g. Magento it should be possible somehow.

A further enhancement would be to show the "direct acess" url for direct copying and sending to colleagues or customers on pages like the saved segment filters. Like youtube does for their videos...
(should I open a second ticket for this?)

**Comment by hpvd** [comment]
hmm am I the only one who could uses such a feature several times a week?
(see use-cases above)

**Comment by mattab** [comment]
Hi @hpvd does it work maybe in 2.12.0? #7432 Make direct links work even if login is required [by @sgiehl]

**Comment by hpvd** [comment]
aaaaahhh yes!!! First tests are positive!! seem to work with latest piwik. Thank you!
What a fortunate coincidence that I've posted here again 9 days after fix.
Without I would have probably waited forever...

**Comment by mattab** [comment]
great!
