### ISSUE TITLE
Add "Download file URL" and "Outlink URL" segments

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4103]
I'm experiencing this issue in 1.12, and it was confirmed by matt on this forum thread:

http://forum.piwik.org/read.php?2,84935,105947#msg-105947

I'm trying to setup a custom segment filtering Downloads to show only mp4 files. When viewing all visits, there are dozens, but when I add a custom segment setting the Page URL contains '.mp4' I get zero results. I'm using the fancy segment UI to build the segment, but obviously something is not working right. One other point of note is that I'm loading all of my data from Apache log files, rather than JavaScript using the included python script.

**Comment by bugsland** [comment]
Hi, 
What about using "Goals" as described in this article: http://www.elysiumsecurity.com/blog/Guides/post8.html
Not ideal, more complex than it should be, and only works on new "hits" but at least it gives you some detailed logs through segments reports/filtering. Could there be an option for the goal to apply to old/existing data?

**Comment by mattab** [comment]
* when this is implemented, will it be possible to create a segment to limit the visitor log to visitors that downloaded any content? it was asked [in the forum](http://forum.piwik.org/read.php?2,127451) - maybe `&segment=downloadUrl!=` would work.

**Comment by mattab** [comment]
Once we have these segments, we will be able to add "Segmented Visitor Log" icon to let us see all users who downloaded a particular file. Refs #7212

**Comment by mattab** [comment]
> Once we have these segments, we will be able to add "Segmented Visitor Log" icon to let us see all users who downloaded a particular file. Refs #7212

Awesome-ly,  the icon is automatically displayed in the report after the segments were created in the action dimensions, so I didn't need to do anything to support this feature

**Comment by mattab** [comment]
PR: #8910
