### ISSUE TITLE
Number format thousands, decimal, abbreviate large numbers  l10n

### ISSUE THREAD

**Issue by gka** [piwik/piwik#4114]
For sites with a lot of visits the numbers at some point get really hard to read. So instead of "22990872 visits" why not show "22.99 mio visits"?

**Comment by mattab** [comment]
FYI: Number formatting is finally implemented in Piwik in #8857 :heart:

**Comment by sgiehl** [comment]
Can we close this, or are there stills tasks open for improving number formats?

**Comment by mattab** [comment]
Well done Stefan!
