### ISSUE TITLE
Import Google keywords from Webmaster tools in Piwik?

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4185]
Since Google is now putting all visitors on SSL, the keywords are no longer available to any web analytics software. Google gives access to the keyword data via Webmaster Tools. 

It would be great to export daily the search keyword data from GWT API, and import it into Piwik. Even though we would not know the visitor level detail, it would be interesting and relevant to integrate it in the existing Search Keywords report.

**Comment by ReessKennedy** [comment]
Is there a plugin for this now? Free or premium?

**Comment by sgiehl** [comment]
not as far as I know

**Comment by corebyte** [comment]
+1

**Comment by sgiehl** [comment]
There is now a premium plugin available that let's you import keywords from Google and Bing/Yahoo:
https://plugins.piwik.org/SearchEngineKeywordsPerformance

**Comment by mattab** [comment]
Some years ago most search engines decided to hide keywords from the referrer urls, which made it impossible for web analytics tools to report reliable keyword statistics. Using the premium Search Keywords Performance Monitor plugin you can now get back powerful insights into how your audience searches on Google, Bing and Yahoo!

Which queries caused your website to appear in search results? Which queries result in more traffic to your website than others? The plugin adds new reports to your Piwik which give you the exact list of all keywords searched by users on these search engines. You can finally go beyond the “keyword not defined” issue and get deep SEO insights in Piwik. Learn more about the features and benefits of Search Keywords Performance.

Once you have configured the Google and/or Bing+Yahoo! Search Keywords imports for a website in Piwik, two new reports will be available:

* Referrers > Search Keywords
* Referrers > Crawling overview

More information: [Search Engine Keywords Performance Piwik](https://piwik.org/docs/search-engine-keywords-performance/)

**Comment by borgmark** [comment]
We are currently making use of the SearchEngineKeywordsPerformance plugin and we are successfully importing stats from Google Search Console. 

At this stage we would like to know whether it is possible to capture 2 different google properties (mob and desktop) under 1 PIWIK site profile. We are assuming that you cannot because under the site profile you can only select 1 Google property from the drop-down.

Mark

**Comment by sgiehl** [comment]
@borgmark  no, you need to do that under different sites. But if you want to have combined results, you can create a property in Google Search Console that combines those two properties and use that one in Piwik.

**Comment by mattab** [comment]
Created a new FAQ for this: [ How do I import Google keywords from multiple websites/domains into one Piwik website?](https://piwik.org/faq/search-engine-keywords-performance/faq_25054/)

**Comment by borgmark** [comment]
Thanks for the quick response guys !!
