### ISSUE TITLE
Install Trac vote plugin

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4236]
Trac contains dozens of very cool ideas. We do our best to sort the ideas by priority. Sometimes though we do not realize how popular a feature or bug can be. 

To allow Piwik users and community to let us know which bugs are important, we could use a simple VOTE mechanism. For example this plugin: http://trac-hacks.org/wiki/VotePlugin

Then we could see which tickets have the most votes and are most popular... (maybe we need to create a trac report for this)

**Comment by sgiehl** [comment]
@mat Guess this one can be closed, as we are not using trac anymore? Or do we still want to use some kind of external tool to provide a voting feature?

**Comment by mattab** [comment]
Tracked @ Github in: https://github.com/isaacs/github/issues/9 but unfortunately they haven't done anything yet
