### ISSUE TITLE
Marketplace - Check translation files when importing a new plugin version

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#4245]
In case a plugin translation file contains a not valid formatted JSON we trigger an exception in Piwik meaning Piwik is not really usable in case a plugin contains invalid JSON.

When importing a new plugin version we should check all translation files for json errors and if an error is found, abort the import and notify plugin developer about the issue.

**Comment by mattab** [comment]
Users will have noticed this in their local Piwik when working on the plugin so shouldn't be needed I think
