### ISSUE TITLE
Display Location-City on visitorLog-page

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4406]
hi,

since i'm patching this on every new update and found it quite useful to see the location city without hoovering over the flag or so, i added a row in the template showing the location city provided by geoIP.
in addition to that i added a link to google-maps incl. showing long/lat position...

see patch attached to ticket...

cheers,
chris
Keywords: Location City visitorLog

**Comment by hpvd** [comment]
still open and wanted in 2.15

**Comment by mattab** [comment]
duplicated in https://github.com/piwik/piwik/issues/9705
