### ISSUE TITLE
Run all automated tests with HipHop Virtual Machine - make build green 

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#4415]
The goal of this ticket is to try to make all our unit + plugins + integration tests pass when Piwik runs HHVM virtual machine. This would lead to CPU performance improvements as well as potentially some improvements in memory usage.

Follows up #4706, #4604 

What is HHMV?

HHVM is a new open-source virtual machine designed for executing programs written in PHP. HHVM uses a just-in-time compilation approach to achieve superior performance while maintaining the flexibility and ease of use that PHP developers are accustomed to (dynamic features like eval(), rapid run-edit-debug cycle, etc).

HHVM is used by Facebook to serve billions of web requests per day. To date, HHVM (and its predecessor HPHPc before it) has realized over a 9x increase in web request throughput and over a 5x reduction in memory consumption for Facebook compared with the Zend PHP 5.2 engine + APC.

**Comment by mattab** [comment]
We likely won't run the automated tests suite on HHVM as our build times and number of build jobs is very precious (since we often need to wait for those builds etc.). We can reopen if it changes in the future
