### ISSUE TITLE
optimize export function for show and export customized tables

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#4446]
there is already a great function to export each table in different formats
(button at the bottom left)

would be very great to enhance this function a little
like it's available at other places e.g. for magento backend data

for making it
- even more user friendly and
- making it possible to use it for two purposes:

-- watching a customized/selected part of the data only and
-- directly export what you are seeing (with the already available formats..) / see what you are exporting

0) do not directly export (at button click), but show the table first 

1) make the columns to show/export selectable
=> e.g. via a button to open a lightbox with a list of all possible columns (simply the ones which are directly exported at the moment) where each could be selected via checkbox

2) make it possible to sort the data by clicking on the head of the table (sort is limited to the numbers of rows shown on the site; this function is already be there: dropdown bottom right)

enhancements
3) make the order of the columns also customizable e.g. by providing a field in each column below the head to put in a number for its position

4) save the settings of the selected columns for each table for every piwik user

**Comment by mattab** [comment]
We likely won't implement something as advanced, but there are some improvements being made in https://github.com/piwik/piwik/pull/11958
