### ISSUE TITLE
Improve UI of Goals Overview report, when Ecommerce is enabled

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#4460]
When Ecommerce is enabled, in Goals Overview report:
* Add clean labelling of ecommerce VS normal goal 

----
e.g.
by 

1) clarification of the used syntax:

there are
- "conversions of defined goals"
- "conversions of ecommerce goal"
and both together may be named
"total conversions"

3) adding the headlines:
- total conversion
- ecommerce

4) giving the info how many conversion the overall ecommerce revenue contains

5) showing at load in the graph the total conversions

**Comment by tsteur** [comment]
Can we close this one since they are separated now?

**Comment by mattab** [comment]
done in https://github.com/piwik/piwik/pull/6944 https://github.com/piwik/piwik/issues/6022
