### ISSUE TITLE
log import hangs in in non deterministic way

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4472]
In my setup I use log import to load data into piwik. Everything seems to go well except for the fact that sometimes (and it doesn't seem to be repeatable) one of recorder threads hangs and the rest of the threads wait on futex.

For example - main process:

# strace -p 24643
Process 24643 attached - interrupt to quit
select(0, NULL, NULL, NULL, {0, 819826}) = 0 (Timeout)
gettimeofday({1388734405, 12820}, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0}^C &lt;unfinished ...>
Process 24643 detached

Hung thread:
# strace -p 24646
Process 24646 attached - interrupt to quit
recvmsg(6, ^C &lt;unfinished ...>
Process 24646 detached

Rest of the threads (all look alike):
# strace -p 24645
Process 24645 attached - interrupt to quit
futex(0x7f8028001540, FUTEX_WAIT_PRIVATE, 0, NULL^C &lt;unfinished ...>
Process 24645 detached

I tried to add a thread dump capability to the import_logs.py and so I got:
One of waiting threads (all are identical):
# Thread: Thread-13(139637655840512)
File: "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.6/threading.py", line 484, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/SVN/scripts/piwik/import_logs.py", line 1167, in _run_bulk
  hits = self.queue.get()
File: "/usr/lib64/python2.6/Queue.py", line 168, in get
  self.not_empty.wait()
File: "/usr/lib64/python2.6/threading.py", line 239, in wait
  waiter.acquire()

Hung thread (I assume, that's the only one different):

# Thread: Thread-7(139638058493696)
File: "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.6/threading.py", line 484, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/SVN/scripts/piwik/import_logs.py", line 1170, in _run_bulk
  self._record_hits(hits)

Main process:

# Thread: Thread-1(139638191130368)
File: "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.6/threading.py", line 484, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/SVN/scripts/piwik/import_logs.py", line 820, in _monitor
  time.sleep(config.options.show_progress_delay)

As far as I know it used to occur in 1.12 (although it used to be less frequent, I think) and occurs in 2.0.2 as well.

My installation works on CentOS 6.4
# rpm -qa | grep python
python-ethtool-0.6-3.el6.x86_64
python-libs-2.6.6-37.el6_4.x86_64
python-setuptools-0.6.10-3.el6.noarch
python-devel-2.6.6-37.el6_4.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python-dateutil-1.4.1-6.el6.noarch
python-urlgrabber-3.9.1-8.el6.noarch
python-pycurl-7.19.0-8.el6.x86_64
rpm-python-4.8.0-32.el6.x86_64
python-2.6.6-37.el6_4.x86_64
python-pip-1.3.1-4.el6.noarch
newt-python-0.52.11-3.el6.x86_64
libxml2-python-2.7.6-12.el6_4.1.x86_64
libproxy-python-0.3.0-4.el6_3.x86_64

Keywords: log import

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
