### ISSUE TITLE
use consistent colours for fonts and buttons

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#4495]
#4457 talks about consistent font types.
To complete this we should look for consistent colours for fonts and buttons both -hover and -not hover too.
Please see attachments for examples

**Comment by mnapoli** [comment]
@mattab maybe we should close this issue, we have done some progress on this and there are issues opened about this anyway?

**Comment by mattab** [comment]
@mnapoli sounds good

@hpvd please create new issue if you have some design feedback / suggestion on 2.14.0 beta version :+1:
