### ISSUE TITLE
Ability to restrict user login to specific IP  addresses

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4577]
For added security, it would be useful to be able to only allow particular users to login from white listed IP addresses.
- "Restrict login to Piwik only from these IP addresses" would be a global setting that would restrict all logins to a particular IP address.
- "Restrict a particular username to login from these IP addresses" would be a setting, per user, optional, that would restrict login by this username.
  - UI: maybe we could extend the 'User Settings' mechanism , to also let Super User edit settings for other users.

Notes:
- When a user goes to the login form, or tries to login, and the IP is not whitelisted, display a message "Access to this Piwik server is restricted. Please contact the admin to ask them to white list your IP address. [more](Learn)"
  - Learn more link goes to a FAQ on Piwik.org, explaining the WhiteList feature, and also explaining "How do I disable IP whitelisting?"
  - This would help a Super User deactivate the IP white listing feature, if he is locked out.
- UI: Ips will accept ranges, similarly to the "Ips to exclude" in the Websites settings.

**Comment by mattab** [comment]
Added new FAQ: [How do I restrict viewing the analytics reports to one or more whitelisted IP addresses or IP ranges?](https://piwik.org/faq/how-to/faq_25543/)

Fixed in https://github.com/piwik/piwik/pull/12242

**Comment by robertharm** [comment]
Thanks for adding this useful feature. As I maintain a site where anonynmous access to dashboard is allowed, login is restricted for specific users only, it would be great if this feature could be enhanced to restrict the display of the login form only - currently this has to be done via vhost-config, which isnt the most usable way:
```
<LocationMatch /piwik/.*Login.*>
Order deny, allow
Allow from .....
</LocationMatch>
```

**Comment by robertharm** [comment]
@mattab just discovered that if `login_whitelist_ip` is set, WordPress backend cannot be accessed if Piwik plugin is active & features from "show statistics" tab are enabled. If you disable e.g. "Dashboard graph:", you can access the backend, the Piwik plugin settings page is still unaccessible if you have not whitelisted the IP too.

So in my opinion securing the login form only would be a better solution as this would not break the Piwik WordPress plugin for other users not whitelisted.

**Comment by mattab** [comment]
@robertharm Thanks for the feedback. Could you please create a new issue to note your various suggestions? as we'd like to follow up but this issue is closed. thanks

**Comment by RajveerSinghBrar** [comment]
please help if i want to setup my account to login from a particular IP address how its done?

**Comment by zhconsultancyservices** [comment]
ANy update on this

**Comment by sgiehl** [comment]
As mentioned above see this FAQ: https://matomo.org/faq/how-to/faq_25543/

**Comment by mddvul22** [comment]
Sorry for commenting in an old issue, but the original post mentioned the possibility of restricting _a particular username_ to login from certain IP addresses.  The FAQ doesn't mention this capability.  I assume that feature was not added and that the only option for IP-based restrictions is for system-wide IP restrictions?
