### ISSUE TITLE
remove extra line break and indentation in Admin UI

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4615]
See attached files, the text should not wrap.

1) Settings > Geolocate, the text wraps on next line after this radio:

![extra_wrapping_on_geolocate_button](https://cloud.githubusercontent.com/assets/466765/4605529/cc51fc70-51e7-11e4-9e7f-40015f5c3f1c.png)

2) In Scheduled report, scheduled to mobile phone, when having defined 2+ phone numbers, they appear as wrapped:
![wrapping](https://cloud.githubusercontent.com/assets/466765/4605530/e398a64a-51e7-11e4-9587-c15620ba543c.png)

**Comment by sgiehl** [comment]
Issued a PR for the second layout bug.
The first might not be that easy to solve generally. But I can guess we could solve it for that special case.

**Comment by mattab** [comment]
> The first might not be that easy to solve generally. But I can guess we could solve it for that special case.

Ok :+1:  would be nice to solve it for the special case, so far it's the only place i've seen this issue

**Comment by mattab** [comment]
Looks fixed @sgiehl so closing, nice!
