### ISSUE TITLE
Log Analytics: Detect standard Urchin log format not detected

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4619]
Hello,
Here is how URCHIN tells you to how to format your logs for apache usuage in the httpd.conf file

LogFormat "%h %v %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{Cookie}i\"" 

Here is the problem
1) it doesn't show any referral data
2) It doesn't show User Agent (Vistor Browser is Unknown)

Attached is a sample log

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
