### ISSUE TITLE
Drop IE8 support

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4620]
At some point we should drop IE8 support. 

As of January 2014 there are only ~10% of all users using IE8. On Piwik.org, we are seeing 1.3% using IE8.

Reasons:
* This is causing extra work for cross browser testing, development, troubleshooting. 
* Since we are considering using AngularJS, and their latest version 1.3 drops IE8 support, and for other reasons, we would like to drop IE8 support.
* In April 2014, Microsoft will be ending support for Windows XP, which means the end of support for the operating system most of Internet Explorer 8 users use.

Note: 

I think we should support IE8 at least until August 2014 to give companies a few months to react after MS drops XP support.

**Comment by sgiehl** [comment]
Piwik Dashboard for sure. piwik.js should always be compatible with as many browsers & versions as possible.

**Comment by mattab** [comment]
when  #8443 will be merged, effectively IE8 support will be dropped.

Let's announce it in Developer changelog as well as in the future Piwik 3 changelog of course.

**Comment by tsteur** [comment]
I'm closing this one, but not be afraid Piwik 2.X which will be supported for more than a year from now on will be compatible with IE8. Closing this issue as support will be dropped in 3.0

**Comment by tsteur** [comment]
Actually I will reopen as there's more to do:

* Changelog
* Update some code blocks where we can now use `.finally()` instead of `['finally']` etc

**Comment by tsteur** [comment]
fixed via #8591. As mentioned we still support IE8 for a pretty long time but in Piwik 3.0 it will be removed.
