### ISSUE TITLE
Date range longer than 1 year, should use the yearly reports instead of 12 months reports

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4757]
Instead of using 12 months in year2006, year2007 etc. we should instead use the YEAR archive for this year. This would result in much faster date ranges for very long periods.

See this test: https://github.com/piwik/piwik/blob/master/tests/PHPUnit/Unit/Period/RangeTest.php#L600

See also related #3611

**Comment by tsteur** [comment]
Isn't this already done see that test and https://github.com/piwik/piwik/blob/2.11.0/core/Period/Range.php#L328-L341

**Comment by mattab** [comment]
> I also did one test manually and it used a year I think.

the test looks good, but to be sure could you try again and confirm 100% that it works, and close issue? thanks!

**Comment by tsteur** [comment]
When requesting eg `2011-12-08,2015-03-18` it does use a year for 2012, 2013 and 2014. It does not use the year of 2015 which seems to be not correct.
It does also not use 2015 when having eg  `2014-12-08,2015-03-18`
