### ISSUE TITLE
Add print stylesheet to morpheus theme

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4788]
For a better look of the printed dashboard, I created a stylesheet specially for printed pages, because with the default style, printed pages don't look nice (images get split across pages).

I created a git-patchfile to fix the style of printed pages. The patchfile is in the attachment .

**Comment by mattab** [comment]
Done in https://github.com/piwik/piwik/pull/11242 :+1:

**Comment by mattab** [comment]
See also #9347
