### ISSUE TITLE
Segmentation operator ">" and custom variables of type numeric

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4879]
I use custom variables of type numeric (i.e. age). Segmentation operators &lt;, >, &lt;=, >=  assume that numeric variables are always of type string, so when I try to create a segment "age>=18" I'm getting wrong results because string "8" is considered bigger than "18".

It would be nice to have different operators for strings and numbers so user can force comparison method. 

(note: as a workaround I started padding numbers with 0s so "8" now is "08". This only works for new visits but I still can't segment historic data).
Keywords: segmentation

**Comment by mattab** [comment]
please see: https://github.com/piwik/piwik/issues/5372
