### ISSUE TITLE
Kafka for Piwik

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4902]
Hello, we need to use Piwik to track thousands of sites everyday. Our plan is to use multiple piwik servers and map a handful of sites to each piwik server. To reduce the communication overhead, we plan to use Apache Kafka [http://kafka.apache.org/] 

Do you think this will be possible with Piwik? Any guidance on how to go ahead with this will be appreciated.

Thank you.

**Comment by mattab** [comment]
See this plugin on the Marketplace http://plugins.piwik.org/KafkaPush

**Comment by ksachdeva11** [comment]
@mattab How can I use KafkaPush plugin? Can't find any documentation..

**Comment by mattab** [comment]
The old third party plugin was removed from the marketplace, as it was not compatible anymore, but the code is still available at https://github.com/gzilt-playground/piwik-plugin-kafkapush
