### ISSUE TITLE
Introduce Dependency Injection

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#4917]
Here are already some requirements I got from some core developers:

1) introduce the concept of a Component to replace current singletons. components would be objects that are automatically stored in an IoC container (ie, a class derives from Component and everything else is taken care of by the system).
2) every public method of a component would be wrapped in an event (ie, Auth.login.before/Auth.login.after or whatever)
3) there would be a global IoC container that holds all core components. it would also hold IoC containers for each plugin. plugin IoC containers would inherit from the global container (so the child container composits the parent container)
4) piwik should probably have its own IoC container class. the class essentially represents the environment Piwik code will run in, so could be called Environment. by creating new instances of such a class, we can access different Piwik's from within a Piwik (which would make the piwik cloud code cleaner & more robust)
5) dependency injection should include something similar to spring's @Autowired functionality. instead of associating components w/ strings and accessing objects by string in a container (as you would w/ pimple), it should be possible to automatically set properties of Components to the instance of other components. two-phase construction can be used to deal w/ cycles.
6) the end user should be able to configure the IoC container (though not directly). for example, plugins shouldn't decide which auth component to use, the end user should.
7) plugin objects, APIs & controllers should all be components

re 2) I think it is not directly related to this feature.

I think we do not need to have all features in the beginning. For instance we can implement 6) later on top of DI. 

Next step:
Do we have more requirements? Do we maybe not need any of those requirements? Does anyone can recommend any good library to fulfill our needs or can someone recommend any lib in general?

Then:
We could start refactoring two or three components to use DI. For instance Log, Access and Config?

A problem might be backwards compatibility as current plugins access those instances via Singleton.

**Comment by mattab** [comment]
Heya @mnapoli, 
It looks like we made big progress on introducing DI to Piwik.
what is the status on this issue?

**Comment by mnapoli** [comment]
Let's close it, it's been long out of date.

**Comment by mattab** [comment]
For anyone interested about using Dependency Injection in Piwik see this guide: https://github.com/piwik/developer-documentation/pull/67/files?short_path=762e172#diff-762e172d280769ca6701a87863ec30f2

**Comment by kaz231** [comment]
@mnapoli I have two questions: 
- I thought that StaticContainer class is deprecated, is it ?
- Am I able to define config in plugin ?

**Comment by mattab** [comment]
Not sure about our official point of view with the deprecated class StaticContainer @diosmosis what do you suggest, maybe the class is not deprecated after all, since we still use it in few places?

> Am I able to define config in plugin ?

yes, you can create DI config.php files in plugins, see for example https://github.com/piwik/piwik/blob/master/plugins/Diagnostics/config/config.php

**Comment by kaz231** [comment]
Thanks @mattab !

What is the order of including of such config files ? Can I override some service/class that is already defined in the main config from a plugin ?

**Comment by mattab** [comment]
Yes, plugin config should override core configs.

**Comment by diosmosis** [comment]
> Not sure about our official point of view with the deprecated class StaticContainer @diosmosis what do you suggest, maybe the class is not deprecated after all, since we still use it in few places?

It will be removed in 3.0. It has to be used now because Piwik dependencies are too tangled up, and because of `@api` static methods that can't be removed/deprecated until 3.0.
