### ISSUE TITLE
Latitude and Longitude should use DECIMAL datatype instead of FLOAT

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#4923]
Recently we encountered problem with accurate lat/long storing when being passed by request parameter.

It looks like it's connected strictly with type of location_latitude and location_longitude columns.
Originally it's float and then error occurs. Altering it to decimal seems to solve problem.
How to reproduce:

- on new Piwik instance set tracker to allow lat/long overriding:
[Tracker]
tracking_requests_require_authentication = 0

Then launch simpliest tracking request like:
http://local.piwik/piwik.php?idsite=1&rec=1&lat=98.23&long=-21.45

and see in database what values are stored:

lat: 98.230003
long: -21.450001

On the other hand tracker debug show proper values.

After changing schema of log_visit table and launching next request, coordinates are stored properly (lat: 98.230000, long: -21.450000)

**Comment by mattab** [comment]
This change requires a schema upgrade to ALTER the column types, which is currently blocked:  No schema change allowed on log_visit nor log_link_visit_actions nor log_action tables #6953

**Comment by tsteur** [comment]
FYI related posts: 

http://stackoverflow.com/questions/34277208/i-need-to-change-data-type-from-float-to-decimal-of-a-database-currently-got-1-b

http://dba.stackexchange.com/questions/9187/mysql-conversion-from-float-10-2-to-fixed10-2

**Comment by mattab** [comment]
@tsteur I went the easy route and simply cast the field to decimal. It's working good enough in our case.

**Comment by mattab** [comment]
Done in #10543
