### ISSUE TITLE
import_logs.py occasionally reports .mobi domain visit as .mobi file download

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4980]
`import_logs.py` will sometimes report a visit to a .mobi domain home page as a download of a .mobi file.  Here is an example of a visit reported as such:

```
xxxx:xxx:x::xxx - - [09/Apr/2014:07:43:55 +0000] "GET http://example.mobi HTTP/1.0" 200 581 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0\x5Cr\x5Cn"
xxxx:xxx:x::xxx - - [09/Apr/2014:07:43:55 +0000] "GET /apple-touch-icon-precomposed.png HTTP/1.0" 404 162 "-" "-"
```

Of the above two clicks, only one click was included in the report.

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
