### ISSUE TITLE
Outlinks not properly encoded

### ISSUE THREAD

**Issue by zeine77** [piwik/piwik#5014]
Outlinks are not properly displayed when containing arabic caracters in Piwik 2.2.0 preventing so to get the actual link.

For exemple: I have an outlink to this page (url contains arabic caracters)

zeine77.wordpress.com/2012/10/29/----/

Piwik diplays it like that : 

zeine77.wordpress.com/2012/10/29/----/

Keywords: arabic, url, unicode

**Comment by saleemkce** [comment]
@mattab Hi Matthieu, Could you assign this issue to me? I have already found out the bug causing the whole mess?

**Comment by mattab** [comment]
Hi @saleemkce you don't need to have issue assigned to you - since it is in `Short term` we have not yet scheduled to work on this (we are working on issues in next version milestone on github ie. currently 2.14.0)

**Comment by saleemkce** [comment]
@mattab, thanks.

**Comment by tsteur** [comment]
FYI: In https://github.com/piwik/piwik/pull/7866#issuecomment-101076864 and  https://github.com/piwik/piwik/pull/7866#issuecomment-101430058 we noticed to fully fix this issue we most likely have to replace `unescape` with `decodeURI` see comments. `unescape` is deprecated anyway and there's a chance it breaks piwik.js in newer browsers some day (or probably already and we don't notice). I think `decodeURI` is available in all browsers but haven't checked. A safe way would be to fall back to `unescape` with `decodeURI` is not defined.

**Comment by mattab** [comment]
Adding to 2.14.0 as this is a "data quality" bug

**Comment by walkercz** [comment]
Hello, 

I installed piwik on windows server 2012 R2 and IIS 8 and using it for tracking visits on SharePoint 2013 Server. Everything running as expected. DB and piwik shows UTF8. Piwik UI,visits on sites are shown allright with czech characters ěščřžýáíé but in search and download strings these characters are replaced with ÄÅ¡ÄÅÅ¾Ã½Ã¡Ã_Ã©. 

Does anybody know how to solve this problem?

piwik 2.13.1

![piwik-bug](https://cloud.githubusercontent.com/assets/3652371/7681566/768d5c9a-fd71-11e4-86a9-b131b6b4f44e.png)
