### ISSUE TITLE
Make theme look great when used in Mobile browser

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#5029]
Screenshot was taken from desktop Chrome 34.0.1847.116 simulating 320px device width, but it looks the same in every mobile browser I've tested so far (Opera for Android, Dolphin, stock 4.04 ICS browser).

It looks a bit cramped, personally much preferred non-responsive version from Piwik 1.12
Keywords: Zeitgeist, theme, piwik

**Comment by mattab** [comment]
It would make sense to

**Comment by mattab** [comment]
it would make sense to consider make Piwik look great on Mobile after the design refresh #7585 and default  left menu #7169

**Comment by mattab** [comment]
Done in #8936 

here is how beautiful it looks like now on a mobile device: http://builds-artifacts.piwik.org/piwik/piwik/master/16015/UIIntegrationTest_dashboard5_mobile

Check it out live on: http://demo.piwik.org/
