### ISSUE TITLE
Windows: rename(C:\misc/GeoIPCity.dat.new,C:\misc/GeoIPCity.dat): The process cannot access the file because it is being used by another process. (code: 32)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5050]
Bug reported [in the forum](http://forum.piwik.org/read.php?2,114254):

```
 Warning:&lt;/strong> &lt;em>rename(C:\Webservices\htdocs\piwik/misc/GeoIPCity.dat.new,C:\Webservices\htdocs\piwik/misc/GeoIPCity.dat): The process cannot access the file because it is being used by another process. (code: 32)&lt;/em> in &lt;strong>C:\Webservices\htdocs\piwik\plugins\UserCountry\GeoIPAutoUpdater.php&lt;/strong> on line &lt;strong>268&lt;/strong>
```

This is triggered in the cron, Scheduled tasks.

I'm not sure what should be done with this issue?

**Comment by grzchr15** [comment]
This does still not work with Piwik 2.16.0 . So the autodownloader of GeoIP DBs is still senseless
Only manual updating works
Renaming cannot work, but 2 files which are used alternative may work

**Comment by sanso2010** [comment]
Hi all, so I've encountered this error as well. For now I've changed the GeoIPAutoUpdater.php, line 271 to `copy` instead of `rename` - ofc this will leave the .new file in the folder. It will be overwritten in the next scheduled update though. It's still better than not being able to autodownload those files. Unfortunately there seems to be no way to "close" the GeoIP Database before deleting/renaming. I have no idea what's keeping that file open reading the code.

**Comment by Globulopolis** [comment]
Yes, this is a bug on Windows platform. In some situations rename function cannot work. In my other project i do copy instead of rename.

**Comment by huan086** [comment]
Still broken in Piwik 3.0.3. @sanso2010's workaround https://github.com/piwik/piwik/issues/5050#issuecomment-252486101 still works.

**Comment by mattab** [comment]
Thanks for letting us know, we'll take a look at this

**Comment by mstenz** [comment]
I am wondering why this easy change is not yet done as a fix is already provided
I cant do it because i am not used to git so much, but for someone dealing anyhow with the piwik code it took 5 seconds to fix this.

**Comment by mattab** [comment]
@mstenz Would you please share a patch (even if not a pull request) that you have tested and fixes the issue for sure?

**Comment by mstenz** [comment]
I don't know how to do this, but you just need to replace one word on line 271 in plugins\UserCountry\Ge
oIPAutoUpdater.php
`            rename($tempFile, $oldDbFile);`
to 
`            copy($tempFile, $oldDbFile);`
Solution was provided already by other users in this thread.
