### ISSUE TITLE
"Make it flat" actions/pages report eats server resources when there's a large amount of data

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#5098]
Ciao, for year 2013 range report some of our websites have counted >2.74 M visits and >6.64 M page views.

When user opens the Actions/Pages report for the whole 2013 and tries to "Make it flat" he can't get the flattened report neither "excluding low population" because the icon wheel stills twisting with no feedback.

Server side, Apache's child uses 100% cpu, then dies in about 2 minutes because memory was exhausted (3Gb in staging environment). Before this death, it was dying by PHP's default max_execution_time setting (now raised to 300s for testing purposes).

Is there any chance to get "Make it flat" working also when we have a lot of data, or just dying with feedback in case of big amount of data, or finally could it be optionally disabled when data is too much?

**Comment by pouyana** [comment]
Hi Matt,
I just read all the linked topics, here but I didn't find a way to get the flat=1 reports done, on a website with more than 1Million visitors a month and also the date=last30 and period=month and so on didn't help either. Can adding hardware resources help here?

**Comment by mattab** [comment]
Hi guys,
can you please test Piwik 2.12.0-b1 ? It brings huge performance improvements to flatten requests and likely this issue is already fixed! Please confirm :-)

**Comment by pouyana** [comment]
Hi I tried to use the 2.12.0-b1 but, I get JavaScript error in assoc. with Angular.js:

 Error: [$injector:unpr] http://errors.angularjs.org/1.2.28/$injector/unpr?p0=piwikProvider%20%3C-%20piwik%20%3C-%20piwikNotificationDirective
  z/...

**Comment by tsteur** [comment]
This should be unrelated to this change. Do you mind creating an issue for this?

**Comment by tassoman** [comment]
Hello there, we're planning a fully upgrade of our Piwik installation from 2.4 to the latest stable 2.1* on the staging server using a dump provided by production servers. We'll keep you informed on this asap thank you for caring of it!

**Comment by mattab** [comment]
This is fixed as far as we know - please comment here if you still have issues using  2.12.0-b1 or later
