### ISSUE TITLE
UNIQUE VISITORS for custom variables

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#5109]
Early this year of 2014, I've upgraded to Piwik v2. While I'm comparing with Piwik v1, I realized that something has been missing in v2, no unique visitors for custom variable as it's one of important/interesting keys for my website Analytics or maybe for others too.

Please to add the feature of UNIQUE VISITORS for custom variables.
Thanks for the quick support.
Keywords: unique visitor custom variable

**Comment by sansac** [comment]
hi
  UNIQUE VISITORS for custom variables are not displaying in visitor log > custom variables UI.
I added configuration based on http://piwik.org/faq/how-to/#faq_113

In my javascript i added bellow code then also i am not able to see UNIQUE VISITORS for custom variables in UI.

![piwik1](https://cloud.githubusercontent.com/assets/5286315/11184714/24f1520c-8c9f-11e5-8468-2c73928c6ebd.PNG)

  var u=(("https:" == document.location.protocol) ? "https" : "http") + "://"+paq_url+"/";
  _paq.push(['setTrackerUrl', u+'piwik.php']);
  _paq.push(['setSiteId', paq_site_id]);
  _paq.push(['setUserId', userId]);
  _paq.push(['setCustomVariable', '2','Full Text Search Users',userId,'visit']);
  _paq.push(['setCustomVariable', '3','Full Text Search User Types',userType,'visit']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  _paq.push(['trackSiteSearch',keyword,category,searchCount]);



Please help me

**Comment by mattab** [comment]
As we will deprecate custom variables in #11524, closing this issue as Won't fix.

We now recommend to use [Custom Dimensions](https://piwik.org/docs/custom-dimensions/) instead.
