### ISSUE TITLE
import_logs.py ignores lines after a line with http 200 status is processed

### ISSUE THREAD

**Issue by vspiliop** [piwik/piwik#5161]
Hello to all!

I am using piwik for a customer and just found out the following very serious issue.

I am using the latest piwik (2.2.2), php  5.4.26 and Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [v.1500 32 bit (Intel)](MSC) on win32.

PROBLEM:

All lines (in the web log) after a line with HTTP status 200 are ignored!! i.e. in the following example only the first entry is included both to the Visits and to the Actions. This applies before or after I do the achieving. So archiving is irrelevant.

I just import (access.log : file with just 2 lines):

66.249.76.11 - - [+0100](11/May/2014:23:59:59) "GET /id/resource/013541589 HTTP/1.1" 303 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.76.11 - - [+0100](11/May/2014:23:59:59) "GET /doc/resource/007667232 HTTP/1.1" 200 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

via command:

    python import_logs.py --url=http://localhost:83/

analytics/ access.log --idsite=1 --recorders=2 --enable-http-errors --enable-http-redirects --enable-static --ena
ble-bots

Result:

0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Parsing log access_006_bl.services.tso.co.uk.2014.05.12.log...
Purging Piwik archives for dates: 2014-05-11
To re-process these reports with your new update data, execute the following command:

    piwik/console core:archive --url=http://example/piwik/

Reference: http://piwik.org/docs/setup-auto-archiving/

Logs import summary

    2 requests imported successfully
    0 requests were downloads
    0 requests ignored:

        0 invalid log lines
        0 requests done by bots, search engines, ...
        0 HTTP errors
        0 HTTP redirects
        0 requests to static resources (css, js, ...)
        0 requests did not match any known site
        0 requests did not match any requested hostname

Website import summary

    2 requests imported to 1 sites

        1 sites already existed
        0 sites were created:

    0 distinct hostnames did not match any existing site:

Performance summary

    Total time: 0 seconds
    Requests imported per second: 3.29 requests per second

Kind Regards,
Vassilis

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
