### ISSUE TITLE
Error was malformed input, while sending PDF Email Report

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5193]
This error was reported a few times in the forums, [in this post](http://forum.piwik.org/read.php?2,115274) for example. The error "malformed input" occurs when sending emails.

Cause is still unknown at this stage, if you experience this bug please comment here with your PHP version. It may be due to a bug in old PHP or other ext.

**Comment by NicolasGoeddel** [comment]
I also experience this bug. This is my PHP version:
PHP 5.4.38-1+deb.sury.org~lucid+2 (cli) (built: Feb 20 2015 12:16:48)
My Piwik version is 2.12.0

**Comment by NicolasGoeddel** [comment]
Here Matt said I should mention the steps to reproduce the bug: http://forum.piwik.org/read.php?2,125254,page=1#msg-125602

These are the steps:
[Switch to User Profile](https://freakscorner.de/owncloud/index.php/s/RgWVgrNzd3aRa7f)
[Switch to E-Mail reports](https://freakscorner.de/owncloud/index.php/s/7gMhaE2SI7ETqi8)
[Create new report](https://freakscorner.de/owncloud/index.php/s/HeW5OE9eBE8PUOF)
[Give it a description](https://freakscorner.de/owncloud/index.php/s/UndG8XJjp662GJ2)
[And at least one report type](https://freakscorner.de/owncloud/index.php/s/UjUaDr8viZjch6v)
[Click on "Create report"](https://freakscorner.de/owncloud/index.php/s/MEdpMqr0wm7oTOp)
[Click on "Send report now"](https://freakscorner.de/owncloud/index.php/s/J5plnrHeOkQfAq7)
[Error](https://freakscorner.de/owncloud/index.php/s/DwyDteKQKTpwrzX)

**Comment by NicolasGoeddel** [comment]
Is there anything new about this?

**Comment by mattab** [comment]
can't reproduce
