### ISSUE TITLE
Run javascript unit tests on minified Javascript tracker

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5195]
Our Javascript tests currently run for the non minified version of piwik.js

when changing the test file to test not the "original /js/piwik.js" but instead test the minified /piwik.js then the test fail (see attached screenshot)

The line to change is: https://github.com/piwik/piwik/blob/master/tests/javascript/index.php#L51-51

Proposed steps: 
- Investigate why the tests fail on the minified JavaScript tracker 
- Run the Javascript tracker tests on both the minified and non minified versions

**Comment by sgiehl** [comment]
duplicates #5165
