### ISSUE TITLE
Detect when a user is actively browsing or using the webpage, for more accurate Time on page

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5208]
Today user often have multiple tabs opened in their browser.
All but 1 are in the background and were not viewed and not used.

Since one could now track onpage events like using css tabs, fold or unfold content or even scrolling one could use the existence of theses events to derive that the user is viewing/using the page.

The other way around one could derive that when there are no events for a period of time e.g. 15sec the page maybe not in use and e.g. only opened in the background.

=> having this "not in use" information one could stop counting the time one page and could achieve better and more realistic about time on page.

One idea regarding usability:
one could a have
- a simple setting to activate this function "stop time counting when there are no events" and
- a field to put in the duration how long there has to be no event until the time is stopped.

=> users who have implemented Custom event tracking can simply activate this, and for all users who have not, everything keeps the same.

What do you think?

**Comment by mattab** [comment]
This should be implemented by the Heart Beat timer: https://piwik.org/faq/how-to/faq_21824/
