### ISSUE TITLE
Display + and - icons in Campaign report

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#5209]
I guess, in the hierarchical view of the campaign report, the little plus icon to expand the campaign and show the keywords is missing. The keywords are just visible in the flat view. I tried with IE9 and Firefox 29.
Keywords: campaign

**Comment by mattab** [comment]
This regressed somehow, the Campaign reports do not show the +/- currently, this can be seen on demo2: http://demo2.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last30#/module=Referrers&action=menuGetCampaigns&idSite=1&period=range&date=last30
