### ISSUE TITLE
Show unique visitors stats if they are processed for the given date / period / range

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#5223]
1) If unique visitor stats are processed for a given date / period / range, they should be shown in the action- and the custom-variable reports. 
2) Exports - When a Datatable is exported, include a consistent set of columns (some export formats export unique visitor stats, others don't). I can't even consitently reproduce this behavior, so this needs further investigation.

This was experienced against Piwik 2.2.0.

**Comment by tsteur** [comment]
I have no idea what is do be done here. Where in the interface is it missing? I can see it when going to "Visitors => Overview" which is basically the `API.get` visualization of the above image / API response.

Custom Variables is handled in a different issue as mentioned so wondering what to do here.

**Comment by mattab** [comment]
Hi @YehiaAboSedera @peterbo  please comment here and reopen issue if you still experience this in 2.10.0  

Closing as it works for us

**Comment by milantestagena** [comment]
I found what cause this error:
you count unique visitors on this way:

SELECT count(distinct idvisitor)  FROM piwik.log_visit_table
where visit_field > '2015-02-01' and visit_field < '2015-03-01'
AND ( v1 = 'Ext' OR  v1 = 'Int' );
(I changed key names for security reason)
and when user is in both groups, Int and Ext
you loose one Unique Visits

so, you need to count this:
SELECT count(distinct idvisitor, v1)  FROM piwik.log_visit_table
where visit_field > '2015-02-01' and visit_field < '2015-03-01'
AND ( v1 = 'Ext' OR  v1 = 'Int' );

**Comment by tsteur** [comment]
Can you post the proper field names? It is not a security problem since they are public here in the source code

**Comment by milantestagena** [comment]
in LogAgregator
Metrics::INDEX_NB_UNIQ_VISITORS    => "count(distinct " . self::LOG_VISIT_TABLE . ".idvisitor)",
change to 
Metrics::INDEX_NB_UNIQ_VISITORS    => "count(distinct " . self::LOG_VISIT_TABLE . ".idvisitor,  " . self::LOG_VISIT_TABLE . ".custom_var_v1)",

and

Metrics::INDEX_NB_UNIQ_VISITORS => "count(distinct " . self::LOG_ACTIONS_TABLE . ".idvisitor)",
to
Metrics::INDEX_NB_UNIQ_VISITORS => "count(distinct " . self::LOG_ACTIONS_TABLE . ".idvisitor,  " . self::LOG_VISIT_TABLE . ".custom_var_v1)",

**Comment by tsteur** [comment]
This looks like custom logic to me but I it can make sense. I reckon it depends on the kind of application and what custom variables are used for. If I understand it correctly, you do want to count two unique visitors in case there is one visitor having two entries each with a different custom variable? @mattab ?

**Comment by mattab** [comment]
@milantestagena can you create a new issue explaining what you are doing and what you would ideally need us to do? this issue is closed already

**Comment by sansac** [comment]
Even After updating  Metrics::INDEX_NB_UNIQ_VISITORS => "count(distinct " . self::LOG_VISIT_TABLE . ".idvisitor, " . self::LOG_VISIT_TABLE . ".custom_var_v1)"  in LogAgregator, unique visitor count is blank.
I enabled unique visitor in piwik based on http://piwik.org/faq/how-to/#faq_113

![piwik1](https://cloud.githubusercontent.com/assets/5286315/11247301/779831f8-8e41-11e5-8b03-e32351758b04.PNG)
