### ISSUE TITLE
CustomEvent in Visitor Profil: Prevent linebreak after event symbol

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5233]
There is a not necessary line break in the Visitor Log directly after the event symbol.
Please see attachment

seen in
2.3.0 final, FF30

**Comment by tsteur** [comment]
I can confirm the line break is still a problem with latest Piwik when event category is very long. Also the arrow is not correctly placed (not centered)

**Comment by hpvd** [comment]
still there in piwik 2.11 b4
![2015-02-11_08h23_21](https://cloud.githubusercontent.com/assets/5681880/6143354/7ec5f2be-b1c7-11e4-9775-4db3e26a4a5a.png)

**Comment by mattab** [comment]
Reopening as per @hpvd feedback.

**Comment by tsteur** [comment]
Should be fixed now. As mentioned in a similar issue the visitorLog html + css needs to be completely redone.
