### ISSUE TITLE
capture custom log param(s); capture only records with custom param(s)

### ISSUE THREAD

**Issue by fogelfish** [piwik/piwik#5252]
It would be nice for import_logs.py to be able to make one or more custom log parameters into Piwik custom variables and hand them to the Piwik Tracking API request.

I am completely new to Piwik but I will see if I can solve this on my own.  I'm not sure of protocol would it be okay to post questions as I work on this?

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
