### ISSUE TITLE
Sparklines fail to load behind reverse proxy because of wrong URI

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#5288]
Sparklines fail to load behind a reverse proxy because of wrong URI, one subdirectory is missing. (Screenshot) 

Tested in Piwik 2.3

**Comment by mattab** [comment]
let's investigate this issue as part of the broader set of bugs in #6880  -> our goal will be to make Piwik work perfectly in this special use case which many users have reported issues with.

**Comment by mattab** [comment]
@peterbo Thanks for the report. Marking as duplicate of https://github.com/piwik/piwik/issues/6644 which is a similar issue.  maybe you could post a  comment with your reverse proxy config in https://github.com/piwik/piwik/issues/6644  in case it's different from the nginx conf mentioned there.
