### ISSUE TITLE
Login leads to wrong URL when using ssl proxy

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#5290]
Concerning Piwik 2.3.0 

Given:

 A short URL for piwik like &lt;http://p.test.invalid>. This is &lt;http://www.test.invalid/piwik/>.
 An ssl proxy that redirects all &lt;http://(*)test.invalid> traffic to &lt;https://ssl.kundenserver.invalid/test.invalid>.
 A rewrite-rule via .htaccess that perfectly works.
 All above not run on an own server but a hosted web package.

Awaited (and worked with Piwik 1):

 Calling &lt;http://p.test.invalid> invokes the correct Piwik login page.
 Logging in there forwards to the correct address &lt;https://ssl.kundenserver.invalid/test.invalid/piwik/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last30>.

What happens with Piwik 2:

 Calling &lt;http://p.test.invalid> invokes the correct Piwik login page.
 Logging in there forwards to the WRONG address &lt;https://ssl.kundenserver.invalid/piwik/index.php>
 After that happens one can circumnavigate the problem with calling once more again &lt;http://p.test.invalid>.
 THEN the right URL occurs: &lt;https://ssl.kundenserver.invalid/test.invalid/piwik/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last30>.

This is a problem for the user.

But this could be also critical for all Piwik users due to the fact that it could be that all Piwik calls with Piwik 2, using this specific ssl proxy service lead to the central ssl proxy address.

**Ive anonymized the adresses**, but the scheme is as is. This is a service provided by 1&1 in Germany.

Piwik forgets the specific site URL part in the forwarded new address.

This did not happen with Piwik 1, it is new to Piwik 2.

Piwik 2 has a problem to detect (?) and work with an ssl reverse proxy setup. It also does not show an own logo branding and it does not show the little graphs at the multiple sites dashboard.

Piwik 1 had another problem to detect and work with an ssl reverse proxy setup. It either did not show an own logo branding but it showed all other graphs, including the previews graphs at the multiple sites dashboard.

I dont know if it is of interest, but: When logging out, Piwik 2 leads to the right login adress &lt;https://ssl.kundenserver.invalid/test.invalid/piwik/index.php?module=CoreHome&action=>, maybe this is a point to narrow the bug.

**Comment by mattab** [comment]
let's investigate this issue as part of the broader set of bugs in #6880  -> our goal will be to make Piwik work perfectly in this special use case which many users have reported issues with.

**Comment by mattab** [comment]
See https://github.com/piwik/piwik/issues/6644
