### ISSUE TITLE
Possibility of cancelling orders in an easy on/off kind of way

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#5292]
According to http://forum.piwik.org/read.php?2,93018 the only way to cancel an ecommerce order is to submit the ID again with a revenue of zero. This seems like a workaround, especially if the re-processing of past logs has to be implemented too, and I didn't find any feature requests or discussions about this topic yet.

I would propose a method of cancelling (and uncancelling) an order through the tracking API. This would have several advantages:
- Order summary stays intact, a cancelled order can be reactivated easily. This is not just theory: A customer may order something, then forget to pay it, the order is automatically cancelled, and then the customer at last decides to go through payment for the order which necessitates reviving the order.
- Cancelled orders are of interest for ecommerce statistics and would be a worthy possible segment, even more so than abandoned carts. After all, people who cancel their orders after placing them have come much further than someone who just put something in their cart, and analyzing the reasons for order cancellations could be very useful. For many online shops cancelled orders can be as high as 20-30%, for various reasons.
- Maybe it would be possible to automatically reprocess the ecommerce statistics which are affected by the changed order, which would be a huge help especially for novice users of piwik (and even advanced users).
- A reason for cancellation could be optional, in order to differentiate these customer segments even more, and the cancellation could be shown in the visitor log (this is just how I would picture it).

I suspect many users of piwik are not tracking their ecommerce orders fully yet, and if they do, their statistics do not represent their actual sales. An easy way of cancelling an order would make it much easier to use the ecommerce plugin in a useful way, and would be a great feature for piwik.
Keywords: order, ecommerce, cancel

**Comment by s1awa** [comment]
@mattab
> To remove an Ecommerce transaction, send the ecommerce transaction in javascript with the same orderId and with a revenue of 0 -> it should cancel the transaction.

Is it possible to do this without JS? e.g. with Tracking HTTP API
So I can send a POST from shop server to piwik server to cancel an order?

**Comment by mattab** [comment]
Hi @s1awa Yes it is possible to use Tracking API directly (the Piwik JavaScript actually uses the Tracking API), see the API reference at: http://developer.piwik.org/api-reference/tracking-api

**Comment by mattab** [comment]
We'll make it happen here: https://github.com/piwik/piwik/issues/10893
