### ISSUE TITLE
Keep Performance- and storage-demand ok when using extensive event tracking

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5347]
Since event tracking is available, this great new feature could easily blow up the total number of "things" being tracked within each visit.

E.g. if having implemented the possibility to track 5 events on each site and each visitor "uses" (->trigger) only 2 of them in average

-> you got instead of 1 site visit 3 "things" to track (Factor 3)
But this number could easily raise to factor 5 or even more...

The goal of is ticket is to collect ideas to prevent a huge impact on
1. Performance and
2. Storage space

**Comment by mattab** [comment]
see https://github.com/piwik/piwik/issues/5347#issuecomment-48316100
