### ISSUE TITLE
single switch to disable eventtracking

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5364]
If you make use of extensive event-tracking, functions for that could be spread all over the website-code. And if you have different types of content on your site this could also be different for each of them.

Not only during development & setup but also on server maxload-times (see #5347)
it could be really helpful to have a possibility to stop event tracking (and with this "event firing") for a complete website using only a single "switch" but keep normal page tracking working...

any ideas howto do this best are very welcome

**Comment by mattab** [comment]
The best way to disable event tracking is to disable the Events plugin.

**Comment by mattab** [comment]
see also https://github.com/piwik/piwik/issues/7115
