### ISSUE TITLE
Make it easier to select websites in Zen Mode

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#5367]
I think lots of people enjoy the "clutter-free" Zen Mode.

But I really miss the site selector (in 2.4b6) once in Zen Mode and it's cumbersome to have to switch to normal view to change websites...
1. Add the menu on the right of  "Search for anything"

or
1. Let the menu at the "usual" place (far right).

Dali
Keywords: Zen mode

**Comment by sgiehl** [comment]
Zen mode now also shows the site selector
