### ISSUE TITLE
Don't show notice every time we switch to Zen Mode

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#5369]
Each time we switch to Zen Mode (2.4b6) the blue notice is showed and it becomes annoying.

In a way related to #5367 (having to go back to normal view to change site).

Suggestions:

1. Display message for 2 seconds and fade out (no click)

Or

2. Once the X is clicked, remember that the message was already showed and don't display for this session.

Dali
Keywords: Zen mode

**Comment by tsteur** [comment]
Closing as ZenMode was removed
