### ISSUE TITLE
Visitor Log: move number of page reloads "3X" next to the action title

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5389]
sometimes its hard to see to which site the number of reloads belong.
Please see example.

One idea to solve this:
Maybe one could move this number directly next to the site title (and make it a little smaller?

**Comment by sgiehl** [comment]
That was already fixed some time ago. It's now displayed that way:
![image](https://cloud.githubusercontent.com/assets/1579355/11919717/9a6f6732-a75a-11e5-92bf-fb85d0015157.png)
