### ISSUE TITLE
As a plugin developer, I want to archive my historical plugin's data without having to re-process all other plugins as well

### ISSUE THREAD

**Issue by quba** [piwik/piwik#5392]
I wonder if it could be possible to archive one specified plug-in. 

Example scenario, when such feature would be useful: 
-running high-traffic instance using Piwik,
-install new plug-in that is using daily archiving,
-archive all historical data.

Currently it's only possible by dropping archives for all plug-ins. It's an overkill in most cases.
Keywords: archiving

**Comment by mattab** [comment]
see https://github.com/piwik/piwik/issues/11974
