### ISSUE TITLE
As a Piwik plugin user, I want to leave a feedback to the plugin developer

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5395]
The Piwik Marketplace is where developers [publish](http://developer.piwik.org/guides/distributing-your-plugin) [Plugins for Piwik](http://plugins.piwik.org/).

Use cases

* As a developer of a Piwik plugin, I want to get feedback from users of my plugin 
* As a Piwik plugin user, I want to leave a feedback to the plugin developer

How could we add support for comments on the Marketplace?

**Comment by tsteur** [comment]
This had been implemented for a while but wasn't shown in the UI. Can be specified in plugin.json via support property see http://developer.piwik.org/guides/distributing-your-plugin
