### ISSUE TITLE
Several development files should no be packaged

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#5401]
In the current piwik-2.4.0.tar.gz there are some files which, in my opinion, should not be packaged with piwik:

plugins/DBStats/.gitignore
plugins/ExamplePlugin/.gitignore
plugins/ExamplePlugin/screenshots/.gitkeep
plugins/ExamplePlugin/.travis.yml
plugins/ExampleTheme/images/.gitkeep
plugins/ExampleTheme/screenshots/.gitkeep
vendor/leafo/lessphp/.gitignore
vendor/leafo/lessphp/.travis.yml
vendor/piwik/device-detector/.gitignore
vendor/piwik/device-detector/.travis.yml
vendor/symfony/console/Symfony/Component/Console/.gitignore
vendor/symfony/yaml/Symfony/Component/Yaml/.gitignore
vendor/tedivm/jshrink/.gitignore
vendor/tedivm/jshrink/.travis.yml
vendor/twig/twig/.editorconfig
vendor/twig/twig/.gitignore
vendor/twig/twig/.travis.yml

And those files too, as they are needed for compiling Apache modules only:

vendor/twig/twig/ext/twig/config.m4
vendor/twig/twig/ext/twig/config.w32
vendor/twig/twig/ext/twig/.gitignore
vendor/twig/twig/ext/twig/LICENSE
vendor/twig/twig/ext/twig/php_twig.h
vendor/twig/twig/ext/twig/twig.c

**Comment by mattab** [comment]
We are discussing removing .gitignore files in: https://github.com/piwik/piwik-package/issues/41

if you want other files removed as well, please create a new issue
