### ISSUE TITLE
Add plugins dependency capability

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5480]
In #4183 support is added for "require" piwik and / or a php version.

* Some plugins may also "require" other Piwik plugins (core or third party) to be installed at a particular minimum version.
* When a plugin has other required plugins, when possible, ask user & then install required plugins first, then this plugin. 

As a result, it will be clean and almost error-free to use a plugin, as long as the developer set the "require" flags properly. This would be a subtle yet useful new feature.

**Comment by tsteur** [comment]
Is this a duplicate of #4485 ? Can we close this one?

**Comment by mattab** [comment]
correct
