### ISSUE TITLE
wrong ecommerce conversion calculation in custom variables report

### ISSUE THREAD

**Issue by ryrun** [piwik/piwik#5828]
The custom variables report in the ecommerce tab show always 0 orders, which is wrong. We are tracking users with custom variables all the time and ecomemrce orders itself are correctly tracked. Only the custom variables report seems to be broken.

**Comment by mattab** [comment]
Hi @ryrun thanks for the report.

**Comment by diosmosis** [comment]
Hi @ryrun, I'm unable to reproduce this problem, if you still experience the bug, can you post a screenshot of the custom variables report w/ ecommerce orders being 0, and a screenshot your ecommerce log showing some ecommerce orders w/ custom variables?

**Comment by ryrun** [comment]
Ok, but i need some time. I'll recheck this issue next week.

**Comment by mattab** [comment]
Hi @ryrun  can you please post a screenshot with 2.12.1 showing the issue?  it looks like it works in 2.12.1

**Comment by ryrun** [comment]
So, the problem is still there. The custom variables report in ecommerce tab still show just 0.
We are using following tracking code for ecommerce tracking:

```javascript
var pkBaseURL = (("https:" == document.location.protocol) ? "https://***/" : "http://***/");
    try {
        var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", ***);
                piwikTracker.setCustomVariable(1, "CustomerStatus", "Bestandskunde", "page");
                piwikTracker.addEcommerceItem("***", "***", "***", 99.99, 1);
        piwikTracker.trackEcommerceOrder("***", 99.99, 99.99, 99.99, 99.99, 0.0);
        piwikTracker.trackPageView();
        piwikTracker.enableLinkTracking();
    } catch (err) {
    }
```
Maybe our tracking is wrong? It works atleast for normal ecommerce tracking. Please note, that i've changed the values.

**Comment by mattab** [comment]
Thanks for the feedback @ryrun 

In
>                 piwikTracker.setCustomVariable(1, "CustomerStatus", "Bestandskunde", "page");


replace `page` by `visit` - this should solve the problem for you. By design Piwik will copy in the Ecommerce conversion / Goal conversion those custom variables that have the scope `visit` - we should document this somewhere so I'll leave issue opened until I document it

**Comment by ryrun** [comment]
Hi @mattab i've changed the tracking code, i'll will post some updates soon.

**Comment by ryrun** [comment]
@mattab Problem is fixed for me. *visit* works fine for me.

**Comment by mattab** [comment]
Good to know. I've updated the user guide at: https://piwik.org/docs/custom-variables/#tracking-a-custom-variable

If you measure Goals or use Ecommerce Analytics, note that when the conversion occurs Piwik will copy any custom variables of scope "visit" in the Conversion. You can then view Conversion rates by Goal (and Ecommerce conversion rate) for each of your "visit" scope custom variables.

**Comment by fnagel** [comment]
@mattab 

A question for understanding: We track a custom variable "language" of scope "page" as the user is able to change the language. Which will not work for eCommerce segements view. This leaves two options: change the custom variable to scope "visit" or wait for #3950 and use that as segment instead of our custom variable. Any other options?

**Comment by mattab** [comment]
@fnagel correct. don't think there are other option. hopefully we can do #3950 sooner rather than later

**Comment by fnagel** [comment]
@mattab Thanks for the fast response. Very appreciated.
