### ISSUE TITLE
text overlapping in the visitor profile view.

### ISSUE THREAD

**Issue by ecrazor1911** [piwik/piwik#5832]
Hello,

I click the "view visitor profile" and some data don't initalize on the left side or wrong display.

![Image of bug](http://i.snag.gy/cCsYj.jpg)

or http://screencloud.net/v/iEXl

**Comment by tsteur** [comment]
Hey,

can you still experience this issue with the latest Piwik version? Which Browser and Operating System are you using?

This seems to be fixed for me meanwhile. I tested with Chrome, Firefox and Safari but not with IE so please reopen in case you still have this issue. I also tried with and without custom variables and with very long titles in custom variables and seems to be alright.
