### ISSUE TITLE
Exclude as many automated bots as possible from being tracked (more reliable tracking)

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5845]
Improve statistic quality / More realistic statistics

**There are more and more AUTOMATIC visitors around and distort/falsify our great statistics:**
not only
1) **search engines** which build and update their index
but also
2) lots of **website watchers** who notify their user on content changes:
  a) standalone softwares
  b) browser plugins 
  c) webservices
and
3) **simple browsers** with lots of open tabs:
a) Depending on the browser and its setting, in the worst case every time the browser starts a new visit is counted:
  -after booting and opening the browser every morning
  -after updates (especially alpha/beta users may gets lots of updates..)
  -after installing/update some browser plugins
  -...
b) websites which were used and are not left or closed but are still opened in a browser tab doesn't stop making visit-time count!
4) probably some more

**=> Piwik should take action to get rid of all this misinformation!!**

**What could be done (cleaning actions):**
1. Exclude visitors which are known/identify as searchengine indexer 
2. Exclude visitors which always visit a subpage at the same time (+- a tolerance of some seconds)
3. Exclude visitors which visit a subpage in continuous intervals: every hours, every 2 hours...
4. Exclude visitors which opens more than one subpage at the same time (+- 1s tolerance)
5. Exclude vistors with no events on the subpage (if you have some events setup on every site)
6. Exclude visitors staying longer than e.g. 15minutes on a subpage
7. Exclude visitors which belong to the e.g. 5% of the most returning visitors on a subpage
8. probably many more things

**To make this as transparent as possible, all statistic cleaning-actions should be transparent visible to and selectable by the piwik users.**

**There are at least two places where this could be done:**
A) **Globally** in the settings
maybe at a new tab "Statistic quality"
via a list with checkboxes to activate each single type of "cleaning action"
B) as items in the **segment editor** /filter (e.g. when disabled it globally)

**What do you think of this topic and the details?**
I think this has a huge impact on our statistics and in consequence on our interpretation and the things we do/change/add/modify on our websites
**Please add any comments and additional ideas!!**

**Comment by mattab** [comment]
Hello, please report all bots to our other popular Device Detector project, which also keeps tracks of bots: https://github.com/piwik/device-detector/
