### ISSUE TITLE
Widget size issues

### ISSUE THREAD

**Issue by p-banaszczyk** [piwik/piwik#5852]
I was looking for duplicates for a while, but couldn't find anything. If this however duplicates anything, please close this issue and paste original one in comment.

There are problems with some types of widgets and reports  - strictly related with columns  and page/dashboard layouts. Ie. 

Dashboard +  page titles:
http://i.imgur.com/lKYgpNV.png

Visitors + settings
http://i.imgur.com/9fuNlr0.png

**Comment by mattab** [comment]
this was fixed in Piwik 3
