### ISSUE TITLE
Daily Scheduled Reports sent one hour late

### ISSUE THREAD

**Issue by tschikarski** [piwik/piwik#5873]
Daily Scheduled Reports are sent about one hour later than specified in the report settings.

Version: Piwik 2.4.1
Server timezone: Europe/Berlin
Website timezone: Europe/Berlin
Email report schedule: Daily
Send hour: 12

E-Mail is sent at 13:05 local time or 11:05 UTC. Remark: At present it is summer time, therefore, Europe/Berlin is CEST = UTC+2

**Comment by mattab** [comment]
it's a very old issue, I' closing. If anyone still experience this bug, please open a new issue
