### ISSUE TITLE
UI/UX issue in narrow screens

### ISSUE THREAD

**Issue by MichalTomczak** [piwik/piwik#5878]
HI,

When using the dashboard, on a narrow screen, the two reports on the page blend in each other.

It would be nice if the design would be more responsive. So that the reports will be positioned underneath each other. 
One example pasted below.
![narrow screen](https://cloud.githubusercontent.com/assets/8134608/3672606/94c2f2f6-1262-11e4-9c08-c5a54bd6b9a0.png)

**Comment by mattab** [comment]
@mnapoli maybe the reports overlapping each issue has been / could be  improved with the bootstrap grid system?

**Comment by mnapoli** [comment]
Yes that issue is fixed by #7504

**Comment by mattab** [comment]
nice!
