### ISSUE TITLE
New admin setting: whitelist website URLs or hosts allowed to tracked visits

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#588]
Piwik statistics can be distortet by copying the JavaScript code to third party sites.
In the "Websites Management" you can add new sites with their URLs. But everybody can copy your JavaScript code to his own site and manipulate your statistics.

Piwik needs to be updated with a function that defines domains that are allowed to be counted.

**Comment by mnapoli** [comment]
There are several things to consider I guess:

1. prevent a 3rd party to track visits on a 3rd party website:
    - in that case we check that the tracked URL is in the authorized domain list
2. prevent a 3rd party to track visits on the tracked website: e.g. I could spam the demo to record 1000 fake visits on piwik.org homepage
    - here it's much more difficult because I see no way to differentiate between a normal tracker request and malicious tracker request? The referrer can be faked for example. One way would be to issue a token in `piwik.js` but we would have to make that token limited in time and unique for each `piwik.js`. But then again I can visit piwik.org, grab the token and spam demo.piwik.org with fake visits using that token…

I don't see a lot of value in fixing 1 if 2 is not fixed.

**Comment by mattab** [comment]
there is value in (1) because sometimes it can be simple human error that a wrong tracking code is set (or the wrong idsite) and it records wrong data in the UI. When this happens currently there is no way for users to filter out the traffic, which creates bad data (while it's not their fault). Once fixed it'll be just enabling a per-website setting "Only record data from the website URLs" (disabled by default). 

i've noticed that quite a few users have asked for this feature in the forums in the past...  

maybe we could try to do it as a third party plugin?  it would be a nice use case for a plugin that  adds a new per-website setting and make this easy for developers (maybe we also wait first for the Admin screen redesign in #7492).

**Comment by gaumondp** [comment]
@mnapoli maybe for #2 add a maximum actions per visitor value in a certain duration would help ?

Someone using httrack software to download a whole site will get as many hits as you got pages. As a webmaster, I'm not too happy to see +200 actions from a single user in 15 minutes when you have 10 000 pages... But right now I live with it.

I really don't know the complexity behind the general idea but let's be frank, fake visits are nasty.

**Comment by barbushin** [comment]
I read all comments, and I have 2 ideas how it implement it: 
1. Like this
![image](https://cloud.githubusercontent.com/assets/683352/8572987/0ec7f684-2598-11e5-9e95-31b09915e13e.png)
2. Or in more compact way
![image](https://cloud.githubusercontent.com/assets/683352/8573009/292a5cb0-2598-11e5-8a9c-2d720c865e5f.png)

I think the good place for that option is Admin - Manage Websites. 

Guys, what do you think?

**Comment by mattab** [comment]
@barbushin we already have the feature to exclude users based on user agents, see Administration > Websites:

![user agent exclude](https://cloud.githubusercontent.com/assets/466765/8591204/f5a75200-2626-11e5-9b8a-2d1834380949.png)


We don't need feature to exclude visits based on referrer. 

I think this feature could be simply done as a new checkbox, on a per-website basis, something like this:

![new feature](https://cloud.githubusercontent.com/assets/466765/8591373/290445b2-2628-11e5-8982-ae4f5edf0baa.png)

what do you think?

**Comment by JonasDoebertin** [comment]
@mattab That looks amazing! 👍

**Comment by barbushin** [comment]
That's nice to keep it simple and easy to use, but what about subdomains?

**Comment by mattab** [comment]
Good point, I reckon we allow all subdomains automatically as well, and rename the checkboxes/inline help to clarify this `Only track visits for actions on any of the website URLs: $URLs_here (and their subdomains)`

**Comment by barbushin** [comment]
@mattab And what if somebody just using multiple site instances on one domain, like `dev.piwik.com`, `stage.piwik.com`.. and `piwik.com` for production, and he don't want to setup different Piwik integration options for different environments?

**Comment by JonasDoebertin** [comment]
@barbushin Isn't it always a good practice to include your tracking code based on your environment? My `local`, `dev` or `staging` sites usually don't load the tracking code at all.

**Comment by barbushin** [comment]
@JonasDoebertin Of course it's not a good practice :) But how we can be sure that everybody are as smart as you?

**Comment by mattab** [comment]
@barbushin I think for our MVP version we can track all subdomains (to KISS). If users ask for possibility to "not track" sub-domains, we could re-visit our product vision?

**Comment by JonasDoebertin** [comment]
@barbushin We can't. But this is something you already had to think about all the time (for nearly any other analytics service, as well).

**Comment by barbushin** [comment]
@mattab Okay, so all we need it to add checkbox `Only track visits for actions on any website URLs`. But I'm not sure that I clearly understand what does it mean. Is it validation that referer equals to any of listed URLs?

**Comment by mattab** [comment]
I think the validation should check `&url=` tracking API parameter (not `urlref`) and check that this is part of one of the URLs set for this website.

**Comment by mattab** [comment]
Added FAQ for this feature: [ How do I force Piwik to only track Page URLs that belong to my website?](http://piwik.org/faq/how-to/faq_21077/)

**Comment by tsteur** [comment]
I just issued a PR to no longer match the subdomain as it was not mentioned in the UI and it was unclear. On the other side if any of these URLs specify a path we will now also check whether the given path is actually present

**Comment by ramramra** [comment]
Hi All 
I am facing issue with matomo user data info .I added multiple user ids in java script and i am trying to lookup for data on particular id But this data coming under singe user id only .Can  anyone please help me for this .Here is my added script
  _paq.push(['setUserId', 'piwik']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);

**Comment by tintjose** [comment]
> Hi All
> I am facing issue with matomo user data info .I added multiple user ids in java script and i am trying to lookup for data on particular id But this data coming under singe user id only .Can anyone please help me for this .Here is my added script
> _paq.push(['setUserId', 'piwik']);
> _paq.push(['trackPageView']);
> _paq.push(['enableLinkTracking']);

@ramramra  May be a late reply but I think you are hardcoding the setUserId to piwik so it will only output piwik as userId. You should fetch the dynamic userId like email or any name and then use that variable.
For Eg:
var userName= ....
 _paq.push(['setUserId', userName]);

Hope this helps!
