### ISSUE TITLE
Log analytics - UTF-8 link from search bug

### ISSUE THREAD

**Issue by soulcreate** [piwik/piwik#5885]
I use piwik/misc/log-analytics/import_logs.py for my log analytics.
A small part of queries is defined as ????. However, if you look at the source HTML, then everything is OK. 
 In the picture on the link address http://yandex.ru/yandsearch?text=%EA%F3%EF%E8%F2%FC+%E2%FB%EF%F3%F1%EA%ED%EE%E5+%EF%EB%E0%F2%FC%E5&lr=213 
 which was well converted into Russian. 
 It is observed on 20% of all requests from Russian yandex and google.
![piwik log analytics](https://cloud.githubusercontent.com/assets/2090261/3711572/0ec303d0-14dd-11e4-9d2f-24e2572e9134.png)

**Comment by soulcreate** [comment]
in php is very easy to adjust using the "rawurldecode" function
http://php.net/manual/en/function.rawurldecode.php

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
