### ISSUE TITLE
wrong statistics when filtering country

### ISSUE THREAD

**Issue by bglxx** [piwik/piwik#5903]
The results in "Visitors / Locations & Provider" statistics are wrong for July. Older months are okay.

I have set a segment filter:
  Country contains de
  OR
  Country contains ch
  OR
  Country contains at

to select the German speaking countries.

When I select "Visitors / Locations & Provider" without filtering, the country statistics are okay.

When I activate the segment filter, the county statistics are much to low. For example:
Without filter: 1379 visitors from Germany
With filter: 280 visitors from Germany

When I select the month June ore before, the statistics are okay.

Piwik Version is 2.4.1
PHP is 5.5.11
Mysql is MariaDB 5.5.37

**Comment by tsteur** [comment]
Do you use the log importer or the normal Piwik JavaScript tracker?

Do you know if you have browser archiving enabled or do you archive via the CLI (`php console core:archive`)?

I tried to reproduce but couldn't. The only thing that would explain this to me would be a problem with archive invalidation or so. Meaning an archive was created at some point but not invalidated and not rearchived afterwards. That would explain why it works with a different order of the countries as they were not archived yet. Is it maybe possible to get access to your Piwik installation and also to your database? If so, can you send us the credentials to hello (at) piwik.org?

**Comment by bglxx** [comment]
sorry for the late reply.
we use regular Piwik JavaScript tracker and there was no log import ever.

since now we have the default settings for piwik archiver (allow piwik archiving to trigger..." = yes)

do u need access to root level console or to the piwik website?

**Comment by mattab** [comment]
Hi @bglxx can you still reproduce this issue with the latest Piwik stable version?

**Comment by bglxx** [comment]
Hi @mattab 
I've tried all known combinations that triggers the error before and now it works well.

My version is 2.12.1 and I suggest to close this bug. I will monitor it in future if this prob is coming back.
