### ISSUE TITLE
When editing a SMS report, hide the row "(optional) Display options"

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5904]
The setting "(optional) Display options" should not be displayed on an SMS report edit screen. (the setting only applies to email reports)

**Comment by tsteur** [comment]
This seems to be already done.

**Comment by mattab** [comment]
bug still here on master (earlier commit does not fix it). the bug is that when editing a SMS report the `Display options` bit should be hidden eg. in: 
![sms optional options](https://cloud.githubusercontent.com/assets/466765/6075066/1008f4d8-ae30-11e4-98d1-cb6fc874fb61.png)

**Comment by tsteur** [comment]
To make this issue more clear. It is not a problem when someone switches from Email to SMS. It is only a problem when editing an already saved entry that has the type SMS
