### ISSUE TITLE
visitor profile: linebreak for type event incorrect

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5916]
in visitor profile the linebreak for type event is incorrect/broken.
At the same place it works fine in visitor log
FF piwik 2.5b1
please see attchements
![2014-08-04_07h14_11](https://cloud.githubusercontent.com/assets/5681880/3793434/310080e2-1b97-11e4-9713-196313cc0b04.png)
![2014-08-04_07h17_00](https://cloud.githubusercontent.com/assets/5681880/3793435/34110892-1b97-11e4-80fd-a8d0efe1a74f.png)

**Comment by sgiehl** [comment]
Can't reproduce that with latest piwik version

**Comment by mattab** [comment]
Hi @hpvd if bug still exists please reopen!
