### ISSUE TITLE
vistor profile: optimize map zoom level possibilities

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#5917]
vistor profile: optimize map zoom level possibilities:
1) on opening the map: zoom as near as possible to catch all locations
2) make it possible to zoom even more on next click/ or ad +- zoom?
please see attachments for actual status in piwik 2.5b1
![2014-08-04_07h35_00](https://cloud.githubusercontent.com/assets/5681880/3793545/c5ecf1ba-1b9a-11e4-9e73-8a588cbbc645.png)
![2014-08-04_07h38_43](https://cloud.githubusercontent.com/assets/5681880/3793547/c823a654-1b9a-11e4-9d02-c3c7919bee2f.png)

**Comment by hpvd** [comment]
could be reproduced in 2.13b1

**Comment by mattab** [comment]
Hello @hpvd - Duplicates https://github.com/piwik/piwik/issues/4301 I believe (please post there, if something is missing)
