### ISSUE TITLE
Not visible "Save" button in Settings

### ISSUE THREAD

**Issue by rivadav** [piwik/piwik#5978]
Settings

**Problem**
Since most of the settings need additional confirmation after editing them, this action should be easily accessible to users. Currently, "Save" button is in different places and sometimes users have to scroll in order to see it.

Sometimes it's also not clear if "Save" relates only to specific section or the whole page (like in Trusted Piwik Hostname).

![wlnpyhzku5](https://cloud.githubusercontent.com/assets/1769990/3875742/011213f0-2155-11e4-8940-8b83dacd6c68.gif)

---

**Proposed solution**
One of possible solutions is to place "Save" button on the bar which will be pinned to the bottom of screen. Thanks to this, it will be always easily accessible and there'll be confusion to which section it relates to.
However, it must used cautiously with in-line edition of elements to avoid confusion.

![screenshot-2014-08-11-15 51 42_proposed](https://cloud.githubusercontent.com/assets/1769990/3876959/8959286e-2161-11e4-8f1b-46968d9047d5.png)

**Comment by mattab** [comment]
Maybe this is easy to add? it's a small trick, but would really help first-time users!

**Comment by tsteur** [comment]
Proposed solution sounds a bit like a floating action button ( https://www.google.de/design/spec/components/buttons-floating-action-button.html ) which also has some downsides ( see eg https://medium.com/tech-in-asia/material-design-why-the-floating-action-button-is-bad-ux-design-acd5b32c5ef ) but in this case it would be good I think.

From a usability perspective maybe we could display a save button below each category and save the specific setting on click via ajax and show notification on success/error. It keeps mouse movements short and the action button would be close to the settings so it's not complicated to find the action button etc. Of course it's more work though

**Comment by mattab** [comment]
> From a usability perspective maybe we could display a save button below each category and save the specific setting on click via ajax and show notification on success/error. It keeps mouse movements short and the action button would be close to the settings so it's not complicated to find the action button etc. Of course it's more work though

If we do this there could be an overload of "Save" buttons...


If we're not sure about this one, let's move it back to `Short term`. 

Another idea would

**Comment by tsteur** [comment]
I don't think there would be too many save buttons as each section is quite long anyway, would have to test it. Maybe there's an even better solution... or maybe we can actually split it into different pages etc.

**Comment by tsteur** [comment]
We should move it back to `Short term` maybe as it takes some time to think about a proper solution and possibly we'd even have to implement different solution to see which one works best. Eg to see whether there would be too many save buttons or not, whether settings could be managed differently better etc

**Comment by sgiehl** [comment]
Guess we can close this one? There is now a save button for each section, which should be good enough imho

**Comment by tsteur** [comment]
:+1:
