### ISSUE TITLE
Piwik 2.5.0 Update broken on IIS  

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6019]
It fails to copy some files see attached screenshot although permissions are recursively set (writable)

Windows 2008 R2
Mysql 5.1.57
PHP 5.3.6

![piwikupdatebroken](https://cloud.githubusercontent.com/assets/273120/3951791/48603a9e-26db-11e4-9e30-731d392e0d9d.png)

**Comment by ThaDafinser** [comment]
@tsteur still a problem with newer version?

**Comment by tsteur** [comment]
No clue, it was reported by a user. I reckon we can close it as we haven't heard anything similar again. It would be nice to hear some feedback from IIS users
