### ISSUE TITLE
Make it easier to create Segments with Custom Variables

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6031]
**Context**
Piwik lets you assign [Custom Variables](http://piwik.org/docs/custom-variables/) to visit and/or pageviews (and [site searches](http://piwik.org/docs/site-search/), [events](http://piwik.org/docs/event-tracking/), etc.). Users can then create [Custom Segments](http://piwik.org/docs/segmentation/) to get reports for all visits and pages matching a particular Custom Variable.

**Goal**
The goal of this ticket is to make creating segments with custom variables more user friendly.

**Why are segments hard to use with Custom variables?**

To create a segment with a custom variable, user has to know which slot the custom variable was created in (slot is a number from 1 to N). A segment to select only page views tagged with a particular author would like this: `customVariableNamePage1==author,customVariableValuePage1==xyz`

This is hard to use by users who may not know which slot was a given custom variable set.

**Proposed solution** 

 * Create new segments providing shortcuts, ie.
  * `customVariableNamePage==name_here` which would automatically select any page view with a custom variable name set with `name_here`. The generated SQL would look something like `custom_var_k1 == name_here OR custom_var_k2 == name_here OR custom_var_k3 == name_here OR custom_var_k4 == name_here OR custom_var_k5 == name_here`
  * similarly create new segment for the value `customVariableValuePage`
  * and the same segments for the "Visit" scope: `customVariableName` and `customVariableValue`

 * the auto-completer for the segment `customVariableName` would show all possible custom variable names for all slots. 

Adding this new "magic segment" matching any slot should make the act of creating custom segments with custom variables much easier. Thoughts?

**Comment by tsteur** [comment]
Added comment in https://github.com/piwik/piwik/pull/8754#issuecomment-139464546 also seeing it a bit dangerously as results can get inaccurate when using it right? Eg when a search term matches different custom variables. Eg `contains 2.` may apply to a custom variable `Android version number` but also `App version number`
