### ISSUE TITLE
Ability to exclude visitors using Dynamic DNS DDNS

### ISSUE THREAD

**Issue by cableghost** [piwik/piwik#6046]
Feature request to add option to exclude DDNS connections. It's cumbersome to continue adding exclude cookies in all my devices.

If the following script is still viable, could it be turned into a plugin? (http://bit.ly/1rqyQmj)

**Comment by sgiehl** [comment]
I'm about to release a small plugin implementing that.
See https://github.com/sgiehl/piwik-plugin-ExcludeByDDNS
