### ISSUE TITLE
Migrate all core plugins to use plugin/composer.json instead of getInformation()

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6061]
Once this is done we can remove some calls to "load translations" before plugins are loaded in `FrontController::init()`. 

It would also showcase the plugin.json and we wouldn't treat core plugins differently anymore.

This can be scripted, so one would not have to create them manually. Goals plugin is maybe the only one which cannot use plugin.json, not sure.

**Comment by mattab** [comment]
Using plugin.json instead of `getInformation` was done in Piwik 3
