### ISSUE TITLE
Multi-Channel attribution modelling

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6064]
The goal of this ticket is to implement a first version of multi-channel attribution across digital channels, and provide of attribution modelling in Piwik.
## Context

Piwik can track Goals and Ecommerce conversions. By default, Piwik attributes 100% of conversion credit to the last referrer that was used before the conversion (sometimes called `Last Non-Direct Click Attribution Model`). A [setting can be changed](http://piwik.org/faq/general/faq_106/) in the config to credit instead the first referrer that was used. This attribution model works quite well for most use cases, but it is too basic and limiting for advanced marketing users spending money across many channels. 

This ticket aims to improve this attribution modelling to better credit the various referrers and campaigns used by visitors before they convert. 
## New attribution models

As a Piwik admin I would like to select one of the following attribution model:
- Last Non-Direct Click Attribution Model. (current)
- First Interaction/First Click Attribution Model. 
- Linear Attribution Model.
  - _The Linear model might be used if your campaigns are designed to maintain contact and awareness with the customer throughout the entire sales cycle._
- Time Decay Attribution Model. 
  - _The Time Decay model assigns the most credit to touchpoints that occurred nearest to the time of conversion. It can be useful for campaigns with short sales cycles, such as promotions._

Note: Linear Model and Time Decay model define a look back window in days.
## Tasks
- piwik.js enhancements: 
  - store the last N referrers in the first party cookie `pk_ref` (currently tracks only the last or first referrer used)
- Tracker enhancements:
  - New console command to modify Piwik schema to measure more than currently one referrer per visit. This is similar to the command to [add more custom variables](http://piwik.org/faq/how-to/faq_17931/). 
  - The following fields are currently used to keep track of referrers: `referrer_type`, `referrer_name`, `referrer_url`, `referrer_keyword`. When adding a new referrer slot, it would look like: `referrer_type_1`, `referrer_name_1`, `referrer_url_1`, `referrer_keyword_1`, `referrer_time_1`. User can choose to create 1 or 5 or 10 referrers slots, depending on how much precision is needed.
  - Refactor Tracker to record the N referrers for each new visit. 
- Aggregating - TBD
- Reporting - TBD
- Create user guide
- Update [this FAQ](http://piwik.org/faq/general/faq_106/).
- Create new FAQ. 
## Outstanding questions
- Currently we do not credit `Direct entry` as a referrer type. Should we consider crediting Direct entry as a valid Referrer? 
## Out of scope

The following enhancements are not in the scope of this issue, but they could be implemented later as we collect all necessary data to build these reports.
- **Path Length report** 
- **Time lag report** - see amount of time customers take from the first channel interaction to conversion.
- **Top path report** - show the top different routes customers take before the conversion.

Note: these useful reports are found in Google Analytics. 

The following enhancements and ideas could be worked on as an extension of this work:
- Offline attribution - attributing the offline impact (revenue/brand value/phone calls/etc) driven by online marketing and advertising.
- Attribution across multiple screens - attributing accurate impact of our marketing and advertising efforts across multiple devices (desktop, laptop, mobile, TV). see #3490

Learn more in [this post](http://www.kaushik.net/avinash/multi-channel-attribution-definitions-models/).

**Comment by mlongley** [comment]
This idea is definitely necessary for piwik to stay competitive with other analytics solutions. Glad to see that it is making progress. Any updates in 2015?

**Comment by NilsEngelbach** [comment]
This is one of the features I am really missing in piwik. 
Beyond the 4 new attribution models the admin should have the possibility to make a custom attribution model. E.g. when a customer was reached by a email campaign, give all credit to this campaign etc.
Also it should be possible to credit value to the direct traffic, just because you have not paid for it means it is worth nothing.
How much time do you think would it take for someone new to the code, to implement this feature?

**Comment by Jeremlicious** [comment]
+1 Multi-Channel attribution modelling is an important feature. First or last click attribution models are not enough for marketers.

**Comment by mrusonis** [comment]
Has anyone found a workaround for this? I want to track both "first click" and "last click" at the same time. I'm currently trying to do this with two trackers but it doesn't seem to be working.

**Comment by mattab** [comment]
The Multi Attribution channel reporting plugin has been published :tada: 

it is available as a premium plugin which you can get here: http://plugins.piwik.org/MultiChannelConversionAttribution

Learn more in the user guides: https://piwik.org/docs/multi-channel-conversion-attribution/
and FAQ: https://piwik.org/faq/multi-channel-conversion-attribution/

It's a awesome product to optimise marketing spends, let us know what you think about it!
