### ISSUE TITLE
Measure how far users scroll down the page

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6069]
It would be great to provide a simple way to track how far users have scrolled down the page? eg. http://www.optimisationbeacon.com/analytics/track-how-far-your-users-scroll-in-google-analytics/

Or somehow more generic measurement of engagement with the page: see also this Google analytics plugin: https://github.com/robflaherty/riveted
`measuring the amount of time users are actively engaged (e.g., clicking, scrolling, using the keyboard) and then reporting the data to Google Analytics in frequent intervals.`

**Comment by cemdev** [comment]
I would LOVE to see this.  We looked at implementing it as a custom page variable - but those need to be set before trackPageView() - so that doesn't work.  Any thoughts on how to attach this data to page views?  We'd be happy to write a plugin - just need to know where to start, or even if it's possible without a change in core.

**Comment by mattab** [comment]
@cemdev Maybe you could track an Event instead of using Custom Variables? http://piwik.org/docs/event-tracking/

**Comment by cemdev** [comment]
it looks like events are session scoped, not page scoped, so to do that I'd need to come up with a way to map events back to pages. I don't see how to easily do that (maybe i'm missing something?). How would I map a scroll event back to the page that was being scrolled on? I suppose I could try page url or page title matching - but that seems pretty fragile.

**Comment by Hopelessone** [comment]
+1 for this important feature to be added. e.g. http://www.searchenginepeople.com/blog/16063-page-scroll-depth-analytics.html

**Comment by mattab** [comment]
Note: this feature is part of [Heatmap & Session recording](http://plugins.piwik.org/HeatmapSessionRecording) premium plugin.

You will see a beautiful and useful Scroll Map report:

Scroll heatmaps use colors to visualize how far down in a page your visitors scroll. When you hover on the Scroll heatmap, you see exactly how many percent have scrolled down to a certain position. This lets you for example find out if there is important content positioned too far down the page, whether your visitors are encouraged to scroll, and more.

![scrollheatmap](https://user-images.githubusercontent.com/466765/27267990-b53ed91c-5500-11e7-80a0-75f578600294.png)

See other benefits of Heatmaps in the user guide: https://piwik.org/docs/heatmaps/

**Comment by MMMXXXZZZ** [comment]
Hi, I believe it's insulting to close this suggestion, as users are asking for this feature to be implemented for free, considering that events in Matomo cannot have their values modified, so scroll depths are difficult to work with when the reports are populated with dozens of scroll 'actions' for each chosen scroll depth percentage. Please reconsider accepting help on this feature for free.
