### ISSUE TITLE
When new plugins are released on the marketplace, the CI build should not always fail

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6076]
## Context 
When a new plugin is released on the marketplace we have a script that runs the Piwik unit + plugins + system tests. This is meant to detect easily whenever some plugins fail the Piwik platform tests. This setup is for information purpose only. 

## Example

When the plugin LdapConnection 0.3.0 was released, this build ran:  
https://travis-ci.org/piwik/piwik-tests-plugins/builds/33558430

This build and all builds triggered on new release are failing in similar way. 

The goal of this ticket is to make the build pass if the plugin does not cause any test to fail. (eg. if plugin adds widget or reports then it will fail and that's fine).

**Comment by diosmosis** [comment]
Next steps:

1) Modify marketplace code so instead of creating a branch to test plugins a commit is made so the .travis.yml file autoupdates.
2) Continue fixing causes for test failures.

**Comment by mattab** [comment]
Moved to 2.12.0 - maybe this will be done along with #6539 since 6539 may need  the piwik-tests-plugins build to run the Phpstorm plugin that will detect @api and @deprecated calls - as mentioned by @diosmosis
