### ISSUE TITLE
New Goal Funnels plugin

### ISSUE THREAD

**Issue by JackieBiz** [piwik/piwik#6080]
I'd like to show an actual funnel for my goals...is it possible to create our own images to show the data in the dashboard?

**Comment by Tobias-Conrad** [comment]
no sence to referre from one post with no solution to another!!
Plugin to provide funnel analysis report #7204
https://github.com/piwik/piwik/issues/6080
Please keep one post open or just fix funnel for us please.

**Comment by mattab** [comment]
@Tobias-Conrad that's what we did, this issue is still open and is the one where we shall discuss Goal Funnel feature in Piwik.

**Comment by Tobias-Conrad** [comment]
Some one make this compatible to Piwik 2?
https://github.com/jesstelford/funnels

**Comment by Tobias-Conrad** [comment]
add urls, goals, campaigns, ... To a success funnel.
https://clicky.com/web-analytics/real-time-goal-tracking

I think its already nearly there.
Per page I can see the in and outs, where the visitors come from and go to.
Just chain this charts together...

**Comment by mattab** [comment]
Goal Funnel feature in Google Analytics  is really well described in this blog post: https://blog.kissmetrics.com/conversion-funnel-survival-guide/

For Piwik I reckon we could implement pretty much the same as it's powerful yet easy to use. Likely it will only work for "data going forward". Interestingly in GA they do not support segmentation for the funnel report, but for sure in Piwik it should be possible to segment the funnel as well.

**Comment by dbharath** [comment]
Just wanted to know the status, is thi done ?

**Comment by dbharath** [comment]
Just asking, @6080 mentioned in Piwik RoadMap that it will get released in sep 2015.

**Comment by willdurand** [comment]
Anyone?

**Comment by KyleShurtleff** [comment]
I agree that this is critical and an updated 'where it is on the roadmap' is at least a good first step.

**Comment by mattab** [comment]
Hi everyone,

The development is finished and Funnel plugin is currently in testing with a few selected partners.

The plugin is not open source and not free. It was decided to make it a premium plugin and provide it as part of Piwik Enterprise. To learn more about it and get the Funnel plugin, please enquire to Piwik PRO: https://piwik.pro/contact/

The plugin works in this way:
- for each goal, you can enable the funnel
- a funnel is defined by a list of steps. each step can be optional or required.
- you can then view the complete Funnel report visualisation, for each Goal where the funnel was defined

If you have any question feel free to ask
Cheers

**Comment by Tobias-Conrad** [comment]
Sorry! But a paid plugin was not my request. Google analytics does it for free!In piwik I have to pay?
So I will sent you an invoice 400 EUR + tax for my time I invested to initial starting and pushing the plugin, I thought it will be open source.

Or tell me how can I and my self hosted piwik get this plugin?

I am very angry at Mr. Aubry.
Tobias Conrad
Ps: if you are doing the same with the video tracking I initial started and pushed then I will go away and never come back.

----- Reply message -----
Von: "Matthieu Aubry" <notifications@github.com>
An: "piwik/piwik" <piwik@noreply.github.com>
Cc: "Tobias-Conrad" <tobiasconrad@leupus.de>
Betreff: [piwik] Goal funnel (#6080)
Datum: Do., Sep. 17, 2015 06:09

Hi everyone,

The development is finished and Funnel plugin is currently in testing with a few selected partners.

The plugin is not open source and not free. It was decided to make it a premium plugin and provide it as part of Piwik Enterprise. To learn more about it and get the Funnel plugin, please enquire to Piwik PRO: https://piwik.pro/contact/

The plugin works in this way:


for each goal, you can enable the funnel
a funnel is defined by a list of steps. each step can be optional or required.
you can then view the complete Funnel report visualisation, for each Goal where the funnel was defined


If you have any question feel free to ask

Cheers

&mdash;

**Comment by willdurand** [comment]
Not open sourcing it is a thing, but would it be possible to buy it for private instances?

We run our own Piwik in France to avoid giving data to third-party services, like a lot of people I think. Piwik Pro is considered a third-party service unfortunately, just like GA, Mixpanel, etc.

**Comment by mattab** [comment]
Hi @willdurand 

Yes, you can buy the plugin and run it on your private instance(s). The Funnel plugin (as well [all other premium plugins](http://piwik.pro/plugins)) are provided to Piwik Enterprise clients. https://piwik.pro/enterprise

**Comment by hpvd** [comment]
another way to do concrete visitor way analysis and rough funnel analysis is described in here: https://github.com/piwik/piwik/issues/7533

**Comment by rajerino** [comment]
@mattab Is the Funnel plugin still being sold to run on private instances? Sales responded to me that premium functionality is only offered as part of Piwik Enterprise.

**Comment by Tobias-Conrad** [comment]
developed with the help of the public and available only via Piwik Pro and not on self hosted Piwik.
i left piwik months ago because of lake of this feature and the video tracking feature, ...
go to google analytics all free and very fast. Piwik Pro is not hosted on your server, same as with google analytics. so why not use google analytics?

**Comment by hpvd** [comment]
@Tobias-Conrad @willdurand
you comments+thoughts+questions go roughly into same direction mine were going, when asking for details on strategy of pro plugins in general in https://github.com/piwik/piwik/issues/9169

**Comment by mattab** [comment]
Funnel plugin is now available to Piwik PRO clients, and will soon be advertised on http://piwik.pro/plugins

More information regarding PRO plugins will be published on the blog in January/Feb. Stay tuned in #9169

**Comment by KyleShurtleff** [comment]
Glad to see this got added... however I don't see it on the Plugins page you linked. I am a Pro customer. Any other limitations/restrictions as it rolls out?

**Comment by mattab** [comment]
Hi @KyleShurtleff - we are currently working on letting Pro clients view, download and install any premium plugin from within Piwik just like you can already browse and install the free plugins. In the meantime to get the Funnel plugin, please ask your support coordinator they will send it to you. Hope you enjoy it and gain insights on your conversion funnels!

**Comment by chihoko** [comment]
It seems to me that you're deprioritising your strongest supporters (self-hosted)? @mattab please explain how we get this plugin or at least what we need to tell our management about it. Thank you.

**Comment by mattab** [comment]
Hi @chihoko we are heavily investing in Piwik platform and also creating a thriving open source business. it is a game of balance and focus so we can achieve our goals and help everyone liberate & keep control of their data. We will post a blog post in coming weeks to explain more about Piwik PRO & Paid plugins. To access the paid plugins you need to become a Piwik PRO enterprise client, find more info @ https://piwik.pro/enterprise/

**Comment by chihoko** [comment]
Hi @mattab thanks for the update and of course your amazing efforts on this project. In your last sentence its not clear whether you are saying:
a) If you need a paid plugin now then your only option is to upgrade to PRO but in the near future we will make paid plugins available to self-hosted customers.
b) Paid plugins will only ever be available to PRO customers.

**Comment by mattab** [comment]
KissMetrics have a very powerful Funnel feature: https://blog.kissmetrics.com/new-funnel-report/

Would be awesome to have something similar for Piwik! :+1:

**Comment by mattab** [comment]
Hello everyone,

We've just launched the new Funnels premium plugin! The premium Funnels plugin provides really powerful Conversion Funnels analytics directly in Piwik. Learn more & get the plugin in the [Funnels Marketplace page](http://plugins.piwik.org/Funnels). Check the [Funnels User Guide](https://piwik.org/docs/funnels/) and [Funnels FAQ](http://piwik.org/faq/funnels) for more information. Looking forward to hearing your feedback!
