### ISSUE TITLE
Perform compatibility check when a plugin is about to be installed or published on the Marketplace

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6150]
In #6149 I reported about the danger of generated plugins and components which will fail on older Piwik versions.

For me this is such a critical problem for the quality of the platform to go so far to perform checks / analyze a plugin which methods it is using and based on that update / correct the required Piwik version dynamically. For instance when publishing it on the Marketplace or even in Piwik itself when updating Piwik or a plugin to prevent ending up in a no longer usable Piwik. 

It could be for instance done by turning the PHP code into an abstract syntax tree and checking whether all the methods exist in that specific Piwik version. We could also analyze the `@since` annotations but don't think this would actually work since it is likely that a core developer forgets to set it and we do not have them currently for all methods. The behavior of a method should not change so checking for existing methods should be enough. In case we do break compatibility for a method - for instance by throwing an exception where none was before - we could not really detect it I reckon. Maybe there are solutions and other problems...

We have similar issues for themes. This should then be a separate issue later. Here we could for instance check whether the used less variables (which is the API basically) actually exist. As there are currently no themes it is not so important but it would be good to provide a good platform that guarantees a certain quality from the beginning.

Seeing this resolved mid or long term. For the quality of the platform definitely rather mid term / soon. Especially as it is not that complex to resolve I think.

**Comment by mattab** [comment]
Our current mechanism is to
* ask plugin developer to specify a maximum version supported by their Plugin
* we now have generators for plugin and the generator will automatically mark the plugin as requiring the current Piwik version the developer is using (in https://github.com/piwik/piwik/blob/2.16.2/plugins/ExamplePlugin/plugin.json#L7-7 )
* few months ago we started some work on a phpstorm plugin that would automatically detect plugin code that calls deprecated code or non existing code, but this project didn't quite complete yet: https://github.com/piwik/phpstorm-plugin-piwikstorm

I suppose we can close issue and reopen later if we decide something has to be done.

 @tsteur if i'm wrong please reopen :+1:
