### ISSUE TITLE
use https://github.com/interagent/http-api-design to create list of API design improvements

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6158]
The link in the title is a list of HTTP API guidelines used by Heroku. It may have many useful ideas that can be implemented in Piwik.

 https://github.com/interagent/http-api-design

    Foundations
        Require TLS
        Version with Accepts header
        Support caching with Etags
        Trace requests with Request-Ids
        Paginate with ranges
    Requests
        Return appropriate status codes
        Provide full resources where available
        Accept serialized JSON in request bodies
        Use consistent path formats
        Downcase paths and attributes
        Support non-id dereferencing for convenience
        Minimize path nesting
    Responses
        Provide resource (UU)IDs
        Provide standard timestamps
        Use UTC times formatted in ISO8601
        Nest foreign key relations
        Generate structured errors
        Show rate limit status
        Keep JSON minified in all responses
    Artifacts
        Provide machine-readable JSON schema
        Provide human-readable docs
        Provide executable examples
        Describe stability

**Comment by mattab** [comment]
Refs Build a RESTful API for Piwik #6000
