### ISSUE TITLE
Clarification of Piwik's goals regarding privacy

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6160]
What does Piwik consider to be good behavior when tracking behavior? How do we believe Piwik users (big companies, small companies, etc.) should treat their users in terms of supporting their rights? How can we encourage such 'good' behavior?

Piwik's stated support for matters of privacy is evident, but as far as I can see translates only to allowing people to own data they track. Perhaps more can be done to make people care about privacy.

See for a possible example: http://www.ianwaring.com/2014/06/08/cloudkit-now-thats-how-to-do-a-secure-database-for-users/

"Apple take this one stage further, in that any application that asks for any personal identifiable data (like an email address, age, postcode, etc) from any table has to have access to that information specifically approved by the handset owners end user; no explicit permission (on a per application basis), no data."

The goals we come up with can influence/manifest new directions in UX.

**Comment by mattab** [comment]
We've made some good progress in clarifying privacy in the last few months. This issue stays open to keep discussion alive, but i'm moving to Mid term milestone.

**Comment by mattab** [comment]
https://github.com/piwik/piwik/issues/6160#issuecomment-55476922
