### ISSUE TITLE
New Piwik Certification program 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6172]
The goal of this issue is to discuss and brainstorm how to create a Certification for Piwik to certify staff on Piwik software platform and general Analytics mindset. 

**Certification topics**
-    installing Piwik,
-    setup tracking,
-    track custom variables,
-    site search,
-    setup goals,
-    learn to use the UI,
-    what to do if traffic loss,
-    etc.

**Proposed steps**
- Prepare material for users to learn Piwik, provide better guides, PDF containing all Piwik User Guides #5315
- Think of the most common 20 steps piwik users go through in the first 6 months of use
- Map them out as question and answers
- link to the documentation page when applicable
- If missing docs, let's add them, write them now. An example such doc: [Google analytics blog guides](http://www.simplybusiness.co.uk/microsites/google-analytics-guide/).

**Later steps**
- There is an opportunity to create and translate from / to several languages. For example in French or German there would be need of such certification and maybe Piwik users willing to help
- Opportunity to run the Certification via a professional system such as the one used by Symfony to run the certification in 4,000+ centers around the world! See their [FAQ page on pearsonvue](http://pearsonvue.com/sensiolabs/).
- Pick a fair price for the certification. Ideally just enough to cover the certification costs from provider eg. pearsonvue. Does anyone know the costs? Ideally, Piwik Certification will be $50 or so.
- For people passing the tests successfully, we want to give recognition!
  - support [Open Badges](http://www.openbadges.org/) a new online standard to recognize and verify learning
  - user can display on their website this badge, which links to a subdomain at Piwik, maybe certified.piwik.org - It would be a page with a brief bio, location and a link to certified user' site.

**Inspirations**
- [Google Analytics Certification](https://google.starttest.com/)
- [Symfony certification](http://sensiolabs.com/en/symfony/certification.html) 
- [Puppet certification](https://puppetlabs.com/services/certification)
- [DAA Cert Test](http://www.digitalanalyticsassociation.org/certification) 

> The DAA Cert Test is a true certification, meaning it tests your ability to do the job over a wide set of circumstances, rather than what you can remember from courses and books. [...] many analysts tend to specialize or be more familiar with certain areas than others, so may want to seek out education in those less familiar areas prior to taking the test. A good way to determine if this might be true for you is to download the Knowledge Required for Certification document here: http://www.digitalanalyticsassociation.org/?page=knowledge_required and review the topics to see if there are any areas you might want to brush up on. Then you can decide which, if any, courses you might want to take or books you might want to read, etc. to prep for test.
> Jim Novo

**Comment by evelascosilva** [comment]
Hi guys,

I'm really interested in this project.

I believe that Piwik need a Professional Certification how Google Analytics.

The next step could be to create the Academy similar to Google Analytics where the users can see videos, make exercises and download documents.

Also I think that the Piwik team can appoint "boss or ambassador" in each country, for example, NanorPiwik could be ambassador in France and I could be ambassador in Spain.

Each ambassador it should prepare documentation in your language for a new users.

Conference? Merchandising? Guides? Videos? Badges?

The price? I think that $50 is ok and only must renew if Piwik have a lot of important changes.

I go to write a post in a blog about Piwik, I want make an appeal to all spanish users that use Piwik, asking for recognition to this Certificate.

Bye,

Enrique.

**Comment by evelascosilva** [comment]
Good Morning guys,

I'm making a course of Web Analytics thanks to platform Activate by Google:
http://www.google.es/landing/activate/formate/

Each module have questions and exams, look at this:

----- First Module -----

Exercises:

1. Do you consider one or two visits in Google Analytics if a user visits a webpage at 23:50 and lasts until 00:19 the next day?

a) One
b) Two

Comment: The expiration date for completion involves two visits here

2.- The websites generally use only Technical Cookies?

a) Yes
b) No

Comment: In general use Cookies and advertising analysis without excluding other

3. Is it mandatory to collect the user's consent before practicing behavioral advertising?

a) Yes
b) No

Comment: The consent must be obtained before collecting personal data as necessary to ensure that those data subjects are aware of consenting and from what consenting

4. Were you able to configure your account, user profile property and Google Analytics?

a) Yes
b) No

Comment: In the administration of Google Analytics

5. Were you able to extract the report "Searching the site" with Google Analytics?

a) Yes
b) No

Comment: It gives me valuable information about the words users search within my Web site

Exam:

1. Complete the sentence: "The analytical Web serves to ...

a) Setting goals for growth. "
b) Set the intentions of the creators of a web "

2. Can a website have more Pageviews who visits?

a) No
b) Yes

3. Differences between analytical system for logs and labels

a) In a system logs information to the server is sent to navigate
b) In a system logs are always measured downloaded pages more than once

4. The rate of healing in the metrics of a website is to ...

a) ... that the website has more than Pageviews Unique Users and Visitors Pageviews that
b) ... that the Web site has more pages views Visits and more visits to Unique Users
c) ... that the website has more visits to Unique users and unique users that Pageviews

5. What is a "Referral"?

a) A reference content and excellent online
b) Are the references to sources for which a visitor accesses a Web page

6. Five basic metrics for Web analysis

a) Unique Visitors, Visitors, Pageviews, Bounce Rate, Average Time on page
b) Unique Visitors, Visitors, Pageviews, Real Time, Searching the site

7. When is originating a Page View as Google Analytics?

a) When viewing a page from a website that the tracking code Google Analytics is controlling occurs.
b) When the user accesses a page of a website without further

8. A high bounce rate is ...

a) Always symptom of a serious problem in the Web site
b) It is a symptom of a possible problem with the web site, but not always

9. What is the "Engagement"?

a) It is a positive mix of Visits + Social Media + Average Time
b) a positive mix + + Percent Visits Pageviews Bounce + Average Time
c) A positive mix Visitors + + + Demographics Average Pageviews content

10. What data yields a digital measurement tool panelists?

a) ... unique users, page views, reach, time, page views and sociodemographic
b) ... unique users, page views, time on page and page views

11. Definition of Web Analytics

a) Is the collection, measurement, analysis and reporting of data extracted from users' browsing a Web site to understand and optimize their use.
b) Is the science websites.

12. When finished, in general, a session in Google Analytics

a) At 30 minutes into the session usually
b) At 20 minutes into the session usually

Sorry for my English, I hope to improve my write.

Bye,

Enrique

**Comment by MagicFab** [comment]
@evelascosilva please don't copy copyrighted content here, specially not from GA offerings/pages. Could you please remove your content? 

"El uso de nuestros Servicios no te convierte en titular de ninguno de los derechos de propiedad intelectual de los mismos ni del contenido al que accedas. Solo podrás usar el contenido de nuestros Servicios si te autoriza su titular o si está permitido por la ley. "
http://www.google.es/intl/es/policies/terms/regional.html

**Comment by MagicFab** [comment]
At the Berlin Piwik meetup another way of recognizing Piwik exceptional contributors offering commercial services was discussed, I proposed the term "Community Professional", perhaps this could be a requirement/distinction in the certification. See https://trello.com/c/DDIKEKDY/18-12-20-12-50-how-do-piwik-org-project-and-piwik-pro-company-sit-together-are-organized-discussing-the-new-team-page

**Comment by evelascosilva** [comment]
Hi @MagicFab,

Sorry for to copy this content but only was an idea :+1:

If I can make something...I'm your man! ;-)

**Comment by gibsonsdad** [comment]
The best way to implement a database of questions as I think Nanor suggests is to use a computer adaptive testing system and/or require the test be taken proctored. Both solutions would be quite easy to implement.. As to what should covered by such a certification assessment, it will need to satisfy employers.. There should be an effort to identify and survey those organizations who might hire either as freelancer and ask what evidence of skills they think are vital.

**Comment by NanorPiwik** [comment]
Hi there,
I worked very hard this week and if everything goes according to the plan, end of this week-end I should be able to provide you with an alpha version of the certification made of 100 questions (in French), I used Lime Survey as it is Open Source for the certification platform. Hope you will like it.

**Comment by NanorPiwik** [comment]
Hi there,
Here is what I succeeded in doing so far : http://pk-certification.limequery.com/578922?lang=fr I still need to understand better how Lime Survey is working. At the moment the final score cannot be displayed which is a lot of frustration. Still working on it.

**Comment by ashgoodman** [comment]
Hi guys, where do things stand with regards to piwik certification?

Suggested study materials?

**Comment by StefanKoning** [comment]
In collaboration with many Piwik experts and enthusiasts, we finally established an official Piwik Certification Program! Here is the link to the certification website: https://certification.piwik.org

Please find the official announcement and additional information on the certification exam here: https://certification.piwik.org/piwik-launches-certified-professional-credential/

I wish you all the best with passing the exam and becoming officially recognized as a Piwik Certified Professional!

Cheers,
Stefan Koning

**Comment by MagicFab** [comment]
@StefanKoning although it's great news, it's frankly disappointing this shows up without a single previous comment, invitation to participate or other related comment on this issue report.

I noticed the date of birth is a requirement at registration, unfortunately this will be filled by invalid information if it remains a hard requirement. Could this be dropped from the registration form?

**Comment by mattab** [comment]
Hi @MagicFab 

Fyi: we involved a lot of people in the process, but we didn't make it public as we didn't have to. And obviously the questions & answers are confidential and secret. We did involve the active Piwik team members and contributors along with a few selected and trusted Piwik & Digital Analytics experts.

@StefanKoning would be good to remove the "Date of birth" requirement if possible

If you take the exam and have constructive feedback please share with us privately and we'll be pleased to improve the certification :+1:

**Comment by mattab** [comment]
:tada: Closing this 3 year old issue as the official Piwik Certification is live! :tada:  Awesome work everyone

**Comment by MagicFab** [comment]
@mattab thanks for clarifying, glad my intuition was right. I don't mean to minimize your effort and work, specially with the great results I see.

As you know I am not too keen on providing private feedback even when on payroll when it involves free open source software, but I'll take the opportunity if it presents itself, thanks again for your hard work :)

**Comment by warenhaus** [comment]
@mattab and now the program is gone again?

**Comment by MagicFab** [comment]
Gone since May, apparently : https://matomo.org/faq/general/is-there-a-matomo-certification-or-training-program/

**Comment by mattab** [comment]
Yes, we have decided to discontinue the program because it didn't have the traction we hoped for, it wasn't up to date anymore, and some of the questions were not really helpful. We also released the training videos and plan on releasing more resources in the future (still hiring someone to help us: https://matomo.org/digital-analytics-expert-content-writer/ )
