### ISSUE TITLE
PHP Fatal error: Either cli core:archive or web index.php, but not both

### ISSUE THREAD

**Issue by andreli** [piwik/piwik#6189]
I updated from 2.4.1 to 2.6.1. 

Everything seamed to work fine with the exception of 

    php console core:archive --...

After deleting the contents of /tmp, the cron job worked fine, but then the web interface ceased to work. After again deleting /tmp, the web was back, as was the problem with my cron job.

Error:

    PHP Fatal error:  Cannot redeclare class Piwik\Plugins\DevicesDetection\Columns\BrowserName in .../plugins/DevicesDetection/Columns/BrowserName.php on line 45

Did I miss a configuration or did I run in a known bug?

**Comment by mattab** [comment]
@andreli @iquito I'm not sure how we could solve this issue, but since that's a problem I've at least reopened the bug!

**Comment by iquito** [comment]
I am not sure myself why this problem appears, in my case I just have two installations of Piwik in two different directories (no symlinks) - everything is seperate (database user, tables, etc.), so nothing should collide, yet in my Nginx error log these errors appear:

```2015/02/20 00:59:11 [error] 13346#0: *24179903 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class Piwik\Plugins\Actions\Columns\EntryPageTitle in /srv/library/piwik/latest/plugins/Actions/Columns/EntryPageTitle.php on line 0" while reading response header from upstream, client: 91.138.4.109, server: panaxis.ch, request: "GET /piwikdev/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "panaxis.ch", referrer: "https://panaxis.ch/piwik/```

I have two paths, "testing" and "latest", and the error message only occurs when I am trying to access the web interface in "testing", yet the error mentions a class which is already declared in "latest".

**Comment by mattab** [comment]
Thanks for the report, but we cannot reproduce. if you know how to reproduce, please create a new issue with steps to reproduce, we will definitely investigate & fix it. thanks
