### ISSUE TITLE
Dimension columns should always be allowed to be NULL in the DB (and should default to NULL)

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6207]
Dimensions are information attached to tracked entity (visits, actions, conversions, whatever). Since they only add context, they are not vital to the entity themselves and thus they should be allowed to be NULL in the DB.

Main use case: will allow easier testing. Not allowing NULL values (and not defaulting to NULL), means dimensions have to be known and data has to be specified for them when inserting test data. This becomes more of a problem when you consider that the dimensions loaded depend on the plugins loaded. If a new dimension is created or new core plugin w/ dimension created, all plugin unit tests that insert data will break.

@mattab Please tell me your thoughts on this, I would like to make this change soon.

CC @tsteur

**Comment by tsteur** [comment]
fixed in https://github.com/piwik/piwik/pull/10492
