### ISSUE TITLE
Force new visit after midnight

### ISSUE THREAD

**Issue by quba** [piwik/piwik#6217]
Personally I don't think it is something we should add to Piwik by default, but this could be an option for users who would like to compare Piwik and GA.

Here is a short quote from GA FAQ:

>Time-based expiry (including end of day):
>After 30 minutes of inactivity (default Piwik setting)
>At midnight (the topic of this ticket)
>Campaign change: (see https://github.com/piwik/piwik/issues/2624)
>If a user arrives via one campaign, leaves, and then comes back via a different campaign.

**Idea:**
Add a setting to Piwik to be able to force new visit after midnight (using site's timezone that will be cached in tracker's cache).

**Comment by tsteur** [comment]
Do we actually need a setting for this? Would just implement it like this. Settings should be avoided if possible.

**Comment by mattab** [comment]
we don't need setting for this, let's make it default
