### ISSUE TITLE
Record  hash tag for outgoing clicks (eg. mega.co.nz outlinks)

### ISSUE THREAD

**Issue by silvioto** [piwik/piwik#6244]
I'm using the MEGA Privacy cloud service to share my podcasts.
In Piwik external links box and section, the MEGA url's is interrupted at # character. Example:

The real url:
https://mega.co.nz/#!yUE0VJDJ!P68eKxBeUhlnicDJNX7jjRGo0K84pDFqEpWxNwNt7Z0
is showed in only first part (the domain):
https://mega.co.nz/
How to visualize the full link?

As a suggestion of matt in my forum topic here: http://forum.piwik.org/read.php?2,120058 I opened this issue.

Thanks.

**Comment by mattab** [comment]
Even when enabling "Tracking of URL fragments/hash tags" I can reproduce in 2.12.1 that the outlink does not contain the hash tag (while Page URLs correctly track the hash tag)

**Comment by silvioto** [comment]
It is possible to create a function or something to make a custom short url system to convert addresses? Looking for a solution I found http://yourls.org/ and I think it is a good point for a features of piwik.
What do you think?

**Comment by mattab** [comment]
Sure it's a great idea, we could have a URL shortener plugin which could
let user generate a short url, and would also measure the clicks and
show reports on how links were clicked, which referrers, etc.
some of our colleagues worked on a quick prototype and we may finish it
someday :)

 do you mind creating a new issue?

**Comment by silvioto** [comment]
Do you have already the prototype? It's fantastic!
I think that a url shortener could close definitively this issue.

**Comment by silvioto** [comment]
No, excuse me, I'm wrong.
An URL shortener do not solve this specific issue, but I really interested in it because the mega links, although complete, don't have the real name of my link.
So, where and/or I can follow the URL shortener plugin project for Piwik? Is necessary to open new issue here on GitHub? Or you are already at work?

Thank you very much.
