### ISSUE TITLE
Widget - Table content disappears when "Display a table with more metrics" icon is clicked

### ISSUE THREAD

**Issue by pksh** [piwik/piwik#6330]
Really strange issue. On a dashboard view inside a widget when you click on "Display a table with more metrics" icon and then close the popup, only single column is shown hiding rest of the report. And similarly on Visitor Browser widget, clicking the same button, the footer draw icon appears on top of the text. Original report and screenshots: 
http://forum.piwik.org/read.php?2,120432,120452#msg-120452

Steps to replicate: 
1. Go to http://demo.piwik.org 
2. On the Keywords/Referrer Websites Widget, click "Change the visualization or configure the report" icon. 
3. Click on "Display a table with more metrics" which would trigger a popup 
4. Close the popup window 
5. In my case, only one column was visible, everything else disappeared and the "Change the visualization or configure the report" icon did not respond. 

Note: The only way to recover was to reload my browser . 
Tested on: Firefox 32.0.3 and Safari 8.0 on Mac OSX (Yosemite)

**Comment by sgiehl** [comment]
Can't reproduce with Piwik 3.
