### ISSUE TITLE
Custom Variables not tracked on Site Searches requests

### ISSUE THREAD

**Issue by Bogun** [piwik/piwik#6333]
Hi all.
Could you please assist with the issue below.
We have some troubles with displaying visitors statistic in PIWIK.
When we in the filter choose "All Visits" we will see:
Custom Variable Name "Action" -> Custom Variable Value "Search".
![image_1](https://cloud.githubusercontent.com/assets/8955725/4439236/37783d34-47b6-11e4-948e-f86ab8d4bd4e.jpg)
But if we apply filter:
![image_2](https://cloud.githubusercontent.com/assets/8955725/4439227/2d9ef668-47b6-11e4-9945-ee5fdb10dd68.jpg)
Custom Variable Value "Search" is not displaying:
![image_3](https://cloud.githubusercontent.com/assets/8955725/4439285/7f8ff83c-47b6-11e4-9d3a-d1da9adaa133.jpg)

Could you please help me with this issue?
What should i do to fix it?

Thank you in advance.

**Comment by tsteur** [comment]
> Re-opening as it is indeed a bug, that Site Search requests are using Custom Variables slots that may be reserved. In this case we should throw an exception in the browser console or something?

Are we actually using Custom Variables there for this? We should rather fix this hack.

**Comment by mattab** [comment]
> Are we actually using Custom Variables there for this? We should rather fix this hack.

Actually not I was wrong... see https://github.com/piwik/piwik/blob/master/js/piwik.js#L3647-L3656

**Comment by mattab** [comment]
Hi @EduardTrayan this issue is getting too long and I'm lost. Maybe the issue is caused becasue you use two tracking codes? Or can you reproduce the issue with only one tracking code? if so please note the steps to reproduce and we'll take a look

**Comment by AlexanderGirgis** [comment]
Hi @mattab 

I was trying to get a site search with local variables too, when I found this issue. After a brief look at the code I think the problem might be that CustomVariables are missing from the call https://github.com/piwik/piwik/blob/master/js/piwik.js#L5026-L5030 of the funcion you mentioned, however I can't set up a full stack to test it at the moment. However this feature is key to my project, I hope that helps solving the problem.

**Comment by mattab** [comment]
Here is what we need to solve the problem / bug: 
 * a clear list of steps to reproduce the issue (maybe a HTML file or two, with minimal content and the piwik code to reproduce)
 * a description of what you get VS what you expected to get 

If we can reproduce the issue then we will for sure aim to fix it quickly!

**Comment by mattab** [comment]
Please createa new bug report with steps to reproduce, and for sure we will take a look at it - thanks for your understanding
