### ISSUE TITLE
when angularjs 1.3 is available and used in piwik, make sure bindtoController is used for all directives w/ controllers

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6365]
As title. Currently, scope variables are not included in the controller scope when controllerAs is used (so a directive's scope variables are not bound to the object created by controllerAs).

This is fixed in angularjs 1.3 w/ the bindtoController attribute (see https://github.com/jesselpalmer/angular.js/commit/b8be80d578fac7839b0a387906921560ee36e419 ).

**Comment by sgiehl** [comment]
@diosmosis we are using angular 1.6 now. is this issue still relevant and maybe something we should handle soon?

**Comment by diosmosis** [comment]
It’s not important. I’ll close it.
