### ISSUE TITLE
Content-tracking: display content views and interactions in the Visitor log

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6416]
The goal of this issue is to display all Contents views and interactions in the Visitor Log. 

Having the data in the Visitor log will bring a lot of value to users. It is aligned with our policy to make all available data in the DB available in the UI. 
- Requires: Live API to contain Contents views and interactions: #6268 
- See also possible issue of "0 action" visit in #6415

**Comment by berters** [comment]
This would be extremely useful to see the effect of exit intent banners or offers. Being able to link impressions and interaction to the user on the visitor log would definitely be valuable to me and many others I'm sure.

**Comment by beatelite** [comment]
I see this is a couple years old. Is it still something that's going to be done? I'd love to get content impression tracking data in the visitor log and in the live visitor api.

**Comment by hpvd** [comment]
strongly +1!!!

Maybe this can be done similar to events (maybe only using another symbol)

**especially "content interaction" is really important**

This would give the **possibility to understand** which **way** the visitor has taken to go from one site to an other:
- does he use the mega-drop-down menu in head of page?
- does he use the "related article links" located at the end of the article?
- does he use the "next article" link?
- does he use the news box on the right side?
- does he use the links within the text of the article?

in addition to understand which way a user has used, **it may give also an inside about his motivation:**
Just an example:
if he uses "related article links" which shows name and image of an related article, he is much more focused and intersted in the content of the related article
than if he uses "next article" link which brings him to an unpreknown type of artikle...

**Comment by hpvd** [comment]
For **content impression it should be possible to show / hide** these pieces of information to not overflow visitor log with informations.

**Comment by hpvd** [comment]
this would also help a lot during setup and testing of content tracking...

**Comment by hpvd** [comment]
maybe one can make a two step aproach and implement content interaction first
(because of it's importance and the no need to hide because of messing up vistitor log, see decribtions above)

an idea on how this can look:
![2016-04-18_08h00_18](https://cloud.githubusercontent.com/assets/5681880/14595115/e5ebab4a-053c-11e6-8790-74a9b251f161.png)

**Comment by mattab** [comment]
FYI this is what Content Tracking looks like

### in Visitor Log
![visitor log content tracking](https://user-images.githubusercontent.com/466765/30272842-7a266cdc-974a-11e7-8142-ca3330312224.png)


### in Visitor profile

![or in visitor profile](https://user-images.githubusercontent.com/466765/30272837-76be1bf8-974a-11e7-8825-7593f6d6e922.png)

**Comment by hpvd** [comment]
@mattab 
many thanks for showing these examples!
And all the work put into it!

2 things maybe interesting:

1. is there already a docu to show best practise:
- which things should be tracked via event and
- which ones via content elements
(I think some examples would help a lot)

2. Is there already a way to select which information should be shown in visitor log/profile?
It's about space requirements and maybe also performance..

e.g.
within global settings
or
on head of visitor-log an -profile

via checkbox:

- pages (always active?)
- events
- content views
- content interactions
- search?
- outlink?
- ecommerce?

**Comment by hpvd** [comment]
and maybe also a 3. thing: see https://github.com/piwik/piwik/issues/12025
