### ISSUE TITLE
duplicate entries in piwik_log_action leading to pages not visible in segments

### ISSUE THREAD

**Issue by voidswitch** [piwik/piwik#6436]
Hi,

currently we encountered a strange issue with pages listed in *actions->pages*, but not if using a segment (which should include this page). Investigating the issue I found duplicate entries in piwik_log_action.

idaction | name | hash | type | url_prefix
---------- | -------- | --------- | -------- | --------
4114714 | example.com/somepage | 652463546 | 1 | 1
4114715 | example.com/somepage | 652463546 | 1 | 1

In piwik_log_link_visit_action only *idaction 4114715* is referenced, and displayed with views in *actions->pages*; creating a segment matching *example.com/somepage* gets 0 views for this page.

Something to consider is that, we use 2 balanced Piwik installations for tracking, a setup which should be working fine, but also has the potential to create this kind of issue as *type, hash* is not unique.

**Comment by fpoepleu** [comment]
It would be really great if this were solved. We have the same problem and our databases date back to 2011.
Are there any news?

**Comment by voidswitch** [comment]
Just want to say thanks for the great work!

**Comment by mattab** [comment]
Thanks @voidswitch I also want to say great work to @diosmosis and the team!
