### ISSUE TITLE
Fatal Error: '' from import_logs.py

### ISSUE THREAD

**Issue by orlitzky** [piwik/piwik#6451]
This started about a week ago, I don't think anything changed here. Every night we run,

```bash
import_logs.py --enable-http-errors --enable-http-redirects --enable-bots --enable-static --recorders=6 --url=https://analytics.example.com/ <all logs from yesterday>
```
Now it regularly gets stuck:

> Parsing log /var/log/apache2/example.com/www/access/access-2014-10-14.log...
> 6886 lines parsed, 6284 lines recorded, 79 records/sec (avg), 148 records/sec (current)
> 6886 lines parsed, 6461 lines recorded, 80 records/sec (avg), 177 records/sec (current)
> 6886 lines parsed, 6676 lines recorded, 82 records/sec (avg), 215 records/sec (current)
> ...
> 6886 lines parsed, 6676 lines recorded, 25 records/sec (avg), 0 records/sec (current)

and eventually fails with the following:

> 6886 lines parsed, 6676 lines recorded, 25 records/sec (avg), 0 records/sec (current)
> Fatal error: ''
> You can restart the import of "/var/log/apache2/example.com/www/access/access-2014-10-14.log" from the point it failed by specifying --skip=5 on the command line.

Is that the sixth line of the log file? If so, there's nothing weird in it.

The problem began on 2.7.0, but persists after an upgrade to 2.8.0.

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
