### ISSUE TITLE
Add visual hints for active form elements

### ISSUE THREAD

**Issue by rivadav** [piwik/piwik#6464]
**The problem**
There's no visual clue what form element is currently selected which may impact accessibility (https://github.com/piwik/piwik/issues/4167). 
As mentioned on Piwik forum: http://forum.piwik.org/read.php?3,118149 
"I noticed on the Login-form, that when moving from field to field with the tab key, 
there's no visual indicator when the focus is on the checkbox or the submit button. 
On textfields the blinking cursor is the only indicator."

![zrzut ekranu 2014-10-18 14 13 20](https://cloud.githubusercontent.com/assets/1769990/4689670/885def64-56c5-11e4-9084-8d046510bdd5.png)
![zrzut ekranu 2014-10-18 14 11 11](https://cloud.githubusercontent.com/assets/1769990/4689669/8859f710-56c5-11e4-98ad-8f6eb1e03f57.png)

**Proposed solution**
The default light-blue border over input is usually sufficient clue that input is selected.
![zrzut ekranu 2014-10-18 15 06 10](https://cloud.githubusercontent.com/assets/1769990/4689811/d8b97436-56cc-11e4-9790-61d15a430d90.png)

**Comment by tsteur** [comment]
This was recently fixed during the Catalyst Academy. A dark / grayish color was used. I think the related PR is #7035
