### ISSUE TITLE
Add a search field in Visitor settings Browsers 

### ISSUE THREAD

**Issue by blau** [piwik/piwik#6490]
In Visitors > Settings > Browsers  web interface

There is no way to pinpoint a specific browser version (say, IE6) other than browsing alle the pages. A search field would be very handy.

**Comment by mattab** [comment]
let's add a search field in  
 * Operating systems
 * Browsers
 *  Device model 
 *  Device brand 
as all those can have 100+ rows and search field is a must then :+1:
