### ISSUE TITLE
icecast2 <session_time> ignored in piwik session time reports

### ISSUE THREAD

**Issue by streamradio** [piwik/piwik#6501]
It would be very nice if the <session_time> field from the icecast2 log import, is taken into account to calculate the session times. Otherwise i need to insert manually a start GET request <session_time> seconds before the actual log entry, which can couse problems in some cases, and its also somehow annoying. Or is there a setting to activate this behaviour per website, or is it solvable via plugin?

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
