### ISSUE TITLE
Automatically refresh every week the last CI build for each of our repository 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6542]
The goal of this issue is to write a script that will periodically (every week) refresh the build status of all our repositories.

Advantages:

 * Detect early when change in piwik/piwik will break something in a plugin
 * Regularly keep up to date with plugin CI builds to avoid getting overwhelmed with too many failing builds
 * Increase shared knowledge of plugins across the team
 * Increase quality of our work
 * Make each developer regularly responsible for keeping CI green

Notes:

 * Before we start working on this issue we should have all plugin builds green at least once.
 * Should be hosted on *.piwik.org 
 * do we refresh all builds of all plugins on the same day (eg. Sunday)?

**Comment by diosmosis** [comment]
Fixed by https://github.com/piwik/ci-trigger.
