### ISSUE TITLE
experiment w/ switching from phantomjs for UI tests to node-webkit

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6550]
node-webkit is similar to phantomjs in that it uses webkit to render pages and provides ability for JS to script webpages. Using it to run UI tests (if possible) may result in faster test execution. It will also provide the full node.js API, which may be useful in the future.

**Comment by mattab** [comment]
We've migrated to Phantomjs2 for now

**Comment by mattab** [comment]
PhantomJS works well now. Can maybe reopen later if it becomes an issue again
