### ISSUE TITLE
noindex, nofollow option

### ISSUE THREAD

**Issue by ways2web** [piwik/piwik#6552]
<meta name="robots" content="noindex, nofollow">

or an possibility to add own meta tags

**Comment by ryrun** [comment]
Hi, this issue should be re-evaluated. See my post here: #8036 Its about preveting for googling for piwik installations.

**Comment by mattab** [comment]
Increasing priority.

Proposed steps:
 * show `<meta name="robots" content="noindex">` on Installation pages, Updater pages, Reporting UI pages, Admin pages, and others if any
 * show `<meta name="robots" content="index">` on the Login form.

**Comment by hpvd** [comment]
just wanted comment on mattabs comment above:
"it's good to index the login pages of Piwik (for example they link to piwik.org)"

of course from seo point of view backlinks I could understand that.

From security point of view easy to find login page is not that great.
On could e.g. easily do the following thing - FULLY AUTOMATED:
1) search for login page
2) start brute force attack
3) when you are successful: look for ecommerce
4) extract /download everything
5) make a database of ecommerce data
6) sell it to everyone (competitors)

on other systems their is a great effort to hide login page with the following:
- of course for every visitor: noindex, no follow, no archive
- have a possibility to easily change login url within the backend

**so I would strongly vote for noindex, no follow, no archive also for login page**

**Comment by AramVK** [comment]
I wonder why it still has index,follow on the login page. Every update I have to change it. If I don't, the page will end up high in the search result for our company name. This is obviously not something anyone wants. The meta tag is for controlling search engines; why would a search engine needs to display a login page for admins?

**Comment by wishsimply** [comment]
This was also my solution until I recently got a warning from google search console
'Indexed, though blocked by robots.txt' 

Related 'learn more' link will lead to  
https://support.google.com/webmasters/answer/7440203#indexed_though_blocked_by_robots_txt,
which says that 

> 'robots.txt is not the correct mechanism to avoid being indexed.'

After that I looked bit more and found 
https://forum.matomo.org/t/exclude-piwik-from-being-indexed-by-search-engines/363/8 ,which will instruct modifying file '<piwik install dir>/plugins/Login/templates/login.twig' 

from

`<meta name="robots" content="index,follow">`

to
`<meta name="robots" content="noindex,nofollow">`

Hopefully it works, but naturally it goes broken again after next update..

**Comment by AramVK** [comment]
Yes you need to be careful with robots, if you don't place it at the right path, it will block your whole website.

After yesterdays update I had to update the login.twig file once again, it's still part of the routine :relieved:

**Comment by wishsimply** [comment]
yes, although (just for sure) that was not my case. I was only blocking /piwik directory, but google had found it anyway. 

I commented also the other related [issue](https://github.com/matomo-org/matomo/pull/8058#issuecomment-440737416) and asked if this could be included to the project. 

I guess that one checkbox in the settings would not be too much asked.
