### ISSUE TITLE
PageURL Segmentation fails on the ecommerce page

### ISSUE THREAD

**Issue by dev-jan** [piwik/piwik#6593]
**Problem:** If there is a segment selected (in our case "Page URL contains /ch/"), here will be no results on the Ecommerce Page (but there should be some results there). 
That problem exists in version 2.4.1, but also in the newest version (2.8.3). 
Maybe important: We use a cronjob to archive our reports.

Thanks for solving this problem.

**Comment by mattab** [comment]
adding `Major` tag as we need to take a look at this one to see if we can fix it quickly or how complex it would be
