### ISSUE TITLE
Move phpunit.xml.dist to phpunit.xml in PHPUnit bootstrap or when executing tests

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6635]
Either on each test run or only if it doesn't exist yet. To make this useful we should replace `REMOTE_ADDR`, `HTTP_HOST` and `REQUEST_URI` automatically. I think we have at least the URI in `SettingsPiwik`? Not sure about the rest. If not, maybe we could read them from config? 

Currently, a developer has to prepare the DB test config and adjust the phpunit.xml. Having everything only in one place makes it easier to configure and to explain in documentations / blog posts. 

By copying the XML all the time it also prevents the issue that sometimes the `.dist` files changes and people are not aware that they have to update their local file. I'm not sure if an updated XML file would take effect immediately or with the next test run but either way it would be still better. 

Not sure what the best way is to resolve it but would be nice to have it. Maybe we can even get rid of the `.dist` file at all and define those 3 variables in bootstrap.php?

**Comment by mattab** [comment]
What's the next step here @tsteur ? maybe it would be better in `Short term` if it is low effort and useful?

**Comment by tsteur** [comment]
It is minimal effort and Piwik 2.12.0 would be fine
