### ISSUE TITLE
Computation load after adding new segments on long existing Piwik instance

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#6638]
Current archiving flow can bring certaing ammount of problems when archiving segments on instances which are 2-3-4 years old. During normal flow of cron archiving, there will always be only last 2 years processed. Adding new segment(s) can bring up two following problems for archive process:
- if at any time archiving will fall back to computing last3, last4 (anything bigger than last2) for year period - it can cause processing of days and months for that 3rd year. This will cause huge increase of archiving time. In addition, the more segments exist on instance, the more additional computing will have to be done to complete last3 archiving.
- On big traffic instances adding new segments can also be troublesome, because Piwik would try to process last 2 days, weeks, months and years. Given a batch of 50 segments, such 'catching up' will take significantly bigger ammount of time. Workaround for this is to add only couple segments at one time, but this can be troublesome when having many Piwik admins.

The goal of this ticket is to decide best approarch to this issue and hopefully plan implementation for improvement

**Comment by mattab** [comment]
First step to solve this issue will be #7223 

If that issue does not solve the problem all together, let's discuss again what solution we could put in place :+1:
