### ISSUE TITLE
Handling migrations in Piwik

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#6640]
Currently migrations are carried out by running core:update command.
However it maybe should also be possible to split updates into two flows. One should be db migration and other would be to perform some additional logic.

Possible use case:
- Piwik admin wants to update his instance with separate DB server,
- does --dry-run (or simply run core:update as in next versions --dry-run will be deprecated) to see what queries need to be executed
- executes queries manually on database
- wants to perform other logic done 'under the hood' (i.e. plugins name change, plugin activation etc) - but currently this is impossible, as Piwik update will notice core_version in piwik_option table set to latest possible, and will omit all the logic that hasn't been executed.

It could come quite in handy when some users have setup, on which running core:update will not be a good idea.

Goal of this ticket is to start discussion about possible improvements and separating DB migrations from additional logic done between some versions.

**Comment by mattab** [comment]
> wants to perform other logic done 'under the hood' (i.e. plugins name change, plugin activation etc) - but currently this is impossible, as Piwik update will notice core_version in piwik_option table set to latest possible, and will omit all the logic that hasn't been executed.

This was fixed in  #6760 by hiding the `core_version` SQL from the list of queries.
So now even when copy pasting the list of queries it will still show the update screen to run any non-sql upgrades.

**Comment by mattab** [comment]
What would be the most useful next step for improving the `core:update` experience, if something needs to be done soon? otherwise I leave the issue opened for further suggestion and feedback!

**Comment by mattab** [comment]
https://github.com/piwik/piwik/issues/5985
