### ISSUE TITLE
Visitor profiles no longer work piwik 2.9.1

### ISSUE THREAD

**Issue by srathbone** [piwik/piwik#6702]
The request returns a 500 HTTP code and the following:-

````
There is an error. Please report the message (Piwik 2.9.1) and full backtrace in the Piwik forums (please do a Search first as it might have been reported already!).

Recoverable Error: Argument 1 passed to twig_split_filter() must be an instance of Twig_Environment, string given, called in /path/httpdocs/tmp/templates_c/87/57/aab6919e479e879d8c6a6cd5429a2616aaf38aa672aaaaaaaaaaaaaaaaaa.php on line 116 and defined in /path/httpdocs/vendor/twig/twig/lib/Twig/Extension/Core.php on line 810

Backtrace -->

#0 Piwik\Error::errorHandler(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Extension/Core.php:810]
#1 twig_split_filter(...) called at [/path/httpdocs/tmp/templates_c/87/57/aab6919e479e879d8c6a6cd5429a2616aaf38aa672aaaaaaaaaaaaaaaaaa.php:116]
#2 __TwigTemplate_8757aab6919e479e879d8c6a6cd5429a2616aaf38aa672aaaaaaaaaaaaaaaaaa->doDisplay(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:279]
#3 Twig_Template->displayWithErrorHandling(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:253]
#4 Twig_Template->display(...) called at [/path/httpdocs/tmp/templates_c/d7/64/9e87997a85bc2bb4e3e7c0449bcf5806e890d03e802fbbbbbbbbbbbbbbbb.php:104]
#5 __TwigTemplate_d7649e87997a85bc2bb4e3e7c0449bcf5806e890d03e802fbbbbbbbbbbbbbbbb->doDisplay(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:279]
#6 Twig_Template->displayWithErrorHandling(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:253]
#7 Twig_Template->display(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:264]
#8 Twig_Template->render(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Environment.php:292]
#9 Twig_Environment->render(...) called at [/path/httpdocs/core/View.php:259]
#10 Piwik\View->renderTwigTemplate(...) called at [/path/httpdocs/core/View.php:253]
#11 Piwik\View->render(...) called at [/path/httpdocs/plugins/Live/Controller.php:125]
#12 Piwik\Plugins\Live\Controller->getVisitorProfilePopup(...) called at [:]
#13 call_user_func_array(...) called at [/path/httpdocs/core/FrontController.php:582]
#14 Piwik\FrontController->doDispatch(...) called at [/path/httpdocs/core/FrontController.php:96]
#15 Piwik\FrontController->dispatch(...) called at [/path/httpdocs/core/dispatch.php:36]
#16 require_once(...) called at [/path/httpdocs/index.php:46]


There is an error. Please report the message (Piwik 2.9.1) and full backtrace in the Piwik forums (please do a Search first as it might have been reported already!).

Warning: Missing argument 3 for twig_split_filter(), called in /path/httpdocs/tmp/templates_c/87/57/aab6919e479e879d8c6a6cd5429a2616aaf38aa672aaaaaaaaaaaaaaaaaa.php on line 116 and defined in /path/httpdocs/vendor/twig/twig/lib/Twig/Extension/Core.php on line 810

Backtrace -->

#0 Piwik\Error::errorHandler(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Extension/Core.php:810]
#1 twig_split_filter(...) called at [/path/httpdocs/tmp/templates_c/87/57/aab6919e479e879d8c6a6cd5429a2616aaf38aa672aaaaaaaaaaaaaaaaaa.php:116]
#2 __TwigTemplate_8757aab6919e479e879d8c6a6cd5429f3826aff38aa672adef26b5a91d15b684->doDisplay(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:279]
#3 Twig_Template->displayWithErrorHandling(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:253]
#4 Twig_Template->display(...) called at [/path/httpdocs/tmp/templates_c/d7/64/9e87997a85bc2bb4e3e7c0449bcf5806e890d03e802fbbbbbbbbbbbbbbbb.php:104]
#5 __TwigTemplate_d7649e87997a85bc2bb4e3e7c0449bcf5806e890d03e802fbbbbbbbbbbbbbbbb->doDisplay(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:279]
#6 Twig_Template->displayWithErrorHandling(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:253]
#7 Twig_Template->display(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Template.php:264]
#8 Twig_Template->render(...) called at [/path/httpdocs/vendor/twig/twig/lib/Twig/Environment.php:292]
#9 Twig_Environment->render(...) called at [/path/httpdocs/core/View.php:259]
#10 Piwik\View->renderTwigTemplate(...) called at [/path/httpdocs/core/View.php:253]
#11 Piwik\View->render(...) called at [/path/httpdocs/plugins/Live/Controller.php:125]
#12 Piwik\Plugins\Live\Controller->getVisitorProfilePopup(...) called at [:]
#13 call_user_func_array(...) called at [/path/httpdocs/core/FrontController.php:582]
#14 Piwik\FrontController->doDispatch(...) called at [/path/httpdocs/core/FrontController.php:96]
#15 Piwik\FrontController->dispatch(...) called at [/path/httpdocs/core/dispatch.php:36]
#16 require_once(...) called at [/path/httpdocs/index.php:46]


A fatal error occurred

The following error just broke Piwik (v2.9.1):

Call to a member function getCharset() on a non-object
in
/path/httpdocs/vendor/twig/twig/lib/Twig/Extension/Core.php line 816
````

**Comment by Zmetta** [comment]
I'm having this same issue on my Piwik Test environment though it didn't seem to start happening until a significant jump in traffic occured (5K hits/day --> 20K/day) . I'll post the error, relevant code, and start poking around at it more. Any help is greatly appreciated. 

>There is an error. Please report the message (Piwik 2.9.1) and full backtrace in the Piwik forums (please do a Search first as it might have been reported already!).

>Recoverable Error: Argument 1 passed to twig_split_filter() must be an instance of Twig_Environment, string given, called in /u01/var/www-vhosts/its-suwi-tst/public/tmp/templates_c/88/99/710eb3ba0e1611ba9190e81c680e7410bd7c39576bc3ece61dfb97a3dfd2.php on line 116 and defined in /u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Extension/Core.php on line 810

>Backtrace -->

>#0 Piwik\Error::errorHandler(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Extension/Core.php:810]
#1 twig_split_filter(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/tmp/templates_c/88/99/710eb3ba0e1611ba9190e81c680e7410bd7c39576bc3ece61dfb97a3dfd2.php:116]
#2 __TwigTemplate_8899710eb3ba0e1611ba9190e81c680e7410bd7c39576bc3ece61dfb97a3dfd2->doDisplay(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Template.php:279]
#3 Twig_Template->displayWithErrorHandling(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Template.php:253]
#4 Twig_Template->display(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/tmp/templates_c/38/a7/c49b714c1432e0b64526f2080fd1caf1345c1fe7eea8f6f4d08d968db446.php:104]
#5 __TwigTemplate_38a7c49b714c1432e0b64526f2080fd1caf1345c1fe7eea8f6f4d08d968db446->doDisplay(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Template.php:279]
#6 Twig_Template->displayWithErrorHandling(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Template.php:253]
#7 Twig_Template->display(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Template.php:264]
#8 Twig_Template->render(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Environment.php:292]
#9 Twig_Environment->render(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/core/View.php:259]
#10 Piwik\View->renderTwigTemplate(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/core/View.php:253]
#11 Piwik\View->render(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/plugins/Live/Controller.php:125]
#12 Piwik\Plugins\Live\Controller->getVisitorProfilePopup(...) called at [:]
#13 call_user_func_array(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/core/FrontController.php:582]
#14 Piwik\FrontController->doDispatch(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/core/FrontController.php:96]
#15 Piwik\FrontController->dispatch(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/core/dispatch.php:36]
#16 require_once(...) called at [/u01/var/www-vhosts/its-suwi-tst/public/index.php:46]


>
>A fatal error occurred
The following error just broke Piwik (v2.9.1):
Call to a member function getCharset() on a non-object
in
>/u01/var/www-vhosts/its-suwi-tst/public/vendor/twig/twig/lib/Twig/Extension/Core.php line 816


From /u01/var/www-vhosts/its-suwi-tst/public/tmp/templates_c/88/99/710eb3ba0e1611ba9190e81c680e7410bd7c39576bc3ece61dfb97a3dfd2.php: lines 98-120

>        // line 27
        if ($this->getAttribute($this->getContext($context, "visitData", true), "browserName", array(), "any", true, true)) {
            // line 28
            echo "            <div class=\"visitor-profile-browser\" title=\"";
            if ($this->getAttribute($this->getContext($context, "visitData", true), "plugins", array(), "any", true, true)) {
                echo twig_escape_filter($this->env, call_user_func_array($this->env->getFilter('translate')->getCallable(), array("UserSe$
            } else {
                echo twig_escape_filter($this->env, call_user_func_array($this->env->getFilter('translate')->getCallable(), array("UserSe$
            }
            echo "\">
                ";
            // line 29
            if ($this->getAttribute($this->getContext($context, "visitData", true), "browserIcon", array(), "any", true, true)) {
                echo "<img src=\"";
                echo twig_escape_filter($this->env, $this->getAttribute($this->getContext($context, "visitData"), "browserIcon", array())$
                echo "\"/>";
            }
            echo "<span>";
            echo twig_escape_filter($this->env, $this->getAttribute(twig_split_filter($this->getAttribute($this->getContext($context, "vi$
            echo "</span>
            </div>
            ";
        }
>

**Comment by Zmetta** [comment]
Removing the files in piwik/tmp/* seems to have resolved this.

**Comment by srathbone** [comment]
Hi @mattab ,

Sorry about the delay, unfortunately I no longer have access to the specific instance I encountered this bug on.

I will let you know if I can reproduce with another instance of the app.
