### ISSUE TITLE
Escape/sanitize strings on output rather than on input

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#6714]
Following a discussion about security:

One of the current best practices in Piwik is **escape everything on input**. But in general, best practices recommend:

- filter on input (e.g. cast to an integer if you expect an integer, but don't sanitize strings)
- escape on **output**

e.g. http://blog.ircmaxell.com/2011/03/what-is-security-web-application.html

Problems with the current approach:

- escaping on input is done for HTML/XML: that escaping doesn't makes sense for SQL, JavaScript/JSON, … And it needs to be undone for those cases
- double escaping issues if we escape on output (e.g. Twig and Angular do that by default)
    - #7987, #7969, #7806, #7531, #7528, #6821, #6722, #6325, #6068, #5189, #5009, #4749, #4709, #4231, #3954, #3549, #3503, #2519, #2400, #2386, #974, #341
- strings are stored in database escaped (not as their "real" values)

**Comment by mattab** [comment]
Duplicated in #4231

**Comment by mnapoli** [comment]
Oh yes thanks I forgot to close!
