### ISSUE TITLE
tracking page URLs like example.com/#!/file should keep url fragment

### ISSUE THREAD

**Issue by tracer99** [piwik/piwik#6718]
Hi, just got Piwik up and running on one of the larger sights at work. 
We're using CanJS for this which uses #! urls. 
We have "Keep Page URL fragments when tracking Page URLs" on. 
If we look at the Visitor Log section, we see all the #! locations being properly tracked. 
ie.
https://manage.opensrs.com/#!/domain
However, in Actions -> Pages everything is simply going to index#! or /index#! and the rest of the url after #! isn't showing there. 
Posted this to the community forums but was told to file a bug report instead.

**Comment by tracer99** [comment]
After discussing this issue with Maciej Zawadziński, it appears I simply got confused with how the interface worked as the output between the two sites we're tracking is so different. This is not a bug.

**Comment by tracer99** [comment]
Sorry, I have no information about the issue that @Jgavin101 is having.

**Comment by mattab** [comment]
Hi @Jgavin101   please open a new issue for your bug and we'll take a look. (this issue was closed.)
