### ISSUE TITLE
Let plugins allow to extend the system check

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6726]
Useful for many things:

1. We could run the system check for plugins before activating it. Eg plugins might want to check whether a certain PHP extension is installed etc. Some plugins might require a certain webserver or other things. While some conditions could be maybe done with `require:` in `plugin.json` many cannot.

2. To show errors, warnings, notices, ... in the system check page under Settings => Diagnose => System Check.

3. I had more advantages in mind but forgot them :) Basically for monitoring etc.

Use case: In Redis Queue plugin we could check for having an extension installed or not, whether a Redis server is actually present and / or whether the connection to the Redis server can be established etc.

**Comment by mnapoli** [comment]
For the record #7646 has been merged, it covers the 2nd point.

**Comment by mattab** [comment]
"Let plugins  extend the system check" was done, see existing diagnostics classes: https://github.com/piwik/piwik/search?utf8=%E2%9C%93&q=implements+Diagnostic :+1:
