### ISSUE TITLE
plugin to update is shown several times

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#6737]
If there are more than one new version of an plugin since your last plugin update, the plugin is shown several times..
piwik 2.9.1 latest beta

see attachment
![2014-11-27_18h35_30](https://cloud.githubusercontent.com/assets/5681880/5220397/89922094-7664-11e4-81fc-780bf1275e36.png)

**Comment by mattab** [comment]
see also #6701

**Comment by hpvd** [comment]
it's still there in 2.15RC1:
https://github.com/piwik/piwik/issues/8999

**Comment by mattab** [comment]
Experienced today in the UI tests as well: http://builds-artifacts.piwik.org/piwik/piwik/master/16400/UIIntegrationTest_admin_plugins

screnshot http://builds-artifacts.piwik.org/piwik/piwik/master/16400/processed/UIIntegrationTest_admin_plugins.png (will be deleted in 30 days)

**Comment by hpvd** [comment]
seems not to happen for all plugins - please see attachment
![2015-10-23_12h16_28](https://cloud.githubusercontent.com/assets/5681880/10690187/5898d738-7980-11e5-82c5-44cfd4644d3e.png)

**Comment by hpvd** [comment]
STRANGE:
after clicking Action Update for TasksTimetable (first one /in third row)
Log viewer is shown twice now (was one time shown before, see post above)
![2015-10-23_12h24_33](https://cloud.githubusercontent.com/assets/5681880/10690352/676bc6ac-7981-11e5-91db-3bd6463ab892.png)

**Comment by hpvd** [comment]
after clicking Action Update for Logviewer 
CustomOptOut is shown twice now
![2015-10-23_12h30_10](https://cloud.githubusercontent.com/assets/5681880/10690418/ffb8e444-7981-11e5-8504-3185b11ca19c.png)

**Comment by hpvd** [comment]
once again in Piwik 2.15 final
![2015-10-30_15h05_17](https://cloud.githubusercontent.com/assets/5681880/10847638/e3a83214-7f17-11e5-8ce5-3d0c8dc5c7d6.png)
