### ISSUE TITLE
Possible CronArchive (& core archiving) algorithm improvements

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6754]
There are some parts of the CronArchive algorithm that seem inefficient. We could probably optimize and simplify the algorithm with the following changes:

- Instead of running archiving for lastN days/weeks/months/etc., the date range to initiate archiving should be determined (either by last archiving time or by command line option) and the optimal archiving requests should be made. It makes no sense to archive for last 50 days and then archive for the last 2 years.
   * Based on the date range, day archiving for every day in the range should be scheduled individually, then week, then month, then year. This way, period archiving will not actually initiate archiving for sub-periods and every individual archiving request can be parallelized.
- Implement bottom up aggregation for period archiving (ie, mimic incremental map reduce). Right now, when cron archive is run again, the year, month, week and day periods for today are re-archived completely. That is to say, when archiving for a year, the data for every month is accessed and aggregated in PHP. This is slow. Instead, we can take the new data for the current day and add it to existing week + month + year periods. May run into issues w/ report limiting features.

**Comment by noogen** [comment]
On a similar topic, I'm using 2.10.0 and the website UI is slow 1+ minutes for 6 millions record archive table.  I trace it down to the daily archive blob being update/invalidate to "done" every time the UI try to read from archive.  Would anyone see an issue in moving one line of code in https://github.com/piwik/piwik/blob/master/core/Archive.php?

Commented out line 561: $this->invalidatedReportsIfNeeded();
Add to line 864: $this->invalidatedReportsIfNeeded();

Only invalidate archive during archive prep?  Or is there a better location to move this to?  So far, website response great and archive still call the invalidate method.

**Comment by mattab** [comment]
Hi @noogen can you please create a new bug report for your problem? it's a bug and we would like to fix it, but this issue is about something else. Thanks!
