### ISSUE TITLE
Large Mysql Database and running Piwik at scale: challenges

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6759]
The goal of this issue is to keep track of all the ongoing challenges that come with running Piwik on large traffic websites. These issues may affect Piwik servers with more than 50M actions/pageviews per month.

 * **Adding indexes, columns, changing column types on large tables takes hours or days:**
  * eg. Adding the [Transitions INDEX](http://piwik.org/faq/how-to/faq_161/) for faster Transitions report is slow  #9276 
  * eg. Migrating from `INT` to `BIGINT` for Primary keys to avoid issues when `log_link_visit_action` table hits 4 billion records (`4,294,967,295`)  #3288
  * eg. when new columns are added in some core plugins
    * Maybe there are Mysql based solutions (percona ? other engines?) that make adding INDEXes faster on multi-Gb databases?
    * How to handle mysql log_* tables when they grow to hundreds of Gigabytes #6848 
 * **Some features don't work or time out:**
  * ~~Custom date range reports are slow: how to make them faster? #4768~~ and #3611
  * ~~Custom date ranges loaded by default are not pre-processed and timeout #6672~~
  * ~~Sub-table implementation becomes slow when thousands of leaves in the tree #6763~~ and #7375   
  * ~~Make it flat  times out when large amount of data #5098~~
  * ~~High computation load after adding new segments to pre-process #6638~~ and #7483 
  * ~~`Live.getCounters` times out on very large instance  #6758~~
 * **Using Piwik with thousands of websites or users can break some functionality:**
  * ~~Show paging in the screen 'Manage websites'  #3838~~
  *  ~~Make archiving faster when thousands of websites with low or no traffic  #5922~~
  * Show paging in the screen 'Manage users' to easily manage hundreds of users #4474 
  * ~~All websites dashboard rendering can timeout or make browser unresponsive #6809~~

See also ideas to research #1999 and continuous performance integration #2000

**Comment by mattab** [comment]
very interesting blog post [Avoiding MySQL ALTER table downtime](http://www.percona.com/blog/2014/11/18/avoiding-mysql-alter-table-downtime/)

**Comment by mattab** [comment]
A lot of progress has been made (i've edited the issue to cross out issues that are now done). We are continuing to work on performance and will do this one next: scale the Website Manager when there are thousands of websites (#3838)

**Comment by dmitrisgit** [comment]
Hey Matt, et all, not sure if this is the right place to post this, but I was wondering if there are any procedures for removing features or blocks of features from Piwik setup/DB?

I am running analytics engine that takes use of Piwik's Event Tracking engine. We are operating on websites with 3M+ uniques and are looking to grow. Since we aren't using all of the features of PW, perhaps there's a way to "lighten" the whole thing? Like a race car :)

**Comment by mattab** [comment]
hi @dmitrisgit, the official way is to disable some plugins from Piwik > Administration > Plugins, this will speed up the Tracker, Archiving, and possibly the UI as well.

**Comment by mattab** [comment]
Will now close this issue as we did a lot of work over the last two years and have solved most obvious issues. Piwik 3 will go even further with BIGINT fields to let users track by default more than 4 billion actions & visits. 

We'll discuss further performance issues/ suggestions in separate issues. Check the tag `c: Performance`: https://github.com/piwik/piwik/labels/c%3A%20Performance
