### ISSUE TITLE
Events reports: option to view all columns: min, max and avg values

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6761]
The goal of this issue is to improve the [Events reports](http://piwik.org/docs/event-tracking/) to add a new option in the Cog icon, to `Show value metrics`. When clicked, the following columns will be displayed on top of existing ones:
 * Average value
 * Min value
 * Max value
 * Event with a value (on hover, show % relative value)

**Comment by tsteur** [comment]
This would be real useful for us see https://github.com/piwik/piwik/issues/9115 . Without this the events are meaningless for us and I presume for many other users as well. It should be maybe even show all columns by default or by smart and detect when there is an avg value of 1 (and min value = 1 and max value = 1) and not show the other metrics in this case.

**Comment by mattab** [comment]
indeed, now that we use it we realise how much crucial this feature is...

**Comment by mattab** [comment]
indeed, now that we use it we realise how much crucial this feature is... Moved into 2.15.1

**Comment by hpvd** [comment]
> now that we use it we realise how much crucial this feature is... Moved into 2.15.1
=> wow that GREAT to here - we hoped you would notice this :-)
maybe one could also add "Visitor log: Show time and nr of action for each site directly"  #8731
to same milestone?

**Comment by tsteur** [comment]
For consistency, I wonder if it wasn't more appropriate to use visualization `tableAllColumns` for this instead of the cog icon? This would probably also avoid adding several new features to core just for this.

**Comment by tsteur** [comment]
I'm adding this feature via `tableAllColumns` here: https://github.com/piwik/piwik/compare/6761?expand=1

It looks like this:

![image](https://cloud.githubusercontent.com/assets/273120/11801170/44622502-a348-11e5-95ed-29c374d7d545.png)

Current problem: It seems to not remember the visualization when clicking on any of the ReportByDimension left menu links. Need to look into it.

Also I noticed there are two more columns available and I'm not sure if we should show them: "Visits" and sometimes "Unique Visitors" depending of period and Piwik setting. Does it make sense to show these columns there?

**Comment by mattab** [comment]
Feedback
 * Nice idea  to re-use the table all columns icon for this
 * the "Footer expanded/collapsed" state is not restored/persisted, it would be nice if it was (not in the scope of this issue so optional)

> Also I noticed there are two more columns available and I'm not sure if we should show them: "Visits" and sometimes "Unique Visitors" depending of period and Piwik setting. Does it make sense to show these columns there? 

It does make sense to show them :+1: 

>  Also should we show nb_events_with_value?

:+1:

**Comment by tsteur** [comment]
Re state restore see https://github.com/piwik/piwik/pull/9398
