### ISSUE TITLE
Let user pick her most important Custom Variables name(s), and create separate report listing top custom variable values

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6762]
The goal of this issue is to make the [Custom Variables](http://piwik.org/docs/custom-variables/) reporting more useful by letting user select (eg. `star`) the Custom Variables names that are most important to her. User will be able to see the list of Values for each `starred` custom variable. 

Proposed steps:
- Let user pick custom variable of interest, eg. maybe a new `star` like icon in the Custom variables table rows. Persist the list per-user?)
- Those custom variables that were clicked will then have their own sub-menu on the Custom Variable page (eg. a left menu selector). By clicking on the menu it will load the values for this custom variable. 
- The starred Custom Variable names can be displayed in the Graph metric picker to let user graph the overall number of visits/pages for those custom variables.
- Show the "Segmented visitor log" icon for each row "Custom variable value" https://github.com/piwik/piwik/issues/8837
- Maybe we check that Insights report work well for a Custom Variable.
- When custom variable values are numbers, we could display interesting reports:
  - Average values
  - Minimum / maximum values
  - Total number of unique values
  - possibly show a histogram bar graph of the values

Please comment with your ideas or suggestions

**Comment by imyawar** [comment]
+1

**Comment by mattab** [comment]
We won't do this because now we recommend to use Custom Dimensions, which actually implements most of these suggestions! :tada:
