### ISSUE TITLE
Provide extended core:archive logger output messages for easier monitoring

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6764]
As a Piwik developer
I'd like to have better archiving output
to make debugging easier.

**What could be added:**

*    ~~log each segment archiving with time (rather than log them all at once), #7536~~
*    ~~ability to print API calls used to archive~~ -> use `--v` to see `climulti:request` calls
*    ~~during archiving - which plug-in is currently being archived,~~ -> the plugin being archived will be logged if level is DEBUG
*    ~~ability to easily print all queries executed during archiving,~~ -> done in logger in verbose mode
*   ~~Provide better information regarding memory usage by each plugin #6708~~
*    ~~while requesting from API with debug parameter - information about selected archives (idarchive, archive type, missing archives) - such debug was available in Piwik 1.*~~

**Comment by mgazdzik** [comment]
:+1:  for this, it would be great to have insight into which segment is currently processed (for ex. processing segment ABCD 1 of 10).
In long running archivings it's hard to determine where archiving is, which segment is heavier than other (it may give us some data to analyse segments complexity impact on processing time) and if archiving is making any progress with segments.

**Comment by quba** [comment]
+1

**Comment by mattab** [comment]
good idea, see proposal in:  Log which segments are currently being archived #7536

**Comment by mattab** [comment]
#7536 is last remaining sub-task. If we have any new idea to improve `core:archive` logger (eg. display new stats or useful info), let's create a new issue

**Comment by mattab** [comment]
All done! if you have further suggestion on how to improve `core:archive` log output, feel free to create new issues
