### ISSUE TITLE
Automatically generate a multilingual Glossary using Piwik translations

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6773]
The goal of this issue is to create a Glossary for Piwik, that will be automatically generated using the existing Piwik translations.

 * Glossary will contain the definition of all metrics found in reports (for which we have some documentation)
 * Where to display it:
  * On Piwik.org website 
  * On FAQ
  * In the product, where?
 * Glossary will be multi-lingual and available in dozens of languages

**Comment by MagicFab** [comment]
We discussed this recently in person and I suggested this could be a generic, unbranded online resource with freely licensed content which could then be reused, improved and shared by others.

A section specific to Piwik could then be implemented (as well as inviting other analytics tools to have their section).

This would also be an interesting tools for book authors and online writers.

**Comment by MagicFab** [comment]
I've also opened a [forum discussion here](http://forum.piwik.org/read.php?3,129141,129141#msg-129141).

**Comment by mattab** [comment]
@MagicFab Good news, I made some progress today on this feature. PR:  #8793

Here is preview of the page so far:

![glossary piwik](https://cloud.githubusercontent.com/assets/466765/9870843/94472f2e-5be3-11e5-8793-7f1ae6bb336c.png)


What do you think?

**Comment by gaumondp** [comment]
Constructive suggestion: Remove the "date selector" when it doesn't make sense.

I created #8798

**Comment by MagicFab** [comment]
@mattab great work, no doubt this will be appreciated! This is awesome :)

I understand now this current implementation (coming up in 2.15) is done within Piwik itself, so having a dedicated site by itself with separate licensing, etc. is a more ambitious undertaking. In the longer term I still think what I proposed above could be useful. Should I file a separate issue for that?

**Comment by mattab** [comment]
Glossary is now displayed in the Left "user" Menu, and when clicking on "Help". It's visible for anonymous user, such as on the demo.piwik.org - The menu link won't be visible for view/admin/super users as to not clutter the menu. The Glossary is also linked from the Help page content itself.

See it live @ http://demo.piwik.org/index.php?module=API&action=glossary&idSite=7&period=day&date=yesterday

**Comment by mattab** [comment]
Glossary is now available at: http://glossary.piwik.org/

It lists all metrics, reports glossary, then lists the languages (with a link), to display the glossary in any language.

For example, glossary in German: http://glossary.piwik.org/?language=de

(this new service was added to our monitoring: http://status.piwik.org/)

Any feedback most welcome!  cc @MagicFab 


TODO before closing this issue:

 * [ ] Create a FAQ to link to the glossary
 * [ ] Link to the glossary from a few relevent FAQ eg. https://piwik.org/faq/general/#faq_36 https://piwik.org/faq/general/#faq_86 etc.
 *

**Comment by MagicFab** [comment]
Amesome implementation of the glossary in a separate page, thank you! That's my feedback for now, we should invite feedback from forums/social media/translators before release.

**Comment by mattab** [comment]
it was posted on twitter: https://twitter.com/piwik/status/651115657501650944
and facebook: https://www.facebook.com/Piwik/posts/10153602451725502

A new FAQ was created: [ Is there a Glossary or lexicon of all terms used in Piwik?](https://piwik.org/faq/new-to-piwik/faq_20877/)

**Comment by mattab** [comment]
Marking as closed for now, but your feedback is welcome and we will listen & follow up on suggestions :+1:
