### ISSUE TITLE
Implement CLI command to precisely delete raw data by date and idsite

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#6785]
There are some Piwik instances that are heavily using Log Analytics/Log Replay feature. However in some cases it's required to delete previously imported data and run import again (i.e. log files were incomplete or corrupted).

It would be great improvement in process, if there could be a CLI method deleting properly raw data from all log_* tables by given date and idsite.
Such command would perform timestamp shift between site timezone and UTC and purge data properly without manual action on admin side.

**Comment by mattab** [comment]
This command logic should reuse the [Delete old unprocessed data](https://piwik.org/docs/managing-your-databases-size/#deleting-old-unprocessed-data) feature in Privacy manager. Code is in the class `LogDataPurger` and can be reused/improved to do the job to delete a given date range.

**Comment by mattab** [comment]
Moved to 2.14.0

**Comment by mattab** [comment]
This will be documented in a new FAQ, see #8118
