### ISSUE TITLE
Error: specify a value for 'reportUniqueId' when exporting Insights reports

### ISSUE THREAD

**Issue by J-Mishima** [piwik/piwik#6790]
Hi.

An error written in the title in the following procedures occurs.

1.Display 'Action' -> 'Pages'.
2.Click 'Insight' icon in the bottom of the report.
3.Export as CSV(or other format).
4.Show message "Error: Please specify a value for 'reportUniqueId'." in new window

This issue is reporduced any report that have 'Insight' mode.

I use Windows 7 Pro and Chrome 39.0.2171.71 m.

![st0197](https://cloud.githubusercontent.com/assets/9860221/5275339/e207ea62-7ae5-11e4-8ef4-c7cb44dc5901.JPG)

![st0198](https://cloud.githubusercontent.com/assets/9860221/5275347/01aea856-7ae6-11e4-8be5-ab22ecff26b3.JPG)

![st0199](https://cloud.githubusercontent.com/assets/9860221/5275349/0553f16e-7ae6-11e4-8daf-90e50caa0346.JPG)

![st0200](https://cloud.githubusercontent.com/assets/9860221/5275351/07fcae74-7ae6-11e4-9ee5-7634b7a97fc9.JPG)

**Comment by tsteur** [comment]
Just noticed it is not easily possible to disable all export links... at least not with introducing a new visualization config so might be worth to fix it properly.
