### ISSUE TITLE
Create Piwik <> CloudFlare integration

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6797]
The goal of this issue is to create an integration for CloudFlare that will let CloudFlare users easily configure their website to use Piwik analytics.

CloudFlare has a huge userbase and client base and such integration would really help Piwik getting exposed to them. Plus users have asked us a few times already for such integration!

The CloudFlare module will let users:
- Use their own self hosted Piwik server (by specifying their Piwik URL, website ID)
- Use [Piwik Cloud](http://www.innocraft.cloud) in case they need a Piwik server setup for them

**Comment by bradberger** [comment]
Came across this just now.

After using both CF and Piwik for a while, got the same idea. CloudFlare just approved and [published a simple integration](https://www.cloudflare.com/apps/piwik_open_source_web_analytics). The repository is on GitHub at [BitolaCo/piwik-cloudflare](https://github.com/BitolaCo/piwik-cloudflare).

Would be happy to add the Piwik Cloud to the integration, if you guys could point me in the right direction.

**Comment by mattab** [comment]
Update: a CF App has been created at: https://github.com/BitolaCo/piwik-cloudflare - I'm communicating with Brad and we will collaborate on this project :+1:

**Comment by natedalliard** [comment]
Any updates on this? I don't get piwik to work on github pages + jekyll + cloudflare.

**Comment by joncamfield** [comment]
+1 I would like this feature

**Comment by mattab** [comment]
[Piwik app on CloudFlare is now available!](https://www.cloudflare.com/apps/piwik)
