### ISSUE TITLE
Add Redis session handler and/or better: Let plugins define session handlers

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6800]
I think it makes sense to offer the possibility to use Redis to manage sessions as mentioned in #6637 and later by another user in #6075. Redis is just perfect for storing sessions when using multiple frontend nodes as an alternative to database. All operations are performed in memory making reads and writes blazing fast. 

It is very easy to configure in case the Redis extension [phpredis](https://github.com/nicolasff/phpredis) is installed which is required for Queued Tracking #6075 anyway.

```
session.save_handler = redis 
session.save_path    = tcp://127.0.0.1:6379  // I think multiple servers can be configured comma separated
```

**Comment by mattab** [comment]
this new features will be documented as a FAQ in #7767
