### ISSUE TITLE
import_logs.py does not work in apache 2.4 in pipe mode

### ISSUE THREAD

**Issue by karlsoon** [piwik/piwik#6805]
Hi!
Script does not record lines.
This is example of output:
212 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
No any errors in log with -d.
How i can help you to find the problem?
I tried 2.9.1 and master version.

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
