### ISSUE TITLE
curl_exec: name lookup timed out. Hostname requested was: plugins.piwik.org

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#6832]
Since Piwik 2.10.0b6 Marketplace can't be browsed while being inside Admin Interface because of mentioned error caused by cURL php extension. 

[Proxy] configurations are set and authentication is done correctly. 

As far I can test, Marketplace was browsable flawless while being behind a proxy in version 2.9.0b8. 

 * module=CorePluginsAdmin
 * action=browsePlugins

**Comment by mattab** [comment]
Hi @tassoman 
We didn't really change anything in the proxy code. Are you confident the proxy,and DNS server, are working OK?

**Comment by tassoman** [comment]
I'll test again as soon as possible, in the meantime I'm asking organization's sysadmins some kind of development server outside in the DMZ.

**Comment by tsteur** [comment]
Is there any update on this?

**Comment by tassoman** [comment]
I've just pulled latest master branch and tested, well it turned in a _worksforme_ "automagically" :sweat: 
Probably we had some issues on proxy/dns services configuration.

**Comment by tsteur** [comment]
Thx for letting us know. Feel free to reopen if needed
