### ISSUE TITLE
Investigate if there are any memory leak in the Archiving process (yearly archives run out of memory)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6846]
The goal of this issue is to investigate the memory usage of Archiving to check whether there are memory leaks and if it can be improved. In particular we will focus on one particular Piwik PRO client that required more than 4Gb of memory to process the 2014 Yearly report. 

Error was:  `PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 8208 bytes) in piwik-2.8.3/core/DataTable.php on line 1156`

Maybe a XHProf run could help us find some memory issues, or maybe we will conclude that the current implementation of sub-tables is simply not fitting for this (next step would be: #6763)...

**Comment by mattab** [comment]
we've made a lot of progress in performance, memory, CPU usage of Piwik in 2.12.0

The archiver was profiled and tweaked several times. We consider this issue done for now (first big step). if anyone still experiences 1G memory exhausted issue for yearly archiving or other periods, then please create a new issue and we will follow up!

**Comment by tsteur** [comment]
FYI: I did some tests on the big instance and it takes about 4GB of memory to archive the year when having lots of data with a total execution time of 50 minutes. 95% of the time is spent in archiving action urls. 3.6GB of memory were used at peak by `Piwik\DataTable::addRowsFromSerializedArray`. 4GB still sounds ok for me. I don't think there is an actual memory leak! It is just what it needs to build thousands of datatables etc.
