### ISSUE TITLE
delete recovered carts from abandoned carts list/graph

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#6896]
Hi,

Will recovered Carts still show up in abandoning carts?
It would be nice to show they complete and hide them from abandoned carts please.

thanks

**Comment by mattab** [comment]
>  After user adds a product to the cart, abandoned cart is created. If user places an order within the same session, this abandoned cart is deleted and you have only an ecommerce order.

Yes, the abandoned cart is always deleted when there is an ecommerce order in the same visit.
