### ISSUE TITLE
Where can I find the Dashboard UI files in PIWIK

### ISSUE THREAD

**Issue by mr360** [piwik/piwik#6913]
I would like to edit some of the menu names and options, but I do not know which files are responsible for this.

If you could help, it would be great!

**Comment by tsteur** [comment]
`plugins/Dashboard/Menu.php`
`plugins/Dashboard/lang`
`plugins/Dashboard`

for any further help or development related questions please ask in Forum next time:  http://forum.piwik.org/list.php?9
