### ISSUE TITLE
Rename plugin management commands

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#6915]
As discussed in #6801 it would be good to rename the following commands:

- `core:plugin activate` in `plugin:activate`
- `core:plugin deactivate` in `plugin:deactivate`
- `plugin:list` (not sure if this one needs to be renamed or created)

Also:

> The ManagePlugin.php command contains actually 3 commands and should be refactored into 3 actual commands, meaning 3 files.

**Comment by mnapoli** [comment]
Also updating the docs with the new commands would solve the original problems of #6801.

**Comment by mattab** [comment]
If we can keep BC for existing scripts using `core:plugin` it would be nice... if not possible, let me know

**Comment by mnapoli** [comment]
Commands renamed + `plugin:list` displayed as a table with a few information:

![capture d ecran 2015-01-12 a 12 38 51](https://cloud.githubusercontent.com/assets/720328/5697522/2743b6ec-9a58-11e4-8f23-8dcccc1fe9fd.png)

I'll update the developer docs.

**Comment by mattab** [comment]
oh, a pretty table! nice change :+1:
