### ISSUE TITLE
Click tracker piwki.php?redirect=[params] was not working 

### ISSUE THREAD

**Issue by johnefemer** [piwik/piwik#6918]
i noticed the target link was not redirecting to the outlink after tracking the interaction.   
````
redirecturl=https%3A%2F%2Fmyhost.com&c_i=click&c_n=FREE%20TShirts&c_p=414%7C0%7CFREE%20TShirts&c_t=https%3A%2F%2Fmyhost.com&idsite=4&rec=1&r=360231&h=13&m=9&s=2&url=https%3A%2F%2Fmyhost.com%2F&_id=731f778e6984d599&_idts=1420410246&_idvc=2&_idn=0&_refts=0&_viewts=1420410526&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=3360x2100&gt_ms=790

````
it seems theres no header 301 in the Url.php,
i added the following line before line 486,
```
            Common::sendHeader("HTTP/1.1 301 Moved Permanently");
```
now its redirecting to the target.

**Comment by mattab** [comment]
Hi @johnefemer thanks for the report!

**Comment by tsteur** [comment]
Shouldn't it be a 302 Not Found / Moved Temporarily or since HTTP 1.1 a 307 Temporary Redirect?

**Comment by mattab** [comment]
`302` http redirect sounds good
