### ISSUE TITLE
Visits Over Time Graph - Bounce rate percentage mis-calculated

### ISSUE THREAD

**Issue by THEANONYMOU5** [piwik/piwik#6923]
Just upgraded to the latest release, 2.10.0 this morning.  It Seems that for the Visits over time Graph the line graph showing the bounce rate is displaying the incorrect bounce rate on hover.  That is, the visual graph is 'okay' but the 'tooltip' on hover is what is displaying incorrect info.  All my bounce rates are showing as < 1%.  Screen shot  attached.
![bug-report_piwik_v2 10](https://cloud.githubusercontent.com/assets/2895660/5617092/b1ec1418-94bf-11e4-8720-44768e05d310.PNG)

**Comment by sgiehl** [comment]
The graph looks correct. The scale for the bounce rate is on the left and matches what is shown in the popover. Maybe your overall bounce rate is that low?

**Comment by THEANONYMOU5** [comment]
Hi, Sorry. I looked more closely.  The scale on the graph is actually
correct based on what is shown on the popover.  But, the average bounce
rate for that site is typically 28-33%, the popover is is showing 0.33%.
It is off by a factor of 10.  The Visits Overview widget correctly shows a
bounce rate of 30%.  I'm showing this same issue across all the sites I am
tracking.

As much as I wish the bounce rate is .33%, that is not the case.

If you require more info please let me know.

-Robert

**Comment by sgiehl** [comment]
Ah ok. I just had a look at your screenshot. Sounds like a bug for me...

**Comment by THEANONYMOU5** [comment]
Fyi,  domain age is also displaying incorrect.   Example: "141379:30:28"

**Comment by mattab** [comment]
> Fyi, domain age is also displaying incorrect. Example: "141379:30:28"

Hi @THEANONYMOU5 can you create another issue for this other bug (please mention the domain name)

**Comment by THEANONYMOU5** [comment]
Submitted,  issue #6925

**Comment by sgiehl** [comment]
@diosmosis That issue seems to be related with one of your tasks. Guess in that case the [API Inconsistensies](https://github.com/piwik/piwik/commit/8cace074b03bbc9fa8f1175b51613eb45ffdf67b) are not applied.
