### ISSUE TITLE
SEO Rankings Widget - Bad display format for Domain age

### ISSUE THREAD

**Issue by THEANONYMOU5** [piwik/piwik#6925]
Domain Age is showing in a format that is not easily human readable.  Please see attached image.
Domain: ganahllumber.com.

![bad domain age](https://cloud.githubusercontent.com/assets/2895660/5618712/799ba31a-94d0-11e4-8251-5004b2925d3b.PNG)

**Comment by mattab** [comment]
Hi @THEANONYMOU5 thanks for the report.
