### ISSUE TITLE
API returned an error: Sequence 'piwik_archive_numeric_2015_01' not found. at Sequence.php:99

### ISSUE THREAD

**Issue by purecanuck** [piwik/piwik#6929]
I just updated to Piwik version 2.10.0 by unziping the zipfile, moving my config file into it, and then clearing the cache via php on the command line.

When I go to $URL/index.php?module=MultiSites&action=index&idSite=5&period=day&date=today

I get error message: 
API returned an error: Sequence 'piwik_archive_numeric_2015_01' not found. at Sequence.php:99

**Comment by mattab** [comment]
Hi there,

to fix this issue you can execute the Mysql QUERY:
```
INSERT INTO piwik_sequence (name, value) VALUES ('piwik_archive_numeric_2015_01' , 99999)
```

**Comment by sgiehl** [comment]
Similar issues were repoted on the forum more than once.

Couldn't we simply create the sequence when it isn't found but should be
there?

**Comment by mattab** [comment]
see #6815

reason we didnt so far put a workaround is because it's a one-off issue, only heappen when old users upgrade, and in quite particular edge case...

**Comment by sgiehl** [comment]
IIRC there was one on the german forum having the issue after upgrading
from 2.9.1 to 2.10

**Comment by amq** [comment]
I am experiencing the same issue - the insert fixed it for January, but now it is back. Will I have to run the insert each month?

**Comment by purecanuck** [comment]
mysql> INSERT INTO piwik_sequence (name, value) VALUES ('piwik_archive_numeric_2015_01' , 99999);
ERROR 1062 (23000): Duplicate entry 'piwik_archive_numeric_2015_01' for key 'PRIMARY'

**Comment by purecanuck** [comment]
I'm still getting this issue after upgrading to Piwik 2.11.

**Comment by purecanuck** [comment]
Let me know if there's any more information I can provide.

**Comment by mattab** [comment]
We need to do something about this bug, adding `Major` tag

**Comment by mattab** [comment]
@tsteur maybe you have an idea how we could fix this one in a proper way?

**Comment by pfmoser** [comment]
New month, new luck. All my APIs requests from WordPress did have the error for the new month. 

INSERT INTO piwik_sequence (name, value) VALUES ('piwik_archive_numeric_2015_03' , 99999)

did solve the problem for now, but I did a regular update via Dashboard and nothing in special. Please fix this before the next month. Thanks.

**Comment by mattab** [comment]
That's strange but I also got this error in the UI tests after upgrading the OmniFixture, eg. http://builds-artifacts.piwik.org/ui-tests.transitions_deterministic_order/10588.8/screenshot-diffs/singlediff.html?processed=../processed-ui-screenshots/EvolutionGraph_annotations_none.png&expected=EvolutionGraph_annotations_none.png&github=EvolutionGraph_annotations_none.png

I'll take a look at this bug...
