### ISSUE TITLE
Set Avatar via JavaScript

### ISSUE THREAD

**Issue by ShiroUlv** [piwik/piwik#6936]
An option should be added to the JavaScript API for setting the user's avatar. A lot of sites rely on the JS tracking code and this would be a really useful implementation.

**Comment by tsteur** [comment]
Do you mean do see an avatar in the visitor profile? Please have a look here: http://plugins.piwik.org/VisitorAvatar

Feel free to reopen / comment in case this is not what you meant.

**Comment by Natgho** [comment]
I have same problem. When user logged in, I want to add user profile photo to Matomo using with Javascript.
