### ISSUE TITLE
Make Travis CI build status render faster by logging less output during builds

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6942]
The goal of this issue is to make a given build page on travis ci load faster.

### Reproduce

1. load this URL: https://travis-ci.org/piwik/piwik-ui-tests/builds/46151349 
2. Loading the build page takes 5-10 seconds, this is slow especially when we have to do this 10+ times a day. 

### Explanation

The page loads with ajax [the build log ](https://s3.amazonaws.com/archive.travis-ci.org/jobs/46151350/log.txt) -> it's quite large at 358.0 kB. We load these URLs many times a day since we often do test driven development. Daily we use CI.

### Proposed solution
 * the "build setup phase" generates 215kb+ of text (see the first two thirds of the build log) -> we could remove most of this text by piping it to a file instead?

**Comment by diosmosis** [comment]
I've noticed sudo apt-get ... commands result in the command continuously outputting status lines like `....  100%`, I guess because it can't modify the last line as it would in a normal terminal. Quieting those command might help w/o making travis harder to debug.
