### ISSUE TITLE
CI Build on PHP 5.3.3 fails with `Bus error`

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6943]
Umh... what does `Bus error` mean? 

Our builds are now failing on PHP 5.3.3 with this Bus Error. Then we get `The command "" exited with 135.`
```
Configuration read from /home/travis/build/piwik/piwik/tests/PHPUnit/phpunit.xml

............................................S.........​​​S.SSSSS 61 / 5349 ( 1%)

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBus error
```

Example: https://travis-ci.org/piwik/piwik/jobs/46153053

any idea?

**Comment by mnapoli** [comment]
Thanks forgot to reference the commit. Here is the bug description: https://bugs.php.net/bug.php?id=53976

**Comment by mnapoli** [comment]
I think we can close this because following the commit the build passed: https://travis-ci.org/piwik/piwik/builds/46156937

Now builds on master are failing because of "MySQL server has gone away".
