### ISSUE TITLE
Using Piwik get a avg_time_on_page  of resulting  has a lot different

### ISSUE THREAD

**Issue by mabaojia** [piwik/piwik#6952]
hi,I have a question.
I'm Chinese,My English is poor,Please understand.
I want to know the trackPageView function.
There were two results was a lot different "trackPageView" with arguments or without arguments.
I don't know what happend,what is the difference between them.

first :

_paq.push(['trackPageView','Variable']);
Variable ：avg_time_on_page result is always 1 sec.
second : 

_paq.push(['trackPageView']);
default ： avg_time_on_page result is correct.

thanks all.

**Comment by mnapoli** [comment]
Duplicates #7027, please follow the other issue for updates.
