### ISSUE TITLE
No schema change allowed on log_visit nor log_link_visit_actions nor log_action tables   

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6953]
The goal of this issue is to ensure that in Piwik 2.11.0, Piwik 2.12.0, Piwik 2.13.0 and maybe Piwik 2.14.0 we do not introduce any major schema change impacting log_visit or log_link_visit_action.

In the meantime we will research a solution for the database to handle such schema changes in a more manageable way. Maybe Mariadb + TokuDB will solve this.

**Comment by mattab** [comment]
See this comment which links to percona article:  https://github.com/piwik/piwik/issues/6759#issuecomment-73435826

**Comment by mattab** [comment]
This issue still applies to 2.14.0 - but it is planned that in Piwik 3.0.0 we will be able to issue schema changes again (to be confirmed!)

**Comment by tsteur** [comment]
Can we close this issue? I find it kinda useless and annoying seeing this all the time and it pollutes the milestone.

**Comment by mattab** [comment]
@tsteur Moved to 2.15.0. We will be able to add schema changes in Piwik 3.0.0. I'd prefer to leave it opened while it's active to make this policy clear since it can be counter intuitive (eg. if new team members join)

**Comment by tsteur** [comment]
I doubt they would directly make big changes to that and if so, we can still mention that if something potentially needs that ;) Also unlikely that someone would see it in the next milestone then

**Comment by mattab** [comment]
Starting in 3.0.0 beta cycle, we can make database schema changes! :rocket: it feels good after 7 months to close this issue.

**Comment by mattab** [comment]
There will be many schema changes in Piwik 3.0.0.
