### ISSUE TITLE
.git/ files should not be part of integrity check

### ISSUE THREAD

**Issue by mtandersson** [piwik/piwik#6955]
(When upgrading from 2.9.0 -> 2.10.0)

I have the piwik source in a private git repo together with my config file other elb files for easy deploy on aws elastic beanstalk.

And when doing a deploy i use
git archive --format zip and then I upload that to elasticbeanstalk. 

When doing that i don't get the .git filders/files. I get warnings in the integrity check on the following files:

File integrity check failed and reported some errors. This is most likely due to a partial or failed upload of some of the Piwik files. You should reupload all the Piwik files in BINARY mode and refresh this page until it shows no error.
Missing file: /var/app/current/piwik/libs/PiwikTracker/.git
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/config
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/description
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/FETCH_HEAD
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/HEAD
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/applypatch-msg.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/commit-msg.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/post-update.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/pre-applypatch.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/pre-commit.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/prepare-commit-msg.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/pre-push.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/pre-rebase.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/hooks/update.sample
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/index
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/info/exclude
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/logs/HEAD
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/logs/refs/heads/filecache-race-condition-fix
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/logs/refs/heads/master
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/logs/refs/remotes/composer/filecache-race-condition-fix
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/logs/refs/remotes/composer/master
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/logs/refs/remotes/origin/HEAD
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/objects/pack/pack-8cb633474ee22e2ef6bd1611fe0ba72abc2eca64.idx
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/objects/pack/pack-8cb633474ee22e2ef6bd1611fe0ba72abc2eca64.pack
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/ORIG_HEAD
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/packed-refs
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/refs/heads/filecache-race-condition-fix
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/refs/heads/master
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/refs/remotes/composer/filecache-race-condition-fix
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/refs/remotes/composer/master
Missing file: /var/app/current/piwik/vendor/doctrine/cache/.git/refs/remotes/origin/HEAD

In my opinion these files should not be part of the integrity check.

**Comment by mattab** [comment]
Thanks for report, it was fixed in https://github.com/piwik/piwik-package/commit/97ff1702c68f6025c5a8ea45114822a41fe9bd2a
