### ISSUE TITLE
Nothing shows up in dashboard after import logs 

### ISSUE THREAD

**Issue by bsmurali** [piwik/piwik#6956]
I was able to run the command sucessfully, but unable to see the new log data in piwik site. Everything is empty on piwik site.

C:\wamp\www\piwik\misc\log-analytics>import_logs.py --token-auth=3b5d086966125a31fd42ed90029c012c --url=http://localhost/piwik F:\ANALYTICS\ext_request.log --add-sites-new-hosts --enable-http-redirects --enable-static --log-format-name=ncsa_extended --enable-bots --enable-reverse-dns --recorders=8 --enable-http-errors --enable-http-redirects --idsite=1

I am following the below sequence

call move_logs.bat
call rename_log.bat
call parse_ext.bat
call parse_int.bat
call archive.bat
call delete_logs.bat

**Comment by sgiehl** [comment]
Did the database fill up with entries in the log_visit / log_visit_action / ... tables?
Maybe you need to [reprocess the data](http://piwik.org/faq/log-analytics-tool/#faq_17994)

**Comment by tsteur** [comment]
@bsmurali  do you still experience this issue? Please let us know otherwise we will close the issue. Please let us also know in case it works now.
