### ISSUE TITLE
Segmentation by User ID

### ISSUE THREAD

**Issue by jantlwoomy** [piwik/piwik#6959]
Task is to separate visits to Users (visitors who has user_id) and Not users (who has not).
How to reproduce:
1. Make visit without setting userID
2. Make another visit from another browser with `_paq.push(["setUserId", 'userid@mydomain.org'])`
3. Go to Piwik, switch to the Visitors - Visitor Log tab. There are 2 visits - without userID (visit1) and with it (visit2).
4. Create new Segment: name - Not Users, Metric: User ID, Match: Is, Value: Empty string
5. Create new Segment: name - Users, Metric: User ID, Match: Is Not, Value: Empty string

Expected results:
* Segment Not Users: only visit1
* Segment Users: only visit2

Actual results:
* Segment Not Users: Empty list
* Segment Users: visit1, visit2

Please see #6954

**Comment by asafyish** [comment]
+1

**Comment by tsteur** [comment]
I was able to reproduce this issue and pull request #6954 looks actually correct for me. The proposed change fixes the issue. I was already wondering why there is not the `user_id` used a while ago... @mattab do you have any objections reopening and merging that pull request (if tests succeed)?

**Comment by mattab** [comment]
@jantlwoomy PR was merged, closing, thanks for report & solution!
