### ISSUE TITLE
Selected Segment style

### ISSUE THREAD

**Issue by jantlwoomy** [piwik/piwik#6961]
Currently selected Segment is not highlighted.
How to reproduce:
1. Create new Segment: name - Not Users, Metric: User ID, Match: Is, Value: Empty string
2. Click at the Segment drop-down.

Expected result: **Not users** should be highlighted with bold.
Actual result: Not users is the same as All visits (default)

There is two reasons:
1. CSS selectors
2. Incorrect JS in the Google Chrome that doesn't add "segmentSelected" class to the list item.

Please see https://github.com/jantlwoomy/piwik/compare/selected_segment_css#diff-e43aeb1ad6d1b908a927966027b16135L682

**Comment by sgiehl** [comment]
Feel free to create a pull request
