### ISSUE TITLE
After Upgrade from piwik 2.9 to 2.10: piwik/core/AssetManager/UIAsset/OnDiskUIAsset.php(61): Warning - unlink(

### ISSUE THREAD

**Issue by davefreemanHH** [piwik/piwik#6965]
Hallo everybody !

After finishing the upgrade from piwik 2.9. to 2.10 with the piwik upgrade scripts, i can login to piwik, IT RUNS, but i get the warning:

piwik/core/AssetManager/UIAsset/OnDiskUIAsset.php(61): Warning - unlink(

piwik/tmp/assets/asset_manager_global_css.css): No such file or directory - Piwik 2.10.0 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)

Of course it is just a minor css bug, but it can be surely solved by some nice developer.

My piwik runs on:
Ubuntu 12.04.5 LTS

PHP-Version >= 5.3.3
PDO Erweiterung
PDO\MYSQL Erweiterung
MYSQLI Erweiterung
Weitere erforderliche Anforderungen zlib
SPL
iconv
json
mbstring
Reflection
Erforderliche Funktionen debug_backtrace
create_function
eval
gzcompress
gzuncompress
pack
Benötigte PHP Konfiguration (php.ini) session.auto_start=0
Verzeichnisse mit Schreibzugriff /var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/assets
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/cache
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/climulti
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/latest
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/logs
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/sessions
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/tcpdf
/var/www/vhosts/lvps92-51-133-35.dedicated.hosteurope.de/hq-high-red-head.de/piwik/tmp/templates_c

Optional

Dateiintegrität
Tracker-Status
Speicherlimit 128M
Zeitzone
URL curl
PageSpeed deaktiviert
GD > 2.x + Freetype (graphics)
Andere Erweiterungen json
libxml
dom
SimpleXML
Andere Funktionen set_time_limit
mail
parse_ini_file
glob
gzopen
Dateisystem OK
Archiv Cron Prozesse via CLI steuern: nicht unterstützt (optional)
Standorterkennung Standorterkennung funktioniert, aber Sie nutzen keinen der empfohlenen Anbieter. Falls Sie Protokolldateien oder andere Dinge importieren welche IP-Adressen enthalten können Sie die PECL GeoIP Implementierung (empfohlen) oder die PHP GeoIP Implementierung wählen.
Datenbankfähigkeiten LOAD DATA INFILE

Die Benutzung von LOAD DATA INFILE erhöht die Geschwindigkeit des Piwik Archivierungsprozesses erheblich. Um dies für Piwik verfügbar zu machen setzen Sie bitte eine neuere PHP & MySQL Software ein und stellen Sie sicher, dass der gewählte Datenbankbenutzer das FILE Recht besitzt.
Falls Ihr Piwik Server Webseiten mit erhöhtem Verkehrsaufkommen (z.B.: > 100.000 Seiten pro Monat) verarbeiten muss empfehlen wir dieses Problem zu beheben.
Fehler:
Try #1: LOAD DATA INFILE : SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'piwik_4'@'%' (using password: YES)[28000]
Troubleshooting: FAQ on piwik.org

**Comment by sgiehl** [comment]
maybe related with #6927

**Comment by mattab** [comment]
This was fixed in 2.11.0
