### ISSUE TITLE
"Get visitors real time" fails after upgrade 2.10

### ISSUE THREAD

**Issue by mcsl** [piwik/piwik#6966]
The update worked fine, only the widget "visitors in real time" fails. I already deactivated the plugin and activated it again and cleared all tmp files. No change.

Error message:
Key "plugins" for array with keys "idSite, idVisit, visitIp, visitorId, actionDetails, goalConversions, siteCurrency, siteCurrencySymbol, serverDate, visitServerHour, lastActionTimestamp, lastActionDateTime, userId, visitorType, visitorTypeIcon, visitConverted, visitConvertedIcon, visitCount, firstActionTimestamp, visitEcommerceStatus, visitEcommerceStatusIcon, daysSinceFirstVisit, daysSinceLastEcommerceOrder, visitDuration, visitDurationPretty, searches, actions, referrerType, referrerTypeName, referrerName, referrerKeyword, referrerKeywordPosition, referrerUrl, referrerSearchEngineUrl, referrerSearchEngineIcon, deviceType, operatingSystem, operatingSystemCode, operatingSystemIcon, browserFamily, browserFamilyDescription, browser, browserName, browserIcon, browserCode, browserVersion, events, continent, continentCode, country, countryCode, countryFlag, region, regionCode, city, location, latitude, longitude, visitLocalTime, visitLocalHour, daysSinceLastVisit, provider, providerName, providerUrl, customVariables, serverTimestamp, serverTimePretty, serverDatePretty, serverDatePrettyFirstAction, serverTimePrettyFirstAction" does not exist in "@Live/getLastVisitsStart.twig" at line 12

![piwik](https://cloud.githubusercontent.com/assets/1553988/5680194/ff3e350a-9809-11e4-9410-33da1b594d62.jpg)

**Comment by tetsuo13** [comment]
I had the same issue. Looking through the PHP error logs I noticed two other issues which were caused by the deactivated **Resolution** and **DevicePlugins** plugins. After activating them the errors in the log cleared up and strangely enough the **Visitors in Real-Time** widget also started working without issue.

In my case this widget error was caused by other factors. You might want to check your PHP error log.

**Comment by mcsl** [comment]
Thanks, after activating the Device Plugin the "visitors real time" worked again.
However, since this is a work-around but does not fix the problem I leave this issue open.

**Comment by sgiehl** [comment]
Did you do the update manually or with the web interface?

**Comment by mcsl** [comment]
Manually.

**Comment by mattab** [comment]
FYI it can happen that plugins don't get activated during update, eg. when the config file is not writable. Ideally Piwik should work when any plugin is disabled.
