### ISSUE TITLE
Referrers Overview, distinct metrics sparklines are always set to one

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6972]
The Referrers > Overview now displays the Sparklines for Distrinct metrics Referrers (they were before hidden behind a `more info` link).

The goal of this issue is to make the sparklines display correct values instead of zeros:
![sparkines](https://cloud.githubusercontent.com/assets/466765/5690915/bbb75c38-990f-11e4-959b-038a21c55ff0.png)

**Comment by diosmosis** [comment]
@mattab Looks correct to me. The sparklines display 0 => 1 and evolution is 0% because it's 1 search engine and 1 search engine now (so 0% change).

**Comment by diosmosis** [comment]
@mattab I think the metrics might be wrong though... there should be more than one distinct search engine & referrer.

**Comment by mattab** [comment]
@diosmosis changed title to reflect the bug

**Comment by mattab** [comment]
fixed in #7034
