### ISSUE TITLE
product conversion/price code add autom. for wocommerce shop

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#6975]
you say i have to integrate a code to show the product name and value on each product. If i have 1000 products it could not be done.
it would be nice if you do it by auto. i wrote this also to the Wordpress woocommerce piwik team with less results.
https://wordpress.org/support/topic/add-additional-code-to-track-product-page-viewsconversions?replies=3

https://wordpress.org/plugins/woocommerce-piwik-integration/

**Comment by mattab** [comment]
Hi @Tobias-Conrad is the woocommerce-piwik WP plugin working OK for you now? if not, please create an issue at: https://github.com/PiwikPRO/3rdparty-woocommerce and we will follow up

**Comment by Tobias-Conrad** [comment]
done: https://github.com/PiwikPRO/3rdparty-woocommerce/issues/10

**Comment by Tobias-Conrad** [comment]
done also for WP-PIWIK plugin https://github.com/PiwikPRO/3rdparty-woocommerce/issues/11
