### ISSUE TITLE
Bad archiver behavior

### ISSUE THREAD

**Issue by DaSchTour** [piwik/piwik#6977]
Well I discovered some bad behavior of the archive script. The first problem is, that the logfile is overwritten. This means, that there is no possibility to check if there was any broken archiving.
The next problem is, that if some parts are not archived because of inconsistencies, this isn't seen as an error and not reported as such. The next thing is, that the script sometimes seems to correctly run through without finishing the logfile. The data is correctly stored but the logfile is doesn't end with finish. Which maybe leeds to the inconstancies which are not reported. So I have to watch the logfiles manually if there is anything wrong. So I also could start archiving manually which would result in the same amount of work. I would like to post some logfile, but as they are deleted when the archiver is stared again I have non of them.

**Comment by DaSchTour** [comment]
Additionally there seems to be a problem with the following:
When this event occurs: "Will ignore websites and help finish a previous started queue instead. IDs: 6" the next archive run will  starts with: "Will process 1 websites with new visits since 29s , IDs: 1" which is somehow stupid, because this page might not have been processed for weeks because it was hanging on queue for ID:6 which than might lead to the problem, that some week or month reports are not available. Also a problem which is randomly discovered and is only fixable by deleting the logs and creating completely new, which takes a lot of time and than also leads to problems and interference with the cron tasks.

**Comment by gaumondp** [comment]
I don't know if I misunderstand the comment about log being overwritten but here is how I keep it grow using the cron job :

``*/15 * * * * php /piwik/console core:archive --url=http://1.2.3.4 >> /logs/piwik-cron.log``

 Using ">>" make the log grow but you keep the full history.

**Comment by mattab** [comment]
can you create an issue for each problem, i'm a bit lost here + see @gaumondp comment for why the log was overwritten (we do this in the doc so that users don't end up with a log file of several Gb)
