### ISSUE TITLE
Key "plugins" for array with keys does not exist in "@Live/getLastVisitsStart.twig" at line 12

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6979]
Error reported in forum: http://forum.piwik.org/read.php?2,123395

> Error message:
> Key "plugins" for array with keys "idSite, idVisit, visitIp, visitorId, actionDetails, goalConversions, siteCurrency, siteCurrencySymbol, serverDate, visitServerHour, lastActionTimestamp, lastActionDateTime, userId, visitorType, visitorTypeIcon, visitConverted, visitConvertedIcon, visitCount, firstActionTimestamp, visitEcommerceStatus, visitEcommerceStatusIcon, daysSinceFirstVisit, daysSinceLastEcommerceOrder, visitDuration, visitDurationPretty, searches, actions, referrerType, referrerTypeName, referrerName, referrerKeyword, referrerKeywordPosition, referrerUrl, referrerSearchEngineUrl, referrerSearchEngineIcon, deviceType, operatingSystem, operatingSystemCode, operatingSystemIcon, browserFamily, browserFamilyDescription, browser, browserName, browserIcon, browserCode, browserVersion, events, continent, continentCode, country, countryCode, countryFlag, region, regionCode, city, location, latitude, longitude, visitLocalTime, visitLocalHour, daysSinceLastVisit, provider, providerName, providerUrl, customVariables, serverTimestamp, serverTimePretty, serverDatePretty, serverDatePrettyFirstAction, serverTimePrettyFirstAction" does not exist in "@Live/getLastVisitsStart.twig" at line 

Solution:
 * when DevicePlugins plugin is disabled, silently ignore the attribute  in the twig template
 * also check reports load when Resolution plugin is disabled

**Comment by sgiehl** [comment]
resolution plugin should not cause troubles as there already was a check for existence.
