### ISSUE TITLE
2.10.0, When the BulkTracking plugin is disabled, bulk imports succeed, but no data is imported

### ISSUE THREAD

**Issue by rmoesbergen** [piwik/piwik#6982]
When the BulkTracking plugin is disabled, the import_logs.py reports success when importing logfiles, but no data is actually imported. This may lead to unnoticed data loss. It would be better if the API reported an error when this plugin is disabled and a request for bulk importing data is done. I've reproduced this with version 2.10.0. Steps:

1. Disable the BulkTracking plugin and restart the webservice/PHP-FPM
2. Perform log imports using import_logs.py, the script will report 'OK'
3. Perform an archive run, no visits will be imported

**Comment by mattab** [comment]
Hi @rmoesbergen thanks for the report

**Comment by tsteur** [comment]
This needs to be fixed / handled in log importer as the behaviour in Piwik itself is correct/expected in this case. What Piwik does is returning a message like `Piwik is a free/libre web analytics that lets you keep control of your data.` in case it does not detect any request tracking data. So basically the log importer has to check whether the response is json and if not show an error maybe.
