### ISSUE TITLE
Reducing test failures due to non-bugs (eg, order of API output)

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6983]
Refs https://github.com/piwik/piwik/issues/6544

Tests (mainly system) can fail for many reasons that aren't actual bugs. This creates pointless work that should be avoided. This ticket contains a list of possible changes that can remove these bugs:

* [ ] **Do not test API rendering in system tests.**

  Avoids test failures that occur when formatting bugs are fixed or formats are changed.

  All tests should either compare against PHP arrays or DataTables themselves instead of rendering to XML/CSV/JSON and comparing against an expected file. The expected data can still be stored in files, we just shouldn't compare the rendered output.

* [ ] **When comparing API output, do not take column ordering into account.**

  Avoids test failures that occur when API output reorders columns.

* [ ] **Remove all PHP test code and put into composer managed component**

  Avoids test failures that occur when tests are run against older Piwik versions.

  Since the test related infrastructure will be managed by composer and not git, checking out a tag won't make new test code unavailable.

* [ ] **Instead of testing all available API methods, System tests should have individual test methods w/ descriptive names.**

  Avoids painful debugging of random changes to API output. Having a test method name that describes what the test is testing for narrows the focus and makes it easier to find the reason for test failures.

@mattab Please give me your thoughts.

**Comment by tsteur** [comment]
Order of API output might be important when using `sort` parameter, or in general the order is quite important or not? What is not important is the order within an "object/entity", meaning the properties. Maybe you meant that?

**Comment by mattab** [comment]
+1, in general the order of columns is important and should be tested in our system tests. better we make columns order fixed in core

**Comment by diosmosis** [comment]
> What is not important is the order within an "object/entity", meaning the properties. Maybe you meant that?

I meant column ordering as in DataTable row column ordering.

> better we make columns order fixed in core

Do you think the ordering of columns should be tested for all API methods?

**Comment by mattab** [comment]
We've made good progress at keeping the build greens!

> Do you think the ordering of columns should be tested for all API methods?

in system tests I think it's ok to test for columns order

Closing the RFC, we can create follow up issue where needed
