### ISSUE TITLE
waffle.io integration

### ISSUE THREAD

**Issue by cybernet** [piwik/piwik#6984]
can piwik benefit from this service ?

example https://waffle.io/piwik/piwik

**Comment by tsteur** [comment]
I don't think so. Basically we know something is in progress once an issue is assigned to someone. We don't have the "ready" state yet. More or less an issue is ready as soon as there is a label & milestone set. A good indicator for ready is, when an issue is in the current milestone. In general we try to solve those states with labels eg `review` etc.

Any thoughts on this? If not we can close it

**Comment by tsteur** [comment]
Feel free to comment or reopen if anyone is interested in it.

**Comment by cybernet** [comment]
i am not the only one who should speak up ... i'm just a user :)
