### ISSUE TITLE
Dreamka2007

### ISSUE THREAD

**Issue by Dreamka2007** [piwik/piwik#6985]
We are using piwik for some months already. From the begining i've add some goals, but piwik doesn't show me statisic by them. 
Maybe the problem is that we are using Server Log File Analytics, but do not put the Javascript code to the site?

![- piwik - 1 2](https://cloud.githubusercontent.com/assets/10500710/5705037/fdbc8552-9a7e-11e4-8849-7ed3988734a0.jpg)
![- piwik - 1 1](https://cloud.githubusercontent.com/assets/10500710/5705038/fdbcb3b0-9a7e-11e4-8b1c-75ab415b5173.jpg)

**Comment by mattab** [comment]
Hi @Dreamka2007 it should work fine. Are you sure that you set the Goal URL correctly? I see that it uses HTTPS, maybe your pages are tracked on HTTP and if you change it it would work?
