### ISSUE TITLE
video tracking - youtube video, html 5 video

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#6995]
sorry i miss this function very much.

possible to add video tracking by default tracking code?

http://blog.neumeier.org/2011/06/track-video-plays-for-html5-with-piwik/

**Comment by mattab** [comment]
Hi @Tobias-Conrad - thanks for the suggestion. I've also created an issue for Video Analytics: #7551

**Comment by Forsskieken** [comment]
Hi There,

Can I test this plugin? Or does is need to developped?

**Comment by mattab** [comment]
Note we've now also released [Video Analytics for Piwik]() as a [premium](https://piwik.org/faq/general/faq_22573/) plugin.

The [Media Analytics User Guide](https://piwik.org/docs/media-analytics/) and the [Media Analytics FAQ](https://piwik.org/faq/media-analytics/) cover how to get the most out of this plugin. The [Media Analytics developer guides](https://developer.piwik.org/guides/media-analytics) help you setting up  the tracking of your video and audio on your websites or apps.
