### ISSUE TITLE
Accessibility: reporting menu titles should read "Visitor menu" instead of "Visitor"

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7001]
The reporting menu looks like this:

- Visitor
    - Visitor Log (link)
    - ...
- ...

*Visitor* is not a link so when read out loud by screen readers it's confusing. In order to improve accessibility it should read "Visitor Menu" (when read out loud). The label of the menu however should not be changed.

**Comment by mattab** [comment]
refs #4167

**Comment by mnapoli** [comment]
Done in #7038
