### ISSUE TITLE
Accessibility: widget titles should read out loud as "Widget …"

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7007]
refs #4167

A screen reader will read widget titles out loud like "Visitor map". By having it read "Visitor map widget" it makes the content of the page clearer.

Widget titles shouldn't be changed: only the "off-screen" data (used by screen readers) should contain "widget".

**Comment by munro98** [comment]
#7007

**Comment by mnapoli** [comment]
Done in #7022
