### ISSUE TITLE
Accessibility: radio buttons read the label 3 times

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7008]
refs #4167

The screen reader has trouble with our custom radio buttons: the label was read 3 times (e.g. "No, No, radio button, No" or something like that).

**Comment by TheCrowsJoker** [comment]
We didnt find an easy fix for this issue and it also happened on other sites when tested indicating it could be a bug with the screen reader as opposed to the website. It does however wok with a simple html page containing only 2 radio buttons.

**Comment by tsteur** [comment]
As it is a very minor issue we will close it for now. Fixing it would most likely take a lot of time. If you see this issue and know what it causes and maybe even have a fix for it let us know.

**Comment by tassoman** [comment]
Can't reproduce this issue inside Settings Page inside admin UI using NVDA screen reader. Labels are correctly spelled.
