### ISSUE TITLE
The UI asset variables.less is not readable 

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#7016]
On master branch, I've just ran **./console core:upgrade** command but it dies with exception, also in web ui:

_An exception has been thrown during the rendering of a template ("The ui asset with 'href' = /var/www/piwik/plugins/Login/stylesheets/variables.less is not readable") in "@CoreUpdater/runUpdaterAndExit_welcome.twig" at line 5._

**Comment by sgiehl** [comment]
That was a temporary issue and is fixed with #7018
