### ISSUE TITLE
Infinite loop when using the DatabaseHandler logger  with DEBUG level

### ISSUE THREAD

**Issue by jon48** [piwik/piwik#7017]
Hello,

Configure your logging setting to the below:
```INI
[log]
log_writers[] = "database"
log_level = "DEBUG"
```

When trying to access Piwik front-end you will get a fatal error:
`Fatal error: Maximum function nesting level of '100' reached, aborting! in [...]\piwik\vendor\monolog\monolog\src\Monolog\Logger.php on line 441`

This seems to be due to the SQL statements being automatically logged at DEBUG level:  when the logger of type DatabaseHandler uses its `write` method, it calls the standard `Db::query` method which itself will try to log the log insertion statement, hence calling again the logging method and triggering an infinite loop.

Not sure what the best way to fix it (implementing a specific non-logged query method in the Db class, adding an extra parameter in the existing methods to prevent logging, putting in place a switch to stop/start logging..)?

Regards.
Jonathan

**Comment by mattab** [comment]
Thanks @jon48 for the report. maybe @mnapoli you have an idea about that one?

**Comment by mnapoli** [comment]
Hi @jon48 thanks for reporting it, I've implemented a fix to disable query logging when inside the database log handler.
