### ISSUE TITLE
Browser Widget Title not Found

### ISSUE THREAD

**Issue by munro98** [piwik/piwik#7019]
The bowser widget display the text "Widget not found " instead of the widget title.
![widgetnotfound](https://cloud.githubusercontent.com/assets/5344420/5747165/db822802-9c9a-11e4-843f-105956160a37.png)

**Comment by Globulopolis** [comment]
Delete widget and add it again. This is temporary solution for this issue.

**Comment by mattab** [comment]
Hi @munro98 Thanks for the report! 

 @sgiehl Maybe you could take a look? I think it regressed sometime in #3962

**Comment by sgiehl** [comment]
Maybe the widget has not been updated. Do you still have the broken widget on your dashboard?
If so it would be helpful if you could send me the database entry for that dashboard.

**Comment by mattab** [comment]
@munro98 reproduced it on fresh git master clone

@sgiehl on the demo and demo2 when I reset the dashboard layout to original layout, I can see the widget "widget not found" as well. Maybe it's a bug in core?
