### ISSUE TITLE
Synchronize GitHub labels and milestones in all repositories

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7020]
We would need a script to synchronize GitHub issues labels between all repositories.

**Comment by mattab** [comment]
and milestones, for example maybe we want to create these milestones in all repositories:
 * Current sprint
 * Short term 
 * Backlog

(except on piwik/piwik where we have a bit more granularity)

**Comment by quba** [comment]
We don't need short term milestone. Current sprint, backlog and no milestone should suffice.

**Comment by tsteur** [comment]
In the Piwik Mobile repositories I don't need/want those labels / milestones. If you do this please allow to define some excluded repositories

**Comment by mattab** [comment]
Maybe the sync could apply to all plugins repos (names starting with `plugin-`) and also a whitelist of repos such as `PiwikPRO/support` etc.

**Comment by mnapoli** [comment]
The repo is here: https://github.com/piwik/github-sync

Currently works for labels but not for milestones.

It allows to select repositories with wildcards, e.g. sync `piwik/piwik` labels to all `piwik/plugin-*` repositories. There is a confirmation for each modification too.

Feedback welcome, start to use it.

**Comment by mnapoli** [comment]
There is now support for milestones too, so it's ok to use for me. If you need something more please open an issue there (https://github.com/piwik/github-sync).

**Comment by mattab** [comment]
Looks great, let's test it next week!

**Comment by mattab** [comment]
fyi I've added it to the FAQ [What other free/libre software projects does the Piwik team create and maintain?](https://piwik.org/faq/general/faq_18850/)
