### ISSUE TITLE
Issue with setUserId - setting to null creates error in Url building when tracking

### ISSUE THREAD

**Issue by hobbysoldat** [piwik/piwik#7043]
We track our users with the users userId and are using the 

    _queueApiCall('setUserId', userId);

API call to track them. This works great, although we found a small problem. When a User logs out, we unset this property, by calling:

    _queueApiCall('setUserId', null);

This leads to problems when calling 

    _queueApiCall('trackEvent', type, action, title);

Because in this line in piwik.js:2919

    (configUserId.length ? '&uid=' + encodeWrapper(configUserId) : '') +

the configUserId.length call will fail because configUserId is null. We resolved this issue locally by just setting the user id to an empty string, but it was hard work finding what failed in the minified source code.

1) How should one unset the configUserId correctly if the user logs out?
2) In my opinion, the application should be robust enough to handle wrong values or fail when they are passed. I am not sure which way piwik is going here, but it would be nice if the current behavior would be replaced.

**Comment by hobbysoldat** [comment]
It seems like this problem is handled by typecasting values to String in other cases in the pwik.js source code.

**Comment by tsteur** [comment]
Thx for the report! Casting it to a string before accessing `.length`
