### ISSUE TITLE
Incorrect bounce rate reported?

### ISSUE THREAD

**Issue by olivierlambert** [piwik/piwik#7044]
Hi,

First, thanks for this excellent tool which is Piwik :)

I would like to report a strange behavior on the bounce rate. This is not a metric I display a lot, so I can't remember since which update it changes.

But for a time, it worked. Now I've got strange number. E.g: usally, I got 30%, but now it seems divided by 100 (0,03%).

I used a small segment on my website and done the count manually, which is 100 * (bounce_count / nb_visits), the same operation done in your [BounceRate.php](https://github.com/piwik/piwik/blob/abf6f8857e3c944446ff4137f1f5be78b8b0bbdc/plugins/Actions/Columns/Metrics/BounceRate.php). And I got the right number 60% and not the displayed number in my dashboard, 0,60%.

Note this number is also visible on your [Piwik Demo](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2014-09-04#/module=Dashboard&action=embeddedIndex&idSite=7&period=day&date=2014-09-04&idDashboard=1), by selecting Bounce Rate in the "Visits Over Time" panel and choosing "Bounce rate".

![bouncerate](https://cloud.githubusercontent.com/assets/1241401/5788398/484b8c6e-9e33-11e4-8356-97023c06ebfd.png)

Sorry if I miss something on my side!

**Comment by sgiehl** [comment]
That should already be fixed on master. See #6923

**Comment by hassanfarhad** [comment]
HI
do you know bounce rate(in Visitors-overview-Evolution over the period) what exactly means?
![piwik pic](https://cloud.githubusercontent.com/assets/13116885/9324237/ad49b00c-459d-11e5-9ae1-6fca9676e020.jpg)
