### ISSUE TITLE
auto-update: curl does not start to download file (core/Http.php [sendHttpRequestBy]) latest.zip with 0kb on disk

### ISSUE THREAD

**Issue by matzegebbe** [piwik/piwik#7050]
hey!

I had some trouble with the update function. 
the file download did not start and i got no response from the website anymore.
the file latest.zip was created but with the size of 0 kb.

so i changed the part where $method = 'curl' to a minimum and now it works.
maybe i had some trouble with the header options or something like that (proxy was not set!)... I use Debian 7.7 with apache. Maybe this helps others.

```php
....
else if ($method == 'curl') {
if (!self::isCurlEnabled()) {
// can be triggered in tests
throw new Exception("CURL is not enabled in php.ini, but is being used.");
}
$ch = @curl_init();
curl_setopt($ch, CURLOPT_URL,$aUrl);
curl_setopt($ch, CURLOPT_FILE, $file);
ob_start();
$response = curl_exec($ch);
ob_end_clean();
...
```

**Comment by tsteur** [comment]
Can you maybe add more of the original code step by step to see what the actual problem is? Otherwise it is hard for us to reproduce / fix it.

**Comment by mattab** [comment]
please reopen if you have more info
