### ISSUE TITLE
Wrong scaled graph for bounce rate

### ISSUE THREAD

**Issue by DaSchTour** [piwik/piwik#7053]
With 2.10.0 something with graph scaling was broken. Since 2.10.0 the bounce rate in percent is scaled to 1%,2%. It looks like the scale is to the number 1 and 2 while the bounce rate is for example 0,6. Because of this there is very low use of the graphs because nearly all percentage values are very flat because they only use half of the graph height.

**Comment by sgiehl** [comment]
fixed in #6923
