### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by lupa18** [piwik/piwik#7058]
Hi, 

I've installed piwik from DreamHost (version 2.2.2), but then appeared a red advice: "update to 2.10.0" so I did it. 

Now **I lost the "Admin" menu** (image1), and **severs configuration doesn't appear** (image 2). 

Image1: 
![piwik-admin-menu](https://cloud.githubusercontent.com/assets/463429/5839030/26381fa4-a16a-11e4-86a0-65189fddbf76.png)

Image2: 
![piwik-servers](https://cloud.githubusercontent.com/assets/463429/5839033/3068f084-a16a-11e4-9fc3-bafc4dfb9206.png)

When I go to themes section y saw some things changed. I tried to enable Zeitgeist and disabled but noting changed. 

Could you help me please? 
Thanks in advance

**Comment by tsteur** [comment]
For problem 1: see #6878 and http://piwik.org/faq/troubleshooting/faq_18485/ There are also many other issues about this. Most likely your webserver does not serve HTML files correct. In the next version it will be a plain link anyway and therefore fixed but you should still make sure to follow that FAQ

For problem 2: see #6497 most likely it is an encoding issue. Try for example this: https://github.com/piwik/piwik/issues/6497#issuecomment-60836702

I will close this issue as problem 1 will be solved in the next release anyway and problem 2 is handled in the other issue.
