### ISSUE TITLE
Execute log analytics tests on Travis

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7062]
See #7059 

I think we should run the log importer tests on travis automated even if it takes one job. To execute them it won't take long. Just executed them locally and getting this error:

```
..Fatal error: cannot automatically determine the log format using the first 100000 lines of the log file. 
Maybe try specifying the format with the --log-format-name command line argument.
```

We could maybe even move the log importer into another repository. Configure travis-yml with `sudo:true` etc. so execution should very fast. Maybe we could also run the tests on windows?

**Comment by mattab** [comment]
:+1: 

@diosmosis also wanted to move Log analytics script to a separate repo, maybe this would increase number of contributions by the community?

**Comment by mnapoli** [comment]
:+1: to move to another repository it would make sense

**Comment by mattab** [comment]
fyi: created issue #7163 to move the app to its own repository

**Comment by chungsm** [comment]
Followed your advice and used the new import_logs.py.
I have successfully imported the iis log with different IP addresses.
Thank you a lot.
BTW. Sorry for late reply.

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
