### ISSUE TITLE
Datatable Sort Column Icon should be next to the title

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7065]
See attachment. I think it would make more sense if the sort icon was closer to the title. This way it would be easier to identify by which column it is sorted...

![column_sort_icon_position_wrong](https://cloud.githubusercontent.com/assets/273120/5868374/4812afdc-a30d-11e4-936e-55d3a776a20c.png)

**Comment by mattab** [comment]
This was already fixed, probably in 3.0.0
