### ISSUE TITLE
email reports: cannot edit anymore if a address-list contains empty line

### ISSUE THREAD

**Issue by ekle** [piwik/piwik#7069]
if there is an empty line between two mail addresses, the report cannot be edited anymore.
firefox-console output:

    TypeError: reportParameters.additionalEmails.join is not a function
    $('#report_additional_emails').text(reportParameters.additionalEmails.join('\n')...

How to reproduce:
  # create an mail-report
  # add two receivers with a blank line between
  # save
  # try to edit the created report

**Comment by tsteur** [comment]
Thx for the report!
