### ISSUE TITLE
Improve Login Screen Layout

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7074]
See screenshot. Submit button is randomly on the right, the input fields are not really centered etc. I am not sure if this is a bug or on purpose but think there is room for improvement. Looking at old UI tests it seems to be on purpose like this.

![loginscreen_piwik](https://cloud.githubusercontent.com/assets/273120/5906814/919b6e92-a5ff-11e4-9d86-f96c71ed27db.png)

**Comment by mnapoli** [comment]
Fixed in #7102

**Comment by mattab** [comment]
Very nice guys!
