### ISSUE TITLE
Content type application/json breaks JSONP

### ISSUE THREAD

**Issue by everflux** [piwik/piwik#7075]
I get this error in the chrome console

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error) (20:52:42:320 | error, network)
  at https://example.com/?module=API&callback=jQuery19108562055646907538_1422301960073&method=VisitsSummary.get&idSite=1&call=&format=JSON&jsonp=callback&token_auth=deadbeef&date=2015-01-26&period=month&_=1422301960074
> 
```

This seems to be cause by a wrong mime type, owncloud has implemented an according change:
https://github.com/owncloud/core/commit/eecd4bd18e49ff7c3e93961574ed9b6f7adb3b1c referenced in this issue: https://github.com/owncloud/core/issues/7869

Steps to reproduce:
Use JSONP with host that has
```
X-Content-Type-Options: nosniff
```
header set.

**Comment by tsteur** [comment]
This is probably the related code that causes it: https://github.com/piwik/piwik/blob/2.11.0-b3/plugins/API/Renderer/Json.php#L72

**Comment by everflux** [comment]
I tested it with Chromium and got the error message above. It did not yet investiage with Firefox.

**Comment by everflux** [comment]
I just noticed that I pasted the wrong error message, sorry for any confusion. The internal server error seems to be caused by a different thing, the real message was the same as in the referenced owncloud bug: content type is not executable and therefore blocked.

**Comment by tsteur** [comment]
Thx! It should be fixed. Feel free to apply the patch if you want to test it. Please reopen in case you still experience the error afterwards. I tested it and get `application/json` when not using JSONP and `application/javascript` when using JSONP

**Comment by everflux** [comment]
Great, thank you. If I have some time to check it before the release I will post resuts.
