### ISSUE TITLE
As a user I want to configure purging of processed custom ranges

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7079]
Goal of this ticket is to introduce new config setting, which would prevent ArchivePurger from deleting complete range archives. There are some cases, when we would like to pre-process some ranges during archiving, as they cannot be processed in real time (this especially affects big instances).

**Comment by mgazdzik** [comment]
Thanks for feedback in previous PR, it makes sense. Could you please take a look at it now ?

**Comment by tsteur** [comment]
I presume this is done? Please reopen if not.
