### ISSUE TITLE
Bad transport method used in certain restricted environments.

### ISSUE THREAD

**Issue by Zmetta** [piwik/piwik#7083]
Automatic updates was failing with the following error:

 > Incompatible archive: PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

The End of Central Dir Record couldn't be found for the latest.zip file because the file, although it was being created, was always empty. The problem turned out to be incomplete logic in /piwik/core/Http.php function isCurlEnabled() misidentifying the transport method. 

`protected static function isCurlEnabled()
{
    return function_exists('curl_init');
}`

Both curl_init and curl_exec are required to complete a cURL request, but Piwik only checks for curl_init when selecting the transfer method to use. In some hosting environments, where curl_exec has been disabled, this will cause Piwik to incorrectly pass cURL as the transport method and show cURL as the Open URL option in the System Check. 

During the automatic update, Piwik attempts to use cURL to fetch latest.zip, touches the file, but is unable to curl_exec the data causing the above error. 

This simple patch in piwik/core/Http.php should fix the issue for environments with curl_exec disabled and cause sockets to be correctly passed as the transport method:

`protected static function isCurlEnabled()
{
    return (function_exists('curl_init') && function_exists('curl_exec'));
}`

**Comment by tsteur** [comment]
Thx for the report, I will add this check
