### ISSUE TITLE
Visit Overview (with graph) widget scroll to wrong position under circumstances

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7086]
When you have eg Visit Overview with graph and without graph on the dashboard (see screen), and click on a metric such as `6 users` in `Visits Overview with graph` it will either scroll to the very top of the page or to the graph of `Visits Overview (without graph)`.

![visit_overview_scroll_bug](https://cloud.githubusercontent.com/assets/273120/5927564/394695e4-a6d8-11e4-9c13-499f0cd96011.png)
`

**Comment by spacenate** [comment]
I was able to replicate this scrolling behavior, and also noticed that the wrong graph gets updated too! The "Visits Over Time" graph ends up displaying the new information, rather than the "Visit Overview (with graph)" graph.
