### ISSUE TITLE
Improve the look of our data tables and of our report pages in general

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7090]
I'm getting a bit distracted / annoyed by our alternate color in datatables (`grey / white / grey / white`). The contrast is high and the grey & white color are both used in other UI elements so that in my mind everything looks "loose". It is sometimes hard to see what belongs together and what not. It reminds me rather of a circus than anything else. See eg. attached screen:

![datatables_look](https://cloud.githubusercontent.com/assets/273120/5929009/bef3b2c4-a6e4-11e4-9ab1-534a4ba2eb89.png)

I just played a bit around and by removing the alternate color and I think it looks already much cleaner IMO. 

![datatables_different_background](https://cloud.githubusercontent.com/assets/273120/5929017/cc94e330-a6e4-11e4-8b03-f405263c9087.png)

Even the headlines and controls are much easier to identify etc. But it is no longer as easy possible to distinguish between the rows (bad for UX). To solve this we could maybe highlight the current row on hover and we could use a slight border below each row. Alternatively we could maybe not alternate between `grey / white` but between `grey / light grey` or so... I'm not a designer! On the other side I think it is even hard right now to distinguish between the rows as the white is also the background color and because of the high contrast of `white / grey with blue link color` in Actions => Pages. 

**If anyone has a nice idea how to make it nicer please comment. Also maybe some people like the current way then please comment as well** 

Maybe we could even find a solution that also works for other pages such as "Devices Detection" and "System Check" which both already use a similar approach. It could be nice to make it consistent.

![device_detection](https://cloud.githubusercontent.com/assets/273120/5929241/d34e524a-a6e6-11e4-8ffa-bdad7eec9054.png)

![system_check](https://cloud.githubusercontent.com/assets/273120/5929246/e260f954-a6e6-11e4-8d88-9da15ffea16d.png)

**Comment by Glisse1** [comment]
for me alternate colors make sense in a scenario of a blog post when ppl comment and alternate color makes it easy to distinguish different commentators. In piwik alternate colors in tables equals for me with unnecessary clutter and distraction.. plus it hurts my eyes to have several tens of rows each with alternate color in a single view on-screen (on blog comments there are just 2-3 such comments, not tens).. so yes, solid block for each table is way cleaner

**Comment by mattab** [comment]
Nice suggestion, but let's wait few weeks as we are working on new designs with Left Menu, better admin area, etc. so we will revisit this when we get the new mockup designs.

**Comment by tsteur** [comment]
The left menu will most likely take a couple of months, or not? And most likely the left menu won't change the look of the datatables etc, will it? If you don't want to change it ok but think the current look definitely needs to be changed and can be done independently of the left menu. At least exploring whether there's a quick fix that would make it better.

**Comment by mattab** [comment]
Adding `Major` tag so we don't forget. Waiting for feedback from Rafal. 

If you reading this have some opinion or design skills please comment :)

**Comment by lemu** [comment]
"The contrast is high and the grey & white color are both used in other UI elements so that in my mind everything looks "loose". It is sometimes hard to see what belongs together and what not."

I'm gonna make an argument that it looks loose, because you did't implement our design in 100%. It's something that Matt was strongly against. We wanted to encapsulate everything in tables, as on the dashboard page - without that it just looks muddled. This is how we envisioned subpages.

![refferers](https://cloud.githubusercontent.com/assets/590637/6130076/29146406-b143-11e4-93ae-fbffdd261471.jpg)

As for the zebra tables it was something that you've used and is very helpful for finding a row value in a long table. I would advise not to remove it, maybe lighten the background a little bit, or make it a setting. This is how it would look like more or less...

![actions-pages](https://cloud.githubusercontent.com/assets/590637/6130250/455ef080-b144-11e4-88b6-c659ce05e947.jpg)

**Comment by tsteur** [comment]
Personally, I don't like the boxes so much either and would rather not want to have them outside of the dashboard area. It looks a bit "heavy" and "bloated". Maybe a "lighter" / "cleaner" version of it would work when having a left menu. Think some apps or OS like iOS 7/8 show that it should be possible to abandon some "lines".

Also I think the alternate color white/grey (zebra tables) still looks a bit muddled even encapsulated and it is for my eyes (or with my display) sometimes often hard to identify which values belong to which row. Maybe using another grey for the white background would help a bit as you mentioned.

**Comment by mattab** [comment]
We need a better / flatter / simpler table design for 2.14.0 (or at latest for 3.0.0).

Suggested requirements:

 * [ ] no zebra background color: all rows have white background
 * [ ] almost no border, and border are very light
 * header row: 
  * [ ] have a light background color to differentiate it from the data rows
  * [ ] make the labels vertically aligned middle
 * [ ] on hover on a row, apply light background color to this row
 * [ ] on hover on a column, apply light background color to this col
 * [ ] a flatter icon will be needed for: 
![plus](https://cloud.githubusercontent.com/assets/466765/8123584/6d961998-1120-11e5-9ccb-5e57a827d3c5.png)
 * [ ] make metrics right aligned #4789

**Comment by tsteur** [comment]
I reckon we need to contact designers re an icon? That's so far my understanding after #7618 .

I looked for some icons online but didn't find quickly enough something that would fit and can be used re the license.

**Comment by mattab** [comment]
Regarding the icon maybe such simple icon (font awesome) would work: http://fortawesome.github.io/Font-Awesome/icon/plus-square-o/ 

Hi @lemu do you already maybe have a flat icon to replace https://cloud.githubusercontent.com/assets/466765/8123584/6d961998-1120-11e5-9ccb-5e57a827d3c5.png ?

**Comment by tsteur** [comment]
I was looking for such icon but didn't find any apart from the same as in FontAwesome
