### ISSUE TITLE
It is hard to see which menu item is currently selected

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7093]
See attached screenshot. In this case "Custom Variables" is selected. It always depends on the screen how good it is to see. On my screen it is hardly possible.

![menu_item_selected](https://cloud.githubusercontent.com/assets/273120/5929820/befb116a-a6ec-11e4-89f9-581b8478745d.png)

**Comment by gaumondp** [comment]
I agree with most of your recent UX suggestion but this one beats them all.

**Comment by tsteur** [comment]
I worked on two versions to improve this. One is making the active link darker (black) and the other menu items lighter. It might be a bit dangerous that the light item color is too light and people can't see it anymore:

![menu_new](https://cloud.githubusercontent.com/assets/273120/5990356/61e0cca4-aa11-11e4-9978-40341dce44d7.png)

![menu_new_admin](https://cloud.githubusercontent.com/assets/273120/5990357/67c27730-aa11-11e4-9491-ff3698aba311.png)

Than I tried to just replace the active link color with the brand color which is by default the Piwik red:

![menu_new_2](https://cloud.githubusercontent.com/assets/273120/5990358/6f2efb24-aa11-11e4-8934-f51bb058bcbe.png)

![menu_new_2_admin](https://cloud.githubusercontent.com/assets/273120/5990360/836fc280-aa11-11e4-843a-c0645edbfbad.png)

I didn't have any other ideas so far. I'm not a designer :) Bold doesn't work as it would be too bold and the font doesn't allow us to set eg `font-weight: 600`. An underline similar to the main reporting menu (red) doesn't really work either.

If anyone has other ideas please comment

**Comment by mattab** [comment]
The first version looks almost good, but maybe the text has not enough contrast indeed. Maybe a bit darker grey would work... Related to

**Comment by tsteur** [comment]
If we make it darker again in the first version then the contrast between the active / highlighted and the other menu items is not high enough...

Displaying the active link in red would be way more clear and not have any contrast problems.

**Comment by lemu** [comment]
What about something like that?
![screenshot 2015-02-10 17 38 09](https://cloud.githubusercontent.com/assets/590637/6131402/db828ae8-b14b-11e4-89d9-3683f67666e9.png)
![screenshot 2015-02-10 17 39 00](https://cloud.githubusercontent.com/assets/590637/6131401/db80b9a2-b14b-11e4-8970-de7f33f55ca1.png)

**Comment by tsteur** [comment]
I don't like the underline in the reporting menu. Wrote that in an earlier comment as I tried it as well. BUT It looks good in the left menu! So if we have a left menu in the future it might be all good, at least for me :) :+1:

**Comment by mattab** [comment]
Yes it looks good in Left menu :+1: 

(we may make the left menu the default menu in Piwik in #7169 )

**Comment by tassoman** [comment]
Hello for accessibility purpose, contrast between foreground and background colors should have enough amount. 

http://webaim.org/resources/contrastchecker/

**Comment by jdeyla** [comment]
I see no issu in menu colors and accessibility, except for some other contrast. 

Light blue of links (#4183C4) is too light, a little change in #376FA7 would be ok.
Blue on light blue (like in message "zen mode activated") is not readable. 
Grey menu voices #666666 on #F2F2F2, are borderline but good.
My suggestion is to avoid this tone-sur-tone

**Comment by mattab** [comment]
This UX issue will be fixed by the new redesign in: #7589

**Comment by tsteur** [comment]
Can we move it to "mid term" or "long term" and instead define a checkbox / follow up task to check this in #7589? Those kinda issues otherwise pollute the milestone and one always reads and looks it over and over again

**Comment by mattab** [comment]
Sure, will be done in #7589
