### ISSUE TITLE
When development mode is enabled, add a new language that shows raw translation id

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7094]
The language could be called "Development", or "Raw" or "TranslationId" or something else.

When this language is selected, nothing will be actually translated. Instead the default translation ID will be used see screenshot. This can be useful for Developers, Translators, ... as it is easier to find a translation key than doing a huge reverse search.

Eg developers currently have to use the translation ID to remove or rename a menu item. It can be hard to find the right one to use. This makes it easier that way. It could be also used to quickly check whether one has created translation IDs for everything or whether one forgot something etc. I'm sure there are more advantages.

![raw_translations](https://cloud.githubusercontent.com/assets/273120/5930398/e87af22e-a6f3-11e4-9aa1-4dce806e4083.png)

**Comment by mattab** [comment]
Nice idea!

**Comment by mnapoli** [comment]
PR: #7156
