### ISSUE TITLE
Blocked by client in Opera

### ISSUE THREAD

**Issue by pyrsmk** [piwik/piwik#7098]
Hi,

I'm facing a strange bug with Opera. The request to `piwik.js` is blocked by the client. I didn't touch anything to the snippet and it works under all other browsers. Maybe it's the asynchroneous request which blocks? Or maybe the `//mywebsite.com/piwik/` scheme-less address?

**Comment by tsteur** [comment]
Which Opera version and which OS?

Just to be sure: Is there maybe an Ad blocker or something else installed?

**Comment by pyrsmk** [comment]
Ahah! Thanks, I forgot that Ghostery blocks piwik too...
