### ISSUE TITLE
1st and 3rd party cookie issues

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7100]
What i want to do?
I'm using piwik on many intranet sites, so i would like to use 3rd party cookie, that the visit is always the same accross the websites. This is currently easy to achieve and works.

But as soon as you would like to track e.g. goals on the backend it will be a problem, since the backend  wont get the visitorId from the 3rd party cookie.

Only solution: use for 1st and 3rd party cookie the same visitorId.

If my thoughts gone right so far, the new userId feature would also benefit from it, since its only one visit the userId will be available accross all websites if it was set on at least one website.
(there are intranet wesites with a userId and some without)

**Comment by tsteur** [comment]
I haven't used 3rd party cookies so far therefore I can't say so much. I'd assume they are already both the same. Can you maybe to something like `Piwik.getTracker(var url = '/', var idSite = 2).getVisitorId()`?

When talking about tracking goals on the backend you mean in your backend right? Not the Piwik backend? Do you access the 1st party cookie there to get the visitorId?

**Comment by ThaDafinser** [comment]
@tsteur yes i'm talking about a "custom/own" backend. I can only access the 1st party cookie, since by security (and thats good) you never receive 3rd party cookies.

But yes AFAIK the cookie differ. Backend goals were always tracked as a new visitor. Multiple goals from the same user of course as the same visitor.

**Comment by tsteur** [comment]
sure, you can't access 3rd party cookies on your own backend. I was wondering if you could get the 3rd party visitor id via the above mentioned JS method, then use this value to set a 1st party cookie. Might be a solution/hack until it is fixed. I'm not sure if the current behaviour is like this by design maybe ping @mattab

**Comment by ThaDafinser** [comment]
If i have it correctly in my mind its by design.

The reason is simple: the 3rd party cookie is set from website #1. When now a user first visit website #2 the 3rd party cookie is taken and the 1st party cookie will get freshly generated.

**Comment by mattab** [comment]
Hi @ThaDafinser if you think there is a bug  or something we could improve in Piwik, could you please describe the steps to reproduce / describe the feature or so?

**Comment by mattab** [comment]
@ThaDafinser please reopen if you can clarify the issue, or create a new one with steps to reproduce etc. thanks
