### ISSUE TITLE
whois.com rate limit

### ISSUE THREAD

**Issue by mrjoops** [piwik/piwik#7103]
As you may know, many free webservices are rate-limited, and whois.com is no different.
Actually the free limit is set to 100 requests a day.
In Piwik, when I look at my dashboard and then click on parameters, I already sent 3 requests to whois.com.
Here are some ideas for future enhancements:
- cache responses in database ;
- provide a way to specify an alternate whois provider.

**Comment by tsteur** [comment]
Let's cache the `SEO.getRank` data using our Lazy cache: https://github.com/piwik/piwik/blob/2.11.0-b3/plugins/SEO/API.php#L41 

There shouldn't be many changes in the output so we could cache it for eg 6 hours per URL to not ending up in exceeding the limit if users manage multiple sites

**Comment by tsteur** [comment]
> provide a way to specify an alternate whois provider
This could be probably done via a plugin if someone wants to do it. Maybe create another issue for it?

**Comment by tsteur** [comment]
Rank will be cached for 6 hours now and I created another issue re alternate whois provider
