### ISSUE TITLE
Cannot upload BIG Bustom Logo

### ISSUE THREAD

**Issue by Setitch** [piwik/piwik#7108]
In scripts there is fixed time of 1 second for uploading custom logo. Also when i changed the time to check if it can upload that file i got error 500. (Probably 1.5mb image of 2000x2000 pixels required too much memory).

I think it should WAIT for ajax call with upload file to finish instead of using fixed time for waiting. Also there should be (if possible) used Image Magic library instead of GD2 (or for big images without Imagick, nice error should be returned).

**Comment by tsteur** [comment]
Thx for the report!
