### ISSUE TITLE
add Asian search engines

### ISSUE THREAD

**Issue by endrepalinkas** [piwik/piwik#7111]
Hi,

Would be nice to have these Search Engines added, as they show up a lot in Referrer Websites. I included referrer URL examples, with 'mykeyword' and 'my long keyword' as keywords.

- [x] Haosou
http://www.haosou.com/s?&ie=utf-8&src=se7_toolbar&q=mykeyword
http://www.haosou.com/s?ie=utf-8&src=hao_search&shb=1&q=my+long+keyword
http://www.haosou.com/s?q=mykeyword&pn=43&j=0&ls=0&src=srp_paging&fr=recom-nlp-formal&psid=499c259433c9199bf1ea57f38e97e07b

- [x] Zxuso
http://www.zxuso.com/ju/?wd=my+long+keyword
http://www.zxuso.com/ri/?wd=mykeyword

- [x] sm.cn
http://m.sp.sm.cn/s?q=mykeyword&uc_param_str=dnntnwvepffrgibijbprsv&from=ucdh
http://m.sp.sm.cn/s?q=mykeyword&uc_param_str=dnntnwvepffrgibijbprsv&from=ucframe
http://m.sp.sm.cn/s?q=mykeyword&uc_param_str=dnntnwvepffrgibijbpr&from=ucframe

These two engines you already have, but Mobile searches aren't sorted under Search Engines.

- [x] Sogou Mobile:
http://m.sogou.com/web/searchList.jsp?keyword=my+long+keyword&uID=SLrzj05ioVhLcLgY&pid=sogou-clse-2996962656838a97&dp=1&de=1&e=1427&v=5&w=1282&mcv=51&pcl=102,3162&sed=1&ml=15&sct=30
http://m.sogou.com/web/searchList.jsp?pid=sogou-clse-2996962656838a97&e=1427&g_f=123&keyword=mykeyword

- [x] Baidu Mobile:
http://m.baidu.com/from=1099a/pu=sz@1320_480,cuid@4CBB82F68BCEB3DB96F100782908E0E5EB8C52FE1OROSQPBHPC,cua@1125_2001_iphone_6.0.6.0_0,cut@iPhone7%2C1_8.1.1,osname@baiduboxapp,ctv@1,cfrom@1099a,csrc@app_box_txt/s?tn=zbios&word=my+long+keyword&sa=cr
http://m.baidu.com/from=1000953b/s?word=mykeyword&ts=7926714&t_kt=165&sa=ihr_1&ss=001
http://m.baidu.com/s?from=2001a&bd_page_type=1&word=mykeyword

**Comment by sgiehl** [comment]
Thanks for your report. I'll have look at that

**Comment by endrepalinkas** [comment]
Hi,

Thank you. One more for Baidu if you don't mind:
http://www.baidu.co.th/s?wd=mykeyword&tn=GSE_THPSpcfastermini_1it5cd8x&ie=utf-8&req_prod=thai
http://www.baidu.co.th/s?tn=GSE_607t1_zgyznn3a&ie=utf-8&wd=my+keyword&req_prod=thai&input_t=1271
http://www.baidu.co.th/s?wd=my%20long%20keyword&tn=GSE_607t1_zgyznn3a&cl=3&ie=utf-8&oq=&req_prod=thai&st=8&input_t=715&rsv_hisdisp=2_1_0&showTop=false

**Comment by sgiehl** [comment]
done.
