### ISSUE TITLE
"Diagnostic" section in admin panel is gone

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7116]
I'm not sure if this is meant to be like this or not, but the "Diagnostic" section in the settings is not visible anymore.

I've had a look both in the personal and general settings.

Should the section be restored? If so, in general settings right?

**Comment by tsteur** [comment]
It's still visible on my installation. Only to SuperUsers by default though which is correct. Otherwise the Installation plugin might be disabled?

**Comment by mnapoli** [comment]
OK thanks that must be something not right on my install. The installation plugin is activated though.
