### ISSUE TITLE
Flattening Referrers.getWebsites is very slow and needs lot of memory

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7120]
Maybe the same is valid for other reports. I haven't tried many. `Referrers.getKeywords` has the same problem.

Eg http://demo.piwik.org/index.php?date=2015-01-04,2015-02-02&module=Referrers&action=getWebsites&widget=1&idSite=1&period=range&flat=1

results in `Allowed memory size exhausted`

Opening http://demo.piwik.org/index.php?date=yesterday&module=Referrers&action=getWebsites&widget=1&idSite=1&period=day&flat=1 results sometimes in an "Internal server error" and sometimes in `Allowed memory size exhausted`

Maybe there are already similar issues in this case simply close it!

**Comment by mattab** [comment]
There are no similar issue, besides the related memory usage of yearly archives #6846

**Comment by tsteur** [comment]
Might be fixed by #7336

**Comment by mattab** [comment]
Very likely yes. I'll push a beta to demo now so we can confirm it is!

**Comment by mattab** [comment]
Wow, those reports now load in a few milliseconds... that's impressive, and fixed :+1:
