### ISSUE TITLE
Allow usernames with 2 letters

### ISSUE THREAD

**Issue by Jibec** [piwik/piwik#7121]
Hello,

I have YunoHost on a server with username of two letters. Unfortunatly, Piwiki looks like to ask for at least 3 letters username and I get this error : 
admin@yunohost:~$ sudo /var/www/piwik/console loginldap:synchronize-users --login=jb
 Synchronizing 'jb'... failed!

--------------------------------------------------------------------------------

Synchronized 0 users! 

--------------------------------------------------------------------------------

Could not synchronize the following users in LDAP:
 jb The login must be between 3 and 100 characters long and contain only letters, numbers, or the characters '_' or '-' or '.' or '@' or '+'

Is there anyway to change this just for my instance of Piwik or for long term ?
Is there a technical reason for 3 caracters ?

Originial issue on github : https://github.com/maniackcrudelis/piwik_ynh/issues/4

**Comment by tsteur** [comment]
Related to #7114
