### ISSUE TITLE
warning on settings page about EOL PHP version

### ISSUE THREAD

**Issue by supervisitor** [piwik/piwik#7122]
since update to 2.10.0 I have this warning message on all settings pages. (could be starting to shown before version 2.10.0, but I don't see, because I do not use the adminstration pages all the time.) the original message:
<pre>Warning
Piwik will stop supporting this PHP version in May 2015. Upgrade your PHP version
before it's too late! The PHP version 5.3 you are using has reached its End of Life
(EOL). You are strongly urged to upgrade to a current version, as using this version
may expose you to security vulnerabilities and bugs that have been fixed in more
recent versions of PHP.</pre>

my server setup:
 - PHP Version 5.5.18
 - MySQL Version 5.6.21

on the SecurityInfo (plugin version 1.0.5) page, the reported versions are:
 - PHP	5.3.28-nmm1
 - Piwik	2.10.0

the reportet version 5.3, I do update with 5.5 at the beginning of 2014. since there piwik should know that I use a new version of php?!

the funny page: piwik > adminstration > diagnostic > system check
on top, there is the warning about the EOL version of PHP, shown above.
first row of report: "PHP version >= 5.3.3" followed by the "ok" sign.
so, in some cases the core knows the right version?

I check if something will change when I disable the SecurityInfo plugin, but it don't.

**Comment by sgiehl** [comment]
Have you tried to upload a simple info.php showing phpinfo(); Maybe your apache/nginx still uses an older version.
Piwik UI always uses the same version. And PHP 5.5.28 is newer than 5.3.3 so the check sign in the settings is correct.

**Comment by supervisitor** [comment]
sorry I forgot: phpinfo() will show the same, correct, true version of PHP: 5.5.18

**Comment by tsteur** [comment]
Is this maybe a multi server environment? Are there maybe different PHP versions installed? 

Did you check phpinfo on the command line? Did you check that within the Piwik directory and opened it via that URL? 

I couldn't find an entry in the PHP changelog to such an issue

**Comment by mattab** [comment]
Hi @supervisitor can you please contact your webhost or admin and ask them? likely it's a environment/infrastructure issue.

**Comment by supervisitor** [comment]
Hi & sorry for delay.
Yes, it is a multi server environment and yes, there are more than one PHP versions possible. But PHP 5.5 is the default and loaded as module, all other PHP versions are only via CGI/FPM useable.
I do one more, I insert "phpinfo(INFO_GENERAL);" in index.php and some other files to seewhich version the file use. And at all PHP banners I see 5.5.18. But in the settings section, there is still the banner with warning about the EOL PHP version?!

**Comment by supervisitor** [comment]
hmmm... is a little be funny!

we change some on the piwik setup and move the installation to a dedicated single machine. no other php is possible now! and now we learn: piwik is not PHP 5.5 ready!

this we see on the old machine:
- infophp shows PHP 5.5, but piwik still use 5.3?
- PHP 5.5 is loaded by default (as httpd module)
- no environment configuration to use 5.3, this we double-check
- all the time, the warning appears at settings section

now we move the installation to some other multi server environments, all are working with a similar configuration, the only difference is: PHP version loaded by httpd module.
 - httpd module: PHP 5.2 / via cgi-fpm possilbe: PHP 5.2, 5.3, 5.4, 5.5, 5.6
=> piwik is working, warning showing at settings section, piwik system check: ok, PHP > 5.3.3, phpinfo reports: PHP 5.2
 - httpd module: PHP 5.3 / via cgi-fpm possilbe: PHP 5.2, 5.3, 5.4, 5.5, 5.6
=> piwik is working, warning showing at settings section, piwik system check: ok, PHP > 5.3.3, phpinfo reports: PHP 5.3
 - httpd module: PHP 5.4 / via cgi-fpm possilbe: PHP 5.2, 5.3, 5.4, 5.5, 5.6
=> piwik is working, warning showing at settings section, piwik system check: ok, PHP > 5.3.3, phpinfo reports: PHP 5.4
 - httpd module: PHP 5.5 / via cgi-fpm possilbe: PHP 5.2, 5.3, 5.4, 5.5, 5.6
=> piwik is working, warning showing at settings section, piwik system check: ok, PHP > 5.3.3, phpinfo reports: PHP 5.5
 - httpd module: PHP 5.6 / via cgi-fpm possilbe: PHP 5.2, 5.3, 5.4, 5.5, 5.6
=> piwik is working, warning showing at settings section, piwik system check: ok, PHP > 5.3.3, phpinfo reports: PHP 5.6

our result: we don't know why piwik is still using PHP 5.3 via cgi-fpm and why piwik use the httpd module only for phpinfo, but since we move it to a standard machine (5.5 default module, all other via cgi) and bind it explicit to 5.4 the warning is no more showing in the settings section and all is working fine.
But we are all convinced it could be not on the environment. Otherwise we would have many similar problems with other products, which we do not have.
