### ISSUE TITLE
simplify archiving logic by implementing archiving layer as caching backend

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#7126]
The logic that uses and manages archive tables should be simple. If an archive exists, use it. If it doesn't exist, get the report/metric data and cache it in an archive. This is what the logic should be like, but the reality is that the archiving code is a complex mess of object spaghetti.

Since the archive tables function essentially as a cache for report & metric data, we could simplify the code greatly by making the archive tables a Piwik Cache backend.

The resulting Archive.php code might look like:

```
function get($idSite, $period, $date, ...) {
    $cache = new ArchiveTableCache();
    if (!$cache->contains($idSite, $period, $date)) {
        $data = ...

        $cache->save($idSite, $period, $date, $data);
    }

    return $cache->fetch($idSite, $period, $date);
}
```

Possible problems:

1. The caching layer would have to support fetching multiple pieces of data at once.
2. The contains()/fetch() calls have to merged somehow. It would be inefficient to issue two almost identical queries for this.

**Comment by tsteur** [comment]
Everything that makes this part easier and understandable is greatly appreciated :+1: 

One more use case: If a cache entry is marked as to be invalidated it will be still valid until there is a new archive which shouldn't be a big problem to implement.

Challenge as you said performance but that sounds doable.

**Comment by mnapoli** [comment]
:+1:

**Comment by mattab** [comment]
seems most agree with this nice idea, maybe we can close RFC and create follow up issue with new cache backend?

**Comment by diosmosis** [comment]
I think it's a non-trivial, I doubt it can be done by 2.11.

**Comment by mattab** [comment]
Moved to 2.12.0, where we can close this RFC and create follow up issue eg. in `Short term`.

**Comment by diosmosis** [comment]
Can't you just move this ticket to Short term and remove 'RFC'?

**Comment by mattab** [comment]
done
