### ISSUE TITLE
make log importing much more flexible by allowing re-ordering of log format fields

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#7135]
Some log file formats are only slightly different from the currently recognized formats. They could, for example, have a couple extra fields or have fields in different order. In these cases, users have to build custom regexes, which unless the user is aware of how the importer works internally, will be very non-trivial.

The log importer should be modified to make these use cases simple for users. Options that allow re-ordering fields w/o knowing the exact format or changing the regex for specific fields would make the log importer much easier to use.

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
