### ISSUE TITLE
"visits over time"-chart

### ISSUE THREAD

**Issue by michaelwowro** [piwik/piwik#7136]
I found a strange behaviour in the calcualtion:
I manually counted the actions in "detailed visitor log" on today:
* 42 "normal" page views (without icon)
* 22 outlinks (with the outlink icon)
* 22 site search (with the loupe icon)

In the "visits over time" chart I hovered over today and got that figures:
* 42 Pageviews
* 22 Outlinks
* 16 Searches

Two issues about that:
1.) My intuition says that the 42 "normal" page views and 22 site search in "detailed visitor log" should sum up to 64 Pageviews in the "visits over time" chart.
2.) the difference between 22 Searches in "detailed visitor log" and 16 Searches in "visits over time". When I looked closer in the "detailed visitor log", I found, that 3 searches were executed twice. Seems those doesn't count at all in "visits over time".

**Comment by mattab** [comment]
> 1.) My intuition says that the 42 "normal" page views and 22 site search in "detailed visitor log" should sum up to 64 Pageviews in the "visits over time" chart.

Pageviews in the chart does not include site searches requests as they are not considered normal pageviews (it's maybe not clear, not sure how we could improve this?)

> 2.) the difference between 22 Searches in "detailed visitor log" and 16 Searches in "visits over time". When I looked closer in the "detailed visitor log", I found, that 3 searches were executed twice. Seems those doesn't count at all in "visits over time".

the count of Searches will dedupe the visits who have done twice or more the same search. so if each time a user searched twice the keyword it will count as one. Maybe we want to change this, we can change https://github.com/piwik/piwik/blob/2.11.0-b3/plugins/Actions/Archiver.php#L469 INDEX_NB_VISITS -> INDEX_PAGE_NB_HITS

**Comment by michaelwowro** [comment]
thanks for the duplicate fixture.
Anyhow, for me, searches are just a subset of pageviews, because a search is just another pageview. Can you tell me, where I can sum up both figures to something like "general pageview" or something like taht?
