### ISSUE TITLE
Only display device type with a value

### ISSUE THREAD

**Issue by bahooha** [piwik/piwik#7140]
In the 'Device type' widget as well as under 'Visitors > Devices' a number of possible device types are listed (Desktop, Car browser, Smart display, Camera, Tv, Console, Smartphone, Tablet, Feature phone).
I don't always get visitors that view my website on a car browser and some other types are not that frequent as well for most Piwik users, I guess.

Maybe it would be possible to only display types that have a value for the number of visitors?

**Comment by sgiehl** [comment]
It was on purpose to display always all types.
That way it is always possible to show the row evolution. Otherwise you wouldn't be able to show the evolution for a type that wasn't used in the current period.
(And of course you would not see which types piwik is able to detect)

**Comment by sgiehl** [comment]
The only option we could maybe provide is to show the 'exclude low population' option. But enabling that would hide types with low population aswell.

**Comment by bahooha** [comment]
Many thanks for your reply!
If there are no stats (from all-time) for a certain device type, then I guess there is no row evolution either?

If the exclude option would be implemented, what would be the threshold for the exclude, when is something defined as low population? Would it be possible to make that a user setting/preference?

Maybe it could be a possibility to make an option to hide certain types in the dashboard, but show all types under 'Visitors > Devices'?

Ofcourse I can't speak for others, but for the sites I monitor, I have never seen any visitors that use a car browser or a camera. Opinions? 
Also I wonder why a smart display in the list as well, isn't that either a tablet or just a all-in-one desktop?

Again, many thanks for looking into this!

**Comment by bahooha** [comment]
This feature has been implemented in v3.0.3

Thank you very much!
