### ISSUE TITLE
Wrong username and password

### ISSUE THREAD

**Issue by prathi22** [piwik/piwik#7142]
When I am trying to login piwik from localhost and giving the proper email id and password, I am getting an error like "Wrong username and password". What is the problem?

**Comment by ThaDafinser** [comment]
@prathi22 are you sure that your credentials are correct? What you mean with localhost? You got a production and development env?

**Comment by mattab** [comment]
Hi @prathi22 can you please try reset your password - does it work then? if you still have problem pls reopen this issue
