### ISSUE TITLE
UI tests fail with phantomjs has crashed

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7147]
The goal of this issue is to investigate and solve the Segmentation fault in phantomjs. 

UI tests CI job sometime fail with:

```
[...]
✓ should show the updated segment after page reload (28791ms)

PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/4fc62382-9b22-a9c5-2c28353d-0e63dcb7.dmp

/home/travis/build/piwik/piwik/tests/travis/travis.sh: line 76: 16423 Segmentation fault phantomjs ../lib/screenshot-testing/run-tests.js --store-in-ui-tests-repo --persist-fixture-data --assume-artifacts --core
```

for example this job: https://travis-ci.org/piwik/piwik/jobs/49804130

(in the same build the 5.3.3 job failed with DB connection errors... maybe the build server is unstable at times)

**Comment by mattab** [comment]
Recently getting those crashes more and more often. 

Maybe it would help to upgrade to newer version of phantomjs if one is available?

**Comment by mnapoli** [comment]
Getting segmentation faults with phantomjs lately, we'll see if it lasts.

**Comment by tsteur** [comment]
Same here on my branch https://travis-ci.org/piwik/piwik/jobs/65056870 . That's the UI test for my branch but it works in the PR build that runs with master

**Comment by mattab** [comment]
btw: we're not the only users to experience phantomjs segfaults and crashes: https://github.com/ariya/phantomjs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+crash+1.9.8 

Travis is currently using 1.9.8 version of phantomjs. have we considered upgrading to 2.0.0, if we're lucky it may help with the crash/seg fault?

**Comment by mattab** [comment]
not seeing this problem anymore
