### ISSUE TITLE
The SEO widget should be displayed even if when a http service calls fail

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7153]
When building the SEO widget, we collect metrics from various web services eg. Google, microsoft, whois, etc. In some cases the HTTP calls can fail. For example Whois may be rate limited to 100 requests per hour. 

Possible steps of this issue
 1.  investigate what possible limits are, check whether we can avoid them
 2. check that errors are logged (as a warning maybe?) 
 3. that the SEO widget is displayed with the failed value as `-` or `Network error` (and other values displayed correctly).

follows up https://github.com/piwik/piwik/issues/7103

**Comment by tsteur** [comment]
So what are the request limits for each service?
