### ISSUE TITLE
Developer.piwik.org - New blog post to announce it to the community

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7154]
The goal of this issue is to post a blog post to announce to the community the launch of the developer.piwik.org website.

Draft blog post at https://piwik.org/wp-admin/post.php?post=16544&action=edit

Follows up  #4456

**Comment by gaumondp** [comment]
404 in footer of http://developer.piwik.org/ under "jobs"

2015-02-08 20:04 GMT-05:00 Matthieu Aubry <notifications@github.com>:

**Comment by mattab** [comment]
Thanks for the report, I've added a redirect and it works now!

**Comment by mattab** [comment]
Blog post has been published! 


[Piwik Developer Guides: helping you make the most of the Piwik platform](https://piwik.org/blog/2015/04/piwik-developer-guides-helping-you-make-the-most-of-the-piwik-platform/)

Congrats everyone involved in this project @diosmosis @tsteur @mnapoli it's been a huge work and we can be proud of it.  (We will keep working on the guides in the future to keep them useful and up-to-date.)
