### ISSUE TITLE
Email reports not working when email SMTP server host contains a space

### ISSUE THREAD

**Issue by F0nix** [piwik/piwik#7157]
Gets this error using .info TLD

An error occured while sending 'HTML Email Report - 3.2015-02-07.11.en.html' to user@gmail.com. Error was ''mail.xxx.info ' appears to be a DNS hostname but cannot match TLD against known list, 'mail.xxx.info ' does not appear to be a valid URI hostname, 'mail.digianalytics.info ' does not appear to be a valid local network name'

**Comment by ThaDafinser** [comment]
The error comes from here https://github.com/piwik/piwik/blob/5d799ee1a434ce97921b412bc34568b7241870ea/libs/Zend/Validate/Hostname.php#L75

**Comment by mattab** [comment]
maybe upgrading our Zend Mail library would help this issue?

**Comment by mnapoli** [comment]
@ThaDafinser `info` seems to be a valid TLD in the file though

**Comment by mnapoli** [comment]
FYI the history of https://github.com/zendframework/zf1/blob/master/library/Zend/Validate/Hostname.php doesn't show anything obvious that has been fixed related to the issue here.

**Comment by F0nix** [comment]
changed to .INFO and it worked.

**Comment by ThaDafinser** [comment]
@F0nix @mnapoli yes it's in there, but the error messages is exactly from there.

It should also work regardless of the casesentivitiy...
https://github.com/zendframework/zf1/blob/master/library/Zend/Validate/Hostname.php#L1433-L1434

**Comment by mnapoli** [comment]
Ha ok having a closer look at the error message:

    'mail.xxx.info ' appears to be a DNS hostname but cannot match TLD against known list

`'mail.xxx.info '` there's an extra space at the end. I'll rename the issue so that we trim extra spaces.

**Comment by rsolvang** [comment]
I have the same problem when trying to send emails from a **.link** SMTP address. Is there any way to bypass this check, as it seems out of date?
