### ISSUE TITLE
Delete idsite=1 and try to add a new user - does not work

### ISSUE THREAD

**Issue by Robdebert** [piwik/piwik#7161]
I installed Piwik new. Then a default-site was added to the list of websites with the id 1.

I added a new site, that now has id 2.

After that i deleted website with the id 1.

Now i wanted to add more users with this url: /index.php?module=UsersManager&action=index&date=today&period=day&idSite=1&showaddsite=false
But of course that is not possible. because the Site with the id 1 no longer exists.

*** Possible Solution: ***
remove the get-paramter idsite=1 from this url, or change it to the first found active website, after deleting a website in the list.

or report to the user, that this page was not found and let him select another page and then continue what he was doing.

**Comment by mattab** [comment]
Hi @Robdebert thanks for the feedback and report.

**Comment by mnapoli** [comment]
Related to #7436 and will be fixed by #7507

**Comment by sgiehl** [comment]
Should be fixed with #7507
