### ISSUE TITLE
Move Log Analytics import_logs.py in its own repository

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7163]
The goal of this issue is to move the Log Analytics folder to its own repository under `piwik/log-analytics`. This was discussed a few times by the team.

Having the project under a separate repository makes sense because it is independent from the main source code, it is written in a different technology python, we think it will make contributions easier to have a separate repo. also we want to add CI for log analytics in  #7062 - maybe we could also split the big python file in several smaller files as suggested by @diosmosis to make maintenance easier. 

This would be done while keeping BC of course. we could ask github support to move the issues with label "Log Analytics" to the new repo (I think they can do this).

**Comment by diosmosis** [comment]
Ok to use a submodule?

**Comment by mattab** [comment]
sure, and add it to https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh#L19-L20 so it's there in the packaged release

**Comment by mattab** [comment]
Moved to 2.12.0 as it's hopefully a quick improvement :+1:

**Comment by mattab** [comment]
note: It's kind of obvious but we must keep the Git history for this file when moving to another repo

**Comment by diosmosis** [comment]
Resource: http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by mattab** [comment]
(FYI: asked github support to move `c: Log analytics` issues to the new repository, waiting for them to answer)

**Comment by mattab** [comment]
Update: Log Analytics issues were moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues
