### ISSUE TITLE
Use the "Left Menu" as default menu for all Piwik users

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7169]
The goal of this issue is to consider the idea of setting the Left Menu as the default menu for new piwik users. 

Why make the left menu the default?
 * the left menu helps usability by making a better use of the screen estate.  
 * our reporting menu is a  two-level menu, having it to the left simply is more usable as user does not need to move the mouse as precisely as when it is on the top
 * it will still be possible to set it back to the top (unless we remove this feature and only stick the menu to the left for all users?)

Related to  #6917,  #7093

**Comment by tsteur** [comment]
:+1: for only supporting left menu and no possibility to move it back to the top. Even if some users would like to have a top menu they most likely wouldn't find the setting for this anyway and I don't think the top menu has many advantages and is not worth supporting it. One can't make it right for everyone, people could develop a theme for it though if they want to. Eg it makes everything complicated as we'd always have to test LeftMenu w/o ZenMode, LeftMenu + Zenmode, TopMenu w/o ZenMode, TopMenu + ZenMode etc. This is already quite difficult to make sure everything works in all cases. Ideally, we can maybe even get rid of ZenMode afterwards.

If people still want to use the whole space I would rather support a minimal left menu that takes only a couple of pixel on the left so that one can collapse it basically.

**Comment by mnapoli** [comment]
agreed, :+1: with left menu only I think it would be an improvement

**Comment by mattab** [comment]
Updated issue as per your feedback -> we shall only support Left Menu and remove completely top menu design and feature.

**Comment by Glisse1** [comment]
+1 for focusing solely on left-menu and make it perfect... it`s not only that almost everybody in the industry is going for such a left-menu approach.. it`s just user-friendly because virtually everybody is having a 16:9 screen ratio and top menu is waste of screen estate

**Comment by IgitBuh** [comment]
In case you change that please make it at least optional. I have all my tabs on the left side in a tree menu (https://addons.mozilla.org/de/firefox/addon/tree-style-tab/). I believe I'm not the only one. Sometimes I see people having their task bar on the left side. I'd highly appreciate it if the menu in Piwik would optionally stay at the top and not be forced to the left leaving less space for analysis columns. Thank you.

**Comment by tsteur** [comment]
Moving to 3.0.0 as we discussed it will be added there

**Comment by mattab** [comment]
It will be time consuming for us to maintain both designs:
 * Top menu 
 * and Left menu

Therefore we would like to completely remove the Reporting Top Menu, and the LeftMenu plugin, and the Zen Mode, and have only one style.

**Comment by mattab** [comment]
fixed in #8936

**Comment by yggi49** [comment]
> the left menu helps usability by making a better use of the screen estate.

I disagree.  I am working on a rotated screen (1080 × 1920) with a custom three-column dashboard.  The new left menu takes approximately a quarter of my available space, and my dashboard columns got pretty narrow.  I am definitely considering downgrading to 2.14.

**Comment by Dehumanizer77** [comment]
Thank you for completely destroying the experience for me. It's disgusting. The left menu now pointlessly takes 1/4 of the screen. Thus, 2.14 is the last possible version for me.

**Comment by mattab** [comment]
With design changes, it is difficult to get everyone on board. Overall we are  confident it is an improvement for most people.

Maybe in the future someone will write a [Theme for Piwik](http://developer.piwik.org/guides/theming) where the menu is displayed at the top?

Also we are thinking of ways to "toggle" the menu so that you could hide it and enjoy the full width of screen.

**Comment by Dehumanizer77** [comment]
At least the toggle would be nice, but as it is now, it's unusable for me. I will have to downgrade, but I'm not sure if there were any changes to the database. Can I simply switch to 2.14.3 without making any changes to the database?

**Comment by yggi49** [comment]
A toggle would be great.  I think a different set of CSS rules should be sufficient to move the menu back to the top and provide an acceptable user experience.

**Comment by yggi49** [comment]
I just created and added a custom stylesheet to my browser that moves the menu back to the top.  At least it does the job for me in Chromium/Linux.  It ain’t too pretty—especially the submenus would need further work and aren’t really accessibility-friendly—but at least it’s a start for desktop users who have a mouse.

Check out https://gist.github.com/yggi49/856df1e553391baa759b if you are interested.

**Comment by Dehumanizer77** [comment]
Thanks a lot, yggi! It works with Firefox and Stylish plugin too. You just made my day :-)
