### ISSUE TITLE
Internal referrer search engine with url like example.com/#!tab=1&query={k}

### ISSUE THREAD

**Issue by Jgavin101** [piwik/piwik#7178]
Our intranet has a search feature which we are trying to integrate as a custom Search Engine for the referrer report, see sample url/code below. 

I believe the reason the code below is not working is because the query URL contains a #.

Are #tags (and everything after) automatically being removed from all referrer URLs? 
I have enabled Page URL fragments tracking so I presumed that this would enable tracking of the full url for Referrers also?

The sample search url below is shown as a referrer in the visitor log as http://searchportal.com/search/simple.htm and no data is appearing on the keywords/Search Engines page.

Sample search url
http://searchportal.com/search/simple.htm#!&page=1&tab=1&query=xxxxxx

Line added to Search Engines Data file
'searchportal.com'           => array('IntranetSearch', 'query', 'search/simple.htm#!&page=1&tab=1&query={k}'),

Similar issue:  <a href="https://github.com/piwik/piwik/issues/6718">#6718</a>

**Comment by mattab** [comment]
Hi @Jgavin101 

unfortunately it's not possible AFAIK to get the Hash tag of a Referrer URL. For example in this SO answer: http://stackoverflow.com/questions/2039306/send-a-location-hash-through-a-referrer

`First, the hash portion of a URL is used on the client side only. It will never appear in server logs, requests, or as part of a REFERRER string.`
