### ISSUE TITLE
Delete old visitor logs uses idvisit instead of the date

### ISSUE THREAD

**Issue by kiwipro** [piwik/piwik#7180]
We configure Piwik (2.9.1) to regularly delete old visitor logs, setting to '42' days the field 'Delete logs older than' from 'Delete old visitor logs and reports' section.

Piwik saves the new configuration, recognizes the visit with oldest date (__2014-12-30__) and counts the records to be deleted by running the following queries:
- SELECT COUNT(*) FROM piwik_log_link_visit_action WHERE idvisit <= '5328886'
- SELECT COUNT(*) FROM piwik_log_visit WHERE idvisit <= '5328886'

The visit with idvisit='__5328886__' from our 'piwik_log*' tables is:
"157204844       38      ÇLÔ/JB" __2014-12-30__ 23:52:59     __5328886__ 1198925 ..."
"__5328886__ 38      ÇLÔ/JB" 23:52:59        1       1       0       0       0       __2014-12-30__ 23:52:59     2014-12-30 23:53:45 ..."

If we click on 'Purge DB now', Piwik runs the following:
- DELETE FROM piwik_log_link_visit_action WHERE idvisit <= '5328886' ORDER BY idvisit ASC LIMIT 100000

Our piwik_log* tables contain a lot of visits with idvisit lower than '5328886', but with more recents dates, i.e. visit with idvisit '__5328876__' has '2015-02-05' as date:
"157164279       30      î«7]¤b³k        2015-02-05 13:56:05     __5328786__ ..."
"__5328786__ 30      î«7]¤b³k        13:56:05        1       1       0       0       0       __2015-02-05 13:56:05__     2015-02-05 13:56:22 ..."

It seems Piwik will not delete the visits older than 42 days, but it will delete visits based on idvisit <= '5328886'.

**Comment by mattab** [comment]
Hi @kiwipro thanks for the report. 

if Piwik does not deleted based on date, that's a bug that could lead to data loss, and we should investigate.

**Comment by kiwipro** [comment]
Hi mattab

any news about ?

We have stopped 'Purge DB' functionality from several weeks, and this affects our storage as piwik db is growing day by day.

We would like to manually delete oldest visits from db using sql queries.

Pls, could you suggest us the correct query to delete visits from piwik_log_link_visit_action and piwik_log_visit piwik tables selecting records by date ??

As example, to delete all the visits of 2015 January 15th from both piwik_log_link_visit_action and piwik_log_visit table, what is the correct query to run via mysql client or mysqladmin ?? 

Awaiting your prompt reply, I thank you in advance for your support.
Ciao
kiwipro

**Comment by kiwipro** [comment]
Hi there,

any news ?? any suggestion ??

Awaiting your input, is there anyone that can help me to build the right query in order to delete old visits from piwik db ??

Thanks in advance.
kiwipro

**Comment by mattab** [comment]
Since this could lead to data loss, increasing priority

**Comment by mattab** [comment]
Dear @kiwipro 

thanks again for reporting this issue. We have fixed it and it's available in Piwik 2.14.0-b3

Could you please test this beta version and confirm that the issue is fixed?
