### ISSUE TITLE
add a plugin description to all core plugins

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7184]
The goal of this issue is
 *  to add a plugin description for plugins currently missing one. 
 * make description of plugins consistent, showing the benefit of the plugin with action verb eg ` Create and reuse custom visitor Segments with the Segment Editor. `

**Comment by sgiehl** [comment]
This changes also needs to be done on oTrance!

**Comment by mattab** [comment]
Thanks @sgiehl for the note, oTrance has been updated for all these english strings

**Comment by sgiehl** [comment]
Shall we remove the translations for those keys? Otherwise they won't get
updated.

**Comment by mattab** [comment]
good point, feel free to do it if you want (not sure in otrance how I can delete translations but not the english one?)

**Comment by sgiehl** [comment]
simplest/fastest way would be to remove the complete key, and reimport the english one ;)

**Comment by sgiehl** [comment]
ok. done

**Comment by tsteur** [comment]
> simplest/fastest way would be to remove the complete key, and reimport the english one ;)

doing it like this usually as well
