### ISSUE TITLE
System check not verifying permissions for LOAD DATA INFILE

### ISSUE THREAD

**Issue by averymd** [piwik/piwik#7185]
Discovered during #6868. Despite a DB user not having permission to use `LOAD DATA INFILE`, the system check page believes that they do. When the user doesn't have permission, their Piwik logs will contain entries like the following during the archive process:

    INFO Referrers[2015-02-12 03:41:31] LOAD DATA INFILE failed... Error was: SQLSTATE[28000]:
    Invalid authorization specification: 1045 Access denied for user '<username>'@'%' (using password: YES)[28000]

This error isn't reported in the cron job's log, only Piwik's own log.

**Comment by mattab** [comment]
here probably what's happening is that `LOAD DATA INFILE` does not work and is logged, however `LOAD DATA LOCAL INFILE` then works. When one of the method works, we should not log an error if the other method does not work.
