### ISSUE TITLE
Fix warnings + coding standards with PHP-CS-Fixer

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7186]
Hello together,

there i a small little helper with a huge benefit i use currently for all my projects:
https://github.com/FriendsOfPHP/PHP-CS-Fixer

This little does not only checking for coding standards, it can be actually used to apply them.
There are e.g. tons of unused use statements in Piwik, which would be automatically removed by that tool

Also that tool can be executed as "dry-run" to only report problems, so it can be included in the travis build process.

![piwik](https://cloud.githubusercontent.com/assets/533017/6166942/a012fdb0-b2b5-11e4-8fc8-936d73378bd6.png)

**Comment by mattab** [comment]
Hi @ThaDafinser thanks for the suggestion. It could make sense to set this up sometime.

**Comment by mnapoli** [comment]
I'd love to be able to use http://fabbot.io/ someday as it can automatically fix your pull requests (so the attention needed and effort is really low). The problem is that it's still in beta and only works for the Symfony repositories for now.

**Comment by mattab** [comment]
Related @kaz231 pointed out there is a tool in PhpStorm as well, which could maybe help until we can automate everything on CI. https://confluence.jetbrains.com/display/PhpStorm/PHP+Code+Sniffer+in+PhpStorm

**Comment by mattab** [comment]
See also our follow up issue `Automatically convert our code base to use a consistent code style` #9545
