### ISSUE TITLE
Visual: Custom Alert overlap

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#7188]
Using Piwik 2.11.b3
Chrome 39 or Firefox  35.01 on Windows.

The blue link to "History of triggered alerts" is hidden under "Manage Custom Alerts". See : 

![image](https://cloud.githubusercontent.com/assets/5972510/6170907/d8af214a-b2a5-11e4-8231-cf23899b790e.png)

The same visual problem appear in "History of triggered alerts" that links back to "Manage Custom Alerts".

**Comment by tsteur** [comment]
Can you try to clean your `tmp/templates_c` directory and if this does not help try to run `./console core:clear-caches`?

**Comment by gaumondp** [comment]
Did both operation, clear also Chrome cache and Xcache on server but still the same overlap...

**Comment by tsteur** [comment]
I released a new version of the plugin (0.1.19) which should be available now. You might have to clear the caches again to see the update in the UI immediately.

**Comment by gaumondp** [comment]
I can confirm 0.1.19 visual works.

Congrats and thanks !
