### ISSUE TITLE
Mysql process list is clogged with very inefficient updates on the archive blob tables

### ISSUE THREAD

**Issue by moee** [piwik/piwik#7195]
I maintain a piwik installation that consists of approximately 1,300 sites and a database size of 70+ GB.  

Since the update to 2.10.0 I see very inefficient update queries clogging the process list. Consequently, performance is severely degraded and opening statistics for a specific website most of the time fail with the error message "`SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction`". 

Offending queries look as follows, where `date1` and `date2` always are today's date and `idsite` is either id.

    UPDATE piwik_archive_blob_2015_01  SET value = 4 WHERE ( (date1 <= '2015-02-13' AND '2015-02-13' <= date2 AND name LIKE 'done%') )  AND idsite IN ('7991')

The shown query, for instance, has been running for 250 seconds and counting. I assume that the query comes from [method "updateArchiveAsInvalidated" in core/DataAccess/Model.php](https://github.com/piwik/piwik/tree/master/core/DataAccess/Model.php#L75).

In the `config.ini.php`, `enable_browser_archiving_triggering` is set to `false` and `time_before_archive_considered_outdated` is set to `86400`. The archiver job itself is triggered every hour.  However, since the database being blocked with the mentioned updates, it fails to finish within one hour.

Please see also this post in the piwik support forum: [Call to updateArchiveAsInvalidated performs very inefficient update statements / Massive performance problems since update to 2.10.0](http://forum.piwik.org/read.php?2,124032).

**Comment by mattab** [comment]
Hi @moee - thanks for the report. I don't know if it will change anything but just to be sure, could you try with 2.11.0-RC version? we've made some improvements in  #7031

**Comment by mgazdzik** [comment]
Hi guys, I'm just wondering if it even makes sense to run update queries on blob tables ?
Since where clause contains
```( (date1 <= '2015-02-13' AND '2015-02-13' <= date2 AND name LIKE 'done%') )``` 
this update query will actually never find a single record to update (AFAIK done flags are only located in numeric tables which are way smaller than blobs.

I believe that this line https://github.com/piwik/piwik/blob/master/core/DataAccess/ArchiveInvalidator.php#L176
should return only numeric tables, and this could make invalidating archives run way faster.

**Comment by mattab** [comment]
> Hi guys, I'm just wondering if it even makes sense to run update
> queries on blob tables ?
>
Good point, thanks!! we'll make the change

**Comment by mattab** [comment]
@mgazdzik  @moee Are the queries locking the database ONLY the queries on the `archive_blob_*` table? or do you sometimes see the `archive_numeric_*` tables as well?

**Comment by moee** [comment]
@mattab thanks for the follow up. no, it's always the `archive_blob_*` tables, but never the `archive_numeric_*` tables that are affected.
ATM I'm updating to 2.11.0. I will shortly post a follow up whether the update fixes the slow query problem or not.

**Comment by quba** [comment]
It's not fixed in 2.11. Probably we will have 2.11.1 to address this issue.

**Comment by mattab** [comment]
Hi @moee  Piwik 2.11.1-b1 has been released with the bug fix- can you please test and tell us if you still have any issue?

**Comment by freelock** [comment]
Hi,

We were experiencing this issue too -- making Piwik practically unusable for us. Can confirm that 2.11.1 fixes it... Much, much better!

Thanks!

**Comment by moee** [comment]
Hey @mattab - Sorry for the late response. I updated to 2.11.1 and I also can confirm that this resolves the issue. Thanks for the fix!
