### ISSUE TITLE
Browser versions in "Visitors in realtime" | Enhancement

### ISSUE THREAD

**Issue by srmobile** [piwik/piwik#7197]
I posted this in the Piwik forums and was asked to put it here.

At the moment when looking at  "Visitors in realtime", you currently cannot see their browser versions. 

Adding this information would be extremely beneficial for many reasons. Would love to see this in a future release.

Thanks Matt!

**Comment by sgiehl** [comment]
Quite simple to change. Maybe it makes also sense to change that in the full visitor log, as well as the visitor profile

**Comment by srmobile** [comment]
Thanks sgiehl, I appreciate the quick response.  Fully agree with adding to the full visitor log and profile as well.
