### ISSUE TITLE
"Action" caching

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7198]
As a follow up to #7104 to gain even more GUI performance, i think it would be good to cache reports and other pages if possible.

All reports, which does not process data from the current day would/should be save to cache.

How to cache it? I think the easiest way would be a complete response cache.
-> take the complete url with all variables and generate a cacheId
-> save the response to cache

If a new request comes in, generate again the cacheId and check if a valid cache is around.
-> when yes return it
-> when no -> go to the normal process

Saving the cache could happen in the FrontController: https://github.com/piwik/piwik/blob/master/core/FrontController.php#L96

Check for the cache could even happen before...e.g. in the index.php or bootstrap.php

Some thoughts:
- maybe the parameters are too different all the time, that nearly no cache item will be hit?
- Cache check needs also time and if the miss rate is high, the benefit is the opposite we want
- Not possible to cache: "live widgets" and reports for the current day

What do you think?

**Comment by mattab** [comment]
Heya, can you post your thoughts in: #7143
