### ISSUE TITLE
  Plugin to provide funnel analysis report

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#7204]
hey please point to a working funnel plugin that is working with piwik 2.x
i did not find any working.

**Comment by mattab** [comment]
Hi there, discussed in #6080

**Comment by mattab** [comment]
Hello,

We've just launched the new Funnels premium plugin! The premium Funnels plugin provides really powerful Conversion Funnels analytics directly in Piwik. Learn more & get the plugin in the [Funnels Marketplace page](http://plugins.piwik.org/Funnels). Check the [Funnels User Guide](https://piwik.org/docs/funnels/) and [Funnels FAQ](http://piwik.org/faq/funnels) for more information. Looking forward to hearing your feedback!
