### ISSUE TITLE
funnels may need only small corrections to work with piwik 2.x

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#7205]
Hey,
could be a integrated in piwik, could also stay a plugin.
i would like to encourage you all to update funnels plugin to work with piwik 2.x
https://github.com/jesstelford/funnels 

or please point to a working funnel plugin that is working with piwik 2.x
i did not find any working

Thank you very much...

**Comment by mattab** [comment]
Hi there, please report in the funnels issue tracker directly as this is not a plugin made by Piwik team. cheers

**Comment by Tobias-Conrad** [comment]
i know that it is a different developer.
but when you add funnels to the main piwik than it is the right place to write here.
no reaction from jesstelford
