### ISSUE TITLE
easy correct user exit rate, on landing pages, one page sites

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#7207]
67% User exit rate (left after view one page)
could be turned into
xx% User exit rate (left after view one page and stayed less than 20 seconds)
1 page visit + less than 20 seconds : user exit
1 page visit + more than 20 seconds : user interested 
2 page visits + more than 20 seconds : user interested 
2+x page visits + less than 20 seconds : user exit (may user interested )

For google e.g. it is important how long the user stays on page.
Think of a landing page (only one page) with video (average view time 8:30 min.).
So Piwik would say user is exit without interest, google would say wow good content, value resource.

So this valuable resource should be honored by Pwiki statistics.

**Comment by mattab** [comment]
Hi @Tobias-Conrad I'm not sure I get it, but it seems related to: #2041

**Comment by Tobias-Conrad** [comment]
#2041 is the software behind (ping server on user exit)
My issue is about mathematics. 
I was using clicky.com before and they do it like I described.
See the middle part of the article.
https://clicky.com/help/faq/tips/different/bounce-rate

**Comment by RMastop** [comment]
Hi @Tobias-Conrad, issue #2041 would be the solution to make us notice a difference between single page visits, with visitors probably reading the page and visitors navigating away within a few seconds. The definition that needs to be added is the amount of time a visitor should have stayed on that single page visit before it is calculated as a visit instead of a bounce.

**Comment by Tobias-Conrad** [comment]
yes that is right. bring it on the road please

**Comment by mattab** [comment]
Duplicates #2041 

it's in short term, so hopefully we get it done in the next 3 months. it would be very nice feature indeed!
