### ISSUE TITLE
DOM User activity tracking

### ISSUE THREAD

**Issue by shahar3012** [piwik/piwik#7208]
Hi,  I'd like to develop new feature for piwik - tracking DOM user activity.
I would add new action type to piwik tracker class and create new plugin to support it.  Also, I would improve the Javascript tracker to implement this new feature. 

Many might think that this can be accomplished by using the existing Events in piwik, but it cannot be done without unrelated data that will be saved to piwik tables in the database.  

I'm asking the project owner / founder for acceptance that this is the way piwik want to go. 

Please reply, so I could think if it worth developing this feature.

**Comment by Glisse1** [comment]
A real-time analytic platform apart from bulk general stats (found for example in google analytics) is absolutely required to have:

1) customizable real-time web desktop notifications  (eg, visitor coming from a certain country, opening a certain page like registration, etc)
2) real-time pinging of visitors (knowing when they are actively reading/ scrolling/ writing something, with just 2-3 seconds of delay) for accurate time on page and reports
3) easy to implement dom activity tracking
 
So, from where I am standing you are tackling 1/3 of the big problem.. it`s not just worth it, it`s an absolute must-have! That is, for a "real-time" label.

**Comment by mnapoli** [comment]
@shahar3012 Isn't what you want to do the same as [Content tracking](http://developer.piwik.org/guides/content-tracking)?

**Comment by mattab** [comment]
as @mnapoli points out, we built powerful feature http://developer.piwik.org/guides/content-tracking for this purpose. If that does not meet your requirements, please create new issue with your requirements listed :+1:
