### ISSUE TITLE
Duplicate actions are logged for lower/upper case encoded URL

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7209]
For example `piwikjapan.org/%E6%A9%9F%E8%83%BD%E8%AA%AC%E6%98%8E/4695` and `piwikjapan.org/%e6%a9%9f%e8%83%bd%e8%aa%ac%e6%98%8e/4695`. Type is always `1`.

Most likely the problem is that we url encode in the browser and different browsers might use uppercase or lowercase: https://github.com/piwik/piwik/blob/2.11.0-b7/js/piwik.js#L2917

We'd need to solve this in the backend and replace all lowercase url encoded values with uppercase (or the other way around but uppercase seems to be more common).

**Comment by tsteur** [comment]
URL and referrer should be no longer stored URL encoded meaning this issue *should* no longer occur. To be sure we will check Piwik demo in 2-3 weeks whether there are still any URL encoded values with lower/uppercase difference.

**Comment by mattab** [comment]
@tsteur could you confirm / check this one is fixed as we suspected?

**Comment by tsteur** [comment]
It's hard to tell. PiwikJapan is still using an old piwik.js. Do we have another site with such urls?

**Comment by mattab** [comment]
unfortunately we don't. I've sent an email asking PiwikJapan team if they can update the Piwik running there.

**Comment by mattab** [comment]
fyi: the site was updated with latest piwik

**Comment by tsteur** [comment]
I couldn't find any url encoded entries of the last days and also tested it myself again. 

Please note if someone still experiences this issue, check the expires header for `piwik.js`. There might be still some users with an older `piwik.js`
