### ISSUE TITLE
Adding Toppreise.ch as search engine

### ISSUE THREAD

**Issue by iquito** [piwik/piwik#7216]
Toppreise.ch is a products search engine in Switzerland, and the following lines should be added to core/DataFiles/SearchEngines.php:

    'www.toppreise.ch'      => array('Toppreise', 'search', null, 'iso-8859-1'),
    'toppreise.ch'      => array('Toppreise', 'search', null, 'iso-8859-1'),
    'fr.toppreise.ch'      => array('Toppreise', 'search', null, 'iso-8859-1'),
    'de.toppreise.ch'      => array('Toppreise', 'search', null, 'iso-8859-1'),
    'en.toppreise.ch'      => array('Toppreise', 'search', null, 'iso-8859-1'),
    '{}.toppreise.ch'      => array('Toppreise', 'search', null, 'iso-8859-1'), 

I am not sure if some lines are redundant, that is why I am just posting it without a pull request.

**Comment by sgiehl** [comment]
I just took a look at ``www.toppreise.ch``. I don't see how the keyword could be passed with the referrer. All external links seem to go through a proxy script.
Do you have a referrer url in your tracking data containing a keyword?

**Comment by iquito** [comment]
Yes, most links from toppreise have a referrer with the search keywords - that is why I implemented it in my Piwik installation and bringing it up here ;-)

The proxy script probably just makes a HTTP redirect, so the proxy page is not saved as referrer, because I never have something like ```http://www.toppreise.ch/call.php``` as referrer, always the page the user was on.

**Comment by sgiehl** [comment]
Could you post an example url, how the full urls are looking like?

**Comment by iquito** [comment]
These are all referrer log entries from Toppreise I got recently:

```http://www.toppreise.ch/index.php?search=Sissel+Sitfit+Plus```
```http://www.toppreise.ch/index.php?search=Kniebandage```
```http://www.toppreise.ch/index.php?search=Epitact+Hallux+Korrekturschiene```

Important in my entry in SearchEngines is the iso-8859-1 encoding, otherwise characters like äöü are falsly assumed to be UTF-8, whereas Toppreise is still fully iso-8859-1.

**Comment by tsteur** [comment]
Sorry that last commit was meant for #7261 !
