### ISSUE TITLE
Data bleeding over in bulk inserting with custom variables

### ISSUE THREAD

**Issue by iquito** [piwik/piwik#7217]
I already reported this issue last summer (unfortunately I cannot find a link to it) and it was supposedly fixed - when doing bulk inserts of many records, the data given to Piwik is not reset after every visit entry for custom variables with scope "visit". I tested it again with the newest release just now, and the same bug still exists:

In my case, I am inserting 1000 page visits at a time. As soon as a custom variable with scope "visit" is set, all further visits seem to be added to this first visit, even though I am setting an explicit visitor ID (via setVisitorId in PiwikTracker class) for every entry.

This leads to HUGE visitor log entries - suddenly one visitor seems to have visited 500 pages and made 4 purchases within his journey (which would be great, if anyone would ever do that).

Currently, to circumvent this problem, every time a custom variable with "visitor" scope is set I issue a ```$t->doBulkTrack();``` and start again. Unfortunately, this is not very efficient - instead of 1000 entries at a time, there are many requests with a small number of inserts. So a fix would be greatly appreciated.

**Comment by mattab** [comment]
Hi there, did you upgrade the PHP client to latest version? it should work thanks to this code here: https://github.com/piwik/piwik-php-tracker/blob/master/PiwikTracker.php#L1310-1312

if it doesn't with the latest version of the Piwik Tracking PHP client please reopen, and if possible post a script to reproduce the issue.

**Comment by iquito** [comment]
Yes I used the latest version, and it contains the code you mentioned - I just checked it. This problem still occurs.
