### ISSUE TITLE
Segmentation for url-encoded page urls does not work

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7218]
Our segmentation logic does always url decode all values so it will never match a url-encoded url like `piwikjapan.org/%E6%A9%9F%E8%83%BD%E8%AA%AC%E6%98%8E/4695`.

If I understand it right one problem is that some actions are stored raw while some other actions are stored URL encoded.

**Comment by tsteur** [comment]
Actually all is good. In this case it was an error that the URL was wrongly tracked (user error). If the URL is stored URL encoded (which happens when sending them double url encoded), then one also has to build a segment filter that is double url encoded.

**Comment by cosmoblonde** [comment]
The error is still there. Testcase: When creating a segment with an "or" combination of 2 or more page URLs - directly after creation of the seqment the report is fine but when revisiting the seqment at a later time it shows: no data for this report.

When copying the generated url into a urldecoder-Tool, decode it and paste it again into the browser - the seqment works. So the double encoding seems to be still an issue. 
Seqments with only one condition work.
 
Tested with Piwik 3.01 and Firefox 51.01

**Comment by mattab** [comment]
@cosmoblonde please try again in Piwk 3.0.2 where we fixed an issue in segmentation. if you have a problem still, open a new issue
