### ISSUE TITLE
No nice overview in Visitors Log after upgrade to 2.10

### ISSUE THREAD

**Issue by zefat** [piwik/piwik#7222]
After upgrading to 2.10 I only have lines as I click Visitors Log (looks like database lines). As there was aways nice lines, (nice colored, OS given, IP and stuff). 

Now it's only a one liner with no layout. 

Please help. 
Thanx

**Comment by mattab** [comment]
Hi there, please upgrade to 2.11.0-rc1 where this bug has been fixed http://piwik.org/faq/how-to-update/faq_159/

**Comment by zefat** [comment]
Thanx mattab.
