### ISSUE TITLE
Allow creating pre-processed segments archived only forward

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7223]
Goal of this ticked is to allow following action:
- user defines new segments
- first archiving will only process those segments since day of their creation, instead going all way back
- this way segments will be lighter in some cases where user doesn't need historical data (which is sometimes huge)

I think that initiall this could be a setting in config, and after some time it could be turned into per-segment setting.

**Comment by RMastop** [comment]
+1 for this feature. Another +1 if one could change the date a segment should be archived from.

**Comment by diosmosis** [comment]
Thinking of adding a new INI config option like:

```
[General]
process_new_segments_from = ... ; allows special values 'beginning_of_time', 'creation_time', 'lastN' (lastN days)
```

which would be handled by CronArchive. May need to add a flag to segment table to track whether segment has been archived for the first time (haven't really looked or thought of alternatives yet, but this is more stable than option values).

**Comment by mattab** [comment]
@mgazdzik could you confirm whether such solution of a new INI setting would solve the problem at hand?

**Comment by mgazdzik** [comment]
As ultimate feature I would vote for adding possibility to define such things per segment from UI.
However what was proposed by @diosmosis also looks nice for initial change, as I guess that in most cases this setting would work well as global.
Therefore :+1: for implementing this config setting

**Comment by mattab** [comment]
@mgazdzik  issue was created for follow up step  #7483 

I'll take a look at the PR from @diosmosis and aim to merge it for 2.12.0

**Comment by mgazdzik** [comment]
Cool to hear, thanks :+1:
