### ISSUE TITLE
DOM User activity tracking - new feature 

### ISSUE THREAD

**Issue by shahar3012** [piwik/piwik#7224]
This issue is related to issue #7208. 

This feature includes whole page automatic tracking: 
- DOM clicks
- DOM hover
- any suggestions? 

The tracked data will be shown in 4 views (new plugin necessary) grouped by:
- HTML tags
- element's css class attribute 
- element's id attribute 
- element's name attribute 

Please consider this as enhancement to piwik. 
In order to make it happen we need to add code to piwik tracker, because it need to be tracked as new tracking data, because of the different views in the plugin - It should be grouped by different column in the new tracking table in the db, and not by some improvisation of existing column in existing table. 

**Furthermore, this feature brings the opportunity to create more relevant and accurate heatmap for piwik, based on the new data that can extend and enhance the overlay feature.**

I want to contribute and develop this feature.

**Comment by mattab** [comment]
Hi there,

Please consider using Content Tracking which is a powerful feature designed for exactly this purpose: http://piwik.org/docs/content-tracking/

See the implementation guide details at: http://developer.piwik.org/guides/content-tracking

**Comment by shahar3012** [comment]
@mattab I did consider Content Tracking, but it not naturally support my requirements and if I use it I have to do some improvising which is not so good and will cause Content Tracking containing garbage data. 
If I work on this feature, you would consider merging it if the master branch?

**Comment by mattab** [comment]
>  I did consider Content Tracking, but it not naturally support my requirements and if I use it I have to do some improvising which is not so good and will cause Content Tracking containing garbage data. 

Maybe you can elaborate on your requirements, and/or the limitations with Content Tracking? my first thought would be that maybe it would be easier to improve Content Tracking to accommodate your requirements, rather than build a new complicated feature. 

> If I work on this feature, would you consider merging it with the master branch? 

We always consider new features of course, but I'm trying to help and minimise the amount of work you'd have to do by reusing some existing features :+1:

**Comment by shahar3012** [comment]
I want to divide the tracking data into 4 views:
* HTML tags
* element's css class attribute
* element's id attribute
* element's name attribute

Using the Content Tracking is not the best solution as I would have track in some way like this: "{HTML tag} |{id} |{name} |{class}"  and

**Comment by mattab** [comment]
Maybe you could use [Event Tracking](http://piwik.org/docs/event-tracking/) to record this data on the server side?

**Comment by shahar3012** [comment]
I think it should be tracked in the client side, because the clicks and hovers occurs in the browser, so it simply better to implement the tracking only one time and for every page on every website.

**Comment by mattab** [comment]
sure, the DOM events have to be collected client side in JS, but I meant that to track it in Piwik you can use Event Tracking - does it make sense?

**Comment by shahar3012** [comment]
I think I'll write a new plugin to add this feature.

**Comment by mattab** [comment]
Please post your comments in the duplicate ticket here https://github.com/piwik/piwik/issues/6371

**Comment by mattab** [comment]
Good news: we're working on [Heatmap Analytics for Piwik](http://www.heatmap-analytics.com/) + scrollmap + click map! It will be awesome and make sure to hear when it's released by signing up here: http://www.heatmap-analytics.com/
