### ISSUE TITLE
Reorganize technical reports

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#7227]
we should reorganize the technical reports. (follow up to #3962)

We currently have:
- Devices
  - Device type
  - Device brand
  - Device model
  - Browser (Versions)
  - OS (Versions)
  - Browser engine
- Visitor settings
  - Resolution
  - Configurations (OS / Browser / Resolution)
  - Browser plugins
  - Browser language

I don't think that this splitting makes much sense. Maybe something like that would fit more:
- Devices
  - Device type
  - Device brand
  - Device model
  - Resolution
- Something like "Browser & Operating System"
  - Browser (Versions)
  - OS (Versions)
  - Browser engine
  - Browser plugins
  - Configurations (OS / Browser / Resolution)

Browser language report will be move to location reports in #7226
Devices reports should also be improved, which will be done in #6933

Maybe we could also link the resolution and the configurations reports as related?

**Comment by tsteur** [comment]
:+1: for reorganizing it like this. I was always confused by that. Would be nice to have something shorter than "Browser & Operating System" but I like that it's clear. Maybe "Software"? or something else...

**Comment by gaumondp** [comment]
"Browser & Operating System" => Browser & OS ?
 "Browser & Operating System" => Client software ?

"Software" alone could be misleading IMHO.

**Comment by sgiehl** [comment]
I think "Client Software" would fit best, as we might add more reports there in #5413

**Comment by mattab** [comment]
+1 for `Client software`

**Comment by tsteur** [comment]
"Client Software" would be only browser but not Operating System right?

"Client Software" from http://techterms.com/definition/client : 
> The term "client software" is used to refer to the software that acts as the interface between the client computer and the server. For example, if you use Microsoft Outlook to check your e-mail, Outlook is your "e-mail client software"

As this report is under "Visitor" I would have preferred just "Software". Maybe some people would be even confused by this rather technical name (Client Software)? Software would be a bit broader / universal since we also want to allow to track other things than websites.

**Comment by sgiehl** [comment]
@tsteur good point. So "software" only?

**Comment by mattab** [comment]
see comment in: https://github.com/piwik/piwik/pull/7292#issuecomment-88301511

After this little one, maybe we close the issue  :+1:

**Comment by sgiehl** [comment]
UI tests should be fixed now
