### ISSUE TITLE
The arrows are displayed incorrectly on Chrome

### ISSUE THREAD

**Issue by MinonHeart** [piwik/piwik#7230]
Google Chrome 39.0.2171.71 (No Extension)
Piwik: 2.10.0

---
![0](https://cloud.githubusercontent.com/assets/8586286/5356250/c9b9f71c-7fd5-11e4-8d42-fe0a5b396249.png)
---
![full](https://cloud.githubusercontent.com/assets/8586286/5368981/78367a3c-8048-11e4-9fe4-c6856aed9529.png)

![chrome](https://cloud.githubusercontent.com/assets/8586286/5368982/783a0ef4-8048-11e4-841e-6a28b5370c9a.png)
---
More Info. → https://github.com/piwik/piwik/pull/6831

**Comment by mattab** [comment]
Hi there, can you reproduce this bug in 2.11.0 ?

**Comment by MinonHeart** [comment]
@mattab pictures
![2015-02-19_105033](https://cloud.githubusercontent.com/assets/8586286/6261189/7f1b7404-b826-11e4-95b6-9027095f3a7c.png)

![2015-02-19_105014](https://cloud.githubusercontent.com/assets/8586286/6261231/174442ec-b827-11e4-9f81-a9adb94e0966.png)

![qq 20150219105236](https://cloud.githubusercontent.com/assets/8586286/6261234/1dd8a65c-b827-11e4-8c86-7c771d283f77.png)

**Comment by tsteur** [comment]
What's your browser language?

**Comment by MinonHeart** [comment]
@tsteur Chinese Simplified

**Comment by mattab** [comment]
Hi @MinonHeart  can you test the fix in https://github.com/piwik/piwik/commit/ee924ac6597f277abb4ae0ad0deae3704db034c7 then delete your `piwik/tmp/*` folder, and confirm that issue is fixed for you? thanks

**Comment by MinonHeart** [comment]
@mattab Fixed. ↖(^ω^)↗
