### ISSUE TITLE
pluging Transitions - possible URL mismatch

### ISSUE THREAD

**Issue by dscaravaggi** [piwik/piwik#7236]
Hi all,
I'm a newbie Piwik programmer, 
I noticed that usage of textarea post parameters at line 34 of
plugins/Transitions/javascripts/transitions.js

may genarate inconsistent url when JSON decoded serverside
on my dev laptop I inserted a "difensive" line:
```javascript
    link = $('<textarea>').html(encodeURIComponent(link)).val();
```

and of course I added the symmetric decode (plugins/Transitions/API.php line 68)
```php
    $l_uriDecodeString = urldecode( $actionName );
    $actionName = $l_uriDecodeString;
```

maybe there is another more elegant way to "sanitize" strange url with a lot of ampersand querystring etc... but this help ma a lot with MS sharepoint sites.

Thanks in advance
Diego

**Comment by dscaravaggi** [comment]
I received positive feedback from the Intranet sharepoint webserver. Transition graphs are correctly generated for any page and url with space ampersand and à ù è etc....

**Comment by mattab** [comment]
Hi @dscaravaggi can you detail how the bug can be reproduced? What kind of URLs were not working in Transitions, and are working after your patch? before we fix the issue we must be able to reproduce it. Thanks

**Comment by dscaravaggi** [comment]
Sorry for my late answer, I reproduced myself on the laptop, I prepared a trivial php script with this url:
http://127.0.0.1:9092/test_tracker_Mysql/test2_mysql.php?param2=hr41%C3%A8%C3%A8&param6=hr6%C3%A0%C3%A01.  (Github is smarter and prevented me to paste such Italian accent).
```
http://127.0.0.1:9092/test_tracker_Mysql/test2_mysql.php?param2=h41èé?param4=ùù0
```
try It with and without my suggestions. (I used v 2.9.1 but source code is the same)
![issuetransitions](https://cloud.githubusercontent.com/assets/9715775/6284340/4d633b44-b8ef-11e4-9bbe-941ac5852064.jpg)

I hope this could help.

**Comment by mattab** [comment]
@dscaravaggi we made a few fixes in 2.10.0 and even 2.11.0 

could you try again with 2.11.0 and confirm whether you can still reproduce this issue?

**Comment by dscaravaggi** [comment]
I've just made the test with 2.11.1 and the problem is **not** present.
I ask to close this  *not a bug*

**Comment by mattab** [comment]
Great news @dscaravaggi
