### ISSUE TITLE
error in statistics graph, avg_time = 2, uniqe_visitors = 0

### ISSUE THREAD

**Issue by bglxx** [piwik/piwik#7247]
since update to 2.11.0 we have the problem, that the large statistics displaying wrong values in the large graphs.

picture err_01.jpg shows values for visits (okay) but wrong values for unique visitors and avg. visit duration - this occurs when i select period length = year
![err_01](https://cloud.githubusercontent.com/assets/8326945/6263337/4eff1eca-b816-11e4-8fea-903262b07df7.jpg)

picture err_02.jpg shows values for visits and for unique visitors (okay) but wrong values at avg. visit duration - this occurs when i select period length = month

![err_02](https://cloud.githubusercontent.com/assets/8326945/6263365/a075fe9a-b816-11e4-8fbb-f6af88c38679.jpg)

the detailled data at "Visitors/Visitor Log" are okay

picture err_03.jpg shows the wrong graph at the top and the right small graphs in the lower section.

![err_03](https://cloud.githubusercontent.com/assets/8326945/6263382/1b68a8f0-b817-11e4-9c2c-7e3e773c6c9b.jpg)

**Comment by bobwalter** [comment]
I have exactly the same issue that began as soon as v11.0 was installed. See attached screen shots.
![piwik-log-p1](https://cloud.githubusercontent.com/assets/3653741/6277271/233ced7c-b842-11e4-8dc5-b7e2818a059a.jpg)
![piwik-log-p2](https://cloud.githubusercontent.com/assets/3653741/6277276/29819c1e-b842-11e4-8dc1-34bf86662f4c.jpg)
![piwik-post-v11](https://cloud.githubusercontent.com/assets/3653741/6277279/3077138c-b842-11e4-8ca6-3450c6f8da74.jpg)

**Comment by tsteur** [comment]
Is the config setting `enable_processing_unique_visitors_year` enabled?

**Comment by bobwalter** [comment]
No, it is set to "0"

I had no idea there was such a value. Should I enable it? If so, what does that have to do with reporting daily visit times?

**Comment by tsteur** [comment]
It solves the part about "wrong values for unique visitors"

**Comment by tsteur** [comment]
FYI: The avg visit duration bug is caused by https://github.com/piwik/piwik/commit/8619da2236a59b67fd4d2faefaf5a3f257de3dca refs #6923

**Comment by tsteur** [comment]
@diosmosis do you mind having a look re avg visit duration? Eg instead of `2min 39s` it would display a `2` and it says `Avg. Duration of a Returning Visit (in sec)` although it is not in seconds.

**Comment by bobwalter** [comment]
What is particularly unusual is that the report changed the visit durations going back as well. See my image of the report. Is there a fix in progress?

**Comment by bobwalter** [comment]
Also, this is new to v11.0. The same day, prior to upgrade, visit duration was correct.

**Comment by mattab** [comment]
* maybe we could add (or edit) a UI test to include the avg_time to prevent regression in future

**Comment by tsteur** [comment]
@bobwalter there are 2 issues. 

* Visit Duration which is a bug indeed
* Unique Visitors for year which is most likely just not enabled (this was reported by the issue creator)

**Comment by bobwalter** [comment]
I am NOT asking about visitors per year. That is an old issue and not very important to me. I made the config change and I am happy about that.

The ONLY issue I am raising is the bug that misreports visit duration. This bug appeared with V 11.0.

Thank you.

**Comment by tsteur** [comment]
@bobwalter I just mentioned in the comment above that the Visit Duration is a bug. I know that you are only raising this issue that's why I mentioned that the year bug was mentioned by the issue creator, not you. We are working on a fix.

**Comment by bobwalter** [comment]
Thanks, I didn't understand.
