### ISSUE TITLE
Class 'Piwik\Ini\IniReader' not found

### ISSUE THREAD

**Issue by blodan** [piwik/piwik#7248]
Hi,

I just tried upgrading to 2.11.0 but received this error:
PHP Fatal error:  Class 'Piwik\Ini\IniReader' not found in /usr/home/www/analytics.203.se/core/Config.php on line 82

So I had to downgrade to 2.10.0 again.

**Comment by claytondaley** [comment]
+1

**Comment by tsteur** [comment]
Do you install / update via Git? If so, try to run `composer.phar install`

**Comment by blodan** [comment]
No, downloaded the zip and extracted it over the old zip/install

**Comment by mattab** [comment]
Some files were not uploaded correctly, check eg. that files in `vendor/` are uploaded

**Comment by claytondaley** [comment]
I used the UI-based upgrade and had the same issue.

**Comment by mattab** [comment]
That's really weird - anyone else experienced this issue? please leave a comment!

**Comment by blodan** [comment]
I made a straight extract from the zip, if there is something missing from the vendor folder it isnt in the released zip

**Comment by mattab** [comment]
can you try again to re-upload all files in `vendor/` and see if that helps?

**Comment by claytondaley** [comment]
OK so I was able to reproduce by unzipping 2.10.0 over the failed 2.11.  When I rerun the upgrade through the UI, I get:

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@piwik.daleycrm.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

Upon refresh, I get the `IniReader` error again.  If I run `composer update`, it runs until the following error:

```
  - Updating mnapoli/php-di 5.0.x-dev (4676e15 => bc174fd)

  [RuntimeException]
  The .git directory is missing from /home/...piwik/vendor/mnapoli/php-di, see http://getcomposer.org/commit-deps for more information
```

Not sure if this could have anything to do with the `Internal Server Error`... but I've never seen an error like this with composer -- and I have a ZF2 project pulling from several dev branches so I've been around the block once or twice with composer quirks.

**Comment by mattab** [comment]
ping @mnapoli - maybe you have an idea? 

maybe at some point it would be nice to do a official PHP-di release, now that we've  (hopefully) ironed out the DI implementation in Piwik?

**Comment by mnapoli** [comment]
Regarding the IniReader error, could it be that by uploading 2.11 over 2.10 some old files are not deleted and are still loaded by Piwik somehow? @mattab Is that recommended to upload a new Piwik version over an existing one even if we know that Piwik auto-loads some files? Maybe there should be something that clears the old files?

@claytondaley & @blodan could you try clearing all the 2.10 files (except the config file) and then upload 2.11?

---

The second error mentioned here (during `composer update`) is normal: `.git/` directories are removed when the release is generated to optimize its size. Using composer at that point isn't supposed to work. And in any case `composer update` shouldn't be run, `composer install` should be used instead. But even then, that is not supposed to work here.

**Comment by claytondaley** [comment]
Unzipping 2.11.1 on top of the 2.10 install worked for me -- no need to delete files.  I rolled back to 2.10 because I didn't have time to deal with it at that moment.  Later, I decided to try and reproduce the error (successfully as it were) so I could provide more info than "it broke".

**Comment by blodan** [comment]
actually, removing the entire folder with the 2.10 install and then extracting the 2.11 install and then copying in the config file worked, thanks!

On another note, you said you are excluding the .git directories from the zip, you might want to exclude the .gitignore files to in that case as they have no use if one isnt using git

**Comment by mnapoli** [comment]
@blodan yes we could indeed. `.git/` is excluded because it can be big, but `.gitignore` is super small so we don't really bother.

**Comment by Irrational86** [comment]
I just did an update about an hour ago through the UI, and the issue is still happening.

For informative purposes: this Piwik install started fresh back on 2.1-ish (maybe a bit before), and has always been upgraded through the UI without any issues.

I have never had to do a manual update until just now, however, it seems to be back up and working fine.
