### ISSUE TITLE
allow to choose the flattened version of reports in email reports (or use the flat version by default in email reports)

### ISSUE THREAD

**Issue by ArnY** [piwik/piwik#7249]
By default reports are hierarchical but sometimes the flattened version of the report is more useful (when the paths used by web sites aren't representative of any hierarchical ordering, for example). 

This isn't an issue on the web interface since the hierarchical items can be unfolded but this is not possible in emailed reports.

It would be usefull to allow the user to choose to receive flattened reports by default when creating a new email report.

**Comment by gaumondp** [comment]
Maybe duplicate of #2137 ?

**Comment by ArnY** [comment]
Indeed a duplicated of  #2137
