### ISSUE TITLE
The parameter 'period' isn't set in the Request, and a default value wasn't provided. when clicking on API link in menu

### ISSUE THREAD

**Issue by petersj77** [piwik/piwik#7250]
Just installed the latest version of Piwik (2.11.0) and set up my first website for tracking purposes. 

I need to get the API code for the WP-Piwik plugin on my WordPress site, so when I click on the View Tracking Code link, and then select API in the left hand menu I get the following error page 

The parameter 'period' isn't set in the Request, and a default value wasn't provided. 

Also occurs on Goals, Widgets, Help links in menu too

**Comment by tsteur** [comment]
Thx for the report!

**Comment by petersj77** [comment]
Still seeing this in 2.11.1 after upgrading from 2.11

**Comment by tsteur** [comment]
Can you clear your browser cache and test it again?

**Comment by petersj77** [comment]
Still happens after clearing the cache in Chrome or IE11
