### ISSUE TITLE
Support for multiple idSites inside synced tracker

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#7257]
I'm posting this issue as a followup of this [forum thread](http://forum.piwik.org/read.php?2,113595,page=1#msg-124236) 

> would be an idea setting multiple IdSite in the asyncronous tracker?
> I mean for example using an object: ``` _paq.push( { 'setSiteId' : [ 6, 8, 16 ] } ); ```

**Comment by mattab** [comment]
Thanks @tassoman for the suggestion. 

It would be a good thing to let users do it this way in the tracker. we could then simplify the [Multiple Piwik trackers](http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers) use case.

**Comment by dzincolorado** [comment]
Hi,

Is there timeline for when this may be fixed?  It would be amazing to be able to pass an array of idSites into the tracker.

Thanks!
Denis

**Comment by anthonystocco** [comment]
hello
I need also this feature. I hope to provide it to the piwik community.
is there a specification explaining the processus from the tracker until writting on database piwik?

thanks

**Comment by tassoman** [comment]
My organization is concerned about using the declaration of **window.piwikAsyncInit()** rather than the new way of _paq[] array definition. Is planned to deprecate it?
Is planned to get this feature request done before definitive synchronous tracker deprecation?

**Comment by mattab** [comment]
This has been implemented in https://github.com/piwik/piwik/pull/10085
and will be later documented: Document new way to easily send tracking requests to multiple Piwik servers and/or multiple websites ID #10174
