### ISSUE TITLE
No CSS when using Firefox Nightly

### ISSUE THREAD

**Issue by mh00h** [piwik/piwik#7259]
There is no CSS loaded when using Firefox Nightly. Piwik should detect that the browser is Firefox regardless of the version and load the appropriate CSS.

Firefox 38.0a1 (2015-02-16)

**Comment by sgiehl** [comment]
I'm not able to reproduce. Just download friefox nightly for windows. CSS on a local piwik instance as well as on demo.piwik.org is loading all fine.
Did you try to view demo.piwik.org? Do you have any adblockers installed?

**Comment by mh00h** [comment]
That was it.
