### ISSUE TITLE
Date Range Selector partially hidden in Dashboard

### ISSUE THREAD

**Issue by ldidsbury** [piwik/piwik#7261]
I hope this is not a repeat...did a quick search and did not find it...

The date range selector that is part of the div class top_controls is partially hidden underneath the website selector control...this is the behavior in default Morpheus theme and the others...in Chrome and IE11.

Here is a screenshot of the overlap:
![image](https://cloud.githubusercontent.com/assets/2789891/6311963/522b11b4-b931-11e4-9172-dcb23b52c905.png)

I found when I added the style parameter display:-webkit-box using Chrome dev tools it fixes the overlap on this page at least...not sure if that helps but here is a screenshot of that fix within the browser:

![image](https://cloud.githubusercontent.com/assets/2789891/6311956/28445072-b931-11e4-8311-351ccd9938d3.png)

**Comment by tsteur** [comment]
Thx for the report! I'm working on a fix. Can't use `*-box` as `moz-box` leads to a weird result on Firefox. 

Nice theme by the way

**Comment by tsteur** [comment]
Fixed in https://github.com/piwik/piwik/commit/54b4d65e0c164cc803dc4d4ad420ce6deb98f86d
