### ISSUE TITLE
Warning - imagecopyresampled() expects parameter 2 to be resource

### ISSUE THREAD

**Issue by palleroy0** [piwik/piwik#7264]
I received this message after upgrading to 2.11.0 and adding a custom logo.  The image failed to validate with `pngcheck`.  It must have gotten corrupted during conversion.  Uploading random files with non-`.png` suffixes did not produce the error.  I labeled a `.jpg` with `.png` and produced the error.

Verifying the image was a valid PNG fixed any issue.

>WARNING CoreAdminHome[2015-02-19 04:42:12] [fcf03] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(223): Warning - imagecopyresampled() expects parameter 2 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
>WARNING CoreAdminHome[2015-02-19 05:03:38] [01db7] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(202): Warning - imagecreatefrompng(): '/tmp/phpEfv0yj' is not a valid PNG file - Piwik 2.11.0 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)

Putting the `.png` suffix on a text file generated other errors.

>WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(221): Warning - imagecolortransparent() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(223): Warning - imagecopyresampled() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(224): Warning - imagepng() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(220): Warning - imagecolorallocate() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(217): Warning - imagesavealpha() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(211): Warning - Division by zero - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(213): Warning - imagecreatetruecolor(): Invalid image dimensions - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(216): Warning - imagealphablending() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(202): Warning - imagecreatefrompng(): '/tmp/phpB7EnAK' is not a valid PNG file - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

http://forum.piwik.org/read.php?2,124339,124384

**Comment by mattab** [comment]
Thanks @palleroy0 for the suggestion, we could improve the messaging to make it clear to user that the image had an invalid format.
