### ISSUE TITLE
Error about whois.com timeout

### ISSUE THREAD

**Issue by jacobshare** [piwik/piwik#7265]
Just upgraded to 2.11.0 this morning and now the dashboard is showing this:

![whois timeout error](https://cloud.githubusercontent.com/assets/6898100/6319088/ebc8cdce-bab8-11e4-9d24-2158739066ea.png)

Whois.com works fine though.

Any ideas?

Jacob

**Comment by jacobshare** [comment]
Could this be related to the fact that I'm still on PHP 5.3?

**Comment by mattab** [comment]
Hi @jacobshare 
Thanks for the report. it's not to do with PHP 5.3.  I'm wondering what is the best way to handle this situation... ping @mnapoli

**Comment by mnapoli** [comment]
Could it be that your server can't access whois.com? (e.g. a firewall? DNS config?…)

It's normal that the warning is shown in case Piwik can't contact a SEO stats provider (since #7153).

**Comment by jacobshare** [comment]
The warning is no longer appearing today. I upgraded yesterday to 2.11.1 but I can't say for sure if the warning disappeared before or after the upgrade. That was the only change I made manually on the server since opening this issue but since I'm hosting on AWS, this might have also been network-related.

I'll reopen this if it happens again
