### ISSUE TITLE
API on Dimension Week/Month/Year don't work on CustomVariables.getCustomVariablesValuesFromNameId

### ISSUE THREAD

**Issue by approached** [piwik/piwik#7272]
Hi@all,

i tried to use Dimension **Week/Month/Year** on **CustomVariables.getCustomVariablesValuesFromNameId** but it still don't works. I have every time response with empty arrays.

Request URL:
http://exmaple.com/index.php?module=API&method=CustomVariables.getCustomVariablesValuesFromNameId&token_auth=MYTOKEN&idSite=1&period=year&format=json&language=de&idSubtable=2&segment=customVariablePageValue1%3D%3D7&date=2014-02-22,2015-02-22

Only dimension **day** work it.

**Comment by mattab** [comment]
Hi @approached if you use `idSubtable` then you must first call the `CustomVariables.getCustomVariables` for `week` or `month` etc. and then call `CustomVariables.getCustomVariablesValuesFromNameId` - the idSubtable will be different for day VS week VS month etc.
