### ISSUE TITLE
Piwik 2.9.1 Array to string conversion in TrackerCodeGenerator.php

### ISSUE THREAD

**Issue by mouyse** [piwik/piwik#7273]
Reported at piwik forum also:
http://forum.piwik.org/read.php?2,124494

<div style='word-wrap: break-word; border: 3px solid red; padding:4px; width:70%; background-color:#FFFF96;'>
        <strong>There is an error. Please report the message (Piwik 2.9.1)
        and full backtrace in the <a href='?module=Proxy&action=redirect&url=http://forum.piwik.org' target='_blank'>Piwik forums</a> (please do a Search first as it might have been reported already!).<br /><br/>
        Notice:</strong> <em>Array to string conversion</em> in <strong>/home/user/public_html/piwik/core/Tracker/TrackerCodeGenerator.php</strong> on line <strong>137</strong>
<br /><br />Backtrace --&gt;<div style="font-family:Courier;font-size:10pt"><br />
#0  Piwik\Error::errorHandler(...) called at [:]<br />
#1  str_replace(...) called at [/home/user/public_html/piwik/core/Tracker/TrackerCodeGenerator.php:137]<br />
#2  Piwik\Tracker\TrackerCodeGenerator->generate(...) called at [/home/user/public_html/piwik/plugins/SitesManager/API.php:93]<br />
#3  Piwik\Plugins\SitesManager\API->getJavascriptTag(...) called at [:]<br />
#4  call_user_func_array(...) called at [/home/user/public_html/piwik/core/API/Proxy.php:211]<br />
#5  Piwik\API\Proxy->call(...) called at [/home/user/public_html/piwik/core/API/Request.php:216]<br />
#6  Piwik\API\Request->process(...) called at [/home /user/public_html/piwik/plugins/API/Controller.php:33]<br />
#7  Piwik\Plugins\API\Controller->index(...) called at [:]<br />
#8  call_user_func_array(...) called at [/home/user/public_html/piwik/core/FrontController.php:582]<br />
#9  Piwik\FrontController->doDispatch(...) called at [/home/user/public_html/piwik/core/FrontController.php:96]<br />
#10  Piwik\FrontController->dispatch(...) called at [/home/user/public_html/piwik/core/dispatch.php:36]<br />
#11  require_once(...) called at [/home/user/public_html/piwik/index.php:46]<br />
</div><br />
 </pre></div>

**Comment by mattab** [comment]
Hi @mouyse thanks for the report. I can't reproduce this bug. Can you explain how to reproduce this? do you use any custom plugin maybe?

**Comment by mouyse** [comment]
I am trying to get a tracking code using __SitesManager.getJavascriptTag__ method. After calling it, I receive the above code plus __result__ like below:

<div style='word-wrap: break-word; border: 3px solid red; padding:4px; width:70%; background-color:#FFFF96;'>
        <strong>There is an error. Please report the message (Piwik 2.9.1)
        and full backtrace in the <a href='?module=Proxy&action=redirect&url=http://forum.piwik.org' target='_blank'>Piwik forums</a> (please do a Search first as it might have been reported already!).<br /><br/>
        Notice:</strong> <em>Array to string conversion</em> in <strong>/home/user/public_html/piwik/core/Tracker/TrackerCodeGenerator.php</strong> on line <strong>137</strong>
<br /><br />Backtrace --&gt;<div style="font-family:Courier;font-size:10pt"><br />
#0  Piwik\Error::errorHandler(...) called at [:]<br />
#1  str_replace(...) called at [/home/user/public_html/piwik/core/Tracker/TrackerCodeGenerator.php:137]<br />
#2  Piwik\Tracker\TrackerCodeGenerator->generate(...) called at [/home/user/public_html/piwik/plugins/SitesManager/API.php:93]<br />
#3  Piwik\Plugins\SitesManager\API->getJavascriptTag(...) called at [:]<br />
#4  call_user_func_array(...) called at [/home/user/public_html/piwik/core/API/Proxy.php:211]<br />
#5  Piwik\API\Proxy->call(...) called at [/home/user/public_html/piwik/core/API/Request.php:216]<br />
#6  Piwik\API\Request->process(...) called at [/home /user/public_html/piwik/plugins/API/Controller.php:33]<br />
#7  Piwik\Plugins\API\Controller->index(...) called at [:]<br />
#8  call_user_func_array(...) called at [/home/user/public_html/piwik/core/FrontController.php:582]<br />
#9  Piwik\FrontController->doDispatch(...) called at [/home/user/public_html/piwik/core/FrontController.php:96]<br />
#10  Piwik\FrontController->dispatch(...) called at [/home/user/public_html/piwik/core/dispatch.php:36]<br />
#11  require_once(...) called at [/home/user/public_html/piwik/index.php:46]<br />
</div><br />
 </pre></div>
<br />
<?xml version="1.0" encoding="utf-8" ?>
<result>&lt;!-- Piwik --&gt;
&lt;script type=&quot;text/javascript&quot;&gt;
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
.....
.....
....
...
...
..
.
&lt;!-- End Piwik Code --&gt;
</result>

**Comment by tsteur** [comment]
Can you let us know how you call it? 

I presume you are using the API?  Can you maybe post the URL that you to use here? Do not forget to remove the parameter `token_auth` if set.

**Comment by mouyse** [comment]
Yes, I am using the API.
And this is my code. 

```php

$p['module'] = "API";
$p['format'] = "xml";
$p['siteName'] = SITE_NAME;	
$p['urls'] = URL;
$p['method'] = "SitesManager.getJavascriptTag";
$p['idSite'] = SITEID;

$url = "http://analytics.connectedforlife.in/index.php?"  . http_build_query($p);
$url .= "&token_auth=TOKEN_AUTH";

$fetch_data = file_get_contents($url);

**Comment by mattab** [comment]
@mouyse can you reproduce this in 2.12.1, or on the Piwik demo? it seems to work there: http://demo.piwik.org/index.php?module=API&method=SitesManager.getJavascriptTag&format=xml&url=http%3A%2F%2Fwww.xxxxxxx.com&idSite[0]=3&token_auth=

**Comment by mattab** [comment]
please re-open if you can reproduce, we will fix it
