### ISSUE TITLE
during core:update display SQL queries as they are executed 

### ISSUE THREAD

**Issue by futureweb** [piwik/piwik#7276]
Hi,

we got a pretty large Piwik DB - and DB Updates on Piwik Updates often takes several hours to complete ... It would be VERY HELPFUL if the CLI Update Script (console core:update) would show some information on progress ...
I know it's not possible to output estimated time left ... but you could output something like

"14 out of 147 Queries finished"
"15 out of 147 Queries finished"
"16 out of 147 Queries finished"

Would be a good feeling to see there is some progress while waiting a few Hours for the Script to complete ... ;-)

Thank you, bye from Austria
Andreas Schnederle-Wagner

**Comment by gaumondp** [comment]
+1 , I almost kill an upgrade a month ago because I wasn't sure it was still running...

Hopefully I opend a second SSH session and used "htop" and saw the script running.

Going 2.7 to 2.11 for a 14 GB database took 36 minutes (8 GB, 2 CPU MySQL-only server) CPU at 40% while updating. 

How large is your DB @futureweb ?

**Comment by mattab** [comment]
Hi guys, thanks for the suggestion. It's a must-have and we will implement it in the next few months.

**Comment by futureweb** [comment]
Hey Matthieu,

sounds good - thx for picking up my idea so fast! ;-)
@gaumondp: DB is about 32GB ... and update from 2.10 --> 2.11.1 took something between 1 and 2 Hours ... so I'm afraid everytime a DB Update is coming towards me ...

Andreas

**Comment by samgabriel** [comment]
Hi guys, Can you please stop updating the piwik_log_visits and piwik_log_link_visit_actions These tables are huge on any normal high traffic site. It would be much better to create a new table and do a 1:1 mapping. The cost on inserting into multiple tables cannot justify being down for 8 hours while the update is completing which is what is happening in our case now. 
Doing an update from 2.4.0 to 2.11.0 so far has taken about 8 hours for the alter column statement. Yesterday we were updating from 2.2 to 2.3 which also took about 8 hours to update the piwik_log_action table.

**Comment by mattab** [comment]
@samgabriel currently such DB schema changes are blocked, see issue https://github.com/piwik/piwik/issues/6953

**Comment by mattab** [comment]
Btw I think it already works to do `core:update --verbose` to see which SQL queries are being executed

**Comment by diosmosis** [comment]
That doesn't tell you the progress, and it shows every SQL statement Piwik uses, including statements that are irrelevant to the update. Nor is the output particularly easy to read.
