### ISSUE TITLE
 curl_exec: Operation timed out after 9984 milliseconds with 6716088 out of 13344050 bytes received. Hostname requested was: builds.piwik.org

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7280]
Reported on [this forum post](http://forum.piwik.org/read.php?8,124491)

The goal of this issue is to increase timeout to leave more time to the Piwik servers to download the latest release.

**Comment by roots84** [comment]
30 seconds didn't work out on our server. I had to change it to 120s to make it work

**Comment by mnapoli** [comment]
@mattab any opinion on making the timeout 120s? It seems a bit high to me (with the risk of users thinking the app is crashed) but if it's really necessary why not.

**Comment by diosmosis** [comment]
It might be possible to create a downloader that downloads in the background using CliMulti, (ie start a download in a CliMulti process then the UI sends AJAX requests to an API method that inspects the CliMulti process output to get the percent done). Might require some modifications to CliMulti.

**Comment by mattab** [comment]
it's kinda expected that not all servers can download ~13mb in 30s (433kb/s). If we assume a server can only download 100kb/s then it would make sense to increase timeout to 130s (whether downloading zip or tar.gz)

Also, it may make sense that instead of having piwik instances download the `.zip` package which is currently 13mb, we would change to download `.tar.gz` which is 9.5Mb (25% less)

**Comment by mnapoli** [comment]
It is now 120s!

**Comment by roddyofchina** [comment]
hello,  my pwiki verion is 2.13.1 , now I met this problem. Modify code for 120s .The problem is not solved.

**Comment by mattab** [comment]
Hi @roddyofchina do you mind creating a new issue here, and pasting the error message you got, or a screenshot maybe? we will investigate, thanks
