### ISSUE TITLE
DB as doubled in size after upgrade from 2.7 to 2.11

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#7281]
Piwik 2.11.b3
PHP 5.3.13
Updated from command line.

Single Piwik instance with 6 web sites, about 2.5 millions pageviews a month. 

Since the update mid-January, my Reports Table has double : 

![image](https://cloud.githubusercontent.com/assets/5972510/6336561/74388baa-bb71-11e4-9e65-8c27c2b08997.png)

Matt suggested I open a bug report in Forum.

**Comment by PatrickChen** [comment]
gaumondp, this sounds like the same problem myself and some others have encountered. There's another issue open here: https://github.com/piwik/piwik/issues/7181 and some context on the forum: http://forum.piwik.org/read.php?2,123852

**Comment by mattab** [comment]
Thanks for the report! can you please post comment and screenshot in #7181

cheers
