### ISSUE TITLE
Error after 2.11.1 upgrade: Unable to find the wrapper "https"

### ISSUE THREAD

**Issue by surfi2000** [piwik/piwik#7282]
WARNING Installation[2015-02-23 23:31:29] [d8e5c] /var/apache/sites/piwik/core/Http.php(408): Warning - file_get_contents(https://hostname/index.php?module=Installation&amp;amp;action=getEmptyPageForSystemCheck): failed to open stream: No such file or directory - Piwik 2.11.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

WARNING Installation[2015-02-23 23:31:29] [d8e5c] /var/apache/sites/piwik/core/Http.php(408): Warning - file_get_contents(): Unable to find the wrapper &amp;quot;https&amp;quot; - did you forget to enable it when you configured PHP? - Piwik 2.11.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by mattab** [comment]
Hi @surfi2000 see this FAQ: http://piwik.org/faq/troubleshooting/faq_177/
