### ISSUE TITLE
visitor-map.js calculating wrong height

### ISSUE THREAD

**Issue by lucasHSA** [piwik/piwik#7284]
Hi,

i'm using the UserCountryMap-Widget as IFrame on our page. But on the bottom of the frame, there are some pixels hidden. 

# How to reproduce the bug

1. Open the UserCountryMap on a new window. [Like this](https://demo.piwik.org/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserCountryMap&actionToWidgetize=visitorMap&idSite=3&period=week&date=2015-02-18&disableLink=1&widget=1)

2. Reduce the height of the window, until the map fills the whole window

3. You will miss some pixels on the bottom of the window and a scrollbar will appear

4. Now you can change the height and width of the window and the count of the missing pixels will stay the same. If you change the height or width, the map has to fill the whole window.

Scrollbar appears:
![map-scrollbar](https://cloud.githubusercontent.com/assets/5647101/6345044/0d924a72-bc01-11e4-8b70-74177d458f7d.png)

Changed the width of the window, scrollbar stays:
![map-scrollbar-large](https://cloud.githubusercontent.com/assets/5647101/6345048/1820f9c0-bc01-11e4-8ec2-95e95f33c3f3.png)

Changed the width and the height of the window, scrollbar stays:
![map-scrollbar-largest](https://cloud.githubusercontent.com/assets/5647101/6345050/1b53f304-bc01-11e4-8829-d17987087b01.png)

# How to fix
Line 1220 of the [visitor-map.js](https://github.com/piwik/piwik/blob/master/plugins/UserCountryMap/javascripts/visitor-map.js):
```javascript
maxHeight = $(window).height() - (this.theWidget && this.theWidget.isMaximised ? 150 : 79);
```
window.height - 79 is not enough. I think the 79px are for the action- and controll-buttons on the bottom of the widget. 
**But** you also need to calculate with the margin of the `<div class="widget">` and `<div class="UserCountryMap dataTable"...>`:

![inspektor](https://cloud.githubusercontent.com/assets/5647101/6345150/92743826-bc02-11e4-939e-bea90a8e3677.png)

The div with the class=*widget* has margin-top: 10px and margin-bottom: 10px
The div with the class=*UserCountryMap dataTable* has a margin-bottom: 9px

The border of the div with the class=*widget* is 1px and already subtracted in Line 1225:
```javascript 
map.container.height(h - 2);
```

So line 1220 should look like this:
```javascript
maxHeight = $(window).height() - (this.theWidget && this.theWidget.isMaximised ? 150 : 108);
```
And the result would be, no scrollbar:
![map-fixed](https://cloud.githubusercontent.com/assets/5647101/6345216/b0b89d58-bc03-11e4-9d65-39721c48e41d.png)

**Comment by mattab** [comment]
Hi @lucasHSA 

Thanks for the research into this bug! Would you mind [creating a pull request](http://developer.piwik.org/guides/contributing-to-piwik-core#contribution-process) with the change? it would help us include it in Piwik faster... cheers
