### ISSUE TITLE
login screen weirdness since upgrade to 2.11.1

### ISSUE THREAD

**Issue by ArnY** [piwik/piwik#7287]
I just upgraded to piwik 2.11.1 (from 2.10) and the login screen now looks like this (in chrome 40 & firefox 35.0.1 on linux):

![piwik-loginscreen-2 11 1](https://cloud.githubusercontent.com/assets/138363/6351479/4be5888a-bc3c-11e4-9379-a46be07d195c.png)

Doubt this is intentionnal.

**Comment by sgiehl** [comment]
Have you tried cleaning piwiks tmp folder?

**Comment by ArnY** [comment]
I just did. No change.

**Comment by sgiehl** [comment]
Do you have any custom plugins installed?

**Comment by ArnY** [comment]
LoginLdap breaks the login screen. Will open a bug there instead. Thanks for pointing the plugins to me.
