### ISSUE TITLE
Open Page Overlay

### ISSUE THREAD

**Issue by aldrichkahla** [piwik/piwik#7288]
I am trying to do the Open Page Overlay function for a 3 month time period. However, Piwik will not even load the webpage for one day. It was "loading" for about 6 hours yesterday and it still did not finish.

**Comment by mattab** [comment]
Hi @aldrichkahla 

please check the Page Overlay troubleshooting: https://piwik.org/docs/page-overlay/#page-overlay-troubleshooting

if you still have an issue let us know and maybe post a screenshot.
