### ISSUE TITLE
Notifications created by warning logs are not displayed on the page the warning occurs

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#7289]
If a warning log occurs in an XHR request, a notification will be created, but it will not be displayed until the user either reload the page or goes to another page. This can cause some confusion.

Also these notifications should be able to be closed.

**Comment by mnapoli** [comment]
> Also these notifications should be able to be closed.

Done.

**Comment by mnapoli** [comment]
I don't really know how to solve the first problem though.
