### ISSUE TITLE
Unique visitors and Visits since 2.11.0 almost the same

### ISSUE THREAD

**Issue by tohn** [piwik/piwik#7290]
We updated Piwik on friday to 2.11.0 and yesterday to 2.11.1.
Today we noticed, that the unique visitors and visits are almost the same (the difference is below 10), but before it was around 600.
![screen shot 2015-02-24 at 18 21 24](https://cloud.githubusercontent.com/assets/427159/6354814/363ed944-bc52-11e4-8cc7-14cb7015f9ab.png)
Is it a bug or are we just loosing visitors? ;-)
We don't know if this helps, but we just added this to our config: http://piwik.org/faq/general/#faq_36

Thanks in advance for any help!

**Comment by quba** [comment]
I think you might be right. We can see it also on demo page:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=VisitsSummary&action=index&idSite=7&period=day&date=yesterday

**Comment by mattab** [comment]
Thanks for the report! I don't understand why tests didn't detect this bug.

**Comment by mattab** [comment]
I need to check on production that it's fixed

**Comment by mattab** [comment]
It wasn't properly fixed, now it should be fine. Will publish new beta and test on demo

**Comment by bcumberledge** [comment]
Is there a plan to fix the bad data?  Also, some have reported due to this the tables storing reports are much larger than usual.  I assume it is related and could use some cleanup also?

**Comment by mattab** [comment]
Bug has been fixed, please use the latest beta version to get your Piwik fixed.

@bcumberledge unfortunately there is no plan nor is it possible to fix the bad data. 
The other issue you mention is a different bug: #7181

**Comment by bcumberledge** [comment]
Piwik UI is not finding 2.11.2 as a beta release.   It says 2.11.1 is the latest.

**Comment by mattab** [comment]
@bcumberledge go to Administration, click on the top right box, click "Check for updates" -> does this work?

**Comment by bcumberledge** [comment]
I tried both options, latest stable and beta.   Both says I have the latest 2.11.1.  This was not an issue before so it is either an issue in 2.11.1 or with 2.11.2.

**Comment by bcumberledge** [comment]
@mattab  You mentioned not possible to fix the bad data.   Is it possible to get a query to delete all the data from those days from all visitor related tables?   Right now, the dashboard won't load for any of those days at all.  Also, the db is now about 500MB larger than it should be also.   So their is data but it is doing nothing but taking up space.

**Comment by mattab** [comment]
no it's not  possible, there was no extra data created so no extra data to delete. the bug was that the `id visitor` was set incorrectly and different for each visit instead of being read/persisted in the first party cookie. 

The fact that the DB is larger is a different bug: #7181
The fact that the dashboard doesn't load is also a different bug but not sure which one (check your server error logs)
