### ISSUE TITLE
Email address hel*lo@mail.com should be accepted as valid

### ISSUE THREAD

**Issue by AlexGanzer** [piwik/piwik#7298]
Hello.
I'm trying to register a user with email "hel*lo@mail.com" using the Piwik's API. The API responses with following error:
```javascript
 'result' => 'error'
 'message' => 'The email doesn't have a valid format.'
```

According to specs (http://tools.ietf.org/html/rfc5322#section-3.4 , http://tools.ietf.org/html/rfc2822#section-3.2.4) email address "hel*lo@mail.com" is valid.

Can you change email validator according specs?

**Comment by mattab** [comment]
Hi @AlexGanzer thanks for the report!

**Comment by ArnY** [comment]
There is really no point trying to validate an email address beside just checking the presence of the @ character and at least one dot after.
```
[^@]+@[^\.]+\..+
```
should be enough

**Comment by AlexGanzer** [comment]
You can use Zend_Validate_EmailAddress. It is written by specs. Zend_Validate_EmailAddress class already exist in Piwik code.
