### ISSUE TITLE
Log import - Replay tracking does not work if js/tracker.php was used

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7300]
Example log line

```
000.00.00.00 - - [09/Feb/2015:00:12:26 +0000] "GET /js/tracker.php HTTP/1.1" 200 15053 "http://www.example.org" "Mozilla/5.0 (X11; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0 FooBar/3.7.0.10"
```

I think the problem is that it tests here for `piwik.php`: https://github.com/piwik/piwik/blob/2.11.1/misc/log-analytics/import_logs.py#L2017

**Comment by diosmosis** [comment]
NOTE: the log file in the ticket desc. will still fail to import because /js/tracker.php has no query string. The tracking request has to be there, ie, `?idsite=1&action_name=whatever`.
