### ISSUE TITLE
Image export is scaled wrong 

### ISSUE THREAD

**Issue by DaSchTour** [piwik/piwik#7303]
I hope there isn't a lot more to say, the picture should be enough to show how the problem looks like
![2015-02-26 at 10 38](https://cloud.githubusercontent.com/assets/1907266/6389351/a7ce99a8-bda3-11e4-8235-2eaae251300a.png)

**Comment by mattab** [comment]
Hi @DaSchTour, thanks for reporting the issue.

**Comment by mattab** [comment]
@DaSchTour can you reproduce this on the http://demo.piwik.org/ ? which browser/ OS are you using? so far it seems to work for me in FF, Chromium on ubuntu.

**Comment by sgiehl** [comment]
Not able to reproduce that on Windows  IE11 / Chrome or Firefox

**Comment by mattab** [comment]
@sgiehl FYI added `Waiting for user feedback / Cannot reproduce yet` new label

**Comment by sgiehl** [comment]
This one was already fixed with #11557.
