### ISSUE TITLE
Maximum CPU execution time exceeded during upgrade

### ISSUE THREAD

**Issue by djvanenckevort** [piwik/piwik#7304]
I get the following error when I try the automatic update of Piwik to version 2.11.1:

is_dir(): Maximum cpu execution time of 15 seconds exceeded in /sites/vanenckevort.net/www/analytics/core/Filesystem.php 349 using PHP 5.4.16 

After a refresh I get:

is_dir(): Maximum cpu execution time of 15 seconds exceeded in /sites/vanenckevort.net/www/analytics/vendor/piwik/decompress/libs/PclZip/pclzip.lib.php 5004 using PHP 5.4.16 

I got the same error when I did the update from 2.10.x to 2.11.0, so this is something I have seen before. I am running Piwik on the TransIP (http://www.transip.nl/) hosting platform.

**Comment by mnapoli** [comment]
What is weird is that both time it was stuck on the `is_dir()` function, which makes not a lot of sense. Maybe you could try contacting your host about that, they maybe have a specific setup regarding the filesystem… In any case I don't think there is much we can do here, 15 seconds timeout is really low, and I'm pretty sure we try to disable the timeout anyway for the upgrade.

Actually I did a quick search and yes we do: https://github.com/piwik/piwik/blob/master/plugins/CoreUpdater/Controller.php#L306-306

**Comment by djvanenckevort** [comment]
The hosting provider says that they have disabled changing the timeout and suggest to split up the process in several separate steps. I don't know if this would be possible.

The hosting provider claims to use SSD only on the hosting platform, which might still be considered non-standard, but should be faster than normal disks.

**Comment by mattab** [comment]
Thanks for the report. Unfortunately there's not much we can do about this. If anyone else experience the issue please leave a comment

**Comment by mattab** [comment]
This is what we could do about it:  Piwik updater: Add support for delta updates #8327
