### ISSUE TITLE
All Websites dashboard: Sorting of the websites is not correct

### ISSUE THREAD

**Issue by twodrunkbots** [piwik/piwik#7314]
Hi

Since we updated Piwik from 2.10.0 to 2.11.1 the sorting of the All Websites dashboard is not working correctly.

The websites in the All Websites dashboard are sorted by the Site ID, not by visits.
The strange thing is, the websites are sorted in two "groups":
First "group", the websites with visits>0 are sorted by Site ID, then the websites with visits=0 are sortet by Site ID. See screenshots: 

![sorting1](https://cloud.githubusercontent.com/assets/11195517/6408815/5ab97e36-be5b-11e4-8d79-b975d4c164e4.png)

![sorting2](https://cloud.githubusercontent.com/assets/11195517/6408817/5ea73a2e-be5b-11e4-981a-14ba00855686.png)
(above: The number in the name is the same as the site ID)

![sorting3](https://cloud.githubusercontent.com/assets/11195517/6408962/0d903616-be5d-11e4-80cf-365bf7004c7f.png)
(above: I added the site ID (red text) with Paint)

We are not using the WebsiteGroups plugin for Piwik pro. We wrote an own plugin to add new websites to a specific group.

Thanks for your help
Steven

**Comment by mattab** [comment]
Thanks for the report. Could you try to enable the WebsiteGroups plugin, maybe it fixes the issue already as a workaround? if not, let me know we will investigate :+1:

**Comment by twodrunkbots** [comment]
Hi Matt

Thanks for your answer.
I now have updated Piwik from 2.11.1 to 2.12.1 and the bug is gone.
--> Now The All Websites dashboard sorts all websites correctly.
So there is no need to enable the WebsiteGroups plugin.

I don't know if this bug was only in our Piwik environment?

**Comment by mattab** [comment]
Great to hear that the bug is now fixed
