### ISSUE TITLE
Opt-out page doesn't take DNT into account

### ISSUE THREAD

**Issue by ArnY** [piwik/piwik#7317]
On a DNT enabled piwik instance, the opt-out page will still tell the user he/she is being tracked even though the user has DNT enabled.

The opt-out page shouldn't rely solely on the piwik_ignore cookie and should also take into account the DNT header sent by the user's browser. The page could let the user know that he/she isn't being tracked because of the DNT setting and not because he/she is explicitly excluded by piwik.

**Comment by mattab** [comment]
Hi @ArnY thanks for the feature suggestion, it would make a lot of sense indeed :+1:

**Comment by ArnY** [comment]
I'll make a pull request to change this but I am unsure on how to deal with new strings. Should I just make the change in the translations I'm familiar with ?

What's more, if a user has DNT enabled, the optout page can not suggest to opt in. So the whole form will be replaced by a message explaining that the user isn't being tracked because the browser reported the user wasn't willing to and since this is a browser setting the user will not be able to opt in as long as the setting is on.

**Comment by mattab** [comment]
Great to hear you consider writing a pull request!

you need to write the translation in English as well, but we can review it aftewards so don't worry.

btw An alternative to hiding the form could be to display the checkbox (un-checked) and grey it out with `" disabled="disabled"`  to show that it's not possible to opt-in.

**Comment by ArnY** [comment]
e3217a227d7f4f5376e63bf860487c84584052a0  uses class DoNotTrackHeaderChecker to check if DNT headers were sent. If so, the user gets a message explaining that his browser reported he/she didn't want to be tracked and that he/she can not opt in with DNT enabled. 

I chose not to display the form, even with the checkbox unchecked and disabled since the user will most probably not have the optout cookie so displaying an unchecked checkbox would lead the user to think that if he/she was to disable DNT he/she would be opted out by default. Which is false, they would be tracked by default.

**Comment by mattab** [comment]
> I chose not to display the form, even with the checkbox unchecked and disabled since the user will most probably not have the optout cookie so displaying an unchecked checkbox would lead the user to think that if he/she was to disable DNT he/she would be opted out by default. Which is false, they would be tracked by default.

Good point :+1:

**Comment by mattab** [comment]
@ArnY your change looks good! could you issue a pull request?

**Comment by mattab** [comment]
Well done @ArnY
