### ISSUE TITLE
How to set user id in plugin event hook 

### ISSUE THREAD

**Issue by shahar3012** [piwik/piwik#7322]
Hi, 
I'm writing a plugin that uses Kerberos authentication which gives me the user I want to set as the user id. 
I can't figure it out how to set the user id from within a plugin. 

I think I should do something like this:
$visitorInfo['uid'] = $_SERVER['REMOTE_USER'];

Note: **Piwik Web server does the authentication on every request.**

**Comment by tsteur** [comment]
Do you mind asking this question in our Platform forum http://forum.piwik.org/list.php?9 ? We usually don't answer support questions here. That'd be great!

**Comment by shahar3012** [comment]
Will you add a new setting for this? 
The administrator may have a new setting that can be check in order to activate the core function that sets the user id with the remote user in $_SERVER array on every visitor request to piwik http tracker.

**Comment by tsteur** [comment]
I don't think we will add a new setting. It should be already doable with a plugin. You're writing a plugin for Piwik right? Please ask in forum there are two ways to solve this I think. One of it is using our [events](http://developer.piwik.org/guides/events) `Tracker.newVisitorInformation` ([link](http://developer.piwik.org/api-reference/events#trackernewvisitorinformation)) and `Tracker.existingVisitInformation` ([link](http://developer.piwik.org/api-reference/events#trackerexistingvisitinformation))

**Comment by shahar3012** [comment]
Unfortunately, I couldn't get it working with the ldapvisitorinfo plugin. I used these events and sets the uid. I checked the database for any sign of uid successfully sets and I found no sign for that. Maybe it doesn't get saved and therefore the ldapvisitorinfo plugin can't fetch the data.

**Comment by tsteur** [comment]
If it doesn't work there are probably other solutions (creating a VisitDimension, it is not documented yet) but it is most likely supposed to work with events as well. Can you to ask in Forum please? If we identify there is a bug/missing feature we will create an issue here with a concrete example etc.
