### ISSUE TITLE
Duplicate url in API.getBulkRequest response

### ISSUE THREAD

**Issue by filipesaraiva** [piwik/piwik#7330]
Hello, first thanks for piwik.

I am trying to get data from two different urls, but the response sent is just for the last url, duplicated. See:

http://piwik.colivre.coop.br/piwik/index.php?module=API&method=API.getBulkRequest&format=xml&idSite=6&period=range&date=2015-01-01,today&urls[0]=method=Actions.getPageUrl&pageUrl=http://wsl.softwarelivre.org/2013/0004/&urls[1]=method=Actions.getPageUrl&pageUrl=http://wsl.softwarelivre.org/2013/0004/download/

Maybe is it a bug in my piwik version or my code is wrong?

**Comment by filipesaraiva** [comment]
I get the same problem with piwik demo website:

http://demo.piwik.org/?module=API&method=API.getBulkRequest&&idSite=7&format=xml&period=range&date=2015-01-01,today&urls[0]=method=Actions.getPageUrl&pageUrl=http://forum.piwik.org/&urls[1]=method=Actions.getPageUrl&pageUrl=http://forum.piwik.org/read.php?2,829

**Comment by mattab** [comment]
Hi @filipesaraiva 

you need to URL encode each URL query parameter `urls[0]` etc.

it looks like this:
```
http://demo.piwik.org/?module=API&method=API.getBulkRequest&&idSite=7&format=xml&period=range&date=2015-01-01,today&urls%5B0%5D=method%3DActions.getPageUrl%26pageUrl%3Dhttp%3A%2F%2Fforum.piwik.org%2F&urls%5B1%5D=method%3DActions.getPageUrl%26pageUrl%3Dhttp%3A%2F%2Fforum.piwik.org%2Fread.php%3F2%2C829
```
