### ISSUE TITLE
Unable to edit or delete goals?

### ISSUE THREAD

**Issue by CaptSaltyJack** [piwik/piwik#7338]
Is this not possible? Or am I missing something? How can we remove goals?

**Comment by CaptSaltyJack** [comment]
Never mind, found it in a really strange spot that's not particularly user friendly. It's under the main Settings, under Manage.

**Comment by tsteur** [comment]
You can as well click on a goal name btw.

**Comment by mattab** [comment]
I think we could improve this - created an issue:  Make it easier to see how to edit a Goal #7345

**Comment by Bugsbane** [comment]
Please... It took me 20 minutes of hunting around to find this, and I only got there by reading this issue report. The first place I looked was by going into the website, clicking and goals. WHen I didn't see edit / delete there, I tried clicking the goal names, but it just showed me the data for those goals and ways to further segment the view... but once again with no option to edit or delete the goal.

**Comment by mattab** [comment]
Hi @Bugsbane please comment on the open issue if you can: #7345

**Comment by dfranco** [comment]
Hi,
Sorry to bother you but I'm running latest version of Piwik (version 2.12.1) and I still can't find how to edit goals ... :(
Any help would be fully appreciated ;)
Best regards
Davide
