### ISSUE TITLE
Problem with ip adress , if use php api 

### ISSUE THREAD

**Issue by Alex-query** [piwik/piwik#7340]
require_once "PiwikTracker.php";
$ip=$_SERVER['REMOTE_ADDR'];
PiwikTracker::$URL = 'http://url/piwik/';
$piwikTracker = new PiwikTracker(1);
$piwikTracker->setIp($ip);
My solution, it`s in file IP.php en function getIpFromHeader()  add line $default = $_GET['cip'];

**Comment by mattab** [comment]
Hi @Alex-query,

When you use `setIp` you must also use `setTokenAuth` and then it will work. 

This is explained in: http://developer.piwik.org/api-reference/PHP-Piwik-Tracker#setip
