### ISSUE TITLE
Make it easier to see how to edit a Goal

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7345]
The goal of this issue is to make it easier for users to see how they can edit the Goal in Piwik. 

Here is a simple usability improvement idea:

 * in the Report for a particular goal ([eg. on demo](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=Goals&action=goalReport&idSite=7&period=day&date=yesterday&idGoal=2)) on hover on the top title (the Goal name) we could show, next to the two icons, a link `Edit goal`. 
  * this link would be the same effect as clicking on the title itself: load the `Manage Goals` screen.

Maybe you also have a suggestion?

**Comment by tsteur** [comment]
As long as it is not an icon...

**Comment by mattab** [comment]
i suggest `Edit goal` as it's clear and to the point. no icon for sure ;-)

**Comment by skpear** [comment]
yes, that's a good idea. Besides, text holding "Edit goal" is suffice and clear rather than having image to describe this action.

**Comment by saleemkce** [comment]
yes, that's a good idea. Besides, text holding "Edit goal" is suffice and clear rather than having image to describe this action.

**Comment by dfranco** [comment]
Hello everybody,
I think that would be a really good idea to improve this.
But meanwhile, does someone could tell me where can I edit my goals please (running version 2.12.1) ? 
Many thanks
Davide

**Comment by mattab** [comment]
Moved to 2.13.0

**Comment by tsteur** [comment]
Maybe it would also make sense to have at some point next to "Administration" and "User" a menu "Websites" or later maybe something like "Properties" or whatever we will call it once we also allow to manage Apps, Servers, ...

We did have a discussion that time where to put such menu items like "Goals" and "Tracking Code" (and later "Segments" etc) as they neither really belong to "Administration" nor "User" menu and it is confusing. 

Just a random thought as I remember one user saying he had a look under "Administration => Websites" first.

**Comment by dfranco** [comment]
Thanks for the feedback @mattab

**Comment by mnapoli** [comment]
PR: #7631

**Comment by Bugsbane** [comment]
I was asked to add my thoughts here after reporting on another bug how much difficulty I had in finding how to edit / delete goals.

In short, I expected to find the functionality easily visible once I clicked "Goals". I would expect to see something like a "Manage goals" or "Edit goals" link next to "Add a New Goal". I would also expect to see links under the individual goal title for "Delete this goal" and "Edit this goal".

Please don't make these invisible unless people happen to already know that they need to hover the cursor over a piece of text that doesn't even look like a link (the title). I'm quite sure I wouldn't have spotted that skimming over the page, looking for the "edit goal" link.

**Comment by mattab** [comment]
Maybe in Goals > Overview, at the bottom of the page we add a new title `Manage Goals` and below write the same text+link as in `Add goal` screen ie. `Goal Conversion tracking is one of the most efficient ways to measure and improve your business objectives.
Learn more about Tracking Goals in Piwik in the user documentation. Manage Goals or create a new Goal now! `

**Comment by mattab** [comment]
Maybe in Goals > Overview, at the bottom of the page we add a new title `Manage Goals` and below write the same text+link as in `Add goal` screen ie. `Goal Conversion tracking is one of the most efficient ways to measure and improve your business objectives.
Learn more about Tracking Goals in Piwik in the user documentation. Manage Goals or create a new Goal now! `

(show these when user has at least admin access to the current site)

**Comment by tsteur** [comment]
Wasn't this basically as it was before we removed it from there? I think that wasn't the best solution either. @Bugsbane suggested to add a menu link "Manage Goals" which goals be before "Add a new Goal". Reckon this would be most clear and visible.

**Comment by mnapoli** [comment]
New pull request: #7704
