### ISSUE TITLE
Description/Comment on Goals

### ISSUE THREAD

**Issue by DaSchTour** [piwik/piwik#7346]
I experienced a certain problem about goals while working in my company. As some users from the management also have access to Piwik they try to analyze the traffic on our website. We have a lot of goals defined to measure the usage of our website. This goals only have relatively short names and use a certain naming convention so that we as the developers know in witch part of our web application this goals are placed. But this short names often aren't as clear to everybody as we thought and this leads to recurring misinterpretation of the goals. So it would be very helpful if there was the possibility to create a detailed description for goals. I guess this shouldn't be a lot of work, but it would be a huge improvement in usability and collaborative usage of Piwik.

**Comment by mattab** [comment]
Hi @DaSchTour thanks for the suggestion! Where do you think this description should be displayed in the UI?

**Comment by DaSchTour** [comment]
In the single goal view it might be below the heading
![2015-03-04 at 10 24](https://cloud.githubusercontent.com/assets/1907266/6480887/c3f49786-c258-11e4-8739-1d6a5eeb9608.png)
And in the goal overview there might be something like a tooltip beside the goal or in the right space
![2015-03-04 at 10 26](https://cloud.githubusercontent.com/assets/1907266/6480927/2bad9526-c259-11e4-8398-aa0d5cb5f0e6.png)

**Comment by mattab** [comment]
Fixed in #10057
