### ISSUE TITLE
Running scheduled task with --force should run the tasks

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7351]
From #7181 a user reported:

> Just ran core:run-scheduled-tasks --force with the updated Rules.php file. This is the updated message:
> Purging temporary archives: skipped (no authorization)

That's a bug. likely in Rules.isRequestAuthorizedToArchive ?

**Comment by ThaDafinser** [comment]
I also experienced the DB growth (thought it was because of another error first).

It seems that it catched the new message i introduced here (same for me currently) https://github.com/piwik/piwik/pull/7305

Is there a bug i dont see from my PR?

**Comment by mnapoli** [comment]
> Purging temporary archives: skipped (no authorization)

is shown if browser archiving is disabled and `$_GET['trigger'] != 'archivephp'`.

When running in the console `$_GET['trigger']` is most probably empty, so if Piwik is using cron archiving you can't purge temporary archives…

Is that the intended behavior? Here is what the comment says, I can't understand it:

> we only delete archives if we are able to process them, otherwise, the browser might process reports when &segment= is specified (or custom date range) and would below, delete temporary archives that the browser is not able to process until next cron run (which could be more than 1 hour away)

**Comment by mnapoli** [comment]
Note the `--force` option just forces to run scheduled tasks (i.e. it applies only to the task scheduler).

Then each task has its own rules, I'm not sure it's easy to pass the concept of "--force" inside the actual logic.

**Comment by diosmosis** [comment]
@mattab No longer relevant at least for archive purging since there is a dedicated command for it now. Since `--force` does force running scheduled tasks, I think this issue can be closed.
