### ISSUE TITLE
Composer install fails for Piwik 2.10.0

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7353]
Due to change in https://github.com/piwik/component-cache/ repository now Piwik 2.10.0 cannot be installed.
Repository listed here https://github.com/piwik/piwik/blob/2.10.0/composer.json#L92 does not exist any more and composer install command fails.
Composer install output for referrence:

```
Installing doctrine/cache (dev-filecache-race-condition-fix c5a6d2a)
Cloning c5a6d2ade84241128fcf95eca386e07b11ffa347
                                                                                           
  [RuntimeException]                                                                       
  Failed to clone git@github.com:piwik/cache.git via git, https, ssh protocols, aborting.  
  - git://github.com/piwik/cache.git                                                       
    Cloning into '/private/var/www/piwik/master.piwik/vendor/doctrine/cache'...            
    fatal: remote error:                                                                   
      Repository not found.                                                                
  - https://github.com/piwik/cache.git                                                     
    Cloning into '/private/var/www/piwik/vendor/doctrine/cache'...            
    remote: Invalid username or password.                                                  
    fatal: Authentication failed for 'https://github.com/piwik/cache.git/'                 
  - git@github.com:piwik/cache.git                                                         
    Cloning into '/private/var/www/piwik/vendor/doctrine/cache'...            
    ERROR: Repository not found.                                                           
    fatal: Could not read from remote repository.                                          
                                                                                           
    Please make sure you have the correct access rights                                    
    and the repository exists. ```

**Comment by mattab** [comment]
Explanation: we used to maintain the doctrine/cache fork until they merged our patches/fixes upstream in their own git repo. Then we deleted our fork as we thought it wasn't useful anymore.

Suggested solution: could you modify the doctrine/cache in composer.json/lock and point instead to their latest release like it is done in our current composer?

**Comment by mnapoli** [comment]
Try to require Piwik 2.11 instead it should solve your problem?

**Comment by mgazdzik** [comment]
I believe that there are more drawbacks of this situation:
- we cannot setup locally 2.10.0 instance
- travis cannot run tests for this version (as it can't install Piwik)

Ability to setup any historical version is crucial for developers in matters of local debuging, investigations, plugin development, CI operation for older version, package building with composer, etc. Also not all instances can be updated to latest version over a day and it could be a serious problem I think.

I think that such situations shouldn't occur, as basically previous tags available on Git are useless without manual hacking in composer.json.
Having that said maybe for sake of old versions this fork could be restored and marked as deprecated or so, but builds would at least work?

**Comment by mnapoli** [comment]
@mgazdzik sorry didn't notice it was you :) I thought it was just someone requiring Piwik in Composer because they wanted to use the reporting API classes :wink:

**Comment by mnapoli** [comment]
I have recreated the fork with the branch taken from master: https://github.com/piwik/cache/tree/dev-filecache-race-condition-fix

Please let us know if it solves the problem.

**Comment by mgazdzik** [comment]
@mnapoli - thanks for recreating missing part. I confirm that composer install passes in 2.10.0 :+1:
