### ISSUE TITLE
Restrict tmp/* to 0770 instead of 0750 (make it group writable)

### ISSUE THREAD

**Issue by derSascha** [piwik/piwik#7354]
I am running piwik embedded into different virtual host, running as different users which are all members of a piwik group. This results in permission problems writing to tmp/* files.

Commit 6c6e5e9d11cc29c17341bd2e181a73c29dae5e6d / #5034 overwrites the umask settings and restricts the group write permission.

Might no big problem to allow group members to write on directories which they can already read.

**Comment by mattab** [comment]
Thanks for the report. let's continue the discussion in the PR:  #7355
