### ISSUE TITLE
Define what is a major database upgrade

### ISSUE THREAD

**Issue by mrjoops** [piwik/piwik#7357]
I have a heavy Piwik 2.10.0 install I wanted to upgrade to 2.11.2, so I looked at the changelog for the 2.11.* versions.
None of the 2.11.* versions mentionned a major database upgrade, so I started confidently the upgrade operation.
But then I saw the queries (one for each `archive_blob` table) : `UPDATE piwik_archive_blob_2015_03 SET name = 'UserLanguage_language' WHERE name = 'UserSettings_language';`

Actually, with a database of nearly 200GB, I think it is a quite major upgrade.
IMHO every upgrade operation that updates any of the `archive_blob`, `archive_numeric` and `log_visit` tables should be a major one.

I welcome your comments.

**Comment by mattab** [comment]
Hi @mrjoops 
A major database upgrade is a Schema altering on one of the `log_*` tables or `archive_*` tables. This UPDATE statement is definitely not a major DB upgrade, as it should complete within minutes at most. See also: #6953

**Comment by mrjoops** [comment]
Well, I don't know if 80 minutes fit in "within minutes at most"...

**Comment by mattab** [comment]
80 minutes is quite long indeed.. this issue will help get an idea: #7276
