### ISSUE TITLE
When UserID is set to empty string, actions maybe added to the same UserID visit

### ISSUE THREAD

**Issue by Glisse1** [piwik/piwik#7368]
Hello, I have this strange bug since upgrading to the latest point release: when opening a visitor profile it lists ALL visits and visitors (i believe from that day or so) instead of only the correct visits for each one.. also, when opening a visitor profile from say 5 hours ago, still shows even the latest visits of other visitors, occurred long after that one...when clicking individual visit #1, visit #2, etc the correct information appears  with different ip, browser, screen resolution, etc... so it does distinguish between visits.. its just that they are all crammed together.

**Comment by Glisse1** [comment]
It has gotten worse.. all of my visitors are now under the same visitID.
Symptom:

- a user joins my site, visitID let`s say #14611 is created. They browse several pages and leaves;
- later on completely another user joins my site, sees other pages.. but the session #14611 is continued from where it ended;
- and so on.

- to be sure i created myself several incognito visits in both chrome and firefox, both direct and via google search, which always were separated visitsID.. i know because i do that often to check things.. but now all of them continued that initial session.

- tried to clear the temp folder, did nothing to help :(

I now have a 4 hours long session with pageviews from at least 10 different unique visitors, from all over the country.. i can see them joining in google analytic real-time map... actually some of them are not registered at all in piwik, although they are actively browsing the site and viewing different pages according to GA (so are not bots)

A new session is created if a new user is on mobile tho.

All of these started last night when i updated to the latest point release 2.11.2

**Comment by quba** [comment]
Are you using standard Piwik tracking code or also some additional features?

**Comment by Glisse1** [comment]
only userID is added, whcih worked perfectly until last night.. my tracking code in theme footer:

<script type="text/javascript">
var _paq = _paq || [];
_paq.push(['setUserId', '<?php global $current_user;get_currentuserinfo();echo $current_user->user_login ;?>']);
_paq.push(['trackVisibleContentImpressions', true, 750]);
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);

(function() {
    var u="xxxxxx";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by quba** [comment]
I would say that it's connected with userId. Please make sure that you are passing there different userid for different users. If that's the case, then it's possible that we have here another bug.

**Comment by Glisse1** [comment]
My tracking code is unchanged for several months.. so there is nothing different on my end.. the thing is that most of the times (80 % of cases or so) there is no userID passed so it cant be different..that`s because the user is not logged-in, no username/email/etc to pass.. only when a user logs-in the userID is set and is recognized as such.. this is how it used to be, and if i recall correctly this is how it was meant to work.. if there is is a userID very good, it helps tracking the same user across different devices, if not, no problem, the old mechanism still works.

will investigate and remove userID and will follow-ip

**Comment by Glisse1** [comment]
Removed the userID from the tracking code and the bug is gone.. both the userprofile one, and the later.. 

So, this means that this feature is no longer available? It worked fine for several months..

**Comment by Glisse1** [comment]
Removed the userID from the tracking code and the bug is gone.. both the userprofile one, and the later..
So, this means that this feature is no longer available? It worked fine for several months..

**Comment by mattab** [comment]
Hi guys, I found the issue. Indeed there is a regression when the User ID is set to empty string. Before it wouldn't update the Visitor ID, but now it does. I've fixed it in this PR: https://github.com/piwik/piwik/pull/7402
