### ISSUE TITLE
en flag not found

### ISSUE THREAD

**Issue by approached** [piwik/piwik#7369]
Hi @all

I updated to 2.11.2 but now i have follow error:
```
"NetworkError: 404 Not Found - http://stats.example.com/plugins/UserCountry/images/flags/en.png"
```

**Comment by ThaDafinser** [comment]
Hmm...since 2 years there were no updates in the flag folder.

https://github.com/piwik/piwik/tree/master/plugins/UserCountry/images

**Comment by wolfgang42** [comment]
@ThaDafinser I don't think the problem lies in the flag folder - 'en' isn't a country!
@approached What page are you seeing the error on?

**Comment by ThaDafinser** [comment]
@wolfgang42 you are right. I was confused because there was a `de.png` ...but thats actually the country and not the language

**Comment by approached** [comment]
@wolfgang42 I see just nothing like a "no image" in browser.

**Comment by wolfgang42** [comment]
Is the nothing that you see in a spot where you would normally expect to
see a language, or a country?

**Comment by approached** [comment]
... a language

**Comment by mattab** [comment]
HI @approached could you post a screenshot showing where this image icon is trying to load?

**Comment by mattab** [comment]
@approached please reopen if you have more info, or if anyone else has this 404 error in the error log. we cannot reproduce so far
