### ISSUE TITLE
provider unknown

### ISSUE THREAD

**Issue by Hinnack** [piwik/piwik#7370]
I do not get any provider with anonymize IPs set to 2 bytes. But I get Cities and Countries via MaxMind db. 
Is gethostbyaddr called too late?

If this is a "feature" please add it here:
http://piwik.org/faq/general/faq_52/

**Comment by mattab** [comment]
Hi @Hinnack 

Can you confirm that you have selected `NO` here: ![privacy](https://cloud.githubusercontent.com/assets/466765/6517539/fccf4e8a-c400-11e4-9738-f521a225bcf0.png)

if you have selected NO, then provider lookup should be done on the RAW ip. then it should work. if it does not then it's a bug.

**Comment by mattab** [comment]
@Hinnack please re-open if you have an issue here.
