### ISSUE TITLE
Cannot click links in visitor-log-lightbox

### ISSUE THREAD

**Issue by cyberbeat** [piwik/piwik#7382]
To reproduce: 

- from the geo-ip-cities/region view click the icon to filter logs for that city/region
- a lightbox opens with the visitors log, and with links to the pages the visitors visited
- scroll down the list (important!)
- now try clicking a page-link: instead of opening the url, the page is scrolled to the top.

**Comment by mattab** [comment]
Thanks @cyberbeat for the report!

**Comment by cyberbeat** [comment]
When will this be fixed? The same problem appears even with middle-click or ctrl-click, no way to click the links.

**Comment by mattab** [comment]
Adding to 2.14.1 - @barbushin maybe you can take a look?
