### ISSUE TITLE
Document how to setup the auto travis update for Plugins

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7394]
The goal of this issue is to document (likely in [tests/README](https://github.com/piwik/piwik/blob/master/tests/README.md)) how, as a core developer / Piwik PRO developer, I can setup my plugin to be have its travis.yml "auto updated".

I noticed that our recent plugins don't have the auto update feature which means that on Monday the builds are not green (we aim for green builds in #6544) but they are in `Error` state. For example this build: https://travis-ci.org/PiwikPRO/plugin-CustomTrackerJs/jobs/50434158

This will greatly help having green builds!

**Comment by mnapoli** [comment]
This is documented here: http://developer.piwik.org/guides/tests-travis-extended (confusing because this is not the Travis guide, this is the Travis extended guide…)

**Comment by mattab** [comment]
removed the duplicated doc on the PRO wiki https://github.com/PiwikPRO/support/wiki/How-to-develop-PRO-plugins%3F#adding-plugin-builds-to-travis and slightly improved the wiki page: http://developer.piwik.org/guides/tests-travis-extended
