### ISSUE TITLE
curl_exec: Resolving timed out after 3153 milliseconds. Hostname requested was: plugins.piwik.org

### ISSUE THREAD

**Issue by ralflutz** [piwik/piwik#7395]
We get the error message:

curl_exec: Resolving timed out after 3153 milliseconds. Hostname requested was: plugins.piwik.org

after clicking the menu option "Marketplace" under Administration or under "Plugins" -> install new plugins.

We can resolve plugins.piwik.org at the cli of the system. Piwik 2.11.2 runs at Centos 7

**Comment by mattab** [comment]
Thanks for the report @ralflutz the timeout is now set to 10s which should work much better.
