### ISSUE TITLE
when sorting results, make the default secondary column sort 'nb_visits'

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7401]
The goal of this issue is that when a column is sorted in any report, and when two values are identical for this column, then the result will be sorted by a secondary column. Each report could decide which secondary column to sort by, but the default will be `nb_visits`. 

The current behavior is not ideal as the rows appear to be sorted randomly eg. when all values of the sorted column are `0`. [Example screenshot](http://builds-artifacts.piwik.org/ui-tests.master/10794.7/screenshot-diffs/singlediff.html?processed=../processed-ui-screenshots/UIIntegrationTest_ecommerce_sales.png&expected=UIIntegrationTest_ecommerce_sales.png&github=UIIntegrationTest_ecommerce_sales.png)

**Comment by diosmosis** [comment]
I think this is done by default when the data type is numeric. I might be remembering incorrectly, but for strings it doesn't do this, which caused problems for me during the processed metrics refactor.

**Comment by mattab** [comment]
Should be fixed with #8449
