### ISSUE TITLE
After preview of Widget live visitor profile, but not adding it to the dashboard, the calls keep on getting requested

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#7404]
These kind of calls are being done by the dashboard page after previewing the visitor profile widget.

/index.php?period=range&idSite=4&segment=&date=last30&format=json&showRawMetrics=1&module=API&method=Live.getLastVisitsDetails&filter_limit=100&showColumns=latitude%2Clongitude%2Cactions%2ClastActionTimestamp%2CvisitLocalTime%2Ccity%2Ccountry%2CreferrerType%2CreferrerName%2CreferrerTypeName%2CbrowserIcon%2CoperatingSystemIcon%2CcountryFlag%2CidVisit%2CactionDetails%2CcontinentCode%2Cactions%2Csearches%2CgoalConversions%2CvisitorId%2CuserId&minTimestamp=1425982961

After a refresh of the dashboard page the calls stop to be requested.

We see this behavior on other Live widgets as well.`

Tested on version 2.9.1 and 2.11.1

**Comment by mattab** [comment]
Thanks @RMastop for the report. +1 to try  remove those extra requests.
