### ISSUE TITLE
RE: piwik proxy script

### ISSUE THREAD

**Issue by k0nsl** [piwik/piwik#7406]
One suggestion: when fetching piwik.js via the proxy script we should set a user agent string as many WAFs will block requests that leaves empty this string.

Just a thought.

**Comment by mnapoli** [comment]
Do you mean this proxy script: https://github.com/piwik/tracker-proxy ?

Have you experienced such problem?

**Comment by k0nsl** [comment]
Yes.

**Comment by mattab** [comment]
@k0nsl can you please create an issue the issue tracker of https://github.com/piwik/tracker-proxy ?

**Comment by k0nsl** [comment]
@mattab: yes I can do that.

**Comment by mattab** [comment]
Thanks that's helpful
