### ISSUE TITLE
Show visitor log of visitors who reached a specific goal

### ISSUE THREAD

**Issue by amenk** [piwik/piwik#7411]
As a site owner it would be nice to be able to show the session of a conversion. There should be a link in the goals widget as well as it should be possible to define such a segment in the visitors log.

**Comment by mattab** [comment]
Hi @amenk thanks for the suggestion.

Note that there is already a segment that you can manually create to see all users who have converted specific goal id: `visitConvertedGoalId`

>As a site owner it would be nice to be able to show the session of a conversion.

+1 - now that we have the feature of Segmented visitor log #4633 we could let users view the Visitor Log segmented to users who have converted the given goal.
