### ISSUE TITLE
Feature request: Average daily pageviews in period

### ISSUE THREAD

**Issue by ttl76543** [piwik/piwik#7418]
It would be very helpful to be able to view the average daily pageviews (for a given period) from within the main interface.

Even better if there was a breakdown — for example, if I'm viewing the month, it gives me the number of average daily pageviews for that month, but then also the average for each week within that period.

And it would also be helpful to be able to see daily pageviews as a list, so for example if I'm viewing the month, a list showing the pageviews on each date in that period.

**Comment by mattab** [comment]
Hi @ttl76543 

Thanks for suggestion. Something like this is definitely much needed and has been asked many times before. See this very similar feature request:  Add a new feature to evolution graphs: show visits for each day in selected period #955

**Comment by mattab** [comment]
Dupes https://github.com/piwik/piwik/issues/955
