### ISSUE TITLE
Only link to plugin MultiSites, if MultiSites is actually enabled

### ISSUE THREAD

**Issue by Chrissitopher** [piwik/piwik#7423]
I have deactivated the plugin MultiSites, because I do not need it. However, the drop-down in the right of the main menu, next to "Website", still contains a link "ALL WEBSITES", which links to the MultiSites plugin. Logically this link is not working, because the plugin is not enabled.

Only add this link, if MultiSites is actually enabled!

![broken-link](https://cloud.githubusercontent.com/assets/4834755/6641573/db53d57a-c99e-11e4-9638-c53e990bb371.png)

**Comment by mattab** [comment]
Hi @Chrissitopher thanks for the suggestion.

**Comment by Chrissitopher** [comment]
I have just tried to fix this issue, but I did not really succeed:

This text is coming from the string named "MultiSitesSummary".

In *plugins/CoreHome/angularjs/siteselector/siteselector.directive.js* this string is used as language label for "allSitesText".

This language label finally is used in *plugins/CoreHome/angularjs/siteselector/siteselector.controller.js*
and the offending link is added in *plugins/CoreHome/angularjs/siteselector/siteselector.directive.html* with this code:

```html
	<div piwik-focus-anywhere-but-here="view.showSitesList=false" class="custom_select"
		 ng-class="{'sites_autocomplete--dropdown': (model.hasMultipleWebsites || 
		showAllSitesItem || !model.sites.length)}">

		<script type="text/ng-template" id="siteselector_allsiteslink.html">
			<div ng-click="switchSite({idsite: 'all', name: allSitesText});view.showSitesList=false;"
				 class="custom_select_all">
				<a href="{{ getUrlAllSites() }}"
				   piwik-ignore-click
				   ng-bind-html="allSitesText"></a>
			</div>
		</script>
```

When I remove the entry *showAllSitesItem ||* from the div container, then the item is gone, but I don't think that's how this issue *should* be solved. Better ideas? I would also be willing to test! :-)

**Comment by Chrissitopher** [comment]
In current versions of Piwik, the "All websites" link now only is displayed, if MultiSites is really loaded. 

This solves the issue.
