### ISSUE TITLE
Data uploaded for "today" appears on graph as "yesterday"

### ISSUE THREAD

**Issue by mfuller615** [piwik/piwik#7426]
I cut a 1 minute section from a log file from 2/18/15 and uploaded it. The log was rendered properly but the date both on mouse over and on the axis was for 2/17/15. I checked the timezone and it was correct. Can someone tell me what I may have overlooked during configuration or if this is a real bug?
Thanks!

**Comment by mattab** [comment]
Hi there,

can you please ask in the forums and also attach a sample log file? 

note that this is related to the website timezone set in piwik, check it's correct.
