### ISSUE TITLE
Popovers should not open on login page

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#7431]
When opening a direct link to a visitor profile with not having access to it ends up on the login page showing an popover loading the login page with another popover and so on.

See http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=34&period=day&date=yesterday#/module=Live&action=indexVisitorLog&idSite=34&period=day&date=yesterday&popover=visitorProfile$3Ae02fb30d85e6d686

Instead only the login page should load.

**Comment by mattab** [comment]
Nice find :+1:
