### ISSUE TITLE
When clicking on Admin => Users it shows login form under circumstances

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7436]
I'm clicking on "Administration => Users". Then I get the following error and the login form is shown:

`Error: You can't access this resource as it requires an 'admin' access for the website id = 1.`

The user has admin access to at least one website. The user has view access to a couple of other sites. I'm currently viewing a site where I only have view access.

Expected: I should still see the UsersManager.

**Comment by mnapoli** [comment]
Pull request: #7507
