### ISSUE TITLE
Need a way to exclude URLs from being tracked

### ISSUE THREAD

**Issue by cfuser** [piwik/piwik#7441]
Since Piwik only uses the ID and not the URL for capture,we need a way to exclude specific URLs from the data capture where not including the script is not an option? In our use case, we use a central CMS for 300 websites and I need to exclude any traffic from the development and staging URLs. This could also be useful for pages that you may not want to track, but uses a shared include that contains the script (e.g. footer).

**Comment by gaumondp** [comment]
I think #588 would solve this also...

Right ?

**Comment by mattab** [comment]
Hi guys,

 duplicates  #588
