### ISSUE TITLE
issues with multiple super users on an instance

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#7442]
In the case of a Piwik instance having multiple super admins, it is hard to share or transfer work. Both super admins have there own set of settings, like email reports they have created for users, segments that have been created, not shared with everyone.

One super admin is not able to access (or view) these parts created by another super admin, so they start creating extra reports, and segments.

This is particularly an issue in enterprise environments.

It would be more than nice for super admins to be able to see and change other people's settings, reports and segments.

**Comment by tsteur** [comment]
I think this refs #7076, #7149 and #6844

**Comment by mattab** [comment]
Hi @RMastop 
* Segments covered in #6844
* Email reports & Alerts covered in  #7076
* Goals covered in #7149 

Please feel free to post your further thoughts re: "Piwik Enterprise" into this new issue:  Building the best Enterprise Analytics Platform #8920
