### ISSUE TITLE
Exclude extensions as downloads

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#7444]
We have a webservice that uses .exe in the URL. These calls is always tracked as a download.
Would love to see a per site setting to exclude / include extensions as a download.

**Comment by tsteur** [comment]
Maybe we should add a new method to the Piwik.js tracker as this is detected on the client side. We won't be able to add a setting there. There are already the following methods:

* `setDownloadExtensions(extensions)`
* `addDownloadExtensions(extensions)`

Maybe we could add a method `removeDownloadExtensions`. This would allow to do the following:

`_paq.push(['removeDownloadExtensions', 'exe']);`
`_paq.push(['removeDownloadExtensions', 'exe|dmg']);`

If someone is working on this anyway, maybe that person can also change those 3 methods to accept an array of extensions as well. Currently, one needs to separate them by a `|` which is not really user friendly and it doesn't allow us to change the internal handling.
