### ISSUE TITLE
Percentage displays more than 100% values in Visitor - Settings - Plugins 

### ISSUE THREAD

**Issue by oussjarrouse** [piwik/piwik#7447]
In the Visitor - Settings view. the Plugins panel gave is showing these numbers (in the attached screenshot): Please note the 102% in the first line.
It might be a small issue related to visitors using ie browser. But it could be a general problem with calculating percentages on the entire webapp. It is worth it to take a look at the math.
![piwik_visitors_settings_screenshot_2015-03-16 18 49 21](https://cloud.githubusercontent.com/assets/1843808/6672711/6fc5eefc-cc0e-11e4-9ea9-7f6a9ed99e84.png)

**Comment by sgiehl** [comment]
duplicates #7437

**Comment by oussjarrouse** [comment]
Thanks +1:
