### ISSUE TITLE
Show indicator whether database upgrade is in progress

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7448]
I recently had some bigger database updates that took a while. I clicked the "Upgrade Piwik" button but nothing really happened. I wasn't sure whether it does anything or not so pressed the button again, still no indicator whether the update started. Not sure if this triggered the update process a second time. In the end I did a `show full processlist` on MySQL to see whether the update started or not.

I would expect the Update button to be in a disabled state and to see a message or any kind of indicator somewhere.

**Comment by mattab** [comment]
we should make button disabled after click, maybe along with redesigning the update screen in #7450

**Comment by mnapoli** [comment]
The button was already disabled, but I changed the label when it's clicked.

**Comment by mattab** [comment]
does the trick!
