### ISSUE TITLE
Make titles black instead of brown

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7449]
The goal of this issue is to make all titles in Piwik black colors, in particular to change the titles currently brown to make them consistent black.

For example: https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/CoreUpdaterDb_main.png

also this: https://github.com/piwik/piwik-ui-tests/blob/master/UIIntegrationTest_goals_overview.png

They look quite wrong Imo so this is the reason to change them :-)

**Comment by mnapoli** [comment]
They are a different color because they are links. If we make them black we can see that they are link, but I tried in blue and that's too much IMO. I think black is good.

**Comment by mnapoli** [comment]
I have fixed this in #7481

I know ideally it should be a separate pull request but #7481 carries changes to uniformise base CSS styles (e.g. for headers) so it would be really more complex to make a separate pull request. I have taken the opportunity to simplify headers style: now Morpheus defines a base h2/h3 style consistent for all Piwik and CoreHome only overrides what's necessary for the h2 and h3 in reports. Much nicer, easier to theme, etc...
