### ISSUE TITLE
Skip to Content overlaps with top menu

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7451]
As described in https://github.com/piwik/piwik/pull/7025#issuecomment-81567476

The `Skip to content` link overlaps with top menu: 
![skip to content](https://cloud.githubusercontent.com/assets/466765/6677890/00367a44-cc99-11e4-8f02-175cf7ae73f2.png)

**Comment by jdeyla** [comment]
(I suggest using the same script found on www.webaim.org)

**Comment by mnapoli** [comment]
I'm moving the link here:

![capture d ecran 2015-04-06 a 13 55 02](https://cloud.githubusercontent.com/assets/720328/6999639/9bcc5a16-dc64-11e4-885e-e3af67038a47.png)
