### ISSUE TITLE
core:update command expects certain directories to be present tmp/

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7459]
During attempt to run core:update on Piwik 2.11.2 I spoted following issue:
- try running ./console core:update --piwik-domain=localhost
- throws following error:

> [UnexpectedValueException]                                                                                                                   
  RecursiveDirectoryIterator::__construct(/private/var/www/piwik/tmp/templates_c): failed to open dir: No such file or directory

Even if tmp/ has 777 permissions granted.
I think that Piwik should be more than capable of handling empty tmp/ directory (especially important on production instances, which sometime have tricky permission schema - we need to be able to populate tmp with proper permissions easily if something would go wrong).

Also just note - core:clear-caches also fails if this specific directory is missing.

**Comment by mattab** [comment]
Thanks for the report. This was fixed earlier https://github.com/piwik/piwik/commit/71cacb0aca6aeb557e536c2b5b5b687f58f5465f - please try again with 2.12.0 beta which includes the fix.
