### ISSUE TITLE
Piwik Schedule Reports not being received

### ISSUE THREAD

**Issue by agrebla** [piwik/piwik#7460]
I Have scheduled reports that I created in the Joomla Piwik component. They used to work and sent an attached PDF on a weekly basis. They stopped working automatically, but if i go to the reports page and manual click "Send Report Now", I receive the report without any problem. What is the difference? Why did the automatically scheduled report stop working?

**Comment by palleroy0** [comment]
My daily reports have stopped arriving as well.

**Comment by mnapoli** [comment]
If you update to Piwik 2.11 or later you can enable logging at DEBUG level (watch out it will log a lot of things!) into the log file:

```ini
[log]
log_writers[] = "file"
log_level = "DEBUG"
```

Then you should be able to find logs by searching for `Scheduler` (`cat tmp/logs/piwik.log | grep Scheduler`).

If you can provide us with those logs that would help a lot. Thank you.

Remember to change from `DEBUG` level to `WARN` level once you have finished (e.g. let it run for a day maybe). Watch out for the log file size if you have a lot of traffic.

(logs added in commit a0044122 for those interested in the details)

**Comment by mattab** [comment]
@agrebla do you still have the issue with the latest Piwik? please check previous comment for some instructions on how to troubleshoot. would be great to learn more of your issue if still applicable

**Comment by mattab** [comment]
Hi @agrebla 

do you mind answering @mnapoli question in the other issue that duplicates this one: #8092

@mnapoli can you ask users in  #8092 with your tips how to get more debug info?
