### ISSUE TITLE
Inconsistent use of country name in [lang].json

### ISSUE THREAD

**Issue by ghtiun** [piwik/piwik#7479]
Certain references to Taiwan are inconsistent in the [lang].json in plugins/UserCountry/lang.  For example, the term "Taiwan, Province of China" is used to indicate Taiwan in the tl and en version; while "Republic of China"(Repubblica di Cina) in the it version.  

May I suggest simply using "Taiwan" and equivalent word in each language version to make it consistent?  Many thanks.

**Comment by mnapoli** [comment]
Related discussion on what StackExchange did: http://meta.stackexchange.com/questions/170143/taiwan-is-not-a-province-of-china

**Comment by mattab** [comment]
+1 to change the en.json to use `Taiwan` as the name
