### ISSUE TITLE
The "pragma" "disableCookies" does NOT work in some browers.

### ISSUE THREAD

**Issue by AgnesWhy** [piwik/piwik#7493]
I have tested the following piece of code, respectively in Firefox 36.0 and Chrome 41.0.2272.89 m
In Firefox, there is no "vsitor" cookie installed while in Chrome, the cookies "ses, id, cvar....) are installed in spite of the instruction diablecookies. 
You can test it using the site ShemaleAgnes.com  (cookies are dia

QUOTE
<script type="text/javascript">

</script>

UNQUOTE

**Comment by mnapoli** [comment]
Duplicates #7494
