### ISSUE TITLE
Goal widget reloads Visits widget on dashboard

### ISSUE THREAD

**Issue by Code-Working** [piwik/piwik#7495]
I have a "Visits Over Time" widget and a specific goal Widget on my dashboard.
In the goal widget, there is a summary of conversions, overall revenue and overall conversion rate below the graph.

However, when I click on one of the summary items, the graph of the widget reloads as expected, but in parallel, the "Visits Over Time" widget graph loads the same data as the goal widget.

Dashboard as it looks correct:
![image](https://cloud.githubusercontent.com/assets/6079169/6748789/1f3384d4-ceea-11e4-8869-9128af136ea9.png)

After clicking on the "overall revenue" item in the goal widget:
![image](https://cloud.githubusercontent.com/assets/6079169/6748793/2b4fc6b0-ceea-11e4-9ce8-9bab61f0ab73.png)

**Comment by sgiehl** [comment]
I can confirm that issue. I'll try to fix it asap
