### ISSUE TITLE
Reloading a report whose saved ViewDataTable params includes pivotBy results in incorrect report rendering

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#7505]
If you:

1. Pivot a table in the UI (eg, CustomVariables), then
2. Reload the page.

The page will use the saved ViewDataTable parameters and get the report w/ the Pivot. For some reason the following bugs occur:

* Instead of the table having the `dataTableVizPivotBy` CSS class, it will have the `dataTableVizHtmlTable` CSS class.
* The column values will all be empty because the displayed columns are `Actions` and `Visits` instead of the pivotted columns.

**Comment by mattab** [comment]
This bug looks fixed in latest beta
