### ISSUE TITLE
Piwik does not track all visits anymore (Piwik 2.12.0 / Wordpress)

### ISSUE THREAD

**Issue by kmindi** [piwik/piwik#7514]
I have not figured out what is the problem yet, but since the update to Piwik 2.12.0 not all visitors are being tracked anymore, hope its no problem from WP-Piwik 0.9.9.12.

**Comment by kmindi** [comment]
it seems that manually adding the code fixes the problem, so i would say it is a problem of WP-Piwik ;)

**Comment by mattab** [comment]
Hi @kmindi can you please report the issue in the WP-Piwik forum? it would be great that the plugin gets better with your feedback :+1:

**Comment by braekling** [comment]
Hi Matt,

looks like I need some help on this. WP-Piwik does not work with Piwik 2.12.x if it is using js/index.php. Using the default tracking code or a proxy script works fine, instead.

If I open js/index.php manually, everything looks fine. But if I open my site, Safari gives me 
> [Error] SyntaxError: Unexpected end of script

Checking the script asynchronously loaded by Safari, it isn't completely loaded, indeed. It ends after ```bH(cn,JSON2.stringify(ag),az,b3,aq)}}if(a1){if(a```

I have no idea what's happening. The tracking code looks like this:
```<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['setVisitorCookieTimeout', '604800']);
_paq.push(['setSessionCookieTimeout', '0']);
_paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//www.example.com/piwik/";
    _paq.push(['setTrackerUrl', u+'js/']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'js/'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->```

Any idea? Did you change something to js/index.php?

**Comment by braekling** [comment]
Hm, the "unexpected end of script" was gone after clearing my browser's cache. Now WP-Piwik is working as expected again.

I will ask my users for more detailed information. At the moment, I'm not able to reproduce the issue.

**Comment by mattab** [comment]
Hi @braekling ok let us know if you find something (feel free to create a new issue)

**Comment by mwaters5** [comment]
I am using Blue Host as my Host. Im currently hosting 8 different sites (All Wordpress) on the same server account. i have used wp-piwik as the plugin to configure all of them. of the 8 sites I am hosting with Blue host. 3 of them workk just fine with Piwik. The rest I get this error: http://screencast.com/t/9yYCta6R3uR

I have called Blue Host and they have verified with me that they are not blocking anything on their side so the problem seems to be on my side. 

Can you give me any idea ??? I am willing to pay $$$ for a resolution.

**Comment by mattab** [comment]
@mwaters5 Load your websites and check that in the footer they have the javascript piwik tracking code. If they have it, it should track your visitors. if it doesn't check this FAQ: http://piwik.org/faq/troubleshooting/faq_58/
