### ISSUE TITLE
Admin page has trouble loading with 10,000+ sites

### ISSUE THREAD

**Issue by roadwing** [piwik/piwik#7515]
We run a Piwik instance that tracks thousands of pages.  In the Admin UI, we are unable to load the list of websites successfully so that we can scroll it.  The browser freezes and we receive timeouts or "Wait " notifications that the script is taking too long.  Here is a screen shot of a typical hang:
![piwikwebsiteloadwait](https://cloud.githubusercontent.com/assets/11618701/6788292/591b2b9c-d166-11e4-9531-540c13d372ac.png)

We are currently using Piwik 2.12.0; this issue has been around since 2.2.0.

**Comment by quba** [comment]
Duplicates https://github.com/piwik/piwik/issues/3838
