### ISSUE TITLE
Make Popovers slightly wider

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7517]
Suggested in #7430 as sometimes the Popover are a bit too narrow and most screens can display more of the popover width.

**Comment by mnapoli** [comment]
Do you mean the popups or something else?

**Comment by mattab** [comment]
Popovers: they are displayed on top when popup are usually new windows (JS objects are called Popover etc)

**Comment by mnapoli** [comment]
ok we were talking about the same thing apparently… just with a different name
