### ISSUE TITLE
Download page should link to HTTPS

### ISSUE THREAD

**Issue by tomascassidy** [piwik/piwik#7520]
I've noticed that the download page only links to http://builds.piwik.org/piwik.zip instead of https://builds.piwik.org/piwik.zip.

Since the latest piwik 2.12.0 now downloads updates over HTTPS (#6441), it would be nice to have the download page also link to a HTTPS url.  It links to a HTTP download url even when I browse to https://piwik.org/download/ over HTTPS.

In addition, browsing to https://piwik.org/download/ (and https://piwik.org/) over HTTPS causes mixed-content warnings in Firefox and Chrome due to loading some images over plain HTTP.

**Comment by mattab** [comment]
The download page now links to the SSL HTTPS download :+1:
