### ISSUE TITLE
Visitor profile, visits loaded on click are missing the datetime

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7522]
The goal of this issue is that in a Visitor Profile, when clicking on "Load more visits" the visits loaded should display the date time in the visit header bar.

(should be quick fix, so adding to 2.12.1)

[URL to reproduce](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=2015-03-22&period=week&idSite=7&segment=visitCount%3E%3D10#/module=Live&action=indexVisitorLog&date=2015-03-22&period=week&idSite=7&segment=visitCount%3E=10&popover=visitorProfile$3A60c547fab167a4de)

See missing visits:
![visitor profile visits loaded on click are missing the datetime](https://cloud.githubusercontent.com/assets/466765/6799558/b25df5de-d27b-11e4-800e-b1b7eab8e013.png)

**Comment by sgiehl** [comment]
I'll have a look at that now.

**Comment by mattab** [comment]
I see in API response:
```

		<serverDatePrettyFirstAction>Wed 25 Mar</serverDatePrettyFirstAction>
		<serverTimePrettyFirstAction>00:42:20</serverTimePrettyFirstAction>
```

so maybe we simply display in the template `serverDatePrettyFirstAction - serverTimePrettyFirstAction` which does not require change to API, what do you think?

**Comment by sgiehl** [comment]
Thought about that, too ;)
Already had added that to the templates. But within the visitorprofile the date is reformated using https://github.com/piwik/piwik/blob/master/plugins/Live/VisitorProfile.php#L23
If it is ok to use another format at that point, I'll change it.

**Comment by mattab** [comment]
+1 to change it to make it consistent with API - we might as well consume the "pretty" dates we give to users :)

**Comment by sgiehl** [comment]
The pretty dates set in the API are not nice to display at that point. The dates would be like "Fr 13 Apr" without a year. Maybe we should change the dates in the API aswell and return a full date.

**Comment by RMastop** [comment]
+1 for changing the pretty date into a full date.

**Comment by mattab** [comment]
+1
