### ISSUE TITLE
local searchengine definition gets lost

### ISSUE THREAD

**Issue by Kornexl** [piwik/piwik#7523]
on every update my searchengine definitions are lost

how can i configure my local definitions to remain active

**Comment by sgiehl** [comment]
Try http://plugins.piwik.org/ReferrersManager

**Comment by Kornexl** [comment]
I can't add an icon.

The definition is not shown in the plugin and is not recognized as search engine in the check

**Comment by sgiehl** [comment]
Adding icons currently does not work in that plugin, as Piwik doesn't have kind of a hook for that.
The plugin shows all definitions defined in the SearchEngines file. Additionally you can define your own one, which will NOT be written to the SearchEngines file. Instead the custom ones will be stored in the database, so they will consist after an update
