### ISSUE TITLE
Heat/Click/Scroll Map

### ISSUE THREAD

**Issue by johnnabil** [piwik/piwik#7545]
Hi , I used the overlay feature in Piwik, but it doesn't provide any clicks information about other parts in my webpage , i need to track the clicks on any part of my page, also i like to track the scrolling happens.

Thank you for your help

**Comment by mattab** [comment]
Hi @johnnabil thanks for your suggestion, it would be really great to have click and scroll map in Piwik for sure... There is also this related heatmap issue:  #6371

**Comment by thob** [comment]
scroll depth is very important indeed

**Comment by mattab** [comment]
Please see https://github.com/piwik/piwik/issues/6371

**Comment by mattab** [comment]
Good news: we're working on [Heatmap Analytics for Piwik](http://www.heatmap-analytics.com/) + scrollmap + click map! It will be awesome and make sure to hear when it's released by signing up here: http://www.heatmap-analytics.com/
