### ISSUE TITLE
Wrong ordering and pagination in Visitor log Piwik 2.12

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#7547]
Hi!
After upgrade to latest version I see that the pagination in "Visitor log" Not working anymore. When I press the "next" to navigate Piwik say "No data to display". And when I go back to the previous page I see the wrong row ordering by date.

After click on "View detailed visitor log" at the bottom of the page with 500 items per page, Piwik load all rows for selected period. After select 25 items per page Piwik load 25 rows again with wrong ordering.

Any ideas?

**Comment by tsteur** [comment]
I think this was fixed in #7521. Please reopen in case it does not work with Piwik 2.12.1 which should be available soon.
