### ISSUE TITLE
w3c problem

### ISSUE THREAD

**Issue by mosandlt** [piwik/piwik#7553]
Hello
my change

wp-piwik.php
$aryNoscript[0] = str_replace('?idsite', '?rec=1&idsite', $aryNoscript[0]);
to
$aryNoscript[0] = str_replace('?idsite', '?rec=1&amp;idsite', $aryNoscript[0]);

cheers

**Comment by sgiehl** [comment]
Is that related to the piwik wordpress plugin? If so you may open an issue there: https://wordpress.org/support/plugin/wp-piwik
Even though I can't see any difference between those two lines...
