### ISSUE TITLE
visitor log: Segmentation with 2 Vistor ID broken

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#7559]
In visitor log a segmentation with 2 Vistor IDs (AND, please see attachment)
doesn't show any results.

When using each Visitor IDs without the other, both show results 
- of course for same time period
- Piwik 2.12.1
![2015-03-27_16h16_02](https://cloud.githubusercontent.com/assets/5681880/6870501/ce76806a-d49c-11e4-88fb-d1b87018ba60.png)

**Comment by sgiehl** [comment]
Every visitor only can have one visitor id, so there won't be results for sure.
If you would like to have a segmentation showing two different visitor ids, you may need an OR connection.

**Comment by hpvd** [comment]
uuups sorry my fault. Many thanks!
=> can be closed
