### ISSUE TITLE
Error archiving data

### ISSUE THREAD

**Issue by lexsanchez** [piwik/piwik#7564]
When I run the command to archive shows me the following error. 

Got invalid response from API request: http://xxx.xxx.xxx.xxx/piwik/index.php?module=API&method=API.get&idSite=3&period=day&date=la                                                                    st52&format=php&token_auth=removed&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:66:"Action table for type '11' was not found during Ac                                                                    tions archiving.";}

**Comment by mattab** [comment]
Hi @lexsanchez 

can you try upgrade to 2.12.1 and check if this error still occurs?

**Comment by lexsanchez** [comment]
Hi Mattab:

The error occurs even taking the version 2.12.1, have reviewed more thoroughly and think the problem is that the table log_action not have some records that need to archive data.

I will review the database backups of days earlier to see if I can find those records that are needed in the table log_action.

**Comment by mattab** [comment]
Hi @lexsanchez any update? if anyone else has the bug also please +1 as I couldn't yet see how this code path could be triggered

**Comment by lexsanchez** [comment]
Hi @mattab, while continuing with the same problem, I've done a merge of data a day before problem with the data that is currently generating and still sends me the same error.

I have tried the system skips the record found, for the system to continue with other records, but even abort the operation.

**Comment by mattab** [comment]
@lexsanchez for now maybe you want to work around this issue by changing this line:
https://github.com/piwik/piwik/blob/2.12.1/plugins/Actions/ArchivingHelper.php#L368
into `return array();` - this hopefully would let you continue the archiving of reports.

**Comment by lexsanchez** [comment]
Hi @mattab, I made the change in the line 368 and run the command file shows me the following error:

Response was 'PHP Fatal error:  Call to a member function isSummaryRow() on a non-object in /opt/bitnami/apps/piwik/htdocs/plugins/Actions/ArchivingHelper.php on line 111 a:2:{s:6:"result";s:5:"error";s:7:"message";s:56:"Call to a member function isSummaryRow() on a non-object";}'

**Comment by mattab** [comment]
@lexsanchez sorry I didn't test again but maybe try `return new Row();` instead

**Comment by mattab** [comment]
@lexsanchez if you still have this problem with latest piwik, please create new issue, thx
