### ISSUE TITLE
Improve translator experience/efficiency

### ISSUE THREAD

**Issue by hansfn** [piwik/piwik#7567]
Hi, currently Piwik uses [oTranCe – the online translation center](http://otrance.de/en/) as the translations software behind http://translations.piwik.org/ That solution is **very** primitive compared to modern solutions like http://translatewiki.net (free/open source) or https://www.transifex.com/ (free/semi-closed source). If moving to one of those services is not an option, please add an export/import feature for a format supported by [Virtaal](http://virtaal.translatehouse.org/)

I'm very happy to translate Piwik (to Norwegian Bokmål), but using http://translations.piwik.org/ is painstakingly slow because there are no translation suggestions, automatic translation of identical strings (from other projects) and so on.

**Comment by sgiehl** [comment]
I'm aware that oTrance might not be the best solution. But it still was a step forward compared to the system "before". Nevertheless I'm open for changes regarding the translations.

@hansfn Are you active on one of the mentioned systems? Which one would you prefer?

I'll try to evaluate those systems the next days.

@piwik/core-team any thoughts/comments?

**Comment by hansfn** [comment]
I like translatewiki.net - it works great and is the most open solution (of the two). There are of course many other options, Launchpad (for translations) is used a lot. If you prefer a self-hosted solution there is Pootle and the new kid on the block - [Weblate](http://weblate.org) with tight Git integration.

To make a choice, I guess setup cost (time) and workflow cost is important to consider. All of these solutions are better than oTranCe.

PS! I of course prefer using Virtaal, but online translation makes it easier for people to contribute.

**Comment by sgiehl** [comment]
I took a look at Transifex. It's quite amazing so far and easy to use.
Some points that would definitely help up as lot:
- It is able to import/export the json file format we are currently using
- There are APIs we could use to update the translation files
- It can be configured to auto update the base translations from url (e.g. github raw url)
- we can split translations into several resources (eg. one per plugin file)

I also took a short look at translatewiki. It's an option aswell. But it doesn't have that much features as Transifex. Also it might not be so easy to use for users not having a technical background.

**Comment by hansfn** [comment]
I'm glad you liked Transifex. From you feedback I'm starting to hope that you'll be able replace oTranCe in the near future.

From a translator's perspective Transifex and Translatewiki are similar to use and has the same features. (I logged in to both services right now to refresh my opinion.) On which basis do you think Translatewiki "might not be so easy to use for users not having a technical background"? Just wondering, I'm fine with using Transifex too :-)

**Comment by sgiehl** [comment]
We still need to discuss that in @piwik/core-team, but I would be happy in switching to an alternative.

For me translatewiki has too much of a wiki. And even for me transifex was easier to handle.
Also transifex has a complete project management, so I could create the project by myself. If I have seen that correctly there's no possibility to do that on translatewiki. There they have to do that. Also the list of supported languages is not so long.

**Comment by hansfn** [comment]
Just to repeat: I'm 110% fine with using Transifex. It seems to have more features and it is easier to manage.

Anyway, just for completeness I have attached two screenshots. Maybe I prefer the translation UI on Translatewiki because it's simpler. (Getting to the translation UI is probably easier on Transifex.)

Transifex:

![transifex-ui](https://cloud.githubusercontent.com/assets/92755/6886043/29738428-d631-11e4-856f-8957d9783f89.png)


Translatewiki:

![translatewiki-ui](https://cloud.githubusercontent.com/assets/92755/6886049/30048e72-d631-11e4-888a-9fe7753c74fe.png)

**Comment by mattab** [comment]
Hi guys,

I guess it's quite a lot of work to rewrite all our tools currently using oTrance to change the tool. I'm not sure yet it is worth it.... we didn't get any complain from the translators. What are the current problems of oTrance?  What would be the advantages of switching to another tool?

**Comment by sgiehl** [comment]
Not getting any complains does not mean the tool is good. I already had a few and there could be more users active...

Advantages of using Transifex:
- Currently we have to update the basis translations on oTrance from time to time (Transifex would do that automatically based on git URLs)
- We currently do not have kind of a review process for translations implemented, Transifex would have
- Currently we are updating the translations on git on demand, with Transifex it would be possible to do that automatically (see http://docs.transifex.com/developer/integrations/github)
- We currently have a limited userbase translating piwik. On Transifex and others also people from other projects would easily be able to help
- Users currently do need to create an account on oTrance to translate, on Transifex there are social logins with github, twitter, facebook and co possible (which makes it easier)

Regarding the rewrite of those tools we are using. They are doing stuff that might easily be possible using the Transifex API.

Tasks that would need to be done to migrate to Transifex:
- Take translations.piwik.org offline (or redirect it to Transifex)
- Finish setup of Transifex (already started that a bit to test the tool)
- import all existing translation files (and setup autoupdate for basis translations using github raw urls)
- write a blog post announcing the switch (also mention it on facebook and twitter)
- write an email to all users that were formally using our oTrance
- update the translation console commands to use the new APIs

**Comment by hansfn** [comment]
> Not getting any complains does not mean the tool is good.

My words exactly ;-) I guess the main reason you don't get that many complaints is that many people don't know there exist much better tools. I can only talk for the Norwegian Bokmål translation, but with better tools I would have translated much more. 

The major benefit from using Translatewiki, Transifex and similar tools is TM - Translation Memory. That enables translation suggestions, auto-translation, real crowdsourcing since translations from other projects/people also are available.

Of course there is some work rewriting your tools, but it seems to be some benefits too -  looking at the list provided by sgiehl.

**Comment by halfdan** [comment]
I definitely agree with @sgiehl and @hansfn here. Both solutions are definitely more user-friendly than what we have right now. Translators may even already be familiar with the systems, making it easier for them to contribute.

**Comment by mattab** [comment]
What are the main problems with oTrance currently?

**Comment by sgiehl** [comment]
- Source files / base translations need to updated manually (that's time consuming as I need to import them from time to time to check that everything is still up to date)
- Updating existing base translations is critical, as we need to remove all translations in other languages so the translators know it needs to be translated (even if the old one would fit good enough until a new one is there)
- Translations don't have a "review" process. In most cases that is fine, but it would be better to have one.
- oTrance is unable to handle placeholders, so it doesn't enforce the user to use them correct. It already took me hours to fix broken translations on oTrance. Maybe another service is able to do that (even if we would need to change the kind of placeholders we are using)
- oTrance is not actively developed anymore, so I don't expect there will be any new features in the future

But the main problem is that currently there are not so many users active on oTrance. Many users have registered but never translated anything. (Not sure why, but it might be caused by the UI which is not very easy to handle.)

**Comment by RMastop** [comment]
I did some translating for my native language, however, sometimes I can't see the context of the part that needs translation. I noticed some others had that as well. It's not possible to change an already translated part that needs 'rework'. I don't know if that might be possible in the other tools?

**Comment by hansfn** [comment]
> What are the main problems with oTrance currently?

I think I have answered that indirectly be describing the benefits (for a translator) of switching to any of the two tools I have mentioned. But, to put it very short: oTrance is wasting translator resources.

Using oTrance is like writing code with Notepad. If Piwik developers switch to using Notepad, I'm fine with translators using oTrance ;-)

**Comment by mattab** [comment]
It's very important for us to make Translators happy and make Piwik translations look great for users. Anything we can do to significantly improve translators life is important!

We will therefore consider this change and I'll discuss it with @sgiehl :+1:

**Comment by sgiehl** [comment]
After discussing with @mattab, we are happy to announce that our translations will be managed using transifex in the future. It will take one or two weeks until all todos will be done and the switch will officially be announced, but I've already created our project on transifex and imported most of the already available translations. You may already feel free to join our project: https://www.transifex.com/projects/p/piwik/

**Comment by baywet** [comment]
@sgiehl I'm the French Translator of Piwik. (well the First one)
Two questions: 
- With this new software, will we be able to use our github account (so modifications and everything appears on github) ?
- Should we stop using the "old" software and start trying the new one?

**Comment by sgiehl** [comment]
Changes done on github in the base translations (english) will automatically be synced to transifex, but changes in other translations will not directly appear on github, but you can use your github account to login on transifex.
Before shutting down the old tool, I will merge all changes done there to transifex, so nothing will be lost. You can already have a look at the new software.

**Comment by tsteur** [comment]
Was it maybe meant whether the changes of the translations appear under the user's github name as a commit basically? Something like this would be cool if possible as it gives more visibility to the translators. 

Maybe it would be good to have a one or two weeks trial run with some translators before actually announcing it? But ignore me if not needed and we're confident that this is the right tool, I'm not into it those tools and the process around this etc and I know you already had a look. 

:+1: 

Do you mind making me a maintainer there? I just requested a language under `tsteur`. I'm curious re their UI :)

**Comment by sgiehl** [comment]
I've added you as a maintainer

**Comment by tsteur** [comment]
Thx! It might be worth to ask one or two more translators for feedback re the tool. I had some troubles using it and found it sometimes a bit hard to use. Many clicks etc, mainly because of the packages. For example you can't just get all untranslated keys or you can't search for a key across packages etc. But I might see it rather from a developer view than a translator view. It's more important that a translator can use it than me :) Other tools are probably worse :) 

Do I get this right that we no longer have to add new keys there? At least I didn't find a way to add one. That'd be awesome :)

**Comment by sgiehl** [comment]
Feedback is welcome for sure.

You can select "all resources" in translation mode. That way you should be able to see and search over all resources...

Adding keys is not necessary anymore. I've set up a resource for each language file and added the github raw url from master as update path. So every change done on master will automatically be synced to transifex. Keys will thus also be automatically removed and updated. The TM (translation memory) of transifex will remember all translations that did exists. So if we remove a translation today and would readd it some days after, transifex will automatically readd all translations (if the text of the original matches 100%). That also applies for duplicate translations or if the key changes (e.g. when moved to another resource)

**Comment by tsteur** [comment]
> You can select "all resources" in translation mode. That way you should be able to see and search over all resources...

Awesome. Didn't notice that. Also re the automatic adding /removing keys :+1:

**Comment by baywet** [comment]
alright @sgiehl you can add me to the French language with my github account, I'm willing to test it :)

**Comment by sgiehl** [comment]
@baywet could you please sign up on transifex using your github account?

**Comment by baywet** [comment]
@sgiehl done, I also requested to join the French translation team.

**Comment by sgiehl** [comment]
approved

**Comment by baywet** [comment]
Ok I just tested it for 2 translations it's way better than the other one. Should I keep translating on the new one or wait for the migration before using it more?
Only the fact that we can implement a review process and have an history is a big improvement and will improve translations' quality if we structure the teams properly.

**Comment by sgiehl** [comment]
@baywet Feel free to keep on using the new tool. Any feedback is welcome. Maybe you also have some thoughts about how to setup/implement the review process

**Comment by RMastop** [comment]
Tested the new translation tool, I must say I like it much more than the old one, in particular the ability to see the translated strings while translating another one.
I came across another issue, in dutch one can write the polite version, and the friendly version. I tend to use the friendly version. 
What is the general opinion/statement on applying this?

**Comment by hansfn** [comment]
First, I'm really happy that my request (this issue) lead somewhere. Thank you, Piwik team.

Secondly, I have just requested access to Norwegian Bokmål. (I'm hansfn on Transifex too.)

@sgiehl Before we spend much time thinking about a review process we should observer if many language team get multiple members ;-) When the teams has many members, experienced translators (long term members on Transifex maybe) can be assigned the review role.

@RMastop The Norwegian translators have decided to use the informal/friendly version, but then very, very few in Norway use the formal/polite version. You really have to discuss this with other Dutch translators.

**Comment by sgiehl** [comment]
@hansfn You're right. We should focus on the review process later.

@RMastop German translations use the formal version

**Comment by baywet** [comment]
@sgiehl just finished updating the French translation. The experience is much better, especially when considering the glossary thing which allows you to have consistant translations for redoundant terms.

**Comment by mattab** [comment]
The migration to Transifex has been announced in the blog post: [Announcement of a new Translation platform for Piwik translators: Transifex](https://piwik.org/blog/2015/04/announcement-of-a-new-translation-platform-for-piwik-translators-transifex/) - kuddos @sgiehl

**Comment by sgiehl** [comment]
Nice! Guess we are almost done with this one then. I'll improve some parts of my pull request, and after merging I think this ticket can be closed. If anyone has suggestions on how to improve our transifex usage, feel free to send us an email, message on transifex or simply create an issue on github.

**Comment by dertuxmalwieder** [comment]
If you grow tired of Transifex one day: Our [TranslationPad](http://www.translationpad.com) is free for FLOSS projects. :)

**Comment by glezos** [comment]
Great to see piwik coming on Transifex guys. Happy to have you! Let us know if you need help. :+1:

**Comment by sgiehl** [comment]
@glezos thx for the welcome. If we need help I'll get in touch with you. btw, feel free to mention piwik on https://www.transifex.com/customers/open-source/

**Comment by xinomilo** [comment]
in case noone noticed... transifex is closed source : https://github.com/transifex/transifex/issues/206#issuecomment-15243207

**Comment by sgiehl** [comment]
I know. Well, isn't github closed source, too?
