### ISSUE TITLE
tracking a joomla site with nfrPiwik 

### ISSUE THREAD

**Issue by dimdam** [piwik/piwik#7568]
as the title says,i am unable to make this work. It keeps asking me about the tracking code although the code is in place. I tried it manually as well,before </body> but still no luck. Any clues?

**Comment by Globulopolis** [comment]
@dimdam you're kidding? Why do you need this useless plugin?
You can implement tracking via html-module:
1. Create new "Custom HTML" module
2. Toggle off html editor
3. Insert tracking code from piwik
4. On the "Options" tab uncheck "Prepare Content"(set to No)
5. Select the module position(e.g. Footer)
6. Save & Close
7. ...
8. Profit

**Comment by dimdam** [comment]
@Globulopolis tried what you said but nothing changed. Still getting the " No analytics data has been tracked for this website yet. Please set up the JavaScript tracking code on your website and refresh the page." message. Thank you for your time though

**Comment by Globulopolis** [comment]
@dimdam which period you want to see in reports? What do you see in "Visitor live"?

**Comment by dimdam** [comment]
@Globulopolis i cant see anything. When i select the Joomla site ,the only thing i can see is the message i wrote on my previous comment, and "No data has been recorded yet"

**Comment by Globulopolis** [comment]
Minimum period for reports - full day.

**Comment by dimdam** [comment]
@Globulopolis  just to be clear (because i have another site  and piwik started showing reports from the very first second),you are saying that i have to wait 24 hours to bypass this: http://i.imgur.com/pZ1rOpk.png ?

**Comment by Globulopolis** [comment]
@dimdam this two sites on the same piwik instance or different?

Just for test you can check the #_log_visit table and look for last records for selected idSite. If no records for selected idSite when tracking code not working.

**Comment by mattab** [comment]
@dimdam you don't need to wait 24 hours, the screen will go away as soon as even one request is tracked in piwik. There are many reasons why you may not see data tracked in Piwik, check out this FAQ for more info: http://piwik.org/faq/troubleshooting/faq_58/

if you experience a particular bug feel free to create an issue
