### ISSUE TITLE
Include certificates for update over HTTPS?

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7580]
It seems some systems do not have certificates installed, which makes the update over HTTPS fail. See this comment: http://forum.piwik.org/read.php?2,125605,page=1#msg-125613

It seems to be a minority of users (for the forum posts). Should we include those certificates in Piwik by default? @mattab what do you think?

(let's discuss this assuming the "update over HTTP" fallback work, i.e. those users still have the possibility to update with HTTP)

**Comment by mattab** [comment]
it's valuable to let users on Windows and other systems without default setup certificates, upgrade Piwik over SSL - so +1 in general

**Comment by bolera** [comment]
Actually, setting the CA path via php.ini is easy as was demonstrated by the user who reported the problem and who fixed it himself. But it seems on some systems there are problems with the location. Maybe people should choose a different location than putting it in the root of C:\ There might be permission issues.

**Comment by mnapoli** [comment]
@bolera for those users we could include the certificate file so it would solve any problem they might have on their system.

**Comment by mnapoli** [comment]
I imported a root certificates file in Piwik, should work on PHP installs that don't have any root certificate set up.

**Comment by mattab** [comment]
Btw: noticed Guzzle also includes the cacert file, in case we wanted to re-use their file and not bundle it ourselves. 
```
// name -> file size
  '/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem' => 250394,
  '/core/DataFiles/cacert.pem' => 249822,
```
