### ISSUE TITLE
New design for Installer screens

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7584]
The goal of this issue is to refresh the design of the Piwik installer screens.

Here is an example of the new design for the "Installation" screens:

![piwik-step1](https://cloud.githubusercontent.com/assets/466765/6911850/c14f030c-d7c2-11e4-970f-7ed7cab661db.png)

Another example:

![piwik-step2](https://cloud.githubusercontent.com/assets/466765/6911851/c15124de-d7c2-11e4-9167-884ab3487f6c.png)

Note: in this issue the scope is only restricted to changes in the design (html/css) and not any text or feature.

**What do you think about these designs?**

**Comment by mnapoli** [comment]
The complete screenshot list:

![step1](https://cloud.githubusercontent.com/assets/720328/7555814/2a5bdbde-f7b4-11e4-9abe-78d8fbb4e34a.png)
![step2](https://cloud.githubusercontent.com/assets/720328/7555815/2cb844d0-f7b4-11e4-9058-2eed0faf93e9.png)
![step3](https://cloud.githubusercontent.com/assets/720328/7555816/2e4aaab8-f7b4-11e4-9688-28802186e83f.png)
![step4](https://cloud.githubusercontent.com/assets/720328/7555817/3011dbc8-f7b4-11e4-85b7-db473b3fe509.png)
![step5](https://cloud.githubusercontent.com/assets/720328/7555818/3198c0f6-f7b4-11e4-819b-c7d3e0afe910.png)
![step6](https://cloud.githubusercontent.com/assets/720328/7555819/3322642c-f7b4-11e4-82bb-714c6413c4ea.png)
![step7](https://cloud.githubusercontent.com/assets/720328/7555820/3512a33c-f7b4-11e4-8543-158d56035dc9.png)
![step8](https://cloud.githubusercontent.com/assets/720328/7555821/36436a20-f7b4-11e4-9016-bed538f4c9b7.png)
![step9](https://cloud.githubusercontent.com/assets/720328/7555822/3774de2e-f7b4-11e4-86f4-21c4bf497a44.png)

**Comment by mnapoli** [comment]
List of pull requests:

- general installation redesign #7875 
- alert redesign: #7874 
- tables redesign (system check): #7895
- buttons redesign (few minor things have changed): #7896
- code blocks redesign: #7793 
- icons: TODO see #7618 
- forms redesign: TODO

**Comment by mnapoli** [comment]
Everything has been merged (except icons), I think we can close this one!

**Comment by mattab** [comment]
Re-opening (rather than creating new issue), as I have little feedback:

 * [ ] can we style checkboxes in the installer?
 * [ ] for the two checkboxes at the bottom of form, maybe the label could be made not to wrap to another line?

![checkboxes not styles](https://cloud.githubusercontent.com/assets/466765/8028050/f309af2a-0df8-11e5-84ba-77132bfb1548.png)

 * [ ] final step of installer looks random: (grey text, checkboxes not styled) - maybe can be improved?

![looks random](https://cloud.githubusercontent.com/assets/466765/8028060/1e9ef74e-0df9-11e5-9f61-efb1fd9bdd58.png)

 * [ ]  Some `Next` buttons are big, some are small. In installer, can we make all `Next` buttons consistently big?

**Comment by mattab** [comment]
* [ ] When "Reusing the tables" was successful, do we want to show this green tick icon, or maybe show the text as a "success" notification?

![reusing the tables success](https://cloud.githubusercontent.com/assets/466765/8028075/80c570c4-0df9-11e5-94ef-d0343734ea1a.png)

**Comment by mnapoli** [comment]
Fixed, except the one related to checkboxes: I believe there is a JS somewhere that replaces the radio/checkboxes with some other HTML that creates a styled radio/checkbox. For example for a radio:

```html
<input type="radio" name="foo">
```

gets replaced with:

```html
<div class="form-radio" style="position: relative;">
    <input type="radio" name="foo" value="today" style="position: absolute; opacity: 0;">
    <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
</div>
```

This JS isn't loaded during the installation (because that only loads the base CSS I guess), so that's why checkboxes are not styled. I don't know if it's a lot of work/if it's worth it, what do you think?

Regarding this:

![](https://cloud.githubusercontent.com/assets/466765/8028060/1e9ef74e-0df9-11e5-9f61-efb1fd9bdd58.png)

I also think it doesn't look very good. The problem is that form inputs are supposed to take 50% of the width, making exception isn't easy especially since the form is built using QuickForm (so I can't even put the long description in a form help div). I want to get rid of QuickForm since it's limiting and it's only used in the installation, but that requires work…

**Comment by mattab** [comment]
> This JS isn't loaded during the installation (because that only loads the base CSS I guess), so that's why checkboxes are not styled. I don't know if it's a lot of work/if it's worth it, what do you think?

sounds good, let's leave them un-styled. 

>  I want to get rid of QuickForm since it's limiting and it's only used in the installation, but that requires work…

Maybe we can tackle this (removing quickform) if really this is what is blocking us from styling these in the installer. it's on the mid term goal to remove code in `libs/` folder so removing `libs/HTML` sounds good. Btw it's used in the Installation also for: Login form and Privacy manager form (`FormDefaultSettings`). 

> [...] put the long description in a form help div

+1 it would look perfect

**Comment by mattab** [comment]
@mnapoli what is the next step, could this issue be closed?

**Comment by mnapoli** [comment]
This issue isn't finished as the feedback you listed isn't fixed yet.

**Comment by mattab** [comment]
End of install form was styled (in  #8135)

![look good](https://cloud.githubusercontent.com/assets/466765/8265936/641e4fa8-1764-11e5-9db9-0c12a14e4678.png)

in general I think the install looks great now :+1: :sunny: 

(any tweak let's maybe note in https://github.com/piwik/piwik/issues/8157)
