### ISSUE TITLE
New design for Administration screens

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7587]
The goal of this issue is to get feedback on the new proposal for the following Administration screens. This look presented, once agreed on, would be automatically used across all Administration menu and User menu screens.

Refs  #7585

# Manage Users

#### Current design 
https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/UIIntegrationTest_admin_manage_users.png

#### Proposed design

![users-new](https://cloud.githubusercontent.com/assets/466765/6912254/389f9866-d7ca-11e4-8015-7765d7f0d481.png)

# Manage Websites
#### Current design 
https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/UIIntegrationTest_admin_manage_websites.png

#### Proposed design

![websites-new](https://cloud.githubusercontent.com/assets/466765/6912255/3bc7395e-d7ca-11e4-9f6c-0dc98822d170.png)

# User Settings
#### Current design 
https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/UIIntegrationTest_admin_user_settings.png

#### Proposed design

![usersettings-new](https://cloud.githubusercontent.com/assets/466765/6912256/41a22154-d7ca-11e4-9f8b-d78a163c625c.png)

# Tracking code
#### Current design 
https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/UIIntegrationTest_admin_manage_users.png

#### Proposed design

![trackingcode-new](https://cloud.githubusercontent.com/assets/466765/6912259/46e76d5e-d7ca-11e4-9cf7-df780eb147c5.png)

**What do you think?**

**Comment by mattab** [comment]
note about *Manage users*: the design does not show all UI elemenst from current screen but it gives an idea. This particular screen will need a UX improvement as it is not super-usable yet, see:  #6187 (Improve User Management and assigning permissions to users)

**Comment by sgiehl** [comment]
Much clearer and easier to handle I think :+1:

**Comment by mnapoli** [comment]
:+1:

**Comment by mattab** [comment]
Maybe it would make sense when working on this issue to also implement this nice usability feature:  Not visible "Save" button in Settings #5978

**Comment by tsteur** [comment]
Is this here to collect feedback re design or UX?

Re design:
* Contrast is very low eg. in inline help box and select fields
* In users / websites screen maybe it is possible to make a rather "flat" design with less lines/borders

**Comment by mattab** [comment]
> Is this here to collect feedback re design or UX?

Yes it's here to collect feedback and there is still possibility to ask for changes/improvements to design team

**Comment by mnapoli** [comment]
For the record there is this PR regarding the forms redesign: #7960 (doesn't contain the redesign of the site and user managers).

**Comment by mnapoli** [comment]
Pull requests: #8001 and #8002

**Comment by mnapoli** [comment]
This issue is finished except for the user manager. I will be moving that topic into a separate issue and will be moving this to 3.0 as we want to release 2.14 soon (can be rediscussed). Also since the site manager is still a moving target (because we want to track other things than websites) doing this now might be tricky (we want to avoid duplicating the styles between the site manager and the user manager).

-> #8119
