### ISSUE TITLE
New design for Administration Left menu

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7588]
The goal of this issue is to improve the design of the Administration Left menu, also used in the User menu screens.

Related to:  New design for Administration screens #7587 and  New Piwik design when main menu is on the left #7589 

### Current menu design

![menu admin](https://cloud.githubusercontent.com/assets/466765/6912403/28168510-d7cd-11e4-99a7-0368b2b49598.png)

### Proposed new menu design:

![menu-new](https://cloud.githubusercontent.com/assets/466765/6912413/5820a736-d7cd-11e4-89b7-e2ba4b0b6a08.png)

**Comment by mnapoli** [comment]
We need a way to keep visible which item is selected (red underline was good) except that :+1: 

I especially like the "return to dashboard", this was a big problem for me when I started using Piwik (in the sense that it wasn't hard to return to the dashboard, but it was confusing)

**Comment by mattab** [comment]
Fixed in  #8936
