### ISSUE TITLE
New Piwik design when main menu is on the left

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7589]
The goal of this issue is to propose and discuss a new design for Piwik when the main reporting menu is on the left of the screen.  

Overall we've been working on making all menus in Piwik easy to use and find out what you're looking for (see discussion and issues linked in #6917). Putting the main menu to the left will be an important improvement, and we want to set it as default for all users (#7169). 

## Current left menu design

![piwik org demo2 - web analytics reports](https://cloud.githubusercontent.com/assets/466765/6912635/d967d762-d7d0-11e4-95ae-cf7d62336bcb.png)

There are some issues like the margins are not right and the Calendar / Website Selector / Segment selector seem to be being randomly put there. 

## Proposed left menu design

The goal is to make Piwik design shine and find the alchemy to display the following UI elements: left menu + top menu + Selectors (website, segment, calendar)

Coming soon!

**Comment by Globulopolis** [comment]
Looks good, but... It's very good idea to add an icon in this menu for Hide/Show menu. And I think we must improve this for mobile. So for users from mobile devices menu should be hidden by default.

Something like this(from Joomla):
![untitled-1](https://cloud.githubusercontent.com/assets/740757/7111047/5594edb0-e1c3-11e4-8faf-938120838835.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/740757/7111048/5c058d8a-e1c3-11e4-98fc-e653e53cb55a.jpg)

**Comment by mattab** [comment]
Here is note about Q/A: 
 * test to create a custom dashboard with name `<img src=1 onerror=alert(document.domain)>` -> check that the left menu is not too wide and the text is wrapped as expected

**Comment by mattab** [comment]
Here are four version of the proposed left menu designs:

### Version 1
![left](https://cloud.githubusercontent.com/assets/466765/7310153/6aab39d2-ea7b-11e4-942d-700dd39735bf.png)

### Version 2
![left1](https://cloud.githubusercontent.com/assets/466765/7310154/6d4a865c-ea7b-11e4-96a5-0ea9a3110a2b.png)

### Version 3
![left2](https://cloud.githubusercontent.com/assets/466765/7310155/7054f440-ea7b-11e4-8df2-93b432184f91.png)

### Version 4
![left3](https://cloud.githubusercontent.com/assets/466765/7310156/7321d8f0-ea7b-11e4-9e24-361a06713c88.png)

### Summary
which one do you prefer?

Do you maybe have any other suggestion?

**Comment by mnapoli** [comment]
They are nice, version 1 is my favorite.

**Comment by RMastop** [comment]
+1 for version 1

**Comment by quba** [comment]
version 1

**Comment by mattab** [comment]
fyi: moved to 2.15.0 milestone

**Comment by mattab** [comment]
**Note: requirement**: for accessibility purpose, contrast between foreground and background colors should be high enough. (from #7093)

**Comment by tassoman** [comment]
Version 1 :+1: 

Version 3 header looks cool. My ideal version would be a v.1 with header from v.3

**Comment by tsteur** [comment]
Once we have the left menu we should remove ZenMode I think. The left menu would be ideally "collapsible" / "minimizable" meaning it would maybe take only a width of 40px instead of 260px by showing only little icons or little letters.

**Comment by mattab** [comment]
Tentatively moving to 2.15.0 as it would be awesome++ to have left menu in our LTS version :100:

**Comment by tsteur** [comment]
We are currently working on the left menu and it currently looks like this but it is work in progress:

![screenshot at sep 21 14-07-19](https://cloud.githubusercontent.com/assets/273120/10047701/a7de88fc-620f-11e5-97c9-578b28267084.png)
![screenshot at sep 21 14-07-47](https://cloud.githubusercontent.com/assets/273120/10047702/a7e7d308-620f-11e5-901d-21fe423504d1.png)

If you want to test it feel free to check out the branch `left_menu_2`. Expect still several minor issues as it is very work in progress. We'll also introduce a search that will bring some awesome features over time, the current version is not really responsive yet but we aim to make it happen for 2.15.0 but there's a good chance we don't have the time for it.

**Comment by tsteur** [comment]
FYI: I implemented Version 1 of comment https://github.com/piwik/piwik/issues/7589#issuecomment-95759373 as an alternative in `left_menu_3` compared to the one previously mentioned in `left_menu_2`. Only the header top bar is implemented a bit different for Version 1 since I could not simply move the "user and sign out" link to the right.

**Comment by mattab** [comment]
You can now view the proposed designs on the live demo!

 * Design 1 = Left Menu with search bar above, top menu with icons, minimal http://demo-newdesign1.piwik.org/
 * Design 2 = Left menu with lines and left colors, structure http://demo-newdesign2.piwik.org/
 * Current design = http://demo.piwik.org/

*(Note: the demos will take a long time to load because the [development mode is enabled](https://developer.piwik.org/guides/getting-started-part-1#enable-development-mode) - the two newdesign demos are refreshed every 3 minutes with the latest code from git.)*

**What do you guys think?**

**Comment by tassoman** [comment]
I have to report two issues in the NewDesign2 
* language's select z-index is insufficient and popups hidden by calendar box
* click on websites select box pushes down all the widgets layout

One issue in NewDesign1:
 * language select box pops under the "x visits" label of the map widget

I didn't browsed by tablet or mobile but NewDesign1 for me is nicer and cleaner.

**Comment by jdeyla** [comment]
Hi guys, it's a redesign, so comments on accessibility could be posted in the wrong place but these tips can help to understand what must be done:

 - links or clickable items  must be easly recognizable (es. an underscore o border under elements in content is needed, different color isn't enough, in a manù there's no need to chande anything)

- make focus (or hover) visible in the same way, and not just using a chenge of colour (an image, a border, or a change of background helps more)

 - put a little wai aria and html5 in elements, don't use just divs, but also sections and roles, and placeholder (ex. search)

For usability:
- white and spaces are great, but some backgrounds or lines somewhere helps to identify better different areas. Contrast is the key of easily finding thuings in interfaces. I found this article very intresting and complete  https://designschool.canva.com/blog/contrasting-colors 

my opinion is
2nd design, but with something different in the active mennu (what about a red background? ugly?)

![piwik_forums_-_report_web_analytics_-_piwik_-_2015-10-01_13 05 53](https://cloud.githubusercontent.com/assets/832590/10219209/3b966474-683d-11e5-908a-53844114f474.png)
)

**Comment by tsteur** [comment]
It might be also worth to alternatively introduce a "high contrast mode" or to have a high contrast theme"

**Comment by jdeyla** [comment]
no need to do so, a good interface is good also for mobile experience (everywhere in every light condition). keep it simple

**Comment by Glisse1** [comment]
design no2 is "sexier" but i also consider it needs a more obvious background for current selection

**Comment by mattab** [comment]
Everyone, the left menu is available in latest Piwik beta 16 :heart: 

if you have any comment Re: accessibility or other feedback, please post here or create a new issue.

**Comment by gaumondp** [comment]
Just wanna add that Piwik Demo has it already (2.15.0-b16) for you to try...

http://demo.piwik.org/

**Comment by tassoman** [comment]
Mr @jdeyla and I we did already an a11y report on menu in the past. Does anyone gave an eye on it?

It's a wiki page https://github.com/piwik/piwik/wiki/Piwik-Accessibility-Analysis#menu

**Comment by tassoman** [comment]
I've updated the a11y analisys wiki page removing already fixed paragraphs. There still some mess in the areas still mentioned in the document.

Talking about the left side menu, the main problems are:

* menu is not focusable browsing by keyboard
* menu should be WAI-ARIA

I'm trying to figure out how to help by a pull request, I'll keep you informed.

**Comment by mattab** [comment]
> I'm trying to figure out how to help by a pull request, I'll keep you informed.

Let's continue discussion in:
 * Pull request: https://github.com/piwik/piwik/pull/9149 or issue https://github.com/piwik/piwik/issues/9148
 * Accessibility issue: https://github.com/piwik/piwik/issues/4167

**Comment by Amenel** [comment]
I've updated to 2.15.0 and I'm wondering what became of two valid (in my eyes) suggestions made by @jdeyla about the highlighting color and @Globulopolis about the "Hide sidebar" icon. I haven't seen any of the two points in the links posted by @mattab to issues #9148 and #4167.

The current design does not stand the comparison to the mock-up by @jdeyla in terms of clarity. Nor does it remind of the 4 designs initially suggested: the markers of currently selected items are no longer there in 2.15.0...

As to the hide sidebar feature, it makes total sense for some users like me who only use the dashboard entry of the menu: in 3 years, I've never needed any of the now top-level entries other than Dashboard... Such rare use cases are out there.

I'm not disabled in any way but I still think both suggestions were valuable. Are they implicitly dismissed? Or were they taken into account some place that I didn't find?

**Comment by tsteur** [comment]
We'll implement a toggle for the left menu at some point. Right now some other features and fixes just have a bit of a higher priority. Issue for toggle of left menu is here: https://github.com/piwik/piwik/issues/9263

Optimizing Piwik for mobile and making it more responsive is not really one of our priorities currently as we have a [Piwik Mobile 2 app](http://piwik.org/mobile/) for Android and iOS. This might change though over time and we will probably always do some tweaks over time.

**Comment by Forsskieken** [comment]
Hi There,

When I implemented custom dimensions I needed to upgrade the piwik which I did.
On Internet explorer 11 the Left menu is now alone on the top and hides for example the date or period.

Yesterday I did a new install of the 2.16.rc2 and noticed the same behaviour.

I have no problem on firefox or chrome

[https://drive.google.com/file/d/0B74nSQnUFHPDN3FYMHI3anBKSUE/view?usp=sharing](url)

**Comment by tsteur** [comment]
We'll have a look, thx

**Comment by tsteur** [comment]
I just tested on IE11 and MS Edge with http://demo.piwik.org and it seems to work fine. Can you open the demo Piwik with your browser and see if it happens there as well? 

If it works on demo, maybe try to clear your cache in `tmp/assets/*`, make sure no adblocker or similar extensions are active, and make sure HTML files can be served by your webserver

**Comment by Forsskieken** [comment]
Hi There,

Before coming back to you I tested several things..
I noticed that indeed the piwik.org is fine
mine http://dgcmdc004 is not

I'm running this on a Windows server 2008 with IIS

I did as advised..
Then I noticed a 2.16 release and installed that one, only the
config.ini.php file was used from before..
When I do a new install I always have a small error complaining the /tmp
directory isn't writable..
and a http://dgcmdc004/plugins/Morpheus/images/logo.svg Failed to load
resource: the server responded with a status of 404 (Not Found)
I checked however on the server and the logo is there ?

can you please explain me what I'm doing wrong

Kind regards
Guy Forssman






2016-02-03 21:53 GMT+01:00 Thomas Steur <notifications@github.com>:

**Comment by tsteur** [comment]
Make sure that the `tmp` directory is writable. Re failing logo do you mind asking in our Forums http://forum.piwik.org/ where someone can maybe help? It looks like a not correctly configured server maybe and we can do much here.

**Comment by Forsskieken** [comment]
Hi There,

I found the error..
It seems piwik serves the pages as
<meta http-equiv="X-UA-Compatible" content="IE=EDGE,chrome=1"/>

I had to change it to
<meta http-equiv="X-UA-Compatible" content="IE=8,chrome=1"/>

Kind Regards Guy Forssman

2016-02-10 8:40 GMT+01:00 Thomas Steur <notifications@github.com>:

**Comment by tsteur** [comment]
I couldn't reproduce it with edge, or IE 11. Is someone else experiencing this issue as well?

**Comment by tassoman** [comment]
http://dgcmdc004 looks like an intranet link, so I suppose that IE is using "compatibility mode" for all the websites inside the intranet network.

I solved that oddity avoiding IE browsers connected inside my custom authentication plugin. I'm using DeviceDetector to exclude IEs before 11.0 version. :wink: 

As far I can remember I talked about it when we discussed on IE8 support abandoning: #4620

**Comment by Forsskieken** [comment]
It is indeed a intranet site...
The policy here is that every browser is IE11 only a few people have access
to chrome..

It's when I played with the document mode settings and lowered to IE8 that
the site menu whent to the left..I then noticed in the source view that
even when we use IE11..The page's show's a <meta http-equiv="X-UA-Compatible"
content="IE=EDGE,chrome=1"/>

It shows a small [object] [object] error window ...which is related to the
Dashboard section as pushing that button/tab isn't working. everything is
 in 1 column.

I would like to hunt this down but have no clue where to begin..

The 2008 R2 server uses IIS 7.5

Kind Regards
Guy Forssman


2016-02-16 17:26 GMT+01:00 Tassoman <notifications@github.com>:

**Comment by tsteur** [comment]
@mattab are we mentioning this already in an FAQ?

**Comment by mattab** [comment]
@tsteur What did you refer to? If I can improve something in a FAQ, please let me know

**Comment by tassoman** [comment]
@mattab , @tsteur this is [my reference](https://github.com/piwik/piwik/issues/4620#issuecomment-48314201). In brief I gave up to IE <11. Forbidding them by use of _Device Detector _in my authentication plugin. Now we're testing IE11+WIN7 looks like being fine.

**Comment by Forsskieken** [comment]
It's solved on my side by solving the svg mime settings.

In a Intranet only site a map where you're customers come from aren't that
importend to show on a map. Therefore we overlooked to long that there
wasn't a map at all.
Once I corrected that, the menu felt in place to

regards
Guy Forssman

**Comment by tsteur** [comment]
@mattab can we have an FAQ like "Piwik is not working in an Intranet with IE11"?

We could mention there are known problems, link to an issue where we explain a workaround that requires changing the code to set meta element `<meta http-equiv="X-UA-Compatible" content="IE=8,chrome=1"/>`. Also maybe we can actually fix it by setting different meta elements depending on IE version via JavaScript (likely not possible via HTML since newer IE versions do not support this anymore).

**Comment by mattab** [comment]
@tsteur Not willing to document users to set a HTML code manually, as we recommend against such practise. Maybe it's a case to create a new issue where we could add a config setting to set appropriate `<meta>` elements on IE11?

**Comment by tsteur** [comment]
yes that would be great @Forsskieken do you mind maybe creating an issue?
