### ISSUE TITLE
Missing indication of unique visitors in one day report

### ISSUE THREAD

**Issue by mosaiqmedia** [piwik/piwik#7591]
Dear Piwik-Team, 

Every time I set up an report wich extends the period of one day, the unique visitors are not included (the report just shows the visits in total but not the unique visits)

![screenshot](https://cloud.githubusercontent.com/assets/11733081/6914136/c24006e8-d787-11e4-992c-79cdad970d3f.png)

Here the requested Screenshot. As you see the unique visitors do not appear in the email-report choosing a period of time . The still appear if I choose a date for the report instead of a period of time extending 1 day). I would be very glad if you could give me a hint how I can fix this, since my client needs it very urgently. 

Kind regards

Teja

**Comment by mattab** [comment]
Hi @mosaiqmedia 

by default Piwik only processes unique visitors for days, weeks and months. to get it for year and date ranges, you can enable this in the INI config file, see this FAQ: https://piwik.org/faq/how-to/faq_113/
