### ISSUE TITLE
Release notes 2.11 missing database upgrade

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7592]
Please mention the dataase upgrade: https://github.com/piwik/piwik/blob/50c9d9bdc0eada5de5a6b693740528a36497ce42/core/Updates/2.11.0-b4.php#L31

http://piwik.org/changelog/piwik-2-11-0/

**Comment by mattab** [comment]
Hi @ThaDafinser it's not a major DB Upgrade that's why we don't mention it (in changelog we only mention major db upgrades for example which change the schema).
