### ISSUE TITLE
Piwik.org SSL configuration issues

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7598]
I'm opening this issue of behalf of @bolera, per his reports in #7576

> the builds.piwik.org server doesn't want to "talk" to us I think the issue can easily be solved by reconfiguring the server without changing any code in Piwik.

Explanation

> However, I still think that your server is configured incorrectly.
> Today I looked thru the curl bug tracker and found an option to enforce TLS1 in connection with that unspecified SSL error. Et voila, adding that option makes the connection work:
> `curl -o piwik.latest.tar.gz https://builds.piwik.org/piwik-latest.tar.gz -k -vvvv --tlsv1`
> Remove the --tlsv1 at the end and it fails. All other servers I tried and which also have SSL2 and SSL3 disabled (as yours) do not fail.
> It seems it simply does not reply to an SSL2/non-TLS client hello, not even to tell "use TLS". Remember, so far it seems that builds.piwik.org is the only one that creates this error with curl.
> 
> Look at the differences (I removed the asterisks as the Markdown interprets them wrongly):
> 
> connect to a working server: SSLv2, Client hello (1): SSLv3, TLS handshake, Server hello (2):
> connect to builds.piwik.org without --tlsv1: SSLv2, Client hello (1): -> fails, apparently with no server response
> connect to builds.piwik.org with --tlsv1: SSLv3, TLS handshake, Client hello (1): SSLv3, TLS handshake, Server hello (2):
> So, seems to me that builds.piwik.org should enforce TLS connections, but instead either doesn't reply or replies with a "no".

**Comment by bolera** [comment]
Thanks to both of you!

**Comment by mattab** [comment]
Note: there was also this issue created by a third party researcher to describe some ways the SSL configuration could be improved: https://github.com/isvsecwatch/httpstracker/issues/22 - piwik.org hosting team will definitely make improvements there but this will take a few months.

**Comment by pilere** [comment]
I does this explain why the oneclick update process fail now ?
![image](https://cloud.githubusercontent.com/assets/3319800/7153916/ef3e6188-e350-11e4-9bee-75a06855791e.png)

**Comment by Globulopolis** [comment]
@pilere yes, but it's not a piwik problem. You should update cacert.pem for you cUrl. Download the file http://curl.haxx.se/ca/cacert.pem and place somewhere. When in php.ini add
```
[cURL]
curl.cainfo = "path_to\cacert.pem"
```
And reload apache.
