### ISSUE TITLE
Encapsulate Piwik environment creation (including DI container creation) in single class

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#7601]
This will make it possible to store more objects in DI, making testing easier/cleaner, and we will also be able to get rid of StaticContainer (eventually).

Current plan is to encapsulate environment creation within a Bootstrap class, and use it in new classes that encapsulate application entry points (ie, tracker/normal web requests/archive.php script/console etc.).

**Comment by mattab** [comment]
is this something we're working on this sprint? if so please move it to 2.13.0

**Comment by diosmosis** [comment]
Fixed in https://github.com/piwik/piwik/pull/7644.
