### ISSUE TITLE
Piwik doesn't make the difference between Internet Explorer and project spartan

### ISSUE THREAD

**Issue by baywet** [piwik/piwik#7603]
Microsoft publicly released a new browser yesterday.
After trying it out it seems that Piwik doesn't make the difference between Spartan and IE users.
It'd be great to have this information.

**Comment by baywet** [comment]
IE11 on w10 (10049):  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0
Spartan (same system): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0

**Comment by ThaDafinser** [comment]
@baywet can you please close the issue here and report it here: https://github.com/piwik/device-detector/issues

Thank you :-)

**Comment by baywet** [comment]
@ThaDafinser done! Sorry for posting at the wrong place.
