### ISSUE TITLE
Notice: Undefined index: nb_users in overview.php - Wordpress Bug

### ISSUE THREAD

**Issue by nopenopenope** [piwik/piwik#7604]
Hi guys,

as documented here http://forum.piwik.org/read.php?2,125685 there might be a bug in the very latest version of WP-Piwik. 

The dashboard function generates a notice error when using WP-Piwik. I'm pretty sorry, I already hotfixed the error for me so I do not have the exact error anymore, however it looks like that the variable nb_users has to be initialised before it gets used. 

In overview.php theres an array in the beginning of the file. If you add 'nb_users' => 0, to the array it seems fixed. I hope you can reproduce the error on your own, if not, give me a shot, I'm pretty sure I can reproduce it again, but I would really appreciate it to not unfix it. 

If you have any questions, give me a shot!

Cheers

**Comment by mattab** [comment]
Hi @nopenopenope 
thanks for the report - it's actually a little bug in the great WP-Piwik for Wordpress. Can you please report it in: https://wordpress.org/support/plugin/wp-piwik (if you still have the bug in the latest plugin version)

**Comment by mattab** [comment]
I've also notified André WP-Piwik lead developer
