### ISSUE TITLE
Do not pre-process custom segments when pre-processing date ranges to load by default

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7611]
In some cases processing every custom range which user selects to display after login may cause huge performance issues. For example in case:
- 2k websites
- approx 4k users
- 500+ segments (for single sites, but still)

When we want to process multiple ranges archiving cannot complete in less than 24 hours (segments are also processed for ranges).
Therefore I propose to introduce config param to prevent this behaviour.

Removing range as available periods will cause UI to break after login attempt, also we don't want to disable segments entirely, so it's not an option.

Please let me know what do you think?

**Comment by gaumondp** [comment]
Did you tried this plugin ?

http://plugins.piwik.org/RerUserDates

*"This Piwik Plugin lets you hide custom date range selection from calendar for regular users, also lets you avoid users setting ranges as default value in their profile."*

**Comment by mattab** [comment]
> Removing range as available periods will cause UI to break after login attempt, 

covered in #7615

**Comment by mattab** [comment]
>      When we want to process multiple ranges archiving cannot complete in less than 24 hours (segments are also processed for ranges).

Maybe a good trade-off solution would be to *not* pre-process any segments for those date ranges set as "Default date to load" ?

**Comment by mnapoli** [comment]
If #7615 is fixed does that mean this ticket is fixed (because then you can disable ranges)? Or is there something left to do?

**Comment by mgazdzik** [comment]
@mattab  - yes, it could be also a reasonable thing to do. I can't tell at this moment how much impact will processing non segmented ranges cause for big instances.
@mnapoli - this ticket is merely about overhead added by processing custom ranges by cron archiving process and processing time increase caused by that

**Comment by mattab** [comment]
IMHO it is not a problem to pre-process custom date ranges even with 5000 users or more. At most there will be 6-7 different possibilities of date ranges so it will only add 6-7 requests per website, which is not big.

however there is a large performance overhead with the fact that all custom segments are pre-processed for those custom date ranges (which could often add extra 7 * 200 requests for each website!). We will fix this by not pre-process segments for date ranges.

**Comment by mattab** [comment]
PR: #7635
