### ISSUE TITLE
missing tmp folder in ZIP

### ISSUE THREAD

**Issue by robinsherwood** [piwik/piwik#7612]
Discussion: http://forum.piwik.org/read.php?2,125778
The ZIP folder is missing the tmp folder. This seems to be a bug. Now the tmp folder is created by piwik - undeletable :(

**Comment by mattab** [comment]
Thanks @robinsherwood for report.

we used to package the `tmp/` folder but seems not the case since 2.10.0 or so - 

Tasks
 * add back tmp folder with .gitkeep file
 * add unit test to make sure the tmp/ folder is there in Piwik

**Comment by mnapoli** [comment]
I've pushed the folder back, which permissions was it supposed to be, 755?

**Comment by robinsherwood** [comment]
In my active running install it is 755

**Comment by mattab** [comment]
* I'm not sure now what it should be but it's important to set same permission as it was before it was removed
 * let's add an automated test that will detect in case the folder is missing in the future

**Comment by mnapoli** [comment]
The test was added in the commit already.

I've downloaded Piwik 2.9.0 and the permissions are 755, so I'll apply those permissions.

**Comment by mnapoli** [comment]
Turns out that git doesn't store permissions, so it's now just like it was before.

**Comment by mattab** [comment]
@mnapoli could you add a unit test to verify the tmp/ folder is in git? i'm afraid otherwise we may delete it again without noticing.

**Comment by mattab** [comment]
Ok I see now that the test exists already in https://github.com/piwik/piwik/commit/2f524cccc39b6326b2ad664b63aa21eb7e7c566c :+1:

**Comment by mnapoli** [comment]
yes that's what I said in the comment ;)
