### ISSUE TITLE
install procedure not satisfied with 755

### ISSUE THREAD

**Issue by robinsherwood** [piwik/piwik#7613]
Switching folders to 777 is letting me to do an install, but I wouldn't call it clean.

**Comment by robinsherwood** [comment]
Is probably/perhaps to be seen in conjunction with https://github.com/piwik/piwik/issues/7612

**Comment by mattab** [comment]
if #7612 is fixed, would this solve your problem here as well? if so we can close it and mark it as duplicate

**Comment by mattab** [comment]
feel free to re-open or create new issue if you still have a problem in the future Piwik 2.13.0 which will include the tmp/ folder
