### ISSUE TITLE
Unable to log into Piwik after disabling ranges as period in UI

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7615]
How to reproduce:
- log into Piwik, set for ex. "last7" as default date, log out,
- set ```enabled_periods_UI = day,week,month,year```
- try logging back into Piwik - you should be served an error message saying that period is invalid.
I guess that in such case, user setting should be ignored and "yesterday" loaded instead or something like that.

Please let me know if this is enough to reproduce issue

**Comment by mattab** [comment]
Thanks for report @mgazdzik

**Comment by mnapoli** [comment]
PR: #7623
