### ISSUE TITLE
import_logs.py doesn't work

### ISSUE THREAD

**Issue by lmgichin** [piwik/piwik#7616]
While trying to import logs : 

./import_logs.py --idsite=2 --url=http://www.xxx.org  /var/log/httpd/xxxxxx_log
Traceback (most recent call last):
  File "./import_logs.py", line 2099, in <module>
    resolver = config.get_resolver()
  File "./import_logs.py", line 880, in get_resolver
    return StaticResolver(self.options.site_id)
  File "./import_logs.py", line 1221, in __init__
    'SitesManager.getSiteFromId', idSite=self.site_id
  File "./import_logs.py", line 1204, in call_api
    return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)
  File "./import_logs.py", line 1193, in _call_wrapper
    raise Piwik.Error(message)
__main__.Error: Internal Server Error

**Comment by mattab** [comment]
Hi @lmgichin thanks for the report.

Here the problem is that the `--url` should point to your Piwik server. If you already have pointed it to your Piwik server, then there may be a problem accessing Piwik from the console. Check your server error log files on Piwik server.

**Comment by mattab** [comment]
we get this report very often in the forums. Maybe we could improve log analytics to help users know what to do when this error occurs...

**Comment by mattab** [comment]
Thanks for the report. created an issue in the log-analytics issue tracker: https://github.com/piwik/piwik-log-analytics/issues/64
