### ISSUE TITLE
Please help me, 0 E-commerce orders , Orders are not tracking

### ISSUE THREAD

**Issue by amarsdml** [piwik/piwik#7621]
Hi, I am new to piwik, Please help me.

I am able to track visitors count, visitors logs etc but eCommerce orders are not tracking.
But in my Back end i can see the count of orders.

I followed piwik syntax of addEcommerceItem and trackEcommerceOrder

![screenshot from 2015-04-02 17 26 33](https://cloud.githubusercontent.com/assets/2852812/6963515/d764b028-d95d-11e4-8e0c-10ac3104feee.png)
ing.

**Comment by mattab** [comment]
Hi there,

please ask in forums: http://forum.piwik.org/

and post there the JS code that is written in your ecommerce pages.

Cheers
