### ISSUE TITLE
Create and maintain up-to-date the Piwik Roadmap 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7624]
The goal of this issue is update the [Piwik Roadmap](http://piwik.org/roadmap/) page with an accurate description of the roadmap for Piwik including new major features, new plugins, improvements to the platform.

This new roadmap should be realistic (with suggested dates for major features) and inspiring to the community and users. The roadmap will be designed to let Piwik fill its mission which is: `“To create, as a community, the leading international open source web analytics platform, that gives every user full control of their data.”`

Stay tuned!

**Comment by mattab** [comment]
[Piwik Roadmap](https://piwik.org/roadmap/) page has been updated and includes some specific dates for groups of features (September 2015 and December 2015!)

![roadmapp](https://cloud.githubusercontent.com/assets/466765/8101948/3034c9f6-1070-11e5-9c31-028e78e7c972.png)

This roadmap is our selection of projects to help create the best possible free/libre and open analytics platform that gives everyone full control of their data. We keep our focus on Web analytics and Mobile analytics, but we also think about making Piwik able to collect data from any other source (servers, internet of things, sensors, etc.). 

With Piwik 3.0.0 we will also invest in the core platform to make it better, faster, stronger, with new and revisited APIs for plugin developers.Feedback from the community, colleagues, clients, team members was key in setting those priorities. 
 
Thanks everyone who has helped so far, and will help make our shared vision a reality!

We look forward to reading your feedback here or on other issues.

**Comment by gaumondp** [comment]
I find the "number of plugins in the marketplace" goal a bit awkward...

Sure with good documentation and support for community developers it's something possible but making it a goal looks odd because you dob't have full control on such a thing.

Maybe I'm over-analyzing...

**Comment by mattab** [comment]
@gaumondp When we [launched the marketplace](https://piwik.org/blog/2013/12/piwik-2-0-release-announced-biggest-best-release-yet/) a year and a half ago, it was one of our objectives to one day reach 50 plugins released on the marketplace. After 18 months are getting there and for us it's a huge achievement which we are really proud of. 

We hope the marketplace will keep growing and more interesting plugins will be available, we can set our next goal to 100 plugins on the Marketplace, maybe during Piwik 3.X ?

**Comment by mnapoli** [comment]
I think you missed the point:

> but making it a goal looks odd because you don't have full control on such a thing.

In other words we don't make the 3rd party plugins.

**Comment by mattab** [comment]
I've updated to 100 plugins & moved it to Mid term.

What did we do to try get developers excited about the Piwik platform? In the last 18 months, we launched the [Marketplace](http://plugins.piwik.org), created public APIs for plugin devs, launched [developer guides](http://developer.piwik.org/), a series of [plugin dev blog posts](https://piwik.org/blog/category/development/), a forum for plugin developers... With Piwik 3.0.0 we will continue investing in creating a great platform and ultimately helping developers create great plugins. 100 plugins will be do-able I think, but it may take a while... I think to go beyond 100 we will need to make the platform much more attractive and easier to extend (let's start with Piwik 3.0.0!).

**Comment by gaumondp** [comment]
Let me add I'm not ranting nor trying to sound negative. Just being realistic and remind you where limits are. ;)

Like @mnapoli said: You don't provide the 3rd party plugins...

And yes, I'm looking forward to 3.0 and plugins to choose from (and more important, Core stuff missing like percents numbers mentionned in #6770 . Yes I sound like a broken record.(That was ranting, oops...)
