### ISSUE TITLE
Ecommerce > Overview view shows no results when segment was chosen

### ISSUE THREAD

**Issue by kaz231** [piwik/piwik#7625]
Steps to reproduce:
- generate a few actions using WooCommerce PiwikPRO Integration (a few orders and abandoned carts)
- go to piwik and open Ecommerce > Overview view
- create and choose a segment for Actions > Page Name (to shows e.g. orders with specific item)

Result: 0 value for all metrics.

I found that segmentation for ecommerce is trying to join results from log_conversion with log_link_visit_action, what causes return of empty set, because log_conversion rows with idgoal equal to -1 or 0 don't have relation to log_link_visit_action. Maybe should there be a joining with log_visit instead of log_link_visit_action ?

**Comment by mattab** [comment]
Thanks @kaz231 for the report. I forgot about it but we had this issue as well: https://github.com/piwik/piwik/issues/6593
