### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by bitbangx** [piwik/piwik#7626]
I'm trying to make requests to Piwik API via Ajax but Piwik doesn't set 'Access-Control-Allow-Origin' field in header. 
I modified config.php.ini and added cors_domains[] = * but nothing changed. 
Using version 2.12.1

**Comment by mattab** [comment]
Hi @bitbangx 
did you add the cors_domain line below `[General]`

**Comment by bitbangx** [comment]
[General]
salt = "                                                    "
trusted_hosts[] = "                    "
cors_domains[] = *

**Comment by mattab** [comment]
I'm not sure if this will work but can you try ` cors_domains[] = "*"` (with double quotes?)

**Comment by bitbangx** [comment]
Nope, It doesn't work

**Comment by mattab** [comment]
Let's investigate and see if we can reproduce this

**Comment by mattab** [comment]
Thanks @bitbangx for the report!
we documented something that was never implemented. Good to know this now works as documented :+1:
