### ISSUE TITLE
Add Help link to top menu

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7642]
Currently `Help` page is available via the Top user menu > Help. It was suggested to add the `Help` link to the top menu for direct access.

Follows up #7637

**Comment by mattab** [comment]
I noticed a little issue: 

 * when the `Help` link is clicked,
 * Got: on page reload it highlights in top menu the User menu.
 *  Expected: to have highlight on `Help` instead.

reproduce URL: http://demo.piwik.org/index.php?module=Feedback&action=index&idSite=1&period=day&date=yesterday

**Comment by mnapoli** [comment]
Good catch! I have the enterprise admin locally which overrides the link, so I tested with and without but obviously not enough!

See #7657
