### ISSUE TITLE
Installation welcome screen doesn't load

### ISSUE THREAD

**Issue by Orrico** [piwik/piwik#7651]
I uploaded the folder of Piwik to my server. Now I can access piwik following this link http://domain.com/piwik. But the script don't run properly.
![captura de tela 2015-04-09 as 10 31 38](https://cloud.githubusercontent.com/assets/40885/7067683/a644f7e6-dea3-11e4-81de-ba77a542c23d.png)

Looking the source code of the page we can see where it's break.
![captura de tela 2015-04-09 as 10 38 06](https://cloud.githubusercontent.com/assets/40885/7067902/07231ff6-dea5-11e4-9fb0-55d5005e5c38.png)

I have tested in other two servers with the same configuration and was ok.
Someone know what's happening?

**Comment by mattab** [comment]
Hi @Orrico do you see any error in your server error log?

**Comment by tsteur** [comment]
Maybe it helps to execute `./console core:clear-caches` and to reload. Did you copy any custom plugins as well? 

FYI: At that point there is usually a `postEvent('Template.topBar)` going on which is used to render the LanguagesManager. Maybe something goes wrong there. As asked in the previous comment please have a look in the error log if possible.

**Comment by mattab** [comment]
We didn't hear from you @Orrico 
Do you see any error in your server error log?

I assume this bug is fixed in latest Piwik - if you still have the problem @Orrico please leave a comment here.
