### ISSUE TITLE
console issue to symfony

### ISSUE THREAD

**Issue by lgbff** [piwik/piwik#7653]
Hi,

when i use 
<code php
/usr/bin/php5 /usr/share/piwik/core/Console.php plugin:list
</code>
this error is diplayed:
<file>
PHP Fatal error:  Class 'Symfony\Component\Console\Application' not found in /usr/share/piwik/core/Console.php on line 22
</file>
My environment:
Debian Wheezy
Piwik 2.12.1-1 (Debian package from piwik repo)

any idea?

thx Karsten

**Comment by diosmosis** [comment]
Hi @lgbff , you should execute the `/usr/share/piwik/console` file, not core/Console.php. So, the command would be: `/usr/bin/php5 /usr/share/piwik/console plugin:list`.

**Comment by lgbff** [comment]
oh, my issue, thx for the hint.
