### ISSUE TITLE
Daily Scheduled Reports sent one hour late, if daylight saving time is active

### ISSUE THREAD

**Issue by tschikarski** [piwik/piwik#7658]
Please refer to this closed but unresolved issue: https://github.com/piwik/piwik/issues/5873

Short summary of old issue:
Daily reports scheduled for 12 are actually sent shortly after 13 o'clock. Global timezone setting is "Europe/Berlin"; Setting for all websites is also "Europe/Berlin".

We recently re-tested this issue (before and after the switch to central European daylight saving time). 
The issue had disappeared during winter time, but has reappeared with summer time. 

Therefore, it looks like Piwik is ignoring the switch to (Central European) summer time. 

Verified on Version 2.11.2

**Comment by mattab** [comment]
Thanks for the report @tschikarski - since the emails are only sent one hour late, it mostly work well, we will not yet investigate this issue. If you have other bugs with scheduled report timing, please let us know.

**Comment by mattab** [comment]
Should be fixed in #10443
