### ISSUE TITLE
consider HTML5 download attribute

### ISSUE THREAD

**Issue by mnlipp** [piwik/piwik#7663]
In HTML5 we have the "download" attribute for the a-element (http://www.w3.org/TR/html5/links.html#attr-hyperlink-download). It would be nice if piwik handled an a-alement with a "download" attribute automatically as a download. Currently (if the file extension isn't known to piwik) I still have to add "class='piwik_download'" in order to enable proper tracking as download.

**Comment by sgiehl** [comment]
I think we should implement a automatic detection for that download attribute.

Btw. in the next version it will also be easily possible to add a new download extension (might be easier than adding classes for each link) see #7444

**Comment by mattab** [comment]
Nice idea - didn't hear of this `download` attribute until now :+1:
