### ISSUE TITLE
Error While downloading the PDF report.

### ISSUE THREAD

**Issue by gangasiddhi** [piwik/piwik#7672]
Am getting following error, while downloading the PDF report.

This page contains the following errors:
error on line 3 at column 63: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.

Please help me out. Thanks in advance.

**Comment by sgiehl** [comment]
Which reports did you try to download as PDF? Does that happen always or only for certain reports?

**Comment by mattab** [comment]
Hi @gangasiddhi 

we didn't hear from you, can you still reproduce this with Piwik 2.14.0? if so please reopen the issue, and let us know the steps to reproduce.
