### ISSUE TITLE
Site Search Parameters - extra trailing white space cause no site search tracked

### ISSUE THREAD

**Issue by futureweb** [piwik/piwik#7678]
Hello,

I guess it would make sense to put a trim() around each Site Search Parameter you can configure for specific Sites / default for all Sites.
I had: "query, searchquery" instead of "query,searchquery" (note the Space) - and searchquery was not tracked as internal Site Search ...
As a Space will never occur within an URL it should be stripped away.

Bye from Austria
Andreas Schnederle-Wagner

**Comment by mattab** [comment]
Hi @futureweb 

thanks for the suggestion! It makes a lot of sense that when reading the list of parameter we should apply a white space trim.

**Comment by tsteur** [comment]
In which browser is this happening? I tried to reproduce in latest Chrome and Firefox but couldn't.

**Comment by futureweb** [comment]
Was tested with latest FF
When Site Search Params contained Space - the second was not recognized as Site Search within Live Tab. As soon as I removed the Space - it showed up as a Search

**Comment by tsteur** [comment]
Did you have this problem with "Global Websites Settings" or on a specific site? Do you remember when you configured it initially (approx., it would be enough to know like 1 month ago, 6 months ago, ...)? 

Can you maybe try to reproduce it again, and then execute those SQL queries (if possible) and post the output:

```sql
select * from piwik_option where `option_name` = 'SitesManager_SearchKeywordParameters';
select sitesearch_keyword_parameters from piwik_site;
```

You could change the value back directly afterwards again to make sure it works again.

**Comment by futureweb** [comment]
Using latest Version, it's configured as Global Setting - never touched since initial Install - which is ago some years.
Wasn't able to reproduce it now - maybe the trim() on save was already introduced in a Version after I configured this Setting - or as you say - maybe there was a Bug in angular?!

Output for booth Queries: query,searchquery (without Space - even if Space is shown in Output of Configuration Page)

**Comment by tsteur** [comment]
Perfect, there was probably a bug before we converted it to angular. 

Cheers
