### ISSUE TITLE
Overlay doesn't work when tracking script is ""js/index.php"

### ISSUE THREAD

**Issue by bastibeckr** [piwik/piwik#7684]
It seems that Overlay does only work when tracking-script is ``/js/piwik.js``. 

After clicking the overlay button, ``client.js`` can not be served (404-error). 

After reading ``/js/README`` I decided to embed the tracking script via ``/js/index.php`` for some reason. 
Overlay isn't a feature I use very frequently - it seemed broken, I blamed Apache/nginx-rewriting for this and planned to investigate deeper as soon as i got some spare time.
When the error also appeared on a second installation with completely different environment, i finally wanted to fix the problem.

The first request to overlay mode seems to load a blank page with just minimized Javascript:
``/index.php?module=Overlay&action=notifyParentIframe``

This script seems to build the framed page and tries to load ``client.js``:

**Broken** (tracking via ``/js/index.php``): ``/js/index.phpplugins/Overlay/client/client.js?v=1``
**Works** (tracking via ``js/piwik.js``): ``/plugins/Overlay/client/client.js?v=1``

Hope this save someone else's time - i got mad debugging nginx-redirects in order to find a missing trailing slash or something like that : )

**Comment by mattab** [comment]
Thanks for the report @bastibeckr - I tried to reproduce but couldn't, it works for me even when tracking via `/js/index.php`, as can be seen in screenshot: 
![works](https://cloud.githubusercontent.com/assets/466765/8678263/df1061ae-2a53-11e5-8343-39d16487f030.png)

(the index.php request is `/js/index.php`)

Works on both firefox and chrome

can you still reproduce this bug with Piwik 2.14.0?

**Comment by mattab** [comment]
If you can reproduce this problem in 2.14.0 @bastibeckr please re-open the issue.
