### ISSUE TITLE
403 error on tracker status

### ISSUE THREAD

**Issue by jgdjunaedy** [piwik/piwik#7685]
After installation, I got 403 error message saying that: GET request to piwik.php failed. Try whitelisting this URL from HTTP Authentication and disable mod_security (you may have to ask your webhost). 

Is this really necessary to fix since it is optional? If yes, what is the best way to solve this problem. Thanks

James

**Comment by mattab** [comment]
Hi James, yes it's needed that you whitelist piwik.php otherwise likely you will not get data logged in your Piwik
