### ISSUE TITLE
How to push the missing orders to piwik.

### ISSUE THREAD

**Issue by gangasiddhi** [piwik/piwik#7690]
How to push the missing orders to piwik explicitly.

Please help me, its urgency.

Thanks in advance.

**Comment by sgiehl** [comment]
What exactly do you mean with pushing the missing orders to piwik?

**Comment by sgiehl** [comment]
No answer within 3 weeks.... I'm closing that ticket for now. If you still have any problems feel free to reopen or ask your question on the forum.
