### ISSUE TITLE
Website selector: searching for special strings will show html code

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7692]
Reproduce:
 * in a website selector, with 10 websites or so,
 * enter in the search field `an` (or any substring of `...<span class="autocompleteMatched">....</span>....
 * notice that the autocompleter will highlight in purple some text but it actually displays html code of the element, as can be seen in this screenshot:

![highlighter](https://cloud.githubusercontent.com/assets/466765/7194906/40a50278-e50b-11e4-92d3-58c2969ab26a.png)

Expected behavior would be that the html code is not displayed (and that the highlighter / search does not match on the html text but only on the text without markup)

**Comment by mnapoli** [comment]
Ah I reported that here: https://github.com/piwik/piwik/pull/7552#issuecomment-86812956 but apparently I forgot to fix it ;)

What do you say I just remove the color highlighting? I remember looking into it and it was a mess because of escaping issues.

**Comment by mattab** [comment]
color highlighting is actually useful: it shows user why the website name matches the search (which sometimes is not obvious when website names are long or when search string is short).
