### ISSUE TITLE
Marketplace Plugin blocks are too big in some cases

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7695]
Here is an example of a Marketplace page rendered:

![marketplace looks wrong](https://cloud.githubusercontent.com/assets/466765/7196075/cbba01ac-e51e-11e4-8c32-4faa18e021d9.png)

Because of the PerformanceInfo plugin that has 2 yellow boxes and has a tall box, all other plugin boxes are tall as well

We expect to see instead the plugin blocks less high such as in this example:

![normal](https://cloud.githubusercontent.com/assets/466765/7196103/44add0de-e51f-11e4-80fd-8de8c87b1030.png)

**Comment by mnapoli** [comment]
In the "before" screenshot, here is what the `PerformanceInfo` plugin looked like:

![image](https://cloud.githubusercontent.com/assets/720328/7196388/dd3a4af8-e524-11e4-9968-f4e2de5e6b61.png)

Do we want to restore the old buggy display? Or what else should we do instead?

**Comment by diosmosis** [comment]
> In the "before" screenshot, here is what the PerformanceInfo plugin looked like:

Was this change merged? The admin page still looks like this for me.

**Comment by mnapoli** [comment]
For me it looks good right now on master:

![capture d ecran 2015-04-19 a 22 51 23](https://cloud.githubusercontent.com/assets/720328/7219151/a3d1c412-e6e6-11e4-853c-c0471882455d.png)

**Comment by diosmosis** [comment]
This is what I see on Firefox:

![marketplace_bug](https://cloud.githubusercontent.com/assets/125140/7219267/7f5a1af2-e64c-11e4-8699-6cf024be8d23.png)

It looks ok on chrome.

**Comment by mnapoli** [comment]
ah yeah I can reproduce in smaller screens (on Firefox at least), I'll fix it!

**Comment by mnapoli** [comment]
It should now display correctly.

**Comment by mattab** [comment]
To make the box less high we would need to remove the yellow notifications from the plugin box. I'm closing this issue as "wontfix" for now and let's think about it during Marketplace redesign in https://github.com/piwik/piwik/issues/7586#issuecomment-94326908
