### ISSUE TITLE
Website Manager small UX and design tweaks

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7696]
the website manager UI now scales thanks to both paging and search. :+1: 

This issue is a follow up to suggest a few small improvements:

* when click next/previous, `Loading data...` is displayed above the buttons causing the buttons+table to jump down one line while loading. Would be great to display the `Loading data...` inline eg. on the right of `Next` button, so the UI does not jump
* maybe the Search input field could be slightly less wider
* the Search button should be vertically aligned with Previous/Next button, in screenshot we can see small difference:

![not enough space below input field and search button](https://cloud.githubusercontent.com/assets/466765/7196597/29d8e500-e529-11e4-92e6-f14d51192718.png)

**Comment by tsteur** [comment]
> when click next/previous, Loading data... is displayed above the buttons causing the buttons+table to jump down one line while loading. Would be great to display the Loading data... inline eg. on the right of Next button, so the UI does not jump

This was not the case in my original PR, it must have been broken by another PR. Also the buttons used to be aligned. I will have a look
