### ISSUE TITLE
Improve logging for "unexpected website"

### ISSUE THREAD

**Issue by larsen0815** [piwik/piwik#7698]
I´ve found this in my php.log:

> Error in Piwik (tracker): An unexpected website was found, check idSite in the request.

Please add the value of idSite to the log entry. How else could I find out which idSite is causing this?

**Comment by mattab** [comment]
Hi @larsen0815 
what version of Piwik are you using and do you have the URL used to reproduce the issue?

**Comment by larsen0815** [comment]
Hi @mattab 
version is 2.8.3. URL is unknown as I don´t have the id in the log.

**Comment by mattab** [comment]
@larsen0815 please upgrade to Piwik 2.12.1 I think this bug was fixed. if you still have the problem with 2.12.1 leave a comment

**Comment by larsen0815** [comment]
Upgraded to 2.13.0 yesterday. Today I still have the same errors in my log.

**Comment by larsen0815** [comment]
Thx, I was able to find out the website now. Though, I was lucky to have an old instance of the database where the site was still in. It would be good when sites that get deleted are either only flagged as deleted (without actually deleting the record) or moved into another table like "site_deleted".

@mattab: May I open a new issue for that?

**Comment by larsen0815** [comment]
Would it be possible to log the referrer so you can see which domain is responsible for the log entries?

**Comment by mattab** [comment]
@larsen0815 can you please create a new issue for this request (this issue is closed)?
