### ISSUE TITLE
filter_pattern & filter_column on SitesManager.getAllSites fails

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#7699]
I noticed a problem with the returned data: 
module=API&method=SitesManager.getAllSites&format=xml&token_auth=mytokenauth&filter_pattern=TextToSearchFor&filter_column=name

The data returned contains all Sites, I expected to get only data returned containing "TextToSearchFor" in the name Column.

**Comment by tsteur** [comment]
I fixed this in #7634 and it should work with Piwik 2.13. Feel free to reopen in case it does not.
