### ISSUE TITLE
SitesManager.getPatternMatchSites returns limited set of sites

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#7700]
The API call SitesManager.getPatternMatchSites returns a max of 15 results.
I expected to get all sites matching the pattern

**Comment by tsteur** [comment]
:+1: Currently it uses the max value of the config setting `site_selector_max_sites` and `autocomplete_min_sites` but it should just return all by default. Note when removing the hard coded limit in that API we need to adjust the websites selector and send a `filter_limit` with every request.

**Comment by mattab** [comment]
Thanks for the report @RMastop
