### ISSUE TITLE
No general image statistics

### ISSUE THREAD

**Issue by approached** [piwik/piwik#7701]
Hi@all,

Has anybody a idea why can not see the general image statistics? Look it in screenshot. I use as a webserver nginx.

![stats-img](https://cloud.githubusercontent.com/assets/3439330/7215178/0e4abe4c-e5cb-11e4-993b-1f6206063c10.png)

**Comment by sgiehl** [comment]
Are those small sparklines working anywhere else in your piwik?
Does the system check of Piwik show any warnings?

**Comment by approached** [comment]
System check is successful.
Only on this place i can not see the sparkline. Other charts works well.

**Comment by mnapoli** [comment]
If you "open the image in a new tab", do you see an error page?

**Comment by approached** [comment]
On open the image it comes a redirect to Dashboard. The nginx error log said nothing.

**Comment by approached** [comment]
On the place Location / Continent it work on my site!

Demo:
https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=UserCountry&action=index&idSite=7&period=day&date=yesterday

**Comment by approached** [comment]
It was a wrong nginx config:
```
 59         location / {
 60                  try_files $uri /index.php;
 61         }
```
