### ISSUE TITLE
Wrong IP address in the Visitor Log

### ISSUE THREAD

**Issue by cuhkrain** [piwik/piwik#7709]
Dear All, 

I find the ip address in the Visitor log is quite strange for our users(the system is for internal use). 

When i run the sql-SELECT inet_ntoa(conv(hex(location_ip), 16, 10)) as ip, conv(hex(idvisitor), 16, 10) as visitorId FROM piwik_log_visit; 

The correct IP address shown in DB, e.g. 202.45.47.90, 202.45.47.29, 202.45.47.44...(as the below screenshot shown) 
![piwik db](https://cloud.githubusercontent.com/assets/716538/7223000/87fa8f92-e74c-11e4-8d7d-defb327864d2.png)

However, the ip address in attached Visitor Log is shown as -'175.159.128.71' and '175.159.128.101'(as the below screenshot  shown). We cannot use them at all. 
![piwik ip](https://cloud.githubusercontent.com/assets/716538/7223011/a406e23a-e74c-11e4-8f62-2d4bf3a59c8c.png)

Please advise if this is setting issue or bug? 

Thanks and regards, 
Rain

**Comment by mattab** [comment]
Hi @cuhkrain 

Maybe you are looking at different visitors and the IP address is actually correct in the Visitor log? can you show more of your DB columns so we can be sure you are showing the same visitors?
