### ISSUE TITLE
search keyword broken for Korean

### ISSUE THREAD

**Issue by mybluepig** [piwik/piwik#7712]
Hi
I am suffering search keyword not displaying correctly.
I didn't edit any of configuration related search.
DB supposed to be utf8
![screenshot-ww2 hc-cc co kr 2015-04-20 16-16-54](https://cloud.githubusercontent.com/assets/6930901/7225423/2fc318a8-e779-11e4-99db-9c57c0259ed5.png)

**Comment by sgiehl** [comment]
Are they all coming from the same search engine?

**Comment by mattab** [comment]
Hi @mybluepig do you still experience this bug in Piwik 2.14.0? we made several fixes recently so maybe this could be fixed. if it is not fixed, can you send us your website URL for Site Search where we can reproduce this issue?

**Comment by mattab** [comment]
Waiting for more information @mybluepig - please let us know and re-open issue if you still have issue with 2.14.0
