### ISSUE TITLE
Data loss because an upgrade was necessary

### ISSUE THREAD

**Issue by Amodio** [piwik/piwik#7715]
Hello,

I am searching for the PiwikLogs during the time I had to upgrade (the database too) and when I actually hit the upgrade button, any idea please?

Thank you.

**Comment by mattab** [comment]
Hi @Amodio would you mind ask in the forums for this question? http://forum.piwik.org/ here is our bug tracker where we discuss bugs and new features.

for your logs you can find them either in your server access logs (and replay them into Piwik: http://piwik.org/docs/log-analytics-tool-how-to/ with `--replay-tracking`) 

Cheers
