### ISSUE TITLE
Creating and mapping custom variables in the segment area

### ISSUE THREAD

**Issue by myluis** [piwik/piwik#7717]
Hi Folks,

Is it possible to create and map custom variables with the variable in the dash board area? I have created a custom variable called 'buyers' which I would like to use in replacing the 'Custom variable name 1 (scope visit)' in the dash board area. It just says, Custom Variable name 1 (Scope visit), etc.

Can someone advise me on how to map and replace this with my custom variable please? I would want the name like Custom variable name 1 (scope visit) to be buyers.

Any advice will be greatly appreciated please.

**Comment by mattab** [comment]
Hi @myluis 
The only way to do this currently is to create a custom plugin, and have your plugin define a custom segment that will be the Custom variable segment you are interested in. If you're a developer, maybe you will be able to do this with our Developer guides: http://developer.piwik.org/develop
