### ISSUE TITLE
Tracker performance regressed

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7718]
This was especially noticed in combination with QueuedTracking where the response time of one tracker request used to be about 4ms. It is now about 20-40ms depending on the server etc. Most of the time is spent in reading the ini config and static container / dependency injection.

I reckon the normal tracker mode got a bit slower as well but as a normal request takes maybe 50-200ms anyway the regression is probably not that much of a problem.

I uploaded a profile here: https://blackfire.io/profiles/983424c0-aa7e-446c-823b-59955f48212f/graph

In this case a client decided to use the QueuedTracking as it was very important to have a very fast tracker response time but the performance regressed.

**Comment by diosmosis** [comment]
Is this related: https://github.com/piwik/piwik/pull/7711 ?

**Comment by tsteur** [comment]
Maybe, we'd need to profile again after #7711 is merged to see how it performs and whether still something makes it "slower".

**Comment by mnapoli** [comment]
In the profiling you linked to [63% of the time is spent in `Profiler::setProfilingRunIds()`](https://blackfire.io/profiles/983424c0-aa7e-446c-823b-59955f48212f/graph?callname=Piwik%5CProfiler%3A%3AsetProfilingRunIds&selected=Piwik%5CProfiler%3A%3AsetProfilingRunIds&settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=focused), it would indeed be great to profile without any different code being executed in Piwik.

**Comment by diosmosis** [comment]
FYI I made some changes in profiler setup in #7711 so that wouldn't happen, you can look through the branch.

**Comment by mnapoli** [comment]
By the way did you profile with `composer dump-autoload -o`? It seems Composer is doing some file_exists where it shouldn't when using the classmap (though I'm not 100% certain)

**Comment by tsteur** [comment]
The profile is not really relevant in this case. The profile shows it took 50ms or more but the 20-40ms I mentioned is with no profiling enabled etc. This used to be 4ms.

**Comment by diosmosis** [comment]
Right, but w/o an accurate profile, how will we diagnose + test the issue? Can you tell us what Piwik version was used when the tracker was fast?

**Comment by tsteur** [comment]
I'm just saying there seems to be a regression that's all. One can at least see where some time is spent and everything else has to be looked into when actually working on this issue anyway.

I reckon this was around December 2014 when the QueuedTracking plugin was built so probably 2.9.0 or 2.10.0.

**Comment by mattab** [comment]
Let's take a look at Tracker API performance and profile it for 2.15.0. it shouldn't take long (ie. couple hours?) to figure out if something is slow or not, and if we really regressed performance, it would be high value to make tracker faster again.

**Comment by tsteur** [comment]
I uploaded an xhprof profile for a single pageview here: https://blackfire.io/profiles/4396e3dd-d9cf-4c48-a337-b5e4737057af/graph It looks good and seems like nothing regressed extremely.

Here is a profile taken with xhprof of a bulk request (with 133 requests): https://blackfire.io/profiles/1849a1c0-6483-4b4c-84eb-9f2d3896951c/graph. I can't tell if anything regressed but didn't find anything that worried me. A lot of time was spend in `$visit->isExcluded()` (27.5%) but we can probably not do much here

**Comment by mnapoli** [comment]
Time spent in Composer and loading files seems very high in your first profile, I already asked this but did you optimize the autoloader? And did you remove dev dependencies (as they can overload the classmap and make a difference in short lived processes)? Also I don't know if you still use PHP 5.4 but did you use an opcache?

Anyway good to know there is no regression.

**Comment by tsteur** [comment]
yes autoloader optimized, I didn't remove dev dependencies but that's not really important in this case. It's PHP 5.5 with opcache and warmed up of course
