### ISSUE TITLE
API returned an error: SQLSTATE[42000]  The SELECT would examine more than MAX_JOIN_SIZE rows

### ISSUE THREAD

**Issue by GeoffAU** [piwik/piwik#7729]
Version 2.13.0-b2 and 2.13.0-b3

API returned an error: SQLSTATE[42000]: Syntax error or access violation: 1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay at Pdo.php:234

**Comment by mattab** [comment]
@GeoffAU can you try again in 2.14.1-b2 (our latest beta) where this bug may be fixed? if it's not fixed, please let us know which URL returns this error.

**Comment by mattab** [comment]
We need more information, hopefully @GeoffAU you can send us bit more info here :+1:
