### ISSUE TITLE
Widgets containing sparklines should list the sparklines one per line

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7738]
after including the bootstrap grid, the UI tests showed that the "Frequency overview" widget regressed and now displays sparklines in two columns instead of below one another.

Got:
![frequency overview](https://cloud.githubusercontent.com/assets/466765/7266879/7419e6fc-e905-11e4-8546-c36275d647f7.png)

Expected:

![34f79e80-a6c3-11e4-99a2-829300ada44e](https://cloud.githubusercontent.com/assets/466765/7266882/7b11c650-e905-11e4-8102-f4353e4616e0.jpg)

**Comment by mnapoli** [comment]
PR: #7740

**Comment by mattab** [comment]
Reopening as there are some more widgets with the issue:

### Goals overview

![widget bis](https://cloud.githubusercontent.com/assets/466765/7287235/c4310a34-e9a6-11e4-8c39-5fa1df197a21.png)


### Visits overview

![widget3](https://cloud.githubusercontent.com/assets/466765/7287230/bd1c1f0e-e9a6-11e4-9011-89b2ec7cc1ea.png)

### Visits overview (with graph)

![widget two columns](https://cloud.githubusercontent.com/assets/466765/7287228/b88eaf10-e9a6-11e4-9774-1f77769754df.png)


 * let's make those also one sparkline per line
