### ISSUE TITLE
Bug in login_cookie_expire setting

### ISSUE THREAD

**Issue by steffenHD** [piwik/piwik#7743]
i use Piwik 2.9.0 and setting login_cookie_expire in the piwik configuration to a low value like 30 seconds doesn't seem to change anything.
To verify that i am changing the correct file and that my changegs take affect i also changed the setting login_cookie_name from piwik_auth to piwik_auth_test which works.

However Browser says that the piwik_auth_test cookie ist still valid until session end (until the browser is closed) and on server side there also doesn't seem to happen anything. The user ist never logged out even though he did not click on "remember me". 

[piwik_session](https://cloud.githubusercontent.com/assets/3170147/7269763/ed70c036-e8d6-11e4-8677-1868b981fa9d.GIF)

**Comment by ThaDafinser** [comment]
It has not changed since 2.9.0 so this bug may still be valid.

https://github.com/piwik/piwik/blob/master/plugins/Login/SessionInitializer.php#L175
https://github.com/piwik/piwik/blob/2.9.0/plugins/Login/SessionInitializer.php#L175

**Comment by mattab** [comment]
Hi @steffenHD 

It works for me. Note that this setting is only used when "Remember me" is checked. I've updated comment to clarify this: https://github.com/piwik/piwik/commit/dca6858ffc6023b1fa046b02f77f05d79345050a
