### ISSUE TITLE
Access management for multiple websites per user

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [piwik/piwik#7745]
Currently, one has to select a website to be able to grant access to a user. This means that, for a new user, except when granting access to all sites, the admin has to select sites one by one to either grant access or verify the accesses that have been granted in the past.

While condensing the three states (No access, View, Admin) into one cell, have a two dimensional grid which displays: users and websites with the crossing displaying the granted access.

![capture](https://cloud.githubusercontent.com/assets/5151122/7275128/4d7372c8-e902-11e4-8c1d-450fcc730085.PNG)
It could also be some kind of clickable bullet to change value of the grant.

**Comment by mattab** [comment]
Hi @patriiiiiiiiiick - thanks for suggestion. 
Making it easier to assign permissions is also discussed in #6187

**Comment by mattab** [comment]
see  #6187
