### ISSUE TITLE
Incorrect figure for Custom Variables

### ISSUE THREAD

**Issue by cuhkrain** [piwik/piwik#7750]
I find the figure of Custom Variables is not correct in following scenario.

1. following figure shows the Custom Variables in the current system.
![piwik custom variables](https://cloud.githubusercontent.com/assets/716538/7289223/803695a8-e99f-11e4-8624-3b4a89fd6afa.png)

2. When i click the Pie chart in the figure above, the result only contains the Custom Variables, but not the detail information. as shown below. This is meaningless.....
![piwik custom variables2](https://cloud.githubusercontent.com/assets/716538/7289311/daf81470-e9a0-11e4-9033-54dd3ba49f2c.png)

Any ideas to change the figure to show the detail information of Custom Variables?

Thanks and regards,
Cuhkrain

**Comment by mattab** [comment]
Hi there, thanks for the report, it would be indeed useful to fix the graphs. See this feature request: #2786 - maybe you wouldnt mind posting your screenshots in that other issue?

The good news is: there is an easy workaround: first "flatten" the report and then click on the graph icon. It will show you the graph with the top custom var values and group rest in "Others"
