### ISSUE TITLE
[2.13.0-rc1] every click a new visit?

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7752]
Some users generate now on every click a new visit, but not all.

Intranet settings
```
[Tracker]
trust_visitors_cookies = 1
visit_standard_length = 7200
window_look_back_for_visitor = 259200
enable_language_to_country_guess = 0
new_visit_api_requires_admin = 0
```

**Comment by ThaDafinser** [comment]
New working settings
```
[Tracker]
visit_standard_length = 7200
enable_language_to_country_guess = 0
```

But i wonder what has changed since 1.12? I didnt found something in changelog.

**Comment by ThaDafinser** [comment]
The problem comes from  `window_look_back_for_visitor = 259200`

Note: i also use the `userId` feature (if that helps)

**Comment by tsteur** [comment]
Hi @ThaDafinser . Do you track via piwik.js?

**Comment by ThaDafinser** [comment]
@tsteur yes. But i couldnt find out, why it happens to some users and some not.

Without using `window_look_back_for_visitor` it seems to be "stable" again

See the crazy action on the screenshots. even 6s after the last click a visitor gets counted as a new one

![visitor_action_log](https://cloud.githubusercontent.com/assets/533017/7313451/af524610-ea59-11e4-8fb9-b6ff172bb21c.jpg)
![visitor_log](https://cloud.githubusercontent.com/assets/533017/7313452/af52abdc-ea59-11e4-9a5c-8cef9f382e01.jpg)

**Comment by tsteur** [comment]
You meant you upgraded from 2.12, not 1.12 right?

**Comment by tsteur** [comment]
I can reproduce it!

**Comment by tsteur** [comment]
In my case the problem was related to `setCookieDomain`.

Eg I used on my local dev `_paq.push(['setCookieDomain', '*.piwik']);` which didn't work as it couldn't set a cookie for `*.piwik`. After changing it to `_paq.push(['setCookieDomain', '*.apache.piwik']);` it worked. Do you maybe use something similar?

**Comment by ThaDafinser** [comment]
@tsteur yes i upgraded from 2.12.

Since i only change the setting `window_look_back_for_visitor` ...i will check if that helps in my case too.

**Comment by mattab** [comment]
Hi @ThaDafinser

can you please try with RC3 and if you still see the error, re-open this issue?

**Comment by tsteur** [comment]
I cannot really see how it can be caused by `1800`

**Comment by tsteur** [comment]
I cannot really see how `window_look_back_for_visitor` could cause this issue. By default a value of `1800` (`visit_standard_length` config setting) is used for this. Setting a higher value for this should not cause more visits. Clearly there are too many visits created here. As a userId is set, the cookie stuff that I mentioned cannot really cause this I think. Can you confirm removing this setting does not cause too many visits?

**Comment by ThaDafinser** [comment]
I trynow 2.13. But i removed the setting already and now i just have a slightly higher visitor count (since the look_back is lower of course)

**Comment by tsteur** [comment]
OK. If you can reproduce again please reopen this issue. Cheers
