### ISSUE TITLE
How can I disable to the video widget

### ISSUE THREAD

**Issue by Goddard** [piwik/piwik#7755]
How can I disable the video widget?

Disabling the example widgets doesn't work.

**Comment by tsteur** [comment]
Can you explain it? Do you want to remove it from the dashboard? Do you want to disable it in a custom plugin?

**Comment by Goddard** [comment]
I disabled it in my dashboard and set the access token for the website but for some reason when people visit it for the first time the video box always is displayed.  I just want to disable it as it doesn't make sense as I have edited the iframe style dashboard.

**Comment by tsteur** [comment]
Is it publicly visible? If so, do you have a link? When you "disabled/removed" the video widget from the dashboard, are you logged in as the user that you have given access to that website? 

> and set the access token for the website 

Just to be sure did you set the access token in the exported dashboard url like `&token_auth=XXX`?

**Comment by Goddard** [comment]
It is not publicly visible.  

But I am using the latest version.  When I login it displays the correct dashboard.  When I am not logged in it displays the same dashboard, but it the layout is different and it also displays the video.  

It doesn't display the video any more if I click the X and close it.

I did use the dashboard token as well.

**Comment by tsteur** [comment]
I tried to reproduce but it just works fine for me. Sorry for so many questions...

Have you enabled the anonymous user? Does this user has access to that website?

Can you maybe post the URL that you use here? Feel free to replace the domain and make sure to replace the `token_auth` with `XYZ` or so.

Can you maybe also try to open that URL in a browser in incognito mode to check how it looks when someone else views it?

**Comment by mattab** [comment]
Hi @Goddard 

It works for us. Steps:
 * As super user, remove the "Support piwik" widget
 * Click Dashboard -> Set as default dashboard layout
 * Log out or open piwik with incognito -> the anonynmous user will not see the Piwik video widget
