### ISSUE TITLE
"Git Fetch/Pull" command in (master) branch often results in  Codebase-Database version or other strange errors

### ISSUE THREAD

**Issue by saleemkce** [piwik/piwik#7765]
Hi everybody,

I often find it strange to encounter this error over and over again. Yesterday, I made a fresh git clone from Piwik Repo. Then created a branch to fix a css issue.https://github.com/piwik/piwik/pull/7764  After that, I wanted to make sure to get updates from master (After switching to master branch) if any. So I ran,

**"git fetch"**  followed by 
**"git pull upstream master"**

Immediately, I find myself locked out of application. I got this error (as screenshot),

![git_pull_error_occured](https://cloud.githubusercontent.com/assets/6330544/7333147/a018a23e-eb80-11e4-9c70-d6dce0b85d31.png)

Sometimes, I am even getting this too,

![piwik_pull_error](https://cloud.githubusercontent.com/assets/6330544/7333148/b17f41c2-eb80-11e4-876c-c72b3b6df722.png)

Now, what is the problem here and how to manage **"git pull"** and get updates properly without getting locked by new updates (I mean git pull / fetch commands)? I just only followed the developer documentation and this occurs often. Help needed sooner.

**Comment by mattab** [comment]
Hi there, See FAQ how to use piwik from git: http://piwik.org/faq/how-to-install/faq_18271/

**Comment by saleemkce** [comment]
Hmm great. Then, how different are the instructions given in this page http://developer.piwik.org/guides/contributing-to-piwik-core? (I have been following this link since the beginning) Is it the right page to follow than the one you just provided?

Thanks.
