### ISSUE TITLE
Browser info tooltip doesnt hide

### ISSUE THREAD

**Issue by sridharrajs** [piwik/piwik#7768]
Hover over the browser icon on the visitor profile. In my case it shows "chrome 44 with plugin installed".

![screenshot from 2015-04-26 19 07 00](https://cloud.githubusercontent.com/assets/1156953/7337489/3a8c72b4-ec49-11e4-8582-4debcdc8b818.png)

Now close the modal by pressing <kbd>ESC</kbd>. You can see that the tool tip shown in the visitor profile modal, tags along with the mouse pointer.

![screenshot from 2015-04-26 19 10 51](https://cloud.githubusercontent.com/assets/1156953/7337491/490cda68-ec49-11e4-9d60-afdf02c082d1.png)

Piwik <code>2.12.1</code>
Browser : <code> Firefox 35.0</code>
AdBlocker plus addon - <code> disabled</code>
PHP version <code> 5.4.32 </code>

**Comment by mattab** [comment]
Thanks for the report @sridharrajs
