### ISSUE TITLE
Allow using first-party cookies in opt-out form by adding form functionality to JS tracker

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#7769]
Refs #3135, #7754 

Currently the opt-out form uses third party cookies, so if a user opts out in one site, he opts out in every site tracked by a Piwik instance. This does not seem like it would always be desired.

Choosing to use first-party cookies also means users will have a better UX when using Safari on Mac or iPhone, as new windows won't have to be created.

**Comment by mattab** [comment]
Hi @diosmosis, it duplicates #6505
