### ISSUE TITLE
Tracker: Faster visitor recognition

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7779]
As discussed with @quba I think the union here is not needed: https://github.com/piwik/piwik/blob/2.13.0-rc2/core/Tracker/Model.php#L382-L386

Instead we could perform one query first to check if there is a `idvisitor = ?` and if not execute a second query with `config_id = ? AND user_id IS NULL`

We noticed on a DB with many log entries that this visitor recognition query is rather slow and this should improve it as in most cases a visitor based on `idvisitor` should be found. Even if not, it should not be slower that way.

**Comment by mattab** [comment]
+1 changing this would definitely help.

This was also reported in  #7454  UNION query in findVisitor() is regularly 100ms+, involves temporary tables and scans
