### ISSUE TITLE
piwik.js: If cookies are disabled, no visitorId should be created / set

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7780]
This means it will fallback to use `configId`. Otherwise we create a new visit on each tracker request (even when calling tracker methods multiple times within one pageview). 

Background: If a `idvisitor` is given, we will always look for `idvisitor` but not for `config_id` eg https://github.com/piwik/piwik/blob/2.13.0-rc2/core/Tracker/Model.php#L337-L339 . 

It goes into this code block for example if `trust_visitors_cookies` is enabled see https://github.com/piwik/piwik/blob/2.13.0-rc2/core/Tracker/Visitor.php#L141-L169 . 

By not setting a `idVisitor` if cookies are disabled, it would actually look for the `configId` and not generate many visits

refs #7752

**Comment by mattab** [comment]
Marking as fixed since #7783 was merged - please re-open @tsteur if there is more work to do
