### ISSUE TITLE
Incorrect browser logged when user switches browsers when using userId

### ISSUE THREAD

**Issue by petergillardmoss** [piwik/piwik#7785]
Hello,

When a user (with a userid) switches browsers/device Piwik continues to log views under the original browser/device.

How to reproduce:

Given a user with a user id:
* Open browser A (e.g. Firefox)
* Piwik Devices shows a single visit from a Firefox browser
* Piwik starts a visit with:
  * browser set to Firefox
  * 1 visited page

Then:
* Open browser B (e.g. Chrome)
* Piwik Devices shows a single visit from a Firefox browser
  * No Chrome browser is acknowledged
* Piwik continues visit with:
  * browser set to Firefox
  * 2 vistited pages

This seems to be true for other metadata (such as device, resolution, plugins, location etc.)

Peter

**Comment by mattab** [comment]
Hi Peter, thanks for suggestion. We would like to change it to what you sugggest in the future.

**Comment by petergillardmoss** [comment]
Brilliant.  I'll watch this space.

I'm sure you know this already, but I looked at the data schema and visits are tight bound to all that info.  I wondered if that info better belonged in log_link_visit_action.  Of course I image this has repercussions elsewhere.

**Comment by mattab** [comment]
This would be fixed in #7691 so marking as duplicate.

**Comment by tmuic** [comment]
Is there any update on this in duplicated task?

For my use case it is pretty important to be able to distinguish flows when user navigates the page from multiple browsers and devices.

**Comment by mattab** [comment]
@tmuic see: https://github.com/piwik/piwik/issues/7691 - it is not scheduled yet and won't be for a while (we have no resources at this time).

**Comment by tmuic** [comment]
ok,
will have to stick to workarounds.
I looked at several tutorials but didn't find anything on how to reuse/extend existing reports.

In this case I'd like to extend Live report and include a few of mine custom dimensions. Is there an official way to do that?
