### ISSUE TITLE
When exporting the dashboard, the name of the dashboard is not correctly displayed 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7791]
See attachment.

The name of the dashboard(s), in this case "Dashboard of root", has a red font color and there's a misplaced red dot etc.

![dashboard_name_exported](https://cloud.githubusercontent.com/assets/273120/7401703/4d2315bc-ef1a-11e4-8220-5f114ff4b71d.png)

**Comment by mattab** [comment]
This can be still be reproduced in Chromium (but it displays correctly on Firefox)

**Comment by tsteur** [comment]
This looks fixed, I can no longer reproduce it in latest Chrome. 

Also if there's only one dashboard the menu is now hidden (which is good) see eg http://demo.piwik.org/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=1&period=week&date=yesterday

Works also correctly with many dashboards. Either we fixed it or Chrome fixed something. Can anyone confirm?

**Comment by tsteur** [comment]
@mattab you mentioned Chromium maybe you can have a look as well?

**Comment by tsteur** [comment]
I can also not reproduce it with latest chromium version (46). Maybe it depends on screen size etc? I can kinda reproduce it if I zoom out 3 times and then zoom in 2 times but don't think that would be worth a fix

**Comment by mnapoli** [comment]
> I can kinda reproduce it if I zoom out 3 times and then zoom in 2 times but don't think that would be worth a fix

Same here (happens only when playing with the zoom), but I don't think it's worth a fix either since displays correctly when the page is loaded/refreshed (even with a custom zoom).

**Comment by sgiehl** [comment]
Checked that again in Chrome, Firefox and IE. Seems to work everywhere.
