### ISSUE TITLE
UI test for Rows count picker

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7794]
We got a regression and noticed last minute in rc3 as there was no UI test for the feature. Let's add a UI test for tihs particular "Rows count" dropdown in the footer.

**Comment by quba** [comment]
Should be also added in 2.13.1 (fix is already there).

**Comment by mattab** [comment]
fyi @quba we fixed this issue just before 2.13.0 so it's actually working in the release

**Comment by diosmosis** [comment]
If you mean the limit selector at the bottom of reports, there is a test here: https://github.com/piwik/piwik/blob/master/tests/UI/specs/ViewDataTable_spec.js#L81

**Comment by mattab** [comment]
Yes I mean this selector. I believe currently we don't take a screenshot but just click on it. The point is to take a screenshot of this selector so we don't regress the style like we almost did in 2.13.0.

**Comment by diosmosis** [comment]
I think that won't be possible. I vaguely remember not being able to capture a screenshot of an open select element.

**Comment by diosmosis** [comment]
Turns out it is possible.
