### ISSUE TITLE
Can't add new site after update to 2.13.0

### ISSUE THREAD

**Issue by justincdotme** [piwik/piwik#7802]
Clicking "+Add a new website" from the "All Websites Dashboard" does not allow me to add a new website. This started after upgrading to 2.13.0. 

The text inputs to add a new site briefly appear on the screen before disappearing. By briefly I mean less than 1 second. 

This happens on Chrome 42 and Firefox 37 on Ubuntu 14. This also happens on Chrome 42, Firefox 33 and IE9 on Windows 7
![piwik-add-site-bug](https://cloud.githubusercontent.com/assets/6857530/7425128/2e4090fc-ef60-11e4-9d96-ecc9160e85f9.jpg)
.

There are no console errors shown when this occurs.

**Comment by tsteur** [comment]
Can you maybe clear your browser cache and execute the command `./console cache:clear` on the server in the Piwik root directory?

**Comment by tsteur** [comment]
Actually, I can reproduce it. It is caused by the URL parameter `showaddsite=1`. It works when clicking on `Administration => Websites`

**Comment by justincdotme** [comment]
@tsteur Thank you, removing the showaddsite=1 param works for me.
