### ISSUE TITLE
Cannot add a new website

### ISSUE THREAD

**Issue by Silver0l** [piwik/piwik#7808]
Since I updated to 2.13.0, when I go on the Administration>Websites page, I cannot add a new website - there is just no button/link to do that.

This is very frustrating, as I can see a link to "Add a new website" appearing on my screen for a fraction of a second, and then it disappears, I have the tabular view of my web sites, but no way to add a new website.

![no-add-website](https://cloud.githubusercontent.com/assets/12196818/7428518/3af0aa34-eff2-11e4-9e1d-5d54f17ddf98.PNG)

Tried it with Firefox 37.0.2 and IE 11.0 - same result.

Also, I cannot edit the settings for any website. When I click to do that, I have an empty alert windows, and I just can close it without any action done.

![cannot-edit-website-settings](https://cloud.githubusercontent.com/assets/12196818/7428524/4515f8ac-eff2-11e4-86c1-b8df993aa56f.PNG)

**Comment by Silver0l** [comment]
Apparently, somebody could find some workaround, but that is still not working for me:
http://forum.piwik.org/read.php?2,126376

**Comment by justincdotme** [comment]
@Silver0l I had the same issue yesterday. A workaround is described here: https://github.com/piwik/piwik/issues/7802

**Comment by Silver0l** [comment]
Thanks! The workaround (removing the showaddsite=1 param) works for me, too.
