### ISSUE TITLE
Automated Installer?

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#781]
I don't know where to post my question so i do it here ;)

I currently develop a full integration of Piwik into TYPO3.

TYPO3 Supports table creation during installation. To use this feature, i need the table structere as create statement.

How does Piwik create them (they must be created during installation?!), perhaps you can point me to the correct lines of code ;), so that the plugin will work with the api.

Regards Kay

**Comment by mattab** [comment]
We have implemented this plugin for [Piwik PRO](http://piwik.pro), it is available as part of Piwik Enterprise, please [get in touch](http://piwik.pro/contact) if you are interested.

**Comment by mattab** [comment]
Please see and follow up in this duplicate feature request: https://github.com/piwik/piwik/issues/10257
