### ISSUE TITLE
Error: No data in this category. Try to "Include all population"

### ISSUE THREAD

**Issue by arunvishun** [piwik/piwik#7811]
Hi
I am getting this error - "No data in this category. Try to "Include all population". What I noticed is that this happens when ever I select a larger date range, and also when we try to open multiple subtables.
I use the latest piwik version - 2.12.1.

Attaching screenshot for the same. The same issue was reported by a few others as well - http://forum.piwik.org/read.php?2,84432,126064#msg-126064

![nodataerror](https://cloud.githubusercontent.com/assets/1584121/7432596/8913e29e-eff7-11e4-91a7-fc1888421b14.jpg)

Thanks
Arun

**Comment by tsteur** [comment]
Can you see any error in the server logs? Can you maybe update to the latest Piwik 2.13 where we made some performance and memory improvements?

Do you have browser archiving enabled? Does it also happen when you eg quickly open the tree? Meaning when you open the path to that page within a few seconds

**Comment by mattab** [comment]
Hi @arun

**Comment by mattab** [comment]
Hi @arunvishun 
Can you still reproduce issue in 2.14.0? or maybe on demo.piwik.org ?

it would be great to hear more info as we cannot reproduce at this stage. Thanks

**Comment by arunvishun** [comment]
Hi Matt,

I couldnt upgrade to latest version. Will test and re-open this in case i see the same issue after upgrade.

Thanks
Arun
