### ISSUE TITLE
Details cut-off on Visitor Log modal pop-up (screenshot included)

### ISSUE THREAD

**Issue by arrayown** [piwik/piwik#7812]
Hello great people of Piwik!

I would like to report a UI issue with Piwik when viewing Visitor Log inside modal pop-up. I am using Piwik 2.13.0.

When you hover over Device icon, the details pane are cut-off by the next table cell. See the screenshot for visual.

Hopefully this can get fixed soon since it makes it hard to find details about specific users.

Thanks and keep up the great work! I will donate again soon.

![piwik-bug-screenie](https://cloud.githubusercontent.com/assets/914322/7440185/d932a9ca-f071-11e4-8fa6-a1ff2de15d88.png)

**Comment by tsteur** [comment]
It would be nice to fix this short term but I presume it will end in rethinking the visitor log and how it is displayed today. The current version of Visitor Log doesn't work with many columns as can be seen here and we waste a lot of time as eg there's often a lot of space below the "Date" and "Visitors" column. Moving to Piwik 3.0.0 for now as it would be nice to have a better visitor log by then but we could also move to Mid term @mattab

**Comment by mattab** [comment]
My previous idea to fix this issue was to:  Make Popovers slightly wider #7517

**Comment by mattab** [comment]
I'm not sure it would fix this particular issue though, as on the screenshot I can see there is more space to the right yet it is not used. Maybe we could force the first column to have some min-width?

**Comment by arrayown** [comment]
I tried (and failed) to make the `.details` class show above all other elements with z-index, but that did not work. I guess there's something else in the CSS overriding it or it simply doesn't work in tables.

**Comment by tsteur** [comment]
#7517 to make the popover rather wider wouldn't solve this issue and would be rather a hack. And what would happens if someone has a small screen? We do have this problem even when it is not displayed in a popover (then 4 columns are used).

As said I think we just need to rethink how it is displayed. Eg we could always use only 2 columns with gives everything more space and we will maybe have less whitespace. There might be even better solutions.

**Comment by tsteur** [comment]
Even when having a screen with `1350px` width the date is not fully visible. I think this shows pretty clearly that this design needs to be revised.

![visitor_log_date](https://cloud.githubusercontent.com/assets/273120/7599467/6210d11c-f956-11e4-8db1-3806f7594aa7.png)

**Comment by mattab** [comment]
Sure the design is wrong. Maybe we can remove the Referrer column and display the info below the date/ip/provider lines (and above any custom variables 'visit' scope lines)

**Comment by starlingDesign** [comment]
The issue lies with the css rule;
````css
.dataTableVizVisitorLog table.dataTable .label {
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
````
If you remove `overflow: hidden` it will show, but gets ugly fast.

**Comment by mattab** [comment]
I've removed the "Referrer URL" column and referrer information is now displayed below any custom variable and/or the datetime+Ip. Saves a lot of space and makes UI better. 

it would be awesome to innovate and redesign our Visitor Log. There are some great tools for  User intelligence such as: http://intercom.io/

**Comment by tsteur** [comment]
In which issue will we handle the redesign of the visitor log? Shall we create a new one? The visitor log (and real time widget) are the most used features in Piwik. At least in Mobile app like 50% of the users only use this so it would be certainly worth investing some time to make it actually good, usable and pretty.

**Comment by mattab** [comment]
Yes let's create a new issue for the redesign and refresh of the feature of Real time visitor & usable User intelligence reports. There was also:  Better Real Time reporting in Piwik #2439
