### ISSUE TITLE
[client xxx.xx] sh: ps: not found, referer: http://www.yyyy.de

### ISSUE THREAD

**Issue by wklueter** [piwik/piwik#7815]
Dear ALL
I had automatically updated at new version 12.13.0 from version before.
Now i saw in privider-logfile a lot of errors like this: ( complete Log since update )

Error-Logs:

30.04.2015 21:09:04 neuemusikschule.de [client 91.6.120.0] whoami: cannot find name for user ID 845556, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
30.04.2015 21:09:04 neuemusikschule.de [client 91.6.120.0] sh: groups: not found, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
30.04.2015 21:10:34 neuemusikschule.de [client 91.6.120.0] Premature end of script headers: index.php, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreUpdater&action=newVersionAvailable
30.04.2015 21:11:24 neuemusikschule.de [client 91.6.120.0] whoami: cannot find name for user ID 845556, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
30.04.2015 21:11:24 neuemusikschule.de [client 91.6.120.0] sh: groups: not found, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
30.04.2015 21:13:23 neuemusikschule.de [client 91.6.120.0] Premature end of script headers: index.php, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreUpdater&action=newVersionAvailable
30.04.2015 21:15:32 neuemusikschule.de [client 91.6.120.0] sh: df: not found, referer: http://www.neuemusikschule.de/piwik/index.php?module=UserCountry&action=adminIndex&idSite=1&period=day&date=today
30.04.2015 21:15:32 neuemusikschule.de [client 91.6.120.0] sh: ps: not found, referer: http://www.neuemusikschule.de/piwik/index.php?module=UserCountry&action=adminIndex&idSite=1&period=day&date=today
30.04.2015 21:15:32 neuemusikschule.de [client 91.6.120.0] sh: ps: , referer: http://www.neuemusikschule.de/piwik/index.php?module=UserCountry&action=adminIndex&idSite=1&period=day&date=today
30.04.2015 21:15:32 neuemusikschule.de [client 91.6.120.0] not found, referer: http://www.neuemusikschule.de/piwik/index.php?module=UserCountry&action=adminIndex&idSite=1&period=day&date=today
30.04.2015 21:17:06 neuemusikschule.de [client 91.6.120.0] Error in Piwik: <!DOCTYPE html> <html> <head> \t<meta charset="utf-8"> \t<title>Piwik &rsaquo; Error</title> \t<link rel="shortcut icon" href="misc/user/favicon.png" /> \t<link rel="stylesheet" type="text/css" href="plugins/Morpheus/stylesheets/simple_structure.css" /> </head> <body id="simple">  <div class="logo"> \t<img title="Piwik" alt="Piwik" src="http://www.neuemusikschule.de/piwik/plugins/Morpheus/images/logo-header.png"/> \t<br/> \t<a href='http://piwik.org/'>free/libre analytics platform</a> </div>  <div class="box">  \t<div class="header"> \t\t<h1>An error occurred</h1> \t</div>  \t<div class="content"><h2>Could not verify the security token on this form.</h2>                     <p><a href="javascript:window.history.back();">Go Back</a> | <a href="index.php">Go to Piwik</a> |                        <a href="index.php?module=Login">Login</a></p>  <ul>                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org">Piwik.org homepage</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org/faq/">Piwik Frequently Asked Questions</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org/docs/">Piwik Documentation</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://forum.piwik.org/">Piwik Forums</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://demo.piwik.org">Piwik Online Demo</a></li>                             </ul>    </div>      <div class="footer">         <a href="index.php">&laquo; Back to Piwik</a>     </div>  </div> </body> </html>  , referer: http://www.neuemusikschule.de/piwik/index.php?module=CorePluginsAdmin&action=plugins&idSite=1&period=day&date=today&activated=
30.04.2015 21:17:06 neuemusikschule.de [client 91.6.120.0] Error in Piwik: <!DOCTYPE html> <html> <head> \t<meta charset="utf-8"> \t<title>Piwik &rsaquo; Error</title> \t<link rel="shortcut icon" href="misc/user/favicon.png" /> \t<link rel="stylesheet" type="text/css" href="plugins/Morpheus/stylesheets/simple_structure.css" /> </head> <body id="simple">  <div class="logo"> \t<img title="Piwik" alt="Piwik" src="http://www.neuemusikschule.de/piwik/plugins/Morpheus/images/logo-header.png"/> \t<br/> \t<a href='http://piwik.org/'>free/libre analytics platform</a> </div>  <div class="box">  \t<div class="header"> \t\t<h1>An error occurred</h1> \t</div>  \t<div class="content"><h2>Could not verify the security token on this form.</h2>                     <p><a href="javascript:window.history.back();">Go Back</a> | <a href="index.php">Go to Piwik</a> |                        <a href="index.php?module=Login">Login</a></p>  <ul>                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org">Piwik.org homepage</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org/faq/">Piwik Frequently Asked Questions</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://piwik.org/docs/">Piwik Documentation</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://forum.piwik.org/">Piwik Forums</a></li>                             <li><a rel="noreferrer" target="_blank" href="http://demo.piwik.org">Piwik Online Demo</a></li>                             </ul>    </div>      <div class="footer">         <a href="index.php">&laquo; Back to Piwik</a>     </div>  </div> </body> </html>  , referer: http://www.neuemusikschule.de/piwik/index.php?module=CorePluginsAdmin&action=plugins&idSite=1&period=day&date=today&activated=
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Warning:  unpack(): Type V: not enough input, need 4, have 0 in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/Lookup.php on line 378, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] 41 messages repeated, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Notice:  Trying to get property of non-object in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/API.php on line 38, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Notice:  Trying to get property of non-object in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/API.php on line 39, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Notice:  Trying to get property of non-object in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/API.php on line 40, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Notice:  Trying to get property of non-object in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/API.php on line 41, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Notice:  Trying to get property of non-object in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/API.php on line 42, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 21:36:09 neuemusikschule.de [client 37.24.23.0] PHP Notice:  Trying to get property of non-object in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/IP2Location/API.php on line 43, referer: http://www.neuemusikschule.de/content/musikkarussell.html
30.04.2015 22:18:17 neuemusikschule.de [client 91.36.26.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
01.05.2015 08:03:37 neuemusikschule.de [client 91.6.120.0] sh: ps: not found
01.05.2015 11:11:55 neuemusikschule.de [client 37.24.23.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/musikkarussell.html
01.05.2015 13:04:56 neuemusikschule.de [client 91.6.120.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/musikkarussell.html
01.05.2015 14:32:06 neuemusikschule.de [client 109.90.119.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
01.05.2015 15:52:07 neuemusikschule.de [client 199.30.25.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
01.05.2015 19:25:24 neuemusikschule.de [client 91.6.120.0] sh: ps: not found
01.05.2015 22:25:30 neuemusikschule.de [client 87.139.58.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
02.05.2015 01:59:14 neuemusikschule.de [client 187.44.17.0] sh: ps: not found, referer: http://neuemusikschule.de/content/inhalt.html
02.05.2015 07:33:11 neuemusikschule.de [client 93.195.108.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
02.05.2015 08:46:50 neuemusikschule.de [client 37.46.118.0] sh: ps: not found
02.05.2015 12:53:32 neuemusikschule.de [client 92.217.53.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
02.05.2015 14:59:35 neuemusikschule.de [client 79.3.69.0] sh: ps: not found, referer: http://neuemusikschule.de/content/inhalt.html
02.05.2015 18:56:39 neuemusikschule.de [client 187.1.46.0] sh: ps: not found, referer: http://neuemusikschule.de/content/inhalt.html
02.05.2015 20:39:36 neuemusikschule.de [client 93.195.123.0] sh: ps: not found, referer: http://neuemusikschule.de/content/inhalt.html
02.05.2015 21:56:29 neuemusikschule.de [client 79.246.97.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html

Dear ALL

I had cecked your answer. These are already exist in that marked file.
So it seems correction-answer will not works.
Pls see my File.

Many thx for your helping hands.
see u
Willi

**Comment by tsteur** [comment]
I'm not really sure what is happening here. Can you try to disable the `IP2Location` plugin and see if you still get any errors?

The error re `ps` could be related to https://github.com/piwik/piwik/pull/7681 but doubt as there as well errors re `groups`, `df`, and it doesn't look like archiving problems.

**Comment by wklueter** [comment]
Dear Thomas


#7681


Many Thx for your reply, I will do it but I can it unfortunately only on evening because i have no Internet-Access at my account in my office





Pls hold on, I will inform you asap.



Mit freundlichen Grüßen

Willi Klüter

**Comment by wklueter** [comment]
dear Thomas 

after deactivating IP2Location and Piwik-update at 2.13.1 these error ever exist.

08.05.2015 03:41:59 neuemusikschule.de [client 188.107.13.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
08.05.2015 09:22:33 neuemusikschule.de [client 148.188.1.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
08.05.2015 11:04:03 neuemusikschule.de [client 79.211.4.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
08.05.2015 12:15:14 neuemusikschule.de [client 89.204.26.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/stellen.html

**Comment by tsteur** [comment]
This could be related to #7681 (run cli on OSX)

**Comment by mattab** [comment]
@mnapoli does CliMulti still work for you if you move https://github.com/piwik/piwik/blob/master/core/CliMulti/Process.php#L175-178 below `        if (self::commandExists('ps') && self::returnsSuccessCode('ps') && self::commandExists('awk')) {` ?

**Comment by mnapoli** [comment]
@mattab It wouldn't work as I don't have NFS (which was the source of the problem), but I've tried an alternative solution here: #7937

**Comment by mattab** [comment]
Looks good - @wklueter can you maybe confirm this fixes the issue for you?

**Comment by wklueter** [comment]
Dear All
Many Thx for your helping hands. Yesterday evening in builded these lines in requested file in.
Today error-log-file looks a little bit better but not solved.
logfile
19.05.2015 18:51:40 neuemusikschule.de [client 89.15.108.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/stellen.html
19.05.2015 21:08:41 neuemusikschule.de [client 91.6.113.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
19.05.2015 22:57:20 neuemusikschule.de [client 2a02:908:100::] sh: which: not found, referer: http://www.neuemusikschule.de/content/akademie.html
20.05.2015 02:56:45 neuemusikschule.de [client 177.99.58.0] sh: which: not found, referer: http://neuemusikschule.de/content/inhalt.html
20.05.2015 04:49:19 neuemusikschule.de [client 2001:e68:5400::] sh: which: not found, referer: http://neuemusikschule.de/content/inhalt.html
20.05.2015 07:14:24 neuemusikschule.de [client 87.210.90.0] sh: which: not found
20.05.2015 10:49:59 neuemusikschule.de [client 82.113.106.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/stellen.html
20.05.2015 12:08:21 neuemusikschule.de [client 2a02:908:dc00::] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
20.05.2015 19:41:18 neuemusikschule.de [client 178.200.115.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html

pls see my php-file

**Comment by mnapoli** [comment]
Since we run the `ps` command to see if it exists the fact that this message is still logged is expected (i.e. just like it was before) :/

**Comment by wklueter** [comment]
Dear Matthieu
thx for info, but I do not really understand, cloud / should I do something ?
Nice Day See u

**Comment by tsteur** [comment]
@wklueter which operating system are you using?

**Comment by wklueter** [comment]
@tsteur: editing homepage: -mostly MS 7, Files with Editor from Adobe, Filetransfer Filezilla-->Modus binary; - fast changes with LINUS, Ubuntu 12,XX, Files with Editor Gedit, same Filetransfer; (only last chances for removing ps /sh Error )
Provider: Strato, Unix ??  Sorry I had forgot it. Ok from your side ? Should I do anything answer? 
Nice Day Willi

**Comment by mnapoli** [comment]
@wklueter You don't have anything to do, there is nothing wrong with your system actually. The log message that you see is Piwik trying to run the `ps` command to see if it works. If it doesn't work, Piwik uses another method.

So there is no problem for you.

**Comment by wklueter** [comment]
@mnapoli  my provider called these log-file "error-logfile", and i check these file 3 time per months, and i get nervous if i see a lot of lines. At first i saw sh: and ps: - message, and now after changing php-file i see only sh-message. That's all.

**Comment by wklueter** [comment]
@mnapoli ; sorry I had forgotten to copy Error-logfile in Comment-Box:
Pls see below:
20.05.2015 10:49:59 neuemusikschule.de [client 82.113.106.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/stellen.html
20.05.2015 12:08:21 neuemusikschule.de [client 2a02:908:dc00::] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
20.05.2015 19:41:18 neuemusikschule.de [client 178.200.115.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
21.05.2015 09:29:50 neuemusikschule.de [client 84.159.87.0] sh: which: not found, referer: http://neuemusikschule.de/content/inhalt.html
21.05.2015 12:02:24 neuemusikschule.de [client 62.246.111.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
21.05.2015 14:06:28 neuemusikschule.de [client 91.6.120.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
21.05.2015 16:47:51 neuemusikschule.de [client 79.192.81.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
21.05.2015 20:56:49 neuemusikschule.de [client 93.195.111.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Class 'Piwik\\Archive\\Parameters' not found in /mnt/weba/d2/34/51062934/htdocs/piwik/core/Archive.php on line 261, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Class 'Piwik\\Archive\\Parameters' not found in /mnt/weba/d2/34/51062934/htdocs/piwik/core/Archive.php on line 261, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Class 'Piwik\\Archive\\Parameters' not found in /mnt/weba/d2/34/51062934/htdocs/piwik/core/Archive.php on line 261, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] , referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] , referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] , referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Class 'Piwik\\Archive\\Parameters' not found in /mnt/weba/d2/34/51062934/htdocs/piwik/core/Archive.php on line 261, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:30 neuemusikschule.de [client 93.195.111.0] , referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:31 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Class 'Piwik\\Archive\\Parameters' not found in /mnt/weba/d2/34/51062934/htdocs/piwik/core/Archive.php on line 261, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:31 neuemusikschule.de [client 93.195.111.0] , referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class 'Piwik\\Archive\\Parameters' not found' in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php:371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] Stack trace:, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #0 [internal function]: Piwik\\Plugins\\CorePluginsAdmin\\Controller->safemode(Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #1 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(531): call_user_func_array(Array, Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #2 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(97): Piwik\\FrontController->doDispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #3 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(184): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #4 [internal function]: Piwik\\FrontController::triggerSafeModeWhenError(), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #5 {main}, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] thrown in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php on line 371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class 'Piwik\\Archive\\Parameters' not found' in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php:371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] Stack trace:, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #0 [internal function]: Piwik\\Plugins\\CorePluginsAdmin\\Controller->safemode(Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #1 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(531): call_user_func_array(Array, Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #2 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(97): Piwik\\FrontController->doDispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #3 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(184): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #4 [internal function]: Piwik\\FrontController::triggerSafeModeWhenError(), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #5 {main}, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] thrown in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php on line 371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class 'Piwik\\Archive\\Parameters' not found' in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php:371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] Stack trace:, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #0 [internal function]: Piwik\\Plugins\\CorePluginsAdmin\\Controller->safemode(Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #1 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(531): call_user_func_array(Array, Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #2 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(97): Piwik\\FrontController->doDispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #3 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(184): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #4 [internal function]: Piwik\\FrontController::triggerSafeModeWhenError(), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #5 {main}, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] thrown in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php on line 371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] PHP Fatal error:  Uncaught exception 'Exception' with message 'Class 'Piwik\\Archive\\Parameters' not found' in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php:371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] Stack trace:, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #0 [internal function]: Piwik\\Plugins\\CorePluginsAdmin\\Controller->safemode(Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #1 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(531): call_user_func_array(Array, Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #2 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(97): Piwik\\FrontController->doDispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #3 /mnt/weba/d2/34/51062934/htdocs/piwik/core/FrontController.php(184): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #4 [internal function]: Piwik\\FrontController::triggerSafeModeWhenError(), referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] #5 {main}, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 20:57:34 neuemusikschule.de [client 93.195.111.0] thrown in /mnt/weba/d2/34/51062934/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php on line 371, referer: http://www.neuemusikschule.de/piwik/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today
21.05.2015 23:39:18 neuemusikschule.de [client 84.163.121.0] sh: which: not found, referer: http://www.neuemusikschule.de/content/inhalt.html

**Comment by mnapoli** [comment]
> PHP Fatal error: Uncaught exception 'Exception' with message 'Class 'Piwik\Archive\Parameters' not found'

It's very likely that an update didn't upload all the files. You should try reuploading Piwik's files manually using the latest release.

**Comment by wklueter** [comment]
@mnapoli I had done it and now goes everything quit well, but now i got  the same errors like before.
pls  help,
I understand these error are only a info but i do not like this. I will my error-log-file empty.
do you undrestand me.
23.05.2015 15:11:35 neuemusikschule.de [client 178.202.57.0] sh: ps: not found, referer: http://www.neuemusikschule.de/content/inhalt.html
23.05.2015 17:53:53 neuemusikschule.de [client 187.183.101.0] sh: ps: not found, referer: http://neuemusikschule.de/content/inhalt.html
