### ISSUE TITLE
Edit personal email report - Report hour is not readable on Firefox

### ISSUE THREAD

**Issue by codeban** [piwik/piwik#7827]
If I edit a current email report (user settings -> email report -> edit) the browser can't display the "report hour".

Page: index.php?module=ScheduledReports&action=index&idSite=1&period=day&date=yesterday

HTML:
```
<input type="text" size="2" class="inp" id="report_hour" style="height: 0.9em;padding-left: 5px;width: 35px;">
```

I had to change **style="height: 0.9em;"** to a higher value.

System:
Mac OS X 10.10
Firefox 37.0.2
Piwik 2.12.0

**Comment by tsteur** [comment]
Can reproduce it with FF 37 on MacOSX as well
