### ISSUE TITLE
Goal url parameter is wrong when generating the image tracking code

### ISSUE THREAD

**Issue by micheleselea** [piwik/piwik#7829]
Hi, I found that in HTTP API if you put "idGoal" as in the img example, the code do not work, You have to use idgoal

**Comment by tsteur** [comment]
Can you post the link to the page where you found the img example?

**Comment by micheleselea** [comment]
The link is automatic generated with the tool in administration page in my site. it's the tool that create the link for you to put in page

**Comment by tsteur** [comment]
Thank you! This is a good find
