### ISSUE TITLE
All websites dashboard don't save period parameter

### ISSUE THREAD

**Issue by semafork** [piwik/piwik#7831]
Hi,

On the All websites dashboard, though I set the parameter "Load dashboard for the current month", the period is still set by default to "current day".

I tried to change the parameter, save, and put it again on "Current month", it does nothing.

Thanks

**Comment by tsteur** [comment]
I think this is a duplicate of #7795. Please reopen if not.

**Comment by semafork** [comment]
You're right. It's a duplicate. Sorry.

Thanks
