### ISSUE TITLE
Rename "Widgets & Dashboard" selector or change the selector

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7835]
When viewing the dashboard, there is a selector that says "Widgets & Dashboard":

![widget_dashboard_2](https://cloud.githubusercontent.com/assets/273120/7466915/3100da38-f341-11e4-81d9-d211bc7a6a0c.png)

This selector let's you
* Add widgets to a dashboard
* Manage dashboards (rename, create, change layout, ...) 

Both is in the end "Dashboard". I would prefer to rename it to only "Dashboard(s)". I don't think everyone knows what "Widgets" are and it is therefore not really important here. In the end one adds a widget to the dashboard but this is still "Dashboard". For example like this:

![widget_dashboard_1](https://cloud.githubusercontent.com/assets/273120/7466914/30fc47d4-f341-11e4-9176-8f3b6a8b1432.png)

If we do not want this change, we should split it into 2 selectors similar to what we did before with "Goals & Ecommerce". We could have one selector named "Widgets" or "Add widgets", and another selector "Dashboards" or "Manage dashboards". This will make each selector easier. Also we could use eg a `+` icon for "Add widgets" instead of the arrow icon similar to segments.

![widget_dashboard_3](https://cloud.githubusercontent.com/assets/273120/7467002/d3b6211a-f342-11e4-9a84-627f8ffd61b8.png)

I would prefer to go just with "Dashboard" as I find the term "Widgets" is not really important there. Maybe there are other ideas? It is a bit weird to let people "Manage Dashboards" there but just left to it select segments and a date, whereas one select a dashboard in the submenu.

Maybe we could kinda do it like on Github and use icons on the right. Although it is harder to discover this way (and on demo.piwik.org only we are currently showing a message there but this can be changed)

![widget_dashboard_4](https://cloud.githubusercontent.com/assets/273120/7467119/0af75e94-f345-11e4-9f22-d3dc82c8e813.png)

**Comment by mattab** [comment]
Hi @tsteur thanks for the suggestion!

> I would prefer to rename it to only "Dashboard".

Sounds like a good idea, anyone else have any feedback?

**Comment by mnapoli** [comment]
+1 for renaming to Dashboard
