### ISSUE TITLE
Deprecate no longer needed / wanted events

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7837]
Piwik 3.0.0 will be happening soon. Therefore we should mark some events as deprecated soon. This will allow us to remove them in Piwik 3.0.0. We also need to make sure to remove those events in a follow up issue in Piwik 3.0.0. Why is this important? Imagine you update from 2.X to 3.0.0. Your Piwik works fine. If we actually remove those events in 3.1.0 and someone else updates to 3.1.0 it can break his Piwik although such an update should not break as it is not a major version update.

In the past I noticed some events that are no longer really needed/wanted, should be renamed or cause performance problems (like `Site.getSite` did).  We should go over the list of events (http://developer.piwik.org/api-reference/events) and see if this is the case for some of them. Please comment if you know any event.

Part of this issue is also to make sure that all deprecated events are documented in our developer changelog. Eg we already deprecated many events like `Menu.Reporting.addItems`, `API.getReportMetadata`, `WidgetsList.addWidgets`.

**Comment by tsteur** [comment]
I'd like to deprecate following events: 

* `Tracker.existingVisitInformation`
* `Tracker.getVisitFieldsToPersist`
* `Tracker.makeNewVisitObject`
* `Tracker.newConversionInformation`
* `Tracker.newVisitorInformation`
* `Tracker.recordAction`
* `Tracker.recordEcommerceGoal`
* `Tracker.recordStandardGoals`

They were kinda all replaced by `Dimension` classes. Deprecating them will at least allow us to remove them at some point. 

Maybe:
* `View.ReportsByDimension.render` I'm not sure if it's used / needed and for what. 

I need to look later again re events.

**Comment by mattab** [comment]
It would be great if we could deprecate ScheduledReports events:

 *    `ScheduledReports.allowMultipleReports`
 *   `ScheduledReports.getRendererInstance`
 *   `ScheduledReports.getReportFormats`
 *   `ScheduledReports.getReportMetadata`
 *   `ScheduledReports.getReportParameters`
 *   `ScheduledReports.getReportRecipients`
 *   `ScheduledReports.getReportTypes`
 *   ScheduledReports.processReports
 *   `ScheduledReports.sendReport`
 *   `ScheduledReports.validateReport`

cc @JulienMoumne 

(possibly we could replace them with a single class or so. )

**Comment by tsteur** [comment]
Those events are actually used so it would not be done by simply deprecating them. We'd need to refactor the ScheduledReports. I reckon this won't be rather not doable for Piwik 3.0.0 so would maybe leave them there? If we have no other deprecations I would deprecate the Tracker events soon and close the issue.

**Comment by mattab** [comment]
@tsteur if we exclude `ScheduledReports.*` what are the next steps / work scope to deprecate those `Tracker.*` events? 

eg. will we maybe need to write better developer documentation Re: dimensions, to let them know how to hook into Tracker (eg. new visit, new action, new goal conversion, new ecommerce conversion, etc.)

**Comment by tsteur** [comment]
Yes, and I will write a short guide then. Basically, we will only document how to generate them and the difference between VisitDimension, ActionDimension and ConversionDimension. The generated code is already documented and will help them to get something down. This will be enough for the beginning as Archiving etc is still very complex anyway. Also PiwikPHPTracker misses methods to track custom data etc.

**Comment by tsteur** [comment]
FYI: I created a PR for the docs in https://github.com/piwik/developer-documentation/pull/100 as we deprecate the events we need to provide docs for the alternative solution
