### ISSUE TITLE
$userPreferences->getDefaultReport() gives Empty String when not set.

### ISSUE THREAD

**Issue by pouyana** [piwik/piwik#7839]
A User with view Access, can not visit her/his settings (citing no IdSite was set). After testing I found out that in `UsersManager->UserSettings()` the `$userPreferences->getDefaultReport()` gives `""`, an empty string. Going to `UserPrefrence` class, you see this:
```php
    public function getDefaultReport()
    {
        $defaultReport = $this->api->getUserPreference(Piwik::getCurrentUserLogin(), APIUsersManager::PREFERENCE_DEFAULT_REPORT);
        if (!is_numeric($defaultReport)) {
            return $defaultReport;
        }
        if ($defaultReport && Piwik::isUserHasViewAccess($defaultReport)) {
            return $defaultReport;
        }
        return false;
    }
```
So having empty string leads to sending empty string to view controller, I changed the `!is:numeric` to `is_numeric` and everything works.

So is there any other solution than here working or should a default-report be set for a newly created user?

**Comment by tsteur** [comment]
You should not change `!is_numeric` to `is_numeric`. It should not lead to any security issues I think but when a user logs in and this functions returns a site the user doesn't have access to, the user might not be able to do anything.

Can you execute the following SQL query and post the result here?

```sql
select * from piwik_option where option_name like 'YOURUSERNAME_defaultReport';
--or following helps you seeing if there is an entry for your username
select * from piwik_option where option_name like '%defaultReport%';
```

Can you go to your user settings, select the default report to load again and press "Save". Does it change anything?

Is it otherwise possible, that the user you are testing, does not have access to any site?

**Comment by tsteur** [comment]
Please reopen if you can still experience this issue after 2.13.1. Would be nice if you could still answer above questions. Maybe before updating to 2.13.1?

**Comment by pouyana** [comment]
Hi I was not checking sorry for the delay, the result of the your query:
`+-----------------------+--------------+----------+`
`| option_name           | option_value | autoload |`
`+-----------------------+--------------+----------+`
`| USERNAME_defaultReport |              |        0 |`
`+-----------------------+--------------+----------+`
`1 row in set (0.00 sec)`
Yes the user doesn’t have access to any sites when it was created. I just add the user after it was created to different sites.
The problem was that without the change I made, I was unable to see the setting as the user. but after the page is shown and I save the option once:
`+-----------------------+--------------+----------+`
`| option_name           | option_value | autoload |`
`+-----------------------+--------------+----------+`
`| USERNAME_defaultReport | 1            |        0 |`
`+-----------------------+--------------+----------+`
`1 row in set (0.00 sec)`
it is saved.

**Comment by pouyana** [comment]
So after the update the bug is solved thanks for the help :D

**Comment by tsteur** [comment]
Thx for letting us know!
