### ISSUE TITLE
Update FAQ "How do I use Piwik from the official Git repository?"

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7842]
http://piwik.org/faq/how-to-install/faq_18271/

There is already a note that we do not recommend to use latest master on production server. This note is at the very end. We should really put this note above the bash example how to do it.

Even more importantly we should explain why it is not good to use an installation from git in Production/QA/Testing/ ... or on any server that can be accessed by anyone via the Internet/Intranet. Piwik via git should be only used for development. This warning must be at the very beginning. Some reasons:

* It is a security risk: For example in our `piwik.zip` we remove many files that are not needed in production and could potentially even cause harm. For example all of our test files etc.
* Some default settings are changed which cause Piwik to be slower than using `latest.zip` (this will happen in near future but we should still warn re this) refs #6536

Users are not aware that it is not good to use Piwik via git see for example https://github.com/piwik/piwik/issues/7838#issuecomment-99112824 

Recommendation for users who still want to install Piwik via git:

A user should instead consider to commit the content of `latest.zip` into a repository, tag a new version, and checkout this version on your server that only contains the files that are supposed to be in production. 

If we don't update this FAQ, I would almost insist that we create a repository (or a branch) for the content of `latest.zip` ourselves, that we maintain it and put the URL of that repository into the FAQ.

**Comment by mnapoli** [comment]
:+1: we should say it's not supported at all. Sometimes it impacts us in our work (we have to think of this use case) but we shouldn't have to care about it (I remember a few times where we had to test/do a few things to preserve this use case).

**Comment by tsteur** [comment]
> we should say it's not supported at all.

We should say it's not supported and we still should explain why and how they can do it better as there otherwise always will be users who just do it though.

**Comment by mnapoli** [comment]
:+1:

**Comment by AndersBillLinden** [comment]
There should also be a note that the full path to composer.phar must be given in the command `php composer.phar install` and what composer actually is maybe?

**Comment by tsteur** [comment]
I'd recommend something like the following:

To use Piwik the recommended way is to download the latest stable version. It is not recommended to use Piwik directly from out Git repository for various reasons:

* The Piwik version from Git contains files that are only needed for development. Those files are not needed in production and could potentially cause harm, for example our test files.
* Some default settings are different which can cause Piwik to be slower. For example caches might be disabled by default. 

In case you want to use the very latest bleeding edge Piwik nonetheless, you may use Piwik directly from our Git repository. 

To deploy Piwik from Git, run the following commands once:

THE EXAMPLE HOW TO INSTALL APPENDED BY

`./console development:disable`

**Comment by tsteur** [comment]
@mattab this is something you probably would need to update? I mean the FAQ

**Comment by mattab** [comment]
FAQ was updated: [How do I use Piwik from the official Git repository?](https://piwik.org/faq/how-to-install/faq_18271/)
Thanks Thomas
