### ISSUE TITLE
Change report period when month start reached

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#7849]
Hi!
Now when we reach the month start Piwik report about `no data for this report`. Maybe it will be better if month automatically change to the previous?

And I found a bug in `Visitor log`. When the month start reached and I press `Next` again and again(example 5 times), I need press `Prev` 5 times too.

PS! Piwik 2.13.0

**Comment by mattab** [comment]
Hi @Globulopolis 

> Maybe it will be better if month automatically change to the previous?

Not sure, it's maybe better not to change behavior based on time of month... did you select "Default period = Current month" in your personal preference?
