### ISSUE TITLE
Piwik 2.13.1 is missing .tar.gz archive

### ISSUE THREAD

**Issue by aureq** [piwik/piwik#7860]
Hi,

It seems like piwik 2.13.1 is only available in a `.zip` format.
Up until 2.13.0, piwik archives used to be available in both `.zip` and `.tar.gz`.

Could we please confirm the change so I can update the piwik-package repository as well.

Thanks.

**Comment by mnapoli** [comment]
I know @mattab had trouble uploading the release 2 days ago because of very slow internet, maybe it's the source of the problem. He might have been able to upload the zip only. I don't expect him to be able to look at this until monday/tuesday FYI.

**Comment by mattab** [comment]
tar.gz package was now uploaded as well - sorry for the delay!
