### ISSUE TITLE
Scheduled Report covers wrong timespan

### ISSUE THREAD

**Issue by futureweb** [piwik/piwik#7862]
I'm having a Problem with my Piwik reports. I have set the time span of the report to "last 7 days excl. today" but sometimes the report I receive coveres the penultimate week.
e.g. on april 27th I recived the Report for the week of april 13th - april 19th....

http://forum.piwik.org/read.php?2,126167,126328#msg-126328

**Comment by mattab** [comment]
Hi @futureweb thanks for the report. We got a few reports in the forum of users who receive the scheduled report from penultimate week instead of previous week.

**Comment by sgiehl** [comment]
@futureweb are you sending the reports at 0 o'clock?
If so maybe that might be a timezone issue.

**Comment by mgonera** [comment]
@mattab @sgiehl I have similar occurrence: report fetches data using &period=range&date=last30 instead of fetching data from previous month. Can this also be treated as part of this bug to be improved, or rather separate issue? Thanks!

**Comment by sgiehl** [comment]
Maybe that is something else, as the timespan is somehow correct - even if last month should not be last 30 days

**Comment by mattab** [comment]
Please @futureweb try again with piwik 2.17.0 where this issue might have been fixed (as we solved issue related to sending reports at given hour of the day & timezones)
