### ISSUE TITLE
Zip archive and GPG signature don't match for Piwik 2.13.1

### ISSUE THREAD

**Issue by aureq** [piwik/piwik#7863]
@mattab @mnapoli 

Following the missing `tar.gz`archive (#7860), I've been trying to improve the Makefile used to generate the Debian package.
During this process, I've discovered that the `zip` and `zip.asc` do not match.

Could we please have a look at this ?
md5: `61ef6b4590a1263fa5f31bde89d258e8  piwik-2.13.1.zip`
md5: `3825d7752646efac96ddd418d23ad38a  piwik-2.13.1.zip.asc`
sha256: `c7bb651fbd9e8349c47b6fa0a93e8a798a477d5ef8ac9bc9e415d266e24cb5b0  piwik-2.13.1.zip`
sha256: `adcf61ec86256c666eef7c7547f8d79366e27e3d41c2f07ddbff4253801a9b8c  piwik-2.13.1.zip.asc`

GPG Error (`gpg --verify piwik-2.13.1.zip.asc`):
`gpg: Signature made Thu 07 May 2015 09:52:31 AEST using RSA key ID 5590A237`
`gpg: BAD signature from "Matthieu Aubry <matt@piwik.org>"`

**Comment by mnapoli** [comment]
See [this comment](https://github.com/piwik/piwik/issues/7860#issuecomment-100337569). FYI the release script first uploaded the zip but it failed at 100%, so he started again manually using filezilla IIRC, maybe the difference comes from that.

**Comment by aureq** [comment]
Thanks for the heads-up @mnapoli !
Just to let you know it's a blocker for me to publish the latest version of the Debian package.

Cheers

**Comment by mattab** [comment]
Hi @aureq  - thanks for the report. This should work now I've repackaged the release with correct signatures. (During last release I had some problems with unreliable internet)
