### ISSUE TITLE
Increasing the maximum number of slices to display in pie charts

### ISSUE THREAD

**Issue by myluis** [piwik/piwik#7865]
Hi,

I am trying to increase the maximum slices that my pie chart result can display. Instead of having just 5 or 6 slices, I would like to increase it. I have had a look at Core/Visualization folders piwik version 2+, but there was no where to increase it. Can someone direct me to the right place please?

Any advise will be appreciated.

**Comment by sgiehl** [comment]
The default config for that is set in https://github.com/piwik/piwik/blob/master/plugins/CoreVisualizations/Visualizations/JqplotGraph/Pie.php#L27
That config value can be overwritten like in https://github.com/piwik/piwik/blob/master/plugins/Resolution/Reports/Base.php#L29

**Comment by myluis** [comment]
Stefan, thank you so much. Your response is so much appreciated.
