### ISSUE TITLE
Move sites (data) from one to another server

### ISSUE THREAD

**Issue by featurereq** [piwik/piwik#7868]
There is no functionality to move data between the servers (not to merge, but move). For example, there are two Piwik servers, Serv1 and Serv2. Each of the servers tracks several websites. There should be a way of moving data from one to another server without a significant interruption in tracking. If we have sites A, B, and C on the Serv1, and sites D, E, and F on the Serv2, we should be able to move sites i.e. A and C to Serv2 and be able to continue tracking with the history available. We should be able to end with site B on Serv1 and sites A, C, D, E, and F on Serv2.

**Comment by sgiehl** [comment]
Please have a look at the SiteMigration plugin: http://plugins.piwik.org/SiteMigration

**Comment by featurereq** [comment]
Thanks. Tried it several times, always fails because of write permissions. Very limited for average people. What permissions exactly are needed? IS data preserved for each website separately?

Thank you

**Comment by sgiehl** [comment]
Haven't done anything with that plugin yet. Maybe create a issue at the plugin repo (https://github.com/PiwikPRO/plugin-SiteMigration)

**Comment by mattab** [comment]
FYI we have released a new plugin which lets you migrate one website from one Matomo instance to another. Get it for free at http://plugins.matomo.org/Migration
