### ISSUE TITLE
The class UsersManager couldn't be found in the file plugins/UsersManager/UsersManager.php

### ISSUE THREAD

**Issue by iahoo** [piwik/piwik#7873]
Hi guys,

I got this error after Updating:

The class UsersManager couldn't be found in the file '//plugins/UsersManager/UsersManager.php
I saw this file on the told root but there is just a empty php file.
How can i fix it?

**Comment by mnapoli** [comment]
This was probably a problem when downloading/updating files. I have downloaded the latest zip and checked: the file is not empty. Please reupload the files manually.

For the record this is related to #7527
