### ISSUE TITLE
Some widgets have wrong styles in widget preview (headline etc)

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7879]
See screenshot. For example Visits Overview with graph.

Tested on Chrome 42 + Mac OSX.

![widget_preview](https://cloud.githubusercontent.com/assets/273120/7558353/3fc45c2a-f7f6-11e4-8d5d-7a52f046012f.png)

**Comment by mnapoli** [comment]
Good catch, turns out that it's even worse than I thought there are a lot of CSS rules for widget that apply only inside the dashboard element. That means that the selector you are showing, as well as embedded widgets have different styles. For example they don't have the same border color!

**Comment by mnapoli** [comment]
PR: #7950
