### ISSUE TITLE
iOS client event tracker issue.

### ISSUE THREAD

**Issue by issueli** [piwik/piwik#7882]
Server version : 2.12.1
piwik-iOS-sdk version : 2.5

1.set parameters according document .
2.call method [sendEventWithCategory:@"Event" action:"Launch_App" label:nil];

expected result 
The event will show in "Dashboard->Actions->Events" .
But real result  
The event show in "Dashboard->Actions->Pages" , and  "Dashboard->Actions->Events" no data report.

and I call method [sendView:"LoginView"]; also will show in "Dashboard->Actions->Pages".
How can I do that make event will show in  "Dashboard->Actions->Events" ?

Please help me to fix this bug, thanks!

**Comment by tsteur** [comment]
Shouldn't this be an issue for https://github.com/piwik/piwik-sdk-ios/issues ? Or is it actually an issue in Piwik?

**Comment by issueli** [comment]
Oh, I didn't notice this.

**Comment by tsteur** [comment]
No worries, do you mind creating the issue there?

**Comment by issueli** [comment]
Yes, I'm waiting for answers .Thanks for you help!
