### ISSUE TITLE
Allow plugin developers to get their plugins translated by the piwik community

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#7883]
We already have some more or less successful plugins listed on plugins.piwik.org
Most of them are only available with english translations or maybe some more languages.

As we have a community helping us to translate Piwik to many languages on transifex, we should give plugin developers the possibility to get their plugins translated.

There is not that much to do to make that possible:

- [x] Check that console command to update translations work for users not having full access to transifex project
- [x] Write a How-To / Update development guide

Proposed How-To:

- Developer needs to get in touch with translations@piwik.org to let us know he would like to get translations
- After a short check someone (likely me) will add the translation file hosted on github to our transifex project (and also the already available translations)
- The developer should then be able to update the plugin translation files using the piwik console ```console translations:update -P plugin```

Most Piwik & PiwikPRO plugins are already available for translation on Transifex.
NOTE: We must not add plugins on transifex that are not open source!

@piwik/core-team Thoughts or suggestions anyone?

**Comment by tsteur** [comment]
:+1:

**Comment by sgiehl** [comment]
Non-Maintainer users are not able to fully use the api methods for the project.
That means we can't simply add new resources for the plugins if the developers should be able to update on their own.
We could create a new project for each plugin and add the developer as a maintainer. If so we would need to adjust the console commands a bit, but that shouldn't be a problem.

I've justed tested that with my own plugin ReferrersManager.
See https://www.transifex.com/organization/piwik/dashboard/piwik-plugin-referrersmanager
I think it should be good enough that way.

The only other solution I see right now, would be not to allow the developer to update on his own, but to create pull requests for their plugins to update the translations...

**Comment by mattab** [comment]
Overall it's a super idea to provide easy way for Third party plugin developers to get their plugins translated and reusing our transifex tool. 

> We could create a new project for each plugin and add the developer as a maintainer. 

If we do this, how will the plugin developer import the translations in the plugin repo? would it be automatic or would developer need to manually import translations.

**Comment by sgiehl** [comment]
I'd do the initial set up, which contains an auto update path for english translations on git.
If there are already translations for other languages they need to be imported. But that's easy to do.

Nevertheless, I'm still searching for another solution. I've created a project for my plugin and none of the translators already started to translate it. I guess that's because they would need to switch to the project... Maybe I can find a solution where we could handle that with only on project

**Comment by sgiehl** [comment]
Ok. I found a solution how to handle all in one project.
Moved my plugin translations to a resource in piwik project.
Problem was the api to fetch available languages for the project. That is not available for non-maintainers. But there is no need to call it when updating plugin translations.

So we will have a new resource for each third party plugin within our piwik transifex project.
I'll name those resources 'Third-Party Plugin ``pluginname``'.

I'll propose an update for the developer documentation. @mattab or @tsteur maybe you can have a look there then. Afterwards we might publish a small blog post and announce that on twitter/facebook.

Anymore thoughts or comments?

**Comment by sgiehl** [comment]
Note: Need to be announced on piwik blog, facebook and twitter and can be closed afterwards

**Comment by mattab** [comment]
@sgiehl Sounds good! Get in touch and we can post on the blog and social media.

**Comment by sgiehl** [comment]
@mattab feel free to post it. Guess we can use some parts of the [developer docs](http://developer.piwik.org/guides/translations#getting-translations-for-your-plugin-)

**Comment by mattab** [comment]
Hi @sgiehl is the draft content ready, or do we need to write something?

**Comment by sgiehl** [comment]
Haven't had time to write something the last days... So we need to write it

**Comment by mattab** [comment]
We published the blog post: [How to get your Piwik plugin translated in many languages?](https://piwik.org/blog/2015/09/how-to-get-your-piwik-plugin-translated-in-many-languages/)

Therefore this issue is closed: translators of open source plugins can now easily get their plugins translated by the Piwik translator community. Really a great move @sgiehl  :+1:
