### ISSUE TITLE
Incorrect number of records returned after segment filter applied.

### ISSUE THREAD

**Issue by ruchitrami** [piwik/piwik#7890]
I am trying to get list of visits with segmentation based on userid and eventCategory. Also, I am using filter_limit for my use case. Following is the call url I am using. 

/?module=API&method=Live.getLastVisitsDetails&idSite=1&format=xml&filter_limit=10&filter_offset=0&period=range&date=2015-04-12,2015-05-12&segment=userId!=0;eventCategory==General

Problem: In the above URL call, it returns me only 3 records. If I increase the filter_limit to 20 the number rises to 5. So, the API is applying segmentation AFTER filter_limit, instead of doing it in reverse order.

**Comment by tsteur** [comment]
This is a duplicate of #7784

**Comment by ruchitrami** [comment]
It has been marked as duplicate of #7784 and #7784 is marked as duplicate of #7890 and both are closed.

**Comment by tsteur** [comment]
#7784 should be still open
