### ISSUE TITLE
Expand Outlinks / Downloads if only one domain given

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7891]
Maybe also for "Pages" and "Page title" report if only one directory given. Or to describe it in general: If only one row on a certain level is given, it might make sense to expand this one automatically. 

See for example following screenshot:

![outlink_normal](https://cloud.githubusercontent.com/assets/273120/7598936/52fddf48-f952-11e4-8b31-ea052498fb3c.png)

It's kinda obvious that my next click will be to expand that domain and it will look like this:

![outlink_expanded](https://cloud.githubusercontent.com/assets/273120/7598950/66922fe6-f952-11e4-8b93-886637d1138d.png)

Ignore the broken characters this is because of testing #7866.

For pages, if there is only one first level and one second level row, we could maybe even expand the first and second row automatically.

There's one disadvantage: It makes it a bit harder to see whether are downloads / outlinks / ... from multiple domains. Eg imagine there would be 50 different outlinks under `example.org` and it would not fit into one screen when automatically expanded. So it is not directly possible to see whether there's a second domain further down. But I think the advantages would overweigh the disadvantage and people might notice if the table is expanded automatically, that there won't be a second first level row (it's hard to learn this behaviour as a user though I reckon).

For many users that have eg downloads only from one domain or all pages under a certain directory it must be very annoying to always open them to see the stats.

I've seen this behaviour in many products. For example PHPstorm would automatically open all folders if there is only one folder/file in it.

**Comment by mattab** [comment]
+1, I've had this issue before and it's always bit frustrating to have to click to expand the domain to see details.

**Comment by tsteur** [comment]
I just quickly checked whether it is easily doable and it was pretty easily doable. I prepared a patch and will at some time try to create a test for it when I fell like needing to work on something else. 

It is actually pretty nice since it also works eg when having the following structure

* blog
  * 2015
     * 04
       * 24
          * my blog post title
  * 2014
    * 02
    * 03
    * 04

When clicking eg on `blog` and then `2015`, it would then automatically open `04` and `24` which is really nice.

**Comment by mattab** [comment]
> When clicking eg on blog and then 2015, it would then automatically open 04 and 24 which is really nice. 

:+1:

**Comment by mattab** [comment]
done in #8018
