### ISSUE TITLE
link tag (shortcut icon) generated twice in Morpheus/templates/layout.twig

### ISSUE THREAD

**Issue by kixe** [piwik/piwik#7897]
piwik/plugins/Morpheus/templates/layout.twig:
  13:             link rel="shortcut icon" href="{{ customFavicon|default('plugins/CoreHome/images/favicon.ico') }}"/
   14  
   15              {% include "@CoreHome/_favicon.twig" %}

please remove!!

**Comment by sgiehl** [comment]
Thanks for the report. You're right, it's defined twice
