### ISSUE TITLE
Piwik under sub path URL

### ISSUE THREAD

**Issue by maggo2801** [piwik/piwik#7898]
I run Piwik under the following domain http://tools.daten-reich.de/piwik . 
The Problem is that different URLs from Piwik ignore the sub path /piwik.

404 - http://tools.daten-reich.de/plugins/Morpheus/images/logo.svg
404 - http://tools.daten-reich.de/?module=MultiSites&action=getEvolutionGraph&period=day&date=2015-04-14,2015-05-13&evolutionBy=nb_visits&columns=nb_visits&idSite=3&idsite=3&viewDataTable=sparkline& ......

**Comment by mattab** [comment]
Hi @maggo2801 
can you reproduce this problem with Piwik 2.14.0?

**Comment by mattab** [comment]
@maggo2801 if you still experience this in 2.14.3, please reopen the issue, thanks

**Comment by mattab** [comment]
Also reported in forums: http://forum.piwik.org/read.php?2,129036

> I just got an untrusted host error-screen and I noticed that the website icon doesn't load properly. The link to the image is wrongly generated by piwik.
> Instead of http://domain.tld/misc/user/logo.png it's http://85.**.***.47/misc/user/logo.png (IP-address)

**Comment by sgiehl** [comment]
I have a Piwik running under a subpath without any problems. The report is already 2 years old, so I assume it was fixed in one of the last versions as we didn't get similar reports meanwhile. If anyone is still having this problem, please open a new issue.
