### ISSUE TITLE
Visitor Profile Widget should not be visible to anonymous users

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7899]
See widget preview:

![visitor_profile_widget](https://cloud.githubusercontent.com/assets/273120/7622161/e979283c-fa20-11e4-8e51-ec732c3f5648.png)

**Comment by sgiehl** [comment]
What is that widget even good for? I would recommend to remove it.
It's confusing... What visitor is displayed? The last one in the choosen period?
And why is it not possible to choose the visitor that should be displayed or maybe click through all available?

**Comment by tsteur** [comment]
I don't know :) But I think it's possible to click through all of them, there should be some arrows somewhere (on hover).

**Comment by mattab** [comment]
the widget shows the latest visitor id profile. it's a bit confusing and of limited use however it is useful to some users. That's because users may want to Widgetize the Visitor Profile for a given Visitor id; for example they may include an iframe to show a visitor within their CMS or CRM.
