### ISSUE TITLE
How do I monitor that Piwik service is up? 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7904]
Let's create a new FAQ to document how to monitor that a Piwik server is running smoothly. 

What do you think?

### How do I monitor that Piwik service is up?  

To monitor for Piwik service, setup the following checks:
 * Tracker API: request to /piwik.php should return http status 200
 * Core platform: request to /index.php?module=API&method=API.XXX  should return http status 200

We recommend to use `https://` in the checks URLs so you're also checking Piwik works over secured connection.
  
Likely the tool you use for monitoring will let you know the services Uptime (eg. 99%) which is useful metric.

**Comment by mattab** [comment]
Notes

  * maybe we could create a new API for this purpose of monitoring, or simply use API.getPiwikVersion for now.
  * Note that HTTP 503 is returned when there is pending DB upgrade #7903
 or Piwik is in maintenance mode #7901 
  * HTTP 500 error is returned when DB connection fails #7903

**Comment by mattab** [comment]
FAQ was created: [How do I monitor that Piwik service is up and running?](https://piwik.org/faq/how-to/faq_20278/)

**Comment by gaumondp** [comment]
I read @mattab FAQ and was wondering if the check involved the database at all. If "MySQL has gone away" the test to index.php?module=API&method=API.getPiwikVersion would still work right ?

If it's the case (no DB call) I will create a new FC for a second test involving the DB.

I'm aware a check could be done directly to MySQL with monitoring tools but having the check from within Piwik would be more simple to setup I think.

**Comment by mattab** [comment]
the index.php check will detect when Mysql server is down and http status should be 500

however the piwik.php check will still work when mysql is down, I looked whether we could provide a piwik.php check that detects the db is down, but it's not easy, so decided not to do it

**Comment by gaumondp** [comment]
Ok then.

BTW, the FAQ seems incomplete. We need the &token_auth= . If not, we still get a 200-OK but also an error message saying we don't get view rights in the XML response :

`<result>
<error message="Vous ne pouvez accéder à cette ressource, ceci requiert au moins un accès de type view à un site web."/>
</result>`

**Comment by mattab** [comment]
Thanks @gaumondp FAQ has been updated with token_auth

**Comment by mritzmann** [comment]
Does the check also check whether the archiving job is running successfully?

**Comment by mattab** [comment]
No it doesn't
