### ISSUE TITLE
Showing the values of a url

### ISSUE THREAD

**Issue by myluis** [piwik/piwik#7905]
Hello,

Help with this question please. I am analysing some result data  in piwik. When I go to the link Action, Pages and Page url, I see the results with some web urls. But I want to be able to check who those id, etc owners are.

Actions > Pages > Page url

https://www.mywebsite.org/school/view.php?id=15
https://www.mywebsite.org/mod/page/view.php?id=30
https://www.mywebsite.org/course/view.php?id=86

Is it possible to know who the full web url especially the ?id=15, ?id=30, and  ?id=86 stand for in piwik please?

Your advise will be of great help.

Thanks

**Comment by mattab** [comment]
Hi @myluis if I understand correctly, maybe you want to "Flatten" the report? in the report, click on Cog icon, then click "Make it flat". If that's not what you're looking for please leave a comment

**Comment by myluis** [comment]
Hello,
Thanks for your reply and advice. I was actually trying to get the meaning for those values in the url. I have now used another method to do it. Thanks a lot.
