### ISSUE TITLE
WP-Piwik Not tracking my stie at all

### ISSUE THREAD

**Issue by mwaters5** [piwik/piwik#7906]
I am using Blue Host as my Host. Im currently hosting 8 different sites (All Wordpress) on the same server account. i have used wp-piwik as the plugin to configure all of them. of the 8 sites I am hosting with Blue host. 3 of them workk just fine with Piwik. The rest I get this error: http://screencast.com/t/9yYCta6R3uR

I have called Blue Host and they have verified with me that they are not blocking anything on their side so the problem seems to be on my side.

Can you give me any idea ??? I am willing to pay $$$ for a resolution.

I also tried manually inserting the Code on my site before the /body tage and that hasnt worked as well.

**Comment by mattab** [comment]
Hi @mwaters5 

Do you see any warning or error in the System check in Administration?

what is your website URL?

See also: http://piwik.org/faq/troubleshooting/faq_58/

**Comment by mattab** [comment]
We didn't hear from you @mwaters5 so closing
