### ISSUE TITLE
Pulling data from moodle mysql database into piwik

### ISSUE THREAD

**Issue by myluis** [piwik/piwik#7910]
Hi,

I have moodle_analytics and piwik installed successfully. They are working well together. Piwik is able to report form my moodle site.  My problem now is this. There are some data in my moodle mysql database table that I want to display on a page in piwik. Is it possible to do this please? Or what it the best way to go about it?

Any advice will be useful.

Thanks

**Comment by tsteur** [comment]
That's possible via a plugin. See http://developer.piwik.org/guides/getting-started-part-1, http://developer.piwik.org/guides/pages . You can access the database via this method http://developer.piwik.org/api-reference/Piwik/Db . For further questions please ask in our plugins & platform forum: http://forum.piwik.org/list.php?9
