### ISSUE TITLE
Allow CLI archiving for only specific segments

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#7912]
Goal of this issue is to give ability of processing only certain segments when running CLI archiver.
There are some cases when only couple of segments need to be re-processed (due to archiving failure or so). For this purpose it would be ideal to have new parameter for ex. --force-idsegments, that will allow passing id's of segments to archive. For sites with 20-30-40 segments it may be extremely inefficient to query for all segments.

Please let me know if you have any questions or want better justification for this request?

**Comment by mgazdzik** [comment]
I've been also thinking about passing segment definitions, but it's opening lots of places for possible error while using such param.
Also possibly a good company to 'force-idsegments' would be 'skip-idsegments' so we can include and exclude some pre-defined segments from being processed (may be many reasons for that I believe)

**Comment by mattab** [comment]
Thanks for the suggestion @mgazdzik 

 *  sounds good to me to add `--force-idsegments` and `--skip-idsegments`  
 * if we add these, we need to display the idsegments in the `core:archive` output as well. Maybe could be done as follows:
```
INFO [2015-05-20 05:48:11] - pre-processing all visits
INFO [2015-05-20 05:48:11] - pre-processing segment 1/1 contentName==xx (idsegment = 42)
```
 * when a idsegment is forced, it should be forced only for those websites where the segment is actually defined and available (ie. either the segment was created for this website specifically, or the segment is set to 'Displayed to [all websites]')

**Comment by mattab** [comment]
Do you ideally need this feature in 2.14.0 ?

**Comment by quba** [comment]
Would be also nice to have option to skip all segments.

**Comment by diosmosis** [comment]
Forgot about this issue, will put up a PR soon.
