### ISSUE TITLE
piwik disable gravity form conflict

### ISSUE THREAD

**Issue by menardmam** [piwik/piwik#7914]
WP 4.2.2, gravity form Version 1.9.8 and piwik Version 0.10.0.6
when gravity form and wp and enable, everything work fine, form can be edit with javascript (jquery), IF you enable wp-piwik, the form still word but CANNOT be edit because javascript jquery conflict and all javascript for gravity form are disable...

**Comment by tsteur** [comment]
Shouldn't this issue be created on the Piwik Wordpress plugin?

**Comment by mattab** [comment]
Hi @menardmam please report the issue on WP-Piwik forum.
