### ISSUE TITLE
3 problems - SEO - quickedit - link

### ISSUE THREAD

**Issue by maguilakindafunky** [piwik/piwik#7916]
Hello !

Thanks for Piwik ! you guys rock !

We have an issue with piwik though... I had to de activate it because every time I activate it my Yoast SEO plugin does not work, nothing happens when I click quickedit and nothing happens when I try to add a link.

This is all inside wordpress by the way.

Cheers

Raul

**Comment by tsteur** [comment]
Thx for the nice feedback! 

Do you use the Piwik Wordpress plugin? If so, should this issue maybe created there?

Otherwise it would be nice to know more about what you have installed and how one can reproduce it.

**Comment by maguilakindafunky** [comment]
Hi,

We have a blog in germany, we use Piwik because people hate google in Germany. About a month ago my wife said.. you know what? I can’t add links anymore while writing posts. ( She had to do it in code). Then she said quickedit is not working anymore. Also our SEO plugin stopped working. I thought it was a  problem with the automatic wordpress update. I updated the website manually and we still had the problem. Then I decided to turn off all the plugins and everything was working again, then I turned back all the plugins one by one and noticed that Piwik was the one breaking those 3 things.

Is there a way to have Piwik running without having to use a wordpress plugin?

Thanks,

Raul

 
> On 18 May 2015, at 10:44 pm, Thomas Steur <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Thx for the nice feedback!
> 
> Do you use the Piwik Wordpress plugin? If so, should this issue maybe created there?
> 
> Otherwise it would be nice to know more about what you have installed and how one can reproduce it.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/piwik/piwik/issues/7916#issuecomment-103204855>.
> 

—
I fix it in post !
Raul Arellano (VFX)
—————————————————————
Phone . +49 176 7834 2650
web . http://www.raularellano.ca <http://www.raularellano.ca/>
Linked in . http://de.linkedin.com/pub/raul-arellano/84/704/80/ <http://de.linkedin.com/pub/raul-arellano/84/704/80/>
---------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended solely
for the use of the individual or entity to whom they are addressed. If you have
received this email in error please notify the sender. This message contains
confidential information and is intended only for the individual named. If you
are not the named addressee you should not disseminate, distribute or copy this
email. Please notify the sender immediately by email if you have received this
email by mistake and delete this email from your system. If you are not the
intended recipient you are notified that disclosing, copying, distributing or
taking any action in reliance on the contents of this information is strictly
prohibited.

**Comment by tsteur** [comment]
Can you create an issue here? https://wordpress.org/support/plugin/wp-piwik It seems to be not Piwik related but feel free to reopen in case it is.

> Is there a way to have Piwik running without having to use a wordpress plugin?

You could log in to your Piwik UI and use only a simple plugin that allows you to track via Piwik or add the tracking code to your theme. I'm sure you will find something in the Forums http://forum.piwik.org/ or feel free to ask for support there. 
Cheers
