### ISSUE TITLE
After update to 2.13.1 not write activity

### ISSUE THREAD

**Issue by 12th** [piwik/piwik#7919]
Hello. 
After update piwik to 2.13.1, tracking stop write first entry on site from refferer which has params described in next screenshot. 
Maybe this bug because referrer has long url. 

Reloading the page and events no logging.

When click by any link on this first page, only then piwik start write activity. 

![piwik ok](https://cloud.githubusercontent.com/assets/1928475/7666233/ac96ffb8-fbe5-11e4-878a-d4a5ae486a31.png)

Please, help. How can write activity if first entry page of user from site like ok.ru

**Comment by tsteur** [comment]
I don't think the referrer is too long. The request returns a 204 response which looks like the request was recorded. Can you see any errors in the server log? How do you know it didn't track this user? Do you miss an entry somewhere? Are all other tracking requests working properly?

**Comment by mattab** [comment]
Hi @12th 
For more information you can also enable tracker debug logging: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker

Please send us more info and reopen issue if problem persists in 2.14.0

**Comment by mattab** [comment]
Actually the problem here is that `ok.ru` is marked as referrer spam in our referrer spam blacklist. I'll remove it from there.

**Comment by mattab** [comment]
fixed in https://github.com/piwik/referrer-spam-blacklist/pull/82
