### ISSUE TITLE
Thunderbird detection not working

### ISSUE THREAD

**Issue by Joey3000** [piwik/piwik#7921]
Detection of the Mozilla Thunderbird e-mail client (used e.g. for RSS/Atom feed reading) was introduced in https://github.com/piwik/piwik/issues/3252 and worked with Piwik 1.12. After updating from Piwik 1.12 straight to 2.13.0 (and later 2.13.1), Thunderbird is not recognized.
Note: The Piwik update was actually a complete re-installation, keeping the MySQL content.

Test steps:
1. Using an administrative account, log-in to Piwik. Go to "Administration" -> "Device detection".
2. Change the browser user agent to one of the following (e.g. in Firefox: by adding general.useragent.override parameter in about:config):
Mozilla/5.0 (Windows NT 6.0; rv:31.0) Gecko/20100101 Thunderbird/31.6.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Thunderbird/31.6.0
3. Reload the "Device detection" page

Expected test results:
1. Current browser user agent info is shown.
3. Similarly to the Firefox browser, Thunderbird is detected and displayed with its icon and version.

Actual test results:
3. Thunderbird is not recognized and "Unknown" (plugins/DevicesDetection/images/browsers/UNK.gif) is shown instead. Whereas country, OS and device type are recognized correctly.

Notes:
- The above is just a quick Thunderbird simulation. The actual use case involves tracking access to RSS/Atom feed articles using the Piwik image tracker, which shows the same behavior.
- Mozilla Thunderbird user agent string is similar to the one of the Mozilla Firefox web browser, so that their parsing rules should be similar, too.

PHP 5.5.22 on Apache on Debian.

**Comment by sgiehl** [comment]
Piwik is currently not able to record/track other clients than browsers.
PIMs, Feed Readers, mobile apps and others will be readded in #5413
