### ISSUE TITLE
Reusing a piwik database created a report that it had been updated to the same version

### ISSUE THREAD

**Issue by AndersBillLinden** [piwik/piwik#7924]
In the great welcome screen that will launch when I access `/piwik` the first time, I will be able to specify which database I want to use for piwik.

The database was successfully reused, however, I got a message saying this:

`The database was successfully updated from 2.14.0-b1 to 2.14.0-b1!`

I like the positiveness of that message actually, but there had been no update, since the version was the same.

This may be cosmetic, but to really be sure that piwik has not tampered with the data in any way, it would be better with a message like this:

`The database was successfully reused, version is still 2.14.0-b1!`

**Comment by mnapoli** [comment]
The "old" version number was actually retrieved *after* the update, so it was equal to the new version ;)

**Comment by AndersBillLinden** [comment]
:+1:
