### ISSUE TITLE
Can't open a file within piwik

### ISSUE THREAD

**Issue by myluis** [piwik/piwik#7925]
Hi Folks,

I have a file with some login details that I want to use to connect to an external database. But when I try to use the code below, I get some funny error messages. Can someone tell me what I am doing wrong inside piwik, please? Is it possible to connect to a file inside piwik? If yes, how do you normally do that, please?

I have this code that I want to use to connect to another file within my piwik plugin.

```php
if (!require_once("../../../test_config.php")) {echo "inc failed";}
$con = mysql_connect(DB_HOST_SSOS, DB_USER_SSOS, DB_PASSWORD_SSOS); 
if (!$con) { die('Sorry, could not connect: ' . mysql_error());}
$db_selected = mysql_select_db("ssos", $con);
if (!$db_selected) {die("It was not possible to use test_db : " . mysql_error());}
```

But when I run the code, I get this error message below.

PHP Fatal error:  require_once(): Failed opening required '../../../test_config.php' (include_path='/home/work/company/piwik/vendor/pear/pear_exception:/home/work/company/piwik/vendor/pear/console_getopt:/home/work/company/piwik/vendor/pear/pear-core-minimal/src:/home/work/company/piwik/vendor/pear/archive_tar:/home/work/company/piwik/vendor/phpseclib/phpseclib/phpseclib:/home/work/company/piwik/vendor/phpunit/php-text-template:/home/work/company/piwik/vendor/phpunit/php-timer:/home/work/company/piwik/vendor/phpunit/php-file-iterator:.:/usr/share/php:/usr/share/pear') in /home/work/company/piwik/plugins/TestPlugin/Reports/GetCityContributors.php on line 30

Your help will be appreciated please.

**Comment by tsteur** [comment]
You need to build the path to that file like this `PIWIK_INCLUDE_PATH . '/plugins/TestPlugin/test_config.php`. 

For further questions please ask in our plugins & platform forum http://forum.piwik.org/list.php?9

**Comment by myluis** [comment]
Thank you so much. You suggestion has solved my problem.
