### ISSUE TITLE
Step "Create tables" of new installation appears untranslated

### ISSUE THREAD

**Issue by PatchRanger** [piwik/piwik#7926]
## How to reproduce
Initialize a new installation of Piwik, follow the installation steps. On "Database setup" step, fill in the form with new table prefix in order to get the use-case of "tablesCreated".

## Expected result
The layout of the page and the message are fully translated to the current language.

## Real result
Everything from layout to appeared message (which is successful, sic) are in English, though all steps before and even after it are localized.

**Comment by sgiehl** [comment]
I can reproduce that. Not sure why the translations are not used even if they are available.

**Comment by PatchRanger** [comment]
After debugging a little, I've discovered that for that page `Translator`, returned by `StaticContainer`, has a private property `currentLanguage` set to `en`, though it's not the case for other pages.

**Comment by mnapoli** [comment]
For the record, PR WIP: #8022
