### ISSUE TITLE
Dashboard fails to load in Firefox with 'Adblock Plus' extension

### ISSUE THREAD

**Issue by joshhansen** [piwik/piwik#7928]
My site is running Piwik 2.13.1. Under Chrome (well, Chromium) 42 the dashboard loads fine, but under Firefox 36 (my preferred browser) I get the following error: 
```
ReferenceError: $ is not defined index.php:68:8
ReferenceError: $ is not defined index.php:739:0
ReferenceError: $ is not defined index.php:764:0
```
This indicates that jQuery has not loaded properly. Without this library, the dashboard is basically worthless.

Of course, I can get by with Chrome support only, but to fail to load under Firefox seems like a serious issue and I hope it could be addressed.

**Comment by mattab** [comment]
Hi @joshhansen that's surprising, can you reproduce this problem on demo.piwik.org as well?

**Comment by joshhansen** [comment]
The problem doesn't occur on the demo site. Can you help me understand why jQuery would fail to load when all HTTP requests are succeeding---but only in Firefox?

**Comment by mnapoli** [comment]
@joshhansen could you have a look in the "Network" tab of the development tools? It should help to debug. It might also be an extension that is installed on Firefox (e.g. an aggressive ad blocker?) that blocks some requests.

**Comment by joshhansen** [comment]
Strangely enough, Adblock Plus in Firefox seems to have been causing the problem. This is especially odd since I also use Adblock Plus in Chromium, but it doesn't seem to be causing problems there. Disabling ad blocking on my Piwik site seems to be sufficient to resolve the problem.

I wonder if anyone else can reproduce this problem? It's a common enough extension that it might be worth looking into why Piwik is triggering the ad blocker.

**Comment by mattab** [comment]
Good to know @joshhansen - thanks for the details.
 
we  should contact Adblock Plus to ask them to upgrade their rules so it does not break when viewing Piwik dashboard. Maybe you would like to contact the developers and report issue to them?

**Comment by hpvd** [comment]
For me this was working without any problems in the past.
About 1 month ago the problems started
for other details on this please see:
https://github.com/piwik/piwik/issues/8760

**Comment by tsteur** [comment]
We definitely need to try to detect adblocker and show a notification

**Comment by mattab** [comment]
Moving to 2.15.0 - if can't be done in time, we'll do it in 2.15.x

**Comment by mattab** [comment]
Actually we will do https://github.com/piwik/piwik/issues/5094 in 2.15.0 rather

**Comment by hpvd** [comment]
one should do this detection **really carefully**
There are lot's of methods out there which work with adding blacklisted words e.g. advertise to the website code the see if this is blocked.
Doing this here wood be like honey and we will have problems with many many other other tools/extension...

**Comment by hpvd** [comment]
I would suggest to understand **why piwik-backend is blocked**
- for website frontend with piwik script inside - it's clear
- but why are ther know problems with Piwik's backend?

**Comment by trendzetter** [comment]
Same issue with firefox and "ublock Origin" on 2.10.0.

**Comment by mattab** [comment]
Hello can you please test with latest piwik beta? it should now display a warning that adblock is used. please let us know if the warning works!

**Comment by mattab** [comment]
Re-open if the warning is not displayed for uBlock origin

**Comment by tsteur** [comment]
It is not directly related to uBlock origin but to the lists that are activated. Eg one needs to enable the EasyPrivacy list in any ad blocker and this will happen. I think by default it did not block anything.
