### ISSUE TITLE
Hide update Notification from Users

### ISSUE THREAD

**Issue by futureweb** [piwik/piwik#7930]
Admins should be able to hide the "Update Notification" from Users. Update Notifications will make normal Users a bit queasy ;-)
Boards: http://forum.piwik.org/read.php?2,126434,126728#msg-126728

Andreas Schnederle-Wagner

**Comment by peterbo** [comment]
I think a config setting to set update_notification_superuser_only = 1 (or similar) would be enough. Or should it be more sophisticated?
