### ISSUE TITLE
Revenue from campaigns is not getting

### ISSUE THREAD

**Issue by shogunjames** [piwik/piwik#7938]
Hi Mattab,

Thank you for your reply,

I have attached a screenshot from my piwik insttalation where I am checking the campaign status.

I am using a magento site for ecommerce activities , and we are sending newlstters to our customers.

I need to get the revenue I got from each newsletter , when they came to the site by clicking the urls in the newsletter and when they purchase a product.

I hope it is clear for you.

Also I have enabled ecommerce for my magento site and installed piwik ecommerce extension in my site.  This is the piwik code which is on the source code of the success page after the order is placed.

//<![CDATA[

var pkBaseURL = (("https:" == document.location.protocol) ? "piwiksiteurl" : "piwikurl");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));

try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);

piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
//]]>

<noscript><p><img src="{piwiksiteurl}?idsite=1" style="border:0" alt="" /></p></noscript>

This is the screenshot :

![piwik](https://cloud.githubusercontent.com/assets/11349118/7701536/bcf7934c-fe45-11e4-8bd9-f2d1ecd9dfc9.png)

My current piwik version is 2.1.0 .  Should I need to upgrade this?  If I upgrade will I get the total revenue from each newsletter I send out?

**Comment by mattab** [comment]
> My current piwik version is 2.1.0 . Should I need to upgrade this? If I upgrade will I get the total revenue from each newsletter I send out?

Yes, please upgrade. there have been more than 10 major versions since yours, this bug should be fixed after you upgrade

**Comment by shogunjames** [comment]
Hi 

I will update piwik and will let you know.

Thanks
