### ISSUE TITLE
Map labels truncated for countries with no visits

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7940]
![image](https://cloud.githubusercontent.com/assets/33569/7712961/4db02dbc-fe29-11e4-977d-36539c1edaf3.png)

Related to #6821?

**Comment by tsteur** [comment]
That works for me, which Piwik version, browser + browser version are you using?

**Comment by dandv** [comment]
Piwik 2.13.1 in Chrome 42.0.2311.152 m on Windows.

**Comment by sgiehl** [comment]
I'm able to reproduce that in chrome on demo.piwik.org for countries not having any visits. Seems to be a problem with the calculation of the tooltip width
