### ISSUE TITLE
Incorrect screen resolution detected for devices with device pixel ratio > 1

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7941]
Possible follow-up to #3962. I'm a new Piwik user and had disabled the UserSettings plugin.

![image](https://cloud.githubusercontent.com/assets/33569/7713084/3eccaa04-fe2a-11e4-920a-ad40bcaeccbb.png)

My device is a Samsung Galaxy S5 and the actual resolution is 1080 x 1920.

**Comment by tsteur** [comment]
Which Piwik version are you using? The UserSettings plugin is "outdated" and replaced by different plugins such as "Resolution", "DevicesDetection" etc. Which Piwik version are you using? 

I presume you are tracking a website and not an Android App?

**Comment by dandv** [comment]
I'm a new user so the latest Piwik, 2.13.1. I'm tracking http://idorecall.com.

UserSettings is inactive.
DevicesDetection and Resolution are active.

**Comment by tsteur** [comment]
Thx! Just one more question from my site (@sgiehl might have some more questions): Does it maybe say which device etc was detected?

**Comment by dandv** [comment]
The screenshot shows "Android 4.4". Should I look elsewhere?

**Comment by sgiehl** [comment]
That might be a general problem with devices having a device pixel ratio > 1. Just had a look with my Nexus 5. Piwik reports 360x640, aswell. The Nexus 5 has a device pixel ratio of 3. We already have a special handling for macs, guess that should be enhanced to be valid for mobile devices, aswell. See https://github.com/piwik/piwik/blob/master/js/piwik.js#L4025-L4059
