### ISSUE TITLE
Notification messages have too low contrast after redesign

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7943]
When displaying a Notification of type Warning, the color used does not have high enough contrast. This results in a hard to read notification text requiring eyes to focus more than normal. If using Piwik outside with the sun, it may be impossible to read the message.

Screenshot:

![warning color has too low contrast](https://cloud.githubusercontent.com/assets/466765/7719281/f83eae0e-ff12-11e4-861c-ef5f3cd68118.png)

Follows up #7874

**Comment by mattab** [comment]
Similarly the "Info notification" has a too low contrast... which makes labels hard to read, see for example:

![no contrast](https://cloud.githubusercontent.com/assets/466765/7953166/5c72d028-0a15-11e5-8790-a1d644131107.png)

**Comment by mnapoli** [comment]
PR: #8037
