### ISSUE TITLE
Ecommerce metrics not aggregated

### ISSUE THREAD

**Issue by Guite** [piwik/piwik#7945]
Since the 30th of April (Piwik 2.13.0) no ecommerce metrics are aggregated anymore (like amount of orders, amount left in cart, etc.).
I first thought it could be related to #6986 but the config values mentioned there make no difference. Even with browser-based archiving enabled all ecommerce values keep 0.

Of course there is still data available which is also shown in the ecommerce log tab.

Any idea how to track this down?

**Comment by mattab** [comment]
Hi @Guite 

can you please upgrade to 2.13.1 first?

if you still have the issue could you post here a screenshot? thanks

**Comment by Guite** [comment]
I am using 2.13.1 already. Just wanted to mention that the problem seems to started with 2.13.0.

Here is a screen:

![screen_ecommerce_metrics](https://cloud.githubusercontent.com/assets/277531/7720011/4b055160-fec8-11e4-9f1c-009fa0ef000b.jpg)

**Comment by mattab** [comment]
Hi @Guite 

If possible for you, can you try upgrade to 2.14.0-b1 ? the beta version works well and fixes an issue in Ecommerce which maybe fix your problem. if it does not fix it, we will do our best to help you and resolve this issue before next release

**Comment by Guite** [comment]
Hi @mattab 

I successfully upgraded to 2.14.0-b1. On the first glance nothing has changed. Can I somehow remove aggregation data for the last four weeks in the database to let the archive script recreate them?

**Comment by tsteur** [comment]
I can't reproduce it and have no idea how to track it down. @Guite do you still have any config settings left from #6986?

Re removing invalid aggregation data you could maybe try to delete the archives for one or two days and re-archive. Here's a FAQ how to do it: http://piwik.org/faq/how-to/faq_155/   You can specify multiple dates comma separated, but would first try it only for one

**Comment by Guite** [comment]
Would it help if I'd provide access credentials to `hello at piwik.org` so that you can check my installation?

**Comment by tsteur** [comment]
Yes, that would help

**Comment by Guite** [comment]
Any update yet? I sent the credentials at the 9th of June, did you receive them?

**Comment by tsteur** [comment]
I'll have a look now. Sorry the mail went into the spam folder

**Comment by tsteur** [comment]
The problem seems to be actually not in Piwik itself. When tracking ecommerce items it sends a wrong JSON and it cannot track the items. 

For example if you go to the actual website of id 34 and execute the following in the console

```
JSON.stringify([1, "test"]);
```
we get this output:

```
[1, \"test\"]
```

But expected output is:
```
[1,"test"]
```

We tried to find what causes this but couldn't 100% identify it. We presume it is caused by prototype.js library. Maybe you have an idea what causes this? Can you let us know so we can create an FAQ entry for this?

**Comment by Guite** [comment]
Hi @tsteur 
thanks for elaborating. I tested that on a few sites and doubt that prototype.js is causing this problem, because it is used on other sites where the test works successfully. I am going to try identifying where this comes from and report back afterwards.

**Comment by Guite** [comment]
Intermediate results: it is indeed related to prototype.js.
I dumped a page to a local test file and iteratively removed stuff. I can reproduce the problem with an almost empty file where only this prototype version is loaded in version 1.6.1. On another site I had briefly tested version 1.7.1 is used where everything works fine. Further investigating...

**Comment by Guite** [comment]
Confirmed: updated prototype to latest version 1.7.2 and it works.
