### ISSUE TITLE
Invalid URL fragment encoding

### ISSUE THREAD

**Issue by gaydenko** [piwik/piwik#7961]
Hi!

A link attached to a page-view action is invalid in link fragment encoding part. In particular, quotes are escaped. for example:
```
http://6000.ru/#!housings/filter?filter={&quot;place&quot;:{&quot;place&quot;:&quot;0c5b2444-70a0-4932-980c-b4dc0d3f02b5&quot;}}
```
So, instead of URL-encoding we have XML-escaping :)
The last stable Piwik version is in use.

**Comment by mattab** [comment]
Hi @gaydenko 

Thanks for the report. 

 * I can reproduce and can see the `&quot;` in the Visitor Log. 
 * The URL looks good however in the Actions > Page URLs report.

The bug is only in Visitor Log. Can you please confirm?

**Comment by gaydenko** [comment]
@mattab, hi!

Yes, you are right at both cases - Visitor log is the only place I have met the issue.
