### ISSUE TITLE
Add Hook to OptOut Action (CustomOptOut)

### ISSUE THREAD

**Issue by Zeichen32** [piwik/piwik#7962]
Currently i need to copy the whole "OptOut Action" and logic to change the "OptOut View". 
https://github.com/Zeichen32/PiwikCustomOptOut/blob/master/Controller.php#L108

I think, it would be a much cleaner way if we can trigger a event just befor the view is render to change the "OptOut View".
https://github.com/piwik/piwik/blob/master/plugins/CoreAdminHome/Controller.php#L362

If it is okay for you, I would like to work on a PR.

**Comment by mnapoli** [comment]
Out of curiosity what are you trying to achieve with your alternate view?

**Comment by Zeichen32** [comment]
The CustomOptOut Plugin allows you to style your optout iframe with custom css per site. To implement this feature i need edit the optout template.

**Comment by mnapoli** [comment]
Mmh right I see, it makes sense then, maybe others will have feedback on the idea?

**Comment by Zeichen32** [comment]
I'm open for any suggestions and ideas.

**Comment by mattab** [comment]
Hi @Zeichen32  let's discuss in your PR #7979
