### ISSUE TITLE
Add a divider after the Visitors in Real-time header

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7965]
I've been using Piwik for a few days now, and whenever I look at the *Visitors in Real-time* widget, I'm confused by the header of that table:

![image](https://cloud.githubusercontent.com/assets/33569/7763885/a76ed82e-fffc-11e4-90c5-12ed984e8b07.png)

The problem is that the first visitor has the same background as the header of the table, which makes me associate the two ("in the last 30 minutes I had the Thursday visitor... what?").

**Comment by tsteur** [comment]
FYI: Will be fixed with #7090
