### ISSUE TITLE
Goal tracking documentation needs updates

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7966]
1. Broken link - http://piwik.org/docs/tracking-goals-web-analytics/ links at the end to http://developer.piwik.org/api-reference/tracking-javascript#manually-trigger-a-conversion-for-a-goal but the anchor doesn't exist on that page.

2. What is the type of the first parameter to trackGoal? Apparently it's a numeric ID (are they simply consecutive numbers, 0-based or 1-based?), but how do those IDs map onto the [goals created in the UI](http://piwik.org/docs/tracking-goals-web-analytics/#create-a-goal)? If I use goals based on events, is it sufficient to call `trackEvent()`, or do I need to also call `trackGoal()`?

3. The [goals doc page](http://piwik.org/docs/tracking-goals-web-analytics/) reads,
> These define how the Goal can be converted: matching a URL, downloads a specific file, clicks on an external link,  or Goal manually triggered using the trackGoal() JavaScript function for specific user actions

  That should also include event tracking, which is missing from the screenshot.

**Comment by dandv** [comment]
Also, what is the type of the first parameter to trackGoal? Apparently it's a numeric ID, but how do those IDs map onto the [goals created in the UI](http://piwik.org/docs/tracking-goals-web-analytics/#create-a-goal)?

**Comment by mattab** [comment]
Hi @dandv thanks for the reports.

> Apparently it's a numeric ID (are they simply consecutive numbers, 0-based or 1-based?), but how do those IDs map onto the goals created in the UI? 

Click on Goals > Manage Goals. The table has a column "Id" which is the Id goal.
They are 1-based.

> If I use goals based on events, is it sufficient to call trackEvent(), or do I need to also call trackGoal()?

It's sufficient to call `trackEvent` which will record a Goal conversion

**Comment by mattab** [comment]
> Broken link - http://piwik.org/docs/tracking-goals-web-analytics/ links at the end to http://developer.piwik.org/api-reference/tracking-javascript#manually-trigger-a-conversion-for-a-goal but the anchor doesn't exist on that page.

Thanks I've fixed the links to JS Tracking guide in 10 user guides and 4 FAQs, to point to the new URL and correct hash tags
