### ISSUE TITLE
Quotes in goal names are over-escaped

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7969]
I created a goal `Click "Let me in!"` and got this:

![image](https://cloud.githubusercontent.com/assets/33569/7766950/448dc1f8-0023-11e5-98a2-b776c5b0c2ce.png)

**Comment by mattab** [comment]
Hi @dandv 
Thanks for letting us know about this issue.

**Comment by diosmosis** [comment]
Caused very indirectly by https://github.com/piwik/piwik/blob/master/plugins/Goals/Controller.php#L77
