### ISSUE TITLE
Make the Visitors Log default to the *latest* visits

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7971]
When I go to the Visitors Log, for some reason the display is from yesterday. This confused me enough that I posted on the forums:

http://forum.piwik.org/read.php?2,126894

**Comment by dandv** [comment]
UPDATE: turns out this is a setting, which by default was Yesterday. Maybe the date should be Today?

![image](https://cloud.githubusercontent.com/assets/33569/7783198/e4307de8-00ed-11e5-8cfb-053ced233c1f.png)

**Comment by tsteur** [comment]
It's yesterday by default as there might be eg no data for the current day yet (if browser archiving is disabled) and we believe most people want to see the data of the previous day by default. Eg it is hard to judge data of today as it shows not "complete" data for that day.
