### ISSUE TITLE
Visitor profile picture doc uses old screenshots

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#7973]
The screenshots with a paperclip at http://piwik.org/docs/user-profile/#feature-overview seem to no longer reflect the current UI.

BTW, is the visitor profile picture a placeholder, perhaps for later integration with FullContact, Rapporto, Ark or the like? I didn't see anything in the docs about changing the visitor profile pic, or adding visitor notes.

**Comment by sgiehl** [comment]
The profile picture can be set using a plugin. See this plugin for example: https://github.com/alnoorp/GrabGravatar

**Comment by mattab** [comment]
Screnshots need to be updated site-wide - we have some tickets already eg #7106 #7269  but we should really update them all since they are _all_ outdated...
