### ISSUE TITLE
No way to get sites without group using the reporting API

### ISSUE THREAD

**Issue by mrjoops** [piwik/piwik#7975]
There is no way to retrieve sites without group using the reporting API method _SitesManager.getSitesFromGroup_.
I tried providing an empty parameter or an empty string as a parameter (single and double-quoted)
I get the error _Please specify a value for 'group'._ or an emty array.

**Comment by tsteur** [comment]
You could write a plugin providing your own API. If you're familiar with PHP it would be quite easy. See eg http://developer.piwik.org/guides/expose-api-methods

**Comment by mrjoops** [comment]
Actually when I call _SitesManager.getSitesGroups_, I get the groups AND and an empty string, so I expect to be able to query it like any other group.
There's no reason to require a value for group.
It's a bug, not a feature !

 I'd love writing a plugin but I'm involved and busy in some other Piwik-related projects, and it's not the point, since it's a bug ;-)

**Comment by tsteur** [comment]
That's right, it is a bug or a missing feature.

I'm recommending a plugin if you need it soon as it might not have a priority and might take a while until it is actually developed.
