### ISSUE TITLE
Increasing the default custom variables slots without access to SSH or command line

### ISSUE THREAD

**Issue by myluis** [piwik/piwik#7982]
Hello,

I would like to increase the default custom variables values from 5 to 25 so that I can have enough to use for both 'page' and 'visits' as I apply segmentation to my analytic report work.

I read somewhere that to do that you would need to be connected to the server hosting piwik through ssh.
"First you need to be able to connect to the server running Piwik over SSH, so you can type commands to the Piwik console. To increase the custom variables SLOTS from 5 to 10, type in the terminal:" (http://piwik.org/faq/how-to/faq_17931/)

My question now, is this. I am using Windows and I normally connect to my piwik application on the server by uploading file using FTP client. So, how do I increase the custom variables without using the method above? Is there any other way that is possible to increase it without the command line , please?

Your suggestions will be of great help.
Thanks

**Comment by tsteur** [comment]
There's not really a way that we would recommend. Maybe you can log in somewhere that allows you to execute a command?

**Comment by myluis** [comment]
OK. Thanks for your response and suggestion.
