### ISSUE TITLE
Provider submenu label may appear untranslated (Provider_SubmenuLocationsProvider)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7985]
This bug can be seen on demo-log-analytics at: http://demo-log-analytics.piwik.org/
Hover on "Visitors" menu and notice the submenu appears un-translated:

![menu untranslated](https://cloud.githubusercontent.com/assets/466765/7789943/e9a09f3a-02c6-11e5-884b-b2472867356c.png)

This issue does not occur on the other demo.piwik.org or in most other Piwik setups. Only some Piwik are affected.

**Comment by mattab** [comment]
If you have this issue the solution is to delete the file `piwik/plugins/Provider/Menu.php`

The files should have been deleted automatically during the upgrade. Clearly sometimes deleting files is not working. Created separate issue:  During Upgrade, deleting outdated files may not work and fail silently #7986

**Comment by mattab** [comment]
Will be fixed in the future for all similar bugs in #7986 

If you experience this issue, our workaround is: delete the file `piwik/plugins/Provider/Menu.php`

**Comment by codifex** [comment]
When deleting the file `piwik/plugins/Provider/Menu.php` to fix the menu entry Piwik shows the error message "No entry or class found for 'Piwik\Plugins\Provider\Menu'" and is inaccessible. Any ideas on how to fix this are welcome.

**Comment by sgiehl** [comment]
Try to clear tmp folder within Piwik

**Comment by codifex** [comment]
Thank you, this fixed the problem.
