### ISSUE TITLE
Scheduled report name is double encoded 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7987]
- Got: scheduled report name is double encoded within the scheduled report `&quot;at a glance&quot;`

![report name double encoded](https://cloud.githubusercontent.com/assets/466765/7790253/1f0ab044-02d5-11e5-8927-45a60998947c.png)
- Expected: scheduled report name should not be double encoded in both PDF and HTML scheduled reports.

**Comment by diosmosis** [comment]
Issue is that API/Request.php sanitizes the `$description` parameter before it is stored in the DB (via `UrlHelper::getArrayFromQueryString()`), and twig will escape again. A quick fix would be to not escape in the template, but this would make the current strategy more entrenched. Still thinking about what the best fix is.

**Comment by diosmosis** [comment]
I have a solution that will be a start for https://github.com/piwik/piwik/issues/4231.

**Comment by mnapoli** [comment]
Added to the (long) list in #6714. By the way @diosmosis do you think #6714 duplicates #4231? (e.g. same goals -> move to sanitizing on output) I could move information in the older issue if that's the case.

**Comment by diosmosis** [comment]
Seems like there's a lot of overlap; The newer one has more information, a more definitive answer to the approach to take and you're obviously maintaining the list of stuff to do, so we could keep that one. We just need one in the 3.0 milestone I think.

**Comment by mnapoli** [comment]
Yours has more history, I've merged #6714 into #4231 with the information.

**Comment by SimonWaters** [comment]
Noted during testing this is still present in 3.0.0-rc3
