### ISSUE TITLE
Metrics for Referrer Type: Websites - xml empty data

### ISSUE THREAD

**Issue by wasek2611** [piwik/piwik#7993]
Go to referrers -> all referrers -> open row  evolution -> export dataset in other format -> xml 
xml is without data (all format, not just xml)

Bug xml in demo -> 

http://demo.piwik.org/index.php?module=API&method=Referrers.getReferrerType&format=XML&idSite=7&period=day&date=2015-04-25,2015-05-24&label=&date=2015-04-25%2C2015-05-24&filter_limit=false&disable_queued_filters=1&format_metrics=1&expanded=1&label=Str%25C3%25A1nky&token_auth=anonymous&filter_limit=30

**Comment by mattab** [comment]
Hi @wasek2611 thanks for the report. this issue was reported just couple days ago: #7983
