### ISSUE TITLE
Wrong Location Entry

### ISSUE THREAD

**Issue by navindransgk** [piwik/piwik#7999]
Hi,
We are using Piwik for Data Analysis, we have our website hosted in ZettaHost, we track the analysis using, Log Action, Log Visit, Log Link Visit Action tables in mysql in Piwik cloud, we found that the entry for country is showing as Hongkong. We are accesing the url from Chennai, Tamil Nadu, India

**Comment by tsteur** [comment]
Please check out http://piwik.org/docs/geo-locate/ . Also you probably have "Anonymize IP" enabled. Feel free to reopen if this does not solve your problem.
