### ISSUE TITLE
Cron reports: Exception in thread Thread-1 (most likely raised during interpreter shutdown)

### ISSUE THREAD

**Issue by myfirstnameispaul** [piwik/piwik#8003]
I have been getting the following in my Cron reports for a very long time now:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
>   File "/usr/lib/python2.7/threading.py", line 504, in run
>   File ".../piwik/misc/log-analytics/import_logs.py", line 1472, in _run_bulk
>   File "/usr/lib/python2.7/Queue.py", line 168, in get
>   File "/usr/lib/python2.7/threading.py", line 236, in wait
> \<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Ubuntu 12.04.5 server x64 running PHP 5.5.25, nginx 1.8.0, MariaDB 5.5.43 and Piwik 2.13.1 is installed.

**Comment by mattab** [comment]
Hi @myfirstnameispaul 
Log Analytics errors are tracked in this issue tracker: https://github.com/piwik/piwik-log-analytics/issues/74
can you please create your bug report there instead? thanks!
