### ISSUE TITLE
Error parsing less file when using &:extend

### ISSUE THREAD

**Issue by marius1512** [piwik/piwik#8004]
It seems that lessphp is not parsing well less files. If I use &:extend i get parser error. Is it possible to use another parser or solve this problem please.

Thanks

**Comment by mnapoli** [comment]
This issue could be merged with #7654, I'll move your comment there.

By the way this extend() problem looks like it's reported a lot in lessphp ([plenty of issues about it](https://github.com/leafo/lessphp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+extend), the project doesn't look maintained a lot…), it's indeed a real problem.
