### ISSUE TITLE
Verify that WhiteLabel plugin still work as expected after all redesigns (before releasing Piwik 2.14.0)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8006]
The goal of this issue is that, before we release 2.14.0 release, we must check that the [WhiteLabel plugin](https://piwik.pro/plugins/white-label) screenshot tests (and others) are passing and that it has not regressed. 

Why is this important?

We are making many design improvements in this release 2.14.0. As part of these projects we are changing a lot of HTML, CSS and some JavaScript. Our UI tests let us know that we have not regressed anything in core Piwik which is great. But we need to ensure that White Label, a premium plugin, works still after we changed all this CSS and HTML.

cc @mnapoli

**Comment by mnapoli** [comment]
:+1: FYI working currently on a UI test that activates another theme (to have that covered).

**Comment by mnapoli** [comment]
UI test for themes: #8015

**Comment by mnapoli** [comment]
For the record I have run the UI tests locally in the #8015 branch and they fail only because of redesigned elements, but the colors and overridden styles are taken into account! So it should be good (but let's check again before 2.14 release).

**Comment by mattab** [comment]
a new WhiteLabel plugin release was done (0.8.1) and it looks good with 2.14.0 :+1:
