### ISSUE TITLE
PHP Tracker Namespace Branch

### ISSUE THREAD

**Issue by claytondaley** [piwik/piwik#8009]
Relevant details already included in piwik/piwik-php-tracker#8.  I'm not clear if this issue hasn't gotten attention because it's low priority or because it's on a related (less trafficked) repo.  I'm cross-listing here in case it's the latter.

P.S. I assume most of the related repos have this problem. Perhaps we should discuss automatically creating an issue on this (main) repo for each issue on a related repo.

**Comment by mnapoli** [comment]
You are right that 3rd party repositories get less attention. I have answered in the original issue.

**Comment by mattab** [comment]
>>  Perhaps we should discuss automatically creating an issue on this (main) repo for each issue on a related repo.
> You are right that 3rd party repositories get less attention. 

fyi some/most of this challenge will be addressed in https://github.com/piwik/piwik/issues/7636

**Comment by mattab** [comment]
We don't need to create duplicate issues in piwik/piwik - instead we will consider other repositories as "first class citizen" but we are still working on this (will post progress in #7636)
