### ISSUE TITLE
Visitors in Real-Time widget: day of week full name shown instead of 3-letter abbreviation

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#8011]
Hi, after upgrading to 2.13.1 I noticed that full name of day is shown instead the usual short version. It looks bad for me, breaking the lines in the middle of icons:

![2015-05-27_200010](https://cloud.githubusercontent.com/assets/5383059/7843610/fbe15e24-04aa-11e5-862e-f61a50f8b1d7.png)

**Comment by mattab** [comment]
Thanks for report @dev-101 
the design for Real time widget was improved in 2.14.0 (which fixes this issue since now the datetime is on a new line) and we will generally improve the date/time formats in Piwik in: #8282
