### ISSUE TITLE
Remove magic quote hacks before 3.0 is released

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8012]
As title, when the minimum required PHP version is increased to 5.4 since magic quotes does not exist there.

**Comment by tsteur** [comment]
I think pretty much only https://github.com/piwik/piwik/blob/3.0/core/bootstrap.php#L20 is left. https://github.com/piwik/piwik/blob/2.16.0/core/Common.php#L280 and other places were already removed

**Comment by tsteur** [comment]
this is done
