### ISSUE TITLE
warning: /var/www/html/mypiwik.stat.com/html/core/Url.php(279) and other warnings

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#8013]
Hello!
I have a next trouble:
warning: /var/www/html/mypiwik.stat.com/html/core/Url.php(279): Notice - Undefined property: Piwik\Config::$General - Piwik 2.13.1
warning: /var/www/html/mypiwik.stat.com/html/core/Url.php(345): Notice - Undefined property: Piwik\Config::$General - Piwik 2.13.1
warning: /var/www/html/mypiwik.stat.com/html/core/SettingsPiwik.php(215): Warning - array_key_exists() expects parametr 2 to be array, null given - Piwik 2.13.1
warning: /var/www/html/mypiwik.stat.com/html/plugins/Installation.php(54): Notice - Undefined property: Piwik\Config::$General - Piwik 2.13.1
warning: /var/www/html/mypiwik.stat.com/html/core/SettingsPiwik.php(212): Notice - Undefined property: Piwik\Config::$General - Piwik 2.13.1
warning: /var/www/html/mypiwik.stat.com/html/core/IP.php(72): Notice - Undefined property: Piwik\Config::$General - Piwik 2.13.1

It is happend when i refresh page "all project"

What is it?

**Comment by mattab** [comment]
Hi @simpleuser99 
Can you re-upload the file `config/global.ini.php`? 

If this does not fix the issue please leave a comment
