### ISSUE TITLE
Installation Error Barnes_&_Noble.ico

### ISSUE THREAD

**Issue by svenlewerentz** [piwik/piwik#8029]
Hello, 
I wanted to install Piwik on a Webspace hosted by "Hetzner South Africa". During the installation I get an error that a file called "/plugins/DevicesDetection/images/brand/Barnes_&_Noble.ico" is missing. 

It is true, the file is missing, because I was not able to copy the file on the server. The server does not accept filenames containing a "&". 
Maybe it would be good not to use special characters like "&" in filenames. 

Regards 
Sven

**Comment by sgiehl** [comment]
First time that issue occurs, but as it should be easy to solve, I'd suggest do replace special chars for filenames with _ or -.
Will have a look at that...
