### ISSUE TITLE
UI tests: PhantomJS kills itself when compared screenshot is identical

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8034]
Eg I execute the tests like this: `./console tests:run-ui --persist-fixture-data --keep-symlinks ActionsDataTable`

Then I get the following output:

```
  ActionsDataTable
    Setting up fixture UITestFixture...
    Using existing database _UITestFixture.
    
    *******************************
      Fixture successfully setup!  
    *******************************
    
    
    ✓ should load correctly (15255ms)
Killed
```

When I remove all the expected screenshots of `ActionsDataTable` and the tests run fine. Is maybe else experiencing this as well? 

Under `kern.log` I get the following output:

```
Jun  2 22:08:41 piwik-trusty64 kernel: [35946.061768] Out of memory: Kill process 19650 (phantomjs) score 224 or sacrifice child
Jun  2 22:08:41 piwik-trusty64 kernel: [35946.062582] Killed process 19650 (phantomjs) total-vm:1728768kB, anon-rss:228096kB, file-rss:0kB
```

I'd attach some more logs but haven't found anything under `/tmp` or so. Not sure where to look! Maybe it's just that our current method of comparing images is too memory hungry?

My VM has 1GB RAM, PhantomJS version is 1.9.8, Linux piwik-trusty64 3.13.0-37-generic

**Comment by mattab** [comment]
> Maybe it's just that our current method of comparing images is too memory hungry?

We fixed this recently, so I'll mark this issue as closed as hopefully it is. feel free to reopen @tsteur if you still experience issue (or anyone else!)

**Comment by mattab** [comment]
The image comparison is now using imagick instead of resemble which we changed to be much more memory efficient, this was done in: https://github.com/piwik/piwik/pull/8163/files
