### ISSUE TITLE
Custom Date range bug on 2.8 Piwik version

### ISSUE THREAD

**Issue by magime0517** [piwik/piwik#8043]
I'm currently having issues with Piwik's custom date range functionality. 
I'm trying to look at the page URLs for the date range of Jan 01 2015- June 03-2015. After entering this date range I get about 108 Page urls in the results page. However, the page url number should be much higher, this looks incomplete. 
I know for a fact that is incomplete because when I search for page urls for only one day, say March 4th, I am able to see page urls that are NOT included in the results page for the date range of Jan 01 2015- June 03-2015.

Will this issue be solved on a newer Piwik version? or is there a fix for this issue in 2.8?

Please Advise.
Thanks,
Giselle

**Comment by mattab** [comment]
Hi @magime0517 we only support the latest Piwik version. Hundreds of bugs  were fixed since 2.8 and this issue should be already fixed.

**Comment by magime0517** [comment]
Matthieu,

Could you specify in which version of Piwik this issue is fixed?
I’d like to be certain before I upgrade.

Thanks,
Maria
