### ISSUE TITLE
Show the "Hiring Software Engineer" message + link to job ad in the browser console

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8044]
By adding the link to the job ad in the browser console, we will reach plugin developers, developers that use piwik, at least at some point we reach them. 

Some projects also show it inside an HTML comment but think rather when they look for frontend people meaning HTML/CSS.

(Idea suggested by @tsteur )

Do you maybe have suggestion for such a message in browser console?

**Comment by mattab** [comment]
Proposal:

```
Hi there, Nice to meet you. Piwik is the leading free & open source analytics platform for Web and Mobile. 

You like to look under the hood? Why not help us build the platform? 
We are hiring a Senior Software Engineer:  http://bit.ly/1HO55hx (full stack, remote based)

Visit http://piwik.org/jobs to learn about our current job openings.
Visit https://piwik.org/get-involved/ for more ways to get involved and help support Piwik.
```

Inspiration: http://consolemessage.com/page/2

**Comment by mnapoli** [comment]
I'm not entirely convinced honestly. We strive to make writing plugins extremely easy so that it's open to all levels of programming. Furthermore the job description has already been very visible a lot in Piwik's ecosystem, I doubt such very limited thing will do much. However of course it doesn't hurt (as long as it's disabled in development) so I don't really care.

**Comment by mgazdzik** [comment]
I have also some doubts regarding this idea:
- Piwik is often used as corporate/enterprise class software, sometimes in intranet env, sometimes it's whitelabeled to remove all "Piwik" mentions... I think it may not be warmly welcome to put Piwik's job ads in other company work environment,
- it may not be very professional/friendly to fill console with such info after each UI request,
- such info would be thightly coupled to this release, so even after 6 months this ad would be displayed, when possibly this job offer would be invalid
- it could be simply irritating 'information noise' after working with this Piwik version in long term (for ex. 6 months day after day)

**Comment by gaumondp** [comment]
What @mgazdzik said !

**Comment by sgiehl** [comment]
I agree with @mgazdzik 
We might add general information and links that are always valid, but no ads with "short" lifetime.

To reach plugin developers with job ads maybe we could add such stuff to the emails sent when updating or adding a plugin to the marketplace

**Comment by tsteur** [comment]
Good points, didn't think of that when it came randomly to my mind. Not sure if I would add it to plugin developers either. I reckon we have to be quite sensitive here and if we're somewhere not sure rather not do it

**Comment by tsteur** [comment]
Closing it for now. Hope that's ok with everyone. Just reopen or comment otherwise
