### ISSUE TITLE
import_logs.py look for https host if http host fails

### ISSUE THREAD

**Issue by rhurling** [piwik/piwik#8051]
Hi,

I currently have the problem that I want to auto-import my log files which didn't work, because the import_logs.py `DynamicResolver` class only looks for 'http://' + host in Piwik, but all my Sites are https only and created in piwik accordingly.

The following change to the `_get_site_id_from_hit_host` function would allow the script to look for a https host if no http host is found.

```python
    def _get_site_id_from_hit_host(self, hit):
        main_url = 'http://' + hit.host
        res = piwik.call_api(
            'SitesManager.getSitesIdFromSiteUrl',
            url=main_url,
        )
        if res:
            return res

        main_url = 'https://' + hit.host
        return piwik.call_api(
            'SitesManager.getSitesIdFromSiteUrl',
            url=main_url,
        )
```

**Comment by mattab** [comment]
Hi @rhurling thanks for feedback. The issue tracker for Log Analytics is at: https://github.com/piwik/piwik-log-analytics

do you mind creating your issue there, and close this one? thanks

**Comment by rhurling** [comment]
Ah, I didn't know it had a separate repo.
I will reopen the Issue there.
Thank you.
