### ISSUE TITLE
Problems with Firefox

### ISSUE THREAD

**Issue by BOUDALIZ** [piwik/piwik#8053]
Tracking is not working for me with Firefox, however it works well with IE and Chrome

**Comment by sgiehl** [comment]
Do you have an adblocker installed in Firefox?

**Comment by BOUDALIZ** [comment]
Yes, I disabled it and Piwik works well
Thanks a lot !

2015-06-07 9:54 GMT+01:00 Stefan Giehl <notifications@github.com>:

**Comment by BOUDALIZ** [comment]
Yes, I disabled it and Piwik works well
Thanks a lot !

**Comment by BOUDALIZ** [comment]
Please, how can i know the ID of a real time visitor to deduct if he's a
returning visitor or not?

Thanks a lot !!

2015-06-07 9:59 GMT+01:00 Zeineb Boudali <boudalizeineb@gmail.com>:

**Comment by ilmg-22** [comment]
bonjour,
Egalement sous firefox, dans les paramètres  "about:preferences#privacy", décocher  le pistage (Indiquer aux sites que je ne souhaite pas être pisté)

Hi,
Also, on Firefox, in about:preferences#privacy, uncheck checkbox "Tracking"  (Tell sites that i do not want to be tracked)

:-)

Ilmg
