### ISSUE TITLE
userId match type should allow =@

### ISSUE THREAD

**Issue by LauraHornbake** [piwik/piwik#8062]
Currently userId match type is restricted to ==, ::NOT_NULL, ::NULL, !=.  This creates the following problem:

I am working on creating segments for users on an intranet and have used the users' emails set as userId. I want to create a segment that matches the domain end of that email/userId. for example: 

With userIds like this: 
bob@department1.com 
alice@department2.com 

I want to have segments like this: 
"Department 1" segment: userId =@ department1.com 
"Department 2" segment: userId =@ department2.com 

but I cannot, I get the error: 
<error message="The specified segment is invalid: Invalid Segment match type: try using 'userId' segment with one of the following match types: ==, ::NOT_NULL, ::NULL, !=."/>

**Comment by mattab** [comment]
Thanks for suggestion. After #6954 we can revert this commit: https://github.com/piwik/piwik/commit/252798d2d742cae998a1f42f50a5ba37c98069df (removing the system test also)
