### ISSUE TITLE
ColumnNames are not translated.

### ISSUE THREAD

**Issue by noasa999** [piwik/piwik#8064]
Hi,
I have problem. 

Use API Actions.getPageUrls. format CSV or TSV. 

http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=CSV&idSite=7&period=day&date=2015-05-05,2015-06-03&label=&date=2015-05-05%2C2015-06-03&filter_limit=false&disable_queued_filters=1&format_metrics=1&expanded=1&translateColumnNames=1&language=en&label=%40%252Findex

ColumnNames are not translated. 

Date,Label,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Avg. time on page,Bounce Rate,Exit rate,Avg. generation time,Metadata: url,Metadata: segment,15 

Thanks.

**Comment by mattab** [comment]
Thanks for the report @noasa999 - issue still exists in master. We will fix it for next releases.

Steps:
 * add system test or other automated test
 * fix issue

**Comment by mattab** [comment]
The problem with the URL you pasted is that there is `&disable_queued_filters=1` - if you remove this parameter the export has the translated column names. I checked on the demo and I cannot reproduce.

@noasa999 can you still reproduce this problem by clicking on the demo?
