### ISSUE TITLE
New  segment operators: "Starts with" and "Ends with"

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#8076]
When creating segments it is only possible to use “Is”, “Is not”, “Contains”, “Does not contain” on non-numeric values. Regarding MySQL Performance, it would make sense to implement “Starts with” and “Ends with” for segment metric definition.

**Comment by mattab** [comment]
Thanks @iMarkus for the suggestion.

**Comment by iMarkus** [comment]
I had a quick look at the code, should not be that hard to implement :)

looking forward

**Comment by tsteur** [comment]
> I had a quick look at the code, should not be that hard to implement :)

We always appreciate pull requests :)

**Comment by iMarkus** [comment]
:)

**Comment by mattab** [comment]
@iMarkus what is the main reason you need "Starts with" and "ends with" - you write "performance" - do you have performance challenge with using "Contains"?

**Comment by iMarkus** [comment]
Hi Mattab,
I thought that using "searchstring%" and "%searchstring" would be faster than "%searchstring%".

Yes we are currently facing some performance issues on real time segments when users define their segments using "Contains" on page urls. Therefore this suggestion came up.

Regards,
Markus

**Comment by mattab** [comment]
It's true that `%search` would use an index, but in Piwik DB, the field `log_action.name` is not indexed so index won't be used (it does not exist).  "Starts with" and "ends with" wouldn't speed up the query.

**Comment by iMarkus** [comment]
Alright. Thanks Matthieu for the detailed explanation. In this case it is unnecessary to implement such feature.

Best regards

**Comment by mattab** [comment]
@iMarkus Thanks for additional information too. it's always positive outcome when features don't need to be implemented :-)

**Comment by tsteur** [comment]
It looks like we will need to implement it after all as it is needed for segmentation of `actionUrls` in #9129 . 

We'll introduce two new operators very likely: `=%` for starts with and `%=` for ends with
