### ISSUE TITLE
NaN in VisitorMap when we have uknown regions

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/piwik#8081]
Example:
![zrzut ekranu 2015-06-09 o 15 42 29](https://cloud.githubusercontent.com/assets/7943292/8078910/38b0e728-0f61-11e5-8ea6-41544cabc720.png)

If you have visits from some country but the regions is not recognized, the ```NaN``` will appear instead of number of visits in legend. This problem is not critical, but it would be misleading for users.

**Comment by mnapoli** [comment]
Fixed by #8082
