### ISSUE TITLE
Updates of referral spam list

### ISSUE THREAD

**Issue by AlterWeb** [piwik/piwik#8083]
I'm seeing a lot of traffic in my Piwik reports of 100dollars-seo.com. I went to the github list to suggest that it would be added but saw that you already added the domain to the list of referral spammers. I understand that on the next update of Piwik we get the new list and we don't see the spam anymore but I thought wouldn't it be great if we could update this list separately. I would love it if it would update every day instead of waiting for the next update of piwik so we really get rid of all the spam all the time.

**Comment by mnapoli** [comment]
Thank you for the suggestion, this is being discussed in this issue: #7674

Putting the list on Github for everyone to contribute was the first step, the next step is to have it auto-update so that spammers are stopped as soon as possible.

I'm closing as duplicates.
