### ISSUE TITLE
Popover displaying messages should use Piwik design style

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8087]
Reproduce:
 * go to Piwik demo, 
 * click Visitors > Real Time Map
 * click on a visitor dot:
 * Expected: nice error message in Popover (eg. #7578 #7648)
 * Got: un-styled popover content:

![popover no permission](https://cloud.githubusercontent.com/assets/466765/8100196/8b5a7682-105c-11e5-9a77-fe90f6da5e22.png)

**Comment by mattab** [comment]
The popover now displays the un-styled login form: 

![un-styled login form](https://cloud.githubusercontent.com/assets/466765/8296713/2e8cff56-19a8-11e5-9d48-98dd37ec40a3.png)

Goal of this issue is to either:
 * when the popover displays a login form, redirect the whole page to the login form (easy fix?)
 * or style the form within the popover (likely not easy / not really needed?)

**Comment by mnapoli** [comment]
PR: #8184
