### ISSUE TITLE
2.14.0 pre-release: manual performance test of All Websites dashboard with thousands of websites

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8098]
Shortly before we release 2.14.0 (likely in RC cycle) we shall run a manual test of Piwik with 20,000 websites and check that the dashboard loads reasonnably fast (since #6809). This is to prevent an easily introducable regression (eg  #7877). sometime later we will create automated performance tests #7889.

Ideally the dashboard should load under 5 seconds, when Piwik tracks 20,000 websites and setting 'browser archiving' is disabled. 

cc @tsteur

**Comment by tsteur** [comment]
tested with 32k sites and was :+1: 

I think we said 10 seconds but not sure if it was for 20k or 30k or 50k websites. I'm kinda sure we said 10 seconds for 30k websites or so

**Comment by mattab** [comment]
Good news. 2.14.0 will be an awesome release :+1:
