### ISSUE TITLE
curl_exec: Operation timed out after 10000 milliseconds 

### ISSUE THREAD

**Issue by roddyofchina** [piwik/piwik#8099]
curl_exec: Operation timed out after 10000 milliseconds with 7193 bytes received. Hostname requested was: plugins.piwik.org  

my piwik version's  is 2.13.1 . 

Nginx error:
1880#0: *114 FastCGI sent in stderr: "PHP message: Error in Piwik: <!DOCTYPE html> <html> <head>    <meta charset="utf-8">  <title>Piwik &rsaquo; Error</title>     <link rel="shortcut icon" href="misc/user/favicon.png" />       <link rel="stylesheet" type="text/css" href="plugins/Morpheus/stylesheets/simple_structure.css" /> </head> <body id="simple">  <div class="logo">       <img title="Piwik" alt="Piwik" src=""/>  <br/>   <a href='http://piwik.org/'>free/libre analytics platform</a> </div>  <div class="box">         <div class="header">            <h1>An error occurred</h1>      </div>          <div class="content"><h2>curl_exec: Operation timed out after 10000 milliseconds with 43193 bytes received. Hostname requested was: plugins.piwik.org</h2>                     <p><a href="javascript:window.history.back();">Go Back</a> | <a href="index.php">Go to Piwik</a> |                        <a href="index.php?module=Login">Login</a></p>  <ul>                             <li><a rel="noreferrer" target="_blank" href="" while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET /index.php?module=CorePluginsAdmin&action=browsePlugins&idSite=18&period=day&date=today&activated=&sort= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s", referrer: "

**Comment by mattab** [comment]
Hi @roddyofchina 

Thanks for the report. 10000 milliseconds with 7193 bytes means your server downloads from the marketplace at about 1 kb/s. This is very slow internet connection unfortunatley.... your Piwik is trying to download the JSON file of list of plugins that weights 350Kb.  it could take 350 seconds. that's very long time to wait. I'm wondering what is our best option?

 * increasing timeout from 10s to 400s does not seem a good idea? (having user wait 400 second is maybe as bad user experience as showing the above error message)
 * maybe we could pre-cache the marketplace response (eg. a scheduled task downloads the JSON file)
 * even if we display the marketplace very fast (eg. with pre-caching) it will be slow or broken to install / update third party plugin (assuming user downloads at 1kb/s)... so i'm not sure what is the best thing we could do.

**Comment by roddyofchina** [comment]
Thank you very much!  Now  I use planning task to download plugins.

**Comment by mattab** [comment]
@roddyofchina what do you mean by "Now I use planning task to download plugins." ?
