### ISSUE TITLE
lastInsertID() in class Db?

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#8103]
Hi!
I cannot find any appropriate method to get the last insert ID. Currently, if I use the Db class to execute queries I will need to do something like this

    Db::query($query, $bind);
    return Db::get()->lastInsertId();

**Comment by tsteur** [comment]
I think that's how it is supposed to work currently. How would you want to use it instead?

**Comment by Globulopolis** [comment]
Ok. I'm asked question just for clarification.

**Comment by tsteur** [comment]
Ok. Please ask questions in the Forums next time. There's a category for that http://forum.piwik.org/list.php?9
