### ISSUE TITLE
 PHP Dependencies case sensitive in HHVM

### ISSUE THREAD

**Issue by Loscillo** [piwik/piwik#8108]
Hi,

I wanted to install Piwik on my machine running HHVM. I was very surprised when I saw that PDO and SPL were not active on my version.

However, after some checking, it seems that my version of HHVM (I do not know if this is common to all versions of HHVM or may occur with a standard PHP) returns both extensions in lowercase.

The problem is the in_array function that is used in the following files:

* plugins/Diagnostics/Diagnostic/PhpExtensionsCheck.php for SPL.
* plugins/Diagnostics/Diagnostic/DbAdapterCheck.php for PDO.

Moreover, it seems that HHVM does not support -1 for directive always_populate_raw_post_data (shown as boolean on http://docs.hhvm.com/manual/en/ini.core.php#ini.always-populate-raw-post-data, possibility of putting 0 but not -1, check is in plugins/Diagnostics/Diagnostic/DbAdapterCheck.php).

Thank you in advance for solving these problems,
Have a nice day.

**Comment by mattab** [comment]
Hi @Loscillo 

Thanks for feedback. Currently we don't offer official support for HHVM.

We welcome pull requests from the community! please consider opening pull request to add HHVM support. See also #7555 #4415

**Comment by Loscillo** [comment]
Hi,

Thank you for your reply. I do it when I have enough time and connection.

Have a nice day.

**Comment by mattab** [comment]
@Loscillo I believe you fixed it in #8131 :+1: 

feel free to re-open in case there is still some work to do
