### ISSUE TITLE
The HTTPS update disappeared from the system check

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#8110]
Regression in UI tests on master: http://builds-artifacts.piwik.org/ui-tests.master/13349.7/screenshot-diffs/singlediff.html?processed=../processed-ui-screenshots/Installation_system_check.png&expected=Installation_system_check.png&github=Installation_system_check.png

The "Update over HTTPS" check disappeared from the system check.

**Comment by diosmosis** [comment]
Looking into it.

**Comment by mnapoli** [comment]
OK if you don't have time don't worry I'll look into it tomorrow (those issues where mostly to remember to fix them as I was working on something else). I think it could be something related to plugin loaded not in the correct order.

**Comment by diosmosis** [comment]
If it has to do w/ plugin loading, I probably caused it :)
