### ISSUE TITLE
Themes are broken

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#8111]
Regression shown by UI tests: http://builds-artifacts.piwik.org/ui-tests.master/13349.7/screenshot-diffs/singlediff.html?processed=../processed-ui-screenshots/Theme_home.png&expected=Theme_home.png&github=Theme_home.png

Themes do not apply anymore.

**Comment by diosmosis** [comment]
Looking into it.

**Comment by mattab** [comment]
:+1: 

fyi: added `not-in-changelog` since this is a regression that appeared in 2.14.0 dev cycle
