### ISSUE TITLE
Revenue from campaigns Stopped working

### ISSUE THREAD

**Issue by shogunjames** [piwik/piwik#8113]
Hi 

I have piwik ( version : 2.13.1) installed. I am using a magento store. I have installed piwik  ecommerce tracking extension in magento to track the ecommerce order in piwik.  I also managed to get the revenue from campaign too. But after one month , it stopped working. 

I am using the following url from campaign :

 [store porduct page url]?pk_campaign=june16&amp;pk_kwd=odernow

to track the campaign revenue, and it was working fine.But now the revenue is not tracking, only the number of visits is showing.

Could you please help me.  I need to solve it asap.

**Comment by mattab** [comment]
Hi @shogunjames 

can you paste here the screenshot showing your Piwik reports?

did you notice if Revenue tracking stopped working after 2.13.1 update, or is it not related to your update?

**Comment by shogunjames** [comment]
Hi Mattab,

I have already upgraded piwik to  2.13.1 for implementing the campaign tracking.

And it was successfull when I implemented . But now when I tried to check it once more , the revenue is not tracking.

I am attaching the screenshot.

![1](https://cloud.githubusercontent.com/assets/11349118/8176305/a6362a4c-1416-11e5-8808-36eb2902be4e.png)

I dont have any idea why it is stopped tracking revenue.

Please help me, I need to send a campaign today.

**Comment by shogunjames** [comment]
Hi Mattab,

This is the javascript tracking code in the checkout page 


 
<script type="text/javascript">
//<![CDATA[

var pkBaseURL = (("https:" == document.location.protocol) ? "[PIWIKURL]/" : "[PIWIKURL]/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 4);
piwikTracker.addEcommerceItem("912337","Regeneration Enzympeeling Puder","Produkte & Bestellung",11.05,3);
piwikTracker.trackEcommerceCartUpdate(40.15);





piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
//]]>
</script>

<noscript><p><img src="[PIWIKURL]/piwik.php?idsite=4" style="border:0" alt="" /></p></noscript>

**Comment by shogunjames** [comment]
Hi mattab,


I don't know what happened to piwik now.  I was getting revenue when I tested last month. Now it stopped working. Please help me...I need to send a new campaign today.

**Comment by mattab** [comment]
Hi @shogunjames is it only Revenue that it's not tracking, or is it also not tracking visits to the campaign? Does it still track correctly other Referrers such as search engine and websites? 

Maybe you can try upgrade to latest Piwik 2.14.0 beta in case it helps: http://piwik.org/faq/how-to-update/faq_159/

andthen try again to track your campaign?

**Comment by shogunjames** [comment]
Hi mattab,

Its only revenue which is not being tracked.

But last month I got the revenue while testing.

Is update only solve this issue. Is there any problem for updating to beta version, since piwik is used for more than 10 sites.

**Comment by shogunjames** [comment]
Its actually the ecommerce tracking is stopped...but ecommerce tracking was successful in the previous version.

**Comment by shogunjames** [comment]
Hi 

When I upgraded to piwik  2.13.1 , all my ecommerce tracking were stopped. 

Do you have any idea about this.

Ecommerce tracking was perfect in the older version.

**Comment by mattab** [comment]
Did you maybe change something on your website around the same time? When you use ecommerce on your website, do you see any warning or javascript error maybe?

you can activate the Tracker debug mode: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker and maybe paste here (or email to hello at piwik.org) your store URL so we can take a look?

**Comment by shogunjames** [comment]
Hi Mattab,

I have send the website url to hello at piwik.org . Could you please check what happened.

I am not getting any idea what to do. It was working in the previous version.

**Comment by shogunjames** [comment]
Helo Mattab,

Is there any way to solve this issue.

**Comment by shogunjames** [comment]
Hi Mattab,

I have upgraded piwik to 2.14.0.

Still now the revenue is not tracking.

Could you please help me.

I have already send mail to piwik, but no response from them.

**Comment by mattab** [comment]
@shogunjames can you send again to matt att piwik.org your website URL and steps to reproduce the issue ? Also please check you enabled traker debugging: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker

**Comment by shogunjames** [comment]
hi Mattab,

I have send the informations to matt att piwik.org.

Could you please check this.

**Comment by mattab** [comment]
The problem is exactly the same as: https://github.com/piwik/piwik/issues/7945#issuecomment-114312376

You need to update the prototype.js library on your website.

**Comment by shogunjames** [comment]
Hi Mattab,

Thank you so much for the help. Now it is working fine.
