### ISSUE TITLE
setDoNotTrack not working when browser setting is "I want to be tracked"

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [piwik/piwik#8114]
With 2.13.1 and FF ESR 31.5.3, and given the following combination of settings:
- Piwik server: tracking all visitors;
- Site setting: _paq.push(["setDoNotTrack", 1]);
- Firefox setting: "Tell sites that I want to be tracked".

I understand such a visit should be taken into account in the statistics. It seems it is not.

Setting FF to "Do not tell sites anything about my tracking preferences" does track the visit while "Tell sites I do not want to be tracked" is honoured.

**Comment by mattab** [comment]
I'm using Firefox 38 and it seems they simplified the Do Not Track setting:

![dnt ff 38](https://cloud.githubusercontent.com/assets/466765/8174028/3ca0ab6a-142b-11e5-8550-7ebf6f57ec6c.png)


@patriiiiiiiiiick with FF 31, when you set "Tell sites that I want to be tracked", can you show a screenshot of your HTTP headers (open console and look for the request in Net panel) for the request to piwik.php ?

**Comment by patriiiiiiiiiick** [comment]
@mattab In that case, there is only the piwik.js call, not the piwik.php.

I don't require a fix for this but will only get the new ESR in a couple of months...

**Comment by patriiiiiiiiiick** [comment]
related: http://forum.piwik.org/read.php?2,117170,117170

**Comment by mattab** [comment]
Since Firefox changed their UI, and it bugs only with old browser, and it rather tracks less data than more data, I mark as `wontfix`. if someone disagrees feel free to comment
