### ISSUE TITLE
use of &cookie= in HTTP tracking 

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#8129]
Hi,

I have a question about the use of HTTP tracking.
The following page shows an Example Tracking Request:
http://developer.piwik.org/api-reference/tracking-api

In this example there is a part in the URL that states: "&cookie="
There is no reference to the parameter in the rest of the page, but can we use this parameter to detect unique visits or visitors while using HTTP tracking? 
The HTTP tracking URL can use the cookie value that is known within the running application.

**Comment by mattab** [comment]
Hi Richard,

The doc was added. This parameter is set to 1 when the user's browser/client supports cookies. it's used to process % of users who support cookie. I've fixed the example as well
