### ISSUE TITLE
Widget border is broken on IE 10

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8134]
See attachment. Seen on Windows 8 + IE 10.

Tried to quickly fix it myself but couldn't.

![ie10_borders](https://cloud.githubusercontent.com/assets/273120/8224079/272936a2-15d5-11e5-90c4-cb9903303b53.png)

**Comment by sgiehl** [comment]
I'm not able to reproduce it on a Win8 / IE10 test vm. It even does not occur when having IE 10 in combat mode or in IE9 document mode... Any steps how to reproduce?

**Comment by tsteur** [comment]
I only update Piwik demo and that's it. I probably use an outdated version of IE10 (see about in screenshot) as I'm missing some updates on that VM. It looks good on Saucelabs with IE10+Win8 as well.

![windows_10](https://cloud.githubusercontent.com/assets/273120/8316942/3406943c-1a4e-11e5-9d85-a7510f8feb37.png)

Thx!
