### ISSUE TITLE
Action 'extend' not found in the module 'CorePluginsAdmin'

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/piwik#8136]
How to reproduce:

* Go to ```administration```
* Select ```marketplace``` from left menu
* Click ```upload a plugin``` and select your plugin
* Click upload

After this, you sholud see something like this:

```
Unzipping plugin
You have successfully installed the plugin ....
```

and two links on the bottom: ```Activate plugin``` and ```Back to Marketplace```.
When we click ```Back to Marketplace```, we will see error:

![zrzut ekranu 2015-06-18 o 10 38 03](https://cloud.githubusercontent.com/assets/7943292/8227263/29392f94-15a6-11e5-88d3-8e2f15ddce34.png)

**Comment by mnapoli** [comment]
Fixed by #8137
