### ISSUE TITLE
Searching for users

### ISSUE THREAD

**Issue by surfi2000** [piwik/piwik#8138]
The 'Users' section within 'Administration' quickly becomes difficult to navigate when there are a large set of users.

I can see that data tables are used for the 3 tables displayed. Would it be possible to add a search field to the 3 data tables displayed in the 'Users' section allowing filtering of results? Something similar to https://datatables.net

**Comment by mattab** [comment]
Hi @surfi2000 thanks for suggestion. See this issue:  Show paging and search in the screen 'Manage users' to easily manage hundreds of users #4474
