### ISSUE TITLE
Warning message in  Piwik 2.14.0-b3: es-ar.json: failed to open stream

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8139]
since update from 2.13 to 2.14.0-b3 sometimes this message pops up on different piwik sites:
WARNING: /usr/local/www/apache24/noexec/piwik/html/plugins/LanguagesManager/API.php(288): Warning - file_get_contents(/usr/local/www/apache24/noexec/piwik/html/plugins/Intl/lang/es-ar.json): failed to open stream: No such file or directory - Piwik 2.14.0-b3 - Please report this message

![2015-06-18_14h06_05](https://cloud.githubusercontent.com/assets/5681880/8230728/3018c852-15c3-11e5-935b-981f55ee00f2.png)

**Comment by verfriemelt-dot-org** [comment]
this still existed after zupgrade von 2.13 to 2.14-b4 but after page refresh the error gone away.

**Comment by sgiehl** [comment]
Would you mind having a look if the file piwik/lang/es-ar.json exists?

**Comment by verfriemelt-dot-org** [comment]
sure, 
 
    # ls -lha lang/es-ar.json 
    -rw-r--r-- 1 www-data www-data 182K Mar 30  2014 lang/es-ar.json

so i dont new, why it was not found in the first place after refreshing the page.
now everything is fine and i touched nothing in the meantime. just hit refresh

**Comment by sgiehl** [comment]
The file lang/es-ar.json is not included in the release atm. I'm not sure if it has been removed in he past, but it should solve your problems if you remove the file.
