### ISSUE TITLE
visitor log+profile: show campaign details in same depth & format

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8140]
Show campaign details in visitor log and visitor profile in  same depth (=> all you have) and same format

Please see attachment from Piwik 2.14B3
![2015-06-18_14h08_48](https://cloud.githubusercontent.com/assets/5681880/8230874/7d795e4e-15c4-11e5-9945-9fd6d060343b.png)

**Comment by mattab** [comment]
Thanks for the suggestion @hpvd 

I guess the issue summary is 
 * In Visitor Profile, display Referrer info consistently with Visitor Log. For example Campaign information in Visitor Profile should be displayed as `from Campaign: kong - blog` instead of `from: Campaign (kont)`

**Comment by hpvd** [comment]
many thanks for working on this.
Now both looks the same! That's great!

when looking on it, it shows now campaign name and referring website (www. ...)
Keyword seem to be gone.

Would be great if one could make this directly compatible to piwikpro advanced campaign
and show all available details in visitor log and profile.
please see the referenced
https://github.com/PiwikPRO/plugin-AdvancedCampaignReporting/issues/25
https://github.com/PiwikPRO/plugin-AdvancedCampaignReporting/issues/26

**Comment by tsteur** [comment]
> when looking on it, it shows now campaign name and referring website (www. ...)
Keyword seem to be gone.

I'm not sure what you mean? It shows not the website for me:

![campaign](https://cloud.githubusercontent.com/assets/273120/9269448/22dcf14e-426a-11e5-8ac3-6c648eeb0275.png)

**Comment by hpvd** [comment]
for is it looks like this:
![2015-08-14_14h21_55](https://cloud.githubusercontent.com/assets/5681880/9273782/15bf9842-4290-11e5-9841-91f009965dad.png)

**Comment by hpvd** [comment]
ah ok just noticed when this happen: these links only have name and source defind - no keywords
->so its fine.

What do you thing of making it directly showing the additional informations when coming from advanced campaign plugin?

**Comment by tsteur** [comment]
Can we maybe create a new issue for this if possible? I'm not so much into campaigns etc and we make sure this way to discuss it when having a new, opened issue

**Comment by hpvd** [comment]
@tsteur:
I've created a new ticket https://github.com/piwik/piwik/issues/8581
