### ISSUE TITLE
Collecting standard events and the js code snippets belonging to them

### ISSUE THREAD

**Issue by masteranalyze** [piwik/piwik#8141]
The main ideea,of this feature,is to have Events centralized in back end of the Piwik.

The events must be able to be disable,or enable,as user wish,totally freedom.
All events,to be with his options in back-end events.

Please feel free to contribute to this post with the Events and js code snippet for them.

I will start with this one,that i`m using for adjusting bouncing rate :
Name of this script : Adjusted bounced rate:

```js
<script>
setTimeout("_paq.push(['trackEvent', 'time spent', '>15sec', 'good reading'])",15000);
</script>
```

Tested and working.

Maybe somebody can put all this script for tracking User with Ad-BLOCK witch is very popular nowdays: http://www.statstory.com/how-many-users-block-your-ads-find-out/

And more...

**Comment by hpvd** [comment]
you have got an invisible script: start with     ```javascript     and end with     ```

**Comment by masteranalyze** [comment]
hmmm,i think i did it put it without quotes.

"<script>
        setTimeout("ga('send','event','adjusted bounce rate','page visit 15 seconds or more')",15000);
</script> " - script for Adjusted Bounced Rate

thanks for correction hpvd.

**Comment by masteranalyze** [comment]
thanks hpvd,i think ,now is good....and corectly.
How we will implement this in piwik back-end ?Or who !?
We can make the list,and people surely will contribute on it,but somebody also needs to implement it!

**Comment by mattab** [comment]
Hi @masteranalyze 

do you mind posting your code snipped in the Forum Knowledge base? More people will see it there and it can be use as starting point for others to contribute their snippet. thanks!

**Comment by masteranalyze** [comment]
I posted here,but seems there is no much people involved into the forum either,at least not on this time!

http://forum.piwik.org/read.php?3,128779
