### ISSUE TITLE
Piwik 2.14.0-b4 package is 30Mb big instead of 14Mb

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8144]
Between beta1 and beta2 the Piwik ZIP package grew 15Mb / 100% to 30Mb. See:

![regressed size](https://cloud.githubusercontent.com/assets/466765/8247234/d73ce4f0-16a0-11e5-94d1-1f2c7b9ec945.png)

let's investigate and make package smaller again, 30Mb is not reasonable.

**Comment by diosmosis** [comment]
The tests folder is 24MB, should it be in betas?

**Comment by mnapoli** [comment]
TCPDF is now installed with Composer (was previously included in the repo manually IIRC): https://github.com/piwik/piwik/blob/master/composer.json#L58

This dependency includes 27Mb of fonts. I guess that explains the difference. I don't know if we use them though, might require to carefully remove them. Also there are 2Mb of examples in there that we can get rid of.

**Comment by mattab** [comment]
> The tests folder is 24MB, should it be in betas?

all files in tests/* are deleted from the releases 

> This dependency includes 27Mb of fonts. I guess that explains the difference. 

That explains it!! we will need to update the build script https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh to remove unused fonts  cc @sgiehl  in case you know which ones we need  

Also created a follow up issue:  automated test to detect when the Piwik files become too big #8158

**Comment by sgiehl** [comment]
See https://github.com/piwik/piwik/blob/master/core/ReportRenderer/Pdf.php#L93-L132
I guess all existing variants of the font we use here, could be removed aswell.

**Comment by mattab** [comment]
done in: https://github.com/piwik/piwik-package/issues/33#issuecomment-113996050

2.14.0-b6 is back to being 16M :+1:

**Comment by mattab** [comment]
it's still 3Mb bigger than 2.13.1 but after looking hard I can't find any more way to make package size smaller
