### ISSUE TITLE
Broken design for Trusted Piwik Hostname in CoreAdminHome Piwik 2.14 beta

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#8146]
Hi!
This issue gradually turned from Piwik 2.13 into Piwik 2.14 beta.
![clipboard01](https://cloud.githubusercontent.com/assets/740757/8248370/09453ab8-1667-11e5-9ba0-52b6b57d62f1.jpg)
IMHO we need to fix buttons and add 3px margin-bottom for these inputs. I know that the `Save` button is for saving all settings, but it's looks like design mistake.

**Comment by mattab** [comment]
Maybe we just make the "Add" a text label, rather than a button?

**Comment by mattab** [comment]
Or we display icon + label eg.

![add new trusted host](https://cloud.githubusercontent.com/assets/466765/8693888/d72b28de-2ada-11e5-8f5d-f0c26fe8d124.png)

**Comment by Fensterbank** [comment]
I like the idea of icon + label above.
Looks way more consistent.

**Comment by barbushin** [comment]
![image](https://cloud.githubusercontent.com/assets/683352/8831928/4e021ba6-30ae-11e5-9659-551989fbcd39.png)

Looks good?

**Comment by barbushin** [comment]
Here is example of how it works http://i.imgur.com/lmBqY9p.gif I changed `Add a new trusted host` to readonly, and added auto-focus to new input text field.

**Comment by mnapoli** [comment]
@barbushin the behavior in the gif looks really good!
