### ISSUE TITLE
Bootstrap integration

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#8147]
This is good news that the Piwik support Bootstrap! Maybe we can change the default styling to support different styles for form elements like labels, buttons, inputs?
Now at least buttons looks the same for btn-primary, btn-default, and other styles.

**Comment by mattab** [comment]
Hi @Globulopolis 

 we don't support the whole of bootstrap and only a few bits that we find most useful. 
Our theming is limited for now to  a few elements, documented in: http://developer.piwik.org/guides/theming
