### ISSUE TITLE
List of codes used like country, region, city in piwik

### ISSUE THREAD

**Issue by ruchitrami** [piwik/piwik#8149]
In reference to forum post on piwik forum: http://forum.piwik.org/read.php?15,123616, documentation of Piwik is missing list of codes used in piwik. They should ideally be part of recognized coding standards or should be clearly defined with and API exposing all the details.

**Comment by mattab** [comment]
We're adding country codes mapping in https://github.com/piwik/piwik/issues/11109 #11376 :+1:
