### ISSUE TITLE
Unable to Add Websites

### ISSUE THREAD

**Issue by 10twebdesign** [piwik/piwik#8155]
I have an installation that has been up for over a year. I'm no longer able to add websites to track. When I open the page, the "Websites Management" area never populates, going from the...

Your Web Analytics reports need Websites! Add, update, delete Websites, and show the JavaScript to insert in your pages. You currently have access to 20 websites. 
A user with Super User access can also specify global settings for new websites.

...paragraph, right to the Global Website setting section; the table with all of my websites never gets created. The 'Loading Data' prompt shows up and disappears, but never gets replaced. I've attempted this in different browsers, different operating systems, and the result is the same.

No errors are being logged in the error_log file. I've even uploaded a completely fresh copy of Piwik (v 2.13.1), and there is no change.

**Comment by sgiehl** [comment]
please check http://piwik.org/faq/troubleshooting/faq_18485/

**Comment by 10twebdesign** [comment]
Just checked them; the two pages were identical without any change in configuration.

**Comment by mattab** [comment]
@10twebdesign can you try upgrade to the latest beta version? http://piwik.org/faq/how-to-update/faq_159/

if you still have an issue, is Administration > System check, showing good results?

**Comment by 10twebdesign** [comment]
Just updated to 2.14.0-b4, with no change. System check reports everything good.

**Comment by sgiehl** [comment]
Can you have a look at the developer console of your browser, if there are any javascript errors occuring or if some requests fail to load?

**Comment by 10twebdesign** [comment]
Here is a full copy of the console:

GET http://track.10t.co/plugins/SitesManager/angularjs/sites-manager/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
Error: [$compile:tpload] http://errors.angularjs.org/1.2.28/$compile/tpload?p0=plugins%2FSitesManage…r%2Fmultiline-field.directive.html%3Fcb%3D742c3534b19283cf4c894d88f8b0a56a
    at Error (native)
    at http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:124:450
    at http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:179:148
    at http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:190:286
    at w (http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:219:167)
    at w (http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:219:167)
    at http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:220:428
    at h.$eval (http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:231:32)
    at h.$digest (http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:228:117)
    at h.$apply (http://track.10t.co/index.php?module=Proxy&action=getCoreJs&cb=742c3534b19283cf4c894d88f8b0a56a:231:362)
GET http://track.10t.co/plugins/SitesManager/templates/help/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
GET http://track.10t.co/plugins/SitesManager/templates/sites-list/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
GET http://track.10t.co/plugins/SitesManager/templates/help/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
GET http://track.10t.co/plugins/SitesManager/templates/help/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
GET http://track.10t.co/plugins/SitesManager/templates/help/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
GET http://track.10t.co/plugins/SitesManager/templates/sites-list/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS
GET http://track.10t.co/plugins/SitesManager/templates/sites-list/index.php?module=MultiSites&action=index&idSite=2&period=range&date=last7 net::ERR_TOO_MANY_REDIRECTS

**Comment by sgiehl** [comment]
Somehow the urls are not what would need to be loaded...
I could have a closer look if you want to, but I would need an account at your piwik to check that.
Would you mind sending me the access data to stefan@piwik.org

**Comment by sgiehl** [comment]
As discussed by mail, that seems to be a server side problem, as some html files are not served correctly.
