### ISSUE TITLE
Design tweaks after 2.14.0-b4

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8157]
Follows up https://github.com/piwik/piwik/pull/8135

 * [x] Installation looks weird  http://builds-artifacts.piwik.org/ui-tests.master/13496.7/Installation_db_setup 
 * [x] ~~Live Real time widget, grey background is too dark on PC (looks better on mac)~~ (Matt's screen color settings were wrongly set)
 * [ ] end of install `Continue to Piwik` button should be big button, got: small button

![end of install button should be big](https://cloud.githubusercontent.com/assets/466765/8265947/5552acd4-1765-11e5-9c5a-7ac63deb0095.png)
 - [x] ~~Icons to expand a subtable are not vertically aligned correctly with the text:~~

    ![capture d ecran 2015-06-18 a 10 48 56](https://cloud.githubusercontent.com/assets/720328/8227442/b7fc95c6-15a7-11e5-8255-1f75ec6f40ff.png)

- [x] ~~In the visitor log, this isn't vertically aligned anymore:~~

    ![capture d ecran 2015-06-18 a 10 56 38](https://cloud.githubusercontent.com/assets/720328/8227566/c00cdc0c-15a8-11e5-8d90-eb4b0090120d.png)

* [ ] make ui tests build green

**Comment by mattab** [comment]
* [ ] Trusted Piwik Hostname UI is broken (`Add` does not work)

**Comment by mattab** [comment]
* [ ] end of install `Continue` button should be big button 

![end of install button should be big](https://cloud.githubusercontent.com/assets/466765/8265947/5552acd4-1765-11e5-9c5a-7ac63deb0095.png)

**Comment by tsteur** [comment]
Installation is fine, it just looks different currently because of another PR that changes the viewport size to 320x240

**Comment by tsteur** [comment]
It's not only the end install page that has a different button. I get a small button on the bottom right on all pages but eg on System Check page it's a huge button on the left side.

**Comment by mattab** [comment]
- [ ] Icons to expand a subtable are not vertically aligned correctly with the text:

    ![capture d ecran 2015-06-18 a 10 48 56](https://cloud.githubusercontent.com/assets/720328/8227442/b7fc95c6-15a7-11e5-8255-1f75ec6f40ff.png)


- [ ] In the visitor log, this isn't vertically aligned anymore:

    ![capture d ecran 2015-06-18 a 10 56 38](https://cloud.githubusercontent.com/assets/720328/8227566/c00cdc0c-15a8-11e5-8d90-eb4b0090120d.png)

**Comment by mattab** [comment]
~~Crossed out~~ two issues above that only show up in UI tests /phantomjs but not in actual browsers

**Comment by mattab** [comment]
@mnapoli can we make all installer buttons "big" sizes? (third checkbox in this issue)

**Comment by mattab** [comment]
CoreUpdater UI tests are regressed. maybe this is due to recent DI work? example recent build: http://builds-artifacts.piwik.org/ui-tests.master/13645.7/screenshot-diffs/diffviewer.html  cc @mnapoli
