### ISSUE TITLE
Update event on plugin update?

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#8175]
Hi!
I can't find anything about it in Plugin class. Maybe we could add an update() method which will be called when plugin just updated from remote or local?
Or maybe another solution exists?

**Comment by tsteur** [comment]
Such a solution exists but it might be not documented on the website. You can generate an update via `./console generate:update`. It will ask for your plugin name and then generate a file under `plugins/YourPlugin/Updates/yourVersionNumber.php`. 

There are some explanations in the generated file but also see eg those examples:

An example is here: https://github.com/piwik/plugin-CustomAlerts/tree/master/Updates

**Comment by mattab** [comment]
It's not documented yet. Here is issue to track the new doc: https://github.com/piwik/developer-documentation/issues/84
