### ISSUE TITLE
List of excluded IP addresses not displayed after using site search

### ISSUE THREAD

**Issue by quba** [piwik/piwik#8185]
List of excluded IP addresses is not being displayed after using site search (in websites management). This setting is actually being saved properly but after using site search or edit button after site search, these values don't load properly.

It's also worth checking if other values are being correctly loaded after using site search there.

**Comment by quba** [comment]
I was able to reproduce it using Piwik 2.13.1 and latest beta.

**Comment by mnapoli** [comment]
Thanks! I believe this was fixed by #8166, please reopen if I'm wrong :)

**Comment by quba** [comment]
OK, thanks for the info. I'll confirm this after next beta release.

**Comment by mattab** [comment]
2.14.0-b8 from yesterday included the fix in #8166, did you really have this issue with this latest beta?
