### ISSUE TITLE
Display permanent notification in admin screen for PHP 5.4 warning about EOL 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8193]
At some point Piwik will require PHP 5.5. #8156

We need to warn users about this at least 6 months before. Since PHP 5.4 is EOL we can start warning users already. Piwik displays such warning for PHP 5.3 so let's display it for PHP 5.4 as well.

Follows up #3877 #6056 #6275

**Comment by tsteur** [comment]
FYI: In #8452 I changed the notification about EOL to PHP 5.4 see eg http://builds-artifacts.piwik.org/ui-tests.3.0/14501.7/UIIntegrationTest_admin_user_settings . I removed the message that we will drop support for PHP 5.4. Maybe this issue is already closed.

**Comment by mattab** [comment]
looks good :+1:
