### ISSUE TITLE
Visitorlog: show always full url instead of "(url)"

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8202]
When new visits starts directly  with an event, only "(url)" is shown instead of full url name although the name is available and visible on hover.
Please see attachment made from 2.14b9 

when do visits starts with an event?
e.g. site was opened some time ago, user keeps it open in background, brings it to front, and uses something like menue, video or similar which triggers an event...

![2015-06-24_12h32_18](https://cloud.githubusercontent.com/assets/5681880/8328332/37aac9b0-1a70-11e5-9288-7571a87f4ae1.png)

**Comment by tsteur** [comment]
I think there are many reasons why the first action could be an event. Eg if a new visit is created after 30 minutes and a new event is tracked after 31 minutes, then this would be the first action. Also if the first action that is tracked after midnight for a given visitor, this would be the first event. Etc.

**Comment by mattab** [comment]
:+1: if a URL is available in the tooltip, then we should also display it in the Visitor Log.
