### ISSUE TITLE
geoip autoupdater shows scheduled time in the past

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8210]
geoip autoupdater shows scheduled time in in the past
all other scheduled tasks are in the future

please see attachment.

piwik 2.14.B10

![2015-06-25_11h39_42](https://cloud.githubusercontent.com/assets/5681880/8351681/7ba4cdea-1b2f-11e5-976b-de50ff860510.png)

**Comment by mnapoli** [comment]
I believe this is normal: the scheduled tasks are processed every few minutes (depends if you run the archiving with cron or not), so it's possible the time is in the past. That only means the task will be run the next time "scheduled tasks" are run.

**Comment by hpvd** [comment]
tanks for the explanation. Is there a difference to the other tasks which show dates in the future?

**Comment by mnapoli** [comment]
The time a task will run depends on the frequency (e.g. each day, week, month, …) but also on the time it was first registered. For example if it was registered at 10am in the morning, for every day, then the next execution time will be 10am the next day.

However if another task was registered at 11am, then the next execution time will be 11am the next day. That may explain why some dates are different. Anyway nothing seems wrong in your screenshot.
