### ISSUE TITLE
Code style: consistent indentation with 4 spaces everywhere

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#8212]
I'm not sure it's covered by #8211 so here is a small issue to decide this: Piwik's codebase has inconsistent indentation accross languages. PHP is always 4 spaces (as per PSR-2), Javascript too IIRC, but Less/CSS and sometimes JSON are often a mix of 2 and 4 spaces.

How about we say it's 4 spaces for everything and be done with it? Anybody against that?

**Comment by tsteur** [comment]
Personally I prefer 2 spaces in less/css files as it is much easier to read IMO

**Comment by mnapoli** [comment]
Standards are not really meant to satisfy personal preferences. We don't use PSR-2 because we think it looks good, but rather because it's simpler for everybody and it's consistent with the rest of the PHP world. Simple and consistency are good for the project (a good illustration is how the indentation is all mixed up today), that's why I'm suggesting this change (not because I like it better with 4 spaces).

**Comment by tsteur** [comment]
You asked, so I answered my opinion on that.

**Comment by mattab** [comment]
@tsteur because most of our less files already use 4 spaces, it would be nice to use 4 spaces for less files (this avoids having to screw all the git history if we changed it to 2 spaces...)

Anyway, we don't need to force space count for less or json - we could just keep standards for javascript and php for now since that's the core of our codebase?

**Comment by tsteur** [comment]
I really do not care whether it's 4 or 2 spaces. Just personally think 2 spaces are for me better to read, at least for me. I do not work so often with it anyway so do not even mind if it is mixed with 2 or 4 spaces :)

**Comment by diosmosis** [comment]
:+1: for consistent indentation across all code files (.php, .less, .css, .html, etc.)

**Comment by mattab** [comment]
Closing - this may be applied in the follow up issue `Automatically convert our code base to use a consistent code style` #9545

**Comment by tsteur** [comment]
Just FYI: There is eg the JavaScript coding standard that uses 2 spaces https://github.com/feross/standard
