### ISSUE TITLE
UrlHelper: QueryParameters parser return wrong result.

### ISSUE THREAD

**Issue by Preclowski** [piwik/piwik#8215]
For example, calling

```
UrlHelper::getArrayFromQueryString($action->getActionUrl())
```

For action url

```
http://piwik.net/index.php?PaywallPlan=40&ArticleId=1
```

The response looks like

```
'array(2) {
  \'http://piwik.net/index.php?PaywallPlan\' =>
  string(2) "40"
  \'ArticleId\' =>
  string(1) "1"
}
```

First parameter is parsed wrong, it should contain only query param name.

**Comment by sgiehl** [comment]
As defined in the method description ```getArrayFromQueryString``` has the query-string as paramater. Your example uses the full url. I don't think this method should try to handle incorrect parameter values
