### ISSUE TITLE
Single quote/apostrophe in segment value replaced with closing parenthesis on save

### ISSUE THREAD

**Issue by junctionapps** [piwik/piwik#8216]
Create a Segment with a value containing an apostrophe: 
![image](https://cloud.githubusercontent.com/assets/8778630/8361280/8f5d1dce-1b48-11e5-929b-a64566179d84.png)

City Is Saint John's 

Ends up with single quote/apostrophe replaced with a right parenthesis, ending up with: 
![image](https://cloud.githubusercontent.com/assets/8778630/8361306/c349d096-1b48-11e5-8e47-c5b4dff12e71.png)

Saint John)s 
and does not filter correctly. Picking "Saint John's" from the suggested list yields the same behaviour. 

Using Version 2.13.1

**Comment by mattab** [comment]
Hi @junctionapps - thanks for this bug report.
