### ISSUE TITLE
Cities are not being shown on the visitors map

### ISSUE THREAD

**Issue by quba** [piwik/piwik#8217]
When I switch to cities view, I can see the following error in the console:
```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
```
I can reproduce it using demo: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=UserCountry&action=index&idSite=7&period=day&date=yesterday

**Comment by igorkba** [comment]
browser type and version, name of javascript which throws this exception? I some time see on my console type error from my chrome plugin. :) I don't have permission on the ID site, but when I change ID site to public, it works fine(google chrome 43.0.2357.130):
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=UserCountry&action=index&idSite=7&period=day&date=yesterday

**Comment by quba** [comment]
Have you changed from Regions to Cities?

**Comment by igorkba** [comment]
ok, I see already. But I got first type error from bubble_compiled.js : *a.target.className.indexOf is not a function*(pretty print line 4369) 
```javascript
-1 != a.target.className.indexOf("jfk-bubble-closebtn") && a.preventDefault()
```

**Comment by igorkba** [comment]
I private mode works fine:
see attachmet
![regionstocity](https://cloud.githubusercontent.com/assets/5531815/8364755/df2c8fa2-1b88-11e5-8376-04788d2abe53.png)

**Comment by igorkba** [comment]
I see already, you're right.

**Comment by mattab** [comment]
Thanks for the report. Adding to 2.14.0 as this is a regression. 

Suggestions:

 * let's add a  UI test for the Cities map (eg. Germany)
 * let's add a UI test for the Region map (eg. USA)
 * then fix the issue
