### ISSUE TITLE
email report generation fails without message when required plugin is inactive

### ISSUE THREAD

**Issue by Fensterbank** [piwik/piwik#8219]
While testing some random scheduled email reports I realized the activation of the statistic **Visitor Configuration** seems to provoke an error.
The download or sending of the report is not possible.

In the auto archiver cronjob error log, I got following output while the scheduler never finished:
> PHP Fatal error:  Call to undefined function Piwik\Plugins\DevicesDetection\getOsFullName() in /var/www/piwik/plugins/Resolution/functions.php on line 21

I tested the option in different reports on different sites. It was reproducable.
All reports worked fine without the statistic **Visitor Configuration**, after including it, they didn't work anymore.

This option seems to crash the report function.
I tested it in Piwik 2.13.1

Can someone confirm this issue?

**Comment by mattab** [comment]
Hi @Fensterbank 

I can't reproduce this error on the demo running the latest beta. Can you try reproduce on latest beta?

**Comment by Fensterbank** [comment]
Hi @mattab 

I realized that the plugin **DevicesDetection** was not activated.
I tried to activate, but the database upgrade failed, because of missing columns. (wtf?!)

I just created the columns manually and was able to activate the plugin.
Now the reports are working!

Finally you should be able to reproduce this issue following these steps:
1. Deactivate the plugin **DevicesDetecion**
2. Create a email report with the included statistic **Visitor Configuration**
3. Download the email report

This type of error can be very disturbing.
A suggestion would be to prevent the selection of specific statistics  if the required plugins are inactive.

**Comment by mattab** [comment]
Hi @Fensterbank 

I cannot reproduce this issue in 2.14.0 - can you please reopen if you can still reproduce the bug? The `Visitor configuration` report loads even when DevicesDetection plugin is disabled.

**Comment by unhammer** [comment]
I was able to add "visitor configuration" without having the devices plugin activated, giving this error message. I think my devices plugin was active at some point earlier. Simply activating the plugin solved it for me.
