### ISSUE TITLE
Enable by default Downloads and Outlinks tracking of right and middle clicks

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8224]
The goal of this issue is to enable by default, the tracking of right and middle clicks on Downloads and Outlinks. This was implemented in  #5287 and currently is only enabled on opt-in. Once we know this feature works well, we could enable it by default (for new Piwik users or for all users?)

**Comment by tsteur** [comment]
Maybe we should re-evaluate before Piwik 3.0?

**Comment by mattab** [comment]
Moved tentatively into 2.15.0

**Comment by tsteur** [comment]
or maybe to 3.0.0 as well? Have we seen it somewhere in practice? Is it enabled somewhere?

**Comment by mattab** [comment]
Moved back to `Sohrt term` for now

**Comment by hpvd** [comment]
Learned from good expierence with testing and optimizing heart beat supported time on page caculation (https://github.com/piwik/piwik/issues/9504)
I would suggest to enable this in demo as soon as possible so we can easily see if it's working as expected in real world.
What do you think?

**Comment by hpvd** [comment]
doing this, maybe on should add something like an additional extra "label" to tracked links to make it possible to see a difference between
- standard following 
- following with extra
?

Reasons:
- it's good for testing of course
- and on the other hand maybe this would have an impact on handling leaving page or not and calculation of visit times in the future...
