### ISSUE TITLE
xxx the end of the ip, but still connect the visits of one person together

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#8237]
i often see that a recurring person is tracked as a new person.
also if the person uses the same IP, ...
this visits could be collected and summed up together 
only by giving the user an anonymous ID and set a cookie with the same ID.
this is a math game if you have same browser, IP, cookie, 
settings it could be the same person also if one parameter is changed.

**Comment by mattab** [comment]
Hi @Tobias-Conrad 
Could you paste a screenshot of the Visitor Log showing the same user tracked as a new visitor?

**Comment by Tobias-Conrad** [comment]
solution: before anonymized IP give the person a fixed ID would help.

i attached a screenshot please search for IP 91.21.76.
IP occurs 7 times, gattered in two userprofiles 3 + 4 visits

A) i had to add only the tracking pixel on one site(digistore24.com).
so for this visits it creates a new visitor ID.
3 visits ID d86820ea0249372e (only tracking pixel), 2x ID 485ea9dd526ac612

![91 21 76-3-visits-from-7-are-gattered](https://cloud.githubusercontent.com/assets/7352673/8402257/06893088-1e3a-11e5-88cf-35bc26b04403.jpg)
![different id-when-only-tracking-pixel-but same ip](https://cloud.githubusercontent.com/assets/7352673/8402272/4938a148-1e3a-11e5-8793-29b646da82c9.png)

B) other IP in log and user details, see attachements
![andere-ip-log-user-details](https://cloud.githubusercontent.com/assets/7352673/8402084/050716f0-1e38-11e5-8588-a26c581c84a9.png)

solution: before anonymized IP give the person a fixed ID would help.
because we save only the visitor ID there will be no harm of any law. (i read about it)
this solution brings also a better location from the full IP, before it will be SAVED anonymized.

**Comment by mattab** [comment]
Hi @Tobias-Conrad 

Sorry but I don't quite understand the issue - could you maybe try again describe what is the issue? maybe you could list "Steps to reproduce" and behavior that you see VS behavior you expected?

**Comment by mattab** [comment]
I'll close it for now, maybe open a new issue with the steps to reproduce, or re-open this one if it's better
