### ISSUE TITLE
Adding/Editing a new goal doesn't update its "state" and some UI issues

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8244]
While testing #8242 I noticed some issues with "Adding new goals" and probably as well with "Editing goals". I'm using Chrome 43 on MacOS. To reproduce go to "Your Username in top right menu => Goals => Create new goal" 

* When selecting another value in the select field "Goal is triggered" the form is not immediately updated. I have to click on the select box again to see the UI change. This results in very weird states eg it says "manually" but it still shows all the radio boxes on the other side. Or it says "when visitors" but I'm not able to select any of the radio boxes.

* Missing space below "Goal is triggered" and checkbox "Case sensitive match" is positioned on the right instead of left. The labels also seem to look different etc but this should not be part of this issue as it might be quite a bit of work.

See screenshot: 

![goals_management](https://cloud.githubusercontent.com/assets/273120/8419922/c4848b0a-1f11-11e5-81ef-32d043b18942.png)

* Wording is incorrect in "Manage Goals" overview. It says "Create a new goal" but then the opened form says "Add a new goal". In Websites Management / User Management we use the term "Add" and it should be used there as well

* When creating a goal triggered "Manually" and then editing a goal the radio boxes look disabled but still can be selected when choosing "Goal is triggered when visitors". They should not look disabled
 
![goals_radio](https://cloud.githubusercontent.com/assets/273120/8420089/54de38da-1f13-11e5-8209-396e3495faf7.png)

**Comment by mattab** [comment]
@barbushin could you maybe take a look at this issue?

**Comment by mattab** [comment]
Not fixed:

 * Wording is incorrect in "Manage Goals" overview. It says "Create a new goal" but then the opened form says "Add a new goal". In Websites Management / User Management we use the term "Add" and it should be used there as well
 *  When creating a goal triggered "Manually" and then editing a goal the radio boxes look disabled but still can be selected when choosing "Goal is triggered when visitors". They should not look disabled

**Comment by barbushin** [comment]
There is a new PR with that fixes https://github.com/piwik/piwik/issues/8279 Sorry, I forgot to pay attention to that bugs.

**Comment by mattab** [comment]
No worries @barbushin  and cheers for issuing the new PR
