### ISSUE TITLE
Field styling in ScheduledReports is making it useless.

### ISSUE THREAD

**Issue by sebastianpiskorski** [piwik/piwik#8254]
Under an address like this `?module=ScheduledReports&action=index&idSite=1&period=day&date=yesterday` when I edit report there is a `Send report at ` field and I don't see what I enter there.
![screen shot 2015-06-30 at 4 18 14 pm](https://cloud.githubusercontent.com/assets/12272711/8432998/aa35b4b8-1f43-11e5-873d-b37eb1e8cc24.png)

**Comment by Fensterbank** [comment]
Is already fixed on https://github.com/piwik/piwik/commit/0b578d2f9c37c39f74592b525ac6fc404fef756e and https://github.com/piwik/piwik/commit/e8bdb6ebb2dfcc848f020b1afb118b8d3f519c5f :+1:

**Comment by sebastianpiskorski** [comment]
That's great! :+1:

**Comment by mattab** [comment]
Duplicates #7827
