### ISSUE TITLE
array to string conversion in 2.14.0 in 3 places

### ISSUE THREAD

**Issue by SR-mkuhn** [piwik/piwik#8268]
via http://forum.piwik.org/read.php?2,127703

There seems to happen array to string conversions in 3 places in Piwik 2.14.0:

WARNING: /srv/www/htdocs/piwik/core/Plugin/Report.php(799): Warning - ucfirst() expects parameter 1 to be string, array given - Piwik 2.14.0
```
public static function factory($module, $action):
...
  $api = $module . '.' . ucfirst($action);
...
```
---------------
WARNING: /srv/www/htdocs/piwik/core/Http/ControllerResolver.php(63): Notice - Array to string conversion - Piwik 2.14.0
```
public function getController($module, $action, array &$parameters):
...
   throw new Exception(sprintf("Action '%s' not found in the module '%s'", $action, $module));
...
```
---------------
WARNING: /srv/www/htdocs/piwik/core/Http/ControllerResolver.php(132): Warning - substr() expects parameter 1 to be string, array given - Piwik 2.14.0
```
in private function isReportMenuAction($action):
...
   $startsWithMenu = (Report::PREFIX_ACTION_IN_MENU === substr($action, 0, strlen(Report::PREFIX_ACTION_IN_MENU)));
...
```
---------------

Greetings
mkuhn

**Comment by tsteur** [comment]
When does it happen? Can you let us know the steps to reproduce? Maybe you have a URL? Feel free to remove the domain of the URL and possible token_auth parameters

**Comment by SR-mkuhn** [comment]
This happend during a penetration test via acunetix.

http://example.com/piwik/plugins/Morpheus/plugins/libs/plugins/CoreHome?action[$acunetix]=1&form_login=erssdkay&form_nonce=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&form_password=g00dPa%24%24w0rD&form_password_bis=g00dPa%24%24w0rD&module=Login

This is from the data-field in the piwik-session table:
https://gist.github.com/SR-mkuhn/62934559874a8f2fddcc

**Comment by mattab** [comment]
Hi @SR-mkuhn 
The payload is kinda designed to trigger warning and notices (ie. passing arrays instead of strings) so I don't think we need to fix these.

**Comment by SR-mkuhn** [comment]
But wouldn't it be a security improvement to have a preliminary test if your inputs (and types) are sane?
