### ISSUE TITLE
Loose of data

### ISSUE THREAD

**Issue by marius1512** [piwik/piwik#8270]
Hello,

I am tracking a site with GA and Piwik, but today i had a visitor that was recorded on Analytics but not in piwik, and I'm not saying about only one pageview, it's all the session. In Analytics i saw that visitor's info and browser was a long rare string (7331230CB97FADECF05283E84ED2F4BE) and OS is (not set). 

I think is a bug of piwik, as that visitor is not recorded in database and any interaction of that visitor and it could be because some data are private or not set. 

Can tell me if this is a real scenario? Is there any solution to this bug?

Thank you!

**Comment by mattab** [comment]
Hi @marius1512 

we're having a similar discussion in the forums, check out this post: http://forum.piwik.org/read.php?2,127765,page=1#msg-128233

maybe you can join this conversation if it's relevant?

Cheers
