### ISSUE TITLE
What are the proxy header settings for nginx?

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#8271]
I'm reverse proxying from [an https site](https://idorecall.com) to a Piwik installation for a domain without an SSL cert:

```
location /piwi {
    rewrite ^/piwi(/?.*)$ $1 break;
    proxy_set_header Host piwik.idorecall.com;
    proxy_set_header X-Real-IP $remote_addr;  # TODO Piwik doesn't know about this cache header, so all requests appear as from this very server
    proxy_pass http://piwik.idorecall.com;
}
```

I've read [How do I configure Piwik when the server is installed behind a proxy?](http://piwik.org/faq/how-to-install/#faq_98) but didn't manage to figure out what the exact settings should be for nginx. Now because of the proxying, Piwik tracks all visits as coming from the server that hosts the app.

**Comment by halfdan** [comment]
@dandv You need to make Piwik aware of the `X-Real-IP` header. As shown in the FAQ add an entry under `[General]` with `proxy_client_headers[] = X-REAL-IP`

**Comment by tsteur** [comment]
Is this issue resolved?

**Comment by halfdan** [comment]
Closing as solved. @dandv reopen if there are open questions.
