### ISSUE TITLE
Announcement: Piwik meetup in Berlin, Germany. You are invited!

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8278]
Dear Piwik Community, 

We’re delighted to invite you to our third **FREE Piwik Community Meetup, held in Berlin on Tuesday, the 4th of August, 2015.**

Connect with other users and meet the core team behind Piwik. We will cover some of the upcoming features, discuss the future of Piwik, share tricks and hacks to help you get the most out of your Piwik platform, and socialise.

Please find more information on our blog: https://piwik.pro/2015/06/piwik-community-meetup-berlin-2015/

We hope to meet you there!

**Comment by sgiehl** [comment]
:+1:

**Comment by mattab** [comment]
Read the Piwik meetup report by @MagicFab: [A *hot* Piwik Community Meetup 2015!](http://piwik.org/blog/2015/08/notes-piwik-community-meetup-2015/) :tada:
