### ISSUE TITLE
iOS visitors not counted in real time API

### ISSUE THREAD

**Issue by orenk86** [piwik/piwik#8280]
Hello,
First of all, great analytics system! Keep up the good work!!!

I've been using Piwik for a little over 6 months now, and everything has been working smoothly, till just recently when we switched to a different machine and updated to the latest Piwik release.
We use the real-time API to track the amount of unique visitors on our iOS app and site at any given moment, according to different segments.
The events from both the website and the iOS app are being registered correctly and seem to look the same, but for some reason the real time API only counts the visitors from the website.

I have opened an issue in the [iOS SDK repository](https://github.com/piwik/piwik-sdk-ios/issues/75) as well to try and pinpoint the problem.
Are there any plugins needed to be installed on the Piwik server for this to work? Or perhaps some configuration I might have missed?

Thanks!

**Comment by tsteur** [comment]
There is no plugin required. Do you see any visitors at all? 

Do you mind asking this question in the Support forum? http://forum.piwik.org/list.php?2 

We do not provide support via Github issues as we only manage bugs / features that way. Maybe also provide information re your used Piwik version, whether you use the same "Website" for your website and mobile app or different one?

One rough thought that comes to my mind could be that you maybe use an HTTPS Piwik url with an invalid certificate maybe?

**Comment by tsteur** [comment]
Also mention whether you can see them in the UI, maybe it's just a problem with how to use the API?

**Comment by orenk86** [comment]
Thanks for the feedback and suggestions, I just want to make sure I'm doing things correctly. I will definitely take this to the support forum. To answer your questions:

Yes, I can see a new visitor on the Piwik dashboard while using the iOS app, all of the visitors' params seem to be in place.
The Piwik URL is HTTP, and definitely the same on both the app and website (it's taken from a config JSON we hold on our backend). If I open the website in my web browser as well, I will see 2 visitors, and the events they send (the ones that I poll with the real time API) seem to be the same, according to the Piwik dashboard.

But if I have the app + website open (2 visitors on the dashboard), both sending the same event at the same time, and I issue a call to the real time API with the event params in the segment - I get back 1 unique visitor.
All events sent by both clients are shown in the "visitors in real time" section of the dashboard, get registered in the "events" section correctly, and don't seem to differ between the clients. I'm starting to run out of ideas as to what I'm missing....

Anyhow, I'll take this issue to the support forum. Thanks again!
