### ISSUE TITLE
Reports do not persist columns to display

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8284]
Eg when going to http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=Goals&action=index&idSite=7&period=day&date=yesterday and changing the metrics to display in the evolution report.

> &lt;div class='alert alert-danger'>&lt;strong>Error:&lt;/strong> Setting parameters columns_to_display is not allowed. Please report this bug to the Piwik team.&lt;/div>

It should save the columns to display. Background: The saved view params save the "last state" of a report so when opening the report at a later time it can restore that state. Eg when selecting different columns to display, the next time I open that report the same columns should be displayed again and not the default columns

**Comment by mattab** [comment]
Thanks @tsteur for the report!
