### ISSUE TITLE
UserCountryMap plugin shows wrong options in countries select

### ISSUE THREAD

**Issue by parruc** [piwik/piwik#8285]
In country select I found a non-working option
```html
<select class="userCountryMapSelectCountry">
...
<option value="undefined">European Union</option>
...
</select>
```

To avoid this I patched visitor-map.js adding the if that excludes undefined isos
```javascript
                        // populate country select
                        $.each(countryData, function (i, country) {
                            if ( country.iso )
	                            countrySelect.append('<option value="' + country.iso + '">' + country.name + '</option>');
                        });

                        initUserInterface();

```

**Comment by mattab** [comment]
Hi @parruc 

Thanks for the report.

I can't find "European union" in maps country selector on demo.piwik.org - but there are other "undefined" countries. Here is the full list 

```
<select>
[...]
<option value="undefined">Anonymous Proxy</option>
[...]
<option value="undefined">Satellite Provider</option>
[...]
<option value="undefined">Unknown</option>
<option value="undefined">Unknown</option>
<option value="undefined">Unknown</option>
[...]
</select>
```

The goal of this issue is to remove "undefined" entries from the Map selector.

**Comment by parruc** [comment]
A temporary patch would be the one I wrote on the first post adding:

```php
if ( country.iso )
```
works for me.

I did not open a pull request because It looks like a dirt solution but if you approve I'll open it.
