### ISSUE TITLE
Tracking Internal Site Search tracks only the first query parameter that matches the URL

### ISSUE THREAD

**Issue by jpthompson23** [piwik/piwik#8287]
Under the "Tracking Internal Site Search" section of the "Websites Management" page I entered the list of query parameters: "q, fq"

If I perform a site search on my site, the query URL looks like this:
/select?q=\*%3A\*&fq=case%3A1

See, in the URL I have both parameters "q" for query and "fq" for filter query.  I need to track both of these parameters, but Piwik only tracks the first one in my list that matches the URL, so it only tracks the search "q=\*:\*" in this instance.

Can I track both "q" and "fq"?

**Comment by mattab** [comment]
Hi @jpthompson23 

> Can I track both "q" and "fq"?

No it's not possible. Piwik will track only one site search term. You can however manually track your two search terms by using the [Javascript tracking API](http://developer.piwik.org/api-reference/tracking-javascript) function `trackSiteSearch(keyword, [category], [resultsCount])`
