### ISSUE TITLE
Display total number of actions across all websites

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8288]
The goal of this issue is to improve Piwik to let user access the total number of actions across all websites in Piwik. This would be especially useful for [Piwik Cloud](http://piwik.pro/cloud) where clients are invoiced based on total number of actions.

### Current behavior

 * It is difficult to even get total Actions for a given website. 
  * In Visitors> Overview one can get "Actions per visit" (but not "Actions")
 * in "All Websites" dashboard, one can see the total number of pageviews across all sites (but not "Actions")

![all sites](https://cloud.githubusercontent.com/assets/466765/8555559/26fae57e-24f1-11e5-88f7-80f955684dbf.png)

### Suggestions
 * We could let user customise columns in All Websites dashboard #2390 and let user display "Actions" column.
   * the All websites summary at the top would show the total actions across all websites.

Maybe you have some other thought?

**Comment by MagicFab** [comment]
Piwik 2.14.0 released today now detects HHVM appropriately. See:

- https://piwik.org/changelog/piwik-2-14-0/
- https://github.com/piwik/piwik/pull/8131

**Comment by mattab** [comment]
From feedback:

> This should also be useful as a reference point to diagnose / anticipate hardware upgrade needs (in self-host scenarios) or cloud-migration opportunities.(not only costs for invoicing)

**Comment by mattab** [comment]
> Another option might be to add "Upgrade" section under "Administration". We can display not only the usage in actions per month for last X months, but also options and benefits that user get by upgrading to Cloud or Enterprise

**Comment by mattab** [comment]
This is really high value for us, so targetting for 2.15.0 - we will need to find a solution, either a quick fix (display the number somewhere in the UI), or the more complicated - but terribly awesome - feature of letting users customise columns on All Websites dashboard:  #2390

**Comment by quba** [comment]
What about goal conversions? Should we add this to the total sum? For sure conversions generate additional hits to the tracking server.

**Comment by mattab** [comment]
> What about goal conversions? Should we add this to the total sum?

Actions do not include Goal Conversions as such.

**Comment by mattab** [comment]
> What about goal conversions? Should we add this to the total sum?

Actions metric does not include Goal Conversions. 

Goal conversions are stored separate of Actions. maybe we want to count Goal Conversions to calculate Cloud pricing, but it won't count as "Actions" from Piwik side. I looked into TrafficMonitor plugin and it looks like currently we only use Actions to determine billing. Maybe we will need to rename "Actions" from Piwik PRO side and call it "Billable actions" or something better...
