### ISSUE TITLE
Apache Error 500 in case of Detected browser engine was not found in $availableEngines

### ISSUE THREAD

**Issue by anchalaggarwal** [piwik/piwik#8289]
Hi,
Recently I have been getting error 502 while importing logs in piwik using log-import.
In apache error logs, only thing written was "Detected browser engine was not found in $availableEngines".
On further debug, I found the same is an exception thrown in the below code file 
`vendor/piwik/device-detector/Parser/Client/Browser/Engine.php`
On logging the engine received by Engine.php, it came out to be Edge which is missing in the array `$availableEngines.
    protected static $availableEngines = array(
        'WebKit',
        'Blink',
        'Trident',
        'Text-based',
        'Dillo',
        'iCab',
        'Presto',
        'Gecko',
        'KHTML',
        'NetFront',
    );`
Adding **'Edge'** to the array has resolved the issue.
This looks like a bug since in yaml and regex, Edge is defined.

**Comment by mattab** [comment]
Hi @anchalaggarwal 

Do you know by any chance the log file line that can reproduce this bug? it would be great to be able to reproduce such problem so we could fix it. thanks for sending more info if possible.

ping @sgiehl

**Comment by sgiehl** [comment]
That's an error in device detector. I'll fix that.

**Comment by sgiehl** [comment]
fixed in https://github.com/piwik/device-detector/commit/984725994f75ddb663caa0bbfef0798862afd23b

**Comment by mattab** [comment]
Thanks @sgiehl :+1:  could you update Device detector used in Piwik so we have the fix in 2.14.1?

**Comment by sgiehl** [comment]
Still working on some other improvements. But I'll release a new version
the next days...

**Comment by mattab** [comment]
Perfect! it will be 1 week at least until 2.14.1 so we have some time

**Comment by anchalaggarwal** [comment]
Hi @mattab, thanks for accepting the bug and its solution.
