### ISSUE TITLE
CLI plugin generator doesn't intercept plugin description

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#8294]
Goal of this issue is to fix glitch, where CLI task generating plugin is ignoring plugin description provided in CLI and replacing it with:
"Piwik Platform showcase: how to create widgets, menus, scheduled tasks, a custom archiver, plugin tests, and a AngularJS component."

Tested on vanilla 2.14.0 version.
Please let me know if I can provide any more info about this.

**Comment by mattab** [comment]
Hi @mgazdzik - thanks for the report, it sounds like an easy bug to fix!
