### ISSUE TITLE
During bulk tracking, return indices of invalid requests

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8296]
If invalid requests are detected during bulk tracking, it would be useful for the indices of these requests to be returned in the response. The log importer could then use this information to display the invalid log lines in a file to help facilitate debugging.

**Comment by quba** [comment]
:+1:

**Comment by mattab** [comment]
It sounds very good idea to display at the end, all log lines that were "invalid". Maybe just before the summary (so the summary is still at very end) ?

**Comment by diosmosis** [comment]
Sounds good to me

**Comment by mattab** [comment]
moved into 2.15.0 as it will help our colleagues to troubleshoot issues, so better not to wait for 3.0.0
