### ISSUE TITLE
Error after update to 2.14.0

### ISSUE THREAD

**Issue by abagshaw** [piwik/piwik#8297]
I tried automatically updating to version 2.14.0 as prompted by piwik this morning. After clicking update automatically the page hung while it was loading and stayed loading for a number of minutes. FInally I just refreshed the page and now I get this error

"Class Piwik\Measurable\Type\TypeManager does not exist"

every time I try to log into Piwik. Nothing is working anymore. Please help!

Thanks! (this has also been posted on Piwik forums but I though this might be a better place to post it)

**Comment by sgiehl** [comment]
Does the file ```core\Measurable\Type\TypeManager.php```exist on your Server?
If not try reuploading Piwik manually.

**Comment by abagshaw** [comment]
No it actually didn't exist - I re-uploaded and everything seems fine now. Thanks!
