### ISSUE TITLE
getVisitorId returns random values when called from a server

### ISSUE THREAD

**Issue by BOUDALIZ** [piwik/piwik#8300]
When I call getvisitorId from a server (the class PiwikTracker is on a remote server), the methods returns random values. It works fine when the class is in the same side wih the client. Howerver, I need to make all work in the server side. What shall i do?

Thanks a lot !!

**Comment by mattab** [comment]
Hi @BOUDALIZ 

getVisitorId reads the visitor ID from the cookie (if it wasn't set with `setVisitorId`), so it can only work when the request is executed by the actual visitor. I don't think we can do better at this stage
