### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_visit.config_resolution' in 'field list'

### ISSUE THREAD

**Issue by Patta** [piwik/piwik#8306]
error

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_visit.config_resolution' in 'field list'

on dashboard widgets after update to 2.14

**Comment by benjaminpick** [comment]
Duplicate of #8304 - see this for a workaround:

http://forum.piwik.org/read.php?2,127838,page=1#msg-127877

(You may need to tweak the table names and remove columns that are already there)
