### ISSUE TITLE
delete old data not working

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8310]
delete old data seems not to work (Piwik 2.14)

used settings:

Delete old visitor logs
- Regularly delete old visitor logs from the database: Yes
- Delete logs older than 1 day

Delete old archived reports
- Regularly delete old reports from the database Yes 
- Delete reports older than: 3 month
- Keep basic metrics: no
- Keep all data for: nothing

Schedule old data deletion 
- Delete old data every: Day
(see attachment)

Done:
- purge now: clicked
- waited for 24h

What happened:
- shown Database size keeps nearly the same
( see also: https://github.com/piwik/piwik/issues/8295 )
- all data is still visible (from about a year, small testing site)

![piwik-data-deletion](https://cloud.githubusercontent.com/assets/5681880/8598099/462960ce-2659-11e5-8636-e3b3c01a9050.png)

**Comment by mattab** [comment]
Hi @hpvd 

* Do you still see old data in Visitor > Visitor log (ie. log data) older than 1 day?
* Do you still see Report data older than 3 months?

**Comment by hpvd** [comment]
Hi @mattab 
indeed "visitor/visitor log" itself seem to be cleaned now!

Maybe I didn't get it / didn't read careful enough:
Is this the only-thing which should be deleted?

Other data is still there, e.g.

Dashboard:
- Visitor over time
- Movers shakers
- Entry pages

Visitors/Overview
Visitors/Devices
Visitors/Software
...

Is this is the way how it should work?
imho would have expected that at least the headline "Schedule old data deletion" and "purge now" - Button would  delete everything

**Comment by mattab** [comment]
>Other data is still there, e.g.

is it also there for data older than 3 months? If you delete old archived data older than 3 months, then it's expected that "Entry pages / Visitors Devices etc." are deleted.

**Comment by hpvd** [comment]
hmmm ok, there is only data left newer than 3 Month.
=> so everything seems to be right?

Is there another way to clean Piwik-Data  complety e.g. all before today?
e.g, for when a testing site is going life?

If not: Having learned this, one only would need to add to these cleaning periods a new item:
"older than today"...

what d you think?

**Comment by mattab** [comment]
Sounds like it's working as expected.

> Is there another way to clean Piwik-Data completly e.g. all before today?

It is possible to do this manually see FAQ: https://piwik.org/faq/how-to/faq_73/

Hope this helps!
