### ISSUE TITLE
Black background after update

### ISSUE THREAD

**Issue by Ruhrpottjung** [piwik/piwik#8313]
After I updated my Piwik from 2.13 -> 2.14 suddenly the background is changed from white to black, what's difficult to read. It doesn't matter if I use Safari or Chrome.
The only thing what's right now white is the menu.

![2015-07-09_11-28-32](https://cloud.githubusercontent.com/assets/13258495/8600901/2874582a-262e-11e5-8c49-14759a04521e.png)

Would be nice if someone can fix that problem.

**Comment by mattab** [comment]
Hi there, 

* when you go to Plugins, then click on Themes, what theme is currently enabled?
* If you go to System check, is the "File integrity" check green?

**Comment by Ruhrpottjung** [comment]
I can see that the bright theme is activated if you mean plugin settings?!

![2015-07-09_11-44-49](https://cloud.githubusercontent.com/assets/13258495/8601198/442137d0-2630-11e5-9d98-083d6bd06ad8.png)

Without the filesystem yes. That say only that a NFS file system is used.

**Comment by mattab** [comment]
What is this "Bright theme" ? maybe that's the problem. can you disable this theme and use our Morpheus theme?

**Comment by Ruhrpottjung** [comment]
Would like to do so, but don't have it. Also don't installed any other theme. That was how it comes when I installed Piwik the first time.

![2015-07-09_11-56-43](https://cloud.githubusercontent.com/assets/13258495/8601437/b13e923a-2631-11e5-974e-f518ffe80a2d.png)

**Comment by mattab** [comment]
This is actually a theme for the CustomOptOut plugin, so it's not what we are looking.

Click on Administration > Plugins then click on "Managing themes". what does this screen show?

**Comment by Ruhrpottjung** [comment]
Thank you that was it, after disable PleineLune it works again. Don't saw on the top that I also could change theme settings under plugins.

![2015-07-09_12-08-56](https://cloud.githubusercontent.com/assets/13258495/8601706/5ef16da2-2633-11e5-93fb-f68ea8985c45.png)

Only ask myself why it switch after the update to the dark theme.
