### ISSUE TITLE
footer scripts not loading after 2.14.0 update

### ISSUE THREAD

**Issue by LFPHBIC** [piwik/piwik#8315]
Hi! I updated to 2.14.0 yesterday (which I somehow didn't notice was a beta update) and now all my footer scripts aren't loading. It's not a lot of visible HTML but it's causing another plugin (My Calendar) to fail. 

Thanks!

Alison

**Comment by mattab** [comment]
Hi @LFPHBIC 
this is not related to Piwik I believe. feel free to ask and provide more info in our forums: http://forum.piwik.org/
