### ISSUE TITLE
Can't load the same page again anymore

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#8319]
It's not possible to load the same page again, if you click the menu item nothing happens.

Surely this was introduced to not let users load the page multiple times, but when i want to reload the `Visitor log` (which has live data) i have now to press F5.

![image](https://cloud.githubusercontent.com/assets/533017/8614303/a743812a-26e8-11e5-84e9-28cf1fd3894c.png)

**Comment by mattab** [comment]
Thanks for the report @ThaDafinser 

 * Expected: when clicking on the already loaded menu item, it should re-load the page again.
 * Got: nothing happens when clicking on currently loaded menu.

**Comment by tsteur** [comment]
I don't think it is a regression, is it? FYI: In https://github.com/piwik/piwik/issues/7822 this is already implemented but it won't be released before Piwik 3.0

**Comment by mattab** [comment]
if it's already implemented I'll move this one to 3.0.0 as well :+1: 

(it is a regression, not in 2.14.0 but in an even earlier version - in other words: months ago it used to work)

**Comment by mattab** [comment]
This is the kind of UI details that matter a lot to users :-) it was reported twice recently in http://forum.piwik.org/read.php?2,128544

**Comment by tsteur** [comment]
fixed via #8442 will be available in 3.0
