### ISSUE TITLE
Custom dashboards and visitor segments glitch

### ISSUE THREAD

**Issue by tflo** [piwik/piwik#8323]
There seems to be a glitch with the custom dashboards and segments: 

1. While in a non-custom dashboard I select a visitor segment 
2. With the segment still selected I switch to one of my custom dashboards 
3. I get an error of the type:
```
The segment 'visitorId!%252525253D643eab7c9bf98e9c%252525253BvisitorId!%252525253D9dbcda4866eaca8b%252525253BeventAction!%…' is not valid
```
[Ellipsis added.]

or… 

1. While in a custom dashboard I select a visitor segment 
2. With the segment still selected I switch to another custom dashboard 
3. I get an error of the type:
```
visitorId is expected to be a 16 hex char string
```
In both cases the error goes away when I deselect the segment and then reselect it (still in the same dashboard). 

So it appears that not my segment is faulty but something with the custom dashboards.(?) 

The error does not appear when switching (with a segment selected) from one non-custom dashboard to another non-custom dashboard, or from a custom dashboard to a non-custom dashboard.

Piwik 2.14.0 (was also in previous releases and betas). 

Tom

[from the [forum post](http://forum.piwik.org/read.php?2,127818,page=1#msg-127818)]

**Comment by mattab** [comment]
Hi @tflo - thanks for the report!

which browser did you use to reproduce the issue?

**Comment by tflo** [comment]
Safari 9.0. But I just tested it with Firefox 39.0 and Opera 30.0, and it’s the same.

I tested the referenced scenario #8077 (Visitor Log & date range & segment): no problem here.

Please note that the errors I described only happen when switching either 1) from a built-in dashboard to a custom dashboard (the 'not valid' error), or 2) from a custom dashboard to another custom dashboard (the '16 hex char' error).

**Comment by mattab** [comment]
Hi @sgiehl maybe you could investigate this issue? would be a nice one to have fixed :-)

**Comment by sgiehl** [comment]
I'm able to reproduce it when creating a new dashboard. Seems to be a double url encode in some cases. I'll try to investigate why...

**Comment by mattab** [comment]
@tflo can you please try again with latest Piwik beta 12 ? it hopefully was fixed  with  #8805

**Comment by sgiehl** [comment]
Did a small tests on the case where I was able to reproduce before, it seems to work with latest version. Hopefully @tflo can confirm it is fixed.

**Comment by tflo** [comment]
It’s fine here, too. Thanks for the fix!
