### ISSUE TITLE
Exclude low population works only with flattened reports

### ISSUE THREAD

**Issue by quba** [piwik/piwik#8325]
Please compare these 2 URLs:
http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=XML&idSite=7&period=day&date=2015-07-10&token_auth=anonymous&filter_limit=-1&flat=0&filter_excludelowpop=nb_visits&filter_excludelowpop_value=134

and 

http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=XML&idSite=7&period=day&date=2015-07-10&token_auth=anonymous&filter_limit=-1&flat=1&filter_excludelowpop=nb_visits&filter_excludelowpop_value=134

This filter should work in both cases as there is a row with 134 visits.

**Comment by mattab** [comment]
duplicates #8324
