### ISSUE TITLE
custom theme no longer compatible with piwik 2.14

### ISSUE THREAD

**Issue by propertunist** [piwik/piwik#8326]
i made a theme for piwik for my own site which just consists of a .less file. it has worked fine up until 2.14. now i see: The following plugins are not compatible with Piwik 2.14.0 and could not be loaded: my_theme_name.

does anyone know what the problem is? i haven't seen any mention of what might be causing this. thanks

**Comment by propertunist** [comment]
this was due to an error in my theme's css file that for some reasons didn't cause a problem with the earlier versions of piwik (a spurious semi-colon was present).

**Comment by mattab** [comment]
Fyi: it started failing because we upgraded the LESS PHP compiler which became more correct

**Comment by propertunist** [comment]
oh ok, thanks for the info :)
