### ISSUE TITLE
Here you can see what feature is missing and what feature is generall

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#8332]
https://clicky.com/compare/piwik

I distributed this link to every piwik developer to read through 
and compare with the piwik roadmap.

this is the hard truth.

from this point start to think hughe

**Comment by sgiehl** [comment]
Well, those compares are always a bit one sided. For sure they would never
list features piwik has, but they haven't. In addition that compare was
last updated end of 2013, so it is a bit outdated. piwik already has some
of that features such as video analytics.

**Comment by mattab** [comment]
Hi @Tobias-Conrad 

Forums would be good place to discuss this, here this is our issue tracker where we keep track of bugs and feature requests, and we create one issue per idea or bug.

**Comment by Tobias-Conrad** [comment]
I see. sorry.

@mattab which forum? may just also create a comparison table.
piwik, analytics, clicky, ... give it the marketing guy please.
@sgiehl video analytics is on the roadmap and not easy to implement at the moment.
Or m i wrong? I need youtube video tracking.

**Comment by sgiehl** [comment]
http://forum.piwik.org

Haven't done much with video analytics. So I can't tell you how to do that.

Btw. If we should ever create and publish such a comparison I would suggest to also include features we do not have implemented. And for sure we should not use some of the wording clicky does.
Stuff like "Industry's best spam / bot filtering" or "The best bounce rate metric in the biz" are cocky...
