### ISSUE TITLE
wrong tracking data

### ISSUE THREAD

**Issue by PeziBuu** [piwik/piwik#8340]
Hello community, 

I got a huge problem and can't find the issue. We had a database crash 5 weeks ago. We had a backup, but it wasn't complete. Some tables were missing. After searching the repository, we found the tables and insert them to the database. The Piwik installation is still the same. No data was lost, but since we restored everything, Piwik tracks each visitor, which opens a new page as a new visitor. So basicly each link click is a new visitor. 

We use the version 1.12 at the moment.

I think it is a problem with the cookie. When i open my Website, the _pk_id... cookie gets always, after i go to another page or refresh the page, a new timestamt. This means, the ID cookie is created new each time i open a page. 

My clue is, that something is missing in the database, which tells, that a visitor is the same or not. Do you have any clue what could be missing? 

I made a second Piwik installation with a new database. The tracking on this installation is right. Means, the cookie doesn't get a new timestamt each visit. 

If you need more information, let me know and i will post them asap. 

Thanks for help and I hope we can solve the issue fast!

**Comment by mattab** [comment]
Hi there,

> We use the version 1.12 at the moment.

This is the problem, please upgrade to latest Piwik and I think this issue will be fixed. if you still have some problem, let us know
