### ISSUE TITLE
Piwik not running in Phonegap Apps

### ISSUE THREAD

**Issue by mayurr87** [piwik/piwik#8341]
I am using piwik to find analyse on website have got the js code from setting option of the piwik.

						
script type
  var _paq = _paq || [];
  _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
  _paq.push(["setCookieDomain", "*.techforum-worldline.rhcloud.com"]);
  _paq.push(["setDomains", ["*.techforum-worldline.rhcloud.com"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  _paq.push(['appendToTrackingUrl', 'bots=1']);
  (function() {
    var u="//piwik-techforumatos.rhcloud.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();

<p><img src="//piwik-techforumatos.rhcloud.com/piwik.php?idsite=1" style="border:0;" alt="" /></p>

Have pasted above code just above </body> tag.

Above code working properly and on dashboard of the piwik getting stats also but same thing via cordavo android apk it's not working. Site is working properly on mobile via apk but call to the piwik not going.

What's wrong there? JavaScript is enabled. Is there a known problem.

Inside config.xml:

access origin="*"

already in place.

**Comment by tsteur** [comment]
Just a guess, maybe instead of `var u="//piwik-techforumatos.rhcloud.com/";` try `var u="http://piwik-techforumatos.rhcloud.com/";` or `https://...`

**Comment by tsteur** [comment]
If it doesn't work, it would be great if you could remote debug your PhoneGap app and let us know if there are any errors

**Comment by mayurr87** [comment]
Bravooo!!!!......Thanks a lot...

var u="http://piwik-techforumatos.rhcloud.com/"; works for me...

Searched a lot for this and final you helped. hope on next version piwik site will give the proper js code. because its very difficult to debug third party lib.

**Comment by mattab** [comment]
@tsteur do you reckon we should do something to prevent such issues in the future (product improvement, or otherwise a FAQ maybe?)

**Comment by tsteur** [comment]
Was thinking about this as well. Not sure what best solution would be. If we had a type "PhoneGap App" (similar to type Mobile App or Intranet) then we could generate the tracking code differently based on that but it will maybe not happen that we have such a type. 

An option in the tracking code generator is maybe too much as only a very few sites are actually PhoneGap apps. Maybe a FAQ entry? But this will be hard to find. Not sure what to do. FAQ seems like easiest solution for now.

**Comment by mattab** [comment]
Created FAQ: [How do I track a Phonegap app with Piwik?](https://piwik.org/faq/how-to/faq_20304/)
