### ISSUE TITLE
Warning - No such file or directory

### ISSUE THREAD

**Issue by paulomartinhago** [piwik/piwik#8344]
Hello!

I'm having a problem when access the menu "All Websites", is returning me the following error:

WARNING: /home/emidsite/public_html/_subdominios/piwik/plugins/CustomVariables/Archiver.php(19): Warning - require_once(/home/emidsite/public_html/_subdominios/piwik/libs/PiwikTracker/PiwikTracker.php): failed to open stream: No such file or directory - Piwik 2.14.1-b1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by sgiehl** [comment]
Please try to reupload Piwik manually. That file should be present and is available in the package.
