### ISSUE TITLE
node.className.split is not a function on tracking click on/near SVG element

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#8346]
I've created a mirror of our signup page where we experience this error. Steps to reproduce:

1. Go to https://idorecall.com/static/bug-demos/piwi-classname.split/
2. Enter some email
3. In the signup success page, click on the "F"acebook link/icon.

After a few seconds, the Chrome console displays

    piwi.js:1390 Uncaught TypeError: node.className.split is not a function

The piwik.js is [from July 1st](https://github.com/piwik/piwik/blob/10124dd4b4cb4afe3df7850d53e5f9f39e680d15/js/piwik.js) and the line in question is [`var classes = node.className.split(' ');`](https://github.com/piwik/piwik/blob/10124dd4b4cb4afe3df7850d53e5f9f39e680d15/js/piwik.js#L1390)

The error occurs despite the checks for presence of `className` because the element in question is an SVG `<use>` and node.className is `SVGAnimatedString {}`. My markup is

```html
<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A//iDoRecall.com/?signupref">
  <svg>
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fa-facebook"></use>
  </svg>
</a>
```

http://stackoverflow.com/questions/12588913/svganimatedstring-missing-method-indexof suggests a possible solution.

A workaround is to add bogus classes to `<svg>` and `<use>` elements in the markup.

**Comment by mattab** [comment]
Thanks for the report, the pull request is #8347
