### ISSUE TITLE
Use the nice designed tooltips for all tooltips in Visitor Log

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8356]
In Visitor Log (and maybe other features?) there are tooltips displayed using the default browser tooltip.

These tooltips are problematic because:
 * they take a few seconds to appear so it's not usable - we have to wait a few second to get the information
 * they are not consistent with our black background tooltips

Example:

![visito rlog](https://cloud.githubusercontent.com/assets/466765/8698245/8bf6eb38-2afc-11e5-89ba-2bac252443b4.png)

Steps
 * Look for all places in Visitor log / visitor profile / real time visitor log, where tooltips are used, 
 * Replace them with the designed tooltips 
 * Have a look around for other tooltips that we could also replace

**Comment by mnapoli** [comment]
PR: #8545
