### ISSUE TITLE
Flag-Symbol missing using PHP-Tracker

### ISSUE THREAD

**Issue by typoworx-de** [piwik/piwik#8359]
I've been trying to use the PHP-Tracker API (with API-Key usage) and noticed that all flag-symbols are missing (replaced by question-mark icon). The mouseover correctly shows the country for all incoming tracks and PHP-GeoDB is correctly setup using maxMind GEO-DB. Also the live-tracking map correctly shows the visits for the countries.

All other Piwik-Accounts using the usual JS-Tracking are working fine and there are no problems with the flag-symbol shown in the tracking-stats.

Are there any suggestions?

Btw. is it possible to combine JS and PHP-Tracking f.e. to track special events using JS on client-side or would this lead to double-tracked visits?

Best regard
Gabriel

**Comment by mattab** [comment]
Hi @typoworx-de 

can you paste here the output of `Live.getLastVisitsDetails` API for one of your PHP tracked visitor? Especially interested in the `countryCode` attribute and whether it's set correctly.


> Btw. is it possible to combine JS and PHP-Tracking f.e. to track special events using JS on client-side or would this lead to double-tracked visits?

It would lead to double tracked visits.

**Comment by mattab** [comment]
@typoworx-de please re-open if you still have issue with latest Piwik beta: piwik.org/faq/how-to-update/faq_159/

**Comment by schelmo** [comment]
For the people who have also this problem:
the country code must be lowercase
as mentioned here:
https://developer.matomo.org/api-reference/tracking-api#other-parameters-require-authentication-via-token_auth
