### ISSUE TITLE
Clear opcache when installing plugins

### ISSUE THREAD

**Issue by oparoz** [piwik/piwik#8362]
On PHP 5.5, using PHP-FPM, the gateway becomes unavailable as soon as a plugin is installed, until PHP-FPM is either restarted or the opcache cleared.
No problem with PHP 5.4 + APC.

Would it be possible to add some opcache clearing code to the installer?

**Comment by quba** [comment]
There's already a command to clear all caches. Could you check if it works? If yes, then it should be easy to implement.

**Comment by mattab** [comment]
It looks like the cache is already cleared when installing a new plugin: https://github.com/piwik/piwik/blob/master/plugins/CorePluginsAdmin/PluginInstaller.php#L49-50

Maybe it does not work for you. can you try the following:
- install a new plugin
- check your server is unavailable
- run `./console cache:clear` in Piwik folder
- is Piwik now available?

**Comment by mattab** [comment]
Should already work. If you still have the problem with 2.14.3 or 2.15.0 beta (http://piwik.org/faq/how-to-update/faq_159/), feel free to re-open
