### ISSUE TITLE
No Tracking

### ISSUE THREAD

**Issue by Trance-Man** [piwik/piwik#8364]
Since the last Piwik update I have ZERO tracking for my website, nothing is working, can someone find out why?

**Comment by ChristianGfK** [comment]
Probably the same issue as https://github.com/piwik/piwik/issues/8304.

**Comment by mattab** [comment]
Hi @Trance-Man 

 *  enable Tracker debugging: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker 
 * what is your website URL?

**Comment by Trance-Man** [comment]
If I enable tracker debugging will that screw up my normal use of Piwik, will it change anything that I might not want to change?Website url is http://www.brucecullen.com/piwik/

**Comment by mattab** [comment]
Enabling debugging will not impact your Piwik

**Comment by mattab** [comment]
Please try again with latest beta if you still have a problem: http://piwik.org/faq/how-to-update/faq_159/
