### ISSUE TITLE
Double escaping in the update error message

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#8366]
![image](https://cloud.githubusercontent.com/assets/33569/8744313/07badc46-2c2b-11e5-964f-1b463f2fb9e8.png)

> Update error: Error while creating/copying file to &lt;code&gt;/var/www/piwik/lang/uk.json&lt;/code&gt;. &lt;br /&gt;Please check that the web server has enough permission to write to these files/directories:&lt;br /&gt;For example, on a GNU/Linux server if your Apache httpd user is www-data, you can try to execute:&lt;br /&gt; &lt;code&gt;chown -R www-data:www-data /var/www/piwik&lt;/code&gt;&lt;br /&gt;&lt;code&gt;chmod -R 0755 /var/www/piwik&lt;/code&gt;&lt;br /&gt;

**Comment by mattab** [comment]
Thanks for the report @dandv 

it's related to: #8293
