### ISSUE TITLE
Can't update GrabGravatar plugin

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#8370]
I've just updated to 2.14.1 and when I try to update the GrabGravatar plugin, it seems that the update executes, but the plugin is still marked as being outdated.

Looking in `plugins`, the timestamps of the files are of minutes ago, but the contents are of v0.1.1.

**Comment by tsteur** [comment]
The timestamps of which files are of minutes ago? Does it say the plugin is updated? Which version does it say is installed? Still `0.1.1`? Maybe it was a weird caching problem otherwise it should work. Do you mind trying again?

**Comment by dandv** [comment]
Updating...

![image](https://cloud.githubusercontent.com/assets/33569/8773518/b19f17f8-2e89-11e5-884b-a464aaa16de7.png)

After update, Piwik still has the old version:

![image](https://cloud.githubusercontent.com/assets/33569/8773531/c8ff46ca-2e89-11e5-9f1a-55e70bbf1495.png)

The timestamps of the GrabGravatar plugin files (the .php, `plugin.json`) are from moments ago. But the contents of plugin.json starts with

```
{
 "name": "GrabGravatar",
 "version": "0.1.1",
```

**Comment by tsteur** [comment]
I presume there's a bug somewhere, we might read the wrong field somewhere. The plugin was tagged with `0.2.0` but the version in `plugin.json` is `0.1.11` see https://github.com/alnoorp/GrabGravatar/blob/0.2.0/plugin.json

There's also a tag `0.2.1` with version `0.2.0`  see https://github.com/alnoorp/GrabGravatar/blob/0.2.1/plugin.json . We usually ignore the tag and read the version number but possibly there's a bug somewhere. 

@mattab I think it's worth looking into this soonish

**Comment by mattab** [comment]
Good point, added issue to 2.15.0 so we get it sorted before 3.0.0 (where many plugins will need to be upgraded and we want to make sure everything works)

**Comment by tsteur** [comment]
Little update: It's a bug caused by the GitHub library that we use and was fixed here: https://github.com/KnpLabs/php-github-api/commit/fada3f3cf088b332655183517d043eea495f6c50

We always downloaded the archive of the `master` branch so far as this is the default. Since we fetch the data within a minute from the repo this should be usually always the same content unless one tags from another branch (eg `develop`). Will see if we can update the library easily.

**Comment by tsteur** [comment]
@dandv  do you mind trying again? I re-imported the GrabGravatar versions and it should work now. Please comment or reopen in case you still experience this problem
