### ISSUE TITLE
"Evolution over the period" displays a far longer period than the one selected

### ISSUE THREAD

**Issue by dandv** [piwik/piwik#8375]
I've selected last week as the period in the Goals overview tab.

The Evolution chart starts six months back, even though I installed Piwik only ~2 months ago:

![image](https://cloud.githubusercontent.com/assets/33569/8760295/0d7adfd0-2cc8-11e5-8bb1-f7f416c0b8e7.png)

**Comment by mattab** [comment]
Hi @dandv 
It works as intended. Maybe you expected to see the date range currently selected in the graph? This issue will be helpful: #955
