### ISSUE TITLE
core:archive cron error since 2.14.1

### ISSUE THREAD

**Issue by fr33tux** [piwik/piwik#8378]
When the archiving cron task is executed :

`/usr/bin/php5 /var/www/piwik/console core:archive --url=https://piwik.website.net > /var/www/piwik/piwik-archive.log`

I got the following error since upgrading to **2.14.1** :

> ERROR [2015-07-18 23:19:02] Got invalid response from API request: ?module=API&
> method=API.get&idSite=4&period=year&date=last2&format=php&trigger=archivephp. Response 
> was 'PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/piwik
> /core/DataTable/Manager.php on line 105 PHP Stack trace: PHP   1. {main}() /var/www
> /piwik/console:0 PHP   2. Symfony\Component\Console\Application->run() /var/www/piwik
> /console:27 PHP   3. Piwik\Console->doRun() /var/www/piwik/vendor/symfony/console/Symfony
> /Component/Console/Application.php:126 PHP   4. Piwik\Access::doAsSuperUser() /var/www
> /piwik/core/Console.php:80 PHP   5. Piwik\Console->Piwik\{closure}() /var/www/piwik
> /core/Access.php:456 PHP   6. call_user_func() /var/www/piwik/core/Console.php:79 PHP   7. 
> Symfony\Component\Console\Application->doRun() /var/www/piwik/core/Console.php:79 PHP   
> 8. Symfony\Component\Console\Application->doRunCommand() /var/www/piwik/vendor
> /symfony/console/Symfony/Component/Console/Application.php:195 PHP   9. Symfony\Component
> \Console\Command\Command->run() /var/www/piwik/vendor/symfony/console/Symfony
> /Component/Console/Application.php:874 PHP  10. Piwik\CliMulti\RequestCommand->execute() 
> /var/www/piwik/vendor/symfony/console/Symfony/Component/Console/Command
> /Command.php:257 PHP  11. require_once() /var/www/piwik/core/CliMulti
> /RequestCommand.php:79 PHP  12. require_once() /var/www/piwik/index.php:27 PHP  13. 
> Piwik\FrontController->dispatch() /var/www/piwik/core/dispatch.php:34 PHP  14. 
> Piwik\FrontController->doDispatch() /var/www/piwik/core/FrontController.php:94 PHP  15. 
> call_user_func_array() /var/www/piwik/core/FrontController.php:494 PHP  16. Piwik\Plugins
> \API\Controller->index() /var/www/piwik/core/FrontController.php:494 PHP  17. Piwik\API
> \Request->process() /var/www/piwik/plugins/API/Controller.php:37 PHP  18. Piwik\API
> \Proxy->call() /var/www/piwik/core/API/Request.php:238 PHP  19. call_user_func_array() 
> /var/www/piwik/core/API/Proxy.php:211 PHP  20. Piwik\Plugins\API\API->get() /var/www/piwik
> /core/API/Proxy.php:211 PHP  21. Piwik\API\Proxy->call() /var/www/piwik/plugins
> /API/API.php:405 PHP  22. call_user_func_array() /var/www/piwik/core/API/Proxy.php:211 PHP  
> 23. Piwik\Plugins\VisitsSummary\API->get() /var/www/piwik/core/API/Proxy.php:211 PHP  24. 
> Piwik\Archive->getDataTableFromNumeric() /var/www/piwik/plugins/VisitsSummary/API.php:35 
> PHP  25. Piwik\Archive->get() /var/www/piwik/core/Archive.php:324 PHP  26. 
> Piwik\Archive->getArchiveIds() /var/www/piwik/core/Archive.php:598 PHP  27. 
> Piwik\Archive->cacheArchiveIdsAfterLaunching() /var/www/piwik/core/Archive.php:660 PHP  28. 
> Piwik\Archive->prepareArchive() /var/www/piwik/core/Archive.php:708 PHP  29. 
> Piwik\ArchiveProcessor\Loader->prepareArchive() /var/www/piwik/core/Archive.php:894 PHP  
> 30. Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive() /var/www/piwik
> /core/ArchiveProcessor/Loader.php:72 PHP  31. Piwik\ArchiveProcessor
> \PluginsArchiver->callAggregateCoreMetrics() /var/www/piwik/core/ArchiveProcessor
> /Loader.php:116 PHP  32. Piwik\ArchiveProcessor
> \PluginsArchiver->aggregateMultipleVisitsMetrics() /var/www/piwik/core/ArchiveProcessor
> /PluginsArchiver.php:63 PHP  33. Piwik\ArchiveProcessor->aggregateNumericMetrics() /var/www
> /piwik/core/ArchiveProcessor/PluginsArchiver.php:211 PHP  34. 
> Piwik\ArchiveProcessor->getAggregatedNumericMetrics() /var/www/piwik
> /core/ArchiveProcessor.php:256 PHP  35. Piwik\Archive->getDataTableFromNumeric() /var/www
> /piwik/core/ArchiveProcessor.php:549 PHP  36. Piwik\Archive->get() /var/www/piwik
> /core/Archive.php:324 PHP  37. Piwik\Archive->getArchiveIds() /var/www/piwik
> /core/Archive.php:598 PHP  38. Piwik\Archive->cacheArchiveIdsAfterLaunching() /var/www/piwik
> /core/Archive.php:660 PHP  39. Piwik\Archive->prepareArchive() /var/www/piwik
> /core/Archive.php:708 PHP  40. Piwik\ArchiveProcessor\Loader->prepareArchive() /var/www
> /piwik/core/Archive.php:894 PHP  41. Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive() 
> /var/www/piwik/core/ArchiveProcessor/Loader.php:72 PHP  42. Piwik\ArchiveProcessor
> \PluginsArchiver->callAggregateCoreMetrics() /var/www/piwik/core/ArchiveProcessor
> /Loader.php:116 PHP  43. Piwik\ArchiveProcessor
> \PluginsArchiver->aggregateMultipleVisitsMetrics() /var/www/piwik/core/ArchiveProcessor
> /PluginsArchiver.php:63 PHP  44. Piwik\ArchiveProcessor->aggregateNumericMetrics() /var/www
> /piwik/core/ArchiveProcessor/PluginsArchiver.php:211 PHP  45. 
> Piwik\ArchiveProcessor->getAggregatedNumericMetrics() /var/www/piwik
> /core/ArchiveProcessor.php:256 PHP  46. Piwik\Archive->getDataTableFromNumeric() /var/www
> /piwik/core/ArchiveProcessor.php:549 PHP  47. Piwik\Archive->get() /var/www/piwik
> /core/Archive.php:324 PHP  48. Piwik\Archive->getArchiveIds() /var/www/piwik
> /core/Archive.php:598 PHP  49. Piwik\Archive->cacheArchiveIdsAfterLaunching() /var/www/piwik
> /core/Archive.php:660 PHP  50. Piwik\Archive->prepareArchive() /var/www/piwik
> /core/Archive.php:708 PHP  51. Piwik\ArchiveProcessor\Loader->prepareArchive() /var/www
> /piwik/core/Archive.php:894 PHP  52. Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive() 
> /var/www/piwik/core/ArchiveProcessor/Loader.php:72 PHP  53. Piwik\ArchiveProcessor
> \PluginsArchiver->callAggregateAllPlugins() /var/www/piwik/core/ArchiveProcessor
> /Loader.php:122 PHP  54. Piwik\Plugins\Actions\Archiver->aggregateMultipleReports() /var/www
> /piwik/core/ArchiveProcessor/PluginsArchiver.php:112 PHP  55. 
> Piwik\ArchiveProcessor->aggregateDataTableRecords() /var/www/piwik/plugins/Actions
> /Archiver.php:502 PHP  56. Piwik\Common::destroy() /var/www/piwik
> /core/ArchiveProcessor.php:225 PHP  57. Piwik\DataTable->__destruct() /var/www/piwik
> /core/Common.php:1255 PHP  58. Piwik\Common::destroy() /var/www/piwik
> /core/DataTable.php:343 PHP  59. Piwik\DataTable\Row->__destruct() /var/www/piwik
> /core/Common.php:1255 PHP  60. Piwik\DataTable\Manager->deleteTable() 
> ERROR [2015-07-18 23:19:02] 2 total errors during this script execution, please investigate and 
> try and fix these errors.                                                                     
> [Exception]
> 2 total errors during this script execution, please investigate and try and fix these errors.

It was working well with 2.14 and before.

**Comment by mnapoli** [comment]
Hi, please have a look at this FAQ: http://piwik.org/faq/troubleshooting/faq_20014/
