### ISSUE TITLE
Include ova as download extension

### ISSUE THREAD

**Issue by felicitus** [piwik/piwik#8385]
I just noticed that piwik doesn't track downloads of OVA files. It would be good to add custom download files to a configuration file.

**Comment by sgiehl** [comment]
You can do this using ```addDownloadExtensions```.
See http://developer.piwik.org/api-reference/tracking-javascript#configuration-of-the-tracker-object

**Comment by felicitus** [comment]
This only works when using the JS tracker, not for log imports. Please re-open.

**Comment by sgiehl** [comment]
If thats a log importer issue, maybe it's better to create it here: https://github.com/piwik/piwik-log-analytics

Btw. the log importer has the option ```--download-extensions```, but that one overwrites the full list of extensions
