### ISSUE TITLE
The email doesn't have a valid format

### ISSUE THREAD

**Issue by acs-ferreira** [piwik/piwik#8391]
When trying to install Piwik with an email like ````user@mydomain.boutique```` it returns ````The email doesn't have a valid format````.

Of course, email exists and is valid.

**Comment by tsteur** [comment]
FYI: We got an email recently with a similar issue but a `.ovh` domain

**Comment by mattab** [comment]
Hi @acs-ferreira  - thanks for the report.
this is likely a regression from #7298  #8259 - cc @barbushin

**Comment by mnapoli** [comment]
Fixed in #8400
