### ISSUE TITLE
Wrong German translation of website in privacy opt out frame 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8394]
See https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/UIIntegrationTest_admin_privacy_optout_iframe.png

It says "Website" but should be "Webseite". Or is it on purpose? @sgiehl ?

**Comment by sgiehl** [comment]
I changed most of that. **Technical** correct translation for website is "Website".... a "Webseite" would be a single webpage on a website. As far as I have seen we currently use the english word website for both meanings, so it's sometimes hard to consider what it means...

**Comment by tsteur** [comment]
Good point, I just remember I had this on my todo list about a year ago and forgot about it
