### ISSUE TITLE
The string General_Cancel was not loaded in javascript

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#8407]
When creating a new Website in 2.14.1 the cancel button does not show up using English as language. Instead of the button the following message occurs:

The string General_Cancel was not loaded in javascript. Make sure it is added in the Translate.getClientSideTranslationKeys hook.

**Comment by tsteur** [comment]
Thx @iMarkus ! Should work with the next release

**Comment by iMarkus** [comment]
Works again in 2.14.2

Thx
