### ISSUE TITLE
Change signature of Dimension hooks to allow to change them in the future

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8409]
In Dimensions we have some "hooks" / methods that are called during tracking: https://github.com/piwik/piwik/blob/2.14.1-rc1/core/Plugin/Dimension/VisitDimension.php#L216-L252

Same applies to `ActionDimension` and `ConversionDimension` eg 
```
    public function onExistingVisit(Request $request, Visitor $visitor, $action)
    {
        return false;
    }
```

Problem is that we will never be able to change this signature as it might break plugins. Instead we should pass only one object where one can call `$i->getRequest()`, `$i->getVisitor()`, ... It is not as nicely readable etc but it will allow us to change code in the future and provide more parameters.

We potentially have similar issues with other classes too, eg `Reports::configureWidgets()`. Those would be ideally changed too. We should do this for 3.0.0 as it will break the API

**Comment by mattab** [comment]
Since we do a LTS release #8546 and we will change our release cycle #8547 - we do not need this anymore
