### ISSUE TITLE
Stable branch ?

### ISSUE THREAD

**Issue by acs-ferreira** [piwik/piwik#8414]
When [deploying from git](http://piwik.org/faq/how-to-install/faq_18271/) we deploy ````master```` branch which is not suitable for production for many reasons.

Wouldn't it be production friendly to have a ````stable```` branch from where we could ````pull```` from for production environments ?

**Comment by tsteur** [comment]
See the FAQ article we do not recommend to deploy from git, especially not in production. Therefore, I reckon, we won't add a `stable` branch to make it more production friendly. 

We always tag a new stable version when there's a new release but the name obviously always changes (as the name is the version number) and isn't `stable`. You could write a little script to read the latest tag automatically. Eg Git 2.0 supports something like `git tag --sort=version`. If you do, feel free to share it by adding a comment and we can put it in the FAQ entry.
