### ISSUE TITLE
"Link to an external website" goal not working as expected

### ISSUE THREAD

**Issue by ktecho** [piwik/piwik#8416]
I have set up a goal. The goal should be triggered "when visitors" / "Click on a Link to an external website". I have chosen "contains" and the pattern is "facebook.com/sharer", because I want to track if user clicks href="https://www.facebook.com/sharer/sharer.php?u=https://xxxxxxxxxxxxxxx".

I was very happy knowing that I was converting goals, but it's converting false positives, as goal is being converted on pages where there's not such link.

I'm seeing the conversions when passing from the first page to the second of these two pages:

https://www.aalquilar.es/
https://www.aalquilar.es/inquilinos/

As you can see, there is no "facebook.com/sharer" url at any place, so it's impossible for my users to trigger the goal.

**Comment by mattab** [comment]
Hi @ktecho 
could you paste screenshot from your Piwik showing the "wrong" data?

**Comment by ktecho** [comment]
Hi Matthieu,

I stopped using Piwik because of this and other problems, and no support
(this ticket being answered after one month, by example). So I cannot help
with this, sorry.
