### ISSUE TITLE
slash error

### ISSUE THREAD

**Issue by efenguo** [piwik/piwik#8421]
when I tried to add a new plugin clickheat, there is an error:
The class ClickHeat couldn't be found in the file 'C:\Bitnami\wampstack-5.5.25-0\apache2\htdocs\piwik/plugins/ClickHeat/ClickHeat.php'

Obviously a slash error happened.

I am using Piwik in Windows platform.

**Comment by sgiehl** [comment]
As that seams to be a problem with the plugin. Maybe create an issue there: https://github.com/piwikjapan/plugin-clickheat
