### ISSUE TITLE
Track location change as new visit

### ISSUE THREAD

**Issue by pebosi** [piwik/piwik#8423]
Would be nice to track a new visit every time the location of a other has changes (based on lat, long).

I'm using Piwik for mobile tracking of users and need to split visits of one user to different locations.
Even if i modify lat, long, city paramerts in tracking request, the visit stays the same and i cant see the location changes.

**Comment by quba** [comment]
It's rather something that can be achieved with custom plugin.

**Comment by pebosi** [comment]
i just did see that lat, lon, city requires token_auth... i will try and report back here.

**Comment by pebosi** [comment]
Ok, it now just overrides the visits lat, lon, city values. So would be nice to get a new visit instead

**Comment by Fensterbank** [comment]
But isn't it technically wrong, to log a location change as a new visit?
If a user is visiting a website and reading some articles while driving on the speedway, the user sould not be tracked with multiple visits.

**Comment by mattab** [comment]
Thanks for suggestion @pebosi 

Notes:
 * we do something similar, we track new visit on new campaigns, and/or website changes, see this faq  [How do I create new visit whenever a user visits my website using a new campaign or a new website referrer?](https://piwik.org/faq/how-to/faq_19616/)
 * you can also manually track a new visit whenever you want, with `new_visit` tracking API parameter, [see this FAQ](https://piwik.org/faq/how-to/faq_187/)
 * we won't add this feature for location change in core.
