### ISSUE TITLE
During tests, if a plugin has dependent plugins, they should be loaded automatically

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8428]
As title. It shouldn't be required to explicitly add the plugins to the activated plugin list.

**Comment by mattab** [comment]
Hey @diosmosis 

is there particular reason this was scheduled for 2.15.0? maybe we can move it to 3.0.0 and groom it on thursday's meeting.

**Comment by diosmosis** [comment]
It makes testing a lot more problematic since the dependent plugins have to be explicitly listed somewhere so they will be loaded for tests. I wanted to change this before the next plugin build fix.

**Comment by mattab** [comment]
as we currently don't have this "plugin requires other plugin" feature, closing
