### ISSUE TITLE
Bug in fresh install on Piwik 2.14.2 - WriteAccessCheck.php and piwik/config path check

### ISSUE THREAD

**Issue by labiloute** [piwik/piwik#8441]
Hi,
Little typo I'd say in the "plugins/Diagnostics/Diagnostic/WriteAccessCheck.php" file on a fresh install.
Replace:
$directoriesToCheck[] = 'config/';
by
$directoriesToCheck[] = '/config/';

Or the checked path will be for example : /var/www/piwikconfig

Cheers !

**Comment by mnapoli** [comment]
Thank you, it duplicates #8439.

**Comment by labiloute** [comment]
Sorry for duplicate, #8439 title was not very explicit, so I did not find it searching for piwikconfig keyword

**Comment by mnapoli** [comment]
I have updated the issue title so that it's more explicit.
