### ISSUE TITLE
Running tests on a virtual domain after setting [tests] http_host doesn't always work

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8447]
As title. If `[tests] http_host` is set to a virtual domain, Piwik will assume the host is `'unknown'` for some reason. May only affect enterprise plugins.

CC @sebastianpiskorski

**Comment by mnapoli** [comment]
Maybe related, I had to do this in my Docker branch: https://github.com/piwik/piwik/commit/2bbee201828157d4c4a3dfcc38da892ce74b4e77

The change basically auto-updates the `tests/UI/config.js` file which is necessary for UI tests (and that is easy to forgot).

Also had to do this fix: https://github.com/piwik/piwik/commit/cbf4f9208a9d32ba805b62dfd42553753067888a

FYI this is all currently on a separate branch.

**Comment by mattab** [comment]
@mnapoli could you move your two commits in a separate PR? these look like fixes we should have in core  independantly of docker branch :+1:

**Comment by mnapoli** [comment]
@mattab will do, so we are sure it will fix this issue?

**Comment by mattab** [comment]
we don't know yet, but  @sebastianpiskorski will be able to test it when he next has a chance :+1:

**Comment by mnapoli** [comment]
PR is here: #8552

**Comment by diosmosis** [comment]
@sebastianpiskorski do you still experience this issue w/ Piwik master? Does the change @mnapoli made fix the problem?

**Comment by sebastianpiskorski** [comment]
Well I didn't have need to run tests locally recently,especially that now we are working on 2.14 and as I see this fix is for 2.15.

**Comment by diosmosis** [comment]
@sebastianpiskorski would you have time to do a test quickly? ie `git checkout master && ./console tests:run --file=/path/to/test/that/failed/before`. Do you also remember which test caused the problem?

**Comment by sebastianpiskorski** [comment]
@diosmosis It is not that simple and I don't believe I have this configuration anymore. As far as I remember it was the UI tests. I'll check that.

**Comment by sebastianpiskorski** [comment]
@diosmosis I still get failure with fixture setting

```
Failed to setup fixture: Expected GIF beacon, got: <br/>
''
 If you are stuck, you can enable [Tracker] debug=1; in config.ini.php to get more debug info.
 ===========================
 URL was: http://unknown/tests/PHPUnit/proxy/piwik.php?(...)
```

**Comment by diosmosis** [comment]
Found the issue. It's a problem w/ a specific plugin. Closing this issue.
