### ISSUE TITLE
Segmenting on page URL or Title not working

### ISSUE THREAD

**Issue by joelanman** [piwik/piwik#8450]
Using Piwik 2.8.3-1

On our project we've set up an AB test, where a page we think might be a problem is skipped for A and not for B. 

The A journeys trigger a virtual page view on Piwik (say "skipped page" ) , but when we segment on [Page name is " skipped page"] the only page these users see according to the report is "skipped page" - no other pages in their journeys are shown. 

Segmenting on page title/url in general doesn't seem to be working. It's as if you just ran a search on title/url: the page you search for appears, but no other pages on the journey, which is what I'd expect.

Should segmenting by page title work?

**Comment by Veda** [comment]
An update on the issue raised by @joelanman. 

We upgraded piwik to 2.14.3 hoping url truncation and segment issues around page title/url would be fixed. Issues seem to still exist. 
We would appreciate if someone could take a look and respond to confirm that they are known issue. If not please point us in the right direction. 

Many Thanks.

**Comment by mattab** [comment]
Could you paste a screenshot showing the problem? Ie. visitor log for a given user, without segment, and then for a given segment. Or maybe you can reproduce on demo.piwik.org and send links to reproduce?

**Comment by Veda** [comment]
Hi Matthieu,

Thanks for your response. 

In order for us to reproduce the issue, we need to create a custom segment which needs login credentials in your demo environment. We have attached the screenshots of the behaviour we have in one of our test environments. Let us know if you need any extra information.

The segment in the journey attached is created with pageURL and doesn't work as expected.  The issue issue exists for pageName too. We expect it to work like EntryPageUrl segments do (return all page urls in the entire journey that contain segmented page url/name).
 
![1-piwik-allpages](https://cloud.githubusercontent.com/assets/857726/9812738/45599ede-5877-11e5-87af-2634e69c7dfa.png)
![2-piwik-createcustomsegmentwithentrypageurl](https://cloud.githubusercontent.com/assets/857726/9812737/455984e4-5877-11e5-92f7-3f8bc3548fcf.png)
![3-piwik-segmentwithentrypageurlwiththeentirejourneypageslisted-expectedbehaviour](https://cloud.githubusercontent.com/assets/857726/9812736/4557f836-5877-11e5-99c7-970bccf390bb.png)
![4-piwik-createcustomsegmentwithpageurl-issuewiththisone](https://cloud.githubusercontent.com/assets/857726/9812734/45561278-5877-11e5-831d-2dc823e375ff.png)
![5-piwik-segmentwithpageurldoesnotincludetheentirejourneypages-issue](https://cloud.githubusercontent.com/assets/857726/9812735/4557895a-5877-11e5-9a9e-73dc8ad09f06.png)

Many Thanks

**Comment by laurencegds** [comment]
Hi Matthieu
I work with both Veda and Joe and wondered whether we could have some commitment on turnaround time for picking up this convo?
I understand investigating can/will take time, but at least if we both endeavour to acknowledge receipt of info, update when we make progress or are blocked, within 1 working day (with caveat of time difference)
it gives us an idea of when we are likely to get a resolution, and whether that is soon enough for us given the deadlines we are working to. FYI we are currently assessing how well PIWIK is working for us and need to work pretty hard to make it worthwhile.

**Comment by joelanman** [comment]
@mattab thanks for looking into this - appreciate any pointers you could give to help us investigate further

**Comment by mattab** [comment]
> The segment in the journey attached is created with pageURL and doesn't work as expected.

It seems to work as expected from your screenshots?

 when you segment on "Entry page Url" then it selects all visits who started their visit on this entry page url. it's expected you get all other kinds of URLs that were visited by the users during their visit.

**Comment by joelanman** [comment]
the `Entry page URL` example (2nd and 3rd screens) seem to work

the `Page URL` example (4th and 5th screens) do not. The only URL listed in the report is `sign-in`. As you say, it ought to be all the other URLs  that were visited by users (who saw `sign-in`) during their visit.

**Comment by mattab** [comment]
In this case, no: the report only shows those URLs you filter to. 

Maybe what you want is something like Segment Sequence #7533

**Comment by Veda** [comment]
Thanks @mattab for clarifying the way page URL/Name segments are supposed to work.

**Comment by joelanman** [comment]
@mattab To confirm, does that mean segments work differently to Google Analytics here?

Normally, a segment means 'filter all reports to just sessions where X applies'.

So normally, a page URL segment would filter to 'sessions where the page URL X was seen' - this is the behaviour seen in GA.

I don't really understand how a segment is just showing one URL in this report - as no sessions saw just this one URL. If this is by design, whats the difference between a page URL segment on the Pages report, and a simple search (in the box at the bottom) on Pages report?
