### ISSUE TITLE
Apply default filter_limit to all API calls

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8458]
In https://github.com/piwik/piwik/commit/2d721cf08386b16f75f979d962c81be7db1689d6#diff-206e6082c2ac821ef0396bf60abbfec7R221 we added the support of `filter_limit` for API calls that return an `array`. However, we could not apply the default filter limit to those API calls as it would break the API. We would have suddenly returned only 100 entities instead of all entities for all API methods that return an `array`. 

For Piwik 3.0 we can break the API as it is easy to adjust for users and we get rid of this method: https://github.com/piwik/piwik/commit/2d721cf08386b16f75f979d962c81be7db1689d6#diff-206e6082c2ac821ef0396bf60abbfec7R221 and this line: https://github.com/piwik/piwik/commit/2d721cf08386b16f75f979d962c81be7db1689d6#diff-16262025799e2435d8bd28df29a147f1R33 which were needed to not break the API

**Comment by tsteur** [comment]
@mattab can you confirm making this change is ok for Piwik 3.0?

**Comment by mattab** [comment]
@tsteur applying the `filter_limit` for API calls returning an array will make the API behaviour consistent across data types (arrays, datatables, ...) - this new consistency makes it worth to break BC of API so :+1:
