### ISSUE TITLE
REF: add full URL source / origin of report in reports email template

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#8461]
It would be useful to add information on where a report originated from (full URL / main URL / other) when reports are sent by email, possibly also in PDF properties.

This would help know the origin of reports for troubleshooting and management purposes.

**Comment by mattab** [comment]
:+1:  to add link to Piwik in the email. 

It should also be do-able to add the info as a PDF property

maybe some users will want to disable displaying the Piwik URL, but we can wait to see if anyone requests this.

**Comment by tsteur** [comment]
If I see correct current text is

```
Hello,
Please find in attached file your weekly report for $reportName.
```

So we'd add something like `This report was sent from $piwikUrl.` ?

**Comment by MagicFab** [comment]
Yes, link to the root URL of the Piwik site (not to piwik.org!).

**Comment by tsteur** [comment]
FYI: I tried to set custom properties/metadata in the generated PDF report for quite a while but didn't get it working. There is this method `setExtraMP()` to set custom metadata but I couldn't find a single example on what to set there: https://github.com/tcpdf-clone/tcpdf/blob/master/tcpdf.php#L9492 . It probably should be some kind of `</df:RDF>` elements... if it is important I can invest more time

**Comment by diosmosis** [comment]
If adding as a PDF property, I think it would be better to add the URL to the PDF Producer element. Though this seems like it could be a security risk if the URL to Piwik is meant to be private? The file could be forwarded to someone who shouldn't know of the URL.

**Comment by mattab** [comment]
Here is how it looks like:

![rpeort pdf](https://cloud.githubusercontent.com/assets/466765/9394531/38154286-4789-11e5-9160-2bd7a1fe76a0.png)


> The file could be forwarded to someone who shouldn't know of the URL.

that's good point, maybe we should be careful with hiding the piwik url within document.

@MagicFab i'll close issue as done for now, thx for suggestion
