### ISSUE TITLE
CSS stylesheet not available

### ISSUE THREAD

**Issue by moderactif** [piwik/piwik#8471]
Hello,

I upgraded the software and everything but it seems that the css is not loaded correctly as I can see just the html code

=> analytics.moderactif.com

why?

**Comment by tsteur** [comment]
Please try to execute `rm $PIWIKDIR/tmp/assets/*.css` on the command line in case you have access to the command line or delete this file manually on your webserver (there should be only one).

 it might fix your problem but not sure. It doesn't return any response at all when requesting the CSS but still an HTTP 200. Can you access your server logs and have a look there?

Did you update via the UI or manually? Which PHP version are you using (if you know)?

**Comment by moderactif** [comment]
File deleted, but nothing changed

sadly I do not have access to my server logs
I updated the software automatically, but the problem was there even with the previous version.. and php 5.4

Thanks for your tim!

**Comment by tsteur** [comment]
It won't be possible to do it manually as the file would be overwritten. Without having access to the server logs it will be hard to tackle this issue. From which version did you update? Is it maybe possible that we get access to the server itself. If so, please send us an email to "hello at piwik.org" and comment here
