### ISSUE TITLE
Date range (7.1 8.3 )

### ISSUE THREAD

**Issue by seikai10** [piwik/piwik#8478]
Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance.

**Comment by sgiehl** [comment]
Could you have a look at the server error log if any error has been logged?

**Comment by sgiehl** [comment]
I'll close this issue now. If you still have trouble, please ask further questions in our forums.
