### ISSUE TITLE
Tag 2.14.2 should be moved to 08fa53b or there should be new tag 2.14.3

### ISSUE THREAD

**Issue by sebastianpiskorski** [piwik/piwik#8480]
Because of this bug https://github.com/piwik/piwik/issues/8439 current tag 2.14.2 is unusable. So if the bug was fixed tag should be moved, because 08fa53b is hard to find.

**Comment by mattab** [comment]
Hi @sebastianpiskorski 
2.14.3-b1  was released, which contains the fix. 2.14.3 stable will be released in the next week or so
