### ISSUE TITLE
Segment for page url results in problems with popups with defail-infos

### ISSUE THREAD

**Issue by cyberbeat** [piwik/piwik#8484]
I created a segment for "pageurl" contains "myparam=1".

When displaying that segment, I have many problems, for example clicking on visitor-log for a city results in the page getting reloaded, but no details displayed.

some other actions result in an error-message

maybe the "=" symbol in the segment is a problem?

**Comment by mattab** [comment]
Thanks @cyberbeat for the report! 
I could reproduce the bug, and created it again (forgot about this one) in #8776
