### ISSUE TITLE
Log Analytics problem on 2.14.2 

### ISSUE THREAD

**Issue by alessandrocanovi** [piwik/piwik#8486]
After upgrading Piwik to 2.14.2 visitor IP of imported logs is always Piwik server IP

**Comment by tsteur** [comment]
Can you maybe give us more information and maybe 2 or 3 example lines of the log you are importing? What kind of log format is it?

**Comment by alessandrocanovi** [comment]
I am using common_complete log format.
Can I send log example directly to you?
I would prefer not to publish it here.

**Comment by mattab** [comment]
Hi @alessandrocanovi 

please create issue in this tracker: https://github.com/piwik/piwik-log-analytics/issues/
and if you can attach a log line or two, and instructions, it would be great (you can change IP address etc.)

**Comment by alessandrocanovi** [comment]
I've just noticed someone else opened an issue for the same problem:

https://github.com/piwik/piwik-log-analytics/issues/82

2015-08-14 17:11 GMT+02:00 Matthieu Aubry <notifications@github.com>:
