### ISSUE TITLE
TypeError: L[Y] is undefined when adding setUserID

### ISSUE THREAD

**Issue by pavarnos** [piwik/piwik#8487]
Hi.

Using Piwik 2.14.2. Copied and pasted the latest tracker code from the piwik admin into my site. Added setUserID per the instructions here http://developer.piwik.org/guides/tracking-javascript-guide.

```javascript
      var _paq = _paq || [];
      _paq.push(['setUserID', "1"]);
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//example.com/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', 1]);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
```

Get the error message  
TypeError: L[Y] is undefined in piwik.js:14:658
in the Firefox developer console.
(piwik server is Ubuntu 14.04 with php 5.6.11-1+deb.sury.org~trusty+1)

If I remove the setUserID line it works fine.
Am I doing something stupid or is this a bug? 
Thanks for your help

**Comment by tsteur** [comment]
It should be `setUserId` not `setUserID`. Please reopen in case it does not solve it
