### ISSUE TITLE
Install script broken

### ISSUE THREAD

**Issue by vincepettit** [piwik/piwik#8490]
When running the installation script it is trying to check permissions on /home/mysite/public_htmlconfig/ 
but it be /home/mysite/public_html/config/ 

This is currently stopping the installation going any further.

**Comment by vincepettit** [comment]
I suspect it is on line 408 of core/Config.php as there seems to be a preceding slash to config

$path = "config/" . basename($this->getLocalPath());

I tried updating the code but it is now telling me there is a integrity error as the file has been changed so I can't test it.

**Comment by sgiehl** [comment]
duplicates #8439, and should already be fixed in latest beta
