### ISSUE TITLE
Visitor Profil: direction of visit-numeration is confusing

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8491]
In the visitor profile you can see the visits of a visitor.
These visits are numbered from top to bottom.

Shouldn't it be from the logical pow the other way around,
so that the first visit has number 1 and every new visits gets the following number?

In addition beside the logic problem, the number of the visits in the past changes, so one could not talk about e.g. the visit with number 4  because when there is a new visit these number changes... 

What do you think?

Please see attachment
![2015-08-05_16h29_52](https://cloud.githubusercontent.com/assets/5681880/9088464/724c2456-3b90-11e5-856f-2d6ec98e4fa1.png)

**Comment by tsteur** [comment]
:+1:

**Comment by Flux3PO** [comment]
I can confirm, I do see this as an issue as well (or at least confusing)

**Comment by tsteur** [comment]
It's not as trivial as we could change change it to 4, 3, 2, 1 but it might be wrong if there were eg 50 visits. Then it should be rather "Visit 50, 49, 48, 47, ...". 

There might be an issue if there were more than 100 visits since we apparently only fetch 100 visits. In this case we would possible show "Visit 100, visit 99, visit 98" which might be actually a higher visit. 

To be confirmed

**Comment by hpvd** [comment]
yes sure. 4,3,2,1 was only an example. Should take all "known" visits into account.

Regarding only fetching 100 visits, one maybe can think of a two step approach:
1) make it working <100 visits within this ticket (which is already a lot)
2) and open a new ticket for making it working fine for >100 visits

in 1) one may show instead of numbering the visits for every shown visit "99+"

**Comment by hpvd** [comment]
btw: are you sure there is a 100 visit limit? One could select show 500 visits please see attachment.
Or is the 100 a limit for visits of the same visitor?
![2015-10-28_06h59_28](https://cloud.githubusercontent.com/assets/5681880/10780770/86fcee06-7d41-11e5-969e-4795b448076a.png)

**Comment by Glisse1** [comment]
Yes, the numbering it is wrong, or at least confusing.First visit should be the first visit, not last. Opening a profile in live widget for instance should list me the visitor with 14th visit today as visit #14, not #1

**Comment by tsteur** [comment]
> btw: are you sure there is a 100 visit limit? One could select show to 500 visits please see attachment.
Or is the 100 a limit for visits of the same visitor?

There is a limit of 100 in the visitor profile. The limit selector is for the visitor log, not for the visitor profile

**Comment by mattab** [comment]
A few users have reported this recently so increasing priority
