### ISSUE TITLE
piwik.js - public method for browser information (browserFeatures)

### ISSUE THREAD

**Issue by vaclavpavek** [piwik/piwik#8494]
Please, create public function for getting browser information. Thanks

**Comment by tsteur** [comment]
What kind of browser information? The `piwik.js` is not really supposed to be a library to detect browser etc and is only meant to send tracking calls to Piwik

**Comment by vaclavpavek** [comment]
I am doing a project which is part of the technical support and the primary goal is to find out as much information about the user in order to resolve technical problems on us developed web applications.

All projects can play with Piwik aa'm satisfied. It occurred to me to use part of it (like Piwik / device-detector) to collect information that can not be read from the UA.

I have no problem to write something, but why not take something that's were authored works well and most importantly is already loaded.

Sorry for my bad English

**Comment by tsteur** [comment]
Fair enough and good idea to reuse existing stuff. 
The device detection is happening in Piwik itself in PHP and not in `piwik.js` unfortunately. We cannot offer such an API to get this kinda information. The repository for the device-detector is here: https://github.com/piwik/device-detector/ and you might want to have a look at https://github.com/piwik/device-detector/issues/5257 and comment re asking for a JS version or create a new issue in that issue tracker.
