### ISSUE TITLE
Is it possible to display individual page gentime in widget or simple screen?

### ISSUE THREAD

**Issue by srhong** [piwik/piwik#8499]
Hi, It's very useful feature, avg.gentime factor.

Is it possible in page - individual access(IP) - menu or some DB query?

**Comment by srhong** [comment]
I want to check gentime(network time+response time) from various country.

**Comment by mattab** [comment]
Hi @srhong 
Yes it's possible to get this data in the Page URLs widget, see also: http://piwik.org/docs/page-speed/

For further question feel free to ask in the forums: http://forum.piwik.org/
