### ISSUE TITLE
Exclude development files from release

### ISSUE THREAD

**Issue by szepeviktor** [piwik/piwik#8508]
Could you please exclude `.phpstorm.meta.php` and other development files for e.g. Composer?

**Comment by szepeviktor** [comment]
Do you keep your release script in this repo?

**Comment by mnapoli** [comment]
Thank you, I've created a pull request: https://github.com/piwik/piwik-package/pull/34 The release script is indeed in a separate repository.

**Comment by szepeviktor** [comment]
Are Bower and Composer files needed in production?

**Comment by mnapoli** [comment]
For Bower and Composer I have to say honestly I'm not so sure… I would say no but since they are kept in the release there might be a reason for it. Ping @mattab who might have an answer.

**Comment by szepeviktor** [comment]
@mattab Could you please help us?

**Comment by tsteur** [comment]
They should not be needed at the moment and could be removed - if needed.

**Comment by szepeviktor** [comment]
I prefer a clean production code.

**Comment by mattab** [comment]
What's the matter with composer files? I think they provide some value, showing Piwik users all libraries bundled with Piwik, eg. for security reasons this may be useful?

**Comment by szepeviktor** [comment]
OK.
I delete every file in piwik root that is for no use in production (for security reasons because all of them can be downloaded)
This way I have to delete these files on every update.

**Comment by szepeviktor** [comment]
> showing Piwik users all libraries bundled with Piwik

Do you think more than 0.1% of the users are familiar with e.g. composer?
