### ISSUE TITLE
New Piwik team page on piwik.org

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8519]
The goal of this issue is to discuss the proposed changes to a new Piwik.org team page. This is a follow up to Piwik Meetup discussions in Berlin 2015.

The team page can be seen at: http://piwik.org/team/

Here are are suggestions that were made to improve this page:
 * can we get pictures for all Piwik contributors,
 * can we list all contributors in alphabetical orders,
 * tag Piwik PRO staff as "Piwik PRO staff" so it is clear who is Piwik PRO contributor VS Piwik contributor,
  *  or maybe we remove Piwik PRO contributors who do not directly contribute to Piwik (although they do contribute indirectly by generating revenue which is directly re-invested in Piwik), 
  * and instead credit "Piwik PRO" as a Piwik contributor and link to a (to be created) team page on Piwik PRO website,
 * can we display email + linkedin + github links for Piwik contributors, (as it was before)
 * can we remove Matthieu and Maciej photos at the top, as this is more relevant for Piwik PRO team page and not Piwik.org team page,
 * ...

This RFC will be opened for a a few weeks until the new team page will be ready. We will post here the updated team page to ask for feedback.

Your feedback is welcome, especially if you are a contributor to Piwik, please let us know how we can make the team page really great!

**Comment by sgiehl** [comment]
As mentioned on the meetup: For future changes it would be good to open such RFCs **before** changes are made without discussion with the contributors/community.

Nevertheless the listed suggestions sounds good.
Regarding the alphabetical order. We should mention that in a small sentence before the list, so no one wonders why a specific person might be listed before another.

**Comment by dczajkacc** [comment]
To me it's better to have PiwikPRO mentioned as a sponsor and some of our developers in person as contributors because they actually committed some code. Personally I was surprised that I'm on a team page at piwik.org.

**Comment by BeezyT** [comment]
Employees of Piwik PRO are not Piwik team members, even when they contribute to the core. In the latter case, they are contributors. Also Maciej is not CEO of Piwik, he's CEO of Piwik PRO.

I'd suggest to create a Piwik PRO team page on the Piwik PRO website where all the Piwik PRO staff is listed. On the Piwik team website, Piwik Pro can be shown as the first contributor without mentioning any names. Instead, there's a link to the Piwik PRO team page.

If Piwik PRO feels that they require more credit than all other contributors, the entry can be highlighted in some way. But imho, they do not deserve extra credit on the team page. They do deserve extra credit on the sponsors page, however.

Becoming part of the Piwik team is something that has to be earned and something one can be proud of. Being part of the Piwik team says that you contribute voluntarily to the project and are part of an open source community. That simply does not hold for Piwik PRO employees and people that work only on Piwik PRO products. Also, it diminishes the value of being a Piwik team member when the entire Piwik PRO staff is part of it. Being a Piwik team member must mean way more than having a contract of employment.

**Comment by ldziuba** [comment]
Here is the new proposed Team page. All text and contributors will be updated in the final page. Feedback is most welcome. 
![teampage](https://cloud.githubusercontent.com/assets/4919863/9199983/da937276-4045-11e5-9b4e-2eecd2d1920b.png)

**Comment by mnapoli** [comment]
:+1: that's a good improvement

**Comment by BeezyT** [comment]
I like how there are links to translators and Piwik PRO. They are very present but not on top.

I would suggest keeping the two sections Team and Contributors, though.

By the way, who should I send my photo to?

**Comment by peterbo** [comment]
That redesign / restructuring looks good in my opinion.

**Comment by MagicFab** [comment]
If and when any PiwikPro staff is added to this page as actual contributors, they could simply have a small "PRO" or similar logo/badge indicating their employment, linking to the (future) PiwikPro team page.
Perhaps other badges could be added for translations team members, instead of having another separate section to link to their page.
I also think a personal website icon would be most useful, not everyone has or wants to have linkedin profiles, twitter, etc.

**Comment by mattab** [comment]
Hi guys

Here is the new Team page template.

![team](https://cloud.githubusercontent.com/assets/466765/9273845/aaccf470-4290-11e5-90d3-c3fcfbb2c284.png)


Changes:
 * moved "contributors" to the "Other contributors" section, to separate who is a team member VS past contributor
 * added a `P` icon to show who is working at Piwik PRO
 * made the icons grey, they will be colored on hover
 

Notes:
 * maybe we need to think about and decide how one can get into the Piwik team, have its own @piwik.org email, be invited to meetups, etc. 
 * if there is no further feedback the new page will be implemented on the site next week. I'll post a comment when it's live and feedback will be welcome of course

**Comment by BeezyT** [comment]
Since you've added an indication for Piwik PRO, I was wondering, will the Piwik PRO staff still be listed as team members and Maciej as CEO of Piwik?

**Comment by mattab** [comment]
Current list of Piwik PRO staff that are also part of Piwik team are: Maciej, Matthieu, Thomas, Benaka. We will add few other under "Contributors" such as designers and webmaster, ... 

We will not display titles/ roles in the page, but write a 2-3 lines text describing the roles or contributions. Maciej will be described as CEO of Piwik PRO and contributor to Piwik.

**Comment by BeezyT** [comment]
Sounds good :+1:

**Comment by sgiehl** [comment]
Any updates? Old page is still online.

**Comment by ewaAB** [comment]
Hi! Just spoke with our devs - there is some delay on the implementation side, but the layout will soon be cut and placed on staging. We will post it here for you to have a look and listen to your feedback! Cheers, e

**Comment by BeezyT** [comment]
The new team page looks good in my opinion. Just one request - could you please remove the weblink after my name? The URL is wrong and I don't work there anymore. So if you could just remove the link entirely, that would be great. Thanks!

**Comment by ewaAB** [comment]
@BeezyT link removed:) I know @mattab got a  list of issues to add/change on this page, so its content might undergo slight changes. In any way, if you guys spot anything that ought to be improved, please let us know. Cheers!

**Comment by mattab** [comment]
Hi everyone, the new team page is finally up!  I hope this new page reflects the great diversity and talent of people who contributed directly to the success of building the leading open source analytics platform.

See the page at: https://piwik.org/team/

 * A big welcome to all newly listed team members and contributors! @dotsbb @braekling @mattiaslevin @aureq @PiotrPress @lemu 

 * Under "Team" all active contributors are listed: contributors who actively maintain a project in the Piwik ecosystem (eg. SDK, Api client, etc.)

 * Everyone who has write access to the main Piwik repo and our 50+ other repositories (plugins, components, qa tools, etc.) is marked in the team page with `Piwik Core developer`. 
  * engineers who have write access to all repos are @tsteur (Lead) @diosmosis (Lead) @mnapoli  @halfdan @BeezyT @gka @JulienMoumne @sgiehl 

 * In coming days/weeks I'll get in touch with a few more contributors to clarify whether you are still interested to participate & maintain your awesome & useful Piwik projects: @nklutter (Python API clients), @halfdan and @Achillefs (Ruby API clients), @halfdan (Java API clients).

 * for everyone listed on the page: we can setup your Linkedin, Github, Twitter, and personal website URL in the page. Feel free to write them here or email me privately to have this information added if you want.

 * "Team" and "Contributors" will all for sure be invited to our next Piwik team meetups :-)

As always with everything we do at Piwik, your feedback and suggestions are very welcome!

**Comment by mattab** [comment]
we will keep tweaking the page as per your feedback and suggestions, but I'm closing the issue as the new team page is done :+1:
