### ISSUE TITLE
How to improve communication between i) Piwik community ii) Piwik contributors iii) Piwik PRO contributors

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8520]
How can communication be improved between:

i) Piwik users community 
ii) Piwik contributors 
iii) Piwik PRO contributors

In private discussions and during the Piwik meetup in Berlin, this topic was raised several times by key contributors. One challenge is that Slack is being used by Piwik contributors, and another Slack account is used by Piwik PRO contributors. 

Maybe there is for us a possibility to:
- merge both Slack into one,
- have some chatrooms made completely public (eg `#dev-core`),
- open a new support channel that will be completely open (eg. as Wordpress has done [WP Slack](https://make.wordpress.org/chat/), [WP Comm discussions](https://make.wordpress.org/core/handbook/about/communication/) 
- document Slack<>IRC relay (as IRC is a communication standard)

**Comment by sgiehl** [comment]
+1 for merging slacks and making it public.

**Comment by MagicFab** [comment]
I believe Slack should not be used here as it is a proprietary SaaS service and this in incoherent with Piwik's mission and values. 
Other alternatives that may be more coherent to use may need some testing and evaluation, I know for example about https://rocket.chat ( see https://github.com/RocketChat/Rocket.Chat#features ) but there may be other better alternatives.

**Comment by gaumondp** [comment]
I don't think using Slack is incoherent. It's as incoherent as using the proprietary IDE PhpStorm for coding...

TYPO3 community has 109 channels on Slack and it just works fine.

That's my 0.02 canadian dollars opinion

**Comment by quba** [comment]
+1 for public slack

**Comment by MagicFab** [comment]
@gaumondp yes, I agree using a Free as in freedom IDE would be better, I suggest you open a bug report about it. 

If the Typo3 community has a different set of values I don't see how that is relevant here or how it should make Slack use coherent within [Piwik's own values](https://github.com/piwik/piwik/wiki/Our-mission-and-values).

I'll re-state the obvious, whenever the Piwik community is required to use tools and SaaS that go against such values in order to contribute, instead of valid existing alternatives, it is in fact incoherent with such mission and values. 

We should at least consider an alternative and evaluate the feasibility of moving to it.

**Comment by mattab** [comment]
What are your thoughts on improving forum discussions?

It was suggested by a few community members that we could use a more modern forum software for the Piwik community, in particular http://www.discourse.org/ was suggested as an alternative to our current phorum-based forum.

Examples of other discourse forums: 
 * New Relic: https://discuss.newrelic.com/
 * Atom: http://discuss.atom.io/
 * Discourse itself: https://meta.discourse.org/

What do you think about this?

**Comment by mnapoli** [comment]
@MagicFab Piwik uses many proprietary tools for its own development. A good example is GitHub.

Modernizing the forum would be great, Discourse is awesome.

**Comment by quba** [comment]
+1 for public Slack and Discourse.

**Comment by MagicFab** [comment]
@mnapoli I know, it's not the topic here, though.

@mattab +1 on Discourse, it may be important to look at possible SSO setup to simplify contibutor's login to this and other tools.

**Comment by mnapoli** [comment]
@MagicFab I'm sorry, I'm probably missing it then :/

> I'll re-state the obvious, whenever the Piwik community is required to use tools and SaaS that go against such values in order to contribute, instead of valid existing alternatives, it is in fact incoherent with such mission and values.

What is the problem with using Slack which isn't a problem when using e.g. GitHub?

**Comment by MagicFab** [comment]
@mnapoli  AFAIK GitHub is not contributing to miscommunication issues, however I agree it's also problematic (for example it's restricted to 13 y.o. and +, you can't have more than 1 account, etc.). I am not involved in development, perhaps those who are will want to elaborate on that. It would certainly be useful to know more details on what you think.

**Comment by mattab** [comment]
Good news: some progress has been made on testing Discourse for Piwik forums! See  Migrating Piwik forums to use Discourse #8747 

(opening Slack to the public is still planned, but I prefer to focus first on Discourse migration as it is more important. will get in touch with Slack for more details, after Discourse migration is successful)

**Comment by mattab** [comment]
Not working with Piwik PRO anymore so closing for now.
