### ISSUE TITLE
Exclude bounced referrer spam.

### ISSUE THREAD

**Issue by theDogsBody** [piwik/piwik#8523]
Referrer spam is rendering my analytics data near futile and attempts to identify and block individual referrers is both time consuming and frustratingly ineffective

Is it possible to exclude all visitors who bounce from my site within 10 seconds, from appearing in my analytics? Or alternatively, to simply exclude visitors who bounce, period?

While this would result in data on 'genuine' bounces being lost, the current referrer bounce rate invalidates the bounce data anyway so in reality i've already lost that information.

**Comment by sgiehl** [comment]
Piwik tries to exclude referrer spam using our own list. Feel free to participate there to fight the referrer spam: https://github.com/piwik/referrer-spam-blacklist
