### ISSUE TITLE
 Some search engines forgotten

### ISSUE THREAD

**Issue by Zefling** [piwik/piwik#8524]
Some search engines forgotten :

Nintendo (via Google) : 
http://cgi2.nintendo.co.jp/gsearch/search.html?p=test

kensaq :
http://www.kensaq.com/web?q=test

kwzf (image) :
http://kwzf.net/#search=test

Dolphin Browser  (via Google):
http://search.dolphin-browser.jp/?q=test

Net-lavi Search (via Google):
http://netlavis.azione.jp/search/?q=test

Au One (via Google / mobile only) :
http://sp-search.auone.jp/search?q=test

KingSoft (via Yahoo! Japan)
http://home.kingsoft.jp/type/web?keyword=test

Google : 
https://search.nan.so/#newwindow=1&q=test
https://search.nan.so/
https://nan.so/

Fooooo :
http://search.fooooo.com/web/?q=test

Laban (via Google / mobile only ?) : 
http://laban.vn/search-image.html?q=test

**Comment by sgiehl** [comment]
I'll have a look within the next days

**Comment by Zefling** [comment]
One more : 

Free (via Google) :
http://search.free.fr/google.pl?qs=test

**Comment by Zefling** [comment]
Hehe, one more :D

Chedot (via Google) :
http://search.chedot.com/?text=test
