### ISSUE TITLE
Duplicate visitors and goals in reports

### ISSUE THREAD

**Issue by JeRRimix** [piwik/piwik#8528]
Hi everyone

I have a strange problem with Piwik. It's record visitors and work woth goals according to my conditions, but in all reports including real-time data I see duplicates!!! If one visitor came it show that the two and if visitor make one goal it show that two goals in report. 

What could be the problem?

**Comment by mattab** [comment]
Hi @jeRR

Maybe you added the piwik code twice in your pages?
