### ISSUE TITLE
Should we block the possibility to commit changes directly to master branch?

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8531]
To prevent human errors by core team developers, and somehow enforce to have all changes go through Pull requests, maybe it would make sense to block committing changes directly to `master` branch?

Follows up: https://github.com/piwik/piwik/commit/affd9703293fc748260fe96993d30ef149b34b1a#commitcomment-12394028

**Comment by tsteur** [comment]
I don't think a review would have prevented this issue and to block something in general is not a solution I'd say

**Comment by sgiehl** [comment]
human errors will always occur, and I also don't think blocking commits to master will solve those issues. Imho it is better to add valuable tests to prevent an error for the future as soon as it occurred the first time.

**Comment by mattab** [comment]
Ok, so we won't block commits to master for now, thanks for the comments!
