### ISSUE TITLE
Debian folder permissions

### ISSUE THREAD

**Issue by luckyraul** [piwik/piwik#8532]
After every debian piwik package update I always should apply manually 
```chown -R piwik:piwik /usr/share/piwik/tmp/```

when Piwik runas as piwik user

It's changing somehow to www-data user.

**Comment by mattab** [comment]
Hi @luckyraul 

Please report this issue in the debian package tracker at: https://github.com/piwik/piwik-package/issues

**Comment by MagicFab** [comment]
@mattab @luckyraul I've opened this issue here : https://github.com/piwik/piwik-package/issues/36
