### ISSUE TITLE
Bug in calling method Live.getCounters (and similar methods) when number of sites more than 1

### ISSUE THREAD

**Issue by diginet-md** [piwik/piwik#8533]
1) We speak about Live.getCounters method
http://developer.piwik.org/api-reference/reporting-api#Live

2) We have PIWIK on our own WEB server.
2.1) We have 7 web sites for testing that is to be tracked in PIWIK on our web-server.

3) in documentation "Standard API parameters"
http://developer.piwik.org/api-reference/reporting-api#standard-api-parameters

shown the following:
Standard API parameters
idSite:
- the integer id of your website, eg. idSite=1
- you can also specify a list of idSites comma separated, eg. idSite=1,4,5,6
- if you want to get data for all websites, set idSite=all

4) problem description
for the Live.getCounters method and other similar method Live.get... mentioned rules
doesn't works when number of sites more than 1.

For example
4.1) data for site #6 (idSite=6) - data available
http://analytics.diginet-solutions.com/?module=API&method=Live.getCounters&idSite=6&lastMinutes=30&format=xml&token_auth=anonymous

4.2) data for site #7 (idSite=7) - data available
http://analytics.diginet-solutions.com/?module=API&method=Live.getCounters&idSite=7&lastMinutes=30&format=xml&token_auth=anonymous

4.3) data for sites #6 and #7 (idSite=6,7): - data available for site # 6 ONLY
http://analytics.diginet-solutions.com/?module=API&method=Live.getCounters&idSite=6,7&lastMinutes=30&format=xml&token_auth=anonymous

4.4) data for ALL web sites (idSite=all): - No data avaialble (empty)
http://analytics.diginet-solutions.com/?module=API&method=Live.getCounters&idSite=all&lastMinutes=30&format=xml&token_auth=anonymous

Pls advise is it bug or problem when we call the method from PIWIK.
Or please adive which other way to use to receive row data  when it is necesaary to obtain information about more than 1 site.

**Comment by tsteur** [comment]
It's a "bug" or the documentation needs to be updated I think. It only works for some reports so far unfortunately.

Technical background: I reckon it only works for reports returning dataTables maybe? Haven't had a look at the code yet.

**Comment by diginet-md** [comment]
Thomas, 
in case you need to have a look on code on our Piwik Server, it is not a problem.
pls provide your contacts to me (info@diginet.md) 

RGRDS
Vladimir

**Comment by tsteur** [comment]
Not needed, we should be able to reproduce it

**Comment by diginet-md** [comment]
OK.

In case it be important.
We use PIWIK 2.14.3.

RGRDS
Vladimir

**Comment by diginet-md** [comment]
In case this is bug, is it possible, at least preliminarily, to estimate when it could be fixed in comming release of PIWIK?

RGRDS
Vladimir

**Comment by mattab** [comment]
This duplicates #8574
