### ISSUE TITLE
E-Mail reports with missing data

### ISSUE THREAD

**Issue by babielau** [piwik/piwik#8536]
Our e-mail reports just include old device type statistics. The Device Detection Plug-In was never deactivated. 

This bug is persistent since several versions:

![devices](https://cloud.githubusercontent.com/assets/8897847/9176066/4bb7c49c-3f89-11e5-8871-3cbf483afeff.png)

Also, the daily reports seem to be corrupted as well. On some weekdays there are no statistics visible in the graphs, though there had been requests to the site.

Right now, we are using Piwik in version 2.14.2

**Comment by mattab** [comment]
Hi @babielau 
thanks for the report. This duplicates #7948

This issue should already be fixed in Piwik 2.15.0-b1 - see http://piwik.org/faq/how-to-update/faq_159/
