### ISSUE TITLE
endless Errors: piwik segments without www.starad24.com, www.myadvertisingpays.com

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#8539]
see screencast please: http://screencast.com/t/VSYBvsyQ2miF

i tried to exclude source pages www.starad24.com and www.myadvertisingpays.com 
and good hugh amount of errors and filter functions which are not working correctly.

please harden piwik with this information.

**Comment by mattab** [comment]
Hi @Tobias-Conrad 

This duplicates #8776 #8484 and should be fixed in #8805
