### ISSUE TITLE
Cannot add new websites

### ISSUE THREAD

**Issue by sndrsk** [piwik/piwik#8541]
I am running 2.14.3 and am unable to add a new website. I had this issue in the previous version as well, and I'm not sure how long this has been going on since I don't need to add websites often. I saw issues https://github.com/piwik/piwik/issues/7808 and https://github.com/piwik/piwik/issues/7802 but removing the showaddsite=1 parameter doesn't solve the issue, so it seems to be something different. I also tried re-uploading files and no luck. I have tried in Internet Explorer, Edge, and Firefox. 
![untitled](https://cloud.githubusercontent.com/assets/12263221/9188458/f7316c34-3fa1-11e5-98ad-d77f6fa5ceb8.png)

**Comment by tsteur** [comment]
From the sounds it's related to #6497 maybe have a look here https://github.com/piwik/piwik/issues/6497#issuecomment-60836702 and at the other comments

**Comment by sndrsk** [comment]
@tsteur I just checked config.ini.php and it already included charset = "utf8".

**Comment by mattab** [comment]
@sndrsk can you please try with 2.15.0-b5 and see if it maybe works better? http://piwik.org/faq/how-to-update/faq_159/

**Comment by sndrsk** [comment]
@mattab Sorry for the delay... I updated to 2.15.0-b6 and the issue is not resolved.

**Comment by tsteur** [comment]
Can you access your database and maybe have a look at the `piwik_site` table? The table might be named `site` or with a different prefix. There should be a column `name`. Temporarily removing or replacing all umlauts or special characters may fix it. You should be able to edit them again afterwards via the UI and add the special characters again

**Comment by sndrsk** [comment]
@tsteur Nope, no special characters within.

**Comment by mattab** [comment]
@sndrsk could you give us access to your Piwik so we can see the problem? please email login credentials to hello at piwik.org if possible :)

**Comment by mattab** [comment]
@sndrsk the HTML files return 404 request.  Check out this FAQ http://piwik.org/faq/troubleshooting/faq_18485/
