### ISSUE TITLE
Introducing Long Term Support for Piwik 2.X

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8546]
The goal of this issue is to announce to the community that we are introducing Long Term Support (LTS) version for Piwik. 

After Piwik 3.0.0 will be released (#6074), we are committed to fully support users on Piwik 2.X for at least one year. 

### Piwik Supported versions policy

* our policy until now was "We only support the latest Piwik version". 
* our new policy will be something like "We recommend to upgrade to the latest Piwik 3.X - but you can also use the latest Piwik 2.X. We support both 2.X (until at least Sept 2016) and 3.X".

### Long Term Support description

 * the last 2.X release will likely be 2.15.0 due in Oct 2015 
 * we will then backport security fixes and any critical/major data bugs, from Piwik 3 into 2.X 
 * we will also fix any security issue or critical bug that only affect   2.X
 * we will release as many 2.X as needed 
 * to get the latest and greatest Piwik, one will have to upgrade to Piwik 3.0. To get the most stable release (eg. [Piwik Enterprise](http://piwik.pro/enterprise)), one can use the LTS version (2.X) 

Your feedback, ideas, suggestions are most welcome!

**Comment by quba** [comment]
I assume that we will port also all regressions (which may be found in some edge cases even after a few weeks)?

**Comment by MagicFab** [comment]
I've created [a wiki page with release dates and other related information](https://github.com/piwik/piwik/wiki/Piwik-releases).

I've also opened [a forum discussion](http://forum.piwik.org/read.php?15,128804,128808) about this.

**Comment by mattab** [comment]
> I assume that we will port also all regressions (which may be found in some edge cases even after a few weeks)?

Technically we should port bugs that cause pain to users, and most regressions do cause some pain, so most regressions should be backported :+1:

**Comment by thomaszbz** [comment]
There's also critical bugs and security issues which might never occur in Piwik 3.0 and therefore cannot be backported (but still should be fixed). This is not included by

    we will then backport security fixes and any critical/major data bugs, from Piwik 3 into 2.X

**Comment by marclaporte** [comment]
This. is. fantastic!

**Comment by benjaminbellamy** [comment]
This is really great news! Thanks!

**Comment by mattab** [comment]
> There's also critical bugs and security issues which might never occur in Piwik 3.0 and therefore cannot be backported (but still should be fixed). 

@thomaszbz good point, added this item to issue description: `we will also fix any security issue or critical bug that only affect   2.X`

**Comment by mattab** [comment]
Question:
 * is there for us an opportunity to "synchronise" our LTS timeline with other popular open platforms? (PHP, Debian) cc @MagicFab 

Next steps:
 * gather more feedback (wait until 2.15.0 is released)
 * Create FAQ about LTS support in Piwik (or a new website page as @MagicFab mentionned in forum post, eg. [PHP LTS page](http://php.net/supported-versions.php) [Ubuntu LTS page](https://wiki.ubuntu.com/Releases))
 * Close this RFC

**Comment by MagicFab** [comment]
I did create a [Releases page for Piwik](https://github.com/piwik/piwik/wiki/Piwik-releases) when I commented about it. Perhaps this could be mirrored on/linked from Piwik.org?

Regarding sync'ing with other projects release cycles, this would need to happen before "freeze" for Debian ([~8 months before release](https://wiki.debian.org/DebianReleases), [~November 2016 for Debian 9](https://wiki.debian.org/DebianStretch)), keeping in mind Piwik has not been yet added to Debian (although [we have Debian packages in a separate repository](https://wiki.debian.org/Piwik)). Piwik 3 will be out before Nov'2016 so it provides time to improve its packaging and possibly aim at including it in Debian 9.

It would then trickle down (via "Debian import") for Ubuntu and all derivatives, having a separate repository (PPA) would also help adoption in Ubuntu until it's added to Debian + imported from it etc. Debian import freeze is about 4-5 months before release and ~1 month before freeze in Ubuntu. The next Ubuntu LTS is 16.04 (in 2016, in 7 months), so the time window for official addition into Ubuntu has passed but verifying the current Debian packages full compatibility with Ubuntu and ideally having a PPA for now could be action items.

Other suggestions are welcome, I primarily evaluate this from a technical/enterprise support + deployment point of view but there may be other considerations.

Regarding PHP + others, I lack the time to further research this at the moment but a major concern raised in other discussions has been aligning Piwik's requirements with PHP / other versions available and supported in Debian/RHEL.

**Comment by gaumondp** [comment]
Syncink with OSes makes little sense compared to PHP versions IMHO,

I'm making up the version numbers for the sake of thinking ahead : 

* Piwik 2.15 LTS = PHP 5.3.3+ tested up to PHP 5.6
* Piwik 3.21 LTS = PHP 5.5+ tested up to PHP 7.x
* Piwik 4.12  LTS  = PHP 7+ and up...

Someone that *need* Piwik will use it /install it whenever there's an official package or not (I'm not saying it's a bad thing to have adoption into the OSes distribution!). Some will try to update their PHP version to get the shinny new 3.x version but I don't think people will update the full OS just to get the official package.

As usual, I can be wrong. :)

**Comment by mattab** [comment]
Fyi: edited [the Roadmap](https://piwik.org/roadmap/) to add a link to https://github.com/piwik/piwik/wiki/Piwik-releases

**Comment by mattab** [comment]
New blog post was published to announce the LTS to the community: [Announcing Long Term Support in Piwik 2 – The analytics platform for your mission critical projects](https://piwik.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/)

Closing this issue: LTS is now official and announced!
