### ISSUE TITLE
Email in login data should be case insensitive.

### ISSUE THREAD

**Issue by sebastianpiskorski** [piwik/piwik#8548]
In the internet in most cases email address is case insensitive, but unfortunately it is sensitive in Piwik. It should be always normalized at the input so user can use it in the way as they are used to.

**Comment by mattab** [comment]
Hi @sebastianpiskorski what is the actual problem or bug that this can cause?

**Comment by quba** [comment]
E.g. a user that copy-pasted the e-mail address may later on try to login using lowercase e-mail address. And for sure this one will be hard to troubleshoot.

**Comment by sebastianpiskorski** [comment]
@mattab 
Given:
    User have registered with email: ExamplE@eXample.Com
    User have tried to login with email example@example.com
Got:
    Login error.
Expected:
    Piwik successful login.

**Comment by mattab** [comment]
Thanks for the report, we will investigate a fix

**Comment by mnapoli** [comment]
I think I'm missing something: users log into Piwik using their username, not emails. Where is the problem happening?

**Comment by quba** [comment]
But they can enter e-mail as login. This is something to discuss further because forcing lowercase will also force lowercase logins. Maybe we should allow to use capital letters, but force lowercase only while checking if such username exists?

FYI: e-mail is the default username when using Piwik Cloud.

**Comment by mnapoli** [comment]
> But they can enter e-mail as login

TIL :smile: 

So case insensitive for login and email would make sense then? I don't see a reason not to.

**Comment by mnapoli** [comment]
I'm sorry I'm maybe being dense here but I can't login into my Piwik Cloud account or my local dev Piwik using my email (checked several time that it's the correct email). Login in with the username of course works.

In the code, [`Auth` calls `$model->getUser($this->login)`](https://github.com/piwik/piwik/blob/master/plugins/Login/Auth.php#L59-59) which search in database [only over the login, not the email](https://github.com/piwik/piwik/blob/master/plugins/UsersManager/Model.php#L152-152).

Where/how can we login with emails?

**Comment by quba** [comment]
They can enter e-mail as login while signing up. I mean that login and e-mail are the same. Sorry for confusion.

**Comment by halabuda** [comment]
not logging in by way of the actual email field of the user table, but the login field of the user table might contain an email address as its value.

**Comment by mnapoli** [comment]
> They can enter e-mail as login while signing up. I mean that login and e-mail are the same. Sorry for confusion.

:confounded: Sorry, I didn't think of that because when I signed up to the cloud I ended up with the generic username of `piwikadmin`, so it didn't think more about that use case ;)

Then definitely will be case insensitive for all logins (emails and regular logins) since there's no difference between them.

**Comment by quba** [comment]
Sure, we've changed this on Cloud recently. Cheers!

**Comment by sebastianpiskorski** [comment]
In my opinion users shouldn't be able to have two account which differ only by letter cases. Like "accont_login" and "AccOunt_loGin" shouldn't be two different logins.

**Comment by mnapoli** [comment]
PR: #8610

**Comment by mattab** [comment]
I just tried to reproduce this issue:
 * created a user with `login` = `test@test.com`
 * then tried creating a user with `login` = `TEST@test.com`
 * Got: `Login 'test@test.com' already exists.`

What is the actual bug- @mnapoli @sebastianpiskorski could you reproduce this or am I doing something wrong

**Comment by mattab** [comment]
Ok got tip from @diosmosis " the bug is that the user created an account like: tesT@user.com by mistake and wants to login w/ test@user.com" so I get it now :)

**Comment by mnapoli** [comment]
Or if the user correctly signed up (without "typo") as matt or test@user.com and wants to login as Matt or Test@user.com :)

**Comment by quba** [comment]
@mattab please see https://github.com/piwik/piwik/issues/8548#issuecomment-129924257 and https://github.com/piwik/piwik/issues/8548#issuecomment-129948080

This comment: https://github.com/piwik/piwik/issues/8548#issuecomment-132934062
introduced some confusion but I think that now we are one the same page.

Thanks!
