### ISSUE TITLE
Map about Tibet and Taiwan in China

### ISSUE THREAD

**Issue by peanode** [piwik/piwik#8557]
I'm a fresh user of Piwik, and i want to use it for my a million visitors per month website.But I saw there are one wrong thing of the map of china,which may cause some errors and other problems.
Tibet is a province of China.

some person will not use the WRONG MAP piwik from China,including me.If you take this into consideration, please correct it,thanks.

![20150812_230744_01](https://cloud.githubusercontent.com/assets/10267344/9227844/2d9352cc-4148-11e5-98c3-0ad298fc03c2.png)

**Comment by sgiehl** [comment]
duplicates #6006.

**Comment by khlipeng** [comment]
Tibet is a province of China.
