### ISSUE TITLE
Setup demo3.piwik.org to showcase Piwik 3

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8560]
The goal of this issue is to create demo3.piwik.org - which will showcase Piwik 3.0 from git branch. We will update the server continuously to always use the latest 3.0 branch.

How to generate data on demo3? maybe the tracker can be added in forum.piwik.org and/or replay the traffic from demo or demo2 (to avoid having to add a new demo3 JS tracker to our websites)

Steps
- [x] Create demo3, continuously deployed
- [x] Push tracking data to demo3
- [x] Add demo3 to monitoring checks
- [ ] Make demo3 available to anonymous user so everyone can view it

**Comment by iMarkus** [comment]
Good idea. Looking forward.

**Comment by MagicFab** [comment]
Reproducing the same segments, goals, reports, dashboards etc. would also be helpful for comparison purposes.

**Comment by tsteur** [comment]
moving this to 3.0.0-RC for now

**Comment by mattab** [comment]
This was done with http://demo-anonymous.piwik.org/ and we'll update demo.piwik.org to Piwik 3 tomorrow or so in https://github.com/piwik/piwik/issues/10944
