### ISSUE TITLE
 in the website selector display tooltip with full website name

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#8569]
When searching for a meta site or websites with long names the autocompleter should display a tooltip with the complete website name or the width of the autocompleter should be increased

Currently it is very hard to differ between some partly equal websites or meta site names

**Comment by mattab** [comment]
Same problem with website groups: 

![piwik_user](https://cloud.githubusercontent.com/assets/9717272/5026997/63fe74a8-6b2a-11e4-87af-0734abf264ed.png)

**Comment by tsteur** [comment]
Have you tried the pull request? does it not work?
