### ISSUE TITLE
Visitor Log Segmenting No Longer Works

### ISSUE THREAD

**Issue by thomcasey** [piwik/piwik#8570]
Updated to 2.14.3 earlier this week and have noticed my previously setup segments no longer work.

**Comment by quba** [comment]
Could you provide an example?

**Comment by thomcasey** [comment]
How would you like the example provided? Via screenshot?

**Comment by quba** [comment]
Segment definition for example. It's available in the URL (@segment=...).

**Comment by thomcasey** [comment]
There were two segments in the URL, and I'm not sure which you wanted. 

http://******.com/index.php?module=CoreHome&action=index&idSite=2&period=day&date=yesterday&segment=pageUrl%3D%40checkout#/module=Live&action=indexVisitorLog&idSite=2&period=day&date=yesterday&segment=pageUrl=@checkout

**Comment by quba** [comment]
Works for me on 2.14.3

**Comment by mattab** [comment]
Hi @thomcasey - this should work fine. please try again with latest Piwik beta: piwik.org/faq/how-to-update/faq_159/

if you still have a problem, re-open the issue or create a new one
