### ISSUE TITLE
Sync UI test screenshots command not working

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8573]
In travis build it says one should use

`./console tests:sync-ui-screenshots 14546.7` which doesn't work (`Screenshot tests artifacts were not found for this build. `), the UI tests viewer says one should use `./console tests:sync-ui-screenshots -r piwik/piwik 14767` which doesn't work either (` The "-r" option does not exist`).

It would be nice if we not had to specify branch `piwik/piwik` by default.

**Comment by mnapoli** [comment]
Forgot to open #8577 yesterday.

**Comment by mnapoli** [comment]
Btw feel free to ask on Slack, I could have answered faster.
