### ISSUE TITLE
Bug with API - method: MultiSites.getAll - if period of report is more than 1 month

### ISSUE THREAD

**Issue by diginet-md** [piwik/piwik#8576]
1) We use PIWIK - 2.14.3.

2) We use PIWIK - API
method:   MultiSites.getAll

3) for example
3.1) for 14 days - the data is available
https://analytics.diginet-solutions.com/?module=API&method=MultiSites.getAll&period=range&date=2015-08-01,2015-08-14&format=xml&token_auth=8fa1661cdf89f6f7668bac542db3927f

3.2) for period 45 days - empty reply
https://analytics.diginet-solutions.com/?module=API&method=MultiSites.getAll&period=range&date=2015-07-01,2015-08-14&format=xml&token_auth=8fa1661cdf89f6f7668bac542db3927f

4) Question
what is the reason

**Comment by mattab** [comment]
Hi @diginet-md 

Please check your server logs for errors, see: https://piwik.org/faq/troubleshooting/faq_19489/

This should work fine. if you can reproduce the problem on the demo let us know
