### ISSUE TITLE
Make Piwik opt-out feature work on internet explorer 11 when third party cookies are disabled

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8578]
Follows up #3135

Let's make the Opt-out iframe work on IE11 as well. It may be as "easy" as changing https://github.com/piwik/piwik/blob/icons/plugins/CoreAdminHome/OptOutManager.php#L153-154 and testing on IE11.

**Comment by tsteur** [comment]
What should be changed there in this line?

**Comment by mattab** [comment]
Maybe we could use the "safari code path" for all browsers rather than just for safari? 

(on safari, when opting out, Piwik opens a popup in a new window that set the  cookie on the third party domain - which is slightly less good UX - but it would work in all browsers even when third party cookies may be disabled)

**Comment by diosmosis** [comment]
@mattab I've managed to get the popup approach working on IE11, however the approach will break on every browser, if a pop-up blocker is used.

I will repeat myself: first party cookies is the only way to solve this problem in the long-term.

**Comment by mattab** [comment]
> I will repeat myself: first party cookies is the only way to solve this problem in the long-term.

left a comment in related issue: https://github.com/piwik/piwik/issues/6505#issuecomment-136507516

**Comment by mattab** [comment]
PR: #8646

**Comment by mattab** [comment]
Fixed in #8646 - you can test this is working in piwik 2.15.0-b5

**Comment by Cruiser13** [comment]
Thanks, works like a charm in IE 11. No issue with popup blockers aswell.
