### ISSUE TITLE
Make Piwik show all campaign details in Visitor log and Visitor Profile

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8581]
Since in #8140 campaign details in Visitor Log and Visitor Profile are made professional looking similar,
the next obvious step would be (as already mentioned in the cited ticket)

**to make at this two places all available details about the campaign shown,
 including these from Advanced Campaign Reporting Plugin**:

1. campaign,
2. source,
3. medium,
4. keyword,
5. content

Since this Plugin is really widely used by people who are doing serious campaign tracking
(already about 3899 downloads till today, which should be a big part of all campaign trackers and make it de-facto  a "standard" and "must have" plugin)
I'm not quiet sure where to allocate this feature best.
It is already documented in
PiwikPRO/plugin-AdvancedCampaignReporting#25
PiwikPRO/plugin-AdvancedCampaignReporting#26

but maybe it would also fit perfectly here within "Main-Piwik"

**Comment by mattab** [comment]
Hi @hpvd 

Campaign Name + Keyword, is displayed in Visitor Log.

For displaying Advanded campaign reporting dimensions in Visitor Log (which would be awesome!) please create issue in the AdvancedCampaignreporting tracker: https://github.com/PiwikPRO/plugin-AdvancedCampaignReporting/issues

**Comment by hpvd** [comment]
@mattab 
ticket is already there since June 16. :-)
https://github.com/PiwikPRO/plugin-AdvancedCampaignReporting/issues/26
