### ISSUE TITLE
Version 2.14.3:  Cannot activate branding -- no upload of image files

### ISSUE THREAD

**Issue by canajun2eh** [piwik/piwik#8582]
I am running Piwik version 2.14.3, and using Firefox 39.0.3 on a Windows 7 laptop to access Piwik.

In the server's Piwik directories, I have set 777 permissions for file /config/config.ini.php and for directory /misc/user and all its contents.

When I click on the radio button "Yes" under the heading "Branding settings" on the "Administration" --> "Settings" --> "General" page, the file upload dialog correctly opens, and the "Browse" buttons let me browse my laptop for the desired Logo and Favicon files.  

In the Browse dialog, I have selected JPG files with minimum sizes as recommended on the "Branding settings" page.  Aftre clicking the "Open" button on my laptop's Browse dialog, the upload of the selected files does not appear to take place;  the "misc/users" directory still contains only the two files that come with Piwik.  The same thing happens when I use JPG files that exceed the recommended minimum sizes.  The file names are of the form "foo.jpg" and "bar.gif" -- I have not tried "foo.JPG".

When I exit from Piwik and access it again, the "Branding settings" dialog has the "Yes" radio button set as expected, but does not show the expected thumbnails for the files that should have been uploaded.

**Comment by sgiehl** [comment]
I've tried to reproduce. But it works for me without problems. If the directory/files wouldn't be writable Piwik should display a warning. 
Piwik is using gd lib to create the images, maybe that doesn't work on your server? You can have a look at Piwik's System Check, it should report if the GD version is correct.

**Comment by canajun2eh** [comment]
This issue can be closed.  It was caused by a server mis-configuration.  The GD library was not properly installed.

Perhaps the system sanity check should look for this error.
