### ISSUE TITLE
RFE: Add plugin notifications in the main dashboard, like regular notifications

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#8585]
This is a request to add plugin notifications in the same place as regular Piwik upgrade notifications.

When plugins need to be updated there is an indicator (number) next to the plugins label in the administration menu. This requires actively looking into this menu.

Plugin upgrade notifications could also be aligned with reguler / point release upgrade Piwik notifications. 

These are just suggestions, the main goal is to make plugin upgrade notifications more visible.

**Comment by tsteur** [comment]
Sounds very useful :+1:  Similar thing was suggested in #6701 . Do you mind adding your comment there? Will close this one as a duplicate.
