### ISSUE TITLE
PIWIK reports

### ISSUE THREAD

**Issue by hassanfarhad** [piwik/piwik#8588]
HI
do you know bounce rate(in Visitors-overview-Evolution over the period) what exactly means?
![piwik pic](https://cloud.githubusercontent.com/assets/13116885/9324262/da8b9120-459d-11e5-92f2-3da9e6fb2953.jpg)

**Comment by mattab** [comment]
Hi @hassanfarhad 

please use forum to ask questions: http://forum.piwik.org/

you can also click on the HELP icon next to the title, to open a documentation that explains what bounce rate means
