### ISSUE TITLE
UI tests fail depending on the PHP version

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8592]
In the admin screens we show a "Your PHP is deprecated notification" if one is using PHP 5.3/5.4. The UI tests currently run on these versions meaning we expect such a notification to be displayed. If one is running the UI tests on a newer PHP version many tests will fail as they do not display such a message.

In the "Tests" session during our meetup we talked about running UI tests on PHP 5.5 or PHP 5.6 to avoid having this message displayed. This would mean we have no longer any tests running on the minimum PHP version. Would that be okay? I guess that's what we maybe have beta releases etc for. One downside would be that tests would still break if one is using the minimum PHP version.

We could alternatively hide this notification in the UI (eg via CSS) and make it work on all PHP versions.

Targeting 2.15.1 for now as this version will be supported for like a year and it will be helpful for plugin developers etc. Could also move it to 3.0.0 maybe

**Comment by mattab** [comment]
> We could alternatively hide this notification in the UI (eg via CSS) and make it work on all PHP versions.

Maybe we could we go with this solution VS running UI tests on php 5.5? (running tests on PHP 5.3 has some value, when we don't rely only on beta testers to report issues and CI may catch some bugs).

**Comment by mattab** [comment]
Suggestion:

* in LTS branch, we hide the notification and run UI test on php 5.3
* in Piwik 3.0 branch, we can run UI tests on PHP 5.5

**Comment by tsteur** [comment]
Sounds good to me.
