### ISSUE TITLE
GET request to piwik.php failed

### ISSUE THREAD

**Issue by francoisromain** [piwik/piwik#8596]
Trying to install Piwik (on gandi simple hosting) there is this error at the step 2: 

    GET request to piwik.php failed. Try whitelisting this URL from HTTP Authentication and disable mod_security

However, there is no 'mod_security' on my server. Here is the list of the loaded modules: 

    core.c, event.c, http_core.c, mod_access_compat.c, mod_alias.c, mod_auth_basic.c, mod_auth_digest.c, mod_authn_core.c, mod_authn_file.c, mod_authz_core.c, mod_authz_host.c, mod_authz_user.c, mod_autoindex.c, mod_deflate.c, mod_dir.c, mod_env.c, mod_expires.c, mod_fastcgi_handler.c, mod_filter.c, mod_headers.c, mod_include.c, mod_info.c, mod_log_config.c, mod_mime.c, mod_negotiation.c, mod_remoteip.c, mod_rewrite.c, mod_setenvif.c, mod_so.c, mod_status.c, mod_unixd.c, mod_vhost_alias.c,

and here is the error.log from Apache

    [Tue Aug 18 22:35:43.653608 2015] [auth_digest:notice] [pid 261:tid 3400658421568] AH01757: generating secret for digest authentication ...
    [Tue Aug 18 22:35:43.654521 2015] [mpm_event:notice] [pid 261:tid 3400658421568] AH00489: Apache/2.4.12 (Unix) configured -- resuming normal operations
    [Tue Aug 18 22:35:43.654534 2015] [core:notice] [pid 261:tid 3400658421568] AH00094: Command line: '/usr/sbin/apache2 -d /srv/data/.config/apache -f apache2.conf'

**Comment by sgiehl** [comment]
There is also no HTTP Authentication using htaccess or something similar?

**Comment by francoisromain** [comment]
nop. nothing.

**Comment by sgiehl** [comment]
Are you able to open piwik.php in your browser?

**Comment by francoisromain** [comment]
no: '500 (Internal Server Error)'

**Comment by sgiehl** [comment]
Do you have access to the error logs of your server? Maybe you can find an error there...

**Comment by francoisromain** [comment]
Php error.log: (I replaced the actual name with `mysite`)

    [24-Aug-2015 19:42:00 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'The configuration file {/srv/data/web/vhosts/stats.mysite.com/htdocs/config/config.ini.php} has not been found or could not be read.' in /srv/data/web/vhosts/stats.mysite.com/htdocs/core/Application/Kernel/EnvironmentValidator.php:64
    Stack trace:
    #0 /srv/data/web/vhosts/stats.mysite.com/htdocs/core/Application/Kernel/EnvironmentValidator.php(45): Piwik\Application\Kernel\EnvironmentValidator->checkConfigFileExists('/srv/data/web/v...', false)
    #1 /srv/data/web/vhosts/stats.mysite.com/htdocs/core/Application/Environment.php(185): Piwik\Application\Kernel\EnvironmentValidator->validate()
    #2 /srv/data/web/vhosts/stats.mysite.com/htdocs/core/Application/Environment.php(94): Piwik\Application\Environment->validateEnvironment()
    #3 /srv/data/web/vhosts/stats.mysite.com/htdocs/piwik.php(56): Piwik\Application\Environment->init()
    #4 {main}
    thrown in     /srv/data/web/vhosts/stats.mysite.com/htdocs/core/Application/Kernel/EnvironmentValidator.php on line 64

**Comment by sgiehl** [comment]
Hm. Ok. The tracker status is checked on the installation page using ajax. Guess that request will return a 500 aswell. To ignore that check for now, try to remove the ```&trackerStatus=XXX``` from the URL in your browser.

**Comment by francoisromain** [comment]
I removed it, but passing from step 3 to step 4 returns this error: 

    Test SQL failed to execute: CREATE TABLE piwik_test_table ( id INT AUTO_INCREMENT, value INT, PRIMARY KEY (id), KEY index_value (value) )Error: SQLSTATE[HY000]: General error: 1005 Can't create table 'piwik.piwik_test_table' (errno: -1)

**Comment by sgiehl** [comment]
Maybe your database user does not have the correct rights to create a table

**Comment by mattab** [comment]
Please try again with 2.15.0 beta: piwik.org/faq/how-to-update/faq_159/

> General error: 1005 Can't create table 'piwik.piwik_test_table' (errno: -1)

as @sgiehl wrote, there is likely not enough permission to create database table. please ask your web host

**Comment by dev-101** [comment]
I also got this problem, bypassed temporarily as advised, and later got problem connecting with db.
Problem was solved by replacing 127.0.0.1 with `localhost`, not sure, but it should be the same (hosts).

**Comment by xros** [comment]
@dev-101 @sgiehl The latest stable version 2.15.0, still has this bug. But if you delete the **&trackerStatus=XXX** from URL, it works. And yet it has no error of DB connection no matter "localhost" or "127.0.0.1".
