### ISSUE TITLE
Potential spam source

### ISSUE THREAD

**Issue by ford-prefect** [piwik/piwik#8609]
I've got the following URL on my Piwik instance turning up in spam emails, and it redirects to a spam website:

http://piwik.arunraghavan.net/large.php?Bradley_Warner

I've had to take down the URL for now. Any reason why this works at all? Something I'm missing?

I'm running 2.14.3.

**Comment by mattab** [comment]
Hi there, I don't understand the question. can you ask in our forums? http://forum.piwik.org/

**Comment by ford-prefect** [comment]
I've tried to clarify in http://forum.piwik.org/read.php?2,128950
