### ISSUE TITLE
UsersManager add user row inputs should use placeholder instead of value

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8611]
As title. If you go to the users manager table and click the add button, a new row is displayed. If you click on the login, the placeholder value `'login?'` is not removed. This is because the `<input>`s use `value=...` instead of `placeholder=...`.

**Comment by tsteur** [comment]
:+1:  Reckon it used be like that for older browsers

**Comment by mnapoli** [comment]
PR: #8628
