### ISSUE TITLE
core:archive output is sometimes too verbose  eg. "0 visits in last last260 weeks,"

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8612]
Our goal is to make Piwik the easiest possible to use and manage. This includes our console commands which should output messages that make sense to everyone.

Recently we've made several improvements to the `core:archive` command messages in #7723 #7536 #8214 and in this issue we'll make the output a little better.

Currently it looks like this:
```
INFO CoreConsole[2014-12-15 23:18:29] [9369d] Archived website id = 14, period = week, 0 visits in last last260 weeks, 0 visits this week, Time elapsed: 15.551s
INFO CoreConsole[2014-12-15 23:18:35] [9369d] Archived website id = 14, period = month, 0 visits in last last52 months,
```

I suggest we simply remove the part ` visits in last last260 weeks, ` / `0 visits in last last52 months,` as it is not useful, and is confusing to some users. This small change was requested by Piwik PRO team.

**Comment by tsteur** [comment]
What is the confusing part here or why is it confusing?

**Comment by mattab** [comment]
Thanks for asking. I remembered this PR was opened:  Fixed double last last messages in core:archive #7807  which would solve the problem of double `last last`. 

Besides this small issue, i'm not actually sure what is confusing. I'm asking for more details, will update here next week.

**Comment by mattab** [comment]
it's not confusing. especially that the core:archive was already improved in 2.13.0 (but this user was using earlier version with less verbose core:archive output). Nothing to do
