### ISSUE TITLE
Issue with tracking an ERP system on my intranet

### ISSUE THREAD

**Issue by ybuffetaud** [piwik/piwik#8617]
Hello we'are using Piwik to track our ERP activity (oracle JD Edward's).
The tracking is fine except the following :+1: 
    - Each time a user is connecting to our ERP (this is an URL which is published over citrix), the tracked vistor IPs are IPs of the citrix. It can be OK but in our ERP login page I Have the following : 
<TR><TD class="loginText" NOWRAP><LABEL FOR="User">User ID:</LABEL></TD><TD><INPUT SIZE=15 class="textfield" TYPE=text NAME="User" ID="User" VALUE=""  ></TD></TR>
I'd like to had to the visitor page the name of the textfield User

-Then when the pages are stored I have the title, this is fine but I'd like to also have an supplemental info which is stored on the HTML : 
<SPAN style="display: none" id="formOID">P01012_W01012B_ZJDE0001</SPAN>
This is to say the value of the SPAN =>P01012 => this represent the name of the app the user is running.

For your info the piwik tracker code is only set in one .js for our ERP. this .js is called everywhere

**Comment by mattab** [comment]
hi @ybuffetaud 

please use forum to ask for support: forum.piwik.org
or contact [Piwik PRO](piwik.pro) for professionnal support
