### ISSUE TITLE
Remove deprecated Piwik\Archive::getDataTableFromArchive()

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#8619]
`Piwik\Archive::getDataTableFromArchive()` should be removed in 3.0 and there's a test for this. However I'll be removing the test and opening it as an issue instead because as long as this method isn't removed unit tests will be failing (which isn't really what we want).

**Comment by tsteur** [comment]
This was done recently in https://github.com/piwik/piwik/commit/6102454146b673a16ab7f45de391e8f1ae8a096e
