### ISSUE TITLE
The reporting menu should not use the module= query param in the URL to determine the active menu section

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8624]
If a plugin adds it's own page to an existing menu section (say, for example, to the Goals plugin), the menu will not be selected when the plugin's page is loaded. This is because Piwik will only activate/highlight the Goals plugin section if the module is `'Goals'`, but since the page is added by another plugin, the module will be different.

The menu JS should use another mechanism to figure out which menu section is currently active.

**Comment by tsteur** [comment]
FYI: For reporting menu it already works differently in `3.0` branch

**Comment by mnapoli** [comment]
Is it necessary to fix it in 2.15 if it's already changed in 3.0 then?

**Comment by diosmosis** [comment]
It is necessary if @mattab still thinks it is required to fix the problem affecting a new plugin. Probably a good idea either way for the LTS version.

**Comment by mattab** [comment]
I think it would be nice to fix if it is easy, ie. can be done in less
than 1h. Otherwise Imho it will be OK to wait for 3.0 where this is
already fixed.
