### ISSUE TITLE
Campaign tracking via HTTP API does not seem to work

### ISSUE THREAD

**Issue by rysiekpl** [piwik/piwik#8630]
I am trying to get Piwik to track campaigns. I am using Piwik Tracking API via [`piwik-php-tracker`](https://github.com/piwik/piwik-php-tracker). In my code [I set the attribution info](https://github.com/occrp/piwik-reprint-tracker/blob/master/php/index.php#L71) -- properly, I think, as it gets recorded in the cookies and is available via `getAttributionInfo()` call.

Specifically, this means that the `_rcn` and `_rck` params of the Piwik HTTP Tracking API call get set. Apparently they are, and they do get passed to Piwik via HTTP, as I can see them in the debug output (I added a bit of logging here and there to Piwik to trace what's happening).

Here's the HTTP request that gets made by `PiwikTracker.php`:

```
http://piwik.example.com//piwik.php?idsite=1&
rec=1&
apiv=1&
r=321068&
cip=146.255.142.15&
token_auth=<valid_token>&
_idts=1440365318&
_idvc=18&
_id=5c736ce5392b0dfa&
url=https%3A%2F%2Fwww.example.com%2Freprints%2FNewCampaign.testkeyword.jpg&
urlref=http%3A%2F%2Frys.io%2Fstatic%2Fpiwik-ref-test.html&
_rcn=NewCampaign&
_rck=testkeyword&
_refts=1440409791&
_ref=http%3A%2F%2Frys.io%2Fstatic%2Fpiwik-ref-test.html&
action_name=Reprint+Tracker+for%3A+NewCampaign+%28keyword%3A+testkeyword%29
```

However, they are being completely ignored, it would seem. "Campaigns" report has "no data", or at least no data about the campaigns that are supposed to be tracked this way, even though visits do get recorded and the referrer info (i.e. referrer URL) gets set properly.

Curiously, campaigns tracked via `pk_campaign` query param in URLs seem to work properly also.

I am using Piwik 2.13.x (upgrading to 2.14.x postponed here until we can sort this one out).

**Comment by rysiekpl** [comment]
Anybody any comments on this?

**Comment by mattab** [comment]
Thanks for the report @rysiekpl I was able to reproduce the issue. we'll investigate

**Comment by rysiekpl** [comment]
Thanks. If it helps, I can do an upgrade to Piwik 2.14.x on our testing infrastructure and test it out for you.
