### ISSUE TITLE
Icon update follow up issue: clarify row evolution row compare button/link design

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8632]
Follow up issue for https://github.com/piwik/piwik/pull/8488

The design of the row evolution 'Pick a Row' link/button is still a point of contention in old PR. This issue should be closed when it is clarified what the link should look like.

The original design of the link looks like this:

![row_evolution_link](https://cloud.githubusercontent.com/assets/125140/9446636/9265e20c-4a47-11e5-8409-83d461f36aff.png)

It was originally changed to this in the PR:

![row_evolution_link_1st_change](https://cloud.githubusercontent.com/assets/125140/9446659/aadd3ef2-4a47-11e5-97f8-8b0467ef6400.png)

Then it was partially reverted to this (which was merged):

![row_evolution_2nd_change](https://cloud.githubusercontent.com/assets/125140/9446717/ee23edaa-4a47-11e5-9b35-825292c497d3.png)

CC @mattab @tsteur

This should be resolved before 2.15 is released.

**Comment by tsteur** [comment]
I prefer the old style but for consistency it should be probably the new one. Maybe we can move it at least further to the left?

**Comment by mattab** [comment]
> Maybe we can move it at least further to the left?

+1
