### ISSUE TITLE
Can't get unique visitors in specified timestamp range

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8635]
The unique visitors will show up in the following time:
![qq20150825-1 2x](https://cloud.githubusercontent.com/assets/2368001/9463703/15112f36-4b51-11e5-9b13-70c8c02f368d.png)

But can't get unique visitors in specified timestamp range, why?

**Comment by tsteur** [comment]
Do you mind translating what it says? That would be helpful. You can also change the language to English temporarily by clicking on your username in top right.

**Comment by jerrycave** [comment]
As you suggested, here's the detail.
![qq20150826-1 2x](https://cloud.githubusercontent.com/assets/2368001/9487125/99196f2c-4c01-11e5-9786-3f136df3a2f0.png)
I can get the unique visitors at the bottom right;

But I can't get unique visitors when specify the date range.
![qq20150826-2 2x](https://cloud.githubusercontent.com/assets/2368001/9487174/d360e020-4c01-11e5-98f3-afc60f7b41eb.png)

**Comment by tsteur** [comment]
Thx! Please have a look here: http://piwik.org/faq/how-to/faq_113/

You need to enable it specifically if you want to use it.

**Comment by jerrycave** [comment]
Thx!
