### ISSUE TITLE
Feature request: Email on events and/or Goals

### ISSUE THREAD

**Issue by srmobile** [piwik/piwik#8645]
Have been using Piwik for over a year, love it!

I would really like to see an option to have certain events or goals emailed to me when they are triggered.

I think this would be a really beneficial feature and easy to implement since Piwik already communicates with an email server and events and goals are monitored in real-time.

Thank you to the Piwik team!

SR

**Comment by tsteur** [comment]
Do you mind explaining it a bit more detailed? Maybe with an example? It might be already possible to develop it in a plugin in case someone would be interested on working it

**Comment by srmobile** [comment]
So basically right now it is possible to setup events and goals. I would want to have an email sent to me when certain events are triggered.

Example for my eCommerce store I have an event for "add to cart" I  can see this when I look at the history but would like to also receive an email when this particular event is triggered.

Thanks

SR

**Comment by tsteur** [comment]
It might be possible to do this by http://plugins.piwik.org/CustomAlerts but it would send this email only at midnight (in the website's timezone) not as soon as the event is triggered.

**Comment by mattab** [comment]
Hi @srmobile 
Thanks for suggestion. this feature you request is what I meant in this other issue: https://github.com/piwik/piwik/issues/6209

it would be great if you could leave a comment on this other issue with your use case. I believe there is huge potential to build something very useful for many use cases :-)
