### ISSUE TITLE
Does it possible to add a column called unique visitors in the page of 'All Websites' ?

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8647]
As you can see the snapshot below:
![qq20150827-1 2x](https://cloud.githubusercontent.com/assets/2368001/9510829/b4ad794e-4ca2-11e5-87e1-4978d84e2754.png)

It's quiet convenient for users to take a glance at important index, including visits, pageviews etc, but don't have the index of unique visitors, is it possible to add it in this page?

**Comment by gaumondp** [comment]
Maybe you should add your voice in #5150 (Customizable columns in All Websites Dashboard)

**Comment by tsteur** [comment]
As @gaumondp  there is already an issue about this. Apart from the mentioned one the current active issue for this is https://github.com/piwik/piwik/issues/2390 . There's also https://github.com/piwik/piwik/issues/5045
