### ISSUE TITLE
Add method to piwik.js that let's you debug which content blocks are on your page

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8650]
While helping a user to figure out via no content impressions are shown in the UI ( http://forum.piwik.org/read.php?15,122599,129060 ) I noticed it would be very helpful to have a method that let's you get all detected content blocks. Either just the dom nodes or a JSON array containing all content blocks like   

```
[{name: '...', target:'...', piece: "..."},...]
```

It could by default just log to the console via `logAllContentImpressions()`

**Comment by mattab** [comment]
Notes from PR:

> After merging I will document in JS Tracker: http://developer.piwik.org/api-reference/tracking-javascript and content tracking guide: http://developer.piwik.org/guides/content-tracking

Also, let's add the new method to dev changelog

**Comment by tsteur** [comment]
It was already in dev changelog

**Comment by tsteur** [comment]
Done
