### ISSUE TITLE
Reoccurring Visitors in wrong Order

### ISSUE THREAD

**Issue by Flux3PO** [piwik/piwik#8652]
Hi,

I just realized that if someone visits my site at least twice, the 1st visit is listed as visit #2 and the 2nd visit is listed as visit #1 (see screenshot)

![Uploading piwik-order.png…]()

**Comment by Flux3PO** [comment]
Upload does not seem to like me

http://s27.postimg.org/rcbi63r83/piwik_order.png

**Comment by tsteur** [comment]
I presume this is a duplicate of https://github.com/piwik/piwik/issues/8491 ?

**Comment by Flux3PO** [comment]
Yepp, sorry did not found this when using the search
