### ISSUE TITLE
2.15.0-b3: Notice re undefined index exclude_unknown_urls

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8654]
WARNING: /home/vagrant/www/piwik/plugins/SitesManager/SitesManager.php(120): Notice - Undefined index: exclude_unknown_urls - Piwik 2.15.0-b3 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

![screenshot at aug 28 10-33-23](https://cloud.githubusercontent.com/assets/273120/9542351/421f0f5e-4d70-11e5-81c1-07602637abc1.png)

**Comment by diosmosis** [comment]
Do you see the exclude_unknown_urls column in the `site` table?

**Comment by tsteur** [comment]
Nope, I presume the update wasn't inserted because of some weird switching between branches or so. Closing it for now and executing update manually

**Comment by tsteur** [comment]
FYI: I just had a similar problem that an update was again not executed and noticed it is probably because of this commit: https://github.com/piwik/piwik/commit/90372750b039ce0b2150d4d6b1279fecbb245465 I might create an issue about this
