### ISSUE TITLE
Add event_category to import_logs.py help

### ISSUE THREAD

**Issue by jifwin** [piwik/piwik#8656]
When trying to import some events from my custom log I figured out that event_category parameter is missing in available_regex_groups. Without this parameter events don't get tracked, which is quite confusing to a user.

**Comment by mattab** [comment]
Hi @jifwin 
Thanks for the report. I've created issue in other tracker at: https://github.com/piwik/piwik-log-analytics/issues/98 - feel free to comment there as well (maybe there are other regex group we should add at the same time)
