### ISSUE TITLE
Can't show chinese character in the piwik log table?

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8670]
As you can see below, the chinese character can't be shown in the log table:
![chn](https://cloud.githubusercontent.com/assets/2368001/9570899/ca540b8c-4fc7-11e5-8647-1d5253b3377a.png)

Here's the DDL of this table:
![test](https://cloud.githubusercontent.com/assets/2368001/9570964/f660988e-4fc8-11e5-97e5-58341c8fa64e.png)

But other tables are able to show chinese character, why?

**Comment by mattab** [comment]
Hi there, these fields are stored in Binary format, see this FAQ for more details: http://piwik.org/faq/how-to/faq_158/
