### ISSUE TITLE
Release LoginSamlSSO plugin on the Marketplace

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8673]
The goal of this issue is to release our LoginSamlSSO plugin on the Marketplace
 
 * plugin location: https://github.com/PiwikPRO/plugin-LoginSamlSSO/
 * Steps:

 * [ ] Setup on Travis CI and make build green
 * [ ] Check file headers are correct
 * [ ] Do a security review of the plugin
 * [ ]  Check Readme is useful
 * [ ] Check UI is usable 
 * [ ] [Release on the Marketplace](http://developer.piwik.org/guides/distributing-your-plugin)

**Comment by sgiehl** [comment]
Note: If this plugin will be fully open source, we could add the translations to transifex

**Comment by mattab** [comment]
whether this is done will depend on Piwik PRO, i'm not sure what they are planning there...

**Comment by mattab** [comment]
SAML plugin is now available on the Marketplace! Please learn more here: http://plugins.piwik.org/LoginSaml

and in our SAML User Guides: https://piwik.org/docs/login-saml/
and the Login SAML Faqs: https://piwik.org/faq/login-saml/

If you need help we can provide some support for SAML, learn more here: https://piwik.org/support/login-saml/
