### ISSUE TITLE
How to run tests ?

### ISSUE THREAD

**Issue by dhoko** [piwik/piwik#8678]
Hi,

I read `tests/README.md` in order to run tests, but it doesn't work.

```sh
$ ./console tests:run core
Executing command: cd /home/dhoko/dev/piwik/tests/PHPUnit && /home/dhoko/dev/piwik/vendor/phpunit/phpunit/phpunit   ../../tests/PHPUnit
PHP Warning:  require_once(/home/dhoko/dev/piwik/libs/PiwikTracker/PiwikTracker.php): failed to open stream: No such file or directory in /home/dhoko/dev/piwik/tests/PHPUnit/bootstrap.php on line 41
PHP Fatal error:  require_once(): Failed opening required '/home/dhoko/dev/piwik/libs/PiwikTracker/PiwikTracker.php' (include_path='/home/dhoko/dev/piwik/vendor/pear/pear_exception:/home/dhoko/dev/piwik/vendor/pear/console_getopt:/home/dhoko/dev/piwik/vendor/pear/pear-core-minimal/src:/home/dhoko/dev/piwik/vendor/pear/archive_tar:/home/dhoko/dev/piwik/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear:/home/dhoko/dev/piwik/vendor/bin:/home/dhoko/dev/piwik/core:/home/dhoko/dev/piwik/libs:/home/dhoko/dev/piwik/plugins') in /home/dhoko/dev/piwik/tests/PHPUnit/bootstrap.php on line 41
```

**PiwikTracker.php** does not exist :-1: 

```sh
$ find . -name '*.php' ! -path '*vendor*' | grep 'PiwikTracker'
./misc/others/ExamplePiwikTracker.php
```

PS: You need to copy `Tests/Config/config.ini.php` and paste it to config/ to be abe to run tests..

**Comment by sgiehl** [comment]
did you init the submodules after checking out piwik from git?

**Comment by dhoko** [comment]
Nop I followed this
https://github.com/piwik/piwik/blob/master/tests/README.md

**Comment by sgiehl** [comment]
ah ok. Guess it's missing there
```git submodule init```

**Comment by dhoko** [comment]
Hum it doesn't work too :) 

We need to run `git submodule update --recursive`

**Comment by dhoko** [comment]
Do you have a docker for piwik ? 
To run tests:
- clone
- fetch submodule
- composer install + --dev
- copy config etc.
- php5-sqlite
- php5-mysql
- config db

etc.

**Comment by tsteur** [comment]
FYI: I issued a PR to update docs re installing Piwik.

There are many dockers available but no official one. There's one based on vagrant though: https://github.com/piwik/piwik-dev-environment Nonetheless you should find many dockers eg via google

**Comment by mnapoli** [comment]
@dhoko FYI there's a branch for running Piwik and its tests with Docker: https://github.com/piwik/piwik/compare/docker Or vagrant in #8542.
