### ISSUE TITLE
Ignore Do Not Track setting for Gnome Epiphany browser.

### ISSUE THREAD

**Issue by ChALkeR** [piwik/piwik#8682]
Similar: #4482, #3486.

Epiphany broke DNT support, it now sends DNT headers by default: https://git.gnome.org/browse/epiphany/commit/?id=4ff8705155fda53460bc9dfdc1de6c14e83880a1.
It's not a user preference anymore (as it should be), it's a default setting, which breaks the purpose behind DNT.

The user agent includes `Epiphany/{version}`, latest version that did not break DNT was `Epiphany/3.17.2`.

**Comment by ChALkeR** [comment]
http://www.w3.org/TR/tracking-dnt/
> A user agent must have a default tracking preference of unset (not enabled) unless a specific tracking preference is implied by the user's decision to use that agent.

**Comment by tsteur** [comment]
We do now ignore DNT for Epiphany. @mattab unfortunately we have to ignore all versions of Epiphany but I think that's ok for now? To respect the users privacy using an earlier version it would be nice to be able to specify a min browser version to ignore. It's possibly not needed in this case and I'll close it for now. Feel free to reopen if it's needed already.
