### ISSUE TITLE
Disable not available release channels and explain why they are not available

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8710]
refs https://github.com/piwik/piwik/issues/8549 see suggestion in https://github.com/piwik/piwik/issues/8549#issuecomment-137228848

It would be nice to disable not available release channels and on hover explain why they are not available. Eg because a specific PHP version is required. 

We could on top show in system check page available release channels.

**Comment by mattab** [comment]
likely we won't implement this, we can re-open if needed
