### ISSUE TITLE
Move website selector to a more prominent postition

### ISSUE THREAD

**Issue by raj45** [piwik/piwik#8712]
The website drop-down selector should be moved next to the logo.

Regular users of Piwik know where to look, but the drop-down website selector is nearly impossible to find for first-time users, at the far right side of the screen.

Almost everybody at my company have a hard time finding it, so they can't change web site, until I show them where the drop-down is.

![piwik-better-website-selector](https://cloud.githubusercontent.com/assets/7046001/9684493/44ca1b7e-5318-11e5-9bad-f4563c12d28d.png)

**Comment by tsteur** [comment]
I think it could also logically make sense since when changing the website everything below that changes including the reporting menu (it can change). I read a good blog post about this a year or two ago but cannot find it anymore. 

FYI: We will move the reporting menu to the left at some point in https://github.com/piwik/piwik/issues/7169 it might be better to see then, even when it is on the same level as date and segment selector

**Comment by MagicFab** [comment]
It would probably make sense for it to be left of the date selector.

**Comment by MagicFab** [comment]
Unless I am mistaken this has been implemented now? I see it left of the date selector on the demo site running the latest 2.15 beta: http://demo.piwik.org/

**Comment by tsteur** [comment]
We have enabled the left menu there... you won't see it when viewing demo as a anonymous user. We're working on improving the left menu view and making it default

**Comment by tsteur** [comment]
BTW: One can enable it under Administration => Plugin Settings. If it doesn't show there one needs to enable the left menu plugin itself under Administration => Plugins

**Comment by mattab** [comment]
This will be done as part of the redesign, where the website selector will be located in a more meaningful place: https://github.com/piwik/piwik/issues/7589#issuecomment-144649158

**Comment by raj45** [comment]
Great, thanks.

**Comment by MagicFab** [comment]
@raj45 you can see the result at http://demo.piwik.org/.

**Comment by raj45** [comment]
That looks great, I can't wait for it to be released. Thank you all for the great work!

**Comment by gaumondp** [comment]
Looking at http://demo.piwik.org/, I get the feeling making the name in bold would help a bit also. Something like:

SITE: **PIWIK FORUMS**

Just the name, not "SITE: ".

**Comment by raj45** [comment]
I second that, make it stand out! But why even include "WEBSITE: " or "SITE: "?
Also, I think it is bad UI-design to not include the current site in the drop-down, which it is in every other GUI.

**Comment by mattab** [comment]
> I think it is bad UI-design to not include the current site in the drop-down, which it is in every other GUI.

@raj45 do you mind creating a new issue? we can consider such change

**Comment by mattab** [comment]
> SITE: **PIWIK FORUMS**

Maybe it looks a bit weird to have non-bold and bold text in the same selector?

**Comment by mattab** [comment]
it looks like this:


![bold non bold](https://cloud.githubusercontent.com/assets/466765/10530974/e7bcf89a-7408-11e5-804c-86ff1a0c9916.png)

**Comment by tsteur** [comment]
I'm also not sure if we actually need the term `website` in front but for now it's better to have I reckon. It's maybe useful for users who did not setup all the websites and don't know the names of the websites etc. (eg http://demo.piwik.org). However, with a good icon the leading "Website" might be obsolete. 

If we make this one bold, we'd kinda also have to make the other selectors bold and doesn't look as nice and also not really increase usability I think. Maybe there are other ways? I think having a nice icon would already make some things better maybe

**Comment by raj45** [comment]
> I think it is bad UI-design to not include the current site in the drop-down, which it is in every other GUI.
>@raj45 do you mind creating a new issue? we can consider such change

Sure, I created an issue here: #9025
