### ISSUE TITLE
Tracking on iOS 9 with Safari

### ISSUE THREAD

**Issue by Eric4502** [piwik/piwik#8715]
I know that iOS 9 is still in Beta, it seems that tracking is not working with Safari but it's working with Chrome. I tested on an iPhone 6.

**Comment by sgiehl** [comment]
Might there be a do not track setting enabled by default?

**Comment by Eric4502** [comment]
You were right, it was not existing before. Only on Safari. Thanks

**Comment by sgiehl** [comment]
Could you please confirm that it was/is enabled by default?
If so maybe we should ignore that like in #8682 and #4482

refs #3531

**Comment by Eric4502** [comment]
It was enabled by defaut on safari and I didn't enabled the option "Do Not Follow" taking in account in Piwik privacy options.

**Comment by mattab** [comment]
If Safari on iOS9 has enabled by default "DoNotTrack" then we should indeed still track the Safari on iOS9+ - 

Would someone else be able to confirm whether safari on iOS9 has DoNotTrack enabled by default?

**Comment by tsteur** [comment]
I just had a look on my iPod which is running one of the latest betas and Do Not Track was not enabled there but I did an update. Not sure how it is for new installations. Will try to update to the final version in case there was a change to enable it by default

**Comment by tsteur** [comment]
Updated to final version of iOS 9 and it's still not enabled for me. As mentioned it might be different for new installations
