### ISSUE TITLE
Missing FAQ entry on migrating from myisam to innodb?

### ISSUE THREAD

**Issue by nekohayo** [piwik/piwik#8716]
Issue #4611 mentions "Add FAQ "How do I change the MySQL table types from InnoDB to myasam?" (sic) but I could not find such a thing in http://piwik.org/faq/ nor http://piwik.org/docs/

Was it forgotten, or was it removed?

Also, does the sitemigration plugin automatically do the conversion?

**Comment by mattab** [comment]
Hi @nekohayo 
The information how to convert all tables to innodb  can be found online eg. http://stackoverflow.com/a/7214751

**Comment by mattab** [comment]
New FAQ was added finally :tada: [How do I convert the MySQL database tables from MyIsam to InnoDB?](https://piwik.org/faq/troubleshooting/faq_25610/)
