### ISSUE TITLE
Tracking outgoing links other than http or https is broken

### ISSUE THREAD

**Issue by sesom42** [piwik/piwik#8722]
I'm using the normal tracking code from Piwiks admin page with link tracking enabled. Outgoing links are normally recorded by Piwik. All fine.

But I also have links other than HTTP or HTTPS on my website, for example, rtp: // ... These links will be logged, but misrepresented on the Piwik page. They all appear as a link to the Piwik Dashboard. In the visitor profile these links as shown as "Page URL not defined". Screenshot attached.

![screenshot-piwik tausys de 2015-09-07 11-11-49](https://cloud.githubusercontent.com/assets/8649051/9713453/bcea0778-5551-11e5-922a-565e4d463d2a.png)

**Comment by sgiehl** [comment]
I can confirm that behaviour.

**Comment by sgiehl** [comment]
Piwik is currently checking for url-like links before tracking them.
https://github.com/piwik/piwik/blob/master/core/UrlHelper.php#L108
Tihs method is used therefore. So currently only ftp, news, http and https are correctly tracked. Everything else will be tracked as "undefined page url"

We have two options to solve this:
Extend the list, or add an config option to extend it?

**Comment by tsteur** [comment]
They should be tracked and displayed IMO. We're not back in the 90's :) Especially in mobile apps deep linking is common (see eg https://en.wikipedia.org/wiki/Mobile_deep_linking) and one wants to probably track and see it

**Comment by mattab** [comment]
adding to 2.15.0 as this should be a quick fix. Are there other protocols we should add like `rtp://` that are commonly used on web pages?

**Comment by sgiehl** [comment]
Guess there are dozens we *could* add. So I would suggest to make that configurable as some might be very special... even `rtp://` might not be very common

**Comment by tsteur** [comment]
Can we not just allow any? Configuring it seems not user friendly and alone in the Android world there probably > 100.000 different protocols (for deep linking).

I'm not sure why it is restricted so maybe someone can help me here?

**Comment by sgiehl** [comment]
Guess that was just to avoid crap being tracked as action. Btw. the reports are afaik not able to handle such "links" correct aswell.

**Comment by tsteur** [comment]
We should at least track it, at least if we claim to be like a mobile app tracking tool etc. Re the reports not sure. I'd probably display it as it'd work if one views it from a mobile device or whatever (depending on the protocol). I don't think people expect them to work when they view it in the browser. Meaning we could display them and link them. If someone clicks on it and nothing happens or a blank window opens that could be okay. Maybe not :) I'd link them

**Comment by sesom42** [comment]
I think if link tracking is enabled, Piwik should record everything that is a link. Why else would anyone turn on link tracking? Whether then the links work in reports or dashboard is up to the platform on which they are looked at. When a Web page is displayed, the browser decides how the links contained are treated. A selection of recordable protocols I do not consider necessary. The author decides with the inclusion of a link on the webpage if there is a link or not.

**Comment by tsteur** [comment]
:+1:
