### ISSUE TITLE
Bad filesystem detection (NFS)

### ISSUE THREAD

**Issue by nuxwin** [piwik/piwik#8734]
Hello ;

I installed Piwik on a test server which is managed by i-MSCP (A Linux control panel for shared hosting environments). When I check the system using Piwik, I get the following warning:

```
Your server is using an NFS filesystem.
This means Piwik will be extremely slow when using file based sessions. 
```

and therefore, the session handler is automatically set to dbtable.

While this behavior is expected for NFS, this should not be the case for bind mounts. Indeed, Piwik detects that I use NFS but this is totally wrong. i-MSCP automatically re-mounts the Web folder directories (bind mount) as shared subtree. More explaination can be found here: https://github.com/i-MSCP/imscp/blob/1.3.x/docs/1.3.x_errata.md#shared-subtree-homedir

In my case, the Web folder is re-mounted as follow:
```
/dev/sda1 on /var/www/virtual/test.tld type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

As you can see here, that is not an NFS filesystem. I don't know how the check is made by Piwik but it seem that the filesystem type is not really checked.

That bind mount is managed by i-MSCP:

```
# fstab-like configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
/var/www/virtual/test.tld /var/www/virtual/test.tld none shared,bind
/var/log/apache2/test.tld /var/www/virtual/test.tld/logs/test.tld none bind
/var/log/apache2/piwik.test.tld /var/www/virtual/test.tld/logs/piwik.test.tld none bind
```

See https://github.com/i-MSCP/imscp/blob/1.3.x/docs/1.3.x_errata.md#imscp_mountall-service

Note: I'm the i-MSCP project director.

**Comment by nuxwin** [comment]
Re ;

I could provide a patch if you want (PR). It seem that the check is done in the core/Filesystem.php file. I must investigate but right now, when running the df command manually on my system, I get

```
root@jessie:/var/www/virtual/test.tld/piwik/htdocs/tmp/sessions# LANG=C df -T -t nfs  /var/www/virtual/test.tld/piwik/htdocs/tmp/sessions 2>&1
df: no file systems processed
```

which is expected. Thus, I presume that the check is wrong somewhere in the checkIfFileSystemIsNFS() method of the Piwik\Filesystem class.

**Comment by nuxwin** [comment]
I find the cause:

```php
        } elseif (function_exists('shell_exec')) {
            // use shell_exec

            $output = @shell_exec($command);
            if ($output) {
                $output = explode("\n", $output);
                if (count($output) > 1) {
                    // check if filesystem is NFS

                    return true;
                }
            }
        }
```

is wrong... You cannot rely on the output of that command to detect filesystem. 

In my case, output array (after explode) hold:

{code}
Array
(
    [0] => df: no file systems processed
    [1] => 
)
{/code}

Then, the result is erroned.

**Comment by tsteur** [comment]
PR would be awesome

**Comment by nuxwin** [comment]
The PR must be made against master or do you have a specific branch for development purpose?

**Comment by tsteur** [comment]
PR should be made against `master` :+1:

**Comment by nuxwin** [comment]
@tsteur 

Ok, then. I'll do that PR in few minutes ;)

**Comment by nuxwin** [comment]
@tsteur 

Done. See #8737

**Comment by tsteur** [comment]
I presume we can close this one then?

**Comment by nuxwin** [comment]
@tsteur 
Sure since you merged the referenced PR ;)

**Comment by nuxwin** [comment]
@tsteur 

I close it right now but I cannot add the BUG label on it ;)

**Comment by tsteur** [comment]
Done, thx

**Comment by DohmenICT** [comment]
Hi!

I run Matomo on a Synology Diskstation locally, and this checkIfFileSystemIsNFS() still returns TRUE!

I did some testing and when I run the following command on my DS
df -T -t nfs "/volume1/web/piwik/tmp/sessions"

I get:
Filesystem     Type  1K-blocks       Used  Available Use% Mounted on
-              -    6039797760 3668011728 2371786032  61% /volume1/web

And the function returns true;

When I change the function so that it just returns False; Matomo works a lot quicker since it really isn't a NFS.

Can this be patched?

**Comment by tsteur** [comment]
BTW: We don't use files for sessions anymore and should be pretty fast.
