### ISSUE TITLE
Title for the widget disappearing after mouse out when Help is open

### ISSUE THREAD

**Issue by dczajkacc** [piwik/piwik#8740]
To Reproduce: 
- Click on any help icon for any of the widgets 
- when the help text shows, mouse out of the area. 
- See the title of the widget and the help hide. 

Desired Result: Title stays in view and hide the help text (Or whatever the current regular behavior is for help text.) 
![helpui-1](https://cloud.githubusercontent.com/assets/11975672/9747077/d49e117c-567b-11e5-8ab8-cb1c3cf8490c.png)
Actual Result: Title and Help Text hide from the UI 

![helpui-2](https://cloud.githubusercontent.com/assets/11975672/9747083/dc8ee064-567b-11e5-90ff-c7f950a286b3.png)

**Comment by quba** [comment]
I was able to reproduce on demo.piwik.org

**Comment by sgiehl** [comment]
Seems to be a weird rendering bug in Chrome. I can reproduce it there, but the styles are ok and it should be displayed.
Works for me in Firefox and IE. Can anyone confirm that it occurs in Chrome only?

**Comment by tsteur** [comment]
I can reproduce it in Chrome but not in Firefox etc. The styles do look good for me as well and it seems to be a bug in Chrome. It sometimes seems to not disappear or less often when developer tools are often or so. Also had a look at the code and as said looks like a Chrome bug to me

**Comment by diosmosis** [comment]
This appears to be caused by nesting `<span>`s. Works when use a `<div>` w/ `ng-transclude`. Will issue a PR.
