### ISSUE TITLE
Too long time to load AllWebsites Dashboard Page

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8741]
Piwik is a great app for monitoring our websites, we do like it, but it takes a long time to load AllWebsites Dashboard Page.

As you can see below:
![all](https://cloud.githubusercontent.com/assets/2368001/9761372/f30a8984-572e-11e5-815f-e70506d44404.png)
23.07s taken to load AllWebsites Dashboard Page, It's too long!

Almost 50 websites together. Also I have taken this method:

Any idea to improve the load speed?

**Comment by jerrycave** [comment]
I have taken this measure: <http://piwik.org/docs/installation/#medium-and-high-traffic-websites-setup-an-automated-task-cron-to-process-reports>

**Comment by tsteur** [comment]
Can you confirm you did setup a cronjob for archiving as described in http://piwik.org/docs/setup-auto-archiving/ and disabled browser triggering the archiving http://piwik.org/docs/setup-auto-archiving/#disable-browser-triggers-for-piwik-archiving-and-limit-piwik-reports-to-updating-every-hour ?

How many websites do you have in your Piwik? We tested it recently with 30.000 websites and it was quite fast. Are you using latest Piwik version?

**Comment by jerrycave** [comment]
Disable browser triggering makes loading quite fast, thank you.

**Comment by tsteur** [comment]
Sweet, have a good day

**Comment by mattab** [comment]
This issue could be solved  by: https://github.com/piwik/piwik/issues/6210
