### ISSUE TITLE
Migrating Piwik forums to use Discourse 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8747]
As announced in https://github.com/piwik/piwik/issues/8520#issuecomment-131781447, we have decided to try [Discourse](http://discourse.org/) for our [Piwik Forums](http://forum.piwik.org/) (currently we are using [phorum](http://www.phorum.org/)). 

### Advantages of discourse

Some nice features of Discourse: it's simple to use, fast,  responsive, and overall looks good. It is actively maintained and has a hosted service (which we will use with a discounted price). The forums structure is flexible. Discourse encourages crowd sourced moderation (via 'Flag' feature). One change is that there is no forum signature feature (design decision to KISS). It's possible to Like posts.  There will be social login via github, twitter, etc. making it super easy to signup.

Overall we hope the migration to Discourse will help you feel more at home in the forums, and over time that it will slightly increase community engagement!

### Checklist before migration can be started

 * [x] enable github social login 
 * [x] enable facebook social login
 * [x] enable google social login
 * [x] enable twitter social login
 * [x] Analytics: setup basic piwik tracking (pageviews)
  * [x] Bug: refreshing topic page creates two tracking requests
 * [x] Theming: do we use a forum style listing all categories (http://piwik.techapj.com/categories) or the default style where all posts are listed independantly of category (http://piwik.techapj.com/) 
  * We will use the default post listing view
 * [x] Check URLs are redirected properly (so we don't lose SEO power or traffic or frustrate users clicking on links)
  * http://forum.piwik.org/list.php?2 opens the posts in forum id 2
  * http://forum.piwik.org/read.php?2,71214 opens a given post id 71214
 * [x] Confirm everything looks correct on the hosted discourse instance 
  * [x] notification emails are sent and not spam
 * [x] Choose a date for migration & Announce it here in comments, and in new forum post

### Suggested migration process

 * [x] Put current forums into read-only mode
 * [x] Ask discourse to do a data migration using most recent data dump
 * [x] Change DNS `forum.piwik.org` to point to discourse 
 * [x] Change social login information to use the correct URL callbacks... 
  * [x] in Facebook (https://developers.facebook.com/apps/878433935579853/settings/basic/)
  * [x] in Github (https://github.com/organizations/piwik/settings/applications/241376)
  * [x] in Google (https://console.developers.google.com/project/piwik-forum-login-discourse/)
  * [x] in Twitter (https://apps.twitter.com/) 

Make Categories look great:

  * [x] Change category names in Discourse (ie. what used to be called forum names) to make them shorter (see good example at http://meta.discourse.org/ or http://discuss.atom.io/)
  * [x] Set a description to each category
  * [x] Edit the welcome message post in each category

Finish the migration:

 * [x] Check it's all working fine, or fix it
 * [x] Set canonical URLs to forum.piwik.org 
 * [ ] Import the list of 15,000 migrated user emails into madmimi
 * [ ] Mass email all migrated users with a login procedure (how to reset their password)
 * [ ] A few days later, write a blog post about the migration and invite everyone to join the new forums!
 * [ ] Send newsletter to let the whole community know about the new forums

### Not for now, can be done after successful migration

Note: Create an issue to follow up these items:

 * [x] Enable `HTTPS` SSL connection for forum.piwik.org
 * [ ] finding volunteer moderators for each category 
 * [ ] integrating Discourse and Developer guides so that people can comment on developer guides 
 * [ ] integrating Discourse and WordPress so that comments on posts will become forum conversations.
 * [ ] Theming: add a top black menu to link back to the website, similar to top bar of developer.piwik.org (see good example at http://discuss.atom.io/)
 * ....

**Comment by mattab** [comment]
Please check & test our Discourse instance at: http://piwik.techapj.com/

You can signup for a new account, or if you already have an account on forum.piwik.org you can use "Reset password" feature to get access to your profile.

Looking forward to feedback and bug reports/suggestions!

**Comment by MagicFab** [comment]
@mattab nice, I see all posts + users have been imported! I tested it for a few minutes, here are some notes:
- I get a blank page when using Icedove 40 + uBlock extension
- getting access was simple as you described, using my existing account + reset password
- attachments seems to be missing (http://piwik.techapj.com/t/high-traffic-piwik-servers-database-usage/3614/146)
- internal links point to the current forum (http://piwik.techapj.com/t/announcement-piwik-spanish-support-forum-foro-de-ayuda-piwik-en-espanol/15527)
- private messages didn't make it
- permissions didn't make it (I have some admin rights/moderator in the current forum, didn't see any in the new - which seemed right, I am OK to request/earn them again)

Some nice improvements I liked immediately:
- Badges! May be useful to implement some of the community recognition items that were discussed in Berlin/etc.
- Tagging/reporting SPAM
- Nice formatting available :)

I'd suggest having the ability to file bugs/issues about this Discourse instance withing the same, much like Discourse does on theirs: https://meta.discourse.org/c/bug?order=op_likes&status=open

Some sort of invitation to current forum users (by email?) would also seem in order, perhaps not *all of them* but at least the past few hundred active users (or last registered).

**Comment by quba** [comment]
@mattab don't forget to set up Piwik tracking. Maybe we will be able to implement it a little bit better here (to have better data in demo.piwik.org instance) - with event and content tracking.

**Comment by mattab** [comment]
@quba basic pageview tracking is already setup (currently tracking in a hidden website on demo.piwik.org). It would be very nice, indeed, to track event and content tracking too! adding to checklist

**Comment by mattab** [comment]
@MagicFab thanks for feedack!

> attachments seems to be missing 
> private messages didn't make it

reported these to discourse 

> internal links point to the current forum 

it will work fine on the production instance because redirects will be setup 

> permissions didn't make it 

some permissions seem to have make it, but we'll start fresh anyway!

> Some sort of invitation to current forum users (by email?) would also seem in order, perhaps not all of them

yep it's planned (see migration checklist). i'll just email all of them, because why not? ;-)

**Comment by mattab** [comment]
Takeshi from Piwik Japan team said they are interested to create a Japanese support forum on forum.piwik.org -> once we have discourse, let's create the forum! :-)

**Comment by MagicFab** [comment]
I'd volunteer to help with French / Spanish. Other than a time machine to multiple @mattab 's time, what else can be done to advance this? :)

**Comment by mattab** [comment]
Progress update: the forums are now hosted on the actual Discourse Cloud and available at: http://piwik.trydiscourse.com/

I will run more tests in coming days and hopefully soon we can kick start the migration :+1:

**Comment by Joey3000** [comment]
Another potential point for the checklist, while at it: Could HTTPS be enabled on forum.piwik.org? It's the only *.piwik.org domain left without HTTPS.

**Comment by mattab** [comment]
> Could HTTPS be enabled on forum.piwik.org? It's the only *.piwik.org domain left without HTTPS.

it should be possible, this was added to the checklist in issue description

**Comment by MagicFab** [comment]
Is it safe to assume the data there is for testing purposes and will be wiped clean at migration time? Perhaps a notice to that effect would be useful until it's done. Can't wait!

**Comment by mattab** [comment]
yes the data will be wiped out and re-imported fresh in coming 48 hours or so (migration is happening very soon!)

**Comment by mattab** [comment]
Migration has started

**Comment by mattab** [comment]
I've switched DNS on forum.piwik.org so it should be updated within 24 hours...

The forum categories were updated: http://piwik.trydiscourse.com/categories

**Comment by mattab** [comment]
@tsteur check out possibility to embed Discourse comments in JavaScript in static HTML site (could be great for our developer.piwik.org) https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by tsteur** [comment]
We can try it and see how it looks. There's a demo link referenced but discourse seems to be down or not working there anymore. 

From https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963:

> One important thing to note with this setup is that users have to navigate to your forum to post replies. This is intentional, as we feel that the posting interface on a Discourse forum is currently much richer than what we could embed via Javascript

It  would be nice if users could post directly from there similar to https://disqus.com/home/  (users can post there on the embedded iframe)

**Comment by mattab** [comment]
Forums have been migrated to Discourse and it has been a success! Join the community at: http://forum.piwik.org/
