### ISSUE TITLE
Minor icons alignment  issues

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8748]
Noticed couple small issues on the demo after upgrading it to beta5:

# Issue 1

 * Expected "Outlink icon" to be vertically aligned with the URL. 
 * Got: outlink icon appears below the blue text

![alignment issue](https://cloud.githubusercontent.com/assets/466765/9779708/c1c3393a-57d2-11e5-95c0-3149ab7b05c8.png)

# Issue 2

 * Expected: Search and outlink icon vertically aligned with text on the right
 * Got:
  * Both icons are missing right margin (text is too close to icon)
  * The Search icon is mis-aligned: appears too low compared to the search term

![icon alignment issues](https://cloud.githubusercontent.com/assets/466765/9779707/c1bfdd8a-57d2-11e5-9db6-0714957e8d54.png)

**Comment by mattab** [comment]
Sub-table icons are still a bit mis-aligned, see screenshot:

![icons aligned](https://cloud.githubusercontent.com/assets/466765/10270664/c4946346-6b55-11e5-8da3-1460219d46f9.png)

**Comment by tsteur** [comment]
which browser is that? Is zoom activated? Tried to reproduce in firefox and chrome

**Comment by mattab** [comment]
Can reproduce this issue on both Firefox and Chromium on Ubuntu, on demo2 + local dev Piwik. The sub-table icons are displayed too much to the bottom, expected: icons vertically aligned. can you reproduce it?

**Comment by tsteur** [comment]
I couldn't. Are you sure there is no zoom or so active?

**Comment by mattab** [comment]
Strange, yes there is no zoom, see screenshot below:

![icons misaligned](https://cloud.githubusercontent.com/assets/466765/10291494/8ed75ef0-6c06-11e5-90e7-13fca594f4f2.png)

**Comment by tsteur** [comment]
OK in master I can reproduce it, was testing in the branch. It's weird as there was this merge: https://github.com/piwik/piwik/commit/0dc0e312e12cbf1ee46df32c107cf5815638fad0 of https://github.com/piwik/piwik/pull/8817 but the code is not in master. History also doesn't show any existence. Was there a `rebase --force` or so?

**Comment by mattab** [comment]
> Was there a push --force or so?

`history | grep force` has no result and I don't use this anyway. It's kinda scary that we can lose commits in this way... I'm wondering if there is a way to detect such "lost" commits...

**Comment by mattab** [comment]
FYI: enabled the "protected branch" feature for our `master` branch on piwik/piwik

Hopefully this will prevent such issue in future?

**Comment by tsteur** [comment]
issued another PR waiting for UI tests then we can merge.
