### ISSUE TITLE
Not working after installed on subdomain.

### ISSUE THREAD

**Issue by MESWEB** [piwik/piwik#8750]
Piwik don't collect any data when You install on subdomain like: piwik.domain.com and You want tracking domain.com. But when You install Piwik on domain.com/piwik/ and tracking domain.com there has working fine. Can someone explain this BUG?

**Comment by hpvd** [comment]
in our enviremont with piwik 2.15 latest beta both is working fine
(we just moved from "domain.com/piwik" to "piwik.domain.com")

**Comment by mattab** [comment]
Works fine, this must be a problem with your configuration or maybe Javascript tracker code not set properly in your website?

**Comment by MESWEB** [comment]
I using latest stable version 2.14. Maybe You should put update for 2.14?
