### ISSUE TITLE
[Security, Critical] Piwik uses the MD5 of the password as a valid login token (!!)

### ISSUE THREAD

**Issue by etjossem** [piwik/piwik#8753]
It is possible to pass a username and a password which is the md5 hash of the user's actual password, and Piwik will treat it as valid.

Per [docs](http://piwik.org/faq/how-to/#faq_30):
```
If you want to provide a one-click automatic login to Piwik for your users, you can use the ‘logme’ mechanism, and pass their login & the md5 string of their password in the URL parameters...
```

If a user ever shares a password between Piwik and another MD5-hashing app, and a bad actor [obtains a dump of the other app's hashes](https://haveibeenpwned.com/PwnedWebsites), their Piwik account will be compromised (even without any reverse hashing).

**Comment by mattab** [comment]
Thanks @etjossem  for the report.

Piwik works in this way by design so far. to resolve this issue properly is included in #5728 where we will improve the hashing algorithm and also provide a more secure `logme` mechanism.
