### ISSUE TITLE
Problem Piwik 2.15 betas and latest FF41 betas 

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8760]
Opening Piwik 2.15 betas and latest FF41 betas 
lots of content is missing.
Please see attachment.
Latest version tested: Piwik 2.15b7 and FF41b8

Yes of course these are betas, but piwik works fine in other browsers, and FF do not show any problems on other websites.
And the problem remains since several betas from both softwares
As far as I can remember, it starts around 2.15.b3

**Update:** I looked a little deeper:
The problem only appears with having ad block plus activated.
This is a very common advertising blocking extension of FF and was never a problem for several years.
https://addons.mozilla.org/de/firefox/addon/adblock-plus/

=> Since I use it with standard settings as lot's of other people do, maybe one should have a look an this....

Latest update of this extension was on July 28, 2015, so the problem should not result from changes in this extension.

![2015-09-11_07h47_48](https://cloud.githubusercontent.com/assets/5681880/9807947/68a18a4a-585a-11e5-93a4-f1f10a47ce44.png)

![2015-09-11_07h55_45](https://cloud.githubusercontent.com/assets/5681880/9807980/b15f399e-585a-11e5-8f43-cff03a423a3d.png)

**Comment by tsteur** [comment]
Possibly not the extension was updated but maybe a "List" they use to decide which parts to block. Such extensions usually allow to whitelist a domain / page which should solve the issue.

I think some to detect whether an ad blocker is installed, not sure how good it works or how it is done etc. If more users will experience this it might be nice to show a warning that they need to disable ad blocker for this page.

**Comment by hpvd** [comment]
thanks for commenting that fast.
Yes website can be white listed of course.
But since it was NEVER needed before, and lots of people uses this combination of software,
I thought it was worth reporting...
Maybe this is only a problem with the current ruleset of the extension....

**Comment by tsteur** [comment]
I expect quite a few users to experience this problem and as mentioned it could be nice to show a warning in such a case. Haven't researched yet if possible and how but I've heard of sites that do detect an adblocker

**Comment by mattab** [comment]
Notification would be useful for sure :+1:
In the notification message I'd suggest to invite users to contact the
"browser extension" developers and ask them to whitelist Piwik from
their rule.

in general, what browser extension are you using that blocks Piwik? it
would be great to contact the devs and kindly ask them to update their
rules not to block local piwik instances. Thanks!

**Comment by tsteur** [comment]
We asked them in the past already and their comment was something like that anything that tracks users is evil no matter what (something like that would need to search for email) and they won't remove it. One should be aware that there are companies behind some ad blockers etc that wanna make $$$ by getting $$$ from advertisers to whitelist their ads etc so they don't really care about such cases

**Comment by hpvd** [comment]
I think these are different cases:

1. this problem is about Piwik backend. This was always working without any problems.. (for years and each single version, even the betas..)

2. The other thing is the possibility to track websites using piwik.
This is sometimes / by some add-ons blocked

**Comment by hpvd** [comment]
some more details on this:
The sites
- Admin
- Help and
- user
are working fine

**Comment by mattab** [comment]
Just noticed it duplicates the issue: https://github.com/piwik/piwik/issues/7928 and https://github.com/piwik/piwik/issues/5094 - feel free to leave comment on the issues if appropriate
