### ISSUE TITLE
It's quite slow for mobile browser to load website page which embedded with piwik tracking code.

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8762]
As mentioned in the title.

For mobile browser: It's quite slow to load website page which embedded with piwik tracking code at the first time. Whether the load speed depends on the network capability of the mobile or not?

Any idea to optimize it?

**Comment by jerrycave** [comment]
As you can see below:
![qq20150914-1 2x](https://cloud.githubusercontent.com/assets/2368001/9841535/8887b0b6-5ad3-11e5-9a1f-8dabbc92c3e9.png)

**Comment by mattab** [comment]
duplicates #8785
