### ISSUE TITLE
Track the wrong url for an url containing a hash

### ISSUE THREAD

**Issue by dhoko** [piwik/piwik#8763]
Hi, 

I'm using piwik with a webapp (Angular). I wanted to track pages but it didn't work.

Some urls:
- `foo.bar/#/home`
- `foo.bar/#/search`
- `foo.bar/#/login`
- `foo.bar/#/login/register`

With the dashboard `Actions > Pages`, I found only one url: [/index](http://foo.bar/) :confused:

The JS:

```js
page: () => {
  console.log('Page url', location.href, arguments)
  tracker.setCustomUrl(location.href);
  tracker.trackPageView.apply(tracker, arguments);
},
```
I tested with this: 
```js
tracker.setCustomUrl(escape(location.href));
tracker.setCustomUrl(encodeURIComponent(location.href));
```

but it didn't work too.

To make it works, I have to remove the `#`.

```js
page: () => {
  console.log('Page url', location.href, arguments)
  tracker.setCustomUrl(location.href.replace('/#/', '/'));
  tracker.trackPageView.apply(tracker, arguments);
},
```

Then I can find my pages as expected.

**Comment by mattab** [comment]
Hi @dhoko 

I just tested and it works for me fine with `  tracker.setCustomUrl(location.href);` 

See how it looks in reports:

![pages](https://cloud.githubusercontent.com/assets/466765/9861235/38e55056-5b85-11e5-9f3b-772576978cba.png)

visitor log:

![visitor log](https://cloud.githubusercontent.com/assets/466765/9861236/38e9df40-5b85-11e5-92e5-c625b8266bc8.png)

**Comment by dhoko** [comment]
It still doesn't work. We were with the `2.14.2`, with the `2.14.3` nop  it doesn't work.

**Comment by RMastop** [comment]
Hi @dhoko,

Just to be sure..

Did you enable "Keep Page URL fragments when tracking Page URLs" like this FAQ shows:
http://piwik.org/faq/how-to/faq_188/

**Comment by dhoko** [comment]
It works ! \o/

Thank you
