### ISSUE TITLE
Open website, date, period, dashboard, ... selector automatically when mouse is over for eg 2 seconds

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8764]
As title.

I think it could be nice when the mouse is over a selector for eg 2 seconds we could open it automatically (eg with fade in animation). As soon as the mouse leaves we would close it automatically

**Comment by mattab** [comment]
Maybe we could introduce this at the same time as the Left Menu #7169 https://github.com/piwik/piwik/issues/7589

**Comment by tsteur** [comment]
I was thinking recently about it and there might be one issue:

Imagine you're using Piwik and moving your mouse somewhere and the mouse stops over a selector. You might not pay attention where the mouse pointer is. Now you start focusing on the content/reports. A second later a selector suddenly opens. This might be distracting and unwanted/annoying as you have to move the mouse out again (or possibly even click somewhere else again) and then focus on content again. I'm not a usability expert but this could be an annoying issue

**Comment by tsteur** [comment]
I'm closing this one again as I think it is actually not a good idea
