### ISSUE TITLE
Not working after installed on subdomain.

### ISSUE THREAD

**Issue by MESWEB** [piwik/piwik#8772]
Hey Mattab You are dumb or stupid? Why You close my first issue with label worksforme? What You gonna prove? I'm lair and I imagine this issue? Look for this issue in piwiki/forum then You will see couple this same errrors. My settings is fine and js code is input to the files, I using pretty urls. Don't close this before I don't fix this. In piwik forum nobody can help me.

**Comment by mattab** [comment]
Hi @MESWEB 

this is not a support forum here, but an issue tracker. Piwik is free and the support is community based (in forums). 

read this: http://developer.piwik.org/guides/core-team-workflow#submitting-a-bug-report

please explain what is the problem in more details, and what you tried etc.

**Comment by MESWEB** [comment]
Ok I think the PIWIK have issue. I have secured domain like https://domain.com with smf forum + pretty Url + rewriting rule in .htaccess. Piwik has been instaled on https://domain.com/piwik and second one in piwik.domain.com. First piwik working fine and collecting data but second piwik don't collect any data from https://domain.com or any different site like domain2.com. All this site have correct js code tracking. Of course when I switch tracking to piwik.domain.com I update tracking code. So what is wrong with subdomain with piwik? Why piwik not working on subdomain? If You wish I can make admin account in piwik for You for test.

**Comment by mattab** [comment]
AS you can see on: http://demo.piwik.org/

PIwik tracks fine subdomains. what's your website that is not tracked?

**Comment by MESWEB** [comment]
My site is trybi.pl and errors.win . I see now. So in my case I think maybe this rewrite rule on .htaccess give this issue but I'm not sure.

**Comment by mattab** [comment]
you can troubleshoot the tracking by following these instructions http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker

what do you find?

**Comment by MESWEB** [comment]
GET piwik.php?action name="some info" status 403 Forbiden. I see this everywhere on my site. But why piwik collect Your data at time 21:28 ? I trying 3 browsers = Waterfox 64 with uBlock Disabled, Chrome with uBlock disabled and Opera Mini on Android device. Results is this same - No Data. But Why Piwik collect Your entry?

**Comment by mattab** [comment]
Check your server error log for an error message

**Comment by MESWEB** [comment]
No errors in error log.
This is from access log:
MY IP - - [14/Sep/2015:18:32:27 +0200] "GET /piwik.php?action_name=Don%27t%20let%20errors.win&idsite=1&rec=1&r=485513&h=18&m=32&s=26&url=http%3A%2F%2Ferrors.win%2F&_id=fad74c2be78d28d5&_idts=1441314647&_idvc=16&_idn=0&_refts=0&_viewts=1442248347&send_image=0&pdf=0&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=1&cookie=1&res=1366x768&gt_ms=827 HTTP/1.1" 403 181 "http://errors.win/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:40.0) Gecko/20100101 Firefox/40.0.2 Waterfox/40.0.2" piwik.trybi.pl

**Comment by mattab** [comment]
you say you have 403 errors on piwik.php so you should have error in error log.

**Comment by MESWEB** [comment]
I don't know why is only one error harder to find:
Error in Piwik: Action &#039;&#039; not found in the module &#039;Proxy&#039;

**Comment by mattab** [comment]
please use forums for free/ community support: forum.piwik.org

**Comment by MESWEB** [comment]
No one can help there!
