### ISSUE TITLE
delimiter not working correctly

### ISSUE THREAD

**Issue by BlackKite84** [piwik/piwik#8775]
follow uri / links not Splitting

https://www.cafe-anime.de/index.php?user/10740-thrawn
https://www.cafe-anime.de/index.php?thread/13521-tsundere-dandere-und-andere-charakterliche-eigearten

![unbenannt](https://cloud.githubusercontent.com/assets/3486554/9839238/80d99eac-5a73-11e5-9064-19a3daadfb81.PNG)

in the config is set

action_url_category_delimiter = /
action_title_category_delimiter = /

The Splitting must be so?

/index.php?user
-- 10740-thrawn

/index.php?thread
-- 13521-tsundere-dandere-und-andere-charakterliche-eigearten

**Comment by BlackKite84** [comment]
Piwik 2.15.0-b7

**Comment by mattab** [comment]
Hi @BlackKite84 

This actually works as designed: the splitting only applies to the Request path, not to the Query string.
