### ISSUE TITLE
Clicking on Row Evolution, when a segment is set, can fail

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8776]
When a segment is used, opening row evolution and/or visitor profile does not work (in some cases)

# Issue 1: row evolution 

Reproduce:

 * Open segmented custom variables report: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&segment=pageUrl%3D%40forum.piwik.org%252Flist.php%253F2#/module=CustomVariables&action=menuGetCustomVariables&idSite=7&period=day&date=yesterday&segment=pageUrl%253D%2540forum.piwik.org%25252Flist.php%25253F2

 * Click "Row Evolution" icon
  * Got: the report "Custom Variables" reloads itself. No row evolution popover is displayed. 
  * Expected: the popover Row Evolution opens, showing the evolution for the clicked label.

# Issue 2: visitor profile

I guess is the same issue:

Reproduce:

 * Login in the demo 
 * Open visitor log with segment: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&segment=pageUrl%3D%40forum.piwik.org%252Flist.php%253F2#/module=Live&action=indexVisitorLog&idSite=7&period=day&date=yesterday&segment=pageUrl%253D%2540forum.piwik.org%25252Flist.php%25253F2
 * Click on `View visitor profile`
  * Got: visitor log page reloads. Popover not shown
  * Expected: popover visitor profile opens

# Suggested steps

 * Add UI test(s) to reproduce this issue (maybe we don't have a UI test for Row Evolution / Visitor profile with a segment set?)
 * Fix the issue

I didn't add `Regression` because this appears not to be a regression!

**Comment by diosmosis** [comment]
This is caused by https://github.com/piwik/piwik/blob/master/plugins/CoreHome/javascripts/broadcast.js#L354. For some reason `broadcast.getHashFromUrl` encodes the URL again. This results in setting the new URL to something different from `broadcast.currentHashUrl` (after the popover= query param is removed), so `broadcast.pageload` will not load the popover (https://github.com/piwik/piwik/blob/master/plugins/CoreHome/javascripts/broadcast.js#L119). Trying to figure out why...

**Comment by diosmosis** [comment]
Actually that's not quite right, it gets encoded again somewhere else...

**Comment by diosmosis** [comment]
Caused by an angular bug, `$location.absUrl()` decodes url parameters (at least in the hash).

**Comment by diosmosis** [comment]
Ok, not a bug, it's because we use `$location.path()` to store hash query parameters. We should be using `$location.search()`.
