### ISSUE TITLE
 when loading dashboard a XHR request errors with Status=cancelled

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8780]
Reproducible on demo.piwik.org - when loading dashboard, one xhr request is Status = (cancelled), and appears red in the developer tools network panel:

![error loading a ajax request](https://cloud.githubusercontent.com/assets/466765/9843587/ed912bcc-5b0f-11e5-9a65-d4b7713232d8.png)

Request that is "Aborted" is `http://demo.piwik.org/index.php?date=2015-09-13&format=JSON2&idSite=7&method=SitesManager.getNumWebsitesToDisplayPerPage&module=API&period=day`

-> Is this xhr request necessary? Maybe we could remove it to fix this issue (and slightly improve performance of dashboard page load)

**Comment by diosmosis** [comment]
This was added in https://github.com/piwik/piwik/pull/8459 (a 2.15 PR). I think I can remove the API call.

@mattab Can you tell me if `SitesManager.getNumWebsitesToDisplayPerPage` needs to be exposed as an API method? If not, and it's not useful, I'll remove the API method.

**Comment by tsteur** [comment]
The API method is useful but should be executed only once. We need to expose all such kinda data via API in the future

**Comment by diosmosis** [comment]
FYI, I fixed the issue in a PR w/o removing the method, so the question isn't relevant now :)
