### ISSUE TITLE
Slow to open Piwik when server has no access to internet

### ISSUE THREAD

**Issue by yifanyou** [piwik/piwik#8783]
When I use piwik on ubuntu in virtualbox to track  a website at my pc without internet. I found it is very slowly to open piwik. And When i connect to internet , it works well.

**Comment by mattab** [comment]
Hi @yifanyou 

you can try to disable the connections from Piwik to the Internet by following these steps: https://github.com/piwik/piwik/issues/6324 - then Piwik should not issue any internet connection and should work faster.
