### ISSUE TITLE
RSS & method API.getLastDate

### ISSUE THREAD

**Issue by NicolasBonduel** [piwik/piwik#8784]
Hello,

The RSS feed on the method getLastDate doesn't seem to work, or the printed error is not the right one.
See on your demo page:
http://demo.piwik.org/?module=API&method=API.getLastDate&date=last10&idSite=1&period=day&format=rss&token_auth=anonymous&translateColumnNames=1

Have a nice day,
Nicolas

**Comment by mattab** [comment]
Hi @NicolasBonduel - thanks for the report. Since we don't use this API in Piwik anymore, I've deprecated it and we will remove it in Piwik 3.0. therefore it's recommended that you don't use it. Cheers

**Comment by NicolasBonduel** [comment]
Well, I have the same problem if I try to use the Live.getLastVisitsDetails method with the RSS format.
(Also the example for this method and the RSS format in the API page of my dashboard is broken because the dateformat is not supported by strtotime)
 I use Piwik last current stable version (2.14.3)

**Comment by mattab** [comment]
> I have the same problem if I try to use the Live.getLastVisitsDetails method with the RSS format.

do you mind create new issue for this? we can likely improve error message or so
