### ISSUE TITLE
Website Loading Quite Slowly Due To Piwik

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8785]
Our team do like this great app.

But a stubborn problem occurs to me, when we put the piwik tracking code into the public page, then we are going to open the website, but it's quite slowly, much time spent on this request:

```
Request URL:http://xxxxxx/piwik.php?action_name=%E5%8D%8E%E5%B3%B0&idsite=2
&rec=1&r=948056&h=21&m=55&s=49&url=http%3A
%2F%2Fxxxxxx%2Fhuafeng%2Fmobile%2Fshare%2Fframe.php%3Ftarget%3DrecentProductsMobile
&urlref=http%3A%2F%2Fxxxxxx%2Fhuafeng%2Fmobile%2Flogin.php&_id=42e41fdb7ffba585&_idts=
1442196139&_idvc=4&_idn=0&_refts=0&_viewts=1442238949&send_image=0&pdf=1&qt=0&realp=0
&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1920x1080&gt_ms=111
```
Replace the website name with xxxxxx for privacy.

![qq20150914-3 2x](https://cloud.githubusercontent.com/assets/2368001/9851743/f205ae90-5b2c-11e5-822c-8d77bbfefcfc.png)
10.39s to load the page.

Any idea to optimize it? THX

**Comment by mattab** [comment]
Hi @jerrycave 
can you try to disable the `Provider` plugin, does it improve performance?

**Comment by jerrycave** [comment]
When I disabled the `Provider` plugin, it does improve the performance. Loading quite fast.

But can you give us some more detail about the reason? Also according to the description of `Provider` Plugin.
```
Reports the Internet Service Provider of the visitors.
```
If I disabled this plugin, anything bad will be happen to piwik? or somehow piwik can't get accurate pv,uv etc any more?

**Comment by mattab** [comment]
The reason is that Provider plugin does a DNS reverse lookup which can be quite slow. Our solution to this problem will be to move the Provider plugin outside of the default Piwik package and move it to the Marketplace. Covered in https://github.com/piwik/piwik/issues/5341

**Comment by mattab** [comment]
We will also disable the 'Provider' plugin by default for new Piwik users #8826
