### ISSUE TITLE
Cront job cannot run: the task did not run due to one of the constraints in the task definition

### ISSUE THREAD

**Issue by chuotnhat1985** [piwik/piwik#8794]
Dear,

I'm setting up cron job for archive piwik data. our Piwik website is using SSL. Cron job was ok long time ago. But after updating to 2.15.0-b7, cron job is alway getting error "Task Scheduler failed to start "\Piwik Auto Archiving" task for user "xyz". Additional Data: Error Value: 2147750692."

How to fix it. Please help me.

**Comment by jerrycave** [comment]
Maybe you can show us the Cron job instruction?

**Comment by chuotnhat1985** [comment]
![2015-09-17 11_20_46-58 86 55 55 - remote desktop connection manager v2 7](https://cloud.githubusercontent.com/assets/5300869/9924880/340ccbc2-5d2e-11e5-9312-beb235a7528c.png)

Hi,

This is message when windows schedule auto run. But it is ok when I run manual.

**Comment by jerrycave** [comment]
Check php.exe path?

**Comment by mattab** [comment]
This error seems to be explained by a few reasons, check out: http://superuser.com/questions/225154/scheduled-task-giving-last-run-result-0x80041324
