### ISSUE TITLE
NL translation: wrong column header in API content

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#8797]
Please check 2nd column (Searches) in Dutch translated version (2nd link). It has the same label as the last column. Is it purely translation issue?

http://demo.piwik.org/index.php?module=API&method=Actions.getSiteSearchKeywords&format=html&idSite=7&period=day&date=yesterday&flat=0&translateColumnNames=1&language=en

http://demo.piwik.org/index.php?module=API&method=Actions.getSiteSearchKeywords&format=html&idSite=7&period=day&date=yesterday&flat=0&translateColumnNames=1&language=nl

**Comment by ieperlingetje** [comment]
This translation was updated a few hours ago and should be fiwed with the next update of Piwik.

**Comment by mgonera** [comment]
thanks for the info!

**Comment by mattab** [comment]
Re-opening until we can confirm it will be fixed in 2.15.0

**Comment by mattab** [comment]
Fixed on the demo (in 2.15.0 beta 8). Thanks @ieperlingetje for improving the NL translation :+1:
