### ISSUE TITLE
Remove Date Selector in menu Personnal

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#8798]
Remove Date Selector in menu "Personnal" since it's irrelevant there : 

* Personal Email Reports
* API
* Glossary (doesn't exist yet, seen in #6773)

**Comment by mattab** [comment]
Thanks @gaumondp for suggestion

 * Date selector is relevant for Personal Email report: it lets you download the report for any date/period
 * Date selector is relevant for API: it lets you download the API data export for any date/period
 * Date selector is not relevant for Glossary and can be removed

**Comment by MagicFab** [comment]
@gaumondp thanks for fiing this issue, I've been meaning to comment on this for a few days, sorry I couldn't before. Could you rename this issue to fix the type in "Personnal" ?

@mattab they are relevant, just not used properly or probably non-functional, see below

**Personal email reports:**
- The date selector in the main Personal email reports view doesn' t seem relevant. I've filed this issue: https://github.com/piwik/piwik/issues/8881
- The date selector as proposed when editing a Personal email report also seems broken - see https://github.com/piwik/piwik/issues/8880

**API**
- It' s not obvious what the date selector is, although quite useful! I' ve filed https://github.com/piwik/piwik/issues/8882

**Glossary**
- I can' t seem to find the Glossary, where is it? I filed https://github.com/piwik/piwik/issues/8883 anyways.
