### ISSUE TITLE
Is there some docs about  log format details?

### ISSUE THREAD

**Issue by yifanyou** [piwik/piwik#8799]
Recently I wanted to import log from tomcat into piwik,but happened to meet some problems.  And I search the issues, found no operatable solutions

**Comment by yifanyou** [comment]
Found that https://github.com/piwik/piwik-log-analytics/blob/master/README.md

**Comment by mattab** [comment]
Hi @yifanyou 

if you have problem importing Tomcat logs, please create an issue at: https://github.com/piwik/piwik-log-analytics/issues/

with a small log file sample you use, the problem you have, and the command you used to import. we will investigate and we aim to make Log Analytics compatible with your log format (and all commonly used log formats!)
