### ISSUE TITLE
Replace REVEUNE with UNIQUE VISITORS in the All Websites dashboard

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#8800]
Hi, piwik developers, thanks for this great App.
Ok, Here's the problem. We want to replace `REVEUNE` with `UNIQUE VISITORS` in the All Websites dashboard, so I want to change somthing.

### Step One:

Change `General_ColumnRevenue` to `General_ColumnNbUniqVisitors`

```
<th id="nbactions" class="multisites-column" ng-click="model.sortBy('nb_uniq_visitors')" ng-class="{columnSorted: 'nb_uniq_visitors' == model.sortColumn}"> 
                <span ng-class="{multisites_asc: !model.reverse && 'nb_uniq_visitors' == model.sortColumn, multisites_desc: model.reverse && 'nb_uniq_visitors' == model.sortColumn}" class="arrow"></span> 
                <span class="heading">{{ 'General_ColumnNbUniqVisitors'|translate }}</span> 
            </th> 
```
From `/plugins/MultiSites/angularjs/dashboard/dashboard.directive.html`

### Step Two
Add `nb_uniq_visitors` in the showColumns.

```
var params = {
                module: 'MultiSites',
                action: 'getAllWithGroups',
                hideMetricsDoc: '1',
                filter_sort_order: 'asc',
                filter_limit: model.pageSize,
                filter_offset: getCurrentPagingOffsetStart(),
                showColumns: 'nb_uniq_visitors,label,nb_visits,nb_pageviews,visits_evolution,pageviews_evolution,revenue_evolution,nb_actions,revenue'
            };
```
From `/plugins/MultiSites/angularjs/dashboard/dashboard-model.service.js`

### Last Step
Change `website.revenue` to `website.nb_uniq_visitors`

```
<td class="multisites-column">
        {{ website.nb_uniq_visitors }}
    </td>
```
From `/plugins/MultiSites/angularjs/site/site.directive.html`

As you can see from the picture below, I get nothing!
![piwik](https://cloud.githubusercontent.com/assets/2368001/9895609/f61a38ba-5c63-11e5-83d6-3199bd279750.png)

Any idea to solve this problem?

**Comment by mattab** [comment]
Hi @jerrycave 

We don't here support code changes in Piwik directly. Maybe ask your question in the `Plugins & Platform ` forum: http://forum.piwik.org/list.php?9

**Comment by phips28** [comment]
@triffic-tang have you ever fixed this?
