### ISSUE TITLE
Clarify meaning of "Search Result Pages" and search_count

### ISSUE THREAD

**Issue by dhoko** [piwik/piwik#8802]
Hi,

The search count doesn't work here. Piwik is up to date, so we tried on a clean install too, nope :/ 
Tested via POST or GET, ex request:

```
http://foo.bar:20280/piwik.php?search=jean&search_count=825&idsite=1&rec=1&r=747679&h=15&m=21&s=38&url=http%3A%2F%2Ffoo.bar%3A3000%2F%23%2Fsearch%3Fq%3Djeanne&_id=8f10a22315783aa6&_idts=1442409669&_idvc=1&_idn=0&_refts=0&_viewts=1442409669&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=2112.000045776367x1188.0000257492065&gt_ms=17
```

So we have `search_count=825` and 
![screenshot from 2015-09-16 15 26 24](https://cloud.githubusercontent.com/assets/713283/9905808/5dac5d82-5c87-11e5-8ba3-67f5f173e8c9.png)

 *There is more than 1 result for other queries*

## Edit 1

It seems to work as expected if the search_count is 0 cf:

![screenshot from 2015-09-16 15 40 48](https://cloud.githubusercontent.com/assets/713283/9906218/73761034-5c89-11e5-9e07-e3f1f91317ec.png)

### Query red 758 results
![screenshot from 2015-09-17 09 27 51](https://cloud.githubusercontent.com/assets/713283/9927505/53daf884-5d1f-11e5-8a68-ae881c431b13.png)

### Query red (2) 758 results
![screenshot from 2015-09-17 09 28 23](https://cloud.githubusercontent.com/assets/713283/9927520/77865e04-5d1f-11e5-8250-ca37b33113a7.png)

### Query papier 1000 results
![screenshot from 2015-09-17 09 29 10](https://cloud.githubusercontent.com/assets/713283/9927527/88ed1a70-5d1f-11e5-896f-fbc4d51a33dc.png)

### Query red (3) 758 results
![screenshot from 2015-09-17 09 32 06](https://cloud.githubusercontent.com/assets/713283/9927536/99911764-5d1f-11e5-8bcc-ebd57042edd3.png)
 results

### Query papier (2) 1000 results
![screenshot from 2015-09-17 09 37 07](https://cloud.githubusercontent.com/assets/713283/9927547/c9eb0118-5d1f-11e5-9096-676e758b03a8.png)

*After a query papiers and another red*

As you can see the count is random :/

**Comment by mattab** [comment]
Hi @dhoko 

At the moment, Piwik uses only the case `search_count=0` to detect that a Site Search had no result, to show them in the "Search keywords with no result" report. If `search_count` is bigger than `0`, currently this data is not tracked in Piwik and not used in the reporting.

**Comment by mattab** [comment]
I'm wondering, what did you expect, and maybe we could improve documentation to make it more clear. Did you think `search_count` would impact `Search result pages` metric/column?

**Comment by dhoko** [comment]
Hum i was expecting to have the `search_count` value into _Search result pages_.
I have only one per per search (lazy load results on scroll), so that's why i don't understand this column, why do we have 5,5 etc. ?


If you use `search_count` as a boolean this name is wrong :)

**Comment by mattab** [comment]
> Hum i was expecting to have the search_count value into Search result pages.

Search result pages actually indicates the number of times a user has searched for this keyword, if user clicks on "Page 2" it will search another time and Piwik will count as "2 Search result pages". 

> If you use search_count as a boolean this name is wrong :)

we only use the value when `search_count=0` but it's not a boolean. Maybe later we could report "Number of search results" (or this could be done in a plugin)

**Comment by dhoko** [comment]
Ok :) 

But I don't understand why there is a 5.5 : 

![](https://cloud.githubusercontent.com/assets/713283/9927547/c9eb0118-5d1f-11e5-9096-676e758b03a8.png)

**Comment by RMastop** [comment]
Hi @mattab,
I was under the assumption that the Search Results Pages was the amount of search results devided by the amount of searches. after all, we do add the number of results in a tag like it was specified in this guide:
http://developer.piwik.org/guides/tracking-javascript-guide#internal-search-tracking 

// Number of results on the Search results page. Zero indicates a 'No Result Search Keyword'. Set to false if you don't know

**Comment by mattab** [comment]
I think to clarify this issue we could  Display Site Search Results Count, in Site Search Keywords widget - covered in #8991 

if that is not enough to clarify this issue please comment here to ask me to re-open
