### ISSUE TITLE
VisitorMap doesn't show anything when segment parameter is URL-encoded

### ISSUE THREAD

**Issue by hagor** [piwik/piwik#8813]
When using an encoded parameter for the segment, the VisitorMap widget does not show the visited countries. Anyway the number of total visits is still shown correctly.
Once the encoding is removed, the visited countries are marked correctly again.
![piwik_visitormap_param_encoded_error](https://cloud.githubusercontent.com/assets/12829879/9932340/6562bc80-5d43-11e5-8f95-6195d77b948d.png)
![piwik_visitormap_param_not_encoded](https://cloud.githubusercontent.com/assets/12829879/9932341/65640d42-5d43-11e5-8129-304e85a8aff1.png)

Maybe the widget is not resolving the encoding and only matches the segment 1:1 with the database and cannot find a matchingsegment (browser triggered archiving is disabled in our case)

Segment definition in DB:
pageUrl=@web.mysite.com/en-us
Segment parameter encoded:
pageUrl%3D%40web.mysite.com%2Fen-us
Segment parameter not encoded:
pageUrl=@web.mysite.com/en-us

Using Piwik 2.14.3

**Comment by mattab** [comment]
Let's check that this is likeky fixed with #8805

**Comment by mattab** [comment]
@hagor can you please try again with latest Piwik 2.15.0-beta 12 ? This may be fixed already, thanks for letting us know either way :+1:

**Comment by hagor** [comment]
@mattab I just installed the newest beta but unfortunately I can reproduce the error
I forgot to mention last time, when I click on an not marked country I get the error message you can see in the bottom left corner
![piwik_visitormap_2 15 0-b12_error](https://cloud.githubusercontent.com/assets/12829879/10020871/69e29d92-6145-11e5-9783-4017be76569f.png)

**Comment by mattab** [comment]
@hagor tried to reproduce on the demo but it seems to work: https://demo.piwik.org/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserCountryMap&actionToWidgetize=visitorMap&idSite=7&period=day&date=yesterday&disableLink=1&widget=1&segment=pageUrl%3D%40en loads the map correct on FF and Chrome. can you reproduce on demo

**Comment by mattab** [comment]
Can be reproduced on demo: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&segment=customVariableName3%3D%3DForum%2520status%3BcustomVariableValue3%3D%3DLoggedIn%2520user#?module=UserCountry&action=index&idSite=7&period=day&date=yesterday&segment=customVariableName3%3D%3DForum%2520status%3BcustomVariableValue3%3D%3DLoggedIn%2520user

The map does not show the indian, London users

**Comment by hagor** [comment]
Ah alright, thats the same effect.

Somehow I was not able to reproduce this error with the pageURL yet.

**Comment by diosmosis** [comment]
@mattab Can you reproduce on demo2?

**Comment by mattab** [comment]
@diosmosis it can be reproduced on http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&segment=customVariableName3%3D%3DForum%2520status%3BcustomVariableValue3%3D%3DLoggedIn%2520user#?module=Dashboard&action=embeddedIndex&idSite=7&period=day&date=yesterday&idDashboard=1&segment=customVariableName3%3D%3DForum%2520status%3BcustomVariableValue3%3D%3DLoggedIn%2520user
