### ISSUE TITLE
manual onclick events cause JS error

### ISSUE THREAD

**Issue by ctrl-alt-deleted** [piwik/piwik#8814]
Hello everyone,

I  am trying to use onClick event tracking option, see below:

`<a href="#" onclick="javascript:_paq.push(['trackEvent', 'Menu', 'Freedom']);">Freedom page</a>`

this does not fire the event, instead JS error shown in the console.

`TypeError: L[Y] is undefined
...=1){X=arguments[W];Y=X.shift();if(n(Y)){L[Y].apply(L,X)}else{Y.apply(L,X)}}}func... `

further looking at the source it could be down to  `apply()` function being  the culprit

            var i, f, parameterArray;

            for (i = 0; i < arguments.length; i += 1) {
                parameterArray = arguments;
                f = parameterArray.shift();

                if (isString(f)) {
                    asyncTracker[f].apply(asyncTracker, parameterArray);
                } else {
                    f.apply(asyncTracker, parameterArray);
                }
            
        }

on `LINE:598:  asyncTracker[f].apply(asyncTracker, parameterArray); `

**Comment by mattab** [comment]
Hi @ctrl-alt-deleted - can you try to add the Piwik  javascript tracking code in the `<HEAD>`, does this fix the issue?

**Comment by ctrl-alt-deleted** [comment]
@mattab   tried , still get the same issue

**Comment by tsteur** [comment]
Which version of Piwik are you using? How do you embed Piwik into your site? Are you using the default tracker code as shown by the tracking code generator?

**Comment by ctrl-alt-deleted** [comment]
@tsteur   
- Version 2.14.3
- the code embedded before the closing </body>
- yea i am using the default tracker  code, created by the generator

**Comment by tsteur** [comment]
The problem is that `asyncTracker[f]` seems to be not defined which I don't really understand why this would be the case. Do you mind sending us a link to debug to  hello (at) piwik.org  and leave a comment here in case it goes to the spam folder? I'd try to reproduce on that page

**Comment by mattab** [comment]
@ctrl-alt-deleted could you help us? see previous comment

**Comment by ctrl-alt-deleted** [comment]
@mattab  i have sent a email , srry for late reply

**Comment by tsteur** [comment]
The seen error there is expected since it is not calling a valid method

`javascript:_paq.push(['SEO1', 'test', 'Link1']);`  `SEO1` is not a valid method.

It should be eg `javascript:_paq.push(['trackEvent', 'test', 'Link1']);`
