### ISSUE TITLE
 Jqplot axis label top part looks missing a little, character doesn't display complete.

### ISSUE THREAD

**Issue by weixuezhang** [piwik/piwik#8821]
Jqplot axis label top part looks missing a little, character doesn't display complete, see attached screenshot. Does anyone can help to fix this?

**Comment by weixuezhang** [comment]
see http://forum.piwik.org/read.php?2,129232,129451#msg-129451

**Comment by sgiehl** [comment]
Which browser are you using?
Can only reproduce when zooming in to 250% on chrome.

**Comment by mattab** [comment]
I was sure to have seen this bug like 2-3 weeks ago, but also can't reproduce it now. @weixuezhang do you still have this problem on demo.piwik.org ?

**Comment by weixuezhang** [comment]
I cannot see this issue on demo now.

**Comment by mattab** [comment]
Please upgrade to latest 2.15.0 beta: http://piwik.org/faq/how-to-update/faq_159/

Which should include the fix. if you still have the problem, please reopen the issue
