### ISSUE TITLE
Disable 'Provider' plugin by default for new Piwik users

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8826]
Currently, Provider plugin is enabled by default in Piwik. In Piwik 3.0.0 we aim to move this plugin to the Marketplace in #5341.

In the meantime, since Provider plugin can negatively affect Tracking API performance #8785, since the value provided by the plugin is small, I suggest we do not enable the plugin by default for new users. This will be good for user experience, tracking speed, and minimising support in LTS.

**Comment by mattab** [comment]
#8827 was reverted but is not yet re-opened

**Comment by MagicFab** [comment]
While reading this it occurred to me some method of caching such information could be implemented later on (unless that's already the case), just writing it here to not forget it.

**Comment by MagicFab** [comment]
This also means for anyone upgrading from a previous version Provider data will not be tracked / kept until the Provider plugin is re-activated. 

TL:DR; If you're upgrading from <2.15 and Provider data is important to you, verify the plugin is re-activated properly as part of the upgrade procedure.

**Comment by mattab** [comment]
@MagicFab the Provider plugin is not disabled on Update, only "not enabled for users installing Piwik new"
