### ISSUE TITLE
piwik-2.15.0-b8: Incorrect redirect on plugin deactivation

### ISSUE THREAD

**Issue by Joey3000** [piwik/piwik#8828]
**Test procedure:**

1. Install piwik-2.15.0-b8 in a subdirectory (e.g. `/p`) on a remote server (see https://github.com/piwik/piwik/issues/8824 for DB access issues on installation and afterwards)

2. Log in as super-user and go to Administration -> Plugins

3. Deactivate a plugin (e.g. ExampleAPI)

**Expected results:**
3. The Plugins page reloads (using correct redirect) with the plugin shown as inactive

**Actual results:**
3. Following redirect occurs: `GET http://[...]/p/index.php?module=CorePluginsAdmin&action=deactivate&pluginName=ExampleAPI&nonce=b577c83c4293bc846f732510a5ed66f7` responds with status code `302 Found` and header `Location: http://[...]/` (i.e. the root directory of the Piwik installation domain).

There are two issues (which may have the same root cause) with that Location header:
* The Piwik installation subdirectory (e.g. `/p`) is not considered - domain root is used instead
* The `index.php?module=CorePluginsAdmin&action=plugins&idSite=1&period=range&date=last30`, etc., part is missing

That is all on a remote server with PHP 5.5.22, MySQL 5.1.73 with PDO\MYSQL.

Notes:
- The issue does not occur on plugin activation, but only on deactivation
- piwik-2.15.0-b8 is the first I tried after piwik-2.14.3, so I don't know which beta this issue occurred with first.
- I don't know if this issue is related to the above mentioned https://github.com/piwik/piwik/issues/8824

**Comment by tsteur** [comment]
Are you using any browser plugins or is your server maybe removing the referrer? It is pretty much redirecting to `$_SERVER['HTTP_REFERER']`.

**Comment by tsteur** [comment]
It should fallback to https://github.com/piwik/piwik/blob/2.15.0-b8/core/Url.php#L127-L169 if there is no referrer but possibly there's a bug maybe

**Comment by Joey3000** [comment]
> Are you using any browser plugins or is your server maybe removing the referrer? It is pretty much redirecting to $_SERVER['HTTP_REFERER'].

That was it, thanks! I do indeed use a referrer overwriting plugin and it was misconfigured to send the domain root directory. I'm sorry for the trouble. Closing this as Piwik 2.14.3 behaves the same way.
