### ISSUE TITLE
Release Piwik 3.0.0-b1

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8836]
Important steps for successful Piwik 3.0.0-b1 release

Prior to release 3.0.0-b1 we must:

* [x] Before merging Piwik 3.0 into master we need to: make all submodule plugins compatible with 3.0.
* [x] developer.piwik.org:  once Piwik 3 is into `master`, we need to increase the version number so our developer documentation display the Version selector for this new major release (https://github.com/piwik/developer-documentation/issues/138)
* [x] search in codebase for `3.0.0-` and update the code - likely these occurences of `3.0.0-` should be replaced with `4.0.0-`  ?
* [x] api.piwik.org: make sure that  **api.piwik.org service returns correct 2.X beta**, on
Latest 2.X beta channel,  should NOT return 3.0.0-b1. URL: http://api.piwik.org/1.0/getLatestVersion/?release_channel=latest_2x_beta 
*  [x] api.piwik.org: make sure standard channel returns latest 3.0.0-b1 ONLY IF php 5.5 or later http://api.piwik.org/1.0/getLatestVersion/?release_channel=latest_beta
* [x] Create a new guide "Migrate Plugin from Piwik 2.X to Piwik 3" (done in https://github.com/piwik/developer-documentation/pull/139)
* [x]  Move this checklist to a wiki page so we can re-use the knowledge when we'll release next major release Piwik 4 as we'll have to do all these steps again
* [x]  **update piwik  package script**, we need to edit build script https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh ...

SEE THIS https://github.com/piwik/piwik/wiki/New-major-releases

(from https://github.com/piwik/piwik/pull/8688  )

**Comment by mattab** [comment]
Great material for our beta1 announcement blog post in the Material redesign PR: https://github.com/piwik/piwik/pull/10397

**Comment by sgiehl** [comment]
We also need to decide how to handle the translations in the future, as translations might get different between 3.x and LTS version. We have two possibilities using transifex:

- Keep using our current transifex project, update the translations automatically using 3.x translations
  This won't make it possible to update the translations for 2.x LTS in the future
- Create a new project on transifex to be able to handle both versions in different projects. This might make it harder for translators, but as translations between projects are synced if they equal it shouldn't be problematic. This way we would still be able to update translations for both versions.

**Comment by mattab** [comment]
@sgiehl It is  reasonable not to update translations for LTS as they are not Major/Critical updates which we focus on in LTS.  So let's keep things simple and Transifex lean :+1:

**Comment by mattab** [comment]
Should be done! we are ready to release 3.0.0-b1 whenever all issues in the milestone will be closed :+1:
