### ISSUE TITLE
Javascript isn’t being loaded in the admin panel

### ISSUE THREAD

**Issue by jonnybarnes** [piwik/piwik#8839]
This could be due to anything and I’m not sure what.

I’m running Firefox Nightly (v44), my local maching is running PHP7 behind nginx 1.9.4 with the HTTP/2 patch applied.

When I look at the admin HTML source of the admin panel I see the line:
```
<script type="text/javascript" src="index.php?module=Proxy&amp;action=getCoreJs&amp;cb=68d318c61961d4506b48f3fbb6d37920"></script>
```

and if I manually visit that URL I see a load of jQuery text in my browser.

However when just visiting the admin CP it isn’t loaded. Thus leading to an error of `ReferenceError: $ is not defined` when later scripts are assuming jQuery has been loaded.

I don’t know why Firefox isn’t even trying to load the script?

**Comment by tsteur** [comment]
Are you using an Ad blocker? See eg https://github.com/piwik/piwik/issues/7928

**Comment by jonnybarnes** [comment]
Disabling uBlock for the page worked! Thanks.
