### ISSUE TITLE
Running testsuite local (IntegrationTests )

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#8846]
Hello,

to get the `IntegrationTests` up and running i needed to manually adjust some things.

After going through https://developer.piwik.org/guides/getting-started-part-1

I needed to adjust the config https://github.com/piwik/piwik/blob/b2f5b5489ceca056217fc6663ec6c2c6b052cd42/tests/PHPUnit/config.ini.travis.php
```
[tests]
request_uri = "/"

[log]
log_writers[] = file
log_level = info
```

Would it make sense to automatically do this on `./console development:enable` ?

Else maybe just mention it on getting-started-part-1 guide?

**Comment by tsteur** [comment]
It's possibly introduced by the new `LogViewer` plugin that I added recently. Can you let me know which tests fail for you and I'd try to write them in a way that they do not fail and do not need any custom adjustments.

**Comment by ThaDafinser** [comment]
@tsteur nope `LogViewer` did not introduced this.

There is just no documentation, what settings you need to run this testsuite.

I use those settings now (mostly from the travis config link above)
```
[database_tests]
host = 127.0.0.1
username = piwik_developmen
password =test
dbname = piwik_tests
adapter = PDO\MYSQL
; no table prefix for tests on travis
tables_prefix =

[tests]
http_host = "http://localhost/GitHub/piwik"
request_uri = "/"

[log]
log_writers[] = file
log_level = info

[Development]
enabled = 1
disable_merged_assets = 1
```

**Comment by tsteur** [comment]
Oh, this sounds like a bug then. Our tests *should* be config independent. If it is config independent and we cannot fix it for some reasons we should add list print this information and check whether config is configured as needed etc.

**Comment by ThaDafinser** [comment]
Some specials i found:
- the database name must be `piwik_tests` (its checked somewhere in the tests)
- `tables_prefixes` must also be blank, otherwise they fail too

**Comment by mattab** [comment]
@tsteur what do you reckon is our next steps here?

**Comment by tsteur** [comment]
I'm not sure. Ideally we have a specific case that we can reproduce and fix, not sure if this is given here.

**Comment by mattab** [comment]
@ThaDafinser please create a new issue with steps to reproduce issue and we'll investigate!
