### ISSUE TITLE
Field 'location_browser_lang' doesn't have a default value In query

### ISSUE THREAD

**Issue by pouyana** [piwik/piwik#8853]
Hi there,
after migrating from MYSQL to MARIADB, and having STRICT_TRANS_TABLES on, I encounter the same error as #6028.
Error query: SQLSTATE[HY000]: General error: 1364 Field 'location_browser_lang' doesn't have a default value.
Any Help would be appreciated.
Piwik version the last stable  2.14.3

**Comment by tsteur** [comment]
This might be actually introduced by https://github.com/piwik/piwik/pull/8589/files as we cannot define database updates currently we should maybe remove `STRICT_TRANS_TABLES` from the SQL mode? @mattab I can imagine that this problem will be faced by many users

**Comment by mattab** [comment]
Fyi @tsteur: #8589 was introduced in 2.15.0-b3 but @pouyana is using 2.14.3

**Comment by mattab** [comment]
@tsteur if you think it's something to investigate before 2.15.0 please move it to milestone

**Comment by tsteur** [comment]
Ideally we would make all columns nullable but this would be a big, long running update statement that we cannot do.

As `STRICT_TRANS_TABLES` will be enabled soon this cat hit many users maybe, not sure how it happens though. I can imagine eg disabling the `UserLanguage` plugin can break tracking, also disabling other plugins might break tracking if they define a dimension with a `not null` column.
 
I guess we should remove `STRICT_TRANS_TABLES` from SQL modes for now but it would be good to have

**Comment by mattab** [comment]
>I guess we should remove STRICT_TRANS_TABLES from SQL modes for now but it would be good to have

OK to play it safe, we probably should do this. But, we can add it in 3.0 branch already, to bring best practise to the future major release. sounds good?

**Comment by mattab** [comment]
PR: #8930

**Comment by tsteur** [comment]
> . But, we can add it in 3.0 branch already, to bring best practise to the future major release. sounds good?

This would mean we need to update all dimensions to be nullable I guess. Also we need to check possible other tables for not nullable columns and whether they will be always set. Shall we create an issue?

**Comment by Joey3000** [comment]
>> I guess we should remove STRICT_TRANS_TABLES from SQL modes for now but it would be good to have

> OK to play it safe, we probably should do this. But, we can add it in 3.0 branch already, to bring best practise to the future major release. sounds good?

Just a remark: Using `STRICT_TRANS_TABLES` would require a bump of the minimum MySQL version to 5.0 on https://piwik.org/docs/requirements/. (Because according to https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html, it was first introduced on 5.0.2, which was one of the alpha versions of 5.0 - see the "Table of Contents" in https://dev.mysql.com/doc/relnotes/mysql/5.0/en/.) See also https://github.com/piwik/piwik/issues/9088#issuecomment-151560592 for other SQL Mode values.

**Comment by mattab** [comment]
> This would mean we need to update all dimensions to be nullable I guess. Also we need to check possible other tables for not nullable columns and whether they will be always set. Shall we create an issue?

Created an issue for this to fix the issue globally:  Make all log_* tables fields NULLable to prevent errors "Field 'X' doesn't have a default value" #9231
