### ISSUE TITLE
2.15b13 Summary in visitor-profile counts wrong

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8855]
2.15b13 Summary in visitor-profile counts wrong
- events seems to be counted as sites

not sure if this wrong counting maybe also be used elsewhere?

please see attachment
![2015-09-26_13h05_33](https://cloud.githubusercontent.com/assets/5681880/10117252/f752f494-644f-11e5-8f25-156cace1cf04.png)

**Comment by tsteur** [comment]
Nice find :+1: we might rename it to something like "... performed 4 actions" or we fix the pageview number

**Comment by hpvd** [comment]
:-)
would prefer to see both numbers here:
fixed number of sites (1) + events/action (3)
what do you think?

**Comment by tsteur** [comment]
I'm using it too rarely to have a proper opinion. I guess it always depends on the kind of site that one has. Pageview is maybe more meaningful than actions for most sites.

**Comment by hpvd** [comment]
yes page view is more important -> so we should show corrected number
actions is also interesting because you get a feeling how intense single people use/like the site
that's why I vote for both :-)

to dig a little deeper:
is this actual faulty number used elsewhere? or is it calculated only for this site?

**Comment by mattab** [comment]
Maybe we could display both Actions and pages, when they are different, something like this:

> and viewed 4 pages (performed 6 actions)

(when pages != actions)

> and viewed 4 pages

(when pages == actions)
