### ISSUE TITLE
Improve date selector usability

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#8864]
When using the date selector, the calendar and month/year dropdown all remain available without regards to the type of date range chosen.

I'd like to suggest to move the date type selection to the left, making this a 2 step selection:
- Select type of date range (for example: year)
- Calendar view changes accordinlgly (if needed, in this example, only allow year values choice)
- Confirm selection by choosing value (for example, for year: current, other from dropdown)

Currently one needs to double click on a month day to enable any date range selection (except for custom).

I am no usability expert, so I trust the above will be adapted or interpreted according to other similar tools and practices.

**Comment by Undergrounder** [comment]
+1

I have already seen some coworkers choosing the wrong date range because of this usability problem.

**Comment by tsteur** [comment]
:+1:

**Comment by mattab** [comment]
Agreed the calendar is confusing to use for first time users. Would be nice to improve it... heard this feedback from a friend in person last week as well ;-) 

Here is another suggestion:
 * As soon as one changes the period (click on a radio button), Piwik loads this period for the currently selected date

This would simplify very much the usability...  as a downside, it would take a bit longer to change the Period as well as change the Date. We should check Piwik will load the calendar very fast to let one change the date after the page reloaded with the new period. Thoughts?

**Comment by tsteur** [comment]
I find the downsides for when not wanting to see the current week too annoying for such a change.

Maybe we could always show the "Apply" button which is currently named "Apple date range" and only shown when the range period is selected. It wouldn't even take more space, maybe a tiny bit.

Someone could either select week and press apply and doesn't have to choose a day, someone else can still select another day.

**Comment by MagicFab** [comment]
I agree not applying the date range immediately is important, in many cases (specially big date ranges) a small mistkae will mean waiting a long time and having to click through date choosing again.

**Comment by MagicFab** [comment]
Some useful links:
- http://www.uxmatters.com/mt/archives/2011/08/date-filters-successful-calendar-design-patterns.php
- http://adhockery.blogspot.ca/2011/03/form-input-controls-for-datetime-values.html

Reading about this also made me think of the mobile implementation (either web access or the Android/Iphone apps), and accessibility (mentioned here: https://github.com/piwik/piwik/issues/4167 )

**Comment by mattab** [comment]
@tsteur maybe we can add this "Apply" button for all periods, in our calendar in 2.15.0? this is nice usability win

**Comment by MagicFab** [comment]
Just checked the demo site with "Apply" button implemented for all periods - simple + effective! Thank you :) 

Now my muscle memory is battling it but I see the old behavior is still there, so it will be a gradual adjustment ;)

**Comment by tsteur** [comment]
Pro tip that I just noticed while reading the code: A double click on a period label or radio button should directly select the period and reload the page :) As long as it is not the currently selected one...
