### ISSUE TITLE
Don't count search terms in paginated results

### ISSUE THREAD

**Issue by raj45** [piwik/piwik#8865]
Certain very specific keywords crawl to the top of the list over most used Site Search Keywords on my site, because of pagination, where the Search Keyword is inserted every time the user clicks "Next page" in the search result.

It would be great if there was an option to exclude a Site Search Keyword from being counted, if there is a parameter like "page" in the URL.

Original post: [Search terms are repeated when pagination is used](http://forum.piwik.org/read.php?2,129206)

**Comment by mattab** [comment]
Hi @raj45 I don't really understand this, could you maybe clarify or post a screenshot showing the problem?

**Comment by raj45** [comment]
A search term like "dkcclterm.id = 80614160", which has definitely only been done once today shows as being done six times today

The only explanation I can see is because the search term is being counted every time the user clicks on "next page" for the search result of "dkcclterm.id = 80614160".

**Comment by mattab** [comment]
"Searches" should be the number of actual people who did the search. You should see six in the column "Search result pages" and one in "Searches"

**Comment by raj45** [comment]
This is what I see, and I am pretty certain some of the searches have only been done once that day, but the count is more than one:
![selection_002](https://cloud.githubusercontent.com/assets/7046001/11439396/636c7eda-94fb-11e5-9bd1-1f104f08eeec.png)

**Comment by mattab** [comment]
@raj45 I cannot reproduce, for me it works fine when a same visitor does multiple searches, I see `Searches` column stays at `1` even though I have paged through search result pages.

**Comment by mattab** [comment]
If you have steps to reproduce, please comment here /reopen or create a new issue

**Comment by raj45** [comment]
@mattab: I have done a test, and you are absolutely right - if a multi-paged search is performed, the <code>Searches</code> column stays at <code>1</code>. Now I just have to find out why certain very odd searches sometimes climb to the top of search terms ...
