### ISSUE TITLE
Usability of Admin Menu should be optimized

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8868]
Usability of Admin Menu should be optimized:
at this time you could not identify easily where you are. Please see attachment.
There are two reasons for this:
- highlighting of active menu item is only bold (no change of colour and or background)
- the opened site does not start with a headline matching with menu entry

![2015-09-29_15h09_55](https://cloud.githubusercontent.com/assets/5681880/10165137/d93ea442-66bd-11e5-8af3-6016d9f8df75.png)

**Comment by tsteur** [comment]
See https://github.com/piwik/piwik/issues/7588 and we're working on a new design where it will be clearer which page will be activated see eg https://github.com/piwik/piwik/issues/7589#issuecomment-142618101

It will be pretty clear which site is active. It still won't use the headline on the top again which would be ideal but think when it's clear on the left which menu item is selected we do not have to repeat it in the right page content.

I'll close it for now but feel free to reopen in case you think we still need the same headline on the top with the new menu. We will release a beta with the new menu in the next days I think

**Comment by hpvd** [comment]
thanks for pointing to the other tickets!
