### ISSUE TITLE
Favicon is unsharp / blurry on MacBook Retina displays

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8869]
See screenshot and comparison with Github favicon:

<img width="117" alt="favicon" src="https://cloud.githubusercontent.com/assets/273120/10167798/5b38b3d2-66ca-11e5-99f4-da9b0923d4d8.png">

I hope one can see it on a normal display

**Comment by MagicFab** [comment]
It seems the current favicon is missing other sizes resources in it, see:
https://github.com/audreyr/favicon-cheat-sheet

Following that logic a number of other resources need to be created for it to look perfect in other browsers (mobile, etc.).

**Comment by quba** [comment]
I confirm. All icons in dashboard also need to be updated (folders, browsers, OS, etc.).

**Comment by tsteur** [comment]
Footer icons in data tables are very unsharp as well

**Comment by tsteur** [comment]
Same for Piwik update screen. The logo on top is not SVG and therefore blurry. 

It is also not displaying a custom logo at the top of the update screen which is not related to this one though. (maybe it can be changed it one step)

**Comment by mattab** [comment]
Maybe it is as easy as replacing the 16x16 favicon by our 32x32 favicon http://piwik.org/favicon.png ?

**Comment by tsteur** [comment]
Yep, that would be already better I reckon. Probably we need to specify the favicon in different sizes though in meta see eg https://github.com/audreyr/favicon-cheat-sheet not sure if needed though.

Many other icons and images are blurry too, shall we create separate issue for them?

**Comment by mattab** [comment]
> Many other icons and images are blurry too, shall we create separate issue for them?

Yes, this is bigger project, but do-able (need to coordinate with designers)

**Comment by tsteur** [comment]
done #9292

**Comment by tsteur** [comment]
I reckon we need to `favicon.png` as ico @mattab
