### ISSUE TITLE
Can't remove first dashboard (idDashboard=1)

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#8870]
I can't remove the first Dashboard. If there is only one, "Remove Dashboard" and other options are not available. 

If there are multiple Dashboards and I want to only remove the first one, confirmation is requested as usual, confirming does not delete the Dashboard.

**Comment by sgiehl** [comment]
That one can't be removed as dashboard with id `1` will always be loaded by default. That way it is also sure that at least one dashboard exists for every user.
Guess we should disable the remove link for that one or display a message when the user tries to remove it.

**Comment by mattab** [comment]
>  Guess we should disable the remove link for that one or display a message when the user tries to remove it.

Or maybe we can "Grey out" the link, and on hover show a tooltip "The default dashboard cannot be removed." - what do you think?

**Comment by MagicFab** [comment]
@mattab +1 for your suggestion.
