### ISSUE TITLE
Top menu: On hover of username and administration show their menu structure in tooltip

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8872]
I wonder if it was a good idea to show the menu structure of the user menu when hovering the user name in the top right menu and the same for administration. This would give a better overview on what can be done there. 

For example like this: 
![hovermenu](https://cloud.githubusercontent.com/assets/273120/10187027/a1f8e4be-6755-11e5-8ce9-e175af3a137c.png)

**Comment by mattab** [comment]
marking this one as wontfix  as I think it would be better instead if the awesome search searched across all menus instead of having a big tooltip. it was a quite nice idea though :)
