### ISSUE TITLE
2.15.0-b14 not availabe with piwik update

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8874]
2.15.0-b14 available here:
https://github.com/piwik/piwik/releases
not available  with piwik update within piwik admin backend

![2015-09-30_15h19_45](https://cloud.githubusercontent.com/assets/5681880/10194030/bceec960-6786-11e5-85b4-9bfc183f834c.png)

![2015-09-30_15h17_31](https://cloud.githubusercontent.com/assets/5681880/10194071/f7b8bee8-6786-11e5-9b36-fd52c0d5006a.png)

![2015-09-30_15h17_52](https://cloud.githubusercontent.com/assets/5681880/10194052/d75ce4ee-6786-11e5-8913-eb1e62d81cc4.png)

**Comment by tsteur** [comment]
Can you click on "Administration" and check which release channel is activated in "Update settings"? It should be under the menu item "Settings => General".

**Comment by hpvd** [comment]
ah ok there the "stable channel" is selected.
But we have not changed it for months: it was always beta.
So the last update to b13 should have switched this...?

**Comment by hpvd** [comment]
=> so this could be closed but maybe we need a new one "automatic channel switching"?

**Comment by mattab** [comment]
Maybe the migration script https://github.com/piwik/piwik/blob/remove_lazy_flush/core/Updates/2.15.0-b12.php did not keep your beta channel preference as expected (was your config file writable by the unix user during migration?)

**Comment by mattab** [comment]
I tested the migration script and it works. Likely your config was not writable so the migration didn't execute.
