### ISSUE TITLE
Report using segments for same URL starting with or without "/" gives different results

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#8900]
These two reports for the same URL (one variant with leading "/", the other without) give different results.

1)  URL contains /forum.piwik.org/list.php?2 -> No result (likely a bug) 

Reproduced here: https://demo.piwik.org/index.php?module=CoreHome&action=index&date=today&period=month&idSite=7&segment=pageUrl%3D%40%252Fforum.piwik.org%252Flist.php%253F2#/module=Actions&action=menuGetPageUrls&date=today&period=month&idSite=7&segment=pageUrl=@%252Fforum.piwik.org%252Flist.php%253F2

2) URL contains forum.piwik.org/list.php?2  -> Returns results (appears to work for use) 

Tested here: https://demo.piwik.org/index.php?module=CoreHome&action=index&date=today&period=month&idSite=7&segment=pageUrl%3D%40forum.piwik.org%252Flist.php%253F2#/module=Actions&action=menuGetPageUrls&date=today&period=month&idSite=7&segment=pageUrl=@forum.piwik.org%252Flist.php%253F2

**Comment by mattab** [comment]
Thanks for report. Already reported at https://github.com/piwik/piwik/issues/8878
