### ISSUE TITLE
"Page URL not defined" in Visitor Log

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#8909]
Hi!
Today I saw that something wrong with the Visitor Log and Live Visits widget.
See screenshots
Visitors in Real-time
![live visitors](https://cloud.githubusercontent.com/assets/740757/10269187/d64e31a8-6ad7-11e5-9fe6-90c723aee84c.jpg)

Visitor Log
![visitor log](https://cloud.githubusercontent.com/assets/740757/10269190/e3cf294a-6ad7-11e5-8021-af35989594b2.jpg)

Visitor Profile
![visitor profile](https://cloud.githubusercontent.com/assets/740757/10269191/ed26fc16-6ad7-11e5-9938-dd73fca26152.jpg)

What's wrong?

PS! Piwik 2.14.3

**Comment by tsteur** [comment]
It's hard to tell, it looks like there was no URL set with the request. Can you hover the Visitor-Id and click on the export icon that should appear next to it? There you will see more details. Is a page title set? Can you maybe try to reproduce the steps?

**Comment by hpvd** [comment]
hmm in visitor log I haven't seen this before, but the Visits widget looks the same in our installation.
Maybe it's fine this way and  I didn't get what it wanted to show?

**Comment by Globulopolis** [comment]
@tsteur below what I see in exported XML

```xml
<row>
<type>action</type>
<url/>
<pageTitle/>
<pageIdAction/>
<serverTimePretty>Sun 4 Oct 04:33:29</serverTimePretty>
<pageId>1634354</pageId>
<timeSpent>1</timeSpent>
<timeSpentPretty>1s</timeSpentPretty>
<icon/>
<timestamp>1443933209</timestamp>
</row>
```

And I cannot reproduce this :(

**Comment by tsteur** [comment]
How often does it occur? Was it only once? I'm not 100% sure whether `pageId` refers to `log_action` table but in case you have access to the database, can you run the following query?

```sql
SELECT * FROM piwik_log_action WHERE idaction = 1634354;
```

If you use a different database table prefix you might have to remove `piwik_` after the from or replace it with something else.

**Comment by tsteur** [comment]
FYI: I just had a similar case and it happened when there was a download without an absolute URL. Eg I did something like `_paq.push(['trackLink', '/download.pdf', 'download'])`. This resulted in `Page URL not defined`. After adding a domain it worked

**Comment by mattab** [comment]
Added to our FAQ [ What is “page url not defined” in the Pages report?](http://piwik.org/faq/general/faq_75/)

the following:
 > 3) if you manually track file downloads using _paq.push(['trackLink', 'https://mydomain.com/download.pdf', 'download']) for example, note that you must use a full valid URL.


if you have more info what was the problem @Globulopolis let us know, we can add to FAQ
