### ISSUE TITLE
Visitors engagement:  "Visits by Visit Number"?

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8915]
in visitors engagement there is an intersting list "Visits by Visits Number"

For e.g. 8 different visits (with different visited pages etc.)
it counts the visits and shows "1/8" = 13% for each visit.
hmmm ... does this mean?

please see attachment
![2015-10-05_15h25_13](https://cloud.githubusercontent.com/assets/5681880/10281515/47319660-6b75-11e5-8e1c-c22a098dee1b.png)

**Comment by hpvd** [comment]
ah ok, I think I get it. It should be probably a Loyalty Report #536 
This idea is really awesome!

...but (sorry for the but...)
shouldn't it show "Number of visits of a visitor"?

The filter used to produce the table shown above was one visitor-ID.
This visitor visited the website 8 times.

So the result should be:
empty rows till
8 visits:
8 visits 1 Visitor  100% of Visitors

=> If I get it the right way (do I???)
- the headline should be modified
- the math should be corrected

**Comment by mattab** [comment]
Hi @hpvd 

When a given user visits the page 8 times, on first visit it will have Visit count = 1, on second visit it will have Visit count = 2, etc. so this works as expected. Due to the way the report is processed we cannot change this behavior.
