### ISSUE TITLE
2.15b15: HUGE selected time period not respected for graphs

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8917]
**2.15b15** and probably some versions before (it's also in the **demo**):
**selected period not respected for graphs**

e.g.
visitor/overview
visitor/engagement
referres/overview
ecommerce/overview
dashboard Visits over time widget

=> in wide main graphs of this pages and also in small graphs

screenshots taken from demo:
![2015-10-05_16h11_43](https://cloud.githubusercontent.com/assets/5681880/10282703/7a935172-6b7c-11e5-9a13-3d4fc9d195d2.png)
![2015-10-05_16h13_13](https://cloud.githubusercontent.com/assets/5681880/10282713/807e2fee-6b7c-11e5-9692-1c3e42ceb8c9.png)
![2015-10-05_16h14_10](https://cloud.githubusercontent.com/assets/5681880/10282715/83e98386-6b7c-11e5-8b25-301ad9d082a2.png)
![2015-10-05_16h14_59](https://cloud.githubusercontent.com/assets/5681880/10282718/88e0ed66-6b7c-11e5-9308-fd69164f6fa8.png)

**Comment by hpvd** [comment]
The huge question is: is it respected for data shown in tables??

**Comment by hpvd** [comment]
an other place whre the problem appears:
screenshot taken from demo
![2015-10-05_16h46_21](https://cloud.githubusercontent.com/assets/5681880/10283643/d037fb9c-6b80-11e5-8f3e-d616b36b32e7.png)

**Comment by hpvd** [comment]
we can reproduce it with different browsers in piwik demo and our own installation (2.15b15)
the STRANGE thing: in a friends installation also on 2.15b15 everything is fine with same browser types!!

**Comment by hpvd** [comment]
the mentioned friend tested demo.piwik.org with the same browser with which in his own installation everything shows fine: he could reproduce the problems in the demo
=> so it seems not to be a browser/plugin issue

**Comment by mattab** [comment]
Hello @hpvd ,

As far as i know this is not a regression and Piwik has always worked in this way. 

This duplicates this one:  Add a new feature to evolution graphs: show visits for each day in selected period #955

**Comment by gaumondp** [comment]
I can concur with Matt, even if it often bugged me it always (back in 1.11) worked that way.
