### ISSUE TITLE
Some static Image graphs are broken

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8923]
See at: http://developer.piwik.org/api-reference/reporting-api-metadata#static-image-graphs

Some of the graphs are broken with error message "Invalid API module and/or action"

This was reported in forums: http://forum.piwik.org/read.php?9,128022

This regressed during 2.15.0 beta cycle. 

Steps 
 * Check why our UI tests for static image graph didn't catch this bug
 * Fix issue

**Comment by diosmosis** [comment]
Works for me locally and on demo2, perhaps this is fixed in master?

**Comment by diosmosis** [comment]
Ok, I can reproduce now.
