### ISSUE TITLE
Remove Majestic SEO metrics from SEO widget

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8924]
Majestic SEO had to remove our API key to access some of their metrics, as someone abused the API.

We haven't yet been able to find a solution, so as a result we unfortunately need to remove the Majestic SEO metrics from our SEO widget.

**Comment by sgiehl** [comment]
Can anyone get an API key there?
We could maybe move the API key to plugin config, and display the metrics only if the admin provided an API key?
