### ISSUE TITLE
Left menu design follow up

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8940]
Follows up #8936 

 * [x] Possible regression or UI tests need to be updated: 
  * http://builds-artifacts.piwik.org/piwik/piwik/master/16015/SiteSelector_expanded
  * http://builds-artifacts.piwik.org/piwik/piwik/master/16015/SiteSelector_search_no_results
  * http://builds-artifacts.piwik.org/piwik/piwik/master/16015/SiteSelector_search_one_char

 * [x] UI tests: there is a empty white selector at top:
  * http://builds-artifacts.piwik.org/piwik/piwik/master/16015/UIIntegrationTest_admin_visitor_generator
  * http://builds-artifacts.piwik.org/piwik/piwik/master/16015/UIIntegrationTest_admin_privacy_settings

 * [x] On demo, on mobile device, selector "You are viewing Piwik demo" overwrites another one:

![overlap](https://cloud.githubusercontent.com/assets/466765/10352991/84d473b6-6daf-11e5-81cc-4f0302a14720.png)

 * [x] Bug, reproduce: open the real time map page, change the website, the language selector will appear expanded for 1 or 2 seconds and then will collapse. reproduced in Firefox. it looks like this for 1 second or so:

![selector expanded](https://cloud.githubusercontent.com/assets/466765/10353309/e358299e-6db1-11e5-970c-30a36480f3c5.png)

**Comment by mattab** [comment]
* Just tested on an iphone to click on the burger, it was quite difficult to click on the small icon. would it make sense to make the clickable area bigger, around the burger icon?

**Comment by tsteur** [comment]
> Just tested on an iphone to click on the burger, it was quite difficult to click on the small icon. would it make sense to make the clickable area bigger, around the burger icon?

That's what I mentioned recently in chat. Ideally all the icons would be bigger for mobile but that's rather an issue of improving mobile view than left menu. That's why I didn't invest even more time as it might be not as trivial.

> UI tests: there is a empty white selector at top:

The selector was there before on the right. It's the update Piwik message that is hidden by default.

**Comment by tsteur** [comment]
Language selector was a very tough one to find out but should be fixed.
