### ISSUE TITLE
UI test build is failing but builds-artifacts does not show screenshots for this build

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8944]
In this build: https://travis-ci.org/piwik/piwik/builds/84220575
* we got 4 failing UI tests in https://travis-ci.org/piwik/piwik/jobs/84220582
* we got 7 failing UI tests in https://travis-ci.org/piwik/piwik/jobs/84220583

Going to builds-artifacts for this job: http://builds-artifacts.piwik.org/piwik/piwik/master/16026/
 * Got: no screenshot listed
 * Expected to see the 11 failed UI tests screenshots

**Comment by tsteur** [comment]
I'm pretty sure this is the case when there are new test screens but no expected uploaded yet.

**Comment by diosmosis** [comment]
FYI https://github.com/piwik/ui-tests-viewer/pull/20

**Comment by mattab** [comment]
This was fixed and should not occur again, thanks for investigating
