### ISSUE TITLE
Piwik doesn't work with Firefox

### ISSUE THREAD

**Issue by ilmg-22** [piwik/piwik#8948]
bonjour,
sous firefox, dans les paramètres "about:preferences#privacy", décocher le pistage (Indiquer aux sites que je ne souhaite pas être pisté).
Valable pour les autres navigateurs (Dans "paramètres>confidentialité" pour chrome : ==> Envoyer une demande "Interdire le suivi" pendant la navigation)

Hi,
On Firefox, in about:preferences#privacy, uncheck checkbox "Tracking" (Tell sites that i do not want to be tracked).
For Chrome it's in "settings>privacy"  ==> "Send a "Do not track" request ..."

:-)

Ilmg

**Comment by tsteur** [comment]
Is it the same message in french and english? I don't really understand the issue. If you do tell Firefox or any other browser to not being tracked Piwik will most likely not track the request.

**Comment by ilmg-22** [comment]
Hi Tsteur
Yes it's same in englsih and french. But it's not a "question".

My explanation is that i've this problem and i'v found the solution with antoher issue : https://github.com/piwik/piwik/issues/8053.
Then for other browsers it's the same think. I wanted help for novice like me...and in french.

I can detele the post if necessary.

ILMG

**Comment by tsteur** [comment]
Got it now, thx! I'll close the issue. Here we usually rather report issues like bugs, feature wishes, ... so wasn't sure whether you're reporting a problem or not :) Cheers
