### ISSUE TITLE
NavBar position in 2.15.0-b16

### ISSUE THREAD

**Issue by SimonDeconde** [piwik/piwik#8950]
Hi there

Just upgraded to Beta version 2.15.0-b16 and noticed that the NavBar is not positioned correctly. I was previously on the latest stable version of Piwik and had the plugin setting "display the NavBar on the left  for widescreen" (can't remember the exact label of that option).

This has been experienced on Ubuntu 14.04 + Firefox 41.0.1 and Chromium Version 45.0.2454.101 Ubuntu 14.04 (64-bit)

I tried the following: 
- delete piwik/tmp
- clear my caches
- go in the database, trackdown the "Plugin_LeftMenu_Settings" in table ks_piwik_option and tried to change it to bool 0, but didn't help. I tried to delete that setting all together, but it didn't help either 

Is this happening to other users?

Here are some screenshots:

== Firefox ==
![selection_149](https://cloud.githubusercontent.com/assets/2490901/10374471/38b24b40-6da8-11e5-9fe5-aff5f27999f9.jpg)

== Chromium ==
![selection_150](https://cloud.githubusercontent.com/assets/2490901/10374472/38b27f48-6da8-11e5-8c43-239f7f93f420.jpg)

**Comment by mattab** [comment]
@SimonDeconde in Administration > System check, do you see any warning with "file integrity" maybe? (I'm wondering if one file was not uploaded correctly or so)

**Comment by hagor** [comment]
@mattab I am facing the same issue with 2.15.0-b17. The file integrity check shows no error.

**Comment by mattab** [comment]
@SimonDeconde @hagor 
could you try in command line to run `./console development:enable`

and then try again, does the UI look different/better?

would it be possible to email us access to your piwik (URL, login, password) by email to hello att piwik.org ?

**Comment by hagor** [comment]
@mattab I enabled the development mode but there was no change of the UI

Unfortunately I can't give you access to our system as it is placed in our Intranet without a connection to the Internet.

**Comment by hagor** [comment]
@mattab I just installed 2.15.0-b19 but here we have still the same effect

**Comment by tsteur** [comment]
Don't forget to disable development mode again via `./console development:disable`

We'd kinda need access to a system that experiences this issue. Please make sure the `LeftMenu` and `ZenMode` plugin is not enabled and ideally does no longer exist on your instance. Are you using maybe an Ad blocker or something similar?

**Comment by tsteur** [comment]
Does it work when you open http://demo.piwik.org ?

**Comment by hagor** [comment]
@tsteur yes I disabled the setting again.

Both plugins are removed from the system and do not exist anymore. 
The problem exists on a Firefox with Ad blocker as well as with a blank Internet Explorer.
http://demo.piwik.org looks fine, the menu here is where it belongs.

I contact your office, we might find another way to let you check our system.

**Comment by SimonDeconde** [comment]
Hey @mattab 

Sorry for the delay. I've emailed you my credentials to access our Piwik setup.

I can also confirm that switching to dev-mode didn't help nor did upgrading to 2.15.0-b19.

I hope this helps.

**Comment by tsteur** [comment]
Thanks a lot @SimonDeconde It's caused by a custom uploaded logo that was displayed too big as it was large. I'll fix it.

**Comment by hagor** [comment]
@tsteur well by disabling the custom logo everything is now looking good here too

**Comment by tsteur** [comment]
Thx for letting me know! I've already commited a patch that should make it work with a custom logo but need to build PHP with GD to make sure it'll work.

**Comment by SimonDeconde** [comment]
Well done guys!
