### ISSUE TITLE
Error 400 on tracking

### ISSUE THREAD

**Issue by HazeDevelopment** [piwik/piwik#8952]
Hi,

I am getting a response with error code 400 from the piwik javascript.
The image version does load, but doesn't track anything.

as for the 400 code, I only get a return with the message "Piwik is a free/libre web analytics that lets you keep control of your data."

I am running piwik version 2.14.3, and it occurs on all the websites I use piwik on.

**Comment by mattab** [comment]
Hi @HazeDevelopment 

can you try upgrade to latest beta, see if it helps? http://piwik.org/faq/how-to-update/faq_159/

**Comment by tsteur** [comment]
Updating to latest beta shouldn't help much I guess. Can you give us an example URL that is sent to the server? Please make sure your webserver etc forwards all parameters to PHP. We return a 400 in case there are no parameters for `piwik.php`, if the specified `idSite` does not exist or if for other reasons nothing was tracked. 

Are you familiar with logs etc? You could try to enable the debug tracker: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker
