### ISSUE TITLE
Make "Last seen" human readable

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#8956]
Administration => Users => User Management

The "Last seen" column is in : HH:MM:SS and reading 6340:45:23 for example, is not really human-friendly. Maybe when hours > 24 then use DD day(s):HH:MM:SS.

Another option would be to just show the date of last login? date("D M j G:i:s T Y"); ?

I don't think #8857 (Improve number formats) takes care of this one as far as I can see.

**Comment by sgiehl** [comment]
#8857 doesn't care that yet. It might be done in a later step. But I'm not sure if it will make it in 2.15

**Comment by ritvikgautam** [comment]
This would be an interesting thing to do for a beginner like me. 
Enough with using piwik, I'd be glad to contribute.

**Comment by gaumondp** [comment]
@ritvikgautam I'll do cheerleading for you. ;)

Seriously I would try the patch if you provide some.

**Comment by ritvikgautam** [comment]
Thanks! 
Could you give me a hint as to which files I should look into for this?

**Comment by sgiehl** [comment]
https://github.com/piwik/piwik/blob/master/plugins/UsersManager/Controller.php#L112-L114

**Comment by ritvikgautam** [comment]
I've created a pull request. Please have a look at #9112

**Comment by mattab** [comment]
done in https://github.com/piwik/piwik/issues/9112 - cheers @ritvikgautam
