### ISSUE TITLE
 Menu Layout problem - Piwik 2.15.0-b17 #108 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8965]
Reported in forums and in  https://github.com/piwik/piwik-log-analytics/issues/108

Menu is not properly layed out and i can't find any option to change it

![menu](https://cloud.githubusercontent.com/assets/3344044/10418992/3745eb6a-70c6-11e5-9065-125e033a3c1c.JPG)

**Comment by tsteur** [comment]
Most likely a caching problem. Maybe try to clear cache? Is an ad blocker used? @XinfinityoO 

Which browser are you using?

**Comment by XinfinityoO** [comment]
i have already cleared cache and tested on different browsers..same problem. i dont have leftmenu and  zenmode plugins installed via piwik.

just tested beta 19 ..still same problem

**Comment by tsteur** [comment]
FYI: This is possibly same problem as #8950  

@XinfinityoO are you using a custom uploaded logo? If so, it will be fixed soon

**Comment by XinfinityoO** [comment]
yes..using custom logo.

thanks

**Comment by tsteur** [comment]
Thx! This should be fixed
