### ISSUE TITLE
Create Piwik plugin which extends device-detector plugin

### ISSUE THREAD

**Issue by soheyb** [piwik/piwik#8967]
I tryed to creat a Piwik plugin based on DeviceDetection plugin There is a point that I didn't understood, and I hope that one of you can help me.

this Plugin will add some new features to the detection system.

But I have a question. How can I make it interacting with te current version of deviceDetection. Because right now I already did a module, and the module work by himself, but I would like that he just add informations to devicedetection

Thank you very much

**Comment by tsteur** [comment]
Hi @soheyb do you mind asking this question in our Plugins & Platform forum: http://forum.piwik.org/list.php?9 

Thx!
