### ISSUE TITLE
When clicking on menu entry in Admin, the graphs are hidden

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8969]
Reproduce:
 * Go to DB Stats report: https://demo.piwik.org/index.php?module=DBStats&action=index&idSite=7&period=day&date=yesterday&activated=
 * Scroll down to see a graph
 * Click on "system check" in left menu (or any other menu)
 * On click on the menu...
   * got: the graph disappeared then the page reloads
   * expected instead that the clicked menu should open, but without hiding the graphs.

See screenshot showing the hidden graph right after click (eg. 500ms)

![graph disappered](https://cloud.githubusercontent.com/assets/466765/10420548/c347bbc6-70f2-11e5-9385-28ca7ccb2618.png)

**Comment by tsteur** [comment]
I doubt this is a regression. See comment in code from 2013: 

> // TODO: this code destroys plots when a page is switched. there must be a better way of managing memory.

It is done to prevent memory leaks
