### ISSUE TITLE
Segmentation of Events

### ISSUE THREAD

**Issue by voidswitch** [piwik/piwik#8972]
We're trying to segment over events, which works, but shows no goals or even action->sites.

Our segment looks like 'eventCategory==someEventCategory;eventAction==someEventAction'. Visitors with these events have visited multiple sites, and ordered something (reached ecommerce goal), but if filtered by segment, it doesn't show any pages (actions->pages) or orders/revenue (ecommerce->overview). On the other hand, ecommerce->products has entries.

If more details are needed, feel free to ask.

**Comment by mattab** [comment]
Thanks for the report @voidswitch

**Comment by mattab** [comment]
Duplicates: https://github.com/piwik/piwik/issues/9189
