### ISSUE TITLE
Segmentation on (on entry page) leads to the transition not working.

### ISSUE THREAD

**Issue by pouyana** [piwik/piwik#8975]
Hi There,

I have the Piwik version 2.14.3 and when there is a segmentation (on the entry page) 
![piwik](https://cloud.githubusercontent.com/assets/2496169/10425475/3edad61c-70d8-11e5-9ef3-c026eb4e981d.png)
done, I can not get the transitions on entry pages and pages. Pushing transitions button leads to Piwik refreshing the document with the text (Processing segmented visitor data may take a few minutes... )

**Comment by mattab** [comment]
Hello @pouyana 

please try again with our latest beta version which should fix this issue: http://piwik.org/faq/how-to-update/faq_159/
