### ISSUE TITLE
Widget: Plugins now work for IE11

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#8978]
It seems that the Plugins detection now works (partly) also for IE11.

Todo:
- [ ] check from which IE version on it works
- [ ] check if all plugin checks work
- [ ] modify the notice at the bottom accordingly

![image](https://cloud.githubusercontent.com/assets/533017/10427639/7d6ff296-70eb-11e5-88db-dc9210f33c36.png)
![image](https://cloud.githubusercontent.com/assets/533017/10427644/827d1976-70eb-11e5-9a35-fa091fd3bde0.png)

**Comment by sgiehl** [comment]
Actually plugin detection is already done for IE >= 11

```
                // detect browser features except IE < 11 (IE 11 user agent is no longer MSIE)
                if (!((new RegExp('MSIE')).test(navigatorAlias.userAgent))) {
                    // general plugin detection
                    if (navigatorAlias.mimeTypes && navigatorAlias.mimeTypes.length) {
```

So I guess we would only need to modify the note

**Comment by mattab** [comment]
Thanks for the report @ThaDafinser 

@sgiehl maybe it would be now ok to remove the notice, since plugin detection works for most browsers?

**Comment by sgiehl** [comment]
Not sure about that. Maybe there are some intranets tracked, where IE<11 still might be used mainly?

**Comment by mattab** [comment]
@sgiehl ok, +1 to leave & modify the message
