### ISSUE TITLE
Update to b17 crashed Piwik: enableMeasurePiwikForSiteId

### ISSUE THREAD

**Issue by skywalker89** [piwik/piwik#8985]
HI, already posted to forums at piwik, but no answer

this is where I am at:

An error occurred
Variable "enableMeasurePiwikForSiteId" does not exist in "_piwikTag.twig" at line 3 

Dan

**Comment by mattab** [comment]
Hello, Please try upgrade to beta 20 which should fix it (make sureall files are uploaded properly)

**Comment by skywalker89** [comment]
HI Matt,

thx!

Is there any instructions how to do that (auto-update not working anymore)?

Thx a million

Dan

**Comment by mattab** [comment]
Hi Dan, please update manually this time. Next time the auto update should work, if not please let us know!

**Comment by skywalker89** [comment]
HI MAtt,

sorry, my bad...I couldnt check after the crash

I did as you suggested, but I was already further, and so I get this (in German

"Ihre Piwik Codebase läuft auf der alten Version 2.14.2 und wir haben erkannt, dass Ihre Piwik Datenbank bereits auf die neuere Version 2.15.0-b19 aktualisiert wurde."

BAsically it says that I now installed Piwik 2.14.2 (my bad) but since I was on the beta channel I had tried to upgrade to 2.15.0-b19 

sorry for this

so my beta upgrade crashed badly
what would y<ou do?

Thx

Dan

**Comment by skywalker89** [comment]
HI Matt,

first looked good...got the update screen

I read some compülaint then that something with "binary" might have gone wrong (Filezilla was set to "binary", when connecting to server I cannot change it to anything anymore)

then I got this

Variable "enableMeasurePiwikForSiteId" does not exist in "_piwikTag.twig" at line 3

help pls
Thx

Dan
