### ISSUE TITLE
2.15b20: Format of task's date broken

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8992]
2.15b20: Format of task's date broken
was fine some betas before...

please see attachment:

![2015-10-13_14h32_24](https://cloud.githubusercontent.com/assets/5681880/10454791/956c5606-71b7-11e5-9c95-b7ebd45b68fb.png)

**Comment by mattab** [comment]
see https://github.com/piwik/plugin-TasksTimetable/issues/3
