### ISSUE TITLE
2.15b20: Dashboard -> Menu -> Segment: site looks strange

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8993]
2.15b20: Dashboard -> Menu -> Segment: site looks strange

please see attachment
![2015-10-13_15h32_05](https://cloud.githubusercontent.com/assets/5681880/10456164/0adccd14-71c0-11e5-8f76-b6ab1efa952f.png)

browser cache is disabled

**Comment by tsteur** [comment]
It should not look like this. Can you check if the plugins `LeftMenu` and `ZenMode` were uninstalled?

Also can you maybe try to execute the command `./console cache:clear` on your Piwik server in your Piwik directory?

**Comment by tsteur** [comment]
Is http://demo.piwik.org/ shown correctly?

**Comment by hpvd** [comment]
Lefmenu and Zenmode are not visible in pluginlist

**Comment by tsteur** [comment]
Piwik Demo is pretty fast here. Is it normal that you have that "Segment" menu item? Do you mind letting me know if you have more plugins from the Marketplace installed? To find out maybe click on the Settings icon to get to Administration, then click on Marketplace in the left menu. At the bottom of each plugin it should say whether it is installed or not.

**Comment by hpvd** [comment]
thanks for the hint:
first guess was right: menu item was introduced by  Piwik Professional Services' ComparisonDashboard (v1.0.6)
disabling this one the menu item disappeared

**Comment by tsteur** [comment]
I'll test it with that plugin now, thx!

**Comment by mattab** [comment]
@hpvd fyi: the plugin ComparisonDashboard was moved as a Premium plugin now available (along with all other premium plugins) to all Piwik [PRO Enterprise](http://piwik.pro/plugins) plans subscribers. This bug may be fixed in 2.15.0-rc2 but you would need the latest ComparisonDashboard release also.
