### ISSUE TITLE
Variable "enableMeasurePiwikForSiteId" does not exist in "_piwikTag.twig" at line 3 error in b20

### ISSUE THREAD

**Issue by skywalker89** [piwik/piwik#8995]
Sorry,

the thread concerning b17 was closed too quickly

b20 shows the same error

could u help me pls?

thx

Dan

**Comment by tsteur** [comment]
Hi @skywalker89 ,

it sounds something went wrong when copying the files again. That file should not exist anymore and should not be included anywhere. Did you copy the files manually this time? Can you copy the files maybe again? You mentioned there were errors re binary transfer?

Maybe also try to execute `./console cache:clear` on the command line on the Piwik server in your Piwik directory (if possible)

**Comment by skywalker89** [comment]
Hi Tsteur

thanks a lot

bec somehow Filezilla seems to not overwrite everything, I deleted the whole piwik folder (keeping the config- file)

I tehn uploaded everything again with FZ and now I get this

It appears the composer tool is not yet installed. You can install Composer in a few easy steps:
In the piwik directory, run in the command line the following (eg. via ssh):

 curl -sS https://getcomposer.org/installer | php 

 php composer.phar install

This will initialize composer for Piwik and download libraries we use in vendor/* directory.

Then reload this page to access your analytics reports.

For more information check out this FAQ: How do I use Piwik from the Git repository?.

Note: if for some reasons you cannot install composer, instead install the latest Piwik release from builds.piwik.org.

I uploaded the whole folder... why is the composer missing?

What can I do?

Thx a million

Dan

**Comment by tsteur** [comment]
Did you copy the files from the ZIP from http://piwik.org/download/ ? You should not see this message re Composer.

**Comment by skywalker89** [comment]
HI Thomas,

thx

I downloaded it from github, I didnt even find those in piwik?

Someone helped me with using composer and it works again, but it was not pretty

So problem solved for now, but am much more cautious now to upgrade

Thx for all the help

Dan

**Comment by tsteur** [comment]
One is not really supposed to download the ZIP from Github see http://piwik.org/faq/how-to-install/faq_18271/  Instead it is always recommended to download the ZIP from our website where everything is prepared and composer is not needed. Also there are files removed that shouldn't be in a release. I'd actually recommend to install the version from the piwik.org download website.

I will close this issue as the actual issue seems to be fixed. 

Cheers

**Comment by skywalker89** [comment]
HI,

thx a lot

since the update to b17 crashed Matt suggested I install b20 

and there is no b20 on piwik.org....did I miss it? In that case it would prob have been much easier

I couldnt go back to piwik.org version bec of the changed database (at least thats what the installer said)

Thx again

Dan

**Comment by tsteur** [comment]
I'm sorry forgot to send you correct link. It's actually http://builds.piwik.org/ There you find RC1 which is the latest

**Comment by skywalker89** [comment]
ah cool, excellent..ok, if I understand you correctly these should be ready install much easier...and so I can do it myself then 

excellent support!

Thank you
