### ISSUE TITLE
Tracking API Documentation: Parameter cdt for bulk operations

### ISSUE THREAD

**Issue by Phalynx** [piwik/piwik#8998]
Hello,

according to this issue:
http://forum.piwik.org/read.php?2,129771,129829

I would welcome a change in the Tracking API Documentation (http://developer.piwik.org/api-reference/tracking-api) regarding the cdt parameter.
It is required to send the bulk entries in ascending order to have the "Time spent on page" value filled correctly.

Doing that, you could also add a note about the expected format of the cdt parameter, it can be also provided as an unix timestamp.

best wishes,
Marius

**Comment by mattab** [comment]
Hi @Phalynx thanks for the suggestion. fixed in https://github.com/piwik/developer-documentation/pull/115/files?short_path=d2cb234#diff-d2cb234790565a8f23460f35f08522d2 and in https://github.com/piwik/developer-documentation/commit/aded6cbc34440c30d4e3a21a3942b93361100dd7
