### ISSUE TITLE
2.15rc1: available plugin updates are counted & shown twice

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#8999]
all available plugin updates are always counted and shown twice
after updating one of these, every thing is fine
also in 2.15rc1

Because I see this problem since several versions, I thought there was already an issue about it, but I couldn't find it any more...

please see attachment

![2015-10-14_09h28_26](https://cloud.githubusercontent.com/assets/5681880/10479332/0d256226-7264-11e5-82e9-c333d092964b.png)

**Comment by tsteur** [comment]
I had an update yesterday and it was shown correctly. Have you seen this with other plugins apart from PerformanceInfo?

**Comment by hpvd** [comment]
yes. I'm not sure if this is for all but a least for most.

**Comment by hpvd** [comment]
ah I found the old one I have started:
https://github.com/piwik/piwik/issues/6737

**Comment by tsteur** [comment]
Thx! Closing this one as a duplicate
