### ISSUE TITLE
Plugins update: improve database upgrade page

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#9003]
![image](https://cloud.githubusercontent.com/assets/533017/10507567/af1f7a90-7321-11e5-87d2-3aa81e9e5c1d.png)

For the core there is a different view, if i'm not wrong, where the CLI command is better shown.

I think the same layout would be great (i didnt noticed the command first)

**Comment by mattab** [comment]
Thanks for the report @ThaDafinser - we will try to make the design consistent as you suggested!

**Comment by ThaDafinser** [comment]
Seems to be fixed
