### ISSUE TITLE
White icons in Manage Goals

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9005]
In Manage Goals, white icons. Expected: dark icons.

![white icons](https://cloud.githubusercontent.com/assets/466765/10508986/c1efd1c8-7386-11e5-9312-81587924e763.png)

Our screenshot tests should have maybe caught this bug? or maybe it's caused by another plugin

**Comment by tsteur** [comment]
Cannot reproduce this one. Maybe caused by another plugin?

**Comment by quba** [comment]
You can reproduce this on demo2

**Comment by tsteur** [comment]
Yes, but must be still caused by a plugin. Don't wanna disable any plugins there to find out. Leaving this to @mattab as I'm not aware of any possible side effects

**Comment by mattab** [comment]
Fyi: this is caused by WhiteLabel plugin https://github.com/PiwikPRO/plugin-WhiteLabel/blob/master/Config.php#L170-L176 - the " Button Text Color " is applied to icons but this color shouldn't  apply to icons

**Comment by tsteur** [comment]
Shall we move the issue to the whitelabel plugin then?
