### ISSUE TITLE
Icons placed wrong in multi line notifications 

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#9011]
When a notification has many lines of text, the notification icon appears on the left in the middle of the notification. It would look better (IMO) at the top left instead of the middle left.

![multiline_notification](https://cloud.githubusercontent.com/assets/125140/10516073/55ba4c70-730b-11e5-87dc-116070be5354.png)

**Comment by tsteur** [comment]
Asked for the same here but think it was on purpose: https://github.com/piwik/piwik/pull/8488#issuecomment-132520254

**Comment by mattab** [comment]
it was on purpose, I would vote for `wont fix` as I think it looks alright?

**Comment by diosmosis** [comment]
Looks weird to me.

**Comment by tsteur** [comment]
Looks weird to me too
