### ISSUE TITLE
Clicking on currently loaded left menu item when current URL is full angular hash path + query, destroys graphs

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#9018]
As title.

To reproduce:

1. Go to http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/?module=VisitsSummary&action=index&idSite=7&period=day&date=yesterday
  Note that the URL contains `#/?` which does not normally happen since menu URLs are defined as `#...` or `#?...`.

2. Click on `Visitors > Overview`.

The result is:

![evolution_missing](https://cloud.githubusercontent.com/assets/125140/10531245/60de4b5c-7364-11e5-83eb-e9376ff4308c.png)

## Cause

This is caused by https://github.com/piwik/piwik/blob/master/plugins/CoreHome/javascripts/menu.js#L24.

When the hash is the same as what is loaded by angular, the browser does nothing. But the event above, triggers this event handler: https://github.com/piwik/piwik/blob/master/plugins/CoreVisualizations/javascripts/jqplot.js#L388 which destroys all visible plots.

**Comment by mattab** [comment]
Ideally, clicking on the current sub-menu, will reload and display the same report again. 

This was implemented in 3.0.0 in https://github.com/piwik/piwik/issues/8319 and would be nice to have in 2.15.0

**Comment by mattab** [comment]
>Note that the URL contains #/? which does not normally happen since menu URLs are defined as #... or #?....

This bug only occurs in this case, how did you reach this case via the UI?

Or did you manually change the URL?

in either case, maybe this is not a "Must fix" if user cannot reach this state 'naturally'. what do you think?

**Comment by mattab** [comment]
>Note that the URL contains #/? which does not normally happen since menu URLs are defined as #... or #?....

This bug only occurs in this case, how did you reach this case via the UI?

Or did you manually change the URL?

in second case, maybe this is not a "Must fix" if user cannot reach this state 'naturally'. what do you think?

**Comment by diosmosis** [comment]
> Or did you manually change the URL?

Manually changed the URL. Only reason it doesn't appear is because menu.twig sets URLs to `#?...` or `#...` which are not correct angular URLs. Angular will change this to the correct URL. So if a user copies & shares the correct URL, then a user can be affected by this issue.

> in second case, maybe this is not a "Must fix" if user cannot reach this state 'naturally'. what do you think?

I fixed it in a PR already.

**Comment by mattab** [comment]
Which PR was it @diosmosis ? issue can be reproduced on demo2:

![no graph](https://cloud.githubusercontent.com/assets/466765/10541074/93f3d28a-746a-11e5-80b3-04128e46b498.png)

**Comment by diosmosis** [comment]
I cannot reproduce on demo2, do you have steps to reproduce?

**Comment by mattab** [comment]
* go to [demo2](http://demo2.piwik.org/)
* wait for a widget with graph to render in the dashboard
* click on "dashboard" main menu link
* got: graph is now hidden and dashboard didn't reload
* expected: graph is only hidden when the whole page is reloaded

**Comment by diosmosis** [comment]
Different bug, but same effect.
