### ISSUE TITLE
CURL response returns failed

### ISSUE THREAD

**Issue by nandhinicomforters** [piwik/piwik#9021]
if  i give the url seperately in browser the events are tracked, but if in CURL response it is returned as "malformed url", please guide to overcome this issue

**Comment by sgiehl** [comment]
Sorry, you might need to give more details in order to get an useful answer. Maybe your CURL settings are not correct or incomplete...
Btw. please use our forums for questions: http://forum.piwik.org

**Comment by nandhinicomforters** [comment]
on appending "http:" before the url sent in CURL , it worked!
