### ISSUE TITLE
Jumping effect in Dashboard

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9022]
eg on demo.piwik.org when being logged in and when using eg the resolution of a MacBook Pro (1280x800): 

First it looks like this:
![image](https://cloud.githubusercontent.com/assets/273120/10534776/bad9e49a-73dc-11e5-80df-6d264abc895b.png)

Hovering widget looks like this:
![image](https://cloud.githubusercontent.com/assets/273120/10534800/f4202dea-73dc-11e5-80c8-3472ef352a6f.png)

Hover the widget header shows why:

![image](https://cloud.githubusercontent.com/assets/273120/10534827/2371ca2c-73dd-11e5-9824-141ae10d4a43.png)

Same applies when hovering Visitors in Real Time etc. So whenever one wants to move the mouse into the real time widget to click on something the whole content moves down

**Comment by mattab** [comment]
@tsteur @sgiehl do you have some thoughts how this one could be solved or whether it's do-able at all?

**Comment by tsteur** [comment]
We could show the icons only when hovering the header. Currently it seems like it does `display:block, visibility:hidden` on widget hover and `display:block, visibility:visible` on title hover. Idea would be to do  `display:none` on widget hover or in general and only `display:block` when hovering the title. 

Not sure if those are actually the style but looking at the screenshot this is how it looks. Might be an easy fix
