### ISSUE TITLE
Include the current site in the web site selector drop-down

### ISSUE THREAD

**Issue by raj45** [piwik/piwik#9025]
It is bad UI-design to not include the current site in the drop-down, which it is in all other GUI's.

Proposal:
![show-current-website](https://cloud.githubusercontent.com/assets/7046001/10536746/802157f0-73ed-11e5-8e65-e616c711bea9.png)

Also, it is not entirely clear in what order the web sites appear in, shouldn't they be sorted alphabetically?

**Comment by mattab** [comment]
Thanks for the suggestion :+1:

**Comment by raj45** [comment]
You're welcome :-)

About the sorting issue - should it be alphabetically, by popularity, or something else? Perhaps it could be a setting the user can configure?

**Comment by mattab** [comment]
currently it seems to be sorted by Idsite

**Comment by raj45** [comment]
It would probably make more sense to sort it alphabetically.

**Comment by tsteur** [comment]
Re sorting: We sort by name client side but as we only request a portion of all sites (when having many websites) it depends what the API method returns on the server side. They are possibly kinda ordered by ID there as mentioned. Maybe ideally we would sort them by number of visits or actions or by how often a certain website was used. For sorting maybe create new issue ideally :)

**Comment by raj45** [comment]
Sure @tsteur - I have created an issue here: #9332.
