### ISSUE TITLE
segment datas are wrong/inexistant because json decoding is missing

### ISSUE THREAD

**Issue by ArnY** [piwik/piwik#9027]
I explained my problem on the forum: http://forum.piwik.org/read.php?2,129751
in short: 
Segment datas are wrong or empty.
Custom variables are declared to the tracker like this:
```
_paq.push(['setCustomVariable', 1,"Site","SET",'page']);
_paq.push(['setCustomVariable', 2,"Redacteur","xxxxx",'page']);
_paq.push(['setCustomVariable', 3,"RubriqueNiveau1","SET_FR1",'page']);
_paq.push(['setCustomVariable', 4,"RubriqueCourante","SET_FR1",'page']);
```
in core/Tracker/Request.php the customVariable values are read out of Common::getRequestVar, but for some reason those are still json encoded instead of being an array as expected: 
```
["Site", "SET"]
["Redacteur","xxxxx"]
["RubriqueNiveau1","SET_FR1"]
[""RubriqueCourante","SET_FR1"]
```
looks like there's a missing json_decode() in the foreach ($customVar as $id => $keyValue) loop.

I could commit a patch but I'm not sure of the implications since I haven't found any other bug reports on the subjet it must still be working for some people...

**Comment by tsteur** [comment]
Hi @ArnY thanks for investigating so much already and looking so deep into it.

In general I can say that custom variables work quite well here. So it might be related to a specific browser or server. 

Which browser are you using? Do you have some details about the server? On which OS is it running and what's the Piwik version? 

There's a `JSON decode` which should convert that string that you mentioned in the forum to an array.

Can you maybe try if it still occurs if you track only one custom var? eg `_paq.push(['setCustomVariable', 1,"Site","SET",'page'])`

**Comment by ArnY** [comment]
Since I noticed the bug on our production server on a segment which 
averaged around ~30,000 monthly before the bug and ~230 after (but all 
segments are impacted), if this was a browser related bug, that would 
mean that 99.993% of the browsers suddendly handled the javascript wrong.

I removed my fix ($keyValue=json_decode($keyValue)) and only left one 
custom variable. The problem still occurs:

DEBUG Actions[2015-10-17 09:55:04] [979f0] Invalid custom variables 
detected (id=1)

I agree there's something strange with the fact that a very small 
percentage of the visits are still being accounted...





On 10/17/2015 08:50 AM, Thomas Steur wrote:
> Hi @ArnY <https://github.com/ArnY> thanks for investigating so much
> already and looking so deep into it.
>
> In general I can say that custom variables work quite well here. So it
> might be related to a specific browser or server.
>
> Which browser are you using? Do you have some details about the server?
> On which OS is it running and what's the Piwik version?
>
> There's a |JSON decode| which should convert that string that you
> mentioned in the forum to an array.
>
> Can you maybe try if it still occurs if you track only one custom var?
> eg |_paq.push(['setCustomVariable', 1,"Site","SET",'page'])|
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/piwik/piwik/issues/9027#issuecomment-148891498>.
>


-- 
Arnaud Abélard
jabber: arnaud.abelard@univ-nantes.fr / twitter: ArnY
Administrateur Système
DSI Université de Nantes
-

**Comment by cbleek** [comment]
I can confirm the problem on ubuntu 14.4, php-5.5.9.
If can reproduce it with piwik 2.13.0 and 2.15.0rc3

**Comment by cbleek** [comment]
One more intresting thing.

If I set the value of my custom variable to "m.jobsintown.de", the value is tracked. Means, the type of $keyValue in https://github.com/piwik/piwik/blob/master/core/Tracker/Request.php#L553 is an array.

<pre>_paq.push(['setCustomVariable', 1,"Domain","m.jobsintown.de",'visit']);</pre>

if I set the value to "www.jobsintown.de" $keyValues is a json encoded string.

<pre>_paq.push(['setCustomVariable', 1,"Domain","www.jobsintown.de",'visit']);</pre>

**Comment by tsteur** [comment]
That's very weird. I tried to reproduce but couldn't. 

I just had a look at the website and it is actually sent differently to Piwik:

`_cvar:{"1":"[\"Domain\", \"www.jobsintown.de\"]"}`

vs

`{"1":["Domain","m.jobsintown.de"]}`

After debugging further I noticed that you are using Prototype 1.6.0.3 which is known to be buggy re JSON. Please update Prototype to a more recent version.

See eg https://github.com/piwik/piwik/issues/2165  or https://github.com/piwik/piwik/issues/7945#issuecomment-114312376

**Comment by cbleek** [comment]
After upgrading prototype, the problem was fixed. 

Thank you very much!

**Comment by ArnY** [comment]
Spot on! We used prototype.js 1.6.0.3 too but I actually upgraded it a few days ago for a completely unrelated reason! I had slightly modified Request.php to send to syslog user-agents of browsers encountering the problem and upgrading prototype.js did fix most of the problem, but even after the upgrade I'm still getting non decoded json arrays for each custom variables (about 1% of the visits). Most of them are using webkit browsers: Chrome and Safari. Might not be important, I just wanted to mention those, just in case.

Thanks anyway!

**Comment by tsteur** [comment]
Those browsers probably still use the cached prototype.js

**Comment by ArnY** [comment]
On 10/27/2015 07:27 PM, Thomas Steur wrote:
> Those browsers probably still use the cached prototype.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/piwik/piwik/issues/9027#issuecomment-151601065>.
>

My thought too, i'll keep an eye on it.
