### ISSUE TITLE
Compare Evolution field on the All Websites dashboard page to same time yesterday

### ISSUE THREAD

**Issue by raj45** [piwik/piwik#9028]
The "Evolution" field on "All Websites dashboard" page should be compared to the same time yesterday, otherwise the number only makes sense when the time is 23.59 :-)

![evolution-field](https://cloud.githubusercontent.com/assets/7046001/10537598/33e663a2-73f3-11e5-8316-7d26418f00ec.png)

**Comment by mattab** [comment]
Thanks for the report, please follow this bug report https://github.com/piwik/piwik/issues/6784
