### ISSUE TITLE
Optional display of Revenue field

### ISSUE THREAD

**Issue by raj45** [piwik/piwik#9029]
It should be possible to turn off the Revenue field completely, if you don't use it anyway.

![selection_001](https://cloud.githubusercontent.com/assets/7046001/10537661/9c38ba36-73f3-11e5-8805-d434813aee9e.png)

**Comment by tsteur** [comment]
Thx for reporting this issue. I'll close it as a duplicate of #2390 . Please follow that issue (there are also a couple of similar issues referenced)

**Comment by raj45** [comment]
Thanks, I'll follow it over there.
