### ISSUE TITLE
When a given menu is expended, remove cursor:pointer on the main menu, as there is no click event 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9030]
reproduce:
 * Click on "Actions" menu
 * The submenu expands
 * Hover on "Actions" main menu 
  * Got:` cursor:pointer`
  * Expected: `cursor:none` because the menu is already expanded and so it is not "clickable"

**Comment by quba** [comment]
Maybe would be easier just to collapse after clicking once again?

**Comment by tsteur** [comment]
collapsing should be easier and would more follow current behaviour, would be more predictable for users

**Comment by quba** [comment]
:+1:

**Comment by mattab** [comment]
:+1:
