### ISSUE TITLE
Fatal error after updating

### ISSUE THREAD

**Issue by nelsonmonteiro00** [piwik/piwik#9042]
I was updating my piwik and a few minutes into the intalation I was gaven an error and now everytime I open my page I'm given this:" Fatal error: Class 'ComposerAutoloaderInite8ad85ba0ba0c32158ef4e39d8e8f85f' not found in /home/geralucros/public_html/estat/vendor/autoload.php on line 7"
Can anyone help me?

**Comment by mattab** [comment]
How did you update your Piwik?

maybe try the latest RC version from:  http://builds.piwik.org/

**Comment by tsteur** [comment]
Did you update via Piwik user interface or GIT?

**Comment by nelsonmonteiro00** [comment]
I updated via the interface

**Comment by tsteur** [comment]
It sounds like a file was not written correctly during the update. Can you try to update manually? See  https://piwik.org/docs/update/#the-manual-three-step-update
