### ISSUE TITLE
Let Live.getVisitorProfile http API return more than 10 visits (new parameter &limitVisits=X)

### ISSUE THREAD

**Issue by foxxx** [piwik/piwik#9046]
index.php?module=API&method=Live.getVisitorProfile&idSite=8&visitorId=XXXXXX&format=xml&token_auth=XXXXXX

if you add &format_limit=50 you still only get the last 10 visits. Unable to return more. We need to be able to get more data from that query.

**Comment by tsteur** [comment]
Hi @foxxx, it should be `filter_limit`, not `format_limit`

**Comment by foxxx** [comment]
index.php?module=API&method=Live.getVisitorProfile&idSite=8&visitorId=XXX&format=xml&token_auth=XX&filter_limit=50

still only 10 results.

**Comment by tsteur** [comment]
Thx! Tried to reproduce and this is indeed a bug. The standard limit feature fails to apply the limit as the visits are returned under the key `lastVisits` and not in root element

**Comment by sherryyuu** [comment]
Hi! I met the same problem and I need Live.getVisitorProfile to return all visits. I'm wondering if there is a solution for this problem now. Thank you for your help and I'm looking forward to your reply!
