### ISSUE TITLE
Number formatted as % but it is not a percentage

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9049]
can be seen @ http://demo-anonymous.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?module=Events&action=index&idSite=1&period=year&date=today

The Total Event value is a numeric value. It is sometimes, formatted as %:

![bug in number formatting](https://cloud.githubusercontent.com/assets/466765/10571816/2885961e-769f-11e5-9710-307b2dce53de.png)

**Comment by mattab** [comment]
Hi @sgiehl maybe you could help / have an idea about  this one?

**Comment by sgiehl** [comment]
Maybe that kind of a casting issue. Would you mind testing a small code change on demo? I'm not able to reproduce that locally:

https://github.com/piwik/piwik/blob/master/core/Twig.php#L304
Try to switch the both compared variables or try:
`if ((string)$string != trim($string, '%')) {`
