### ISSUE TITLE
Incorrect time value in visitor_localtime

### ISSUE THREAD

**Issue by bakhesh** [piwik/piwik#9052]
I have had an issue copying my data from MySQL into MSSQL. Every time I tried to copy data from the piwik_log_visit table, I received the following error....

OLE DB provider "MSDASQL" for linked server "piwik_Instance1" returned message "[MySQL][ODBC 5.3(a) Driver][mysqld-5.5.41-0ubuntu0.14.04.1]Invalid time(hours) format. Use interval types instead".
Msg 7330, Level 16, State 2, Line 1
Cannot fetch a row from OLE DB provider "MSDASQL" for linked server "piwik_Instance1".

I eventually tracked this down to a single record, which had the visitor_localtime set as '252:49:33'. I am unsure how this value was originally logged

![piwikscreen](https://cloud.githubusercontent.com/assets/15192455/10573595/6727c9b6-7648-11e5-96c4-ff0debe92208.PNG)

I'm afraid I don't have any more details, although I will try to answer any questions

**Comment by mattab** [comment]
Thanks for the report @bakhesh !
