### ISSUE TITLE
Blank Dashboard

### ISSUE THREAD

**Issue by andoruB** [piwik/piwik#9057]
So, after some inactivity in using Piwik, I came back to it to check the analytics for a site of mine, and I was surprised to see a blank dashboard, with no apparent errors. I searched around for similar issues, but all I found as solutions was to clear the cache under /piwik/tmp/ and to update Piwik to the latest version, which I did both, and it still didn't fix the issue. I took a look at the error console (under FF's developer tools) and all I found was this JS error:
```
ReferenceError: $ is not defined
```

Piwik version: 2.14.3
Firefox Version: 41.0.2

I haven't done anything unusual to reproduce this issue except to log in and go to Piwik's Dashboard. Other areas of Piwik, like Administration, Help and Personal Settings seem to display properly, this problem being prevalent only under Dashboard and All Websites.

**Comment by mattab** [comment]
Hello

Please try upgrade to latest PIwik: http://piwik.org/faq/how-to-update/faq_159/

My guess is that you're using an adblocker or some other browser extension blocking some javascript.
