### ISSUE TITLE
NumberFormatter architecture is flawed

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#9061]
The current NumberFormatter class is not built into the existing metrics formatting system in core. Instead, it essentially re-formats values, trying to guess the meaning of a value, after the meaning is removed or transformed. This approach is prone to error and adds an unnecessary extra layer of logic.

Instead, the logic in NumberFormatter should be included in the Html MetricsFormatter (if it is only for UI), or included in the MetricsFormatter base. If neither of these work for some reason, a new base class can be used. But the MetricsFormatter base should be the only way to format values for display and no method should try to guess how to format a value. Users should explicitly specify how they want values to be formatted.

This technical debt should be removed before the next major release.

**Comment by sgiehl** [comment]
:+1: 
the reason I have build it that way, is that it shouldn't affect API responses for 2.15
For 3.0 we should move all formatting to the MetricsFormatter and remove it from the frontend.
Also we should mark all numeric, percentage and money columns, so they can automatically be formatted or something like that.

**Comment by diosmosis** [comment]
> Also we should mark all numeric, percentage and money columns, so they can automatically be formatted or something like that.

For processed metrics, this is done by each ProcessedMetric subclass (the `format()` method is passed a a MetricsFormatter). Aggregated metrics aren't handled this way at the moment, but they should be.

**Comment by mattab** [comment]
this will get done over time :+1:  but we probably don't need to keep track of this tech debt as issue
