### ISSUE TITLE
"Check for updates" does not check for plugins updates on Marketplace

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9065]
At this moment on demo.piwik.org we use version 0.1.1 of plugin `AnonymousPiwikUsageMeasurement`. A new version 0.1.2 was released few minutes ago. After clicking `Check for updates` in the top right selector in admin area, the new plugin update is still not displayed as available. 

Expected behavior: `Check for updates` button should reset the cache for Piwik core version but also all plugins installed from the marketplace.

**Comment by mattab** [comment]
it's possible that this occured because the plugin was disabled. Maybe the plugin update check does not check for disabled plugins?

**Comment by tsteur** [comment]
I had a look and we usually do invalidate the marketplace cache when checking for updates.

Possibly it's because it is disabled then

**Comment by tsteur** [comment]
I can confirm it was because the plugin was disabled see PR in #9235
