### ISSUE TITLE
Two different errors for different non-existing idSites

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9066]
Two different "no website" errors are thrown for different idSites. I discussed this with @tsteur and his idea is that for one of these there might be some data in log tables, and this could be the cause.

Piwik 2.14.3

![screen shot 2015-10-20 at 15 54 14](https://cloud.githubusercontent.com/assets/11424829/10609701/2b20a692-7745-11e5-8f3e-1b99d0d490cc.png)
![screen shot 2015-10-20 at 15 54 09](https://cloud.githubusercontent.com/assets/11424829/10609700/2b1de312-7745-11e5-9c6a-c3c9d64e6ede.png)

Method that thrown this: index.php?module=CoreHome&action=index&idSite=191610&period=month&date=2015-09-30#/module=Actions&action=menuGetPageUrls&idSite=191610&period=month&date=2015-09-30

**Comment by mattab** [comment]
Thanks for the report. I think it's fine to have two error messages... it shouldn't cause a problem :-)
