### ISSUE TITLE
Add Ability to Export ALL Records

### ISSUE THREAD

**Issue by cfuser** [piwik/piwik#9068]
When exporting data, the export feature should automatically export ALL records and not be limited to the filtered record count. If that is not a viable option, then "All" (&filter_limit=-1) should be available in each record count selector without manual intervention from the user. Personally, I would like the ability to have all records exported by default and the ability to add additional filter increments including "All" in the administrator.

**Comment by mattab** [comment]
Thanks for the suggestion @cfuser 

A simple solution to this issue will be to add `all` in the Row Count selector (after `500`). It will let you export all data after having it displayed in the UI and clicking export.

**Comment by mattab** [comment]
PR #9281
