### ISSUE TITLE
Cron fails if mysql is not enabled globally

### ISSUE THREAD

**Issue by rfnx** [piwik/piwik#9074]
Hello,

I'm trying to setup cron but I'm facing a strange problem. On my server, pdo_mysql.so is not enabled globally, I enable it in the php engine (with uWSGI) only for websites that need it. Some webapps, like piwik or wordpress, need cron to work well and that's why I have to add in the command line each extension I need.

Here is the command line I want to use : 
```
php -d extension=pdo_mysql.so -d extension=gd.so -d extension=iconv.so -d extension=openssl.so -f /path/to/piwik/console core:archive --url=https://analytics.mydomain.com/
```

But I get this error :
```
Empty or invalid response 'Error in Piwik: The mysql driver is not currently installed The mysql driver is not currently installed ' for website id 1, Time elapsed: 0.264s, skipping
```

It's strange because this method works perfectly with my other webapps. Also, why is there a difference between enabling mysql in php.ini or in the command line ?

**Comment by rfnx** [comment]
Ok I really don't know why but after many tries, suddenly it works now... The only thing I did was (like I said in the first post) : enable pdo_mysql.so globally, run the cron (it works) then disable again pdo_mysql.so globally and put it back in the command line. It shouldn't work, but it is.

Maybe the cron has to be launched once with pdo_mysql.so enabled globally ?

**Comment by rfnx** [comment]
The problem appeared again after one or two hours. So I did some tests :

-Change adapter to mysqli : same error.
-Update to 2.15 : error fixed for one or two hours, then same issue.

It's very strange, nothing changes between the cron, except the error.

**Comment by tsteur** [comment]
Maybe this is rather something for our forum http://forum.piwik.org/ ? It seems to be some kind of server configuration problem

**Comment by rfnx** [comment]
I'm not sure it's a server configuration problem but for the moment I enabled mysql globally. Maybe the cron call php and doesn't use the command line arguments I use ? I tried to look at the source code but I don't have the time now, I'll do it later.

**Comment by tsteur** [comment]
The database connection shouldn't depend on the arguments you use. Can you maybe paste the command that you use to run the cron? Is only the cron experiencing such issues or also the Piwik UI? Do they both run as the same user?

**Comment by mattab** [comment]
> Maybe the cron call php and doesn't use the command line arguments I use ? 

I think issue #9258 forward PHP CLI parameters to CLI subrequests, will fix this as well. marking as duplicate

**Comment by rfnx** [comment]
@mattab Thanks :)

Sorry @tsteur, I forgot to answer you. I had other things to do so as a workaround (but not a fix) I enabled mysql globally. I'm now waiting for the new version to try and see if it is fixed.
