### ISSUE TITLE
Variable "enableMeasurePiwikForSiteId" does not exist in "_piwikTag.twig" at line 3

### ISSUE THREAD

**Issue by ThomasKujawa** [piwik/piwik#9079]
Autoupdate to 2.15.0

Variable "enableMeasurePiwikForSiteId" does not exist in "_piwikTag.twig" at line 3

**Comment by ThomasKujawa** [comment]
new download from https://piwik.org/download/

upload via filezilla

and https://piwik.org/docs/update/

but always the same error

Variable "enableMeasurePiwikForSiteId" does not exist in "_piwikTag.twig" at line 3

**Comment by bsiege** [comment]
My solution was: ./console plugin:deactivate Zeitgeist

**Comment by buzanits** [comment]
Thanks, bsiege. This also worked for me. It is more a workaround than a solution, but it works!

**Comment by ThomasKujawa** [comment]
???

Can you help me, what to do?

I have access with Filezilla and WinScp (putty).

**Comment by buzanits** [comment]
This workaround only works if you have shell access (SSH). Can you use putty to login in your server? If you can, go to your piwik installation and type in the command bsiege wrote here.

**Comment by ThomasKujawa** [comment]
./console: No such file or directory

:-(

**Comment by sgiehl** [comment]
Try removing the directory ./plugins/Zeitgeist if it exists.
That one should have been removed with 2.4.0 update. If it still exists maybe Piwik wasn't able to remove due to access rights...

**Comment by ThomasKujawa** [comment]
damn.

there is no  zeitgeist - directory

**Comment by tsteur** [comment]
It sounds like a file was not overwritten correctly. I recommend to update Piwik manually see https://piwik.org/docs/update/#the-manual-three-step-update

You could maybe also try to update the file `plugins/Morpheus/templates/layout.twig` with the content of https://raw.githubusercontent.com/piwik/piwik/2.15.0/plugins/Morpheus/templates/layout.twig . If this doesn't fix it you might have a custom theme installed that is still using this file.

**Comment by julia-r** [comment]
Same problem here, also no Zeitgeist plugin...

**Comment by tsteur** [comment]
If you experience this issue please manually copy over all files see https://github.com/piwik/piwik/issues/9079#issuecomment-151256131 .

**Comment by ThomasKujawa** [comment]
After deleting all files and copy again.

Warnung
Folgende Plugins sind nicht kompatibel mit Piwik 2.15.0 und konnten nicht geladen werden: Feedannotation, ReferrersManager, SecurityInfo, TreemapVisualization, Zeitgeist
Sie können diese Plugins auf der Plugins verwalten Seite aktualisieren oder deinstallieren.

**Comment by tsteur** [comment]
> The new files should overwrite all the old files with the same names.

Deleting the files was not needed, only overwriting existing ones in this case. Maybe it should be mentioned a bit more clear in the FAQ @mattab ? 

You can download these plugins again by going to `Administration` => `Marketplace`. In order to download them, you might have to remove the plugin names from `config/config.ini.php` file. The plugins might be mentioned in `Plugins[] = ...`. Removing them from `PluginsInstalled[]` should not be needed and is probably better to leave them there.

**Comment by mattab** [comment]
Changed the update guide to: `If you upload these files using FTP to your Piwik server, please make sure all files are transferred in binary mode. It is not needed to delete your old Piwik files before transferring the new ones. The new files should overwrite all the old files with the same names. ` in https://piwik.org/docs/update/#the-manual-three-step-update

**Comment by ThomasKujawa** [comment]
thanks to all. problem solved.
