### ISSUE TITLE
Logviewer plugin complain about  No entry or class found for 'log.file.filename'

### ISSUE THREAD

**Issue by wumingzhang** [piwik/piwik#9081]
Any idea why? I've enabled logs as 

[log]
; Possible values are "screen" (default value), "file" and "database" (logs to tables logger_*)
log_writers[] = file
; Possible values are ERROR, WARN, INFO, DEBUG
log_level = WARN
; if configured to log to file, log entries will be written to this file
logger_file_path = tmp/logs/piwik.log

But nothing has been recorded to piwik.log

**Comment by tsteur** [comment]
Try to set `log_level = DEBUG` and see if it then logs something over time. Maybe there was just no warning/error in the meantime?

**Comment by mattab** [comment]
@wumingzhang could you try the suggestion above?
