### ISSUE TITLE
Server overdue ?

### ISSUE THREAD

**Issue by ShaoKhan** [piwik/piwik#9084]
I get this error message:
"Oops… während der Anfrage ist ein Problem aufgetreten. Möglicherweise war der Server temporär überlastet, oder ..."

If i refresh the Widgets is all fine.
My server is idling around.

Whats wrong ?

**Comment by sgiehl** [comment]
When new reports are being calculated sometimes a server timeout occurs as it takes to long to finish.
In that case the mentioned message is displayed.
You could set up archiving using a cron job. See http://piwik.org/docs/setup-auto-archiving/
