### ISSUE TITLE
2.15.0 search overlaps menu and gettext does not get text

### ISSUE THREAD

**Issue by SR-mkuhn** [piwik/piwik#9085]
After updating to 2.15.0 from 2.14.5 a glitch in the search field renders the menu unusable.
Edit: search field is unusable too.
![Search field glitch](http://i.imgur.com/rZpNXT6.png)

~~EDIT: It seems it affects just one user by now.~~

**Comment by sgiehl** [comment]
have you tried to clean the tmp folder of piwik?

**Comment by SR-mkuhn** [comment]
yes. problem persists.

**Comment by ThaDafinser** [comment]
@SR-mkuhn i had that too. You downloaded maybe from git? And didnt include vendors? :)

**Comment by SR-mkuhn** [comment]
No, downloaded from http://builds.piwik.org/piwik.zip
md5sum is a6483db15f4fbf4907360f2fffe22768.
And followed standard update procedure.

**Comment by SR-mkuhn** [comment]
Ah i forgot about cleaning the nginx fcgicache. Sorry :-)

**Comment by SR-mkuhn** [comment]
And it reappeared.

**Comment by SR-mkuhn** [comment]
Is this maybe a problem with ZenMode?

**Comment by sgiehl** [comment]
ZenMode has been remove with 2.15. If this plugin still exists on your installation. simply remove it.
