### ISSUE TITLE
Attempting to upgrade to 2.15.0 throws curl SSL error

### ISSUE THREAD

**Issue by stuartlangridge** [piwik/piwik#9086]
Piwiki 2.14.3 has alerted me that 2.15.0 is available to download; attempting to upgrade automatically displays this error:

    Downloading the latest Piwik version over secure HTTPS connection did not succeed, because of the following error:
    curl_exec: SSL: certificate subject name &#039;*.alwaysdata.net&#039; does not match target host name &#039;builds.piwik.org&#039;. Hostname requested was: builds.piwik.org

Firstly and least importantly, it's improperly escaped. More importantly, this stops the upgrade from working. It is possible that the version of curl on my host doesn't have a correct certificate or is old, but I can't fix that; that's the shared hosting I use. I could probably avoid this problem by downloading over HTTP, I suspect.

**Comment by ThaDafinser** [comment]
@stuartlangridge do you use PHP 5.6?

In PHP 5.6 OpenSSL received a lot of "default improvements" regarding security: http://php.net/manual/en/migration56.openssl.php

**Comment by stuartlangridge** [comment]
Nope. 5.3.28 is what my host is currently on, according to `phpinfo()`.

**Comment by mattab** [comment]
Thanks for the report!

>  I could probably avoid this problem by downloading over HTTP, I suspect.

:+1: 

Since there is a workaround via HTTP, and this should be fixed in modern PHP, we can't do much in Piwik.
