### ISSUE TITLE
Half of the dashboard manager dropdown is cut off now due to it's placement in top controls

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#9100]
See:

![dashmanager](https://cloud.githubusercontent.com/assets/125140/10747283/9191c008-7c10-11e5-8c1f-db45dca6f78f.png)

Not sure what the best way to fix this is. Could display the dropdown to the left so part of it isn't out of the viewport.

**Comment by tsteur** [comment]
It's not really a bug as it is still usable. It's more a usability issue. To change this a month ago I suggested to implement the selectors like all selectors / drop down on other sites work:

![image](https://cloud.githubusercontent.com/assets/273120/10747527/1071555a-7cbb-11e5-88eb-e13cf001b705.png)

Basically the opened dropdown is a bit separated from the button, it can be also next to each other but they are independent. This also allows to make the button actually responsive and to get rid of `position:absolute` in top control button bar where we always have to recalculate the left position and will fix some other issues where eg the content might be pushed down by an opened dropdown etc.

If you search for date selectors or dropdowns one will notice that they pretty much all work like this for a good reason. Once the dropdown is separated from the actual button we can move the drop down further to the left to make sure all the content is visible (if the screen is wide enough)

**Comment by thetrial** [comment]
Enhancement?! On a small laptop the screen is not wide enough. So I would await that this changes the behaviour and e.g. lets open the stuff the other direction. With the old design these problems did not occur.
