### ISSUE TITLE
2.15.0 installation hangs

### ISSUE THREAD

**Issue by peakpeak-github** [piwik/piwik#9102]
Uploaded the files through wget a third time. Chmod config directory to 777. Started install. Clicking Next button: First one minute of nothing happens, then a blank screen forever. Firebug Report: 

 http://example.com/piwik/index.php?action=systemCheck 503 Service Unavailable 

 Rest of my site works ok as usual ....

**Comment by mattab** [comment]
Hi @peakpeak-github 

What is the message in your server Error log file?

**Comment by peakpeak-github** [comment]
example.com 9.8.7.6 - - [25/Oct/2015:16:10:25 +0000] "GET http://example.com/Analytics/piwik.php?action_name=example.com&idsite=2&rec=1&r=242690&h=17&m=13&s=23&url=http%3A%2F%2Fexample.com%2Fexampletext%2F&urlref=http%3A%2F%2Fexample.com%2Ftest%2F&_id=1371a HTTP/1.1" 204 - "http://example.com/test/" "Mozilla/5.0 (Linux; Android 4.4.2; GT-N8020 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:24 +0000] "GET http://example.com/piwik/ HTTP/1.1" 200 3092 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/jquery/themes/base/jquery-ui.min.css?cb=939cb0a2977b6cfe835d45a073c374e8 HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular-sanitize/angular-sanitize.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/Installation/stylesheets/installation.css?cb=939cb0a2977b6cfe835d45a073c374e8 HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular/angular.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/jquery/dist/jquery.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/jquery-ui/ui/minified/jquery-ui.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular-animate/angular-animate.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular-cookies/angular-cookies.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/filters/filter.module.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/services/service.module.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/ngDialog/js/ngDialog.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/filters/translate.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/piwikApp.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/piwikApp.config.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/directives/focus-anywhere-but-here.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/directives/directive.module.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/menudropdown/menudropdown.directive.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/Installation/javascripts/installation.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/LanguagesManager/angularjs/languageselector/languageselector.directive.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/index.php?module=Installation&action=getBaseCss&cb=939cb0a2977b6cfe835d45a073c374e8 HTTP/1.1" 200 7641 "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:34 +0000] "GET http://example.com/piwik/libs/bower_components/jquery/dist/jquery.min.map HTTP/1.1" 200 141666 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/libs/bower_components/angular/angular.min.js.map HTTP/1.1" 200 102431 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/menudropdown/menudropdown.directive.html?cb=undefined HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/libs/bower_components/jquery/dist/jquery.js HTTP/1.1" 200 84236 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/piwik.php?url=http://example.com HTTP/1.1" 200 356 "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:38 +0000] "GET http://example.com/piwik/index.php?action=systemCheck HTTP/1.1" 503 1 "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 4.3.2.1 - - [25/Oct/2015:16:29:41 +0000] "GET http://example.com/piwik/index.php?module=Installation&action=getEmptyPageForSystemCheck HTTP/1.1" 200 502 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 4.3.2.1 - - [25/Oct/2015:16:29:45 +0000] "GET http://example.com/piwik/index.php?module=Installation&action=getEmptyPageForSystemCheck HTTP/1.1" 200 502 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"

**Comment by peakpeak-github** [comment]
example.com 9.8.7.6 - - [25/Oct/2015:16:10:25 +0000] "GET http://example.com/Analytics/piwik.php?action_name=example.com&idsite=2&rec=1&r=242690&h=17&m=13&s=23&url=http%3A%2F%2Fexample.com%2Fexampletext%2F&urlref=http%3A%2F%2Fexample.com%2Ftest%2F&_id=1371a HTTP/1.1" 204 - "http://example.com/test/" "Mozilla/5.0 (Linux; Android 4.4.2; GT-N8020 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:24 +0000] "GET http://example.com/piwik/ HTTP/1.1" 200 3092 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/jquery/themes/base/jquery-ui.min.css?cb=939cb0a2977b6cfe835d45a073c374e8 HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular-sanitize/angular-sanitize.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/Installation/stylesheets/installation.css?cb=939cb0a2977b6cfe835d45a073c374e8 HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular/angular.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/jquery/dist/jquery.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/jquery-ui/ui/minified/jquery-ui.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular-animate/angular-animate.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/angular-cookies/angular-cookies.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/filters/filter.module.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/services/service.module.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/libs/bower_components/ngDialog/js/ngDialog.min.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/filters/translate.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/piwikApp.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/piwikApp.config.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/directives/focus-anywhere-but-here.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/common/directives/directive.module.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/menudropdown/menudropdown.directive.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/Installation/javascripts/installation.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/plugins/LanguagesManager/angularjs/languageselector/languageselector.directive.js?cb=953c8655246e67938e92ea9f3c33ad9a HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:32 +0000] "GET http://example.com/piwik/index.php?module=Installation&action=getBaseCss&cb=939cb0a2977b6cfe835d45a073c374e8 HTTP/1.1" 200 7641 "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:34 +0000] "GET http://example.com/piwik/libs/bower_components/jquery/dist/jquery.min.map HTTP/1.1" 200 141666 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/libs/bower_components/angular/angular.min.js.map HTTP/1.1" 200 102431 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/plugins/CoreHome/angularjs/menudropdown/menudropdown.directive.html?cb=undefined HTTP/1.1" 304 - "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/libs/bower_components/jquery/dist/jquery.js HTTP/1.1" 200 84236 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:35 +0000] "GET http://example.com/piwik/piwik.php?url=http://example.com HTTP/1.1" 200 356 "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 1.2.3.4 - - [25/Oct/2015:16:28:38 +0000] "GET http://example.com/piwik/index.php?action=systemCheck HTTP/1.1" 503 1 "http://example.com/piwik/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 4.3.2.1 - - [25/Oct/2015:16:29:41 +0000] "GET http://example.com/piwik/index.php?module=Installation&action=getEmptyPageForSystemCheck HTTP/1.1" 200 502 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
example.com 4.3.2.1 - - [25/Oct/2015:16:29:45 +0000] "GET http://example.com/piwik/index.php?module=Installation&action=getEmptyPageForSystemCheck HTTP/1.1" 200 502 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"
 
Från: Matthieu Aubry [mailto:notifications@github.com] 
Skickat: den 27 oktober 2015 06:50
Till: piwik/piwik <piwik@noreply.github.com>
Kopia: Peter Åkerström <peter.akerstrom@kunskapsgreppet.se>
Ämne: Re: [piwik] 2.15.0 installation hangs (#9102)
 
Hi @peakpeak-github <https://github.com/peakpeak-github>  
What is the message in your server Error log file?

**Comment by peakpeak-github** [comment]
If I remove/rename manifest.inc.php installation do proceed to the next step:
File integrity check could not be performed due to missing manifest.inc.php. If you are deploying Piwik from Git, this message is normal.
 
Från: Matthieu Aubry [mailto:notifications@github.com] 
Skickat: den 27 oktober 2015 06:50
Till: piwik/piwik <piwik@noreply.github.com>
Kopia: Peter Åkerström <peter.akerstrom@kunskapsgreppet.se>
Ämne: Re: [piwik] 2.15.0 installation hangs (#9102)
 
Hi @peakpeak-github <https://github.com/peakpeak-github>  
What is the message in your server Error log file?
