### ISSUE TITLE
Logger not working in version 2.15.0?

### ISSUE THREAD

**Issue by d33a** [piwik/piwik#9103]
Hi guys,

Since we upgraded to the latest version, piwik stopped writing anything to the logs. 

This is my configuration for development. 

[log] 
; Possible values are "screen" (default value), "file" and "database" (logs to tables logger_*) 
log_writers[] = file 
; Possible values are ERROR, WARN, INFO, DEBUG 
log_level = INFO 
; if configured to log to file, log entries will be written to this file 
logger_file_path = tmp/logs/piwik.log 

Checked that it has full permissions to write in that location, tried switching it to database, nothing comes out. We're running the archive process as well, no output, not even in debug. 

Tried changing the /var/www/piwik/plugins/Monolog/config/config.php to override the values, nothing. 

Any input on this?

**Comment by tsteur** [comment]
I just tested it on my server and works fine. Can you check if the "Monolog" plugin is actually enabled under "Administration" => "Plugins"?

**Comment by d33a** [comment]
Hi,

Yes, that fixed the issue. I think it's nice that you deprecated the internal logging feature and created the Monolog plugin. However, this plugin should be enabled by default. Moreover, the documentation on this page should be updated http://piwik.org/faq/troubleshooting/faq_115/ since it doesn't mention anything about enabling the Monolog plugin.

**Comment by tsteur** [comment]
The plugin should have been activated automatically by our system. Possibly the config file was not writable. 

@mattab I leave this issue open for 2 things:

* [ ] Add to FAQ to make sure `Monolog` plugin is updated
* [ ] Run Piwik updater only when config file is writable, this will avoid many issues in the future

**Comment by mattab** [comment]
* Added a note in FAQ [How do I enable logging in Piwik](https://piwik.org/faq/troubleshooting/faq_115/) 
* Created issue: Display warning during Piwik update, if the config file is not writable #9128
