### ISSUE TITLE
Implement ordering by "last updated", "new" at http://plugins.piwik.org/

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#9105]
It would be useful to see plugins that have been recently updated or newly added at http://plugins.piwik.org/.

**Comment by mattab** [comment]
Thanks for suggestion. Note: sorting plugins this way is possible within Piwik > Admin > Marketplace

**Comment by gaumondp** [comment]
But Piwik server that doesn't have access to the internet like mine can't have such view...

I also think a second tab to separate PRO vs. Downloadable plugins would be quite useful too !

**Comment by tsteur** [comment]
They are now sorted by newest but it is not possible to change it
