### ISSUE TITLE
can not run tests as the table does not exist!

### ISSUE THREAD

**Issue by moha-teravolt** [piwik/piwik#9114]
Hi,

I have installed a fresh Piwik from Git and trying to understand the PHPUnit-Tests on it. I have following this page for configuring it to run the tests on the core. 
https://github.com/piwik/piwik/tree/master/tests

However after running the following command I am getting an error and it says the table does not exist.  $ php console tests:run --testsuite unit

I have checked my database and there is no table names "piwiktests_option" so the question what I did do wrong? How can I fix it?

Thanks in advance.

==================================================================
```
\piwik-master>php console tests:run --testsuite unit
Did you know? You can run tests faster by disabling xdebug (if you need xdebug, speed up tests by setting xdebug.coverage_enable=0)
Executing command: cd \piwik-master/tests/PHPUnit && \piwik-master/vendor/bin/phpunit   --testsuite Unit
Tests

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neu.piwiktests_option' doesn't exist' in \piwik-master\libs\Zend\Db\Statement\Pdo.php on line 234

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neu.piwiktests_option' doesn't exist in \piwik-master\libs\Zend\Db\St
atement\Pdo.php on line 228

Call Stack:
    0.0000     237416   1. {main}() \piwik-master\vendor\phpunit\phpunit\phpunit:0
    0.0156    1154496   2. PHPUnit_TextUI_Command::main() \piwik-master\vendor\phpunit\phpunit\phpunit:47
    0.0156    1161176   3. PHPUnit_TextUI_Command->run() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:100
    0.0156    1163976   4. PHPUnit_TextUI_Command->handleArguments() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:110
    0.0156    1758240   5. PHPUnit_TextUI_Command->handleBootstrap() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:585
    0.0156    1767280   6. PHPUnit_Util_Fileloader::checkAndLoad() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:764
    0.0156    1767480   7. PHPUnit_Util_Fileloader::load() \piwik-master\vendor\phpunit\phpunit\src\Util\Fileloader.php:36
    0.0156    1801792   8. include_once('\piwik-master\tests\PHPUnit\bootstrap.php') \piwik-master\vendo
r\phpunit\phpunit\src\Util\Fileloader.php:52
    0.5460    7371896   9. prepareServerVariables() \piwik-master\tests\PHPUnit\bootstrap.php:118
    0.5460    7372208  10. Piwik\SettingsPiwik::getPiwikUrl() \piwik-master\tests\PHPUnit\bootstrap.php:71
    0.5460    7372336  11. Piwik\Option::get() \piwik-master\core\SettingsPiwik.php:168
    0.5460    7372464  12. Piwik\Option->getValue() \piwik-master\core\Option.php:46
    0.5460    7372568  13. Piwik\Option->autoload() \piwik-master\core\Option.php:173
    0.5460    7372888  14. Piwik\Db::fetchAll() \piwik-master\core\Option.php:260
    0.5460    7373080  15. Zend_Db_Adapter_Abstract->fetchAll() \piwik-master\core\Db.php:200
    0.5460    7373080  16. Piwik\Db\Adapter\Pdo\Mysql->query() \piwik-master\libs\Zend\Db\Adapter\Abstract.php:736
    0.5460    7373080  17. Zend_Db_Adapter_Pdo_Abstract->query() \piwik-master\core\Db\Adapter\Pdo\Mysql.php:245
    0.5460    7373080  18. Zend_Db_Adapter_Abstract->query() \piwik-master\libs\Zend\Db\Adapter\Pdo\Abstract.php:238
    0.5460    7375248  19. Zend_Db_Statement->execute() \piwik-master\libs\Zend\Db\Adapter\Abstract.php:479
    0.5460    7375248  20. Zend_Db_Statement_Pdo->_execute() \piwik-master\libs\Zend\Db\Statement.php:300
    0.5460    7375296  21. PDOStatement->execute() \piwik-master\libs\Zend\Db\Statement\Pdo.php:228

Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neu.piwiktests_option' doesn't exist in \piwik-master\
libs\Zend\Db\Statement\Pdo.php on line 234

Call Stack:
    0.0000     237416   1. {main}() \piwik-master\vendor\phpunit\phpunit\phpunit:0
    0.0156    1154496   2. PHPUnit_TextUI_Command::main() \piwik-master\vendor\phpunit\phpunit\phpunit:47
    0.0156    1161176   3. PHPUnit_TextUI_Command->run() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:100
    0.0156    1163976   4. PHPUnit_TextUI_Command->handleArguments() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:110
    0.0156    1758240   5. PHPUnit_TextUI_Command->handleBootstrap() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:585
    0.0156    1767280   6. PHPUnit_Util_Fileloader::checkAndLoad() \piwik-master\vendor\phpunit\phpunit\src\TextUI\Command.php:764
    0.0156    1767480   7. PHPUnit_Util_Fileloader::load() \piwik-master\vendor\phpunit\phpunit\src\Util\Fileloader.php:36
    0.0156    1801792   8. include_once('\piwik-master\tests\PHPUnit\bootstrap.php') \piwik-master\vendo
r\phpunit\phpunit\src\Util\Fileloader.php:52
    0.5460    7371896   9. prepareServerVariables() \piwik-master\tests\PHPUnit\bootstrap.php:118
    0.5460    7372208  10. Piwik\SettingsPiwik::getPiwikUrl() \piwik-master\tests\PHPUnit\bootstrap.php:71
    0.5460    7372336  11. Piwik\Option::get() \piwik-master\core\SettingsPiwik.php:168
    0.5460    7372464  12. Piwik\Option->getValue() \piwik-master\core\Option.php:46
    0.5460    7372568  13. Piwik\Option->autoload() \piwik-master\core\Option.php:173
    0.5460    7372888  14. Piwik\Db::fetchAll() \piwik-master\core\Option.php:260
```

**Comment by tsteur** [comment]
Can you check `config/config.ini.php` what the config `tables_prefix` in the `[database_tests]` section says? Maybe try to clear the value and set `tables_prefix = ""`. It should work with any table prefix though. Is there a value defined for `dbname` in this section? 

The unit tests should even work without a database but haven't tested this recently.

**Comment by moha-teravolt** [comment]
I do not see anything related to tables_prefix under [database_tests] I did not have this config in my config file and added it by my self after reading : "Ensure the [database_tests] section in piwik/config/config.php.ini is set up correctly, i.e. with the correct password to prevent the following error: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"

So I just added the same config as my normal piwik database. I think it should be a seperate database with some default tables in it ? But how to get it import to mysql, is there any *.sql I can import or any script which will create the tests tables ?

**Comment by tsteur** [comment]
My database section looks like this:

```ini
[database_tests]
host = "127.0.0.1"
username = "root"
password = "secure"
tables_prefix = ""
```

This should have been configured automatically by the test runner command when you execute `console tests:run` the first time. You should not define a `dbname` here, just to be sure it won't overwrite your regular Piwik database. There is no SQL to import. It should all work automatically. Whenever we run a test we reset the database and create all needed tables etc. Does the specified user have permissions to create a MySQL database and table etc?

**Comment by moha-teravolt** [comment]
Thanks for your reply. I have checked my configuration again and it seems to be correct
```
[database_tests]
host = "127.0.0.1"
username = "root"
password = ""
tables_prefix = ""
```

**Comment by moha-teravolt** [comment]
After searching in the files I have found following :
https://github.com/piwik/piwik/blob/master/tests/resources/piwik-1.13-dump.sql

I have imported it to my database and now that error is not showing any more.

However I am getting following error :

Executing command: cd \piwik-master/tests/PHPUnit && \piwik-master/vendor/bin/phpunit   --testsuite SystemTests
WARNING: for tests to pass, you must first:
1) Install webserver on localhost, eg. apache
2) Make these Piwik files available on the webserver, at eg. http://localhost/dev/piwik/
3) Install Piwik by going through the installation process
4) Configure tests section if needed in config/config.ini.php:
[tests]
http_host   = "localhost"
request_uri = "@REQUEST_URI@"
remote_addr = "127.0.0.1"

Try again.

==================================

I have already installed webserver on local host and can access my piwik over a internal domain "piwik-master.dev" => http://piwik-master.dev/index.php

I have installed piwik on the same internal domain through the installtion process. 

I also added [tests] and its arguments to my config file.

Any Idea why is it happening?

**Comment by moha-teravolt** [comment]
I got it finally solved. 

[database_tests]
host = "127.0.0.1"
username = "root"
dbname = "piwik"
tables_prefix = "piwik_"

piwik is my database and after adding that and tables_prefix it is working now.

**Comment by tsteur** [comment]
Just FYI:

In case you are using some `dbname` and `tables_prefix` in `[database]` section you might overwrite your normal Piwik instance data whenever you run a test. In this case I'd use a different `tables_prefix` for tests.

I'm still not sure why it didn't work before. It looks like `root` user didn't have permission to create another database maybe or so but doesn't seem to be likely.

**Comment by diosmosis** [comment]
Just a guess, but FrontController or some other class will autoload options even when running a console command. So when running `./console tests:run`, it will try to access the database in `[database]` before launching phpunit. My guess is this was set to `piwiktests` in the user's config, but no Piwik was actually installed resulting in the error above.

**Comment by tsteur** [comment]
Good point, I think we used to check for this but removed it, since it slowed down the tests quite a lot. Instead we call `SettingsPiwik::isPiwikInstalled()` maybe this check is not really working

**Comment by mattab** [comment]
See: https://github.com/piwik/piwik/issues/10348#issuecomment-255291834
