### ISSUE TITLE
Transitions: Every tracked site opens with the same Transition Data (also exits are negative)

### ISSUE THREAD

**Issue by Jarla** [piwik/piwik#9120]
Hi,

When i open a transition view for a tracked page i get the same transition data for all pages. The Url parameter are different (see screenshots) and when i click it i get forwarded to a differnt page so piwik does know the correct page that i clicked its just the same data for every page. 
Also the "exits" Number is negative.

Its working correct on the "pagetitle" view but doesnt work on pages, entry pages and exit pages views

Piwik Version is 2.14.1

The data on the Page view (where i open the transistion view) seems to be correct
![transitions1](https://cloud.githubusercontent.com/assets/631594/10816068/66e974e6-7e30-11e5-9bd0-7d0212f1930a.png)
![transitions2](https://cloud.githubusercontent.com/assets/631594/10816069/66eae790-7e30-11e5-90cd-7c126b951931.png)

best regards
Chris

**Comment by mattab** [comment]
Hi @Jarla 

Could you try upgrade to 2.15.0 and confirm if you still have this issue?

**Comment by mattab** [comment]
@Jarla 
please upgrade to our latest 2.16.0 beta version: http://piwik.org/faq/how-to-update/faq_159/

if you still have the problem after this upgrade (for new data) please re-open this issue and we will investigate!
