### ISSUE TITLE
noindex, no follow, no archive also for login page

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9121]
follow up to https://github.com/piwik/piwik/issues/6552
and as proposed in
https://github.com/piwik/piwik/pull/8058#issuecomment-151971579

=> a new ticket for better security of login page:

From security point of view an easy to find login page is not that great.
One could e.g. easily do the following thing - FULLY AUTOMATED:
1) search for login page
2) start brute force attack
3) when you are successful: look for ecommerce
4) extract /download everything
5) make a database of ecommerce data
6) sell it to everyone (competitors)

on other systems their is a great effort to hide login page with the following:

- of course for every kind of visitors: noindex, no follow, no archive
- have a possibility to easily change login url within the backend

**so I would strongly vote for noindex, no follow, no archive also for login page**

another idea what could happen also on non ecommerce sites is written here: https://github.com/piwik/piwik/pull/8058#issuecomment-151757663

**Comment by tsteur** [comment]
:+1: 

One could still crawl for Piwik installations though, at least in most cases when one uses JS tracking. Eg one can search for standard Piwik snippet in website and get the URL to the Piwik instance. This can be done automated too, it is harder this way though as one has to actually crawl websites. There are also some services I think that show which websites use Google Analytics, Piwik, ... 

A very important thing would be to actually prevent brute forces eg via https://github.com/piwik/piwik/issues/2888 or by making authentication each time a few seconds slower when login fails etc

**Comment by hpvd** [comment]
of course this is only one step and there are more to do!

hmm can one really find piwik by searching for a part of an embedded code snippet?
I thought google searches (shows) only for "visible" information.

Doing a site specific search on our domain (site:www. ... ) which is using piwik
for "piwiktracker" there were no results.
Do you have a working example finding piwik in source code?

**Comment by tsteur** [comment]
You could crawl the internet yourself, eg with something like http://nutch.apache.org/ or any other web crawler. There might be even search engines already that let you search for certain snippets in a website. Just saying with enough effort your Piwik can be still found usually (unless you are using maybe LogImporter and do not track client side). Therefore it is also important to work on the brute force attack issue.

**Comment by mattab** [comment]
Thanks for suggestion! but because it does not help security, I don't want to do it. One is welcome to write a plugin to do it, but honestly there is no value in terms of security.
