### ISSUE TITLE
Entry Piwik\Plugins\Diagnostics\DiagnosticService cannot be resolved

### ISSUE THREAD

**Issue by pcambra** [piwik/piwik#9122]
Entry Piwik\Plugins\Diagnostics\DiagnosticService cannot be resolved: The parameter 'mandatoryDiagnostics' of Piwik\Plugins\Diagnostics\DiagnosticService::__construct has no value defined or guessableFull definition:Object ( class = Piwik\Plugins\Diagnostics\DiagnosticService scope = singleton lazy = false __construct( $mandatoryDiagnostics = #UNDEFINED# $optionalDiagnostics = #UNDEFINED# $disabledDiagnostics = #UNDEFINED# ))

Running 2.14.3

Checked #8479 but everything that is mentioned there seems fine

If I do ./console diagnostics:run -v I get:

INFO [2015-10-29 12:42:53] Unable to test if mod_pagespeed is enabled: the request to http://unknown/./console?module=Installation&action=getEmptyPageForSystemCheck failed

**Comment by mattab** [comment]
Hello
Add a line `Plugins[] = "Diagnostics"` in your config.ini.php

See #8479

**Comment by pcambra** [comment]
Thank you, that was it, I had it configured in one webserver but not the mirrored one.
