### ISSUE TITLE
Javascript doesn't load correctly on the first load for admin pages

### ISSUE THREAD

**Issue by pcambra** [piwik/piwik#9123]
Piwik 2.14.3, both firefox and chrome I'm always getting a js error on the first load of the piwik admin pages:

TypeError: $(...).attr(...) is undefined
...){if(broadcast.isHashExists()==false){$('li:first a:first',this.menuNode).click(...

That makes the date range widget look like this:

https://monosnap.com/file/88Dud3StbxP2y5WiQfSphHJbhK9Nnp.png

And the graphs aren't displayed either.

Refreshing the page solves the problem but it happens in every new visit.

**Comment by tsteur** [comment]
Do you mind updating to the latest Piwik version (2.15.0)? There's a chance this issue is fixed and in case you're using something like an Ad blocker Piwik should detect it and display a warning.

**Comment by pcambra** [comment]
Thanks for the feedback, we don't have Ad blockers in place an this happens to all our admin users.

Planning to upgrade to 2.15.0 but not immediately, I've been having this issue since 1.8-1.9 (not sure if before), any hint on where to start debugging?

**Comment by tsteur** [comment]
Yes, I'd check out https://piwik.org/faq/troubleshooting/faq_18485/ in this case
