### ISSUE TITLE
piwik.js - throws error when used in xulrunner

### ISSUE THREAD

**Issue by DinkoMiletic** [piwik/piwik#9125]
Hello,

I want to use piwiki in my xulrunner application. In xulrunner envinroment document.domain is set as null and can't be changed. Trying to do splice on document.domain will throw error.

Error thrown by xulrunner.

```javascript
Timestamp: 29.10.2015 19:42:15
Error: TypeError: hostName is null
Source File: https://domain.com/piwik/js/piwik.js
Line: 1547
```

And this is line when problem occurs.

```javascript
 hostName.slice(0, 5) === '74.6.') {     
```

**Comment by mattab** [comment]
Hi @DinkoMiletic Thanks for the report!

maybe you know JavaScript and can open a pull request to fix this issue, we'd welcome this :-)
