### ISSUE TITLE
Attach official release package to GitHub releases

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9126]
Some users go to GitHub releases to download the Piwik ZIP see https://github.com/piwik/piwik/issues/9097#issuecomment-151915377. Those ZIP files seem to include all files though which makes it as "bad" and "complicated to use" (composer, ...) as using it directly via Git which is not recommended. 

Instead it would be good to have the official package there which doesn't include the test files, the plugins that are not needed etc.  If this is not possible we should check if there's a way to disable downloads there. This might also avoid some random issues in the future.

Wasn't sure if it belongs to https://github.com/piwik/piwik-package/issues . Feel free to move

**Comment by mattab** [comment]
The release on Github is not created with a script but is created manually (in two clicks using Releases > New), just prior to running the script to package the build https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh

 to attach the files automatically to the github release, we'd need to use Github API.
Alternatively we could add a link in the release notes on Github to point the ZIP packaged URL in builds.piwik.org/piwik-x.y.zip

**Comment by Joey3000** [comment]
https://github.com/piwik/piwik/issues/9091 is another example of someone downloading from Github instead of builds.piwik.org.

> Alternatively we could add a link in the release notes on Github to point the ZIP packaged URL in builds.piwik.org/piwik-x.y.zip

Maybe that could be added to the release notes of the already released Piwik 2.15.0, to help prevent such issues from popping up with the current release? (The notes can be modified post-release.)

**Comment by tsteur** [comment]
Thx! I updated https://github.com/piwik/piwik/releases/tag/2.15.0 

Maybe we can do something like this easily in the build script. That would be helpful

**Comment by Joey3000** [comment]
@tsteur Thanks! Just one minor thing: Both added download links support HTTPS. Could they be changed to `https://`?

Note: The download link on the https://piwik.org/download/ page does not use HTTPS, but that's something for https://github.com/piwik/piwik/issues/8236#issuecomment-153171121.

**Comment by mattab** [comment]
I've changed links to `https` and updated the "Release 2.15.0 checklist" to include this new step: https://github.com/piwik/piwik/issues/8787#

(So we'll remember to do it for next release)

**Comment by mattab** [comment]
as you can see in Piwik 2.15.1 release checklist in https://github.com/piwik/piwik/issues/9236, there is now a step to update the Github release page to link to the builds. This should fix this issue, thanks for suggesting!
