### ISSUE TITLE
Issues related to Site Migration Plugin

### ISSUE THREAD

**Issue by shivateja-madipalli** [piwik/piwik#9127]
Site Migration Plugin isn't working as it is suppose to work.
https://plugins.piwik.org/SiteMigration

I have 2 servers running Piwik and tracking 8 sites. Server 1 has new data (After Oct 13th) and Server 2 has old data (Before Oct 13th).
I need to merge Server 2 with Server 1, I used SiteMigration plugin, small website data were migrated without flaw but, larger website data have not been transmitted, it was stuck for more than 7 hours.

Though smaller data was migrated, piwik saved it under different siteID, like in my old data, website 1 siteID was 2 where as after migrating the siteID changed to 16.

I use Piwik newest version + mySQL

**Comment by AlexTheBest** [comment]
I had the same issue, with the smaller sites I could transfer in decent amount of time.
However for large sites I let it run for 2-3 hours and appeared to be frozen, so I let it run longer and after another 3 hours I see it has done one month. After almost 3 days it transfer a years worth of data to the site. So for me it worked just took massive amount of time.
 
I haven't gone through the code and see how it works but I'm guessing it shouldn't take this long and what i could see on the database process list and web servers there wasn't actually any activity.

I use Piwik 2.9.1

**Comment by shivateja-madipalli** [comment]
That's for sure long time. 
Thanks for the input Alex!
I got it resolved, it took long time for me too but, at last it did migrate the data.

**Comment by mattab** [comment]
FYI we have released a new plugin which lets you migrate one website from one Matomo instance to another. Get it for free at http://plugins.matomo.org/Migration
