### ISSUE TITLE
Display warning during Piwik update, if the config file is not writable

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9128]
When the config file is not writable during an ugprade, some of the config file updates are not applied. For example in a recent Piwik version we introduced  new plugin `Monolog`, and this plugin was activated during the Upgrade. When the config file is not writable, the plugin cannot be activated, resulting in a partly broken Piwik instance (where logging does not work).

Suggested: when the config file is not writable and there is some update to execute, 
 * either issue a warning to the user to explain that the config file should be writable for the time of the upgrade, 
 * or issue an error message to prevent user from proceeding to the upgrade

follows up https://github.com/piwik/piwik/issues/9103#issuecomment-152302231 and many similar issues.

**Comment by mattab** [comment]
This will prevent serious bugs in the future :+1:

**Comment by tsteur** [comment]
See https://github.com/piwik/piwik/issues/9623 we should ideally also check whether tmp / cache directory is writable in order to clear the cache.

**Comment by alphaonex86** [comment]
Purge it and if unable to purge (remove failed) then display an error.

**Comment by mattab** [comment]
Done in #10423
