### ISSUE TITLE
security: disable autofill on login page

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9132]
For login the username is one part of the game,
so one should disable autofill also for username on login page for security reason

should be tested in common browsers.
at this tiem there is an autofill at least in FF and Opera

ideas on how to:
https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by mattab** [comment]
@hpvd thanks for suggestion, covered in https://github.com/piwik/piwik/issues/6347
