### ISSUE TITLE
Update Tracking Campaigns docs to include all existing aliases to pk_campaign and pk_keyword

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#9135]
According to https://github.com/piwik/piwik/issues/6674 there are several more aliases which are not documented at http://piwik.org/docs/tracking-campaigns/

It would be useful to have a full list of those in the documentation and why this matters or what the use case would be.

This information comes from global.ini.php comments:

; Comma separated list of variable names that will be read to define a Campaign name, for example CPC campaign
; Example: If a visitor first visits 'index.php?piwik_campaign=Adwords-CPC' then it will be counted as a campaign referrer named 'Adwords-CPC'
; Includes by default the GA style campaign parameters
campaign_var_name = "pk_cpn,pk_campaign,piwik_campaign,utm_campaign,utm_source,utm_medium"

; Comma separated list of variable names that will be read to track a Campaign Keyword
; Example: If a visitor first visits 'index.php?piwik_campaign=Adwords-CPC&piwik_kwd=My killer keyword' ;
; then it will be counted as a campaign referrer named 'Adwords-CPC' with the keyword 'My killer keyword'
; Includes by default the GA style campaign keyword parameter utm_term
campaign_keyword_var_name = "pk_kwd,pk_keyword,piwik_kwd,utm_term"

**Comment by mattab** [comment]
Thanks for suggestion, but we'd rather not document aliases, better to keep it simple :-) the fact that google analytics campaign parameters are supported is documented via the FAQ listed at the end http://piwik.org/faq/general/faq_119/
