### ISSUE TITLE
Upload artifacts for pull requests fails?

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9141]
I think when there is a PR like https://github.com/piwik/piwik/pull/9137 (not from `piwik/piwik`) the artifacts upload fails because of invalid authentication key see https://travis-ci.org/piwik/piwik/jobs/88599319#L1349  or maybe it is because of something else?

For reviews it would be good if we could see the uploaded artifacts. Do we actually need a key for `piwik/piwik`? I think we used to not have a key and we added it afterwards possibly to not allow to upload anything. Maybe there's a way we could allow uploading articfacts?

**Comment by mattab** [comment]
I believe it's due to the encryption of github tokens that only work when the PR is done by someone who is member of the Piwik ORG. @diosmosis would there be a way to have artifacts uploaded for all PRs including external contributors?

**Comment by diosmosis** [comment]
Not for external contributors w/o making the artifacts password public (ie, unencrypted).

**Comment by tsteur** [comment]
It would be helpful to have a solution for this. Maybe we can make the password public and instead add some security on the uploads server to make sure only expected things are uploaded (images etc)?
I just had a look at a PR with failing UI tests and had to run UI tests manually. Maybe there are other ideas?

**Comment by diosmosis** [comment]
>  instead add some security on the uploads server to make sure only expected things are uploaded (images etc)?

Should already be in place. Issue is w/ people potentially uploading lots of images or DDoS-ing. If there is some way to verify the request comes from travis-ci, then we don't need the password.

**Comment by tsteur** [comment]
Not sure if that's possible as possibly pretty much anything can be changed/faked if someone wants to

**Comment by diosmosis** [comment]
Just thought of something: try removing the environment variables from .travis.yml and setting them here: https://travis-ci.org/piwik/piwik/settings . Maybe these will be used by PRs.

**Comment by tsteur** [comment]
That's cool, haven't seen it before. I presume it's exactly for such cases maybe.

**Comment by diosmosis** [comment]
Actually in that case should make sure it's only the artifacts password that's used there. The autoupdate token shouldn't be forwarded to other repos.

**Comment by mattab** [comment]
Adding to 2.15.1 as it would be awesome to get UI tests artifacts for third party contributed Pull requests :+1:

**Comment by tsteur** [comment]
I will try it now

**Comment by tsteur** [comment]
Actually, I just read this:

> By default, the value of these new environment variables is hidden from the export line in the logs. This corresponds to the behavior of encrypted variables in your .travis.yml.

> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

So it won't work as pull requests could read the secret token otherwise. It should work though if we made the token visible. In this case it would as well work to define it in .travis.yml in plain text. But then anyone could ddos again and we cannot verify request is made from travis

**Comment by diosmosis** [comment]
Got screenshots to upload for a PR (build: https://travis-ci.org/piwik/piwik/jobs/99020321, screens: http://builds-artifacts.piwik.org/piwik/piwik/master/17369/).

**Comment by diosmosis** [comment]
Works for plugins as well: (build: https://travis-ci.org/piwik/plugin-TasksTimetable/builds/99023364, screens: http://builds-artifacts.piwik.org/piwik/plugin-TasksTimetable/master/72/).

See ui-tests-viewer for relevant changes.

Closing this issue.

**Comment by tsteur** [comment]
:+1: Awesome

**Comment by tsteur** [comment]
It  doesn't seem to work for System tests. I've created a new issue: https://github.com/piwik/piwik/issues/9685
