### ISSUE TITLE
Unable to access to plugins section in Administration panel after upgrading from version 2.14.0-RC1 to 2.15.0

### ISSUE THREAD

**Issue by abouquet** [piwik/piwik#9147]
After having upgraded Piwik from version 2.14.0-RC1 to 2.15.0, we are unable to access plugins section from the administration panel.

It seems that when we try to open this panel, Piwik try to get some data from the following DN : http://piwik.alwaysdata.net/

But when we try this URL from a navigator for example, DN can not be resolved, instead we get the following message : 

> Host not found

Is there any prerequisites to be able to browse the plugins panel ? 

Thanks

**Comment by mattab** [comment]
Hi @abouquet 

To browse the Plugins / Marketplace panel, it may be necessary that your server can connect to `plugins.piwik.org` hostname which is the API for the [Marketplace](http://plugins.piwik.org/)

**Comment by abouquet** [comment]
Hi @mattab,

I will open ```plugins.piwik.org``` destination in my firewall. But when i'm doing a tcpdump, it seems piwik try also to reach ```http://piwik.alwaysdata.net```. Why ?

**Comment by abouquet** [comment]
Ok, firewall open to destination IP.

It works, still have one question about the DN ```http://piwik.alwaysdata.net```
