### ISSUE TITLE
Add WAI-ARIA features to main menu for better accessibility

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#9148]
According to [Using ARIA menus](http://www.w3.org/WAI/GL/wiki/Using_ARIA_menus#Example_Keyboard_Behavior) WCAG WorkGroup at W3G and our [Accessibility analisys](https://github.com/piwik/piwik/wiki/Piwik-Accessibility-Analysis#main-menu), Piwik's menu should use *role* attribute using *menu, menuitem* values.

**Comment by mattab** [comment]
:+1:

**Comment by mattab** [comment]
Hi @tassoman was this issue fixed in your PR #9149  or is there more work to do?

**Comment by tassoman** [comment]
Focusing on main menu, things are almost done for now.
Mr @jdeyla and I are facing issues with NVDA and JAWS screen readers, they're working in different ways on Dashboard's ready moment, NVDA looks like award of page fulfillment (after widget load), JAWS still unaware, the link "skip to content" brings navigation to the empty div tag. 

In the end I think this is a different issue on a11y and may be a future PR. Such as "second menu" (horizontal) WAI-ARIA integration, will be.

There still opened a question opened with Core Dev Team on #7589, do you agree with Mr @jdeyla suggestions? (ref. [comment nr. 144698624](https://github.com/piwik/piwik/issues/7589#issuecomment-144698624))

**Comment by mattab** [comment]
> There still opened a question opened with Core Dev Team on #7589, do you agree with Mr @jdeyla suggestions? (ref. comment nr. 144698624)

This issue is closed, maybe you could create a new one or post here the feedback?

**Comment by tassoman** [comment]
Sorry for misunderstanding I was meaning that when he argued with menuitems low contrast visibility was 1st Oct. then you closed on 7th :)

Do you think we should open a new issue on it?

**Comment by tassoman** [comment]
In the user navbar there's the profile link. Screen readers reads this link only as user's Alias field value.
The best would be read a multi language translation of "Alias's personal settings" but I have no clue how to edit translations that are stored on [Transifex](https://www.transifex.com/piwik/piwik/dashboard/) :it: :fr: :gb:

**Comment by sgiehl** [comment]
Simply change the english default text in the english translation files on git. Transifex will automatically update the source and remove already available translations so they get translated again.

**Comment by tassoman** [comment]
I've managed it without adding any new translation string :sunglasses: 
I think this topic could be closed for now :smile:
