### ISSUE TITLE
not detecting users from INDIA and logging them as users from US

### ISSUE THREAD

**Issue by 28harishkumar** [piwik/piwik#9150]
This issue was marked as closed in 2009 https://issues.piwik.org/420 but it is there in latest version of piwik. I installed piwik yesterday and It showed me logged in from US instead of India.

I am still using google analytics in parallel and according to google analytics 22% sessions of my visitors are from INDIA. Piwik dashboard is showing no visit from India.

Is it still an issue in Piwik or I have to change and configuration?
You can also check embedded script in website http://www.findalltogether.com

In admin section, I had not blocked anything except my ip address (same in google analytics).

**Comment by gaumondp** [comment]
If you don't configure Geolocalisation, Piwik will use the language of visitors' browsers.

See: http://piwik.org/faq/how-to/faq_163/ and http://piwik.org/docs/geo-locate/
