### ISSUE TITLE
New visit after midnight - setting for disabling this characteristic

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#9156]
Refs #6217 - I disagree with the statement, that we shouldn't make a config setting for forcing a new visit at midnight as there are clearly many use cases where day change after midnight is irrelevant and should not force a visit to be new. We need this flexibility for piwik to not exclude certain industries or IoT tracking.

For example:
- Users who run campaigns at night for their target groups get very confusing results (e.g. TV spots or campaigns for certain industries). For them, it's the timespan of the traffic peak that counts, not the day change at midnight.
- as we approach the IoT space, we face the fact that for many "things" (gadgets, machines, idk), midnight is not relevant, because they're running around the clock and define their own timeframes and new visit triggers. Therefore the analyst should have the option to force a new visit at any time, even if it's after e.g. 3 days.

How's your opinion on that?

**Comment by tsteur** [comment]
True

Bit off topic: Ideally such setting would be site specific and have a global default setting but many settings in config are useless because they are always applied to all sites. Sometimes one wants to have different settings/behaviour per site.

**Comment by mattab** [comment]
@peterbo sounds good.

Downside is that: if a visit keeps being registered in the "previous day", then archiving may run in the meantime. Visit will keep updating in the "previous day" but the archive is already created. So we risk that any request done "in previous day" after archiving, will not be present in the archives. The archives will have "partial data" causing a data bug. What do you think?

**Comment by peterbo** [comment]
@matt yep, that's indeed a problem. I didn't think of that. 

Nevertheless I vote for this setting with e.g. a warning description in the global config. This makes sense when you're using Piwik just for a tracking purpose to pull the data into your own DWH. Therefore, the data should be biased as little as possible. Especially when this was done because of a technical implementation detail.

The per site vs global settings mentioned by @tsteur would be great as well, but I think that's a thing for another ticket as you already mentioned.

If you agree, I'll issue a pull request.

**Comment by mattab** [comment]
@peterbo PR sounds good :+1:

**Comment by peterbo** [comment]
Sorry, the first two commits were rubbish, because the fork was out of date and there were uncommited changes. Should be fine now with the PR.

**Comment by mattab** [comment]
fixed in https://github.com/piwik/piwik/issues/9310 - cheers @peterbo :+1:
