### ISSUE TITLE
errors with IP2Location plugin - 2.15.1-b1

### ISSUE THREAD

**Issue by schaganti1** [piwik/piwik#9157]
I recently installed IP2Location plugin on piwik 2.15.1-b1. I installed activated the plugin on Piwik admin dashboard and downloaded a SAMPLE.BIN file and placed in /plugins/IP2Location/data folder

I get bunch of errors in the dashboard 
WARNING: /var/www/html/piwikcust/piwik/plugins/IP2Location/Lookup.php(271): Warning - fseek() expects parameter 1 to be resource, boolean given - Piwik 2.15.1-b1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
×
WARNING: /var/www/html/piwikcust/piwik/plugins/IP2Location/Lookup.php(378): Warning - unpack(): Type V: not enough input, need 4, have 0 - Piwik 2.15.1-b1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by tsteur** [comment]
@schaganti1 do you mind creating the issue in this repository: https://github.com/ip2location/ip2location-piwik IP2Location is a plugin developed by another developer and we cannot directly help you here unfortunately
