### ISSUE TITLE
No error message is shown when a plugin fails to be installed

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9160]
My plugin does the following in the `install` method:

```php

    public function install()
    {
        $table = "`idcustomdimension` BIGINT UNSIGNED NOT NULL,
                  `idsite` BIGINT UNSIGNED NOT NULL ,
                  `name` VARCHAR(100) NOT NULL ,
                  `index` SMALLINT UNSIGNED NOT NULL ,
                  `scope` VARCHAR(10) NOT NULL ,
                  `active` TINYINT UNSIGNED NOT NULL DEFAULT 0,
                  `extractions` TEXT NOT NULL DEFAULT '',
                  UNIQUE KEY idcustomdimension_idsite (`idcustomdimension`, `idsite`)
                  UNIQUE KEY uniq_hash(idsite, `scope`, `index`)";

        DbHelper::createTable($this->tableName, $table);
    }
```

I was missing a comma before the second `UNIQUE KEY`. It tried to install it and failed but I was not notified in the UI about this problem. I thought it only did not find the install method or did not notice yet that it is not installed and took me a while to figure out there is an error in the SQL.

**Comment by mattab** [comment]
@tsteur  
+1 to fix in 2.15.1 (assuming it is trivial) and prevent some confusion to plugin developers
