### ISSUE TITLE
Tracker: Custom variables in scope page need to be cleared after tracking a pageview

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9162]
When calling `setCustomVariables` in scope `page` we never clear the set custom variables after a tracked pageview. This can be especially problematic in a single page application / website where one tracks multiple pageviews without reloading the whole page. 

This is for example the case in our Piwik app itself. We track a new pageview whenever a new report is loaded via ajax so a later pageview might actually use the custom variables of a previous pageview.

**Comment by mattab** [comment]
This may be a BC break for some, so adding tentatively to Piwik 3

**Comment by mattab** [comment]
As we will deprecate custom variables in #11524, closing this issue as Won't fix.

We now recommend to use [Custom Dimensions](https://piwik.org/docs/custom-dimensions/) instead.
