### ISSUE TITLE
Remove SQLite dependency in tracker tests

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9163]
To run Tracker tests via `http://$domain/tests/javascript/` one needs to have SQLite installed. It would be good to remove this dependency if possible and use eg MySQL instead or a plain text file if possible. 
We already have credentials for MySQL so this should be possible.

In the past I've always had some trouble getting SQLite to work and now [PHPBrew](https://github.com/phpbrew/phpbrew) I don't get it to work at all as I'm always getting an error when installing the extension and I cannot solve it. Meaning I cannot write tracker tests needed for custom dimensions etc.

It would be nice to reuse existing dependencies here (to be clear: MySQL). Does maybe anyone remember why we chose SQLite for this?

**Comment by diosmosis** [comment]
Looks like all it does is insert rows & do two simple queries. Could probably replace it w/ a text file.

**Comment by tsteur** [comment]
I'm just working on supporting MySQL and it pretty much works. There are some queries for token_auth so text file wouldn't be really so good.
