### ISSUE TITLE
Piwik.php returns 404 with two ">>" signs in title tag

### ISSUE THREAD

**Issue by pienisieni** [piwik/piwik#9166]
When using two greater-than signs ">>" within the title tag of a page, piwik.php returns a "404 not found" error. Thus the visit is not recorded. This behaviour was observed using WordPress 4.3.1. Piwik 2.15.0.

![two_greater_than_signs_piwik](https://cloud.githubusercontent.com/assets/9020358/10941497/0d349790-834f-11e5-8a03-5d0031f82c65.jpg)

**Comment by mattab** [comment]
Hi @pienisieni 

I think this is due to a module you use on your server, usually some mod security module or similar. See: https://piwik.org/faq/troubleshooting/faq_100/

Usually these server modules trigger 404 or 500 error when the request contains < or << etc.
