### ISSUE TITLE
segment selector: usable for funnel analysis by respecting order of elements

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9167]
enhancement of the great segment editor to respecting order of elements.
With this one could use it for concrete visitor way analysis and rough funnel analysis.

It's the same direction as the already implemented segments "entry page" and "exit page" work, but with a more general approach.

One idea how to implement this:
- new checkbox for activating "respect order of segments"
- when activated: switch "AND" => "THEN"

please see attachment
![2015-11-05_05h46_46](https://cloud.githubusercontent.com/assets/5681880/10960172/039119ce-8382-11e5-99b9-23deea877591.png)
.

**Comment by hpvd** [comment]
if this one is similar to #7533, please mark as duplicate
if not please leave it open and let us discuss about it.

**Comment by tsteur** [comment]
That's actually a pretty cool idea

**Comment by mattab** [comment]
:+1: 

It is discussed in issue: https://github.com/piwik/piwik/issues/7533#issuecomment-153959537
