### ISSUE TITLE
generate:plugin should control the name provided against an appropriate regex

### ISSUE THREAD

**Issue by abouquet** [piwik/piwik#9171]
When generating a new plugin, i've created a new one containing "-" character following the example

```php console generate:plugin --name="My-Plugin"```

The problem is that the name of the plugin is used to generate a php class file which isn't compatible with naming rules

**Comment by tsteur** [comment]
This is a very good find, thx! I issues a pull request to fix it (https://github.com/piwik/piwik/pull/9173) and I'm also updating the Marketplace and docs

**Comment by abouquet** [comment]
Thx for your quick fix :)
