### ISSUE TITLE
segment editor: use available ecommerce data for better segmentation of visits

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9172]
with piwik it's possible to track ecommerce data
```
// all parameters are optional, but we recommend to set at minimum productSKU and productName
_paq.push(['setEcommerceView',
"9780786706211", // (required) SKU: Product unique identifier
"Endurance: Shackleton's Incredible Voyage", // (optional) Product name
"Adventure Books", // (optional) Product category, or array of up to 5 categories
20.11 // (optional) Product Price as displayed on the page
]);
_paq.push(['trackPageView']);
[...]
```
source:
https://piwik.org/docs/ecommerce-analytics/

=> so it would be really gorgeous to use this already available ecommerce data for better segmentation of visits on ecommerce sites with making them available directly in segment-editor.

An idea for a structure in the segment editor, is the following:

**Visits**
- pages with products with prices  ` > / < / = `   123
- pages with products with sku  ` is / is not / contains / does not contain `  xxx
- pages with products with name  ` is / is not / contains / does not contain `  xxx
- pages with products of category  ` is / is not / contains / does not contain `   xxx

this ticket is the more general version of existing "Segment by Product Category" #4519
in which some more details e.g. on reasons for importance of product category segment are described...

**Comment by hpvd** [comment]
using the available ecommerce data for segmentation based on ecommerce ACTIONs is described in  segment editor: make ecommerce actions acessible #9175

**Comment by mattab** [comment]
Thanks for the suggestion @hpvd - your suggestions are now included in the scope of https://github.com/piwik/piwik/issues/4519
