### ISSUE TITLE
ecommerce: track more details of abandoned cart

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9176]
Piwik could track details of abandoned carts:
- items
- quantity
- price

That's great.
The results are showen e.g. in visitor log
please see attachment.

The question for the shop owner is not only what he has lost but also even more important
**why did he lost this order?**

To get a little help with the answer one need piwik to track some more data of the of abandoned carts:

Depending on the point of leaving the shop, the visitor may have seen and done (chosen)
everything.

With this, these things should be also be tracked and be visible within piwik
in same manner they are tracked on a successful order.

**1) Details for each item** on cart:
- Name
- SKU
- Original Price
- Price (on cart, after discount)
- Quantity

**2) For cart in general:**
- ShownTotal Revenue 
- Shown Tax amount
- Selected Payment method
- Shown payment cost
- Selected Shipping type
- Shown Shipping Cost
- Discount offered
- Discount reason e.g. coupon

even if some are not set (because not shown to visitor), one should still show the items but with the remark "not seen"

**Only with this information one could identify the reason for leaving the shop**

![2015-11-06_14h55_21](https://cloud.githubusercontent.com/assets/5681880/10999038/05589520-849a-11e5-9006-b68f97dbaffa.png)

**Comment by hpvd** [comment]
would be great to start tracking of all data soon (first step)
Showing and using the data could be added a little later (second step)

**Comment by mattab** [comment]
Hi @hpvd please note your suggestion new features/new tracking data, in the issue https://github.com/piwik/piwik/issues/6177
