### ISSUE TITLE
ecommerce: complete tracking of order's details

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9177]
Piwik is already tracking details of orders:

- Order Revenue grand total (includes tax, shipping, and subtracted discount)
- Order sub total (excludes shipping)
- Tax amount
- Shipping amount
- Discount offered 

This is great so far but some important things are missing for making good decisions on base of Piwiks data for the right direction/future of business concepts and details (e.g. strategy of products, prices and discount, shipping, payment etc.)

Since there was just a ticket opened collecting all important data to be tracked on abandoned carts #9176,
the same items are of course important for completed orders.

Here is the list:

**1) Details for each item** in order:
- Name
- SKU
- Original Price
- Price (on cart, after discount)
- Quantity

**2) For order in general:**
- Total Revenue 
- Tax amount
- Payment method
- Payment cost
- Shipping type
- Shipping Cost
- Discount
- Discount reason e.g. coupon

feel free to add some more!

**Comment by hpvd** [comment]
would be really great to start tracking of all data soon (first step, because they are needed to have good statistics afterwards)
Showing and using the data could be added a little later (second step)

**Comment by hpvd** [comment]
of course this is also still very interesting
"order with customer registration or without" #4760
the items above will give a real good base.

**Comment by mattab** [comment]
Hi @hpvd - thanks for suggestion! do you mind adding your suggestions of new features in the issue https://github.com/piwik/piwik/issues/6177  - note that piwik already tracks `1) Details for each item in order:` and displays them in the Visitor log. Piwik tracks some of the items in `2) For order in general:` but not all, maybe you can add the new suggested ones in #6177
