### ISSUE TITLE
manage plugins: Link to Plugin Hompage opens in same browser tab

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9178]
manage plugins: Link to "Plugin Hompage" opens in same browser tab
Should open in new tab like the other links do.
tested in Piwik 2.15

please see attachment
![2015-11-06_20h51_08](https://cloud.githubusercontent.com/assets/5681880/11007234/d59d4fea-84c8-11e5-8618-08f4f422c7b3.png)

**Comment by tsteur** [comment]
Thx for reporting!
