### ISSUE TITLE
Use crowd of all piwik users to enhance bot list, device list etc.

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9183]
Giving normal, non developer piwik users the easy to use possibility to **enhance bot list, device list, etc.** (e.g. with the method described in #9182)
these data should not only be usable local in the piwik installation of the user who enhanced the list, but **should be synced back to piwik and from there to other users.**
** *With this one can make the power of the crowd accessible to make piwik better and better.* **

**Comment by mattab** [comment]
Hi @hpvd 
Thanks for suggestion!

I like the idea unfortunately it's difficult to implement nicely in the product.

Our vision/strategy so far has been to create sub-projects that are open source where we welcome contributions from the community, and where the new contributions are automatically tested & validated.

I'm referring to:
 * referrer spammer blacklist: https://github.com/piwik/referrer-spam-blacklist/
 * search engine & social list: https://github.com/piwik/searchengine-and-social-list (just released!)
 * device detections: https://github.com/piwik/device-detector

Note that: referrer spammers, and Serach engine/social lists are automatically updated every week or so, in all Piwik installs, so when new contributions come, all Piwik users will benefit from them.

Marking this as wontfix as realistically we won't do it in product for now.
