### ISSUE TITLE
Allow Upgrade to replay logs automatically

### ISSUE THREAD

**Issue by agrowe** [piwik/piwik#9186]
Hi all,

It would be great if using the command line upgrade or the web upgrade would automatically replay the logs for you once complete.

Currently there is no easy way to do this as it requires somehow finding the correct "piwik.php" requests in a very large Apache log file and then importing them using the python import file.

If there was a config option to redirect logs or similar, so that when it comes to the `shouldRecordStatistics()` function in core\Tracker.php it is able to divert or create a special log file in the /tmp dir, that file could then be imported once the upgrade has been completed without losing any tracking information.

Are there any plans to reconfigure how upgrades work so that larger installations can update more easily?

Thanks
Alex

**Comment by tsteur** [comment]
The logs itself are written by your webserver, eg apache. There could be maybe a script that gets all requests between upgrade start and upgrade end and then replaying these logs. 

The last upgrades did not include any schema changes so the updates should have taken only a few seconds but it obviously depends on the setup etc. Also there might be upgrades that take longer in the future and there might be plugins that take a long time when installing them (eg the new plugin [CustomDimensions](https://github.com/piwik/piwik/issues/9129) will take a long time when installing it via Marketplace).

There is a plugin [QueuedTracking](http://plugins.piwik.org/QueuedTracking) that writes all requests into a queue similar to how you described but it would do it all the time, even when you are not upgrading.

**Comment by agrowe** [comment]
Hi @tsteur 

I was thinking more along the lines of a custom log file just for piwik.php, as the Apache access file contains all page hits for the Piwik website.

We're trying to come up with a solution where an upgrade can be completed where no requests will be dropped, as we track all visits with userid and a custom variable to map a user's actions through our sites.

If we use the Redis plugin, I imagine we can stop the queue processing, upgrade the site then re-enable the queue processing, that will then pick up and slowly process all hits during the upgrade process? Are there issues when uploading new versions of the plugin/piwik and there being a time where the upgrade has not completed so it will not track requests?

**Comment by tsteur** [comment]
It should work with the Redis plugin but I haven't tested it. 

Basically you could:
1. Enable writing requests into redis
2. Start upgrade
3. Finish upgrade
4. Process all requests from redis into DB
5. disable queued tracking (Redis) again
6. Use normal tracking behaviour

**Comment by mattab** [comment]
We have this FAQ: [ How do I upgrade a large Piwik instance without losing any tracking data?](https://piwik.org/faq/how-to-update/faq_20844/)

I've just added in the FAQ the following: 



### Option 2

The second option requires the use of the [QueuedTracking plugin][4] with Redis. 

0. Install and setup QueuedTracking plugin.
1. Enable writing requests into Redis
2. Start Piwik upgrade
3. Finish Piwik upgrade
4. Process all requests from Redis into DB (backfill all your data)
5. Disable QueuedTracking plugin (Redis) again
6. Piwik normal behavior resumes

If you have any feedback or suggestion, please leave a comment below.


--> marking as closed as it's now documented. if there is any problem or question ask here or in the FAQ comment box
