### ISSUE TITLE
Filter visitors based on product viewed/purchased

### ISSUE THREAD

**Issue by ruchitrami** [piwik/piwik#9188]
Need product SKU/name in the segment creation section to filter by product viewed/purchased by visitor. It is basic feature that will be required for any ecommerce website.

**Comment by hpvd** [comment]
@ruchitrami this should be a double of a part of https://github.com/piwik/piwik/issues/9172
maybe you can spread a word about "needing this too" there..

**Comment by mattab** [comment]
Hi @ruchitrami @hpvd, duplicates #9172
