### ISSUE TITLE
Logs visit when using campaign

### ISSUE THREAD

**Issue by alexander7567** [piwik/piwik#9190]
When having a campaign set in the URL, PIWIK tracks the visit even if the do not track cookie is set.

**Comment by tsteur** [comment]
From which browser is this tracking request made? 

Do not track should not be related to campaign parameters. Are you sure it is only ignored when there is a campaign parameter?

There could be several reasons for it. Do Not Track feature is disabled in Piwik, PrivacyManager plugin is disabled, request is made from a browser that has Do Not Track always enabled

**Comment by alexander7567** [comment]
Turns out.. it was my fault. Sorry about that!

**Comment by tsteur** [comment]
Thx for letting us know
