### ISSUE TITLE
No data in segmented visitor log for urls with ampersand

### ISSUE THREAD

**Issue by babadoo** [piwik/piwik#9192]
We get a message "There is no data for this report." when trying to open
the segmented visitor log.

Reproduction steps:
1. Action/Pages
2. Choose the icon "Open segmented visitor log" for an url with an ampersand
f.e. www.mydomain.com/somepath?param1=value1&param2=value2

(We tried to work around with url encoding the ampersand with %26 but it doesnt help.)

Piwik Version 2.15.0, updated a few days ago, the users have the opinion, that this issue was not in the previous version.

**Comment by tsteur** [comment]
Can reproduce it: https://demo-anonymous.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?module=Actions&action=menuGetPageUrls&idSite=1&period=year&date=today&popover=RowAction$3ASegmentVisitorLog$3AActions.getPageUrls$3ApageUrl$253D$253Dhttp$25253A$25252F$25252Fdemo-anonymous.piwik.org$25252FMultiSites$25252Findex$25252F$25253FidSite$25253D1$252526period$25253Dday$252526date$25253Dtoday$3A$257B$257D

Thanks for the report!
