### ISSUE TITLE
segment counts more conversion than All visits segment

### ISSUE THREAD

**Issue by sidazhou** [piwik/piwik#9194]
Piwik 2.15
Please see screen shots below. (1st one is the segmented one, 2nd is the all visits)

My understanding is that a Segment is a subset of your Analytics data.

In piwik dashboard, I go to "Goals" -> "Overview" 
I notice that when I use "All visits (default)", it has LESS conversions than if I use some setting on Segment (which supposed to be a subset of All visits) In this case, the segment I used was "Page URL" "contains" "......."

How is this possible?

I've checked http://forum.piwik.org/read.php?2,129751,129751#msg-129751
which is solved by upgrading prototype, however I'm not using prototype nor custom variables.

link to forum:
http://forum.piwik.org/t/page-url-segment-counts-more-than-all-visits-segment/16621

![segemented_visit](https://cloud.githubusercontent.com/assets/8648738/11074170/0d9873ca-87a3-11e5-9031-cc1103b81cfd.jpg)
![all_visits](https://cloud.githubusercontent.com/assets/8648738/11074176/1389432c-87a3-11e5-8e0a-695f4ed5e989.jpg)

**Comment by mattab** [comment]
Thanks for the report @sidazhou 

I could reproduce this bug on the demo:
 * [No segment, 20 conversions](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2015-11-05#/?module=Goals&action=goalReport&idGoal=2&idSite=7&period=day&date=2015-11-05)
 * [Segment Page URL contains X, 26 conversions](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2015-11-05&segment=pageUrl%3D%40forum.piwik.org%252Flist.php%253F2#/?module=Goals&action=goalReport&idGoal=2&idSite=7&period=day&date=2015-11-05&segment=pageUrl%3D@forum.piwik.org%252Flist.php%253F2)

**Comment by tsteur** [comment]
I reckon this one could be similar to https://github.com/piwik/piwik/issues/9367 and it might show more conversions etc due do the fact that it goes over any `idaction_url`. So if we tracked the same `idaction_url` for events as for pageviews then it might find the same conversion multiple times. I will try to have a look at the database.

**Comment by tsteur** [comment]
Actually there were no events for this site so it cannot be the case

**Comment by tsteur** [comment]
Problem is when segmenting we seem to not respect the setting "goal can be only converted once per visit" see 

![image](https://cloud.githubusercontent.com/assets/273120/11771259/ab71898a-a272-11e5-9692-522599d51f1d.png)

Eg with query
```sql
SELECT
			log_link_visit_action.*
			FROM
				piwik_log_conversion AS log_conversion
				LEFT JOIN piwik_log_link_visit_action AS log_link_visit_action ON log_conversion.idvisit = log_link_visit_action.idvisit
			WHERE
				( log_conversion.server_time >= '2015-01-25 11:00:00'
				AND log_conversion.server_time <= '2015-01-26 10:59:59'
				AND log_conversion.idsite IN (1) )
                AND
                ( ( log_link_visit_action.idaction_url IN (SELECT idaction FROM piwik_log_action WHERE ( name LIKE CONCAT('%', '/', '%')  AND type = 1 )) ) )
                AND log_conversion.idgoal = 4
```
Here I get 49 results, but it should be 22 results which I get when I do eg `SELECT distinct log_link_visit_action.idvisit`

**Comment by xpader** [comment]
This happeing again in 3.12.0...
