### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cibler95** [piwik/piwik#9195]
bonjour

mon piwik fonctionne,  mais comment corriger :

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /srv/disk3/1073848/www/chweb.eu/semi-dedie/piwik/tmp/templates_c/8/3/83cbef9a0e8290a723662ff1192c2c8ec19555c324cd1e95ae3287198c367433.php on line 45

**Comment by tsteur** [comment]
Hey, do you mind using English here? 

Re your error: Did you install Piwik via Git or did you download the ZIP file from http://piwik.org ?

Maybe remove all files within the `piwik/tmp/*` directory and try again

**Comment by hpvd** [comment]
@cibler95 thanks for report.
A better description in short-description (=name=headline) would be nice ;-)

**Comment by mattab** [comment]
> Maybe remove all files within the piwik/tmp/* directory and try again

**Comment by mathewco** [comment]
The problem I had also from a second domain. I added trusted_hosts[] = "second-domain.tld" but it did not work. Great, removing all files within piwik/tmp has helped.

Many thanks!
