### ISSUE TITLE
Creating visitor segment in mobile phone fails

### ISSUE THREAD

**Issue by openbrian** [piwik/piwik#9196]
The popup will popunder.  Drag and drop doesn't work at all.

**Comment by tsteur** [comment]
Thanks for reporting. This issue is related to https://github.com/piwik/piwik/issues/9100 and is a duplicate of https://github.com/piwik/piwik/issues/9179

**Comment by tsteur** [comment]
It's actually not a duplicate, it's about drag & drop

**Comment by mattab** [comment]
It counts as a Major bug, as one expects to be able to create segments on Mobile. Adding to 2.15.1.

**Comment by mattab** [comment]
This should be fixed in git, let's confirm when it will be deployed on demo

**Comment by mattab** [comment]
Fixed in #10045 and verified on demo.piwik.org running latest beta. Kuddos @wronan
