### ISSUE TITLE
Plugin Updates Appear twice

### ISSUE THREAD

**Issue by Mooash** [piwik/piwik#9203]
I don't really know how to explain this without a picture:

![plugin_update_piwik](https://cloud.githubusercontent.com/assets/3689532/11115479/b8216e06-8923-11e5-8b7b-a093666ca035.png)

I don't have the plugin installed twice as far as I can see.

I'm using Piwik 2.15.0 on Ubuntu 14.04 running PHP 5.5.9

**Comment by hpvd** [comment]
thanks for report! Seems to be doubling:
https://github.com/piwik/piwik/issues/6737

**Comment by Mooash** [comment]
Ugh sorry, you're right. I tried to search but couldn't find anything. Closing in favour of #6737
