### ISSUE TITLE
Vistor-Log-Tool: 1. step: general setup + actions of type delete

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9204]
Doing a first step, setting up a first working version of the Visitor Log Tool described in https://github.com/piwik/piwik/issues/9182

containing the first actions, which are already
discussed to be highly needed in #3385

1) delete Visit
2) delete the visitor belonging to this visit (and all of his visits)

reasons for both: because you noticed e.g. it was you/ your colleague, it was a developer test etc...

Important:
the visits should not be really deleted but only be marked as deleted.
With one can integrate an undo feature easily.
Of course these "marked as deleted" visits should
- not be visible anywhere
- should no be part of any statistic

edit: just opened an extra ticket for this base work: https://github.com/piwik/piwik/issues/9205

**Comment by mattab** [comment]
Hi @hpvd - doesn't this duplicate  #3385 and could be maybe pasted as comment there?
