### ISSUE TITLE
Base function: Possibility to give visits a type like "standard", "deleted", "bot" etc.

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9205]
Possibility to give visits a "type" like:
- "standard"
- "deleted"
- "bot"
-...

With this one can keep every visit always in database but can
easily decide (filter) for each type of visit being
- visible 
- considered within statistic

This should be the better, more general way to achieve all advantages from
https://github.com/piwik/piwik/issues/9184

This is the basic for
1)  **Delete function** and being able to have an "undo function" (https://github.com/piwik/piwik/issues/3385 and https://github.com/piwik/piwik/issues/9204)
With this  the action **"deleting" is only a change of type** from standard to deleted
And undo is simply changing type from "deleted" back to "standard".
2) **Simplifying bot tracking** https://github.com/piwik/piwik/issues/9067 
every bot got the "type" "bot"

**Comment by hpvd** [comment]
to making undo easily possible one could e.g store a second type for each visit "was before type"

**Comment by hpvd** [comment]
from technical pov this could be somehow related to https://github.com/piwik/piwik/issues/8161

**Comment by mattab** [comment]
Thanks for suggestion @hpvd - I think it duplicates #9184 - feel free to post comment there if needed
