### ISSUE TITLE
Creating new goals immdiately after creating new website is not possible

### ISSUE THREAD

**Issue by idwaikat** [piwik/piwik#9206]
I created new website, then immediately I went using the menu to create new Goal, it redirected me to "No data has been recorded yet" (See screenshot below). I need to create my goals before recording any data. Why this is not applicable at this point?

![no-record](https://cloud.githubusercontent.com/assets/15815668/11117233/983d36a2-8940-11e5-9d46-a2bcfbaf4a17.png)

**Comment by tsteur** [comment]
You should still be able to create a goal meanwhile by going to your personal area (username or user icon top right) and then clicking on Goals. Maybe there could be a link to Manage Goals page from this screen.

**Comment by idwaikat** [comment]
It worked using this way. Thank you
