### ISSUE TITLE
You can't access this resource as it requires an 'view' access for the website id = 42.

### ISSUE THREAD

**Issue by jerrycave** [piwik/piwik#9213]
Hi,
I want to make piwik api call like this:
`http://xxx.com?module=API&method=VisitsSummary.get&idSite=42&period=day&date=2015-11-01&format=xml`

`http://xxx.com` is the server which ships the piwik application, but I get this error message:
`<error message="You can't access this resource as it requires an 'view' access for the website id = 42."/>`

Does I do something wrong?

**Comment by jerrycave** [comment]
Sorry, I resolved it by adding token_auth

**Comment by zinwalin** [comment]
thanks for tips.
