### ISSUE TITLE
Generation time is false when user visit one page

### ISSUE THREAD

**Issue by minple** [piwik/piwik#9215]
Last page (Visitors > Visitor Log > action) or when user visit one page, Generation time is false. It is only 0.xx s.

**Comment by tsteur** [comment]
Are you sure a generation time is set? By any chance, you do not mean the "time spent" dimension where this is kinda expected?

**Comment by minple** [comment]
I don't know. However, When user visit for 2 page or more, only last page has generation time is 0.xx s, other page has generation time is 57 s, 1 m, .... Visitors close browser or close tab, generation time is false.at current page.

I am sorry for my English, My English is not good

**Comment by mattab** [comment]
Hi @minple I can't reproduce this issue. Are you using piwik 2.15.0? could you post a screenshot showing the problem?

**Comment by minple** [comment]
Yes, Piwik 2.15.0. Some screenshots.
![screenshot from 2015-11-18 14-03-20](https://cloud.githubusercontent.com/assets/10332628/11234781/e8d629d6-8dfd-11e5-8097-7911c6e1b364.png)
![Uploading Screenshot from 2015-11-18 14-03-30.png…]()
![screenshot from 2015-11-18 14-04-00](https://cloud.githubusercontent.com/assets/10332628/11234782/e8dbd174-8dfd-11e5-885f-f5a177c97b49.png)
![screenshot from 2015-11-18 14-04-04](https://cloud.githubusercontent.com/assets/10332628/11234784/e8de8c70-8dfd-11e5-8b9f-8a4601ddfc63.png)
![screenshot from 2015-11-18 14-05-30](https://cloud.githubusercontent.com/assets/10332628/11234786/e8e0c3f0-8dfd-11e5-9116-0df9f48f1dbf.png)
![screenshot from 2015-11-18 14-06-48](https://cloud.githubusercontent.com/assets/10332628/11234785/e8df484a-8dfd-11e5-90ad-73839b4314cf.png)

**Comment by tsteur** [comment]
Can you show a screenshot of a page that is not the last one?

Please be aware that in pages that are not the last we also show a "Time on page" metric and/or "Generation time". It might be a bit confusing. 

It looks like the page generation time of the last one is correct.

**Comment by minple** [comment]
![screenshot from 2015-11-19 13-03-28](https://cloud.githubusercontent.com/assets/10332628/11263521/f7c2ccc2-8ebd-11e5-8d47-336cbf4d0ddb.png)
![screenshot from 2015-11-19 13-08-10](https://cloud.githubusercontent.com/assets/10332628/11263580/9b6c8390-8ebe-11e5-8f06-acd888836335.png)

Sure, page is not the last, time is true.

No no, any pages of the last always has generation time is under 0. I visit my website, waiting a long time, generation time is under 0 at page of the last.

**Comment by tsteur** [comment]
Generation on time is always the same. What is > 1min is the time on page which is something different.

Generation time is the time it needs to generate the page on the server. Time on page is the time a user spends on the page. 

There is no time on page for the last entry as we don't know how long the user spent on this page as there is no following page.
