### ISSUE TITLE
Fatal error with APC

### ISSUE THREAD

**Issue by bronco0** [piwik/piwik#9225]
Hi,

When I turn on APC in php I get the following error in Piwik Version 2.15.0 :

`PHP Fatal error:  Call to undefined method ComposerAutoloaderInit3032eb0f643af862f66412785109e21c::getLoader() in /home/httpd_app/datas/var/www/html/piwik/vendor/autoload.php on line 7`

I tried to clear the cache with './console cache: clear' reboot or reinstall APC, anything, I always this error.

Thanks

**Comment by tsteur** [comment]
Did you install Piwik via git? 

If so, you possibly have to run something like `php composer.phar install --no-dev` again see http://piwik.org/faq/how-to-install/faq_18271/

If not, I'd recommend to download the files of the Piwik version you are using from  http://builds.piwik.org/ and copy them to your server. The instructions for this are in the  [manual three step update](http://piwik.org/docs/update/#the-manual-three-step-update)

**Comment by bronco0** [comment]
I installed piwik by achive version 2.15.0 from http://builds.piwik.org/.

I tried to reinstall piwik the same way but I still have the same problem when I APC active.

I did a update vendor with `php composer.phar install --no-dev`, still the same error.

**Comment by tsteur** [comment]
Does it work when APC is disabled? Which version of PHP are you using?

**Comment by bronco0** [comment]
Yes it work when APN is disabled.

PHP 5.4 from repository remi for RedHat/CentOS.
 - php-5.4.45-2.el6.remi.x86_64
 - php-pecl-apc-3.1.15-0.4.20130912.el6.remi.5.4.x86_64

`$ php --version`
PHP 5.4.45 (cli) (built: Sep 30 2015 15:56:06)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by tsteur** [comment]
Are there some other applications running on the same server? I reckon it must be some kind of APC misconfiguration. I think it's the first time I'm seeing such a problem. Maybe someone else has an idea?

Can you try to set the APC config setting 
```
apc.stat=1
apc.include_once_override=0
```

**Comment by mattab** [comment]
Not a Piwik bug.
