### ISSUE TITLE
 File integrity check failed and reported some errors.

### ISSUE THREAD

**Issue by themantripleman** [piwik/piwik#9233]
This was originally posted here: http://forum.piwik.org/t/file-integrity-check-failed/15786/2 but I was asked to post it here as well.

Some info: Hosting is through Dreamhost, PHP version 5.6.10, Piwik version 2.15.0, Piwik System Check gives all other system requirements green check marks.

I had tried using the 1 click upgrade process, it failed and broke my installation. Then I tried the command line, 3 step version:

```

$ wget http://builds.piwik.org/piwik.zip # download latest version
$ unzip -o piwik.zip # extract it to "piwik/" directory
$ rm piwik.zip # delete the archive and read below the next step

```

…which, you'd think, would bypass the "upload files in binary mode" issue.

The three terminal commands worked well with no errors. Nonetheless, when pointing my browser to my Piwik install, I still get:

> File integrity check failed and reported some errors. This is most likely due to a partial or failed upload of some of the Piwik files. You should reupload all the Piwik files in BINARY mode and refresh this page until it shows no error.

>```

>Missing file: /path/to/piwik/libs/bower_components/angular-animate/.bower.json
Missing file: /path/to/piwik/libs/bower_components/angular/.bower.json
Missing file: /path/to/piwik/libs/bower_components/angular-cookies/.bower.json
Missing file: /path/to/piwik/libs/bower_components/angular-mocks/.bower.json
Missing file: /path/to/piwik/libs/bower_components/angular-sanitize/.bower.json
Missing file: /path/to/piwik/libs/bower_components/chroma-js/.bower.json
Missing file: /path/to/piwik/libs/bower_components/html5shiv/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jquery/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jQuery.dotdotdot/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jQuery.dotdotdot/.gitignore
Missing file: /path/to/piwik/libs/bower_components/jquery-mousewheel/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jquery-placeholder/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jquery-placeholder/.gitattributes
Missing file: /path/to/piwik/libs/bower_components/jquery-placeholder/.gitignore
Missing file: /path/to/piwik/libs/bower_components/jquery.scrollTo/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jquery-ui/.bower.json
Missing file: /path/to/piwik/libs/bower_components/jquery-ui/.gitignore
Missing file: /path/to/piwik/libs/bower_components/jquery-ui/themes/.gitignore
Missing file: /path/to/piwik/libs/bower_components/jquery-ui/ui/.jshintrc
Missing file: /path/to/piwik/libs/bower_components/jScrollPane/.bower.json
...

```


It should be made clear, those files, of course, are actually there.

Would love to hear of a solution to this.

**Comment by mattab** [comment]
Hi @themantripleman 

Thanks for the report. This is a strange issue! 

Could you paste output of `ls -la /path/to/piwik/libs/bower_components/jquery-ui/themes/.gitignore` ? 

Just to confirm, you were able to install Piwik even with this issue correct?

**Comment by themantripleman** [comment]
OK, mea culpa.

Now that I look at it more closely, none of those files are there. When I originally searched for the files, I did not include the preceding dot.

Yes, you can curse my complete lack of knowledge. I hope that my error hasn't cost you too much of your time. 

I still have no idea why those files aren't there, though.

**Comment by mattab** [comment]
no problem. if update fails, let us know, I think it shouldn't fail

**Comment by themantripleman** [comment]
I went through and uploaded the missing files, there are no more errors.

Quick question though, shouldn't the three step, command line version of the update/install have included all of the dot files?
