### ISSUE TITLE
Enhanced Link Attribution feature

### ISSUE THREAD

**Issue by shenzhuxi** [piwik/piwik#9238]
https://support.google.com/analytics/answer/2558867?hl=en
In Google Analytics, Enhanced Link Attribution is for differentiating multiple links on a page that all have the same destination. 
It will be very useful for the page overlay in Piwik.

**Comment by mattab** [comment]
Thanks for suggestion @shenzhuxi - duplicates https://github.com/piwik/piwik/issues/5182
