### ISSUE TITLE
In 2.15 archiving parameter --force-date-last-n="11" have no effect if there are no new visits since midnight

### ISSUE THREAD

**Issue by sebastianpiskorski** [piwik/piwik#9239]
As in title I cannot force Piwik to archive data with parameter --force-date-last-n even if I have added new data for e.g. yesterday. I have to add at least one new visit to current day. Although --force-all-websites seems to work fine.

This occurs even if this is a fresh Piwik install. Without any archives and all tracking data is with dates before current day 00:00:00.

**Comment by tsteur** [comment]
Thx for reporting this issue!

**Comment by mattab** [comment]
@sebastianpiskorski could you try this patch which should fix this issue: https://github.com/piwik/piwik/commit/2615dd39340a981c282f37d72095b62e9b33f579

I'll merge it after you confirm it works for you. thanks!
