### ISSUE TITLE
Is php builtin server supported ?

### ISSUE THREAD

**Issue by maboiteaspam** [piwik/piwik#9242]
Hi,

I tried to start piwik with php built in server,

```
php -S 0.0.0.0:8000 -t tracking-system tracking-system/index.php
```

And i got that fail,
```
Warning: require(D:\work\TrackingSystem\tracking-system\vendor/facebook/xhprof/xhprof_lib/utils/xhprof_lib.php): failed to open stream: No such file or directory in D:\work\TrackingSystem\tracking-system\vendor\composer\autoload_real.php on line 58

Fatal error: require(): Failed opening required 'D:\work\TrackingSystem\tracking-system\vendor/facebook/xhprof/xhprof_lib/utils/xhprof_lib.php' (include_path='D:\work\TrackingSystem\tracking-system\vendor/pear/pear_exception;D:\work\TrackingSystem\tracking-system\vendor/pear/console_getopt;D:\work\TrackingSystem\tracking-system\vendor/pear/pear-core-minimal/src;D:\work\TrackingSystem\tracking-system\vendor/pear/archive_tar;D:\work\TrackingSystem\tracking-system\vendor/phpseclib/phpseclib/phpseclib;.;C:\php\pear') in D:\work\TrackingSystem\tracking-system\vendor\composer\autoload_real.php on line 58
```

Am i doing wrong ?
Is it supported ?

I could not find information about this in the documentation.

thanks.

edit: i should say that tracking-system/ contains piwik tree.

**Comment by maboiteaspam** [comment]
ok.. figured out it is a setup issue.  but not sure why...

**Comment by maboiteaspam** [comment]
OK.

For anyone elese passing around here 

```
composer install --no-dev
```

should make the trick.

**Comment by maboiteaspam** [comment]
last note, the built in server seems to work,
```
php -S 0.0.0.0:8000 -t tracking-system tracking-system/index.php
```
but i did not served the assets so far...

**Comment by maboiteaspam** [comment]
later found about this...
https://developer.piwik.org/guides/getting-started-part-1

Elle est infame cette doc les amis..

**Comment by mattab** [comment]
> Elle est infame cette doc les amis..

Tu pourrais peut etre nous aider en faisant un feedback constructif ? nous aimerions bien l'ameliorer

**Comment by maboiteaspam** [comment]
En un mot : eparpille. 
Du coup je ne sais jamais vraiment ou chercher pour telle ou telle information et me retrouve a chercher partout.

Dans l'immediat, le readme devrait contenir, selon moi, un genre d'exemple comme cela

## Install
```
wget piwik archive
mkdir piwik && cd piwik
unzip piwik archive
mysql start
php -S ....
open http://localost:piwik/
```
Suivit d'une note pour indiquer que le reste du setup sera realisee dans le navigateur, notamment la db.
Suivit d'une autre note vers le deploiement en production pour le tout venant comme fais ici http://piwik.org/docs/installation/, 
une note vers le redisqueue, config apache, nginx, et autres plugins dans la continuite de la procedure d'installation.

A minima pour installer, demarrer le logiciel rapidement et au passage pouvoir jeter un oeil sur le deploiement.

Par exemple cette page, http://developer.piwik.org/api-reference/tracking-javascript, meme si il n'y a pas l'information que je cherchais, elle donne le sentiment de regrouper l'information et d'etre un bon point de depart.

Ceci dit je comprends bien que la question est delicate dans la mesure ou celle ci doit s'adresser a differentes audiences, et que les sujets a aborder sont tres tres nombreux..

**Comment by mattab** [comment]
Decrire "comment setup Piwik" est le but de cette documentation: https://developer.piwik.org/guides/getting-started-part-1 - c'est fait pour les "developpeurs" qui veulent hacker sur Piwik.

Si tu veux juste installer c'est cette doc qu'il faut lire: https://piwik.org/docs/installation/

est ce que quelque chose n'est pas clair? si oui, quoi ?

**Comment by maboiteaspam** [comment]
Par exemple cette page https://github.com/scotch-io/scotch-box/issues

j'aurais bouger toute la partie plugin en bas, 
Dans la section setup, avoir un ide ou, mais en fait non, c'est l'install, pas un guide pour apprendre a coder.
Qu'on nous y parle des frameworks de tests, des multiples database disponible en debut de guide ect. me semble inadequat.

Que le guide se contente de nous emmener vers un setup minimal qui fonctionne.
Qu'ensuite il nous donne plus d'informations et des directions vers des topics connexes, parfait.

Autant je trouve tres agreable qu'en fin de setup on nous suggere et nous explique comment inserer des donnes de tests.
Autant l'install guide explique des gros basiques, mais fais l'impasse sur la raison des submodule init, alors que dans le Phe du dessus on nous indique que ces dependances sont optionnels (enfin, faut il encore que je clarifie cette partie pour moi meme nayant pas initialise les submodules).

En fait ce setup guide, c'est aussi un mini learn to code, mais aussi un get started to create your plugin guide ect on y trouve un peu de tout. 
Je pense que cela degrade la qualite d'acces a l'information.
