### ISSUE TITLE
Exact location of IP address is not deducted correctly

### ISSUE THREAD

**Issue by mstsolutions1** [piwik/piwik#9243]
Actually i viewed a website from in india that is not deducted properly. My ip address belongs to india but in report, i can see US flag and different IP address.
![ipadress](https://cloud.githubusercontent.com/assets/7480313/11297305/7e6883ea-8f9d-11e5-990d-9ec9f8c82f56.png)
![ip1](https://cloud.githubusercontent.com/assets/7480313/11297350/d884e8be-8f9d-11e5-8cc0-0a76fec3dd10.png)

**Comment by ieperlingetje** [comment]
It looks like the two last octets are removed for privacy reasons: https://piwik.org/docs/privacy/#step-1-automatically-anonymize-visitor-ips . That's also the reason I think why the geolocation fails.

**Comment by RMastop** [comment]
Looking at the data provided in the screenshot, no geolocation plugin is activated, or no geo location database is called while tracking.

By default piwik uses the language setting of the browser to decide what country to add in stats.

Thinking of it, it's actually kinda weird to do it like this. 
There shouldn't be any country reported based on language settings. 

Guess that would break some of the reports, but I think it is better to not report a country, than faking it.

One could fix these reports by using a geolocation database and connect it to the plugin.

How to do this? Check the following page:
http://piwik.org/docs/geo-locate/

**Comment by tsteur** [comment]
> Guess that would break some of the reports, but I think it is better to not report a country, than faking it.

+1 one for that. I created a new issue for this here: https://github.com/piwik/piwik/issues/9251

I will close this issue as it looks like either "IP anonymization is enabled and the anonymized IP is used for geo location" or no GEO provider is installed as @RMastop pointed out see http://piwik.org/docs/geo-locate/
