### ISSUE TITLE
ExampleTracker plugin doesn't delete its columns when uninstall

### ISSUE THREAD

**Issue by shenzhuxi** [piwik/piwik#9245]
ExampleTracker plugin added three columns to 3 tables, but didn't clear clean them after uninstall.

**Comment by tsteur** [comment]
How did you uninstall the plugin? In the UI I can only deactivate it, but not uninstall it.

**Comment by shenzhuxi** [comment]
I can't find the Uninstall link under Inactive now... facepalm
I guess that we need clean up in

class ExampleTracker extends \Piwik\Plugin
{
   public function uninstall()
}

**Comment by tsteur** [comment]
Dimensions are automatically uninstalled with the plugin, a plugin doesn't has to implement it specifically. As this is a plugin that comes with Piwik itself it cannot be uninstalled unfortunately. It would be installed again with the next Piwik update. The only way would be to drop the columns in the database manually and to disable the plugin. Be aware if you ever enable the plugin it might cause tracking errors if the columns in the database are missing.
