### ISSUE TITLE
Doubled meta robots tag

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9247]
Go to demo.piwik.org and check page source. This meta tag is defined there two times:
```
<meta name="robots" content="index,follow">
```

**Comment by quba** [comment]
https://github.com/piwik/piwik/blob/master/plugins/Login/templates/login.twig#L6-L8

I guess this one shouldn't be in the head block.

**Comment by tsteur** [comment]
FYI: This is only the case on the login page
