### ISSUE TITLE
Improve responsive layout header to use less space and look better

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9250]
My suggestion is to change this:

![before](https://cloud.githubusercontent.com/assets/11424829/11324050/b48305de-9125-11e5-94fe-5fc5b86dd632.png)

into this:

![after](https://cloud.githubusercontent.com/assets/11424829/11324051/b9fb584a-9125-11e5-8f7c-dac7abc8656f.png)

**Comment by tsteur** [comment]
Or maybe we make each selector full width similar to Piwik Mobile 1 http://piwik.org/wp-content/uploads/2012/09/device-2012-09-16-113810-400x666.png (without the graph in between) like 
![image](https://cloud.githubusercontent.com/assets/273120/11326168/0302399a-91c7-11e5-892a-9979de2816e1.png)

One challenge is when not having them full width that each selector may take a variable amount of space and the available width depends on the device. This makes it hard to position them next to each other or left aligned / right aligned next to each other.

We already have some icons in the UI to add a drawer/ right sidebar and we might display them in a right sidebar a bit similar to Piwik Mobile 2. In General we haven't really worked on the responsive version yet and there is a lot of work to do. Eg making buttons bigger etc. If you are using iOS or Android we recommend to use our app [Piwik Mobile 2](http://piwik.org/mobile/)

**Comment by mattab** [comment]
Thanks for suggestion @mgonera - we will go with @tsteur suggestion of showing one per line :+1:

**Comment by mattab** [comment]
It was reverted #9322

**Comment by mattab** [comment]
This was implemented in Piwik 3 :boom:
