### ISSUE TITLE
Provider not being shown in dashboard on hover over country flag.

### ISSUE THREAD

**Issue by tliitts** [piwik/piwik#9254]
Until several weeks ago now, when in the dashboard I hovered over the country flag, it would show me the provider as the rightmost field. Now, however, though the word "Provider" is there, no provider is ever shown. I'm using update 2.15.0, which it says is the current update.

The tracking code I'm using is:
var _paq = _paq || [];
_paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
_paq.push(["setCookieDomain", "*.terryliittschwager.com"]);
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
  var u="//terryliittschwager.com/analytics/";
  _paq.push(['setTrackerUrl', u+'piwik.php']);
  _paq.push(['setSiteId', 1]);
  var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
  g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
})();

**Comment by tliitts** [comment]
Using 2.15.0, which is says is the current update.

**Comment by tsteur** [comment]
Can you check if the Provider plugin is activated? You can do this by going to the Administration (settings icon top right) and by selecting "Plugins" in the left menu.

By "Dashboard" do you mean the "Visitors in real time"?

**Comment by tliitts** [comment]
That was the problem. I activated it and it is now working, showing
    the Provider in the Visitors in Real-time on hover over the country
    flag.
    
    Apologies for having submitted my lack of knowledge as a bug. Should
    I remove the bug report, or do you do that?
    
    Terry
      
      On 2015-11-22 18:28, Thomas Steur wrote:
    
    
      Can you check if the Provider plugin is activated? You can do
        this by going to the Administration (settings icon top right)
        and by selecting "Plugins" in the left menu.
      By "Dashboard" do you mean the "Visitors in real time"?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by tsteur** [comment]
No worries. We won't delete the issue but I'll close it. I'm glad it works now :+1:
