### ISSUE TITLE
document cookies, sessions requirements for tracking request

### ISSUE THREAD

**Issue by maboiteaspam** [piwik/piwik#9255]
Hi,

Looking forward to know if the server is writing, either cookies or session, to the client when a tracking request occur.

In my reading, so far, i found out that the job was done in the javascript tracker implementation.

This said, the software is pretty huge and have many plugins, thus i find it difficult to get an overview.

Is there any guideline, reference or document about that ?
Is the server allowed to store session values, is the server allowed to write cookies on the client during a tracking request processing ?

thanks !

**Comment by mattab** [comment]
Hello,

please use forums to ask questions. See also: https://piwik.org/faq/general/faq_146/

**Comment by maboiteaspam** [comment]
hi,

Ok. 

If i m right, so called "first party cookies" are set from the JS.

And if you want to enable tracking across multiple site, a "third party cookie" is set from piwik.php.

So in 
```
To track visitors, Piwik by default uses 1st party cookies, set on the domain of your website. Cookies created by Piwik start with: _pk_ref, _pk_cvar, _pk_id, _pk_ses.
```
At https://piwik.org/faq/general/faq_146/

It s about the piwik JS, right ?

thanks
