### ISSUE TITLE
When pk_campaign = (utm_campaign =) is used, which is utf-8, string will cut 70 "bytes" without boundary.

### ISSUE THREAD

**Issue by piwikjapan** [piwik/piwik#9257]
PHP's function substr calls unreadable characters, because it cuts multibyte characters without boundary. And mysql varchar has a number of multibyte characters - not bytes.

**Comment by piwikjapan** [comment]
Please see the pull request https://github.com/piwik/piwik/pull/9259 .

**Comment by mattab** [comment]
fixed in #9259
