### ISSUE TITLE
Allow to profile all archiving subrequests:  forward PHP CLI parameters to CLI subrequests

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9258]
It looks like currently it's not possible to profile the whole archiving process by using --xhprof flag. After a few tests, I noticed that archiving process generates profiles only for:
- the main archiving process,
- daily archiving (without segments),
- scheduled tasks.

Currently the workaround is to trigger archiving via `./console climulti:request -q  --superuser "<archiving subrequest>&xhprof=2`. For instance, this allows me to create a profile for a specific segment with a `month` period.

Additionally, it would be nice to forward PHP CLI parameters to archiving subrequest. E.g. I'd like to be able to trigger archiving with -dmemory_limit=8G flag. Currently, it's inconvenient to change PHP setting every time I want to profile some memory-expensive process.

**Comment by mattab** [comment]
> Additionally, it would be nice to forward PHP CLI parameters to archiving subrequest. 

:+1: this makes sense.

This was also suggested in #9074 by @rfnx

> Here is the command line I want to use :

> php -d extension=pdo_mysql.so -d extension=gd.so -d extension=iconv.so -d extension=openssl.so -f /path/to/piwik/console core:archive --url=https://analytics.mydomain.com/

> But I get this error :

> Empty or invalid response 'Error in Piwik: The mysql driver is not currently installed The mysql driver is not currently installed ' for website id 1, Time elapsed: 0.264s, skipping

**Comment by rfnx** [comment]
@mattab Is there any news on this issue ? Do you need someone to try to fix this ?

**Comment by mattab** [comment]
@rfnx for sure it would be very helpful if you manage to fix it / submit a pull request :-) we are very grateful for any help!

**Comment by rfnx** [comment]
@mattab I tried to look at the code but it is very hard for me because I don't know it.

But I found something interesting : If I'm not wrong, the cron mainly uses the file https://github.com/piwik/piwik/blob/master/core/Console.php .  At https://github.com/piwik/piwik/blob/master/core/Console.php#L31 and then https://github.com/piwik/piwik/blob/master/core/Console.php#L135 we can see that command line args are only used if php isn't loaded in CLI mode.

Can someone who knows this code better can look at it ?

**Comment by quba** [comment]
Would be also nice to forward `vvv` parameter (in case it's possible to output more for all subrequests). Just an idea.

**Comment by tsteur** [comment]
Do you mind creating a new issue for this one? It's not as trivial as the other changes and requires some kind of refactoring

**Comment by tsteur** [comment]
I will close this one for now as I was just waiting for the other 2 to be merged, forgot to close it since I wasn't sure which PR would be merged faster
