### ISSUE TITLE
Branding Images can not be uploaded

### ISSUE THREAD

**Issue by szediwy** [piwik/piwik#9261]
I try to upload my own logos when following error occurrs:
```php
PHP Fatal error:  Call to undefined function Piwik\\Plugins\\CoreAdminHome\\imagecreatefrompng()
```

Version: 2.15.0

**Comment by tsteur** [comment]
You need to install GD extension (`GD > 2.x + Freetype (graphics)`). You will probably see that the extension is missing when going to "Administration => System Check". Also see http://piwik.org/faq/troubleshooting/#faq_34

@mattab should we maybe only show the upload feature when GD is installed? If not please close this issue :)

**Comment by mattab** [comment]
Added FAQ instead: [ I get: PHP Fatal error Call to undefined function imagecreatefrompng() ](https://piwik.org/faq/troubleshooting/faq_21082/)
