### ISSUE TITLE
Forward currently selected segment to overlay row action

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9264]
When there is a segment selected in the dashboard and someone clicks on the Overlay row action feature, we should forward the currently selected segment to the overlay. 

Note: An Action Custom Dimensions subtable defines a segment in the row as well. In this case we'd have to connect both segments via boolean operator "and" (`;`)

**Comment by mattab** [comment]
:+1: this will fix #9256

**Comment by tsteur** [comment]
This is not implemented btw and I am not working on this

**Comment by mattab** [comment]
duplicates https://github.com/piwik/piwik/issues/9256
