### ISSUE TITLE
Create a Media Player Analytics for Piwik plugin in the Marketplace

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9265]
Our mission is to help everyone liberate and keep control of their data. A big part of the Internet is playing videos content. In this issue, we will give for free to every Piwik user, a plugin that lets you measure your videos. 

### Review and release the MediaPlayer plugin

Steps:

 * [ ] Review code, architecture, tests, readme
 * [ ] Review new screens, reports, usability
 * [ ] Test on HTML5 video
 * [ ] Write & publish user guide on https://piwik.org/docs/
 * [ ] Write & publish FAQ `How do I measure media video players activity with Piwik?`
 * [ ] Release plugin to Marketplace
 
This will fix https://github.com/piwik/piwik/issues/7551

**Comment by sbaconnais** [comment]
Hello, any news about this plugin ? I'm really interested in it :)

**Comment by tsteur** [comment]
As there is no pull request, what is the best way to give feedback?

**Comment by mattab** [comment]
@tsteur would it be maybe possible to create a pull request against an empty branch or so, for the benefit of reviewing code?

**Comment by tsteur** [comment]
Yes that would be possible. Ideally one of the developers would do that so they get the feedback via email etc.  @andrzejewsky @sebastianpiskorski what do you think? Do you mind creating a PR?

**Comment by tsteur** [comment]
FYI: A manual on how to do this is mentioned here: http://astrofrog.github.io/blog/2013/04/10/how-to-conduct-a-full-code-review-on-github/  see "If the first commit is important..."

**Comment by tsteur** [comment]
PR is https://github.com/PiwikPRO/plugin-MediaPlayer/pull/15

**Comment by sbaconnais** [comment]
Your  link is dead :P

**Comment by tsteur** [comment]
I guess the plugin is still private from the looks. Gonna change soon I reckon

**Comment by sbaconnais** [comment]
I can help for beta testing if you want.

**Comment by tsteur** [comment]
Finished reviewing. I don't think any work will happen on applying some changes very soon so I guess best is to move it to 2.16.1 

@sbaconnais thanks for that! I presume the repository will be made public once some changes are done to the plugin as it is not yet ready to be used for testing

**Comment by mattab** [comment]
@tsteur Nice - Moving this issue to 2.16.1 as it won't block our 2.16.0 release (the plugin will not require changes in core so we can release it publicly after our 2.16.0 release)

**Comment by MARK-BAIN** [comment]
Hi mattab, any update on the plugin ? I'm also looking forward to embed it for our videos and audio files

**Comment by mattab** [comment]
No update, hopefully in Feb or March we will release it. Stay tuned

**Comment by sajkec** [comment]
Any update, possible demo code?

**Comment by andrzejewsky** [comment]
@sajkec Recently, we discussed about this feature and we are currently working on it. We will let you know if some demo/beta will be available.

**Comment by nerbix** [comment]
Same question as above -- any ETA for beta testing?

**Comment by elgrafico** [comment]
I'd really love to see that happen - any updates?

**Comment by mattab** [comment]
Hi guys, I am not sure what is the status here. This plugin has been worked on for more than one year by Piwik PRO but it has not been released yet. Maybe someone else will need to create this plugin :+1:

**Comment by mojowill** [comment]
Did this ever see the light of day? Very interested in this, especially the JwPlayer integration.

**Comment by ReessKennedy** [comment]
If the PIWIK PRO team has stalled the development on this, I am willing to collaborate on building it with some of you in this thread. Message me if interested.

**Comment by JonnyHeavey** [comment]
I'm still very interested in this feature, is there an update on progress or if help is needed?

**Comment by elgrafico** [comment]
In the meantime, the plugin seems to have been realised as a paid option: https://plugins.piwik.org/MediaAnalytics

**Comment by tsteur** [comment]
Indeed, it was released it a day ago or so. More information is also available here: http://www.media-analytics.net/   The plugin gives useful insights into media / video / audio analytics and adds many new reports, widgets and segments to Piwik.

**Comment by tsteur** [comment]
Works with HTML5 video & audio, Vimeo and YouTube out of the box. Support for other players can be added easily and is documented in the [developer docs](https://developer.piwik.org/guides/media-analytics). After installation the plugin will in most cases directly start tracking data see the [setup](https://developer.piwik.org/guides/media-analytics/setup) guide

**Comment by bigretromike** [comment]
> Our mission is to help everyone liberate and keep control of their data. A big part of the Internet is playing videos content. In this issue, we will give for free to every Piwik user, a plugin that lets you measure your videos.

I'm interested in that FREE to every piwik/matomo user experience - but I only see the payed version, where can I found the FREE one ?

**Comment by tsteur** [comment]
@bigretromike there is no free version of it.
