### ISSUE TITLE
In Popover, show the full title in a tooltip on hover on the title

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9266]
Sometimes popover are created with very long titles, [for example here with Firefox](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Referrers&action=getSearchEnginesAndKeywords&idSite=7&period=day&date=yesterday&popover=RowAction$3ASegmentVisitorLog$3AReferrers.getKeywords$3AreferrerType$253D$253Dsearch$253BreferrerKeyword$253D$253Dcannot$252Buse$252Boutput$252Bbuffering$252Bin$252Boutput$252Bbuffering$252Bdisplay$252Bhandlers$3A$257B$257D)

Let's display a tooltip, on hover on the title of all popovers, that show the full title.

![truncated](https://cloud.githubusercontent.com/assets/466765/11356750/b02fad4c-92c5-11e5-98d8-8658c9abdad5.png)

**Comment by tsteur** [comment]
Just FYI: This won't be easy as we possibly need to modify jquery etc.
