### ISSUE TITLE
Get rid of file_get_contents everywhere, also in tests

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#9269]
There still [many portions of code using **file_get_contents()**](https://github.com/piwik/piwik/search?utf8=%E2%9C%93&q=file_get_contents), running tests using Proxy behind my company's firewall gives me back warnings. :warning: 

This function ignores proxy configuration, I think shouldn't be used no more because storically [there are plenty of issues against it](https://github.com/piwik/piwik/issues?q=is%3Aissue+is%3Aclosed+file_get_contents+sort%3Aupdated-desc) :fearful: 

This is a minor Issue because outputs only warnings in console (tests skipped, I suppose). It happens also if you try to write your own IntegrationTests while developing plugins.

**Comment by mattab** [comment]
:+1: we should use our `Http::sendRequest` method instead (which uses the configured proxy). @tassoman a pull request would be very welcome!

**Comment by tassoman** [comment]
I'll do my best! Looks like I can do it :surfer:

**Comment by tassoman** [comment]
Well, looking deeper looks like file_get_contents in tests is correctly used for fetching inside local file system. So doing a *Http::sendHttpRequest($thing, $timeout)* here is wrong. 
This issue looks like a nevermind thing. 

But my doubt still here, the question is: why while I'm running my plugin's Unit Tests, Piwik's console Runs also Referers Plugin's unit tests [looking for missing file](https://github.com/piwik/piwik/blob/master/plugins/Referrers/tests/Unit/SearchEngineTest.php?r107#L107) /home/systemuser/path/to/piwik/vendor/piwik/searchengine-and-social-list/SearchEngines.yml ?

**Comment by mattab** [comment]
@tassoman you need to run `composer install` to remove this error

**Comment by tassoman** [comment]
Crazy! I forgot running ```composer update```, do you think would be useful adding a check in the console command while it's in developer mode? 

That check could manage local composer's update timestamp displaying a CLI warning message if it feels composer not enough updated ...

Or it's simply the best practice :green_book:  starting each day with:

```shell
$ composer selfupdate
$ composer global update
$ composer update
```

:smile:
