### ISSUE TITLE
Issue after new JS release?

### ISSUE THREAD

**Issue by alwyndeB** [piwik/piwik#9270]
Dear Piwik,

we are having issues on our site vvaa.nl using de piwik.js where a symbol is not difined. on row 67 colom 1070
This is also having issue publishing content of our CMS. Has there been any changes on your side which have led to this?

![image](https://cloud.githubusercontent.com/assets/15997869/11365195/0d86ead0-92a5-11e5-9724-c8e2ca29267e.png)

**Comment by tsteur** [comment]
@quba @andrzejewsky can you have a look at this? Seems to be the MediaPlayer plugin

**Comment by alwyndeB** [comment]
Dear thomas

Piwik pro had a look and sent me this mail and the problems have disappeared for now

Hello Alwyn De,
I'm sorry for the inconvenience.
Can you please try again and confirm if the problem still exist?
Please do not hesitate to ask if you have any questions or problems.
Regards,


--
Michał Tomczak
Piwik Support Specialist

Met vriendelijke groet,
VvAA Groep B.V.

A. (Alwyn) de Bruijn
Webbeheerder
06 573 351 91<tel:06%20573%20351%2091>
alwyn.de.bruijn@vvaa.nl<mailto:alwyn.de.bruijn@vvaa.nl>

www.vvaa.nl<http://www.vvaa.nl/>, Orteliuslaan 750,
Postbus 8153, 3503 RD Utrecht


-------- Oorspronkelijk bericht --------
Van: Thomas Steur <notifications@github.com>
Datum:24-11-2015 21:37 (GMT+01:00)
Aan: piwik/piwik <piwik@noreply.github.com>
Cc: "Bruijn, Alwyn de" <alwyn.de.bruijn@vvaa.nl>
Onderwerp: Re: [piwik] Issue after new JS release? (#9270)


@quba<https://github.com/quba> @andrzejewsky<https://github.com/andrzejewsky> can you have a look at this? Seems to be the MediaPlayer plugin

**Comment by tsteur** [comment]
Thank you for letting us know. I will close this issue
