### ISSUE TITLE
Piwik "white screen death error php" stack trace

### ISSUE THREAD

**Issue by anvar-kuchkartaev** [piwik/piwik#9273]
I'm providing content of error_log file of my apache web server in Oracle Linux 6.7 distribution
(I've not installed piwik yet only downloaded and extracted to docroot and getting error 500)

[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP Catchable fatal error:  Argument 1 passed to DI\\Definition\\Resolver\\AliasResolver::__construct must be integer, object given in /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/AliasResolver.php on line 35
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP Stack trace:
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   1. {main}() /var/www/html/piwik/index.php:0
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   2. require_once() /var/www/html/piwik/index.php:27
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   3. Piwik\\Application\\Environment->init() /var/www/html/piwik/core/dispatch.php:28
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   4. Piwik\\Application\\Environment->validateEnvironment() /var/www/html/piwik/core/Application/Environment.php:94
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   5. DI\\Container->get() /var/www/html/piwik/core/Application/Environment.php:184
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   6. DI\\Container->resolveDefinition() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Container.php:122
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   7. DI\\Definition\\Resolver\\ResolverDispatcher->resolve() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Container.php:285
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   8. DI\\Definition\\Resolver\\ObjectCreator->resolve() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:60
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP   9. DI\\Definition\\Resolver\\ObjectCreator->createInstance() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php:79
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  10. DI\\Definition\\Resolver\\ParameterResolver->resolveParameters() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php:156
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  11. DI\\Definition\\Resolver\\ResolverDispatcher->isResolvable() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ParameterResolver.php:82
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  12. DI\\Definition\\Resolver\\ResolverDispatcher->getDefinitionResolver() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:73
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  13. DI\\Definition\\Resolver\\AliasResolver->__construct() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:114
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  14. Piwik\\ErrorHandler::errorHandler() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:35
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  15. Piwik\\Log::warning() /var/www/html/piwik/core/ErrorHandler.php:99
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  16. Piwik\\Log::logMessage() /var/www/html/piwik/core/Log.php:142
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  17. Piwik\\Log::getInstance() /var/www/html/piwik/core/Log.php:225
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  18. Piwik\\Container\\StaticContainer::get() /var/www/html/piwik/core/Log.php:94
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  19. DI\\Container->get() /var/www/html/piwik/core/Container/StaticContainer.php:80
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  20. DI\\Container->resolveDefinition() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Container.php:122
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  21. DI\\Definition\\Resolver\\ResolverDispatcher->resolve() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Container.php:285
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  22. DI\\Definition\\Resolver\\ObjectCreator->resolve() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:60
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  23. DI\\Definition\\Resolver\\ObjectCreator->createInstance() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php:79
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  24. DI\\Definition\\Resolver\\ParameterResolver->resolveParameters() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php:156
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  25. DI\\Definition\\Resolver\\ResolverDispatcher->isResolvable() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ParameterResolver.php:82
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  26. DI\\Definition\\Resolver\\ResolverDispatcher->getDefinitionResolver() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:73
[Tue Nov 24 17:12:19 2015] [error] [client 46.222.143.228] PHP  27. DI\\Definition\\Resolver\\AliasResolver->__construct() /var/www/html/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php:114

**Comment by tsteur** [comment]
Which version of Piwik and PHP are you using?

**Comment by anvar-kuchkartaev** [comment]
2.15.0 piwik version
php-5.6.15-1.el6.remi.x86_64 php version
more information about php visit https://anvartay.com/phpinfo.php
username php
password php

**Comment by tsteur** [comment]
Thank you. Where did you download the release from? From the https://piwik.org website? Do you think it would be maybe possible to get access to the server to debug the problem? I'm a little clueless here. If so, maybe send us an email to hello at piwik.org

**Comment by anvar-kuchkartaev** [comment]
Thanks for your help but credentials are only for viewing php versions link will run only
<?php
phpinfo();
?>
as the security reasons I cannot make this code open everyone... I'm running php from remi repository that can override default php packages with latest php version and I run out from compiling php with my hand. I've installed php php-pear php-pecl php-ZendFramework2 php-symfony and a lot of php packages because this server maintained by me runs a lot of websites. But I've tried to run older piwik versions I've downloaded it from official website of course but same problem I'm getting... I got white screen in another application called owncloud on the same server, there was the problem I got php-mysqlnd and php-pecl-mysql package together and after I've erased php-pecl-mysql owncloud started working. That time owncloud was the only one application on my server but now I've a lot of applications so I cannot erase packages one by one to see if there is the conflict... or it is the piwik have internal errors... I'm not familiar with php I'm familiar building and maintaining servers and their security so I cannot debug it... Can you help me to find this bug...

**Comment by tsteur** [comment]
Making code open to everyone is not needed. If it's possible for you to send us credentials to your server via email to hello at piwik.org we can debug the problem. It could be a new user for us and afterwards delete the user again to prevent further access. I can't really help here as it's hard to tell what the problem could be. Maybe someone else has an idea? or maybe you know someone with PHP experience who can debug it?

**Comment by mattab** [comment]
Not heard from user since. Please open new issue if you still experience a problem with latest Piwik.
