### ISSUE TITLE
Make transitions faster for all Piwik users: add more INDEX  to database

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9276]
Goal of this issue is that, for new Piwik users, we should add more INDEX to the database schema, in order to make Transitions very fast to render.

This issue has been documented for years in the Piwik FAQ: [ How do I make “Transitions” feature work faster on high traffic websites?](https://piwik.org/faq/how-to/faq_161/) 

But it is uncomfortable situation for users:
 * one has to notice transitions is slow  (which is annoying and bad user experience)
 * one has to think "maybe there is a solution to make this faster?"
 * then one has to look in FAQ and find this one: https://piwik.org/faq/how-to/faq_161/
 * then one has to ask sysadmin to execute long and cumbersome SQL queries (that can take hours or days on big databases)

By adding these INDEX for New users in Piwik, we will prevent this issue forever.

For existing Piwik users, we need to decide if:
 * we add the INDEX during the upgrade to 3.0.0 (recommended!)
 * or instead we could add a System check entry "Has the transitions INDEX been setup?" or so

**Comment by theyosh** [comment]
Hi,

as adding indexes will take a lot of time if you have a big database, this should not be applied automatically. Adding indexes can always be done afterwards. Without the indexes it still works, but slow. So the system is not hanging or not working without the indexes. It is just slow.

As I have a large setup, I would like to execute the index SQL statements through console. And also when it suits me. So I would add this information, and the SQL statement somewhere in a system overview page.

For new setups, just add the indexes to the install SQL file.

**Comment by tsteur** [comment]
As discussed closing this issue as it is not super slow for most sites but would make tracking slower. FAQ explains how to add the indexes if there are problems. We might reopen this later and add the indexes
