### ISSUE TITLE
problem after upgrade 2.2.0 -> 2.15.0 and specific dual setup

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#9282]
Hi, I am experiencing some issues with angular.js and 403 access forbidden, so the top menus with date etc. are not displaying in first domain (website comes with 2 unique domains, tracked as one).

Setup:

>domain # 1 + own piwik installation + js tracking code A => one common database (issue below)
>domain # 2 + own piwik installation + js tracking code B => one common database (working fine)

Same server, database, php, browser, everything. All visits are tracked together, there are no 2 different installations technically (except on the file sys level). Everything was working fine with 2.2.0 versions, until yesterday when I decided to upgrade.

The complex setup was done to avoid issues with cross-domain scripting protection and firewall used in my hosting. Also, for historical reasons, once they were a single domain, now separated. No separate prefixes in db, just to be clear.

Screnshoot:

![piwik-toolbar](https://cloud.githubusercontent.com/assets/5383059/11415952/656baa28-9409-11e5-944f-16b965a7be39.png)

Console:

![piwik-console-errors](https://cloud.githubusercontent.com/assets/5383059/11424615/e25838b8-944e-11e5-840b-ac29e87d90bd.png)

After the upgrade was performed via domain # 2 (and database was updated from there), when I visit domain # 1/piwik, the above 403 and issue with angular occurs, generating thousands of repetitive/cycling errors in console. domain # 2/piwik is working perfectly fine. Files were unzipped directly on the server multiple times, and checked offline via d/l, everything matches (except different configs), so that is not the issue.

Also interesting, when I try from admin to edit Websites table, and add multiple domains in new lines, it now does not work properly, it replaces the domain # 1 with domain # 2 cloned version. Only way I can do this is to restore it directly in database. But, now does not make any difference, anyway.

Re-installation on domain # 1 is not gonna solve this, when I temporarily renamed config, angular.js still failed to load on setup pages.

```
"..." is domain # 1

GET http:// ... /403.php 403 (Access Forbidden)(anonymous function) @ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:191s
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:186f
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:183J
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:213J
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:213(anonymous function)
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:214h.$eval
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:225h.$digest
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:222h.$apply
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:225(anonymous function)
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:130d
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:147c
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:130dc
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:130Wc
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:129(anonymous function)
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:328j @ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:4k.fireWith
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:4m.extend.ready
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:4J
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:4
index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:204

Error: [$compile:tpload] http://errors.angularjs.org/1.2.28/$compile/tpload?p0=plugins%2FCoreHome%2F…ctor%2Fsiteselector.directive.html%3Fcb%3De75ca39379e91361b8a9f29d815e9f82
    at Error (native)
    at http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:118:450
    at http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:173:148
    at http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:184:286
    at w (http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:213:167)
    at w (http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:213:167)
    at http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:214:428
    at h.$eval (http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:225:32)
    at h.$digest (http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:222:117)
    at h.$apply (http:// ... /piwik/index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:225:362)(anonymous function)

@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:204(anonymous function)
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:180w
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:213w
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:213(anonymous function)
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:214h.$eval
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:225h.$digest
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:222h.$apply
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:225m
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:184w
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:189B.onreadystatechange
@ index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:191
index.php?module=Proxy&action=getCoreJs&cb=e75ca39379e91361b8a9f29d815e9f82:191
```

Errors infinitely repeats afterwards several times per second. Why is it 403 forbidden on this domain (when it points to it, not the other one), and works fine on second domain?

I mean, it is not such a big deal in the end, both domains access and reads same data, only I am curious why in the first domain # 1 scripts w date selection are not loaded, and some settings in admin pages which depend on those scripts.

Diagnostics shows couple of performance issues, nothing related.

What could be wrong with 2.15.0 and this setup? Why it was fine in old version?
Thanks

**Comment by tsteur** [comment]
Did you change something in your server configuration? It rather looks like a problem with your server maybe? Can you check your webserver error logs to see if it gives you more details about the error?

**Comment by dev-101** [comment]
Hi, the setup is on a shared hosting and nothing was changed during/after upgrade. The only suspect could be the firewall, but than it should affect both sites. No clues in logs...

**Comment by tsteur** [comment]
When you say one common database do you mean they also use the same database table prefix, meaning the very same database? What we do support is Piwik in a load balanced environment: http://piwik.org/faq/new-to-piwik/faq_134/ which is similar to your setup. If the config files on both servers are same it should work. Maybe also have a look here: http://piwik.org/faq/troubleshooting/faq_18485/ 

From the looks there are static files blocked which means there seems to be some kind of server configuration issue, eg firewall. Piwik itself does not return any 403 status codes, meaning the server seems to do forbid the access for some reasons.

Feel free to send us a link with access to your Piwik installation via email to hello at piwik.org if possible and I'll have a quick look if I can find something. You could create a new user with "View" access only and delete the user afterwards again. Otherwise we possibly have to close this issue since it seems unrelated to Piwik even though it is strange since it occurred after the Piwik update

**Comment by tsteur** [comment]
One thing to try would be to compare whether both servers contain the same files. Eg download the Piwik directory from both servers, clear the `piwik/tmp` directory and compare the content with a `diff` tool or so. Maybe server one is missing something

**Comment by dev-101** [comment]
tsteur: When you say one common database do you mean they also use the same database table prefix, meaning the very same database?

Hi, yes, already wrote it in opening post:

> No separate prefixes in db, just to be clear.

Anyway, I was busy with some other work, my idea is to investigate which files are contacted outside and if I can move them locally, satisfying firewall and Piwik, at the same time. But, as I already said, this is not a big deal as long as at least one installation works fine 100%, just accessing through 2nd domain instead of 1st.

Thanks
