### ISSUE TITLE
tiny: 2.15.1b5 dashboard/widget/entry pages does not use label

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9283]
tiny: 2.15.1b5 dashboard/widget/entry pages seems not to use label
please see attachment
![2015-11-26_07h12_20](https://cloud.githubusercontent.com/assets/5681880/11416375/622ff23e-940d-11e5-9667-21e0621d420a.png)

**Comment by tsteur** [comment]
FYI: This is the Insights report (took me a while to be able to reproduce it). It's also happening with Beta 3 on demo.piwik.org. Might be not a new regression in 2.15?

**Comment by tsteur** [comment]
Quickly tried to fix it but not sure why it doesn't work anymore. It seems like it never worked for this report possibly. Problem is `metricName` is not translated in DataTableMetadata in https://github.com/piwik/piwik/blob/master/plugins/Insights/InsightReport.php#L222-L224 There is no report metadata translation for metric `nb_visits` as report metadata contains translations for `entry_nb_visits` and `entry_bounce_count` (which is correct).

`nb_visits` has always been hard coded here I think: https://github.com/piwik/piwik/blob/2.15.0/plugins/Insights/API.php#L207

@hpvd do you know if it worked in 2.14?

**Comment by hpvd** [comment]
thanks!
hmm do not know exactly when it appears: saw it the first time today...

**Comment by tsteur** [comment]
Actually, I'll replace the label `regression` with `bug` since I can't see how it ever worked :) @mattab I'll also unassign the milestone

**Comment by hpvd** [comment]
seems to be solved.
