### ISSUE TITLE
Links from piwik webpages: add campaign data

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9284]
Some piwik users uses very often the links from piwik to webpage.
An idea for an easy way to identify them (and keep statistics clean)
is using campaign tracking possibilities and include some special campaign data to all outgoing links.

With this one can keep statistics clean, even if they did not enable to not track themselves, which is very common because
- not know about this possibility
- of browser cleaning
- using different browsers/devices and not all are setup right...

**Comment by tsteur** [comment]
Maybe if one doesn't want to track own usage rather exclude all your visits via cookie or IP?

**Comment by hpvd** [comment]
sure this works for me.
The problem is, if there are several users in one piwik installation, and each one maybe uses 1-3 different browsers and do some "browser cleaning" from time to time.
In addition they work in office and also at home or mobile (no static IP)

So it's only a question of time till something goes wrong and you track your own people.

Having the possibility to always attach campaign data nothing can go wrong anymore...

**Comment by mattab** [comment]
Thanks for the suggestion @hpvd this could be done as a third party plugin. By default we couldn't modify URLs as it may break the URLs and the website.
