### ISSUE TITLE
Making features with high performance demand possible

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9289]
Some ideas for features would be **great, but they may stress a piwik server.**

This ticket is about **making it possible to implement these features** and giving ideas
why "performance reasons" shouldn't be a blocker.

A) **Some reasons why "performance reason" it's not always a "killer"** and why and how one can deal with it:

1) piwik is very often used on pages with very low traffic

2) one did not need all information on load of a page so one can display it when it's ready

3) performance of server hardware is growing very fast (Multicore CPU, tons of RAM, SSD, PCIe-NVME SSDs...)

4) Performance of software grows, e.g. PHP 5.6 => 7.0

5) sometimes one do not need the very exact number:
- so one can "Stop counting" after a special amount of time and show something like "1000+"
- one can reuse numbers
- one can preindex values (on times when there is low server load)

6) data could often be (re-)used on several places

7) one can implement a **switch in settings to activate all things which are great but power consuming** (for users with a good quotient of vistors/server power and backend user/server power)

8) one can cut the worst case: do not show if segment is  "all visits"

9) ...

I'm no developer, but probably there are several more ideas to work with power demanding tasks in general...

This is an extract of write up https://github.com/piwik/piwik/issues/9110

B) of course not a solution but **a demonstration**, that others are working with perfect performance too (e.g. counting number of entries)
Yes of course it looks unfair because google has other "resources", but they also have other amounts of data to deal with ;-)

![2015-11-26_06h49_38](https://cloud.githubusercontent.com/assets/5681880/11425250/c6fb38a4-9453-11e5-8e2d-9e0df1a2ee80.png)

C) Would be good to have some kind of **best practise guide for working on performance relevant things** within piwik.

D) Would be good to have a **new label for issues of type: "performance demanding"**
so every one discussing or working on this issue is aware to take care for this

E) This is a list of **things which were already dropped** because of not possible because of performance reasons - maybe one can revise them again

1) https://github.com/piwik/piwik/issues/9110

F) This is a list of all issues where **performance should be observed**:

1) https://github.com/piwik/piwik/issues/9110
2) https://github.com/piwik/piwik/issues/9109
3) https://github.com/piwik/piwik/issues/8942
4) https://github.com/piwik/piwik/issues/8785
5) https://github.com/piwik/piwik/issues/8225

**Please add all your ideas and findings to A)...F)**

**Comment by tsteur** [comment]
BTW: There is also https://github.com/piwik/piwik/issues/6759 where we worked on some tweaks. Some of those issues might be actually not such a big deal anymore (I haven't looked at the one you mentioned yet).

**Comment by mattab** [comment]
Hi @hpvd I'm not sure what this issue is about, as it references other issues. if you have specific new suggestions please create one issue for each
