### ISSUE TITLE
Google Chrome Opt-Out problem when connectiong to Piwik via ssl proxy

### ISSUE THREAD

**Issue by ggeorgg** [piwik/piwik#9290]
Hey!

I've got a problem with the piwik opt-out function in chromium.

I've installed Piwik (version 2.15.0) on piwik.domain1.de with force_ssl=1 in config.ini.php

I use the opt-out iframe on a domain2.de with 
<iframe style="border: 0; height: 250px; width: 100%;" src="https://ssl-account.com/piwik.domain1.de/index.php?module=CoreAdminHome&amp;action=optOut&amp;language=de"></iframe>

In IE and Firefox it is possible to set the opt-out cookie. In Chromium a new tab is opend and closed by clicking the opt-out feature (like in the other browsers), but there is no cookie set in chromium.

Don't know if this is a bug, but I would be pleased if you could help me.

**Comment by tsteur** [comment]
Can you maybe send us a URL to reproduce it? Feel free to send it to us via email to hello at piwik.org so it won't be public.

**Comment by ggeorgg** [comment]
Just sent a mail to the mentioned address. 

The version of my Google Chrome installation is 46.0.2490.86 m just in case it is important.

**Comment by ggeorgg** [comment]
Can someone reproduce this? Or is is a missconfiguration of my Google Chrome?

**Comment by tsteur** [comment]
I tried to reproduce it and can confirm it doesn't work. It works though when I send the request as GET to Piwik manually (the request that is usually triggered via POST by clicking on the checkbox). 

I just had a look again and noticed it does not use the same domains. The iframe for the opt-out uses a different domain (what you mentioned with domain2.de) and it must be somehow related to this. I think it should at least set a cookie on that domain but it doesn't. 

I have an idea what could cause it but am not sure. Can you temporarily change this line https://github.com/piwik/piwik/blob/2.15.0/plugins/CoreAdminHome/OptOutManager.php#L183 with `if ($nonce !== false) {` and check if it works then? It might be either a missing configuration of Piwik or actually a bug in Piwik. Not sure yet :)

**Comment by ggeorgg** [comment]
I just changed the line, tried to set the opt-out cookie again with Google Chrome and it works now!
So is this second check for security reasons or can I just leave the changed line now like it is?

Thank you so far!

**Comment by tsteur** [comment]
Yes, it should be there for security reasons. Can you have a look at your `config/config.ini.php` file in your Piwik installation for entries starting with `trusted_hosts[] =` whether the domains / hosts you are listed?

**Comment by ggeorgg** [comment]
Currently I have got the following section in my config/config.ini.php.
The first two lines of trusted_hosts were already there after installing piwik. I added the other three lines by myself but I am not sure which of these lines I really need...

[General]
force_ssl = 1
salt = "xxxxxxxxxxx"
trusted_hosts[] = "piwik.domain1.de"
trusted_hosts[] = "piwik.domain1.de.xxxxxxx.kasserver.com"
trusted_hosts[] = "ssl-account.com"
trusted_hosts[] = "ssl-account.com/piwik.domain1.de"
trusted_hosts[] = "ssl-account.com/piwik.domain1.de.xxxxxxx.kasserver.com"

**Comment by tsteur** [comment]
Probably only this one is needed: `trusted_hosts[] = "ssl-account.com"` as the rest is probably ignored. However, it is not really good to whitelist all paths from `ssl-account.com` as someone else having a path there as well could misuse it. It is a rather small risk though I would say.

**Comment by ggeorgg** [comment]
Ok. But i guess there is no problem with my trusted_hosts configuration, right?
But what else can cause this issue, that firefox and ie are able to set the cookie but chrome not? Is it an addidional security feature of chrome?

**Comment by tsteur** [comment]
To be honest I'm not sure why it worked in Firefox or Chrome. Possibly they didn't send a referrer with the request and this way it worked fine. 

There's no problem with your current trusted_hosts configuration

**Comment by ggeorgg** [comment]
I just found some time to look at this problem once again and I think I solved it. 
It seems that it really was a missconfiguration of my piwik. I installed piwik via a tool from my provider and I have not set the required settings mentioned here: http://piwik.org/faq/how-to-install/#faq_98
Now I added the following lines to my config.ini.php
```
assume_secure_protocol = 1
; Uncomment line below if you use a standard proxy
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_host_headers[] = HTTP_X_FORWARDED_HOST
```
It seems that there is no problem with setting the cookie in Chrome, Firefox and IE anymore.

I don't know how this really works but an other interesting thing for me is when I try to login via https://ssl-account.com/turnen.turnerschaft-lichtenfels.de/piwik/ I get an error because I am redirected to https://ssl-account.com/piwik and this is not the right adress. I know I don't really need this adress to login to piwik, because I also can use the normal adress (https://turnen.turnerschaft-lichtenfels.de/piwik) as well. 
Another problem is, when I try to login via http://turnen.turnerschaft-lichtenfels.de/piwik I get the following error:
```
Fehler: Sicherheitschecks fehlgeschlagen. Bitte laden Sie das Formular erneut und prüfen Sie, ob Ihr Browser Cookies zulässt. Wenn Sie einen Proxy Server verwenden, müssen Sie [Piwik so einrichten, dass es Proxy Header akzeptiert](http://piwik.org/faq/how-to-install/#faq_98).
```
They say I have not configured Piwik to accept proxy headers but I though I did this by adding the lines mentioned above?
Also, I am wondering about why I can still reach piwik via http because I already added `force_ssl = 1` to my config.ini.php. What is this really for?

To come to an end:
I think the bug label isn't justified here anymore.

**Comment by mattab** [comment]
Thanks for letting us know. I'll close the issue for now. if you still have problem or question please create new issue or ask in our forums: http://forum.piwik.org/
