### ISSUE TITLE
enable help text by default for new users

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#9293]
The help text for reports are hidden by default.
Only on mouse over on the location where the hidden question mark is located will show this question mark.
After klicking on the question mark the help text becomes available for the user.
It would help the user on-boarding if there would be a per user setting to enable/disable help text for reports.

This setting should be set to enabled by default when creating a new user.

![image](https://cloud.githubusercontent.com/assets/7987117/11431326/347a0a44-9496-11e5-9790-275aa2c03772.png)

**Comment by mattab** [comment]
I don't think we can show the help text by default, but I wrote your idea in the related issue about onboarding users: #7170 and https://github.com/piwik/piwik/issues/3185
