### ISSUE TITLE
#4815: "Transition and Overlay does not work when site-url contains &" reappeared

### ISSUE THREAD

**Issue by HermannPRODYNA** [piwik/piwik#9296]
Issue #4815 reappeared on Version 2.14.3

In Actions->Pages any page containing an '&' gets "There's no data for..." when trying to open transitions.
There are no problems for any pages that don't contain '&'

**Comment by tsteur** [comment]
I think row evolution is currently handled and already fixed here: https://github.com/piwik/piwik/issues/8393 

Transition would still need to be tested.

**Comment by HermannPRODYNA** [comment]
Since this issue was already fixed in the past (see #4815) this should be a regression right?

**Comment by tsteur** [comment]
Good point, thx :)

**Comment by tsteur** [comment]
I can't reproduce this one locally and also works here: https://demo-anonymous.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?module=Actions&action=menuGetPageUrls&idSite=1&period=year&date=today&popover=RowAction$3ATransitions$3Aurl$3Ahttp$3A$2F$2Fdemo-anonymous.piwik.org$2FCoreHome$2Findex$2F$3FidSite$3D11$26period$3Dday$26date$3Dyesterday

We fixed it already a few weeks ago here: https://github.com/piwik/piwik/commit/4e69cc717eb65cb09dc4daf843dc5a0c25531942  (I tested it and it didn't work before applying this patch)
