### ISSUE TITLE
Show a warning when Piwik is used as a SuperUser via HTTP

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9305]
It is quite risky to use Piwik via HTTP as a SuperUser. We should show a warning in the admin if this is the case:

* Explain via it is not secure / risky  (man-in-the-middle, ...)
* Recommend to setup HTTPS
* Explain it is good practice to create a user having view access and to use this user when viewing reports etc. (eg one would also not work as `root` under linux all the time)

**Comment by mattab** [comment]
Fixed in #9570
