### ISSUE TITLE
Running core:delete-logs-data with option --no-interaction doesn't do anything

### ISSUE THREAD

**Issue by ekooiker** [piwik/piwik#9316]
When I run the command: `./console core:delete-logs-data --dates=2015-11-20,2015-11-23` it asks the following question:
`You are about to delete log data. This action cannot be undone, are you sure you want to continue? (Y/N)` which defaults to No

This is fine, but when I add the option `--no-interaction` it still defaults to No so doesn't do anything.

I could not find a setting for this, so I changed the function `askForDeleteConfirmation` in `plugins/CoreAdminHome/Commands/DeleteLogsData.php` to this

    private function askForDeleteConfirmation(InputInterface $input, OutputInterface $output)
    {
        if ($input->getOption('no-interaction')) {
            return true;
        }
        $helper   = $this->getHelper('question');
        $question = new ConfirmationQuestion('<comment>You are about to delete log data. This action cannot be undone, are you sure you want to continue? (Y/N)</comment> ', false);

        return $helper->ask($input, $output, $question);
    }

Could this fix be added in a next release?

**Comment by tsteur** [comment]
FYI: Same was asked for in https://github.com/piwik/piwik/issues/8469 but for a different command. Therefore putting it in same milestone. 

Can you maybe issue a Pull Request for this change? (if you are familiar with Github + PHP)
