### ISSUE TITLE
An error occurred The directory "/var/www/aviacion/piwik/tmp/cache/tracker/" is not writable.

### ISSUE THREAD

**Issue by jamvyysa** [piwik/piwik#9317]
I try to install Piwik, but when I go to the browser tells me I have problems with creating a folder, not how to solve this problem, could someone help me?

**Comment by tsteur** [comment]
Are you using Red Hat by any chance? If so, please try solution in https://github.com/piwik/piwik/issues/8918#issuecomment-147778190

**Comment by kfiresmith** [comment]
More importantly, is SELinux currently enforcing?  If so, the fix I've just verified is:

(as root)
chcon -t httpd_sys_content_rw_t /var/www/html/piwik/tmp
chcon -R -t httpd_sys_content_rw_t /var/www/html/piwiki/tmp/tracker/
chcon -R -t httpd_sys_content_rw_t /var/www/html/piwik/tmp/cache
systemctl reload httpd.service

**Comment by tsteur** [comment]
Thx @kfiresmith . I will close this issue as a duplicate and leave the other issue open (#8918) as it is most likely the same problem. @jamvyysa feel free to comment and to reopen this issue if it doesn't help you

**Comment by mattab** [comment]
a new FAQ was published to hopefully summarise the solutions: [How do I fix the errors “Unable to write in the cache directory” or “The directory matomo/tmp/cache/*” is not writable.”?](https://matomo.org/faq/how-do-i-fix-the-error-unable-to-write-in-the-cache-directory-or-directory-not-writable/).
