### ISSUE TITLE
Minor changes to Installation > Create Super User step for German users

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9321]
When installing Piwik, at the Super User installation step ([screenshot](https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/Installation_superuser.png)), 
when we detect that the browser language is German, then:

- we write `Piwik PRO Gmbh` instead of `Piwik PRO`
- link to https://piwikpro.de/ instead of piwik.pro
- and we un-check the second checkbox for `Piwik PRO Gmbh` newsletter

These minor changes are legally required to collect data for German users.

Fyi: we will also need to enable a double opt-in mechanism in this mailing newsletter

**Comment by sgiehl** [comment]
> - we write Piwik PRO Gmbh instead of Piwik PRO

We can simply change the translation to realize that, or shall we remove `Piwik PRO` from the translation string and inject it in the code?

**Comment by mattab** [comment]
@sgiehl +1 we can simply str_replace /replace company name in the existing translation
