### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Exception' with message 'The configuration file {/home/config/config.ini.php}

### ISSUE THREAD

**Issue by system4id** [piwik/piwik#9330]
Installing process on page 2 gives 500
GET request to piwik.php failed. Try whitelisting this URL from HTTP Authentication and disable mod_security (you may have to ask your webhost). For more information about the error, check your web server error log file.
After making this change, restart your web server. 
Error_log: 
PHP Fatal error:  Uncaught exception 'Exception' with message 'The configuration file {/home/config/config.ini.php} has not been found or could not be read.' in /core/Application/Kernel/EnvironmentValidator.php:64\nStack trace:\n#0 /core/Application/Kernel/EnvironmentValidator.php(45): Piwik\\Application\\Kernel\\EnvironmentValidator->checkConfigFileExists('/home/l/logrise...', false)\n#1 /core/Application/Environment.php(185): Piwik\\Application\\Kernel\\EnvironmentValidator->validate()\n#2 /core/Application/Environment.php(94): Piwik\\Application\\Environment->validateEnvironment()\n#3 /piwik.php(56): Piwik\\Application\\Environment->init()\n#4 {main}\n  thrown in /core/Application/Kernel/EnvironmentValidator.php on line 64, referer: http://site.com/

**Comment by system4id** [comment]
Version 2.15, in /config/ file config.ini.php is absent.

**Comment by tsteur** [comment]
What's your PHP version and operating system? Can you try to clear `piwik/tmp` directory and remove `piwik/config/config.ini.php` (if it exists, might not be there see error message).

It looks like it is trying to find the `config.ini.php` in the wrong path but no idea why. Which PHP version and operating system are you using?

**Comment by system4id** [comment]
OS:	3.10
Apache:	2.2.22
MySQL:	5.5
PHP:	5.3.29
Correct directory in error log is /public_html/config/config.ini.php
Piwik was copied in /public_html/ directory.

**Comment by tsteur** [comment]
Have you tried to remove the config file and tmp directory? Or can you maybe just delete all files, copy the files from the build ZIP on your server again and begin the installation again and check whether it works now?

**Comment by system4id** [comment]
config.ini.php is absent in distributive. No such file. In config directory only global.ini.php is. I removed tmp directory and replay installation. All is ok, but message with 500 for piwik.php appear again.
In Internet there are many messages with this problem, no solution.

**Comment by tsteur** [comment]
OK thx for that. It looks like some kind of server configuration issue. Do you mind asking in the forums? http://forum.piwik.org/  More people will possibly see your problem there and can maybe help you finding out what the problem with the server is. In case it is actually an issue with Piwik feel free to reopen this issue and to comment here. We only handle bugs and features in this issue tracker. Questions and help for configuration is given in our forums.

Maybe also have a look here https://github.com/piwik/piwik/issues/8417 and https://github.com/piwik/piwik/issues/6841

**Comment by tsteur** [comment]
Maybe also something to check: What appends if you try to access `piwik.php` in your browser manually... Maybe mod_security is actually still enabled or so

**Comment by tsteur** [comment]
Just FYI: seeing the message 

> PHP Fatal error: Uncaught exception 'Exception' with message 'The configuration file {/home/config/config.ini.php} has not been found or could not be read.' in /core/Application/Kernel/EnvironmentValidator.php:64\nStack trace:\n#0 

At this stage of the installation is kinda expected. I just tried to reproduce it and it works fine for me. I am getting message as well but we do return a HTTP 200 which is the important part here. Can you check your webserver logs again if you maybe see some kind of other error as well?
