### ISSUE TITLE
piwik.php returns 204 response

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#9334]
I always have 204 when I get piwik.php
I use piwik version 2.15.0
How can I resolve it?

**Comment by sgiehl** [comment]
That is correct behavior. That response code means "No Content" but still is a "positive" result.

**Comment by msonnad** [comment]
Hi to avoid this error, We are also facing issues consistently. The error log file size keeps on increasing.

Piwik : 3.13.2
How we can overcome this?

Thanks,

**Comment by tsteur** [comment]
That's an expected response. Any 2XX response isn't a error so not sure why it appears in your error log?
