### ISSUE TITLE
Do not track crawler, bots etc

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#9335]
Hello. 
I use the next track code:

>  < script type="text/javascript">
>   var _paq = _paq || [];
>   _paq.push(['trackPageView']);
>   _paq.push(['enableLinkTracking']);
>   _paq.push(['appendToTrackingUrl', 'bots=1']);
>   (function() {
>     var u="https://mypiwikdomen.fr/";
>     _paq.push(['setTrackerUrl', u+'piwik.php']);
>     _paq.push(['setSiteId', 3]);
>     var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
 >    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js';  >s.parentNode.insertBefore(g,s);
>   })();
> </script>
> < noscript >< p>< img src="https://mypiwikdomen.fr/piwik.php?idsite=3&rec=1&bots=1" > > style="border:0;" alt="" /></p></noscript>

But this don't track bots, crawlers, and if I make request from curl I didn't view it in piwik.
How I can track it?
P.S. My piwik version is 2.15.0

**Comment by sgiehl** [comment]
Tracking bots is not fully supported in Piwik out of the box. Please have a look at the BotTracker plugin.

**Comment by simpleuser99** [comment]
I install the BotTracker plugin. But  if I make request from curl I didn't view it in piwik, and i don't view bots.

**Comment by simpleuser99** [comment]
![no_bots](https://cloud.githubusercontent.com/assets/11714750/11804546/c63178ae-a315-11e5-90d5-b6c5b3edaa15.PNG)

Help me to resolve my problem.
By the way, in piwik doc http://piwik.org/faq/new-to-piwik/faq_63/ describe that if I use bots=1 I can view bots, but it doesn't work for me. I doesn't see nay bot.
