### ISSUE TITLE
Iceweasel should be tracked as Firefox

### ISSUE THREAD

**Issue by nidico** [piwik/piwik#9336]
In #1167 it was already concluded that "GNU/Debian rebranded firefox should not appear in a different segments". I fully agree with this - the browser split happened due to smaller licensing issues, but is irrelevant from an analytics point of view in my opinion.

Nevertheless, Piwik currently tracks firefox and iceweasel separately.

I'd suggest to treat iceweasel treated as firefox again.

Related note: Chrome and Chromium are currently also tracked separately. I don't have a clear opinion on that one though, they indeed feel like more different browsers than firefox and iceweasel do.

**Comment by mattab** [comment]
Hi @nidico please create suggestion in our Device Detector project: https://github.com/piwik/device-detector/issues/
