### ISSUE TITLE
Deleted User and Browser with old Cookie => Uncaught

### ISSUE THREAD

**Issue by maugsburger** [piwik/piwik#9338]
When a User get's deleted, but there is a browser still holding a cookie for that user, you get PHP/SQL Errors instead of a clear error message.

The User has to manually delete the cookie, instead I would wish that it is invalidated by piwik and the user do a normal login/re-register.

**Comment by mattab** [comment]
Hi @maugsburger can you please write exact steps to reproduce, and exact error message you got? we have never encountered this issue before. Thanks

**Comment by maugsburger** [comment]
No Problem:

1. Create user in Admin-Panel
2. Login with that user (Auto-Login disabled, in Incognito-Window), leave window open.
3. Delete that user in Admin-Panel
4. Reload Incognito-Window, it shows:
```
Warning: array_merge(): Argument #1 is not an array in /home/xxx/public_html/include/functions_user.inc.php on line 394

Warning: Invalid argument supplied for foreach() in /home/xxx/public_html/include/functions_user.inc.php on line 396

Notice: Undefined index: id in /home/xxx/public_html/include/functions_user.inc.php on line 422

Notice: Undefined index: status in /home/xxx/public_html/include/functions_user.inc.php on line 422


Warning:  [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

SELECT cat_id
  FROM piwigo_user_access
  WHERE user_id = 
; in /home/xxx/public_html/include/dblayer/functions_mysqli.inc.php on line 830


Fatal error: Call to a member function fetch_assoc() on boolean in /home/xxx/public_html/include/dblayer/functions_mysqli.inc.php on line 891
```
