### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by jonnybarnes** [piwik/piwik#9339]
I’m trying the latest piwik (v2.15.1-b7), though this same error occured with the latest stable release, on PHP7.0.0 and nginx 1.9.7

When I try to login:
```
Error: Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Piwik to accept the proxy header that forwards the Host header. Also, check that your Referrer header is sent correctly.
```

I get this same error even if I deliberately enter an incorrect password.

Here’s my nginx conf file:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ****;

    ssl_certificate /etc/letsencrypt/live/****/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/****/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

    root /home/jonny/websites/piwik;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* \.php$ {
        fastcgi_pass unix:/usr/local/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include includes/fastcgi_params;
        fastcgi_param HTTPS on;
    }

    # Specify a charset
    charset utf-8;

    # Security Headers
    #include includes/security-headers.conf;

    # SSL Stapling
    include includes/stapling.conf;
}
```

My `fastcgi_params` are:
```
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

Why can’t I log in?

**Comment by tsteur** [comment]
Please have a look here in case you need to configure a proxy: http://piwik.org/faq/how-to-install/faq_98/

Do you mind asking this question in the forum? http://forum.piwik.org/ We only handle bugs/feature requests here and questions are usually answered in the forum. More people might see the question there and people having NGINX knowledge etc might be able to help you there.

Just to be sure: Has Piwik ever worked with an older version? And have you tried with a different PHP version?

**Comment by jonnybarnes** [comment]
It worked when I tried to install it on the PHP7 RCs.

**Comment by tsteur** [comment]
and now it doesn't work with PHP7 final?

**Comment by jonnybarnes** [comment]
It seems so. Just signed up to the forums. If I can tie it down to a more specific bug I’ll report back here :)

**Comment by tsteur** [comment]
I'll try to install latest PHP7 final for a quick test here as well. Only tested with RCs before

**Comment by jonnybarnes** [comment]
I assume if anything it’s going to be an issue with how nginx passes values to php-fpm, but what the problem is in particular I don’t know.

**Comment by tsteur** [comment]
This error message usually only happens when you for example wait for too long on the login form until you actually press "log in" and the token stored in the session is invalidated meanwhile. So it might be a problem related to PHP not finding the session or so. 

A fix might be to configure database as session handler http://piwik.org/faq/how-to-install/faq_133/ or Redis http://piwik.org/faq/how-to/faq_20521/

**Comment by jonnybarnes** [comment]
Changing to use the database doesn’t fix the error.

**Comment by jonnybarnes** [comment]
Okay, interesting, the PIWIK_SESSID cookie is being set for the wrong domain. This piwik installation is hosted at `analytics.domainA.com`, the cookie is being set for `domainB.com`. Would explain why I can’t log in.

**Comment by jonnybarnes** [comment]
My `php.ini` file had set `session.cookie_domain` set to `domainB.com`. Commenting this line out has allowed me to log in.

**Comment by tsteur** [comment]
Thx for letting us know :+1:
