### ISSUE TITLE
Handle submodules via composer and checkout correct submodules when changing branch

### ISSUE THREAD

**Issue by JohnMaguire** [piwik/piwik#9349]
Sorry for commenting on the existing issue, I didn't want to open a new one if you planned to work there since it's an identical bug to #6906 just in 2.15.0.

I installed Piwik using `composer`. Originally, all my widgets were erroring (like #6906) and many pages were also erroring. I disabled `CustomVariables` per the other bug, and that fixed my issue.

I just re-enabled it for this bug, and my widgets seem to be working now actually, but all the erroring pages still error.

```
2015/12/07 13:41:28 [error] 11289#11289: *44252 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/home/john/www/analytics.leftforliving.com/libs/PiwikTracker/PiwikTracker.php' (include_path='/home/john/www/analytics.leftforliving.com/vendor/pear/pear_exception:/home/john/www/analytics.leftforliving.com/vendor/pear/console_getopt:/home/john/www/analytics.leftforliving.com/vendor/pear/pear-core-minimal/src:/home/john/www/analytics.leftforliving.com/vendor/pear/archive_tar:/home/john/www/analytics.leftforliving.com/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear') in /home/john/www/analytics.leftforliving.com/plugins/CustomVariables/Archiver.php on line 19" while reading response header from upstream, client: 68.62.16.159, server: analytics.leftforliving.com, request: "POST /index.php?date=yesterday&module=VisitsSummary&action=index&idSite=1&period=day HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "analytics.leftforliving.com", referrer: "https://analytics.leftforliving.com/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday"
```

The file it's looking for does not seem to exist:

```
root@dib:/home/john/www/analytics.leftforliving.com# ls libs/PiwikTracker/
root@dib:/home/john/www/analytics.leftforliving.com# 
```

Erroring pages:
 - Visitors > Overview
 - Visitors > Custom Variables
 - Visitors > Engagement
 - Actions > Site search
 
Thank you for the great piece of software!

**Comment by JohnMaguire** [comment]
Ah, I see now that `libs/PiwikTracker` is a submodule, so composer [can't resolve it](https://stackoverflow.com/questions/18100420/how-do-i-use-a-git-submodule-with-a-composer-loaded-library).

It looks like `piwik-php-tracker` has a `composer.json` though, so maybe it could be switched to a composer dependency?

The (less clean) alternative I see is to add `--prefer-source` when doing a `composer install`, and perhaps add a `post-install-cmd` to the `composer.json` that checks out submodules.

If you have a preference, I wouldn't mind submitting a pull request for the change.

**Comment by tsteur** [comment]
We cannot make it a composer dependency see https://github.com/piwik/piwik/issues/6757 and https://github.com/piwik/piwik/issues/6605

The less clean alternative might be interesting. Do you mind submitting a pull request for it? Ideally it would check whether `git` command is available and if not, prints some kind of error message or so if that is possible?

**Comment by JohnMaguire** [comment]
Hi @tsteur, I'm a little confused by the assertion "We cannot make it a composer dependency", since I don't actually see where in those issues it's discussed as being problematic? What prevents it from being a composer dependency?

I can certainly take a look at doing that. :) In the meantime, for the submodule issues many seem to be facing, I have a couple tips:

1. Create a `.git/hooks/post-checkout` that runs `git submodule update --recursive --init`. This will ensure that every time you checkout a different branch, your submodules are updated with the commit tagged by the origin.
2. From then on, simply cd into the submodule, `git pull origin master` and then add the submodule in order to update it.

Submodules are a little tricky, but not terrible!

**Comment by tsteur** [comment]
I'm reopening the issue as it would be nice to put those hooks in there. Maybe we could do this as part of this issue. 

It's possible it was discussed in another issue. Think it was here: https://github.com/piwik/piwik/issues/6870#issuecomment-67590075

**Comment by JohnMaguire** [comment]
The hooks are for user configuration unfortunately. They're useful for development. I actually recommend creating a directory called `~/.git_template` and placing the hook there and then setting the following Git config:

`git config --global init.templatedir '~/.git_template/'`

Any future clones will get the hook added locally.

I've submitted a pull request to checkout the submodule automatically when creating a project with `composer create-project --prefer-source piwik/piwik`. Is there any relevant documentation I can update?

**Comment by JohnMaguire** [comment]
Sorry, pull request is at #9353
