### ISSUE TITLE
New menu structure for Personal => Manage menu items

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9354]
Currently, Goals, Tracking Code, Custom Variables (and if installed Custom Dimensions) can be configured in "Personal" section which is accessible by clicking on the "User icon" in the top right.

When writing eg a guide re how to configure Custom Dimensions it always feels wrong to write "Go to your personal section/area" to configure them. They are not really personal, they are rather website related. 

Idea would be to move them into the Administration section under a main category "Configure". As Custom Variables cannot be configured we would move them under "Diagnostic". 

![image](https://cloud.githubusercontent.com/assets/273120/11640308/cbc42912-9d96-11e5-9933-d6e77f48e84e.png)

Another idea could be maybe to have a dedicated "manage websites" area accessible via an icon in the top right menu. There one could manage all the websites (create new websites, edit urls etc, there would be a new menu item for the global website settings as well) showing the following links:
* Manage Websites
* Global Website Settings
* Goals
* Custom Variables
* Custom Dimensions
* Tracking code

This would also make the Manage websites screen easier as it currently combines two very different things (manage websites and global website settings). Problem: It might be a bit confusing with the "All Websites" link in the top menu as both links would be website related.

Any other ideas?

**Comment by tsteur** [comment]
FYI: Recent idea from design team was to merge Personal and Administration settings into one big menu.

For super users this would approx look like this:
![image](https://cloud.githubusercontent.com/assets/273120/13623067/a6d1b600-e608-11e5-8d18-83f4c167edc4.png)

For users without super user access but admin access there would be less entries. Eg 

![image](https://cloud.githubusercontent.com/assets/273120/13623139/2fa267f4-e609-11e5-974b-4debe1b1ba40.png)

For users without admin or super user access there would be even less entries...

**Comment by mattab** [comment]
merging menus sounds good to me, it makes things simpler and more streamlined.

**Comment by tsteur** [comment]
Done
