### ISSUE TITLE
CA Root Certificates must be updated for "Let's encrypt"

### ISSUE THREAD

**Issue by FerhatAkgun** [piwik/piwik#9356]
The current app is not able to validate SSL certificates, created via https://github.com/letsencrypt/letsencrypt

Please update the bundle of CA Root Certificates.

**Comment by tsteur** [comment]
I presume you mean the Piwik Mobile app? For this please have a look https://github.com/piwik/piwik-mobile-2/issues/5348 and https://github.com/piwik/piwik-mobile-2/issues/5327

**Comment by tsteur** [comment]
Sorry I just realised you meant something else :)

**Comment by mattab** [comment]
Hi @FerhatAkgun 

could you please try with the new cacert file in this pull request? https://github.com/piwik/piwik/pull/9439

I'm not sure that it fixes the issue so i woud like to confirm, thansk

**Comment by FerhatAkgun** [comment]
I have replaced cacert.pem.
Now I am getting another error inside the app. With this new error, the app is useless until SSL validation is disabled again.
Error:
"hostname in certificate didn't match"
<ferhatakgun.com> != <*.kasserver.com>

On the left side is my own domain name. On the right side you see a domain name of my web hoster.
How do you guys determine that right part?

**Comment by mattab** [comment]
>  "hostname in certificate didn't match"

FYI: this is not an error generated from Piwik from the SSL library we use under the hood. it means your SSL setup seems invalid.
