### ISSUE TITLE
Customize PDF Reports Email

### ISSUE THREAD

**Issue by vegastriguy** [piwik/piwik#9359]
I just happen to notice this text on Auto Reports sent out to my customers.

Hello,
Please find in attached file your monthly report for xxxxxx.
Sent from http://www.mydomain.com/analytics/.

1) I do not want people to see the actual address where the reports folder is located
2) How can I totally customize this email message? The actual PDF report I type a personal message to the client and would like to do the same here. Please just point to the particular file and I am sure I can figure it out.

**Comment by tsteur** [comment]
Have a look around this area of `ScheduledReports.pdf` https://github.com/piwik/piwik/blob/2.15.0/plugins/ScheduledReports/ScheduledReports.php#L325

Be aware that when you make changes to the file you will have to apply the patches whenever you update Piwik. Feel free to send us a Pull Request in case you make it customizable in the UI.
