### ISSUE TITLE
Lack of parameter in <noscript> part of Piwik's JavaScript tracking code

### ISSUE THREAD

**Issue by tomasztomik** [piwik/piwik#9360]
Hello,

It seems that <noscript> failover within tracking code generated by Piwik in site settings page will not work. Piwik.php requires two parameters "idsite=x&rec=1" to generate tracking image. The problem is that <noscript> part of Piwik's JavaScript tracking code generated via site settings page lacks this paramater. Example of generated

 tracking code:
```
<noscript><p><img src="//localhost/piwik1/js/tracker.php?idsite=2" style="border:0;" alt="" /></p></noscript>
```

when it should be:

```
<noscript><p><img src="//localhost/piwik1/js/tracker.php?idsite=2&rec=1" style="border:0;" alt="" /></p></noscript>
```

Result is that if somebody will implement tracking code from Piwik's website settings page - <noscript> turnover will not work. Issue found in 2.15 Piwik version.

![clipboard02](https://cloud.githubusercontent.com/assets/16131839/11654815/cb2e4c00-9da8-11e5-8f36-1fef211f6500.jpg)

Regards,
Tomasz

**Comment by tomasztomik** [comment]
FYI @mattab

**Comment by tsteur** [comment]
This is currently on purpose from the looks see comment

> By default, Piwik doesn't track non-JS visitors.

See https://github.com/piwik/piwik/blob/master/core/Tracker/VisitExcluded.php#L70-L82

**Comment by mattab** [comment]
Hi @tomasztomik 
This is by design. see also: https://piwik.org/faq/how-to/faq_176/ and https://piwik.org/faq/new-to-piwik/faq_63/
