### ISSUE TITLE
Goal revenue not accurately reported in Live.getLastVisitsDetails API

### ISSUE THREAD

**Issue by cemdev** [piwik/piwik#9361]
Steps to reproduce:

Create a goal in Piwik (manually or via API) with a $0 revenue.
Add this to a page: _paq.push(['trackGoal', {goalId}, 25]);  (note the non-zero revenue)
Browse to the page.
Call Live.getLastVisitsDetails for that visitor (using visitorId segment)

In the list of visits.actionDetails, one of the actions will be of type = "goal". This action contains the goal id, goal name, url and revenue fields. All are correct, except revenue, which returns 0, not 25. 

The piwik web interface correctly shows $25 worth of revenue, so this bug appears to be in the Live API module.

**Comment by cemdev** [comment]
Note - it actually always returns the default value of the goal, it doesn't consider goal value sent via trackGoal

**Comment by tsteur** [comment]
Thank you for reporting this bug. 

FYI: It's a bug in the query as we always fetch the stored revenue from goal table and ignore a value set in `log_conversion.revenue`: https://github.com/piwik/piwik/blob/2.15.0/plugins/Live/Model.php#L89

**Comment by tsteur** [comment]
Fixing this should be as easy as this: https://github.com/piwik/piwik/commit/98e8178ae4cf0a24dee504d66a213ce7fa7d8839

Just FYI: Changing the goal value afterwards for a specific goal will no longer change the value in the output which is correct and expected I'd say.

**Comment by mattab** [comment]
Nice find @cemdev thanks for letting us know

**Comment by cemdev** [comment]
Guys, this is fantastically responsive. Many thanks for investigating and fixing so quickly. I've noticed a couple of other issues with Live API that I have been able to work around, so did not report. I'll add those once I find my notes and repro again.
