### ISSUE TITLE
Date range translations broken for some languages

### ISSUE THREAD

**Issue by rbrdevs** [piwik/piwik#9365]
When a report involves dates of different months the formatted text of report title and e-mail subject are wrong.
For a period like "1 week" from 2015-30-11 I am getting "week  30 6 MMMM–d 6 MMMM 6 y"

Piwik 2.15.0
CentOS 7.1
nginx/1.6.3
PHP 5.5.29

**Comment by sgiehl** [comment]
which language have you choosen?

**Comment by rbrdevs** [comment]
Spanish.
I have tested to generate this report switching to English and text are displayed right.
How can I achieve to fix this in Spanish?
Thanks.

**Comment by sgiehl** [comment]
Guess thats a bug in handling the spanish date/time formats. I'll have a look at that.

**Comment by sgiehl** [comment]
Does that work correct for you when you choose such a date range in the date selector in piwik itself?

**Comment by rbrdevs** [comment]
No, It fails always If I manualy choose such date range in admin "Email reports" or If I receive the e-mail report generated by a scheduled cron.
