### ISSUE TITLE
http://demo.piwik.org - latest beta

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#9366]
The demo site should always contain the latest version (also beta) for comparison.

**Comment by tsteur** [comment]
Thx for the comment. We often update latest demo to the latest beta version to detect errors as early as possible but we cannot always update etc. Often some beta updates only contain small changes needed for a plugin etc. so we sometimes don't update demo.piwik.org . Maybe we could one day if a `beta.piwik.org` that updates automatically and a `nightly.piwik.org`. 

Just out of interest: Do you want to compare something specific?

**Comment by iMarkus** [comment]
Hi, thanks for the response.

No nothing specific. But it happened a few times that I upgraded to the latest beta version on our dev system and then just wanted to see if demo.piwik.org reacts like our dev system.

**Comment by tsteur** [comment]
Got it, for this we would actually at some point have a beta.piwik.org which updates automatically to latest beta.

**Comment by iMarkus** [comment]
That would be great. Looking forward :+1:
