### ISSUE TITLE
Be more clear about "Track only visits for defined URLs" feature in UI and/or FAQ

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9370]
See https://github.com/piwik/piwik/pull/9358#issuecomment-163283324 and https://github.com/piwik/piwik/pull/9358#issuecomment-163366428

As mentioned in the comments it would be nice to be more clear with the examples. Especially re subdomains and paths. 

Also we could improve the sentence explaining this feature and mention subdomain/paths.

**Comment by tsteur** [comment]
The second part of the FAQ https://piwik.org/faq/how-to/#faq_21077 could be adjusted to something like 

> It is possible to configure your website in Piwik so that only requests to “example.com” will be tracked, and all other requests ignored. Go to Administration > Websites > click “Edit”. Below the “URLs” field for your website, there is a checkbox “Only track visits and actions when the action URL starts with one of the above URLs.”. If you click this checkbox, and click “Save”, Piwik will then only track requests where the domain and the path is an exact match of one of the URLs you specified for this website. This means each valid subdomain has to be specified separately. For example when the known URLs are 'http://example.com/path' and 'http://good.example.com', tracking requests for 'http://example.com/otherpath' and 'http://bad.example.com' are ignored.

**Comment by mattab** [comment]
@tsteur fyi: FAQ was updated

**Comment by mattab** [comment]
#9491 was merged and FAQ updated, this looks good to me!
