### ISSUE TITLE
Different wordings for username/login in UsersManager

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9372]
The wordings for both are probably different all over in Piwik but especially in UsersManager we should be consistent.

Eg when creating a new user it says "login"
![image](https://cloud.githubusercontent.com/assets/273120/11704190/46fc46fa-9f4a-11e5-91e1-62c0fb71425c.png)

but the header title says "username"

![image](https://cloud.githubusercontent.com/assets/273120/11704194/53b174d8-9f4a-11e5-974c-04831b8e5ad3.png)

**Comment by mattab** [comment]
+1 for using `username` consistently

**Comment by mattab** [comment]
fixed in #9603
