### ISSUE TITLE
Different wordings for access/permission in UsersManager

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9373]
Probably the wordings are different across Piwik but noticed it in UsersManager.

Sometimes we use "Permission"

![image](https://cloud.githubusercontent.com/assets/273120/11704412/798170bc-9f4c-11e5-89b2-e8320de31a8e.png)

sometimes we use "access"

![usersmanager](https://cloud.githubusercontent.com/assets/273120/11704441/b3da2808-9f4c-11e5-9205-6433d3c3b15d.png)

**Comment by mattab** [comment]
+1 to use `access` consistently (and remove `permission`)

**Comment by sgiehl** [comment]
In my understanding `access` and `permission` have a different meaning. Having access to something is more or less kind of a permission.
For example: An admin has the permission to give another user permissions like `view access` or `admin privileges`

**Comment by tsteur** [comment]
I thought about that too (eg `... has a permission to access ...`) but not sure if it's maybe rather confusing in the end for users that don't understand any difference here?

**Comment by halfdan** [comment]
With @sgiehl on this one. The wording should definitely be made clearer - removing `permission` isn't the right way though. This really depends on what is happening in the interface.

**Comment by tsteur** [comment]
I'd recommend 
`Decide which users have access to your websites. You can also give access to all the websites at once by choosing "Apply to all websites" in the website selector` 

instead of 

`Decide which users have which Piwik access on your Websites. You can also set the permissions on all the Websites at once.`
