### ISSUE TITLE
"greater than" or "less than" symbol are html encoded ("&gt","&lt") not url encoded ("%3e","%3c") when put into bulk request

### ISSUE THREAD

**Issue by milexjaro** [piwik/piwik#9393]
I need some help, when I used a bulk API request, and adding some segmentation where ">" is "%3e" in url encoding, it transform to "&gt" thus it can't provide the correct response. Is there any solution or alternatives to solve this problem? Thanks in advance

**Comment by tsteur** [comment]
Do you maybe have a URL or command to reproduce this? Feel free to hide your domain and make sure there is no value for `token_auth` visible

**Comment by milexjaro** [comment]
Hi @tsteur thanks for replying, sure, I used piwik domain to test, and here it is:

http://demo.piwik.org/?module=API&method=API.getBulkRequest&format=json&urls[0]=method%3dVisitsSummary.getVisits%26idSite%3d7%26period%3drange%26date%3d2015-11-30%2c2015-12-4%26segment%3dvisitDuration%3d%3d30%3bactions%3E%3d2%26format%3dJSON%26token_auth%3danonymous

I don't know why it's transformed into html encoding, thanks

**Comment by tsteur** [comment]
I can confirm this is a bug. Problem is that it's handled correctly by `API.getBulkRequest` but when `getBulkRequests` performs each individual API request the Segment `actions>=2` get's transformed to `&gt;=2` here: https://github.com/piwik/piwik/blob/2.15.1-b10/core/API/Request.php#L109 . Only a few lines above we take care of the segment special case here https://github.com/piwik/piwik/blob/2.15.1-b10/core/API/Request.php#L90-L92 when reading the original values but not when an individual request is executed via `Request::processRequest`. 

To be exact it gets converted to `&gt;` here: https://github.com/piwik/piwik/blob/master/core/UrlHelper.php#L198

Maybe we could `unsanitizeValue($requestParsed['segment'])` if a segment value is present here: https://github.com/piwik/piwik/blob/2.15.1-b10/core/API/Request.php#L110 ? but not sure re any downsides @mattab @diosmosis
