### ISSUE TITLE
Feedback to #9382 (DB lock name should be less than 64 characters for MySQL compatibility)

### ISSUE THREAD

**Issue by Joey3000** [piwik/piwik#9395]
This is intended as a review of https://github.com/piwik/piwik/pull/9382, as it is already merged.

1. https://github.com/piwik/piwik/pull/9382/files#diff-f0dc4d4d133f84005fcebc1e10f155c0R289: If `$archiveId` is in decimal representation, [dechex()](https://secure.php.net/manual/en/function.dechex.php) could be used to make it shorter by converting it to hexadecimal.

2. https://github.com/piwik/piwik/pull/9382/files#diff-f0dc4d4d133f84005fcebc1e10f155c0R285 and the line after that:
  a. How was the "magic number" 23 calculated? (A comment explaining that value could be added to clarify.)
  b. It seems to NOT use the entire 64-character length. Currently, the maximum length is:
  ```
  strlen($dbLockName) = strlen("rmPrevArchiveStatus") + strlen(".") + strlen($tableWithoutLeadingPrefix) + strlen(".") + strlen(dechex($archiveId)) =
                      =           19                  +    1        +                23                  +    1        +        16 (conservatively, PHP_INT_SIZE on 64 bit: 8 bytes * 2 chars/byte) =
                      = 60
  ```

**Comment by Joey3000** [comment]
To the point 2a: Alternatively, a constant could be introduced for that "magic number", and the descriptive comment added to its definition. (As some strict coding guidelines handle it, forbidding "magic numbers".)

**Comment by tsteur** [comment]
Re 2a) `23`: I made it more clear here: https://github.com/piwik/piwik/commit/bc4013ebfa65d85bd92c1eb24e72ab8f4143b998#diff-f0dc4d4d133f84005fcebc1e10f155c0

**Comment by tsteur** [comment]
Re 1 and 2b) The string without archiveId is `44` characters long leaving up to 20 characters for the integer archiveId. Don't think it is needed to convert it to hex, is it? It would be nice to rather have it readable so when doing eg `show full processlist` etc one can debug things better. We don't have to use the entire 64 characters.

**Comment by Joey3000** [comment]
Ok, thanks for clarification!
