### ISSUE TITLE
header or footer custom code

### ISSUE THREAD

**Issue by Vebryn** [piwik/piwik#9401]
Hello,

I would like to get Piwik visitors infos. I create a dedicated site named Piwik. I want to put site tracker in a Piwik header or footer.

Is it possible to add a custom field to allow custom HTML code in header or footer ?

Thank you,

Best regards.

**Comment by tsteur** [comment]
Please check out http://plugins.piwik.org/AnonymousPiwikUsageMeasurement . You can install it directly within Piwik by going to Administration => Marketplace.

**Comment by Vebryn** [comment]
Tank you, I will try this plugin.
