### ISSUE TITLE
500 internal server error 

### ISSUE THREAD

**Issue by diverso** [piwik/piwik#9402]
tried to upgrade to no no avail, command line doesn't work, and clicking on the upgrade button and well as the link to db queries return 500 internal server error 

Any hint truly appreciated

**Comment by RMastop** [comment]
Hi @diverso,

Anything usefull in the logfiles?
Usually a solution is to backup both database and the configuration file at <piwik>/config/config.ini.php

Unpack the new version of Piwik ( http://builds.piwik.org/ ), replacing the current files.
Add the backup of config file in the <piwik>/config/ folder and start the commandline upgrade.

The procedure is written on the following page: 
http://piwik.org/docs/update/#the-manual-three-step-update

**Comment by tsteur** [comment]
See answer from @RMastop . Please try the manual three step update. Make sure to backup especially `config/config.ini.php`. It should work fine again.

Let us know if it doesn't solve it.

**Comment by diverso** [comment]
what can I say guys, thank you for the help, it seems that unexpectedly after multiple errors 500 PW finally upgraded, not sure what went on but either one of the attempts actually worked

**Comment by tsteur** [comment]
Glad to hear and thank you for letting us know
