### ISSUE TITLE
Setting default_language = en does not work

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#9404]
In our case we tried to set 'en' as default language but it did not work so far. In the global.ini.php we found the following lines

; if you want all your users to use Piwik in only one language, disable the LanguagesManager
; plugin, and set this default_language (users won't see the language drop down)
default_language = en

Also with LanguagesManager disabled (removed from global.ini.php), Piwik always switches Language and displays the language drop down in the user settings.

Can anybody reproduce this?

**Comment by sgiehl** [comment]
You may need to remove it from global.ini.php and from config.ini.php.

**Comment by iMarkus** [comment]
Hi,
I removed it from both configs but it still behaves the same.

Regards

**Comment by sgiehl** [comment]
I did a small test: removed it from both configs, set the default language to `fr` and opened piwik with a user that was configured to german before. Piwik was then displayed in french as expected.

Which version did you use? And could you provide a small description how you produce the misbehavior?
