### ISSUE TITLE
Login may fail with un-helpful message "Form security error" when SSL is mis-configured

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9407]
### How to reproduce

 * Set `assume_secure_protocol = 1` in config
 * Set `force_ssl=0`

Go to: 
 * http://piwik-server/
 * attempt to login 
 * Got `Form security failed` error message, that does not include the actual solution to the problem in this case
 * Expected: message should be helpful and help user solve the issue, which is to set `force_ssl=1`. 

### Explanation

When Piwik is used over HTTPS, we set the [Secure cookie flag `session.cookie_secure` ](http://php.net/manual/en/session.configuration.php#ini.session.cookie-secure)

```
        // advise browser that session cookie should only be sent over secure connection
        if (ProxyHttp::isHttps()) {
            @ini_set('session.cookie_secure', '1');
        }
```
source: https://github.com/piwik/piwik/blob/2.15.0/core/Session.php#L61-L64

So the PHP session ID cookie is only set when HTTPS is used.

In the case where Piwik thinks it's loaded over HTTPS (`assume_secure_protocol=1`) but it actually isn't, then the session ID cookie will be discarded and re-created on each page view, causing the NONCE to be re-generated, causing the login form submit to fail the nonce check.

### Solution

By setting `force_ssl=1` this will likely solve issue for this use case.

**Comment by mattab** [comment]
## Suggested solution

![https](https://cloud.githubusercontent.com/assets/466765/11886832/40adcf4a-a593-11e5-8eec-1afcd5a33f8b.png)

**Comment by manyk** [comment]
I have same issue if running Piwik on Nginx server behind proxy (with offloaded ssl). The solution was to force redirect login from http to https.
I had to alter the Nginix config as follows:

In http section:
```
map $http_x_forwarded_proto $proxy_https {
  default '';
  https on;
}
```

then in server section where location = /index.php is defined this must be added:
```
location = /index.php {
    if ($proxy_https = '') { return 301 https://$server_name$request_uri; }

    # rest of the code follows
}
```
Now, login page is automaticaly redirected to SSL.
