### ISSUE TITLE
Problem with bot tracking

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#9410]
Hello. My problem is https://github.com/piwik/piwik/issues/9335, but the issue did closed.  I don`t know how can I open issue 9335, and I forced to try to speak about my issue.
I install the BotTracker plugin. But if I make request from curl I didn't view it in piwik, and i don't view bots.

![no_bots](https://cloud.githubusercontent.com/assets/11714750/11894189/aadcfdd0-a586-11e5-8dcb-e3e8d23a268b.PNG)

Help me to resolve my problem.
By the way, in piwik doc http://piwik.org/faq/new-to-piwik/faq_63/ describe that if I use bots=1 I can view bots, but it doesn't work for me. I doesn't see nay bot.

**Comment by sgiehl** [comment]
If you are using the javascript tracker, you won't see many bots in Piwik. Even when using the Bottracker plugin. Bots usually don't interpret javascript or fetch additional content from pages, so they won't send the required tracking request to piwik.

To get useful bot statistics you need to do the tracking directly using the API or use log analytics.
