### ISSUE TITLE
Add a direct link to "Create Goals" when website has had no visitor yet

### ISSUE THREAD

**Issue by SimonBackx** [piwik/piwik#9412]
When you first create your website, and you're implementing for example a goal tracker, it isn't possible to add goals because you have no visitors yet. Piwik keeps complaining about it, and doesn't show a menu, only the tracking code...

There should be a way to add these before you have visitors. That would make sense because you develop a website **before** you make it public.

**Comment by sgiehl** [comment]
You should be able to add goals in your personal settings. But maybe we could add a hint for that within the "no data" message.

**Comment by tsteur** [comment]
We had same problem here: https://github.com/piwik/piwik/issues/9206 It seems to be a common issue. Maybe this time we should actually add a link to the description text to the "Manage Goals" section?

**Comment by mattab** [comment]
sounds good @sgiehl @tsteur updated issue title as suggested
