### ISSUE TITLE
Unable to achieve "Tracking No Result Search Keywords" using Custom Parameter

### ISSUE THREAD

**Issue by sumit140** [piwik/piwik#9421]
Hey Team, I am trying to achieve "Tracking No Result Search Keywords" using custom parameter instead of using default search parameter. But facing some issues in getting proper result. Also below I am maintaining my code what I have tried so far:
```js
function searchCheck() {
 if (document.getElementsByName('_3_keywords') && document.getElementsByName('_3_keywords')[0]) {
  var keywords = document.getElementsByName('_3_keywords')[0].value;
  if (document.getElementsByClassName('portlet-msg-info')
    && document.getElementsByClassName('portlet-msg-info')[0]) {
   var searchResults = document.getElementsByClassName("portlet-msg-info")[0].value = "No results were found that matched the keywords:";
   if (searchResults == "No results were found that matched the keywords:") {
    if (document.getElementsByName('_3_keywords') && document.getElementsByName('_3_keywords')[0]) {
     var searchCount = 0;
     //code to track search with no result
     console.log("keywords:::::::::" + keywords + "count" + searchCount);
	_paq.push([ 'trackSiteSearch', keywords + '', false, 0 ]);
  
    }
   }
  } else {
   //code to track search keyword having results
   var searchCount = 15;
   console.log("Sucess: keywords:::::::::" + keywords + "count" + searchCount);
    }
 }
}
```
Here '_3_keywords' is my custom parameter. Also, I have tried this as well: "_paq. push (['setCustomUrl', keywords + '&search_count=' + searchCount]);" But unable to get the no search keyword result. Can you please help me where I am doing wrong so that I can resolve my issue asap.

**Comment by tsteur** [comment]
Can you try `_paq.push([ 'trackSiteSearch', keywords + '', 0 ]);`. Not sure why you set it as custom data? Also `setCustomUrl` should work as explained here: http://piwik.org/docs/site-search/#tracking-no-result-search-keywords 

```js
_paq.push(['setCustomUrl', document.URL + '&search_count=' + searchCount]);
_paq.push(['trackPageView']);
```

You need to track a pageview after setting the custom URL

**Comment by tsteur** [comment]
Please reopen if you still experience the issue

**Comment by sumit140** [comment]
Hi Thomas,

I have solved my issues by calling trackpageview function based on
condition...it's work fine for me.
Thanks a lot for your all support.

**Comment by tsteur** [comment]
Glad to hear and thx for letting us know
