### ISSUE TITLE
Giving view access to a user does not work when using another case

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9422]
Reproduce:

* a user `username` has admin access to a website,
* a user `another-username` also with admin access to the same website,
* login as `another-username`
* go to Admin > Users
* then in the input box add admin access to `usernaME`

then:

* Got: `username` lost admin access. 
* Expected instead: `This user has access to this website already.` (ideally, since #8548 #8610) or `User usernaME doesn't exist.` 

follows up #9379

**Comment by tsteur** [comment]
What's your database collation for that table?

**Comment by tsteur** [comment]
Actually not needed, issued PR https://github.com/piwik/piwik/pull/9426 .
