### ISSUE TITLE
menubar cleanup @ 320px ~ 360px screens

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#9431]
Now it really looks cramped.

Suggestion:
![piwik-mobile-menu-improvement](https://cloud.githubusercontent.com/assets/5383059/11953633/021a91e8-a8a2-11e5-8a2d-c8faa7128a35.png)

Arguments:

1) remove mobile app link - yes, we know about it, and those who don't will easily find it. No need to remind us every time on precious screen space.

2) Dashboard & All Websites shortcuts could be moved into menu, and options to display them can be added in settings.

version 1:
![piwik-mobile-menu-improvement-fix 1](https://cloud.githubusercontent.com/assets/5383059/11953841/bdae216c-a8a3-11e5-8997-52374473fe41.png)

version 2: (with Dashboard shortcut)
![piwik-mobile-menu-improvement-fix 2](https://cloud.githubusercontent.com/assets/5383059/11953843/c086e3d8-a8a3-11e5-9521-ed7ed273d06c.png)

Saving 1-2 extra rows in total.

Thanks

**Comment by tsteur** [comment]
:+1: Icons should possibly also made bigger. We have a couple of ideas to improve responsiveness but currently do not really work much on it since there's also the mobile app.

**Comment by mattab** [comment]
Note this is related / similar to https://github.com/piwik/piwik/issues/9250
