### ISSUE TITLE
Bing, Yahoo, etc. may be shown as "Websites" instead of "Search engines"

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9438]
this was reported in the forums: http://forum.piwik.org/t/https-bing-in-referrer-websites-instead-of-search-engines/17304 and verified on the demo eg. http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Referrers&action=indexWebsites&idSite=7&period=day&date=yesterday

### Some search engines appear as "website" referrer

![websites](https://cloud.githubusercontent.com/assets/466765/11969628/4da77664-a981-11e5-8f79-fecfafdd7fb3.png)

ping @sgiehl maybe you have an idea?

**Comment by endrepalinkas** [comment]
Thanks!

A few more URLs:
https://search.yahoo.com/
https://tw.search.yahoo.com/
https://uk.search.yahoo.com/


In the demo screenshot this is not HTTPS, but should also be added =)
http://us.yhs4.search.yahoo.com/

**Comment by sgiehl** [comment]
That happens if no search keyword can be found in the referrer url. 
An empty keyword is currently only "allowed" for `Google`, `Yahoo!`, `Ixquick` and `DuckDuckGo`. See 
https://github.com/piwik/piwik/blob/master/plugins/Referrers/SearchEngine.php#L283-L306

As more and more search engines switch to https and hiding the keyword in the URL, we may need to allow that for all search engines or at least extend that list to cover those engines now popping up as referrers.

**Comment by endrepalinkas** [comment]
Just a note, this also applies to Bing now, there are lots of https://www.bing.com entries appearing in the Referrer Websites, instead of Search Engines.

**Comment by parruc** [comment]
Same problem here:

bing and others are being shown as a referral instead as search engine.

This fact messes up the referral stats.

**Comment by sgiehl** [comment]
would you mind pasting the full referrer addresses for those entries? Maybe we need to adjust the detections

**Comment by parruc** [comment]
It looks like it is www.bing.com/

![referral_bing](https://cloud.githubusercontent.com/assets/1440608/15008146/75f6a6ce-11de-11e6-9de0-6594cf7c06fd.png)

**Comment by endrepalinkas** [comment]
Yes, lots of HTTPS search URLs are not recognized.

I have added a list here https://github.com/piwik/searchengine-and-social-list/issues/3 as matthieu advised.

**Comment by mattab** [comment]
Since there was a lot of progress in https://github.com/piwik/searchengine-and-social-list/issues/3 I suppose this issue is now fixed. Kuddos to @sgiehl
