### ISSUE TITLE
Outlinks and Goals don't seem to Track External link clicks when Using the Piwik HTTP API

### ISSUE THREAD

**Issue by eSilverStrike** [piwik/piwik#9442]
I have a Joomla site with a plugin that connects to my Piwik website using the HTTP tracking API.

Everything works as expected except Goal tracking and the outlinks report. Nothing is ever shown in these reports for clicks on my site of links to other websites. These tools are available (not disabled) so I assume I can use this through I have found no documentation about this (in regards to using it while using the API instead of javascript).

Someone suggested it may be a bug as it should just work so I am posting it here.

See for more details:http://forum.piwik.org/t/how-to-track-clicks-on-external-links-using-the-piwik-http-api/17320

**Comment by tsteur** [comment]
As you track your website manually via HTTP Tracking API how do you track the goals / outlinks? You need to listen to clicks on outlinks on your website via JavaScript and then send a tracking request to your server (which can then do the HTTP Tracking API request). As the user is about to leave your website you will also need to keep the site busy on the "unload" event similar to https://github.com/piwik/piwik/blob/2.16.0-b1/js/piwik.js#L1224-L1247 so your Ajax request actually has enough time to finish execution. It is not quite trivial I would say and it might be easier to use `piwik.js`. There is no documentation about this so far indeed as it's usually covered by using the JavaScript Tracker

**Comment by eSilverStrike** [comment]
Okay thanks for the reply. I figured it was something along those lines. I will probably switch to the javascript tracker then.
