### ISSUE TITLE
enable https on forum.piwik.org 

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik#9443]
It is not possible to connect to the forum via HTTPS. I consider this bad practice. 
Could you enable https on the forum site?

**Comment by sgiehl** [comment]
That will be done in the future. See #8747

**Comment by Joey3000** [comment]
> That will be done in the future. See #8747

@mattab So, the following in the above issue can be ticked off, and this issue here labelled as "Security" and "Website piwik.org" :)
> Note: Create an issue to follow up these items:

> - [ ] Enable HTTPS SSL connection for forum.piwik.org

**Comment by mattab** [comment]
Done! https://forum.piwik.org/
