### ISSUE TITLE
console command cause abrt

### ISSUE THREAD

**Issue by prokopowichj** [piwik/piwik#9444]
Running the following consistently causes abrt (crash report) on RHEL6,

./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='http://piwik.local.gc.ca'

cmdline:        /usr/bin/php -q /data/piwik/console climulti:request -q --piwik-domain=piwik.local.gc.ca --superuser module=API&method=API.get&idSite=4&period=day&date=last1000&format=php&trigger=archivephp&pid=775c331d9b524ad547d6d9c8a561f034516360d48805b227c5700c70a208ab945a06a2f8bd34624dd83c5b170c144a8b71c00
executable:     /usr/bin/php
kernel:         2.6.32-431.20.3.el6.x86_64
last_occurrence: 1450896833
pid:            16634
pwd:            /data/piwik
time:           Wed 23 Dec 2015 01:53:53 PM EST
uid:            1013
username:       piwik

**Comment by mattab** [comment]
Hi there, could you check your error log or syslog for the actual error? also please upgrade PHP version to more modern as I suspect you may use an old PHP version.

**Comment by prokopowichj** [comment]
Dec 22 14:17:39 ottrhapp034 abrt: detected unhandled Python exception in '/data/piwik/misc/log-analytics/import_logs.py'
