### ISSUE TITLE
Package mnapoli/phpdocreader is abandoned, you should avoid using it. Use php-di/phpdoc-reader instead.

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#9445]
I've tried installing a new Piwik cloning the master branch and I got this warning message :)

**Comment by sgiehl** [comment]
We would need to update `php-di/php-di` as the version we use requires `mnapoli/phpdocreader` instead of `php-di/phpdoc-reader`

**Comment by sgiehl** [comment]
We won't be able to fix that before 3.0. As all newer versions of `php-di/php-di` require PHP 5.4

**Comment by sgiehl** [comment]
Note: I'll close this ticket as it is almost fixed on 3.0 branch. composer.json was already adjusted, but the composer.lock needs an update, which will for sure be done before the release.

**Comment by tassoman** [comment]
Sure no problem! Have good times
