### ISSUE TITLE
The Chinese name and date can't show normally in image graphs

### ISSUE THREAD

**Issue by ZE3kr** [piwik/piwik#9458]
This bug appear in image graphs when the language is setting to Chinese(I think this bug also appear in other language what use non-english characters)

The characters can't show normally (it's disappear as a square □), I think add more font to piwik or **use English strict in image graphs**.

![iOS screenshot](https://cdn-tlo.b0.upaiyun.com/temp/IMG_1226.PNG)
![Email report screenshot](https://cdn-tlo.b0.upaiyun.com/temp/20.57.31.png)

I found a another issues like this https://github.com/piwik/piwik/issues/1907

**Comment by sgiehl** [comment]
To enable that please check http://piwik.org/faq/how-to-install/faq_142/

**Comment by MrSlawa** [comment]
@sgiehl I can understand why this font is not included by default (15.5 MB) as it is not necessary in most cases.

How about adding Unicode support to the settings? When enabled the server will automatically download the necessary font.

**Comment by sgiehl** [comment]
Feel free to create a Pull Request for that. We currently don't have the manpower to handle a change for that.
If you are not able to create a PR, you may also create a new issue with your (detailed) suggestions. Maybe someone else is able to handle that.
