### ISSUE TITLE
A report is sent even though the user is deleted

### ISSUE THREAD

**Issue by schwindelbub** [piwik/piwik#9474]
Hi,

i've the problem, that a weekly report is send, even the user was deleted.
The user doesn't exist in the 'piwik_report' nor in the 'piwik_user' table. But the report is still send.
I deleted the user through the UI. I don't canceled the report before the user was deleted.

How could that be?
How could I stop the sending?
Is there a cache or somthing else that has to be revoked?

System
Debian 7.9
Apache 2.2.22
PHP 5.4.45-0+deb7u2
Piwik ﻿﻿2.15.0

Best regards,
Schwindelbub

**Comment by sgiehl** [comment]
Maybe the users email address was directly entered in the report details?

**Comment by schwindelbub** [comment]
Thanks @sgiehl that was the right hint! Another user created an report and added an email-address of someone else :) So, nervermind. 

But as a suggestion: It would be create to have as an admin an overview of all created reports in the piwik instance. So the admin has the possibility to delete one or all reports. 
Should we use this ticket as the suggestion? Or should I create a new one?

**Comment by sgiehl** [comment]
Please create a new one for that. Guess the best would be to add that overview somewhere within the administration...
