### ISSUE TITLE
Yesterday real-time map worked and today no data to report

### ISSUE THREAD

**Issue by standupgirl** [piwik/piwik#9487]
Something has changed my real-time visitor map shows not data but all the other plugins do show current data. Can anyone help me quickly?  

We need to show this map at our donor gala dinner tonight so I am getting stressed.

I sent a message to hello@ with my login details to for quick help.  Please, please help me!!!
Site is http://standupgirl.com/piwik/index.php
Diana

**Comment by tsteur** [comment]
I had a quick look and it might be the same reason as https://github.com/piwik/piwik/issues/9381#issuecomment-170391214

For some reason the tracking of cities/ regions stopped a few days ago. I'll close this issue as a duplicate. Please comment in #9381
