### ISSUE TITLE
Site with ssl protocol no tracking

### ISSUE THREAD

**Issue by MESWEB** [piwik/piwik#9488]
My site use https and piwiki is installed in other website using http. Piwik can't track any url with https.

**Comment by kylekatarnls** [comment]
It's not a bug, it's a browser security feature, without it, the encryption would not be guaranteed. Piwik cannot bypass it, you must set up a ProxyPass (with Apache for example) to get an HTTPS Piwik URL.

**Comment by tsteur** [comment]
As mentioned by @kylekatarnls this is a browser security feature. Please consider setting up https for Piwik. You can probably see the related error message in the browser developer tools (console) . Maybe we should make this case more clear in the tracking code generator?
