### ISSUE TITLE
Visitor profile summary uses many different styles

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9489]
See eg 

![image](https://cloud.githubusercontent.com/assets/273120/12224378/a335e6ca-b853-11e5-8bec-92c62c90c2b6.png)

or 
![image](https://cloud.githubusercontent.com/assets/273120/12224380/b33b1c8e-b853-11e5-941c-e17ace79d72a.png)

noticed it while testing #9460 

There are many numbers highlighted (bold) and some are italic etc. I find it quite hard to read because there are just too many different styles. Maybe we could remove them all or reduce it to have only one or max two things bold

**Comment by hpvd** [comment]
**Summary**

Spent a total of **25 min 22s** on the Website, and <br />
performed **46 actions** (21 Pageviews‚ 2 Events, 3 Downloads, 1 Outlinks, 19 Searches) <br />
in **15 visits**.
Converted **2 Goals** (1 Visit Docs, 1 Opens Contact Form).

Site Search Keywords: **at, fuga, quo, amet, minima, ut, hic, vero, dolor, nulla,
nisi, accusamus, odio, culpa, eos, et, maiores, fugit, dignissimos**

Each page took on average **1.675s** to load for this visitor.

**Comment by hpvd** [comment]
btw:
- their is a space between number and "min"
but not between number and "s"

- minute is "min" and second is "s" -> why not "m"+"s" or "min" + "sec"

**Comment by hpvd** [comment]
btw2:
ecommerce data shown at this place should be handled the same way (regarding style, highlighting and linebreak)

**Comment by tsteur** [comment]
Thx for suggestion. That looks much better

![image](https://cloud.githubusercontent.com/assets/273120/12244234/7ac2d770-b907-11e5-8be9-2dc49487f363.png)

Would be nice to see this change :) Re `s` and `min` it might be not easily doable and maybe it's even ok like this. Looks a bit weird maybe to have space between number and `s`.

![image](https://cloud.githubusercontent.com/assets/273120/12244250/9ce5a0ee-b907-11e5-9f86-6bd60b007fea.png)

**Comment by hpvd** [comment]
not only different styles are used in vistor profile, but also different types of data are selected to show:
- from all vsists
- only from last
-  from first and last
=> this builds a distorted image of the visitor
just opend a new ticket:
https://github.com/piwik/piwik/issues/9507

**Comment by hpvd** [comment]
within this ticket one should
- optimize styles not only for the text and values showen in screen shot above, but also for all topics possibly shown in visitor visit summary see https://piwik.org/docs/user-profile/
- make a new screenshot for docu

**Comment by tsteur** [comment]
Cheers for creating the other issue! 

> optimize styles not only for the text and values shown in screenshot above, but also for all topics possibly shown in visitor visit summary see https://piwik.org/docs/user-profile/

Not quite sure what you mean here. Do you mean the right side of the visitor profile that lists all the visits? This would be not as easily doable as it looks unfortunately. It's a bit coupled with the visitor log and the HTML structure is a bit weird etc. see eg https://github.com/piwik/piwik/issues/5229#issuecomment-92124026 

It would be nice to create a new issue for further modifications so we can resolve this issue soon as we want to release a new version of Piwik soon.

**Comment by hpvd** [comment]
sorry for being that cryptic.
Still talking about the left site, where in "visitor visit summary" -if available- these topics do appear:
------
This summary is aggregated using at most the last 100 visits of a visitor’s visits. It displays:
- the total amount of time the visitor spent on your website,
- the total number of page views and visits,
- the total conversions and the total conversions for each goal,
- the total amount of money the visitor spent on your site,
- the total amount of merchandise the visitor abandoned in his cart on your site,
- the internal search keywords used by the visitor,
- and the average amount of time it took your servers to generate a page for the visitor.
----
source: https://piwik.org/docs/user-profile/

=> some of these points are not within the optimized screenshot you posted

=> just want to make sure, that we "optimize" the appearance of all of them,
and afterwords putting updated screenshots to docu

**Comment by tsteur** [comment]
Got it, thx for that. Made some more changes

**Comment by hpvd** [comment]
same type of data put together here, would be perfectly fit also in visitor log (not as sentence but as headwords) see https://github.com/piwik/piwik/issues/9755
