### ISSUE TITLE
Error connecting to database even with correct config file

### ISSUE THREAD

**Issue by oceanspirate** [piwik/piwik#9496]
Hello
We've changed host and so received the error message unable to connect to database when trying to login. I've checked the config file and the database info is correct and the database is working.
The only change is that we no longer use SSL. 
What else should I check?
Thanks
Yona

**Comment by tsteur** [comment]
What's your Piwik and PHP version? Do you use `localhost` or so? Please make sure the settings in `[database]` sectiion `config/config.ini.php` are correct

**Comment by oceanspirate** [comment]
Hello tsteur,
In the change log it says ## Piwik 2.13.0. PHP version is 4.0.10.7 - I believe. It's the version of my PhP myadmin. (Yes, I'm that much of a novice with PHP). I've inherited this website and so working out the details. I have the login info but like a I said I just get a PIWIK error message. Thanks for any insight!
Yona

**Comment by mattab** [comment]
Hi there, please try upgrade to 2.16.0 or our latest beta: http://piwik.org/faq/how-to-update/faq_159/
