### ISSUE TITLE
STRANGE visit times - also in demo (2.16b1?)

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9504]
strange visit times - also in demo
Three cases:

1) 4-14HOURS
wow - these visitors really stay for a long time
=> is the content that interesting???
or is the new heartbeat ping active (see https://github.com/piwik/piwik/issues/8225) and maybe also working when page is in background in browsers with several tabs opened?

2) NO visit time
=>to fast to track?
If so one should show a hint
(to make it consistent)

3) SEVERAL MINUTES
this one looks ok
=> is it?

Please see attachment for details
![2016-01-12_10h50_56](https://cloud.githubusercontent.com/assets/5681880/12261393/19719816-b921-11e5-8340-b883077435b4.png)

**Comment by hpvd** [comment]
for 2)
https://github.com/piwik/piwik/issues/9505

**Comment by hpvd** [comment]
for 1)
nice: lots of people stays that long :-)

![2016-01-12_14h32_33](https://cloud.githubusercontent.com/assets/5681880/12264809/871a01a6-b939-11e5-9221-28a6c19e9101.png)

**Comment by hpvd** [comment]
demo seems to be running v2.16b1

**Comment by tsteur** [comment]
Thx for that, looks like something we should look into on DB level etc. @mattab

**Comment by hpvd** [comment]
hmm first thought the only reason can be
"heart beat also working when page is in background in browsers with several tabs opened",
than I had a look again:
the order of visits is messed up too
=> maybe one is somehow dealing with local times of visitors??
please see attachment

pretty strange

![2016-01-12_21h16_54](https://cloud.githubusercontent.com/assets/5681880/12275789/5602374e-b972-11e5-8231-dded269adfa8.png)

**Comment by hpvd** [comment]
another strange finding:
looking in the sourcecode of tracked website in demo, heartbeat is enable but no special period is set.
With this it should be 15 seconds.
When looking at the shown duration of visits with only one action (thes is where heartbeat helps determine time on page)
- these are not multiples of 15 seconds and
- these are also not multiples of 15 second plus typical loading times (1-4seconds)

**Comment by hpvd** [comment]
just found the date when strange things started:
![2016-01-12_21h46_33](https://cloud.githubusercontent.com/assets/5681880/12276447/2146f068-b976-11e5-87d7-2a2e0bbaa353.png)

**Comment by hpvd** [comment]
btw:
are there already any checks available to automatic catch huge changes like that?
should one open a ticket for this?

**Comment by hpvd** [comment]
also new visits from today are tracked as too long (and are shuffled in ordered)
imho this has two effects:
it's not the best advertising seeing this in a demo
and on the other hand some statistics becomes tainted.
=> One should think of fixing this with high prio
or separate "public demo" from trial and error with betas.

![2016-01-14_20h00_36](https://cloud.githubusercontent.com/assets/5681880/12334283/84843ae4-baf9-11e5-9761-22135cc9feec.png)

**Comment by tsteur** [comment]
FYI: I had a look in the database and in the access logs for one visitor and eg the total time of 7h 50minutes was actually correct for that user. There were thousands of ping requests over several hours for that visitor and also the database entries seem valid. 

I tested manually whether it stops tracking when the tab is no longer focused / opened and it worked.

**Comment by mattab** [comment]
@hpvd if you can reproduce an issue that PIwik is over-tracking, let us know the steps / browsers to use to reproduce. our tests show that it "should" work as expected (track only in active tab). It looks like a lot of users may open a forum thread and leave it there open, for hours! 

Maybe in our ping mechanism we should check that the mouse or some keyboard keys are actually used, before sending a ping? maybe there is no advantage to send a ping if keyboard/mouse are idle...

**Comment by tsteur** [comment]
Also I presume most useful feature would be to really increase ping interval over time as I had eg like 4000 ping requests for one page for the visitor that I analyzed which might not be needed to be that much :) see https://github.com/piwik/piwik/issues/9423

**Comment by hpvd** [comment]
many thanks for looking at this. If that many people have pages opened and keep them active in foreground there is something wrong - how many Monitors they have? do they not have to work? or look at facebook in between? ;-)

Just digging a little deeper:

First shot-> **first result**:
This way one can easily reproduce that foreground detection is not always working:
going to:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-01-15#?module=Live&action=indexVisitorLog&idSite=7&period=day&date=2016-01-15
**right mouse button click** on one of the links to pages people visit " open in new tab"
=> page opens in background and visit time is counting all day long (but has never been seen by the user)

![2016-01-15_06h06_07](https://cloud.githubusercontent.com/assets/5681880/12345859/935ebdc8-bb4e-11e5-9737-8a0a65c783b3.png)

**Comment by hpvd** [comment]
![2016-01-15_06h26_41](https://cloud.githubusercontent.com/assets/5681880/12346076/56ded4b6-bb51-11e5-8ea6-04d9c9aaa397.png)

**Comment by hpvd** [comment]
- **browser** was most of the time **in backgrund** (yes I have to do some other things...)
- **browser tab** was always in background**
but still counting

![2016-01-15_06h46_31](https://cloud.githubusercontent.com/assets/5681880/12346403/3de13492-bb54-11e5-8e8a-552c9a2bf757.png)

**Comment by hpvd** [comment]
@tsteur
>Also I presume most useful feature would be to really increase ping interval over time as I had eg like 4000 ping requests for one page for the visitor that I analyzed which might not be needed to be that much :) see #9423

sure ;-), another idea: clean it afterwards https://github.com/piwik/piwik/issues/9530

**Comment by hpvd** [comment]
just brought the tab to foreground for some time and closed it afterwards
-> (as expected) nothing of this could be seen in tracking 
=> so we do not know if the visitor has seen the page
![2016-01-15_07h10_02](https://cloud.githubusercontent.com/assets/5681880/12346714/4e882686-bb57-11e5-8c28-a68b3ccde46e.png)

**Comment by hpvd** [comment]
maybe before each ping one can simply check if mouse position in browser window is the same than before last ping - if so no new ping is send.

**Comment by tsteur** [comment]
You're right! See comment https://github.com/piwik/piwik/issues/9504#issuecomment-171873380 and following. When opening browser tab in new window with eg right click and even though the tab might have never been opened we do send ping requests. 

We should possibly aim to work on this for 2.16.0

**Comment by hpvd** [comment]
good to hear!
If there is a first solution, please put it to demo where we could reproduce this problem
=> so we can easily see within same testing-enviroment if it helps to get more plausible visiting times.
Otherwise we have to look for other causes for this long visit times...

**Comment by mattab** [comment]
Hi @hpvd demo was updated with our latest beta

**Comment by hpvd** [comment]
Is it already fixed "enough"?
Average time on page is still more than twice as long as it was before heartbeat function was activated.. 
![2016-01-25_16h58_401](https://cloud.githubusercontent.com/assets/5681880/12556424/1a5d71c2-c386-11e5-9499-1feee3bea87f.png)

**Comment by hpvd** [comment]
to see the results of made changes faster by asap adaption of usage by all visitors,
a versioning of piwik's js to bypass visitor's browser caches maybe the way to go
see https://github.com/piwik/piwik/issues/9619

**Comment by mattab** [comment]
Hi @hpvd we've released 2.16.0-RC1 and deployed on demo - how does it look to you?

**Comment by hpvd** [comment]
Hi @mattab
many thanks! We need a little time to have some visitors using it...
btw: Which values would you expect to see in avarage time with know having heart beat enabled?
I'm not really sure about this.
maybe a bit longer because last page visited adds additional time?
or a little shorter because now also one page visits have a time on page which should be considered within calculation of average time? (are they? Or were they even before with 0s?)
or because of both: nearly the same? e.g. +-20% ?

**hmmm the only thing which would not look very plausible to me is a jump of +-100% in average**

**Comment by hpvd** [comment]
please have a look on new https://github.com/piwik/piwik/issues/9645 which may influence avarage time too...

**Comment by tsteur** [comment]
The times on page are expected to be pretty much the same as without heartbeat apart from the last action. The last action should have a longer time on page. With the current implementation it is expected that it should be max around 30 minutes for the last action (depends on a config entry and the type of the last action). How much longer the times are depends on the users and their behaviour.

**Comment by hpvd** [comment]
ok, that's the same I would expect.
With RC1 there is still more than factor 3 difference in average times per visit between without and with heartbeat.
Does anyone has any ideas what may be the reason(s)?

![2016-01-27_21h03_11](https://cloud.githubusercontent.com/assets/5681880/12626680/29acb56a-c53a-11e5-9901-a4117b159d8e.png)

**Comment by tsteur** [comment]
Average time before heart beat was about 2 minutes. When visitors leave tab open for a while at the end of their visit it might be ok that it increases to say 6 minutes? (Also again piwik.js might be still cached for some users I haven't checked). 

It would be interesting to see what the [median](https://en.wikipedia.org/wiki/Median) value was as this one might be more accurate here. When having a low visit duration of say less than 3 minutes which is probably the case for most websites a few users can increase the avg visit duration a lot just by having the tab open for 30 minutes. This might be less of a problem the more visits there are. Would be neat to offer users a median graph as well :)

**Comment by tsteur** [comment]
Also in this case the forum has many visits with only one pageview. Meaning the avg visit duration was rather very low for many visits. Now we are actually able to track the duration also for just one pageview so it might be expected to have 3 times higher avg visit duration.

**Comment by hpvd** [comment]
yes median graph would be interesting.

But shouldn't the "long open last pages of visits" be compensate by the now tracked "only one page visits" (which have a short visit time in total)?

**Comment by hpvd** [comment]
or were this only one page visits put into caclculation with 0s in the past ?

**Comment by tsteur** [comment]
> or were this "only one page visits" put into caculation with 0s in the past ?

I presume so

**Comment by mattab** [comment]
Hi @hpvd if you find any issue with heartbeat logic or reporting, please create new issue, cheers
