### ISSUE TITLE
check needed: calculation of average visit time

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9506]
would be good to check:
Does the calculation of average visit time (e.g. in engagement)
take only the visits having a visit-time tracked (t>0s) into account (without heartbeat enabled this means visits with more than one page view)?
Otherwise results will be messed up...

**Comment by mattab** [comment]
@hpvd Yes, it works as you describe (average visit time is processed by the sum of all generation time divided by the number of requests where the generation time was correctly set).
