### ISSUE TITLE
index.php overwritten

### ISSUE THREAD

**Issue by neoandratal** [piwik/piwik#9508]
The installation was via Softaculous. It did not complete due to a conflict with index.php. The option to over-write was taken. Now the site loads with Piwik rather than my site. when I tried "/login", this error came up:
Class '\MPL\Publisher\DownloadWidget' not found in
/home/xxxxxxxx/public_html/wp-includes/class-wp-widget-factory.php on line 43
Should Piwik be deleted or is there another solution?

**Comment by tsteur** [comment]
Do you mind asking this question in our Forum http://forum.piwik.org/ as it seems to be not a problem with Piwik itself? We can't really help here unfortunately.
