### ISSUE TITLE
Visitor Map shows "Loading data..." but does not load

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9510]
This was regressed recently - the visitor map does not load and shows "Loading data..." undefinitely

The HTTP request to fetch data for the map returned `{"result":"error","message":"API returned an error: The segment 'false' is not valid. at SegmentExpression.php:108"}`

this can be reproduced on demo2

**Comment by sgiehl** [comment]
See https://github.com/piwik/piwik/pull/9495#issuecomment-171069697

**Comment by tsteur** [comment]
This was fixed in https://github.com/piwik/piwik/commit/e62c61cbea52320029052ca42b5ae0d96f9a0e36
