### ISSUE TITLE
Suddenly extremely low visit-log count

### ISSUE THREAD

**Issue by Bitkeeper2015** [piwik/piwik#9518]
Hello!

We are running Piwik since over a year now and typically track around 150 website visits a day.
Since a few days (seems it started 1st of January 2016) we only have 10 visit-logs a day.
When I go to the website myself from my office computer or via the iPhone, my own visit is also not logged, although this always worked before. I definitely do not block Piwik on my computer or iPhone.
However, the log-count is not "zero". Piwik logs some visits every day, just the majority does not get logged.
Does anybody have an idea what it could be? We already updated PHP, which didn't help.
Regards,
Bitkeeper

**Comment by Bitkeeper2015** [comment]
I used Internet Explorer, went to developer section, network section and started recording. Then I called the suspicious website and can see the log.

Besides other entries I can see a http://piwik.pXXXXXX.webspaceconfig.de/piwik.js which is not returning an error.
And we have a /_system/assets/plugins/jquery-1.10.2.min.map that comes up with a not-found error. I am not sure yet if this one is related to Piwik.
But I do not see any line referring to piwik.php

**Comment by Bitkeeper2015** [comment]
Under Console I see three error messages
1) The method setTrackerUrl is registered more than once in "paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation
2) The method setSiteId is registered more than once in "paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation
1) The method enableLinkTracking is registered more than once in "paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation

I have to call the website admin to see if they understand that...

**Comment by Bitkeeper2015** [comment]
We have a suspicion now. It seems our partner Multiview also added a Piwik script in his script.
Depending on which call is faster, it takes the log into their or into our Piwik log.

**Comment by tsteur** [comment]
That sounds very likely. You can workaround this see http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers by creating a tracker instance manually like `Piwik.getTracker(yoursiteid, yoururl)`.
