### ISSUE TITLE
Query generated by Live plugin is too heavy.

### ISSUE THREAD

**Issue by jpraczykppro** [piwik/piwik#9524]
The following API call generates a query which will always end up in a PHP timeout.

`index.php?module=API&method=Live.getMostRecentVisitorId&idSite=2&format=JSON&token_auth=TOKEN`

Generates the following query:

    Info: SELECT sub.* FROM (
				
			SELECT
				log_visit.*
			FROM
				piwik_log_visit AS log_visit
			WHERE
				log_visit.idsite in ('2') 
			ORDER BY
				idsite, visit_last_action_time DESC LIMIT 1
			) AS sub
			GROUP BY sub.idvisit
			ORDER BY sub.visit_last_action_time DESC

**Comment by quba** [comment]
Even though it's limited to 1 record, it fetches all the rows because it has to be ordered by visit_last_action_time. 

Additionally, why is it needed to order it by idsite? 

I'd suggest to add there date range and check e.g. last month or allow to specify the date-range.

**Comment by tsteur** [comment]
The idsite is there so it uses the index I suppose (index = `idsite, visit_last_action_time, config_id`)

**Comment by tsteur** [comment]
Applying by default `last month` or `last week` which can be changed optionally sounds good :+1:
