### ISSUE TITLE
automatic cleaning of unnecessary heartbeat pings from db

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9530]
Since heart beat function produces lots of data, there should be an automatic process to clean unnecessary pings (not need for calculation of visit time) from db
(of course it can only be decided afterwards if they were unnecessary because there was an other action/pageview afterwards)

**Comment by tsteur** [comment]
There are no new records written for ping requests in the database. Only the last one is updated.

The thousands records I mentioned where apache access logs which we cannot delete :)
