### ISSUE TITLE
CDN obfuscates visited pages

### ISSUE THREAD

**Issue by quixoticraindrp** [piwik/piwik#9536]
With Piwik code inserted into Wix.com website, Piwik dashboard reports only the CDN page and not the original requested page.

I.e., where the code probably should report /index.html or /about.html, it is instead showing website_name.usrfiles.com/html/RandomString.html

**Comment by tsteur** [comment]
@quixoticraindrp do you mind asking this question in the forums? http://forum.piwik.org/ We're only handling bugs / features here and the forum is there for questions / support by the community. 

It looks like the Piwik tracking code is not configured correctly. When you ask in the forum, maybe also show the tracking code you use. Ideally maybe link to a website where it is possible to reproduce.

You might have to set a custom URL like `_paq.push(['setCustomUrl', '/index.html'])`

**Comment by quixoticraindrp** [comment]
Dear Thomas,

I did ask this question in the forums. It got zero response, which told me nobody knew the answer. That is why I opened it as a bug. As installed, it does not correctly report its information, and that’s a problem.


--
Sincerely yours,
 
Bacil D. Warren
Owner & Chief Code Monkey, Quixotic Raindrop Software
(520) 333-5228 || http://software.quixoticraindrop.com



On January 17, 2016 at 12:50:06, Thomas Steur (notifications@github.com) wrote:

Closed #9536.

**Comment by quixoticraindrp** [comment]
Dear Thomas,

In addition, setting a custom URL in that way is exceedingly inefficient, since any non-trivial website would require constant changes and different tracking information on every single page.

--
Sincerely yours,
 
Bacil D. Warren
Owner & Chief Code Monkey, Quixotic Raindrop Software
(520) 333-5228 || http://software.quixoticraindrop.com



On January 17, 2016 at 16:45:59, Bacil D. Warren (software@quixoticraindrop.com) wrote:


Dear Thomas,

I did ask this question in the forums. It got zero response, which told me nobody knew the answer. That is why I opened it as a bug. As installed, it does not correctly report its information, and that’s a problem.


--
Sincerely yours,
 
Bacil D. Warren
Owner & Chief Code Monkey, Quixotic Raindrop Software
(520) 333-5228 || http://software.quixoticraindrop.com



On January 17, 2016 at 12:50:06, Thomas Steur (notifications@github.com) wrote:

Closed #9536.

**Comment by tsteur** [comment]
Can you post the link to the forums post? I can have a look

**Comment by tsteur** [comment]
BTW: Maybe one of the existing forums post helps as well but of course depends on the problem

**Comment by quixoticraindrp** [comment]
http://forum.piwik.org/t/how-to-handle-usrfiles-com-cdn/17468
