### ISSUE TITLE
Evolution graph: changing selcted period resets metrics selction

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9552]
Evolution graph e.g. in visitor/overview.
changing selcted period 
e.g. from 15.11.2015 - 18.01.2016 -> 15.12.2015 -18.01.2016
resets metrics selection
e.g.from "average visit time" -> back to "visits"

https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=range&date=2015-11-15,2016-01-18#?module=VisitsSummary&action=index&idSite=7&period=range&date=2015-11-15,2016-01-18

Maybe this happens because metric selction is not witthin url?

**Comment by tsteur** [comment]
This works for me when being logged in. For anonymous users we do currently not persist the change. Can you reproduce it in your Piwik?

**Comment by hpvd** [comment]
sorry did only found this in demo. Being logged in in my own installation it works as expected!
Didn't know that this is working different when being looged in.
I think a hint if this is not possible because one has to log in before is not that easy to integrate?
