### ISSUE TITLE
Long URI get truncated (trackPageView)

### ISSUE THREAD

**Issue by rristow** [piwik/piwik#9563]
There is a limit of 177 chars for URI. This is not enought in some "special" use-cases.
Piwik Version: 2.15.0
Report: indexVisitorLog

**Comment by tsteur** [comment]
It should be possible to save much longer URIs. I'm not quite sure which field or URI you mean? How do you track the URL? Why the JavaScript Tracker? Is maybe only part of the URI visible but the whole URI is tracked?

**Comment by rristow** [comment]
> which field or URI you mean? 
I mean the URI that are showed in the 'Visitor Profile report': http://piwik.org/docs/user-profile/#visitor-profile-report

>> How do you track the URL? 
Hier ist one Snippet from the Javascript-code:
```javascript
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
(...)
```
>>> Why the JavaScript Tracker? 
and Why not?  (I don't want to 'import' nor use the 'bild' way)

>>>> Is maybe only part of the URI visible but the whole URI is tracked?
This is possible, but the problem ist that the Links are also 'broken'.
Is very useful wenn you can just click the link in the report and visit the same page with the same query-string.

**Comment by tsteur** [comment]
The URLs are most likely only shown truncated but tracked and persisted correctly.
The links should not be broken though. What do you mean by they are broken? Is part of the URL at the end missing? How long is the URL with query?

Is it maybe possible that we get access to your Piwik so we can have a quick look?

**Comment by rristow** [comment]
You can reproduce the problem if you visit this [TEST-LINK:](https://dev.mediq.ch/test_request_page?The_key_1=and%20this%20is%20the%20value%201%20of%2030&The_key_2=and%20this%20is%20the%20value%202%20of%2030&The_key_3=and%20this%20is%20the%20value%203%20of%2030&The_key_4=and%20this%20is%20the%20value%204%20of%2030&The_key_5=and%20this%20is%20the%20value%205%20of%2030&The_key_6=and%20this%20is%20the%20value%206%20of%2030&The_key_7=and%20this%20is%20the%20value%207%20of%2030&The_key_8=and%20this%20is%20the%20value%208%20of%2030&The_key_9=and%20this%20is%20the%20value%209%20of%2030&The_key_10=and%20this%20is%20the%20value%2010%20of%2030&The_key_11=and%20this%20is%20the%20value%2011%20of%2030&The_key_12=and%20this%20is%20the%20value%2012%20of%2030&The_key_13=and%20this%20is%20the%20value%2013%20of%2030&The_key_14=and%20this%20is%20the%20value%2014%20of%2030&The_key_15=and%20this%20is%20the%20value%2015%20of%2030&The_key_16=and%20this%20is%20the%20value%2016%20of%2030&The_key_17=and%20this%20is%20the%20value%2017%20of%2030&The_key_18=and%20this%20is%20the%20value%2018%20of%2030&The_key_19=and%20this%20is%20the%20value%2019%20of%2030&The_key_20=and%20this%20is%20the%20value%2020%20of%2030&The_key_21=and%20this%20is%20the%20value%2021%20of%2030&The_key_22=and%20this%20is%20the%20value%2022%20of%2030&The_key_23=and%20this%20is%20the%20value%2023%20of%2030&The_key_24=and%20this%20is%20the%20value%2024%20of%2030&The_key_25=and%20this%20is%20the%20value%2025%20of%2030&The_key_26=and%20this%20is%20the%20value%2026%20of%2030&The_key_27=and%20this%20is%20the%20value%2027%20of%2030&The_key_28=and%20this%20is%20the%20value%2028%20of%2030&The_key_29=and%20this%20is%20the%20value%2029%20of%2030&The_key_30=and%20this%20is%20the%20value%2030%20of%2030)
The link has 30 arguments in the query-string, 

The piwik server for test is here:  http://piwik.mediq.ch
user:guest
pwd: guest4test

If you go to the user's log, you will see that the link ist "broken" and piwik "just" handle until the parameter 24. (char-length: 1359)

**Comment by tsteur** [comment]
Thx I can reproduce (and I removed credentials from your post). Can you try to specify a different value for `page_maximum_length = 1024` in your config.ini.php.

It has to be in `General` section:

```
[General]
page_maximum_length = 2048
```

@mattab I couldn't find a FAQ for this one. Maybe there is one? Or should we create one?

**Comment by tsteur** [comment]
Feel free to comment in case it does not solve this issue @rristow

**Comment by mattab** [comment]
> I couldn't find a FAQ for this one. Maybe there is one? Or should we create one?

Created new FAQ [ How do I correctly track my very long Page URLs and Page Titles without truncating any characters?](https://piwik.org/faq/troubleshooting/faq_21239/)

**Comment by rristow** [comment]
Yes it works and thanks for the FAQ!
