### ISSUE TITLE
DB field piwik_log_visit.location_provider too small

### ISSUE THREAD

**Issue by theyosh** [piwik/piwik#9564]
Default the field piwik_log_visit.location_provider is 100 chars. But that is to small. I have already data that is 153 chars long. So I manually changed the length to about 200 chars.

ex of an location entry: 
Institute of Bioorganic Chemistry Polish Academy o - AS9112 Institute of Bioorganic Chemistry Polish Academy of Science, Poznan Supercomputing and Networ

So I think this field should be updated to a length of 200 chars.
Else you will get exceptions in PHP, and the loglines are not imported / processed.

This is found in version 2.15.0

Error:
2016/01/19 14:23:36 [error] 30919#0: *14833 FastCGI sent in stderr: "PHP message: Error in Piwik (tracker): Error query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'location_provider' at row 1 In query: INSERT INTO piwik_log_visit (idvisitor, config_id, location_ip, idsite, visit_first_action_time, visit_goal_buyer, visit_goal_converted, visit_last_action_time, visitor_days_since_first, visitor_days_since_order, visitor_returning, visitor_count_visits, visit_entry_idaction_name, visit_entry_idaction_url, visit_exit_idaction_name, visit_exit_idaction_url, visit_total_actions, visit_total_searches, referer_keyword, referer_name, referer_type, referer_url, location_browser_lang, config_browser_engine, config_browser_name, config_browser_version, config_device_brand, config_device_model, config_device_type, config_os, config_os_version, visit_total_events, visitor_localtime, visitor_days_since_last, config_resolution, config_cookie, config_director, config_flash, config_gears, config_java, config_pdf, config_quicktime, config_realplayer, confi" while reading response header from upstream, client: 82.150.152.12, server: stats.streamzillacdn.com, request: "POST /piwik.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "stats.streamzillacdn.com"

**Comment by theyosh** [comment]
(Github does not allow me to update the ticket. Stupid system.)

This issue is found in version 2.15.0

**Comment by tsteur** [comment]
We should increase it, however we cannot do this in Piwik 2 as the update could take too long for some database. I'll move it to Piwik 3.0 for now @mattab feel free to change or close if you think it is not needed. 

Not sure why there is a PHP error as we trim the length of a provider to max 100 characters here: https://github.com/piwik/piwik/blob/2.16.0-b3/plugins/Provider/Columns/Provider.php#L77

**Comment by theyosh** [comment]
Not sure if the javascript tracker was causing this or the python import script. I did see that the python import script did not process the data. I would expect that both trackers would use the same php code.
Maybe an different in character set? Not sure, but could be that a multi bite character is counted as one character in PHP and double in MySQL?

And yes, changing this will take a long time with a full table. But I think this could be put with the other issues I had with to small database fields. Like the int vs bigint issue with auto increment fields. And I had also another issue with a small int field.

**Comment by tsteur** [comment]
Yes, it must be a character set problem since both use same PHP code. We should possibly switch to `mb_substr` instead of `substr`. Also for other fields.

We can provide this update with the other issues you created #9565 and https://github.com/piwik/piwik/issues/3288 but we committed to not have any such db updates in Piwik 2.X. Piwik 2.16.0 should be the last minor release of Piwik and then only some patch releases will follow see http://piwik.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/ so we can only include it in Piwik 3

**Comment by theyosh** [comment]
I agree with the upgrade path. So for now, just collect those bugs, and with fix them in a fresh 3.0 version.

**Comment by tsteur** [comment]
fixed in https://github.com/piwik/piwik/pull/10003
