### ISSUE TITLE
DB field piwik_log_visit.visit_total_actions too small

### ISSUE THREAD

**Issue by theyosh** [piwik/piwik#9565]
Again, the database field piwik_log_visit.visit_total_actions is to small. A smallint(5) is not enough. I get the error below. Current value already is: 115011

So also increase this field. I suggest just to use integers. The performance loss between smallint(5) and int(11) is not something to worry about. Also the extra space this will take, is not a problem.

Found in version 2.15.0

Please consider to increase this field so that it does not give the error below.

2016/01/19 17:01:20 [error] 22722#0: *73840 FastCGI sent in stderr: "PHP message: Error in Piwik (tracker): Error query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'visit_total_actions' at row 1 In query: UPDATE piwik_log_visit SET idvisitor = ?, visit_last_action_time = ?, visit_exit_idaction_url = ?,  visit_total_actions = visit_total_actions + 1 , visit_total_time = ?, custom_var_k1 = ?, custom_var_v1 = ? WHERE idsite = ? AND idvisit = ? Parameters: array (   0 => '��	C?�Q',   1 => '2016-01-18 18:51:20',   2 => 377733,   3 => 47156,   4 => 'Not-Bot',   5 => 'PHP-SOAP/5.4.16',   6 => 1,   7 => 378708, )" while reading response header from upstream, client: 82.150.152.12, server: stats.streamzillacdn.com, request: "POST /piwik.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "stats.streamzillacdn.com"

**Comment by tsteur** [comment]
We should increase it indeed. Similar to https://github.com/piwik/piwik/issues/9564 we cannot do this in Piwik 2.X but would be nice to have it in Piwik 3. Since we implemented the heart beat feature the visit_total_time might increase a lot showing hours or days for some users. From my personal browsing behaviour I can tell I have some tabs open for days or weeks without reloading etc and for some it might not stop sending ping requests.

**Comment by tsteur** [comment]
We should also review in general some other fields if more fields need to be updated.

**Comment by tsteur** [comment]
@mattab should we also increase any of

* visitor_count_visits' => 'SMALLINT(5)
* visit_total_events' => 'SMALLINT(5)
* visit_total_time' => 'SMALLINT(5)
* visitor_count_visits' => 'SMALLINT(5)

?

**Comment by mattab** [comment]
@tsteur :+1:  as these would become an issue at some point in the future otherwise.

**Comment by tsteur** [comment]
done
