### ISSUE TITLE
reports for period have invalid filename

### ISSUE THREAD

**Issue by bwagenseil** [piwik/piwik#9580]
The Filename of the attached report file for a report over a period (weekly, monthly, etc) contains a invalid character (en dash / u+2013), which causes some mail clients aren't able to open the mail / attachment.

The filename must built following the rules of the RFC 5987 to allow characters which aren't in ASCII or ISO-8859-1. 

Be aware that the filename is identical to the subject of the mail plus the file extension. I did a quick fix changing all en dashes in ./plugins/Intl/lang/de.json (for my use only in german) into dash inside of ASCII code table.

**Comment by tsteur** [comment]
Do you mean the attachments in sent emails via a scheduled report contain invalid characters?

**Comment by bwagenseil** [comment]
No, the attachments themselves are fine.  I mean the filename of the attachment in the header of the mime body. See following part of source code of a email:

--=_7d9a4ed223249f0d3dfea17c59cb11cc
Content-Type: application/pdf
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="Bericht XXXX - Woche 4.â€“10. Januar 2016.pdf"

**Comment by mattab** [comment]
@bwagenseil could you try to apply this patch: https://patch-diff.githubusercontent.com/raw/piwik/piwik/pull/9632.patch (you only need to patch the changes to `core/Mail.php`) and see if it fixes the issue? if it does not fix the issue please let us know as fast as possible so we may have a chance to fix it in 2.16.0 due in next few days

**Comment by bwagenseil** [comment]
Many thanks for the quick fix and the patch works fine so far.

**Comment by mattab** [comment]
That's great news @bwagenseil thanks for letting us know
