### ISSUE TITLE
Wrong date format for last seen column in users management

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9582]
See the image below:
![screenshot 2016-01-20 13 28 48](https://cloud.githubusercontent.com/assets/647328/12448935/d8e66240-bf79-11e5-9f6e-d651173471e7.png)

Would be nice to change the format to an exact date if the value is greater than 24 hours.

**Comment by RMastop** [comment]
must have been a regression, 2.9.1 it looked like this:
![image](https://cloud.githubusercontent.com/assets/7987117/12449038/ac694b8c-bf7a-11e5-8d0f-5eeec0d6c333.png)

**Comment by tsteur** [comment]
It works for me with latest beta as well. Which Piwik version are you using?

**Comment by quba** [comment]
latest stable

**Comment by gaumondp** [comment]
Was fixed in https://github.com/piwik/piwik/pull/9112

But I find it strange it worked in 2.9 ???

**Comment by mattab** [comment]
fixed in #9112

**Comment by quba** [comment]
@mattab it should be somehow marked as a regression. Cheers!
