### ISSUE TITLE
average time on page determined by using unique pageviews

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9583]
in actions/pages

"average time on page" is  determined by using count of "unique pageviews"
shouldn't it use  "(all) page views"?

please see attachment

![2016-01-20_10h59_26](https://cloud.githubusercontent.com/assets/5681880/12449036/a7e9483c-bf7a-11e5-86c1-1da37a1f9006.png)

**Comment by hpvd** [comment]
may be this is also done
- for determination of other values within staistic (BOUNCE RATE, EXIT RATE AVG. GENERATION TIME)?
- within other statistic pages?

**Comment by tsteur** [comment]
I can confirm it is using the unique values. In https://github.com/piwik/piwik/blob/2.16.0-b4/plugins/Actions/Columns/Metrics/AverageTimeOnPage.php#L36-L39 it mentions to use `nb_visits` which seem to be unique pageviews in the context of Actions.

![image](https://cloud.githubusercontent.com/assets/273120/12460452/8f271f1a-c018-11e5-95d1-7fa18b1d1efc.png)

![image](https://cloud.githubusercontent.com/assets/273120/12460423/73f41176-c018-11e5-9bac-863c3012f277.png)

It is using 39 for `$visits` which is unique pageviews

**Comment by mattab** [comment]
Great find @hpvd !
