### ISSUE TITLE
visitor log: grouping hides information

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9586]
In visitor log visits of the same page are grouped.
This behaviour curently hides information: one could not see (on hover) time on page for each visite.

With this one has no change to unterstand/speculate why this page is requested/visited by the visitor more than one time.

This becomes even more important when optimized implemantation of heartbeat could show more "breaks" within a visit (because page was in background in between)

![2016-01-20_21h46_10](https://cloud.githubusercontent.com/assets/5681880/12462788/644be990-bfc0-11e5-9741-d56ee14a6a64.png)

![2016-01-20_21h53_06](https://cloud.githubusercontent.com/assets/5681880/12462814/8b253d0a-bfc0-11e5-9ba5-30a6fb56484d.png)

**Comment by tsteur** [comment]
Also for last page it does not report correct information about "Time on page". 

Eg if second last one was 13 seconds and last one was 3 hours it would report "13 seconds"

**Comment by hpvd** [comment]
thankyou for having another look on it ...hmm
maybe one can go without grouping, but show a symbol before reloaded/revisited pages
starting with second one. e.g. a simple "=" because its the same page than before...

**Comment by hpvd** [comment]
could be done this way not only for pageviews but for all types of actions...

**Comment by mattab** [comment]
this wasn't actually fixed yet
