### ISSUE TITLE
Users not receiving Email Reports - re-open

### ISSUE THREAD

**Issue by autodeskpiwik** [piwik/piwik#9592]
Hello,

Please refer to existing ticket: Users not receiving Emal Reports #8996 

I followed the instruction to upgrade our Piwik instance to the latest version. This is now complete but we are still unable to generate the e-mail reports as we were expecting to be able to. Please advise on the next course of action.
-Alex

**Comment by tsteur** [comment]
I'm reopening the other issue and will close this one.

**Comment by autodeskpiwik** [comment]
Ok great, thanks Thomas.
