### ISSUE TITLE
After clicking "Update" for a plugin, Plugin is successfully updated but the page is completely white

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9597]
Currently on demo, there are 3 plugins that can be updated to the latest version. I clicked on `Update` link to update the plugin and then the page became white. The plugin was successfully updated.

Expected: after the plugin is updated to lates version, redirect back to the Plugin pages, and show the "Success message" in a green, closable, notification.

**Comment by sgiehl** [comment]
On my local setup updating with latest master works as expected.

**Comment by mattab** [comment]
Works on demo today again... so it is not a bug. maybe it was a temporary issue.
