### ISSUE TITLE
testing in which browsers fixes for correct time on pages (with heartbeat) works fine

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9607]
We need some testing in which browsers
various fixes for correct time on pages (with heartbeat)
like: https://github.com/piwik/piwik/issues/9504 , https://github.com/piwik/piwik/issues/9540 , https://github.com/piwik/piwik/pull/9542 , https://github.com/piwik/piwik/issues/9543 , https://github.com/piwik/piwik/issues/9423 , https://github.com/piwik/piwik/issues/9539
works fine.

=> For this we can look on average time on page for visitors with different browser.
Off course they would differ but not within several hundert percent.

At a first look for visitors using firefox something is working (fixed at least partly) for visitors using chrome it doesn't.
Please see attachment (of course this is a very bad statistics but shows the problem) 
![2016-01-21_09h56_48](https://cloud.githubusercontent.com/assets/5681880/12475936/8ef1adb8-c026-11e5-9dc1-0599c4bf3dbc.png)

=> how could this be done in an efficient way?
for good statitstics one should use a platform with enough visitors like http://demo.piwik.org
(from which also example above was taken from)

**Comment by hpvd** [comment]
this could be a general approach for testing piwik regarding problems with
- different browser 
- different OS
- differnt protocolls (hhtp / https)
- and maybe if nessary also different browser versions

=>
- avarage time on page should be within same magnitude
- average number of each type of actions (pageview, event, download etc) should be within same magnitude

**Comment by tsteur** [comment]
I tested the recent "open in new tab" in Chrome and worked. It is also possible that eg Chrome caches still uses the file from cache whereas Firefox maybe fetched the new `piwik.js` file.

**Comment by hpvd** [comment]
Today average time on website is getting lower. But it's still far away from start value.

Since cache may be a reason, one should think of finding a possibility to always get changes directly to the user. The key should be an intelligent versioning of this file.
Just opend a new issue for this: https://github.com/piwik/piwik/issues/9619

**Comment by Glisse1** [comment]
As of today 14 feb, the heartbeat is working well for me. It updates the total visit time, but not the last action time, as it used to. I have 2 min 36 sec average visit time over the past week, which is very correct from my point of view and from what i can see in logs, and also average times on pages seem to be correct. Heartbeat is working fine in chrome/firefox/opera.. i have very few ie visitors and cant speak for that.

**Comment by mattab** [comment]
We assume Heartbeat is now working well, so closing this issue.

Note the other still opened issues about heartbeat: 
* #9626 Heartbeat / ping requests should only update visit_total_time 
* #9540 Heart beat should count only the time that was actively spent on a page
