### ISSUE TITLE
testing piwik regarding correct statistics for visits with different: browser, OS, protocols...

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9608]
**general approach for testing piwik** regarding correct statistics for vists using
- different browser 
- different OS
- different protocols (http / https)
- and maybe if nessary also different browser versions

**=> comparing for same magnitude** of
- avarage time on page 
- average number of each type of action (pageview, event, download etc) 

usecase identified in https://github.com/piwik/piwik/issues/9607

**=>**
**- what more to test?**
**- how could this be done in an efficient way?**
for good statitstics one should use a platform with enough visitors like http://demo.piwik.org

**Comment by tsteur** [comment]
What I had in mind for this would be https://github.com/piwik/piwik/issues/7066#issuecomment-173675347

**Comment by hpvd** [comment]
The question to answer:
how does this look for different browsers,
OS,
etc?
**Is it near equall?**
Or are ther large differnts not only in absolute values but in trends?

![2016-01-25_16h58_401](https://cloud.githubusercontent.com/assets/5681880/12556578/f424d1ca-c386-11e5-8851-26ae2792b44b.png)

**Comment by tsteur** [comment]
I had a quick look using segment `browserCode==` with different values `FF, IE, CH, SF, OP` and it looked good. Some browsers have to many visits to be 100% sure about it. Note: I didn't each different browser versions.

**Comment by mattab** [comment]
Closing as we couldn't identify a particular problem. To detect "Tracking issues" in different browsers, we have this idea: https://github.com/piwik/piwik/issues/9874
