### ISSUE TITLE
add formating to numbers to make them more clearly visible

### ISSUE THREAD

**Issue by rdrewno** [piwik/piwik#9609]
I would like to make reading data easier in the dashboard. I know how it should look like, but I don't know how to implement. Features are:
1. *Decimal separators* would ease reading long numbers - you could easily say if you are looking at tens of thousands, eg. visits or milions. Separators could be translation specific. For English it would be a comma, but for Polish it should be a white-space.
![20150121 piwik overview](https://cloud.githubusercontent.com/assets/14833473/12482571/ac68968e-c050-11e5-9655-ba894bc36c1b.jpg)
2. *Alignment of numbers in tables* - when numbers are aligned to the right-hand side of a cell it is easier to notice orders of magnitudes. I think that in right-to-left languages numbers could be aligned to the left-hand side.
![20150121 piwik alignment](https://cloud.githubusercontent.com/assets/14833473/12482815/03c4b48e-c052-11e5-9571-85a684c8c6e9.jpg)

**Comment by tsteur** [comment]
Are you using the latest Piwik version? This was done recently I believe. I will close the issue but feel free to comment and/ or reopen in case you are using the latest version.

**Comment by rdrewno** [comment]
You're right. Sorry for trouble.
