### ISSUE TITLE
Deathlock in core:archive

### ISSUE THREAD

**Issue by SR-mkuhn** [piwik/piwik#9620]
Hiho,

we're experiencing database problems with Piwik 2.15.0 at the moment.

<code>
ERROR [2016-01-21 23:26:55] Got invalid response from API request: ?module=API&method=API.get&idSite=876&period=week&date=last2&format=php&segment=entryPageUrl%3D<some filterstring here>&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:111:"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction";}'
ERROR [2016-01-22 00:00:11] 1 total errors during this script execution, please investigate and try and fix these errors.

                                                                                                 
  [Exception]                                                                                    
  1 total errors during this script execution, please investigate and try and fix these errors.  
                                                                                                 

ERROR [2016-01-17 23:25:11] Got invalid response from API request: ?module=API&method=API.get&idSite=874&period=year&date=last2&format=php&segment=entryPageUrl%3D%40<some filterstring here>&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:111:"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction";}'
ERROR [2016-01-18 00:10:31] 1 total errors during this script execution, please investigate and try and fix these errors.

                                                                                                 
  [Exception]                                                                                    
  1 total errors during this script execution, please investigate and try and fix these errors.  
                                                                                                 

ERROR [2016-01-15 23:47:02] Got invalid response from API request: ?module=API&method=API.get&idSite=1044&period=month&date=last2&format=php&segment=entryPageUrl%3D%40<some filterstring here>&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:111:"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction";}'
ERROR [2016-01-16 00:10:58] 1 total errors during this script execution, please investigate and try and fix these errors.

                                                                                                 
  [Exception]                                                                                    
  1 total errors during this script execution, please investigate and try and fix these errors.  
</code>

**Comment by tsteur** [comment]
Which MySQL version are you using? can you reproduce this every time the core archiver is running?

**Comment by mattab** [comment]
See also similar issue in: https://github.com/piwik/piwik/issues/6398
