### ISSUE TITLE
white screen when in want install piwik with any error 

### ISSUE THREAD

**Issue by patteerr** [piwik/piwik#9622]
hello . i want to install piwik on folder and i turned on error display but show any error . and just white screen with 500 server error , i dont know how i can repair this . everything is ok and my server provider says that is any error in server . okease help me 

http://igoods.ir/analytics/

**Comment by sgiehl** [comment]
Do you have access to the webserver logs? Maybe you can find an error message there.

**Comment by mattab** [comment]
see also https://piwik.org/faq/troubleshooting/faq_19489/
