### ISSUE TITLE
Realtime map bug

### ISSUE THREAD

**Issue by alphaonex86** [piwik/piwik#9623]
Hello,

just now, gains on https://stat.first-world.info/index.php?module=CoreHome&action=index&date=2016-01-22&period=day&idSite=1#/?module=UserCountryMap&action=realtimeWorldMap&date=2016-01-22&period=day&idSite=1
I have:
Uncaught TypeError: Cannot read property 'remove' of undefined
3index.php?module=Proxy&action=getCoreJs&cb=78dbd74eab08411104756d3dd7a91d12:2659 Uncaught TypeError: Cannot read property 'remove' of undefined
On line:
lastVisits=[].concat(report).concat(lastVisits).slice(0,maxVisits);oldest=Math.max(lastVisits[lastVisits.length-1].lastActionTimestamp,yesterday);var _removed=0;if(removeOldVisits){visitSymbols.remove(function(r){if(r.lastActionTimestamp<oldest)_removed++;return r.lastActionTimestamp<oldest;});}

Cheers,

**Comment by alphaonex86** [comment]
To fix: rm -Rf tmp/cache/* not done at each update? Do you purge at each update the tmp file?

**Comment by tsteur** [comment]
We do, but only works if the user has proper file permissions. Did I get it right that clearing the cache directory solved the issue for you?

**Comment by alphaonex86** [comment]
Hello, you don't produce update error when the update code can't remove the temporary file? All the file was proper file permissions (user apache2 for file, apache process, and CLI user). Clearing the cache directory solved the issue.

**Comment by tsteur** [comment]
We might do it already but I'm not sure. I will mention it as to be checked in a related issue here: https://github.com/piwik/piwik/issues/9128
