### ISSUE TITLE
Pdf reports doesn't contain any graphs

### ISSUE THREAD

**Issue by arvindsarangi14** [piwik/piwik#9627]
[SmartOffer-Test_-_Monday_25_January_2016_-_Report_data__SMO_UI_Test.pdf](https://github.com/piwik/piwik/files/104010/SmartOffer-Test_-_Monday_25_January_2016_-_Report_data__SMO_UI_Test.pdf)

GD extension is added

**Comment by tsteur** [comment]
Maybe graphs are not included because there is no data?
