### ISSUE TITLE
Error files differences

### ISSUE THREAD

**Issue by totoyo47** [piwik/piwik#9635]
I have downloaded the last version (2.15.0) on the official website.
When i installed on my server, i get always this error :

Différence de taille de fichier : /home/siteweb/piwik2/libs/bower_components/jquery.scrollTo/jquery.scrollTo.min.js (longueur attendue: 2712, rencontrée : 2706)
Différence de taille de fichier : /home/siteweb/piwik2/libs/pChart/class/pData.class.php (longueur attendue: 31449, rencontrée : 30661)
Différence de taille de fichier : /home/siteweb/piwik2/libs/pChart/class/pDraw.class.php (longueur attendue: 327671, rencontrée : 321446)
Différence de taille de fichier : /home/siteweb/piwik2/libs/pChart/class/pImage.class.php (longueur attendue: 20477, rencontrée : 19996)
Différence de taille de fichier : /home/siteweb/piwik2/libs/pChart/class/pPie.class.php (longueur attendue: 67069, rencontrée : 65570)
Différence de taille de fichier : /home/siteweb/piwik2/libs/pChart/GPLv3.txt (longueur attendue: 35823, rencontrée : 35148)
Différence de taille de fichier : /home/siteweb/piwik2/libs/pChart/readme.txt (longueur attendue: 12528, rencontrée : 12386)
Différence de taille de fichier : /home/siteweb/piwik2/vendor/monolog/monolog/.php_cs (longueur attendue: 801, rencontrée : 786)
Différence de taille de fichier : /home/siteweb/piwik2/vendor/piwik/decompress/libs/PclZip/gnu-lgpl.txt (longueur attendue: 26934, rencontrée : 26430)
Différence de taille de fichier : /home/siteweb/piwik2/vendor/piwik/decompress/libs/PclZip/readme.txt (longueur attendue: 22011, rencontrée : 21590)

I try to download the files again, but this erros stay always.

**Comment by tsteur** [comment]
Marking it as duplicate of https://github.com/piwik/piwik/issues/9492 

When you installed it on your server on production, make sure not to install via Git see http://piwik.org/faq/how-to-install/faq_18271/ Always download the ZIP from the website if you want to use Piwik in production
