### ISSUE TITLE
"No data has been recorded yet" when no data from the day

### ISSUE THREAD

**Issue by candaj** [piwik/piwik#9636]
I've noticed that when i upgrade piwik from 2.3.0 to 2.15.0 (and after on 2.16.0b6).

When i open the default page of piwik (i.e. just index.php) if a site have no visit, the is no more an empty dashboard but just the page with "No data has been recorded yet" with no option to choose the range date for example. But if i inject data (with VisitorGenerator plugin for example) the dashboard will be back.

I don't know if it's a bug or not but i think it's more user friendly if we have an empty dashboard and if we can pick the range. 

Is there a workaround for avoid this problem ? 

Regards,

**Comment by sgiehl** [comment]
This page should only be displayed as long as there wasn't any data tracked at all for the current selected website. As soon as the first data was tracked, that page automatically disappears.

**Comment by candaj** [comment]
@sgiehl , thanks for your answer. The problem is that i've data tracked for the selected website. 
Lets me explain : for the range last90 i've that page on the index.php. BUT i've data if in database, i've data if i use the API and i've my dashboard if i use the plugin dashboard directly.

**Comment by sgiehl** [comment]
are you using javascript tracking or the log importer?

**Comment by candaj** [comment]
javascript tracking

**Comment by sgiehl** [comment]
Had a small look at the code. The query used to check if a site has no data is here:
https://github.com/piwik/piwik/blob/master/core/Tracker/Model.php#L420
I can't see a reason why it should return nothing if there is data in the `log_visit` table.

**Comment by candaj** [comment]
Interresting. When I execute the sql request on my db, I've empty row. But I've still data tracked on the "all websites dashboard" for a range of last90. The log_visit table is archived, isn't it ?

**Comment by sgiehl** [comment]
Have you enabled the option to remove old log data? By default the data won't be removed. But if so, it might be possible that there are no entries in the log tables for website that don't have recent data tracked. Guess we would need to extend the check for already archived data

**Comment by candaj** [comment]
Hum, no, the option to remove old log data is disabled.. I don't know the code, but maybe the core:update do a archive of current log in order to speedup or something ?

**Comment by tsteur** [comment]
When you request the API to fetch data, can you make sure you fetch the correct `idSite`?

**Comment by mattab** [comment]
@candaj please re-open if you still experience this issue with Piwik 2.16.0
