### ISSUE TITLE
Log Analytics - Problems viewing data

### ISSUE THREAD

**Issue by nhouli** [piwik/piwik#9637]
Server Logs for my website were imported using the Log Analytics tool. When I try to view a data range of a month or more I am receiving the following message on my dashboard:

![errormessage](https://cloud.githubusercontent.com/assets/16895879/12578028/454e1518-c416-11e5-8580-e9c05fee4a70.jpg)

Also the majority of my page titles are appearing as errors:
![pageerrors](https://cloud.githubusercontent.com/assets/16895879/12577527/b4f36f98-c412-11e5-840c-0c60a23e369a.jpg)

**Comment by tsteur** [comment]
Maybe try to increase memory? Do you get any errors in your server log?
