### ISSUE TITLE
can't annotate visitors graph

### ISSUE THREAD

**Issue by foss-** [piwik/piwik#9638]
tested in FF 43.0.4 + Safari 9.0.3 on OSX 10.11.3. Sample video showing the issue linked below. When trying to annotate the visitors graph, piwik tries to load something, doesn't succeed. User can not annotate.

https://vid.me/nUjV

**Comment by tsteur** [comment]
Can you try it on http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=VisitsSummary&action=index&idSite=7&period=day&date=yesterday ? 

If it works there, can you give us access to your Piwik installation? A temporary user with view access would be enough for us to have a look and debug the problem

**Comment by foss-** [comment]
Temporary test user for debugging purposes setup. How can I send en encrypted mail with that users name + pw to piwik dev team?

**Comment by tsteur** [comment]
We don't have a pgp for our hello@piwik.org (at least I cannot find it on a public key server) @mattab can we maybe create one?

**Comment by mattab** [comment]
@foss-  could you send encrypted email to `thomas` or `matt` att piwik.pro?

**Comment by tsteur** [comment]
Thx for sending us the details. The issue was solved by readding the widget.
