### ISSUE TITLE
2.16RC1: last page visited without time on page

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9645]
After upgrading your demo to RC1 I just a have look on some visits in details.
What seems to be **different than before (B6)**:
visits with
- more than one page visited, and
- last page not loaded more than once,

=> very often (always?) shows **no time on last page visited** (visitor log, hover)
sure this can be fine in some cases but imho not for that many (all?)

**Comment by hpvd** [comment]
hmm, just had a look again, now it seems to work...

**Comment by mattab** [comment]
That's a good news @hpvd ! closing for now, we could reopen if it re-appears
