### ISSUE TITLE
2.16RC1: outgoing links to pages and downloads have time on page

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9646]
Outgoing links to external websites have time on page (hasn't been there in B6)
which is added to total time on website
that's a bit strange ;-)

please see attachement.

the same could be seen for links to downloads on external page
(sorry no screenshot)
-> this is strange also...

3 cases are possible:
- visitor stays on page with link and open link target in new tab in background
- vistor stays on page but put it to background by openen the link target in a new tab in foreground (so from tracking pov  he leaves the pages)
-  vistor follows link in same tab and leave with this the page

![2016-01-27_11h09_26](https://cloud.githubusercontent.com/assets/5681880/12610403/deb53188-c4e7-11e5-8727-d6518d31d26f.png)

**Comment by tsteur** [comment]
We're aware of this. It could be also an event etc and it should have been as well the behaviour before `rc1` I believe?

**Comment by tsteur** [comment]
It's pretty much this and will close it as a duplicate for now: https://github.com/piwik/piwik/issues/9539

@mattab feel free to reopen if you think we can do something there and add some exceptions for downloads, outlinks, events and attribute the time to last pageview instead.
