### ISSUE TITLE
New browser: Brave

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9647]
There is a new open source browser Brave https://www.brave.com/ based on Chrome see eg https://github.com/brave/browser-laptop .

I just got an invite and it reports the browser as Chrome. My user agent is 

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) brave/0.7.9 Chrome/47.0.2526.73 Electron/0.36.2 Safari/537.36`

It should be reported as "Brave 0.7.9". Do you need more information? @sgiehl

**Comment by sgiehl** [comment]
No that's enough information. I'll add the detection to device detector
