### ISSUE TITLE
Create a new widget, added to the default dashboard, advertising Piwik PRO On-Premises

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9649]
Goal of this issue is to add a new widget in the middle column, at the top, added to default dashboard, with a CTA button to Piwik PRO On-Premises landing page.

## Who will see the widget?

*    Widget visible to users who haven't customised their dashboard
*    Widget also visible to users who are newly installing Piwik
*    Widget not visible to exiting Self-Hosted users who have already customised their dashboard

## Proposed texts

these texts could be rotated, and performance tracked with `pk_content` parameter:

*    Discover the power of open-source combined with enterprise-grade support and premium functionalities.

*    Bring your analytics to enterprise level. Upgrade your Piwik platform and receive access to numerous premium features and assistance from our experts.

*    Want Funnel Analytics? Get Premium features and enterprise-grade support from the makers of Piwik.

*    Do you feel the need for SLAs? ....

*    Do you need 24/7 Monitoring And Incident Handling for your Piwik? Get Premium features and enterprise-grade support from the makers of Piwik.

*    Is your Piwik slowing down? The Piwik makers can help with your server setup!

*    Want to know how to use all the exciting features in Piwik? Try our User training to be up to speed with working with Piwik.

*    Did you know you can adjust the look and feel of Piwik to your brand, and even replace "Piwik" with your Product name? Try our White Label product!

## Proposed CTA button text

*    Read more

*    Learn more

**Comment by shahar3012** [comment]
Are you planning to let users to control the appearance of this widget (Active / Inactive). I'm asking because in closed network it's not going to work and I'd like to inactive this widget.

**Comment by sgiehl** [comment]
Widgets can always be removed from the dashboard. And as described, it will only be visible in new installs and unmodified default dashboards.

**Comment by shahar3012** [comment]
Of course it can be removed from dashboard. However if this widget will be in a plugin that can be inactivate it will be great. 
Is it something you could do?
