### ISSUE TITLE
Error message after sending manual e-mail reports. 

### ISSUE THREAD

**Issue by drenkan** [piwik/piwik#9652]
**PHP version 7.0.**

WARNING: /customers/a/b/c/mydomain.nu/httpd.www/libs/pChart/class/pImage.class.php(34): Deprecated - Methods with the same name as their class will not be constructors in a future version of PHP; pImage has a deprecated constructor - Piwik 2.15.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

WARNING: /customers/a/b/c/mydomain.nu/httpd.www/libs/pChart/class/pData.class.php(56): Deprecated - Methods with the same name as their class will not be constructors in a future version of PHP; pData has a deprecated constructor - Piwik 2.15.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by tsteur** [comment]
Thx for that. I can reproduce this with PHP7. The graph renders fine but there is a warning in the log. 

There is no update for this lib so I will have a look if I can quickly fix it myself.
