### ISSUE TITLE
Event Actions and Events Names don't stay flat

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#9660]
In the built-in Actions => Events page, both Events Actions and Event Names sub-reports don't stay flat.

If you go back to Actions Pages and back again to Action Events, both will have revert to Hierarchical.

If you create a custom Dashboard and include Event Actions or Names, both widgets keep the state you last set them. That's what is expected.

**Comment by tsteur** [comment]
I just tried to reproduce but it seems to work fine for me. Are you logged in? Which browser are you using?

**Comment by gaumondp** [comment]
Got the same problem on demo.piwik.org (Crowdfunding for Year 2015 to have some Events in reports).

I'm using Chrome 45 on Windows and tried FF 43 and FF 44.

On Demo, I tried in French and English, same result. The "flattening" isn't remembered.

**Comment by tsteur** [comment]
On demo.piwik.org it won't work as you are probably not logged in (anonymous user). We only save it for logged in users.

**Comment by gaumondp** [comment]
Yes I'm obviously anonymous on Demo but I'm admin on my own Piwik installation and the behavior is the same.

I've upgraded my Chrome (no Ad-block) to v48 and still, choosing "Event Actions"=>Make it flat, then clicking "Event Categories" and back to "Event Actions", the report is back to hierarchical.

**Comment by sgiehl** [comment]
@gaumondp which version of Piwik are you using? Tried to reproduce that on various Piwik 2.16.0 installations as logged in user but couldn't. 

Could you check if you have a database entry in the `piwik_option` table with the `option_name` `viewDataTableParameters_%username%_Events.getName` (while `%username%` needs to be replaced with your piwik username). If there is an enrty, please post the `option_value`

**Comment by gaumondp** [comment]
I'm still on 2.15 (as in January 2016 when I opened this ticket) and I've just check again in this version and it is still there.

As you asked:

```
viewDataTableParameters_me_Events.getAction	{"isFooterExpandedInDashboard":true,"flat":"1","filter_sort_column":"label","filter_sort_order":"des...	0
viewDataTableParameters_me_Events.getCategory	{"isFooterExpandedInDashboard":true,"flat":"1","filter_sort_column":"","include_aggregate_rows":"0"}	0
viewDataTableParameters_me_Events.getName	{"isFooterExpandedInDashboard":true,"flat":"1"}
```

**Comment by mattab** [comment]
Probably a 2.15.0 bug - if you still have this issue in Piwik 2.16.1 or later please re-open

**Comment by gaumondp** [comment]
Piwik 2.16.1 works fine ! Sorry for not telling you before.

**Comment by mattab** [comment]
Great to hear!
