### ISSUE TITLE
Improve all websites dashboard performance

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9662]
All websites dashboard loads without any hassle when fetched for single day or week. It is problematic when you fetch 2 days for example, merging the data lasts for very long and usually does not finish. This occurrence was observed in instance with around 2k websites, this definitely is important for testing purposes.

**Comment by tsteur** [comment]
We've spent lots of time on improving the performance for All Websites and Range dates. Both kinda came to a limit where we can't do much more improvements easily. However, we can always have a look at a XHProf profile to see if there's maybe room for improvements. Can you provide us access to the instance? Ideally with XHProf installed?

What means "very long"? I presume the data was pre-archived right? And browser-archiving is disabled?

**Comment by mgonera** [comment]
@tsteur shall I provide you SSH access to this instance? Is below XHProf what you need?

ROOT => db-2.machine:~# apt-cache policy php5-xhprof
php5-xhprof:
  Installed: (none)
  Candidate: 1:0.9.4-1~dotdeb+php56+7.1
  Package pin: 1:0.9.4-1~dotdeb+php56+7.1
  Version table:
     1:0.9.4-1~dotdeb+php56+7.1 1005
        500 http://packages.dotdeb.org/ wheezy-php56/all amd64 Packages

**Comment by tsteur** [comment]
Yes ssh access would be great. Yeah it looks like the correct package. Also the extension needs to be activated.

**Comment by mattab** [comment]
> What means "very long"? I presume the data was pre-archived right? And browser-archiving is disabled? 

Hi @mgonera  if you still need some help investigating slow All Websites dashboard, please notify Thomas, otherwise I suggest to close this issue.

**Comment by mgonera** [comment]
@mattab the problem persists. All websites dashboard loads fine for single day, but times out when loaded for date range of 2 days, despite these days being archived.

**Comment by mattab** [comment]
@tsteur maybe you could investigate this one next week? (I'll ask for server connection details / xhprof)

**Comment by tsteur** [comment]
I can have a look if having a connection to server or xhprof profile of it.

Is the latest Piwik version used?
