### ISSUE TITLE
Translation strings show up with placeholders in UI

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9670]
This regressed I think from #9546 - some of the strings are displayed with placeholders in the UI eg.

![not translated](https://cloud.githubusercontent.com/assets/466765/12708857/b7c318e4-c909-11e5-9429-740b3040ba8c.png)

ping @sgiehl

**Comment by tsteur** [comment]
Possibly caused by https://github.com/piwik/piwik/blob/2.16.0-rc1/plugins/CoreHome/javascripts/dataTable.js#L1313 ?

Maybe translation should be changed to `This report is not pivoted %1$s Pivot by %1$s` and then we update the line in JavaScript
