### ISSUE TITLE
Improve error handling and message when a non-piwik URL is specified in import_logs.py

### ISSUE THREAD

**Issue by MagicFab** [piwik/piwik#9673]
When using import_logs.py with non-Piwik URL the URL parameter specified should be a Piwik server. If it's not, the corresponding error thrown is not very helpful. It could be improved to specify its URL parameter is wrong.

[A forum user had this problem, as described here](http://forum.piwik.org/t/import-logs-py-except-piwik-error-e/16647/2).

**Comment by mattab** [comment]
Hi @MagicFab - hope you are well! it would be great if you could re-created this issue in the log analytics issue tracker here: https://github.com/piwik/piwik-log-analytics/issues
