### ISSUE TITLE
tiny: optimize presentation of plugins on piwik.org

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9680]
optimize presentation of plugins on piwik.org

please see attachement with comparison of piwik backend marketplace and presentation on piwik.org
screenshots from FF 44

![2016-02-02_06h39_23](https://cloud.githubusercontent.com/assets/5681880/12741080/a68abf3a-c979-11e5-9e0f-ec436d5566c4.png)

**Comment by tsteur** [comment]
thx. I added it locally and will deploy it later.
