### ISSUE TITLE
marketplace: sorting order of plugins "newest"

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9681]
In Piwiks backend marketplace the sorting order of plugins "newest"
is a little confusing

what's the goal for sorting:
a) sorting for "first release date"
b) last updated

if a) this date should be shown otherwise one didn't get it easily beacause one only see last updated
if b) something is broking and maybe also name of  filter should be changed "newest => "last updated"

please see attachement
![2016-02-02_07h00_31](https://cloud.githubusercontent.com/assets/5681880/12741390/1ac0730c-c97c-11e5-858e-0814a445edad.png)

**Comment by tsteur** [comment]
Thx! That's a bug. I fixed it already locally and will deploy it later on the Marketplace as I will make some more changes there anyway
