### ISSUE TITLE
Next page doesn't work in segmented visitor log

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/piwik#9687]
Steps to reproduce:
1. Go to the _Action -> pages_
2. Open some entry from the list ( /index ) by clicking on _Open segmented visitor log_
3. Scroll to the bottom and try click _Next_
4. You should see the notice "_There is no data for this report._"

![segmented visitor log](https://cloud.githubusercontent.com/assets/7943292/12780967/999c92fa-ca71-11e5-9859-350a3ef77688.png)

**Comment by tsteur** [comment]
Thx for creating this issue! This is a known issue that is unfortunately not trivial to solve. The original issue is here: https://github.com/piwik/piwik/issues/9200
