### ISSUE TITLE
JS method to specify value of campaign parameters

### ISSUE THREAD

**Issue by tomasztomik** [piwik/piwik#9688]
Hello,

It would be good to have possibility to specify value of campaign parameters (like pk_campaign) using Java Script Tracking Client method. Actually it can be done only via HTTP Tracker parameters, which is not convenient way.

This idea came just from real life example.

**Comment by quba** [comment]
Actually, you can. See http://piwik.org/faq/how-to/faq_120/

**Comment by tomasztomik** [comment]
Sorry, I meant method to specify **value **of campaign parameters, will update issue in a moment.

**Comment by quba** [comment]
It's rather a hack, but should work.
```
_paq.push(['setCustomUrl', document.URL + '&pk_campaign=campaignName']);
```

**Comment by tsteur** [comment]
Can you explain the use case a little? It would be nice to know what is expected to happen etc. Setting campaign parameters might create new visits etc so it would be good to know a little more about the background.

**Comment by tomasztomik** [comment]
It is a question and use case from customer, I'll paste email content:

> Do you know if it is possible to set the value of the pk_campaign over the API?
> For example: I have a new visitor, and I don’t take the value of the pk_campaign parameter from the URL. However I know that the value of the pk_campaign for this visit should be campaign_1. Can I set through the Piwil API the value of the pk_campaign for this visit to campaign_1?

**Comment by tsteur** [comment]
Got it, what @quba mentioned in https://github.com/piwik/piwik/issues/9688#issuecomment-179318052 would be the current way to do it. It's a little hack but not too bad, that's what the method is there for... 

Someone has to be very carefully with the implementation as when set to late, and already a tracking request was sent, we'd create too many visits all the time. Basically we would create for each visit 2 visits (one with campaign, and one without). 

Not sure if we can close this issue, or should create an FAQ for this (if not exists yet).

We'd probably not add a method for this as it may result in too many visits tracked when not used correctly. Also not sure how it would work when say someone does `setCampaignParameter(name, ...)` followed by `setCustomUrl(url)` ... etc. Should we still apply the campaign to the custom url or would setCustomUrl overwrite this again etc. For now it would be best to go with @quba suggestion

**Comment by mattab** [comment]
Hi @tomasztomik 

 * I suppose we don't need a new JS function as `setCustomUrl` sounds good enough in this case.
 * if you would like to suggest a new small FAQ for this question/use case, please share your suggestion here or privately, and i'll be glad to add this new FAQ :+1:
