### ISSUE TITLE
Reset password, error logging in. “You’ve been blocked, because we had too many failed login attempts from You”

### ISSUE THREAD

**Issue by UptakeFieldSupport** [piwik/piwik#9690]
I was logged into Piwik as an admin and logged out. When I tried logging back in, I received the error message, "You've been blocked, because we had too many failed login attempts from You". I tried logging in again, same error. I clicked on Lost Password and reset my password. I clicked on the link that was sent to my email and tried logging in with the new credentials, and it gave me a different error message, "you don't have access to this place!".

Tried logging in again, got another error message: "Error: Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Piwik to accept the proxy header that forwards the Host header. Also, check that your Referrer header is sent correctly."

How can I fix this so that I can log back in?

**Comment by tsteur** [comment]
We do not have a logic in Piwik core itself to block you because of too many failed login attempts. Are you using any custom plugins, maybe from the Marketplace?

**Comment by UptakeFieldSupport** [comment]
I don't believe I am using any custom plugins.  I am not able to log in right now so I can't verify.  All of a sudden, it booted me out.  I originally noticed this problem when I created a new user for someone else.  I am an admin and the new user I created it for was getting those same error messages.  I tried to replicate that by logging out, and logging back in and that's when I saw the error message.

**Comment by UptakeFieldSupport** [comment]
I take that back, I installed the 2.15 plugin package a couple months ago which included these 9 items: 
![piwikplugins](https://cloud.githubusercontent.com/assets/17052271/12794402/6e82ef8e-ca7a-11e5-9863-1ab3e7da483f.JPG)

**Comment by mattab** [comment]
Hi @UptakeFieldSupport 
Thanks for the report. It's likely a bug or issue with `PasswordPolicy` plugin. we will investigate and reply to you on the forum thread http://forum.piwik.org/t/reset-password-error-logging-in-youve-been-blocked-because-we-had-too-many-failed-login-attempts-from-you/17886 - in the meantime, if you want to get access back, you can disable the `PasswordPolicy` plugin.

cc @quba

**Comment by UptakeFieldSupport** [comment]
@mattab that worked perfectly!  Thanks for your help!
