### ISSUE TITLE
The filter "piwikProCampaignParameters" does not exist in "ajaxMacros.twig" at line 34

### ISSUE THREAD

**Issue by markwaters** [piwik/piwik#9703]
I performed a single-click auto-upgrade this morning after seeing the alert.

No errors during the upgrade process.

Now when I try and open Piwik I see this :-

"The filter "piwikProCampaignParameters" does not exist in "ajaxMacros.twig" at line 34"

**Comment by sgiehl** [comment]
Try cleaning the `tmp` directory of piwik

**Comment by gaumondp** [comment]
I still don't understand why wiping /tmp/ isn't still part of Upgrades and Plugins activations...

**Comment by markwaters** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I have deleted the entire line 34 and restarted the webserver to clear
the xcache and after a database upgrade its all working again.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)

iQIcBAEBCgAGBQJWs3vJAAoJEFF+5OlxuacGUnYP/1/I2gMlqj6DeLJoobx/cXE0
+Z/pnc07GYZc8JmQg7J9B0kZr5JJmuxlCKlQ/XmFE+dwUByt1JoI1VM33KN9E4Sb
/vQqCXp/+ppuGZGlMqmcUjn8RUdDkNQr63GYF0tN98/ZB53i7CQQTyfzgjVz/IoG
y/3vIsxiFhF5yITolEmV+NkLqOULolLrGd3kPHxj33T2ckw4JZ4D0uMH0zJf52er
6j1jmKY+MC92HofRkiOgPr0nuNE+aAEOD/nlCEX/hi6ln513CBbfAP9tSRc+Y9jC
9KCUEGVpNhFufJfMXAES7R/V9fXFJgWULetFOaGEpCwJ8icv8dyfrhIHgRoasAND
TWlPg0jNZulHE0YSZmmh9Rv0/Nmv7duzJ3xfKV9lWWWyxnAT7ml7Dg+RAViTo6C5
gHLGl+1Y14q2oLL637GoCal99d0RHzJm3KHEAW46zhH7WxX2h9ccdXKOImrTNgwQ
c33/exPm+dWoIsgpgdABtzXi/NBdnIVsPJX53HUrNWS0G1TykXBBw1aA7oG0iJhA
ZiBT38SBlPWvEK5ew2JUk4pmzf5MXsbqop1yPUnu8zYetHuKMhhtn6gPKjFiqeLq
nF8Hft9pIEdhg63JyWojx/gp/DqZS+awoYCJI3wqxVj0kd9rJYn8xijhqP0Xi3mN
k2ajvacxI3ZzYUvx5KuG
=s/0Z
-----END PGP SIGNATURE-----

**Comment by tsteur** [comment]
> I still don't understand why wiping /tmp/ isn't still part of Upgrades and Plugins activations...

The files *should* be cleaned during update. For template files: There used to be a bug that template files weren't actually cleared but this was fixed in 2.11 here: https://github.com/piwik/piwik/commit/07fd55f9e53533b5718fd43a86cdb31317dd0fa2 

It's possible user was updating from an older Piwik (<= Piwik 2.11)
