### ISSUE TITLE
Error after upgrade to 2.16.0

### ISSUE THREAD

**Issue by CannyDuck** [piwik/piwik#9704]
After upgrading my installation to 2.16.0 I get this JavaScript error and see no stats anymore:

`ReferenceError: DataTable_RowActions_Transitions is not defined
Quelldatei: .../index.php?module=Proxy&action=getCoreJs&cb=43f191bb6d2019ae495832ef5f01689c
Zeile: 2062`

**Comment by sgiehl** [comment]
Please try cleaning the `tmp` directory of Piwik.

**Comment by CannyDuck** [comment]
I deleted all files from the `tmp` directory. No change, the error still occurs.

**Comment by sgiehl** [comment]
Could you look up a more detailed error description with maybe a stack trace in the dev tools of your browser?

**Comment by CannyDuck** [comment]
Affected code:

`DataTable_RowActions_Transitions.registerReport({isAvailableOnReport:function(dataTableParams){return isPageUrlReport(dataTableParams);},isAvailableOnRow:function(dataTableParams,tr){return isPageUrlReport(dataTableParams)&&tr.find('> td:first span.label').parent().is('a')},trigger:function(tr,e,subTableLabel){var link=getLinkForTransitionAndOverlayPopover(tr);this.openPopover('url:'+link);}});DataTable_RowActions_Transitions.registerReport({isAvailableOnReport:function(dataTableParams){return isPageTitleReport(dataTableParams);},isAvailableOnRow:function(dataTableParams,tr){return isPageTitleReport(dataTableParams);},trigger:function(tr,e,subTableLabel){DataTable_RowAction.prototype.trigger.apply(this,[tr,e,subTableLabel]);}});DataTable_RowActions_Overlay.registerReport({isAvailableOnReport:function(dataTableParams){return isPageUrlReport(dataTableParams);},onClick:function(actionA,tr,e){return{link:getLinkForTransitionAndOverlayPopover(tr),segment:null}}});});`

**Comment by tsteur** [comment]
Can you check if the `Transitions` plugin is enabled in "Administration => Plugins"? 

This is a bug as we're not checking everywhere whether this row action is actually available. We either need to load `transitions.js` in `CoreHome` or check for availability of this class

**Comment by chris246** [comment]
Same bug here

**Comment by tsteur** [comment]
Can you check if the Transitions plugin is enabled in "Administration => Plugins"? This will solve it for now.

**Comment by CannyDuck** [comment]
That solved it for me. Thanks.

**Comment by chris246** [comment]
It is.
I've disabled and re-enabled it - no effect.
And I've cleared the tmp-directory.

**Comment by tsteur** [comment]
Did you clear the browser cache?

**Comment by tsteur** [comment]
FYI: Issues fix for this here: https://github.com/piwik/piwik/pull/9713

**Comment by chris246** [comment]
Used Ctrl + F5 to reload (Firefox 44.0)

Thanks

**Comment by chris246** [comment]
Sorry, in my case, the Overlay-Plugin was disabled.
Re-enabling fixed the issue.
Maybe you want to extend fix #9713

**Comment by tsteur** [comment]
Thx for letting us know @chris246 . There should be a fix for Overlay plugin in #9713 

Cheers
