### ISSUE TITLE
show city and region in Visitor log (without hover)

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9705]
In Visitor Log:
On none widely international visited websites, city is even more intersting than already shown country.

So it would be good to show the city directly in in visitor log without the need to hover the country flag (where it is already shown)

Please see attachement.

![2016-02-04_13h41_41](https://cloud.githubusercontent.com/assets/5681880/12815356/43237710-cb46-11e5-8a03-50c6665f47c0.png)

**Comment by hpvd** [comment]
it's the updated (based on 2.16 design)
and more concrete version of https://github.com/piwik/piwik/issues/4406

**Comment by tsteur** [comment]
That would be really useful :+1: Like it :)

**Comment by hpvd** [comment]
it would be also great to show the region, because sometimes
- you doesn't know the shown city because it's to tiny
- there are cities with the same name in different regions

in example above it would be:
flag of germany, Nürnberg, Bayern
