### ISSUE TITLE
Follow-Up to #9708

### ISSUE THREAD

**Issue by stefan-niedermann** [piwik/piwik#9714]
![unbenannt](https://cloud.githubusercontent.com/assets/4741199/12840191/42861ed4-cbe1-11e5-9b59-92c4ce833d41.PNG)

I am not able to comment issue #9708, so here is an edit:

Thanks for help, i fixed it.

- xxxx-prefix is my database name (i removed the real name - sry)
- the table has been deleted (no idea why. i recreated it from the instance of friend)

```sql

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `piwik_user_language` (
  `login` varchar(100) NOT NULL,
  `language` varchar(10) NOT NULL,
  PRIMARY KEY (`login`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `piwik_user_language` (`login`, `language`) VALUES
('<username>', 'de');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
```

Regards

**Comment by sgiehl** [comment]
You did an update, right? Which version did you update from?

**Comment by tsteur** [comment]
I reopened https://github.com/piwik/piwik/issues/9708 so you can comment there and will close this one. As @sgiehl asked do you mind answering from which version you updated in the other issue?
