### ISSUE TITLE
Translation Problem at Dashboard / Menu - it appears 'General_Website'

### ISSUE THREAD

**Issue by BSG2000** [piwik/piwik#9715]
I have just updated a Piwik version of 2.15.0 to 2.16.0. The installation will track 2 sites, but you can not switch between these two sites in dashboard. The name of the page will not be parsed, it only appears "**{{'General_Website' | translate}}**".
The menu item is not clickable.
![05-02-_2016_09-47-18](https://cloud.githubusercontent.com/assets/5871824/12841686/cf60f5fc-cbed-11e5-9adc-10d5524c3c2a.png)

Here the full span element:
```
<span>{{ 'General_Website'| translate }}:
            <span ng-bind-html="selectedSite.name || model.firstSiteName">?</span>
</span>
```

**Comment by sgiehl** [comment]
have you tried to clean the `tmp` directory of Piwik?

**Comment by BSG2000** [comment]
Yes, I did... but doesn't work.

**Comment by tsteur** [comment]
Thx for the report. We have fixed this one already in https://github.com/piwik/piwik/pull/9712 see https://github.com/piwik/piwik/pull/9712/files You might want to apply the same changes. You'll likely see a similar error afterwards somewhere else. We haven't fixed similar errors yet but hope to fix them soon. If you are having a technical background: You can possibly make your Piwik work again by replacing some whitespace with a correct whitespace where the error occurs next.
