### ISSUE TITLE
Do not view day of week

### ISSUE THREAD

**Issue by simpleuser99** [piwik/piwik#9717]
Hello. 
Since I update piwik to 2.15.0 , I didn't view day of week. I thought when I update to 2.16 version, these bug be fix. Unfortunately there is a bug.

![piwik_bug](https://cloud.githubusercontent.com/assets/11714750/12844409/2bedee2a-cc10-11e5-9d7d-f71e8250073f.PNG)

How can I fix it?

**Comment by sgiehl** [comment]
What exactly is the problem? Would you mind switching to english and check if it still appears?

**Comment by simpleuser99** [comment]
THe problem is i do not view day of week on russian language. But I view day of weeks if I use english 
![piwik_en](https://cloud.githubusercontent.com/assets/11714750/12844778/a100fe8a-cc12-11e5-9105-a7fd3d1cba0c.png)
Compare screenshots please. In english i view that day of week is Sun(Sunday), but in russian version I don't view day of week. Understand?

**Comment by sgiehl** [comment]
Ah, ok. Now that's clear for me what the problem is. thx
Will have a look.

**Comment by sgiehl** [comment]
Guess I found the problem.

You could try to fix it by updating this file:
https://github.com/piwik/piwik/blob/master/core/Date.php#L721-L725

Simply replace all the uppercase "C" with a lowercase "c" in the marked lines.

Need to test that later, then I will issue a PR to fix it

**Comment by simpleuser99** [comment]
I manual change "C" to "c" and I have good result. Thx!
