### ISSUE TITLE
Empty Dashboard after Upgrad from 2.15 to 2.16 - JS Error

### ISSUE THREAD

**Issue by mosag** [piwik/piwik#9718]
After Upgrading I get an empty Dashboards for all websites.
![empty-dashboard](https://cloud.githubusercontent.com/assets/525925/12844695/46061224-cc01-11e5-862c-614cb9bf97fd.jpg)
On the JS Console I get the following error:
**`ReferenceError: DataTable_RowActions_Transitions is not defined rowactions.js:28:5`**

I've cleared browser cache, /tmp folder, added [Development] disable_merged_assets = 1 in config file, but nothing's happen .

**Comment by mattab** [comment]
Hi @mosag - please enable Transitions plugin in Administration > plugins. (we will fix this issue in 2.16.1 so you don't need to activate the plugin).

**Comment by mattab** [comment]
Duplicate: https://github.com/piwik/piwik/issues/9704#issuecomment-180347799

**Comment by mosag** [comment]
Thanks mattab, sorry for duplicate, I could'nt delete my issue and I can't write a comment this afternoon, github tells me "somethin went wrong ...".
I have to active Transition **AND Overlay** Plugin to view the dashboard again.
