### ISSUE TITLE
Piwik shows confusing screen resolutions like 2112.0000 or 1848.0000 instead of the common format 1680x1050

### ISSUE THREAD

**Issue by Cymassius** [piwik/piwik#9723]
As i mentioned in the summary, my piwik server shows confusing screen resolutions
like 2112.0000 or 1848.0000 instead of the normal format number x number.

I am using Piwik 2.16.0.

Please find a screenshot of the resolution output attached.
<img width="956" alt="brocken_resolutions" src="https://cloud.githubusercontent.com/assets/17107264/12871642/cc61d39c-cd84-11e5-86b8-84663b3d46bf.PNG">

**Comment by tsteur** [comment]
It looks like a cached version of `piwik.js` is maybe still used by some of your users (browser cache). This should have been fixed in 2.16.0. Have you experienced this issue before 2.16.0?

**Comment by Cymassius** [comment]
Thank you for the hint. I made an update to 2.16.0 a few days ago and indeed it can be that this error does not happend again since that. I will have a look on the screen resolutions in the next days.

My thought was, if the new version will fix this bug, also the stored resoultions will be fixed. I dont thought that a bug fix will only prevent new resolution corruptions .

**Comment by tsteur** [comment]
Let me know how it goes. I will close the issue for now but we can reopen or comment any time.

**Comment by mattab** [comment]
Btw: reopened a variation of this issue in: https://github.com/piwik/piwik/issues/9911
