### ISSUE TITLE
top_controls not displayed in Chrome 

### ISSUE THREAD

**Issue by SpaceRichard** [piwik/piwik#9724]
I noticed since some weeks that the top_controls (Website, Date / Time, etc ) are not displayed in Chrome (48.0). The same installation(s) in Safari and Firefox it is displayed normal, I tested it with 3 installations of piwik on different servers, all with the same behavior. 

I got the following warning at Chrome/Developer Tools:
jquery.js:9592 
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by tsteur** [comment]
Can you post a screenshot or maybe send us credentials to your Piwik so we can have a look? A user with view access and only one access to one website would be good enough. You could probably create a new website for this so we can't see any of your data. If so, please send information about your Piwik to hello at piwik.org . Apart from this make sure there is no adblocker or something similar active

**Comment by tsteur** [comment]
In case you are not using the latest Piwik version: Please update :)

**Comment by SpaceRichard** [comment]
Yes it's the current version, I was hoping the latest update will fix this.

I had the chance to test it on a different computer and there it's looks fine .. So I guess it's a local issue ...
