### ISSUE TITLE
2.16.0 upgrade error auto archiving 

### ISSUE THREAD

**Issue by mvdepot** [piwik/piwik#9725]
`ERROR [2016-02-05 21:42:02] Got invalid response from API request: ?module=API&method=API.get&idSite=3&period=day&date=last52&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:352:"Your Piwik codebase is running the old version 2.15.0 and we have detected that your Piwik Database has already been upgraded to the newer version 2.16.0. Maybe your Piwik administrators are currently finishing the upgrade process. Please try again in a few minutes. If you still have this issue please contact your Piwik administrator for assistance. ";}'`

new error from chron after upgrading to 2.16.0

Also get the following, but I assume it is related the the first, any ideas?:

`ERROR [2016-02-05 21:42:02] Empty or invalid response '' for website id 3, Time elapsed: 0.566s, skipping
ERROR [2016-02-05 21:42:02] 2 total errors during this script execution, please investigate and try and fix these errors.`

**Comment by tsteur** [comment]
Have you updated all Piwik files (and cleared any opcache if needed)? Sounds like your Piwik is still running on 2.15.0 but database is 2.16.0. Have a look here: http://piwik.org/docs/update/#the-manual-three-step-update

I think it is related to the first but hard to tell as there's not much to see.

**Comment by mvdepot** [comment]
Thanks for the ideas. Piwik says it is running 2.16 in the admin console. Opcache is not enabled on cli, but I cleared it anyhow with no improvement to the auto archive errors. Also restarted apache, no change.  I will try the manual upgrade, have never had to do that in the past.

**Comment by tsteur** [comment]
Just FYI: The cron archiver might use HTTP and go via web to send archiving requests depending on the operating system and installed packages. That's why I mentioned re opcache. Let me know how it goes after the manual update. Don't forget to backup `config/config.ini.php`

**Comment by mvdepot** [comment]
tried a differential update, no help. did a full replace update - no help.
while I was logged into the server I grabbed the autoupdate command from the cron job to run it from the console and found the issue: the cron job was not changed when we updated domain names.
Thank you for the assistance tsteur, have a great week. MVD
