### ISSUE TITLE
Empty dashboard after upgrade from 2.15.0 to 2.16.0

### ISSUE THREAD

**Issue by Jan-E** [piwik/piwik#9727]
The upgrade to 2.16.0 was far from easy to me: I ended up with an empty dashboard. After a couple of hours of debugging I found out that this was caused by the fact, that I had deactivated the Overlay plugin. The Transitions plugin was active, though.

This caused a Javascript error 'undefined variable Datatable_Rowactions_Overlay' and effectively ended the loading of all widgets.

The bug is probably introduced by this commit:
https://github.com/piwik/piwik/commit/8324df36220fd23ea81cce8c4550047e76e7ecf1

There should be a check to see if the Overlay plugin is activated before trying to access Datatable_Rowactions_Overlay.

**Comment by tsteur** [comment]
Thx for your feedback. I mark it as a duplicate and it's fixed here: https://github.com/piwik/piwik/pull/9713 (to workaround enable the Overlay plugin and maybe Transitions plugin for now)

**Comment by Jan-E** [comment]
OK, thanks for fixing. Sorry I missed that issue (because it was closed already).
