### ISSUE TITLE
Site Search category not displayed in Visitor log

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9732]
Standard search & result finding process seems to be not trackable well:

1. doing a search e.g. for "myword"
2. results page opens "myword"
3. use a filter e.g. "myfilter"
4. follow one of the links to pages shown on result page

Visitor log shows  only a second search for "myword"
Filter usage is not shown

![2016-02-08_15h36_56](https://cloud.githubusercontent.com/assets/5681880/12888701/9cde43ba-ce7b-11e5-9108-8bf4e72d889d.png)

This is how url structure for this looks as an example within  Magento:

searching for "myword"
...site.de/catalogsearch/result/?q=myword&cat=

and than applying a filter of name 
"myfilter"

...site.de/catalogsearch/result/index/?cat=36&q=myword

("myfilter" is cat = categorie = 36)

this should be visible.

This is how setup looks:
![2016-02-08_15h48_34](https://cloud.githubusercontent.com/assets/5681880/12888658/7c9723d8-ce7b-11e5-8c56-efd52e006fb8.png)

maybe there is simply a way to set it up in a better way?

**Comment by mattab** [comment]
Hi @hpvd 

do you mean that "Site Search Category" is not displayed in Visitor Log? If you confirm, we would be able to easily fix this issue.

**Comment by hpvd** [comment]
yes (I think so, should fit decription above)

**Comment by sgiehl** [comment]
If a search category is set, it should be displayed on hover in the visitorlog.
Checked that by generating visits with VisitorGenerator plugin:
![image](https://cloud.githubusercontent.com/assets/1579355/14799286/07abd494-0b3c-11e6-9009-17e6001db474.png)

**Comment by romanoza** [comment]
Is it possible to construct the filter (segment) based on the search category?

**Comment by mattab** [comment]
>Is it possible to construct the filter (segment) based on the search category?
 
@romanoza not yet possible, but it would be possible to add, could you create an issue for this new feature?

**Comment by mattab** [comment]
> If a search category is set, it should be displayed on hover in the visitorlog.

Cheers @sgiehl for checking. Closing as should already work.
