### ISSUE TITLE
search result count is always 0 in visitor log

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9733]
search result count is always 0 in visitor log (hover)

![2016-02-08_16h10_02](https://cloud.githubusercontent.com/assets/5681880/12889306/8c27f932-ce7e-11e5-9425-6b587644a3ea.png)

but it's bigger than 0 even in cases without any results

![2016-02-08_16h06_39](https://cloud.githubusercontent.com/assets/5681880/12889160/f387865c-ce7d-11e5-8711-a1bf7c65fe8c.png)

in this statistic:
![2016-02-08_16h01_57](https://cloud.githubusercontent.com/assets/5681880/12889103/b1f290d8-ce7d-11e5-9a56-622dac692792.png)

**Comment by sgiehl** [comment]
@hpvd do you still have this problem with Piwik 3. For me that works fine locally.

**Comment by hpvd** [comment]
works fine for us too.
