### ISSUE TITLE
List our Goals for Piwik 3.0.0 in the Roadmap and in a blog post

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9735]
The goal of this issue is to communicate clearly to everyone what will be our goals for Piwik 3.0.0 release. We shall

 * Update the Roadmap http://piwik.org/roadmap to describe in more details what will Piwik 3.0.0 bring
 * Write a blog post listing our main goals and vision for Piwik 3.0.0

Any other idea welcome!

**Comment by hpvd** [comment]
perfect idea!
would be awesome if you could tell the 5 most important points within this issue before making them public to the max large community.
With this we could comment on it and you got some additional points to address within the blogpost.
 What do you think?

**Comment by gaumondp** [comment]
Many ideas already there in #8920 (Building the best Enterprise Analytics Platform)

**Comment by mattab** [comment]
The communication of "What Piwik 3 brings" was published in our earlier post: https://piwik.org/blog/2016/09/piwik-3-development-update-1-new-ui-design-api-changes-release-date/
