### ISSUE TITLE
Turn current Dashboard into a PDF report

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#9737]
Many of my users do custom dashboards but are puzzled to recreate them in Emails/PDF reports.

Would be great to have those 2 new options : 

1. Save current Dashboard as PDF
2. Add this Dashboard in Email Reports

What is very important is to keep "preferences" from the Dashboard, mainly numbers of rows, Flat or not, etc.

**Comment by tsteur** [comment]
I like this idea a lot. See also https://github.com/piwik/piwik/issues/9351 here I also mentioned 

> Let a user create a custom "dashboard" / "view" in Piwik based on this export. It would be some kind of dashboard but showing it more report like. This would be directly shown in the UI

which is basically the other way around. 

Export dashboards is a duplicate of https://github.com/piwik/piwik/issues/5101

**Comment by gaumondp** [comment]
Dear @tsteur , I find it strange to see the label/milestone set to 2.16.1, I had the impression that 2.16 was LTS so no new features, only bug/security fixes... and such new features would get the 3.0 milestone.

**Comment by tsteur** [comment]
I set it to 2.16.1 as I closed this issue as a duplicate and left https://github.com/piwik/piwik/issues/5101 open. So it won't be developed in 2.16.1 in this case
