### ISSUE TITLE
trying to connect to sql database

### ISSUE THREAD

**Issue by mem811** [piwik/piwik#9739]
I am desperately trying to connect to my sql database without luck.  I either get "Error while trying to connect to the database server: SQLSTATE[HY000] [2002] Connection refused" when i leave the database server as 127.0.0.1 or I get "Error while trying to connect to the database server: SQLSTATE[HY000] [2002] No such file or directory" when i change the database server to local host.  I am at a loss.  I have no clue what else I can do.

**Comment by tsteur** [comment]
Are you sure MySQL is installed and running? Do you know on which host it is listening?

**Comment by gaumondp** [comment]
May I suggest you install the very light yet powerful Adminer script. If this works, then it's a Piwik problem but if Adminer doesn't work then you have some error in your access.

https://www.adminer.org/

Adminer is like phpMyAdmin but 300 kB instead of 22 MB... Way more secure too...

**Comment by kvordf** [comment]
Was this issue every solved?  I have the same error but insteading of using Adminer to test, I was able to connect to the database using MySQL Workbench. Is that an accurate test?

Thanks

**Comment by g0ldname** [comment]
After i added plugin DBStats, i have Connection refused error at all pages of script :c
