### ISSUE TITLE
Encoding problem with site names

### ISSUE THREAD

**Issue by mduvergey** [piwik/piwik#9743]
Hi,

Site names containing UTF-8 characters don't display correctly (see image below) in various places like site list or &lt;title&gt; HTML tag.

Regards,

Martin

![image](https://cloud.githubusercontent.com/assets/3368437/12943408/58de1df4-cfe1-11e5-9054-5174e709f9a4.png)

**Comment by tsteur** [comment]
Is it like this after updating Piwik? Or has it always been like this? Which Piwik version are you using? Can you check which "Encoding" the browser is using when viewing the page? Eg in Chrome you can see this by going to "View => Encoding"

**Comment by mduvergey** [comment]
Yes, I think it's like this after a recent update. The Piwik version i'm using is 2.16.0.
I'm using Chrome as a browser and the encoding is set to UTF-8.

**Comment by tsteur** [comment]
From which Piwik version did you update?

**Comment by mduvergey** [comment]
Well I apply Piwik updates regularly but I'm afraid I can't tell you which version exactly I was using before the problem turned up. I think it showed up no more than say 6 months ago.

**Comment by tsteur** [comment]
Is it possible that you give us access to your Piwik and to your database? That would help us debugging. If so, please email credentials to hello at piwik.org and let us know here in case it goes into spam. 

It's hard to guess what the reason for this could be. Another idea would be to go to the "Administration => Sites manager" and changing the name for these websites again. Maybe it'll be saved correctly this time.

**Comment by mduvergey** [comment]
Hi, I changed the names in the administration section and all was saved correctly, no encoding problem any longer. Thank you very much for the hint!

**Comment by tsteur** [comment]
Sweet :+1:
