### ISSUE TITLE
All Websites dashboard : Show ID and add sorting based on it.

### ISSUE THREAD

**Issue by gaumondp** [piwik/piwik#9746]
It would be useful sometimes to see the Website ID number and be able to sort the table based on those numbers.

Maybe it could be hidden by default, in a drawer or a personal preference or part of the bigger "All Websites dashboard" customization #2390 (All websites dashboard: let user customise columns and add new ones)

**Comment by mattab** [comment]
Hi @gaumondp 

> Maybe it could be hidden by default, in a drawer or a personal preference or part of the bigger "All Websites dashboard" customization #2390 (All websites dashboard: let user customise columns and add new ones)

:+1: I will add this idea as part of #2390
