### ISSUE TITLE
Document what to do if a server is behind a corporate firewall

### ISSUE THREAD

**Issue by mathieubouchard** [piwik/piwik#9752]
Piwik makes a lot of outgoing connections. There are some options to disable all these connections, but there's no central place where to look at to know easily what to do to disable all outgoing connections.

Some things that are needed:
- Disable SEO plugin
- Set enable_auto_update = 0 in config.ini.php
- Set enable_marketplace = 0 in config.ini.php
- Disable subscribeNewsletter?
- etc.

**Comment by tsteur** [comment]
Thanks for the feedback! There is this FAQ http://piwik.org/faq/troubleshooting/faq_16646/ and this issue https://github.com/piwik/piwik/issues/6324

**Comment by mathieubouchard** [comment]
The referenced FAQ and issue don't cover all the configuration options and outgoing connections :

builds.piwik.org:
    plugins/CoreUpdater/Updater.php
    Set enable_auto_update = 0
api.piwik.org:
    core/UpdateCheck.php
    Set enable_auto_update = 0
plugins.piwik.org:
    plugins/CorePluginsAdmin/MarketplaceApiClient.php
    Set enable_marketplace = 0

Transifex:
    core/Translation/Transifex/API.php
    https://www.transifex.com/api/2/
Update spammer blacklist:
    weekly task
    plugins/CoreAdminHome/Tasks.php
    https://raw.githubusercontent.com/piwik/referrer-spam-blacklist/master/spammers.txt
Update search engines:
    plugins/Referrers/Tasks.php
    weekly task
    https://raw.githubusercontent.com/piwik/searchengine-and-social-list/master/SearchEngines.yml
Update socials:
    plugins/Referrers/Tasks.php
    weekly task
    https://raw.githubusercontent.com/piwik/searchengine-and-social-list/master/Socials.yml
GeoIP:
    ./plugins/UserCountry/GeoIPAutoUpdater.php
    ./plugins/UserCountry/Controller.php
    monthly task
    http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

Deactivate Feedback plugin
Deactivate ExampleRssWidget plugin
Deactivate SEO plugin
Deactivate MobileMessaging
