### ISSUE TITLE
interesting element found in visitors/locations

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9762]
interesting element found in visitors/locations:
- what's this?
- should it be clickable?
- does it need server power for generation?
- a part of it is doubling information

=> could one think of removing it?

![2016-02-11_22h18_19](https://cloud.githubusercontent.com/assets/5681880/12991327/132f8660-d10f-11e5-8ca1-6aed3b9ce30c.png)

**Comment by tsteur** [comment]
true, I think we could actually remove it although the evolution chart has some kind of value to see how your website is doing. Should be maybe better shown in "Visitors overview" or so

**Comment by sgiehl** [comment]
I agree that this information is not needed there right now, looking at the way it is implemented atm.

But I'm not sure if that information should really be (re)moved, as both values might differ if we might change some stuff. 

The distinct countries metric is calculated as a numeric value while archiving, so it is saved separately from the country data metrics.

Enabling the "exclude low population" feature for that datatable for example might cause different values. 
Or maybe the datatable containing all countries might be limited another way (e.g. maximum rows), causing some columns to be aggregated to "others".

**Comment by hpvd** [comment]
I stumbled on this because
- it does not look like other evolution charts more like some pixel pulp /max compressed jpg
- does not make anything on click like some on other other places do
- was only at bottom of continent table (not on other)

Content may be useful but this looks broken. And if it's useful, than it should be also shown on other similar places too.

**Comment by mattab** [comment]
It is not ideal to show this item, but not too bad neither. Looks better  / more clear at least in Piwik 3
