### ISSUE TITLE
After pass change, sanitized string is passed to Auth (instead of unsanitized)

### ISSUE THREAD

**Issue by wronan** [piwik/piwik#9763]
https://github.com/piwik/piwik/blob/master/plugins/UsersManager/Controller.php#L462

Should be:
```
$auth->setPassword($newPassword);
```
instead.

**Comment by mattab** [comment]
Hi @wronan does it cause a bug that can be reproduced? could you describe the issue ie Steps to reproduce, Got VS Expected behavior

**Comment by wronan** [comment]
Steps to reproduce:
1. log into your Piwik
2. go for your personal settings
3. change password to New"Pass
4. you will get permission error, will have to reload the page manually and will land on login form

This partially fails: new password will be set in the DB, but initSession() will fail due to pass mismatch (it will pick new correct pass hash from the DB and compare it with md5('New&quot;Pass')

**Comment by wronan** [comment]
Well... to be hones, I tested it on 2.15.0 but I don't see any code change in this controller, so I assume problem still exists.

**Comment by tsteur** [comment]
I can confirm this.
