### ISSUE TITLE
Piwik Core Archive w/ Custom php.ini

### ISSUE THREAD

**Issue by bmoore9** [piwik/piwik#9764]
In my environment, piwik core archives happen on a server that houses multiple php versions. For the core archive I use php5.5 and the archive is invoked by
`/usr/bin/php55 -c /etc/php5.5/php.ini /www/piwik/console core:archive --url=http://example.com`

Because of the multiple PHP versions I use a specific php.ini file that I specify on the command line. While core archive runs, it seems it reinvokes the requested PHP executable for each segment, but it doesn't preserve the specified php.ini file.

`/usr/bin/php55 -q /www/piwik/console climulti:request -q --piwik-domain='example.com' --superuser 'module=API&method=API.get&idSite=39&period=day&date=last2&format=php&segment=deviceType%3D%3DSmartphone%2CdeviceType%3D%3DPhablet&trigger=archivephp&pid=7ae1e41fe89b3f4ca1bbfff7033ea4b125d927aeebbf2a3a976f22d31ba58c735f71702b105d15cf4b39bfc3b3632a86e86d1'`

Ideally this request would look like

`/usr/bin/php55 -c /etc/php55/php.ini -q /www/piwik/console climulti:request -q --piwik-domain='example.com' --superuser 'module=API&method=API.get&idSite=39&period=day&date=last2&format=php&segment=deviceType%3D%3DSmartphone%2CdeviceType%3D%3DPhablet&trigger=archivephp&pid=7ae1e41fe89b3f4ca1bbfff7033ea4b125d927aeebbf2a3a976f22d31ba58c735f71702b105d15cf4b39bfc3b3632a86e86d1'`

**Comment by tsteur** [comment]
I think what you want was maybe developed in Piwik 2.16 see https://github.com/piwik/piwik/pull/9500

Use eg `--php-cli-options="-c /etc/php55/php.ini"` when calling the archiver. I'll close it for now but let me know in case it does not solve the issue, then we can reopen the issue.
