### ISSUE TITLE
Not tracking hashtag

### ISSUE THREAD

**Issue by fmp777** [piwik/piwik#9771]
It doesn't seem the hashtag tracking works anymore

`_paq.push(['discardHashTag', false]);`

None of my hashtags are getting recorded

`	var _paq = _paq || [];
	_paq.push(["setDomains", ["*.www.xxxxxx.com"]]);
	_paq.push(['discardHashTag', false]);
	_paq.push(['trackPageView']);
	_paq.push(['enableLinkTracking']);
	_paq.push(['enableHeartBeatTimer']);
	(function() {
		var u="//www.xxxxxx.com/piwik/";
		_paq.push(['setTrackerUrl', u+'piwik.php']);
		_paq.push(['setSiteId', 2]);
		var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
		g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
	})();`

**Comment by sgiehl** [comment]
This method is afaik meant to discard the hash fragment on the client side. Setting it to `true` will prevent the fragment beeing sent to the tracking server at all. Setting it to `false` doesn't have an effect unless it was set to true before.

If you want to enable tracking of fragments, you need to enable that in the website options within piwik admin.
