### ISSUE TITLE
Website dashboard causes PHP-FPM core dump

### ISSUE THREAD

**Issue by ShadowNinja** [piwik/piwik#9772]
I recently updated my server to PHP 7.0.3 and updated Piwik to 2.16 at about the same time.
I noticed that after loading a website's dashboard a php-fpm process would dump core.
This only happens on the website dashboard page, not on any other page or in any other application.
The page still renders fine, so I'm not sure what effect this has.
I'm running Piwik through PHP-PHP-FPM 7.0.3 behind nginx.
This might be a PHP-FPM bug.
Backtrace I got:
```
systemd-coredump[<PID>]: Process <PID> (php-fpm) of user <UID> (http) dumped core.
Stack trace of thread 3248:
#0  0x00007fed5398c5f8 raise (libc.so.6)
#1  0x00000000006b4c15 n/a (php-fpm)
#2  0x00000000006b4d12 n/a (php-fpm)
#3  0x00007fed5398c680 __restore_rt (libc.so.6)
#4  0x00007fed53a42df0 accept (libc.so.6)
#5  0x00000000007207b0 n/a (php-fpm)
#6  0x000000000043372b n/a (php-fpm)
#7  0x00007fed53979610 __libc_start_main (libc.so.6)
#8  0x00000000004349f9 _start (php-fpm)
```

**Comment by tsteur** [comment]
Can you try to remove one widget after another to maybe find out by which widget of the dashboard it is caused?

**Comment by ShadowNinja** [comment]
This seems to be caused by this PHP-FPM bug, and the accompanying patch has been merged: https://bugs.php.net/bug.php?id=71269

**Comment by ShadowNinja** [comment]
test...

**Comment by tsteur** [comment]
Thank you for letting us know
