### ISSUE TITLE
Clicking on the 'Goal metrics' icon in 'All Referrers' report, the column headers are missing the goal names

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9773]
When clicking on the Goal metrics icon in reports, the expected behavior is that the report table shows Goal conversion rates, for each goal, for each row of the report table.

### Expected behavior

![working](https://cloud.githubusercontent.com/assets/466765/13026836/94882d3e-d236-11e5-9d08-9d47b4d01c70.png)

### Issue description

There is an issue with the "All Referrers" report. For this report, the goal names are missing from the column names:

![missing goal names in column](https://cloud.githubusercontent.com/assets/466765/13026829/5b87cc9c-d236-11e5-8c65-e89f2718e4a4.png)

All column headers are "Conversion rate" but should be "$Goal_name_here conversion rate".

**Comment by sgiehl** [comment]
Trying to debug this one. Not as easy as I thought. Seems for some reason the idSite is not set as metadata for the datatable, which makes it impossible to load the goal names for the labels.
