### ISSUE TITLE
Process Goal conversions, conversion rate, for each Device Type

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9777]
Currently we process Goal conversions and Conversion rates for each of the following dimensions:

![dimensions goals](https://cloud.githubusercontent.com/assets/466765/13029960/ddac4eb4-d29a-11e5-9896-e5642c175583.png)

Goal of this issue is to add "Device type" at least to these dimensions, so that one can know the conversion rate per device type, for each goal. It would be valuable to know conversion rates of Desktop VS Mobile VS Table!

**Comment by mattab** [comment]
Fixed in  #10070  - will be released in Piwik 3 :+1:

**Comment by mattab** [comment]
I just tried it on demo3 and i'm not yet sure that it's working well, as it seems almost all conversions are attributed to "device type = Unknown" whereas only 0.5% of all visits are unknown.. I'd expect only 0.5% of conversions (on average) to be attributed to unknown

@sgiehl can you take a look at https://demo3.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=2016-09-21&category=Goals_Goals&subcategory=3

**Comment by sgiehl** [comment]
Can't find the credentials for demo3 right now, but you seem to have requested an older report. As the dimension fields in goal report didn't exist before, the data can only be available for new requests.

**Comment by mattab** [comment]
sent you creds to demo3

As the PR was merged 27 days ago, we should have valid data for about 3+ weeks but I'm not seeing good data recently, even for yesterday. let me know what you find!

**Comment by mattab** [comment]
Seems not to have data on https://demo-anonymous.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?idSite=1&period=year&date=today&category=Goals_Goals&subcategory=1 neither. trying to create a new goal to have more data soon. 

Not sure yet if the feature works as expected, will check

**Comment by sgiehl** [comment]
I found the problem:
https://github.com/piwik/piwik/blob/3.x-dev/plugins/DevicesDetection/Columns/DeviceType.php#L73 always returns false (if the goal conversion isn't the first tracking request).

Not sure why that's the case. Thought the visitor properties should be filled with the data saved in the database. Will have a closer look at that later

**Comment by mattab** [comment]
Will check on demo3 in coming days

**Comment by mattab** [comment]
It works, well done @sgiehl :+1:
