### ISSUE TITLE
“Only track visits and actions when the action URL starts with ” feature doesn’t seem to work 

### ISSUE THREAD

**Issue by kira510** [piwik/piwik#9781]
Hello @tsteur , @dandv  , @nuxwin , @ArnY ,
I tried the steps mentioned in http://piwik.org/faq/how-to/faq_21077/ for our internal websites but the consequence was no more tracking at all. Has anyone else faced the same issue? Please let me know what might be the problem at the earliest.

**Comment by tsteur** [comment]
Have you specified the correct subdomain and path? You need to create an entry for each possible subdomain

**Comment by kira510** [comment]
hello @tsteur , @dandv , @nuxwin , @ArnY ,
Can you please tell me how i can check this? As i dont see any subdomain and path option in manage settings.

**Comment by nuxwin** [comment]
@kira510 

As stated in the FAQ:

Go to Go to Administration > Websites > click “Edit”. Below the “URLs” field for your website, there is a checkbox “Only track visits and actions when the action URL starts with one of the above URLs.”.

So here, I presume that you must check the URLs field. You must of course check the checkbox.

Once all this is done, save the changes.

**Comment by kira510** [comment]
Hello,
Enabling “Only track visits and actions when the action URL starts with one of the above URLs.” results in no more tracking at all. I checked this several times. Do you have any idea why this is happening?

**Comment by nuxwin** [comment]
@kira510 Do you have filled the URLs field?

**Comment by kira510** [comment]
![image](https://cloud.githubusercontent.com/assets/17250677/13214026/0736da2c-d973-11e5-808f-143c5f345ea7.png)

you can see that i have enabled the option.

**Comment by kira510** [comment]
Hello @tsteur , @dandv , @nuxwin , @ArnY ,
Any idea why am seeing this behaviour? Please help.

**Comment by tsteur** [comment]
What's the URL that you want to track?

**Comment by kira510** [comment]
It is an internal website, piwik tracks this site when i haven't enabled the feature.

**Comment by tsteur** [comment]
Do you have an example for the URL you want to track? Otherwise it'll be hard for us to reproduce.
