### ISSUE TITLE
consistent spelling (German)

### ISSUE THREAD

**Issue by alexplusde** [piwik/piwik#9782]
Hello!

I'd like to suggest improving the spelling of several strings for Piwik in German.

e.g. terms like
```
Privatsphäreeinstellungen (subpar)
Aktualisierungseinstellungen (subpar)
E-Mail-Server-Einstellungen (correct)
Branding Einstellungen (wrong)
```

should be
```
Privatsphäre-Einstellungen
Aktualisierungs-Einstellungen
E-Mail-Server-Einstellungen
Branding-Einstellungen
```

for improved readability and consistent (and correct!) spelling.

**Comment by sgiehl** [comment]
Thanks for the suggestions to improve the german translations. Our translations are completely community contributed. We are using transifex to manage our translations. If you would like to contribute feel free to register there: https://www.transifex.com/piwik/piwik/
