### ISSUE TITLE
Add sid to the list of query params excluded by default

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9789]
Please see:
https://github.com/piwik/piwik/blob/2.16.0/core/Tracker/PageUrl.php#L31

I think that `sid` is the most commonly used query param to save session ID.

**Comment by mattab** [comment]
`sid` is used in phpBB - are there other famous softwares using `sid` as session id? i've never heard of it. rather I think `sid` is more often used for legitimate use cases. The problem with adding it to PageUrl is that users cannot actually track it even if they really need it: it's blacklisted in the code...

**Comment by mattab** [comment]
Maybe a good idea would be to let users define these blacklisted parameters in the config file? Then anyone could customise them and one could add `sid` to the list... someohow having these parameters in our PHP file is a bug.

**Comment by quba** [comment]
Yep, should be possible to customize all of them. Now it's kinda confusing, that there are a few excluded parameters and we list in the UI only two of them.

**Comment by tsteur** [comment]
Maybe this could be a new issue? Let's maybe for now not overdo it :)

**Comment by quba** [comment]
Yep. But instead of config file, would be nice to define them only in the UI. Otherwise we would double a single functionality to exclude params.

**Comment by tsteur** [comment]
I've created a new issue for this: https://github.com/piwik/piwik/issues/9889

`sid` will be ignored in the future and will therefore close.
