### ISSUE TITLE
Rename ExampleRssWidget plugin to RssWidget

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9791]
Let's rename our ExampleRssWidget plugin to RssWidget.

**Comment by tsteur** [comment]
What's the thought behind it? We'll need to make sure to not break BC in any way etc.

**Comment by mattab** [comment]
Thoughts behind the suggestion:

 * ExampleRssWidget is not actually an example plugin: It does provide a real useful functionality. 
 * As a Piwik admin I want to disable all "Example*" widgets without losing any useful functionality.

Let's keep BC using event `Request.getRenamedModuleAndAction`
