### ISSUE TITLE
console diagnostics:run complains about always_populate_raw_post_data

### ISSUE THREAD

**Issue by oz42** [piwik/piwik#9795]
Although I have set always_populate_raw_post_data=-1 in php.ini, Piwik complains about this and shows an empty dashboard.

**Comment by tsteur** [comment]
Just to rule some simple things out. Have you restarted your webserver? In case you have multiple PHP versions or so installed, was the change made in the right `php.ini`?

Also can you create eg a file called `test.php` and put following text in there:

```
<?php
echo phpinfo();
```

Then open the url in the browser and maybe you can send us what value it shows for `always_populate_raw_post_data`?

**Comment by oz42** [comment]
Am 2016-02-18 08:12, schrieb Thomas Steur:
> Just to rule some simple things out. Have you restarted your
> webserver? In case you have multiple PHP versions or so installed, was
> the change made in the right php.ini?

Everything was okay. This was missing: the overlay module was disabled, 
Piwik does no longer run if it is disabled.

Olaf

**Comment by tsteur** [comment]
I tried to disable the overlay module but it still worked, can someone reproduce this one? If so, please comment here and I will reopen
