### ISSUE TITLE
strtotime error in widget

### ISSUE THREAD

**Issue by fmp777** [piwik/piwik#9798]
![image](https://cloud.githubusercontent.com/assets/2659615/13117276/d89a2410-d564-11e5-9dc6-1df0de601d86.png)

> Error: Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): 2016-02-12,2016-02-15

You guys know about this one?

**Comment by fmp777** [comment]
PS:  seeing it on the "visits over time" widget on dashboard

**Comment by sgiehl** [comment]
Which period is choosen? Maybe you have missmatching parameters in the URL.

**Comment by fmp777** [comment]
No period chosen, don't think the widget even permits that.  Simply click on dashboard and there it is.  It shows the graph fine I think

**Comment by fmp777** [comment]
Its even there on both the websites I have setup so far to track stats

**Comment by tsteur** [comment]
What happens when you change the date? Can eg try to select "day - Feb 18th" and then change back to previous date? Also maybe try to log out and log in again, is it still happening?

**Comment by oleg-sh** [comment]
I believe it's the same error that I got from API documentation page: check this [URL](http://demo.piwik.org/?module=API&method=Live.getLastVisitsDetails&idSite=7&period=day&date=last10&format=rss&token_auth=anonymous&translateColumnNames=1)
This URL comes from the Piwik documentation at http://developer.piwik.org/api-reference/reporting-api#Live

**Comment by tsteur** [comment]
I think this is another problem and rather unrelated to this one. I've created a new issue for this here: https://github.com/piwik/piwik/issues/9840

Have you tried to log out and in again? Maybe try to select a single day etc?

**Comment by fmp777** [comment]
OK - I figured out how to reproduce it and get rid of it.  Its all about the "date range" option.  Switching to a single date eliminates the error.  ANY date selected in the range option generates the error

**Comment by tsteur** [comment]
Is it possible that you paste an example URL here? Feel free to replace your domain.

**Comment by fmp777** [comment]
/index.php?module=CoreHome&action=index&idSite=1&period=range&date=2016-02-17,2016-02-18#?module=Dashboard&action=embeddedIndex&idSite=1&period=range&date=2016-02-17,2016-02-18&idDashboard=1

**Comment by tsteur** [comment]
Is this only happening for one widget or for all widgets? It works perfectly fine for me when using the same URL. Can you try to create a new user, give the user access to this website, and log in with this user to see if it happens there as well? Does it also happen for other date ranges?

**Comment by mattab** [comment]
@fmp777 can you reproduce this on demo.piwik.org?

**Comment by mattab** [comment]
@fmp777 please re-open if you can reproduce the issue on demo.piwik.org or in your Piwik 2.16.0 - also please try upgrade to latest beta: http://piwik.org/faq/how-to-update/faq_159/
