### ISSUE TITLE
Update documentation: Placement of JavaScript tracker code

### ISSUE THREAD

**Issue by utrenkner** [piwik/piwik#9802]
This had me quite confused - please update the documentation to reflect the new recommendation.

During the installation I  thought I read "We recommend to paste it immediately before the closing </head> tag.".

But my colleague - who had implemented Piwik in our other sides - placed it, as usual, before the closing </body> tag. Therefore, I wanted to verify what the recommendation was and found https://piwik.org/docs/installation/#install-the-javascript-tracking-tag , which still has the old recommendation.

I then went back to make another install on a test system just to be sure what I had read there.

**Comment by tsteur** [comment]
Thanks! This FAQ is outdated indeed.

**Comment by tsteur** [comment]
Maybe also related is https://github.com/piwik/piwik/issues/9776 and eg https://github.com/cbleek/YawikDemoSkin/issues/1 etc

**Comment by mattab** [comment]
Thanks for the suggestion. The user guide https://piwik.org/docs/installation/#install-the-javascript-tracking-tag has been updated with our latest recommendation (paste the code immediately before the `</head>` tag)
