### ISSUE TITLE
Help needed with log in page

### ISSUE THREAD

**Issue by yeahtav** [piwik/piwik#9804]
Hi There, 

this is really a silly issue, but i would appreciate the help.

I have installed Piwik on the sub-domain of the website which i need to track. 

for Instance to track example.com , i have created analytics.example.com and installed piwik there. 

I have installed Piwik long back, I have the user name and password. but I forgot the login path for the Piwik analytics dashboard. 

I guess it shoud be like, analytics.example.com/somelogin.php 

but i'm tired of permutations and combinations. 
Somebody please help me with the log in page.

Thanks in advance.

**Comment by tsteur** [comment]
It should be just `analytics.example.com` or `analytics.example.com/index.php`
