### ISSUE TITLE
Visitor log for the particular server time

### ISSUE THREAD

**Issue by Mohan08** [piwik/piwik#9808]
For the report by server hour, looks like piwik is considering only last action hour.

For instance,

If my site has only one visitor who starts at 8 AM and ends at 9 AM, the complete visit is accounted under 9 AM (all actions are being reported at the 9th hour).

In this scenario, number of visits at 8th hour=0, 9th hour=1

Can someone confirm this how piwik works?

![capture1](https://cloud.githubusercontent.com/assets/17331379/13173686/08319bba-d725-11e5-9895-a94878cebb3d.PNG)

in the above table (from visitor log for 23rd hour) the visits have started at 7th hour and ended at 23rd. So, all the actions are reported as those occurred in the 23rd hour. In my opinion this is not logical since the actions occurred throughout the day.

**Comment by tsteur** [comment]
Good point, I think you're right. So far we are counting it only for the last action. However, maybe we should attribute it to all hours between first and last action.

**Comment by Mohan08** [comment]
Thank you for the reply. Hope this will get fixed soon. 

Is there any way to get the traffic metrics breakdown by hours/days/weeks? 

For example,

1. If I have a signup page and I want to see the number of signups breakdown by hours, days & weeks.

Is this possible with piwik by adding a granularity parameter? (by adding a dimension)

Thanks.

**Comment by tsteur** [comment]
I think it's not trivial. You got possibly create loads of segments and filter them separately but that's not really a solution. I would say it is not possible yet, unless you develop a plugin that does this yourself (or contract someone like https://piwik.pro ). Do you mind creating a new issue for this? It would be really useful :+1: 

BTW: in case signup page is a goal, you can go to the goal detail page and get these kinda reports I think. At least some of them

**Comment by Mohan08** [comment]
Segments can only work with the server time and not at a day/week level (as a dimension). 

I do have few goals configured and I could see this report (visit by server time) under Goals by User attribute section.

Thank you for the information, I will create a new issue for this.

**Comment by mattab** [comment]
Correct, it works as expected. We prefer to attribute the visit to only one hour, so that when you sum all visits across all hours, you get the same number of visits as the overall visits for that day.

**Comment by tsteur** [comment]
I wonder if this is actually the best way though and whether it is what users actually expect? 

Also why are we using last action timestamp and not maybe the first one? I don't think current way it works is actually really good.
