### ISSUE TITLE
Piwik DisableCookies tracking

### ISSUE THREAD

**Issue by alexbarbara** [piwik/piwik#9813]
Hi, 

after read this faq page (http://piwik.org/faq/general/faq_156/)  there is something that I haven't  about Piwik function DisableCookies. When you disable cookies by typing 'disableCookies' in JavaScript code, how can Piwik keep caching data? The page talk about IP address and 'other footprints', but what are this footprints? Can you specify it? I'm very interested on this other types of tracking.

**Comment by tsteur** [comment]
You can have a look here in case you are familiar with PHP: https://github.com/piwik/piwik/blob/2.16.1-b1/core/Tracker/Settings.php#L33-L77

For further questions please ask them in our forum: http://forum.piwik.org
