### ISSUE TITLE
Three-level event exploration

### ISSUE THREAD

**Issue by jeremejevs** [piwik/piwik#9816]
Originally described in [this forum post](http://forum.piwik.org/t/exploring-events/18140).

When submitting an event, I can specify its **category**, **action** and **name**. For example:

    trackEvent header click logo // a user has clicked the main logo
    trackEvent footer click blog // a user has clicked the blog link

That works fine, everything gets tracked without issues.

However, I can't find a way to explore the collected events by all three parameters. It appears to be possible only by combinations of two (actions by category / names by action / actions by name). Basically, I'd like there to be a **+** to the left of **click** in this image:

![](https://standard-discourseorg.netdna-ssl.com/uploads/trydiscourse1/original/2X/f/f8a67e6d8e8975f4728b3af644ffb321d519bd48.png)

So that I could see all **names** that were reported with **click** actions, all inside one category **header**. In other words, **names by action by category**. I'm sure I'm not the only one who would benefit from this.

Or is this already implemented, and I'm just looking in the wrong place?

**Comment by tsteur** [comment]
It's not yet implemented but it would be really nice to have. We have an issue for this here: https://github.com/piwik/piwik/issues/7855

**Comment by jeremejevs** [comment]
Thanks, sorry for not finding it, just too much noise to sort through.

**Comment by tsteur** [comment]
No worries, it took me 10 minutes to find it and almost gave up :)

**Comment by tsteur** [comment]
I corrected the title of the other issue so it's actually possible to find ;)
