### ISSUE TITLE
Traffic Metrics breakdown by hours/days/weeks

### ISSUE THREAD

**Issue by Mohan08** [piwik/piwik#9818]
Is there any way to get the traffic metrics breakdown by hours/days/weeks?

For example,

If I have a signup page and I want to see the number of signups breakdown by hours, days & weeks.
Is this possible with piwik by adding a granularity parameter? (by adding a dimension)

**Comment by tsteur** [comment]
FYI: We discussed it initially here https://github.com/piwik/piwik/issues/9808#issuecomment-187074467 and partially a workaround is to create a goal to get some of these reports. At some point we want to be able to combine any dimensions to generate any report. Then it will be easily possible.
