### ISSUE TITLE
Please provide me the solution for this error message

### ISSUE THREAD

**Issue by poojas13** [piwik/piwik#9821]
when i try to debug my code on my vmplayer's centos i get this error msg on giving this command 
: php API.php 
The error message is -----
PHP Fatal error:  Class 'Piwik\Plugin\API' not found in /var/www/html/piwik/plugins/MASPluginNew/API.php on line 43

**Comment by tsteur** [comment]
Do you mind asking this question in our forum https://forum.piwik.org/c/plugins-platform ? There is a category for Plugin development. Maybe also paste some code from that `MASPluginNew/API.php` file if possible. Otherwise it's hard to tell by what it is caused.
