### ISSUE TITLE
GetCore request erroring piwik

### ISSUE THREAD

**Issue by Power2All** [piwik/piwik#9825]
```
index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:58 GET http://WEBSITEURL/index.php?module=Proxy&action=getCoreJs&cb=2d238387fe17ff2e20162026bc4671ba net::ERR_INCOMPLETE_CHUNKED_ENCODING
index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:80 Uncaught ReferenceError: $ is not defined(anonymous function) @ index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:80
index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:755 Uncaught ReferenceError: $ is not defined(anonymous function) @ index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:755
index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:781 Uncaught ReferenceError: $ is not defined(anonymous function) @ index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday:781
```

Shows on all browsers, 
Something generated going bad ?
I didn't had any trouble yesterday and the days before, just today somehow...

**Comment by tsteur** [comment]
Have you installed any other plugins recently or updated Piwik?

It's hard to tell what it could be. Is it maybe possible that you give us access to your Piwik installation? You could create a new user for us only with view permission. That should help. If you can reproduce it on another website too, you could even create a new website just for this user so we won't be able to see any data. If that's possible, please send us credentials to hello at piwik.org.

**Comment by Power2All** [comment]
Hi,
Seems it's working again.
Is there a possibility Piwik tries to load a external javascript file or something, while contacting the GetCore parameter ?
Might be that a external site was down, lot's of DDoS was going on lately, various sites we're down.

Well, it works again.

**Comment by tsteur** [comment]
Sweet. No, it's not really loading any external JS. I'll close it for now.
