### ISSUE TITLE
Validation Error when installing

### ISSUE THREAD

**Issue by Zarickan** [piwik/piwik#9827]
Running PHP 7.0 on IIS, I get the following message during instalation, validation.

**_500 GET request to piwik.php failed. Try whitelisting this URL from HTTP Authentication and disable mod_security (you may have to ask your webhost). For more information about the error, check your web server error log file.
Efter ændringen er have foretaget - genstart webserveren. _**

_[22-Feb-2016 18:37:21 UTC] PHP Fatal error:  Uncaught Exception: The configuration file {C:\Web\Piwik/config/config.ini.php} has not been found or could not be read. in C:\Web\Piwik\core\Application\Kernel\EnvironmentValidator.php:63
Stack trace:
#0 C:\Web\Piwik\core\Application\Kernel\EnvironmentValidator.php(44): Piwik\Application\Kernel\EnvironmentValidator->checkConfigFileExists('C:\\Web\\Piwik/co...', false)
#1 C:\Web\Piwik\core\Application\Environment.php(185): Piwik\Application\Kernel\EnvironmentValidator->validate()
#2 C:\Web\Piwik\core\Application\Environment.php(94): Piwik\Application\Environment->validateEnvironment()
#3 C:\Web\Piwik\piwik.php(56): Piwik\Application\Environment->init()
#4 {main}
  thrown in C:\Web\Piwik\core\Application\Kernel\EnvironmentValidator.php on line 63_

**Comment by tsteur** [comment]
Are you using the latest Piwik version (2.16.0)?

I think we used to have such an error but in an earlier Piwik version. Can you check if `C:\Web\Piwik/config/config.ini.php` exists and is readable by the PHP application?

**Comment by Zarickan** [comment]
I believe I am using the newest version (downloaded it on 22/02-16 from your website). I ignored the error, and installed anyways, and everything seems to work.

C:\Web\Piwik/config/config.ini.php exists and is readable.

**Comment by tsteur** [comment]
Good to hear! Let us know if you experience any other issues. Cheers
