### ISSUE TITLE
inform user that a new password will change API-token and may break webcrons etc.

### ISSUE THREAD

**Issue by alexplusde** [piwik/piwik#9833]
Piwik stopped archiving a few days ago and I didn't know why until i found this thread:

https://forum.piwik.org/t/web-cron-archiving-error/15971
"woops. It appears I changed my password recently, thereby changing the token_auth. I'll go cry in shame somewhere."

Advanced users may know that a new password also causes a new token. But people new to piwik should be told about it. For example via password changing e-mail or after the password changing dialogue.

**Comment by tsteur** [comment]
Very good point. We definitely need to mention this as it is not "normal" that token changes when you change password. It will break all kinda API access and will cause other apps and integrations etc to fail. 

Also related to this is : https://github.com/piwik/piwik/issues/6559 which we will hopefully tackle in Piwik 3. It's very much needed.

**Comment by alexplusde** [comment]
It looks like you'll be informed if you change the password in piwik backend but not if you use the password reset option.
