### ISSUE TITLE
Embed Piwik Report - columnDescription-bubbles are out of view

### ISSUE THREAD

**Issue by bernhardriegler** [piwik/piwik#9838]
When embedding a piwik report the column description bubbles can are not fully visible.

Please see the demo for reference:
http://demo.piwik.org/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=7&period=day&date=yesterday&disableLink=1&widget=1

Hover over the column headlines (i.e. page views).

**Comment by sgiehl** [comment]
Thanks for the report. I'm able to reproduce it.
Guess we need to implement "smarter" tooltips for that, to make them able to decide where it's better to display them

**Comment by bernhardriegler** [comment]
Please point me in the right direction ... Maybe I can provide an improvement.
