### ISSUE TITLE
Site Search not working 2.16

### ISSUE THREAD

**Issue by anujjamwal** [piwik/piwik#9841]
I deployed piwik 2.16. 
I am invoking trackSiteSearch from js code.

`Piwik.getAsyncTracker().trackSiteSearch($scope.searchKey, false, totalCount);`

I can see a request getting fired in browser, but nothing shows up in the browser in Site Search Keywords. Only "Visitors in Realtime" seems to work

**Comment by tsteur** [comment]
Just to make sure I got it right. You can see the actual keyword in "Visitors in Realtime" but not in any other "Site Search" report?

Has this problem started after updating to Piwik 2.16?

 Is `totalCount === 0`?

**Comment by mattab** [comment]
It works for us, please let us know how to reproduce.
