### ISSUE TITLE
mysql database name with `+`

### ISSUE THREAD

**Issue by goretkin** [piwik/piwik#9844]
The database name I can use contains a `+`. During setup Piwik tells me that's an invalid database name.

I don't follow the code perfectly, but it looks like it boils down to 
https://github.com/piwik/piwik/blob/7f375924db9328f20a0b7cb1e41397f2309b60a7/plugins/Installation/FormDatabaseSetup.php#L63

and then

https://github.com/piwik/piwik/blob/7f375924db9328f20a0b7cb1e41397f2309b60a7/core/Filesystem.php#L54

I'm going to try the regular expression `(^[a-zA-Z0-9]+([a-zA-Z_0-9.-\\+]*))$` instead

**Comment by tsteur** [comment]
Thx! This is a bug and we probably should allow a `+` in database name
