### ISSUE TITLE
Page statistics having problem with "/" in title

### ISSUE THREAD

**Issue by kongsted** [piwik/piwik#9846]
Hi,

If a page title contains a / (slash) in the page title, it will show up in "Actions -> Page title", as a page with a subpage.
Example.
If a pages in called "About Company A/B" it will show as:
- About Company A
   - B
In the "Page Title" page.
Hope it make sense. :)
I'm using Piwik version 2.16.0.

Anybody else seeing that problem, or have I misconfigured something?

//Anders

**Comment by sly7-7** [comment]
I just jumped into piwik, and thought it was a kind of "hidden feature"

**Comment by tsteur** [comment]
This is some kind of feature indeed. You can select to "flatten" the report by clicking on the arrow down below a report and then select "Make it flat" in the cog icon in the bottom right. If you are logged in, it should remember to flatten it next time.

**Comment by kongsted** [comment]
In my opinion, it's not a solution, but just a work around to change to "flatten view".
Am I the the only one seeing that problem, or is it a general problem (= bug)?
//Anders

**Comment by tsteur** [comment]
Does it not give you valid results when using "Flatten"? 

I'd understand that's a probem when using the API as one would have to set "flat=1" in the API only for this report and one would need some kind of a hack for this. However, the UI should give the same results? It's for sure possible I'm missing something.

**Comment by mattab** [comment]
It is both a hidden feature and a bug. See this bug report: https://github.com/piwik/piwik/issues/2956
