### ISSUE TITLE
In Users management, on hover, display a cursor over green/red icons 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9848]
Currently one cannot guess that these icons are clickable. 
- Let's add a cursor on hover
- Maybe even a tooltip

**Comment by codetheorist** [comment]
Is this issue resolved? I come to implement the hover state however this has already been implemented. Should I proceed with the tooltip or is this feature a non-requirement?

**Comment by mattab** [comment]
Hi @codetheorist feel free to work on this or even any other easy pick here: https://github.com/piwik/piwik/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22Easy%20pick%22%20milestone%3A3.0.0
