### ISSUE TITLE
GeoIP is not working

### ISSUE THREAD

**Issue by pjs13** [piwik/piwik#9853]
Hi ,

I have followed this **description **

[Download Piwik GeoIp Plugin](http://issues.piwik.org/attachments/5465/GeoIP.zip?format=raw)
Unzip the plugin and copy the extracted directory “GeoIp” in the directory piwik/plugins/
Configure the MaxMind database:
Either download MaxMind GeoLite City or GeoIP City database from http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz Uncompress this file and copy it in plugins/GeoIP/libs/GeoLiteCity.dat
For more performance, it is recommanded to install the module apache mod_geoip. Configure your Apache according to: http://www.maxmind.com/app/mod_geoip
Enable GeoIP plugin in Piwik. Go to Piwik > Settings > Plugins > Geoip, click Enable

for downloading & installing GeoIP. But after completing the process, when i Go to Piwik > Settings > Plugins > i cant find GeoIP plugin to enable it. 
So i manually created in config.ini.php file, just to enable it in plugins folder but even then i am getting this error message. - 

![untitled1](https://cloud.githubusercontent.com/assets/17407411/13354970/2b11c2aa-dcc4-11e5-906c-1155f3bf5ebf.png)

So please help me out for this....

**Comment by Globulopolis** [comment]
Follow these instructions [http://piwik.org/docs/geo-locate/#maintaining-geoip-databases](http://piwik.org/docs/geo-locate/#maintaining-geoip-databases)
