### ISSUE TITLE
Debian Package for Piwki 2.16.0 still missing

### ISSUE THREAD

**Issue by gebi** [piwik/piwik#9856]
Hi,

Just a note, it's already 3 weeks since you released a new version which is marked **critial** for security and your mirrors still have 2.15.0 as the lastest version.

I fixed your debian packaging up so it does build a working debian package for piwik release 2.16.0, but it would be nice to have timely debian packages in the future, especially for security critical releases.

https://github.com/piwik/piwik-package/pull/47

**Comment by tsteur** [comment]
ping @mattab @aureq

**Comment by aureq** [comment]
@gebi Thanks for the ping. The new package has just been published. I tested the upgrade in my environment and everything went fine.

**Comment by tsteur** [comment]
Thx a lot @aureq !

**Comment by gebi** [comment]
@aureq thx for the new release. We had no upgrade problems in our environment too, though we are still using our own packages, hope we can switch back to upstream for the next release.

Thx for also integrating our other [suggestion](https://github.com/piwik/piwik-package/issues/14) for user changeable logo, though a mention for our contributions would have been nice...

**Comment by mattab** [comment]
Hi @aureq 
Thanks for the release! is there something we could do to help you cut the release shortly after the official release? for example maybe you would like to be notified by email of new releases (sign up @ http://madmimi.com/signups/139168/join ).
