### ISSUE TITLE
No logs are printed in std-out, when running console core:archive

### ISSUE THREAD

**Issue by pouyana** [piwik/piwik#9861]
After updating the PHP version to 5.5.14, the logs on core:archive console are vanished. I tried different verbosity, -v -vv -vvv and all of them give no output. When there is an error it will be printed but the logs are not printed at all. I am using the last version of Piwik 2.16 but this happened in the versions before too.

**Comment by filippog** [comment]
can confirm with debian wheezy php `5.4.45-0+deb7u2`, no output from `core:archive` regardless of verbosity setting. Other commands seem unaffected though, e.g. `core:delete-logs-data -vv` emits something like this

```
Preparing to delete all visits belonging to ALL websites between 2015-09-05 00:00:00 and 2016-03-05 00:00:00.

**************************************************************************
  Successfully deleted 0 visits. Time elapsed: 0.155s  
**************************************************************************
```

**Comment by tsteur** [comment]
It works fine for me. Can you check if the plugin `Monolog` is enabled in `Administration => Plugins`?

**Comment by filippog** [comment]
@tsteur indeed enabling `Monolog` did the trick, thanks!

**Comment by tsteur** [comment]
Sweet, I'll close the issue for now. Please comment in case there are still problems.
