### ISSUE TITLE
The site search HTML chars are not displayed correctly in visitor log

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/piwik#9862]
We noticed that Piwik is incorrectly encoding some keywords in the visitor log. What’s surprising is the fact, that on the reports everything looks fine. Here’s the screenshot:

![visitor log](https://cloud.githubusercontent.com/assets/7943292/13459818/9ae32604-e076-11e5-81c4-c2d961ea88f8.png)

After some quick investigation, I think we should add ```|rawSafeDecoded``` filter here:
https://github.com/piwik/piwik/blob/2fe8faacdbde76121dfabca6088a300d6e8fae7d/plugins/Live/templates/_actionsList.twig#L88

Let me know your thoughts and if it’s fine, I’ll prepare a PR and add a test.

**Comment by sgiehl** [comment]
solved with #9863
