### ISSUE TITLE
Clickable phone number freezes piwik

### ISSUE THREAD

**Issue by Glisse1** [piwik/piwik#9865]
Hello,
Ever since I have started to use piwik I have this bug. Probably I am in a very small minority, but here it is:

- in mobile version of my site I have a widget formatted to be directly clicked for dialing my number. The link is the standard html recommended one, `<a href="tel:012345678">012345678</a> `
- when a customer clicks this link it leaves the browser and dials the number as expected, but on piwik end I get some sort of "unknown" page listed as the action-url (not an outgoing link, as I believe it should).. at this point piwik freezes and stops auto-refreshing the live widget

**Comment by sgiehl** [comment]
Not sure how it should be tracked at all.
But as `tel`-links should imho be handled the same way as `mailtio`-links, it needs to be added in https://github.com/piwik/piwik/blob/master/js/piwik.js#L4155 I guess

**Comment by tsteur** [comment]
Good point, I'll add it to 2.16.1 as it seems like a quick fix but we can also move it out of 2.16.

**Comment by tsteur** [comment]
I tested and debugged it, and what happens now, is that nothing is tracked when clicking on `tel:0123456..`. This seems to be same behaviour as for `mailto`. Tracking mailto, tel, ... links would be another new feature I presume.

**Comment by heet25itachi** [comment]
HELLO BRO +91 92198 18683 PLS FIND THIS NUMBER IF U CAN HE IS FRAUDING 1000 OF PEOPLES., PLS CONTACT ME IN MY EMAIL ID AS I PROVIDED OR MY INSTA ID
