### ISSUE TITLE
z-index issue on profile settings page

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#9868]
when changing the password the site selector for default report has an z-index that is higher than the overlays background.

Expected: site selector should be "greyd out" aswell

![image](https://cloud.githubusercontent.com/assets/1579355/13476755/94347008-e0c9-11e5-8bf9-2342ffaf790e.png)

**Comment by mgonera** [comment]
![screen shot 2016-03-07 at 13 55 54](https://cloud.githubusercontent.com/assets/11424829/13582913/17ec907c-e4af-11e5-82ec-69ba66fffae3.png)

**Comment by mattab** [comment]
(suggestion: create a UI test for the "Metric" tooltip)

**Comment by tsteur** [comment]
I hope we won't end up creating ui tests for all tooltips ;) I'd rather not create one for such things

**Comment by mattab** [comment]
I meant: let's create a UI test for one tooltip (only one needed). It is possible that we already have a UI test for our metric tooltip, but I couldn't find it so far.

**Comment by sgiehl** [comment]
Having a single tooltip test won't prevent having other z-index or tooltip
issues.

But I'll check if it's usefull to add any Ui tests when solving the issue
