### ISSUE TITLE
Disabling overlay plugin causes dashboard not to load - Piwik 2.16.0

### ISSUE THREAD

**Issue by Jgavin101** [piwik/piwik#9870]
Many of our sites are behind different firewalls so we have decided not to use the overlay plugin.
After upgrading to 2.16.0 the dashboard would not load, I checked the dev console and could see an error relating to the Overlay plugin, once enabled the dashboard loaded again. Is this a bug or is the overlay plugin now required?

**Comment by sgiehl** [comment]
I think that's more a bug. Would you mind posting the error message?

**Comment by Jgavin101** [comment]
Uncaught ReferenceError: DataTable_RowActions_Overlay is not defined

**Comment by mattab** [comment]
Can you try our latest beta? http://piwik.org/faq/how-to-update/faq_159/ this bug may already be fixed

**Comment by Jgavin101** [comment]
This is on a production load balanced environment so I cannot updated to a beta release. I will try to test locally later today.

**Comment by Jgavin101** [comment]
Issue fixed in latest beta.
