### ISSUE TITLE
Way to determine which way is used

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9871]
On a website there are often different ways (direct links) to go from site A to site B
e.g there is
- a menu acessible on site A containing a link to site B
- there is a "next" button at the end of an article one site A which leads to site B
- there are previews of articles to similar topics shown at the bottom of site A containing a link to site B

At this time there seem no way within piwik to determine which way is used by a visitor to go from site A to site B, does it?

The only construct which may work is setting up some kind of "internal campaign"

Is this the way it should be handeled?

The questions to solve with this:
1) how do site B recieve their visits?
2) which way does a specific visitor choose from site A to B?
3) which location is the best to attract visitors to visit another site?
4) ...

**Comment by sgiehl** [comment]
If it is relevant which link is used I guess the best choice would be a heatmap.
But as Piwik doesn't have a good plugin for that atm. I guess another possibility would be to make some content tracking in order to get information which content pieces have been clicked.

**Comment by hpvd** [comment]
thanks for your answer!
Just opend a new issue to make it possible to use it in the way desired:
Show "content interactions" in vistor log https://github.com/piwik/piwik/issues/10052
