### ISSUE TITLE
Outlinks and downloads may not be tracked if users don't specify a leading slash in paths (eg. setDomains)

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9872]
As stated, outlink and download events are not tracked at all with IE 11. Same visit occurring in Chrome for example, generates proper actions and visitor log.

**Comment by mgonera** [comment]
Seems like mistake on user end.

**Comment by mattab** [comment]
If it was confirmed, the way to prevent this would be to: run our automated piwik.js tests on more browsers than just webkit (modern IE, firefox, ...) #9874

**Comment by mgonera** [comment]
@mattab 

Issue is reproducible on http://m4g.gbros.pl/ec/site1a using IE 10.0.9200.17556 and 11.212.10586.0
![screen shot 2016-05-05 at 21 41 16](https://cloud.githubusercontent.com/assets/11424829/15054909/1e2db720-130a-11e6-832d-9cf744c2263d.png)

**Comment by wronan** [comment]
This problem occurs around here:
https://github.com/piwik/piwik/blob/master/js/piwik.js#L3115

For `isSitePath(path, aliasPath)` there is a situation when 
`path = '/site1/path/(...)`
and
`aliasPath = 'site1/path/(...)`

There is a '/' missing. I hotfixed that on my test instance by something like that:
`if (stringStartsWith(path, '/') && !stringStartsWith(aliasPath, '/')) {
 aliasPath = '/' + aliasPath;
}`
just before this https://github.com/piwik/piwik/blob/master/js/piwik.js#L3115 condition. Function stringStartsWith was of course introduced somewhere above.
I will create a PR for reviews tomorrow.
