### ISSUE TITLE
Auto-Archiving - Unable to load dynamic library 'C:\php\ext\php_pdo.dll' - The specified module could not be found.

### ISSUE THREAD

**Issue by adhamshamkh** [piwik/piwik#9875]
Hello

I'm trying to setup auto-archiving following the steps here: [http://piwik.org/docs/setup-auto-archiving/#important-tips-for-medium-to-high-traffic-websites]

I have a Windows PIWIK configuration (IIS)

I get a warning: PHP Warning:  

**_PHP Startup: Unable to load dynamic library 'C:\php\ext\php_pdo.dll' - The specified module could not be found._**

The PHP documentation suggests this DLL is no longer required for PHP 5.3 and above [(http://php.net/manual/en/pdo.installation.php)]

Is this just a warning, I'm getting errors during the  auto-archive process (stating authenticated user does not have permission to use this DLL) and can't be sure if this is the reason or not.

Thanks in advance
Adham

**Comment by adhamshamkh** [comment]
I resolved this issue, I needed to give IISUSR full permissions to the piwik folder. The warning however does remain - I guess this is a low priority issue as you need to enable the pdo dll in the ini file even though it doesn't exist.

**Comment by sgiehl** [comment]
Looks like a server misconfiguration. A PHP Startup Warning can't be related with Piwik.
Guess you need to adjust your php config.
