### ISSUE TITLE
config to ignore specific url for tracking

### ISSUE THREAD

**Issue by stephanfriedrich** [piwik/piwik#9885]
Hi i love piwik, its realy usable.

but it would be nice if i could set an specific url (like "localhost") to be ignored by tracking.
greetings

**Comment by sgiehl** [comment]
It's already possible to allow tracking only for specific urls (whitelist). I don't see any advantages in having a blacklist aswell.

For activating the whitelist see http://piwik.org/faq/how-to/faq_21077/
