### ISSUE TITLE
Custom Variables - percentage values in subtable should be based on parent table 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9890]
See eg https://demo-anonymous.piwik.org/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=CustomVariables&actionToWidgetize=getCustomVariables&idSite=1&period=day&date=2016-03-07&disableLink=1&widget=1

![image](https://cloud.githubusercontent.com/assets/273120/13589610/fc490424-e53d-11e5-9d8a-12eeb4fe76dd.png)

For example in this case "Custom Variable value not defined" shows only 11.3% because it's calculated in relation to all tracked Custom Variables in total. However, I would expect to see about 80%.

This way it would be for example easy to answer the question how many users with a tracked MySQL version use version "5.5.5". In the example it shows "1.4%" but it's actually about 25%. 

![image](https://cloud.githubusercontent.com/assets/273120/13589659/608b03b0-e53e-11e5-9660-8e69788fb333.png)

**Comment by mattab** [comment]
As we will deprecate custom variables in #11524, closing this issue as Won't fix.

We now recommend to use [Custom Dimensions](https://piwik.org/docs/custom-dimensions/) instead.
