### ISSUE TITLE
Name for our new Piwik 2 and 3 develop branches (feedback needed quickly)

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9891]
As I'm starting to actively working on Piwik 3 basically today I need to create "develop" branches. We already have a `3.0` branch that I would rename. Re handling Piwik 2 and 3 see here: https://github.com/piwik/piwik/issues/9806 and we also need a develop branch anyway as it is the only way to make sure we always have a green build in master.

Are there any good examples from other projects? Maybe any "standards"? I was thinking about simply using `2_X` and `3_X` as develop branches for 2.X and 3.X. We won't exactly follow git flow or so, instead we want to keep things simple for us. If there are any opinions please comment ASAP as I need to start creating such branches for several plugins, otherwise I can't get the tests in `3.0` branch green.

**Comment by kaz231** [comment]
Maybe something like 2.X-dev ?

**Comment by mattab** [comment]
Maybe `2.x` and `3.x` ?

**Comment by tsteur** [comment]
I reckon adding a `-dev` does make sense and is more clear. :+1: for that. Eg `2.x-dev` (lowercase is easier to write on console :) ). Any more ideas?

**Comment by tsteur** [comment]
If I hear no complaints in the next few hours `3.x-dev` and `2.x-dev` it is.

**Comment by mattab** [comment]
:+1:
