### ISSUE TITLE
Automatically triggered Plugin to export data 

### ISSUE THREAD

**Issue by kira510** [piwik/piwik#9900]
Hello @tsteur , @dandv , @nuxwin 
Am trying to develop a plugin that is triggered automatically when data comes into piwik (basically this plugin collects the visitor info and exports to another application) , some of the possible methods are
1. Access the database and trigger the plugin whenever data enters the Database
2. call my plugin via the javascript tracking code, this probably requires piwik source code change
3. change the piwik code which in turn calls the plugin.

Is there a plugin in the marketplace which does this? We prefer not to change the piwik source code so using a plugin would be a better option.
If no, then please suggest me which method is more efficient and less time consuming. Also share the documentations apart from the ones in piwik.org regarding piwik core and plugin development.

**Comment by tsteur** [comment]
Hi @kira510 please have a look at http://developer.piwik.org/ and ideally ask for such questions in our forum for plugins https://forum.piwik.org/c/plugins-platform . Here we only handle issues. 
 
As of your questions:
> when data comes into piwik
What kind of data? only visitors? or also users etc? Maybe checkout tracker events and other events: http://developer.piwik.org/api-reference/events#tracker

For database and other methods see http://developer.piwik.org/api-reference/classes 
Some guides can be found here: http://developer.piwik.org/develop

2. ) shouldn't require change as there are events for this etc.

**Comment by kira510** [comment]
Hi @tsteur ,
i did post on the piwik forum but i wont get an immediate response so i had to ask here. Just one more question, can the plugin be triggerd automatically whenever a website(the one tracked by piwik) is opened?

**Comment by tsteur** [comment]
Check out the events page, there are lots of events for all kinda stuff.

**Comment by kira510** [comment]
I was using tracker methods but they are deprecated. So i have to use dimensions instead. But the documentation does not provide enough information.

**Comment by nuxwin** [comment]
@kira510 

Please, post on the FORUM. You must wait for answer, as any other people. We're not at your service ;)
