### ISSUE TITLE
Goals without conversions has no Conversions Overview

### ISSUE THREAD

**Issue by wronan** [piwik/piwik#9909]
I know that this in on purpose, but I think that there should be some information.

Here I have it:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-03-07#/?module=Goals&action=goalReport&idGoal=2&idSite=7&period=day&date=2016-03-07

here I don't:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-03-05#/?module=Goals&action=goalReport&idGoal=2&idSite=7&period=day&date=2016-03-05

For inexperienced user this might look like a bug of some sort. Just an empty space where 'some table' is expected.

**Comment by quba** [comment]
I'd add there a box with such an information:

> Reports are not displayed because there is no conversion data for the selected Goal and date.
