### ISSUE TITLE
Can not drill down into sub pages

### ISSUE THREAD

**Issue by cornelinux** [piwik/piwik#9910]
I have a strange effect in the dashboard in the pageview.
I can not drill down into sub pages. This only occurs in one installation with 2.16. I also upgraded to 2.16.1-b1 and it has the same effect. On another website the drill down works fine.

Please see the forum entry:
https://forum.piwik.org/t/dashboard-pages-view-can-not-drill-down-into-sub-pages/18014

This is a screenshot of the problematic sub pages
http://postimg.org/image/hvt87o1nb/

**Comment by tsteur** [comment]
Is it possible to get access to your Piwik instance to have a look at it? Ideally we would also have instance to the database and maybe the files of the Piwik installation but not sure if it's needed. If so, can you maybe create a user with view access to this website and send us credentials to hello at piwik.org? It's hard to tell from the pictures what it could be

**Comment by tsteur** [comment]
I can't find the mail, also not in spam folder or so. Have you sent to hello(at)piwik.org?

**Comment by tsteur** [comment]
@cornelinux I had a quick look and something always renders an additional `<head/>` before the actual HTML response. I've had a look and couldn't find the same string in our Piwik code so very likely something in your Piwik setup adds a `<head/>` to our ajax requests. For example your webserver. Or maybe have you made a change accidentally in one of the files? Or maybe you are using a third party plugin that is adding this for some reason? In this case I would try to disable some third party plugins temporarily. 

Please keep us updated about it if possible and let us know what caused it. Maybe someone has a similar issue one day.

**Comment by cornelinux** [comment]
Thanks a lot for this information. This gives me something to investigate.

Code was not altererd. In fact I also created a new one.
No 3rd party modules in piwik.
.htaccess looks the same like on the other machine.

Maybe the head is rendered like this

    "<head " .  somespecial_information . "/>

But the information is empty which results in an empty head.

I will investigate possibilities with the webserver.

THanks again
Cornelius

**Comment by cornelinux** [comment]
Hi,
I was not able to find the issue.
I now used the 2nd piwik installation to manage both sites.
THanks 
Cornelius
