### ISSUE TITLE
DB field name Screen resolution is too small: width and height should not be limited to 9999 pixels

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9913]
The current resolution field is set to VARCHAR(9). This means that the field may be truncated if we store a resolution width or height more than 9999 pixels. Then the resolution wouldn't fit in 9 characters (they are stored separated by a `x` in `log_visit.config_resolution`).

Goal of this issue is to change the DB field type to allow for more characters, so one could track very large resolutions. (note that the integration test in RequestTest.php (and `getResolution` in Tracker/Request) will need to be updated, see https://github.com/piwik/piwik/pull/9914/files#diff-35f2659319670251c767de1da7cb514aR358)

follows up https://github.com/piwik/piwik/issues/9911

**Comment by tsteur** [comment]
:+1:
