### ISSUE TITLE
INSERT statement into `piwik_log_visit` fails (stable version 2.16.0)

### ISSUE THREAD

**Issue by netbrothers-tr** [piwik/piwik#9922]
After upgrading to the latest stable version (2.16.0) Piwik generates the following error in the Apache error log.

> Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error: 1364 Field 'config_resolution' doesn't have a default value In query: INSERT INTO piwik_log_visit (idvisitor, config_id, location_ip, idsite, visit_first_action_time, visit_goal_buyer, visit_goal_converted, visit_last_action_time, visitor_days_since_first, visitor_days_since_order, visitor_returning, visitor_count_visits, visit_entry_idaction_name, visit_entry_idaction_url, visit_exit_idaction_name, visit_exit_idaction_url, visit_total_actions, visit_total_searches, referer_keyword, referer_name, referer_type, referer_url, config_browser_engine, config_browser_name, config_browser_version, config_device_brand, config_device_model, config_device_type, config_os, config_os_version, visit_total_events, visitor_localtime, visitor_days_since_last, visit_total_time, location_city, location_country, location_latitude, location_longitude, location_region, location_provider) VALUES [...]

Shouldn't be `NULL` a valid value for the field `config_resolution`? It seems Piwik can't always determine the screen resolution. The according line in the code is here:
https://github.com/piwik/piwik/blob/2fe8faacdbde76121dfabca6088a300d6e8fae7d/core/Columns/Updater.php#L260

Seeking for confirmation or disproval by the community if this is a general problem or just ours. Thanks to all!

**Comment by tsteur** [comment]
I presume this can happen if the Resolution plugin is disabled. By any chance, is it disabled?

Otherwise it should work as Resolution should always return a non-null value (a string)

**Comment by netbrothers-tr** [comment]
It stemmed from an incompatible _UserSettings_ plugin that has been active still, i.e. our mistake. After uninstalling it, the regarding columns were gone. So the issue is obsolete.
