### ISSUE TITLE
Goals not being fired by events

### ISSUE THREAD

**Issue by PhilBuckley** [piwik/piwik#9923]
Hi all -

Thanks as always for the brilliant work on PIWIK. 

As discussed with Matthieu on the support forum, I think there is a bug whereby goals I am setting to be fired when an event occurs are not being registered. 

Context: we have an isomorphic application which gives JavaScript users an immersive experience as they go through the pages, while non-JS users go back to the server and refresh the page each time they click through. In order to track events accurately, we have an abstraction layer whereby both JS and non-JS users send events to a sort of 'events engine' on our server, which then fires an event over to PIWIK.

I don't know if this is the problem or just in the naming of events? Anyway - it's working totally beautifully in terms of sending events - in the PIWIK events section, sorted by category, we get great information like:

Event category                   
00.Departure country	 17	events
01.Destination country      17 events

However, I would love to tie these events up to goals - but when I set up a goal eg:

GOAL NAME                                       
Applicant chooses departure country 
GOAL IS TRIGGERED WHEN
Send an event (Event Category) Pattern contains: 00.Departure country

I just can't get these goals to fire. I've tried what seems like every possible combination of 'pattern contains', 'exact match' etc.

If it will help, I will happily give you read access to our development site and development PIWIK instance so you can reproduce it. 

With many thanks -

Phil

**Comment by tsteur** [comment]
When you track an event normally, is an event category set and shown in the report afterwards?

The only thing that I can think of would be that eg already another goal was converted so it won't trigger this goal based on events. Could this be the case maybe?

Sure, access to development Piwik instance + server would be helpful to debug otherwise. Can you send us credentials to hello at piwik.org and leave a comment here afterwards so we can check spam folder etc?

**Comment by mattab** [comment]
Hi @PhilBuckley 
would you be able to provide more info as per our previous comment? Thanks.

**Comment by PhilBuckley** [comment]
Hi all- very sorry for the delay in responding to this. 

I've emailed you a whole load of details and hopefully you will have an invitation to our PIWIK dashboard - if not, your user name will be piwik. 

Thanks all, do contact me with any questions - 


Phil

**Comment by tsteur** [comment]
I had a look and I could reproduce it on your instance. Afterwards I tried to reproduce the same on my instance but couldn't reproduce it. When I attach the event information via `e_c=...&e_a=...` parameter to a normal tracking request the goal is triggered on your server as well. So it seems to only not work when the event is tracked via your "event engine" on your server. Do you think it is possible that you send me an example URL of such an event tracking request that is sent from your "event engine"?  

Update: I had a further look through the code and I can imagine that likely the `url` tracking parameter is missing?

**Comment by PhilBuckley** [comment]
Hi Thomas –

OK, thanks very much for this. It may take the team a little while to investigate this as they are in the middle of a different problem so I’ll alert you as soon as they get a chance to look at it. I’ll ask them to see if adding this URL parameter helps.

Best wishes –


Phil

Phil Buckley | Digital Transformation Manager
+44 207 008 0091| +44 7808 764882 | @philbuckley5<https://twitter.com/philbuckley5>

**Comment by tsteur** [comment]
@mattab do you maybe know why the action URL is needed when a goal is converted here https://github.com/piwik/piwik/blob/2.16.0/core/Tracker/GoalManager.php#L192 ? I'm not sure if we just never adjusted this bit of code when adding events, or whether it is actually needed.
