### ISSUE TITLE
Refresh keyword from broken status

### ISSUE THREAD

**Issue by mybluepig** [piwik/piwik#9927]
Dear

I reported broken keyword in my language last year and it seems been fixed.

But problem is people keep using same keywords since last year and I still see it broken.

I think this happens database still has broken keywords and new records being added to it.

I can guess what it is but I don't want to just guess it because they are top keywords.

Reverse links to search sites are not working since keywords are broken, links also broken.

Do you have any idea I can fix this?

**Comment by tsteur** [comment]
Can you maybe add a link to the original issue that you reported re the language?

Can you maybe show some screenshots to explain what you mean?

**Comment by mybluepig** [comment]
Dear Thomas

Sorry for late reply

here is original thread about broken texts
https://github.com/piwik/piwik/issues/7712

I attach the result today to see keywords still broken but it seems new keyword is good.

is there any way I can refresh keywords?

--------- 원본 메일 ---------
보낸사람: Thomas Steur <notifications@github.com>
받는사람 : piwik/piwik <piwik@noreply.github.com>
참조 : mybluepig <mybluepig@hanmail.net>
날짜: 2016년 3월 17일 목요일, 04시 24분 17초 +0900
제목: Re: [piwik] Refresh keyword from broken status (#9927)
Can you maybe add a link to the original issue that you reported re the language?
Can you maybe show some screenshots to explain what you mean? 
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub

**Comment by tsteur** [comment]
Please let us know more information about your environment. Which Piwik version are you using? Which PHP version? Which MySQL version? How should the keywords you mentioned there actually look like?

**Comment by mattab** [comment]
Hi @mybluepig it would be great if you could provide more info (see our previous comment).

**Comment by mybluepig** [comment]
my piwik version is 2.16.0
and my PHP version is 5.6.8
and my MySQL version is 5.6

here is information from phpMyAdmin in Korean but you will see everything
데이터베이스 서버

서버: localhost via TCP/IP
서버 타입: MySQL
서버 버전: 5.6.21-log - MySQL Community Server (GPL)
제품 버전: 10
사용자: root@localhost
서버 문자셋: UTF-8 Unicode (utf8)
웹서버

Microsoft-IIS/7.0
데이터베이스 클라이언트 버전: libmysql - mysqlnd 5.0.11-dev - 20120503 - 
PHP 확장: mysqli 문서
PHP 버전: 5.6.0

I see keyword section now
![current_status](https://cloud.githubusercontent.com/assets/6930901/14241837/d0c7e3e6-fa88-11e5-9973-19bec7cea454.png)

It should be look like one of these
홍천cc
홍천컨트리클럽
강원도
홍천
etc

**Comment by mattab** [comment]
@mybluepig could you please post a Referrer Search engine full URL, which contains one of your keywords eg. ` 홍천컨트리클럽` ? I suppose it's possible that there is a bug in detecting the keyword from this search engine. Is the search engine google?

**Comment by sgiehl** [comment]
Closing this issue here now. If anyone has any similar problems with search engine detections please create a new issue at https://github.com/piwik/searchengine-and-social-list/issues
