### ISSUE TITLE
tiny: visitor log: Linebreak within "google position"

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9930]
visitor log: depending on window width and keyword length, there is the possibility for a linebreak within "google position"
please see attachments

![2016-03-15_21h09_28](https://cloud.githubusercontent.com/assets/5681880/13792564/b8fd89e6-eaf2-11e5-824e-de4f27a220cd.png)
![2016-03-15_21h09_41](https://cloud.githubusercontent.com/assets/5681880/13792566/bbeb93aa-eaf2-11e5-8b28-199babebbcea.png)

**Comment by tsteur** [comment]
Thx :+1:
