### ISSUE TITLE
Missing device detection after upgrade from 2.3.0 to 2.16.0

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#9935]
Hi there,
 we just did a Piwik jump from 2.3.0 to 2.16.0 version, now we're missing stats we stored about _Mobile Vs Desktop_ devices during 2.3.0. 

We figured out that since version 2.10.0 change-log announced MobileVsDesktop feature was deprecated. 

We suppose that since 2.14.1 _Mobile Vs Desktop_ has gone definitively in favor of _Device Detector_ and we missed its "translation" support. 

Do we need to repeat the entire upgrade process, jumping from 2.3.0 to 2.14.1 and finally to 2.16.0? Or do we need more steps?

**Comment by sgiehl** [comment]
The mentioned report isn't available anymore. Instead you should have a report about the device types. 

Example on demo: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=DevicesDetection&action=devices&idSite=7&period=day&date=yesterday

**Comment by tassoman** [comment]
Hello @sgiehl thank you for your fast reply, that report it's empty on our installation.
During upgrade, log didn't shown any error.
![screen](https://cloud.githubusercontent.com/assets/92727/13815239/2b3f0b14-eb8a-11e5-8a8b-238a48b07005.png)

**Comment by sgiehl** [comment]
Is it also empty for a current period? Maybe it is not calculated for older periods

**Comment by tassoman** [comment]
For the current period we can get type, model, brand and resolution correctly.
Because of this we suppose there were a conversion process between 2.10 and 2.14 that we miss. So Now we have the old's report data not fitted to the new device detector report.
My question is about doing a mid-jump to get old _Mobile Vs Desktops_ reports converted in _Device Detector_ using a Piwik version were not yet removed. Is it?

**Comment by sgiehl** [comment]
Did you have the `DevicesDetection`plugin enabled when running 2.3.0?

If you still have all the log data you could also let piwik rearchive all the data, maybe the reports will get visible then.

**Comment by tassoman** [comment]
So you suggest to simpy run:
`php console core:archive --force-all-websites --force-all-periods --url=http://test.server.tld/piwik/`
We didn't ran yet a full re-archive because wasn't mentioned on upgrading steps documentation.

**Comment by tassoman** [comment]
We keep only 45 days of logs because there are about an hundred configured websites. 
The past data is made of reports, we can't just `php console core:archive`.
I think the only way to get device detection converted from mobile vs desktop should be during the upgrade process but we missed the "grace period" of the old feature.

**Comment by sgiehl** [comment]
If DevicesDetection plugin was disabled before there won't be any reports you might be able to use. 
You can have a look at the older archive tables an check if there are any entries for `DevicesDetection_types`

**Comment by tassoman** [comment]
No reason for _DeviceDetection_ plugin deactivation in 2.3.0. As you can see from this production screenshot, it's still there up and running. More, we didn't found any _DevicesDetection_types_ column name in the production 2.3.0 db.

![administration_-_2016-03-17_09_23_10](https://cloud.githubusercontent.com/assets/92727/13840294/ec6451a4-ec21-11e5-9867-95a780edf63f.png)

**Comment by tassoman** [comment]
Please @sgiehl, can you say in which release _Mobile Vs. Desktop_ statistic has been substituted by the _Device Type_ one?

**Comment by sgiehl** [comment]
I guess it was 2.10.0. But after an update the old MobileVSDesktop report should be availabe as Device type. There should have been an update script to provide that change.

**Comment by tassoman** [comment]
First of all sorry for posting last screenshoot. Was a mistake, DeviceDetector plugin wasn't never activated until some days ago my colleague did some tests on plugins.
 
That plugin was in _Beta_ status while in 2.3.0 so anyone did enabled it. Would be a better practice to automatically enable all core plugins for the future.

So now the problem is we still have data of the MobileVsDesktop type in archive report db tables but they didn't changed To _DeviceDetection_types_ after 1.16.0 upgrade script.

Now I have two roads to follow:

- a) review all the update process looking for the missing MobileVsDesktop support then change the past 2y archived reports to detection type
 - b) build a new plugin that extract old widget's code and shows the last 2y of MobileVsDesktop.

In your opinion what to do? Do you have any idea where to look for the update script that upgrades this kind of data? Maybe in the plugin itself? Is there the archive process pluggable by each plugin?

**Comment by tassoman** [comment]
Diving into code :surfer: I found that [getMobileVsDesktop api](https://github.com/piwik/piwik/blob/2.11.2/plugins/UserSettings/API.php#L56-L62) relies on DeviceDetector_type metric since 2.10 as sources said.

I can't find the code who tells to the update scripts how to fetch from userSettings reports and write to DeviceDetector type. Maybe was never written?

**Comment by sgiehl** [comment]
The archives should have been renamed from usersettings to devicedetection. See https://github.com/piwik/piwik/blob/master/core/Updates/2.10.0-b5.php

**Comment by mattab** [comment]
Hi guys, i'm closing, as it's supposed to work.

**Comment by tassoman** [comment]
Ciao! Yes, is a _worksforme_ because I ended up «MobileVsDesktop» has never been recorded but computed on the fly by a function: [getDeviceTypeFromOS($osLabel)](https://github.com/piwik/piwik/blob/2.3.0/plugins/UserSettings/functions.php#L68-L91).

So now I'm writing a Plugin that exposes an API to let OsFamilies get counted as the previous function did. Finally I want to render the result in a Controller and a Widget.

Now I'm stuck in merging old function **getDeviceTypeFromOS($osLabel)** to DevicesDetection's **getOsFamilies()**

I publish my code in this issue in hope to get helped somehow, that's what I've written in my APIs until now: 

```php
<?php

namespace Piwik\Plugins\RerMobileVsDesktop;

use Piwik\Container\StaticContainer;
use Piwik\DataTable;
use Piwik\Plugins\DevicesDetection\API as ddAPI;


/**
 * API for plugin RerMobileVsDesktop
 *
 * @method static \Piwik\Plugins\RerMobileVsDesktop\API getInstance()
 */
class API extends \Piwik\Plugin\API
{
    private $logger;

    public function __construct()
    {
        $this->logger = StaticContainer::getContainer()->get('Psr\Log\LoggerInterface');
    }

    public function viewMobileVsDesktop($idSite, $period, $date, $segment = false)
    {
        $ddOsFamilies = ddAPI::getInstance()->getOsFamilies($idSite, $period, $date, $segment);

        foreach ($ddOsFamilies->getRows() as $row)
        {
            $os = $row->getColumn('label');
            $visits = $row->getColumn('nb_visits');
            $this->logger->debug('«{os}» {vis} visits.',
                [ 'os' => $os, 'vis' => $visits]
            );
        }

        //Dummy Output missing real visits, placeholders are random int
        $table = DataTable::makeFromSimpleArray([
            array('label' => 'Desktop', 'nb_visits' => rand(0,9)),
            array('label' => 'Mobile', 'nb_visits' => rand(10,99)),
            array('label' => 'Unknown', 'nb_visits' => rand(100, 999)),
        ]);

        return $table;
    }

}
```
