### ISSUE TITLE
Notice on undefined index in VisitRequestProcessor.php

### ISSUE THREAD

**Issue by mrjoops** [piwik/piwik#9940]
I updated Piwik from 2.14.3 to 2.16.0 and my log files were filled with this notice :

`PHP Notice: Undefined index: create_new_visit_after_midnight in /usr/share/piwik/plugins/CoreHome/Tracker/VisitRequestProcessor.php on line 158`

When I say "filled", I say 40K notices per hour (my install is fairly large).

I had to downgrade to 2.14.3.

**Comment by sgiehl** [comment]
Maybe your `global.ini.php` wasn't updated correctly. There should be a config value set for `create_new_visit_after_midnight` within the `Tracker` section after update. If not maybe you need to reupload the `global.ini.php`.
