### ISSUE TITLE
Error after installing Piwik 2.16

### ISSUE THREAD

**Issue by irigopou** [piwik/piwik#9941]
Hi,

After installation on the server side Piwik 2.16 (I had 2.15 previously) I tried to access piwik/index.php in my home account but I got the following message:
No entry or class found for 'Piwik\PiwikPro\Advertising'

I have recently changed the ftp password in my server. Could that be the reason? But then the message should have different.

Regards

Ioannis

**Comment by masteranalyze** [comment]
how did you installed ?Can you replicate step by step what you did more exactly?

Why you did not just done an update from 2.15 to 2.16 if you already did have 2.16?Or this problem arrised when you updated from 2.15 to 2.16?

**Comment by irigopou** [comment]
Thanks for responding!About an hour after I posted my initial message I was able to resolve the issue. I tried to post a second message in github to notify you about this but github somehow did not allow me to post it! It gave me the warning: "Sorry! We couldn't save your comment. Please try again." I logged out from github, logged back in and tried again to no avail.
There seems to be a problem with github. I have just tried to post within github these lines you read here, but I received the same message as above.
Anyway, to answer to your question, I clicked on the "update" button that my web hosting provider (WebHostingHub) made available on the Site Management Panel screen. Therefore I cannot know what exactly this "update" button did.
I managed to resolve the problem by downloading your zip installation file and extracting its contents inside the piwik folder in my account.  

    masteranalyze <notifications@github.com> schrieb am 18:01 Donnerstag, 24.März 2016:
 

 how did you installed ?Can you replicate step by step what you did more exactly?Why you did not just done an update from 2.15 to 2.16 if you already did have 2.16?Or this problem arrised when you updated from 2.15 to 2.16?—
