### ISSUE TITLE
vistorlog: provider "unknown" is self-link

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9945]
In vistorlog provider "unknown" is self-link.
imho: if no provider and with this no hompage of provider is available, there should be no active link

please see attachment
![2016-03-17_15h55_06](https://cloud.githubusercontent.com/assets/5681880/13850314/b296bbb4-ec59-11e5-83df-8e71ec48fd32.png)

**Comment by tsteur** [comment]
Thank you @hpvd this is a bug indeed.

**Comment by hpvd** [comment]
solved - thanks!
