### ISSUE TITLE
Dashboard does not load after disabling Overlay plugin

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9946]
Looks like there's some JS code missing after disabling the Overlay plugin. See:
`Uncaught ReferenceError: DataTable_RowActions_Overlay is not defined`

It's a regression because it worked in 2.15.0.

**Comment by sgiehl** [comment]
That already seems to be fixed in master. Can't reproduce that on my local instance.

**Comment by tsteur** [comment]
Thank you for creating the issue. It was fixed as part of this issue: https://github.com/piwik/piwik/issues/9704
