### ISSUE TITLE
Rendering Bug?

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#9950]
After a while, the page sometimes becomes just garbled. I have never seen this anywhere with my PC/Browser (Chrome) (I cannot reproduce it), except on Piwik installation. Restarting the browser resolves the problem. Could this be related to Chrome? Memory Page issues (PC)? Really not sure. Again, never happens on other websites, just in Piwik tab(s) (always using latest beta recently).

![2016-03-19_153819](https://cloud.githubusercontent.com/assets/5383059/13899227/055b7a5c-ede9-11e5-9638-ac7fe1d78022.png)

**Comment by sgiehl** [comment]
What zoom level are you viewing the page with?

**Comment by dev-101** [comment]
Normal 100%, of course. But, I do use zoom on some other tabs occasionally, not sure if that might be the cause, since it never happened on other sites/tabs.

Interesting enough that hard reload and disabled caching does not help, only browser restart does the trick.

I know that it will be impossible to catch, find true cause and how it occurs, but had to post it here anyway.

Thanks
