### ISSUE TITLE
Revealing debugging information in errors messages

### ISSUE THREAD

**Issue by jaceklubzinski** [piwik/piwik#9960]
Some of the debugging informations like paths and database name can be available for everyone.
It would be best if on the page appears only information about checking logs.
![piwikpath](https://cloud.githubusercontent.com/assets/13852206/13992986/9d6bcd00-f11e-11e5-83eb-2e2a83f329a3.png)
![piwikdbinfo](https://cloud.githubusercontent.com/assets/13852206/13992987/9d851aa8-f11e-11e5-9207-0d5523881b2c.png)

**Comment by tsteur** [comment]
I think this is behaviour is currently wanted and helpful for most users and we should keep showing these messages. Important is that we don't leak any passwords. In above case we could maybe hide the host and database name.

If someone wants to hide further details we could trigger an event so anybody could modify error message and title if needed. So far it is only possible to modify the rendered error page and this is not really practical to change error messages within a rendered HTML page.
