### ISSUE TITLE
Don't try to display a custom logo or favicon if they don't exist

### ISSUE THREAD

**Issue by ksubileau** [piwik/piwik#9966]
Hi,
In the general settings page, under the branding settings (Administration > General Settings > Branding), when no custom logo or favicon has never been used, Piwik generates two requests to missing files (_/misc/user/logo.png_ and _/misc/user/favicon.png_) and displays broken image icons:
 ![piwik-broken-image](https://cloud.githubusercontent.com/assets/3837104/14066597/7aa70f90-f44e-11e5-862f-26bce914be49.png)
As we can see in [this template file](https://github.com/piwik/piwik/blob/af7997f/plugins/CoreAdminHome/templates/generalSettings.twig#L214) at lines 214 and 220, there is indeed no check on the actual existence of these files : the img tag is always generated.

I think Piwik should verify the existence of the logo and favicon files to prevent Web browsers to attempt to access a missing file.

By the way, we can see that the server returns in this case a 403 error instead of 404, probably because of the .htaccess file inside the misc directory, which denies access to all files by default.
![piwik-broken-image-2](https://cloud.githubusercontent.com/assets/3837104/14066598/7ac00a4a-f44e-11e5-8f1d-d12103c38f21.png)

**Comment by tsteur** [comment]
> By the way, we can see that the server returns in this case a 403 error instead of 404, probably because of the .htaccess file inside the misc directory, which denies access to all files by default.

Are you using Apache? The `.htaccess` should specifically allow these files in `misc/user`.

**Comment by tsteur** [comment]
Also the files should exist by default unless they were deleted.

**Comment by ksubileau** [comment]
Yes I'm using Apache. I have an .htaccess file under the misc folder with the following content, which cause the 403 error : 
```apache
<Files "*">
<IfModule mod_access.c>
Deny from all
</IfModule>
<IfModule !mod_access_compat>
<IfModule mod_authz_host.c>
Deny from all
</IfModule>
</IfModule>
<IfModule mod_access_compat>
Deny from all
</IfModule>
</Files>
```
It seems that the current code does not generate this file in this folder, but I don't remember having created it manually. Maybe it's a relic of an older version, as the initial installation on my server goes back to December 2012 and was updated regularly until the current version.

Anyway, this isn't the main subject for which I opened this issue :) If I remove this .htaccess file, I still get a 404 error because Piwik tries to load the images even if they don't exist.

You say that they should exist by default, but from where should they come from ? I don't see them either on [the repository](https://github.com/piwik/piwik/tree/b12f74f4a782996d4ce9db65c9579f90a2aa6965/misc/user) nor in the [downloadable archive](http://piwik.org/download/). Are they generated or copied at setup time ?
AFAIK they are created only the first time the user configures a custom logo or favicon, isn't it ?

**Comment by tsteur** [comment]
True, they actually don't exist. I forgot that I had custom logo uploaded. 

I presume the problem is, when not showing the `<img>` and then uploading an image, the instant preview would not work. So we also need to update JavaScript to create this image element in case it is not there or solve it differently.

**Comment by ksubileau** [comment]
You're right, I forgot the JS. The instant preview is broken with the commit mentioned above.
The image source is fetched from the `src `attribute, so it's not so easy indeed.

Maybe we could always create the `<img> `tag with a `data-src` attribute giving the image path (without the cache buster), and generate the `src `attribute on server-side if the images exists or on client-side after an upload (based on the path given by the `data-src` attribute) ?

Thus we avoid depend on another element to generate and position the images.

**Comment by mattab** [comment]
Hi @ksubileau if you can test it, and create a Pull request, we would be glad to investigate and merge it!

**Comment by tsteur** [comment]
@ksubileau sounds like a good idea :+1:

**Comment by trusteddigital** [comment]
How about the 403 error. I actually have uploaded the images but it doesn't show them because it's showing the 403. Has one of the htaccess files been kept from a previous version but it no longer needed? There's one in /misc/user/ but also one in /misc/ which dates back to 07/08/2013 in my installation. Should this be modified or deleted?

**Comment by trusteddigital** [comment]
I've answered my own question. On the current repository, neither of these .htaccess files exist so I'll remove both for now.

**Comment by tsteur** [comment]
It's possible that some files were not writable in that directory and then it couldn't update or remove an `.htaccess` file. The updater does - I think - not show an error in this case.

**Comment by ksubileau** [comment]
@trusteddigital The .htaccess file under /misc/user is generated at setup and upgrade times by [the ServerFilesGenerator class](https://github.com/piwik/piwik/blob/4c334be38b8426f54a7e6ab314a82ec25ce49c81/plugins/Installation/ServerFilesGenerator.php#L49)
But as I said earlier, it seems that the .htaccess file of the misc folder is a relic of an older version. The fact that you also have this file causing the same 403 errors seems to confirm this hypothesis.
