### ISSUE TITLE
When changing segment definition, inform the user that past data will be cleared

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9984]
When segment definition is changed, all previous data is deleted as it is not matching the definition anymore. Users could use a message that would tell about this fact.

**Comment by sgiehl** [comment]
Wondering if we should simply add a small note within the segment editor or if it would be better to show a confirmation box. Last solution would ensure the user is clearly notified about it.

**Comment by gonerator** [comment]
Definitely the latter, let's show message box with confirmation when data deletion may actually occur.

**Comment by mattab** [comment]
Note that data is not actually deleted, but since the segment definition changes then the archives for the old segment won't be read anymore (unless the segment is reverted back to the old definition in which case the previous data will be re-used again.
