### ISSUE TITLE
Visitors Overview - Missing Report Pictures

### ISSUE THREAD

**Issue by keltik85** [piwik/piwik#9999]
My Piwik instance is not rendering the images in the Visitors Overview:

![image](https://cloud.githubusercontent.com/assets/13469004/14254777/8be450b2-fa91-11e5-82b3-de9a28ef9df8.png)

This is the Network access log of Chrome:

![image](https://cloud.githubusercontent.com/assets/13469004/14256357/f55b776c-fa98-11e5-8c6e-e2fb38375325.png)

I already have done the following (edit `config.ini.php`, add disable_merged_assets ), but of no avail:

http://piwik.org/faq/troubleshooting/faq_135/

What else can I do?

**Comment by tsteur** [comment]
Do you have access to the server logs?

**Comment by mattab** [comment]
See https://piwik.org/faq/troubleshooting/faq_34/

**Comment by keltik85** [comment]
> Do you have access to the server logs?

Yes, and I have also activated the piwik.log like this: http://piwik.org/faq/troubleshooting/faq_115/ .

I can see the Piwik log like this, but its empty:
```
root@bb8b20685309:/var/www/html# cat tmp/logs/piwik.log | grep ERROR
root@bb8b20685309:/var/www/html#
```

To see the access and error log of apache I can do this:    
```
[root@localhost templates]# docker logs piwikcontainer | grep Error
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 05 06:17:22.297939 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.19 configured -- resuming normal operations
[Tue Apr 05 06:17:22.297995 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```




> See https://piwik.org/faq/troubleshooting/faq_34/

Thanks for the advice. I have installed the `php5-gd` library, but still the images dont, show up. My Dockerfile looks like this:
```
FROM php:5.6-apache
MAINTAINER "<max.payne@abc.org>"
COPY ./templates/apache2files/piwik /var/www/html/
COPY ./templates/php.ini /usr/local/etc/php/
RUN chmod 777 -R /var/www/html/
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install mbstring
RUN apt-get update && \
         apt-get install -y php5-gd --no-install-recommends && \
         rm -r /var/lib/apt/lists/*
```
